== Further Testimony to Truth / Revived Out of the Ruins of the Apostasy

[.heading-continuation-blurb]
Or several things opened from the spirit of truth,
touching the way of life and salvation;
which will reach to the witness in the hearts of those whose spirits are quickened,
and whose ears and understandings are opened by the spirit and power of the Lord.

[.heading-continuation-blurb]
Written in a deep sense and tender love,

[.section-author]
By _Isaac Penington_

[quote.section-epigraph, , Isa. 60:1-3]
____
Arise, shine; for thy light is come, and the glory of the Lord is risen upon thee.
For behold, the darkness shall cover the earth, and gross darkness the people;
but the Lord shall arise upon thee, and his glory shall be seen upon thee.
And the Gentiles shall come to thy light, and the kings to the brightness of thy rising.
____

[quote.section-epigraph, , Isa. 2:5]
____
O house of Jacob! come ye, and let us walk in the light of the Lord.
____

[.section-date]
published posthumously in 1680

[.centered]
=== Preface

Oh! how excellent and precious is the name of the Lord, in this our day,
among his people, whom he hath gathered out of the worldly spirit unto himself,
and whom he mightily defendeth in that wherein he hath gathered them!
Insomuch as it may now be said inwardly, as it was of old outwardly,
Psalm 76. "`In Judah is God known; his name is great in Israel.
In Salem also is his tabernacle, and his dwelling-place in Zion.
There brake he the arrows of the bow, the shield, and the sword, and the battle,
Selah.`" Oh,
what mighty things hath the Lord God done in and for the spirits of his people!
How hath he scattered the darkness from about them,
broke the chains which held them in captivity!
How hath he risen up against all the enemies of their souls, discovered their snares,
snapped in sunder the weapons of war,
which the spirit of darkness hath formed and lifted up against them!
And how hath he preserved them in life, in peace, in purity, in holiness,
in his power and dominion (over that spirit, and the devices thereof), to this very day!
He lives and reigns in power over all; and because he lives, we live also;
and because he reigns,
those that are in his life and Spirit partake of his holy reign and dominion (over sin,
hell, death, and the powers of darkness) with him.
Lo! this is our God; this is he whom we have sought after, and waited for;
and now his power is made manifest, now his righteousness and salvation is revealed,
how can our souls but be glad and rejoice therein!
Yea, how can we conceal the good tidings of the day of our God,
and of the gospel of his salvation, which hath arisen and broke in upon us!
How can we but desire to awaken the minds of men out of their sleep,
and call upon them to shake off the drowsiness and blackness of the night,
and to lift up their eyes towards the hill and mountain of God`'s holiness,
that they also may behold the beauty of his day in others,
and wait for the springing of his life and glory in themselves!

Now there is somewhat revealed of God, of his own nature, power, and Spirit,
wherein we have met with him.
To this we invite, of this we speak, concerning this we testify,
as being that which the Father will honor, and wherein he hath and will appear.
It is a poor, weak, low thing to consider of,
or behold with the eye and understanding of man; but there is the riches, the glory,
the life, the righteousness, the peace, the joy,
the everlasting power of the kingdom in it;
and to them that receive it in the demonstration of God`'s Spirit, and in the love of it,
it is the wisdom of God and his power to the redemption and salvation of their souls.
Indeed of all the wise builders (out of the true
sense and power) it is rejected at this day,
as it always was of old; but to us who are called of God, taught by him,
who have received an understanding from him, etc.,
we know the value of that which comes from him,
being instructed by him not to judge according to the appearance,
but to judge the righteous judgment; and in the righteous judgment,
in the balance of the sanctuary,
we find this little despised light to be elect and precious, even the foundation-stone,
the corner-stone, and the top-stone of the building of God.
And this we testify to men in true love,
and from certain knowledge and experience which we have received from him that is true,
and hold in him that is true.

Now this precious pearl (of which we testify) lies hid deep within;
and thither must men come to know it, to purchase it, to possess it;
and thither it is the desire of our hearts to bring men.
Nor do we open the thing of God before men to this end,
that they might get a knowledge thereof into their brains, and feed on it there;
but through tender love we bring these things a little
into the very view of men (as the Lord enables us);
not that they might stick there,
but that having a taste of the excellency and beauty of truth,
they might be inflamed (with desires after it) to travel thither, where it is to be had.
Therefore dwell not in the notion,
delight not in the outward knowledge of the thing
itself (though the knowledge be ever so sweet,
pleasing, satisfactory, and demonstrative to the mind);
but come to the everlasting spring.
Feel the measure of life in thy particular,
and that will lead thee to the spring of life,
from whence the measure comes as a gift from the Father to thee,
to bring thee to the Father.
And singly for this end have I been drawn to write what follows, in service to the Lord,
in faithfulness to him, in dear love to the souls of men,
especially of those who have formerly been travellers,
and have felt somewhat of the Lord,
and yet retain desires and breathings in their hearts after him.
Oh that the Lord would touch their spirits, discover to them the way everlasting,
and lead them therein to that which their souls darkly desire and seek after;
to which there is no other way than that which hath been from the beginning,
only there have been various discoveries and manifestations of the one way!
But what greater discovery can there be than of the thing or seed itself,
which the Lord hath been pleased to make manifest in this day of his glorious mercy,
love, and power, whereof he hath raised up many witnesses,
whom he hath enabled (by his Spirit and power) to give a living, clear,
certain testimony to?
Happy is the ear that hears! for that also must be of God,
as the message and messengers are known to be.

[.centered]
=== A Further Testimony to Truth

[.inline]
==== Some _Queries_ concerning Christ`'s righteousness,--how it justifieth; whether as inwardly revealed and dwelling in the heart, or only as imputed, or both.

[.numbered-group]
====

[.numbered]
_Query 1._ Is not Christ the righteousness and justification of the soul with God?
Is not he made of God unto us righteousness,
and are not we made the righteousness of God in him?
How is this done?
Is it not by being ingrafted into him--covered with him?
Is this a mere imputation?
or is it not rather a bringing the soul into the thing itself, and a drawing his nature,
life, and Spirit over the soul, which was and is always righteous in itself,
and so accounted with God?
And he that is found in him, clothed with him, emptied of himself, and filled with him,
is he not really righteous in the sight of God?

[.numbered]
_Query 2._ Is not the principle of life, which is from Christ,
of the same nature with Christ?
is it not also holy and righteous?
yea, is not Christ the fulness of it?
And he that receiveth this principle, doth he not receive life, receive Christ,
receive righteousness?
Can the righteousness of Christ be separated from the seed of his life, nature,
and Spirit?
Can a man deny himself, go out of himself, give up to that, and be found in that,
and not found in the righteousness?
or can a man come to righteousness by imputation without that?

[.numbered]
_Query 3._ This principle or seed of life being from Christ, of Christ,
and one with Christ in nature, though not of the same stature and fulness,
yet hath it not the property and virtue of all that is of Christ in it?
Do not all the promises belong to this seed, and go along with this seed?
Doth not all that is good in man spring up from this seed?
He that receiveth this, doth he not receive that which is righteous,
and which makes him righteous, so far as he is of it, and in it?
yea, the sacrifice of Christ in the flesh, the virtue thereof,
the forgiveness of the Father for the sake of his Son,--doth it not go along with this?
and is it not accepted for that man who is found here,
and his iniquities (which he committed formerly) freely forgiven him for his name`'s sake?
Yea, are not his sins afterwards also blotted out upon the same terms,
he returning to this, abiding in this, and being found in this,
and wherein the remission of sin, and the power against sin,
is alone to be felt and received forever?
So here is the imputation in its right place,
and the right use and pleading of the sacrifice of the Son, which here,
in this its proper place, and in this state, prevails with God, and not otherwise.
For the kingdom, the righteousness, the peace, the joy, the power thereof,
etc. is placed by God in this seed, which is as a grain of mustard seed:
and he that ever finds it must so find it;
and he that ever joins to it must so join to it;
and he that ever receiveth it aright must so receive it.

[.numbered]
_Query 4._ Is not he that is born of God new created in Christ Jesus?
and is not the new creature and new creation righteous in the sight of God?
When Adam was created at first, he was created in God`'s image;
and was not that image righteous, and he righteous in that image?
And when man is regenerated, renewed, brought again into the image,
is not the image again holy and righteous, and he in the image?

[.numbered]
_Query 5._ Is not faith the gift of God?
And is it not holy, spiritual, and righteous in its own nature,
and in the creature to whom it is given?
And being given to the creature, is it not owned by God as such,
and so justified in the creature?
Is not the faith which is of God as righteous as
the unbelief from the root of bitterness is unrighteous?
And doth not God own and justify that as righteous,
as well as condemn and reject the other as unrighteous?

[.numbered]
_Query 6._ Is not the obedience of the soul in Christ,
and from the principle of his life in the soul, and through his Spirit, righteous?
nay, as righteous and justifiable in the sight of God,
as the disobedience of the first nature is unrighteous?

[.numbered]
_Query 7._ Are not all the works which are wrought in God righteous?
and doth not he that doeth truth bring them to the light,
that it may be made manifest that they are wrought in God? John 3:21.
Now there is no condemnation, but justification,
to the deeds that are wrought in God; as there is no justification,
but condemnation to the works that are wrought out of him.

====

So that here now he that is indeed of God, he that is new created in Christ Jesus,
he knows the Father and fountain of righteousness, the Son of righteousness,
the righteous seed, the righteous faith and obedience of the seed,
and the works which are wrought by the power, and in the Spirit,
which being brought to the true light, are always justified by it.

[.inline]
=== Concerning the true Church and Ministry

There is a great noise in the world about church and ministry.
Many are affirming which is it, and many are doubtful and inquiring about it;
and many are truly and groundedly satisfied,
having received the knowledge of the thing from God, who is not deceived about it,
nor deceiveth any, but giveth the true understanding of these and other things,
to them that wait upon him aright; to wit, in his fear,
and in the silence of the fleshly wise part before him.
Now, I have a testimony to give concerning these things,
which that ear which is of God can hear, and to that I desire to speak.

That is the church which is the spiritual body of Christ.
The church is Christ`'s spouse, he the husband.
The head is living, and so are all the members of the body.
The head is anointed,
and the oil wherewith the head is anointed runs down from the head upon all the body;
and that upon which the oil runs not is none of the body.
Now, no outward thing can make one a member of this body;
much less can any outward thing, way, profession, or practice make a church.
The church under the law was made so by outward things, by an outward gathering,
an outward circumcision, an outward law, an outward worship, etc.;
but the gospel is a state of substance, a state of the invisible things,
of persons invisibly gathered by the Spirit into the life and power of God,
inwardly circumcised, inwardly baptized with the Holy Ghost and with fire,
inwardly worshipping in Spirit and truth,
bowing at every sound and name of the Lord Jesus:
and what is of an outward state here is brought forth
and preserved by the power of the inward appearing,
and dwelling in it.
So that this is the church now,--a people gathered by the life and Spirit of the Lord;
a people gathered by the power from on high, abiding in the power, acting in the power,
worshipping in the power,
keeping in the holy order and government of life (both inwardly in their own hearts,
and outwardly in their assemblings and walkings) by the power.
Christ was made a king, priest, and prophet, not after the law of a carnal commandment,
but after the power of an endless life; and in this power he gathers, governs,
and preserves his church, and ministereth from and by his Spirit and power in it.
Now, find this power of the endless life, find a people anywhere gathered by this power,
and in this power; there is the church, there is the living body,
there is Christ the head, whose dominion and strength is over all,
against whom the gates of hell cannot prevail.

And so for the ministers of this church.
The same thing that gives to know the church gives to know the ministers thereof;
for they also are of God, called by him, receiving power from him,
and abiding and ministering in that power.
So that there are three things requisite to a true ministry,
without which they cannot be right, or execute their office rightly.

[.numbered-group]
====

[.numbered]
1+++.+++ They must be called by God.
The ministry under the law,
this was their warrant,--they were called and appointed of God thereunto.
Christ himself took not the honor to himself,
but he was called of God to this priesthood, as Aaron to his.
So the apostles and ministers, in the first publication of the gospel,
were called and appointed by Christ.
And when the everlasting gospel is again to be preached, God sends his angel with it,
as Rev. 14:6.

[.numbered]
2+++.+++ They must receive ability and power from God.
The elders that were to help Moses were to receive of his spirit.
Under the law, the priests were to be anointed with the outward, literal oil,
and the ministers of the gospel are to be anointed with the inward, spiritual oil.
Their work is spiritual; and how can they perform it, but by the anointing,
by that presence, guidance, life, virtue, and power of the Spirit,
putting itself forth in them?
The apostles themselves, who had been taught by Christ,
who knew his conversation and doctrine,
who were eye-witnesses of what they were to publish,
and had received an authority and commission from him,
yet were not to go forth merely upon this call and commission,
but to wait for power from on high; and when they had received the Spirit and power,
then they were made able ministers of the New Testament, not of the letter,
but of the Spirit and power.

[.numbered]
3+++.+++ They must abide in the power, keep in the power, feel the motion, virtue,
and assistance of the power, in all their work and service.
They must neither pull down, nor build up, nor watch over,
or oversee the flock in their own wisdom, in their own spirit, in their own wills;
but in the anointing, in the light and guidance of the Lord.
This gathering, this building, this work of the Lord, begins out of flesh, out of man;
and flesh must be kept out of the whole carrying on of it.

====

And indeed, unless the ministers of the gospel be in the Spirit, in the life,
in the power, how can they minister to the nature, to the spirit, to the life,
in the body?
yea, so much as to the least member in the body?
They may minister outward knowledge to the man`'s wisdom, to the man`'s understanding;
but that is not the food that is to be ministered to the church,
nor is that part in man to be fed by the true minister.
But they are to minister life (living food) from the living fountain, from the head,
from the Spirit of Christ in them, to the particular members under their charge;
and so are to be good stewards and shepherds to the flock,
giving every one their proper portion in due season.

It was no small matter to be a minister under the law.
It was easy to err, and minister amiss then.
It was easy erring from the letter,
unless great care and circumspection was used to keep strictly to it.

But it is a much more weighty thing to minister under the gospel, to receive the power,
to minister in the power, to that which is begotten and born of the power.
And this is precious, and (without controversy) of God, wherever it is found.
But they only that are of God can hear and receive this ministry
(as 1 John 4:6). The uncircumcised ear cannot hear here,
nor the wise and knowing according to the flesh.
The wisdom of God is foolishness to him,
and the mysteries of his kingdom (the mystery of his life,
and the true godliness) are riddles, and direct madness to the eye of his wisdom:
so far is man degenerated from God,
and bound down with chains of darkness and corruption.
And he that would know the true church, or be of it,
and hear the voice of God in his true ministry,
must first take up the cross to that part in him which is not of God,
and receive from God the eye which sees, and the ear which hears.

[.inline]
=== An _Objection_ concerning the Newness of the Way of Truth, answered: With a tender, expostulating Exhortation

[.discourse-part]
Objection.
It is objected against us, that this which we testify to, hold forth, and practice,
is a new way, sprung up of late,
never known nor heard of in the world till some few years ago.

[.discourse-part]
Answer.
The light eternal, when it shineth out of the darkness,
after the great apostasy from the Spirit and life of the apostles,
is new indeed to those that were overwhelmed and buried in the darkness of the night,
and so never saw or heard of it before; but it is not new in itself,
but the same that it was from the beginning.
This seed of life, this seed of blessing,
is the same that was promised at first to bruise the serpent`'s head.
The same which was promised to Abraham, when the gospel was preached to him.
The same that saved all (that believed in it) under the law;
for it was not the types and shadows, and outward ordinances, which saved the soul then,
but the seed, who was the Saviour from the beginning, and is the Saviour all along,
even to the end: and it was the same which was the gospel in the days of the apostles.
They preached the seed also, the word of faith; Christ the way, Christ the power.
Yea, all along the times of the apostasy,
this was the thing that preserved the witnesses,
saving them from being swallowed up in the darkness,
and keeping them alive in their testimony.
And there is no other thing held forth now by those who are in the truth,
and raised up by the power of God in it to give testimony to it.
This is it from whence life hath sprung in any that have felt life,
in all ages and generations.
This is the root and offspring of David, the bright and the morning star.
This is the desire of all nations (oh that they knew their desire),
and their saving health too, without which they can never be healed!
And, O ye! who ever felt any thing of God at any time, which was true,
either in reading the Scriptures, or hearing a ministry, or in private breathings, etc.,
this was it which gave you to feel in that state, to desire after the Lord,
to turn from vanity, to long for communion with him, etc.
Oh that ye were so far in it now, as ye have been in times past!
For there is no other thing we testify to you of (or desire to draw you
to) than that which was the root and strength of your life in those days.
I remember that time very well, and what I was and felt among you,
nor can I deny it at this day, but know that it was of the Lord; yea,
my soul blesseth his name in the remembrance of it:
but he that sticks in the letter of that (having lost the
life thereof) is in a dead state before the Lord;
and in that dead state hath not the true sense and feeling,
and then must needs err and mistake concerning the truth,
and (in that error) make use of his wisdom and knowledge to resist and oppose it.
And this brings more death and darkness upon the soul,
insomuch as the very light there becomes darkness, and the very life dead;
and if they could truly look inwards, they would see that they are not now there,
what once they were, nor their duties or ordinances (as they account them) such;
but a blasting and withering is come upon them, from the Spirit and power of the Lord,
and they have lost their beauty and freshness, to all that with a true eye behold them.
Therefore come back to the life; know that which formerly gave you life.
Is it removed?
stick not behind, but follow on.
Oh, know the Lamb, who is the leader!
And this is the great duty of duties to follow him whithersoever he goes.
He may in his tender mercy visit in Egypt, in Sodom, in Babylon:
but these are not the places of his rest, nor so to be esteemed,
because he once appeared, visited, touched, refreshed the soul there.
But his dwelling-place is Zion, his holy city is Jerusalem,
where the Christians dwelt with him before the apostasy,
and where those that are redeemed out of the apostasy, are again to dwell.
For the darkness of the night is not to diminish or take
away any of the beauty or brightness of the day forever;
but the brightness and beauty of the day, in its rising and glorious growth,
is to overcome and swallow it up.
Therefore lose no more time in disputings, in thoughts, in reasonings, in consultings,
with that which will never advise the soul for its good; but wait on the Lord,
that ye may come (through his leadings) to the true sense of his seed,
to the feeling of the nature of his eternal light and life in the heart;
and that will put an end to disputes; yea, scatter the disputing mind,
and powerfully determine the controversy in the pure
sense and demonstration of the Spirit.
And he that knoweth any thing of this, let him abide here, wait here, live here,
dwell here, and breathe to the Father here,
watching narrowly over that which would lead from hence,
and draw the mind into another way, wisdom, and spirit.
And thus, O poor soul! if the Lord touch thine heart, and open thine eye,
thou wilt see thy beloved, even the choicest among ten thousand; whom none can parallel,
whom nothing is like to for excellency of nature,
nor is there any can do for the soul as he!
It is felt, it is experienced, it is testified unto you in the love, and in the truth:
oh that ye could hear!
They are not the words of the letter, nor the observation of all that is in the letter,
that can give life; but his voice gives life.
The words that he speaks (at any time) are Spirit and life; and if he speak them not,
but letter.
So this is it we live upon; not the bread which we can make;
not the things we can gather or comprehend from the letter;
but the words which proceed from the mouth of God.
Now, this seed is his mouth, in and through which he speaks to our souls,
who fear before him, and wait upon him, in his own eternal and everlasting ordinance,
at the door and posts of the everlasting wisdom.
And here we meet with all in substance, in life, in freshness, in purity, in power,
that ever we met with of God;
and we meet with somewhat more also than we formerly met with.
And this testimony is given forth to you in the love of God, from his tender bowels,
which know your present state, your wants, your wanderings,
your deep prejudices and settled hardness against his truth;
yet he remembers the days of your youth, and cannot give over seeking after you,
and crying unto you.
Oh, when will ye turn, when will ye hear, when will ye wait to feel life in the Spirit,
and not increase death in you from the letter!

=== A Caution

[.section-summary-preface]
To those who are at any time touched with the power of Truth;
how they afterwards hearken to and let in the enemy,
and so thereby have the good seed stolen away, the true sense lost,
and the mind filled with prejudices and stumbling-blocks instead thereof.

The Truth of God, being received into the inward parts, is found to be of a living,
powerful nature, working mightily there for the cleansing and redeeming of the hearts.
Yea, this is certainly witnessed, that as the mind joined to deceit is thereby defiled,
so the mind joined to the truth of God is, by its power and virtue, purified.

Now, having felt this,
and being filled with the love and good-will of God to the souls of others,
how can we but testify it to others,
who stand in need of God`'s truth (and its cleansing property and virtue) as well as we;
especially being thereunto moved and drawn by the Spirit of the Lord?

Now, when the Lord giveth forth the sound in its power and life,
it many times pierceth deeply through the earthly veil, and reacheth to its own; which,
being reached to, answers to the testimony, saying, It is Truth.
So here is a beginning of the work of God in that heart,
the soul being touched with his truth, feeling it inwardly,
and yielding in some measure to the overcoming virtue and power of it.

But then comes the subtle one,
whose design and labor is to undermine and overturn the work of God in the soul;
and he begets doubts and jealousies and questionings, both concerning us,
and concerning the doctrine taught by us, to suggest into the mind, as if it were not,
nor indeed could be, of God:
and so bringing the dispute and determination into
another part than where truth got entrance,
he easily sways the mind to determine against its own former feeling,
and to turn from that work which was begun to be wrought in it by God,
and from the worker also.
And thus many poor hearts are entangled, and carried back into captivity,
who began to feel the stirrings of truth in their hearts (wherein is the
power of redemption) which would have redeemed them as well as others,
had they received it in the love of it, and become subject to it.

Oh! it is a precious thing to receive from God a spirit of discerning,
which gives ability to discern his Spirit from the spirit of deceit; yea,
it is impossible to be preserved in the right Spirit and way, but as this is felt.
For how can the Lord be received in all the motions and operations of his Spirit?
or how can the contrary spirit be turned from in all its subtle devices, twistings,
and reasonings in the mind, unless there be a discerning, in the true light of the Lord,
what is of the one, and what of the other?

And ye that would not be deceived, sink deep beneath the thoughts, reasonings,
and consultations of the earthly mind,
that ye may meet with somewhat of the kingdom and power
(which carries its own evidence and demonstration with it),
and may be gathered into it, and find a sense, knowledge, and judgment there,
which never was deceived, nor can deceive.
Know the elect of God, which the deceits pass over, and cannot reach;
for its nature and birth is beyond them.
It came from the light of the Father.
It lives in the light of the Father.
It sees in that light; yea, there its judgment and understanding is,
where deceit never had power to enter.
But he that considers as a man, sees as a man, judges as a man,
concerning the things of God, by what he can gather out of the Scriptures,
or conclude from his own sense, knowledge, and experience, he may easily err; yea,
indeed, he is in the way of error in so doing.
For the pure religion, the pure knowledge, the right judgment, the living faith,
begin in the power and demonstration of the Spirit; and these are its limits,
out of flesh, out of man, out of his will, out of his wisdom,
out of the compass of his comprehension.
And he that passeth not these bounds never meets with the life, power,
and virtue of truth.
He may meet with a body of notions and formed knowledge,
wherein he may tell of the fall of man, and restoration by Christ, and very exactly,
according to a literal description; but the life, the true knowledge,
the powerful virtue, is another thing, and is met with in another country,
whither man cannot travel, but as he is stripped of himself, and new formed,
made and brought forth in another.

Oh! therefore, ye that desire after the Lord (that would be his,
that would feel him yours, that would know his truth in the life and power of it),
wait for the demonstrations of his Spirit; learn to distinguish inwardly,
between his teachings from his Spirit,
and the teachings of another spirit from the letter.
For it is so indeed: that other spirit would have taught Christ so;
and he will teach any one else so, that will hearken to him.
Now, he that is taught so, and follows such teachings, wanders from God,
is not accepted with him, but follows that which leads from him,
under a pretence and appearance of leading to him.
And here hardness and deadness grow and increase,
the soul being turned from that which is living, and alone able to give life.

[.discourse-part]
Question.
But how may I do, who am weak, and full of doubts and fears,
to keep in the sense of truth, and to come to a certainty that I am not deceived therein?

[.discourse-part]
Answer.
To thee, who puttest this question in the uprightness and simplicity of thy heart,
I have somewhat to say.

[.numbered-group]
====

[.numbered]
1+++.+++ Mind how thou wast touched, mind how thou wast reached,
observe what ear was opened in thee,
and breathe to the Lord to keep that ear open in thee, and the other shut.
For this I can assure thee in the truth of God,
that with that ear which the Lord opened to truth
(which thou feltest his Spirit unlocking in thee,
and letting in truth by), I say,
with that ear thou shalt never be able to let in any thing afterwards contrary to truth.
But if the enemy can open the other ear, that will hear his prejudices, his jealousies,
his doubts, his fears, his temptations, and let them in,
to thrust out that which entered at the other ear.
Now, canst thou not distinguish, O poor soul,
(a little to help thee) between that which brought some sense of truth into thee,
and that which riseth in thee against truth?
Oh, fear before the Lord! oh, watch and pray, that when the tempter comes,
thou enter not with him into temptation,
and so lose thy union and growth in that which is invaluable!

[.numbered]
2+++.+++ Keep thine eye and heart upon the preciousness of what thou feltest.
Oh! remember how fresh, how warm, how living it was; how it reached, how it overcame,
how it melted.
The remembrance of this (cleaved to in the mind) will be a strength
against the temptations and subtle devices of the enemy.

[.numbered]
3+++.+++ Meddle not with the things that the enemy casts into thy mind.
Consider not whether they be so or no.
He that considers of a temptation (in many cases) hath let it in, and is overcome already.
When Eve did but hearken to what the serpent said, how soon was she lost and gone!
The enemy many times brings temptations beyond the state, capacity,
and ability of the soul to determine.
These things, at present, are too high for thee.
Thou hast not yet received a proportion of life from God to determine them by;
and if thou run beyond thy measure, and determine things in thy mind,
which as yet are beyond thy reach, thou must needs run into the snare.

[.numbered]
4+++.+++ The present determining of these things would not be of so great advantage to thee,
as thou mayst apprehend.
Why so?
Because the enemy hath many temptations and devices of the same kind (as
well as of other kinds) which he would bring one after another.
And when he brings a second, a third, etc.,
that which engaged thee to consider of the first,
would engage thee also to consider of the rest.
And if thou couldst find one answered, and not the other,
that would appear to thee as so much the more weighty,
and thou wouldst hardly be able to escape consenting to the tempter therein.
Therefore the way is to keep out of him,
in the upright sense of what the Lord wrought in thee; for so far he is with thee;
and abiding there, thou art out of the enemy`'s reach.
But being drawn by the enemy to consider of things that are out of thy reach,
thou therein layest thyself open to his snares and betrayings.

[.numbered]
5+++.+++ Mind what was forbidden thee, or required of thee in that time,
when thou feltest the warmth from God.
For there is then a heavenly voice, and a heavenly vision most commonly in the heart,
though the enemy turns the mind, as much as may be, from heeding it.
There is then oftentimes somewhat of the worldly nature and course discovered,
or somewhat of God`'s will made manifest; somewhat that thou doest, or hast done,
which then thou seest to be not of the Father, but of the world;
and somewhat perhaps of the Father,
which thou knowest thou oughtest to become subject to, but thou art afraid of the cross,
or shame, or would fain have some more clearness first.
Oh! call this to mind afterwards: and if ever thou wouldst receive life,
and come into union with God`'s truth, and receive his Spirit and power,
and be established therein; become obedient to the heavenly vision!
Consult not with flesh and blood, but enter into the obedience of that very thing,
which was forbid or required, be it little or much.
This is the right way, this is that thy mind should be exercised in.
And if thy mind be exercised faithfully here,
the Lord will strengthen thee against the tempter,
when he comes with his temptations and subtle objections.
But if thou falter here, and become unfaithful in the little,
thou art not like to meet with more; no,
nor with the preservation of the Lord in that little.
And indeed this is the cause of the miscarriage of many,
because they receive not that little which was made manifest, in the love of it;
but had pleasure in the unrighteousness,
and so lingered in pleasing the spirit of the world, both in themselves and others,
when they were called by the Lord to quit it, and travel out of it.

[.numbered]
6+++.+++ Wait for the renewings of life and sense in thee from God; wait for another visit,
wait for another touch and demonstration of his Spirit.
Where didst thou meet with it?
Go thither again, wait there again,
and look up to the Lord to stay thy spirit till he appear again.

But, oh! take heed, that before the light arise again, before the life stir again,
thou be not gone (by hearkening to temptations) into
an incapacity of knowing or receiving it.
For this is the way of the Lord, the experienced way;
after him (after the touches of his truth) comes the tempter with his reasonings,
deceits, likenesses, etc.
Now the Lord is trying thee, how thy heart will stick to him:
and if thou come off from the temptation, if thou stand clear of the enemy,
the Lord will appear to thee again; strengthen thee, comfort thee, open more to thee,
lead thee further in the way of life, and nearer to the power and purity thereof:
but if thou draw back from that, wherein the Lord began to work,
the Lord`'s soul hath no pleasure to appear any further to thee,
or work any further in thee.

====

And one thing I will tell thee.
If thou let not in the enemy`'s temptations, but abide (under the clouds,
under the storms, under the tempests, under the confused reasonings, fears, doubts,
and troubles), looking towards the Lord, waiting for him,
and not making a league with the enemy against him in the mean time,
the Lord will certainly appear; and when he doth appear,
thou shall find one of these two effects.

Either the power of the enemy`'s objections, or temptations, will be so broken,
as thou shalt not then heed them;
or they will be so answered by the appearance and light of the Spirit of the Lord,
as thou shalt be satisfied about them.
Now, which of these is the better for thee, the Lord God knows,
and that thou shalt be sure to receive from him in that hour; neither will he leave thee,
but secretly support thee in the mean time; thy eye and mind being towards him.

The light and power of the Lord, when it ariseth,
scatters and breaks that in pieces in the mind, which was very powerful before;
so as the soul doth not now so much as mind the considering or knowing of that,
which the enemy hath made it believe was so necessary for it to know.
For mark: that which causeth me to grow, is the feeling of life,
the sense of the Lord`'s presence and power with me, the living knowledge,
the knowledge which quickens, and gives life.
Now, when the life springs, when the light shines,
when the Lord in the power and precious visitations of his truth, reacheth to my heart,
this is present with me.
Then what matter I those objections and prejudices, which the enemy casts into my mind?
Nay, I cannot heed them, being taken up with another thing of a deeper nature.
Thus have I often found it by experience; all that troubled me, and that I doubted of,
vanishing in a moment; that being present with me, and prevailing in me,
which puts an end to all thoughts, reasonings, and disputes.

Again, it pleaseth the Lord at other times (when he seeth good) to open the mind,
and let it into the light of those things (it waiting upon him,
and letting them alone his season) which of itself it could never have waded through.
Thus also have I seen the objections,
and stumbling-blocks concerning this precious people (who are of God,
as the first-fruits of his powerful visitation after the apostasy),
concerning their principle, way, doctrine, practices, etc.,
opened unto me in the clear light of God, and in the holy demonstrations of his Spirit;
insomuch as I have manifestly seen, and been fully satisfied,
that what was objected in my own heart, and is objected to in the hearts of others,
hath been from the subtle accuser of the brethren,
who beareth false witness against them,
and would draw as many as he can to partake in his false testimony,
and so also to become false witnesses against God, his truth and people.
Therefore beware, all ye that desire after the Lord,
and would meet with the rest and satisfaction of your souls in him,
how ye be prejudiced against that whereby God worketh in others,
and whereby he hath appointed to work in you, and all whom he worketh in.
For he hath sent his Son to give life, and he will not give life by another.
And he hath appointed his Son shall be received as a principle, as a seed of life,
though as little as a grain of mustard- seed; yet thus must he be received;
and in this his low appearance hath he the presence of God with him,
and his power and authority;
and what he--this little seed--(though ever so little) requires, teaches, forbids,
etc. must be observed.
But there is none upon the earth can own or submit to this,
but he that becomes a child also; yea, a very little child.
Man`'s spirit, man`'s wisdom, man`'s knowledge, man`'s religion, man`'s zeal,
etc. is too big to enter here.
Men are too wise, too knowing, too rich from scriptures and experiences,
to submit to this; as the Scribes and Pharisees were to submit to Christ`'s appearance,
doctrines, and preachings, when he appeared among them in that body of flesh.
Therefore, come into the true feeling, out of the dead knowledge into the living sense,
where life, power, righteousness, yea, the peace and joy of the kingdom, is tasted of,
and in some measure witnessed by those who bow down in spirit
before the least or lowest name or appearance of Jesus;
the lowest degree and measure of whose life is King and Lord over death forever.

[.inline]
=== An _Objection_ against the Principle, which in faithfulness to God, and in love to souls, we bear witness to, briefly answered.

[.discourse-part]
Objection.
Many do believe, and in that belief do object against it, that it is a natural principle,
and but a natural principle: and so, in its utmost improvement,
could lead but to the state of Adam`'s nature, and not to the redemption and new life,
which is in and by Jesus Christ.

[.discourse-part]
Answer.
I can grant that it is natural, in a sense; but not in the intended sense.
It is a principle, indeed, of God`'s nature, of Christ`'s nature; but not of man`'s nature.
It is that which stands a witness in man against him, when he falls and transgresses.
It is a light indeed that shines in his conscience; but it was before his conscience was,
and is of a higher nature.
Man is earthly (with his understanding, knowledge, reason, judgment, conscience);
but the light that shines in him (even in his dark, hard, unregenerate,
earthly heart) is heavenly; such as his darkness cannot comprehend,
though it shine in his darkness.
But wouldst thou in true understanding know what it is?
Feel it; come out of the darkness where it finds thee, into that light where it dwells,
and then thou wilt know it indeed, and be able to judge of it better.
Now I will tell thee how we know it to be the light of the new covenant.
Why thus: Because we find it discover to us the new covenant, and lead us into it; yea,
also show us the sins against the new covenant,
and furnish us with power from God against them, and preserve us out of them.
And with this demonstration, indeed, our hearts are satisfied;
though we could also say further, we have witnesses, both in heaven and in earth,
concerning this thing, whose testimony fully concludeth it,
to the full satisfaction of the soul, where it is heard and felt.

[.inline]
=== Some Questions and Answers concerning the New Covenant; opening the nature and way of it, as it is experimentally felt in the heart, and witnessed to in the holy Scriptures.

[.discourse-part]
Question 1. What is the New Covenant?

[.discourse-part]
Answer.
It is a new agreement between God and the soul, different from that former agreement,
which was between God and that people of the Jews.
It is a precious, glorious covenant, containing precious promises on God`'s part,
and as easily to be obtained on the creature`'s part as can possibly be.
It is a covenant of the eternal love of God; of life, peace, and rest to the soul;
of the power of the Lord stretched out for the soul, to deliver it from Egypt,
carry through the wilderness, bring into the Holy Land,
giving it its proper possession and inheritance there,
and maintaining it therein against all its enemies.
Yea, this covenant contains very precious things, which the soul finds great need of,
and rejoiceth in the sense and presence of,
when they are felt flowing from the covenant into it;
as writing the laws of God in the heart, putting his fear in the inward parts; yea,
putting his own Spirit within, to be a fountain of life and strength there,
whereby he causeth the soul to walk in his ways,
and preserveth it from departing from him.
Likewise in this covenant God becomes the teacher,
who createth in the soul a capacity to learn, and causeth it to heed and profit.
And in this covenant there is a forgiving of iniquity, and a remembering of sins no more,
but a destroying and rooting out of that which caused to sin,
and a healing of the backslidings of the soul, and a loving it freely.

[.discourse-part]
_Question 2._ How is this covenant made with the soul?

[.discourse-part]
Answer.
In Christ, the seed, who is all in this covenant.
He is the light of it; he is the life of it; he is the power of it;
he is the righteousness and sanctification of it.
By coming into him, the soul comes into this covenant; by abiding in him,
it abides in this covenant; and by growing up in him, it grows up in this covenant.

[.discourse-part]
_Question 3._ Is this an absolutely free covenant?
or are there any terms or conditions required of the soul in it?

[.discourse-part]
Answer.
It is absolutely free in its own nature.
It comes from the free love of God; it contains in it the free love of God;
it is freely offered to all to whom it is offered;
it is freely given to all to whom it is given.
Here is no price, nothing of the creature`'s required for it;
all that is required is the creature`'s receiving of it, and giving up to God in it.
And here, and after this manner, many things are required of the creature,
without which the creature can never come to receive the covenant, abide in it,
or reap the blessings contained therein.
This the Scriptures abundantly testify to;
as also the experiences of those who know and feel the nature and virtue of the covenant.

[.discourse-part]
_Question 4._ What things are required in this covenant, according to the Scriptures,
and according to the experiences of those that enter into it,
and reap the fruits and benefits of it?

[.numbered-group]
====

[.numbered]
_Answer 1._ This is required, that when the Lord calls, when the Lord quickens,
when the Lord toucheth the heart, openeth the ear,
giveth a faculty and ability of hearing, that then the Lord be hearkened diligently unto,
the ear, which he hath opened, kept open to him,
and that that whereby he openeth the one ear and shuts the other be kept close to,
and he waited upon therein; the true ear may be more and more opened by him,
and the other ear (which is apt to hearken to and let in the enemy) more and more shut.
Who is there among us that hath not felt the Lord God requiring this of us?
Wherein, as he hath been answered, the work of God hath gone on in us;
and as he hath not been answered, the work hath gone backward, and not forward.
And the Scripture bears witness to the same,
as Isa. 55:1-3. where the free covenant is proclaimed;
yet there is somewhat even there required.
"`Hearken diligently: come and eat ye that which is good,
and let your soul delight itself in fatness.
Incline your ear, and come unto me; hear, and your souls shall live;
and I will make an everlasting covenant with you, even the sure mercies of David.`"

[.numbered]
2+++.+++ Repentance is required, turning from the old, unclean nature and spirit,
and touching it no more; but cleaving to that which hath power against it,
and preserveth from it.
This also is felt and witnessed to be required of God now,
and was also testified to of old, as 2 Cor. 6:17-18. "`Touch not the unclean thing,
and I will receive you, and will be a father unto you,
and ye shall be my sons and daughters, saith the Lord Almighty.`"

[.numbered]
3+++.+++ Faith, believing the testimony of truth, and receiving the Spirit`'s baptism,
is required.
He that will enter into this covenant,
must believe the testimony of the gospel (the record of
God concerning his Son) with the faith which is of him,
and must be circumcised, baptized, renewed, and changed by him.
Now he that doth this shall be saved, as Christ promised.
Mark 16. but he with whom is the power of life and salvation
did not promise that any should be saved otherwise.

[.numbered]
4+++.+++ Obedience of the gospel, subjection to Christ in the rule of his Spirit,
and keeping of his commandments, is required.
For as the first covenant required the obedience proper to it;
so the second covenant requires the obedience proper to it.
And as there was no salvation, or standing in the first covenant,
without the obedience thereof; so neither in the second, without the obedience thereof.
He that will enjoy the peace, the righteousness, the justification, the life,
the power of this covenant, must live in the Spirit, walk in the Spirit,
fulfill the will of the Spirit; keep to the seed, keep to the anointing,
that the evil one touch him not; that the interrupter, the slayer,
the destroyer of life in the heart, have not power over him,
as he hath over any out of the limits of this covenant.
For within it are all the good, but without it the evil things, the dangers,
the temptations, the snares, the death and destruction of the soul;
and whoever wanders out of the covenant, cannot but meet with them,
and acknowledge it to be so, if he be in the true sense.
Therefore there must be a great care to abide in that which hath gathered,
in that which hath quickened, in that which giveth the true sense and understanding,
and keepeth out of the wrong.
How tender,
how free was the love of Christ to his disciples! yet he bids them abide in his love,
and tells them how they should do it: "`If ye keep my commandments,
ye shall abide in my love, even as I have kept my Father`'s commandments,
and abide in his love.`"

====

[.discourse-part]
_Question 5._ But how shall the soul be able to perform all these things?
Are they required of it in its own strength,
or doth God undertake to perform and work all in it?

[.discourse-part]
Answer.
Not at all in its own strength, will,
or wisdom (these are eternally shut out of this covenant); but in the strength, life,
and power, which flows from God in the covenant.

[.discourse-part]
_Question 6._ How shall the soul receive this strength, life, and power?

[.discourse-part]
Answer.
By embracing it as it comes, cleaving to it, panting after it,
patiently mourning and waiting for it.
(The vision of good will come to that soul in the Lord`'s season,
and will not tarry.) By not despising the little,
and looking after more before the little be received,
but thankfully entertaining the beginnings of life,
the beginnings of the holy instructions,
the first drawings from off the spirit and nature of this world, in whatever it be.
He that disputes not concerning the thing, but receives it just as it appears,
in a simplicity and uprightness, watching thereto, he shall be blessed of the Lord,
and meet with the desire of his soul in the Lord`'s season,
when the Lord hath fitted and prepared his heart for it.
Now this is so little and strait a door, so poor and low a beginning,
as the wisdom of man can never enter at it;
and if there should be a little entrance in the overcoming power of life,
yet that wisdom will drive the soul back again presently.
Let me know the doctrine first, saith the wise man;
I will understand the doctrine thoroughly before I will change my present way.
No, saith Christ,
"`He that doth his will shall know of the doctrine.`" Thou shalt know a little,
which will reach to thy heart.
There thou must begin; and being faithful there, thou shalt know further of the doctrine;
but being unfaithful there, thou mayest be stumbled and prejudiced against the doctrine,
but never be able to know it.
Oh, the mystery of life!
Oh, the hidden path thereof, which none can learn but those whom the Father teacheth!
But many think to learn in that, which ever was, and ever will be, shut out.
If Christ would lay his doctrine before them, and make it good to their understanding,
they would receive it.
No, no; they must bow to Christ, to his name, to his power, to his will,
to his way of manifesting his truth; he will not bow to theirs.

[.discourse-part]
_Question 7._ What are the sins against this covenant, and what effects have they?

[.discourse-part]
Answer.
The sins against this covenant are chiefly unbelief in the power,
and disobedience to the power,
which are of a deeper nature than the sins against the first covenant,
and have more dangerous effects.
The refusing of this covenant is more dangerous than the refusing the covenant of Moses.
And the breaking of this covenant; to wit,
the starting back from God (through a heart of unbelief) here,
is more dangerous than the breaking of the first covenant.

[.discourse-part]
_Question 8._ Why, can this covenant be broken?
Hath not God undertaken all in it?

[.discourse-part]
Answer.
It is an agreement between God and the soul, wherein things are required of the soul,
through the life and strength which flows from the covenant.
And the soul may hearken to the enemy, and not to the Lord; may walk after the flesh,
and not after the Spirit; may lust after high knowledge,
and hidden things of the kingdom, as they of old did after prying into the ark;
may draw back from the Lord in those respects wherein it had given up unto him, etc.
Now, these and such-like are breaches of the covenant;
or at least such sins against it as draw down judgments upon the soul at present,
and at last utter casting off,
unless the soul be brought back by the judgments into the
agreement again with the Lord in truth and uprightness.
It is true, the Lord doth all in the covenant according to his good pleasure; but withal,
he hath appointed a way of his working out the life and happiness of the soul,
to which it is his good pleasure to keep.
And his way is Christ, his seed.
Hence all the love, mercy, care, and tenderness of God flows.
Hither is the soul to come for it; and here the soul is to abide,
that it may enjoy and possess it.
But if the enemy can by any means draw the soul out from hence,
he draws it from its life and strength,
and from the sweet blessings and influences of the holy and free covenant.
Now, the Lord hath not given power to the enemy to force from hence;
but he gives power to the soul to abide with him here; and in the hour of distress,
if it cry to him, he helps the helpless, and lifts up a standard against the enemy.

Now, all that desire the sweetness of this covenant, the life, the virtue,
the blessings of it, oh! wait to feel and receive somewhat from God,
and in that to fear before him, and walk worthy of him,
and not to grieve or provoke his Spirit.
For he hath the power of life and death in his hand,
and whom he will he may have sufficient cause against,
to turn from and cut off when he pleaseth; and whom he will he may extend mercy to,
as far and as long as he pleaseth; for it is his own, and he may do what he will with it.
Only know this, God is love; God is bowels, infinite bowels; yea,
his tenderness is beyond imagination or comprehension, and he hates putting away.
The poor mourning souls that cry unto him, feeling their need of him,
and gasping after him, he cannot cast off; no,
nor any that come unto him in the truth of their hearts: but the wise, the confident,
the conceited, from their apprehensions of scriptures,
that think themselves safe by virtue of the covenant,
and yet are enemies in their minds to the light of the covenant,
these are out of the thing at present (in their own imaginings
and conceivings,) and are in the most danger of any I know.
The Lord in mercy cause his light to shine, his life to arise, his power to be manifest,
and thereby lead into, and preserve in, his everlasting covenant,
according to his good pleasure.
Amen.

[.inline]
=== A _Question_ or two, relating to Election, answered

[.discourse-part]
_Question 1._ How may a man make his calling and election sure?

[.discourse-part]
Answer.
By making Christ sure to him, in whom the calling and election is;
for the Lord chooseth only in him, and refuseth or reprobateth only out of him.

[.discourse-part]
_Question 2._ How may I make Christ sure to me?

[.discourse-part]
Answer.
By receiving him, giving up to him, parting with all for him,
and waiting upon him in the way and path of life,
till I feel the power of that broken in me, which would separate from him.
For what danger is there then, when the soul is naturally become the Lord`'s,
rooted in his love, circumcised in heart to love the Lord above all,
even with the whole heart and soul?
Certainly the love of the Lord cannot but flow in great strength to that soul,
and what can come between?
But now, while there is somewhat ungiven up, somewhat yet standing,
in which the enemy hath a part, and by which he may enter,
the state of that soul is not fully sure;
but there may be a going back from the saving life into
that wherein is the perdition and destruction of the soul,
and whoever goes thither meets with perdition and destruction,
so far as he travels that way.
For in the path of death there is death, which is met with by all that enter into,
and walk therein; as in the path of life there is life.
God is no respecter of persons; but he is a respecter of his seed,
and of his eternal covenant of life, which stands firm in his seed forever.
Here is life for every soul that feels the drawings of the Father,
and comes to his Son for life, and abides in him;
and there is death for every soul that comes not to this,
and departs from this through the heart of unbelief.
So the way of God is eternal and immutable; he cannot deny himself.
He that believeth in the Son hath life;
he that believeth not is in the death and condemnation which belong to the unbelief.
Now, wouldst thou know thy election, wait to know and distinguish between Jacob and Esau,
Isaac and Ishmael, in thyself; for they were outward figures,
and allegories of somewhat inward.
Feel Esau, the profane one; Ishmael, the scoffer at the wisdom, way,
and seed of God,--feel, I say, these (that are cast off by God) cast out of thee;
and then feel Isaac, the seed of the promise; Jacob, the plain birth of life,
raised up in thee, living in thee, and thou in it.
And then thou feelest the election, and art in the election.
And as his seed is sure to thee, and thy union with it,
and standing and abiding in it sure, so thy election is sure.
Election is a deep mystery,
and none can read the scriptures about it (which indeed are hard to be understood,
but easy to be wrested), but they that understand the thing,--that can read in the seed,
life, power, and openings of the Spirit of the Lord,--they read things as they are;
but other men only read things as they apprehend and conceive them to be.
So that the knowledge that God hath given his people
is above all the knowledge that can be searched out,
gathered, or comprehended by all the men upon the earth; whereby they know God better,
the things of God better, the words and scriptures of truth better,
than they themselves otherwise (or any else) could possibly attain to.

[.inline]
=== A _Question_ answered concerning the Ground of Men`'s misunderstanding and wresting of Scriptures

[.discourse-part]
Question.
What is the ground of men`'s misunderstanding and wresting of scriptures?

[.numbered-group]
====

[.numbered]
_Answer 1._ Want of acquaintance with God`'s Spirit,
and the right way of waiting upon him to receive the understanding of them.
For though men may go thus far,
as to know and confess that the Spirit of the Lord
is the only revealer of the things of God,
and the alone right interpreter of his own words; yet that man, who thus confesseth,
may not certainly and distinctly know the Spirit of the Lord,
and when he receiveth the interpretation of a scripture from him,
or when from his understanding, or a spirit that is contrary to him.
For there is another spirit near man, whose nature, work,
and delight is to cause man to misunderstand, and miswalk by the very scriptures;
and will bring things as warmly and (as it were) clearly to him,
as he can from scriptures, purposely to deceive and mislead him.
Now, he that hugs and receives everything that thus riseth in him, easily runs into,
and is surely caught in the snare of the enemy.
Therefore a man must watch and wait and fear and pray,
that he may distinguish between the nature and voices of spirits in himself,
that so he may know (in the light of the Lord) when the Lord speaks,
and also when the mysterious spirit of deceit strives to speak like the Lord.
Now, man cannot know this of himself, but as he is taught by the Lord,
at the very time when the snare comes; and he must not determine hastily,
but wait to feel that wherein the Lord appears and speaks to him,
and wherein the enemy cannot speak.
Thus feeling the birth of life in his heart, the seed which is of the Father,
which hath an ear that knows the voice of the Shepherd, and sinking into this,
and listening in this (out of his own thoughts, reasonings,
and whole course of his own wisdom), he also hath his ear opened to hear the true voice,
and findeth ability here to distinguish it from the voice of the stranger,
let him counterfeit ever so deceitfully.
For the eye of the Lord, the eye of truth, the eye of life, the eye of the Spirit,
pierceth through, and discovereth all deceits to the soul that feareth before him,
diligently waiteth upon him in his seed, and desireth to walk faithfully therein.

[.numbered]
2+++.+++ Want of acquaintance with God`'s truth in the love, life, and power of it.
For he that knows truth, that hath received from God the thing the Scriptures speak of,
how easy is it to him to understand the words that speak of that thing!
But he who hath the knowledge of the thing but from the words,
how easy is it for him to misunderstand the words!
As for instance: he whom God hath justified,
he who hath received the righteousness of the Son,
he who daily feeleth the blood of sprinkling, etc.,
how easy and natural is it unto him to understand
the words of scripture which speak of these things!
But he that hath not received this, nor thus knoweth the thing,
how easy is it for him to misunderstand the words;
and so from misunderstanding of the words,
to set up another righteousness for the righteousness of Christ,
than that which the Spirit of God intendeth in the Scriptures!

[.numbered]
3+++.+++ The opinions, apprehensions, ways, and practices of men,
which they have taken up in the dark, and in which their minds are engaged,
are a great let in their way from the right understanding of scriptures,
or the testimony of truth from others according to the Scriptures.
For there hath been a cloudy and dark day, or a great night of darkness upon the earth,
wherein the light, which leadeth to the soul`'s rest,
hath not shined clearly in men`'s spirits; and so,
in this cloudy darkness men have wandered from mountain to hill,
seeking their resting-place.
Now, some have fixed and pitched on one mountain, some on another; some on one hill,
some on another, saying, Here is the resting-place.
So when the Spirit of the Lord comes and cries, Depart ye, depart ye;
this is not your resting-place, for it is polluted; they cannot hear.
Why so?
Because they have already believed otherwise,
and in that belief taken it up for their rest;
and so cannot rightly understand or believe those scriptures,
or those living testimonies from the Spirit of the Lord, which declare it not to be so;
but are ready to wrest the one, and reproach the other.

====

[.inline]
=== Some _Questions,_ _Answers,_ and _Queries,_ concerning Deceit and Deceivers; as what they are, what discovers them, how man may come out of them, and be preserved from them, etc.

In the truth there is no deceit; and they that are in the truth,
are out of the deceit; and abiding there, are out of the reach of deceivers:
but they that are out of the truth, are in the deceit already,
and are liable daily more and more both to be further deceived,
and to help to deceive others.

[.discourse-part]
_Question 1._ What is deceit, and who are deceivers?

[.discourse-part]
Answer.
That which appeareth like truth, but is not,--that is deceit:
and they which are in a form of godliness, but are without the Spirit, life,
and power of it,--they are deceivers.

[.discourse-part]
_Question 2._ Who are most liable to deceit?

[.discourse-part]
Answer.
The simple, the heedless, the careless, the credulous;
those that wait not upon the Lord in the light, power, and demonstration of his Spirit,
to try things; these (with good words and fair speeches,
and appearances of things) are easily led aside from the
truth itself into some likeness or resemblance of it.

[.discourse-part]
_Question 3._ Which is the time of deceit?

[.discourse-part]
Answer.
The night; the cloudy, the dark time,
when the enemy hath raised his fogs and mists in the minds
of men,--then is his time of deceiving their hearts.

[.discourse-part]
_Question 4._ Is it now night or day?

[.discourse-part]
Answer.
It is night with some, day with others.
Where the light is arisen, there it is day;
where the darkness covereth and possesseth the minds of men, there it is night.

[.discourse-part]
_Question 5._ How may a man know whether it be night or day with him?

[.discourse-part]
Answer.
By waiting to feel somewhat of the life of God arising in him,
by turning and hearkening to his witness.
That will faithfully discover how it is with him, and where he is.

[.discourse-part]
_Question 6._ How may a man come out of the darkness of the night,
into the light and brightness of the day?

[.discourse-part]
Answer.
By joining to the first glimmerings and breakings forth thereof upon him.
The least light of truth hath the same nature, virtue and properties with the greatest.
Though not the same in degree, yet the same in kind;
and he that will come to the greatest, must begin with the least.
Light makes manifest; the day discovers both the things of the night and of the day.
Hast thou any discovery of either kind?
either of that which is good, or of that which is evil?
either of that which is of the worldly nature and the evil one,
or of that which is of the heavenly nature and the Holy One?
Join in immediately in the virtue, strength, and power of that which makes the discovery,
and thy spirit therein will find an entrance into the light of the day;
and going on faithfully thus, it will daily more and more break in upon thee,
even until it hath gathered thy spirit out of the blackness, darkness,
and deceit of the night, into the beauty, brightness, and truth of the day.

[.discourse-part]
_Question 7._ How may a man be preserved from deceit and deceivers?

[.discourse-part]
Answer.
By abiding in that which discovers them to him, and preserveth out of them;
by dwelling in that light, in that life, in that power, in that truth,
into which they cannot enter: by keeping to and in the elect of God,
which never was deceived, nor can be deceived: for it is of God, it is his seed,
of his nature, in which the wicked one, the deceiver, finds nothing,
hath nothing in him to enter at; and he that abides in him is safe in him.
But he that goes forth out of the life, out of the light, out of the seed,
out of the power which preserves, out of the holy anointing which keeps the eye open,
he easily runs into, and is entangled in, the deceivableness of unrighteousness,
judging it (for want of a true discerning) righteousness;
and then having judged that to be righteousness,
which is in its own nature but unrighteousness,
he must needs also judge that which is the true righteousness, to be but unrighteousness;
and then, having passed this judgment in himself, he grows wise, confident,
and strong in his deceit, both believing himself,
and also endeavoring to convince and persuade others, that it is the truth.
Oh! who knoweth the security of the little ones of God,
who have a being and standing in his truth!
The arm of his power is stretched round about them,
and he is a defence and strength unto them against all that would break in upon them,
to make a prey of their life, or to shake their standing in his truth,
either inwardly or outwardly.
Oh! bless his name, sing high praises to him, ye that feel it,
over all deceit and deceivables, over all the devices of the dark spirit,
which entangleth others, and would also entangle you, but that his goodness, mercy,
tender love, and powerful arm is stretched out over you.
So to him be the praise, and the bowings of that soul,
which feels his powerful and merciful preservation, forever and ever.

Now it is in my heart to add four queries, which, rightly weighed and resolved,
in and according to truth,
may further open men`'s minds into the true sense and right understanding of this thing.

[.numbered-group]
====

[.numbered]
_Query 1._ Have not the last days,
the perilous times (the times foretold of by Christ
and his apostles) been a long while upon the earth,
wherein iniquity hath abounded, and the love of many waxed cold,
wherein men have been lovers of themselves, covetous, boasters, proud,
etc.? Hath there not been a long night of darkness,
wherein these things (with many other fruits and effects of the night) have hid
and covered themselves almost in all sorts of professors of Christianity,
under a form of godliness?

[.numbered]
_Query 2._ Is not their time expiring already, and in some degree expired?
Was it not to have an end when the light and power of truth, which at first kept it back,
did spring and rise again?

[.numbered]
_Query 3._ Is not the day arisen?
Is not the darkness already past?
And doth not the true light now shine (and the true
power of life now appear) in many vessels?
Let the souls, that desire to know the truth of this,
wait to feel that which is of God answer in them.

[.numbered]
_Query 4._ Where are the deceivers, and where is the deceit?
Is it among those that have embraced the light of life?
or among those who abide in their old darkness,
and whose eyes are not yet opened to see the light and beauty of the day,
which is arisen in the hearts of those that are quickened
and raised by the power of the Lord?

====

[.inline]
=== That the Way of _Life_ and _Salvation_ is freely held forth by God to all; and there is nothing in him to let, stop, or discourage any man from receiving his Truth, and giving up to him in the faith and obedience of it, but very much to invite and encourage.

It hath pleased the Lord, who is over all, and good unto all,
to provide a remedy for the sin and transgression of the creature.
For as sin hath abounded unto death, so he hath caused righteousness to abound unto life;
yea, the free gift, which is as large and universal as ever sin was,
hath more power in it to save than sin hath to destroy.
And there is no ground of discouragement for any
(who hath not outsinned the day of his visitation,
and so the offer of mercy is over as to him) in reference to God;
though the enemy of the soul strives to raise up many discouragements
and objections in the minds of many,
to keep them from hoping in the Lord, and from giving up to his truth,
which saveth all that receive it, and abide in it.
Now, it is in my heart at this time, from a true sense,
to signify somewhat concerning the nature of the Lord (and
his real desire to save even those that perish),
which may conduce towards the removing of objections
and lets of this nature out of the minds of men.

[.numbered-group]
====

[.numbered]
1+++.+++ God is sweetness, meekness, tenderness, abounding in mercy and lovingkindness,
pitying the miserable, and naturally holding forth a helping hand towards them: yea,
he is universally thus.
There is not one miserable soul, not one perishing creature upon the face of the earth,
but as he hath wisdom and power to help it, so he hath tender bowels,
and a heart thereunto.
And it is not for want of somewhat to be done on his part, that souls perish,
but the failing always was and still is on the creature`'s part.

[.numbered]
2+++.+++ God loveth all his creatures, and cannot but be good to them.
He is outwardly good, he is inwardly good to them all.
He can do nothing against any one of them, but what stands with his love and mercy.
He doth not forget himself;
he doth not lose his nature in the manifesting of his righteousness, wrath,
and severity against sin and sinners.

[.numbered]
3+++.+++ He desires not the death of a sinner, nay, not of the wicked.
How mercifully did he walk with the Jews in the first covenant!
Did he ever desire their miscarriages, and the miseries which came upon them thereby?
Nay, did he not desire their good,
and their obedient walking with him therein for their good?
"`Oh,`" said he, "`that there were such an heart in them, that they would fear me,
and keep my commandments always, that it might be well with them,`" etc. Duet. 5:29.
How mercifully doth he walk with all in the second covenant,
that are in any measure drawn within the limits and compass thereof!
He is a Saviour, that is his nature;
and he seeketh the salvation of his creatures with his whole heart,
and with all his soul.
And when he bringeth any to repentance, there is joy in his bosom;
and when the enemy breaketh in upon any of his,
or by any subtlety draweth them into that which destroyeth, his pure,
tender Spirit is grieved therewith, and mourneth because of it.
"`O Jerusalem, Jerusalem,`" (said his true,
living image with tears) "`how often would I have gathered thee!`"

[.numbered]
4+++.+++ He would have all men to be saved, and come to the knowledge of the truth.
God sends his truth, his powerful truth, to save; and he shuts not any one out of it,
but seeks (in the way he hath appointed) to gather all into it,
that they might be saved by it.

[.numbered]
5+++.+++ He is very patient and long-suffering, waits long, tries long, invites often,
touches often, draws often; yea, the very vessels of wrath fitted to destruction,
there is much patience and long-suffering exercised towards them,
before the Lord can cast them off, and give them up utterly to destruction.
For mark: destruction is not his work or delight;
it is the work of the spirit and nature contrary to his.
"`I came not,`" saith Christ, "`to destroy men`'s lives, but to save;`" to give life to them.
And this is the proper end of God in every ministration: his end is not death,
destruction, increasing of the condemnation of the creature, etc.,
but to bring it to life thereby,
out of that which leadeth into the condemnation and destruction.
Did he not, for this end, bear with the old world?
Was not this the end of Noah`'s preaching to them, and warning of them?
Did he not, for this end, bear with the Jews in Egypt, in the wilderness, in Canaan,
etc.? Is not this the proper intent of the goodness, forbearance,
and long-suffering of God,--that it should lead to repentance?
(Rom. 2:4) and repentance leads to mercy, remission, and life.

[.numbered]
6+++.+++ The sacrifice of Christ had relation to all men.
He was sent out of God`'s universal love to mankind, to the whole world;
and was made a propitiation by God for the sins of the whole world.

[.numbered]
7+++.+++ There is no man perisheth for want of power;
for there is power in the free gift which comes upon all.
There is power in it to quicken, to give faith, to preserve in the faith,
to do all that is to be done in the soul; and it doth all everywhere,
as it findeth place and entertainment in the soul.
But man refuseth, man loveth the darkness, hateth the light,
shutteth his eyes against it, withdraweth his heart from it,
and so beateth back the purpose and counsel of God`'s love and good-will towards him.
For as the Jews outwardly, in the outward covenant, almost always rebelled, resisted,
and brought wrath upon themselves, to the grief of God`'s heart and of his holy prophets;
so do men in reference to the inward covenant (in that nature and spirit),
exceedingly provoking the Lord,
until his Spirit (in its holy jealousy and indignation) turn from them,
and give them up to hardness, senselessness, and impenitency,
which sealeth up to destruction.
But as Israel, in that first covenant,
could never justly lay the cause of their destruction on God,
but God did most justly lay it on them ("`O Israel! thy destruction is of thyself,
but in me is thy help`"); so neither can any blame the Lord, who perish from,
and fall short of, the virtue of the second covenant;
for he faileth not in doing his part therein, no more than he did fail in the first.
But man turneth from the power which saves, from the light which makes manifest,
from the life which quickens; and this is his condemnation,
and the cause of his perishing;
so that God will be just and clear of the blood of all men,
and the blood of them that perish will lie upon their own heads.
Had there not been somewhat near every man, which had more power in it than sin had,
they might have had some plea before the Lord; but the presence of this,
the power of this, the working of this, in every heart, more or less,
leaves all men without excuse,
and clears the free giver and his free gift in the balance of righteousness.
For this gift of his is faithful to every man upon the face of the earth,
never consenting to his iniquities and transgressions in any kind,
but still testifying against them as the Lord pleaseth to open its mouth.
But who hath believed its report?
and to whom hath the arm of the Lord been revealed?
Yet greater will the condemnation be upon them,
upon whom the Lord hath more abundantly shined;
and many will have a plea in respect of them, which the Lord will hear and consider,
and so they shall not enter into that depth of judgment and condemnation,
which will light on such as have resisted the light and power of life,
in its more glorious and bright appearances and strivings with them; even as Christ said,
It shall be easier for Tyre and Sidon, Sodom and Gomorrah, in the day of judgment,
than for Chorazin and Bethsaida, Capernaum and Jerusalem.

====

Therefore, O all men upon the earth, know the day of your visitation!
Make peace with the Lord, O transgressors! lay hold on his strength,
that ye may make peace with him.
Believe not the liar, who would put you out of hope,
but believe the voice of his love and tender Spirit.
Turn in, listen after him, watch if he do not call, mind if he do not draw;
and do not say, I want power; but wait in humility, meekness, and fear,
until his power arise.
Bear his judgments, wait upon him in the way of his judgments.
Do not fly from him because thereof; for therein is the mercy, life, and salvation.
Be not hasty, but wait long, believe long, hope long, feel the patience of the Lamb,
learn the mysterious path of life from the inward teacher, that ye may certainly know it,
and find your feet guided by his Spirit into it.

Is not the voice gone forth from him that is true?
"`Ho, every one that thirsteth, come ye to the waters,`" etc.
"`And whosoever will,
let him take the water of life freely.`" And is not he near who causeth the thirst,
and giveth the will?
Whom hath the Lord excluded?
Why should any man exclude himself?
The call is universal, the way is set open to all.
That is at hand which hath life and power in it, and is ready to work in all.
This commandment hath it received of its Father;
and it is faithful which hath received it: and all that come to the Father here,
in this gathering of life, the Father is ready to receive.
Thy soul, O man! is the Lord`'s. It is very precious in his eye: he seeks to save it,
and hath sent somewhat into thy heart to gather thee from that which would destroy it.
And this which he hath sent, hath in it of the Father`'s love, of the Father`'s mercy,
of the Father`'s power, of the Father`'s light, of the Father`'s life,
of the Father`'s wisdom, righteousness, etc.,
and will gather thee out of the world into the Father`'s nature and Spirit,
if thou wilt hearken to him with the ear which he will create in thee,
and receive him with the heart which he will give thee: yea,
he will help thee to turn from and forsake thy own wickedness, and the wicked spirit,
and to turn towards him who is life, righteousness,
and peace to the soul that is gathered unto him;
do but give up thyself (in the faith and obedience which he is
creating in thee) in the way of his quickening and renewing life.

[.inline]
=== Some _Questions_ answered concerning the Spirit of _Christ,_ and the spirit of the Scribes and Pharisees

[.discourse-part]
_Question 1._ What kind of spirit was the spirit of the Scribes and Pharisees?

[.discourse-part]
Answer.
A strict, zealous, righteous spirit,
according to their understanding and apprehensions of the letter.
They fasted much, they prayed much, they gave alms,
they were great contenders for the circumcision and ordinances of Moses.

[.discourse-part]
_Question 2._ What kind of Spirit was the Spirit of Christ?

[.discourse-part]
Answer.
A righteous, strict, and zealous Spirit, according to the power of the endless life.
He was in that from which the righteousness of the law came,
and which brought it forth and fulfilled it in his vessel.

[.discourse-part]
_Question 3._ What did the Scribes and Pharisees judge of Christ according
to their apprehension and understanding of the letter?

[.discourse-part]
Answer.
They judged him a sinner, and transgressor of the law of Moses, a loose person, an eater,
a drinker, a friend of publicans and sinners;
one who taught not his disciples to fast and pray, but rather to break the law of God,
and transgress the sabbath; yea, one who was a blasphemer, and a deceiver of people, etc.

[.discourse-part]
_Question 4._ How came the Scribes and Pharisees thus to judge of Christ?

[.discourse-part]
Answer.
Because they were in that spirit, nature, and mind, which giveth wrong judgment.
For it is not a gathered knowledge from the letter, which makes able to judge of spirits,
and about the things of God; but a receiving and being born of the Spirit.
For from the Spirit alone is a right understanding of the letter,
which the Spirit hath to give, and giveth to the true birth.

[.discourse-part]
_Question 5._ What did Christ judge of the Scribes and Pharisees according
to his knowledge of them from the Spirit and power of life?

[.discourse-part]
Answer.
That they were hypocrites, painted walls, and sepulchres,
which make a fair show in the flesh, but were not of nor in the truth.

[.discourse-part]
_Question 6._ Is the spirit of the Scribes and Pharisees to be found now in the world?

[.discourse-part]
Answer.
There is nothing new under the sun.
The spirit of wickedness and deceit is always the same, in all ages and generations;
and the Spirit of holiness and truth is the same also.
So that Cain, Ishmael, Esau,
the scoffer and persecutor of the prophets (of Christ`'s apostles and holy martyrs)
are to be found in every age (the same in spirit and nature with them):
and so are Abel, Enoch, Isaac, Jacob, etc.

[.discourse-part]
_Question 7._ Where is the spirit of the Scribes and Pharisees now to be found?

[.discourse-part]
Answer.
They in all professions, gatherings, and walkings, that are strict, zealous,
and righteous, according to their own understandings and apprehensions of the letter,
and not according to the Spirit and power of the
endless life,--they are of and in that spirit.

[.discourse-part]
_Question 8._ How may a man come out of the spirit of the Scribes and Pharisees,
and into the Spirit of Christ?

[.discourse-part]
Answer.
By coming to the power of the endless life, wherein Christ`'s ministry is,
wherein his Spirit is felt and ministereth.
This shuts out all the deceits and devices of that spirit which lieth in wait to deceive.
He may entangle the mind about the letter, about the understanding of scriptures,
and practices and ordinances there;
but he that begins in the Spirit (in the power of life,
in the living demonstration of truth) is out of his compass; and there abiding,
groweth up and remaineth out of his reach.

[.discourse-part]
_Question 9._ How may a man come to the power of the endless life?

[.discourse-part]
Answer.
By waiting to feel it.
There is somewhat of God near every man; which,
his spirit retiring and waiting on the Lord,
the Lord will give him to feel in the seasons of his good pleasure.
For it is near man, not as a talent always to lie dead and buried, but to work in him,
and bring him out of his own sinful, corrupt nature into his holy, pure nature.

[.discourse-part]
_Question 10._ How may a man feel and know the power of this life?

[.discourse-part]
Answer.
By its nature, properties, manner and end of working in the heart.
It enlightens the soul, it quickens to God,
it draws the heart from that which is manifestly and sensibly evil without dispute,
it opens the eye to see and discern that which is holy and good,
inflaming the mind with desires after it.
Now, this is the appearance of the Holy One, who thus appears and begins to work,
to draw the mind from that which is sinful and destroyeth,
to that which is holy and saveth.
Happy, oh! happy is he who thus feels the drawing, quickening Spirit,
and in faithfulness gives up thereto! for he (by
the Spirit and power of life) shall feel Cain,
the sacrificer according to the flesh, Ishmael, the seed of Abraham after the flesh,
Esau, the first birth, whose mind is in the earth,--he shall feel these, I say, cast out;
and Abel, the righteous seed, who lives and sacrifices in the true faith; Isaac,
the seed of promise, Jacob, the wrestler with God,
in the power and strength of his own Spirit,
with the tears and supplications which are from his
own life,--he shall feel (I say) this nature,
birth, and Spirit raised in him, and his soul in it living to God,
and increasing in union and fellowship with him.

[.inline]
=== Some _Questions_ answered concerning Blasphemy and Blasphemers

[.discourse-part]
_Question 1._ What is blasphemy?

[.discourse-part]
Answer.
It is the reproaching or speaking ill of the truths or name of God,
in any of their appearances, or of them whom he hath chosen to bear his name,
or hold forth his truth.
To reproach the name or truths of God, as they have been held forth in former ages,
or as they are held forth in this age; or to speak evil of the instrument he then chose,
or now chooseth and maketh use of to hold them forth,--this is blasphemy:
and the Lord will not hold him guiltless who so doth, whatsoever he be.

[.discourse-part]
_Question 2._ In which respect are men most liable to blasphemy?
Are they aptest to reproach and speak evil of God`'s truths,
as they have been held forth in former ages,
and the instruments by which God then held them forth?
or are they apter to reproach and speak evil of the truths of God,
as they are held forth in their age,
and the instruments and ministers who then held them forth?

[.discourse-part]
Answer.
Men are not so liable to blaspheme the truths (or name) of God, as formerly held forth,
or the messengers and ministers of former ages,
as the present truth and the present ministry.

[.discourse-part]
_Question 3._ How cometh that about, or why is it so?

[.discourse-part]
Answer.
Because the truths of former ages, and the ministry therein,
have wrought through the deceit and opposition, which withstood them in their day,
and have left a good savor behind them;
so that it would be hard and disadvantageous to the evil
spirit to endeavor to bring a reproach over them.
If men should go about to revile Moses or the prophets of old, Christ or his apostles,
who would give an ear to them?
Surely very few, if any.
But to cry up these and their doctrine,
and to endeavor to make the present dispensation of truth appear to men,
as if it were different from and contrary to these (of another nature, of another spirit,
tending to other ends,
and towards the producing of other effects),--this is a very subtle device,
and an advantageous way of opposing the present truth and ministry with;
and this way the enemy hath taken all along.
Moses in his day had enemies and resisters,
but after his death we never hear him spoken against;
but those that withstood the prophets in after ages,
would honor the remembrance of Moses.
In Christ`'s day they would honor both Moses and the prophets; but Christ,
and his disciples and apostles, were reproached as blasphemers and deceivers.
After that age, Christ and his apostles were generally acknowledged,
as well as Moses and the prophets; but yet they that were in the same spirit,
in the same life, in the same nature,
have afterwards still been persecuted and opposed by the present age.

[.discourse-part]
_Question 4._ Who are the great blasphemers in every age?

[.discourse-part]
Answer.
They which profess truth, but are not in the power and life of that which they profess;
and among these, those especially who have had any taste of the power:
for if these turn from the power, which it pleased God to give them some taste of,
they are given up by God to delusion, devilishness, subtlety, and enmity,
above all others.
For as the blasphemy (which I am speaking of) is above truth and the name of Christ,
so it is chiefly to be found among those who pretend to his name.
Those that have the outward name, knowledge, and talk about the name, about Christ,
about the heavenly things,--these blaspheme and reproach
those who have and are in the thing itself,
who dwell in heaven, and worship in the heavenly place,
even in the true tabernacle which God hath pitched, and not man.
These bring their knowledge, wisdom, scriptures, experience, observations,
and all that ever they can reap and rend, against the present power and life of truth.

[.discourse-part]
_Question 5._ How come men, who pretend to truth, and to seek after it,
to run into this grievous and dangerous blasphemy?

[.discourse-part]
Answer.
By reason of their not being in that,
which demonstrateth the truth in the holy power and nature thereof.
They want its light and demonstration, and so understand things out of it;
and in this their own misunderstanding turn against that, which should enlighten,
sanctify, and preserve them.
Now, not being in that (but in another thing), not being in the true Spirit,
in the true light, in the true knowledge, in the true sense and understanding,
they must needs err and misjudge; and the greater their knowledge, ability, wisdom,
and zeal is, the more desperate and dangerous is their path of error,
both to themselves and others.
Who erred so dangerously in that day, as the Scribes and Pharisees;
which by their wisdom, knowledge, and skill in the Scriptures,
would dispute against Christ, prove he was not (he could not be) the Messiah,
according to the Scriptures (bidding men search the Scriptures,
and see if any prophet came out of Galilee, John 7:52), judged him,
who was indeed the Holy One (who loved righteousness, and hated iniquity) an unholy one,
a sinner and companion of sinners, a blasphemer, deceiver, etc.? And in the same spirit,
the stricter a man is, and the more he knows,
and the more confident he is of his knowledge and skill in the Scriptures,
the more desperately and dangerously will he venture to oppose the appearance
of the Spirit and power of the Lord Jesus in this day.

[.discourse-part]
_Question 6._ How come they who have so much literal knowledge of scriptures,
and have had a true sense and experience (some of them) of the things of God,
to be out of that which demonstrateth the truth?

[.discourse-part]
Answer.
By their turning from it, and rejecting it.
The Scribes and Pharisees rejected the counsel of God, against themselves.
There is but one thing can open the eyes,
and the Scribes and Pharisees turned against it,
believing that their eyes were opened already,
by the light and knowledge which they had received from Moses.
Moses, said they, we know God speaks to; but as for this fellow,
we know not from whence he is.
And just so is it now.
Oh that ye could read, whose state it is!

[.discourse-part]
_Question 7._ Why do they turn from it and reject it?

[.discourse-part]
Answer.
Because it answers not their expectations.
That appearance of Christ in flesh in that day,
did not answer the expectations of the Scribes and Pharisees.
And this appearance of Christ in his Holy Spirit and power after
the apostasy doth not answer the expectations of many now.
And so, not appearing as what they look for, as what they have expected,
according to their apprehensions and understanding of the Scriptures,
they cannot (so standing and believing) wait, but turn from it,
and turn the Scriptures against it,
as the Scribes and Pharisees turned the Scriptures against that appearance of Christ.

Now, oh that men, that have any desires after truth,
might not run into this kind of blasphemy,
and so thereby provoke and turn that Spirit and power of life against them,
which alone is able to save them!
For the Spirit and power of the Lord turneth against the other spirit,
in all its devices and transformings, and against them who are joined to that spirit.
And as the eye of the Lord is chiefly upon his present ministration
of truth in the present age to mind that,
to bless that, to appear in that;
so his Spirit most turneth against that which opposeth and seeketh to overturn it.
Yea, little do men know what they have lost from God,
as to themselves and their own states; and what they are become in his sight,
by opposing the present dispensation and ministration of truth;
even as little do many know in this day, as the Scribes and Pharisees did in their day,
what they brought upon themselves,
and others whom they infected (by their false knowledge and wrong expounding
and managing of the Scriptures) with a prejudiced spirit against Christ.

The Lord did promise that he would become the Shepherd, and gather his sheep himself,
after the cloudy and dark day.
He is come to seek out, to gather, to heal, to bind up, to comfort, to preserve, etc.
He is known, he is witnessed, he is received; his life, virtue,
healing and saving power is felt.
Let men reproach and revile it ever so much, yet it is known to be the thing, the pearl,
and seed of the kingdom, etc.
Yea, and he that receiveth it, and is born of it, knoweth that he is of God,
and hath the true nature of life, and true language from God; which that,
which knoweth God, heareth; but that which is not of God cannot hear.

[.inline]
=== A _Question_ concerning Miracles answered

[.discourse-part]
Question.
If this be a new dispensation of the life and power of God,
even of the preaching of the everlasting gospel again after the apostasy,
why is it not accompanied with outward miracles now, as formerly it was?
I say outward miracles, because it is accompanied with inward miracles.
For the lame, that could never set step in the path of life, do now walk;
the eyes that were blind, are opened, and do now see; the ears that were deaf,
have been unstopped, and do now hear; the lepers inwardly,
who were all overspread with sin and corruption, have been washed, cleansed,
and healed by the pure power; yea, the dead inwardly, have been quickened, raised,
turned to him that lives forevermore, have received life from him,
and do live in him and with him.
Now, these are mighty things, wonderful miracles,
even the substance of the miracles which were wrought under the law,
and which Christ himself wrought outwardly.
For it was not the outward healing, which is salvation, life,
and power chiefly aimed at therein;
but to point men by that to the thing which was to work the inward;
that they might take notice of it, know it, come to it, and wait upon it,
to be made partakers of the inward health and salvation by it.
Yet seeing in that day Christ did then please to put forth his power outwardly,
to point to and witness of the inward, why doth he not do so now?

[.discourse-part]
Answer.
The nature of the present dispensation doth not require it.
For the present dispensation of life,
is to bring men to the principle of life which is within
them (which is the sum and substance of all former dispensations);
and to bring them to this,
there doth not need any thing of a miraculous nature outwardly; but the witness,
demonstration and enlightening of the Spirit inwardly.
Now, when the outward law was to be received,
then the Lord saw need of outward miracles to confirm it; so also in the prophets`' days,
while that dispensation held, till towards the coming of Christ.
And when Christ came in the body prepared by the Father, it pleased the Lord to confirm,
by outward, visible demonstrations of his power in him, that this was he.
Likewise afterwards,
the apostles having the doctrine concerning that
appearance to preach and testify to the world,
the Lord was also pleased and saw good to confirm it by miracles.
But now there is not any new doctrine to be preached.
The doctrine concerning Christ is the same that it was,
the very same that the apostles preached.
Neither is there any need of confirming it now;
for it is generally believed among professors of all sorts; as Christ`'s birth, preaching,
living holily, dying (offering himself up as a sacrifice for sin), rising, ascending,
sitting at the right hand of the Father, etc.,--who doubts of these things?
But under all this knowledge men hide their sins, their lusts and corruptions,
serving not the Lord (not truly fearing, believing in, and obeying him), but his enemies,
and are become corrupt like unto the Heathen; being in words Christians,
but as to the holy conversation and power of the endless life,
as far from it as the very Heathen.
Therefore hath the Lord visited the world in this state,
and sent forth what he judged meet for it in this state; to wit,
not a ministry to preach over that doctrine,
under which the Christian world had corrupted themselves;
but to point to the principle of life, wherein is the light and power to discover,
lead from, and wash away this corruption.
And with this ministry there goeth a power to reach the heart and raise the witness,
in all that hear in fear, and in the sense and dread of God;
so that the witness presently answers, and the mind is inwardly satisfied,
knows the thing, and turns to it.
Now, this (and the effect of this) is beyond miracles,
and the satisfaction or assurance which they can afford.
For miracles leave a dispute in the mind (notwithstanding all the miracles Christ showed,
there was yet a dispute and dissatisfaction in the minds of many concerning him).
But he that feels the thing itself in the true principle,
where the demonstration and certainty of the Spirit`'s assurance is received;
he is past dispute, and is gone a degree, in the nature of things,
beyond that satisfaction which miracles can afford.
He is out of that state and mind which asketh a sign, or seeketh confirmation by a sign.
So that men ought to take heed how they expect or call for miracles now,
as the Jews did to Christ for a sign of old;
for that is not the temper of mind which this dispensation is to answer,
but rather to draw men out from thence into a principle,
into the new life and Spirit itself;
where fuller demonstrations (of a deeper nature) are given to the soul,
than outward miracles are.
Feel the power that is revealed, feel the life that is made manifest,
let in the light of the day which shines; this will scatter the darkness from thee,
and clear up the things of the day unto thee.
The pure ministration of power, the pure ministration of life,
the light of the everlasting day, is come.
Oh! wait the opening of the eye that sees it,
and be conceived and brought forth in the womb of it.

[.inline]
=== Some further _Questions_ answered, concerning the New Covenant

[.discourse-part]
_Question 1._ What were those days, after which the New Covenant was to be made?

[.discourse-part]
Answer.
They were the days of the law and prophets, the days of the first covenant,
the days of God`'s exercising and making trial of that outward people, the Jews,
by his outward and literal covenant.
After the full expiring of those days, another covenant was to be made.

[.discourse-part]
_Question 2._ What are the days wherein the new covenant is made?

[.discourse-part]
Answer.
They are the days of Christ, the days of his power,
the days of the ministration of his Spirit.

[.discourse-part]
_Question 3._ What is the house of Israel and Judah, with which this new covenant is to be made?
Is it the Israel and Judah according to the flesh?--the
Israel and Judah according to the old covenant,
or according to the new?

[.discourse-part]
Answer.
When the old covenant is passed away,
the consideration of Israel and Judah after the flesh passed away also;
and the new covenant is fitted for and made with the new Israel and Judah; so that,
as the apostle said, "`He is not`" (now, according to this covenant) "`a Jew,
that is one outward; nor is that circumcision, which is outward in the flesh;
but he is a Jew, which is one inward,`" etc.
This gospel breaks down the outward consideration between Jew and Gentile,
and brings up another consideration in both;
so that the promises and blessings are not to either in their old state,
but as they are gathered into, and spring up in, the new seed.

[.discourse-part]
_Question 4._ Is this covenant faultless?
Doth it mend that which God found amiss in the other?
Doth it keep more firmly to him than the other did?
Is there no falling away from it?

[.discourse-part]
Answer.
Yes, it is faultless.
It doth help the defects of the other.
It doth keep more firmly to God.
There is no falling away from it, by those with whom it is fully made,
and who are established in it.
But in the passage and travel,
there is danger to the soul which is not faithful and watchful,
lest it be drawn from that which gives it right to and entrance into the covenant.
For as the beginning is in the faith, and in the obedience, so is the continuance,
growth, and progress.
Thus the gospel was preached, "`He that believeth, and is baptized,
shall be saved;`" which believing includes not only a beginning to believe,
but a going on therein, and continuing to the end.
For so is the promise and word of Christ,
"`He that continueth to the end shall be saved.`" But if any man draw back from the Lord,
from his Spirit, and return into the way of death with the other spirit,
the soul of the Lord will have no pleasure in him.

[.discourse-part]
Objection.
But then this also is like the first covenant, depending upon the creature,
and is defective as the other was.

[.discourse-part]
Answer.
No; this covenant doth not depend upon the creature, but upon God`'s love, mercy,
and power, which hath no limits in this covenant,
but may extend itself as far and as long as it pleaseth.
It dependeth upon the principle of his life,
upon the power of his Spirit freely dispensed to the creature;
yet the creature that will reap and enjoy this,
must come to it in the faith and power which is of the principle,
and in the same must abide with it.
For God forceth none to come, but draweth and maketh willing;
neither doth he force any to stay, but persuadeth and maketh willing to stay.
This is the manner of his working in the day of his power.
But now, if the soul hearken to the other spirit and his drawings,
and depart from the Lord, and will not hearken and be won again,
the love and pleasure of the Lord turns from it,
even according to the law of this covenant.
For there is a law of this covenant,
according to the nature of it (according to which
the Lord works) as well as there was in the other.

Now, search ye the Scriptures concerning this thing.
Is there any promise of salvation, but upon coming to the Son; or to them that come,
without abiding?
Did not Christ tell his own disciples, that as they were in the vine, in his love,
so they must abide there?
It was the law his Father gave him, and the same law he giveth them.
It is natural to man to backslide;
and in his backsliding from that wherein is the life and virtue,
how can he but miss of the life and virtue of it?
Therefore, in this covenant,
the Lord hath provided that which will heal the backslidings,
which will work out all in man freely, which will powerfully preserve him, etc.
But he must come to it (he must come to the Son, he must come to the waters),
and he must also abide there.
Yet this is not required of him to do of himself neither,
according to the law and course of the old covenant; but of him in the new ability,
which is in the new principle of life, wherein he is daily to receive it: yea,
it is with him, and near him; as near him to be daily drawing him into,
and preserving him in, life, and within the limits of the covenant,
as the tempter is to be drawing him into sinning against the covenant, and so into death.

[.discourse-part]
_Question 5._ What doth God promise to do for the
new house of Israel and Judah in this new covenant?

[.discourse-part]
Answer.
He promiseth to put his laws into their mind, and to write them in their hearts.
(Oh, happy he that knoweth these laws, this mind, this heart,
this manner of writing!) He promiseth to be their God, and that they shall be his people.
(This covenant is a powerful covenant;
it will make so indeed!) He promiseth to become their teacher,
and such a teacher as all shall know him, from the least to the greatest,
even so as they shall not need to seek out abroad after the knowledge of him.
(It is so where this covenant is made, even with the least with whom it is completed;
but it is not so where it is only begun,
or in some few degrees carried on.) He promiseth to take away that
which alone is able to hinder the good things of the covenant;
for he will be merciful to their unrighteousness,
and their sins and iniquities will he remember no more.
This also is witnessed according to the soul`'s growth in, and receiving into it,
the strength of the covenant.
For many find sinning against the covenant,
and the remembering of their iniquities in their passage; yea,
judgment doth continue in the refining time, till that be made to pass away thereby,
which the judgment is to; but in the covenant itself is rest, joy, peace, satisfaction,
life, and powerful redemption and righteousness forevermore.

[.discourse-part]
_Question 6._ How is this covenant made, and how doth the soul enter into it, grow up in it,
and reap and enjoy the sweet blessings and promises of it?

[.discourse-part]
Answer.
It is made in the faith and obedience of the soul to the gospel,
to the power of the endless life.
It is made according to the promise.
The promise is to him that believes and obeys the gospel.
There is no other way in it but union with Christ in the faith,
from which flows obedience to the holy commands and requirings of his Spirit.
All unbelief and disobedience is out of this holy blessed covenant.
They are stops in the way, and hinder the soul both from entering into,
and from abiding in, the covenant; yea,
the gates of hell may easily prevail against them who do not believe, obey, watch,
and pray, but enter into the temptation of the enemy, which draw into death,
as the motions and requirings of the Spirit lead into life.

[.inline]
=== A brief Account concerning Silent Meetings; the nature, use, intent, and benefit of them.

This is a great mystery, hid from the eye of man,
who is run from the inward life into outward observations.
He cannot see either that this is required by the Lord of his people,
or any edification therein, or benefit thereby;
but to the mind that is drawn inward the thing is plain;
and the building up hereby in the life of God, and fellowship one with another therein,
is sweetly felt; and precious refreshment from the presence of the Lord received by them,
who singly herein wait upon him according to the
leadings and requirings of his Holy Spirit.
Now, to open the thing a little to the upright-hearted, if the Lord please.

After the mind is in some measure turned to the Lord, his quickenings felt,
his seed beginning to arise and spring up in the heart,
then the flesh is to be silent before him,
and the soul to wait upon him (and for his further appearings)
in that measure of life which is already revealed.
Now, this is a great thing to know flesh silenced,
to feel the reasoning thoughts and discourses of the fleshly mind stilled,
and the wisdom, light, and guidance of God`'s Spirit waited for.
For man is to come into the poverty of self, into the abasedness, into the nothingness,
into the silence of his spirit before the Lord;
into the putting off of all his knowledge, wisdom, understanding, abilities,
all that he is, hath done, or can do, out of this measure of life,
into which he is to travel, that he may be clothed and filled with the nature, Spirit,
and power of the Lord.

Now, in this measure of life which is of Christ, and in which Christ is,
and appears to the soul, there is the power of life and death;
power to kill to the flesh, and power to quicken to God;
power to cause the soul to cease from its own workings,
and power to work in and for the soul what God requires,
and what is acceptable in his sight.
And in this God is to be waited upon and worshipped continually,
both in private and in public, according as his Spirit draws and teaches.

For the Lord requireth of his people not only to worship him apart,
but to meet together to worship him, in the seasons, and according to the drawings,
of his Spirit: and they that are taught of him,
dare not forsake the assembling of themselves together, as the manner of some is;
but watch against the temptations and snares,
which the enemy lays to deceive them therefrom, and to disturb their sense by,
that they might not feel the drawings of the Father thereunto.

And this is the manner of their worship.
They are to wait upon the Lord, to meet in the silence of flesh,
and to watch for the stirrings of his life,
and the breakings forth of his power amongst them.
And in the breakings forth of that power they may pray, speak, exhort, rebuke, sing,
or mourn, etc. according as the Spirit teaches, requires, and gives utterance.
But if the Spirit do not require to speak, and give to utter,
then every one is to sit still in his place (in his heavenly place I mean),
feeling his own measure, feeding thereupon, receiving therefrom, into his spirit,
what the Lord giveth.
Now, in this is edifying, pure edifying, precious edifying; his soul who thus waits,
is hereby particularly edified by the Spirit of the Lord at every meeting.
And then also there is the life of the whole felt
in every vessel that is turned to its measure:
insomuch as the warmth of life in each vessel doth not only warm the particular,
but they are like a heap of fresh and living coals, warming one another,
insomuch as a great strength, freshness, and vigor of life flows into all.
And if any be burdened, tempted, buffeted by Satan, bowed down, overborne, languishing,
afflicted, distressed, etc., the estate of such is felt in Spirit, and secret cries,
or open (as the Lord pleaseth), ascend up to the Lord for them,
and they many times find ease and relief, in a few words spoken, or without words,
if it be the season of their help and relief with the Lord.

For absolutely silent meetings, wherein there is a resolution not to speak, we know not;
but we wait on the Lord, either to feel him in words,
or in silence of spirit without words, as he pleaseth.
And that which we aim at,
and are instructed to by the Spirit of the Lord as to silent meetings,
is that the flesh in every one be kept silent, and that there be no building up,
but in the Spirit and power of the Lord.

Now, there are several states of people: some feel little of the Lord`'s presence;
but feel temptations and thoughts, with many wanderings and rovings of mind.
These are not yet acquainted with the power, or at least know not its dominion,
but rather feel dominion of the evil over the good in them.
And this is a sore travailing and mournful state,
and meetings to such as these (many times) may seem
to themselves rather for the worse than for the better.
Yet even these, turning, as much as may be, from such things, and cleaving,
or at least in truth of heart desiring to cleave,
to that which disliketh or witnesseth against them, have acceptance with the Lord herein:
and continuing to wait in this trouble and distress (keeping close to meetings,
in fear and subjection to the Lord who requireth it,
though with little appearing benefit), do reap a hidden benefit at present,
and shall reap a more clear and manifest benefit afterwards,
as the Lord wasteth and weareth out that in them, wherein the darkness hath its strength.
Now, to evidence that the Lord doth require these silent meetings,
or meetings after this manner silent, it may thus appear.

God is to be worshipped in spirit, in his own power and life,
and this is at his own disposal.
His church is a gathering in the Spirit.
If any man speak there, he must speak as the oracle of God,
as the vessel out of which God speaks; as the trumpet out of which he gives the sound.
Therefore there is to be a waiting in silence till the Spirit of the Lord move to speak,
and also give words to speak.
For a man is not to speak his own words, or in his own wisdom or time;
but the Spirit`'s words, in the Spirit`'s wisdom and time,
which is when he moves and gives to speak.
And seeing the Spirit inwardly nourisheth, when he giveth not to speak words,
the inward sense and nourishment is to be waited for,
and received as it was given when there are no words.
Yea, the ministry of the Spirit and life is more close and immediate when without words,
than when with words, as has been often felt,
and is faithfully testified by many witnesses.
Eye hath not seen, nor ear heard,
neither hath entered into the heart of man how and
what things God reveals to his children by his Spirit,
when they wait upon him in his pure fear, and worship and converse with him in spirit;
for then the fountain of the great deep is unsealed,
and the everlasting springs surely give up the pure and living water.
