== Reply to Queries and Animadversions

[.section-date]
1667, published posthumously

[.asterism]
'''

[.offset.emphasized]
+++[+++The following appears to have been written in answer
to the queries and animadversions of an author not named therein.
It is supposed our Friend Isaac Penington might have mentioned him in the title,
or pointed him out by some short introductory address, which, through accident,
was omitted by the printer.--1761 editor.]

[.asterism]
'''

[.section-summary-preface]
Concerning the Rule of the New Covenant,
or that which _God_ hath appointed to be the Rule to the Children of the New Covenant.

The way, the truth, the life; the everlasting way, the everlasting truth,
the everlasting life; that is the rule in the new covenant.
God sent Christ his Son, the Word of eternal life, a light into the world;
and the message and drift of the gospel,
is to turn men from the inward darkness to the inward light; and being turned to it,
the manifestation of this light is to be the rule,
which manifests the way of light and truth as immediately in the heart,
as ever the darkness did the way of deceit and error.

The promise of the new covenant is,
"`I will put my Spirit within them;`" and this Spirit hath an inward law and testimony,
which it writeth in the heart;
which inward law and testimony is to be the rule of the heart.
And as the outward Jews were to have recourse to the outward law and testimony,
so the inward Jews are to have recourse to the inward law and testimony;
and to witness the law of the Spirit of life in Christ Jesus revealed in them,
and their minds and spirits subjected thereto: and this is near, bright,
and powerful in those who receive the Spirit,
and with him the law and power of the endless life.

The letter killeth: the Jews understood not the way of life by the letter;
therefore the promise was,
"`I will pour out my Spirit upon all flesh:`" and because ye are sons,
God hath sent forth the Spirit of his Son; and thou shalt hear a voice behind thee,
saying, "`This is the way, walk in it.`" And this voice is to be hearkened to;
this prophet (which God raiseth up to the soul in
the new covenant) is to be heard in all things:
and he that hears his voice, and obeys, lives; and he that hears not is in death,
even until now, profess what he will.

In Christ Jesus, neither circumcision availeth any thing, nor uncircumcision,
but the new creation; if any man walk according to this rule, peace be upon him, etc.
What doth the apostle call the rule here?
Oh! wait on the Lord to read in the Spirit, and rightly to understand.

If a man receive the Spirit, and walk in the newness of the light,
and quickenings thereof every day, hath he not a rule which is certain and infallible?
If any man be in Christ, there is a new creation;
and the limits of that new creation (which is the light and power of the endless life,
or of God`'s Holy Spirit dwelling within) are his rule.
And within the bounds of that (within the bounds of his light, his life, his motions,
his instructions) man never errs; but out of it,
deceit and darkness and error are always at hand.

Yet, though we do own Christ to be the rule,
we do not deny making use of the Scriptures to try doctrines and forms of religion by;
but know that what is of God doth and will agree therewith,
and what doth not agree therewith is not of God;
and that our fore-fathers in the faith were led to
batter the superstitions and idolatries of the Papists,
by the testimony of the Scriptures.
And we have also the testimony of the Scriptures with us,
both to the light and Spirit within, and against forms formerly invented,
or now practised, out of the life and power.
But we believe the Spirit to be a touch-stone beyond the Scriptures,
and to be that which giveth ability to try and discern, not only words, but spirits;
whereas a man may hold the form of doctrine and godliness, and yet want the power:
in which case, nothing can try such a spirit, but the Spirit of God,
which is in the spiritual man.
And for calling the Scriptures the Word of God,
we cannot but look upon it as an improper expression, they being many words,
not the one Word; and Christ is called in the scripture, not only the Word God,
but the Word of God.
And if, in the fear of the Lord, and true sense,
we keep herein to the expressions of scripture, and its form of words, which is sound;
surely we cannot justly be blamed for so doing.

But whereas ye affirm the scripture to be the rule; consider seriously,
and answer me this question, How is it a rule?
Whether it be a rule as it is literally understood,
or whether it must not be interpreted before it can be understood as a rule?
If it must be interpreted, what must be the interpreter, whether it be the Spirit of God,
or a man`'s wisdom?

As to that question,
Whether the writings of any now be of equal weight with the Scriptures;
I have this to say:

The weight of the words which are from God`'s Spirit is according
to the strength of life which he pleaseth to clothe them with.
He sent forth Moses, the prophets, the Son in that body of flesh,
the apostles in his name and authority;
and the angel that he sends with the everlasting gospel, after the apostasy,
to preach to every nation, kindred, tongue, and people,
he sends not without his authority; yea,
the message that he thus sends in any age hath a
peculiar reference to the state of the world,
and the state of the people of God in that age;
and none can slight it (whether it be signified by word
or writing) without dashing against God`'s authority,
and despising him that speaketh in these latter days.
Yea, the immediate word of the Lord, spoken and declared at this day,
by any man to whom it pleaseth the Lord to commit the same, is of no less authority,
nor more to be slighted now, than it was in his servants in the days past,
by whom the Scriptures were given forth.

=== Concerning Christ

Christ is that Word of eternal life,
which was glorified with the Father before the world was; who,
in the full appointed time took up the body of flesh prepared by the Father,
to do the will in, and did the will in it, fulfilling all righteousness,
to the satisfaction of the very heart of the Father;
for whose name`'s sake the sins of believers are pardoned.
And this same Word of eternal life, and no other, which took that body of flesh upon him,
is also manifested, and dwelleth in the hearts of his saints;
who (as they receive him in the faith which is of him) dwells in them richly,
manifesting in the vessel the treasures of his divine wisdom and knowledge.
Now, this is the precious knowledge of Christ indeed;
and this is it every one is to wait for, to find a measure of knowledge.
Now, this is the precious knowledge of Christ indeed;
and this is it every one is to wait for, to find a measure of the same life,
the fulness whereof dwells in him bodily, dwelling in our mortal bodies,
and making us like unto him, in spirit, nature, and conversation.
And he that knoweth not, but opposeth, this (in any of its appearances or operations),
either in himself or others, is so far of the dark antichristian spirit.

=== Concerning the Form of Sound Words

Not only the form of sound words,
but also the good knowledge of the heavenly things themselves, have been miserably lost,
and buried in the ruins of the great apostasy.
And though God hath oftentimes touched men`'s spirits,
and given them some sense of the antichristian state of darkness;
yet have they not had that regard thereunto,
so as to be led thereby out of the state of darkness, but are found in Babylon,
by the Spirit of the Lord, at the very time of his coming to destroy her.
For though the Spirit of the Lord call out of Babylon;
yet there is great danger of not observing and following the call;
but of abiding still there, and partaking of her plagues.

Now, though men have had the Scriptures, yet wanting the Spirit of God,
and not knowing how to turn their minds thereto,
and distinguish his voice from the voice of their own spirits and reasonings (yea,
of the enemy also,
who lieth in wait to steal into men`'s minds false apprehensions from the Scriptures),
they have not come into a clear understanding,
either of the things or words of scripture; but with that knowledge,
and those apprehensions of things, which they have gathered,
they have many times been ready to fight rather against Christ than antichrist;
and so their confessions of faith, and expositions of scriptures, have been mixed things;
rather suiting to their own beliefs and apprehensions,
than the true nature of the things themselves: yea,
by this gathered knowledge they have been in great danger of a
desperate opposing the pure administration of God`'s truth,
from and in the light and power of his own Spirit.
Likewise the churches they have gathered and built up,
they have done in a way of imitation of what was done once formerly by the power,
and in the authority, of the Spirit; but not in the same power, life, and authority.
I might say the same about their ordinances and duties;
wherein the Lord (God knoweth) hath manifested to others, and can manifest to them,
that they have erred very much.

It is true, ye have rejected some wood, hay, and stubble;
and we acknowledge the Lord`'s goodness to you, in that ye have gone so far.
Yea, but there is yet more to be rejected; and all imitations, and knowledges,
and interpretations of scripture out of the pure life, are to be laid aside;
and the Spirit of the Lord waited upon, in the light which is of him;
to which the mind is to be turned from the darkness, and in which it is to abide.
Now, here ye are very short;
not so much as to come to the outward owning or understanding of the way;
so far are ye from walking therein.

That ye seek to find the power and operation of truth in your hearts,
I do believe concerning divers of you;
and do bless the Lord in reference to any of you that it is so with you;
and from my heart desire for you, that your hearts may be answered by the Lord therein,
and that ye may feel preservation through that which is of him in you;
though distinctly ye know it not, nor how to have your minds turned towards,
and to wait upon, the Lord in it.

So, to seek to have Christ formed in you, and to know union with him,
and a real implanting into him; to know him as a vine, as head, a living stone, a root,
as meat indeed, and drink indeed, etc., this is precious indeed to desire after,
but much more precious to witness: and oh that ye also knew the way, the living way,
wherein God communicateth these things abundantly,
to those who once sat in the desolate and barren places,
mourning and sorely crying out for the want of them! for then ye
would not oppose us for turning people from darkness to light,
but be one with us therein.

The integrity which is in any of you is of God;
and though the soul mistake about a duty or ordinance,
yet the cry therein after him is not wholly rejected and despised by him.
But ye would know much more of him, if ye were acquainted with him in his own way,
and worshipped him in the everlasting ordinance, which is the pure light of his Son;
which was before the letter, brings the soul nearer to the Lord than the letter can,
and gives a fuller communion with the Lord in Spirit,
than can be had or enjoyed through words or conceptions of things.
And the end of the letter`'s testimony is to bring into the
Spirit and power which is the administration of the gospel.

=== Concerning Inward Impressions

All the impressions which are from the holy, pure power of the living God,
are of the gospel administration, and are of great use and virtue;
and he that is gathered out of the dark power, into the pure power of God, who is light,
and who gathers into the light, by the message and ministration of the gospel,
in that light hath a discerning of the power into which he is gathered,
from the power out of which he is gathered.
And here he neither can nor dares receive any impression of the dark spirit and
power (which is known and experienced to work in great subtlety and deceivableness),
nor refuse any motion or impression which is of the pure and holy One.
But ye lay the great stress upon owning doctrinals
according to your apprehensions of them;
whereas ye must come much further out of Babylon, out of man`'s spirit and wisdom,
more into the pure fear and waiting upon God, more into the sense and power of truth,
and into the light and knowledge which is thereof,
before your doctrinals can be owned and subscribed to, by that which is of God.
And this springs in my heart in true love, and tenderness,
and melting bowels concerning you: Oh that ye held the head!
I question not, but that ye hold notions about the head,
according to your understanding of things;
but to hold the head is a far deeper thing than so.

As for that passage about communion with God, apply it; oh! apply it,
or rather wait for the Spirit of the Lord to apply it close to your hearts!
For it is possible, by his light and Spirit, in his own due season,
he may make manifest to you,
that much of that which goeth with you for communion with God, is not really so; and,
indeed, in the true love and upright tenderness of my heart towards you,
I would not have you mistake about these things.
As for raptures, the error is easy;
but in that which lies low in the pure fear is the preservation.
And, friend, I pray consider this question which is now in my heart to thee.
Thou speakest of departing from the faith: ah! friend, art thou yet come to the faith?
Do not answer it slightly; for I put it not slightly to thee, nor without a cause.
For through the faith of the Son of God, another knowledge, and sense of things,
in this day of the Lord`'s power, is received, than thou hast yet attained.

That a man`'s doctrinals are right according to scripture in all the main substantials,
is no infallible rule to try what power it is that works in him, or what his spirit is;
because deceit works in a mystery; and the spirit of error may come in sheep`'s clothing,
and may get good words and fair speeches to deceive the hearts of the simple.
And there were those that held a form of godliness, and had not the true power,
but denied it; and such were to be turned from; because, denying the true power,
they denied the Lord that bought them, and so held not the head; and he that doth so,
whatsoever he holds of the doctrine of scriptures,
hath sufficient cause to question his communion with God,
and also the truth of his ravishments and spiritual enjoyments,
and all his duties and graces.

Again; a man may apprehend his doctrinals to be right, as to the main substantials,
when indeed they are not so.
For the doctrines of the gospel are mysteries.
Faith is a mystery; the love of God in the Spirit a mystery;
obedience to the truth a mystery;
the right confession of Christ in and through the Spirit a mystery;
the worship of God in Spirit a mystery; justification, sanctification,
and the peace and joy of the Spirit, mysteries of the kingdom, etc.,
and it is easy missing and misunderstanding these things,
but hard to come to the true knowledge of them; and if any of the true, inward,
spiritual knowledge of these things be received at any time, it is hard retaining it,
nay, impossible rightly so to do, but in that which gave it.
And, indeed, this is the great mystery of religion; to wit, to begin in the Spirit,
and so to travel on in the pure light, life, and knowledge thereof,
and not to entertain or mix with any thing of the flesh.
But now if a man have not the Spirit of Christ,
or if he be not able to distinguish the Spirit of Christ, in its voice, motions,
and workings, from the other spirit, and from his own wisdom and understanding;
when he reads a scripture, he may easily err and mistake about the doctrines thereof,
and let in somewhat of his own, or the other spirit`'s forming,
instead of that which is the pure truth of God.
And then this which he hath so let in, will cause him to misjudge concerning the truth,
when God manifests and brings it forth purely and unmixedly in others,
and make him a great enemy to it.

This was the case of the Scribes and Pharisees and great priests, in the time of Christ;
they studied the law, gave interpretations of it,
being appointed by God to preserve the people`'s knowledge;
and by their understanding of the law and prophets, Christ could not be the Messiah; for,
plainly, that appearance of his disagreed with the law and the prophets,
according to their understanding of them.
Christ was to abide forever; but he said the Son of man must be lifted up.
Yea, the very disciples themselves understood not this for a long time:
and if the sense of the life and power of the Father
in him had not bowed down their spirits,
they also would have reasoned against him in many things.
"`When Christ cometh, no man knoweth whence he is:
but we know this man whence he is.`" And when Nicodemus (who was
touched with the sense of his power) seemed to savor him;
what said they to him?
"`Search and look, for out of Galilee ariseth no prophet.`" And they themselves,
in searching, and looking, and trying by the Scriptures, found him not agree with Moses,
and the law which he had given from God (who they said they knew was of God:),
but whereas Moses had given a strict command about the sabbath,
upon which there was no work to be done, nor burden borne, etc., he,
on the other hand bids a man "`take up his bed and walk on the sabbath-day.
How could this be the Messiah, of whom Moses wrote`" (would they say in their hearts)?
Would he teach and practise contrary to Moses?
So that there is no certain trying by the Scriptures,
further than a man is certain that he hath the understanding
of those scriptures which he trieth by,
from God`'s Spirit.
For was not this plain to them, that no burden was to be borne on the sabbath?
And do they not herein (according to their understandings and knowledge
of the Scripture) find Christ contrary to Moses and the prophets?
What then would follow naturally?
A deceiver! a deceiver! would they presently cry.
He cannot be of God; let him talk of what power he will, it cannot be of God`'s power:
we need a further sign from him, before we can believe him to be the Messiah.

But the way of trying doctrines by the unerring Spirit,
and pure light of truth in the heart, is certain and infallible.
He who is truth, and no lie, never deceives about truth; yea,
the very instinct of his life and nature distinguishes things truly,
and never teaches the heart to err, who is acquainted with it, and keepeth to it.
And what is the Spirit which is given, and why is he given?
Is he not above the letter?
And where he is received, is he not to be acknowledged above it?
Is not his law of light, written by his finger in the heart,
above any literal description or command of it?
We must set the Spirit above the Scriptures,
and the ministration of the Spirit above the ministration of the letter.
We cannot be clear before the Lord, in giving way to any professors on the earth herein,
but must testify for God against them.
Yea, he that hath received the anointing, and knoweth how it teacheth,
and how it preserveth from all that seduceth, cannot but give the honor to it,
and acknowledge that it is the great ordinance of God in the gospel,
even above and beyond the letter.
And till he is so known and received,
men can never be able to distinguish the truths of God,
as held forth by him in the Scriptures of truth,
from their own conceivings and apprehensions about things,
but will be ready to take their own apprehensions and conceivings for truth;
and having so done, they cannot but mis-see, mistake,
and misjudge about that which is truth indeed.
So that the doctrine which they thus set up,
is not indeed the doctrine of truth according to the Scriptures,
but rather that which they conceive and have imagined so to be.

So that, whereas thou sayest, "`Your religion consists, first, of right apprehensions,
etc.`" we, on the other hand, cannot but testify, as we have been convinced by the Lord,
and felt and understood in him that is true, that a man must first receive the Spirit,
before he can have right apprehensions about the mystery of God, Christ, etc.,
because the Spirit searcheth the deep things of God;
and the things of God knows no man but by the Spirit; therefore,
there is a necessity for people first to be turned to the Spirit of God,
as being the first step in the way to true, saving knowledge.

=== Concerning the Light

Christ, who had all power given him by the Father,
and authority to send forth messengers to preach the gospel of his salvation,
he sent forth his apostles and servants to testify and declare of it.

That which they were to preach and testify of, was,
"`That which was from the beginning;`" even the "`eternal life, which was with the Father,
and was manifested unto them.`" And this is the message which they heard of him,
and were to declare to others, "`That God is light,
and in him is no darkness at all.`" And this Word of faith,
this Word which was from the beginning, this Word which reconciles the soul to God,
they were to preach, as near in the heart and in the mouth.
And the intent of their preaching and testifying of this, was to turn men to it;
from the darkness within to the light within;
from the power of Satan within to the power of God within.
Thus was the gospel preached before the apostasy,
and thus is it again preached after the apostasy; and this light, this life,
this power of the invisible Word, is witnessed again to become the salvation,
as it was before the apostasy.

Now here, being turned to this, this discovers the darkness, the lost estate,
the captivity, the bands, the misery of the soul, and gives to long after the Saviour;
and not only so, but it also showeth the Saviour whom it causeth the soul to long after;
and in the waiting upon the Saviour in the light which is of him,
giveth to partake of his salvation.

And so here we come to have that work of God renewed in our hearts and spirits,
which at any time was formerly wrought; and wrought more clearly and effectually;
as it must needs be, as the mind is turned toward and gathered into the pure light, life,
and power.
And in this we are taught to own Christ, as he appeared in that body of flesh,
and what he did in the life and virtue of the Father; yea,
the preciousness of that his sacrifice, both in its own nature,
and in the eye of the Father; and we bless the Lord for him,
and believe in the Father through him.
Yea, we bless the Lord for the declarations of the good things in the Scriptures,
and read them with joy and thankfulness to the Father,
and in the watch against that which would imagine about them;
for we know any such thing (let into the mind) darkens.
So that we do not fall short in a true owning of Christ, as he appeared in that body;
and also we know and own the same Word of eternal life appearing in us;
so that we can say truly with the apostle,
"`It hath pleased the Father to reveal the Son in us, and it is the eternal life,
it is the Son indeed of the Holy God, and not another.`"

Now, for that way of working which thou speakest of, of seeing a man`'s nakedness,
filthiness, wretched, lost, undone condition; of being convinced of his own impotency;
that his help is not in himself; that all his righteousness is as filthy rags;
of crying out, what shall I do!
Woe is me, I am undone!
What shall I do to be saved?
How shall I appear before the Lord?
And so of mourning in secret, and the sore running, etc., and the discovery of Christ,
as was in that day, as offered without money, without price, etc.,
and so the soul`'s humble and cordial casting itself upon him, etc.,
and desiring to know him, not only as a Saviour, but as a Lord also, reigning over it,
etc.--all this we knew, in the true and sensible experience,
as it was revealed in that day.
But we knew not the Word of life within to be the
Word (though we felt operations from it);
and so were not founded upon the rock, upon the Word of life, as revealed within;
and so when the storms came,
they had greater power upon our spirits than we believed they could possibly have.
And now in the Lord`'s fresh visiting of us, we have not lost any thing we had before,
nor do deny any thing that God wrought in us then; but have it again with advantage,
and precious additions, from the Lord God,
in that pure light of life wherewith he hath visited us.

And now God having demonstrated this thing to us, showing us what it is,
and giving us to partake of the precious virtues of it;
how can we call it less than a measure of Christ, of his Spirit;
than the seed of the kingdom; than the heavenly leaven,
etc.? knowing and experiencing it assuredly to be
that very thing which Christ so called in his parables;
and that in you which is offended at us for it, we know to be not the true birth,
but the birth of another wisdom, which is to be cast out with its mother:
and it will be a happy day with you, if ever ye come to witness the casting of it out;
which ye can never do, till ye come to know, and own, and be subject to, Christ within,
to the pure commandment and Word of life in the heart,
to the law which cometh out of Zion,
and to the testimony and word of the Lord from Jerusalem.
And they that come not to know it cast out of them by the power,
they thereby will be cast out with it.

But that there are some glimmerings of light remaining in fallen man,
directing concerning many things morally good, as to honor parents, to deal justly,
to do as we would be done unto, etc., there is, thou sayest,
a light discovering these things as duties, and the contrary to be evil,
and there is also some answerable strength to come up to such moralities.
If thou meanest a light distinct from the Spirit and divine nature of God,
I desire thee to manifest it from scripture:
for Adam was to die the death that very day that he sinned.
And the death and curse came upon his posterity, who are dead in trespasses and sins;
but the light that discovers and leads out of evil is from Christ.
That which maketh sin manifest, is his light.
I read that the grace which bringeth salvation, hath appeared to all men;
and that that teaches men to deny ungodliness and worldly lusts,
and gives them strength so to do;
and that it is the work of the Spirit to convince of sin;
and that the Spirit of the Lord strived with the
old world to reduce them from their evil ways;
and that he gave the Jews his good Spirit to instruct them,
but they rebelled against him:
but that there are some glimmerings of light distinct from the Spirit of Christ,
teaching fallen men to do this, and some answerable strength in him to walk up thereto,
I read not.

It is the promise of the new covenant, that God will write his laws in the heart;
and whatever of his law is written in any man`'s heart, it is by virtue thereof;
for man is dead unto God`'s law naturally, and his eye blinded by the god of the world:
but that which opens his eye to see what the law saith, is the light of the Spirit.
For that which maketh manifest is light;
and that which may be known of God in the Gentiles
is made manifest to them by the light of God in them;
which shineth in their darkness, but their darkness cannot comprehend it;
but it fathometh and comprehendeth the darkness,
and is able to gather the mind out of it, being subjected to it,
in the will which it creates and begets, through the eternal power which visits by it,
and is present with it, to work the mind out of, and deliver it from, the darkness.
And as this light comes from Christ ("`for he is the true light,
that enlighteneth every man that cometh into the world`"),
so it discovers and maketh manifest Christ, in his nature and Spirit,
and leadeth and guideth towards him; and he that is led to him in Spirit,
and born of him in Spirit,
cannot miss of the benefit and virtue of what he did in that body of flesh;
being gathered into and found in that which is of him, to which all belongs.
And in and by this is received that nature wherein the law is answered;
and the work of answering the law is through the renewing of the mind,
and an evidence of somewhat of a new nature;
every degree of which nature is begotten and maintained by Christ, the power of God;
who is over the fall, and the whole corruption thereof.
But by the old corrupt nature or mind, can no man do the things contained in the law;
for it is enmity against God, and is not subject to his holy law, neither indeed can be.
But the law is spiritual, holy, just, and good, converting the soul,
and making wise the simple; which work it effecteth,
wherever it is written in the heart by the finger of God`'s Spirit.

Then again, as touching God`'s imputing Christ`'s active and passive obedience, etc.,
we do not lay the stress of justification in believing a
notion concerning Christ`'s active and passive obedience;
but this we know, that Christ did obey and suffer, and that it was for our sakes;
and that, for his sake, there is a gift given us from the Father, to draw us to Christ;
and that he that is overcome to God, by the gift of his light,
is thereby drawn out of the darkness;
and that that gift brings every man (that hears the heavenly voice thereof,
and follows it) into the Son`'s light, into the Son`'s nature, into the Son`'s life,
into the Son`'s Spirit;
in which the Gentiles might partake of remission of sins for his sake,
being gathered thereby out of the darkness, into his light and power.
For though they had never heard the outward sound or name Christ; yet feeling the thing,
and being gathered to God by the thing,
the value and virtue of it could not but redound to them; for it is not the outward name,
but the inward life and power, which is the Saviour.

And whereas the voice of the Spirit saith, "`Ho, every one that thirsteth,
come ye to the waters;`" what are the waters to which the thirsty are invited to come?
Did we not believe in Christ, and cast ourselves on Christ in that day,
according as thou apprehendest?
And yet the thirst and cry of our souls was not satisfied.
But the living waters satisfy the thirst.
Nor is it a believing a relation concerning the thing, but a receiving of the thing,
of the milk, of the wine, of the living water,
which answers the desire of the thirsty soul.
And by coming to the living waters, and hearing the living voice,
and eating and drinking the living food, the soul lives,
and the everlasting covenant is made with it, even the sure mercies of David,
which are sure in the covenant of life forever.
And those that are living, in and by the true life,
cannot desire to reap or enjoy any thing out of the new covenant of life, but only in it.

This is in my heart concerning you; Ye lay the stress upon a notion,
and upon an act of the creature from and upon a notion;
which they that are out of the life may perform;
and who (that hath any sense of a man in him) would not perform, to avoid perishing?
That is, who would not thus cast himself upon Christ,
if believing after such a manner would save him?
And yet there is also a difference, a very great difference, between doing of it now,
when Christ is generally owned as the Saviour, and doing it then,
when he was generally disowned.
Then, who thus believed, it argued the teachings of the life and power so to do;
but now the form of owning Christ is far more common than any form or way of disowning.
So that now, not the word, nor the form, nor the outward owning,
nor the casting of the soul upon Christ, is so much to be considered or valued;
but rather the power, the light, the life, the gift,
wherein and whereby this is alone rightly and truly done.
And he that owneth Christ aright will own that which is of Christ,
the manifestation and gift of his Spirit, the shining of his pure light,
first in the darkness, and then out of the darkness,
to that mind which it hath gathered and preserveth out of the darkness.

And then for being complete in Christ in a relative way, while the heart is unmortified,
and unsubdued to God; it is a dangerous mistaking about these things.
I do confess that sins are pardoned upon a true belief,
and the soul enters into the covenant of life, and is accepted with the Lord,
as it finds entrance thereinto, and walks therein.
And there is no condemnation to them that are in Christ, "`who walk not after the flesh,
but after the Spirit.`" But if there be a hearkening to the flesh,
and walking after the lusts and desires thereof, is there no condemnation then?
Is not the justification in the covenant, and according to the laws of the covenant?
Alas, alas! how do men imagine concerning things! and so, in their imaginations,
justify themselves wherein the Lord condemns them; and know not the way of the covenant,
and of the justification thereof.
For there is a new covenant, as well as an old (and the new is not like the old);
and a walking with God in the new covenant; and every step in it his life justifies,
and every step out of it his life condemns;
and the Mediator of the new covenant justifies it according to the new covenant,
and never otherwise.
For the way of God is perfect (the way of life, the way of reconciliation,
the way of redemption), and the soul is only accepted and justified of the Lord therein.
Yea, justification is a mystery to man`'s wisdom and understanding,
with all his knowledge he can gather from scripture: and he only knows it who feels it,
and hath the experience of it, in that which is true, and which cannot deceive.

=== Concerning Justification

The apostle James saith expressly, that by works a man is justified,
and not by faith only; and his words were from God`'s Spirit, and are true,
and the Lord saw a use and service of them.
There are works which are excluded the covenant of life,
and there are works which are not excluded, no, not to justification.
There are works required by the covenant;
works wrought in the faith and by the power of God;
and when they are brought to the light,
it is made manifest that they were wrought in God; even works that are of his Son,
wrought in the life and by the Spirit of his Son, and these the Father always justifieth.
Yet we do not say this is a man`'s justification for his sins past,
but they are forgiven for his name`'s sake: nor do they expiate sins afterwards committed,
etc., but the advocate intercedes, and his blood washes them away.
But this we say, that alone in the faith, in the obedience of the new covenant,
the justification of the new covenant is witnessed:
and the new covenant justifeth no sin, nor the soul in sin; but purgeth away the sin,
and justifieth from it,
washing off the venom and defilement of the wicked spirit from the conscience,
which the Lord purgeth by the faith,
and by the virtue of the water and blood which the faith brings in.

Now, having been led by God into the pure covenant of life,
and having there had the true sense, knowledge, and experience of things,
even of the truth as it is in Jesus,
we cannot but speak and testify of it as we have felt and received it;
and here we know and find certainly and infallibly,
that it is not the law of works which justifieth the believer,
nor the obedience or righteousness thereof; but there is a righteousness revealed,
of a higher nature and kind than that righteousness of the law,
which is made the soul`'s in and by the faith.
And this is Christ`'s righteousness the righteousness of his life,
the righteousness of his nature, the righteousness of his Spirit,
which is revealed in the soul, and which, in the union with Christ, becomes the soul`'s,
and Christ thereby is made of God unto us righteousness.
And the works which are wrought in man by this righteous
Spirit and holy power are of far more value in themselves,
and of more acceptation with God, than man`'s obedience to the law could be,
could he obey ever so exactly; for these are from a higher principle,
and of a far more excellent nature, spirit, and kind, than man`'s nature and spirit is;
and yet the acceptance is not for the work`'s sake,
but for the sake of the worker of these works.

=== Concerning God`'s Love to Mankind

Great is the love of God to mankind, who desireth not their destruction,
but their redemption and salvation from that which destroyeth.
Now, from and according to this love, he sent Christ as a ransom,
a propitiation for the sins of the whole world: and not only so,
but he hath given him as a light to enlighten all the dark parts of the earth,
that every soul might believe in his life,
and by its guidance and power come out of the darkness:
and the free gift is as large and as powerful to save,
as the offence or offences are to destroy.
So that God hath not only said it,
but he hath manifested that he desireth not the death of a sinner;
but would have all men to be saved, and come to the knowledge of his truth,
and gift of his grace, that they may be saved thereby.
And this is the gospel, even the grace which bringeth salvation,
and the power of eternal life, to all men`'s doors;
by and in which the Spirit of the Lord God (who is able to save) strives
with them and in them (according to his pleasure) against the enemy.

Now, for men to interpret a scripture so as to overturn this,
contrary to the very drift of the gospel,
and contrary to the very nature and heart of God, they do not well,
nor by the guidance of his Spirit in so doing.
And now in love to thee, though I have not much freedom to open these things,
knowing that they are above the state of most people to understand,
and that it is rather proper for them to wait in what is clear and manifest,
than to meddle with things hard to be understood, and deeply mysterious,
before the Spirit of the Lord opens them to them: yet I say,
in love I find freedom in the Lord to say a little to thee.
Mind the words of the apostle, in fear and reverence towards the Lord.
"`What if God, willing to show his wrath, and to make his power known,
endured with much long-suffering the vessels of wrath fitted to destruction?`"

Now consider, how is God willing to show his wrath,
and to make the power of his destroying a vessel known?
Is it a thing natural to him?
Is it not contrary to his nature to destroy?
Any who can testify any thing of the life of God in their hearts,
do they find any thing of a destroying nature in it?
Christ, who was the express image of God, did not he come to save?
Did he come to destroy any?
And when any resisted the counsel of God against themselves, was it not grievous to him?
"`O Jerusalem!
Jerusalem! how often would I have gathered thee!`" Here the
heart of God towards the sons of men may be read,
as in a true glass.
And before the Lord gives them up to destruction,
doth he not endure them with much long-suffering?
And is it not the proper intent of the goodness, forbearance,
and long-suffering of God to lead men to repentance? Rom. 2:4.
And they that are led by the long-suffering to repent,
do they not witness it salvation? 2 Pet. 3:15.
Ah! wait on God,
that thou mayest understand these things from him as they are;
and not according to the imaginations and reasonings of thine own wisdom and understanding.
It hath been a long night of darkness,
wherein many misapprehensions and false conceivings
upon scriptures have been swallowed down,
which the Lord pitied us under, and bare with us in them;
but now it is high time to bow down to and receive that light which
purgeth the vessel from all such misapprehensions and misconceivings,
which are as really hay and stubble in the sight of God,
as the grossest darkness of popery is.

=== Concerning Baptism

We own the one baptism; and, blessed be the Lord, are baptized therewith into one body.
That of water was but the forerunner`'s, but the shadow of Christ`'s baptism,
which is with the Holy Spirit and fire.
Now, when Christ sent his apostles to preach and baptize,
did he send them to baptize with the forerunner`'s baptism or with his own baptism,
when he said, "`Go teach all nations,
baptizing them into the name,`" etc.? Paul professeth openly he was not sent to baptize,
but to preach the gospel.
Was he not an apostle?
Had he not seen the Lord?
Had he not his commission from him?
Did not the apostolic commission contain baptism as fully as preaching?
Is it not said, "`He that believeth, and is baptized, shall be saved`"? Yes, without doubt,
it did contain Christ`'s baptism (without which there is no salvation) as well as preaching;
but the baptism of water,
which was a figure of the thing (which Paul did find freedom to do to some),
Paul said he was not sent to do.
He did it not by commandment, but he might do it by permission, as well as circumcise;
which was another figure of the same thing.

=== Concerning Perfection

Christ is a perfect physician,
and is able to work a perfect cure on the heart that believeth in him,
and waiteth upon him: yea, he came to destroy the works of the devil,
to cleanse man`'s mind of the darkness and power of Satan,
and to fill it with the life and power of truth;
and he sent forth a ministry not only for the beginning,
but for the perfecting of the work: yea, his Word in the mouth and heart is powerful,
sharper than a two-edged sword, and he can cast out the strong man,
and cut down all that is corrupt and contrary to himself,
and break down every strong hold in the mind, and spoil all the goods of the enemy.
Christ likewise bids his disciples "`be perfect,
as their heavenly Father is perfect;`" and the apostle bids men "`perfect
holiness in the fear of God,`" that they might be fully separated from,
and not so much as touch, the unclean thing;
but enjoy the promises of God`'s dwelling in them, and walking in them, whose temple,
under the gospel, is to be pure.
And if a man wait upon God in the work of purifying,
and witness the power and virtue of the new covenant, even the fear put into the heart,
which keepeth the heart clean, and will not suffer it to depart from the Lord,
and witness the powerful law of the endless life giving
him dominion over the law of sin and death in the members,
and the Spirit of the Lord put within him, causing him to walk in his ways,
and to keep his statutes and do them; surely this man cometh near to perfection.
Did Christ cure perfectly outwardly in the days of his flesh;
and shall he not cure perfectly inwardly in the day of his Spirit?
Yes, certainly; the lame, the deaf, the blind, the dumb, the lepers,
waiting upon him in the way of his covenant, shall be cured by him as perfectly inwardly,
as ever others were outwardly.
And then is the day of joy, and of reaping the good things which the promises contain,
feeding on the feast of fat things on God`'s holy mountain, in peace of spirit,
in security from the soul`'s enemies,
none of them being able to come near to hurt or destroy; nay,
not so much as to make afraid on the mountain of God`'s holiness:
and then the song of Moses, and the song of the Lamb is sung,
and walking in the way of holiness witnessed; which no unclean thing can pass over to,
but only the ransomed and redeemed of the Lord.

Now, if any man come in truth to witness this from the Lord,
and hath found by his consuming fire the dross burnt up in him,
and his soul cleansed from what is corrupt and unrighteous; doth he deceive himself,
or is he a liar, if he say, the Lord hath cleansed me from all my unrighteousness?
And did John speak here of his own state,
or of the state of the other apostles and believers,
who were grown up in the life and power of truth, and had overcome the wicked one,
by the strength of Christ in them?
or did he speak condescendingly (as the apostles often did with the weak:
becoming as weak,
when they were exalted by God to a higher state than that condition signified)?
Had he not fellowship with the Father and the Son?
And was not his joy full?
And is the joy of any full, while sin, while corruption, is near and hath power;
while Satan, while the powers of darkness, are not trodden under foot?
There is a state of righteousness without Christ,
wherein if a man say he hath no sin (and so thinks
he hath no need of Christ) he deceives himself.
But there is a power in Christ to perfect the work of redemption in the heart;
to sanctify the creature wholly, in body, soul, and spirit; yea,
his leaven received will work, and works daily, till it hath wrought all out,
and the whole be leavened; and he that truly feeleth it so, can say in God`'s presence,
and in the true fear and humility of heart, The old leaven is wholly wrought out,
and the new hath wholly leavened me; this is not the voice of deceit,
but of truth in him.

[.discourse-part]
As for that question,
Whether Christ hath not reigned in his Spirit all along in the souls of his true people?

[.discourse-part]
Answer.
There hath been little of Christ`'s reign in Spirit witnessed all along the apostasy.
It is a great matter to come to witness Christ`'s reign in the heart: yea,
there are many who never yet came through the suffering which goes before the reign:
but the cross, the power of the cross,
and the thorough death thereby of all that stands in the way of Christ`'s pure reigning,
is yet to be taken up, and many journeys to be gone,
before men come to witness Christ`'s kingdom, and the reign of his Spirit therein.

There are some other passages which I find in my heart to say somewhat to.
One is this: "`That ye know through mercy when ye are well; that ye are satisfied,`" etc.

There hath been a cloudy and dark day; which for its thickness, may well be called night;
wherein the people of the Lord have been scattered from mountain to hill,
seeking their resting-place.

Now, it hath pleased the Lord, after this thick night of darkness,
to gather the scattered sheep,
and to become the physician (in the ministration of his Spirit, life,
and power) to heal them, and bind them up.

And those that have been sick and distressed, and brought into the true sense,
they feel the need of the physician,
and bless his name for the healing which he bringeth with him under his wings.

But there are some that are fat and strong,
and whole and complete by an imputed righteousness, according to their own apprehending;
and these are well; these are satisfied; they have no need of this visitation of God,
nor of this dispensation of life and power from on high.

There was a church once, before the apostasy took place,
that knew the truth better than ye do, that said, she was rich, increased with goods,
and had need of nothing; and yet wanted the tried gold, the white raiment,
and the eye-salve.
And if ye knew how aright to wait on the Lord, and receive counsel and light from him,
perhaps ye might therein see also, that ye are destitute of and want the same things.

Now, in that we testify to you that we have been in your state, and fully experienced it,
and seen in the light of the Lord the truth thereof, and the defects thereof;
and in love, and in the leadings of God`'s Spirit, are drawn to testify thereof to you,
and have from him received the knowledge of the living way,
which was made manifest before the apostasy, and is now again;
and are taught and enabled by the Lord to walk with him therein,
the Lord having led us into that, and brought us forth in that,
from which all the apostates have erred, and out of which they all are;
this should not be a thing slighted by you; but being a weighty testimony,
and of great concernment to you, should be weightily considered of,
and determined in you, by that which alone is able to decide it.
Now, if ye weigh this testimony by scriptures,
and have not a true understanding of those scriptures from God,
ye will but thereby err the more, and be the more confident and hardened in your errors,
and so go on in a kind of satisfaction and peace in kicking against the pricks.

And as for our confidence, we can truly say in the Spirit of truth,
we know that we are of God,
gathered unto him by the life and Spirit of his Son revealed in us;
and we could eat our bread in secret,
and drink the water of life out of our own cisterns silently,
but that the Lord required us, and his love constraineth us,
and it is due to the glorious work of his mercy and power towards us, to declare,
in the seasons of his choosing, what the Lord hath done for our poor, distressed,
mourning, wandering, undone souls.
Now, if others are confident without a cause; that doth not make void our confidence,
which is grounded upon the truth; nor the testimony thereof,
issuing forth from and in the truth: but that which is of God heareth and owneth it,
and feeleth the work of his love and great power, and blesseth his name therefor.

As for those expressions, It is enough for thee that Jesus Christ is thine, etc.,
so far as thou feelest union with him, in the principle of life which is of him,
thou mayest say so truly.
But is it not strange, that thou shouldst be of it, and not be able to know and own it,
in this day of its manifestation; but call the light, which is spiritual and eternal,
(and gives the true and certain knowledge of Christ) natural?
What! of God, of Christ, (having received the Spirit,
the living well) and yet not know the mystery of life within,
nor its pure voice in this present day! but limit the unlimited One to a form
of words formerly spoken by him! how do these things agree with what thou professest?
Surely they are deeply in the mist, who know not Christ from antichrist;
but fight against Christ and his light, as if it were of antichrist or nature.
Now, we are one with any of you (though ye know it not)
so far as ye know and are of the truth,
and feel true union with whatever is of God in you.

Thus in faithfulness to God, and in love to truth, and tenderness to thee,
I have given forth that which sprang in me towards thee.
And, indeed, I singly breathe to the Lord in my spirit,
that it may be serviceable in the hands of the Lord for thy good;
even to shake that knowledge and sense which is not of him
in thee (though thou strongly believest it to be of him),
and so to bring thee to the infallible sense and experience of the true foundation,
and to a fixed building and establishment in Spirit thereupon,
in that light which is of the Father;
that therein thou mayst own and partake of the ministration of
the everlasting and pure power in thy present day and generation;
which is now so dispensed as it hath not been since the night of apostasy.
Blessed be his name, whose light shines, whose life is made manifest,
whose power is risen out of, and reigns over, the darkness;
whose love and mercy abounds in the hearts of his redeemed ones,
who abundantly partake of the covenant of life,
and of the precious promises of the gospel,
to the praise of the riches of the grace and mercy which
were to be revealed in the ages to come after the apostasy,
and are so revealed, and are yet more to be revealed,
to the increase of the glory of his name,
and of the joy and consolation of his redeemed ones;
who find that to be God`'s power and wisdom, and mighty redemption to them,
which to others is a stumbling-block, weakness, and foolishness: and he who ever was,
and still is, the life, is once again become a stumbling-stone,
and rock of offence to both the houses of Israel; who though they have longed after him,
and breathed for him, and prayed that his kingdom might come; yet now, when he is come,
they know him not, but are wise and strong in resisting and opposing him;
which is much to their hurt and great danger,
as the Lord God seeth in the light wherein he dwells, and as he hath given his children,
who dwell with him in the same light, to see with his eye.
And, friend, take heed that thou turn not the edge of thy weapon,
even of thy scripture-knowledge, against Christ (there were those that once did so),
nor that thy table become thy snare;
for that was the curse which lighted on those who opposed Christ`'s appearance in flesh;
and it may also (in the just and most righteous judgment of God)
befall those who oppose his appearance in Spirit in this his day.

And as for what I have written unto thee,
thou shalt one day witness that I have written to thee in true love,
and in the true light and sense of truth:
and if thou canst retire into that which is of God in thee,
and receive the true sense and understanding there, thou wilt there feel it so now.
And oh that thou couldst distinguish between God`'s witness in thy heart,
and the voice of thy understanding and gathered knowledge!
that thou mightst receive a being,
life, pure sense, and understanding, in that which is pure of God;
that the gold might be separated from the dross,
and there might come forth a vessel for the refiner!

I am a lover of souls, and an earnest desirer after their welfare;
but especially of such as breathe after and long for communion with the Lord,
in that which is living and pure.

[.signed-section-signature]
Isaac Penington

[.signed-section-context-close]
25th of the 11th month, 1667

=== a Reply to Thy Animadversions

[.inline]
==== To the First

A man is justified upon account of Christ, of being in him, believing in him,
obeying his gospel.
All these have reference to justification, according to the soul`'s experience,
and according to the Scriptures, and none of them are to be excluded.
God hath appointed Christ to be a prince and a Saviour, to give repentance, faith,
and remission of sins; and in the exercise of that repentance and faith,
the righteousness and justification is received.
And the Lord condemns the unbeliever, because he believes not; and the disobedient,
because he obeys not the gospel: and he also justifies the believer and the obedient,
because of the faith and obedience of his Son which he finds in them.
And in this faith, the righteousness, the pure righteousness, flows;
the Spirit of the Lord covers; and it is not only the principle, but also the garment,
of righteousness and salvation; yea, all that Christ did in the flesh comes in here,
and the soul feels and partakes of the virtue and value of it all, being found here.
But out of this are the notions and imaginations of men`'s minds,
upon and about scriptures concerning the thing;
who indeed and in truth (as it really is) know it not.

[.inline]
==== To the Second

There are two covenants, and there are works of each, works required by each.
In the old covenant, obedience to the law of Moses is required.
In the new covenant, believing in Christ ("`this is the work of God,
that ye believe in him whom he hath sent`"), and obedience to his gospel and Holy Spirit.
Now these, and the works of the old, are not one and the same,
nor have the same acceptance and justification with the Lord.
Nay, though a man could perform all the law of Moses exactly,
yet would he not be therein so justified in the sight of God as the believer is;
his faith and obedience, which he receiveth from Christ,
and performeth in the strength of his grace and new life, being of a higher kind,
and more excellent nature,
than man`'s fulfilling the law in his own natural capacity and principle can be.
I am sorry thou hast no better a knowledge and savor of the things of the kingdom,
than to testify a dislike of this distinction.
And as for the Papists, we meddle not with them, farther than we are led by the Lord:
for my part, I know not what they hold as to this thing.

[.inline]
==== To the Third

God did threaten the Gentiles (wishing them to take heed of boasting against the Jews),
that if they did not continue in the faith and in the fear,
they should be cut off as the Jews were.
Now, there was a great and general departing from the faith,
and answerably a general cutting off.
And though life was reserved in a select number in the wilderness;
yet the true way of gathering into churches and the church state fell.
And now being fallen, the Lord alone is able to rebuild, as he built at first.
Now, men reading the scriptures of the glory of the former church state,
have been longing after it (which was good),
but withal too forward to thrust themselves into it, and build by imitation,
without the clear light, leadings, and guidance of the Spirit;
and so have not built up in the same life and power by which the building was at first,
and can alone be truly raised again.
Now, the Lord being come forth in his power, and raising up his own building,
the same Spirit that raiseth up that testifieth against all the others,
which are raised up without it.
And, indeed,
the testimony against the present churches and congregations gathered out of the power,
is God`'s, not ours.
But consider seriously; John had a reed given him to measure the temple, etc.,
when part was to be reserved for God, and part to be given to the Gentiles.
But who gave you power to gather churches,
or practise those which ye call church ordinances?
"`Who hath required these things at your hands?`" And where dost thou read,
that the Gentiles did tread down the outward court after it was given them?
They trod down the holy city, indeed, forty-two months.

[.inline]
==== To the Fourth

So far as you see, hear, taste, feel any thing in the pure light of the truth,
as it is in Jesus, we rejoice therein; and heartily desire the increase thereof in you:
but we would not have you mistaken about these things.

[.inline]
==== To the Fifth

Concerning the word or commandment which Moses speaks of,
and which Paul said was the word of faith which they preached.

If the first covenant had been faultless, there had not been place left for a second.
"`For if there had been a law given, which would have given life,
righteousness should have been by that law.`" But notwithstanding
the wonders which God did in Egypt and the wilderness,
and the giving the law and ordinances, etc.,
yet the veil was upon them and "`the Lord had not given them a heart to perceive,
nor eyes to see, nor ears to hear, to that very day.`" Duet. 29:4. Well then,
there was a necessity of another covenant;
and these words which Moses now speaks to them from God,
were words concerning another covenant besides that made in Horeb.

But where is the commandment of this covenant?
Where is the law of this covenant?
Where is the Word of this covenant?
It is not hidden from thee, neither is it far off.
It is not in heaven, that thou shouldst say, Who shall go up for us to heaven,
and bring it unto us, that we may hear it, and do it?
Neither is it beyond the sea; "`but the Word is very nigh unto thee, in thy mouth,
and in thy heart, that thou mayest do it.`" And this nigh Word,
this Word of the other covenant, whereby God circumciseth the heart,
to love the Lord God with all the heart, is the Word eternal, and no other;
who hath received the power of the Father, and none else hath received it:
and in the obedience to him, his righteousness is revealed and received,
and made the soul`'s, from faith to faith.
And it is in vain for you to think to blind our eyes either concerning this scripture,
or concerning the thing itself which this scripture testifies of;
God having opened the eye and heart, which sees and knows, and which,
in the true light which is from and of the Word, sees him who is invisible and eternal,
even the life, holy power, wisdom, and righteousness,
which was in and with the Father before the world was.
And this was the Word, before it took up the body of flesh, and is still the Word,
and no other; and its commandment is life eternal; in the pure faith whereof,
and in the pure obedience whereto, he giveth life abundantly:
but out of the faith and obedience thereto, he doth neither give life,
nor the justification of life;
but the deceits of the enemy there prevail in men`'s minds concerning these things.

Now, had the Jews under the law come to this Word,
they had by the light thereof understood the law, and by the power thereof fulfilled it.
And when Christ and the apostles preached, had they that heard, felt this Word,
they could not but in their hearts have believed him to be the Lord,
and also have confessed his resurrection from the dead; which, in that day,
it was a great thing to confess, being not revealed by flesh and blood;
nor the testimony then easily swallowed by the fleshly and earthly part,
but generally opposed by it.
But now these things are received and acknowledged by multitudes without the power;
and as so received, are of no value, nor can save; but the owning and receiving,
and being born of the Spirit, life, and power (which was in him), saves,
and gives such an acknowledgment of these things, as is of the life and power,
and accepted with the Father.

But, alas friend! how hast thou wrested and perverted this scripture,
turning aside the intent of God`'s Spirit, and putting thine own meaning upon his words,
striving to make them speak what thou wouldst have them!
Is this reading of the Scriptures in reverence, humility, and godly fear?
Oh that God would give thee a sense of what thou hast done herein!
For neither Moses nor Paul doth thus restrain them,
nor mention any such sort of people as thou speakest of; but thou, by thy exposition,
makest void the mind of God, and the drift of his Spirit in the Scriptures.
If thou hast, in this wisdom and latitude of thy own spirit, read the Scriptures,
not knowing God`'s Spirit to gird and limit thee from thine own apprehendings and conceivings,
what kind of rule hast thou made to thyself out of them?
Ah friend! if thou knowest God`'s Spirit, keep to it; if thou knowest it not,
wait for it to become thy guide and leader,
and the opener of scriptures and the mysteries of the kingdom to thee.

The light which enlighteneth every man that cometh into the world,
and the eternal Word or Son of God is the same.
And this light shining in the darkness, shineth and enlighteneth with the true light:
and the end of its enlightening is,
that therein men might feel the drawings of the Father, the strivings of his Spirit;
and in the faith thereof, and subjection thereto, come out of the darkness.

Now, the condemnation is not because Christ hath not sufficiently enlightened them,
or that there goeth not sufficient power with his light to redeem from the darkness;
but because men turn the deaf ear to him, will not hear him, but in love to the darkness,
hear the voice of him who dwells in the darkness.
But the Spirit of Christ, who is in the light, and dwells in the light,
who strives with the dark world by his light,
is able to conquer and overcome the darkness.
Yea, the Word of life, nigh in the mouth and heart,
is able to overcome the power of death there, to quicken, to gather to God,
to set the captive free, etc.
And the reason why men perish, is not through God`'s insufficient visiting of them,
but because of their turning from the measure of the manifestation of his Spirit.
They despise the day of small things;
they will not come to that wherein the life and virtue was hid,
and so lose the day of their visitation and miss
of the good which God intended to them thereby.

And whereas thou sayest, "`The light doth not, nor cannot, discover Christ,
and his being raised from the dead,`" etc., I cannot but say, on the other hand,
what doth discover them, but the light?
How came the Scriptures to declare of Christ?
Was it not from the Spirit?
And is not the same light still with the Spirit, by which the Scriptures were given forth?
And can he not give it forth without the letter, where he seeth need of it,
and vouchsafeth so to do?
But how can the vast unbelieving multitudes of the world
experience what the light and Spirit of the Lord can do,
being not subject to it, but rebelling against it. Job 24:13.
And why may not men now, by the light of the Spirit,
come to know that Christ is come, dead, and risen,
as well as these things were known and believed before the Scriptures were written?
Yet if a man should not know the outward death of Christ,
and his raising from the outward grave;
yet being in the faith of the power (which whomsoever it toucheth and draweth to it,
it redeems) that gives him a right to all that was done by Christ;
for then he hath union with the thing which saves,
and strength from it against that which destroys.
Yea, there was a time when the disciples of Christ were in the faith,
and yet neither knew nor believed his death and resurrection: yea, Peter,
with no small confidence, said, "`Lord this shall not be unto thee.`" Matt. 16:22.

As touching that passage of renouncing the works not only of the old covenant,
but even those of the new also, as filthy rags,
that is manifestly unscriptural and unsavory;
the works of the new covenant being fruits of God`'s Holy Spirit,
which he works in us and for us.
If any man be in Christ, there is a new creation (where the old things are passed away);
and he that walks after this rule walks in the newness of the Spirit,
and the Spirit moves and lives and works in him.
Not I, but Christ in me.
And as the root is holy, so is also the fruit.
The fear which God puts into the heart is clean, and keeps the heart clean;
and out of the good and honest and clean heart, comes good, honest, and clean fruit,
which is not unclean, like filthy rags.
Read Isa. 64:5. and consider it, waiting on the Lord to open thine understanding.
Were the works which the apostle speaks of,
Heb. 11. and James 2:24. to be reckoned as filthy rags?

Abraham was acquainted with the invisible, eternal Word,
and was turned from darkness to light, and from the power of Satan unto God;
and in his converted estate had the promise of the seed; and saw,
with the rest of the prophets,
through the day of his flesh to the day of his Spirit.
1 Pet. 1:10-12.

David was a spiritual man, and knew the Word of the new covenant;
which is a lantern to the feet, and a light to the paths,
of the children of the new covenant,
who witness and experience their way cleansed by
taking heed thereto according to this Word.
And the precepts, statutes, laws, commandments, ordinances, judgments,
etc. of this Word are a mystery to all that are not acquainted with it.
But they that are acquainted with it, and in the pure fear and humility wait upon it,
they learn of it the way of its precepts,
and are guided by the Spirit of the Lord in the way everlasting.

The wisdom which Solomon speaks of, is undoubtedly Christ, the Word eternal.
It is much thou shouldst boggle at this.
He is the Sun of the inward world, which enlightens the dark inward world;
not that they should abide in the darkness,
but by the virtue and power of his light come out of it.
And, friend, mark these following words,
and wait upon the Lord for the true understanding of them.
Till thou witness the inward Word, with the inward law and testimony thereof,
and know its commandment to be a lamp, and its law a light, etc.,
thou canst never witness the perfect keeping and preservation from the evil woman,
from the flattery of the tongue of the strange woman;
but wilt be apt to lust after her beauty in thine heart,
and to be taken with her eye-lids.
But if thou know and keep wisdom`'s commandments, thou wilt thereby witness life indeed,
according to that saying of Christ, "`If a man keep my sayings,
he shall never see death.`" And Christ directed his apostles
to wait for his Spirit to receive his sayings from,
who teacheth not only the greatest, but the least, in the new covenant;
writing his law in their hearts, which law is light.
And if any man hear the inward voice of wisdom, and turn at her reproofs,
she will pour out her Spirit upon him, she will make known her words unto him.

The same thing that teaches to do justly, and love mercy,
teacheth also to walk humbly with the Lord.
It is the same grace which brings salvation, which teacheth to live godlily,
that teacheth also to live soberly and righteously.
What I had in my former profession and congregational way,
the Lord brake by a mighty hand; but yet in tender mercy he was with me,
preserving me in the midst of the storms, and floods, and roarings of the enemy upon me,
till his fresh visiting of me.
And he visited me with his own Spirit, with the eternal light, life, and power thereof;
and I know it to be the same thing which had been with me from the beginning; yea,
the child, being quickened and raised out of the grave, presently knew its Father,
and cannot but honor and bear testimony to that appearance of truth,
wherewith his Father visited him,
and wherein he hath felt the renewing and restoring of his former work.
And they that knew me formerly, before the Lord dashed me to pieces,
could and did witness, that the Lord had given me true humility,
and my soul did witness a walking with him in the humility which he gave me.
And now I witness from him, in this precious dispensation of his life and power,
the very same humility (and blessed be his name, with great increase),
and a fresh walking with him therein,
in a fresh sense and meltings and bowings of spirit before him night and day.
I do confess I took it to be a natural thing, and overlooked and despised it,
till the Lord opened my understanding, and showed me what it was,
and how he wrought by it, and that it was a mystery hid from all,
but those to whom he revealed it.
And, indeed, I do hang daily upon the Lord in this for life and power,
and am very weak without, but strong as it pleaseth the Father to manifest himself in me,
and to breathe upon me through it; yea, indeed, my life, peace, rest, hope, joy, delight,
etc. is a continual gift from the Father of spirits,
who hath manifested himself near unto me, and shown me his dwelling-place.
And I am satisfied that the Spirit of the Lord, by his immediate light,
is able to reach the darkest heart in the darkest part of the world,
and to turn his mind to, and give him belief in, that which saves,
and to save him thereby.

The word of faith which the apostles preached, and the word of life eternal,
and the light which enlighteneth every man that cometh into the world, differ not,
but are the same; and the light wherewith he enlightens them,
that they might believe in him who enlighteneth,
is of the same nature with the Enlightener,
and sufficient to guide them to the faith of him.
But, friend, take heed of reproaching the truth.
Though thou mayest do it ignorantly, yet it is not wholly excusable.
Hast thou heard the preaching which thou speakest thus slightly of?
If thou hast not, surely thou shouldst have heard and considered,
before thou hadst judged.
Thou settest up thine own understanding,
and a judgment according to the appearance of things to thee,
instead of the true and righteous judgment;
therein exposing thyself to the righteous judgment of the Lord,
who judgeth in truth and righteousness, and far otherwise in this matter than thou dost.

Christ is the pearl of price, or treasure hid in a field.
The field is the world.
The world is in man`'s heart.
And yet this mystery was hid from ages and generations;
and the kingdom which the Pharisees sought, was within them;
who were as far from any sense and understanding of it, as the Gentiles;
and so though it was within them, yet they were without it; they had no knowledge,
no understanding, no sense of it, had reaped no benefit by it,
but were enemies and alienated in their minds from it.
Ah! what palate and understanding is that, to which this is unspiritual and unsavory?
But how bold and presumptuous,
do men`'s apprehensions (which they take up from the letter of the Scriptures,
without the light and leading of God`'s Spirit) make them,
even to fly in the face of that which is certainly known, witnessed,
and experienced to be of God, as well as held forth in the Scriptures, as Col. 1:27,
see the Greek.

As to those harsh expressions, vilifying the truth of our God,
and the conversion to him thereby; I shall only say this; well, friend, go on;
reproach us and our testimony, and the truth of our God,
as being able to lead us no further than morality, etc.,
we assuredly know and experience, and faithfully testify as in God`'s sight,
that it hath led us further into the mystery and power of life,
and into union and fellowship with the Father and the Son,
than your doctrines ever have done or can do.
For the apprehensions of man upon Scriptures are passing away, and the pure truth itself,
which the Scriptures testify of, is already revealed, and further to be revealed,
and to have the glory.

Ye think we set up a natural light, and esteem it spiritual;
but we are taught of God to distinguish, understandingly and experimentally,
between nature, and him from whom nature came; who is the Word of life,
the Lord God of life, besides whom there is no Saviour;
who is near to every man to warn him of, turn him and deliver him from,
the devourer and oppressor of the soul.
Now, though the vessels in which the light shines be natural, and filled with darkness,
and become darkness in the darkness; yet the Discoverer, Reprover, and Checker thereof,
which giveth the living sound in the vessel, is spiritual;
even the Spirit of the Lord God,
which striveth with fallen man in the midst of his darkness and captivity at seasons,
according to his good pleasure.
This the Shepherd of our souls hath taught us, opening our ears,
and causing us to hear and know his voice, and to learn of him;
who is truth and speaketh truth; who is life and Spirit,
and giveth of his own eternal life and Spirit to his children.

[.inline]
==== To the Sixth

What others have been I know not; but this I know concerning myself,
that I was settled firmly in the doctrines which ye now own,
and in the congregational way of worship, till the Lord smote me and brake me to pieces.
Which such as I did converse with (to wit, teachers,
and others of esteem in that way) professed they could not conceive the ground of;
but said it was a prerogative case,
and did not doubt but the issue thereof would be good unto me.
But what if the sheep were scattered, before the Shepherd came to gather them?
What if they were wandering from mountain to hill, seeking their resting-place?
What if they went mourning up and down from one watchman to another,
from one sort of people to another, inquiring after their beloved?
Did this make them unfit to be pitied and visited by the Shepherd?
What sort did Christ gather in the days of his flesh?
Were they not despised of the wise, learned,
settled ones (in their knowledge of the law and prophets)?
But blessed be the Lord, who hath now manifestly revealed the foundation,
and the kingdom that can never be shaken, and in his mercy and tender love,
and by his power, fixed them thereon; that they know in whom they have believed,
and how they came to believe; and have taken up the cross of our Lord Jesus Christ,
wherein the power is manifested to crucify that which cannot otherwise be crucified.

The Seventh hath been largely spoken to already.

[.inline]
==== To the Eighth

The Lord God knoweth that it is not in my heart to judge or set at nought any man;
but in faithfulness to God, and in tender love to souls,
to testify to others what I have seen in his light, as he requireth of me.
And is this setting them at nought?
It is true,
they cannot believe nor receive the testimony in the state wherein they stand;
but that doth not disannul or weaken it; but truth and its testimony stands,
notwithstanding their rejecting and rising up against it.

To the first particularly.
To own and contend earnestly for the Scriptures aright is good;
but it was not good formerly to set up the writings
of Moses and the prophets above and against Christ;
nor is it good now to set up the Scriptures above the Spirit,
or to make them trier instead of the anointing. 1 John 2:27.
For the Scriptures came from the Spirit, and they testify of the Spirit;
and the Spirit is to be received, and to dwell in the soul as in its temple:
and here the King and Lawgiver of the church (with
the balance of the sanctuary) is indeed known.
And he that receives the Spirit is to live in the Spirit, and walk in the spirit,
and in the light of the new Jerusalem; which light is eternal, discovering,
dispossessing, and working out of the darkness, and so taking up its place.

Now, though ye may aim at having things concerning churches, and church-worship,
regulated according to the Scriptures; yet ye may easily err therein,
and cannot but err therein,
if your understandings be not opened and kept open by the Spirit; yea,
ye may not wait for the Spirit`'s gathering and building, but may gather of yourselves,
and build of yourselves;
whereas the apostles were to wait for the power from on high to do their work with.
And were your eyes truly opened, ye would quickly and easily see,
that neither your preaching nor praying is at all like theirs.
They spake what they received from the Spirit; ye,
what ye apprehend and conceive concerning words spoken of by the Spirit.
This is very short of speaking as God`'s oracles.
And one sort of you conceives thus, and another thus, concerning the same scriptures, etc.

[.numbered-group]
====

[.numbered]
_To the second._
Till ye know the Spirit, and come to the true waiting upon the Spirit,
and understand his voice,
ye can never recover the form of sound words by reading the Scriptures;
but will be liable to be setting up your own conceivings and apprehensions,
instead of the truth itself.
And till ye have the true understanding of the Spirit,
ye cannot but also err concerning the power, and about your experiences of things;
and so will be continually in great danger of being deceived,
and of deceiving one another`'s souls.

[.numbered]
_To the third._
Ye have a notion about Christ`'s active and passive
obedience being imputed to the soul as its righteousness,
which the Scriptures speak not;
and which manifests that ye do not know how the righteousness is revealed,
and how the Son is made of God unto them righteousness, who wait upon him in the faith,
and obey his gospel.
For the righteousness is revealed in the faith,
and is further and further made the soul`'s, in and by the faith.

====

[.inline]
==== To the Ninth

God is my witness (whom I worship in spirit,
and in whose fear I write and speak) that I dearly love you;
and in the truth and dearness of love, earnestly desire concerning you,
that ye may not mistake about Christ, his Spirit, his scriptures; about faith, love,
mortification; and about the righteousness, peace, and joy of the kingdom,
or any other spiritual thing; but may know, experience,
and enjoy the truth and substance of things, as they are in Jesus.
Now, if ye know, and have received, the true, living faith, and witness the powerful,
purifying virtue of it, which God hath given to overcome the world,
and the wicked one with; how comes it about that there is such a belief in you,
that it can never do its work perfectly in this world, but only in part?
Surely this belief is not of or from the true faith;
nor to the honor of him that hath given it.
For the spiritual weapons are mighty through God,
to the pulling down of the strong-holds,
and bringing all (even every thought) into subjection to Christ.

[.inline]
==== To the Tenth

That God did as much for Judas as for Peter, is not our doctrine:
for God giveth more or less out of his rich treasury, according to his own good pleasure.
But the unprofitable servant had also a talent given him, which he did not improve,
but hid it in a napkin; and his Lord condemned him therefore.
There were others had talents likewise, which they did improve,
and their Lord accepted and justified them therein; saying, "`Well done,
good and faithful servant, thou hast been faithful over a few things,
I will make thee ruler over many things; enter into the joy of thy Lord.`"

Now, is there just ground for any of these servants to boast and say,
the other had a talent as well as I; but I made myself to differ; I improved my talent,
whereas he did not?
The true Jew doth believe, doth obey the gospel,
and hath praise of God (he that hateth the light, doth not believe nor obey);
and yet he seeth no ground of boasting: for it was not he, of himself,
but the grace and power of the Lord, wrought all in him.
And what is done in and by and through the power of the Lord;
the honor and glory thereof properly belongs to the Lord.
Yea, he that is in the true faith, feels that which excludes boasting,
and keeps in the sense of the love and mercy.
Oh that thou knewest a limit and check to this wisdom, and these reasonings in thee,
which are not of,
but against the truth! as that light which thou despisest would manifest to thee,
if thou knewest the nature and virtue of it, and didst cleave unto it.
In this wisdom and understanding thou mayest read much, and comprehend much,
and be greatly taken with thine apprehensions upon scriptures;
but it is shut out of the true knowledge of them,
and out of the Spirit and power of life, which they that wrote them were in,
and witnessed of.

As for free-will; we own no such thing as man`'s free-will to do good in the fallen estate.
But the Spirit of the Lord changeth and reneweth the will in the day of his power;
and whoever he striveth with, and draweth, may come in the drawing;
virtue issuing out with the drawing from him that draweth.
And this is not the condemnation, that men cannot come to the Son,
that they might have life; but that they do not come; that they do not turn,
at the reproof of his wisdom, from that which he stands ready to turn them from.

There may be high admirations concerning God and his love, in the natural part;
which we have known, and are made able in the Lord to judge of,
since he hath taught us to distinguish of things: and this is chaffy in all sorts of men.
But there is a feeling of the pure nature of heavenly love,
and a sinking therein into the deep sense thereof; and an acknowledging of it to God,
in the humility, in the fear, in the Spirit, and in the power.
Now, this is indeed from the beloved, and accepted with God in the beloved.
And in this his children, who are stripped of their own ability of admiring and loving,
are taught of him to love and admire him,
being gathered out of that which is natural of man, into that which is spiritual,
and of God.

As for the four Queries at the close, which I propounded in love,
and for advantage to thee;
it seemeth to me strange thou shouldst say thou wouldst speak to the sense of them,
and yet so wave the main drift and plain sense.

The first was, concerning Christ`'s being spiritually born of his Church;
to which thou hast said nothing at all,
but that the first Christians and churches were very glorious, etc.
Which they also can own, who have denied the faith, and are not in the truth.

To the second thou hast answered as little, nor rightly according to the letter,
putting in the dragon instead of the beast.

Thy third and fourth are also short, and not directly to the thing;
but I wrote not to contend.
The Lord God show thee mercy, bring down the wrong wisdom in thee,
bring thee into a capacity of knowing and receiving his pure, living truth,
that thou mayst not witness or fight against him; but in and by his Spirit,
understand the Scriptures aright, and witness for him.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Nineteenth of Twelfth Month, 1667.

=== Postscript

There is a word of advice in my heart to thee,
which it behooveth thee seriously and uprightly to wait on the Lord,
to be made able to weigh and consider aright; it is this.
Take heed of setting up the letter above or against the
Spirit (for that is not right in the sight of God);
and take heed also of setting up thine own wisdom, conceivings,
and apprehensions above both; for that is a dangerous way of erring,
and may prove a great snare to thy soul, as it hath been formerly,
and is at this day to many.
If ye had known what this meaneth, said Christ, "`I will have mercy,
and not sacrifice,`" ye would not have condemned the guiltless.
We own the Scriptures truly and singly, being taught of God so to do,
and do not hold forth any thing contrary thereto, or deny any thing therein contained;
but are witnesses, living witnesses, of the truths expressed and related therein;
but men`'s meanings and conceivings thereupon (who, though they will acknowledge,
that a man cannot understand the Scriptures without the Spirit, yet will venture,
in their own wisdom, spirit, and understanding,
to expound and give meanings) we cannot own, nor them,
in such their apprehensions and practices.

That in thee, or any, which breathes after the Lord, we have unity with;
but that wisdom and comprehension which is above it, and a veil over it,
and contrary to its nature, and which is a limit and bond to the precious seed,
we cannot have unity with,
because it is of the same nature with that which
the Lord hath condemned and destroyed in us,
and he will not suffer it to live in others, where his life and power prevails.
