== A Few Experiences / Concerning Some of the Weighty Things Relating to God`'s Everlasting Kingdom

[.heading-continuation-blurb]
Given forth in true and tender love for the help of any such
of the race of the true travellers as may stand in need thereof.

[.section-author]
By Isaac Penington

[.section-date]
1671, published posthumously

[.inline]
=== I. A Faithful Testimony concerning the true and pure Way of Life; with Breathings for such as have desires after it, and yet are Strangers to it

This hath been the cry of my soul from my childhood, even after holiness,
after the presence of the Lord, after union with him,
after the nature and image of his Son, after a separation from what was contrary to him,
and a being brought forth in the power of his life.

Now, blessed be the Lord, that is revealed which answers the cry;
which so far as my soul comes to partake of,
it is refreshed and satisfied with the supply of that which it thirsted and cried after.

And all that have felt the true cry, oh that they might also be taught of God,
and learn aright how to wait upon him, and to walk humbly and in fear before him,
that nothing might come between them and the cry of their souls;
but they might be led by him into the enjoyment and possession of that which
the true birth (which is born of the Spirit and is Spirit) naturally longs after!

Now, truly there is no other way to life and satisfaction,
than by believing in that power, and following that power,
which raised Christ from the dead; for that is to work the work in all that are saved.
To feel this power revealed within, to have the mind turned to this power,
to follow this power in the regenerating work and path,
is the way to partake of its virtue,
and to experience the redemption which is thereby and therefrom.

And he that is born of the Spirit, and hath his eye opened by the Spirit,
and daily exercised thereby; he knoweth the Spirit,
and is acquainted with his stirrings and movings,
and taught of God to distinguish them from the evil spirit, its stirrings and movings;
and so doth not quench the Spirit of God, nor grieve it when it moves;
nor give way to the other spirit, when it moves and allures.

Now, the spirit of deceit allures and guides men not so much by outward rules,
as by an inward evil nature, and by the law of sin and death.
So the Spirit of truth leads into truth,
by the newness and power of its own life revealed in the heart,
by the pure instinct of life within,
and by the law of God written in the nature of the new creature,
which is nearer than words without.
For God blots out of the hearts of his what Satan had written there,
and writes by the finger of his Spirit what he would have the new birth read there;
and indeed there is a kingdom of life, of righteousness, of true peace and joy (yea,
of the holy power and wisdom of the Most High),
for his children (which are born of his Spirit,
and spring up of the immortal seed) to read.

Oh, why should men`'s eyes be closed, and their hearts hardened against the truth!
Why should they cry up Christ in words,
and cry out against his life and power where it is revealed!
Is this to kiss the Son?
Can such choose (who are guilty of this) but perish in the way of their soul`'s travels?
And how many must needs perish in their resisting the power of truth,
and precious testimony of God`'s Holy Spirit (in this our day) tending
to their rescue and salvation from that which captivates and destroys!

Christ came to destroy sin, he having received power from his Father so to do.
He knoweth it to be of a destroying nature, and that it will destroy the soul,
where it is not by the power of life consumed and destroyed in the soul.
Oh! most precious to us is that visitation of truth, light, life, and power,
which searcheth out and discovereth sin to the very root, and also destroys it.
Oh! glorious is that axe of the Lord Jesus Christ
which is laid to the root of the corrupt tree,
and is daily hewing at and cutting it down, that it might cumber the ground no more;
but that the heart might become good earth, sanctified earth,
circumcised by the Lord to bring forth good fruit, good grapes,
and good increase of the good seed of life to the good husbandman, who is worthy to reap,
even in this world, the grace and mercy, love and goodness, wisdom and power,
etc. which he plentifully soweth in the spirits of his daily.
Glory to his name over all forever, who hath exalted, exalteth,
and will exalt that which the several sorts of high professors, in their wisdom,
trample upon and despise.

[.inline]
=== II. Concerning the perfecting of God`'s Work in the Heart

Is it not the will of God that his people
and children should be sanctified throughout,
in soul, in body, in spirit?

Is it not the will of Christ that his disciples should be perfect,
as their heavenly Father is perfect?

Did he not bid them pray, "`Thy kingdom come, thy will be done in earth,
as it is in heaven`"? And would he never have them
believe and expect that it should be done in earth,
as it is in heaven?

Doth not he who hath the true, pure, living hope,
(which anchors within the veil) purify himself, even as He is pure?

Is not this the way to enjoy the promises of God`'s holy presence
(who tabernacleth in his people that are cleansed and sanctified),
to cleanse ourselves from all filthiness of flesh and spirit,
perfecting holiness in God`'s fear?
Will God dwell in an unholy temple?
Will he dwell where sin dwells?
He may indeed to such, when at any time they are tender, and truly melted before him,
be to them as a wayfaring man that tarries for a night;
but he will not take up his abode there, walk there, sup there,
and give them to sup with him.

Hath not Christ received all power both in heaven and earth from his Father?
Is not this the end of receiving this power, to bring down the soul`'s enemies,
and to purify and sanctify his church, that it may be without spot, or wrinkle,
or any such thing?
Is he not the Captain of our salvation, anointed to fight the battles of the Lord?
Where is the fight?
Where is the strong man to be found, cast out, his goods spoiled,
and the house emptied of him, and all that belongs to him?
Is not Christ the author of faith, the finisher of faith;
and doth not he carry on the work of faith with power?
And what is the work of faith?
Is it not to fight with and overcome sin; to be too hard for the enemy at all his weapons?
Is there not a whole armor of light, life, and salvation prepared?
What is it prepared for?
Is it not that the children of light should be wholly armed with it?
Were there never any wholly armed with it;
or can the enemy prevail on those that are wholly armed with it?
Are those that are armed with it afraid of the enemy, his power, his snares, his wiles?
Or are they bold in the faith, following on, in the spiritual battles,
him who rideth before them, conquering, and to conquer?

Oh that men`'s eyes were opened by the Lord! then might they see the glory of truth,
in the pure light which shines from God`'s holy mountain;
and such dark doctrines of the night (which tend to the dishonor of Christ,
his power and love, and to the upholding of the enemy`'s kingdom) would pass away,
and prevail no more in the hearts of any that truly fear the Lord;
but they would quietly wait and hope for his salvation,
that by the law of the Spirit of life in Christ Jesus,
they might be made free from the law of sin and death, and not always be subject thereto.
For all whom the Son maketh free, they are free indeed; and being made free by him,
may serve God in freedom of spirit, without fear,
in holiness and righteousness before him, all the days of their lives.
And then they know the power and virtue of the new covenant,
and the defence which is thereby, where the wing of the Almighty overshadows,
and his salvation (revealed therein) is experienced
for a sufficient wall and bulwark against the enemy.

[.inline]
=== III. Concerning the true Christ, how it may be certainly and infallibly known which is he

While people were in expectation and mused in their hearts concerning John,
whether he were the Christ or not, John answers the case,
and tells them how they might discern and know the true Christ.
It is not he that baptizeth with water,
but he "`that baptizeth with the Holy Ghost and with fire.`" He "`whose fan
is in his hand,`" wherewith he cometh "`thoroughly to purge his floor,
gathering the wheat into his garner, and burning the chaff with fire unquenchable.`" Now,
he that knoweth him that doth this work, and experienceth him doing this work in him,
doth he not know Christ?
Oh! is it not precious to be baptized by him whom God hath appointed to baptize?
Oh! the fan, the precious fan, wherewith Christ, who is the power and wisdom of God,
separates the precious from the vile, severs the wheat and the chaff,
gathers the wheat into the precious treasury,
and lets out the unquenchable fire upon the chaff!
"`Our God is a consuming fire,`" saith the apostle.
To what is he a consuming fire?
Is it not to the chaffy, earthy, drossy nature in men and women?
Why, bring the chaff to the fire, will it not burn it up?
And then, as that is burnt up and consumed, that which is pure, that which is upright,
that which is tender, that which is born of God, can dwell with, and delight in,
the devouring fire, and everlasting burnings.
For God is not terrible to the child which is born of him,
to him who is brought forth in the image and Spirit of his Son;
but to the transgressing nature, to the seed of evil-doers,
which are naturally inclined to do evil, and every day doing evil,
he is terrible forevermore.
Oh, blessed are they who believe in that power, and experience that power near,
which raised Christ from the dead, and are baptized with his baptism!
They have access to God: for so the true Jews have been inwardly cleansed and kept clean;
but the unclean, who have only a notion of Christ`'s blood, and of his righteousness,
but are not washed thereby, nor clothed therewith,
nor ever knew what it was to put off the filthy garment, and to put on the white raiment,
they may pray in their own wills and spirits;
but they know not what it is to draw nigh to God in the Spirit and life of his Son,
and so are yet to learn what it is to pray to the Father in the name of Christ.
For none truly know Christ, but they who truly know and are led by his infallible Spirit.
"`They that have not the Spirit of Christ are none of his;`" and they that have his Spirit,
have that which is infallible.
It is one thing to have words spoken concerning Christ, or formerly by Christ;
another thing to have the infallible Spirit itself; to be infallibly born of the Spirit,
and brought up in the light and life of the Spirit,
that he may certainly know the Shepherd`'s voice from the voice of every strange spirit.

[.inline]
=== IV. Some Queries to such as affirm the Scriptures to be the only Rule, and deny the Spirit, the seed of the kingdom, the new covenant, the holy leaven of Life, the Law written in the heart, to be the Rule of the Children of the new Covenant

[.numbered-group]
====

[.numbered]
_Query 1._ How are the Scriptures the rule:
or which of the scriptures are the rule?
Are the whole scriptures the rule,
from the beginning of Genesis to the end of Revelations?
or are some parts of them the rule, some other not?
If some parts of them be the rule, and some not, which parts are the rule,
and which are not the rule?
As to instance, in the book of Job; his friends spake many words concerning God,
which were not so right as Job`'s. Job 42. And also Job himself,
in some of his words and speeches, darkened counsel by words without knowledge,
as he himself confessed. Job 42:3.
Now, which of Job`'s friends`' words are the rule, and which not;
and which of Job`'s words are the rule, and which not?

[.numbered]
_Query 2._ Moses was the minister of the old covenant
(for he ministered to the Jews the old covenant,
which was glorious in its day); but he was not the minister of the new covenant.
Now, the new covenant, and ministration thereof, exceeds the old in glory.
The writing of the law inwardly in the tables of the heart is a more glorious
ministration than the writing of it outwardly in tables of stone.

Now, were Moses`' words to the Jews under the old covenant intended by
God to be the rule of the children of light under the new covenant?
Shall the words of that ministration which was to pass away be the rule
of the children of that ministration which is to abide forever?

[.numbered]
_Query 3._ Did Moses say, that when Christ came,
my words which I speak or write shall be your rule, or part of your rule?
Or did he not rather say, When God raiseth up that prophet,
him shall ye hear in all things?
Is there any one that is truly a sheep,
who is not so made by him who gives life to the soul?
And after he is made alive, and knows the Shepherd`'s voice,
is he not to hear his voice forever, who gives life eternal,
and who leads into the pastures of life, and to the pure, still waters,
all that hear his voice and follow him?
Read John 14:3-4. and Acts 3:22. and consider.

[.numbered]
_Query 4._ Was not John as great, if not greater than Moses?
Had ever any the honor besides him to be the immediate
forerunner and preparer of the way,
and to point to the Lamb of God as he did?
And yet was not he to decrease in his ministry (it being
not the gospel ministration of the Spirit and power,
as Christ`'s was), and Christ to increase in his gospel ministration?
Is not the least in the kingdom greater than John?
And are not all that are quickened by Christ, and follow him, led by him into the kingdom?
And who can give the rule of life in the kingdom but the King thereof?
In the last days doth not the Lord speak to his people by his Son?
And is not he faithful in all his house, as a son,
to give the law and rule of life to them in Christ?

[.numbered]
_Query 5._ Are not all that are soldiers and subjects under Christ to follow him,
their Lord and Captain, whithersoever he goes or rules?
How can they know whither he goes or rules,
but by an inward eye and ear fixed upon and open to him?
So that when once they know his Spirit (the voice of his Spirit, as his true sheep do),
his movings, his drawings, his leadings, his going before, is their rule to follow.
And they are not to grieve or quench his Spirit,
in drawing back from any thing that he leads and draws them to.

[.numbered]
_Query 6._ Is not Christ the way, the truth, the life; the living way, the living truth?
Is not the living way the rule to them that live?
Is not the truth itself the rule of all that are true?
What should rule and guide the spiritual man, that is born of the Spirit,
but the wisdom of the Spirit,
but the oracle of God manifested in his temple and sanctuary?
That which is born of the Spirit, is Spirit, in which the Spirit is to dwell;
and he in whom he dwells is to be ruled by him.

[.numbered]
_Query 7._ What is that which the apostle calls the rule, Gal. 6:15-16.
which if a man walk according to, peace will be upon him?
Is it not the word, power, and wisdom of God?
Doth not he that walketh according to that walk in the newness of the Spirit?
Doth not he that walketh out of that walk in the oldness of the letter at the best?
Doth not he that believeth according to that, hopeth according to that,
prayeth according to that,--I say, doth not he believe, hope,
and pray according to the rule?
Doth not he that believeth, hopeth,
prayeth otherwise (though ever so zealously and affectionately), yet, at best,
can any better be said of it, but that it is in the oldness of the letter,
and so is not in the right way which God requires in the gospel covenant?

[.numbered]
_Query 8._ Is not the law of the Spirit of life in Christ Jesus the law of the new covenant?
And is not that the rule to the children of the new covenant?
Is not the truth which makes free the way and rule to them who are made free by it?
Is the letter or Spirit the rule under the ministration of the Spirit?
Let that which is sensible,
and which feels and knows the truth and way of life (as it is in Jesus) answer.
Men may search the Scriptures, and yet not come to Christ for life;
and men may get descriptions and a knowledge of things out of the Scriptures,
and yet not receive from him the rule of the new life.

====

[.inline]
=== V. Concerning the Light, wherewith Christ the Life enlighteneth every Man

[quote.section-epigraph, , John 1:4-5]
____
In him was life, and the life was the light of men.
And the light shineth in darkness, and the darkness comprehended it not.
____

What is the darkness which comprehendeth not the light?
Is not man in the unregenerate state?
"`Ye were darkness,`" saith the apostle,
speaking concerning them as they had been in that state.

Now, it pleaseth the Lord that in this darkness his pure light should shine,
to gather man out of the darkness.
For unless light should shine on man in his dark state,
he could never be gathered out of it; but he that is turned to the light,
and followeth it, cannot abide in the darkness;
but cometh into that which gathereth and preserveth the mind out of it.

But of what nature is this light, which shineth in man in his dark state?
It is of a living nature; it is light which flows from life;
it is the light which hath life in it; it is the life of our Lord Jesus Christ,
of the Word eternal, which is the light of men.
And he who cometh to the true understanding,
may thereby distinguish it from all other lights whatsoever.

There is a vast difference between it, and the reason and understanding of a man:
for the natural man, with his understanding, is dead;
but this is living and powerfully operating in man, as it finds entrance,
and as his mind is joined to it.
He that is dead, indeed, knows it not; but he that is alive unto God,
feels the virtue of it.
This light is above all gathered knowledge whatsoever,
and above all descriptions of things whatsoever: for it is the thing itself,
even of the nature of him from whom it flows.
A man may get a notion from this into his mind,
which he may retain the dead knowledge of, yea, his notion may quickly be dead in them;
but he that dwells in the thing itself, knows that, and dwells in that, which never dies.

[.inline]
=== VI. A few Words further concerning Perfection

What was the intent of God in commending
Job to Satan for a perfect and upright man,
one that feared God and eschewed evil?
Was it not to represent him as a person whom he could not make any breach upon,
or prevail upon to sin?
Thou hast been ranging up and down the earth, tempting many, defiling many;
what sayest thou to my servant Job, Satan, is not he perfect?
Is not he upright to me in his heart, and all his ways?
Canst thou make any breach upon him?

What saith Satan hereto?
Doth he object any sin against Job?
He is the accuser of the brethren; and if he have wherewith to accuse,
he will not fail to lay it to their charge, even before the throne of God.
But what hath he to say against Job?
What can he object (either against his uprightness,
or against his perfection) to the Lord?
Oh! says he, thou hast set a hedge about him.
He serves thee, indeed, perfectly and uprightly;
I confess I have nothing to lay to his charge: but doth he serve thee for nought?
But take away thy hedge, suffer me to winnow him,
and thou shalt quickly see I shall have somewhat to lay to his charge,
and that no small matter neither: for do but take away thy blessings from him,
wherewith thou hast so abundantly blessed him, and he will soon curse thee to thy face.

Well, the Lord giveth him leave to try if he can stain Job`'s uprightness and perfection:
and now begins the trial, whether the devil`'s temptations shall bring him to sin,
or the fear of the Lord prevail to preserve him from sin.

First, the devil hath power to touch all he hath; which he soon doth.
What doth this produce?
Doth he sin against the Lord, doth he murmur, doth he blaspheme, as the devil had said:
No; he, fell on the ground and worshipped,
acknowledging all to be the Lord`'s and blessing his name.
So that in all this sore affliction, he sinned not, nor charged God foolishly. Job 1:20-22.

But the commendation, which God had given him, to being a perfect and upright man,
fearing God and eschewing evil, still remains and stands good against Satan, chap.
2, 3.

Satan gets leave to try him yet further, insinuating against him,
that if he may have liberty to smite his body, he shall easily prevail upon him to sin;
not being able at present to bring in any plea against his perfection and uprightness,
against his fearing God and eschewing evil.
But this hath the same success with the former;
for he could not bring Job to sin with his lips, ver. 10.

Now mind, Can any man, that hath his heart made upright by the Lord, keep that integrity,
and sin?
Is not every sin a departing from the purity, from the integrity?
Was not every transgression against the first covenant, out of the first covenant,
even a departing from the limits of it?
Is not every transgression of the second covenant
a departing out of the limits of the second covenant?
He that abideth in Christ, doth he sin?
Can he sin?
Doth not he that sins depart out of his light, out of his life, out of his power,
into the darkness, into the death, into the temptation of the enemy?
Is it not promised, I will put my fear in their hearts,
and they shall not depart from me:
while the fear which God puts into the heart abides there, can that man sin?
Doth not the pure fear cleanse the heart, and keep it clean,
that the conscience may be void of offence, both towards God and man?
Is the conscience void of offence, where sin is committed either against God or man?
When the blood flows in the pure light, doth it not wash?
Doth it not wash clean?
Doth it not make whiter than the snow?
When sin is entered into afterwards, and committed again, doth it not defile?
Oh! read in the true sense, in the true experience, with the true understanding,
which God gives.

[.inline]
=== VII. Concerning Imputation of Righteousness

The scripture saith, that Abraham believed God,
and it was counted unto him for righteousness;
and that so it shall be also to all that believe as he did,
even in the same power which he believed in. Rom. 4:23-24.

Now, thus we witness the thing: our minds being turned from sin,
and turned to the pure gift of God, that works a change in us.
Herein we feel faith spring up, which fastens our spirits to the power of life;
and then we feel that (in the power of life) flow
upon our spirits which washeth away our sin;
and all that is done in this holy and righteous faith is of the holy,
righteous life and power, and accepted with the Lord;
and that which condemns sin in us never condemns any work which is wrought in God,
but justifies it.
So that the root of sin, with all that flows from it,
is condemned by the righteous principle of life; but the root of holiness,
with all that flows from it, is justified.
And this is our righteousness, even Christ the holy power of life,
who condemns and casts out sin:
and it is great joy to any of us to feel the root
of sin struck at and condemned by his power,
and him casting sin out of us, and the root of righteousness growing up in us,
and bearing us, and causing us to bring forth fruit to God.
And here we sensibly find we have right to the Scriptures, to the promises,
to all that Christ did and suffered for us,
and witness the propitiation by and through him,
and bless God for all the dispensations of life,
wherein he hath appeared to the children of men in any age,
which were all glorious and excellent in their season;
but the dispensation of the Spirit is the standing dispensation, which excels in glory,
which Christ, in the days of his flesh, pointed his disciples to wait for,
which his going away was to make way for.
This dispensation was revealed and set up before
the apostasy from the life and Spirit of the apostles,
and is again revealed and set up in power and great glory,
after the long night of apostasy; blessed be the name of the Lord forever!
For the darkness is already passed away from many spirits,
and the true light again shineth.
Glory in the highest to the God of life and glory forever and ever!
Amen.

[.inline]
=== VIII. Some Queries concerning the Time and Work of Reformation

[.numbered-group]
====

[.numbered]
_Query 1._ What did the time of Reformation and Substance (spoken
of Heb. 9:10) signify and point at in relation to the mystery?
Was it not for the bringing in of the gospel; the day of Christ`'s Spirit and power;
the day of his inward renewing and reforming;
the day of his taking his fan into his hand, to purge his floor;
the day of his laying the axe to the root of the corrupt tree,
that he may destroy the works of the devil in men`'s hearts,
casting down and plucking up what his heavenly Father hath not planted there?
When he cometh as a refiner`'s fire, and fuller`'s soap, to purify the sons of Levi,
as gold and silver is purged,
that they may offer unto the Lord an offering in righteousness;
is not this the time of reformation?

[.numbered]
_Query 2._ Who is the reformer?
Is it not the Lord Jesus Christ?
Doth not he create anew?
Doth not he blot out the old image, and form into a new lump?
For if any man be in Christ, there is a renewing there; a new building there; yea,
old things are passed away there; there is nothing in him but what is new.
He is faithful (in all his house) inwardly to judge, condemn, crucify, subdue,
destroy whatsoever is contrary to the nature and Spirit of his Father,
and to form and build up the spirits of his in that which is new and pure.

[.numbered]
_Query 3._ How, or by what, doth Christ reform?
Is it not by his Spirit and power, by the light thereof, by the life thereof,
by the virtue thereof?
For nothing can change and reform the heart,
but that which is more powerful than him who corrupteth it.

[.numbered]
_Query 4._ Where doth Christ reform and new-create?
Is it not in the new covenant; in the faith and obedience thereof?
Doth he not, by the laws thereof, break and disannul the laws of the old covenant,
and make void the covenant of hell and death;
and so make an everlasting covenant of life and peace; even a holy, pure,
living agreement, between God his Father and the souls of his?
Thus by his light he overcomes darkness; by his life he overcomes death;
by his pure nature and Spirit he overcomes (chains down, subdues,
and destroys that which is impure, breaking the bond of sin and iniquity,
and letting the oppressed go free from under it.
Thus he manifests himself to be the Saviour by his holy anointing,
breaking the yoke of the oppressor. Isa. 10:27.

[.numbered]
_Query 5._ Whom doth Christ reform?
Are they not those who take his yoke upon them, and learn of him?
Are they not those who are turned to the light of his Spirit, inwardly made manifest;
turned from the darkness, walking no more therein, but in his pure light?
They that own his inward appearance in their hearts,
and turn (from the enmity there) to him, receiving his light, his law, his life,
his Spirit, them doth he exercise daily,
and is daily reforming their hearts and ways thereby.
But if any man receiveth not his light, his life, his Spirit, within,
such a one is none of his; and he may reform himself as much as he can,
but he knoweth not yet the day of the true reformation.

[.numbered]
_Query 6._ How are they to walk whom Christ has begun to reform?
Is it not in that light, in that Spirit, in that covenant, in that grace,
wherein and whereby he hath in some measure reformed them?
Is it not in the newness of the Spirit, and in the newness of the law thereof?
Here Christ walked before the Father in all well-pleasing, ("`Lo, I come;
I delight to do thy will, O my God; yea, thy law is within my heart,`" said he,
Ps. 40:7-8) and here all his are also to walk. 1 John 2:6.
For indeed there is no pleasing the Father, or Christ our Lord and Master,
out of the virtue, life, and newness of his own Spirit.

[.numbered]
_Query 7._ What was the glory that was to follow the sufferings of Christ,
spoken of 1 Pet. 1:11? Was it not the glory of his inward
reformation in the hearts of the children of the new covenant?
Doth not Christ give of his grace in the gospel?
And doth not his grace make a glorious change?
Doth not he give of his Spirit to his children?
And doth not his Spirit change from sin, from shame, into holiness, into true beauty,
into the heavenly glory, and so from glory to glory,
translating more and more into the glory?
Doth not Christ appear gloriously in the hearts of his, and in the assemblies of his,
who meet together in his name, and wait upon him in that which is pure and living of him?
And is there not a covering, or defence of the wing of the Almighty, upon the glory?
Isa. 4:5

[.numbered]
_Query 8._ Was not this glory brought forth in the days of the apostles?
Was not great grace then upon them all?
(I mean such as received and held the truth in the love of it.)
Did they not witness the peace which passeth man`'s understanding?
Had they not received the holy and spiritual understanding from him that is true;
and were they not in him that is true?
Did they not know victory and dominion over sin and death?
Did not the little babes witness pardon of sin, and know him who preserveth from sin?
Had not the young men overcome the wicked one;
and were not the elders strong in the Lord, and in the power of his might?
Were they not come to the spiritual Zion, and heavenly Jerusalem;
and did they not walk in the light of the Lamb, and of the holy city,
before God the Judge of all?
There is no man, in these our days, can so much as conceive the glory of that state,
but he that hath tasted of a measure thereof.

[.numbered]
_Query 9._ Was not this glory eclipsed, and did not a great darkness come over it,
hiding it from the sons of men,
so that (for ages and generations) they knew not the true Spirit, the true light,
the true life, the everlasting covenant, the holy gospel, the true church, the man-child,
etc.; but these, with many other heavenly mysteries, have been hid from their eyes.

[.numbered]
_Query 10._ What hath got up since these have been hid?
Have not the shadows of the night took place, and overspread the Christian state,
instead of the light of the day?
Hath not antichrist got up, and a false church appeared; that which hath been tender,
and begotten of God, snibbed, bowed down, curbed, and persecuted,
and false devotion and worship set up instead of the true?

[.numbered]
_Query 11._ Must not antichrist be destroyed, the false church judged,
the true church come out of the wilderness into which she fled,
the man-child appear again,
conquering and to conquer all which hath risen up from the spirit
of darkness since the first breaking forth of the gospel?
And is not the gospel to be preached again to them that dwell on the earth;
even to every nation and kindred and tongue, and people? Rev. 14:6.

====

Now, who is wise to understand the appearance of the Lord,
and the beginning of these things, which is in a way contrary to man`'s wisdom?
and so he that will discern them, must come out from following of the man`'s own spirit,
nature, and wisdom in himself,
into the sense and leadings of him who giveth the true eye-sight.
The appearance of the Lord is inward and spiritual,
and he must have an inward and spiritual eye who discerneth it.
It was said of old, by mockers and scoffers, Where is the promise of his coming?
For all things continue as they were from the beginning.
The same spirit will say so still; and yet, to that eye which the Lord hath opened,
he is already come inwardly, spiritually, in his own pure eternal life and power;
and the precious effects of his coming are made manifest in many hearts;
blessed be his name.
Yet he is further to appear in glory and pure brightness;
and so we wait further for his appearance, both in our own hearts,
and in the hearts of the children of men.
We have met with our beloved; our God, whom we have waited for, hath appeared.
The Sun of righteousness hath arisen, with healing under his wings,
and we have felt virtue and healing from him,
and cannot but rejoice and testify of his salvation.

And what further manifestations of himself he hath yet to give forth,
we are sure to partake of, being formed by him in Spirit,
and found in that wherein he appears, and from whence his glory shines.
Oh that all that love the Lord Jesus Christ in any
measure of sincerity did know the way of the gospel,
which is in the Spirit, light, life, and power, which is eternal,
even in the grace and truth which is in him!
And his kingdom, which is spiritual, and not of this world,
cannot be shaken by this world (nor his Mount Zion removed);
but is able to shake all nations and kingdoms which kiss not the Son, but oppose him.
Blessed are they who are turned to the light of his Spirit,
and who therein kiss and obey him.

[.inline]
=== IX. Some Queries concerning the Spirit of Christ, or the Spirit of the Father (it being one and the same Spirit), for those who take themselves to be Christians (and under the Gospel Dispensation) to consider and examine themselves by, that they may not be deceived, either concerning their present Estate here, or the eternal Estate of their Souls hereafter; seeing the Apostle so expressly saith, "`If any Man hath not the Spirit of Christ, he is none of his.`" Rom. 8.

[.numbered-group]
====

[.numbered]
_Query 1._ Dost thou know the Holy Spirit of the Father?
Thou mayest have read somewhat concerning it,
and have apprehensions in thy mind about it;
but dost thou truly know what it is by its inward
appearances and operations in thine own heart?

[.numbered]
_Query 2._ Hast thou received God`'s Holy Spirit into thy heart?
Hast thou let in Christ`'s Spirit, when he hath knocked at the door of thy heart,
and received him?
For he that is a true child, most naturally breatheth and crieth for the Father`'s Spirit;
and the Father also most naturally giveth his Spirit
to them that truly and rightly ask it of him, Luke 11:13.
and thou must thankfully receive the Comforter, the Holy Spirit,
when the Father gives him.

[.numbered]
_Query 3._ Doth the Spirit of Christ dwell in thee?
Hath the stronger man cast the strong man out of thee, and taken possession of thy heart,
and doth he dwell therein?
Then thou mayest truly say,
that thou art built up by God a habitation for him in the Spirit.
Then thou art washed and cleansed indeed from thy filthiness;
and lusts or vain thoughts do not lodge in thee.
For the Holy Spirit of Christ will not dwell where such things lodge;
but come out from among them, and be ye separate, and touch not the unclean thing,
and I will receive you, and be a Father unto you, and ye shall be my sons and daughters,
saith the Lord Almighty, in whom I will dwell and walk. 2 Cor. 6:15-17.

[.numbered]
_Query 4._ Doth God`'s Spirit lead thee into all truth that thou needest know and walk in?
Art thou a true child, depending upon, and guided by, the Spirit of the Father?
Canst thou not see thy way, but as he maketh it known to thee?
Art thou a follower of the spotless Lamb, in the same spirit wherein he walked?
If it be thus with thee, then art thou a child of God indeed.

[.numbered]
_Query 5._ Dost thou live in the Spirit?
Dost thou feel the Spirit of God to be a fountain of life,
from whence life springs up into thee daily?
Dost thou witness that scripture fulfilled in thee,
"`He that believeth on me,`" as the scripture hath said,
"`out of his belly shall flow rivers of living water`"?
Hast thou received the living water from Christ?
And is that living water become a well of life in thee?

[.numbered]
_Query 6._ Dost thou walk in the Spirit, in the life thereof,
in the newness thereof springing up in thy heart?
Dost thou know the difference between walking in the oldness of the letter,
and in the newness of the Spirit?

[.numbered]
_Query 7._ Didst thou ever learn of the Father, to know Christ?
And didst thou ever learn of Christ, to know the Father?
And hath the Father indeed revealed the Son to thee,
and the Son indeed revealed the Father to thee?
Or art thou yet only in the dead and dry notions,
or barren comprehensions about these things?

[.numbered]
_Query 8._ Dost thou know how the letter killeth,
and how the Spirit quickeneth and maketh alive?
And art thou made alive by the Spirit, and born of the heavenly water and Spirit,
and so become spiritual as the scripture testifieth, "`That which is born of the Spirit,
is Spirit`"?

[.numbered]
_Query 9._ Art thou come under the ministration of the Spirit?
Dost thou know what the ministration of the Spirit is?
Or dost thou only know what the letter saith concerning the ministration of the Spirit,
but art altogether ignorant of the ministration itself?

[.numbered]
_Query 10._ Dost thou know what the law of the Spirit of life in Christ Jesus means?
Hast thou ever received this law; the law of the new covenant;
the holy law of life written in thy heart by the finger of God`'s Spirit?
For the same Spirit that wrote the law of the letter in tables of stone,
writeth the law of the Spirit in the fleshly tables of the heart.

[.numbered]
_Query 11._ Dost thou not grieve the Holy Spirit, nor quench it,
nor despise the prophesyings thereof in thine own heart?
For Christ is a king, a priest, a prophet; and he ministers in his sanctuary,
in his temple (which the holy renewed heart is), in and by his Spirit.

[.numbered]
_Query 12._ Dost thou know what the anointing is?
Art thou anointed therewith?
And doth thy whole ability lie therein,
insomuch as that thou art daily sensible thou canst not do any thing of thyself,
but still findest God working in thee,
both to will and to do that which is right in his eyes, of his own good pleasure?

[.numbered]
_Query 13._ Did thy religion begin in the Spirit?
In the living ministration of the new covenant?
Did thy knowledge begin so; to wit, in feeling God opening thy heart by his Spirit;
and giving thee the understanding whereby thou mightest know him?
Did thy faith begin in his power, and doth it stand in the same power to this day?
Oh that men were sensible what is the right religion,
and of the inward appearance of God`'s holy arm and power, which alone can redeem,
and save the soul out of the hands of its enemies?

[.numbered]
_Query 14._ Doth thy worship stand in the Spirit, and inward life of truth in thy heart?
Art thou such a worshipper as the Father hath sought out and made so?
Or art thou a worshipper of thine own or other men`'s making?
And dost thou keep within the limits of the living and spiritual worship,
and not transgress the law thereof?

====

Oh, who would be mistaken and deceived about such weighty things as these,
of so great necessity and concern!
Who would miss of God`'s Spirit, and of the law and covenant of life in Christ Jesus,
and be only in a dream concerning these things, without the true,
demonstrative knowledge, possession, and enjoyment of them!

[.inline]
=== X. Of the true Way (the Way of Holiness, the Way of Life), and of the true Teaching and Knowledge

Christ is the way, the only way to the Father; there is not another.
Now, every one that will truly know Christ, and come to Christ, must learn of the Father.
It is written in the prophets, "`All thy children shall be taught of the Lord;
every one therefore that hath heard and learned of the Father,
cometh unto me,`" said Christ.
Here are two things necessary for every one that would come to Christ.
One is hearing of the Father: the other is learning what he teacheth.
For though a man do hear the living voice of the Father,
yet if he do not learn and keep the instruction of life received from him,
he may be drawn aside before he come to the Son.
But he whose ears are opened to hear the voice,
and who feels the instruction of life from the Father,
to go to him in whom he hath placed life;
here the Spirit of the Father secretly draws in the inwards of a man`'s mind and spirit,
from that which is really dead, to that which is truly living.

Now, when a man is come to the Son, in whom the Father hath placed the fulness of life,
then he shall witness him the way to the Father,
and he will teach him daily of the Father.
And here is the state of true subjection to the Son experienced,
whom the soul must hear (and of whom he is to learn) in all things;
who discovers the inward darkness in man`'s mind,
and breaks down that in him which is contrary to God,
having a daily cross ready for that which is to be crucified in him,
whereby he shall die daily to himself.
And as he dies to himself, Christ will reveal himself more and more in him,
and he shall feel the pure seed of life springing more and more up in him,
and living in him, and he in it;
in and through which he shall come more and more
into union and fellowship with the Father of spirits,
and the whole living body of his church and people.

But now, to learn of the Father to come to the Son,
and to learn of the Son to know the Father,
and to walk in newness of Spirit before him and not in an old,
dead knowledge and fleshly understanding), these are great mysteries,
which none can learn by a literal conception and comprehension of things,
but as they are quickened,
and their minds and understandings opened and kept open by the Lord.
Therefore this is the great skill and true wisdom, to know the Shepherd and his voice;
and his manner of appearing, and to what he appears; which is to his own sheep,
to the true birth.
And his way and manner of appearing to that birth is by
visiting and reaching to it by his power opening it,
thereby giving it to see, hear, and understand;
but shutting up himself from the contrary nature, wisdom, and spirit in all men.

There is somewhat which maketh a fair show in the fleshly part, as if it were of God;
but God knoweth what and who are his.
Now, it is for the true children, that the milk of the word, and the bread of life is;
and them the Lord is still gracious to,
and heareth all the desires and breathings of their hearts;
them he preserveth and visiteth in Egypt, and also bringeth out thence.
Them he leadeth through the wilderness, dividing the Red Sea before them;
before them also he divideth Jordan (the river of judgment),
causing them to pass through it also, that they may enter into the Holy Land.
And their lot he defendeth in the Holy Land,
in their subjection to the Spirit and law of life which rules there.
But the contrary birth falleth short by the way,
and cannot enter into nor abide in that which is pure and living of God.

Now, in the lowly seed the whole mystery of life is learned,
by those that come thither and wait there, growing up into him who is the head;
but no lesson of life, and of the truth as it is in Jesus, is learned out of it.
Oh, how careful had men need be to know this seed in themselves,
and to witness its daily springing up and growth in them!

=== XI. Concerning Separation from the Spirit and Ways of the World

There is a necessity of separation from the spirit, ways,
and worships of the world, by those that will be the Lord`'s people.
The Jews outward were to be a separated people from all other people (from their gods,
from their worships), if they would enjoy the favor of the Lord,
and the blessings of the good land.
God had separated them from all other nations, and they were not to mingle with them;
neither in their worship, nor marriages, etc.
So the Jews inward, who are God`'s gathering of spiritual worshippers,
out of every nation, kindred, tongue, and people,
are to be a separated and holy people to the Lord.
For when God cast off the Jews, he sought out worshippers in their stead,
even for a spiritual nation and holy people of inward Jews,
instead of that outward people, outward place of worship, and outward land,
which he cast off.
Now, those whom God seeks to be the new inward, spiritual worshippers,
instead of the literal and outward, must come out of all other ways and gatherings,
upon the many mountains, to the mountain of the Lord`'s house,
and to the place of his gathering: the command is express, "`Come out from among them,
and be ye separate; and touch not the unclean thing, and I will receive you,`" etc.
2 Cor.
6+++.+++ It is true, I seek you for worshippers,
and I call you to the gospel feast of fat things, and I will receive you if ye come;
but ye must first come out from among all the false ways and false worshippers,
and depart from (and not so much as touch) that which is unclean (the unclean spirit,
his unclean ways and worshippers), and then I will receive you,
and own you as my sons and daughters, and be a Father to you; not else.
Mark now; the Jews outward (in their day) must be separate from all the Heathen outward,
if they would be judged and owned by God for true worshippers according to the law.
The primitive Christians were to separate from both
Heathen and Jews too (even their temple,
priests, and ordinances, which were once of God), if they would be worshippers,
true worshippers under the gospel, worshippers of God`'s seeking.
And the Christians, after the antichristian corruption and darkness,
must come out of Babylon; that is, out of all forms of religion,
and buildings out of the life and power (for that is Babylon, the city of confusion,
which is built, stands out of, and practiseth out of, the order and unity of the Spirit),
if they will be found worshippers in the day of restoration;
after the long darkness of the apostasy,
they must not worship the beast (nor worship God as the beast teacheth and requireth;
for in so worshipping, God is not worshipped, but the beast), nor bear his name,
nor receive his mark, either on their forehead or right hand,
nor be of the number of his name.
Now, the command is as express to come out of Babylon, that is,
to separate from all antichristian ways and worships,
as ever it was to separate from the Heathen and Jews;
and there is no being a true worshipper in God`'s sight,
but in the true way of separation from all false worshippers,
who worship in forms and appearances of godliness, out of the life and power.

Now, oh, how precious it is to feel God seeking, God gathering, God separating,
God teaching, leading, drawing into the truth, and true way of worship!
For there are self-separations, which are out of the true Spirit, life, and power.
Yea, God may begin the separation, and another wisdom may step in, and carry it on,
out of the limits of the sweet, innocent Spirit, life, and power.
Oh, blessed is he who is separated by the Lord from all that is not of him!
But he that is but sensual, and hath not the Spirit,
but only by a literal knowledge separateth himself,
he differeth from others but in the outward form and appearance of godliness;
but is one in nature and ground with those whom he separateth from.
Thus the Papists,
and all pretended Christians (of the same spirit) who feel not the true Spirit, power,
and life, are but one in the ground, how great soever their difference outwardly seem.
And those that separate further and further (even to the utmost extent outwardly,
or in a way of appearance),
being not separated by the Lord from that nature and spirit wherein the enmity lodgeth,
they are still inhabitants of one and the same city
(for the city of Babylon is very large),
and daughters of one and the same mother, even of the wisdom which is from beneath;
which wisdom, in its highest exaltation,
is far beneath the nature and true excellency of the pure and heavenly wisdom,
even in its lowest and most contemptible appearance.
Oh! blessed is the religion, the worship, the separation, the fear of the Most High God,
the faith, the knowledge,
which begins in the Spirit and power (even in the
evidence and demonstration of God`'s own Spirit),
and which stands and abides therein!
For herein are the children of light distinguished, and kept distinct (by God Almighty,
who hath made the difference), from all the children of darkness.

[.small-break]
'''

[.section-author]
By Isaac Penington

[.section-author-context]
Prisoner for the testimony of truth at Reading Jail

[.signed-section-context-close]
1671+++.+++ About the 12th month.
