== A TREATISE CONCERNING GOD`'S TEACHINGS, AND CHRIST`'S LAW

WITH SOME OTHER THINGS OF

WEIGHTY IMPORTANCE

PARTICULARLY MENTIONED AFTER THE PREFACE

WRITTEN BY

ISAAC PENINGTON

PRISONER AT READING JAIL FOR THE TESTIMONY OF TRUTH

"`They also that erred in spirit shall know understanding, and they that murmured shall learn doctrine.`" Isa. 29:24. Blessed be the Lord, it is so.
This prophecy is sensibly and experimentally fulfilled, and fulfilling daily more and more

+++[+++ca. 1671]

=== PREFACE

CHRIST, who came from the Father, and knew the way of truth and life everlasting,
and was to guide men to the Father, being the only way unto him, preached the kingdom,
and bid men seek the kingdom;
teaching and instructing them in many parables concerning it,
and directing them where and how to find it.

The apostles likewise (who succeeded Christ in the same Spirit
and power wherein he ministered) preached the same kingdom,
declaring and describing what it was, and wherein it consisted; namely, not in word,
but in power (even in the power which shakes all that is to be shaken,
but cannot be shaken itself, nor the kingdom which is in it, 1 Cor. 4:20.
and Heb. 12:28). Nor was the
kingdom of God meat and drink (or any outward thing);
but righteousness, and peace, and joy in the Holy Ghost. Rom. 14:17.

And they preached not in vain; for the life was inwardly revealed in many,
the power inwardly revealed, the kingdom inwardly revealed, and the righteousness, peace,
and joy thereof felt.
For such as truly believed and obeyed the gospel,
received the kingdom which could never be shaken,
and had an entrance ministered to them thereinto,
according to their diligence and carefulness in the truth.

Now, afterwards a great darkness came over, and this glorious kingdom was again veiled,
and the kingdom of darkness and deceit overspread the profession of Christianity;
and in this time notions and outward knowledges took with men,
instead of the life and truth itself, wherein the kingdom and power stands.

But, blessed be the Lord, the light of life again shines out of and over the darkness,
and the kingdom is again received and the entrance into it again known;
and from what is seen and heard (and in measure enjoyed
and possessed) is a faithful testimony given forth.
And blessed are they who hear the joyful sound;
for it is no less than the sound of life itself, the power itself, the gospel itself,
the Spirit himself, manifesting himself in, and speaking through,
vessels according to his pleasure.

Now, they that receive this light, which is testified of, and witnessed to,
receive Christ; but they that despise and reject it, reject him;
as will be made manifest in the day of the Lord, whatever men,
in their wisdom and comprehensions, judge to the contrary, who know not,
nor are able to judge of the appearances of the Lord,
or of the glory of this dispensation.

For this dispensation is indeed most precious, glorious, and living,
being a dispensation of the seed and power of life itself,
whereby God translateth out of darkness, and the regions thereof,
into the kingdom of his dear Son, and into his glorious image.
Which, reader, not that thou mayest have only notions concerning,
but mayest really come to partake of,
is the end of my giving forth these things following; which sweetly, freshly, livingly,
and powerfully sprang up in my heart for thy sake,
and are in great love presented to thy view,

By a sufferer for the truth which lives in him, and in which he lives,
through the tender mercy of the Lord, and to the glory of the riches of his grace,

ISAAC PENINGTON

=== A TREATISE CONCERNING GOD`'S TEACHINGS AND CHRIST`'S LAW

==== 1. Concerning God`'s Teachings

// todo section epigraphs for both
"`It is written in the prophets`" (said Christ) "`they shall be all taught of God.
Every one therefore that hath heard, and hath learned of the Father,
cometh unto me.`" John 6:45. "`For the prophets indeed had said,
All thy children shall be taught of the Lord, and they shall all know me,
from the least of them to the greatest of them.`"

NOW, whose children are they which shall all be taught of the Lord?
And which are they which shall all know the Lord by the teachings of his Spirit,
from the least to the greatest?
Are they not the children of the free woman,
the children of the Jerusalem which is from above,
which is the mother of all that are truly living?
Now, all her children the Father of life begets, and taketh care to teach them the true,
pure, heavenly, living knowledge; so that they indeed know the Lord,
being taught by the anointing so to do; and they indeed know Christ,
the Father revealing him to them: for none knows the Father but the Son,
and none knows the Son but the Father, and he to whom the Father reveals him.
"`Flesh and blood hath not revealed it to thee,
but my Father which is in heaven,`" said Christ to Peter. Matt. 16:17.
And it pleased God to reveal his Son in me, said Paul. Gal. 1:15-16.
And how did Paul preach Christ among the Gentiles?
Did he not preach him as a mystery hid from ages and generations,
which none but the Father could reveal and make manifest?
And when he is known and made manifest, is he not known within, revealed within,
made manifest within? Col. 1:26-27.
and 1 John 1:2. Mark:
"`The life was manifested.`" Thus they came to know Christ;
and if they would bring others to the knowledge of Christ,
they must bring them to the manifestation of the same life,
and show unto them that eternal life which was with the Father,
and was manifested unto them, ver. 2. Now, that they might do thus,
they were to preach the light to them (even this message, that God is light,
and in him is no darkness at all, ver. 5),
and to turn them to the light (Acts 26:18) in which
alone men can see and receive the life which is eternal.
Men may know or comprehend many things concerning the Messiah from the letter;
but they can only know the Messiah himself in the light which shines into their hearts,
and which he sent his apostles to direct and turn their minds to.
For they directed them to the Word within, light within, life within, Spirit within;
to feel after the manifestation of God within,
which was communicated to the very Gentiles. Rom. 1:17.
And so Paul directed the Gentiles to seek after and find God nigh,
and not afar off. Acts 17:27.
Oh, this is precious to find and feel God near, Christ near;
in his light to see light, in his life to feel and enjoy life!
For here (in the place of darkness, in the place of sin and death,
in the place where dragons lay, Isa. 35:7) is the redeeming power to be felt,
and the deliverance of the soul experienced by those that truly believe.

The Scribes and Pharisees had a knowledge that the Messiah was to come;
but how came they by it?
Why, they had read so in the letter of the Scriptures.
The professors of this age have a knowledge that Christ is come; how came they by that?
Why, they have read so in the writings of the evangelists and apostles.
But who hath believed the report of life now,
and to whom is the arm of the Lord (which is now stretched forth) revealed?
Who hath heard and learned of the Father to know the Son, and so to come to him,
even from the inward revelation of his Spirit,
and from the inward living knowledge which is thereby?
Every one therefore (saith Christ), every one of these children,
every one that is taught of God (because of what
they have heard and learned of the Father),
cometh to the Son.
Now, every one that is thus drawn, and thus cometh, Christ receiveth,
and giveth to all such eternal life; and they know him who giveth them eternal life,
and who preserveth and maintaineth life in them.
Others have but a notional knowledge of him; but do not indeed know him that is true,
nor are in him that is true, even in his Son Jesus Christ,
who is the very God and life eternal. 1 John 5:20.

And so they that are taught of God learn of him to repent from dead works,
and do repent them thereof; whereas others, through hardness of heart,
do not so much as discern which are dead works, which not, in matters of worship.
Others do not know the true difference between that which is dead,
and that which is living;
but death (unknown to them) lives and reigns in their
very knowledge and apprehensions of things;
even in their faith, in their duties, yea, in all they believe and perform to God.
For as Paul was alive without the law once,
even when he walked according to the letter of the law blameless;
so all sorts are now dead,
in the midst of all their knowledges and practices from the letter (how much alive soever
they may seem to themselves therein) till they come to the ministration of the Spirit.
"`For the letter killeth; but the Spirit quickeneth,
or giveth life.`" 2 Cor. 3:6. and ver. 3. This therefore is the work of a true minister,
to beget into the Spirit, and into the life; but ah,
how little do men know what dead works are,
and what it is truly to witness repentance from them!
Men out of God`'s Spirit, light, and power, are so far from repenting for them,
that they do not so much as rightly distinguish and discern them;
but take that for living which is dead; kindling a fire of themselves,
and compassing themselves about with sparks,
thinking the warmth thereof to be the true warmth.
Now, if men are not come to the true repentance from dead works,
much less are they come to the true faith towards God; and so are yet in their sins,
yet out of Christ, having never learned of the Father to come to him;
and so are still in Egypt`'s spirit, in Egypt`'s wisdom, and in that hold their religion:
and whenever God appears in his Spirit and power,
he will not be that to them which they expect;
but a dreadful stroke from him will come upon all their ways and worships,
which are as abominable to God, as they are pleasing to them.
But alas, to what end are words to that ear, to that spirit,
which is like the deaf adder, which will not hearken to the voice of the charmer,
charm he ever so wisely!
Could the letter-learned Scribes and Pharisees hear
the voice of Christ in the days of his flesh?
Nay; they could not, in that gainsaying spirit.
Can the letter-learned professors, in the same spirit,
hear the voice of Christ`'s Spirit now?
Nay; they cannot.
And they that cannot hear the voice of the second Adam,
the voice of the quickening Spirit, the voice of him who gives life to the soul,
how can they live?
And if they first receive not life from Christ,
how can they perform any living action to God?
How can they worship in the Spirit and in the living truth,
who are not gathered into the Spirit and into the living truth?
Oh, that men could consider aright of these things,
and wait on the Lord for the true understanding of them!
For without the true knowledge of God and Christ (without
that knowledge which is life eternal) men must needs perish.
It cannot be otherwise; for the true knowledge only saves,
and therefore they which have it not must needs perish.

==== II. Concerning the Law of Christ

"`And the isles shall wait for his law,`" Isa. 42:4.

WHAT is that law which the isles were and are to wait for?
Is it not the grace and truth which comes by Jesus Christ,
even the grace in the inward parts, even the truth in the inward parts?
The law outward was given by Moses to the outward Jews;
but grace and truth comes by Jesus Christ.
That is the law of the Jew inward, which the isles of the Gentiles were to wait for.

The apostle holdeth forth Christ to be the soul`'s master (he is the Shepherd, Lord, King,
and Bishop of the soul), to whom every one must give an account.
Now, what must men give an account to him of?
Is it not of the grace and truth which comes by him?
If any man hath received that, obeyed that, believing the sound, report,
and voice of that, and so loved and followed it, will it not be said unto him,
"`Well done,
good and faithful servant`"? But if any one hath neglected
and despised the grace (not improving the talent,
but improving his own natural abilities, while God`'s talent lay wrapped up in a napkin,
and hid in the earth),
will not that person be judged a slothful servant as to improving the talent,
whatever he hath been as to improving his own natural parts and abilities?

Now mind: If Christ be an inward, a spiritual master,
what is his law but the inward teachings of his Spirit?
A prophet shall the Lord your God raise up unto you like unto me,
him shall ye hear in all things; and he that will not hear him,
how secure and confident soever he may seem to himself of his state at present;
yet it shall come to pass,
that he shall be cut off and destroyed from among God`'s people.
Are not the words, the voice, the motions, the leadings, the drawings,
the commands of his Spirit, the law to all that are spiritual?
Doth not he say to one, Go, and he goeth; and to another, Come, and he cometh;
to another, Do this, and he doeth it?
Here is the glory of the great Lord and King, and of the great High-priest,
over the household of God,
in that he giveth forth precepts according to his holy will and pleasure;
and all his sheep know his voice, and follow him;
and all his children and servants observe and obey him.

If we live in the Spirit, let us also walk in the Spirit, said the holy apostle.
Here are the limits of the children of the new covenant;
here is the law of life (the law of the Spirit of life in Christ Jesus),
the law of the new covenant, written in the heart,
which none can read but with the new eye.
The children of the flesh may read the letter, and comprehend concerning the letter,
and gather rules and observations out of the letter;
but the children of the new covenant alone can read the law of life in the heart.
And this law is the path of life, the path of all that are renewed by God`'s Spirit,
which the Jew inward is to read diligently, and to have his delight therein,
and to meditate thereon day and night.
And this law is light, true light, pure light, spiritual light, yea,
the light which is eternal, and never varies;
and the commandment which comes therefrom is a lamp,
which they that receive know it to be no less than life everlasting; for indeed,
the commandments of Christ`'s Spirit are felt to be so.
Now, this commandment, this law, this light, shines in the darkness at first;
but afterwards, out of the darkness more and more (as it is believed, received, obeyed,
and walked in) unto the perfect day.
See Prov. 4:18-19.

[.discourse-part]
Question.
But how may I wait for, come to know, and receive this law?
I am not of the stock of the Jews natural, but of the isles of the Gentiles;
how may I meet with and receive the law of life from Christ,
or the grace and truth which comes by him?

[.discourse-part]
Answer.
The way of receiving it is to mind that which enlightens and renews the mind,
drawing it out of the nature and spirit of this world, and out of the ways, worships,
knowledge, and customs thereof, into that which seasons it otherwise,
and opens it another way.
Now, here the grace is met with, here the truth is met with,
here the Spirit of life is met with; here the inward change is felt,
and the new law written in the heart and spirit.
And here the mind comes to prove and know what is that good, that acceptable,
and perfect will of God: for God is the teacher in the new covenant,
and his teachings are here, even in that which he renews.
He gathereth into his Spirit, and he teacheth those that abide in his Spirit,
and giveth unto them eternal life, eternal virtue, eternal nourishment,
in and from his Spirit.
But they that may be great searchers into the letter, and comprehenders from the letter,
and practisers according to their apprehensions of the letter
(not being gathered into nor reading in the Spirit),
they miss of eternal life, and of the redeeming arm and power,
and are not saved from sin by the blood of Christ; but are yet in transgression,
darkness, and death, even until now.
The Lord, who knoweth all things, make manifest their estates and conditions unto them,
that they perish not forever; but may learn of the Father to know the Son,
and of the Son to know the Father,
and come to witness true life manifested in their own hearts,
that they may have fellowship with the Father and Son therein.
For he that is not turned from darkness unto light
(from the darkness within in his own heart,
unto the light which God causeth to shine there)
doth not yet know Christ livingly and savingly;
but is only in the notions and comprehensions concerning him, which cannot save.
For it is the life and power of the Lord Jesus Christ,
inwardly revealed against the power of sin and death,
which is alone able to save therefrom.

Now, consider with yourselves (all who would not be deceived
in this matter) have ye known this law?
Have ye received it in measure, and do ye wait to know and receive it daily more and more?
Then are ye Christians indeed, and of the house of Jacob,
which walk in the light of the Lord, and in the light of the holy city,
whose light the Lamb is.
But without this law, without this light,
without the inward writing of God`'s Spirit in your hearts, ye cannot be inward Jews,
nor children of the new covenant.

These are weighty things, and to be considered weightily,
and weighed in the balance of the sanctuary.
Oh! wait to know what it is to go into the sanctuary,
and to weigh things there in the balance thereof,
which exactly and infallibly weigheth and determineth whatever is brought thither!
For of a truth ye cannot understand any scripture aright
which treateth of any spiritual and heavenly mystery,
but as ye are taught of God, to bring it unto the balance of the sanctuary,
and to weigh it there; where all your own apprehensions, meanings,
and conceptions will fall,
and the mind and intent of God`'s Spirit be alone owned and justified.
Ah! what a vast difference there is between weighing men`'s apprehensions
and conceivings upon scriptures in the balance of their own understandings,
and weighing them in the true balance!
In the former are all the erring judgments; but in the latter is the true,
unerring judgment of God`'s own Spirit, in the light which is eternal;
which judgment will stand forever.

==== III. A brief Relation concerning myself, in reference to what has befallen me in my Pursuit after Truth

I WAS acquainted with a spring of life from my childhood,
which enlightened me in my tender years, and pointed my heart towards the Lord,
begetting true sense in me, and faith and hope and love and humility and meekness etc.,
so that indeed I was a wonder to some that knew me,
because of the savor and life of religion which dwelt in my heart,
and appeared in my conversation.

But I never durst trust the spring of my life, and the springings up of life therefrom;
but, in reading the Scriptures, gathered what knowledge I could therefrom,
and set this over the spring and springings of life in me, and, indeed,
judged that I ought so to do.

Notwithstanding which, the Lord was very tender and merciful to me, helping me to pray,
and helping me to understand the Scriptures, and opening and warming my heart every day.

And truly my soul was very near the Lord,
and my heart was made and preserved very low and humble before him,
and very sensible of his rich love and mercy to me in the Lord Jesus Christ;
as I did daily, from my heart, cry grace, grace, unto him,
in everything my soul received and partook of from him.

Indeed, I did not look to have been so broken, shattered, and distressed,
as I afterwards was, and could by no means understand the meaning thereof,
my heart truly and earnestly desiring after the Lord,
and not having the sense of any guilt upon me.
Divers came to see me, some to inquire into and consider of my condition;
others to bewail it, and (if possible) administer some relief, help, and comfort to me;
and divers were the judgments they had concerning me.
Some would say it was deep melancholy; others would narrowly search, and inquire how,
and in what manner, and in what way I had walked,
and were jealous that I had sinned against the Lord, and provoked him some way or other,
and that some iniquity lay as a load upon me: but after thorough converse with me,
they would still express that they were of another mind;
and that the hand of the Lord was in it, and it was an eminent case,
and would end in good to my soul.

At that time, when I was broken and dashed to pieces in my religion,
I was in a congregational way; but soon after parted with them, yet in great love,
relating to them how the hand of the Lord was upon me,
and how I was smitten in the inward part of my religion,
and could not now hold up an outward form of that which I inwardly wanted,
having lost my God, my Christ, my faith, my knowledge, my life, my all.
And so we parted very lovingly, I wishing them well,
even the presence of that God whom I wanted; promising to return to them again,
if ever I met with that which my soul wanted, and had clearness in the Lord so to do.

After I was parted from them, I never joined to any way or people;
but lay mourning day and night, pleading with the Lord why he had forsaken me,
and why I should be made so miserable through my love to him,
and sincere desires after him.
For truly I can say,
I had not been capable of so much misery as my soul lay in for many years,
had not my love been so deep and true towards the Lord my God,
and my desires so great after the sensible enjoyment of his Spirit,
according to the promise and way of the gospel.
Yet this I can also say, in uprightness of heart,
It was not gifts I desired to appear and shine before men in; but grace and holiness,
and the spirit of the Lord dwelling in me, to act my heart by his grace,
and to preserve me in holiness.

Now, indeed the Lord at length had compassion on me, and visited me;
though in a time and way wherein I expected him not:
nor was I willing (as to the natural part) to have
that the way which God showed me to be the way;
but the Lord opened my eye, and that which I knew to be of him in me closed with it,
and owned it; and the pure seed was raised by his power,
and my heart taught to know and own the seed,
and to bow and worship before the Lord in the pure power, which was then in my heart.
So that of a truth I sensibly knew and felt my Saviour,
and was taught by him to take up the cross, and to deny that understanding, knowledge,
and wisdom, which had so long stood in my way;
and then I learned that lesson (being really taught it of the Lord)
what it is indeed to become a fool for Christ`'s sake.
I cannot say but I had learned somewhat of it formerly;
but I never knew how to keep to what I had learned till that day.

And then God showed me (by degrees,
as he nurtured me up in the heavenly sense and experience of his spirit)
the workings of the good in me and the workings of the subtlety;
and how himself had, in time past, taught me to pray, and to understand the Scriptures,
and to believe in his Son, and know some things aright; but withal,
how a knowledge and understanding of another nature had crept in,
and gained ground upon me (which indeed I knew not
how to distinguish thoroughly from the other,
and watch against), and so the truth came not to live in me, nor I to live in that,
according to the earnest desire and travail of my soul.

But now of a truth, by this blessed visitation of the everlasting gospel,
the Lord hath at length brought me back to the same
spring I was acquainted with at first,
and joined my heart in true sense and understanding to it;
so that the life that I live is by the springing up of life in me;
and I know the Lord my God, by being daily taught by him so to do; and I love him,
by feeling my heart circumcised and constrained through the new nature thereunto.
And truly it is natural to the good seed in me, and to my soul in and through the same,
to trust my Father, and to suffer any thing that he requires of me,
who freely giveth me both to do and to suffer: for indeed I live not of myself,
but by a continual gift and quickening of life in my heart.

And oh that others also could come to hear the testimony
of truth and life from God`'s Holy Spirit,
and be turned thereby to the pure principle and Spirit of
life itself! (which many formerly had a true taste of,
but are now turned aside to another nature and spirit,
though they themselves know it not) that they might witness the gospel power,
and know the spiritual and heavenly Jerusalem, and suck at her breasts,
and be dandled on her knee,
who is the mother and bringer-up of all that are truly living.

==== IV. A Question about preaching the everlasting Gospel answered

[.discourse-part]
Question.
How is the everlasting gospel (wherein Christ is truly made known,
and salvation really witnessed in the hearts of those
that receive it) preached at this day?
How hath the Lord appointed it to be preached, and how is it preached,
and how may men come to hear it, that their souls may live?
Are not they blessed that hear the joyful sound thereof?
Are not they wretched and miserable, and blind and naked,
who mistake and miss concerning that sound of it,
which it pleaseth the Spirit of the Lord to give forth in this day?

It is wonderful to consider how the truth, the gospel, the life, the power which saves,
is one and the same in all ages and generations, and yet still hid from the wise,
prudent, professing eye, in every age and generation.

Now let me speak a few words to this thing: not only from what I have felt in my heart,
but have also read in the Scriptures of truth.

[.discourse-part]
Answer.
The gospel, after the apostasy, is thus to be preached: "`Fear God, and give glory to him,
for the hour of his judgment is come; and worship him that made heaven and earth,`" etc. Rev. 14:6-7.
He that knoweth the preacher that preacheth this;
he that hath heard this preached in his own heart;
he that hath met with that fear which God`'s Spirit teacheth and giveth;
he that hath known the hour of God`'s judgment,
and had the axe laid to the root of the corrupt tree,
and hath been taught by the Son to worship the Father in spirit and truth; he hath,
without doubt, met with the gospel, the everlasting gospel;
and if God require of such a one,
and assist him by his Spirit and power to preach this to others,
he is a preacher of the everlasting gospel, and an able minister of the New Testament,
not of the letter, but of the Spirit.
But all should take heed of preaching their own formings and conceivings
upon the letter (as too many do in this day,
who reproach, revile, and persecute the life and power),
for that falls short of true preaching the letter.

Oh that these things were weighty upon men`'s spirits,
that they might learn aright to search and understand the Scriptures,
and know how the Father hath revealed the Son in this day, and how to come to him,
to receive life from him!
For many (who seem knowing), through ignorance, mistake in this matter,
and so run on in their own wills, wisdoms, and comprehensions of things,
and miss of the drawings of the Father, and so come not aright to the Son;
but only according to what they themselves imagine and apprehend
from what they have gathered and conceived upon the Scriptures.

God, who commanded light to shine in this outward world,
hath judged it necessary to cause the light of his
Spirit to shine inwardly in men`'s hearts;
and this gives the knowledge of the Scriptures,
and the true sense and discerning of inward and spiritual things; yea,
here the Son is known, and his blood felt cleansing;
which the Scriptures without do not make manifest;
but this the Scriptures are a clear and faithful record of, and testimony to.
Men had need take heed how they read, and how they understand,
the Scriptures (in what light, in what spirit), for it is easy erring;
but without the presence and guidance of God herein men cannot walk safely.
And truly it is great presumption in any man to read the Scriptures boldly,
without fear and reverence to him who is the author of them;
or to put any of his meanings and conceivings upon God`'s words;
which it is hard for him to forbear doing,
who readeth them in the liberty of his own spirit, out of the light of God`'s Spirit,
which is the limit and yoke of the true readers and understanders of the Scriptures.

==== V. Concerning Christ`'s Ministry, or Priesthood

CHRIST is made by God a minister, or high priest,
over the spiritual Israel of God, "`not after the law of a carnal commandment,
but after the power of an endless life,`" (as Heb. 7:16 and chap.
8:2); and he ministers with his Spirit and power unto and in all his.
So that he that knows Christ`'s ministry, knows the power, the life,
the Spirit in which he ministers; but he that is not acquainted with these,
is yet to learn to know Christ aright, and to believe in him unto life and salvation,
which are wrapped up, comprehended, revealed,
and communicated in the power wherewith he ministers.
For the very beginning of Christ`'s ministry is in the Spirit and power of God,
whereby he redeems out of the spirit and power of Satan;
and to this men are to be turned, if they will witness salvation by Jesus Christ,
even to the light and power of God`'s Holy Spirit,
which breaks the darkness and strength of the kingdom of Satan in the heart.
For indeed all literal professions, beliefs, knowledges, and practices,
out of the life and power, Satan can transform himself into,
and uphold and maintain his kingdom under, in the hearts of men;
but the inward light and power of life breaks it, where the minds of the people are,
by the Spirit of the Lord, turned thereto, and subjected under its rule and government.

==== VI. Concerning the true Knowledge of Christ

IT was said, in the time of the prophets,
under the ministration of the law, that "`the priest`'s lips should keep knowledge,
and they`" (that is, the outward Israel,
Israel after the flesh) "`should seek the law at his mouth;
for he is the messenger of the Lord of Hosts.`" Mal. 2:7. And doth not Christ,
our High Priest, and the Apostle of our profession, keep all the people`'s knowledge?
And are they not all to seek the law of life, the law of the new covenant, at his mouth?
Is not he the Messenger of the covenant,
who brings tidings of the covenant of life and peace;
and must not the soul that will live hear him? Isa. 55:1-3.
Is not he the Sealed and Sent-One of the Father, to open the blind eye,
and to bring the prisoner out of the pit?
Is not he the Shepherd of the spiritual flock?
And are not such as are called out of the world (and sanctified by him) his sheep?
And are not all his sheep to hear his voice, and follow him?
Is not he the Prophet, like Moses, appointed by God,
for all the spiritual Israel to hear in all things?
Is not his Spirit to teach and lead into all truth?
Can any else lead into truth?
Or can any come into truth unless they be led?
And they that will not hear the voice of his Spirit in these latter days (seeing God,
in these last days, speaketh by his Son,
and saith to all the true disciples and followers of the Lamb, Hear ye Him),
are they not to be cut off from the comforts of his Spirit,
from the pure refreshments of his Spirit, from the life of his Spirit,
and from the living Israel, and so to be numbered among the dead and unredeemed?

Christ saith, "`I am the way, the truth,
and the life.`" It is he alone that is the living way, which leads to the Father.
Now, how is Christ the way to the Father?
How is he the truth?
How is he the life?
Is he so by any literal and outward knowledge of him; or by the inward, spiritual,
and living knowledge of him?
They that know his Spirit know the way; and they that walk in his Spirit walk in the way.
This is most certain: they that walk not in the oldness of the letter,
but in the newness and life of the Spirit, they walk in the new and living way.
How is the letter old; and how is the Spirit new?
How is Christ known after the flesh, and so to be known no more?
And how is he known after the Spirit, and so to be known forever?
Man is but flesh, and his knowledge and understanding of things,
of his own fetching from the literal relations and descriptions of them,
is but the knowledge of the fleshly part; but there is a new eye, a new understanding,
a new heart and mind, to which the Father reveals him;
and that knowledge which the new birth receives of the Father, that is spiritual, true,
pure, heavenly, living knowledge.
And so the children of the kingdom are to dwell in that
light wherein the Father reveals the things of the kingdom;
and this differenceth them from all the literal knowers
of the things of God upon the face of the earth.
Now, this is it which satisfieth my heart concerning my knowledge of the things of God,
even that I have so learned to know Christ,
and to believe in him (and to repent from dead works, and to obey him,
and suffer for him), as I could never have learned,
unless the Father himself had taught me.
And now, seeing and partaking of the difference,
I cannot but testify against all dead teachings, unto the Spirit`'s teaching,
which is living; knowing assuredly,
that no other teaching or learning the things of God will amount to the true knowledge,
or be owned in the day of the Lord, but that which is of and in the Spirit.

==== VII. A few Words more concerning the Right Way of Knowing, as it is witnessed unto in the Scriptures, and experienced in the Hearts of those that truly and livingly know the Lord

"`WISDOM is justified of her children,`" said Christ. Matt. 11:19.
Now, who is wisdom?
What is wisdom?
Is it not the heavenly mother of all the living?
It is the Spirit which begets all, who are truly begotten to the Lord.
Now where, and into what, doth he beget them?
In the earthly nature, in the earthly wisdom, in the earthly spirit; or out of it,
in and into that which is heavenly?

Now, all that are of this heavenly begetting and birth,
they know (own and justify) that wisdom, wherein they are begotten.
They justify the nature of truth, the light of truth, the life of truth,
the power of truth, the appearance of truth in their age and generation.
The false birth will own and justify the words of truth which were formerly spoken,
and the former appearances thereof (as the Scribes and Pharisees did Moses and the prophets,
who denied Christ, who was truth, and spake truth beyond them);
but the true birth knoweth and justifeth the present words,
and the present appearances of truth,
which the false birth still slighteth and despiseth.

If any man therefore will judge aright concerning the things of God,
he must be sure to be of the true birth (a child of the true wisdom),
and that he keep to that nature, Spirit, and birth, to which God giveth the discerning.
For there is an eye of discerning, and a way of discerning, which is a gift;
and he that will know aright, and judge aright, must keep to the gift of light,
the gift of grace, the gift of the Spirit, the gift of the holy anointing;
and be watchful and careful to judge in it, and take heed of judging out of it.
For though a man be come to a spiritual state, and hath received the gift of grace,
knowledge, and discerning; yet if he be not watchful to keep to the gift,
he may easily err, and judge amiss.

==== VIII. Concerning Christ`'s Righteousness, which is the Righteousness of all his Saints

CHRIST is the head, his saints the body;
and do they not all partake of one nature, one Spirit, one virtue, one life,
one righteousness?
Doth not Christ give them of his own righteousness,
even of the righteousness which his Father gave him?
And is not that righteousness which Christ giveth them, their righteousness?
What was Christ`'s righteousness?
Was it not the righteousness of God revealed in him, communicated to him, and made his?
And what is their righteousness?
Is not the same righteousness revealed in them, communicated to them, and made theirs,
in and by Christ?
Are not they made partakers of the divine nature, in and through him,
and made the righteousness of God in him?
Christ trusted his Father, and obeyed his Father in all things.
Now, was not that an effect of the righteous nature and Spirit of his Father in him?
"`He became obedient unto death, even the death of the cross.`" And, oh,
how was his Father pleased therewith!
Did not he say to him, as to Abraham in the like case?
"`Because thou hast done this thing, in blessing I will bless thee;
and in multiplying I will multiply thy seed;
and thou shalt see of the travail of thy soul,
and be satisfied:`" for thou shalt not only gather the "`dispersed
of Israel,`" but "`inherit the Gentiles`" also;
"`and have the uttermost parts of the earth for thy possession.`"

Consider now, seriously, in God`'s fear;
Is Christ`'s obedience to the law of Moses the saints`' evangelical righteousness?
Or is his righteousness revealed in them, from faith to faith?
Was his being circumcised outwardly, their circumcision?
Or is his inward circumcising them, their circumcision?
Which of these is the gospel circumcision; the circumcising of his flesh outwardly,
or the circumcising of their hearts inwardly?
Again, was his being outwardly baptized, their baptism?
Or is the inward baptism of the Spirit, the gospel baptism?
Doth he not fulfill the righteousness of the law of the Spirit of life in them,
who believe in his Spirit and power, and walk not after the flesh, but after the Spirit?
Was not Christ justified in the Spirit?
And are not all his justified in the Spirit also?
Whatsoever is of God, whatsoever is wrought in God, doth not God justify?
Is not the person here justified, the faith justified,
the works justified with the justification of life, and of God`'s Holy Spirit,
from whence they proceed?
And here Christ`'s words are verified, "`He that doth truth, cometh to the light,
that his deeds may be manifest,
that they are wrought in God.`" John 3:21. And are not his deeds then justified?
He that is united to the Spirit of God (and acquainted with the Spirit of God,
and knows his voice), hears, and sees, and feels, and understands what God condemns,
and also what he justifies; who never condemns any thing that ariseth from himself,
and is wrought in himself; but only that which cometh from the flesh,
and is wrought in the flesh.
And here he sees (in the true light) what faith is imputed for righteousness,
and what faith is shut out; and what works are accounted righteous,
and what works are shut out:
and how Enoch walked with God in the righteous Spirit and life,
and was therein justified; and how Noah built an ark in the faith, being moved with fear,
and was therein with his family saved.
So Abel sacrificed in the faith, "`by which he obtained witness that he was righteous,
God testifying of his gifts.`" Heb. 11:4. Mark; his sacrifice, his gift,
came from a righteous Spirit, and so the righteous God testified of his gift;
and such are all the sacrifices now, that are offered up in God`'s Spirit,
and in the true faith.
And so we also see how Abraham (the father of the faithful) was "`justified
by works,`" James 2:21. and how God was pleased with him,
because he had done that thing of offering up his only son at God`'s command.
Also Phinehas`'s zeal for the Lord, in executing judgment,
was highly esteemed of the Lord, and "`was counted to him for righteousness,
unto all generations forevermore.`" Ps. 106:30-31.

But alas! how do men mistake about the righteousness of Christ,
about the gospel righteousness; and, in effect, make it but the righteousness of the law,
but the righteousness of the old covenant, performed in the person of another for us,
and imputed to us!
Whereas it is the righteousness of another covenant, even of the new and living covenant,
which the Lord Jesus Christ worketh, both in us and for us.
Now, whoever receiveth this righteousness from him, and is clothed with it by him,
he findeth it to be the righteousness of the gospel, the new and living righteousness,
the true and everlasting righteousness, both of the Father and Son,
which the souls of those that truly believe partake of in them and with them.

Now, consider a scripture or two, to evidence this further.

The apostle saith, 2 Cor. 3:17-18.
"`The Lord is that Spirit`" (the Lord Jesus is the second Adam,
the quickening Spirit) in whom the "`veil is done away,`" ver. 16.
And so the true Christian (in whom the "`veil is done away,`" who
is come into the true liberty of the Spirit) "`with open face,
beholding as in a mirror the glory of the Lord, is changed into the same image.`"

Now mind: if man be changed into the heavenly image, if he partake of Christ`'s image,
is he not made righteous, and become truly righteous therein?
Was not the image of the first Adam holy and righteous?
And is not the image of the second Adam holy and righteous also?
And are not they that are changed from the image of sin and Satan, into Christ`'s image,
holy and righteous in that image?
Are they not changed from unrighteousness to righteousness?
And is not this image, whereinto they are changed,
and wherein they are new created by God, their righteousness?
Whoever is ingrafted into Christ,
is he not ingrafted into righteousness?--cut off from unrighteousness,
and ingrafted into righteousness; even into the righteous nature and Spirit of the Lamb?
And doth he not partake of the righteousness of the Vine or Olive-tree,
into which he is ingrafted?
And doth not that become his righteousness?
If the root be holy, then are also the branches; and if the root be righteous,
so are also the branches; and that is the righteousness and holiness of the branches,
which they have from the root.

The other scripture is that of Eph. 4:22-24. which speaks of putting off the old man,
which is corrupt according to the deceitful lusts;
and of being renewed in the spirit of the mind, and putting on the new man,
which after God is created in righteousness and true holiness.
Mark; here is the new creation.
Now, consider well, what is the holiness and righteousness of the new creation?
Is not that which is put off, old, corrupt, unholy, unrighteous?
Is not that which is put on, new, holy, righteous; even the image before spoken of,
Christ the heavenly image, the new man, which is created and formed in man?
And then God owneth such to be his people. Isa. 51:16.

No man can do that which is righteous,
but he that first partakes of God`'s righteous nature and Spirit.
The tree must first be good, before the fruit can be so.
A man must first be renewed and made righteous, before he can bring forth righteousness.
So that he that doth bring forth righteousness, without doubt he is inwardly renewed,
without doubt he is inwardly righteous.
Did the Gentiles do by nature the things contained in the law?
Then, without doubt, they were partakers of another nature than the old corrupt nature,
which is not subject to the law of God, neither indeed can be.
"`Little children, let no man deceive you; he that doth righteousness, is righteous,
even as he is righteous.`" 1 John 3:7. This is the
true and weighty judgment of God`'s Spirit;
and he that judgeth otherwise is deceived, and erreth in this particular;
and showeth that he doth not yet know God`'s righteousness, and Christ`'s righteousness,
which is one and the same.
For, "`If ye know that he is righteous,
ye know that every one that doeth righteousness is born of him.`" 1 John 2:29. Mark;
the new birth precedes the doing of righteousness;
and the doing of righteousness is a certain evidence of the new birth.
He that doth righteousness is born of God;
this fruit can arise from no other but the pure, living, heavenly root.

==== IX. Of the Grace of the Gospel

THE prophets of old prophesied of the sufferings of Christ,
and the glory that should follow. 1 Pet. 1:10-11.
Now, what was the glory which should follow?
Was it not the setting up Christ`'s inward and invisible kingdom in the hearts of men?
Was it not God`'s abundant pouring out his Spirit, and filling vessels therewith;
so that the Spirit of grace and of glory should rest upon believers,
as it had done upon Christ?
Was it not God`'s tabernacling in men, and becoming their God, and making them his people?
Was it not the fulfilling the precious promises concerning the gospel state,
whereby men should be made partakers of the divine nature (of the heavenly image),
and be changed from glory to glory, by the renewing Spirit and power?
Was it not to have fellowship with Christ, not only in his sufferings and death,
but also in his resurrection and kingdom;
where the bread and wine of the kingdom is eaten and drunk,
and the feast of fat things partaken of?
Is it not a glorious state to be translated out of the kingdom of darkness,
into the kingdom of the dear Son?
And to dwell with Christ in the kingdom; and sup there with him, and he with them?
To have fellowship (pure fellowship, living fellowship) with the Father and the Son,
that the blessedness and joy of the soul in the gospel state may be full?

The law was a ministration of shadows;
for under it were the various and many shadows of the good things to come,
which were to be possessed and enjoyed in the days of the gospel.
In the law there was an outward people (the Jews outward), an outward covenant,
an outward land of blessings, plenty, and rest; an outward Zion, outward Jerusalem,
outward temple, outward ark, outward table, outward laver, outward candlesticks,
outward lamps, outward oil, outward anointing, outward circumcision and sacrifices,
outward new moons and sabbaths, outward kings, outward priests,
and outward victories over outward enemies, etc.

But now, in the gospel, there is the substance of these things inwardly revealed,
and inwardly possessed and enjoyed; even the Jew inward (the new man of the heart),
an inward covenant of life and peace, an inward land of blessedness, of rest;
an inward sabbath or day of gospel rest (which the true believer keepeth in the faith,
not bearing any burden, kindling any fire, nor doing any work of the flesh therein);
an inward Zion, an inward Jerusalem or holy city;
an inward temple (in which is the Holy of Holies), an inward ark,
in which the law of life is treasured up; inward table, inward laver, inward candlestick,
inward lamp, inward oil, inward anointing, inward circumcision and sacrifices,
and solemn seasons; the inward King of glory, inward prophet and priest known,
even Christ within, who giveth victories and dominion over the inward enemies,
and giveth his to partake of his kingdom and priesthood. Rev. 1:6.
Yea,
and (by his Spirit poured out upon them) maketh his seers and prophets also,
as it is written, "`I will pour out my Spirit upon all flesh,
and your sons and your daughters shall prophesy.`"

Now, was not this fulfilled after the sufferings of Christ in the flesh?
And is it not daily more and more fulfilled, as the sufferings of Christ,
which are yet behind, are filled up in his body the church?
Did not the glory then succeed?
Was not the gospel spirit and power then revealed and bestowed?
And did it not bring into the gospel state?
Were not the precious promises fulfilled therein? 2 Pet. 1:3-4.
Are they not all yea and amen in Christ?
Is not the veil or covering taken away in him?
Is not the glory revealed in him?
Is not the Lord one, and his name one in him?
Is there not glory then in the highest, on earth peace, and good-will among men,
as well as good-will in God towards men?
Where is the enmity and wars, and lusts and fightings?
Where is the envy of Judah or Ephraim, or the vexing one another here?
Are not these things drowned in the love and in the peace,
in the life and in the power which is revealed in the gospel state,
and springs up in the gospel spirit?
They know not what spirit they are of,
who would have fire come down from heaven upon the disobedient and gainsayers.
To be sure, they are not of the gospel spirit, not of Christ`'s Spirit,
who came not to destroy men`'s lives, but to seek and save that which was lost,
and to overcome by the overflowings of his love and tender visits of his life.
And how do his children make war in this day?
Is it not with innocency, with meekness, with patience, with bowels of love,
with long-suffering, with truth, with righteousness, like the followers of the Lamb,
like the children of him who abounds therein?
Indeed there is a sword given, there is a threshing instrument,
there are darts and arrows to be shot into the hearts of the King`'s enemies; Ps. 45:3-5.
but it is not to destroy the creature,
but rather to smite and wound that spirit which captivates it,
that the creature may witness deliverance and freedom therefrom: though it is true,
that they who join with that spirit, must partake of its judgments and plagues,
even to destruction, if they so continue.

Now, this glory is wrapped up in the grace which is ministered by the gospel;
and where grace is sown, the glory is sown (there is a true seed of the glory);
and where grace abounds, the glory abounds.
It was said concerning the first gathering of Christians by the apostles,
that "`great grace was upon them all,`" Acts 4:33. and indeed,
it was a precious and glorious state, which they were gathered into and brought forth in.
Now, the grace is revealed again, the grace is poured forth again,
the grace hath appeared, teaching and bringing salvation again;
doth it not behoove every one to know it and partake of
it?--not to be content with words concerning the grace,
but to know the grace itself, receiving it from the hand of him that giveth it,
and hearing the voice, reproofs, and instructions of it?
"`Hear, and your souls shall live.`" Whom should they hear?
Are they not to hear Christ, the great prophet?
How shall they hear Christ?
Is there any other way, than by hearing his grace teaching them?
than by hearkening to the measure of the gift of grace, which is by Jesus Christ?
"`The law was given by Moses`" (all his people, all his children,
all his family were to come under the law, to be governed by the law).
"`Grace and truth comes by Jesus Christ,`" (all his children, all his people,
all his family are to come under the grace,
to be governed by the grace) who is faithful in all his house,
dispensing of his grace and truth to all his,
as Moses did of the law (committed to him) to all under him.
So then, all that desire to be truly Christians,
let them wait to know what the grace and truth which Christ giveth is,
and to partake of it and come under it; under its teachings, under its influences,
under its protection, under its government (by being subject to it;
and in everything guided by it), that they may know what that scripture means,
in the true and weighty experience: "`Sin shall not have dominion over you,
for ye are not under the law, but under grace.`" Rom. 6:14.

==== X. A Question answered concerning real Holiness

[.discourse-part]
Question.
ARE not persons to be really holy (really sanctified
in Christ Jesus) who would be received by the Lord,
and enjoy fellowship with him as sons and daughters, in the gospel of his Son?

[.discourse-part]
Answer.
Under the law, that people of the Jews were to be separated from the Heathen,
to be outwardly circumcised and cleansed by the water and blood
of purifying (which sanctified to the purifying of the flesh),
and not to touch any dead or unclean thing; for any such thing polluted them,
and those that were unclean must be kept without the camp,
as unfit for the holy communion with God and his people, till cleansed.

Now, what did this signify?
Did it not signify that pure and clean state inwardly,
which God requireth under the gospel?
Did it not signify the inward circumcision of the heart and spirit before the Lord,
and the cleansing of the soul, mind, and body,
before its appearing to worship in the inward and spiritual temple? Heb. 10:22.
Is there not a Jerusalem under the gospel,
into which no uncircumcised or unclean thing is to enter, or appear before God there?
Mark what the apostle saith, Heb.
12. "`Ye are not come to the mount that might be touched,`" to outward Mount Sinai,
or Zion, to the appearance of God there; but ye are come to the inward Zion,
and to the city of the living God, the heavenly Jerusalem,
and to fellowship with God and Christ there, ver. 18-22.

Now, what is the way to this holy fellowship and heavenly communion?
Doth not God himself prescribe it? 2 Cor. 6:16-17.
"`Wherefore come out from among them,
and be separated,`" saith the Lord, "`and touch not the unclean thing,
and I will receive you; I will be a Father unto you,
and ye shall be my sons and daughters,
saith the Lord Almighty.`" For God would have a people representatively
holy in the time of the law (yet not destitute of inward holiness),
and he will have a people really holy in the time of the gospel.
"`He that defileth the temple of God, him will God destroy:`" but keep the temple clean,
pure, holy, and then the Holy God will dwell and appear there, according to his promise;
"`I will dwell in them, and walk in them.`" And this is eternally true,
and witnessed by certain experience among them that know the Lord;
that if any thing that is unclean be touched, there is a defilement thereby,
and there must be a cleansing felt,
before an admittance into the presence of the Holy God,
and enjoying fellowship with him again.

==== XI. Concerning the Law of Sin in the Fleshly Mind, and the Law of Life and Holiness in the Renewed Mind; and whence each have their Strength

WHAT is the law of sin?
Who writes it in the mind?
And what is it when it is writ?
"`When lust hath conceived, it bringeth forth sin: and sin when it is finished,
bringeth forth death`" James 1:15. So that the first beginning of sin is evil lust;
and the whole corruption that is in the world, is through lust. 2 Pet. 1:4.
Now, whence cometh that lust?
Is it not begotten in the mind and spirit by the tempter?
And what is the law, both of the lusting, and of the sins committed through the lust?
Is it not the lustful nature, the lustful will, the lustful wisdom,
the lustful desires and passions,
which the god of this world begetteth in the worldly part?
So on the other hand, there is a holy law in the holy and renewed mind.
Whence cometh that law?
Doth it not come from God?
Doth it not come from the Holy One?
Is it not he that blots out Satan`'s law, and then writes his own law in the hearts of his?
Now, what is his law?
Is it not of a contrary nature to Satan`'s law?
What God writeth in the hearts of his, teaching them holiness, requiring holiness,
enlightening the mind unto holiness; manifesting the good, perfect, and acceptable will,
is not that his law?
Under the old covenant the law was at a distance, writ in tables of stone;
but under the new covenant the law is nigh,
written in the heart by the Spirit and power of the Lord Jesus Christ.
For he is King, the inward King, the spiritual King of his people, who cometh to reform,
and amend by his covenant, what was amiss under the former.
Now, because he found under the old covenant,
that laws outwardly written would never bring men into, and keep men in,
subjection to his Father; therefore he writeth inwardly by his Spirit and power,
and visiteth with the inward eternal day, even the day of his power;
and so maketh his people willing to receive the law of his Spirit of life,
which maketh "`free from the law of sin and death.`" For this law being inward and spiritual,
and more powerful than the other, overcomes the other law,
even the "`law of sin and death`" (though it be inward and spiritual,
and inwardly written also), and setteth free from it. Rom. 6:18.
and 8:2.

Now, these laws have each their strength from him that writes them.
The law of sin and death hath its strength from the god of this world,
the prince of darkness,
who ruleth in all that are disobedient to the Spirit and power of Christ.
The law of holiness, the law of life, the law of faith in the power,
the law of obedience to God`'s Holy Spirit, hath its strength from the Holy One,
from the Prince of life and peace; for Satan is near his subjects, and dwells in them,
to act them, and to make his laws of sin and disobedience forcible in them.
Every motion and temptation to sin he kindles, and adds vigor to,
that he may set on flame the wicked spirits of men after sin, vanity, pride, lust,
uncleanness, cruelty, and all manner of wickedness,
that they may draw on iniquity as with cart-ropes, and drink it in as the ox doth water.
And the Lord also is near to the soul; the King of holiness,
the King of righteousness and peace is near,
to give strength to every holy desire in the heart,
and to every motion of his Spirit towards that which is good and holy.
Hence it is, that he that trusts God`'s Spirit,
watching to and following the movings and drawings thereof, finds life flow in,
virtue and strength flow in,
to carry on effectually in that which the Spirit of the Lord moves to.
So that come but truly to know a motion,
to understand the drawings and leadings of God`'s Spirit,
strength is never wanting to him who giveth up in the faith
to follow the Lord in that which he moves and draws to.
And this is the great skill of Christianity, to come inwardly to know the Lord;
to know the inward appearances of the Shepherd, his leadings out into the pastures,
where eternal life is fed on; and again into the fold of rest,
which is no less than the bosom of love, and life eternal.
Now, the growth of the new man, the growth of the Christian state,
is in the exercise under the law of life, under the law of the Spirit.
For the Spirit exerciseth the mind by his law,
and the mind is to give up to the exercise thereof,
and to wait upon the Lord in it day and night; finding itself never without,
but still under the law to Christ in everything.
And indeed, how can a man do any thing aright without the sense and knowledge of the law?
How can a man fight aright with his spiritual enemies
without understanding the law of fighting?
For there is a lawful fighting and an unlawful fighting against the soul`'s enemies.
The unlawful fighting is in the self-will, wisdom, and strength,
according to one`'s own apprehensions and conceivings, which gains no real ground;
and therefore they that so fight cannot overcome.
The lawful fighting is in the faith, in the wisdom and guidance of the Lord,
in his Spirit and power, and this is ever successful.
So there is a lawful running and an unlawful running the race,
which the apostle plainly implieth, when he saith,
"`So run that ye may obtain.`" 1 Cor. 9:24. So likewise there is a law of prayer,
a law of faith, a law of love, a law of new obedience,
a law of liberty (for the liberty under the gospel is not boundless,
but bounded by the Spirit), a royal law, which the King of glory writes,
and keeps living in the heart; by which his will is understood,
and the way of life known,
which never can be understood by any but those in whom this law is written,
even the law of the new covenant, the law of the Spirit of life in Christ Jesus.

Read and consider this seriously:
for indeed it contains the very mystery of Christianity and redemption.
For redemption is not by a notional knowledge of Christ (it is not so witnessed by any),
but by receiving and subjecting to the law of his Spirit.
And mind and wait to know and understand whether
this be not the law which David speaks of,
when he saith, Ps. 19:7, etc.
"`The law of the Lord is perfect, converting the soul.
The testimony of the Lord is sure, making wise the simple.
The statutes of the Lord are right, rejoicing the heart;
the commandment of the Lord pure, enlightening the eyes; the fear of the Lord clean,
enduring forever; the judgments of the Lord truth,
altogether righteous.`" Certainly the law of the Spirit
of life in Christ Jesus is all this,
containing in it the commandment which is life everlasting, and the sure testimony,
and all the holy statutes, judgments, and fear, which the soul need to learn;
and is indeed perfect, and able to convert, and instruct perfectly the converted soul.
And here the scripture is fulfilled under this holy law of the Spirit and power of life.
"`They shall not teach every man his neighbor, and every man his brother, saying,
Know the Lord`" (they shall not do so in this covenant, under this ministration,
which is a ministration not of the letter, but of the Spirit);
"`for they shall all know me,
from the least of them to the greatest of them,`" by the teachings of my own Spirit,
by my writing my law in their hearts, by my holy unction, which shall teach my children,
my anointed ones, all that they need to know. 1 John 2:27.
Jer.
31. and Heb.
8.

Come, be not deceived about the new covenant; but wait to find the entrance thereinto,
and to feel the virtue thereof, and to know and receive the law and power thereof,
as becometh Christians.

==== XII. Concerning God`'s gathering us Home to himself, who are a people despised and rejected of Men, and in Scorn by them called Quakers

IT pleased the Lord, who is rich in mercy and goodness,
to pity our many wanderings and sore distresses,
and at length to gather us home to the light and Spirit of his Son,
which was the gospel standard in the apostles`' days.

Now, that by which God gathered us was the power of Christ,
and the preaching of the everlasting gospel by the ministry
which he hath raised up in these latter days.
For as the Lord raised up a ministry to preach it at first,
when he had some of the Jews and many of the Gentiles to gather;
so he hath raised up a ministry to preach it again after the apostasy,
that he may cause the sound thereof to go through all nations.
And this ministry hath been raised to go forth in the same virtue, power,
and Spirit wherein the foregoing ministry was sent.

God promised of old, that he would seek after, search out, and gather home,
his scattered sheep himself, and become their Shepherd.
Ezek.
34. Now, this was fulfilled in a great measure in the days of Christ and his apostles,
when Christ came himself, and also sent his apostles after him,
to seek and gather the lost sheep of the house of Israel; and not only so,
but also to preach the gospel to all nations,
that he might be God`'s salvation to the ends of the earth,
gathering and saving lost and scattered souls out of every quarter and corner thereof.

But afterwards (after the spreading of the gospel,
and Christ`'s gathering of many thereby) there was a great apostasy,
and scattering from this holy standard of life and salvation,
and darkness overspread the nations again, and an antichristian reign and kingdom got up,
under a form and forms of godliness, without the life and power;
in which forms people generally have been scattered from the life and power,
which indeed is the gospel.

Now, in this cloudy and dark time,
great hath been the loss and distress of the poor hungry sheep;
their shepherds and watchmen not being able to preach the gospel distinctly to them,
and direct their minds to the Spirit and power which saves: therefore God,
in pity to this sad and lost condition of his sheep,
sends his angel to preach his everlasting gospel to "`them that dwell on the earth;
to every nation, kindred, tongue, and people.`" Rev. 14:6.

Now, as the former publishing of the gospel began at the scattered Jews,
who were God`'s people under the law; so this begins at the scattered Christians,
who had some true desires, and had been seeking after the Lord (from mountain to hill,
and hill to mountain), but could by no means find him;
nor by any of the watchmen hear any certain news of their souls`' beloved.
But the Lord, in his tender love and rich mercy, in the appointed time,
sends forth the Shepherd of Israel to seek and find them out.
And, blessed be the Lord, he sought them effectually, and hath found out many,
and persuaded them to follow him;
and hath brought their weary souls home to their proper resting-place,
where they dwell under the care of the Shepherd and Bishop of their souls.

But if any shall yet further inquire, How, and by whom, the gospel was preached unto us,
my answer is, By the Shepherd himself.
God himself gave forth the sound,
and great hath been the company of them that published it;
and our ears and hearts were opened by the Lord to hear the sound,
and know the Shepherd`'s voice.

And mind my words (which the Spirit of the Lord is now uttering forth through me),
for they are words of truth, and certain understanding;
they that do not hear and own the sound thereof now
(from this ministry which the Lord hath now chosen,
and sent forth),
would not have heard nor owned the sound thereof in Christ`'s and his apostles`' days,
had they lived therein; but would have reproached and opposed them,
had they lived then in those days, as they do now in these days.
For of a truth it is the voice and sound of one and the same Spirit and wisdom;
and they that do despise the one, would have despised the other,
had they lived in the day of the appearance and manifestation thereof.

And then, for the manner of its preaching, it was just such as is described,
ver. 7. of Rev.
14. For we are commanded to "`fear God, and give glory to him,
because the hour of his judgment`" (the great and terrible day of the Lord) "`was come`";
and therefore to leave off all false ways and worships,
and learn to worship the living God, the Creator of all, in Spirit and in truth.
And truly it was a terrible day to the man of sin in us;
for the judgments of God were revealed against him,
and we in fear lay under the judgment, that we might learn righteousness,
and witness the redemption of Zion thereby.

Now, being thus turned to that light and Spirit and power which judgeth,
it wrought effectually in us against the darkness and power of Satan; searching, trying,
manifesting, judging the secrets of our hearts daily.
It tried all our knowledge, all our faith, all our desires, all our thoughts, words,
ways, and worships;
so that all things were naked and open before him with whom we had to do;
and what had gone before as glorious and taking in our eyes,
was now manifested to be loathsome and abominable in the sight of God.
For indeed, the axe was laid to the root of the tree,
and every plant which the heavenly Father had not planted was he now plucking up,
that they might no longer cumber the ground;
but he might have room for his own seeds and plants of holiness and righteousness,
which he was ready to sow in his own garden.

And so at length we came to witness (abiding the trial of this dreadful day,
wherein our God appeared to us as a consuming fire) a new heaven and a new earth inwardly;
and no more sea of wickedness, no more sea of inward trouble; but righteousness, peace,
and joy inwardly; and our God becoming a rich portion to us,
watching over us in most tender care and love, and delighting in us to do us good,
making known to us the riches of the gospel, even the feast of fat things;
and giving us to partake of the well or fountain of living waters in our own hearts,
which springs up freshly in us daily, unto life eternal.
So that we were not only invited to the waters, but taught also to come thereto:
and when we came, we were not sent away empty, but had the water of life given us;
which became such a well, as out of it flow streams of living water.
Ah, blessed be the Lord!
Did we ever think, in our dry, dead, barren estate, to have seen such a day as this?

And all this we met with in the way of self-denial, and taking up the cross;
in denying our own wisdom, our own knowledge, our own faith, our own righteousness,
and all that we could call our own; and owning a little seed of light and life eternal,
even the seed of the everlasting kingdom, which the Shepherd of Israel discovered to us,
and helped us to search after, and taught us how to find;
which was indeed in a way very despisable, even to the eye of our own wisdom.
For thus it was: --

We had been long looking out abroad, searching very diligently the Scriptures,
and other serious books, for great, full, certain, and undoubted wisdom and knowledge;
but now we were directed to turn inwards (even thither where we thought
no good was to be found) to mind the appearance of God there,
the Spirit of God testifying to us (according to
the Scriptures of truth) that the kingdom was within;
and there we were directed to search for the least of all seeds,
and to mind the lowest appearance thereof;
which was its turning against sin and darkness;
and so by minding and observing that in us which turned against sin and darkness,
we came by degrees to find we had met with the pure, living, eternal Spirit;
and by observing the movings, stirrings, guidings, directions, and law thereof, we found,
ere we were aware, that we had met with the law of the new covenant,
the law of the Spirit of life, which had life and virtue in it,
to enable us to do the holy will; and then our hearts rejoiced,
being made truly sensible that we had found that which we had mourned after,
and longed for all our days.
And then we began to see our way more clearly, and to wait on our God for his teachings,
and to follow the Lamb, our leader, with joy and comfort.
For indeed, this experience greatly settled our spirits; knowing assuredly,
that as none but Christ could do those works outwardly
which he did in the days of his flesh;
so none beneath his Spirit could do these works inwardly, enlighten inwardly,
enliven inwardly, bind up and heal inwardly, open the inward eye, the inward ear,
the closed heart, and loosen the dumb tongue, so as the touch of his power,
and virtue of his life and holy presence among us,
hath done very frequently and livingly.

And now, is this testimony nothing to you, O ye professors, that we have found him,
by God`'s holy guidance (or rather have been found by him),
whom we could never find in your ways and gatherings?
But still that which God had quickened in us was there unsatisfied, weary, panting,
and gasping, for want of, and after, the breath of life.

Oh, come and see if this be not he indeed!
Wait to feel the closing of that eye which cannot
see (which God hath ordained shall never see),
and for his opening the eye which is as yet blind
in you (to which he giveth the true sight),
that ye perish not from the way of life,
through mistakes and deceits from the mists of darkness,
which are yet over all who have not seen the light of God`'s day.
To the law, and to the testimony (to the inward law, and inward testimony,
if ye be inward Jews; for the law inwardly written is light,
even the light of the living, and the testimony of Jesus is the Spirit of prophecy);
for he that knoweth not these, nor walketh according to these,
nor speaketh according to this Word, it is because there is as yet no morning in him.

Oh, come to the morning light of the everlasting day!
Come to the Son`'s light, to the Son`'s Spirit!
Wait for the dawning of the day of righteousness, love, and peace,
and for the arising of the day-star.
COME DIE TO YOUR OWN WISDOM (it was the word livingly spoken to me,
and entered my soul when it was spoken; never departing from me,
though I was long in learning it), and know what it is to suffer with Christ,
that ye may also reign with him.

Ah! if that candle were lighted in you,
which ye so much reproach and despise the light of, ye might see,
that instead of suffering with Christ, that which is of Christ in you (the pure light,
the pure life of his Spirit) suffers by you, and the worldly spirit lives (shall I add,
and reigns?) in you, under all your professions, knowledge, faith, worships, duties,
ordinances, as ye call them, who want the knowledge of the everlasting ordinance,
even of the Spirit and power of our Lord Jesus Christ;
which is the great ordinance and way of the gospel.
And he that is subject to this ordinance shall be saved;
but he that misseth of this shall perish; let him search the Scriptures,
and practise according to what he apprehends therefrom, as exactly as he can,
without this Spirit and power.

==== XIII. A few Words concerning the Worship which our God hath taught us

OUR worship is a deep exercise of our spirits before the Lord,
which doth not consist in an exercising the natural part or natural mind,
either to hear or speak words, or in praying according to what we, of ourselves,
can apprehend or comprehend concerning our needs; but we wait,
in silence of the fleshly part, to hear with the new ear,
what God shall please to speak inwardly in our own hearts; or outwardly through others,
who speak with the new tongue, which he unlooseth, and teacheth to speak;
and we pray in the Spirit, and with the new understanding, as God pleaseth to quicken,
draw forth, and open our hearts towards himself.

Thus our minds being gathered into the measure, or gift of grace,
which is by Jesus Christ; here we appear before our God, and here our God,
and his Christ, is witnessed in the midst of us.

This is that gathering in the name, which the promise is to, where we meet together,
waiting with one consent on the Father of life,
bowing and confessing to him in the name of his Son; and that fleshly part,
that fleshly understanding, that fleshly wisdom, that fleshly will, which will not bow,
is chained down, and kept under by the power of life, which God stretcheth forth over it,
and subdueth it by.
So then, there is the sweet communion enjoyed, the sweet love flowing,
the sweet peace of spirit reaped, which the Father breathes upon,
and gives to his children; the sweet joy and refreshment in the Lord our righteousness,
who causeth righteousness to drop down from heaven,
and truth to spring up out of the earth.
And so our Father is felt blessing us, blessing our land, blessing our habitations,
delighting in us, and over us to do us good;
and our land yields its increase to the Lord of life, who hath redeemed it,
and planted the precious plants and seeds of life in it.

=== THE CONCLUSION

Now, this ought to be the great care of every renewed mind,
even to keep out that which is unclean.
The enemy will be assaulting, tempting, casting into the mind that which is unclean;
but the pure, chaste mind will not entertain or touch it,
but withdraw and retire from it into the place of safety,
into the strong tower of defence, from all the assaults and annoyances of the enemy.
Such the Lord receiveth, such the Lord delighteth in as his dear children,
and in every respect carrieth himself as a Father to;
and this is a precious state truly to enjoy.

Now, blessed be the Lord, who hath revealed and bestowed on his sons and daughters,
in these latter days, that light of his Holy Spirit,
which searcheth the most inward parts,
discovering everything that is of a contrary nature to itself,
turning and separating the mind therefrom, and bringing the mind, heart, soul,
and spirit under that which is a cross and yoke to it,
and hath power from God to crucify and subdue it;
that so life and immortality may be brought to light, and reign in the heart;
and death and uncleanness be swallowed up in victory.
For this is the intent of the gospel, and of Christ`'s appearance, even to destroy sin,
and bring up the holy seed, and establish the law of the new covenant, the law of love,
the law of life, righteousness, and holiness,
in which the renewed should walk before the Lord all their days.

And God forbid,
but that the gospel of our Lord Jesus Christ (which is the
power of God unto salvation) should attain its end,
and the will of God be fulfilled; which is the sanctification of his people in soul,
body, and spirit; that they may be wholly leavened with the leaven of his kingdom,
and become a new lump to him.

The Lord bring this to pass in the hearts of the children of men,
bringing down all religions which have not the true virtue in them;
and propagate and establish that religion more and more which stands in the evidence,
demonstration, virtue, and power of his own Spirit;
that men may be redeemed out of and preserved from deceit in matters of religion,
wherein the eternal condition of their souls is so deeply concerned!
Amen.

