[short="Concerning Reading the Scriptures Aright"]
== A Question Answered Concerning Reading the Scriptures Aright

[.discourse-part]
Question.
How may a man know whether he readeth the Scriptures to his advantage and benefit?
or whether he readeth them to his disadvantage or hurt?

[.discourse-part]
That the holy Scriptures, written by men inspired by God`'s Spirit,
were of great use and benefit to those to whom they
were written (they rightly understanding them,
and becoming subject to the voice of God`'s Spirit in those
that wrote or spoke them) is an undeniable truth.

And that they were not only written for them, but for others also, in future ages,
who also may reap benefit in the reading of them; this is as manifest.

Yet that men may so read them, as not to understand them aright,
but misapply them to their own hurt; that is true also, and hath been often,
and is still evidenced by lamentable experience.

The Jews, the Scribes and Pharisees, heard and read the law and prophets to their hurt;
some in a spirit of direct opposition to the truths and will of God,
held out by the prophets; others in a spirit of misunderstanding.

Thus the Scribes and Pharisees, in Christ`'s time,
so read the words of Moses and the prophets (who testified concerning the Son,
and his coming), as that thereby they became strong, wise, and confident,
in opposing him when he came.
They thought they could prove by scriptures, that _this_ was not, could not be, He:
he was to be a glorious King, and to restore Israel.
This was a mean man, a carpenter`'s son; and so taught, and so behaved himself,
that if men _believed in him,
the Romans would thereby be provoked to destroy their place and nation._
He was an eater, a drinker, a friend of publicans and sinners,
a frequent breaker of the sabbath, a Galilean, etc.
"`And shall Christ come out of Galilee?
Search and look;
for out of Galilee ariseth no prophet.`" John 7:52. As if they had said,
can this be the Messiah, of whom the Scriptures have so abundantly prophesied,
who cometh out of Galilee,
out of which the Scriptures have not prophesied of so much as any prophet to arise?
Thus they read the Scriptures to their hurt.

And so afterwards, in the apostles`' days, men wrested the words of the apostles,
as they did also the other scriptures, to their own destruction.

And since, in the apostasy from the apostles`' spirit, life, and doctrine,
and the coming up of many sects, heads, and horns;
which of them have not so read the scriptures,
as to confirm themselves even in those very doctrines and practices,
which are directly contrary to the doctrines, practices, and spirit of the apostles?

Yea, since God`'s breaking the darkness of the night,
and causing the light of his day again to arise,
how do men read and understand scriptures?
Even so as to oppose this light, life, spirit, and power, now it is again made manifest;
thinking and judging its appearance now (according to their understanding of,
and apprehensions on,
the Scriptures) to be as contrary to its appearance in the apostles`' days,
as the Scribes and Pharisees judged Christ`'s appearance in their days,
to be different from, and contrary to,
what the prophets had prophesied concerning the Messiah.

Therefore it is a matter of very great weight,
for a man to know when he reads the Scriptures aright, that his table (whereon he feeds,
and by which food he hopes to live to God,
and be accepted with him) become not his snare, and set him further off from God.
For it is as true in this day, as it was in Christ`'s day;
that publicans and harlots are nearer the kingdom, than those who are in the spirit,
wisdom, and righteousness of the Scribes and Pharisees; who have a knowledge, a belief,
a hope, a zeal, etc. from a misunderstanding of the Scriptures;
for this is wrong in a mystery of deceit, which is worse in its nature,
and more dangerous to the person in whom it is,
and to the souls of others than the deceit which is openly manifest.

Well then; Is it not worth the diligent inquiry, and waiting upon God to know,
_What is the right reading of the Scriptures; and whether a man so read them,
as is to the benefit and profit of his soul, or to his loss and detriment?_
To come then to the Answer, which is as followeth.

[.discourse-part]
Answer.
He that reads the Scriptures in a true measure of life received from God,
he reads them aright; and whenever he so readeth, it is to his benefit.
He that readeth out of that, readeth to his hurt; that being then up in him,
which misunderstands, misapplies, and grows conceited, wise, and confident,
according to the flesh; and so he is thereby liable to, and in great danger of,
setting up his interpretations, instead of the meaning of God`'s Spirit;
and of condemning that which doth not assent and agree therewith,
though it be ever so necessary and precious a truth of God,
and ever so fully demonstrated by his Spirit,
to those who are in the true faith and understanding.

The true birth is meek, tender, gentle, fearing before the Lord, waiting upon him,
often crying to him, that it may not be deceived, that a wrong thing get not up in it;
that it receive not any thing for truth, but what he knoweth to be truth;
and when the Lord pleaseth to give the true knowledge,
that it hold that knowledge of his truth in righteousness, in his life, in his will,
in his wisdom, etc.
But the wrong birth is not so, nor is its course thus;
but that is subtle in searching and forming of things, and holding them in the subtlety,
and drawing the wrong part in others to own and acknowledge
that which it represents and holds forth as truth.

There is a wisdom in man, which is against God;
which wisdom opposeth the wisdom of God two ways; either in a direct, opposite way,
or in a secret, subtle, undermining way.
Now, no man can come to God, or truly understand or receive the things of God,
but as this wisdom comes to be confounded and destroyed in him,
by the light and power of God.
All its strong holds, all its subtle imaginations,
all its reasonings and consultings must be dashed, and brought to nought,
before the truth of God can have full place and power in the heart.
Now, in the true discovery of this wisdom to man, and in his denial of it,
watching against it, and turning to the other; he may wait upon God aright,
receive the knowledge of the heavenly mysteries aright, read the Scriptures aright,
come to the true sense, understanding, and experience of them; but at any time,
so far as he is out of this, he is liable to the snare,
to the misunderstanding of scriptures,
and to the fleshly confidence that ariseth thereupon.
So that, having taken up a misunderstanding of a scripture, or some scriptures;
he will even boldly venture to speak evil of the heavenly and spiritual dignities,
which are of God, and the holy truths which are held forth by his holy ministers;
against the prophets in their day, against Christ and his apostles in their day,
against the witnesses in the times of the apostasy,
and against the angel (learn who that is) that is to preach the everlasting gospel again,
after the apostasy.
Ah! how doth this wisdom destroy and entangle;
and how hath it destroyed and entangled many at this day,
who think they are greatly for God in those things and practices,
wherein they are directly against him; and that they only oppose error,
and a wrong spirit, when they are opposing his truth and his Holy Spirit!
And it is impossible it should be otherwise,
while they judge and act from that which is wrong, and in that which is wrong.
Now mark:

The Spirit, the truth, the life, the substance, is God`'s forever;
the unclean spirit cannot enter into it, the unclean womb cannot conceive of it,
nor bring it forth; but the letter, the shell, the outward figure,
the outward relations and descriptions of things; the other spirit, wisdom,
and nature in man may read, guess at, transform, receive, believe,
and build up with according to the flesh.
And here is the foundation and rise of antichrist and Babylon,
among them who raise up a building, a knowledge, a faith, a hope, a church, a worship,
duties, ordinances, justification, sanctification, etc. in imitation of Zion.
But they are not the thing itself, but false representations of the thing;
either such as were invented by man, or such as were once appointed,
and made use of by the Spirit of the Lord.
For there is little difference between inventing a new thing,
and making use of an old thing, which once was of God, but is now understood, observed,
and practised out of the sense, light, and guidance of his spirit, in another spirit,
and according to another wisdom.
Now, this is not the right way of reformation; to wit,
to return to outward (literal) things, which were practised by the Jews in their day,
or by the former Christians in their day; but to return to the Spirit that they were in,
and to feel (in the true life and leadings thereof) what
it teacheth and requireth to be observed and practised now.
For there are things, whose value is not in themselves, but in God`'s requiring of them;
which the wrong spirit may get into,
and the Lord may draw his people out of them (as he did out of the outward court,
into the inward building or temple, by his light and Spirit within,
when he gave the outward court to the Gentiles.
Rev. 11:1-2). And he that is found in those things,
after God hath given them to the Gentiles, and drawn his people out of them,
is not therein owned or accepted of God,
though God may bear with him in the time of his ignorance;
yet if he abide in them after the rising of light, and its testimony,
the Lord will not so bear with him; but will condemn him,
and deal with him as a transgressor of that covenant,
wherein life and peace with him is witnessed.

Therefore, in all things that concern God, whether in reading the Scriptures, praying,
or observing any thing ye call duties and ordinances,
oh that ye would approve yourselves Christians indeed,
waiting to know your guide and leader, and the true limits which are set by God;
that ye may serve him in the true faith, Spirit, and understanding,
even in that which God knoweth to be so, and not in that which ye may falsely account so!
For mark; if ye be Christians, are ye not in Christ, and is not Christ in you?
And are ye not to feel his life, and the guidance of his Spirit,
so as ye may live in the Spirit, and walk in the Spirit, read in the Spirit,
pray always in the Spirit, believe in the Spirit, worship in the Spirit,
and in the holy understanding of his truth, which is of him?

He that would be right in religion, must have a right beginning.
How is that?
He must begin in the Spirit: his knowledge, his faith, his hope, his peace, his joy,
his righteousness, his holiness, his worship, etc. must begin there.
He must come out of his own spirit, his own wisdom,
the counsels and thoughts of his own heart; and wait on him,
who beginneth the work of regeneration and life in the heart.

And he must afterwards diligently watch against that spirit and wisdom,
from which the Lord hath led him, that it at no time again enter him;
for it will be striving to lead him out of the way, with likenesses,
and false images of things, with knowledge falsely so called,
with a faith which is not truly of God,
nor of the same nature with that which he first felt; with false hopes, false fears,
false joys, a false righteousness and holiness,
which are not Christ`'s nor according to the Scriptures;
but only such as he apprehends to be so.
For a man, who once tasted the truth, and in some measure judged aright,
may afterwards err in his palate and judgment, and then take the wrong for the true,
not keeping to that, nor being now in that, which formerly gave him the true relish.

Now, he that would meet with the true religion, the religion of the gospel,
must meet with the power, receive the power, believe, dwell, and act in the power.
For Christ was made a king, priest, and prophet,
"`not after the law of a carnal commandment,
but after the power of an endless life:`" and his covenant is not like the old,
in word or letter; but in the same power and life wherein the priest was made,
and ministers.

So the knowledge here, the faith here, the hope here, etc. are not literal, but living.
He that receiveth this knowledge, receiveth living knowledge.
This faith gives victory over unbelief,
and over that spirit whose strength lies in unbelief.
This hope purifies the heart even as he is pure.
And he that receiveth the righteousness of this covenant, receiveth a living garment,
which hath power in it over death and unrighteousness.
The beginning of this religion, of this power and holy inward covenant, is sweet;
but the pure progress and going on of it much more pleasant,
as the Lord gives to feel the growth and sweet living freshness of it;
notwithstanding the temptations, fears, troubles, trials, oppositions, and great dangers,
both within and without,
which the life (which was at first turned to) being still kept to,
by the power which is from it, and through the faith which is in it,
in its own seasons and way of its own wisdom overcomes,
giving the soul that is diligent and faithful, to witness,
that _all its ways are pleasantness, and its paths peace;_ yea, the very _yoke is easy,
and the burden light,_ when the mind and will is changed by the power,
and helped and assisted by the Lord in its subjection to the power.

So the Lord God of tender mercies (who pitieth the miserable and erring out of the way,
especially those in whom he hath begot desires after himself) remove the stumbling-blocks,
and lead the wandering Jews (who are entangled in their own thoughts and
reasonings about the letter) into that which is of himself in them,
which is Spirit and life, and was before the letter,
and excels the letter (with its dispensation) in glory;
and is to remain (after the letter) the rest, joy, life, peace,
and portion of the soul forever and ever.
So honor the letter, in believing its testimony concerning Christ,
who is the Shepherd (to whom the Sheep are to be gathered), the way, the truth,
the life itself, to whom the soul is to come, and on whom the soul is to wait for life;
and having received life from him, to dwell, abide, and grow up into him,
who is the life; and not go backward into any thing that is literal, or without life,
nor to glory in the knowledge, or literal descriptions of things;
but forward into the spiritual, heavenly dispensation of life and power.
The law was letter, the gospel is life and power;
the law was a shadow of good things to come; but the gospel is the substance, the life,
the virtue, the Spirit of what the law shadowed out.
From hence the Christian is to spring; the Jerusalem from above is to be its mother,
the Holy Spirit its begetter.
And because here the state of true sonship is witnessed,
therefore God pours out the Spirit of his Son upon these;
and then the Spirit being received, which is above the letter,
a life is to be felt and lived in beyond words; even that which the good words lead to,
and end in.

And here the truth, sweetness, and fulness of words is known, felt, and witnessed,
even in that which comprehends them, and gives them their due weight and measure.
Nor can any possibly understand the words of the Spirit, but he that is in the Spirit;
and then he knows the place of the words which came from the Spirit,
and of the Spirit from whom the words came.
And this is precious; but not to be witnessed by the wise disputer,
but by the serious traveller, who first is broken and dashed to pieces in his own wisdom,
and then afterwards healed, led, and guided by the eternal Spirit of wisdom,
which is the sure and unerring guide.

The Spirit of God knoweth the things of God, and the states of persons,
and what is proper or improper for them:
he knew what was proper for the Jews under the law and prophets,
what was proper for them in Egypt, what in the wilderness, what in Canaan,
and what in their several dispersions and captivities;
for the disciples in the days of Christ`'s appearance in flesh,
for the churches in the days of the apostles,
for the witnesses and mourners in the times of the apostasy,
and for those who by his power are raised up, and delivered out of the apostasy.

And the Spirit of the Lord doth not only know the state thus in general,
but likewise every soul`'s particular state, and how to apply things to its state.
There are some newly quickened, newly come out of the darkness.
There are several states and degrees of growth; there is a tempted state,
a wandering state, a backsliding state, a shaken state, an established state, etc.
Now, there is somewhat proper to every one according to his state,
which the Spirit of the Lord knows; and those who are called out by him,
to minister in his name and power, know also, as his Spirit pleaseth to teach them,
and make manifest to them.
All truths are not proper to every state, nor all remedies to every disease.
Christ had many things to teach and say to his disciples,
which they were not able to bear; and a man in reading the Scriptures,
though he should understand the truth of what he reads, yet he is apt to misapply things,
as to himself or others, unless the Lord guide and help him.
He is apt to apply that to him which belongs not to him,
and thrust that from him which belongs to him.

Thus may a man easily err, and wander from error to error,
and toil and wear out himself in his several apprehensions, ways,
and practices (thinking he doth as he ought, and as God requires of him,
according to the Scriptures), and yet his mind be from that,
and his understanding out of that, which opens the Scriptures aright,
and gives the right use of them.

Therefore wait on the Lord to feel quickenings from him,
through a measure of his life revealed, and the mind gathered into, and purged thereby;
and then wait for the Spirit`'s appearing to thee in this measure; further quickening,
purifying, guiding thee, and manifesting his truth therein to thee,
according as he sees thy need, estate, and condition to require.

And thus thou wilt be like a child, living not upon a wisdom of thy own,
but upon thy Father`'s wisdom, and not gathering a knowledge according to thy own will,
and into thy own comprehension;
but receiving it as a gift daily from the hands of the Father,
and so thou shalt always have it fresh and living, and safe for thy use; whereas that,
whilst thou keepest in thy comprehension, and canst run to when thou listest,
and make use of when thou listest, putrefies, and yields but corrupt nourishment,
feeding not the living, but the dead, in thee;
and so thy very knowledge corrupts thy mind, and brings it into death;
and thou hast only such a knowledge as may be held in the dead part,
and so livest and walkest as man may live and walk,
without the pure life and presence of God.

So this is the answer which was in my heart (and indeed sprang up in me,
as the question was laid before me in spirit).
In the true measure of life, which is from God, and one with him,
the Scriptures are rightly read and understood, in the will of God,
by him that doth it in the holy understanding which comes from him:
not in a man`'s own will or understanding;
for he cannot understand what scriptures he will, nor when he will, nor as he will;
but he must wait on him who hath the key,
who understandeth what is fit and proper for him, to know, or not to know;
and so openeth or shutteth in his eternal pleasure, and according to his eternal wisdom;
and what he openeth to thee, that is proper for thee to know;
and what he shutteth from thee, that is proper for thee (as yet) not to know;
but to wait the times and seasons of things, which are in the Father`'s hand.
And so, what the Lord reveals not to thee, that is yet a secret with him, as to thee;
but what he reveals to thee,
that is thine in his fear and counsel to feed on and make use of.

So here, in the gathering of life, in the holy building,
there is a holy order and wisdom from the Most High,
wherein every one waits on the Master, on the Lord, on the Shepherd,
on the Father of Spirits, and receives from his hand, what is proper to his state.
And so all hold the head, and live by the life, virtue,
and teaching that comes from the head.
And there is one God who is over all, and one Christ in whom all are,
and one Spirit of life in which all are baptized and joined together.
And every one as he springs from this life, and feels the union, virtue,
and fellowship thereof, so abiding here, he is in his place and service,
beloved of the Lord and Father of all, and felt by the life in all,
in the unity of the body; and so cherished and helped forward in the love and Spirit,
wherein the body is knit to the head; yea,
whatever his state be (whether a state of mourning or temptation or deep distress,
or a state of joy, rejoicing, and peace), yet abiding and waiting on the Lord,
he is felt, received, owned, and dearly beloved in the Lord.

=== A few Words to such as complain for want of Power

Be sure ye receive Christ; for he is the same that ever he was.
"`To as many as received him, to them gave he power`" (not only to stand against sin,
but) "`to become the sons of God;`" he did so formerly, and he doth so still.
And they that are true Jews, born after the Spirit, truly circumcised,
and are indeed come to Mount Zion, and the heavenly Jerusalem inwardly,
feed on God`'s holy mountain, and dwell in his holy city,
in the building that is from above, for the birth which is from above.
There is no complaining in the streets of this city; but what God requireth is performed,
and what God promiseth to his is enjoyed there,
according to the several states and conditions of each,
and according to the ability which is given in the new covenant,
where God fulfilleth the good pleasure of his goodness, and the work of faith with power,
in the hearts of his daily.
Everlasting praises and honor to his name!

Oh, the precious name of Jesus,
in which the spirits of the redeemed meet! in which name is power;
and he who is the arm and power of God is in the midst of them.

They who receive him who is the power, who is a spiritual vine and olive-tree to all his,
who yields daily of the living sap and virtue to them (wherein there is power);
how can they want power?
Or how can they but praise the Lord,
who daily ministers unto them of the power of the endless life?
When the holy life and power springs, and is felt,
praises to the Lord cannot but spring with it.

So that it concerns all people seriously to consider,
whether the reason why they have not power, be not because they do not receive Christ,
who hath all power in heaven and earth given to him.
For many talk of Christ, but few come to him in the Father`'s drawings;
so will not receive him; like the Jews who waited for his appearance,
and yet rejected him when he came.

[.signed-section-signature]
Isaac Penington
