== SOMEWHAT RELATING TO CHURCH-GOVERNMENT 

WHEREIN THE

NECESSITY, USEFULNESS, AND BLESSED EFFECTS OF THE TRUE CHURCH-GOVERNMENT ARE HERE AND THERE HINTED AT; AND THIS CLEARLY MANIFESTED

THAT

THE AUTHORITY AND POWER OF CHRIST`'S SPIRIT IN HIS CHURCH IS NO USURPED ANTICHRISTIAN AUTHORITY, NOR CONTRARY TO THE TRUE LIGHT AND LIBERTY OF ANY PARTICULAR MEMBER, BUT A CHERISHER AND PRESERVER OF IT

AS ALSO

REMARKS


UPON SOME PASSAGES IN A LATE BOOK, ENTITLED, "`ANTICHRIST`'S TRANSFORMATIONS WITHIN`" DISCOVERED BY THE LIGHT WITHIN

WHEREIN THE


ANTICHRISTIAN TRANSFORMER IS MADE MANIFEST, AND THE LIGHT WITHIN CLEARED FROM HIS FALSE IMPUTATIONS AND PRETENCES TO IT

Written in obedience to Him that is true: who hath given a certain testimony against him that is false, to very many in this his day; and, among others, to me also; whom he hath pleased to gather and own among his children and servants in truth


ISAAC PENINGTON


+++[+++ca. 1675, published posthumously]


"`For God is not the author of confusion, but of peace, as in all churches of the saints.`" 1 Cor. 14:33

"`For what have I to do, to judge them also that are without?
Do not ye judge them that are within?`" 1 Cor. 5:12

"`The government shall be upon his shoulder, etc.
Of the increase of his government and peace, no end,`" etc.
Isa. 9:6-7

"`Woe unto the world, because of offences; for it must needs be, that offences come; but woe to that man, by whom the offence cometh!`" Matt. 18:7

"`For there must be also heresies among you; that they which are approved may be made manifest among you.`" 1 Cor. 11:19

"`Also of your ownselves shall men arise, speaking perverse things, to draw away disciples after them.`" Acts 20:30

"`For not he that commendeth himself is approved; but whom the Lord commendeth.`" 2 Cor. 10:18


=== PREFACE

IT hath pleased God, in these our days,
to cause his true light to shine forth out of darkness.
Oh, everlastingly blessed be his name!
He hath laid the foundation of life in many hearts,
and gathered his once desolate people into families and churches;
and hath been with them, and is with them, dwelling among them, preserving them,
building up Zion more and more, and causing his glory more and more to appear therein.
The living God hath made us a living people, and honoreth us with his living presence,
and with the daily manifestations of his pure power.
Oh! glory, glory is sounded to him, in his own springing life,
in the hearts of his children, day by day.

But the enemy of God and his appearance,
hath wrought against his power and work many ways,
and hath endeavored to stop the gathering to the light and the building up,
not only by outward force,
but also by all the devices and mysterious workings he could invent.
But blessed be the Lord, who hath appeared against them all,
and preserved his remnant from them all; though some that have not watched and lain low,
but being soaring high, in that part where the snare is laid and takes,
have stumbled and fallen.
Yet truth stands, and the gathering in the truth stands;
and the life which God hath raised, and to which he hath given dominion, reigns;
and much is subdued, and the Lord is going on to subdue more and more under it daily,
in the hearts of such as sensibly and livingly, and not notionally and in a dead,
formal way, wait upon him and worship him.

Now, the sorest and most mischievous way of opposing truth, is by pretending to it.
Who could more advantageously or readily betray Christ, than an apostle of Christ?
And who can be fitter to undermine the light, than he who in words cries it up,
and yet is departed from it, and secretly fights against it, and would bring forth,
propagate, and set up a hideous, monstrous,
comprehensive kind of knowledge (which is contrary to it,
and cannot consist with it in the name of it?

Ah! that this person, who now appears against the truth,
and the church and ministry which is in and of the truth,
were but what he pretends to be!
For then I should gladly have received his testimony,
and not have been thus necessitated to appear against his spirit,
and the dark work and testimonies thereof.
He saith, there are two Christs, both the true Christ and antichrist.
I confess his work comes from one of them, even antichrist,
who would destroy Christ`'s work, kingdom, and building,
and the ministry which he makes use of, both to plant, water, and build up;
but not from that Christ, who hath gathered a church to himself,
and is with the church which he hath gathered,
and blesseth the church which he hath gathered, and owneth them in their assemblings,
and in their ministering: which owning and testimony will stand; when the disowning,
and false testimonies of all these false, apostate spirits, will fall,
and end in their own sorrow and misery.

What I have here written, I have written in a holy constraint,
in the opening and feeling life of truth, with true love to souls; yea,
even of this very person, who is erred so exceedingly from the holy light and Spirit,
and its holy testimony, and would fain exalt his critical conceits and notions,
above the plain testimony and evidence of truth, in the hearts of God`'s chosen ones.

The Lord bring down the kingdom of darkness,
and exalt his own kingdom in the hearts of the children of men more and more;
and add to his church,
and keep them in that which will never suffer them to depart from it;
or to testify against the life and power and presence of the Lord, manifested, dwelling,
and ruling in it!
Amen.

=== REMARKS UPON SOME PASSAGES IN A LATE BOOK, ENTITLED "`Antichrist`'s Transformations Within,`" etc.

THE first thing that I shall observe is, That he doth deny that man hath any rule, power,
dominion, government, or authority, either given or committed to him from the Lord,
as pertaining to the conscience in things relating to the worship of God.

Remark.
God sent Christ into the world,
and he gave him power and authority in his name to do whatever he required of him.
And Christ sends his servants and ministers into the world, as sheep among wolves,
and he gives them power and authority to do whatever he requires of them,
and which he expects from them, and would have done by them.
And their work relates to the conscience, and to the worship of God;
and their power and authority extends, thither, where their work lies.
They are ambassadors of Christ,
and they have power and authority in Christ`'s stead
to beseech men to be reconciled to God.
For as Christ came in his Father`'s name,
to fulfill the work which the Father gave him to do, so they come in Christ`'s name,
to fulfill the work which he gives them to do.
They have power to feed the flock; they have power to watch over them;
they have power to build up in that which is good;
and they have power and authority to testify against and hammer down that which is evil;
they have power to reprove;
they have power and authority to visit with a spirit of meekness,
and power to come with God`'s rod, yea, with his sword,
and to smite that with it which riseth up against the truth, against the life,
against the Spirit, against the holy way and work of the Lord,
and holy order and government of this truth and Spirit,

That Christ hath sent forth his servants, his ministers, his ambassadors,
about things relating to the conscience, is so manifest that it cannot be denied.
But that he hath sent them forth with power and authority
in things pertaining to the conscience,
relating to the worship of God, that this man denies;
but all that have received the truth, hold the truth, and keep the truth,
cannot but acknowledge it.

Now, the reason he gives why he denies "`man any rule, power, dominion, government,
or authority, either given or committed to him from the Lord,
as pertaining to the conscience in things relating to the worship of God,
is because it belongeth to Christ, the light,
the invisible power which dwells in men and women,`" etc.

Remark.
All power in heaven and earth was given to Christ, and belongs to him;
that is freely granted.
But the question is, whether he hath not given of this power to his children,
and his servants and ministers, as his Father gave of it unto him.
Doth not he give power to as many as believe in his name to become sons of God?
Did not he make his apostles able ministers of the new covenant,
in the Spirit and power which he gave them?
"`All power is given me in heaven and in earth,`" said Christ. Matt. 28:18.
"`Go ye therefore and teach all nations,`" etc.;
ver. 19. but wait at Jerusalem for the power first. Acts 1:4.
So when the power came upon them, it led them forth in their work,
and they had power to gather, and power to build up,
and power to govern and watch over the flock of God,
over which the Holy Ghost had made them overseers. Acts 20:28.
And Paul speaks of the power the Lord had given him to use sharpness,
even against those in that church of Corinth,
who would not be subject to him in that which he had received from the Lord. 2 Cor. 13:10.
But this power was to edification, but not to destruction.
For though he had power from Christ the Lord, and did, by that Spirit, and in that power,
deliver Hymeneus and Alexander unto Satan;
yet it was not that they should be destroyed by the devil, but that,
by feeling themselves out of the truth, and under the dominion of a wrong spirit,
they might come to true sense and understanding, and learn not to blaspheme the truth,
nor the dignities whom God hath made honorable in the truth. 1 Tim. 1:20.
And not the apostle only, but the church of Corinth,
had a share in the same power; and therefore the apostle,
knowing what was given and committed to them, exhorts them,
that in the name of our Lord Jesus Christ, when they were gathered together,
and his Spirit, with the power of our Lord Jesus Christ, to deliver such a one to Satan:
but this was not for destruction, to destroy the soul;
but to bring it back into a state of edification and salvation, which now,
by departing from the truth, it was gone from.
It was indeed for the destruction of the flesh, but not of the spirit;
but that the spirit might be saved in the day of the Lord Jesus. 1 Cor. 5:4-5.

Secondly, The next thing I shall observe is this:--he saith,
"`There is no glory to be given to man, although he be born of the light.`"

Remark.
That glory and honor is to be given to man, which God gives to man, who hath said,
"`Them that honor me, I will honor;
and they that despise me shall be lightly esteemed.`" 1 Sam.
2:30. He that brings his deeds to the light,
they being justified and approved there, he hath honor in the light.
His deeds being made manifest that they are wrought in God, that is honor enough for him. John 3:21.
The children of light seek for glory
and honor and immortality and eternal life;
and that glory and honor they have, and eternal life from God. Rom. 2:7.
They seek not the honor that is from men,
but the honor that cometh from God only, John 5:44. the honor in the truth,
in the life, in the power,
which God gives them in the hearts of all that are truly sensible and living.
For honoring the Lord and his truth,
how can I but honor those that are honorable in his eye,
and who are glorious in his truth!
For indeed, the children of light, the tender, the humble,
the contrite and brokenhearted ones, are glorious in his eye,
and the Lord doth exalt them in due time; for after the true humility,
and in the true humility, they come to partake of the true honor. 1 Pet. 5:5-6.
And so every true Jew, every true servant, every faithful steward,
every true minister, that is faithful in the use of his gift and talent,
hath praise of God; Rom. 2:29. and they that are of God honor those whom God honors,
glorifying the Lord for them, and honoring them in the Lord. 2 Cor. 8:18.
Oh, how could this man say, there is no glory to be given to man,
though he be born of the light,
whenas "`the king`'s daughter is all glorious within,`" and man in
that birth is nothing but glorious in the eye of the Lord!
Man, having sinned, fell short of the glory of God; but coming out of sin,
cometh into the glory again,
and is daily more and more changed into the glorious image of the Son,
from glory to glory, etc. 2 Cor. 3:18.
The aim of God is to bring many sons to glory; Heb. 2:10.
and as they come out of darkness and sin into light and holiness,
they come into the glory, and are in the glory.
Is it not their glory in the Lord and in his light,
to be owned and acknowledged by them that are one with them in the same light?
They who love God, and honor God, cannot but love them, and honor them,
who are begotten by him,
and who are in an especial manner made use of by him in his service,
for the good of souls, and for the preservation and building up of the church.
The apostle speaks of double honor to be given to the elders that rule well,
especially they who labor in the Word and doctrine,
and would (from the Spirit of God) have them counted worthy of it. 1 Tim. 5:17.
How far is this man from the apostle`'s mind,
who would have no glory given to any man, no, not to the children of light,
nor ministers in the light, who, in the apostles`' days,
were the glory of Christ! 2 Cor. 8:23. Yea, the just that live by faith in Christ,
and are gathered by him out of Satan`'s kingdom into his spiritual kingdom,
and walk in the light, as God is in the light, there light doth shine in them,
and they do shine as the sun in the firmament;
and they that are honored by the Lord to turn many to righteousness, do shine as stars:
and though one star differs from another in glory,
yet all that come into the true nature and heavenly image
of the Son do come into a measure of the true glory,
and have some of the glory given them which God gave to Christ; and in that are glorious,
partaking of his Spirit, kingdom, power, and holy dominion over sin and Satan,
all which is truly glorious. John 17:22.

Thirdly, The third thing I shall observe is this: he saith,
"`All is to be given to Christ, the light in man, unto whom alone it doth belong,
who is the true Minister,
and hath power in himself to teach all the sons and daughters of men,`" etc.

Remark.
That Christ is the true Minister, that is not denied; but doth not Christ,
who is the true Minister in the power of the endless life,
send forth disciples and ambassadors in the same power, and make them,
through his Spirit and power, able ministers of the New Testament?
And they that hear them, do they not hear Christ?
And they that despise or deny them, do they not despise or deny Christ?
And doth not Christ say to the seventy disciples, "`He that heareth you, heareth me;
and he that despiseth you, despiseth me; and he that despiseth me,
despiseth him that sent me`"? Luke 10:16. It is
antichrist that so vainly pretends to set up Christ,
or his light, or Spirit, or power, as to deny those that are sent of him,
and minister in his name.
As man is in the fall, he is corrupt, and his works are out of God,
and he is there to be denied, ceased from, and not accounted of; but in the restoration,
in union and fellowship with the Lord, he is a worker together with God,
and is there to be owned,
and hath a share in ministering out of the heavenly treasure that dwells in him.
So Christ was the great Minister, who had the fulness;
and they that have gifts from him for the work of the ministry,
and who minister in and from the gift, and in that are able and faithful,
are esteemed and accounted as ministers by him.
So saith the apostle, "`As every man hath received the gift,
even so minister the same one to another, as good stewards of the manifold grace of God.
If any man speak, let him speak as the oracles of God; if any man minister,
let him do it as of the ability which God giveth;
that God in all things may be glorified through Jesus Christ,
to whom be praise and dominion forever and ever.
Amen.`" 1 Pet. 4:10-11. And Paul saith,
he was made a minister of the gospel according to
the gift of the grace of God given unto him,
by the effectual working of his power. Eph. 3:7.
Now, the gift is given,
not to those that are wise after the flesh (unless that wisdom be first broken);
but to such as are mean, poor, weak, low,
or some way or other contemptible in the eye of man`'s wisdom,
and easy to be disregarded and despised by men.
Yet it is hard to despise the man whom God sends, without despising his gift in him;
and the gift cannot be despised or rejected,
without despising or rejecting him that gave it;
as the apostle told the church of the Thessalonians, he that despised or rejected,
despised or rejected not man,
but God (who gives his Holy Spirit to them whom he sends forth to minister in his name). 1 Thess. 4:8.
He had been beseeching and exhorting
the brethren by the Lord Jesus Christ,
that as they had received of them how they ought to walk, and to please God,
so they would abound more and more.
"`For ye know,`" said he, "`what commandments we gave you by the Lord Jesus Christ.`" Mark:
the apostle did not only turn them to the Word of life and power in themselves;
but did give them commandments from the Word of life in him,
and they received of them whom Christ sent forth, how they ought to walk,
etc. ver. 1-2. And life hath not lost any of its authority;
but the power may teach and command others through any vessel when it pleaseth;
and they that are the true sheep, know the voice of the true Shepherd,
speaking either in their own hearts, or through any other instrument unto them.
And the voice of wisdom in any,
is in every age still heard and justified of her children;
and he that is of God heareth his voice, in those whom he sends in this age,
as well as in former ages; and he that is not of God heareth not his voice;
and hereby the Spirit of truth and spirit of error is known in this,
as well as in former ages. 1 John 4:6.

Fourthly,
The fourth passage I shall take notice of is in these words:`"Wherefore,`" said he,
"`whosoever doth exalt Christ the light, who is the true Minister, before themselves,
by Christ the light within shall those be exalted.`"

Remark.
This is very different from what went before:
for before he denied all glory and exaltation at all to man,
although he be born of the light; here he speaks of exalting Christ, the true minister,
before themselves; which doubtless every true minister, and every child of light,
cannot but do; and herein he confesseth they shall be exalted by Christ the light.
Then glory is given to them; and he that sees them thus exalted by the light,
cannot but esteem them, as so honored and exalted by Christ,
and give them that glory which Christ hath given them.
And happy would it be with this man, could he see the true church,
which God hath brought out of the wilderness,
and beautified and gloriously built up to a great height;
and the elders and ministers whom he preserveth, and is with,
and makes use of in his service,
and give them in his heart the honor and glory which God hath glorified them with.
But that he cannot do, till he come out of Babylon,
and out of that dark and confused spirit wherein he wrote these things,
into that light and holy Spirit of truth,
which discovers what they are (to those that are in the truth),
and condemns the ground and root out of which they sprang.

Fifthly, The next thing to be observed by me is this:--He layeth it down as his judgment,
faith, and belief, that whatever is written to the churches,
ought to be written from God`'s infallible Spirit, and the Word of eternal life;
wherein I am one with him: for what good can any thing do the living,
but what comes from life, and from God`'s infallible Spirit,
which alone is able rightly to exhort, advise, admonish, warn,
and build up the spiritual?
But his inference thereupon is that which is before me to take notice of.
"`Wherefore,`" saith he, "`your paper to the churches is not to be owned by the churches,
inasmuch as it was written from a sight, or a sense, and from the sensible part,
and not in and from the Spirit of revelation.`"

Remark.
God hath, in his holy church and living people, opened the eye that was once blind,
and daily anointeth that eye, giving a true sight,
and in the springings of life giveth a true sense;
and that which giveth this is the Spirit of revelation;
and what is written in this sight and sense, is written from the Spirit of revelation.
And the called people of the Lord wait upon the Lord,
that they may be kept in this sight, sense, and Spirit, in what they do at all times;
but more especially when they consider of things relating to the churches,
even to the welfare, holy order, and peace thereof,
that God`'s Spirit may have its scope everywhere,
and nothing else have place in the churches of Christ.
And though every one be not an eye and ear-witness of what
is to be considered of for the good of the churches;
yet every one waits to feel things in the opening and springing life,
and in that to speak, consider, or write.
I have often seen the carriage of things after this manner, to the joy of my heart,
and causing of my soul livingly to bless the Lord for it; and therefore may I, yea,
ought I, now thus to speak this testimony, which the Lord hath livingly given me,
being at this time required of me.
Oh that men knew the seriousness and solemnity of our spirits before the Lord,
in our considering things relating to his church,
and how we retire out of man`'s wisdom (affectionate part, and comprehending part,
as he speaks) to feel the springing life, and God`'s holy guidance there;
and how the Lord doth satisfy and bless us with it!
So that we can say, in truth and uprightness of heart,
not we (as men) of ourselves do things on truth`'s account;
but he on whose shoulders God hath laid the government rules and reigns among us;
and things are ordered by his counsel and wisdom to his praise.
And the peace and comfort of God`'s Spirit remains with us,
in the midst of all the reproaches and oppositions we meet with from that evil spirit,
which envieth and opposeth us many ways.
This one word more is with me, as to this particular: God hath given believers,
his church, senses exercised to discern both good and evil;
and those senses are not without the true life and Spirit,
and every motion and action of them is in that life, and in that Spirit.

And whereas he further saith:--"`Whatsoever is written, declared, or given forth,
in the sight, or in the sense, or from the sensible part, it is not to be owned;
for the sensible part is that which hath been in the transgression with the woman,`" etc.

Remark.
Herein he is greatly mistaken: for Friends in truth do not speak, or write, or admonish,
or reprove, or give warning from that part;
but from the sight and sense which God gives to his own birth;
and it is the Spirit of God that gives both the sight and sense, and speaks through them;
and those whose ears are circumcised and opened know the voice, and give glory to God,
and are obedient to his Spirit, when it gives advice and warning through any;
which those that are in the comprehending part, and consider and judge in that,
cannot have the sense of.

Sixthly, He saith, "`Antichrist will bring a veil over the understanding of men and women,
and yet they, for the present, cannot perceive it.`"

Remark.
This is very true.
I would he and others, who are veiled by antichrist, did see it;
for then he would not esteem those veiled whom the Lord hath unveiled,
nor attribute these sayings of his, and this his book, to the light within,
which those whom the Lord hath unveiled, and keepeth unveiled,
in his pure Spirit and quickening life, know to have come from the darkness within,
and not from the true light; but the true eye, in the truly living sees through it,
and hath no union with it; but returns it back thither, from whence it came.
Oh, how deeply doth antichrist blind and deceive men; that that which is their own state,
they cannot see to be so! but apply it to others, whose state it is not,
and so justify themselves in that wherein God condemns them,
and condemn others in that wherein God justifieth them.
This is sad work and will have a sad issue.

Seventhly, He saith, "`There is an invisible woman in every visible man,
and there is an invisible man in every visible woman; and the man Christ Jesus,
who is the light of the world, he is in them both,`" etc.

Remark.
Is not he now in the notional and comprehending part,
muddling himself and others (whose ears are open to him) about a woman in a man,
and a man in a woman, and Christ in both?
Whereas truth is a plain thing; which they that come to feel and abide in,
feel and witness redemption, and preservation out of the comprehending part,
and the dead, notional knowledge thereof.

Eighthly, He saith, He doth not own the judgment and opinion of those ministers,
nor yet their superiority, who say,
he that is not justified by the witness of God in Friends, is condemned by it in himself.

Remark.
I shall not now argue that there are true ministers,
and that there is a true superiority (some being greater
and some less in the covenant and life of truth),
which every one that heareth and learneth of the Father, and so is taught of God,
will own: but to the thing itself.
The witness of God is but one in all, and it condemns nothing but what is not of God;
and what his witness in another condemns in me,
his witness in me (whenever it ariseth and speaketh
in me concerning that thing) cannot but condemn also.

It is true, as he saith, that "`justification is by Christ alone,
who is the head in every member,`" etc.

Remark.
But Christ is in other members also, as well as in one;
and his life hath power to judge and condemn; and it judgeth and condemneth nowhere,
but that which is to be judged and condemned.
So that wherever Christ`'s life in any judgeth and condemneth any thing,
that is judged and condemned by Christ.
And the saints have power and authority in Christ,
not only to judge and condemn the world,
but also to judge and condemn fallen angels and spirits.
To what end are they bid to try the spirit, if after they have tried them,
they may not judge and condemn what they find life and truth judging and condemning?

Ninthly, He excepts against that passage in Friends`' paper (as he recites it),
"`that none are to minister, but those that are reconciled to the church,
and have the approbation of the elders.`"

Remark.
What is the end of ministering, but to gather out of the world into the church,
or to build up the church?
And are they fit to do either, who are not reconciled to the church?
Or whom the Spirit, life, and power in the church and elders hath not unity with?

He further saith, "`That God was in Christ, reconciling the world unto himself,
and not to the church`" (saith he); he remembers no such scripture.

Remark.
God added to the church such as should be saved;
and were they not reconciled to it before they were added?
And Christ said concerning that brother that would not hear the church,
that he should be looked upon as a heathen or a publican;
and are such as will not be reconciled to the church, nor hear it,
allowed by God to minister, either to gather into the church, or to build up in it?
Ah! surely it cannot be.
There can be no true ministering out of the life and Spirit of the body,
or church that is in God.
And all such as have thus gone out from God in whom the church is,
have ministered against the life, Spirit, and power, but not in it;
but in antichrist`'s spirit and power, and against the truth.

Tenthly, He saith, "`Christ, the light within,
will not give his power and authority out of his own hand to any man or men;
for unto him alone is all judgment in heaven and in earth committed in matters of conscience.`"

Remark.
Is Christ`'s power given out of his hands,
when his life and Spirit in one judgeth concerning
that which is evil and out of the truth in another?
Doth not the spiritual man judge all things?
Doth not Christ teach and enable him so to do?
Is there not such a gift of his to discern spirits?
Cannot the ear that is circumcised, and kept open by the Lord, try speeches and actions,
and discern when they are out of the life, and when in the life?
And doth he give the power and authority out of his own hands, in enabling them so to do?
What dark expressions are these, and dead too; not so much as literally true?

Eleventhly, He saith, "`Christ, the light within, is able to break,
and he is also able to bind up that which he hath broken,
and to heal that which he hath wounded,`" etc.

Remark.
And hath not Christ put a spiritual rod and sword into the hands of his church and ministry,
with which to smite and wound, as his Spirit guides and leads them?
Have they not power both to bind and loose as Christ saith?
And is not this a wounding and healing virtue and power?
After Christ had said, "`Tell the church; but if he neglect to hear the church,
let him be unto thee as a heathen man or a publican;`" doth he not immediately add,
"`Verily I say unto you, whatsoever ye shall bind on earth, shall be bound in heaven:
and whatsoever ye shall loose on earth,
shall be loosed in heaven`"? Matt. 18:17-18. Is not this
power and authority necessary to the true church?
What! a church, and not have power over her own members;
but every one left to the dictates of what they shall call the light within,
and not be subject to the judgment of the true light, Spirit, and power of Christ,
the head in the living body?
What a church was this?
A mere Babel, and heap of confusion, a body that would never be at unity in itself.
But God is the God of the order of his own Spirit, life, and power;
and not of such confusion.
This doctrine may go for truth in Babylon, but can never be owned in God`'s Jerusalem,
where his Spirit did build up, and defends the buildings,
and judgeth out all such sandy and windy doctrines, which are loose and airy,
and have not a ground or bottom in the truth.

Twelfthly, He saith, "`There is fallibility attends all those, who are regenerated,
and born of the Spirit of God, who is light,
and that it is possible for them to err from the light again,`" etc.

Remark.
He doth herein lay the state of the truly regenerate
and born of God lower than the scripture lays it.
The scripture saith, "`Whosoever is born of God, doth not commit sin;
for his seed remaineth in him, and he cannot sin,
because he is born of God.`" 1 John 3:9. And again,
"`We know that whosoever is born of God sinneth not;
but he that is begotten of God keepeth himself,
and that wicked one toucheth him not,`" chap.
5:18.

There is a gathering into the seed, and an abiding in the seed;
and there the soul is in the strong tower, and munition of rocks,
where the enemy cannot reach.
Adam in the fall was in a fallible state.
Is the renewed, the redeemed state, as fallible?
What state is that wherein truth is so natural, and the soul so one with it,
that it can do nothing against the truth, but for the truth, as Paul speaks?
What state is that, wherein men overcoming, shall become pillars in the house of God,
and shall go no more out? Rev. 3:12.
But let men be ever so fallible,
the infallible Spirit and power is given to the church of God,
to guide them in true understanding and judgment,
especially in all things that relate to and concern them as a body;
and they that are of the truth, and in the truth, love the judgment of Christ, the head,
in her; but they that are of another spirit, and would have liberty out of the truth,
to the transforming nature and spirit, cannot abide it.
What were my life in me, if it did not judge in me?
And what were the church`'s life, if it did not judge in her,
and condemn all that riseth up from a contrary spirit and nature?
What means that promise, Isa. 54:17.
"`No weapon that is formed against thee shall prosper,
and every tongue that riseth against thee in judgment, shalt thou condemn`"?

Yet he confesseth, "`That God is infallible,
and that no fallibility attends him;`" but denies "`the very
regenerate and born of the Spirit to be infallible;
and that it is possible for them to err from the light again; the enemy,
which is the power of darkness,
presenting to them the fruit of the tree of knowledge,`" etc.

Remark.
If God be infallible, as he confesseth (though it is to be questioned,
whether from any true knowledge of his nature, or only from the comprehension),
and God beget children, into what doth he beget them?
Whether into a fallible nature and spirit, or into his own nature and Spirit,
the least degree whereof is infallible?
When men are truly turned to God, there are great and precious promises made to them,
which, through faith, obedience, and diligence, they come to enjoy,
whereby they are made "`partakers of the divine nature.`" 2 Pet. 1:4. And when
they partake of the "`divine nature,`" do they partake of a nature that is fallible,
or infallible?
"`He that is joined to the Lord is one Spirit.`" 1 Cor. 6:17.
And is that one Spirit a fallible,
or infallible spirit?
There is one baptism, wherewith the truly living are baptized;
and doth that baptism wash away that which is fallible, or no?
The church of Christ, the body of Christ, the spouse of Christ,
the chaste virgin that is married to Christ, is one with Christ;
is it one with him in fallibility, or in infallibility?
Bear with me, for I am constrained to speak these things for truth`'s sake,
for the church`'s sake; yea, for Christ`'s sake,
and for the sakes of them who cry up the light within in words,
and yet are deceived about it, and know it not; but are erred from it,
and have set up the darkness of antichrist in their minds, instead of it,
which with them goes for the true light; and in this they judge that which is true,
as if it were false, and justify that which is false, as if it were true,
both in themselves and others; both which are an abomination to the Lord.

He saith, "`There is a fallibility attends all those that are regenerate,
and born of the Spirit of God.`"

Remark.
What all?
Those that come to the highest pitch, and greatest growth, can they not pass fallibility,
and arrive at infallibility in a measure, and abide in it?
To be regenerated and born of God is a high state;
it is not for every notionist and comprehender to be talking what is experienced there.
There is a regenerating, and a being regenerated.
There is a following Christ in the regeneration,
and there is a conformity to him in his death, and in his life too.
It is not good for him to be speaking much concerning that state,
but rather to wait to be led into it, and to arrive at it in the true travel.
But how he that is regenerated is one with Christ
(and is in measure as he is) is hard to be known,
and harder to be uttered.
But he that is in this state hath witnessed the holy calling,
and faithfulness to him that called, and the election, and is one of the chosen,
or elect of God; and Christ saith, such are beyond fallibility;
for speaking of false Christs, he saith, "`If it were possible,
they should deceive the very elect,`" Matt. 24:24.
plainly signifying that it is impossible.

Now, their possibility of erring he lays upon the enemy`'s presenting
to them the fruit of the tree of knowledge whilst they are in Eden,
p. 6.

Remark.
The enemy`'s presenting temptations doth not imply a possibility of letting in the temptation,
and so of erring, in all to whom he doth present things.
For he presented things to Christ,
and yet it was impossible for that Spirit and nature that Christ was of,
to let in his temptations.

But then, immediately in the next words he showeth,
How this possibility of falling is upon the enemy`'s
presenting to them the fruit of the tree of knowledge;
namely thus, "`Their minds taking delight in it, and they feeding upon it,
the enemy hath power to draw their minds out of Eden again.`"

Remark.
The regenerate and born of God are partakers of the divine nature,
and wait on God for living food, and receive it of him, and live by it,
and cannot abide dead, dry, notional food, nor feed upon it.
Blessed be the Lord, there is that birth known, which can feed on nothing but life itself.
And let the power of darkness present the fruit of the dead tree ever so often,
the living babe will not meddle with it, but hungers and thirsts after righteousness,
and desires the sincere milk of the pure, living word, that it may grow thereby.
And if this holy nature be put into the babe,
how much stronger is it in those that are grown in truth,
and who come to be naturalized into it, the contrary nature being crucified,
and slain in them by the cross of Christ, and the new and holy nature ruling in them?

Thirteenthly, He saith,
"`Wherefore I do believe that I ought not to subject myself to what the church imposeth.`"

Remark.
The church of God under the law, walking in that outward covenant,
was a glorious camp or body; and had outward power, according to the outward law,
appertaining to it.
And the church of God under the gospel,
walking with God according to the covenant of the gospel, is a glorious, spiritual body,
and hath inward power belonging to it; and though not the church merely as men,
yet that Spirit and power in the church, ought to be obeyed by every member thereof,
in things pertaining to God.
So it was in the apostles`' days;
they that were not disorderly and unruly were obedient to the Spirit
and power of God in the apostles and churches then, 2 Cor. 7:15.
and chap.
2:9. who had power to judge those that were within. 1 Cor. 5:12.
And those that are indeed of God will be obedient
and subject to his Spirit and power in his church now.
And there is nothing else desired, but obedience to the Lord, as he moves, guides, leads,
and orders, both in the particular and in the general.

His reasons why he doth not believe that he ought
to subject himself to what the church imposeth,
are these:--"`For then,`" saith he, "`I must believe that it is God in them,
which doth impose those yokes of bondage upon their brethren.`"

Remark.
The church is called into the liberty of the gospel,
and her children are born of the word immortal, and of the truth which makes free;
and it is not the church`'s nature, either to receive or impose yokes of bondage,
but to stand fast, and to exhort all her members to stand fast,
in the liberty wherewith Christ hath made them free.
But where there is any thing unruly, or contrary to the power,
that is to be yoked down by the power.

And the particular waiting upon God in his Holy Spirit, light, and power; the Spirit,
light, and power will discover what is disorderly, and unruly,
and not of God in the particular, and lay a yoke upon it.
The church also waiting upon God in their meetings together in his name,
the Lord will discover what is hurtful to the body, and contrary to the life of the body,
and lay yokes upon it;
and he that refuseth this yoke keeps alive that which is impure and fleshly,
and keeps down the just in himself.

But, indeed, he that doth not believe God in his church, and that his Spirit, life,
and power sits as king there; he is not in a capacity to obey aright,
because he doth not discern nor acknowledge that in the church,
which alone is to be obeyed.

Another reason he gives is,
Because (he saith) he must also then believe that the church is infallible,
and cannot err.

Remark.
The Spirit of God is infallible;
the power whereby the church was gathered and built up is infallible.
Christ is infallible, and hath given to his church of his infallible Spirit;
without which they cannot be preserved, or act aright?
and is the church in God fallible?
And this Spirit will not fail them in their waiting upon him;
and the church which is one with Christ, married to Christ, joined to Christ,
partaketh of his holy, living, and infallible nature.

Judge in the truth how it would suit: a holy head, an unholy body; a living head,
a dead body; an infallible head, an elect and chosen head,
but a body very liable to be deceived and err.
Hath not the church that Spirit, that life, that power, of the Lord Jesus Christ,
her head, with her, that is able to keep her from erring?
And is it not her earnest travail and desire to keep to it herself,
and to have all her members kept to it?
And will not that power keep and preserve all that keep to it?

He addeth further to the foregoing words, "`Which thing I cannot believe,
for then I must believe these particulars following.`"

First, "`I must believe that they are as infallible as God is;
and that it is as impossible for them to err, as it is for God to err.`"

[.discourse-part]
Answer.
No. A man may believe that God hath given to his
church a glorious proportion of his Spirit,
to dwell in them, and guide them, as his sons, spouse and wife;
and that they are married to him that is infallible,
and partake of a blessed proportion of his nature;
and yet not believe that they are as infallible as God is.
The Lord is absolutely infallible of himself; what infallibility the church hath,
is by gift, by union, and communion with the Lord, her Husband and Maker.

But doth he believe, or will he go about to maintain,
that the church hath nothing of the infallible Spirit of her husband?
Or that she is to act in a fallible spirit?
Or that she is to act nothing at all?
But only direct men to the light and Spirit within, and let her members alone,
though she infallibly (by the infallible Spirit and
power) know that they are deceived and err,
and see (with the anointed eye) that they are going from, and acting contrary to,
the light in their own particulars?
If she should do so, she would show little care over her children,
and small regard or faithfulness to him,
who hath entrusted her with his own Spirit and power, for edification and salvation,
and not for destruction.

Secondly,
"`That no man or woman shall ever attain to any higher
measure of the grace of God than they;
and that they are come to the highest revelation
that can be attainable by the Spirit of God.`"

[.discourse-part]
Answer.
The highest measure of life and of the Spirit is
not necessary for the government of the church;
but a true measure.
And a true measure the Lord hath ordained for his church; and Christ, the Head,
is not absent from his church; but present with it,
to supply with what wisdom and power he seeth needful.
And where is the attainment and growth in grace?
Is it in the church, or out of the church?
Doth not the Lord add to the church such as shall be saved?
And is not their growth there?
And if any member be blessed, and grow ever so abundantly in grace,
it is the growth of the church, and the church is glad of it.
Now, if it be a true growth, they would have unity with the church,
and mind the peace of the church,
and be subject to the Spirit and pure power of life in the church;
else their growth is in another spirit, which the true church can never own.

Thirdly, "`And that there is no more to be made known by the Spirit of God,
in the sons and daughters of men, but what already is made known to them.`"

[.discourse-part]
Answer.
The particular`'s owning a measure of life, of truth, of the Spirit and power,
doth not argue there is no more to be made known or revealed in the particular.
And the church`'s owning a fuller measure dwelling in the body than
in any one particular (for the greatest fulness in any particular
doth but go to make up the largeness or fulness in the body),
doth not argue that the church shall not grow, or be enlarged and filled as it grows.
But if he intend the growth of any departing from the church,
or out of the Spirit of life of the church, who hath her life from the Head,
and is in unity with the Head, that growth we cannot but deny,
finding it by constant trial and experience to be a growth in notion and comprehension,
out of the feeling life and power.

Now, this kind of growth I do not desire ever to know;
the Lord also preserve others out of it, and open their ears to hear the voice of Christ,
and of his church, that they may be preserved out of it!
For had this been hearkened and kept to, things had been better with many,
as to their inward state, and true peace with the Lord, than they have been.

Fourthly, "`Or if there be any thing more to be revealed by the Spirit of God,
that God will make it known to them, and to none else.`"

[.discourse-part]
Answer.
The true church doth not limit God where he shall reveal, or not reveal;
but owneth God in whatever it reveals in any man upon the face of the earth.
For being in unity with God`'s Spirit, and born of the immortal life,
they are in the feeling sense and knowledge of what came from the life in ages past,
or in this present age, and are in unity with it;
yet they know the Lord revealeth the mystery of his truth and kingdom in the churches,
and the growth is in the churches.

Now, if any, in Lucifer`'s nature,
will hearken to that spirit which despiseth God`'s church, and rend from it,
and think to grow above it,
and expect this growth in their high notions and comprehensions about things,
in that exalted mind, should be owned by the church, they will be mistaken:
for the true Spirit, which knows all things, and guides the church,
will not guide the church to own any such spirit or growth;
but to judge and condemn it in its greatest spreading and exaltation.

There were those in the apostle`'s days who would seem to be grown high,
and to be spiritual, far above the apostles, and such as lay low in the truth,
and obeyed the holy commandments, and yet were far short of their life,
as may be seen abundantly in his epistles to the church of Corinth.
But what saith the apostle concerning such?
"`If any man think himself a prophet, or spiritual,
let him acknowledge the things that I write unto you are the commandments of the Lord.`" 1 Cor. 14:37.
And did not he give commandments about those that were unruly,
and would not be subject to the order, power,
and government of God`'s Spirit in the church?
And did not the apostle say of unruly persons, and vain talkers and deceivers,
that their mouths must be stopped? Tit. 1:10-11.
What! had the church or ministers,
in the first promulgation of the gospel, power to stop mouths?
Yea; in the Spirit that was in them, and with them,
they knew which were the vain talkers, the unruly, and deceivers;
and what mouths were to be stopped, and what power would stop them.

Fifthly, he saith, "`Friends,
I would have you seriously take into your consideration some of your doctrines
and principles which are commonly preached among us,
how they can stand with God`'s sovereignty, dominion, and glory,
that either the seed or God should arise in man.`"

Remark.
Christ preached a seed, even the kingdom, like a grain of mustard seed,
and this seed sown in man.
Now, if it was sown in man, in his earthly heart, nature, and spirit,
then the earth was over it, and did cover it,
and it was to spring up or arise over and above the earth, and the pure power, wisdom,
and glory of the Father to appear to be manifested in it.

Is this such a strange doctrine to him?
Where are his spiritual senses?
How was he convinced?
Was it without the feeling of the seed?
If he truly felt it, where did he feel it?
Did he not feel it in the earth?
Was there not much over it?

I am sure, we who were truly convinced, felt it so; felt the pure seed under suffering,
the pure life under, the pure measure of truth under, and much of the earth over it,
the Lamb slain inwardly by sin and transgression; and blessed be the Lord,
we felt also the earth judged, and removed out of its place; the earth plowed up,
and the seed springing over all that is earthly,
and growing up in that which God made new, over that which was old.

And did not God arise outwardly, in the manifestation of his power outwardly,
among the outward Jews?
And doth not he arise inwardly, in the manifestation of his power inwardly,
among the inward Jews?
Are the enemies ever scattered inwardly till God`'s arising inwardly?
What kind of convincement or growth hath that man been acquainted with,
who never experienced these things?

Now, having proposed this, he asketh some questions, which,
as the Lord shall open my heart, I may return answers to; not after a notional way,
but as the Lord hath given me that knowledge, feeling, and experience of the thing.

His first question is, "`Whether the Light or Spirit, Seed, and God,
be not all one and the same thing?`"

[.discourse-part]
Answer.
God is the fulness, the seed is a measure and manifestation of him, the infinite fulness.
And as he is light and Spirit, so the seed that comes from him,
or that the good husbandman sows, is light and Spirit also.

His second question is, "`How came this seed of God to be under, or beneath, in man?`"

[.discourse-part]
Answer.
Any man that knows the truth in the holy experience, and hath been tempted,
and let in sin upon him, may know what comes then under, and how it comes under.
The Spirit by sin is grieved; yea, the Holy Spirit may be quenched,
and man may crucify to himself the Lord of glory.

His third and fourth questions are, "`What shall raise it up?`" And, "`By what?`"

Answer to both.
The power of God, the Spirit of God, the life of God, entering into its own in man,
entering into the witness, raiseth it up, brings that under which resisted, oppressed,
and kept it down.
The power of the Almighty, by his out-stretched arm, crusheth Pharaoh inwardly,
and brings his spiritual seed out of spiritual Egypt, Sodom, and Babylon;
in all which the Lord, in all ages,
hath inwardly and spiritually been crucified by them that have
resisted his Holy Spirit in the pure manifestations thereof;
for what is done to it is done to him.
"`Saul, Saul, why persecutest thou me?`"

Lastly, "`Whether the appearance of God in man, to man by his Spirit,
be not for the quickening and raising of man, both soul and body,
out of a state of bondage and captivity?`"

[.discourse-part]
Answer.
Yes, it is; but how doth God raise up man?
Is it not by joining him to his seed, and causing him to bow to his seed,
and suffer with his seed, and deny that which is contrary to his seed; so that the seed,
which hath been grieved and burdened with sin and iniquity, may rise up over it,
and crush the head of the serpent, in the authority, power,
and dominion of the Father`'s life?
Who of the redeemed ones, that have witnessed true redemption,
have not witnessed God bringing that up which was down, low, deep in the heart,
and bringing that down which was high and exalted over it?

But for the raising of God, that is but his misrepresentation of this sound doctrine,
and holy experience: for Christ himself, who was God, and the resurrection and the life;
yet the Godhead was not raised in him,
but the resurrection and the life raised that body.
And that of him which he soweth in us, and which differeth in the soul,
through the soul`'s sin, he raiseth up in his own holy dominion,
in them that come to suffer with it,
and to bear the cross with that which crucifieth sin.

This is sound doctrine, and sound experience,
universally experienced by all that know the inward truth, and have subjected to it.
They have felt what truth was, and where it was; and what it is, and where it is;
and what they are in it, and by it; blessings and praises over all unto him, who,
by the working of his most glorious power,
hath brought this about in a remnant whom the Lord hath visited and shown mercy to.

Let him wait for true understanding from him who is able to give it,
and answer me this one question then, Doth not the devil, the enemy of mankind,
hunt after the precious life,
even in those that come to witness redemption in measure from him?
And if, at any time, they hearken to his temptations, and let him in,
doth not the life receive a wound?
Is not the Spirit grieved?
Is not the tender, righteous, living plant hurt?

Oh, the tender mercy of God to permit his truth, his seed, his Son,
not only to suffer for man without the gates of Jerusalem, but also to suffer in man,
even in the streets of Sodom, where our Lord was, in ages past, crucified,
and is spiritually crucified to this day! Rev. 11:8.

He saith, "`The kingdom of heaven is within all men and women, and heaven is above hell,
and the light is above darkness,`" p. 7.

Remark.
If he mean that their nature is so, I grant it; but if he mean that heaven,
or the light which is heavenly,
is uppermost in men who are under the kingdom and power of darkness,
he is utterly mistaken; for in the kingdom where Satan and antichrist reign,
antichrist is there exalted (in that heart) above all that is called God;
even above the light, Spirit, and power which ought to be worshipped and obeyed there,
but is not; and there is need of the arm and power of God to be awakened,
and to put on strength there, to cut Rahab, wound the dragon, and bring him under,
and to bring up the seed into its heavenly authority, dominion,
and power (which is due unto it) in that heart.

He saith, "`The seed is to redeem, and not to be redeemed.`"

Remark.
This is true, relating to the seed, as it is in itself:
but as God hath bestowed it on man, given it as a gift in man,
and it condescends to his condition, descending into the lower parts of the earth,
and suffering with man, that it might bring man into its death and sufferings,
and so raise him in and with itself; so the mighty power of life, from whence it came,
is to be revealed in it, and bring it out of Egypt,
and the darkness wherein it finds man, and in the tender love of God to man,
bears a share with him.
It is not only the Jew outwardly that pierced Christ,
but the soul inwardly by transgression pierceth his life and Spirit;
and as it comes to true sense and faith, looks upon him whom it hath pierced by sin,
and mourns bitterly over him, and turns from and hates that sin whereby it pierced him.

He saith, "`The seed in both man and woman is both God and Christ,
and is above the seed of the serpent in all, and he is in himself,`" etc. p. 7.

Remark.
Who denies that God and Christ, and the holy seed, which are one in nature,
though not in measure and fulness, as he is in himself, is above the seed of the serpent?

He addeth further, "`Neither hath man`'s mind been so blinded,
that he could not see his sins by the light,`" p, 8 l. 38 (as corrected by the errata).

Remark.
There is an eye that the god of this world blinds,
that it may not see the glorious shinings of the light. 2 Cor. 4:3-4.
And the eye that is blind cannot see, till God opens it.
The outward eye cannot see the shining of the outward sun, but as it is opened;
nor can the inward eye see inward things, but as the Lord opens it.
Paul was sent to the Gentiles to open their eyes, and to turn them from darkness to light. Acts 26:18.
So that man`'s eye is blinded, that though the light shine in the darkness,
yet he cannot see, nor walk in the way of the light,
but as God anoints and opens his eye; "`anoint thine eyes with eye-salve,
that thou mayest see.`" Rev. 3:18.

But I beseech him, in the tender bowels of love, to consider where his standing is,
and what it is in him, that brings forth these things;
for I am sure it is not the true light,
wherewith God hath shined in the hearts of his people, and doth shine at this day.
He mistakes the true light in others, and calls it darkness;
and also mistakes the darkness in himself, and calls it light: and whither,
after this rate, may he wander in his uncertain notions and comprehensions?
and while he is thus talking of God, and heaven, and the light within,
let him take heed lest he be found among them who blaspheme God, and his tabernacle,
and them that dwell in heaven.

What I have hitherto took notice of, may sufficiently manifest, even to himself,
could he retire low enough, where the true understanding and knowledge is given,
how he hath erred from the true light, and but pretended to it; and not been led by it,
in what he hath now writ.

As for the other part of his book, though I could say much to it,
if the Lord did require me; yet finding it chiefly to be matter of notion and criticism,
my heart is not engaged to meddle with it; for it is not in me,
to bring people into such critical disputes, about an invisible man, or invisible woman,
or who was the first invisible man, which one while he seems to call God or Christ;
another while the son of perdition, or power of darkness,
he calls the first invisible man, as page 21. for which I am satisfied,
he can produce no scripture; which he requires of Friends, for what they assert.

I must confess, I see no profit in his meddling with such things,
but rather a drawing the minds of the people into forbidden knowledge,
and airy comprehension about the heavenly things,
and feeding that part in themselves which should not thus be suffered to fly aloft,
but be kept under.

And happy were it for him, if he could feel the truth, seed,
and life (which is grieved in him), rise above them, trample them down,
and reign over them: but he must experience great humility, and a long travel,
before he can come to witness this.

As for his denying himself to be of us;
indeed he hath sufficiently manifested by this book,
and by his strange notions and comprehensions therein, that he is not of us;
but a stranger to that life, spirit, and power, which hath gathered, guideth,
and preserveth us out of such paths as these.

And oh that he did not hug so many notions (and those very strange ones too,
contrary to the truth and holy experience, in the hearts of God`'s redeemed ones,
and the Holy Scriptures, as hath been already showed),
and get such comprehensions into his brain, concerning the saving power;
but wait to descend, and come down thither, where he may feel it in his heart,
and that will preserve him for the future from such contradictions and confusions,
which the other part of his book is also too full of; which, if the Lord please,
he may draw forth some other to lay open,
for the vindication of truth and its true testimony, from his spirit and false testimony,
uttered in very strange and extravagant expressions;
not at all suitable to the nature of truth,
but rather to the nature of that dark spirit from whence it came;
which the Lord of his tender mercy manifest to him, and redeem him from, into a tender,
living, humble sense of the meek and lowly principle of life in the heart.

=== POSTSCRIPT

SINCE the writing of the former, and my not intending to meddle with the rest,
there hath something lain upon me, as to some few passages therein also,
to write a few words by way of testimony, to one or two particulars therein:
but that which mainly lay upon me was somewhat in relation to his Postscript;
he looking upon it as so unanswerable,
and yet so plain and clear an answer arising to it in my heart.

First, As to his main controversy with Friends,
about the "`Christ that died at Jerusalem`" (he affirming,
"`That neither justification nor condemnation is by him;`" and reproaching Friends,
"`as having gone back to the professors`' Christ and Saviour,
who died without the gates of Jerusalem,`" as page 17, 21, 26),
this is in my heart to say: --

Remark.
Is Christ divided?
Is there one Christ that died without the gates of Jerusalem,
and another that did not die?
Or is it not the same Lord Jesus Christ, who died without the gates of Jerusalem,
according to the flesh, and yet was then alive in the Spirit?
Do we affirm that the Godhead died?
(No, we do not so much as affirm, that his soul died, as he doth,
page 19.) But according to the flesh he died; that is,
he who was the resurrection and the life laid down his life, and took it up again,
according to the commandment of his Father.

Thus we have been taught of God to believe, and thus to hold it forth.
And we have no other justifier, condemner, Saviour,
or intercessor than he that laid down the life of the body,
offering it up a sacrifice to his Father, without the gates of Jerusalem.
"`Who is he that justifieth?`" Is it not God, in and through him?
And, "`Who is he that condemneth?
Is it not Christ that died?`" And where did he die?
Was it not without the gates of Jerusalem?
"`Yea rather, that is risen again,`" etc. Rom. 8:33-34.

Secondly, The next thing that lies upon me to take notice of, is writing against sense,
and disowning the exhortation to come to a sense, and to wait in a sense,
and abide in a sense, etc. as p. 25.

Remark.
Though I have given a touch at this already, in the foregoing part,
yet there is somewhat more lies upon me.
The inward man, the new man, the spiritual man, hath inward and spiritual senses.
Christ`'s sheep have spiritual ears to hear his voice with;
and a spiritual eye is given to the spiritual man, to see him who otherwise is invisible.

There is also a spiritual taste to savor and distinguish between that which is living,
and that which is dead; between that which is corrupt and unwholesome,
and that which is wholesome food: and by the exercise of these senses,
the children of God become more and more skilful in discerning between good and evil. Heb. 5:14.
And in this living sense, the elect cry unto God against their enemies,
and are heard and preserved by him, and shall, in due time, be fully delivered. Luke 18:7-8.

The truly living are truly sensible.
Indeed, if he could take away the sense of life,
and the judgment of life from God`'s people,
it were an easy matter to deceive them with such kind of notions
and comprehensions as he hath brought forth in his book.
But the Lord hath given a living sense or senses to his, and pure,
living judgment therein; which their minds being kept to,
it is impossible for this spirit, or any such like, with all its enchantments,
to prevail upon them, because the sheep`'s ear knows the sound and voice of life,
from the sound and voice of death,
let antichrist transform in any of his ministers ever so mysteriously.

He saith, "`God is not a sense, nor is his Spirit a sense.`"

Remark.
It is not for him, in his notional way, to say what God is; he that made the eye,
shall not he see?
He that made the ear, shall not he hear?
Doth he beget his children into a living sense, and bestow living senses upon them?
And hath not he the thing in himself much more?

But let me ask him this question; did God, the holy begetter of life,
ever beget him into a living sense?
If not, he was never of us; if the Lord did, let him wait to be begotten so again,
and he shall soon be one of us again, and judge in the true Spirit, life, and power,
what he hath here writ and published abroad in the wrong; and he shall no longer believe,
that this his writing was written from the testimony of Jesus in him (as he expresseth,
p. 21), but shall experience the life of Jesus condemning it in his own heart,
as I am sure it hath done and doth in mine,
and cannot but do in all that have been gathered to, and abide in,
that which keepeth livingly sensible.

Thirdly, The third thing, and that which most lies upon me,
is that charge of his upon Friends, That they do show more homage, reverence,
and obedience to the form outwardly, than to the power of God inwardly;
and that they worship the form beyond the power,
because they keep their hats on when they wait and worship in silence;
but in public prayer, both men and women either stand up, or else kneel down,
and the men all put off their hats: herein (he saith) they worship, reverence,
and adore the form outwardly; and the words, more than the word of life in their hearts, etc.
This practice he would have them vindicate, if they can:
indeed he hath sufficiently condemned it, and more than God hath allowed him to do,
or will justify him in.

Remark.
The thing is nakedly and plainly thus; the great God, by the arm of his power,
hath gathered a people to himself,
and taught them to worship him in his own Spirit and truth; yea,
he hath taught us to be continually retired, and upon our watch, and in his fear;
eying and regarding him in all we do.

Besides this, he hath appointed us solemn times of meeting together to worship him;
in which times we do, in a more solemn, and after a more especial manner,
retire to feel his presence with us, and holy Spirit and power working in our hearts,
and ministering to us.
And, blessed be the Lord, he is still found, according to his promise,
in the midst of us; and doth give us pure breathings after him, and pure sense of him,
and pure praises to him; even praises from and in that which is pure.

Yet, while we are sitting thus waiting, or when breathings or praises arise,
we are not taught or required of the Lord to pull off our hats, or kneel on our knees.

But when the Lord moveth and calleth any forth (for the assembly,
or in the name and on the behalf of the assembly) to offer prayer or praises to God;
then, to signify our unity in the Spirit, and our joint reverence to our God,
we are moved either to kneel, or stand, as the Lord shall incline our hearts,
and to uncover our heads before him.
And in this we do not adore the form, as our God knoweth and beareth witness,
but him who hath taught us the form, and who teacheth us to continue therein,
and justifeth us in the use and practice thereof.

And what spirit is this that condemneth us after this vaunting manner,
as if he had brought forth such a manifest evidence
of our adoring the form as could not be answered?

The last thing which lies on me to take notice of
is those words about the close of his postscript:
"`I have yet another book, that is written in and from the Spirit of God;
the tendency of which book is,
for the overthrowing of all antichrist`'s ministers in this nation,`" etc.

Remark.
This testimony lies on my heart concerning him, that he is not in a condition,
or capacity to write or speak in or from God`'s Spirit.
He may pretend to have written this, or to write another book, from God`'s Spirit,
but he doth but take the name of the Lord in vain in so doing,
and the Spirit of the Lord will, without doubt,
through some of those that are in him that is true, give a sure and certain sound,
and testimony, against his false pretences.

Oh that he could indeed think or write or speak against antichrist`'s ministers,
and against the spirit of antichrist! which if ever he be able from God to do,
he must first see how antichrist hath prevailed over him, and darkened him,
and how he dwelleth and reigneth in his heart, as if he were God; yea,
he must deny his present light and spirit, and call it no more Christ;
but feel that which is now little and low in him rise (through his sense of it,
and subjection to it) over that which is now so high,
and so exalted above the measure of truth in his own heart; which, if it were so,
or might once be so, how glad would my soul be for his sake,
which is now grieved to see him so lifted up, and so mistaken, and so deeply to err,
both concerning himself, and God`'s people, church, and ministers,
and concerning God`'s light and Spirit; denying, debasing, and casting down that,
to exalt himself; that so he might set up the wrong instead of the right,
and be justified and owned by the one, seeing he cannot by the other!

The Lord, if it be his will, in tender mercy to him, bring him down from his high seat,
and exalt that holy blood of the covenant, which is now trampled under foot by him,
that his soul may be saved,
and not perish forever (in the day that never shall
have end) from the presence of the Lord,
and from the glory of his power.
Amen.

