[#misrep-gov-cleared, short="Misrepresentations Concerning Church-government Cleared"]
== Some Misrepresentations of Me Concerning Church-government Cleared

[.heading-continuation-blurb]
And the power and authority of God`'s spirit in governing his church testified to.

[.heading-continuation-blurb]
By one whom it hath pleased the Lord to make a member of the Church,
which he hath gathered, and preserveth by his own Almighty Arm;
who accounteth it his duty and honor in the Lord,
to be subject to the government and ordering of his Spirit and Power in his Church.

[.section-author]
Isaac Penington

[quote.section-epigraph, , 1 Cor 16:16]
____
That ye submit yourselves unto such,
and to every one that helpeth with us, and laboreth.
____

[quote.section-epigraph, , Heb. 13:17]
____
Obey them that have the rule over you, and submit yourselves;
for they watch for your souls, as they that must give account,
that they may do it with joy, and not with grief;
for that is unprofitable for you.
____

[quote.section-epigraph, , 1 Pet. 5:5]
____
Likewise, ye younger, submit yourselves unto the elder;
yea, all of you be subject one to another, and be clothed with humility;
for God resisteth the proud, and giveth grace to the humble.
____

[quote.section-epigraph, , Eph. 5:18,21]
____
And be not drunk with wine, wherein is excess;
but be filled with the Spirit,
and submitting yourselves one to another in the fear of God.
____

=== Preface

Upon occasion of the suffering of our dear friends and brethren in New England,
cruel imprisonments, many hard usages, and at last (some of them) death itself,
for their obedience and faithful testimony to the Lord, and his precious truth;
and because of the undue covering thereof,
by the grounds and causes produced to justify their proceedings;
I was engaged to show the nakedness and unreasonableness thereof,
in a book entitled, "`An Examination of the Grounds and Causes,
which are said to induce the Court of Boston in New England,
to make that Order or Law of Banishment upon pain of death against the QUAKERS,`" etc.
Whereunto somewhat was added (being very proper to the subject in hand)
about the authority and government which Christ excluded out of his church,
which also occasioned somewhat concerning the true church-government.

Now, this latter part (about church-government) hath been so misrepresented, as if,
because the wrong church-government was excluded,
the exclusion of all church-government was intended by me,
there being no notice taken of my owning the true church-government,
but only some passages of my disowning the false produced,
as if they intended to overturn and deny all church-government,
which never was intended by me: for in that very book which is thus made use of,
I did positively affirm the necessity and use of the true church-government,
which may more fully appear in that which hereafter follows.

=== Some Misrepresentations of Me Concerning Church Government

[.heading-continuation-blurb]
Or the manifesting that I am misrepresented,
and the clearing of my innocency from those misrepresentations, this is on my heart: --

[.numbered-group]
====

[.numbered]
_First,_
to set down those words which John Pennyman hath cited out of that part of my book which
speaks of the authority and government which Christ excluded out of his church.

[.numbered]
_Secondly,_ To add somewhat, in way of confirmation of that truth and tender sense,
which was then upon my heart.

[.numbered]
_Thirdly,_ To propose some questions, as I shall find them arise in my heart,
further to open and manifest the intent of my heart in this thing.

[.numbered]
_Fourthly,_ To annex somewhat,
which is mentioned and immediately added in the very same part of the book,
concerning true church-government;
which plainly manifesteth that I was not against the true church-government,
nor did mention or intend any of those things to hinder, deny,
or oppose the true church-government, of which I do there infer an absolute necessity.

[.numbered]
_Fifthly,_ It is on my heart to add a few considerations further, concerning the necessity,
usefulness, and benefit of the true church-government.

====

The first words John Pennyman cites out of this part of my book,
concerning the authority and government which Christ excluded out of his church,
from Matt. 20:25 to 29 are these:

"`Here Christ cuts off that power and authority,
which grows up in the corrupt nature of man,
which was ever and anon springing up even in the disciples;
here he wholly excludes it out of his church, and saith expressly,
he would have no such thing amongst them, no such kind of greatness,
no such kind of authority.

[.discourse-part]
_Confirmation._
It is the full belief of my heart,
that Christ hath cut off that power and authority
which grows up in the corrupt nature of man,
and wholly excluded it out of his church,
even very expressly in this fore-cited scripture; plainly signifying therein,
that he would have no such kind of greatness,
no such kind of authority among his gathered and chosen people.

[.discourse-part]
Question.
But doth this signify or imply, that he would have no authority at all?
Doth this exclude the authority and government of his Spirit and power in his church?
Doth not he, notwithstanding this, say,
"`Go tell the church`"? And enjoin the members of the church to hear the church,
upon the penalty of being accounted heathens and publicans?
And did not the Holy Ghost make and appoint overseers over the church? Acts 20:28.
And what is an overseer?
or in what were they to oversee?
Were they not to oversee in the true light,
to which every child of light is to be subject?
And they that did resist the light, Spirit,
and power of the Holy Ghost in any of the overseers, were they not unruly,
and departers from the light in themselves;
though they might pretend they were still for the light,
and that it was the overseers that were departed and erred from it?

[.inline]
==== The next Words he cites are these:

"`Two things are here excluded by Christ,
from whence all the mischief ariseth in the church,
all the tyranny and oppression of men`'s consciences, and of their persons, estates,
and liberties for conscience`' sake.
First, Greatness: Secondly,
The exercising dominion and authority by those that would be great therein.`"

[.discourse-part]
_Confirmation._
It is my belief, that all the mischief in the church,--tyranny,
and oppression of men`'s consciences, and of their persons, estates,
and liberties for conscience`' sake,--doth arise from a wrong greatness,
and from the exercising of a wrong dominion and authority,
by those that would be great therein;
and that these two things are here excluded by Christ, in the fore-mentioned scripture.

[.discourse-part]
Question.
But is there not a true greatness?
Those that lie low before the Lord,
and have humbled themselves under his mighty hand,--doth
not the Lord exalt them in due time,
filling them with his Spirit, life, virtue, and power?
And is not that great in them?
And are they not highly favored, and exalted in the eye of the Lord therein?
(Oh! none knows how great those are in the eye of the Lord, who are poor and low,
and nothing in their own eyes.) And is there not a true authority
and dominion of God`'s Spirit in the church in general,
as well as in the particular, over the spirit and power of darkness?
Because of which Spirit, because of which power,
because of which holy authority and dominion,
the gates of hell shall not be able to prevail against it.

[.inline]
==== His next citation is this (which, though somewhat long, I am willing to recite punctually, that my innocency may the more appear):

"`This spirit must be kept out from amongst you,--this aspiring spirit, this lofty,
ruling spirit, which loves to be great, which loves to have dominion,
which would exalt itself because of the gifts it hath received,
and would bring others into subjection;
this spirit must be subdued amongst Christ`'s disciples, or it will ruin all.
The Lord gives grace and knowledge for another end,
than for men to take upon them to be great, and rule over others because of it.
And he, that because of this thinks himself fit to rule over other men`'s consciences,
and to make them bow to what he knows,
or takes to be truth,--he loseth his own life thereby;
and so far as he prevails upon others, he doth but destroy their life too.
Therefore the disciples, or church of Christ, are to watch over every such spirit,
to beat it down, to testify against it, to turn from it, to lay it flat,
to put it in its proper place, that is, beneath all, and so not to suffer it to arise.`"

Before I come to the confirmation of this,
I judge it meet to set down the foregoing clause or paragraph omitted by him,
which will very much help to clear the naked drift and true intent of these words.
The foregoing paragraph runs thus:

"`Such a kind of greatness as is in the world is the destruction of the life of Christ;
and such a kind of dominion and authority as is among the
nations is a direct overturning of the kingdom of Christ.
It sets up another power than Christ`'s, another greatness than Christ`'s,
another kind of authority than Christ`'s;
and so eats out the virtue and life of his kingdom,
and makes it just like one of the kingdoms of this world.`"

This (which immediately went before) being thus added,
may sufficiently open the thing of itself.
Yet for further satisfaction,
I shall add a confirmation to the truth of that which he hath cited;
and that in several particulars, because of the length of the citation.

[.discourse-part]
_Confirmation._
_First,_ An aspiring spirit, a lofty, ruling spirit, which loves to be great,
which loves to have dominion, which would exalt itself,
etc. must be kept out from among the disciples and church of Christ.
There must not be such a spirit, or loving to be great, or such a ruling among them,
as is in the world.
No; life alone, the Spirit alone, the humble seed alone, the truth alone,
the grace alone, must rule among them;
and God forbid the authority and government thereof should be stopped in any.
It cannot be well with the church that it should be so,
that God`'s Spirit should be grieved or quenched or stopped in its
holy way of governing and ordering the church of its own building.

[.numbered-group]
====

[.numbered]
_Second,_ That which would exalt itself because of the gifts it hath received,
and would bring others into subjection;
this spirit must be subdued among Christ`'s disciples, or it will ruin all.
God alone, Christ alone, the Spirit alone, the truth alone, the seed alone,
is to be exalted in the church; not flesh, not self, not the aspiring, lofty,
ruling spirit.

[.numbered]
_Third,_ The Lord gives grace and knowledge for another end,
than for men to take upon them to be great, and rule over others because of it.
Man, without grace and true knowledge, is high and exalted,
and would be ruling over and subjecting others;
but true grace and knowledge brings man down, and keeps him low,
even out of every desire of aspiring and ruling over others,
in earnest breathings and endeavors that both the grace
and spirit may teach and rule both over himself and others.

[.numbered]
_Fourth,_ Because God hath given a man knowledge,
he must not take upon him to rule over others with his knowledge.
Christ did not rule over his disciples with his knowledge,
nor require them to believe what he knew to be truth.
Nor may any man at this day, though ever so full of God`'s holy Spirit and power,
take upon him (above what his Lord and Master did) to rule over other men`'s consciences.
If he do, he will do it out of the leadings of life, and of God`'s holy Spirit;
and so will wound and hurt his own life thereby;
and so far as herein he prevails on others, he will hurt their life too.

[.numbered]
_Fifth,_ Therefore this spirit (which Christ never was of himself,
nor encouraged in his disciples) the church is to watch over, beat down, testify against,
turn from, lay flat, and keep beneath all, and so not suffer it to arise.

====

[.discourse-part]
Question.
But doth all this hinder, deny, or oppose Christ`'s Spirit, Christ`'s power,
Christ`'s truth and grace from arising in the church,
in a way of spiritual and holy government?
Because man is not to aspire, nor take upon him to reign or rule, because of grace,
gifts, or knowledge received; shall not therefore the head govern the body?
Shall not life, and truth, and the wisdom of God, spring in the church,
to order and govern the church?
But must every man be left to the dictates of what he calls light in him,
and not to be reproved or testified against,
though the Spirit of God manifest it (to them that are indeed in the light, life, Spirit,
and power) that it is not light, as persons may pretend and imagine; but real darkness,
gross darkness, darkness that may be felt, even by the least babes that are in the true,
living sense?

[.inline]
==== The next Citation

"`If this rule of Christ had been kept to, antichrist`'s power could never have got up,
nor the poor innocent lambs so often have been worried by the wolves.`"

[.discourse-part]
_Confirmation._
It is most certainly true, if the wrong authority and government had been kept down;
if the aspiring, lofty spirit, which exalts itself,
and loves to have the preeminence over that which
it should be subject to both in itself and others,
had been judged, beat down, denied, turned from, etc.,
how could the spirit of antichrist,
which is the spirit that would be exalting itself above all that is indeed of God,
have got up?
This is the wolf that worries the lambs;
and if this power and spirit be kept out of the church,
how can there be any wolf found there, to worry the innocent lambs and sheep of Christ?

[.discourse-part]
Question.
But did ever antichrist`'s power get up by the exercise
of the power of Christ in his church?
Doth not that power turn against antichrist, and keep out antichrist?
Did that power ever worry the lambs?
Nay, rather doth it not cherish, feed, build up, and preserve the lambs?
And is it possible but antichrist`'s power should get up, unless this power be watched to,
and observed, in its ordering and governing the church,
and discovering the subtle working of the wolfish spirit of antichrist;
which appears in the sheep`'s clothing, and may pretend to the light within,
that it might draw men from that which is indeed the light within,
into that which is indeed darkness in the sight of the Lord,
and in the sight of all that are kept truly living and sensible by him?

[.inline]
==== The next Citation

"`The great work of the minister of Christ, is to keep the conscience open to Christ,
and to preserve men from receiving any truths as from them,
further than the Spirit opens, or to imitate any of their practices,
further than the Spirit leads, guides, and persuades them;
for persons are exceeding prone to receive things as truths,
from those they have a high opinion of, and to imitate their practices,
and so hurt their own growth, and endanger their souls.`"

[.discourse-part]
Confirm.
When the minister of Christ comes with the gospel of Christ, he finds men in darkness,
with their consciences defiled, with the door of the heart shut against Christ.
Now, his great work is to turn them to the light, Spirit, and power,
whereby their hearts may be opened, their consciences washed,
and there may be a ready entrance for Christ`'s Spirit and power into them.
Then the conscience being opened to Christ, their great endeavor, labor,
and work is to keep it open, and that that may not be let in again by them,
which will shut it against Christ.
For as there is one Spirit opens to Christ, so there is another will shut,
even after the heart and conscience is opened, if a man hearken to it.

And the way of receiving truth,
is in the evidence and demonstration of God`'s Spirit in one`'s own particular;
and this is forever the aim and care of the ministers of Christ to keep men to,
and not to allure men to receive truth as from them, but from Christ;
or to imitate any of their practices, further than the Spirit leads, guides,
and persuades them.
For the ministers of Christ are sensible how exceeding
prone persons are to receive things as truths,
from those they have a high opinion of; and to imitate their practices,
and so hurt their own growth, and endanger their souls.
Now, it lies on my heart to testify, upon this occasion,
that I have found the ministers of Christ, whom I have conversed with in this age,
walk so towards me and others, still turning me to that light, Spirit,
and truth in my own particular,
wherein the knowledge of truth was to be given me by the Lord,
and not imposing upon me that which they knew to be truth,
before the Lord had prepared and fitted my heart for the knowledge thereof.
And this is still the course and practice of the ministers of Christ to this day.

[.discourse-part]
Question.
But must not the minister of Christ, who is ordained of God to watch for the soul,
watch against that,
which (if hearkened to by any particular) will shut the conscience against Christ,
and open it to another spirit, who is often working in a mystery to deceive it?
And if they see the working of this other spirit in any, ought they not,
in faithfulness to Christ, and the souls of such, to warn them of it!
And if any, having let in the wrong spirit,
turn from and deny the practices which the Lord once
taught them (and wherein the testimony of truth stands),
into practices which are of the world, and answer the world`'s spirit,
and tend to weaken the faithful testimonies of others in the true light and Spirit;
ought the minister of Christ to leave these persons to their openness to a wrong spirit,
and wrong practices, wherein they deny the Lord that bought them and enlightened them,
and are shut up against the visitations and testimonies
of God`'s true Spirit and power in his children,
who keep their habitations in that light which these are departed from,
though they make ever so great pretences to it?

[.inline]
==== The next Citation

"`Ah, poor hearts! how simply do they come thither, where they once tasted refreshment,
to find wholesome advice, not suspecting what is got up there since;
and so give dominion to a wrong thing, and take directions from a wrong spirit,
and betray their own simplicity?
Therefore the main thing is to keep the conscience pure to the Lord,
and not to take things for truths because others see them to be truths,
but to wait till the Spirit makes them manifest to me; nor to run into worships, duties,
performances, or practices, because others are led thither,
but to wait till the Spirit lead me thither.
He that makes haste to be rich (even in religion, running into knowledge,
and into worships and performances before he feel
a true and clear evidence) shall not be innocent,
nor the Lord will not hold him guiltless,
when he comes to visit for spiritual adultery and idolatry.`"

[.discourse-part]
_Confirmation._
This hath been experienced in this our day, more than once; when some,
having departed from the power whereby the innocent lambs
had tasted sweet nourishment and refreshment through them,
and have come afterwards for that which is wholesome,
not suspecting what was got up in them since, and so gave dominion to a wrong thing,
and took directions from a wrong spirit, and betrayed their own simplicity.

[.discourse-part]
Question.
But had these resorted to the church, and waited for judgment from the church,
to whom God has given eyes to see,
in such cases as may pass the eye-sight of the particular, and a mouth to speak;
might not the church have been instrumental to have opened the true eye in them also,
and so have preserved them from being ensnared,
by any that ran out from the truth in their own particulars,
and lost their habitation therein?
And mark; when the church was in its great glory, clothed with the sun,
and the moon under its feet, and crowned with a crown of twelve stars, yet the dragon,
even then, might prevail upon some stars,
and with his tail sweep them down from their place;
but the church he could not prevail upon.
The gates of hell, the power of the dragon, the mouth of the dragon, nay,
the tail of the dragon (which what if I should say is the false prophet within) cannot.

[.discourse-part]
_Further Confirm._
Indeed, the main thing is to keep the conscience pure to the Lord.
To bring men to that which purifies the conscience, and to keep them to it,
this is the great work.
Men must not take things for truths,
because others see them to be truths (that is not God`'s way,
nor did his ministers ever so teach),
but to wait till God`'s Spirit makes them manifest to the particular.
Nor must men run into worships, duties, performances, or practices,
because others are led thither,
but wait till the Spirit lead every one in his own particular thither.

[.discourse-part]
Question.
Where is the faithful minister that teacheth otherwise,
or practiseth otherwise at this day?
I am sure I never met with any thing of this nature from any of them,
but only one that ran out in his own particular,
who first endeavored to draw me from esteeming or taking directions from others,
and then would have given me directions himself,
and would speak and undertake to prophesy great things of me,
that he might have raised up that part in me, which could have answered him.
And though he himself be dead, yet his spirit is alive in others at this day,
which the Lord discover and preserve his people from!

[.discourse-part]
_Further Confirm._
It is not good to make haste to be rich (no not in religion).
He that rightly believeth, and abideth in the true and living faith,
makes not haste to run into knowledge, worships, and performances,
before he feel his guide; but rather chooseth to be as a weaned child,
lying low before the Lord, in brokenness of spirit,
and not meddling with things too high for him; and so he is kept in innocency, poverty,
and humility before the Lord,
and preserved out of the bed of the stranger (the strange spirit and power),
and so not judged or condemned by the Lord, for either spiritual adultery or idolatry.

[.discourse-part]
Question.
But he that lets in a wrong spirit, that mistakes about the light in him,
and judgeth that which is indeed darkness to be it, and errs from the true church,
and denies the authority of God`'s Spirit and power in it, and is not preserved thereby,
but entangled and bewitched with this wrong spirit,
and in it testifies against the true church and true Spirit,
and the ministry and ministers of Christ;
is not he joined to the spirit of whoredom in his own particular?
And hath not he set up an idol in his own heart, instead of the true light there?
And doth not he worship and obey that idol, that wrong spirit, that wrong power?
And will not the Lord visit and judge him for his
spiritual adultery and idolatry from the true?

[.inline]
==== The next Citation

"`In the apostles`' days,
Christians were too apt to strive after a wrong unity
and uniformity in outward practices and observations,
and to judge one another unrighteously in these things.
And mark;
it is not the different practice from one another that breaks the peace and unity,
but the judging one another because of differing practices.
He that keeps not a day may unite in the same Spirit, in the same life, in the same love,
with him that keeps a day;
and he who keeps a day may unite in heart and soul with
the same Spirit and life in him who keeps not a day;
but he that judgeth the other because of either of these errs from the Spirit,
from the love, from the life, and so breaks the bond of unity.
And he that draws another to any practice,
before the life in his own particular lead him,
doth as much as in him lies to destroy the soul of that person.
This was the apostle`'s rule, for every one to perform singly to the Lord what he did,
and not for one to meddle with the light or conscience of another, etc.;
but every one to keep close to their own measure, etc.;
and here is the true unity in the Spirit, in the inward life,
and not in an outward uniformity; that was not necessary in the apostles`' days,
nor is it necessary now;
and that eye which so dotes upon it overlooks the one thing which is necessary.`"

[.discourse-part]
_Confirmation._
This is so manifest from that scripture quoted by me, which is here omitted,
that he that shall read that scripture, which is Rom. 14.
may easily observe the apostle affirming and teaching these things.

That even in the apostles`' days,
Christians were too apt to strive after a wrong unity
and uniformity in outward practices and observations,
and to judge one another unrighteously in these things,
is manifest from the several instructions and exhortations given to this church,
in this chap.
as ver. 2,3,4. "`One believeth that he may eat all things;
another who is weak eateth herbs.
Let not him that eateth, despise him that eateth not; and let not him that eateth not,
judge him that eateth; for God hath received him.
Who art thou that judgest another man`'s servant?
To his own master he standeth or falleth; yea, he shall be holden up,
for God is able to make him stand.`"

Yea, in matters of worship (as keeping and observing a day to God, or not keeping it),
it is not the different practice from one another that breaks the peace,
but the judging of one another, because of differing practices.
So the apostle plainly holds forth, ver. 5-6. "`One man esteemeth one day above another;
another esteemeth every day.
Let every man be fully persuaded in his own mind.
He that regardeth the day, regardeth it unto the Lord; and he that regardeth not the day,
to the Lord he doth not regard it.
He that eateth, eateth to the Lord, for he giveth God thanks; and he that eateth not,
to the Lord he eateth not, and giveth God thanks.`"

And he that draws another to any practice,
before the life in his own particular lead him,
doth as much as in him lies to destroy the soul of that person.
So the apostle signifies, ver. 15. (which was quoted in my book) in that he saith,
"`Destroy not him with thy meat,`" for whom Christ died.
So that not an outward uniformity in all things, but a unity in the one Spirit and life,
is the necessary thing.
And there may be unity, and love, and life, and peace, without a uniformity in practice,
further than the Spirit of God teacheth and leadeth his unto.

[.discourse-part]
Question.
But if the Lord hath taught a man, opened the same eye in him that he opened in others,
and brought him into unity and uniformity with the church,
in the practices which the Lord hath taught it; and he afterwards let in another spirit,
and fall from these practices, and judge the very church itself for continuing in them;
may not the church testify to this person, that he is erred from his guide,
hath lost the right judge in himself, and so judgeth amiss, both concerning himself,
and concerning the church of God?
This hath been the state of some who went out from among us formerly,
and may also be the state of some who go out from us now.
For as there is one that gathers to the true church;
so there is another that endeavors to draw and scatter from it,
and then to cause men to turn head against it, as if it were not of God,
but apostatized from the Spirit and principle of truth,
which indeed is their own state and condition in God`'s sight; but not the church`'s,
which was gathered and is preserved by him, glory to the Lord,
over all the accusations of the accuser, through what mouth soever he utter them forth.

[.inline]
==== The next Citation

"`Oh! how sweet and pleasant is it to the truly spiritual eye,
to see several sorts of believers, several forms of Christians in the school of Christ,
every one learning their own lesson, performing their own peculiar service, and knowing,
owning, and loving one another in their several places,
and different performances to their Master, to whom they are to give an account,
and not to quarrel one with another about their different practices!
This is the true ground of love and unity,
not that such a man walks and does just as I do,
but because I feel the same Spirit of life in him, and that he walks in his rank,
in his own order, in his proper way and place of subjection to that.
And this is far more pleasing to me, than if he walked just in the track wherein I walk;
nay (so far as I am spiritual), I cannot so much as desire that he should do so,
until he be particularly led thereto, by the same Spirit that led me.`"

[.discourse-part]
_Confirmation._
The spiritual eye beholdeth things aright, beholdeth things in the Lord,
and tasteth sweetness in, and is pleased with, that which is spiritual.
If every one did eye the Lord, subject to the Lord,
answer the light and Spirit of the Lord in their own hearts,
though the forms in the school of Christ be higher or lower, the lessons different,
and the practices answerable, yet every one minding his own place and lesson,
and performing his own peculiar service, the spiritual eye would be delighted therewith.
And those that are of the true seed and birth do know, own,
and love one another in their several places, and different performances to their Master,
to whom they are to give an account;
and do not quarrel with one another about their different performances.
Oh, how sweetly is this practised and experienced among us at this day!

And unity in the life is the ground of true brotherly love and fellowship.
Not that another man walks just as I do; but though he be weaker or stronger,
yet he walks by the same principle of light, and is felt in the same Spirit of life,
which guideth both the weak and the strong, in their several ranks, order, proper way,
and place of subjection, to that one Spirit of life and truth,
which all are to be subject to.

Nay, he that is truly spiritual and strong in the light and Spirit of the Lord,
cannot desire that the weak should walk just as he does;
but only as they are strengthened, taught, and led thereunto,
by the same Spirit that strengthened, taught, and led him.

[.discourse-part]
Question.
This is true concerning every one that is in the faith, that is in the true light,
that is in the true Spirit; and keeps his rank, order, place, and subjection,
though in a weak and low degree;
but will this hold good concerning any that have erred from the faith,
have made shipwreck thereof,
and have turned from the true light and Spirit in themselves, and left their rank, order,
and testimony against the world, and are again become one with the world,
even in those very practices which the spirit of the world delights in,
and which the Spirit of the Lord hath testified and still testifeth against,
in all that are faithful, and keep to their first love and light?
Is the church to bear with these in their practices, or own such spirits,
or believe that they now walk according to the light which first convinced them?
Is not the Spirit of judgment with the church?
Hath not God given her discerning?
Hath she not power and authority from God to try spirits?
yea, and to judge false spirits, that have lost their habitation in the light,
though they may still pretend to dwell there;
can she not try those which say they are Jews and are not, but have lost the light,
Spirit, and power which circumciseth, and keepeth circumcised,
and are run back into the uncircumcised paths of the world again,
which came from and answer the uncircumcised spirit and nature,
both in themselves and others?

[.inline]
==== The next Citation

"`And he that knows what it is to receive any truths from the Spirit,
and to be led into any practices by the Spirit,
and how prone the fleshly part is to make haste, and how dangerous that haste is,
will not be forward to press his knowledge or practices upon others,
but rather wait patiently till the Lord fit them for the receiving thereof,
and fear lest they should receive and practise too soon,
even in that part which cannot serve the Lord.`"

[.discourse-part]
_Confirmation._
I will send the comforter, the Spirit of truth, saith Christ to his disciples,
and he shall lead you into all truth.
Now, the disciple of Christ is led into truth,
in the cross to that part wherein others may receive the notion of things; yea,
perhaps of truth itself.
And the disciple must also abide in the cross,
after that the Lord hath given him the true knowledge,
or he cannot be rightly led into the practice of what he knows.
So that the disciple comes very hardly, both by his knowledge,
and by his ability to practise what the Spirit of God teacheth him and requireth of him.
There is a fleshly part indeed, prone to make haste; but that haste is dangerous,
and that fleshly part, in all its hasty desires and motions,
is to be denied and kept down.
And he that is diligent in denying and keeping down that fleshly
part in himself (with the forwardness and hastiness thereof) cannot
easily be forward to press his knowledge and practices upon others;
but will be patiently waiting on the Lord,
for their kindly and seasonable understanding of the truth, and growth in it; and fear,
lest they should run before their guide, and be practising too soon,
even in that part which cannot serve the Lord;
for the Lord must be served and worshipped in his Spirit and truth;
and thither are all to be directed and brought,
and there is every mind to be said and kept, or it cannot worship and serve aright.

[.discourse-part]
Question.
But what if a man entertain a wrong spirit, and let go the truths he had received,
and turn from the practices which God`'s Spirit taught him,
into the spirit and practices of the world,
which God`'s Spirit hath testified and will forever testify against?
Is not the church to deny this spirit, and these practices,
and the person that hath hearkened to this spirit, and is found in these practices;
that he may turn from this spirit and practices, to the true Spirit,
and to the true testimony and practices which it once taught him,
and still teacheth all that hearken to its voice and holy motions,
and listen not to the voice and instigations of a stranger?

[.inline]
==== The next Citation

"`The great error of the state of the apostasy hath
been to set up an outward order and uniformity,
and to make men`'s consciences bend thereto, either by arguments of wisdom, or by force;
but the property of the true church-government is to leave
the conscience to its full liberty in the Lord,
to preserve it single and entire for the Lord to exercise,
and to seek unity in the light and in the Spirit,
walking sweetly and harmoniously together in the midst of differing practices.`"

[.discourse-part]
_Confirmation._
That there have been ages of apostasy from the true Spirit and power of the apostles,
is very manifest, both by the doctrines, discipline,
and cruel practices of those that would have themselves
accounted the true church and true believers and Christians.
And they that have set up an outward order and conformity,
and have used both arguments of wisdom, and also force,
to make men`'s consciences to bend thereto,--this is as manifest as the former.
Now, that this has been an error, and a great error, is very manifest also;
because it is contrary to the nature of conscience, which is to be led by God`'s Spirit,
not bent by man`'s wisdom and constraint,
and contrary to Christ`'s and his apostles`' doctrine and practice,
who would have every man fully persuaded of what he performs to God,
from whom he must receive the reward and approbation, or the dislike and punishment,
for his answering or disobeying the light which God sets up, or causeth to shine,
in his own conscience.

And the property of the true church-government,
and the practice and path of the true church in these our days
is to leave the conscience to its full liberty in the Lord;
to preserve it single and entire for the Lord,
and to seek unity in the light and in the Spirit,
walking sweetly and harmoniously together in the midst of differing practices.
Nay, it is not the desire of the church at this day,
that any should come up into the practice, or holy order of the gospel,
according to what the Lord hath taught others,
but only as the Lord teacheth and leadeth them.

[.discourse-part]
Question.
Concerning what conscience is this to be understood?
Is it to be understood of the tender and weak conscience;
or of the hard and seared conscience?
For the conscience which God once made tender may afterwards come to be seared and hardened.
And is the church of Christ, which is guided by the Spirit and wisdom of God,
taught and required by him so to act towards the hard and seared conscience,
as it is towards the tender and weak conscience?
Is the hard and seared conscience, which hath forsaken the true light, Spirit, and power,
and turned against the truth, and is in a wrong, stiff, wilful,
hardened liberty and subtlety, to be left to its liberty,
and to that spirit which draweth it out and hardeneth it in a wrong liberty?
Can there be any unity, in the light and in the Spirit,
had with those who are erred from the light and from the Spirit,
and are deceived in their own hearts concerning it, and do but only pretend to it?
Can they walk sweetly and harmoniously together in differing practices,
who differ also in the ground, and are not one in the foundation,
even in the true light and Spirit of the Lord?
Ought not the church to judge this spirit,
with its liberty and evil conscience (for that spirit
will make the consciences of all that let it in,
evil), as well as, to the utmost,
to cherish the liberty of the tender consciences in and to the Lord?
Read and consider these scriptures following, Tit. 1:15. 1 Tim. 1:19. and 4:2.

[.inline]
==== The next Citation

"`And this I can truly say concerning myself, I never found my spirit forward to draw any,
either to any thing I believed to be true,
or to any practice or way of worship I observed or walked in;
but desired that the power and leadings of life might go before them,
and I was afraid lest men should receive things from my hand,
and not from the Lord`'s.`" He hath written in the margin of the book he sent me, "`Oh,
what a tender spirit was here!`" intimating as if it were not so with me now.

[.discourse-part]
_Confirmation._
Blessed be the Lord, it was so with me formerly, and is so with me daily more and more;
for as I wait on the Lord in his truth, which makes tender; so upon this occasion,
being forced to it, I cannot but confess,
that I witness the Lord daily more and more uniting my spirit to him in his truth;
and as truth increaseth, so the tenderness which comes from it still increaseth in me,
and I do not (nay, I may say cannot,
the contrary is so written on my heart) so much as desire to drive
any to what practice or way of worship I believe to be true,
and am taught of God to observe; but this is the longing of my soul,
that the power and leadings of life may go before them;
and I daily behave myself as one that is afraid,
lest men should receive things from my hand, and not from the Lord`'s.

[.discourse-part]
Question.
Yet, where I find persons manifestly warp and turn aside from the truth,
and let in a wrong thing, and testify against the truth and way of the Lord,
and their hearts hardened by the subtlety of him who hath deceived them;
may I not singly and faithfully testify it to them, and breathe to the Lord for them,
that they may return to the true Spirit, and to the holy testimony and practices thereof,
and not condemn such, as departers from the light and truth, who abide in it,
nor justify themselves as abiding in it, when they are really departed from it?

[.inline]
==== His last citation of words of mine is out of another book, entitled, [.book-title]#An Answer to the Common Objection,# etc. p. 8. The words are these:

"`That power therefore in the church which spares the hypocrites
(who can easily comply with an outward conformity in worship,
without feeling an inward life and virtue),
but lights heavy on that which is tender and shy in matters of worship,
that is not the true church power, but at best but a counterfeit of the true.`"

[.discourse-part]
_Confirmation._
The power which Christ hath given his church is not to spare hypocrites,
who may easily comply with an outward uniformity in worship,
without feeling an inward life and virtue.
And such are not spared, but smote at, by the Spirit and power of God among us very often.
And oh that there were no hypocrites and formal spirits among us;
but that all that profess the truth were in the truth, and subject to it,
and did live the life of it!
Nor doth the true church power light heavy on that
which is tender and shy in matters of worship;
but the ministry of the true church is to the conscience, as in God`'s sight,
and is very tender of it, as before him,
to whom it is to give an account of the spiritual power it hath received from him,
and of the exercise of it.
That power therefore which spares the hypocrites,
and lights heavy on that which is tender and shy in matters of worship,
to be sure is not the true church power, but at best but a counterfeit of the true.

[.discourse-part]
Question.
But that power in the church which doth not spare hypocrites,
but is very gentle and tender to all tender consciences,
is not that the true church power?
And who is the hypocrite?
Is not he that pretendeth to the light, when he is departed from it, a hypocrite?
And he which setteth up that which he calls light in himself,
and denieth that which is indeed true light,
and which issueth forth from God`'s Holy Spirit in his church, is not he a hypocrite?
And hath not the church power to judge all his false pretences,
and to try his spirit by the true light and Spirit of the Lord Jesus,
which is still present with the true church?
If the Spirit of Christ be indeed present with his church,
surely it cannot but have power and authority to try, judge,
and condemn everything that is of a contrary spirit and nature,
in all false pretenders whatsoever; who by their pretences to the true light,
cannot shelter that which is indeed contrary to it from the holy
and righteous judgment of the Spirit and power of God in his church.

Thus I have gone over these several citations of John Pennyman`'s,
and punctually set them down as he had cited them,
and spoken more words to the confirmation of them, to manifest to others,
as I find it plainly with me before the Lord, that I am fully the same at this day,
in the sense and belief of my heart, as I was then; believing the same truth,
and as ready to hold it forth, if the Lord at any time shall call me unto it,
as I was then.
But I was not then against true church-government;
nor did intend this to encourage any man to shelter himself,
by a pretence to the light in himself, against true church-government;
assuredly knowing that the spirit of the prophets is subject to the prophets;
and that he that is truly subject to the light and Spirit of God in his own heart,
will be taught thereby to be subject to it also in others.
For the life, Spirit, and power of God doth not rise in vain in any;
and he that hath the true ear open, will hear its voice in whomsoever it speaks;
and he that doth not hear its voice, when it speaks through any to him,
doth not hear with the circumcised ear, nor understand with the circumcised heart.
So that John Pennyman, in citing these my words,
as if in so writing I was against the true church-government,
or for setting up the judgment of any particular
man (upon any pretence whatsoever) above the sense,
understanding, and judgment of the true church, doth me great wrong,
even before the Lord, who knoweth that it was otherwise with me in that day;
and he greatly wrongeth my words, which did not signify any such thing:
for in the very same book, and in some of the pages which he quotes,
there is expressed a sense of, and a testimony to, the true church-government,
which I am assured the Spirit of the Lord will give forth, and lead his into,
as the necessities and occasions of the church require.
For as the Lord is not wanting to the particular,
so will he not be wanting to the general: but he is faithful,
who hath promised to be with his church and people, who wait upon him,
and look up to him for the light and judgment of
his Spirit in things wherein he engageth them,
and which require their single discerning and judgment in.

To manifest, therefore, from this very book, what my belief was,
and how hearty I was to church-government,
and sensible of the necessity and usefulness of it,
I shall recite some passages out of it.

First, I shall mention the title of that part of my book,
which had John Pennyman expressed fully, as it is in the title page,
he had done me some right,
and manifested somewhat of my sense concerning true church-government.
The title, in the title page, is thus:
"`Whereunto somewhat is added about the authority
and government which Christ excluded out of his church,
which occasioneth somewhat concerning the true church-government.`"

This might have poised people`'s spirits in the reading of his Citations,
from judging me to direct men to the setting up of any thing
in their minds and consciences which they may call light,
in opposition to the light and Spirit of God in his church,
or to set up a private judgment in themselves,
above the light and judgment of God`'s Spirit in the church.
For as the church is to be tender of every member,
so every member is to be tender and regardful towards the church,
and of the power and authority which God hath given it.

[.inline]
==== The next Passage that is on me to mention, is p. 76

"`There is nothing to hurt in the mountain of God`'s holiness;
but there is a righteous sceptre, a sweet sceptre, a spiritual sceptre,
which reacheth the spirit in the power of life,
but toucheth not the outward man.`" To which I may add,
The power of the church is not to hurt the outward man; nay, nor the soul neither:
but is for the destruction of the flesh, that the soul may be saved.
And when the church hath testified against their practices, or denied their spirit,
it leaves them to the Lord; yet still praying to him that repentance may be given them,
and mercy shown them by him, whose mercy endures forever.`"

[.inline]
==== Another Passage in p. 77

"`Let the life in every one rise over it,`" (speaking of the proud,
aspiring spirit) "`and trample upon it: and afterwards,
that in thee may arise which is fit to teach, yea, and to rule in the Lord,`" etc.

P+++.+++ 78. The example of Christ is urged,
who did not exercise a wrong authority over his disciples,
though he was their Lord and Master, which signified both greatness above them,
and authority over them,
see line 15. "`Yet Christ took not upon him this kind of greatness,
nor did exercise this kind of authority; but he was a servant,`" etc., and did minister.

So that there was one kind of greatness and authority which Christ did not exercise,
and which his church also is not to meddle with:
but there was another kind of authority which he had, and which he,
who hath all power in heaven and earth, giveth to his church, to partake with him in,
and to act in his name.

But why should I mention any such small touches at the thing,
when it is directly spoken to in a Question propounded, and the Answer thereto, p. 79,
80, etc.? I shall therefore set down the Question, and part of the Answer thereto;
the whole being too long to be here inserted.

[.discourse-part]
Question.
"`But is there to be no greatness, no authority, among the disciples of Jesus,
or in the church of Christ?
Is every one to do what he will, to be subject to his own fancies and imaginations,
to the inventions of his own corrupt heart?
What a confused building will this be?
Surely this will not long remain a Zion, but soon become a Babylon,
even a heap of disorder and confusion.`"

[.discourse-part]
Answer.
There is to be no such kind of greatness, no such kind of authority;
yet there is both a greatness and authority suitable to the state of disciples;
suitable to that kind of kingdom whereof they are.
There are laws, there are governments, there are governors, there is a ruling,
and there is a subjection; but all in the Spirit,
all suitable to that which is to be governed; but no government of, or according to,
the flesh.
As Christ`'s kingdom is not of this world,
so the government of his church and people is not according to the world:
but as that which gathers is his Spirit, and that which is gathered is spiritual,
so that which is governed is the spirits of his people,
and they are to be governed by his Spirit, and spiritually,
and not after a fleshly manner.
Thus Christ himself, though he ministered to his disciples,
yet he also was their Lord and Master,
and in the Spirit and life of the Father ruled over them; and thus the apostles,
and other ministers of Christ, had likewise in the Spirit the care of the churches,
and authority in the Lord by his Spirit to govern the spirits of his people:
not to govern after a fleshly manner, by their own wills,
nor to prescribe to them in a lordly way, either what they should believe or practise;
but in the light and in the power of the Spirit,
to make their way into every one`'s conscience in the sight of God,
ministering to every one in the Spirit according to their capacity and growth,
and waiting patiently for God to convey the food and nourishment,
and to build their spirits up in the faith thereby.

The spirit of the prophets is subject to the prophets.
Here is the government; here is the law of rule and subjection in the life.
Every one feeling a measure of the Spirit in himself,
is thereby taught to own and subject to a greater measure of the same Spirit in another.
He that hath no measure of the Spirit of God, he is not of God, he is none of Christ`'s:
and he that hath received a measure of the Spirit,
in the same Spirit feels another`'s measure, and owneth it in its place and service,
and knoweth its moving, and cannot quench it, but giveth way to it with joy and delight.
When the Spirit moves in any one to speak,
the same Spirit moves in the other to be subject and give way:
and so every one keeping to his own measure in the Spirit, here can be no disorder,
but true subjection of every spirit: and where this is wanting,
it cannot be supplied by any outward rule or order set up in the church by common consent;
for that is fleshly, and lets in the flesh, and destroys the true order, rule,
and subjection.

And then to limit the government aright,
these two precious cautions or directions are added, p. 85.
which I am sure will answer the truth and witness of God in every conscience.

[.numbered-group]
====

[.numbered]
_First._
Care must be had that nothing govern in the church of Christ, but the Spirit of Christ.

[.numbered]
_Secondly,_ That the conscience be kept tender,
that nothing be received but according to the light in the conscience.

====

There is likewise an Objection answered about Uniformity, p. 87-88.
which not being very large,
and tending further to open the sense of my heart in this thing, I shall also here annex.

[.discourse-part]
Objection.
But is not uniformity lovely;
and doth not the apostle exhort Christians to be of one mind;
and were it not a sweet thing if we were all of one heart, and one way?

[.discourse-part]
Answer.
Yea, uniformity is very lovely, and to be desired and waited for,
as the Spirit of the Lord, which is one, leads and draws into one.
But for the fleshly part (the wise,
reasoning part of man) by fleshly ways and means
to strive to bring about a fleshly uniformity,
which ensnares and overbears the tender conscience, this is not lovely, nor spiritual,
nor Christian.
And the apostle who exhorts Christians to be of one mind,
yet doth not bid them force one another into one mind,
but walk together sweetly so far as they had attained;
and wherein they were otherwise minded,
God in his due time would reveal more to them, Phil. 3:15-16.
He that hath, to him shall be given.
And the intent and work of the ministry (with the several ministrations of it)
is to bring into the unity (Eph. 4:13) as persons are able to follow,
and not to force all men into one practice or way; that is the way to destroy the faith,
and the true unity,
and at best can introduce but a fleshly appearance of unity in
such a form of worship and godliness as eats out the power.
And for being of one heart, and one way, blessed be the Lord,
this is in measure known and witnessed.
The way is one; Christ, the truth of God; and he that is in the faith,
and in the obedience to that light which shines from
his Spirit into the heart of every believer,
hath a taste of the one heart and of the one way;
and knoweth that no variety of practices (which is
of God) can make a breach in the true unity.
This is the one way,
for every one to be subject to that light of Christ`'s
Spirit which he hath received from Christ;
and every one keeping here,
there is also one heart kept in the midst of all the variety and diversity of practices.
And the unity being thus kept, all will come into one outwardly also at length,
as the light grows in every one, and as every one grows into the light;
but this must be patiently waited for from the hand
of God (who hath the right way of effecting it,
and who alone can do it), and not harshly and cruelly attempted by the rough hand of man.

Now, I desire all that would not injure and wrong another
(in taking part of one`'s sense and mind,
and concealing the other) to observe how serious my heart
is in the sight of the Lord concerning church-government,
and unity and uniformity among the people of the Lord,
in the Spirit and power of the Lord,
as the Lord shall please rightly and orderly to bring it forth, and not otherwise.
And my words so plainly signifying, and holding forth this,
oh! how will J. Pennyman answer it to the great God, for thus misrepresenting me,
and striving to make my words signify that which they never did,
and as a proof how contrary our doctrine was then, to what it hath been of late years?
whereas, in that very book he cites, my words are full concerning church-government,
the authority of the church, and the duty of subjection to it in the life,
as was before recited.

I have been in a great travail of Spirit for J. Pennyman,
the Lord having showed me his spirit and state (as he hath also done to many others,
who abide in that pure, holy light which he hath forsaken, and is departed from);
and this hath been the cry of my heart to the God and Father of my life for him,
in great brokenness and tears, many times; Father, forgive him,
for he knows not what he does.
He knows not what Spirit and power he acts against,
nor what spirit and power it is that leads him.
Oh that he might see it, and turn from it, and live!
And oh, that all that err, and are mistaken in judgment,
might have a sense of that which is truth indeed, and of that which is darkness indeed,
in their own hearts; and might not put darkness for light, and light for darkness,
as too many now do, to the great hurt of their own souls,
and the hardening of others against God`'s precious way and truth,
which will be bitterness in the latter end unto all such!

=== Three or Four Considerations Added Concerning Church-government

[.numbered-group]
====

[.numbered]
_First,_ That it is the holy will and pleasure of the great God,
that his church should be governed by his Holy Spirit and power revealed in it.
God is the God of order, and not of confusion,
and he would have everything in the right and holy order everywhere,
especially in his church.
He hath given a measure of his good Spirit to every man,
and he would have every man governed thereby:
and he hath given more of his good Spirit and holy power to his church than to any particular,
and he would have his church governed thereby.
Read the epistles of Christ to the churches in the
second and third chapters of the Revelations,
and see how government and care over their members is expected from them.
A church is a gathering in the name, power, and authority of the Most High; and Christ,
to whom God gave all power in heaven and earth, is in them, and with them.
God knows they can do nothing without his power;
and he is faithful who hath appointed them to meet together in his name,
and he will not fail them.
How hath this been experienced in former days!
And how is this experienced in this our day, blessed be the name of our God!
The life that springs in the church, the light that shines in the church,
the power and presence of the Lord that is revealed in his church, oh,
how glorious is it!
God hath not gathered nor preserved a people through so many trials,
nor so exercised and built them up in his pure fear, Holy Spirit, and living truth,
to leave them so suddenly, and cast them off, as some men vainly imagine;
but as the Lord hath thrown down that which shall never be built up more,
so the Lord hath built up that which shall never be thrown down more,
and brought many of his people to a settled state, in the unchangeable truth and power.

[.numbered]
_Secondly,_ It is the great work of Satan, and the great interest of Satan,
to oppose the holy order and government of the Spirit of Christ in his church.
It is that power which threw down his kingdom, and that power will keep his kingdom down;
yea, the more that authority and power is established in the church,
the more he is seen through,
and his strength and subtlety avail nothing before
the wisdom and power of God revealed in his church.
And this we have observed, and may observe, in this our day, the judgment of the church,
the life in the church, the light that hath stayed with the church or holy gathering,
while particulars sometimes have been mistaken, and erred about the light in themselves,
have been a stay to those that have hearkened to her voice,
and a means to help to recover those, who, through the strength of the temptation,
and their too confident leaning to that which they took for the light within,
and not consulting with those whom God had ordained to be a help to the weak,
and had a clearer eyesight and understanding in the truth than themselves,--I say,
the light that hath stayed with the church hath been
a help to recover such who have mistaken in judgment,
and erred from the light in their own particulars.

[.numbered]
_Thirdly,_
There is great benefit and safety to every particular in the holy
order and government which God hath ordained in his church.
God knoweth it is not fit for believers or his gathered ones to be alone,
and therefore he hath appointed, that by the same power and Spirit which gathered them,
they should be added to the church which he hath already gathered.
And then they are in the place where God takes care of them; where the Lord God appears;
where the Lord God dwells.
For as he dwelt outwardly in the national church of the Jews,
so he dwells inwardly in the spiritual church, and gathering of believers.
There life is in its unity and strength; there light shines as in its proper place;
there the Shepherd is who keeps the sheep from erring; there the leading power,
the preserving power, the ordering power, is daily waited for,
and experienced in its brightness and clearness.
"`Woe is to him that is alone;`" but blessings are upon him
who is in unity with God`'s holy gathered people,
and is in the sense of, and under the guidance of,
that Spirit which is continually present with them.
And as we have witnessed blessings in our first gathering,
as we were gathered and joined to the light, Spirit,
and power of the holy God in our own particulars,
so we have witnessed blessings in our unity with the life in the body.
Oh, how every motion of life is felt there!
How the wisdom and power of God is revealed there!
What help is administered to every member there!
How the knitting in the life,
and the flowing of the life and holy power from vessel to vessel,
is daily experienced there!
So that every one is quickened with the pure life; every one seasoned with the pure salt;
every virgin anointed with the holy ointment;
every one leavened with the leaven which unleavens to sin and Satan, and leavens to God.
Indeed, my soul daily blesseth the Lord, not only that he hath visited me,
but brought me into the holy, living society;
and that daily the Lord vouchsafeth to give me to partake of their life and Spirit,
in which life and Spirit I have unity with them, and love them, and honor them,
and not out of it.
Oh! praises and everlasting honor and renown to the Lord my God,
who hath remembered me with the favor he bears to his people,
and hath so visited me with his salvation,
that he hath given me to see the good of his chosen, and caused my poor, desolate,
mourning soul to rejoice in the gladness of his nation,
and to glory in him with his inheritance.
Glorious things were spoken of the church under the law;
a glorious power and presence was with that outward people, under that outward covenant;
but this was but a shadow of the glory that was to
be revealed in the church of the new covenant,
and of the presence and power of the living God,
that was to be manifested and dwell there.
And indeed it is manifested, indeed it doth dwell there,
and those that are the begotten and born and preserved by God`'s Holy Spirit,
and power of the immortal Word of life, daily witness it.

[.numbered]
_Fourthly,_ The glory and beauty of the New Testament church doth, in no small degree,
consist in the holy order and government of them, as a spiritual, living body,
by the blessed Spirit and power of the Lord.

====

There were four things wherein the glory of the church
of the Jews under the first covenant did much consist.

[.numbered-group]
====

[.numbered]
The _first_ was, in the salvation wherewith God visited them,
and which he bestowed upon them.
"`Happy art thou, O Israel: who is like unto thee, O people saved by the Lord,
the shield of thy help, and who is the sword of thine excellency.
And thine enemies shall be found liars unto thee,
and thou shalt tread upon their high places.`" Duet. 33:29.

[.numbered]
_Secondly,_ In the gifts God bestowed upon them;
for God did adorn and beautify that people with the
good things which he bestowed upon them. Ezek. 16:14.

[.numbered]
_Thirdly,_ In the presence of the Lord their God in the midst of them,
the ark of whose presence was with them, and whose dwelling-place was among them,
and who was nigh unto them to be inquired of by them,
and to answer and supply them with all that they wanted and called upon him for. Duet. 4:7.

[.numbered]
_Fourthly,_
In the holy statutes and righteous judgments which
God gave them to be ordered and governed by,
as his chosen people, ver. 5, 6, 8.

====

Now, all these are much more fulfilled in the New Testament church; for,

[.numbered-group]
====

[.numbered]
_First,_ There is the salvation witnessed,
which this outward salvation of this outward people was but a figure of.
There the everlasting arm of God`'s power is revealed
in an inward and spiritual way and manner,
to destroy the enemies of a man`'s own house, to redeem from Satan, to cut Rahab,
to wound the dragon inwardly,
and to defend his gathered people from the inroads of his strength,
and from the subtlety of his temptations.

[.numbered]
_Secondly,_ The Lord doth give great gifts to his churches;
he blesseth them with all spiritual blessings in heavenly things in Christ.
Mark the diversity of gifts, and diversity of manifestations,
which God gave to his churches in the apostles`' days.
1 Cor. 12:4, etc.

[.numbered]
_Thirdly,_ There was God`'s presence revealed; there Christ was in the midst,
whenever they were gathered together in his name.
Every church (as well as that of the Ephesians) was built
up together a habitation of God through the Spirit. Eph. 2:22.
Yea, Christ was head over all things to the church, which is his body,
the fulness of him that filleth all in all, chap.
1:22-23. Yea, they were and are the temple of the living God,
in which God would dwell and walk, and be their God, and they his people. 2 Cor. 6:16.

[.numbered]
_Fourthly,_
The holy order of his own Spirit and life God will not fail to reveal unto them,
that they may walk in the Spirit of the gospel, in the power of the gospel,
in the order of the gospel,
and the holy government of God`'s Spirit and power may shine in the midst of them,
and that God may bless them as a habitation of justice, and mountain of holiness. Jer. 31:23.

====

The church is a body; every particular soul that is renewed, quickened, and kept alive,
is a member.
Now, every member needs the presence and power of that Spirit which quickened it,
to nourish, keep alive, and order it.
And the church hath much more need of the Spirit to be present with it,
to guide and order it, and keep it in the holy order, power, and government of life.
And this order and holy government in the Spirit and power
of the Lord was brought forth in the apostles`' days:
for the apostles did rejoice in it concerning that church of Colosse,
who joyed beholding their order, and the steadfastness of their faith in Christ.
Col. 2:5. For the apostles and ministers
of Christ did set things in order in that day, Tit. 1:5.
1 Cor. 11:34. and it was their joy to see that order observed,
and their grief when any were unruly,
and would not be subject to the holy order and government of the church. 1 Thess. 5:14.
Tit. 1:10. And the church of Corinth,
though it fell short in no gift, yet falling short in order,
it did not arrive at the glory of some other churches.

The spiritual Solomon, who is full of the wisdom of God, oh,
the blessed order and holy government that he brings forth among his church and people!
How doth God establish Jerusalem, and make her a praise in the earth,
but by the holy order and blessed government of his Spirit, governing her as a church,
as a spiritual body, by his own pure wisdom,
which no other government or order can come near?
And truly my heart hath been often affected and filled with ravishing joy,
when I have beheld the heavenly and blessed order and government
which the Lord God of wisdom hath already brought forth among us,
and guided us in, to the comfort and refreshment of many,
and to the injury and hurt of none, neither without nor within.
And indeed we do not desire any greatness or authority of man;
but only of the Lord our God in the midst of us,
that all men may be but his servants and ministers in the church, and to the church,
for the good of the church.
No, no; this is the day of the Lord,
of the setting up and exalting of his power in the church, which the church waiteth for,
and knoweth the appearance of, and cannot bear the exaltation of man (of man`'s spirit,
wisdom, power,
and authority) instead of the Lord`'s. Yet nothing that cometh from the Lord,
from his pure life and Spirit in any, must be rejected:
and if the Lord please to make use of those whom he did
make use of to gather home to himself,--I say,
if he hath given them gifts, and please to make use of them also in building up,
and manifesting the holy order of his Holy Spirit and power,
the Lord must not be resisted or withstood therein;
but whatever comes from him must be received with thankfulness,
through what instrument soever he please to convey it.

[.discourse-part]
Objection.
But have I not been taught to be subject to the light in my own heart,
and to make that my judge?
And is not this another, or new, or different doctrine from that,
now to tell me I must subject to the light of God`'s Spirit in his church?
Suppose that which the church requires, or orders, or holds forth,
be different from my light,
or be not yet revealed to me by the light wherewith God hath enlightened me,
must I deny the light wherewith God hath enlightened me,
and subject to the church`'s light?
Or must I practise as the church orders,
before I have light and faith in my own particular?

[.discourse-part]
Answer.
I shall answer this question according to the naked and plain sense of truth in my heart.

[.numbered-group]
====

[.numbered]
_First,_ God gives power to his church to perform all that he requires of her as a church.
Now, the church is a spiritual body, and is to take care of her members,
to look after them that they mind the truth, and walk according to truth,
and to admonish and reprove them when they do otherwise.
And every member of the church ought to hear the church,
in whatever she speaks unto it from God.

[.numbered]
_Secondly,_ every member hath need of the light, Spirit,
and power which God gives his church, and reveals in his church,
for the good of the body, and the benefit and advantage of each member therein.

[.numbered]
_Thirdly,_ The light, Spirit, and power in the church is never contrary to the light,
Spirit, and power in any member; but always one with it,
and a cherisher and preserver of what God begets, and which answers his witness in any.
The new Jerusalem, the church of God`'s building in his own Spirit and power,
is a city at unity within itself.
The greatest degree of light owns, and is at unity with, the least,
and the least degree of light hath a sense of that
which is in degree and measure above it.

[.numbered]
_Fourthly,_ The light in the weakest, which they are at first to be turned,
and afterwards to be kept to, though there is a sufficiency in it for the particular,
yet they are not so understanding and sensible of it as those whose
senses have been long exercised in the living truth,
and are grown in the holy experience.
Therefore as the elders are to be tender of the younger,
so the younger are to reverence the elders in the Lord,
and not to slight their testimony, experience, or judgment in the truth.
When we were first convinced of the truth,
were we not in a great degree ignorant and doubtful
concerning the risings and motions of it in the heart,
which the eye being yet weak, could not clearly distinguish?
And oh! how helpful to us was the tender care and advice
of such whom God had made acquainted with those things,
and were able to give us true judgment from him,
in such cases as our weak minds were apt to be entangled about,
and could not see through!

[.numbered]
_Fifthly,_ Great sobriety is needful in such cases,
wherein men are too prone to be judging others, especially the church of God.
Every man is to take heed of thinking of himself more highly than he ought to think;
but to think soberly, according as God hath dealt to every man the measure of faith. Rom. 12:3.
And the young men (who have not the experience of the aged,
and are most apt to confidence and excursions) are
in a special manner to be exhorted to be sober-minded. Tit. 2:6.
Men may easily judge that others err,
and that they themselves keep to the light and measure of truth in their own particulars;
but it is hard to do it.
But they that indeed do it, abide in the humility, and innocency, and lamb-like spirit,
which would give no offence in any thing, neither to Jew nor Gentile,
nor to the church of God.
If it will go so hard with him that offends one of Christ`'s little ones,
how will it go with him that offends his church, wherein his power and glory riseth,
and is established?
The church is not apt to be such an erring body from the light, Spirit,
and power of the Lord Jesus,
as many (who mistake concerning the light in their own particulars) are too apt to suppose.

[.numbered]
_Lastly,_ Ever since the fall of man, man hath been secretly, or more manifestly,
directed by a light, or the principle within to direct or guide his ways.
To Adam the holy seed was promised,
which was not only to appear outwardly in a body of flesh,
but also within in man`'s heart, to bruise the serpent`'s head there.
And the holy patriarchs had not the letter outwardly, but God`'s Spirit inwardly,
to be their guide and teacher,
which did also strive with the wicked old world before the flood.
The Jews also were directed to the Word nigh in the mouth and heart:
and by this Word God showed also to the Gentiles what was good,
and what the Lord required of them;
and by this Word such of the Gentiles as hearkened to it felt somewhat of the new creation,
and of the new nature, by which nature they did in measure answer the holy law of God,
and do the things contained in the law, which by the old, corrupt nature no man can do.
Also Christ preached the kingdom, or seed of the kingdom within.
And the apostles preached the same Word of faith within, which Moses had testified of.

====

Yet in none of these dispensations was any testimony from God to be despised;
but his voice to be heard in the prophets, in Christ, and in the apostles.
And though men are blessedly and gloriously turned, and to be turned to the light within,
in these our days;
yet they are not thereby taught to neglect or despise the voice of God,
in any whom he sends and speaks by, and pretend it is contrary to their light;
but to lie low before the Lord, that in the true humility and holy fear,
they may know the voice of the Shepherd, both in their own hearts,
and in whomsoever he pleaseth to speak.
For the great Almighty God is not limited,
but he may speak in and through whom he pleaseth.
He may speak to me from the anointing in my own heart,
and the holy anointing may please to speak to me through others;
and so far as I am of God, and sensible of his appearance,
I cannot despise the voice of the anointing in my own heart, or through others.
Yea, truth teacheth that modesty, temperance, humility, tenderness, and sobriety,
that I dare not despise the voice that pretends to the anointing in any,
until I have made trial of it.
Yea, John Pennyman`'s voice and testimony I durst not condemn, until the Lord my God,
in the unerring light and pure springing life, manifested unto me that it was not of him,
but of the transforming enemy,
who had bewitched and deceived him by his strong delusions (he forsaking the rock,
which would have been his strength), to receive and believe a lie instead of the truth.

Oh, blessed be the Lord for the building up such a church,
and speaking to us through his church!
And happy are they that hear her voice, and so keep to their own,
as to know the voice of their own in the church,
and are not through temptation prejudiced against it.
For it is the Lord`'s gathering, and the Lord is with it;
and the people who have been gathered by the Lord, and are daily taught by him,
keep with him.
And though some may depart from us, and, through error of judgment, testify against us,
yet truth abides, and the Lord`'s people abide with the truth, and his building goeth on,
and the holy government of his Son increaseth in it,
and the Lord appears more and more inwardly in his glory,
as the hearts of his people are made capable to receive it from him.
And in all the goings out of any, and apostasies that have been in any,
through hearkening to a wrong spirit,
they that have heard and reverenced the voice and testimony of the church,
and God`'s chosen and blessed ministry, which he hath raised among us,
have still been preserved; and they that have gone therefrom been betrayed.
And it is my faith, this church of God`'s gathering shall still be preserved,
and grow in the holy dominion and authority of God`'s blessed Spirit;
and that all her enemies shall be found liars unto her,
and she shall tread upon their high places,
and shall grow and prosper the more by all opposition;
the everlasting arm and wisdom of the Almighty being with her, to preserve, prosper,
and bless her, so be it.
Amen.
