== The Seed of God and of His Kingdom

[.heading-continuation-blurb]
Treated and testified of according to the Scriptures of truth,
and according to true experience felt in the heart from the God of truth.

[.section-author]
By Isaac Penington

[quote.section-epigraph, , Matt. 13:31-32]
____
The kingdom of heaven is like to a grain of mustard-seed,
which a man took and sowed in his field.
Which indeed is the least of all seeds: but when it is grown,
it is the greatest among herbs, etc.
____

[quote.section-epigraph, , 1 Pet. 1:23]
____
Being born again, not of corruptible seed, but of incorruptible,
by the Word of God which liveth and abideth forever.
____

[quote.section-epigraph, , 1 John 3:9]
____
Whosoever is born of God, doth not commit sin;
for his seed remaineth in him: and he cannot sin,
because he is born of God.
____

=== Preface

I would fain have (and my soul exceedingly breathes to the
Lord for it) disputing about religion come to an end,
and the right understanding, practising,
and experiencing the true religion begun and go on in men`'s hearts.
The gospel religion, in the apostles`' days,
did begin in the evidence and demonstration of God`'s Spirit inwardly;
and it cannot rightly begin any otherwise now.
Nor can it rightly go on any other way, but according to its beginning:
for they that begin in the Spirit, cannot possibly rightly go on, or be made perfect,
by the flesh.
Did the apostles in vain wait for the Spirit and power from on high?
Can the gospel ministry, or gospel work in any heart, be carried on without it?
Or did they in vain turn men from Satan`'s power to God?
Can the least true change be wrought in the heart,
without the operation of God`'s Holy Spirit and power there?
And to be turned to wait for, and taught to know,
the risings of the pure power of the Lord inwardly (which is so necessary to begin,
preserve, and carry on the work), oh, what a precious ministration of life,
and of the gospel, is this from the Lord!
The thing that we wanted, and mourned after all our days,
in our several strains and ways of profession, without the knowledge of this,
is now met with; blessed be the Lord God of Israel,
who cast up and prepared the way (according to his promise) before the face of all people.
Whoever hath an ear to hear what the Spirit saith to the churches of his own gathering,
or from the angel of his own sending,
may now hear the blessed tidings of the reign of the King of Israel,
and of Zion his holy hill, and Jerusalem his holy city;
and how to wait for the law going out of Zion, and the word of the Lord from Jerusalem,
and how he may receive the sheep`'s nature, and the sheep`'s ear,
which hears the voice of the Shepherd, and is not deceived about it.
Oh, come out of the vain, disputing mind, and thou comest out of deceit!
Come into the true silence and stilling of the fleshly part thither,
where God`'s voice is heard and understood; and thou comest into true certainty.
There thou comest to hear the voice behind thee,
calling thee from every false way (which is polluted, and where thy soul`'s rest is not),
and directing thee to the true way, to the way of holiness,
livingly pointing out and saying to thee, "`This is the way,
walk in it.`" This is the way of life, this is the way of truth, this is the way of peace,
this is the way of holiness, here all the true travellers are to walk,
with their faces Zionward,
to obtain the kingdom and righteousness of our Lord Jesus Christ.
Now, O every one that truly thirsts! why do ye not come to the waters?
God hath opened the way, he heartily invites you; yea,
"`the Spirit and the bride say come,
and take the waters of life freely.`" Oh! wait to know the inward, holy power,
and the inward birth, and the inward teaching, and the inward covenant,
and this birth`'s overcoming, by the inward power, the inward enemies;
that ye being delivered from them, may come to enjoy the well of life,
and to sit down in the heavenly places in Christ Jesus, where the true rest is;
and in the strength, life, and virtue of his Spirit,
may serve the Lord in righteousness and holiness,
without fear of those enemies which the Lord hath delivered you from, and which his love,
mercy, and power is as a wing over you to preserve you forever from; I say,
that ye may serve the Lord your God out of the fear of these,
and feed on his holy mountain, out of the reach of those,
in the majesty of the name of the Lord your God,
and these may not be able to make you afraid, or disturb your rest,
or hinder your sweet enjoyment and precious service of your God any more!
O ye that are afraid of being deceived! take heed
that ye be not deceived inwardly in your hearts,
about these things; and, by the veil which the enemy spreads there,
hindered and deprived of your share in the blessed administration of the Spirit, life,
and power of our Lord Jesus;
whom to know after the flesh (or as man can comprehend
concerning him in his carnal mind) is of little value;
but to know him inwardly and spiritually, to live and reign,
and to exercise his dominion in the heart over every temptation,
and over all that is contrary to God (whenever any such thing appears) is a pure, living,
excellent, and satisfactory knowledge of him;
which the Lord lead every truly hungering and thirsting
soul towards the obtaining and full enjoyment of!
Amen.

[.old-style]
=== Concerning the Seed of God / Or the Seed of the Kingdom

[.section-summary-preface]
What it is: Where it is to be found: Who sowed it there: What is hid or wrapped up in it:
What is its Nature: What its Effects: Of its Growth, and Hindrances thereof;
Of its Blessedness, and how it makes Blessed: How Christ is formed of this Seed;
and how the Soul is born of this Immortal Seed.

[.discourse-part]
_First,_ what is the seed?

[.discourse-part]
Answer.
The seed of God is the word of God; the seed of the kingdom is the word of the kingdom.
It is a measure of the light and life, of the grace and truth, which is by Jesus Christ,
whereof in him is the fulness.
It is a heavenly talent, or manifestation of his Spirit in the heart,
which is given to man for him, in the virtue and strength of Christ, to improve for God.
This which God hath placed in man, to witness for himself,
and to guide man from evil unto good (in the pure breathings, quickenings,
and shinings of it), this is the seed, which is freely bestowed on man,
to spring up and remain in him, and to gather him out of himself, into itself.

[.discourse-part]
_Secondly,_ Who is the sower of this seed?

[.discourse-part]
Answer.
God, in and through Christ.
He is the good husbandman.
He, by the word which created all in the beginning, creates anew in Christ Jesus,
renews his workmanship in man,
and puts a measure of this word or Spirit of life in man`'s heart, whereby he renews him;
and they that are thus renewed by him, are his workmanship,
created in Christ Jesus unto good works.

[.discourse-part]
_Thirdly,_ Where is this seed to be found?

[.discourse-part]
Answer.
Where God sows it, which is in the inward earth.
It is an inward seed, and it is sowed in inward land or earth; that is,
in the hearts of men.
There the light of the word shines, there the life of the word is felt,
stirring secretly in and quickening those that were dead in trespasses and sins.
There the voice and call of the word is heard, calling from unrighteousness and sin,
to righteousness and holiness.

[.discourse-part]
_Fourthly,_ In what sorts of earth is this heavenly seed sown?

[.discourse-part]
Answer.
In all sorts; in thorny ground, stony ground, highway ground, and good ground.
God`'s inward lightnings enlighten the inward world throughout;
so that God hath not left any man without a witness in his conscience against sin.
So that, though man`'s conscience be corrupt, and his light become darkness,
yet God`'s witness in his conscience can never be corrupted;
but whenever it shines in the heart, it gives true light there;
and whenever it witnesseth there, it witnesseth the truth for God, and against man,
and the corruption and searedness of his heart and conscience.

[.discourse-part]
_Fifthly,_ In what sort of earth it brings forth good fruit to perfection.

[.discourse-part]
Answer.
Only in the good ground.
It brings forth fruit in other grounds, and the fruit it brings forth is good.
The convictions are good, the desires begotten there by it, and that arise from it,
are good.
The leaving off of some bad things, and doing some good things, is good; but the thorns,
the cares, the worldliness, the fear of persecution, that spring up from another root,
and are of another nature,
choke the good which the seed brings forth in the thorny ground,
and stifle and choke the seed itself also, in such kind of grounds.
But in the good ground which yields its whole nourishment to the good seed,
and will not yield nourishment to any bad; the good seed not only springs up,
but brings forth fruit to perfection.

[.discourse-part]
_Sixthly,_ How may the ground that is bad be made good?
Was not the ground which is now good, once bad; and may not the ground which is now bad,
be made good?

[.discourse-part]
Answer.
God hath shut up all men in unbelief, that he might have mercy upon all.
The heart that is now soft, was once hard.
The heart that is now believing, was once in the unbelief.
The heart that now loves God, was once in the enmity.
The plow of God, put into the thorny ground, tearing it up,
and rooting out the thorns thereof, will change its nature, and make it become better.

"`Break up your fallow ground: sow not among thorns;`" said God to his Israel of old.
And the stony ground, if the stones be picked out of it, will be less stony; yea,
not at all stony if all the stones be picked out.
And the highway ground, being enclosed, and dressed by God`'s Spirit and power,
will be no longer common or highway ground.
Doth not man, by care, art, and industry, change the nature of outward land or ground?
Surely then the Lord by the word of his power, by his inward destroying of evil,
and creating good anew, can change the nature of ground inwardly.

Now, for the clearer and plainer signifying of what yet remains on my heart,
concerning this precious seed of life, or seed of the kingdom of God;
I shall distribute it under these three heads:
under which the things mentioned in the foregoing title will be comprised.

[.numbered-group]
====

[.numbered]
I+++.+++ What is hid or wrapped up in this seed.

[.numbered]
II. The nature of it.

[.numbered]
III. The effects of it.

====

[.inline]
==== I. What is hid or wrapped up in this precious, heavenly Seed

[.discourse-part]
Answer.
Indeed there is so much wrapped up in it, as the heart of man cannot conceive,
much less the tongue utter; yet somewhat have I felt, and somewhat is upon my heart,
to say in answer to this thing, under these four heads following: --

[.numbered-group]
====

[.numbered]
_First,_ The glory of the kingdom of heaven, the glory of the everlasting kingdom,
is hid and wrapped up in it as in a seed.
Whatever Christ appears, reigns, and shines in, is there as in a seed.
Oh, the shootings forth, and spreadings abroad of it, are indeed glorious and excellent!
How can a man almost speak concerning it! the thing itself (being inwardly felt, known,
and enjoyed) is so far beyond all words!
What doth the kingdom of God stand in?
It stands not in word, but in power.
The power is hid and wrapped up in this seed.
The pure power of life is in this seed.
The sword that pierceth Leviathan, that woundeth the serpent`'s head,
that cutteth Rahab and the dragon, is in this seed.
Doth the kingdom of God consist in righteousness, peace, and joy in God`'s Spirit?
This is all in this seed, and is partaken of and enjoyed, as this seed springs up,
and gains authority and dominion in the heart.
Yea, the horn of God`'s anointed,
the righteous and peaceable sceptre of the Saviour is known and exalted in this seed,
as it springs up, and spreads abroad in the life and virtue of the Father.

[.numbered]
_Secondly,_ The divine nature of God Almighty is hid and wrapped up in it.
It is the seed of God, and it is the very nature of God; and he in whom it springs,
and who is gathered into it, born of it, and one with it, partakes of the divine nature.
Peter speaks of the great and precious promises,
whereby the saints are made partakers of the divine nature.
All the promises are to the seed of promise, to Christ the Son of God,
to the seed of God, to the heirs of life and salvation in Christ;
and they are all fulfilled to them, and enjoyed by them, who are ingrafted into,
and one with Christ, the seed; which cannot be, but by the grace, by the truth,
by the light, life, Spirit, and power, which he sows in the heart;
which are not many things, but all contained and comprehended in the one seed.

[.numbered]
_Thirdly,_
All the graces and virtues of God`'s holy Spirit are hid and wrapped up in this one seed.
There is nothing God can require of the soul, nor nothing the soul can desire of God,
but is hid and wrapped up in this seed, so that all that is needful,
or all that can be desired, is the growing and spreading of this seed in the soul,
and the soul`'s gathering into it, and its living, dwelling, abiding, and acting in it.
And oh! the great difference between the soul`'s selfish striving and willing and running,
to join to God and Christ, and to live in God and Christ;
and God`'s joining it to himself and his Son in this seed, and its living, willing,
and acting in the springing life of this seed!
To make this a little more plain and evident to the hearts
of those that desire the true understanding of this thing,
I shall instance in some particulars.

====

[.numbered-group]
====

[.numbered]
_First,_ The pure, living, heavenly knowledge of the Father, and of his Son, Christ Jesus,
is wrapped up in this seed.
God is light; and this seed, which comes from him, is not darkness, but light;
and in the springing light of this seed, God and Christ are revealed.
The divine nature of them springs up in the seed (and if I know their nature,
I know them); yea, here we, whom the Lord hath visited, and shown mercy to,
though men despise us, know the righteous Spirit of Christ,
the righteous nature of Christ, the righteous life of Christ,
and feel him to be one with the Father, who begets of the same Spirit, nature,
and life in us.
And he that is born of the Spirit is Spirit;
and he that is united to the Lord is one Spirit; and he that is united to the seed,
to the measure of grace and truth from Christ (wherein and whereby the soul is united),
is united to God, and ingrafted into Christ; and as the seed is formed in him,
Christ is formed in him; and as he is formed and new-created in the seed,
he is the workmanship of God, formed and new-created in Christ.

[.numbered]
_Secondly,_ Faith, the true faith, the lively, effectual, saving, conquering faith,
which gives victory over the world, and over the devil and his temptations,
is contained or wrapped up in this seed.
Faith is the gift of God, the precious gift of God; which is not found in man`'s nature,
but springs and grows from the precious seed of the kingdom,
which God sows in man`'s heart.
So that it is a gift to be waited for, and obtained from God.
Therefore the apostle Peter, writing to the saints in his time,
directs his epistle thus:--"`To them who have obtained like precious faith with us,
through the righteousness of God,
and our Saviour Jesus Christ.`" 2 Pet. 1:1. Faith is a precious thing,
a righteous thing, an holy thing, which God is the giver of,
which Christ is the author and finisher of; and it springs from the holy root,
from the holy seed of life and righteousness which God sows in the heart.
This faith (I speak not of man`'s ability of believing,
or the faith which is found in man`'s nature) is the faith of God`'s elect. Tit. 1:1.
The faith which God gives to them that are born of him, John 1:12-13.
who are born of the seed incorruptible, by the Word of God,
which liveth and abideth forever, 1 Pet. 1:23.
which Word being nigh in the mouth and heart, and begetting, preserving,
and increasing faith there (as is daily experienced plentifully, blessed be the Lord),
is therefore called the word of faith. Rom. 10:8.

[.numbered]
_Thirdly,_ The pure fear, the holy fear, the heavenly fear,
which is of a clean and heavenly nature, and endureth forever, is also in this seed.
The child-like fear is in the nature of the child;
and the more it grows in the true child-like nature,
the more it grows in this kindly fear, wherein there is no torment,
but the pure pleasure of life, and of holy obedience to the Father of life.
The child-like fear is a promise of the new covenant;
and given to the children of the new covenant, by virtue of the new covenant;
God putting it into their hearts from the seed of life springing up in them,
which preserves them from departing from the Lord. Jer. 32:40.

[.numbered]
_Fourthly,_ The pure divine love is in it.
As this springs, love to God springs.
As God is love, so the seed that is of him partakes of his love.
There is no enmity in it, and no enmity or ill-will springs from it.
This is it that makes it so natural to the children of God to love;
because they are born of that seed which came from the God of love, whose nature is love.
Oh, how daily is it found, by sweet and certain experience,
that this seed (springing up) teacheth and enableth to love!
And they that have this seed springing up in them need not to be writ to,
or outwardly taught to love with the brotherly love; for in it, and by it,
and through it, they are taught of God to love one another.
So that there needs nothing but the circumcising of the heart,
the purifying of the heart, through the obedience of the truth,
the cutting off of that fleshly mind, nature, will, and wisdom, which cannot love aright;
and the pure love will spring up fully towards the Lord, and towards the brethren, Duet. 30:6.
1 Pet. 1:22. yea, it will be natural to love all;
and that command of Christ will not be grievous; namely, to love enemies,
even the greatest revilers, cursers, and persecutors. Matt. 5:44.

[.numbered]
_Fifthly,_ The pure hope, the hope of the upright, the hope which makes not ashamed,
the hope which goes within the veil, and is a sure and steadfast anchor there,
staying the mind upon the Lord, who keeps such in perfect peace;
this hope is contained in and springeth from the seed.
For nothing but that which comes from God (from the holy seed of
truth and righteousness) can stay the mind upon God.
So that he that feels the seed feels the hope,
and keeping to the seed (to the holy root) to the end, the hope remains to the end.
So the mind being turned to the light, being turned from Satan`'s power to God,
being turned to Christ,
being turned to the appearance and voice of the word of life within,
being turned from the seed of wickedness and darkness,
to the holy and righteous seed of the kingdom, it is turned to the hope,
it is turned to that which begets a true and right hope in the heart;
which hopes in God`'s love, hopes in God`'s mercy, hopes in God`'s kind, tender,
and faithful nature; and hath no confidence nor hope in the flesh,
but in the holy and heavenly seed, and work of righteousness and of the kingdom;
which is God`'s battle-axe and weapon of war, whereby he brings down the flesh.
This hope stays the mind in every temptation, in every distress, in every trial,
in all the winds, storms, and waves of persecution that it can be assaulted with.
For in this seed the root of Jesse is felt,
the everlasting rock and foundation of life is felt; and here the hope of God fills his,
that are gathered hither, and abide here, with all joy and peace in believing,
that they may abound in hope, through the power of the Holy Ghost. Rom. 15:12-13.

[.numbered]
_Sixthly,_ The true patience, which obtains the crown, which makes perfect and entire;
so that there is nothing wanting, where it hath its perfect work; James 1:4,
the patience which enables quietly to suffer any chastisement from God,
or any affliction, or hard dealing from men, it is contained in and given with this seed.
As God is patient and long-suffering, so this seed is also.
It is man that is of the brittle, fretful, impatient nature;
but he that receiveth the word of faith, the seed of faith,
in it he receiveth faith and patience also:
so that to him it is not only given to believe,
but to suffer also for the sake of Christ; and he that abides in the seed,
and feels the seed remaining in him, and its nature prevailing, can never be impatient,
whatsoever the Lord suffers to befall him.

[.numbered]
_Seventhly,_ The Lamb`'s meekness is in it.
Where should the Lamb`'s meekness be found, but in his Father`'s seed,
or in the seed of his Father`'s kingdom?
Here the meek and quiet Spirit is received, witnessed, and enjoyed,
which in the sight of God is of much price.
This seed is sowed or begotten in the womb of the heavenly wisdom;
and the meekness of wisdom, the true meekness of the true wisdom, is found in it.
Here the still, soft, gentle, lamb-like nature grows up,
wherein there is none of Esau`'s roughness.

[.numbered]
_Eighthly,_ Here poverty of Spirit, true poverty of Spirit, is witnessed.
He is poor indeed, who hath sold all, and hath nothing left him but this seed,
and the appearance and help of God in this seed; which is not in his own hands neither,
but in the will and disposal of God.

[.numbered]
_Ninthly,_ Here mercifulness towards others is experienced;
for he that is brought hither lives only by mercy; and he that lives by mercy,
and is daily what he is by mercy, cannot but be merciful unto others.

[.numbered]
_Tenthly,_ Here the true mourning and lamenting after the Lord,
and his precious life and presence,
and because of the presence or power of that which hinders the growth of the seed,
and the soul`'s union with, and enjoyment of, the Lord in it, is witnessed.
For the true mourning, to which the blessedness belongs, is of God,
from the living sense that ariseth from his pure seed in the heart;
and blessed indeed are they that thus mourn, for they shall be comforted.

[.numbered]
_Eleventhly,_ The true hungering and thirsting after righteousness ariseth from this seed.
It is the seed of God, the birth of God,
that which hath the sense of the excellency of his righteousness,
that hungers and thirsts after his righteousness.

[.numbered]
_Twelfthly,_ The true sobriety, moderation, and temperance ariseth from this seed;
and they that are joined to the seed, and are and act in the seed,
easily learn such sobriety, moderation, and temperance,
as they that are out of it cannot possibly learn.

[.numbered]
_Lastly,_ To name no more, the cross which mortifies and crucifies to the world and to sin,
can only be taken up in the seed, or by virtue of the seed.
Indeed the seed is a cross; yea, enmity to the serpent`'s nature, spirit, and course;
and he that takes it up, its will, its nature, its law of life,
takes up the cross to the other nature, will, and the law of sin and death.
So that fly the holy seed, and thou hast only a shadow or appearance of the cross;
but in a sense of and subjection to the seed, the cross of our Lord Jesus Christ is felt,
working powerfully against sin, and the whole course of the evil and sinful nature,
effectually crucifying and subduing it.

====

[.numbered-group]
====

[.numbered]
_Fourthly,_ The fourth thing which is hid or wrapped up in the precious seed,
which is the last that remains to be mentioned by me at this time, is this;
The new covenant, which God makes with the new Israel, by which he makes the heart new,
and writes his law in it, and takes away the stony heart,
and heals all their backslidings, and loves them freely, and puts his Spirit within them,
causing them to walk in his ways, and to keep his statutes and judgments, and do them;
even the holy agreement of the soul with God in Christ Jesus, is in this seed.

====

God gave Christ for a covenant, and the seed of grace and truth comes by Jesus Christ;
which is of his nature, of him the covenant;
and all that receive this grace and truth from him, this holy seed of the kingdom,
they receive the covenant; and they that walk in it, walk in the covenant.

Here, and here alone, the new creation in Christ Jesus is known.

Here, and here alone, the coming to God by Christ is truly understood and witnessed.

Here, and here alone, the law of the Spirit of life in Christ Jesus is writ in the heart.

Keep here, thou never goest out of the holy agreement with God and with Christ;
for in this grace and truth, in this seed of life,
there is nothing that disagrees with them.
Here thou livest in the Spirit, walkest in the Spirit, and dost not, canst not,
fulfill the lusts of the flesh.
There is nothing here that will either displease God, or lead thy soul aside from him;
but here the Lord guides the feet of his saints,
and teacheth all of them (from the least babe of them, to the highest growth),
and puts his law of life and new obedience, and his holy Spirit, into their hearts,
that none of their steps may slide.
Here the way of holiness, wherein God preserves his from erring, Isa. 35:8.
is known and walked in.
Yea, here Christ is known and felt to be the way, the truth, and the life.
The sheep that are gathered hither, and come hither,
are returned to the Bishop and Shepherd of their souls, who watcheth over them,
and powerfully preserveth them, that they run astray no more.
For whither should they go, or whom should they hear, when they have found him,
and know his voice, with whom are the words of eternal life?

I shall conclude this head with that precious scripture, 1 Cor. 1:30.
"`But of him are ye in Christ Jesus, who of God is made unto us wisdom,
and righteousness, and sanctification,
and redemption.`" How are we of God in Christ Jesus, but by this seed of God,
by being born of the Spirit of God, by being begotten out of the spirit of the world,
into the nature and Spirit of Christ, from this immortal and incorruptible seed of life,
truth, grace, and Spirit?
And how do we put on Christ, but by putting on this seed?
And how do we grow up in Christ, but by the growing up in this seed,
and feeling this seed grow up in us?
And here, in truth and demonstration of God`'s Spirit, we are formed in Christ,
and Christ formed in us, as this seed groweth up into a form and shape in us,
and we into a form and shape in it.
Now, we cannot receive this seed,
but as we part with and deny our own wisdom and fleshly confidence; and denying that,
and crying to God for wisdom, God brings up the wisdom of the seed in us,
and makes Christ become unto us wisdom therein.
And we cannot hunger after the true righteousness, the heavenly righteousness,
the righteousness of our Lord Jesus Christ, but as we see the loathsomeness of,
and put off, our own righteousness; and then becoming naked,
we are taught of God to buy white raiment of him,
which is the righteousness of the saints, and so he becomes our righteousness,
made so of God to us.

And he is the purger and cleanser of sin and unholiness out of our hearts and lives,
and the holy leavener and sanctifier of our hearts; so that we have nothing of holiness,
but what we have of him and in him.
And he is our redemption; our redemption is by him and through him,
our redemption is wrought and preserved by him, and enjoyed in him; yea,
he is made of God unto us redemption.
So that having him, we have redemption through his blood; yea,
he is our redeemer and redemption forevermore.
Alas, what is it to get notions of these things into the outward
comprehension! but to feel them livingly in the heart,
is life and peace forevermore; and the knowledge of this seed of the kingdom,
and of God and Christ in this seed, is the most precious knowledge that can be desired,
obtained, or enjoyed.

[.inline]
==== II. The Nature of this Seed

What is the nature of the seed of God, or the seed of the kingdom?

[.discourse-part]
Answer.
Though the nature of it hath been largely signified already,
under the foregoing head (for the mentioning of what is wrapped up in it,
abundantly showeth its nature),
yet I shall speak a little more punctually and expressly of it in several particulars,
according to the Scriptures,
that the reader may have the more distinct sense and inward apprehension of it,
the Lord opening his heart in reading these things.

[.numbered-group]
====

[.numbered]
_First,_ It is of an immortal, incorruptible nature. 1 Pet. 1:23.
It is a seed that can never die in itself,
though it may be as it were dead in man, or unto man,
not putting forth any of its hidden life or virtue
in the man that hath slain it as to himself;
who having slain that whereby God gives life, is dead in trespasses and in sins,
and cannot live any more, till God breathe upon and quicken this seed in him,
and him by this seed.
This is a great mystery.
Doubtless the seed of life and godliness,
wherein the life and godliness of the soul lies hid, must needs be a great mystery,
and cannot be known but as God reveals it.

[.numbered]
_Secondly,_ It is of a gathering nature.
It is of the nature of a net. Matt. 13:47.
It gathers out of that which is contrary to God, unto God.
It gathers out of the world, out of the sea of wickedness,
out of the kingdom of darkness, out of a man`'s own nature and spirit,
into God`'s nature and Spirit, and his light and kingdom, wherein the soul should dwell,
and walk, and be subject, with God.

[.numbered]
_Thirdly,_ It is of a purging, cleansing nature.
It is of the nature of fire, of the nature of water, inwardly and spiritually.
This seed is Spirit and life in a measure; and by it,
or by God`'s Spirit which dwells and is revealed in it,
he washeth and purgeth away the filth of the daughter of Zion,
and the blood of Jerusalem from the midst thereof.
There is strength in this seed, and virtue in this seed,
against all the strength of deceit and wickedness in the other seed;
and as it springs up, and is received and joined to in the holy fear of the Lord,
it prevails over it, and casteth away its darkness,
and purgeth away and burneth up its filth, chaff, and corruption.

[.numbered]
_Fourthly,_ It is of a seasoning, leavening, sanctifying nature.
It is like salt, it is like leaven.
It seasons and leavens with life.
It seasons and leavens with righteousness.
It seasons and leavens with the image of God.
So soon as ever it springs in the heart, it begins to leaven it;
and if it be not snibbed, or grieved, or hurt, or quenched (for it is of a most sensible,
tender nature), it will go on leavening more and more with the nature of truth,
into the likeness of the God of truth. Mark 9:50.
Luke 13:21. Col. 4:6.

[.numbered]
_Fifthly,_ It is of an enriching nature.
It is a hidden treasure or pearl of great price.
It makes the wise merchant very rich, who sells all for it, and buys the field and it.
He that buys the truth, and will by no means sell or part with it,
but gives up to it and makes it his treasure, oh,
how doth it enrich his heart with that which is holy and heavenly!
How rich doth it make him towards God! Matt. 13:44-46.

[.numbered]
_Sixthly,_ It is of an improving, growing nature,
of a nature that will grow and may be improved.
The one talent may be increased into more.
The little seed, like a grain of mustard-seed,
will grow in the good ground beyond all herbs, and become a tree,
a tree of righteousness of the Lord`'s planting, that he may be glorified. Matt. 13:31-32.
chap.
25:16. chap.
13:23.

====

[.inline]
==== III. Of the Effects

What are the effects of this seed?

[.discourse-part]
Answer.
The effects of the pure seed in the heart are very many, very great, very sweet,
precious, and blessed, which every one comes to experience,
that experienceth the growth and spreading of it.
I shall instance only in some few, to give a taste thereof.

The first I shall mention is, union and communion with God,
the Father of our Lord Jesus Christ, and the Father of this seed,
and of all that are united to it.
Union and communion with God is still in this seed, and never out of it.
For as in the seed of the serpent, a man is separated from God, alienated from his life,
and can never come near him, nor have fellowship with him; so in the holy seed,
in the seed of life, in the seed of righteousness, in the seed of faith,
the soul is united to God, hath access to him, the living fountain,
and hath fellowship with him in that which is living and holy of him.
Men may imagine a union and communion with God out of this,
but none can truly unite to God, or have fellowship with him, but in the gift,
in the grace, in the light, in the Spirit which is of God.

[.numbered-group]
====

[.numbered]
_Secondly,_ This seed felt springing up in the heart, and joined to,
brings down and keeps down all that is contrary to God.
This honor and power God hath given to the seed of
the woman (even to the least measure of it),
that it should bruise the serpent`'s head,
and free the soul from captivity and slavery to the wicked one.
So that the soul, in the living sense, authority, and virtue of this,
may refuse yielding its members, its faculties, its will, its mind, its understanding,
its affections, to sin and unrighteousness.
Yea, the devil, the great red dragon, the god of the world,
the mighty spirit and power of darkness, being resisted in this, is still overcome.
When any resist the devil in their own strength (in the strength of their own desires,
abilities, and resolutions), he still overcomes them;
but they that resist the devil in the faith that springs from this seed,
still overcome him.
So that sin is brought down, and temptation kept out of,
by the virtue and power of the life and authority of the Saviour,
that springs up in this seed of God, which the soul that is joined to it (leavened with,
and transplanted into) partakes of.

[.numbered]
_Thirdly,_ As it springs, and its operations are felt and received,
it brings into the image and nature of God.
It blots out the devil`'s image in the mind, and makes like God and like Christ.
Yea, here we have the very mind of Christ, and are one with the mind of Christ.
As in the serpent`'s seed, the serpent`'s image and nature is put on; so in this seed,
the image of God and Christ is put on.
Yea, the serpent, the dark spirit, the wicked spirit, the deceitful spirit,
is here put off, and Christ is put on;
and whoever would know the real putting off the old man,
and the putting on of the new man,
which is created in the righteousness and holiness of truth, must know it in this seed.
Here the truth is known as it is in Jesus, in its effectual power and virtue,
putting off the old image and nature, and putting on the new, even the heavenly,
divine image and nature.

[.numbered]
_Fourthly,_ It brings the mind, the heart, the soul, the spirit,
into the new obedience (into its own obedient nature),
even to do the will of God with great delight and pleasure.
I delight to do thy will, said Christ.
This seed is of his nature.
It is a measure, a proportion, a heavenly talent of his grace and truth;
a gift of light and life from him, the fulness,
given to make willing (like him) to do the Father`'s will, and it really doth so,
insomuch as the soul, that is thoroughly leavened and one with it, can also say,
I likewise delight to do thy will, O God! it is become my meat and drink;
for I am nourished, refreshed, and delighted with the virtue that I feel spring in me,
in doing thy will.
Indeed it is not so at first, while there is a nature, a will,
a wisdom contrary to the nature, will, and wisdom of God; obedience is then hard,
the cross is then a sore yoke upon my neck.
But that nature being subdued, and the nature of the seed coming up and prevailing,
what can be more delightful to this new nature,
than to do the will of its heavenly Father,
and to find the heart of the Father pleased with the child, which it always is,
while the child is in tenderness of spirit, in the holy faith,
and in the holy obedience to him!

[.numbered]
_Fifthly,_ It brings into the understanding, sense,
and enjoyment of all the precious promises,
and to the partaking of all the spiritual blessings in Christ Jesus our Lord.
All the promises are to the seed and yea and amen in Christ;
and the least measure of his life hath a share therein.
The seed, the everlasting seed, is the heir; and we joined to the seed, born of the seed,
growing up in the seed, are joint-heirs, heirs of God, and joint-heirs with Christ.
So that every promise comes to be understood here, tasted of here, enjoyed here.
How full are the Scriptures of sweet and precious promises!
Alas! what is it for men to apply them to themselves, when they have no right to them,
nor indeed rightly understand them,
nor were they intended by the Lord to their present states and conditions!
But to come to the true understanding of the promises,
to be led by the Lord into that condition, and preserved by him in that condition,
to which the promises belong, and to have him bring home the promises to the heart,
and drop in the sweet, healing, delighting, refreshing virtue of them; oh, how sweet,
comforting, and gladding is this!
Indeed, in this seed all the curses of the book pass away, and all the blessings flow in,
and multiply on the soul day by day.
So that this may well be called the blessed seed; for in it the soul is blessed,
and filled with blessings by him who is able to multiply them upon the soul,
and to guide the soul in the safe and right use and enjoyment of them.

====

But what need I mention any more?
Here is light, here is life, here is righteousness, here is peace, here is heavenly joy,
here is the holy power, springing and bringing forth their fruits,
and precious operations and effects in the heart;
and here is assurance of the love of God in Christ forever,
and that God will never leave nor forsake that soul which is joined to him,
and abides with him in this seed; but it shall be kept by the power of God,
through the faith that springs from this seed, unto perfect redemption and salvation.
Amen.

[.old-style]
=== Some Queries Concerning God`'s Kingdom / Whereby the Seed Thereof May Be the Better Illustrated and Understood

[.numbered-group]
====

[.numbered]
_Query 1._ What is the kingdom of God,
which Christ said he must preach to other cities also?
For therefore was he sent. Luke 4:43.

[.numbered]
_Query 2._ What is the kingdom of heaven, which first John, the fore-runner,
and then Jesus himself, when he began to preach, bid men repent, because it was at hand? Matt. 3:2.
and chap.
4:17. What would repentance advantage men?
Would it fit men for entrance thereinto?
Did those that truly repented and believed,
come out of the kingdom of darkness and Satan,
and enter into the kingdom of the dear Son? 2 Pet. 1:10-11.

[.numbered]
_Query 3._ What is the kingdom of God, and the righteousness of God,
which Christ (the everlasting, wise, and holy counsellor) adviseth men first to seek? Matt. 6:33.
Where is this kingdom to be found?
Where is this righteousness to be found?
What is it hid and wrapped up in?
Can it be found in any thing but what it is hid by God and wrapped up in?

[.numbered]
_Query 4._ What kind of poverty of spirit is it, and who are those poor in spirit,
to whom the kingdom of heaven belongs? Matt. 5:3.

[.numbered]
_Query 5._ How may men know when the kingdom of God is come unto them?
Is it not then manifest, when the stronger than the strong man,
not only knocks at the door of the heart, but casts out Satan thence,
and maketh spoil of his goods? Matt. 12:28-29.

[.numbered]
_Query 6._ Who are they that shall enter into the kingdom of God?
Are they not they who are born of water and of the Spirit? John 3:5.
Of what water?
And how must they be born of the Spirit?
Were not this worth the knowing?
And they that become as little children; simple,
innocent (not wise or knowing after the flesh),
that know the breast that is natural and proper for them,
and thirst after and drink in the sincere milk of the word of life,
from the breast of the heavenly wisdom? Luke 18:17.
1 Pet. 2:2.

[.numbered]
_Query 7._ Who shall in no wise enter into the kingdom of heaven?
Shall not all they be excluded who want the wedding garment,
who want the true righteousness? Matt. 5:20.

[.numbered]
_Query 8._ What are the glad tidings of the kingdom of God?
Is it not that the kingdom of God is come, and that his reign is set up,
and setting up therein? Luke 8:1.
Isa. 52:7.

[.numbered]
_Query 9._ Who are they,
before whom publicans and harlots shall enter into the kingdom of God? Matt. 21:31.
Who were they in that age?
And who are they in this age?
Oh that men had hearts rightly to consider and understand!

[.numbered]
_Query 10._ Who are they that the kingdom of God shall be taken from,
and given to a nation bringing forth the fruits thereof?
Are they not the wrong builders in every age,
and such as are taught by the wrong builders, to reject the living stone?
ver. 42-43.

[.numbered]
_Query 11._ Who are the children of the kingdom that shall be cast out into utter darkness,
where shall be weeping and gnashing of teeth? Matt. 8:12.

[.numbered]
_Query 12._ Who are those God reveals the mysteries of the kingdom to in every age?
(Are they not his begotten ones,
his babes in the Spirit?) And who are those that he hides
the mystery of the kingdom of life and salvation,
and the way thereof, from in every age?
(Are they not the wise and prudent in their own apprehensions of the letter,
without the Spirit?) Matt. 13:11. and chap.
11:15.

[.numbered]
_Query 13._ Who are those that are nigh the kingdom of God?
Are they not those who know that love is the fulfilling of the law,
and that the substance is beyond shadows? Mark 12:33-34.

[.numbered]
_Query 14._ Who are those that shut up the kingdom of heaven against men?
Are they not those who take upon them to expound the letter to men,
and do not turn men to the Spirit, but quench it both in themselves and others? Matt. 23:13.
Luke 11:52. Isa. 22:22.

[.numbered]
_Query 15._ What kingdom is that,
wherein he that is least is greater than the greatest prophet?
wherein he that is feeble shall be as David, and the house of David as God,
as the angel of the Lord before the inhabitants of Jerusalem? Matt. 11:11. 12:8.

[.numbered]
_Query 16._ Who were they in the apostles`' age (and are there
any such in this age?) who shall not taste of death outwardly,
till they have seen the kingdom of God come with power inwardly? Mark 9:1.

[.numbered]
_Query 17._ What kind of looking back is that,
which makes a man unfit for the kingdom of God?
Is it not a looking back from the plow, and not forward to the plow?
And what plow is it a man must put his hand to, and not look back,
that he may be fit for the kingdom of God? Luke 9:62.

[.numbered]
_Query 18._ What hand, what foot, what eye, is it,
which a man may enter into the kingdom of God with?
And what hand, what foot, what eye, is it,
which a man cannot enter into the kingdom of God withal? Mark 9:47.

[.numbered]
_Query 19._ What is it to eat bread in the kingdom of God?
Is not there the feast of fat things, and of wines well refined, made to the soul;
and doth it not there sup with Christ, and Christ with it?
And is not the wine of the kingdom there drunk new and fresh with Christ? Luke 14:15.
Isa. 25:6. Rev. 3:20. Mark 14:25. Luke
22:16,18. Shall not the mountains there drop down new wine,
and the hills flow with milk, and all the rivers of Judah flow with water?
And shall not a fountain come forth out of the house of the Lord,
and water the valley of Shittim? Joel 3:18.

[.numbered]
_Query 20._ How may one become as a little child, that he may receive the kingdom?
Must not that man be born anew?
Must he not be unborn after the flesh, and born after the Spirit?
(And not only so, but he must receive and enter into and abide in the kingdom,
in that child-like simplicity and innocent wisdom, whereof he is born.) Luke 18:17, John 3:3.

[.numbered]
_Query 21._ What is that flesh and blood which cannot inherit the kingdom of God,
and that corruption which cannot put on incorruption? 1 Cor. 15:50.
(Let him that readeth understand the thing,
both in the letter and in the Spirit.)

[.numbered]
_Query 22._ Who are the unrighteous, that shall not inherit the kingdom of God?
Are they not both the manifestly unrighteous, and also the secretly unrighteous; who,
though they may preach faith in Christ, and the righteousness of Christ,
and may think themselves believers in him, and clothed with his righteousness,
yet have not received power to become the sons of God,
nor through the Spirit have mortified the deeds of the body; but at last,
notwithstanding all their profession and pretence to Christ`'s
righteousness (out of the faith that works by love,
and out of the fine linen, in their own filthy rags),
are found by him workers of iniquity. 1 Cor. 6:9.
Luke 13:26. Rom. 8:13. 1 John 3:7.

[.numbered]
_Query 23._ Shall any enter into the kingdom of heaven,
but they that do the will of Christ`'s Father which is in heaven?
Is it enough to pray, Thy will be done on earth, as it is in heaven?
Is it not necessary also to receive that power which makes willing,
and that nature and Spirit whose delight it is to do the will of the Father? Matt. 7:21.

[.numbered]
_Query 24._ Who shall be counted worthy of the kingdom of God?
Shall not they who suffer for it in the holy faith and patience,
and so are willing through the much tribulation (whether outward or inward,
or both) to enter into it?
2 Thess. 1:4-5, Acts 14:22.

[.numbered]
_Query 25._ What are the keys of the kingdom of heaven?
Who hath need of them, and whom are they given unto?
Were they given only to the apostles?
Or only to the ministers of the church?
Are they not given to every one that hath need of them,
to whom God giveth understanding to open the mysteries of the kingdom with them? Matt. 16:19.
The lawyers were blamed for taking away the key of knowledge. Luke 11:52.
Then they from whom they took it should have had it,
that they might have entered into the kingdom of heaven by it,
and not have been hindered from entering for want of it:
and they taking it away from others lost it themselves;
for when Christ came and preached the kingdom, they could not see to enter into it,
but were blind and opposed it. Matt. 23:13.
And now, under the gospel, if any man have not the Spirit of Christ,
he is none of his (he is not the Father`'s child,
who hath not the Father`'s Spirit to lead him.
Rom. 8:4); and he that hath the Spirit of Christ,
hath he not the key of knowledge`"? 1 Cor. 2:10-11.

[.numbered]
_Query 26._ What is the joyful sound, which they that know are blessed?
Is it not the testimony of the kingdom?
Is it not the preaching of the gospel of the kingdom?
which they that repent, and become little children,
being begotten and born of the Spirit,
believing in the Spirit and power of the Lord Jesus, enter into, and walk in,
the light of God`'s countenance there. Ps. 89:15.
Gal. 4:15.

[.numbered]
_Query 27._ Which is the joyful sound of the everlasting gospel to every nation, kindred,
tongue, and people,
after the ages of the great apostasy from the spirit and power of the apostles?
Is it not this, "`fear God, and give glory to him, for the hour of his judgment is come;
and worship the Great Creator in spirit and in truth`"? He that heareth this sound,
in the evidence and demonstration of God`'s Spirit, doth he not hear the gospel?
He that indeed knoweth this sound, doth he not know the joyful gospel sound?
And he that believeth and obeyeth it, doth he not believe and obey the gospel,
even as God hath appointed it to be preached, and obeyed by all nations, kindreds,
tongues, and people? Rev. 14:6-7.

[.numbered]
_Query 28._ What is that kingdom that cometh not with observation, but is inward,
and to be found within?
Where men need not say, lo here, or lo there, but may find the Messiah,
and his light shining in upon them? Luke 17:20-21.
2 Cor. 4:6.

[.numbered]
Query 29. What is that kingdom which stands not in word, but in power;
nor is meat and drink, but righteousness, and peace, and joy, in the Holy Ghost? 1 Cor. 4:20.
Rom. 14:17.

[.numbered]
_Query 30._ What is it to come unto and visit the churches of Christ,
in the fulness of the blessing of the gospel of Christ?
Is it not to come in the fulness of God`'s Spirit and power,
to feed them with the bread of life,
to fill their hearts with the strength and virtue of life from God,
as the Lord shall please to drop it into their spirits through them,
and to build them up in the holy faith,
that at length they may be filled with all the fulness of God? John 21:15-17.
Rom. 15:29. Eph. 3:19.

[.numbered]
_Query 31._ Whom will the Lord assemble?
And whom will he gather to make up his kingdom of, in the days of the gospel?
Will not the Lord assemble her that halteth, and gather her that is driven out,
and her that he hath afflicted?
And will not he make her that halteth, a remnant; and her that was cast off,
a strong nation?
And shall not the Lord reign over them in Mount Zion, from henceforth, even forever?
(For when Christ, the inward and spiritual King,
comes to sit on the throne of his Father David, inwardly and spiritually,
he shall reign over the house of Jacob forever,
and of his kingdom there shall be no end.
Luke 1:32-33) Mic. 4:6-7. Ezek. 34:16.

[.numbered]
_Query 32._ What are the places wherein the sheep of God have been scattered,
in the cloudy and dark day, which the Lord promised to deliver them out of?
And what is the good pasture he will feed them in after he hath delivered them?
And what are the high mountains of Israel, where their fold and fat pastures shall be?
Are not those things to be fulfilled to the spiritual people,
in the inward and spiritual kingdom of the Messiah? Ezek. 34:12,14.
John 10:27,28,3,4,9.

====
