== An Epistle to All Serious Professors / Of the Christian Religion

[.heading-continuation-blurb]
Wherein a brief touch of my knowledge, sense, belief, and experience concerning the godhead,
the offering up of the Lord Jesus Christ in his body on the tree,
as a propitiatory sacrifice to the Father,
and the imputation of his righteousness to those who believe in his name and power,
is nakedly laid before them;

[.heading-continuation-blurb]
Wherein I am not alone,
but one with those who have so learned and experienced the same
in the leadings and light of his Holy Spirit.

[.heading-continuation-blurb]
Written in love to them
(that they might have the better understanding of us, as to these things,
and might not think otherwise either of us, or of the truth of our God,
which we bear witness to, than there is cause, to their own hurt and prejudice)

[.section-author]
Isaac Penington

After it pleased the Lord to touch my heart with the sense of his truth,
and to manifest unto me the principle of his life,
in the demonstration and power of his own Spirit, insomuch as I could reason, dispute,
consider about it no longer, but was fully satisfied concerning it,--I say, after this,
the love of God sprang in me towards you, and pure desires and breathings unto him,
that ye also might have the way cast up before you, and might so walk therein,
as to come to partake of the same mercy and salvation.
How I have mourned before the Lord for you,
and desired that the stumbling-blocks might be removed from you,
and that ye might so seek as to obtain (not in that wisdom and disputing mind,
which still is shut out; but in that meekness, humility, and fear that gives entrance),
the Lord God knoweth.
Yea, the desires in me after you are still living; who knoweth,
but the Lord may at length hear, and with his key so open your hearts,
and so anoint your eyes with his eye-salve, that ye may see, acknowledge, believe in,
and receive the Beloved of your souls,
even as he now appears (after the long night of darkness)
a comforter of the drooping spirits of his people,
with the pure light of life, wherein the redeemed house of Jacob (who sat in darkness,
and in the valley of the shadow of death, mourning after him) now in holy rejoicing,
and pure joy of spirit, walk before him?
Oh! the Lord God visit you, and break in upon you, as he hath done upon us,
and cause you to set to your seals also, as we could not but do,
that this is he whom all our days we waited for, and longed after.
And now there are two or three things in my heart to open to you,
how it is with me in reference to them;
for indeed I have not been taught to deny any testimony
the Scriptures hold forth concerning the Lord Jesus,
or any of his appearances,
but am taught by the Lord more certainly and fully to own and acknowledge them.

The first is concerning the Godhead, which we own as the Scriptures express it,
and as we have the sensible, experimental knowledge of it.
In which "`There are three that bear record in heaven, the Father, the Word,
and the Holy Spirit;
and these three are one.`" 1 John 5:7. This I believe from my heart,
and have infallible demonstrations of; for I know three, and feel three in spirit,
even an eternal Father, Son, and holy Spirit, which are but one eternal God.
And I feel them also one,
and have fellowship with them (through the tender mercy of the Lord) in their life,
and in their redeeming power.
And here I lie low before the Lord in the sensible life,
not desiring to know and comprehend notionally, but to feel the thing inwardly, truly,
sensibly, and effectually; yea, indeed,
this is to me far beyond what I formerly knew notionally concerning them,
and I cannot but invite others hither.

Now consider seriously,
if a man from his heart believe thus concerning the eternal power and Godhead;
that the Father is God, the Word God, the Holy Spirit God;
and that these are one eternal God, waiting so to know God,
and to be subject to him accordingly;
is not this man in a right frame of heart towards the Lord in this respect?
Indeed friends, we do know God sensibly and experimentally to be a Father, Word,
and Spirit, and we worship the Father in the Son by his own Spirit,
and here meet with the seal of acceptance with him.
Nor would we contend with you about your crimes in this respect,
but that you provoke us thereunto, in laying to our charge as if we denied the thing;
whereas we do not, nor can, deny the expressions which the Scripture useth,
nor our own sense and experience concerning the thing.
I pray let this suffice, and let us all strive to know God, and his Son, Jesus Christ,
in his life, Spirit, and power, wherein is unity and true demonstration;
and not contend about such expressions concerning things, as are besides the Scriptures.
For would not ye yourselves think it hard (I mean
such of you as read the Scriptures seriously,
desiring to understand and observe what is written therein) to have a
belief of things imposed on you otherwise than is there written,
and otherwise than ye have the sense, knowledge, and experience of them from the Lord?

The second is concerning the offering of the Lord Jesus Christ,
without the gates of Jerusalem.
I do exceedingly honor and esteem that offering,
believing it had relation to the sins of the whole world,
and was a propitiatory sacrifice to the Father therefor.
And surely he that is redeemed out of the world up to God by Christ,
cannot deny that Christ was his ransom, and that he was bought with a price,
and therefore is to glorify God with his body and spirit,
which are God`'s. 1 Cor. 6:20. And, saith the apostle Peter,
ye know that ye were not redeemed with corruptible things, as silver and gold,
from your vain conversation, etc., but with the precious blood of Christ,
as of a lamb without blemish and without spot, 1 Pet. 1:18-19.
who so offered himself up to God through the eternal Spirit. Heb. 9:14.
This we do own single and nakedly, as in the sight of the Lord;
though I must confess we do not lay the sole stress upon that which is
outward and visible (though we truly and fully acknowledge it in its place),
but upon that which is inward and invisible; upon the inward life, the inward power,
the Spirit within; knowing and experiencing daily, that that is it which doth the work.
The outward flesh is not the meat indeed, nor the outward blood the drink indeed;
but it is the Spirit, the life, the substance,
which the birth that is born of the Spirit feeds upon and lives by.
Oh! consider seriously, and wait on the Lord rightly to understand that scripture, John 6:63.
"`It is the Spirit that quickeneth, the flesh profiteth nothing;
the words that I speak unto you, they are Spirit,
and they are life.`" What doth this scripture lay the stress upon?
Is it not upon the quickening Spirit,
and the words which the quickening Spirit speaketh to the soul, which are living,
and give life to those that hear them?
"`Hear, and your soul shall live!`" Hear his voice who giveth life,
and your souls shall live by him; but can any one live,
without hearing the voice of him who alone is able
to quicken and raise the soul from death,
and out of the grave of sin?

The third thing is concerning the imputation of Christ`'s righteousness,
to such as believe in his name and power, which we have felt, witnessed,
and own to be thus:

God visits men by the light and power of his Holy Spirit, in their dead and dark estate,
even while they are ungodly.
Now, they that feel life, and in the quickenings of life,
by the faith which comes from life, turn to the light and power which visits them,
by this faith in the power, they are in measure transplanted out of the unholy root,
into the holy root, where they partake of the nature and virtue of the true olive-tree;
and the mercy of the Lord in and through his Son Jesus Christ, is spread over them,
and their iniquities are pardoned,
and their transgressions done away for his name`'s sake; and they are reckoned by God,
not as in the old root and unholy nature, but that whereon they lay hold by faith,
and are in union with, they are reckoned by in the eye of the Lord;
and they are accepted and beloved in him in whom they are found,
by him who transplanted them there, and ingrafted them thereinto.
So that Christ is really theirs, and they his;
and what he did for them in his body of flesh is become theirs,
and they have the benefit, and reap the sweet fruits of it.
And if they sin afterwards, they have an advocate who pleads their cause with the Father,
and who breathes livingly upon them again, and quickens faith in them,
and gives them to turn from that which ran after them,
and overtook them and defiled them.
So that in this state of true faith in, and union with, the Son,
the fountain is felt set open for sin and for uncleanness,
which daily washeth away the pollutions and stains of the mind,
which it is liable to in the travelling state.

But now to every faith this doth not belong,
but to the faith only which flows from the power of the endless life,
and which stands in the power.
The faith which is from the power is precious, having a precious nature and virtue in it,
and very precious effects flow from it.
For it is the substance of things hoped for; it is of a pure nature, which hath dominion,
and giveth dominion over the wicked one.
There is no overcoming of the saints here; for as it came from the power,
so it stands near the power, and engages the power of life against the enemy,
and so is still too hard for him.
For he that resisteth the enemy in the true faith,
still overcomes him, and makes him fly. James 4:7.
But that belief on Christ, and applying his righteousness,
which is not of this faith, nor in the true light of life,
but according to the creature`'s apprehensions concerning things,
that is not of the same nature with this, nor hath the same virtue,
nor produceth the same effects; but notwithstanding such a believing and hoping,
men are still in their sins,
and they are not washed away from them by the blood of Christ,
nor remitted or covered by the Spirit of the Lord.
And oh that men were wary, and did take heed in this matter,
that they might not miss of true pardon from the Lord,
and so find their sins bound by him, in the days of his refreshing others!

For there is a state,
wherein there is an imputation of Christ`'s righteousness
to persons reached to by the power of the Lord,
and coming up out of the ungodly state, and so a real bringing into the righteousness.
For in the true growth the soul daily grows more and more out of its own unrighteousness,
out of the dark, corrupt image, into the righteousness of Christ,
and into his pure image.
Thus Christ is formed in the hearts of them that truly believe, daily more and more;
they receiving him as a heavenly leaven, and giving up to be leavened by him,
are changed daily more and more into the newness of Spirit,
even until they become a new lump, even a lump wholly leavened,
so that old things are passed away, and all things become new; that is,
not of old Adam any more, but all of God in Christ, all of the new nature and Spirit,
which is all of it righteous in the sight of God.
Now, this is it all should labor for and seek after,
even the kingdom of God and his righteousness,
to find an entrance ministered to them into the everlasting kingdom,
and the righteousness thereof,
that they might really put off the old man with his affections and lusts,
and put on the new man; the new man`'s nature, the new man`'s image, the new man`'s spirit,
the new man`'s righteousness, the new man`'s holiness;
that they might have the wedding-garment on to be married to Christ in,
and might be as a bride prepared for the bridegroom.
Oh, it is precious for any one to feel his soul in this state!
And who would not travel and wrestle and strive and watch and pray and wait,
that he might be thus fitted by the Spirit of the Lord for his Son Jesus Christ?
For, friends, there is a coming under grace, under grace`'s wing,
and out of shame and confusion because of sin, into the glory which is in the pure image;
and there is a being changed from grace to grace, and from glory to glory,
by the Spirit and power of the Lord.
Oh that such as take upon them the profession of Christianity might feel the power,
and wait upon the power, and know what it is to believe in the power,
and live in the power; for without this, the oppressed state of Christianity is but dead,
dry, and cold, not having the true living sap and warmth in it.
There are great deceits in the world about these things,
but he that knoweth the truth as it is in Jesus, who was visited by the power,
gathered to the power, and abides in the power,
he hath that with him which anoints his eye and heart,
and strengthens them against the most subtle devices
and deceits of the transforming spirit.
But whoever he be that professeth Christianity, and is not here, he is not safe,
but the enemy hath ways of bewitching and deluding him,
which he hath not wherewith effectually to withstand and avoid.

Now, having nakedly expressed these things to you, as they are in my heart,
there is a question lies before me to propound to you,
which deserves your serious consideration of,
and ability to answer in the sight of the Lord, which is this:

[.discourse-part]
Question.
Do ye rightly, truly, and fully (as the Lord requireth of you) know, esteem,
and honor the Son?
Do ye own him as God hath revealed him in the spirit of his children, since the apostasy?
Do ye feel him as a horn of salvation lifted up there?
Do ye find and experience him revealed within by the Father, as the seed of the woman,
bruising the head of the serpent?
Oh! this is precious knowledge,
and the right way of truly knowing him as he came from the Father,
lived in obedience to him, suffered for the sins of the whole world,
ascended again to the Father, and now sits with him in glory!
For, indeed, it is the chief thing, and that whereon the soul`'s rest depends,
to know and feel him near.
Oh that we were one here (I mean in the inward sense
and acknowledgment of the Lord Jesus Christ),
and we should soon be one in the other also!

For we, who are reproachfully by many called Quakers,
are (for the most part) a people who have much and long sought after the Lord,
and after the experimental knowledge of those truths,
which are testified of and related in the holy Scriptures.
We sought not after a new Christ, or a new Spirit,
or new doctrines concerning Christ or his Spirit; but to know Christ,
so as to receive life from him,
and to live to him in the life and spirit received from him;
this hath been the single aim and desire of our souls.
And if men could with patience consider what we hold forth,
and wait till God open their understandings,
they would not lay such blame upon us as they do in many respects,
but find that we reverence the Scriptures,
believing and holding concerning the things of God according as is there expressed,
from a true understanding received from the Lord,
and in the true light and guidance of his Spirit.
There is another question springs in my heart unto you,
I beseech you consider of it seriously, perhaps there may be a blessing to you in it.

[.discourse-part]
Question.
Do ye rightly and weightily consider and embrace that counsel of Christ, Matt. 6:33.
"`Seek ye first the kingdom of God,
and his righteousness`"? Do ye mind what Christ likens the kingdom to?
Even a grain of mustard-seed, a pearl hid in a field, a little leaven,
a lost piece of silver, etc.
Do ye know, and are ye acquainted with that little thing which is like unto these?
And do ye really and rightly seek after it?
Do ye seek it where it is to be found?
Do ye know the place where it is hid?
And do ye take the right way to buy and purchase it?
How is that?
Why not by outward observation, saith Christ, but by inward sweeping the house;
by keeping the eye upon it, and sweeping out the rubbish that covers it;
this is the way to find it, purchase it, and possess it.
Oh that ye could all learn thus, and be thus exercised by the Spirit of the Lord daily.
Surely they that thus seek shall find, and they that thus ask shall have,
and they that thus knock, to them the everlasting kingdom shall be opened.

For mark the difference between the state of the law and gospel.
The law was a shadow of good things to come.
The gospel is a state of enjoyment of the good things shadowed out under the law.
The law was a type of the kingdom, of the spiritual kingdom of Christ,
which is set up under the gospel.
In John`'s day the kingdom was at hand;
but in the day of Christ`'s power the kingdom is come.
Under the law there was a tabernacle pitched by man;
but under the gospel the true tabernacle and temple is witnessed,
which God pitcheth and not man; and the holy, spiritual, heavenly sacrifices,
and the living covenant, whereof Christ is the mediator,
and the law written in the heart, and the Spirit of the Lord put within,
so that his presence is as really witnessed inwardly,
in that which is truly his tabernacle and temple now, as ever it was witnessed outwardly,
in his outward tabernacle and temple under the law.
Oh that Christians might not have the name only,
but might be in the life and in the power,
wherein these things are felt and experienced! for indeed,
the wonders of the Lord are seen in his temple, and his name is praised there, Selah.
There he breaks the shield and the bow, the spear and the battle, Selah.
There the enemy is overcome; the holy victory that bringeth him under,
issueth out thence, Selah.
There the well is opened, and the Philistine nature hath power to stop it no more, Selah.
There the treasury of life and wisdom,
and the riches of God`'s goodness are made manifest forever.

Truly, friends, I have not lost any thing that ever I had,
or acknowledged of God in the days of my former profession,
by believing in the light which God hath now revealed in me, but have it still with me,
and in greater clearness and plainness, and fuller demonstration than I then had it;
but that of the flesh which mixed with it,
and hindered it from being rightly serviceable to the Lord, and fully comfortable to me,
that the Lord hath been removing by his searching light,
and by the demonstration of his Spirit and power.
And if at length, after all my deep and long misery,
the Lord hath given me to meet with and enjoy that which is truly excellent
(among those whom men despise) I could heartily wish for you,
that ye also might meet with and enjoy the same,
without passing through that misery and bitter anguish and distress of spirit,
through which the Lord led me thereto.
The Lord preserve his people, by the arm of his mighty power,
which he hath stretched out for them, and whereby he hath gathered them to himself.
And those which are not yet of this fold, oh that it would please him to seek them out,
and bring them home also; that the Lord may be one, and his name one amongst us,
and that that which divideth and scattereth from the living truth,
might be scattered and brought to nought everywhere, in all who would be one,
and desire to serve God (with one consent) in that which is true and pure!
Amen.
