[short="Concerning Gospel-Baptism"]
== A Reply to an Answer of Some Queries Concerning the Gospel-Baptism

[.section-author]
Given forth by me, I. P.

[.heading-continuation-blurb]
With answers to some queries
returned, in a paper subscribed N. B.

[.section-date]
1679

[.discourse-part]
_Query 1._ Which is the gospel baptism, or of what kind is the baptism in the gospel state?
Is it outward or inward?
Is it the figure of the inward baptism, or the inward baptism itself?

[.discourse-part]
N+++.+++ B.`'s answer is, "`It is a stooping to God`'s law.`"

[.discourse-part]
_Reply._ This is a very improper answer, and not at all to the thing in hand;
for the query was not concerning the stooping or subjecting to baptism;
but what the baptism is, which is to be stooped and subjected to,
whether that be an inward or outward baptism?
Whether it be a figure of the holy and heavenly baptism of the gospel,
or the holy and heavenly baptism itself?
So that in these words, there is no answer at all returned to the query,
but rather the asserting of another thing, which the query did not mention,
altogether improper in this place;
for the query tends to determine what the baptism itself is,
and when that is once determined, about stooping and subjecting to it,
there will be no question I hope between us.

[.discourse-part]
Now, to explain what this law of God is, which is to be stooped to, he saith,
"`It is the law of the Spirit of life in Christ;`" quoting to prove it, Rom. 8:2.
Matt. 28:18-19. Mark 16:16.

[.discourse-part]
_Reply._ That baptism (water-baptism),
as he afterwards expresseth it in his answer to this query,
is the law of the Spirit of life in Christ Jesus, I never read in scriptures.
Nor doth it effect in the heart what the law of the Spirit of life in Christ Jesus doth,
which the apostle saith, made him free from the law of sin and death;
and it hath virtue and power in its nature over the law of sin and death,
which water-baptism hath not.
The law of sin and death is of an inward and spiritual nature;
and the law of the Spirit of life also is of an inward and spiritual nature,
stronger than the law of sin and death,
and is able to make free from the law of sin and death inwardly.
But water-baptism is an outward thing, an elementary thing,
not able to reach the law of sin and death, nor to make free from it.
I beseech you consider,
ye who look upon this to be a command and ordinance of our Lord Jesus Christ, are ye,
or are they, who are outwardly baptized with water,
made free from the law of sin and death thereby?
Nay, Paul himself,
who was by the law of the Spirit of life in Christ
Jesus made free from the law of sin and death,
yet was not made free so by outward baptism.
For if he was outwardly baptized (as I am ready to believe he was,
it being usual at that time), it was when Ananias came to him,
and when the scales fell from his eyes, and he received sight. Acts 9:18.
But he was not then made free from the law of sin and death; for afterward,
in his inward and spiritual exercise and holy travail,
he found and complained of a law in his members, warring against the law of his mind,
and bringing him into captivity to the law of sin in his members. Rom. 7:23.
This was not a state of freedom from the law of sin;
for with his flesh he still served it, while in this state.
But when by the Spirit the flesh was crucified,
when the law of the Spirit of life in Christ Jesus
prevailed over the law of sin and death in his members,
then he was no longer under Satan`'s captivity by sin, but a delivered man,
made free therefrom by the law of the Spirit of life in Christ Jesus.
Then he knew the truth, and the power and virtue of the truth manifested itself in him,
and made him free, and he was free indeed;
and said no more he could not do the good he would,
nor forbear doing the evil he would not; but he was more than a conqueror over the evil,
and set at liberty to work righteousness,
and could do all things through Christ that strengthened him.
Oh that ye that plead so much for outward water, knew this law writ in your hearts,
and the effectual power and virtue thereof freeing you from the law of
sin and death! and then ye would no more attribute that to an outward
thing (or to your obedience as to such an outward thing),
which belongs to the Spirit and power of the Lord Jesus,
and to the law of his life inwardly written in the heart.

[.discourse-part]
Another scripture he brings to prove water-baptism
to be the law of the Spirit of life in Christ Jesus,
is Matthew 28:19.

[.discourse-part]
_Reply._ If it were granted, that Christ did in that place command water-baptism,
yet that would not prove it to be the law of the Spirit of life in him.
The law of the Spirit of life in him is a deep thing (I beseech you do not mistake it),
and hath mighty effects in the soul, which water-baptism never had,
nor can have upon any.
The law of the Spirit of life in Christ Jesus,
hath that virtue and power from God in its nature, which water-baptism is not capable of.
The figures, the outward representations, have not a capacity to receive that from God,
which the inward law and substance hath.

But that outward baptizing with water is there commanded by Christ,
is not at all manifest from that scripture, but rather the contrary,
if it be well-minded.
For Christ saith, all power was given him in heaven and earth,
and bids them go and baptize.
Doth he say with water?
Nay; doth he not say into the name of the Father, Son, and Spirit?
So that now, when the gospel is preached in the Spirit and power of God,
and his Spirit and power reacheth to our hearts,
we are by that Spirit and power both taught and baptized inwardly,
gathered into the name of the Father, Son, and Spirit, and baptized into their name.
And he that doth this in the heart, teacheth the heart to call this the gospel baptism;
and to call that which came forth in the hand of the forerunner, the type,
or figure of this, the representation of this, the shadow of the gospel baptism,
but not the gospel baptism itself.
Indeed, we dare not call John`'s baptism, or water-baptism, the gospel baptism,
or Christ`'s baptism; the Lord, who hath manifested things to us,
and taught us to put a difference between things that really differ,
would judge and condemn us for so doing.

Mark further, Christ, who saith,
"`All power in heaven and earth is given me,`" and therefore bid them go teach and baptize,
yet withal bid them wait for the same Spirit and power which was given him. Acts 1:4-8.
And then having his Spirit and power,
wherewith he inwardly taught and baptized,
might they not be able therewith to reach the heart and conscience,
and spiritually both to teach and baptize, as instruments in God`'s hand,
in the springings of his life and power in them?

Now to manifest this further; for I feel the Lord opening my heart in this thing,
and I hope it is for your sakes,
(O ye mistaken ones in this weighty business!) that
the Lord may explain things of this nature to you,
and do you good thereby.
To whom was this commission or command, in the authority and power of God`'s Spirit given,
to go and teach all nations, baptizing them into the name, etc.?
Was it not especially given to the apostles, who were especially gifted thereunto?
And was not Paul one; yea, one of the chief, made so by God our Father,
and the Lord Jesus Christ?
And he being in a special manner sent to the Gentiles,
or Heathen nations (for the Jews were but one nation),
did not this commission extend to him, and this command lie upon him?
Now, if this command did extend to inward, spiritual, gospel baptizing,
with the Spirit and power of the Lord Jesus, he had it as full as any of them;
but if it be understood of water-baptism, we do not find that he had any such commission,
but rather otherwise.
Read his commission, Acts 26:18. is there any thing of water-baptism in it?
There is remission of sins, which depends upon believing and turning to God,
in his illuminating Spirit and power, but nothing of water-baptism.
And mark, it is God that opens men`'s eyes, and it is God that opens their hearts,
and inwardly turns them from darkness to light, and Satan`'s power to God;
yet Paul was sent by the Lord to do this.
And is it a harder matter inwardly to baptize than to do this?
So that it is not Paul, but the Lord that opens the eyes, and turns men;
yet the Lord sent Paul to do it, and surely the Lord enabled him,
by his Spirit and power, to do what he sent him to do.

[.discourse-part]
Objection.
But though it is not here particularly expressed, yet it may be implied or intended.
Or if this commission did not reach to him, the former apostolic commission would,
he being made so extraordinary an apostle.
Or at least it would reach him as a teaching disciple;
for he that hath authority to teach the nations, hath also authority to baptize them.

[.discourse-part]
Answer.
No, Paul neither by this commission, nor by the apostolic commission,
nor by his discipleship, had any authority or mission from God to baptize,
if ye take baptism in this place for baptizing with outward water,
as he himself expressly saith,
"`Christ sent me not to baptize (speaking of water-baptism),
but to preach the gospel.`" 1 Cor. 1:17. Nay,
he thanks God that he baptized none of them, to his remembrance, but Crispus, Gaius,
and the household of Stephanus, ver. 14,16. Now,
if he had looked upon water-baptism as Christ`'s ordinance,
and as the law of the Spirit of life in Christ Jesus,
would he thank God he had obeyed it no more?

[.discourse-part]
Objection.
But he gives the reason of that, lest any should say he had baptized in his own name.

[.discourse-part]
Answer.
Why, persons might say he preached in his own name,
yet that would not have excused him from preaching.
No more would men`'s saying he baptized in his own name excuse him from baptizing,
if water-baptism had been Christ`'s command and ordinance.

[.discourse-part]
The last place he brings to prove water-baptism to be the law of
the spirit of life in Christ Jesus is Mark 16:16. "`He that believeth,
and is baptized, shall be saved; but he that believeth not, shall be damned.`"

[.discourse-part]
_Reply._ This showeth the necessity of the gospel baptism,
but this doth not express which the gospel baptism is,
whether an inward or outward washing.
We know, having been taught by the Lord,
that there is no salvation without inward washing,
which is also very demonstrable to others; but God forbid that all should be damned,
that are not baptized with outward water.

[.discourse-part]
He saith, "`This law was confirmed by them that had the Spirit-baptism,
being commanded to be obeyed by them that had the Spirit.`" Acts 10:47-48.

[.discourse-part]
_Reply._ That Peter did command persons to be baptized with water, and that John`'s baptism,
or water-baptism, was made use of in those days, and that John had it from God,
and that it was done in God`'s name, this is not denied;
but that water-baptism was Christ`'s baptism, or the gospel baptism,
this place doth not prove.

[.discourse-part]
He saith, further,
"`The kind of this baptism is water-baptism,`" bringing Matt. 3:16.
and Acts 8:38-39. to prove it.

[.discourse-part]
_Reply._ Matt. 3:16. only proves that Christ was baptized with water,
but doth not prove that water-baptism is the gospel baptism.
If I could prove by scripture expressly, that Christ was circumcised,
yet that would not prove that therefore that was to be the gospel circumcision.
So though it be manifest, that Christ was baptized by John, with his water-baptism,
yet that doth at all prove that John`'s water-baptism is Christ`'s gospel baptism.
The end of John`'s baptizing with water was, that Christ might be made manifest. John 1:31.
And when he is made manifest (when he who is the word, who is the life,
is made manifest, 1 John 1:1-2) then men must come to him,
to be baptized by him with his baptism, which is with the Holy Ghost, and with fire, Matt. 3:11.
or with the Spirit of judgment and burning. Isa. 4:4.

That other place of Acts 8:38-39. doth not at all
prove that water-baptism is the gospel baptism,
but only that Philip did baptize the eunuch with water,
which is not a thing denied by us.
Yea, what if I should grant, that the Lord did honor it as much as any shadow,
or more than other shadows, by letting it have a longer time, and otherwise;
yet that will not prove it to be Christ`'s baptism, or a gospel ordinance.
And if men do take it up in tenderness of spirit, bowing to the Lord,
it is so much the better; yet it is not easy to believe that all do so;
and those that do so, may err in their judgments, notwithstanding; though I am persuaded,
the Lord is tender to persons that do things in tenderness of heart to him,
notwithstanding some error or mistake in their judgments.

[.discourse-part]
_Query 2._ What is it that is to be washed in the gospel state?
Is it the outward or inward man?
And what is the inward man to be washed with?

[.discourse-part]
Answer.
His answer is, "`it is the body, the whole man or woman to go into the water,
in the name of the Father, Son, and Spirit;
so that the soul comes to be sanctified by the word and Spirit.`"
For the proof of which he quotes John 3:23. and chap.
15:3.

[.discourse-part]
_Reply._ That the whole body was to go into the water, according to John`'s baptism,
is granted; but that this is the gospel baptism, or Christ`'s baptism, is denied by us.
It is the inward Jew that is to be washed in the gospel state, and it is inward water,
spiritual water, that he is to be washed with.
I pray consider that scripture seriously,
(and the Lord give you the true understanding thereof) Zech.
13:1. Doth not that scripture speak of the gospel state?
What fountain is it that is opened in the gospel state?
Is it an outward fountain of outward waters, which is opened for sin and for uncleanness,
to wash it away?
The Lord knoweth of what nature sin is, and with what water it is to be washed away,
and therefore openeth that fountain in the house of David in the gospel state,
which is proper to wash it away with.
What is the house of David?
Who is the Jew in the gospel state?
What is the tabernacle or house of David that is raised up then?
What is the fountain that is opened there for sin, and for uncleanness?
Can sin be washed away from any heart and conscience, but by the water of this fountain?
And is not the gospel baptism with this water?
Do not those that are washed with this water feel the true washing,
and know it certainly, evidently, infallibly, in the demonstration of God`'s Spirit,
to be the true baptism; not the figurative, outward washing of the body,
but the real inward washing of the soul?
There is the washing of regeneration, Tit. 3:5. which is with that which regenerates,
which the water of the fountain of life and holiness doth, which God opens in the heart,
and washeth the soul with, and causeth the soul to wash in; but the outward water,
which washeth the outward body, hath no such nature or virtue in it,
nor ever was appointed by God to produce any such effect.
That the soul is sanctified by the Word and Spirit, is granted:
but that the soul is not sanctified by the Word and Spirit,
unless the body is washed with outward water, that is denied;
and the scriptures afore mentioned by him, of John 3:23. and chap.
15:3. do not at all prove any such thing.
Now, the gospel obedience is to Christ`'s baptism, not to John`'s baptism.
And the soul that is subject to Christ`'s baptism, doth not live in disobedience,
for not taking up John`'s baptism; which God doth not allow him to do;
but in the gospel state, every one is to hear the Son, the Shepherd of the soul,
and follow him the substance, and not Moses`'s circumcision or John`'s baptism.

[.discourse-part]
_Query 3._ What is washed away by the gospel baptism?
Is it the filth of the outward body or flesh?
Or the filth of the soul?
And with what water is the filth of the soul to be washed away?

[.discourse-part]
Answer.
"`Sin is washed away by the gospel baptism;`" for the proof whereof he quotes. Acts 22:16.
Rom. 6:17-18.

[.discourse-part]
_Reply._ Thus far we agree, that sin is washed away by the gospel baptism;
but what that baptism is which washeth away sin, herein we greatly differ.
He affirmeth it to be outward water, and the washing of the outward man therewith.
I affirm it to be inward water, from the inward,
holy fountain which God opens in the house of David,
whereby the soul and conscience is washed from sin, and uncleanness.
That place of Acts 22:16. speaks of Paul`'s being baptized, and washing away his sins;
but doth not say,
that outward washing the body with outward water is the washing away of sins;
but bids him wash away his sins, calling on the name of the Lord.
And thus the washing away of sins is at this day experienced.
The Lord manifests sin, turns the mind against it, and causeth a cry to the Lord,
and then the Lord opens the fountain, causeth the pure water to flow,
which the soul is washed with; and so far as it is washed therewith,
it is clean in the sight of God,
and hath the inward sense of its cleanness from the Lord.
Yet that there was a figurative washing away of sins by John`'s baptism, I do not deny;
for it was unto repentance, and they thereby professed repentance,
and were to "`bring forth fruits meet for repentance.`" Matt.
3:8. Nor doth that other place (Rom. 6:17-18) prove,
that washing the body with outward water washeth away sin, or maketh free from sin;
but that which makes free from sin, is the power, virtue,
and life of truth felt in the heart, washing and cleansing it.
It is receiving the truth in the love of it, and being moulded into the nature of it,
believing it in the evidence and demonstration of God`'s Spirit,
and obeying it in the obedience of the new nature, mind, and Spirit.
And the answer of a good conscience comes from the inward baptism,
// lint-disable invalid-characters
from the washing which the apostle calls Αντιτυπους, the anti-type, 1 Pet. 3:21.
which baptism is not the washing away the filth of the flesh or body;
but an inward baptism, which so washeth inwardly,
that the answer of a good conscience is presently felt, in the sight and presence of God.
And then the soul knows what water it was washed with, which was able to produce,
and did produce this effect.

[.discourse-part]
He saith, "`And thus it appears; First it takes off disobedience.`"

[.discourse-part]
_Reply._ What is it takes off disobedience?
The truth as it is in Jesus, the life and power of truth, felt and working in the heart,
destroys the disobedient nature, and takes away the disobedience thereof;
but outward washing of the body doth not,
though men may apprehend there is an outward command for it,
and judge they do it in obedience to that outward command.
But obedience is from true understanding of the mind and will of God,
and from that holy light of his Spirit wherein the holy understanding is given.
And in this obedience the Lord`'s justification is witnessed;
which is not witnessed in the other;
I mean in that which men call obedience to that which they account a literal command,
according to their conceivings and apprehensions.

[.discourse-part]
"`Secondly,
As it leads persons unto Christ;`" for which he quotes Rom. 6:2-3. Gal. 3:27.

[.discourse-part]
_Reply._ That which leads unto Christ, and into the truth as it is in him,
the children of the new covenant know, who are drawn by the Father,
and are taught and learn of him to come to the Son. John 6:44-45.
And how can we give that honor to John`'s baptism,
or outward washing the body, which belongs to the Father, and his powerful Spirit?
To be baptized into Christ is a great thing.
To be buried with Christ by baptism into death is a precious state,
and effected by the inward work of the Spirit in the heart, working against sin,
working the mind out of sin, into the nature, Spirit, and life of Christ.
And the being baptized into Christ is the real putting on Christ.
It is the effect of knowing the truth as it is in Jesus,
which causeth the putting off of the old man, and the renewing in the Spirit of the mind,
and putting on the new. Eph. 4:22-24.
But John`'s baptism, or the washing the body with outward water,
doth none of these things,
but is only a type or representation of what is done in and by the inward baptism.

[.discourse-part]
He adds further, "`And so the soul receives Christ in his prophetical and priestly office;
so by Christ we are delivered from all filthiness of flesh and spirit,
that we may perfect holiness in the fear of God.`"

[.discourse-part]
_Reply._ The kingdom of Christ is spiritual, the kingdom of Christ is within,
and he that would truly know him as he is King, Prophet, and Priest,
must hear his knocks, know his voice, open to him, and let him in,
and then he will manifest himself there, and the soul shall know what he is,
even his King, Priest, and Prophet, and feel him exercising all these holy offices,
in the authority and power of his Father, in the heart.
This is precious knowledge indeed.
Yea, he shall know him with his fan in his hand,
thoroughly purging his floor from all unbelief, from all disobedience,
from all chaffiness and earthliness; yea, from all filthiness of flesh and spirit;
for his fan turns against them all,
and his Spirit of judgment and burning flames inwardly against them all;
and as they are consumed and burnt up,
the pure fear of the Lord is increased in the heart, wherein holiness is begun,
and at length perfected, by the thorough circumcision and baptism of the Spirit.
But the Corinthians were not cleansed from all filthiness
of the flesh and spirit by water-baptism,
but were afterwards exhorted by Paul to do it.

[.discourse-part]
Query 4. What water is it that the inward Israel shall be sprinkled with,
that they may be clean?
Is it not inward water, spiritual water?
And can any be clean or baptized in the sight of God,
that are not baptized with this water,
wherewith God sprinkleth and washeth his inward and spiritual Israel?

[.discourse-part]
Answer.
"`Baptism is not sprinkling, nor so rendered by the Spirit, but baptize;
baptize is to dip or put into the water.`"

[.discourse-part]
_Reply._ When God sprinkleth his inward Israel,
with the water which he hath promised to sprinkle with,
he doth sufficiently cleanse them; for whom the Lord sprinkleth with this water,
they are cleansed thereby. Ezek. 36:25.
And this relates to the gospel state;
for a new heart is immediately promised,
ver. 26. which is the promise of the gospel covenant.
And the blood of sprinkling in the new covenant doth sufficiently wash and cleanse, Heb. 12:24.
Rev. 1:5. sprinkling and dipping are but figures;
but they are both comprehended in the substance,
which we should wait inwardly to feel and experience.
The water which Christ speaks of, John 3:5. (which place he quotes) is not outward,
but of the same nature with the Spirit, whereof the soul is washed and born again,
and riseth up in the new life with Christ.

[.discourse-part]
He saith, "`The inward fits for the outward.`"

[.discourse-part]
_Reply._ It is true,
John`'s baptism did require inward qualifications (in which respect it went beyond circumcision),
and so, where those qualifications were found, who could forbid water?
But Christ`'s baptism, the baptism with Spirit and fire to purify the mind,
and burn up the dross, is of a higher ministration,
and a far more glorious baptism than that. Matt. 3:11.
"`He shall baptize you:`" you, what you?
You whom I have baptized with water?
So that those whom he hath baptized to repentance, he tells of another baptism,
a more glorious baptism than his, which happy are they that wait for,
and feel accomplished in them.

[.discourse-part]
_Query 5._ What is the gospel circumcision?
Is it not an inward and spiritual circumcision?
And is not the circumcising knife, wherewith the inward Israel is circumcised,
inward and spiritual?
And is not the gospel baptism, wherewith the inward Israel is washed,
as inward and spiritual as the gospel circumcision?
Is not this circumcision and washing of the same nature,
and effected without outward hands?

[.discourse-part]
Answer.
"`It is inward, spiritual, heavenly,
that which God works by the knife of his word.`" Heb. 4:12. Hos. 6:5.

[.discourse-part]
_Reply._ This is true; we whom God hath called, quickened, enlightened, circumcised,
and baptized, experience it so; and happy is he, if he experience it also.
For the word is living, and makes alive; the word is quick and powerful,
sharper than any two-edged sword,
and it doth inwardly pierce to the dividing asunder of the soul and spirit, (oh,
this is a blessed experience inwardly,
wherever it is felt!) and of the joints and marrow,
and is a discerner of the thoughts and intents of the heart.
And this word came to the prophets, and did hew through the prophets,
and God`'s judgments by this word were as a light that went forth.
This word is the word of life, and the life is manifested in it,
as the apostles knew in their day, 1 John 1:2.
and as God`'s gathered ones know in this day.

But let him take heed, lest he put the letter,
or outward descriptions of heavenly things, for the word;
for the kingdom or gospel state stands not in such kind of words, but in power, 1 Cor. 4:20.
and the apostles were made able ministers of the New Testament, not of the letter,
but of the Spirit; for the letter killeth, but the Spirit ministereth life. 2 Cor. 3:6.
So we distinguish the word of life (the quick,
piercing word that giveth life), from the words which came from it, Acts 5:20.
which words are also living, as they come from the life,
and are livingly spoken to the heart by him, who is the life; otherwise, in the mouth,
understanding,
or comprehension of him who is not living (nor in
a true sense and understanding of them),
they are not life.
So men should not strive to comprehend things with that outward understanding,
which can never attain thereto, but wait to receive the understanding from God,
whereby they may know him that is true, and his gospel ordinance,
and the holy laws of his kingdom,
and be found in the obedience thereof to him in the Spirit.

Now, granting the gospel circumcision to be inward and spiritual,
how can he make the gospel baptism to be of a nature inferior to it,
even outward and carnal; viz., a washing with the elementary water of this creation,
and not with the inwardly sanctifying and cleansing water of life,
which God sprinkleth upon his spiritual Israel, and also plunges their souls into?
And consider seriously, whether the apostle,
speaking of both circumcision and baptism, Col. 2:11-12.
did intend either of them as to the outward,
and not rather both of them as to the inward, wherein the true, inward,
spiritual circumcising, and also the true, inward baptizing, is witnessed,
and both without hands;
for neither circumcision nor uncircumcision avails
(no more doth outward washing the body,
or not washing it avail), but a new creature;
the putting off the body of the sins of the flesh
by the circumcision and baptism of Christ,
this avails, and is of great esteem with God.

[.discourse-part]
_Query 6._ What is the one baptism of the spiritual Israel, without which,
there is no salvation?
Can there be any salvation without the inward washing of the soul?
May there not be salvation without the outward washing of the body?

[.discourse-part]
Answer.
"`That which Christ Jesus commanded; for there is but one baptism commanded,
and that leads us to Christ and God.`"

[.discourse-part]
_Reply._ Was not John`'s baptism commanded, which was an outward washing?
And is not the inward washing commanded also?
Was not Israel commanded to circumcise their hearts,
and was not that an inward circumcision?
And were they not also commanded to wash their hearts from wickedness,
and was not that an inward washing or baptism?
How could they do either of these?
Why, did not Moses direct them to the word nigh in their mouth and heart,
whereby both these might be done?
And can either of these be done in any heart,
but by the operation of this word of life inwardly in the heart?
We know, There is no other name under heaven, nor way to be saved, but Christ,
the word of life, and light of men.
But they that are saved by him, must know him as a living stone within,
and come from all else in their hearts to him (as
to a precious foundation-stone of life),
and be new-created by him, circumcised and baptized into him, and so walk in him,
the new and living way, and serve God his Father, in the newness of the Spirit,
and not in the oldness of the letter; which happy are they that understand what it is,
and are found in this obedience to the Lord,
and in thus worshipping him in his Spirit and truth,
which is the gospel service and worship.
For men may easily mistake about the letter;
but the new birth doth not mistake concerning the Spirit,
nor the true sheep concerning the voice of Christ.

[.discourse-part]
_Query 7._ How are men buried with Christ by baptism into death?
Is it not an inward, spiritual death, that men are thus buried with Christ into?
And is it not effected by an inward, spiritual baptism?

[.discourse-part]
Answer.
"`By water-baptism; for Christ was buried, so are we.
Christ was buried by baptism in the water, so are we.`"

[.discourse-part]
_Reply._ Christ was outwardly circumcised; so are we also circumcised; not outwardly,
as Christ was.
Christ was not circumcised to effect any thing upon him (for he needed it not),
but for our sakes.
And he was baptized for our sakes also, that we also might be circumcised,
and baptized with the circumcision and baptism which we need,
which is the circumcising and baptizing of our souls,
and not the circumcising or washing of our bodies.

[.discourse-part]
He adds, "`Christ did it to fulfill all righteousness;
we to fulfill the righteous law and will of God,
we thereby entering into covenant with God,
whereby we set to his seal +++[+++I suppose he means, our seal], that he is true.

[.discourse-part]
_Reply._ It remains yet to be proved,
that baptizing with water is God`'s law and will in the gospel state.
I am sure there are those that are taught otherwise by him that teacheth all his children,
from the least to the greatest, in the new covenant.
And the new covenant is an inward covenant; which they that hear God`'s voice therein,
and have his law written in their hearts, and obey it, are led by him more and more into.
Now, the new covenant is not made with every thirsty one after the living waters,
but only such as come to Christ in the drawings and teachings of his Father;
and when they are come to Christ, incline their ears, and hearken diligently to him, Isa. 55:1-3.
such assuredly know and enjoy the sure mercies of David,
having God to be their Shepherd to spread their table for them;
and they eat that which is good, and are satisfied with the fat things of his house,
and so can set to their seal that God is true and faithful,
who hath not only promised such things,
but is daily fulfilling and making them good in and to their souls.

[.discourse-part]
_Query 8._ What is that baptism,
from whence there certainly and constantly ariseth
the answer of a good conscience towards God?
Doth not this always arise from the inward baptism,
from the washing away of that which defileth the conscience?
Is not then the conscience thereby made good and holy in the sight of God?
And doth it not then answer the holy will, law, and Spirit, of the holy and good God?

[.discourse-part]
Answer.
"`The baptism of water; being that which Christ commanded.`"

[.discourse-part]
_Reply._ Water-baptism, or outward washing of the body, cannot make the conscience good;
for a man may do that upon a mistake, through error of judgment,
and go unchanged into it, and come unchanged out of it.
But the inward circumcision and inward baptism,
doth really cut off and wash away the sin and filth of the conscience,
and so make it good; and then the good conscience doth answer to God,
in what he teacheth and requireth.
But that water-baptism was commanded by Christ, is still denied on our part,
and unproved on his.

[.discourse-part]
He saith, "`A clear conscience ariseth from a true conformity to the law of God.`"

[.discourse-part]
_Reply._ This is very true.
But what is the law of God in the new covenant, but what he writes in the heart?
God is the teacher of his people in the new covenant,
and what he teacheth and requireth of them by his Spirit, is their law.
Christ is their law-giver, and he gives forth his law of life, from his Spirit of life,
to those that wait for it. Isa. 42:4.
And he likewise opens the Scriptures,
and shows what God taught and required of former ages, and of this present age.
He shows what the shadows of the law were,
and what the ministration of the prophets and John was,
and what the ministration of the Son is;
who is faithful in all his house to every one there, as a Son,
to give the law of the Spirit of life to them; even as Moses, the servant,
was to give the outward law to those of his house.
So that it is not sufficient to read a scripture, or scriptures,
and say this was commanded, and this was practiced of old;
but to wait to know how it was commanded, and how practiced, and of what nature it was,
whether of the everlasting nature of the kingdom, which is to remain; or of an outward,
elementary nature, which might be shaken and pass away.
For it was the will of God, that all such things should be shaken and pass away,
that the kingdom itself alone, which cannot be shaken, might remain. Heb. 12:27.

[.discourse-part]
_Conclusion._
Oh that people knew and experienced the baptism which is the substance,
and then they would not idolize that baptism, or outward washing,
which in its nature can be no more than a sign, signification,
or representation of that which is the substance!

[.discourse-part]
Answer.
"`Our baptism, which is the gospel baptism, being baptized into Christ,
is that which brings us to the substance, Christ Jesus our Lord,
the substance of all things.
So that signs or significations are nothing to us, but Christ is all to our souls.`"

[.discourse-part]
_Reply._ That water-baptism is the gospel baptism, can never be proved by you,
it being neither the nature of the gospel, nor commanded by Christ,
the law-giver in the gospel.
And that this washing with outward water is the baptizing into Christ,
is a very low and dark apprehension, far from truth,
and the right understanding of the Scriptures,
and the experience of those who are baptized with Christ`'s baptism.
And that which brings to Christ, is the Father, by his drawings; not outward baptizing,
or washing the outward man with outward water; that is but a bodily exercise,
and bodily exercises profit little, so far are they from bringing to Christ,
the substance.
And as for what he saith concerning signs and significations; oh that it were so indeed,
that they were nothing to you, but Christ all to your souls!
For if it were so indeed, could ye thus cry up a figure or shadow of the gospel baptism,
and be so ignorant of the substance?
Do the Jews know the inward circumcision?
Or do ye know the inward baptism, any more than the Jews knew the inward circumcision?
Read that scripture, Rom. 2:28-29. and the Lord apply it home to your souls;
"`He is not a Jew which is one outwardly,
neither is that circumcision which is outward in the flesh;
but he is a Jew which is one inwardly,
and circumcision is that of the heart in the Spirit, and not in the letter,
whose praise is not of men, but of God.`" Now,
may not the Spirit of God say in these our days (yea,
of a truth the Spirit of our God doth say so, and many have heard his voice so speaking),
He is not a Christian which is one outwardly, neither is that gospel baptism,
which is outward on the flesh; but he is a Christian which is one inwardly,
and the gospel baptism is that of the heart in the Spirit, not in the letter,
whose praise is not of men, but of God.
The Jews praised the outwardly circumcised, and ye praise the outwardly baptized;
but God praised the inwardly circumcised and washed.
So that their justification and praise is of him,
and they matter not the justification or praise of man.

[.discourse-part]
He adds further,
"`Neither do we these things but to obey him and follow
his footsteps that he went before us in,
and so he is our leader and commander.`"

[.discourse-part]
_Reply._ Every practice of his he doth not lead or command his disciples to follow him in.
He was circumcised outwardly; are we to take it up because it was his footstep?
No more are we to take up the outward washing, because it was his footstep.
But we are to take up that circumcision which cutteth off that which is evil from us,
and crucifieth to the world;
and we are also to take up that baptism which inwardly
baptizeth and effectually cleanseth from sin.
Oh, how plain are these things where the eye is single,
and the mind not blinded or prejudiced with its own conceivings and misapprehensions!

[.discourse-part]
He adds yet, "`So that we are not idolizing any thing,
but following Christ in the way he went before us in.`"

[.discourse-part]
_Reply._ I wish from my heart ye were not idolizing John`'s baptism, or water-baptism,
by setting it in the place of Christ`'s baptism,
and not attributing that to it which belongs to Christ`'s baptism, and not to it.
To affirm that water-baptism is the law of the Spirit of life in Christ,
and that stooping to it is stooping to the law of the Spirit of life in Christ,
and that the soul cannot be sanctified without going into the outward water;
for till then it is in disobedience, and charged as a transgressor;
and the inward man cannot be washed while living in disobedience,
and that sin is washed away by this outward water-baptism and that this takes off disobedience,
and so is the answer of a good conscience in obedience to God,
and that it leads persons into Christ, with more of this nature;
what is this but the idolizing of an outward, elementary creature and creaturely action,
and an undervaluing of that water and blood which alone can do this?
Now to term this idolizing is no reflecting on Christ; but on men`'s error of judgment,
and their erroneous practices which ensue thereupon; much less is it blasphemy,
although Christ himself was accounted a blasphemer for testifying the truth,
by the professors of that age; and such a judgment may his followers meet with now,
from the professors of this age.

[.discourse-part]
He saith further, "`I know that the pretence of all this is the baptism of the Spirit.`"

[.discourse-part]
_Reply._ He is greatly mistaken.
It is not a pretence, but a feeling of the baptism of the Spirit,
by the water of the fountain of life which God opens in the heart,
and the being born of this water and of the Spirit.
By this means we came to know the baptism which saves,
and the Spirit`'s washing and regenerating us therewith;
and if we should give the honor of this baptism to
the washing of the body with outward water,
we should sin against the Lord,
and be unfaithful in the testimony he hath given us to bear.

[.discourse-part]
He saith, "`Take notice that the baptism of the Spirit is a promise, not a duty.`"

[.discourse-part]
_Reply._ That it is a promise is granted; but it is also a duty to receive the promise,
and to give up to be baptized by him.
Now, to open this a little; for I write in love and tender good-will,
and in that which opens my heart.
The Spirit of the Lord did strive with the old world.
What did he strive for?
Did he not strive to reclaim them from sin?
To circumcise them?
To wash them?
God gave his good Spirit to the Jews to instruct them.
To what end to instruct them,
but that they might circumcise the foreskin of their hearts, and be no more stiff-necked;
and that they might be inwardly washed in heart from their wickedness,
and their vain thoughts might no longer lodge within them.
So that the inward circumcision and the inward baptism of the soul
and conscience (from whence is the answer of a good conscience)
was before either the outward circumcision or outward baptism,
and is the substance, whereof the other were but figures.
The Spirit was not only promised in the time of the gospel,
but was also promised in the time of the law (though more
abundantly promised to be poured forth in the gospel days). Prov. 1:23.
Now, what doth it do when poured forth?
Doth it not enlighten, quicken, lead, touch, wash, or sanctify, purge out the old leaven,
and leaven with the new leaven of the kingdom?
Here is true understanding and true experience.
Oh that ye might come to witness and partake of it!
Do ye desire to obey?
Oh that ye were taught of God to know Christ, as the Father reveals him inwardly,
and to deny and put off all that is contrary unto him, that ye may be baptized into him,
and be found in him, filled and clothed with his righteous Spirit, life,
and nature! in which righteous Spirit, life, and nature,
the true circumcision and the true baptism is witnessed.

[.discourse-part]
He saith, "`The promise of the Spirit,
John calls the baptism of the Spirit.`" Matt. 3:11.

[.discourse-part]
_Reply._ Though the Spirit, when poured out according to the promise of the Father,
did baptize several ways;
yet that is not it which John there calls the baptism of the Spirit;
but the baptism of the Spirit is the inward purging away of sin and filth,
by the Spirit and its fire, or by the Spirit of judgment and burning;
which those that were baptized by John were afterwards to expect and wait for,
that with his fan their floor might be purged, their chaff burnt up,
and the wheat gathered into the garner, ver. 12.

[.discourse-part]
He saith again, "`Take notice, that the being baptized with the Spirit,
or having the Spirit, does not excuse us of our being baptized in water,
but rather fits us for it.`"

[.discourse-part]
_Reply._ If baptism with water were a command of Christ, being baptized with the Spirit,
or having the Spirit, would not excuse from it.
But if baptizing with the Spirit be the gospel baptism,
and that which was figured out or represented by John`'s baptism,
then we are not to turn back from the substance to the figure,
or from Christ`'s command to his disciples, to God`'s command by John to his disciples.

[.discourse-part]
He quotes Acts 8:29. compared with ver. 38-39. "`Where`" saith he, "`we may see,
that the Spirit was in the work of the administration of water-baptism,
as it leads men to the truth of the gospel, and therefore it is that the apostle saith,
'`that by one Spirit we are baptized into one body.`'`" 1 Cor. 12:13.

[.discourse-part]
_Reply._ God, from whom the law was, and the prophets, and John`'s preaching and baptism,
did work in them all by his Spirit; and John`'s ministration being the highest,
God might please to work most therein.
But that this is Christ`'s baptism, commanded by him in the gospel, or the water thereof,
the water wherewith Christ washeth the soul,
or the water of regeneration whereby God regenerates, that we cannot but deny,
being taught of God, and having experience of the contrary.
Yea, it is manifestly but a shadow of Christ`'s baptism, and not the baptism itself;
not the baptism of his Spirit and fire,
wherewith alone the soul can be inwardly purged. Matt. 3:11.
compared with Isa. 4:4.

But that water-baptism leads men into the truth of the gospel, is his great mistake.
He had said but a few lines before,
"`that it is the office and work of the Spirit of God to lead us
into all truths of the gospel;`" let him stick to that,
and wait to experience that, and not attribute that to a dead thing,
which belongs to the living Spirit.

And whereas he interpreteth that scripture, 1 Cor. 12:13.
of outward visible baptism with outward water,
that is a very manifest misapprehension (I wish he
did not so misunderstand and misinterpret scriptures,
for want of the right key which opens them).
For all that are baptized with outward water (whether Jews or Gentiles, bond or free),
are not baptized into one body; but all that are inwardly baptized by the one Spirit,
are baptized into the one body, whereof Christ is head,
and they all drink into one Spirit;
in which Spirit they all have life to act in the body,
and have a living sense of their place and service in the body,
which they who only are baptized with water have not.

Thus far in way of Reply to his Answers to those Queries, which did flow from me,
as life and the love of God sprang up in me, without any premeditation at all;
which retain their truth, evidence, and strength,
notwithstanding all that he hath said to invalidate or weaken them.
Now, follow his Queries returned to consideration,
which it is on my heart to return an Answer to, in the nakedness and plainness of truth,
as the Lord hath pleased to open and give me the
knowledge and experience of the things queried of.

[.discourse-part]
_Query 1._ "`Whether the baptism of the Spirit be not a promise,
and the work of God to give it to his creatures,
and the baptism of afflictions an imputation of wicked men;
and but one baptism commanded by Christ as a duty to submit unto; if not water-baptism,
what is it then?

[.discourse-part]
Answer.
The baptism Christ commands his disciples to submit to, is his own baptism,
the baptism of his Spirit.
The true disciples of Christ are inward Jews and inward Christians,
and they are to submit to the inward circumcision and baptism of Christ their Lord.
They are to be washed inwardly with the water of that fountain,
which God opens to the house of David,
and to the inhabitants of Jerusalem for sin and for uncleanness. Zech. 13:1.
Doth God set this open for the inward and spiritual Jews or Christians?
And is it not their duty to be washed or baptized inwardly with it?
They are to be baptized with the Holy Ghost and with fire. Matt. 3:11.
Every disciple ought to wait for, receive, and experience this baptism.
They are to be washed with the Spirit of judgment and burning,
and to have their corrupt blood purged away thereby. Isa. 4:4.
They are inwardly to be baptized into the name of the Father, Son,
and Spirit, that they may inwardly rise up in the newness of the life,
and of that living name. Matt. 28:19.
They are to be baptized into the one body, which is the spiritual body;
and by spiritual baptism is the soul baptized into it (and not by that which is carnal),
and so to come to Mount Zion, and the heavenly Jerusalem, and enter into it;
which the uncircumcised and unclean cannot enter into,
but they alone that know the truth as it is in Jesus, and keep it. Heb. 12:22.
Isa. 52:1. and chap.
26:2.

[.discourse-part]
_Query 2._ "`If but one baptism commanded,
and men cannot baptize one another with the Spirit,
and it is sinful to afflict one another, what baptism is this one baptism?

[.discourse-part]
Answer.
God made his apostles (and makes those whom he makes ministers
in the gospel) able ministers of the New Testament,
not of the letter, but of the Spirit.
And if the Lord make them able ministers in his Spirit,
what should hinder them from ministering the spiritual baptism?
The same Spirit that teacheth through them, is it not able to baptize through them?
"`Who is sufficient for these things?`" saith the apostle, 2 Cor. 2:16.
Were they sufficient to teach, but as God taught through them?
And are they not sufficient to baptize, as God baptizeth through them?
How often have we found our souls taught and baptized by the water
of life flowing from the spring of life through the holy ministry,
which God hath mercifully raised up, and maketh use of, in these our days.

[.discourse-part]
_Query 3._ "`Whether it be not the work of God on the inner man,
that brings the outward man to be baptized, and obey the commands of God?`"

[.discourse-part]
Answer.
It was the work of God on the inner man, when John`'s baptism was commanded by God,
to bring men to John`'s baptism; and it is the work of God`'s Spirit in the heart,
which brings men to discern and subject to Christ`'s baptism;
for the baptism of Christ is not discerned by man`'s wisdom, or by the reasoning mind,
but by the sense of life in the heart.

[.discourse-part]
_Query 4._ "`Whether men can be truly sanctified by faith and the Spirit,
that are disobedient to God, and live so?`"

[.discourse-part]
Answer.
No, they cannot.
But true obedience requires true light and true understanding;
for all are not obedient who judge themselves so, but those whom God judgeth so.
The inward Jew is obedient to the inward baptism, which Christ hath appointed,
and dareth not set up John`'s outward in its place.

[.discourse-part]
_Query 5._ "`Whether the Spirit of God doth not distinguish between sprinkling of the Spirit,
and baptism?`"

[.discourse-part]
Answer.
They are both figurative expressions; but they tend to, and end in,
one and the same thing in substance, which is inward cleansing.
"`Sprinkling clean water upon the soul,
doth cleanse it.`" Ezek. 36:25. And dipping into, or being overwhelmed with,
the water of life, in the pourings out of the Spirit upon the soul, doth cleanse also.
For there is a river, the streams whereof do not only refresh,
but also cleanse and carry away sin and filth from the soul, as with a flood.

I pray consider that place, Isa. 44:3-5. When God, from the fountain of life,
pours out water and floods upon him that is athrist,
do not these floods and water wash him and nourish him also?
Do not they wash away that which hinders his springing up and growth in the truth?
And is not he hereby baptized into the name of the Lord?
God is the God of Jacob, the Holy One of Israel.
And doth not one that is washed,
feeling that carried away by the floods and overflowings of the Spirit, inwardly feel,
and presently say in his heart,
"`I am the Lord`'s. And another surname himself by the name of Israel`"? Now,
I am one of the seed of Jacob indeed, and of God`'s Israel, and that name belongs to me.
I am inwardly washed from my former wicked and deceitful heart: that is gone,
and a new heart and spirit of God`'s creating and forming is witnessed by me,
and God`'s Spirit testifies in me, and to me, "`That I am an Israelite indeed,
in whom is no guile.`"

[.discourse-part]
_Query 6._ "`Whether the circumcising knife be not the word of God,
and the soul obeying of it be not a sign the knife hath entered,
and taken place on the soul of man?`"

[.discourse-part]
Answer.
It is true; the word of God, the quick, powerful, piercing word of life,
the word which lives and abides forever, and is a commandment of life in the heart,
(Duet. 30:11-15. which is the commandment, law, or word of the new covenant, chap.
29:1. which is the word of faith, which the apostles preached,
Rom. 10:8) this word of God is the circumcising knife,
and the soul obeying of it cannot but be circumcised by it.

But I am jealous with a godly jealousy, lest he mistake and call somewhat else the word,
and reckon his obedience to what he apprehends from the letter,
to be obedience to the word; and if so he greatly deceives his own soul.
And I have good reason thus to be jealous concerning him, because I find him,
in his answer to my first query,
terming water-baptism the "`Law of the Spirit of life in Christ;`"
which cannot but be strange language to all that know the nature,
virtue, life, and power of the law of the Spirit of life in Christ Jesus.

[.discourse-part]
_Query 7._ "`Whether baptism doth not lead men into Christ,
as obedience to the mind of God in Noah`'s time led him into the ark,
that we may be saved by Christ, as Noah was by the ark?`"

[.discourse-part]
Answer.
It is the Father, by his drawings, that leads men to Christ,
and Christ by his Spirit baptizeth them into himself.
He conforms those to himself that come to him, both in his death and resurrection,
by the Spirit and power of the Father.

Now, it is this baptism, or the inward washing, which removeth that which destroys;
and the soul that is subject to the ministration of Christ`'s Spirit,
and gives up to be washed by him, is washed and made clean,
and comes into the number of the saved; for feeling the power which saves,
and experiencing the virtue and operation of it, he must needs be saved thereby.

Nor was it obedience in Noah`'s time which led him into the ark,
but God`'s voice or special command to him, which he received in the faith,
("`By faith he prepared the ark.`" Heb. 11:7) which faith produced obedience;
so that it is faith in the mighty power of God which saves;
which power works mightily in them that truly believe, mightily circumcising,
mightily baptizing, mightily burying with Christ, burying the soul into his death,
and raising it up again in the newness of his life.
So that here is a real inward work of faith,
a real inward appearing and working of the power, and a real obedience to,
and a going along with, the power in its work, in the holy fear and trembling;
and so the soul works out its salvation,
by the power which works in it "`both to will and to do according
to God`'s good pleasure.`" Phil. 2:12-13. Eph. 1:19-20.

[.discourse-part]
_Query 8._ "`Whether Christ was not buried in the water in baptism?
We then being baptized, are we not buried with Christ by baptism?

[.discourse-part]
Answer.
Christ was circumcised with Moses`' circumcision,
and was also baptized with John`'s baptism, which was a dipping into, or burying in,
the water; yet notwithstanding this,
he hath his own spiritual circumcision and spiritual baptism,
to be administered in the gospel dispensation unto his.
And as all Moses`' disciples were to be circumcised with his circumcision,
and all John`'s disciples to be baptized with his baptism unto repentance,
so all Christ`'s disciples are to be inwardly circumcised
and baptized with his inward circumcision and baptism,
which is the substance of both the other figures.

Now, those only that are thus circumcised, are circumcised by Christ,
and those only that are thus baptized, are buried with him by baptism into his death;
which must be, before they can truly know a rising with him in his life.
May not a man or woman easily, from an apprehension in their understanding,
go into the outward water, and rise up again out of the water,
and yet not know what it is to die with Christ, or rise with Christ?
But he that knoweth the inward baptism witnesseth and experienceth these things,
being made a partaker with Christ, both in his death and resurrection.

[.discourse-part]
_Query 9._ "`Whether obedience to the law of God doth not give
a soul a good conscience in the sight of God,
and disobedience make the conscience guilty?
And whether ever the soul can be clear of sin,
while living in disobedience to the law of God?`"

[.discourse-part]
Answer.
It is God`'s sprinkling the soul, whether with the water of his holy fountain,
or with the blood of the covenant, and his washing them therewith,
which makes the conscience good. Ezek. 36:25.
ZEcc. 13:1. Heb. 10:22. (Let it be considered seriously,
whether outward water, or inward, be intended in that place. Heb. 10:22.
And when David said, he washed his hands in innocency, Ps. 26:6.
whether he did it with outward water.) This water, this blood,
this sprinkling, this washing, is received in obedience, and not in disobedience.
But what obedience is it received in?
Is it received in obedience to Moses`' circumcision or John`'s baptism?
or in obedience to Christ`'s circumcision and baptism?
And let him, and all of his persuasion, seriously weigh,
whether ever the soul can be clear of sin, while living in ignorance of,
or disobedience to, Christ`'s circumcision and baptism,
whereby alone sin can be cut off from the heart, and washed away from the conscience.

[.discourse-part]
_Query 10._ "`Whether to obey God be not the way to meet with God,
and to be baptized of God?`"

[.discourse-part]
Answer.
"`Obedience is better than sacrifice, and to hearken,
than the fat of rams.`" And to obey Christ`'s Spirit in the gospel dispensation,
being inwardly circumcised and washed by him,
is far better than to be circumcised with Moses`' circumcision,
or baptized with John`'s baptism.
The day is dawned, and the shadows are fled away,
and the obedience is not now to the shadowy ordinances of Moses, or John the Baptist,
but to the light of the day,
which shines in the hearts of the children of the new covenant.
And they only have the true knowledge of Christ, and the true obedience,
who know the shinings of this light, and walk with God in the shinings thereof. 2 Cor. 4:6.
1 John 1:7.

[.discourse-part]
_Query 11._ "`Whether men can idolize God`'s ordinances, in keeping, doing, loving,
and living up to them?`"

[.discourse-part]
Answer.
They that set up Moses`' circumcision or John`'s baptism for Christ`'s (which are not outward,
as Moses`' and John`'s, but inward and spiritual), they idolize them,
and are found guilty of so doing, in the sight of him who judgeth righteously.
Is it not idolizing the shadow or figure, to set it up in the place of the substance?

[.discourse-part]
_Query 12._ "`Whether men`'s calling the keeping, doing, loving,
and pleading for God`'s ordinances, idolatry,
but not some of those hard speeches Jude speaks of, Jude 15?

[.discourse-part]
Answer.
He still all along takes the thing in question for granted.
We grant that Moses`' circumcision was God`'s ordinance,
and that John`'s baptism was God`'s ordinance;
but that either of these is a gospel ordinance,
that Moses`' circumcision is the circumcision of Christ,
or John`'s water-baptism is the baptism of Christ,--that
we conscientiously and groundedly deny;
God`'s Spirit in the Scriptures putting a difference between them; as particularly,
between John`'s baptism and Christ`'s. Matt. 3:11.
So that as he greatly mistakes the thing,
so (through his mistake) he lamentably wrests and misapplies that scripture,
Jude 15. And let him seriously consider,
whether that scripture may not justly be applied to them,
and whether they can possibly avoid the lash of it, without repentance,
who deny and revile the inward appearance of Christ, by the light of his Spirit,
in the hearts of his, in this our day,
and deny his inward circumcision and baptism to be
the gospel ordinance of our Lord Jesus Christ,
setting up John`'s water-baptism in the stead thereof.

[.discourse-part]
The last Query, "`Whether it be not invading,
and laboring to make void God`'s law and commands, when men so slight, contemn, despise,
write, and do all they can to keep people from closing in with them,
and make them afraid of them by their writing and preaching, as some do?`"

[.discourse-part]
Answer.
This Query implies a very deep, wrong charge against the children and servants of God,
for their obedience to God`'s Spirit.
Oh, how will he answer this to God!
Because we own Christ`'s baptism, with the Holy Ghost and fire,
and into the name of the Father, Son, and Spirit,
with the water of the fountain which God opens for sin, and for uncleanness,
and give testimony thereto in the requirings of God`'s Spirit, having learned it of him,
and experienced it from him,
and having a necessity upon us in his name and authority (many times) to testify,
that this is the gospel baptism of Christ our Lord,
and that John`'s water-baptism is not the gospel baptism, but only a figure,
representation, or shadow thereof; therefore this man chargeth us with invading,
and laboring to make void God`'s law and commands, with slighting, contemning, despising, etc.
Are not these hard words,
and a very unjust accusation against God`'s chosen messengers and servants,
and any whom he pleaseth to make use of in this testimony?
But the truth is,
these hard words are not so much against us as against Him that sends us with this testimony,
and is no less than a fighting against Him who will be too hard for you all,
and will gather people more and more from the outward water-baptism of John,
to the inward baptism by His Holy Spirit and fire,
which happy are they that know and are baptized with.

[.discourse-part]
He saith at the close, "`I have no end in this, but God`'s glory.`"

[.discourse-part]
Answer.
But he greatly mistakes the way to glorify God; for to set up the shadow of a thing,
instead of the thing itself, is not the way to glorify Christ,
or the gospel dispensation.
For Christ is the Son, who doth not come forth with Moses`' circumcision,
or John`'s baptism (who were both servants), but with the Spirit and power of his Father,
wherewith he circumciseth and baptizeth inwardly and spiritually.
And to set up that which is outward in the stead
of this is both to dishonor the Father and the Son.

=== The Conclusion

Now, for a close, I shall open a little of the mystery of Christ,
and of his enlightening, quickening, circumcising, and baptizing, from some scriptures,
as the Lord hath pleased to open them in me, and to me,
and give me the inward sense and experience of them.

John 1:1 and 3. "`The Word was in the beginning,
which created all things;`" and this Word is also
the beginning of the creation of God in the heart.
"`In this Word was life, and the life was the light of men; and this light,
which is life in the Word,
shines in men`'s darkness,`" which enlighteneth them that believe in it,
and the life thereof quickeneth and giveth life to them that hear its voice,
and believe in it; and both the light and life, or the Word by its light and life,
circumciseth and baptizeth.
Doth not the pure light cut off, chase away,
wash away darkness (wherein all sin and uncleanness is comprehended) from the heart?
Doth not the pure Word of life, received in the faith, purify the heart?

[.discourse-part]
Question.
But where is this Word?
or how shall a man come at this Word, or hear its voice or commandment,
in the obedience whereof he is enlightened, quickened, circumcised, and baptized?

[.discourse-part]
Answer.
It is not far off; "`It is nigh thee, saith Moses,
thou needest not go up to heaven for it, or down to the deep,`" etc.
For God, in his love to man, hath placed it nigher, even in man`'s mouth and heart,
that he might hear it and do it. Deut. 30. and Rom. 10.
And he that inclines his ear to this Word, hears and obeys it, lives.
And as it is the Word of the new covenant
(in which is the light and life of the new covenant),
so it brings him into the new covenant, or makes an everlasting covenant with him,
even the sure mercies of David. Isa. 55:3.

Another scripture is, 1 John 1:1. where he speaks of the same Word, of the same life,
of the same light, wherewith men are enlightened, and wherein they are to walk.
ver. 7. That which is declared of,
that which is to be testified of by the gospel ministers, is the Word, the life,
the light.
This is the message Christ gave his apostles to preach,
"`That God is light.`" ver. 5. What is the intent of this message,
but "`that men might be turned from darkness to this light.`" Acts 26:18.
And then the light enlightens them,
and they soon come to feel life, and the Word from which the life comes.
And so they that truly received the testimony of the light (which is the gospel message,
ver. 5),
they soon come to the manifestation of the life (or
of him who is the life) in their own hearts,
and so into fellowship with them that are in the light, and with the Father,
and his Son Jesus Christ also.

A third scripture is, 2 Cor. 4:6. which shows the way of enlightening the mind,
which is by God`'s causing the light of life to shine in the heart;
which being believed in,
gives the knowledge of the glory of God in the face of Jesus Christ.
God is a Spirit; the knowledge of him is spiritual,
given and received in the shinings of his light in the heart.

Thus we receive the beginnings of our spiritual knowledge,
and thus we receive the increase thereof day by day.
In his light (in the shinings of his light in our hearts) we see light at first,
and in the further shinings thereof we see more and more light.

The last place I shall mention is Matt. 13:31.
The kingdom of God was that which Christ much preached,
and here he preacheth it as a "`seed sown in the heart,`" and that a very little one.
Now, consider if this be not the Word of God in a seed, Christ in a seed, life in a seed,
light in a seed, God`'s seed ("`his seed remaineth in him,`" 1 John 3:9). Now,
this seed as it grows in the heart, grows in its own life, light, nature, Spirit, power,
etc., and puts all these forth in the heart in which it grows against sin,
and towards righteousness.
Yea, the judgment of God is revealed in the spiritual light, life,
and power of this Word against sin, and for righteousness; and God`'s Zion, God`'s inward,
spiritual Zion (or his people and children) is redeemed by the judgment
and righteousness which is revealed from and in this Word in the heart.
And this Word is so powerful against sin, that it doth not only cut it off,
and wash it away from the mind and conscience, and so make them clean,
but it also keeps the mind, in which it remains, as it is regarded and hearkened to,
from joining to sin any more; and if sin cannot be joined to,
it can neither be conceived nor brought forth. 1 John 3:9.
James 1:15.

[.discourse-part]
Objection.
But by this doctrine or experience, as thou callest it, Christ in his outward appearance,
his sacrifice and blood, as also the Scriptures,
with the exhortations and commands thereof, are all laid waste, and made void,
and of no use or effect, all being attributed to this Word, life, and light within.

[.discourse-part]
Answer.
No, in nowise.
This Word within, with the life and light thereof,
doth not make void any former appearance or ministration of God,
but rather establishes them, by owning them in their proper place, use, and service.
For he that truly owns this Word, light, life, spirit, power, etc. in his own heart,
must also own it in the hearts of others, in Moses, in the prophets, in John,
and in its fulness in Christ in the flesh; and the virtue of all it did in Christ,
and by Christ in the flesh, towards the salvation of mankind, which his obedience,
and the shedding of his blood, was by the Father made absolutely requisite unto.
And the Scriptures, the instructions reproofs exhortations, commands thereof,
etc. in the hand of the Spirit, are very useful to this day; and the shinings of Christ,
and the quickenings of his life, are felt in them,
when the Lord manageth them unto the soul for good.
Yea, the words which Christ spoke in the days of his flesh,
are spirit and life to this day, when he speaks them in the heart.
But they are not life, as men apprehend, understand, or speak them of themselves,
but rather death, as so made use of.

And those that thus only learn the words, or practise the words,
they do not learn aright, pr practise aright; they do not know Christ aright,
they do not believe aright, or repent aright;
they cannot know Christ as he is the word of life in the heart, nor hear him,
nor obey him, nor be circumcised or baptized by him;
but are drowned in literal apprehensions and conceptions of their own,
beneath him who is the life.

Thus the Jews, in their day waited for the Messiah,
and spake great things of the kingdom of the Messiah,
but knew neither him nor his kingdom, when he appeared and preached it.
So likewise, many now speak great things of Christ being come, and of his obedience,
death, resurrection, ascension, etc., and yet know not him, his voice,
his appearance in their own hearts, or in the hearts of others;
but think in their obedience to what they apprehend
from the Scriptures to have eternal life,
whilst strangers to the living principle of truth,
whereby he gives eternal life to his sheep
"`that hear his voice, and follow the Lamb of God wheresoever he goes,`"
and leads along his sheep with him. John 10:27-28.

He that would know God and Christ to salvation,
must know them in that mystery of light and life,
wherein and whereby they save and deliver from the mystery of sin and death;
for there is the mystery of God, the mystery of the Father, the mystery of Christ,
the mystery of the gospel, the revelation of the mystery, the preaching of the mystery,
the mystery of the kingdom of God, the speaking the wisdom of God in a mystery,
the riches of the glory of the mystery, the acknowledgment of the mystery,
the fellowship of the mystery, and the mystery of the faith held in a pure conscience.
The true ministers of Christ are stewards of the mysteries of God.
They have the treasure of life in their earthen vessels,
and are to give forth from that treasure to those they minister to,
and bring them to the discerning and partaking of the same treasure in themselves.

Oh, consider, consider all ye professors of Christ, and of the Christian religion!
There is a mysterious power that begets,
a mysterious womb that conceives and brings forth,
a mysterious birth that is begotten and brought forth, which hungers after the mystery,
and is fed with the knowledge, life, and virtue of the mystery.
That birth which is of a nature below this, or feeds on a knowledge below this,
and hath a faith and hope beneath the nature of the
faith and hope which God gives to his birth,
is but the child or birth of the bond-woman, which is not to inherit with Isaac,
the true heir; but all such kind of children of the kingdom must be cast out,
with the bond-woman, their mother. Matt. 8:12.
Gal. 4:30.

The birth of the Father`'s Spirit and power is only the true inward Jew or Christian,
to which the promises, the kingdom, and everlasting salvation belongs;
and all else are but pretenders to be what they are not;
who after all the fires of their own kindling,
and sparks wherewith they compass themselves about,
will at last lie down in sorrow from the hand of the Lord.
Oh that none might be deceived by the enemy of their soul,
about matters of so great concern!

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Eighteenth of 5th Month, 1679
