== Epistles to Friends

[.letter-heading]
To Friends in and about the Two Chalfonts

[.salutation]
Dear Friends,

Ye have a deep place in my heart, and my cries are to the Lord for you,
that ye may live to him, and find his life springing up and abounding in you.
What is it to have a distinct name, or distinct meetings from the world,
unless the power of the Lord be felt in your hearts, and his presence in your assemblies?
Oh that the Lord would awaken you!
Oh that the Lord would quicken you!
Oh that it would please the Lord to raise up a strict watch in you,
against all drowsiness, and carelessness, and temptations, and snares of the enemy,
that ye may travel on your journey, with your backs upon the world,
and your faces towards Zion; never looking back to the fleshly nature, desires, or lusts,
to entertain any thing of that any more,
which ye have parted with in the demonstrations and leading of life,
but still pressing on further and further,
till ye come to apprehend and be possessed of that,
for which ye have been apprehended by God, and drawn in some measure towards.

O my friends!
There is a path of life in which ye must travel, even to the very end of it,
or the crown of life is not to be received!
Oh that ye might travel on!
Oh that nothing might stop you!
Oh that ye might every day wait for and feel the leader,
and walk on with him in the simplicity, uprightness, and sense of his life,
out of the reach of that wisdom,
which is ever and anon forming reasonings in the heart against it,
and striving to darken, and make the plain way of God intricate to the soul!

My life often reacheth to you, my soul exceedingly longeth after you!
And in the stirrings of the same life be ye also helpful to me,
crying to the Lord for me, that I may abide with him, feel his preservation,
and dwell in that which he hath chosen to appear to and refresh the soul in,
that I may be acceptable to him, and further helpful to you,
in the season of the stirrings of his precious and powerful life in my heart.
The Lord God of mercy watch over you,
pruning and keeping down all the earthliness and corruption in any of you,
and watering and cherishing his own plant in you all,
that ye may daily witness the dying and decrease of the one,
and the quickening and growth of the other,
even till death be perfectly consumed and swallowed up by the growth, power,
and presence of the immortal life in you, and your souls safe and happy in your God.

And so to the tender mercies and care of the Lord do I give you all up,
breathing for you (as for my own soul) that ye may be perfectly the Lord`'s,
perfectly given unto him, perfectly waiting upon him,
and daily receiving into your precious vessels the precious,
living testimonies of his love and acceptance, and his sweet, heavenly dews,
which will exceedingly refresh and make your hearts glad,
as he causeth them to descend and light upon you.
So that which is of God in your hearts, every day wait to feel God breathing upon,
that it may open unto him, receive strength from him,
and ye in it be more and more gathered and united to the Lord,
even till ye wholly become one nature, mind, and spirit with him;
and then ye will see the end of your travels, and sit down in his joy, and peace,
and pure rest, from all laboring after life,
and all sorrows for the want and absence of it,
and all fears of losing or being separated from it;
being established in the power which is over all,
and which preserveth all that are encompassed with it, and established in it,
forever and ever.

Your friend and brother, in the meek, innocent nature of the Lamb,
and in the begetting of the royal, heavenly life,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From my present place of Confinement in Aylesbury, according to the will of God;
who is blessed, and to be blessed in all that he doth, or suffereth to be done:
22nd of the 3d month, 1666.

[.postscript]
====

O my friends! prize the rich, tender mercy of the Lord, in calling you out of this world,
towards his everlasting inheritance and fulness of life!
And let not anything of this world come between him and you;
but let all that is of this worldly nature, both within and without,
be trampled upon by you,
and the prize of the high calling of our God in Christ
Jesus be faithfully and earnestly pursued after;
that none fall short of the hope and glory set before him, but that every one may so run,
as certainly to obtain and enjoy forever,
even the dominion and reign of God over all that is contrary to him,
and the sitting down in the rest, joy, and peace of his nature forevermore.
Amen.

====

[.letter-heading]
To Friends in Truth, in and about the Two Chalfonts

Oh, let every soul wait to feel the pure life of God,
that in that we may wrestle with our tender Father,
for the opening the depth of his bowels and tender mercy,
that that may be brought forth in every vessel, and in the whole body,
which may make the glory of his name shine,
and may fill the vessels of his choice with the joy and pleasure of his salvation!
Oh that the pure measure of his life might be awakened
and raised in your assemblies together,
that ye might feel the pure fountain, the springs opening in you,
the streams running through you, and every soul refreshed, filled, and satisfied;
that ye might go away blessing his name,
who hath taught you and given you hearts to wait upon him, and who showeth you mercy,
and giveth you acceptance in your waitings!

And, dear friends! watch, that life may be always fresh and savory in you,
to the seasoning of all your thoughts, words, conversations, and actions,
that ye may feel the name of God written upon you, and his precious presence in you,
and with you.

And in this freshness remember me,
to whom the Lord hath given to remember and breathe for you, who am a prisoner,
and have suffered many afflictions,
because that of God which is in me cannot bow to that which is of man.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From Aylesbury prison, the 23d of the Sixth month, 1666

[.letter-heading]
To Diligent and Faithful Friends, in and about the Two Chalfonts

[.salutation]
O tender and dearly-beloved Friends,

My spirit is at this time touched with the sense
of the great goodness and mercy of the Lord,
insomuch as I feel breakings forth therein, and repeating there over and over again, Oh,
what hath the Lord done for us, what hath the Lord done for us?
For he hath not only given us a sense and taste of the precious promises in the Scripture,
but hath also led us in the way of the fulfilling of them.
He hath manifested that to us, wherein not only the promise is made,
but whereto also the promise is fulfilled.
Which of you, that is open and fresh, doth not know the seed of life,
the living principle, the light eternal, which leads out of death and darkness,
into the land of the living, the holy land, wherein dwells peace and righteousness,
the land which flows with milk and honey, wherein are the vineyards which ye planted not,
and the houses that ye built not, wherein the true vine grows,
and its branches shoot forth and bear the right grapes?
O my friends, do ye not know the Father which begat you,
and the Son in whose image he hath begotten you, and his Spirit, which is the breath,
strength, and power of your life?
How hath the Lord God advanced you, a poor, afflicted, despised, persecuted remnant,
above all kindreds, families, and professions of the earth!
How nigh is the Lord your God unto you!
Doth he not tabernacle and dwell in you?
Do ye not feel him walking up and down, and taking delight in your spirits,
who are separated from the unclean thing,
and to whom subjection to him is become pleasant and natural?
Oh! the Lord God give his people a sense what he is unto them in this day,
and lead them along into their several professions and inheritances,
that they may sit down with Abraham, Isaac, and Jacob,
each in his portion in the holy land,
and in the heavenly dwelling-places in Christ Jesus,
which the souls of those that are redeemed by him are acquainted with and sit in.

It is on my heart to instance in some things a little more particularly,
that the sense and remembrance of God`'s goodness to you herein,
may come the nearer and closer to your spirits.

[.numbered-group]
====

[.numbered]
_First,_
Have ye not had experience of the Lord`'s love and
faithfulness in manifesting his name unto you,
which ye have in some measure known, as pure, precious, and excellent,
as a strong tower in case of danger and assaults from the enemy?
And hath not the Lord taught you, by a secret instinct of his Spirit and life in you,
to retire and hide yourselves in this tower, from the violence and fury of the enemy?
And have ye not always found relief, safety, and protection therein?
Indeed, when ye have gone out into your own thoughts,
and consulted with the reasons of the fleshly mind,
there ye have met with a wound and a hurt,
and have lain open to the stroke of the betrayer and devourer;
but the name of the Lord hath never deceived or disappointed
any of you that have trusted in it,
relying upon his kindness, tenderness, mercy, love and faithfulness therein.

[.numbered]
_Secondly,_ Hath not the Lord given you a proportion of the pure, heavenly patience,
even of the Lamb`'s meekness and patience,
and also given you to possess your souls therein,
wherein hath been felt a true measure of rest and peace with him,
in the midst of all the disturbances, fears, and troubles, both within and without?
And hath not this been a help and succor to you, even in the time of his judgments,
wherein ye have been enabled to wait and lie still, until the indignation was over-past,
and the mercy sprang afresh?

[.numbered]
_Thirdly,_ Hath not God manifested to you the place of his worship, even so that ye know,
and have often experienced it to be in his name, Spirit, truth, and power?
And hath he not prepared for you, and given to you, the pure offering and sacrifice,
and accepted it at your hands?
And have ye not often, yea, may I not say always, felt his presence meeting there,
and the refreshments which come from his presence in this day of his mercy,
and of his tender visiting and refreshing his seed?

[.numbered]
_Fourthly,_ Have ye not felt the word of his power shaking the mountains,
breaking the rocks, and making the dark hard part in you, and the enemy of your souls,
to tremble at the sound of his voice?
Yea, have ye not found thereby the stony heart in a great measure taken out of you,
and a tender heart, an heart like flesh, given you instead thereof,
which hath melted and bowed before the Lord,
and tenderly received the impressions of his Spirit?

[.numbered]
_Fifthly,_ Have ye not found the laws of life,
the laws of the new covenant written by the finger of God`'s Spirit in this new heart,
so that ye could read the will and requirings of your God,
by the light of his Spirit in the inner man?

[.numbered]
_Sixthly,_ Hath not he also put his Spirit within you,
that ye have not only read the law written,
but have also found a delight (and ability also in him) to do his will?
For the Lord hath not left you to do what he requires, according to the old covenant,
but he himself worketh in you both to will and to
do what is acceptable to him of his own good pleasure.

[.numbered]
_Seventhly,_ Have ye not found his fear put into your hearts,
even a fear which no precepts of men can teach, nor ye can by no means attain to,
but as he pleaseth to give it you?
And doth not this fear make you wise in him to depart from evil?
Doth it not cleanse out the evil?
Doth it not keep out the evil?
Did ye not find this virtue in it at the very first,
and do ye not still find it to this very day?

[.numbered]
_Eighthly,_ Do ye not find the blotting out of iniquity,
and the not remembering of your sins by the Lord?
Ah! how hath the Lord forgiven you!
How doth he pity you!
How doth he bear with you!
Do ye not know the place and state wherein mercy pleaseth him,
and where he is never weary of pardoning, blotting out, and forgiving?
Do ye not feel the sprinkling of the blood of the covenant daily by him upon your consciences,
and the precious virtue thereof?

[.numbered]
_Ninthly,_ Do ye not find the anointing near you, yea, within you,
ready to teach you to know the Lord, so that ye indeed know him,
not according to outward names and apprehensions only,
but his nature in his heavenly power, in his inward virtue, manifestations, operations,
and appearances in you?
And this is true knowledge indeed, pure knowledge, fresh knowledge, living knowledge,
which makes you conformable to, and brings you forth in,
the image and likeness of what ye know.

[.numbered]
_Tenthly,_ Is not the way of the ransomed, the way of holiness,
become clear and pleasant to you?
Hath not the Lord removed many stumbling-blocks, that he might make the way plain?
And is it not a path wherein there is no erring,
wherein a way-farer may walk without fear or danger, the light is so certain,
the guide so faithful, and the path so easy and infallible to the plain, honest, single,
upright heart, who freely giveth up to the Lord, and waiteth to be taught and led by him?
Indeed, to the wise, reasoning, disputing mind, it is not thus,
nor to you at any time when that part is up; but as that is brought down,
and the simplicity of Christ (the innocent birth) raised in you,
do ye not still feel it thus?
Therefore ye had need to watch and pray and wait and believe,
that ye may know and enjoy the preciousness of your
spiritual estates and conditions in the Lord,
and that that which would corrupt and destroy, may,
by the lifting up and displaying of the banner of his love and power in you,
be beat down and kept out.

[.numbered]
_Eleventhly,_ Hath not God given you of the true humility,
whereby that which was once exalted in you above his fear, and above his seed,
is now brought down and laid low, and his pure life and fear in you exalted over it?
Do ye not know the feigned humility and fear (which man`'s wisdom teacheth,
and man`'s wisdom learneth) and abhor them?
And is not the true fear and humility which ye have received from God very precious,
and of great use and service to you?

[.numbered]
_Twelfthly,_ Have ye not received the true love,
whereby ye are taught and enabled to love the Lord your God above all, and the brethren,
children, and fathers in him; yea, and your very enemies also.
How precious is this!
Who can witness this,
but he who hath received it! but he whose heart the Lord hath circumcised,
and from which he hath cut off the enmity and contentious nature,
which cannot truly love neither the Lord nor his people, nor his creatures,
though it maketh a subtle, deceitful show thereof,
to the deluding both of itself and others.

[.numbered]
_Thirteenthly,_
Do ye not know the true righteousness and the true
sanctification which is in Christ Jesus,
and which ye receive and abide in in him,
which formerly (in a great measure) ye did but talk of,
and which many to this day (whom the Lord hath not gathered, as he hath done you,
but hath left behind, out of the power, out of the calling,
out of the election) have only the words of, and their own apprehensions upon the words,
but know not nor feel nor enjoy the thing itself, as ye do this day,
blessed be the name of your merciful God and Redeemer?

[.numbered]
_Fourteenthly,_ Do ye not know Zion, the holy hill of God,
and Jerusalem the holy city which is built thereon, which hath long been hid,
even from ages and generations, but now is made manifest in the Spirit,
and many are already come thither, and many more are travelling thitherwards,
and some dwell and abide therein, and feel the law going forth out of Zion,
and the word of the Lord from Jerusalem,
and find their souls translated by the mighty power of God from death and hell and enmity,
into the nature, love, and life of the Lamb;
in whose light those that are saved and redeemed by him walk?

[.numbered]
_Fifteenthly,_ Do ye not know the true church and body of Christ,
which is one spirit with him, which is flesh of his flesh, and bone of his bones?
And hath not the Lord in his mercy made you members thereof?
And do ye not feel the nourishment, virtue, life,
and Spirit of the whole body in your own vessels,
and so are partakers of the true union and fellowship, both with the Lord Jesus Christ,
and one with another?
For he that is gathered by, and walks in, the true light,
is also in the true life and fellowship, both with that which begets,
and with that which is begotten.

[.numbered]
_Sixteenthly,_ Do ye not know the kingdom and reign of Christ already in measure set up,
and daily more and more setting up in your hearts?
And is not his government sweet, pure, heavenly, precious,
refreshing to that which is of God in you,
and an iron hammer and sceptre to that which is earthly and fleshly?
And is it not your joy to feel him reign and overcome his enemies,
exalting his holy name, power, and sceptre over them?
And what he hath done, and what he is doing, and what he yet will do in you,
of his own tender love, and for his own name`'s sake; do not your hearts leap within you,
when at any time the Lord pleaseth to give you the sense and sight thereof?

[.numbered]
_Seventeenthly,_ Do ye not know the fast which the Lord hath chosen,
and hath not the Lord helped you to keep that fast?
Have ye not felt his power break the bond of iniquity in you,
and the once oppressed in you coming up in a true measure of the pure freedom,
to serve and worship the Lord?
And have ye not also had a taste of the feast which
the Lord hath prepared on his holy mountain,
even of the fat things, and wines on the lees well refined,
which they that inhabit there eat and drink of abundantly in his presence?

[.numbered]
_Eighteenthly,_ Do ye not feel God the Lord making an everlasting covenant with you,
even of the love and mercies sure to David and his seed forevermore?
Is not he near you, yea, with you and in you, who is the gatherer into,
and the preserver in, this covenant?
Yea, do not ye feel him teaching and enabling you to keep
covenant with the Lord your God (by the virtue,
power, and presence of his life and Spirit in you), even as he keepeth covenant with you;
insomuch as ye begin to feel a settlement and establishment in him that is true,
and your calling and election becoming sure,
and the danger and fear of falling away or miscarrying removing from off your spirits?

====

What shall I say to you, what shall I mention further, or what shall I instance in?
Have ye not felt the wilderness become a fruitful field,
and the fruitful field become a forest?
Have ye not felt the lame walk, the deaf hear, the blind see, the dumb speak,
the leper cleansed, the dead raised, etc.? Have ye not witnessed the sore shaking,
and terrible passing away (in measure) of the old heavens and old earth, and the forming,
planting, and bringing in (in measure) of the new heavens and the new earth,
wherein dwells righteousness, in the stead thereof?
So that in places where dragons lay, is now green grass, with sweet-smelling flowers;
and in the once parched, dead, dry, barren, desolate heaths,
are now springs and flowings of the pure, living water.

Friends; There is one, whom the Father hath sealed (and he is but one, yea,
the very same in us all), in whom are all the treasures of wisdom and knowledge,
and all the riches and substance of life; and we,
through the mercy and goodness of the Lord, partake thereof, as we are gathered into him,
found in him, and abide in him.

And now my friends; What hath differenced us from others,
or why hath the Lord done this for us more than for others?
Search your hearts, see if any of you can find the cause thereof in yourselves.
Indeed I cannot.
From my very heart I cannot but cry grace, grace! mercy, mercy! love, love (deep,
tender love)! goodness, goodness! from the very first beginning, all along,
throughout the whole carrying on of the work, to this day;
and I have nothing else to hope in, or plead before my God.
Do I believe?
It is he gave me faith; yea, he putteth it forth, and causeth it to act in me,
or I easily fail therein.
Do I will that which is good in any kind?
My will is of him, yea, it is in him, and hath its creation, preservation, being,
and strength from him.
Do I obey or do that which is good?
No, no, not I; but his life, power, and Spirit in me.
Do I suffer inwardly or outwardly?
That is not of me neither, but he that hath given me to believe,
he also giveth me to suffer, and beareth up my spirit in my sufferings, by his power,
and for his name`'s sake.
So that my heart saith (and I confidently believe he will, in his mercy and goodness,
preserve me in that sense forever), Not unto me, not unto me, in any one respect,
but to thy name, to thy holy name, to thy tender name, to thy infinite bowels,
and precious love and compassions in every respect,
be the acknowledgment and praise given of what thou hast done, and yet dost,
and wilt do in and for my soul, forever and ever.

And now, my dear friends; As the Lord hath demonstrated the way of life unto you,
so that it is sealed in your spirits, and ye have walked in it, and always met with,
not only the promises of life, but even life itself therein;
so the Lord still watch over you, that nothing ever blind that eye in you,
which alone can see this way; and the Lord preserve you in uprightness of heart,
that ye may singly wait on him, for his further manifesting of it in you and to you;
and that he, by his living Spirit, would continually quicken and rouse up your spirits,
to walk diligently and faithfully therein;
that so ye may come to see what ye have not yet seen,
and to desire what ye have not yet desired,
and may find your hearts and inheritances enlarged in the Lord.
Ah, what is the world, or any worldly thing or interest, in comparison of this!
The Lord remove every snare and every stumbling-block out of your way,
and every weight and burden from off your spirits,
that ye may run with joyfulness to the end of your course,
and may enter into the full kingdom and possession of life.
Ye have received already that which is all;
but ye must wait for the further opening and spreading of it in you,
and your further growth into it.
The Lord`'s soul hath travailed for you,
and his faithful messengers have likewise travailed and sought after your souls,
and your souls have travailed and mourned and waited,
and gone through temptations and trials of many kinds, and had a taste of the true peace,
and true holiness, the true righteousness, the true joy,
even the joy of the everlasting kingdom.
Now the Lord God preserve you, that nothing may interrupt or come between you,
and that wherein ye have felt him, and wherein is his riches and fulness;
but that ye may always feel that, and abide faithful to the Lord in that,
wherein the preservation and growth unto life eternal alone is witnessed.

And friends; Put the Lord in mind, that as he hath pleased to manifest the way,
and show that clearly unto you, whereby the heart is joined to him and preserved in him;
so he would please, of his free and tender mercy, to add this also,
even to give upright hearts, and entire spirits,
to abide with him in that principle of life wherein he hath gathered you,
and to watch unto, and be faithful to, all his warnings, drawings, movings, and leadings,
that his Spirit may have no matter of grief against you,
but it may be the delight of his soul to do you good continually,
and to answer the desire of your souls in everything that ye breathe unto him for;
that the Lord may not be ashamed to own you to be his people, and ye may feel with joy,
and abundant consolation, that he is your God.
And this will be enough in all the tribulations, afflictions,
and trials that ye meet with, either inwardly or outwardly.
So the God of love and peace preserve you, in that wherein is fellowship with him,
and in which his life, love, joy,
and peace naturally and delightfully spring up and flow into the soul.
Amen, Amen.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Written in Aylesbury Jail, about the Ninth and Tenth of the Twelfth month, 1666

[.letter-heading]
For Friends of our Meeting, and Thereabouts

[.salutation]
Dear Friends,

I am deeply sensible that it is a day of trouble, rebuke, and distress,
to the Israel of God.
The Lord hath pitched his pure, living tent, and begun to build up his beloved city;
the Lord hath indeed had mercy upon Zion, and favoured the ruins and desolations thereof.
But the malice and rage of the enemy is great,
who seeketh to compass the tent of the holy and the beloved city,
that he may lay waste and destroy the work and heritage of God.
Now, all that feel life, all that are of the true birth, all that know the seed;
oh! abide, live, and breathe in the seed, that ye may come forth in the true life,
and in the strength of God`'s holy Spirit (with strong cries and tears,
with innocency and righteousness, with meekness and patience, etc.),
to the help of the Lord against the mighty.
We have no strength but our God,
nor is our expectation from man (whose breath is in his nostrils,
who is to be ceased from); but we believe the voice, that not by strength,
nor by man`'s power, but by my Spirit, saith the Lord of hosts,
shall this work of his be preserved and go on.
Therefore every one wait to feel the seed travail and cry daily to the Father,
that so the spirit of darkness may be hindered, and by the power of life withstood,
in all its enterprises against the children of light.
Oh! let the condition of Jerusalem be written upon every one`'s heart;
and as members of the living body, feel the wants, afflictions,
and distresses of your fellow-members day by day.
And let every one say in spirit:

Lord, take care of all thy children.
O thou tender Father! consider what they suffer for the testimony of thy truth,
and for thy name`'s sake, and uphold them,
and give them victory and a holy dominion over all,
because it belongs to thy seed into which thou hast gathered them,
and in which thou hast united them to thyself.
Oh! carry on thy glorious work, which thy own mighty arm hath begun,
and cut it short in righteousness for thine elect`'s sake,
that it may be finished by thee, to thine own everlasting praise.
Thy children wait on thee, they cry to thee day and night,
that they may be preserved by thee in the well-doing, and in the pure, holy,
innocent sufferings for thy truth`'s sake; until thou say, It is enough,
until thy holy Spirit say, It is finished: my lambs, ye shall suffer no more,
but now ye shall reign with me and my Son forever.

My dear friends, it is now the time of prayer, and of waiting upon, and hoping in,
the Lord, who knoweth and considereth all our conditions.
If any be afflicted, let him pray.
We are afflicted, we are oppressed without cause or provocation on our parts,
only because we fear, and love, and obey our God, according as he hath taught us,
and because he hath put this resolution into our hearts,
that we will abide in subjection to him,
and stand to the holy testimony which he hath given us to bear, whatever befalls us.
And what shall separate us from his love, or come between us and his care over us,
who is able to bear us up in all,
and carry us over all (in the holy dominion and strength
of his seed) that can set upon us,
and strive to turn us out of the way, or to make us faint in the way?

Dear friends, In my bonds I remember you, and pray for your prosperity.
Do ye also remember me in your daily addresses and approaches to God,
that I may receive increase of virtue and strength from the Lord,
by the help of your prayers; and, oh! feel the afflictions of the afflicted,
and breathe for them day by day, that the whole body may receive the flowings in of life,
help, and strength daily,
from the pure breathings of life in every member of the body every day.

So the God of love and mercies be with, and do good to, his whole heritage;
and fill you (with the rest of his children) from the pure fountain of life,
with fresh streams of life day by day.
Amen.
This is the hearty desire of

Your friend, brother, and companion in the faith and patience of the saints,
who has had a share in the afflictions which befall his children and chosen ones,
for his name`'s sake,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, the 9th of the Sixth Month, 1670

[.postscript]
====

And truly friends, it is not grievous, but rather joy to me,
to undergo the several afflictions and temptations, which my tender Father,
in his tender love and good-will, orders for me.
Yea, all that can taste, tell me, is it not greater riches, and far sweeter,
in this our day, to bear the reproach of Christ,
and to suffer for the testimony of his precious truth,
than to enjoy the pleasures of sin and glory of this world, which are but for a season?

====

[.letter-heading]
To Friends in Truth, in Chalfont, and Thereabouts

Dear friends (whom I love in the Lord,
and whose prosperity and growth in the truth I greatly desire),
this sense is on my heart, in reference to you at this time.

The Lord`'s soul travaileth for you (having visited you in tender mercy,
and with great lovingkindness), and he desireth to enjoy and possess you,
as an inheritance for himself, to delight in and to do good unto continually;
and I know there are many among you, who have also desired and travailed after the Lord,
and have been burdened and grieved with that which hath
in any measure hindered your souls enjoying the Lord,
and your faithful serving him, and his delight and pleasure in you.
Now friends, this is my present desire and breathing for you,
even that ye may be joined further and closer in the everlasting
covenant of life and peace with the Lord,
which must never be forgotten on your parts, as it cannot be on his;
wherein to help all the tender and faithful-hearted among you,
this advice sprang in my heart to you this morning.

Mind and watch to that which quickens and enlivens the soul towards God,
and watch against that which flats and deadens it; for they are both near,
and they both seek after you, the one for your good, the other for your hurt.
I need not tell you what these are,
nor where or how they appear (ye have been abundantly, and as ye wait on the Lord,
are daily instructed therein, blessed be the name of the Lord),
but in continual watching to the one, and against the other,
is the diligence and care of your spirits daily to be exercised.
Oh, at no time let your spirits be loose and careless!
For the enemy waits to do hurt, and the Lord waits to be gracious,
and to do your souls good.
Watch, therefore, and pray, that ye enter not into the temptation of the enemy,
nor miss of the tender mercies and loving-kindnesses of the Lord,
which are sure to the seed (and to all that are of and abide in the seed) forever.

Oh! who would miss of the quickening virtue of our God,
of being anointed with his holy oil,
and having the flames of life kindled further in him?
Who would be captivated and brought into subjection to sin, Satan, vanity,
and the spirit of this world again,
who hath witnessed any proportion of deliverance therefrom?
Ye know that ye can do nothing of yourselves: oh, what need have such to watch to that,
which is able to work mightily in the heart,
and to bring forth the fruits and effects of righteousness, and to bring under,
and keep under, kill and slay that power of unrighteousness,
and to root out and bury the dead, out of the sight and remembrance of the living!
Glorious things are testified (truly testified) concerning the power of the Lord,
and his mighty operation inwardly in the hearts of his children,
in this day of the preaching of the everlasting gospel again,
after the long night of darkness.
Let none be content,
without witnessing and experiencing a measure thereof in their own particular.
Oh, dwell not with death, vanity, nor corruption!
O my dear friends,
let not vain or earthly thoughts lodge in any of
your hearts! but dwell with him who is pure,
who is living, and gives life to your souls; and also gives peace,
and brings it home to you,
leaving upon your spirits that "`peace which passeth
all the understanding`" and comprehension of man,
and who maketh his called, chosen,
and faithful ones glad with his deliverance from the power and temptation of the enemy,
and with the flowings in of life and redeeming virtue, from the fountain thereof.
Judea (the city) is known among the living, _whose walls are salvation,
and all the gates and entrance into it praise._

And, my dear friends, mind your meetings together,
to wait upon your God with great seriousness and intention of spirit,
every one watching to feel life up in your own spirits.
Oh! sit down (yea,
breathe earnestly to the Lord to give you to sit down) in the silence of flesh,
and in the stillness of your spirits, waiting for the presence, appearance,
and power of your God to be revealed in the midst of you,
that your hearts may be searched more and more,
and the pure judgment revealed against whatever would appear
or rise up contrary to the holy nature and will of God,
and that which is for death, brought into death more and more,
and so the bread and water of life given to that which is to be nourished up in life,
that all that is impure may be kept down,
and that which is pure (the plants and trees of righteousness) may thrive, flourish,
and spread more and more,
and you sit down under the shadow of your own vine and olive-tree,
partaking of the sap and fatness thereof.

Oh that every one of you, in all your meetings together,
might witness that scripture fulfilled in you! "`They shall
be abundantly satisfied with the fatness of thy house,
and thou shalt give them, or make them to drink, of the rivers of thy pleasure.`"

And I beseech you, in the bowels of tender love, take heed of sluggishness,
or carelessness, or deadness of spirit in your meetings;
these things in nowise become the Lord`'s people,
nor your professions of waiting upon the living God; ye are to look up, to watch, wait,
and breathe for the Lord, to be exercised by his Spirit,
to have to do with him before whom all things are naked and bare,
to offer up that acceptable sacrifice of a broken heart, of pure praises, of love, life,
humility, thanksgiving, etc.,
and to receive what the Father of mercies stands
ready (in and through the Lord Jesus Christ,
the Son of his love) to give forth unto you.
Can you be thus exercised, while in a drowsy, sluggish, careless spirit?
Do not such dishonor the Lord, whose name ye should honor?
And is not the jealous God provoked and grieved by such things as these,
whom ye should walk in all humility, tenderness of spirit, and well-pleasingness before?

I beseech you, therefore, watch against all things of this nature, and be diligent,
that ye may witness the law of the Spirit of life in Christ Jesus making you free,
and fencing you against all things of this kind, that ye may be a chosen generation,
a royal priesthood, a holy nation, a peculiar people, a temple of living stones,
wherein the living God may dwell and walk, and sup with you,
and give unto you to sup with him, where ye shall eat the pure bread of life,
and drink the wine of the kingdom, which will glad your hearts exceedingly,
and the joy of the Lord will become your strength;
which strength will carry you above the strength of the enemy,
and cause you to bring forth the fruits of life, and righteousness,
naturally to the Lord; and so you shall shine as lights in your several places,
and show forth the praises of him who hath called
you out of darkness into his marvellous light;
for it is a marvellous light indeed,
which the Lord hath caused to shine in the spirits of his children, whom,
in this day of his power, he hath begotten to himself,
and the life eternal is wrapped up in it; and they that truly know it,
know it to be no less than the light of life,
even the light which came from the pure life of the Son,
and leads to the habitation and dwelling-place of the Father.

There is one thing yet remains with me, which I would fain have you grow in a true,
sensible, and experimental understanding of, which is this; to wit,
What it is not to touch the unclean thing.
The enemy will be stirring up and casting in that which is unclean,
upon the vessels which God is purifying and preserving from all pollution.
But there is a starting back from and eschewing the evil, a forsaking of the vain,
earthly mind and thoughts, and a receiving in such temptations and suggestions no more.
Oh that ye might all experimentally know and witness what this is!
I know many of you do in some measure, blessed be the God of our mercies,
blessed be our Saviour and Redeemer forever and ever!
But oh! more, more, more of this knowledge, more of this experience,
my heart livingly breathes for, for myself and you,
that we may witness the scripture abundantly fulfilled in our hearts from the Lord:
"`Whosoever is born of God doth not commit sin; for his seed remains in him,
and he cannot sin, because he is born of God.`" Oh, feel the weight of this scripture,
in that which gives the understanding of it!
The Lord hath made a new covenant, and a living covenant,
and prepared a new and living way for the ransomed to walk in without erring,
that he might amend all (in this new people) which
was amiss in those under the first covenant.

Oh! let the Lord enjoy the design of his heart, and his people so wait upon him,
that they may all be renewed in the spirit of their minds,
and the Lord may have a generation of Calebs and Joshuas,
who may fully follow after him in all things,
and who may witness his power and presence still with them, and the holy, tender,
merciful God may never be provoked by them,
to cause him to withdraw his good Spirit from them,
and so to leave them and forsake them; for if any draw back from the Lord,
and from the holy commandment of life, the Lord`'s soul can have no pleasure in such.
Oh that, therefore,
there may be none among you drawing back to perdition! and take heed of deadness,
drowsiness, sluggishness of spirit, earthliness, fleshly wisdom, unbelief, etc.
(for that is a degree thereof, and leadeth thitherwards), but all to grow in faith,
with diligence,
towards the saving of your souls (which is far nearer than when you first believed),
which ye shall be sure in due time to reap, even the salvation ye wait for,
if ye faint not, nor grow weary in your minds, but abide in the faith and patience,
unto the end of your trials, both inward and outward,
which are measured out by the Spirit and wisdom of the Lord,
and not by the wiles of your enemies, whom the Lord stops and chains at his pleasure.

The grace, mercy, love, and peace of God our Father, and of our Lord Jesus Christ,
be multiplied unto you, and fill your hearts from day to day,
according to your several capacities, and enlarge your capacities,
and bring you more and more into the heavenly fellowship,
that your joy therein may abound, and ye may daily rejoice in the goodness of the Lord,
and in his exercising lovingkindness, judgment, and righteousness in the earth.

This is from your brother and companion in the afflictions,
and also in the joy and glory, of this day of the salvation of our God,
which is further to be revealed and enjoyed by those
who meekly and patiently wait for it,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, 22nd of the Third month, 1671

[.postscript]
====

And all my dear friends,
who have known what it is to be uncovered and stripped of your
own righteousness (and of all fleshly robes and garments),
and to put on the Lord Jesus Christ,
even the innocency and righteousness of his nature and Spirit,
and so to appear before the Lord,
and walk with him in the garment which he puts upon you;
O friends! keep this garment about you,
that ye be not stripped and robbed of that wherewith God once clothed you,
and so your nakedness appear, and men see your shame; and instead of being an honor,
ye become (any of you) a reproach to the name and truth of the Lord,
which is very honorable, and should be honored in and by us all.

The direction of this in my heart was to Friends in truth in Chalfont and thereaways,
among whom my heart hath been greatly comforted and refreshed,
who (some of you) had some knowledge of my former great misery and distress,
for want of the power and presence of the Lord,
and are now witnesses with me of his tender mercy and great salvation;
glory to him who sits on the throne, and to the Lamb whose kingdom is exalted over all,
who already reigns in righteousness in the hearts of a remnant; who sit down,
and find rest and peace, and true joy of heart, soul, and spirit,
under the shadow of his government, and cannot but sing and sound forth praises,
pure praises, honor, and dominion, and strength,
to the name and arm which hath done the valiant acts, bringing sin, corruption, death,
and the grave under, and bringing life and immortality to rule and have dominion over it;
so that he that is pure power and life is felt tabernacling and living in his people,
and he gives unto them to live in and through and with him;
and they cannot but sound praises to the power and glory of his life from day to day;
glory in the highest to our God, and to his Christ, forever and ever, amen, hallelujah!

====
