== Some Queries Concerning Compulsion in Religion

[.section-date]
1670

[.numbered-group]
====

[.numbered]
_Query 1._ Whether every man ought not to endeavor to be fully persuaded in his own soul
concerning the religion and worship which he performs and offers up to God?

[.numbered]
_Query 2._ Whether,
when a man is fully persuaded concerning the religion
and worship he ought to perform to God,
whether he is not then bound in conscience so to worship and serve God,
as he is fully persuaded in his own soul?

[.numbered]
_Query 3._ Whether, if a man should leave that way of religion and worship,
whereof he is fully persuaded in his own soul,
and should worship according to the law and worship of the country wherein he lives,
whether this would be accepted of the Lord,
and whether his soul would not be in danger of the
displeasure and wrath of the Lord therefor?

[.numbered]
_Query 4._ Whether God hath given any man or men power, by laws and penalties,
to compel men to worship him contrary to the belief of their
hearts and the full persuasions of their souls?
Is it not written, that whatsoever is not of faith is sin?
And hath God given any men power and authority to compel others to sin?
Surely the end of magistracy is to restrain men from sin, and not to compel men to sin.

[.numbered]
Query 5. Whether under the law of Moses,
the worship was not first made manifestly clear to men`'s hearts and consciences,
and they fully persuaded thereof,
before they suffered any penalties annexed for failing in it, or turning aside from it?

[.numbered]
_Query 6._ Whether under the gospel,
Christ or his apostles did ever compel any by outward force to their way of worship,
or give any rule for compulsion after their days.
Did not they say, they were not lords over men`'s faith,
but that there was one Lord and Master, even Christ,
to whom every man was to give an account?
Now, if men should commend us for worshipping as they teach us,
and by laws require of us contrary to the belief and full persuasion of our own souls,
and Christ condemn and punish us therefor, would it not go hard with us?

[.numbered]
_Query 7._ Was it not the beast that compelled men to worship,
and is he not branded therefor?
Rev. 13. But could he by his laws and penalties compel any,
whose names were written in the book of life, to his worship?
others indeed he did compel, and cause to worship, as may be seen in that chapter.

[.numbered]
_Query 8._ Is not Christ`'s kingdom spiritual?
Are not the weapons of his warfare spiritual?
Are they not mighty through God, to convince and establish men in the truth,
and in the way of the gospel worship?
Would Christ have any people forced by outward compulsion, to serve or worship him?
Whosoever will, let him come, saith he; and his people are a willing people,
and God loveth a cheerful giver and a cheerful worshipper.
Is not compulsion a great argument against that church and ministry that useth it,
that they want the spiritual weapons?
that they want the authority and power of the true church and ministry,
and so are fain to supply it by the authority and power of man?
For that which is of man, if it were not held up by man, would fall;
but the truth will grow and increase,
and that which is of God will stand and out-live all the violence and oppositions of men.
And one thing is worthy of very serious consideration concerning this worship,
which there is such striving to compel men to, which is this;
what kind of persons they are that dissent from it, and what they are,
for the generality, that so cry it up.
Are not many of them very loose, profane, swearers, cursers, excessive drinkers, yea,
some of them Atheists?
Is there not a ground of jealousy at least, if not a strong argument,
against that worship and way of religion which pleaseth these?

====

Can that which came from God, and is of God, please corrupt man?
And who are they that dissent from, and dare not practice it?
Are they not men of tender consciences, and that fear to offend the Lord,
and who seek after that religion and worship, wherein there is truth, life, virtue,
and power?
Now, which of these are likeliest to know the truth,
and to be taught of the Lord the true worship?

Oh that these things were seriously considered of!
for though men were wicked and profane themselves,
yet if they did not oppose that which is good,
but could suffer others quietly to serve and fear the Lord,
neither their sin nor danger would be so great.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, 19th of the Seventh month, 1670.

[.postscript]
====

He that ruleth over men must be just, ruling in the fear of God;
now he that is just and ruleth in the fear of God,
cannot afflict or punish any for fearing God,
or for worship which they perform to him in his fear.
Shall not he that made the world be worshipped by his children and servants,
according as he requires of them?
But shall the authorities of this world oppose him therein,
and with all their might stop and hinder (as much as in
them lies) his children and servants from obeying him?
Now, the Lord God of heaven and earth (who is above all,
and hath power over all) knoweth, that not in opposition to authority,
but in the fear of his name,
do we (who are called Quakers) meet together to worship him as he hath required of us;
and that if we should not so do, we should sin against him,
and be guilty of rebellion against the King of kings,
who is able to save and destroy body and soul forever.
And in this case it is that Christ hath bid us not fear him that can kill the body,
and can go no further, but rather to fear him who can kill both body and soul,
and cast them into hell.

Oh that the magistrates of this nation were just,
ruling in the fear of God! could they then afflict those that fear him as they do,
even such as are taught by him to love and pray for their enemies?
Is not there work enough for the magistrate`'s sword against manifest wicked men,
but it must still be turned against those that fear the Lord?
Will ye provoke the Lord to the utmost?
Are ye stronger than he?
Will ye put it to the proof, whether he be able to deliver his people or no?
Remember, the nations are but as the drop of a bucket,
and as the small dust of the balance before him?
What then is the wisdom and strength of one, two, three, or four nations,
to his wisdom and strength?

This is written in our hearts, that God is to have his due, as well as Caesar his;
and that God is to have his due in the first place, but Caesar after God,
and in subjection to God.
But if there be an absolute necessity put upon us by men (which they ought not to do),
either of disobeying God or Caesar,
we do really believe that question of some of the apostles, in this case,
to be very weighty, and worthy to be duly considered. Acts 4:19.
Whether it be right in the sight of God,
to hearken unto ye more than unto God, judge ye,
for we cannot but obey the Lord our God in what he hath required and doth require of us.
And truly, if we should do so, great and dreadful woe would be upon our souls,
and we should lose the enjoyment of God`'s presence,
and the peace which passeth all understanding;
which we cannot but value above our estates, liberties,
or whatever outward thing we can enjoy or possess in this world, above our very lives;
yea,
it were far better for every one of us to lose our lives in our
faithful testimony to the true worship of God in Spirit and truth,
which he hath taught us, and required us to practise and give our testimony to,
than to be found unfaithful and disobedient to him herein.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, the 12th of 7th Mo. 1670

====
