== CONCERNING THE DISPENSATION OF THE GOSPEL

OR THE

DISPENSATION OF THE SON IN SPIRIT

WHICH IS THE

LAST DISPENSATION


WHEREBY THE


Mystery of God, the Mystery of the work of Redemption, is finished in the Heart, all created anew inwardly, all subdued that is contrary to God, the Soul brought into, or translated into, the Everlasting Kingdom, and the Kingdom at length delivered up to the FATHER, and GOD becomes All in All; where all Names cease, and the Pure, Eternal Being is known, united to, and lived in, after an unutterable Manner.

+++[+++1678]

TO know the Father (even the God and Father of our Lord
Jesus Christ) as the fountain or original spring of light,
life, love, wisdom, power, holiness, righteousness,
and all spiritual and heavenly blessings:

To know the Son as the way to the Father, as the way to life, peace,
and blessedness in the Father:

To know the Son`'s Spirit, and the Father`'s also, whereby the Father draws to the Son,
and the Son brings to the Father; whereby the Son quickens, begets, renews, sanctifies,
destroys, cuts down, burns up that which is drossy, corrupt, and chaffy; yea,
not only the fruits of sin, but the very root itself, yea,
the very earth in which the root grows,
and the heavens that water the earth are consumed and pass away inwardly,
and a new heaven and a new earth is inwardly planted and formed,
wherein dwells righteousness; so that the cage of unclean birds,
the place where the dragons lay, is shaken and removed,
and the place of the wicked inwardly known no more;
but instead thereof there are new heavens and earth, even of the new creation of God;
which earth brings forth the increase of life, and fruits of life,
the seeds and trees of righteousness, of God`'s sowing, planting, grafting, pruning,
and causing to grow, that he may be glorified,--I say,

Thus to know the Father, thus to know the Son, thus to know the Holy Spirit of light,
life, love, and righteousness, etc., not notionally in the brain,
or with a comprehensive knowledge of the mind, but livingly in the heart,
in the light that shines from the Father and Son, in the life that springs from them,
in the love which is of them (for indeed, it is love that gives the bright,
purely sensible, and uniting knowledge),--this is precious knowledge;
and all knowledge of the very same things any otherwise than as coming from, and held in,
this springing life,
is of no comparison with the excellency (for nature and virtue) of this kind of knowledge.

Now, there have been two great dispensations of the Father, Son, and Spirit.
The one figurative, the other substantial.
The one called the law, the other the gospel.
For under the law the Father was made known, the Son made known, the Spirit made known;
but all in figures and outward ways of manifestation.
God was to that people of the Jews a fountain of living waters;
and when they forsook him, and trusted in lying vanities,
they forsook the fountain of their own mercies.
They then forsook the fountain of living waters,
digging to themselves broken cisterns that could hold no water.

So the Son was made known under the types and figures of the law,
as the King of righteousness, as the high priest of God,
as the prophet that God would raise up,
as the spiritual rock which yielded the spiritual waters, of which the soul was to drink.
And they that were athirst were to come to him and buy wine and milk of him,
and incline their ear to him, that they might hear and live,
and he would make an everlasting covenant with them, even the sure mercies of David.

So the Spirit of God,
which was typified under a pillar of cloud and fire in the wilderness,
did strive with man before the law, and was given to the Jews to instruct them,
and to plow up their fallow ground, and circumcise them inwardly,
and to wash their hearts from wickedness and vain thoughts,
that they might not lodge in them.

But all this was not properly (in the Spirit and
power of it) the dispensation of the law;
but hid in a mystery, and running under-ground, as I may so say.
This was from another covenant,
and part of another covenant than the covenant of the law, though in the time of the law.
For there was another covenant which Moses declared of,
besides the covenant of the law made in Horeb, which was the word of life,
or word of faith in the mouth and heart, which teacheth the substance of the law,
and also gives power to fulfill the righteousness of the law,
to them that hear and receive its voice, in the faith which it gives or begets.
And so the Father of Spirits was known in the time of the law.
Christ, the Redeemer, was known to live, yea to live in the heart in the time of the law.
The free Spirit, the Spirit of love was received,
and the presence of God felt and enjoyed by God`'s Calebs, Joshuas,
and Davids (by men after God`'s own heart) in the time of the law.
Moses had his meekness and tenderness,
and was made faithful in all God`'s house by the Spirit of Christ,
the meek lamb-like Spirit.

Now, when the shadows came to an end, Christ, the substance, was to come.
The everlasting King, the everlasting High Priest, the everlasting Prophet was to appear.
The everlasting Rock and holy Builder was to appear,
and raise up David`'s tabernacle in Spirit, and minister in the true sanctuary,
by his light, by his life, by his power, by his righteous Spirit.
There is not another tabernacle to be built, not another temple,
not another Jerusalem than the heavenly Jerusalem,
not another Mount Zion to be known or come to than the gospel Mount Zion;
not another God than God the judge of all in the gospel state;
not another word or law of life than the law which goeth forth out of Zion,
and the word that issueth out from this heavenly Jerusalem;
not another water to wash the soul with,
not another blood to sprinkle the conscience with, not another spirit to enlighten,
quicken, keep alive, and comfort, than the Spirit of light, life, and love from God,
which reconciles unto God, and brings into the gospel righteousness, rest, and peace,
and establisheth the soul therein.

So now, feeling the Spirit of the Son, and being led by him to the Father,
and the Father with the Son by the Holy Spirit, creating me anew, enlightening me,
quickening me, raising me in life, circumcising my heart to love, I am come to life,
and at rest in him that lives in me, and works in me, and gives me to live, and work,
and rest in him.
For there are the sabbath-day`'s works, even works of love, works of life,
works of righteousness and holiness,
works that the Lord works in the souls in whom he dwells and rests,
and which they in the pure rest, peace, and joy of life, work in the Lord their God,
who works all their works in them and for them.

Now, in this gospel dispensation, or this dispensation of the Son in Spirit,
all other dispensations are gathered into and wrapped up,
and thoroughly experienced by the soul that travels with and is led by Christ,
in this his gospel dispensation.

As first, There is Moses in Spirit known and travelled through.
There is the ministration of the law in Spirit inwardly commanding known, heard, felt,
received, before the gospel power is given to perform.
And here is hard travel and sore exercises.
Here the Father is known commanding, the soul consents and would fain obey,
but finds the law in the members rebelling against
the law which the mind hath a sense of,
and desires after.

Then afterwards comes the dispensation of the prophets,
wherein there are prophecies of a better state to come,
openings of the mercy and love which is to be manifested in the latter days,
at the end of these trials and exercises, wherein the soul hath promises from God,
that the righteousness shall be revealed, that power to become a son shall be given,
and the enemy`'s strength broken,
and the bowed-down soul raised up from under his oppression,
and the Lord shall tread him under the feet of the poor and needy,
and the hungry and thirsty shall be filled with righteousness,
and the meek come to inherit God`'s earth, and the beggar come from the dung-hill,
raised up in the power of life, to sit among princes,
even the princes in the heavenly glory of God`'s everlasting kingdom.

After this succeeds John`'s ministry in Spirit, even the levelling the mountains,
the raising up the valleys, the preparing the way for the King of glory,
that he may come in and reveal his glory inwardly.
For not in the time of the law inwardly, nor in the time of the prophecies inwardly;
but after the soul is exercised and prepared inwardly (that being wasted which hindered,
that raised up which lay low, that made straight which lay crooked,
that made plain that was rough,
and so the way is prepared and fitted for the great
appearance of the great God and Saviour,
in the pure, bright gospel glory, Spirit, and power),
doth the King come suddenly into his temple; not when the foundation is laid,
but when Zion is built up, doth God appear in his glory therein.
Read Isa. 40:3-5. and consider.
After John`'s coming in a body of flesh, and preparing the way by his outward ministry,
Christ came in a body of flesh, and was revealed as the only begotten of the Father,
full of grace and truth, by the life, Spirit, and power that that body was filled with.
And after John comes in Spirit, and prepares the way in any heart,
by the mighty and effectual operation of his ministry there,
then Christ comes after him in Spirit, in the great power and glory of the Father,
and the Father is revealed, and the Son also in the Spirit of light, life, love,
and righteousness, and the glory of the Lord is beheld with open face,
in the glass of life and righteousness, and the soul is changed into the same image,
and partakes of the heavenly glory, and is married or joined to the Lord,
to become one spirit with him,
and hath fellowship with the Father and the Son in the light of life;
and this is the gospel state and glory, and there is not another.

Now take one scripture more which sums up all dispensations,
and sets up the dispensation of the Son in Spirit as the last,
as the dispensation of the last days.
It is Heb. 1:1;
read but what things are spoken of to be brought to pass in the
last days of the great gospel glory to be revealed then,
of the perfect redeeming to God, and centring in him, of being married to him,
and becoming one with him, etc., and of the Son`'s being the minister in the gospel state,
by the Spirit and power of the endless life, to bring it all forth,
and accomplish it in the husbandry and building of God.
Consider the place; at sundry times, and in divers manners,
God spake in times past by Moses, by the prophets, by John;
but now the last days are come, now the last dispensation is come,
now the covenant wherein God himself is the teacher is come,
now the time of building the Zion, the Jerusalem,
wherein God himself will dwell forever, is come;
now the light of the city of God is come, which is an eternal light,
an unchangeable light.
Now, the Spirit of love, which brings up the gospel life, is come,
and edifies the holy gospel building, in the gospel love and life.
Oh, the light, oh, the life, oh, the love, oh, the righteousness, oh, the divine nature,
which is now revealed and partook of in the Son!
He is the brightness of the Father`'s glory; and thither he brings his.
What would ye have more?
He destroys antichrist inwardly, by the brightness of his coming or appearing.
Oh, the desolations that he makes inwardly of sin and iniquity in the hearts of his!
He is the express image (or engraving) of his Father`'s substance; and he makes thee,
who art one with him in his Spirit of life and love, of the same image with him.
He translateth thee out of Satan`'s image, into his very image.
His light, his life, his love, his righteousness, his divine nature,
doth not wax old as a garment, but endure and remain the same forever.
He is Alpha and Omega.
There was nothing before him, nor shall be after him.
There is no other thing appertaining to life and godliness,
but what he now dispenseth in the gospel; no other kingdom,
but what stands in the power of the life and righteousness,
which is now revealed in the peace, love, and joy of the Spirit.
The gospel building is his house; and he is faithful in all his house, as a Son,
having received all power from his Father, to gather fully, to preserve fully,
to build up fully, to leaven fully with life and righteousness, even in soul, body,
and spirit, to lead into the Holy Land, and to enable to keep the holy sabbath there,
even to cease from sin, and everything that burdens the life, and to rest in God,
and not work any thing of ourselves any more, but to feel the Spirit of life, love,
and power work in us.
And his yoke of life, his yoke of love, his yoke of the power,
is the pure gospel liberty comprehended in.
The Lord Jesus did appear in flesh; but now he appears in Spirit, and is Spirit;
giving himself to be life and Spirit in his.
And where the Spirit of the Lord is, there is liberty;
and everything which is of a fleshly nature, which deceiveth and imbondageth,
wherein the pure liberty is not, he discovereth, and keepeth his out of,
that so they may stand fast in the pure liberty of the light, life,
and love of his Holy Spirit, wherewith he maketh his free.

I+++.+++ P.

The 18th of the 9th Month, 1678

