== Some Experiences

[.heading-continuation-blurb]
Which it hath pleased the Lord to give me concerning his way,
his Truth, his Church and People,
against whom the Gates of Hell cannot prevail.

First, IT hath pleased the Lord to manifest to me,
that there is a light wherewith he (in his tender mercy, love,
and good-will) enlighteneth mankind.
This light I have found my own soul enlightened with, even from my very childhood,
though I never took notice of it to be what it is, till the Lord manifested it to me.
But ever since it pleased the Lord to manifest it to me, and to turn my mind to it,
I have found it to shine inwardly in my heart,
even as the outward light of the sun shineth outwardly to the outward eye.

Secondly,
By this light it hath pleased the Lord to give me
the distinction of things inwardly in my own heart.
The Lord hath shown me by it evil and good in my own heart,
and taught me to choose the good, and refuse the evil.
So that as my eye hath been turned to this light, and kept to this light,
I have known and walked in the way of life;
for the power which hath appeared in this light, hath created me anew,
made me a child of light, and taught and caused me to walk in this light,
as God is in the light.
And in this light I have experienced fellowship with the Father who is light,
and with his Son who is light also, and with all the children of light.

Thirdly, In this light (being gathered out of darkness into it,
and abiding in it) I have had remission of sins.
For no sin is laid to the charge of any soul that abides in this light,
but only to such as continue in darkness, or go out from it into darkness.
This I have had the constant experience of from my
first distinct knowledge of God`'s truth;
for I never found, at any time, any condemnation,
while I abode in the pure light of God`'s Holy Spirit, and blessed witness;
but if at any time, I hearkened to the enemy, the prince of darkness,
and went by his allurements into darkness, I still met with condemnation there.

Fourthly, In this light I have received power to become a son to God.
Oh, it is unutterable to relate what power is here received against the soul`'s enemies,
and to do the will of God!
Indeed, in the light there is power; yea, full power, suitable to every soul`'s condition.
There needs no more power (no not to the highest condition) than what is laid up,
and to be received in this light.
All the power of darkness is communicated in the darkness to the children of darkness;
and all the power of light is communicated in the light to the children of light.
In the light there is a holy will and ability given daily more and more,
and the unholy will and ability (which troubleth the holy seed) removed out of the way.

Fifthly, In this light I know the true church,
the holy gathering by the gospel spirit and power;
for none are the true church in the gospel days but such.
The law church was a company of Jews after the flesh, circumcised in flesh,
to keep the outward law of commandments;
but the gospel church is a company of believers after the Spirit, circumcised in Spirit,
to keep the inward law, even the law of the Spirit of life in Christ Jesus,
which makes free from the law of sin and death.
So that all the gospel church are children of the true woman,
growing up in the holy liberty from the bondage of sin and corruption,
unto the royal law of holiness and righteousness.
So that being in the light, I see the children of light,
and know that the holy gathering, even the gospel church, are such,
and that none else can be of the gospel church,
having (out of the light) nothing of the nature of the gospel church or Spirit in them.
Ye may as well make a man without the nature of a man,
as a Christian without the nature of a Christian.
He was not a Jew outward under the law, without the nature of a Jew outward;
nor is he a Jew inward under the gospel, without the nature of a Jew inward.
And as the law church consisted of Jews outward,
so the gospel church consists of Jews inward; which are children of light,
and not of darkness, and can be known only by them who are in the true light.
So that the Lord having mercifully gathered me into his gospel light,
these things (in his gospel light) have been clearly seen by me.

Sixthly, In this light I know the gospel worship,
the worship which lies not in the darkness of man`'s apprehensions,
but in the light which shines from God in the heart.
For the children of God are taught in the light,
know God their Father in his own pure light, and worship in the light,
wherein they are taught by him to know him.
They worship in the truth.
They are led by the Spirit of light and truth, out of darkness, out of deceit,
out of all kind of error and unrighteousness; and they worship in truth,
and in the Spirit, into which they are led, and in which there is no deceit nor error.
They gather together in the Son`'s name (in his living name, oh,
wait to understand that!). And there the Son is in the midst of them,
and his life and Spirit intercedes in them;
and in his name they offer up the righteous sacrifices, the holy sacrifices of life,
and the pure incense, in which the Father is greatly delighted,
and smells a sweet smell and savor of rest.

Seventhly, In this light I have experienced the good conscience,
even the conscience which answers to truth, and will not answer to unrighteousness.
Indeed in this light I have felt my heart sprinkled from
an evil conscience (I testify it in deep humility of spirit,
and in great thankfulness towards the Lord).
The darkness defiles and stains; but in the pure light the heart is washed, cleansed,
and sanctified, from whence ariseth the answer of a good conscience towards God.
And in this light the conscience is still kept good;
but though it hath its habitation in the light, if it keep not its habitation,
but go out from thence into the darkness, it is soon defiled and corrupted again.

Eighthly, I have, and (bless the Lord) daily do still, experience faith,
the heavenly faith of the new birth, the precious gift of God to his own children,
in this pure blessed light of the Son of God,
which shines from the heavenly glory into the hearts of his redeemed ones.
Unbelief came at first from the darkness, and lodgeth in the darkness,
issuing thence into those that give ear to the dark spirit;
but faith springs from the holy root of life in the heart.
Here I cannot but believe, and also know him in whom I do believe,
who is the holy power of life and light,
who opposeth and overcometh the prince of darkness, who hath the power of death.
And in the light God carries on the work of faith with power; and unbelief,
which stops it, is not able to enter the minds of those,
who are stayed upon the Lord in his pure light.

Ninthly, In the light I taste and enjoy the pure peace, which passeth man`'s understanding.
In the darkness is condemnation and trouble, as man`'s mind comes to be awakened;
but in the light is righteousness, justification, and peace,
to all that dwell and abide there.
Perfect peace the mind here grows up into, which the enemy cannot break or interrupt.
Indeed, in the darkness, out of the light, the peace that is there is easily broken;
but never in the light is the true peace broken.

Tenthly,
In the light I have experience of the killing or
mortifying of that which is contrary to the light.
"`I kill, I make alive, saith the Lord.`" Indeed he doth so in and by his light.
Doth not light expel darkness in the figure?
Much more doth it so in the substance.
Light drives away darkness, banisheth darkness, destroyeth darkness,
in the mind that is truly enlightened by the Lord, and singly gives up to his light.
Oh! the desolations of darkness (the works of darkness, the power of darkness),
that God makes in the hearts of such as are sensible
of and subject to the light of his Son shining there.
The Lord there cuts his work short in righteousness,
making an end of the kingdom of darkness, revealing his own kingdom instead thereof,
and gathering and translating the mind thereinto.

Eleventhly, In the light I have experience of the new creation in Christ Jesus,
even the passing away of the old things, and the new things coming instead thereof.
The old heart gone, the hard heart gone, and a new and tender one instead thereof.
The old law of sin and death taken out of the way,
and the law of the Spirit of life in Christ Jesus received in the place thereof.
And the fear of the new covenant put into the new heart (in which
is the beginning and perfection of the heavenly wisdom),
and the Spirit of God put within, to enlighten, enliven,
and fill the mind with life and righteousness,
and cause it to walk with God in the new and living way,
and to know his statutes and judgments, and do them.

Twelfthly, In the light the gospel love is known and springs.
In the darkness is enmity; but in the light is love.
It is true indeed, that here the whole law is fulfilled,
even of loving the Lord God with all the heart, soul, mind, and strength,
and one`'s neighbor as one`'s self.
Yea, here one is not only commanded to love enemies, but taught and enabled so to do.
Yea, keep but here in the light, no enmity can spring up,
but only love to the greatest enemies, whom we have no coals of wrath,
but only of love to heap upon.

Thirteenthly, Here I meet with and partake of a cool, meek, patient, tender, gentle,
quiet, lowly spirit, which is of the Lord, and of much esteem with him.
This is the Lamb`'s nature, who is light;
and this also is their nature who are of the Lamb, and walk in the light of the Lamb.
All Esau`'s roughness, all Ishmael`'s disdain and scoffing,
all Cain`'s envy and cruelty towards his brother, is of the darkness, whereof Cain,
Ishmael, and Esau are, and wherein they walk, and their offspring;
but this is not found in them who are light in the Lord, and who walk in the light,
as he is in the light.
And in patience to possess the soul, and to be tender towards sinners, meek, quiet,
and humble before the Lord, and of a gentle spirit towards all.
Oh! who, besides the children of light,
know the preciousness of being created by the Lord, and of thus walking before him,
in the light of the Lord Jesus, in the renewings of the mind by him,
in the life and power, wherein he anew createth and changeth,
these things become natural.
For in the light, whatever is of the darkness, whatever is corrupt,
whatever is of the devil`'s kingdom,
is discovered and removed from them that take up the light`'s yoke;
and a contrary nature planted in the mind instead thereof,
which brings forth quite other fruits,
even of a contrary kind to what the darkness brought forth before.
So that as it was said of Christ, Behold the Lamb of God; so it may be said of them,
behold the lambs of God, who are sweet, meek, gentle, lowly in heart like him,
bringing forth fruits like him, and walking like sheep among wolves, as he also walked.

Lastly, (To mention no more) Here, in the light, I meet with certainty, assurance,
satisfaction; yea, infallibility.
I meet with the evidence and demonstration of God`'s spirit, which is infallible.
I meet with God`'s witness, which is an infallible witness.
I meet with God`'s Spirit, which is an infallible Spirit,
who infallibly leads into all truth, and infallibly guides in the truth.
I meet with an infallible Shepherd, who hath an infallible voice,
and gives to his sheep an infallible ear, wherewith they infallibly hear.
He opens an infallible eye, and gives to it an infallible sight of God,
and the heavenly mysteries of his kingdom.
The Spirit breathes infallibly, begets infallibly, leads infallibly, creates a new heart,
a right spirit; which heart, which spirit, is of God`'s infallible nature, like him;
for that which is born of the Spirit is Spirit.
That which is born of man`'s fallible spirit and wisdom is fallible;
but that which is born of God`'s Spirit and heavenly wisdom,
is of the nature of his Spirit and wisdom;
and hence it is that wisdom is justified of her children.
The apostle speaks to the Galatians of having begun in the Spirit, chap.
3:3. and did they not begin in that which is infallible?
And if they went on in the Spirit, did they not go on in that which is infallible?
I never found the light deceive me, nor did I ever find the birth of God`'s Spirit,
the holy elect seed, deceived in me.
And the new and living way, wherein this birth walks, is infallible,
in which there is no erring by those who eye the Lord, and follow his Spirit therein.
This is the way cast up (the way of holiness, life, and peace),
for the ransomed and redeemed of the Lord to walk in, in the gospel days,
in which the wayfaring men, though fools, shall not err, Isa. 35:8. The Lord,
who hath promised, is able to make it good.
The Lord make it more and more manifest, and bring more and more people into it,
and keep them in the guidance of his blessed Spirit of truth,
that they may see his light, and walk therein,
and not let in any temptations from the spirit of darkness, and so follow him,
and miss of the guide unto, and the preserver in, the new and living way.

=== POSTSCRIPT

I DO not say that I, as a man, am infallible, or that any of us as men are infallible;
but God`'s light, God`'s grace, God`'s truth, God`'s Spirit, God`'s wisdom and power,
is infallible; and so far as we partake of that, are gathered into and abide in that,
we partake of that which is infallible, and are gathering into and abide in that,
which is infallible.
And oh! let not men rest in, or be contented with, that knowledge which is fallible,
but press after unity and fellowship with the Lord in his infallible spirit;
there being no true union nor fellowship with him in any thing that is fallible.

Oh that Protestants, Papists, Jews, Turks, Indians, did all know and own this light,
that there might be an end of the darkness and misery,
wherewith mankind hath been so long overwhelmed;
and happiness both in particular nations, and in the whole world,
might be experienced in the stead thereof.
For men`'s erring from the light and spirit of God,
hath been the cause of all their misery;
and their returning to the light and Spirit of God (from which
all have erred) will take away the cause of their misery,
and in it (as they faithfully subject to the Lord
and travel therein) they shall find his power,
love, and mercy revealed, towards their restoring unto happiness.

I+++.+++ P.

Thirty-first of the 5th Month, 1679.
