== CONCERNING THE TIMES AND SEASONS BOTH WHICH HAVE BEEN, AND WHICH ARE YET TO BE

+++[+++1679]

WHEN God made man in his own image, placing him in paradise,
and giving him dominion over the works of his hands;
then was a time of great joy to Adam and Eve, and should have still been so to them,
and all mankind, had they continued in the state wherein they were created.

When Eve, and by her means Adam, hearkened to the voice of the serpent,
disobeyed the Lord their Creator, aspiring after wisdom,
and the knowledge of good and evil, out of God`'s way;
then was a season of misery to Adam and all his posterity;
the holy and heavenly image being lost, and a cursed image gained in the stead thereof,
and so man thrust out of paradise, and the blessedness thereof, into the earth,
which was cursed for man`'s sake.
So in this state, sin and the curse is man`'s portion,
instead of the holiness and blessedness, which his Creator had allotted him.

When God promised the blessed seed, and revealed himself to the fathers in the faith,
begetting sons to himself, who heard his voice, obeyed and walked with him;
then was a blessed time and season to them, though sin and death reigned in the world.
But when the sons of God also forgat him,
and mingled their seed with the corrupted world, then the deluge came,
sweeping away all but Noah with his family, and the creatures saved in the ark.

When the Lord chose the Jews to be a people to himself, from amidst all nations,
delivering them by his out-stretched arm out of Egypt, destroying Pharaoh, and his host,
and led them through the wilderness, fitting the succeeding generation for the good land,
bringing them into it, blessing and establishing them in it,
while they feared him and walked in covenant with him,
then was a blessed time and season with that people.
But when they provoked God, brought his judgments often,
and at last utter ruin and desolation upon themselves,
then were seasons of great misery and distress, and at last of utter destruction to them.

While the Gentiles were cast off, and were no people,
being of the corrupt seed which God hath not chosen, nor had any delight in,
and while they knew not the living God, but worshipped stocks and stones,
and so were liable to the pouring down of his wrath and indignation upon all occasions,
and to utter ruin and destruction, when their iniquities were full,
it was a sad time and season with them, wherein they were estranged from the life of God,
and his holy covenant of promise, and were without God in the world.

When the Lord preached the gospel to the Gentiles, by his holy apostles and ministers,
manifesting Christ to them, the hope of glory, the mystery hid from ages and generations,
ingrafting them into the holy vine and olive-tree,
giving them to partake of the sweetness and fatness thereof,
even of the riches of his grace and goodness in his Son, who is eternal life,
and gives eternal life to all his; then was such a time and season of love, grace, mercy,
and peace from God our Father,
and from the Lord Jesus Christ (both towards Jews and Gentiles)
as had not been known in the world before.

When the Christian church apostatized, the love in many waxing cold,
men minding the name of Christianity, and form of godliness, but not the life and power,
and so the Lord was provoked against them, to remove their candlestick out of its place,
and give up the outward court to the Gentiles,
and so the Spirit was lost and departed from, the life lost, the power lost,
the everlasting gospel hid from men`'s eyes,
and darkness and men`'s inventions set up instead thereof, in nations, tongues,
and people,
and the witnesses to any appearances of God`'s living truth and holy power persecuted;
then was a sad time, then was a season of death and darkness reigning over all nations,
kindreds, tongues, and people, and the cup of fornication drunk by them all,
and all generally bewitched by it,
except those whose names were written in the Lamb`'s book of life.
This was the greatest time of darkness (wherein the mystery of iniquity most
deeply wrought in the deepest ways of deceit) that ever was in the world.

When the church comes again out of the wilderness,
when the Spirit and power of God build up again the gospel church in its primitive glory,
when the everlasting gospel is preached again to all nations, kindreds, tongues,
and languages, in the authority and power of God,
when the Spirit of the Lord is poured out plentifully on his sons and daughters,
and they prophesy, walk, and live in it, when God dwells and walks in his people,
and his true light shines in them, dispelling the darkness thoroughly,
and filling them with the glory and majesty of the Lord,
and they ascend up out of the world`'s spirit and nature, into his Spirit and nature,
even in the sight of their enemies,
and the full wrath of the Lamb be poured out on Babylon,
and the full glory revealed in Zion;
then shall there be such a day of brightness and pure,
heavenly glory as shall dazzle the eyes of all beholders.

But the passing away of this night,
and the bringing forth of this day will be very terrible and dreadful,
both in particulars and in nations.
The kingdoms of this world must indeed become the kingdom of our Lord and of his Christ;
but it will require great power to bring it about.
The wrath and strength of the spirit of darkness will be
working against the Lord and his power to the utmost;
and the more it works against the Lord and his power, the more will the Lord`'s power,
and the wrath of the Lamb be revealed against that spirit,
and against all its devices and undertakings against the counsel and power of the Lord.
Oh! blessed are they that are of the Lamb`'s nature and Spirit,
of his righteousness and meekness;
for the wrath of the Lamb will not be kindled against them,
but he will be a munition of rocks unto them, and their inward life shall be preserved,
and they shall enjoy peace with the Lord in the midst
of all that shall outwardly befall them.

Mesborow in Kent, 22nd of the 6th Month, 1679

The everlasting gospel hath been preached in this nation (and also other nations),
just after that very manner as it was foretold it should, Rev. 14:7.
"`Saying with a loud voice, Fear God, and give glory to him;
for the hour of his judgment is come; and worship him that made heaven and earth,
and the sea, and fountains of waters.`"

Now, they that have heard this blessed sound of the everlasting gospel,
and have learned to fear God with this fear which the gospel
calls for (which is the fear of the new covenant,
which is not taught by the precepts of men,
but which God puts into the heart in the new covenant), and to give glory to him,
bowing to him, and learning righteousness of him,
in the hour of his judgment upon their souls, and have worshipped him, and him only,
in his Spirit and truth, which is the gospel worship,
or the worship of God according to the everlasting gospel;
these are accounted with God knowers and obeyers of the gospel of our Lord Jesus Christ.
These are a peculiar people to God, whom he hath taken an especial care of,
and whom he will hide under the shadow of his wings, and in the secret of his pavilion,
while his wrath is poured out upon peoples and nations.

But others that have not been gathered under the shadow of God`'s wings,
by the preaching of the everlasting gospel,
who have not known or obeyed the sound thereof; when the storm comes,
when the wrath of God is revealed against all ungodliness
and unrighteousness of men (whereof this nation is full,
and hath had several tokens of God`'s great displeasure for a long time),
they will not find a shelter,
though they flee to the rocks and mountains to hide
and cover them from the wrath of the Lamb,
but will lie open to the stroke of the overflowing scourge,
which useth to overflow nations,
after such a deluge of sin as hath long overflowed this nation.
Oh that men could hear the voice of the rod, and him who hath appointed it,
and seek a hiding-place, and enter into the chamber of rest and quietness with the Lord,
until the indignation be overpast!

Now, unto any whose hearts are touched with the fear of the Lord,
and the sense of his righteous judgments and wrath due to
this nation (which doubtless have come in part already,
and are coming faster and faster, and entering into the very heart and bowels of it),
and who would escape the stroke of God`'s dreadful hand,
and find inward rest and peace with him in the day of outward trouble and sore distress;

To such, a few words of advice, very early this morning, lay upon my heart.

First, Seek the Lord (oh, do not seek the world,
but seek the Lord who redeems out of the spirit of the world, where the wrath comes,
and upon which it is to seize!). And "`seek righteousness, seek meekness;
it may be ye shall be hid in the day of the Lord`'s anger.`" Zeph. 2:3.

Secondly, Wait upon God, that ye may learn of him to "`keep your heart with all diligence,
for out of it are the issues of life.`" If ever ye know the issues of life,
ye must know them there; and if ye know the issues of life there,
and they sweetly issue up, and flow into your souls,
they will refresh and delight you in the midst of all the sore afflictions, troubles,
and distresses, which can befall you outwardly.
Read Psa.
46. and consider.

Thirdly, Mind who knocks at the door of your hearts,
whether it be the destroyer or Saviour of the soul;
for both of these knock often at the door, but men are not aware thereof.
And wait to receive power from God, to be faithful door-keepers,
that ye may keep the door of your hearts shut against the enemy,
when he knocks with any temptation, and may open them to the Lord,
when he knocks with any motion or pure stirring of life.

Fourthly, Wait to know, and experience truly, and also more and more,
the Christian Spirit and state, the state of a servant to the Father, and his Son Christ,
the state of a soldier, the state of a pilgrim and holy traveller;
to be doing the Lord`'s work (the Lord`'s will, and not your own),
to be fighting the Lord`'s battles, against his and the soul`'s enemies,
and to be travelling farther and farther out of the spirit, mind,
and nature of this world (wherein the kingdom of darkness stands), into God`'s Spirit,
where the kingdom of the dear Son is known and entered into,
by those that deny their own wisdom, and become as little children.

Many have the form of godliness, who are not accepted of the Lord;
but such only as know God`'s power, and are led by his Spirit,
such are indeed in Christ Jesus; for the holy power grafts the soul, mind,
and spirit of a man, into the holy stock and root of life.
And such know the new creation in Christ, and the works of the new creation,
which they perform and walk in (being God`'s workmanship, created in Christ Jesus,
unto good works).
And here the old things pass away (which can pass away by no other means,
but by the revealing of the arm and power of God inwardly in the heart,
and by its effectual operation there), and so all things become new.
Now, where all things become new, where the heart is new, the mind and spirit new,
the desires new, the joys and delights new, the life and conversation new,
and the soul walks before the Lord, not after the flesh, but after the Spirit,
even in the newness thereof; what is there for the wrath of God to seize upon?

Though the Lord be a consuming fire, yet it is to his enemies, to sin,
to unrighteousness, to the chaffy, earthly mind and nature; he is not so to his children,
to the wheat, to the holy seed, to them that are new-created and cleansed by him,
to them that fear him, love him, walk with him, keep his commandments,
obey the gospel of his Son, denying all for him,
and following the Shepherd and Leader of their souls,
out of all untruth and unrighteousness, into all truth and righteousness.
Surely, these shall not only be able to abide, but dwell with the devouring fire,
and everlasting burnings; and that shall be their safety and shelter,
when the flames thereof break forth to consume and burn up the chaff everywhere.

25th of the Sixth Month, 1679


=== POSTSCRIPT

THE gospel religion is very precious,
being inwardly felt and experienced in the life and power of it;
but a bare profession of it, out of the life and power of godliness,
is of no value in the sight of God, nor is it of any profit or advantage to the soul.

ISAAC PENINGTON

