== Letters of Isaac Penington

=== TO S. W.

DEAR FRIEND,

I ever had a love to thee, and a deep sense of the serious work of God upon thy heart,
and the upright desires of thy soul after Him.
And, that the Lord should yet preserve thee alive,
in the midst of so great and languishing weakness, is wonderful in my eye, and I hope,
hath a tendency of some honor to his name, and good to thee.
I have often inquired of late concerning thee,
and was glad to understand what I inquired after, by a letter from thy own hand;
upon reading whereof, in the retired sense of my heart, I felt love arise to thee,
and breathings to the Lord for thee; and, oh that thou mayst fully feel,
and be joined to the seed of life, the seed of the kingdom, which our Lord Jesus Christ,
in the days of his flesh, did not disdain to be a prophet of.

O my dear friend! let not any part of thy life lie in notions above the seed,
but let it all lie in the seed itself,
in thy waiting upon the Lord for its arisings in thee, and in thy feeling its arisings.
Oh! what becomes of flesh, and self, and self-righteousness, when this lives in the heart?
My religion, which I now daily bless my God for, began in this seed; which,
when I first felt, and discerningly knew from the Lord, my cry to him was, oh,
this is it I have longed after and waited for!
Oh, unite my soul to thee in this forever! this is thy Son`'s gift from thee,
thy Son`'s grace, thy Son`'s truth, thy Son`'s life, thy Son`'s Spirit!
I desire no more, than to be made nothing in myself, that this may be all in me:
and what I meet with and witness here,
what I feel the Lord Jesus Christ to be made to me here, none knows,
or possibly can know, but they that have felt the pure power of the Spirit of life,
and have been led by it into the same holy and blessed experience.

Ah! sin hath no share here, in this blessed seed;
but is excluded by the life and power which is stronger than it.
Here Christ is formed in the soul, of a truth,
here the black garments of unrighteousness, yea, of man`'s righteousness too, are put off,
and the white raiment put on; here the holy image is brought forth in the heart,
even the image of the dear Son, which partakes of the divine nature of the Father;
here the soul is new created in Christ Jesus, here is no deceit in any kind met with,
but only truth from God, even the true life, light, virtue, power,
of the Lord Jesus Christ, as livingly felt in the heart,
and as effectually operating there, as ever the power of sin did.
Oh that thou mightst daily discern this, and feel this to grow up in thee more and more,
and die to all notions, even of the heavenly things themselves, out of this;
that thy soul may fully live in the life, Spirit, and power of the Lord Jesus Christ;
and nothing but his life, Spirit, and power may live in thee;
to the glory of God the Father,
and to the great joy and gladdening of thy heart in his presence!
Amen.

Thy friend, in the true, sincere love of the heavenly, everlasting seed.

I+++.+++ P.

13th of Twelfth Month, 1678

=== TO THE LADY CONWAY

DEAR FRIEND,

In tender love, and in a sense of thy sore afflictions and exercises,
I do most dearly salute thee; desiring for thee,
that the work of the Lord in thy heart may not be
interrupted by any devices of the enemy;
but that it may go on and prosper in thee,
in the springing up of the pure seed of life in thy heart,
and in the powerful overturning, by the mighty arm of the Lord,
of all that is contrary thereto in thee.
Oh that thou mayst daily feel that holy birth of life, which is begotten by the Father,
and lives by faith in him!
I say, oh that thou mayst daily feel it living in thee,
when temptations and trials on every hand increase--feel the birth of life,
which will cry to the Father, "`Lord, increase my faith!`"

Though sorrows, heaviness, and faintings of heart ever so much increase; yet,
if thy faith increase also, it will bear thee up in the midst of them.
I would fain have it go well with thee, and that thou mightst not want the Reprover,
in any thing that is to be reproved in thee; nor the Comforter,
in any respect wherein thy soul wants comfort; nor the holy Counsellor and Adviser,
in any strait or difficulty which the wise and tender God orders to befall thee.

Ah! that thou mightst come to feel the daily wasting of sin and death,
and the daily springing of life and holiness in thy heart.
The pearl is worth thousands of worlds,
with the greatest earthly glory and pleasure imaginable.
Oh that thou mayst be taught of God to discern it more and more, and to buy it,
and to come into the enjoyment and possession of it!
The Lord manifest Zion more and more to thee, and show thee the glory of it,
and set thy feet towards it; and put into thy heart to seek of him the way to it,
renewing thee more and more in the spirit of thy mind,
whereby the way comes clearly to be discerned, and faithfully walked in;
that thou mayst witness, daily, the everlasting covenant of life and peace,
even the sure mercies of David.

The desire of my soul is, that thy afflictions, which how grievous soever,
yet are but momentary, may fit thee for, and work out, an eternal weight of glory,
for thy soul to inherit in another world, forever.

I remain a sympathizer with thee in thy sufferings;
who desire all the advantage and blessings from the God of my life may come to thee,
which hardships, temptations, and trials prepare the heart and make way for.

I+++.+++ P.

14th of 12th Month, 1678

=== POSTSCRIPT

My dear Friend,

Some time after writing the foregoing, this arose in me to thee.
If the Lord, in thy waiting upon him, to search and try thy heart and ways,
shall please to show thee any thing amiss therein; mind this counsel on my heart to thee:
Be not looking at it too much, on the one hand, or excusing it, on the other hand;
but sink down beneath thyself, retiring thither,
where thou mayst receive from the Lord true judgment concerning it,
and also strength against it.
And know this, in the holy experience; that thou must be weakened by the Lord,
and be contented in or with thy weak and distressed estate,
if thou wouldst receive mercy and strength from him.
And the more thou art weakened and distressed, the more thou art fitted for,
and the more abundantly shalt thou partake of, his mercy and strength;
waiting upon him in the meek, quiet, patient, and resigned spirit,
which he will not fail to work thy mind into; that, in the issue of all,
thou mayest reap the quiet fruits of righteousness and heavenly peace from his hand.
Amen, so be it from the Lord to thy soul!

=== TO S. W.

DEAR S. W.

I have ever had a love to thee,
and have many times been filled with earnest desires for thee;
that thou mayst know the Lord in his own pure teachings,
and travel into and dwell in the fulness of the kingdom of his dear Son;
and that thou mayst be blessed with spiritual blessings in heavenly places in Christ.

In order to arrive here, thou must wait to know God and Christ,
in the mystery of their Spirit, life, and power; and by that Spirit, life, and power,
find the secrets of the mystery of darkness searched and purged out,
and the mystery of godliness opened and established in thy heart,
in the room thereof;--Christ formed inwardly; the soul formed, yea,
and created inwardly anew in him; a real transplanting into his death,
and a real feeling of his springing and rising life; and an experience of the sweetness,
safety, and virtue of his rising life; and daily to be sensible,
what it is in the risings of the life and power;
and so be only what thou art made and preserved to be, in the light, grace, life, virtue,
and power of the Lord Jesus Christ; and to feel him remove any thing that is unrighteous,
and clothing thee with his pure life, Spirit, and righteousness.

Oh! this is indeed the pure, precious, living knowledge of the Lord Jesus Christ;
which all the outward knowledge tends to lead to, and is comprehended and ended in.
This is the excellency of the knowledge of Jesus Christ our Lord,
which Paul was so ravished with, and counted all things but dross and dung for.
Now, that thou mayst obtain this, mind the inward appearance, the root, the fountain,
the rock within, the living stone within,--its openings, its springings,
its administering life to thee;
and take heed of running into the outwardness of openings concerning the heavenly things;
but keep, oh learn to keep, oh mind to keep, in the inwardness of life within!
This is the everlasting habitation of the birth which is begotten and brought forth,
bred up and kept alive, alone by the presence, power, and operation of the living Spirit;
and the Lord Jesus is that Spirit, as really as he was man, even the holy, heavenly,
immaculate, spotless Lamb of God.
And in this state, life reigns in the heart, and the horn of the Holy One is exalted,
the head of the serpent crushed, yea, Satan trod under foot, by the God of peace;
who would have his children dwell in the sweetness and fulness of the gospel,
in the peace, life, righteousness, and joy of his blessed Spirit and power.

Oh! who would not desire after and wait for and walk with the Lord,
towards the obtaining and possessing of these things?
All the promises, in Christ, are yea and amen.
Inward victory is promised; the inward presence of God is promised;
God`'s dwelling and walking in the soul is promised; Christ supping with the soul,
and the soul with him, is promised; putting the law in the heart, and writing it there;
putting the pure, living fear into it; yea, also the holy, powerful Spirit into it,
which can cause it to walk in God`'s ways,
and to keep his righteous judgments and do them:
and he is able to do this work in the heart;
for what cannot the Spirit of judgment and burning consume and burn up within?
Yea, all these things are promised.
He can cause the soul to rejoice in the Lord, and work righteousness,
and to remember the Lord in his ways,
as some were taught and enabled to do in former times; Isa. 64:5; yea,
he can bring into the way of holiness, the King of glory`'s highway,
into which no unclean thing can enter, and +++[+++can]
keep undefiled therein; and they that are kept undefiled therein taste the sweetness,
blessedness, purity, and holy pleasures thereof.

I would fain have my own soul and thine, and all the real, serious,
faithful people of God experience, and be able to say with David, that which,
after his many trials, afflictions, troubles, temptations, and grievous fall,
he was able to say, in relation to his walking with the Lord,
"`For I have kept the ways of the Lord, and have not wickedly departed from my God.
For all his judgments were before me, and I did not put away his statutes from me.
I was also upright before him,
and I kept myself from iniquity.`" Ps. 18:21-23. Oh! this is precious,
when a man comes to know his iniquity, wherein the enemy`'s strength lies as to him,
and whereby the enemy hath most advantage to tempt and gain ground on him,
brought down and subdued.
Certainly, when one gains strength from God, to overcome the enemy here,
and to keep out of this, he comes very near to the keeping of himself,
in and by the virtue of the Holy Spirit and power, so as the wicked one cannot touch him,
and nor draw him to touch any unclean thing.
If that be indeed put off, wherein the enemy`'s power lies; and that indeed put on,
wherein the strength of the Lord Jesus is revealed;
and the soul be really in the possession of, and abide in this state;
how can it be but strong in the Lord, and in the power of his might;
and witness the good pleasure of the goodness of the Lord fulfilling,
and the work of faith going on with power, daily, more and more;
a little measure whereof, kept to, removes the mountains inwardly,
and gives strength over the enemy.
How, then, doth it increase and grow up in life and virtue,
and in a sensible understanding and experience of the name of the Lord Jesus?
Is there not, in this state, a feeling of remission of sins, a feeling of redemption,
a feeling of reconciliation, a feeling of oneness with God in Christ,
a feeling of God being the salvation, strength, and song, and a trusting in him,
and not being afraid? Isa. 12:2.
Is there not a being careful in nothing,
but in everything making the requests to God, by prayer and supplication,
with thanksgiving, in that Spirit and holy breath of life, which the Father cannot deny;
and so, the peace of God, which passeth all understanding,
keeping the heart and mind through Christ Jesus?

O my friend! there is an ingrafting into Christ,
a being formed and new created in Christ, a living and abiding in him,
and a growing and bringing forth fruit through him into perfection.
Oh, mayst thou experience all these things! and that thou mayst do so, wait to know life,
the springings of life, the separations of life inwardly,
from all that evil which hangs about it, and would be springing up and mixing with it,
under an appearance of good; that life may come to live fully in thee, and nothing else.
And so, sink very low, and become very little, and know little; yea,
know no power to believe, act, or suffer any thing for God, but as it is given thee,
by the springing grace, virtue, and life of the Lord Jesus.
For grace is a spiritual, inward thing and holy seed, sown by God,
springing up in the heart.
People have got a notion of grace, but know not the thing.
Do not thou matter the notion, but feel the thing;
and know thy heart more and more plowed up by the Lord,
that his seed`'s grace may grow up in thee more and more,
and thou mayst daily feel thy heart as a garden, more and more enclosed, watered,
dressed, and delighted in by him.

This is a salutation of love from thy friend in the truth, which lives and changes not.

I+++.+++ P.

27th of Twelfth Month, 1678

=== TO M. HIORNS

DEAR FRIEND,

I received two letters from thee lately,
whereby the sense is revived in me of thy great love to me,
and the Lord`'s great goodness to thee,
in administering that which rejoiceth and refresheth thee.

Now, this advice ariseth in my heart.
Oh! keep cool and low before the Lord, that the seed, the pure, living seed,
may spring more and more in thee,
and thy heart be united more and more to the Lord therein.
Coolness of spirit is a precious frame; and the glory of the Lord most shines therein,
in its own lustre and brightness; and when the soul is low before the Lord,
it is still near the seed, and preciously (in its life) one with the seed.
And when the seed riseth, thou shalt have liberty in the Lord to rise with it;
only take heed of that part which will be outrunning it, and getting above it, and so,
not ready to descend again, and keep low in the deeps with it.

O my friend!
I have a sense,
that this hath been the error of that people that thou hast formerly walked with:
and I observe in thy spirit yet a liability thereto;
which the Lord give thee to watch against,
that thou mayst come to a pure observation and discerning of the everlasting,
unchangeable seed in thy own heart,
and mayst daily feel thy mind bowed down and worship in it,
become wholly leavened into it, and perfectly changed and preserved by it.

=== POSTSCRIPT

We are here but awhile in this world, for the Lord to make use of us,
and serve himself by us; and so, by his ordering of us, to fit us for the crown of glory,
which he will give us fully to wear in the other world.
Now, feel the child`'s nature, which chooseth nothing,
but desires the fulfilling of the Father`'s will in it.
I cannot desire to enjoy any thing (saith the nature of the true birth),
but as the Father, of himself, pleaseth to give me to enjoy.
There is a time to want, as well as to abound, while we are in this world.
And the times of wanting, as well as abounding, are greatly advantageous to us.
How should faith, love, patience, meekness,
and the excellency and sufficiency of God`'s grace shine, but by, in,
and through the many exercises and varieties of conditions,
wherewith the Lord visiteth his?
Yea, the greatest in the life, power, and glory of the Lord,
have the greatest trials and exercises, which is to their advantage,
as also for the good and benefit of others, and to the great honor and glory of the Lord.
Oh! at all times, and in all conditions, take heed of a will, take heed of a wisdom,
above the seed`'s will, and above the seed`'s wisdom.

Let the Lord alone be all in thee, and make thee every day what he pleaseth; and,
in due time, thou shalt know a life,--even the seed`'s life,
the Son`'s life,--whom all of the angels are to worship,--and
the mystery of whose life the angels desire to look into,
as it is revealed and brought forth!
So, be still and quiet, and silent before the Lord;
not putting up any request to the Father, nor cherishing any desire in thee,
but in the seed`'s lowly nature and purely springing life;
and the Lord give thee the clear discerning, in the lowly seed,
of all that springs and arises in thy heart.

Thou didst read precious things of the seed when thou wast here, written outwardly;
oh that thou mightst read the same things, written inwardly in thy own heart;
which that thou mayst do, become as a weaned child,
not exercising thyself in things too high or too wonderful for thee.
Every secret thing, every spiritual mystery, but what God opens to thee,
is too high and wonderful for thee.
And if the Lord at any time open to thee deep mysteries, fear before the Lord;
and go no further into them than the Lord leads thee.
The error is still in the comprehending, knowing mind, but never in the lowly,
weighty seed of life;--whither the Lord God of my life more and more lead thee,
and counsel thee to take up thy dwelling place there, daily instructing thee so to do.
For the greatest, as well as the least, must be daily taught of the Lord,
both in ascending and descending, or they will miss their way; yea,
they must be daily taught of him to be silent before him, and know +++[+++what it is]
to be still in him, or they will be apt to miss in either.

This from thy friend,

I+++.+++ P.

Amersham, Woodside, 4th of Fifth Month, 1679.

=== TO SARAH ELGAR

THE child which the Lord hath taken from thee was his own.
He hath done thee no wrong, in calling it from thee.
Take heed of murmuring, take heed of discontent, take heed of any grief,
but what truth allows thee.
Thou hast yet one child left.
The Lord may call for that too, if he please; or he may continue and bless it to thee.
Oh, mind a right frame of Spirit towards the Lord, in this thy great affliction!
If thou mind God`'s truth in thy heart, and wait to feel the seasoning thereof,
that will bring thee into, and preserve thee in a right frame of spirit.
The Lord will not condemn thy love and tenderness to thy child,
or thy tender remembrance of him; but still, in it be subject to the Lord,
and let his will and disposal be bowed unto by thee,
and not the will of thy nature above it.
Retire out of the natural, into the spiritual,
where thou mayst feel the Lord thy portion; so that now, in the needful time,
thou mayest day by day receive and enjoy satisfaction therein.
Oh, wait to feel the Lord making thy heart what he would have it to be,
in this thy deep and sore affliction!

I+++.+++ P.

Nunnington, Sixth Month, 1679

Now, let the world see how thou prizest the truth, and what truth can do for thee.
Feed on it; do not feed on thy affliction; and the life of truth will arise in thee,
and raise thee up over it, to the honor of the name of the Lord,
and to the comfort of thy own soul.

=== TO WILLIAM ROLLS

FRIEND,

David saw through the sacrifices and burnt offerings in his time;
and the spiritual eye sees through all shadows to the substance,
which have no place in the brightness of the day of God:
and outward washing is no more than outward circumcision,--no
more of a gospel nature,--nor can avail any more,
but is of the nature of the things that were to be shaken and pass away;
that the spiritual kingdom of our Lord Jesus Christ,
and the things which cannot be shaken might remain.

I could say very much to every passage of thy letter; but to what purpose would it be?
The Lord give thee a sense, where the true understanding is given,
and teach thee aright to wait for it; that thou mayst receive it from him,
and thereby discern the nature of that wisdom,
from which God hath hid the mystery in all ages and generations,
and from which he hides it still;
that so thou mayest experimentally know what it is
to become a fool in thyself for Christ`'s sake,
that thou mayst be wise in him; concerning which,
it is easy to have many notions in the mind, but hard to come to the true experience of.

These are the breathings of my heart for thee, in the flowings of my love;
who desire that thou mayst not seek after the knowledge
of the Scriptures in that which cannot understand them;
but mayst meet with the right key, and the right understanding,
wherein thy soul will be safe and happy; which is my heart`'s desire for thee,
who am a real friend and well-wisher to thy soul in the Lord.

I+++.+++ P.

=== TO THE POOR AMONG FRIENDS, who are relieved by the charity and bowels of love, which God opens in other Friends towards them

O FRIENDS,

Ye ought deeply and often to consider of God`'s visiting you with his precious truth,
whereto being faithful, ye are sure to be happy forever;
how hard soever it should go with you, and how strait soever your condition should be,
in reference to the things of this world.

But ye have not only this assurance and benefit by the truth,
but ye are also come to partake of a better provision, as to your necessities outwardly,
than other poor meet with.
For God himself takes care of you,
in drawing the hearts of his children to consider of your wants,
and make supply unto you; so that many of you are so provided for,
as ye had never like to have been while in this world,
had it not been for the interest God gives you in the hearts of others,
through and because of his truth.
Surely this should not be forgotten by you, but daily acknowledged to the Lord,
in the use and enjoyment of those things, which ye ought to receive as from his hand,
through those who minister to you in his name, and for his sake.

And take heed of murmuring, if the supply answer not any of your expectations;
for if we wait upon the Lord, to be ordered and guided by him in this matter,
and answerably witness his presence with us,
and holy wisdom ordering us in these affairs; your murmurings are not against us,
but against the Lord.
And if ye watch narrowly over yourselves, ye will find it is the unsubdued part,
which is apt to be repining and murmuring; but that which is of the Lord, and eyes him,
is that which is sensible of his goodness, and thankful to him for it.
But if there be judged to be any neglect towards any, or any just cause of complaint;
let it, in tenderness, meekness, and the fear of the Lord, be laid before us;
and we will wait upon him to give it a due and full consideration,
and do therein as the Lord shall open and guide our hearts.
For great exercises of spirit do we meet with in these affairs,
and great are our cries of spirit to the Lord,
to guide and order us according to his will and holy counsel therein.

And dear Friends, wait to feel that which stays your minds on the Lord,
and keeps your eye towards him; and take heed of judging us in things,
wherein we truly desire to act singly towards the Lord,
and of which we must give an account to him; and if ye in any thing judge us,
wherein our God justifies us, certainly the Lord will therein condemn you.
Therefore be wary and watchful in this matter.

I+++.+++ P.

=== TO SARAH BOND

DEAR SARAH,

I have had many thoughts of thee in this my imprisonment;
wherein I have seen in spirit thy error and miscarriage,
and a hope and expectation in thy heart which will deceive thee.

Oh, how much precious time hast thou lost! wherein thou
mightst have been travelling far on thy journey,
while thou art disputing in thy mind,
and wandering in the deceitful reasonings of thy heart.
And indeed, it must not be, it must not be as thou imaginest; but thou must begin low,
and be glad of a little light to travel with out of the earthly nature,
and be faithful thereunto; and in faithfulness expect additions of light,
and so much power as may help thee to rub on.
And though thou may be long low, and weak, and little, and ready to perish;
yet in the humble and self-denying state, the Father will help thee,
and cause his life to shoot up in thee,
in the shooting up whereof will be thy redemption.

But, oh hasten, oh hasten out of the earthly nature, whilst thou hast time,
or any visitations from the Spirit of the Lord! and do not, in thy wisdom, limit him,
but accept what at present comes from him; for the flood is breaking out,
and will swallow up and drown all that are not found in the ark.
Oh! therefore enter, enter apace; mind that which checks in thy heart;
mind also that which reasons against those checks, to hold thee still in captivity,
and to keep thee from travelling out of the earthly nature, spirit, wisdom,
and practices; and come out of the spirit and way of this world, that thou mayst live,
and not die.
For none shall live, but those that walk in the way of life,
and leave the paths and course of the dead, in which thou art yet entangled.
Oh that thou mightst be loosed, and travel out thence,
with a little light and a little help! and not limit
the Holy One of Israel in thy desires or expectations,
but thankfully receive the smallest visitation that comes from him to thy soul;
for there is life and peace in it, and death and perplexity in turning from it.
And this will not be thy comfort or satisfaction hereafter,
to have had a day of visitation and mercy from on high;
but to have received the visitation, and to have been turned in it,
from the darkness of the earthly mind and nature,
into the light of the living and redeemed souls,--this will be comfortable indeed!

And this is my tender counsel to thee:
wait for and gaspingly receive the checks of the Most High,
and take heed of reasoning against them;
but as that (though in a low and mean and despicable way to thy
wisdom) draws and leads thee out of any earthly thought,
word, custom, or practice, follow diligently; not reasoning against it,
but waiting to have thy reasonings subdued to the
smallest motions and lowest guidance of life in thee.
For I know that life is near thee, even the life that would effectually redeem thee;
but it is bowed down and held captive under the dominion of the earthly wisdom;
and so thy redemption (which is to be wrought out by it) sticks, and will stick,
until thy heart be persuaded to join to it and become subject, without reasoning,
without consulting, without disputing.
For I certainly know the light manifests in thee;
but the darkness puts off the present manifestation of the light, and expects another;
and this is in the will of the flesh, which the Father will not answer;
and in this will and expectation thou wilt perish; but thy help, life,
and salvation are in being subject to the present manifestation of light,
parting with and departing from what thou already knowest to be of the earth,
and not of God.

And in thus doing, more will be made manifest in the Lord`'s season,
and power given to become a child, after some belief in the Father,
and some entrance into the childlike nature;
but the will and expectation of the flesh in thee shall never be
answered:--it hath been long written in my heart concerning thee,
but I dare never utter it to thee.
Oh that it may be now uttered, to the melting and advantage of thy heart! for, indeed,
I love thee, and have travailed for thee, and desire the salvation of thy soul,
as of my own.
Oh that thou mayst be led out of that wisdom which destroys,
into that which saves! and mayst there, in humility of heart, receive instruction daily,
according to thy need.
But indeed, of a truth,
thou must come into and come under that which crucifies thy nature and wisdom;
and there (in the seasons of God`'s wisdom,
who answers the desires of his own Spirit in the heart,
but regards not the flesh) mayst thou meet with life and power, but no where else.

I am thy friend, and a dear lover of that in thee which desires the Lord;
and oh that that might come up in thee, and be severed from the earth,
that thy soul may live!

I+++.+++ P.

=== FOR MY DEAR FRIENDS IN THE TRUTH AT LEWES

THE God of truth plants his truth in the hearts of people, that it might grow there,
and bring forth fruit to him.
O my dear friends! feel it grow in every one of your hearts,
and bringing forth the proper fruits of its growth to the Lord.

Mind what ariseth from the truth, what truth brings forth,
and wait for and receive your nourishment from the Lord,
that it may be brought forth in you.
And that which the Lord hath made barren (in you,
who have experienced his righteous judgments), let it be kept so,
by the same power which made it barren,
that no more fruit may be brought forth to sin and unrighteousness, by any of you.
Then shall ye live the life of truth, and no life but the life of truth,
and dwell and walk in the truth, than which there is no greater joy, delight,
or peace to be desired or enjoyed.

O my dear friends! know and every day experience Enoch`'s
life,--a being translated out of the kingdom of darkness,
into the kingdom of the dear Son, and of walking with the Son in his kingdom;
then ye will walk with the Father also, and know the heavenly paths of life, joy,
righteousness, and peace in the pure light of life,
which is no less than a paradise to the renewed soul.

I would fain have seen you together, had the Lord made way;
but let me feel you in the hidden life, and meet you at my Father`'s throne,
where let us beg of our God, what our souls and his whole flock stand in need of,
praying for the peace and prosperity of Jerusalem,
unto the God and Father of our Lord Jesus Christ, who hears our prayers;
that we may daily see and feel the going on of the work of our God, in our hearts,
and in the kingdoms of the world (which must become the Lord`'s and his Christ`'s),
and may bless and magnify his name, who hath power over all,
and orders all for good to his chosen heritage.

This is the salutation of my love to you, which lay so upon me,
that I could not pass it by, who am your friend, in the everlasting,
unchangeable truth of our blessed God and Saviour.

I+++.+++ P.

=== TO +++_______+++ +++_______+++

BECAUSE my not praying in my family, according to the custom of professors,
seemed to be such a great stumbling-block to thee,
it sprang up in my heart to render thee this account thereof.

I did formerly apply myself to pray to the Lord,
morning and evening (besides other times), believing in my heart,
that it was the will of the Lord I should so do.
And this was my condition then:--sometimes I felt the living spring open,
and the true child breathe towards the Father; at other times I felt a deadness,
a dryness, a barrenness, and only a speaking and striving of the natural part, which I,
even then, felt was not acceptable to the Lord, nor did profit my soul;
but apprehending it to be a duty, I durst not but apply myself thereto.

Since that time,--since the Lord hath again been pleased
to raise up what he had formerly begotten in me,
and begun to feed it,
by the pure giving forth of that breath of life which begat it
(which is the bread that comes down from heaven daily to it,
as the Lord pleaseth freely to dispense it),--the Lord hath shown me that prayer
is his gift to the child which he begets and that it stands not in the will,
or time, or understanding, or affectionate part of the creature,
but in his own begetting, which he first breathes upon,
and then it breathes again towards him:--and that he worketh this at his own pleasure,
and no time can be set him when he shall breathe: or when he shall not breathe,
and that when he breathes, then is the time of prayer,
then is the time of moving towards him, and following him who draws.
So that all my times, and all my duties, and all my graces, and all my hopes,
and all my refreshments, and all my ordinances, are in his hand,
who is the spring of my life, and conveys, preserves,
and increases life of his own good pleasure.

I freely confess, all my religion stands in waiting on the Lord,
for the riches of his Spirit, and in returning back to the Lord (by his own Spirit,
and in the virtue of his own life), that which he pleaseth to bestow on me.
And, I have no faith, no love, no hope.
no peace, no joy, no ability to any thing, no refreshment in any thing,
but as I find his living breath beginning, his living breath continuing,
his living breath answering, and performing what it calls for.
So that I am become exceeding poor and miserable,
save in what the Lord pleaseth to be to me by his own free grace,
and for his own name`'s sake, and in rich mercy.
And if I have tasted any thing of the Lord`'s goodness sweeter than ordinary,
my heart is willing, so far as the Lord pleaseth,
faithfully to point any others to the same spring;
and not discourage or witness against the least simplicity, and true desire after God,
in them.
But where they have lost the true living child,
and another thing is got up in its stead (which,
though it may bear its image to the eye of flesh,
yet is not the same thing in the sight of God),
and where this nourisheth itself by praying, reading, meditating,
or any other such like thing,
feeding the carnal part with such a kind of knowledge from Scriptures,
as the natural understanding may gather and grow rich by; this,
in love and faithfulness to the Lord and to souls, I cannot but testify against,
wherever I find it, as the Lord draweth forth my spirit to bear its testimony.

And this I know, from the Lord, to be the general state of professors at this day.
The Spirit of the Lord is departed from them, and they are joined to another spirit,
as deeply and as generally as ever the Jews were;
and that their prayers and reading of the Scriptures, and preaching, and duties,
and ordinances are as loathsome to the soul of the Lord,
as ever the Jews`' incense and sacrifices were.
And this is the word of the Lord concerning them.
Ye must come out of your knowledge, into the feeling of an inward principle of life,
if ever ye be restored to the true unity with God,
and to the true enjoyment of him again.
Ye must come out of the knowledge and wisdom ye have gathered from the Scriptures,
into a feeling of the thing there written of,
as it pleaseth the Lord to open and reveal them in the hidden man of the heart.

This is it, ye are to wait for from the Lord; and not to boast of your present state,
as if ye were not backslidden from him,
and had not entered into league with another spirit;
which keeps up the image of what the Spirit of the Lord once formed in you,
but without the true, pure, fresh life.

From a faithful friend and lover of souls.

I+++.+++ P.

=== TO E. TERRY

FRIEND,

If the Lord hath extended favor to thee and shown thee mercy,
I therein rejoice on thy behalf.

Thy desire, that what thou wrotest may be looked upon as nothing,
and that no contest may be raised from it, I am content fully to answer thee in;
nor do I desire to have any advantage against thee,
nor art thou at all disparaged in my thoughts by what thou hast written,
but it is in my heart as nothing, and my love flows to thee;
for I take notice of thy seriousness, and what I have unity with in this letter,
and overlook the other.

As touching disputes, indeed, I have no love to them:
Truth did not enter my heart that way,
nor do I expect to propagate it in others that way; yet,
sometimes a necessity is laid upon me, for the sake of others.
And truly, when I do feel a necessity, I do it in great fear;
not trusting in my spear or bow, I mean in strong arguments or wise considerations,
which I (of myself) can gather or comprehend; but I look up to the Lord for the guidance,
help, and demonstration of his Spirit,
that way may be made thereby in men`'s hearts for the pure seed to be reached to,
wherein the true conviction, and thorough conversion of the soul to God is witnessed.
I had far rather be feeling Christ`'s life, Spirit, and power in my own heart,
than disputing with others about them.

Christians that truly fear the Lord, have a proportion of the primitive Spirit; and,
if they could learn to watch and wait there, where God works the fear,
they would daily receive more and more of it, and in it,
understand more and more the true intent and preciousness of the words of the Holy Scriptures.
He that will truly live to God, must hear wisdom`'s voice within, at home,
in his own heart; and he that will have her words made known,
and her spirit poured out to him, must turn at her reproof. Prov. 1:23.
Indeed, I never knew, and am satisfied that none else can know,
the preciousness of this lesson, till they are taught it of the Lord.

There is one thing more on my heart to express, occasioned by thy last letter,
which is this: I have more unity in my heart and spirit before the Lord,
with the Puritan state,
than with the churches and gatherings which men have built up and run into since.
Indeed, men have enlarged their knowledge and comprehension of things;
but that truth of heart, that love, that tenderness, that unity upon truth`'s account,
which was then amongst them, many have made shipwreck of,
and do not now know the state of their own souls, nor truth in the life and power of it.
This principle of life and truth was near me, as well as others; yea,
with me in that day; but I wandered from it into outward knowledge, and,
with great seriousness, into a way of congregational worship,
and thereby came to a great loss; and at length, for want of the Lord`'s presence, power,
and manifestation of his love, was sick at heart.
But now, the Lord, in great love and tender mercy,
having brought me back to the same principle, and fixed my spirit therein,
I discern the truth and beauty of that former estate,
with the several runnings out from it; and find what was true or false therein,
discovered to me by the holy anointing, which appears and teaches in that principle.
And, friend, it is not a notion of light, which my heart is engaged to testify to;
but that which enlivens, that which opens, that which gives to see,
that wherein the power of life is felt.
For truly, in the opening of my heart by the pure power,
was I taught to see and own the principle and seed of life,
and to know its way of appearance; and so can faithfully and certainly testify,
that that which is divine, spiritual, and heavenly, is nearer man than he is aware,
as well as that which is earthly and selfish.

O friend! if thou canst not yet see and own the principle
and seed of Christ`'s life and Spirit,
nor discern his appearance therein; yet take heed of fighting against it; for, indeed,
if thou dost, thou fightest against no less than the Lord Jesus Christ himself.

I+++.+++ P.

=== TO A NEAR RELATIVE

DEAR +++_______+++,

The gospel is the power of God unto salvation;
it is the glad tidings of freedom from sin,
of putting off the body of sin by the circumcision and baptism of the Spirit,
of being delivered out of the hands of our spiritual enemies,
that we may serve God (without fear of them any more),
in holiness and righteousness all the days of our life.

The ministers of the gospel are those, who, in the Spirit of Christ,
by the gift and inspiration thereof, preach these tidings to the poor and needy,
to the captives, to those that groan under the pressure of the body of corruption.

The gospel, through the great mercy of God, I have, at length, heard preached;
and I have not heard man, but the voice of my Beloved; whose voice is welcome to me,
though in the meanest boy, or most contemptible female.
For in Christ, there is neither male nor female; nor should his Spirit,
which is not limited to males, be quenched in any.
And though thou, through prejudice,
call this speaking of the Spirit through servants and handmaids, prating,
yet the Lord can forgive thee; for surely, if thou knew what thou didst herein,
thou wouldst not thus offend the Lord;--extolling preaching by man`'s wisdom,
from a minister made by man, for gospel preaching,
and condemning the preaching of persons sent by God,
in the immediate inspiration of his Spirit.
I am confident, if, without prejudice, and in the fear of God, thou didst once hear such,
thou wouldst not be able to forbear saying in thy heart, It is the voice of God,
of a truth.
But that which hath not the sheep`'s ear can never own the voice of the true Shepherd.

As for those whom thou callest ministers, if I should speak, concerning them,
the very truth from the mouth of the Lord, thou couldst not,
in that state wherein thou standest, receive it;
yet am I far from accounting them the offscouring of the earth;
for I look upon them as wise and knowing,
and as of great beauty in the earthly learning and wisdom; but surely,
not as having "`the tongue of the learned,`" "`to speak
a word in season to him that is weary;`" nay,
they are men unlearned in this kind of learning,
and such as toss and tear and wrest the scripture,
in their uncertain reasonings and guessings about the sense of it,
and in the various doubtful interpretations they give.

And whereas I am blamed for not putting a difference
between the profane and scandalous ministers,
and the reverend and godly sort; my answer is, They are united in one ministry;
and the question is not concerning the persons, but the ministry;
in which they are one,--their call one, their maintenance one,
their way of worship and preaching one, their standing and power of government one;
which is not by the power and presence of the Spirit,
but by the strength of the magistrate.
But the true gospel and ministry is spiritual,
and cannot stand nor be upheld by that which is carnal, neither in its call, maintenance,
government, or what else belongs to it.
When Christ came in the flesh,
the words he pronounced were not so much against the profane
and scandalous among the Scribes and Pharisees;
but against those that appeared most strict,
and were accounted among the Jews the most reverend and godly.
And, were it not for the appearance of godliness in these men,
the persecution of the present times had not been so hot, the good old cause so lost,
and the work of reformation (inasmuch as relates to men) so overturned as at this day.
O +++_______+++! there was once a good thing in divers of them,
which my soul would rejoice to see revived;
but as the seat of government eat out the good that was in the bishops,
so gaping after the seat of government hath sunk the good thing in others also;
and made their eye so dim,
that they cannot see the mighty breakings forth of the Spirit of Christ in his people.

I+++.+++ P.

=== TO RICHARD ROBERTS

R+++.+++ R.

THOU didst acquaint me that Timothy Fly, the Anabaptist teacher,
did charge me with denying Christ`'s humanity, and also the blood of Christ,
which was shed at Golgotha, without the gates of Jerusalem;
and that I own no other Christ but what is within men.

Sure I am, that neither T. Fly, nor any other man, did ever hear me deny, that Christ,
according to the flesh, was born of the Virgin Mary, or that that was his blood,
which was shed without the gates of Jerusalem.
And the Lord, who knoweth my heart, knoweth, that such a thing never was in my heart;
nay, I do greatly value that flesh and blood of our Lord Jesus Christ,
and witness forgiveness of sins and redemption through it.
Yet, if I should say,
I do not know nor partake of his flesh and blood in the mystery also,
I should not be a faithful witness to the Lord.
For there is the mystery of God and of Christ;
and that is the soul`'s food which gives life to the soul,
even the living bread and the living water.
For there is living bread and living water; and the flesh and blood in the mystery,
on which the soul feeds, is not inferior in nature and virtue to the bread and water.
There is a knowing Christ after the flesh, and there is a knowing him after the Spirit,
and a feeding on his Spirit and life; and this doth not destroy his appearing in flesh,
or the blessed ends thereof, but confirm and fulfill them.

The owning of Christ being inwardly in his saints,
doth not deny his appearing outwardly in the body prepared;
unless T. F. can maintain this,
that the same Christ that appeared outwardly cannot appear inwardly.
"`Know ye not your own selves.
how that Jesus Christ is in you,
except ye be reprobates?`" 2 Cor. 13:5. "`And if Christ be in you,
the body is dead because of sin,`" etc. Rom. 8:10.
"`Christ in you, the hope of glory.`" Col. 1:27. "`Behold,
I stand at the door and knock; if any man hear my voice and open the door,
I will come in to him.`" Rev. 3:20. "`I will come again,`" saith Christ:
Ye are now in pain, as a woman in travail, full of sorrow for the loss of my outward,
bodily presence; but I will come to you again in spirit;
see John 16 and John 14:17. "`He,`" that "`dwelleth with you, shall be in you:`" and then,
when the Bridegroom is inwardly and spiritually in you and with you,
"`your heart shall rejoice, and your joy no man taketh from you.`" John 16:22. And so,
the apostles and primitive Christians did "`rejoice with joy unspeakable,
and full of glory,`" 1 Peter 1:8,
because of the spiritual appearance and presence of the Bridegroom.
And yet, there is no other bridegroom, who now appears in spirit,
or spiritually in the hearts of his, than He that once appeared in the prepared body,
and did the Father`'s will therein.

I+++.+++ P.

=== ADDRESSED TO THE INDEPENDENTS AT CANTERBURY

I HAVE been a seeker after God, and a worshipper of him from my childhood,
according to the best of my understanding; and, at last,
sat down in that way which is called Independency,
believing it to be the way of the gospel,
and entering into it with much fear and seeking of God.
In which way, the Lord had regard to the uprightness and tenderness of heart,
which he had formed in me.

But, at length, the Lord`'s hand fell upon me, breaking me all to pieces therein,
as to my inward state; for what cause, I had then no knowledge at all of;
but mourned before him unutterably, night and day,
and lay panting and languishing after him, who was the only Beloved of my soul.
Many pitied me, but none could reach my state, but, after much serious discourse with me,
greatly wondered: and some said, it was a prerogative case, and would, questionless,
end in good-will and mercy from the Lord to me.
I parted from that people in great love and tenderness;
they expecting my return to them again (the love
between me and them being so exceeding great,
and I having let in no prejudice against them), and I knowing nothing to the contrary.

But it pleased the Lord, after many years, when my hope nearly failed,
to visit me in a wonderful manner, breaking my heart in pieces,
giving me to feel his pure, living power,
and the raising of his holy seed in my heart thereby; insomuch,
that I cried out inwardly before him, "`This is He, this is He whom I have sought after,
and so much wanted! this is the pearl,
this is the holy leaven! do what thou wilt with me, afflict me how thou wilt,
and as long as thou pleasest, so that at length I may be joined with this,
and become one with this!`" So the eye of my understanding was from that day anointed,
and I saw and felt the pure life of the Son made manifest in me;
and the Father drew me to him, as to a living stone, and hath built my soul upon him,
and brought me to Mount Zion, and the holy city of our God;
where the river of life sends forth its streams,
which refresh and make glad the holy city,
and all the tabernacles that are built on God`'s holy hill.
And indeed, from this holy hill and city, the law and word of life doth issue,
and the inhabitants of the rock of life hear it, and are friends to the Bridegroom,
and glad of the Bridegroom`'s voice, and follow the Lamb,
the Shepherd and Bishop of their souls, whithersoever he leads;
who leads them into the pastures of life, and folds of pure rest,
and gives them eternal life to feed on,
and his peace and patience to possess their souls in.

O ye Independents! whom I have loved above all people,
and never had thoughts of rending from you,
but was forcibly taken by the hand of the Lord out of your Society;
yet not without a desire to return to you again,
if the Lord pleased to make any way thereto;--I say, O ye Independents,
above all professions the one most dearly beloved by me! oh that ye could hear the sensible,
experienced testimony that is on my heart to you concerning my Beloved,
concerning his appearance, concerning his church, concerning his way, his truth,
his kingdom.
It is nigher than ye are aware, and above all that ye can comprehend concerning it.
Oh that ye might inwardly know these things!
Turn in, turn in: mind what stirs in your hearts; what moves against sin,
what moves towards sin.
The one is the Son`'s life, the Son`'s grace, the Son`'s Spirit;
the other is the spirit and nature which is contrary thereto.
If ye could but come to the sense of this, and come to a true, inward silence,
and waiting, and turning at the reproofs of heavenly wisdom,
and know the heavenly drawings into that which is holy and living;
ye would soon find the Lord working in your hearts, to stop the issues of death,
and to open the issues of life there;
and ye would find yourselves anointed daily by the
Lord (for there is not a day but we need to see,
nor a day but the Lord gives sight),
and an understanding also would be given you to know Him that is true,
and the "`eternal life,`" 1 John 1:2, and an abiding in him that is true.
And, abiding here,
ye cannot fail of receiving power (from him who ministers
according to the power of the endless life),
not only to overcome sin and your souls`' enemies, but to become sons to God,
with delight performing his will.
And that yoke, which yokes down and subdues sin in you, will be easy, yea, the ease,
pleasure, and joy of your souls.

The Lord open an ear in you to hear as the learned,
that ye may become experiencers and possessors of these things; for, of a truth,
the Lord is arisen to shake terribly the earth, and to build up his Zion,
and to give unto his people "`a peaceable habitation and
sure dwellings and quiet resting-places`" upon Mount Zion. Isa. 32:18.

I+++.+++ P.

=== TO FRANCIS PORDAGE

FRIEND,

There is a mind, which can never know nor receive the things of God`'s kingdom; and yet,
this mind is very busy in searching and inquiring after them.

The Scribes and Pharisees were still questioning Christ,
and desiring satisfaction about the kingdom, and about his doctrine and miracles,
and the practice of his disciples, but could never receive satisfaction; yet,
the disciples themselves were many times afraid to ask Christ questions,
there being a dread of God upon their spirits,
and a limit to the knowing and inquiring part in them; for indeed,
the true birth learns under the yoke.

This, therefore, is precious; to come to feel somewhat to limit that mind,
which is forward and inquisitive out of the true nature and sense,
and to receive the yoke, and to be limited by it and famished; for famine,
not food of life, is appointed for that mind and birth.
It is written, "`I will destroy the wisdom of the wise,
and bring to nothing the understanding of the prudent.`" Now,
this is precious and greatly needful: for a man to know, and discern,
and watch against that wisdom and understanding in himself,
which God will destroy and bring to nothing; for, to be sure,
while he is learning and striving to know with that, God will never teach him,
but rather hide the mystery of life and salvation from him.
And what is all man`'s knowledge worth, that he learns of himself without God`'s teaching;
and which he receives into that understanding which is to perish and be destroyed?
In the new understanding, God sets up the true light; but in the other understanding,
are false lights set up, which do not give a true distinction of good and evil,
but they call good evil, and evil good, and put darkness for light,
and light for darkness, and cannot do otherwise; because, the light in them is darkness,
it not being the gift of grace whereby they see and judge,
but a light of their own forming, according to their own comprehension of things,
in the dark and false understanding.

Now, the Lord hath taught us the difference between all these lights,
and the light of his grace, which purely teacheth, livingly teacheth,
not in the reasonings of the mind,
but in the evidence and demonstration of God`'s Spirit in the soul and conscience.
When we came to see in this light, we found, that which we had called good,
according to our former apprehension of things, was not so in the true balance;
and what we thought had pleased God, was abominable in his eyes.
And truly, all that are not come to this light,
they offer that which is abominable to God, and yet think it pleaseth him;
and what a gross and dangerous mistake is this! indeed,
all are no better than will-deeds, which are done out of the light, life, virtue,
and power of God`'s Spirit.
For the root must be good, or the fruit cannot be good.
The mind must be renewed, or the knowledge is but old, dead, literal, and fleshly;
such as the fleshly understanding comprehends and receives,
which can neither know nor receive what is spiritual.

Truly, the Lord hath led us a great way in our journey,
and done great things inwardly for and in our spirits; yet,
if we were not kept under the yoke, but that part in us had liberty to know, and live,
and act, and worship, we should yet perish, and be cut off from the land of the living.

I+++.+++ P.

=== IN REPLY TO AN ANSWER OF I. H. TO SOMEWHAT WRITTEN ON BEHALF OF TRUTH

+++_______+++ INDEED, to speak properly, the church of the gospel, or new testament church,
is invisible.
The persons in whom the church is, are visible;
yet the new testament church is not a society of men,
but rather of the invisible life in men.
It is a fellowship in the faith, in the Spirit,
which is the bond of their unity and of their peace.

The life is breathed invisibly into the hidden man; John 3:8;
it is there nourished and built up invisibly into a spiritual, invisible temple, house,
or church; and in that is the unity and fellowship.
So that the church is a mystery, and the fellowship a mystery,
which is hid from every eye but the eye of life;
and there is no having fellowship one with another, but by coming to that,
and keeping in that, wherein is the fellowship. 1 John 1:7.
It is of inward Jews the church is built; it is of such,
God seeks to frame his new house of worship, under the gospel. John 4:23.
Now, of such stones as these,
the Lord builds up a temple for his Spirit to dwell in,
a house for his life and presence to manifest itself
in,--even a church for the living God.
This building is by the Spirit, in the Spirit, and of that which is spiritual;
this building is one with the foundation,
and therefore is the pillar and ground of Truth, which none is but Christ,
and that which is married to him, and so one with him. 1 Tim. 3:15.
Consider the place well,
and see whether it relate to that which thou callest the invisible,
or to that which thou callest the visible church.

It is the candlestick in persons, that is the church; not any outward meeting of persons,
or joining together by covenant, or receiving or practising of ordinances,
can make a church; but the eternal life in believers,
formed by the Spirit into a candlestick, to hold the eternal lamp or light,
with the everlasting oil of salvation.
The light thus shining in this candlestick,
continually refreshed by this oil,--here is a flourishing temple, wherever it is found;
here is the church of the living God, here is the spouse married to the Lamb,
her Husband.
But grieve the Spirit, quench the Spirit, despise the prophesyings thereof,
and light up a candle of the fleshly wisdom and knowledge of the things of God,
instead of these, the oil soon fails; the oil failing, the lamp goes out; the lamp,
or light, being gone out of the candlestick, the Lord soon removes the candlestick;
and the candlestick being once removed, the very same persons may meet together often,
and hold up the form,--performing things mentioned in the Scriptures concerning a church,
and observing such things as they may call the institutions and
ordinances thereof,--but they are far from continuing to be a church.
Take away the faith, what is left of a Christian?
and take away the candlestick, what is left of a church?

It is the Spirit alone that can square stones, and fit them for building a church of;
and he alone can build them up into a house, when he hath squared them. Eph. 2:22.
And after he hath built, he can pull down again,
and bring into a wilderness state;
for there is a wilderness state of Christianity as well as a built state; Rev. 12:6,
and as, in the built state, it is dangerous to be out of the church, so,
in the wilderness state,
it is dangerous remaining in that building which the Spirit of the Lord hath forsaken.
Now, if the Spirit be the builder, then, surely, he will take in no stones,
but such as he hath first squared and fitted for the building.
And after the church is built, it is he alone who addeth to the church;
who will be sure to add none, but those whom he hath first converted. Acts 2:47.

The church is a body gathered in the Spirit, and watching to the Spirit;
who is present there with his pure, searching, discerning eyes;
so that nothing that is impure can enter (they watching to the Spirit,
according to the order of the gospel), no, not one counterfeit Jew, no,
nor so much as one false apostle,
though they clothe themselves ever so like angels of light.
Rev. 22. But if they be negligent, and from off the watch,
not waiting for the guidance of the Spirit; then that which is corrupt may creep in,
and endanger the body.
Jude 4.

=== TO BRIDGET ATLEY

DEAR FRIEND,

I am sensible of thy sore travail and deep distress,
and how hard it is for thee to meet with that which is comfortable and refreshing,
and how easily again it is lost;
and whence it ariseth,--even from the working of
the enemy in a mystery of deceit in thy heart;
wherein thou dost not perceive nor suspect him, but swallowest down his baits,
and so he smites thee with his hook,
and thereby draws thee back into the region of darkness; and then,
entereth that part in thee which is in nature one with him,
filling it with his wickedness; and then, laying loads of accusations upon thee,
as if they were true.
These are not strange things to the travellers after the Lord,
but such as are usually met with in the like cases:
but if thy eye were made single and opened by the Lord, thou wouldst see those baits,
and turn from that, which thou now so readily swallowest down; and so avoid the stroke,
and keep thy station, in the light and mercy of the Lord.
Thou must not look so much at the evil that is nigh,
but rather at that which stands ready to pity and help,--and
which hath pitied and helped thy distressed soul,
and will pity and help it again.
Why is there a mercy-seat, but for the sinner to look towards in time of need?

Neither must thou hearken to the questionings of the insnaring questioner;
but cleave to that which shuts them out, keeping to the sense of the love and mercy,
when the Lord is kind and tender to thee.
When the enemy entered thy habitation again, and broke thy rest, peace,
and enjoyment of the Lord; again, an earnest desire after cleansing arose in thee;
not from the life, but in the evil; this was also a means to rob thee of that, which,
in its abiding and powerful operation cleanseth the heart; and here,
thou wouldst be limiting the Lord in his dealings,
who worketh according to the counsel of his own will,
and visiteth when and where he pleaseth.
And thus the enemy having caught thee with his mysterious workings,
he than draws thee into the pit of darkness, where the remembrance of life,
and the sense of mercy and love vanisheth; and there is no help for thee,
by any thing thou canst do or think.
But be patient, till the Lord`'s tender mercy and love visit thee again; and then,
look up to him against this and such like snares,
which would come between thee and the appearance of the Lord`'s love;
that thou mayst feel more of his abidings with thee, and of the sweet effects thereof.
For, these things are not to destroy thee, but to teach thee wisdom;
which the Lord is able, through many exercises and sore trials, to bestow upon thee;
which my soul will exceedingly rejoice to hear the tidings of;
that thy heart may be rid of all that burdeneth,
and filled with all it rightly desires after,
in the proper season and goodness of the Lord;
to whose wise ordering and tender mercy I commit thee, remaining

Thy faithful friend,

I+++.+++ P.

=== TO ABRAHAM GRIMSDEN

FRIEND,

Thou hast made some profession of truth, and at times come amongst us;
but whether thou hast been changed thereby,
and been faithful to the Lord in what has been made manifest to thee,
belongs unto thee diligently to inquire.
There is no safe dallying with truth.
He that puts his hand to the plow, must not look back at any thing of this world;
but take up the cross and follow Christ, in the single-hearted obedience, hating father,
mother, goods, lands, wife, yea, all for His sake; or he is not worthy of Him.
The good hand of the Lord is with his people,
and he blesseth them both inwardly and outwardly;
and they that seek the kingdom of heaven, and the righteousness thereof,
in the first place, have other things also added: but they that neglect the kingdom,
and are unfaithful to truth, seeking the world before it,
the hand of the Lord goes forth against them, and they many times,
miss of that also of the world, which they seek and labor for.

Truth is honorable.
Oh! take heed of bringing a reproach upon it, by pretending to it,
and yet not being of it, in the pure sense and obedience,
which it begets and brings forth in the hearts and lives of the faithful.
But if any be careless and unfaithful to what they are convinced of, and so,
for the present, bring a reproach upon God`'s truth, which is altogether innocent thereof;
the Lord, in his due time, will wipe off that reproach from his truth and people;
but the sorrow and burden will light upon themselves,
which will be very bitter and heavy to them,
in the day that the Lord shall visit them with his righteous judgments.

Oh, consider rightly and truly!
It had been better for thee, thou hadst never known truth,
nor been directed to the principle and path of righteousness; than,
after direction thereto, to turn from the holy commandments,
and deny obedience to the righteous One.
The Lord give thee true sense and repentance, if it be his holy pleasure,
and raise thee out of this world`'s spirit, to live to him in his own pure Spirit.
It is easy to profess and make a show of truth, but hard to come into it.
It is very hard to the earthly mind, to part with that which must be parted with for it,
before the soul can come to possess and enjoy it.
Profession of truth, without the life and power, is but a slippery place,
which men may easily slide from; nay, indeed, if men be not in the life and power,
they can hardly be kept from that which will stain their profession.
The Lord, who searcheth the heart, knows how it is with thee: oh, consider thy ways,
and fear before him, and take heed of taking his name in vain,
for he will not hold such guiltless!

I am, in this, faithful and friendly to thy soul, desiring its eternal welfare,
and that it may not forever perish from the presence and power of the Lord.

I+++.+++ P.

=== TO +++_______+++ +++_______+++

FRIEND,

God breathed into man the breath of life, and man thereby became a living soul to God,
to whom by transgression he died.
But Christ (who was before Abraham, and, in due time,
took up that body prepared by the Father) is the resurrection and the life, who,
from the father, breathes life into man again, and so he comes to live again.
And man, being quickened by Christ, is to rise up from the dead,
and travel with Christ into the land of the living.
And Christ is all to the believers, in whom dwells all fulness;
the circumcision is in him, the baptism in him, and the righteousness, rest,
and peace also; yea, in him are all the treasures of wisdom and knowledge;
and he is made of God, unto them that believe in him, wisdom, righteousness,
sanctification, and redemption.
Now, it is very precious to feel this;
but of little value to imagine or comprehend apprehensions about this.
For the end of words is to bring men to the thing; but the Scribes and Pharisees,
by their apprehensions upon the words given forth by the Spirit,
missed of the thing (though they thought they missed not,
but were blessed in the knowledge of the law,
and they that knew not the law were cursed):
and the same spirit is alive in many that profess truth now, who,
by their understanding of scripture words,
are kept from the thing which the Scriptures testify of.
What did Christ come in the flesh and suffer for, but to unite and reconcile to God?
and what is the antichristian way of erring from the truth,
but to cry up the appearance of Christ in the flesh, his sufferings, resurrection,
ascension, etc., in that spirit,
wherein the true union and reconciliation is not witnessed?
If we receive the light, and walk in the light, as God is in the light,
then have we a share in his Son`'s death and atonement,
and his blood cleanseth from unrighteousness; but not otherwise.

Oh that all who truly desire salvation, might know the way hither,
and receive that from God, which cleanseth and keepeth clean!
Amen.

=== TO +++_______+++ +++_______+++

FRIEND,

The Lord God on whom I wait, and whom I worship in spirit and truth,
and whom it is my delight to serve and obey,
hath divers times engaged my mind to write to thee in true and tender love.
There is somewhat, also, on my heart at this time to thee,
concerning the state of the gospel in general,
and in particular concerning the state and condition of those,
who truly know and serve the Lord Jesus Christ, the King of saints.

The state of the gospel in general,
is a state of redemption and deliverance from the soul`'s enemies;
of which redemption every soul partakes,
according to its faith in and obedience to the Truth,
and according to its growth in him who is true.
The babes in Christ and little children, their sins are forgiven them for his name`'s sake.
The young men have fought valiantly, and have overcome the wicked one.
The old men, or elders in the truth,
they are experienced in the heavenly wisdom and knowledge of Him who is from the beginning.

Now, there are some things which belong to all in general, or which are common to all,
and somewhat which is peculiar to each member in particular.
These things, which belong to all in general, are very many;
but it is only on my heart to mention to thee at this time
those few which the apostle recites together in Eph. 4:4-6,
which indeed comprehend much; and he that knoweth and partaketh of them,
hath also a share in, and benefit by, all the rest.
First, he saith, "`There is one body.`" There is one head; and this one head hath one body,
of which all that are truly living are members.
Secondly, "`There is one Spirit,`" which quickens, keeps alive, and gives nourishment to,
ordereth, comforteth, defendeth this one body.
Thirdly,
"`There is one hope of`" their "`calling;`" for they are all called from the land of darkness,
and out of the shadow and dominion of death, to travel towards an inheritance of light,
and life everlasting.
Fourthly, There is "`one Lord,`" who hath power over, and the rule and dominion of,
this one body; to whom they are all to give an account daily of what they do,
and at the last day, of what hath been done in their body of flesh.
Fifthly, There is "`one faith,`" wherewith they all believe in, and draw virtue from,
the head; which faith is the gift of God, and springs from the root of life in his Son,
and is of another nature than that natural ability of believing,
which is found in mankind.
Sixthly, There is "`one baptism,`" by the one Spirit;
whereby all the true members are baptized into the one living body,
and come to partake of the virtue, benefits, and privileges thereof.
Lastly, There is "`one God and Father of all,`" who begat them all,
and is to be worshipped by them all, as their Lord and God;
he being witnessed and experienced by them to be "`above all, and through all,
and in`" them "`all.`" This is the state in general, the gospel state,
into which Christ gives his sheep--his Father`'s children--entrance;
and it is a blessed thing to know and experience this state, that is,
to have a real interest in, and really to partake of, these things.

The state of every one in particular is thus:--"`Unto
every one`" in particular "`is given grace,
according to the measure of the gift of Christ.`" Grace and truth comes by Jesus Christ;
for the fulness is his, yea, he is the fulness;
and of his fulness doth he give a measure to each member in particular.
Not to all a like proportion, but to every one some;
as he pleaseth to distribute and proportion out the gift of his grace to them.
For it is his own, and he may dispense his gifts and heavenly talents as he pleaseth;
and according to the state of each in the body, and according to their work and service,
so doth he proportion out his gift of grace to them.
Now, this is that which every one is to mind; even the grace given to them,
their own gift from Christ, to grow in that, and to be what they are in that.
He that hath none of this grace, he is none of Christ`'s;
and he that hath received the grace, the free gift, he is to keep to the measure of it,
in all he is and does.

Now, shall I say to thee, feel my love in these lines?
or shall I not rather say, feel the love of my God, who visits thee yet again,
and would not have thee perish, in resisting his Holy Spirit,
and slighting the grace and truth which is by Jesus Christ,
which is now powerfully revealed in many hearts?
Blessed be he who hath visited his people with the horn of salvation.

I+++.+++ P.

=== TO +++_______+++ +++_______+++

O DEAR FRIEND!

The eternal love of my Father is to thee; and, because he loves thee,
and would entirely enjoy thee,
therefore doth he so grievously batter and break down that which stands in the way.
What he is doing towards thee, thou canst not know now, but thou shalt know hereafter.
Only be still, and wait for the springing up of hope,
in the seasons the Father sees necessary; that thou mayst not faint under his hand,
but be supported by his secret power, until his work be finished.
The great thing necessary for thee at present to know is the drawings of his Spirit;
that thou mayst not ignorantly withstand or neglect them,
and protract thy day of thy redemption.

Oh! look not after great things: small breathings, small desires, after the Lord,
if true and pure, are sweet beginnings of life.
Take heed of despising "`the day of small things,`" by looking after some great visitation,
proportionable to thy distress, according to thy eye.
Nay, thou must become a child, thou must lose thy own will quite by degrees.
Thou must wait for life to be measured out by the Father,
and be content with what proportion, and at what time, he shall please to measure.

Oh! be little, be little; and then thou wilt be content with little: and if thou feel,
now and then, a check or a secret smiting,--in that is the Father`'s love;
be not over-wise nor over-eager, in thy own willing, running, and desiring,
and thou mayst feel it so; and by degrees come to the knowledge of thy Guide,
who will lead thee, step by step, in the path of life, and teach thee to follow, and,
in his own season, powerfully judge that which cannot nor will not follow.
Be still, and wait for light and strength; and desire not to know or comprehend,
but to be known and comprehended in the love and life, which seeks out, gathers,
and preserves the lost sheep.

I remain thy dear friend, and a well-wisher to thy soul, in the love of my Father.

I+++.+++ P.

=== TO +++_______+++ +++_______+++

DEAR FRIEND,

I received thy letter kindly, and in the tenderness of love,
which desires thy enjoyment of the Lord in this world,
and the eternal welfare of thy soul with him forever.

It is a great matter, to have the mind rightly guided to that wherein God appears,
that the soul may wait at the posts of wisdom, to hear wisdom`'s voice;
and he that hears and observes wisdom`'s voice, what saith wisdom concerning such an one?
"`I will pour out my spirit unto you, I will make known my words unto you.`" Prov. 1:23.

Thou hast read in the Scriptures, of the kingdom of God, which,
Christ told the Pharisees, was within them.
He also, in parables, expressed what it was like; even like a grain of mustard seed,
like a pearl of great price, like a lost groat, or piece of silver,
like a treasure hid in a field, like leaven, etc.
Now, oh that thou mightst come to the discerning of this.
Is there any such thing in thee?
Surely, there is.
Dost thou know it?
art thou in union with it?
is it grown and enlarged in thee?
is there room made for it, and doth it overspread thy heart?
Oh that it were thus with thee!

Whereas thou sayest, The covenant, the new covenant, is contained in the Scriptures;
that expression of thine is not clear, and to the nature of the thing.
There are, indeed, descriptions of the covenant in the Scriptures;
but the covenant itself as an agreement of life and peace,
made with the soul in the Lord Jesus Christ, upon his believing in His power,
and obeying His voice; according to that scripture, "`Hear, and your souls shall live,
and I will make an everlasting covenant with you,
even the sure mercies of David.`" Isa. 55:3. Now, this is it the soul is to wait for;
even to feel the power of life breaking the bonds of death,
and opening the ear to the voice of God`'s Spirit,
that it may receive the impressions thereof, and feel the new creation inwardly,
the new heart, the new mind, the new law of life,
written within by the finger of God`'s Spirit,
even the law of the Spirit of life in Christ Jesus.
And then this law is the rule inwardly,
as the outward law was the rule to the outward Jews.

Thou thinkest me somewhat too sharp and severe,
in my sentence concerning the ministers +++[+++of the day]. I do not remember that passage.
I have received great mercy, and I would not be sharp or severe towards any.
If, therefore, any such thing was, be assured it was in faithfulness to the Lord.
All sorts of Christians own Christ in words, but all do not distinguish, discern,
+++[+++nor are]
subject to, the appearances of his Spirit and power; but resist, gainsay, and oppose,
through error and mistake at first, till at length they come to hardness.
These are the builders who refuse the Corner-stone.
The builders rejected Christ`'s appearance in flesh, in the days of his flesh;
and the builders again refuse his appearance in Spirit, in this day of his Spirit.
Oh that any who are tender among them might be sensible of it! that they
might not draw down God`'s severity and sharpness upon their heads;
which if they do, it is not our joy, but matter of grief to us.
And, friend, the state of profession is not what it was, when thou and I were acquainted;
but a withered state in comparison of that.
I can truly say, concerning many professors, Oh that I could find them to be now,
what they were twenty years ago!
They have got more head-knowledge;
but that savor of life which then was in them is not now to be found among them.
Truly, I speak not otherwise concerning them,
but as I feel the Spirit of the Lord testifying in me;
neither would I have mentioned this at this time, but for thy sake.
Whatever is of God in any, my heart cannot but own:
but many take that to be of God (that fear, that faith, that love, those prayers,
those hopes, that peace, that joy, etc.), which is not of him.
Oh, how precious is that which truly and rightly distinguisheth! "`My sheep hear my
voice.`" The voice of the Shepherd distinguisheth ever deceit and every deceiver.

But whereas thou sayest, The spirits are to be tried by the Scriptures;
I have found it otherwise in my experience.
The Scriptures may try words; but nothing can try spirits, but the Spirit.
"`I will know,`" said the apostle, "`not the words of them that are puffed up,
but the power.`" Deceivers may come with scripture words,
but they cannot come with the true power.
Therefore, the Apostle John, who bade the believers try the spirits, told them,
they had an unction from the Holy One, and pointed them to the anointing. 1 John 2:20,27.
But who can judge of this, but he that hath the anointing,
and is taught of the Lord to try things by it?
he knows how it tries,
and what a certain judgment it gives concerning the nature of things,
and concerning every voice and every appearance.
The Spirit of God searcheth all things, discerns all things,
discovers all things,--every snare, every device of the enemy,
the net spread ever so secretly; blessed are they,
whose eyes are opened and kept open by him.

There was a time of great darkness befell me,
wherein all that I had known and formerly experienced was hid from me; and I cried out,
"`I know not the Lord; and yet I cannot live without him.
Oh! what shall I do?`" etc.
But I never denied Christ to be the way of salvation, in my deepest darkness and distress.
And now at length,--blessed be the Lord!--I have lived to see the day,
wherein he is made of God, wisdom, righteousness, sanctification, and redemption to me;
and I feel his blood sprinkled and overflowing, which makes whiter than snow;
and find him to be the mercy-seat, through whom I have access to God;
and live by mercy and the deep compassions of God towards me, which,
because they fail not, but are daily renewed upon me,
therefore is my soul preserved in life before my God.

Oh, wait to know that wherein the Lord inwardly appears! and take up the cross
of our Lord Jesus Christ to everything that is contrary to God;
that it all may be crucified in thee,
that thy soul may live in the abundance of life and peace.
God is not straitened to any of the children;
oh that none of them may be straitened in their own bowels!
And be not discouraged because of any weakness, or because of thy age.
What knowest thou, what the Lord will do for thee?
Thy weakness is not thy disadvantage, but thy advantage;
for the weaker thou art in thyself,
the fitter art thou to have Christ`'s power revealed and manifested in thee.
Only wait to know that wherein God appears in thy heart, even the holy seed,
the immortal seed of life; that that may be discerned, distinguished,
and have scope in thee; that it may spring up in thy heart, and live in thee,
and gather thee into itself, and leaven thee all over with its nature;
that thou mayst be a new lump, and mayst walk before God,
not in the oldness of thy own literal knowledge or apprehensions of things,
but in the newness of his Spirit.

The Lord appear to thee,
in the light and demonstration of his Spirit in thy heart and conscience, touch thee,
quicken thee, lead thee, guide and make thee sensible of every appearance of his;
that no motion or drawing of his Spirit may be quenched in thee,
nor any motion of the contrary spirit, under any deceivableness, hearkened to;
that thou mayst travel faithfully,
and come to the end of thy travels with joy and full peace,
reaping the sheaves in life everlasting, of all that thou hast sown to the Spirit.

This is the earnest and single desire of my soul for thee,
who am thy true and faithful friend, and a hearty well-wisher to thee and thine.

I+++.+++ P.

=== TO RUTH PALMER

MY DEAR FRIEND,

Whose love I am sensible of, and whom I entirely wish well unto, and desire for thee,
that thou mayst purchase and possess the pearl of price;
and so know and enjoy Christ Jesus, the Lord,
as that thou mayst witness him to be eternal life to thy soul.

I received a letter from thee, which occasions this my writing to thee.
It is precious, indeed, to have the Spirit of God witness to us,
that our sins are pardoned.
And they who are truly pardoned, to whom the Spirit so witnesseth, receive the Spirit;
indeed, all that are Christians receive the Spirit;
for he that hath not the Spirit of Christ, is none of His.
And where the Spirit is, there is He who hath power over sin,
who delights to exercise his power in mortifying and subduing sin,
and in reigning and triumphing over it.
Now, they that have received the Spirit, are to live in the Spirit,
and walk in the Spirit; and doing so, they cannot fulfill the lusts of the flesh,
nor love the world, nor the things of the world, nor fashion themselves according to it;
but are redeemed out of it, in heart, spirit, life, and conversation, up to God.
O my friend! let no religion satisfy thee, but that which brings thee hither,
and which brings forth this fruit in thee.
We must needs own Christ to be the spring, and that we can do nothing without him,
but only by, and in, and through him; because we daily experience it to be so.

As touching election, we do believe it, according as the Lord hath taught us,
and as the Scriptures express it:
but such an election as shuts out any from the salvation
God hath prepared for the sons of men,
we cannot own;
because the Scriptures expressly testify that God "`would have all to be saved,
and come to the knowledge of the Truth.`" Yea, also, we know it to be his nature.
It is the nature of the destroyer to destroy,--he would have none saved;
but it is the nature of God, the Saviour, to save,--he would have none perish.
But as there is a making the calling and election sure,
so there is first a coming into the calling, and into the election.
Now, the election cannot perish, nay, the elect seed cannot be deceived.
And, as we are chosen in him,
and come into him (out of darkness into his marvellous light,
out of death into his life), so we must abide in him:
and the promise is to him that continues unto the end.
And Christ said to the church of Ephesus, "`Remember from whence thou art fallen,
and repent, and do the first works; or else, etc.: and mind, what a state they fell from,
and how far they were fallen, when so severely threatened.
It was not wholly; it was but from the first love and first works; and yet,
if they repented not, how great was their danger.

As for that place of Rom.
11, it is manifest that there is an election, and that this election is not of works,
but of grace.
Yet, there must be a hearing of the voice; "`Today,`" said the apostle,
"`if ye will hear his voice;`" and so, there must be a coming to Christ,
and an abiding in him, and a walking in the strait way; for it is the way God chooseth.
God hath chosen Christ, and the soul in him; and the message is to invite to come to him,
and abide in him to the end.
And the condemnation is upon rejecting him, and the salvation, to them,
that receive him,--which is not of man`'s self neither, but men are made willing so to do,
in the day of God`'s power; and the power is not far from, or wanting to any,
in the way that the Lord hath appointed; though there are also the aboundings of love,
mercy, and power according to his pleasure.
The falling away is, not because persons were not elected,
but because they let in that which is contrary to the election, and cleave to it.
So there is a "`heart of unbelief,`" in which men depart from the living God,
and make shipwreck of faith and of a good conscience; and the ground of their falling is,
their hearkening not to the Lord, but to the voice and temptations of the enemy.
There are called, and faithful, and chosen.
These are states, to be come into and abode in.
Many may be called, who never come to be faithful, nor chosen.
To witness the peculiar choice of God, this is precious:--and then,
not to be content with a touch of the calling, or a touch of the election,
but to "`make`" them "`sure.`" There is no choosing but in the seed.
Make sure of that seed, and thou maketh both thy "`calling and election sure.`" For indeed,
"`many are called, but few chosen.`" And yet, when a man comes thus far,
so as to know himself chosen, is he quite out of danger?
Did not Paul know his election sure?
yet, was he not afterwards careful to keep that under and in subjection,
which was to be kept under and in subjection?
"`lest,`" saith he, "`when I have preached to others, I myself should be a cast-away.`"

Thou sayest, Whom God once loves, he loves to the end.
Did he not once love all men, even the whole world?
Did he not manifest it, in sending his Son for them?
And they that come into his Son, they come into his love;
and they that come into his love, must continue in his love and in his goodness.
For, it is not persons ("`God is no respecter of persons`"), but the seed, God loves.
"`In thy seed shall all the families of the earth be blessed;`" and, in that seed,
they are loved, and continuing there, they continue in the love.
It is true, God`'s grace appears, and thereby many are gathered.
And when any fall, the grace of God appears again, and thereby many are restored.
But if any be hardened by "`the deceitfulness of sin,`"
that they hearken not to the voice of grace,
when it comes to restore, are they restored by it?
And God`'s compassions failed not to Israel of old, nor to Israel now; yet,
were none consumed then, who, though they came out of Egypt, yet rebelled, and lusted,
and tempted Christ, etc., and so were destroyed of the destroyer?
And so, do none make shipwreck of faith now, whereby the standing is?
as the apostle expresseth, Rom. 11:19-22. Read, and consider.
And the apostle, in the sense of things, cries, "`Oh, the depth!`" etc.
Love in severity, mercy in severity!
If it be stopped one way, it will break forth more abundantly in another way.
And, "`who hath known the mind of the Lord,`" or given him counsel,
which way he should manage his love and mercy?
as in ver. 33-34 of that 11th chapter.
Indeed, all the salvation is to be ascribed to God,
and is ascribed to God by all that receive salvation from him; but still,
God saves in the way he hath appointed (in coming into the way, in abiding in the way,
in walking in the way),--there, alone is safety; but out of it,
death and destruction forever.

All our best righteousness is as filthy rags, it is true;
but the gift of God is not as filthy rags,
the righteousness of his Son revealed in the heart, is not as filthy rags.
The pure offerings and incense, which are offered up to God in the times of the gospel,
are not as filthy rags.
See Mal. 1:11; and consider, whether he that offers up to God the male,
offers up a corrupt thing, a filthy rag, or no, ver. 14. Oh,
what a state of blindness are many in,
that they cannot distinguish between what is of themselves, and what is of God in them:
and so avoid offering up the corrupt thing, and offer up that which is holy and pure,
even the holy sacrifice, with the holy fire, upon the altar of God!
Consider 3rd ch.
3rd verse of Malachi; and tell me, if thou knowest, what an offering in righteousness is,
whether it be as filthy rags, or no.
Consider that place, John 3:21. "`He that doeth truth cometh to the light,
that his deeds may be made manifest,
that they are wrought in God.`" And what are those deeds, that are wrought in God?
Is not God holy and pure?
And is any thing wrought in him, but what is holy and pure?
And mind that place, where the prophet speaks,
"`All our righteousnesses are as filthy rags,`" etc.
Mind ver. 5, and ver. 6, of Isa.
64, and see if they be not two different states?
None of those, whose righteousness was as filthy rags, called upon the name of the Lord,
ver. 7. Did not the prophet call on the name of the Lord?
The prophet there represents the state of backsliding Israel,
that did not remember God in his ways, nor, through faith, work righteousness,
as some others did; ver. 5, all their offerings, all their sacrifices out of the faith,
were as filthy rags, as the cutting off a dog`'s neck, etc.; but the offering of Abel,
and the sacrifice of the righteous were not so, in any age or generation.
Therefore, we should wait rightly to distinguish things,
and not jumble the precious and the vile together, as if they were all one.

As for method of speaking, I have none of my own, but wait for the method and words,
which God`'s wisdom teacheth.
Indeed, when I speak of the light, and the life, and the power, I do mean Christ Jesus,
who is the light, life, and power; but it is a great matter,
to come to know him so revealed in the heart; for where he is so revealed, darkness,
and death, and the power of Satan, are scattered and put to flight by him.
Yea, Satan falls like lightning before the power of his kingdom, where it is revealed.

This is a blessed experience; and these know Christ indeed.
The Lord grant that thou mayst so do! which is the
hearty desire of thy soul`'s true and faithful friend,

I+++.+++ P.

=== TO JOSEPH WRIGHT

I ENTREAT thy son to acquaint my brother Arthur, that I took very kindly,
and was very glad of, his affectionate expressions towards me;
having been somewhat jealous, that though my religion had enlarged my love towards him,
yet his religion might have diminished his to me.
I bless the Lord on his behalf that he enjoys his health so well; and for myself,
though I have been exceedingly weakly formerly, yet the inward life and comfort,
which the Lord daily pleaseth to administer to me,
increaseth the health and strength of my natural man, beyond my expectation;
blessed be my tender and merciful Father, who hath visited one so distressed, miserable,
and helpless as I was, for so many years!

And whereas he saith, he is like me in speech, but most unlike me in opinion;
I pray tell him from me, that my religion doth not lie in opinion,
but in that which puts an end to opinion.
I was weary and sick at heart of opinions;
and had not the Lord brought that to my hand which my soul wanted,
I had never meddled with religion more.
But as I felt that in my heart which was evil and not of God,
so the Lord God of my life pointed me to that of
him in my heart which was of another nature,
teaching me to wait for and know his appearance there; in subjection whereto,
I experience him stronger than the strong man that was there before; and by his power,
he hath separated me from that within, which separated me from him before;
and thus being separated, truly I feel union with him,
and his blessed presence every day; which, what it is unto me, my tongue cannot utter.

I could be glad, if the Lord saw good, that I might see my brother before I die;
and if I did see him, I should not be quarrelling with him about his religion,
but embrace him in brotherly love, and in the fear of the Lord.
As for his being a Papist, or an arch-Papist,
that doth not damp my tender affection to him.
If he be a Papist, I had rather have him a serious than a loose Papist.
If he hath met with any thing of that which brings forth a holy conversation in him,
he hath so far met with somewhat of my religion,
which teacheth to order the conversation aright, in the light,
and by the spirit and power of the Lord Jesus.
My religion is not a new thing,
though newly revealed more fully than in many foregoing ages;
but consists in that which was long before Popery was,
and will be when Popery shall be no more.
And he that would rightly know the true church,
must know the living stones whereof the true church is built,
against which the gates of hell cannot possibly prevail.
Oh, the daily joy of my heart,
in feeling my living membership in this church! where the true "`gold,`"
the "`white raiment,`" the pure "`eye-salve`" (with which the eye,
being anointed, sees aright), are received and enjoyed inwardly,
by such as the world knows not, but despiseth: blessed be the name of the Lord!

I desire my sincere, entire affection, as in God`'s sight,
may be remembered to my dear brother.

I+++.+++ P.