[#ch1, short="Things of Great Weight and Concernment to All"]
== Some Things of Great Weight and Concernment to All,

[.heading-continuation-blurb]
Briefly opened and held forth from a true sense and understanding
for the healing of the ruins and breaches, which the enemy of mankind hath made in men`'s souls, as

[.heading-continuation-blurb]
I+++.+++ Some Assertions concerning the Principle and Way of _Life_

[.heading-continuation-blurb]
II+++.+++ Some further Directions to _Christ,_ the Principle and Fountain of _Life_

[.heading-continuation-blurb]
III+++.+++ The End of _Christ`'s_ Manifestation, his Salvation and whom he saves

[.heading-continuation-blurb]
IV+++.+++ Three Questions answered, concerning Justification

[.heading-continuation-blurb]
V+++.+++ Of the pure, constant, eternal, unchangeable Nature of God`'s truth

[.heading-continuation-blurb]
Written in the time of my confinement in Aylesbury, when Love was working in me,
and the Life of God in me travailing and wrestling with the Lord for the salvation of others

[.section-author]
By Isaac Penington

[.section-date]
1667

=== I. Some Assertions Concerning the Principle and Way of LIfe

That it is a great and hard matter to come into a
capacity of knowing and receiving the truth.
It is no hard matter to take up any religion that a man finds in the world.
To read scriptures, to believe what a man finds related there,
according to his understanding of them; yea,
to believe that he hath the light and help of the Spirit in his reading and understanding;
to apply himself also to practise and observe what he finds therein required;
and to aim at holiness, etc.; this is no hard matter; every man that is serious,
and seeks religion of any kind but in the weight of a man`'s spirit, may go thus far.
But all this administers not the true capacity, but he that meets with it,
must go further than thus.

[.numbered-group]
====

[.numbered]
2+++.+++ That which gives the true capacity is a principle of life from God,
and there alone and nowhere else, can man meet with it and receive it.
This principle is the seed of the kingdom, or heavenly leaven,
with which the mind must be in some measure leavened,
ere it can come into a true capacity of understanding and receiving the truth.
And in this leaven must it abide and grow up, if it abide and grow in the true knowledge, etc.

[.numbered]
3+++.+++ That from this principle, and in this principle,
not only the true light and knowledge of the Lord Jesus
Christ and all spiritual things is given and received;
but also the true faith, the true love, the true sanctification, the true justification,
the true peace, the true joy, etc.
And what of these is not received and held here, is not of the truth,
but a garment of men`'s own forming, and not the covering of the Spirit.

[.numbered]
4+++.+++ That the Spirit himself sows this principle, and is received in this principle.
And he that receives this principle, and is born of this principle,
receives and is born of the Spirit; and he that receives it not, nor is born of it,
neither hath received nor is born of the Spirit;
but is but in the imagination and self-conceit about the things of God,
but is not in the truth as it is in Jesus.

[.numbered]
5+++.+++ That in this principle the new covenant is made with the soul and entered into;
and he that receives this principle from the hand of God, receives life,
and enters into the covenant of life, and feels the pure fear,
wherein God cleanseth the heart, and whereby he keeps the heart clean,
and feels the laws of God daily writing there by the finger of God`'s Spirit,
and feels the power and sense of the Spirit to teach and cause obedience;
so that the yoke,
which is hard to the transgressing nature (alienated from the life and power),
is easy (and as I may say natural) to him that is born of this nature.
For being dead with Christ, and risen with Christ, and changed into the nature of Christ,
by the principle which is of him, through the power and Spirit of Christ,
which worketh therein; he can say as Christ did, when the Lord calls him to any thing;
Lo, I come; it is my meat and drink, yea, my great delight, to do thy will, O God! yea,
thy law is written in the midst of my bowels!

[.numbered]
6+++.+++ Among those who are gathered into this principle, and abide in the sense, light,
and life of this principle, there is great love and unity.
They are of one mind, of one heart, of one soul, of one spirit, of one life,
gathered into one demonstration of truth; and there is no jarring, no doubting,
no dissenting, etc.
All this is out, in the world, in the earthly wisdom,
in the earthly professions and walkings; but it is excluded the principle of truth,
and them that are gathered into and abide therein.

[.numbered]
7+++.+++ That all that are not gathered into, nor walk nor live in this principle,
they are yet in the darkness and error from the pure power of God,
and stand and walk in slippery places; and though their way may seem very right,
and their estate and condition sure (as to God-wards) in their own eyes and judgment,
yet it is not really so; but they are but in a dream concerning the truth,
not in the truth itself;
which (how strange soever it may seem to them at present to be affirmed
concerning them) yet they shall certainly feel it to be so,
when the Lord by his powerful voice and bright appearance of his Spirit awaketh them.
For many things go for truth now with men in the dark,
which will vanish like smoke before the light of the day;
and then that only which is truth indeed shall have
the glory and praise of being accounted so;
and then what will become of those who have mistook about truth,
and are not clothed with the pure wedding-garment
(the spotless life and righteousness of the Son),
but only with that which they have accounted so?

[.numbered]
8+++.+++ That to those that see in the light of this principle,
the mountain of the Lord`'s house is discovered;
and those that abide and grow up therein,
they know and experience it established above all mountains, and exalted above all hills;
all earthly knowledge, earthly religions, earthly ways, earthly worships,
earthly spirits and minds, etc., in their greatest exaltations and glory,
being far beneath it.
And here the feast of fat things, and wines on the lees well refined,
even the fruit of the vine which gladdeth and refresheth the very heart of God,
is fed on and partaken of by those that dwell here.
For the Father, and the Son, and the Spirit is here revealed,
in the holy house and tabernacles which are built here; and here they make their feast,
bringing forth the riches of their nature, spirit, and precious life,
on which they feed with the soul,
and give unto the soul favor and ability to feed with them;
in which food there is the life, strength, righteousness,
and joy of the kingdom given forth and received.

[.numbered]
9+++.+++ That in the heart which discovers iniquity, reproveth it, witnesseth against it,
and striveth with the mind to turn it from it,
and to wait for life and power from on high, that is this very principle.
In that is the divine nature, even the nature of God`'s Spirit,
which was always against sin, and ever will so be,
and in all its appearances testifieth against it,
and in love to the creature striveth with the creature to
convince it of that in it which is contrary to God,
and to draw it to that strength and divine virtue which stoppeth it, beateth it back,
and worketh it out of the mind and nature of the creature, as it can get entrance,
and is hearkened and subjected to.
For there is no salvation, but by the cross and yoke of our Lord Jesus Christ;
for in that is the power to crucify the affections and lusts,
which lead into sin and death, and will not cease to tempt and lead aside,
till the soul be gathered into unity with that,
and become subject to that which is contrary to them.
So that this is the main thing in religion,
even to know Christ revealed in the soul as a standard against corruption,
and to be gathered under his banner, which is the cross,
or that living principle in the heart which resisteth the corrupt principle;
and he that is gathered hither, and continueth faithfully fighting here,
shall receive mercy, help, and strength from on high, in every time of need.

[.numbered]
10+++.+++ That the true and certain way of knowledge of the things of God,
is in the faith and obedience of this principle.
It is not by reasoning and considering things in the mind (after
the manner of men) that a man comes to know spiritual things;
but they are spiritually revealed by God, after a spiritual manner, to the believer,
to the obeyer; and they are revealed to him in his believing, in his obeying,
in his waiting, in his holy fearing, in his distrusting of himself,
and feeling his own insufficiency, either to attain them or retain them,
but as the Lord God makes them manifest in him and preserves him in the sense of them.
"`He that doth my will, shall know of my doctrine,`" saith Christ.
This is the way.
Wouldst thou know what God requires of thee,
what this or that is which appears in this or that sort as truth, whether it be so or no?
Mind this principle in thee, mind the pure, the holy light,
inward touches and leadings of this pure, divine principle;
that will make manifest to thee whatever is fit for thee in thy present state to know;
and thou art not to desire more,
but as a child to rest contented with that portion of knowledge and strength,
which the wise and tender Father judgeth fit for thee;
and as thy state groweth capable of more, he will not fail to administer to thee.
And what he giveth thee is good, seasonable, and proper for thee,
which thou mayest safely feed upon and enjoy in the sense and fear of him.
But if thou press after what he would not as yet have thee know,
thou enterest into the will and wisdom of the flesh; and there are the disputes,
discontents, murmurings, and ill tempers and dispositions of the mind,
which there will increase and grow upon thee to thy hurt.

[.numbered]
11+++.+++ That the mind that is gathered here will find great opposition,
both within and without;
insomuch as he shall not easily pass from out of the kingdom of darkness,
into the kingdom of the dear Son, but through many trials, temptations, oppositions,
and dangers many ways, for turning the back on the kingdom of darkness,
by joining to the principle of life, in hearkening and subjecting to the light thereof;
hereupon the powers of darkness both within and without
bestir themselves to hinder the soul`'s progress,
and to bring it back again into subjection under the will and wisdom of the flesh.

Oh, how doth the will and wisdom strive within a man`'s own bosom!
What risings of the impure are felt against the pure!
What secret and subtle reasonings to ensnare and entangle the mind! and
if they cannot draw the soul back from the Lord and the living path,
then they strive to vex, afflict, and torment it!
There is none knows what is felt inwardly by the followers of the Lamb,
but those that travel with him in the living path;
they are often sensible of that they meet with in their travels,
and how hard it is to abide in the path of salvation,
insomuch as they understand the truth of that saying:
"`If the righteous scarcely be saved.`" It is scarcely indeed! so subtle, so strong,
such a many holds, so many stratagems hath the subtle, twining, crooked,
piercing leviathan, to ensnare, perplex, over-run, and entangle them with.
And then outwardly, the same flesh, the same earthly spirit and wisdom, the same crooked,
hellish will, is striving in men without also,
to bear down and subject the pure principle in them who are born of God,
to their devices and institutions, decrees, ways, customs, etc.,
which are of the will and wisdom of the flesh.
So that, as the apostle said,
through much tribulation is the entrance of the soul into the heavenly kingdom;
and there is no avoiding the many tribulations,
but by turning aside out of the way (which though thereby the flesh get ease for a time,
it will be to the greater loss and sorrow in the end).
For the spirit of the world, the wisdom of the world, the nature, religion, worship,
and whole course of the world,
is contrary to the way of the pure wisdom and Spirit of God, and useth it as its enemy,
wherever it findeth it; and they that will not bow to the spirit, wisdom,
and way of the world, must feel the force of its beastly claws.
For is it not a beastly thing (even far beneath the
nature of a man) to persecute that which is good;
to hurt, reproach, and pursue the innocent life of the Lamb?
And yet this is that which the spirit of the world (which is not of God, but wise,
and seemingly just and righteous in another wisdom, nature,
and principle) always hath done, still doth, and will do to the end.

[.numbered]
12+++.+++ That there is a glorious crown prepared for all those,
who are gathered to the Lamb in this principle,
and abide with him faithful therein to the end, hearing his voice,
believing the demonstration of his Spirit, obeying him in all his motions and requirings,
undergoing every yoke,
which is appointed by him to yoke down the fleshly nature and mind,
and taking up every cross of every kind in meekness, patience, and fear.
And there is not only a crown laid up for them at last,
but the power of the Lord God is nigh unto them to work all in them,
to bear them up through and over all, and to keep them to and in that principle,
whereby and whereinto his tender mercy and powerful arm gathered them.
For as the power of the Lord began the work,--for there could never any heart be gathered
from under the power of darkness to the light which leads out of it,
but by the power of the Lord; for the powers of darkness stand between,
and would hold and keep their own, did not a greater power appear,
and put forth itself for the soul against them,--I say,
as the power of the Lord began the work,
so the same power alone is able to go on with it and perfect it;
and it will go on with it and perfect it upon the same terms it began, and no other.
How were the terms at first, but on a giving up of the soul in the faith to the Lord,
in the sense of his love and goodness and mercy, touching, and drawing,
and making willing?
And how is the standing, but in the same giving up still; in abiding with the Lord,
in hearkening to the voice of the Lord,
in waiting for the wisdom and counsel of the Lord?
But if any man draw back from this,
if he despise the Spirit and his motions and counsels,
and hearken to the voice of a contrary spirit, believing and following it,
like the angels that fell, he departeth from his place and habitation,
which he had in the drawings, life, and power of God,
and is not to God what he was before, nor is God to him what he was before, but the Lord,
who loved him before, and delighted in him to do him good, hath now no pleasure in him,
he being turned from that which the Lord loveth,
and in which he hath determined and appointed to choose, love,
and own the children of men; who, as they are gathered thither, are his children;
as they that are gathered from thence, into a contrary principle,
are the children of the wicked one.

====

And now what is of man in all this?
Where is the man that can boast before the Lord, who is thus saved?
He hath all from a principle; yea, he is gathered into, preserved in,
and abideth in this principle by the power, goodness, and mercy of the Lord.
The power begins the work in him, the power accompanies him;
the power carries him through, or he falls and miscarries.
There is no man can stand any longer here, than he submits to and is upheld by the power,
nor act nor suffer, but as the power acts in him and helps him to suffer.
Let the man that boasteth, bring forth somewhat of his own, if he can, here.
Is the will at any time his own?
Doth not he that is spiritual, and in the true sense,
always find God to work in him to will, whenever he willeth rightly and holily?
And if he cannot will of himself, can he do any thing of himself?
Can he believe of himself, pray of himself, wait of himself,
resist enemies and temptations of himself; nay,
so much as give a look to the Lord at any time of himself?
Indeed, in the grace of the Lord, and the principle of his life, there is sufficiency:
and therein he that is joined to the Lord, and become one Spirit with him,
what can he not do here?
but that is, as he is new-made in Christ, and as Christ ariseth, lives, and acts in him:
which he that is in the true sense and feeling will still acknowledge,
not only in his words to men, but in his heart and spirit before the Lord.

=== II. Some Further Directions to Christ, the Principle and Fountain of Life, by Way of Question and Answer

[.discourse-part]
_Question 1._ What is Christ?

[.discourse-part]
Answer.
He is the word of eternal life, who is appointed of the Father to give life,
and who giveth life to them that receive him, and obey his gospel.
He is the Son of God, the wisdom of God, the power of God, the righteousness of God,
the Saviour and salvation of God.
The peace, the rest, the joy, the life of the soul.
The King, the Priest, the Prophet, the Shepherd of the sheep.
The way, the truth, the door, the vine, the olive-tree,
into which the living are gathered and ingrafted.
And he is also a hammer, an axe, a sword, a fire to the corrupt tree and fruit.

[.discourse-part]
_Question 2._ How is Christ known, received, and obeyed?

[.discourse-part]
Answer.
As a seed; as the seed of life, as the seed of the kingdom, as a leaven, as salt;
as a little small thing, rising up in the heart against all that is great and mighty.
As a branch out of the dry ground; as a little child to lead,
which all the wisdom of man and flesh cannot but despise;
and therefore that must first be brought down in some measure in the heart,
before Christ can be owned in the heart, and subjected to.

[.discourse-part]
_Question 3._ How is the seed received?

[.discourse-part]
Answer.
By feeling its virtues, manifestations, and operations in the heart,
and subjecting thereto.

[.discourse-part]
_Question 4._ What are its virtues, manifestations, and operations?

[.discourse-part]
Answer.
They are all living, and have all living and powerful effects upon the heart,
as they are let in.
They are all against darkness, sin, and death; tending to discover it,
to turn the mind from it, to lead out of the captivity, power, and reach of it;
and they are also all for God, tending to prepare the heart for him,
and to bring it into union and covenant with him.

[.discourse-part]
_Question 5._ What is the first operation of the seed to the soul, wherein it is to be waited for,
and closed with, that the soul may come into the further sense and feeling of it?

[.discourse-part]
Answer.
It is according to the state of the soul; which being in darkness, sin, and death,
it appears as a light to discover the darkness, sin, and death,
and to lead out of it to the redeeming power.
And then, to them that thus receive it,
and wait upon it in the fear and humility which it gives and begets, it appears as life,
quickening the soul, and as power, enabling it in some measure to live to God,
and to walk with him in the way to the kingdom.

[.discourse-part]
_Question 6._ How comes this way to be hid from some that desire after the Lord,
and to know his truth as it is in Jesus?

[.discourse-part]
Answer.
From the subtlety of the enemy, who blinds the eye which alone can see,
and stops the ear which alone can hear, and hardens the heart which alone can understand;
and hath devices, snares, and baits, and false reasonings from scriptures,
and from experiences, which any one that hearkens unto, and is entangled and ensnared in,
is his captive, and cannot be at liberty to see, or know, or embrace the truth as it is;
but his heart is deceived about it, and filled with prejudices against it.
(Therefore such should wait for the true circumcision,
that they might hearken to the Lord, come out of the enemy`'s snares and subtle devices,
and live) as Isa. 55:1-3.

[.discourse-part]
_Question 7._ But may not these be saved notwithstanding?

[.discourse-part]
Answer.
There is no salvation but in and by Christ Jesus;
and the salvation is not to them that received a bare notion of him under the law,
or another empty notion under the profession of the gospel;
but only to them that receive him as he was promised, as the holy seed:
for in that alone is the redemption, freedom from sin, and power of life felt,
and no where else.
So that he that hath not this knowledge of him, hath not the true knowledge;
nor he that doth not so believe in him, doth not rightly believe;
nor he that doth not so hope in him, hope in him, doth not rightly hope:
and without the true knowledge, the right faith and hope, how can any man be saved?

Therefore awake! awake!
O weary, thirsty souls! come to the spring of life; come to the living waters.
Become little, that ye may learn of Christ; wait to have your eyes anointed,
that ye may see him, and your hearts opened, that ye may know and receive him.
Oh! wait for the manifestation of this seed in you, be abased before him, join to him,
receive his checks, receive mourning and repentance from him;
wait for the light and faith that he gives, and the power that issues from his throne,
and ye shall find him the bruiser of the serpent`'s head (which none else is able to do),
and the breaker of the bond of iniquity, which keeps down the just,
and sets the unjust at liberty, till he dissolve it.
And this is sufficient to manifest against all the disputes of the mind, that this is he,
and no other, by his doing that which none else can do.
This demonstration he gave to the Jews in the flesh, in his appearance in flesh;
and this demonstration he giveth now to the Jews in spirit, in his appearance in Spirit,
whereby he satisfieth their hearts, and putteth them out of doubt that it is he.
And we must profess to the world (as our hearts are drawn and guided by the Lord,
to give forth the testimony we have received of him) that we look not, yea,
we cannot look, for another.
Whom should we look for besides the Lamb, besides the Word which was in the beginning,
besides him who is one with the Father, and hath the eternal life, wisdom, righteousness,
and power of the Father, and manifesteth it in us?
We look indeed for more of the same,
and the more universal and powerful breaking of it forth; but another thing,
another Christ, another life, Spirit, power, etc., we cannot look for.
And this we further testify,
that whoever receives this testimony in the truth and uprightness of his heart,
waiting on that which discovers sin to him,
and in simplicity joining and giving up thereto,
and walking with him in forsaking the evil and cleaving to the good,
in the faith of him and of his power, he shall witness the same thing with us;
and all the reasonings, imaginations,
and strong-holds of his mind shall be battered down, and come to nothing,
before the virtue, power,
and life of him who thus is pleased to appear and manifest himself after the apostasy,
even as he did before, even in an inward principle, an inward seed, an inward light,
an inward life, an inward word, an inward power.
And friends and people, mark in your minds,
and learn to put a right difference between that which stumbles you,
and that which draws and convinces you.
What makes any of you own truth at any time?
Is it not an inward, lively, powerful touch and demonstration of God`'s Spirit?
What makes you afterwards doubt and question?
Is it not another thing, of a different nature from this?
Is it not a subtle reasoning, whereby the enemy twines into your spirits,
and begets first a doubt concerning, then a prejudice,
and at last a great strength against that, which before ye had some sense of,
and some unity with, in the teachings and quickenings of the Spirit of the Lord?
And what spirit is it in you, that thus worketh in your minds?
And whither doth he lead you by these workings and subtle reasonings.
Oh that ye might see, oh that ye might feel, the snare,
and know with us the preserver therefrom! for we have met with much of this;
and had we not been helped by the Lord, and given up to him,
we had been entangled to this very day, as ye are.
And he that hath helped us, waits to be gracious to you; and oh,
that you would not reject his help,
that he might deliver you also! that ye also might bless his name,
in feeling the benefit and joy of his preservation.
And this is written in true bowels and tender, yearning love,
that ye might be a little stirred up to wait to know the Father`'s house,
and might feed on the bread which abounds therein,
and drink of the water which makes fresh and living to God,
and be clothed with the raiment which the master of the family gives to his spouse,
children, and servants.

=== III. The End of Christ`'s Manifestation, His Salvation, and Whom He Saves

Christ came (and is manifest in the hearts of those
that receive him) to destroy the works of the devil,
and to set the soul free from sin; and whom he maketh free, are free indeed.
Is the liberty which the Son giveth inferior in this life, in its kind,
to the captivity and bondage of the enemy in its kind?
Which of them is stronger; the enemy to inthrall,
or the Lord Jesus Christ to set free from his thraldom?
Yes, the Lord Jesus Christ, the captain of our salvation,
the mighty Saviour (who is more able to save than the enemy to
destroy) delivereth his Israel out of the hands of their enemies,
and so mightily and powerfully delivereth them,
that they are able (in the power of his might) to serve him,
without fear of them any more,
in holiness and righteousness before him all the days of their life.

It is true, there is a state of darkness, sin, and death, wherein Satan reigns;
and there is a state of weakness, wherein Satan much prevails,
if the watch be not strictly kept to him who is the everlasting strength;
and there is a state of sighing and groaning under the body of sin and death,
and crying out, who shall deliver from it!
But there is also a state of growth in the life,
and of victory (through the life) over that which captived and caused to cry out.
There is a treading down of Satan under the feet by the God of peace,
insomuch as not only the elders, but the very young men in Christ,
overcome and triumph over him,
feeling the entrance ministered to them abundantly into the everlasting kingdom,
into which no unclean thing can enter.
Oh! wonderful is the travel to the holy rest of the pure life!
Happy are they that meet with the true leader, and faithfully follow him,
till they have travelled through and overcome all that stands in their way!
For to them, and to them alone,
is the promise of the possession of the everlasting inheritance;
and such find and feel the Lord to be their God indeed,
and themselves to be his children (brought forth in his holy life and nature),
which to feel in truth and certain knowledge is more than tongue can utter.

Christ saves only those that come unto him, and believe in him,
and so are born of his Spirit; and by the faith,
and through the strength and virtue of his Spirit, overcome the wicked one, his works,
snares, and temptations in their hearts.
And these feel in themselves the root of his life,
the holy seed of his kingdom springing up in them, into which they are ingrafted,
and become one with him, and so bringing forth the holy fruit, the living grapes,
the new and righteous conversation wherein the life of God shines, and is glorified.
Now it is not knowing, or believing,
or receiving any thing into the old understanding that avails with God,
or the reformation which is there wrought; but the new creature alone,
created of God in Jesus Christ.
This is born of God, this lives in him, this is clothed with him.
This puts off the old man, with his deeds,
and puts on the newness of the nature and Spirit of the Lord Jesus Christ;
so that this man is as really in Christ, in the spirit, in the new Adam, found in him,
formed in him, covered with him, as the first man, or nature, is in the old Adam.
Therefore this is the main thing in religion, to mind the seed of the kingdom,
the leaven of the kingdom, its growth in the mind, soul, and spirit, and the mind`'s,
soul`'s, and spirit`'s gathering into, and growth in it.
And here is faith, the true faith, the true love, the true hope,
the true meekness and patience, the true justification and sanctification felt,
and not elsewhere; but those that are out of this, out of Christ the seed,
out of Christ the Word, out of Christ the wisdom, righteousness, and power of the Father,
are only in a dream concerning these things,
but know not the truth and real nature of them, as they are felt in Jesus,
by those who are truly ingrafted in him, and livingly grow up in him.

=== IV. Three Questions Answered Concerning Justification

[.discourse-part]
_Question 1._ What is justifying, or justification with God?

[.discourse-part]
Answer.
It is God`'s owning the state, works, or actions of a creature,
either inwardly in his own mind, or manifestly to them.
This is God`'s justifying of them, or his justification;
his disowning or disallowing them is his condemnation.
As for instance: God`'s owning Adam in the upright estate of his innocency,
wherein God created him, and any thing he did in that state and spirit,
was his justifying of him and his works.
God`'s disowning and disallowing his hearkening to his wife and the serpent,
and his eating the forbidden fruit upon their temptation, was his condemnation thereof.

[.discourse-part]
_Question 2._ What is it God justifies, and what is it he condemns?

[.discourse-part]
Answer.
That which God justifieth is the Spirit of his Son, the life of his Son,
the nature of his Son, brought forth in any creature, the faith which is in him;
and so the creature, as it is in the obedience which is of him,
and the works that are wrought in him.
But the fallen estate of man from him, and all that is done by man out of him,
God condemns.

[.discourse-part]
_Question 3._ How is justification received, kept, and grown up in?
and what is the preservation out of condemnation?

[.discourse-part]
Answer.
Justification is only received by receiving him,
who is the righteousness and justification, and only kept by abiding in him,
and only increased by growing up in him.
For as every one that is found in him is justified, so he that hath more of him,
more of his life, more of his faith, more of his nature, more of his Spirit,
more of the pure obedience,
more of the garment of righteousness and salvation drawn over him,--he is more justified.
For there are degrees of justification, as the soul that is really in the thing,
and is acquainted with the true nature and dispensation of it from God, feels and knows.
A father is more or less pleased with his children, yea, with the same child sometimes;
which is a true figure to man who is come under God`'s teachings.
And the preservation out of condemnation is by being
preserved out of that which God condemns;
for no man upon the earth, that hath the true sense and feeling,
shall ever find the Holy and Just One justifying him in his sins;
but as the heart is turned from them, and by the power of life kept out of them.
He that will be kept in the justification must be
kept out of that which the justification is not to:
for there he is not justified; but in his being drawn again out of it,
and turning again from it, his justification, in the tender mercy of the Lord,
is renewed.

Justification under the law was according to that covenant.
He that walks with God in that covenant,
he that walks in and after the Spirit of Christ,--he is therein justified;
but he that walks after the flesh,
and doth any thing that is fleshly,--that is not justified with God nor he in that;
but in the faith, which cleanseth and giveth victory over it:
in that is the justification from it, and the pure,
heavenly peace with the Lord God of life witnessed.

He that is in Christ, and receiveth his knowledge from Christ,
and is kept in the pure fear and sense of him,--he
understandeth the truth of these things;
but he that is erred in spirit, and holds up but a literal knowledge (though from,
or at least accompanied with,
some remembrance of former feelings and experiences),--he errs about these things also;
and deceit and a lie hath prevailed over him, as he will find,
when the Lord confounds his wisdom and present apprehensions of things,
by awakening his witness in him.
For religion, the true religion, is a mystery; life is a mystery; Christ is a mystery;
the Spirit is a mystery; faith is a mystery; obedience (the pure obedience) is a mystery;
worship (the spiritual worship in and according to the new covenant) is a mystery;
hid from the eyes of all the wise searchers of the world,
but revealed to the least babe that is of God,
and abideth in the quickened life of his Son.
But many that are out of the mystery of truth are in the mystery of deceit,
and have a knowledge or profession concerning Christ, his Spirit, faith, obedience,
the spiritual worship, etc., in that mystery of deceit, which they, for the present,
account the true, and by it venture to judge, disallow, and condemn the truth itself;
but that is not all to the hurt of the truth, or such as are in it;
but rather to their own hurt and great danger.
For the sparks which man kindles will never light him to God;
the garments of man`'s righteousness (either according
to his apprehensions of the letter of the law,
or letter of the gospel) will never clothe him; but for all that,
he must lie down in shame and sorrow, when the truth of God appears in his conscience,
and all his shadows and deceits flee away.

Therefore hearken to the testimony from these, whom the Lord hath awakened,
whom the Lord hath quickened, whom the Lord hath led out of the darkness of the night,
into the light and brightness of the day; who have seen Jesus,
and testify what they have seen, heard, felt, and handled of that eternal Word,
which was from the beginning, which appeared in flesh, and afterwards in spirit,
before the apostasy, and hath again appeared, since the apostasy, as a shepherd,
as a gatherer, as a seeker-out and preserver of his wandering sheep,
who were driven from him in the cloudy and dark day.
And if ye would hearken aright,
breathe to the Lord in that which desires and longs after him,
that he would circumcise the heart, and open the right ear in you,
that the ear may hear his witness in you,
that so ye may indeed know the voice of the shepherd, and in true understanding, sense,
and constant experience,
bear witness to that true testimony which Christ spake in the days of his flesh:
"`My sheep hear my voice, and follow me; but a stranger they will not follow;
for they know not the voice of strangers.`"

=== V. Of the Pure, Constant, Eternal, Unchangeable Nature of God`'s Truth

Truth is of God, and was with God, and in God, before any thing else had a being.
Truth was before error or deceit: for it was from the truth that the error was,
and it was about truth that the deceit was.
There was somewhat which erred from truth, and brought in deceit into the world;
but truth remains the same that it was, keeping its pure, eternal, unchangeable nature;
and is not, nor ever was, nor ever can be, defiled or tainted with any error or deceit;
but testifieth against it, reproveth it, and condemneth for it, draweth out of it,
and delivereth from its bands and captivity, all those that hearken and cleave to it,
in the faith which is of its nature and begetting.

The Father, the fountain of truth, is the same.
The Son, his express image (whom he fills with himself, and in whom he appears),
is the same.
The Spirit, the anointing (who is truth, and no lie), is still the same.
The principle or seed of truth is still the same.
The doctrine and way of truth is still the same;
for it was the same truth which was preached in shadows under the law,
the substance whereof appears, and is witnessed in the gospel:
and it was the same before the great apostasy, in the latter days from it,
and all the time of the apostasy, and again after the apostasy.
It hath the same nature still, the same properties, the same operations and effects,
and gives forth the same testimony in the ears and hearts of all that are open to it.
Indeed the minds of men, and the states of men, may often change in relation to truth;
but truth itself changeth not, but is equal, fair, and just to all men upon the earth,
in all ages and generations, always condemning that which is unjust, erroneous,
and deceitful, and always justifying what is pure, holy, and righteous.

Now is not this a pearl; Nay, is not this the pearl indeed, the precious pearl of price?
Who would not buy it?
Who would not sell all for it?
Who would not dig in the field, where this treasure is hid, until he find it?
The field is near thee, O man! which thou art to purchase and dig in,
and must feel torn up by the plow of God in some measure,
before this pearl or treasure appear to thee;
and thou must take up and bear the yoke and cross of Christ,
until all be bowed down and crucified in thee which is contrary to its nature,
before it be polished in thee,
and thou come to behold and enjoy its riches and everlasting fulness.
Oh, happy are they that are begotten and born of it! happy are they that know its voice,
and give up to it, to be gathered and redeemed by it, out of all deceits,
out of all errors, out of all that entangles and ensnares the soul in sin, misery,
and utter perdition; for destruction and misery everlasting is out of it,
and life and salvation is alone to be found in it.

There is a witness in every heart, which knows these things,
and will testify it to their faces, when the light of God is opened in them,
and its tongue speaks therein to them.
Oh, happy they that wait for, know, hear, and subject to the heavenly voice,
while the day of their visitation and reclaiming lasteth,
wherein they may travel from sin to holiness, from death to life
by its help and guidance!
Oh! why should man perish?
Why should man hearken to that which hates him, and seeks his destruction,
and stop his ear against that which loves him,
and warns him of his danger in the dearness of love,
and in tenderness of bowels towards him?
