[#unsatisfied, short="To Such As Are Not Satisfied"]
== To Such As Are Not Satisfied with a Profession Without the True Life and Power

[.heading-continuation-blurb]
But have sincere Desires in their Hearts after the Lord himself,
and a Willingness to be acquainted with his pure living Truth,
and with the Soul`'s true Guide and Leader;

[.heading-continuation-blurb]
This experience is in my Heart to express unto you,
which we have all along witnessed in our Travels out of the dark,
corrupt Land, into the Land of Life and Purity.

[.section-date]
1668

WE have still found the willer, the runner, the self-striver, the wise,
comprehending part, etc., left behind;
and the grace of God alone able to lead towards him,
and the birth which is of and by grace still to obtain the mercy.
And Christ is our life,
and in the union with his Spirit lies all our ability and strength;
and that knowledge of Christ, which we witness to be life eternal,
we did not meet with whilst we thought to have it in the Scriptures,
but it hath been all along revealed to us by God`'s Spirit; so that we can truly say,
flesh and blood did not reveal the Son to us, but the Father.
Yet that which the Scriptures testify concerning Christ
is exactly true according as it is there related,
and is so acknowledged and really owned by us;
though we obtain not our knowledge of Christ by the letter,
but by a receiving a principle of life from God; and coming into union with his Spirit,
we came to the true knowledge and owning of the letter; which as it came from the life,
so can it only be rightly read and understood in the life from which it came:
so that he that is out of that, cannot but err concerning the letter,
and misjudge concerning the things of God; whereas he that is guided by,
and lives in God`'s Spirit (receiving his knowledge there),
cannot err concerning the Spirit, or concerning the letter; but hath that within him,
which gives to him, and preserves him in, the true sense and understanding of both.

Now, friends, this is an excellent thing indeed, to come to, and be acquainted with,
and receive that, which the Scriptures testify of; to wit, to receive Christ,
to feel union with him in his Spirit, to enter into the new and holy agreement with God,
into the everlasting covenant of life and peace, to feel the partition wall broken down,
and the wall of salvation reared up, and the defence which is thereby;
to find the law of God, the law of life, the law of the new creation,
written in the heart; the pure fear planted there by God,
which keepeth the mind and spirit from departing from him; to have his Spirit put within,
causing to walk in his ways, and to keep his statutes and judgments, and do them;
and so to have union and fellowship with the Lord
in that which is pure and living of him,
in Christ the new and living way, which was before the fall,
and leads the obedient out of the fall, even beyond Adam`'s state,
into himself who never fell, in whom is no sin, nor erring, no,
not for the wayfaring man, though a fool,
who often erred and wandered before he came thither; but there the Father`'s hand,
even the hand of eternal power, is felt, which none can pluck out of.
Oh! that ye knew the infallible Leader,
and were turned from darkness to light (and did believe therein),
and from the power of Satan unto God, that ye, through his Spirit,
might undeniably witness the mysteries of his kingdom,
and partake of and enjoy that which his love, grace, and mercy,
plentifully distributes among his children that wait upon him in one way,
under the holy ordering of his Spirit;
which was long harped at and longed after by many of us; but we could never meet with it,
till the Lord in his mercy caused the light of his day to shine into our hearts,
which chased away the darkness of the night, and made the things of the day manifest.

Are ye of the house of Jacob?
Are ye of the right seed?
Are ye of the true breathers after God`'s holiness,
after the life and righteousness of his Zion?
Oh! then come ye, know, acknowledge, receive, and wait to walk in the light of the Lord;
and do not join to that in you which is separated from, and knoweth not,
the light of the Lord, but opposeth it.
And, friends, I beseech you, take heed in this point; for he that denieth, refuseth,
opposeth, speaketh evil, or thinketh hardly of any thing that is indeed of Christ,
doth it to Christ himself, in Christ`'s account (that is,
Christ looketh upon it as if he had denied him, refused him, opposed him,
spoke evil of him, etc.), and it will be so laid to his charge in the day of the Lord.
And indeed such is my love to you,
and such my desire after your eternal good and welfare,
that I would not have you stumble at the light and power of life,
which the Lord hath revealed and stretched out (in
this day of his mercy) to gather and save with;
but feel the gathering by it from all that scattereth from the Lord,
with the preservation which is thereby,
and the effecting of that in your spirits which it is able to effect,
as it comes to manifest itself unto you, and to put forth his strength in you.
So wait for the gathering unto the light (the light of the everlasting day of God),
and into the power which is able to redeem and defend
the soul from all that is contrary to God.
And when ye are there, be diligent and faithful to the Lord:
and feel (oh! daily wait to feel from him) the unclothing
of your spirits from all their own unrighteousness;
yea, from all their own righteousness also (which is but as filthy rags before the Lord,
even of the same nature with the unrighteousness),
that ye may be clothed upon with the new and living garment,
wherein there is neither spot nor wrinkle, nor any such thing.
For they that are of Christ, and in Christ, do as really put on the nature, the Spirit,
the garment of the second Adam, as ever they did put off the old garment, nature,
and spirit.

This is from one who uprightly and singly desireth your
union with the Lord in his pure truth and holy anointing,
and your disunion from all that is contrary to him.

ISAAC PENINGTON

=== A Query added, with its Answer

WHAT is the true confession of Christ,
even that confession which ariseth from the knowledge which is life eternal?

Answer.
Friends, I witness it to be this: A confession of his nature, a confession of his Spirit,
a confession of his life, a confession of his power.
To confess the present living appearance of Christ, that is to confess Christ.
"`Behold,`" saith he, "`I stand at the door and knock.`" He that heareth his voice,
acknowledgeth him, letteth him in,
subjecteth to his truth and Holy Spirit,--he confesseth him.
But though a man should acknowledge and confess all
that is recorded in the Scriptures concerning him;
yet if he know not his knocks, so as to let him in, and become subject to his power,
he doth not confess Christ as he ought to do, and as God requireth of him.
Oh that ye could learn thus to know Christ, and thus to confess him!
For until ye thus know him, ye cannot thus confess him.
And your knees must first bow at his name, before your tongues can rightly confess him,
to the glory of God the Father!
For if ye will indeed glorify the Father, ye must bow to the Son,
who is the light wherein God dwells, in the shinings whereof he appears to,
and visits the sons of men.
And as the Son himself is spiritual; so is the light wherewith he visits dark man.
His law is spiritual, able to convert the soul of any man in whose heart it is written,
and to make wise (the most simple among men) unto salvation.
For the law of God, writ in the heart, is from the covenant of life;
and delivers and preserves from the law of sin and death, having the light, power,
and Spirit of Christ in and with it, from whom it comes.

Now if ye will know these things clearly, certainly, and infallibly;
wait to feel some touches, some drawings,
some convictions of God`'s Spirit upon your hearts.
And then dispute not against them; but immediately become subject,
so far as the light and drawings of the Father incline and lead the mind;
and then ye shall see what he is that draws, and of what nature his drawings are.
And if once ye come to feel the preciousness of his ointment; and to partake of it,
receiving it and following it, it will bring you into the pure virginity,
which loves and longs after the name that anoints with the pure living oil.

Friends, I was once where ye now are; and in that day,
I also (through error and mistake) called the light
wherewith Christ hath enlightened man,
natural, as ye now do.
But the Lord hath since showed me,
that it was not the true birth of life in me which so called it;
and it is also manifested to me in his Spirit of truth (which deceives not),
that it is not the true birth in you, which so judges of it.
Oh that ye were born of the Spirit,
and in it knew the names of the things from their nature,
and might be taught of the Father to worship the Son! which ye can never do,
till ye come into the Son`'s light; and that is the Son`'s light,
even that wherewith he hath enlightened men,
that they might believe in the Father through him.
The Scriptures (or any words spoken or written) are not the light itself,
but testimonies concerning the light.
Now that which ye are to come into, and to dwell and abide in, is the light itself;
which light was before any words that testify of it,
and is the substance of all the shadows,
and the end of all the testimonies concerning it.
He is Alpha and Omega, the Beginning and the End of the new creation of God.
Oh that ye so knew him!

That from which the Scriptures came, is the thing, the life, the Spirit,
the power itself; which is able to write inwardly, as well as outwardly.
And he that knows the thing,
and is led to the thing by the inward writing (which is the testimony of Jesus,
the Spirit of prophecy) he by the testimony of Jesus, by the Spirit of prophecy,
is led to the Holy Power; which he believing in,
it prevails to save him out of the contrary spirit and power.
And this the Gentiles without the law, the Jews under the law,
and the believers under grace,
had spiritually all one and the same way and path of life unto salvation;
and God will be clear and just in judging them all according thereunto,
who had all some manifestation of the gospel and power which saves,
according to the dispensation of the good pleasure of the free giver.
And men`'s perishing in the time of every dispensation,
is not for want of light and power from God,
but from men`'s withdrawing and apostatizing from the light and power,
which in every dispensation of life stretched forth
its hand and arm sufficiently to gather and save.

There is one thing more in my Heart unto You, at this Time, which is

=== CONCERNING APPLYING THE PROMISES

THE promises of God are great and precious,
and give to partake of the divine nature those that wait
upon the Lord in the faith and obedience of his truth.
Now there are estates and conditions to which they do belong;
and there are estates and conditions to which they do not belong:
and if any one apply any promise to himself,
he not being in that estate and condition to which that promise belongs,
he deceives his soul, and sucks not in the true sweetness and comfort of the promise,
but of his own imaginary apprehensions concerning the promise.

There is a state of wounding, of judging, of God`'s pleading with the soul,
because of sin and transgression.
Now he that breaks and wounds, he alone can bind up and heal;
and the Lord is to be waited upon in the way of his judgments,
until he see meet to bind up and heal.
Now the Lord heals by the same Spirit and power wherewith he wounds;
but it is hard to lie under the judgment, to bear the indignation of the Lord,
and so keep the wound (which he makes) open, till he pour in the oil, and heal.
For there is that near, which will be offering to heal before the season,
and will be bringing in promises, and applying promises,
otherwise than the Spirit of the Lord intendeth or applieth them.
Now this is diligently to be watched against,
that the hurt of the soul (judged and wounded by
the Spirit of the Lord) be not healed slightly,
and peace spoken to it (and an expectation and hope
raised in it) which is not of the Lord.
But this is the right way, even to give up to feel that which wounds,
and to receive the woundings of thy soul`'s friend,
and lie low before him in the wounded state,
waiting upon him in the way of his judgments and righteous indignation;
till the same that wounded, speak peace.
For the same is to speak peace, and not another; "`I the Lord wound, and I heal; I kill,
and I make alive.`" Judgment is mine, and mercy is mine; and they both issue from my lips.
(See Isa. 12:1). So every one, that would not be deceived about,
nor misapply the promises, wait to feel that in you,
which leads into the condition to which the promise belongs,
and to be led into and kept in the condition by it.
And then, the same that leads into the condition,
will apply the promise to him who is in the condition, the ear being open to him,
hearkening to the Lord, waiting what he will speak,
who speaks peace to his people in his seasons;
and having the ear shut against the voice of the
unrighteous troubler of the souls of God`'s heritage.
Yea, he that applieth the promises to the soul (having
brought it into the state to which they belong),
he also will lead and bring unto the fulfilling of the promises,
even to the receiving of the good things promised and waited for;
so that the soul shall witness the gospel to be a glorious state indeed; a state of life,
a state of liberty, a state of power, a state of dominion, a state of holiness,
a kingdom of righteousness and peace,
wherein there are everlasting mansions and dwelling-places in Christ Jesus,
for the seed of the righteous forevermore.

The Lord God of everlasting mercy, life, power, and rich goodness,
cause the light of his own Holy Spirit to shine into your hearts,
guide you thereby into and in the true way, even in the pure,
living path (which was and is but one forever) that ye may come into the true possession,
and full enjoyment, and infallible witnessing of these things.

23d of the Second month, 1668

=== There is another Query of great Concernment, which springeth up in my Heart towards you.

Query.
Is not the Spirit, or anointing, the great gospel promise, and the great gospel ordinance?
Is not he truth, and no lie, and the leader out of all lies and deceits into the truth,
and the preserver of the mind and spirit therein?
"`Little children,`" said the same apostle, who had directed to the anointing,
"`keep yourselves from idols.`" Is there any possibility
of being kept from images and idols but by him?
Can any understand the things of the Spirit,
or the words spoken by the Spirit concerning spiritual things, but by him?
And then, is not every apprehension,
that ye take up from the Scriptures concerning spiritual things,
which ye have not from him, but comprehend and gather of yourselves, an image,
or conceiving of your own, concerning that thing,
and not that true knowledge and understanding of the thing which he alone can give?
Oh that all the chambers of imagery were thrown down in you,
and every idol of the heart and mind discovered to you,
and broken down by the light and power of the Lord!
that ye might come to that which is pure and living,
and by its purifying know the pure heart, the pure mind, the pure conscience,
and offer up the pure, perfect offering; not the lame, blind, imperfect, etc.,
which were not accepted, in the figure, under the law, nor acceptable under the gospel.
Mal. 1:11,13, and chap.
3:3.

Friends, ye must know that which is pure from God,
and ye must come into it (out of that which is impure, into that which is pure).
Now that ye may do so, ye must know the purifying;
for nothing that is impure can enter into that which is pure.
Yea, ye must become priests to God, and wear the priest`'s garment, the pure garment,
the living garment, the fine linen, without mixture of the woollen.
Ye must be born of the innocency, be clothed with the innocency.
The stony, hard, desperately wicked heart must be taken away,
and the tender heart of flesh received, the mind renewed to God,
the fear put within (which cleanseth and keepeth clean), the law written within,
the Spirit of the Lord put in the inward parts,
and felt powerfully operating and changing there.
Yea, and the inside must not only be clean, but the outside also;
for ye must be clothed with the Spirit,
clothed with the Lamb`'s righteousness and holiness;
and thus ye must appear before the Lord in his temple, which is the beauty of holiness,
whose house holiness becomes forever;
where ye are never to appear in your own filthy rags, but in the nature, Spirit,
righteousness, and life of Christ.
And thus ye are well pleasing to God, even in that which is of God; being born of that,
formed of that, found in that, appearing in that.
But in his own, no man can be accepted; for it is determined of God,
and stands irreversible forever, that in his own (in his own knowledge,
in his own faith, in his own obedience, in his own righteousness,
in his own willing and running, etc.) shall no flesh forever be justified in his sight;
but only and alone in the nature, Spirit, life, righteousness, faith, obedience,
and holiness of his Son.
Therefore wait for the seed, that ye may know the seed, feel the seed,
the pure seed of life (the leaven of the heavenly kingdom),
and may witness it arising and come in you to do the will,
and you in it quickened and enabled to live to and serve the living God.
And when ye know this seed, ye know Christ; and when ye receive this seed,
ye receive Christ; and if it live in you, Christ lives in you; and in it (being in it,
and abiding in it) are ye heirs of the life, kingdom, and power, which hath no end;
and shall daily feel the promises and blessings belonging to the seed,
flowing in upon your spirits.
But if ye content yourselves with the knowledge of Christ which the erring and apostatized
spirit of man from the life and power may gather out of the letter of the Scriptures,
and feed thereon; that will not nourish you up to eternal life, but death and sin,
and the gates of hell will have power over you notwithstanding that; but if ye,
through the Spirit, receive power over that which is contrary to God,
and through him mortify the deeds of the body, ye shall live.
Therefore wait for the manifestation of the pure power of the endless life,
which is now dispensed from on high (blessed be the name of the living one!),
and wait to know and be joined to that seed of life, wherein and whereby it is dispensed,
that ye may witness Christ`'s kingdom come to you,
and the reign of your spirits with him therein, over all that captivateth from him,
loadeth the soul, boweth down and oppresseth.

[.old-style]
=== A Postscript / Concerning Deceit and being Deceived

THERE is that which deceives (where it is hearkened to),
and there is that which is liable to be deceived by it.
There is likewise that which deceiveth not;
and there is also that which cannot be deceived.
So likewise there is a pure fear and watching in the truth against the deceit,
lest by any means it should enter and betray.
As also there is a fear that is a snare (which the true faith preserves
out of) whereby many are entangled in the very bowels of deceit,
even concerning those very things about which they are afraid they should be deceived.
This hath been experienced by those,
who have been acquainted with the Lord`'s precious truth,
and thereby are come to know and discern the wiles and devices of Satan;
who often hath quenched what the Lord hath kindled, by his stirring up a fear,
lest it should not be of the Lord, but from the spirit of deceit.

It is true, that in the apostasy from the life and Spirit of truth,
deceit did generally prevail and overwhelm the minds of people.
And so far as people are yet in the apostasy (not being gathered and redeemed out of it,
by the Spirit and power of the Lord), they are yet under deceit;
though perhaps they little think so.
Little did we think formerly (and little do they think now,
who are now in that state we were then in), that while we so much feared being deceived,
we were already deceived, being short of the life and power of truth,
which alone is able to make free and preserve from deceit.
When the Lord cometh to bring to the primitive light and principle,
that he might perfectly deliver out of deceit;
what can the enemy do more advantageously towards keeping his hold in the mind,
and towards keeping the mind in the deceits wherein he hath already entangled it,
than to stir up and heighten a fear in it, lest the precious truth,
which God maketh manifest to deliver the soul by, should be deceit?
And they that hearken to, and let in, the voice of the deceiver,
must needs believe it to be so.
And thus with them light cometh to be called darkness, and darkness light.
Yea, who is it, at this day, who escapeth this snare, of calling evil good, and good evil?
Surely none but he, whose soul is led into and lives in the light and power of truth.

For most men take up principles,
according to their own or other men`'s understanding of the Scriptures,
and judge according to those principles;
and so the Spirit and light of the Lord judgeth not in them,
but they themselves judge according to an assumed knowledge.
So that flesh is not silent, the man is not dead in them and brought to nothing,
but only lives in a higher region than he did before.
Before, he lived in an apparent unrighteousness;
now he lives in an imagined righteousness and faith; but not in the Son`'s righteousness,
not in the Son`'s faith, not in the Son`'s power, not in the Son`'s dominion;
but at best only in that which he apprehendeth and strongly imagineth to be so.

Oh! happy is he,
who is come through all his own imaginings and conceivings about the things of God,
and his own apprehensions about scriptures and promises,
and is come into the thing itself,
into the Spirit of life (into the truth and into the power),
and who walks with God therein, daily witnessing the redemption which is of him,
through his Son Jesus Christ, who is known and partook of in the pure, quickening Spirit,
and not otherwise.
And he that is truly begotten of God, and dwells with him in the light which is eternal,
knows that he is of God; which others may strongly imagine they are,
but none else can truly know it,
but may easily err and be entangled in the deceits of the enemy about the new birth,
and other weighty things, while they are greatly afraid of being deceived by him, and so,
through that fear, fly the pure truth, which frees from deceits,
lest it should deceive them.
