[#muggleton, short="Observations on Passages of Lodowick Muggleton"]
== Observations on Some Passages of Lodowick Muggleton

[.heading-continuation-blurb]
In his Interpretation of the 11th Chapter of the _Revelations._

[.heading-continuation-blurb]
As also on some Passages in that Book of his, styled,
[.book-title]#The Neck of the Quakers Broken#
and in his [.book-title]#Letter to Thomas Taylor.#

[.heading-continuation-blurb]
Whereby it may appear what spirit he is of and what god his Commission is from.

[.heading-continuation-blurb]
Whereunto is added A brief Account of my Soul`'s Travel towards the Holy Land,
with a few words concerning the Way of knowing and receiving the Truth.

[.heading-continuation-blurb]
Written in tender love to Souls,
in true sense and understanding received from the Lord,
and with reverence to his holy Spirit and Power.

[.section-author]
By Isaac Penington

[.section-date]
1668

=== The Preface to the Reader

Having had a book of Lodowick Muggleton`'s sent me to peruse,
and having been earnestly pressed thereunto by some,
who had let in his spirit and doctrines, to their great hurt: in the fear of the Lord,
and in the sense of his holy Spirit of Truth,
and in tender love to them who had requested this of me, I cast my eye thereupon;
wherein I observed very many things contrary to the Spirit of the Lord,
the Testimony of the holy Scriptures, and the nature of Truth;
some whereof (for the service of others) are here communicated.
To which, there arose somewhat in my heart to add concerning myself,
in reference to my wearisome seekings, journeys and travels after the Lord.
Indeed it came upon me very freshly and livingly:
and the Lord may please to make it useful to others,
even to help to stay the minds and quicken the hopes of such that are fainting,
as I deeply was.
Now if so be any shall reap any benefit thereby, let them give glory to the Lord alone,
who alone is worthy thereof.
For I seek not esteem of men; but all my desire is,
that men might know the Lord and the Power of his Truth,
and by him be gathered into and preserved in that which is pure of him.
It is the day of the Gospel, even of God`'s eternal power, which is risen in many hearts:
for indeed the Light of the Everlasting Day of God shines gloriously,
and doth conquer and shall conquer the darkness and
corruption in men`'s minds daily more and more.
O that more might partake of its virtue, and not stumble at that stumbling Stone,
which the builders out of the Life and Power, in every age and generation,
have still despised and rejected.
O that men might seek after Christ, the Wisdom of God aright:
not in that spirit and wisdom which shall never find him.
For it is easy to seek amiss, but none can seek aright,
save only those that are led and taught of God so to do.

=== Observations on some passages of Lodowick Muggleton, in his Interpretation of the 11th Chapter of the Revelations

IN page 9, he saith, "`The law is not written in the seed of faith`'s nature at all,
but in the seed of reason`'s nature only.`" (Reason, or the spirit of reason, he saith,
is the devil, p. 15.)

Observation.
The sum of the law is love: even to love God above all, and one`'s neighbour as oneself.
And this love, which is the sum of the law, and fulfils the law,
God writeth in the hearts of his spiritual Seed.

In p. 15 he affirmeth that that "`saying of the devil was true`" which he said to Christ,
"`All the kingdoms of the earth are mine.`"

Observation.
The earth is the Lord`'s, and the fulness thereof.
The devil hath no right to it.
God never gave it him: but God himself is Judge,
who throweth down one and setteth up another,
disposing of the kingdoms of men according to his pleasure. Ps. 75:7.
Dan. 4:25.

In p. 19 he saith,
"`There never was no enmity between the person of the serpent and the person of the woman:
but the enmity which lay between them was in the two seeds.`"

Observation.
Is not the enemy as expressly placed by God between the serpent and the woman,
as between their seeds?
"`I will put enmity between thee and the woman,
and between thy seed and her seed.`" Gen. 3:15.

In p. 21 he saith,
"`So that now God himself is not capable to dissolve himself into Seed or Nature,
as he was before.`"

Observation.
Is God changeable?
Is he one thing today, and another thing tomorrow?
and can he never be any more what he was yesterday?
His god may be so: but the true God is not so ("`I the Lord change not.`"): his Nature,
his Seed, his Life, his Spirit, his Power is the same forever.

Further in p. 21, he saith,
"`These two seeds were those two spiritual bodies
which are called by the revelation of Moses two trees.
Yet they were in the forms of men, and was capable, as they were spiritual bodies,
to dissolve into seed or nature, and so become capable to suffer the pains of death.`"

Observation.
O the depth of imagination from that Spirit,
which giveth imaginations to them that will receive them!
He that is taught of God never learned thus, but learneth much otherwise;
and in the feeling sense and experience knoweth the two Seeds,
and is born of the one and separated from the other from the very womb, I mean,
from his birth of the Jerusalem which is above,
which is free (from the spirit of deceit and all its imaginary
knowledge) which is the Mother of all that are born of the Spirit.

In p. 22 he saith, "`Knowledge proceedeth from life that hath wisdom in it.`"

Observation.
Living knowledge doth.
But there is a knowledge which comes not from the true Wisdom;
nor doth convey life but death.
And such is the knowledge which he hath from his god, and holdeth forth to others:
it poisons and corrupts the mind,
and leads out of the capacity of receiving and obeying the Truth, as it is in Jesus.

In p. 27 he saith, "`Reason can feed on nothing but what it can see with this visible eye.`"

Observation.
That is not reason`'s food only, which is seen with this visible eye:
but reason is in the mind,
and feeds chiefly on things which the mind gathers and comprehends inwardly.

In p. 29 he saith, "`I declare, by revelation from the holy Spirit,
that out of these two spiritual trees came forth these two commissions, namely,
the commission of Moses and the prophets, and the commission of Jesus and the apostles.`"

Observation.
He had said before, p. 11,
that one of these trees was the tree of knowledge of good
and evil ("`in the form of a man,`" p. 14) that tempted Adam.
Was that which tempted Adam, the tree out of which Moses`' commission came?
Doth not he call this tree the serpent?
(p. 30). Had Moses his commission from the serpent?
Surely everyone that is of God will say, no.

In p. 30 he saith, "`These two olive-trees and candlesticks here spoken of,
I declare are those two commissions which came forth of these two spiritual trees.`"

Observation.
One of these trees he said "`was the very person of God himself,`" p. 10.
That the other was the tree "`that tempted Adam`":
whereas the Tree did not tempt Adam,
but the serpent tempted Eve to eat of the fruit of the tree.

Again p. 30 he saith, "`Moses acted as a God in the person of the angel,
or tree of knowledge of good and evil.`"

Observation.
Moses was faithful in all his house as a servant.
Nor did he act in the person of the serpent; for the serpent was the devil,
and was out of Truth long before Moses`' time, and spake of his own:
but Moses spake and ministered from the pure holy Spirit of Life.
Was not the devil defiled, a corrupt tree, an angel fallen from his habitation,
before he tempted Eve and Adam to sin and fall?
And who can bring a clean thing out of an unclean?
or an holy commission out of the devil?

In p. 31 he saith, "`The law`" +++[+++speaking of Moses`' law]
which is "`just and good,`" "`doth enlighten reason to do as he is done unto,
not as he would be done unto.`"

Observation.
If Christ may be believed, he saith otherwise: for he saith,
All things whatsoever ye would that men should do to you, do ye even so to them:
for this is the law and the prophets, Matt. 7:12.
So that the law and the prophets did teach and require this,
not only for a man to do as he is done unto, but as he would be done to.

In p. 32 he saith, "`The law of reason...is called a law of sin and death,
it being given unto reason, because reason is sin;
for there is nothing doth break the law but reason.`"

Observation.
Those that are delivered by the powerful appearance
of Christ from the law of sin and death,
knows it to be another law than the law of reason,
even a law contrary not only to the Life of Christ,
but to the reason and understanding of a man, bringing him below the state of reason,
even into brutish captivity and sensuality.
Doth reason teach a man to manage his body destructively and unreasonably,
as the corrupt and unreasonable law of sin and death teacheth many men?
Reason is not sin: but a deviating from that from which reason came, is sin.
God did not create man in sin; or make a sinful creature: but he gave him reason,
and thereby made him reasonable.

In. p. 34 he saith, "`The moon +++[+++Rev. 12]
did signify the law of Moses,
which must now be trod underfoot by the sun-shine light of the gospel.`"

Observation.
No not so: the law is not trod underfoot by the light and power of life,
when it appeareth;
but its righteousness is fulfilled in them that walk not after the flesh,
but after the Spirit, Rom. 8:4.
Christ did not teach men to tread Moses and his law underfoot;
but brings forth that life and bestows that Spirit,
which leads through and beyond the law, even to the righteousness of faith,
which (the apostle Paul said) they did not make the law void by, Rom. 3:31.
Therefore not trod underfoot through faith in the gospel.

In p. 37 he saith,
"`There was none of the prophets that were commissionated to write scripture.`"

Observation.
They spake and wrote as they were moved by the holy Spirit,
and is not that a sufficient commission?
In his book called The neck of the Quakers broken,
he had scoffingly cast away the writings of Solomon from being scripture;
and now he casts away the writings of all the prophets too,
as being written without commission.

In p. 42 he argueth against God`'s being an "`infinite, incomprehensible`" Spirit, saying,
"`Such a great vast Spirit do not know itself,
neither can this vast Spirit tell where to find or see itself;
and if it cannot know or see itself,
how should his creature be able to know or see his Maker,
when as he cannot know or see himself? &hellip;Then would
that be a vain thing which is spoken of in holy writ,
where it is said, '`It is life eternal to know the true God`'.`"

Observation.
Here is dark imaginations indeed.
He that cannot read in the Spirit, let him read that place, Isa. 40:12.
according to the plainness of the letter,
and see if God can be less than infinite and incomprehensible.
He that knoweth the nature and Spirit of God, knoweth God,
though he be not able to measure or discern the utmost extent of his being,
which who can?
For he is a sea of life, a sea of love, a sea of purity and righteousness,
a sea of power and wisdom, etc. but in a measure of the same life, received from him,
we know him so to be; and worship him in the Spirit and life which is of him;
not making likenesses of him in our minds,
but bowing to him and worshipping him in his own appearances.

In p. 77 he saith, "`The holy Ghost sat upon none,
'`like as of fire,`' but upon the twelve apostles only;
neither could any other speak with tongues by inspiration, but the twelve apostles.`"

Observation.
This is directly contrary to the testimony held forth in scripture.
For, said Peter, the holy Ghost fell on them, as on us at the beginning, Acts 11:15.
And they of the circumcision which believed, were astonished,
because that on the Gentiles also was poured out the gift of the holy Ghost.
For they heard them speak with tongues and magnify God, chap.
10:45-46.

In p. 52 he saith, Christ`'s "`apostles could do no miracles,
neither could they cast out devils, until he was ascended.`"

Observation.
Did they not cast out devils and do miracles, while he was on earth?
Did not he give them power so to do?
See Matt. 10:8.

In pp.
59 and 60 he speaking of the wild olive-tree, and the good olive-tree.
"`That wild olive-tree,`" he saith, "`is the state of nature or reason, the devil,
which is wild by nature.`" "`That good olive-tree,`" he saith,
"`was the very person of Christ,`" "`which the Gentiles were ingrafted into
by faith.`" But "`the commission of Moses and the prophets proceed+++[+++ed]
from the tree of knowledge of good and evil,
he acting his part in that seed,`" etc. which he afore said was the serpent.

Observation.
Is the wild olive-tree (the devil which is wild by nature) one of God`'s witnesses,
or the head or root from whence any of the commissions of God`'s Spirit came?
Did the law of God, which was against sin and the devil, come from the devil?
Is not the law holy, just and good?
and did it come from an unholy root?
What was the olive-tree the Jews were broken off from?
Read their state, Rom. 9:4-5.
and 11:16-17. Was this holy Root they were broken from a wild olive-tree?
What interpretation of Scripture is here?
Surely from a spirit quite contrary to that which wrote it.

In p. 63 he saith that the "`great and high wall +++[+++about the new Jerusalem]
was all that visible and external worship which was set up by Moses,
which did belong to that tabernacle,`" etc.

Observation.
Is this the defence about the glory of the new Jerusalem?
is this the wall and bulwark?
Nay, nay: the power of God`'s salvation is the wall and bulwark, Isa. 20:1.
which is a sure defence upon all the glory of this building. Isa. 4:5.

In p. 66 he saith,
"`The &hellip; apostles &hellip; should be equal in the kingdom of glory, &hellip; as
they were equal here in the kingdom of grace.`"
And again, p. 67. "`As there should be no preeminence with the &hellip; apostles
here in the kingdom of grace,
neither should there be any preeminence in the kingdom of glory.`"
Yet p. 102. he saith that Peter was "`the head of the apostles.`"

Observation.
Hath the head no preeminence in the body?
Are the rest of the members equal with the head?
is not this an absolute contradiction?

In p.78 he saith, "`The commission of the apostles &hellip; was not the commission of the Spirit.`"

Observation.
Paul saith, they were made able ministers of the new testament, not of the letter,
but of the Spirit, 2 Cor. 3:6. What is to be desired more than the new covenant?
wherein life, Spirit and power is received.
Now the apostles were made by God able ministers thereof:
and the glory of this covenant and ministration remaineth, verse 11.

In p. 93 he saith, "`Death being the first-born of the law,
it went forth as a conqueror of all life, both in God and man.`"

Observation.
The law is holy, just and good, and bringeth forth only that which is holy.
Sin is not of the law, but against the law, and the wages of sin is death.
Yet neither sin nor death could ever conquer the life of God,
but the unconquerable life and power have ever reigned over them.
God`'s kingdom is an everlasting kingdom, and his dominion endureth throughout all ages,
which sin, nor death, nor hell could ever conquer.
That life which Christ did give up, none took from him as a conqueror,
but he laid it down freely, at the requiring of the Father,
knowing his glorious power was able to restore and raise it up again.

In p. 105 he saith, "`The body of man is that Tophet that was ordained of old,
and the spirit of reason is that king, which must abide in this Tophet.`"

Observation.
The body of man was God`'s temple before it was defiled with sin;
and is God`'s temple again, when it is purified and purged from sin.
Now him that defileth this temple of God, him will God destroy.
And Christ said, Fear him who after he hath killed, hath power to cast into Hell, Luke 12:5.
What is he able to cast into Hell?
why, both body and soul, Matt. 10:28. Then the body of man is not the Tophet or Hell:
but Tophet is that whereinto the souls and bodies of the wicked are to be cast.

In p. 116 he saith, "`Eternity did become time, and time shall become eternity again.`"

Observation.
Eternity did never become time, but is unchangeable in its nature, spirit,
life and being forevermore: but it brought forth natural and changeable things in time,
which time shall have an end.

=== Observations on some Passages in a Book of Lodowick Muggleton`'s, styled by him, The Neck of the Quakers Broken

In p. 14 he affirmeth that "`Adam had no part in the begetting`" of Cain.

Observation.
The Scripture saith, Adam knew Eve his wife; and she conceived and bare Cain, and said,
I have gotten a man from the Lord, Gen. 4:1.
Here the holy Spirit of God attributeth the
begetting of Cain to Adam`'s knowing his wife Eve;
but L.M. saith otherwise.

In p. 15 he saith, "`Whoever is partaker of the seed of Adam,
may be said to have the Spirit of Christ in them, and their spirits to be in him,
that is, Christ dwells in their hearts by faith.`"

Observation.
The Scriptures distinguish between the first and second Adam.
None have the Spirit of Christ from or in the first Adam, but only from and in the second.
And the old Adam`'s seed, spirit and nature is to be put off by him that puts on the new;
and he must be born again of the immortal seed of life, who receives the Spirit of life.

In p. 17 he calls reason the devil, and p. 29 saith,
"`This devil so much spoken of in Scripture, is no other but the spirit of reason.`"

Observation.
Indeed corrupted reason is of the devil: but pure reason is of God.
Man, by his fall, had his reason corrupted, and so became brutish and unreasonable:
but by faith in the redeeming power he is brought out of the fall,
raised from death to life, and in the new life hath the true, holy,
righteous reason restored to him again, 2 Thess. 3:2.
which reason is neither the devil, nor of the devil.

In p. 22 he saith, "`If God be a person in the form of a man,
as I am sure he is (for I do acknowledge no other God but the man Christ Jesus,
who is a distinct body of flesh and bone of his own,)
how then can he fill heaven and earth with his presence,
and get into the Quakers`' bodies,`" etc.

Observation.
Solomon said in prayer to God, 2 Chron. 6:18.
(which prayer God testified his acceptance of,
as being from his own spirit, chap.
7:1) Behold heaven, and the heaven of heavens cannot contain thee,
how much less this house which I have built?
Again,
Thus saith the high and lofty one that inhabiteth
eternity (what is eternity?) whose name is holy,
I dwell in the high and holy,
with him also that is of a contrite and humble spirit etc. Isa. 57:15.
Yet again it is said, Ye are the temple of the living God,
as God hath said, I will dwell in them and walk in them. 2 Cor. 6:16.
Is it such a strange thing that
God should be in heaven and in earth also?
Is not the earth his footstool?
and are not the feet present in the place on which they tread?
Was not Christ in heaven while he was here on earth, according to his own words?
No man (saith he) hath ascended up to heaven, but he that came down from heaven,
the Son of Man which is in heaven, John 3:13.
And cannot God be in heaven and in earth too,
and also by his Spirit in the hearts of his people?

In p. 23 he saith, to "`say that &hellip; Christ,
according to the flesh &hellip; was of Abraham &hellip; is blasphemy.`"

Observation. The apostle said concerning the Jews
(whom he calls his brethren and kinsmen according to the flesh, Rom. 9:3),
of whom as concerning the flesh Christ came, who is over all, God blessed forever, amen, verse 5.
Did Christ come of the Jews according to the flesh,
and did he not come of Abraham according to the flesh?
Now lest any should apprehend there may be some difference between according in verse 3,
and concerning in verse 5, I shall add this, they are both the same in Greek.
// lint-disable invalid-characters
It is κατα σάρκα in both.

In pp.
24-25 he saith, "`None can interpret Scripture truly, but my self.`"

Observation.
All that are children, to them God giveth of his Spirit:
(Gal. 4:6) and they that have the Spirit,
have that which interprets Scriptures truly; which they keeping to,
cannot be deceived about the interpretation of them.
But they that keep not to the anointing within,
but receive interpretations from men without, may easily be deceived.

In p. 25 he saith, "`God hath made me the judge of Scriptures.`"

Observation.
Let him that readeth, wait to feel the Spirit which is of God,
and the Light wherein God dwells,
and that will open Scriptures and the mysteries of
the kingdom to him (he abiding in unity therewith,
through the pure subjection thereto) and manifest to him
who is the judge in spiritual matters in God`'s Israel.

Again p. 25 he saith further, "`We the Witnesses of the Spirit do know more than Moses,
the prophets, or apostles did, things of more higher concernment.`"

Observation.
The apostles were not the least in the kingdom,
but in the glory of the day (1 Pet. 2:5) in the eternal life,
in him that was true (1 John 5:20) and they had the whole counsel of God,
even a ministry sufficient to perfect the work of God in the saints (Eph.
4:12) that so they might present men perfect in Christ Jesus, Col. 1:28.
And happy is he that receiveth their testimony,
and cometh into and walketh in that light which their message was concerning, 1 John 1:2.
and verses 5 and 7.

Yet again, p. 25 he saith,
the "`Quakers...have nothing but the dead letter of other men`'s words,
whose light was but dark in comparison of that light
that comes by this commission of the Spirit.`"

Observation.
Yes, they have much more than the dead letter of other men`'s words;
for they witness the living Spirit, and are taught thereby and subject thereto,
blessed be the Lord, who is become the Shepherd and Teacher of his people himself,
according to his promise.

And as for the apostles`' "`light being dark in comparison,`" etc.

Observation.
We all with open face, beholding as in a glass the glory of the Lord,
are changed into the same image, from glory to glory, even of the Lord the Spirit, 2 Cor. 3:18.
Again, God who commanded the light to shine out of darkness,
hath shined in our hearts to give the light of the knowledge of the glory of God,
in the face of Jesus Christ, chap.
4:6. In that day the woman was clothed with the sun
(for as many as are truly baptised into Christ,
have put on Christ, Gal. 3:27) had the Moon under her feet,
and was crowned with a crown of twelve stars, and not only travelling to bring forth,
but brought forth the Man-child which was to rule all nations.
They who are indeed in the Spirit, know that the Light which is now broke forth,
is but the Light of the same Day which shined then very gloriously in them,
who were the glory of Christ, 2 Cor. 8:23.
They had the Spirit of God plentifully poured upon them,
which opened to them the mysteries of the kingdom and the deep things of God, 1 Cor. 2:9-10.
And how highly soever he think or speak of himself,
yet this is known concerning him, that he hath a very great journey to travel,
before he can come to that measure of light that they were in,
or to receive that proportion of the true Spirit that they received:
For he is yet quite out of it.

In p. 29 he affirmeth, "`that it was the very God-head life that suffered death.`"

Observation.
If the God-head life suffered death, what power was left to raise it up again?
I am the resurrection and the life, said Christ;
but he spake concerning that which raised Lazarus,
which was of an immortal nature and could not die: not concerning the body;
but the life and power of the Father, which dwelt in and was revealed through the body;
which died not with the body, but remained alive to raise the body.
What kind of doctrine is this, that the very God-head life suffered death,
and so to make the Creator mortal like the creature?

In p. 39 he saith, "`God the king of heaven is not in this world at all.`"

Observation.
Whither shall I go from thy Spirit?
or whither shall I flee from thy presence?
said David (who had the Spirit of God).
If I ascend up into heaven, thou art there: if I make my bed in hell, thou art there, etc.
Ps. 139:7-8. And do not I fill heaven and earth saith the Lord, Jer. 23:24.
But L.M. hath affirmed contrary to these testimonies,
that God is not in this world at all.

In p. 48 he saith,
"`I am the only and alone judge what shall become of men and women after death;
neither shall those that are damned by me, see any other God or judge but me,
or that sentence which I have passed upon them.`"

Observation.
Is he God?
is he Christ?
is he the only one?
is there not another God another judge?
(Yes we know there is another, who judgeth otherwise than he hath judged:
who judgeth that to death which he judgeth to life,
and that to life which he judgeth to death.) And
in the resurrection of the just and the unjust,
shall not both the just and unjust see him who is the judge?
Read Matt. 25:31, etc.

Again, p. 48 he saith, "`No man upon the earth can,
or ought to judge of the doctrine of a prophet, that hath a commission from God.`"

Observation.
Cannot he judge, who hath the anointing?
Doth not he that is a child of God receive his Spirit?
and is not the Spirit of God able to judge in them that receive it?
Judge not according to the appearance, (saith Christ) but judge righteous judgment, John 7:24.
Did Christ absolutely forbid men from judging concerning him,
or his doctrine and miracles,
or did he not rather direct them how they might judge aright?
I speak as to wise men, judge ye what I say, 1 Cor. 10:15.
The apostle had a commission from God,
and yet he did not bar men from judging of his words, but bid them judge:
and the same apostle saith, Let the prophets speak two or three,
and let the others judge, 1 Cor. 14:29.
Is the Spirit of God given to and received of the believer,
and shall he not therewith judge concerning spirits and
doctrines and commissions which pretend to be of him,
and apostles and angels, whether they be angels of light indeed,
or only such as would so appear?
Believe not every spirit, but try the spirits whether they are of God, 1 John 4:1.
And they which are of God,
love to come to the light which tries and makes manifest;
but they that are not of God refuse to be tried by it.
Thou hast tried them that say they are apostles and are not, and hast found them liars, Rev. 2:2.
God giveth that light, that Spirit,
that anointing to his which hath in it ability to try,
and they ought to try therewith doctrines, spirits, prophets, apostles,
and certainly find thereby that they are of him before they receive them,
or else they may easily be deceived? Despise not prophesyings, saith the apostle, 1 Thess. 5:20.
but yet withal though a man may not despise them,
yet neither may he receive them without due trial:
therefore the apostle in the next words adds,
Prove all things, hold fast that which is good, verse 21.

Further p. 48 he saith,
"`Who do you blind Quakers think should be judge of
a prophet that hath a commission from God?`"

Observation.
What saith the apostle? 1 Cor. 2:10.
The Spirit searcheth all things, yea the deep things of God. And again verse 15.
The spiritual man discerneth (or judgeth) all things,
yet he himself is discerned of no man.

Yet again p. 48 he saith, "`Is not a true prophet the law-giver,
and ought not every one to submit unto his laws?`"

Observation.
There is but one law-giver, but one king, but one Lord, but one Master.
All prophets and ministers from him, are but his messengers and servants, not law-givers.
The law cometh forth from the king himself,
from the great prophet and shepherd of the soul, to every lamb and sheep in the covenant,
as it is written,
All thy children shall be taught of the Lord (and I will write
my law in their hearts) and so taught by this prophet (in the new
and living covenant) as that they shall need no other teacher.
This was once fulfilled before the apostacy (as is faithfully testified, 1 John 2:27.
The anointing which ye have received of him, abideth in you;
and ye need not that any man teach you,
but as the same anointing teacheth you of all things
etc.) and it is again fulfilled after it,
blessed be the name of the holy one of Israel.

But mind, reader, what is the reason that he reviles us above all others,
calling us blind, and the darkest pieces to interpret Scriptures,
and the cursedst of all sects, and the like; but because we stand most in his way,
because we cannot receive him as a law-giver, because we have received the true light,
the true Spirit and anointing from God,
which discovereth and denieth him in his very root and ground.

In p. 50 he makes himself the judge,
and the day of judgement but a day of general execution, wherein Christ shall say,
Come you blessed and go you cursed.
He saith "`there shall be no more pleading with God,
but this will be all that God will say in the resurrection,
Come you blessed and go you cursed.`"

Observation.
Yes, there will be more said.
There will be the reason given publicly why men are blessed or cursed,
as was testified by Christ himself, while he was here on earth, Matt. 25:35, etc.
And men shall have liberty to plead as is there expressed, verse 44.
So that Christ,
the great judge, is not so bound up, as he would bind him up: nor are persons,
to be judged by him,
absolutely bound up from considering of their sentence and pleading their cause with him;
but if they have any thing to say on their own behalfs, they shall be equally heard.

In p. 60 he saith,
"`God doth not come down from heaven upon this earth to interpret the scriptures to men,
but this was always God`'s practice to commissionate particular men,
and furnish them with gifts for that purpose,
and what interpretations of scriptures they give,
it is owned of God as if he had done it himself.`"

Observation. The apostle saith, Every man is to stand or fall to his own master,
and bids every man be fully persuaded or assured in his own mind, and affirms,
that whatsoever is not of faith is sin, Rom. 14:4-5.
and verse 23. Nor did Christ deal thus, with his disciples,
requiring them to receive whatever interpretation of Scripture he would give them,
but he opened their understanding that they might understand the Scripture themselves,
and saith the Spirit of Truth should lead them into all truth.
Nor did the apostles thus deal with men,
but they waited for God`'s opening of the true capacity in others,
and were not lords over men`'s faith,
but demonstrators of the truth of God to men`'s consciences by his Spirit,
and as in his sight.

Again he saith, "`Christ doth not teach every particular man neither by his Spirit,
nor by voice of words.`"

Observation.
Every man that is truly begotten and new-born to God, is born of his Spirit,
John 3. (There is not another begetter and bringer forth
of life in the heart.) And the Spirit of the Lord,
in the new covenant, teacheth all its children.
It was written so of old, All thy children shall be taught of God.
How taught?
Why, they shall hear and learn of the Father, John 6:45. Thus the Scriptures speak:
and thus it is witnessed, felt and known in the heart, blessed be the name of the Lord.
For the children of the Lord are anointed with the holy anointing,
with the oil of the same Spirit (the same oil of gladness, Ps. 45:7.
and Heb. 2:11) wherewith Christ was anointed;
which maketh them also of quick understanding in the fear of the Lord,
and of deep insight into the mysteries of his kingdom, as they grow up in his life,
and sweet innocent holy nature.

Yet again in that page he saith, "`The true and right interpretation of the Scriptures,
it lieth in those men that God hath chosen, anointed and sealed for that purpose,
and men cannot come to the knowledge of God, nor the true meaning of the Scriptures,
no other way.`"

Observation.
The gospel is a ministration of the Spirit and power of the endless life:
and it consists not in receiving words,
but in receiving the Spirit from which the good words and precious knowledge comes.
And he that receives the Spirit and hath the Spirit,
receiveth and hath that which openeth and giveth entrance,
not only into words concerning the kingdom, but into the kingdom itself.
And the apostle who had a true commission from God,
was not sent to limit men to his interpretation of Scriptures;
but to turn men to the Light and to the power which
gives to see the Scriptures and spiritual things, Acts 26:18.
And the church of Laodicea was counselled not only to buy gold and raiment,
but also eye-salve of Christ, that therewith they might be enabled to see, Rev. 3:18.
They had words from those that were sent by God,
and much knowledge (insomuch as they seemed to themselves
to be rich and full) but yet they wanted the eye-salve,
which they were to buy themselves: for no man is to offer any thing, but at his own cost.

Yet again in p. 60 he saith the opening of the Scriptures
"`belongs unto commissionated men,
and not unto Christ himself.`"

Observation.
In the New Covenant God himself is the shepherd, the King, the prophet, the teacher.
(This is not known only from words left upon record by holy men of God;
but also inwardly felt and witnessed.) The eternal Word is nigh;
nigher than words from commissionated men; and teacheth more inwardly and fully,
than words from men can.
The same God who creates the heart anew, puts his law into the mind and heart,
yea his Spirit within.
Now to this the gospel ministers formerly did (and still do) direct and turn men;
but did not limit them to words from themselves,
or to their interpretations of Scriptures, as was said before.
And as under the law men were to hear Moses:
so under the gospel men are to hear Christ in all things;
and he that doth not hear him is to be cut off, as Acts 7:37.

In p. 62 he saith,
"`Though the prophets and apostles were anointed and sealed of God for that great work,
will it follow therefore that you Quakers, because you read their writings,
that you are anointed and sealed of God for the work of the ministry?`"

Observation.
Where was this ever affirmed by them?
But this they certainly know and faithfully testify,
that they have received the very same Spirit in measure
which the prophets and the apostles had,
and minister in its name and authority and demonstration,
and have the true and living seal of their ministry in many hearts.

In p. 17 he saith, "`As for my mouth being full of cursing,
that is my commission.`" And p. 18. "`God hath ordained me the chief
judge in the world at this day to give sentence upon men and women`'s
spiritual and eternal state what will become of them after death.
Full of this cursing I confess my mouth is, and I do rejoice in it too,`" etc.

Observation.
When Christ pronounced judgment upon Jerusalem, he did it weeping, Matt. 23:37-38.
and Luke 19:41, etc.
And the true apostle knew that those that watched for the soul,
when they gave up the account concerning such as did not submit to and obey the Truth,
but rebelled against it and perished, they could not do it with joy, but with grief, Heb. 13:17.

In p. 69 he teacheth his disciples to curse men to eternity,
"`despising spirits`" he calls them, such he means as do not own his commission,
but know it not to be of God, and faithfully testify against it.

Observation.
Christ taught his disciples to bless, saying to them, Bless them that curse you, Matt. 5:44.
And the apostles said, Bless and curse not, Rom. 12:14.
And Christ is the same at this day, and teacheth his Disciples so now.
Yea I and many others can faithfully witness it,
that since we felt the seed of blessing in our hearts,
we never learned of it to curse any man,
but rather to pity them and pray to the Lord for them, and direct them to the holy light,
Spirit and power,
whereby they might be turned from their iniquities and come into the blessing,
as Acts 3:26. And though he pretends that those whom he curses,
have sinned the sin against the Holy Ghost, and are devils;
yet that is but the judgment of his spirit, not of God`'s Spirit:
for they are in that which keeps from grieving God`'s Spirit;
much more from sinning the great and unpardonable sin against it.

In p. 63 he saith, "`Neither do I curse any until he judge me first.`"

Observation.
Feel, ye that have true sense and understanding, what moves him to curse.

In p. 73 he saith, "`If the witness that informed me did not witness truth,
then the sentence which I have passed upon them shall be of no value.`"

Observation.
How often hath he affirmed his judgment to be infallible,
and such as God himself could not reverse?
But here, it seems, it is such as may be passed by hearsay,
and depend upon the witnesses`' words:
so that if the witness that informed him spake truth, it shall stand;
but if the witness did not speak truth,
then the sentence which he hath passed shall be of no value.
What, shall a man be commissionated and receive authority from God to judge irreversibly,
so as God himself cannot pardon that man he hath judged
(as he affirmeth) and yet that man not receive true sense,
wisdom and understanding from God to preserve him from misplacing it,
but it may be a true judgment or a false judgment
according as the witnesses`' information was?
Ah cease deceit, and for shame be silent: thy covering is manifestly too narrow.

In p. 66 he saith,
(speaking of the penalty or punishment of the laws)
"`If my innocency nor money will not deliver me,
I must and will suffer under it.`"

Observation.
He hath took scope enough to avoid the cross or suffering by any laws,
which might lay hold on him for conscience sake.
The apostles never saved themselves by money from their sufferings for their testimony.

In p. 70 he saith,
"`Every man that read the Scriptures doth think to find eternal life in them,
as Christ said to the Jews, and as you Quakers and others doth now adays.`"

Observation.
Do the Quakers think to find eternal life in the Scriptures?
did they ever teach men so?
Have they not very often faithfully testified otherwise?
Not in words concerning the thing, but in the thing itself,
in the Word which was in the beginning and from the beginning,
do they look to find eternal life.
Yea and there they have found it, and do live in the life which is eternal,
and the life which is eternal lives in them.
This testimony hath the living seal to it (whereby it may
be known by those that are truly living) and cannot be shaken.
But he hath manifestly in this thing (as in several
others also) discovered himself to be a false witness:
and a false witness can never be a true judge.
Nay alas his judgment is of and like his spirit, which manifestly is not of God;
and his knowledge which he holds forth leads not to God nor to life,
but to the chambers of hell and death.

=== Observations on some Passages in his Letter to Thomas Taylor

In page 5 he saith,
"`I marvel what satisfaction any man can have in his mind in believing in a Quakers`' God,
to tell a man that God abides in himself, and is what he is.`"

Observation.
Doth not God say to Moses concerning himself, I am that I am.
When Moses desired to know how he should answer the Israelites,
when they should enquire who sent him to them,
God bid him tell them that I am had sent him, Ex. 3:14.
How could the Israelites understand what God was by this?
what satisfaction could they find in this answer of Moses, would this spirit say?
But God is not to be known by the description of words of the earthly wisdom,
but in his own feeling Spirit and life.

In p. 11 he saith, concerning the Quakers, "`That which purifies your hearts,
is the law written in your seed and nature,
even the same as was written in the angel-serpent`'s nature before his fall,
which is no other but the nature of reason.`"

Observation.
This is not a true testimony:
for the light wherewith Christ enlighteneth the soul (to redeem
and bring it back out of the fall) is not of the nature of reason,
but confounds corrupt reason and brings it into the dust,
begetting the soul into the divine wisdom and giving it to partake of the divine nature.
Yea that which we are born of and purified by (as we sensibly feel
and truly understand) is not the nature of the serpent`'s reason,
but the immortal Word of God`'s eternal power, which doth that in us and for us,
which the nature of reason never did nor can do in any.

Again in p. 11. he saith very slightingly and as untruly concerning the Quakers, thus,
"`As for the sins your hearts are cleansed from, they are no other but such like as these,
that is to say, to keep the hat on the head before a magistrate,
and to find fault with gold-lace, and a piece of ribbon, a bandstring, and a gold button,
and to rend and tear gold-lace, and other lace off their clothes, and burn it,
and to use the language of thee and thou.
He or she that gets thee and thou perfectly, is a very good Quaker,
they are gotten half way to the Quakers`' heaven.
These and such like righteousness, is the Quakers`' perfection,
and all the cleansing of heart they have:`" etc.

Observation.
O thou despiser, reproacher and beliar of the work of God in the hearts of his children.
Nay, nay, there are thousands, who in God`'s presence can testify against thee,
that they have waited for and received the inward
cleansing from the filthiness of flesh and spirit,
from the inward lusts and motions of sin in the mind,
having felt the ax of the Lord and the two-edged sword,
which cutteth up sin at the very roots.
But thou art so far from having thy heart cleansed,
that thou art not yet cleansed from lying lips, but bringeth forth thy false reproachful,
slanderous testimony against the heritage of God in the sight of the sun.

In p. 13 he saith further of the Quakers, that "`they own no other death of Christ,
but what is within them, whatever they pretend by using the words of the Scripture,`" etc.

Observation.
They sincerely and in plainness of heart,
own and acknowledge the death of that body which the Father prepared for his Son,
in which he did the Father`'s will in his suffering without the gate of Jerusalem.
Therefore in this, he is a very false witness,
and therein hath grossly belied the Quakers.

In p. 15. he saith, "`You Quakers are the darkest pieces to interpret Scripture,
of any other opinions in the world, for you will name places of Scripture,
but never interpret any,`" etc.

Observation.
It is better to bring men to that, which opens the mind to understand the Scriptures,
than to give men interpretations of words or things beyond their capacity.
Yet the Spirit of the Lord, in and through many called Quakers,
doth often open many Scriptures in clearness and demonstration to others.
(Read the book, called Gospel-Liberty or the royal Law of Love,
and see if many Scriptures be not therein opened to the lowest capacity.)
But the Lord hath given them the true skill and understanding,
and they are not to open to and feed that in men,
which the Lord hath appointed to be famished.
Yet if they did not open Scriptures,
the Scriptures are plain to him that hath an understanding.

Now for a close, I shall add somewhat of the testimony which is written in my heart,
by the finger of God`'s Spirit, concerning the people called Quakers.

Indeed they have met with many reproaches, and sore oppositions many ways,
since they were a people: but notwithstanding all, their bow abides in strength,
and the hands of their arms have been made strong against the wicked one,
with all his devices in his several kinds of instruments:
and their light is still the same and their God the same,
who blesseth them from day to day, even in the midst of all the revilings, slanders,
persecutions and curses, which they have met with from men without,
and in the midst of all the temptations, inward trials and afflictions also,
which are often met with inwardly.
Yea we know him to be our God and cannot but trust him,
having found him to be faithful to us hitherto, and knowing his nature to be such,
that he cannot but continue his lovingkindness and faithfulness,
to all who are gathered by him into his holy inward,
spiritual covenant of life and peace, and who dwells with him therein.
And truly we are fully satisfied and at rest in him, and cannot desire another,
than he who hath redeemed our souls from death, given us life,
brought us out of the pit wherein was no water, into a large place,
set our feet upon a rock (a rock indeed) and establisheth
our goings in the path of holiness,
working all our works in us and for us, by his Spirit and power.
Yea, we have the witness in our hearts,
even the witness which never erred nor can deceive,
which testifieth to and with our spirits our sonship:
so that we do not imagine ourselves sons from apprehensions upon Scriptures,
but we feel ourselves sons in the true sensibleness, and know who David is,
and reap and inherit the sure mercies of David daily, O blessed be our Father,
O blessed forever be the Father of life, who feeds, who nourishes, who waters,
who refreshes (with the bread of life and with the pure living water) his lambs,
his babes, his plants, his tender ones, of whom he is daily tender,
and who are daily tender of his name and honor.
And if any man preach another God, then he who creates anew in the true light,
and therein puts forth his arm of salvation,
death and destruction and the curse are his portion from the hand of the Lord.

Now, O people, any of you that reads this man`'s writings and admire them;
what spirit are ye of! what is it in you that relisheth them?
what do they feed in you?
Not the true birth, I am sure: but that in you which must perish,
and come into death and destruction, if ever your souls be saved.
I speak sensibly, and from the true understanding and experience which God hath given me:
yea I certainly know,
that the knowledge and notions which he holds forth are not pure
nor able to cleanse the heart of any that receives them.

And all people, that truly love your souls and desire the salvation thereof,
O wait on God that ye may be enabled by him rightly to distinguish,
between receiving notions concerning God and Christ,
and feeling and receiving the power which effectually redeems from sin and death:
for deceit may enter in at the one, but cannot at the other.
The enemy hath all deceivableness of unrighteousness,
to paint as if it were righteousness and appear in, and to enter and possess the mind by:
but he is excluded the redeeming power.
He that feels that which renews his heart to God,
and breaks the power and strength of lusts and temptations in him,
and brings him into subjection to the Truth,
which from God lives in the hearts of those that receive it in the virtue,
life and power of it: here his devices and deceits are at an end,
and here the elect sheep feel the hand of the Father, which is stronger than all,
which none can pluck out of.
Here is the fold, here is the safe dwelling place,
whither the Lord leadeth and where he preserveth his lambs and children,
and there is not another.

Now as for him (notwithstanding all that he hath done against the Lord
and against his dear people) so far am I from wishing any harm unto him,
that I could wish with all my heart,
that it were possible for him to come to a true sense
of the true light of God`'s holy Spirit,
that by it he might examine, wherein he hath provoked and sinned against the Lord,
that the Lord should thus leave him, not only to be deceived himself,
but to become an head or root of deceit to others,
and so to bring the blood of many souls upon him,
which will be his bitter burden and misery in the day of the Lord upon him,
when the Lord shall rebuke him for blaspheming his name, his light, his Spirit,
and shall justify (in the sight of men and angels) those
to be his heritage and everlastingly dear unto him,
whom he hath reproached, misrepresented and cursed unto eternity:
but they are gathered by God into the blessed Seed (which he knoweth not,
nor in this spirit nor by this commission shall ever know) where he cannot curse,
nor can his curse reach or touch them, but they therein are blessed forevermore, Amen.

=== A Brief Account of my Soul`'s Travel Towards the Holy Land

and how at length it pleased
the Lord to join my Heart to his pure,
holy, living Truth; wherein I have witnessed the New Covenant,
and Peace with the Lord therein.
With a few Words concerning the way of Knowing and Receiving the Truth:
which is not done by Disputes and Reasonings of the Mind about it;
but in waiting aright for the Demonstration and Power
of God`'s Spirit to open the Heart and Understanding,
and by submissive Obedience to it, even in its lowest Appearances in the inward Parts

My heart from my childhood was pointed towards the Lord,
whom I feared and longed after from my tender years; wherein I felt,
that I could not be satisfied with (nor indeed seek
after) the things of this perishing world,
which naturally pass away; but I desired true sense of, and unity with,
that which abideth forever.
There was somewhat indeed then still within me (even the seed of
eternity) which leavened and balanced my spirit almost continually;
but I knew it not distinctly, so as to turn to it, and to give up to it,
entirely and understandingly.
In this temper of mind I earnestly sought after the Lord,
applying myself to hear sermons, and read the best books I could meet with,
but especially the Scriptures, which were very sweet and savory to me; yea,
I very earnestly desired and pressed after the knowledge of the Scriptures,
but was much afraid of receiving men`'s interpretations of them,
or of fastening any interpretation upon them myself; but waited much, and prayed much,
that from the Spirit of the Lord I might receive the true understanding of them,
and that he would chiefly endue me with that knowledge,
which I might feel sanctifying and saving.
And indeed I did sensibly receive of his love, of his mercy, and of his grace,
which I felt still freely to move towards me,
and at seasons when I was most filled with the sense of my own unworthiness,
and had least expectations of the manifestation of them.
But I was exceedingly entangled about election and
reprobation (having drunk in that doctrine,
according as it was then held forth by the strictest of those that were termed Puritans,
and as then seemed to be very manifest and positive from Rom. 9. etc.),
fearing lest, notwithstanding all my desires and seekings after the Lord,
he might in his decree have passed me by;
and I felt it would be bitter to me to bear his wrath,
and be separated from his love forevermore; yet, if he had so decreed, it would be,
and I should (notwithstanding these fair beginnings
and hopes) fall away and perish at the last.
In this great trouble and grief (which was much added to
by not finding the Spirit of God so in me and with me,
as I had read and believed the former Christians had it),
and in mourning over and grappling with secret corruptions and temptations,
I spent many years, and fell into great weakness of body;
and often casting myself upon my bed, did wring my hands and weep bitterly,
begging earnestly of the Lord, daily, that I might be pitied by him,
and helped against my enemies, and be made conformable to the image of his Son,
by his own renewing power.
And indeed at last (when my nature was almost spent,
and the pit of despair was even closing its mouth upon me) mercy sprang,
and deliverance came, and the Lord my God owned me, and sealed his love unto me,
and light sprang within me, which made not only the Scriptures,
but the very outward creatures glorious in my eye,
so that everything was sweet and pleasant and lightsome round about me.
But I soon felt, that this estate was too high and glorious for me,
and I was not able to abide in it, it so overcame my natural spirits; wherefore,
blessing the name of the Lord for his great goodness to me,
I prayed unto him to take that from me which I was not able to bear,
and to give me such a proportion of his light and presence,
as was suitable to my present state, and might fit me for his service.
Whereupon this was presently removed from me; yet a savor remained with me,
wherein I had sweetness, and comfort, and refreshment for a long season.
But my mind did not then know how to turn to and dwell with that which gave me the savor,
nor rightly to read what God did daily write in my heart,
which sufficiently manifested itself to be of him,
by its living virtue and pure operation upon me;
but I looked upon the Scriptures to be my rule,
and so would weigh the inward appearances of God to me by what was outwardly written,
and durst not receive any thing from God immediately, as it sprang from the fountain,
but only in that mediate way.
Herein did I limit the Holy One of Israel, and exceedingly hurt my own soul,
as I afterwards felt and came to understand.
Yet the Lord was tender to me, and condescended exceedingly, opening scriptures to me,
freshly every day, teaching and instructing, warming and comforting my heart thereby;
and truly he did help me to pray, and to believe,
and to love him and his appearances in any; yea, to love all the sons of men,
and all his creatures, with a true love.
But that in me which knew not the appearances of the Lord in my spirit,
but would limit him to words of scriptures formerly written, that proceeded yet further,
and would be raising a fabric of knowledge out of the scriptures,
and gathering a perfect rule (as I thought) concerning my heart, my words, my ways,
my worship; and according to what I thus drank in (after this manner,
from the Scriptures) I practised,
and with much seriousness of spirit and prayer to God fell
a helping to build up an Independent congregation,
wherein the savor of life and the presence of God was fresh with me,
as I believe there are yet some alive of that congregation can testify.

This was my state, when I was smitten, broken, and distressed by the Lord,
confounded in my worship, confounded in my knowledge,
stripped of all in one day (which it is hard to utter)
and was matter of amazement to all that beheld me.
I lay open and naked to all that would inquire of me,
and strive to search out what might be the cause the Lord should deal so with me.
They would at first be jealous that I had sinned and provoked him so to do;
but when they had scanned things thoroughly, and I had opened my heart nakedly to them,
I do not remember any one that ever retained that sense concerning me.
My soul remembereth the wormwood and gall, the exceeding bitterness of that state,
and is still humbled in me in the remembrance of it before the Lord.
Oh, how did I wish with Job, that I might come before him, and bowingly plead with him;
for indeed I had no sense of any guilt upon me, but was sick of love towards him,
and as one violently rent from the bosom of his beloved!
Oh, how gladly would I have met with death!
For I was weary all the day long, and afraid of the night,
and weary also of the night-season, and afraid of the ensuing day.
I remember my grievous and bitter mournings to the Lord; how often did I say, O Lord,
why hast thou forsaken me?
Why hast thou broken me to pieces?
I had no delight but thee, no desire after any but thee.
My heart was bent wholly to serve thee,
and thou hast even fitted me (as appeared to my sense)
by many deep exercises and experiences for thy service;
why dost thou make me thus miserable?
Sometimes I would cast mine eye upon a scripture, and my heart would even melt within me;
at other times I would desire to pray to my God, as I had formerly done;
but I found I knew him not, and I could not tell how to pray,
or in any wise to come near him, as I had formerly done.
In this condition I wandered up and down from mountain to hill, from one sort to another,
with a cry in my spirit, Can ye tell news of my beloved?
Where doth he dwell?
Where doth he appear?
But their voices were still strange to me, and I would retire sad and oppressed,
and bowed down in spirit, from them.

Now surely, all serious, sober, sensible people, will be ready to inquire,
how I came satisfyingly to know the Lord at length;
or whether I do yet certainly know him, and am yet truly satisfied?

Yes indeed, I am satisfied at my very heart.
Truly my heart is united to him whom I longed after,
in an everlasting covenant of pure life and peace.

Well then, how came this about?
will some say.

Why thus.
The Lord opened my spirit,
the Lord gave me the certain and sensible feeling of the pure seed,
which had been with me from the beginning;
the Lord caused his holy power to fall upon me,
and gave me such an inward demonstration and feeling of the seed of life,
that I cried out in my spirit: This is he, this is he; there is not another,
there never was another.
He was always near me, though I knew him not (not so sensibly, not so distinctly,
as now he was revealed in me and to me by the Father);
oh that I might now be joined to him, and he alone might live in me.
And so in the willingness which God had wrought in
me (in this day of his power to my soul),
I gave up to be instructed, exercised, and led by him,
in the waiting for and feeling of his holy seed,
that all might be wrought out of me which could not live with the seed,
but would be hindering the dwelling and reigning of the seed in me,
while it remained and had power.
And so I have gone through a sore travail, and fight of afflictings and temptations,
of many kinds; wherein the Lord hath been merciful to me in helping me,
and preserving the spark of life in me,
in the midst of many things which had befallen me,
whose nature tended to quench and extinguish it.

Now thus having met with the true way, and walked with the Lord therein,
wherein daily certainty, yea,
and full assurance of faith and of understanding is at length obtained;
I cannot be silent (true love and pure life stirring in me and
moving me) but am necessitated to testify of it to others;
and this is it, to retire inwardly, and wait to feel somewhat of the Lord,
somewhat of his Holy Spirit and power,
discovering and drawing from that which is contrary to him,
and into his holy nature and heavenly image.
And then, as the mind is joined to this, somewhat is received, some true life,
some true light, some true discerning;
which the creature not exceeding (but abiding in the measure of) is safe;
but it is easy erring from this, but hard abiding with it,
and not going before its leadings.
But he that feels life, and begins in life, doth he not begin safely?
And he that waits, and fears, and goes on no further than his Captain goes before him,
doth he not proceed safely?
Yea, very safely, even till he cometh to be so settled and established in the virtue,
demonstration, and power of truth, as nothing can prevail to shake him.
Now blessed be the Lord, there are many at this day,
who can truly and faithfully witness,
that they have been brought by the Lord to this state.
And thus have we learned of the Lord; to wit, not by the high, striving, aspiring mind,
but by lying low, and being contented with a little.
If but a crumb of bread (yet if bread), if but a drop of water (yet if water),
we have been contented with it, and also thankful to the Lord for it;
nor by thoughtfulness,
and wise searching and deep considering with our
own wisdom and reason have we obtained it;
but in the still, meek, and humble waiting, have we found that brought into the death,
which is not to know the mysteries of God`'s kingdom, and that which is to live,
made alive and increase in life.

Therefore he that would truly know the Lord,
let him take heed of his own reason and understanding.
I tried this way very far; for I considered most seriously and uprightly; I prayed,
I read the Scriptures, I earnestly desired to understand and find out whether that,
which this people, called Quakers, testified of,
was the only way and truth of God (as they seemed to me but to pretend);
but for all this prejudices multiplied upon me, and strong reasonings against them,
which appeared to me as unanswerable.
But when the Lord revealed his seed in me, and touched my heart therewith,
which administered true life and virtue to me,
I presently felt them there the children of the Most High, and so grown up in his life,
power, and holy dominion (as the inward eye, being opened by the Lord,
sees) as drew forth from me great reverence of heart, and praises to the Lord,
who had so appeared among men in these latter days.
And as God draweth, in any respect, oh,
give up in faithfulness to him! despise the shame, take up the cross;
for indeed it is a way which is very cross to man,
and which his wisdom will exceedingly be ashamed of;
but that must be denied and turned from, and the secret,
sensible drawings of God`'s Spirit waited for and given up to.
Mind, people: He that will come into the new covenant, must come into the obedience of it.
The light of life, which God hath hid in the heart, is the covenant;
and from this covenant God doth not give knowledge to satisfy the vast, aspiring,
comprehending wisdom of man; but living knowledge,
to feed that which is quickened by him; which knowledge is given in the obedience,
and is very sweet and precious to the state of him that knows how to feed upon it.
Yea truly, this is of a very excellent, pure, precious nature,
and a little of it weighs down that great vast knowledge in the comprehending part,
which the man`'s spirit and nature so much prizeth and presseth after.
And truly, friends,
I witness at this day a great difference between
the sweetness of comprehending the knowledge of things,
as expressed in the Scriptures (this I fed much on formerly),
and tasting the hidden life, the hidden Manna in the heart (which is my food now,
blessed forever be the Lord my God and Saviour).
Oh that others had a true, certain, and sensible taste of the life, virtue,
and goodness of the Lord, as it is revealed there!
Surely, it could not but kindle the true hunger, and inflame the true thirst;
which can never be satisfied but by the true bread,
and by water from the living fountain.
This the Lord (in the tenderness of his love,
and in the riches of his grace and mercy) hath brought us to;
and this we earnestly and uprightly desire and endeavor,
that others may be brought to also;
that they may rightly (in the true silence of the flesh,
and in the pure stillness of spirit) wait for, and in the Lord`'s due time receive,
that which answers the desire of the awakened mind and soul,
and satisfies it with the true precious substance forevermore, amen.
