[short="Some Things Relating to Religion Proposed"]
== Some Things Relating to Religion Proposed to the Consideration of the Royal Society, So Termed

[.heading-continuation-blurb]
To wit, Concerning the right ground of certainty therein;
Concerning tenderness of spirit, and persecution;
a query concerning separation;
Concerning washing away sin from the conscience and the garment of salvation,
and what it is that is covered therewith.

[.heading-continuation-blurb]
Likewise, some Questions and Answers, concerning the Church of the New Covenant,
the Rock or Foundation whereon it is built, and its preservation by and upon the Rock.

[.heading-continuation-blurb]
With some Queries concerning the scattered and hidden Estate of the Church;
and concerning that Church which got up in the view of the World, instead thereof;
and was acknowledged by the World as if she had been the true Church;
though in Deed and Truth she was not so.

[.heading-continuation-blurb]
Whereunto are added some queries to professors, who speak of high attainments, etc.

[.heading-continuation-blurb]
Written by one, whom it hath pleased the Lord, of his great goodness, and tender mercy,
to lead out of the darkness, into his marvellous light; known among men by the name of

[.section-author]
Isaac Penington

[.section-date]
1668

[.centered]
=== To the Royal Society So Termed

[.salutation]
Friends,

I have heard that ye are seeking after the excellency of nature and learning.
I am not for discouraging any man, in endeavoring after that which is good, useful,
and excellent in its kind and place; but it is the advantage of everything,
to know and abide in its place; and to honor and serve Him,
from whom all good gifts and endowments come.
Man hath but a moment in this world, and he is here no more;
and then the spirit returneth to God that gave it,
to give an account of the talent which he gave it, and its improvement thereof,
to the glory of him that gave it, and to the salvation of its own soul.
Now, this talent is of an higher kind than nature, and will lead higher than nature;
giving a man to partake of that wisdom from which nature came;
and teaching him to order all that is natural to its right end.
For God is not an enemy to nature, but to the corruption and disorder of nature.
I desire ye might know and partake of the true wisdom,
and feel union with God in the principle of his own life;
and the incorruptible and heavenly seed of God receive
dominion over the earthly and corruptible.
For this end singly, in the love springing up in my heart towards you (as it often doth,
both towards particular persons and societies; for I am a friend to all,
and a lover of all; sincerely desiring the good of all,
and the right guidance of their souls to happiness),
have I proposed these things following more particularly to your view,
though they concern others also,
that ye thereby might be awakened to search after that which is most excellent in you,
and be acquainted with the virtue and precious effects thereof,
to the full satisfaction and complete joy of your souls,
in that which alone is able fully to satisfy,
and give them ground of durable joy and rejoicing,
in that which is not of a perishing nature; but which was, and is, and will be,
the same forever.

From a friend to the everlasting peace of your souls,
and a desirer of your welfare and prosperity in this world.

[.signed-section-signature]
Isaac Penington

[.old-style]
=== Some Things Relating to Religion, etc. / Of Certainty, and Rightly-grounded Assurance, in Matters of Religion

There is a witness of and from God in every conscience; which, in his light, power,
and authority, witnesseth for him, and against that which is contrary to him,
as he pleaseth to move upon it, visiting and drawing the hearts of the sons of men by it.

From this witness proceeds the true and well-grounded religion in the mind towards God:
for this witness both testifieth and demonstrateth that there is a God,
and also inclineth the mind to desire and seek after
the right knowledge and true worship of him.

And such who keep to this witness, and wait upon God therein,
are taught by it the true spiritual worship; the true and pure fear of the Most High;
the faith which he giveth to his saints; the love which is chaste and unfeigned;
the hope which purifieth the mind, and anchors it on the eternal rock; the meekness,
patience, gentleness, humility, etc., which is not of man`'s nature, but the gift of God,
and the nature of the heavenly Giver.

And then for exercises of religion, as praying to the Father of spirits,
hearing the heavenly voice, reading in the Spirit, and with the renewed understanding,
singing and making melody in the heart (and also with the voice) to the Lord,
as his life is felt, and the spiritual blessings and treasure received; all these,
and whatever else is judged necessary for the soul,
are taught by this witness of God in the conscience, as the soul groweth up in the light,
Spirit, nature, and holy power thereof.

But now, when the Lord reacheth to his witness in men,
and is teaching their hearts by it, then the enemy, the other spirit,
whose seat is in the other part, keepeth a noise there,
to overbear the voice of the witness, and to make men take up religion in another part,
which is shallow, and reacheth not to the depth and weight of truth,
which is in the witness of God,
and which the witness of God gives to them that come thither.

Thus the enemy stirreth up reasonings, imaginations, and consultations about God,
and his worship; wherein he raiseth up the vain, shallow mind,
forging and bringing forth somewhat pleasing and suitable to the earthly understanding;
taking up the mind therewith,
and engaging the heart in some such practices therefrom
as may quiet and satisfy that part in men.
For the ways that men take up in their reasonings and understandings,
satisfy their reasonings and understandings; and so they walk in the light of the sparks,
and warm themselves by the fire of their own kindling;
but all this answers not the witness of God in them,
nor will be approved by his light in their own consciences,
when it comes again to be revealed and made manifest in them.

This was the ground of the error both of the Jews and Gentiles.

The Gentiles were enlightened by God with his true light;
what might be known of God (suitable to their state
and capacity) being manifested in them;
insomuch as it is witnessed concerning them in the
Scriptures (which are a true record and testimony),
that they knew God.
But when they knew him, they glorified him not as God,
but became vain in their imaginations,
and so their foolish heart was darkened concerning him:
and they worshipped him not as the witness taught them he was to be worshipped,
not according to the manifestation of his light in them;
but according to their own foolish imaginations and reasonings,
which taught them to make images of him, and so to worship him in and through creatures,
according to their own inventions; which is not the true worship. Rom. 1:21-23.

So likewise the Jews,
not keeping to the manifestation of his light within them
(to the word or commandment nigh in the mouth and heart,
to which Moses directed them),
which would have taught and enabled them to have kept to the law of the letter
without them,--they also ran into the nature and spirit of the heathen,
and fell into imaginings and reasonings, which led them to worship like them;
insomuch that they also changed their glory into the image of an ox, that eateth grass.
Ps. 106:20.

Now from this part in man ariseth all the uncertainty, and doubts,
and dissatisfaction about religion.
And hence arise the opinions, and judgments, and reasonings, in the minds of men: yea,
indeed, the best of men`'s religion here is but an opinion or judgment,
which the breath of God`'s Spirit will shake and dissolve everywhere, sooner or later.
All flesh is grass; and all the beauty of men`'s knowledge, religion, and worship here,
will wither like grass.
All the buildings and churches that are raised here (how beautiful soever) are but Babylon,
built by man`'s understanding, by man`'s knowledge, by man`'s comprehension,
by man`'s wisdom, by man`'s skill, and indeed in man`'s will and time,
and their standing, beauty, strength, and glory, is but from man, and in man`'s day,
and will fade away like a flower.

But the true certainty is the day of God,
from the light of his Spirit shining into man`'s spirit,
from God`'s inward reaching to his heart by his power, and testifying his truth there.
And this all the powers of darkness cannot prevail against in itself; no,
nor against that man that is kept to it.
For it is the rock (the only rock) upon which the whole church is built,
and which cannot fail to preserve every member of the church which is built upon it.

Ye then which would come to certainty in religion,
observe the way which is made manifest from God in this our day, blessed be his name,
which is this: mind the witness of God in thy heart, and come to, and build upon,
the light thereof.
Dwell not in reasonings; take not up thy religion in reasonings of the mind;
but pass through them, pass beyond them, into a light of an higher nature.
Wait to know the birth which is from God, and the light which he gives to that birth.
What is the birth?
Is not the birth of and from the second Adam?
And what is the heavenly birth`'s light?
Is it not the light of the second Adam?
Is it not in nature and kind above the light of the first Adam?
Where is the seat of reasonings?
Is it not the earthly mind, the fallen mind?
Here lies man`'s strength; here is man`'s wisdom; here is man`'s life.
It is so indeed; but the wisdom of Christ, the light of Christ, the life of Christ,
the power of Christ, is a cross to this; finds it in the enmity against God,
crucifies it, slays it, brings it to nothing; and he that will become wise as to God,
must become a fool unto all this, a child, a babe, entering the kingdom without this,
and must there remain naked as to this, and never put it on more.

Now observe (ye that have understanding and true sense) the difference
between the religion which God hath taught us,
and led us into, and the religions of all men upon the earth besides.

Our religion stands wholly out of that which all their religion stands in.
Their religion stands in the comprehension,
in a belief of a literal relation or description.
Our religion stands in a principle which changeth the mind,
wherein the Spirit of life appeareth to,
and witnesseth in the conscience to and concerning the things of the kingdom;
where we hear the voice, and see the express image of the Invisible One, and know things,
not from an outward relation, but from their inward nature, virtue, and power.
Yea, here (we must profess) we so know things, that we are fully satisfied about them,
and could not doubt concerning them,
though there never had been word or letter written of them;
though indeed it is also a great comfort, and sweet refreshment to us,
to read that testified of outwardly,
which (through the tender mercy of our God) we feel and enjoy inwardly.
And in this our whole religion consists; to wit, in the silence and death of the flesh,
and in the quickening and flowing life of the Spirit.
For he who is of the new birth, of the new creation,
of the second Adam (the Lord from heaven), is as really alive to God,
and as really lives to him in his Spirit,
as ever he was really dead in trespasses and sins in the
time of his alienation and estrangement from God.

[.centered]
=== Of Tenderness of Spirit, and Persecution

He which is born of God, he who is of the love, and in the love,
cannot but be tender.
He who is born of the earthly wisdom, who taketh up and holdeth forth a religion there,
cannot but persecute.
Why so?
Because he cannot but judge that any man may take up religion as he hath done, and so,
by reasonings, may come to acknowledge and take up what he hath taken up,
and holdeth forth, or else he is wilful and stubborn, as he judgeth.
But now he that is born of God, and hath received his light, knowledge, religion,
and way of worship from him,
he knoweth that no man can rightly receive them but the same way; to wit, from God,
by the light which he causeth to shine into the heart at its pleasure,
and in the faith which he gives.
So that God`'s free and powerful Spirit is to be waited upon,
for the working of all in his people, and not any forced to act beyond, or contrary to,
the principle of his life and light in them.

[.centered]
=== A Query Concerning Separation

[.discourse-part]
_Query._
Whether, after the apostasy from the Spirit, life, and power of the apostles,
and the getting up of the antichristian state, church, and worship,
there must not of necessity be a separation from all these,
before there can be a recovery of the life and power again, and of the true church-state,
which was brought forth in the days of the apostles?
Must there not be a perfect coming out of the corrupt state (in the whole nature,
several parts and degrees of it) before there can be a restoration
to and witnessing of the true and pure state?
Must not the Christians now come out of all the antichristian inventions and churches,
as well as the Christians of old came out of all the heathenish worship, yea,
out of the Jewish worship and church (which once
was of God) before they can become an holy building,
an habitation to God in the Spirit?
Yea, doth not the same Spirit which cried to the people of God then:
"`Come out from among them, and be ye separate,`" etc., call and cry now: _Come out of her,
my people,_ out of Babylon, out of the false church,
out of all the antichristian buildings,
which are reared up after the several forms and ways of men`'s inventing,
being out of the Spirit, life, and power,
which alone is able to build up in and unto the Lord?
And what is that which cries out against separation,
in the day of the Lord`'s dividing and separating,
but that spirit which would hold back the soul from being gathered to the Lord,
in the chains of darkness, and in the land of death and confusion?

Oh that men knew that which divides and separates,
and which is appointed by God to divide and separate both inwardly and outwardly,
and might feel the full work and effect of it,
even perfect separation from all that is not of God, that so they might be joined to him,
and built up in him, who is the life, rest, peace, joy,
and pure breath of the soul forever!
The Word of God is quick and powerful, sharper than any two-edged sword;
and what doth it do?
Why it separates between nation and nation, between church and church,
between people and people, between cattle and cattle, between soul and soul, yea,
between the thoughts and intents of the same heart;
owning and cherishing all that is of the pure,
and condemning and destroying all that is of the impure.
And happy, oh! forever happy is he,
who can witness the work of this Word perfected in his soul,
even the axe of the Lord powerfully laid to, and having cut down,
all that is corrupt in him, that the pure plant of God may flourish,
and bring forth fruit in him in peace, without annoyance or interruption of the impure.
Then the river of life, as the streams of everlasting righteousness,
shall flow into the vessel, and Jerusalem become in and to him a quiet habitation,
and nothing be able to hurt or destroy any thing of life in him,
who dwells in and abides on the mountain of God`'s holiness.
Oh, blessed is the race of travellers,
which in the pure light of the everlasting day are travelling thitherwards,
even with their hearts and faces faithfully bent towards Zion, which is the holy,
spiritual, heavenly hill of God!
And blessed, oh blessed forever is the Lord God of life and power,
who is the faithful guider, leader,
and conductor of all that follow the footsteps of the flock, in the way which is pure,
true, living, and everlasting!

[.old-style]
=== Concerning the Washing Away of Sin from the Conscience / And the Garment of Salvation, and What It is That is Covered Therewith.

There is somewhat appointed by God to wash away sin,
which is the water of regeneration, the water of life, the Spirit`'s water,
and the blood of the Lamb, which are known, received,
and felt by faith in the light of the Spirit, wherein alone his work is wrought.

Thus now, upon believing, the soul is washed; the faith brings in, or lets in,
the water and blood, which cleanse and purge the conscience from the sin,
which before stained and defiled it: and according to the faith,
so is the water and blood let in, and accordingly is the washing.
And he that is baptized, he that is washed by the Spirit, comes out of the water clean;
and watching to the light wherein he was purified,
witnesseth the powerful word of life as able to preserve in cleanness,
as it was to cleanse.

But if there be not a watch to, and faith in, and singlehearted obedience to,
that which purified, and keepeth pure, there is that near which will defile,
where it is hearkened to and let in; there is that which will tempt to lust and sin,
and so draw into darkness and death again.
And if any man sin afterwards, sin defiles again,
and the stain thereof will lie upon the conscience, till, by repentance and faith,
the water and blood be let in again,
and the cleansing virtue from it received and restored again.
So that if any man sin, there is an advocate,^
footnote:[But this is not the state of them that sin willfully
after they have received the knowledge of truth.
+++[+++I.P.+++]+++]
an intercessor, a divine helper, one who hath the water of life,
and the blood of life to wash with.
There is a fountain set open for sin, and for uncleanness,
for Judah and Jerusalem to wash therefrom;
but every defilement and pollution sticks until it be washed off.

Now, there are sins of several kinds.
Some are easily remitted and washed off,
insomuch as the stain is hardly felt by the soul,
the tender mercy and pure life doth so readily and naturally flow over them.
Some, again, are long held and bound by the Spirit upon the conscience,
and often remembered to the heart, which is apt to backslide: yea, there is,
in some cases, a severe judgment, and a long waiting on the Lord for his mercy,
and for his renewing and enlivening of faith,
before the water and blood which washeth can be again felt.
For faith is not in a man`'s power, nor repentance neither; but they are given of God,
to whom and when he pleaseth.
And a man that is in part converted may give ear to the enemy,
and let in sin and death upon the soul; but he cannot repent again presently,
nor believe again presently; but as God breathes upon him,
and revives the work of faith and repentance in him.

There were sins under the old covenant, and there are sins under the new.
The sins of the old covenant did lie upon him that committed them,
until they were expiated according to the law of the old covenant;
and sins under the new covenant lie also upon the soul and conscience,
until they be expiated according to the law of the new covenant;
which is until the Advocate interpose and plead with the Father,
and give faith and repentance to the soul,
and sprinkle upon the heart and conscience that water
and blood which hath virtue in it to wash.
And if it were not for this after-washing (as I may so say) no man could be saved:
but though he were once washed, yet sinning again afterwards,
he would die in his sins (and so fall under condemnation), unless he were again washed.
Oh! blessed be the name of the Lord, for the water and blood of the covenant,
and for his continual pouring them out upon the souls of his,
in the light that is eternal!

Now, as men come to the truth as it is in Jesus,
they will find their own apprehensions about these things to have been but dreams,
wherewith the enemy hath fed and pleased them,
while he hath lulled them asleep in the night of darkness,
that he might the better steal away the true,
weighty knowledge of the things of the kingdom from them.
Thus men have dreamed about justification, about sanctification, about regeneration,
about redemption, about faith, hope, love, righteousness, peace, joy, etc.:
and have been mistaken about them,
missing of that power and light whereby and wherein they are revealed and made manifest.
Now, he that will rightly know these things must know them in the feeling and true experience;
and therein he shall find all these are wrought in
a mysterious way of pure life`'s operation,
out of the reach of man`'s comprehension; and no man can understand them,
but as the new and holy understanding is given him;
nor retain the sense and knowledge of them, but as he abides in the new nature,
and retains the new understanding.

So for the garment of salvation; that is Christ, the righteousness of Christ,
the nature of Christ, the Spirit of Christ.
This is the holy covering.
He that puts on Christ, puts on this: he that wears Christ, wears this:
he that appears before God in Christ, appears in this; and the soul puts on this,
as it puts off the other.
It is the purified soul that only puts on him that is pure:
and as a man is cleansed from the impure,
so only hath he in him a capacity of receiving and being clothed with Christ.
And this now is the work of the true ministry; to wit, to preach the Word,
to reveal the Word, and bring the mind to the Word (which changeth it,
and begets the new capacity), and so to begin the work of life and reconciliation,
wherein and whereby there is some unclothing of the old, and some clothing with the new;
and so to carry on this work in the Spirit and power of the Father until it be perfected.
And is this a blessed work, and blessed is the ministry which is called to,
and entrusted with, this work, being faithful in it:
and blessed are they that witness the truth of, and receive the effect of, this ministry,
and are subject to it in the Lord.
For through and under this ministry there is a receiving of a perfect
gift in some measure at first (wherein some true union and little
acquaintance with the Lord of life is at first witnessed,
and some operation of the light and power of his Holy Spirit):
and a growing up in it unto perfection, as the soul is exercised by it,
and faithful to the Lord in the exercise, under the daily cross,
which daily worketh against and crucifieth in the heart, mind, life,
and conversation whatever is contrary to God, as it is singly waited for, taken up,
and subjected to.

[.centered]
=== Some Questions and Answers

[.heading-continuation-blurb]
Concerning the Church of the New Covenant, the Rock or Foundation whereon It Is Built,
and Its Preservation by and upon the Rock.

[.heading-continuation-blurb]
With some _Queries_ concerning the scattered Estate of the true Church,
and concerning that Church which got up in its Stead,
and made a great Show with her golden Cup,
for the Time while the true Church was scattered.

[.discourse-part]
_Question 1._ What is the church of God under the new agreement or covenant?

[.discourse-part]
Answer.
It is a company of living stones, quickened by God,
and knit together in the unity and fellowship of his Spirit,
to worship God together in his Spirit, and offer up unto him spiritual sacrifices,
acceptable to God by Jesus Christ.
What was the church of the old covenant?
Was it not the seed of Abraham, the outward Jews, the children of the old covenant?
And what is the church of the new covenant?
Is it not the seed of God, the Jews inward, the children of the new covenant?

[.discourse-part]
_Question 2._ How are these stones joined together?

[.discourse-part]
Answer.
By the Spirit of life, which begets them all in one nature,
and knits them together in that nature.
By the inward circumcision, cutting off that which causeth enmity and disunion,
and so fitting them to be made one new lump in Christ.
By Christ`'s baptism, which is the baptism of fire and of his Spirit,
which burns up the old earthly nature, and so baptizes them into one new, living body,
suitable and fitting to their head, which is the fountain of life,
and distributes life through all the body, according to its capacity, need, and service.

[.discourse-part]
_Question 3._ Upon what is this church built?

[.discourse-part]
Answer.
Upon the rock or foundation of God, which God hath laid in his spiritual Zion;
which rock is Christ.
For "`other foundation can no man lay, than that which is laid,
which is Jesus Christ;`" nor other rock did the Lord
ever choose for his church to be built upon;
nor hath any other rock sufficient strength to bear up the building
against the storms and stress of the powers of darkness,
which it often meeteth with, even every member, in its travels;
after it is once built on the rock, the gates of hell press hard upon it;
but abiding on the rock, it feels the strength and preservation of the rock.
For as they cannot prevail against Christ,
so neither can they prevail against that which is built upon him.
But if there be a going forth from the strength and preservation,
there is a liableness to be made a prey.
And the promise is not absolutely and perpetually to that person
or congregation which is received or let into the truth;
but to that person or church which abideth and continueth in the truth unto the end.
The Jews were safe in the faith and obedience of their covenant; and the Christians,
or Christian churches, are not safe but in the faith and obedience of theirs.
For if they walked not humbly with the Lord, and in his fear,
which keeps the heart from departing from him, and in the faith whereby they stand,
they were to be cut off from their church-state, as well as the Jews were from theirs,
as the apostle Paul expressly tells the church at Rome. Rom. 11:21-22.

[.discourse-part]
_Question 4._ What was Paul?

[.discourse-part]
Answer.
The apostle of the Gentiles, who labored abundantly,
even more abundantly than all the other apostles;
and hath left more instructions relating to the Gentiles than all the apostles besides;
and was tender of them, in standing for and defending their liberty in Christ,
when Peter a little warped, and was to be blamed. Gal. 2:11.
For indeed man cannot be certain and infallible,
further than he keepeth to, and is exercised by, the certain and infallible Spirit;
which he is subject to be tempted to err from, further than he stands upon the watch,
and cannot but err from, unless he feel a continual preservation in the fear,
and by the power of the Lord.
And the certainty of truth doth not depend so much upon the person from whom it is received,
as upon the demonstration and evidence to the conscience wherein it is received.
The apostles were not lords over the true Christians`' faith; but helpers of their joy.
And Christ did not require his disciples to believe whatever he knew to be true;
but prepared their capacities, and dropped in according to their capacities.
And this is the way of true ministers, to wait on God to beget,
and on him again to water the begotten soul, and carry on his work in it;
to make them know Christ their Master, from whom they are to receive light, life,
instruction, and direction; and to feel the Head, and be joined to the Head,
and receive from the Head their knowledge, as well the least as the greatest.
Heb. 8. What is Paul?
What is Apollos?
What is Cephas?
Were not they carnal that cried up these one above another?
Yet the younger ought to be subject to the elder,
and all to be subject one to another in the truth. 1 Pet. 5:5.

[.discourse-part]
_Question 5._ What was Peter?

[.discourse-part]
Answer.
One of the disciples of Christ, a precious stone in the building (John 1:42),
one of the most eminent apostles, even the chosen minister to them of the circumcision,
as Paul was to the Gentiles.
But he knew that Christ was the only rock or foundation, as well as Paul,
as that Christ alone was able to bear the weight of that building,
and to defend it against the gates of hell; and he never had commission,
nor can it be proved that he ever preached himself the rock,
but he preached Christ the foundation-stone, the rock of offence, the rock of defence,
etc. see 1 Pet. 2:4 and ver. 6-8. And if an angel from heaven,
or any man or church on earth, so interpret any scripture,
as to hold forth any such thing, that any else besides Christ is the rock,
they plainly show that they are erred from the truth,
and that their interpretation is of their own private spirit,
and not that public Spirit which all the prophets of God, and apostles,
and truly holy men were guided by.

[.discourse-part]
_Question 6._ Was the church always to be a gathered company?
Or was there a possibility of their being scattered?

[.discourse-part]
Answer.
There was a possibility of their being scattered; yea, a certainty,
if they grew corrupt in doctrine and practice, and kept not the faith.
Rom. 11. For the Lord God intended a pure building, a spiritual building,
fit to offer the spiritual sacrifices. 1 Pet. 2:5.
A holy people, separated from the world, 2 Cor. 6:17.
in which he might dwell and walk,
ver. 16. If therefore any church depart from the Spirit and life and power of the apostles,
and mix again with the world, losing their own proper pale which fenced from the world,
they soon lose that which maketh them a church of God,
and so become a synagogue of Satan.

Now, it is in my heart also to propound a few queries concerning
the scattered and hidden estate and condition of the church,
and concerning that church which got up in the view of the world,
and was acknowledged by the world instead thereof afterwards.

[.numbered-group]
====

[.numbered]
_Question 1._ Whether the true church did retain her
ministry outwardly, and her outward ordinances,
and way of worship of the outward court, after her scattering?
Or whether the false church, which appeared in her room as if she had been the true,
caught up and appeared in the outwardness of these?
The grounds of this query are these following:

====

[.numbered-group]
====

[.numbered]
1+++.+++ Because, upon God`'s measuring of his temple and worshippers,
the outward court (consider well what that is,
and how far it extends) was left out of God`'s measure;
so that he intended to reckon it no longer as his,
but given by him to the Gentile Christians; such as were Christians or Jews in name,
but Gentiles in spirit and nature.
Rev. 11.

[.numbered]
2+++.+++ Because in the last days, when that strange generation of Christians was to spring up,
who should be lovers of their own selves, covetous, proud, blasphemers,
disobedient to parents, unthankful, unholy, without natural affection, truce-breakers,
false accusers, incontinent, fierce, despisers of those that are good, traitors, heavy,
high-minded, lovers of pleasure more than lovers of God;
yet these should have a form of godliness, but deny the power thereof. 2 Tim. 3:1-6.
Now mind: the temple wherein was the power,
God had removed with the true worshippers;
but the outward court (wherein was the appearance of some kind of a form of a church,
ministry, and ordinances) those had got, and were found worshipping in it,
in the midst of all this great wickedness and abomination of spirit.

[.numbered]
3+++.+++ Because the Jews (who were the type), while they were in captivity in Babylon,
could not sing the songs of Zion, nor had the worship of the outward Jerusalem there.

====

And can the spiritual Jews sing the spiritual songs of spiritual Zion, in Mystery-Babylon?
No;
there they are but witnesses to that life and power
which the true church enjoyed and flourished with,
in her built estate.

[.numbered-group]
====

[.numbered]
_Question 2._ Whether this is not an infallible mark,
and most certain demonstration of the false church,--her sitting upon many waters;
which waters are peoples, multitudes, nations, and tongues?
Did not the Spirit of the Lord thus mark her out to John? Rev. 17:15.
Did the true church ever sit upon many waters?
Was not the church a gathering out of the nations,
into the power and life which the nations persecuted?
But the false church sits over the nations with a form of godliness,
but without the true power thereof.
Then if this be a mark that God hath set upon her, let every one wait to read it aright,
that he may know thereby which is she,
and praise the name of the Lord for discovering her to him.

[.numbered]
_Question 3._ Whether this false church be not rightly called Babylon,
even a heap of confusion (in a mystery) as to God`'s eye,
though to man`'s eye her appearance may be orderly and decent?
And whether she be not justly termed, by the Spirit of the Lord, the great whore,
both for largeness in bulk, and for the greatness of her fornications,
having whored from the bed of the husband, and entered into the bed of a stranger;
and having taught and compelled others to acknowledge and worship in her forms; which,
thus held forth and maintained by her, are not only without, but also against,
the true power?

[.numbered]
_Question 4._ Whether antichrist be not entered into, and become the head of, this false church?
And whether he doth not sit there ruling in it, even as Christ was head of the true,
and sat ruling in the true?
And whether antichrist doth not keep his hold of this church, and possess his seat in it,
for many ages and generations,
even from the time he got in after the days of the apostles,
till the very coming of Christ in his power and brightness?
2 Thess.
2.

[.numbered]
_Question 5._ Whether the great plagues, woes, terrible thunders, and cups of God`'s indignation,
spoken of in the book of the Revelations, are not to be poured,
in their several orders and degrees, upon this false church, and upon antichrist,
her beloved head and king, even till she be stripped naked, made desolate,
and her flesh burnt with fire, and her head bruised and destroyed by Christ,
the true Head and King of the true church?

[.numbered]
_Question 6._ Whether the people of God, such as feel somewhat of the power,
and bow to the Lord in Spirit and truth in some measure; yet these,
if they mind not his call out of this Babylon, and come not fully out of her,
but abide in any part of her, observing any of her ways or worships,
till the time of God`'s controversy with her, and judging of her,
whether they also shall not partake of her plagues? Rev. 18:4.

[.numbered]
_Question 7._ Whether all people have not great reason to fear before the Lord,
and to look to their ways and worships,
lest they be found in any thing therein which is not of him, but contrary to him,
and so bring upon their souls and bodies that wrath and
sore judgment from God which they are not able to bear? Rev. 14:9-11.

[.numbered]
_Question 8._ Whether it was not the great love and mercy of God to warn the
churches of these things in the book of the Revelations?
And whether he can be safe in these respects, who either doth not understand,
or not observe, the warnings given by the Spirit of the Lord therein?
How often is it therein said: "`He that hath an ear,
let him hear what the Spirit of God saith to the churches.`" It is also said:
"`Blessed is he that readeth, and they that hear the words of this prophecy,
and keep those things, which are written therein: for the time is at hand.`" He, then,
that readeth not, that hath not an ear to hear the words of this prophecy,
how can he keep what is written therein?
How can he beware and avoid the seeming beauty and glory of the false church,
or suffer with the faithful witnesses of God in their testimony against her?
And if he do not thus,
but is entangled by the false church with her golden cup of fornications,
(Rev. 17:4) he misseth of the blessing;
and ah! what is he to meet with instead thereof!
My heart hath often melted within me,
and my bowels rolled at the consideration and deep
sense which the Lord hath given me of these things;
and this I say therein, to those that desire life and peace from God,
Oh! wait on him for the eye which sees in his light, for the ear which hears his voice,
and for the heart which understands the words and messages of his Spirit,
that ye may feel his gathering, guidance, and preservation out of that,
to which his wrath is forever, and against which his wrath is to be made more manifest,
and poured out more fully and abundantly than ever it yet was.
For the Lord will empty his love and his life into Zion,
and empty the very dregs and thick mixtures of the cups
of his indignation into the very heart and bowels of Babylon;
and her sickness, misery, woe, death,
and destruction will be exceeding dreadful and unutterable.
Therefore wait on the Lord in fear and singleness of spirit,
crying and mourning unto him to discover to you the
extent and limits of this false church,
this false building, this building in a form and outward order,
without the life and power of the Spirit; and then fly as fast out of her,
and from her (and as far), as the Spirit of the Lord leads,
even till ye come to the holy building, which is of him,
and the heavenly places which are prepared there by him,
for every one of his (according to their growth and stature in his Son),
that ye may sit down in him.

====

[.centered]
=== Some Queries to Professors

[.heading-continuation-blurb]
Who speak of high Attainments and Experiences in Religion, and yet do not witness,
nor can acknowledge, the Truth, as the Lord hath now revealed it
(and done great Things by it in the Spirits of his People),
but look upon it as a poor, mean and low Thing.

[.numbered-group]
====

[.numbered]
_Query 1._ Have ye known the great and terrible day of the Lord,
wherein he ariseth to shake terribly the earth?
And have ye known that shaken down in you which must
be shaken down and removed as a cottage,
before the everlasting kingdom can be established in you?

[.numbered]
_Query 2._ Do ye know the living, powerful, eternal word, which is quick and piercing,
sharper than any two-edged sword, dividing between thought and thought, grace and grace,
(as I may so speak) light and light, life and life, spirit and spirit, power and power?
etc. Have ye known it a hammer, a fire, an axe laid to the root of the corrupt tree?
And do ye know the corrupt tree (root, branches, leaves,
and fruit) so cut down by it as to cumber the ground no more?

[.numbered]
_Query 3._ Do ye know the paradise of God, and the tree of life there?
Do ye indeed feed thereon?
Have ye passed through the flaming sword to the tree of life?
And is the flaming sword (which once fenced from life,
and the power thereof) set now to fence up the way to the tree of knowledge,
that ye may feed no more thereon, and die, but feed only on that which is life,
and gives life, and so live forever?

[.numbered]
_Query 4._ Have ye witnessed the effects of the great
and terrible day of the Lord in your spirits?
Is antichrist destroyed, the whore burnt, flesh consumed, man ceased from,
both within and without?
Is the loftiness of man bowed down in you, the mighty removed out of his seat,
and the meek, holy, humble seed raised up to rule in righteousness in your hearts?
Is every high tower battered down, and every fenced wall laid flat?
Are all your imaginations, and conceivings, and fleshy apprehendings upon scriptures,
yea,
every pleasant picture and image of the things in
heaven (formed in your minds) brought to an end,
and the pure living truth of the Father waited for, received from him, and lived in?
Yea, is the Lord alone exalted in your spirits, and all other dominion, authority, rule,
and lordship put under?

[.numbered]
_Query 5._ Do ye know the mountain of the Lord`'s house,
and the Lord`'s house built and established by his
own Holy Spirit and power upon his own holy mountain?
And do ye worship the Lord alone therein?
Do ye come up to the New Jerusalem, to offer your sacrifices there,
according to the institution of the gospel?
And do ye worship the Lord there, on his own day, which he hath spiritually made?
And do ye bear no burden, kindle no fire, do no work on that his day?
Do ye never warm yourselves at any fire, or by any sparks of your own kindling?
Or are ye yet worshipping upon some of the many mountains
and hills which the Lord hath not formed nor established;
but have been formed and set up by man in the night of darkness,
before the everlasting light of the day break forth?

[.numbered]
_Query 6._ Do you know the wilderness through which the passage is from Egypt to Canaan?
And have ye faithfully travelled in the leadings of God`'s Spirit there through?
And are ye entered into the pure rest thereof?
Are ye not under the law, but under grace; not under the enemy`'s power,
but under the Spirit`'s power, out of the other`'s reach,
so that the wicked one cannot touch you?
Have ye gone through the exercises and trials of the wilderness?
Have ye fed on the manna dropt down from heaven upon your spirits therein?
Have ye drunk of the water of the rock?
Have ye seen the serpent lifted up, and felt the healing thereby?
Have ye witnessed the pillar of cloud by day, and the pillar of fire by night,
to be your defence and leader?
And have ye now at length received the kingdom of life, and set under the shadow of it,
drinking water out of your own cistern,
and eating under your own vine and fig-tree the fruits of the good land,
after the shaking of that which was to be shaken; now being come to,
and enjoying the kingdom which cannot be shaken?
Have ye really felt these things, or have ye been in the dreams and imaginings about them?

[.numbered]
_Query 7._ Do ye walk in the light of the Lord, as the spiritual house of Jacob is to do?
Have ye received the Spirit?
Do ye live in the Spirit?
Are ye truly united, so as to become one Spirit with the Lord?
Are all the walls of partition broken down?
And is there nothing now between you, but of two ye are made one in that which uniteth?

====

If it be thus with you,
then hold forth the right hand of fellowship to those whom the Lord hath brought hither;
and know and acknowledge that whereby the Lord hath wrought in them.
But if ye be not really in the thing itself,
but only in the apprehensions and conceivings about it,
ye can never so be witnesses concerning these things,
nor concerning the truth whereby God works these things:
and ye will find there is a great gulf between you and us,
which ye cannot possibly pass over, till ye meet with our principle and guide,
and faithfully travel with him in the footsteps of the flock,
that ye may come to the Shepherd`'s tents (even the tents which the Shepherd pitcheth,
and which no man can pitch), and may know the true tabernacle, sanctuary, and temple,
whereof he is the Minister.
