== OF THE CHURCH IN ITS FIRST AND PURE STATE,

IN

ITS DECLINING STATE, IN ITS DECLINED STATE, AND IN ITS RECOVERY

WITH THE WAY OF SALVATION IN THE COVENANT OF LIFE OPENED, AND SOME STUMBLING-BLOCKS REMOVED OUT OF THE WAY OF THE SIMPLE-HEARTED

LIKEWISE SOME QUERIES CONCERNING THE NEW COVENANT WITH AN EXHORTATION TO ALL PEOPLE, BUT MORE ESPECIALLY TO SUCH AS ARE DESOLATE AND DISTRESSED

Whereunto is added

A Visit of tender and upright Love to such as retain any Sincerity towards the Lord

Also a brief Account of the ground of Certainty and Satisfaction, which it hath pleased the Lord to establish in my heart, concerning Religion, and the things of his Kingdom

And a Question answered about the way of knowing the Motions, Doctrines, and Teachings of Christ`'s Spirit

With somewhat relating to the Gospel Rest, or Sabbath

And some Queries to such as complain of want of Power to become the Lord`'s and serve Him

By one who testifieth what he hath seen and heard and tasted and handled of the Word, and Life eternal,

ISAAC PENINGTON

+++[+++1668]

=== THE PREFACE

THE true church is a mystery, and so is the false also;
neither of which the outward eye of man`'s understanding is able to discern;
but he alone who is enlightened and taught of God.
Who can see how the Spirit of God works, changing men`'s hearts,
gathering them into his truth, and building them up into an holy temple in his Son?
And who can discern how the spirit of deceit works with an outward knowledge, doctrine,
and form of religion, persuading or compelling men thereunto,
and so builds up a false church?
Yea, who can tell when the Spirit of the Lord withdraweth from the church,
which was once his, leaving it to the other spirit to reenter and possess;
from which time it becometh a synagogue of Satan?
There was need of the anointing of God`'s wisdom and Spirit
to try Jews and apostles (for there were such,
even in the apostles`' days, as said they were so, but were not);
and there is also need of the same wisdom and spirit to try churches,
whether they be indeed the churches of Christ (in and of his Spirit
and power) or only in the name and outward profession of the thing,
without the nature, Spirit, life, and power thereof.

The apostle Paul (who was the apostle of the Gentiles,
and knew what was likely to be their future state), writing to the Romans, tells them,
that the Gentiles were cut out of the olive-tree, which was wild by nature; and were,
contrary to nature, ingrafted into the true Olive-tree,
and so came to partake of the root and fatness thereof.
But withal he tells them, that unless they did continue in the faith,
and the goodness of God,
keeping out of the highmindedness and conceitedness of their own estate and condition,
in the fear (which makes the heart clean,
and preserves it in the cleanness from that which would defile,
and cause it to depart from the Lord) they likewise should be cut off.
Rom. 11:17, and 20, etc.

Now it would be seriously considered,
whether the Gentile churches did abide in the faith,
and in the goodness and power of the Lord, which gathered them?
Or whether they grew high-minded,
holding their estate in a presumption (as if the promise was so to them,
that they must needs be the church forever) out of the fear,
and so were cast off by God,
and cut off (according to the apostle`'s words) from God`'s Spirit,
and so have not partook of the root and fatness of the Olive-tree, for many generations?
It would also further be inquired (if it prove thus upon true search and examination,
that they have been cut off),
whether they can partake of the root and fatness of the true Olive-tree any more,
till he that cast them off, gather and build them up again?

It is true, there have been witnesses against the corrupt state,
even a seed who have been persecuted by it; and these have, in some measure,
partook of the root and fatness of the Olive-tree, all this time of the degeneration.
But hath the church-state of the Gentiles, which provoked God, and was cast off,
and persecuted the witness of the Lamb, his holy seed, who could not but,
in his nature and Spirit,
testify against their corruption,--have they partook
of the root and fatness of the Olive-tree,
or have they not rather grown up from, and drunk in of,
the sap and juice of another stock?

The same apostle speaks of the man of sin, that wicked one, the son of perdition;
who should get into the temple of God, sit there, and show himself as God;
and yet oppose and exalt himself above all that is truly called God,
and that of right ought to be worshipped. 2 Thess. 2:4.
Now when he gets into the temple,
doth not he leaven it with his wicked spirit, making it become wicked,
like him that sits and reigns in it, and is the head of it?
And doth the church or temple, all the while he sits in it,
partake of the root and fatness of the Olive-tree?
(Of Christ its former Vine, of Christ its former Head?) Or doth it not rather suck in,
and partake of, the venom and poison of this new head?
And how long is this new head, this false head of the church, to sit in the temple?
Is it not from the very time of his getting in, till Christ, by the Spirit of his mouth,
consume and scatter him; and by the brightness of his appearance and coming,
utterly destroy him?
ver. 8.

This is certain (as certain as ever there was a true church in the days of the apostles),
that after the apostles`' days there got up a false church,
which the Spirit of the Lord calls the great whore (indeed she was far bigger,
by multitudes of degrees, than ever the true church was).
This great whore had a golden cup in her hand,
wherewith she made the kings and inhabitants of the earth drunk.
And she sat upon many waters; which waters are peoples, nations, multitudes, and tongues.
Did ever the true church do thus?
That was a little flock, gathered out of peoples, nations, multitudes, and tongues,
reigning in the Spirit and power of the Lord, over them only who were thus gathered;
but never sat upon whole peoples, nations, multitudes, and tongues,
as this great whore hath done. Rev. 17:1-15.

Now it would be worth the inquiry what this cup is (this golden cup,
which appears like gold).
And what this wine is, wherewith she made the kings and inhabitants of the earth drunk.
Ask her, and she will tell you: It is the cup of salvation,
and her wine the wine of the kingdom,
even the doctrine and discipline of holy mother-church; out of which, and without which,
no man can be saved.
But ask the Spirit of the Lord (or hear what the Spirit
of the Lord said to the churches concerning it),
and he will tell you, it is the wine of fornication, the cup of destruction,
full of abominations, and filthiness of her fornication;
and that she shall be so far from saving others,
that she shall be destroyed and perish herself;
and whoever drinks of her wine shall perish, unless he vomit it up again,
and drink of the pure blood of the Lamb after it.
See Rev.
17 and also chap.
18 and chap.
14:9-11.

Now one word, in the love and truth of God, to all that have separated from this church.
Have ye separated fully?
Have ye separated wholly?
Have ye separated from her in nature and spirit?
Have ye waited for the building which God alone can rear;
for the church which he alone can frame?
Or have ye built up another church,
in the resemblance and likeness of that ye separated from?
This is a weighty thing: ye must answer it to God, and stand by his judgment therein.
I beseech you consider it.
"`What will it profit a man,`" saith Christ, "`if he gain the whole world,
and lose his own soul?`" So say I in this case: What would it profit you,
if ye could make your church stand, and be approved in the sight of the whole world,
if the Lord disown and disallow it, and they that are gathered into it perish by it?
If it be not of God`'s building, if it have not his presence, virtue, Spirit,
and power in it, it cannot save.
Oh, hear, hear! for the Lord will strip Babylon,
and fill her with dreadful plagues and judgments; and she shall appear naked as she is,
and become the scorn of every eye, and the reproach of every beholder:
and that which hath been reproached, scorned, hated, and persecuted by her,
the Lord will honor.

Now consider, and wait on the Lord, to know the extent of Babylon;
that ye may not be found by the Spirit of the Lord (nor by his angels,
which pour out his plagues upon her) within her limits.
For the great whore is not Babylon only, or alone; but she is the Mother of harlots,
and all her daughters are harlots also; even all that have built up churches,
like her (in her spirit, with her materials) out of the leading, guidance,
and power of the Spirit of truth.

=== OF THE CHURCH

==== I. Of the CHURCH in its First and Pure State, when it was clothed with the Sun, had the Moon under its Feet, and was crowned with a crown of Twelve Stars, travailing to bring forth, and brought forth the Man Child, which was to Rule all Nations with the Rod of Iron

IT pleased the Father to send his Son into the world (in his name, power, and authority),
to gather out of the world;
and to manifest his name to the men whom he should gather out of the world.
The Jews, for all their great profession, and high esteem of themselves,
were but a worldly polity, having but worldly,
elementary shadows of the good things to come,
and to be set up in the kingdom of the Messiah.
John preached that, the kingdom was at hand; Christ said, John prepared for it;
Christ brought it.
He came in the Spirit, in the life, in the virtue, in the dominion of the Most High;
and he gathered disciples unto him, by the word and power of the Father.
And those that continued in his word, were his disciples indeed; of his gathering;
such as the Father had sent the Son out to seek; even the new sort of worshippers,
who should worship neither at Samaria, nor Jerusalem;
nor with reference to any other outward place; but in Spirit and in truth.
They should meet together in that name, wherein Christ had gathered them; and meeting so,
he would be in the midst of them, and they should feel the presence, power,
and authority, which belonged to his church.

Now, if any would know what kind of persons these disciples are,
Christ giveth many descriptions of them.
They are such as are born from above,
such as are changed by the name and power which gathers them.
They are Jews inward, circumcised inwardly; such as are baptized with the Holy Ghost,
and with fire; squared stones, hewn by the Spirit, for the spiritual building; not old,
rough, fierce, cruel, implacable, unregenerate, unholy spirits; but meek, gentle, lowly,
tender, poor in spirit, merciful, peaceable in themselves, and making peace among men,
renewed, and sanctified in spirit; holy in conversation,
suffering (both from the heathenish,
and from the worldly-professing spirit) for that power of truth and righteousness,
which they profess and bear witness to.
They are the salt of the earth, having that in them which seasoneth their own hearts,
and which hath virtue in it to season others.
They are the light of the world, having that in them which casts rays of light,
conviction, and demonstration, wherever they go.
They being changed into the leaven of the kingdom, become a leaven,
and so a weight upon iniquity; testifying against, yea, bowing down and afflicting,
that spirit, as the power of life springs in them and breaks forth through them.

Now, if the church be thus; if it be a gathering by the power into the power; by Christ,
who came in the name, into the name in which he came;
must not the ministry needs be much more thus?
Must not they be grown in the name, be grown in the power,
who are to minister to those who are gathered into the name,
who are gathered into the power?
Must not they be well grown in the Spirit, if they be able ministers of the Spirit?
Did not Christ, when he sent out his disciples to preach in his name,
give them of his Spirit and power?
And afterwards, when he was to go away, and they to succeed him,
what were they to succeed him in?
Were they not to succeed him in his Spirit and power?
And did not he bid them wait for it, and receive it,
before they went forth to preach and set up his kingdom?
And was it not by this the church was gathered?
And can the church be preserved by any thing beneath this?
Yea, falling short of this, is it not in a degenerated and fallen estate?

After that those who had been gathered in the name, had waited as Christ directed them,
for the holy Spirit and power, and after it had fallen upon them, then the glory began,
then the ministry shined,
then the church (or people gathered in the Spirit and power) shined;
then great life was in them all, then great grace and holiness was upon them all;
then faith (which springs from the Spirit and power) was fresh, then love abounded;
then they minded not earthly things, but the kingdom, the life, the glory,
which was come upon them in power; then Satan`'s kingdom fell down like lightning,
and they went on (in and with the Spirit which led them) conquering the Jewish professors,
and the heathenish worshippers also;
none being able to resist the power and Spirit wherein they spake and ministered.
Read the scriptures of the New Testament,
and wait on God for the opening of the true eye in you,
and these things will be manifest and plain to you therein; for the sweetness, freshness,
preciousness, and beauty of that state, may abundantly be read there,
by those whose eyes the Lord opens.
To instance in some places.

Peter writes two general epistles,
in one whereof he speaks of their having received like precious faith with them, 2 Pet. 1:1.
and in the other,
that they did rejoice with joy unspeakable and full of glory. 1 Pet. 1:8.
Yea, he speaks also of their being as lively stones,
built up a spiritual house, a holy priesthood (mark;
all God`'s people who are gathered into the name, who are of the faith,
who are in the life and power, are priests unto him), to offer up spiritual sacrifices,
acceptable to God by Jesus Christ. 1 Pet. 2:5.
Now, was it a small thing to be a priest under the law,
to offer up the outward sacrifices thereof?
What is it then to be a priest in the Holy Spirit and power of life?

John also writes a general epistle,
wherein he divides Christians into three estates,--children, young men,
fathers,--speaking great things and glorious of them all.
He said, "`The darkness is past, and the true light now shineth,`" Paul had said,
The night is far spent, and the day is at hand; but he said, the night is past,
and the day is come. 1 John 2:8.
And he writes to all,--children, young men,
fathers,--as being passed from the darkness, and in the light of the day.
The little children had had their sins forgiven them for his name`'s sake,
and had known the Father.
ver. 12-13. The young men were strong, and the word of God did abide in them,
and they had overcome the wicked one.
ver. 14. The fathers knew him that was from the beginning, ver. 13-14. and knowing that,
they knew enough; for that was it which appeared to save,
and that was it which was to be preached, even that which was from the beginning,
the light which was with God, the light which was in God, the light which was God,
in which is no darkness at all.
chap.
1:1,5. Yea, the little children had an unction from the Holy One,
and they knew all things; and John wrote not unto them as not knowing the truth,
but because they knew it, chap.
2:18-21. Yea, they had received the anointing, and it did abide in them,
and they needed not that any man should teach them,
but as the same anointing taught them of all things; and it so taught them,
as that no seducer nor antichristian deceiver could impose or prevail upon them,
they keeping to it.
ver. 18, 26-27. What a glorious state was here,
when the little children were thus advanced in the strength and power of life!
Sure that promise was now made good indeed,
"`Ye shall be all taught of God,`" when the little children were thus taught.
Yea, and they were taught to abide in him, so as they might not sin; for how could they,
the anointing abiding in them, and teaching them of all things,
and they being in subjection thereto;
for that preserves out of sin the vessel in whom it dwells and reigns.
Sin is a transgression of the law; but they that are in the anointing,
taught by the anointing, subject to the anointing,
are far above the righteousness of the law, even in the righteousness of the Son;
the righteousness of whose nature is far above the
righteousness which the law requires of man`'s nature.
And let men talk and imagine what they will,
the sinner is not in the redemption and power of righteousness which is by Jesus Christ.
For that which is born of God doth not commit sin,
but the seed remaineth in him which is born of God,
preserving him from the nature and spirit of the devil,
and from the works which flow from that nature and spirit, chap.
3:4, etc.
Yea, they might so walk as that their hearts should not condemn them;
but that they might have confidence towards God.
ver. 20-21. And as Christ said to the Father, "`Father,
thou always hearest me;`" so could they say, "`Whatsoever we ask, we receive of him,
because we keep his commandments,
and do those things that are pleasing in his sight,`" ver. 22. even as Christ had said,
"`He that sent me is with me,`" etc.,
"`for I do always those things that please him.`" John 8:29. Yea, these little children,
having received the anointing, were able to try spirits,
and had tried and overcome them (notwithstanding
the subtlety and strength of all their deceits),
because that light, life, Spirit, and power which dwelt within them,
was greater than that which was in the world.
chap.
4:1,4. And can the less overcome the greater, the greater keeping to its strength?
Nay, nay: these that are of the love, and dwell in the love, are,
by the power and virtue of the love,
kept out of all the snares and devices of the enmity;
for the enmity cannot enter the love, nor the soul that abides in the love;
but only him that departs out of it.
Here is a munition of rocks, here is safety indeed; let him that hath an ear hear,
and let him that hath a spiritual eye read and consider.
What should be said more of them?
They were in the love which keeps the commandments,
of the birth to which the victory is given, and in the faith which gives the victory.
chap.
5:3-4. Yea, did they not so keep themselves, as that the wicked one could not touch them?
ver. 18. How could he, when they had overcome him, and abode in that which overcame him?
Satan falls like a flash of lightning before the power of truth, before the living faith;
the faith which is from and stands in the power.
And if the devil would fly from those that resisted him,
how much more would he fly from those that had overcome him,
and stood armed with that armor which is painful and dreadful to him!

Again, the apostle that writeth to the Hebrews,
speaketh of their work and labor of love (which advanceth
the soul apace towards the kingdom),
and of their patient enduring the trials, persecutions, afflictions, and crosses,
through which perfection is attained. James 1:4.
Heb. 6:10. and chap.
10:32-33. Yea, he speaketh expressly concerning them, that they were come to Mount Zion,
and to the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels;
to the general assembly and church of the first-born which are written in heaven,
and to God the Judge of all, and to the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling, chap.
12:22-24. and that they had received, or were receiving,
a kingdom which could not be moved.
ver. 28.

There is another place in my heart to mention, which speaks great glory and a high state,
in the sense of my spirit, attributing glory and dominion to Christ for his loving them,
and washing them from their sins in his own blood,
and making them kings and priests unto God and his Father. Rev. 1:5-6.
What is he who is both a king and priest to God?
Surely he is washed, surely he is clothed with the priest`'s raiment,
surely he is in the dominion and purity of life,
who reigns and offers up therein holy sacrifices to the Father.

Thus far have instances been given in reference to the general state.
Now it is also in my heart to give some instances in particular churches,
wherein testimony is given to the freshness of life in them,
and of their precious state therein.

First, I shall instance in that church at Jerusalem:
in what a beauteous glory and lustre did they spring forth!
Acts 2:41, to the end.
Consider the place well, and tell me,
if this was not the beginning of the spiritual and heavenly Jerusalem;
if the glory of it did not descend upon his new-gathered people and converts?
So likewise see chap.
4:31, etc.

The church at Rome, the apostle Paul says, were beloved of God;
and that their faith was spoken of throughout the whole world. Rom. 1:7-8.
Now what a glorious precious state was this!
For by faith is water drawn out of the wells of salvation: and how much might they draw,
who abounded in faith!
True faith springs from the power of life,
and it brings the power of life into the soul in which it springs,
according to the degree and growth of it.
He that is beloved of God, and abounds in faith towards him, what glory, what life,
what virtue, what power can he want?

The same apostle, writing to the church at Philippi, saith, he did thank God,
upon every remembrance of them: making request for them with joy always,
in every prayer of his for them all,
for their fellowship in the gospel (which is power and life to
them that have fellowship therein) from the first day until now. Phil. 1:3-5.
And he calls them dearly beloved and longed for, his joy and crown.
chap.
4:1.

So writing to the saints and faithful brethren at Colossus,
he gives thanks for their faith, and their love to all the saints, chap.
1:3-4. And saith further concerning them,
that the word of the truth of the gospel had brought forth fruit in them,
since the day they heard and knew the grace of God, in truth.
ver. 5-6. To what then were they grown?
Surely very far into the mystery of life in Christ;
in whom they had been circumcised and baptized, and were complete, abiding in him,
and drinking in of the life, virtue, and power which floweth from him.

Likewise he writes to the church of the Thessalonians, as being in God the Father,
and in the Lord Jesus Christ. 1 Thess. 1:1.
Ah! how excellent and glorious was the state and condition of Christ,
to be in the Father!
How glorious is the state of that church, which is both in Christ and in the Father!
He speaks also of their work of faith, and labor of love, and patience of hope.
ver. 3. Yea, he writes to them again as such. 2 Thess. 1:1.
Surely they did abide in the vine;
they did dwell in the name and power into which they were gathered;
and so did feel the dews from above, and the springs from beneath;
so that their faith did grow exceedingly, and their love abound;
and the apostles did find cause of glorying in them, in the churches of God,
for their patience and faith in all their persecutions and tribulations that they endured.
ver. 3-4.

Writing also to the Ephesians,
he giveth a high expression of the goodness of God to his people in those days,
and of the blessedness of their estate,
in that God had blessed them with all spiritual blessings, in heavenly places in Christ,
chap.
1:3. That is hard to be understood; yet this may be sensibly said:
in the heavenly places in Christ, the spiritual blessings are received;
and they that are raised together with him, and live in and with him,
do also sit with him in the heavenly places in him,
even in the mansions which he hath prepared, and is preparing;
for he raiseth the soul higher and higher, from glory to glory, at his pleasure.
The apostle also saith that they were fellow-citizens with the saints,
and of the household of God; and were built together in Christ, for a habitation of God,
through the Spirit.
chap.
2:19,22.

So the church of Smyrna; Christ owneth her works, and tribulations, and poverty,
and pronounceth her rich. Rev. 2:8.
Christ knoweth how to value things.

And the church of Philadelphia was in a very precious state indeed;
Christ owning her works, and having set before her an open door, which no man could shut;
and promising to make those who made a profession
of the truth (of being Jews) but were not in it,
to come and worship before her feet, and to know that he had loved her;
as also that he would keep her in the hour of temptation,
because she had kept the word of his patience. Rev. 3:8.
etc.
Thus it is manifest that the church in general, and many churches in particular,
was once in a pure, fresh, living, powerful, glorious state.

==== II. Of the Church in its declining and falling Estate

BUT all the churches were not thus; nor did those who were thus always continue thus:
but there was a declining and falling from this glorious estate by degrees,
even from the light, brightness, purity, and power of the day,
into the darkness and corruption of the night again.

And thus the apostasy came in; to wit, by not keeping to the anointing,
by not abiding in that Spirit, life, and power whereinto they were gathered;
by not keeping singly to the voice of the Shepherd.
For then another ear got up in them, and that itched after new and strange things;
not being contented with the simplicity of truth which is in Christ,
with the plain heavenly bread.
For truth is a naked simple thing to look at; not answering man`'s wisdom at first,
nor ever afterwards: but in the cross to that, its power is felt, and its beauty seen.
But if the wisdom of man get up from under the cross,
if it be not still kept down by that, it will presently be judging the wisdom of God,
and the plain way of truth, foolishness, and be listening after somewhat else.

Thus the church of Corinth, who did abound in spiritual gifts, yet were apt to run out,
and be lifted up above their measures, and think they reigned as kings,
without (if not beyond) the apostles;
and so came into danger of hearkening to false spirits and ministers of unrighteousness.
1 Cor. 4:8, etc. 2 Cor. 10:11.

And the churches of Galatia, which began well, and very zealously,
even so as they could have plucked out their eyes for Paul`'s sake;
yet were afterwards so far bewitched and prevailed upon,
that the apostle professed he stood in doubt of them,
and was afraid lest he had bestowed upon them labor in vain. Gal. 4:11,20.

When the enemy could not prevail in open battle, by manifest afflictions, oppositions,
persecutions, etc., then he tries by deceit, getting into the form,
to see what he can do there, how he can please and satisfy men therewith,
and so work them from that power which redeems.
And those that do not eye the power, keep to the power, walk in the power,
and judge by the power, to be sure he catcheth this way.
"`The false prophets,`" saith Christ,
"`which come in sheep`'s clothing,`" (with the good words, as ministers of Righteousness;
but not with the living,
powerful fruits of righteousness) come with so subtle an appearance, as,
if it were possible, they would deceive the very elect:
but God keepeth that eye in his elect open, which cannot be deceived; but all else are.
They that depart from the power, they that err from the faith,
they that are in the highmindedness and conceitedness,
out of the fear,--they easily hearken to seducing spirits, and drink of their poison.
And Peter plainly foresaw that these would be many. 2 Pet. 2:1-2.

See also what complaint Paul makes to Timothy,
about the declining of many from the truth;
he exhorts him to "`keep faith and a good conscience; which some having put away,
concerning faith have made shipwreck;
of whom is Hymeneus and Alexander.`" 1 Tim. 1:19-20.

Again, he speaks of some that were "`already turned aside after Satan.`" chap.
5:15. And of some that had "`erred from the faith,
and pierced themselves through with many sorrows.`" chap.
6:10. Again:
"`All they which are in Asia be turned away from me.`" 2 Tim. 1:15.
Likewise he speaks of some,
who "`would increase unto more ungodliness,`" and whose
word "`will eat as doth a canker,`" chap.
2:16-17. and that "`evil men and seducers shall wax worse and worse,
deceiving and being deceived.`" chap.
3:13. Yea, "`the time will come,`" saith he,
"`when they will not endure sound doctrine.`" chap.
4:3. "`Demas hath forsaken me,
having loved the present world.`" ver. 10. "`Alexander the coppersmith did me much evil:
the Lord reward him according to his works.`" ver. 14. "`At my first answer,
no man stood with me, but all men forsook me.`" ver. 16. Surely love was grown very cold,
iniquity likely to abound, and the apostasy from the truth to increase.

And among the churches of Asia, how many of them were warping!
Ephesus, though she had much good remaining in her, yet she had left her first love,
and was fallen from her first state and works, Rev. 2:4-5.
Pergamos also had them which held the doctrine of the Nicolaitans,
which thing Christ hated.
ver. 15. Thyatira, she likewise suffered the woman Jezebel,
which called herself a prophetess, to teach and seduce God`'s servants.
ver. 20. (Now, this she ought not to have done, the churches having the Spirit,
the holy anointing, to try spirits and prophets by; yea, to try apostles;
which will faithfully discover which are truly such, and which are not,
as ver. 2). Sardis had a name that she lived, but was generally dead;
there being but a few names left in Sardis which had not defiled their garments.
chap.
3:1,4. Laodicea was lukewarm; neither cold nor hot; in the profession,
in the form and appearance of truth; but without zeal, without life, without power.
ver. 15. Now being in this state (having the form and appearance of all),
she judged herself rich, and increased with goods, and to have need of nothing.
ver. 17. This indeed is a pleasant state in man`'s eye, but very loathsome to God,
ver. 16. This church seemed to have all, but indeed had lost all, and wanted the gold,
the raiment and the eye-salve; and so was wretched, miserable, poor, blind, and naked.
ver. 17-18.

In this declining state some fell from the doctrine of truth,
giving heed to seducing spirits, and doctrines of devils. 1 Tim. 4:1.
Some from the fellowship and worship;
it being the manner of some to forsake the assembling themselves together,
Heb. 10:25, which the church, when first gathered, was very diligent in. Acts 2:42,46.
Some held the form of knowledge and profession,
but fell from the life and power. 2 Tim. 3:5.
Yea, many ways did the wolfish,
false spirits drive and scatter from the flock,
as they could get entrance into men`'s minds.

Objection.
But how could the church decline thus in the apostles`' days;
the Spirit of God being so powerful in the apostles,
and being also so generally then bestowed upon believers?
as Gal. 4:6.

Answer.
It is true, they had great advantages of standing,
by reason of the presence and power of the spirit with them.
But yet withal, the Spirit of the Lord is tender, jealous,
and might be grieved and provoked by neglects (his warnings being slighted,
and his motions quenched), and so might draw back from such,
as either received not the truth in the love of it, or grew cold and careless afterwards;
and then the spirit of darkness and deceit thereby had advantage to blind them,
gain upon them, and enter into that part of them,
which the Spirit of the Lord had before recovered and possessed.
Now, the enemy, having got entrance, prevails and captivates more and more,
unless the Lord, in tender love and mercy, visit it again,
lifting up a standard for the soul,
and so drawing it back by degrees into his light and power again.

Besides, it is easy to decline (easy for any soul, easy for any church);
but there is need of much care, fear, faith, obedience, watchfulness to the Lord,
and against the enemy, etc., to preserve and keep the estate of a heart,
or the estate of a church, chaste and pure.
"`Ye are kept by the power of God,
through faith unto salvation.`" Can any thing preserve a soul or church, but God`'s power?
And doth God preserve any soul or church, but in the way he hath appointed?
A church is like a garden, needs digging, dressing, watering, sun-shine,
to cause it to thrive and flourish.
Do not weeds easily spring up in a garden?
yea, ranker weeds than in common ground; which spread apace and over-run it faster,
if it be not looked to and kept by the gardener?
Read the figure, and understand.
Are not spiritual weeds as corrupt and spreading as the outward?
Are they not like leaven; have they not a poisonous, infecting nature in them?
"`Know ye not,`" saith the apostle,
"`that a little leaven leaveneth the whole lump?`" 1 Cor.
5:6. If but one root of bitterness spring up in a church,
it may defile many, and trouble the whole. Heb. 12:15.
And as one corrupted person, so also one corrupted church,
may infect and poison many more.
Yea, was it not thus in the apostasy?
When it once got head, did it not break in and overflow apace?

==== III.
Of the declined and fallen State of the Church

WHEN antichrist (or that spirit which wrought against that spiritual appearance of Christ,
and power of his truth) was revealed, and got into the temple,
appearing and being acknowledged there as God, then, without controversy,
was the declined state.
He had been a long while working under-ground by his agents and ministers,
appearing as ministers of righteousness, in a form thereof, out of and against the power;
but the power (in the true apostles and ministers) stood in his way,
and wrought against him, so as he could not for a long time get up.
Yet he prevailed more and more in the corrupt part in men,
till at length he drew many of the very stars from heaven after him;
and then fighting an open battle, gets rid of the true church,
vomits out a flood after her, as if she were an harlot,
and not worthy the name of Christ`'s spouse, and so gets into the temple,
and is owned there (as Christ) in the stead of Christ.

Objection.
Will any man own antichrist, worship antichrist,
and acknowledge antichrist (instead of Christ) to be God.

Answer.
Read 2 Thess. 2:4. and see if it be not so.
See if he do not get into the temple,
and sit ruling and governing in the temple (that which was once so,
and ought still to be so),
till the very coming and appearing of Christ in his Spirit and brightness.
ver. 8.

Question.
But how could this possibly ever be, or how can it be?

Answer.
He doth not directly get up, nor show himself directly as he is;
but in a mystery of deceit.
He doth not appear as antichrist, crying up all manner of filthiness, abomination,
and contrariety to Christ, in direct words, but as Christ, preaching righteousness,
crying up scriptures, ordinances, church-ministry, holiness, etc.
Yet, for all these words, and fair pretences, he is not the true spirit, but the false,
the antichristian; and those that receive him, or bow to him in any of these,
they bow not to Christ, but to him.
He hath a mark, he hath a name, he hath a worship, he hath a church, he hath a ministry,
he hath laws and ordinances of worship; which whosoever receives,
worships not the Lord Jesus Christ, but that spirit which, under a disguise,
thus appeareth, which hath horns as it were of a lamb, or like a lamb;
but not the Lamb`'s horns, nor the Lamb`'s nature, nor the Lamb`'s Spirit,
nor the Lamb`'s meekness; but the old nature of the dragon,
who gives him both subtlety and power.

Now mark: when Christ brought forth his church, it was a pure, holy, spiritual building,
built up of renewed spirits; such as were new-born, such as were washed,
such as were sanctified, such as were justified in the name of the Lord Jesus,
and by the Spirit of our God.
Christ`'s church was Zion, even the holy seed, built upon the holy hill of God,
into a holy city or temple.
But antichrist`'s church is Babylon, which hath the wisdom and order of man in it,
such as man`'s eye judgeth right, but is foolishness and confusion in the eye of God.
Now, the Lord hath most terrible plagues to pour out upon this antichrist,
and upon his Babylon; yea, upon every one that hath his mark or name,
or that which amounts to his name, though it be not directly so called.
Therefore, oh, fear the Lord God! and ye that love the peace of your souls,
pray to be delivered from that which his wrath is to;
for the dregs of the cup of trembling are to be poured
out on antichrist inward and outward,
and on Babylon inward and outward.
Let him that readeth understand the tender warnings,
which are given forth in the tender nature and Spirit of the Lord;
for the day of mercy spreads apace, and the night of anguish and tribulation hastens.

The true church of Christ was gathered by his Spirit into his name and power,
and was a spiritual building, or building of spirits therein;
wherein the Spirit of the Lord was as present spiritually,
as ever he appeared in the outward temple or ark outwardly.
And the ministers of the New Testament were made by the Spirit,
and sent forth by the Spirit, and in the power.
"`Stephen,`" though but a deacon, "`was full of faith,
and of the Holy Ghost;`" and if any man taught in the church,
he was to "`speak as an oracle of God.`" Flesh is to be silent there,
and only the Spirit`'s voice to be heard in the spiritual building.
But now, in the apostasy, the ministers there, are as wells without water,
clouds without rain, who have only the show of the thing after the flesh,
but not the truth of the thing after the Spirit; and so being not in the thing,
nor in the Spirit, they despise the dominion,
and speak evil of the dignities which are of the Spirit,
and for advantage`' sake cry up the dominions and dignities which are of the earth.

In the apostles`' days, the ministers of the church were not of man,
nor set over the flock by man; but made by God,
and set over the flock as overseers by him. Acts 20:28.
For the same Lord who gave apostles, prophets, and evangelists,
gave also pastors and teachers. Eph. 4:11.
And though the hands of the presbytery
were laid on those that were made ministers;
yet that was not done suddenly, or lightly, but by a guidance of God`'s Spirit;
and there went a gift and power of the Spirit along with it,
according as Paul said to Timothy: "`Neglect not the gift that is in thee,
which was given thee by prophecy,
with the laying on of the hands of the presbytery.`" 1 Tim. 4:14. But now,
in the declined, fallen estate, there is no such thing; but an empty form,
a form of worship, a form of godliness, a form of ministry, a form of doctrine,
a form of discipline; without the life, without the Spirit, without the power,
from which the true form came, and whereby alone it could be preserved.

This declined state hath been a very sink of iniquity,
wherein the Christian love hath not only grown cold, but hath been quite dead,
and plucked up by the very roots; yea,
wherein all that filthiness which was sprouting forth and
getting up in the declining state hath reigned in power,
defiling the very name of Christianity, oppressing the good seed,
and corrupting the earth.
Read 2 Tim. 3:2, etc.,
and see what a generation of Christian professors were to
grow up (and did grow up) in the time of the apostasy.

==== IV. Of the State of the Church in its Recovery; or what State the Church shall be in after it is recovered out of the Apostasy.

THE state of the church after the apostasy,
is to be like the state it was in before the apostasy, for purity, power, brightness,
and glory, etc.; yea, shall it not be more glorious,
after its coming through all this darkness, and shining over it, than it was before?
The New Jerusalem is to come down from God out of heaven;
the bride is to be clothed and adorned as the Lamb`'s wife,
meet for the delight of her husband.
The power and Spirit of the Lord, which cleanseth away all this rubbish,
will make his truth shine, his church shine, his suffering lambs,
that come out of the great tribulation, shine more than ever before.
The Lord God Omnipotent will take his great power unto him to reign,
and will reign according to his power in the hearts of his children, and over the earth.
He will break that which stands in his way with a rod of iron;
and he will embrace and exalt that which boweth to and kisseth the sceptre of his Son,
who is to appear upon the holy hill of Zion: and the law is to go forth out of Zion,
and the word of the Lord from Jerusalem;
the power whereof shall break down the power of iniquity,
and bring up the suffering seed into the dominion and glory of life.

In this restored state antichrist shall be worshipped no more, nor the beast,
nor the dragon, who gave his power to the beast;
but the Lord God shall be worshipped and magnified over all.
It shall be said no more, Who can make war with the beast?
after the Lamb hath overcome him; but, Who is like to thee, O Lord,
O King of saints! who hast taken to thee thy great power, and hast reigned,
and dost reign; who hast brought down this lofty city,
and trod it under the feet of the poor, and made the steps of the needy to pass over it;
who hast made it an heap, (the city fenced by all the might, wisdom, and power of man),
a ruinous heap, a place no more for thy dear children to be captived in and oppressed;
but a habitation of dragons,
and a cage of every unclean and noisome bird forever?--Who shall not fear thee, O Lord,
and glorify thy name?
For thou only art holy; for all nations shall come and worship before thee;
for thy judgments are made manifest. Rev. 15:4.
Thou hast judged down Babylon, which was exalted; thou hast pitied Zion,
which lay in the dust for many ages and generations,
and hast raised up thine holy building again,
and wilt give to thy children to be clothed,
and to walk before thee in pure white linen (which is the
righteous nature and Spirit of thy son) forevermore;
and the darkness shall never come over them again, but the beast, dragon,
and false prophet shall be cast into, and bound down in, the lake;
and the springs of life shall open, and whosoever will may come freely,
and drink of the water of life.
And the people in heaven shall say, "`Hallelujah! salvation, and glory, and honor,
and power unto the Lord our God.`"

And the voice of great multitudes, and the voice of many waters,
and the voice of mighty thunders, shall say, "`Hallelujah!`" and shall be glad,
and rejoice, and shall give honor to the Lord, for the bride`'s marriage with the Lamb,
and for her rich adorning for her bridegroom.
Yea, the earth shall rejoice, and the multitudes of the isles be glad.
Why so?
Because the Lord reigns, who is tender even of the earth,
and hates the oppressing not only of his seed, but also of his creatures:
for he will reign and judge in righteousness, and tenderness,
and much mercy to all that is of him; and none shall feel his judgment and severity,
but that which is contrary to him, and joineth to his enemy.
For the Lord will make war with that spirit, which is contrary to his life and nature,
forever and ever.
And he that joineth to that spirit, shall find woe, misery,
and tribulation (tribulation and anguish shall light
upon every soul that continues in the evil doing);
but he that comes from under that spirit by the leadings of God`'s Spirit,
bowing to and kissing the Son, shall taste of the Father`'s love to the Son,
and partake of the mercy, peace, and reconciliation which is treasured up in him.
Amen.

=== THE WAY OF SALVATION IN THE COVENANT OF LIFE OPENED / And some stumbling-blocks removed out of the way of the Simple-hearted

THERE are many whom the Lord hath raised up,
in this day of the manifestation of his power, and of his everlasting love,
to bear witness to his truth; among whom I also (who was an outcast,
and miserable beyond expression) have obtained mercy to partake of the virtue, life,
and power of his precious truth, which redeems from the bondage of sin and iniquity;
and am also many times moved by the Lord to testify
of that which he hath made known unto me,
and given me to experience.

This brief touch sprang in me by way of preface.
Now to the thing itself.

The Father, in whom is the whole virtue and power of redemption,
sent his Son to gather the scattered and lost sheep of the house of Israel;
and not only so, but he gave him also for a light to the Gentiles,
that he might be his salvation to the ends of the earth; and sending him,
he sent his Spirit and power with him:
for that which is begotten by the Father is not able to do the work,
unless anointed and assisted by the Father: therefore the Father,
who sent him to preach the gospel, anointed him, and filled him with his Spirit,
that he might preach the gospel according to that scripture, Isa. 61:1-3:
"`The Spirit of the Lord God is upon me,
because the Lord hath anointed me to preach good tidings to the meek;
he hath sent me to bind up the brokenhearted, to proclaim liberty to the captives,
and the opening the prison to them that are bound;
to proclaim the acceptable year of our Lord, and to comfort all that mourn,`" etc.

Question.
But how came these meek, these brokenhearted, these captives, these bound in prison,
these mourners,
to meet with the redemption and blessings which he is anointed to preach to them?
Or which way do they come to receive and partake of them from him?

Answer.
In faith.
This all his outward healings did signify, being thus dispensed.
("`If thou wilt believe, thou shalt see the glory of God.
Thy faith hath made thee whole.
O woman! great is thy faith! be it unto thee according to thy faith.`") And thus
all his inward healings are bestowed upon and received by the soul;
to wit, in the faith.

Question.
But how came they to have faith?
Or how cometh any man to have faith in the redeeming power?

Answer.
It is bestowed upon them by God, in the sense which is from him.
His Word goeth forth from his mouth; there is a witness of him in the heart,
towards which it reacheth.
Now, it reaching to the witness, immediately it brings into a sense,
and in that sense begets faith;
and being mixed with this faith (which is of its own begetting) in them that hear it,
begins the work of life and redemption in that heart where it is not yet begun,
or carries it on in that heart wherein it is already begun.
Thus faith hath a work,
a work from the beginning of the heart`'s turning to God even to the end;
which he that abides in the faith till the end, finds accomplished.

Objection.
But this faith is bestowed on some few whom God hath elected, not on all men.

Answer.
God hath sent his gospel to be preached to every creature,
and his Word is able to reach the witness, and work sense in every creature;
and in whomsoever there is a sense wrought, they listening to God in that sense,
he works faith in them; and waiting on the Word, hearkening of the Word,
and staying their minds there through on the Lord, he will speak peace to them,
and keep them in peace,
daily removing them more and more out of the reach
and power of that which troubleth them.

Question.
Doth the new covenant lay all upon God, and require nothing of the creature?
Or is there something required by God of the creature,
in and by virtue of the new covenant?

Answer.
Consider well;
Doth not God require of the creature in the new covenant what he gives in the new covenant?
Doth he not require the faith, and the exercising of that faith,
which he himself works and gives in the sense,
from the power and demonstration of his truth, to the soul?
The new covenant requires more of the creature than ever the old did;
but it requires them not of the creatures as weak in the fall,
but as taught (strengthened and enabled) to walk with God in and by virtue of the covenant.
Yea, all manner of holiness, and righteousness of heart, life,
and conversation is required in and by the new covenant:
for as the Lord works out of all therein in the creature,
so the creature works out all thereby in the Lord, according to that known scripture,
"`work out your own salvation with fear and trembling: for it is God which worketh in you,
both to will and to do of his good pleasure.`" And as the
creature is able to do nothing that is good of itself;
so being grown up into the life and ability, which is of God,
it is able to do all things through Christ that strengtheneth it.

Question.
But why is it said that Christ was anointed to preach the gospel to the poor, the meek,
the brokenhearted, the captives, the bound in prison,
the mourners (for want of righteousness, life, and peace)?
Did not God give his Son in love to all?
Was he not made a ransom and propitiation for all?
Yea, was he not anointed to preach the gospel to all?
How then comes it here to be thus limited and restrained to some?

Answer.
It is true, God had a general respect to mankind, in the gift and anointing of his Son:
but yet there are some in a better capacity to receive;
already in the sense of the want of him, and panting and longing after him.
Yea, there are some, who are grievously sick in soul, and deeply wounded in spirit;
the sadness and misery of whose condition cries aloud for the help of the physician.
Now the eye and heart of the Lord is more especially towards these;
and so he bids his prophets be instructing and comforting these,
concerning the salvation, the healing, the oil of gladness, the Messiah to come;
and when he comes, he sends him up and down to seek out these,
to keep company with these, to help and relieve these;
having given him the tongue of the learned, to speak a word in season to these weary,
distressed ones.
These are not like the common, rough, unhewn, knotty, rugged earth;
but like earth prepared for the seed, and so easily and naturally receive it.
The gospel is preached to others at a distance; which, it is true, they may have,
if they will hearken to it, and wait for it,
and part with what must first be parted with;
but they have a great way to travel thither.
But these are near the kingdom; these are near that which opens, and lets in life;
these are quickly reached to, melted, and brought into the sense,
in which with joy they receive the faith; and with the faith the power;
which brings righteousness and salvation to their souls.
Though also the enemy is exceeding busy, to darken, disturb, and bow down these;
that he might still keep them in the doubts, in the fears, in the chains, in the fetters,
in the prison-house, from the liberty and healing which the word of the anointing brings.

Now mind.
God is real towards all; he desires the life and salvation of all;
not the destruction of any one soul that ever he created: it is unnatural to him.
And the way that he holds forth, he stands ready to meet any man in.
Whom is it that he doth not draw?
And who is it that may not come in the drawing?
Is not his word a hammer?
And whom can it not break?
Is it not fire?
And whose corruption can it not burn up?
Is it not water, wine, and blood?
And whom cannot it wash and nourish?
Therefore, let no man think to lay the blame upon God, because of his perishing;
for he will be deceived therein: and God will prove true, who saith,
Man`'s destruction is of himself; and every man a liar, who layeth any blame on him,
for not giving him further assistance with his power.
Neither let him blame God for hardening him; for God hardeneth no man,
but him who first refuseth and grieveth the power
and love which would melt and soften him.
It is true; we are the clay, and God the potter:
and may not the potter make what vessels he will of his clay?
This parable came from the Spirit of the Lord to Israel of old:
but what use did the Lord make of it?
Did he say to them: Do what ye will; some of you I will cast off,
and others of you I will show mercy to; for I have determined so?
Nay, not so: but I have this power over you; therefore do not provoke me.
+++[+++Read Jer.
18.]
Was not God exceeding tender to the outward people, in that outward covenant?
Did he ever give them up to pain and sufferings,
without great provocations on their parts?
"`He doth not afflict willingly, nor grieve the children of men.
Wherefore doth a living man complain; a man for the punishment of his sins?
Let us search and try our ways,
and turn again to the Lord.`" And the Spirit of the
Lord never failed to do what was his part,
towards the turning them from iniquity, towards the Lord, in that covenant.

And when they did believe, consent, and obey, and did eat the good of the land,
was it not pleasant and delightful to him?
And when they provoked him to jealousy, and drew down judgments upon their heads,
was it not irksome and painful to him?
+++[+++Read Duet. 5:29. Isa.
5+++.+++ Ezek.
20. Jer. 44:4 and chap.
31:20. Isa. 63:7. to ver. 15.]
And will God fail to do his part towards any man for the salvation of his soul,
which is so precious, of so great concern,
and the loss whereof he knoweth to be so invaluable?
No, no; the Spirit of God suffers, in every man upon the face of the earth,
that sins against him;
and is grieved and wounded by their unjust and unrighteous conversations,
from day to day, against the testimony of somewhat of him in them,
which is contrary thereto.
Now this is of a precious nature; and being so despised and rejected by men,
can it be wondered that God doth not proceed to make it more manifest,
and to work more in men by it?
Nay, may it not rather be wondered that God doth continue to manifest it so much?
What man could endure to behold a thing so precious in his
eyes (as this is in God`'s) so continually abused by,
and to suffer so much from, that which is so far beneath it, as God daily doth?
Therefore, if there come a day of reckoning for this,
with all men upon the face of the earth (for who hath not had a talent from God;
even of the pure eternal light in him,
witnessing in his heart and conscience against the darkness?),
there will be no cause of wondering at it.
And is not this light and Spirit (which shines in all men`'s darkness in some measure,
stirring and witnessing against it,
and endeavoring to persuade and draw the mind from it) the very same, in nature and kind,
with the light and Spirit of the Father, which appeared in that person of Christ?
And, if hearkened unto, and followed,
would it not bring into union and fellowship with him,
and into a partaking of the benefit of all he did in that body?
Yea, would not the Spirit reveal whatever is necessary to be known,
to that soul which receives and follows it?
Oh, what hath God done (in his rich and tender mercy towards all) for mankind!
And how clear will he be, when he opens and manifests the righteousness of his judgment!
He will not clear himself after this manner;
that he hath disposed of them to destruction,
according to the power and prerogative of his will;
but that they have run headlong into destruction,
against the light and leadings of his will and power; to which it is natural to save,
but not to destroy.
That is the act which is proper to another nature and spirit, but strange to his.

Objection.
But could not God save any if he would?
Who can resist his will or his power?
Who can stop or resist him in the work of redemption, or destruction?

Answer.
God can so put forth his will and power, as none can resist.
Yea, the will and power of God, which offereth to save, and standeth ready to save,
will bring destruction upon all that so dally with it,
as to neglect and let pass the day of their visitation:
and thus none can resist his will, or his power.
But in the way wherein he appeareth, and hath chosen to work out life and salvation,
Satan, and man`'s corrupt heart and mind,
may and do often resist the will and power of the Lord.
Now, that which resisteth is not of God, but against him;
yet it is the patience of the Lord, to suffer it.
I find drawings in my heart from God, or I durst not open these things.
For I dare not hold out to men what the Lord hath given me to know and experience,
but only what he giveth and chooseth for me to hold out:
and that will be life to them that receive it.
But if I should hold out any thing of myself, that would not reach to life,
but only feed the wrong part in men; and so help to build up that,
which God will again throw down,
before he saves that soul which is built up with
the knowledge of things after this manner.

There is somewhat springs up in my heart,
which may perhaps open this thing further to the minds of some.

Cain was the first wicked man that we read of;
and how tender was God towards him! even him that sacrificed not after the Spirit,
but after the flesh, and slew his brother Abel.
Now, can any man lay Cain`'s wickedness either upon the will,
or upon the decree and counsel of God?
Might he not have done well?
Might he not have sacrificed to God in the faith, as well as his brother Abel?
And if he had done well, and offered in the faith,
had he not found forgiveness and acceptance with the Lord?
God accepteth no man`'s person: God rejecteth no man`'s person;
but there is a seed he hath chosen; and to gather man into this seed,
is his delight and work; as it is the delight, nature,
and work of another spirit to scatter from this seed.

Now, in this seed he doth accept, and not out of it.
Yea, in this seed shall all the families of the earth be blessed,
as they are gathered into and abide in it.
And this seed is a word nigh in the mouth and heart, both of Jew and Gentile; which,
as it is hearkened to, writes the law of the spirit of life in the heart,
either of Jew or Gentile.
And as they become sons, so the Spirit of the Father is poured out upon them;
even the Spirit of adoption, which crieth Abba, Father, either in Jew or Gentile.
And this is the gospel of the kingdom, which is preached more sparingly, or abundantly,
by the mouth of the seed, as the Lord pleaseth.

For God`'s power, wisdom, mercy, love, goodness, patience, long-suffering,
etc. is his own; and he may sow of it, or exercise it, more sparingly or abundantly,
as he pleaseth.
Yea, he doth exercise it more abundantly towards the vessels of mercy;
so that the cause of their salvation doth not so
much arise from their embracing of mercy,
as from God`'s exercising of it.
He visiteth nations as he pleaseth, and persons in nations as he pleaseth;
and who may say unto him, What dost thou?
Why art thou so good and kind here?
or, Why art thou so sharp and severe there?
But still in the way, and according to the path, of the covenant, doth the Lord walk,
in and towards all: and his mercy endureth forever towards the seed of the righteous,
and his justice and indignation forever towards the seed of the evil-doer:
and man (simply considered) is not either of these; but as he is gathered into,
and brought forth in, the root and spirit of either of these.
Now, every man hath a day for the life of his soul; and power and mercy is near him,
to help him to travel from death to life.
Happy is he who is taught of God to make use of it.

And let not men puzzle themselves about the mystery of election and reprobation;
which cannot be understood by such as are out of the thing wherein it is made manifest.
Only thus at present: Pharaoh and Israel, Esau and Jacob, Ishmael and Isaac,
etc. were parables, signifying somewhat inward.
What was Pharaoh?
Was he not the oppressor of God`'s Israel?
What was Esau?
Was he not the first birth, which sold the birth-right and inheritance?
What was Ishmael?
Was he not the birth after the flesh?
These are rejected, and cast off by God forever; and the spiritual Israel,
the spiritual Jacob, the spiritual Isaac, are accepted.

Shall I speak out this thing yet more plain?
Why thus then: it is not the creature which is rejected by its Maker;
but somewhat in the creature, and the creature in that.
Nor is it the creature (simply) which is elected; but somewhat in the creature,
and the creature in that.
And as any man comes into that, the election is begun in him:
and as any man abides in that, he abides in the election:
and as that is made sure to any man, his calling and election are made sure to him.
But as any man departs from that, he departs from the election into the reprobation:
and going on in that into the full impenitency and hardness,
he will forever miss of the election; and the reprobation,
and sealing up to condemnation, will be made sure to him.
For God is no respecter of persons; but everywhere, he that receiveth his holy seed,
and therein worketh righteousness, is accepted of him.
And he that receiveth the wicked seed,
and therein worketh wickedness and unrighteousness, is with it rejected.

Objection.
But (may the honest heart say) this may be truth for aught I know;
but indeed I did not apprehend things to be so:
for I thought man and his works had been wholly excluded by the covenant of grace;
but this seems to take both him and them in upon a consideration.

Answer.
Man is wholly excluded the covenant of grace, as in himself; as he stands in himself,
and in his own ability,
out of the newness of life and ability which is of the new covenant.
But he is not excluded as he is renewed, and receiveth a new being, life, virtue,
and ability, in the new covenant.
But here much is required of him; and whatever he thus doth is owned, acknowledged,
and accepted by God.
Here the true Jew hath praise of God.
He is commended for his faith, and for his obedience in the faith:
for his loving the Lord his God with all his heart, and his neighbor as himself:
for his washing his garments in the blood of the Lamb,
and keeping them clean in the same blood, while others defile theirs:
for his merciful nature and actions to Christ in his members,
while others are rough and cruel: for his watching against snares and temptations,
while others are running into them: for his crucifying that in himself,
which others feed in themselves: yea,
for his denying and turning from all ungodliness and worldly lusts, even of the flesh,
eyes, and pride of life;
all which are not of the Father (whom he is born of and seeks after),
but of the spirit of the world, which the earthly-minded man is born of,
and seeks to please.
So that (mark) though man is excluded in his corrupt nature and state,
yet not the new man, not man in the regeneration.
But man must be regenerated; and thus man must enter into the covenant of life;
and thus man must abide and be found in the covenant of life, in the nature,
in the righteousness, in the holiness, in the power thereof, if ever God own him.

Objection.
But this seems to lay difference on man`'s act, and not wholly on the grace of God.
For the grace, in itself, is equally powerful towards all; but it is my receiving of it,
which maketh it effectual unto me; which others not receiving, it is not so to them.

Answer.
The grace, in itself, is of its own nature everywhere.
This is true.
And that it hath power in it everywhere, and that this power is over and above sin;
this is true also.
But yet there is a greater or lesser proportion of it given,
according to the pleasure and good-will of the giver:
and according to the measure of it (which is freely given),
and the soul`'s growth therein, so is the power of it manifested in the heart.

Now, the difference in every man is by the grace: not of himself;
for he can do nothing that is good, as of himself; but only by the grace,
which is alone able to work that which is good in him, and to cause him to work in it.
Yet thus it is: as the grace reacheth to him, draweth him, quickening and causing him,
in the virtue, life, and obedience of the grace, to answer the grace;
so doth the work thereof go on in him.
And there is matter of condemnation to him who doth not answer the grace;
and there is matter of justification and praise to him who doth answer the grace.
Yet this whole ability arising not from himself, but from the grace,
the acknowledgment of what is effected thereby doth of right and due belong to the grace.
And therefore they who are justified, sanctified, and crowned by the grace,
do of right and due cast their crowns at the feet of the Lamb, at the throne of grace;
giving honor and glory to him who is worthy,
and to his grace which hath wrought all in them.

Now, if any man would know this thing groundedly and certainly,
let him not run into disputes of the mind and brain, but come to heart experience.
Hast thou ever found the work of God`'s grace in thy heart?
Hast thou found thy heart, at any time, believe and obey,
in and through the strength of the grace?
Hast thou found thy heart, at another time, negligent of or rebellious against the grace?
When thou were rebellious, wert not thou condemned, and that justly too?
When thou didst believe and obey, to whom did the honor thereof belong?
to thee, or to the grace?
Canst thou answer this?
Why, as it is in thyself, between thee when obeying and disobeying,
the same is the state of the case between godly and wicked men.
There was a difference between thee when thou obeyedst the grace,
and when thou disobeyedst it: so is there between the unregenerate and regenerate.
When thou obeyedst not, that which called for obedience condemned thee; so it doth them.
When thou obeyedst, thou didst sensibly feel the praise was not thine,
but belonged to the grace which wrought in thee; so is it also in the regenerate,
in whom the Lord works by his grace, and who work out their salvation through him,
and make their calling and election sure in him.
Leave brain knowledge,
and come to true sense (where the mysteries of God are made manifest),
and this will soon be easy and clear to thee.
But these things were never intended by God to be found out by man`'s disputing wisdom;
for God, who giveth the knowledge, hideth them from that part,
and giveth them to the innocent, simple birth of his own Spirit.

Objection.
But when the Father draweth, can any man resist or hold off?
Doth not the power of the Lord make any man willing, whom he exerciseth his power towards?
And is it not thereupon said, "`Thy people shall be willing in the day of thy power`"?

Answer.
The power of the Lord is great, and hath dominion over all evil spirits that can tempt,
and over all the corruptions, backslidings, and withdrawings of the heart.
But the Father doth not save man by such an absolute act
of his power (for then there would need no more to be done,
but an immediate translating of a man from death to life; which if the Lord please to do,
nothing could come between to hinder);
but the power of the Lord works in and according to the way that he hath appointed.
And in this way the devil hath liberty and power to tempt from, oppose,
and resist the word of God: and they that hearken to him,
and enter into the temptation and snare which he lays, let his power in upon them,
and withdraw from the virtue, operation, and strength of the power of God.
Yet for all this, the Lord not only begins his work,
but also carries it on in the day of his power; giving not only to will, but also to do,
what is right and pleasing in his eyes;
but still in and according to his own way and covenant.

Objection.
And so whereas some men say: If God put forth his power to save,
and the devil interrupt and stop his work;
then it seems that the devil is stronger than God.
Is the devil stronger than God, say they?
If he be not, how can he resist and withstand him in the work of his power?

Answer.
Nay; the devil is not stronger than God; though he is very strong.
But if the heart let in the enemy, grieve the Spirit,
beat back his power in the way wherein it hath appointed to work,
the devil may be more prevalent with him than the power of God.
But in those that believe, and become obedient and subject to the power of God,
his power is far stronger in them to defend and carry on his work,
than the power of the devil is to work against and hinder it.

There are objections also relating to free-will, and falling from grace,
which stick much in the spirits of many, and they cannot get over them;
but it hath pleased the Lord to clear up these things to us,
and to satisfy our hearts concerning them,
so that with us there is no difficulty nor doubt about them.

As touching free-will: We know, from God,
that man in his fallen state is spiritually dead, and hath no free-will to good;
but his understanding and will are both darkened and captivated by the enemy.
But in Christ there is freedom, and in his word there is power and life:
and that reaching to the heart, looseneth the bands of the enemy,
and begetteth not only a freedom of mind towards good, but an inclination, desires,
and breathings after it.
Thus the Father draws, and thus the soul (feeling the drawing) answers in some measure;
and the soul, thus coming, is welcomed by Christ, and accepted of the Father.
But for all this, the enemy will tempt this soul; and the soul may hearken to, let in,
and enter into the temptation, and so draw back from the plough to which it put its hand.
"`Now, if any man draw back, my soul shall have no pleasure in him,`" saith the Lord.
"`And he that putteth his hand to the plough, and looketh back,
is not fit for the kingdom of heaven.`"

So concerning falling away; The Lord shows us what it is that is apt to fall,
and what cannot fall.
Christ cannot fall; and that which is gathered into him,
stands and abides in him (and so partakes of his preservation), cannot fall.
There is no breaking in upon that power,
which preserves in the way that it hath appointed:
but there is a running and perishing out of the way.
Out of the limits of the covenant,
the preservation and power of the covenant is not witnessed.
But in coming to Christ in the drawings of the Father,
in the sense and faith which he begets, and abiding with him that drew,
in the sense and faith which he daily and freshly
begets anew (for he reneweth covenant and mercy daily,
and keepeth covenant and mercy forever) in this is the power felt,
the preservation felt; in this the Father`'s hand encompasseth the soul,
which none can pluck it out of.
Now he that feels and experiences these things every day,
that sees and feels daily how he can fall, and how he cannot fall;
how he meets with the preservation, and how he misses of the preservation;
how he abides in the pure power (which is the limits of this holy covenant),
and how he wanders out of this power, into the limits of another covenant, spirit,
and power; he knows these things, how they are indeed;
whereas other men (who are not exercised in the thing) do but guess at them;
striving to comprehend them in that part which God hath shut out of them.

Now mind a parable, with which I shall conclude this.

Though the natural and outwardly-visible sun be risen ever so high upon the earth,
yet he that is naturally blind cannot see it, nor partake of the light thereof.
So also, though the spiritual Sun, the Sun of righteousness, the Sun of the inward world,
be risen ever so high, and appear brightly in ever so many clouds;
yet they that are spiritually blind cannot discern it,
nor reap the benefits of his light, nor partake of the healing which is under his wings.

=== SOME QUERIES CONCERNING THE NEW COVENANT

Query 1. WHAT is the covenant of hell and death,
which must of necessity be broken,
before a soul can be gathered into the covenant of life?

Query 2. What is the covenant of life and peace, into which God gathers the soul?

Query 3. How doth God gather?
By a mere act of power, which none can resist?
Or in a way wherein his power (though much resisted)
shall prevail for the salvation of those,
who are faithful in the covenant; who come to Christ, abide in Christ,
resist and fight (in Christ) against all that is contrary to his nature and Spirit,
and overcome through him?

Query 4. Are there any terms in this covenant?
Or can there be any terms in this covenant, suitable to the nature of the covenant?
Is believing in the power, as absolutely required in this covenant,
as obedience to the law was under the covenant of the law?

Query 5. If faith in the power, and obedience to the power that redeems,
be required as terms in the new covenant;
yet if they be not required of the creature in its own capacity and ability,
but as strengthened and enabled by the virtue, life, and power of the covenant,
are they not free terms, noble terms, worthy and becoming a free covenant?

Query 6. Is not this the gospel, or new covenant: That whosoever believeth,
and receiveth the baptism of the Holy Ghost and fire,--suffering in the flesh,
and having his sins and corruptions purged away by the spirit of judgment,
and by the spirit of burning, and so walketh no longer after the flesh,
but after the Spirit,--I say, is not this the gospel, or new covenant,
that he that thus believeth, and is thus baptized, shall not be condemned with the world,
but justified and saved by that Spirit and power which cleanseth him?

Query 7. Doth God write his laws in men`'s hearts, or put his fear therein,
or his Spirit within them, causing them to walk in his ways and statutes,
and to keep his judgments, etc.--I say, doth God do this to men out of the faith?
Is not the work of salvation begun in the faith,
and carried on and perfected in the faith?
And he that maketh shipwreck of faith, and of a good conscience,
can he groundedly hope to have the work of salvation carried on in him?

Query 8. Doth not God beget, increase, and perfect the faith,
which is available unto salvation?
Is any man accepted in the faith, which is of his own nature?
Or is the acceptation in and through the faith which is of the Son`'s nature?

Query 9. May the temptations of the devil, with a man`'s hearkening thereto,
hinder God`'s begetting faith in him, or no?
Or if it be begotten, can they hinder the growth and increase of it?

Query 10. When God draws, must a man necessarily come to the Son?
Or may the devil so tempt, and he so hearken thereto,
as that his coming to the Son may be hindered, notwithstanding the Father`'s drawing?

Query 11. Is there not justification to them that receive the seed,
to them that obey the light?
And is there not condemnation to them that refuse the seed,
and obey not the gospel of its salvation.

Query 12. Do men perish for want of power from God?
Or through their cleaving to another power,
and refusing the strength of that which is over that other power;
whose hand would help their souls, and bring them through and over it,
did they receive it, and cleave to it in the way the Lord hath appointed?

Query 13. They that receive the power, believe in it,
and live,--do they do it by their own strength?
Or in the strength and virtue which flows from the power, which enlivens, draws,
and makes able to follow?

Query 14. Those that are weak as to the power,
and in whom the enemy and corruptions are strong,--is the defect on God`'s part?
or on his covenant`'s part?
Or in the way of life,
which he hath pitched upon as sufficient to redeem and deliver fallen man by?
Or is God (and his covenant and way of life) wholly clear of the defect,
and rests it wholly on them?

=== AN EXHORTATION TO ALL PEOPLE, BUT MORE ESPECIALLY TO SUCH AS ARE DESOLATE AND DISTRESSED

Now is the acceptable time, now is the day of salvation.
Now is the life arisen, and now the light shines, to guide out of the darkness and death,
into the land of the living.
Oh awake! ye that sleep in the dust of the earth; arise up from among the dead,
and Christ shall give you light, to walk along in the path of the living.
Come to him whom the Father hath sealed; who is life,
and who giveth life freely to all that come; yea, abundantly,
to those that wait upon him, and walk faithfully in his covenant.
Oh! therefore come into covenant with him; mind the words of his lips, which beget sense,
and in that sense his life stirs,
and in the stirrings of his life the drawings of the Father are felt.
And when the Father draws, he whomever he draws may come; and him who comes,
Christ will in no wise cast out; but receive into his arms, and defend by his power,
against that which would draw or force back from him into perdition.
Therefore hearken to the little movings and stirrings in you,
after that which is eternal; for any desire which is in truth after him,
he will not quench (it is his nature to cherish it);
but he will be a strength and relief to the soul,
against that which would quench and put out the breathings and pantings after him,
that it might still hold the soul in bondage and captivity.
And, people, mind this (it is a true testimony).
The door of life is now so opened, by him who hath the key and power,
that whoever will may enter.
For the power of life is arisen,
against the power of death and the destroyer of the soul: so that great, yea,
very great advantage is there in this day,
to all that are willing to follow the Leader and Captain of salvation,
out of the land of captivity.
Mind but his visits, and be faithful in the strength which flows from him;
and nothing shall hinder thy soul from overcoming what stands in thy way,
to stop thee from attaining the eternal crown and inheritance of life.

And as for you afflicted mourners, who are seeking the way to Zion,
bewailing the absence of your beloved, in whose presence is life and redemption,
resurrection from the dead, and victory over sin; yea, all that your hearts have desired,
or can desire: what shall I say to you?
O my friends, and dear brethren!
May I speak a little freely to you concerning the Lord Jesus?
How that he was born of the virgin Mary, according to the flesh,
fulfilled his ministry and service in the flesh, and was taken up to God;
and how that the same Lord Jesus was afterwards born in Spirit, of the spiritual woman,
the church; even so born as to rule all nations with an iron rod;
and yet did not come forth to rule the nations, but was taken up to God again,
and hath not since appeared in that Spirit, power, and dominion;
but only in such a strength of life,
as might enable his witnesses to bear witness to him all along the apostasy,
until the church should come out of the wilderness, and the man-child appear again.

And now hear the joyful news.
The apostasy is ended.
Mark; I do not say the apostasy is generally ended.
No, no; there are many woes, plagues, judgments,
and terrible thunders to come upon persons, and nations, before they feel it ended.
But it is ended in some vessels, which are upon the earth.
The man of sin, that wicked one, the son of perdition,
hath been discovered by the Spirit of the Lord; chased, consumed,
and destroyed by the breath of his mouth,
and by the brightness of his appearance in some.
Yea, the church is come out of the wilderness, and the man-child is come along with her;
for she is not come without her beloved, but leaning upon her beloved;
and he is known ruling with his golden sceptre,
and with his iron rod battering down the corrupt, selfish, stubborn, earthly spirit,
and raising up that which is meek, tender, lowly, and lay bowed down and oppressed.

Now, as Christ said, preaching in the days of his flesh,
"`This day is this scripture fulfilled in your ears.`" Luke 4:21.
Was it not then fulfilled outwardly among the outward Jews?
Were there any sick, or weak, or blind, or lame, or lepers, or possessed with devils,
whom he was not ready to cure?
And did he not go about doing good, and seeking them out to cure them?
So may it not now be said in the Spirit and power of the Lord, among the spiritual Jews,
This day is this scripture fulfilled spiritually in your ears?
Yea, what he did then outwardly is known in spirit to be done among you inwardly and spiritually.
How many that were before blind do now see?
that were before deaf do now hear?
that were formerly lame do now walk?
that were very leprous are now cleansed?
that were very dead are now raised?
that were quite dumb do now speak?
And the poor, the empty, the naked, are now clothed,
and filled with the riches and treasures of the everlasting kingdom.
May it not be truly said, by many poor, distressed hearts,
that the wilderness and solitary place is now glad,
because that which once was parched with drought
and barrenness now feels the living springs,
and the breaking forth of the pure, clear river of life,
the streams whereof make glad the city of God, and cause melody in the heart to the Lord?
Where is the envious, cruel, dragonish nature?
may some say.
Yea, where is the place where dragons lay?
Is there not a new creation?--a new heaven, a new earth;
and are not all things become new therein?
Are not the old things of the night, and of the darkness, passed away,
and all things become new in this day, which the Lord hath made,
in the hearts which have received and been subject to his light?

And now what hinders, but that ye also should lift up your heads,
and see the coming of the Son of man in the clouds wherein he comes,
and partake of the redemption, virtue, and power of his appearance?
What are the clouds wherein he comes?
Is his coming outward?
Or are the clouds outward?
Or is his coming inward and spiritual in ten thousands of his saints?
Did not Enoch see that he was to come so to judge the world?
Doth he not come to be glorified in his saints?
Are not they to judge the world?--they in him, he in them?
Oh! read aright; read with the Spirit, and with the understanding which is thereof;
and then the truth of the letter will be manifest and shine in you.
There is nothing stands in your way,
but want of a spiritual eye to see his spiritual appearance
in others (and so to wait for it in yourselves),
even the eye of faith, which sees the invisible power and glory, as the Lord openeth it,
and maketh manifest to it.

Now, this I have to say to you, in true sense and understanding:
Come down to the Gentile`'s light,
come down to that which God hath dispensed to the Gentile, as well as to the Jew;
which is the word (or commandment) nigh in the mouth and heart.
This hath been the lowest of all, despised by all;
and this is in the heart of God to exalt over all; for it is above all.
The lowest in its descent from the Father; the highest in its ascent to the Father.
This is the thing which man ran from, when the veil came over him;
which all the shadows of the law were to point out and signify.
And as man is brought again to this, life springs in him,
and the powerful redemption of the eternal word is witnessed by him.
Yea, he that hears the voice of this, though he were ever so dead in trespasses and sins,
shall feel life spring in him, and the covenant of life inwardly revealed, which,
by the pure faith and obedience, is the entrance into, and the abiding in.
And this is the one truth, the one pure, eternal word and way to the Father,
which was from the beginning, and remains the same unto the end.
This is the door, at which all hitherto have entered into life,
at which all do still enter, and there is no other.
Blessed forever is he, who hath made it so manifest and plain in this our day;
and blessed are they that see it, and enter into life at it!

=== A VISIT Of tender and upright love / TO SUCH AS, AMONG THE MANY PROFESSIONS AND WAYS OF RELIGION, RETAIN ANY MEASURE OF SINCERITY OF HEART, AND TRUE DESIRES AFTER THE LORD

THE main thing in religion is to receive a principle of life from God,
whereby the mind may be changed,
and the heart made able to understand the mysteries of his kingdom,
and to see and walk in the way of life;
and this is the travail of the souls of the righteous, that they may abide, grow up,
and walk with the Lord in this principle; and that others also, who breathe after him,
may be gathered into, and feel the virtue of, the same principle.

But there is one that stands in the way to hinder this work of the Lord, who,
with great subtlety, strives to keep souls in captivity,
and to prejudice them against the precious living
appearances of the redeeming power of the Lord.

One great way whereby he doth this is by raising up in them
a fear lest they should be deceived and betrayed,
and instead of obtaining more, lose that little of God which they have.
With this I was exercised long; and still, when life stirred in my heart,
then this fear was raised in me; so that I durst not in judgment close with what,
secretly in spirit, I felt to be of God, it having a true touch of his quickening,
warming, convincing, enlivening virtue in it.

Now, that this snare may be escaped by such as breathe after the Lord, oh! let them wait,
mourn, and cry to him, that he would write his pure fear in their hearts,
and teach them when to fear, and how to fear, and what to fear;
and in that (or as that is brought forth in them) they shall
see that they have more cause to fear their present state,
than to fear that which, in the quickening warmth and virtue of God,
comes to make a change in their present state; yea,
they shall then see how the enemy now causeth them to fear, where no fear is;
and keepeth them from fearing, where the fear is.
For what is the ground of fear now?
This is the great thing that they should fear,
lest they should not hear the call of the Spirit of the Lord out of Babylon;
out of that part of Babylon out of which they have not yet travelled;
and lest they should not hear and mind the call of his Spirit unto Zion,
the holy mount of God, towards and unto which he leadeth his people,
in this day of the revelation and manifestation of his glorious love and power.

Oh! therefore, my friends, ye that long after the Lord,
ye that desire to feel the power of his truth,
wait for the principle of life from him to be revealed in you,
and the pure fear which is therefrom,
that he may feel the Lord thereby and therein (even
in and through that principle) writing his fear,
his pure fear, his holy fear, his powerfully-preserving fear, in your hearts;
that ye may know the way to him, the seed (which is the way),
may come and join to him therein, and never depart from him.
The fear of the Lord, from the principle of his life, will, without fail,
effect this in you as ye receive it from the Lord; but the other fear,
the fear which the enemy begets, will not do it;
but will be a bar and sore stop in your way, till the Lord, by his holy power,
through his tender mercy, remove it from you.

And now answer me one question uprightly, as in God`'s sight,
from whom it is in my heart to propound it to you.

Are you come to Zion, or are ye travelling thitherward rightly and truly?
Have ye ever known any of the travellers that ye have been acquainted with,
that could in truth say, that they were come to Zion?
The Christians, in the primitive times, were come to Zion,
and they were acquainted and dwelt with God and Christ there; and knew Jerusalem,
the heavenly building, the city of the living God.
Oh! where are ye?
Nay, are ye yet come out of Babylon?
Do ye yet know the wilderness, the intricate passages therein,
wherethrough God alone can lead the soul?
Oh! depart ye, depart ye from your present stations (in the leadings of God`'s Spirit),
unless ye can say, in the true, unerring light, that they are your rest,
your soul`'s true rest, even the everlasting kingdom,
which the primitive Christians received, and into which they found entrance,
which could not be shaken.

And, friends,
let me tell you one thing further (for my heart is
at this present opened to you by the Lord),
that as the soul, in its travels, comes to Zion,
the law of the Spirit of life in Christ Jesus is witnessed,
which makes free from the law of sin and death.
And then there is no more such a crying out of the body of sin as there was before:
but a blessing of him who hath delivered, and daily doth deliver, from it: yea,
the body of sin is known and felt to be put off, and Christ put on in the stead thereof.
For, my friends, there are several states witnessed by the soul,
in its true and sensible travels towards the holy land.
As for instance:

1+++.+++ There is a state of Egyptian darkness and bondage,
in which the power of death reigns and rules in the heart,
subjecting it to sin and death.
And here the soul is in the grave, and under death, captivity, and bondage,
in the midst of all its professions of religion, and talk of God and Christ,
and reading scriptures, and observing ordinances and duties, etc.

2+++.+++ There is a wilderness state, wherein the strength of captivity is somewhat broken,
and the heart drawn to mind the leadings of life,
and to follow after the Lord through the trials, through the preparations,
through the several exercises, which the Lord seeth good to exercise it with.

And here the mercy and goodness of the Lord is experienced,
and the deceitfulness and treachery of the heart.
This is the place of humiliation and breaking,
wherein the soul daily feels how untoward and unaccustomed it is to the yoke,
which should break the spirit, and subdue it to God.
Here the Lord shows the soul what its heart is, that he might humble it,
and do it good in the latter end.
Here the very law of God appears weak, through the strength of the flesh,
which is not yet subdued.
Now, here is mourning, and groaning, and crying to the Lord night and day,
both because of the violence and multitude of the enemies,
and because of the naughtiness, distrust, and unbelief of the heart.

3+++.+++ There is a state of rest, a state of peace, a state of life, a state of power,
a state of grace, a state of dominion, in the life, and through the power of the Lord,
wherein the law of life is manifested in dominion
in the heart over the law of sin and death.
There is an everlasting kingdom, wherein God and Christ reign,
in which God treads Satan down under the feet of the soul,
and makes the soul a king and a priest in the Son of his love;
and the soul feels it is one with, and accepted in, the beloved.

Now, friends, that ye may know this kingdom, travel faithfully towards it;
feel and come into the reign of Christ in it;
sit down in the heavenly places in Christ Jesus, and inherit substance;
know the gathering to Christ in the name, and sit down in the name,
where the enemy cannot touch you;
but feel the preservation and powerful life and dominion
of that seed which is over the enemy,
and wherein and whereby the Lord scatters the enemy, bruising the serpent`'s head,
and anointing the soul with the oil of gladness,
and clothing it with the beautiful garments of his righteousness and salvation;
and that ye may know the precious and glorious building of life in the Spirit,
even of the holy house and city of God, where the walls are salvation,
and the gates praise.
For this end it is in my heart from the Lord to write these things unto you;
and the Lord God of his mercy open the door of entrance to you into these things;
for there is but one door of life, and there is not another; which door is Christ,
the seed; which seed is revealed within, there to break the wisdom, strength,
and head of the serpent; and so far as he breaks it there,
redemption and freedom is witnessed from it, and no further.

Oh that ye might receive an understanding from the Lord,
and be taught by him to deny and part with the understanding which is not of him,
that ye might see things (from him, and in his light) which ye have not yet seen;
and consider aright of that, which the enemy hitherto, by his subtlety,
hath prejudiced you against.

And now as for us, who experience the truth as it is in Jesus,
and with the Lord our God in his light,
and by virtue of his life and love shed abroad in our hearts,--I say,
what is it to us to be judged by you in your day as persons that deny Christ,
deny scriptures, deny ordinances, deny duties,
etc.? We are satisfied in our hearts as touching your judgment,
knowing from the Lord what it is in you that thus judgeth of us,
even the same thing that judged amiss of Christ (in the Scribes, Pharisees,
and professing Jews) in the days of his flesh.
And indeed, that in you can never judge aright; but is to be judged, condemned,
and destroyed by the life and power of the Lord.

And oh that ye knew (sensibly knew) what is to live, and what is to die in you,
that ye might feel the rising of your souls out of the grave,
through the immortal seed of God,
and the bringing of all your wisdom and knowledge of the things of God (which ye hold,
and make use of, out of the compass and limits of his holy life and covenant) into death!

For, friends, let me tell you, that which hath been parted with (for the kingdom`'s sake,
and the righteousness thereof) in some, was more precious than what ye hold so stiffly,
and so magnify in your own thoughts and reasonings against the truth.
Yea, that which was once of high esteem, and very glorious in our eyes,
is now become as dross and dung, for the excellency of the pure, living knowledge of,
and fellowship with, Jesus Christ, our Lord;
and if ye had the true measure and balance to weigh things in, ye would acknowledge it:
but the letter, and little ordinances and duties,
and apprehensions of things out of the life, kills you, and keeps you under the veil,
and from the sight of the things which are within the veil.

Oh that God would rend the veil in you!
Oh that God would give you the feeling of, and union with, that whereby he rends the veil!
Oh that he would humble you, and bring down the mighty from his seat of judgment in you,
to be judged and abased,
and exalt the meek and lowly into that which is his proper place!

Oh that ye might feel the work of God, even the redemption of the soul,
begun and carried on by him with power in your hearts!
Then would ye know Christ indeed, the scriptures indeed, the ordinances indeed,
the duties indeed, the everlasting sabbath, the everlasting worship;
even the substance of all that was shadowed out under the law,
and sit down under the wing of the Almighty, from whence the power, the life, the virtue,
the healing, drops into the soul.

And now, to give a touch at those things before mentioned, which ye so stumble at,
a little to help to remove them from your spirits, if it please the Lord.

1+++.+++ We do not deny that Christ which died at Jerusalem; but own him, and no other:
and own what he did, his obedience to the Father always, and in all things;
his sufferings in the virtue and power of the Father,
and the value of them with the Father.
This the Lord our God teacheth us to own, and to bless the name of the Lord,
for him who is the Captain, the worker out of our salvation;
a measure of whose life and power we have received, and embrace in our hearts;
and in this is He, the fulness, made manifest to us; and we, through this, and by this,
and in this, ingrafted into him;
and so come to partake of the sweetness and fatness of the olive-tree.
Yea, this we certainly know,
that Christ was not only made manifest in that body of flesh,
but is also made manifest in our mortal flesh, as we are gathered into his life,
and his life brought forth in us.
And he is not only antichrist, that denieth Christ`'s appearance in that body of flesh;
but he that denieth him (the hope of glory) in his saints, his spiritual body.
Yea, I beseech you consider,
whether it hath been the work of antichrist all along the apostasy
to deny the appearance of Christ in that body of flesh,
or to deny the appearance of his life and Spirit in the flesh of his saints?
"`We know (saith the apostle John) that the Son of God is come,
and hath given us an understanding to know him that is true.`" How was he come?
Was not he that was with them come in them?
Did he not live in them, act in them, speak in them?
And did not they that were of God hear the voice of Christ, the voice of the Shepherd,
in them?
But they which were not of God, which were not the sheep,
could not hear the voice of Christ in his apostles and believers;
could not own him come in their flesh, though they could preach the same Christ in words,
and own his coming in that body of flesh which he had appeared in. 1 John 4:6.

2+++.+++ We do indeed really, heartily, singly, as in God`'s sight, own the scriptures;
the scriptures written by the prophets and holy men of God under the law;
the scriptures written by the evangelists and apostles in the time of the gospel;
and we read them with delight and joy,
and would draw no man from a right reading of them to the benefit of his soul;
but only from giving their own judgments on them without the Spirit of God;
lest in so doing, they wrest them to their own destruction.

This is that which the Lord hath drawn us from,
and which we know it would also be profitable to others to be drawn from too; to wit,
from imagining and guessing at the meaning of scriptures,
and interpreting them without the opening of that
Spirit from which they were given forth;
for they who so do, feed that part (with a gathered knowledge) which should be famished,
die, and perish, that another thing might come to live in them, and they in it.

Now to us, being taught of God,
and led by him into the things and through the conditions the scriptures speak of,
the scriptures are very precious, the relation of things under the law precious,
the instructions, promises, and comforts precious, yea,
the very reproofs and denunciations of judgment to that part,
nature and spirit which the judgments are to, precious;
and it is impossible for any heart to conceive (who hath
not the experience of the thing) how life springs in us;
and how sweet, pleasant,
and profitable the words of life in the writings of the holy men of God are to our spirits;
and in reading them we often meet with refreshment, comfort, hope, and joy,
from the working of the same Spirit in us, which gave forth the good words through them.

3+++.+++ As touching ordinances,
we own all the ordinances and appointments of God to the Jews under the law,
and God`'s presence with them, walking with the Lord,
and worshipping him in the faith according thereto.
Yea, what if I should say,
that we know and are exercised in the same worship in Spirit towards the Lord our God,
who hath called and taught us to worship him in spirit and truth, so as he taught them,
according to the shadow and letter?
What if I should say,
that we worship the Lord in spirit on the Lord`'s day (which is inward and spiritual,
the true rest, the substantial sabbath),
and that we offer up to him the living sacrifices,
which the High Priest of our profession prepares in us for
the most excellent majesty and glory of our God therein?
Were not the sacrifices under the law, which they offered up according to the letter,
types and shadows of what the Lord teacheth us,
and giveth us to offer up to him in spirit,
when we appear before him in his house built on his holy mountain?
For, friends, the house wherein we appear is spiritual (an house of God`'s own building);
the worship spiritual, the sacrifices spiritual, the day of worship spiritual,
even the day which the Lord hath made.
And here we know and enjoy the things shadowed out under the law spiritually,
eating that which is meat indeed, and drinking that which is drink indeed,
even the flesh and blood of the Son of man; in which we feel and partake of his nature,
his virtue, his life, his substance, and both take it into us, and put it upon us;
so that we have Christ both to be our food and clothing; and in the birth, nature,
and Spirit which is of him, cannot be deceived concerning him.

But the great matter ye seem to have against us as to ordinances,
is about the baptism of water, and breaking outward bread, and drinking outward wine;
concerning which I have two or three weighty queries
to propound to be seriously considered of.

Query 1. Were these things themselves the things of the kingdom,
or significations of somewhat relating to the kingdom, as the shadows under the law were?
And so, though they might have a use and service in the passage from the law,
yet could they have an absolute place in the day?
For as the day dawns and breaks, the shadows fly away.
What should the shadow do, when that which the shadow signified is come?
What place is there for shadows in the substance, in the everlasting kingdom?

Now though the apostle condescended so as to circumcise for the sake of the Jews,
yet circumcision was not to abide.
So he condescended also as to John`'s baptism; to wit,
the baptism of water (for that was not Christ`'s baptism,
but his baptism was that of the Holy Ghost and fire);
yet he blessed God he did not make use of it, and said, he was not sent to baptize.
What was he not sent to baptize with?
Why, not with water, not with John`'s baptism;
but he was sent to baptize with Christ`'s baptism; to baptize into the name,
into the Spirit, into the power (and so were all the apostles),
as well as to preach the gospel. Gal. 3:5.
Matt. 28:19.

Then for the outward supper: was not that a shadow of the true,
substantial supper of the Lord, of the breaking of the true bread,
and drinking of the true wine (the fruit of the vine of life) in the kingdom of God?
Which kingdom was at hand in John`'s time,
and the disciples of Christ were to pray it might come; and the apostles,
and they afterwards (that were in the power, in the life, in the righteousness,
in the joy eternal) did witness it come.
For mark: the promise was not only of a kingdom of glory hereafter,
when the body is laid down; but they were to receive the kingdom,
and feel an entrance (yea,
an abundant entrance) into the everlasting kingdom ministered to them even then:
and they were to eat bread in the kingdom, and drink wine in the kingdom, even new bread,
and new wine, fresh from the table of the Lord, yea, and with the Lord, in his presence,
according to the promise, he would come and dwell in them, and walk in them,
and sup with them, and they with him.
And thus they in their day,
and we in our day (blessed be the name of the Lord our God!) eat and drink
of the heavenly bread and wine of the kingdom with Christ therein;
every one sitting in the heavenly place, and mansion of rest,
which the Lord hath built up and prepared for him.

Query 2. Have not these outward things been much abused,
and the antichristian spirit (even the whorish spirit,
which hath adulterated from the life and power of God) appeared in them,
and cried them up?
And surely, as so cried up by that spirit, they are neither of nor for Christ.

And consider well what that outward court was which God gave to the Gentiles,
and what the worship and ordinances of the outward court were;
and whether they were not given to the Gentiles also,
and whether these are any part of them; for if so, then they belong not to,
nor are required by, the Lord, of the inward Jews,
who are of the circumcision in the heart, and are come to inherit the substance.

Query 3. Whether there be any virtue in these things in themselves,
without God`'s requiring of them?
Can outward water wash the soul?
Can outward bread and wine feed or refresh it?
Indeed if God require a man to wash his body with water, he ought to be subject,
and there will be profit to him in his subjection;
but of itself it is but a bodily exercise, and without God`'s requiring it,
it would be but will-worship, and profit him nothing at all.

Now truly the Lord did never require this of us;
but hath shown us the water which our souls and bodies had need of to be washed with,
and the bread and wine which they are to be fed and refreshed with:
and in following the Lord according as he hath led us, and required of us,
we have found reconciliation, life, rest, peace, and joy with our Father,
and pure refreshment from him.

Query 4. As touching duties: These are the two great duties we are taught,
To love the Lord our God with all our heart, soul, and spirit;
and our neighbor as ourselves.
And these we learn by believing in him whom God sent,
and receiving the seed of life from him; in the growth whereof in us we live,
and are made one with him, and partakers of the ability which is of him.
For not by working of ourselves do we attain to this;
but by the working of his powerful life in us, through his mercy to us.
He circumciseth us, he cuts off the enmity,
he brings under the old nature and spirit in us, and then the new springs up,
and we are renewed in it.
And in this we learn and are made able to love the Lord, and his children,
and his creatures, yea, all that is of him.
And this love constrains us to obey the Lord, and deny all for him;
so that we can suffer any thing (through his strength) but sin, but corruption,
but unbelief, but disobedience to him.
Yea, this makes us so tender towards him, that we can rather part with all of this world,
than the integrity and subjection of our spirits
to him in the least thing that he requires of us;
his truth (and our testimony thereto) in every respect
being far dearer to us than our lives,
and all the enjoyments and pleasures of this present world.

From these two great duties flow many others as towards God;
to fear him with the fear which is not taught by the precepts of men,
but which he writes in our hearts; to wait upon him night and day in his temple,
even in the holy place of his building; to call upon him in the motion, guidance, will,
and help of his Spirit (for indeed when once we learn of God,
we are taught to pray no more after the flesh, no more after the will, wisdom,
or way of man); as also to be sensible of his goodness,
and give thanks to him in every condition.

And in this we feel his presence and acceptance, as the Lord is not forgotten by us;
but when we eat and drink, walk abroad, or stay at home, we feel him near,
and our hearts acknowledge him, bow to him, wait upon him, bless him, praise his name,
and speak words concerning him, or to him, with the outward voice, when he gives them,
and requires them of us; but of a truth we dare bring no sacrifices of our own,
nor kindle any fire or sparks of our own; but wait for the holy breath, Spirit,
and power of our God, to perform all in us, and by us.

But now, because we do not pray at certain set times (as we formerly were wont to do),
nor speak words before and after meat as formerly, and the like, ye are offended with us,
and say we deny this duty.
No, no; we do not deny to God the prayer which is from the birth immortal;
but this we say, and sensibly feel, prayer is a gift,
and the ability thereof is in God`'s Spirit;
for we know not what to pray for as we ought,
nor have we a power in us to pray when or as we will; but in the Holy Spirit,
in his breathing in us, is our ability;
and we are to wait on him for the moving and breathing of his Spirit,
and not to pray of ourselves, or in our own wills or times,
but in the Father`'s. And it is a mighty thing to speak to God aright in prayer.
Flesh must be silent before him, and laid still and low in his presence,
that the pure spring may open, the pure breath breathe, and the pure voice issue forth;
for God heareth not sinners, but the born of him that doth his will.
This must every soul witness in his measure, as Christ witnessed it in the fulness;
and there is no serving God aright,
or performing any duty or ordinance of worship to him aright,
but in a measure of the same life and Spirit wherewith Christ served him.

Now, I do not only own the state of the Jews in their integrity,
and of the primitive Christians in theirs,
and of what the Lord hath caused to break forth in this our day,
but I also own all the appearances of God all along the
night of the apostasy in the holy martyrs and witnesses,
which he raised up, and enabled to bear testimony to his truth,
and against the antichristian practices of many in that dark night of the apostasy.
And thus also I own all the work of God in my own heart,
and in the hearts of others (whom he pleased to work upon) in former times; yea,
the breathings and desires which are yet in the hearts of any after the Lord,
so far as they are in the truth, and of and from the Lord, I cannot but own.
But the Lord hath shown me that there is a great
mixture in men`'s desires and endeavors after him;
and that the evil spirit, by his subtlety, doth often get the managing of them,
and turn the very zeal and earnestness of the mind (through prejudices
and misapprehensions) against the Lord and his truth.
Now, this is a very dangerous state,
and there are some (who little think so) in this state, doing that against the Lord,
and against his Christ, his truth, his people, which, if ever their eyes be opened,
they will mourn bitterly over; and if their eyes be not opened,
but they walk on by a wrong light (even by a light of their own gathering, imagining,
and conceiving), whither will it lead them, and what will their end be?
Oh that ye could hear!
Oh that ye could fear aright!
Oh that ye could rightly consider!
Oh that ye could feel the life and power of the Lord near you, the Word of life near you,
even as near as ye have felt the enemy and his temptations, that ye might partake of,
and witness with joy, the virtue and redemption of it!
Oh that ye could once aright look upon him whom ye have pierced, and yet daily pierce,
and cannot but pierce,
until the righteous judgments of the Lord be poured
out on the head of the transgressor in you,
and the Lord waited upon, feared, and subjected to, in the way of his judgments,
that ye may feel the refining work finished, the dross burned up, the temple prepared,
the vessel brought out of the furnace!
What then?
Why, when the Lord hath built up Zion, prepared his temple, cleansed his house,
will he not appear there in his glory?
Shall it not become a house of prayer?
of pure prayer, and of pure praises?
Shall there be any lame or blind sacrifices offered up there?
Shall it not be the beauty of holiness indeed?
Shall not the appearance of the Lord be more glorious than
ever it was in the temple and ordinances under the law?
Shall not every living stone in this building feel
the God of life and power present of a truth,
and feel not only the earth, but the very heavens melt before him and pass away,
and nothing remain but the pure light and life of the Lamb?

Words and promises spoken concerning things to be brought
forth in the gospel state do not go beyond the things spoken;
but the things brought forth excel and go beyond the words,
being so felt and enjoyed by that which is fitted and prepared by the Lord,
as words cannot utter.
The Lord God lead all that rightly desire after him into the right way (and preserve
them therein) of meeting with and enjoying what their hearts rightly desire,
and beat back the enemy in all his devices of entangling, perplexing,
and drawing them aside; that they may receive the covenant, the new covenant,
walk with God in the light thereof, live in the life thereof,
obey through the power thereof; and may know what kind of meat and drink, what joy,
delight, and pleasure it is to the soul to do the will, in the principle,
and by the power, of the new life.
So the Lord God Almighty, the Creator, Guider, and Preserver of his Israel,
lead you out of the darkness, bring you through the wilderness, reveal the hope in you,
and stay your minds thereon,
and give you to feel the true travel and faithful
walking with him in the footsteps of the flock,
which he hath led and is leading his in,
and unto some of whom (in the tender mercy which from on high hath
visited them) he hath given full rest and satisfaction in his truth.

=== A BRIEF ACCOUNT OF THE GROUND OF CERTAINTY AND SATISFACTION, WHICH IT HATH PLEASED THE LORD TO ESTABLISH IN MY HEART, CONCERNING RELIGION, AND THE THINGS OF HIS KINGDOM

I HAVE been afflicted from my childhood,
mourning and seeking after the Lord, and feeling very much grief and pain of spirit,
through my sense of the want of him.
I have not been contented with the way of religion I was educated in,
but (through that of God which stirred in me) found great defects in it,
and was drawn and led by his Spirit to travel through it, and seek further.
That which I still sought after was the resting-place, the life of my soul,
and power and presence of the Lord,
that demonstration of his Spirit (as touching truth and the way
of God) which was witnessed in the days of the apostles.
Now, breathing after this, but not meeting with it, caused unutterable anguish, misery,
and distress in my heart, so that my condition could not be hid within mine own breast,
but my sorrow also brake forth in the sight of others.

But at length the eternal bowels have pitied me,
and have showed me the place of the soul`'s rest,
and I have felt the eternal arm gathering me into, and giving me some possession of,
a measure thereof;
so that my heart is satisfied about religion and the things of God`'s kingdom,
being taught of God how to know the Pearl,
and the way also how to come to inherit and enjoy it;
and in that way I have had great experience of the love, mercy, wisdom, goodness, power,
and righteousness of the Lord; and notwithstanding all my soul`'s enemies,
I still feel his presence, life, and power, to his praise, which doth the work in me,
and which giveth me to hope in him, and wait upon him.
And now in love and tenderness of bowels to others,
it is in my heart to answer a question or two about the ground
of the assurance and satisfaction which God hath given my soul;
it being in my heart not to grieve or trouble any,
but only to be helpful in holding forth what the
Lord hath demonstrated to and written in my heart,
as he shall draw, move, and enable my spirit thereunto; to whom my soul boweth,
and giveth the praise of all that he hath done in me,
and pleaseth by his Spirit and power to work through me.

Question 1. It may be inquired by some, how I come to know the Spirit of God, and his church,
and the scriptures of the holy men to be written
by the inspiration and leading of his Holy Spirit;
and how I know the motions and drawings of his Spirit in me, from the motions,
suggestions, and temptations of the evil spirit;
and how I am satisfied that I am in the way of truth and life eternal,
and do not wander out of it, and err from it.

Answer.
Thus I know: By receiving, joining to, abiding and growing up in, that holy seed,
which the Father of spirits hath sown in me.
There is an elect seed which cannot possibly be deceived, which seed the Father soweth,
and causeth to grow in the hearts of them that receive it;
whose earth is by him digged and prepared for it.
Now, I have felt this seed from God, this holy, pure thing,
which there is nothing like for virtue and excellency.
Nothing hath its nature besides it, nothing manifests the Father but it;
the heart is changed, renewed, restored into the holy image by this alone.

In this seed there is no deceit; no deceit ever came from it,
no deceit ever entered into it, nor can; and from the day that I have known it,
I have always felt preservation by it, while my heart hath been kept to it.
Mine eye never missaw in it, mine ear never misheard in it,
my heart never misunderstood in it; but here I have felt given to me,
and maintained in me by God, the eye which sees, the ear which hears,
the heart which understands the things of his kingdom;
and here the entrance hath been ministered into the everlasting kingdom,
where God reveals by his Spirit the mysteries of his kingdom,
which all else are shut out of, but this seed and the birth which is of it.
And when the enemy hath at any time in my travels, by any temptation or device,
got in any degree between my soul and this seed; then a darkness, a loss, doubts, fears,
troubles, etc. have so far come over my soul.

Question 2. But how know I this seed?
may some inquire.

Answer.
By its nature, by its properties, by its manifesting of itself in my heart.
It hath that light, that life, that power in it, which I never met with anywhere else.
It bruiseth the head of the serpent at its pleasure,
whereby I know it to be the seed of the woman.
It dasheth in pieces (through subjection to it) whatever is contrary to God,
and bringeth up his holy nature in me.
It so bringeth me into the very image of his Son,
that what I read in the Scriptures concerning the nature, righteousness,
and work of salvation by Christ, I find formed and springing up in mine own heart,
as I am gathered into, and brought forth in, this seed.
Yea, I really feel that I am born of God`'s Spirit, so far as I am born of this.
Here I feel, know, understand, and am acquainted with, the substance, the thing itself,
that which all the types and figures of the law shadowed out.
Here I meet with the circumcision which is without outward hands;
the baptism which is without outward water;
the supper of the Lord which is without outward bread or wine;
and here I know the true Jew, whose nature, spirit, works, and ways are all of God,
in and through his Son, Jesus Christ.
and here I must profess, I cannot doubt concerning the things of God:
but in the light and anointing of this seed, see both the mystery of iniquity,
and the mystery of godliness, and the ways and workings of each spirit,
both inwardly and outwardly; and my unity with the one (through the tender mercy,
goodness, love, and power of the Lord, all which are herein revealed),
and my separation from the other.

And this is the true way of certainty and satisfaction, which is of God, and will stand,
when all the several ways of men`'s inventions will fail of what they promise to men,
and fall in the sight of men.
For this seed and birth of God are to be acknowledged, and reign in the day of his power,
and not another.
And it is the day of his power in some, and shall be the day of his power in others;
for darkness or death shall not prevail to bring the life
of the risen Son into the sepulchre or grave again;
but he shall ride on conquering and to conquer, subduing and to subdue,
reigning and to reign,
until he hath brought all things under the dominion of the Father`'s power.

=== A QUESTION ANSWERED ABOUT THE WAY OF KNOWING THE MOTIONS, DOCTRINES, AND TEACHINGS OF CHRIST`'s SPIRIT

Question.
How may a man know the motions, doctrines, and teachings of Christ`'s Spirit inwardly,
from the deceivable movings, appearings, and workings of a contrary spirit?
And how may a man know concerning the doctrines that others teach,
whether they speak from Christ, or whether they speak of themselves?

Answer.
This is a great matter indeed, and he must first receive somewhat from God,
who is able to do this.
He must be born of the wisdom that is from above,
he must receive a spirit of discerning from God,
he must receive somewhat of the sheep`'s ear, somewhat of the holy understanding,
whereby he may be able to distinguish spirituals,
and put a difference between the pure and impure;
between the pretender to the things of God, and him which is indeed of God.
There is a balance of the sanctuary appointed to
weigh spiritual things and appearances in;
and by this balance alone are they truly and rightly discerned and distinguished;
and this balance is in the sanctuary, in the holy, heavenly place in Christ Jesus,
where the true weight of spiritual things (or things
that pretend to be truly spiritual and living,
but are not) is given and discerned.
But he that weighs without this, he that weighs by his own judgment and understanding,
by his own comprehension and conceivings; he weighs by that which is uncertain,
changeable, and fallible,
and turns up and down according to the appearance of things to him,
but judgeth not the righteous judgment, which is from the sense, and in the light of,
truth.

Therefore, oh! that men were humble, tender,
meek and sensible of their inability to judge as of themselves,
that they might see the need of this gift of God, and wait upon him for it;
being in the mean time as the weaned child, not meddling with things too high for them,
but keeping and abiding low,
in fear and subjection to that which the Lord hath already made manifest to them.
For what man is there, to whom the Lord hath not already,
in his tender mercy and goodness, made somewhat of himself manifest?
Who is there, who, by the light of the Spirit of God in his conscience,
knoweth not some evil which he ought to leave undone, and some good which he ought to do?
Now this is the way of God, and the work which man should be exercised in,
to feel his mind gathered into that which teacheth this,
that he might receive power from the Lord to cease
to do the evil which he is thus warned by him of,
and to do the good which is thus required of him.
For thus the Spirit of the Lord teacheth and requireth of men,
even inwardly in their secret parts,
secretly quickening and enlivening them in some measure,
and giving them a sense of their sin, death, separation from him,
misery and danger thereby; for where there is any sight of sin,
and any sense of the burden thereof, there is some life, some light,
some little stirrings of the life, and some quickenings thereby,
without which this sense could not be.
Now mark:

Are not here the drawings of the Father?
Are not here the teachings of the Father, though but in a little measure; yet true,
yet living?
Is not here some little discerning given between the precious and the vile;
between somewhat that is of God, and somewhat that is against him?
Well then, here is the gift of discerning, though in a poor, low, little, weak measure;
and that man who receiveth this, receiveth the beginnings of the gift,
somewhat of the gift,
whereby he may be able to discern and distinguish a little about spiritual things,
so far as the light and ability of the gift in him extendeth.

Now, this is man`'s work (and in this lies his safety), to come hither, abide here,
and grow here.
Not to judge out of this; to judge no further concerning the things of God,
than this judgeth in him; to keep the judgment he hath from this;
not hearkening to the subtle devices of the enemy,
which will strive afterward to cloud his mind, delude and deceive him,
with a false appearance of wise reasonings and disputings of his own, or from other men,
to make him believe otherwise.
And so keeping what ground he hath gained, he is to wait for more of this light,
more of this life, more of this virtue, that his soul may grow up and increase therein,
that his eye may be strengthened to see further, and his ear to hear further,
and his heart to embrace more of the instructions
and directions of the Spirit of the Lord,
unto and in the way of the kingdom.

Therefore the man that would meet with, and receive from God, the gift of discerning,
let him mind the present manifestation of God`'s light from his Spirit in his heart;
embrace that, fall in with that,
take heed of the reasonings of the mind against the
convictions and demonstrations of God`'s Spirit,
but receive the truth in the love of it, even the lowest appearance of truth,
about the least and most despisable things, and give up faithfully to the Lord therein,
without murmuring, without disputing, without consulting with flesh and blood.
And he that is faithful to the light of the Spirit
(and to the discerning that is thereby) in the little,
he shall receive more, he shall have his light and discerning thereby increased,
as his need requireth.
But he that stands disputing, and would have all his way made clear to him,
before he sets one step in it; he is far from becoming that child,
which the Father teacheth, and administereth an entrance into the kingdom to.

This, in effect,
was the very answer which Christ gave to this thing in the days of his flesh,
when there were great disputes concerning his doctrine,
how to know whether it was of God, or no.
What was the resolution he gave of this; "`If any man,`" saith he, "`will do his will,
he shall know of the doctrine whether it be of God,
or whether I speak of myself.`" John 7:17. Wouldst thou know of the Son`'s doctrine?
Wouldst thou know whether it be the doctrine of the Son indeed,
the doctrine of him who comes from the Father?
Yes, very fain, will the upright heart say;
oh that I might know concerning what rises and opens in my heart,
whether it be from the Spirit of God, or from the root of deceit in me!
Why, this is the way; do the Father`'s will.

Objection.
Do the Father`'s will; why what an answer is this!
The dispute is about the Father`'s will.
Is not the doctrine of the Son the Father`'s will?
How can I do the Father`'s will, which the Son is to teach me,
until I first know of the Son`'s doctrine?

Answer.
It is true, the Son`'s doctrine is the Father`'s will,
and thou canst not do the Father`'s will, but as thou receivest the Son`'s doctrine.
But mark: There are disputes in thy mind about somewhat of the Son`'s doctrine,
whether it be his doctrine, or no; somewhat also about inward motions, workings,
and stirrings in thee, which thou wouldst fain know whence they are.
Now, the question is concerning the way how thou mayest attain to this;
how thou mayest come to a certain and satisfactory knowledge herein?
Which is,
not by entering into reasonings and disputes about these things whereof thou doubtest,
but by coming into that wherein and whereby they are made manifest;
and that is by coming into obedience to the Father
in that which he hath already made manifest;
for in that light (to them that believe in it),
and in obedience thereto (be it ever so little, or the manifestation ever so small),
the Father will reveal more,
and give to that heart and mind to be sensible of what is of him,
and what is of the enemy, so far as it is needful for it as yet to know.
For wise and absolute judgment in all things is not necessary for a babe;
but sense to know the breast, and to receive from it the milk,
by which it is to be fed that it may grow.
This is enough in its present state;
yet if there be need of strength at any time to still the enemy and the avenger,
the Lord will reveal it in the heart,
and bring it forth out of the mouths of the babes and sucklings,
to the perfecting of his praise.

So mind and learn the way, O ye that are simple-hearted (and truly desire after the Lord,
and the purity and power of his kingdom)! and take heed of the wrong way;
take heed of man`'s way, which is by consulting with his own wisdom,
and weighing things in the balance of his own reason and understanding;
and thus he may weigh scriptures written in former ages,
and the appearances of God in this age, and err in heart, mind,
and judgment concerning them both, all his days.
But he that waits on the Lord in fear,
and in obedience to that which is already made manifest,
not desiring knowledge from God in his own will, time, or way, but in the Lord`'s,
who perfectly knows every one`'s state,
and what is fit for him,--he shall know concerning every
doctrine his heart desireth to be instructed in,
in the Lord`'s season; and in the mean time the Lord will feed him with food convenient,
and clothe him with clothing convenient; and there shall be no want to him,
who boweth before the Lord in what is already made manifest,
and waiteth for his further manifestations and appearances.
But the wise hunter after knowledge, before the Lord leads,
and further than he leads and teaches,--this is the first birth,
which is excluded the kingdom and the mysteries thereof:
this is he who always despised and would still kill the heir,
that the inheritance might be his;
but the inheritance is appointed for and given to another; even to the Lamb`'s nature,
the Lamb`'s Spirit, the Lamb`'s innocency, the birth of another wisdom,
which is a foolish, weak birth in his eye, and not worthy at all to inherit;
but it is the Father`'s pleasure to give the kingdom
and inheritance of life everlasting to these.

To speak yet a little more plainly, and bring it yet a little closer to the heart,
if it may be.
It hath pleased the Father, in this day of his love and power,
to gather a little flock out of the world (and all
worldly professions of worship and religion) to himself.
This flock he hath gathered by a poor, little, low thing in their hearts,
exercising them thereby in poor, mean, and contemptible ways to the eye of the world,
and to all the professions of man`'s wisdom; and by this, and concerning this,
he testifieth, through those whom he hath gathered, to others.
And the testimony doth evidence itself, through the power of the Spirit,
to all that wait upon God for an ear, and hear in the simplicity thereof.

Now, when we tell men of a divine principle, of a seed of God,
wherein their religion is to begin, and from which it is to grow,
and whereof they are to be born; this will enter into many, yea,
many will assent to be drawn so far as to wait inwardly for and upon this.
But now when this begins to stir and move in them, it is in such a way,
and many times about such low, mean, contemptible things in their eyes,
that they are very apt to despise it, and enter into disputes against it,
and so miss of the entrance, and can never thus enter into it;
but instead thereof are filled with doubts about the leader and his motions,
and puzzled and entangled in their minds, and stopped at the very beginning.
And so, though they desire much, and hope much,
yet all comes to little because the enemy hath possessed
their minds with a device of his subtlety,
as if these were small things, and of little concernment.
That which they want is the powerful life, the clear light, etc.,
and so their minds are taken up with thoughts about these great things,
and desires after these great things,
and they overlook the way wherein and whereby these are to be witnessed and obtained.

For the Lord God, in his infinite wisdom,
picked out these contemptible things to exercise his flock by, and to lead them in.
And whatever men may think of them, yet none knows, but they who experience it,
how hard it is to follow and subject to the Lord in these,
and how much they bow down and break the earthly and uncircumcised spirit in a man.
Now, friend, thou who desirest life from God,
oh! take heed thou dost not beat back the beginnings of his life,
and the redemption of thy soul, by despising and overlooking the day of small things.
Why may not God choose to lead thee in the way that he hath led the rest of his flock?
Why shouldst not thou also come to deny the customs and vanities
of this world (and come into that which is simple and plain),
and stand in the will and life of God out of them?
Are not the ways, customs, and vanities of the world, of the spirit of the world,
and not of the Father?
Did they not come from the corrupt part?
Are they not of the corrupt part?
Do they not please the corrupt part?
Must they not be left behind by him that travels into the seed, is one with the seed,
and lives in the seed?
Why wilt thou stick in these things?
Why wilt thou dispute about these things?
Oh! feel the Father`'s drawings, first out of the world,
first out of that which is not of the Father, but of the world;
that he may draw thee further and further, even into the kingdom and power everlasting,
which are many days`' journey beyond that which thou stickest at.

Now mind and remember this which followeth: In the days of Christ and his apostles,
God chose the foolish things, and the weak things, and things that were not,
to hide the path of life, and the mysteries of his kingdom, from the wise,
searching eye of man in those days.
Why may he not choose the like things now?
Why may he not now reveal things to the babes,
and not to the wise of this age and generation?
Why may it not be to his glory, to have it now said also: "`Where is the wise?
Where is the scribe (where is the learned man)?
Where is the disputer of this world?`" Can any of them find out that,
or any of them discern that, which God revealeth to his little ones?
No, no; they are generally got too high above that little, low, tender, meek,
sensible principle, in the faith whereof, and in obedience whereto,
the teachings of God are received, and his life and power witnessed.
And because of their riches, wisdom, and knowledge out of this,
therefore is the entrance into the pure, living truth (which cleanseth the mind,
and keepeth it clean, which quickeneth it,
and keepeth it living) to them so exceeding difficult.

And as the principle is little,
the seed of the kingdom little (like a grain of mustard seed), the least of all seeds;
so, why may not its appearance also be little, even in low, weak things,
despisable to man`'s eye and wisdom; which man sees nothing in,
and may account of no value?
And yet, the power of the cross (which brings down and slays the corruptible),
and the resurrection of the life may be witnessed and felt in them.
"`The foolishness of God is wiser than men,
and the weakness of God is stronger than men:`" and he knoweth what
he doth in leading his children in this contemptible path,
and by these contemptible exercises, which all that is wise, high, lofty, and aspiring,
according to the flesh, may easily overlook and slight,
but can hardly stoop down and subject to.

God is the same that ever he was; and he still appears in the way of his own wisdom,
and out of man`'s;
and he that will partake of God`'s wisdom must deny and keep out of his own.
His touches, his drawings, his teachings, his blessings, his love, his peace, his joy,
his sweetness, etc. are let forth upon, felt, and enjoyed by the soul,
in the new creation, in the new sense, in the denial and passing out of the old.

=== SOMEWHAT TOUCHING THE GOSPEL-REST, OR SABBATH

WHAT is the gospel-rest?
What is the gospel-sabbath?
Is it a shadow, as that of the law was?
Or is it the substance of that which the law shadowed out?

"`The law was given by Moses.`" Moses, by the command of God,
gave forth the shadows of the heavenly things under the law;
"`But grace and truth came by Jesus Christ.`" The true sabbath, the true rest,
the law of the Spirit of life, in and to the true Jews, comes by him.
The law of Moses had the shadow of the good things to come;
which good things themselves the gospel contains, bringing life and immortality to light,
and the soul into the enjoyment and possession of the heavenly things themselves.

The apostle disputes the case about both these, Heb.
4. both about the seventh day of rest, and about the land of rest;
showing that they were neither of them the substance;
they were but the rests which were to pass away.
But besides them, there was a rest remaining, a day of rest remaining,
a land of rest remaining; whereof they both (both the outward sabbath of rest,
and the land of rest under the law) were figures.

Now for whom did this rest remain?
Why, it remained for the true Jews, for believers,
for the spiritual circumcision in the times of the gospel.
"`And we (saith he) who have believed, do enter into rest.`" The faith gives entrance,
the Son`'s faith; the faith which stands in the power, the faith which is victory,
and gives victory over sin and the world,
removes the mountains and difficulties which stand in the way,
and gives entrance into the gospel-rest.
Faith, which is from and of the power of the endless life, puts sin under,
brings down self, gathers man into a new principle, brings man forth in a new principle,
causeth him to live and act in a new principle, etc.
And as man comes thither, and that life riseth and hath power in him,
it causeth him to rest from his own works, and to wait for and experience God,
in and through Christ, to work all, and be all in him.

The apostle Peter also speaks of this rest, and declares how it is attained,
even by suffering in the flesh,
"`He that hath suffered (saith he) in the flesh hath ceased
from sin.`" 1 Pet. 4:1. It is the fleshly part,
the motions in the flesh, from whence sin ariseth.

"`Lust, when it is conceived,
bringeth forth sin.`" Now Christ hath prepared and appointed a cross, a spiritual yoke,
to bring down the flesh,
which causeth great suffering in the flesh to him that taketh it upon him.
To deny all ungodliness, and every worldly lust, motion, desire,
and delight of the fleshly mind and nature,
there is a sore suffering to the earthly part;
but yet this bringeth down the earthly part in all that take it up,
and helpeth and causeth to cease from sin.
And he that hath taken up the cross wholly, and felt the thorough work of it,
and suffered in the flesh the parting with and crucifying all that is of the flesh,
that which would cause him to sin is slain in him, and he ceaseth from sin.
Then he is in the rest; then he keeps the rest fully; then he knows the yoke and cross,
which was once burdensome to him, to become easy and delightful,
that being worn out in him to which it was painful.

Now he that is in measure delivered, that hath in measure suffered, findeth some rest,
and may in some measure keep the sabbath; yea, in the faith,
the weakest babe (abiding there) cannot but keep the sabbath,
and offer up the sacrifices, and perform the services thereof to the Lord.
For the worship of the New Testament relates not to outward times or days;
but is in the Spirit, in the truth, in the name, in the power, in the substance,
on the day, and in the times and seasons which the Lord hath made, and makes,
in the spirits of his people.

And here that scripture is witnessed to those that are born of the Spirit,
and live in the Spirit, and walk after the Spirit: "`Sin shall not have dominion over you;
for you are not under the law, but under grace.`" Who are not under the law,
but under grace?
Why, they that are gathered by the grace, that hear the voice of God in the grace,
drawing and enabling them to follow;
they whom the grace overshadows from the power and dominion of sin; they are under it,
they are sheltered, saved, and preserved by it.

He that is born of God sinneth not, but obeyeth the grace; but he that committeth sin,
is the servant of sin, and not yet made free by the grace and power of the Son, from it.
Yea, the Son gives that freedom in his day from sin, and the power of Satan,
as they that are out of the light of his day cannot so much as believe;
but they that are gathered into, and walk in the light thereof,
they witness the law of the Spirit of life in Christ Jesus,
making them free from the law of sin and death.
What! is the stronger than the strong man come,
with his law and power of the endless life,
and shall not he manifest his dominion in the heart, over the law of sin and death?
Yea, as it is received, and let in, it works out, overcomes, bears down,
over-runs the law of sin and death; and that promise is witnessed, fulfilled, O death!
I will be thy death.

And if God, by the power and breath of his Holy Spirit, with the living,
powerful laws thereof, kill sin and death in the heart, what shall make them alive again?
No, no; then they are dead indeed,
and the kingdom and reign of Christ is witnessed in that soul.

Then the birth of life is witnessed; then the man-child is witnessed,
ruling with a rod of iron, dashing in pieces all motions and temptations to corruption,
and all that would defile, so that they cannot enter the mind;
and guarding it in the pure peace, unspeakable joy, and rest of the Son continually.
And there it is as truly witnessed inwardly (as ever it was at any time
enjoyed or hoped for by the Jews outwardly) that this horn of salvation,
which God hath raised up in the house of his servant David,
breaks all the horns of the oppressors, and gives rest to the soul from them round about,
that, without fear of them any more,
it may serve him in holiness and righteousness before him all the days of its life.

There are some good desires in many people, for which, blessed be the name of the Lord;
but there is great error of judgment, and wandering up and down from the truth,
for want of that which is able to stay the mind upon the Lord,
and to guide it in the right way.
Some run to this mountain, and sacrifice there; others to that hill, and offer there;
but few know the true resting place, or the place of the true worship.
Now in these their errors, they can witness no acceptance with the Lord.
Oh that they knew the acceptable thing, the acceptable way of worship,
and might appear before, and be found of, the Lord therein!
Then might they begin in that which is substantial, (in the gospel Spirit, life,
and power) and come to inherit and sit down in that which is substantial and everlasting.

=== SOME QUERIES / TO SUCH AS COMPLAIN OF WANT OF POWER TO BECOME THE LORD`'s, AND SERVE HIM; AND WHO ARE NOT YET SO ACQUAINTED WITH THE TRUTH AS TO WITNESS THE CLEANSING BY IT, AND CEASING FROM SIN

Query 1. Was not Christ made a king and priest after the power of an endless life?
And doth he not communicate of the power of that
endless life to all that rightly believe in him,
receive the truth as it is in him, and obey his gospel?

Query 2. Was it not the end of Christ`'s coming, to destroy sin in the heart,
and to set the soul free therefrom, that it might serve the Lord in the liberty, life,
and power of his Spirit?

Query 3. To them that believe in and receive him,
doth not Christ give power to become sons to God?
And to them that are sons, doth not the Father give the Spirit of the Son?
And hath not the Spirit of the Son power over the contrary spirit?

Query 4. Were not the deliverances of the Jews under
the law real deliverances from their outward enemies?
And are not Christ`'s deliverances as real from the inward enemies?
Whom the Son maketh free, are they not free indeed?
Free from sin, free from Satan, being under the shadow of the wing of the Almighty,
which preserveth out of the darkness,
and guardeth the mind from the evil and danger thereof?

Query 5. Is not Christ stronger than the strong man, whom he cometh to dispossess?
Are not his weapons stronger than the weapons of the enemy?
Is not he able to dispossess him, to cast him out, to spoil him of his goods and strength?
And when he hath gained the house, is not he able to cleanse it, and garnish,
and keep it clean and pure in the way of his covenant, against all the enemy can do?

Query 6. Doth not Christ dwell in the heart by faith?
And is not Christ`'s nature and Spirit pure?
and will he dwell in any thing that is impure?
Is not the spiritual temple under the gospel to be as pure inwardly,
as ever the outward temple under the law was to be pure outwardly,
or by way of representation?
Must not they be cleansed from all filthiness of flesh and spirit,
who witness the Father dwelling in them, and walking in them?

Query 7. Who offer up the incense and the pure offering in the times of the gospel?
Can any do it but the sons of Levi, whom the Lord hath purified?
Who can bring a clean thing out of an unclean?
Who can compass the altar of the Lord, or offer up an acceptable offering there,
whose hearts and hands are not washed in innocency?

Query 8. Is not the worship of the New Testament to be in spirit and truth?
Is not the Spirit pure, the truth pure?
Can any thing unclean enter into it?
Can any be in it, can any worship in it, but they which be cleansed, purified,
and changed by it.

Query 9. How did the apostle express the right manner
of drawing nigh to God in the spiritual,
gospel worship?
Was it not to be thus, with the heart cleansed from an evil conscience,
and the body washed with clean water?
And is not the presence, power,
and acceptance of God witnessed by them that appear before him and worship him thus?

Query 10. Had not other lords dominion over their heart, to subdue it to sin, and defile,
it, before Christ was known and received in his Spirit and power?
But when Christ is known and received in his Spirit and power,
have the other lords power to do so still?
Is not Christ`'s law, the law of his Spirit of life, able to bring under,
and make the soul free from the law of sin and death?
Insomuch as now it may be said in truth, by the souls whom he hath set free: "`O Lord,
our God! other lords besides thee have had dominion over us;
but (now henceforward) by thee only will we make mention of thy name.`"

Query 11. Was it not a brand of ignominy on those who had
got the good words and high notions about Christ,
but were not in the authority and power of his Spirit,
that they had eyes full of adultery, and could not cease from sin?
And he that receiveth the power of the new life,
is it not natural to him to cease from sin, and unnatural to him to commit it?

Query 12. Is not the Lord the teacher of his people under the new covenant?
Was it not promised of old concerning the gospel times,
and is it not fulfilled in the gospel times,
that "`all thy children shall be taught of the Lord`"? And what doth the Lord teach?
Doth he not teach to cease from doing evil, and to learn to do well?
And shall his children never learn this lesson of him?

Query 13. Whose servants are they that obey unrighteousness?
Are they clothed with the strength of God?
Do they stand in the power of his might against the power of the enemy?
Are they overcomers of the wicked one?
Or are they not rather daily overcome by him?

Query 14. What is the whole armor of God provided and appointed for?
Is it not to keep out the enemy wholly?
and is it able to do it, or no?

Query 15. Will not Christ say to all men upon the earth, profess they what they will,
hope in Christ, and cast themselves upon him for salvation ever so much,
and ever so often; yea,
though they have received such power from him as to preach in his name,
and to cast out devils in his name;
yet if they have not so received the power as to overcome sin in their own hearts,
and to cause them to cease from working iniquity, though they call him Lord,
and cry to him with confidence, "`Lord, Lord, open to us,`" yet will he not say to them,
"`Depart from me, ye workers of iniquity,
I know ye not;`" ye are not of the birth of my power;
ye are not those who have done my will;
ye were never by me redeemed out of the evil doing;
but have still all your days (notwithstanding your profession,
not withstanding your knowledge, not withstanding your owning me as your Lord,
and preaching in my name) been workers of iniquity?

Query 16. He that receiveth the spiritual circumcision and baptism of Christ,
doth it not cause him to cease from sin?
And doth not the new life spring up in him, which causeth him to live holily to God?
He that hath the offending eye plucked out, the offending hand cut off,
is not that taken away from him which caused him to sin?
And he who is created a new creature in Christ,
doth he not naturally do that which is holy and righteous? 1 John 3:7-8.

Query 17. Doth not the true faith, the faith of the Son of God, give victory over sin?
Can any believer be conquered by the enemy, he standing in the faith,
abiding in the covenant?
Doth not the power stretched out by the Father of life defend the soul
in the way of the covenant against all the assaults of the enemies,
so that the gates of hell cannot prevail against any here,
but the name of the Lord is felt a strong tower against them;
and though they encompass like bees,
yet in the name of the Lord victory is witnessed over them,
and against all that they can do?
And doth not the Lord teach and enable his to keep covenant?

Query 18. Was not such a thing witnessed by Paul (and may not such
a thing be witnessed by the believing and obedient travellers now):
"`I can do all things through Christ that strengthens me.
I know how to want, I know how to abound; everywhere,
and in all things I am instructed,`" etc.? I am armed with the whole armor of God,
and taught to stand so upon my guard in the power of his life,
that the enemy cannot come at me; but the power of the endless life so preserveth me,
as that the evil one can not touch me,
cannot enter me with any of his temptations in any condition.

Query 19. Was there not such a condition once witnessed,
and may it not be witnessed again,
of being more than conquerors through the love and power of Christ?
When the life doth arise in its power and dominion in the heart,
doth it not soon scatter the enemies?
Do they not fly away, and are chased at the blast of God`'s Spirit?
When the soul is filled with the love and with the power,
is not the land cleansed of what annoyed it?
And this, which is sometimes felt by many of the travellers,
may it not be an abiding state?
Are there not dwelling-places on Mount Zion (on the
mount of God`'s holiness in the gospel time),
and is not there security from sin, Satan, the soul`'s enemies, and dangers?
"`They shall not hurt nor destroy in all my holy mountain,
saith the Lord;`" and will he not fulfill it to those
that wait upon him in the way of his covenant?

=== THE CONCLUSION

THERE is a principle of darkness in the hearts and minds of men,
which is as a seed or root of corruption in them,
bringing forth in them fruits of sin and unrighteousness unto death.

And there is also a principle of the pure, heavenly light, as a free gift from God,
to discover the darkness, turn man`'s heart against it,
and lead him into the way and path of life.

Now as Satan rules in the principle of darkness, and there is the power of death therein;
so God rules in the principle of light,
and there is the power of life and redemption manifested by God therein.

For this principle is of the Father, of the Son, of the Spirit; yea, the Father, Son,
and Spirit are in this principle; and here the soul meets with them,
and is brought into union and fellowship with them,
and feels the everlasting arm revealed and stretched forth for its delivery from corruption,
and the captivity thereof, into the liberty of the sons of God.

And he that is here meets with the substance of things,
and that which all the types of the law shadowed out; meets with the one offering,
the cleansing which is thereby, the imputation of righteousness,
or of faith unto righteousness; yea, and with somewhat more,
even with the everlasting righteousness itself brought into the heart,
and dwelling there; insomuch as his nature is changed (truly changed) his spirit changed,
his mind, heart, soul, and conscience changed, his conversation changed,
the leopard`'s spots and the Ethiopian`'s skin washed away,
the deceitfulness of the heart removed, and the new garments of righteousness, life,
and salvation put on in the stead thereof; so that he is unclothed of the evil,
unholy nature and spirit, and clothed with the Spirit of the Lord.

For Christ is really made unto him wisdom, righteousness, sanctification, and redemption.
How is that?
Why he that once was a fool, is now made wise unto God, and the things of his kingdom,
by the mystery of his Son`'s life and power revealed in him.
He is a child of wisdom, and he hath heard the wisdom of his mother,
and learned wisdom of her.
So putting on Christ, who is the righteousness, being ingrafted into him,
being brought forth in him, he partakes of the sweetness and fatness of the olive-tree,
and is renewed into the image of the true righteousness and holiness,
and drinks in the virtue and life of the precious promises,
wherein and whereby he is made partaker of the divine nature,
and so cannot but witness redemption from the earthly, corrupt nature.

Now, it is not any striving, believing, or obedience of man`'s own spirit,
which can effect this; he may will strongly, he may run hard, and yet never obtain;
he may so cast himself upon the mercy of God, and hope concerning his mercy in Christ,
as to miss of it.

But the principle of life which is from God, and faith in God from that principle,
without fail effects this, and no other faith doth.
But out of this are the mysterious images and idols,
and subtle workings and devices of the cunning one,
to take up the mind with somewhat which appears as substantial and truly excellent,
but is not so indeed.
His birth hath desires after the kingdom (and makes no question but it shall be his),
wills, runs, strives, believes, hopes, prays, reads scriptures,
observes duties and ordinances; and in these they meet with a wrong knowledge,
a wrong sanctification, a wrong joy, a wrong confidence and assurance,
a wrong rest and peace; in which there may be a great warmth,
and seeming life and pleasure,
from the fire and sparks of their own kindling and blowing up,
which the mind that is blinded by him can hardly suspect that it is not true; yea,
may be taken with it, and strongly justify it in its own thoughts for the true,
and set it above that that is indeed the true.
This, this is the great mystery of iniquity,
which hath great subtlety of deceivableness in it,
to pick up and steal away the good seed out of the heart,
and to steal in a false image and likeness thereof,
which may have a more glorious appearance to man`'s eye than the
true seed itself (for that is the least of all seeds,
makes the least show of any), but hath not the same nature, virtue, and power.

Ah! the Lord God of tender mercy help all the poor souls that breathe after him,
that they may not be thus deceived.
And those that are thus deceived,
and in the snare of the enemy (and do not witness
the faith which hath the Son`'s dominion in it,
and gives victory over sin, Satan, and the world, and wherein the blood of sprinkling,
which livingly washeth, is felt, in the light of life,
wherein the redeemed walk to the praise of their Redeemer);
the Lord guide them also to that wherein all deceits are made manifest,
and where the truth which is of the Son,
is made to shine in such who were once in the barren places, and in the thick darkness,
but now are light in the Lord, and who have a dwelling-place with the Lord in his light,
which is the pure and everlasting habitation.
Amen.

=== A POSTSCRIPT / CONTAINING SOME FURTHER QUERIES CONCERNING THE NEW COVENANT

Query 1. WHAT is the new covenant?
Is it not an agreement between God and the soul in Christ, according to the law of faith,
as the old covenant was an agreement between God and the people of the Jews,
according to the law of works?

Query 2. Who is the Mediator of this covenant?
Is it not the Lord Jesus Christ?
Doth not he prepare the heart for the covenant, bring into the covenant,
keep in the covenant, preserve peace between God and the soul,
and keep the soul in the way of truth and peace?

Query 3. Who is the Shepherd, King, and Prophet in this covenant?
Is it any other than Christ, the Mediator?
Is not he the King and Prophet raised up to rule in righteousness,
and to instruct in the path of life?
And is not his Spirit able to teach and instruct in all things,
and able to govern and rule in righteousness all that are subject to his breathings,
quickenings, and holy movings, and instructions in their hearts,
who writes his law there, and guides and governs by the law which he writes?

Query 4. How come men into this covenant or holy agreement with God?
Is it not by repentance and faith?
Is it not by turning from the darkness, which is not of him, to the light which is of him?
Is it not by turning from the Spirit of Satan to his Spirit,--from
the standard and power of the wicked one,
to the standard and power of the Holy One?
What is it that God lifts up against the darkness of the enemy,
but the light of his Spirit, which discovers where a man has been, and what he hath done,
and gives him to repent thereof, and forsake all his dead works,
and turn to the life and power which instructs and quickens him,
in and by the Holy Spirit?
And this is true conversion; and thus a man feels the covenant of sin, death,
and hell broken, and enters into a new covenant, a pure covenant, a living covenant,
a powerful covenant, and comes to feel those things which the covenant contains,
as his condition requires, and as his capacity is made able to receive.

Query 5. How do men come to abide in this covenant?
Is there any abiding but according to the entrance?
Is there any staying in the covenant, but in and by the faith that lets in?
Doth not unbelief and disobedience keep out from it at first?
And doth not unbelief and disobedience cut off from it afterwards?
For there are sins against this covenant, as well as against the old?
and the sins against this are more dangerous to the soul than the sins against the old.
"`Take heed (said the apostle) lest there be in any of you an heart of unbelief,
to depart from the living God.`" And saith Moses, speaking of the prophet,
or angel of this covenant, "`Beware of him, and obey his voice;
for he will not pardon your transgressions, for my name is in him,
and whosoever hearkeneth not to this prophet,
he shall be cut off.`" How can it be otherwise?
For he speaks life, and he speaks it in the covenant to the circumcised ear,
to the soul in the faith, in the obedience.
Hear, and your souls shall live.
So then he that hears not must needs abide in death;
and he that departs from hearing him, must needs return to death.

Query 6. Whether there be any purifying of the heart, or any justification,
or keeping the vessel clean, out of the obedience of the truth?
"`If a man keep my sayings,`" saith Christ,
"`he shall never see death.`" "`If ye,`" saith the apostle, "`through the Spirit,
mortify the deeds of the body,
ye shall live.`" But if the deeds of the body be not mortified by the Spirit,
if a man do not keep the sayings of Christ, doth he, or can he, live then?
Is not this then the main thing in religion, that a man receive the truth in the faith,
and that he feel the power of the Spirit of life bringing
him into and keeping him in the obedience thereof?
For it is the truth that saves; the living truth, the living knowledge, the living faith;
the law of the Spirit of life that makes free from the law of sin and death;
and it makes free by its powerful working in the mind, working out, and preserving from,
that which defiles, captivates, and destroys.
For Christ comes with his power to save, with his power to break the bonds of darkness,
and to set the captive free: with his power to dislodge and dispossess all the enemies,
and sanctify the vessel to himself;
and the effects of his power in and upon the heart are his salvation;
and he that falleth short of the manifestation of the power of life to his soul,
and of the effects thereof in his soul, is so far defective in point of salvation;
for no man is saved further than he is redeemed and delivered
from that which Christ comes to save him from.

Query 7. Whether the first thing of all to be witnessed
in religion is not the Spirit of Christ?
Is not the whole work to be done by him?
And how can a man be certain concerning any work wrought in him,
unless he be certain that it is he that works?
How can I be certain concerning the knowledge given me,
unless I be sure it be he that gives it?
How can I be certain concerning any prayers or breathings arising in my heart,
unless I be sure they be from him?
How can I understand any scripture concerning Christ,
or the knowledge of any spiritual thing, unless I be sure he open it to me?
And how can I be sure of any thing that he giveth or openeth to me,
further than I know him, and have the true sense of him in his nature and operations?
So then, if the Spirit be my leader, guide, teacher, instructor in the way of life,
in the covenant of life, in the things of the kingdom, in the knowledge of scriptures,
etc., it is of great concernment to me to receive that ear and heart from God,
which knows and understands his voice; for, for want of this, are all the defects,
mistakes, miscarriages, and errors, in and about religion.
But as men come to this, they come out of error into certainty, and know the one Christ,
the one faith, the one baptism, the one body, the one church,
and assembly of the first-born, the pure love, which is of and in the truth,
the pure path of the kingdom, the way of holiness,
which the ransomed and redeemed walk in; yea, the Lord is One,
and his name One among all that are here, and the pure one language,
which is of the Spirit, wisdom, and teaching, is here received,
and the one voice of the Shepherd heard, etc.
But out of this are the janglings, strifes, contentions, debates, disputes; subtle, wise,
entangling reasonings of the earthly, one with another,
and all as one against the heavenly and spiritual.

Query 8. Did not the message which Christ sent his apostles to preach,
"`He that believeth and is baptized shall be saved,`" contain the sum of the covenant?
What doth God require of the soul,
but believing in his Son (which includes repentance from the dead spirit and works),
and receiving his baptism?
To be baptized into him, into his death, into his life, into his nature, into his Spirit;
to take up his cross, to bear his yoke, to be circumcised in him and by him,
that he may love the Lord his God with all his heart, that the power, virtue,
and life of love may constrain him to live wholly in and to God.
And then doth not the promise of salvation to him that believeth
and is baptized into Christ contain writing the law in the heart,
putting the fear into the heart; putting the Spirit within to become the teacher, guide,
strength, and comforter,
and whatsoever else is necessary to the soul in the way to the kingdom?

Query 9. How is God merciful to men`'s iniquities, and remembers their sins no more?
Is it not in the covenant, and according to the covenant?
Is there not a warfare to be accomplished,
before the soul come to witness the perfect blotting out of sin?
Is not Christ the Mediator, the Judge to whom all judgment is committed?
And doth not he judge his people for their transgressions
against the law of his Spirit and life?
And must not the soul, who will witness the days of refreshment,
and the perfect blotting out of sin therein,
wait upon the Lord in the way of his judgments,
even till sin be judged and brought under, and God`'s righteousness perfectly revealed?
Under Moses`' law every transgression received a just recompense of reward,
and shall he escape in the gospel who grieves the Spirit, who despises the Son,
and gives ear to the enemy?
Nay, nay; the same covenant that holds forth mercy to the tender brokenhearted,
to the believing, to the obedient,
contains also righteous judgment against the transgressor of this covenant.
Yea, judgment begins at the house of God,
and ceaseth not till that cease which judgment is to.
The Lord shall judge his people; shall not Christ judge his own family?
Yes, yes; they that are of the family, and in the true sense,
feel the Lord pleading with whatever is contrary to him in them,
and they can rejoice therein, and sing of mercy and judgment,
after the Lord hath done his work in them,
and brought forth the quiet fruit of righteousness in their hearts thereby.

Blessed is he that experienceth these things,
witnessing that from the Lord which preserveth out
of all mistakes and deceits about them.
