== An Inquiry After Truth and Righteousness

[.heading-continuation-blurb]
And after the people whom the lord establisheth, and will establish therein;

[.heading-continuation-blurb]
In some _Queries_ on Isaiah 58 and also on Chap. 54.

[.section-date]
1671

[.numbered-group]
====

[.numbered]
_Query 1._ Are there any people to be found who exceed
the state spoken of in ver. 2. of seeking God daily,
and delighting to know his ways, as a nation that did righteousness,
and forsook not the ordinance of their God?
They ask of me, said the Lord, the ordinances of justice;
they take delight in approaching to God.
Are there not many professions and sorts of professors at this day,
who in God`'s sight fall short of this state, and yet think highly of themselves?
Yet these the prophet of the Lord was not to spare;
but to lift up his voice like a trumpet against them,
because of their transgression and sin which they committed,
notwithstanding their thus daily seeking the Lord.

[.numbered]
_Query 2._ What was the transgression and the sins
which the prophet was not to spare them in,
but lift up his voice like a trumpet against them for?
Was it not (among other things) for their wrong fasting,
their wrong afflicting their souls, their wrong seeking of God, out of the meek, tender,
merciful spirit?
Doth God require such fasting or praying of any man?
Or will the Lord accept such fasting or praying at any man`'s hand?
Ah! how many fast and pray at this day, who never rightly considered,
nor truly understood, what the fastings, and what the prayers are which God requireth,
and which alone he will accept!

[.numbered]
_Query 3._ What is the fast which God requireth, and will accept in all ages?
Is not this it, "`To loose the bands of wickedness, to undo the heavy burdens,
to let the oppressed go free,
to break every yoke`"? etc. ver. 6-7. Who can understand or learn this fast,
but he that is taught of God?

[.numbered]
_Query 4._ Are there any whose light breaks forth as the morning,
and whose health springs forth speedily, and whose righteousness goeth before them,
and whom the glory of the Lord gathereth up,
or is a rearward to (as is promised to those who observe this fast),
and whom the Lord is ready to hear and answer in all that they call upon him for?
as ver. 8-9. Doth not God teach his children in the new covenant to observe this fast?
And they who are taught by him to keep it (and do faithfully keep it),
do they not inherit this promise?

[.numbered]
_Query 5._ Are there any now among the sons of men, whose light hath risen in obscurity,
and whose darkness hath become as noon-day?
Whom the Lord guideth continually, and whose soul he satisfieth in droughts,
and makes fat their bones; and makes them like a watered garden,
and like a spring of water, whose waters fail not?
Surely if there be any,
who are truly taught of the Lord to observe that which leads hereto,
they cannot miss of enjoying these precious promises:
for he is faithful and true who hath promised, ver. 10-11.

[.numbered]
_Query 6._ Are there any at this day, whom God honoreth in building the old waste places,
in raising up the foundations of many generations; in repairing the breach,
and restoring the paths to dwell in?
What are the paths that are to be dwelt in?
Are they not the same which the soul is to walk in?
Is not the just man`'s path and his dwelling-place all one, even the light of the living,
which he is both to walk and abide in?
See 1 John 1:7. and Prov. 4:18.

It is said concerning Christ, "`He that saith he abideth in him,
ought himself also so to walk, even as he walked.`" 1 John 2:6. How did Christ walk?
Did he not walk in the light of God`'s Spirit?
in subjection to God`'s Spirit?
Was not the fulness given him?
Was not the Father always with him?
And did not he act in the Father, and the Father in and through him?
Now, doth not he give forth a measure of the same Spirit, of the same anointing,
of the same power to become sons, unto all his?
And are not they to walk according to the measure of light and life they receive from him?
And he that walks according to this rule, can he err in so walking?
Is not this the pure path, the living path,
the path for the ransomed in the days of the gospel, who walk not after the flesh,
but after the Spirit; not in the oldness of the letter, but in the newness of the Spirit?
Oh that men could consider this with the true understanding,
and know the way of life in the true sense and experience thereof!
That which enlightens and gives life to my soul, is somewhat from Christ,
even a measure or appearance of his pure Spirit; it is no less:
and the law of life written inwardly is more to the soul than words written outwardly,
though all the words that ever come from God`'s Holy Spirit are very precious,
and greatly useful, to those to whom he vouchsafeth to give the understanding of them.

[.numbered]
_Query 7._ What is the sabbath spoken of, ver. 13? Is it the law sabbath,
or the gospel sabbath?
Is it inferior in nature to the fast before mentioned?
What is God`'s holy day, which is the soul`'s delight, the holy of the Lord, honorable,
wherein the souls that enter into the true rest (by
faith in him who is life) honor the Lord,
in ceasing from their own ways, pleasures, and words?
See also Heb. 4:3 and 10.

[.numbered]
_Query 8._ They that keep God`'s holy sabbath, do they not delight themselves in the Lord?
Do they not feel the pleasure of his day, and of his appearance in his day?
Are not these of the true seed of Jacob (who prevail with the Lord for the blessing)?
And doth not the Lord feed them with the heritage of Jacob, their father,
even with the blessing of the covenant of life and peace forevermore?

====

=== Some Queries on Isaiah 54

[.numbered-group]
====

[.numbered]
_Query 1._ Is there such a state to be witnessed, either in the particular,
or in the general, wherein the womb that was barren shall travail and bear,
and sing for joy of heart and spirit before the Lord?
See ver. 1.

[.numbered]
_Query 2._ Is there such a state to be witnessed, as of the Maker to become the husband?
Is not this a glorious state indeed, and a name better than of sons and daughters,
signifying nearer intimacy and union than any other relation with the Holy One,
the Redeemer of Israel?
And do not such as come to this state, even to be married to the Lamb,
partake more abundantly of his redeeming power and holy presence?
See ver. 6.

[.numbered]
_Query 3._ Are there some so visited and redeemed by the Lord,
as that they shall never be cast off more,
as that the floods of wrath shall never overtake them more,
nor the covenant of their peace be removed?
Ah, precious state!
Blessed are they doubtless, who have been so visited and redeemed by God`'s mercy,
as to be made partakers of it.

[.numbered]
_Query 4._ Who is this that hath been afflicted, tossed with tempests, and not comforted?
Have there been any such in our days,
who have been deeply afflicted for want of the presence of the Lord God of their life,
who have been tossed up and down with tempest after tempest,
and could meet with no comforter to speak a word in season to their weary souls?
And hath the Lord appeared to these, visited these, built upon these, comforted these?
Surely then, the poor whom he hath raised out of the dust,
and the needy whom he hath lifted off from the dunghill, cannot but praise his name.

[.numbered]
_Query 5._ Who is this, whose stones God lays with fair colors,
and her foundation with sapphires?
Whose windows God makes of agates, and her gates of carbuncles,
and all her borders of pleasant stones?
Was not the covenant of life so adorned in the apostle`'s days?
And is she not so adorned now again?

[.numbered]
_Query 6._ Whose children are they, who shall be all taught of the Lord,
and whose peace shall be great, who shall be established in righteousness,
who shall be far from oppression, so that they shall not fear; and from terror,
so that it shall not come near them?
Is there such a generation of the heavenly birth, of the covenant of life,
brought forth in this our day, who sanctify the Lord of hosts himself,
and make him their fear and their dread, but are not terrified with the wicked one,
nor with the snares and engines of the ungodly?
Surely they who are taught of God, have peace from him and in him,
and are established in the righteous Spirit and life of his Son;
they are like Mount Zion, which cannot be shaken or removed,
by all the terrors and oppressing devices of the ungodly.

[.numbered]
_Query 7._ By whom do they gather together, who gather together against such a people?
Certainly it is not by the Lord, nor by any advice or counsel from him;
but by the advice of that spirit which opposeth himself
against the power and work of the Lord:
and that spirit must fall for the sakes of those whom God hath raised up by his power,
and undertaketh to defend.
How tender was God of Israel after the flesh in the day of his delivering them!
See 1 Chron. 16:19, etc.
And will he not be as tender of his spiritual Israel,
in the day of his redeeming and delivering them?
Indeed, the opposition will be very great, but consider who shall have the victory,
see Rev. 17:14. Certainly it is true, and sealed by the Spirit of the Lord,
that patience, meekness, innocency, love, righteousness, etc.,
shall at length overcome all unrighteousness, enmity, oppression, cruelty, wrath, etc.,
and that spirit from which they proceed; and as they are overcome,
and when they are overcome,
the Lamb`'s Spirit shall reign and shine in the glory of the Father.
Oh! the sweet sense of this day, and further hope thereof;
how doth it bear up the suffering lambs,
in the midst of all their trials and tribulations!

[.numbered]
_Query 8._ Hath not God created the waster to destroy?
And hath not he power over him?
And doth not he limit him in the midst of his destroying work?
But did God create him to destroy his heritage?
or will God suffer him so to do?
They may indeed destroy the buildings which are not of God?
but God is the wise, great Master-builder, who counted his cost before he began,
and knew he was able to maintain his building, against all the oppositions and opposers,
which could rise up against it.

[.numbered]
_Query 9._ Can any weapon formed against the covenant of life, and the children thereof,
who are taught of God, and have peace from him,
and who are established by him in righteousness,--I say,
can any weapon formed against these prosper?
Every tongue that riseth up in judgment against them, doth not the holy tongue condemn?
Is not this the heritage of the servants of the Lord, in this our day?
And doth not the Lord say (whatever men say to the
contrary) that their righteousness is of him?
Indeed, whoever receiveth the true righteousness, receiveth it from the hand of the Lord,
and knoweth it to be of him.

====

And this testimony we have, even from the Spirit of the Lord,
who taketh away our unrighteousness and filthy garments,
and giveth us righteousness from and in his Son`'s righteousness,
even the very same wherewith the Son himself was clothed.
For as the seed is but one, and of one, Heb. 2:11.
so the righteousness is but one also.
Be not hasty in spirit, but wait to understand in the light and Spirit of the Lord,
which is wisdom`'s place of giving true understanding to her disciples.

It is true, there hath been great darkness,
and the true church hath been in the wilderness,
and the remnant of her seed hunted and persecuted
up and down the earth by the false church,
which hath been cried up for the true.
But, blessed be the Lord, the darkness is passing away, and the true light shining again;
which light discovers and redeems out of all that is false, into that which is true;
so that he that is truth, and no lie, is again known, and he speaketh truth and no lie,
and he anointeth with the true and holy oil of life and salvation,
all that are truly living.
And now the kingdom of darkness is going down,
and the kingdom of our Lord Jesus Christ raising up and exalting;
which is an inward kingdom, a spiritual kingdom, a kingdom of life, a kingdom of peace,
a kingdom of righteousness,
a kingdom of holy power and dominion over sin and death in the heart.
And this will spread and increase, to the blessing of persons, families,
and nations (as they come to be sensible of and subject
to the holy light and power thereof),
with the blessings of Abraham, wherewith all families and nations are to be blessed,
as they come to be unleavened from the serpentine spirit and wisdom,
and leavened with the innocency and righteousness of the Lamb`'s nature and Spirit.

The mighty God carry on his work,
by the same mighty arm of strength wherewith he began it;
and open the eyes of this nation, that they may see their proper hope and interest;
for indeed the Lord hath great love to this nation,
and blessing in store for it (for the seed`'s sake
which he hath sown and caused to spring up in it);
though many trials and tribulations must first be passed through,
and the spirit of enmity and opposition against the
appearance of God`'s Holy Spirit and power worn out.
Oh that men could come to that which gives the eye-sight,
that thereby they might see aright,
and no longer take the rise of their seeing from that spirit and wisdom,
which misrepresents things.

Written in Reading jail, in the tender love, true innocency, and uprightness of my heart;
which the Lord hath given me to suffer with for his truth`'s sake;
about the latter end of the 4th month, 1671.

[.signed-section-signature]
Isaac Penington
