== The Holy Truth and People Defended:

[.heading-continuation-blurb]
And some of the weapons and strength of the power of darkness,
broken and scattered by the Light and Power of Truth,

[.heading-continuation-blurb]
In _An Answer_ to the Chief Passages in a _Letter,_
written to me, and replied to by me, before my Imprisonment in this Place.

[.heading-continuation-blurb]
Where I have been a Prisoner above a Year and a Half, without any Law broken,
or Cause given on my Part, who only came Innocently and Peaceably to Visit my Friends in Prison.

[.section-author]
By me _Isaac Penington_

[.heading-continuation-blurb]
Prisoner for the _Testimony of Truth_
(for could I have denied _Truth,_ I might have avoided the _Snare_),
at Reading Jail.

[quote.section-epigraph, , 1 Sam. 2:4]
____
The Bows of the Mighty are broken;
and they that stumbled are girt with Strength.
____

[.section-date]
1672

=== The Preface

A Letter was sent me from a dear friend of mine (bearing
date the fifth of the eleventh month,
1671), who had long been greatly distressed,
and could not find relief in the way of her former profession and church-fellowship;
for whom I greatly travailed with the Lord,
and towards whom my spirit was made very tender by him.
I still felt the seal of God`'s love and mercy towards her, even in her lowest condition,
deepest despair, and sorest captivity, through her great and manifold temptations;
and my testimony to her at times, from the Lord, on this behalf,
was sometimes of use to her, to bear up her spirit,
till the day of God`'s visiting and redeeming her,
with the virtue and healing power of his salvation; which, blessed be his name,
she hath since had sweet experience of, and true peace and joy in knowing the true Head,
holding him in the faith, and being held by him.

Now, this letter of an ancient acquaintance of mine, which I had answered long ago,
one that belonged to Sir Henry Vane (as she signified
in her letter to me) desired she should see;
which is said to be an answer to a letter of mine.
If my answer had gone along with it, I should have took no further notice of it;
but it going without my answer,
lest it should do hurt to those to whom the Lord hath done or is doing good,
I am engaged in spirit to reply somewhat to it,
and to give forth to others what the Lord giveth in to me, upon this new occasion.
How greatly, truly, and purely I have loved the man, I will not boast (the Lord knoweth,
with whose knowledge herein I am content): but,
oh that this his paper might not be laid to his charge
at the great day! which (I am afraid) it will,
unless he repent of it; for indeed, it is not a fruit of life from God`'s Holy Spirit;
but of the growth of Egypt and Babylon.

It was sent me in the form of a book, as if it had been sent abroad for special service.
There was no name at it, as if it were an arrow to fly in the dark, and wound secretly:
but no weapon formed against the Israel of God shall prosper, either from this hand,
or any other; and every tongue that riseth up against them to judgment will God condemn.
This is the heritage of the despised people and servants
of the living God in this our day;
whose righteousness is the righteousness of his Son bestowed upon them,
wherewith he himself hath clothed them, as the anointed eye now seeth,
and all eyes shall one day see, and tongues confess, to the glory of God the Father.

=== The Holy Truth and People Defended

He excepteth against those words of mine to him in a former letter
(of Jan., 24. which I have not here by me),
That when his eyes are opened by the Lord,
he shall then acknowledge that we oppose no truths of the Lord,
but hold forth what we have received from him.

[.discourse-part]
To which he thus replieth:
Is redemption by Christ`'s blood no truth of the
Lord`'s? Which he chargeth one of us in particular,
and many others in general, with denying.

[.discourse-part]
Answer.
We are gathered into that, and abide in that, in which no truth can be denied;
and are in him that leadeth into all truth, and teacheth to deny no truth,
that ever was held forth by the Spirit of the Lord.
Some of us may not yet be grown up in understanding into the mysteries of the kingdom,
which God hath revealed and made manifest to others; but yet we do not deny,
but own one another in our several measures of knowledge and sense of things,
and in our several growths.
And we own and acknowledge, in God`'s sight,
the several dispensations he hath brought forth, both before the law,
and under the law and prophets, and in the time of Christ`'s appearance in the flesh;
and after, when he sent his Spirit, and all the time the church was in the wilderness,
and now she is coming forth again, in the brightness and glory of the Father,
looking fair as the morning, clear as the sun, terrible as an army with banners.
Nor do we disown any thing that is of God in the professors of this age;
but only that which we know, and are required by him to testify against,
as being not of him.
Oh that they could weigh our words and testimony in a right
spirit! for they would not then be so offended at,
and speak so against us, as now they do.
And the Lord knoweth we would do anything that lieth in
us to remove the stumbling-blocks that lie before them;
but it cannot be done to that spirit in them,
before which God Almighty hath laid the stumbling-block, that it might stumble, and fall,
and be snared, and broken, and taken.
But if they could come into another Spirit, and feel unity with, and the birth of,
another Spirit,
the birth of that pure wisdom should find no stumbling-block
or offense in this precious dispensation of truth,
wherewith God from on high hath visited us.

And as for denying redemption by the blood of Christ,
oh! how will he answer this charge to God,
when none upon the earth (as the Lord God knoweth) are so taught,
and do so rightly and fully own redemption by the blood of Christ,
as the Lord hath taught us to do! for we own the blood of the Lord Jesus Christ,
both outwardly and inwardly; both as it was shed on the cross,
and as it is sprinkled in our consciences;
and know the cleansing virtue thereof in the everlasting covenant,
and in the light which is eternal; out of which light men have but a notion thereof,
but do not truly know nor own it.
And let him consider, before the time of antichrist,
it was a great matter to know and own Christ outwardly, as he appeared in that body;
but since the antichristian spirit had got that,
the distinguishing knowledge and owning of Christ is, to know and own him inwardly.
The outward knowledge and confession now (as it is generally separated from,
and held forth in way of distinction from the inward)
is but the knowledge and confession of Babylon,
and not the true, living knowledge and confession of Christ,
in and by the Spirit of the Father,
which is the knowledge and confession of all the true and heavenly mother,
which is the mother of all that are born of the Spirit.

[.discourse-part]
He repeateth those words of mine, That we do not make any finite thing our righteousness;
but Christ of God is made unto us righteousness.
This, he saith, is well spoken, and wisheth we may always abide in this confession.

[.discourse-part]
Answer.
These words arose in me from an inward feeling of him who giveth righteousness,
and of the righteousness given; and the Lord preserving me in that life,
I shall feel so forever, and confess so forever.
And truly I can testify of no other righteousness; for, blessed be the name of my God,
I feel the righteousness of his Son revealed in me daily, from faith to faith.
In his name I have been gathered, in his name I live, and in him I feel righteousness;
and indeed there is nothing but righteousness, holiness, truth, life,
and salvation (and the like) in him.

And he that is truly in him, is righteous and holy in him;
there being in him a new creating of all that are there,
and a renewing into the holy and heavenly image,
which consists in the righteousness and holiness of truth.

He desireth me to give a plain answer to this question:

[.discourse-part]
Is Christ of God made our righteousness by faith in his blood, or in his Spirit?

[.discourse-part]
Answer.
A pretended faith in Christ`'s blood, without faith in his Spirit,
is but dead and notional.
"`Except ye eat my flesh, and drink my blood (saith Christ) ye have no life in you.
It is the Spirit that quickeneth:
the flesh (saith he) profiteth nothing.`" Now the faith must be in that which quickeneth,
and the faith in that which quickeneth is holy and righteous,
and the man who is found in it is justified, through that faith in the quickening power,
in the sight of God.
Thus Abraham was justified in the sight of God;
and thus are the children of Abraham to be justified,
even through believing in that holy power and Spirit which requireth obedience,
and justifieth the obedient, and condemneth the disobedient forever. Rom. 4:24.

[.discourse-part]
He saith, He fears a snake in this green grass, when I say, From his life, virtue,
and power revealed in us, is our conformity to him.

[.discourse-part]
Answer.
It were better and safer for him to fear at home; for the snake is in his own grass,
and many notional, high, soaring expressions, without true knowledge.
But can there be any conformity to Christ without his life, virtue,
and power inwardly revealed?
What else can conform unto, and bring forth in, the image and likeness of Christ?

[.discourse-part]
He saith, He feareth lest I make this life and virtue our righteousness,
which is indeed the fruits of it.

[.discourse-part]
Answer.
Who is this that darkeneth counsel by words without knowledge,
and runneth out from the truth into his own imaginations?
What was Christ`'s righteousness?
Was it not the life, the virtue, the Spirit of the Father in him, he being one with it,
in the faith of it, and in the obedience to it?
And is not the righteousness of the head and the body the same,
communicated from the head to the body?
Are they not all of one, and the righteousness one and the same in both?
So much of Christ`'s Spirit, so much of his righteousness; and out of his Spirit,
out of his righteousness forevermore.
For the righteousness of the Son is revealed, and communicated from faith to faith,
in his Spirit;
and so Christ is indeed made righteousness to them that are found in his Spirit;
and they are covered with the garment of righteousness and salvation,
who are covered with his Spirit.

[.discourse-part]
He saith, Our righteousness is before this.

[.discourse-part]
Answer.
What! is our righteousness before any of the life, virtue,
and power of Christ revealed in us?
Is God a respecter of persons?
Doth he justify any out of the holy covenant before he hath made a change in him?
How doth this man, with his vain imaginations,
turn the whole way and counsel of God upside down.

[.discourse-part]
He brings a scripture to prove this, The spirit is life for righteousness sake.

[.discourse-part]
Answer.
That scripture (which is Rom. 8:10) speaks of those in whom Christ is and dwells;
and there indeed "`the body is dead because of sin,
and the spirit is life because of righteousness.`" This is plainly spoken,
and plainly felt and known as it is spoken.
Oh that he had the true sense and understanding of it as it is in Jesus!

[.discourse-part]
He saith, Righteousness is in order of nature before sanctification.

[.discourse-part]
Answer.
That which is holy is righteous;
there is nothing righteous in the eyes of the pure God but that which is holy.
The head was really holy and righteous,
and they that are in him partake of his holiness and righteousness,
and are really holy and righteous in him; and faith, which purifies the heart,
and through which sanctification is,
must needs be in order of nature before the justification which is by it;
for God justifeth no unbelievers, but believers only.
Yea, the wicked must forsake his way, and the unrighteous man his thoughts,
and turn unto the Lord; which cannot possibly be without some degree of sanctification,
before the Lord will have mercy, and pardon the soul its sins.
Isa. 55:7 and chap.
1:16-18.

[.discourse-part]
He saith, Justification is an act of grace passed upon us by God freely,
without respect to us as godly; nay, properly reflecting on us in that moment as ungodly.

[.discourse-part]
Answer.
I charge this in the sight of God for absolutely false doctrine,
and contrary to the gospel.
For God justifieth no man as ungodly; but calleth upon men to repent,
and turn from their ungodliness, and he will have mercy upon them, justify and save them.
Now men are not ungodly in turning from their ungodliness, but changed;
and so their state is in some measure changed before justified.
If Abraham was ungodly when God called upon him; yet in forsaking his own country,
and following the Lord, and offering up his son, he was obedient, and not ungodly,
and in that obedience he was justified.
A man may have notions of justification in his mind,
and accordingly take himself to be justified, when he is not;
but there is no man justified by the Lord till he be changed,
translated into him in whom God justifeth,
out of the place of condemnation into the place of justification.
For till men are changed by the Spirit and power of the Lord, they are but darkness,
and in the darkness, where no justification is.
It is the believing, the obedient, the children of light, that are justified by the Lord.

[.discourse-part]
He saith, Were we godly before or at that time,
it were no act of grace to pronounce us righteous.

[.discourse-part]
Answer.
He that witnesseth salvation in Christ Jesus,
witnesseth it to be a continued act of grace.
Grace appears to the soul, grace teacheth, grace enableth,
grace maketh a change from the ungraciousness of the heart and state;
and then grace (or God by his grace in and through Jesus
Christ) forgiveth the sins that were committed before.
For though the Lord visit me with life, quicken me thereby,
make a change in my heart and state; yet it is his mercy to accept me,
and to pass by for his name`'s sake my former debts and trespasses against him.
Alas! the new covenant is wholly a covenant of grace and mercy; and the giving of Christ,
drawing the mind to him, accepting and justifying in him,
are works of grace and mercy towards his.
So the spiritual Israel may well sing this song in the land of holiness and redemption,
"`O praise the Lord! for he is good,
and his mercy endureth forever.`" I can truly set my seal to this thing;
that the more holy and righteous the Lord maketh me in his Son,
the more sensible am I of his love, grace, and mercy, in justifying of me;
and it is precious to me to witness justification
and acceptance with him in and through his Son.

[.discourse-part]
He saith further, But this is the bounty, the freeness, the munificence,
the riches of the grace of God, to call things that are not as though they were.

[.discourse-part]
Answer.
Take heed of abusing that scripture.
God sent Christ to renew, to redeem, to change, to make holy and righteous,
to make people such as the Father might be pleased with, accept, and justify;
and as Christ maketh them so, the Father receiveth and accepteth them as such.
But God doth distinguish and call things as they are.
He doth not call an ungodly man a holy man, a justified man;
but when he hath changed him, new created him in Christ Jesus,
took him out of his old stock, and planted him into the new;
then he accounteth and calleth him so, and not before.
It were better for men to wait upon God to understand
what his Spirit meant in what he spake,
than to put formed meanings of their own upon his words.

[.discourse-part]
He wrests my words, charging and reproving me, as if I said,
The love of God was a bare thing.

[.discourse-part]
Answer.
Those were not my words, nor did my words so signify; but my words were,
That it is not by bare loving (or mere loving,
or only loving) that God makes a man righteous; which is very true and manifest:
for there is, besides his love (in and through that love) the sending of his Son,
and revealing of his Son, drawing to and transplanting into his Son,
to make holy and righteous in him.
For holiness, though it may be distinguished,
yet it cannot be divided from righteousness;
nor can a man possibly be righteous in God`'s sight,
unless he be also holy in some measure.
His reflecting words hereupon I pass by,
though very unjustly and unchristianly cast upon
me (without any just occasion given him by words),
which I desire the Lord may make him sensible of, that he may be forgiven it.

[.discourse-part]
He blameth me for saying, We make no finite thing our righteousness, and yet he saith,
We make the measure of the Spirit (which each member of Christ receives) our righteousness.

[.discourse-part]
Answer.
A measure hath the same nature with the fulness.
A measure of the Spirit and life, of the grace and truth which comes from Jesus Christ,
hath the same nature that the fulness hath.
All the life, all the new creation that comes from him, and dwells in him, is righteous,
and found righteous wherever it is found.
Yet I do not remember that we have thus expressed it,
that that measure is our righteousness; but it is he who is the fulness,
who is revealed in that measure; and it is he who is our righteousness, our wisdom,
our sanctification, our redemption; but it is in the holy,
pure measure of the heavenly gift that he is made thus of God to us, not out of it.

[.discourse-part]
He saith, The Lord our righteousness redeems us,
not properly by the life and Spirit of his Godhead; though that was in the work,
supporting, enabling him, and carrying him up, in that great undertaking;
but by the death and sufferings of his manhood.

[.discourse-part]
Answer.
This is strange doctrine, to make the manhood the main Redeemer,
and the life and Spirit of the Godhead but the supporter
and carrier up of the man in the work of redemption;
whereas it was the Word which created all, which also redeemed; he that left his glory,
and made himself of no reputation, but came in the form of a servant, to do the will.
It was the Spirit and life of the Father (even the eternal Son) which took up that body,
appeared in that body, offered it up a pure and acceptable sacrifice to the Father,
finishing the work therein which the Father gave him to do. John 17:4-5.

[.discourse-part]
He saith, Shall we think to answer the law by our obedience?

[.discourse-part]
Answer.
We do not look upon the law of Moses, which was given to the Jew outward,
to be the dispensation of the new covenant,
or to be the law of the Spirit of life in Christ Jesus;
but those who are in the new covenant, and have God`'s law written in their hearts,
and his fear put there, which preserveth from departing from him,
and his Spirit put within them, to cause them to walk in his ways,
and to keep his statutes and judgments, and do them; and who live in the Spirit,
and walk not after the flesh,
but after the Spirit,--the righteousness of the law is fulfilled in these.
Yet they do not magnify and cry up their own obedience (nor call it their righteousness),
but him from whom their obedience comes.
For in the measure of his grace and living truth the soul is one with him;
and all that he is, and all that he hath done, is theirs;
and it is he himself that is the righteousness of all that are in him:
and they that abide in him partake of his righteousness from day to day,
which floweth in like a stream upon them.

I wish he could consider in what spirit it is that
he calls the white stone a ticket for the righteousness.
Doth he know the white stone with the new name?
It is no less than the foundation-stone, than the righteousness itself;
and what doth he talk of bringing that as a ticket for the righteousness?

He seemeth to pass by some things (which I speak in tender love and weightiness
of spirit to him) as the judgment of man in his day;
but let him take heed, when he comes to appear before God, he then +++[+++will]
find it was the judgment of God`'s Spirit in the light of his day;
which day is inward and spiritual, which believers are to hasten to,
and which approacheth in every heart, as the night spendeth and passeth away.
And all true Christians and believers ought to wait for the passing away of the night,
and the dawning of this day, and the arising of the day-star in their hearts.

[.discourse-part]
He saith, Christ is now ready to be revealed.

[.discourse-part]
Answer.
I believe he is to be revealed further, and in fuller glory;
but he is truly already revealed as the Saviour, Shepherd, and Bishop of the soul;
and many are gathered home to their resting-place in him, which,
while they were scattered up and down upon the barren mountains (before
the Shepherd appeared and made himself manifest) they could not find.

[.discourse-part]
He seems to strike at the peace and joy which is of God, and to give it a dash,
Because minds estranged from the enlightenings and
convictions of God have much peace in their ways,
and such are under delusions.

[.discourse-part]
Answer.
We do not tell men of the peace and joy we have in our God boastingly;
but in a faithful way of testimony concerning, and invitation to, what we once wanted,
but now have found, under the leadings of the true Shepherd.
And the peace and joy which he gives,
is an evidence and assurance in the hearts of those to whom it is given by him.
And they that have been greatly distressed for want of the Lord,
and his powerful arm of salvation, having met with it,
it riseth up from life in them to testify and say to others, Lo! this is our God,
we have waited for him, and we will be glad and rejoice in his salvation.
And oh that ye also were stripped of this dead, notional,
comprehensive knowledge concerning the Saviour!
That ye might meet with the Saviour himself,
and receive that knowledge from him which is life eternal.
And this, with the true peace and joy thereof from him, ye would find no delusion.

[.discourse-part]
He speaketh, Of suffering loss, and of phrases and expressions:
Better (said he) to suffer loss in these, than themselves to be destroyed.

[.discourse-part]
Answer.
Let him apply this home.
Oh that he saw how those phrases and expressions, and imaginary knowledge,
which he hath brought forth in this letter,
stand in his way to hinder the true knowledge;
and that he cannot possibly receive the true knowledge without being emptied of these,
and parting with them for the excellency of the knowledge of the truth as it is in Jesus;
and without the true knowledge of Jesus, men cannot but perish,
and be overtaken with destruction.

[.discourse-part]
Then for being helpful to establish persons in grace.

[.discourse-part]
Answer.
Such kind of doctrines as these do not tend thereto.

They may establish men in such a notion of grace as he hath formed;
but they neither tend to lead to, nor establish in, the grace itself,
but keep men from it.
Nay, I can truly say it from him that is true, that he himself cannot receive the grace,
the thing itself, till he part with these notions.
And oh that he might know the stone cut out of the mountain without hands to
dash his image! that the Living One (who gives life) might be received by him,
in that measure of grace and truth which he inwardly dispenses
to all that travel out of the darkness of their own imaginations
and conceivings upon the Scriptures into his pure light.

The main reason he giveth why he is not satisfied with that which I sent him,
concerning the sum and substance of the true religion, is;
because it fights with his notions, even a stating of our righteousness with God,
according to his imagination; which is absolutely a mere dream,
which he hath dreamed of in the night, and not seen in the light of the day.
For the cry of the Spirit of the Lord is in the gospel-day; "`Open ye the gates,
that the righteous nation, which keepeth the truth, may enter in.`" This is the truth,
as God hath revealed by his own Spirit, in this our day;
but to say this speaks of our state in him, without witnessing it in ourselves,
is but a mere dream; and men cannot bring forth fruit to God,
nor be lovely and pleasing in his eyes, but as their fallow ground is ploughed up,
the thorns, thistles, briars, and that which is unclean and unholy, removed.

[.discourse-part]
Christ, he saith, is the heavenly man, and mansion in whom we are thus blessed,
and in whom we sit down in a state of rest and reconciliation, heavenly and divine,
before and without the consideration of any works of righteousness which we have wrought, etc.

[.discourse-part]
Answer.
If he means this concerning the full sitting down in rest,
it is directly contrary to scripture.
For none sit down in that full rest,
before and without consideration of works of righteousness wrought by them.
For that great judgment is a time of rendering to every man according to his works.
Rest is the reward of the traveller, and his travels are not despised,
but considered in his reward.
Mark; every one that improved the talent, had a reward from his lord.
"`And come ye blessed of my Father, inherit the kingdom prepared for you:
for I was an hungered, and ye gave me meat,`" etc.
Mat. 25. And the apostle is of the same mind with Christ, when he saith,
"`It is a righteous thing with God, to recompense tribulation to them that trouble you,
and to you rest,`" etc. 2 Thess. 1:6-7.
So that persons do not sit down in eternal blessedness in Christ,
before or without consideration of any works wrought by them.

And then for sitting down in an heavenly, divine state of righteousness, rest,
and peace in him here; it is a glorious state to be travelled to.
There must be a translating out of the kingdom of darkness,
into the kingdom of the dear Son first.
The kingdom must first be come, and the soul prepared to enter into it,
at the gate which the Spirit opens to him in the way of the gospel.
For it is one thing to know somewhat of Christ, and to begin to become a disciple;
and another thing to learn of him so to deny a man`'s own wisdom and will,
as to come to receive and be born of that which is true and living of him;
and to learn to wait aright for the opening of the gate,
and entering into the kingdom and land of life, and to be prepared to sit down with him.

For there is a state of discipleship, wherein a man hardly knoweth a settlement,
so much as how to watch with Christ rightly and constantly;
but it is a great matter to be able to dwell and abide with him.
None can do this, but he that can dwell with devouring fire and everlasting burnings:
for the pure word of life is a fire, and he that sits down in the heavenly place in him,
must sit down in that fire.

This he reckons the firm, stable state, which indeed is no state at all.
There is not a state in Christ without being in Christ;
and then the state is according to the soul`'s being in Christ:
for then the work of regeneration, the work of sanctification, the work of justifying,
etc., goeth on; and a man is with God,
according as he is framed and new created in Christ, and not otherwise.
So that the life and power of the Lord Jesus Christ is found
judging and condemning whatever is not of God;
and justifying only what is of God in him.
For the soul then comes into the new covenant,
which requireth and justifeth that which is new, all that is wrought in God;
and condemneth all that is wrought out of him.
And so here is the true sense and knowledge of sin,
by the new and pure law of the new covenant; and the Advocate known,
and repentance given by him upon all occasions, to those that wait upon him,
and the sprinkling of the blood, and the remission upon repentance.
This is the new, living way of the Lord Jesus Christ,
which he hath consecrated for all his (made known in the
demonstration of his Spirit) which will stand forever;
whereas men`'s apprehensions about those things,
which they have gathered and comprehended of themselves out of the Scriptures
(in the supposed light of their natural reason and understanding),
are but dreams, and will vanish even in their own hearts,
if ever the true light arise there.

[.discourse-part]
He saith, This state can never fall, nor be finally fallen from.

[.discourse-part]
Answer.
There is a way of coming to Christ, and there is a way of preservation in Christ.
For there is a power that redeems;
and men are preserved by that power in subjection to it.
And so every one, that thinketh he standeth, is to fear, and to take heed lest he fall;
and not to boast and say, I am in a state of justification,
which is firm and cannot be moved; and it cannot fall, nor be finally fallen from.
"`For ye are kept by the power of God,
through faith unto salvation.`" Keep to the power which preserves,
"`hold that fast which thou hast, let no man take thy crown.`" Keep the faith,
make not shipwreck of it, and of a good conscience.
Oh that men knew the right doctrine and way of coming to Christ! which they cannot do,
till they are taught of the Father, John 6:45.
and the right doctrine and way of standing and abiding in him.
For truly men`'s professed coming to Christ, believing and standing at this day,
is generally notional, outward, without; but not in the inward life and power itself,
without which no man can come to him, nor stand nor abide in him.

[.discourse-part]
He chargeth us, With setting up a covenant of works; always doing and never done;
a covenant to be performed by us, for ourselves, not by Christ for us.

[.discourse-part]
Answer.
I would he saw in the true light how unjust and untrue this charge is.
For the Lord God of life knoweth that he himself hath taught us the new covenant,
and thereby taught us to wait upon himself in his Son,
to work all our works in us and for us; and this we daily experience,
that we can work nothing, but as he works in us.
Therefore our whole course is a waiting on him in stillness,
to witness him appearing and doing all in us; and blessed be his name,
we do not wait in vain.
But if he think all works are excluded out of the new covenant, he greatly erreth;
for the works of God`'s Spirit are required and have a place therein;
and God and Christ (the King and Shepherd) is the Judge of his people in the new covenant,
and justifieth or condemneth according to the law thereof.
In the faith and obedience he justifieth; in the unbelief and disobedience he condemns,
without respect of persons.

And it is a precious thing in the gospel ministration to come to God, the Judge of all,
and to witness true judgment set up by God in a man`'s own heart;
that by the ministration of the pure judgment there,
the soul may come to learn righteousness, of the holy Teacher and Shepherd,
even the Lord Jesus Christ, who is just and faithful under his Father,
in the impartial ministration of the new covenant.

Hereupon several charges he brings against us,
through his own mistakes and misapprehensions of us.

[.discourse-part]
As, _first,_ that our doctrine implies free-will and power in the creature.

[.discourse-part]
Answer.
We have never experienced free-will nor power, as of ourselves,
but as we have been turned to God`'s power, and received it from him;
nor did we ever testify to others,
that they could receive and embrace truth in their own will, and by their own power.
Oh that this person had true discerning of, and were severed from,
that spirit which thus chargeth us!
For whoever receives this testimony concerning the inward light of our Lord Jesus Christ,
shall never find himself able to do anything therein by his own will and power;
but there witnesseth God`'s begetting him out of his own will,
by the life and power of truth.

[.discourse-part]
_Secondly,_ He chargeth it, That it maketh the election of God altogether frustraneous.

[.discourse-part]
Answer.
Election of the seed, in the seed, it doth not at all make frustraneous;
but men`'s wrong apprehensions concerning election out of the seed,
the true doctrine of election doth not consist with.
He hath chosen us in him.
So that in him, to wit, in Christ, the choice is;
and he that will make his election sure, must make the seed sure to him;
growing in the nature thereof, wherein the election is to the truly obedient.

[.discourse-part]
He saith, Our righteousness with God is the foundation.

[.discourse-part]
Answer.
But is there not somewhat, which is the foundation of our righteousness with God?
And can we be righteous with God, till we come to that foundation,
and be made righteous by it?
Must we not first believe in him?
And is not faith a gift which comes from the holy root,
and maketh a change in them in whom this gift is found?
Doth not faith make a difference between them that believe, and them that believe not?
So that, so soon as ever there is true faith, and it thus works, the state is changed;
and there is no justification before faith.
For in the unbelief is the condemnation forever.
"`He that believeth not, is condemned already.`" And what! is he justified there too,
at the same time?
Was Abraham, our father, justified in the unbelief and disobedience,
or in believing and obeying God?
For what saith the scripture?
"`Abraham believed God, and it was counted to him for righteousness.`"

[.discourse-part]
That which I spoke of, he saith, Is but the fruit and superstructure.

[.discourse-part]
Answer.
When Christ directs men to the seed of the kingdom,
doth he direct unto the fruit and superstructure?
I spoke there of the seed, of the light, of the holy Spirit, of the quickening virtue;
is that the superstructure?
Or is that the fruit of men`'s being made righteous?
Nay; must they not turn to that, receive that, believe in that,
even in the light of God`'s Spirit (for they are the true and right believers),
before a man can come to be made righteous,
or accounted righteous in the eyes of the Lord?
For none are righteous, but in him; and all are out of him,
till they be gathered into him.

He instanceth in one passage of mine (in a book entitled,
"`The Sum or Substance of our Religion, who are called Quakers`")--the words are these:
This is the sum of all,
even to know and experience what is to be brought down into death, and kept in death;
what to be brought up out of the grave, to live to God, and reign in his dominion;
and what to be kept in subjection and obedience to him, who is to reign.
Now to experience it thus done in the heart, the flesh brought down,
the seed of life raised, and the soul subject to the pure, heavenly power,
whose right it is to reign in the heart,
in and by the seed,--this is a blessed state indeed; for here the work is done, etc.
These were my words.

Now mind: God is the teacher in the new covenant.
Now he that hath learned this of him, hath he not learned the true religion?
And is not this a full sum and substance of religion?
When the apostle saith, "`Pure religion, and undefiled before God,
is to visit the fatherless,`" etc.
Alas! might this spirit have said against the blessed apostle,
that is not the pure religion (not the sum or substance of pure and undefiled religion),
that is but a fruit or superstructure!
Oh that men had true sense and understanding!
That they might savor the words that come from God`'s Spirit,
and the words that come from their own spirit;
and might not be offended at that which is true, pure, and living of him.

[.discourse-part]
But having disliked this sum, he giveth one of his own, in these words following: I say,
the sum, and that which first and mainly imports us to know, as the Lord hath taught me,
is; That the old man is crucified with Christ, and brought down into his grave,
and that we are risen together with him, by the faith of the operation of God;
and from this faith to be working with God; to mortify our members that are on the earth.

[.discourse-part]
Answer.
Doth not Christ send his apostles to preach the gospel, and give them this message,
"`That God is light;`" and to turn their minds to the true light,
that they might be enlightened by it?
Doth it not import men first to know that whereby they might be crucified,
before they can know themselves crucified thereby?
So that Christ did judge this as the first thing
necessary to be known in the preaching of the gospel;
and bid men preach the light, and turn men to the light,
and to the inward appearance and voice of God`'s word in their hearts.
And what! are men risen together with him, by the faith of the operation of God,
while they are yet in their sins, in their ungodly state?
And how can any witness the faith of the operation of God in this state?
Now it had been better he had forborne affirming, that the Lord taught him this;
for truly the Lord never taught any thus.
This is not truth from God, nor will it be owned by the Lord as his truth,
when he comes to appear before him; and he should have took it to himself,
and not have put the name of the Lord to it.

But against this his own doctrine, he raiseth an objection in these words;
Shall we mortify that which is mortified already?

His answer is; The old man which is crucified together with Christ,
is the state of the flesh, and of enmity.
This is past away, and in this is the concern of our righteousness,
and justification properly.

[.discourse-part]
That which remains to be mortified, are our members upon earth,
which are the fruits of that evil state; and in the mortifying of these,
is the concern of our sanctification.
The will of God is done in heaven, etc.

[.discourse-part]
Answer.
Paul speaks of the law of sin in his members; and he also speaks of the body of death,
and cries out against that; "`Oh wretched man that I am,`" saith he,
"`who shall deliver me from the body of this death?`" He felt somewhat
that nourished and gave strength to the law of sin in his members,
and looked upon himself as wretched, till he could meet with deliverance therefrom.
Now some are of opinion that there is no being delivered from the body of sin,
while in this life.
Dost thou look upon it to be done in Christ, for us, without us;
but never to be done by Christ in us?
Let me tell thee, if ever thou come to witness the pure,
eternal light of the Lord Jesus Christ revealed in thee;
that will not find out some members on earth only, but the very body thereof;
and show thee the necessity of the putting off that body from thee,
and that circumcision whereby it is to be done, which is the circumcision of Christ.
Mark the promise of the new covenant: "`I will circumcise thine heart,
and the heart of thy seed, to love the Lord thy God with all thine heart,
that thou mayest live.`" Is not this the circumcision of Christ?
Doth not this cut off the body of the sins of the flesh,
in the particular where this is witnessed?
This is the truth, as it is in Jesus,
even "`to put off the old man with his deeds.`" It doth not say,
The body is put off in Christ without us, and men must only put off the members or deeds;
but, they must put off the body, and come to witness in themselves the very nature,
spirit, root, and principle from whence they proceed, cut down and destroyed in them.
They must feel the axe laid to the root of the corrupt tree,
and it cut down in them (not think it enough to say, it is done in Christ for them); yea,
they must also witness the Lord arising to shake terribly the earth,
in which the tree grew;
that so the place of dragons and serpents (where each lay
in times past) may henceforward become the place of holiness;
where grass may grow, and the new plants and flowers of the paradise of God.

And how is the will of God done in heaven?
Is it done in heaven after this manner?
Have mercy and righteousness the preeminence, the leading of the van?
(they are his own words) and said to go before,
and look down from heaven after this manner (the
body of sin being put off in Christ there)?
Are there not those here on earth, who dwell in heaven?
whose conversation is in heaven; even the witnesses to God`'s holy truth,
who are ascended up above the spirit of this world, and dwell in God`'s holy Spirit;
and who walk in the light, as God is in the light?
Hell is not far from the wicked;
nor is heaven far from them who are renewed in the spirits of their minds,
and who witness the passing away of the old things, and the new creation in Christ.
Oh that he could look back (in a true sense) and see how he hath wrested those scriptures!
Ps. 85:9-11, Isa. 4:2. and Eph. 2:6. after his own imaginations: and, indeed,
in this spirit, men cannot but turn the precious truth of God into a lie; that is,
as to themselves, as to their own knowledge of it.
It is known how the branch of the Lord is beautiful and glorious,
and the fruit of the earth excellent and comely, and in what day it is so; which day is,
When the Lord shall have washed away the filth of the daughter of Zion,
and shall have purged the blood, etc., by the spirit of judgment,
and by the spirit of burning. Isa. 4:4.
Then every one that is left shall be called holy,
and the branch of the Lord shall be glorious in the midst of them,
and the fruits of the earth excellent and comely for them.
And then they that are thus purged, shall sit with Christ in the heavenly places;
there being an abundant entrance ministered to them into the everlasting kingdom. 2 Pet. 1:11.

[.discourse-part]
_Thirdly,_ He chargeth it with making the obedience and sufferings of Christ superfluous,
except only as a pattern.

[.discourse-part]
Answer.
Christ came to do the Father`'s will; to obey, to suffer, to taste death for every man;
to fight with and overcome the devil; to offer a holy,
spotless sacrifice for all mankind,
that through him they might witness atonement and acceptance.
And the Lord saw the use of this, and we witness the use of this,
and find everything in its proper place and service in him,
who is God`'s covenant of life and peace in us, and to us.
But the work of this day is not to preach up a notional
knowledge of these things (the Christian world,
so called, hath been drowned and dead in them long enough),
but to bring to that measure of the Spirit, to that sense of grace and truth,
which is come by Jesus Christ;
wherein the benefit of these things is truly reaped and enjoyed; and, indeed,
that is the work committed unto us from the Lord, who gave us this testimony to bear,
whatever men may think or speak of us.

[.discourse-part]
And whereas he speaks of our laying hold of passages, in his printed sermons,
to favor our cause:

[.discourse-part]
Answer.
That is his mistake as to me; it was for his sake I mentioned it.
There was, indeed, at that time, somewhat stirring in him, which would have gathered him,
had he known and obeyed its voice, and not run out into lofty notions concerning it.
He had some sense then of a glory approaching, which he might have from the true Prophet;
though even then he ran out in his imaginations concerning it,
and did not rightly apprehend, nor know how and when it appeared.

[.discourse-part]
He hath further charges against us; Of crying up works against the work-man;
man`'s grace and righteousness against God`'s; conformity to Christ against Christ; yea,
to make a Christ of our righteousness, a Saviour of our conformity.

[.discourse-part]
Answer.
Oh, what will this man do,
when the Lord shall show unto him that he hath charged not so much us,
as the Spirit and power, and precious appearance of the Lord Jesus Christ,
with these things!
We cry up works no otherwise than we are taught of God,
and as the apostles and prophets have cried them up.
Faith is necessary, and works are necessary in their places;
and the justification of each follows them.
And he that receiveth the Spirit of the Son, and therein doth righteousness,
is therein esteemed of God righteous, as the Son is righteous. 1 John 3:7.
God justifieth us in his Son, and loveth his holy seed too therein,
and the faith that comes from him, and all the works that are wrought in him;
and out of this holy root of life and power, is no man, nor his faith,
nor his works justified.

Then for man`'s grace and righteousness.
Where doth he hear us speak of man`'s grace?
Oh! what doth he mean?
Will he misrepresent the cause of his neighbor or brother, to make it bad?
And for man`'s righteousness, we do not cry it up or put it on,
but testify men must be unclothed of it; and we ourselves were fain to part with it,
and put it off, before we could be clothed with God`'s righteousness.
But the works of life, the works of God`'s Spirit, the works of the new creature,
the works of the new covenant; these are not man`'s works, nor unrighteous works,
condemned by God; but justified in and through him that works them.
The works wrought in us are truly acceptable, and we in him who works them,
who is our righteousness.
And concerning this people (these children of the new covenant)
which the Lord hath begotten and brought forth in this our day,
that scripture is fulfilled in them, and upon them: "`Their righteousness is of me,
saith the Lord.`" Isa. 54:17. Well! as long as the Lord saith so,
we matter not though others say, that our righteousness is of ourselves,
and that it is our own righteousness;
being assured that God`'s testimony in our hearts (as to this thing) will stand.

[.discourse-part]
He aggravateth this charge thus:
And this to be done by those that have been so far enlightened,
and that account all the religion and profession in the world below them as carnal.

[.discourse-part]
Answer.
Indeed we magnify truth, life, the anointing, the spiritual,
the inward appearance of our Lord Jesus Christ, to which we have been turned,
and in it made spiritual; and all other knowledge, faith, profession,
religion (which hath not its rise there) we cannot but call carnal.
For the enlightening Spirit of the Lord hath given us this testimony to bear,
against all the dead, notional professors of this age,
who build from the letter (or rather their apprehensions of the letter) out of the life;
all which cry up names of the foundation and corner-stone; but refuse, reject, deny,
and turn from the corner-stone himself;
and have neither skill nor patience to try what he is, in this his pure, precious,
living, powerful, and glorious appearance in the spiritual light of his inward day,
after the long thick darkness of the foregoing night.
And woe would be unto us, if we did not thus testify!
For, for this cause we were born and brought into the world,
to testify to the present appearance of our God, and of his Christ, in this our day.
Glory to him who hath called and chosen us to,
and (in a true and precious measure and degree of
his own pure life) made us faithful therein.

[.discourse-part]
This (saith he) is so far from giving us a lift nearer heaven,
that I cannot more properly resemble it than to the coming forth of Amalek,
who met Israel by the way when they were come forth out of Egypt,
and smote the hindmost of them, etc.

[.discourse-part]
Answer.
Do not talk of having a lift nearer heaven.
Oh! learn the way, the holy way, the living way, wherein no dead, unclean thing can walk.
Learn to know God`'s Spirit in yourselves, from that which opposeth his Spirit.
Ye have been long learning, after your old conceivings and apprehensions of the letter;
oh! at length come to learn the truth as it is in Jesus, which discovers sin and death,
and the body of it, and crucifies and puts it off,
and makes room in the heart for him that is true and pure.

And then for Amalek`'s smiting Israel, oh, how greatly are ye mistaken!
Ye take yourselves for Israel, and us for Amalek; whereas, if your eyes were anointed,
ye would see that we have been begotten and born of God`'s Spirit,
through the Word of life, which was from the beginning,
wherein we have been circumcised with the circumcision made without hands,
that we might worship God in his own pure Spirit, and in his living truth;
and that our God hath inwardly appeared to us, and led us out of Egypt`'s land,
and out of Babylon also,
and all the lands whereinto we have been scattered in the cloudy and dark day:
and that this is Amalek`'s spirit in your several sorts of professors (through your
dark imaginations and conceivings about the letter) which riseth up against us;
and this spirit in you feareth not that God who hath appeared,
and by his own holy arm of power hath led, and is leading us.
So that we may take up the complaint of the prophet in this day,
"`Who hath believed our report?
And to whom is the arm of the Lord revealed?`" For though we speak what we have heard,
seen, and felt of the life which is eternal,
and of the "`Word which was in the beginning;`" yet ye are
so far from the witness of God in your own hearts,
that ye cannot receive our testimony, but oppose it with your dead, dry, notional,
conceited, imaginary knowledge,
which will stand you in no stead at all when ye come to appear before God.

[.discourse-part]
Then he proceedeth, complaining against us thus: Ah,
Sir! instead of clapping us on the back, and ministering to us in our journey,
you clog our march, and fall upon our rear.
Instead of serving the kingdom of Christ, which the church is now in travail of,
you deny the first principles of the gospel, and wholly disown,
the hope of Christ`'s second appearing and kingdom; knowing or acknowledging,
as no other Saviour, so no other kingdom, but a principle or a light in yourselves.

[.discourse-part]
Answer. "`God is light, and in him is no darkness at all;`"
and this is the message of the gospel. 1 John 1:5.

And Christ, who is one with the Father, he is one and the same light with him;
and we confess we look not for another besides him, nor for another kingdom,
besides the kingdom which is revealed in him;
for the kingdom which is revealed and manifested in and by him, is the spiritual,
eternal, everlasting kingdom, and there is not another.
We do not say the fulness, or that the full glory of the kingdom,
is now revealed or enjoyed (nay, we confess we have but the earnest, in comparison,
but a measure, a proportion);
but this is the same in nature and kind with the fulness itself.
And all that is of Christ, of his Spirit, of his nature, is saving;
the least measure of his grace that appeareth in any heart bringeth salvation with it;
the least touch of his finger hath pure life and saving virtue in it;
yet this is not distinct nor separate from the fulness, and so it is not another,
though it be not the fulness.

But whereas thou complainest of our not ministering to you in your journey,
but clogging it.
Oh that ye knew what your journey is,
and whither ye are marching and travelling in that present spirit wherein ye act!
We acknowledge it God`'s great love and mercy to us, to deliver us from that spirit,
and from that way of knowledge, religion, and worship wherein ye still abide.
And what we have seen and known from the Lord,
that are we required of him to testify to you;
and if your eyes were opened (by the principle of light from him) in the holy anointing,
ye would bow to the testimony; but judging of it in a contrary wisdom and spirit,
ye not only turn from it, but fight against it;
and reproach and slander us for our faithfulness to the Lord, and good-will to you;
which the Lord make you sensible of, and forgive you,
that at length ye may know and receive him (who is
the desire of all nations) in his pure,
living, inward, and spiritual appearance.

And as for denying the first principles; that belongs to yourselves;
for do ye not deny that light which is the foundation of all,
and wherein and whereby all the mysteries of God`'s kingdom are seen;
and instead thereof, set up a notional, comprehensive knowledge of your own conceiving,
comprehending, and gathering from the letter;
whereas no man can understand the letter but as he comes into and abides in the light?
This we have experienced in ourselves formerly;
for we were but guessing at and imagining concerning the letter, until we were turned to,
and our minds gathered into, and comprehended in, the light of God`'s Spirit.

And as for disowning the hope of Christ`'s kingdom, the Lord knoweth that is far from us;
for we ourselves bless him for what of his kingdom is already appeared,
and wait and hope for the further and fuller appearance thereof.
But this we confess, another Spirit, another Christ, another light, another life,
another power, another kingdom, besides him who hath already appeared, we do not expect:
for he is our King and kingdom both;
and the least proportion of his life and Spirit received (bought with the loss of all,
and so purchased and possessed) is no less than a pearl of great price,
and a heavenly kingdom to him that enjoyeth it.

[.discourse-part]
He addeth further: If Christ be but a principle, then we are no other;
and only principles shall be saved, and no persons: Is this your gospel?

[.discourse-part]
Answer.
Christ is the promised seed, to which all the promises are,
in which seed all the families of the earth are blessed, as they are gathered unto,
and grafted into, him.
But he is not only the seed, but the seedsman also; who soweth of his life,
of his nature, of his Spirit, of his heavenly image,
in the hearts of the children of men.
He giveth a measure of the grace and truth unto them,
the fulness whereof he hath received of his Father.
Now this measure of the light eternal is very precious,
and is that wherein he appears and manifests himself.
Yea, indeed, glorious things are both spoken and witnessed of the seed of life,
of the seed of the kingdom, of the grace and truth which comes by Jesus Christ;
but we never said that this seed or measure of life is the fulness itself,
but that which the fulness imparts to us, and brings salvation home to our doors by.
And if any man will receive Christ,
he must receive that from Christ wherein he manifests himself.
There is a difference between the light which enlighteneth (the fulness of light,
which giveth the measure of light, the measure of anointing to us),
and the measure or proportion which is given, the one is Christ himself,
the other is his gift; yet his gift is of the same nature with himself,
and leavens those that receive it, and abide in it, into the same nature:
so that not only the gift is one with him, but we also are one with him in the gift.
Come, be not thus wise after the flesh,
nor do not strive so (in thy wisdom and knowledge
out of the truth) to triumph over the truth,
and truth`'s testimony, in this the day of God`'s great love,
and glorious arm of salvation, revealed in the midst of his people,
which he hath gathered out of Babylon, and the dark knowledge thereof,
into the light and kingdom of his own dear Son; where he giveth them eternal life,
and of the fruits of the good and heavenly land.

[.discourse-part]
He addeth: I firmly believe, and so have all the saints that have gone before,
that Christ is a person,
and his Spirit is a living principle in the hearts of all the faithful;
but it is not the Spirit or principle in us that did redeem us, but the man Christ Jesus.

[.discourse-part]
Answer.
If he mean by the man Christ Jesus, the second Adam, the quickening Spirit,
the heavenly man, the Lord from heaven, he who is One with the Father,
the Word which was in the beginning, which created all things,
I grant him to be the Redeemer; for it was he who laid down his glory,
wherewith he was glorified before the world was, and made himself of no reputation,
but took upon him the form of a servant, and came as a servant, in the fashion of a man,
to do the will.
But if he distinguish Christ from this Word and Spirit,
and make the man`'s nature the Saviour,
and the Godhead only assistant to him (as he seemed to word it before,
and as these his words seem to imply), that I utterly deny.
For so testifieth the scripture, "`I am the Lord, and besides me there is no Saviour.
I am a just God, and a Saviour,`" etc.
So that Christ is the Saviour, as he is one with God.
It was God`'s arm and power (revealed in him) that effects salvation.
Yea, if I may so speak, his obedience was of value, as it came from the Spirit,
and it was the offering it up through the eternal
Spirit that made it so acceptable to God.
So that we must not attribute redemption originally to him as a man,
but as he came from God;
and bring the honor all back to the spring and fountain from whence he had all,
that God may be all in all, and the very kingdom of Christ may endure and abide forever,
in the root of life from whence it came.

And so he is not a foundation or the corner-stone distinct from God.
He, as the foundation, was and is the rock of ages, the spiritual rock,
both before and since he took upon him the body prepared for him.
It is the Spirit,
the life which was revealed in that man (by which he did his Father`'s will)
which was and is the foundation whereupon all the living stones are built.
There is a foundation of death, and that is the wicked spirit;
there is a foundation of life, and that is the Holy Spirit,
by which Christ himself was led and guided (in that his appearance in the flesh),
which descended upon him, and he was anointed with, and all his are to be anointed with,
and live in, the same Spirit.
And he that knows Christ in this Spirit, he hath the true and abiding knowledge of him,
and no otherwise.
And though the names Messiah, Jesus, Christ, Saviour, Anointed,
etc. were given to him as in the flesh, or as man,
they most properly and originally belong to him with
respect to the divine life and birth in him,
as the sent-one, and only-begotten, proceeding from the Father,
the brightness of his glory, etc.
For he, as the eternal Son of God,
was the spiritual rock before he took upon him that body which was prepared for him,
which expressly was called "`the body of Jesus,`" and
which he called "`this temple;`" and distinctly,
he being called Jesus Christ come in the flesh, which every spirit that confesseth not,
is not of God, but is that spirit of antichrist. 1 John 4:3.

[.discourse-part]
He speaketh of sitting on the throne of David.

[.discourse-part]
Answer.
It is a great matter to know that throne which David`'s throne signified,
and Christ sitting thereon.
His kingdom, his throne, are not of this outward, worldly nature,
but inward and spiritual; and his throne is in his kingdom and temple, where he reigns,
and is worshipped.
He that knoweth Satan dishonored and cast out, knoweth also Christ come in,
and sitting on his throne.
Oh that men did give over their dreaming about the heavenly glory,
and come thither in the leadings of God`'s Spirit where it is revealed!

Was the scripture written in vain concerning the glorious state of the gospel?
"`But we all with open face beholding, as in a glass, the glory of the Lord,
are changed into the same image, from glory to glory,
as by the Spirit of the Lord.`" 2 Cor. 3:18.

[.discourse-part]
He putteth up a prayer for us, that the Lord would awaken us,
and make us do our first works, and return to our first love.

[.discourse-part]
Answer.
Ah! poor man, how is he blinded! not discerning how the Lord hath done this for us,
and much more.
But it is he himself that hath lost his first love, and doth not do his first works;
but is found short of that tenderness, quickness, and savor that once was in him.
Oh that he might see it, and return to him whose quickening virtue restores and heals?

[.discourse-part]
He concludeth with the words of the prophet Jeremiah, chap. 13. ver. 15-17.
"`Hear ye, and give ear; be not proud, for the Lord hath spoken.
Give glory to the Lord your God, before he cause darkness,
and before your feet stumble upon the dark mountains; and while ye look for light,
he turn it into the shadow of death, and make it gross darkness.
But if ye will not hear it, my soul shall weep in secret places for your pride,
and mine eyes shall weep sore, and run down with tears,
because the Lord`'s flock is carried away captive.`"

[.discourse-part]
Answer.
How doth this man mistake in his sight and application of scriptures,
seeing and applying in a wrong spirit?
It is true, the Lord hath spoken; but he himself, and many such as he is,
have not given ear.
And what is the reason,
but because they are exalted above the pure principle of life in their own hearts?
And are not such proud?
Hath not he brought forth these weapons, these false charges and reasonings,
in this paper, against the heritage of God in the pride of his heart?
As for us, the Lord God hath humbled us, and taught us, who have learned,
and daily learn of him, in the humility,
and in humility and fear do we give forth our testimony,
though also in the authority and majesty of our Master`'s name,
whose name stands over and is exalted above every name,
and his mountain and gathering is (in the pure authority and power
of his Spirit) above all other mountains and gatherings whatsoever.
And as for God`'s causing darkness, let him, and such as he is, look for it;
for God doth not, nor will,
cause darkness to them whom he hath gathered into the light of his Spirit;
but saith to them, Arise, shine; for thy light is come,
and the glory of the Lord is risen upon thee,
O city and dwelling-place of the living God!
But those that know not, or turn against his appearance,
and cry up former dispensations of the same life and power,
but reproach and blaspheme the present,
on them doth he cause the gross darkness to fall and cover them.
And this which he threateneth us with, is already fallen upon himself,
when his feet are fallen upon the dark mountains; and whilst he looks for light,
he hath lost that which once he had;
and his very light (as he esteems it) is become obscurity and gross darkness,
and this dark paper of his (from the dark spirit and principle) makes manifest
to all that shall read it in any measure of true sense or discerning.
And truly my soul doth weep in secret for his pride and height of spirit,
in opposing the Lord, his truth, and people.
And for this cause shall those,
who have looked upon themselves as the children of the kingdom and flock of God,
be laid waste; and know, that as it was a dreadful thing to oppose Christ Jesus,
the Lord, in his appearance in flesh,
so is it also dreadful to oppose his appearance in his Spirit and power,
wherein he is arisen to set up his kingdom, and to throw down Babylon,
which is built in the likeness of Zion, but by and in another spirit.

Those in whom there is any tenderness towards God (and true breathings after
him left) the Lord give them the sense and true understanding of this inward,
spiritual appearance of his Son, and of what they have been doing, and are doing,
against it; that they may not continue to fight against the Lord,
and kick against that which is able to wound and prick, to their own hurt,
and eternal ruin.
For there is not salvation in any other name than in that which is now revealed;
blessed are all they that trust therein, it being not another,
but the same that ever was.

=== To His Postscript

He beginneth it with the justification of that passage
of his in a foregoing letter of his to me,
wherein he saith, Christ is heaven, and I am hell.

[.discourse-part]
Answer.
When God visiteth man, he finds him in union with hell, death, and darkness;
and the man is dead, is dark, is of a hellish nature and spirit in that state:
but when the Lord hath converted him, cut him off from that root,
leavened him with the Spirit and nature of his Son, is he hell still?
"`Ye were darkness,`" saith the apostle, "`but now are ye light in the Lord.
And such were some of you; but ye are washed, but ye are sanctified,
but ye are justified in the name of the Lord Jesus, and by the Spirit of our God.`"

A man can be but hell before he is washed,
before his filth be purged away by the Spirit of judgment and burning,
before the old leaven is purged out, and he sanctified and made a new lump;
but after the Lord hath thus changed him, and new-created him in Christ is he still hell?

[.discourse-part]
He saith: He doth not call the new creature hell; but there is an old man,
an outward man, as well as the new man, and the inward man;
flesh as well as Spirit in the regenerate.

[.discourse-part]
Answer.
What doth he mean by the outward man?
The sinful body, the body of flesh is within.
The outward body, that is not hell; that is the temple of God,
where the heart is sanctified: and the pure Word of life sanctifies throughout,
even in soul, in body, in Spirit, those that are subject to it.
"`Know ye not that your bodies are the temples of
the living God`"? And your spirits much more,
for God is a Spirit, and he dwells in a spiritual temple, and his temple is holy.

[.discourse-part]
He addeth: And unless your attainment be beyond Paul`'s, he found that in him,
that is his flesh, dwelt no good thing; and the flesh lusting against the spirit,
so that he could not do the thing that he would.

[.discourse-part]
Answer.
Paul did once experience such a state; that he felt himself carnal, sold under sin;
when he did not find how to perform that which was good, but did what he hated,
the law of sin being strong (in his members) against the law of life in his mind;
which state he calleth a state of captivity to the law of sin in his members,
and calleth it a wretched state. Rom. 7:23-24.
But did Paul never experience another state?
Did he never witness the virtue and power of the new covenant,
even the law of the Spirit of life, and the power thereof,
freeing him from the strength and captivity of the law of sin in his members?
There were young men, John speaks of, who were strong, and had overcome the wicked one.
Did Paul himself never attain to that state?
He bid others be strong in the Lord, and in the power of his might,
and showed them how to resist in it, so as to overcome.
Did he never experience and witness it himself?
He said, He had fought a good fight, and was more than a conqueror.
What! was he then a captive to the law of sin in his members, and did he then cry out,
Who shall deliver me from the body of this death?
He said, He could do all things through Christ that strengthened him.
Was not that a state different from that other wherein he found only to will,
and could not do the good he desired, but did the evil he allowed not, but hated?
And blessed be the Lord,
there are many at this day who witness a further
state of redemption and deliverance from sin,
and the law thereof in the members, than that state of captivity was,
which Paul there expresseth his former groanings and complainings under.
For he was not in that state of captivity when he wrote that epistle,
but knew the dominion of grace over sin, and bid that church, Be subject to the grace,
and not give way to sin, but yield their members servants to righteousness unto holiness,
chap.
6+++.+++ For that other place, of the flesh lusting against the spirit,
and the spirit against the flesh, Gal. 5:17. he doth not there speak of himself,
but of the Galatians, who were in a weak, low, and (indeed) fallen state,
from the Spirit and power of the gospel, having let in that which was contrary thereto.
And so he strives to gather them into the Spirit again, and bids them live in the Spirit,
and walk in the Spirit, and so they should not fulfill the lusts of the flesh:
for in the new covenant man is taught of God the holy lesson of ceasing from evil,
and doing good; and taught in the virtue and power of the covenant;
so that he learns daily, and grows daily out of deceit into truth,
until he come to be a true Israelite, in whom there is no guile.
And so in the spiritual war, the house of Saul grows weaker and weaker,
and the house of David stronger and stronger,
until Saul`'s kingdom be at length overturned and wholly destroyed,
and the kingdom of David established in righteousness forever and ever.
Then Jerusalem, the holy building, the city of the living people,
the city of righteousness (the habitation of righteousness, and mountain of holiness),
is known, and Jerusalem is witnessed a quiet habitation,
there being peace in all her borders.
Then the mind is fully stayed upon the Lord in all conditions,
and he keeps it in perfect peace.
Then the soul is careful for nothing;
but in everything makes its requests known to God by prayer and supplication,
with thanksgiving; and the peace of God, which passeth all understanding,
keeps the heart and mind through Christ Jesus.
Surely the apostle had learned himself (when he taught
others this) in every state to be content.
He knew how to be abased, and how to abound, etc.
Oh glorious state!
Oh pure state of pure life in the heart!
And what if I should add, Oh perfect state!
The apostle James saith, "`Let patience have its perfect work,
that ye may be perfect and entire, wanting nothing,`" or in nothing. James 1:4.
When Paul had so learned Christ that abundance could not lift him up,
nor want deject him, or cause him to repine or distrust,
what did he want of this perfect state?

[.discourse-part]
His next words are, If you have no sense of this,
your state is never the better to be liked.

[.discourse-part]
Answer.
Christ led captivity captive;
and the same power is revealed to lead captivity captive in us.
And truly when God leads our souls out of captivity, putting his fear within us,
writing his living, powerful law of life in our hearts, and putting his Spirit into us,
leading us in the way of holiness, and causing us to walk therein,
we find this a better state than when we were groaning under deep captivity.

[.discourse-part]
Further he saith,
If your peace and joy stand in seeing no sin yourself
(in yourself I suppose it should be),
I shall more than suspect it not to be the peace and joy of Paul and all the saints,
but a delusion.

[.discourse-part]
Answer.
Our peace and joy is in him who is without sin; and it abounds in us,
in his cleansing and delivering us from sin;
and we have found him remove sin as far from us as the east is from the west;
and as he removeth transgression from us,
and bringeth sin and the power of Satan to an end in us,
he giveth us of his peace and joy.
And truly we do not only witness him destroying sin and the works of the devil,
but breaking the very head of the serpent, casting him out, and piercing Leviathan,
that crooked serpent, and slaying the dragon that is in the sea.
And though such as he may suspect our peace and joy; yet, while Christ gives it us,
and maintains it in us, it is very sweet and pleasant to us; and the time may come,
that he may wish from his heart that he might partake with us therein.

[.discourse-part]
He concludes the matter thus: We are without sin in him, but in ourselves nothing but sin.

[.discourse-part]
Answer.
He spake of delusion just before; a greater than this I do not know.
For Christ doth make a real change; if any man be in Christ, there is a new creation,
there is a real change.
The man is not what he was before; but he puts off that which is old,
and puts on that which is new; and so is really changed in his state,
and in the sight of God, and is not what he was before.
The heart, when it is really renewed, and washed by the water, blood, and Spirit,
is not the old, abominable, wicked, deceitful heart that it was before.
If this be his knowledge and experience, let him keep it to himself:
for my part I desire not to partake with him therein; but to be like Christ,
my Lord and Master, even sanctified throughout in soul, body, and spirit,
that I may become wholly his, and the enemy of my soul have no part in me.

[.discourse-part]
He saith, Christ shall appear without sin to salvation.

[.discourse-part]
Answer.
I grant it; but when, and how?
Doth he not inwardly appear without sin to salvation to those who have waited for,
hastened, and come to, the inward day?
Doth not Christ appear without sin to salvation inwardly in the day of his own Spirit?
Is not salvation then witnessed for walls and bulwarks?
Is not the glorious salvation of the gospel brought forth in the gospel-day?
And is not there in the life and dominion of grace a pure defence about all the glory?
Is there any sin in the grace and Spirit of the gospel
which appears and shines in the day of the Lord?
And doth not this grace bring salvation to them that wait for the revealing of it?

[.discourse-part]
He seemeth to clear himself of watching for our haltings.

[.discourse-part]
Answer.
Had he not watched for our haltings, and received things into, and considered them in,
the prejudiced part, he could not have written such a paper against truth and us,
so far from true understanding and judgment as this is.

[.discourse-part]
But he saith, He hath watched for our repentings.

[.discourse-part]
Answer.
If we should repent of having our eyes opened by the Lord, and turning to his truth,
and receiving his Holy Spirit,
and of having the precious promises of the Scripture made good to us,
and fulfilled in us, we might justly lose our portion and inheritance of life forever.
We have repented from dead works; but we cannot repent of God`'s pure truth,
and the living way, spirit, and power thereof.
But this I can tell him, and that from the Lord, whose name I reverence and worship in,
that the Lord watcheth for his repentings,
and turnings from that spirit in him which darkeneth him concerning,
and prejudiceth him against, the truth.

He beseecheth me in love, etc., and requireth me to clear myself of free-will,
falling from grace, denying election of persons, and imputed righteousness.

[.discourse-part]
Answer.
What the Lord requireth of me, that I must mind;
and I have divers times expressed my heart nakedly in these things.

The principle of life which the Lord hath raised in me,
in that is the freedom to do good, and in that am I made free by Jesus Christ, my Lord.
And I had rather witness him upholding me by his power,
than contend about a notion of falling or not falling away.
And my care hath been about making my calling and election sure in him,
who is sure to those that are of him forever.
And I have witnessed the righteousness of the Lord Jesus Christ revealed in me,
and imputed to me, and my soul clothed therewith in his sight; blessed be his name.

Oh that the professors of this age might come to the anointing,
and see those things in the anointing! then would they know
the truth and harmony of the Scriptures therein.
But men, by the letter without the Spirit,
can never discern or find out the mystery of life;
but only gather into their minds and retain a literal knowledge, that killeth.

[.discourse-part]
He bids me, Love the truth better than a party.

[.discourse-part]
Answer.
The Lord knoweth he hath taught me so to do:
for had it not been for the evidence and demonstration of God`'s Spirit in his people,
I could never have owned them.
(For oh, how low was the knowledge they held forth, in my eye,
before the power of the Lord reached to my heart, raising up his own seed in me,
wherein I knew them!) And the Lord also knoweth, that it is in him that I love,
and discern, and honor them to this very day: yea,
I see his name written on their foreheads,
and them brought forth in the glorious image and heavenly life of his
Son (though it be hid from the wise eye of the professors of this age),
and in the true light, with the true eye (which God hath opened in me) have I seen it.

[.discourse-part]
He speaks of Clinging together, and keeping up a party against all right.

[.discourse-part]
Answer.
Nay, nay; this is the gathering of the Lord Jesus Christ by his Spirit and power,
after the long night of darkness; and we are kept up by the same Spirit, and power,
and life of truth, which gathered us.

[.discourse-part]
He saith, It is not a calling for a work within,
which will give you authority to lay waste Christ and the gospel,
in the most fundamental and concerning truths thereof, and those above mentioned, etc.
And above all the rest, denying the person of our Lord Jesus Christ,
and making him but a light, or notion, or principle in the heart of man.

[.discourse-part]
Answer.
This is but his own mistake, not a true and just charge against us,
as he will one day see.
The Lord hath not taught us to lay waste, nor do we lay waste any truth of the gospel;
but own everything in its place.
And though our religion do not lie in notions concerning him,
but in the principle of life itself, even in the grace and truth,
which is by Jesus Christ (which is a measure of light from him, the full light);
yet we do not learn thereby to deny the full light, but the more to acknowledge it.
And we own him to be the true and full light, and his outward appearance in that body,
in the fulness of time, to fulfill the Father`'s will therein;
and his appearance in Spirit and power in the hearts
of his people in the day of the gospel;
and his setting up his spiritual and glorious kingdom there,
where he reigns as king on the throne of David over the spiritual Israel of God.

Come, consider seriously:
Do not ye yourselves fall short of not only the principle and power of life,
but also of the true knowledge of things according to the letter?

[.discourse-part]
He confesseth, There is too little power; and without it profession is little worth.

[.discourse-part]
Answer.
Oh! that the professors of this age knew the Scriptures and the power of God,
and had that knowledge which comes from, and stands in, the power!
For then that evidence and demonstration of truth would be witnessed
which puts an end to the disputes and reasonings of the mind;
and then the great care would be to live the life of that
which God makes manifest and requires in the new covenant.

[.discourse-part]
He saith, To pull down the pillars and principles of the gospel,
is the work the devil employs his power in.

[.discourse-part]
Answer.
I grant what he saith is true (and wish he knew how rightly to apply it);
but there is a great error and mistake in his judgment about it.
For the Lord is pulling down that which men have built up, which they may,
in their mistaken judgments, call principles and fundamentals,
and is building up that which men have trampled on, even the tabernacle of David,
which hath long been fallen down; and the city of the living God,
which hath long been trodden under foot of the false Christians;
and the power of the devil is greatly at work to oppose
this appearance and mighty work of the Lord in this day.
Let him take heed of blaspheming the Lord`'s power, calling it the devil`'s,
and owning the devil`'s power for God`'s.

[.discourse-part]
He concludeth thus: Come to the point.
What singular thing do you more than moding and wording it,
save only that out of you have risen men,
that have more audaciously lifted up a standard against
the sealed and experienced truths of the gospel,
than ever I have heard or read of any before you?
You talk of words, and boast of perfection:
I tell you a humble sense of a man`'s nothingness,
driving him out of himself to live and glory in Christ alone,
is better than all such boasted perfections a thousand times.
Sir, accept my zeal for your soul.

[.discourse-part]
Answer.
We are a people (many of us) who have gone through
great distress for want of the Lord our God,
and exceedingly waited and longed for his living and powerful appearance.
And for my own part, this I can say, that had not this appearance been in power,
and in the evidence and demonstration of his Spirit to my soul, reaching to,
and answering that which was of him in me, I could never have owned it;
so deeply was I jealous of it, and prejudiced against it.
And since my mind hath been turned to the pure Word of life,
even the Word which was in the beginning (I speak as in the Lord`'s presence),
it hath had singular effects on my heart.
The light hath so searched me as I never was searched before,
under all my former professions;
and the Lord hath given me a true and pure discerning of the things of his kingdom,
in the light which is true and pure;
and singular quickenings have I met with from his Spirit,
and the faith which stands in his heavenly power, and giveth victory and dominion in him;
blessed be his name.
And the love which he hath given me is not notional,
but ariseth from his circumcising my heart, and answereth his nature;
springing forth purely and naturally towards him, and those of his image,
and all his creatures; yea, towards those who are enemies to me for his name`'s sake.

I might mention the patience also, and faithfulness to his truth,
with the long-suffering spirit, which cannot be worn out;
which his Spirit testifieth in me to be of a singular nature; with many other things.
Nor am I alone, or the chiefest; but have many equals; yea,
there are such as far exceed me in the heavenly and divine image of my Father.
And the fruits are according to the root of life in us;
and so acknowledged by all who look upon us with the true eye,
with the eye of God`'s giving and opening.

Now, the same that hath wrought thus inwardly in us,
the same hath required some outward behavior and expressions from us,
which are foolish and weak to the eye of man`'s wisdom,
but chosen of God to hide the glory of this life from that eye which discerns it not,
but despises the day of small things.
And though this be the least part of our religion (yet subjected to,
because it is of God, whom we dare not disobey in the least),
yet the spirit which is contrary to God casteth this upon us, as if this were all,
or at least the main, wherein we differ from others.
Some call the living words of truth from us (when God, according to his good promise,
giveth them us) but canting;
and thou callest all that is singular in us but moding and wording of it.
Alas! it is in the main we differ from you;
we holding our religion as we receive it from God, in the light and life of his Spirit:
you, as you apprehend it from the letter.
Christ is our rock and foundation, as inwardly revealed;
yours but as outwardly conceived of.
We believe with the faith which is of the nature of him whom we believe in,
which faith is mighty through God, and works through all the powers of darkness,
giving victory over them all, in God`'s way and time;
ye believe with a faith which esteems victory,
and a perfect and entire state (wanting nothing) as impossible while in this world.
And as our root differs, so all that grows up in us differs from yours:
so that indeed all is singular that is in us,
and all also is singular that is brought forth by us, as the Spirit of the Lord,
who knoweth the difference of things, witnesseth.

Have we so long walked in the name and Spirit of our God amongst you,
showing the singular virtues of his Spirit daily in our faithful testimony, sufferings,
patience, and conversation?
And do ye still cry, What singular thing do ye?
Just like the Jews, who, after all Christ`'s mighty works,
and demonstrations of his Father`'s virtue and power outwardly, asked for a sign.
Oh that your eyes and hearts were opened by the Spirit and power of the Lord!
for then ye would soon see otherwise in this respect than now ye do.

And then as for that expression,
Of audaciously lifting up a standard against the
sealed and experienced truths of the gospel,
that is but an over-confident expression,
through prejudice and mistake of judgment at least:
for I can truly testify I have never learned,
since the pure heavenly light of the Lord Jesus Christ hath shined on my spirit,
to deny any one truth that ever was sealed to me, or experienced by me,
in the days of my former profession;
for whatsoever was then of God hath been restored to me,
and that only which was of the flesh pared off.
And I have ground also to believe,
that it is so with others in this respect as it hath been with me.

[.discourse-part]
He speaks, As if our difference or talk were about words.

[.discourse-part]
Nay, it is about things:
for though we own the same Lord Jesus Christ to be the foundation of life;
yet after a different manner.
Ye, as ye notionally apprehend concerning him; we,
as we experience him to be the precious stone and foundation of life in us.
And we testify of justification and sanctification,
as we witness him bestowing it upon us, and working it in us.

But for boasting of perfection, I wonder how he dares speak thus!
What! is there no fear of God before his eyes, or in his heart,
that he dares charge us with that which is so utterly false?
Where is any of us that did ever boast of perfection?
But that God`'s power and covenant is able to make perfect,
and that God`'s will is our perfect sanctification in soul, body, and spirit;
even that we be wholly leavened with the salt of the kingdom,
and become a fit temple for him.
This we humbly and reverently testify of, and press towards, in his holy name and fear.

And as for that humble sense, Of a man`'s own nothingness, drawing him out of himself,
to live and glory in Christ alone, this we meet with,
and witness in that light which this generation of professors despiseth.
But others, though they may talk of it, can never come truly to witness it,
but in that light wherein God bestoweth and preserveth it.

Well, the professors of this age, who despise the light, shall one day find,
that what they take themselves to be, they are not, in God`'s sight; nor are we,
before him, what we are reproachfully represented by them;
but "`we are his workmanship in Christ Jesus,
created by him unto good works;`" and that it is natural to us to
bring forth the fruits of righteousness and holiness to our God,
however men reproach us.

As for his zeal for my soul, which he desired me to accept, it is strange zeal,
and would tend to my utter destruction, had it power over me; but blessed be my God,
who hath called me into the light of his Son,
and I am satisfied that he will preserve me therein,
even in that holy Spirit of life which he hath gathered me into,
from all deceivable spirits of darkness whatsoever,
in that holy covenant wherein his strength appears to me, and is revealed in me.
And oh,
that he might know what that spirit is wherein he hath thus appeared
against the Lord (though under a pretence as if it were for him),
and bring forth no more the fruits of it!

For a close, I shall add a few words on that scripture, Phil. 3:3.
"`For we are the circumcision, which worship God in the Spirit,
and rejoice in Christ Jesus,
and have no confidence in the flesh.`" It is a precious thing
to witness this scripture fulfilled in the heart;
to experience that there, which inwardly circumciseth,
which cutteth off the foreskin of the heart, which lieth over it and veileth,
till it be cut off by the inward appearance of the life
and power of the Lord Jesus Christ inwardly revealed.
Then when this is done, I can truly and sensibly say, I am a Jew inward.
How so?
How can that be proved?
Why, I am inwardly circumcised.
I have felt that within which circumciseth the heart,
and have borne the inward pain and cutting thereof, and am circumcised by it.
That which stood between me and the Lord is cut off, the veil is taken away,
the stiff-neckedness and unsubjection to God removed,
the wall of separation is inwardly broken down,
and now I am in true unity of Spirit and communion with my God, even with the Father,
and the Son, in that One Holy Spirit wherein they are One.

Now I can bow before the Father of our Lord Jesus Christ,
and worship him in his own Spirit, even in the new and fresh life thereof day by day.
Now my rejoicing is in Christ Jesus, whom the Father hath sent,
both outwardly in a body of flesh to fulfill the holy will,
and do what therein the Father had for him to do,
and also inwardly in his Spirit and power unto my heart,
to destroy the works of the devil there,
and so to work me out of the enmity and unreconciled state,
into the love and reconciliation.
And I cannot but rejoice both in what he did in his body of flesh for me,
and in what he doth by his Spirit and power in me.
And, blessed be the Lord, I feel him near, his Spirit near, his life near,
his power near, his pure virtue near, his holy wisdom near, his righteousness near,
his redemption near; for he is my rock, and my strength, and my salvation, day by day.
And I have no confidence in the flesh, in what I am, in what I can do after the flesh;
but my confidence is in him, who hath weakened me, who hath stripped me,
who hath impoverished me, who hath brought me to nothing in myself,
that I might be all in him, and that I might find him all unto me.
He is my peace, he is my life, he is my righteousness, he is my holiness,
he is the image wherein I am renewed; in him is my acceptance with the Father;
he is my Advocate, he is my hope and joy forever.
He hath destroyed that in me which was contrary to God, and keepeth it down forever.
He is my Shepherd, his arm hath gathered me, and his arm encompasseth me day by day.
I rest under the shadow of his wings,
from whence the healing virtue of his saving health droppeth upon my spirit day by day.
Oh!
I cannot tell any man what he is unto me; but, blessed be the Lord, I feel him near,
his righteousness near,
his salvation daily revealed before that eye which he hath opened in me, in that true,
living sense wherewith he hath quickened me.

And now, ye that have high notions, and rich,
comprehensive knowledge concerning these things, but not the thing itself,
the life itself, the Spirit itself, the new and living covenant, and law of life itself,
wherein alone Christ is livingly revealed,--ah, how poor, miserable, blind,
and naked are you,
in the midst of all your traditional knowledge and
pretended experiences concerning these things!

Come, be quiet a while, and cease from bitterness of spirit,
and reviling the work and people of the Lord; for the Lord knoweth,
and will make manifest, both who are his and who are not his.
All the living stones are his; but the great professors of the words of scripture,
without the Spirit and life of the Scriptures, are not his, nor ever were,
nor ever will be owned by him.

Come, learn to distinguish from God by his life, by his anointing, by the everlasting,
infallible rule, and not by words without life,
where the great error and mistake hath been in all ages and generations.
The great way of deceit hath long been (and still is) by a form of godliness,
without power: be sure ye be not thus deceived; for if ye miss of the power which saves,
ye cannot but perish forever.
And what if the appearance of the Spirit and power of our Lord Jesus Christ inwardly,
which is that which saves, be as strange to your sense, understanding, and judgment,
as his outward appearance was unto the people of the Jews?
Take heed of their spirit, take heed of their judgment,
who judged according to the appearance of things to them,
which they imagined and conceived from the Scriptures,
but judged not the true and righteous judgment,
which only the children of the true wisdom can.

=== Postscript

There are four or five things very precious,
which were generally witnessed in the days of the apostles among the true Christians,
which are all mentioned together. Heb. 6:4-5.

[.numbered-group]
====

[.numbered]
_First,_ They were truly enlightened.

The ministers of the gospel were sent by Christ, to turn men from darkness to light,
and from the power of Satan to God. Acts 26:18.
1 John 1:5. And they were faithful in their ministry,
and did turn men from the darkness and power of Satan to the light of God`'s Holy Spirit;
and they were enlightened by it, and received power through it,
and so came to be children of the light, and to walk in the light,
as God is in the light.

[.numbered]
_Secondly,_ They tasted of the heavenly gift.

What is the heavenly gift which Christ gives to those who come unto him,
and become his sheep?
He gives them life, eternal life. John 10:27-28.
He brings them out of death,
and gives them a savor and taste of the life which is eternal.
This was it which the apostles testified of,
even of the life which was manifested in that body
of flesh of our Lord Jesus Christ (1 John 1:2);
and they that turn from the darkness to his light,
he gives them a taste of the same life.

[.numbered]
_Thirdly,_ They were made partakers of the Holy Ghost.

The gospel is a day of bringing forth the spiritual seed,
and of pouring out the Holy Spirit upon them.
The law state is a state of servants; the gospel,
of sons! and because true believers in Christ are sons,
God sent forth the Spirit of his Son into their hearts to cry, Abba, Father.
And God cannot deny his own Spirit to his children that ask it of him;
he knoweth how absolutely necessary it is to the state of a son;
and whosoever truly receiveth Christ, Christ doth give him power to become a son;
which power is in, and with, and cannot be separated from, his Spirit.
Yea, the Spirit of Christ is so necessary and inseparable from him that is Christ`'s,
that the apostle expressly affirms, that "`if any man have not the Spirit of Christ,
he is none of his.`" Rom. 8:9.

[.numbered]
_Fourthly,_ They tasted of the good Word of God.

Of that Word from which the gift comes;
of that Word which was in the beginning of the world,
which is ingrafted into the hearts of those that truly believe;
which Word is able to save the soul.

[.numbered]
_Fifthly,_ They tasted of the powers of the world to come.

Of the power of the endless life, whereof Christ is the Minister,
and according to which he ministers life, in that holy, true, living, inward,
spiritual temple,
which he pitcheth and reareth up for an habitation to God in his own Spirit.

====

Now, in the apostasy and night of darkness which hath come over the Christian state,
these things have been greatly lost.
For there have been none that have been found able to turn
people to that light which the apostle directed to.
None could tell men where the light is to shine, and where men were to expect it,
and wait for it.
None were able to direct men to the seed of the kingdom within, to the Word of faith,
the Word of the kingdom, nigh in the heart and mouth;
much less were they able to instruct men how they
might know and distinguish it from all other seeds,
and the voice of the Shepherd from all other voices.
Here it came to pass, that though at times God visited and opened men`'s hearts,
a little warming them by the breath which came from himself;
yet they not knowing how to turn to the Lord,
and wait upon him for preservation in the gift and measure of his own grace,
the good hath soon been stolen away from them,
and the building which hath been raised up in them hath
not been a building of life according to the Spirit,
but a building of wisdom or knowledge concerning
the things of God according to the flesh;
and so the building that hath been raised up in men`'s spirits hath been Babylon,
instead of Zion.

But the Lord hath had a remnant all along the apostasy, who felt some begettings of life,
and had in measure some sense and taste of the heavenly things.
These mourned after that state which was once enjoyed, and felt their want of it,
travelling from mountain to hill, seeking their resting-place,
which none could rightly inform them of.
Now, for the sakes of these, God hath at length appeared.

How appeared?
may some say.

Why thus: he who is light hath appeared inwardly, causing his light to shine inwardly,
causing his life to spring inwardly; so that he who is light, who is life, who is truth,
is felt and known in his own inward visits, breakings-forth, and appearances.
For God, who is a Spirit, his appearance is spiritual, his day is spiritual,
his kingdom is spiritual, his light is spiritual, his life is spiritual,
his day-star is spiritual; and his day dawneth, and his day-star ariseth in the heart.

Thus the day-spring from on high did visit us, who sat in darkness,
and in the region of the shadow of death.
And here we have met with what the apostles met with, the very same light of life,
the very same enlightening Spirit and power, and have been enlightened by it,
and tasted of the same gift.

The very same grace that appeared to them, and taught them, hath appeared to us,
and taught us; and of it we have learned the same lessons,
in the same covenant of life wherein they learned;
and now can we seal to their testimony in the same Spirit wherein they gave it forth,
and witness to the same eternal life, and the same holy oil and anointing,
our eyes having been opened and kept open by it.
And though there be great disputes about our testimony in this
our day (and the present professors rise up against us,
as the former professors did against them);
yet let but any man come rightly to distinguish in
himself between that which God begets in the heart,
and all other births,
and let that speak and judge in them,--that will
soon confess that our testimony is of God,
and given forth in the authority and by the commission of his own Spirit.
True wisdom is justified by the children that are born of her;
it is the other birth that doth not, nor can, own her.
The other birth can own former dispensations (according to the letter of them);
but not the life and power of the present.

I have known the breaking down of much in me by the powerful hand of the Lord,
and a parting with much (though not too much) for Christ`'s sake.
The Lord hath brought the day of distress and inward judgment over my heart;
he hath arisen to shake terribly the earthly part in me (yea,
what if I should say that the powers of heaven have been shaken also),
that he might make me capable to receive, and bring me into,
that kingdom which cannot be shaken.
And now that which God hath shaken, and removed in me, I see others build upon,
and they think it shall never be shaken in them; but such know not the day of the Lord,
nor the terrible searching of his pure light, nor the operation of his power,
which will not spare in one, what he hath reproved, condemned, shaken,
and overturned in another.
He that knows the living stone within, and comes to him as to a living stone,
and is built upon the revelation of his Spirit, life,
and power (revealed inwardly against the power of darkness), is not deceived.
All that otherwise build (I mean upon an outward knowledge concerning Christ,
and not upon his inward life),
their building will not be able to stand in the day of the Lord.
I wish they might have a sense of it in time, that they might not perish forever;
but experience that life and power of our Lord Jesus Christ,
which redeemeth and preserveth out of the perishing state forever and ever.
Amen.
