== The Ancient Principle of Truth: / Or the Light Within Asserted;

[.heading-continuation-blurb]
And held forth according to true experience,
and the faithful testimony of the Scriptures
_in the answers to four questions._

[.heading-continuation-blurb]
I+++.+++ What this Light is which we testify of, and what is the nature of it?

[.heading-continuation-blurb]
II. What it doth inwardly in the heart?

[.heading-continuation-blurb]
III. How it cometh to be lighted, set up, and increased there?

[.heading-continuation-blurb]
IV. How it cometh to be diminished or extinguished in any?

[.heading-continuation-blurb]
Also _An Appeal_ to the witness of God in all consciences,
which is the more sure Word of Prophecy;
the testimony of the Scriptures without,
or the voice and testimony of the Light and Spirit of God within, in the heart?

[.heading-continuation-blurb]
By one once greatly distressed, but now at length, in the tender mercy of the Lord,
effectually visited and redeemed by the Light and Power of Truth,

[.section-author]
Isaac Penington

[.section-date]
1672

=== Preface

The true ministers of the gospel, the ministers of the new covenant,
were ordained and appointed by God to be ministers of light, ministers of righteousness,
ministers of the Spirit. Matt. 5:14.
2 Cor. 11:15. chap.
3:6. And this was their work and service, even to preach the light,
to deliver their message concerning the light, which they heard of Christ,
and were sent by him to preach,
as is recorded 1 John 1:5. So that they were to tell men what the light was,
and where it was to be found; and to turn men from darkness to light,
from sin and unrighteousness to purity and righteousness,
from the spirit and power of Satan to the Spirit and power of the living God,
(Dan. 12:3. Acts 26:18) that so they might come from under Satan`'s authority,
power, and kingdom of darkness, into the light, wherein Christ reigns as King, Priest,
and Prophet, unto and over all his; who is faithful in all his house,
and Son and Lord of all, distributing life, righteousness, mercy,
and peace to his whole family, as they abide in him,
and walk in subjection to his Spirit.
So that there is no condemnation to them that are gathered unto Christ,
ingrafted into him, and who abide in him (walking not after the flesh,
but after the Spirit) who is the quickener, guide,
and rule of all the children of the new covenant.
For Christ is the way, the truth, and the life, in and to them all,
and is made by God all in all unto them.
He is their Shepherd, their King, their Captain, their vine, their olive-tree,
their leader, their door, their path, their rule, their righteousness, their holiness,
their wisdom, their redemption, their altar, their sacrifice, their priest,
their prophet, their sabbath, their light, their day-spring,
their bright and morning-star, their sun, their shield, their rock, and their high tower.

What shall I say?
God hath gathered together all things into One, even in him, whose Spirit, life,
and light eternal is the One substance,
which answers all the figures and shadows of the law, and they are all comprehended,
and fulfilled, and end in him.
So that he is the end of the law for righteousness, to all that believe in him.
And he ministers righteousness, he ministers truth, he ministers life,
he ministers salvation, he ministers power, he ministers pure, heavenly wisdom;
and no good thing will he withhold from them that
come unto him in the drawings of his Father,
and follow him whithersoever he leads, and obey his gospel,
which is everlastingly new and living.

Now, this precious ministry hath been withdrawn, and hid from ages and generations,
in the long night of the great apostasy and thick darkness.
And how could it be otherwise?
For men being in the dark, and having erred from the true Spirit,
and let in a wrong spirit, and built up wrong churches;
and having not known the true wilderness (nor being willing
to flee into it) whither the true church fled,
and was nourished by God with the true food, even with the true,
living virtue and nourishment, all this dark night of the apostasy,--I say,
how could they come at the true light, the true Spirit,
the true power (from which the true ministry is), which did not visibly now appear,
but was with the true church in the wilderness?
So that there hath been a true church all this while,
which the gates of hell have not been able to prevail against,
as to her inward temple and altar (nor over the worshippers which have worshipped therein),
although they have gained the outward court;
God having severed it from his inward building, and given it to the Gentiles in spirit;
who are not true Jews, who are not worshippers in the Spirit, and in the truth. Rev. 11:1-2.

But now, at length, blessed be the Lord, the long night of darkness draws towards an end;
yea, is come to an end in many spirits;
and the true light is broken forth again (and shineth again inwardly in many),
and the true ministry is revived again,
and the everlasting gospel (the everlasting covenant of life, mercy, and salvation,
in and through Christ Jesus, the light and life of men) preached again.
For now it is not only outwardly read,
that "`God is light;`" but the message hath been received, and persons chosen,
and sent forth by God to publish it; and to turn men from darkness to light,
and from Satan`'s power to God.
And, blessed be the Lord,
the publishing of this precious testimony (in the power
and authority of the Most High) hath not been in vain.
But the captivity of many hath been broken by the power of light,
and the power and strength of darkness (inwardly) overturned by it.
Oh, how hath the strong man, which kept the house,
before the stronger than he appeared in the name and authority of his Father,--I say,
how hath he trembled at the inward and spiritual
appearance of him that was stronger than he!
And how have the pillars of the old building been shaken!
How hath the witness of God been reached to in men`'s spirits!
How have the dead been raised, the blind eye opened, the deaf ear unstopped,
the dumb tongue loosed, the lame caused to leap as a hart,
and the tongue of the dumb to sing, the inward, spiritual leprosy cleansed,
and done away forever, the wounded healed, the brokenhearted bound up!
And what hath not the Lord done inwardly and spiritually for his people,
who have been sensible of his appearance,
and gathered by his Spirit and power to the true Shiloh, who is the true Shepherd,
the land of the living, the holy city and temple, the light of the city,
the life of the city, the gates and wall of the city, the king and kingdom both!
For his life, his nature, his Spirit is all, and in all.
Ah! what do we desire to have, but Christ the seed,
and this seed sown in our hearts and abiding in us, and his life,
righteousness and glory, his holy power, dominion, and kingdom springing up in it?
And as, in the apostles`' days there was the seal to their testimony in people`'s hearts,
where their ministry was ordered by the Lord, and was received; even so it is now.
Oh, how doth the witness answer in men`'s hearts and consciences!
And they that keep to the witness, and its testimony,
not hearkening after words to the wisdom of the flesh;
how do they become living epistles, to be seen and read of all men,
as the Lord pleaseth to open that eye in any, which can see and read.

Now, to be often testifying of this light (which the Lord hath visited us with,
and wherein we experience the knowledge of his Son, and redemption by him),
to us it is not grievous; and it is good and safe for others.
Therefore, it arising in my heart, in the springings of life,
and lying upon me (as in the sight of the Lord) to give forth this further short testimony,
for the sakes of such as have any desire to know and experience the truth,
as it is in Jesus; I am given up in spirit to serve my God therein;
and do give it forth in humility, in fear, in tenderness of spirit, in true love,
with breathings to my God,
that he would please to open the hearts of those that shall be inclined to read it,
that they may feel somewhat of that in themselves, from which the testimony came;
and so therefrom may hear, in true sense and understanding,
the true and good report of the sound of life and salvation in this our age,
and may learn so to turn inwardly from the darkness to the light,
from the power of Satan to God`'s Spirit and appearance inwardly,
that the arm of the Lord may be revealed in them, and powerfully stretched out for them.

And this is the precious knowledge of Christ indeed,
even to know Christ the power of God, Christ the wisdom of God,
inwardly revealed and working in the heart, destroying sin there,
and building up the holy building, where he himself will dwell and reign.
Oh that all that truly breathe after him,
might not be withheld from him (and his living testimony,
and inward appearance) by the power of darkness and deceit,
which works subtly in the heart against the appearance, power,
and work of the Lord there, but might thus come to know him!
Amen.

=== The Ancient Principle of Truth, etc.

==== Question I

What is this light which we so earnestly testify of, and whereof we affirm,
That all men are, or have been, in some measure, enlightened by it?
And what is the nature of it?

==== Answer

It is that which shineth from God in the heart, wherein God is near to men;
and wherein and whereby men may seek after God, and find him.

God is a spirit; and his Spirit and presence is near to all men.
"`Whither shall I go from thy Spirit?
Or whither shall I flee from thy presence?`" Ps. 139:7 etc.
It is impossible for any so to do.
For God, who is a Spirit (and the Father of spirits), is nigh to every spirit.
Every spirit depends upon him, the fountain of spirits; and hath its being, life,
and motion from him, and in him, after a sense; though not after such a sense,
as they who are quickened by him experience.

Now God, who is light, being so near every man, doth he never shine upon them?
They are darkness; but doth he never appear in the darkness?
He who is light, loveth mankind; doth he never visit them with his love?
He knoweth what and how great inward and spiritual enemies mankind have;
doth he never make any discoveries of their enemies to them?
Yes; the light is near all mankind, to discover to them,
and help them against the darkness;
and the love is near to help them against the enmity which destroyeth,
and so to save them.
For whosoever joineth to the light of God`'s Spirit,
cannot but witness salvation thereby; for it is of a saving nature,
and bringeth salvation with it to all that receive it.
Christ is in it, and is known by it (inwardly, spiritually, livingly known),
and he is not, nor can be, known without it.
He that knoweth the light of God`'s Spirit knoweth Christ;
and he that believeth in it believeth in him; and he that knoweth not,
nor believeth therein, neither knoweth nor believeth in Christ.
So that as the Jews`' circumcision outward,
and their knowledge and thinking to be justified by the
righteousness and works of the law (which most of them brake,
and were transgressors of; though Paul said, he was,
"`touching the righteousness which is in the law, blameless`"),--I say,
as this was disowned, and denied by Christ and his apostles; and the circumcision,
and work of God on the hearts of the Gentiles set over it, and exalted above it, as Rom.
2 so is it now also.
The knowledge of those, and belief of those, who own the light, and believe in the light,
is owned by God`'s Spirit (in this our day) for the
true believing in the Lord Jesus Christ,
and for that knowledge which is life eternal; and the knowing and believing on him,
as men account it, according to their apprehensions of the letter, without this,
is reckoned with God for ignorance and unbelief.

So that in this is God known, in this is Christ believed in.
Here God draws nigh to every man, and is a God not afar off, but nigh at hand;
and his salvation is nigh, and his righteousness ready to be revealed here;
and here every man may seek after and obtain the knowledge of him, the saving knowledge,
the knowledge of the grace, of the gift of grace which brings salvation.
In this is the Son kissed, in this is he drawn nigh to, and come to by the soul,
and not out of it.
Here are the drawings of the Father felt.
Let any man feel this, he feels that which begets to God;
he feels that which comes from the Son, is of the nature of the Son,
wherein the Father draws the heart of the child whom he begets, to the Son.
And in this as the soul comes,
it comes out of the darkness wherein Christ is not nor dwells,
into the light wherein Christ is with the Father; and so in this the soul is ever near,
and out of it still afar off.
In this is the holy root witnessed, and the ingrafting thereinto;
out of this the holy root is not known,
nor can men understand what it is to be ingrafted into him, and how he is an Olive-tree,
a Vine, a Door, a Shepherd, a Leader, a Captain, a Redeemer.
Nor can men possibly know the voice of the true Shepherd from the voice of a stranger,
till they come hither; nor how the true Shepherd walks before his sheep,
and what it is to follow him out of that which destroys, into that which regenerates,
makes new and living, till they come hither.

Now this inward light is abundantly testified of in the Scriptures.

[.numbered-group]
====

[.numbered]
As _first_ by Moses, who speaking of the other covenant, the new covenant,
the covenant of circumcising the heart,
turneth or directeth the mind to this word of commandment nigh,
whereby alone it can be done, as Deut. 30.
And this was the reason why God so often commanded
the Jews to circumcise their hearts,
and to wash them and make them clean from their wicked ways and vain thoughts;
because Moses had directed their minds to that, and that was near to them,
wherein and whereby it might be done.
In another place, he bids them make them a new heart. Ezek. 18:31.
How could that be done?
Why, by turning to God`'s Spirit which strove with them,
his power would effect it in them; and men are said to purify their hearts,
through the Spirit, in loving and obeying the truth which doth it. 1 Peter 1:22.
John 17:17.

[.numbered]
_Secondly,_ By Job, who speaks of God`'s candle shining upon his head,
and of walking through darkness by his light, chap.
29:3. He speaks likewise of those that rebel against the light,
that know not the ways thereof, nor abide in the paths thereof, chap.
24:13.

[.numbered]
_Thirdly,_ By David, who by it saw through the types and shadows to the substance,
and grew wiser than his teachers, he knowing the word within,
and having his candle lighted by it,
so that he knew the inward law which converts the soul,
and was led by God`'s light and truth shining in his inward parts. Ps. 43:3.

[.numbered]
_Fourthly,_ By Solomon, "`The commandment is a lamp, and the law light,
and the reproofs of instruction the way of life.`" Prov. 6:23.
Every one that experienceth the light,
the law, the commandment within, knoweth it to be thus.
Again, saith he, "`The path of the just is a shining light,
that shineth more and more unto the perfect day,`" chap.
4:18. Just as a light, which shines outwardly, is to the outward man;
such is the inward light to the inward man; yea more:
for inwardly the light and the way is all one.
Christ is the way, the truth, and the life,
which are three names of one and the same thing.
And he that walks in the light, walks in the way of life and holiness;
which he that walks in the darkness walks out of.
I shall mention but one place more, which is very differently rendered, it is chap.
20:27. The new translation renders it thus: "`The spirit of man is the candle of the Lord,
searching all the inward parts of the belly.`" The old thus,
"`The light of the Lord is the breath of man,
and searcheth all the bowels of the belly.`" The heart of man (the unregenerate mind,
the unregenerate spirit) is deceitful above all things, and desperately wicked;
that whereby God searcheth it, is his light, his candle, his own Holy Spirit.

[.numbered]
_Fifthly,_ By the prophets, as Isaiah, Jeremy, Ezekiel, Micah, etc. who said,
"`He hath showed thee, O man, what is good.
And what doth the Lord require of thee, but to do justly, and to love mercy;
and to humble thyself to walk with thy God?`" chap 6:8. How doth God show this to mankind,
but by the inward light of his Spirit?

[.numbered]
_Sixthly,_ By John Baptist, who was the forerunner,
and testified of Christ as of the inward and spiritual baptizer,
who had his fan in his hand.
What is that?
What doth Christ fan with?
What doth he fan, and with what?
The light within is a fan, the Spirit within is a spirit of judgment and burning;
it scatters the darkness; yea, it consumes and burns up the dross and stubble there.

[.numbered]
_Seventhly,_ By Christ himself, who said, "`This is the condemnation,
that light is come into the world, and men loved darkness rather than light,
because their deeds were evil.`" John 3:19. Mark
how Christ preached the light (the seed,
the kingdom, the leaven), and bid men bring their deeds to it,
and blamed them that did not, ver. 20-21. How can there be an inward Jew,
an inward circumcision, without an inward law, inward light, and inward testimony?
And to this inward law and testimony, must the inward Jew daily have recourse,
and bring his deeds thither, to be judged and scanned there.

Again, Christ saith, "`I am the light of the world:
he that followeth me shall not walk in darkness, but shall have the light of life,`" chap.
8:12. How is Christ the light of the world?
Or how was Christ the light of the world?
Was he only so, as he appeared in that body of flesh?
Is he not so in his inward and spiritual appearance?
Is he not the universal light, the Sun of righteousness,
which enlighteneth the whole dark world?
Yet again he saith: "`Yet a little while is the light with you;
walk while ye have the light, lest darkness come upon you;
for he that walketh in darkness, knoweth not whither he goeth.
While ye have the light believe in the light, that ye may be the children of light,`" chap.
12:35-36. This is Christ`'s direction to men how they may become true believers; to wit,
by believing in the light.
The light shines in the darkness ("`ye were darkness`"), and by believing in it,
men become children of it.

[.numbered]
_Eighthly,_ By the apostles and evangelists.
They were sent to turn men from darkness to light, Acts 26:18.
and they testified of the light they were to turn men to;
delivered their message that God was light, and that in him was no darkness at all.
They preached Christ, the light, the life, the way, the truth:
they turned men from Satan`'s spirit, which is darkness, to God`'s Spirit,
which is light.

====

John the evangelist testified of "`the Word which was in the beginning,`" and said,
"`In him was life, and the life was the light of men.
And the light shineth in darkness, and the darkness comprehended it not,`" chap.
1:4-5. And again saith, speaking of him, "`That was the true light,
which lighteth every man that cometh into the world,`" ver. 9.

Paul saith,
"`Whatsoever doth make manifest is light.`" Eph.
5:13. Wherefore "`awake thou that sleepest,
and arise from the dead,`" ver. 14. for God hath sent
forth the light of his Son to rouse thee.
Again, he professedly averreth,
that the Word nigh in the mouth and heart was that Word of faith which he preached. Rom. 10:8.
If so, then that is the Word of faith which is to be believed in,
if men would believe in Christ, and be saved by him.

James speaketh of God as the Father of lights,
from whom every good and perfect gift proceedeth, chap.
1:17. Then surely from him is the grace, and the gift (the free gift) by grace,
which is upon all to justification of life, that receive it,
and follow the teachings of it.

Peter speaks of the more sure word of prophecy, to which men should take heed;
and wait (in taking heed to that) for the dawning of the day,
and the arising of the day-star in the heart. 2 Peter 1:19.
Indeed all men ought to wait for, and give heed to,
the light of God`'s Holy Spirit, and the holy prophecies, warnings,
and directions thereof in their hearts.

And John, at last, as I may say,
in that book of the Revelation (closing up the testimony of that
age and generation) speaks of walking in the light of the Lamb,
chap.
21:23-24. (which every one that comes to witness the true light ought to do,
else there is no true fellowship with God, nor with his sanctified ones,
who are gathered into and walk in the light, even as God is in the light.
1 John 1:7) And the angel that opened the prophecies
and mysteries of that book to John,
said, that "`the testimony of Jesus is the Spirit of prophecy,`" chap.
19:10. So then, he that hath this Spirit of prophecy, he that hath this inward light,
hath the testimony of Jesus; but he that hath it not, hath not the testimony itself,
but only words concerning the testimony.
For this is the distinction between the true believer and the false:
the true believer hath the spirit of prophecy, the witness in himself, 1 John 5:10.
the false believer hath but the outward testimony or relation of things;
but not the inward substance, the covenant and law of life within.

==== Question II

What doth this light do inwardly in the hearts of those that receive it, believe in it,
and give up to it?

==== Answer

It doth all that is requisite to be done,
from the soul`'s coming out of spiritual Egypt into the land of rest;
and all that is needful for its growth and preservation there.

[.numbered-group]
====

[.numbered]
_First,_ It enlighteneth.
It showeth what is evil, and also what is good,
according to the measure and proportion of it,
and according to God`'s causing it to shine in the heart.
It discovers the mystery of darkness, the mystery of ungodliness,
the mystery of iniquity, the mystery of deceit in all its mysterious workings;
for nothing is hid from the light of him with whom we have to do.
And it also discovers the mystery of godliness, the mystery of holiness,
the pure way and commandment of life;
and gives all the believers (the true believers in Christ) this experience,
that "`his commandment is life everlasting.`" There
is nothing the heart needs desire to know of God,
but this makes it manifest in the due season.
It opens the very mystery of the Scriptures,
gives the right understanding and application of the promises,
and fulfils the prophecies thereof in the heart.

[.numbered]
_Secondly,_ It doth not only manifest the good and evil,
but likewise inclines the mind to choose the good, and refuse the evil.
It draws from the evil, and towards the good; yea,
and the soul is made willing in the day of him who is light,
and who appears in the light, and reveals his power there.
There is a way, a high-way, spoken of, Isa. 35:8. called the way of holiness,
which the unclean can neither discern nor pass over to;
but the light of the Lord Jesus Christ,
the measure of grace and truth wherewith he enlightens men,
so manifests and leads into this way, that they that are taught and guided by him,
shall walk therein, and not err.

[.numbered]
_Thirdly,_ It scatters the darkness, breaks the power of the enemy;
it makes one with him who is all power, and giveth to partake thereof;
so that power is given to become sons in the light, to the children of the light;
power given to become kings and priests to God;
power given to reign in the dominion of his life, in the dominion of his truth, over sin,
over death, over deceit; and to offer up the holy, living sacrifices to God.

====

What shall I say?
It is one with Christ, it is of his heavenly Spirit and nature, it makes way for him,
it leads to him, it fills with him,
it brings into unity and fellowship both with the Father and the Son,
where the peace which passeth understanding, and the joy unspeakable and full of glory,
abounds.
This is the gospel message, that God is light;
and they that are gathered into and abide in this light,
they are gathered into and abide in unity and fellowship,
both with the Father and the Son.

David had great sense and great experience of this light of God`'s Holy Spirit,
and of his truth sent forth, manifested, and revealed in his inward parts,
as is signified, Ps. 51:6. and again, in that vehement prayer of his: Ps. 43:3.
"`Oh! send out thy light and thy truth; let them lead me,
let them bring me unto thy holy hill, and to thy tabernacles.
Then will I go unto the altar of God, unto God the gladness of my joy; yea,
upon the harp will I praise thee, O God, my God.`" Indeed when the light shines,
and the truth springs up in the heart, it leads to him that is true,
it leads to the holy hill and mountain of the Lord, and to the inward altar;
which they have no right to, who serve and worship at the outward;
and the harp is known whereon the Most High is praised, even that inward harp,
whereof David`'s outward harp was but the figure.
Therefore they that come to the holy hill of God, to the mountain of the Lord`'s house,
and to that holy building which was reared there,
they invite and encourage others to walk in that light which led them thither,
wherein communion with God, and one with another,
and the blessings of life and peace are enjoyed. Isa. 2:5.

But what should I speak of the sufficiency of the light
and grace of the Spirit of our Lord Jesus Christ,
or of what it is able to do, and of what he is pleased to work by it?
I shall only say this, that as the fulness was enough for Christ,
and to fit him for the work which he had to do;
so the measure of grace and truth which he bestows, is enough for every man.
"`My grace is sufficient for thee,`" said God to Paul, and so it is for every man.
There is no want of sufficiency in the grace of God, in the seed of the kingdom,
in the pearl of price, in the holy leaven, in the heavenly salt;
but the virtue and strength of it is greater than the enemy is able to withstand;
and he that keeps to it, and departs not from it,
shall feel life and power springing up in it, to quicken him,
and carry him through all that God requires of him.
For the water which Christ gives is a well,
springing up (in him to whom it is given) unto life eternal;
and this water is able to wash, able to nourish,
able to fill the soul with living virtue, which waiteth for it and partaketh of it.
And all the nations of them that are saved, are to walk in the light of God`'s Spirit.
To this men are to be turned, unto this they are to be gathered,
into this they are to be translated (even from the kingdom of darkness,
into the Son`'s marvellous light):
and being changed by it (into its nature) become light in the Lord,
and ought to walk in the light, as God is in the light. 1 John 1:7.

==== Question III

How doth the mind come to be enlightened,
and the candle of the Lord come to be set up in the soul?

==== Answer

By God`'s causing it to shine there, and the mind`'s being turned to it,
and given up to be exercised by it, as it pleaseth the Lord to cause it to shine.

The power of the Lord reacheth to the pure principle of life and light in the heart,
in the seasons of his good pleasure.
This being reached to and touched by the Lord, answers his touch, his visit, his call;
and the mind being turned to it, sensible of it,
and willing to let it into its nature and spirit,
and to become one with it (suffering with it, and bearing its cross);
the seed cometh to grow there,
the light which was hid and overwhelmed under the earth (under the earthly wisdom,
the earthly will, the earthly knowledge, the earthly desires, the earthly delights,
etc.) cometh to be lighted up there; yea, the life cometh to be quickened more and more,
and the holy leaven to spread more and more there.
And this sensible plant of God`'s renown being thus entertained,
and being not afterwards grieved, despised, quenched, or hurt, by the giving way to,
and letting in of that which is contrary to it,
it shooteth up into a kingdom of righteousness, into a tree of righteousness,
within the compass whereof, and under the shadow whereof,
the soul sitteth down in peace and rest,
and is defended and nourished with that which is pure and living,
and full of the pure sap and virtue, and so becomes strong in the Lord,
and in the power of his might, against the power and strength of darkness.
Now, this all men may experience (at first in some low measure and degree,
and afterwards more and more) as they come to feel after,
and have a sense of that which is of God, and good in the heart,
and come to join and give up to it.
For then it will be working against, and purging out, that which is of a contrary nature,
and overspreading the heart with its own nature;
insomuch as that which was the least will become the greatest;
and that which was the lowest of all (and indeed trampled
under foot) will rise up into dominion and power over all,
and bring all under.
So that the lofty city, the lofty building of fleshly wisdom,
and of sin and iniquity in the heart, will be laid low,
and the feet of the seed shall tread it down;
even the feet of that which was once poor and needy, until it was anointed,
and its horn exalted by the Lord.

==== Question IV

How is the light or candle of the Lord diminished,
and at length extinguished or put out in some?
Or how cometh that about?

==== Answer

By their neglecting, despising, quenching it;
hearkening and giving way to the contrary spirit in its motions and temptations.
For as the good let in, stops and works out the evil; so the evil let in,
stops and works out the good: so the Philistine nature given way to,
stops the inward well which Jacob had digged and opened.
There is a time when life is a mystery, a fountain sealed;
and there is a time wherein God unseals the fountain, and opens the mystery in the heart.
Oh! then great care is to be had, and the soul is to lie very low in the pure fear,
that it may continue in his goodness, and walk worthy of his love,
that the fountain may be kept open, and the pure springs of the holy land flow,
and not be sealed and shut up again.
For there are some that rebel against the light, and they dwell in a dry land.
There were some that did always resist and vex God`'s Spirit,
and the Lord`'s Spirit ceased striving with them,
and gave them up to a reprobate sense and judgment concerning the things of God.
There are some that do not improve God`'s good talent,
and from them that which was once given is again taken away.
Yea, the candle of the wicked shall one time or other be put out,
and they shall be silent in darkness,
and their mouth stopped from having any thing to say against God,
his truth and people forevermore.
And all men had need to take heed how they be wanton with the grace of God,
or despise the day of their visitation by the holy light of God`'s Spirit;
for if God take away the talent, if God put out the inward candle,
who can light it again?
Oh! how did poor David, the man after God`'s own heart,
suffer by letting the enemy`'s temptations in upon
him! "`Cast me not away from thy presence,`" said he,
"`and take not thy Holy Spirit from me.`" Indeed he did lose his condition at the present,
and he speaks as a man in danger of being quite undone;
though afterwards he came to comfort and assurance that
God would restore to him the joy of his salvation,
and light his candle, and enlighten his darkness again.

But I am not insensible of what doubts and disputes there are in men`'s
minds about this testimony which we give (from certain knowledge and true
experience) concerning the light wherewith God enlighteneth souls.
At first, when the testimony first came forth,
men would not grant such a thing as a light from God in men,
which convinced of and reproved for sin; but now there are many will assent to that,
who yet cannot believe it to be a measure of the
grace and truth which comes by Jesus Christ,
and that in it the sufficiency and power of God is revealed,
against the strength and power of Satan.
But let such seriously consider,

[.numbered-group]
====

[.numbered]
_First,_ Who they are that have testified, and testify of this light.
They are persons who generally have been deeply exercised in religion:
persons who have read the Scriptures very diligently,
with much praying and waiting upon God, for the true, certain,
and clear understanding of them:
persons who (several of them) have had experience
of most (if not all other) separated ways,
but could never meet with the answer of the cry of their souls,
nor with satisfaction to that birth which breathed in them after the Lord night and day.

[.numbered]
_Secondly,_ What their testimony is; which is manifold.
As first, that they were by the Lord (even by his Holy Spirit,
and the shinings and springings of his precious seed in them) turned to this light,
and shown it to be of God.
Secondly, That in turning to it, they still meet with the presence, appearance,
and power of the Lord working in their hearts.
Thirdly, That it did not only discover sin to them, but also powerfully resist it,
fight against it, and bring it under;
which no light and power besides the light and power of God`'s Spirit can do.
Fourthly, That the life of the Son is manifested and revealed in it,
and they come therein truly to see, and taste, and handle the Word of eternal life.
Fifthly, That in this light they come to witness cleansing by the blood of the Lamb,
and the everlasting covenant made with them (even the sure mercies of David),
and the holy, precious promises fulfilled in them,
whereby they are made partakers of the divine nature,
and come to witness an entrance into the holy city,
and drink of the streams of the pure crystal river,
which refresh and make glad the city of our God,
and all the tabernacles wherein he dwells.
Lastly, to mention no more,
The Lord hath shown them how this had been formerly with them,
even in the days of their former profession;
and how God had wrought by this in them in former times, though they then knew it not;
and that all their ability then to understand any thing of God aright,
or to pray unto him, or reap any true benefit from the Scriptures,
was through the stirring of this in them, whereby God even then, in some measure,
enlightened and quickened their minds.
For there being such a principle in man, it works variously,
and many times when he is not aware of it: and he hath benefit thereby,
if he resist it not, but receive its influence and operation,
though he hath not the distinct knowledge and discerning of it.

[.numbered]
_Thirdly,_ Again consider whether the light of Christ`'s Spirit,
or the grace and truth which is come by Jesus Christ,
hath not this property of discovering, convincing, and reproving for sin.
Doubtless the law of the Spirit of life in Christ Jesus,
in the lowest ministration of it, is of that nature,
that it discovereth and fighteth against the law of sin and death, wherever it finds it.
And whether the Comforter, the Holy Spirit of truth,
who leads out of all error and falsehood, and into all truth,
is not as well to be known by this, even by his convincing the world of sin,
and inwardly reproving for sin, as by his comforting of the saints,
in their holy travels out of sin, and battles against sin.

[.numbered]
Consider, _Fourthly,_
whether any thing can convince of sin but the light
of God`'s Holy Spirit shining in the heart?
There may be an outward declaration of sin by the law outward;
but it never reacheth the heart and conscience but by the shining of the light inward.
Nay, it cannot so much as reach to the understanding, but as God opens the heart,
and brings home the conviction by his light and power.
This we have experience of in the Jews;
who though the prophets came with certain evidence and demonstration from God`'s Spirit,
yet they were not convinced thereby, but stood it out against the prophets,
and justified themselves against the voice and Word of the Lord; their eyes being closed,
their ears shut, and hearts hardened against that of God in them,
as may be read in Jeremiah, chap. 2. and divers other places, even to admiration.
And what wickedness is so great which the hardened man will not plead for,
and be defending and justifying himself in!
Yea, if God do open men`'s understandings in some measure,
so that they cannot but confess such and such things to be evil in general (as pride,
covetousness, drunkenness, riotousness, excess in apparel, lying, swearing, etc.),
yet they are not able to see the evil and danger of these things in and to themselves,
but have covers and excuses to hide them,
unless the inward light and Spirit of the Lord search their hearts,
and make them manifest to them.

[.numbered]
_Fifthly,_ Consider the weight and proper tendency of these two scriptures,
and do not form another meaning,
and so put off the drift and intent of God`'s Holy Spirit in them.
The first is that of the apostle. Eph. 5:13-14.
"`But all things that are reproved, are made manifest by the light:
for whatsoever doth make manifest, is light.
Wherefore he saith, Awake, thou that sleepest,`" etc.
Every man is bid to awake,
because every man hath some proportion of that in him which (if hearkened to) will reprove,
rouse up, and awaken him, and lead him from among the dead, to him who gives the light,
and causeth it to shine in him, even in the midst of his darkness and corruption,
that it might awaken him out of it.
The other scripture is that of Gal. 5:17. where the
apostle speaks of the flesh lusting against the Spirit,
and the Spirit against the flesh, and these two are contrary.
Did not God`'s Spirit strive with the old world; not only with the sons of God,
who had corrupted themselves, but with the rest also?
And what is it that hath striven with wicked men since,
and that doth strive with wicked men still?
Is it not the same good Spirit?
What is it also that inwardly resists and lusts against
the will and strivings of God`'s Spirit?
Is it not the flesh?
So here are the two seeds,
the two principles (which are contrary one to the other) near man.
For there is the creature man (which of right is the Lord`'s),
into whom the destroyer hath gained entrance,
and in whom he rules by the law of sin and death.
Now he who made man, seeketh after him, and findeth out his enemy in man,
and giveth forth a law against him inwardly in the heart; which,
so far as any man gives ear to, believes, and receives,
there ariseth presently a fight and striving between
these two contrary principles in him,
so that this man cannot do the things that he would.
Now that which thus strives against sin in any man, and troubles him because of sin,
reproving and condemning him for it,
that is of another nature than the flesh (which harbors sin), and contrary to it.

[.numbered]
_Lastly,_ Consider the great love of God to mankind, and the great care he hath of them.
First, as touching their bodies; how doth he provide for the bodies of all mankind!
He would have none hurt, none destroyed; but feedeth all, nourisheth all,
making plentiful provision, and giving fruitful seasons; causing his sun to shine,
and his rain to descend on all.
Then as to their souls, he knoweth the preciousness thereof,
and what the loss of a soul is; yea, he knoweth how eager the devourer is to destroy,
and setteth himself against him.
He is the Father of spirits, and his Son the Shepherd and Bishop of souls,
whose nature it is to gather and save; and it is said expressly of God,
by the testimony of the Spirit of truth, that he would have all to be saved,
and come to the knowledge of the truth.
And whereas it was said to the Jews, that God was as the potter, and they as the clay,
and he could make them vessels either of honor or dishonor at his pleasure, Jer. 18:6.
yet it was to this end,
even to invite and encourage them to be subject to him,
that they might be made vessels of honor by him, as appears ver. 11.

====

Now consider, if God be as tender of souls as of the bodies of men,
doth he not make provision for the soul as well as for the body?
Would he not have the soul live, and would he not have the soul fed as well as the body?
If so,
then needs must the light of his Holy Spirit shine inwardly throughout all nations,
and the saving grace and power be manifest everywhere, even in every heart,
in some measure,
and the flesh and blood of the Son of God (which
is the soul`'s food) be distributed to all.
And truly, the Lord is not a hard master to any, as the unprofitable servant,
in every dispensation, is ready to account of him;
for the times of ignorance and darkness God winketh at, or passeth over,
being very tender towards men in that estate; yea,
a little that is of him turned to and heeded,
according to the measure of understanding that God gives, will be owned and accepted,
even in the midst of a great deal of darkness and evil working against it.

There was a time before the law (for the law was given by Moses): what saved then?
Was it any thing but the saving grace, the saving light, the saving Spirit,
the holy anointing, could any be saved but thereby?

What saved under the law?
Did the shadows then save, or the substance of life veiled under them?
Did not the Spirit then work inwardly, redeem inwardly, save inwardly?
Did not the word of commandment nigh in the mouth and heart (to which Moses,
by God`'s direction, had turned their minds) enlighten and save inwardly?

And any of the Gentiles, as the Word or Spirit of life did work in them,
did it not circumcise inwardly, and save them also?
So that though they had not the law or ministration of Moses outward,
yet they had the inward writing from God on their hearts,
and showed the work and efficacy of it there, and shall at last be justified by,
and according to, the everlasting gospel, which justifieth all whatsoever,
so far as in any measure they receive and are subject
to the light and law of God`'s pure Spirit,
which the carnal mind cannot receive, nor be subject to.

Oh that men could die to themselves, even to their own wisdom and prudence,
and not lean to their own understandings,
nor idolize their own apprehensions and conceivings,
but wait to receive understanding from God,
who giveth liberally of the true wisdom to those that ask and wait aright!
And how doth God give true wisdom and understanding?
Is it not by the shining of his light in the heart?
Oh that men were turned inwardly thither,
and inwardly dead to that wisdom and prudence from which God ever hid things,
and ever will!
He that will be truly wise, must first become a fool, that he may be wise; that is,
he must not strive to learn in the comprehensive way of
man`'s wisdom and prudence the things of God`'s kingdom;
but feel the begettings of life in his heart,
and in that receive somewhat of the new and heavenly understanding,
and so die to the other, and know no more the things of God after the flesh; that is,
as a wise man, as a learned scribe, as a great disputant (for where is the wise?
Where is the scribe?
Where is the disputer of this world?
Can they find out the mystery of life, the mystery of God`'s kingdom in this age,
any more than they could in former ages?), but become a babe, a fool,
and so receive and bow to that which his own wisdom will call foolishness,
and account weakness; but the other birth, which is begotten and born of God, will know,
and daily experience, to be the wisdom and power of God unto salvation.

[.centered]
=== An Appeal

[.heading-continuation-blurb]
To the Witness of God in all Consciences, which is the more sure Word of Prophecy,
the testimony of the Scriptures without,
or the voice and testimony of the Light and Spirit of God within, in the Heart?

The apostle Peter speaks of a more sure word of prophecy
(or a more sure prophetical word,
as the Greek hath it) than that voice which came from heaven,
which they heard when they were with Christ in the holy mount. 2 Pet. 1:18-19.
Now, what this more sure word is,
which ought to be given heed to in the most especial manner,
more than to such an eminent voice and testimony from heaven,
even from the excellent glory, is a very great and weighty question.
Now, some affirm, that it is the word and testimony of the Scriptures without;
others affirm, that it is the voice, sound, and testimony of the Word of Life within.

I do not know a scripture that my heart hath been more tenderly solicitous about,
desiring to give due honor both to the Spirit of God, and to the holy Scriptures,
and also to understand what the Lord would have me
in the most especial manner give heed to,
until the season came from him in which he should cause the day to dawn,
and the day-star to arise in my heart.
And now, that others might come to the same understanding and satisfaction also,
are these following considerations proposed in the weight of my spirit to them.

[.numbered-group]
====

[.numbered]
_First,_ Consider how sure the word of prophecy was,
how sure the voice and testimony from heaven was;
than which the apostle directs them to somewhat as more sure.
This I may clearly say of it, it was undoubtedly from God,
and that in a very extraordinary manner, even in Christ`'s presence,
when Moses and Elias were with him, and God bestowing upon him honor and glory,
transfiguring him before his disciples, causing his face to shine as the sun,
and making his raiment white as the light. Matt. 17:2.
And the intent of it was to give the disciples
full evidence and satisfaction (for the voice was not for his sake,
but for theirs), or rather that they might have a full ground,
after his death and resurrection,
to testify for the satisfaction and confirmation of others;
for till then they were to keep it secret,
ver. 9. Now that which was provided for this end, doubtless was very sure,
and testified by them who were chosen to be faithful witnesses in this respect.

[.numbered]
_Secondly,_
Consider whether the testimony of the prophets concerning
Christ was surer than the immediate voice from God himself?
Were they surer to those that lived in those days, or to those that should come after,
than this testimony was to the apostles,
and to those that did communicate it in the will and counsel of the Lord?
The prophets did testify from God`'s holy, unerring Spirit;
but they that lived in those days did not always believe and receive their prophecies,
but sometimes doubted of them and questioned them; yea,
their prophecies were not always evident,
and clearly understood by those who desired to understand;
but their visions were many times a book sealed, both to the learned and unlearned.
But this testimony, this word of prophecy,
this voice from the excellent glory ("`This is my beloved Son, hear him`"),
is a very plain, evident, full testimony, easy to be understood by any in that present,
or in after ages.
And I must confess, as to myself,
the reading of it did always deeply affect and satisfy my heart.

[.numbered]
_Thirdly,_ Consider the manner of God`'s appearing to the prophets,
and compare it with the manner of this appearance.
God appeared to them sometimes in visions, sometimes in dreams.
Moses saw a bush burning, and heard a voice.
"`The vision of Isaiah the son of Amos.`" Isa. 1:1. And Ezekiel saw visions, chap.
1:1. And Daniel had a dream and visions on his bed. Dan. 7:1.
And Jeremiah had that sweet prophecy (of God`'s satiating the weary soul,
and replenishing every sorrowful soul) in his sleep. Jer. 31:26.
Now here to these blessed apostles
was a vision given of the glory of Christ,
and of Moses and Elias with him; not in the mind or head, as Daniel`'s visions were, Dan. 7:1.
but the excellent glory did appear, and Christ, Moses,
and Elias were really there together on the mount
(which is more than a prophetic vision of a thing),
and Christ was clothed with and swallowed up in the glory.
For God, the Father, did set himself to honor and glorify him,
so as never man was glorified before; and the voice came (the certain voice;
what voice could be more certain?) from the excellent glory, "`This is my beloved Son,
in whom I am well pleased.`" 2 Pet. 1:17. And
this pure vision of glory (even of God`'s thus appearing,
and Christ`'s thus transfiguring) they saw, and heard the voice which came from heaven,
when they were with him in the holy mount.
Now were the prophecies of the prophets that Christ should be born in Bethlehem,
and that he should be thus and thus, etc., equal to this in evidence and demonstration?
Why was John greater than the rest of the prophets?
Was it not in that he was chosen to be the immediate forerunner and preparer of the way,
and could point with his finger to the Messiah?
And yet,
is not this immediate testimony from the excellent
glory greater than the testimony of John?

[.numbered]
_Fourth,_
Consider whether Christ`'s own words in the flesh to his
disciples were surer than the voice from the excellent glory.
If I should extol the words of Christ in the flesh above
the words of the prophets which testified of him,
should I therein do the words and testimonies of the prophets any wrong?
He was the Son; he had the fulness of life, the fulness of the Spirit,
the great authority and virtue of God, his Father.
"`God`" saith the apostle, "`who at sundry times, and in divers manners,
spoke in time past unto the fathers by the prophets,
hath in these last days spoken unto us by his Son,`" Heb. 1:1-2.
seeming to exalt and magnify God`'s speaking by his Son,
and the way of this ministration above the ministration of the
prophets (which ministration was first by him in the flesh,
afterwards in Spirit, which is properly called the ministration of the Spirit.
2 Cor. 3:8). Now consider whether this sure word
of prophecy from the excellent glory,
so immediately from the majesty on high,
was not intended by him as a seal to the faith of the disciples,
as a seal to Christ`'s appearance in the flesh,
and to what he had taught them (which was sometimes in parables,
and not so fully understood by them); and whether this was not more bright,
more ravishing, more certain, more establishing,
than his common presence and appearance among them,
and than the words which he from the Father, not the Father so immediately himself,
spake to them?
For that which is given to confirm a thing, is (in order of nature,
and for evidence`' sake) more certain and clear than that which it is given to confirm.

[.numbered]
_Fifthly,_
Consider whether the voice of God`'s Spirit and light within the
heart be not more clear and certain to him that hears it,
than any word or testimony from without?
Is it not a surer word of prophecy than this relation or testimony of the apostles,
of what they heard from the excellent glory?
Yea, is it not surer than any testimony of the Scriptures,
or than all outward testimonies put together?

Sixthly, Consider whether they who are turned from darkness to the light,
even to the inward manifestation of God`'s Holy Spirit,
ought not to give diligent heed unto it, until the day dawn,
and the day-star arise in their hearts?

[.numbered]
_Lastly,_ Consider,
what is the difference between this light shining
(as a word of prophecy) in the dark place,
and the day dawning, and the day-star arising in the heart?
Is it not the same light, only further revealed and shining in its glory,
in the holy and pure place?

====

The apostle Paul excellently openeth the thing. Col. 1:25-27.
First, he speaketh of the Word in general, which he was to fulfill,
or fully to preach.
Then he showeth how this Word is a mystery, hid in the Gentiles (for so the Greek,
ver. 27. is) even in them that believe not; the Word is nigh there,
the instruction and commandment of life nigh there.
But in those that receive the grace, and believe in the light,
and so become children of the light, and walk in the light, as God is in the light:
in them Christ is risen, and they are risen together with him,
and he is in them the hope of glory.
So that the day hath dawned there; the day-star hath risen,
and they know not only a measure of Grace from Christ, but Christ himself arisen,
dwelling, living, acting, walking in them, and they in him.

Let these things be duly considered of, and equally weighed in the holy balance,
and then I dare appeal to every serious and sober heart and mind,
whether the inward light, the inward Word, the Word nigh in the mouth and heart,
and the holy, living testimony thereof, the voice of the witness within,
of the prophecy within, be not surer to that man that hath it,
and hears and knows the voice of it, than any outward voice or testimony whatsoever?

[.discourse-part]
Objection.
But some may object thus, or after this manner:
I am satisfied that there is a Word nigh in the mouth
and heart (to which Moses did direct the Jews,
and the apostles the Christians), and that this Word doth enlighten the mind,
and doth separate in the mouth between words and words,
and is a swift witness against the bad words, and a justifier of the good words,
which come from the truth and uprightness of the heart, and are seasoned with grace.
I also believe that this Word is quick and powerful in the heart,
separating and dividing between the thoughts and intents there;
and that the testimony thereof is surer and clearer (as to the hearts in which it shines,
and to them whose spiritual ears are opened to hear its
voice) than any words and testimonies from without.
And I am satisfied also, that they who are the sheep of Christ,
do thus hear the Shepherd`'s voice, and do know both the voice behind them,
when it comes after them to reprove their wanderings,
and direct their minds into the true way; and also the voice before them,
when the Shepherd (who is the leader) putteth forth his sheep, and goeth before them,
and they follow him; for they know his voice. John 10:4.
Yea, I have had the experience hereof in my own heart;
for I have felt that work within, and that living,
sweet testimony of God`'s Spirit in my own heart,
which hath been more to me than all that ever I heard or read from without;
so that I can truly say (with the Samaritans, John 4:42) Now I believe,
not because of the testimonies or words I have heard from without,
but from the evidence and demonstration of life,
and of God`'s Holy Spirit in my own heart.
Nor can I see how the apostle Peter, in this place,
can prefer the testimonies of the prophets (for that which is called the New
Testament was not yet written and added to the old) before this glorious,
immediate testimony from God Almighty, which Christ was honored with,
and they were greatly honored in being admitted to be beholders and witnesses of.
Yet somewhat sticks with me; namely, those words of the apostle,
ver. 20-21. wherein he plainly seems to me to speak
of the scriptures or writings of the prophets,
as if they had been the more sure word of prophecy,
which in this place he had directed to.
For why should he say thus, "`Knowing this first,`" etc.,
unless he had intended the same Word of prophecy which he had been speaking of before,
and directing their minds how they might make use of that Word of prophecy?

[.discourse-part]
Answer.
Peter was the minister of the circumcision,
and he was to deal with people who were great admirers and studiers of the letter;
therefore, though he as well as Paul and John, and the other apostles
(Rom. 10. and Acts 26:18. and 1 John 1),
was to direct men to the Word within, and light within,
yet he knew it was of great concernment to them rightly
to read and be able to understand the letter without.
Therefore, having first directed them to the Word of prophecy, to the path of the just,
which is the inward, shining light,
to the light which shines more and more in the dark place to them that give heed to it;
in the next place it was very proper, useful,
and necessary to direct them how to read the Scriptures aright.
For indeed the oracles of God were given to them, Rom. 3:2.
and they ought to be diligent in the reading of them,
that they might understand the holy prophecies, and precious promises, etc.,
and reap the hope and comfort of them, and be made partakers of the divine nature,
which is the thing promised.
And not only to the Jews,
but to the Christians gathered from among the Gentiles in that age,
were the Scriptures greatly useful:
and so they are also to such as are gathered by the
Holy Spirit and power of God in this age.

The prophecies, the judgments, the promises, the mercies, the experience,
etc. are all useful,
and profitable to those that read and understand them in the light of God`'s Holy Spirit.
But the first thing needful is, to turn a man`'s mind to the light,
that he may have somewhat to guide him,
somewhat to stay his mind upon in reading the Scriptures,
somewhat to open and unseal the holy and divine words and mysteries to him.
For no man can truly and rightly understand the Scriptures,
but as his mind is opened by the Lord,
and the understanding of the words and things given him.
So that this is exceeding necessary to be known (after a
man is turned to the light and Word of prophecy within,
and comes to read the outward oracles and testimonies of the Holy
Spirit) that all the holy men spake not in their own wills,
nor in the will of the flesh, nor in the will of man,
but as the Spirit of God gave them words, and moved them to speak.
And those words spoken by God`'s Spirit knoweth none, but that Spirit which spake them.
So that no man ought to venture by his private spirit
to undertake to open and interpret those words;
but he must first receive the same Word of life, the same Spirit of prophecy within,
and wait upon him, and learn to know his voice,
who openeth what and when he pleaseth to the sons of men.
And so when the same Word of life speaks in a man`'s heart now, showing things to come,
either concerning a man`'s self or others, that man must be careful to retire,
and lie very low before the Lord,
waiting upon him for the true understanding and right interpreting of his own words,
else a man may easily misunderstand and misapply what was truly and rightly spoken.
So that this is the right way of understanding the words
of prophecy from the holy men of God in former ages,
and the instructions of the Word of life in the heart.
"`The secrets of the Lord are with them that fear him.`" In the true fear the ear is opened,
and the right understanding given; but in the wisdom of the flesh,
and in the confidence thereof,
it is easy erring at any time from the true sense and right
use of that which was opened and given by God,
either for the soul`'s own good, or for the good of others.

To conclude this appeal:
there is one consideration on my heart to propose to the serious and sober-minded;
and oh that they might rightly consider and understand it!
David was a man after God`'s own heart, a wise man, an inwardly-exercised man,
an experienced man, a holy, spiritual, heavenly man; a man who knew the inward,
everlasting kingdom, and had the Spirit of God,
and witnessed his truth in the inward parts:
can ye think that David did not know the Word and commandment of life within?
Did not God write his law in his heart?
How else could he become a man after God`'s own heart?
Did not he witness the everlasting covenant, and the law thereof, the new law,
the living law, even the law of the Spirit of life in Christ Jesus?
Now when David said, "`the law of the Lord is perfect,
converting the soul,`" what law did he mean?
What is the law which converts the soul to God?
Can any thing less than an inward power, an inward light, an inward law, an inward life,
than the inward drawings and teachings of God`'s Spirit, convert the soul to God?
And what testimony is that which makes wise the simple?
Is it not the inward testimony?
What made him wiser than the ancients, and his teachers,
who knew and could teach the law outward?
Were they not the inward teachings and inward precepts
of God`'s Holy Spirit from the Word of life within,
which doubtless was very nigh him, he being a man so exercised by God`'s Spirit,
and so formed after his heart?
And what are those right statutes which rejoice the heart,
and the pure commandment which enlightens the eyes,
and the clean fear and righteous judgments?
Are not all these things known within, and received within?
Doth not God put his fear within, in the heart?
Doth not God reveal his righteous judgments within against sin and iniquity?
Oh, how did David cry out because of God`'s dreadful judgments upon him for sin,
and said his sore ran in the night, and he watered his couch with his tears!
And in another place, "`My flesh trembleth for fear of thee,
and I am afraid of thy judgments.`"

And when he speaketh so much (as in Psal.
119) of God`'s word, God`'s law, his testimonies, precepts, statutes, judgments, etc.,
what doth he speak of?
Doth he speak of the outward or inward ministration of the Word in the heart?
Doth he not speak of the inward writing, of the law in the heart,
of the commandment in the heart, of the testimony of life there?
For he had the testimony within, the Spirit within, the law within, the light within,
the inward and spiritual kingdom (wherein the holy
dominion of God is revealed) he knew within;
and so believing, could speak of the power and glory thereof,
and of God`'s wondrous works.
Psal.
115.

And when he said, "`Thy Word is a lamp unto my feet,
and a light unto my path,`" what Word did he mean?
Did he mean the letter or law outward, or the Word nigh in the mouth and heart,
which Moses had testified of, and directed the Jews to,
and he himself had been very well acquainted with?
When again he saith,
"`Wherewithal shall a young man cleanse his way?`" And immediately giveth the answer,
"`By taking heed according to thy Word.`" Doth he mean the letter without,
or the Word within?
What is it that cleanseth the heart, that cleanseth the way?
Is it any thing less than the water of life, than the blood of the everlasting covenant,
than the Word and life of truth within?
"`Sanctify them by thy truth; thy Word is truth.`" In the sense of that inwardly,
and obedience to it, is the renewing and sanctification felt.
And so this brings to be undefiled in the way, and to keep the testimonies of life,
and preserves from doing iniquity.
"`Blessed are the undefiled in the way,`" saith he, "`who walk in the law of the Lord.
Blessed are they that keep his testimonies, that seek him with the whole heart.
They also do no iniquity,`" etc.
Had he no experience of these things himself?
Yea, surely.
He knew the holy heart, the pure heart, the new and heavenly image,
the heart after God`'s own heart; and he knew what it was to walk in innocency,
and to be kept out of sin.
Hear what he himself saith.
Ps. 18:21, etc.
"`For I have kept the ways of the Lord, and have not wickedly departed from my God.
For all his judgments were before me, and I did not put away his statutes from me.
I was also upright before him, and I kept myself from mine iniquity.`" What was that?
Was not that it which had most power over him,
and was most apt to entangle and ensnare him?
Now he that arrives here, he that doth this, that keeps himself from his iniquity,
doubtless witnesseth great power and victory over lesser and +++[+++greater]
sins.
Was not David strong in the Lord, and in the power of his might?
Did not the Word of God abide in him?
Did not he overcome the wicked one by the power thereof?
How else could he walk thus in the ways of the Lord, as he expresseth,
and keep himself from his iniquity.

Now this Word of life, these living testimonies and precepts, yea,
the everlasting ordinances and statutes of the new covenant,
with the sure mercies of David, which Word Moses had testified of, and directed to,
and David had experienced (it being the pearl he had treasured up and hid in his heart),
and which was the Word of faith which Paul and the
other apostles preached and testified of,
turning men from darkness to this inward light,--I say, this Word,
this living Word (and the inward ministration thereof)
God hath revealed and made manifest in this our day,
and hath turned the minds of many to it, and is daily inviting men to Shiloh`'s streams,
to the living waters, to the light and habitation of the living.
Blessed are they that hear the joyful sound,
and come to the holy mount and city of our God, where life lives and reigns,
and is fed on by all the living; who are God`'s elect, God`'s heritage,
God`'s vineyard of red wine, God`'s enclosed garden, whom he watcheth over night and day,
and watereth every moment; and in whom he dwelleth and walketh,
and is to them a God and Father,
and maketh them daily sensible that they are his servants, children, and spouse,
in whom is his great delight,
and on whose hearts and foreheads is written "`Holiness to the Lord.`" Yea,
and the Lord will bless thee forever, "`O habitation of justice,
and mountain of holiness!`" And every tongue that riseth up in judgment
against thee will the Lord God condemn forevermore.
This is the heritage of the servants of the Lord,
whom the Lord hath gathered by the arm of his mighty
power (inwardly revealed and stretched forth in them,
and for them), "`and their righteousness is of me, saith the Lord.`"

=== Postscript

There is a Scripture now openeth in me, as it hath often done,
and it hath been very sweet to my taste;
but I have not had freedom to give it forth to others,
as at this time it is with me to do: it is that scripture Rom. 9:18.
"`Therefore hath he mercy on whom he will have mercy, and whom he will he hardeneth.`"

Now many apprehend from this scripture, as I also formerly did,
that God hath chosen out a certain number of persons on whom he will have mercy,
and save by Jesus Christ the Lord; and that he hath passed over the rest,
so that they were never intended to have any benefit
by Christ`'s death as to their eternal salvation.
This the wisdom of man, from the letter of the scripture and many other places,
may easily apprehend and strongly reason for.
But as the Lord openeth the mind, and men come to a sense of his nature and Spirit,
and his intent in sending his Son,
and receive the key which openeth the truth as it is in Jesus,
they will easily see that this is contrary to God`'s nature,
and his intent in sending his Son, and the universal covenant of light and life,
and the manifest testimony of the Scriptures.

[.numbered-group]
====

[.numbered]
_First,_ As touching the nature of God.
His nature is _love;_ love to all his creatures.
He would not have it go ill with any of them.
He needeth not their misery to make himself happy.
His nature is to love, to bless, to save; not to destroy or cut off,
nor to afflict or grieve the children of men; not to hurt either the body or soul of any:
he preserveth man and beast. Ps. 36:6.

[.numbered]
_Secondly,_ As touching his sending his Son.
He sent him in his love to mankind, to save mankind.
His love was not to a few only; but he loved all his creatures, he loved all lost souls,
and he sent his Son to save them all.
He gave him light to enlighten them all, and he gave him life to quicken them all;
only he dispenseth this in different ways,
according to the infinite wisdom and good pleasure of his Father.

[.numbered]
So that, _Thirdly,_ The covenant of light and life as universal, and nigh all mankind,
by which the darkest parts and corners of the earth are at some times enlightened,
and feel somewhat of the quickening life.
For the life is the light of men, and the light comes from the life, and is a quick,
piercing, quickening light, conveying warmth and life, yea,
living virtue into the darkest hearts, as it moves and finds entertainment in them.

[.numbered]
_Lastly,_ As for the testimony of the Scriptures,
it is very clear that God would have none to perish.
"`All souls are mine,`" saith the Lord. Ezek. 18:4.
"`I have no pleasure in the death of him that dieth,`" ver. 32. And again,
"`As I live, saith the Lord God, I have no pleasure in the death of the wicked,`" chap.
33:11. I have sent my light to enlighten all men, and turn all men,
and I would have all men receive it, and be turned by it.
I have showed every man what is good, and what I the Lord require of him;
and I would have every man answer the manifestation of my light and Spirit in him.
Do ye not read God`'s charge against the whole earth, Isa. 24:5.
that they had transgressed the law, changed the ordinance,
broken the everlasting covenant?
Why, then they all had the law, had the ordinance, had the everlasting covenant;
and for this cause it is that the curse and judgment comes upon them,
ver. 6. So that this was the condemnation from the beginning,
and this is the condemnation still, "`that light is come into the world,
and men love darkness rather than light,
because their deeds are evil.`" Men are not condemned for want of light from Christ Jesus;
but because they do not believe in and obey that light which they have from him;
because they believe in the darkness, believe in the dark spirit,
believe in the dark power,
which riseth up against the ministration of light in the heart,
and do not believe in that which is given of God to discover and work it out.
What should I multiply scriptures for?
That common scripture is absolutely undeniable (as
the Lord opens the heart unto the simplicity of truth,
and keeps it out of the subtle, enchanting wisdom), John 3:16-17.
"`For God so loved the world, that he gave his only begotten Son,
that whosoever believeth in him should not perish, but have everlasting life.
For God sent not his Son into the world, to condemn the world; but that the world,
through him,
might be saved.`" What can be more naked and plain than these words of Christ,
who knew the very heart of God in this particular, and plainly declares what it is,
even not to condemn, not to destroy, but to save men from condemnation and destruction?
And would Christ have so affectionately wept over Jerusalem,
had he known it to be his Father`'s will and determinate
counsel that they should have perished,
and not have been gathered and saved by him?
I shall add but one place more, where the apostle (who knew God`'s counsel,
and understood the mystery of election and reprobation,
and had the mind of Christ) saith expressly, that "`God will have all men to be saved,
and to come unto the knowledge of the truth.`" 1 Tim.
2:4. What words can be spoken more plain and full?
And let people mind that these words are far plainer and easier to be
understood than those scriptures which treat of election and reprobation;
which is a deep mystery; and men must come to a growth in the truth,
before they can receive that capacity which is necessary
towards the understanding of them.
But to open the thing a little, as it is now in my heart.

====

There hath been a three-fold dispensation of God to mankind.
A dispensation of the law to the Jews; a dispensation of the gospel (or promise,
which was as well before the law as after it) to the called Jews and Gentiles;
and a secret, hidden dispensation of the mystery of grace,
of the mystery of life and salvation,
which the apostle calls the mystery hid in the Gentiles.
Col. 1:27. For somewhat of God, somewhat of the nature and Spirit of Christ,
the souls of all mankind have had near them, to enlighten them,
and to turn them from Satan`'s power to God;
though it hath not been a thing known to them, but a mystery hid in them.

Now that God did cast off any Jew under the law,
or any whom he visits with the grace and power of the gospel,
from a mere absolute will in himself, because he would destroy them and have them perish,
to show forth the praise of his justice, and his absolute sovereignty,
this the true sense of life in me denies;
but all have a visit of that which saves heartily and in true good-will from God;
and he that is turned to that which God hath sent to turn him,
shall be owned and saved thereby.
He that believeth in the truth, in the light, in the Word nigh,
even in the very lowest appearance of it (for the lowest
appearance is the same thing in nature with the highest,
and the grace is saving in its very lowest appearance, as well as in its highest),
shall be saved thereby.

Now mark: God`'s grace, God`'s mercy, God`'s love, God`'s light, God`'s Spirit,
God`'s power, etc. is his own, and he may do with his own what he pleaseth.
Now it being by this that he strives, converts, and saves;
and it being in his own will and good pleasure how
long he will strive and contend to save;
it lieth therefore absolutely in him, even in his own will, what he will do in this kind.
He may take advantage against rebellious man, and cut him off when he will; and again,
he may strive and raise true sense in a man`'s heart, and give repentance,
and pardon his transgressions, as long as he pleaseth; yea,
he may so change a man`'s heart, and so create him anew in Christ Jesus,
and so bring him into unity with the pure seed, and to that estate in the seed,
as that he may have assurance he shall never be utterly cast off;
but that though he should sin, and transgress the holy law of God`'s Spirit,
his iniquity shall be chastised with stripes,
and his soul recovered and brought back thereby, but not utterly rejected by the Lord.
Now it being thus, hath not God mercy on whom he will?
And doth not he harden as he pleaseth?
Did not God give up the Jews to hardness, after much striving with them?
Did not God give up the Gentiles to hardness,
and to vain imaginations concerning the true God,
after they had rejected a measure of the true knowledge? Rom. 1:21.
Have not the vessels of wrath, who are fitted to destruction,
a day of much longsuffering first? Rom. 9:22.
Had not the old world, who were fitted for that destruction of the flood,
a long day of patience and forbearance from God, his Spirit reproving of them,
and striving with them?
To what end did God forbear them, and cause his spirit to strive with them?
Was it not to lead them to repentance,
that thereby they might have avoided that destruction, which,
by their rebellion and stiffness of spirit against God`'s good and tender Spirit,
they were fitted for, and exposed to?
See Rom. 2:4. So for Cain,
how tenderly did God deal with him! how uprightly did God seek his good!
Would not God have had him come to a true sense and repentance?
Would not God have had him believed and offered in the faith,
and been accepted as his brother was?
And for Pharaoh,
God indeed was against that nature and spirit in him which oppressed Israel;
but would not the Lord have had him denied and turned from that nature and spirit,
and let Israel go?
God would have no man do evil, and bring upon himself destruction;
though in his just judgment he is many times provoked to give men
up to that which leadeth into and hardeneth in evil.
So not only Pharaoh, but Israel also, was given up to their own hearts`' lusts,
when they would none of the Lord, nor hearken to his counsel. Ps. 81:12.
But saith the Lord,
oh that it had been otherwise! "`Oh! that my people had hearkened
unto me!`" etc. it should then have been otherwise with them,
ver. 13. etc.

So that God of himself doth not desire the destruction of his creature;
nor doth he desire to harden them, or to give them up to a deluding spirit,
that they might be damned; but men first refuse the truth, and turn from it,
or let it go; not receiving it in the love of it,
or not liking to retain the knowledge of it (which is death to the man`'s corrupt nature,
spirit, will, and wisdom, and such a cross and yoke as he is in no wise willing to bear);
and then the Lord, in his just judgment, gives them up to the deceitfulness of sin,
to be hardened by it.
Now this liveth in God`'s own breast when and to whom to do it,
according to his own will, and according to his own wisdom and counsel;
so that it may be truly and properly said, "`he hath mercy and compassion on whom he will,
and whom he will he hardeneth.`" But that God hath determined to harden any,
without giving them a day of mercy;
or that it is God`'s will and determinate counsel that men
should reject the day of his mercy and precious invitation,
that they might be hardened by him and perish; this is not God`'s truth,
but men`'s misapprehensions upon true words,
gathering meanings therefrom in their own wisdom,
and not waiting upon God till he cause the true light to shine in them,
and thereby give them the true knowledge and understanding.

Therefore, since there is such mercy in God towards all,
and he hath given all men a day of visitation, greater or lesser; yea,
since of late he hath caused his light to shine forth,
and given this age such a visitation as many ages have not had,
oh! let men take heed how they close their eyes, stop their ears,
and harden their hearts against it,
lest they provoke God to give them up to their own imaginary, conceited,
fleshly comprehensive knowledge of the letter,
and so seal them up in that hardness of heart and deadness
of spirit which they first gave themselves up to.
For the letter, without the Spirit, killeth; and so doth all literal knowledge:
and there needs no greater curse from God (it will
sufficiently avenge the cause of his reproached light,
and holy covenant of life in Christ Jesus,
now abundantly revealed and made manifest) than to close men`'s eyes,
and stop their ears,
and harden their hearts (in their literal knowledge and practices)
from beholding and partaking of the precious life and virtue of
the holy and living ministration in Christ Jesus the Lord,
wherewith God visiteth and redeemeth his people.

Indeed the physician is come inwardly and spiritually,
and he inwardly heals and restoreth his people, faithfully seeking after the sick,
the distressed, the broken, the wounded; pouring oil into their wounds, and healing them.
But there are some who are so sound and whole in their notional apprehensions and practices,
that they have no need of the physician, and them the physician passeth by,
as unworthy of him, and whom he intendeth shall have no share with him.
"`Ephraim is joined to idols`" (he is well, he hath enough,
he hath no need of me) "`let him alone,`" saith the Lord.
I will pour out the choice virtue of my spiritual life and
redeeming power among my gathered sheep and lambs,
who have need thereof, and will rejoice therein.
These will know my voice; these will justify the appearance of my Spirit and power;
these love the savor of my anointing and precious ointment,
which runs down from the head upon all the living body, and these shall have it.
These understand how I have mercy on whom I will, and whom I will I harden;
and it is my will to have mercy on these my once greatly distressed ones,
and to destroy (inwardly to destroy, oh,
who knows what that means!) the fat and the strong, and to feed them with judgment.
Oh that men did know to whom the mercy and to whom the judgment belongs!
To the wisdom of the flesh,
to the wise comprehenders of the things of God after the flesh, is the judgment:
to the poor, to the distressed,
to the broken in spirit (not to them that are at ease in the literal knowledge,
but to the mourners in Zion after the holy God, and his living power and righteousness),
is the everlasting gospel, the mercy, the love, the peace, the binding up,
the redemption which is by Christ Jesus,
the living Minister in the holy sanctuary of our God.
