== NAKED TRUTH

OR

TRUTH NAKEDLY MANIFESTING ITSELF IN SEVERAL PARTICULARS

FOR THE REMOVING OF HINDRANCES OUT OF THE WAY OF THE SIMPLE-HEARTED

THAT THEY MAY COME TO TRUE KNOWLEDGE, LIFE, LIBERTY, PEACE, AND JOY IN THE LORD, THROUGH THE VIRTUE AND POWER OF HIS PRECIOUS TRUTH REVEALED AND WORKING IN THEM

GIVEN FORTH

BY WAY OF QUESTION AND ANSWER

Whereunto are added, Some Experiences, with some Scriptures, very sweet, and necessary to be experienced in the gospel-state

As also, A few words concerning the true Christ;

And a few words in the Bowels of tender Love and Good-will to my Native Country

By a long Mourner and Traveller after, but at length a happy Experiencer of, the Truth, as it is in Jesus,

ISAAC PENINGTON

"`Blessed are the eyes which see the things that ye see.`" Luke 10:23

+++[+++1674]

=== PREFACE

TRUE knowledge and true experience, especially concerning things of necessity,
and great concern to the soul, is very precious.
As; to know the true foundation, the cornerstone, which God lays in his spiritual Zion;
and the heavenly Jerusalem, which is the mother of all that are born of God;
and the gathering out of the spirit of this world (with
the vanity and falsehood thereof) into God`'s Spirit,
which is truth and no lie; and the building up of the holy temple, in which God appears,
and is worshipped; and the heavenly communion with the Father and Son,
in the one pure light which shines from them into the heart; and the one faith,
the one circumcision, the one baptism, the one holy mountain,
the one feast of fat things made thereon; the one water of life, the one bread,
the one cup of salvation, etc.

Now the things of the kingdom are all at the disposal of the king thereof.
To him all power is given, in him are hid all the treasures of wisdom and knowledge;
he hath life in himself, and he hath life to dispose of, and dispense to his.
He gives the true knowledge, which is life eternal; he gives repentance,
and remission of sins.
He teacheth to believe in the Father, and he giveth faith also.
He is the Shepherd of the sheep,
who by his voice quickeneth and maketh alive and leadeth
and preserveth and nourisheth up to life eternal.
Therefore, whoever will understand aright, must receive understanding from him;
and whoever will repent aright, must receive repentance from him;
and whoever will believe aright, must receive faith from him;
and whoever will hear and see aright, must receive an ear and eye from him;
and whoever will come unto him, and receive him,
must witness that new heart forming or formed in him,
wherewith and whereby he is received.
Men greatly mistake and err about the gospel knowledge and religion,
by beginning therein without the gospel spirit and power.

Therefore that man that would not be deceived, and lose his soul forever,
let him take heed how he begins, how he stands, and how he proceeds in his religion.
The Jews stood in the revelation of God`'s Spirit and power outwardly;
and the state of the Christians, the new covenant state,
stands in the revelation of God`'s Spirit and power inwardly;
for none can beget a new birth to God inwardly,
but his own Spirit and power working inwardly in the heart.

Therefore, thou that wouldst live with God forever,
and not perish from the presence and glory of his power, mind these three things:

First, God`'s inward visiting thee, and making a real change in thee.
I do not mean a change in thy mind from one notion to another;
but a change in thy heart from one nature and spirit to another.
This is the great work, which nothing but the mighty power of God,
which raised Jesus from the dead, can effect in the hearts of the children of men.
Now, that this may be wrought out in thee,
wait for the appearing and working of that power,
which (by its appearing and working) doth effect
it daily more and more in those that unite to it,
and give up to its operations.
Oh! wait to feel the power begetting somewhat of its own nature in thee,
leavening thee into its nature by the pure,
heavenly leaven wherewith God waits to leaven thy heart.
Thus feel thy beginning from the true root, from the holy principle,
from the seed of the kingdom; and then wait to feel that grow up in thee,
and to grow up therefrom, that as the beginning is pure, so the growth may be pure also.
For after God hath visited thee, and begotten somewhat in thee,
and leavened thee in some measure, so that there is true life, true sense,
true hungerings, true breathings, after the Lord and his righteousness,
after the fountain of living waters,
then (in the next place) mind and wait to learn of
the true teacher how to come to the true waters,
that thou mayest drink thereof, and of no dirty puddle,
of thy own or any other`'s forming.
Where are these waters dispensed and where are they to be found?
Why, in the new covenant, which God makes with the hungry and thirsty souls,
as they come to the Shepherd, and hear his voice, and learn of him, and follow him.
Therefore thou must wait to distinguish spirits,
and the knocks of spirits in thy own heart.
Thou must know when the Shepherd knocks, and when the stranger knocks;
and let in the Shepherd when he knocks, and not let in the stranger when he knocks.
Thus, by knowing him, inclining thine ear to him, and hearing his voice,
thou comest to have the everlasting covenant made with thy soul,
even the sure mercies of David, wherein the union with God is sure, the teacher sure,
never more to be removed from thee; the fear which God puts into the heart sure;
the law of the new life sure,
being so written in thy heart by the finger of God`'s Spirit, as none can blot out;
the love of God sure, his preservation sure, the inheritance of life sure.
O sweet covenant!
O holy covenant!
O blessed covenant! and blessed are all those souls with whom God makes this covenant,
and who are kept by him in the sense and enjoyment of it!

Now, lastly, after God hath made this covenant with thee, and spoken peace to thee,
and given thee of the power, righteousness, and joy of the kingdom,
and set the holy hedge of his power and wall of salvation about thee,
thou must take heed of going forth after any lust, after any desire of the flesh,
after any temptation of the enemy; thou must keep within the holy limits,
and not touch any dead or unclean thing, lest thou be defiled,
and so in degree separated from him who is pure.

The occasion of what follows was briefly thus:

There was a controversy between me and another about many of these things,
towards whom my love was in a travail;
and having a sense on my heart that the enemy makes use of the wrong apprehensions
and mistakes he begets in men`'s minds about these things,
contrary to the true knowledge and experience which God
giveth to the children which are born of the heavenly womb,
who indeed alone can rightly plead for and justify their mother,
in this day of great strife and contention about the kingdom,
and the right heir thereof,--I say, having this sense on my heart,
and these things naturally springing up and opening in me upon this occasion,
I was drawn in love, and in the motion of life, thus to give them forth to others,
hoping that the Lord may thereby open the minds of some towards,
and confirm the minds of others in, the sense and belief of the truth,
and the inward manifestation of his Spirit,
which discovers and strives against the darkness, lusts, and corruptions in them.
The Lord give people the sense of the strivings and
reproofs of his Holy Spirit inwardly in their hearts,
and join their spirits thereto, that they may receive light, life, virtue,
and strength from his Holy Spirit,
and thereby witness the overcoming and keeping under the enemy of their souls,
that they may know what it is to have the seed of the woman
bruise the serpent`'s head in their own particulars,
that so the holy child Jesus may be exalted (his horn exalted in them).
and he may reign, and exercise his government in them,
and they may become kings and priests to God,
and reign in him over all that his power is ordained to break and keep under, yea,
utterly consume and destroy,
in the hearts of those that submit themselves willingly to him,
and walk in the light and leadings of his Holy Spirit.
Amen.

=== NAKED TRUTH

==== I. Concerning understanding the Holy Scriptures truly and aright

Question.
WHETHER the Scriptures can be understood aright,
without the light of God`'s Holy Spirit shining inwardly in the heart,
and giving the true understanding of them?

Answer.
No; not possibly.
For as the outward eye cannot possibly see without the shining of some outward light,
no more can the inward eye see without the shining of the inward light.
God, who commanded light to shine out of darkness,
causeth the light of his Spirit to shine in the hearts
of people according to his holy pleasure,
and thereby they come to see.
God seeth all things in his own light, in the light of his pure, eternal Spirit;
and in his light do the children of light see light.
The things of God`'s kingdom are holy mysteries,
and the words which he speaks concerning those holy mysteries none can understand,
but as he pleaseth to open and reveal them.
He hath given us an understanding to know him that is true. 1 John 5:20.
"`The inspiration of the Almighty giveth
understanding,`" (Job 32:8) without which,
man is dead, and can neither hear, nor see,
nor understand any of the things of God`'s kingdom.

==== II. Concerning the illuminating Spirit, and sanctifying Spirit

Question.
Whether the illuminating and sanctifying Spirit be one and the same Spirit or no?
because it is affirmed by some (and written by one to me as a sound distinction of divines,
which distinction he saith he hath a mind I should
learn) that there is a Spirit of sanctification,
and that is peculiar to the godly; and there is a Spirit illuminating,
and that is oft vouchsafed to the wicked, as it was to Balaam.

Answer.
The Spirit which illuminateth, and the Spirit which sanctifieth,
is one and the same Spirit;
and the illumination of the Spirit is in order unto sanctification.
The same light which discovereth the darkness, also chaseth away the darkness,
as it is received and subjected to, and purifieth the mind;
for the light hath not only a property of enlightening,
but also of cleansing and sanctifying.
And the reason why men are not changed, justified, and sanctified, in and by the light,
is because they love it not, and bring not their hearts and deeds to it;
and so it is their reprover and condemner, and not their justifier and sanctifier.
But the same Spirit, light and life which enlighteneth, also sanctifieth,
and there is not another.

==== III. Concerning the Holy Spirit of God, and the Holy Scriptures

Question.
Whether they be always joined; or some may have the Spirit, who have not the Scriptures;
and some may have the Scriptures, who have not the Spirit?

Answer.
The Holy Spirit of God, and the holy Scriptures, are not always joined together;
for some in the dark corners of the earth may be visited by the Spirit,
become sensible of the Spirit, and receive the Spirit, who never heard of the Scriptures;
and many may have the Scriptures, and yet be very ignorant of, and strangers to,
God`'s Holy Spirit; as the Jews were,
who had them read in their synagogues every sabbath day, and yet Christ told them,
"`Ye neither know the Scriptures, nor the power of God.`"

==== IV. Concerning the Law of the Lord, which is perfect, and which converts the soul

Question.
What is the law of the Lord, which is perfect, and converts the soul?
Is it the outward law or writing in the letter,
or the inward law and writing in the Spirit?

Answer.
No man is, or ever was, or ever can be,
converted to God from the inward law of sin and death,
but by the inward law of life and righteousness written in the heart;
and I am sure that law is perfect, the new covenant is perfect,
and the law thereof perfect; the law of the Spirit of life in Christ Jesus perfect,
which converts the mind to Christ, the righteousness of God,
and sets it free from the law of sin and death.
And David was a spiritual man, and knew the inward covenant,
and the inward creating of the heart anew, and God`'s holy and free Spirit,
and the law and testimony thereof.
I will grant a great deal to the letter and ministration outward;
but I must attribute more to the inward; or else God`'s light,
and the holy experience which he hath given me, will condemn me.
And as the Jew outward had the law, and testimony, and statutes outward;
so I am sure the true Jew, the Jew inward, hath the law, and testimony,
and statutes inward, written in his heart by the finger of God`'s Spirit; yea,
and the same Spirit put within him, to cause him to keep this law,
and the holy testimony, statutes, and judgments of the Lord; and the spiritual Jacob,
and Israel of God, in this the day of their redemption and salvation from on high,
do follow the Lamb whithersoever he goes, and walk in the light of the Lord.

==== V. Concerning David`'s longings, expressed in Ps. 42:43. 119. and other places

Question.
Were David`'s longings more after the law outward,
or after the law and light of God`'s Spirit inward?

Answer.
David was a man after God`'s own heart;
a man that knew an inward and clean heart of God`'s creating,
and knew the free Spirit of the Lord, and the fresh springing life thereof,
and the leadings of the pure, living truth inwardly in his heart,
and this was it he most especially prized and longed after.
"`Create in me a clean heart, O God, and renew a right spirit within me,
and take not thy Holy Spirit from me,`" etc., saith he, Ps. 51:10-11. after his fall,
showing what he had been acquainted with before,
and what he now (God having touched his spirit afresh) began to long after again.
And saith he, in another place, "`Oh! send out thy light and thy truth; let them lead me,
let them bring me unto thy hill, and to thy tabernacles.`" Ps. 43:3. Oh,
the sweetness of light within, truth within!
Oh, the precious leadings and drawings thereof, which were once felt,
upon a fresh and tender remembrance thereof, cannot but be longed after again!

==== VI. Concerning the Sun, or Fountain of spiritual Light

Question.
Whether the holy Scriptures, or written testimonies, be the sun or fountain,
and the light within but a ray or stream from them?
(as is affirmed by my antagonist.)

Answer.
It is just quite contrary:
for the holy men spake the holy words from the inward light
and quickening life of God`'s Spirit within them;
so that that was the fountain in them, and is so still.
"`With thee is the fountain of life; and he that believeth, as the Scriptures have said,
out of his belly shall flow rivers of living water.
This spake he of the Spirit,`" (John 7:39) that is the fountain.
"`The water that I shall give him,
shall be in him a well of water springing up into everlasting life.`" John 4:14.
Who esteems and honors the Scriptures aright?
He that believes their testimony, comes to Christ, and makes his Spirit, light,
and life all;
or he that sets the Scriptures in the stead of that Word of life which they came from,
testify of, and point men to,
as the fountain and foundation of life and salvation to all mankind?

==== VII. Concerning the Word`'s being a fire and a hammer to burn up the chaff, and break the rocks in pieces

Question.
Is the Word, which is a fire and hammer,
the testimonies and declarations of the holy Scriptures without,
or the Word nigh in the mouth and heart?

Answer.
That which I have felt hammering inwardly,
that which I have felt burning inwardly (unquenchably, as the mind has been kept to it),
has been the Word of life itself, from which the good words and holy testimonies proceed.
That which does the work in the inward Jew is the
inward ministration of the inward covenant,
the appearance of God there.
He is the consuming fire; he is the Spirit of judgment and burning, who,
by his holy flamings inwardly, burns up the filth of the daughter of Zion.
A man may be exercised in the letter all his days,
and yet witness nothing of this inwardly in truth and righteousness;
but he whom the Spirit of judgment and burning inwardly comes nigh,
and whose flesh is kept in that holy furnace, it will be consumed there day by day,
until it be quite wasted and destroyed,
and so he come to be judged according to the flesh, and to live to God in the Spirit.

==== VIII. Concerning God`'s writing his law in the heart

Question.
How doth God write his law in the heart?

Answer.
By his Spirit and power working there, whereby he both creates a new heart,
and writes the new law, even the law of the Spirit of life in Christ Jesus,
in the new heart.
"`The isles shall wait for his law.`" Whose law?
The law of the Messiah, the law of grace, which gives dominion; the law of the anointing,
the law of the new birth, the law of the holy seed.
"`His seed remaineth in him.`" 1 John 3:9. In that seed is the new nature,
and the new law both.
What is the law of sin?
What is the law of death?
How is it written in the heart?
How doth the enemy write it there, but by his corrupt spirit and nature?
And doth not God, by his holy Spirit and nature, write the new law, the law of life,
in the hearts of those that are renewed and made tender to the impressions of his holy,
quickening power?
Every motion and drawing whereof is a law to them who are born of the Spirit,
and taught of God to eye and walk after the quickening Spirit.

==== IX. Concerning the inward light of God`'s Spirit

Question.
What is it which the mind is to be turned to, to enlighten it,
and to work the darkness and corruption out of it?

Answer.
It is no less than the light of God`'s Spirit; nothing else can do it.
The day-spring must arise from on high in the heart,
or there will be night forever there.
All notions or apprehensions concerning the light will not do it;
it is the shining of the light alone inwardly which is able to expel the darkness there.
It was not for nothing that Christ came a light to enlighten men,
and directed men to follow him, the light, that they might not abide in darkness,
and that he sent his apostles with this message, that "`God is light,
and in him is no darkness at all;`" and so gave his apostles wisdom, authority,
and power to turn men from the darkness to the light.
And if the darkness was within, which they were to be turned from,
surely the light must shine within, to discover the darkness,
and to that light must they be turned.
And in this light the Holy Spirit is received, and dwells there; but out of this light,
and the limits thereof, in every heart, dwells the unclean and dark spirit,
and hath power and rule there;
for nothing but the light and strength of God`'s Spirit is able
to break his kingdom and dominion inwardly in the heart.

==== X. Concerning the ministers and ministry of the gospel

Question.
Who are the ministers, and what is the ministry of the gospel?

Answer.
They are the ministers of the gospel who have received the
Spirit and power wherein the ministry of the gospel stands.
For Christ came in the Spirit and power of the Father,
and he sends his apostles and ministers in the same Spirit and power,
that they might be able to beget,
and reach to that birth which is to be begotten and ministered to.
It is one thing to be a minister of the law, and to minister letter;
and another thing to be a minister of the gospel, and to minister Spirit.
The apostles were able ministers of the New Testament; not of the letter,
but of the Spirit; and so are all in a degree,
who succeed them in any measure or proportion of their ministry.
For the ministry of the gospel is in the light, Spirit, and power of the Most High,
to turn people`'s minds to a proportion of the same light, Spirit,
and power in themselves,
and so to come to the manifestation and quickening of the same life in themselves,
that so they may walk in the same light.
For the life is the light; and he can never have light, or see light,
who comes not first to feel some virtue from the quickening power.
Oh! how precious is this ministry!
Blessed be the Lord for his renewing of it in these our days!
And this ministry is not to be confined to an outward order of men,
as the ministry of the law was; but whoever hath received the gift, so he is to minister,
as the Lord guides, leads,
and orders him in the use of that gift which he hath bestowed upon him for that end.
And what if he be an herdsman, a fisherman, a tentmaker, or the like?
Yet if God hath poured out his Spirit upon him, and openeth his mouth,
he hath not only liberty, but more, even authority,
from the Lord God Almighty to speak in his name, either for turning men unto Christ,
the light and life of men, or for building men up in their holy faith in him,
whose Spirit and power was and is the resurrection in the life forevermore.

==== XI. Concerning trying of spirits, and searching the heart

Question.
What is it which searcheth the heart, and infallibly tries spirits?

Answer.
God`'s Spirit, God`'s word nigh in the heart and mouth,
separateth and giveth true discerning and judgment there,
to all whose ears are circumcised and inclined to it.
God`'s Spirit is the spirit of judgment; and where he is given,
the Spirit of judgment is given,
and he judgeth in his children by the quickening life and sense he bestoweth on them,
which distinguisheth between life and death, between truth and deceit; yea,
between the same words, when they come from the dead spirit,
and when they are spoken in his living power: Christ gives his Spirit to his sheep,
which gives them to know his voice, to know when life speaks, and when words are living,
and food for the living; and in what mouth they are dead,
and cannot yield living nourishment.

==== XII. Concerning things necessary to Salvation

Question.
Whether all things necessary to salvation be contained in the Scriptures?

Answer.
The Scriptures give testimony concerning the one thing necessary to salvation;
but the thing itself, Christ himself, the seed itself,
is not contained in the Scriptures, but revealed in the shinings of the true light,
and so received or rejected inwardly in the heart.
"`Behold I stand at the door and knock.`" Blessed are they that hear his voice,
and believe him knocking, and open to him, and receive him,
who gives eternal life and power to become sons of God to as many as receive him,
and believe in, and give up to,
the inward revealings of his redeeming arm and power therein.
"`To whom is the arm of the Lord revealed?`" To them in whom, and to whom,
this arm is revealed, Christ is revealed; and they in whom, and to whom,
Christ is revealed, know the one thing necessary, even him who is life eternal,
in whom all other necessary things are wrapped up,
and by whom they are conveyed to the soul, according to its need,
by him who is faithful in all his house,
and takes care of every sheep which the Father committeth to him.

==== XIII. Concerning the true Gospel Church, or Society

Question.
What is the true gospel church, or society?

Answer.
A company of true believers in the Spirit and power of the Lord Jesus Christ.
A company of true Jews, inward Jews, Jews in Spirit, of the true circumcision,
whom the Father had sought out, and made true inward worshippers;
such as are gathered to the name, and gathered together in the name of the Lord Jesus,
to offer up spiritual sacrifices to God through him.
A company of living stones, who have received life from him, the foundation stone;
and meet together to wait upon and worship the Father,
in the light and Spirit which they have received from him.
This is the holy church, or living assembly of the New Testament;
blessed are they that are of it!
For about this church is the wall of salvation;
and they that are added by God`'s Spirit and power to this church, and abide in it,
shall certainly be saved.

==== XIV. Concerning the Way to Salvation

Question.
Which is the certain and infallible way to salvation?

Answer.
It is a new and living way; it is such a way as none but the living can walk in.
It is a holy way, which none but the cleansed, the ransomed, the redeemed of the Lord,
can set one step in.
The way, the life, and the truth are all one; blessed are they that find it,
and walk in it!
In plain and express terms, it is the Lord Jesus, the light of the Lord Jesus,
the life of the Lord Jesus, the Spirit of the Lord Jesus, the truth as it is in him,
his wisdom, his power, he himself, the covenant or holy limit between God and the soul.
He that comes into him, comes into the way; he that abides in him, abides in the way;
he that walks in him, walks in the way.
He that comes to his light, his life, his Spirit, his truth in the inward parts,
comes to him; he that abides therein, abides in him; he that walks therein, walks in him:
and he that walks out of the light and leading of his Spirit,
let him walk in what form he will, yet he walks not in him, the way.

==== XV. Concerning Christ`'s saving the Soul.

Question.
How doth Christ save the soul?

Answer.
By visiting inwardly, knocking inwardly, appearing inwardly,
causing the light of life to shine inwardly, and so enlightening and quickening inwardly,
breaking the strength of the enemy inwardly,
and bringing out of the region and shadow of darkness inwardly,
into the region and path of light.
By the light and power of his Spirit he begets a child of light;
which child of light he brings out of Egypt, the dark land; out of Sodom, the filthy,
unclean land; out of Babylon,
the land and city of confusion (where the Spirit of the living God,
and the holy order of life, and his precious government in the heart,
is not so much as known), and brings him into the light, where he and his Father dwells.
And this child of light is not of the nature of darkness, but light in the Lord,
and walks in the light, as he is in the light;
and by the further shining and working of the light and life in him,
he preserves and saves him daily more and more.

==== XVI. Concerning Regeneration, or the New Birth

Question.
What is regeneration, or the new birth?

Answer.
It is an inward change, by the Spirit and power of the living God, into his own nature.
It is a being begotten of his Spirit, born of his Spirit;
begotten into and born of the very nature of his Spirit.
("`That which is born of the Spirit, is Spirit,
"`John 3.) It is not every change of mind which is the right change;
but only that which God,
by the very same power wherewith he raised our Lord Jesus Christ from the grave,
makes in the hearts of those whom he visits; who are sensible of, receive,
and are subject to his inward life, light, and power.

==== XVII. Concerning true Holiness

Question.
What is true holiness?

Answer.
That holy nature, and those holy actions, which arise from the holy root;
all else are but imitations of holiness, not the true holiness.
The tree must be made good first, and then the fruit will be good also.
There are many likenesses of the true holiness up and down in several professions;
but there is no real holiness to be found, nor righteousness either,
but in the trees of God`'s planting,
in the branches which are by him ingrafted into the true vine and olive-tree,
whose strength of virtue and holiness lies in the sap, which they daily receive from him.

==== XVIII. Concerning Christ`'s Works outwardly in the days of his flesh, and inwardly in the day and inward shining of the light of his Spirit in the heart

Question.
Which are greater,
the works which Christ did outwardly on the bodies of men in the days of his flesh,
or which he doth inwardly in men`'s minds and spirits
by the powerful appearance and operation of his Spirit?
Because Christ said, the works that he did, those that believed on him should do,
and greater also, because he went to the Father. John 14:12.

Answer.
Doubtless to reach to the soul, and quicken the soul,
and raise the soul out of the grave of death, and cure the blindness, deafness, hardness,
and diseases of the soul, is greater than the outward, and was signified by the outward.

==== XIX. Concerning the yoke, or cross of Christ

Question.
What is the yoke or cross of Christ?

Answer.
It is inward, as that which is to be crucified is chiefly inward.
It is that gift of God, that light of his Spirit which is contrary to the darkness,
contrary to all that is corrupt; which wills and wars against it; and being received,
subjected to, and borne patiently, takes away the life of the flesh,
the will and wisdom of the flesh,
and all the subtle reasonings and devices of the fleshly part;
and so that languishes and dies, and God`'s plant is eased of it;
and the soul abiding under this cross, comes into the true, pure, and perfect liberty,
where it hath scope unto holiness, freedom unto righteousness,
and is in strait bonds and holy chains from all liberty to the flesh,
and from all unholiness and unrighteousness of every kind.

==== XX. Concerning making our calling and election sure

Question.
How may a man make his calling and election sure?

Answer.
By making the gift of God sure to him;
by making that sure to him wherein his calling and election is.
For the choice is of the seed, the holy seed, the inward seed, the seed of God`'s Spirit,
and of the creature as joined to the seed.
God would have none to perish; but would have all come to the knowledge of Christ,
the truth, who is the seed, in whom the election stands; and his holy advice to men is,
whom he begins to call and to lead towards the election,
"`to make their calling and election sure.`" So that
the way of making the calling and election sure is,
to make the gift sure, the seed sure, the leaven sure, the pearl sure,
which God will never reject, nor any that are found in true union with it,
and in the love and obedience of it.
Oh! therefore, as God visits with power (with his powerful gift),
and as thou receivest power, dominion,
and authority over sin (for in this gift is God`'s dominion and authority revealed),
be faithful to the gift, be faithful to the power,
give up to the truth in the inward parts, come into it, dwell in it,
that thou mayest feel its virtue and delivering nature
from every enslaving and embondaging thing,
and then stand fast in the liberty wherewith Christ the Lord (by the life, virtue,
and power of his truth) sets thee free.
And so here thou wilt read thy calling, and read thy election day by day;
and find them sealed, and sure to thee, in that truth, in that gift,
in that heavenly light, in that holy seed, which came from God, and is of him,
and which he delights to own, and will never reject.

==== XXI. Concerning Prayer

Question.
What is the true prayer?

Answer.
The breathings which arise from the true birth,
from the living sense which God gives to the true birth; these are the true prayer.
There is a Spirit of prayer and supplication given by God
to his children to wrestle and prevail with him by.
All prayer that arises from, and is given by, that Spirit, is true prayer;
all other prayer is not right and true, but at best an imitation of the true.
"`We know not what to pray for as we ought;
but the Spirit maketh intercession for us with groanings which cannot be uttered.`" Mark:
the very groanings that come from God`'s Spirit,
from his breathing and work upon the heart, are right prayers in God`'s sight;
but other sighs and groans are not so.

==== XXII. Concerning Repentance

Question.
Which is the true repentance?

Answer.
That which Christ gives, whom God hath exalted to be the prince and Saviour,
to give repentance and forgiveness of sins. Acts 5:31.
It is not in man`'s power to repent; his heart is hard and impenitent.
It is God`'s power which melteth, tendereth, and changeth the heart.
So that there is a great difference between the sense and sorrow of man`'s nature,
and the sense and sorrow which God gives to the heart which he renews and changes.
The one is of an earthly, the other of a heavenly, nature.
The one is like the early dew, or morning cloud, it soon passeth away;
the other is written in the new heart, and abideth.
So that in it there is a real sorrow and mourning over the corrupt nature,
and all the dead works of the flesh, and a turning from them,
and meddling no more with them.
This is the repentance of the renewed ones,
which is the gift of the Lord Jesus Christ unto them,
and is a godly sorrow for sin not to be repented of.

==== XXIII. Concerning Faith

Question.
What is the true faith?

Answer.
It is a belief in the power which saves,
from a true sense and experience of it in the heart.
For the power which saves must first manifest itself, before it can be believed in;
and how doth it manifest itself, but by shining in the heart,
which hath been darkened by transgression, to open the eye of the understanding,
which the god of the world hath blinded, and to unstop the deaf ear,
and so it begets and creates somewhat capable to receive its further manifestation.
The Scripture speaks of a new creation in Christ.
Indeed all true believers are so: and they have the ability, the faculty,
the power of believing from him who creates them anew.
There is that which is called faith in unregenerate men;
but that is not the faith I am now speaking of,
but that which is the gift of God to his own birth, to his own begotten.
"`To you it is given not only to believe,`" etc. Phil. 1:29.
Mark: It is given to believe.
Oh, this holy gift! this faith of the new birth is the faith which pleaseth God,
prevaileth with him, purifieth the heart to which it is given, giveth access to God,
interest in his power and promises, and victory over the worldly nature,
and over all the soul`'s enemies.
Blessed be the Lord for bestowing and increasing it in the hearts of his children.

==== XXIV. Concerning Obedience

Question.
What is obedience?

Answer.
The obedience which flows from the true understanding of God`'s will,
and from the holy nature which he begets in the heart.
It is the obedience which flows from true sense, true understanding, and true faith.
There is no birth can believe aright but one; nor is there any birth can obey aright,
but that birth which believes aright.
The true believing is from the quickening virtue
of God`'s Spirit (all other faith is but dead faith);
and the true obedience is in the newness of the Spirit.
Rom. 6:4 and 7:6. Man may strive to understand and obey all his days;
but he can do neither, but as he is quickened, taught, and enabled of the Lord.
"`Teach me, O Lord,
the way of thy statutes.`" Ps. 119:33. There is a mystical path of life.
The way of wisdom, the way of holiness, the holy skill of obeying the truth,
is hid from all living, from all mankind,
but such as are begotten and brought up by him in
the holy skill and mystery of subjection to the Lord.
"`Thy people shall be a willing people in the day of thy power.`"
It is the power of God that works the will in the heart,
and the same power works to do also; and none can learn either to will or to do aright,
but as they come to be acquainted with that power, joined to that power,
and feel that power working in them.
And here, in this power, to this new birth, faith and the holy obedience are as natural,
as unbelief and disobedience are to the birth of the flesh.
It is frequently and abundantly experienced by his holy birth,
by the child of his begetting.
Blessed be the name of the Lord.

==== XXV. Concerning Justification

Question.
What is justification, or how is a man justified in the sight of God?

Answer.
By a true sense of, and faith in, that which justifies; which is the Spirit, the life,
the water, the blood, the virtue, the power of the Lord Jesus.
All these are one in nature, and they go together.
Man is sinful naturally, fallen from God, found a transgressor against him.
Now he needs justification from his sins,
and he needs justification in respect of what God hath entrusted him with,
and requires of him; and in the new birth,
and joining to the Spirit of the Lord Jesus Christ, he meets with both.
Being quickened by his Holy Spirit, turned from the darkness, coming into the light,
and walking in the light; there his sins are done away, blotted out,
as if they had never been, for his name`'s sake; and there he receiveth a new ability,
a new heart, a new Spirit, yea, the Spirit of the living God, to quicken him,
and work in him; and whatever he doth in this Spirit (or rather what God doth by him,
in and through this Spirit) is justified, owned, and accepted.
God finds no fault in any of the fruits of his own
Spirit (in any of the children of men),
but only in the fruits of the flesh.
And if, for want of watchfulness, the enemy should prevail, and draw into a snare;
yet upon turning to the light of God`'s Holy Spirit, which discovers and reproves for it,
in the holy light the water flows, the blood is sprinkled, the conscience is cleansed,
and so becomes clean even in God`'s sight.
Oh! blessed is he who is not deceived with dead notions of justification,
but feels the justification which comes from God, and is accompanied with a living sense,
and with the testimony of his Holy Spirit.

==== XXVI. Concerning good Works

Question.
What are good works?

Answer.
The works that flow from God`'s good Spirit, the works that are wrought in God,
they are good works.
The works of the new birth, of the new creature, are good works;
whereas all the works of the flesh are bad, though never so finely painted.
All its thoughts, imaginations, reasonings, willings, runnings,
hunting to find out God and heavenly things, with all its sacrifices,
are corrupt and evil, having of the bad leaven, of the bad nature in them.
Make the tree good, or its fruit can never be good:
so that they are only the good works that flow from the good tree, from the good root.
And here all the works of the flesh, though never so glorious and taking in man`'s eye,
are shut out by God`'s measure,
by God`'s line and plummet of righteousness and true judgment;
and every work of God`'s Spirit, the meanest work of faith, the least labor of true love,
the least shining of life in the heart, and the giving up thereto,
is owned by God as coming from him, and wrought in him,
who worketh both to will and to do, of his own good pleasure.
He that is gathered to the light which God hath enlightened him with,
hath received the light, dwelleth in the light, and walketh in the light;
the Spirit of the living God is near him, and dwelleth with him, and worketh in him;
and he bringeth his deeds to the light,
where it is manifest that they are wrought in God.
But he that is out of the inward light of God`'s Holy Spirit,
his works are not wrought in God,
and so can but make a fair show in the flesh (to
the fleshly eye) but are not good in God`'s sight.
The erring man`'s way and works are often right in his own eyes;
ah! but blessed is he whose way and works are good and right in the eye of the Lord,
in the judgment of his searching, unerring light and Spirit.

==== XXVII. Concerning Love

Question.
Which is the true love?

Answer.
The love which ariseth from the nature which God begets,
and from this circumcising the heart from the other nature.
Love is the beautiful thing.
What can be higher expressed concerning God himself, than to say he is love?
Love is greatly commended and admired, and there are many pretenders to it;
but none have the true love, but only those that are born of God, and circumcised by him.
"`The Lord thy God will circumcise thine heart, and the heart of thy seed,
to love the Lord thy God with all thine heart, and with all thy soul,
that thou mayest live.`" Duet. 30:6. Mark:
the true love ariseth from the true circumcision;
and the more a man comes to have his heart circumcised from the fleshly nature,
and to grow up in the pure and heavenly nature, the more he loves.
God is love; and the nigher any one comes to him, and the more he partakes of him,
the more he becomes love in the Lord,
and the more he is taught of God to love the Lord his God,
and his brethren in the Spirit, and all mankind,
who are of his blood (for of one blood God made all mankind) according to the flesh,
or according to a natural consideration.

==== XXVIII. Concerning Meekness and Patience

Question.
What is the true meekness and patience?

Answer.
The meekness and patience which ariseth from the Lamb`'s nature.
Deceit will put on an appearance of love,
and deceit will put on also an appearance of meekness and patience;
but it cannot put on the true love, the true meekness and patience:
that is only learned of the Lamb,
and received of him by receiving of his Spirit and nature from him.
And oh, how precious is this! how sweet is it felt in the heart!
To feel a meek, a quiet, a patient spirit in the midst of all trials, all troubles,
all fears, all doubts, all temptations of every kind.
Indeed this is of much price in the sight of the Lord,
and also in the eye of him who hath received it from the Lord, and enjoyeth it in him,
and possesseth his soul in him.

==== XXIX. Concerning the knowledge of the new covenant

Question.
What is the knowledge of the new covenant?

Answer.
The knowledge which is given by God to the new birth: for to it the new covenant belongs,
and the knowledge thereof.
The truly begotten of God, the true disciples of Christ,
to them it is given to know the kingdom of God; but to others it is not given.
The Jew outward, the first birth, the birth after the flesh,
for them the priest`'s lips were to preserve knowledge,
and they were to seek the law at his mouth;
and to them God sent prophets to speak to them, and taught them by his prophets:
but concerning the inward Jews, the children of the new covenant,
the children of the Jerusalem which is above, concerning her seed it was prophesied,
that they all should be taught of the Lord;
they all should hear and know the voice of the Shepherd himself;
they should all be gathered to the Shepherd and Bishop of the soul, and taught by him.
So that in this new, holy, living covenant, God himself is the Shepherd,
God himself is the Teacher, not only of the greatest, but of the very least.
Heb. 8. For he teacheth them all to know the Lord, and to know his Son,
and to come to his Son, and to love him their Father, and one another.
So that he that is taught of God, he hath the true knowledge, the living knowledge,
the substantial knowledge, the knowledge of the thing itself, of the life eternal itself.
All that are not thus taught (but learn only from a literal description
and relation of things) have not the knowledge of the new covenant,
the knowledge of the thing itself; but only an outward knowledge,
such as the first birth may catch at, lay hold on, and comprehend.

==== XXX. Concerning the fear of the new covenant

Question.
What is the fear of the new covenant?

Answer.
It is the fear which God puts in the hearts of his children;
which fear cleanseth their hearts, and keepeth them from departing from their God.
There is a great deal of difference between the fear
which may be learned from precepts from without,
and the fear which God puts in the hearts of his children from a root of life within;
which fear is of a heavenly nature,
and is the free gift of God to his own heavenly birth, and none else;
which no man can possibly attain by any thoughts or reasonings of his own,
but only by the springings of life from God.
And he that would have this fear, must know the place of wisdom, and wait there for it;
and when he hath it, this fear will soon begin to make him wise towards salvation,
and teach him to depart from evil, which is the cause of destruction. Job 28:28.

==== XXXI. Concerning Hope

Question.
What is the true hope?

Answer.
The stay of the mind upon the Lord, the stay of the heavenly birth upon its Father:
for we must distinguish between hope and hope.
There is the hope of the hypocrite, or false birth, which shall perish;
and the hope of the true birth, which will never fail it, nor make it ashamed;
because that birth is taught of God to hope aright.
Now, in hope, there is both the ground of it, and the hope itself.
The ground of the hope is God`'s love, God`'s truth, God`'s faithfulness, God`'s grace,
his seed, his Christ felt within; being of him, united to him, in him, he in me:
here is the ground of my assurance of the everlasting glory and inheritance,
which is sure to the seed, and to all that are of and in the seed.
So knowing Christ within me, feeling Christ within me, living in him, and he in me,
I have an anchor sure and steadfast within the veil, which no storms, no tempests,
no trials, no temptations, present or to come, have power over.
And then there is the hope, or hoping itself; that is,
the staying of the mind upon the Lord, the leaning upon the Lord,
the retiring beyond all thoughts or reasonings or lookings out, to the inward life;
to feel somewhat spring from it, for the soul to hope or trust in,
beyond all outward appearance.
And this hope never deceives nor makes ashamed those who
are taught of God thus to stay their minds upon him.
Nay, though the state be darkness, and no light seen;
yet beneath the darkness there is somewhat to stay the mind
of the child and servant of the Lord till he appear,
and cause light to break out of obscurity; for light is sown for the righteous,
and joy for the upright, even in their darkest, saddest, and most distressed conditions;
in all which the Lord is near them, and there is still ground for them to hope in him.

==== XXXII. Concerning Peace

Question.
Which is the true peace?

Answer.
The peace which God speaks to the soul; the peace which Christ gives to his own disciples.
The way of truth, the way of life leads to peace;
and the peace which is found therein is of God`'s giving, and is the true peace.
First, God breathes upon the heart, begets a right birth, a true child;
then he leads him into the holy way, the righteous way;
from that which loads and burdens, to that wherein is the ease and rest.
Thus in the believing and following him there is joy and peace.
This is experienced by all the true travellers, and by none else.
No man, with all his wisdom, knowledge, and understanding,
can so much as guess at what this peace is.
The peace of God, the peace which he speaks to his children, the nature of it,
the sweetness of it, the heavenliness of it, passeth man`'s understanding;
but he who is born from above, who hath a new and heavenly understanding,
he knoweth the nature, excellency, and preciousness of it;
and would not for all this world, for any fear, or danger,
or expectation of any thing from without,
hazard the breaking off this precious peace and rest of his soul in his God.

==== XXXIII. Concerning Joy

Question.
Which is the true joy?

Answer.
The joy which flows from God`'s presence, and the work of his power in the heart,
and the assured expectation which he gives of the
full inheritance and glory of life everlasting.
When the bridegroom is present, when the soul is gathered home to him, married to him,
in union with him, in the holy, living fellowship;
when he appears against the enemies of the soul, rising up against them, breaking,
scattering them, and giving of his good things, filling with life, filling with love,
filling with virtue, feasting the soul in the presence of the Father; oh,
what sweet joy! oh,
what fulness of joy is there then in the heart! "`In thy presence is fulness of joy,
and at thy right hand are pleasures forevermore,`" said the psalmist. Ps. 16:11.
Surely he had had a taste of the thing, he had been in God`'s presence,
and that made him cry out, "`Cast me not away from thy presence,`" Ps. 51:11;
and he had drunk of the river of God`'s pleasure, which is at his right hand,
which made him speak so sensibly of it. Ps. 36:8.
and 46:4. Christ said to his disciples,
that because of his going away they should have sorrow; but he would see them again,
and their heart should rejoice, and their joy no man should take from them. John 16:22.
How or when was this fulfilled?
What were they sorry for?
Was it not the loss of his outward presence,
which had been so sweet and comfortable to them?
How would he come to them again?
Was it not by the Comforter?
Was it not by his inward and spiritual presence?
So that he that was with them should be in them?
Before they knew Christ with them; now they should know Christ in them;
the Father in them, and they in him; Immanuel, the gospel state, God with us,
dwelling with us, tabernacling in us, living in us, walking in us,
and we living and walking in him.
When the apostles came to this state,
then they came to witness the joy in the Holy Ghost, even the joy unspeakable,
and full of glory.
And hence it is that the gospel state is a state of joy and rejoicing in the Lord,
even in his glorious, living presence, and in the glory of his power.
For in the gospel state the true light shines inwardly in the heart,
the life is manifested; and being manifested,
they that come into the manifestation of it, come into the holy union,
and into the holy fellowship with the Father and Son, where the joy is,
and where the joy is full;
where the power is revealed which does away that which is contrary to the holy fellowship,
and hinders the holy joy and rejoicing in the Lord.
See 1 John 1:3-4.

==== XXXIV. Concerning poverty of spirit and humility

Question.
Which is the right poverty of spirit, and the true humility?

Answer.
That poverty and humility of spirit which springeth
from the same root from which the faith,
the love, the peace, the joy, and the other heavenly things arise;
and is of the same nature.
There is a voluntary humility, and a voluntary poverty, even of spirit,
which man casts himself into, and forms in himself, by his own workings and reasonings.
This is not the true, but the false image, or counterfeit of the true;
but then there is a poverty which ariseth from God`'s emptying the creature,
from God`'s stripping the creature;
and a humility which ariseth from a new heart and nature.
This is of the right kind, and is lasting,
and abides in the midst of the riches and glory of the kingdom.
For as Christ was poor in spirit before his Father,
and lowly in heart in the midst of all the fulness which he received from him;
so it is with those who are of the same birth and nature with Christ.
They are filled with humility, and clothed with humility,
in the midst of all the graces and heavenly riches
which God fills them and adorns them with.
Keep in the faith, keep in the truth, keep in the light, keep in the power;
it excludes boasting in or after the flesh,
and keeps the mind in that humility and poverty of spirit which God hath brought,
and daily further and further brings it into;
and so the humility and poverty remain (poor in spirit forever,
humble in spirit forever,
nothing before the Lord forever) even as that remains which brought into that frame,
and keeps in that frame forever.
And so the Lord of life is only exalted, and the creature kept abased before him,
and low forever; and is nothing but as the Lord pleaseth to fill,
and make it to be what it is.
So what I am, I am by God`'s love, by his grace, by his mercy, by his goodness,
by his power, by his wisdom, by his righteousness, by his holiness,
which he of his own good pleasure communicateth and causeth to spring in me,
and filleth and clotheth me with, as seemeth good in his sight.

==== THE CONCLUSION

THERE is mention made in the book of the Revelations,
in the epistles from Christ to the seven churches of Asia, of a tree of life,
which is in the midst of the paradise of God (the fruit whereof is good for food,
and the leaves thereof for the healing of the nations); and of hidden manna,
and a white stone, and in the stone a new name written,
which none knoweth but he that receiveth it; and of a morning star to be given,
and power over the nations, to rule their spirit,
even as Christ hath received of his Father; and of being clothed in white,
and his name confessed before the Father (this is the sheep of my fold,
the child of my Father`'s begetting, who is named by me among the living,
I know him by his name, John 10:3); as also of his being a pillar in the temple of God,
and of going no more out, but bearing the name of God, and the name of the city of God,
the new Jerusalem which cometh down from God out of heaven;
and of Christ`'s new name (oh! what is that!) and of sitting with Christ in his throne.

This is the generation of spiritual kings, who have a spiritual kingdom,
and a spiritual throne, even Christ`'s kingdom, and Christ`'s throne,
the royal priesthood of God.
Oh, precious things!
Oh, rich glory!
Surely eye hath not seen, nor ear heard,
nor hath it entered into the heart of men to conceive what these things are.

Now he that would witness these things; he that would know, experience,
and enjoy these things, must mind that seed in which they are wrapped up, as in a seed,
and out of which they spring and shoot forth.
The kingdom is in the seed, the throne in the seed, the power in the seed.
He that is united to the seed, and abideth in the seed, receiveth power from the seed,
and overcometh, he shall inherit all things; and I will be his God,
and he shall be my son. Rev. 21:7.
But he that will be so,
must not be fearful or unbelieving of overcoming sin, or his soul`'s enemies;
but must depend upon the almighty and all-sufficient power of God,
which will give him victory over sin, and keep him that he touch no unclean thing;
that he may be holy, as the Lord his God is holy; and righteous,
even as the Lord his God is righteous.
Indeed it becometh the heavenly children to partake of the divine life,
of the heavenly nature of their Father, and be like him.
And he that partaketh of his nature, of his holiness, Heb. 12:10, is holy,
as he is holy; and he that from the holy root of purity and righteousness,
doth righteousness, is righteous, even as he is righteous. 1 John 3:7.
So it is written without, and so it is testified within,
by him that is born of God in whom the seed remaineth, which overcometh the wicked one,
bruiseth him and keepeth him under:
and the just live by the faith which giveth victory over him.

=== A PREFACE TO THE EXPERIENCES

It hath pleased the Lord, to unseal and open the Fountain of life,
in the midst of his heritage; so that in his light do they see light,
and in his life do they reap and enjoy life.
And the precious promises are fulfilled in the midst of them, of sending the Comforter,
and pouring out of the Holy Spirit; so that he that believeth,
out of his belly do flow rivers of living water.
Yea, the Lord hath a vineyard of his own planting,
which he keepeth night and day (lest any hurt it), and watereth every moment.
Oh, the streams of life, the streams of love, the streams of grace, the streams of mercy,
the streams of peace, the streams of joy and consolation,
which flow from him into the bosoms of his children!
Indeed grace and mercy and peace are multiplied from God our Father,
in and through the Lord Jesus Christ, daily;
insomuch as that saying of Christ to his disciples (John 16:26-27) is now fulfilled:
"`I say not unto you, that I will pray the Father for you;
for the Father himself loveth you,`" etc.
The Father in his love hath brought us to the Son,
and the Son in the same love hath brought us back to the Father;
and now the love flows from the Father, in and through the Son,
most naturally and abundantly.
And where the heart is circumcised, and much forgiven,
there also love returns back most truly and naturally; so that the Lord our God,
in the Lord Jesus Christ, is loved with all the heart, and with all the soul,
and nothing is thought too good to sacrifice to him,
nor any thing too much to suffer for him.
Oh, the pure love that springs and flows between the heavenly Father and the spiritual child!
The best love that is to be found in this world (in the
men of this world) is not worthy to be a shadow of it.
God is love: and his children are of him, and partake of and dwell in the same love,
though the enmity and highest wisdom of this world know them not, nor can know them;
even as it never could know the children of the true wisdom formerly.

Now, from this Fountain,
do not only issue springs and streams of life to refresh our own hearts;
but testimonies concerning the life which we feel and partake of,
and concerning our travels from the dark land,
through the valley of tears (where he who gave us life was our well),
towards our resting-place.
These, many times, spring up in us for the sakes of others:
of which nature are the things which follow.
For not for my own sake did they spring up in me at this time;
but to signify to others the mercy the Lord hath shown me,
and the way wherein he hath led me,
and what he hath given me to taste of and experience in the way;
which will answer every true palate, every palate that is seasoned with life,
and with the true experience.
And having received them from the Lord for this very end,
to hold them forth to others in love and tenderness of spirit,
my heart is freely given up to him therein; not aiming at any thing thereby,
but his glory singly,
and the good of such souls to whom he shall please to extend favor and show mercy,
in opening the heavenly mystery of life and salvation to them.

I have often said in my heart, Who hath begotten me these?
Who would have said that Sarah should have given children suck!
My wound was deep, and seemed incurable.
But blessed be the Lord, who hath made known to me the physician of value,
for whom no disease is too hard; but he is able to cure every sickness,
and to relieve and rescue all that are captived and oppressed by the devil,
that come unto him and wait upon him,
in the way of his righteous judgments and most tender mercies.
For after all my religion and deep exercises, and inward experiences and knowledge,
I came to such a loss of what I once had, that I sensibly felt I knew not the Lord,
and lay continually groaning and mourning after him,
and deeply afflicted for want of him.
Oh, the pure light, and precious life, and sweet presence of my God, that my soul wanted,
insomuch that my moisture was turned into the drought of summer,
and my bones grown dry and withered!
But at length, the Lord, in his goodness (Oh, blessed forever be his name!),
breathed upon the dry bones, and I felt life enter from him into me,
and the days of deep sorrow and distress were at length forgotten,
because a man-child was at length conceived and brought forth.
And now where is the sackcloth?
Where is the ashes?
Oh, there is beauty in life, instead of the ashes in the state without life;
and the garment of praise, instead of the spirit of heaviness!
Oh glory, glory to the binder up of the bruised and brokenhearted,
to the Redeemer of the captives, to the repairer of the breaches,
to the builder up of the wasted and desolate ones!
Glory to his tender mercy, glory to his grace, glory to his love, glory to his wisdom,
glory to his power, forever and ever, amen

=== SOME EXPERIENCES ADDED

==== I. Concerning the seed of the kingdom

CONCERNING the seed of the kingdom, this I have experienced;
that it consists not in words or notions of the mind, but is an inward thing, an inward,
spiritual substance in the heart, as real inwardly in its kind,
as other seeds are outwardly in their kind: and that being received by faith,
and taking root in man (his heart, his earth, being plowed up and prepared for it),
it groweth up inwardly, and bringeth forth fruit inwardly,
as truly and really as any outward seed doth outwardly.
This seed is known by its contrariety and enmity against the seed of the serpent;
against all the seeds of evil in the hearts of men; it discovering them,
turning the mind from them, and warring against them,
and bruising and overcoming them in all that receive it, and let in its holy nature;
which, as a holy leaven or salt, worketh out that which is unholy and unrighteous,
dark and dead, and seasoneth with light, with life, with grace,
with the holiness and righteousness of truth.

==== II. Concerning the soul`'s food

The soul`'s food is that which nourisheth it,
which is the same with that which giveth it life.
Every word proceeding out of the mouth of God, every motion, every quickening,
every operation of his Spirit, is living, and nourisheth the soul with life,
which receiveth it and feedeth on it.
The spiritual manna, the spiritual water, from the holy well or fountain,
the milk of the word, the flesh and blood of the Son of the living God, his words,
which are spirit and life, nourish up the living birth unto life everlasting.
How comes man to live at first, but by hearing the voice of him that giveth life?
And how comes man to live afterwards, and to increase in life,
but by hearing the same voice still?
"`Incline your ear, and come unto me: hear, and your soul shall live,`" etc. Isa. 55:3.
This I have also experienced to give me life,
to nourish up and strengthen me in life;
even fresh life communicated from the living Fountain; and so my life is not in myself,
not in any thing I can comprehend concerning Christ; but in being joined to him,
in being ingrafted into him the holy root, into him the true olive-tree, into his Spirit;
and so by the sap that springs up into me from him,
my life is maintained and increased in me daily.
Glory to his name forever.

==== III. Concerning God`'s power

Concerning God`'s power, this I have experienced;
that that is it which doth the work in the soul.
It begets to God, it brings out of the land of darkness,
it leads through all entanglements, and preserves in the midst of them all.
It breaks down the old building of sin and iniquity (both inwardly and outwardly,
both in heart, and also in life and conversation), and raiseth the new and holy building.
It makes willing, it makes obedient, it gives to believe, it gives to suffer.
Oh, blessed be the Lord for the day of his power, which is inwardly broken forth!
Oh, what would the poor child do (the poor lambs in the
midst of the wolves inwardly and outwardly),
were it not for the Father`'s hand, the Father`'s arm, the Father`'s power,
which is still with them, and compasseth them about!
Oh, blessed are they that know the ministration of the life inwardly,
the power of life inwardly!
For in life, in the seed of life, is the holy power; which is manifest, appears,
and works, as it gains ground on the creature,
to put forth and exercise in it the virtue and strength
which it daily receiveth from its Father.

==== IV. Concerning Temptations

Concerning temptations, this I have experienced; that the strength and hurt of them,
as to the soul, lies in the soul`'s looking at them.
For the strength of God is revealed in his children against the tempter;
which being patiently waited for, and trusted in, will never fail them.
The least babe, the Lord would not have let in temptation and sin; but watch to that,
and keep joined to that, which will preserve out of temptation and out of sin.
God is faithful, who hath care of all his, and whose promise is to all his;
and as he would have none sin,
so none that diligently wait shall want his power to stand by them,
to preserve out of sin.
"`Look unto me, and be saved, all ye ends of the earth.`" It is universally true.
Look unto me, trust in me; look not at yourselves, trust not in yourselves;
look not at the enemy, fear not the enemy; I will save you from every snare,
every temptation, as your eye is steadfast upon me.
What if the enemy come in like a flood?
If the Spirit of the Lord lift up a standard against him, can he prevail?
What though he cast fiery darts?
What though he beset round about?
Will not the shield of faith quench them all?
Will not the whole armor of God defend and keep safe from them all?
If the enemy be resisted lawfully (that is,
in true faith in that power which is engaged for the soul against him),
doth not the power of the Lord arise and scatter him,
and strengthen and establish the soul in the grace, and in the truth?
Oh! the holy mystery of the heavenly warfare,
and of the working of the pure power against the enemy;
which overcomes all his impurities, and keeps clean from them!
Look not at the enemy; let not in the reasonings of the mind; keep in the patience,
keep in the pure fear, in the holy, living sense: be only what thou art in the seed,
in the new birth, in the life which God hath begotten in thee; then art thou safe,
then art thou in the name of the Lord, which is the strong tower.
The enemy indeed may make a noise about thee with his lusts, with his temptations,
with his floods, with his storms, with his fiery darts;
but he cannot enter thy habitation.
The Spirit of darkness, the prince of darkness, is shut out of the land of the living.
Abide thou there: dwell in the light, and walk in the light, as God is in the light,
and he shall never have power over thee.

==== V. Concerning Prayer

I have experienced prayer to be the breathing of that birth which God begets,
to the Father of life which begat it;
who by his Spirit makes known to it its condition and wants,
and gives a suitable sense of heart, and cries to it.
For as it is not in man to beget himself to God;
no more can he pray to God in his own will or time,
but as God pours out the Spirit of prayer and supplication upon him,
and by his Spirit teacheth and helpeth him to pray as he ought.
"`Because ye are sons, God hath sent forth the Spirit of his Son into your hearts, crying,
Abba, Father.`" I have had a sense of the natural man, and of the spiritual man;
and of the cries and prayers of each: and this I have been taught and learned of God,
that the gospel prayer is the prayer of that birth which
is begotten by the Spirit and power of the gospel;
and which prays in the Spirit, and in the springing of the holy life and power;
whereby it rightly wrestles, and prevails with God,
obtaining the mercies and blessings which it wrestles with him for.
For to this child there is access to God in the faith,
through that holy Spirit of life which makes way for it,
to obtain grace and mercy in the time of need.
And through this Spirit it prays to God,
and prevails with him on the behalf of others also.
For the prayers of the righteous avail much, as it is written.

==== VI. Concerning Justification and Sanctification, some things which it hath pleased the Lord, in his tender mercy, to give me to experience

First, That it is the same Christ, the same Spirit, the same life, the same wisdom,
the same power, the same goodness, love, and mercy, the same water, the same blood,
which both justifies and sanctifies.

Secondly, That justification and sanctification go hand in hand together.
There is none justified, but he that is in measure sanctified:
and there is none sanctified, but he that is in some measure justified.
For God justifieth by a rule (by the new covenant, and according to the law thereof);
and men receive and partake of justification, according as they are brought into,
and keep within, the compass of that rule.
For God acted of old toward and justified the children
of the old covenant according to the law thereof;
and the children of the new covenant are justified, and partake of justification,
according to the law thereof.

Thirdly, That justification and sanctification are both of and through the grace.
It is so in the beginning, and it is so all along.
"`By grace ye are saved,`" saith the apostle.
The whole work of salvation is begun and carried on through grace.
It is through that, God visits and reaches to the soul,
with his quickening virtue and power.
He regenerates also thereby.
Through that he justifies; through that he sanctifies, etc.
So that as the work goes on, grace, grace, is to be cried to him that does the work,
from his very laying the foundation, and fastening the soul thereupon,
to his very laying on of the top stone.

Fourthly, Though justification and sanctification be of God`'s grace and mercy in Christ;
yet this doth not exclude faith: but they are also through faith, and not without it.
God doth not justify man in the unbelieving state, in the dead state,
in his abiding there; but in the coming out of it,
in the repenting and turning from the dead works to the living God,
and in believing in him: and so he also sanctifies him.

Fifthly, Faith and obedience are of the same nature, and always go together.
So that wherever there is faith, there is obedience likewise;
and wherever there is obedience, there is faith.
Obedience flows from faith, and cannot be without it;
for the very nature and virtue of faith is in it.
And faith is obedience.
For this is the command of God,
that the soul believe on him (and in his appearances) whom he hath sent to save;
and this believing is obedience unto him that commands it.
And this faith, and this obedience, is holy and just in God`'s sight;
and through it (but not without it) the soul is both justified and sanctified.

Sixthly, That the works of faith, the works of the new life,
are not the works of the law, the works of the old covenant;
nor are excluded justification, as the works of the old covenant are.
For I have found the Lord, who hath condemned and excluded all my doings,
which ever I have been able to do of myself,
still justify and accept what his Spirit and holy power hath done in me.
They are not of the same nature in themselves;
nor are they so accounted of in the eye of the Lord.
For the Lord distinguisheth between root and root: and what springeth from the holy root,
he justifieth as holy; and what ariseth from the unholy root, he condemneth as unholy.

Seventhly, That by the law of faith all boasting is excluded,
in the whole work both of justification and sanctification.
What is the law of faith?
Is not this its law, to fetch all from the Son, to do all in the Son?
to quit self, and its own ability, and to perform all in the newness of the Spirit,
in the ability which is of God, given and continued, in and through his grace and mercy,
to the soul in the Lord Jesus Christ?
All the veins of life, all the streams of the new covenant run here.
Here is no boasting of the creature; here can be no boasting:
for all its ability and strength is shut out; and that which is given of God to it,
is all and doth all.
Yet every Jew here hath praise of God.
His faith is commended, his love is commended, his faithfulness is commended,
his zeal for the Lord, his obedience to the Lord, his patience in suffering,
is commended, etc.
But the praise and honour of all redounds not to his flesh,
but to the Spirit and grace of God in him.
So that here flesh is laid low, and kept in the dust forever,
and God alone exalted in this day of his pure power in the heart.
He that truly believeth, entereth into rest.
How into rest?
From what doth he rest?
Why, from his own works, from the works of the flesh; yea,
from the works of the old covenant; from the works that arise from his own ability,
from the works wherein he can never be justified with the gospel justification.
But doth he cease from the works of faith?
Doth he cease from the labor of love?
Doth he cease from obedience to any thing that God requires?
Nay: then surely he rather beginneth to work and labor in the vineyard;
and his labor is not in vain in the Lord.

==== VII. Concerning Faith

Several things I have experienced, both concerning the nature, virtue,
and operations of it;
some whereof (as I feel them spring up livingly in my heart) I may mention at this time.

First, This I have often experienced;
that it is a hard thing truly and rightly to believe.
It is an easy matter to believe notions concerning God, and concerning Christ:
but to believe in God, to believe in Christ, to believe in him that raised up Jesus,
to believe in the light, life, and power, which flows from Jesus; this indeed is hard,
by reason of the great darkness and ignorance which man is fallen into through transgression.

Secondly, I have experienced this also; that faith is God`'s gift,
and that it flows from the power of his life.
There is first a quickening, first a touching of the heart, by the holy,
pure power of the Lord; and when a man is touched and quickened,
then in and by and through that virtue which flows into him,
he can believe in that which toucheth and quickeneth him.

Thirdly, That faith never stands in a man`'s own power,
but always in the virtue and power of the life of the Son.
So that he that will believe aright,
must wait to feel the life of the Son revealed in him, and faith flowing therefrom.
For the true belief springs from the life of the holy root;
and from the flowing up and springing up of that life,
faith receives its nourishment and daily virtue.

Fourthly, I have observed this in my travels; that the earthly wisdom,
and notions therefrom got into the mind, and held in the mind out of the sense of life,
are a great let to faith.
For these strengthen and nourish that in man, which is to be weakened and die; that life,
and the birth of life, may be all in the heart.
Man is to die; man is to be ceased from; his understanding, his wisdom,
is to be brought to nought.
But after it hath had a stroke and wound from God`'s Holy
Spirit and power (even the very wound which tends to death),
yet it will be getting life again (getting its deadly wound healed),
and nourishing its life by those very notions, which came from that life and power,
which in measure slew it.
And thus the Jew outward hath his life in the outwardness of knowledge,
in the outwardness of the law, in the letter which killeth:
for the relation and outward knowledge of things killeth and deadeneth more and more,
unless man come into the inward life and virtue, and daily feel them quickened there.
"`If ye live in the Spirit, walk in the Spirit,`" said the apostle.
A man cannot live in an outwardness of knowledge
concerning the Spirit and power of the endless life;
but he that would truly live, must live in the Spirit itself;
and he that would rightly walk on in his way,
must walk in that Spirit wherein he received life,
and wherein he that abideth lives before the Lord.

Fifthly, This I have also observed; that all notional faith,
wherein is not the living virtue (as concerning Christ, his sufferings, death,
resurrection, ascension, intercession; and concerning justification by him,
etc.) the enemy will let the soul alone with, and let him enjoy peace in;
but his war is desperately against the true faith, against faith in the true power,
against faith in the light of life.
Oh, how many sore and sharp assaults doth he make against
the faith which receives its virtue from God,
and causeth the soul to live to God!
And how sore is it with the soul, when faith is weak,
and the enemy comes on against it with the strength of his assaults and temptations.
"`Lord increase our faith,`" said the sensible disciples.

Sixthly, It is a precious thing to feel faith quickened by God, and helped by God,
against the enemy.
For then the enemy cannot prevail against the soul; but the soul,
through the virtue and power of life, prevails over the enemy in the faith.
And this is the great work of a Christian, not only to wrestle and fight,
but to learn so to wrestle, and so to fight, as to overcome.

Seventhly, That in the pure fear (not that which is taught by the precepts of men,
but which God puts into the heart) faith hath its strength, and exercises its strength.
Oh! who knows the preciousness of this fear!
The power of faith, the power of life, the power of salvation,
and everlasting preservation is revealed in it.
Therefore, saith the Lord,
when he speaketh of providing for his children in the new covenant,
that they shall abide with him forever, and not depart any more from him,
as the children of the old covenant did; "`I will put my fear in their hearts,
and they shall not depart from me.`" And when the angel preached the everlasting gospel,
how did he preach it?
"`Fear God, and give glory to him, for the hour of his judgments is come,`" etc.
Rev. 14. When the pure fear is felt, when that which is contrary to God is judged;
then the gospel is known, and the work thereof experienced in the heart.
And how easy is it, when the pure fear is felt, to distrust and deny one`'s self,
and trust in the Lord!
Oh, how weak are the reasonings and imaginations then,
and how strong is the power which scatters them, and lifts up the head over them!

Now it concerns every one deeply to consider, of what nature his faith is,
and what virtue is in it,
and what it can do in and through the power of the Lord for him;
how it fetcheth in the true, living nourishment every day, how it delivers the soul,
and gives it victory over that which faith was appointed to deliver from.
For he, who through the faith overcometh that which is contrary to God, shall inherit;
and he that fights the good fight of faith, shall overcome:
but he that overcomes not his enemies, which stand in his way,
shall be sure to be hindered by them from attaining to his journey`'s end.

==== VIII. Concerning Obedience, some experiences also

First, True obedience, gospel obedience, flows from life, flows from the living faith.
If I could obey in all things that God requires of me, yet that would not satisfy me,
unless I felt my obedience flow from the birth of his life in me.
"`My Father doth all in me,`" saith Christ.
This was Christ`'s comfort.
And to feel Christ do all in the soul,
is the comfort of every one that truly believes in him.

Secondly, True obedience, gospel obedience, is natural to the birth which is born of God.
It is unnatural to the flesh, to man`'s wisdom, to deny himself, and take up the cross;
but it is natural to the birth which is born of God`'s Spirit.
"`That which is born of the Spirit,
is Spirit;`" and it is natural to it to be conversant in, and exercised about,
that which is spiritual.

Thirdly, That honoring and pleasing, and answering the will of the Lord,
is the proper aim of the truly obedient.
Oh, how do they delight to do the will of God! "`I have meat,`" saith Christ,
"`that ye know not of.`" To do the will was his meat and drink:
and it is meat and drink to all that are of his nature and Spirit.
If I should never have any other reward, but the pleasure of obedience;
yet I could not but say and testify, that in answering the law of the pure life,
in keeping the holy statutes and commandments of God`'s Spirit, there is a great reward.
But yet there is a crown also,
and a reaping after this life of everything that is sown to the Spirit:
and the crown is weighty and everlastingly glorious.

Fourthly, Gospel obedience is exceeding necessary in and to the gospel state.
Mark: The lamb is the leader: and can any be saved by him, but they that follow him?
When Christ calls out of the world, must not the soul come to him, who is the Shepherd?
And must not the sheep daily learn to know his voice, and follow him;
even till they come to be acquainted with every moving, drawing,
and leading of his Spirit; and so come to follow the Lamb whithersoever he goes?
Mark: what a weight Christ layeth upon doing.
"`If ye know these things,
happy are ye if ye do them.`" Why then the disciple cannot come to happiness,
but in the doing, in the obeying of the will of Christ, his Lord and Master.
And "`he that heareth these sayings of mine, and doeth them,
I will liken him to a wise man, that built his house upon a rock.`" But the believer,
without doing the will, is the foolish builder, whose building will not stand.
Again, saith Christ, "`As the Father hath loved me, so have I loved you;
continue ye in my love.
If ye keep my commandments, ye shall abide in my love;
even as I have kept my Father`'s commandments, and abide in his love.`" The disciples,
whom he most dearly loved, must keep his commandments, if they will continue in his love.
And his apostles taught the same, even the working out of the salvation,
and the purifying of the heart, through the obedience of the truth.
For mark: there is a covenant of life, a way of life; and how can life be reaped,
how can the work of life go on, but in subjection and obedience thereto?

Oh! blessed is he, who meets with the power of life, which enables to obey;
and who is obedient and subject to that power.
For he that truly believes in Christ, is turned by him to his light,
and to the power of his Father; and the peace, growth, joy, blessedness,
etc. is witnessed in subjection thereto.

==== IX. Concerning the cross of Christ

This I have experienced concerning the cross of our Lord Jesus Christ;
that it is an inward and spiritual thing,
producing inward and spiritual effects in the mind; and that this is it,
even that which slays the enmity in the mind, and crucifies to the world,
and the affections thereof.
"`God forbid,`" said the apostle, "`that I should glory,
save in the cross of our Lord Jesus Christ, whereby the world is crucified unto me,
and I unto the world.`" Now mark: that which is contrary to the world,
and crucifies to the world, that is the cross.
The cross hath this power, and nothing else; and so there is nothing else to glory in.
"`The flesh lusteth against the Spirit, and the Spirit against the flesh;
and these are contrary one to the other.`" Mind, here is the cross:
the Spirit which is contrary to the flesh, which mortifies the flesh,
through the obedience whereof the flesh is crucified.
"`If ye, through the Spirit, mortify the deeds of the body,
ye shall live.`" Whatsoever is of and in the Spirit, is contrary to the flesh.
The light of the Spirit is contrary to the darkness of the flesh.
The holiness of the Spirit is contrary to the unholiness of the corrupt heart.
The life of the Spirit is contrary to the life (or rather death) that is in sin.
The power of the Spirit is contrary to the power that is in Satan, and his kingdom.
The wisdom of God is contrary, and a foolish thing, to the wisdom of man.
Yea, the new creature, which springs from God`'s Holy Spirit,
is contrary and death to the old.
Now he that comes hither, out of his own wisdom, out of his own will,
out of his own thoughts, out of his own reasonings;
and comes to a discerning of God`'s Spirit,
and to the feeling of his begetting of life in the heart,
and his stirrings and movings in the life which he hath begotten; and waits here,
and receives counsel here; he is taught to deny himself, and to join to and take up that,
by which Christ daily crosseth and subdueth in him that which is contrary to God.

And here is the fight of faith, and the good travel under the cross,
whereby the holy journey is gone,
and the enemies (which rise up to oppose in the way) vanquished and overcome.
For here is the power revealed; the preserving power, the leading power,
the conquering power of him who rideth on conquering and
to conquer his spiritual enemies in the hearts of his children,
who know his voice, and are subject to him; who daily denying themselves,
and taking up his cross, follow him.
Woe is to them that are at ease in Zion, under any thing that is contrary to God;
but blessings are upon them whose dwelling is under the cross,
and who know no ease but what it allows.
It will make truth, life, holiness, righteousness, faith, obedience, meekness, patience,
love, separation from sin, communion with the Lord, and all the fruits of the Spirit,
as natural to them in the renewed state, as ever sin was in the corrupt state.
And in that state they shall be able to say with Paul;
who once complained of his captivity, and that he did what he hated;
yet after he had known the power of the cross, and was crucified with Christ,
he could then do nothing against the truth, but for the truth; yea,
then being a conqueror, having overcome the enemies which stood in his way,
he could do all things through Christ that strengthened him.
The cause of so many complaints and bowings down of the head,
and going mourning because of the prevailings of the enemy, through temptations, sin,
and corruption,
is because the cross of Christ which is the power of God (which is his
ordinance against the strength of the enemy) is either not known,
or not taken up.
And this is the reason that many that make a fair show for a while,
yet afterward come to nothing (but are like untimely figs,
or like corn upon the house-tops, which hastily springeth up,
but soon withereth) because they either never rightly learn, or keep not to the cross.
For that alone hath power from God to bring down
and keep down that which is contrary to him.
So that from under the cross of Christ,
there is no witnessing salvation or preservation from the Lord;
but out of the limits of the cross,
the enemy hath power to recover and bring back under his dominion again.
And whosoever in his travels leaves the cross behind him, does draw back unto perdition,
and not travel on, in the living faith, and newness of obedience,
towards the salvation of the soul.

==== X. Concerning the Mystery of Life, and the Mystery of the Fellowship which is therein.

God is hid from man, as he lies in his sinful and fallen state;
and no man can find or know him,
but as he pleaseth to reveal himself by his own blessed Spirit.
And Christ, being God`'s image, there is no knowing or confessing him,
or right calling him Lord, but in and by the same Spirit. 1 Cor. 12:3.
When he appeared in the days of his flesh,
flesh and blood could not reveal him, but only the Father.
And he is the same today as he was yesterday.
He is not to be known now, but in the same Spirit; in his own grace and truth,
in a measure of his own life.
The dead cannot know him; they only know him, who are his sheep,
who are quickened and made alive by him.
And this life is a mystery: none can understand it, but they that partake of it.
Can a man that is naturally dead know what the life of nature means?
No more can a man that is spiritually dead know what the life of the Spirit means.
The natural man may get the words that came from life, and cry them up,
and speak great words of the fame of wisdom and of her children;
but the thing itself is hid from them all.
Oh! it is a strait gate at which the birth enters, at which none else can enter.
The wise and prudent knowers and searchers after the flesh (and of the Scriptures,
as they can put meanings upon them and comprehend them) are shut out in every age;
but there is a babe born of naked truth (born of the pure simplicity) admitted by God,
while men disdain and despise it.

And the fellowship of the saints is in the life, and in the light, which is this mystery.
The fellowship is not outward, but inward.
All they that meet together in the outward place, are not in the fellowship, or worship;
but only they that meet together in the inward life and Spirit.
"`They that worship the Father, must worship him in Spirit and truth.`" Look,
there is the worship, there are the worshippers; they that are in the Spirit,
in the truth; they that meet in the Spirit, in the truth,
they meet together in the one spiritual place, as I may call it.
And so we own no man after the flesh, no man according to the appearance;
but in the righteous judgment of the Spirit, those only who are of the Spirit.
Indeed we are tender where there is the least beginning of the work of God in any heart;
yea, where there is but so much as a conviction of the understanding;
but men are not presently of us, who own our principle in words or outward appearance,
but only such as are inwardly changed thereby in the heart.
It is true, persons may walk among us, and afterwards go out from us,
who were never of us (as it was in the apostles`'s days),
that were never in the fellowship of life with us,
whom we could never own in the sight of the Lord, as being born of him;
though we were willing to wait and watch for their good,
that they might come to witness the true birth.
Now from such come the offences,
even from the falling off of such as never were truly ingrafted,
and also from the slips of such who are not watchful to that which preserves.
And woe is to the world, because of the offences which cannot but come.
For they which are to be approved in the sight of the Lord,
must not somewhat or other happen to make them manifest?
And when they are made manifest, the world`'s eye is offended,
and is apt to think hardly of and reproach the truth itself, because of them.
Blessed is the eye which sees into the mystery, into the life itself,
where there is no offence.
Truth is one and the same forever.

==== XI. Concerning judging according to the appearance, and judging righteous judgment.

Judge not according to the appearance, said Christ, but judge righteous judgment.
John 7:24

What is it to judge according to the appearance?
and what is it to judge righteous judgment?
I shall speak what I have experienced, having been deeply exercised about this thing.
Mark then:

The holy Spirit of life breatheth upon the heart; and,
by his breathing and working there, he quickens and begets life. John 3:8.
And that which is begotten and born of him is begotten and born in his nature, and so is of the same nature with him, as verse 6.
of that chapter.

Now, to that which is born of the Spirit, the Spirit is the leader, the preserver,
the supporter, the comforter, the daily quickener.
He can do nothing without the Spirit,
without the present life and power of him that begat him;
so that all the judgment which the birth of life hath is
from and of and in the holy Spirit of the Father.

And here is true judgment, both concerning righteousness,
and against all unrighteousness; so that keep to the life, keep to the Spirit,
keep to the birth, keep to the power,
then is the wisdom and righteous judgment of God revealed: but any that go out of this,
and measure without this, they measure in the unrighteousness;
and though they search the Scriptures,
and think in themselves they measure from the Scriptures, yet they are mistaken,
and measure but from their own knowledge and apprehensions upon the Scriptures,
as the Scribes and Pharisees did, when they seemed to conclude,
upon searching the Scriptures, that Christ could not be the Messiah. John 7:52.
"`Search and look,
(said they) for out of Galilee ariseth no prophet.`" How then can this Galilean be he?
See by the Scriptures if this can be the Christ.

It is said of Christ, "`He shall not judge after the sight of his eyes,
nor reprove after the hearing of his ears, but with righteousness shall he judge,`" etc. Isa. 11:3-4.
Christ judged righteous judgment.
How came he to judge so?
Why, he judged in and with the Spirit.
He kept to the Spirit`'s judgment.
The Spirit of the Lord rested upon him,
and made him quick of understanding in the fear of the Lord,
ver. 2-3. And no man can judge aright concerning the things of God,
but in and by the same Spirit.
How shall I know whether my duties be right, my prayers right, my ways right,
my worship right, my faith right, my hope of the right kind,
my knowledge and understanding of the Scriptures right, etc.? Why,
there is none but one can determine.
He who begetteth life knows whether that which is in thee be from his life;
and whether that which thou offerest to him be truly living or no:
and when the Lord separates the living from the dead,
what will remain in many that make great professions at this day?

I would have no man mistaken about these things; I know many are deeply mistaken,
as their own hearts will one day acknowledge, when the Lord shall make manifest to them,
how they have called evil good, and good evil; and put darkness for light,
and light for darkness.
Indeed it is just as it was in the days of Christ`'s
appearing outwardly in a body of flesh.
The same life, the same Spirit, is denied now as was then.
Then the Jews cried up Christ to come; but they then spiritually saw him not.
They saw the flesh, or outward form, but they saw not him who dwelt in that flesh.
And though the world of Christians now acknowledge Christ is come and did appear,
yet neither do they know him who did appear, but deny his life, his Spirit, his virtue,
his power,
which is revealed in this day of his love and goodness
to the eye of the children of the true wisdom.
Oh! let not flesh judge: be silent, O all flesh, before the Lord, and cease judging,
for he is arisen to judge.
He is Judge in the midst of his people, and he will judge the heathen also.

And every one bring this near.
Wait to feel flesh judged in thee, and brought down in thee,
that it may not judge in thee; but Spirit and life may be exalted,
and sit upon the throne in thy heart.
And when life is exalted, and doth begin to judge, oh,
take heed of hearkening to the flesh, or letting in the judgment of flesh afterwards,
lest the Spirit be grieved and quenched!
For the wisdom of the flesh is near,
and will be striving to get in and recover its seat again;
and if the watch be not singly kept to God`'s Holy Spirit,
somewhat else will be judging in thee,
which will judge according to the appearance of things to thy mind,
and so thou wilt miss of the true and righteous judgment of God`'s Spirit.

==== XII. A question answered about knowing God`'s Spirit

Question.
How shall I know God`'s Spirit?
How shall I know the motions thereof?
How may I know whether the faith and hope in my heart be from him?
whether my prayers and desires arise thence, etc.?

Answer.
No man of himself, or by any way he of himself can take, can know God`'s Spirit.
There must first be a capacity given before any man can know the Spirit of the Lord;
his life, his power, must first be felt, and somewhat quickened, somewhat formed by him,
somewhat begotten of him, which is Spirit, and this can know him.
Now, man in this may know him, but out of this can never know him.
Therefore this is the great skill and diligence and wisdom of a Christian,
to keep to this, to wait for this, to have his eye toward the pure spring of wisdom,
that when it springs, he may discern and receive it;
and when that which is of a contrary nature springs,
he may discern it under all its deceitful appearances, and turn from it.
For out of the heart are the issues both of life and death.
There is all manner of deceivableness of unrighteousness in the unrighteous nature,
in the unrighteous spirit; and if the watch be not diligently kept,
it is easy to be deceived at any time; but the true seed, the holy seed, the living seed,
the elect seed, the immortal seed, is never deceived.
Oh! blessed are they who have their eyes opened and kept open in it,
to discern the mystery of godliness and the mystery of iniquity,
that they may be preserved safe in the one, out of the reach of the other!XIII.
Some queries concerning the seed of the kingdom,
in which the kingdom itself is contained (as the nature
and substance of things are contained in the seed thereof),
and out of which it springeth up and ariseth in the heart

Query 1. What is that seed which is spoken of, 1 John 3:9.
which remaineth in those that are born of God,
and preserveth out of sin those that are led by it and comprehended in it?
Is it not the seed of the kingdom?

Query 2. Do not the natural herbs and flowers, the natural plants and trees,
grow from a natural seed?
Do not the spiritual plants, the spiritual trees, the trees of righteousness,
grow from the seed of righteousness?

Query 3. Was it not the great doctrine of Christ to preach the kingdom?
And how did he preach it?
Did he not preach it as a seed, as a grain of mustard-seed?
and did he not liken this spiritual seed to leaven, to a precious pearl,
to treasure hid in a field, to a piece of silver lost, etc.? Oh,
how happy is he who knows and enjoys the thing itself which Christ preached!
All the prophets prophesied concerning him; and when he came, this was his doctrine,
that men should mind this, look after this, purchase this, possess this,
feel this planted and grow up in them,
and themselves ingrafted into and growing up in it.

Query 4. Can any man be born of God, and not born of this seed?
Can any man be born of this seed, and not born of God?

Query 5. How doth grace and truth come by Jesus Christ?
Doth it not grow up from this seed?
Can it grow up any other way in any heart?

Query 6. Is not salvation felt and witnessed in every heart (of those that are
in any measure redeemed) as this seed grows up and overshadows them?
Was not this the salvation ready to be revealed in the last time, 1 Pet. 1:10.
whereof the apostle Peter himself was made a partaker?
chap.
5:10. In the law were the shadows of good things to come;
but in the gospel the substance, the seed itself, is revealed.

Query 7. Is it not the right beginning in religion to begin in the Spirit?
and can any begin in the Spirit, but he that begins in and with the seed of the kingdom?

Query 8. Is it not the main and chief thing in religion to know this seed,
and to feel this seed, to be joined to this seed, and abide in this seed?

Query 9. Is not all that flows from this seed true and certain?
Is not the knowledge certain here?
the faith here?
the love here?
the peace here?
the joy here?
the righteousness here?
From this root, can there grow or shoot forth any thing but that which is true?
Oh! every breathing here is from pure life, and precious in the eye of the Father.
Is there any certainty elsewhere?
Oh! when the Lord appears,
will he not disown all the religion and worship which is not of this growth?

Query 10. But some may say, How may I know this seed, and how may I be joined to it?

Answer.
In the quickening life mayest thou know it, and no where else.
Didst thou ever feel that which quickened thy heart towards the Lord?
Therein and thereby, at that time, thou mayest feel an eye and heart opened,
which can truly see and know somewhat of God;
and keeping thy eye to the quickening power of God, as that stirs, moves, and operates,
in thee and upon thee, thou mayest know again and know more.

Therefore eye the power which quickens,
and eye the seed which it reveals and raiseth in thee,
and wait to feel the power subjecting thee to the seed, that thou mayest come under it,
and it may come over thee,
and press down in thee all that is contrary to its pure nature.

And as thou comest hither, thou wilt find that which death hath no power over; and,
as thou abidest there, thou shalt find it to have no power over thee.
For, of a truth, in the holy covenant of life and peace,
death never had nor can have power; but he who abideth in him who is the covenant,
who is the Shepherd, who is the love, who is the wisdom and power of God,
witnesseth there a sure defence and strong tower,
where salvation is for a wall and bulwark against the enemy.

There are many sorts of talkers concerning the thing,
but there are few travellers into it; but he alone who is a true traveller into it,
and takes up his rest there,
certainly knows and can truly witness what is to be found there.
And this is the reason that so many (who seem great
and experienced knowers) cannot receive our testimony,
because they know neither the seed nor its voice,
concerning which and whereby we testify.
But wisdom is justified of her children; and they that know the voice of the Shepherd,
know his present appearance in this our day,
which is contrary to the wisdom and knowledge of all other seeds and births whatsoever.
"`He that hath an ear to hear, let him hear;`" but he that hath not the true ear,
cannot hear the true testimony, though it should ever so often be declared unto him.
But blessed is he that knows and stumbles not at the appearances
of the seed and power of life in his own heart,
but is turned from the darkness to the light there,
and from the power of Satan to the manifestation of God`'s Spirit there.
For the end of words (even of Christ`'s own directions in the days of his flesh)
is to turn men to the holy life and power from whence the words came;
and thither man is to travel, and therein to centre, waiting on the Lord,
in the way of his judgments and tender mercies,
to witness a translation from darkness to light,
and from the kingdom of Satan into the kingdom of the dear Son;
which kingdom is at first but as a grain of mustard-seed,
and must be so known and so received.

And now let every serious heart examine concerning himself.
Dost thou know the kingdom?
Is the seed grown in thee?
doth it overspread thee?
Art thou in it as in a kingdom?
dost thou feel it overshadowing thee?
art thou in unity with it?
doth it speak peace to thee from the Lord?
Is the wall of partition broken down in thee?
Is there of twain made one new man?
Dost thou feel that which is contrary to Christ subdued in thee by his power?
and his holy nature, life, and Spirit, reigning over it?
Canst thou read that Scripture sensibly and experimentally,
"`if ye through the Spirit mortify the deeds of the body, ye shall live`"?

Ah, how miserably do men talk of Christ, the power of God,
and miss of the effect and work of his power in them!

Faith is a powerful thing, it gives victory (true faith gives victory),
it scatters that which stands between, and gives real access to God,
and lets in his pure, fresh, living virtue, upon the heart.

Love is a powerful thing, it constrains to obedience:
and the heart that is circumcised to love the Lord God,
Oh! how doth life flow from him into it!

Oh! away with empty notions, and come to the ministration of the Spirit,
where the knowledge is living, the faith victorious, the love pure and undefiled,
the worship truly spiritual, even flowing from, and comprehended in,
the life and virtue of the Spirit.
Oh that all that truly breathe after the Lord might be gathered hither, found here,
and dwell here!
Amen.

=== POSTSCRIPT TO THE EXPERIENCES

PERSONS that have had some true touches of life, and true breathings after the Lord,
yet not having their eye fixed rightly upon him, nor discerning from whence those come,
may easily lose the true sense of life,
and another birth of another nature spring up in them instead thereof.
This was it we generally wanted in the day of our former profession,
even the discerning of that, and fixing upon that, which begat life in us;
through want whereof, many of the most tender-hearted came to a loss;
whom the Lord at length showed mercy to, manifesting to them the light of their eyes,
and the stay of their souls.
Now, to all that have been gathered hither by the Lord, life hath been renewed,
and their former experiences (of the Lord and his goodness
to them in the Lord Jesus Christ) restored again with advantage.
And here they sensibly see, and daily experience, that nothing is of their own works,
but all of grace and mercy in and through Christ,
in whom they are created unto good works,
which God before ordained that we should walk in them.
And here the glory is revealed; the glory of life, the glory of peace with the Lord,
the glory of righteousness in and through his Son,
the glory of victory over the soul`'s enemies, and of leading captivity captive,
and treading upon the necks of kings, even of mighty lusts,
which mightily prevailed over and oppressed the soul,
before the Captain of our salvation appeared in the power and authority of his own Spirit.
But blessed be the Lord, there is not only this glory revealed,
but there is a defence over the glory;
for there is that revealed which is able to defend it, and doth defend it,
in the hearts of many,
and in the living assemblies which have been gathered by God`'s holy power;
which holy power (which gathered) daily quickens and overshadows, and is a rock unto,
and will be so forever, even to all that abide with him in his holy covenant;
but out of the limits of that into which God gathers,
and wherein and whereby he preserves, there is no defence to any.
The cursed thing, the unclean thing, the earthly spirit, the earthly mind and wisdom,
the Lord hath excluded, and it is to be excluded out of his camp forevermore,
that the inward Israel may be kept holy to the Lord,
and may serve and worship the Lord in the beauty of the inward holiness,
as the outward Israel was outwardly, to be, and to do,
in that outward ministration of the shadows of the gospel state.

=== Some scriptures very sweet, and necessary to be experienced in the gospel state

"`This is life eternal, that they might know thee the only true God,
and Jesus Christ whom thou hast sent.`" John 17:3. There
is a knowledge of God and Christ which is life eternal;
and there is a knowledge of them (or at least that
which men call so) which is not life eternal.
The knowledge which is life eternal is that knowledge which God gives to his own birth;
even the spiritual knowledge which God gives to those which are born of the Spirit;
which is the knowledge of the mystery of God, and of Christ in the mystery,
inwardly appearing, and working in the heart against the mystery of sin and death,
Oh! precious is the birth to which God gives this knowledge,
and precious is the knowledge which he giveth to it.
The knowledge (or that which men call knowledge) which is not life eternal
is that knowledge which man can get and comprehend from without,
of himself,
without the enlightenings and quickenings of God`'s holy
Spirit and power inwardly felt and operating in the heart.

"`No man can say that Jesus is the Lord,
but by the Holy Ghost.`" 1 Cor. 12:3. It is precious to witness that confessing
and acknowledging Jesus to be the Lord which is by the Holy Ghost.
For only they that are governed by the Holy Ghost can so confess him.
The devil did confess Jesus to be the Holy One, the Son of the living God, etc.,
and many now confess Jesus to be the Lord, in the same spirit,
being alienated from the life of God, and having no true sense or understanding of that.
But there is a confession which cannot arise but from God`'s Spirit,
and from the knowledge, sense, and understanding which he gives;
blessed are they that experience that.

"`It is written in the prophets, and they shall be all taught of God.
Every man therefore that hath heard, and hath learned of the Father,
cometh unto me.`" John 6:45. Ah! blessed is he that can in true understanding say,
The Lord hath made good this promise to me! he is become my teacher.
I have heard his voice, as truly and certainly, inwardly in my heart,
as ever I heard the voice of Satan there.
He hath revealed his Son, his pure, holy, living child Jesus in me.
He hath drawn me to his Son; he hath taught me to come to his Son:
and indeed so soon as ever I heard and learned of the Father,
I could not but come to the Son, and receive the Son, and give up myself to him;
and he hath received me, and daily preserveth me from death,
and the sting and power thereof, and giveth unto me eternal life.

"`He that hath the Son, hath life; and he that hath not the Son,
hath not life.`" 1 John 5:12. Ah,
this is abundantly experienced! blessed be the name of the Lord!
Many who had not life, while they had not the Son,
but mourned and lamented deeply after him (the Spirit of the Lord being grieved in them,
and his life not possessed by them), the Father revealing his Son in them,
and giving him to them, and they enjoying and possessing him,
feel that they are daily in the enjoyment and possession of pure and fresh life in him.

"`My flesh is meat indeed, and my blood is drink indeed.
He that eateth my flesh, and drinketh my blood, dwelleth in me,
and I in him.`" John 6:55-56. We are of his flesh, and of his bone,
said they that did eat his flesh, and drink his blood.
They that eat Christ, the one bread,
are by that food made partakers of his divine nature,
and become one bread (for we being many, are one bread, as said the apostle);
so that now they are no longer darkness, but light in the Lord.
Oh, the pure flesh and blood of the immaculate Lamb!
Oh, the incorruptible food which gives life to the soul!
Oh, the living word!
Oh, the milk of this word, the milk of the heavenly breast,
which nourisheth the babes! but the bread, the flesh, the blood, is stronger nourishment.
Oh, how brightly might this be opened in the demonstration of life,
to the spiritual ear and understanding! but the carnal-minded are thick and gross,
being drowned in their own apprehensions and sense of the letter,
but having no sense of the mystery,
what it is mystically to eat and drink the flesh and blood of Christ (of him who is life,
and gives life), and to dwell together with him in the one Spirit, light, life,
and power eternal.

"`For with thee is the fountain of life;
in thy light shall we see light.`" Ps. 36:9. Oh,
blessed are they that can experimentally speak thus, who know the fountain of life,
and dwell there, where light shines more and more!

"`Ho, every one that thirsteth, come ye to the waters; and he that hath no money, come ye,
buy and eat: yea come, buy wine and milk without money, and without price.
Wherefore do ye spend money for that which is not bread?
and your labor for that which satisfieth not?
hearken diligently unto me, and eat ye that which is good,
and let your soul delight itself in fatness.
Incline your ear, and come unto me; hear, and your soul shall live;
and I will make an everlasting covenant with you,
even the sure mercies of David.`" Isaiah 55:1-3. Here is happiness, true happiness,
full happiness!
He that experiences this one portion of Scripture is happy.
He knows the true thirst after the true waters,
and comes to the waters which he thirsts after, and knows how to buy,
and hath bought the wine and milk which is to be had at the waters (Oh,
who knows what this buying is! this is beyond all
talk and outward profession concerning the thing,
concerning the precious pearl; this is the real,
hearty trafficking of the wise merchant for it).
And then to hearken diligently, and eat that which is good,
and to have the soul delight itself in the fatness of God`'s house,
in the riches and fatness of his goodness and mercy in Christ Jesus;
and not only to taste of mercy, but to witness it sure in the everlasting covenant,
that God will never be wroth with me more, never be a stranger to me more,
never depart from me more, nor suffer me to depart from him;
but preserve me pure and chaste to him, through his love shed abroad in my heart,
and his holy fear, which constrains me to abide with him, and to keep his commandments.

"`But whosoever drinketh of the water that I shall give him, shall never thirst:
but the water that I shall give him,
shall be in him a well of water springing up into everlasting
life.`" John 4:14. Is not this a universal promise,
to be made good to every one that drinks of the water of life,
of the water that Christ gives?
Did not Christ promise it should be a well?
a springing well?
The fountain is of a springing nature: and is not every drop of the same nature?
of a living nature?
of a springing nature?
He that rightly drinks doth he not receive a well?
Oh, the water which Christ giveth! doth it not become a well in the true disciple,
in the living disciple,
out of which well the water is still springing and
flowing to nourish up with life and unto life,
even with life of an everlasting nature, and unto life everlasting?
Oh, the pure glory that is revealed in the gospel dispensation!
why is it so hid from men`'s eyes,
who profess themselves to know the Lord Jesus Christ, and to be his disciples?

"`For the life was manifested, and we have seen it; and bear witness,
and show unto you that eternal life which was with the Father,
and was manifested unto us.
That which we have seen and heard, declare we unto you,
that ye also may have fellowship with us; and truly our fellowship is with the Father,
and with his Son Jesus Christ.`" 1 John 1-3. This
is precious to experience the life inwardly manifested,
and to come out of death inwardly felt, into life inwardly manifested,
and so to come into the holy fellowship with the Father and Son,
and with the saints in light; for he that comes out of the darkness into the light,
comes out of the fellowship of the dead into the fellowship of the living.

"`Come unto me all ye that labor and are heavy laden, and I will give you rest.
Take my yoke upon you, and learn of me, for I am meek and lowly in heart:
and ye shall find rest unto your souls.
For my yoke is easy,
and my burden is light.`" Matt. 11:28-30. This invitation
of Christ was to be fulfilled in the hearts of his disciples;
and it is precious inwardly to witness it effectually in the heart,
as really as ever it was spoken by him.
To be able to say, in the evidence and demonstration of his Spirit: It is true,
I did labor, I was heavy laden, none could ease or help me, till he called,
till he knocked at the door of my heart, and till I came to him, and received him in;
and he hath made good his word to my soul;
he hath given me rest from my labors and heavy loads.
He hath laid his yoke upon me, and I have took it and borne it,
and have learned of him to be meek and lowly in heart like him,
and I have found rest to my soul.
And now I shall never complain more of his yoke or burden, he hath made it,
and doth daily make it, so easy and light to me.

"`And we know that the Son of God is come, and hath given us an understanding,
that we may know him that is true; and we are in him that is true,
even in his Son Jesus Christ.
This is the true God and eternal life.`" 1 John 5:20. There is an inward,
spiritual coming of the Son of God into the heart,
by which coming (to them that receive him) he giveth a new and spiritual understanding,
whereby they know him that is true (and without it they cannot),
and are ingrafted into him and found in him; partaking of his life and righteousness,
to the glory of God the Father; and so in true understanding are able to say,
"`Lo this is the God, this is the Saviour we waited for.
This is the true or very God, and eternal life.`" What are all notions about God,
and about his Son Jesus Christ, to this inward sense and experience of them?

"`God, who commanded the light to shine out of darkness, hath shined in our hearts,
to give the light of the knowledge of the glory of God in
the face of Jesus Christ.`" 2 Cor. 4:6. Oh,
how precious is it to be able to witness this in measure!
to experience God shining upon my tabernacle (as Job speaks,
Job 29:2-3), and by his light my walking through darkness!
It is true, Christ was the light, he had the fulness of light,
and the apostles a very great proportion: but, blessed be the Lord, I have received some,
and am changed by it, and become light in the Lord; and walk with God,
and dwell with God in the light, even as he is light, and dwells and walks in the light.
Is not this a blessed testimony?
and is not he blessed who can set his seal to it?

"`Which veil is done away in Christ.`" 2 Cor. 3:14. It was promised of old,
that in the mountain where God would make the feast of fat things, he would destroy,
swallow up, or do away the veil,
or that which veils the life and glory of the Lord from man,
and hinders it from being revealed in him. Isaiah 25:6-7.
Now in Christ there is no veil; in his light, life, Spirit, and power,
there is no veil: where they are inwardly manifested and received, the veil is done away,
and the glory of the mystery revealed and beheld.

"`If ye continue in my word, then are ye my disciples indeed; and ye shall know the truth,
and the truth shall make you free.`" John 8:31-32. What is this word
which the disciples of the Lord Jesus Christ are to continue in?
Is it any less than Spirit and life?
And what is it to be a disciple indeed, but to learn the law of life at his mouth,
and to continue therein?
And what is the truth which makes free?
Is it not the living Truth (the Word which lives and abides forever),
the powerful Truth, the operative Truth?
This cuts between a man and his lovers; this divides between soul and spirit,
joints and marrow,
and makes the soul free from that evil spirit which hath embondaged it.
It sanctifieth, it cleanseth, it reneweth, it quickeneth, it giveth strength,
it maketh free from the soul`'s enemies, from the bondage of sin and corruption,
and brings into the glorious liberty of the sons of God:
and they that are made free from sin by that which is contrary to sin, and which subdues,
overcomes, and destroys sin, they doubtless are free indeed.
Oh, precious is it to experience this, even the truth that is free from sin,
and makes free from sin all that truly know it, and are joined to it,
and live and abide in it!

"`For sin shall not have dominion over you; for ye are not under the law,
but under grace.`" Rom. 6:14. What is the law?
what is the ministration of the law?
Is it not the ministration of the letter?
of that which is holy and righteous, by an outward or literal command?
What is grace?
Is it not the inward teacher,
which inwardly instructeth to deny ungodliness and worldly lusts, and to live soberly,
righteously, and godly?
etc. Is it not the ministration of the Spirit and power?
Is it not the ministration of the new covenant,
where the law of the Spirit of life in Christ Jesus is written in the heart,
and the commandment of life made easy by the power of the Lord Jesus,
who manifests himself within to make willing unto, and to strengthen to obedience?

Now they that are under this grace, under this Spirit, under this power,
doth it not break the power and dominion of sin in them, and set them free therefrom?
Can sin break in upon those who dwell under the shadow of the Almighty?
Indeed a man may be under a literal dispensation of holy commands against sin,
and yet be under the power of sin: but he that is gathered under the wing of Christ,
under the grace and Spirit of the gospel, turned from Satan`'s power to God`'s power,
and within the wall and bulwark thereof, he witnesseth this true, sin hath not dominion,
sin cannot have dominion, sin shall not have dominion over you.
No device of the enemy shall be able to hurt or destroy on God`'s holy mountain:
for his light shines there to dispel the darkness, and his power is revealed there,
to scatter and dash in pieces the strength of the enemy whenever it appears.

"`Upon all the glory shall be a defence.`" Isaiah 4:5. Oh! the Lord God,
by the Spirit and power of the gospel, in the day thereof,
is bringing many sons to glory, into great, inward, spiritual glory; yea,
into exceeding glory (for the ministration of the Spirit exceeds in glory).
And as God hath ordained this glorious ministration
for his sons and daughters under the new covenant,
so by the Spirit and power of the new covenant, when it breaks forth,
he is daily working, translating, and changing them, out of the earthly nature and image,
into his own divine nature, into his own heavenly glory. 2 Cor. 3:18.
And, blessed be the Lord,
the defence of his power is spread over the glory of his holy mountain,
so that nothing can make a prey of, or devour the birth of life,
or deprive of the inheritance of life there.
The Lord doth not only give a blessed lot, and lines in pleasant places,
but he maintains the lot of his children;
so that they can dwell in their Father`'s house,
and feed on the heavenly food and rich dainties of the kingdom,
in the majesty of the name of the Lord their God; which is such a dread unto the enemies,
and such a defence about them, as none can make afraid;
but they are kept in perfect peace, in perfect rest, in pure love,
out of which life springs and flows continually.

"`And in that day thou shalt say, O Lord, I will praise thee;
though thou wast angry with me, thine anger is turned away, and thou comfortest me.
Behold, God is my salvation; I will trust and not be afraid;
for the Lord Jehovah is my strength and song, he also is become my salvation.
Therefore with joy shall ye draw water out of the wells of salvation.`" Isa. 12:1-3.
Oh! precious to witness the inward,
spiritual day of redemption and deliverance,
wherein praises from a living sense naturally spring
up to the Lord! to witness the reproofs at an end,
the anger, indignation, trouble, and sorrow at an end, and the Comforter come,
ministering peace, joy, and comfort to the soul!
Ah! when the Lord is felt, the salvation (his presence, his power, his life,
his virtue the salvation); when faith springs towards him,
and the fear of the enemy (or concerning the enemy) is banished;
when he is experienced to be the soul`'s daily strength against him;
yea and doth so deliver, that instead of the former fear,
because of the fury and oppression of the enemy, the soul can now sing,
because of that strength and heavenly authority,
which the Lord putteth forth and exerciseth in the heart against him;
when the well of life, the well of salvation, the Saviour`'s well, is kept open,
and the Philistines, the uncircumcised spirit, power, and nature, cast out,
that they can stop it no more;
but the soul can draw the water of life out of the well and fountain
of life with joy,--ah! then the gospel dispensation is indeed known,
and the blessed estate thereof witnessed and experienced!

"`I counsel thee to buy of me gold tried in the fire, that thou mayst be rich;
and white raiment, that thou mayst be clothed,
and that the shame of thy nakedness do not appear; and anoint thine eyes with eye-salve,
that thou mayst see.`" Rev. 3:18. What is the gold tried in the fire,
which man is to buy of Christ, that he may be made rich therewith?
What is the white raiment which the soul is to be clothed with,
without which it is naked in God`'s sight,
and in the sight of the truly discerning (and there is a
time when the shame of its nakedness will appear more generally,
as it doth already to the eye of the spiritual man who judgeth all things)?
What is the eye-salve wherewith the eye is to be anointed, or it cannot see?
Is it not precious to purchase this gold and raiment of Christ,
and to have this eye-salve to anoint the eye with,
and to keep it open that it may daily see its way, and walk in the light of the Lord?
Certainly this is all inward and spiritual, as a remnant witness it this day;
glory to the Lord God.

"`But the anointing which ye have received of him, abideth in you;
and ye need not that any man teach you:
but as the same anointing teacheth you of all things, and is truth, and is no lie;
and even as it hath taught you,
ye shall abide in him.`" 1 John 2:27. The outward anointing was a shadow of the inward,
and had a glory in it under the dispensation of the law;
and the inward anointing in the gospel dispensation is spiritual and divine,
and exceeding glorious.
Christ, the anointed one, anoints all his.
No being a son, without being begotten by the Spirit and power of the Father;
and no abiding a son, but by the virtue and power of the same Spirit,
remaining in and with the soul;
so that every son receives of the anointing of the Father: Christ received the Spirit,
the fulness, that he might give to them a proportion.
Now to experience this anointing, and to experience it abiding and teaching all things;
and to know this voice, the voice of the Shepherd, the voice of the anointing,
which the sheep still finds to be true, and no lie; and to abide in the vine,
in the life, in the Spirit, in the power, as this Spirit or anointing teacheth: oh,
here is the sweet, the clear state, the blessed state!
Here the promises and blessings are Yea and Amen in Christ: and the soul can say,
he is faithful and just who hath promised,
who hath opened the treasures of life to his family, to his house, to his children,
to his servants, and blesseth them with all spiritual blessings, in heavenly things,
in Christ.

"`Surely his salvation is nigh them that fear him, that glory may dwell in our land:
mercy and truth are met; righteousness and peace have kissed.
Truth shall spring out of the earth; and righteousness shall look down from heaven.
Yea, the Lord shall give that which is good; and our land shall yield her increase.
Righteousness shall go before him,
and shall set us in the way of his steps.`" Ps. 85:9. to the end.
Is it not precious to witness that fear of God in the heart, to which salvation is nigh,
and the land wherein glory dwells?
Where mercy and truth meet, righteousness and peace kiss?
Where truth springs out of the earth, and righteousness looks down from heaven?
Where God gives that which is good,
and the land of the living yields the increase of life to him?
Where righteousness goes before him, and he sets his in the way of his steps?
Where the Lamb goes before, and the way is not known,
but as the Lamb goes before and leads into it?
Where God is the Shepherd, and the soul doth not want,
because he maketh it to lie down in pastures of tender grass,
and leadeth by the waters of quietness (where it drinks of the brook in the way),
and in the paths of righteousness for his name`'s sake!
See Psa.
23. Is there not a kingdom of darkness, a land of iniquity inwardly?
and do not they that dwell there, and sit there, dwell in darkness,
and sit in the region and shadow of death?
And is there not a travel out of this land into the holy land (the land of light,
the land of the living),
and a translation out of this kingdom into the kingdom of the dear Son?
And is not God the Shepherd there?
Christ the Bishop of the soul there?
and doth not he oversee and take care of souls there, leading them into fresh pastures,
and by the soft flowing waters?
Is not salvation nigh there, yea, round about that land?
Do not mercy and truth meet there?
righteousness and peace kiss there?
yea, doth not the glory of the Most High dwell in and overshadow that land?
Is not the eye of the Lord upon it for good, from one end of the year to the other?
doth not he watch over it night and day that none hurt it,
and water it in the proper seasons?
Oh, who can utter the goodness and glory of the Lord which is revealed and shines here!
Rev. 3:20.
"`Behold, I stand at the door and knock; if any man hear my voice,
and open the door, I will come in to him, and will sup with him,
and he with me.`" Here are several things, which, in their order and seasons,
the living come to a certain and sensible experience of.

As, First, Christ standing at the door and knocking.
What is the door at which he stands?
and how doth he knock?
How doth the contrary spirit knock?
how doth his Spirit knock?

Secondly, What is his voice?
and how is his voice heard?
To hear Wisdom`'s cry within, in the inward streets; his call at the door,
at which he would enter; must not the true ear in some measure be opened first?
Can any one hear without an ear?

Thirdly, What it is to open the door?
There is a door-keeper`'s state to be witnessed,
and the right door-keeper knows how to open and how to shut the door,
and is exercised in opening and shutting the door.
The king of glory is to be opened to, and let in; but no wolf, no stranger,
no strange spirit, is to be hearkened or opened to.

Fourthly, What Christ`'s coming in is at the door opened to him?
When he knocks, would he not come in?
Would he stand always at the door knocking?
Nay, nay; when the door is opened at which he knocks,
he who is the resurrection and the life enters; the king of righteousness,
the king of peace, enters; he who is the wisdom and power of God enters:
and what becomes of the power and goods of the enemy then?
Doth he not kill and destroy them?
Doth he not consume and devour them?
Doth he not empty the house of them, and garnish the house with that which is truly pure,
glorious, and beautiful?

Lastly, What is it to have him sup with the soul?
And what is it for the soul to sup with him?
Is not here eating and drinking in his Father`'s kingdom?
Doth he not first destroy the devil`'s kingdom, and then set up his own kingdom?
And doth he not fast with the soul, and feast with the soul,
in the kingdom which he sets up there?
Oh that all men knew how near he who is eternal life is to them!
Doth not God search the heart?
Is not he near the heart?
Doth not his light shine there, in the midst of man`'s darkness and corruption?
Doth not his power reach thither, and assault and trouble the enemy?
Doth not his pure love wherewith he loveth man pierce thither?
Doth he not knock?
Doth he not call?
Doth he not touch?
Doth he not draw?
Doth he not give at times, some living tender sense to many hearts,
who too much neglect and despise him, and regard not the day of his tender visiting them,
and calling after them?
Oh! how is the love of God, the Spirit of God, the life of God, the wisdom of God,
the power of God,
the drawings and instructions of his grace day by
day resisted by the wisdom and will of the flesh,
in those that are born thereof, and hearken thereto, and so live after the flesh,
and not after that which reproves the flesh!

Many more scriptures might be mentioned, and also sensibly and livingly witnessed to;
but these are enough to give a taste.
The Lord open men`'s understandings into the thing itself,
and give them the key which opens into the truth, even into the mystery thereof,
wherein is the hidden life and virtue.
Amen.

=== A FEW WORDS CONCERNING THE TRUE CHRIST; HOW IT MAY BE CERTAINLY AND INFALLIBLY KNOWN WHICH IS HE

This question relates not to his outward appearance,
in the days of his flesh; but to his inward and spiritual appearance,
how it may be known.
To which the answer on my heart is: Even after the same way,
and by the same means is he to be known in his inward appearance,
as he was known in his outward; which was by the revealing of the Father.
For "`none knows the Son but the Father,
and he to whom the Father reveals him.`" And when Simon Peter confessed him to be Christ,
the Son of the living God: "`Blessed (said he) art thou, Simon Bar-Jona;
for flesh and blood hath not revealed it unto thee,
but my Father which is in heaven.`" Matt. 16:16-17.

And if none could know Christ in his appearance in the flesh,
notwithstanding so many manifest and express prophecies concerning him,
but such only to whom the Father revealed him;
how shall any know his inward and spiritual appearance,
unless they be taught of the Father, and hear and learn of him so to do?

But more particularly to show how the Father revealed his Son,
and how they came to know in that day that he was the Son of the living God,
the Holy One, the anointed Saviour; and that the same way, and by the same means,
people that will truly know him, must come to the knowledge of him now:

First, They came to know him by the manifestation of the life that was in him,
by the fulness of the grace and truth which dwelt in him, and put itself forth,
so as to be discerned by the inward and spiritual eye in them.
"`For the life was manifested.`" 1 John 1:2. The life which was
in him was manifested to the spiritual eye which was in them:
and thus they came to know him.

Secondly, By his voice and knocks.
Thus said he concerning his sheep in those days, that they knew his voice. John 10:4.
Oh, he hath such a voice, as none hath but he!
He speaks in his Father`'s authority (not as the scribes, not as earthly-wise,
learned men); he speaks in the evidence and demonstration of God`'s Spirit.
The words which he speaks are Spirit and life; they that hear his voice live;
and when he stands at the door and knocks, he pierceth deep.

Oh, the beatings of his hand upon the tender and sensible hearts and consciences!
Oh, his secret reproofs, his secret instructions,
his secret quickenings and enlightenings!
How did they, and how do they,
eternally make him manifest in the hearts and consciences of his?

Thirdly, By his baptism, or by his baptizing into his own Spirit and power.
While people were in expectation, and mused in their hearts of John,
whether he were the Christ or not, John answers the case,
and tells them how they might discern and know the true Christ.
It is not I, who baptize with water; but he that baptizeth "`with the Holy Ghost,
and with fire; whose fan is in his hand,`" etc. Luke 3:15-17.
Was not this then, and is not this now, the way to know the true Christ?
He that knoweth him who inwardly and spiritually baptizeth, him who hath the fan,
who inwardly fanneth and purgeth the floor, gathering in the wheat,
and burning up the chaff, doth not he inwardly, truly, and spiritually know Christ?
He that knoweth the word, which is quick and powerful,
and sharper than any two-edged sword, piercing,
even to the dividing asunder of soul and spirit, and of the joints and marrow,
and is a discerner of the thoughts and intents of the heart;
doth not he know "`the word which was in the beginning, which was with God,`" yea,
"`which was God`"? For he is the only searcher of the heart, and trier of the reins.

Fourthly, By his mighty works.
"`The works which the Father hath given me to finish, the same works that I do,
bear witness of me,
that the Father hath sent me.`" John 5:36. And when John
sent two of his disciples to Jesus with this question:
"`Art thou he that should come,
or look we for another?`" Christ bids them go and
tell John what things they had seen and heard:
"`How that the blind see, the lame walk, the lepers are cleansed, the deaf hear,
the dead are raised, to the poor the gospel is preached;
and blessed is he whosoever shall not be offended in me.`" Luke 7:22-23. "`Why,
herein is a marvellous thing`" said the blind man "`that ye know not whence he is,
and yet he hath opened my eyes.`" John 9:10. He who hath the power,
and putteth forth the power inwardly; who openeth the inward eye, the inward ear,
looseth the inward tongue, causeth the inward feet to walk in the way of life,
and the inward hands to work the works of God,--he is the Messiah, the Saviour,
the Word of life, the Son of the living God.
They that believe in him, in his Spirit, in his power, in his inward appearance,
have the witness in themselves, the living testimony, which none can put out,
or take away from them.
He hath opened mine eyes, he hath opened my heart, he hath raised me out of the grave,
he hath given me eternal life.
He hath changed me inwardly, created me inwardly, by the working of his mighty power;
and I daily live, and am preserved, and grow by the same power, I feel his life,
his virtue, his power, his presence day by day.
He is with me, he lives in me; and I live not of myself,
but by feeling him to live in me, finding life spring up from him into me,
and through me; and therein lies all my ability and strength forevermore.

=== A FEW WORDS IN THE BOWELS OF TENDER LOVE AND GOOD WILL TO MY NATIVE COUNTRY

It is written, "`When thy judgments are in the earth,
the inhabitants of the world shall learn righteousness.`"
Oh that this might be verified concerning thee,
O England, even that thou mightest learn righteousness,
and that the days of thy unrighteousness, might come to an end!
Have not God`'s judgments been upon thee?
Yea, are not God`'s judgments still upon thee?
And can any thing divert them from coming more upon thee,
but thy speedy returning unto the Lord, in breaking off thy sins by unfeigned repentance?
Oh that thou mightest be sensible of the hand of the Lord, and mightest hear the rod,
and him who hath appointed it!
The Lord hath power over all nations, and can break them in pieces as a potter`'s vessel.
They are but as the drop of a bucket, as the small dust of the balance;
they are before him as nothing, and are counted to him less than nothing, and vanity.

Read Isai.
24. See how God will plead with nations,
and consider whether he be not dealing thus with thee?
Oh! hath not that been found in thee, and is not that found in thee,
which provoketh the Lord exceedingly?
Oh that the weighty sense of thy sins were upon thee,
and that thou mightest truly repent, and turn from them;
that thou mightest reap the benefit of God`'s judgments, and learn righteousness,
and his indignation might be removed from thee,
and his tender bowels of compassion move towards thee!

But perhaps some may say, "`What is the righteousness we should learn?`"

Answer.
Oh! learn to know God; that is a righteous thing.
Learn to fear God; learn to worship him aright.
How is that?
Why in his own Spirit and truth, in which he seeks to be worshipped.
Learn humility towards God; learn justice and mercy towards men;
learn to love thy enemies.
If ye will be Christians, that is the law of Christ;
but that which is called the Christian world,
many of them have not yet learned so much as to love their friends;
but hate and persecute such as fear the Lord, and seek their good,
and stand in the gap to keep back the wrath of the Lord from breaking in upon them,
and are wrestling mightily with him with strong cries,
that he would stay the sharpness thereof,
that it might not break forth to their destruction.

Learn to do to others as ye would be done to.
Do not do to any, because of their religion and tender consciences towards the Lord,
what ye would not have done to yourselves because of your religion.
How long will it be ere ye learn this?
How many judgments and distresses shall come upon you,
before ye bow in spirit under the mighty hand of God,
and yield yourselves in submission to him, to learn these things of him?

Question.
But how shall we learn righteousness?

Answer.
Retire inwardly to that, and hearken inwardly to that,
which gives the sense of judgments, and learn of that;
and that will wean you inwardly from all your unrighteousness,
and teach you righteousness.
There is that inwardly in the unregenerate which hardens and misleads;
there is also that inwardly which tenders, melts, teacheth, and leadeth aright,
as it is believed in and obeyed.

Oh that men knew the difference between these two,
and how to turn from the one to the other!
For out of the heart proceeds all that is evil and vain,
and out of the heart are the issues of life also.
The well or puddle of the muddy waters, of the waters of Egypt, of the wine of Sodom,
and waters of Babylon, is there;
and the well and cistern of the pure waters is there also.

Oh, my native country,
that thou mightest be the first nation in this age of the
world that might pass through the judgments of God,
and be cleansed thereby, and be happy!
Oh that thy rulers and governors were weaned from the spirit and wisdom of this world,
and might receive of God`'s holy Spirit and wisdom,
and judge and govern themselves and the people thereby!
When the Jew outward was chosen to be the people of God,
did not he pour out of his Spirit to govern them by?
Were the judges, kings, and leaders thereof only anointed with outward oil?
Were they not also anointed with God`'s Spirit?
And can any Christian magistrate govern aright any Christian
nation without the assistance and guidance of the same Spirit?
And oh that all the people were anointed also,
that they might be inwardly kings and priests to the Lord,
and the kingdom of Christ might be inwardly set up in all their hearts,
and every man might reign, in and through him, over the enemies of his own soul!
Oh that the power and glory of the Lord might cover thy governors and inhabitants,
O England!
Oh, the prayers that have been long put up in bowels of tenderness for thee!
Oh! the besom of the Lord, the besom of his righteous judgments,
that it might sweep the hearts of men inwardly,
that this nation might be prepared for the glory of the Lord (for the
glory which he reveals in his heavenly birth) to break forth outwardly,
to the admiration and magnifying of the work of his power in the eyes of all beholders!
Amen, amen.
