== The Flesh and Blood of Christ / In the Mystery and in the Outward

[.heading-continuation-blurb]
Briefly, plainly, and uprightly acknowledged and testified to,
for the satisfaction and benefit of the tender-hearted,
who desire to experience the quickening, healing, and cleansing virtue of it.

[.heading-continuation-blurb]
With a brief account concerning the people called Quakers,
in reference both to principle and doctrine.

[.heading-continuation-blurb]
Whereunto are added, some few other things, which, by the blessing of God,
may be experimentally found useful to the true pilgrims and faithful
travellers out of the nature and spirit of this world.

[.heading-continuation-blurb]
Written in true love and tenderness of spirit by

[.section-author]
Isaac Penington

[.section-date]
1675

[quote.section-epigraph, , 1 Tim. 3:16]
____
And without controversy great is the mystery of godliness.
God was manifest in the flesh, justified in the Spirit, seen of angels,
preached unto the Gentiles, believed on in the world,
received up into glory.
____

[quote.section-epigraph, , Rom. 9:5]
____
Of whom are the fathers, and of whom as concerning the flesh Christ came,
who is over all, God blessed forever. Amen.
____

=== Preface

Having been lately at London,
upon occasion of a meeting between some of the people called Quakers,
and some of the people called Anabaptists, and other confederates,
wherein I was somewhat concerned, being charged or brought in by Thomas Hicks,
in his second book of [.book-title]#Dialogues,# called "`Continuation,`" p. 4 to prove,
that the Quakers account the blood of Christ no more than a common thing;
and having been at that meeting to clear my innocency in that particular,
but the thing not then coming in question,
and I being to return to my habitation in the country (though I
stayed also a second meeting for that purpose),--it was on my heart,
in the clearness and innocency thereof, to give forth this testimony,
to take off that untruth and calumny of T.H. both from the people called Quakers,
and myself; being both of us greatly therein injured,
as the Lord God of heaven and earth knoweth.
I have had experience of that despised people for many years,
and I have often heard them (even the ancient ones
of them) own Christ both inwardly and outwardly.
Yea, I heard one of the ancients of them thus testify,
in a public meeting many years since, That if Christ had not come in the flesh,
in the fulness of time, to bear our sins in his own body on the tree,
and to offer himself up a sacrifice for mankind, all mankind had utterly perished.

What cause then have we to praise the Lord God, for sending his Son,
in the likeness of sinful flesh, and for what his Son did therein!
O professors,
do not pervert our words (by reading them with a prejudiced
mind) quite contrary to the drift of God`'s Spirit by us!
If ye should thus read the holy Scriptures, yea,
the very words of Christ himself therein and give that wisdom
of yours which fights against us scope to comment upon them,
and pervert them after this manner,
what a strange and hideous appearance of untruth and contradiction to the very scriptures
of the Old Testament might ye make of that wonderful appearance of God?
For the words of Christ seemed so foolish and impossible to the wise men of that age,
that they frequently contradicted, and sometimes derided him.

If we be not of God, we shall come to nought; nay, we had not stood to this day,
if his mighty power had not upheld us.
We could not have stood inwardly, nor could we have stood outwardly,
against the fierce assaults we have met with both ways.
And as we have not had by-ends to move us inwardly,
so neither have we had by-ends to move us outwardly, as our God knoweth.

Oh!
T.H. dost thou believe the eternal judgment at the great day,
not outwardly only in notion, but inwardly in heart?
Oh! then consider how thou wilt answer it to God,
for saying so many things in the name of a people, as their belief and words,
which never were spoken by any one of them, nor ever came into any one of their hearts!
Innocency in me, life in me, truth in me, the Christian spirit and nature in me,
is a witness against thee,
that thou wrotest thy dialogues out of the Christian nature and spirit; and thy brethren,
William Kiffin and the rest,
who have stood by thee to justify thee (or at least seemed so to do),
must take notice of these things, and condemn them in thee,
or they will expose themselves, and their religion, to the righteous judgment of God,
and of all who love truth, and hate forgery and deceit.

I pity thee; yea, I can truly say,
I forgive thee the injury thou hast done me (though indeed it is very great,
thus to represent me publicly; what thou couldst not have done,
if thou hadst equally considered the things written in that book);
and I also desire that thou mayest be sensible of what thou hast so evilly done,
and confess it before God, that he also might forgive thee.
Oh!
I would not bear the weight of this sin at the judgment seat
of Christ for ten thousand worlds!
And that these books should be so long public, and thy brethren take no notice of them,
but rather at last apply themselves to justify thee, oh! how will they answer this thing,
when they come to answer it forever?
Oh! why will ye set up an interest against our Lord Christ (who is the truth,
and teacheth truth), and bend all your strength and understanding to make lies,
falsehoods and forgeries to appear as if they were truth, and not forgeries?

If ye will judge yourselves, and repent of these things,
ye shall not be condemned of the Lord; but if ye will go on,
to cover and hide this great iniquity, ye shall not prosper therein.

As for my particular, I had committed my cause to the Lord,
and intended to have been wholly silent,
knowing my innocency will be cleared by him in this particular at the great day,
and the love, truth, and uprightness wherein I wrote these things owned by him.

But in the love of God, and in the stillness and tenderness of my spirit,
I was moved by him to write what follows.
And oh that it would please the Lord to make it serviceable even to T.H. himself,
for his good

=== The Flesh and Blood of Christ, etc.

In the second part of Thomas Hick`'s [.book-title]#Dialogues# called "`Continuation,`" p. 4.
he maketh his personated Quaker speak thus:
"`Thou sayest, we account the blood of Christ no more than a common thing; yea,
no more than the blood of a common thief.`"
To which he makes his personated Christian answer thus:
"`Isaac Penington (who I suppose is an approved Quaker) asks this question;
Can outward blood cleanse?
Therefore, saith he, we must inquire, whether it was the blood of the veil,
that is the human nature, or the blood within the veil, viz., of that spiritual man,
consisting of flesh, blood, and bones, which took on him the veil, or human nature.
It is not the blood of the veil; that is but outward; and can outward blood cleanse?`"

Now to satisfy any that desire to understand the truth as it is,
and to know what the intent of my heart and words (as spoken by me) was,
I shall say somewhat to his stating the question,
and then open my heart nakedly and plainly, as it then was, and still is, in this matter.

[.numbered-group]
====

[.numbered]
_First,_ I answer, these were not my words, which he hath set down as mine,
but words of his own patching up, partly out of several queries of mine,
and partly out of his own conceivings upon my queries,
as if he intended to make me appear both ridiculous and wicked at once.
For I nowhere say, or affirm, or did ever believe, that Christ is a spiritual man,
consisting of flesh, blood, and bones, which took on him the veil, or human nature.
Thus he represents me as ridiculous.
It is true, Christ inwardly, or as to his inward being, was a Spirit,
or God blessed forever, manifested in flesh;
which (to speak properly) cannot have flesh, blood, and bones, as man hath.
And then, besides his alterations at the beginning,
putting in only four words of my query,
and leaving out that which next follows (which might
have manifested my drift and intent in them),
he puts in an affirmation which was not mine, in these his own words:
"`It is not the blood of the veil;
that is but outward;`" and then annexeth to this affirmation of his own,
the words of my former query,
"`Can outward blood cleanse?`" as if these words of mine ("`Can outward blood cleanse?`")
did necessarily infer that the blood of Christ is but a common thing.

Herein he represents me wicked, and makes me speak, by his changing and adding,
that which never was in my heart,
and the contrary whereto I have several times affirmed in that very book where
those several queries were put (out of which he forms this his own query,
giving it forth in my name).
For in the 10th page of that book, beginning at line 3, I positively affirm thus:
that "`Christ did offer up the flesh and blood of that body`" (though not only so,
for he poured out his soul, he poured out his life) a sacrifice or offering for sin,
"`a sacrifice unto the Father, and in it tasted death for every man;
and that it is upon consideration (and through God`'s acceptance
of this sacrifice for sin) that the sins of believers are pardoned,
that God might be just, and the justifier of him who believeth in Jesus,
or who is of the faith of Jesus.`" Is this common flesh and blood?
Can this be affirmed of common flesh and blood?
Ought not he to have considered this, and other passages in my book of the same tendency,
and not thus have reproached me, and misrepresented me to the world?
Is this a Christian spirit; or according to the law or prophets, or Christ`'s doctrine?
Doth he herein do as he would be done by?
Oh that he had a heart to consider it!
I might also except against those words,
"`human nature,`" (which he twice putteth in) being not my words, nor indeed my sense;
for by human nature, as I judge, is understood more than the body: whereas I,
by the word veil, intended no more than the flesh, or outward body,
which in scripture is expressly so called, Heb. 10:20. "`through the veil,
that is to say, his flesh.`"

[.numbered]
_Secondly,_ I cannot but take notice of this, that he hath not cited the place, page,
or pages; nay, not so much as named the book,
where those words or sayings which he attributeth to me are written;
whereby any persons that are not willing to take things
upon bare report (especially in so deep charges,
reflecting not only upon one person, but a whole people), might consult the place,
and see whether they were my words or no;
and whether the queries I did put (indeed to the
hearts of people) had any such drift or no,
and might compare the words (if they were mine) both with what went before,
and also followed after; and with what was said in several other places of the book,
which speak of Christ`'s flesh and blood as of no common thing,
but as that which God makes use of toward the redemption of mankind.

[.numbered]
_Thirdly,_
The drift of all those queries in that book was not
to vilify the flesh and blood of Christ,
by representing it as a common or useless thing,
but to bring people from sticking in the outward, to a sense of the inward mystery;
without which inward sense and feeling,
the magnifying and crying up the outward doth not avail.
Indeed, at that time, I was in a great exercise concerning professors:
love was deeply working in my heart;
and I was in a very tender frame of spirit towards them, as any may perceive, who,
in the fear of God, and in meekness of spirit, shall read that book (it is entitled,
A Question to the Professors of Christianity, whether they have the true, living,
powerful, saving knowledge of Christ, or no, etc.). And in this tender frame,
in the midst of my crying to God for them, those queries,
from a true sense and understanding, sprang up in my heart, even to necessitate them,
if possible, to some sense of the mystery,
which there is an absolute necessity of unto true Christianity and salvation.
This was the very intent of my heart in the several queries,
which generally speak of one and the same thing, under several metaphors and figures.
And that this was my intent, these words following,
in the second page of my preface to that book, do plainly express.
The words are these:--

[quote]
____
Now to draw men`'s minds to a sense of truth, to a sense of that which is the thing,
that they might know the bread indeed, that they might know the living waters,
come to them, and drink thereof,
and find Christ in them a well of water springing up to eternal life;
therefore was it in my heart to give forth this question and the ensuing queries,
which he that rightly answers, must know the thing; and he that doth not know the thing,
by his inability to answer, may find that he doth not, and so may wait upon God,
that he may receive the knowledge of it, and come to it,
for the eternal life which it freely giveth.
____

And that I did mean the mystery, when I spake of bread, water, the wine,
the live coal from the altar, the leaves of the tree of life, the putting on Christ,
the flesh and blood of Christ, etc., is very plain to him that reads singly.
But to make it manifest, particularly concerning the flesh and blood of Christ;
I shall recite one query; it is the 33d query, page 29. The query is thus:
"`Is not the true church flesh of Christ`'s flesh, and bone of his bone?
Is not the false or antichristian church flesh of Antichrist`'s flesh,
and bone of Antichrist`'s bone?
What is the flesh of the spiritual whore,
which is to be stripped naked and burnt with fire?
Shall ever the church, which is of Christ`'s flesh, be stripped naked and burnt with fire?
Nay, doth not his flesh make able to abide the devouring fire,
and to dwell with the everlasting burnings?`" Can this possibly
be understood of outward flesh and bone?
Is it not manifestly intended of flesh and bone in the mystery?
Yea, that it did relate to the mystery, in that very query,
out of which he takes the four first words, and no more,
is very manifest by the following words of the same query.
It is the 17th query, page 25. The query runs thus:
"`Can outward blood cleanse the conscience?
Ye that are spiritual, consider; can outward water wash the soul clean?
Ye that have ever felt the blood of sprinkling from the Lord upon your consciences,
and your consciences cleansed thereby, did ye ever feel it to be outward?
It is one thing what a man apprehends (in the way of notion)
from the letter concerning the things of God,
and another thing what a man feels in Spirit.`" Is it not manifest,
by the express words themselves,
that I spake of the inward feeling of the blood in the mystery?

[.numbered]
_Fourthly,_ This query,
"`Can outward blood cleanse the conscience,`" etc. doth not necessarily,
nor indeed at all infer, that the blood of Christ, as to the outward,
was but a common thing, or useless.
If I had been to answer this query myself,
he doth not know what my answer would have been.
It was put to the professors to answer inwardly in their hearts, who I did believe,
upon serious consideration, could not but confess, in way of answer thereto,
that outward blood itself (or of itself) could not
cleanse and purge away the filth that was inward;
but that must be done by that which is inward, living, and spiritual.
Then hereby they had been brought to see the necessity of the mystery, the Spirit,
the power, the life of the Son, to be inwardly revealed in them;
and then I had obtained my end.
Nor was I their enemy in desiring or aiming at this for them,
or in setting queries before them,
which to my eye (as in the sight of God) seemed proper and conducible in themselves
(however they might fail as to them) towards the obtaining of this end.
And if they could once come to this, to own the flesh and blood in the mystery,
and so come to partake of its cleansing and nourishing virtue,
and not fix and appropriate that to the outward which
chiefly belongs to the mystery,--I say,
if they could but go thus far with me,
in owning the inward life and power in the sensible feeling and operation thereof,
I could meet them a great way in speaking glorious things of,
and attributing a cleansing or washing virtue to, the outward,
in and through and with the inward.
For I do not separate the inward and outward in my own mind;
but the Lord opened my heart, and taught me thus to distinguish,
according to the Scriptures, in love to them, and for their sakes.
For that was not my intent to deny the outward,
or make it appear as a common or useless thing.
There was never such a sense in my heart,
nor was ever word written or spoken by me to that end; which to make more manifest,
I shall now plainly open my heart, how it hath been, and is still,
with me in this respect,
since it pleased the Lord and Father of mercies to
reveal the mystery of himself and of his Son in me.

====

In the first place, I freely confess, that I do own and acknowledge, as in God`'s sight,
OUR LORD JESUS CHRIST, HIS FLESH AND BLOOD IN THE MYSTERY.
The apostle Paul speaks of the mystery of God, and of the Father, and of Christ. Col. 2:2.
The Son was revealed in him, Gal. 1:16.
and so he knew the mystery of Christ, and preached the mystery of Christ. Col. 4:3.
He was made an able minister of the new covenant, not of the letter,
but of the Spirit or mystery;
and so he preached the wisdom of God in the mystery or Spirit, 1 Cor. 2:7.
2 Cor. 3:6. Col. 1:25-27. and he had great conflict
to bring people to the rich knowledge and acknowledgement of the mystery,
chap.
2:1-2. He was sent to turn men from darkness,
and from the power of Satan (which is a mystery,
and works in men`'s hearts in a mystery) to the light, to the Spirit and power of God,
which is a mystery also; and remission of sins is received in and through this mystery. Acts 26:18.
And I desire every serious and tender heart to consider,
whether this knowledge of Christ in the mystery was not that which
he called the excellency of the knowledge of Jesus Christ his Lord. Phil. 3:8.
Certain I am,
that the knowledge of God and Christ in the mystery is the most excellent knowledge,
and no less than life eternal, inwardly revealed and felt from God in the heart.
And here no legal righteousness, no self-righteousness, can stand;
but the virtue and power of Christ`'s death and resurrection,
inwardly revealed and felt in the mystery, subdues and destroys it all.
Indeed self-righteousness may be given up in the way of notion,
or seemingly destroyed as to men`'s apprehensions,
without the revealing or working of the mystery;
but it cannot be destroyed in reality but where this is felt;
but where the mystery is known, is received, and thoroughly works,
self-righteousness can have no place there.
Now the apostle, who was acquainted with the mystery of Christ, he speaks of his body,
flesh, and bones, in the mystery, Eph. 5:30.
(and if there be flesh and bones in the mystery,
is there not also blood in the mystery?) yea, the apostle John speaks of the Spirit,
water, and blood. 1 John 5:8.
Now consider seriously, are all these of one and the same nature?
or are they of a different nature?
the Spirit of one nature, and the water and blood of another nature?
Blessed be the Lord, the birth which is born of the Spirit, and is spiritual,
knoweth the nature of the Spirit which begat it,
and knoweth water which is inward and heavenly,
and blood which is not at all of an inferior nature to it: and Jesus Christ,
our Lord and teacher, speaketh of flesh which came down from heaven,
which flesh is the bread of life, which he that lives, feeds upon,
and none can feed upon but they that live.
And by this it is manifest (to all to whom God hath given understanding in the mystery),
that his flesh and blood in the mystery is intended by him, in that he saith,
"`He that eateth my flesh, and drinketh my blood,
dwelleth in me and I in him.`" John 6:56. This dwelling
in each other is an effect of the mystery,
and is witnessed by none that know not the mystery.
And to this effect Christ himself expressly expoundeth it,
ver. 63. "`It is the Spirit that quickeneth, the flesh profiteth nothing:
the words that I speak to you, they are Spirit, and they are life.`" As if he had said,
I am speaking of the soul`'s food; I am speaking of the heavenly bread;
I am speaking of Spirit and life; I am speaking of the mystery,
which ye look upon and understand as outwardly intended by me,
and so miss of the mystery of the Spirit, wherein is the quickening virtue,
and look only at the outward body or flesh, which, without the Spirit, profiteth not,
nor ever can profit man.

[.numbered-group]
====

[.numbered]
_Secondly,_ I confess further, that I have the sense, experience,
and knowledge of this also, that in the mystery is the quickening virtue,
the cleansing virtue, the nourishing virtue, unto life eternal.
The Spirit, the water, the blood inwardly sprinkled,
inwardly poured by God upon the soul, inwardly felt and drunk in by the thirsty earth,
do cleanse, do feed, do nourish, do refresh.
Doth not God promise to sprinkle clean water upon his Israel in the new covenant,
and they shall be clean?
and to pour water on him that is thirsty, and floods upon the dry grounds?
Is it not by the spirit of judgment and burning,
that God washeth away the filth of the daughter of Zion, etc. Isa. 4:4.
Doth not the live coal from the altar purify and take away the iniquity?
Isa. 6. Oh, read inwardly!
Oh, wait to be taught of God to read inwardly, that ye may know what these things mean!
Why should ye quarrel at the precious and tender openings of truth, in love to your souls?

[.numbered]
_Thirdly,_ I have likewise this sense, and have also had this knowledge and experience,
that the outward without this cannot avail.
A man is not cleansed by notions or apprehensions concerning the thing,
but by the thing itself.
Let a man believe what he can concerning the blood of Christ,
and apply to himself what promises he can, yet this will not do, (Oh,
how grievously do men mistake herein!) but he must feel somewhat from God,
somewhat of the new creation in Christ Jesus, somewhat of his light (shining from him,
the Son, into the heart) somewhat of his life, somewhat of his power,
working against the darkness and power of the enemy in him.
Now a man being turned to this, joined to this, gathered to this standard of the Lord,
translated in some degree out of himself into this;
here somewhat of the mystery is revealed, and found working in him;
and so far he is of God, and hath some true understanding from him.
And here also he hath right to Christ`'s flesh and blood in the outward,
and to all the benefits and precious effects that come thereby.
For by owning the mystery, and receiving the mystery,
we are not taught of God to deny any thing of the outward flesh and blood,
or of his obedience and sufferings in the flesh,
but rather are taught and enabled there rightly to understand it,
and to reap the benefits and precious fruits of it.

[.numbered]
_Fourthly,_ The Lord hath shown me this also, very manifestly and clearly,
that in former times (in this nation as well as elsewhere),
before professors ran so into heaps (I mean,
into several ways and forms of church-fellowship, so called),
they had more inward sense of the mystery than now they have;
and were a great deal more tender, both unto the Lord, and one towards another,
than now they are.
For then grace in the heart, and the inward feeling,
was the thing that was most minded among the stricter sort.
They did not mind so much bare reading, or hearing, or praying,
or any outward observation whatsoever, as what they felt therein.
Let men have spoken ever so many glorious words concerning the things of God; yet,
if they had not been spoken warmly and freshly by him that spoke them,
there was little satisfaction to the soul that hungered after that which was living,
but rather an inward grief and dissatisfaction felt:
so that in that day there was an inward sense of the mystery,
though not a distinct knowledge of it, which was precious in the eye of God,
and very savory inwardly in the heart.
But now, in so long time, by looking so much outward, and beating their brains,
and disputing about the outward, many have very much, if not wholly,
lost the sense of the inward, and are found contending for the outward,
against the very appearance and manifestation of the inward;
and so are in danger of being hardened and sealed up in that which is dead and literal,
out of the limits of that which is living and spiritual.
It is a dreadful thing to fight against the living God,
and his living appearance in the hearts of those whom he chooseth,
in any age or generation.
The Lord hath been pleased to bring us (a poor despised
remnant) back to that which first gave us life,
in the days of our former profession.
Oh that ye were brought thither also, that that might remove the veil, hardness,
darkness, and deep prejudices from you;
which can never be removed while ye stick in literal apprehensions,
without the light and teachings of God`'s Spirit!
Now as touching the outward, which ye say we deny,
because of our testimony to the inward,
I have frequently given a most solemn testimony thereto;
and God knoweth it to be the truth of my heart; and that the testifying to the inward,
from which the outward came, doth not make the outward void,
but rather establish it in its place and service.
God himself, who knew what virtue was in the inward,
yet hath pleased to make use of the outward;
and who may contradict or slight his wisdom and counsel therein?
Glorious was the appearance and manifestation of his Son in flesh;
precious his subjection and holy obedience to his Father;
his giving himself up to death for sinners was of great esteem in his eye!
It was a spotless sacrifice of great value, and effectual for the remission of sins;
and I do acknowledge humbly unto the Lord the remission of my sins thereby,
and bless the Lord for it; even for giving up his Son to death for us all,
and giving all that believe in his name and power to partake of remission through him.

====

And seeing it is thus with me, seeing the root of the matter is in me, oh,
how can any man, that hopes to be redeemed by my Lord and Saviour,
reproach me for speaking of the mystery, without the least derogation to the outward,
or what was done by him in the outward!
But if I should speak vehemently concerning men`'s neglecting the mystery,
and setting up that which is outward instead of it, I should not be condemned,
but justified of the Lord in so doing.
Indeed there is a great and weighty charge from God`'s
Spirit upon the professors of this age,
for departing from the inward (I mean that sweet sense, which, in some measure,
God gave them in former times of the inward),
and magnifying and striving to establish that which they apprehend concerning the outward,
without it, and against it.
Oh that it were otherwise with them,
that God may not have this charge to manage against them,
when at the great day they are to appear before him, and be judged by him!
When all that have slighted or spoken contemptuously of his Son`'s appearance in flesh,
and have not come to a sense thereof, and repentance for it, shall be condemned;
and they that have slighted or spoken contemptuously of his appearance in Spirit,
shall not be justified: which appearance is now made manifest in the hearts of many,
blessed be the Lord for it!
Oh, what cries have been in my heart many years concerning you,
O ye professors of all sorts who have had any tenderness
towards the Lord! that ye might see and know the Lord Christ;
and confess him in Spirit, in the mystery, even in his inward appearance in the heart,
and might feel his redeeming power and virtue there,
and so be brought into union and fellowship with him!

=== The Conclusion of the First Part

There is a precious promise of God`'s making a feast of fat things on his holy mountain,
and of destroying there the face of the covering, cast over all people,
and the veil that is spread over all nations. Isaiah 25:6-7.
Now, what is this mountain?
Was there not a Mount Zion under the law, which was figurative?
and is there not a Mount Zion under the gospel, which is the substance of that figure?
and did not the Christians in the apostles`' days, who were called of God and sanctified,
come to this Mount Zion, and the city of the living God, the heavenly Jerusalem,
where they had fellowship with God the Judge of all,
and with Jesus the Mediator of the new covenant,
etc.? Heb. 12:22-24. And was not the veil here done away in him who was their Lord,
their light, their life, their strength, their sun of righteousness,
their bright and morning star?
so that with open face they could behold the glory of the Lord,
and were changed thereby into his heavenly image, from glory to glory. 2 Cor. 3:18.

But alas, how hath that life, Spirit, and power been lost, since the days of the apostles!
Men have still owned the apostles`' words,
and formed many notions and apprehensions out of the letter,
but lost the apostles`' spirit, lost the knowledge of the holy mountain,
where the veil is taken away, and where the feast of fat things is made;
and so are only dreaming about eating and drinking spiritually,
but know not what it is to feed on the living substance.
And so (being ignorant of that) the veil is over
their hearts while they read the prophets`' words,
and Christ`'s and his apostles`' words; and the mystery of life,
and of the redeeming power, is hid from their eyes:
and that which God intended to them for a table,
is become their snare (as it was with the Jews);
and their back is so bowed down under the loads and burdens of the enemy,
that they cannot so much as hope or believe in the power of life for redemption therefrom,
but conclude it must necessarily be so with them all their days.

Oh! where is the faith that gives victory over the enemies?
Where is the ability in the faith, so to resist him as to make him fly?
Where is Satan`'s falling like lightning (Oh,
his strength before the power of the Lord is but a flash!),
and the God of peace his treading him under the feet of his saints?
Oh! where is that truth, or that knowledge of the Son, which makes free from him?
(John 8:32,36) Where is that Spirit wherein liberty from his power and snares is felt? 2 Cor. 3:17.
Where is living in the Spirit, and walking in the Spirit,
and in the pure light of the Lord, where he cannot come?
Where is reading of the Scriptures in that which gives to witness them,
and which fulfils them in the heart?

Oh, the mystery of godliness, the power of godliness, where the life is revealed,
and the veil taken away, and an understanding given, opened, and kept open,
to read and understand the Scriptures aright; yea, and the hidden glory also!
Where it cannot be said in truth to those that are there, Ye know not the Scriptures,
nor the power of God; but, Ye have received power to become sons of God,
and ye are in him that is true; who truly opens the Scriptures in your hearts,
and gives you the enjoyment, inheritance, and possession of the precious promises,
whereby ye are made partakers of the divine nature,
and live in him who is the head and spring of that nature.
Oh that people that profess Christ were here!
Oh that they did know him who begets! and then they would
not be so ignorant of those that are begotten by him;
but would come into the true faith, into the true love,
into the true knowledge and obedience of him,
whom God hath appointed to guide and govern, and build up the whole living body.
The Lord guide me inwardly thither, where the mystery is revealed,
and the fellowship with God, and his Son and saints, held in the mystery!
For our fellowship is not in a notional knowledge concerning Christ,
but in the life itself; which the Lord God gather his people more and more into,
and build them more and more up in.
Amen.

=== A Brief Account Concerning the People Called Quakers

[.heading-continuation-blurb]
We are a people of God`'s gathering, who (many of us)
had long waited for his Appearance, and had undergone great Distress for want thereof.

[.discourse-part]
Question.
But some say, What appearance of the great God and Saviour did ye want?

[.discourse-part]
Answer.
We wanted the presence and power of his Spirit to be inwardly manifested in our spirits.
We had (as I may say) what we could gather from the letter,
and endeavored to practise what we could read in the letter;
but we wanted the power from on high, we wanted life,
we wanted the presence and fellowship of our beloved;
we wanted the knowledge of the heavenly seed and kingdom, and an entrance into it,
and the holy dominion and reign of the Lord of life over the flesh,
over sin and death in us.

[.discourse-part]
Question.
How did God appear to you?

[.discourse-part]
Answer.
The Sun of righteousness did arise in us, the day spring from on high,
the morning-star did visit us,
insomuch that we did as really see and feel the light
and brightness of the inward day in our spirits,
as ever we felt the darkness of the inward night.

[.discourse-part]
Question.
How did God gather you?

[.discourse-part]
Answer.
By the voice of his Son, by the arm of his Son,
by the virtue of his Son`'s light and life inwardly revealed and working in our hearts.
This loosed us inwardly from the darkness, from the bonds of sin and iniquity,
from the power of the captiver and destroyer,
and turned our minds inwardly towards our Lord and Saviour,
to mind his inward appearance, his inward shinings, his inward quickenings;
all which were fresh from God, and full of virtue.
And as we came to be sensible of them, join to them, receive and give up to them,
we came to partake of their virtue,
and to witness the rescuing and redeeming of our souls thereby.
So that by hearing the Son`'s voice, and following him,
we came to find him the way to the Father,
and to be gathered home by him to the Father`'s house, where is bread enough,
and mansions of rest and peace for all the children of the Most High.

Now as touching the blessed principle of truth, which we have had experience of,
and testify to (for how can we conceal so rich a treasure, and be faithful to God,
or bear true good-will to men!), it is no new thing in itself,
though of late more clearly revealed,
and the minds of men more clearly directed and guided to it, than in former ages.
It is no other than that which Christ himself abundantly preached,
who preached the kingdom, who preached the truth which makes free,
and that under many parables and resemblances; sometimes of a little seed,
sometimes of a pearl or hid treasure, sometimes of a leaven or salt,
sometimes of a lost piece of silver, etc.
Now what is this, and where is this to be found?
What is this which is like a little seed, a pearl, etc., and where is it to be found?
What is the field?
Is it not the world, and is not the world set in man`'s heart?
What is the house which is to be swept, and the candle lighted in?
Is it not that house, or heart, where the many enemies are?
A man`'s enemies, saith Christ, are those of his own house.
Indeed the testimony concerning this was precious to us;
but the finding and experiencing the thing testified of to be according to the testimony,
was much more.
And this we say in perfect truth of heart,
and in most tender love to the souls of people, that whoever tries,
shall find this little thing, this little seed of the kingdom, to be a kingdom,
to be a pearl, to be heavenly treasure, to be the leaven of life,
leavening the heart with life,
and with the most precious oil and ointment of healing and salvation.
So that we testify to no new thing,
but to the truth and grace which was from the beginning;
which was always in Jesus Christ, our Lord and Saviour,
and dispensed by him in all ages and generations, whereby he quickened, renewed,
and changed the heart of the true believers in his
inward and spiritual appearance in them,
thereby destroying the enemies of their own house, and saving them from them.
For indeed there is no saving the creature, without destroying that in the creature,
which brings spiritual death and destruction upon it.
Israel of old was saved by the destroying of their outward enemies;
and Israel now (the new Israel,
the inward Israel) is saved by the destruction of their inward enemies.
Oh! that people could come out of their own wisdom, and wait for God`'s wisdom,
that in it they might come to see the glory, the excellency,
the exceeding rich virtue and treasures of life,
that are wrapped up in this principle or seed of life; and so might receive it,
give up to it, and come to partake thereof.

And as touching doctrines, we have no new doctrines to hold forth.
The doctrines held forth in the holy Scriptures are the doctrines that we believe.
And this doth further seal to us our belief of this principle,
because we find it a key by which God openeth the Scriptures to us,
and giveth us the living sense and evidence of them in our hearts.
We see, and have felt in it to whom the curse and wrath belong; and to whom the love,
mercy, peace, blessings, and precious promises belong;
and have been led by God`'s Holy Spirit and power through the judgments to the mercy,
and to the partaking of the precious promises.
So that what should we publish any new faith, or any new doctrines for?
Indeed we have none to publish;
but all our aim is to bring men to the ancient principle of truth,
and to the right understanding and practice of the ancient,
apostolic doctrine and holy faith once delivered to the saints.
Head notions do but cause disputes; but heart knowledge, heart experience,
sense of the living power of God inwardly,
the evidence and demonstration of his Spirit in the inward parts,
puts an end to disputes,
and puts men upon the inward travel and exercise
of spirit by that which is new and living,
which avails with God.
Now whereas many are offended at us, because we do not more preach doctrinal points,
or the history of Christ, as touching his death, resurrection, ascension, etc.;
but our declaration and testimony is chiefly concerning a principle,
to direct and guide men`'s minds thereto; to give a plain account of this thing,
as it pleaseth the Lord to open my heart at this time in love and
good will to satisfy and remove prejudices where it may be;
thus it is in brief:

[.numbered-group]
====

[.numbered]
_First,_
That which God hath given us the experience of (after
our great loss in the literal knowledge of things),
and that which he hath given us to testify of, is the mystery, the hidden life,
the inward and spiritual appearance of our Lord and Saviour Jesus Christ,
revealing his power inwardly, destroying enemies inwardly,
and working his work inwardly in the heart.
Oh, this was the joyful sound to our souls,
even the tidings of the arising of that inward life and power which could do this!
Now this spiritual appearance of his was after his appearance in the flesh,
and is the standing and lasting dispensation of the gospel,
even the appearance of Christ in his Spirit and power inwardly in the hearts of his.
So that in minding this, and being faithful in this respect,
we mind our peculiar work and are faithful in that
which God hath peculiarly called us to,
and requireth of us.

[.numbered]
_Secondly,_ There is not that need of publishing the other as formerly was.
The historical relation concerning Christ is generally believed
and received by all sorts that pretend to Christianity.
His death, his miracles, his rising, his ascending, his interceding,
etc. is generally believed by all people; but the mystery they miss of,
the hidden life they are not acquainted with, but alienated from the life of God,
in the midst of their literal owning and acknowledging of these things.

[.numbered]
_Thirdly,_ The knowledge of these, without the knowledge of the mystery,
is not sufficient to bring them unto God;
for many set up that which they gather and comprehend
from the relation concerning the thing,
instead of the thing itself,
and so never come to a sense of their need of the thing itself, nay,
not so far as rightly to seek after it.
And so many are builders, and many are built up very high in religion,
in a way of notion and practice, without acquaintance with the rock of ages,
without the true knowledge and understanding of the foundation and corner-stone.
My meaning is, they have a notion of Christ to be the rock,
a notion of him to be the foundation-stone; but never come livingly to feel him the rock,
to feel him the foundation-stone, inwardly laid in their hearts,
and themselves made living stones in him, and build upon him,
the main and fundamental stone.
Where is this to be felt but within?
And they that feel this within, do they not feel Christ within?
And can any that feel him within, deny him to be within, the strength of life,
the hope of glory?
Well, it is true once again (spiritually now, as well as formerly literally),
"`the stone which the builders refused`" (Christ within,
the builders of this age refuse) "`is become the head of
the corner,`" who knits together his sanctified body,
his living body, the church, in this our day,
more gloriously than in the former ages and generations, blessed be the name of our God.

[.numbered]
_Fourthly,_ The mystery, the hidden life, the appearance of Christ in Spirit,
comprehends the other: and the other is not lost or denied, but found in it,
and there discerned or acknowledged more clearly and abundantly.
It was to be after it, and comprehends that which went before it.
Paul did not lose any thing of the excellent knowledge of Christ, when he said,
"`Henceforth know we no man after the flesh; yea,
though we have known Christ after the flesh,
yet henceforth know we him no more.`" If he did not know Christ after the flesh,
how did he know him?
Why, as the Father inwardly revealed him.
He knew him in his Spirit and power.
He knew his death inwardly, he knew his resurrection inwardly, he knew the Spirit,
the virtue, the power of it inwardly; he knew the thing in the mystery in his own heart.
Oh, precious knowledge!
Oh, the excellency of this knowledge of my Lord and Saviour Jesus Christ!
What is the outwardly most exact literal knowledge without this?
But what then?
Do I now deny or slight the outward?
No; I have it here, and I have the inward feeling of the Spirit of life,
how it dwelt in him, how it wrought in him,
and of what wonderful value all his actions and obedience were,
in and through the virtue of this Spirit.
Was Abraham`'s offering his son so precious in God`'s eye?
Oh, then what is this!
Never was such a body so sanctified, so prepared; never such a sacrifice offered.
Oh, the infinite worth and value of it!
For by the inward life and teachings of God`'s Spirit,
am I taught and made able to value that glorious outward appearance
and manifestation of the life and power of God in that heavenly
flesh (as in my heart I have often called it),
for the life so dwelt in it, that it was even one with it.
Yet still it was a veil, and the mystery was the thing;
and the eye of life looks through the veil into the mystery, and passes through it,
as I may say, as to the outward, that it may behold its glory in the inward.
And here the flesh of Christ, the veil, is not lost,
but is found and known in its glory in the inward.
Be not offended at me, O tender-hearted reader! for I write in love things true,
according to the inward feeling and demonstration of God`'s Spirit,
though not easy perhaps to be understood at present by thee;
but in due time the Lord can make them manifest to thee,
if thou in uprightness and tenderness of heart, and in the silence of the fleshly part,
wait upon him.

====

=== A Few Words Concerning the Way of Peace

[quote.scripture, , Rom. 3:17]
____

The way of peace they have not known.
____

There is a way of peace, of true peace with God,
who is an adversary to all that is unholy and unrighteous.
Those who have been unholy and unrighteous, who have been awakened, troubled,
and could find no rest,
but the severe and righteous judgments and wrath
of the Lord lying upon their spirits night and day,
having at length had their ears opened by him,
and being led by him out of the unholy and unrighteous way,
into the holy and righteous way, have felt both life and peace therein.

Now, there are two sorts which the apostle here mentions (or two states,
which the apostle here speaks of), which have not known, nor can know,
the way of peace with God, who is an adversary to them both,
and will one day speak trouble to them both,
when their souls and consciences come to be searched and judged by him.

The one is the profane, or Gentile state, which is without the sense of God,
not heeding any appearance of his, or any inward voice of his Spirit,
or the writing of his law upon their heart.
These never knew the way wherein the heart is inwardly
and spiritually circumcised and renewed,
sin forgiven, and peace obtained.

The other is the professing or outward Jew`'s state, who may study the letter,
and apply themselves to conform outwardly to the letter,
but never were acquainted with the inward Spirit and power.
These greatly differ from the Gentile or profane state, both in outward appearance,
and in their own eye; but are the same in the ground with the Gentiles,
and know no more of the way of peace than the other do.

[.discourse-part]
Question.
But what is the way of peace, which neither the profane,
nor any sort of professors out of the life and power, ever knew, or can know?

[.discourse-part]
Answer.
It is an inward way, a way for the inward Jews,
for the inwardly renewed and circumcised to walk in.
It is a holy or sanctified way, for the sanctified ones to walk in.
It is a living way, which none but the living can find.
It is a new way, which none but those to whom God hath given the new eye can see.
It is a way that God prepares and casts up,
and leads men`'s spirits into (who hearken unto him),
and guides the feet of his saints in.
It is a strait and narrow way, which no lust of the flesh,
nor wisdom of the flesh can find out, or enter into.
Oh, how little, how low, how poor, how empty, how naked, must he be,
that enters into this way, and walks therein!
Many may seek after it, and may think to find it, and walk in it; but few shall be able,
as our Lord Christ said.
Here circumcision outward avails not; here want of that circumcision hinders not;
here bodily exercise profits little.
The new creature is all here; the cross of Christ is all here;
the power of God is all here; and he that walks according to this rule,
peace is upon him, and the whole Israel of God.
But he that knows not this rule, nor walks according to this rule, peace is not upon him,
nor is he one of the inward Israel of God, who receive power to become sons,
who receive the law of the Spirit of life in Christ Jesus,
which is the inward rule of the inward Israel.

This was the way of peace from the beginning; this is the way of peace still;
and there is not another.
To be new created in Christ Jesus, to be ingrafted into him, to abide in him,
to have the circumcision of the flesh (the body of the sins of the flesh cut
off) by the circumcision of Christ (made inwardly in the heart without hands),
and to walk not after the flesh, but after the Spirit, even in the newness of the Spirit,
here is life and peace, rest and joy forevermore.
The Lord of his tender mercy give men a sense of it, and lead men into it more and more.
Amen.

=== The Conclusion of the Whole

There is a birth which is born, not of blood, nor of the will of the flesh,
nor of the will of man, but of God. John 1:13.
And this birth, which is born of the Spirit, is Spirit.
chap.
3:6. Now this birth, which is born of the Spirit, and is Spirit,
hath a life and way of knowledge suitable to its nature and being;
which is very far above man.
Its life is in the Spirit, and its walking in the Spirit,
and its knowledge is after the way of the Spirit,
very far above man`'s way of conceiving or comprehending.
The birth itself is a mystery to man,
and its way of knowing is a way altogether hid from man.
It is indeed in the evidence and demonstration of God`'s Spirit,
in the shinings of his light in the heart:
"`In thy light shall we see light.`" The birth knows what this means.
There is a wise and prudent part in man, from which God hides the sight of his kingdom,
and the heavenly glory thereof;
but there is a babe to which God reveals the mystery thereof.
Flesh and blood cannot reveal; but the Father can and doth to his children,
who is the teacher of them all, from the least to the greatest,
in the new and living covenant.
There is man`'s day, and there is God`'s day.
There is man`'s day of gathering knowledge, after his fleshly manner of comprehending;
and there is God`'s day of giving knowledge,
by the shinings of the light of his own eternal Spirit.
In man`'s day, how doth wise and prudent man beat his brains,
and labor in the fire for very vanity!
But in God`'s day, how doth the knowledge of the Lord cover the earth,
as the waters cover the sea!
When the day-spring from on high visits inwardly,
when the Lord lighteth the candle inwardly, oh, how clear is the knowledge of the Lord,
and how doth it abound then!
Oh, what a difference there is between man`'s apprehensions and conceivings concerning Christ,
and God`'s revealing him inwardly;
and between man`'s coming to Christ according to his own apprehensions,
and his coming to Christ in the heavenly drawings and teachings of the Father! John 6:45.
Oh that the begettings of life and the
birth thereof were felt in men`'s hearts,
that in it men might know the day of God, and the kingdom of God,
and the treasures of wisdom which are hid in Christ, and will ever be so,
but as Christ is inwardly revealed and formed in the heart!
Many may have notions of Christ being formed in them:
ah! but to feel it inwardly! there is the sweetness, there is the assurance,
there is the life, there is the peace,
there is the righteousness of the Lord Jesus Christ,
and there is the joy of the true Christian forever.
Come, oh! come, all sorts of tender professors, out of yourselves, into God`'s Spirit,
into God`'s truth, that ye may know what it is to be in the Spirit, and in the truth,
and what it is to live there, and to know things there, and to worship there,
and to have fellowship with the Father and Son there.
The poor receive the gospel, the poor receive the kingdom, the poor receive the power,
the poor receive the righteousness and salvation of our Lord Jesus Christ.
Ye are too rich in your comprehensions and gathered
knowledge from your own literal conceivings,
to learn to wait aright, to receive of him his gold, his raiment, and his eye-salve.
What pleasure is it to us to testify against you?
Were it not for obedience to our God, and love to your souls, we would never do it.
We are content and satisfied to be of the little, despised flock,
which the Shepherd feeds, giving to every one his proportion of daily nourishment, life,
peace, righteousness, and joy.
It is our love to you that we would not have you
lay out your money for that which is not bread,
and your labor for that which will not satisfy the truly hungry and awakened soul,
but might come to feed on substance, on the life itself,
on the sweetness and fatness of God`'s house,
where nothing that any of his children can need or long after is wanting.
Oh that ye had the sense of our love!
If ye had the true understanding and sense of God`'s love,
ye could not but have a sense of our love also; for it comes from him,
and it flows towards you in his will and tender movings.
Do ye love God?
Are your hearts circumcised to love God?
If not, ye do not truly love.
And if ye loved him that begets, ye would love them that are begotten by him.
Your love is to your own notions and apprehensions of God, not to his nature;
for if ye loved his nature (that holy, heavenly, spiritual nature as it is in him),
ye could not but love it in his children also.
Well, our God is love, and taught us to love even our enemies,
and to wrestle with our God for them, that if it be possible,
the Lord may remove the scales from their eyes,
and give them repentance to the acknowledgment of the truth as it is in Jesus,
where it is more living and powerful, more effectual and operative (inwardly purifying,
sanctifying, yea, and justifying also), than any but those only that are born of God,
and kept alive by him, yet ever knew, or can know.

[.centered]
=== Postscript

[.heading-continuation-blurb]
Containing a few Words concerning the Doings and
Sufferings of that despised People called Quakers,
which are both misunderstood and misrepresented by many:
with an Exhortation to true Christianity.

First, their doings are looked upon by many to be from a natural principle,
and according to the covenant of works,
and not from the free grace and gift of God`'s Spirit.

Now concerning this I can speak somewhat faithfully,
as having been long experienced in the principle,
and as having had experience of the grace and tender mercy of the Lord from my childhood.
And indeed thus it hath been with me from my childhood; whatever hath been done in me,
or by me, that was good, I have felt to be from God`'s grace and mercy to me,
and have cried grace, grace, mercy, mercy, to the Lord continually therefor.
And when I was turned to his truth in the inward parts,
I found it was God`'s grace and tender love to me to turn me to it, and to preserve me,
being turned; and to cause it to spring in me day by day,
and to give me ability through it.
Ah! none knows, but they that have had experience,
how we have been weakened in the natural part; how poor we have been made,
that we might receive the gospel, and how poor in ourselves we are kept,
that we might enjoy the riches and inheritance of the kingdom.
And this we daily experience, that not by the works of righteousness which we had done,
but according to his mercy he saved us, and doth daily save us,
by the washing of regeneration, and the renewing of the Holy Ghost.
Yea, God`'s writing his law in our hearts, and placing his fear there,
and putting his Spirit within us, to enlighten and quicken,
and cause us to walk in his ways, and to keep his statutes and judgments, and to do them,
and all the mortifying of sin, and denying of the lusts of the flesh,
and performing that which is holy and acceptable in the eyes of the Lord (as
all that proceeds from his own Holy Spirit is),--all this is of the new covenant,
and performed by the working thereof,
and not by the working of the natural part of itself,
but by the working of the Spirit of life in the new birth,
and through the natural part as his instrument.
So let none reproach the works that God brings forth in us,
who hath created us anew in Christ Jesus unto good works,
lest thereby he reproach the Holy Spirit and power of the living God,
in which they are wrought, and by which they are brought forth,
and could never be brought forth without it.

Then for our sufferings, indeed they are gifts we receive from God;
so that we can truly say,
it is given us by the Lord our God not only to believe in his Son,
but to suffer for his sake; and that it is only in good conscience to God,
and by the assistance of the Lord, that we suffer;
that the patience and meekness wherewith we suffer, is not of ourselves, but of him.
Whenever the Lord permits afflictions or sufferings to come upon us, our eye is to him,
and we enter into them in his fear, knowing our own inability to go through them,
and looking up to him for strength.
And when we are in them, while they continue, we daily look up to him for strength,
and have been, many times, very weak in ourselves, when immediately or very soon after,
we have felt great strength in the Lord.
Also after our sufferings, when the Lord hath been with us all along,
and brought us through our sufferings in the peace and joy of his Spirit,
we do not look back boastingly, as if we had been any thing,
or done any thing as of ourselves; but we bow before the Lord, and bless the Lord,
when we consider how he hath been with us,
and how he hath upheld us by the right-hand of his righteousness;
and what he hath done for us when we were very poor, weak, afflicted,
and often sorely distressed.
Therefore let none reproach, misrepresent, or vilify our sufferings,
which our God hath helped us through, and for which we, in humility of heart,
give him thanks, and cannot but do so all our days,
because the thankful remembrance and sense of them
is written by the finger of his Spirit upon our hearts.
Oh! all sorts of people, whom we love and travail for,
and use our interest in the Lord our God for,
that ye might be truly sensible of your conditions,
know the inward appearance and visits of the Shepherd and Saviour of the soul,
turn to him (looking in true faith unto him), and be saved!
I say unto you, in tenderness of spirit,
oh! do not requite us so ill for our love and truth of heart towards you,
as to cast untrue and unjust reproaches upon us,
and to render that truth vile which God hath made honorable,
in sanctifying and redeeming many thereby.
Truly our love is from the God of love.
We could not so love you as we do, if our God had not taught us;
nor so seek after you as we do, in tenderness of bowels,
if we were not instruments in the hand of the Shepherd of Israel.
And the light we testify of, which we feel shine in us, it is no less than the true,
sure light of the Sun of righteousness, which God hath caused to shine in our hearts;
who also loveth mankind, and causeth it to glance into the darkest corners of the earth.
And the life we are quickened by out of sin and transgression,
and the power we have received to become sons of
God,--it is from him who is the fountain of life,
and hath all power in heaven and earth.
Oh that ye could receive the blessed report!
Oh that the arm of the Lord might be revealed in you!
Oh that ye could feel and witness the Saviour working out your salvation in you,
binding the strong man in you, casting him out of you, with all his goods after him,
that the place of the wicked one might be found no more in you,
nor none of his lusts or vain thoughts lodge in your hearts any more;
but ye might witness and experience the new heart, the clean heart, the pure heart,
in which God dwells, and the eye that sees him that is invisible.
Oh! glory to the Lord for what he hath done in and for a despised
people (who were no people before the Lord made them one),
who hath brought them to Zion, his holy mountain, where he dwells and reigns,
and where he builds up his own house and temple, which he establisheth over all;
where the sheep of Israel feed,
and where the Shepherd of Israel reigns and triumphs
in glory over the enemies of his kingdom.
The little, innocent babes taste somewhat of his holy dominion and power,
and of his kingdom of peace and righteousness;
but in his ancients his light shines very brightly,
and before them he reigneth gloriously;
so that he is praised in the very heights of Zion,
and his name renowned there over all forever.
Glory, glory to the pure spring of life, from whence the living streams come,
which refresh the souls of the living.
Surely his pure praises shall be sounded in the hearts of the living forever and ever.
Amen.

[.centered]
=== An Exhortation to True Christianity

[.heading-continuation-blurb]
It is easy to pretend to _Christ;_ but to be a true Christian is very precious,
and many Tribulations and deep Afflictions are to be passed through before it be attained unto,
as those who are made so by the Lord experience.

Now everlasting happiness and salvation depends upon true Christianity.
Not upon having the name of a Christian only,
or professing such or such Christian doctrines;
but upon having the nature of Christianity, upon being renewed by the Spirit of Christ,
and receiving the Spirit, walking in the Spirit,
and bringing forth the fruits of the Spirit.
Oh, here is the Christian indeed! and it should be every
one`'s care not to fall short of this.
Now because there is a contention about Christianity, who is the right Christian,
it behooves every man to take care as to himself that he be really such;
that he receive that from God, and be that to God,
which none but the right Christian can be, or can receive.
This is the use I would make of these things in my own heart,
even to be sure I be such a one as God hath made, and will accept and own as a Christian.
And having had some experience of this thing,
and truly understanding what the Christian state is, and what doth attend it,
I shall set down some few things, which he that inwardly knoweth, witnesseth,
and enjoyeth, is without all controversy a true Christian,
whatever men may account of him.

[.numbered-group]
====

[.numbered]
_First,_ He that is a new creature, is without doubt a true Christian.
He that is regenerated, he that is renewed in the spirit of his mind by Christ Jesus,
he that is new created in the holy and heavenly image,
he has felt the power of God`'s Spirit begetting him anew, forming him anew,
out of the old nature and image of the first Adam,
into the nature and image of the second Adam, who is the quickening Spirit,
and that which is begotten and born of him is Spirit.

[.numbered]
_Secondly,_ He that is in the new covenant is a true Christian.
He that hath thirsted after the living waters,
and hath heard the call to the waters of life,
hath heard the voice of him who gives life, and hath received life from him,
who giveth life to all that come to him,
and who maketh the new and everlasting covenant with all that hear his voice,
take up his cross and follow him, he is without doubt one of Christ`'s sheep,
whom the Shepherd owneth, and taketh care of.

[.numbered]
_Thirdly,_ He that is inwardly circumcised with the circumcision made without hands,
he is a Jew inward, a Christian inward (in the sight of God),
who hath felt the Spirit and power of Christ Jesus, and rejoiceth in Christ Jesus,
and is one of those worshippers whom God hath sought out,
and taught to worship him in the life and Spirit of his Son.

[.numbered]
_Fourthly,_ He that is inwardly washed with clean water, with the inward water,
he is the inward Jew, the inward Christian.
God promised to pour out clean water upon his Israel, and they should be clean.
He who hath the clean water poured upon him inwardly,
which inwardly washeth and cleanseth,
he is without controversy one of God`'s inward Israel.

[.numbered]
_Fifthly,_ He that feeds on the bread of life within,
and drinks the water of life out of his own well or cistern, he without doubt is living.
He that is invited to the marriage supper of the Lamb, and comes and sups with the Lamb,
he is one of the same nature and spirit with him.
He with whom Christ sups, who hath heard Christ knocking at his door, hath opened to him,
and received him in, to purify his heart, and dwell in him, and sup with him,
and give him to sup with himself; so that he eats bread in the kingdom,
and drinks wine in the kingdom, and partakes of the feast of fat things,
which God makes to his Israel in his holy mountain, he is without doubt one of Christ`'s,
and partakes of this in and through him.

[.numbered]
_Sixthly,_ He that lives the Christian life, who walks not after the flesh,
but after the Spirit; who doth not fulfill the lusts of the flesh,
but hath the law of God written in his heart, and his fear put within him,
and his Holy Spirit given to instruct him,
and to guide him to answer the holy law written in his heart,
which the carnal mind is not subject to, nor can be subject to,
without doubt he is spiritual; without doubt he is a true Christian.

[.numbered]
_Seventhly,_ He that lives by faith, who knows the faith which is the gift of God,
hath received it, and lives by it; who can do nothing of himself,
but only by faith in that holy power which doth all in him; so that he lives,
and believes, and obeys from a holy root of life, which causeth life to spring up in him,
and love to spring up in him, and the Lamb`'s meekness and patience to spring up in him,
and all grace to spring up in him,--I say, he that lives thus,
without doubt is ingrafted into the true vine, into the true olive-tree;
and the root bears him, and ministers sap unto him, and he is a true, fresh, green,
living branch of the true vine, of the holy olive-tree.

====

Many more things might be mentioned, as they are experimentally known and felt among us,
who are true Christians;
though the Baptists and others have represented us to the world as if we were no Christians;
but that touching us not,
their saying so is no more to us than the professing Jews of the same spirit,
who said Christ had a devil.
But these are to give a taste;
and he that knows and feels these may also know and feel the rest,
and he that doth not know or feel these would not know or feel the rest,
if ever so many more should be mentioned.
Now the way to feel these,
and to become a true Christian (and to grow up in the Christian life),
is to feel the seed of the kingdom, which is the beginning of the kingdom,
the beginning of true Christianity;
and then to feel the seed abiding (the seed which is of the Spirit, and which is Spirit),
here is the constant seal of Christianity in my heart;
here are true and certain evidences, day by day,
of the Christian nature and spirit manifesting themselves undeniably inwardly.

And now having the witness in myself, the testimony of him that begat life in me,
testifying to his own work, and to his own birth,
of what value are any testimonies of men without, against this?
Christianity is a mystery, and he only can truly see who is a Christian indeed,
who hath the inward eye opened,
and with that inward eye is taught of God to pierce into that wherein Christianity consisteth.
There have been many Christians of men`'s making;
there are also some Christians of God`'s and Christ`'s making;
which Christians God and Christ will own, but not the other.
Oh! let men have a care,
that when God cometh to distinguish between cattle
and cattle (between Christian and Christian),
they be found such as God will make up as his jewels, and own as the sheep of his fold;
such as shall be able to bear the trial of his searching judgment, and pure,
impartial eye; and not such as still,
notwithstanding all their profession of religion and Christianity,
are found workers of iniquity, and so not created anew in Christ Jesus unto good works,
and therefore not truly of him, nor true Christians in his eye.
