== To the Jews Natural, / And to the Jews Spiritual;

[.heading-continuation-blurb]
With a few words to England, my native country.

[.heading-continuation-blurb]
Whereunto are added three queries touching the river and city of God,
and the pure stillness wherein God is known and exalted.

[.heading-continuation-blurb]
As also some questions answered concerning the true church,
ministry, and maintenance under the gospel;

[.heading-continuation-blurb]
And likewise about the Lamb`'s war.

[.heading-continuation-blurb]
Written in travailing bowels, by

[.section-author]
Isaac Penington

[.section-date]
1677

[quote.section-epigraph, , Ps. 73:1]
____
Truly God is good to Israel, to such as are of a clean heart.
____

[quote.section-epigraph, , John 1:47]
____
Behold an Israelite indeed, in whom is no guile.
____

[quote.section-epigraph, , Rom. 2:28-29]
____
For he is not a Jew that is one outwardly;
neither is that circumcision which is outward in the flesh;
but he is a Jew which is one inwardly, and circumcision is that of the heart,
in the Spirit, and not in the letter; whose praise is not of men, but of God.
____

[quote.section-epigraph, , Jer. 9:25-26]
____
Behold, the days come, saith the Lord, that I will punish all them which are circumcised,
with the uncircumcised, Egypt, and Judah, and Edom, and the children of Ammon and Moab,
and all that are in the utmost corners that dwell in the wilderness;
for all these nations are uncircumcised,
and all the house of Israel are uncircumcised in the heart.
____

=== Preface

What a day of distress, and revelation of the righteous judgment of God,
is to come upon the wicked and ungodly world (even upon man,
who was created in the image of God, but is now fallen from it, and found out of it,
and in another image very unlike it); the eye which the god of this world hath blinded,
and the heart which he hath hardened by sin and transgression, hath no sense of.

What a day of distress and misery some in this nation (and in other parts of the world)
have already met with! how they have felt the weight of sin upon their spirits,
and what a sore thing it hath been to them to feel their souls separated
from that God that made them (who is the Husband and Father,
King and Preserver of souls that are found in his image and nature);
how they have been inwardly captivated by a foreign power, and oppressed,
and made to serve under sin,
and could hear no effectual tidings of his appearance who was able to save,
but their spirits were ready to sink, and their hope of redemption,
from that which oppressed and captivated them,
almost cut off,--this being an inward state and condition,
hath been altogether hid from the eye which is outward.

How the Lord at length appeared unto these (his bowels having long rolled over them,
and he having long waited to be gracious to them,
even till the full and acceptable set time was come);
how his light hath shined in and upon them; how he gathered those dry bones together,
and breathed life into them,
and made them live,--this also is altogether a hidden thing from the eye of the world.

How the Lord, who appeared to them, hath exercised and tried them;
how he hath judged them, and how he hath saved them;
what desolations he hath made inwardly in them, and what he hath built there,
what a hammer, a sword, a fire, etc. his pure word of life hath been in them;
how that birth which could live without God, without his inward life,
or upon words and knowledge without life, hath been famished, until,
by the pain of the famine, its very life and breath hath been taken from it,
and it crucified with Christ, by the pain of the cross of Christ;
and what birth hath been raised and crowned afterwards,
and beautified with the ornaments of righteousness and salvation, yea,
with the endless love and mercy with its God; and how the Lord is with his people,
and dwells and walks in them, and how he hath humbled them to walk with him;
and how in fear and humility they do walk with him in the light of day everlasting,
even as God is light,
and walks in the light of his own day,--these are very strange and unknown
things to the wisest and most prudent in religion at this day,
who are not gathered into the mystery of godliness (nor into the Spirit, power,
and glory of the Father), where these things are revealed in and by the Son.

What faith the children of wisdom have in the wisdom and power which hath appeared;
what confidence they have in the Lord their God,
that he will stand by them in all their exercises and trials, both inward and outward;
and what experiences they have had of the Lord`'s standing by them in both;
how his faithfulness doth not fail;
and how their faith in him is upheld and preserved by him,
that it doth not fail in the stormy time, or hour of great distress;
and how their eye is unto him, and their hearts with him in the calms,
so that their God is all in all unto them continually,--(and
who knows this but they that have it!) Oh,
who can utter or declare the sweetness and certainty of this, where it is enjoyed?

What love also the Lord sheds abroad in their hearts;
and how he teacheth and causeth them to love, by often circumcising their hearts,
and cutting off that which hindereth the pure love from springing in them;
and how they love others, in the love wherewith God (who is love) hath loved them;
and how natural it is to them to pray for their enemies,
and to bless them that curse them, and do good for evil;
but cannot requite evil for evil, being transplanted into, and growing up in,
the root that is good; and sends up good sap and virtue into them,
which nourisheth all that is good in them,
but is death and destruction to the remainders of evil,
as the Lord pursueth and findeth it out,--oh,
how impossible is it for the heart of man to conceive and understand!

Now I also having tasted of the mercy and goodness of the Lord,
and having been brought out of a state of great misery and sorrow of heart,
into the redemption and joy of God`'s chosen; and having found the Lord faithful to me,
and giving me faith in the appearance of his Spirit and power in me,
and true love (tender love), not only to my brethren in the truth, but to all mankind,
springing in me, and divers fruits issuing forth from it;
some of them at this time I cannot but publish,
and the Lord open the hearts of those whom it concerns, that they may find some help,
benefit, and furtherance by it.
For it is the joy of my heart to receive good from God; to be filled with his blessings,
to have my cup overflow; and that others may be helped, refreshed, and gladded therewith,
and, by the sweet taste thereof,
led to wait for the opening of the same root and fountain of life in themselves,
to yield living sap, and send forth living streams in them day by day.

[.old-style]
=== To the Jews Natural and to the Jews Spiritual / Somewhat in the Love of God to the Jews Natural, or Seed of Abraham after the Flesh

Oh, the glory of your state outward, who were the people whom God once chose and loved,
and manifested his power and presence among,
above all people! whose land was the glory of all lands,
to which God brought you out of Egypt by an outstretched arm,
through a dreadful wilderness, wherein ye were tempted, tried, and exercised,
and the succeeding generation fitted to enter into.
Oh, what laws and statutes, and righteous judgments, did God give you,
such as no nation besides had!
What a temple had ye to appear before God in, and the ark of the covenant,
and holy priests, kings, and prophets! and how nigh was God to you,
to be inquired of by you; and how ready to hear your prayers,
in all that you called upon him for!
The eternal God was thy refuge,
and underneath were the everlasting arms (the Lord was thy rock,
and thou wast built upon him); and he did thrust out the enemy before thee, and did say,
Destroy.
And when the arm of the Lord did destroy them before thee,
thou didst dwell in safety alone; and the Lord was a fountain of living waters to thee,
and his heavens did drop down fatness upon thee.
Happy wast thou, O Israel! who was like unto thee,
O people saved by the Lord! the shield of thy help,
and who was the sword of thy excellency! and thine enemies were found liars unto thee,
and thou didst tread upon their high places.
And it might have been still so with thee,
hadst thou not been unmindful of the rock that begat thee,
and forgotten God that formed thee.
For thy glory should not have been taken from thee, but swallowed up in a higher glory,
wherein thou mightest have had the first and chiefest share, hadst thou not,
by thy almost constant rebellion and unbelief, provoked the Lord against thee;
not only often to afflict, but at last utterly to cast thee off from being a people,
and to choose a people in thy stead,
who should bring forth better fruits to the Lord of the vineyard,
than thou in thy day hadst done.

Yet when thy state was thus glorious, it was not a state of the truly substantial,
lasting glory, but a shadowy state or representative thereof.
Thy day of glory was not the day of the Messiah, the day of everlasting light inwardly,
wherein the Lord alone is exalted inwardly in the hearts of all,
in whom he breaks down all that is contrary to the light of his day.
Thy day was but the day of the outward shadows of the heavenly substance;
but when that day (the day of the inward substance and glory) shined,
thy shadows or shadowy state was to fly away,
and to be swallowed up in the pure substance and spiritual kingdom of the Messiah.

Thy birth from Abraham after the flesh was not the birth which
was to inherit the promise in the kingdom of the Messiah;
but there is a birth inwardly born of the Spirit, born after Abraham in his faith,
who travels inwardly, as Abraham did outwardly, and seeks an inward country and city,
whose builder and maker is God: to these the spiritual kingdom and promises belong.

Thy circumcision was but the circumcision outward, the circumcision of the flesh;
it was not the circumcision of the heart: that is the circumcision of the inward Jew,
which indeed the scripture calleth for from you, because there was somewhat near you,
which would have so circumcised you, had ye hearkened and given up to it.
But ye, as a people, were not so circumcised,
but were a stiff-necked people (as Moses and the prophets were
still complaining of you) uncircumcised in heart and ears,
resisting God`'s Spirit both in your own hearts and in the prophets,
until the Lord was provoked to take away both vision and prophet from you.

The Egypt in which your fathers were in bondage, and Pharaoh who oppressed them,
was but the Egypt outward, and Pharaoh outward.
There is an inward Egypt, wherein the spiritual seed, the inward man, the soul,
is in bondage; and there is a spiritual Pharaoh, that oppresseth the spiritual seed,
in spiritual Egypt: and there is a stretching out the arm of the Almighty inwardly,
to break the strength of the inward Pharaoh, to pierce Leviathan the crooked serpent,
and to deliver the soul from under his captivity.

The wilderness also your fathers were led through, was but the outward wilderness,
where they were tempted and tried by the Lord many ways,
that he might do them good in the latter end.
But the inward Israel, after they are led out of the inward Egypt,
are tried in the inward wilderness; where they are judged after the flesh,
and that wasted in them, which is not to enter into and inherit the good land,
where they are tried in the furnace of affliction,
and their filth purged away by the spirit of judgment and burning;
that the righteous nation, which hath received the holy inward law, and keeps the truth,
may enter into the good land, city, and kingdom of the Messiah,
and inherit the blessed promises of life and salvation there.

Moses, your great prophet, was a type of the great, lasting, standing prophet,
whom God would raise up like unto Moses,
who was to give his inward law as Moses did the outward,
and to lead all the spiritual Israel as Moses did the outward Israel;
and his word was to be heard and stand in all things
whatsoever he shall say unto his people:
and whosoever will not hear and obey this prophet, shall be cut off from among the holy,
spiritual, and inwardly living people.

Joshua who succeeded Moses, led but into the figurative rest:
he was but a figure of him that inwardly leads into the inward and spiritual rest;
which the true Jews, which are inwardly created and formed by God,
and made a willing people in the day of his power, enter into.

The pillar of cloud, and pillar of fire in the wilderness,
were but figures of the spiritual pillar of cloud and fire,
by which the spiritual Israel are led and defended
in the glorious gospel day of God`'s Spirit and power.
Read Isaiah, chap. 4. which speaketh of the gospel-day,
and the pillar and cloud of fire to be created therein,
and of the defence which is to be on all the inward and spiritual glory.

The land of Canaan, the outward good and kingdom of Israel,
was but a figure of the inward land and kingdom of the inward Israel,
in the days of the Messiah.
This is the land of Judah in which the song is sung,
because of the inward strong city where God appoints salvation for walls and bulwarks,
which the righteous nation which keepeth the truth, enter into.
Isaiah 26.

Their outward kings in that land, and particularly David,
were but types of the spiritual king, the spiritual David,
whom God will raise up to the spiritual people, who should seek the Lord their God,
and David their king; who shall be their spiritual shepherd and ruler,
whom God hath appointed to feed them in the integrity of his heart,
and to guide them by the skillfulness of his hands,
who is King of righteousness and peace inwardly,
and who ministers righteousness and peace to the sheep and lambs of his pastures.

Their outward priests (even their high-priests) were but
a representation of the great high-priest of God,
who was to be a priest forever, after the order of Melchizedek.
Psal.
110.

Their outward covenant (made with them from the outward mount Sinai,
upon the giving of the law, and holy statutes and ordinances,
by which they were to live and enjoy God in their outward
state) was but a shadow of the inward and spiritual covenant,
the new and everlasting covenant,
which God makes with his inward and spiritual people in the latter days.

Their outward law, as written and engraven in tables of stone,
was but a shadow of the inward law, which God puts into the children of the new covenant,
insomuch that they need not go outwardly to learn the knowledge of God,
or his will or law; but the inward Israel find it inwardly written within.
There the isles who wait for the law of the Spirit of life, for the law of the Messiah,
receive the ministration of the law (in the Spirit
and power of the Messiah) which they wait for.

Their outward Mount Zion, on which the outward temple was built by Solomon,
that wise king, that righteous king, that peaceable king,
was a figure of the inward mountain,
whereupon the inward house is built in the days of the gospel,
in the days of the Messiah:
and to this mountain are the spiritual people to come up and worship.
And this is the Zion and Jerusalem (even inward and spiritual) from which
the law and word of the Lord go forth in the days of the Messiah:
and the spiritual house of Jacob combine or agree
together to walk in the light of the Lord,
who sends forth his light and truth, and leads them to his holy hill,
and to his tabernacles.

Their outward tabernacle and temple, sanctified by God for him to dwell and appear in,
was a shadow of God`'s inward dwelling place in man;
"`I will tabernacle in them.`" God dwelleth not in houses or temples made with hands;
that is not the place of his rest, as saith the prophet Isaiah:
but the high and lofty One that inhabits eternity, whose throne is in heaven,
and the earth his footstool,
he dwelleth also with him that is of an humble and contrite spirit,
to revive the spirit of the humble, and to revive the heart of the contrite ones.

Their outward sabbaths were not the lasting sabbath or rest of the gospel,
but given them for a sign; but the day of redemption from sin,
the day of resting from sin, the day of ceasing from the works of the flesh,
the day wherein God is all, and doth all by his Spirit and power inwardly,
and wherein he alone is exalted,--this is the day of rest
which the Lord hath made for the spiritual Israel,
and which they are glad of and rejoice in.

So their incense and sacrifices were not the lasting incense and sacrifices,
but shadows thereof.
The prayers of the saints,
when God pours out the spirit of prayer and supplication upon them,
and they pray to him therein, that is the incense.
"`Let my prayer be directed before thee as incense,
and the lifting up of my hands as the evening sacrifice.`"
And this was the incense and pure offering,
which in every place was to be offered up to God`'s name among the Gentiles,
when his name should be great among them, as Malachi foretells.
And what said David of old, when God`'s Spirit and the holy vision was upon him?
"`Sacrifice and offering thou didst not desire; mine ears hast thou opened:
burnt-offering and sin-offering hast thou not required.
Then said I, lo I come; in the volume of the book it is written of me:
I delight to do thy will, O my God; yea, thy law is in the midst of my bowels.
The sacrifices of God are a broken spirit (rend your hearts, and not your garments,
and turn to the Lord your God); a broken and a contrite heart, O God,
thou wilt not despise.`" The offering praise to God from a sincere heart,
and the ordering of the conversation aright,
these are the sacrifices well-pleasing to God;
for sacrifices were not the thing which God mainly required of outward Israel, but this,
OBEY MY VOICE: and obedience is more acceptable than all other sacrifices,
and to hearken than the fat of the choicest rams.

Besides, those outward sacrifices could not remove or take away sin from the conscience,
but he that came to do the will, and to put an end to those sacrifices and oblations,
which were but outward and imperfect; he doth both wash and take away sins from within,
and also bring in everlasting righteousness, where his light shines,
and his pure life springs inwardly in the heart.

And this is the substance of all the shadows, even the light eternal, the word eternal,
the Son of the living God (who is light as the Father is light),
the word nigh in the mouth and heart, the word of the new covenant;
the which Moses directed your Fathers to, Deut. 30. and by which the Lord speaketh,
and hath spoken throughout the world, Ps. 50:1.
and teacheth every man that hearkeneth to his voice, to do justly,
love mercy, and walk humbly with his God, as it is expressed by the prophet Micah.

Now to you Jews,
of the outward line of Abraham (whose return to the
Lord my soul most earnestly desireth after,
and for which I have most vehemently and wrestlingly prayed
to the Lord) are some few weighty queries upon my heart:

[.numbered-group]
====

[.numbered]
_Query 1._ How came David to pant so after the living God,
like the hart or hind after the water-brooks?
Was it not from the quickening virtue of this inward word, which Moses, the man of God,
had directed the mind to?
Read Psal. 119. and see how he breathed for quickenings from this word, on which all depends.
And if ye come to experience this word, and the quickening virtue of it,
and follow the Lord on therein, ye will soon come to know the day of the Messiah,
and the glory of his kingdom, which is not outward, transitory,
and of a perishing nature; but inward, spiritual, and everlasting
(as David well knew, and spake sensibly of. Psal. 145. and elsewhere).

[.numbered]
_Query 2._ What are the waters which every thirsty soul is invited to?
Are they not the waters of the Messiah?
are they not waters that flow out of the wells of salvation?
Isaiah 12. Do not the spiritual Israel draw spiritual water
out of the wells of the Saviour in the days of the Messiah?
What is it to come to these waters?
Oh that ye experimentally knew!
But this I will tell you, from true and certain experience,
that if ye come to take notice of this word of life,
which God hath placed nigh in your mouths and hearts,
to separate between the evil words and evil thoughts
of the enemy`'s begetting and bringing forth,
and the good words and good thoughts of God`'s begetting and bringing forth,
and incline your ear to it, and come from that which it reproves in you,
and draws you from to itself; your souls shall soon come to live;
and he that gives you life, will make an everlasting covenant with you,
even the sure mercies of David: but ye must still mind him as a witness, and leader,
and commander, inwardly in your hearts, that ye may be preserved in the covenant,
and enjoy the blessings of it; see Isaiah 55.

[.numbered]
_Query 3._ Did not the Messiah come at the set time,
at the time set by the Holy Spirit of prophecy?
Did he not come in the prepared body to do the will?
and did he not do the will?
And after his obedience to his Father, was he not cut off, though not for himself?
And after his cutting off, were not ye made desolate?
Why were ye made desolate?
Why did such a stroke come upon you as never before?
Oh, consider it!
Read Dan. 9:24. to the end of the chapter, and let him that readeth understand.

[.numbered]
_Query 4._ What was that curse, and on whom did it light?
"`Let their table become a snare to them,`" etc.
Psa. 69. Was it not on those that gave gall and vinegar to the Messiah to drink,
whom David was a figure of, and spake in Spirit concerning?
Whose eyes are always darkened?
Doth not the veil lie still on your whole nation?
Do ye know the inward mountain, where the veil or face of the covering is destroyed?
in the inward day and light of the Messiah it is destroyed.
There that which veils the noble eye of the mind is known,
and also that which destroys and removeth it.
To what purpose is it for you to read Moses and the prophets,
when the veil is so upon you, that ye cannot see what is to be abolished,
and is abolished, by the dawning of the glorious day of the Messiah,
and what is to remain and never to be abolished?
There is a Jewship, there is a circumcision, there is a sabbath, there is a rest,
etc. for the inward and spiritual people, which is to remain, and never to be abolished.

[.numbered]
_Query 5._ Who were those that God would hide his face from,
and see what their end should be, because they were a froward generation,
children in whom was no faith?
Who were they that moved God to jealousy, and provoked him to anger?
And what was the people and foolish nation he would
provoke them to jealousy and anger with? Deut. 32.
Was it not the spiritual, the holy nation inwardly, the true Jews,
whom God took from among the Gentiles, whom he appeared among,
and was a God and a Father to, when he cast off and forsook the Jews outward,
and left them to be a desolation?

[.numbered]
_Query 6._ Who are those that shall be hungry when God`'s servants shall eat?
and thirsty, when God`'s servants shall drink?
and ashamed, when his servants shall rejoice?
Are not your souls hungry and parched for want of the spiritual sustenance,
which the living God satisfieth his servants with,
making a feast of fat things to them on his inward holy mountain?
And are not ye ashamed of your expectations of the Messiah,
while the servants of the Lord rejoice in him, their Prince and Saviour,
and witness him daily a leader and commander to them?
What is the people whom the Lord hath slain and made desolate?
(Are not ye a slain people to God, alienated from his life, Spirit, and power,
dead in your literal notions and observations?) And what are the servants of the Lord,
whom the Lord hath called by another name, even a name that ye never knew? See Isa. 66.
And consider, how all your day God spread out his hand to you,
and ye were rebellious, and would not hear; and now night is come upon you,
and your visitation, as such a people, is and hath been long ended.

[.numbered]
_Query 7._ Did not God signify by the prophet Malachi, that he had no pleasure in you,
nor would accept an offering at your hand?
And did not he also signify the choosing of the Gentiles in your stead;
that the called among the Gentiles should be his people; and his name,
which ye had profaned, should be great among them,
and their incense and pure offering in every place be accepted,
even from the rising of the sun to the going down of the same?
read Mal. chap. 1.

[.numbered]
_Query 8._ Now the inward people, and the inward covenant, the new covenant,
are brought forth, shall ye ever be owned or regarded as an outward people,
according to your outward covenant any more?
Will not all such expectations fail you forever?
Ye have looked, from generation to generation,
for the coming and appearing of the Messiah outwardly, after an outward manner:
but his coming and appearance is inward; and he setteth up his kingdom,
his everlasting kingdom, in his saints, and in their hearts he ruleth inwardly;
and the Messiah, the seed of the woman, bruiseth the head of the serpent there.
Oh that ye knew the substance!
Oh that ye knew the word of life in the heart, and were turned to it,
and daily faithful and obedient! that ye might feel it crushing
and dashing the power of sin and corruption in your hearts.
This is the consolation, hope, and joy of the inward and spiritual Israel.
Oh that ye might be made partakers thereof;
and that your long outward captivity and desolation
might at length end in inward freedom and redemption!
Amen.

====

[.old-style]
=== Somewhat of Concern to the Jews Spiritual / Who Are of the Seed of Abraham Spiritually, or According to the Faith, and Gathered in This Day of God`'s Power, to the True and Everlasting Shiloh

[quote.scripture, , Gen. 49:10]
____

The sceptre shall not depart from Judah, nor a lawgiver from between his feet,
until Shiloh come; and unto him shall the gathering of the people be.
____

Old Jacob, in the spirit of prophecy, saw that Judah was to have the sceptre,
the kingly power; and it was not to depart from him, it was to be his right,
and the lawgiver was to be between his feet, till Shiloh came;
then the right was Shiloh`'s to reign, and to give laws to his people,
whom he should gather out of the kingdom of darkness, and from Satan`'s power,
into his own inward, spiritual and everlasting kingdom.
This was the true king, God`'s king,
whom he would set upon the holy hill of spiritual Zion; and all the holy, inward,
spiritual gatherings of all people, scattered from the holy, living power,
must be to him.

"`I will overturn, overturn, overturn it, and it shall be no more,
until he come whose right it is,
and I will give it him.`" And his dominion shall not pass away,
or the sceptre and lawgiving power shall not pass away from him, as it did from Judah,
nor shall his kingdom ever be destroyed, Dan. 7:14.
but God will give to him the throne of his father David,
and he shall reign over the house of Jacob forever;
and of his kingdom there shall be no end.

[.discourse-part]
_Query._
But who are the people that shall be gathered to him?

[.discourse-part]
Answer.
The people that shall hear his voice, and come at his call,
that shall receive the instruction of wisdom,
and feel the drawing power and virtue of the Father, in the day of his power.
It is written in the prophets,
"`All thy children shall be taught of the Lord.`" And
every one that is taught and learneth of the Father,
cometh to the Son, cometh to the Messiah, cometh to the Shiloh, to the Word eternal,
to the Word of life in the heart.

[.discourse-part]
_Query._
Was not the Messiah promised to the Jews, to come of them, and to be appropriated to them?

[.discourse-part]
Answer.
He was promised to them, and to come of them, but not to be appropriated to them;
but he was to be the universal Saviour to all that
should come under his ensign and banner.
"`He shall set up an ensign for the nations, and he shall sprinkle many nations,`" etc.
And God promised that he would give his Son (his elect,
choice servant) for a light to the Gentiles.

[.discourse-part]
_Query._
Were the Jews then excluded?

[.discourse-part]
Answer.
No: they were to be gathered to Shiloh, as well as others.
Nay, the Lord had a special regard to them; the gospel was first preached to them;
they had the first offer, or the first call to the spiritual glory;
they were the children of the prophets,
and of the covenant of God made with their fathers;
unto whom God having raised up his Son Jesus, sent him to bless them,
in turning away every one of them from their iniquities.
And the whole nation, turning from their iniquities, should have been gathered by him,
and should have enjoyed the blessing of his day and kingdom.
Yea, the first gathering was from among them,
and the first glorious gospel church was at Jerusalem,
where the Spirit and power of the Lord Jesus did
most eminently and wonderfully break forth,
and great grace was upon them all.
But the nation was not gathered to Shiloh, nor did come under his sceptre and government;
but only a remnant of the nation.
So these being gathered, the rest were cast off;
and the ensign was carried among the Gentiles,
and the great gathering was there among them.

[.discourse-part]
Question.
How is it manifest that the great gathering to Shiloh was to be from among the gentiles?

[.discourse-part]
Answer.
By many express prophecies of scripture, and promises to the Messiah,
that he should have the Gentiles for his inheritance and possession.
When God established his king, the Messiah, upon the holy hill of spiritual Zion,
notwithstanding all the heathen`'s rage against him,
and the people of the Jews imagining a vain thing
(thinking to keep the body of him in the grave,
who was the resurrection and the life), what saith the Lord to him?
"`Ask of me, and I will give thee the heathen for thine inheritance,
and the uttermost parts of the earth for thy possession.`"
Ps. 2. The Lord said in another place:
"`It is a light thing that thou mayest be my servant, to raise up the tribes of Jacob,
and to restore the preserved of Israel;
I will also give thee for a light to the Gentiles,
that thou mayest be my salvation unto the ends of
the earth.`" Isa. 49:6. Again the Lord saith further:
"`From the rising of the sun, even unto the going down of the same,
my name shall be great among the Gentiles;
and in every place incense shall be offered unto my name, and a pure offering;
for my name shall be great among the heathen,
saith the Lord of hosts.`" Mal. 1:11. "`Sing, O barren! thou that didst not bear;
break forth into singing, and cry aloud, thou that didst not travail with child;
for more are the children of the desolate than the children of the married wife,
saith the Lord.`" Isa. 54:1. Who was the married wife?
Who was the mother in the days of the first covenant?
was it not the Jerusalem below?
Who was then desolate and barren?
was it not another Jerusalem, which is free, and the mother of all the spiritual children?
Why was she now to rejoice and sing,
but because she was to break forth on the right hand and on the left,
and her seed was to inherit the Gentiles, and make the desolate cities to be inhabited?
ver. 3. The covenant of Mount Sinai did bring forth a great people, whereof Jerusalem,
that was below, was the mother.
The covenant afterwards made, besides that in Horeb,
whereof the Word nigh in the heart and mouth is the foundation (by which Word God circumciseth),
was as yet barren, and did not bring forth a people to the Lord.
But this covenant was to have a time; the Jerusalem above was to have a time,
wherein her seed should inherit the Gentiles; and the Maker, the Husband,
should be called the God of the whole earth.
ver. 5. Read Gal. 4. and see how the apostle of the Gentiles expounds the mystery,
showing which is the free woman, and her free children, and which is the bond woman,
and which the bond children, who are cast out in the day of God,
and in the shining of his heavenly light inwardly,
and cannot inherit the glorious kingdom of the gospel,
with the children of the free woman.
And consider: who were the people in the time of the first covenant?
who obtained mercy then?
Were they not the Jews?
And who were not a people?
and who did not obtain mercy,
but were left out of the love and mercy of the first covenant?
Were they not the Gentiles?
And did not the Lord promise that he would have mercy on them that had not obtained mercy?
and that he would say to them that were not his people, THOU ART MY PEOPLE;
and they shall say, MY GOD? Hos. 2:23.
compared with Rom. 9:26. Was not this once gloriously
fulfilled in the first visitation of the Gentiles?
And is it not again gloriously fulfilled in his now visiting
them again with the fresh sound of the everlasting gospel,
as was promised, Rev. 14:7.

Oh, what a promise is that concerning the day of God!
that "`in that day there shall be a root of Jesse,
which shall stand for an ensign of the people; to it shall the Gentiles seek:
and his rest shall be glorious.`" Isa. 11:10. Is not
this the day wherein the holy mountain is known,
and that nothing can hurt or destroy there?
And doth not the knowledge of the Lord cover his land, his earth,
as the waters do the sea?
And doth not the root of Jesse, the rock of life and salvation, stand for an ensign,
placed so by God?
and who can displace it, or shake them that are built on the inward Mount Zion?
Yea, is not the rest of the weary soul, when he comes hither, found to be very glorious?
And when this ensign is more fully lifted up,
shall not the Gentiles more abundantly come unto God from the ends of the earth,
and bewail their dead and estranged estate from God?
(saying, "`Surely our fathers inherited lies, vanity,
and things wherein is no profit.`" Jer. 16:19) And shall
they not turn from all their idols to serve the living God? 1 Thess. 1:9.
And concerning the Messiah it was promised,
that in his name should the Gentiles trust, and the isles should wait for his law,
and he should bring forth judgment to the Gentiles. Isa. 42:1-4.
with Matt. 12:21.

But what should I mention any more scriptures unto you concerning this thing,
whenas ye have so large, full, certain,
and daily experience of it in that which is pure and living of God,
which never deceived nor can deceive any;
for ye are begotten by his Spirit into his own image and nature,
and have received the Spirit of adoption, wherein ye cry, Abba, Father,
to the Father of spirits.
He found you indeed in a strange land, under great captivity, and alienation from him.
Ye have been in Egypt, in Sodom, in Babylon, spiritually;
but the mercy of the Lord hath followed you thither,
and the arm of the Lord hath reached to you there, and hath cut Rahab,
and wounded the Dragon: yea,
he whom the Lord hath given for a light to the Gentiles hath shined to you there,
in the midst of your darkness.
So that God sent among you the prophet like unto Moses (though far above Moses),
and hearing him, he led you out of Egypt,
and by the rod of his power did signs and wonders and valiant acts there,
breaking that power which, with a strong hand, held you captive there, and oppressed you.
And you have known the travel, trials, and temptations in the spiritual wilderness,
and the falling of the carcasses which were to fall there,
and the holy leading by the pillar of cloud and fire
through all the entanglements and dangers therein.
Yea, and the faithful among you, the tried and prepared among you,
have passed over Jordan, the river of pure judgment, into the good land,
and come to witness David and Solomon (who are one in Spirit) your King,
who rules in righteousness, and ministers to you peace everlasting.
And ye have a High-priest there, not after the order of Aaron,
but after the order of Melchizedek, who is made the everlasting High-priest of God;
not after the law of a carnal commandment, but after the power of an endless life;
whose lips preserve the knowledge of the law for you, in that endless power of life;
who ministers for you and to you, in that endless power,
and intercedes with power and efficacy, and sprinkles the blood of the covenant upon you,
which takes away sin from your hearts and consciences.
So that ye know the inward Jew`'s state, the inward holy land and kingdom,
the inward circumcision, before ye enter into that land; and the inward Lamb,
the inward passover, the inward Mount Zion, and Jerusalem;
the inward sacrifices and incense, the inward tabernacle, temple,
and ark of the covenant, the inward shew-bread, the inward manna,
the inward rod that buddeth, the inward candlestick, and the lamps,
which are never to go out in God`'s temple.
And what should I say more?
All that that people were to be outwardly, in an outward way and state,
hath God made you inwardly in the substance;
and what God would have been to them outwardly, had they obeyed his voice,
and kept his statutes and judgments, that he is to you inwardly,
who are the called and chosen and faithful followers of the Lamb;
and ye are the enjoyers of their blessings and promises inwardly.
Oh, the glory of your state to the eye that is opened to see it!

Now, somewhat doth remain on my heart unto you.
Oh, be daily sensible of the tender goodness and mercy of the Lord,
which is broken forth among you!
What mercy, what love, hath the Father shown unto you,
that ye should be thus accounted the children of God! that they, which were once nigh,
should be removed so far off; and ye, which were so far off, should be brought so nigh,
and should forever inherit the sure mercies of David!
For of a truth the Lord will never forsake you;
but his mercy endures forever towards you, and your stakes shall never be removed;
but this inward building shall stand forever.
This Zion is the place of God`'s rest, where he will dwell forever;
whereof the outward Zion was but a figure.

[.numbered-group]
====

[.numbered]
_Secondly,_ Remember what the Lord promised himself concerning you.
When he was weary of that people, and continually complaining of them, oh,
what did he promise himself concerning the people he would bring
forth by the Spirit and power of the Messiah in the latter days!
Did he not promise himself that they should be a holy people,
an inwardly circumcised people, a people that should please him;
sheep that should hear the Shepherd`'s voice, and be healed by him, gathered home to him,
and so follow and learn of him the Shepherd;
that they should all know him from the least to the greatest;
and that he would forgive their sins, and heal their backslidings,
and they should not return to folly, or backslide any more,
as the children after the flesh always did?
Is not this the people whom indeed God hath formed for himself,
who shall show forth his praise?

[.numbered]
_Thirdly,_ Remember what a covenant God hath prepared to make with you,
as ye incline your ears to him, and are led by him into the holy agreement with him;
even a covenant which is not weak, as the old covenant was;
but is full of virtue and vigor, to enable you to do whatever God requires of you.
Mark what it contains, putting God`'s fear into you:
not the fear which is taught by man`'s precepts, which man may get into his carnal mind;
but which God places as the treasury of life in the heart; as it is written,
"`The fear of the Lord and his treasure.`" Isa. 33:6. And oh,
who knows the preciousness of his treasure!
How it cleanseth the heart, and keepeth it clean,
and will not suffer the mind that is seasoned with it, and kept to it,
to depart from the living God!
It fenceth from unbelief, it fenceth from disobedience;
it will not suffer the soul so much as to meddle with any appearance of evil.
Oh, precious, glorious,
blessed treasure! happy is the man that feareth always with this fear!
Another precious thing this covenant contains, is the law written in the heart,
that it shall be as near, yea, nearer than sin is, in the heart that is made tender,
and hath the law of the Spirit of life written in it.
Who knows what it is to have the law of love, the law of life, the law of the Spirit,
the law of faith, the law of new obedience, livingly written by God in his heart!
Surely none can but they in whom God writes it!
And such can not but desire to have it written in their
hearts by his blessed finger daily more and more.
But this covenant contains yet more, even the putting of his own Spirit within them,
to be a fountain of life there, a fountain of strength and wisdom there,
to make them more and more willing in the day of his power,
and to cause them to walk in his ways, and keep his statues and judgments, and do them,
that the Lord their God may bless them, and delight in them.

====

Oh, who would not long after, and take up the cross and shame,
to enjoy the glory of this state!
Oh, what hath God done for a poor despised remnant among the Gentiles!
Oh, who would not desire to keep this blessed covenant with the Lord,
that he might fully enjoy the Lord,
that the marriage with the Maker might be witnessed
in his lovingkindness and everlasting righteousness,
and all unrighteousness and uncleanness might be put away, removed,
and separated from the heart forever!
Ah, the virgin spirit which the Lamb loves,
and delights to marry with! "`He that is joined to the Lord
is one Spirit,`" and he must part with all that is old,
evil, unclean, and corrupt in him, that would be joined to the Lord,
and become one Spirit with him.

Oh, who would lose the precious fear of the covenant, which is clean,
and endureth forever, and keepeth clean and chaste to the Lord forever!
And who would miss of one law which God hath to write in the hearts of his children,
when every law is a law of life, and changeth the mind into the nature of the lawgiver!
And who would grieve God`'s Spirit, which is our Comforter,
or quench that which kindles the pure flame of love and life in our hearts!
Much less can any of his dear and tender children be willing to vex him,
by manifest carelessness and disobedience,
who giveth us to drink of the river of his pleasure.

Oh, my dear friends, ye do not know the great travail of my heart,
that all the children of the Lord might walk before him in all well-pleasing,
that we might come all into covenant, into the full covenant,
and walk fully with him in the covenant,
that his anger might be forever turned away from us all,
and he might never be wroth with, nor rebuke any of us any more.
It is written on my heart the breaking forth of this glory would reach the Jews:
and though they be cast off as to their outward state, and not so to be owned,
or come into that glory any more; yet there is a day of mercy and love for them,
as to that inward state of life and redemption, which their outward state typified:
and the breaking forth of the full glory of the Gentiles,
and the manifestation of God`'s mighty power and presence
with them (they being made by God a people to him,
and so walking with God, as none possibly can but those who are created anew,
and so made by him), this might provoke the Jews (the poor, scattered,
forsaken Jews) to seek after the Lord their God, and David their King,
inwardly to be revealed in them, and rule among them.

The Lord God of our life and tender mercies,
carry on to perfection this blessed work of his, which he hath so mightily begun,
and so mightily hitherto carried on; and keep us in the sense of his good Spirit,
and in tender and holy subjection thereto, and in unity together in the life,
wherein we have been gathered and preserved,
and in pure judgment over all the workings of the enemy everywhere,
and in the gospel love one to another, and to all men, even our greatest enemies,
that we may seek the good of all men,
even the rescuing and preserving all out of sin and wrath, as much as in us is possible;
that the pure light wherewith our God and heavenly Father hath enlightened us,
may shine in us; and the life wherewith he hath quickened us, may live in us,
and we may feed on nothing but life, and grow in nothing but life and truth,
to the great glory of our heavenly Father, and to the great joy of our hearts.
Amen.

=== A Few Words to England, My Native Country

[.salutation]
O Land of my Nativity!
O my dear Countrymen!

The pure power of the Lord is upon me, and the springs of life open in me;
and among many other things, I am melted in love and desires after your welfare.
And this is in my heart to say to you: If I now testify to you in truth of a pearl,
a heavenly pearl, an everlasting pearl, will ye not hear me?
If I tell you your heart is the field, or earth, wherein it is hid,
will ye not consider of it?
If the everlasting gospel be preached again,
which contains true tidings of redemption from sin, will ye not listen after it?
If the kingdom of God, and righteousness of Christ, be to be revealed within,
would ye not willingly learn to wait for it there,
and beg of God that the eye may be opened in you,
which alone can see it when it doth appear.
Indeed God`'s visitation is upon this nation in an especial manner;
his light and power is breaking forth in it,
against the darkness and power of the spirit of Satan,
which hath captivated and still captivateth many.
Ye desire outward liberty, and the enjoyment of your outward rights;
would ye not be free inwardly?
Free from the base, earthly, selfish nature and spirit, which man, fallen from God,
and the glory wherein he created him, is degenerated into?
Oh! is not the power of God, and life of Christ, able to restore man to this?
He that created man at first so glorious, in his own image,
is he not able to create him anew?
Oh, hear, my dear countrymen! the power is revealed which createth anew;
and they that receive it, and are as clay in the hands of the great Potter,
given up to be formed by it, are daily created (by the operation of it) anew,
into a holy, heavenly, innocent, living, tender, righteous frame day by day;
and are made willing, daily more and more, to be the Lord`'s, in this day of his power;
and do receive power to become sons, and strength against their soul`'s enemies:
and the glorious work of redemption which God hath begun in them,
the arm of his strength mightily carrieth on in them,
to their comfort and his everlasting praise.

There is a spiritual Egypt and Sodom, as well as there was an outward;
and there is a spiritual wilderness, and Canaan also;
and the arm of God`'s power inwardly and spiritually
hath been revealed in this spiritual Egypt,
wilderness, and Canaan, as really as ever it was in the outward.
Do you not read of a Jew inward, and a circumcision inward, and the leaven inward,
and keeping the feast of unleavened bread, even of bread that is not leavened with sin?
And he that eats of the unleavened bread, it unleavens him of sin,
and leavens him with life and holiness: for it is a holy bread, and a living bread.
This is the bread which comes down from heaven, which they that feed upon live,
and they that live feed upon.
And though they be many, yet feeding upon this bread, they become one bread,
one living body, consisting of a living head, and living members;
for the same life and pure heavenly nature which is in the head,
is communicated by him to the members.

[.offset]
But how shall we find this?
may some say.

I will tell you how we found it, and how none can miss of it, that sweep the house,
and make a diligent and faithful search after it.
That in the heart of man which turns against sin, discovers sin, draws from sin,
wherein God ministers help against sin,--that is it.
That is the pearl hid; that is the kingdom hid;
in that is the righteousness of God revealed from faith to faith,
in all that receive and give up to this holy leaven.
This is of the nature of God and Christ; this is a measure of his light,
of his pure life; this is the law and commandment everlasting,
which God writes in the hearts of his spiritual Israel.
For the inward Jew hath inward tables, where the inward law is written,
for the inward eye to read.
Oh, how nigh is God inwardly, to the inward people, in this our day!
Oh! the pure glory is broke forth.
But alas! men are in their several sorts of dreams, and take no notice of it.
What shall the Lord do to awaken this nation?
In what way shall his power appear, to bring down unrighteousness,
and to bring up righteousness, in the spirits of people?
Do ye not think the Lord hath been at work?
How could deceit be so wasted inwardly, and truth so grown inwardly,
and overspread more and more, and gain ground in the nation,
if the hand and power of the Lord were not with it, blessing it.
Oh! take notice of the handy-work of the Lord, ye children of men,
and wait to feel truth near, and to partake of the living virtue and power of it,
that ye may feel your hearts creating anew,
and the old heavens and earth may inwardly pass away, wherein dwells unrighteousness;
and the new heavens and the new earth may be inwardly witnessed,
wherein dwells righteousness.
Oh that this nation might become a paradise of God!
Oh that every one might be sensible of his presence and power and
kingdom and righteous government inwardly in the heart,
from the king that sits on the throne, to the beggar on the dunghill!
Surely man was not made for himself!
Surely he was not made such a creature as now he is! but in the holy image of God,
with love in his heart to God above all, and to his neighbor as to himself.
Oh, what are the religions and professions of several sorts where this love is not found!
The Lord is restoring his image, and bringing forth the true, pure religion again.
The pearl, the truth, contains and comprehends it.
Oh, buy the pearl! oh, buy the precious truth! sell all that is contrary to it for it;
take up the cross to all that is evil in thee, as the light in thee maketh it manifest,
and thou shalt have the free possession of it in thy heart, and feel it a root of life,
a treasure of life, a well of life,
out of which the living water will be daily springing up in thee unto life everlasting.
Amen.

[.signed-section-context-close]
The 22d of the 7th month, 1676

=== Three Queries upon Three Verses of the 46th Psalm

[quote.scripture, , Verse 4]
____

There is a river,
the streams whereof shall make glad the city of God,
the holy place of the tabernacles of the Most High.
____

[.numbered-group]
====

[.numbered]
_Query 1._ Which is the river, and what are the streams thereof,
which make glad the city of God?
And which is the city of God which they make glad?
which are the tabernacles of the Most High?
and which is the holy place of those tabernacles?
Oh, my dear countrymen,
that every one in this nation did understand and enjoy these
things! for the Lord is ready to beget a will,
to beget a thirst, in the hearts of the children of men; and whosoever thirsteth,
whosoever will, is called to the waters, and may come to the waters,
and take of the water of life freely, (Isa. 55:1. Rev. 22:17) yea,
to the full satisfaction of their souls.
For indeed this is the day of God`'s power,
wherein he doth make his people willing to come to him,
and to abide with him in the fountain of living waters; and those that do come to him,
and abide with him, he abundantly satisfieth with the fatness of his house,
and giveth them to drink of the river of his pleasures. Ps. 36:8-9.
Mark: God is the fountain of living waters,
with him is the fountain of life, a river of pleasures,
a river whose streams make glad the whole city,
even the holy place of all the tabernacles of the Most High;
and he giveth his citizens to drink of it; and whosoever drinketh of it,
it maketh them glad, it refresheth their life.
Oh that more knew what this means!

[quote.scripture, , Verse 5]
____

God is in the midst of her, she shall not be moved; God shall help her,
and that right early;`" or when the morning appeareth, or from the morning appearing.
____

[.numbered]
_Query 2._ How is God in the midst of this city?
Is it not more gloriously in an inward way,
than ever he was in the temple in the outward Jerusalem, in an outward way?
How is she built?
How is she founded and situated?
How comes it about that she shall not be moved?
How is God her refuge and strength, and present help in the time of trouble?
After what manner doth God arise inwardly, and scatter his enemies?
How doth the morning light help her?
After what manner, when the enemy cometh in like a flood,
doth the Spirit of the Lord lift up a standard against him?
Ah, blessed are they that know and experience and live in the enjoyment of these things!
Oh that this whole nation did so!
Were it not worth the suffering of much, the denying of much,
and the bearing of much judgment, to come to this?

[quote.scripture, , Verse 10]
____

Be still, and know that I am God; I will be exalted among (or in) the heathen;
I will be exalted in the earth.
____

[.numbered]
_Query 3._ What is that stillness wherein God is known to be God, not outwardly in notion,
but inwardly in the heart?
What is that silence of mind, wherein God teacheth his Israel in the new covenant,
to know him as he is; even all of them, from the greatest to the least?
How will God come to be exalted in the heathen, and in the earth?
Is it not by the light of his day, breaking forth and shining in them?
Where this day breaks forth in any heart,
doth it not break down and destroy the kingdom of darkness inwardly?
And doth not the King of glory consume the man of sin,
the wicked one that was exalted in the temple before
(which temple belonged of right to God),
with the Spirit of his mouth,
and destroy him with the brightness of his coming or appearing? Isa. 11:4.
2 Thess. 2:8. Then is the day known wherein the Lord alone is exalted.
Oh that this day were more known; and the Lord, who is indeed worthy, were more exalted,
and all flesh become his footstool forever!

====

[.centered]
=== Concerning the true Church and ministry under the Gospel

[.heading-continuation-blurb]
And the Maintenance thereof;
some few Questions answered in Truth and Plainness of heart,
and left to the Witness and Testimony of God in other Men`'s Consciences.

[.discourse-part]
_Question 1._ Which is the true church,
or the gospel church or the church according to the new covenant?
(For there was an old covenant, and a church according to that, under the law;
and there is a new covenant, and a church according to that, under the gospel.)

[.discourse-part]
Answer.
For the clearing of this to the hearts and consciences of people,
let us inquire and consider what the new covenant is,
and then it will more easily appear which is the church according to the new covenant.

The new covenant according to plain scripture,
and according to manifest experience in this blessed day
of the shining of the gospel light in men`'s hearts,
is a covenant of God`'s putting his law in the inward parts of people,
and writing it in their hearts, and of his becoming their God,
and making them his people,
and of teaching them all to know him (inwardly and
experimentally) from the least to the greatest,
and of being merciful to their unrighteousness,
and remembering their sins and iniquities no more. Jer. 31:33-34.
Heb. 8:10-12.

Now if this be the new covenant, the covenant of the gospel church,
then they are the gospel church who are the people of God according to this covenant,
who have the law put by God into their inward parts, and written in their hearts;
and so according to this law and covenant, have God to be their God, and are his people,
and are taught by him to know him (as it is written,
"`All my people shall be taught of the Lord,`" Isa. 54:13. and John 6:45),
and whose unrighteousness God hath been merciful to,
and whose sins and iniquities he remembereth no more,
being washed away from their consciences by the blood of the everlasting covenant,
which the blood of bulls and goats could never do:
so that this is the New Testament church (or gospel church); a church of Jews inward,
as the law church was a church of Jews outward: a church of inward worshippers,
of worshippers in Spirit and in truth, John 4:23.
as the law church was a church of worshippers outward:
a church of inwardly circumcised ones,
as the law church was a church of outwardly circumcised ones. Rom. 2:29.
A church of such as are inwardly holy,
as the law church was to be a church of such as were outwardly holy:
a church of such as offer inward incense and sacrifices,
as the law church was a church of such as offered outward incense and sacrifices:
a church of inwardly redeemed ones, from the inward Egypt,
from the inward darkness and power of Satan,
as the law church was a church of such as were redeemed from the outward Egypt,
and the power of Pharaoh outward: a church that hath the inward ark,
(Rev. 11:19) the inward presence, the inward manna, etc.,
as the outward church of the Jews had the outward.

[.discourse-part]
_Question 2._ Which is the true gospel ministry, and who are the true gospel ministers?

[.discourse-part]
Answer.
Those whom Christ sends forth, in the Spirit and power of his Father,
to gather and build up this church.
Christ had all power in heaven and earth given him, even to this very end, to gather,
defend, and build up his church; and he bid his apostles wait for the same power,
and sends forth his ministers in the same power,
that they may be able ministers of the gospel, which is not words but power,
even the power of God unto salvation. Rom. 1:16.
The new covenant stands not in the letter, but in Spirit and power;
and they that are the ministers of it, must receive life, Spirit, and power from Christ,
the head, and minister in that Spirit, life, and power to the members,
or they cannot nourish and build them up; yea,
they must preach and minister to the world in it,
or they are not able to gather out of the world into it.
Christ, the Lord of his church, the foundation of life in his church,
the everlasting rock, is a living stone; and his church is built of lively stones;
and how can any minister life unto them, or build them up in the life, Spirit, and power,
but who are in the life, Spirit, and power, and who receive life, Spirit,
and power from the Head, to further, quicken, and build up the living members with?
The milk which nourisheth the living babe, is living,
which must come pure from the breast of life,
and not be mixed with man`'s wisdom or brain inventions,
or it cannot yield pure nourishment.
What then must the bread and wine and water of the kingdom be,
whereon the children and heirs of the kingdom must feed, or they cannot be satisfied?
And the ministers of the gospel are stewards of this heavenly life, this heavenly Spirit,
this heavenly power, this heavenly treasure, which they have in the earthen vessels,
and which God enables them to bring forth, for the feeding of his lambs and sheep.
Christ said unto Peter, "`Lovest thou me more than these?`" Peter answered him, "`Yea, Lord,
thou knowest that I love thee.`" If it be so, "`feed my lambs,
feed my sheep,`" said Christ to him.
But how should he feed them?
In what should he feed them?
With what should he feed them?
All power, saith Christ, is given me in heaven and in earth;
and I am to ascend to my Father, and to receive the fulness of his Spirit;
and do ye wait, and ye shall receive abundantly of the same Spirit and power,
and then in that Spirit and power ye shall be able to feed my lambs and sheep,
that are begotten and gathered to me, in it;
but out of it none is able to feed and build them up;
for that is the very thing they are to be fed with and built up in.
Indeed a man may be a minister of the letter, a minister of the law,
without the Spirit and power; but of the gospel he cannot possibly;
for that consists not in letter, but in Spirit, 2 Cor. 3.
and the faith that is to be begotten there, is not to stand in the wisdom of man,
but in the power of God.
The gospel state, the gospel church, the gospel building, begins in the power,
and is carried on in the power, and finished or perfected in the power;
and the whole ministry of the gospel is to partake of this power, and minister in it,
or they can do nothing in this work.
Christ Jesus our Lord begun it in this power,
and none can carry it on without this power: the Lord God of glory laid the foundation;
"`Behold, I lay in Zion for a foundation.`" etc. Isa. 28:16.
1 Pet. 2:4-6. And the quickening Spirit
alone is able to make living stones and spiritual stones;
and the Lord alone is able to build them up by the operation of this Spirit and power;
and they that are the true ministers of the gospel, minister in this,
and are to wait for it daily from God, that they may minister in it.

[.discourse-part]
_Question 3._ What is the maintenance of the ministers of Christ,
or what is to be the maintenance of the true ministers under the gospel?

[.discourse-part]
Answer.
Christ, who hath sent them forth to minister in his name, hath provided for them;
and they that are his true ministers,
are satisfied with what he hath provided for them, Matt. 10:10.
being careful not to make the gospel, which is to be an inward blessing,
outwardly chargeable to any.
The mind of the true ministers is about the service of Christ;
how they may be faithful to him, gather souls to him,
feed them with the bread of life from him;
not what they shall have from men for so doing, for such covet no man`'s gold or silver, etc.

=== Some Questions Answered Concerning the Lamb`'s War

[.discourse-part]
_Question 1._ Who is the Lamb?

[.discourse-part]
Answer.
He that takes away the sins of the world.
The Word which was in the beginning.
"`Behold the Lamb of God,`' saith John, John 1:1.
and ver. 29. He that was born of the virgin Mary after the flesh;
and was also the man-child, born of the travailing church, after the Spirit. Rev. 12:5.

[.discourse-part]
_Question 2._ Who makes war with the Lamb?

[.discourse-part]
Answer.
All that are in wickedness, in darkness, in sin and corruption,
and under the power thereof,
who strive to defend and maintain this kingdom against the appearance of his light,
Spirit, and power in them.

[.discourse-part]
_Question 3._ What strength have they on their side that make war against the Lamb?

[.discourse-part]
Answer.
The strength of the great red dragon, who hath seven heads and ten horns;
and in every one of his heads is wisdom, and in every one of his horns there is power.
So that dreadful is the battle that is fought between them, either inwardly in the heart,
or outwardly in the world, when Christ appears in his light, Spirit, and power,
to assault and break down the kingdom of darkness, and to set up his own kingdom,
which must be set up, even in the world. Dan. 7:14,27.
Rev. 11:15.

[.discourse-part]
_Question 4._ Did the great red dragon and his army ever (in any respect) prevail in this battle?

[.discourse-part]
Answer.
Yes; for even while the Lamb, and his pure life and holy testimony have prevailed,
so that the dragon and his army could get no ground over them inwardly,
but salvation (the wall and bulwark of God`'s heritage) and strength,
and the kingdom of God, and the power of his Christ, did prevail inwardly;
yet the dragon, even then, hath prevailed over their goods, liberties,
and lives outwardly; and he drove the woman, the true church, out of her place,
as I may say, that she was forced to fly into the wilderness, he so sorely assaulted her:
yea, after that also, he made war with the remnant of her seed,
and cast some of them into prison,
and drank the blood of those that would not drink his false church`'s cup,
but keep the commandments of God, and have the testimony of Jesus.
Rev. 12. and chap.
2:10. Yea,
the beast to which he gave his power (which had seven heads and ten horns like him, chap.
13:1) made war with the saints, and overcame them outwardly,
though he could not overcome them inwardly; for he could not make them to worship him,
ver. 7-8. Nay, nor the second beast neither, though he had horns like a lamb,
and spake like a dragon, and exercised all the power of the first beast,
and did great wonders, and had power to give life unto the image of the former beast,
and would kill all that would not worship the image of it;
and would suffer none to buy or sell but such as had the mark or name of the beast;
yet neither could this beast overcome the followers of the Lamb,
as to their inward life and testimony,
though it had power to kill and suppress them outwardly, ver. 11. to the end, and chap.
14:9. to ver. 13. which plainly shows the saints had patience,
and kept the commandments of God, and the faith of Jesus,
and would not worship the beast and his image, nor receive his mark,
either in forehead or hand.

[.discourse-part]
_Question 5._ What was the cry up and down nations, when the dragon and the beast thus prevailed,
and when the false church carried her cup of fornications
up and down through kingdoms and nations,
and made the kings and inhabitants of the earth drink thereof;
and who would not drink thereof, she would not let them buy nor sell, but impoverish,
imprison them, and drink their blood? Rev. 17:2.
and 6.

[.discourse-part]
Answer.
The cry everywhere was, "`Who is like unto the beast?
Who is able to make war with the beast?`" Indeed there appeared
no power anywhere able to withstand or resist this power,
which the dragon had, who gave it both to the beast which arose out of the sea,
and to the beast which arose out of the earth;
both which joined together to persecute all that
would not drink of the false church`'s cup,
which was golden without, but full of abomination and filthiness of fornication,
fornicating from the holy life, Spirit, and power of the Lamb inwardly,
who is the head of the true church and true worshippers. Rev. 13:4.
and chap.
17:4-5.

[.discourse-part]
_Question 6._ What is the time of the dragon`'s, the beast`'s,
and false church`'s thus prevailing against the true church, in reference to the outward,
though they cannot prevail against its inward life and testimony;
but that (through patience and suffering) prevails over and reigns inwardly,
in the midst of all their cruelty and oppressing of the outward man?

[.discourse-part]
Answer.
It is the time of Antichrist`'s reign, and sitting in the temple as if he were God,
and exalting himself over all that is called God, and which ought to be worshipped.
It is the time of the true church`'s being in the wilderness,
and of the man-child`'s (which the true church brought forth) being caught up to God;
which things were to last, according to the scripture account,
one thousand two hundred and sixty days, or a time, times, and half a time. 2 Thess. 2:3-4.
Rev. 12:14-6.

[.discourse-part]
_Question 7._ What will the Lamb do when this time is out?

[.discourse-part]
Answer.
He will come and make war again, he will come with his heavenly armies,
armed with spiritual armor, and fight a heavenly battle; yea,
he will judge and make war in righteousness, against the unrighteousness of the dragon,
and the beast, and the false prophet;
and his heavenly armies shall follow him their Captain and Leader, on white horses,
clothed in fine linen, white and clean, who shall fight in his Spirit and power,
against all that he fighteth against; and out of his mouth goeth a sharp sword,
that with it he should smite the nations; and he shall rule them with a rod of iron,
and make the spirits of all his opposers bow under him,
and fly to shelter themselves from that wrath which they cannot escape.
Oh, who would not kiss the Son, that he might not provoke the Lamb to wrath against him,
whose wrath is dreadful! Rev. 19:11.
to the end. Ps. 2:12.

[.discourse-part]
_Question 8._ What shall the cry be,
when God`'s Spirit and power prevaileth over the dragon`'s spirit and power,
when the Lamb gets the victory, when he smites the earth with the rod of his mouth,
and with the breath of his lips shall slay the wicked; when he brings down the dragon,
beast, and false prophet, and the false church,
mother of harlots (which hath drunk the blood of saints), with his vials, plagues, woes,
thunders, etc.; when Babylon the great city falls,
which made all nations drunk with her spiritual wine of fornication?

[.discourse-part]
Answer.
Then the power which doth this shall be magnified.
Then it shall be said no more, who can make war with the beast?
but who can withstand his power?
Who can make war with the innocent, righteous Lamb (who hath his sword in his mouth),
and with his tender-hearted, faithful followers, and prosper?
"`Who shall not fear thee, O Lord, and glorify thy name?
For all nations shall come and worship before thee; for thy judgments are made manifest.
Great and marvellous are thy works, Lord God Almighty; just and true are thy ways,
thou King of saints.`" Rev. 15:3-4. "`Yea,
a great voice of much people in heaven shall say: Hallelujah, salvation, and glory,
and honor, and power unto the Lord our God: for true and righteous are his judgments;
for he hath judged the great whore, who did corrupt the earth with her fornication,
and hath avenged the blood of his saints at her hand,`" chap. 19. ver. 1-2.

Now doth it not concern all people to consider which is Zion, God`'s holy mountain,
and which is the Jerusalem of his building; and the holy city of God,
the holy church of God, the mother of all the truly living children?
for the Jerusalem which is above, and which is free, is the mother of them all. Gal. 4:26.
And also which is Babylon, the city built by man,
and the spirit of antichrist, in a kind of likeness,
but not in the real nature of the true church;
that they may wait for and follow God`'s call to come out of her,
and may not partake of her sins, of her sorceries (Rev. 18:23),
of her fornication from the pure life, Spirit, and power, and setting up worships,
and compelling people to worship in her forms (which are out of the life,
and out of the power), that they partake not of her plagues,
which will indeed be very dreadful, such as shall affright any from coming near her,
or meddling with her spiritual sorceries and fornications any more. Rev. 18:4.
and ver. 9-10. Oh! therefore let every one consider what the beast is,
what his image, what the mark in the forehead, what in the right hand;
and take heed he be not found worshipping the beast and his image, or receiving his mark,
either in his forehead or right hand,
lest God make him to drink of the wine of his wrath which
is poured out without mixture into the cup of his indignation,
and he be tormented with fire and brimstone in the presence of the holy angels,
and in the presence of the Lamb, and have no rest day nor night.
Rev.14:9-11. I had rather run great hazards outwardly,
and suffer much affliction and persecution from men, to keep my soul true to God,
in the spiritual worship and testimony which he hath given me,
against all false ways and invented worships,
than expose my soul to the hazard of drinking of this dreadful cup of God`'s indignation;
which the Lord God of tender mercies teach men, and give them true wisdom,
to avoid and escape.
Amen.

=== Conclusion

[quote.scripture, , Isa. 52:13-15]
____

Behold my servant shall deal prudently, he shall be exalted and extolled,
and be very high.
As many were astonished at thee (his visage was so marred more than any man,
and his form more than the sons of men); so shall he sprinkle many nations;
the kings shall shut their mouths at him: for that which had not been told them,
shall they see; and that which they had not heard,
shall they consider.
____

[quote.scripture, , Ps. 45:2-7]
____

Thou art fairer than the children of men: grace is poured into thy lips;
therefore God hath blessed thee forever.
Gird thy sword upon thy thigh, O Most Mighty, with thy glory and thy majesty.
And in thy majesty ride prosperously, because of truth and meekness and righteousness;
and thy right hand shall teach thee terrible things.
Thine arrows are sharp in the hearts of the King`'s enemies,
whereby the people shall fall under thee.
Thy throne, O God, is forever and ever: the sceptre of thy kingdom is a right sceptre.
Thou lovest righteousness, and hatest wickedness, therefore God, thy God,
hath anointed thee with the oil of gladness above thy fellows.
____

[quote.scripture, ,Isa. 35:3-10 ]
____
Strengthen ye the weak hands, and confirm the feeble knees.
Say to them that are of a fearful heart, Be strong, fear not:
behold your God will come with vengeance, even God with a recompense,
he will come and save you.
Then the eyes of the blind shall be opened, and the ears of the deaf shall be unstopped.
Then shall the lame man leap as an hart, and the tongue of the dumb sing;
for in the wilderness shall waters break out, and streams in the desert.
And the parched ground shall become a pool, and the thirsty land springs of water;
in the habitation of dragons, where each lay, shall be grass with reeds and rushes.
And an highway shall be there, and a way, and it shall be called the way of holiness;
the unclean shall not pass over it, but it shall be for those: the wayfaring men,
though fools, shall not err therein.
No lion shall be there, nor any ravenous beast shall go up thereon,
it shall not be found there; but the redeemed shall walk there.
And the ransomed of the Lord shall return and come to Zion with songs,
and everlasting joy upon their heads: they shall obtain joy and gladness,
and sorrow and sighing shall flee away.
____

Blessed be the Lord God of life forever! these scriptures, and many more,
are sweetly and preciously fulfilled in the hearts of a remnant, in this our day.
They were once (in a degree) fulfilled in the day of the appearance of the word of life,
in the prepared body of flesh.
They were again more generally fulfilled, in the day of the pouring out of his Spirit,
and gathering a people to him, both from among the Jews and Gentiles,
whom he did sprinkle with his holy life, Spirit, and power.
And they are again fulfilled in the hearts of many, after the long night of darkness,
and great and large apostasy from the Spirit and power of the apostles.
Blessed, oh, blessed be the Lord! the Sun of righteousness hath again shone forth,
and appeared inwardly in a glorious, living, powerful manner,
to them that have feared his name; and he hath been a God of vengeance to the man of sin;
yea, to all that was dark, fleshly, and corrupt in them;
and a God of mercy and tender bowels to those which
panted after and waited for his salvation.
And the healing virtue from under the wings of the Saviour, and the holy anointing,
have dropped upon the eyes of the blind, the pure eye-salve, and they have been opened;
and the ears of the deaf, by the voice of the Son of God, have been unstopped;
and the inwardly and spiritually lame have leaped as an hart; and the tongue,
which could not name God in truth and righteousness, but hath been dumb before him,
and before men also, could not but sing,
because of the breaking forth of the waters and streams of life,
upon the thirsty land and parched ground, making them a pool and springs of water;
which land, which thus is changed from its wilderness and parched state, into a holy,
fresh, and living state, the dragons do not lodge in;
nor is it any more a habitation or cage for unclean
and noisome birds (as great professing Babylon,
the mother of harlots, with all her fleshly professing daughters, is),
but life dwells there: the Holy One is in the midst of this land,
and it brings forth the fruits of life and righteousness, to the righteous and Holy One.
And here the King of glory`'s highway, even the way of holiness, is known,
which none but those whom he makes holy can walk in.
Let men profess what they will, yet being unclean in heart and conversation,
they cannot pass over to come into this way; but the holy,
they which are made holy by God, and keep to, live in, and follow that which is holy,
though wayfaring men, and though otherwise fools, yet they shall not err here,
but be preserved by the holy power, in the holy way,
which is prepared and cast up for these: and as for that which would tear and destroy,
it shall not be found on all that holy mountain where these live and feed.
Yea, here is the house of God and throne of God, and God the Judge of all,
and Jesus the Mediator of the new covenant, and the blood of sprinkling,
where the ransomed of the Lord enjoy the presence of the bridegroom,
whom God hath set King, and who reigns on his holy hill of inward and spiritual Zion,
and causeth them to sing,
who feel him reign (even the everlasting seed of life to reign inwardly in the heart).
Oh, everlasting joy is upon their heads! they have obtained joy and gladness;
and sorrow and sighing flee away,
when the joy unspeakable and full of glory is felt springing in the heart,
from the sense of the presence and enjoyment of the bridegroom.
For of a truth, the Lord hath comforted Zion; yea,
he hath comforted many of her waste places (he was angry with her daughters,
before their filth was purged away by the Spirit of judgment and burning;
since that time his anger hath been turned away, and he hath comforted them,
Isa. 12:1, etc.); and he hath made her wilderness in many hearts like Eden,
and her desert like the garden of the Lord (even like the garden that he waters):
and how can joy and gladness but be found here,
with thanksgiving and the voice of melody? Isa. 58:11.
and chap.
51:3. Thus it is with such of the gathered people and nation of the Lord,
that hearken and give ear to him,
and have known the way of life to proceed out of his mouth,
and his judgment to rest for a light, ver. 4.
