== Some Sensible, Weighty Queries

[.heading-continuation-blurb]
Concerning some things very sweet and necessary to be experienced in the truly christian state.

[.heading-continuation-blurb]
Whereunto is added _a postscript,_ containing some queries on Isa. 50:10-11.
A scripture of deep counsel and concern to the darkened and
distressed states of some among those that fear and obey the Lord.

[.heading-continuation-blurb]
Written by one who hath been sorely darkened and distressed for a long season,
but at length mercifully enlightened and comforted by the hand which afflicted and distressed him:

[.section-author]
Isaac Penington

[quote.section-epigraph, , Hos. 6:1]
____
Come, and let us return unto the Lord, for he hath torn, and he will heal us;
he hath smitten, and he will bind us up.
____

[quote.section-epigraph, , Isa. 12:1]
____
And in that day thou shalt say, O Lord, I will praise thee;
though thou wast angry with me, thine anger is turned away, and thou comfortest me.
____

=== A Brief Preface

Indeed the Lord hath reached unto me by his living power,
and thereby hath begotten somewhat which he doth own,
and which he hath taught to know and own him in his living appearances in my heart;
and by its pure life and operations in me, I know it to be the pure power.
And truly I would fain have this life and power more and more reach to, prevail,
and spread in my own heart, and in the hearts of other men.
I am not for any notional religion out of the power, in any way or form whatsoever (no,
indeed I am not so much as for the very true form of godliness out of the power);
but where there is any touch, any sense, any operation,
any savor of the true life and power anywhere, my soul loveth and embraceth it,
blessing the Lord for it.
And oh! that this might be visited by the Lord wherever it is,
and kept alive to the day of redemption,
and led by the Lord into the pure and living way, and holy, everlasting covenant of life,
wherein he redeems; for which end these queries have broke forth from me:
and indeed no less than a necessity (or a necessitous force of
love and life pursuing me) hath constrained me to publish them,
who with reverence of spirit commit them into the hands of the Lord,
who can open the hearts of whom he pleaseth,
and give the living sense of what comes from him.
I am satisfied that God`'s powerful work of redeeming will go on.
Oh, blessed be his name, who hath a mighty arm,
and hath done mighty things with it inwardly in men`'s hearts! and we
are in the true faith assured that he will yet do more mighty things,
as he seeth good, to the gladding of the hearts of those whose hope is in him,
and who have no help besides him.

[.old-style]
=== Some Sensible, Weighty Queries / Concerning Some Things Very Sweet and Necessary To Be Experienced in the Truly Christian State

[.numbered-group]
====

[.numbered]
_Query 1._ What is the water wherewith the soul or inner man is to be washed,
that it may be cleansed from its inward filthiness,
as outward things are by washing with outward water? Ezek. 36:25.
Ps. 51:2. etc.

[.numbered]
_Query 2._ What is the answer of a good conscience towards God,
when the soul is inwardly baptized and made clean? 1 Pet. 3:21.

[.numbered]
_Query 3._ Christ saith, "`Blessed are the pure in heart:`" Do, or can,
any witness purity of heart before this washing?

[.numbered]
_Query 4._ How may the heart be sprinkled from an evil conscience,
and the body washed with pure water;
so that there may be a drawing near to God with a true heart,
and in full assurance of faith? Heb. 10:22.
Ps. 26:6.

[.numbered]
_Query 5._ How might the Jews wash and make themselves clean? Isa. 1:16.
Could it be any otherwise done by them,
than by taking heed to the word of the new covenant, nigh in the mouth and heart,
to which Moses had directed them? Duet. 30:14.
Ps. 119:9.

[.numbered]
_Query 6._ What is the fire which takes hold of,
and burns up the lusts and corruptions of the heart?
Is it not the word of life within, which flames against evil, and hammers down evil?
Doth not the Holy One in the midst of the spiritual Israel do this?
When Christ, who knocks at the door of the heart, is let in, and his voice hearkened to,
doth he not become a Spirit of judgment and burning,
judging and burning up what is evil there?
Is it not blessed to know this spiritual appearance,
and this work of Christ in the heart? Isa. 4:4. and 10:17.

[.numbered]
_Query 7._ What are the enemies of a man`'s house?
Who must overcome them?
How may they be overcome?
Is a man safe, or delivered from them till they be overcome? Matt. 15:19.
2 Cor. 10:4-5.

[.numbered]
_Query 8._ What is the house of the strong man, where he dwells till he be dispossessed?
Who can dispossess him?
How doth he dispossess him?
How doth he spoil his goods, and then garnish the house anew?
Oh, what a new creation and change within is witnessed when this is done!
And who would not wait, and pray, and believe,
and suffer the judgings and burnings of the Spirit of judgment and burning,
that this may be done thoroughly and effectually? Luke 11:21-22.
Isa. 26:9; 2 Cor. 5:17.

[.numbered]
_Query 9._ What is that coming to Christ which none can witness
but those that hear and learn of the Father,
and are taught by him, in the drawings of the life and Spirit of the new covenant,
to come to the Son? John 6:44-45.

[.numbered]
_Query 10._ Who can confess Jesus to be the Lord by the Holy Ghost?
Can any but they that receive the help of his Spirit,
and feel somewhat of his lordship and holy dominion in their hearts? Isa. 26:13.

[.numbered]
_Query 11._ What is the precious faith, which is the gift of God,
which none can obtain but they that are born of God? John 1:12-13.

[.numbered]
_Query 12._ Can any rightly believe that Jesus is the Christ,
unless they receive this faith, which God gives to his own children,
that are born of his Spirit? 1 John 5:1.

[.numbered]
_Query 13._ Doth not this faith give victory over the
world (over the worldly nature and spirit within,
over the worldly nature and spirit without also)?
Can any other faith give victory? 1 John 5:4.

[.numbered]
_Query 14._ What is the love of God`'s children?
Whence doth it arise?
How come they to love?
Is it not of a heavenly, spiritual nature?
Doth it not arise from God`'s begetting them, and circumcising their hearts,
and teaching them in the Spirit of the new covenant to love him, and one another, yea,
and enemies also? 1 John 4:7.
Duet. 30:6. 1 Thess. 4:9.

[.numbered]
_Query 15._ How come the children of God, who are begotten of him, to obey his commandments?
Is it not from the constrainings of his love,
which makes them natural and easy (where the birth and nature is grown up),
and not grievous and burdensome? Matt. 11:30.
1 John 5:3.

[.numbered]
_Query 16._ What is the fear God puts into the hearts of the children of the new covenant?
Is it a fear taught by the precepts of men,
or a fear springing from the root of life within?
Can any who receive this fear from God,
and who are preserved in the sense of it (and in
the holy awe and reverence which it produceth),
depart from the holy, tender, living God and Father? Jer. 32:40.

[.numbered]
_Query 17._ What is the law which God writes in the
hearts of the children of the new covenant?
Is it not the law of the Spirit of life in Christ Jesus?
Is it not the law which the isles wait for? Isa. 41:5.
And do the isles wait for it in vain?
Oh, blessed be the Lord! by the once distressed and miserable ones,
in this age it hath not been waited for in vain.

[.numbered]
_Query 18._ What is the truth that makes free indeed from the law of sin and death?
Is it not the truth as it is in Jesus; the inward truth,
which hath virtue and power in it,
to work against and work out that which is contrary to truth,
and so deliver and free the mind from it?
For the light, which is truth, can expel darkness; the life, which is truth,
can overcome death; yea, the truth, which is living, holy, and righteous,
can overcome and subdue the unholy and unrighteous nature,
and break down the strong-holds,
and bring every rebellious and captivated thought into captivity and subjection. John 8:32.
Rom. 8:2. Eph. 4:20-21. 2 Cor. 10:4-5.

[.numbered]
_Query 19._ How doth God cause the children of the new covenant to walk in his statutes,
and to keep his judgments, and do them?
Is it not by putting his Spirit into them, and by the holy virtue, power,
and operation thereof in them?
Doth not that make them a willing people in the day of his power?
And doth not that give them to do also, and strengthen them with might in the inner man?
So that not grieving that, or quenching that, that is as a flame of life in them,
and fills their hearts with joy; and the joy of the Lord is in their strength,
and in this joy and strength they can rejoice, and work righteousness,
and remember the Lord in his ways. Isa. 64:5.
Ezek. 36:27.

[.numbered]
_Query 20._ Can any work righteousness, or do righteousness,
but he that is truly righteous, inwardly righteous, in whom the righteousness of God,
the righteousness of Christ, is revealed from faith to faith?
Must not the tree be good, before the fruit can be good?
Must not the heart be changed, be made holy and righteous,
before it can bring forth that which is holy and righteous?
Can any but the plants of God, the plants of righteousness,
bring forth the fruits of righteousness? Isa. 61:3.
and 1 John 3:7.

====

Oh that people, nations, tongues, and languages could understandingly, sensibly,
and experimentally, as in God`'s sight, with the seal of his blessed Spirit,
answer every one of these things!

=== Three Queries More Added

[.numbered-group]
====

[.numbered]
_Query 1._ Dost thou indeed know the new covenant?
Hast thou inwardly felt the spiritual,
powerful gathering by the mighty arm and power of the Lord,
out of the sinful nature and state, into it?
Dost thou abide with God therein?
Art thou daily taught and fed by him there?
These are very weighty things.
Can any man be safe or happy without experiencing them?
Heb. 8:8, etc.

[.numbered]
_Query 2._ Hast thou experienced the true hunger and thirst after the living waters?
Hast thou been called and led to them?
Hast thou eaten and drunk the bread, wine, and milk which those waters yield?
Hast thou been abundantly satisfied with the fatness of God`'s house,
and hath he given thee to drink of the river of his pleasure?
Hath the Lord opened an ear in thee to hear as the learned?
And hast thou inclined thine ear, and come unto him who gives life,
and received him who is life, and gives life in that inward, spiritual,
living appearance of his in the heart, wherein and whereby he gives life?
Hast thou known his appearance inwardly, as of a living stone?
Hast thou heard and learned of the Father how to come to him, as to a living stone?
And hast thou been new created and formed a living stone by him?
And art thou a living stone, built upon him, the living stone inwardly in spirit,
daily living in him, and daily receiving spiritual life and virtue from him?
If it be thus with thee, then surely thou dost know and enjoy the everlasting covenant,
even the sure mercies of David. Isa. 55:1-3.
Ps. 36:8-9. 1 Pet. 2:4-5.

[.numbered]
_Query 3._ Dost thou sensibly and experimentally know how
the Spirit of the Father begets the child-like life,
love, and fear in the heart;
and how the pure fear of the Lord is the beginning of wisdom,
and the living child`'s treasure?
And dost thou know what the womb is wherein the living child is formed?
what the Jerusalem above is, which is the mother of all that are truly living?
and how Christ is formed in all that are begotten, and born of, and live in his Spirit? Isa. 33:6.
Gal. 4:26. John 3:6-8. Gal. 4:19.

====

=== The Conclusion

Oh, how miserable is he who is deceived about these things!
Oh, how happy is he who hath received the true understanding from God,
which cannot be deceived?
wherein he hath the evidence and demonstration of God`'s Spirit concerning them,
and knoweth the truth as it is in Jesus; as it is in his life, in his Spirit,
in his power, who ministers after the power of an endless life, unto all his sheep,
who are returned to the Shepherd and Bishop of the soul,
who hear his voice and follow him wherever he goes or leads, who is an eternal Shepherd,
and eternal Door of life to his, and leads to precious pastures,
and sweet still streams of life, and is giving the sweet food, rest,
and pure pleasure of eternal life unto his abundantly; even as it is his will,
that after their many sore trials, exercises,
and travels (and faithfulness to him therein),
they should abundantly possess and enjoy it.
Glory to the Lord forever, whose kingdom is set up in the hearts of many,
and who already reigns in the hearts of many, and will reign in the hearts of more!
Oh that men might hear the sound of his everlasting gospel! and learn to fear him,
and give glory to him, and know the hour of his judgment come in their own heart,
that by his judgment against sin and unrighteousness in them,
they might come to know and worship him;
and then the worship of the dragon and beast would soon come to an end in their hearts;
and they would worship the begetter of holiness, the begetter of life,
the King of saints, who dwells and rules in those that are his own, as the devil,
the destroyer doth in those that are his!
The Lord God of everlasting power break down the kingdom of Satan
(the kingdom of unrighteousness and darkness in men`'s hearts),
and exalt the kingdom and sceptre of his own Son instead thereof.
Amen.

[.old-style]
=== Postscript / Containing Some Queries on Isa. 50:10-11

[quote.scripture, , Verse 10]
____
Who is among you that feareth the Lord, and obeyeth the voice of his servant,
that walketh in darkness, and hath no light?`"
It is rendered in another translation:
"`And no light shineth upon him`"
(which was Job`'s case in his great affliction, as is signified by him, chap. 29:2-3).
"`Let him trust in the name of the Lord, and stay upon his God.
____

[quote.scripture, , Verse 11]
____
Behold, all ye that kindle a fire, that compass about with sparks,
walk in the light of your own fire, and in the sparks ye have kindled,
this ye shall have of mine hand, ye shall lie down in sorrow.
____

[.numbered-group]
====

[.numbered]
_Query 1._ Doth not the tender and merciful God many times,
in the bowels of his love and mercy,
bring darkness and great distress upon men`'s spirits,
that they might wait for his healing and redemption?
Yea, doth not this befall some who fear the Lord,
and are found in the holy reverence and obedience to him?
And is it not good that it should befall them?

[.numbered]
_Query 2._ Should not men, in such a condition of darkness and distress,
trust in the name of the Lord,
and stay upon him till he cause light to arise out of obscurity,
and comfort them that mourn in Zion; giving them beauty for ashes,
the oil of joy for mourning, and the garment of praise for the spirit of heaviness?

[.numbered]
_Query 3._ Are not persons very prone and liable, in time of darkness and distress,
instead of waiting upon God for his help and salvation, to be kindling a fire,
and compassing themselves about with sparks?

[.numbered]
_Query 4._ Are there not some who cannot be content without
heat and warmth in their religion and performances,
and yet, instead of waiting for God`'s kindling the fire,
and his causing the sparks of life to arise, kindle a fire of themselves,
and compass themselves about with sparks of their own kindling?

[.numbered]
_Query 5._ May not men, after they have kindled a fire and sparks,
walk in the light thereof?
And may not God, in his just judgment and sore displeasure against them,
leave them to themselves, and give them up to do so?

[.numbered]
_Query 6._ What will God do in the end, or what in the end shall befall them from God,
who kindle a fire and sparks, and have continued walking in the light thereof,
and have been heated and warmed thereby?
Will not God cause them at length to lie down in sorrow?
Oh that persons that are serious in religion, might not thus err,
and so provoke God to give them up to walk in the
light of the fire and sparks of their own kindling?

[.numbered]
_Query 7._ When do men kindle a fire and sparks of their own?
Do they not first forget the God of their salvation,
and become unmindful of the rock of their strength?
And do they not then plant pleasant plants, and set strange slips?
(And where do they plant and set them?) But what will the harvest be in the day of inheritance,
when they come to reap and inherit what they have planted and sown?
(For what a man soweth,
that must he also reap.) Will it not be a heap for
the fire of God`'s jealousy to take hold on,
in the day of their tribulation, anguish, and desperate sorrow of heart? Isa. 17:10-11.

[.numbered]
_Query 8._ In what light do men build up a wall inwardly,
and daub it with untempered mortar, to secure themselves from the wrath to come?
Is it not in the light of the fire and sparks of their own kindling?
Will any wall or defence built up in the light of this fire or sparks secure men?
Will not the wrath of God, in the day thereof,
break forth upon all the workers of iniquity,
whatever their faith or hope be to the contrary?
Will any wall defend the soul from the overflowing storm of wrath,
but the wall of God`'s salvation?
And can any enter within that wall, but the righteous nation that keepeth the truth? Isa. 26:1-2.
The name of the Lord indeed is a strong tower; but can any run into it,
and get shelter in it, but the righteous? Prov. 18:10.

[.numbered]
_Query 9._ Who is he, who, when he falleth, shall rise again;
and after he hath set in darkness, the Lord shall be a light unto him?
Is it not he that feareth the Lord, and obeyeth the voice of his servant,
that in the time of his darkness and distress trusteth in the name of the Lord,
and stays upon his God?
Yea, is it not such an one as is willing to bear the indignation of the Lord,
because he hath sinned against him, until he plead his cause,
and execute judgment for him?
Will not the Lord bring forth such an one to the light?
and shall not such an one behold his righteousness? Mic. 7:8-9.

[.numbered]
_Query 10._ When shall persons`' light arise in obscurity,
and their darkness be as the noon-day?
When shall their light break forth as the morning,
and their health spring forth speedily, and their righteousness go before them,
and the glory of the Lord gather them up?
And when shall the Lord be their continual guide, and satisfy their soul in droughts,
and make fat their bones, and make them like a watered garden,
and like a spring of water, whose waters fail not?
Are not these promises belonging to the gospel state?
And are they not fulfilled in the gospel state,
as people come to know and keep the gospel fast, and the gospel sabbath?
Read Isa. 58:6. to the end, and wait on the Lord, to receive understanding from him,
that in reading thou mayst understand.

====

Oh that men knew the gospel fast, and the gospel sabbath,
with the feasts of unleavened bread, tabernacles, trumpets, etc.
A little of the knowledge of the mystery of the hidden life and power, is of more value,
and would do their souls more good,
than heaps of literal knowledge wherewith the world is so filled.
The knowledge of God and Christ in the mystery is no less than life eternal,
in them and to them, who are taught in the new covenant,
or ministration of the power of the endless life, so to know them.
