== The Everlasting Gospel of our Lord Jesus Christ / And the Blessed Effects Thereof, Testified to from Experience

[.section-date]
1678

[quote.section-epigraph, , ]
____
"`The darkness is past, and the true light now shineth.`" 1 John 2:8
____

[quote.section-epigraph, , ]
____
"`Arise, shine; for thy light is come, and the glory of the Lord is risen upon thee:
for behold, the darkness shall cover the earth, and gross darkness the people;
but the Lord shall arise upon thee, and his glory shall be seen upon thee.`" Isa. 60:1-2
____

[quote.section-epigraph, , ]
____
"`When the Lord shall build up Zion, he shall appear in his glory.`"
Ps. 102:16. (indeed he doth so.)
____

THE blessed message which the apostles (who were
sent by Christ to preach the gospel) heard of Christ,
and were to declare to others was, "`That God is light,
and in him is no darkness at all.`" 1 John 1:5.

The end of Christ`'s sending them with this message was,
that thereby (preaching it in the evidence and demonstration
of God`'s Spirit) they might "`open men`'s eyes,
and turn them from darkness to light, and from the power of Satan to God,
that they might receive forgiveness of sins,
and inheritance among them that are sanctified by faith that is in him.`" Acts 26:18.

Now the eye of the mind being opened,
and the mind turned from the darkness within to the light within,
and from Satan`'s power to the power of God, which is revealed in the light,
the soul in the light comes to see (over the darkness,
and Satan who darkened it) the things of God and his kingdom,
as they are revealed in the light, which makes them manifest.

As, First, It sees him, who is the rock, the holy foundation of God,
the holy foundation of life in the soul, the living stone,
by which all the other living stones are made alive,
and they are taught of God to come to him as to a living stone,
and so are built upon him, and become God`'s building, and new creation in him. 1 Pet. 2:5.
2 Cor. 5:17. And here, in this light,
none can miss of the true coming, hearing the voice of the Father,
and being drawn and taught by him to come to the Son. John 6:44-45.

Secondly, Here the true Jew`'s state, the state of the inward Jew,
and the inward circumcision,
and the true worship (even the worship of the Father in Spirit and truth) is known.
For the Jew inward is a child of light, begotten in the light, redeemed out of darkness,
and dwells and walks in the light, as God is in the light. 1 John 1:7.
And the circumcision is not a fleshly act;
but the cutting off of that which is fleshly from
the mind by the Spirit and power of Christ.
And the gospel worship, or the worship of the Jew inward,
is the worshipping of God in the newness of the life of his Son.

Thirdly, Here is the true repentance from the dead nature and dead works,
which no man can attain to of himself; but is God`'s gift through his Son,
whom God hath appointed to be a Prince and a Saviour,
to give repentance and forgiveness of sins. Acts 5:31.
I say here, that repentance is known, waited for, and received.
For not to men in the darkness, and loving the darkness, is the true repentance given;
but to them that are turned to the light, to them is repentance given unto life. Acts 11:18.
compared with chap.
26:17-18.

Fourthly, Here the true faith, the precious gift of faith, is received,
whereby men believe in him who gives life, and receive life from him.
And this is the faith which gives access to God, and gives victory over the world,
and that which is contrary to God: the faith which is given in the light doth so;
but the faith which men have in the darkness doth not so.

Fifthly, Here is the cross of Christ known, which is an inward, living, spiritual thing,
effectually crucifying that man that takes it up, and daily bears it,
to all that is earthly and sinful;
and then the pure seed and life of Christ springs up in his earth, over the world,
and every worldly thing. Gal. 6:14.

Sixthly, Here the pure love springs in the heart, both to him that begets,
and to him that is begotten.
In the light there is nothing but love;
but in the darkness there is no true love to be found;
but the very love that is found there is of the nature of enmity.
It is the light of truth that purifieth the heart to the love unfeigned. 1 Pet. 1:22.
Duet. 30:6.

Seventhly, Here the Lamb`'s patience and meekness is experienced,
and the soul adorned with it.
The Lamb is the light of the world, and they that are made lambs by him,
partake of his sweet and meek nature, learning of him to be meek and lowly in heart,
and so have that patience and meekness from him which no other can attain to. Matt. 11:29.

Eighthly, In the light the precious promises are fulfilled and partaken of;
which make them who partake of them, and in whom they are fulfilled,
partakers of the divine nature; for the divine nature is not partaken of in the darkness,
but in him who is light.
Man (who is darkness) cannot partake of the promises
which belong to the children of light;
but when, by the operation of God`'s power, his state and nature are changed,
and he is now no more darkness, but light in the Lord,
then the promises which were made to the children of light he cometh to have a share in. Eph. 5:8.
2 Pet., 1:4.

Lastly, In the light the holy anointing is received, the voice of Christ heard,
and the new everlasting covenant, even the sure mercies of David, made with the soul. Isa. 55:3.
The law of the new covenant (even the law
of the Spirit of life in Christ Jesus) written in the mind,
and the holy fear of the new covenant, which cleanseth and keepeth clean,
put in the heart, and the blessed Spirit of the Father given and received,
which gives to those that receive it power to become the sons of God,
causing them to walk in his ways, and to keep his statutes and judgments, and to do them.
Oh, blessed dispensation of life and holy power,
which the Lord hath caused to break forth among a despised people in these latter days!
Oh that the sons of men would hear and understand
this precious lovingkindness of the Lord,
and put their trust under the shadow of his wings,
and know what it is to be satisfied with the fatness of his spiritual gospel house,
and to drink of the river of his pleasures, and in his light to see light! Ps. 36:7-9.

This opened in me this morning, in love and compassion towards the Papists.
My bowels have often rolled over them, and been pained concerning them,
to see how they are closed and shut up as to the
true sense and understanding of things of this nature.
Oh that they would prize the day of their visitation,
that they might hear the sound of life both from others, and also in their own hearts,
and the saving arm of the Lord might be inwardly revealed to them,
and they effectually redeemed thereby!

I am no disdainer of Papists, or any sort of Protestants, nay, not of Turks or Jews;
but a mourner because of their several mistakes,
and a breather to the God of my life for tender mercy towards them all.

Astrop, 13th of the Seventh month, 1678.

=== POSTSCRIPT

AND in this light the true church, the gospel church, the New Testament church, is known;
which is a church of the children of light, a building built in the light,
which church is in God the Father, and in the Lord Jesus Christ; 2 Thess. 1:1.
in whom they are built together for a habitation of God,
through the Spirit. Eph. 2:22.
Yea, in whom all the building, fitly framed together,
groweth into an holy temple in the Lord,
ver. 21. (for the Lord frameth them fitly together into a spiritual and holy building).
And all that are here gathered out of the darkness into the light, who walk in the light,
and abide in the light, are built upon the foundation of the apostles and prophets,
Jesus Christ himself being the chief corner-stone,
ver. 20. and are no more strangers and foreigners, but fellow-citizens with the saints,
and of the household of God, ver. 19.

The gospel church is the spiritual house of Jacob, which walk in the light of the Lord, Isa. 2:5.
who go up to the mountain of the Lord (to that which
is revealed to be the mountain of God in the last days,
even spiritual Mount Zion, Heb. 12:22), to the house of the God of Jacob,
where he teacheth his spiritual people, the inward Jews, of his ways,
and they learn to walk in his paths;
for out of this Zion shall go forth the law of the Spirit
of life in Christ Jesus (in the days of the gospel),
and the word of the Lord from this Jerusalem,
ver. 2-3. For Jerusalem which is above is free,
which is the mother of all the children which are born of God`'s Spirit. Gal. 4:26.
John 3:6. And she being the mother of them all,
nourisheth them all with the Word of life, which goeth forth from her;
and all her children know and justify her, their mother. Matt. 11:19.
Oh that all, both Papists and Protestants, knew this true mother-church,
this mother of all the living, of whom none but the living are born,
and who nourisheth all the living, and none else, with the law and Word of eternal life!

And if they knew the true church, the church which is of the true Jews,
the church of the first-born, whose names are written in heaven,
and did live and walk in the light of the Lamb, and follow the Leader,
the Shepherd of Israel, and faithful Bishop of the soul,
who overseeth and taketh care of the soul, they would learn,
and come to know and experience these things following:--

First, The dwelling-place of Mount Zion, and her assemblies,
and God`'s creating upon every of them a cloud and smoke by day,
and the shining of a flaming fire by night,
which is the defence upon all the glory that the Lord bringeth
forth among his spiritual church and people. Isa. 4:5.

Secondly, They would know the land of the inward Jews, and spiritual Judah,
and the song sung therein, because of the strong city which the Lord builds there,
and the salvation which he appoints for walls and bulwarks about it;
and would see and know how none but the inward Jews,
the inwardly circumcised and sanctified, even the righteous nation,
that keepeth the truth, can enter by the gates into that city. Isa. 26:1-2.
And they that dwell in that city, whose minds are stayed on the Lord,
and who trust in him, the Lord will keep in perfect peace,
ver. 3. Then Jerusalem is a quiet habitation indeed,
and the resting and feeding-places in it are sure. Isa. 32:18.
and chap.
33:15, 20.

Thirdly, They would know the feast of fat things,
which the Lord of hosts makes to all people that are here;
to all people that come up to and dwell on his holy mountain,
and serve and worship him in Spirit and truth.
The Lord of hosts maketh such a feast as no eye hath seen, nor ear heard,
nor can it enter into the heart of man to conceive what it is,
but only by the Spirit of God; even a feast of fat things,
even a feast of spiritual fat things, a feast of wines on the lees,
of fat things full of marrow, of wines on the less well refined. Isa. 25:6.
They that are turned to the light, and follow Christ the light,
shall not abide in darkness, but have the light of life; John 8:12.
shall be translated out of the kingdom
of darkness into the kingdom of the dear Son,
and they shall sup with Christ, and he with them,
and both together drink of the fruit of the vine of life new in the Father`'s kingdom.

Fourthly, They shall infallibly know here,
in this light which shines on God`'s holy mountain,
the destroying or swallowing up of the face of the covering cast over all people,
and the veil spread over all nations. Isa. 25:7.
For the veil is cast over and spread in the darkness;
but is done away and swallowed up in Christ, the light:
for the veil is done away in him. 2 Cor. 3:14.
And all that are in Christ, in his Spirit,
in the light and liberty thereof, behold as in a glass the glory of the Lord,
and are changed into the same image, from glory to glory, by the Spirit of the Lord.
ver. 17-18.

Lastly, Here the King of righteousness`' highway is known, even the way of holiness,
which the unclean cannot pass over; but the sanctified in the light do walk in;
and the wayfaring men here, though fools, do not err in. Isa. 35:8.
For they that are taught of God in the new covenant,
and follow the leading of his blessed Spirit, do not err.

Oh that the true church were known, which is now come and coming out of the wilderness,
leaning upon her Beloved, who led and leads her out thence,
into her own land of life and glory, where her light shines,
and she ariseth and standeth upon her feet before the Lord,
and the glory of the Lord shines upon her, and covers her!
Happy is the eye that seeth this, and the soul that hath a share in it!
