== Chapter I. Spiritual Knowledge

[quote.scripture, , John 17:3]
____
This is life eternal, that they might know you, the only true God,
and Jesus Christ whom you have sent.
____

I sought and traveled (from my childhood) after the true knowledge of God,
and of his Christ, and was satisfied with nothing that I ever could meet with.
But having at length (through the tender mercy of the Lord,
and guidance of his Spirit) met with it and been satisfied,
finding it to be the eternal life, the true food, the living power, the pure rest,
the joy and salvation of my soul,
I cannot help but testify of it to those that
spend their money on that which is not bread,
and their wages on that which does not satisfy.

We (some of us at least) have spent just as much of our money and labor as they^
footnote:[He speaks of professing Christians,
and more particularly their leaders and priests
who were educated in schools of higher learning,
and who held Quakers in contempt.]
who now despise us have done.
And some of us (I speak it in the fear of the Lord, and in a true sense,
without boasting) have had just as much of what they feed upon, and what they call bread,
as they have now.
Yet when the Lord brought us to the true balance, we found it not to be bread,
nor able to give the soul true satisfaction.
The true bread was not what we then called bread,
but was a bread which we had overlooked and not known.
For the eternal life which is hid with the Father, and is manifested in the Son,
and made known to the soul--this is true bread which does not perish.
Such bread will endure when all literal and outward knowledge of God fails and
falls short of satisfying the hunger of the soul which seeks the substance itself.

Now, it is my heart`'s desire to draw men`'s minds to a sense of truth,
to a sense of that which is the substance itself, that they might know the bread indeed,
know the living waters, come to them and drink,
and find Christ in them a well of water springing up to eternal life.
Therefore, it was in my heart to give forth the ensuing question,
and the inquiries that follow.
He that can rightly answer these questions must indeed know the substance.
But he that cannot answer may thereby discover that he does not rightly know,
and so may wait upon God to receive the knowledge of it,
and come to him for the eternal life which he freely gives.

The Jews were puzzled about the Messiah to come because of
their literal knowledge of the law and prophets.
Indeed,
they were kept from the true knowledge of him by their
own understanding of the prophecies concerning him.
Most sorts of men who now profess Christ are similarly
puzzled about a knowledge concerning the outward body,
flesh, and blood of Christ, according as they apprehend the Scriptures to speak.
Thus the veil remains over their hearts as well,
and they cannot see the eternal life and substance any more than the Jews,
but by their outward and literal knowledge they are kept back from the substance.

Now the breathing of my heart to the Lord is this:
to take away the veil from all hearts that sincerely desire the truth,
and to open the true eye in them,
that they may see the desire and beloved of their souls,
and be led by him into the true travel, out of self and towards the kingdom.
Oh that they may travel into the very land of the living,
where the food of life is fed upon and where the living springs flow.
There are the vineyards which we planted not, and dwelling places which we built not,
where the fruit of God`'s planting (the wine of the kingdom) is drunk,
even drunk anew in the kingdom with the Father and Son in the Spirit,
who are One and all there.

=== A Question to Professors of Christianity

The question is not whether they know what is said of Christ in the Scriptures,
but whether they know it savingly, truly, livingly, and powerfully.
Yes, they may know what is said of him,
and yet not know him of whom those things are said.
So it was with the Scribes and Pharisees,
for they knew what was said of Christ in the law and prophets,
but they knew him not when he appeared in that body of flesh.
So men may now know what the apostles and the evangelists have said
concerning his appearance in a body of flesh (concerning his birth,
circumcision, baptism, preaching, doctrine, miracles, death, resurrection, ascension,
intercession, etc.), and yet not know him of whom these things are said.
Yes, they may know what is said concerning the Word which was from the beginning,
and yet not know the Word, the power, the life itself.

Since the prevailing of the apostles`' testimony,
the way of the enemy has not been directly to deny Christ,
but to bring men into such a knowledge of Christ that does not save.
And as the enemy did acknowledge Christ when he appeared in that body of flesh, saying:
"`I know who you are,
the Holy One of God;`" so he has found it to his advantage (ever
since) to acknowledge that outward appearance.
This outward appearance he does not oppose,
nor men`'s knowledge and understanding of Scriptures that confirm them in this.
But the saving knowledge, the true knowledge, the living knowledge,
the powerful knowledge of truth--__that__ he always opposes;
for that alone overturns and destroys his kingdom in man,
and brings man from out of his reach.

Now there is a vast difference between knowing
the descriptions concerning a thing,
and knowing the thing described.
And there is also a great deal of difference between
believing the descriptions concerning a thing,
and believing in the thing which is described.

Spiritual things cannot be savingly known except by a union with them,
by a receiving of them.
A man can never truly know the Spirit of God by words that are said concerning it.
Rather, he must first experience something of it in order to truly know it.
So the peace, the joy, the life, the power--these pass the understanding.
Thus a man can never rightly know them by reading or
comprehending ever so much concerning them,
but rather by coming out of himself,
and traveling to where they are given and made manifest.
Only in this way may he come into acquaintance with them.
And if the peace which Christ gives, the joy, the life, the power,
cannot be known by literal descriptions, how could Christ himself,
who is the fullness of all, the fountain of them all, the treasury of all perfection,
in whom are hid all the riches and treasures of wisdom and knowledge--
how could he be known by outward and literal descriptions?

True knowledge is in a seed, in which man can receive a capacity of knowing,
and wherein the Father (from whom the seed came) does teach.
And this is his way of teaching us: by making us one with the thing he teaches.
In this way we learn Christ--by being born of him, by putting him on.
In this way we know his righteousness, his life, his wisdom,
his power--by receiving a proportion of them,
which gives an ability to discern and acknowledge the fullness.
And in this we receive the understanding of the Scriptures,
and know the seed of the woman (which bruises the serpent`'s head), by receiving the seed,
by feeling its growth in us, and its power over the enemy.
Then we know the thing itself.

Likewise, we know the woman that brings forth this seed after the Spirit,
which is the Jerusalem above.
And we know also, and singly acknowledge,
the seed that was brought forth outwardly after the flesh.
This seed we know to be the seed of Abraham, the seed of David after the flesh,
and the seed of God after the power of the endless life.
And we are taught of God to give the due honor
to each--to the seed of God in the first place,
to the seed of David in the second place.^
footnote:[Here Penington speaks of the two natures of Christ,
who was fully God according to the seed of God,
and fully man according to the seed of Abraham and David.]
There was the seed that wrought the thing, which seed was the life itself;
and the seed in which he wrought it, which was formed into a vessel like ours,
but without sin.
In this vessel the pure Lamb appeared in the pure power of life,
which kept the vessel pure;
and so he (who was to be the first fruits) had the honor above all his brethren,
being anointed with the oil of gladness above his fellows.

But we also are born of the same seed.
He is formed in us; we are formed of him; we are as well of his flesh and blood,
as he was of ours.
And by being thus formed, and feeling him grow up in us,
and receiving an understanding from him, and in him, thus we come to know him,
and to understand the words of Scripture concerning him.
By experiencing and knowing the Lamb in our vessels,
we know also what the Lamb was in his vessel.

Thus we know things in the certainty and demonstration of God`'s Spirit,
even in the light which shines from him, and in the life which he begets.
And we speak of things as they are, and as we feel them to be in the true life,
which the Spirit of Christ has begotten in us.
And we can truly say concerning the Scriptures that now we believe,
not so much because of the relation of things
concerning Christ which we have found in them,
but because we have seen and received the thing of which the Scriptures speak.
And we find this to be the very substance indeed, the very Christ of God,
the spotless one, the living garment of righteousness and salvation,
wherein God finds no fault, and in which the soul appears without blame before him.
And concerning this, can we speak words of its nature, words of its virtue,
words of its life, power, and righteousness.
These are words that the flesh cannot hear,
but he that is born of God does naturally acknowledge and understand.
Why so?
Because he knows the nature of the thing, and receives the words in the savor thereof.
Can life deny life?
Can the birth of life deny that which springs out of the same womb?
No, no.
The children which are born of wisdom do justify wisdom
in its several sproutings-forth and appearances.
But that which denies it is a birth after the letter,
a birth after the literal and outward knowledge of things,
a birth of man`'s comprehending wisdom.
This birth indeed reproaches and blasphemes the
incomprehensible wisdom in its incomprehensible ways,
and would restrain life to be what they can apprehend
or comprehend by the letter concerning it.

And this may be a great evidence to professors^
footnote:[The word _professor_ will be used throughout to
refer to those who _profess_ faith in Christ.
Here the word has nothing to do with teachers or educators.]
that they indeed do not know Christ in his nature, Spirit, life, and power,
because they do not speak of him as persons who experience the substance,
nor speak from the present sense and acquaintance with it,
but only as persons that bring forth a notion which
they have received into their understanding.
And yet they fail in this also,
for they speak not of Christ according as the Scriptures truly
present him (when compared one with another),
but only what they have grossly apprehended concerning him from some Scriptures,
even as the outward Jews did.

Now friends, if you have this living spiritual knowledge,
and if you hold it in him who is true,
then own and acknowledge it (as it is expressed in the Scriptures,
and as God has now brought it forth in his people),
so that you may manifest yourselves as being of him.
There is an understanding and wisdom of man,
and there is a witness of God which gives true judgment.
Man (at his best) judges only according as things appear to him from the Scriptures.
But the witness of God judges the things of God in the demonstration of the Spirit,
according as they are felt and known to be in him.

But if you do not have this spiritual knowledge,
but have long given out your money and labor for that which is not bread,
nor can yield the true satisfaction, then oh, come to the waters,
and receive that which is given freely, without money and without price!
Oh, sell all for the pearl, for the knowledge which is of life,
for the knowledge which is life! "`I am the way, the truth, and the life,`" said Christ;
to know this is eternal life.
So wait to feel the rock laid as a foundation in you, even the seed of God,
the life of Christ, the Spirit of Christ revealed in you, and your souls born of it,
and built upon it.
Oh that you could come out of your own understanding,
that you might feel and receive the love of my heart,
and know the travail of my soul for you--that you might be born of the truth,
and know and receive it as it is in Jesus, and as it is felt in the Spirit,
and its own pure power!

=== Christ Known Outwardly and Inwardly

Now a little further,
to remove the scruples and prejudices out of the minds of
those who at times have been touched with the power of truth,
and have had the witness of God reached to in their hearts,
but afterwards the enemy has raised a mist, and cast blocks in their way,
stirring up in them hard thoughts against us; I say,
to remove this out of the minds of the honest-hearted (who in
the guidance of God might chance upon this paper),
I shall open my heart nakedly: ^
footnote:[The following assertions are made in response to what was a common
(though false) criticism against Penington and the early Quakers, namely,
that they taught Christ to be only an inward life or light that worked in the heart,
but denied or neglected the outward work of Christ accomplished in His natural body.]

[.numbered-group]
====

[.numbered]
1+++.+++ We do indeed acknowledge that the Word of God (the only begotten
of the Father) did take up a body of the flesh of the virgin Mary,
who was of the seed of David, according to the Scriptures,
and did the will of the Father therein, in holy obedience unto him,
both in life and death.

[.numbered]
2+++.+++ That he did offer up the flesh and blood of that body (though not only this,
but he poured out his soul, he poured out his life) a sacrifice or offering for sin,
a sacrifice unto the Father, and in it tasted death for every man.
And it is upon God`'s consideration and acceptance of this
sacrifice for sin that the sins of believers are pardoned,
so that God might be just and the justifier of him who believes in Jesus,
or who is of the faith of Jesus.

[.numbered]
3+++.+++ What is attributed to Christ`'s body we do acknowledge in its place,
according as the Scripture attributes it,
which is through and because of that which dwelt and acted in it.
But that which sanctified and kept the body pure
(and made all acceptable in him) was the life,
holiness, and righteousness of the Spirit.
And the same thing that kept his vessel pure is that which now cleanses us.
For man was shut out from this living virtue and power by the fall;
but through the true knowledge of the death of Christ, the way is made open for it again,
and man is brought to it to be baptized, washed, cleansed, sanctified, fitted for,
and filled with life.

====

Now of this thing we might speak yet more clearly and plainly,
if men could hear our words.
But if we have spoken to you earthly things (in
parables and figures) suitable to your understanding,
and you believe not, how shall you believe if we speak to you heavenly things,
or if we tell you plainly of the Father, in whom is all the life of the Son,
and all the virtue and salvation that ever the Son had from him?
The Jews were to learn in types, figures, and shadows, till Christ came.
And after Christ came, he also taught them in resemblances and similitudes of things.
And the apostles wrote and spoke much to persons who were just coming out of that state,
in a language suited to that state.
But he that comes into the substance itself, and is taught there by the Spirit,
after he is grown up and made capable,
he is taught plainly the nature of the heavenly things.
Then the words of the apostles (concerning the deep
things of God) which are mysterious to others,
are manifest and plain to him.
Yes, the Lord teaches him things that words cannot utter.
The peace of God, the joy of his Spirit, the life and power of the Lord Jesus Christ,
his wisdom, righteousness, and pure, precious ways of sanctifying the heart,
the tender mercy, faithfulness, and rich love of the Father, etc.,
these are known in such a way as cannot be uttered to any man.
Indeed, they are not learned (nor could ever be learned) from words about the things,
but rather by the sense and experience of the thing itself.
The Lord (in whom are the depths of life,
and who gives the sense and understanding of the deep
things of the Spirit) opens these things in him,
and manifests them to him.

Indeed, this is the right and excellent way of knowledge: to come into union,
to come into the thing itself, to learn in the union, to see and know in the thing.
This is the way that the Lord teaches all his children in the new covenant,
by the inward life, by the pure light within, by the inward demonstration of his Spirit,
by the power and virtue of the truth itself.
And he that is in the Son has some measure of this life.
But he that does not have some measure of this life is not in the Son,
but only in a talk and a wise knowledge of things according to the flesh,
which will perish, and he with it who abides there.
For no man can be saved, but by coming into the knowledge which is of a pure, eternal,
living, saving nature.
Can an opinion which a man takes up concerning Christ from the Scriptures save him?
No, for it is no more than an opinion or judgment of man,
unless he be in the life and power of the thing itself.
Only then is it truth indeed to him, and right knowledge in him.
Otherwise it is but a false knowledge,
a knowledge that will not subdue his heart to truth, for its seat is not in the heart,
but rather in his head, making him wise and able there to oppose truth.
Such false knowledge brings man into a state of condemnation, wrath,
and misery beyond the heathen,
and makes him harder to be wrought upon by the light
and power of the truth than the very heathen.

Therefore, consider your ways O professors of Christianity!
Do not despise the hand which is stretched forth to you in the love of God,
and in the motion and guidance of his Spirit, who condescends to you exceedingly.
Let him reach to his own in you and scatter your apprehensions, imaginations,
and conceivings about the meanings of Scriptures (which
are like many chains of death and darkness upon you),
so that you might come to him in whom is life,
and who gives life freely to all who come to him.
Oh, observe what iron bars were in the way of the Scribes and Pharisees!
They would not come to him that they might have life; indeed,
they could not as they stood.
Yet there are greater bars in your way; yes,
it is harder for many of you to come to him than it was for them.
My upright desire to the Lord for you is that he would
remove the stumbling blocks out of your way,
that he would batter and knock down the flesh in you,
and that he would strip you of all your knowledge of Scriptures according to the flesh.
Only then will you be capable of knowing and receiving things according to the Spirit.
Only then will you know how to understand, honor, and make use of the Scriptures also.
But until then you cannot help but make use of them both
against your own souls and against Christ and his truth.

Now, having certainly felt and known the thing in our own hearts,
and having also seen the snares and nets which the enemy lays for you,
whereby he keeps you from the true bread,
and from the water and wine of the kingdom (even as he kept us formerly),
how can we hold our peace?
How can we help but witness to you (in the love and
drawings of the Spirit of the Lord) of the truth,
life, and power which we have felt in Jesus, even if by doing so you become our enemies?
It is not our desire or end to bring you to another opinion or outward way,
but rather that you might feel the thing itself, and know assuredly what is the truth,
and abide in that which was never deceived itself, nor ever deceived any.
Oh, why should you wander in the dark opinions and uncertainties of the night?
Why should you not rather come to that wherein the light of the day springs,
and out of which it shines?
Can the natural man (who has his eyes) be deceived about the light of the natural day?
Does he not recognize and know the light of the day both from
the light itself and also from the darkness of the night?
Ten thousand times more certain and inwardly
satisfied is he who is born of the spiritual day,
brought forth in the light thereof, and who spiritually sees, lives, and walks therein.
Indeed, there is no doubt in him who is grown up into the thing;
for he has the assurance of faith (which is far
above the assurance of outward sense or reason),
and the assurance of understanding.
Oh blessed is he who has an eye to see, an ear to hear, a heart to understand,
the things which God has revealed by his Spirit in this our day,
the living way which he has now made manifest,
the seed of life that he has raised out of the grave of death.

But he that reproaches and speaks evil of this
light (who will neither enter in himself,
nor allow others), he is far from receiving the blessing or blessedness of this seed.
Such a man grows up in the wrong nature and spirit,
the spirit whose end is to be burned along with all
that is in union with it and grows up from it.
Therefore, come out from that spirit;
come out of that dark mind and nature which never saw, nor ever can see the truth,
but sets up opinions and appearances of things instead of it.
Come receive the anointing which is given with and in the seed, which is raised in some,
and visited in many, in this day of the Lord`'s love and tender mercy.
Come to him to whom the living, the sensible, the redeemed sing praises,
and on whom they wait for the further manifesting of
his power and glory in them daily more and more.

Now friends, if you will know aright, or believe aright,
you must know and believe in him who was with the Father before the world was,
who was the Savior, the Jesus, the Christ, from everlasting.
For what makes him so?
Is it not the power of salvation in him?
His taking up a body made no alteration in him, added nothing to him;
only it was necessary that he should take it up to fulfill the will of God in it,
and to offer it up as a sacrifice in his own life and Spirit to the Father.
This we firmly believe!
And yet we cannot help but say further that the virtue, the value, the worth,
the excellency of what was done by him in the body was not _of_ the body,
but it was in him before time, in time, and will be after time, and forever.
Yes, it is he to whom the name Jesus and Christ did rightly belong before he took up the body.
And he put forth in the body the saving virtue which he had before,
which belonged to the nature, to the anointing in him,
whether he had ever saved any with it or not.
And this virtue, this life, this Spirit, this nature of his, is the food,
the righteousness, the garment of life and salvation,
which he (through the death of the body) made and
prepared a living way for the soul to come to,
to feed on, and be clothed with.

I can hardly stop speaking of these things for your sakes,
that through my words you might come to feel that which
is able to give you the holy understanding.
Oh that you might come to the true sense and experience of the truth itself,
and might see who has blinded you, and how he has blinded you,
and fed you with husks and dry food, instead of that which has the true living sap in it.
But while you see and judge in that which is wrong,
you must of necessity judge amiss both of yourselves and others.
You cannot help but judge wrongly the truth itself,
and the words spoken concerning it (either formerly or now).
And in this way you expose and bring yourselves
under the righteous judgment of the truth itself,
even of the Son, and the light of his day,
which has power from the Father to judge all false appearances, deceits, and deceivers.

=== Rejecting the Inward Appearance of Christ

It has pleased the Lord,
as he manifested his Christ gloriously before the apostasy, so to manifest him again.
For he was not only born (in the flesh) of the virgin Mary;
but he was also born in the Spirit of the woman clothed with the Sun,
which had the moon under her feet, and on her head a crown of twelve stars.
She also brought forth the man-child, who was to rule all nations with a rod of iron.
Rev. 12.

Now of this appearance and return of the Lord Jesus Christ,
and of the fresh bringing-forth of his life and power in his body, the church,
there are many witnesses who have seen, felt, and tasted thereof,
with the eyes and senses which are of God, and of the new birth.
And of this, in the love and goodwill of God,
and from the drawings and requirings of his Spirit,
they bear witness to others that they also might
come to see the glory and brightness of his day,
and rejoice therein.
For indeed it is a glorious day inwardly in Spirit to those that are
made alive and gathered to the living Shepherd and Bishop of the soul,
by the eternal arm of his power.
And happy is the eye that sees the things that they see,
and the ear that hears what they hear,
and the heart which understands the things which
God has revealed in and unto them by his Spirit.

Glorious was the appearance of Christ in the flesh,
but there were blocks in the way of the Jews so that they could not know, acknowledge,
believe, and receive him.
And glorious is the administration of his life in the Spirit in this day of his power,
but there are now also blocks lying in the way of those to whom he is sent,
which cause them to stumble and not give up to him or let him in.
But blessed was he who was not offended at Christ then,
and blessed is he who is not offended at him now.
For he that is offended at him who is life, and gives life,
and so stumbles at the present way by which God has chosen to give life,
how shall he live?
This is the cause that so many poor hearts lie mourning and groveling on the earth,
groaning because of their sins,
fearing because of the strength of the enemy and the corruptions of their
own hearts which are continually ready to betray them into his hands.
These do not know the one who has stretched out his arm,
and has come in his power to deliver,
but indeed are prejudiced against the way wherein he has and does deliver.
Truly, they know not the voice that calls, "`Come unto me;
I am the resurrection and the life.
He that believes in me shall receive my strength; and though he is ever so weak,
shall become as David.
And though he is ever so unclean,
he shall find the waters that spring from my well to cleanse him,
and nourish him to life everlasting.`"

How tenderly did Christ visit the Jews in the days of his flesh!
How powerfully, and in the true authority of God, did he preach among them!
What mighty works did he show!
And yet they could not believe.
Why so?
The enemy had entered them with his temptations,
had got something into their minds of a contrary nature so to keep out the sense,
knowledge, and acknowledgment of him.
So that when their hearts were even overcome with his power, and his sweet,
precious doctrine, and were ready to yield that he was the Christ indeed,
then the enemy raised up some argument or other to prejudice them against
him and drive them back again from acknowledging or receiving him.

"`This man is not of God,`" say some; "`for he keeps not the Sabbath.`"
He cannot be a prophet, say others, because "`he is of Galilee,
out of which no prophet arises.`"
He "`cannot`" be Christ, says a third sort, because "`we know where he is from;
but when Christ comes, no man knows where he is from.`"
He is not holy, strict, and zealous according to the law, say others; but a loose person,
"`a gluttonous man, and a wine-bibber, a friend of publicans and sinners.`"
He does not teach his disciples to fast and pray, as the Pharisees did theirs,
and John (who was generally looked upon as a prophet) did his.
He justifies them in plucking the ears of corn on the Sabbath day,
and thereby he encourages them to break it,
rather than strictly to observe and keep it according to God`'s law.
He is a "`blasphemer,`" say some, "`making himself equal with God.`"
He reproaches the most strict and zealous men that we have,
even our teachers and interpreters of the law and prophets, calling them "`hypocrites,
painted sepulchers, blind guides,`" etc., and pronounces woe upon woe against them.
And those that are the children of Abraham he calls the children of the devil; and says:
"`He that commits sin is the servant of sin; but if the Son makes you free,
you shall be free indeed.`"
And if we will have life in us, we must believe in him, and eat his flesh,
and drink his blood.
(Did ever Moses or any of the prophets teach such doctrine?) Again he says:
"`If a man keeps my sayings,
he shall never see death;`" whereas Abraham and the prophets,
who believed God and kept his sayings, are all dead.
This made them even conclude that he had a devil. John 8:52.
So how could they understand him when he said he was "`the good Shepherd,
and the door,`" etc.,
and "`that all that ever came before him were thieves and robbers;`"
would they not look upon this as witnessing of himself,
and endeavoring to set up himself?
And when he said: "`Verily, verily, before Abraham was,
I am;`" were they not ready to stone him for speaking a
false and impossible thing (as it seemed to them),
he being not yet fifty years old?
And then for his miracles, having beforehand concluded that he was a bad man, a sinner,
a breaker of the Sabbath, a blasphemer, a deceiver of the people, etc.,
how easy was it for them to harden themselves against them,
and to infer that he wrought these things by the aid and assistance of the devil.
Indeed many were the arguments (and some seemingly strong and unanswerable)
which the wisdom and understanding in them formed against Christ,
whereby they justified themselves in their refusal of him.

These things are past,
and can be easily condemned by those who are now acting in the same spirit.
The same spirit, under a new guise,
still opposes truth in its present appearance and dispensation,
and stirs men up to slight and blaspheme that holy name and
power (by which they that believe are saved and sanctified).

Well, what shall I say to you?
Oh that you could discern spirits!
Oh that you could see what spirit you are of, and whom you serve,
in opposing God`'s present dispensation of life!
Oh that you could see how you read Scriptures outside of that light which wrote them,
and bend them against him that wrote them!
Thus you make yourselves wise and strong in a
wrong wisdom and knowledge against the Lord,
and against his Christ, whom he has set upon his holy hill of Zion,
and who appears there (though you do not see it).
For Zion is not now natural, or after the flesh (for the day is come,
the shadows are gone).
Rather, Zion is the holy hill of God in Spirit,
upon which the heavenly Jerusalem was built, which is revealed, come down,
and coming down from heaven, and many of the heavenly citizens dwell there already,
and more are coming there to dwell.
For even from the east, west, north,
and south they shall be gathered to sit with Abraham, Isaac, and Jacob,
in the kingdom which cannot be shaken.
This kingdom was received by the Christians formerly (before
the apostasy) and is now received again.

=== Christ Who Died at Jerusalem

We, who are commonly called Quakers,
are a people whom the Lord has gathered out of wanderings, out of many professions,
out of several scattered estates and conditions,
and into a measure of the eternal rest where we have found that life, power,
and manifestation of the eternal Spirit,
with which we were never before distinctly acquainted.
And now, having tasted of this, having known this, having felt this,
and come to a real enjoyment of it (in some degree, according to our several measures),
we could not possibly conceal this treasure.
Rather, in the movings of his life and the power of the Spirit,
we have been drawn to testify of it to them who are left behind,
still groveling under the burden of corruption,
and crying out because of the sin and bondage.

Now this we have often found:
That our testimony has not been received in the
same Spirit and love wherein it has gone forth.
The enemy, by his subtlety, has raised up prejudices against us,
as if we denied the Christ that died at Jerusalem; professing him only in words,
but denying him in reality and substance.

To clear this matter, we have solemnly professed, in the sight of the Lord God,
these two things:

_First,_
that we do really in our hearts acknowledge that Christ who came in the fullness of time,
in that prepared body, to do the Father`'s will (his coming into the world, doctrine,
miracles, sufferings, death, resurrection, etc.),
according as it is expressed in the letter of the Scriptures.

_Secondly,_ that we acknowledge no other Christ than that,
nor hold forth any other thing for Christ, besides him who then appeared,
and was made manifest in flesh.

Now then, it should be inquired into by professors,
what is the reason that their prejudices still remain concerning us.
For certainly if they did know and acknowledge the same thing with us (in the Spirit,
and in the power, life, and love which are of the truth),
this prejudice and these hard thoughts could not remain.
But if they themselves do not know Christ in the Spirit
(but only according to a description in the letter),
it is no wonder that they miss both the Spirit
and the true intent and meaning of the letter.

And indeed the Lord has shown me in Spirit several times,
that they themselves are guilty of that very charge which they cast upon us,
even of denying that Christ which died at Jerusalem.
For he that knows the words of Scripture according as he
apprehends or conceives them in the reasonings of his mind,
does not wait to have them revealed in the Spirit.
Such a one sets up his own conceivings, reasonings, and imaginations,
or an image in his mind concerning the things of the Spirit,
but misses the thing itself.

Now, no man can in truth call Jesus the Lord except by the Spirit.
However, any man that is somewhat serious, and weighs the Scriptures in the natural mind,
may so learn to acknowledge his coming into the world, and that he is Lord and King,
etc., and may thus call him Lord.
Indeed such a man may kindle a great heat in his
affections towards Christ (though without the life,
without the Spirit),
yet all this is but an image which man forms in his mind from
his reading the Scriptures and from his own observations.
But the true calling Jesus Lord is from the
experience of his eternal virtue in the Spirit,
and from finding the Scriptures being opened to him by the Spirit,
and in a seed which is above the reason, comprehends the reason,
and confounds and brings it to nothing.

Again, there is no true knowledge of Christ, no living knowledge,
no saving knowledge, no knowledge which has eternal virtue,
except that which is received and retained in a
measure of light given by God to the creature.
Such knowledge is held in the faith which is a gift,
in the grace which is supernatural and spiritual;
whereas the reasoning part is but natural.
And those who have received the spiritual understanding
know it to be distinct from the natural.
Moreover,
we experientially find a very clear distinction between Scriptures searched
out by the reasonings of the mind (and the practices drawn therefrom),
and Scriptures opened by the Spirit, and felt in the life.

Now,
professors generally have not received their knowledge of Christ from the Spirit,
or from Scriptures opened in the Spirit (and so do not know the thing itself,
but only a description of the thing which man`'s reasoning part
may drink in from the letter of the Scriptures).
This is manifest in that they are not able (in spirit and understanding) to
distinguish the thing itself from the garment wherewith it was clothed,
though the Scriptures are very clear in this.
Speak of Christ according to a relation of the letter, and there they can say something.
But if you speak of the substance, of the very spirit of the thing,
there they stutter and stammer and show plainly that they know not what it is.

Now the Scriptures do expressly distinguish
between Christ and the garment which he wore;
between the one that came and the body in which he came;
between the substance which was veiled, and the veil which veiled it.
"`Lo! I come; a body you have prepared me.`"
There is plainly he, and the body in which he came.
There was the outward vessel, and the inward life.
This life we certainly know, and can never call the bodily garment Christ,
but rather that which appeared and dwelt in the body.
Now if you indeed know the Christ of God,
tell us plainly what that is which appeared in the body,
and whether that was not the Christ before it took up the body,
after it took up the body, and forever.

O friends!
Look to your knowledge of Christ, and to your faith and knowledge of the Scriptures,
and to your prayers also!
For it is easy missing the living substance in all these, and meeting with only a shadow.
The shadow may please the earthly part,
and make a great show in the natural understanding and affections,
but it does not satisfy the soul that is born after the Spirit,
which still cries out (where the soul is awakened) after truth, substance, life,
virtue from God`'s Spirit.

=== A Faithful Guide to the Path of Truth

There must be something let down from God into a man`'s
heart to change his heart and redeem it to God,
or he cannot be saved.
He must receive a seed, be born of a new and incorruptible seed,
or he cannot be renewed from his corrupt nature and state.
He must be born of water and God`'s Spirit, or he cannot enter into God`'s kingdom.

Now this is the true religion: namely,
to experience and be subject to that power which redeems to
God and breaks the power of the wicked one in the heart,
first casting him out,
and then taking possession of the vessel and filling it with the holy treasure.

[.discourse-part]
Question: But how may a man meet with such a thing as this?

[.discourse-part]
Answer: The Scripture, which gives a faithful testimony concerning the truth,
says that Christ, the Word of faith which the apostles preached, is near.
Therefore, a man need not say, '`Who shall go up or down to fetch it?`'
For, "`The word is very near you, in your mouth, and in your heart.`"
This is that Word which reconciles to God,
cutting down and slaying the enmity by the power of the cross,
and bringing up the seed.

[.discourse-part]
Question: But how shall I know and receive this?

[.discourse-part]
Answer: There is a seed given to the heart which is contrary to sin, which discovers sin,
which witnesses against sin, and is drawing the mind away from it,
furnishing those with a new and holy ability who wait upon the Lord in it.
Now he that minds this seed, hearkens to it,
turns from what it shows to be evil (in its pure, unerring light),
follows what it shows to be good (in the will, strength, and ability which is of it),
this one truly receives it.
And then, by waiting upon it, and becoming daily subject to it, he shall grow up in it,
increase in the knowledge of it and acquaintance with it,
and receive of it daily more and more.
Thus the man whose way was vile, whose heart was formed in wickedness,
filled with corruption, and daily bringing forth sin and fruits unto death,
shall find these things
(by the pure light and holy instructions of life)
daily purged out of him.
And he shall find Christ formed in him,
and the holy fruits of righteousness brought forth
through his vessel by the power and Spirit of Christ,
to the glory of God the Father.

And then, being in Christ, being in the seed of his life and acting therein,
there is peace in the soul, rest from its enemies and God`'s judgments,
and acceptance with the Father in what the soul thus is and works.

Then the world will persecute and hate exceedingly, because this soul,
who thus submits to God, and is thus changed by him, is not of the world,
but of the Father, who begat it in Christ, and formed it in his image and likeness.
But let him that once puts his hand to the plow (beginning to feel something of God,
and becoming subject unto it,
and tasting of the peace and pureness of it) never look back to the world,
nor mind the temptations and oppositions he will meet with from that nature and spirit,
either in himself or others.
For if he does, he will never be able to travel on,
but rather will consult with flesh and blood, and so return back into Egypt.
There he will lose the crown which is laid up
for those who pass on through the wilderness,
through the trials, through the temptations and various exercises,
to their journey`'s end.

This is the path of life in brief,
and happy is he who experiences the one who guides into it,
and faithfully follows him therein unto the end.
But there is another question that springs up in my heart, which is this:

[.discourse-part]
Question: How may a man come to have his sins washed away by the blood of Christ?

[.discourse-part]
Answer: By coming into the light, and walking in the light which discovers the blood,
and wherein alone it is sprinkled by God, and felt by the soul;
there he may receive the cleansing which is by it.
This is according to the testimony of Scripture; 1 John 1:7, "`If we walk in the light,
as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ, his Son, cleanses us from all sin.`"
By the light the darkness is dispelled,
and in the light the corruption and filth is washed away by the blood,
and the soul (mind and conscience) is cleansed from it.

"`This then is the message that we have heard of him, and declare unto you,
that God is light, and in him is no darkness at all.`"
ver. 5. What then?
Then those who will know God, and walk with God,
must (by the virtue of his truth) be turned from darkness to light,
and from the power of Satan unto God,
as in Acts 26:18. And in that light he shall meet with the Father,
and with his Son Jesus Christ, and have fellowship with them, ver. 3,
and shall be washed (both with the water and with the blood)
and kept clean and pure thereby in the sight of God.

[.discourse-part]
Question: But how shall I come into the light, and how may I walk therein?

[.discourse-part]
Answer: Christ is the light.
He is the light of the world, the light of men, the light of life.
You need not say in your heart,
"`Who shall go up to heaven, or down into the deep, for him?`"
For he is near, in your mouth, and in your heart.
This is the word of faith, which you are to believe in, love, and obey, that in the love,
faith, and obedience thereof, your heart may be circumcised, and you may live.
This is the gospel of our salvation, even this Christ, this word, this light, this life,
which redeems from sin, which destroys the destroyer,
and sets the soul free to serve and live to the Lord.
This was the message the apostles had to deliver in their day,
as in Rom. 10:8. And this was Moses`' message too,
when he spoke concerning the new covenant.
For Moses did not only deliver the old covenant, but he also spoke concerning the new,
even another covenant than that of Mount Horeb. Duet. 29:1.
And the word of this other covenant was
not the law written in tables of stone,
but the word near in the mouth and heart. chap. 30:14.

Now, every man that will be sanctified, and inherit God`'s kingdom,
must be born of the will of God.
He must deny his own will
(as Christ did, saying, "`Not my will, but yours be done`");
that will must be crucified.
He must suffer in the flesh, die to the flesh,
and live in and to the holy nature and Spirit of God.
By hearing the word that is near in the mouth and heart, and becoming subject to it,
a man comes to be born of the pure will.
This cuts down his own will day by day, and brings up the will and nature of God in him,
through which he is changed and sanctified, and becomes a new creature.
For the old creature is made up of the old understanding and will;
but the new creature is made up of the new.

"`How shall a young man cleanse his way?
By taking heed according to your word,`" said David.
What word was that?
Was it the word of the old covenant, or the word near in the mouth and heart?
And "`your word,`" says he, "`is a lantern to my feet, and a light to my path.`"
What word was that, the word of the first covenant, or the word of the second?
"`The law of the Lord is perfect, converting the soul.`"
What law is that?
"`The testimony of the Lord is sure, making wise the simple.`"
What testimony is that?
"`The statutes of the Lord are right, rejoicing the heart.`"
What statutes are they?
(Were not the statutes of the old covenant heavy and
burdensome?) "`The commandment of the Lord is pure,
enlightening the eyes.`"
What commandment is that?
Oh that men could read!
Oh that men could see the thing which is pure, and makes pure; which is righteous,
and makes righteous!
After men have seen the thing, there is a great way to travel to it;
but how far off are they who do not so much as see it,
but are in the darkness and prejudices of that nature and spirit which is contrary to it!

Now if the Lord, in his tender mercy and love to your soul,
brings you to a sense of this thing, and you begin to feel this precious,
searching word discovering any evil to you, either in your heart or ways,
oh do not dispute!
Do not reason against it!
Rather bless the discoverer, bow to the Son, become obedient immediately,
faithfully following the Lamb therein, lest he remove his light from you,
and allow darkness and the disputing wisdom to overtake you.

Christ is not of the world, and he leads out of the world, out of its vanities,
ways, customs, fashions, etc.
A man cannot serve Christ and the world.
Can any man be born of the Father, be begotten by him out of the spirit of the world,
and yet live in that, walk in that, which is not of the Father?
Can a man be born of God and yet still live in that which is of the world,
which came from the worldly part, is of the worldly part,
nourishes and pleases the worldly part in man, but pleases not the Father?
Can that man who is not of the world, but truly of the Father,
do anything that upholds the lust of the flesh, the lust of the eyes,
or the pride of life, either in himself or others?
Does not the Spirit of the Lord, where it is hearkened to, draw out of these,
and out of all things which are of these?
Therefore, consider well what it will cost, and how hard it is to follow Christ,
so that you who desire to be the Lord`'s may receive
help and strength from him to be faithful,
that in his strength you may overcome all that stands between you and life.

=== Some Assertions Concerning the Seed and Way of Life

[.numbered-group]
====

[.numbered.emphasized]
1+++.+++ That it is a great and hard matter to come into
a capacity of knowing and receiving the truth.

[.small-break]
'''

It is no hard matter to take up any religion that a man finds in the world.
To read Scriptures and believe what is found related
there (according to man`'s understanding of them);
to believe that he has the light and help of the Spirit in his reading and understanding;
to apply himself also to practice and observe what he believes required;
and to aim at holiness, etc.--this is no hard matter.
Every man that is serious, and who seeks religion of any kind, may go this far.
But all of this administers not the true capacity of knowing and receiving the truth,
and he that desires to find it must go further than this.

[.numbered.emphasized]
2+++.+++ That which gives the true capacity is a seed of life from God,
and there alone and nowhere else, can man meet with it and receive the truth.

[.small-break]
'''

This seed is the seed of the kingdom, or heavenly leaven,
with which the mind must be in some measure leavened,
before it can come into a true capacity of understanding and receiving the truth.
And in this leaven it must abide and grow up,
if it is to abide and grow in the true knowledge.

[.numbered.emphasized]
3+++.+++ That from this seed, and in this seed, are all things given.

[.small-break]
'''

Not only are the true light and knowledge of the Lord
Jesus Christ given and received in this seed;
but also the true faith, the true love, the true sanctification, the true justification,
the true peace, the true joy, etc.
And whatever of these is not received and held here, is not of the truth,
but a garment of man`'s own forming, and not the covering of the Spirit.

[.numbered.emphasized]
4+++.+++ That the Spirit himself sows this seed, and is received in this seed.

[.small-break]
'''

He that receives this seed, and is born of this seed,
receives and is born of the Spirit.
He that receives it not, nor is born of it,
neither has received nor is born of the Spirit,
but remains in imagination and self-conceit about the things of God,
and is not in the truth as it is in Jesus.

[.numbered.emphasized]
5+++.+++ That in this seed the new covenant is made with the soul and entered into.

[.small-break]
'''

He that receives this seed from the hand of God, receives life,
and enters into the covenant of life,
and feels the pure fear wherein God cleanses the heart,
and whereby he keeps the heart clean.
Here the soul feels the laws of God daily written by the finger of God`'s Spirit,
and feels the power and sense of the Spirit to teach and cause obedience.
Thus the yoke,
which is hard to the transgressing nature (being alienated from the life and power),
is easy (and I may say natural) to him that is born of this nature.
For being dead with Christ, and risen with Christ,
and changed into the nature of Christ (by the seed which is of him),
he can say as Christ did (by the same power and Spirit of Christ which works therein):
"`Lo, I come; it is my food and drink, yes, my great delight, to do your will, O God!
Indeed, your law is written in the midst of my heart!`"

[.numbered.emphasized]
6+++.+++ Among those who are gathered into this seed, and abide in the sense,
light, and life of this seed, there is great love and unity.

[.small-break]
'''

They are of one mind, of one heart, of one soul, of one spirit, of one life,
gathered into one demonstration of truth.
And there is no jarring, no doubting, no dissenting, etc.
All this is out in the world, in the earthly wisdom,
in the earthly professions and walkings; but it is excluded from the seed of truth,
and from those that are gathered into and abide therein.

[.numbered.emphasized]
7+++.+++ That all who are not gathered into, nor walk or live in this seed,
they are yet in the darkness and err from the pure power of God.

[.small-break]
'''

These stand and walk in slippery places;
and though their way may seem very right,
and their state and condition sure (with regard to God) in their own eyes and judgment,
yet it is not really so; but they are in but a dream concerning the truth,
and not in the truth itself.
And however strange such an affirmation concerning them may seem to them at present,
yet they shall certainly feel it to be so afterward,
when the Lord by his powerful voice and bright appearance of his Spirit awakens them.
For many things pass for truth now with men in the dark,
which things will vanish like smoke before the light of the day.
And then,
only that which is truth indeed shall have the glory and praise of being accounted so.
And what then will become of those who mistook the truth,
and are not clothed with the pure wedding garment (the
spotless life and righteousness of the Son)?

[.numbered.emphasized]
8+++.+++ That to those who see in the light of this seed,
the mountain of the Lord`'s house is discovered.

[.small-break]
'''

Those who abide and grow up in the mountain of the Lord`'s
house know and experience it established above all mountains,
and exalted above all hills--all earthly knowledge, earthly religions, earthly ways,
earthly worships, earthly spirits and minds, etc.
All of these, in their greatest exaltations and glory, are far beneath it.
And on this mountain is the feast of fat things and wines well refined,
even the fruit of the vine which makes glad and refreshes the very heart of God.
For the Father, and the Son, and the Spirit are here revealed,
in the holy house and tabernacle which are built here.
And here they make their feast, bringing forth the riches of their nature, spirit,
and precious life, on which they feed with the soul,
and give unto the soul favor and ability to feed with them.
For in this food there is the life, strength, righteousness,
and joy of the kingdom given forth and received.

[.numbered.emphasized]
9+++.+++ That it is this very seed in the heart which discovers iniquity,
reproves it, witnesses against it, and strives with the mind to turn it from it,
and to wait for life and power from on high.

[.small-break]
'''

In that seed is the divine nature, even the nature of God`'s Spirit,
which was always against sin, and ever will be so.
In all its appearances it testifies against it,
and in love to the creature strives to convince it of that which is contrary to God,
and to draw it to that strength and divine virtue which stops it, beats it back,
and works it out of the mind and nature of the creature.
For there is no salvation but by the cross and yoke of our Lord Jesus Christ.
In that cross is the power to crucify the affections
and lusts which lead into sin and death,
and will not cease to tempt and lead aside till the soul be
gathered into unity with that which is contrary to them.
So that this is the main thing in religion:
even to know Christ revealed in the soul as a standard against corruption,
and to be gathered under his banner, which is the cross.

[.numbered.emphasized]
10+++.+++ That the true and certain way of knowledge of the
things of God is in the faith and obedience of this seed.

[.small-break]
'''

It is not by reasoning and considering things in the mind (after the
manner of men) that a man comes to know spiritual things;
but only as they are spiritually revealed by God, after a spiritual manner,
to the believer and obeyer.
They are revealed to him in his believing, in his obeying, in his waiting,
in his holy fearing, in his distrusting of himself,
and feeling his own insufficiency either to attain them or retain them.
They are known only as the Lord God makes them manifest
in the believer and preserves him in the sense of them.
"`He that does my will shall know of my doctrine,`" says Christ.
This is the way.
Do you desire to know what God requires of you, whether this or that be so or not?
Mind this seed in you!
Mind the pure and holy light, the inward touches and leadings of this pure, divine seed!
This will make manifest to you whatever is fit for you in your present state to know;
and you are not to desire more,
but as a child are to rest contented with that portion of knowledge
and strength which the wise and tender Father judges fit for you.
And as your state grows capable of more, he will not fail to administer to you.
What he gives you is good, seasonable, and proper for you,
which you may safely feed upon and enjoy in the sense and fear of him.
But if you press after what he would not as yet have you know,
you will enter into the will and wisdom of the flesh.
Here you will find disputes, discontents, murmurings,
ill tempers and dispositions of the mind,
which will increase and grow upon you to your hurt.

====
