== Chapter III. The Holy Truth and People Defended

The following is an answer to the chief passages of a letter, written to me,
and replied to by me,
before my imprisonment at Reading Jail (where I
have been a prisoner above a year and a half,
without any law broken, or cause given on my part).
I am engaged in spirit to reply something to it,
and to give forth to others what the Lord has given to me.

[.discourse-part]
Objection: He objects in his letter that we deny redemption by the blood of Christ.

[.discourse-part]
Answer: Oh how will he answer this charge to God?
For none do so rightly and fully acknowledge redemption
by the blood of Christ as the Lord has taught us to do!
For indeed we acknowledge the blood of the Lord Jesus Christ both outwardly and inwardly;
both as it was shed on the cross, and as it is sprinkled in our consciences.
And we know the cleansing virtue of it in the everlasting covenant,
and in the light which is eternal, outside of which light men have only a notion of it,
but do not truly know nor own it.

[.discourse-part]
Objection:
He charges that justification is a single act of grace passed upon man by God freely,
which act pronounces him to be righteous.

[.discourse-part]
Answer: He that truly experiences salvation in Christ Jesus,
witnesses it to be a continued act of grace.
Grace appears to the soul, grace teaches, grace enables,
grace makes a change from the ungraciousness of the heart and state.
And then grace (or God by his grace in and through Jesus
Christ) forgives the sins that were committed before.
For though the Lord visit me with life, quicken me thereby,
make a change in my heart and state, yet it is still his mercy to accept me,
and to pass by (for his name`'s sake) my former debts and trespasses against him.
Indeed, the new covenant is wholly a covenant of grace and mercy.
The giving of Christ, the drawing of the mind to him,
the accepting and justifying which are in him, etc., these are works of grace and mercy.
So the spiritual Israel may rightly sing this
song in the land of holiness and redemption,
"`O praise the Lord! For he is good, and his mercy endures forever.`"

[.discourse-part]
Objection: He asks, do we think to satisfy the law by our obedience?

[.discourse-part]
Answer: We do not look upon the law of Moses, which was given to the outward Jew,
to be the dispensation of the new covenant,
or to be the law of the Spirit of life in Christ Jesus.
But indeed,
the righteousness of the law is fulfilled in those who are in the new covenant,
and who have God`'s law written in their hearts,
and his fear put there (which preserves from departing from him),
and his Spirit put within them to cause them to walk in his ways,
and keep his statutes and judgments.
These live in the Spirit, and walk not after the flesh,
yet they do not magnify and claim their own
obedience (nor call it their own righteousness),
but rather acknowledge him from whom their obedience comes.
For in the measure of his grace and living truth,
the soul is one with him and all that he is, and all that he has done, is theirs.
And it is he himself that is the righteousness of all that are in him;
and they that abide in him partake of his righteousness from day to day,
which flows in them like a stream.

He seems to pass by some things (which I spoke in tender love and
weightiness of spirit to him) as the mere judgment of man in his day.
But let him take heed, for when he comes to appear before God,
he then will find it was the judgment of God`'s Spirit in the light of his day.
This day is inward and spiritual, which believers are to hasten to,
and which approaches in every heart, as the night is spent and passes away.
And all true Christians and believers ought to wait for the passing away of the night,
and the dawning of this day, and the arising of the day-star in their hearts.

And as for his remarks about the will of God done in heaven,
are there not those here on earth who dwell in heaven?
Are there not those whose citizenship is in heaven;
even the witnesses of God`'s holy truth,
who are ascended up above the spirit of this world, who dwell in God`'s holy Spirit,
and walk in the light as God is in the light?
Hell is not far from the wicked,
nor is heaven far from those who are renewed in the spirit of their mind,
and who witness the passing away of the old things, and the new creation in Christ.
Oh that he could look and see how he has wrested those scriptures (Ps. 85:9-11, Isa. 4:2.
and Eph. 2:6) according to his own imaginations.

[.discourse-part]
Objection:
He charges that we account all religion and Christian
profession in the world as below us and carnal.

[.discourse-part]
Answer: Indeed we magnify the truth, the life, the anointing,
the spiritual and inward appearance of our Lord
Jesus Christ to which we have been turned.
And all other knowledge, faith, profession,
and religion which does not arise from this we cannot help but call carnal.
For the enlightening Spirit of the Lord has given us
this testimony to bear against all the dead,
notional professors of this age,
who build from the letter of Scripture (or rather their
apprehensions of the letter) outside of the life.
All of these celebrate Christ`'s name of "`foundation`"
and "`cornerstone,`" but they refuse,
reject, deny, and turn from the cornerstone himself.
They have neither the skill nor patience to try what he is, in this his pure, precious,
living, powerful, and glorious appearance in the spiritual light of his inward day,
after the long, thick darkness of the foregoing night.
And woe would be unto us if we did not thus testify!
For, it is for this cause that we were born and brought into the world,
to testify to the present appearance of our God, and of his Christ, in this our day.
Glory to him who has called and chosen us,
and has (in a true and precious measure and degree of
his own pure life) made us faithful therein.

[.discourse-part]
Objection: He then objects as follows: "`Instead of clapping us on the back,
and ministering to us in our journey, you clog our march, and fall upon our rear.
Instead of serving the kingdom of Christ, you deny the first principles of the gospel,
and wholly disown the hope of Christ`'s second appearing and kingdom,
acknowledging no other Savior, or no other kingdom,
besides a seed or a light in yourselves.`"

[.discourse-part]
Answer: "`God is light, and in him is no darkness at all;`"
and this is the message of the gospel. 1 John 1:5.
And Christ, who is one with the Father,
he is one and the same light with him.
We confess we do not look for another besides him,
nor for another kingdom besides the kingdom which is revealed in him;
for the kingdom which is revealed and manifested in and by him is the spiritual, eternal,
everlasting kingdom, and there is not another.
We do not say that the fullness, or the full glory of the kingdom,
is now revealed or enjoyed by us.
No, we confess we have but the earnest in comparison, only a measure, a proportion.
But this measure is the same in nature and kind with the fullness itself.
And all that is of Christ, of his Spirit, of his nature, is saving.
The least measure of his grace that appears in any heart brings salvation with it;
the least touch of his finger has pure life and saving virtue in it.
Nevertheless, this measure is not distinct or separate from the fullness,
and so it is not another, though it is not the fullness.

And as for denying the first principles of the gospel, that belongs to yourselves.
For do you not deny that light which is the foundation of all,
and wherein and whereby all the mysteries of God`'s kingdom are seen?
And without this light, do you not set up a notional,
intellectual knowledge of your own conceiving, comprehending,
and gathering from the letter (though no man can understand
the letter except as he come into and abides in the light)?
This we have experienced in ourselves formerly;
for we were but guessing at and imagining things concerning the letter,
until we were turned to the light of God`'s Spirit.

And as for disowning the hope of Christ`'s kingdom,
the Lord knows that is far from us.
For we ourselves do bless him for what of his kingdom has already appeared,
and wait and hope for its further and fuller appearance.
But this we confess: another Spirit, another Christ, another light, another life,
another power, another kingdom, besides him who has already appeared, we do not expect.
For Christ is our King and kingdom both,
and the least proportion of his life and Spirit received (bought with the loss of all,
and so purchased and possessed) is no less than a pearl of great price,
and a heavenly kingdom to him that enjoys it.

Indeed, it is a great matter to know that throne which David`'s throne signified,
and Christ sitting thereon.
His kingdom, his throne, are not of this outward, worldly nature,
but inward and spiritual; and his throne is in his kingdom and temple, where he reigns,
and where he is worshiped.
He that comes to know Satan overthrown and cast out, knows also Christ come in,
and sitting on his throne.
Oh that men did give over their dreaming about the heavenly glory,
and come to this kingdom in the leadings of God`'s Spirit where it is revealed!

[.discourse-part]
Objection: He says, Christ shall appear without sin unto salvation.

[.discourse-part]
Answer: I grant it, but when, and how?
Does he not inwardly appear without sin unto salvation to those who have waited for,
hastened, and come to the inward day?
Does not Christ appear without sin unto salvation inwardly in the day of his own Spirit?
Is not the glorious salvation of the gospel brought forth in the gospel day?

[.discourse-part]
Objection: He adds, "`Is your attainment beyond Paul`'s,
who found that in him (that is in his flesh) dwelt no good thing,
and found his flesh lusting against the spirit so that
he could not do the thing that he desired.`"

[.discourse-part]
Answer: Paul did once experience such a state when he felt himself carnal, sold under sin.
In this state he did not find how to perform that which was good,
but rather did what he hated,
the law of sin being strong (in his members) against the law of life in his mind.
This state he calls a state of captivity to the law of sin in his members,
and a wretched state. Rom. 7:23-24.

But did Paul never experience another state?
Did he never witness the virtue and power of the new covenant,
even the law of the Spirit of life, and the power thereof,
freeing him from the strength and captivity of the law of sin in his members?
There were young men whom John speaks of (read 1 John 2:13) who were strong,
and had overcome the wicked one.
Did Paul himself never attain to that state?
He bid others be strong in the Lord and in the power of his might,
and showed them how to resist in it, and so to overcome.
Did he never experience and witness it himself?
He said he had fought a good fight, and was more than a conqueror.
Was he then a captive to the law of sin in his members?
He said he could do all things through Christ that strengthened him.
Was this not a different state from that wherein he found he could only will, but not do,
the good he desired, but only the evil that he hated?
And blessed be the Lord,
there are many at this day who witness a further state of redemption and
deliverance from sin than that state of captivity which Paul there expresses,
under which he formerly groaned and complained.
For indeed Paul was not in that state of captivity when
he wrote the epistle to the church in Rome,
but rather knew the dominion of grace over sin,
and bid that church to be subject to the grace, and not give way to sin,
but yield their members as servants to righteousness unto holiness, chap.6.

And in that other place, where he speaks of the flesh lusting against the spirit,
and the spirit against the flesh, Gal. 5:17, he does not there speak of himself,
but of the Galatians, who were in a weak and low state,
and fallen from the Spirit and power of the gospel,
having let in that which was contrary to it.
And so he strives to gather them into the Spirit again, and bids them live in the Spirit,
and walk in the Spirit, and so they should not fulfill the lusts of the flesh.
For in the new covenant, man is taught in the virtue and power of the covenant,
so that he learns daily, and grows daily out of deceit into truth,
until he come to be a true Israelite, in whom there is no guile.
And so in this spiritual war, the house of Saul grows weaker and weaker,
and the house of David stronger and stronger,
until Saul`'s kingdom be at length overturned and wholly destroyed,
and the kingdom of David established in righteousness forever and ever.
Then Jerusalem, the holy building, the city of the living people,
the city of righteousness (the habitation of righteousness and mountain of holiness),
is known, and Jerusalem is witnessed to be a quiet habitation,
there being peace in all her borders.
Then the mind is fully staid upon the Lord in all conditions,
and he keeps it in perfect peace.
Then the soul is anxious for nothing,
but in everything makes its requests known to God by prayer and supplication,
with thanksgiving.
And the peace of God, which passes all understanding,
keeps the heart and mind through Christ Jesus.

Surely the apostle had learned himself (when he
taught others) to be content in every state.
He knew how to be abased, and how to abound, etc.
Oh glorious state!
Oh pure state of pure life in the heart!
And what if I should add, Oh perfect state!
The apostle James says, "`Let patience have its perfect work,
that you may be perfect and entire, lacking nothing.`" James 1:4.
When Paul had so learned Christ that abundance could not lift him up,
nor any need deject him, or cause him to repine or distrust,
what did he lack of this perfect state?

[.discourse-part]
Objection: He claims,
"`Out of you have risen men that have more audaciously lifted
up a standard against the sealed and experienced truths of the
gospel than any other of which I have heard or read.`"

[.discourse-part]
Answer: We are a people (many of us) who have gone through
great distress for want of the Lord our God,
and have exceedingly waited and longed for his living and powerful appearance.
And as for my own part, this I can say,
that had this appearance of the Lord not been in power,
and in the evidence and demonstration of his Spirit to my soul
(reaching to and answering that in me which was of him),
I could never have acknowledged it,
for I was so deeply jealous of it and prejudiced against it.
But since my mind has been turned to the pure Word of life,
even the Word which was in the beginning (I speak as in the Lord`'s presence),
it has had singular effects on my heart.
The light has so searched me as I never was searched before,
under all my former professions of Christianity.
And the Lord has given me a true and pure discerning of the things of his kingdom,
in the light which is true and pure.
And I have met with singular quickenings from his Spirit,
and the faith which stands in his heavenly power and gives victory and dominion in him.
And the love which he has given me is not notional,
but arises from his circumcising of my heart,
and corresponds to his nature which springs forth purely and naturally towards him,
and towards those of his image, and all his creatures.
Indeed, this love springs towards those who are enemies to me for his name`'s sake.

I might mention the patience also, and faithfulness to his truth,
with the long-suffering spirit--which his Spirit testifies in
me to be of a very particular nature (along with other things).
And I am not alone in this, nor am I the chiefest; but I have many equals; and indeed,
there are those who far exceed me in the heavenly and divine image of my Father.
The fruits are according to the root of life in us,
and so they are acknowledged by all who look upon us with the true eye,
the eye which God gives and opens.

Now, the same one that has worked inwardly in us,
he has also required some outward behavior and expressions
from us which are foolish and weak to the eye of man`'s wisdom,
but are chosen of God to hide the glory of this
life from the eye which cannot discern it,
but rather despises the day of small things.^
footnote:[Penington here refers to some of the
outward ways in which Quakers felt led to dress, speak,
and live contrary to the proud and man-exalting customs and traditions of their day.
Though these outward things played a part in the Quaker`'s
testimony against the man-centered religion of their time,
they were by no means at the heart of their faith,
nor the principle things that distinguished them from other professing Christians.]
And though this is the least part of our religion (yet
we submit to it because it is of God,
whom we dare not disobey in the least),
yet the spirit which is contrary to God belittles us, as if this were all,
or at least the main thing in which we differ from others.
But alas, it is in the main that we differ from you.
For we hold our religion as we receive it from God--in the light and life of his Spirit.
You, however, hold yours as you apprehend it from the letter.
Christ is our rock and foundation as he is inwardly revealed;
but he is yours only as he is outwardly conceived.
We believe with the faith which is of the nature of him in whom we believe,
which faith is mighty through God, and works over all the powers of darkness,
giving victory over them all.
But you believe with a faith which esteems victory impossible while in this world.
And as our root differs, so too all that grows up in us differs from yours.

Now to close, I shall add a few words on that scripture, Phil. 3:3.
"`For we are the circumcision, which worship God in the Spirit,
and rejoice in Christ Jesus, and have no confidence in the flesh.`"
It is a precious thing to witness this scripture fulfilled in the heart,
to experience that which inwardly circumcises and cuts off the foreskin of the heart.
For this foreskin indeed lies over and veils the heart till it is cut off by the
inward appearance of the life and power of the Lord Jesus Christ inwardly revealed.
Then, when this is done, one can truly and sensibly say that he is an inward Jew.
How so?
How can that be proved?
Why, he is inwardly circumcised!
He has felt that knife within which circumcises the heart,
and has borne its inward pain and cutting, and is circumcised by it.
That which stood between him and the Lord is cut off, the veil is taken away,
the stiff-neckedness and independence from God is removed,
the wall of separation is inwardly broken down,
and now he is in true unity of Spirit and communion with his God--even with the Father,
and the Son, in that One Holy Spirit wherein they are One.

Now he can bow before the Father of our Lord Jesus Christ,
and worship him in his own Spirit, even in the new and fresh life, day by day.
Now his rejoicing is in Christ Jesus, whom the Father has sent,
both outwardly in a body of flesh to fulfill the holy will,
and also inwardly in his Spirit and power unto his heart,
to destroy the works of the devil there.
And he cannot help but rejoice both in what he did in his body of flesh for him,
and in what he does by his Spirit and power in him.

Oh blessed be the Lord, I feel him near, his Spirit near, his life near,
his power near, his pure virtue near, his holy wisdom near, his righteousness near,
his redemption near; for he is my rock, and my strength, and my salvation, day by day.
And I have no confidence in the flesh, in what I am, in what I can do after the flesh;
but my confidence is in him who has weakened me, who has stripped me,
who has impoverished me, who has brought me to nothing in myself,
that I might be all in him, and that I might find him made all unto me.
He is my peace, he is my life, he is my righteousness, he is my holiness,
he is the image wherein I am renewed.
In him is my acceptance with the Father.
He is my Advocate, he is my hope and joy forever.
He has destroyed that in me which was contrary to God, and keeps it down forever.
He is my Shepherd, his arm has gathered me, and his arm encompasses me day by day.
I rest under the shadow of his wings,
from which the healing virtue of his saving health drops upon my spirit day by day.
Oh, I cannot tell any man what he is unto me!
But, blessed be the Lord, I feel him near, his righteousness near,
his salvation daily revealed before that eye which he has opened in me, in that true,
living sense with which he has quickened me.

And now, you that have high notions, and rich,
intellectual knowledge concerning these things, but not the thing itself,
the life itself, the Spirit itself, the new and living covenant, and law of life itself,
wherein alone Christ is livingly revealed,--oh, how poor, miserable, blind,
and naked are you,
in the midst of all your traditional knowledge and pretended experiences!

Come now, be quiet a while, and cease from bitterness of spirit,
and reviling the work and people of the Lord.
For the Lord knows, and will make manifest, both who are his and who are not his.
All the living stones are his, but the great professors of the words of Scripture,
who are without the Spirit and life of the Scriptures, are not his, nor ever were,
nor ever will be owned by him.

Come now, learn to distinguish from God by his life, by his anointing,
by the everlasting, infallible rule, and not by _words without life._
This is where the great error and mistake has been in all ages and generations.
The great way of deceit has long been (and still is) by a form of godliness without power.
Be sure you are not deceived in this way; for if you miss the power which saves,
you cannot help but perish forever.
And what if the appearance of the Spirit and power of our Lord Jesus Christ inwardly,
which is that which saves, be as strange to your sense, understanding, and judgment,
as his outward appearance was unto the people of the Jews?
Take heed of their spirit, take heed of their judgment!
For they judged according to the appearance of things to them,
which they imagined and conceived from the Scriptures;
but they judged not with the true and righteous judgment,
which only the children of the true wisdom can.

=== The Dawning of the Spiritual Day

There are four or five very precious things which were generally
witnessed in the days of the apostles among the true Christians,
which are all mentioned together. Heb. 6:4-5.

[.numbered.emphasized]
First, they were truly enlightened.

The ministers of the gospel were sent by Christ to turn men from darkness to light,
and from the power of Satan to God. Acts 26:18.
1 John 1:5. They were faithful in their ministry,
and did turn men from the darkness and power of Satan to the light of God`'s Holy Spirit;
and they were enlightened by it, and received power through it,
and so came to be children of the light, and to walk in the light as God is in the light.

[.numbered.emphasized]
Secondly, they tasted of the heavenly gift.

What is the heavenly gift which Christ gives to
those who come unto him and become his sheep?
He gives them life, eternal life. John 10:27-28.
He brings them out of death,
and gives them a savor and taste of the life which is eternal.
This was what the apostles testified of,
even of the life which was manifested in that body of flesh of our Lord
Jesus Christ (1 John 1:2). They that turn from the darkness to his light,
he gives them a taste of the same life.

[.numbered.emphasized]
Thirdly, they were made partakers of the Holy Spirit.

The gospel is a day of bringing forth the spiritual seed,
and of pouring out the Holy Spirit upon them.
The law state was a state of servants; the gospel, a state of sons!
And because true believers in Christ are sons,
God sent forth the Spirit of his Son into their hearts to cry, Abba, Father.

[.numbered.emphasized]
Fourthly, they tasted of the good Word of God.

That is, of that Word which was in the beginning of the world,
which is ingrafted into the hearts of those that truly believe,
which Word is able to save the soul.

[.numbered.emphasized]
Fifthly, they tasted of the powers of the world to come.

Of the power of the endless life, whereof Christ is the Minister,
and according to which he ministers life in that holy, true, living, inward,
spiritual temple,
which he pitches and rears up for a habitation to God in his own Spirit.

Now,
throughout the apostasy and night of darkness which has come over the Christian state,
these things have been greatly lost.
For there were none who were able to turn people
to that light to which the apostles directed.
None could tell men where the light is to shine,
and where men were to expect it and wait for it.
None were able to direct men to the seed of the kingdom within, to the Word of faith,
the Word of the kingdom near in the heart and mouth.
Much less were they able to instruct men how they might
know and distinguish it from all other seeds,
and the voice of the Shepherd from all other voices.
Here it came to pass, that though at times God visited and opened men`'s hearts,
warming them a little by the breath which came from himself,
yet they knew not how to turn to the Lord and wait upon him
for preservation in the gift and measure of his own grace.
Thus the good seed was largely stolen away from them,
and the building which was raised up in them was
not a building of life according to the Spirit,
but rather a building of wisdom or knowledge concerning
the things of God according to the flesh.
And so the building that was raised up in men`'s spirits has been Babylon, instead of Zion.

But the Lord has had a remnant all throughout the apostasy,
who felt some true begetting of life,
and had in measure some sense and taste of the heavenly things.
These mourned after that state which was once enjoyed, and felt their lack of it,
traveling from mountain to hill, seeking their resting place,
about which none could rightly inform them.

But now, for the sake of these,
God has at length appeared!
"`How has he appeared?`" some may ask.
Why thus: he who is light has appeared inwardly, causing his light to shine inwardly,
causing his life to spring inwardly; so that he who is light, who is life, who is truth,
is felt and known in his own inward visits, breakings-forth, and appearances.
For God is a Spirit, and his appearance is spiritual, his day is spiritual,
his kingdom is spiritual, his light is spiritual, his life is spiritual,
his day-star is spiritual.
And so his day dawns and his day-star arises in the heart.

In this way the day spring from on high did visit us, we who sat in darkness,
and in the region of the shadow of death.
And here we have met with what the apostles met with, the very same light of life,
the very same enlightening Spirit and power, and we have been enlightened by it,
and have tasted of the same gift.

The very same grace that appeared to them and taught them,
has also appeared to us and taught us, and of it we have learned the same lessons,
in the same covenant of life wherein they learned.
And now we can set our seal to their testimony
in the same Spirit wherein they gave it forth,
and witness to the same eternal life, and the same holy oil and anointing,
for our eyes have been opened and kept open by it.
And though there are great disputes about our testimony in
this our day (and the present professors rise up against us
just as the former professors did against them),
yet if any man come rightly to distinguish in himself between
that which God begets in the heart and all other births,
they will soon confess that our testimony is of God,
and is given forth in the authority and by the commission of his own Spirit.
True wisdom is justified by the children that are born of her,
though the fleshly birth does not (nor can) acknowledge her.
The fleshly birth can acknowledge former dispensations (according to
the relation of them in the letter),
but not the life and power of the present gift.

I have known the breaking down of much in me by the powerful hand of the Lord,
and a parting with much (though not too much) for Christ`'s sake.
The Lord has brought the day of distress and inward judgment over my heart.
He has arisen to shake terribly the earthly part in me (yes,
what if I should say that the powers of heaven have been shaken also),
that he might make me capable to receive, and bring me into,
that kingdom which cannot be shaken.
And now, that which God has shaken and removed in me, I see others building upon,
and they think it shall never be shaken in them.
But such know not the day of the Lord, nor the terrible searching of his pure light,
nor the operation of his power, which will not spare in one what he has reproved,
condemned, shaken, and overturned in another.
He that knows the living stone within, and comes to him as to a living stone,
and is built upon the revelation of his Spirit, life,
and power (revealed inwardly against the power of darkness), is not deceived.
All that build otherwise (I mean upon an outward knowledge concerning Christ,
and not upon his inward life),
their building will not be able to stand in the day of the Lord.
I desire that they might have a sense of this in time,
and that they might not perish forever,
but rather experience the life and power of our Lord Jesus Christ,
which redeems and preserves out of the perishing state forever and ever.
Amen.
