== Chapter V. The Experiences

=== A Preface

The Father, in his love, has brought us to the Son, and the Son in the same love,
has brought us back to the Father;
and now the love flows from the Father most
naturally and abundantly in and through the Son.
And wherever the heart is circumcised,
there the love returns back to him most truly and naturally,
so that the Lord our God is loved with all the heart, and with all the soul,
and nothing is thought too good to sacrifice to him,
nor anything too much to suffer for him.
Oh, the pure love that springs and flows between the heavenly Father and the spiritual child!
The best love that is found in this world (among men of
this world) is not worthy to be a shadow of it.

Now, from this Fountain issue forth not only springs
and streams of life to refresh our own hearts,
but also testimonies concerning the life which we feel and partake of,
and concerning our travels from the dark land, through the valley of tears,
towards our resting place.
Many times these spring up in us for the sake of others,
and the following things are of that nature.
For it is not for my own sake that these did spring up in me at this time,
but to signify to others the mercy the Lord has shown me,
and the way wherein he has led me,
and what he has given me to taste of and experience in the way.
And having received them from the Lord for this very end--to hold them forth to
others in love and tenderness of spirit--my heart is freely given up to him therein.
I aim at nothing in this but his glory singly,
and the good of such souls to whom he shall be pleased to extend favor and show mercy,
in opening the heavenly mystery of life and salvation to them.

Indeed, my wound was deep and seemed incurable.
But blessed be the Lord who has made known to me the physician of value,
for whom no disease is too hard.
Surely he is able to cure every sickness,
and relieve and rescue all that are captive and oppressed by the devil,
who come unto him and wait upon him in the way of his
righteous judgments and most tender mercies.
For after all my religion and deep exercises, and inward experiences and knowledge,
I came to such a loss of what I once had, that I sensibly felt I knew not the Lord,
and I lay continually groaning and mourning after him.
Oh, the pure light, and precious life, and sweet presence of my God that my soul lacked,
insomuch that my moisture was turned into the drought of summer,
and my bones grew dry and withered!
But at length, the Lord, in his goodness, breathed upon the dry bones,
and I felt life enter from him into me,
and the days of deep sorrow and distress were at length forgotten,
because a man-child was conceived and brought forth.
And now where is the sackcloth?
Where are the ashes?
Oh, there is beauty in life, instead of the ashes in the lifeless state;
there is a garment of praise instead of the spirit of heaviness!
Oh glory, glory to him who binds up the bruised and brokenhearted.
Glory to the Redeemer of the captives, to the repairer of the breaches,
to the builder of the wasted and desolate ones!

[.alt]
==== I. Concerning the Seed of the Kingdom

Concerning the seed of the kingdom, this I have experienced:
that it consists not in words or notions of the mind, but is an inward thing--an inward,
spiritual substance in the heart,
as real inwardly in its kind as other seeds are outwardly in their kind.
And being received by faith, this seed takes root in man (his heart, his earth,
being plowed up and prepared for it), it grows up inwardly,
and brings forth fruit inwardly, as truly and really as any outward seed does outwardly.
This seed is known by its opposition to, and enmity against, the seed of the serpent,
and against all the seeds of evil in the hearts of men.
It discovers them, turns the mind from them, wars against them,
and bruises and overcomes them in all that receive it.
It also lets in its own holy nature, which, as a holy leaven or salt,
works out that which is unholy and unrighteous, dark and dead,
and seasons the soul with light, with life, with grace,
with the holiness and righteousness of truth.

[.alt]
==== II. Concerning the Soul`'s Food

The soul`'s food is that which nourishes it,
which is the same as that which gives it life.
Every word proceeding out of the mouth of God, every motion, every quickening,
every operation of his Spirit, is living,
and nourishes the soul (which receives and feeds upon it) with life.
The spiritual manna, the spiritual water, from the holy well or fountain,
the milk of the word, the flesh and blood of the Son of the living God, his words,
which are spirit and life, nourish up the living birth unto life everlasting.
How does a man come to live at first, but by hearing the voice of him that gives life?
And how does a man come to live afterwards, and to increase in life,
but by hearing the same voice?
"`Incline your ear, and come unto me; hear, and your soul shall live,`" etc. Isa. 55:3.
This I have also experienced to give me life,
to nourish up and strengthen me in life,
even fresh life communicated from the living Fountain.
And so my life is not in myself, not in anything I can comprehend concerning Christ,
but in being joined to him, in being ingrafted into him who is the holy root,
the true olive tree, into his Spirit.
And so by the sap that springs up into me from him,
my life is maintained and increased in me daily.
Glory to his name forever.

[.alt]
==== III. Concerning God`'s Power

Concerning God`'s power, this I have experienced:
that it is the power of God which does the work in the soul.
It begets to God, it brings out of the land of darkness,
it leads through all entanglements, and preserves in the midst of them all.
It breaks down the old building of sin and iniquity (both inwardly and outwardly,
both in the heart, and also in life and conduct), and raises the new and holy building.
It makes willing, it makes obedient, it gives ability to believe and to suffer.
Oh, blessed be the Lord for the day of his power which has inwardly broken forth!
Oh, blessed are they that know the ministration of the life inwardly,
the power of life inwardly!
For in life, in the seed of life, is the holy power which manifests, appears,
and works as it gains ground in the creature,
exercising in it the virtue and strength which it daily receives from its Father.

[.alt]
==== IV. Concerning Temptations

Concerning temptations, this I have experienced:
that the strength and hurt of them, as to the soul, lies in the soul`'s looking at them.
For the strength of God is revealed in his children against the tempter,
which being patiently waited for, and trusted in, will never fail them.
The Lord does not desire that even the least babe let in temptation and sin,
but rather watch in that,
and keep joined to that which will preserve out of all temptation and sin.
"`Look unto me and be saved, all you ends of the earth.`"
This is universally true.
Look unto me, trust in me; look not at yourselves, trust not in yourselves;
look not at the enemy, fear not the enemy; I will save you from every snare,
every temptation, as your eye is steadfast upon me.
What if the enemy comes in like a flood?
If the Spirit of the Lord lifts up a standard against him, can he prevail?
What if he casts fiery darts?
Will not the shield of faith quench them all?
Will not the whole armor of God defend and keep safe from them all?
If the enemy is resisted rightly (that is,
in true faith in the power which is engaged for the soul against him),
does not the power of the Lord arise and scatter him,
and strengthen and establish the soul in grace and truth?
Oh look not at the enemy!
Let not in the reasonings of the mind, but keep in the patience, keep in the pure fear,
and in the holy, living sense.
Be only what you are in the seed, in the new birth,
in the life which God has begotten in you; for then are you safe,
then are you in the name of the Lord, which is the strong tower.
The enemy indeed may make a noise about you with his lusts, with his temptations,
with his floods, with his storms, with his fiery darts;
but he cannot enter your habitation.
The Spirit of darkness, the prince of darkness, is shut out of the land of the living.
Abide there.
Dwell in the light, and walk in the light, as God is in the light,
and he shall never have power over you.

[.alt]
==== V. Concerning Prayer

I have experienced prayer to be the breathing of that birth which God begets,
unto the Father of life which begat it;
who by his Spirit makes known its condition and needs,
and gives sensible cries unto him for them.
For as it is not in man to beget himself to God,
no more can he pray to God in his own will or time,
but only as God pours out the Spirit of prayer and supplication upon him,
and by his Spirit teaches and helps him to pray as he ought.
"`Because you are sons, God has sent forth the Spirit of his Son into your hearts,
crying, Abba, Father.`"

I have had a sense of the natural man, and of the spiritual man,
and of the cries and prayers of each.
And this I have been taught and learned of God--that the gospel prayer is the
prayer of that birth which is begotten by the Spirit and power of the gospel,
and which prays in the Spirit, and in the springing up of the holy life and power.
In this way, prayer rightly wrestles and prevails with God,
obtaining the mercies and blessings which it wrestles with him for.
For to this child there is access to God in the faith,
through that Holy Spirit of life which makes way for it
to obtain grace and mercy in the time of need.
And through this Spirit it prays to God, and prevails with him on behalf of others also.
For the prayers of the righteous avail much, as it is written.

[.alt]
==== VI. Concerning Justification and Sanctification

Some things which it has pleased the Lord, in his tender mercy,
to give me to experience:

First, that it is the same Christ, the same Spirit, the same life,
the same wisdom, the same power, the same goodness, love, and mercy, the same water,
the same blood, which both justifies and sanctifies.

Secondly, that justification and sanctification are both of and through grace.
It is so in the beginning, and it is so all along.
"`By grace you are saved,`" says the apostle.
The whole work of salvation is begun and carried on through grace.
It is through that grace that God visits and reaches to
the soul with his quickening virtue and power.
He regenerates by grace, and through it he justifies, sanctifies, etc.
So that as the work goes on, "`grace,
grace,`" is to be cried unto him that does the work,
from his laying the foundation and fastening the soul thereupon,
to his laying of the top stone.

Thirdly, that faith and obedience are of the same nature, and always go together,
so that wherever there is faith, there is likewise obedience;
and wherever there is obedience, there is faith.
Obedience flows from faith, and cannot be without it;
for the very nature and virtue of faith is in it.
And faith is obedience.
For this is the command of God,
that the soul believe on him (and in his appearances) whom he has sent to save.
Indeed, this believing is obedience unto him that commands it.
And this faith, and this obedience, is holy and just in God`'s sight;
and through it (but not without it) the soul is both justified and sanctified.

Fourthly, that the works of faith, the works of the new life,
are not the works of the law (or works of the old covenant);
nor are they excluded from justification, as the works of the old covenant are.
For I have found that the Lord,
who has condemned and excluded all my doings whichever I have been able to do of myself,
still justifies and accepts that which his Spirit and holy power does in me.
These are not of the same nature as the works of the law,
nor are they so accounted in the eye of the Lord.
For the Lord distinguishes between root and root.
Whatever springs from the holy root, he justifies as holy;
whatever arises from the unholy root, he condemns as unholy.

Fifthly, that by the law of faith all boasting is excluded in the whole work,
both in justification and sanctification.
For what is the law of faith?
Is not this its law--to fetch all from the Son, and to do all in the Son?
Is it not to quit self and its own ability,
and to perform all things in the newness of the Spirit,
in the ability which God gives and continues
supplying in and through his grace and mercy,
to the soul that is in the Lord Jesus Christ?
All the veins of life, all the streams of the new covenant run here.
Here there is no boasting for the creature, nor can there be,
for all man`'s ability and strength is shut out,
and that which is given of God is all and does all.
Yet every inward Jew here "`has praise of God.`" Rom. 2:29.
His faith is commended, his love is commended,
his faithfulness is commended, his zeal for the Lord, his obedience to the Lord,
his patience in suffering, is commended, etc.
But the praise and honor of all rebounds not to his flesh,
but to the Spirit and grace of God in him.
So that here flesh is laid low and kept in the dust forever,
and God alone is exalted in this day of his pure power in the heart.

He that truly believes enters into rest.
How into rest?
From what does he rest?
Why, from his own works, from the works of the flesh.
Yes, he rests from the works of the old covenant,
from the works that arise from his own ability,
from the works wherein he can never be justified with the gospel justification.
But does he cease from the works of faith?
Does he cease from the labor of love?
Does he cease from obedience to anything that God requires?
No, but rather he begins to work and labor in the vineyard,
and his labor is not in vain in the Lord.

[.alt]
==== VII. Concerning Faith

Several things I have experienced concerning the nature, virtue,
and operations of faith;
some of which (as I feel them spring up livingly in my heart) I may mention at this time.

First,
this I have often experienced--that it is a hard thing to truly and rightly believe.
It is an easy matter to believe notions concerning God and Christ, but to believe in God,
to believe in Christ, to believe in him that raised up Jesus, to believe in the light,
life, and power which flows from Jesus,
this indeed is hard because of the great darkness and
ignorance which man is fallen into through transgression.

Secondly, I have experienced this also--that faith is God`'s gift,
and that it flows from the power of his life.
There is first a quickening, first a touching of the heart by the holy,
pure power of the Lord.
Then, only when a man is touched and quickened in and
by and through that virtue which flows into him,
he can believe in that which touches and quickens him.

Thirdly, that faith never stands in a man`'s own power,
but always in the virtue and power of the life of the Son,
so that he that will believe aright must wait to
feel the life of the Son revealed in him,
and faith flowing from him.
For the true belief springs from the life of the holy root,
and it is from the flowing up and springing up of that life
that faith receives its nourishment and daily virtue.

Fourthly,
I have observed this in my travels--that the earthly wisdom and its notions,
when gotten into the mind and held in the mind out of the sense of life,
are a great obstacle to faith.
For these strengthen and nourish that in man which must be weakened
and die if the true birth of life will ever reign in the heart.
Man is to die; man is to be ceased from; his understanding,
his wisdom is to be brought to nothing.
But after it has had a stroke and wound from God`'s Holy Spirit
and power (even the very wound which tends to death),
yet it will be seeking life again (getting its deadly wound healed),
and nourishing its life by those very notions which came from the life and power,
which in measure slew it.
In this way, the outward Jew finds his life in the outward knowledge, in the outward law,
in the letter which kills.
For indeed,
the descriptions and outward knowledge of things kills and deadens more and more,
unless man comes into the inward life and virtue.
"`If you live in the Spirit, walk in the Spirit,`" said the apostle.
A man cannot live in an outward knowledge concerning
the Spirit and power of the endless life.
He that would truly live must live in the Spirit itself,
and he that would rightly walk on in his way,
must walk in that Spirit wherein he received life.

Fifthly,
this I have also observed­--that all notional faith
without the living virtue (as concerning Christ,
his sufferings, death, resurrection, ascension, intercession, justification by him,
etc.) the enemy will let the soul alone with, and let him enjoy peace in.
But he will desperately war against the true faith, against faith in the true power,
against faith in the light of life.
Oh, how many sore and sharp assaults does he make against
the faith which receives its virtue from God,
and causes the soul to live to God!
And how painful it is in the soul, when faith is weak,
and the enemy comes against it with the strength of his assaults and temptations.
"`Lord, increase our faith,`" said the sensible disciples.

Sixthly,
that it is in the pure fear (not that which is taught by the precepts of men,
but which God puts into the heart) that faith has its strength,
and exercises its strength.
Oh, who knows the preciousness of this fear!
The power of faith, the power of life,
the power of salvation and everlasting preservation is revealed in it.
Therefore, when the Lord speaks of providing for his children a new covenant, he says,
"`I will put my fear in their hearts, and they shall not depart from me.`"

Now it behooves everyone to deeply consider of what nature his faith is,
and what virtue is in it.
What can it do in and through the power of the Lord for him?
Does it indeed fetch the true, living nourishment every day?
Does it deliver the soul and give it victory over that
which faith was appointed to deliver from?
For he, who through faith overcomes that which is contrary to God,
shall receive the inheritance; and he that fights the good fight of faith shall overcome.
But he that does not overcome his enemies which stand in his way,
shall be sure to be hindered by them from reaching his journey`'s end.

[.alt]
==== VIII. Concerning Obedience

First, true obedience, gospel obedience, flows from life,
flows from the living faith.
If I could obey in all things that God requires of me,
it would not satisfy me unless I felt my obedience flow from the birth of his life in me.
"`My Father does all in me,`" said Christ.
This was Christ`'s comfort.
And to feel Christ do all in the soul is the
comfort of everyone that truly believes in him.

Secondly, true obedience, gospel obedience,
is natural to the birth which is born of God.
It is unnatural to the flesh, to man`'s wisdom, to deny himself and take up the cross,
but it is natural to the birth which is born of God`'s Spirit.
"`That which is born of the Spirit,
is Spirit,`" and it is natural to it to be acquainted with, and exercised about,
that which is spiritual.

Thirdly, that honoring, pleasing,
and answering the will of the Lord is the proper aim of the truly obedient.
Oh, how do they delight to do the will of God! "`I have food,`" says Christ,
"`that you know not of.`"
To do the will was his food and drink,
and it is food and drink to all that are of his nature and Spirit.
If I should never have any reward other than the pleasure of obedience,
still I could not help but testify that in answering the law of the pure life,
in keeping the holy statutes and commandments of God`'s Spirit, there is great reward.
Yet there is a crown also,
and a reaping after this life of everything that is sown to the Spirit.

Oh, blessed is he who meets with the power of life which enables him to obey,
and blessed is he who is obedient and subject to that power!
For he that truly believes in Christ is turned by him to his light,
and to the power of his Father, and all peace, growth, joy, blessedness,
etc. is witnessed in subjection thereto.

[.alt]
==== IX. Concerning the Cross of Christ

This I have experienced concerning the cross of our Lord
Jesus Christ--that it is an inward and spiritual thing,
producing inward and spiritual effects in the mind.
For it is the cross of Christ which slays the enmity in the mind,
and crucifies to the world and the affections thereof.
"`God forbid,`" said the apostle, "`that I should glory,
save in the cross of our Lord Jesus Christ, whereby the world is crucified unto me,
and I unto the world.`"
Now note: that which is contrary to the world, and crucifies to the world,
that is the cross.
The cross alone has this power and nothing else,
so there is nothing else in which to glory.
"`The flesh lusts against the Spirit, and the Spirit against the flesh;
and these are contrary one to the other.`"
Here is the cross: the Spirit which is contrary to the flesh, which mortifies the flesh,
in the obedience of which the flesh is crucified.
"`If you, through the Spirit, mortify the deeds of the body, you shall live.`"
Whatsoever is of and in the Spirit is contrary to the flesh.
The light of the Spirit is contrary to the darkness of the flesh.
The holiness of the Spirit is contrary to the unholiness of the corrupt heart.
The life of the Spirit is contrary to the life (or rather death) that is in sin.
The power of the Spirit is contrary to the power that is in Satan and his kingdom.
The wisdom of God is contrary, and a foolish thing, to the wisdom of man.
Yes, the new creature, which springs from God`'s Holy Spirit,
is contrary and death to the old.
Now he that comes here, out of his own wisdom, will, thoughts, and reasonings,
and comes to a discerning of God`'s Spirit,
and to the feeling of his begetting of life in the heart, and waits here,
and receives counsel here, such a one is taught to deny himself,
and to join to and take up that by which Christ daily
crosses and subdues in him whatever is contrary to God.

Here is the fight of faith and the true journey under the cross,
whereby the enemies (which rise up to oppose in the way) are vanquished and overcome.
For here (in the cross) is the power revealed, the preserving power, the leading power,
the conquering power of him who rides on conquering and to
conquer his spiritual enemies in the hearts of his children.
These know his voice and are subject to him, and daily deny themselves,
taking up his cross and following him.
Woe to them that are at ease in Zion with anything that is contrary to God.
But blessings are upon those whose dwelling is under the cross,
and who know no ease except what it allows.
It will make truth, life, holiness, righteousness, faith, obedience, meekness, patience,
love, separation from sin, communion with the Lord, and all the fruits of the Spirit,
as natural to them in the renewed state, as ever sin was in the corrupt state.
For Paul, who once complained of his captivity, and that he did what he hated,
yet after he had known the power of the cross, and was crucified with Christ,
he could then do nothing against the truth, but only for the truth.
Yes, then being a conqueror, having overcome the enemies which stood in his way,
he could do all things through Christ that strengthened him.

The cause of so many complaints,
and so much mourning because of the prevailing of the enemy (through temptations, sin,
and corruption), is because the cross of Christ, which is the power of God,
is either not known, or not taken up.
And this is the reason that many who make a fair show for a while,
yet afterward come to nothing (but are like untimely figs,
or like corn upon the housetops, which hastily spring up,
but soon wither) because they never rightly learn or keep to the cross.
For the cross alone has power from God to bring
down and keep down that which is contrary to him.
But out from under the cross of Christ,
there is no witnessing salvation or preservation from the Lord.
Outside the limits of the cross,
the enemy has power to recover and bring back under his dominion again.
And whosoever in his travels leaves the cross behind him, draws back unto perdition,
and cannot travel on in the living faith, and the newness of obedience,
towards the salvation of the soul.

[.alt]
==== X. Concerning the Mystery of Life, and the Mystery of the Fellowship which is Therein.

God is hid from man so long as he lies in his sinful and fallen state;
and no man can find or know him,
except as he is pleased to reveal himself by his own blessed Spirit.
When Christ appeared in the days of his flesh, flesh and blood could not reveal him,
but only the Father.
And he is the same today as he was yesterday.
He is not to be known now, except in the same Spirit, in his own grace and truth,
in a measure of his own life.
The dead cannot know him, but only those who are his sheep,
who are quickened and made alive by him.

Now this life is a mystery; none can understand it except they that partake of it.
Can a man that is naturally dead know what the life of nature means?
No more can a man that is spiritually dead know what the life of the Spirit means.
The natural man may get the words that came from life, and claim and commend them,
and speak great words about the fame of wisdom,
but the thing itself is hid from them all.
Oh, it is a narrow gate through which the birth enters,
and through which none else can enter!
The wise and prudent learners and searchers
according to the flesh (even of the Scriptures,
as they can put meanings upon them and comprehend them) are shut out in every age.
But there is a babe born of naked truth (born of
the pure simplicity) who is admitted by God.

The fellowship of the saints is in the life and in the light, which is a mystery.
The fellowship is not outward, but inward.
All they that meet together in the outward place are not in the fellowship,
but only they that meet together in the inward life and Spirit.
"`They that worship the Father, must worship him in Spirit and truth.`"
There is the worship; there are the worshipers.
They that are in the Spirit, in the truth, meet in the Spirit, in the truth,
they meet together in the one spiritual place, as I may call it.
And so we know no man after the flesh, no man according to the appearance,
but only in the righteous judgment of the Spirit, those only who are of the Spirit.
Indeed, we are tender where there is the least beginning of the work of God in any heart,
yes, where there is only so much as a conviction of the understanding.
But they are not truly one of us,
who acknowledge our principles in words or outward appearance,
but only those who are inwardly changed thereby in the heart.

[.alt]
==== XI. Concerning the Increase of the Kingdom

Was it not the great doctrine of Christ to preach the kingdom?
And how did he preach it?
Did he not preach it as a seed, as a grain of mustard seed?
Did he not liken this spiritual seed to leaven, to a precious pearl,
to treasure hidden in a field, to a piece of silver lost,
etc.? Oh how happy is he who knows and enjoys the thing itself which Christ preached!
All the prophets prophesied concerning him, and when he came,
this was his doctrine--that men should mind this precious seed, look after it,
purchase it, possess it, feel it planted and growing up in them,
and themselves ingrafted into and growing up in it.

Now, there are many sorts of talkers concerning the thing,
but there are few travelers into it.
Only the one who is a true traveler into it, and who finds his rest there,
can certainly know and truly witness what is to be found there.
And this is the reason that so many (who seem to be wise and learned) cannot
receive our testimony--because they know neither the seed nor its voice,
concerning which and by which we testify.
But wisdom is justified by her children,
and they that know the voice of the Shepherd know his present appearance in this our day,
which is contrary to the wisdom and knowledge of all other seeds and births whatsoever.
"`He that has an ear to hear, let him hear.`"
But he that has not the true ear cannot hear the true testimony,
though it should be ever so often declared unto him.
But blessed is he that knows and stumbles not at the
appearances of the seed and power of life in his own heart,
but rather is turned from the darkness to the light there,
and from the power of Satan to the manifestation of God`'s Spirit there.
For the end of words (even of Christ`'s own directions in the days of his
flesh) is to turn men to the holy life and power from which the words came.
Unto this is the soul`'s true travel,
waiting on the Lord in the way of his judgments and tender mercies,
to witness a translation from darkness to light,
and from the kingdom of Satan into the kingdom of the dear Son,
which kingdom is at first but as a grain of mustard seed.

And now let every serious heart examine concerning himself.
Do you know the kingdom?
Is the seed grown in you?
Does it overspread you?
Are you in it as in a kingdom?
Do you feel it overshadowing you?
Are you in unity with it?
Does it speak peace to you from the Lord?
Is the wall of partition broken down in you?
Is there of the two made one new man?
Do you feel that which is contrary to Christ subdued in you by his power?
Do you feel his holy nature, life, and Spirit, reigning over it?
Do you experience that scripture,
"`If you through the Spirit mortify the deeds of the body, you shall live`"?

Ah, how much do men talk of Christ, the power of God,
and yet miss the effect and work of his power in them!
Faith is a powerful thing, it gives victory (true faith gives victory).
It scatters that which stands between, and gives real access to God,
and lets in his pure, fresh, living virtue, upon the heart.

Love is a powerful thing, it constrains unto obedience,
and the heart that is circumcised to love the Lord God,
oh how does life flow from him into it!

Oh, away with empty notions, and come to the ministration of the Spirit,
where the knowledge is living, the faith victorious, the love pure and undefiled,
the worship truly spiritual, even flowing from, and comprehended in,
the life and virtue of the Spirit!
Oh that all that truly breathe after the Lord might be gathered here, found here,
and dwell here!
Amen.

=== A Few Words Concerning the True Christ

[.discourse-part]
Question: How may the inward and spiritual appearance of Christ be known?

[.discourse-part]
Answer: The inward appearance is to be known in the same way, and by the same means,
as was his outward appearance, which was by the revealing of the Father.
For "`none knows the Son but the Father, and he to whom the Father reveals him.`"
And when Simon Peter confessed him to be Christ, the Son of the living God, he said,
"`Blessed are you, Simon Bar-Jona, for flesh and blood has not revealed it unto you,
but my Father which is in heaven.`" Matt. 16:16-17.
Now, if none could know Christ in his appearance in the flesh
(despite so many manifest and express prophecies con­cerning him),
but only such to whom the Father revealed him,
how shall any know his inward and spiritual appearance,
unless they be taught of the Father, and hear and learn of him?

The true Christ is known by the manifestation of his life within,
by the fullness of the grace and truth which dwells in him, and puts itself forth,
so as to be discerned by the inward and spiritual eye in man.
He is known by his voice and knocks.
His sheep know His voice.
He speaks in his Father`'s authority (not as the scribes, not as earthly-wise,
learned men); he speaks in the evidence and demonstration of God`'s Spirit.
The words which he speaks are Spirit and life, and they that hear his voice live.
Oh, the beatings of his hand upon the tender and sensible hearts and consciences!
Oh, his secret reproofs, his secret instructions, his secret quickening and enlightening!

He is known by his baptism, or by his baptizing into his own Spirit and power.
While people were in expectation, and mused in their hearts about John,
whether he were the Christ or not, John answered the case,
and told them how they might discern and know the true Christ.
It is not I, who baptize only with water; but he that baptizes "`with the Holy Spirit,
and with fire; whose fan is in his hand,`" etc. Luke 3:15-17.
He that knows him who inwardly and spiritually baptizes, who has the fan,
and who inwardly fans and purges the floor,
gathering in the wheat and burning up the chaff, does he not inwardly, truly,
and spiritually know Christ?
He that knows the word which is quick and powerful, and sharper than any two-edged sword,
piercing even to the dividing asunder of soul and spirit, and of the joints and marrow,
and is a discerner of the thoughts and intents of the heart,
does he not know "`the word which was in the beginning, which was with God`"?

He is known by his mighty works.
"`The works which the Father has given me to finish, the same works that I do,
bear witness of me, that the Father has sent me.`" John 5:36.
And when John sent two of his disciples to Jesus with this question:
"`Are you he that should come, or should we look for another?`"
Christ bids them go and tell John what things they had seen and heard:
"`How that the blind see, the lame walk, the lepers are cleansed, the deaf hear,
the dead are raised, to the poor the gospel is preached;
and blessed is he whosoever shall not be offended in me.`" Luke 7:22-23.
"`Why,
herein is a marvelous thing`" said the blind man "`that you know not where he is from,
and yet he has opened my eyes.`" John 9:30.
He who has the power,
and shows forth the power inwardly-- who opens the inward eye, the inward ear,
looses the inward tongue, causes the inward feet to walk in the way of life,
and the inward hands to work the works of God--this one is the Messiah, the Savior,
the Word of life, the Son of the living God.
They that believe in him, in his Spirit, in his power, in his inward appearance,
have the witness in themselves, the living testimony, which none can put out,
or take away from them.
Oh, he has opened my eyes, he has opened my heart, he has raised me out of the grave,
he has given me eternal life!
He has changed me inwardly, created me inwardly, by the working of his mighty power!
And now I daily live, and am preserved, and grow by the same power.
I feel his life, his virtue, his power, his presence day by day.
He is with me, he lives in me, and I live not of myself,
but by feeling him to live in me, finding life spring up from him into me,
and through me.
Herein lies all my ability and strength forevermore.
