== Chapter VII. To the Jews According to the Flesh / and According to the Spirit

=== First: To the Seed of Abraham After the Flesh

Oh, the glory of your outward state,
you who were the people whom God once chose and loved,
and manifested his power and presence among above all people!
Your land was the glory of all lands,
to which God brought you out of Egypt by an outstretched arm,
through a dreadful wilderness, wherein you were tempted, tried, and exercised.
Oh, what laws and statutes, and righteous judgments did God give you,
such as no other nations had!
What a temple you had in which to appear before God, and the ark of the covenant,
and holy priests, kings, and prophets!
And how near was God to you, to be inquired of by you,
and how ready he was to hear your prayers, in all that you called upon him for!
The eternal God was your refuge,
and underneath were the everlasting arms (the Lord was your rock,
and you were built upon him).
He did thrust out the enemy before you, and when the arm of the Lord destroyed them,
you dwelt in safety, and the Lord was a fountain of living waters to you,
and his heavens did drop down fatness upon you.
Happy you were, O Israel!
Who was like you, O people saved by the Lord!
And indeed, it might have still been so with you,
had you not been unmindful of the rock that begat you,
and forgotten the God that formed you.
For your glory should not have been taken from you,
but rather swallowed up in a higher glory,
wherein you might have had the first and chiefest share,
had you not (by your almost constant rebellion and unbelief),
provoked the Lord against you.
For he was moved not only to afflict,
but at last to utterly cast you off from being a people,
and to choose a people in your stead,
who should bring forth better fruits to the Lord of the vineyard,
than you in your day had done.

Yet when your state was glorious, it was not a state of the truly substantial,
lasting glory, but rather a shadowy state or representation thereof.
Your day of glory was not the day of the Messiah, the day of everlasting inward light,
in which the Lord alone is exalted inwardly in the hearts of all,
where he breaks down all that is contrary to the light of his day.
Your day was but the day of the outward shadows of heavenly substance;
and when that day (the day of the inward substance and glory) shined,
your shadows or shadowy state was meant to fly away and be swallowed
up in the pure substance and spiritual kingdom of the Messiah.

Your birth from Abraham after the flesh was not the birth
which was to inherit the promise in the kingdom of the Messiah.
There is, however, an inward birth of the Spirit, born after Abraham in his faith,
who travels inwardly, as Abraham did outwardly, and seeks an inward country and city,
whose builder and maker is God.
It is to these that the spiritual kingdom and promises belong.

Your circumcision was but the outward circumcision,
the circumcision of the flesh; it was not the circumcision of the heart.
The circumcision of the heart is for the inward Jew,
which indeed the Scripture required of you (because there was
something near you which would have so circumcised you,
had you hearkened and given up to it, see Duet. 30:14). But you, as a people,
were not so circumcised,
but were a stiff-necked people (as Moses and the prophets complained of you),
uncircumcised in heart and ears,
resisting God's Spirit in your own hearts and in the prophets,
until the Lord was provoked to take away both vision and prophet from you.

The Egypt where your fathers were in bondage, and the Pharaoh who oppressed them,
was but the outward Egypt and outward Pharaoh.
There is an inward Egypt, wherein the spiritual seed in the inward man, the soul,
is in bondage.
There is a spiritual Pharaoh that oppresses the spiritual seed, in spiritual Egypt.
And there is a stretching out the arm of the Almighty inwardly,
to break the strength of the inward Pharaoh, to pierce Leviathan the crooked serpent,
and to deliver the soul from under his captivity.

The wilderness also, that your fathers were led through,
was but the outward wilderness, where they were tempted and tried by the Lord many ways,
that he might do them good in the latter end.
But the inward Israel, after they are led out of the inward Egypt,
are tried in the inward wilderness.
Here they are judged after the flesh,
and that which is not to enter into and inherit the good land is wasted in them.
Here they are tried in the furnace of affliction,
and their filth is purged away by the spirit of judgment and burning.
Then the righteous nation, which has received the holy inward law, and keeps the truth,
may enter into the good land, city, and kingdom of the Messiah,
and inherit the blessed promises of life and salvation there.

Moses, your great prophet, was a type of the great, lasting, standing prophet,
whom God would raise up like unto Moses,
who was to give his inward law as Moses did the outward,
and to lead all spiritual Israel as Moses did outward Israel.
His word was to be heard and stand in all things
whatsoever that he shall say to his people,
and whosoever will not hear and obey this prophet shall be cut off from among the holy,
spiritual, and inwardly living people. Duet. 18:15.

Joshua, who succeeded Moses, led into the figurative rest;
he was but a figure of him that inwardly leads into the inward and spiritual rest,
which the true Jews (who are inwardly created and formed by God,
and made a willing people in the day of his power), enter into.

The pillar of cloud and pillar of fire in the wilderness were
but figures of the spiritual pillar of cloud and fire,
by which the spiritual Israel are led and defended in
the glorious gospel day of God's Spirit and power.
Read Isaiah, chap.
4, which speaks of the gospel day,
and the pillar and cloud of fire to be created therein,
and of the defense which is to be on all the inward and spiritual glory.

The land of Canaan, the outward land and kingdom of Israel,
was but a figure of the inward land and kingdom
of the inward Israel in the days of the Messiah.
This is the land of Judah in which the song is sung because of the strong
inward city where God appoints salvation for walls and bulwarks.
Into this city enters the righteous nation which keeps the truth.
Isaiah 26.

The outward kings in that land, and particularly David,
were but types of the spiritual king, the spiritual David,
whom God would raise up to the spiritual people who seek the Lord their God,
and David their king.
He shall be their spiritual shepherd and ruler,
whom God has appointed to feed them in the integrity of his heart,
and to guide them by the skillfulness of his hands,
who is King of righteousness and peace inwardly,
and who ministers righteousness and peace to the sheep and lambs of his pastures.

The outward priests (even their high priests) were but
a representation of the great high priest of God,
who was to be a priest forever according to the order of Melchizedek.
Ps. 110:4.

The outward covenant (made with them from the outward mount Sinai,
upon the giving of the law, and holy statutes and ordinances,
by which they were to live and enjoy God in their outward
state) was but a shadow of the inward and spiritual covenant,
the new and everlasting covenant,
which God makes with his inward and spiritual people in the latter days.

Their outward law, as written and engraved in tables of stone,
was but a shadow of the inward law, which God puts into the children of the new covenant,
insomuch that they need not seek outwardly to learn the knowledge of God,
or his will or law.
Rather, the inward Israel finds the law written within,
and the islands who wait for the law of the Spirit of life, for the law of the Messiah,
receive the ministration of the law (in the Spirit and
power of the Messiah) for which they wait.

The outward Mount Zion,
on which the outward temple was built by Solomon (that wise, righteous, peaceable king),
was a figure of the inward mountain,
whereupon the inward house is built in the days of the gospel,
in the days of the Messiah;
and to this mountain the spiritual people come up and worship.
And this is the Zion and Jerusalem (even inward and spiritual Zion) from
which the law and word of the Lord go forth in the days of the Messiah.
Here the spiritual house of Jacob agree together to walk in the light of the Lord,
who sends forth his light and truth, and leads them to his holy hill,
and to his tabernacles.

Their outward tabernacle and temple,
sanctified by God for him to dwell and appear in,
was a shadow of God's inward dwelling place in man; "`I will tabernacle in them.`"
God dwells not in houses or temples made with hands; that is not the place of his rest,
as says the prophet Isaiah.
Rather, the high and lofty One that inhabits eternity, whose throne is in heaven,
and the earth his footstool,
he dwells also with him that is of a humble and contrite spirit,
to revive the spirit of the humble, and to revive the heart of the contrite ones.

The outward sabbaths were not the lasting Sabbath or rest of the gospel,
but were given for a sign.
For the day of redemption from sin, the day of resting from sin,
the day of ceasing from the works of the flesh,
the day wherein God is all and does all by his Spirit and power inwardly,
and wherein he alone is exalted,--this is the day of
rest which the Lord has made for the spiritual Israel,
in which they are glad and rejoice.

So too their incense and sacrifices were not the lasting incense and sacrifices,
but shadows thereof.
For the prayers of the saints,
when God pours out the spirit of prayer and supplication upon them,
and they pray to him therein, that is the incense.
"`Let my prayer be directed before you as incense,
and the lifting up of my hands as the evening sacrifice.`"
And this was the incense and pure offering,
which in every place was to be offered up to God's name among the Gentiles,
when his name should be great among them, as Malachi foretells.
And what said David of old, when God's Spirit and the holy vision was upon him?
"`Sacrifice and offering you did not desire; my ears you have opened;
burnt offering and sin offering have you not required.
Then said I, lo I come; in the volume of the book it is written of me.
I delight to do your will, O my God.
Yes, your law is in my heart.
The sacrifices of God are a broken spirit (rend your hearts, and not your garments,
and turn to the Lord your God).
A broken and a contrite heart, O God, you will not despise.`"
The offering of praise to God from a sincere heart, and the ordering of the life aright,
these are the sacrifices well-pleasing to God.
For sacrifices were not the thing which God chiefly required of outward Israel, but this:
"`OBEY MY VOICE.`"
For obedience is more acceptable than all other sacrifices,
and to heed than the fat of the choicest rams.

Moreover,
those outward sacrifices could not remove or take away sin from the conscience,
but he that came to do the will of God,
and to put an end to those sacrifices and
oblations (which were but outward and imperfect),
he does both wash and take away sins from within,
and also brings in everlasting righteousness where his light shines,
and his pure life springs inwardly in the heart.

Now this is the substance of all the shadows--even the eternal light,
the eternal word, the Son of the living God (who is light as the Father is light),
the word near in the mouth and heart,
the word of the new covenant to which Moses directed your fathers, Deut.
30, and by which the Lord speaks, and has spoken throughout the world, Ps. 50:1.
And it is by this word that God teaches
every man that hearkens to his voice to do justly,
love mercy, and walk humbly with his God, as it is expressed by the prophet Micah.

Now to you Jews of the outward line of Abraham (whose
return to the Lord my soul most earnestly desires after,
and for which I have most vehemently prayed to the Lord),
here are a few weighty inquiries upon my heart:

[.discourse-part]
Inquiry 1: How did David come to pant after the living God,
like the deer after the water brooks?
Was it not from the quickening virtue of this inward word, which Moses, the man of God,
had directed the mind to?
Read Psa. 119, and see how he breathed for quickenings from this word upon which all depends.
And now, if you come to experience this word, and the quickening virtue of it,
and follow the Lord therein, you will soon come to know the day of the Messiah,
and the glory of his kingdom, which is not outward, transitory,
and of a perishing nature, but inward, spiritual, and everlasting (as David well knew,
and spoke sensibly of, see Psa. 145 and elsewhere).

[.discourse-part]
Inquiry 2: What are the waters to which every thirsty soul is invited?
Isa. 55. Are they not the waters of the Messiah?
Are they not waters that flow out of the wells of salvation?
Isaiah 12. Is not the spiritual Israel to draw spiritual water
out of the wells of the Savior in the days of the Messiah?
What is it to come to these waters?
Oh that you experientially knew!
But this I will tell you from true and certain experience,
that if you come to take notice of this word of life,
which God has placed near in your mouths and hearts, and incline your ear to it,
and come away from that which it reproves in you, as it draws to itself,
then your souls shall soon come to live.
And he that gives you life will make an everlasting covenant with you,
even the sure mercies of David.
But you must be still and mind him as a witness, and leader, and commander,
inwardly in your hearts, that you may be preserved in the covenant,
and enjoy the blessings of it; see Isaiah 55.

[.discourse-part]
Inquiry 3: Did not the Messiah come at the set time,
at the time set by the Holy Spirit of prophecy?
Did he not come in the prepared body to do the will of God?
And did he not do his will?
And after his obedience to his Father, was he not cut off, though not for himself? Dan. 9:26.
And after his cutting off, were not you (natural Israel) made desolate?
Why were you made desolate?
Why did such a stroke come upon you as never before?
Oh, consider it!
Read Dan. 9:24 to the end of the chapter, and let him that reads understand.

[.discourse-part]
Inquiry 4: What was that curse, and upon whom did it fall?
"`Let their table become a snare to them,`" etc.
Psa. 69. Was it not on those that gave gall and vinegar to the Messiah to drink,
of whom David was a figure, and concerning whom he spoke in the Spirit?
Whose eyes are always darkened?
Does not the veil lie still on your whole nation?
Do you know the inward mountain,
where the veil of the covering is destroyed in the inward day and light of the Messiah?
To what purpose is it for you to read Moses and
the prophets when the veil is still upon you,
that you cannot see what is to be abolished, and is abolished,
by the dawning of the glorious day of the Messiah?
Here there is a Judaism, there is a circumcision, there is a Sabbath, there is a rest,
etc., for the inward and spiritual people, which is to remain, and never to be abolished.

[.discourse-part]
Inquiry 5: What was that people and nation
with which God would provoke you to jealousy? Deut. 32.
Was it not the spiritual people, the holy inward nation, the true Jews,
whom God took from among the Gentiles?
Was it not those in whom he appeared and was a God and a Father to,
when he cast off and forsook the outward Jews, and left them to be a desolation?

[.discourse-part]
Inquiry 6: Who are those that shall be hungry when God's servants shall eat,
and thirsty when God's servants shall drink, and ashamed when his servants shall rejoice?
Are not your souls hungry and parched for lack of the spiritual sustenance
with which the living God satisfies his servants on his inward holy mountain?
And are not you ashamed of your expectations of the Messiah,
even while the servants of the Lord rejoice in him, their Prince and Savior,
and witness him daily a leader and commander to them?
What is the people whom the Lord has slain and made desolate?
(Are not you a slain people to God, alienated from his life, Spirit, and power,
dead in your literal notions and observations?) And what are the servants of the Lord,
whom the Lord has called by another name, even a name that you never knew? See Isa. 66.
And consider, how during all your day God spread out his hands to you,
and you were rebellious, and would not hear.
But now night has come upon you, and your visitation, as a people, has been long ended.
See Luke 19:44

[.discourse-part]
Inquiry 7: Now that the inward people, and the inward covenant, the new covenant,
are brought forth, shall you ever be owned or regarded again as an outward people,
according to your outward covenant?
Will not all such expectations fail you forever?
You have looked from generation to generation for the
coming and appearing of the Messiah outwardly,
after an outward manner, but now his coming and appearance is inward.
For he sets up his kingdom, his everlasting kingdom, in his saints,
and in their hearts he rules inwardly; and it is there that the Messiah,
the seed of the woman, bruises the head of the serpent.

Oh that you knew the substance!
Oh that you knew the word of life in the heart, and were turned to it,
and daily faithful and obedient!
Then you would feel it crushing and dashing the
power of sin and corruption in your hearts.
This is the consolation, hope, and joy of the inward and spiritual Israel.
Oh that you might be made partakers of it,
and that your long outward captivity and desolation
might at length end in inward freedom and redemption!
Amen.

=== Second: To the Spiritual Seed of Abraham

[quote.scripture, , Gen. 49:10]
____
The scepter shall not depart from Judah, nor a lawgiver from between his feet,
until Shiloh come; and unto him shall the gathering of the people be.
____

Old Jacob, in the spirit of prophecy, saw that Judah was to have the scepter,
the kingly power, and it was not to depart from him, it was to be his right,
and the lawgiver was to be his until Shiloh^
footnote:[The term "`Shiloh`" in Genesis 49:10 comes from an
obscure Hebrew word that is variously interpreted to mean "`the sent
one,`" "`the seed,`" or "`the peaceable and prosperous one.`"
Whatever the correct translation,
the word is universally accepted to be a reference to the Messiah.]
came.
Then the right was Shiloh's to reign, and to give laws to his people,
whom he would gather out of the kingdom of darkness, and from Satan's power,
into his own inward, spiritual, and everlasting kingdom.
This was the true king, God's king,
whom he would set upon the holy hill of spiritual Zion, and all the holy, inward,
spiritual gatherings of all people must be unto him.

"`I will overturn, overturn, overturn it, and it shall be no more,
until he comes whose right it is, and I will give it to him.`" Ezek. 21:27.
And his dominion shall not pass away,
or the scepter and lawgiving power shall not pass away from him, as it did from Judah,
nor shall his kingdom ever be destroyed, Dan. 7:14.
For God will give to him the throne of his father David,
and he shall reign over the house of Jacob forever;
and of his kingdom there shall be no end.

[.discourse-part]
Question: But who are the people that shall be gathered to him?

[.discourse-part]
Answer: The people that shall hear his voice, and come at his call,
that shall receive the instruction of wisdom,
and feel the drawing power and virtue of the Father in the day of his power.
It is written in the prophets, "`All your children shall be taught of the Lord.`"
And everyone that is taught and learns of the Father comes to the Son,
comes to the Messiah, comes to Shiloh, to the Word eternal,
to the Word of life in the heart.

[.discourse-part]
Question: Were the Jews then excluded from this gathering?

[.discourse-part]
Answer: No, they were to be gathered to Shiloh, as well as others.
Indeed, the Lord had a special regard to them, for the gospel was first preached to them.
They had the first offer, or the first call to the spiritual glory.
They were the children of the prophets,
and of the covenant of God made with their fathers.
And unto them God, having raised up his Son Jesus, sent him to bless them,
in turning away every one of them from their iniquities.
And the whole nation, turning from their iniquities, should have been gathered by him,
and should have enjoyed the blessing of his day and kingdom.
For truly, the first gathering was from among them,
and the first glorious gospel church was at Jerusalem,
where the Spirit and power of the Lord Jesus did
most eminently and wonderfully break forth,
and great grace was upon them all.
But the nation at large was not gathered to Shiloh,
nor did it come under his scepter and government, but only a remnant of the nation.
And so, these being gathered, the rest were cast off,
and the banner was carried among the Gentiles,
and the great gathering was there among them.

[.discourse-part]
Question:
How is it manifest that the great gathering unto
Shiloh was to be from among the Gentiles?

[.discourse-part]
Answer: By many express prophecies of Scripture, and promises to the Messiah,
that he should have the Gentiles for his inheritance and possession.
When God established his king, the Messiah,
upon the holy hill of spiritual Zion (notwithstanding all the heathen's rage against him,
and the people of the Jews imagining a vain thing,
thinking to keep his body in the grave, who was the resurrection and the life),
what says the Lord to him?
"`Ask of me, and I will give you the nations for your inheritance,
and the uttermost parts of the earth for your possession.`" Ps. 2:8.
The Lord said in another place:
"`It is a light thing that you may be my servant, to raise up the tribes of Jacob,
and to restore the preserved of Israel; I will also give you for a light to the Gentiles,
that you may be my salvation unto the ends of the earth.`" Isa. 49:6.
Again the Lord says further: "`From the rising of the sun,
even unto the going down of the same, my name shall be great among the Gentiles,
and in every place incense shall be offered unto my name, and a pure offering.
For my name shall be great among the nations, says the Lord of hosts.`" Mal. 1:11.
"`Sing, O barren, you that did not bear!
Break forth into singing, and cry aloud, you that did not travail with child.
For more are the children of the desolate than the children of the married wife,
says the Lord.`" Isa. 54:1.
Who was the married wife?
Who was the mother in the days of the first covenant?
Was it not the Jerusalem below?
And who was then the desolate and barren one?
Was it not another Jerusalem which is free, and the mother of all the spiritual children?
Why was she now to rejoice and sing,
but because she was to break forth on the right hand and on the left,
and her seed was to inherit the Gentiles, and make the desolate cities to be inhabited?
ver. 3. For indeed, the covenant of Mount Sinai did bring forth a great people,
whereof Jerusalem below was the mother.
And the covenant made afterwards was as yet barren,
and did not bring forth a people to the Lord.
But this second covenant, and the Jerusalem above,
was to have a time wherein her seed would inherit the Gentiles, and the Maker,
the Husband, should be called the God of the whole earth. ver.5.

Read also Gal. 4, and see how the apostle of the Gentiles expounds the mystery,
showing which is the free woman with her free children,
and which is the bondwoman with her children of bondage.
For the children of bondage are cast out in the day of God,
and in the shining of his heavenly inward light,
and cannot inherit the glorious kingdom of the
gospel with the children of the free woman.

Now consider:
Who were the people in the time of the first covenant who obtained mercy?
Were they not the Jews?
And who was it that were not a people, and did not obtain mercy,
but were left out of the love and mercy of the first covenant?
Were they not the Gentiles?
And did not the Lord promise that he would "`have mercy on them that had not
obtained mercy`"? Did he not promise to say to them that were not his people,
"`you are my people;`" and they would say,
"`my God`"? (See Hos. 2:23. compared with Rom. 9:26.)
Was not this once gloriously fulfilled?
And is it not again gloriously fulfilled by now visiting them
again with the fresh sound of the everlasting gospel,
as was promised, Rev. 14:7.

But why should I mention any more scriptures unto you concerning this thing,
when you have so large, full, certain, and daily experience of it,
in that which is pure and living?
For you (spiritual Israel) are begotten by his Spirit into his own image and nature,
and have received the Spirit of adoption, wherein you cry, "`Abba,
Father,`" to the Father of spirits.
He found you indeed in a strange land, under great captivity and alienation from him.
You have been in Egypt, in Sodom, in Babylon, spiritually;
but the mercy of the Lord has followed you there,
and the arm of the Lord has reached to you there, and has wounded the Dragon.
Yes, he whom the Lord has given for a light to the Gentiles has shined to you there,
in the midst of your darkness.
For God sent among you the prophet like unto Moses,
Duet. 18:15 (though far above Moses), and hearing him, he led you out of Egypt,
and by the rod of his power he did signs and wonders and valiant acts
to break that power which held you captive and oppressed you.
And you have known the travel, trials, and temptations in the spiritual wilderness,
and the falling of the carcasses which were to fall there,
and the holy leading by the pillar of cloud and
fire through all the entanglements and dangers.
And truly, the faithful among you, the tried and prepared among you,
have passed over Jordan, the river of pure judgment, into the good land.
You have come to witness David and Solomon (who are one in Spirit) your King,
who rules in righteousness, and ministers to you peace everlasting.
And you have a High-priest there, not after the order of Aaron,
but after the order of Melchizedek, who is made the everlasting High Priest of God,
not after the law of a carnal commandment, but after the power of an endless life.
And now his lips preserve the knowledge of the law for you,
in that endless power of life, and he ministers for you and to you in that endless power,
and intercedes with power and efficacy, and sprinkles the blood of the covenant upon you,
which takes away sin from your hearts and consciences.
So that you know the inward Jew's state, the inward holy land and kingdom,
the inward circumcision, before you enter into that land.
You know the inward Lamb, the inward Passover, the inward Mount Zion and Jerusalem,
the inward sacrifices and incense, the inward tabernacle, temple,
and ark of the covenant, the inward shewbread, the inward manna,
the inward rod that budded,
the inward candlestick and lamps which are never to go out in God's temple.
And what more should I say?
All that that people were to be outwardly, in an outward way and state,
God has made you inwardly in the substance.
And what God would have been to them outwardly (had they only
obeyed his voice and kept his statutes and judgments),
that he is to you inwardly,
who are the called and chosen and faithful followers of the Lamb.
Oh, you are the enjoyers of their blessings and promises inwardly!
Oh, the glory of your state to the eye that is opened to see it!

Now, something does remain on my heart unto you.
Oh, remember what a great covenant God has prepared to make with you,
as you incline your ears to him, and are led by him into this holy agreement!
For it is a covenant which is not weak, as the old covenant was,
but rather full of virtue and power, to enable you to do whatever God requires of you.
Mark what it contains:
putting God's fear into you--not the fear which is taught by man's precepts,
which man may get into his carnal mind,
but that which God places as the treasury of life in the heart, as it is written,
"`The fear of the Lord and his treasure.`" Isa. 33:6.
And oh, who knows the preciousness of his treasure!
How it does cleanse the heart, and keep it clean,
and will not allow the mind that is seasoned with it, and kept to it,
to depart from the living God!
It protects from unbelief, from disobedience,
and will not permit the soul so much as to meddle with any appearance of evil.
Oh, precious, glorious, blessed treasure!
Happy is the man that fears always with this fear!

Another precious thing this covenant contains
is this--the law written in the heart.
For this law shall be as near, yes even nearer, than sin is,
in the heart that is made tender, and has the law of the Spirit of life written in it.
Who knows what it is to have the law of love, the law of life, the law of the Spirit,
the law of faith, the law of new obedience, livingly written by God in his heart?
Surely none can know but those in whom God writes it!
And such cannot help but desire to have it written in
their hearts by his blessed finger daily more and more.
But this covenant contains yet more--even the putting of his own Spirit within,
to be a fountain of life there, a fountain of strength and wisdom there,
to make them more and more willing in the day of his power.
And this Spirit will cause them to walk in his ways, and keep his statues and judgments,
and do them, so that the Lord their God may bless them and delight in them.

Oh, who would not long after, and take up the cross and shame,
in order to enjoy the glory of this state?
Oh, what has God done for a poor despised remnant among the Gentiles!
Oh, who would not desire to keep this blessed covenant with the Lord,
that he might fully enjoy the Lord,
that the marriage with the Maker might be witnessed in
his loving kindness and everlasting righteousness,
and all unrighteousness and uncleanness might be put away, removed,
and separated from the heart forever!
Ah, the virgin spirit which the Lamb loves and delights to
marry! "`He that is joined to the Lord is one Spirit.`"
And he that would be joined to the Lord and be one
Spirit with him must part with all that is old,
evil, unclean, and corrupt in him.

Oh, who would lose the precious fear of the covenant,
which is clean and endures forever, and keeps clean and chaste to the Lord forever!
Who would miss even one law which God has to write in the hearts of his children,
when every law is a law of life, and changes the mind into the nature of the lawgiver!
And who would grieve God's Spirit, which is our Comforter,
or quench that which kindles the pure flame of love and life in our hearts!
Or how could one of his dear and tender children be willing to vex him,
by manifest carelessness and disobedience towards the
one who gives us to drink of the river of his pleasure.

=== A Few Words to England, My Native Country

O Land of my Nativity!
O my dear Countrymen!
The pure power of the Lord is upon me, and the springs of life are opened in me,
and among many other things, I am melted in love and desires after your welfare.
And this is in my heart to say to you: If I now testify to you in truth of a pearl,
a heavenly pearl, an everlasting pearl, will you not hear me?
If I tell you your heart is the field, or earth, wherein it is hid,
will you not consider it?
If the everlasting gospel is preached again,
which contains true tidings of redemption from sin, will you not listen to it?
If the kingdom of God, and righteousness of Christ, is to be revealed within,
would you not willingly learn to wait for it there,
and beg of God that the eye may be opened in you
which alone can see it when it does appear?

Indeed, God's visitation is upon this nation in a special manner;
his light and power is breaking forth in it against the
darkness and power of the spirit of Satan,
which has captivated and still captivates many.
You desire outward liberty, and the enjoyment of your outward rights;
but would you not be free inwardly?
Do you not desire to be free from the base, earthly, selfish nature and spirit,
which man (fallen from God, and the glory wherein he created him) is degenerated into?
Oh, is not the power of God and the life of Christ able to restore man?
He that created man at first so glorious, in his own image,
is he not able to create him anew?
Oh listen, my dear countrymen!
The power is revealed which creates anew;
and they that receive it (and are as clay in the hands of the great Potter,
given up to be formed by it), are daily created anew into a holy, heavenly, innocent,
living, tender, righteous frame, day by day.
They are made willing, daily more and more, to be the Lord's, in this day of his power;
and to receive power to become sons, and strength against their soul's enemies.
For the glorious work of redemption which God has begun in them,
is carried on in them by the arm of his strength,
to their comfort and his everlasting praise.

There is a spiritual Egypt and Sodom, just as well as there was an outward.
There is a spiritual wilderness, and a Canaan also;
and the arm of God's power inwardly and spiritually has
been revealed in this spiritual Egypt,
wilderness, and Canaan, as truly as ever it was in the outward.
Do you not read of an inward Jew, and an inward circumcision, and the inward leaven,
and keeping the feast of unleavened bread, even of bread that is not leavened with sin?
And he that eats of the unleavened bread, it unleavens him of sin,
and leavens him with life and holiness; for it is a holy bread, and a living bread.
This is the bread which comes down from heaven, which they that feed upon live,
and they that live do feed upon.
And though they be many, yet feeding upon this bread, they become one bread,
one living body, consisting of a living head, and living members.
For the same life and pure heavenly nature which is in the head,
is communicated by him to the members.

But how shall we find this, some may ask.
I will tell you how we found it, and how none can miss it,
who sweep the house and make a diligent and faithful search after it.
That in the heart of man which turns against sin, discovers sin, draws away from sin,
and wherein God ministers help against sin,--that is it.
That is the pearl hid; that is the kingdom hid;
in that is the righteousness of God revealed from faith to faith,
in all that receive and give up to this holy leaven.
This seed is of the nature of God and Christ.
This is a measure of his light, of his pure life.
This is the law and everlasting commandment,
which God writes in the hearts of his spiritual Israel.
For the inward Jew has inward tablets where the inward law is written,
for the inward eye to read.

Oh, how near is God inwardly to the inward people in this our day!
Oh the pure glory has broken forth!
But alas, men are in their several sorts of dreams, and take no notice of it.
What shall the Lord do to awaken this nation?
In what way shall his power appear, to bring down unrighteousness,
and to bring up righteousness in the spirits of people?
Do you not think the Lord has been at work?
Oh, take notice of the handiwork of the Lord, you children of men,
and wait to feel truth near.
Oh, partake of the living virtue and power of it,
that you may feel your hearts created anew,
and the old heavens and earth inwardly passing away, wherein dwells unrighteousness,
and the new heavens and the new earth inwardly being witnessed,
wherein dwells righteousness.
Oh that everyone might be sensible of his presence, power, kingdom,
and righteous government inwardly in the heart, from the king that sits on the throne,
to the beggar on the dunghill!
Surely man was not made for himself!
Surely he was not made such a creature as he now is, but rather in the holy image of God,
with love in his heart to God above all, and to his neighbor as to himself.
Oh, what good are the religions and professions of those where this love is not found?
The Lord is restoring his image, and bringing forth the true, pure religion again.
The pearl, the truth, contains and comprehends it.
Oh, buy the pearl!
Oh, buy the precious truth!
Sell all that is contrary to it for it!
Take up the cross to all that is evil in you, as the light in you makes it manifest!
Then you shall have the free possession of it in your heart,
and feel it to be a root of life, a treasure of life, a well of life,
out of which the living water will be daily springing up in you unto life everlasting.
Amen.

=== The True Church and Ministry Under the Gospel

[.discourse-part]
Question: What is the true church, or the gospel church,
or the church according to the new covenant?
(For there was an old covenant, and a church according to that, under the law;
and there is a new covenant, and a church according to that, under the gospel.)

[.discourse-part]
Answer: To answer this, let us inquire and consider what the new covenant is,
and then it will more easily appear what the church according to the new covenant is.

The new covenant, according to plain scripture,
and according to manifest experience in this blessed
day of the shining of the gospel light in men's hearts,
is this: God putting his law in the inward parts of his people,
writing it in their hearts, becoming their God and making them his people,
and teaching them all to know him (inwardly and
experientially) from the least to the greatest,
being merciful to their unrighteousness and
remembering their sins and iniquities no more.
Jer. 31:33-34, Heb. 8:10-12.

Now if this is the new covenant (the covenant of the gospel church),
then they are the church who are the people of God according to this covenant.
These have the law put by God into their inward parts and written in their hearts,
and so according to this law and covenant, they have God to be their God,
and they are his people, and are taught by him to know him (as it is written,
"`All my people shall be taught of the Lord,`" Isa. 54:13.
and John 6:45). To these God has been merciful,
and their sins and iniquities he remembers no more,
having been washed away from their consciences by the blood of the
everlasting covenant (which the blood of bulls and goats could never do).
So that this is the New Testament church (or gospel church)--a church of inward Jews,
even as the law church was a church of outward Jews.
It is a church of inward worshipers, of worshipers in Spirit and in truth, John 4:23,
even as the law church was a church of outward worshipers.
It is a church of inwardly circumcised ones,
even as the law church was a church of outwardly circumcised ones. Rom. 2:29.
It is a church of such as are inwardly holy,
even as the law church was to be a church of such as were outwardly holy.
It is a church of such as offer inward incense and sacrifices,
even as the law church was a church of such as offered outward incense and sacrifices.
It is a church of inwardly redeemed ones from the inward Egypt,
from the inward darkness and power of Satan,
even as the law church was a church of such as were redeemed from the outward Egypt,
and the power of outward Pharaoh.
It is a church that has the inward ark (Rev. 11:19), the inward presence,
the inward manna, etc.,
even as the outward church of the Jews had these things outwardly.

[.discourse-part]
Question: What is the true gospel ministry, and who are the true gospel ministers?

[.discourse-part]
Answer:
Those whom Christ sends forth in the Spirit and power of his
Father to gather and build up this new covenant church.
Christ had all power in heaven and earth given him, even to this very end--to gather,
defend, and build up his church.
He bid his apostles to wait for the same power,
and even now sends forth his ministers in the same power,
that they may be able ministers of the gospel, which is not words but power,
even the power of God unto salvation. Rom. 1:16.
The new covenant stands not in the letter, but in Spirit and power.
Those who are the ministers of it must receive life, Spirit, and power from Christ,
or they cannot nourish and build up his members.
They must preach and minister to the world in this power, Spirit, and life,
or they are not able to gather others out of the world into it.

Christ, the Lord of his church, the foundation of life in his church,
the everlasting rock, is a living stone, and his church is built of living stones.
How can anyone minister life unto them, or build them up in the life, Spirit, and power,
besides those who are in the life, Spirit, and power,
and who receive from the Head to further quicken and build up the living members?
The milk which nourishes the living babe is living,
and must come pure from the breast of life,
and not be mixed with man's wisdom or brain inventions.
What then must the bread and wine and water of the kingdom be,
upon which the children and heirs of the kingdom must feed and be satisfied?
The ministers of the gospel are stewards of this heavenly life, this heavenly Spirit,
this heavenly power, this heavenly treasure, which they have in earthen vessels,
and which God enables them to bring forth for the feeding of his lambs and sheep.
Christ said unto Peter, "`Do you love me more than these?`"
Peter answered him, "`Yes, Lord, you know that I love you.`"
If it be so, "`feed my lambs, feed my sheep,`" said Christ to him.
But how should he feed them?
With what should he feed them?
All power, says Christ, is given me in heaven and in earth,
and I am to ascend to my Father to receive the fullness of his Spirit.
If you wait, you shall receive abundantly of the same Spirit and power,
and then in that Spirit and power you shall be able to feed my
lambs and sheep that are begotten and gathered to me.
But apart from this Spirit and power, none is able to feed and build them up,
for this alone is the thing with which they are to be fed,
and in which they are to be built.

Indeed, a man may be a minister of the letter, a minister of the law,
without the Spirit and power.
But such a one cannot possibly minister the gospel, for it consists not in letter,
but in Spirit, 2 Cor.
3+++.+++ And the faith that is to be begotten in the
gospel is not to stand in the wisdom of man,
but in the power of God.
The gospel state, the gospel church, the gospel building, begins in the power,
is carried on in the power, and is finished or perfected in the power.
The whole ministry of the gospel is to partake of this power, and minister in it,
otherwise they can do nothing in this work.
Christ Jesus our Lord began it in this power, and none can carry it on without this power.
The Lord God of glory laid the foundation--"`Behold, I lay in Zion for a foundation.`"
etc. Isa. 28:1,16 Pet.
2:4-6. And the quickening Spirit alone is able to make living and spiritual stones.
The Lord alone is able to build them up by the operation of this Spirit and power,
and they that are the true ministers of the gospel are to wait for it daily from God,
so that they may minister in it.

[.discourse-part]
Question: What is the maintenance of the ministers of Christ,
or what is to be the maintenance of the true ministers under the gospel?

[.discourse-part]
Answer: Christ, who has sent them forth to minister in his name, has provided for them;
and they that are his true ministers are satisfied with what he has provided for them, Matt. 10:10.
These are careful not to make the gospel,
which is to be an inward blessing, outwardly chargeable to any.
The mind of the true minister is concerned with the
service of Christ--how he may be faithful to him,
gather souls to him, feed others with the bread of life from him.
He is not concerned with what he shall have from men for so doing,
for such ministers covet no man's gold or silver, etc.

=== The Everlasting Gospel

The blessed message which the apostles (who were sent
by Christ to preach the gospel) heard of Christ,
and were to declare to others was this: "`That God is light,
and in him is no darkness at all.`" 1 John 1:5.
The goal of Christ's sending them with this
message was that thereby (preaching it in the evidence and
demonstration of God's Spirit) they might "`open men's eyes,
and turn them from darkness to light, and from the power of Satan to God,
that they might receive forgiveness of sins,
and an inheritance among them that are sanctified by faith that is in him.`" Acts 26:18.

Now, as the eye of the mind is opened,
and the mind is turned from the darkness within to the light within,
and from Satan's power to the power of God (which is revealed in the light),
the soul in the light comes to see (over the darkness,
and over Satan who darkened it) the things of God and his kingdom.

First, it sees him who is the rock, the holy foundation of God,
the holy foundation of life in the soul, the living stone,
by which all the other living stones are made alive.
These are taught of God to come to him as to a living stone, and so are built upon him,
and become God's building, and new creation in him.
1 Pet. 2:2,5 Cor. 5:17. And here, in this light, none can miss the true coming,
hearing the voice of the Father, and being drawn and taught by him to come to the Son. John 6:44-45.

Second, here the true Jew's state, the state of the inward Jew,
and the inward circumcision,
and the true worship (even the worship of the Father in Spirit and truth) is known.
For the inward Jew is a child of light, begotten in the light, redeemed out of darkness,
who dwells and walks in the light, as God is in the light. 1 John 1:7.
And the circumcision is not a fleshly act,
but rather the cutting off of that which is fleshly
from the mind by the Spirit and power of Christ.
And the gospel worship, or the worship of the inward Jew,
is the worshiping of God in the newness of the life of his Son.

Third, here is the true repentance from the dead nature and dead works,
which no man can attain to of himself, but is God's gift through his Son.
For God has appointed Christ to be a Prince and a Savior,
to give repentance and forgiveness of sins. Acts 5:31.
It is here that repentance is known, waited for, and received.
For it is not to men who are in the darkness, loving the darkness,
that the true repentance is given,
but to those who are turned to the light--to them is repentance given unto life.
Acts 11:18, compared with chap.
26:17-18.

Fourth, here the true faith, the precious gift of faith, is received,
whereby men believe in him who gives life, and receive life from him.
And this is the faith which gives access to God,
and gives victory over the world and all that is contrary to God.
Indeed, the faith which is given in the light does so,
but the faith which men hold in the darkness does not do so.

Fifth, here is the cross of Christ known, which is an inward, living,
spiritual thing, effectually crucifying the man that takes it up and daily bears it,
to all that is earthly and sinful.
Then the pure seed and life of Christ springs up in his earth,
rising over the world and every worldly thing. Gal. 6:14.

Sixth, here the pure love springs in the heart, both to him that begets,
and to him that is begotten.
In the light there is nothing but love,
but in the darkness there is no true love to be found;
and even the love that is found there is of the nature of enmity.
It is the light of truth that purifies the heart to unfeigned love.
1 Pet. 1:22, Duet. 30:6.

Seventh, here the Lamb's patience and meekness is experienced,
and the soul is adorned with it.
The Lamb is the light of the world,
and they that are made lambs by him partake of his sweet and meek nature,
learning of him to be meek and lowly in heart,
and so have that patience and meekness from him which no other can attain to. Matt. 11:29.

Eighth, in the light, the precious promises are fulfilled and experienced,
which make those who partake of them (in whom they are
fulfilled) partakers of the divine nature.
For the divine nature is not partaken of in the darkness, but rather in him who is light.
Man (who is darkness) cannot partake of the
promises which belong to the children of light.
But when, by the operation of God's power, his state and nature are changed,
and he is now no more darkness, but light in the Lord,
then he has his share in the promises which were made to the children of light.
Eph. 5:2,8 Pet., 1:4.

Ninth, in the light, the holy anointing is received,
the voice of Christ is heard,
and the new everlasting covenant (even the sure mercies of David) is made with the soul. Isa. 55:3.
The law of the new covenant (even the law of
the Spirit of life in Christ Jesus) is written in the mind,
and the holy fear of the new covenant, which cleanses and keeps clean,
is put in the heart.
The blessed Spirit of the Father is given and received,
which gives power (in those who receive it) to become the sons of God,
causing them to walk in his ways, and to keep his statutes and judgments, and to do them.
Oh that the sons of men would hear and understand this
precious lovingkindness of the Lord,
and put their trust under the shadow of his wings,
and know what it is to be satisfied with the fatness of his spiritual gospel house,
and to drink of the river of his pleasures, and in his light to see light! Ps. 36:7-9.

Tenth, in this light the true church, the gospel church,
the New Testament church, is known.
This is the church of the children of light, a building built in the light,
which church is in God the Father, and in the Lord Jesus Christ, 2 Thess. 1:1,
in whom they are built together for a habitation of God through the Spirit. Eph. 2:22.
Yes, in him all the building, fitly framed together,
grows into a holy temple in the Lord,
ver. 21. And all that are here gathered out of the darkness into the light,
who walk in the light, and abide in the light,
are built upon the foundation of the apostles and prophets,
Jesus Christ himself being the chief cornerstone, ver. 20,
and are no more strangers and foreigners, but fellow-citizens with the saints,
and of the household of God, ver. 19.

The gospel church is the spiritual house of Jacob,
which walks in the light of the Lord, Isa. 2:5.
These go up to the mountain of the Lord (to that
which is revealed to be the mountain of God in the last days,
even spiritual Mount Zion, Heb. 12:22), to the house of the God of Jacob,
where he teaches his spiritual people, the inward Jews, his ways,
and they learn to walk in his paths.
For out of this Zion shall go forth the law of the Spirit of
life in Christ Jesus (in the days of the gospel),
and the word of the Lord shall proceed from this Jerusalem, Isa. 2:3.
For the Jerusalem above is free,
which is the mother of all the children which are born of God's Spirit.
Gal. 4:26, John 3:6. And she being the mother of them all,
nourishes them all with the Word of life, which goes forth from her,
and all her children know her. Matt. 11:19.
Oh that all, both Catholics and Protestants,
knew this true mother church, this mother of all the living,
who nourishes the living with the law and Word of eternal life!
