[#ch9, short="Life and Immortality Brought to Light"]
== Chapter IX. Life and Immortality / Brought to Light by the Gospel

=== Two Questions Concerning God`'s Teaching

[.discourse-part]
Question: What is the reason that others cannot learn, nor become subject to,
the same spiritual truths which God makes manifest to us, and subjects our spirits to?

[.discourse-part]
Answer: The reason is because they do not learn the same way that God teaches us.
And so, though they may have many advantages above us in natural abilities, learning,
etc., and study hard to know much,
yet not coming into the right way in which God`'s Spirit teaches,
they never come to learn the truth.

[.discourse-part]
Question: But what is the way wherein God teaches you?

[.discourse-part]
Answer:
This is the way God teaches us--by giving us an understanding to know him that is true,
and by opening an ear in us to hear his voice.
And so, being kept within the limits of that understanding and that ear,
we come to hear and know aright.

"`Take heed,`" said Christ, "`how you hear.`"
Oh, the Lord has made us sensible of the weight of that scripture!
And we have often experienced that it is easy to hear amiss, and read amiss,
and pray amiss, and believe amiss, and hope amiss;
but it is hard to do any of these aright.
Therefore, we are taught to wait for the stirring of the waters,
for the moving of God`'s Holy Spirit upon our spirits.
Only then is healing virtue and ability felt and
received from him to perform what he requires.

Thus, when we read the Scriptures, our eyes are towards him,
and we watch against our own understandings,
against what we could gather or comprehend of ourselves.
And we wait to feel how he will open our spirits,
and what he will make manifest to them when they have been opened.
And if he drops down nothing, we gather nothing; but if he gives light,
then in his light we see and receive light.
So in praying, we wait to feel the birth of life (which is of the Father,
and which the Father hears) breathe in us;
and so far as the Spirit of the Father breathes upon the soul,
and it breathes to the Father, that far we can pray.
But when life stops, we stop, and dare not offer up to God any sacrifice of our own,
but only what the Father prepares and gives us.
So in eating and drinking, and whatever we do, our heart is retired to the Lord,
and we wait to feel everything sanctified by his presence and blessing, and indeed,
here everything is sweet unto us.
And in whatever God enables us to do, we narrowly watch to that direction of Christ,
"`not to let the left hand know what the right hand does.`"
For we are nothing of ourselves, nor can we do anything of ourselves.
Therefore, whatever is done in us, is done as we feel the grace of God,
the virtue and power of his life, working all in us.

And in this temper of spirit we find nothing too hard for us.
For the strength of Christ is always at hand, even in the midst of our weakness;
and the riches of the kingdom are always at hand
in the midst of our poverty and nothingness.
And his strength works,
and our weakness does not hinder the glory of him that works through it.
And so we are assured, by a constant sense and daily experience,
that it is not by our willing or running according to our wisdom and strength,
that we can attain anything, but by God showing mercy to us in Christ.
We therefore daily wait at the posts of God`'s heavenly wisdom,
to feel the gate of mercy and tender love opened to us,
and mercy and love flow in upon us,
whereby we obtain what our hearts desire and seek after.
Blessed be the Lord forever!

And truly here in the springings of love and openings of mercy from our God,
we have fellowship with the Father and Son, and one with another,
in the Holy Spirit of life.
And we testify of these things to others,
that they also may come into the same fellowship,
and be of the same faith which flows from, and abides in, the power and life eternal.

May the Lord guide all tender, breathing, panting spirits here,
that they may be satisfied in the goodness and lovingkindness of the Lord,
and may eat abundantly of the fatness of his house,
and drink of the rivers of his pleasures,
and no longer wander up and down in their own barren thoughts, apprehensions,
and conceivings upon the Scriptures.

[.offset]
// lint-disable unexpected-asterisk
*The Threefold Appearance of Christ*--Namely:
Under the Law, In the Body of Flesh, and in His Spirit and Power.

__First__--His appearance under the law.
Various were the appearances of Christ under the law.
Sometimes he was as an angel, or in the likeness of a man (as to Abraham, Jacob, Joshua,
and Moses, etc.). Also,
the appearances of God to the prophets in visions were often the appearances of Christ;
as particularly, that glorious appearance of God sitting upon a throne,
and his train filling the temple, and the Seraphim crying,
"`Holy! Holy! Holy is the Lord of hosts; the whole earth is full of his glory!`" Isa. 6:3.
This was an appearance of Christ to Isaiah, as is manifest by John 12:41,
where the Evangelist (relating to that place) uses this expression:
"`These things said Isaiah, when he saw his glory, and spoke of him.`"
Also, he was the angel of God`'s presence who went before the
Jews in all their journeys and travels out of Egypt,
through the sea, in the wilderness, and in the time of the Judges,
and who wrought all their deliverances for them, as is signified in Isa. 63:9,
"`In all their afflictions he was afflicted,
and the angel of his presence saved them,`" etc.
So too with the three children,
he appeared in the midst of the fiery furnace in a form like the Son of God. Dan. 3:25.

Now, indeed,
the whole law was a shadow of him who was to come to be the substance of it,
and to perform inwardly in the heart that which the law represented in outward figures.
Thus Moses and all the prophets were forerunners of him
who is the great prophet of the spiritual Israel of God.
All the priests, especially the high priests, were types and forerunners of him,
and were meant to end in him, who is the high priest over the household of God forever.
The judges and saviors were types of him who is the great Savior and Redeemer,
for they saved not by their own strength, but by his Spirit and power coming upon them,
so that the yoke (which was made and brought
upon them by their rebellion against the Lord,
and disobedience to his law) was broken because of the anointing.

David, Solomon, and the good kings were types of him-- David,
in his conquest over his spiritual enemies; Solomon, in his ruling Israel in peace,
after he had conquered their enemies.

Circumcision was a type of his circumcising the heart,
that his children (his holy seed) might love the Lord their God with all their heart,
and live.

The Passover, and blood of the lamb,
was a type of his blood sprinkled upon the conscience,
which preserves against the stroke and power of the destroyer;
and so God passes over all such, when he visits for sin and transgression.

The outward Sabbath was a type of the pure rest which
Christ gives to those that believe in his name.
For indeed, they that truly believe in him do enter into rest,
and cease from their own labors and workings of themselves,
and witness God`'s working in them, "`both to will and to do of his good pleasure.`"

The outward law in the letter, written in tablets of stone,
was a shadow of the inward, living, pure, powerful,
spiritual law of love and life which God writes in the hearts of his children,
which constrains them to obedience,
and enables them to do all that God requires of them with ease and delight.
For truly the yoke of his law is easy, and the burden of his commandments is light.
They are not at all grievous to them that are under, and in subjection to, his Spirit.
For when the mind is gathered,
and brought from under the spirit and power of darkness into his Spirit and power, oh,
how easy it is to believe, to love, to obey, etc.! Indeed there is nothing but love,
and faith, and obedience, and life, and righteousness, and holiness, and pure power,
and peace, and joy here.
"`For the old things are passed away,
and all things are become new in Christ,`" to them that are in the new creation in him.

So too Canaan, the Holy Land, represented the land of life, or country of life,
into which God gathers, and in which he feeds and preserves all the living,
whom he gathers out of the territories of death and darkness.
And the plenty and fullness of the land of Canaan, and the sweet rivers therein,
signified the abundance of rich things, and the rivers of God`'s pleasure,
where his redeemed ones drink as they come to
live and dwell and walk and sup in and with him.

Jerusalem, the holy city, was a figure of the New Jerusalem,
the spiritual Jerusalem, the heavenly Jerusalem,
which is the mother of all who are born of the Spirit.
The hill upon which Jerusalem was built signified God`'s holy mountain,
whereupon his city is built.
The inhabitants of the outward Jerusalem signified the
inhabitants of the new and inward Jerusalem.
The temple signified Christ`'s body, and the bodies of the saints,
which are temples in which the Holy One dwells in the midst.
The altar in the outward temple signified the altar in this inward temple,
which all the true, inward, spiritual Jews have right to partake of, and none else.
The fire in the outward temple, and the candlesticks,
and the lights which were never to go out,
signified the holy fire in the spiritual temple, which comes from heaven,
and with which all the spiritual sacrifices are to be offered up.
The candlestick is to hold the light (and the priests to keep
the lamps burning) or God will remove it out of its place.
So too the holy garments of the priests signified the robes of righteousness, innocence,
and purity,
with which the people of God under the gospel (who are
a royal priesthood to him) are to be clothed.

The ark signified that which holds the law of the new covenant,
and the pot of manna showed with what kind of food God
fed and nourished the soul in the wilderness,
before he brought it into the Holy Land.
For indeed, Christ appeared to, and was with, that people in the wilderness,
in a cloud by day, and in a pillar of fire by night,
which signified the leadings of God`'s Spirit in the day of the gospel. Isa. 4:5.
And he was the rock that followed them,
and the manna of which they did eat, and the water of which they did drink.
For they did eat and drink of the heavenly things in a figure,
and as their spirits were at any time opened,
they had a taste and sense of the true food, in and through the figure.
Yes, doubtless, at sometimes they had a sense,
and did eat of the same spiritual food of which we now eat,
"`and did all drink of the same spiritual drink`" of which we now drink, 1 Cor. 10:3-4.
For they were not only all under the cloud,
and did not only all pass through the sea,
but they were also all baptized in the cloud and in the sea,
having a sense of the pure power of the Lord,
and of his outstretched arm made bare for them.

Likewise there was Aaron`'s rod that budded, laid up in the ark,
which is the evidence of the true priesthood and ministry forever.
This priesthood is not to be spurned against, but still to be acknowledged and honored,
as of God.
In this ark were also the tablets of the law, which represented the true ark,
wherein are the tablets of the law of life, which God writes by the finger of his Spirit,
and appoints to be kept in the spiritual ark forever.

Above the ark was the mercy-seat, with two cherubim of glory,
one at each end of it, spreading their wings on high over the mercy seat.
Between these God dwelt or sat, and he met and communed with Moses,
and with the priests under the law, when they came to worship him and inquire of him.
This was a figure of the true mercy seat under the gospel,
where the true priests (the true circumcision,
the spiritual Israel of God) have access with boldness to the throne of grace.
And through the high priest of their profession,
they may obtain mercy and grace to help in time of need.

So too under the law, all the sacrifices (the sin offering, the peace offering,
the thank offering, the heave offering, the wave offering, the whole burnt offering,
the meat offering, the drink offering, etc.) signified Christ,
the one true offering who comprehends them all,
which the spiritual people (the priests of the gospel) are daily to offer up to God.
And the sweet spices, frankincense,
and odors signified the sweet seasonings of the gospel sacrifices with grace, with salt,
with the Spirit, with the fresh breathings of life, with innocency, meekness, tenderness,
zeal, faith, love, etc., which yield a most pleasant scent in the nostrils of the Lord.
Oh, how precious it is to read the figures of the heavenly things with true understanding!
But to read _through_ the figures (with the eye of life,
with the eye of the Spirit) into the invisible substance,--this is sweet, precious,
and heavenly indeed!

[.small-break]
'''

__Second__--Christ`'s appearance in a body of flesh.
When the time of these shadows drew towards an end, and the fullness of time was come,
he who thus appeared in several types and shadows now came down from the Father,
debased himself, and clothed himself like a man, partaking of flesh and blood.
In all things he was made like unto us (except for sin;
for he was the Lamb without spot) humbling himself to come under the law,
and under the curse,
that he might redeem those that are under the law (and under
the curse) by fulfilling the righteousness thereof,
and bringing them through into the everlasting righteousness.

Now, in this body he finished the work which his Father gave him to do.
He fulfilled all righteousness (the righteousness of the letter,
the righteousness of the Spirit) that he might bring his
people through the righteousness of the law or letter,
into the righteousness of the Spirit and power, that is,
the righteousness of the new life.
His whole life was a doing of the will of the Father who sent him.
And when the Spirit of the Lord was upon him, moving him to preach the gospel,
he preached the gospel in the Spirit and power of the Father, and went about doing good,
and healing all that were oppressed of the devil,
as his Father`'s Spirit led and guided him.
For he did nothing of himself, or in his own will, or for himself;
but did all in the will and time of the Father.

Thus he did always please his Father, and seek the honor of him that sent him.
He was obedient unto death, even the death of the cross,
being willing to drink of the cup which his Father gave him to drink.
And so, having finished his work,
he returned from where he had come and sat down at the right hand of the majesty on high,
being exalted above all principalities, and powers, and dominions, both in this world,
and in that which is to come.

[.small-break]
'''

__Third__--Now, the third appearance of Christ (which these two outward
appearances made way for) was his appearance in Spirit,
even his pure, inward, heavenly appearance in the hearts of his children.
This he bids his disciples to wait for, telling them,
"`that he would not leave them comfortless, but would come again to them.`"
They had known the appearance of the bridegroom in the flesh, and he was to go away.
It could not be helped; it was necessary for them that he should go away; but (says he),
"`I will come again.`"
The same power and presence that is now with you in a body of flesh,
shall visit you in Spirit, and so abide with you forever.
For he that is now with you shall be in you, and until that time you shall have sorrow,
and be like a travailing woman.
The world, in the meantime, shall rejoice; "`but I will see you again,
and your heart shall rejoice, and your joy no man will take from you.`"
And was it not so?
Did not Christ send the Spirit, the Comforter?
Did he not come in the Spirit and power of the Most High to be with them always,
even to the end of the world?
Did he not bid them "`stay and wait at Jerusalem`" for
that appearance of him in his Spirit,
and not go about his work and message till he came in the
power and authority of his Father to go along with them?
And did not their hearts rejoice when he came with joy unspeakable, and full of glory?
Did they not then have the joy and peace which passed all the understanding of man,
which joy and peace none could take from them?
Yes, truly, in the kingdom, Spirit,
and power of our Lord Jesus Christ there is a seeing eye to eye.

Truly this administration of the Spirit
and power of the gospel is exceedingly glorious,
and they that come into it come into the glory and heavenly dominion
and authority of the Lord Jesus Christ (and so are made kings by him,
and wear crowns in his presence, though they still cast them at his feet),
and are changed from glory to glory.
These behold, as in a mirror, the glory of the Lord,
which none can do but with the eye that is in some measure changed and glorified.

Now, this dispensation of the gospel, Spirit, and power,
began in the apostles`' days, and the church was exceedingly chaste, pure,
and beautiful then, without spot or wrinkle.
But there was a falling away after this, and a thick dark night,
and a very great and universal apostasy from the Spirit and power of the apostles.
Many departed out of the fear of the Lord into high-mindedness,
and did not keep their standing in the faith, and love, and obedience of the truth;
but held to a form of godliness outside of the power.

=== Concerning Mount Sinai and Mount Zion

Was not Sinai the mountain that could be touched, an earthly mountain,
from which came the ministration of the outward law, or letter, which led to bondage,
condemnation, and death?
Does not the apostle Peter say, concerning the law as so administered,
"`that it was a yoke too heavy for them or their fathers to bear`"? Acts 15:10.

Is not the gospel`'s Zion a spiritual mountain, a heavenly mountain,
a mountain that cannot be touched by human senses,
a mountain from which comes the ministration of the Spirit, the ministration of liberty,
the ministration of life, the ministration of the glory that exceeds?
Is this not the holy mountain, upon which the holy city (the New Jerusalem) is built,
and where the King of Righteousness rules in
righteousness and peace over all his subjects,
and where he makes them the feast of fat things, and sups together,
eating and drinking the bread and wine of the kingdom, even the living bread,
and the fruit of the living vine?

"`You are not come (says the apostle) to the mount that might be touched,
and that burned with fire, nor unto blackness, and darkness, and tempest,
and the sound of a trumpet, and the voice of words, etc., but you are come to Mount Zion,
and unto the city of the living God, the heavenly Jerusalem,`" etc.
Heb. 12.

Now, Mount Sinai was that mountain of earth which the voice and presence
of the Lord shook at the ministration of the outward law.
But there is an inward earth which is to be shaken also,
even the nature which transgressed,
the nature that was subject to sin and under the curse,
the earth which brings forth briars and thorns.
Into the earth the plow of the Lord must go, to break it up and overturn it,
that there may be a new earth formed, fit to receive the heavenly seed,
and bring forth fruit to God.
Yes, not only the earth, but also the heavens, are to be shaken and removed.
"`But yet once more, says the Lord, I shake not earth only, but also heaven;
which signifies the removing of those things that may be shaken,
that those things which cannot be shaken may remain.`"

There is that which is changeable, and there is that which is unchangeable.
The old earth and the old heavens are changeable;
the new heavens and the new earth are unchangeable.
There is a changeable mind, a changeable spirit, a changeable nature, a changeable will,
a changeable wisdom,
a changeable reason and understanding (which blows this way and that),
and a changeable knowledge of God, which man learns not from the Spirit of the Lord,
but after a traditional way, by hunting with his own mind,
and drinking knowledge into that part which is old and earthly.
There man kindles his own fire, with which he warms himself,
gathering unto himself peace and joy, hope and confidence, etc.
But when the Lord appears,
and his voice is heard (when he arises to shake terribly the earth, yes,
and the heavens also), all these will be shaken,
and will fall like untimely figs at the rushing of a mighty wind and terrible tempest.

For the day of the Lord, the day of his pure appearance,
the day of the brightness of his rising, will be upon all that is high and lofty,
and upon all that is proud and lifted up above the pure seed.
Every cedar of Lebanon and oak of Bashan that is high and lifted up,
every high mountain and hill that is lifted up, every high tower, and fenced wall, etc.,
shall all feel the terror of his majesty, and only that which is of the pure seed,
gathered into the seed, and changed into the nature of the seed, shall stand.
Nothing else shall be able to dwell with the devouring fire and everlasting burning.
And so it may be very well said, "`Who may abide the day of his coming;
and who shall stand when he appears?
For he is like a refiner`'s fire, and like fuller`'s soap;
and he comes with his fan in his hand, to fan away the chaff.
And he shall sit as a refiner and purifier of silver, to purify the sons of Levi,
and purge them as gold and silver,
that they may offer unto the Lord an offering in
righteousness... pleasant to the Lord,`" Mal. 3:2-4,
which none can do but those that are purified by him.

Oh happy will they be,
whose religion and worship in that day will stand the trial, and bear the fire!
And oh, blessed forever be the Lord, who has come near for judgment,
and is a swift witness against all deceit and unrighteousness;
but is a justifier of those whose consciences he has sprinkled with the blood of Jesus.

But now, as the Lord takes away the old, so he brings in the new.
As he removes the old earth and the old heavens, wherein dwelt unrighteousness,
so he forms and brings forth the new heavens and the new earth,
wherein righteousness dwells.
And here the kingdom is known and received which can never be shaken.
Here is the Mount Zion, which shall never be removed,
and the Jerusalem whose stakes or cords shall never be plucked up or broken.
Here is the city which has everlasting foundations, whose builder and maker is God.
Blessed are they that come and dwell here,
who are not come to the mountain that may be touched and shaken and removed,
but to the holy mountain of God, upon which all the buildings of life are raised,
and upon which they stand firm forever.
For the Lord of Hosts, who has created the new heavens and new earth,
has created Jerusalem a rejoicing, and her people a joy,
and they shall be glad and rejoice in him, forever and ever.
Amen

=== The Temple and Sacrifices Under the Gospel

God`'s temple under the gospel is the light of his Son, the Spirit of his Son,
and those souls which are renewed,
and built up as a habitation for him in the Spirit of his Son,
and also those bodies in which renewed minds and spirits dwell.
God is light, and he dwells in light.
God is Spirit, and his building is holy and spiritual,
for he dwells in nothing that is dark or corrupt or unclean.

Now, that which is sacrificed or offered up to God must be clean and pure.
No unclean thought, no unclean desire,
nothing that is earthly or fleshly or selfish must be offered up to God,
but rather the pure breathings of his own Spirit.
For whatsoever is of him, and comes from him, is accepted with him.
But whatever man can invent or form or offer up of his own, or of himself,
though it be ever so glorious or highly esteemed in man`'s eye,
yet it is an abomination in the sight of the Lord.

Thus all the sacrifices of the Gentiles (or the heathenish nature) are rejected.
And thus all the sacrifices of the outward Jews (or of the religious mind and nature,
without the true life) are rejected also.
"`With what shall I come before the Lord,`" said the prophet of old,
"`and bow myself before the high God?
Shall I come before him with burnt offerings, with calves of a year old?
Will the Lord be pleased with thousands of rams, with ten thousands of rivers of oil?
Shall I give my firstborn for my transgression,
the fruit of my body for the sin of my soul?`" Mic. 6:6-7.
What was the answer of God?
No, no, this is not the way to come to pardon of sin, or to acceptance with the Lord.
Rather, come to that which teaches what is good,
and shows what the "`Lord requires of you, O man!`" which is "`to do justly,
and to love mercy, and to walk humbly with the Lord.`"
Come there in the teachings of God`'s Spirit, and worship there,
and there you shall witness forgiveness of sins, and acceptance with the Lord.
Mic. 6:7-8 and Isa. 1:16-18. For it was not offering
sacrifices of old (appointed under the law) that would do the thing,
nor is it men`'s pleading the sacrifice of Christ under the gospel,
but rather a coming to that Spirit which teaches holiness,
and being subject to that Spirit,
and offering in that Spirit (to the Father) what proceeds from him.
So that God`'s building in the Spirit is the only true temple,
and the sacrifices or offerings in the Spirit are the only offerings of the new covenant.

Here every groan or sigh towards the Lord after that which is pure,
every supplication in the Spirit,
every acknowledgment of the goodness of the Lord in a true and pure sense,
are of a sweet savor in the nostrils of the Lord.
Indeed, hospitality, relieving the poor,
or doing anything that is good out from the good and holy root,
are sacrifices acceptable to the Lord.
Read these following scriptures, and if the Lord opens your eyes,
you may thereby come to see both what the temple and the sacrifices are.
As for the temple,
see 1 Cor. 3:16 and 2 Cor. 6:16. Isa. 5:15-7. Eph. 2:21-22. Heb.
3:6. Rev. 21:22. John 4:23. Ps. 90:1. Then for the sacrifices,
Ps. 1:14-15 and 51:16-17 and 141:2. Mal. 1:11. Heb. 10:8-9.
Rom 12:1. 1 Cor. 6:19-20. 1 Pet. 2:5. Heb. 13:15. Phil. 4:18.

=== Concerning God`'s Election

Now, as concerning God`'s election, observe this: that it is in Christ,
and not out of him.
For it was the intent of God to honor his Son, even as his Son honored him.
And this was the honor which God gave him--that he
should be his salvation to the ends of the earth,
that whosoever believed on him should not perish, but have everlasting life.
That he should be the way for all mankind to come to the Father, through faith in him.
For, as in Adam all died, so in Christ all might be made alive;
and in Adam all men were shut up in death and condemnation,
so the free gift might come upon all,
and the way of life and redemption be opened to all, in him.

Mind the figure, the brazen serpent,
which was not lifted up so that a certain number might be healed, and no more.
Rather, it was lifted up that everyone that was wounded,
everyone that was stung with serpents, might look up and be healed.

So too was Christ lifted up,
that every sinner that was stung with sin and with the serpent might look up
to the physician of souls and receive virtue and healing from him,
according to that precious scripture, "`Look unto me and be saved,
all the ends of the earth.`"
And, "`Whoever is thirsty, let him come; and whoever will,
let him come and drink of the water of life freely.`"
Yes, God stands ready, by his Holy Spirit and quickening power (which is near men),
to kindle the true thirst in them, and to make them truly willing.

But to open this thing yet further: there is a predestination, election, calling,
justifying, and glorifying.
There is a predestination unto holiness, an election in that which is holy,
a calling out of darkness into light, a justifying and glorifying in the light,
through the renewing and sanctification of the Spirit.
All of these God orders and manages according to his good will,
and according as he has purposed in himself; but he is not the decreer,
nor the author of sin or rebellion against himself,
which is the cause of the creature`'s condemnation.

Now, all things are as present with God before they were;
for God did foreknow Adam`'s fall (though he was not
therefore the author of it) before it came to pass.
And he foreknew how his power and love and mercy should work towards men and for men,
in and through Christ.
He knew how far he would visit men with his love,
and how far men would resist and strive against his holy and good Spirit.
And he determined how long his Spirit should strive with nations and persons, for indeed,
with some he would long wait to be gracious,
and with others he would be quicker and more severe, according to their provocations.

Indeed, God`'s love, mercy, power, and his good Spirit are his own,
and he may show forth the operations of them towards men according to his pleasure.
And who can say unto him, '`What are you doing?`'
Can he not do with his own what he pleases?
And because he may show mercy as long as he will,
and harden as soon as he will (as he sees cause), may it not be truly said,
"`That he has mercy on whom he will have mercy; and whom he will he hardens?`"
But he does not harden without first giving them a day of mercy, visitations of mercy,
following after and forbearing them in mercy,
and seeking by the riches of his goodness and long-suffering to lead them to repentance,
that they might escape his wrath.
Indeed, to suggest that God hardens any from a mere will in himself,
because he desires to destroy the far greater part of men,
this the Scriptures do not declare, but rather abundantly testify against.
For how long did God strive with the old world (in the days of Noah),
even to have saved them, whom afterwards he did destroy?
And how long did he strive with that people of the Jews (yes,
and with other nations also)?
"`As I live, says the Lord,`" (and he speaks his heart),
"`I desire not the death of the wicked, but rather that they might return and live.
I am not the destroyer, I am the Savior, and my delight is not to destroy, but to save.`"
"`O Israel, your destruction is of yourself, but in me is your help!`"
Truly, no man`'s blood will lie at God`'s door, but at his own.

Therefore, as God has prepared a Savior, so there is no lack of love, or mercy,
or power on his part, to draw men to the Savior.
But this is the condemnation:
that men harden themselves against the drawings of his Spirit,
and against the operation of his holy light and power when it
appears and is willing to work in and upon their hearts.
Scripture does not declare that man`'s condemnation is
because the light does not shine in his heart,
but rather because light does shine and men love darkness more than the light.
For indeed a measure of light appears and shines to all men,
witnessing against and drawing away from the darkness.
And in the end it will be clearly manifest that God`'s Spirit did indeed strive with all,
and that they who have refused him would not be turned
from their darkness to the light of the Lord.
Every mouth will be stopped before him, for all men that perish are justly condemned,
having refused and neglected so great a salvation.
For truly the light of the sun of God`'s everlasting day,
and the sound of his Spirit visiting dark man, reaches throughout all the earth,
and his voice extends to the ends of the world.

[.discourse-part]
Question: How may a man make his calling and election sure?

[.discourse-part]
Answer: By making Christ sure to him, in whom the calling and election is;
for the Lord chooses only in him, and refuses or reprobates only outside of him.

[.discourse-part]
Question: How may I make Christ sure to me?

[.discourse-part]
Answer: By receiving him, giving up to him, parting with all for him,
and waiting upon him in the way and path of life till you feel
the power of that broken in you which would separate from him.
For then what danger is there, when the soul is naturally become the Lord`'s,
rooted in his love, circumcised in heart to love the Lord above all,
even with the whole heart and soul?
Certainly the love of the Lord cannot help but flow in great strength to that soul,
and what can come between?
But now, while there is still something not given up,
something yet standing in which the enemy has a part, and by which he may enter,
then the state of that soul is not fully sure.
For there may be a going back from the saving life into
that wherein is the destruction of the soul,
and whoever goes there meets with perdition and destruction,
so far as he travels that way.

In the path of death there is death; in the path of life there is life.
God is no respecter of persons, but he is a respecter of his seed,
and of his eternal covenant of life, which stands firm in his seed forever.
Here is life for every soul that feels the drawings of the Father,
and comes to his Son for life, and abides in him.
But there is death for every soul that does not come to this,
but rather departs from the Lord through a heart of unbelief.
So the way of God is eternal and immutable; he cannot deny himself.
He that believes in the Son has life;
he that believes not is in the death and condemnation which belong to the unbelief.

Now, do you desire to know your election?
Then wait to know and distinguish between Jacob and Esau, Isaac and Ishmael, in yourself.
For these were outward figures and allegories of something inward.
Feel Esau, the profane one; Ishmael, the scoffer at the wisdom, way, and seed of God.
You must feel these, who are cast off by God, cast out also of you.
And then feel Isaac, the seed of the promise; feel Jacob, the plain birth of life,
raised up in you, living in you, and you in it.
And then you will feel the election, and will be in the election.
And as his seed is sure to you, and your union with it,
and standing and abiding in it is sure, so your election is sure.

Election is a deep mystery,
and none can read the scriptures about it (which indeed are hard to understand,
but easy to twist) except those who can read in the seed, life, power,
and openings of the Spirit of the Lord.
These read things as they are;
but other men only read things as they apprehend and conceive them to be.
For the knowledge that God has given his people is
above all the knowledge that can be searched out,
gathered, or comprehended by all the men upon the earth.
