== Chapter X. The Ministration of Spirit and Power

There are chambers of imagery in many people, and strongholds, reasonings,
imaginations, and high thoughts,
exalted above the pure seed and measure of life in their hearts.
For every true Christian, every true believer, has received something of Christ`'s Spirit,
some proportion of grace and truth from the fullness of Christ,
which is as leaven and salt, to leaven the heart, and season the mind and spirit.
But all do not distinctly know this,
nor have all that do know it become subject to it in such a way that it does lead,
command, and rule in them.
Instead, there is something else which holds captive.
The enemy of the soul has the rule and dominion in many men`'s spirits.
And though they profess godliness, still they keep the seed under in them,
so that their souls are kept back from the redemption and
deliverance which they could partake of in and with the seed.
So it is that many talk of the gospel (and speak great words of Christ,
and redemption by him) who do not know
"`immortality brought to light,`" nor the dead raised by him,
to live to God and praise his name.

Now, in these chambers of imagery, in these strong-holds,
there are many pleasant pictures, many images of heavenly things,
which men form in their minds from their own
imaginations and conceivings upon the Scriptures.
For men reading the Scriptures outside of the life, Spirit,
and power which gave them forth (but rather with that which is natural),
do not come to the true, pure, heavenly, living knowledge.
These obtain only a natural knowledge, according to which they believe and worship,
and so they bow down before the apprehensions and imaginations of their own minds.
And so one believes and worships one way, and another believes and worships another way.
And truly, here men worship what they do not know; but they who are the true Jews,
know what they worship.
For indeed, salvation is of the true Jews, who worship neither at this mountain,
nor at the other mountain, but only in Spirit and in truth,
even in the life and power of our Lord Jesus Christ.

Thus it is with all men in their several professions of religion in the darkness,
in the apostasy from the true life and power,
which all sorts have erred and wandered from, but few have returned to.
Oh, few have found the pearl of price which has been long lost!
Instead,
they have contented themselves with a literal relation and knowledge about the pearl,
without knowing and possessing the pearl itself.
Yes, this was the state of darkness the Lord found us all in when he came to visit us.
For the strong man had his strongholds in us,
whereby he held us captive in the bands of death,
and free from that righteous life and power which we thirsted after.
But when the stronger man came, he battered his strength,
he assaulted and took his strongholds.
He broke all his reasonings, knowledge, wisdom, and subtlety, wherein he trusted,
and made spoil of his goods, and delivered the captive from under his hand.

For truly, when the mighty day of the Lord came upon us, and his pure,
heavenly light shone in our hearts, God searched Jerusalem as with candles,
discovering the most hidden things of Esau`'s nature inwardly.
Then all the knowledge and wisdom, all the understanding and experiences,
which were treasured up in us outside of the pure life,
outside of the truth (which lives and abides), were found to be dead.
And these were condemned to death in us, and so cast forth,
even as the treasures of Egypt and Babylon,
and were thrown to the bats and moles (who
either creep up and down in the earthly nature,
or soar aloft in the dark dreams and imaginations of the night of darkness and apostasy).
For when the true light shines, it discovers what the day is, and what the night is,
and also the things which are of the day, and the things which are of the night.

Now, when the Lord thus appeared unto us,
and caused the light of his Son to shine in us, many of us quickly came out of Egypt,
turning our backs upon the darkness.
We went willingly into the wilderness, to travel along with the Lord,
and to be exercised and fitted there for the good land, the land of the redeemed,
the land of the living, the land which flows with milk and honey (which is pure,
heavenly food).
For those that come there find the excellent vine, which bears the heavenly grapes,
of which is the wine of the kingdom, and the true olive, which yields sweet oil,
and houses which they did not build,
wherein are many dwelling places of rest and pure glory.

But there were others, who were unwilling to come out of Egypt,
or to forsake the idols and ways of worship in Egypt and Babylon,
whom the enemy long held captive in their thoughts and reasonings,
and in the disputings of their minds.
Now, these suffered much,
and felt many of the strokes and dreadful judgments of the Lord
poured out upon that spirit in them which held them captive,
and upon them for their hearkening and joining to the
subtle reasonings and suggestions of that spirit.
For the enemy uses all his strength and subtlety to the utmost,
to hold his captives in subjection to him, and under his power, as long as he can.
He keeps every hold,
he strengthens every reasoning and every thought
and imagination of the mind against God`'s call,
against the appearances of his Spirit in the heart.
'`Do not go yet!`' (says the enemy), '`Your way is not yet plain before you,
your light is not yet clear enough!`' '`Your objection or
consideration is not yet fully answered.
You are to try all things!
And there is still this, or that, or the other consideration,
which you have not yet tried, or considered fully and satisfactorily to your own heart.`'
Thus many pure drawings of the Father (in which there was
light sufficient for the soul to follow) have been lost,
and the soul thereby has missed the hand which was put forth (in the
tender love of the Lord) to help and save it.

[.discourse-part]
Question: But some may say, '`What have you learned of the Lord more than we,
or more than you knew before, when you walked among us,
and practiced the ordinances which we practice?
Have we not good directions from the Scriptures?`'

[.discourse-part]
Answer: There are three things I shall mention (besides many others,
which might be mentioned) which the Lord has taught us
since his Spirit and power has appeared to us,
and led us out of the darkness, which are these: He has taught us to believe;
he has taught us to obey; and he has taught us to pray to him in the name of his Son.

[.discourse-part]
Objection: Did you never learn these before?

[.discourse-part]
Answer: No, not as the Lord has taught us now.
There was indeed some true faith from the true seed in us, and some true obedience,
and some pure breathings to the Father in the days of our former profession.
But we knew not the root from which they came, so as to turn to it, and abide in it.
Thus the holy desires, and the true sense in us, were often made a prey of,
and we remained in need and in barrenness in a strange land, and could not enjoy,
possess, or retain, what was freely given to us by our God and Father in Christ.
For still there was a fleshly wisdom, a fleshly comprehension, a fleshly nature, mind,
and knowledge (which in that day we thought was spiritual, as others do now),
which rose up over it.
But when the Lord turned us to the light of his Spirit,
and by the light and power of his Spirit broke the bonds and chains of darkness in us,
then we could believe in him who appeared,
and (in the strength and virtue received from him) we could obey him,
yielding our members instruments of righteousness to do his will.
And in the Spirit of the Son (which we then received in the faith,
even the heavenly Spirit, the most excellent Spirit) we could pray to the Father--first,
sighing and groaning before him, and afterwards,
pouring out our requests and supplications to him, with giving of thanks.

[.discourse-part]
Question: How did the Lord teach you to believe?
Or what did he teach you to believe now, more than before?

[.discourse-part]
Answer: It is written in the prophets, "`All your children shall be taught of the Lord.`"
And in the new covenant it is promised, "`They shall all know me,
from the least to the greatest.`"

Now, as we were brought by the Lord into the light of this covenant,
we were taught thus to know him and to believe in him and his Son, as he was made known.
So that we knew the Father revealing the Son, and the Son revealing the Father.
Our hearts were drawn to believe in both, as they were both revealed in us, and to us,
and the revealing was in the Spirit of both, in the light of both, in the life of both,
in the power of both, which Spirit, light, life, and power, are one.
And he that indeed knows the Son, knows the Father also.
And he that indeed knows the Father, knows the Son also.

So now to us there is but one God and Father, "`Of whom are all things,
and we in him;`" and "`one Lord Jesus Christ, by whom are all things,
and we by him;`" and but one Spirit and one power of life,
which we have received of the Son and Father,
through which we believe and lay hold on the pure,
eternal power and strength of the Almighty, which redeems and saves the soul.

[.discourse-part]
Question: How did the Lord teach you to obey?

[.discourse-part]
Answer: Truly,
the Lord has taught us obedience in such a way as we
never learned before--putting his laws into our minds,
writing them in our hearts, and giving us his good Spirit to dwell in us,
to quicken and help us to obey and perform his holy laws.
And those two commandments (upon which the whole law and prophets hang), namely,
"`To love God with all our hearts,
and our neighbors as ourselves,`" this he has inwardly written in our hearts,
and taught us to observe and obey.
So that now we have no other God but him,
who brought us out of spiritual Egypt by his out-
stretched arm and holy power revealed inwardly for us,
as it was outwardly revealed to the Jews, whom God redeemed out of outward Egypt.

[.discourse-part]
Question: How did God teach you to pray?
Surely you never learned the Lord`'s prayer, for you do not practice that among you.

[.discourse-part]
Answer: As God brought us into a truly sensible condition,
so we came to feel our poverty, and the need of our souls, inwardly and spiritually.

Now, waiting on the Lord in this sense, when we meet together,
and when we are alone also, the Lord breathes upon us,
and kindles in us fervent desires and longings of soul after that which is pure,
and to be delivered from that which is impure,
and that we might be ingrafted more and more into Christ.
We desire that judgment and condemnation might pass upon all that is not of God in us,
and that our hearts might be so united to the Lord that we fear his name fully.
For we feel and observe that all our life and strength
flow from the union of our souls with the Lord.
Therefore, above all things, we cry out for that,
and for separation from that spirit which captivates into the things of the earth,
and in the earthly mind and nature.

So, we watch unto prayer, and watch for help from God in our calling upon him.
We are deeply sensible that we have need both of watching and praying continually,
for the enemy is so near, and the soul`'s snares and dangers are so many.

And truly, Christ, our Lord and Master,
who taught his disciples to pray formerly, has taught us also to pray that very prayer,
though not to say the words outwardly in the will of men, or in our own will.
Indeed, he has taught our hearts to breathe after the same things,
even that the name of our heavenly Father might be hallowed or
sanctified more and more among all that call upon his name in truth,
and especially in our own hearts.
And we desire that his kingdom come more and more,
that he might reign more in men`'s spirits,
and the kingdom of sin and Satan be thrown down, so that his will might be done,
even in our earth, as it is done in the heavenly places,
where all the hosts of God obey him.
And we look to him for that proportion of the
heavenly bread whereby our souls may live to him,
and necessary food and outward provision also, according as he sees good,
who cares for us.

Now, as we are kept in the light,
and watch to the light which discovers all things, we can see what we are kept out of.
And if at any time we are entangled and so trespass against the Lord,
then we are taught to beg pardon, and to wait where pardon is to be received,
through our advocate, even as God has taught us to forgive.
Yet this does not embolden any of the little ones to sin,
but they pray that they may not fall into temptation,
and instead witness deliverance from evil, which the enemy watches to ensnare them with.

Now, we witness this to be true religion, and undefiled before God,
and we are sensible that the Lord has taught us this.
Surely he is with us in our faith (which he has given to us), in our obedience,
in our praying to him in the name of his Son, in our watching, in our waiting,
in the silence of our spirits before his mighty and glorious majesty.

Oh that you all knew our God and his Christ in the same covenant and
power of life wherein it has pleased him to make himself manifest to us!
Oh, awake, awake out of your dreams;
come out of the night of sin and darkness into the light of the day!
And be not offended that I call them dreams of the night,
for they are no better than dreams before the light of the day.
Oh, be not contented with dreams concerning God, with dreams concerning fellowship,
remission, justification, peace, sanctification,
concerning the help of God`'s Spirit in prayer, etc.

Ah friends, dear friends, let go of the dead for the living!
Away with dead knowledge, dead faith, dead hope, dead prayers,
dead understanding of the Scriptures, dead strivings after holiness,
which shall never obtain the promise!
Come to feel that seed raised in you, in the true retired waiting upon the Lord,
which shall certainly obtain the promise in you, as your minds are united to it,
and come into the true sense and subjection under it.

=== Concerning the Gospel State

The Gospel is a ministration of the new covenant,
or a spiritual ministration of the substance of all that was shadowed out under the law.
There were many things under the law, but in the gospel God has gathered all into one.
In Christ there is but one seed, one Spirit, one life, one power, which redeems,
one circumcision, one baptism, one faith, etc.
The law was given by Moses, and its ministration continued through the prophets,
until the seed should come,
who was to put an end to the law and the righteousness thereof (as in the letter),
and bring in the righteousness in the Spirit, which should last forever.

The gospel is by Christ, by whom God spoke in the last days,
who is the beloved Son, the prophet and high priest of God, who is to be heard forever.
Christ taught his disciples, while he was with them on earth,
in that body of flesh which his Father prepared for him.
And afterwards, by his Spirit (or holy Anointing), he continues teaching his children,
and bringing them up in the virtue, life, and power of the new covenant,
giving them a new heart and spirit,
and causing the old nature of the earthly Adam to die in them, and pass away from them.

The law was given to the outward Jew, and is contrary to the nature in man,
who seems willing to obey, but will not.
The law was also given to check that part (or nature in man) which is above the seed,
to which were given all the outward shadows and types.

But in the gospel, which is the power of God to the redemption of the soul,
that part is done away, and the seed is raised, and comes to live in the soul,
and the soul lives in the power that quickens it, in and through the seed.
So here the life, virtue, and nature of the seed overshadows all,
and changes all in the gospel ministration.
So that here is a new heaven and a new earth wherein God reigns,
and where righteousness dwells.
The old things, wherein unrighteousness dwelt, and wherein the devil reigned,
are done away, and so his kingdom is destroyed and laid waste in man,
and the kingdom of Christ is set up, exalted, and established.

Then the mountain of the Lord`'s house comes to be
known on top and above all the mountains and hills;
and then is the flowing of the enlightened soul there,
to learn of the Lord in his holy sanctuary,
that it may know his ways and walk in his paths.
Then is the voice of the true Shepherd heard,
and the law known (the law of the Spirit of life
in Christ Jesus) which comes out of Zion.
Then is the day of the Lord known--the mighty, terrible, shaking day of the Lord,
which is then upon all flesh,
silencing it in the dread and awe of him who is holy and pure.
And the seed is then raised to life and power,
and the Lord alone is exalted in that soul.

Then, after this shaking,
after the work of this terrible day of the Lord in the heart,
when God has purged away the filth and blood of the defiled
soul and spirit by his Spirit of judgment and burning,
then that which is left shall be called holy, and dedicated to the Lord,
even in everyone that is written and reckoned by God among the living in his Jerusalem.
And all God`'s tabernacles and dwelling places on his holy mountain, and in his holy city,
he will cover with the glory of his presence.
And in all their assemblies (by his cloudy pillar, and by his shining flame),
God will be a defense around them, before which brightness Satan,
with his devices and fiery darts, shall fall like flashes of lightning.
Indeed,
his storms and winds shall not be able to prevail against the dwelling
places which God builds on this his holy mountain of peace and salvation.

Then the rod of the stem of Jesse is known,
and the branch which grows out of his root, and the Spirit of the Lord resting upon him.
"`For grace and truth came by Jesus Christ,`"
and where this grace and truth are received,
and his everlasting covenant is entered into,
there the same Spirit is poured forth and rests.
And true judgment is set up in the heart,
and the soul is established in the righteousness and peace of his kingdom.

So, if any lack wisdom, let him ask in faith,
for it is presently given from the Spirit of wisdom which is poured out upon the seed.
This is a Spirit of understanding and knowledge, and of pure, heavenly fear,
which makes the fear of the Lord come alive in the understanding,
and (being understood and observed) keeps the heart clean,
teaching it to avoid and keep out of all that defiles.
Here there is not so much as a touching of unclean things by
any of the sons and daughters who are led by God`'s Spirit,
and live and walk in the Spirit,
but a following of the law of the Spirit of life in Christ Jesus fully and perfectly.

Yes, in this day the feast of fat things is made on God`'s holy mountain!
And in this mountain the veil of the covering (spread over the heart) is done away. Isa. 25:7.
For in the seed there is no veiled covering,
but rather an opening of the unveiled eye to see the unveiled life and power,
even the revealed arm of the Redeemer.

"`Who has believed our report; and to whom is the arm of the Lord revealed?`"
This was said in the old covenant, in the law dispensation,
but it is not said so in the new covenant, in the gospel dispensation.
For the veil is done away in Christ,
and the children there with open face behold (as in a mirror) the glory of the Lord.
And here the seed is revealed, and the soul comes into the seed,
and becomes one with the seed, which is felt to break the serpent`'s head.
And then says the soul, "`Lo, this is my God who I so needed, and so long waited for!
Oh, he is come, he is come to judge my heart in righteousness,
and to bring down all that has kept the seed under in me!
I feel him, my soul`'s salvation, and my heart is glad in him!
And now I know the land of Judah`" (for that
land outwardly was but a figure of the inward),
"`and the strong city that is there!`"
