== Chapter XI. Christ`'s Baptism

[quote.scripture, , Mark 16:16]
____
He that believes, and is baptized, shall be saved; but he that believes not,
shall be condemned.
____

This is a very weighty scripture,
and it is necessary for every Christian to rightly understand it, that he may so believe,
and be so baptized, as to witness salvation by the gospel of our Lord Jesus Christ.

Now, what believing is this which is here required as necessary to salvation?
Is it anything less than a believing in the Lord Jesus
Christ from a true sense of his power to save,
which the Father has given him?
Is it not an inward believing, a believing with the heart?
And what baptism or washing is it which saves?
Is it not an inward washing, a washing of the soul, a washing of the heart,
a washing of the conscience from dead works to serve the living God?
Does outward washing save the soul?
Inward washing does; baptizing into the name does.
Bodily exercise profits little;
but godliness (the inward renewing and washing of the heart and mind) profits greatly.

There is one faith and one baptism. Eph. 4:5.
Is not the one faith inward and spiritual?
Is not the one baptism so also?
I am certain that he that believes and is baptized in this way shall be saved.
But he that believes not, remains in the filthy, unwashed state,
in which there neither is, nor can be, salvation, but rather judgment and condemnation,
death and destruction, forever.
Now consider:

[quote.scripture, , 1 Pet. 3:20-21]
____
&hellip;the Divine longsuffering waited in the days of Noah, while the ark was being prepared,
in which a few, that is, eight souls, were saved through water.
There is also an antitype which now saves us,
baptism--not the removal of the filth of the flesh,
but the answer of a good conscience toward God--through the resurrection of Jesus Christ.
____

The apostle Peter shows what the baptism is which saves,
even that which is the "`antitype,`" or which
inwardly or spiritually answers to Noah`'s ark.
The Greek word is _antitypous,_ which signifies antitype, or that which fulfills the type;
it is the substance, which comes instead of the figure or shadow.
And so it is more properly and naturally rendered
(as the old translation has it)--
"`The baptism that now is, fulfilling that figure, saves.`"
For just as Noah`'s ark saved the bodies of those that were in
it when God came to judge and destroy the old world,
so now the inward washing saves those that are washed thereby from
the wrath and destruction which will come upon all that are unwashed.

Now, lest any should misunderstand and misapply his words,
as if he spoke concerning an outward baptism or washing,
Peter explains himself in the following words: "`Not,`" says he,
"`the removal of the filth of the flesh,`" not the outward washing of the body,
that is not what saves;
but rather that baptism which brings about the answer of a good conscience towards God,
by the resurrection of Jesus Christ.
For this is the effect of the inward baptism--sin is washed away by the water of life,
by the blood of the Lamb, and that which is new, that which is renewed,
rises up out of the water that washes away sin.
Then the pure and good conscience answers to God,
and the soul knows and partakes of both the
death and resurrection of our Lord Jesus Christ.
And so, being baptized by the one baptism, even the baptism of Christ, into the one body,
the soul comes into the state and fellowship of the living.
Another apostle also speaks of the inward washing,
even "`the washing of regeneration and renewing of the Holy Spirit,`" by which, says he,
"`God according to his mercy saved us.`" Tit. 3:5.

Elsewhere, the apostle Paul speaks of a
"`circumcision made without hands,`" and tells wherein it consists,
namely, in putting off the body of the sins of the flesh.
Moreover, he shows how this is effected, that is, not by Moses`' circumcision,
but by the circumcision of Christ. Col. 2:11.
And truly,
those who are circumcised in this way are the true circumcision,
the spiritual circumcision, who worship God in the Spirit,
and have no confidence in the flesh, but rejoice in Christ Jesus who circumcises them.
Now, in the very next verse Paul speaks of baptism,
of being "`buried with Christ in baptism,
and of rising with him through the faith of the operation of God,
who raised him from the dead.`"
What is this baptism?
Is it inferior to the circumcision spoken of just before?
Is it not also without hands?
What is it that buries into the death of Christ,
and raises into the life of Christ through the faith of the operation of God?
Is not this the one spiritual and heavenly baptism,
with which the one body is baptized by the one Spirit?
What does outward circumcision avail?
Does it avail anything?
What does outward washing avail?
Does it avail any more than outward circumcision?
But the inward circumcision of the inward Jew,
and the inward washing of the soul from sin, does avail very much.

Now, as for Matt. 28:19, where Christ expressly commands baptizing,
it is a very weighty question, and worthy to be considered,
what baptism he there commands.
For if it be outward baptism,
they greatly err who believe it to be the inward and spiritual baptism.
But if it be the inward and spiritual baptism which Christ intended in those words,
then they greatly err who think it to be the outward.
Now consider the words in the fear and weight of God`'s Spirit.

It is said, "`Go teach, baptizing,`" but it does not say, baptizing with water,
but rather "`baptizing in the name,`" or rather
(as the Greek has it)
"`baptizing __into__ the name of the Father, and of the Son, and of the Holy Spirit.`"

Now, to baptize with water is one thing, and to baptize into the name is another,
as all who experience the spiritual baptism know it to be.
For the word of faith turns men from Satan to the power of life,
and then as they receive the power, and are made partakers of the power,
they are baptized into the power and virtue of life.
And so they are buried by the power of his Spirit with this heavenly baptism,
into death unto sin, and by the same power are made alive unto righteousness.
Thus the name of the Lord (the name of the Father, Son, and Spirit) comes over them,
and they rise up in it unto life and righteousness, and so are dead unto sin,
and alive unto God.

Now, any outward circumcising or washing can be only a figure of this,
but the inward circumcising and washing is the thing itself.
For Christ did not send his able ministers of the new covenant to minister the letter,
or to minister the figures of things, but rather to minister the Spirit,
(else how were they able ministers of the Spirit?), that is, to minister the substance.
They were not to minister a circumcision or baptism which might be shaken and pass away,
as outward and elementary,
but rather to minister the circumcision and baptism which cannot be shaken.
This is the circumcision and baptism of the gospel,
the circumcision and baptism of the Spirit, the circumcision and baptism of the kingdom,
which is never to be shaken and pass away as elementary, but to stand and abide forever.
Read Heb. 12:26-28,
and consider how all elementary and outward things that
could be shaken were to be shaken and pass away,
so that those things which were of a higher nature (even of the
nature of the kingdom) might remain and be established in their stead.

And indeed,
even as the inward circumcision could not be thoroughly and
singularly established while the figure thereof remained,
the same may be truly said concerning the inward baptism.
By this it may appear that the baptism of water cannot
be the baptism which Christ intended in this place,
because the baptism here spoken of was to continue to the end of the world.
But the baptism of water is clearly of an outward,
elementary nature as can be shaken (as well as circumcision),
and so was to be shaken in due time, that that which could not be shaken might remain.

[.discourse-part]
Objection:
Against this it is objected that the baptism of the
Spirit cannot be the baptism spoken of in this place,
because the baptism spoken of in this place is commanded;
but the baptism of the Spirit was never commanded.

[.discourse-part]
Answer: Surely this is a great mistake.
Was the inward washing of the heart never commanded?
The gospel is a ministration of inward things,
and the inward things are strictly commanded there.
Can any man be saved without inward baptizing?
And is he not commanded to receive inward baptizing?
Does he not sin if he will not wait to receive it,
and give up his heart and soul to be baptized by God`'s Holy Spirit?

Oh, if the eye were opened in people to look into the gospel ministration,
and into the inward nature of things,
this might easily be demonstrated to the least babe there.
For indeed, to the Lord, the gospel existed before the law,
and could not be annulled by the law.
So this ministration of the Spirit`'s baptism (in
nature and kind) was long before John`'s baptism,
and could not be annulled by any outward ministration of baptism,
but rather abides the same forever.
And this baptism is to have its place in the gospel state,
where all figures and shadows of things pass away, and that which is true, lasting,
and substantial, fills up its place.

Now, the baptism of the Spirit,
or the spiritual washing and circumcising the heart (which is all one in substance),
was called for and required of the Jews under the law,
and it was their sin not to answer God`'s call and requiring therein.
Consider these following scriptures, with many more of the like nature:
"`Break up your fallow ground, and sow not among thorns.`" Jer. 4:3.
Again: "`Circumcise the foreskin of your hearts,
and be no more stiff-necked.`" Duet. 10:16.
"`Make you a new heart and a new spirit; for why will you die,
O house of Israel!`" Ezek. 18:31.
(Is this not all one in substance with that scripture,
"`He that believes and is baptized, shall be saved`"?) "`O Jerusalem,
wash your heart from wickedness, that you may be saved!
How long shall your vain thoughts lodge within you!`" Jer. 4:14.
"`Rend your hearts, and not your garments.`" Joel 2:13.
"`Wash you, make you clean,
put away the evil of your doings from before my eyes.... Come now,
and let us reason together, says the Lord: though your sins be as scarlet,
they shall be as white as snow; though they be red like crimson, they shall be as wool.
If you be willing and obedient, you shall eat the good of the land;
but if you refuse and rebel, you shall be devoured with the sword,
for the mouth of the Lord has spoken it.`" Isa. 1:16-20.

Is this not the true baptism, and the remission of sins, which comes thereupon?
Is this not the blessing on the baptized state, and the curse on the unbaptized state,
which extends both to Jew and Gentile (for with God there is no respect of persons)?
Oh that men could read the Scriptures of truth,
with the true Spirit and with the true understanding!
For these things, which were written to the people of the Jews,
were written for our learning.
Indeed, precious things may be learned from the Scriptures by
those whose eyes are opened by the Lord,
and who keep close in their reading to that which anoints and opens the eye.
But otherwise,
man cannot help but misunderstand and twist them to their own great danger,
or to the ruin and destruction of their souls.

[.discourse-part]
Objection:
The baptism of the Spirit cannot be intended in Matt. 28:
19 because this baptism is to be administered by men;
but the baptism of the Spirit was never administered by men, but rather by Jesus Christ.

[.discourse-part]
Answer: The apostle says that "`God had made them able ministers of the new covenant,
not of the letter, but of the Spirit.
For the letter kills, but the Spirit gives life.`" 2 Cor. 3:6.
Now mark--they were made able ministers by God of that which gives life,
and that they did minister the Spirit by the laying on of hands is manifest, Acts 19:6,
and in many other scriptures.

Indeed the apostles were not able of themselves,
or by any virtue or strength of their own, to beget men unto God,
or to baptize men into his name and power; but their sufficiency was of God.

Consider: Paul was sent to the Gentiles to open their eyes. Acts 26:18.
Now, opening the eyes of the blind is just as peculiar to
Christ as baptizing with the Spirit can be.
And when Christ gave his apostles commission to teach, baptizing, he told them,
"`All power in heaven and earth was given me`" and he bid,
"`Do not depart from Jerusalem, but wait for the promise of the Father.
For John truly baptized with water,
but you shall be baptized with the Holy Spirit not many days
from now,`" (Acts 1:5) and then they should receive power.
Power to do what?
To baptize with water?
Or to baptize into the name with the same baptism wherewith they themselves were baptized?
See Matt. 28 together with Acts 1.

Now, if the commission given to the apostles in Matt. 28:16, etc.,
was to baptize with water, then Paul was inferior to the other apostles.
For he, though he had seen the Lord,
and was sent from him to open the eyes of the Gentiles,
yet he was not sent to baptize with water, as he expressly says,
"`I was not sent to baptize`" (that is, outwardly with water),
"`but to preach the gospel.`"
But if the baptism intended by Christ was inward and spiritual, even into the name,
virtue, life, and power of the Spirit,
then Paul had the apostolic commission as fully as any of the rest,
and the grace and power of God did work as mightily in him to this end,
as in any of them.

But men are as much mistaken about the teaching required by
this commission as they are about this baptism.
For this teaching is not a literal teaching of things,
or a discipline into an outward knowledge and way,
but rather a teaching in the Spirit and power.
And he who God enables to teach in Spirit and power,
he also enables to baptize into the same Spirit and power.
Yes, indeed,
when the life and power ministers (the word
spoken being mixed with faith in them that hear),
it brings the earthly part under,
and brings the life and power of the Lord Jesus Christ over the heart and spirit.
This is true baptism,
and is the substance of the figure or shadow which was
before the figure of both baptism and circumcision,
and remains when they are gone.

[.discourse-part]
Objection: The baptism in the commission was to all nations,
but the baptism of the Spirit fell only upon a few at the beginning.

[.discourse-part]
Answer: The promise of receiving the Spirit is upon believing,
and it extends to everyone that believes.
"`He that believes in me, as the Scripture has said,
out of his belly shall flow rivers of living water; but this he spoke of the Spirit,
which they that believe in him should receive. John 7:38-39.

Likewise, Peter said to that great assembly to which he preached,
to which there were added about three thousand souls, "`Repent and be baptized,
every one of you, in the name of Jesus Christ, for the remission of sins,
and you shall receive the gift of the Holy Spirit.
For the promise is unto you, and to your children, and to all that are afar off,
even as many as the Lord our God shall call.`" Acts 2:38-39.

And this is the one washing which all the flock are washed with,
and so baptized into the one pure, living body.
This is the substance of the figure, which substance belongs to the gospel state,
even though God also made use of some figures in the breaking forth of that gospel day,
and even inclined their hearts then to make use of them.

[.discourse-part]
Objection: The baptism in the Matt.
28 commission cannot be the baptism of the Spirit,
because it is to be administered in the name of the Spirit.

[.discourse-part]
Answer: The Greek word is not _'`en,`'_ which signifies in,
but rather _'`eis,`'_ which signifies into.
So that the baptism commanded here is to baptize _into_ the name, into the Father`'s name,
into the Son`'s name, into the Spirit`'s name, by turning them from darkness to light,
from the power of Satan to God.
Then the power and life of God`'s Holy Spirit comes over their hearts and minds,
and breaks the power of Satan, and washes the conscience from that which is dead,
and plunges or dips them into that which is living.

But that there was also a baptizing with outward water, that I do not deny.
And that it was used as a type or shadow to the weak and ceremonial
state the Jews were in (when Christ sent forth his apostles to gather
them out of the law state into the gospel state),
I am also satisfied.
But this has been since corrupted,
and set up above its place by those who have fallen from the power and life.
And everyone should consider and wait on the Lord to know what God requires,
and what he will accept of him.
For the kingdom of God stands not in food and drink, or any outward washing;
nor does it come in the way of man`'s observation, but in a heavenly seed,
and in the Holy Spirit and power of life.
Happy are they who are made partakers of, baptized with, and led by, the Spirit of God.
Indeed, God will try every man`'s religion, work, and practices,
by the true measuring line.
Blessed is he whose religion will bear that trial!

It is a great matter to know the gospel state and ministration,
the gospel Spirit and power, the gospel church and ordinances,
the words of the holy prophets concerning the day of the gospel,
the words of Christ concerning the kingdom and power of God,
the words of the apostles concerning the mystery of faith,
and the Word which was from the beginning.

Indeed, these are weighty things, and of great importance,
about which men may easily miss and twist the Scriptures,
unless they are enlightened by the Lord in the renewing of their minds,
and their eye kept to the holy anointing, so that they do not run ahead,
and so imagine and conceive of themselves
according to their own ability of understanding.

The Pharisees had a great deal of knowledge and understanding of the law of God,
and prophecies of things to come from the words of Moses and the prophets.
But not having the true key of knowledge, "`they erred,
not knowing the Scriptures`" (despite all their diligent reading and studying them),
nor the power of God.`"

Oh, consider!
The Pharisees little thought they would have killed the prophets,
had they lived in their days.
No, they greatly condemned their fathers for doing so,
and yet they themselves crucified Christ.
And many now little think they would have crucified
Christ had they lived in the days of his flesh;
and yet they disdain, reproach, and persecute the appearance of the same Spirit, life,
and power, as it now appears in his saints.

[.discourse-part]
Question: What is it that must be washed in the gospel state?
Is it the outward or inward man?
And what is the inward man to be washed with?

[.discourse-part]
Answer: Consider this scripture seriously,
and may the Lord give you the true understanding--"`In that day a fountain
shall be opened for the house of David and for the inhabitants of Jerusalem,
for sin and for uncleanness.`" Zech. 13:1.
Does not this scripture speak of the gospel state?
What fountain is it that is opened in the gospel state?
Is it an outward fountain of outward water which washes away sin and uncleanness?
The Lord knows of what nature sin is, and with what water it must be washed away,
and he therefore opens that fountain in the gospel
state with which it is proper to wash it away.

Now, that there was a figurative washing away of sins by John`'s baptism,
I do not deny.
For John`'s was a baptism unto repentance, and by it they professed repentance,
and were to "`bring forth fruits worthy of repentance.`" Matt. 3:8.
But the "`antitype`", (1 Pet. 3:21) or fulfillment,
is not the washing away the filth of the flesh or body, but rather an inward baptism,
which so washes inwardly that the answer of a good conscience
is presently felt in the sight and presence of God.
And then the soul truly knows with what kind of water it was washed.

Oh that people knew and experienced the baptism which is the substance!
Then they would not idolize that baptism (or outward washing),
which in its nature can be no more than a sign, signification,
or representation of that which is the substance!

Now consider: Did the Jews know the inward circumcision?
And do you know the inward baptism any more than the Jews knew the inward circumcision?
Read that scripture, Rom. 2:28-29,
and the Lord apply it home to your souls--"`He is not a Jew who is one outwardly,
neither is that circumcision which is outward in the flesh;
but he is a Jew who is one inwardly, and circumcision is that of the heart in the Spirit,
and not in the letter, whose praise is not of men, but of God.`"
Now, may not the Spirit of God say in these our days (yes,
of a truth the Spirit of our God does say so, and many have heard his voice so speaking),
'`He is not a Christian who is one outwardly,
neither is gospel baptism that which is outward in the flesh;
but he is a Christian who is one inwardly,
and the gospel baptism is that of the heart in the Spirit, not in the letter,
whose praise is not of men, but of God.`'
The Jews praised the outwardly circumcised, and you praise the outwardly baptized;
but God praises the inwardly circumcised and washed.

[.discourse-part]
Objection: But the baptism of the Spirit is a promise, and not a duty.

[.discourse-part]
Answer: That the baptism of the Spirit is a promise is granted;
but it is also a duty to receive the promise, and to give up to be baptized by him.
For John said, "`I indeed baptize you with water unto repentance,
but He who is coming after me is mightier than I, whose sandals I am not worthy to carry.
He will baptize you with the Holy Spirit and fire.`"
The baptism of the Spirit is the inward purging
away of sin and filth by the Spirit and its fire,
or by the "`Spirit of judgment and burning.`" Isa. 4:4.
Those who were baptized by John were
afterwards to expect and wait for this baptism,
that with the Lord`'s fan their floor might be purged, their chaff burnt up,
and the wheat gathered into the barn. Matt. 3:12.

Now, we indeed grant that Moses`' circumcision was God`'s ordinance,
and that John`'s baptism was God`'s ordinance.
But to assert that either of these is a gospel ordinance--that
Moses`' circumcision is the circumcision of Christ,
or John`'s water baptism is the baptism of Christ--this
we conscientiously and groundedly deny.
Indeed, God`'s Spirit (in the Scriptures) declares a difference between them,
as particularly, between John`'s baptism and Christ`'s. Matt. 3:11. Moreover,
to set up the shadow of a thing instead of the
thing itself is not the way to glorify Christ,
or the gospel dispensation.
For Christ is the Son, who did not come forth with Moses`' circumcision,
or with John`'s baptism (who were both servants),
but with the Spirit and power of his Father,
with which he circumcises and baptizes inwardly and spiritually.

=== The Testimony of God`'s Spirit

[quote.scripture, , Ps. 51:16-17]
____
O Lord, open my lips, and my mouth shall show forth Your praise.
For You do not desire sacrifice, or else I would give it,
nor do You delight in burnt offering.
The sacrifices of God are a broken spirit; a broken and a contrite heart--these, O God,
You will not despise.
____

[.discourse-part]
Inquiry 1:
What rule did David have from the law of Moses to say that God did not desire sacrifices,
nor delight in burnt offering?
Did not God desire and require that his people perform these things under the law?
And did he not accept them, and delight in them, when they performed them aright,
in faith and obedience to him?
Was not the Lord pleased with Abel`'s sacrifice?
And did not God smell a sweet savor in Noah`'s sacrifice?
How could David say in truth, and from a true Spirit,
that God did neither desire them nor delight in them?

[.discourse-part]
Inquiry 2: Should not David try this Spirit which spoke these things in him,
whether it was of God or no?
Should he receive a testimony from any spirit so directly contrary in
appearance to the foregoing testimonies of God in the holy Scriptures,
without a full and certain evidence and demonstration that it was the Spirit of God?

[.discourse-part]
Inquiry 3: How was David to try this Spirit, whether it was of God or no?
Was he to try it as to whether it spoke according to the testimony and law of Moses,
which certainly was of God, and was given by God for a law or rule to the Jews?
If he had tried it in this way,
would he not have judged it to be a different spirit from the Spirit of Moses,
speaking contrary to the law and testimonies which God gave forth by him?
For indeed, sacrifice and burnt offering was strictly required there,
and God often testified his acceptance of it and delight in it.
So that God did accept and did delight in these in one respect,
and did not accept nor delight at all in them in another respect,
for his aim was at another thing, and at other sacrifices, which David clearly saw.
And so David`'s eye, mind, heart, and spirit being gathered inward,
even to where God`'s eye and heart was, there he had a clear sight,
and gave a certain testimony concerning what was, and was not,
acceptable in the eye of the Lord.
So he says, "`God did not desire sacrifice,
nor delight in burnt offering,`" Ps. 51:16,
though the language of the law of Moses speaks far otherwise, where circumcision,
sacrifices, and such outward things are expressed as of great value with the Lord.

[.discourse-part]
Inquiry 4: Now, may not the same Spirit, or the children of God in the same Spirit,
say to the Lord in this day (concerning things of the same
outward nature)--'`You desire not such outward things,
else would we perform them.
You delight not in outward shadows of the things of the kingdom.
You desire not outward washing the body with water,
or eating and drinking of outward bread and wine,
which avail no more than circumcision and the Passover.
If your delight was in things of this nature, and you did require them of us,
oh how willingly would we be found in the practice of them before you!
But your delight is in that water which washes the soul from its filth,
and in the souls that are washed with it.
And you desire to see your children feeding on the living bread,
the bread which comes down from heaven, and drinking the wine which refreshes,
and makes glad the heart of both God and man.`'

The Lord has likewise shown us clearly that outward water, bread, and wine,
are not the substantial, the spiritual, the heavenly water, the heavenly bread and wine.
Rather, these are of the nature of the things that were to be shaken,
that those things which cannot be shaken may remain in the gospel state and kingdom.

Oh therefore, let men take heed how they build,
or how they judge concerning the appearances of God,
by their own apprehensions upon the letter of the Scriptures.
But let everyone be careful to build upon the rock which is Christ, upon his Spirit,
his life, his power inwardly revealed, which the birth, being kept to,
reveals in and to us.
For no man, by his own conceivings and apprehensions upon the letter, ever knew,
or can know, the Spirit and voice of the Lord.
For man is dead, dark, and corrupt, except as he is quickened, enlightened,
and his heart sanctified by God`'s Holy Spirit.
What can a dead man see?
What can a dead man hear?
Can he hear the living sound before he is quickened by it?
Do not the Scriptures speak of spiritual things?
And can the natural man understand them?
Can man`'s unholy mind understand the words of God`'s pure, holy Spirit,
which were given forth through vessels that were sanctified (some from the womb),
and when the Spirit of the Lord was upon them?

Oh that men saw their need of the Lord to open their hearts,
and that flesh might be silent in them!
Oh that they might come to witness the birth of God`'s Spirit,
and the precious understanding of heavenly things which is given therein!
And then that understanding which is not precious, nor living, nor of God,
but of themselves, would not be of so great value with them.
For indeed, through this great mistake,
many (some of whom are zealous and knowledgeable according to
the esteem of men) reject that which is of God,
and set up that which is of themselves, even of their own apprehending and conceiving,
all of which will be bitterness and sorrow in the latter end,
when that eye shall be opened in them which is at present closed.

Blessed is he who can truly say, '`The Lord has opened an eye in me,
even the true eye, the pure eye, the living eye, and with that eye I now see!
But the eye with which I saw before, I now see not.
And now I know the difference between seeing the same things with my own eye,
and with the eye which God has given me.
So that now,
my earnest desire and prayer to the Lord is to keep
open in me forever that eye which he has opened,
and also to keep that eye shut which he, in his tender mercy to me,
has been pleased to close up in me.

And truly,
this is the ground of the great difference between us
and others with regard to the things of God.
For though we acknowledge the same things, and speak of the same things,
yet we do not acknowledge them alike, nor speak of them alike.
Why so?
Because we see them with different eyes, and so have a different sense of them.
Others call things true and so acknowledge them as they apprehend them from the letter.
We call things true as they are demonstrated to us by God`'s Spirit,
and as we feel the virtue, life, and power of them from God in our hearts.
