== Chapter XIII. God's Teaching and Christ's Law

=== Preface

Christ, who came from the Father, and knew the way of truth and life everlasting,
and was to guide men to the Father (being the only way unto him), preached the kingdom,
and bid men to seek the kingdom.
He taught and instructed them in many parables concerning it,
and directed them where and how to find it.

The apostles (who succeeded Christ in the same Spirit and power
wherein he ministered) likewise preached the same kingdom,
declaring and describing what it was, and in what it consisted--namely, not in word,
but in power, even in the power which shakes all that is to be shaken,
but cannot be shaken itself. 1 Cor. 4:20, Heb. 12:28.
Nor was the kingdom of God food and drink (or any outward thing),
but righteousness, peace, and joy in the Holy Spirit. Rom. 14:17.

Indeed, the apostles did not preach in vain,
for the life was inwardly revealed in many, the power inwardly revealed,
the kingdom inwardly revealed, and the righteousness, peace, and joy of it was felt.
For such as truly believed and obeyed the gospel,
received the kingdom which could never be shaken,
and had an entrance ministered to them thereinto,
according to their diligence and carefulness in the truth.

Now, afterwards a great darkness came over the world,
and this glorious kingdom was again veiled,
and the kingdom of darkness and deceit overspread the profession of Christianity.
In this time,
notions and outward knowledge took with men instead of the life and truth itself,
wherein the kingdom and power stands.

But blessed be the Lord,
the light of life again shines out of and over the darkness,
and the kingdom is again received, and the entrance into it is again known.
And now, from what has been seen and heard (and in measure enjoyed and possessed),
a faithful testimony has been given forth.
And blessed are they who hear the joyful sound;
for it is no less than the sound of life itself, the power itself, the gospel itself,
the Spirit himself, manifesting himself in, and speaking through,
vessels according to his pleasure.

Now, they that receive this light, which is testified of, receive Christ;
but they that despise and reject it, reject him,
as will be made manifest in the day of the Lord.
For this dispensation is indeed most precious, glorious, and living,
being a dispensation of the seed and power of life itself.
And by this seed God translates out of darkness, and the regions thereof,
into the kingdom of his dear Son, and into his glorious image.
This, reader, is the goal of my giving forth the following things,
not that you may have only notions concerning them, but that you may, in truth,
come to partake of the thing itself.

=== Concerning God's Teachings

"`It is written in the prophets`" (said Christ) "`they shall all be taught of God.
Everyone therefore that has heard, and has learned of the Father, comes unto me.`" John 6:45.
For the prophets indeed had said,
"`All your children shall be taught of the Lord,`" and "`they shall all know me,
from the least of them to the greatest of them.`"

Now, whose children are they which shall all be taught of the Lord?
And who are they that shall all know the Lord by the teachings of his Spirit,
from the least to the greatest?
Are they not the children of the free woman,
the children of the Jerusalem which is from above,
which is the mother of all that are truly living? Gal. 4:26.
Now, all her children are begotten by the Father of life,
and he takes care to teach them the true, pure, heavenly, living knowledge.
These indeed know the Lord, being taught by the anointing to do so,
and they indeed know the Son, the Father revealing him to them.
For "`no one knows who the Son is except the Father,
and who the Father is except the Son, and the one to whom the Son wills to reveal him.`"
"`Flesh and blood has not revealed it to you,
but my Father who is in heaven,`" said Christ to Peter. Matt. 16:17.
And it pleased God to reveal his Son in me, said Paul. Gal. 1:15-16.
And how did Paul preach Christ among the Gentiles?
Did he not preach him as a mystery hidden from ages and generations,
which none but the Father could reveal and make manifest?
And when he is known and made manifest, is he not known within, revealed within,
made manifest within?
Col. 1:26-27 and 1 John 1:2. Notice John's words: "`The life was manifested.`"
In this way they came to know Christ,
and if they desired to bring others to the knowledge of Christ,
they must bring them to the manifestation of the same life,
and show unto them that eternal life which was with the Father,
and was manifested unto them. ver. 2.

Now, in order that they might do thus,
they were to preach the light to them
(even this message, "`that God is light, and in him is no darkness at all.`" ver. 5),
and to turn them to the light, Acts 26:18,
in which alone men can see and receive the life which is eternal.
Men may know or comprehend many things concerning the Messiah from the letter,
but they can only know the Messiah himself in the light which shines into their hearts.
This is the light to which he sent his apostles to direct and turn their minds.
For they directed them to the Word within, the light within, the life within,
the Spirit within, to feel after the manifestation of God within.
And so Paul directed the Gentiles to seek after and find God near, and not afar off. Acts 17:27.
Oh, this is precious to find and feel God near, Christ near,
in his light to see light, in his life to feel and enjoy life!
For here (in the place of darkness, in the place of sin and death,
in the place where dragons lay, Isa. 35:7) is the redeeming power to be felt,
and the deliverance of the soul experienced by those that truly believe.

The Scribes and Pharisees had a knowledge that the Messiah was to come,
but how did they come to this knowledge?
Why, they had read so in the letter of the Scriptures.
The professors of this age have a knowledge that Christ is come,
but how did they come to that knowledge?
Why, they have read so in the writings of the evangelists and apostles.
But who has believed the report of life now,
and to whom is the arm of the Lord (which is now stretched forth) revealed?
Who has heard and learned of the Father to know the Son, and so to come to him,
even from the inward revelation of his Spirit,
and from the inward living knowledge which is thereby?
Everyone, Christ says,
that is taught of God (because of what they have heard and learned of the Father),
comes to the Son.
Now, everyone that is drawn in this way, and thus comes, is received by Christ,
and given eternal life.
And these know him who gives them eternal life,
and who preserves and maintains life in them.
But others have only a notional knowledge of him,
and do not indeed know him that is true, nor are they in him that is true,
even in his Son Jesus Christ, who is the very God and life eternal. 1 John 5:20.

And so, these that are taught of God learn of him to repent from dead works,
and they do indeed repent.
Others, however, through hardness of heart,
do not so much as discern which are dead works, and which are not, in matters of worship.
Others do not know the true difference between that which is dead,
and that which is living,
but death (unknown to them) lives and reigns in
their very knowledge and apprehensions of things.
Death reigns even in their faith, even in their duties, yes,
in all they believe and perform to God.
For as Paul once thought himself alive without the law,
even when he walked according to the letter of the law blameless,
so too many are now dead,
in the midst of all their knowledges and practices from the letter,
till they come to the ministration of the Spirit.
"`For the letter kills; but the Spirit gives life.`"
2 Cor. 3:6 and see ver. 3.

This therefore is the work of a true minister: to beget into the Spirit,
and into the life.
But oh, how little do men know what dead works are,
and what it is to truly witness repentance from them!
Men who are out of God's Spirit, light, and power, are so far from repenting for them,
that they do not so much as rightly distinguish and discern them!
Rather, they take that for living which is dead, kindling a fire for themselves,
and compassing themselves about with sparks,
thinking the warmth thereof to be the true warmth.
Now, if men have not come to the true repentance from dead works,
much less have they come to the true faith towards God.
So they are yet in their sins, yet outside of Christ,
having never learned of the Father to come to him.
They are still in Egypt's spirit, in Egypt's wisdom, and in that they hold their religion.
And whenever God appears in his Spirit and power,
he will not be to them what they expect,
but rather a dreadful stroke from him will come upon all their ways and worships,
which are as abominable to God as they are pleasing to them.

But alas, what good are words to that ear, to that spirit,
which is like the deaf adder, which will not hearken to the voice of the charmer,
though he charm ever so wisely!
Could the learned Scribes and Pharisees hear the voice of Christ in the days of his flesh?
No, they could not; not in that disputing spirit.
Can the learned professors, who are in the same spirit,
hear the voice of Christ's Spirit now?
No, they cannot.
And if they that cannot hear the voice of the second Adam,
the voice of the quickening Spirit, the voice of him who gives life to the soul,
how can they live?
And if they do not first receive life from Christ,
how can they perform any living action to God?
How can they worship in the Spirit and in the living truth if they
are not first gathered into the Spirit and into the living truth?
Oh, that men could consider aright these things,
and wait on the Lord for the true understanding of them!
For without the true knowledge of God and Christ (without that
knowledge which is life eternal) men must necessarily perish.
It cannot be otherwise; for only the true knowledge saves,
and therefore they which do not have it must perish.

=== Concerning the Law of Christ

[quote.scripture, , Isa. 42:4]
____
And the coastlands shall wait expectantly for his law.­
____

What is that law which the coastlands were and are to wait for?
Is it not the grace and truth which comes by Jesus Christ,
even the grace in the inward parts, even the truth in the inward parts?
The outward law was given by Moses to the outward Jews,
but grace and truth comes by Jesus Christ.
This is the law of the inward Jew, which the coastlands of the Gentiles were to wait for.

The apostle holds forth Christ to be the soul's master (he is the Shepherd, Lord,
King, and Bishop of the soul), to whom everyone must give an account.
Now, for what must men give an account to him?
Is it not for the grace and truth which comes by him?
If any man has received that, obeyed that, believing the sound, report,
and voice of that, and so loved and followed it, will it not be said unto him,
"`Well done,
good and faithful servant`"? But if anyone has neglected and
despised the grace (not improving the talent,
but improving his own natural abilities, while God's talent lay wrapped up in a napkin,
and hidden in the earth),
will not that person be judged a slothful servant as to improving the talent,
regardless of what he has done to improve his own natural gifts and abilities?

Now mind this: If Christ is an inward and spiritual master,
what is his law but the inward teachings of his Spirit?
Moses wrote, "`A prophet shall the Lord your God raise up unto you like unto me;
him you shall hear in all things;`" and he that will not hear him (however
secure and confident he may seem to himself in his state at present),
shall be cut off and destroyed from among God's people. Duet. 18:15-19.
The words, the voice, the motions, the leadings, the drawings,
the commands of his Spirit, are these not the law to all that are spiritual?
Here is the glory of the great Lord and King,
and of the great High Priest over the household of God,
in that he gives forth precepts according to his holy will and pleasure.
Indeed, all his sheep know his voice and follow him,
and all his children and servants observe and obey him.

"`If we live in the Spirit, let us also walk in the Spirit,`" said the holy apostle.
Here are the limits of the children of the new covenant.
Here is the law of life (the law of the Spirit of life in Christ Jesus),
the law of the new covenant, written in the heart,
which none can read but with the new eye.
The children of the flesh may read the letter, and comprehend concerning the letter,
and gather rules and observations out of the letter,
but the children of the new covenant alone can read the law of life in the heart.
And this law is the path of life, the path of all that are renewed by God's Spirit,
which the inward Jew is to read diligently, and in which he is to have his delight,
and to meditate day and night.
And this law is light, true light, pure light, spiritual light, yes,
the light which is eternal and never varies.
The commandment which comes from this light is a lamp,
and they who receive it know it to be no less than life everlasting; for indeed,
the com­mandments of Christ's Spirit are felt to be so.
Now, this commandment, this law, this light, shines in the darkness at first,
but afterwards, it shines out of the darkness more and more (as it is believed, received,
obeyed, and walked in) unto the perfect day.
See Prov. 4:18-19.

[.discourse-part]
Question: But how may I wait for, come to know, and receive this law?
I am not of the stock of the natural Jews, but of the coastlands of the Gentiles.
How may I meet with and receive the law of life from Christ,
or the grace and truth which comes by him?

[.discourse-part]
Answer: The way of receiving it is to carefully mind
that which enlightens and renews the mind,
drawing it out of the nature and spirit of this world, and out of the ways, worships,
knowledge, and customs thereof.
Now, here the grace is met with; here the truth is met with;
here the Spirit of life is met with; here the inward change is felt,
and the new law is written in the heart and spirit.
And here the mind comes to prove and know what is the good, acceptable,
and perfect will of God.
For God is the teacher in the new covenant, and his teachings are here,
even in that which he renews.
He gathers into his Spirit, and he teaches those that abide in his Spirit,
and gives unto them eternal life, eternal virtue, eternal nourishment,
in and from his Spirit.
But they that may be great searchers into the written letter,
and comprehenders from the letter,
and practicers according to their apprehensions of the letter (not
being gathered into nor reading in the Spirit),
these miss eternal life, and the redeeming arm and power,
and are not saved from sin by the blood of Christ.
These are yet in transgression, darkness, and death, even until now.
Now, the Lord, who knows all things,
makes manifest their states and conditions unto them, so that they do not perish forever,
but rather learn of the Father to know the Son, and of the Son to know the Father,
and come to witness true life manifested in their own hearts,
that they may have fellowship with the Father and Son therein.
For he that is not turned from darkness unto
light (from the darkness within in his own heart,
unto the light which God causes to shine there)
does not yet know Christ livingly and savingly,
but remains only in notions and comprehensions which cannot save.
For it is the life and power of the Lord Jesus Christ
inwardly revealed against the power of sin and death,
which alone is able to save the soul.

Now, consider with yourselves (all who would not be deceived in this matter),
have you known this law?
Have you received it in measure,
and do you wait to know and receive it daily more and more?
Then you are Christians indeed, and are of the house of Jacob,
who walk in the light of the Lord, and in the light of the holy city,
whose light is the Lamb.
But without this law, without this light,
without the inward writing of God's Spirit in your hearts, you cannot be inward Jews,
nor children of the new covenant.

=== Of the Grace of the Gospel

The prophets of old
"`prophesied of the sufferings of Christ, and the glory that should follow.`" 1 Pet. 1:10-11.
Now, what was the glory which should follow?
Was it not the setting up of Christ's inward and invisible kingdom in the hearts of men?
Was it not God's abundant pouring out of his Spirit, and filling vessels,
so that the Spirit of grace and of glory should rest upon believers,
even as it had done upon Christ?
Was it not God's tabernacling in men, and becoming their God, and making them his people?
Was it not the fulfilling of precious promises concerning the gospel state,
whereby men should be made partakers of the divine nature (of the heavenly image),
and be changed from glory to glory by the renewing Spirit and power?
Was it not to have fellowship with Christ, not only in his sufferings and death,
but also in his resurrection and kingdom,
where the bread and wine of the kingdom is eaten and drunk,
and the feast of fat things enjoyed?
Is it not a glorious state to be translated out of the
kingdom of darkness into the kingdom of the dear Son,
and to dwell with Christ in the kingdom?
Is it not to have fellowship (pure fellowship,
living fellowship) with the Father and the Son,
that the blessedness and joy of the soul in the gospel state may be full?

The law was a ministration of shadows,
for under it were the various and many shadows of the good things to come,
which were to be possessed and enjoyed in the days of the gospel.
In the law there was an outward people (the outward Jews), an outward covenant,
an outward land of blessings, plenty, and rest.
There was an outward Zion, outward Jerusalem, outward temple, outward ark, outward table,
outward laver, outward candlesticks, outward lamps, outward oil, outward anointing,
outward circumcision and sacrifices, outward new moons and Sabbaths, outward kings,
outward priests, and outward victories over outward enemies, etc.

But now, in the gospel, there is the substance of these things inwardly revealed,
and inwardly possessed and enjoyed.
There is an inward Jew (the new man of the heart), an inward covenant of life and peace,
an inward land of blessedness, of rest,
an inward Sabbath or day of gospel rest (which the true believer keeps in the faith,
not bearing any burden, kindling any fire, nor doing any work of the flesh therein).
There is an inward Zion, an inward Jerusalem or holy city,
an inward temple (in which is the Holy of Holies), an inward ark,
in which the law of life is treasured up, an inward table, inward laver,
inward candlestick, inward lamp, inward oil, inward anointing,
inward circumcision and sacrifices, and solemn seasons.
Indeed, there is now an inward King of glory, an inward Prophet and Priest known,
even Christ within, who gives victories and dominion over the inward enemies,
and gives his to partake of his kingdom and priesthood. Rev. 1:6.
Yes, and by his Spirit poured out upon them,
he makes his children seers and prophets also, as it is written,
"`I will pour out my Spirit upon all flesh,
and your sons and your daughters shall prophesy.`"

Now, was not this fulfilled after the sufferings of Christ in the flesh?
And is it not daily more and more fulfilled as the sufferings of Christ,
which are yet behind, are filled up in his body the church?
Did not the glory then follow?
Was not the gospel spirit and power then revealed and bestowed?
And did it not bring into the gospel state?
Were not the precious promises fulfilled therein? 2 Pet. 1:3-4.
Are they not all yes and amen in Christ?
Is not the veil or covering taken away in him?
Is not the glory revealed in him?
Is not the Lord one, and his name one in him?
Is there not glory then in the highest, on earth peace, and goodwill among men,
as well as goodwill in God towards men?
Where is the enmity and wars, the lusts and fightings?
Are not these things drowned in the love and in the peace,
in the life and in the power which is revealed in the gospel state,
and springs up in the gospel Spirit?
They know not what spirit they are of,
who would have fire come down from heaven upon the disobedient and gainsayers.
To be sure, they are not of the gospel Spirit, not of Christ's Spirit,
who came not to destroy men's lives, but to seek and save that which was lost,
and to overcome by the overflowings of his love and tender visits of his life.
And how do his true children make war in this day?
Is it not with innocency, with meekness, with patience, with hearts of love,
with long-suffering, with truth, with righteousness, like the followers of the Lamb,
like the children of him who abounds within?
Indeed there is a sword given, there is a threshing instrument,
there are darts and arrows to be shot into the hearts of the King's enemies. Ps. 45:3-5.
But these are not to destroy the creature,
but rather to smite and wound that spirit which captivates it,
so that the creature may witness deliverance and freedom from it.
Nevertheless it is true, that they who join with that spirit,
must partake of its judgments and plagues, even to destruction, if they so continue.

Now, this glory is wrapped up in the grace which is ministered by the gospel.
Where grace is sown, the glory is sown (there is a true seed of the glory);
and where grace abounds, the glory abounds.
It was said concerning the first gathering of Christians by the
apostles that "`great grace was upon them all,`" Acts 4:33,
and indeed,
it was a precious and glorious state which they were gathered into and brought forth in.
Now, the grace is revealed again, the grace is poured forth again,
the grace has appeared, teaching and bringing salvation again.
Does it not behoove everyone to know it and partake of
it?--not to be content with words concerning the grace,
but to know the grace itself, receiving it from the hand of him that gives it,
and hearing the voice, reproofs, and instructions of it?
"`Hear, and your souls shall live.`"
Whom should they hear?
Are they not to hear Christ, the great prophet?
How shall they hear Christ?
Is there any other way besides hearing his grace teaching them,
and hearkening to the measure of the gift of grace, which is by Jesus Christ?
"`The law was given by Moses`" (all his people, all his children,
all his family were to come under the law, to be governed by the law).
"`Grace and truth comes by Jesus Christ,`" (all his children, all his people,
all his family are to come under the grace,
to be governed by the grace) who is faithful in all his house,
dispensing of his grace and truth to all his,
even as Moses did of the law (committed to him) to all under him.

So then, all that desire to be truly Christians,
let them wait to know what this grace and truth which Christ gives is,
and to partake of it and come under it--under its teachings, under its influences,
under its protection, under its government (by being subject to it;
and in everything guided by it).
In this they will come to know what that scripture
means in the true and weighty experience:
"`Sin shall not have dominion over you, for you are not under the law, but under grace.`" Rom. 6:14.

=== A Question Answered Concerning Real Holiness

[.discourse-part]
Question: Are not persons to be really holy^
footnote:[The distinction here is between a true inward
transformation of the soul and a mere positional or unexperienced,
imputed holiness.]
(really sanctified in Christ Jesus) who desire to be received by the Lord,
and enjoy fellowship with him as sons and daughters in the gospel of his Son?

[.discourse-part]
Answer: Under the law, the Jews were to be separated from the heathen,
to be outwardly circumcised and cleansed by the water and blood of
purifying (which sanctified to the purifying of the flesh),
and not to touch any dead or unclean thing.
Any such thing polluted them,
and those that were unclean had to be kept outside the camp as
unfit for the holy communion with God and his people,
until cleansed.

Now, what did this signify?
Did it not signify that pure and clean inward state which God requires under the gospel?
Did it not signify the inward circumcision of the heart and spirit before the Lord,
and the cleansing of the soul, mind, and body,
before its appearing to worship in the inward and spiritual temple? Heb. 10:22.
Is there not a Jerusalem under the gospel into
which no uncircumcised or unclean thing is to enter,
or appear before God there?
Mark what the apostle says in Heb. 12.
"`You are not come to the mount that might be touched,`" to outward Mount Sinai,
or Zion, to the appearance of God there; but you are come to the inward Zion,
and to the city of the living God, the heavenly Jerusalem,
and to fellowship with God and Christ there. ver. 18-22.

Now, what is the way to this holy fellowship and heavenly communion?
Does not God himself prescribe it? 2 Cor. 6:16-17.
"`Wherefore come out from among them,
and be separate,`" says the Lord, "`and touch no unclean thing, and I will receive you.
I will be a Father unto you, and you shall be my sons and daughters,
says the Lord Almighty.`"
For God desired to have a people representatively holy in the
time of the law (yet not destitute of inward holiness),
and he will have a people truly holy in the time of the gospel.
"`He that defiles the temple of God, him will God destroy,`" but keep the temple clean,
pure, holy, and then the Holy God will dwell and appear there, according to his promise,
"`I will dwell in them, and walk in them.`"
And this is eternally true,
and witnessed by clear and certain experience among those who
know the Lord--that if anything that is unclean be touched,
there is a defilement thereby,
and there must be a cleansing felt before there
is an experience of the presence of the Holy God,
and enjoying fellowship with him again.

Now, this ought to be the great care of every renewed mind,
even to keep out that which is unclean.
The enemy will be assaulting, tempting, casting into the mind that which is unclean.
But the pure, chaste mind must not entertain or touch it,
but rather withdraw and retire from it into the place of safety,
into the strong tower of defense, from all the assaults and annoyances of the enemy.

Now, blessed be the Lord,
who has revealed and bestowed on his sons and daughters in these latter days,
that light of his Holy Spirit, who searches the most inward parts.
This Spirit discovers everything that is of a contrary nature to itself,
turning and separating the mind from it, and bringing the mind, heart, soul,
and spirit under that which is a cross and yoke to it,
and has power from God to crucify and subdue it.
In this way life and immortality are brought to light and come to reign in the heart,
and death and uncleanness are swallowed up in victory.
For this is the intent of the gospel, and of Christ's appearance, even to destroy sin,
and bring up the holy seed, and establish the law of the new covenant, the law of love,
the law of life, righteousness, and holiness,
in which the renewed should walk before the Lord all their days.

Oh God forbid that the gospel of our Lord Jesus Christ (which
is the power of God unto salvation) should not attain its end,
or that the will of God not be fulfilled.
For his desire is the sanctification of his people in soul, body, and spirit,
1 Thess. 5:23, that they may be wholly leavened with the leaven of his kingdom,
and become a new lump to him.

May the Lord bring this to pass in the hearts of the children of men,
bringing down all religions which do not have the true virtue in them.
And may he propagate and establish that religion
more and more which stands in the evidence,
demonstration, virtue, and power of his own Spirit,
so that men may be redeemed out of deceit in matters of religion,
wherein the eternal condition of their souls is so deeply concerned!
Amen.

=== Concerning the Law of Sin in the Fleshly Mind, and the Law of Life and Holiness in the Renewed Mind

What is the law of sin?
Who writes it in the mind?
And what is it when it is written?
"`When lust has conceived, it brings forth sin; and sin when it is finished,
it brings forth death`" James 1:15. So that the first beginning of sin is evil lust,
and the whole corruption that is in the world is through lust. 2 Pet. 1:4.
Now, from where does this lust come?
Is it not begotten in the mind and spirit by the tempter?
And what is the law, both of the lusting, and of the sins committed through the lust?
Is it not the lustful nature, the lustful will, the lustful wisdom,
the lustful desires and passions,
which the god of this world begets in the worldly part?

Likewise (on the other hand), there is a holy law in the holy and renewed mind.
From where does this law come?
Does it not come from God?
Does it not come from the Holy One?
Is it not he that blots out Satan's law,
and then writes his own law in the hearts of his own?
Now, what is his law?
Is it not of a contrary nature to Satan's law?
Is not God's law what he writes in the hearts of his children, teaching them holiness,
requiring holiness, enlightening the mind unto holiness, manifesting the good, perfect,
and acceptable will?

Under the old covenant the law was at a distance, written in tablets of stone,
but under the new covenant the law is near,
written in the heart by the Spirit and power of the Lord Jesus Christ.
For he is King, the inward King, the spiritual King of his people, who comes to reform,
and amend by his covenant.
Now, because he found (under the old covenant) that laws
outwardly written would never bring men into,
and keep men in, subjection to his Father,
therefore he writes inwardly by his Spirit and power,
and visits with the inward eternal day, even the day of his power.
In this way he makes his people willing to receive the law of his Spirit of life,
which makes "`free from the law of sin and death.`"
For this law being inward and spiritual, and more powerful than the other,
overcomes the other law,
even the "`law of sin and death`" (though it be inward and spiritual,
and inwardly written also), and sets the soul free from it.
Rom. 6:18, and 8:2.

Now, these laws each have their strength from him that writes them.
The law of sin and death has its strength from the god of this world,
the prince of darkness,
who rules in all that are disobedient to the Spirit and power of Christ.
The law of holiness, the law of life, the law of faith in the power,
the law of obedience to God's Holy Spirit, has its strength from the Holy One,
from the Prince of life and peace.
For Satan is near his subjects, and dwells in them, to act in them,
and to make his laws of sin and disobedience forcible in them.
Every motion and temptation to sin he kindles, and adds vigor to,
that he may set on flame the wicked spirits of men after sin, vanity, pride, lust,
uncleanness, cruelty, and all manner of wickedness.
But the Lord also is near to the soul.
The King of holiness, the King of righteousness and peace is near,
to give strength to every holy desire in the heart,
and to every motion of his Spirit towards that which is good and holy.
Hence it is, that he that trusts God's Spirit,
watching to and following the movings and drawings thereof, finds life flow in,
virtue and strength flow in,
to carry on effectually in whatever the Spirit of the Lord moves to.
So that, if one comes truly to know a motion,
or to understand the drawings and leadings of God's Spirit,
then strength is never lacking to him who gives up in the faith to follow the Lord.

Now this is the great skill of Christianity--to come inwardly to know the Lord,
to know the inward appearances of the Shepherd,
to know his leadings out into the pastures where eternal life is fed upon,
and back into the fold of rest, which is no less than the bosom of love and life eternal.
Now, the growth of the new man, the growth of the Christian state,
is in the exercise under the law of life, under the law of the Spirit.
For the Spirit exercises the mind by his law,
and the mind is to give up to the exercise thereof,
and to wait upon the Lord in it day and night, finding itself never without,
but always under the law to Christ in everything.
Indeed,
how can a man do anything aright without the sense and knowledge of the inward law?
How can a man fight aright with his spiritual enemies
without understanding the law of fighting?
For there is a lawful fighting and an unlawful fighting against the soul's enemies.
The unlawful fighting is in the self-will, wisdom, and strength,
according to one's own apprehensions and conceivings, which gains no real ground,
and therefore they that so fight cannot overcome.
The lawful fighting is in the faith, in the wisdom and guidance of the Lord,
in his Spirit and power, and this is ever successful.
So there is a lawful running and an unlawful running the race,
which the apostle plainly implies when he says, "`So run that you may obtain.`" 1 Cor. 9:24.
So likewise there is a law of prayer, a law of faith, a law of love,
a law of new obedience,
a law of liberty (for the liberty under the gospel is not boundless,
but bound by the Spirit), a royal law, which the King of glory writes,
and keeps living in the heart.
By this law his will is understood, and the way of life is known,
which never can be understood by any but those in whom this law is written,
even the law of the new covenant, the law of the Spirit of life in Christ Jesus.

Read and consider this seriously,
for indeed it contains the very mystery of Christianity and redemption.
For redemption is not by a notional knowledge of Christ,
but by receiving and being subject to the law of his Spirit.
Wait to know and understand whether this is not
the law which David speaks of when he says,
Psa.
19, "`The law of the Lord is perfect, converting the soul.
The testimony of the Lord is sure, making wise the simple.
The statutes of the Lord are right, rejoicing the heart;
the commandment of the Lord pure, enlightening the eyes; the fear of the Lord clean,
enduring forever; the judgments of the Lord are true and righteous altogether.`"
Certainly the law of the Spirit of life in Christ Jesus is all this,
containing in it the commandment which is life everlasting, and the sure testimony,
and all the holy statutes, judgments, and fear, which the soul needs to learn.
It is indeed perfect, and able to convert, and instruct perfectly the converted soul.
And here the scripture is fulfilled under this holy law of the Spirit and power of life,
"`They shall not teach every man his neighbor, and every man his brother, saying,
'Know the Lord'`" (they shall not do so in this covenant, under this ministration,
which is a ministration of Spirit and not of the letter); "`for they shall all know me,
from the least of them to the greatest of them.`"
Indeed, they shall know by the teachings of my own Spirit,
by my writing my law in their hearts, by my holy unction, which shall teach my children,
my anointed ones, all that they need to know.
1 John 2:27, Jer.
31, and Heb.
8.
