== Chapter XIV. The Seed of the Kingdom

[.discourse-part]
Question: What is the seed?

[.discourse-part]
Answer: The seed of God is the word of God;
the seed of the kingdom is the word of the kingdom.
It is a measure of the light and life, of the grace and truth, which is of Jesus Christ,
who is the fullness.
It is a heavenly talent, or manifestation of his Spirit in the heart,
which is given to man to bear an increase for God, in the virtue and strength of Christ.
This gift, which God has placed in man to witness for himself,
and to guide man from evil unto good (in the pure breathings, quickenings,
and shinings of it), this is the seed, which is freely bestowed on man,
to spring up and remain in him, and to gather him out of himself, into itself.

[.discourse-part]
Question: Who is the sower of this seed?

[.discourse-part]
Answer: God, in and through Christ.
He is the good gardener.
He, by the word which created all in the beginning, creates anew in Christ Jesus,
renews his workmanship in man,
and puts a measure of this word or Spirit of life in man's heart, whereby he renews him.
Now, these that are thus renewed by him are his workmanship,
created in Christ Jesus unto good works.

[.discourse-part]
Question: Where is this seed to be found?

[.discourse-part]
Answer: It is found where God sows it, which is in the inward earth.
It is an inward seed, and it is sowed in inward land or earth, that is,
in the hearts of men.
There the light of the word shines, there the life of the word is felt,
stirring secretly in and quickening those that were dead in trespasses and sins.
There the voice and call of the word is heard, calling from unrighteousness and sin,
to righteousness and holiness.

[.discourse-part]
Question: In what sorts of earth is this heavenly seed sown?

[.discourse-part]
Answer: In all sorts--in thorny ground, stony ground, highway ground, and good ground.
God's inward lightnings enlighten the inward world throughout,
so that God has not left any man without a witness in his conscience against sin.
And though man's conscience is corrupt, and his light has become darkness,
yet God's witness in his conscience can never be corrupted,
but whenever it shines in the heart, it gives true light there.
Whenever it witnesses there, it witnesses the truth for God, and against man,
and the corruption and searedness of his heart and conscience.

[.discourse-part]
Question: In what sort of earth does it bring forth good fruit unto perfection?

[.discourse-part]
Answer: Only in the good ground.
It brings forth some fruit in other grounds, and the fruit it brings forth is good.
The convictions are good, the desires begotten there by it, and which arise from it,
are good.
The leaving off of some bad things, and doing some good things, is good.
But the thorns, the cares, the worldliness,
and the fear of persecution--these spring up from another root,
and are of another nature, and stifle and choke the seed in the thorny ground.
But the good ground yields its whole nourishment to the good seed (and will not
yield nourishment to any bad seed) so that the good seed not only springs up,
but brings forth fruit to perfection.

[.discourse-part]
Question: How may the ground that is bad be made good?
Was not the ground which is now good, once bad?
And may not the ground which is now bad, be made good?

[.discourse-part]
Answer: God has shut up all men in unbelief, that he might have mercy upon all.
Indeed, the heart that is now soft was once hard.
The heart that is now believing was once in unbelief.
The heart that now loves God, was once in the enmity.
The plow of God, put into the thorny ground, tearing it up, and rooting out the thorns,
will change its nature, and make it become better.
"`Break up your fallow ground; sow not among thorns;`" said God to his Israel of old.
Does not man, by care, art, and industry, change the nature of outward land or ground?
Surely then, the Lord by the word of his power can change the nature of inward ground.

Now, for the clearer and plainer signifying of what yet remains on
my heart concerning this precious seed of the kingdom of God,
I shall consider it under these three headings:
I+++.+++ What is hid or wrapped up in this seed, II. The nature of the seed, III.
The effects of the seed.

[.alt]
==== I. What is wrapped up or hidden in this precious, heavenly seed?

Indeed, there is so much wrapped up in it, as the heart of man cannot conceive,
much less the tongue utter.
Nevertheless, I have felt something,
and it is upon my heart to answer this thing under the following headings.

_First,_ the glory of the kingdom of heaven, the glory of the everlasting kingdom,
is hid and wrapped up here as in a seed.
In whatever way Christ appears, reigns, and shines, he does so here in this seed.
Oh, the shooting forth and spreading abroad of this seed is indeed glorious and excellent!
How can a man speak concerning it?
The thing itself (being inwardly felt, known, and enjoyed) is so far beyond all words!
What does the kingdom of God stand in?
It stands not in word, but in power.
The power is hid and wrapped up in this seed.
The pure power of life is in this seed.
The sword that pierces Leviathan, that wounds the serpent's head,
that cuts Rahab and the dragon, is in this seed.
Does the kingdom of God consist in righteousness, peace, and joy in God's Spirit?
This is all in this seed,
and is partaken of and enjoyed as this seed springs up
and gains authority and dominion in the heart.
Yes, the horn of God's anointed,
the righteous and peaceable scepter of the Savior is known and exalted in this seed,
as it springs up and spreads abroad in the life and virtue of the Father.

_Secondly,_ the divine nature of God Almighty is hid and wrapped up in it.
It is the seed of God, and it is the very nature of God.
Therefore, the one in whom it springs, and who is gathered into it, born of it,
and made one with it, partakes of the divine nature.
Peter speaks of the great and precious promises by which the
saints are made partakers of the divine nature. 2 Pet. 1:4.
All the promises are to the seed of promise, Gal. 3:19,
to Christ the Son of God, to the seed of God,
to the heirs of life and salvation in Christ.
And these promises are all fulfilled to them, and enjoyed by them,
who are ingrafted into, and made one with Christ, the seed.
Now this cannot be, except by the grace, by the truth, by the light, life, Spirit,
and power, which he sows in the heart, which are not many things,
but are all contained and comprehended in the one seed.

_Thirdly,_ the new covenant,
even the holy agreement of the soul with God in Christ Jesus, is in this seed.
Here is the covenant which God makes with the new Israel,
by which he makes the heart new, and writes his law in it,
and takes away the stony heart, and heals all their backslidings, and loves them freely,
and puts his Spirit within them,
causing them to walk in his ways and to keep his statutes and judgments, and do them.
God gave Christ for a covenant, and the seed of grace and truth comes by Jesus Christ.
All that receive this grace and truth from him (in the
holy seed of the kingdom) receive the covenant;
and they that walk in it, walk in the covenant.

Here, and here alone, the new creation in Christ Jesus is known.
Here, and here alone, the coming to God by Christ is truly understood and witnessed.
Here, and here alone,
the law of the Spirit of life in Christ Jesus is written in the heart.
Keep here, and you will never go outside of the holy agreement with God,
for in this grace and truth, in this seed of life,
there is nothing that disagrees with him.
Here you live in the Spirit, walk in the Spirit,
and do not (indeed cannot) fulfill the lusts of the flesh.
There is nothing in this seed that will either displease God,
or lead your soul aside from him.
Rather, here the Lord guides the feet of his saints, and teaches all of them,
putting his law of life and new obedience, and his Holy Spirit, into their hearts,
so that none of their steps may slip.
Here the way of holiness, by which God preserves from erring, Isa. 35:8,
is known and walked in.
Yes, here Christ is known and felt to be the way, the truth, and the life.
The sheep that are gathered here, and come here,
have returned to the Bishop and Shepherd of their souls, who watches over them,
and powerfully preserves them, that they run astray no more.

_Fourthly,_
all the graces and virtues of God's Holy Spirit are hid and wrapped up in this one seed.
There is nothing God can require of the soul, nor anything the soul can desire of God,
but what is hid and wrapped up in this seed.
All that is needful, or all that can be desired,
is the growing and spreading of this seed in the soul, and the soul's gathering into it,
and its living, dwelling, abiding, and acting in it.
And oh, the great difference between the soul's selfish striving, willing,
and running to join to God, and God's joining the soul to himself in this seed,
and his living, willing, and acting in the springing life of this seed!
Now, to make this a little more plain and evident to the hearts of those
that desire the true understanding of these graces and virtues,
I shall give some particulars under this fourth heading.

First, the pure, living, heavenly knowledge of the Father, and of his Son,
Christ Jesus, is wrapped up in this seed.
God is light, and this seed, which comes from him, is not darkness, but light;
and in the light that springs from this seed, God and Christ are revealed.
Their divine nature springs up in the seed, and if one knows their nature,
then they are truly known.
Indeed, here we know the righteous Spirit of Christ, the righteous nature of Christ,
the righteous life of Christ, and we feel him to be one with the Father,
who begets of the same Spirit, nature, and life in us.
And he that is born of the Spirit is spirit;
and he that is united to the Lord is one spirit; and he that is united to the seed,
to the measure of grace and truth from Christ (wherein and whereby the soul is united),
is united to God, and ingrafted into Christ.
And as the seed is formed in him, Christ is formed in him.
And as he is formed and newly-created in the seed, he is the workmanship of God,
formed and newly-created in Christ.

Secondly, faith, the true faith, the lively, effectual, saving, conquering faith,
which gives victory over the world, and over the devil and his temptations,
is contained or wrapped up in this seed.
Faith is the precious gift of God, which is not found in man's nature,
but springs and grows from the precious seed of the kingdom,
which God sows in man's heart.
Indeed, faith is a gift to be waited for and obtained from God.
Therefore the apostle Peter, writing to the saints in his time,
directs his epistle in this way--"`To those who
have received like precious faith with us,
through the righteousness of God, and our Savior Jesus Christ.`" 2 Pet. 1:1.
Faith is a precious thing, a righteous thing, a holy thing,
of which God is the giver, and Christ is the author and finisher.
This faith springs from the holy root,
from the holy seed of life and righteousness which God sows in the heart.
This faith (I speak not of man's ability of believing,
or the faith which is found in man's nature) is the faith of God's elect. Tit. 1:1.
The faith which God gives to them that are born of him, John 1:12-13,
who are born of the incorruptible seed, by the Word of God,
which lives and abides forever. 1 Pet. 1:23. And this Word,
being near in the mouth and heart, and begetting, preserving,
and increasing faith there (as is daily experienced),
is therefore called the word of faith. Rom. 10:8.

Thirdly, the pure fear, the holy fear, the heavenly fear,
which is of a clean and heavenly nature, and endures forever, is also in this seed.
This childlike fear is a promise of the new covenant,
and is given to the children of the new covenant-- God putting it
into their hearts from the seed of life springing up in them,
which preserves them from departing from the Lord. Jer. 32:40.

Fourthly, the pure divine love is in it.
As this seed springs, so love springs to God.
As God is love, so the seed that is of him partakes of his love.
There is no enmity in it, and no enmity or contrary will springs from it.
This makes it so natural to the children of God to love,
for they are born of that seed which came from the God of love, whose nature is love.
Oh, how daily is it found, by sweet and certain experience,
that this seed (springing up) teaches and enables to love!
And they that have this seed springing up in them need
not to be outwardly taught to love with brotherly love,
for in the seed, and by it, and through it, they are taught of God to love one another.
So that the soul needs nothing but the circumcising of the heart,
the purifying of the heart, through the obedience of the truth,
the cutting off of that fleshly mind, nature, will, and wisdom, which cannot love aright.
Then the pure love will spring up fully towards the Lord, and towards the brethren. Duet. 30:6.
1 Pet. 1:22. Yes, it will be natural to love all,
and that command of Christ will not be grievous--namely, to love enemies,
even the greatest revilers, cursers, and persecutors. Matt. 5:44.

Fifthly, the pure hope, the hope of the upright,
the hope which makes not ashamed, the hope which goes within the veil,
and is a sure and steadfast anchor there, staying the mind upon the Lord,
who keeps such in perfect peace--this hope is contained in, and springs from, the seed.
For nothing but that which comes from God (from the holy seed
of truth and righteousness) can stay the mind upon God.
So that he that feels the seed, feels the hope,
and keeping to the seed (to the holy root), the hope remains.
So the mind being turned to the light, being turned from Satan's power to God,
being turned to Christ,
being turned to the appearance and voice of the word of life within,
being turned from the seed of wickedness and darkness,
to the holy and righteous seed of the kingdom,
it is turned to that which begets a true and right hope in the heart.
This is not a hope in the flesh, but in the holy and heavenly seed,
and the work of righteousness and of the kingdom,
which is God's battle-axe and weapon of war, whereby he brings down the flesh.
This hope stays the mind in every temptation, in every distress, in every trial,
in all the winds, storms, and waves of persecution that it can be assaulted with.

Sixthly, the true patience, and its perfect work, James 1:4, is contained in,
and given with, this seed.
As God is patient and longsuffering, so is this seed also.
It is man that is of the brittle, fretful, and impatient nature,
but he that receives the word of faith, the seed of faith,
in it he receives faith and patience also.
To this one it is not only given to believe, but to suffer also for the sake of Christ.
And he that abides in the seed, and feels the seed remaining in him,
and its nature prevailing, can never be impatient,
whatsoever the Lord allows to befall him.

Seventhly, here the true poverty of spirit is witnessed.
He is poor indeed who has sold all, and has nothing left him except this seed,
and the appearance and help of God in this seed; which also is not in his own hands,
but in the will and disposal of God.

Eighthly, here true mercy towards others is experienced;
for he that is brought to the seed lives only by mercy; and he that lives by mercy,
and is daily what he is by mercy, cannot help but be merciful unto others.

Ninthly,
the true hungering and thirsting after righteousness arises from this seed.
It is the seed of God, the birth of God,
which has a sense of the excellency of his righteousness,
and which hungers and thirsts after his righteousness.

Tenthly, to name no more,
the cross which mortifies and crucifies to the world and to sin,
can only be taken up in the seed, or by virtue of the seed.
Indeed the seed is a cross, yes, it is enmity to the serpent's nature, spirit, and course.
He that takes it up (with its will, its nature, its law of life),
takes up the cross to the other nature, will, and the law of sin and death.
So that if you miss the holy seed, you can have only a shadow or image of the cross.
But in the true sense of, and subjection to, the seed,
the cross of our Lord Jesus Christ is felt working powerfully against sin,
effectually crucifying and subduing the whole course of the evil and sinful nature.

[.alt]
==== II. What is the nature of the seed of God, or the seed of the kingdom?

[.discourse-part]
Answer:
Though the nature of it has been largely signified already under the previous heading,
yet I shall speak a little more expressly of it in several particulars,
according to the Scriptures.

_First,_ it is of an immortal, incorruptible nature. 1 Pet. 1:23.
It is a seed that can never die in itself,
though it may seem dead in man, or unto man,
when not putting forth any of its hidden life or
virtue in the man who has slain it as to himself.
For the one who has rejected and slain the seed by which God gives life,
is still dead in trespasses and sins,
and cannot live till God breathe upon and quicken this seed in him,
and so bring him to life by the seed.

_Secondly,_ it is of a gathering nature.
It has the nature of a net. Matt. 13:47.
It gathers out of that which is contrary to God, unto God.
It gathers out of the world, out of the sea of wickedness,
out of the kingdom of darkness, out of a man's own nature and spirit,
into God's nature and Spirit, and his light and kingdom, wherein the soul should dwell,
and walk, and be subject to God.

_Thirdly,_ it is of a purging or cleansing nature.
It is of the nature of fire, of the nature of water, inwardly and spiritually.
This seed is Spirit and life in a measure,
and by it (or by God's Spirit which dwells and is revealed in it) he
washes and purges away the filth of the daughter of Zion.
There is strength in this seed, and virtue in this seed,
against all the strength of deceit and wickedness in the other seed.
And as the seed of the kingdom springs up,
and is received and joined to in the holy fear of the Lord,
it prevails over the contrary seed, and casts away its darkness,
and purges away and burns up its filth, chaff, and corruption.

_Fourthly,_ it is of a seasoning, leavening, sanctifying nature.
It is like salt; it is like leaven.
It seasons and leavens with life.
It seasons and leavens with righteousness.
It seasons and leavens with the image of God.
Just as soon as it springs in the heart, it begins to leaven it.
And if it be not neglected, or grieved, or hurt,
or quenched (for it is of a most sensitive, tender nature),
it will go on leavening more and more with the nature of truth,
into the likeness of the God of truth.
See Mark 9:50, Luke 13:21, and Col. 4:6.

_Fifthly,_ it is of an enriching nature.
It is a hidden treasure or pearl of great price.
It makes the wise merchant very rich, who sells all for it, and buys the field with it.
He that buys the truth, and will by no means sell or part with it,
but gives up to it and makes it his treasure,
oh how does it enrich his heart with that which is holy and heavenly!
How rich does it make him towards God! Matt. 13:44-46.

_Sixthly,_ it is of an increasing, growing nature.
The one talent may be increased into more.
The little seed, like a grain of mustard seed,
will grow in the good ground beyond all herbs, and become a tree,
a tree of righteousness of the Lord's planting, that he may be glorified.
Matt. 13:31-32, chap.
25:16, chap.
13:23.

[.alt]
==== III. What are the effects of this seed?

[.discourse-part]
Answer: The effects of the pure seed in the heart are very many, very great, very sweet,
precious, and blessed, which everyone comes to experience,
who experiences the growth and spreading of it.
I shall mention only a few.

_First,_
is a true union and communion with God the Father of our Lord Jesus Christ,
the Father of this seed, and with all that are united to it.
Union and communion with God is in this seed, and never out of it.
For in the seed of the serpent, a man is separated from God, alienated from his life,
and can never come near him or have fellowship with him.
So in the holy seed, in the seed of life, in the seed of righteousness,
in the seed of faith, the soul is united to God, has access to him, the living fountain,
and has fellowship with him in that which is living and holy of him.
Men may imagine a union and communion with God outside of this,
but none can truly unite to God, or have fellowship with him, except in the gift,
in the grace, in the light, in the Spirit which is of God.

_Secondly,_ this seed is felt springing up in the heart, and when joined to,
it brings down and keeps down all that is contrary to God.
This honor and power God has given to the seed of the woman (even to
the least measure of it)--that it should bruise the serpent's head,
and free the soul from captivity and slavery to the wicked one.
Thus the soul, in the living sense, authority, and virtue of this seed,
may refuse yielding its members, its faculties, its will, its mind, its understanding,
its affections, to sin and unrighteousness.
Yes, the devil, the great red dragon, the god of the world,
the mighty spirit and power of darkness, being resisted in this, is truly overcome.
When any resist the devil in their own strength (in the strength of their own desires,
abilities, and resolutions), they are still overcome by him.
But they that resist the devil in the faith that springs from this seed will overcome him.
So it is that sin is brought down, and temptation kept out,
by the virtue and power of the life and authority of
the Savior that springs up in this seed of God.

_Thirdly,_ as it springs, and as its operations are felt and received,
it brings into the image and nature of God.
It blots out the devil's image in the mind, and renews like unto God and Christ.
Yes, here we have the very mind of Christ, and are made one with the mind of Christ.
As in the serpent's seed, the serpent's image and nature is put on; so in this seed,
the image of God and Christ is put on.
Yes, the serpent, the dark spirit, the wicked spirit, the deceitful spirit,
is here put off, and Christ is put on.
And whoever desires to know the real putting off of the old man,
and the putting on of the new man (which is created in
the righteousness and holiness of truth),
must know it in this seed.

_Fourthly,_ the seed brings the mind, the heart, the soul, the spirit,
into the new obedience (into its own obedient nature),
even to do the will of God with great delight and pleasure.
"`I delight to do your will,`" said Christ.
This seed is of his nature.
It is a measure, a proportion, a heavenly talent of his grace and truth,
a gift of light and life from him who is the fullness.
It is given to make willing (like him) to do the Father's will, and it really does so,
insomuch that the soul which is thoroughly leavened and one with it, can also say,
"`I likewise delight to do your will, O God!
It has become my food and drink, for I am nourished and refreshed,
and delight in the virtue that I feel spring in me, in doing your will.`"
Indeed, it is not so at first, while there is a nature, a will,
a wisdom contrary to the nature, will, and wisdom of God.
Then obedience is hard, and the cross is still a sore yoke upon the neck.
But that nature being subdued, and the nature of the seed coming up and prevailing,
what can be more delightful to this new nature
than to do the will of its heavenly Father,
and to find the heart of the Father pleased with the child?

_Fifthly,_ it brings into the understanding, sense,
and enjoyment of all the precious promises,
and all the spiritual blessings in Christ Jesus our Lord.
All the promises are to the seed and are yes and amen in Christ,
and the least measure of his life has a share therein.
The seed, the everlasting seed, is the heir, and we who are joined to the seed,
born of the seed, and growing up in the seed, are joint-heirs with Christ.
So that every promise comes to be understood here, tasted here, enjoyed here.
How full are the Scriptures of sweet and precious promises!
Alas, what good is it for men to apply them to themselves,
when they have no right to them, nor indeed rightly understand them,
nor were they intended by the Lord to man's present state and condition!
But to come to the true understanding of the promises,
to be led by the Lord into that condition,
and preserved by him in that condition to which the promises belong--oh, how sweet,
comforting, and joyous is this!
Indeed, in this seed all the curses of the book pass away,
and all the blessings flow in and multiply on the soul day by day.
So that this may well be called the blessed seed, for in it the soul is truly blessed,
and filled with blessings by him who is able to multiply them upon the soul,
and to guide the soul in the safe and right use and enjoyment of them.

But need I mention any more?
Here is light, here is life, here is righteousness, here is peace, here is heavenly joy,
here is the holy power,
springing and bringing forth its fruits and precious operations and effects in the heart.
Here is assurance of the love of God in Christ forever,
and the knowledge that God will never leave nor forsake that soul which is joined to him,
and abides with him in this seed.
Such a soul will be kept by the power of God,
through the faith that springs from this seed, unto perfect redemption and salvation.
Amen.

=== A Brief Clarification Concerning the Imputation of Christ`'s Righteousness

God visits men by the light and power of
his Holy Spirit in their dead and dark state,
even while they are ungodly.
Now, they that feel life, and in the quickenings of life,
by the faith which comes from life, turn to the light and power which visits them,
these are in measure transplanted out of the unholy root, into the holy root.
Here they partake of the nature and virtue of the true olive tree,
and the mercy of the Lord in and through his Son Jesus Christ is spread over them,
and their iniquities are pardoned,
and their transgression is done away for his name's sake.
These are reckoned by God, not as in the old root and unholy nature,
but rather in that root which they have laid hold of by faith, and are in union with it.
Here they are reckoned in the eye of the Lord,
and they are accepted and beloved in him in whom they are found,
by him who transplanted and ingrafted them there.
So that Christ is really theirs, and they are his.
And what he did for them in his body of flesh has become theirs,
and they have the benefit, and reap the sweet fruits of it.
And if they sin afterwards, they have an advocate who pleads their cause with the Father,
and who breathes livingly upon them again, and quickens faith in them,
and gives them to turn away from that which ran after them, overtook them,
and defiled them.
So that in this state of true faith in, and union with, the Son,
a fountain is felt to be open for sin and for uncleanness,
which daily washes away the pollutions and stains of the mind,
which it is susceptible to in the traveling state.

But now, to every claim of faith these things do not belong,
but only to the faith which flows from the power of the endless life,
and which stands in the power.
The faith which is from the power is precious, having a precious nature and virtue in it,
and very precious effects flow from it.
For it is the substance of things hoped for; it is of a pure nature, which has dominion,
and gives dominion over the wicked one.
But the belief in Christ, or the applying of his righteousness,
which is not of this faith,
nor in the true light of life (but rather according to
the creature's apprehensions concerning things),
this is not of the same nature, nor does it have the same virtue,
or produce the same effects.
For, despite this kind of believing and hoping, men are still in their sins,
and they are not washed away from them by the blood of Christ,
nor remitted or covered by the Spirit of the Lord.
And oh, that men were wary, and did take heed in this matter,
that they might not miss the true pardon from the Lord!

For there is indeed a state wherein Christ's righteousness is
imputed to persons reached by the power of the Lord,
who are coming up out of the ungodly state into the true righteousness.
And in the true growth,
the soul daily grows more and more out of its own unrighteousness, out of the dark,
corrupt image, into the righteousness of Christ, and into his pure image.
Thus, Christ is formed in the hearts of them that truly believe, daily more and more.
They receive him as a heavenly leaven, and giving up to be leavened by him,
are changed daily more and more into the newness of the Spirit,
even until they become a new lump, a lump wholly leavened.
So it is that old things are passed away, and all things become new,
that is--they are not of old Adam any more, but are all of God in Christ.
They are all of the new nature and Spirit, which is righteous in the sight of God.

Now,
this is what all should labor for and seek after--even
the kingdom of God and his righteousness,
to find an entrance ministered to them into the everlasting kingdom,
and the righteousness thereof,
that they might really put off the old man with his affections and lusts,
and put on the new man, the new man's nature, image, spirit, and righteousness.
All should seek the true wedding garment in which to be married to Christ,
to be as a bride prepared for the bridegroom.
Oh, it is precious for anyone to feel his soul in this state!
And who would not travel and wrestle and strive and watch and pray and wait,
that he might be thus fitted by the Spirit of the Lord for his Son Jesus Christ?

Oh,
that such as take upon them the profession of Christianity might feel the power,
and wait upon the power, and know what it is to believe in the power,
and live in the power.
For without this, the oppressed state of Christianity is but dead, dry, and cold,
not having the true living sap and warmth in it.
There are great deceits in the world about the
imputation of righteousness and such things.
But he that knows the truth as it is in Jesus, who has been visited by the power,
gathered to the power, and abides in the power,
he has found that which anoints the eye and heart,
and strengthens against the most subtle devices and deceits of the transforming spirit.
But whoever professes Christianity, and yet is not here, he is not safe,
but the enemy has ways of bewitching and deluding him,
which he cannot effectually withstand and avoid.

=== A Brief Question About Reading Scripture Aright

[.discourse-part]
Question:
What is the right reading of the Scriptures so
as to benefit and profit the reader's soul?

[.discourse-part]
Answer: He that reads the Scriptures in a true measure of life received from God,
he reads them aright, and whenever he so reads, it is to his benefit.
He that reads outside of that measure of life reads to his own hurt,
for the nature that misunderstands, misapplies, and grows conceited, wise,
and confident according to the flesh is still at work in him.
This one is prone to set up his own interpretations
instead of the meaning of God's Spirit,
and also to condemn all that does not assent and agree with his own understanding.

The true birth is meek, tender, gentle, fearing before the Lord,
waiting upon him, often crying to him, that it may not be deceived,
that a wrong thing does not rise up in it,
and that it receive nothing for truth except what God knows to be truth.
And when the Lord is pleased to give the true knowledge,
it is held in the Lord's righteousness, in his life, in his will, in his wisdom, etc.
But the wrong birth is not so, but instead is subtle in searching and forming ideas,
and holding them in subtlety,
and drawing the wrong part in others to agree with and
acknowledge that which it represents and holds forth as truth.

There is a wisdom in man which is against God.
This wisdom opposes the wisdom of God in two ways:
either in a direct and contradictory way, or in a secret, subtle, undermining way.
Now, no man can come to God, or truly understand or receive the things of God,
except as this wisdom comes to be confounded and
destroyed in him by the light and power of God.
All of its strongholds, all of its subtle imaginations,
all of its reasonings and consultings must be dashed and brought to nothing
before the truth of God can have full place and power in the heart.

Now, in the true discovery of this false wisdom, and in the soul's denial of it,
watching against it, and turning to the true wisdom, a man may wait upon God aright,
read the Scriptures aright, and come to the true sense, understanding,
and experience of them.
But if at any time he is without this, he is liable to the enemy's snare,
to the misunderstanding of Scriptures, and to the fleshly confidence that arises therein.
So that, having taken up a misunderstanding of a Scripture,
he will even boldly venture to speak evil of the
heavenly and spiritual things which are of God.
Oh how does this wisdom destroy and entangle!
And how has it destroyed and entangled many in this day who think they are greatly
for God in those things and practices wherein they are directly against him!

Now mark well: The Spirit, the truth, the life, the substance, is God's forever,
and the unclean spirit cannot enter into it, nor can the unclean womb conceive it,
or bring it forth.
However, the letter, the shell, the outward figure,
the outward relation and description of things--these the other spirit, wisdom,
and nature in man may read, guess at, transform, receive, believe,
and build up according to the flesh.
And here is the foundation and rise of antichrist and
Babylon in those who raise up a building,
a knowledge, a faith, a hope, a church, a worship, duties, ordinances, justification,
sanctification, etc., in the imitation of Zion.
But these things are not the thing itself,
but rather false representations of the thing--either such as were invented by man,
or such as were once appointed and made use of by the Spirit of the Lord.
For there is little difference between inventing a new thing,
and making use of an old thing which once was of God, but is now understood, observed,
and practiced outside of the sense, light, and guidance of his Spirit (in another spirit,
and according to another wisdom).

Now, this is not the right way of reformation, namely,
to return to outward and literal things, which were practiced by the Jews in their day,
or by the former Christians in their day,
but rather to return to the Spirit that they were in,
and to feel (in the true life and leadings thereof) what it
teaches and requires to be observed and practiced now.
For there are things whose value is not in themselves, but in God's requiring of them,
which the wrong spirit may get into.
And the Lord may draw his people out of these things (as he did out of the outward court,
into the inward building or temple, by his light and Spirit within,
when he gave the outward court to the Gentiles.
Rev. 11:1-2). And he that is found in these
things after God has given them to the Gentiles,
and drawn his people out of them, is no longer owned or accepted of God in them,
though God may bear with him in the time of his ignorance.
Yet if he abides in them after the rising of light and its testimony,
the Lord will not so bear with him, but will condemn him,
and deal with him as a transgressor of that covenant
wherein life and peace with him is witnessed.

Therefore, in all things that concern God, whether in reading the Scriptures,
praying, or observing anything called duties and ordinances,
oh that you would approve yourselves Christians indeed,
waiting to know your guide and leader, and the true limits which are set by God!
For thus you may serve him in the true faith, Spirit, and understanding,
even in that which God knows to be so, and not in that which you may falsely account so!
For mark: if you are Christians, are you not in Christ, and is not Christ in you?
And are you not to feel his life, and the guidance of his Spirit,
so that you may live in the Spirit, and walk in the Spirit, read in the Spirit,
pray always in the Spirit, believe in the Spirit, worship in the Spirit,
and in the holy understanding of his truth, which is of him?

He that would be right in religion, must have a right beginning.
How is that?
He must begin in the Spirit, that is, his knowledge, his faith, his hope, his peace,
his joy, his righteousness, his holiness, his worship, etc., must begin there.
He must come out of his own spirit, his own wisdom,
the counsels and thoughts of his own heart,
and wait on him who begins the work of regeneration and life in the heart.

And afterwards,
he must diligently watch against that spirit and
wisdom out from which the Lord has led him,
that it at no time enters him again.
For it will be striving to lead him out of the
way with likenesses and false images of things,
with false knowledge, with a faith that is not truly of God,
nor of the same nature with that which the soul first felt.
It will present him with false hopes, false fears, false joys,
a false righteousness and holiness, which are not Christ's,
nor according to the Scriptures, but only such as man apprehends to be so.
For a man, who once tasted the truth, and in some measure judged aright,
may afterwards err in his palate and judgment, and then take the wrong for the true,
not keeping to that which formerly gave him the true relish.

Now, he that would meet with the true religion, the religion of the gospel,
must meet with the power, receive the power, believe, dwell, and act in the power.
For Christ was made a king, priest, and prophet,
"`not after the law of a carnal commandment,
but after the power of an endless life,`" and his covenant is not like the old,
in word or letter, but in the same power and life.
So the knowledge here, the faith here, the hope here, etc., are not literal, but living.
He that receives this knowledge, receives living knowledge.
This faith gives victory over unbelief,
and over that spirit whose strength lies in unbelief.
This hope purifies the heart, even as he is pure.
And he that receives the righteousness of this covenant, receives a living garment,
which has power in it over death and unrighteousness.
The beginning of this religion, this power and holy inward covenant, is sweet,
but the pure progress and going on of it is much more pleasant,
as the Lord gives to feel the growth and sweet living freshness of it.
Though there are temptations, fears, troubles, trials, oppositions, and great dangers,
both within and without,
the soul that keeps to the life (which it was first
turned to) finds the yoke easy and the burden light,
as the mind and will is changed by the power,
and helped and assisted by the Lord in its subjection to the power.

So, may the Lord God of tender mercies remove the stumbling blocks,
and lead the wandering souls (who are entangled in their own thoughts
and reasonings about the letter) into that which is Spirit and life.
For the Spirit and life was before the letter,
and excels the letter (with its dispensation) in glory,
and is to remain after the letter, and be the rest, joy, life, peace,
and portion of the soul forever and ever.
So honor the letter, in believing its testimony concerning Christ, who is the Shepherd,
the way, the truth, the life itself, to whom the soul is to come,
and on whom the soul is to wait for life.
And having received life from him, then dwell, abide,
and grow up into him who is the life.
Do not go backward into anything that is literal, or without life,
nor seek glory in the knowledge, or literal descriptions of things,
but go forward into the spiritual, heavenly dispensation of life and power.
The law was letter, the gospel is life and power.
The law was a shadow of good things to come, but the gospel is the substance, the life,
the virtue, the Spirit of what the law shadowed out.
From here the Christian is to spring, the Jerusalem from above is to be its mother,
and the Holy Spirit its begetter.
And here the truth, sweetness, and fullness of words is known, felt, and witnessed,
even in that which comprehends them, and gives them their due weight and measure.
For none can possibly understand the words of the Spirit except he that is in the Spirit;
and then he knows both the place of the words which came from the Spirit,
and the Spirit from whom the words came.
Oh this is precious!
But it will not be witnessed by the wise disputer, but only by the serious traveler,
who is first broken and dashed to pieces in his own wisdom,
and then afterwards is healed, led, and guided by the eternal Spirit of wisdom,
which is the sure and unerring guide.
