== Chapter XV. Letters of Isaac Penington / Written between 1666-1679

[.letter-heading]
To Friends in the Two Chalfonts

[.salutation]
Dear Friends,

You have a deep place in my heart, and my cries are to the Lord for you,
that you may live to him, and find his life springing up and abounding in you.
What is it to have a distinct name, or distinct meetings from the world,
unless the power of the Lord is felt in your hearts,
and his presence is in your assemblies?
Oh that the Lord would awaken you!
Oh that the Lord would quicken you!
Oh that it would please the Lord to raise up a
strict watch in you against all drowsiness,
carelessness, temptations, and snares of the enemy,
that you may travel on your journey with your
backs upon the world and your faces towards Zion.
And may you never look back to the fleshly nature, desires, or lusts,
to entertain anything of that anymore.
For you have parted with such things in the demonstrations and leading of life,
and must press on further and further,
till you come to apprehend and be possessed by
that for which you have been apprehended by God.

O my friends, there is a path of life in which you must travel,
even to the very end of it, or the crown of life is not to be received!
Oh that you might travel on, and that nothing might stop you!
Oh that you might every day wait for and feel the leader,
and walk on with him in the simplicity, uprightness, and sense of his life,
out of the reach of that wisdom which is always
forming reasonings in the heart against it,
and striving to darken and to make difficult the plain way of God.

May the Lord God of mercy watch over you,
pruning and keeping down all the earthliness and corruption in any of you,
and watering and cherishing his own plant in you all,
that you may daily witness the dying and decrease of the one,
and the quickening and growth of the other,
even till death be perfectly consumed and swallowed up by the growth, power,
and presence of the immortal life in you, and your souls safe and happy in your God.
O my friends, prize the rich,
tender mercy of the Lord in calling you out of this world
towards his everlasting inheritance and fullness of life!
And let not anything of this world come between him and you,
but let all that is of this worldly nature, both within and without,
be trampled upon by you.
Let the prize of the high calling of our God in Christ
Jesus be faithfully and earnestly pursued after,
so that none fall short of the hope and glory set before you.
And may everyone so run as to obtain and enjoy forever the
dominion and reign of God over all that is contrary to him,
and so sit down in the rest, joy, and peace of his nature forevermore.
Amen.

Your friend and brother, in the meek, innocent nature of the Lamb,
from my present place of confinement in Aylesbury, according to the will of God,
who is blessed, and to be blessed in all that he does, or allows to be done,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
22nd Third Month, 1666

[.letter-heading]
To Friends in Truth in Chalfont and Thereabouts

Dear friends, whom I love in the Lord,
and whose prosperity and growth in the truth I greatly desire,

This advice sprang in my heart to you this morning:
Mind and keep watch to that which quickens and enlivens the soul towards God,
and watch against that which flattens and deadens it.
For these are both near, and they both seek after you, the one for your good,
the other for your hurt.
I need not tell you what these are, nor where or how they appear,
but in continual watching to the one, and against the other,
is the diligence and care of your spirits daily to be exercised.
Oh, at no time let your spirits be loose and careless!
For the enemy waits to do hurt, and the Lord waits to be gracious,
and to do your souls good.
Watch therefore, and pray, that you enter not into the temptation of the enemy,
nor miss the tender mercies and lovingkindness of the Lord,
which are sure to the seed (and to all that are of and abide in the seed) forever.

And, my dear friends,
mind your meetings together to wait upon your God with
great seriousness and intention of spirit,
everyone watching to feel life rise up in your own spirits.
Oh, sit down (yes,
breathe earnestly to the Lord to enable you to sit down) in the silence of flesh,
and in the stillness of your spirits, waiting for the presence, appearance,
and power of your God to be revealed in the midst of you.
In this way your hearts will be searched more and more,
and the pure judgment will be revealed against whatever would
appear or rise up contrary to the holy nature and will of God,
and that which is for death, will be brought into death more and more.
Thus the impure will be kept down,
and that which is pure (the plants and trees of righteousness) may thrive, flourish,
and spread more and more,
and you will sit down under the shadow of your own vine and olive-tree,
partaking of the sap and fatness thereof.
Oh that every one of you, in all your meetings together,
might witness that scripture fulfilled in you--"`They shall be
abundantly satisfied with the fatness of your house,
and you shall give them to drink of the rivers of your pleasure.`"

I beseech you, with a heart of tender love, to take heed of sluggishness,
or carelessness, or deadness of spirit in your meetings.
These things are in no way becoming of the Lord`'s people,
nor of your professions of waiting upon the living God.
You are to look up, to watch, wait, and breathe for the Lord,
to be exercised by his Spirit before whom all things are naked and bare,
and to offer up that acceptable sacrifice of a broken heart, of pure praises, of love,
life, humility, thanksgiving, etc.
You are to receive what the Father of mercies stands
ready (in and through the Lord Jesus Christ,
the Son of his love) to give forth unto you.
Can you be exercised in this way while in a drowsy, sluggish, careless spirit?
Do not such things dishonor the Lord, whose name you should honor?
And is not the jealous God provoked and grieved by such things as these,
with whom you should walk in all humility and tenderness of spirit?

I beseech you, therefore, watch against all things of this nature,
and be diligent,
that you may witness the law of the Spirit of life in Christ Jesus making you free,
and fencing you in, against all things of this kind, that you may be a chosen generation,
a royal priesthood, a holy nation, a peculiar people, a temple of living stones,
wherein the living God may dwell, and walk, and sup with you.

There is one thing that yet remains with me,
which I would eagerly have you grow to a true, sensible,
and experiential understanding of, which is this--namely,
what it means to "`touch no unclean thing.`"
The enemy will be stirring up and casting that which is unclean upon
the vessels which God is purifying and preserving from all pollution.
But there is a turning away from and shunning of evil, a forsaking of the vain,
earthly mind and thoughts, and a receiving of such temptations and suggestions no more.
Oh that you might all experientially know and witness what this is!
I know many of you do in some measure, but may there be more of this knowledge,
more of this experience!
Indeed, my heart livingly breathes for myself and for you,
that we may witness this Scripture abundantly fulfilled in our hearts,
"`Whosoever is born of God does not commit sin; for his seed remains in him,
and he cannot sin, because he is born of God.`"
Oh, feel the weight of this scripture!
The Lord has made a new covenant, a living covenant,
and he has prepared a new and living way for the ransomed to walk in without erring,
that he might rectify all (within this new people) that
was amiss in those under the first covenant.

Oh, let the Lord enjoy the design of his heart!
And let his people so wait upon him that they
may all be renewed in the spirit of their minds,
that the Lord may have a generation of Calebs and Joshuas,
who fully follow after him in all things.
For if any draw back from the Lord, and from the holy commandment of life,
the Lord`'s soul can have no pleasure in such.
Oh that there may be none among you drawing back to perdition!
Take heed of deadness, drowsiness, sluggishness of spirit, earthliness, fleshly wisdom,
unbelief, etc.
But grow in faith, with diligence,
towards the saving of your souls (which is far nearer than when you first believed),
which you shall be sure in due time to reap, even the salvation you wait for,
if you do not faint or grow weary.

May the grace, mercy, love, and peace of God our Father,
and of our Lord Jesus Christ, be multiplied unto you,
and fill your hearts from day to day, according to your several capacities,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, 22nd of Third Month, 1671

[.letter-heading]
To Catherine Pordage

[.salutation]
Friend,

I observed yesterday that you did acknowledge the light to be the seed of life,
and that you did affirm that those people with whom you walked also acknowledged it.
Now, it is one thing to acknowledge the seed, and another thing to know it,
feel its guidance, and be subject to it.
It is a good step to acknowledge it in the comprehension, from an external testimony,
but they that go so far may still never come truly to know and own the thing itself.

Oh, many have had some touches of the light,
some true appearances and tastes of the glory.
But who has been so united to the light so as to keep out of all that corrupts?
There is something that still lives near, that would eagerly be mixing with the light,
and drawing the soul higher than the pure light of life and truth.
Oh how this leads out of the way, above the pure, true, innocent, and simple!
How it makes haste to be spiritually rich and glorious,
departing from that poverty of spirit wherein is
the safety and preservation of the soul.

Come now, live no more; know no more of yourself.
Instead, wait to feel the pure seed raised to live and know in you,
and to feel its light enlightening you, and creating a new capacity in you.
This will allow you to bear the pain of dying, and of taking up the cross,
which will truly slay every life, appearance, and power that is not of its own nature.
You have formerly taken up crosses in a way of man`'s wisdom,
and according to a natural knowledge and judgment.
Come now, learn to take up the seed`'s cross in the true foolishness.
For there is not another thing that gives life
besides the cross of our Lord Jesus Christ,
which truly and really slays.
And to whoever can discern and take up this cross, and live and walk under it,
the yoke is easy and the burden is light.
But that which finds the cross hard must first be brought under and destroyed,
before the yoke and burden are known to be light.
If you could come out of your own wisdom and consideration of things,
into the simplicity of the seed, you would soon recover your lost ground again.
And you would also see how the enemy, with his subtlety, has gained upon you,
and into what great danger he has brought your soul.

The Lord searches and tries the heart,
and what his light discovers is the true state of the soul.
The mind outside of the light cannot apprehend its own state.
Therefore, be still; do not justify yourself, nor condemn the judgment of others,
till the Lord makes the thing manifest to you.
If it then proves better with you than what others have said,
that will be to your advantage.
But if you then prove mistaken,
and the judgment of others (which your heart has condemned) should stand,
it will be your great loss and disadvantage.

This is in love and true friendship to your soul,
in a deeper sight and sense of you than you are aware,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
26th Third Month, 1671

[.letter-heading]
To Nathaniel Stonar

[.salutation]
Dear Friend,

There is something on my heart to express to you, in love and great goodwill,
which is as follows:

Would it not be sad if you should perish from the Lord forever?
If you err in heart from the living way, it may be so.
Indeed, if your mind is not turned from darkness, inward darkness,
to the inward light of God`'s Spirit, it cannot be otherwise.
Now, if you feel the inward light, the power of the pure light, and are changed by it,
you cannot speak against that light.

There was no true religion in the apostles`' days
without turning to the inward light,
and the true ministry was then sent to turn men to it.
And there is no true religion now without being
inwardly turned to and walking in the same light,
nor can man try any truth, or understand any scripture rightly,
except in the light of God`'s Spirit.
No one can understand the things of God except the Spirit of God.
The Scriptures are holy words, and deal with the things of God,
which no man can understand except in a light of the same nature from which they came.
And when a man comes to the true understanding,
he quickly finds that the understanding which he had of the
same things before was but an understanding after the flesh,
far short of the nature of the true understanding.
And friend, consider if your knowledge, which you have hitherto had,
has changed or does change the nature of your understanding and will.
Or is your old understanding and will yet remaining,
despite all your knowledge and practices in religion?
Oh, do not dally in things of such great importance, lest you repent too late!
For I do not tell you what I see concerning you in the light of God`'s eternal Spirit,
but rather desire that your own eye, or rather the right eye in you,
be opened and brought to see.

Now consider one scripture seriously concerning the church of Laodicea.
Did not this church have the true knowledge outwardly, and a true church state,
and right ordinances?
Did it not believe in Christ, and look up to him for justification,
etc.? What did it lack as to the outwardness of its state?
But it lacked true sense, life, and warmth, inwardly.
So that, if you had all ordinances and truths of the gospel light outwardly,
yet lacked the inward power, you could not help but lack the tried gold,
the white raiment, and eye salve.
And so, even though you might think yourselves rich, etc.,
yet the shame of your nakedness would appear: Yes, indeed,
the nakedness of such as are not clothed with
God`'s Spirit does clearly appear to the Lord,
and also to the eyes and spirits of his children which he opens in his own light,
and who see with this eye.
Truly the shame of their nakedness does appear,
notwithstanding all the religious covers they put upon themselves.
Oh that you had desires, living desires, after the nature of truth,
and were acquainted with the new nature,
which can be satisfied with nothing but the virtue, life, and power of truth!

Come friend; wait on the Lord to have the old nature, the old spirit, mind,
wisdom, understanding, and will broken, and the old garment torn to pieces.
Only then will you come to experience that which is new, pure, and living,
and find the new vessel filled with that which is new.
For if you will come into the ministration of the new covenant,
you must come into the Spirit and power.
You must know the letter of the Scriptures in the Spirit and power which wrote them,
if ever you will know them aright.
Yes, if you will become a son of God, you must receive power from Christ so to do;
and if you will believe aright,
you must feel faith wrought in your heart by that very
power which raised our Lord Jesus Christ from the dead.
All other faith falls short of the nature of true faith.

Now consider:
the apostle speaks of the state of the Gentiles
before they were turned from darkness to light,
and from the power of Satan to God.
Their understanding was darkened,
being alienated from the life of God through the ignorance that was in them,
because of the hardness of their heart.
Even though what might be known of God was manifest in them, Rom. 1:19,
their ignorance remained because of their hardness in not minding it, not turning to it,
and so they became alienated from the life, and their understanding was not opened by it.
In this state, men are without God, without Christ, strangers to the covenant of promise,
and without any true hope of salvation.
And in this same state are those who have a form of godliness without the power;
they are even as the natural heathen.
For nothing makes a true Christian besides the life and power;
and he that does not hear the voice of Christ`'s Spirit
in his heart is no better than a heathen and a publican.
Yes, any church built up outside of the life and
power is no better than a synagogue of Satan.

It is precious indeed to know the Spirit of the living God,
and to be begotten by him in the life which is true and pure.
It is precious to be separated from death and its power,
and to be married to life and its power--to be married to the conquering Lamb,
who triumphed over sin and death in his body of flesh, and who, by his Spirit and power,
delivers his spouse from the strength and dominion of them.
And it is precious to walk with the Lamb, and to follow the Lamb wherever he goes.
For he always leads out of sin and unrighteousness,
into ways of purity and righteousness, into the path which is prepared for the ransomed,
where there is no danger of erring.

God does not strip his people naked,
and gather them out of the spirit of this world,
that they should be empty and desolate forever.
No, he gathers them into, and fills them with, his own Spirit!
He fills them with light, fills them with life, fills them with holiness,
fills them with righteousness,
fills them with peace and joy in believing and obeying the gospel!
And in this Spirit is the kingdom known which is not of this world, the inward kingdom,
the spiritual kingdom, the everlasting kingdom, where the everlasting throne is near,
and the everlasting power is revealed.
The Lord God Omnipotent reigns in the hearts of his, and other lords do not reign,
but their horns are broken, and the horn of God`'s Anointed is exalted,
who sits ruling as King on his holy hill of Zion.
Truly those who have suffered with him, and gone through great tribulation,
do reign with him.
Blessed be his name forever!

I am your friend in the heartiness of true love,
so far as the Lord pleases to make use of me towards you,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
7th Fourth Month, 1671

[.letter-heading]
To Nathaniel Stonar

[.salutation]
O Friend!

It is a dangerous thing to resist God`'s Spirit;
and yet it is very easy for man to do so,
who has not received a true understanding from the Lord,
nor is acquainted with the leadings and outgoings of him who is pure.
He that is tender and truly sensible may discern when he resists, when he quenches,
or when he grieves the Spirit of the Lord; but he that is not truly enlightened,
nor in the true sense, cannot do so.

The Scribes and Pharisees were interpreters of the law,
and very strict in outward observations and ordinances, etc.,
and blamed their fathers for killing the prophets, yet, concerning these, Stephen said,
"`You stiff-necked, and uncircumcised in heart and ears,
you do also resist the Holy Spirit; as your fathers did, so do you.`"
For until the stiff will and stiff wisdom be brought down in a man,
he cannot help but resist God`'s Spirit, and fight for his notions and practices,
according to his apprehensions of the letter.

Paul walked blamelessly according to the letter of the law,
yet resisted the Spirit which gave forth the law.
He who would not be found resisting God`'s Spirit must know the Spirit,
receive the Spirit, live in the Spirit, walk in the Spirit,
and not fulfill the lusts of the flesh.
But he that is only in the letter,
and in the form of godliness outside of the inward life and power, he is of that birth,
mind, nature, and spirit, which cannot do otherwise than resist God`'s Spirit.
He does not know, and cannot heed, the Spirit`'s drawings, movings, light,
and life--either in his own heart, or in the hearts of others.

Oh, wait to receive an understanding from the Lord,
that you may come truly to know whether you have resisted God`'
s Spirit or no--that you do not lose the opportunity of making
peace with your adversary while you are in the way with him.

This, in very dear, true, and tender love,
from one who most sincerely and heartily wishes well to you,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
17th Fifth Month, 1671

[.letter-heading]
To Catharine Pordage

[.salutation]
Friend,

It is true, the way to life is so difficult and intricate that none can find it,
except those who are enlightened by the Lord, and who follow the guidance of his Spirit.
Christ, who preached the kingdom, and bid men seek it, yet said,
"`Narrow is the gate and difficult is the way which leads unto life,
and few there are that find it.`"
In a race many run, but one obtains the prize.
Are you able to read what Christ said, "`Except you eat the flesh of the Son of man,
and drink his blood,
you have no life in you`"? This seemed a hard saying to some of his own disciples,
many of whom left him.
And truly, friend, as it is not an easy thing to come into the right way,
so neither is it an easy thing to abide in the way, for many are the bypaths,
many and great the temptations, both on the right hand and on the left.
The way was always the same, surely as difficult and hard formerly as it is now.
But the states and conditions of some make it harder to them than it is to others.

It is sad indeed that any should be convinced
of truth and not come into subjection to it;
yet it is very easy and common.
For men cannot deny conviction when it comes in power,
but they may deny obedience to that of which they are convinced.
Some in the apostles`' day went further, even to taste of the heavenly gift,
and the powers of the world to come, and to partake of the Holy Spirit,
and yet fell away.
Was this not very sad?
And yet sadness was not a well-grounded objection against the truth and way of God then.
Indeed, I make little of the illumination of the understanding,
without subjection to him that illuminates.

As for prayer, it is a gift.
He that receives it must first come to the sense of his own inability,
and so wait to receive it,
perhaps beginning with but a groan or sigh from the true Spirit,
and thus grow in ability from the same Spirit,
denying the ability which is after the flesh.
This fleshly ability abounds in many, who mistake and err in judgment,
not waiting on the Lord to be enabled by him rightly to
judge and distinguish between flesh and Spirit.
Many times men are willingly ignorant in this particular,
and it will cost them dear to come to a true understanding therein.

Has not all flesh had some manifestation of God`'s Spirit allotted to it?
And is not God`'s light, God`'s gift, God`'s Spirit, the rule to all?
Is any prayer required or accepted outside of this?
Indeed, he that has the sense of being but a dog, as I may say,
and not worthy to be counted a child, yet he may pray for crumbs, and be heard,
and receive them.
But what are prayers without the light and life of God`'s Spirit?
Are they not prayers of the fleshly birth, fleshly will, fleshly wisdom?
Can they that are in the flesh, or who pray in the flesh, please God?
Oh, forsake your own wisdom, reasonings, will, and desires,
that you may come to true understanding in this matter.
A little praying from God`'s Spirit, and in that which is true and pure,
is better than thousands of vehement desires in one`'s own will, and after the flesh.
For as long as a man pray in the flesh,
that which should die in him still lives in his very prayers.
And how shall it ever be destroyed, if it gets food and gains strength there?

As to "`stirring up the gift,`" 2 Tim. 1:6, Paul knew to whom he wrote.
Timothy had a great understanding, and both knew the gift, and how to stir it up.
But he that does not have a true understanding may stir up something else,
instead of stirring up the gift, and so kindle a fire of his own,
and offer up his own sacrifice with his own fire,
neither of which are acceptable to the Lord.

As for Christ being a mediator and reconciler, it is by his death and life,
both of which are partaken of in the light which comes from him,
even in the grace and truth which he dispenses.
For as God wrought all in him by the fullness which he bestowed on him,
so he works all in those that are his by a measure of the same Spirit, life, and power.
But why do you so desire to be able to comprehend and reason about these things?
This is not your present concern, but rather to feel after, and be joined to,
that whereby Christ renews and changes the mind,
and wherein he gives the knowledge of his good, acceptable, and perfect will.
Take heed of being exalted above measure,
or desiring to know the things of the kingdom after the flesh.
It is better to lie low, and as a child to enter the kingdom,
and to receive the knowledge of the things of God there,
than to be feeding that knowing mind, which is to be kept out and famished.

Oh watch, that you may not lose your Leader, and meet with the deceiver,
instead of him that is true.
Take care that you do not go back from light, life, truth, and power,
instead of going forward toward them.
Indeed, this letter of yours makes me afraid, as Paul speaks to the Galatians,
lest I have bestowed labor on you in vain.
For there seems to be in you a strengthening of your mind towards returning
back to that from which the Lord has been redeeming and gathering you.
If you feel the right seed, and come to be of the right seed,
the way of the seed will not be too hard for you; otherwise it will.

This is to you, in love and grief, from your soul`'s true friend,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
21st Sixth Month, 1671

[.letter-heading]
To Catharine Pordage and Another

[.salutation]
Friends,

If I should say one word to you, could you bear it?
And yet this counsel is with me towards you: Oh wait for, receive, embrace,
and be glad of that which reproves you,
and be afraid of that which comforts you in your present state!
For you must come through the trouble, judgment, breaking down, plucking up, consuming,
and burning of the contrary nature and spirit which yet deceives you.
And truly, you must witness all the knowledge, profession, practices, beliefs, hopes,
that are founded there, and spring up from there, confounded and destroyed,
before you can possibly come into the true ministration of life and power.
You must die to your own wisdom if ever you will be born of, and walk in,
the wisdom of God.
Yes, you must die to that part which is so active in the wisdom of man,
and which would even labor in fire for that which is but vanity,
if ever you will receive the knowledge which springs out of truth and life itself,
which indeed flows over and covers the earth of
God`'s heritage as the waters cover the sea.

When we were in desolation and great distress, indeed, unutterable,
we had none of these helps and instructions which now abound towards you.
Oh, what a day of mercy you have met with!
But how great will be your condemnation if you
become as deaf adders to the Spirit of the Lord,
and so miss his salvation!
And if you will ever know the Spirit of the Lord,
you must meet with him as a searcher and reprover in your own hearts.
Yes, you must first meet with the merciful God as a severe Judge, and an unquenchable,
consuming fire against that spirit, wisdom, knowledge, and faith in you,
which is but of a chaffy nature.
Truly, friends, it is far better to be stripped of it,
than to find any rest or pleasure in it.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
7th Seventh Month, 1671

[.letter-heading]
To an Unknown Recipient

[.salutation]
Dear Friend,

Some Scriptures sprang up and opened in my heart towards you this morning.
The first was 2 Cor. 10:4-6:

[quote.scripture]
____
For the weapons of our warfare are not carnal
but mighty in God for pulling down strongholds,
casting down arguments and every high thing that
exalts itself against the knowledge of God,
bringing every thought into captivity to the obedience of Christ,
and being ready to punish all disobedience when your obedience is fulfilled.
____

That which was chiefly on my heart was about the fulfilling of obedience.
First, there is a knowing the will of God,
a waiting to know and understand from God what is his holy, good, perfect,
and acceptable will.
Then, as God gives the knowledge, he requires obedience,
which is to be learned of God in the new spirit and life.
For in the old nature, mind, and spirit, there is nothing but darkness and disobedience;
and in the new creation there is the new obedience.
So that there is first a beginning of knowledge in the Spirit,
a beginning of faith in the renewing power,
and a beginning of obedience (in the same) to him that calls.
Then there is an increase of knowledge, of true, pure, living knowledge,
an increase of faith, and a growing more and more obedient under the exercises,
judgments, and chastisements of the Father`'s Spirit.
And at length, the soul comes to witness a full readiness, skill,
and strength (in and through Christ,
in and through the measure of the gift of grace received from him),
to obey in all things.
When the new birth is thus grown up into strength and dominion,
into the stature of a man in Christ, then the senses,
which have been long exercised in discerning between good and evil, grow strong,
and there is a quick discerning in the fear of the Lord,
and an authority in his name and power over the enemy and his temptations.
Here every stronghold is broken down,
every imagination and false reasoning concerning the truth is
subjected and broken by the evidence and power of truth,
every thought is brought under into captivity, even to the obedience of Christ,
with a readiness to reject all unbelief and
disobedience that so much as offer to rise up.
Now, is not this the Christian state, which God would have his children aim and strive at?
Are they not blessed who witness it?
Does not the true ministration of the gospel light, Spirit, and power lead to it?
And should any be at rest in their spirits in an easeful, formal, dry,
dead profession without it?

Another Scripture was 1 Pet. 2:2-5:

[quote.scripture]
____
As newborn babes, desire the pure milk of the word, that you may grow thereby,
if indeed you have tasted that the Lord is gracious.
Coming to him as to a living stone, rejected indeed by men,
but chosen by God and precious, you also, as living stones,
are being built up a spiritual house, a holy priesthood,
to offer up spiritual sacrifices acceptable to God through Jesus Christ.
____

It is precious to witness the state of a newborn babe,
to be begotten to God by the word of life and power,
even by the word which God ingrafts into the heart.
Oh, what living desires rise up after that which nourishes the birth of life,
which God breathes from his own Spirit!
Now as the birth is pure,
so the nourishment is pure--pure milk from the pure word--sincere,
unmixed milk from the word of life, from the breast of life.

Now, who is it that begets to God?
It is the Spirit, the Word, the second Adam, he whose name is the Word of God.
Who is the mother of these children?
It is the heavenly wisdom, the Jerusalem which is above.
("`The Jerusalem which is above is free,
which is the mother of us all;`" "`Wisdom is justified
of her children.`") And who feeds these children?
Who nourishes and brings them up?
Why, the mother who bore them, she holds forth the breast of life to them,
she yields to them the pure milk of the word.
The newborn babes, they long for it, they cry for their food,
they earnestly desire after it,
and the tender mother gives it forth to them--even the
milk of the breast of life from the pure word of life,
and by this they grow.

But how came the babes to desire after such pure, sincere, unmixed food?
Oh, they have "`tasted that the Lord is gracious!`"
They have had the heavenly taste,
they have tasted that which was living and pure from God,
from his tender mercy and grace, wherein he ministers life and salvation.
Indeed, the remembrance and sense of the sweetness of this is upon their palates!
And how precious and living is it, when it comes new and fresh from him!
The words which he speaks, they are still spirit and life to the soul.
How can they help but desire that he minister unto them the pure food,
that they may know and feed on the truth as it is in Jesus?
Here they come to him as unto a living fountain, and a living stone,
rejected by the builders after the flesh in all ages and generations, but chosen of God,
and precious to all that have the true sense and understanding.
Thus they come to him daily, and so are built up into a living house,
or spiritual temple and dwelling place for God.
He is the foundation stone, the corner stone, the top stone,
the hope and crown of their glory.
They are the living stones in him, quickened and kept alive in and by him,
and shining in his light and glory.

Oh,
little do you know the loving kindness of the Lord in visiting you with his truth,
in giving you a sense beyond others, and in so tenderly drawing and inviting your heart!
Nor have you yet seen what this will come to, if you faithfully give up, hearken to,
and follow him.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
20th Tenth Month, 1671

[.letter-heading]
To Thomas and Ann Mudd

[.salutation]
Dear Friends,

Of whose love to me I have been and am sensible, and to whom I bear true love.

When I was last at Rickmansworth, it was on my heart to visit you,
and while I was there with you,
true and living breathings did spring up in my heart to the Lord for you.
Since then, I have often thought of you,
and in my desires have wished well concerning you, even as to my own soul.

Your days here cannot be long,
and what you sow here you must reap when you go out of this world.
Oh that you may now sow to the Spirit of God in such a
way that you may then reap from him life everlasting!

Last first day, my wife had a letter of George Fox`'s sent to her,
which I read that night.
In the reading of it, I had many thoughts respecting you,
and a desire that you might sincerely, uprightly, and without prejudice, peruse it,
and so I sent it unto you the next day for that end.
Now, this morning you were upon my heart,
and two things rose up in me in reference to you, as very necessary for you,
that you may be safe, and that it may go well with you forever.

One was, that you keep steadfast in that holy testimony of truth,
which was given forth among us at the beginning.
For this truth is the same, and the testimony of it does not vary or pass away,
but shall last throughout ages and generations, to redeem all that receive it,
and are faithful to it.
The testimony was this: to draw away from outward, dead knowledge,
and out of dead practices and worships after men`'s own conceivings, into an inward seed,
and into worship in Spirit and truth, both inwardly in the heart,
and outwardly in the assemblies of God`'s gathering.

The second was, that you be daily exercised, guided,
and your hearts opened and quickened, by the seed and Spirit of truth,
so that you may know what it is to walk with the Lord, and to feel the power of the Lord,
and enjoy the presence of the Lord, and be led by him out of, and away from,
the mysterious workings of the power and spirit of inward darkness.
For if, through a grievous mistake, you let this into your minds and spirits,
instead of the Spirit of truth, you cannot help but call darkness light,
and light darkness, truth error, and error truth,
and so you will err from the true way and fall into something which, in God`'s sight,
is not so.
For there is a spirit of delusion as well as a spirit of truth.
This spirit of delusion works in the heart as a minister of righteousness,
in a seeming light, warming the heart with a wrong fire,
bringing it into a wrong bed of rest.
It administers to the heart a wrong peace, hope, and joy, setting up there a wrong sense,
belief, and judgment concerning itself and others.
And so it leads to separate from them that are true, and be joined to them that are false.
It draws from the assemblies and worship of God`'s true gathering,
and begets prejudices against, and hard thoughts about, those who are owned by the Lord,
and are kept in their habitation by him who dwells in them, and they in him.

O my friends, may the Lord give you the true discerning of this spirit,
and of his own Spirit!
And may he deliver you out of the snare of the enemy by opening that
eye in you to which he gives the sight of what is of him,
and what is not of him.
And may you be disjoined from all that is not of God, and joined to the Lord,
abiding and walking in him.

I am a true friend to you both (in true and faithful love, as in God`'s sight),
and a hearty desirer of your everlasting happiness,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
19th Twelfth Month, 1672

[.letter-heading]
To Colonel Kenrick

[.salutation]
Dear Friend,

The gospel dispensation consists in Spirit and power.
The kingdom which Christ and his apostles preached--
which the true believers were to receive,
and to wait for an entrance to be ministered to them into--stood not in word,
but in power.
Now there are four sorts of professors of the Christian religion in this our day,
of which only one sort are truly acquainted with the gospel dispensation.

First,
there is one sort who have been nurtured in a profession of Christianity by education,
and have improved it by study, but have never known the power, virtue, and inward life.
But as men, with the man`'s part, wisdom, understanding, and seriousness of mind,
they have considered the truth and weight of things contained in the Scriptures,
and so they have received something of the holy
doctrine into their natural understanding,
and given themselves up to the observation and practice thereof,
according as they have apprehended and understood things.
These have become more serious and excellent men than others,
but still fall very short of the nature and state of Christianity.
Yes, the strictest among these, many times,
become the greatest opposers and persecutors of true Christianity.

Secondly, there are some who have had a taste of the true power,
and have had living desires and breathings after it,
and a sense of the preciousness and excellency of it,
who have also felt the quickening Spirit, and begun therein.
But afterwards, they have lost that sense,
and landed in a literal knowledge and wisdom about those very
things of which they once had some living experience.
These are like salt which has lost its savor,
and it is hard for them ever to be seasoned again.
And from among these do rise the greatest persecutors
and bitterest persecution against the life,
truth, and power.

Thirdly, there are some who,
though they never came to the distinct knowledge of the power,
yet have had a great sense of their lack of it, and have abode in that sense.
And in all the ways and forms of religion they have been, or are in,
they still seek after it, and find no value in outward forms,
except as the power (in some measure) appears in it.
For the cry of their souls is daily after the power and life, and their waiting is for it.
These, wherever they are, are of the true seed.
These are of the birth of the heavenly Spirit and wisdom.
These are sheep of the true Shepherd`'s fold,
though they are not yet gathered home to the fold to which they properly belong.
These are the broken, the bruised, the sick, the wounded, the captives, the distressed,
the poor, the naked, etc., to whom the gospel of peace, the gathering, the salvation,
and redemption belongs.
And the bleating of these sheep is known.
Yes, their longing and cry after the redeeming and gathering power of the Shepherd is felt,
though they may be, at present, prejudiced against that very dispensation of truth, life,
and power, whereby the Shepherd gathers.

Fourthly,
there are some whom God has brought to the distinct sense and knowledge of the power.
There are some whose minds God has turned to the inward light and power.
There are some whom the Shepherd has gathered home to the Father`'s house,
where there is bread enough, and to the true fold, where there is rest and peace enough.
These have seen to the end of man`'s legal
comprehendings and creaturely strivings after life,
righteousness, and holiness,
and at last have come to the commandment wherein is life everlasting.
Now these indeed experience something of the gospel dispensation,
and know the difference between being under the law and under grace.
These can tell what the kingdom is which Christ preached and bade men seek,
and what the gospel is which the poor in spirit receive,
and what the healing is which drops from under the wing of the Savior and Redeemer.
And these can distinguish between truth as testified in the letter,
and truth as it is in Jesus; between the law of the letter, and the law of the Spirit,
which is written in the new heart and mind, by the finger of God`'s pure and living power.

Now the knowledge of these, the faith of these, the peace, the joy,
the justification, and sanctification, and redemption of these,
differs greatly from all the former--from the two first sorts in nature and kind,
from the latter in degree, clearness, and purity.
For though all the sheep of the true Shepherd have something of the true knowledge,
true faith, true justification, true sanctification,
and may at times have some taste of true peace and joy,
and have true breathings and supplications in their
spirits towards their Father that begat them,
still they are not clear, they are not pure, they are not unmixed.
There is a great deal which is not true,
which passes for true with them because they are not come to the anointing,
to the eye salve which opens the eye, nor to the Spirit of judgment and burning,
which separates inwardly in the heart, understanding, mind, and judgment,
between the precious and the vile.
So that when they speak of the heavenly things, they do but stutter and stammer.
And even though truth can sometimes acknowledge their sense (yet,
many times not their words), there is such a mixture of the dark,
earthly comprehension in them, which they are not yet delivered and redeemed from.

But it is otherwise with those who are turned
to the light and power of our Lord Jesus Christ,
and have known it, and been exercised, fanned, and purged by it.
For in these, the blind eye is opened and the deaf ear is unstopped.
And to them,
the pure understanding and language is given whereby they know and understand,
not only words concerning him, but he himself who is true,
and they are in him that is true, even in him who is the very God and life eternal.

Yet there are different states among those who
are thus effectually called and gathered home,
according to their growth in the truth, and their faithfulness to it.
For if there is not a great care and watchfulness, there may be, in some,
a neglecting to hear the voice of the Shepherd, and to walk with him.
These can miss the pastures of life, and the pure rest, joy, and peace,
and the garment or covering of the Spirit,
which they who live and walk in the Spirit (giving up in everything to the Spirit,
and denying all the lusts and fruits of the flesh) daily find themselves covered with.
God does not "`dwell in them and walk in them,`" as he does in
those that remain separate from all evil (from which the
Spirit of judgment and burning purifies and separates),
and touch no unclean thing.
Yes, they who grieve Christ`'s Spirit, and do not heed his call and knocks,
do not partake of the river of life and wine of the
kingdom as fully as those whose ear is open to him,
and who are always ready to obey and follow him "`wheresoever he goes.`"

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
19th Fourth Month, 1673

[.letter-heading]
To Widow Hemmings

[.salutation]
Dear Friend,

I think it long since I heard from you.
I remember the sweet and precious savor that was
upon your spirit the last time I was with you,
with my dear friend, J.C.
It has been my hope and desire that the Lord might preserve you therein.

The truth in the inward parts is of God.
That is the thing which all are to mind, and in which acceptance with God is witnessed.
Without the truth in the inward parts, there is no acceptance with God,
let men profess what they will or can.
For God never disowned the truth, nor any that are in it.
Here, the flesh and blood which give life are fed upon.
Here, the bread which comes down from heaven and the water of life are known.
But outside of this they are not, nor can they be, known.

Oh my friend, that you might feel more and more truth in the inward parts,
and be more and more established therein!
What is the outward feeding, or outward supper?
It is but a shadow.
The inward feeding, or the inward supper, is the substance.
And as the day dawns, and the daystar arises in your heart, the shadows will flee away,
and the substance will be discovered, owned, and delighted in by you.
The shadows reach but to the outward part, but the ministration of life,
the ministration of the substance, reaches to the seed.
And you must be more and more transplanted into the seed,
that Christ may be formed in you, and you formed in him,
and so grow up into his heavenly nature and image, out of the earthly,
out of the natural.
Oh, may the Lord God prosper his own seed and holy plantation in your heart!
And may he keep you in the meek, lowly, humble, poor, and tender spirit,
unto which is his mercy and blessing.

I expected to have heard from you, or at least from your daughter S.,
before this time, supposing I had a promise thereof from her.
The Lord uphold, preserve, and bless her.
Let her look not out, but only look within, for the will of the Lord;
may she mind nothing else; and it will be well with her.

My dear love is both to you and her, who am your sincere friend,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
4th Ninth Month, 1673

[.letter-heading]
To an Unknown Recipient

[.salutation]
Dear Friend,

I had a desire to have stayed a little while
with you the last time I passed through Uxbridge,
but was prevented.
The occasion of my writing to you is something which was on my heart toward you.

Do you desire to know the Lord in the gospel covenant,
and would you walk with him therein?
I know you would.
Do you desire to have sin destroyed in you, and Christ reign in your heart?
Do you desire to fight against your enemies so as to overcome,
and to run the race so as to obtain the everlasting prize, the eternal weight of glory?
Oh then, mind truth in the inward parts,
even the grace and truth which are by Jesus Christ to whom God has given power!
For he gives power to his own, by the grace of his Holy Spirit,
over sin and corruption in the inward parts.
Did not God conquer the enemies of the outward Jews in Egypt, in the wilderness,
and in the good land also?
And shall he not do so inwardly for the inward Jews?

Truly, there are enemies in Egypt,
in the land that is (as I may say) wholly dark,
and under the oppression of spiritual Pharaoh.
There are enemies also in the heart which is like a wilderness and solitary place.
And there are enemies also in that heart which is in some measure renewed,
and made good and honest.
Now all the spiritual enemies, all the enemies of a man`'s own house,
are to be destroyed by the power of the Lord
Jesus Christ working by his grace in the heart.
This grace, being received, subjected to, dwelt in, and obeyed,
brings deliverance and salvation from them all.
And when salvation is brought home to the heart, and wrought out there by the Lord,
it is to be enjoyed and abode in,
and the soul is not to return back again into captivity.
Indeed,
having been delivered out of the hands of its inward and spiritual enemies by the holy,
inward, and spiritual covenant,
the soul is to serve God in the dominion of his Son`'s life,
in holiness and righteousness all its days here upon the earth.

O my friend, mind this precious truth inwardly, this precious grace inwardly,
the precious life inwardly, the precious light inwardly, the precious power inwardly,
the inward word of life, the inward voice of the Shepherd in the heart, the inward seed,
the inward salt, the inward leaven, the inward pearl, etc.,
whereby Christ effects his work.
Distinguish between mere words concerning a thing, and the thing itself within.
Then wait and labor to know, understand, and be guided by the motives, leadings,
drawings, teachings, quickenings, etc., of the thing itself within.
And take heed of being offended by anything either within or without.
For offenses will come,
but blessed was he that was not offended at Christ outwardly in the days of his flesh;
and blessed is he that is not offended at his inward truth,
and inward way of appearance in the day of his Spirit.

O my friend, how precious is the substance, beyond all words or testimonies!
Oh that you may come to know it in yourself,
and be sensible of God`'s ministering by it to you, and increasing it in you!
Then you will experientially feel the seed in you, and find it growing more and more,
till it come to be a tree.
And then you will sit under its shadow, and be delighted with its defense,
and partake of its sap and fruit.
Oh that every day you might have a sense of the life itself, the truth itself,
the power itself, the wisdom itself, the righteousness itself!
And may you find the Lord Jesus Christ both unclothing and clothing you inwardly,
sensibly, and experientially--that is, that you might find him taking away your sin,
your iniquities, your unrighteousness, both within and without also, and filling you,
and clothing you with his righteousness.
Then, by his putting these on you, and forming them in you,
you might find your heart filled and covered with the nature, image,
and Spirit of the dear Son.
And so you may indeed put off the old man with his nature and deeds,
and put on the new man, and know the renewing and new-creating in Christ Jesus,
in the spirit of your mind.
And then you will have a certain understanding of the truth as it is in Jesus,
and as he manifests it, gives power to it, and causes it to work in your heart.
This is the desire of my soul for you.
May the Lord guide you to it, and remove all obstacles and hindrances out of your way.

My dear and true love is to your husband.
May the Lord manifest his pure and living truth in both your hearts,
and gather both your minds to it, and make you one in it.

Your friend in truth, who heartily wishes well to your soul,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Grove Place, 17th of Ninth Month, 1673

[.letter-heading]
To Elizabeth Stonar

[.salutation]
Dear Friend,

Whose life in the Lord, and prosperity in the truth, my heart greatly desires,
even that you may come to the perfect service,
and free and full enjoyment of your soul`'s Beloved.
And truly, if I could be in any way helpful to you in this,
my heart would greatly rejoice and bless the Lord.

This morning when I awoke, my heart was exercised before the Lord concerning you.
Several things did spring up in my mind relating to you, which I may now signify to you,
as the Lord shall please to bring them again to my mind,
and open them in my heart in reference to you.
I greatly desire to have you rightly understand, and be found doing,
that which the Lord requires of you, that it may go well with you,
and that your heart may be satisfied, and your soul blessed,
in believing and obeying the truth as it is in Jesus.

A few scriptures, sweet and precious to my taste,
sprang up in my heart to lay before your view, that you also might suck sweetness,
and reap benefit through the living sense of them.
The first scripture that sprang up in me to you was that of Rom. 12:2,
"`be not conformed to this world, but be transformed by the renewing of your mind,
that you may prove that good, that acceptable and perfect will of God.`"
You must stand at a distance from the spirit of this world,
you must not touch the unclean thing, but be a chaste virgin in heart, in word,
in conduct, if you expect to be married to the Lamb, to become one spirit with him,
to know his mind, and to enjoy the love and be the delight of his Father.

The next was Samson`'s riddle from Judges 14:14.
"`Out of the eater came forth meat, and out of the strong came forth sweetness.`"
It is everlastingly true, both inwardly and outwardly, to the children of the Most High,
who live in his Spirit, and walk in his Spirit,
and are guided by the power and virtue of his life.
For everything that seeks to devour and destroy them,
the Lord destroys by the power and virtue of his life and Spirit springing up in them.
And truly, out of that which is strong against them,
which roars against them in the strength and power of darkness,
the Lord brings forth sweetness in and to their spirits.

Then that of Luke 9:23-24 came before me: "`If any man will come after me,
let him deny himself, and take up his cross daily, and follow me.
For whosoever will save his life shall lose it;
but whosoever will lose his life for my sake, the same shall save it.`"
Now, I beseech you, consider: do you take up the daily cross,
and bear it faithfully for Christ`'s sake?
Do you stand a faithful witness against the spirit of darkness, and works of darkness,
where you live?
Do you not comply with any worship there which your
heart knows to be out of the truth and Spirit of life,
in which all true, holy, living, spiritual worship can alone be performed?
Oh take heed of shunning the cross in any respect!
For then you give way to unbelief, and to that wisdom, thought, reasoning,
and judgment which are not of the truth, but rather of the flesh.
And then you shun that which God has appointed to crucify sin in the heart,
and under which the seed is to spring up and live,
which is the power of God unto salvation to all that abide under it and daily bear it.

Thus, my dear friend, in the most dear, tender,
and true love have I opened my heart to you, as things sprang in me for your sake.
And the desire of my soul to the Lord is that they may be serviceable to you,
and that you may be led by the holy, leading Spirit more and more into truth,
and live in truth, and feel the life of truth living and reigning in you.
Oh that you would be delivered from the enemy`'s temptations,
and the subtle twistings of the serpent,
which your present condition will often meet with.
May the Lord discover them to you, and preserve you from being ensnared with them.

Your constant friend in love and truth,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Amersham, Bury End, 20th of First Month, 1675

[.letter-heading]
To Catharine Pordage^
footnote:[Being that this letter to Catherine Pordage
is something of a strong correction and warning,
it seems appropriate to insert here a few words of John Penington,
Isaac`'s Penington`'s eldest son, written upon the occasion of his father`'s death.
He writes, "`I have also observed, where he +++[+++Isaac Penington+++]+++
has been engaged on truth`'s behalf to rebuke anyone sharply,
who were declining from their first love, and deviating from the truth as it is in Jesus,
it has been with so much reluctancy and averseness to his natural temper,
as I never discerned the like in any.
So that it may be safely said, he never used the rod,
except with great compassion to reclaim.
Truly it was in love that he was drawn to smite what
the purest love could not allow to go unrebuked.`"]

[.salutation]
Ah, my poor, distressed, entangled Friend,

While you seek to avoid the snare, you deeply run into it!
For you are feeding on the tree of knowledge by giving way to these thoughts,
reasonings and suggestions which keep you from obedience to that
which has already been made manifest to your understanding.
And it is no wonder you are feeble in your mind,
while you are thus separated from him who is your strength,
and while you let in his enemy.
Why should you not act, so far as God has given you light?
Why should you not appear willing to obey him, even in little things,
so far as he has given you light?
What if I should say that all this reasoning is but the
subtlety of the serpent`'s wisdom to avoid the cross,
and is not that simplicity and plainness of heart towards God which you take it to be?
What if you are unwilling to be so poor, and low, and small in the eyes of others,
as this practice would make you appear?

And what a subtle device the enemy has put into your mind about prayer,
which has no weight or truth in it as applied to this present case!
For prayer is the breath of life, an effect of God`'s spiritual breathing,
which no man can perform aright without the Spirit`'s breathing upon him.
Therefore, the Spirit is to be waited upon for his breathings and holy fire,
so that the sacrifice may be living, and acceptable to the living God.
But the prayer you mention is mere language,
as any man or woman uses in ordinary conversation,
and does not require a motion of life to bring it forth,
no more than to bring forth other words.
And will you say that you truly long for and pant after the Lord,
and the way of truth and righteousness,
while you remain walking against the light which God has given you?

O my friend, you and your husband have dallied too long.
The Lord has shown great love and mercy towards you.
Take heed of dallying any longer.
What more would you have the Lord do?
How far has he worked towards bringing you into obedience in this thing!
But you say you find an inability to abide therein.
Do you abide in the faith where the strength is given,
and out of the thoughts and consultations of the enemy?
Oh take heed of murmuring against the Lord (as you have been too apt to do)!
Consider rather what great matter of complaint the Lord has against you.
What could he have done more for you, than he has already done?
And have you not been turning aside from his convictions and drawings,
into your own thoughts and reasonings?

I received your letter last night,
and upon the reading of it was greatly burdened and grieved for your sake,
feeling your spirit so exceedingly wrong in this matter,
and your reasoning so crooked and provoking to the Lord.
But this morning, my heart was opened and drawn forth in this manner to you.
And now,
may the Lord give you a present and a future sight of the
enemy`'s working in this against the love of God towards you,
and against the redemption and peace of your soul.
My heart breathes to the Lord for you,
and desires that he may manifest to you that nature, wisdom, and spirit,
from which these things arise.
Oh that the child may not always be stuck in the birth,
but at length be brought forth into the light, into the life,
into the faith which gives victory, and into the single-hearted and holy obedience,
where the pure power is known.

Your friend in the truth, and in sincere love,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Amersham, 25th of Ninth Month, 1675

[.letter-heading]
To His Brother Arthur^
footnote:[Arthur Penington, Isaac Penington`'s younger brother,
was a Roman Catholic priest.]

[.salutation]
Dear Brother,

I have been a traveler after the Lord from my childhood,
and great misery have I undergone because of my longing after him.
That which I lacked was his Spirit, life, virtue,
and redeeming power to be revealed in my heart.
And oh, blessed be the Lord, beyond my expectation,
he has directed me where to wait for this within, and has revealed it in me!
And now I can say in truth of heart,
and in the sense of that birth which God has begotten in me, "`Lo,
this is my God whom I wanted, and for whom I so waited!`"
And indeed I find him stronger in my heart than the strong man,
who possessed it before he cast him out from there, and made a spoil of his goods.
And now, dear brother, how can I hold my peace, and not testify of the love, mercy,
and goodwill of the Lord towards me,
and invite others to the redeeming power of which the Lord, in his goodness,
has made me a partaker?
Now, brother,
a few words with respect to your response to what I sent you--not for contention`'s
sake (the Lord knows my dwelling is in that life and peace which shuts that out),
but in the tender love and care of my heart concerning the eternal welfare of your soul,
which I would not, by any means or device of the enemy, have eternally deceived.

All sides may agree in notions about the regenerating power,
but all do not receive the regenerating power,
or are truly regenerated in the sight of God.
Nor do all come to witness the head of the serpent inwardly crushed,
and his works destroyed, and his kingdom laid waste inwardly by this power,
which must be witnessed before a man is translated out of the kingdom of darkness,
into the kingdom of the dear Son.
There is an inward kingdom of darkness,
where the unbelieving and disobedient to God`'s Spirit and power dwell.
And there is an inward kingdom of light, wherein the children of light dwell with God,
and walk in the light as he is in the light.

But that the work of regeneration is only begun in this life,
and not finished till the other life, that is a great mistake.
For the Scriptures testify that salvation is to be wrought out here, and not hereafter.
Christ had all power in heaven and earth,
and he sent forth his Spirit and power to work out the work here,
by his sanctifying Spirit and power which is able to sanctify throughout, in soul, body,
and spirit.
And the gifts of the ministry are for perfecting the saints,
till they all come in the unity of the faith, unto a perfect man,
that they may be presented to God perfect in Christ Jesus.
The holy leaven is put into the lump here, and it is able to leaven the lump here.
So that holiness is not only to be begun, but perfected in the fear of God,
as the apostle exhorts, who did not exhort to a needless or impossible thing.
And the whole armor of God is able to defend the whole
man from all the assaults of the wicked one;
for greater is he who is in the saints, and who preserves from sin,
than he that tempts to sin.
Oh, how precious is it to war with the enemy in this conquering faith,
and to resist him therein, and to watch him flee from God`'s power and sword,
which will pierce him and can easily overcome him.

There is a state where the spirit is willing, but the flesh weak.
But it is not so where the spirit has become
strong in the Lord and in the power of his might.
The flesh will be rebelling against the Spirit until it
be destroyed by the cross of our Lord Jesus Christ.
But when a man is really crucified with Christ and dead to sin,
then sin has no more power over him,
for Christ lives in him and reigns in his heart over sin and its temptations.
When the God of peace treads Satan under the feet of
the soul that was once taken captive by him,
there it is known to whom belong the kingdom and
the power and the victory and the dominion.

And this is true blessedness begun, carried on, and upheld by the pure,
sanctifying power of the word of life in the heart.
Indeed, the birth which is born of God knows this to be no delusion,
but rather the truth as it is in Jesus.
These are obedient to the true church of God,
and to the holy ministry which he has brought out of the wilderness,
and they also know of what nature the churches and ministries
have been which have appeared and been set up in the world.
For the devil has long transformed himself into the likeness of an angel of light,
and cheated and beguiled souls.
Indeed, the false church has reigned,
with antichrist sitting in the temple (the man-child having been caught up to God,
and the true church hidden in the wilderness),
and men have generally put darkness for light, and light for darkness.
But blessed be the Lord,
the true light which shone in the apostles`' days now shines again!
This light discovers the mystery of iniquity,
and the golden cup of abominations with which the earth has been made drunk,
and Satan falls down like lightning before the power of him upon whom
the true church leaned when she came out of the wilderness.
And upon him she still leans, and will lean forever,
and the gates of hell shall not be able to prevail against her.

Blessed be the Lord who has brought many wanderers and
distressed ones to the knowledge of the true church,
and to a delightful obedience to her, whose voice is not different than Christ`'s,
but one with it.
These are in fellowship with the Father and Son,
and with the saints who dwell in the light.
They are clothed with the Lamb`'s innocency and righteousness,
and do not dwell in darkness or sin,
having crucified the old man with his affections and lusts,
and put off the body of the sins of the flesh by the circumcision of Christ,
and put on the new man which is created in Christ Jesus,
in the righteousness and holiness of truth.
They that are here dwell not in notions and preferences, but in eternal life,
in the pure pastures of life,
where the Shepherd of the inward and spiritual Israel feeds his holy flock day by day.

As for the Roman Catholic Church,
or any other church built up in the apostasy from the Spirit and life of the apostles,
the Lord has given me to see through them, to that which was before them,
and will be after them.
And O dear brother, if you could but rightly wait for and meet with the holy,
regenerating, purifying power (which in tender love I testified to you of),
it would lead you to that which is the true church indeed,
which has been persecuted by the dragon and false church,
who are made drunk by the blood of the true seed.

The Lord has made me your brother in the line of nature;
oh that you were my brother in that truth which lives and abides forever!
Oh that you knew the church of the firstborn, who are written in heaven,
and the Jerusalem above, which is free,
and is the mother of all who are born of the regenerating virtue and power!

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
20th Seventh Month, 1676

[.letter-heading]
To Sir William Armorer^
footnote:[About this man, Thomas Ellwood writes,
"`Penington`'s sixth imprisonment was in the year 1670, in Reading Jail,
where he went to visit his friends that were sufferers there for the testimony of Jesus.
Notice being given of his visit to one called Sir William Armorer,
a justice of the peace living in the town,
he was forthwith brought before him and committed to the jail,
thereby becoming a fellow-sufferer with those he had come to visit.`"
This imprisonment lasted about twenty-one months.]

[.salutation]
Friend,

The weighty sense of an eternal condition after
this life has been upon my heart from my childhood,
and it is often with me that I must give an account to God (when I
pass out of this transitory world) of all things done in the body.
Then indeed I shall enter into eternal rest and blessedness, or eternal woe and misery.

This causes me to call upon the Lord daily, for grace and wisdom from him,
that my conscience, being cleansed through the blood of his Son,
may be kept void of offense, both towards him and men.
And truly (I speak not boastingly, but in the fear of the Lord,
and in the sense of his goodness and tender mercy to me),
my heart is preserved in love and innocency towards those who most injuriously,
and without provocation on my part, have taken away my liberty, as far as I know,
for my whole lifetime.
What you further intend towards me, the Lord knows, to whom I have committed my cause.
But this is on my heart to express to you, because, when I was with you,
you spoke words to this purpose--that we wished you hanged,
or we would be glad if you were hanged.
God, who knows my heart, is witness, that I wish you no evil,
neither to you nor your family.
Indeed, I wish you may avoid all such things that may bring his wrath and curse upon you,
either in this world or the world to come.

And, friend, do not provoke the Lord by afflicting those that fear him.
Rather, cease to do evil, learn to do well, and this will please the Lord,
and is more acceptable to him than all the worship that
can be offered up to him without this.

I have sent you a little book as a token of my love,
desiring you to peruse it seriously.
Oh do not endeavor to bring me into such a condition as is there related!
In the light I have seen that I ought not to swear,
but to give the "`Yes`" and "`No`" of truth, which comes from the Christian nature,
and is of far more certainty and assurance than swearing.
For the man that swears may easily break his oath,
but he that keeps to the truth cannot alter his yes and no, but it stands in the truth.
And this our Lord and Master has set above, and instead of,
swearing--which if we should vary from and deny,
we would deny him who has taught us not to swear.

Friend, God has given you an immortal soul,
and does require of you righteousness towards your fellow creatures,
and temperance and moderation of spirit,
and sensibleness of the judgment to come after this life.
You are stricken in years, and you have but a little moment left remaining of your time,
and then it will be determined concerning your soul, what or how it shall be forever!
Let the words of love, truth, and innocency from me, prevail upon you to be serious,
and to let in the sense and fear of God upon your heart.
You have spent much time in serving man; oh, spend a little in serving and fearing God!
There is something which is pure, and of God,
and appointed by him to exercise the conscience towards him.
You have this thing near you.
Oh that you might know it, and be joined to it!
For until then, you can never truly serve or fear the Lord,
but may spend your time here in a vain show,
and at last be judged and condemned by the Lord, and lie down in eternal sorrow.
Truly,
it is the desire of my heart that this be not your portion from the hand of the Lord.

This is from a sufferer by you,
who never gave you the least cause or provocation to so deal with me,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail

[.letter-heading]
To the Lady Conway

[.salutation]
Dear Friend,

I have heard both of your love to truth, and of your great afflictions outwardly,
both which occasion a sense concerning you,
and breathings to the tender Father of my life for you.
My earnest desire is that your heart may know and be joined to the truth,
and that you may live and walk in it, reaping the sweet comfort, support,
and satisfaction,
which God daily ministers in and through it to his gathered and preserved ones.
Oh that you may be led to where the Comforter does daily delight to
supply the afflicted and suffering ones with comfort,
whether inwardly or outwardly.

Now, my dear friend,
take heed of that wisdom and knowledge which is not of the seed,
and which can be held in the mind, without the springing life of the seed.
The first day I was convinced,
I was not only convinced in my understanding concerning the seed,
but I felt the seed in my heart,
and my heart was enraptured with the sense and feeling of it.
And my great cry to the Lord was that I might faithfully travel
through all the sufferings and death of the natural part,
into union with an enjoyment of the seed,
and that the wisdom which was not of the pure living root and nature might die in me.
Now, how I have been exercised and taught since that time is hard for me to utter.
What poverty, what weakness, what foolishness I have been led into!
How I have learned in the true sense, out of the reach of the comprehending, knowing mind!
How tender I have been of every secret shining of light in my heart!
How the Lord has taught and enabled me to pluck out my right eye,
and cut off my right hand, and cast them from me, that I might not see with that eye,
nor work with that hand, but be greatly maimed in the sight of men,
and in my own sight too.

O friend, wait daily to feel the seed, to feel the seed live in you,
and let the most pleasing part of your nature die, as it can live outside of the seed.
Oh that you could exchange all old knowledge for that which is new and living!
The seed is the well; receive the seed and you receive the well.
Let it spring; wait for its springing; wait to know its springing.
Bear all the trials and judgments which the Father of life
sees necessary to prepare the heart for its springing.
And learn to feel that which limits and subdues your thoughts,
and brings them into captivity and subjection!
Be not exercised in things too high for you.
David, the man after God`'s own heart, who was wiser than his teachers, was not.
Rather, come out of knowledge into feeling,
and there you will find the true knowledge given, arising, springing,
and covering your heart, as the waters cover the sea.
And wait to be taught of God,
to distinguish between the outwardness of knowledge--the notional
part as it can be comprehended in the mind--and the life of it,
as it is felt and abides in the heart.

May the Lord God of my life be your teacher,
and point your mind to the pure seed of the kingdom, and open it in you.
And let him make you so little, that you may enter into it,
and keep you so low and poor that you may abide in it,
managing these troublesome times in the outward for your advantage in the inward.
Then the city and temple of the living God may be built within,
and you will know him daily dwelling and walking therein.
Thus may you be married to the Lord, and become one spirit with him,
finding him to remove all that must be removed by the
mighty arm and pure operation of his Spirit,
till all that is contrary is done away.
Then may your soul dwell with its Beloved in fullness of joy, life, and peace forevermore.

This is from the tender love, and fresh breathings of life,
in your soul`'s true friend, and most hearty well-wisher,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
17th Third Month, 1677

[.letter-heading]
To James Eeles^
footnote:[James Eeles with either a magistrate
or a priest who demanded tithes from Penington.]

[.salutation]
Friend,

God is my witness, to whom I must give an account of all my actions,
that it is my desire to be found in all true love, courtesy, and righteousness,
in my dealings towards all men, and I would by no means deny any man his just due,
which he can by any just law or right claim from me.

Now, with respect to tithes,
the payment or refusing of them is to me a matter of conscience,
weighty on my heart before the Lord, and I desire to do therein as he might justify,
and not condemn me.
I know tithes were ordained by God to be paid to the Levitical priesthood under the law,
but the same power that ordained them under the law, annulled them under the gospel.
See Heb. 7:12 and 18. Here is God`'s power and authority for annulling them.
Now, to suggest that any man has a true right, power,
or authority to require payment under the gospel
for what God`'s power has annulled--indeed,
I do not see in Scripture.
Nor can I be subject to any human authority or
law in this thing without sinning against God,
and incurring his wrath upon my soul, which I have formerly found very dreadful,
and would not, for fear of sufferings in this world, expose myself to bearing it.
Besides, Christ says, "`He that denies me before men, him will I deny before my Father.`"
He is the substance of all the figures under the law; he has put an end to them.
Truly he is King, Priest, and Prophet in the church of God.
All power in heaven and earth is given to him,
and he sent forth his ministers without tithes.
Now, tithes were set up in the dark time of Roman Catholicism,
and not by the gospel light.
Those who know the gospel light dare not be subject to
that which was set up by the dark power of Rome,
in the time of darkness.

I was willing to give you this plain and naked account
that you may see how weighty the thing is with me,
and how dangerous it would be for me to do what you require of me.
For in so doing, I would lose my peace with God,
I would be unfaithful to the testimony he has given me to bear,
I would dishonor his name and truth,
and bring his sore wrath and displeasure upon my soul and conscience.
Judge for yourself in this matter,
whether I had not better expose myself to any outward sufferings,
though ever so great (either from you or any you shall make use of),
than expose my soul to so great inward misery and sufferings
for disobedience to the Lord in this particular.
Consider Ralph Trumper,^
footnote:[Ralph Trumper was one of thousands of Quakers who had corn, cattle,
and other goods taken by force to pay obligatory tithes to the Church of England.
He was later imprisoned on at least two occasions for the same offense.]
a just, tender, honest-hearted man--how much he has suffered in this respect,
to keep his conscience clear in this thing.
But I believe he would rather suffer all his former losses ten
times over again than suffer what he did for paying tithes
after he was convinced of the evil and unlawfulness of it.
I do not contend with you by the law of the land;
but I must be subject to the law of God, who shows me from what root tithes came,
and that they are not the maintenance of the ministry of Christ, or allowed by Christ,
but rather the maintenance of a ministry that Rome`'s power set up.
And truly this ministry and its maintenance are to be denied and witnessed
against by those whom he calls forth to testify to his truth.

So, at present, I say no more, but remain your friend, ready to do you any good,
though I should suffer ever so deeply from you,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
25th Fourth Month, 1677

[.letter-heading]
To Dulcibella Laiton

[.salutation]
Dear Friend,

Concerning whom I feel a travail,
the following is the sense of my heart in relation to you.

There is a pure seed of life which God has sown in you;
oh that it might come through, and come over all that is above it, and contrary to it!
And for that end you must wait daily to feel it, and to feel your mind subdued by it,
and joined to it.
Take heed of looking out, in the reasonings of your mind,
but dwell in the feeling sense of life,
and then that will arise in you more and more which makes you truly wise,
and gives power, and brings into the holy authority and dominion of life.
Many that have been long traveling are now
entering into their possessions and inheritance,
which the Lord is daily enlarging in them, and to them.
Oh that your lot may be among them, inwardly witnessed and possessed by you!
Prize inward exercises, griefs, and troubles,
and let faith and patience have their perfect work in them.
Oh, desire to be good, upright, and perfect in God`'s sight, and wait to feel the life,
Spirit, and power which makes you so!
Come out of the knowledge and comprehension about things, into the feeling of life,
and let that be your knowledge and wisdom, which you receive and retain there.
This will lead you into the footsteps of the flock, without reasoning, consulting,
or disputing.

Oh wait to be taught and enabled by God to take right steps in your travels,
and to take up the cross and despise the shame in everything where that wisdom, will,
and mind of man (which is to be crucified) would be judge!
For the wisdom from below will judge amiss and lead aside if it be hearkened to by you.

You must be very low, weak, and foolish,
that the seed may arise in you to exalt you, and become your strength and wisdom.
You must die exceedingly, again and again, more and more, inwardly and deeply,
that your life may spring up from the holy root,
and you may be more and more gathered into it, spring up into it, and live in the life,
virtue, and power of it.
The travel is long, the exercises many, the snares, temptations, and dangers are many,
and yet the mercy, relief, and help is great also.

Oh that you may feel your calling and election, your sinking down, springing up,
and establishing in the pure seed, in the light and righteousness thereof.

Your friend, in the most sincere, tender love,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
11th Fifth Month, 1677

[.letter-heading]
To Sir William Drake

[.salutation]
Dear Friend,

You expressed to one of my youngest sons, as he related to me,
that you had a desire I should visit you,
that you might have some discourse with me about religion.
That is the most profitable kind of discourse that can be,
if it be ordered in the fear of the Lord, and in a weighty sense and dread of him.
I am very serious in reference to religion,
and desire not to mistake or miscarry in it by any means.
And if I might be helpful to you, or to any man, as to the truth and power of religion,
it would be a matter of gladness to my heart, and of praising and blessing the Lord,
in the sense of his stretching forth his hand towards the saving of any.

Now, that our meeting and discourse may be the more solemn and advantageous,
I have written below a few plain propositions to consider,
which I do not only find signified in the Scriptures,
but the Lord has also written them on my heart.
And if these things are plain to you, and you also are in the serious sense of them,
it may tend towards the making of our discourse the more easy and profitable.

_First,_ there is a holy, righteous, living, powerful God,
who made heaven and earth, and all things therein, and at last made man in his own image,
and set him over the works of his hands, to have dominion,
and rule in his wisdom and power over them.
Now, in this state, God was pleased and took delight in the works of his hands,
and in man above all.

_Secondly,_ man, sinning against his Maker, lost this image, which was his glory,
and became brutish in understanding, and an enemy to God in his mind,
and liable to the wrath of God`'s holy and righteous nature.

_Thirdly,_ there is no reconciliation to be had between God and man,
except by the change of this nature in man.
For God is unchangeable; he is light, he is life, he is holiness unchangeable,
and he will never be reconciled to, or have fellowship with, darkness,
or with that which is dead and unholy--which man in his fallen state is.
So man must be begotten again unto God and changed and renewed
from his evil and sinful nature into a good and holy nature.
He must be turned from evil works and become the workmanship of God,
created anew unto good works.

_Fourthly,_
nothing can produce this change in man except the Spirit and power of Christ,
except the grace and truth which is by Jesus Christ.
Therefore, a man must be sure that he receive this Spirit and power,
and that he feel the operative, changing virtue of it, and be really changed thereby,
being created anew, begotten anew to God, in the holiness and righteousness of truth.
He must be sure that he is made a son and servant to the living God,
or he can never know what belongs to true reconciliation with God,
and to fellowship with him in the light and life of his Son.

_Fifthly,_
all the religions and professions upon the face
of the earth which fall short of this Spirit,
life, and power, and wherein this new creation in Christ Jesus is not witnessed,
nor power received to abstain from what is evil,
and to become sons to God--these are not the pure, powerful, gospel religion,
wherein the divine virtue and power of life operates.
Rather, these are religions which men, in the earthly wisdom, have formed without life.
And all religions that have but a form of godliness, and not the power,
are to be turned away from, and witnessed against,
by such as are called forth to be witnesses to
the true gospel religion and way of worship,
which stands in Spirit, life, and power.

_Sixthly,_ this religion and worship, which stands in Spirit, life, and power,
is the religion and worship which Christ set up about sixteen hundred years ago.
John 4:23-24, 1 Cor. 4:20, Rom. 6:4.
And this is the religion which God has revived and set up again,
as they that receive the gospel now preach it.
And those who believe in the power, which is both outwardly testified of,
and also inwardly revealed, have the witness of it in their own hearts.
Rev. 14:6-7, 1 John 5:10-12, Isa. 53:1. Oh,
how sweet are these scriptures when they are rightly read and rightly understood.
May the Lord give the right understanding, and lead into the true experience of them!

I remain an acknowledger of your kindness,
and a desirer for you that you may obtain from God the knowledge of himself and his Son,
which is experienced (by them that receive it) to be life eternal,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
19th Fifth Month, 1678

[.letter-heading]
To the Women`'s Meeting at John Mannock`'s

[.salutation]
Dearly beloved and honored in the Lord,

Blessed be the Lord, who has gathered you, and given you hearts to meet together,
to feel his precious presence and power, and to wait to do his will therein.

Oh what could the Lord do more for his people,
than to turn them to that pure seed of life which will make them all alive,
and keep them all in life and purity,
and then to make use of every living member in the
living body as his Spirit shall breathe upon them,
and his power actuate them?
And indeed, there is need of all the life and power to the body,
which the Lord sees good to bestow on any member of it.
Every member of the body has life given it, not only for itself,
but also for the use and service of the body.
Only dear Friends, here is to be the great care,
that every member keep within the limits of life,
wherein its capacity and ability for service lies.
For apart from this, it can do no real service for God or to the body.
Oh, therefore, keep the eye fixed upon the life, upon the power,
upon the presence of the Lord with your spirits!
Then he may go along with you, and guide you in every thought you think,
in every word you speak, in reference to his work and service.

And mind, Friends, what is now upon me to write to you:
It is one thing to sit waiting to feel the power,
and to keep within the limits of the power there; and it is another thing, yes,
and a harder one,
to feel and keep within the sense and limits of the power when you come to act.
For then your reasonings, your wisdom, your apprehensions,
have more advantage to rise up in you, and to put themselves forth.
Oh therefore watch narrowly and diligently against the forward part in you,
and keep back to the life, which, though it rise more slowly,
yet acts more surely and safely for God.

Oh,
wait and watch to feel your Keeper keeping you within the holy bounds and limits,
within the pure fear, within the living sense, while you are acting for your God!
Then you will be his instruments alone, and will feel him acting in you.
Therefore, everyone wait to feel the Judge risen up,
and the judgment set in your own hearts, so that what arises in you may be judged,
and nothing may pass from you publicly except for what
has first passed the pure judgment in your own breasts.
And let the holy rule of the blessed apostle James be always upon your spirits,
"`Let everyone be swift to hear, slow to speak, slow to wrath.`"
Oh, let not a talkativeness have place in any of you!
Rather, abide in such gravity, modesty,
and weightiness of spirit as becomes the judgment seat
of the Spirit and power of the Lord.
You can never wait too much for the power, nor can you ever act too much in the power,
but you may easily act too much without it.

And as for this troublesome, contentious business in some,
may the Lord teach you to consider and manage it in a wise, tender, and healing spirit.
You must distinguish in judgment between enemies and erring friends.
And take heed of the quickness and strength of reason, or of the natural part,
which avails little.
But wait for the evidence and demonstration of God`'s Spirit,
which reaches to the witness in others and does the work.
Are they in a snare?
Are they overtaken in a fault?
Are they in measure blinded and hardened, so that they can neither see nor feel aright?
Retire, sit still awhile, and travail for them.
Feel how life will arise in any of you, and how mercy will reach towards them,
and how living words, from a tender sense, may be reached forth to their hearts, deeply,
by the hand of the Lord, for their good.
And if you find them, at length, bowing to the Lord,
oh let tender compassion help them forward!
Then what has been so troublesome and dissatisfactory in their progress,
may at length have a sweet issue for their good,
and for our joy and rejoicing in the Lord.

So, my dear friends, the Lord be with you, and guide you in this,
and in all that he shall further call you to.
And may he multiply his presence, power, and blessings upon you,
and make your meetings as serviceable to the honor of his name,
as he himself would have them, and as you yourselves can desire them to be.

Your friend and brother in the tender truth,
and in the pure love and precious life,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
19th Fifth Month, 1678

[.letter-heading]
To Those Who Drink of the Waters at Astrop Wells

[.salutation]
Dear Friends,

There is a great God, the Creator of all things,
who gave man a being here in this world,
to whom every man must give an account when he goes out of this world.

This great God, who loves mankind, and would not have them perish,
is near unto man, to teach him the fear which is due from him to God.
The man that learns this pure fear of God is
daily exercised by it in departing from evil,
both in thought, word, and deed, and in doing that which is good in his sight.

There is likewise another teacher near man,
who is also ready to teach such as do not know or fear God.
This one teaches to dishonor the great God who made man a vessel of honor for his glory.
They that learn of this teacher learn not to fear God, or to do good,
but rather to please themselves in doing evil, both in thought, word, and deed.
Oh, what account will all such give when they go out of this world,
and come to be judged by the great God (who is of pure eyes, and cannot behold iniquity),
when all their sins are set in order by him before them,
and just judgment is proportioned out by him?
Oh, why do men forget God their Creator days without number,
and instead hearken to him who first deceived them,
doing the will of the deceiver and destroyer of souls,
and not the will of the blessed Creator and Savior?

Oh, hearken to wisdom`'s counsel,
when she cries in the streets of your hearts against that which is evil,
and contrary to the nature, life, and will of God,
lest a day of calamity from God come upon you!
For then you will cry unto the pitiful and tender God,
but his tender heart will be turned against you, and refuse to show you mercy!
Read Prov. 1:20 to the end of the chapter,
and may the Lord give you the weighty consideration and
true understanding of it for your soul`'s good,
and for the reclaiming of you from anything that is evil, and destructive to your souls.

This is written in tender love unto you, from one who pities and loves you,
and desires your prosperity in this world,
and your everlasting happiness with God forever,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Astrop, 15th of Sixth Month, 1678

[.letter-heading]
To Such as Drink of the Waters at Astrop Wells

[.salutation]
Dear Friends,

I entreat you to consider what I have included for your eternal good.
Oh be not deceived by the enemy of your souls, in things of an everlasting concern!
Here are some questions, propounded for your consideration,
in the tender melting love of my heart towards your everlasting welfare.

First question: Is not God light?
Is he not pure light, spiritual light, eternal light, in whom is no darkness at all? 1 John 1:5.

Second question: Is not man, in his natural, unregenerate, corrupt state, darkness?
And can he possibly, in that state,
have any union or fellowship with the great God and Savior?
See Eph. 5:2,8 Cor. 4:1,6 John 1:6.

Third question: Does not the great God, in his tender love to mankind,
cause his pure, heavenly light to shine in man`'s heart,
in this his dark and corrupt state? 2 Cor. 6:6, John 1:5.

Fourth question:
What is the purpose of God`'s causing his pure light to shine in man`'s corrupt heart?
Is it not that man might be turned from darkness,
and from the power of Satan (who keeps him in darkness),
to the light which God causes to shine in him, and to God from whom this light comes?
See Acts 26:18. So that, following Christ, and not walking in darkness,
he might obtain the light of life? John 8:12.

Fifth question: Does man, in his natural corrupt state,
love this light when it shines in him?
Or does he rather hate it?
And can he hate this light without hating God from whom it comes, and whose nature it is?

Sixth question: Why does man, in his natural, corrupt state, hate this light?
Is it not because his deeds are evil,
and because he would prefer to continue in his evil deeds,
without being disturbed or reclaimed by this light? John 3:19-21.

Seventh question:
What does the light of the pure God do for them that receive and obey it?
Does it not bring them out of darkness and change their nature,
so that they become children of the light,
and "`light in the Lord,`" and no more children of darkness, as they were before?
John 12:36, Eph. 5:8.

Eighth question:
How shall it fare with those who receive the
shinings of this light of Christ in their hearts,
hearkening to the reproofs of it, and fleeing from that which it shows to be evil?
Shall they not receive the remission of their sins from God,
and an inheritance among the saints in light?
Acts 26:18, Col. 1:12-13.

Ninth question:
But what will become of those who do not mind the shining of God`'s light in their hearts,
nor are turned to it, nor changed by it,
but rather spend their time in what pleases the corrupt part in themselves?
Will they not be separated, when they go out of this world, from God, who is light,
and have their portion with dark spirits, in utter darkness? 2 Thess. 1:6-10.
See also Matt. 25:30.

Oh, consider these things, while you have time, for your souls`' eternal good,
so that you do not miss the holy way of life and salvation, and so perish!
For God does not desire that any perish,
but stretches forth his hand of love by his inward
"`light of life,`" effectually to save your souls.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Astrop, 20th of Sixth Month, 1678

[.letter-heading]
To One Who Sent a Message from Astrop Wells

[.salutation]
Friend,

I had no purpose in writing or sending those
papers besides true love to your immortal soul,
that you might seriously consider them, and be found in the practice of them,
and so be happy forever.
For as Christ said to his disciples, so it is with me in this case towards you,
"`If you know these things, happy are you if you do them.`"
I have felt the sweetness and great benefit of the practice of them,
which I heartily desire you may also experience.

I here send enclosed a token of my love to you in particular,
which your courteous message drew from me.
It contains, in a few words, the true pathway of salvation, which,
though you may know already,
yet the reading and serious consideration thereof may be serviceable to you.

[.small-break]
'''

[.centered.offset]
THE PLAIN PATHWAY OF SALVATION

[.centered.offset.emphasized]
The Lord Jesus Christ is the only Savior.

[.centered.offset.emphasized]
Grace and truth comes by Jesus Christ.

[.centered.offset.emphasized]
The Lord Jesus Christ saves by the grace and truth which comes by him.

[.centered.offset.emphasized]
For it is the grace of God that brings salvation, and it is the truth, as it is in Jesus,
which makes free indeed.

[.small-break]
'''

He, therefore, that desires to be saved from sin and condemnation,
must wait for the inward manifesting and revealing of the grace and truth in his heart,
and must receive it, and be subject to it,
learning of the grace to deny ungodliness and worldly lusts in every kind.
And he must learn of the truth as it is in Jesus,
to deny whatever is contrary to the life, nature, and Spirit of Jesus.
He must likewise learn of the grace and truth to fear God, to turn from all false,
invented worships and ways of men, and to worship God, the Father of spirits,
in spirit and in truth.
And as he learns and practices this,
he will also learn of the grace and truth to live
soberly and righteously in this present world,
yes, and godly also, even as the holy God would have him. Titus 2:11-12.
For God would have men live no
otherwise than as his grace and truth teaches them.
Now God`'s grace and truth,
and the law of the Spirit of life in Christ Jesus (which is written in the inward parts),
do not only teach that which is good, and to deny and depart from that which is evil,
but they also give ability so to do.
"`My grace is sufficient for you,`" said God to Paul.
And the truth of Jesus, revealed inwardly, has virtue and power in it,
insomuch that they who receive the grace and truth which comes by Jesus Christ,
receive power to become sons of God.
For grace and truth are not notional things,
but indeed have in them the virtue and power of life,
and also the power of mortification.
They that truly receive these, partake of their virtue and power in operation,
and a true exercise of them in their hearts, and are thereby really made dead unto sin,
and alive unto God.

So then, he that knows the grace and truth which comes by Jesus Christ,
and receives it, learns of it, is subject to it, and partakes of its virtue and power,
this one knows Christ unto salvation.
But he that knows not, receives not, is not subject to the grace,
and does not experience the sufficiency of the grace,
nor witnesses the ability and power through it to become a son
of God and to do the will of God--this one does not yet know
the Lord Jesus Christ unto the salvation of his soul,
regardless of what he may profess or believe concerning him.

I am your friend, in true love and desires for you,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Astrop, 28th of Sixth Month, 1678

[.letter-heading]
To the Women Friends that Meet at Armscot in Worcestershire

[.salutation]
Dear Friends,

In your meetings together to do service for the Lord,
every one of you be very careful and diligent in watching to his power,
that you may have the sensible, living feeling of it, each of you in your own hearts,
and in the hearts one of another.
Be careful to keep within the limits of it, and not think, or speak, or act beyond it.
And wait more and more to know how to keep that silence which is of the power,
so that in every one of you, whatever the power would have silent, may be silent.
Oh, take heed of the forwardness of the flesh, the wisdom of the flesh,
the will of the flesh, the talkativeness of the flesh!
Keep them back; oh let them forever be kept back in every one of you,
by the presence and virtue of the power!

The power is the authority and blessing of your meetings,
and therein lies your ability to perform what God requires.
Be sure you have it with you!
Keep back to the life; keep low in the holy fear, and you shall not miss it.
You will find it easy to transgress, easy to set up self,
easy to run into sudden apprehensions about things,
and then one will be of this mind and another of that.
But feel the power keeping down all of this, and keeping you out of it,
while everyone watches to the life, when and where it will arise to help you.
Then you will be sensible of it when it does arise,
and not (in the wrong wisdom) oppose it, but rather be one with it.
And thus, if anything should arise from the wrong wisdom in anyone,
you will be sensible of it, not defiled or entangled with it,
but abiding in that which sees through it and judges it.
Thus, life will reign in your hearts and in your meetings,
above that which seeks to be forward and rise up over the life.

So the Lord God of my life be with you,
and season your hearts with his grace and truth, and daily keep you in the savor thereof.
Then you will be blessed by him, and be a blessing in his hands,
and all that is evil and contrary to truth will be kept down in your own hearts,
and you will be fit to keep down evil in the minds and hearts of others.
And if anything be unsavory anywhere, it will be searched into, judged, and cast out,
and the soul that let it in can be sought out, and if possible, recovered and restored.
Then, you will know the joy of seeking out and bringing back the lost sheep.

There is that near you which will guide you.
Oh, wait for it, and be sure you keep to it!
Then, being innocent and faithful in following the Lord in the leadings of his power,
his power may plead your cause in the hearts of all his tender people hereabouts,
and they will see and acknowledge that your meetings are of God,
and that you are guided by him into that way of service, in his holy fear,
in which he himself is with you.
Be not hasty either in conceiving anything in your minds, or in speaking it forth,
or in anything you are to do.
Rather, feel him by his Spirit and life going along with you,
and leading you into what he would have any of you to do.
If you be in the true feeling sense of what the Lord your God would have done,
and join with what is of God as it rises in any,
or against anything that is not of God as it is made manifest among you,
then you are all in your places and proper services,
obeying the blessed will and doing the blessed work of the Lord your God.

I had something upon me yesterday to you, but my weakness was great.
This morning, this lay as a weight upon my spirit to lay upon yours;
may the weight of it come upon you,
to weigh down whatever is light or chaffy in any of you,
that the seed of life may come up over it, and you may be weighty before the Lord,
in the weighty seed of life.
May the Lord make you rightly serviceable to him.
You will find a great work to keep one part down,
so that that which is pure and living of God may come up in you, and you act only in it,
not exceeding its limits.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Written at John Hawford`'s, 7th of Seventh Month, 1678

[.letter-heading]
To S. W.

[.salutation]
Dear Friend,

I ever had a love to you,
and a deep sense of the serious work of God upon your heart,
and the upright desires of your soul after him.
And it is wonderful in my eyes that the Lord should yet preserve you alive,
in the midst of so great and languishing weakness.
I have often inquired concerning you, and was glad to find a letter from your own hand,
upon the reading of which, in the retired sense of my heart, I felt love arise to you,
and breathings to the Lord for you.
Oh that you may fully feel, and be joined to the seed of life, the seed of the kingdom,
of which our Lord Jesus Christ, in the days of his flesh, prophesied.

O my dear friend, let not any part of your life lie in notions above the seed,
but let it all lie in the seed itself,
in your waiting upon the Lord for its arisings in you, and in feeling its arisings.
Oh what becomes of flesh, and self, and self-righteousness,
when the seed lives in the heart?
My religion (for which I now daily bless my God), began in this seed,
and when I first felt it, and discerningly knew it to be from the Lord,
my cry to him was, "`Oh, this is what I have longed after and waited for!
Oh, unite my soul to you in this seed forever!
This is your Son`'s gift from you, your Son`'s grace, your Son`'s truth, your Son`'s life,
your Son`'s Spirit!
I desire no more than to be made nothing in myself, that he may be all in me.`"
And now, what I meet with and witness here,
what I feel the Lord Jesus Christ to be made to me here, none knows,
or possibly can know, except they that have felt the pure power of the Spirit of life,
and have been led by it into the same holy and blessed experience.

Ah, sin has no share here in this blessed seed,
but is excluded by the life and power which is stronger than it.
Here Christ is formed in the soul.
Truly, here the black garments of unrighteousness, yes, of man`'s righteousness too,
are put off, and the white raiment is put on.
Here the holy image is brought forth in the heart, even the image of the dear Son,
which partakes of the divine nature of the Father.
Here the soul is newly created in Christ Jesus.
Here is no deceit of any kind met with, but only truth from God, even the true life,
light, virtue, power, of the Lord Jesus Christ, as livingly felt in the heart,
and as effectually operating there, as ever the power of sin did previously.
Oh that you might daily discern this, and feel this to grow up in you more and more,
and die to all notions,
even notions of the heavenly things themselves which are held outside of this.
Then your soul may fully live in the life, Spirit, and power of the Lord Jesus Christ,
and nothing but his life, Spirit, and power may live in you,
to the glory of God the Father,
and to the great joy and gladdening of your heart in his presence!
Amen.

Your friend in the true, sincere love of the heavenly, everlasting seed,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
13th Twelfth Month, 1678

[.letter-heading]
To the Lady Conway

[.salutation]
Dear Friend,

In tender love, and in a sense of your sore afflictions and exercises,
I do most dearly salute you,
and I desire for you that the work of the Lord in your heart
may not be interrupted by any devices of the enemy.
Oh may it go on and prosper in you,
in the springing up of the pure seed of life in your heart,
and in the powerful overturning, by the mighty arm of the Lord,
of all that is contrary to it in you.
Oh that you may daily feel that holy birth of life, which is begotten by the Father,
and lives by faith in him!
May you daily feel it living in you when temptations and trials increase on every side.
Oh, feel the birth of life, which will cry to the Father, "`Lord, increase my faith!`"
Though sorrows, heaviness, and faintings of heart increase ever so much, yet,
if your faith increase also, it will bear you up in the midst of them.

Oh that you might come to feel the daily wasting away of sin and death,
and the daily springing up of life and holiness in your heart.
The pearl is worth thousands of worlds,
together with the greatest earthly glory and pleasure imaginable.
Oh that you may be taught of God to discern it more and more, and to buy it,
and to come into the enjoyment and possession of it!
May the Lord manifest Zion more and more to you, and show you the glory of it,
and set your feet towards it, and put into your heart to seek the way to it,
renewing you more and more in the spirit of your mind,
whereby the way comes clearly to be discerned, and faithfully walked in.
Then you will witness daily the everlasting covenant of life and peace,
even the sure mercies of David.

The desire of my soul is that your afflictions (which,
however grievous they may be, are but momentary), may fit you for, and work out,
an eternal weight of glory, for your soul to inherit in another world, forever.

I remain a sympathizer with you in your sufferings,
and desire that all blessings from the God of my life may come to you, which hardships,
temptations, and trials prepare the heart and make way for,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
14th 12th Month, 1678

[.letter-heading]
To S. W.

[.salutation]
Dear S. W.

I have ever had a love to you,
and have many times been filled with earnest desires for you,
that you may know the Lord in his own pure teachings,
and travel into and dwell in the fullness of the kingdom of his dear Son.

In order to arrive here you must wait to know
God and Christ in the mystery of their Spirit,
life, and power,
and here you will find the secrets of the mystery of darkness searched and purged out,
and the mystery of godliness opened and established in your heart in its place.
You must know Christ formed inwardly, the soul formed, yes,
and created inwardly anew in him.
You must know a real transplanting into his death,
and a real feeling of his springing and rising life in all of its sweetness, safety,
and virtue.
So you must be only what you are made and preserved to be in the light, grace, life,
virtue, and power of the Lord Jesus Christ,
and must feel him remove anything that is unrighteous, and clothe you with his pure life,
Spirit, and righteousness.

Oh this is indeed the pure, precious, living knowledge of the Lord Jesus Christ,
which all outward knowledge must lead to, and where it is comprehended and finds its end.
This is the excellency of the knowledge of Jesus Christ our Lord,
which Paul was so ravished with, and for which he counted all things but dross and dung.

Now, that you may obtain this, mind the inward appearance, the root,
the fountain, the rock within, the living stone within.
Mind its openings, its springings, its administering life to you,
and take heed of running into the outwardness of openings concerning heavenly things,
but keep in the inwardness of life within!
This is the everlasting habitation of the birth which is begotten and brought forth,
bred up and kept alive by the presence, power, and operation of the living Spirit alone.
The Lord Jesus is that Spirit, as really as he was once Man, even the holy, heavenly,
immaculate, spotless Lamb of God.
And in this state, life reigns in the heart, and the horn of the Holy One is exalted,
the head of the serpent crushed, yes, Satan is trodden underfoot by the God of peace.
For the Lord desires that his children dwell in the sweetness and fullness of the gospel,
in the peace, life, righteousness, and joy of his blessed Spirit and power.

Oh,
who would not desire after and wait for and walk with the Lord
towards the obtaining and possessing of these things?
All the promises in Christ are yes and amen.
Inward victory is promised; the inward presence of God is promised;
God`'s dwelling and walking in the soul is promised; Christ supping with the soul,
and the soul with him, is promised; putting the law in the heart,
and the writing of it there, and putting the pure, living fear into the heart,
and the holy, powerful Spirit which can cause it to walk in God`'s ways,
and to keep his righteous judgments and do them--all of this is promised.
Yes, the Lord is able to do this work in the heart,
for what cannot the Spirit of judgment and burning consume and burn up within?
Indeed, all these things are promised.
He can cause the soul to rejoice in the Lord, and work righteousness,
and to remember the Lord in his ways,
as some were taught and enabled to do in former times. Isa. 64:5.
Yes, he can bring into the way of holiness, the King of glory`'s highway,
into which no unclean thing can enter.
And truly, they that are kept undefiled in the way taste of the sweetness, blessedness,
purity, and holy pleasure.

Certainly, if that is indeed put off wherein the enemy`'s power lies,
and that indeed is put on wherein the strength of the Lord Jesus is revealed,
and if the soul is really in the possession of,
and abides in this state--how can it not be
strong in the Lord and in the power of his might?
How will it not witness the good pleasure of the Lord fulfilling his good work,
and the work of faith going on with power, daily, more and more?
A little measure of this kept to, removes the mountains inwardly,
and gives strength over the enemy.

O my friend, there is an ingrafting into Christ,
a being formed and newly created in Christ, a living and abiding in him,
and a growing and bringing forth fruit through him into perfection.
Oh, may you experience all these things!
And that you may do so, wait to know life, the springings of life,
the separations of life (inwardly) from all the evil which hangs about it,
and would be springing up and mixing with it, under an appearance of good.
I desire that that life may come to live fully in you, and nothing else.
So sink very low, and become very little, and know little.
Yes, know no power to believe, act, or suffer anything for God,
except as it is given to you by the springing grace, virtue, and life of the Lord Jesus.
For grace is a spiritual, inward thing; it is a holy seed, sown by God,
springing up in the heart.
People have a notion of grace, but know not the thing.
Do not concern yourself with the notion, but feel the thing,
and know your heart more and more plowed up by the Lord,
that his seed`'s grace may grow up in you more and more,
and you may daily feel your heart as a garden enclosed, watered, dressed,
and delighted in by him.

This is a salutation of love from your friend
in the truth which lives and changes not,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
27th Twelfth Month, 1678

[.letter-heading]
To M. Hiorns

[.salutation]
Dear Friend,

I received two letters from you lately, whereby I sense your great love to me,
and the Lord`'s great goodness to you,
in administering that which rejoices and refreshes you.

Now, this advice arises in my heart: keep cool and low before the Lord,
that the seed, the pure, living seed, may spring more and more in you,
and your heart be united more and more to the Lord therein.
Coolness of spirit is a precious frame, and the glory of the Lord most shines therein,
in its own luster and brightness.
When the soul is low before the Lord, it is near the seed,
and preciously (in its life) one with the seed.
And when the seed rises, you will have liberty in the Lord to rise with it.
Only take heed of that part which will be outrunning it, and getting above it,
and so not ready to descend again, and keep low in the depths with it.

O my friend,
I have a sense that this has been the error of
that people with whom you have formerly walked,
and I yet observe in your spirit a liability to it.
May the Lord give you to watch against it,
that you may come to a pure observation and discerning of the everlasting,
unchangeable seed in your own heart.
And may you daily feel your mind bowed down to worship in this seed,
and become wholly leavened into it, and be perfectly changed and preserved by it.

We are here but a little while in this world, for the Lord to make use of us,
and to serve himself by us,
and to fit us for the crown of glory which he
will give us fully to wear in the other world.
Now, feel the child`'s nature, which chooses nothing,
but desires the fulfilling of the Father`'s will.
I cannot desire to enjoy anything (says the nature of the true birth),
except as the Father is pleased to give me to enjoy.
There is a time to need, as well as to abound, while we are in this world.
And the times of need, as well as the times of abounding, are greatly advantageous to us.
How should faith, love, patience, meekness,
and the excellency and sufficiency of God`'s grace shine, except by, in,
and through the many exercises and varieties of conditions wherewith the Lord visits us?
Yes, the greatest in the life, power, and glory of the Lord,
have the greatest trials and exercises, which is to their own advantage,
as well as for the good and benefit of others,
and to the great honor and glory of the Lord.
Oh, at all times, and in all conditions, take heed of a will, take heed of a wisdom,
which is above the seed`'s will, and above the seed`'s wisdom.

Let the Lord alone be all in you, and make you every day what he pleases.
In due time, you shall know a life--even the seed`'s life, the Son`'s life,
whom all of the angels are to worship--as it is revealed and brought forth!
So, be still, quiet, and silent before the Lord,
not putting up any request to the Father, nor cherishing any desire in you,
except in the seed`'s lowly nature and purely springing life.
And may the Lord give you the clear discerning, in the lowly seed,
of all that springs and arises in your heart.

You did read precious things of the seed when you were here, written outwardly;
oh that you might read the same things written inwardly in your own heart!
This you may do, if you become as a weaned child,
not exercising yourself in things too high or too wonderful for you.
Every secret thing, every spiritual mystery, besides what God opens to you,
is too high and wonderful for you.
And if the Lord at any time opens to you deep mysteries, then fear before the Lord,
and go no further into them than the Lord leads you.
The error is still in man`'s comprehending, knowing mind, but never in the lowly,
weighty seed of life.
For the greatest, as well as the least, must be daily taught by the Lord,
both in their ascending and descending, or they will miss their way.
Yes, they must be daily taught of him to be silent before him,
and know what it is to be still in him, or they will be apt to miss in both.

This from your friend,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Amersham, Woodside, 4th of Fifth Month, 1679.

[.letter-heading]
To Sarah Elgar

[.salutation]
Dear Friend,

The child which the Lord has taken from you was his own.
He has done you no wrong in calling it from you.
Take heed of murmuring; take heed of discontent; take heed of any grief,
except what truth allows you.
You have yet one child left.
The Lord may call for that too, if he please, or he may continue and bless it to you.
Oh, mind a right frame of spirit towards the Lord in this your great affliction!
If you mind God`'s truth in your heart, and wait to feel its seasoning,
it will bring you into, and preserve you in, a right frame of spirit.
The Lord will not condemn your love and tenderness to your child,
or your tender remembrance of him.
But still, in this be subject to the Lord, and bow before his will and disposal,
and let not the will of your nature rise above it.
Retire out of the natural, into the spiritual, where you may feel the Lord your portion,
so that now, in the needful time, you may daily receive and enjoy satisfaction therein.
Oh, wait to feel the Lord making your heart what he would have it to be,
in this your deep and sore affliction.

And now, let the world see how you prize the truth, and what truth can do for you.
Feed on it; do not feed on your affliction.
The life of truth will arise in you, and raise you up over your affliction,
to the honor of the name of the Lord, and to the comfort of your own soul.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Nunnington, Sixth Month, 1679

[.letter-heading]
To Sarah Bond

[.salutation]
Dear Sarah,

I have had many thoughts of you in this my imprisonment,
wherein I have seen in spirit your error and miscarriage,
and also a hope and expectation in your heart which will deceive you.

Oh, how much precious time have you lost,
wherein you might have been traveling far on your journey,
while you are disputing in your mind,
and wandering in the deceitful reasonings of your heart!
And indeed, it will never be as you imagine, but you must begin low,
and be glad of a little light with which to travel out of the earthly nature,
and be faithful therein.
And in faithfulness you may expect additions of light,
and as much power as may help you to continue on.
And though you may long be low, weak, little, and ready to perish,
yet in the humble and self-denying state, the Father will help you,
and cause his life to shoot up in you, and in this shooting up will be your redemption.

But oh, hasten out of the earthly nature while you have time,
and still have any visitations from the Spirit of the Lord!
And do not, in your wisdom, limit him, but accept whatever at present comes from him;
for the flood is breaking out,
and will swallow up and drown all that are not found in the ark.
Therefore enter, enter quickly!
Mind that which checks you in your heart.
And mind also that which reasons against those checks, to hold you still in captivity,
and to keep you from traveling out of the earthly nature, spirit, wisdom, and practices.
Oh, come out of the spirit and way of this world, that you may live and not die.
For none shall live except those that walk in the way of life,
and leave the paths and course of the dead, in which you are yet entangled.
Do not limit the Holy One of Israel in your desires or expectations,
but thankfully receive the smallest visitation that comes from him to your soul,
for there is life and peace in it, and death and perplexity in turning from it.
Therefore, receive the day of your visitation,
and be turned in it from the darkness of the earthly mind and nature,
into the light of all living and redeemed souls!

And this is my tender counsel to you--wait for and
gaspingly receive the checks of the Most High,
and take heed of reasoning against them.
As these (though in a low and mean and despicable way to your
wisdom) draw and lead you out of any earthly thought,
word, custom, or practice, follow diligently,
waiting to have your reasonings subdued to the smallest
motions and lowest guidance of life in you.
For I know that life is near you, even the life that would effectually redeem you.
But now the life is bowed down and held captive under the dominion of the earthly wisdom.
So it is that your redemption (which is to be wrought out by the life) is hindered,
and will be hindered,
until your heart is persuaded to join to the
life and become subject to it without reasoning,
consulting, or disputing.
For I certainly know the light manifests in you,
but the darkness puts off the present manifestation of the light, and expects another;
and this is in the will of the flesh, which the Father will not answer.
O friend, in this will and expectation you will perish; but your help, life,
and salvation are in being subject to the present manifestation of light,
and parting with, and departing from, what you already know to be of the earth,
and not of God.

In doing this, more will be made manifest in the Lord`'s season,
and power will be given to become a child (after
some entrance into the childlike nature).
But the will and expectation of the flesh in you shall never be answered.
It has been long written in my heart concerning you, but I dare never utter it to you.
Oh that it may be now uttered, to the melting and advantage of your heart!
For indeed, I love you, and have travailed for you,
and desire the salvation of your soul, as of my own.
Oh that you may be led out of that wisdom which destroys, into that which saves,
where (in humility of heart) you will receive instruction daily, according to your need.
But truly you must come into, and come under, that which crucifies your nature and wisdom.
Here only (in the season of God`'s wisdom,
who answers the desires of his own Spirit in the heart,
but regards not the flesh) will you meet with life and power, but nowhere else.

I am your friend, and a dear lover of that in you which desires the Lord.
Oh, that it might rise up in you, and be severed from the earth, that your soul may live!

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Friends in the Truth at Lewes

[.salutation]
My Dear Friends,

The God of truth plants his truth in the hearts of people,
that it might grow there, and bring forth fruit to him.
O my dear friends, feel it grow in every one of your hearts,
bringing forth the proper fruits of its growth to the Lord.

Mind what arises from the truth, what truth brings forth,
and wait for and receive your nourishment from the Lord,
that it may be brought forth in you.
And whatever the Lord has made barren in you (you who
have experienced his righteous judgments),
let it be kept so by the same power which made it barren,
that no more fruit may be brought forth to sin and unrighteousness.
Then you will live the life of truth, and dwell and walk in the truth,
where there is no greater joy, delight, or peace to be desired or enjoyed.

O my dear friends, know, and every day experience,
Enoch`'s life--a being translated out of the kingdom of darkness,
into the kingdom of the dear Son, and of walking with the Son in his kingdom.
Then you will walk with the Father also, and know the heavenly paths of life, joy,
righteousness, and peace in the pure light of life,
which is no less than a paradise to the renewed soul.

I would eagerly have seen you together, had the Lord made a way,
but let me feel you in the hidden life, and meet you at my Father`'s throne.
This is the salutation of my love to you,
which so lay upon me that I could not pass it by, who am your friend, in the everlasting,
unchangeable truth of our blessed God and Savior.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

Because my not praying in my family, according to the custom of professors,
seemed to be such a great stumbling-block to you,
it sprang up in my heart to render you this account thereof.

I did formerly apply myself to pray to the Lord,
morning and evening (besides other times),
believing in my heart that it was the will of the Lord I should so do.
And this was my condition then--sometimes I felt the living spring open,
and the true child breathe towards the Father, but at other times I felt a deadness,
a dryness, a barrenness, and only a speaking and striving of the natural part.
Even then, I felt this was not acceptable to the Lord, nor any profit to my soul,
but I apprehended it to be a duty, and I dared not but apply myself to it.

Since that time--that is,
since the Lord has again been pleased to raise up what he had formerly begotten in me,
and feed it by the pure giving-forth of that breath of life which begat it,
which is the bread that comes down from heaven daily to it--the Lord
has shown me that prayer is his gift to the child which he begets.
I have seen that true prayer stands not in the will, or time, or understanding,
or affectionate part of the creature, but in the Lord`'s own begetting,
in which he first breathes upon the soul, and it breathes again towards him.
The Lord works this at his own pleasure, and no time can be set when he shall breathe,
or when he shall not breathe.
When he breathes, then is the time of prayer, then is the time of moving towards him,
and following him who draws.
So that all my times, all my duties, all my graces, all my hopes, all my refreshments,
and all my ordinances, are in his hand, who is the spring of my life, and conveys,
preserves, and increases life of his own good pleasure.

I freely confess,
all my religion stands in waiting on the Lord for the riches of his Spirit,
and in returning back to the Lord (by his own Spirit, and in the virtue of his own life),
that which he pleases to bestow on me.
I have no faith, no love, no hope, no peace, no joy, no ability to do anything,
no refreshment in anything, except as I find his living breath beginning, continuing,
answering, and performing what it calls for.
So that I have become exceedingly poor and desolate,
except in what the Lord pleases to be to me by his own free grace,
and for his own name`'s sake, and in his rich mercy.
And if I have tasted anything of the Lord`'s goodness sweeter than ordinary,
my heart is willing (so far as the Lord pleases) to
faithfully point any others to the same spring,
and not to discourage the least desire after God in them.
But where they have lost the true living child,
and another thing has risen up in its stead (which,
though it may bear the image of the true to the eye of flesh,
yet is not the same thing in the sight of God),
and where this nourishes itself by praying, reading, meditating,
or any other such like thing,
feeding the carnal part with a kind of knowledge from Scriptures--this,
in love and faithfulness to the Lord and to souls, I cannot but testify against,
wherever I find it, as the Lord draws forth my spirit to bear testimony.

This I know from the Lord to be the general state of professors at this day.
The Spirit of the Lord is departed from them, and they are joined to another spirit,
as deeply and as generally as ever the Jews were in their day.
And their prayers and reading of the Scriptures, and preaching, and duties,
and ordinances are as loathsome to the soul of the Lord,
as ever the Jews`' incense and sacrifices were.
And this is the word of the Lord concerning them: You must come out of your knowledge,
into the feeling of an inward seed of life,
if ever you will be restored to the true unity with God,
and to the true enjoyment of him again.
You must come out of the knowledge and wisdom you have gathered from the Scriptures,
into a feeling of the thing there written,
as it pleases the Lord to open and reveal them in the hidden man of the heart.

This is what you must wait for from the Lord,
and not to boast of your present state, as if you were not backslidden from him,
and had not entered into league with another spirit which keeps up
the image of what the Spirit of the Lord once formed in you,
but is without the true, pure, fresh life.

From a faithful friend and lover of souls,

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To E. Terry

[.salutation]
Friend,

If the Lord has extended favor to you and shown you mercy,
I therein rejoice on your behalf.

Your desire--that what you wrote may be looked upon as nothing,
and that no contest may be raised from it--I am fully content to oblige.
Indeed, my love flows to you, for I take notice of your seriousness,
and of whatever I have unity with in your letter, and I overlook the other.

With regard to disputes, indeed, I have no love for them.
Truth did not enter my heart that way, nor do I expect to propagate it in others that way.
Yet, sometimes a necessity is laid upon me, for the sake of others.
And truly, when I do feel a necessity, I do it in great fear,
not trusting in my spear or bow (I mean in strong arguments or wise considerations,
which I, of myself, can gather or comprehend),
but I look up to the Lord for the guidance, help, and demonstration of his Spirit,
that a way may be made thereby in men`'s hearts for the pure seed to be reached.
Only in this is there a true conviction,
and a thorough conversion of the soul to God is witnessed.
I had far rather be feeling Christ`'s life, Spirit, and power in my own heart,
than disputing with others about it.

Christians that truly fear the Lord have a proportion of the primitive Spirit,
and if they could only learn to watch and wait there (where God works his fear),
they would daily receive more and more of it.
Only by this will they come to understand more and more of the true
intent and preciousness of the words of the Holy Scriptures.
He that will truly live to God, must hear wisdom`'s voice within, at home,
in his own heart, for he that will have her words made known,
and her spirit poured out to him, must turn at her reproof. Prov. 1:23.
Indeed, I never knew, and am satisfied that none else can know,
the preciousness of this lesson till they are taught it of the Lord.

There is one thing more on my heart to express, occasioned by your last letter,
which is this:
I have more unity in my heart and spirit before the Lord with the Puritans,
than with the churches and gatherings which men have built up and run into since.
The seed of life and truth was near me, as well as others, in that day,
but I wandered from it into outward knowledge, and, with great seriousness,
into a way of congregational worship, and thereby came to a great loss.
Then, at length, for lack of the Lord`'s presence, power, and manifestation of his love,
I became exceedingly sick at heart.
But now, the Lord, in great love and tender mercy,
having brought me back to the same seed, and fixed my spirit therein,
I discern the truth and beauty of that former state,
(along with my several runnings out from it),
and I find what was true or false there uncovered to me by the holy Anointing,
which appears and teaches in that seed.
And friend, it is not a notion of light which my heart is engaged to testify of,
but rather that very light which enlivens, which opens, which gives the heart to see,
and that wherein the power of life is felt.
For truly, in the opening of my heart by the pure power,
I was taught to see and own the principle and seed of life,
and to know its way of appearance.
So that I can faithfully and certainly testify, that that which is divine, spiritual,
and heavenly, is nearer man than he is aware,
as well as that which is earthly and selfish.

O friend,
if you cannot yet see and own the principle and seed of Christ`'s life and Spirit,
nor discern his appearance therein, yet take heed of fighting against it.
For, indeed, if you do, you fight against no less than the Lord Jesus Christ himself.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Richard Roberts

[.salutation]
Dear R. R.

You did acquaint me that Timothy Fly, the Anabaptist teacher,
did charge me with denying Christ`'s humanity,
and also the blood of Christ which was shed at Golgotha, outside the gates of Jerusalem,
and that I acknowledge no other Christ except he that is within men.

Certain I am that neither Timothy Fly, nor any other man,
did ever hear me deny that Christ was born of the Virgin Mary according to the flesh,
or that it was his blood which was shed outside the gates of Jerusalem.
And the Lord, who knows my heart, knows that such a thing was never in my heart.
No, for I do greatly value that flesh and blood of our Lord Jesus Christ,
and witness forgiveness of sins and redemption through it.
Yet, if I should say that I do not also know nor partake of his flesh and blood in spirit,
I should not be a faithful witness to the Lord.
For there is the mystery of God and of Christ,
and it is the soul`'s food which gives life to the soul,
even the living bread and the living water.
There is a knowing Christ after the flesh, and there is a knowing him after the Spirit,
and a feeding on his Spirit and life; and this does not destroy his appearing in flesh,
or the blessed ends thereof, but rather confirms and fulfills them.

Indeed,
the acknowledging of Christ being inwardly in his saints does not
deny his appearing outwardly in the body that was prepared for him,
unless Timothy Fly can prove this--that the same Christ
that appeared outwardly cannot appear inwardly.
"`Do you not know yourselves that Jesus Christ is in you,
unless indeed you are disqualified?`" 2 Cor. 13:5.
"`And if Christ is in you, the body is dead because of sin,`" etc. Rom. 8:10.
"`Christ in you, the hope of glory.`" Col. 1:27.
"`Behold, I stand at the door and knock;
if any man hear my voice and open the door, I will come in to him.`" Rev. 3:20.
"`I will come again,`" says Christ; you are now in pain,
as a woman in travail, full of sorrow for the loss of my outward, bodily presence,
but I will come to you again in Spirit;
see John 16 and John 14:17. "`He that dwells with you, shall be in you,`" and then,
when the Bridegroom is inwardly and spiritually in you and with you,
"`your heart shall rejoice, and your joy no man will take from you.`" John 16:22.
And so,
the apostles and primitive Christians did "`rejoice with joy unspeakable,
and full of glory,`" 1 Peter 1:8,
because of the spiritual appearance and presence of the Bridegroom.
And yet, there is no other bridegroom, who now appears in Spirit,
or spiritually in the hearts of his own,
than he who once appeared in the "`body prepared
for him,`" to do the Father`'s will therein.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To the Independents at Canterbury

[.salutation]
Dear Friends,

I have been a seeker after God, and a worshipper of him, from my childhood,
according to the best of my understanding.
And for a time, I sat down in that way which is called Independency,
believing it to be the way of the gospel,
and entering into it with much fear and seeking of God.
In this time, the Lord had regard to the uprightness and tenderness of heart,
which he himself had formed in me.

But, at length, the Lord`'s hand fell upon me,
breaking me all to pieces as to my inward state.
For what cause, I had then no knowledge of at all, but I mourned before him unutterably,
night and day,
and lay panting and languishing after him who was the only Beloved of my soul.
Many pitied me, but none could reach my state, and after much serious discourse with me,
they greatly wondered.
Some said it was a unique case,
and would doubtless end in goodwill and mercy from the Lord to me.
I parted from the Independents in great love and tenderness--they expecting my
return to them again (the love between me and them being so exceedingly great,
and I having let in no prejudice against them), and I knowing nothing to the contrary.

But it pleased the Lord, after many years, when my hope nearly failed,
to visit me in a wonderful manner, breaking my heart in pieces,
giving me to feel his pure, living power,
and the raising of his holy seed in my heart thereby.
Then I cried out inwardly before him, "`This is he, this is he whom I have sought after,
and so much wanted!
This is the pearl, this is the holy leaven!
Do what you will with me, afflict me how you will, and as long as you please,
so that at length I may be joined with this seed, and become one with it!`"
So the eye of my understanding was from that day anointed,
and I saw and felt the pure life of the Son made manifest in me.
Indeed, the Father drew me to him, as to a living stone, and has built my soul upon him.
He brought me to Mount Zion, the holy city of our God,
where the river of life sends forth its streams
which refresh and make glad the holy city,
and all the tabernacles that are built on God`'s holy hill.
And truly, from this holy hill and city, the law and word of life does issue forth,
and the inhabitants of the rock of life hear it, and are friends to the Bridegroom,
and glad of the Bridegroom`'s voice.
These follow the Lamb, the Shepherd and Bishop of their souls, wheresoever he leads.
And he leads them into the pastures of life, and the folds of pure rest,
and gives them eternal life to feed upon.

O you Independents, whom I have loved above all people!
I never had thoughts of departing from you,
but was forcibly taken by the hand of the Lord out of your Society,
and yet not without a desire to return to you again,
if the Lord pleased to make any way thereto.
O beloved Independents, that you could hear the sensible,
experienced testimony that is on my heart to you concerning my Beloved,
concerning his appearance, concerning his church, concerning his way, his truth,
his kingdom!
It is nearer than you are aware, and above all that you can comprehend concerning it.
Oh that you might inwardly know these things!
Turn in, turn in!
Mind what stirs in your hearts, what moves against sin, and also what moves towards sin.
The one is the Son`'s life, the Son`'s grace, the Son`'s Spirit;
the other is the spirit and nature which is contrary to it.
If you could only come to the sense of this, and come to a true, inward silence,
and waiting, and turning at the reproofs of heavenly wisdom,
and know the heavenly drawings into that which is holy and living,
then you would soon find the Lord working in your hearts, to stop the issues of death,
and to open the issues of life.
You would find yourselves anointed daily by the Lord (for
there is not a day that we do not need to see,
nor a day where the Lord does not give sight),
and an understanding also would be given you to know him that is true,
and an abiding in him that is true, even the "`eternal life.`" 1 John 1:2.
And abiding here,
you cannot fail to receive power (from him who
ministers according to the power of the endless life),
not only to overcome sin and your souls`' enemies, but to become sons to God,
with delight performing his will.
Then the yoke, which yokes down and subdues sin in you, will be easy.
Yes, it will be the ease, pleasure, and joy of your souls.

May the Lord open an ear in you to hear,
that you may become experiencers and possessors of these things.
For, of a truth, the Lord is arisen to shake terribly the earth,
and to build up his Zion,
and to give unto his people "`a peaceable habitation and sure
dwellings and quiet resting places`" upon Mount Zion. Isa. 32:18.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Francis Pordage

[.salutation]
Friend,

There is a mind which can never know nor receive the things of God`'s kingdom,
and yet, this mind is very busy in searching and inquiring after them.

The Scribes and Pharisees were questioning Christ,
and desiring satisfaction about the kingdom, and about his doctrine and miracles,
and the practice of his disciples, but they could never find satisfaction.
Yet, the disciples themselves were many times afraid to ask Christ questions,
there being a dread of God upon their spirits,
and a limit to the knowing and inquiring part in them; for indeed,
the true birth learns under the yoke.

This, therefore, is precious--to come to feel that which limits the natural mind,
which is forward and inquisitive without the true nature and sense.
Indeed it is good for that mind to receive the yoke,
and to be limited by it and famished; for famine is appointed for that mind and birth.
It is written, "`I will destroy the wisdom of the wise,
and bring to nothing the understanding of the prudent.`"
Now, this is precious and greatly needful--that a man know, discern,
and watch against that wisdom and understanding in
himself which God will destroy and bring to nothing.
For, to be sure, while he is learning and striving to know with that mind,
God will never teach him, but rather hide the mystery of life and salvation from him.
And what is all man`'s knowledge worth, that he learns of himself without God`'s teaching?
What good is that which man receives into the
understanding which is to perish and be destroyed?
In the new understanding, God sets up the true light;
but in the other understanding there are false lights set up,
which do not give a true distinction of good and evil, but they call good evil,
and evil good, and put darkness for light, and light for darkness.
Indeed they cannot do otherwise, for the light in them is darkness,
not being the gift of grace whereby they see and judge, but a light of their own forming,
according to their own comprehension of things, in the dark and false understanding.

Now, the Lord has taught us the difference between all these lights,
and the light of his grace, which purely teaches, livingly teaches,
not in the reasonings of the mind,
but in the evidence and demonstration of God`'s Spirit in the soul and conscience.
When we came to see in this light, we found that which we had called good,
according to our former apprehension of things, was not so in the true balance.
And what we thought had pleased God, was abominable in his eyes.
And truly, all that have not come to this light offer that which is abominable to God,
and yet think it pleases him.
Oh what a gross and dangerous mistake this is!
Indeed, all such things are no better than acts of man`'s own will,
which are done outside of the light, life, virtue, and power of God`'s Spirit.
For the root must be good, or the fruit cannot be good.
The mind must be renewed, or the knowledge is but old, dead, literal, and fleshly.
The fleshly understanding seeks to comprehend and receive knowledge,
but can never know or receive what is spiritual.

Truly, the Lord has led us a great way in our journey,
and has done great things inwardly for and in our spirits.
Yet, if we were not kept under the yoke, and that part in us still had liberty to know,
live, act, and worship, we should yet perish, and be cut off from the land of the living.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
In Reply to an Answer of I. H.

[.salutation]
Dear Friend,

Indeed, to speak properly, the church of the gospel, or the new covenant church,
is invisible.
The persons in whom the church is, are visible;
yet the new covenant church is not a society of men,
but rather of the invisible life within men.
It is a fellowship in the faith, in the Spirit,
which is the bond of their unity and of their peace.

The life is breathed invisibly into the hidden man, John 3:8,
and is there nourished and built up invisibly into a spiritual, invisible temple, house,
or church, and in that is the unity and fellowship.
So the church is a mystery, and the fellowship is a mystery,
which is hid from every eye but the eye of life.
There is no having fellowship one with another except by coming to that,
and keeping in that, wherein is the fellowship. 1 John 1:7.
The church is built of inward Jews,
whom God seeks to frame his new house of worship under the gospel. John 4:23.
Now, of such stones as these,
the Lord builds up a temple for his Spirit to dwell in,
a house for his life and presence to manifest itself in,
even a church for the living God.
This building is by the Spirit, in the Spirit, and of that which is spiritual.
This building is one with the foundation,
and therefore is the pillar and ground of Truth, which none is but Christ,
and that which is married to him, and so one with him. 1 Tim. 3:15.

It is the candlestick within persons--that is the church.
It is not any outward meeting of persons, or joining together by covenants,
or receiving or practicing of ordinances, that can make a church,
but rather the eternal life in believers, formed by the Spirit into a candlestick,
to hold the eternal lamp or light, with the everlasting oil of salvation.
The light thus shining in this candlestick,
continually refreshed by this oil--here is a flourishing temple, wherever it is found.
Here is the church of the living God.
Here is the spouse married to the Lamb, her Husband.
But if you grieve the Spirit, quench the Spirit, despise the prophesying thereof,
and light a candle of the fleshly wisdom and
knowledge of the things of God instead of these,
then the oil soon fails.
When the oil fails, the lamp goes out.
And the lamp, or light, being gone out of the candlestick,
the Lord soon removes the candlestick.
And once the candlestick is removed, the very same persons may meet together often,
and hold up the form, performing things mentioned in the Scriptures concerning a church,
and observing such things as they may call the institutions and ordinances thereof,
but they are far from continuing to be a church.
Take away the faith, what is left of a Christian?
And take away the candlestick, what is left of a church?

It is the Spirit alone that can square stones
and fit them for the building of a church.
He alone can build them up into a house when he has squared them. Eph. 2:22.
And after he has built, he can also pull down again,
and bring into a wilderness state.
For there is a wilderness state of Christianity, as well as a built state. Rev. 12:6.
And just as it is dangerous to be out of the church in its built state,
so too it is dangerous remaining in that building which
the Spirit of the Lord has forsaken.
Now, if the Spirit be the builder,
surely then he will take in no stones except such as he
has first squared and fitted for the building.

The church is a body gathered in the Spirit, and watching to the Spirit.
And the Spirit is present there with his pure, searching, discerning eyes,
so that nothing that is impure can enter (each stone watching to the Spirit,
according to the order of the gospel).
There is not one counterfeit Jew.
There is not so much as one false apostle,
though they clothe themselves ever so like angels of light.
Rev. 22. But if they are negligent, and come off from the watch,
not waiting for the guidance of the Spirit, then that which is corrupt may creep in,
and endanger the body. Jude 4.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Bridget Atley

[.salutation]
Dear Friend,

I am sensible of your sore travail and deep distress,
and how hard it is for you to meet with that which is comfortable and refreshing,
and how easily again it is lost.
And I know from where this arises,
even from the working of the enemy in a mystery of deceit in your heart,
wherein you do not perceive or suspect him, but instead swallow down his baits,
and so he smites you with his hook,
and thereby draws you back into the region of darkness.
Then he enters that part in you which is in nature one with him,
filling it with his wickedness, and laying loads of accusations upon you,
as if they were true.
These are not strange things to the travelers after the Lord,
but such as are usually met with in the like cases.
But if your eye were made single and opened by the Lord, you would see those baits,
and turn away from that which you now so readily swallow down, and so avoid the stroke,
and keep your place in the light and mercy of the Lord.
You must not look so much at the evil that is near,
but rather at he who stands ready to pity and help,
and who has pitied and helped your distressed soul, and will pity and help it again.
Why is there a mercy seat, but for the sinner to look towards in time of need?

Neither must you hearken to the questionings of the ensnaring questioner,
but rather cleave to that which shuts them out,
keeping to the sense of the love and mercy when the Lord is kind and tender to you.
When the enemy entered your habitation again, and broke your rest, peace,
and enjoyment of the Lord, he then drew you into the pit of darkness,
where the remembrance of life, and the sense of mercy and love vanishes.
Here there is no help for you from anything you can do or think.
But be patient, till the Lord`'s tender mercy and love visit you again.
And then, look up to him against this and such like snares,
which would come between you and the appearance of the Lord`'s love,
so that you may feel more of his abiding with you, and the sweet effects thereof.
For, these things are not to destroy you, but rather to teach you wisdom,
which the Lord is able, through many exercises and sore trials, to bestow upon you.
And my soul will exceedingly rejoice to hear that your
heart has been rid of all that burdens you,
and filled with all it rightly desires after.

Your faithful friend,

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Abraham Grimsden

[.salutation]
Friend,

You have made some profession of truth, and at times have come among us,
but whether you have been changed thereby,
and been faithful to the Lord in what has been made manifest to you,
belongs unto you diligently to inquire.
There is no safe dallying with truth.
He that puts his hand to the plow must not look back at anything of this world,
but rather take up the cross and follow Christ in the single-hearted obedience,
hating father, mother, goods, lands, wife, yes, all for his sake,
or he is not worthy of him.
The good hand of the Lord is with his people,
and he blesses them both inwardly and outwardly.
They that seek first the kingdom of heaven, and the righteousness thereof,
have other things also added.
But they that neglect the kingdom, and are unfaithful to truth,
seeking the world before it--the hand of the Lord goes forth against them,
and they many times also miss the world for which they seek and labor.

Truth is honorable.
Oh take heed of bringing a reproach upon it by pretending to it, and yet not being of it,
in the pure sense and obedience which it begets and
brings forth in the hearts and lives of the faithful.
Oh, consider rightly and truly!
It had been better for you if you had never known truth,
nor been directed to the seed and path of righteousness, than,
after being directed there, to turn from the holy commandments,
and deny obedience to the righteous One.
May the Lord give you a true sense and repentance, if it be his holy pleasure,
and raise you out of this world`'s spirit, to live unto him in his own pure Spirit.
It is easy to profess and make a show of truth, but hard to come into it.
It is very hard to the earthly mind to part with that which must be
parted with before the soul can come to possess and enjoy it.
Profession of truth without the life and power is but a slippery place,
from which men may easily slide.
Indeed, if men are not in the life and power,
they can hardly be kept from that which will stain their profession.
The Lord, who searches the heart, knows how it is with you.
Oh, consider your ways, and fear before him, and take heed of taking his name in vain,
for he will not hold such guiltless!

I am, in this, faithful and friendly to your soul, desiring its eternal welfare,
and that it may not forever perish from the presence and power of the Lord,

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

God breathed into man the breath of life,
and man thereby became a living soul to God, to whom, by transgression, he died.
But Christ (who was before Abraham, and, in due time,
took up that body prepared by the Father) is the resurrection and the life, who,
from the Father, breathes life into man again, and so he comes to live again.
And man, being quickened by Christ, is to rise up from the dead,
and travel with Christ into the land of the living.
And Christ is all to believers, in whom dwells all fullness.
The circumcision is in him, the baptism is in him, the righteousness, rest,
and peace also are in him; yes, in him are all the treasures of wisdom and knowledge.
Truly Christ is made unto those that believe in him, wisdom, righteousness,
sanctification, and redemption.

Now, it is very precious to feel this,
but of little value to imagine or comprehend apprehensions about this.
For the end of words is to bring men to the thing itself, but the Scribes and Pharisees,
by their apprehensions upon the words given forth by the Spirit,
missed the thing (though they thought they did not miss,
but rather were blessed in their knowledge of the law).
This same spirit is alive in many that profess truth now, who,
by their understanding of Scripture words are kept from
the thing of which the Scriptures testify.
What did Christ come in the flesh and suffer for, but to unite and reconcile to God?
And what is the anti-christian way of erring from the truth,
but to extol the appearance of Christ in the flesh, his sufferings, resurrection,
ascension, etc.,
in that spirit wherein the true union and reconciliation is not witnessed?
If we receive the light, and walk in the light, as God is in the light,
then we have a share in his Son`'s death and atonement,
and his blood cleanses us from unrighteousness, but not otherwise.

Oh that all who truly desire salvation, might know the way here,
and receive from God that which cleanses and keeps clean!
Amen.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Dear Friend,

I received your letter kindly,
and in the tenderness of love which desires your enjoyment of the Lord in this world,
and the eternal welfare of your soul with him forever.

It is a great matter to have the mind rightly guided to that wherein God appears,
that the soul may wait at the posts of wisdom, to hear wisdom`'s voice.
And what says wisdom to he that hears and observes her voice?
"`I will pour out my spirit unto you; I will make known my words unto you.`" Prov. 1:23.

You have read in the Scriptures of the kingdom of God, which,
Christ told the Pharisees, was within them.
In parables he also expressed what it was like--even like a grain of mustard seed,
like a pearl of great price, like a lost coin, or piece of silver,
like a treasure hid in a field, like leaven, etc.
Now, it is my desire that you might come to the discerning of this.
Is there any such thing in you?
Surely, there is.
Do you know it?
Are you in union with it?
Has it grown and enlarged in you?
Is there room made for it, and does it overspread your heart?

You say the covenant, the new covenant, is contained in the Scriptures.
There are, indeed, descriptions of the covenant in the Scriptures,
but the covenant itself is an agreement of life and
peace made with the soul in the Lord Jesus Christ,
upon believing in His power, and obeying His voice.
For thus says the scripture, "`Hear, and your souls shall live,
and I will make an everlasting covenant with you, even the sure mercies of David.`" Isa. 55:3.
Now, this is what the soul is to wait for--even to feel the
power of life breaking the bonds of death,
and opening the ear to the voice of God`'s Spirit.
Only then will the soul receive his impressions, and feel the new creation inwardly,
the new heart, the new mind, the new law of life,
written within by the finger of God`'s Spirit,
even the law of the Spirit of life in Christ Jesus.
And then this law is the inward rule,
even as the outward law was the rule to the outward Jews.

You think me somewhat too sharp and severe in my
sentence concerning the ministers of this day.
I have received great mercy, and I desire not to be sharp or severe towards any.
If, therefore, any such thing was written by me,
be assured it was in faithfulness to the Lord`'s requirings.
All sorts of Christians own Christ in words, but all do not distinguish, discern,
nor are subject to, the appearances of his Spirit and power.
Instead, many resist, gainsay, and oppose, through error and mistake,
till at length they come to hardness.
These are the builders who refuse the cornerstone.
The builders rejected Christ`'s appearance in the flesh, in the days of his flesh,
and the builders again refuse his appearance in Spirit, in this day of his Spirit.
Oh, that any who are tender among them might be sensible of it!
Then they might not draw down God`'s severity and sharpness upon their heads,
which if they do, it is not our joy, but a matter of grief to us.
Whatever is of God in any of them, my heart cannot help but own.
But many take that to be of God (that fear, that faith, that love, those prayers,
those hopes, that peace, that joy, etc.), which is not truly of him.
Oh, how precious is that light which truly and rightly
distinguishes! "`My sheep hear my voice.`"
The voice of the Shepherd distinguishes every deceit and every deceiver.

But whereas you say,
"`The spirits are to be tried by the Scriptures,`"
I have found it otherwise in my experience.
The Scriptures may indeed try words, but nothing can try spirits except for the Spirit.
"`I will know,`" said the apostle,
"`not the words of them that are puffed up, but the power.`"
Deceivers may come with Scripture words, but they cannot come with the true power of God.
Therefore, the Apostle John, who bade the believers to try the spirits,
told them they had an anointing from the Holy One, and pointed them to that. 1 John 2:20,27.
But who can judge this, except he that has the anointing,
and is taught by the Lord to try things by it?
This one knows how it tries,
and what a certain judgment it gives concerning the nature of things,
and concerning every voice and every appearance.
The Spirit of God searches all things, discerns all things,
discovers all things--every snare, every device of the enemy,
even the net spread ever so secretly.
Blessed are they whose eyes are opened and kept open by him.

Oh, wait to know that wherein the Lord inwardly appears!
And take up the cross of our Lord Jesus Christ to everything that is contrary to God,
so that it all may be crucified in you,
and that your soul may live in the abundance of life and peace.
And be not discouraged because of any weakness, or because of your age.
Your weakness is not your disadvantage, but rather your advantage,
for the weaker you are in yourself,
the fitter you are to have Christ`'s power revealed and manifested in you.
Only wait to know that wherein God appears in your heart, even the holy seed,
the immortal seed of life, that it may spring up in your heart, and live in you,
and gather you into itself, and leaven you all over with its nature.
Then you will be a new lump, and may walk before God,
not in the oldness of your own literal knowledge or apprehensions of things,
but in the newness of his Spirit.

May the Lord appear to you,
in the light and demonstration of his Spirit in your heart and conscience.
May he touch you, quicken you, lead you,
guide and make you sensible of every appearance of his,
so that no motion or drawing of his Spirit may be quenched in you,
nor any motion of the contrary spirit, under any deception, be hearkened to.
Then you may travel on faithfully,
and come to the end of your travels with joy and full peace,
reaping the sheaves in life everlasting, of all that you have sown to the Spirit.

This is the earnest and single desire of my soul for you,
who am your true and faithful friend, and a hearty well-wisher to you and yours,

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Ruth Palmer

[.salutation]
My Dear Friend,

Whose love I am sensible of, and to whom I entirely wish well,
and desire that you may purchase and possess the pearl of great price,
and so know and enjoy Christ Jesus, the Lord,
and witness him to be eternal life to your soul.

I received a letter from you, which occasions my writing to you.
With regard to election, we do believe it, according as the Lord has taught us,
and as the Scriptures express it.
But such an election as shuts out any from the
salvation that God has prepared for the sons of men,
we cannot own,
because the Scriptures expressly testify that God "`would have all to be saved,
and come to the knowledge of the Truth.`"
Yes, we also know it to be his nature.
It is the nature of the destroyer to destroy--he would have none saved.
But it is the nature of God, the Savior, to save--he would have none perish.
There is indeed a "`making the calling and election
sure,`" but there is first a coming into the elect seed.
And, as we are chosen in him,
and come into him (out of darkness into his marvelous light, out of death into his life),
so we must abide in him, for the promise is to the one that continues unto the end.

As for that place of Rom. 11, it is manifest that there is an election,
and that this election is not of works, but of grace.
Yet, there must be a hearing of the voice; "`Today,`" said the apostle,
"`if you will hear his voice,`" etc.
So there must be a coming to Christ, and an abiding in him,
and a walking in the strait way, for this is the way God chooses.
God has chosen Christ, and the soul in him,
and the message is to invite all to come to him, and abide in him to the end.
The condemnation is upon rejecting him,
and the salvation is to them that receive him--which is not of man`'s self either,
but men are made willing so to do in the day of God`'s power.
And this power is not far from any, or lacking to any,
in the way that the Lord has appointed it.

The falling away is not because persons were not elected,
but because they let in that which is contrary to the election, and they cleave to it.
So there is the "`heart of unbelief,`" in which men depart from the living God,
and make shipwreck of faith and of a good conscience,
and the ground of their falling is their hearkening not to the Lord,
but to the voice and temptations of the enemy.

Yes, there are called, and faithful, and chosen.
These are states to be come into, and abode in.
Many may be called who never come to be faithful, nor chosen.
To witness the peculiar choice of God, this is precious,
and then one should not be content with a touch of the calling,
or a touch of the election, but rather to "`make them sure.`"
There is no choosing except in the seed, so if you make sure of that seed,
you make both your "`calling and election sure.`"
For indeed, "`many are called, but few chosen.`"
And yet, when a man comes so far as to know himself chosen, is he quite out of danger?
Did not Paul know his election sure?
Yet, was he not afterwards careful "`lest,`" says he, "`when I have preached to others,
I myself should be a castaway.`"

You say, "`Whom God once loves, he loves to the end.`"
Did he not once love all men, even the whole world?
Did he not manifest it in sending his Son for them?
And they that come into his Son, they come into his love.
They that come into his love must continue in his love and in his goodness.
For, it is not persons ("`God is no respecter of persons`"), but the seed, God loves.
"`In your seed shall all the families of the earth be
blessed,`" and in that seed they are loved,
and continuing there, they continue in the love.
It is true, God`'s grace appears, and thereby many are gathered.
And when any fall, the grace of God appears again, and thereby many are restored.
But if any become hardened by "`the deceitfulness of sin,`" that they
hearken not to the voice of grace when it comes to restore,
are they restored by it?
Indeed, God`'s compassion did not fail to Israel of old, nor to Israel now,
yet were not many consumed then, who, though they came out of Egypt, yet rebelled,
and lusted, and tempted Christ, etc., and so were destroyed by the destroyer?
And so, let none make shipwreck of faith now, for it is by faith that any stand,
as the apostle expresses in Rom. 11:19-22. Read, and consider.
And the apostle, in a true sense of things, cries, "`Oh, the depth!`" etc.
Love in severity, mercy in severity!
If it be stopped one way, it will break forth more abundantly in another way.
And, "`who has known the mind of the Lord,`" or given him counsel,
which way he should manage his love and mercy? Romans 11:33-34.
Indeed, all salvation is to be ascribed to God,
and is ascribed to God by all that receive salvation from him.
But still, God saves in the way he has appointed (in man coming into the way,
in abiding in the way, in walking in the way).
Here alone is safety; but out of it is death and destruction forever.

All our best righteousness is as filthy rags, it is true.
However, the gift of God is not as filthy rags;
the righteousness of his Son revealed in the heart is not as filthy rags.
The pure offerings and incense which are offered up to
God in the times of the gospel are not as filthy rags.
Oh, what a state of blindness many are in that they cannot distinguish
between what is of themselves and what is of God in them!
And so they cannot avoid offering up a corrupt thing,
nor can they offer up that which is holy and pure, even the holy sacrifice,
with the holy fire, upon the altar of God!
Consider the 3rd chapter, 3rd verse of Malachi, and tell me, if you know,
what an offering in righteousness is, and whether it be as filthy rags, or no.
Consider that place, John 3:21, "`He that does the truth comes to the light,
that his deeds may be made manifest, that they are wrought in God.`"
And what are those deeds that are wrought in God?
Is not God holy and pure?
And is anything wrought in him except what is holy and pure?
Therefore, we should wait rightly to distinguish things,
and not jumble the precious and the vile together, as if they were all one.

As for a method of speaking, I have none of my own,
but wait for the method and words which God`'s wisdom teaches.
Indeed, when I speak of the light, and the life, and the power, I do mean Christ Jesus,
who is the light, life, and power,
but it is a great matter to come to know him so revealed in the heart.
For where he is so revealed, darkness, and death, and the power of Satan,
are scattered and put to flight by him.
Yes, Satan falls like lightning before the power of his kingdom, where it is revealed.

This is a blessed experience, and these know Christ indeed.
The Lord grant that you may so know him,
which is the hearty desire of your soul`'s true and faithful friend,

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Joseph Wright

[.salutation]
Dear Friend,

I entreat your son to acquaint my brother Arthur,
that I took very kindly and was very glad of his affectionate expressions towards me.
I have been somewhat concerned that, though my religion had enlarged my love towards him,
yet his religion might have diminished his to me.
I bless the Lord on his behalf that he enjoys his health so well.
And for myself, though I have been exceedingly weak formerly,
yet the inward life and comfort which the Lord daily is pleased to administer to me
increases the health and strength of my natural man beyond my expectation.
Blessed be my tender and merciful Father, who has visited one so distressed, miserable,
and helpless as I was for so many years!

And whereas he says he is like me in speech,
but most unlike me in opinion--I pray tell him from me,
that my religion does not lie in opinion, but in that which puts an end to opinion.
I was weary and sick at heart of opinions,
and if the Lord had not at last brought to my hand that which my soul so needed,
I would have never meddled with religion more.
But as I felt that in my heart which was evil and not of God,
so the Lord God of my life pointed me to that of
him in my heart which was of another nature,
teaching me to wait for and know his appearance there.
And in subjection to this,
I now experience him stronger than the strong man that was there before,
and by his power,
he has separated me from that within which separated me from him before.
And so being separated,
I truly now feel union with him and his blessed presence every day, which,
what this is unto me, my tongue cannot utter.

I would be glad, if the Lord saw good, that I might see my brother before I die,
and if I did see him, I would not be quarreling with him about his religion,
but rather embrace him in brotherly love, and in the fear of the Lord.
As for his being a Roman Catholic, that does not damp my tender affection to him.
If he be a Catholic, I had rather have him be a serious than a loose Catholic.
If he has met with anything of that which brings forth a holy life in him, then he has,
that far, met with something of my religion, which teaches to order life aright,
in the light, and by the Spirit and power of the Lord Jesus.
My religion is not a new thing,
though it is newly revealed more fully than in many foregoing ages.
Truly it consists in that which was long before the Romish church was,
and will continue when it shall be no more.
And he that would rightly know the true church must
know the living stones whereof the true church is built,
against which the gates of hell cannot possibly prevail.
Oh, the daily joy of my heart in feeling my living membership in this church!
Here the true "`gold,`" the "`white raiment,`"
the pure "`eye salve`" (with which the eye,
being anointed, sees rightly), are received and enjoyed inwardly,
by such as the world knows not, but rather despises.
Blessed be the name of the Lord!

I desire my sincere, entire affection, as in God`'s sight,
may be remembered to my dear brother,

[.signed-section-signature]
I+++.+++ P.

[.asterism]
'''

[.blurb]
=== The following testimony was written by Mary Penington, the wife of Isaac Penington, upon the death of her dear husband in 1679.

While I keep silent concerning you (oh you who are blessed of
the Lord and his people!) my heart burns within me.
I must make mention of you, for you were a most pleasant plant of renown,
planted by the right hand of the Lord.
Indeed you took deep root downwards, and sprang upwards.
The dew of heaven fell on you, and made you fruitful,
and your fruit was fragrant and most delightful.

Oh, where shall I begin to recount the Lord`'s remarkable dealings with you?
He set his love on you, oh, you who were one of the Lord`'s peculiar choice!
Your very early childhood days declared of what stock and lineage you were.
You desired the "`sincere milk of the word as a
newborn babe,`" even in the bud of your age.
And who can declare how you had traveled towards
the Holy Land in the very infancy of your days?
Who can tell what your soul felt in your travel?
Oh the heavenly, bright, living openings that were given you!
God`'s light shone round about you.
Such a state as I have never known of in any other, have I heard you declare of.
But this it did please the Lord to withdraw, leaving you desolate and mourning,
weary of the night and of the day, naked and poor in spirit, distressed and bowed down.
You refused to be comforted,
because you could not feed on that which was not bread from heaven.

In that state I married you.
My love was drawn to you, because I found you saw the deceit of all notions.
You remained as one who refused to be comforted by
anything that had only the appearance of religion,
until he came to his temple who is truth and no lie.
For all those shows of religion were very manifest to you,
so that you were sick and weary of them all.

This little testimony to your hidden life, my dear and precious one,
in a day when none of the Lord`'s gathered people knew your face,
nor were in any measure acquainted with your many sorrows, have I stammered out,
that it might not be forgotten.
But now the day has broken forth, and you were so eminently gathered into it,
and a faithful publisher of it.
I leave this other state of yours to be declared by the sons of the morning,
who have witnessed the rising of the bright star of righteousness in you,
and its guiding you to the Savior, even Jesus, the First and the Last.
Let those speak, who are strong, and have overcome the evil one,
and are fathers in Israel.
You have declared of your life in God, and have published it in many testimonies.

Ah me, he is gone!
He that none exceeded in kindness, in tenderness,
in love inexpressible to the relation of a wife.
Next to the love of God in Christ Jesus to my soul,
was his love precious and delightful to me.
My bosom one!
My guide and counselor!
My pleasant companion!
My tender, sympathizing friend, as near to the sense of my pain, sorrow,
grief and trouble, as it was possible!
Yes, this great help and benefit is gone, and I, a poor worm,
compassed about with many infirmities,
through mercy was enabled to let him go without an
unadvised word of discontent or inordinate grief.
And such was the great kindness the Lord showed me in that hour,
that my spirit ascended with him the very moment the spirit left his body,
and I saw him safe in his own dwelling place, and rejoiced with him there.
From this sight my spirit returned again, to perform my duty to his outward tabernacle.

This testimony to Isaac Penington is from the
greatest loser of all who had a share in his life.

[.signed-section-signature]
Mary Penington
