[#root-struck, short="The Root of Popery Struck At"]
== The Root of Popery Struck At, / and the True Ancient Apostolic Foundation Discovered;

[.heading-continuation-blurb]
In some propositions to the papists
concerning _Fallibility_ and _Infallibility_
which cut down the uncertain,
and manifest the certain way of receiving and growing up into the truth.

[.heading-continuation-blurb]
Also some _Considerations_ concerning the True and False _Church_ and _Ministry_,
with the State of each since the days of the _Apostles_,

[.heading-continuation-blurb]
Held forth in true Love and Pity to the Souls of the _Papists,_
that they may Hear and Consider and not Mistake and Stumble at the _Rock of Ages,_
whereupon the _Prophets,_ _Apostles,_
and whole _Flock_ of _God_ throughout all Generations, have been built.

[.heading-continuation-blurb]
There is likewise somewhat added concerning the _Ground_ of _Error,_
and the Way to _Truth_ and _Unity,_
for the Sake of such as are more Spiritual,
and have been more inwardly exercised in searching after _Truth._

[.section-author]
By _Isaac Penington,_ the Younger

[quote.section-epigraph]
____
In vain do they worship me, teaching for Doctrines the Commandments of Men.
Matt. 15:9
____

[.section-date]
1660

=== Preface

The mystery of iniquity (which overspread the earth
under the shape and appearance of holy church,
and holy worship) did begin to work in the apostles`' days. 2 Thess. 2:7.
And this was the way whereby the god of this world did deceive;
he endeavored to blind men`'s minds, to put out their right eye, 2 Cor. 4:4.
to draw from the Spirit, from the anointing, 1 John 2:26,
to rob of the eye-salve wherewith the eye must be anointed to see the things of God, Rev. 3:18.
And now when he hath done this,
how easily may his false ware pass for true!
His synagogue (built in the likeness of the true church, Rev. 3:9),
for the true church!
Antichrist, his son (sitting in the temple like Christ, 2 Thess. 2:4),
for the true Christ!
His doctrines, for the true teaching! Matt. 15:2.
His feigned, formal, dead, earthly traditions, for the true,
everlasting gospel! Rev. 14:6.
His Gentiles, or Heathens (who are so in nature,
and Christians only in name), for the true Christians! Rev. 11:2.

"`The light of the body is the eye,`" saith Christ, by way of parable. Matt. 6:22-23.
Now if the eye be dark, "`if the light which is in thee be darkness,
how great is that darkness!`" How shalt thou see the gospel, the church, the Spirit,
the things of God?
But if that eye be clear, who shall be able to blind thee?
The devil may come with his deceits, his false church, his false gospel, his false power,
etc., yea, though his spirit creep into the very true form of godliness,
thou wilt be able to discern him there.
But if thou see with another`'s eye, thou mayst easily see amiss, mistake Christ,
mistake the church, and so believe as the false church believes,
and fare as the false church fares.

Oh! who shall redeem the deceived nations back to the Spirit?
Who shall preach to all nations, kindreds, tongues, and people, the everlasting gospel?
Who shall open the eye in them which hath been so long blinded?
Who shall take the golden cup of fornication from their lips,
and loosen their hearts from the sorceries, flatteries,
and enchantments of the false woman?

The everlasting bowels of the Lord roll toward his poor captivated seed,
and towards the poor deceived nations;
and he is now preparing to build the ruins of many generations.
He is bringing forth that power of truth,
that demonstration of his Spirit in the spirits of his people,
as no paint shall be able to stand before.
He will rend the veil of the covering from off all nations,
and the Desire of all nations shall be seen by the eye which he opens and anoints;
and that which hath deceived, and destroyed, and led from the truth,
building up a mystery of unrighteousness in the stead of it;
even the beast and false prophet (which wrought miracles,
with which he deceived them that had the mark of the beast,
and them that worshipped his image), shall be taken, and cast alive into the lake, Rev. 19:20.
Then captivity shall be led captive;
and those which have been led captive shall creep out of their dens,
and out of their holes, into the light of the living,
and worship the true and everlasting King, when the king Abaddon is destroyed. Rev. 15:2-4.

Oh! who shall be accounted worthy to be taught by the Lord where to wait for this?
To whom will the Lord discover the place of wisdom (the place where wisdom is learned,
her voice heard, and her instructions to life received),
which is hid from the eyes of all living? Job 28:21.
Whom shall he teach knowledge?
And whom shall he make to understand doctrine?
They are them that are weaned from the milk,
and drawn from the breasts of the false woman.
Isa. 28:9, and chap.
52:15. They that are turned from man, from the fleshly wisdom in themselves,
towards the spring of life, they may hear the voice of this wisdom,
which begins in the living fear and power;
which effectually turns the heart from death and darkness towards the living God;
to worship him in spirit and in truth, according to the pure, living teachings thereof;
and not after the inventions, imaginations, and traditions of men:
and he that is once come hither, as he is true and faithful to the light of life,
doing the will as it is made manifest to him, shall know more and more of the doctrine, John 7:17.
and have his feet infallibly guided into, and preserved in,
the way of peace.

=== The Root of Popery Struck At

[.numbered-group]
====

[.numbered]
_Proposition I._ That councils may err
(if I should add, and have erred, it might not be impossible to prove it).

_First,_ In that they are men not perfected in the knowledge, faith,
and obedience of the truth, it necessarily implies a capacity of error,
both in relation to the knowledge, to the faith, and to the obedience.

_Secondly,_ Their doubtful disputation of things, and long canvassing,
imply an uncertainty, and possibility of erring.

_Thirdly,_
Their way of determining things at last (which is by a vote
of the major part) is an uncertain way of determination;
for it is not impossible but the major part may be over-swayed by by-ends,
and in relation to their own advantage and interest,
against the righteousness and equity of the reason of the lesser part:
so that the way of determining things by a council is not a certain way in itself;
but because men know not well how to find out a better
and more probable way of deciding controversies,
they judge it necessary to acquiesce therein.
But the votes and determinations of men concerning a thing
do not conclude a thing to be true or false in itself;
they only signify their opinion, judgment, and testimony concerning the thing,
the validity whereof depends upon their knowledge of the thing; which if it be not clear,
full, and certain, their testimony, opinion, or judgment is of little value.
Truth remains the same in itself,
though all the wise men in the world should testify against it, calling it error,
or heresy; and falsehood can never become truth,
though ever so many wise men should testify for it,
putting the fairest habit and appearance of truth upon it that they can.

[.numbered]
_Proposition II._ That the pope himself may err.

The pope hath not greater freedom from fallibility
in judgment or doctrine than Peter himself had.
Now Peter had not only a capacity of error in him,
but he did err in that doctrine which he taught the Gentiles,
of living after the manner of the Jews; for he did not only do the thing itself, Gal. 2:12.
but he compelled the Gentiles to do the same thing,
holding it forth as a practice which ought to be observed by the Gentiles,
ver. 14. for which carriage of his, Paul withstood him to the face, and said,
"`he was to be blamed,`" ver. 11. And the council of Constance, deposing pope John,
and advancing the authority of councils above the pope,
did plainly imply that the pope might err;
which might further be confirmed by what the council
of Basil determined concerning pope Eugenius.

[.numbered]
_Proposition III._ That every man may err in his interpretation of scriptures,
further than he hath a certain and infallible opening of them to his spirit,
by that Spirit which gave them forth.

The Spirit knoweth his own mind in every word which he hath spoken;
but no man knoweth his mind, nor the meaning of his words, but as he reveals them. 1 Cor. 2:11.
So that God is true in all his sayings in the scriptures;
but man is a liar in all the meanings he gives of his sayings,
according to his own guessings, reasonings, and imaginings,
without the Spirit`'s infallible opening of his own words to him.
So that the Spirit itself is the ground and foundation of
all true light and knowledge of the things of God.

[.numbered]
_Proposition IV._ That if there be any light to be found any where shining from God,
that light cannot err: for God is pure;
and that which comes immediately from him cannot but be pure.
All the knowledge which man gathers, or can gather, into his vessel, he may pollute;
but what issues from the spring is pure, and of a perfect nature. James 1:17.

[.numbered]
_Proposition V._
That there must necessarily be such a light communicated to all men since the fall,
that they may believe thereby, come to the knowledge of the truth, and be saved;
which I prove thus:

1+++.+++ From the will of God.
The apostle saith expressly, that "`God would have all men to be saved,
and to come unto the knowledge of the truth.`" 1 Tim. 2:4. Why then
there must necessarily be somewhat dispensed from God to all men,
sufficient to bring them to the "`knowledge of the truth,`" that they may be "`saved.`"

2+++.+++ From what is found in man.
There is found in man a light shining in his darkness, John 1:5.
a light discovering the darkness, and drawing from it;
somewhat which checks and reproves the sinner,
but never consented to the evil of his heart and ways.
This is of God; this is from God; this is pure; this is spiritual; nor of the fleshly,
not of the natural;
for then it might be drawn some time or other to
consent to some of the corrupt desires of the natural;
but though the conscience be ever so much defiled,
yet the light in itself can never be defiled.
Indeed a man may set up that for light in his conscience, which may be darkness;
but God`'s light, God`'s witness there, can never be bribed, but will speak truly,
(when God at any time awakeneth, or raiseth it up) witnessing for him,
both against the evil of the man, and against the searedness, hardness,
and unfaithfulness of his conscience towards God.

[.numbered]
_Proposition VI._
That this being let in, believed in, and obeyed, shineth more and more unto the perfect day;
even until it hath wholly brought out of the error into the truth.

Every way of it is infallible, and every step of the creature after it is infallible.
Indeed the creature`'s reasonings and consultations about it may be fallible;
but the light is infallible in itself; and so far as there is a pure, simple,
naked thing begotten by it (for it is of a begetting nature, James 1:17-18),
so far there is an acknowledgment of its certainty in the creature.
There are some things that all the men of the earth certainly know to be evil,
by means of its shining; and some things also that they certainly know to be good;
and at some times there is a will begotten in them towards the good,
and against the evil: now if they did honestly wait in the singleness of this will,
breathing to the God of power to have it brought to victory in them,
the light would shine more and more from his presence; and in the light,
the power and saving arm would arise;
which would effectually lead out of the death and captivity,
into the fellowship and freedom of the life.

[.numbered]
_Proposition VII._
That nothing less can lead unto eternal life than an eternal light in man`'s spirit,
where the darkness is; which is to be discovered there, subdued there, and to be led from.

This was the apostle`'s message (who received and came with the message of the gospel),
"`that God is light,
and in him is no darkness at all.`" 1 John 2:5. And this
they preached to bring men into fellowship with this light,
ver. 3. that they might walk with God in it,
and there be cleansed by the blood of Jesus through it.
ver. 7. Which that they might obtain, they must first be turned from darkness to it,
Acts 26:18, and from the power and kingdom of Satan to the seed of the kingdom of God, Matt. 23:31.
which Christ told the Pharisees was within them. Luke 17:21.
And the Apostle Paul told the Hebrews, that the laws of the covenant,
whereof Christ was the Minister and Mediator, were by the tenor of the new covenant,
to be written in the heart and mind by the Spirit; and not to be written outwardly,
as that covenant was which God made with the Jews by Moses, Heb. 8:6,
etc. which was not the eternal covenant itself, but a shadow of it;
which made nothing perfect, but only made way for the hope of a better covenant,
by which believers draw nigh to God. Heb. 7:19.
Yea, Moses himself tells the Jews, that the commandment of life,
the Word Eternal (according to faith wherein, and obedience whereto,
they were to live or die eternally) was within them. Duet. 30:14-15.
And Paul tells the church at Rome,
that this was the word of faith which they preached;
that it was also the covenant of life and death under the gospel. Rom. 10:8.
Christ is the light of the world, John 8:12. or the Eternal Word, John 1:1.
which Light or Word speaks within every man`'s conscience.
He that believes in it, brings his deeds to it, and obeys it, is justified by it;
but he that hates its reproof, is condemned by it, John 3:20-21.
and not only shut out of life, but out of the very ways to it;
for the reproofs of the instruction of this wisdom
are the sole way or path of life to the sinner. Prov. 6:23.

====

Now behold the true certainty of the everlasting foundation,
and behold your own uncertainty.
See the Rock of ages, whereupon the prophets, apostles,
and all the saints have been built.
See that which indeed is infallible; and cease from man, who is vain,
and subject to vanity and error.
The church of the Jews did err; the churches of the Gentiles also did err,
even in the apostles`' days; insomuch as their candlestick was threatened to be removed,
and was soon removed; yea,
the apostle particularly foretold the saints at Rome concerning the Gentiles,
that their standing was by faith; and that if they continued not in God`'s goodness,
they should also be cut off, as the Jews were. Rom. 11:20,22.
Now there was not a standing in the faith, but a general backsliding,
and falling away from the faith; and then the man of sin was revealed,
and Christ and his truth withdrawn; strong delusion, deceit,
and false appearances of truth starting up instead thereof. 2 Thess. 2:11-3.
For the Lord God,
upon the great defection and apostasy of the Gentiles,
separates the outward court from his temple, altar, and spiritual worshippers;
which temple was his true church, which he reserved for himself,
giving the outward court to the Gentiles. Rev. 11:1-2.
And then the true church fled into the wilderness,
where she had a place prepared of God for her;
and so the Gentile-Christians could build up their false churches in the
cities or palaces where the true church had been built by God,
and appeared before.
And these false churches may easily become much larger than the true church ever was;
for while the Lord built the church by his Spirit, he built only of spiritual stones, 1 Pet. 2:5.
adding to it such as he first converted. Acts 2:47.
For such alone are fit to worship him in Spirit and truth,
and such alone he seeks out to make up his church of, instead of the Jews,
whom he had cast off from being a church and people to him. John 4:23.
But when man comes to build, he takes in more largely than God allows;
he may gather in or force a whole city or nation to become a church,
by persuading or compelling them to receive the doctrine and tradition which he prescribes,
and be setting up an outward knowledge, policy, and government, according to man,
and in the wisdom of man, which the human part will answer to, and be satisfied with.
To make this a little more manifest to such as in simplicity
of heart desire to know the mind of God in this respect,
and the true state of the church since the days of the apostles,
consider these things following:

[.numbered-group]
====

[.numbered]
1+++.+++ God, in those days, sent his true apostles and ministers with the everlasting gospel,
which was the word of faith which they preached, to gather men of Jerusalem, Judea,
and all nations, into the obedience of the faith, Rom. 1:5.
that he might have a spiritual house, a spiritual people, to worship him,
instead of those outward worshippers whom he then cast off. John 4:23.

[.numbered]
2+++.+++ That this gathered people in Judea, at Jerusalem, at Corinth, at Ephesus, at Coloss,
at Philippi, at Rome, etc. were his several churches or congregations;
and not the city of Jerusalem, not the city of Corinth, Ephesus, Rome, etc.
None of these were churches; but only a select remnant gathered out of these.

[.numbered]
3+++.+++ That the devil, after he had stirred up the Jews everywhere,
and the heathens as much as he could, to cry out against the truth,
and such as God had converted to the faith, for heresy and a sect,
and to persecute them and it, yet could not prevail that way; then he tried another way,
sending his messengers abroad, clothing them as angels of light;
teaching them also to preach Christ, and the doctrine of the gospel;
and so transforming themselves under this color, secretly to sow the seeds of division,
error, and heresy in the church.

[.numbered]
4+++.+++ When this would not do,
but these were discovered and judged (by the power and presence
of the light of the Spirit in the church) for false Jews,
false apostles, deceitful workers, ministers of Satan, etc., Rev. 3:9. and chap.
2:3. then they separate themselves from the church,
Jude 19. and make up a body of their own, go out into the world, preach there,
gather a company there, get the greater number, and then set upon the church,
fight with her, overcome her and her ministry,
and get up their own false church and ministry.
Thus the synagogue of Satan and his ministry got footing in the world,
even in the very same cities and places where the church had newly had dominion before.
And now, whereas before there was a church at Jerusalem, a church at Rome,
a church at Ephesus, etc., when the synagogue of Satan is set up,
and hath got the dominion there, the whole city of Jerusalem, or the whole city of Rome,
etc. can then become a church.
To make this yet more manifest,
observe and weigh these things following in the balance of the true sanctuary:

====

[.numbered-group]
====

[.numbered]
1+++.+++ The false prophets, the false apostles, which had crept into the church,
Jude 4. which strove to seduce the church, 1 John 2:26. these went out from the church,
ver.19. and went into the world. 1 John 4:1.

[.numbered]
2+++.+++ When they went out into the world,
their intent was to leaven the world with their doctrine,
and to gather people after them.
They preached to gather people to them, and their doctrine, and form of godliness,
as the apostles preached to gather people to God, and his living truth.

[.numbered]
3+++.+++ The world heard them; they hearkened to their doctrine;
were willing to be gathered by them, owning their false ministry, and their false church,
or synagogue; even as those that were of God hearkened to the apostles,
and owned the truth. 1 John 4:6.
So that here were now two distinct bodies
in cities and places where the gospel had come:
a body of the true saints and true apostles; a body of the false apostles and ministers,
of the deceitful workers, who showed miracles and wonders,
and had all manner of deceivableness of unrighteousness on their side. 2 Thess. 2:10-9.
Thus there was a great division and
breach in the places where the gospel had been preached,
and had reigned in power: for he that was of God heard the true apostles,
and kept to the true church; but those that were not of God, but of the worldly spirit,
heard the false apostles and false ministers, and so joined to the synagogue of Satan, 1 John 4:6.
where Satan had his seat and dwelling, Rev. 2:13.
even as Christ dwelleth and sitteth in his temple, the church.

[.numbered]
4+++.+++ These false apostles and ministers, with the help of the world,
which they had gathered in unto them,
joined together against the true church and her seed (as
wherever the two contrary spirits and principles appear,
they cannot but contend and fight against each other;
the one for the faith and truth of the gospel; the other against that which is true,
and for a counterfeit of it); so, Rev. 12.
there is Michael and his angels fighting on the side of the true church;
there is the dragon and his angels fighting for the false church.
Now mark who prevails: the true church, Michael and his angels, prevail one way;
the false church, the synagogue of Satan, the dragon and his angels, prevail another way.

====

[.discourse-part]
Question.
How doth the true church prevail?

[.discourse-part]
Answer.
Thus: she keeps all the spiritual, invisible,
holy things of God from the paw of the dragon, and of all those false worshippers.
The invisible Jew, the invisible life and power,
that whereof God had built up his church, is preserved by him;
and against his life and Spirit, and his church (which he builds by his Spirit,
and preserves in it), all the powers of darkness cannot prevail;
but do they all what they can, the man-child is caught up to God; and the church,
by God`'s help, flies from the face of the dragon into the wilderness,
where she is fed forty-two months, or twelve hundred and sixty days,
which is the time of the dragon`'s prevailing outwardly,
by his false church and ministry.
Rev. 12.

[.discourse-part]
Question.
How doth the dragon and false church prevail?

[.discourse-part]
Answer.
By putting the man-child and true church to flight; by gaining the church`'s ground,
setting up his synagogue (or false representation of the
true church) where the true church had stood before.
For the true church being fled into the wilderness, the field was left to him;
and there he sets up his false synagogue, in the sight of the world,
calling her the true church, and her seed the true catholics;
but casting a flood of reproach after the woman,
reviling her (who indeed was the true church) for a strumpet,
and all her seed for seducers, schismatics, heretics, etc.,
even such as were not fit to be suffered in the earth, but to be made war with,
both by the spiritual and civil sword. Rev. 12:15,17.

Thus then was the victory on each hand:
the true church and temple (with the inward power of life) was preserved by God;
who caused it, by the wings of his Spirit,
to fly out of the sight of false worshippers and imitators,
as far as that is from the sight of men in a city,
which flieth out of the city into a wilderness.
And to the other is left the outward court to worship in; the profession, the attire,
the garments,
the visible observations and practices wherein the church before had appeared,
and in which she did once truly and spiritually worship;
for the church did acceptably worship in the outward court,
before it was measured and divided from the inward temple, and given to the Gentiles. Rev. 11:2.

[.discourse-part]
Question.
Now how long was this false church to stand?

[.discourse-part]
Answer.
Till the church`'s coming out of the wilderness in the same
Spirit and power wherewith she fled into the wilderness.
When Christ comes with the fiery breath of his mouth,
and with the brightness of his eternal light,
then this false image of the church melts and dissolves away. 2 Thess. 2:8.
But till then she keeps her seat on the beast; on whom she rides,
and by virtue of whom she sits upon the waters, even upon peoples, multitudes, nations,
and tongues.

[.discourse-part]
Objection.
But did not Christ say the gates of hell should not prevail against his church?

[.discourse-part]
Answer.
No more they did not: for she had wings of an eagle given her,
to fly into the wilderness; into the place prepared of God for her;
into which she did fly, and was there fed and preserved,
do all the powers of darkness what they could.
So that the dragon and his angels prevailed not against the woman;
but she was hid from the face of the serpent, and from all his spite and power,
who could not come within the bounds of her heaven in the wilderness,
but was cast out into the earth, and his angels with him. Rev. 12:8-9.
But Christ did not say that the gates of
hell should not prevail against her outward estate;
but the contrary, in this very prophecy of John, is here declared; to wit,
that she was so far prevailed against: the true woman, who was "`clothed with the sun,
and had the moon under her feet,
and was crowned with a crown of twelve stars,`" was to fly away, and give place;
and a false woman to start up in her stead; who, with the golden cup of her fornications,
was to deceive and bewitch all nations, kindreds, tongues, and languages,
forty-two months, or twelve hundred and sixty days,
which was the full time the church was to remain in the wilderness:
but after that time the false church,
with antichrist her husband (who all this while sat in the temple), was to be revealed,
judged, and destroyed,
and the true church return again out of the wilderness into her own place.

[.discourse-part]
Question.
Why would God suffer his church thus to be prevailed against,
thus to be banished and driven out of the building which his Spirit had reared for her,
into a wilderness;
and a mystery of deceit and falsehood to be set up in her name and stead?

[.numbered-group]
====

[.numbered]
_Answer. First,_ As a just judgment upon the world (who slighted the day of their visitation,
and would not come into the vineyard to work), God brings the night upon them,
wherein they could not enter into the vineyard, nor work if they would ever so fain. John 9:4.

[.numbered]
_Secondly,_ As a just judgment upon such, who,
though they could not but own and acknowledge the truth,
yet did not love it in their hearts, but loved their unrighteousness,
their darkness still;
and lets out a power of darkness and deceit upon them, wherewith they were deluded,
instead of the truth itself. 2 Thess. 2:10-11.

[.numbered]
_Thirdly,_
That such as were approved might be made manifest in the Spirit to be pure gold indeed.
They that held the living truth, and could not be drawn aside,
with all the pleasures of this world on the one hand,
nor with all the dangers from it on the other hand; no,
nor yet with all the deceivableness of unrighteousness;
these did shine indeed in the light and power of the Spirit,
and were a great honor and crown upon the head of their Master.

[.numbered]
_Fourthly,_ That darkness might have its day, or hour,
or season of manifestation to the full.
There hath been no day of any dispensation hitherto,
but it hath had a night coming after it.
There was an antichrist to be revealed in the power of darkness,
as well as Christ (the eternal light of life) in the living power.
Now as long as the true church stood,
and as long as the man-child was found dwelling here with her,
in the habitation which God had built up for them, the man of sin could not be revealed,
but the pure power of life would soon discover him.
Therefore at length, when the full time and season of his discovery came,
God removed that into the wilderness which stood in the way; and then he and his spouse,
the false church, made a fair show in the world. 2 Thess. 2:7.

[.numbered]
_Fifthly,_ That the Lord might make the name of his Son,
with the glory of his truth and power, to shine,
by overcoming the dragon and this false church, after so long a time of thick darkness,
and after such a universal prevalency of the powers and deceits thereof.
Was it not a great glory and honor to the Lord, to overcome the heathenish world,
and Jewish church and worship,
by the power of his truth shining through a poor
despicable company of fishermen and mechanics?
And will it not be as great (if not a greater) glory to him to overcome
the antichristian world (after it hath taken so long and so deep root,
and is become so strongly founded) by as poor, contemptible instruments as they were?

====

[.discourse-part]
Question.
But how was it possible that so great a deceit should
get up in the world so near the apostles`' days,
or rather in the very days of the apostles, as this seemeth to be?

[.discourse-part]
Answer.
The false apostles and ministers came "`with all deceivableness of unrighteousness,
and with all power, and signs,
and lying wonders.`" 2 Thess. 2:10-9. And the power of
miracles in the true apostles might well cease;
for the end of miracles was but to testify to the world,
to be a sign to the unbelievers. 1 Cor. 14:22.
But now their work towards the world was well nigh finished,
and judgment was to come upon them for neglecting and despising the day of their visitation.
So that the power of deceit was let up in the false apostles,
and the power of truth did draw inwards in the true apostles,
which made it very easy for deceit to prevail.
Besides, the false apostles appeared in a higher appearance than the true apostles did,
with more glorious discoveries;
so that they could hold forth all that the apostles
did (as to the form and outward doctrine),
and more too, and could show wonders to confirm what they held forth further.
And now how could they choose but prevail over all that kept not close to the anointing,
which distinguisheth and discerneth not by any outward manifestation or appearance,
but by the savor of the ointment?
Yea, so great was the power of deceit in them,
that they drew the third part of the stars of heaven from their place,
into this earthly building; so that they fell from the true ministry,
and the true church, into this false church and ministry. Rev. 12:4.
How many then of the inferior and common sort were then drawn aside!

[.discourse-part]
Question.
Has there been no visible true church-state in the world since that time?

[.discourse-part]
Answer.
It is impossible for any to build a true church for God, but his own Spirit.
And if God removed the church which he built, into the wilderness,
it is impossible for all the men of the earth to build up another true one,
all that season that God appoints his church to abide in the wilderness.
Several sorts of men may attempt it,
and each may build up their different images of the thing;
but none can recover the thing itself, till the Lord by his Spirit (who first built,
and then pulled down) pity the dust of Zion, and raise up the tabernacle of David again.
Ps. 102:13. Isa. 2:2. Rev. 21:2-3.

[.discourse-part]
Question.
What is the wilderness?
Tell us; that the simple-hearted, who long after the truth, may know where to look for,
and how to find the true church.

[.discourse-part]
Answer.
It is not an outward place, into which the bodies of persons might flee;
but a parable to express somewhat inward by.
And it is under the feet of all the false worshippers,
who are worshipping in their several buildings, in the outward court.
That which they trample upon, keep down, and despise, is the holy city. Rev. 11:2.
And the place where the true church all this
while hath been (and yet in a great part is) is there.

[.discourse-part]
Question.
But if God`'s church hath not been in a built state,
but hath lain desolate in the wilderness ever since
antichrist and the false church got up,
what hath the estate of his people been ever since?

[.discourse-part]
Answer.
A state of witnesses. Rev. 11:3.
In every age God hath had two witnesses (which
was a sufficient number to confirm his truth by),
to witness to the power of his truth,
against the emptiness and corruption of the forms which antichrist had brought in,
instead of the living power; which witnesses were clothed with sackcloth,
giving forth their testimony with tears;
while they of the antichristian party were rejoicing in the glory, riches,
and beauty of their false church, as they could slay, suppress,
and keep down the witnesses.
Rev. 11:10 and chap.
18:7,9.

[.discourse-part]
Question.
What did the dragon do after this victory,
after he had got his building up in the outward court
(for after he had prevailed to corrupt it,
the Lord gave it to his worshippers, the Gentiles, Rev. 11:2.
those that made a profession of his truth, but were not true Jews, Rev. 3:9.
not of the inward circumcision, Phil. 3:3),
and had got the holy city under the feet of his worshippers?

[.discourse-part]
Answer.
He pursued his victory against the woman, and the remnant of her seed.
As for the woman, he cast a flood of infamy, of reproach after her,
that she might never be able to lift up her head again in the power of truth;
but what she caused to spring up might still be reviled for falsehood and heresy;
and that nothing might henceforth go for truth,
but what this false woman should determine to be so:
and as touching the remnant of her seed which still remained true to God,
keeping his commandments, and having the testimony of Jesus,
he applies himself now to wage the war against them. Rev. 12:15,17.

[.discourse-part]
Question.
How doth he wage the war against them?

[.discourse-part]
Answer.
He raiseth up a beast out of this sea of confusion and wickedness
(which ensued upon this great battle and victory on his side),
to whom he gave "`his power, his seat,
and great authority.`" Rev. 13:2. He had hitherto kept his seat in his synagogue,
where he had been slaying the faithful martyrs of Jesus, Rev. 2:13.
and had put to death such as loved not their lives unto death. Rev. 12:11.
Now he finds it more for his advantage to raise up this beast,
and to give his power, seat, and authority to him.
This was the Roman power; which, till it was thus depraved and enslaved by Satan,
was not a beast, but more noble and just in government than the corrupted Jews were;
but now it becomes a beast;
and this beast he stirs up against the very name and form of godliness,
that he might root out the very appearance of Israel from off the earth:
for he got but into the form, to eat out the power; and now, seeing the power is removed,
it is for his advantage also to corrupt and destroy the memorial of the true form.

[.discourse-part]
Question.
Doth he effect this, and prevail likewise against the witnesses?

[.discourse-part]
Answer.
Yea; as he effected the other.
He overcomes the witnesses after the manner that he had overcome the church (to wit,
by captivating the outward man, and killing with the sword;
but they overcome him by patience and faith, in their testimony and sufferings.
Rev. 13:10); and this in all kindreds, tongues, and nations;
and so all the public worship of the earth is given to him.
ver. 7,8.

[.discourse-part]
Question.
Why would God suffer him to do this, seeing he hath all power in his hands,
and could have restrained him if he had pleased?

[.discourse-part]
Answer.
This was greatly needful to the present estate of his people;
for by this God raised up that which was good and pure in any, and kept life in it;
which otherwise might have perished in the estate of that corrupt form,
which then had prevailed, and had gotten dominion outwardly over the true power.

[.discourse-part]
Question.
But did not this tend to destroy Satan`'s kingdom also?
For this stroke going against the very name of Christianity, and profession of godliness,
might light upon his carnal gospellers likewise.

[.discourse-part]
Answer.
They could easily save themselves, turning about to avoid sufferings, and crying,
"`Who is like unto the beast?
Who is able to make war with him?`" Rev. 13:4.
Being already one with him in spirit and principle,
they would not easily differ from him, and suffer about a form;
especially seeing their master`'s interest and service ran now another way.

[.discourse-part]
Question.
What became of this beast?

[.discourse-part]
Answer.
The Lord did rend and tear him outwardly by his plagues, famines, pestilences, wars,
etc., insomuch as one of his heads was wounded as it were to death; and inwardly,
by the innocency and power of his truth appearing in his witnesses,
which scorched and tormented the adversary;
so that this engine of the dragon grew faint and weary, and unfit for this service,
as he stood in this capacity.

[.discourse-part]
Question.
What doth the dragon do then, to carry on his war against the witnesses?

[.discourse-part]
Answer.
After this tempestuous sea was over, he raiseth up another beast out of the earth,
with another kind of power,
even with "`horns like a lamb,`" Rev. 13:11. but "`he spake
as a dragon,`" exercising all the power of the first beast,
ver. 12. so that he is the main in power henceforward;
yet he setteth up the first beast also, causing "`the earth, and them that dwell therein,
to worship the first beast,
whose deadly wound was healed.`" And thus these two join together,
to set up an image to be worshipped; and all that will not worship this image,
(but the living God alone,
in his pure life and Spirit) this latter beast hath power to cause to be killed,
ver. 15. and such must not so much as buy or sell,
who will not receive the "`mark of the beast, or his name,
or`" at least "`the number of his name;`" to which number the
highest growth and perfection in religion and worship,
after the wisdom of the flesh, (or man`'s wisdom) is to be reckoned.
ver. 17,18.

Observe now diligently the place of the true church, and her estate,
and the estate of her children, all the forty-two months.
Her place of habitation is a wilderness; her estate, an estate of widowhood;
a city unbuilt, trodden under the feet of the Gentiles; her seed, witnesses, reproached,
persecuted, and slain, by the false woman and her seed.
Observe likewise the place and estate of the false church and her children;
she rears up a glorious building as to the outward;
she is a city built and richly adorned; she hath a golden cup of doctrine and discipline,
of ordinances and worship, to hold forth to the kings and inhabiters of the earth;
in all nations, peoples, kindreds, and tongues;
she is arrayed in purple and scarlet color, and decked with gold, and precious stones,
and pearls. Rev. 17:4.
and all her daughters (who though they may deny her,
yet partake of her spirit,
and learn to rear up buildings of churches like her)
they also flourish in their degree and measure.
None is poor but Zion; none is desolate but God`'s Jerusalem, but his church,
which fled into the wilderness, to abide there all the time of his appointment;
and her witnesses are clothed with sackcloth,
testifying to God`'s despised and reproached truth, with mourning and grief of spirit;
and not with that fleshly joy, wisdom, and confidence,
wherewith Babylon and her merchants vent their wares; but only in the evidence,
demonstration, and assurance of the Spirit in their hearts,
which all the wise and confident builders and inhabitants
of Babylon trample upon and despise.

Now it behoveth all to consider what this Babylon, what this woman is, spoken of, Rev. 17.
which came in the place of the other woman spoken of, Rev. 12.
what this built city is, which the wrath of the Lord will make desolate;
what this beast or false prophet is,
which appears like a lamb (and showeth such miracles to deceive the earth),
and yet is fierce and cruel to such as witness for God. Rev. 13:13-15.
For dreadful are the plagues, woes, vials of wrath, thunders, etc.,
which God hath prepared for her; even the cup of the Lord`'s indignation without mixture;
torment with fire and brimstone, in the presence of the holy angels,
and in the presence of the Lamb. Rev. 14:10-11.
and chap.
18:8. And who would not fear thee,
O thou King of saints! when thou comest with thy cup of fury and indignation,
to empty into the bowels of this woman,
which hath been so long drunk with the blood of thy saints and martyrs. Rev. 17:6.
Consider these things, O ye Papists!
Wait on the Lord in his fear and dread; that he may vouchsafe to make known to you what,
and where, this city Babylon is;
and that such of you as belong to him may hear his voice calling you out of her,
that ye may escape this bitter cup.
Rev. 18:4

The great judgment is already begun.
(This we know, who have tasted of it.) It hath begun at God`'s house,
and is spreading further; yea, even over the nations which have disowned you,
and yet have learned of you to build up a church
and worship after the manner of your whoredoms.
These the Lord will judge first;
he will plead with the daughters who have disowned their mother,
and yet have gone on in her spirit of whoredoms, worshipping the work of their own hands,
and administering and magnifying the beauty of the churches which themselves have formed.
Now is your time to consider;
now is the time for the simple-hearted among you to flee from Babylon,
before the wrath of the Lord besiege her.
There are three things in general (besides many particulars) which
the Protestant nations and churches have learned of you,
which will cost them dear, ere they be made willing to part with them.

[.numbered-group]
====

[.numbered]
_First,_ Their taking upon them authority over men`'s consciences,
commanding them what they should believe; which the apostles never did,
but said expressly, they had not dominion over the faith of others,
but were helpers of their joy. 2 Cor. 1:24.
They could not command any to believe their doctrine;
but spake in the demonstration of the Spirit, waiting till God opened the heart, 2 Cor. 4:2.
and would not have men profess, believe, or practise from their words,
but by a feeling of the power. 1 Cor. 2:5.
And when men did believe some things,
and came into the unity and fellowship of the faith,
they did not require them to believe all that the church taught or held forth as true,
but waited till God pleased to reveal further. Phil. 3:15.
Indeed they could command obedience to the faith:
what truths the Spirit of the Lord revealed and taught any man,
they could charge him in the name of the Lord to be faithful to. Rom. 1:5.
But they knew it was God alone who
could ingraft the truth into the heart and conscience,
and also give the increase of it; and so from him alone they expected it;
waiting in patience on the stubborn and perverse,
till God should please to work upon them, 2 Tim. 2:24-25.
and likewise on those that were convinced,
and had subjected themselves to the faith, for his increase of it. 1 Cor. 3:6-7.

[.numbered]
_Secondly._ Their abridging men`'s liberty in things wherein God hath left them free,
and pressing them to a uniformity to things which they themselves confess to be indifferent.
Now the apostle (who had the care of all the churches, 2 Cor. 11:28),
though he knew certainly how to determine about meats and days, as himself confesseth, Rom. 14:14.
yet he telleth the church at Rome expressly,
that Christ was the Lord and Master of every disciple,
to whom he must stand or fall herein,
ver. 4. and that every man ought to do as he is fully persuaded in his own mind.
ver. 5. Nay he is so far from pressing a necessity of uniformity in such cases,
that he presseth a necessity of bearing on each hand.
ver. 3. So that, in the apostle`'s judgment,
the church hath not power to lay commands on the conscience,
but must receive the weakest in the faith,
ver. 1. leaving him to the liberty of his conscience,
and to his subjection to his own Lord and Master;
to whom every believer must give an account of what he receives,
and of what he obeys and performs.
ver. 10-12.

[.numbered]
_Thirdly._ Their setting up a church-building, government, and discipline,
by the magistrate`'s power.
This the apostles no where taught nor practised.
They converted men by the power of the Spirit: they cut down errors, heresies, seducers,
and heretics, by the same word;
and they found the weapons of their warfare sufficient, 2 Cor. 10:4.
they had no need of running to the magistrate.
But that church, those doctrines, that government and discipline,
which is set up by the magistrate`'s sword without and against the Spirit,
that hath need of a carnal sword to defend it against the Spirit,
and to cut down God`'s witnesses (whom he raiseth up to
testify against it) for schismatics and heretics,
or its nakedness will soon be made manifest and its ruin approach.

====

Now when the Lord hath judged all the daughters of Babylon for these things,
then will he at length begin to plead with their mother, Babylon the Great,
who hath gone a whoring from the Spirit, and built up a gaudy church without the Spirit,
which she hath defended by violence and blood, drinking the blood of the saints,
who have been inspired by the Spirit to testify against her, Rev. 11:7-8.
and hath taught all her daughters to do the same; to wit,
to drink the blood of the witnesses against them,
even as she hath drunk the blood of the witnesses that have testified against her.
And though, because she hath had a half-day more given her,
after her time seemed to be even expiring,
and after judgment and desolation were beginning to enter upon her; though,
because of this, she thinks the bitterness of death is past,
and she shall now sit as a queen, a lady, a glorious church forever, Rev. 18:7.
yet for all this is she come again into God`'s remembrance.
Rev. 16:19, and she shall see widowhood, and be cast into a bed of torment,
and all her children into great tribulation with her; and she shall be desolate,
and naked, and drink of the cup, and not repent that she might escape it. Rev. 16:11.
9:20,21. This is her portion, from the hand of the Lord.
Oh! happy is he whose eyes the Lord shall open, to flee out of her for life!
For the Lamb is arisen to make war,
and his spouse is making herself ready for his pure bed of life,
and his anger is kindled against all the kings and
powers of the earth that stand in his way;
and though they fight ever so resolutely against him and his meek ones,
they shall not prevail, but the Lamb will overcome all; for he is "`King of kings,
and Lord of lords,`" and they that are with him in this battle of his Spirit, are "`Called,
and Chosen, and Faithful.`" Rev. 17:4. And though this woman (the false church,
in her various dresses) is so strong,
everywhere getting the earthly powers and authorities on her side,
that now it may be said concerning this beast, in the several appearances of it,
as was concerning the former;
"`Who is able to make war with her?`" yet there is an invisible power stronger than she,
who will call her to judgment, Rev. 18:8.
and make her give an account of all
the saints`' blood which she hath drunk herself,
and which she hath taught her daughters to drink.
And "`salvation, glory, honor, and power,`" shall be ascribed to the Lord,
for his righteous and powerful judging of her. Rev. 19:1-2.
And he that hath any glimmering
of this in the eternal light of the Lord`'s pure,
ever-living Spirit, let him even now say,
"`Hallelujah`" to him who is "`arisen out of his holy
habitation,`" and hath already begun this work,
who will not fail to perfect it.
Amen.

=== Somewhat Concerning the Ground of Error, and the Way to Truth and Unity; for the Sake of Such as Are More Spiritual

There is no way to become an heir of the kingdom of God,
but by being begotten and born of his Spirit; which blows upon the spirit of man,
breathes life into him, and forms him in the eternal image. John 3:8.
Gal. 4:19.

There is no way of having this work of God preserved,
but by turning to the Spirit which begets,
standing and keeping upright in that which is begotten,
and taking heed of the fleshly wisdom,
which stands near to corrupt and destroy the work of God;
tempting and leading aside from the truth itself, into some image and resemblance of it.
And if this prevail, there is suddenly a departing from the living God,
and a running a whoring after the inventions of the fleshly wisdom,
which appears in the likeness of the true wisdom, that it might the better deceive.

Now when man is first breathed upon, and begotten towards God,
there is but a little life, a little simplicity, a little light, a little power,
a little of the wisdom of the true babe; but a great body of death, deceit, darkness,
power, and the wisdom of the flesh, standing;
and all these apply themselves to overturn and destroy the true work of God,
by raising up a false image of it, which is easily done;
but abiding and preservation in the truth is difficult,
and alone maintained by that power which at first begat.

Now the power preserves through keeping out of the sensual
and reasoning part (where the corrupt one hath his lodging),
in that poor, low, little, childish sensibility of the life,
which the Father hath begotten.
Here is the entrance into the truth; here is the growth,
here is the preservation and safety;
which makes it so hard for those that are wise and
strong in the reasoning and comprehending part,
either to enter in, or to abide and grow in the nakedness, simplicity,
and seeming folly of the truth of the gospel.
Oh, what a deal is to be brought down,
before they can be truly reached and convinced by the foolish and
weak things which God chooseth to effect his great works by! 1
Cor.1:27,28. What a work hath God with them to batter their wisdom,
and bring down their understanding; which the larger it is,
the more it stands in the way of his light. 1 Cor. 1:19.
And if they be convinced at any time,
what an easy and natural return unto them doth their own wisdom find,
by some subtle device or other,
to draw them back from the plainness and singleness of the truth,
into a holding it in the wisdom and subtlety of the understanding part,
where the simplicity is soon lost. 2 Cor. 11:3.

In the Spirit which begets, and in the truth which is begotten by it, is the true unity.
Feeling that in one another, is that which unites us to one another.
Every one keeping to that in his own particular, is kept to that which unites;
and that is kept alive in him which is to be united; but departing from that,
there is a departing from the true unity into the error and ground of division.
And then that which hath erred and departed from the true unity,
strives to set up a false image of unity, and blames that which abides in the truth,
because it cannot thus unite; for that which abides in the Spirit,
and in that which the Spirit hath begotten and formed,
cannot unite according to the flesh; as that which is run a whoring from the Spirit,
into an image of the fleshly wisdom`'s forming, cannot unite according to the Spirit.
Consider this, O ye professors of this age!
Ye blame us for departing from you; for withdrawing from unity with you.
We blame you for departing from the living principle,
wherein our unity with you formerly stood, and wherein alone we can again unite with you;
and not in such things as uphold a fleshly and false image of the true unity.

Oh, that ye could hear the Lord`'s voice,
who crieth aloud to the professors of this age to cease from man!
Cease from man in thyself,
O thou who hast ever had any taste of the pure grace and power of God!
Cease from thine own understanding, thine own affections, thine own zeal,
thine own gathered knowledge and wisdom from the Scriptures,
with all the sparks of thine own kindling; that God may be all in thee,
and his eternal habitation be raised up in thee, and perfected,
and thou swallowed up and comprehended in it forever.
Oh, what a work hath God to drive man`'s reason and wisdom out of his temple,
out of his Scriptures, out of all his holy things!
He that hath an ear, let him hear, for the sake of his soul`'s eternal peace.
Alas! alas! how many stumble at, and blaspheme that, which alone can save the soul!
There have been many dispensations of, but there is but one living truth;
but one substance; but one arm of salvation.
And he that stumbles at the thing itself, how can he be saved by it?
It is easy misunderstanding a former dispensation, reading it in the letter;
and so to miss of the salvation hoped for by it.

The Jews owned the Messiah (according to the Scriptures, as they thought),
but rejected him in the way he came to save them in.
Now if Christians have gathered such a kind of knowledge
from the letter of the Scriptures as they did,
how can they avoid the same error; namely, of owning Christ according to the Scriptures,
as they think, but rejecting him as he comes to save them;
rebelling against his living ministry,
and the pure power and demonstration of his Spirit, because it appears weak and low;
because it doth not appear the same thing to them which they expect to be saved by,
according to their apprehensions of the Scriptures?
Thus reading the Scriptures in another spirit and wisdom than that which wrote them,
they must needs conclude and gather another thing from them than what is written in them;
and so make that a means to them of erring from the life,
which was written to testify of, and point to,
the living principle from whence life and salvation springs,
and where alone it is to be had.
