== An Epistle / To all such as observe the Seventh Day of the Week for the Sabbath of the Lord.

FRIENDS,

In true love to your souls, and in the fear of the Lord,
I have a few things to lay before you, that the simplicity in you may not be deceived,
and ye err from the way of life, while ye may be eagerly seeking and pressing towards it:
for notwithstanding that, if with the wrong eye ye be searching into Scripture,
ye must needs mis-read, mis-understand, and mis-practice;
and so thereby will still be running further and further from God,
even while ye think ye are drawing nigher towards him.
Be persuaded, therefore, seriously to consider (out of the wisdom from which God hides,
in the babish simplicity of his begetting,
where the true life springs) these few things following.

1+++.+++ That the whole law of Moses
(the ten words, as well as the institutions about sacrifices and worship)
was added because of transgression. Gal. 3:19.

2+++.+++ That the whole law (the ten words, as well as the sacrifices) was representations,
figures, or shadows, of somewhat relating to Christ, the seed;
subservient to the promise, not making perfect, but pointing to, and making way for,
the bringing in of the better hope. Gal. 3:21.
Heb. 7:19. The law of the commandments, or the ten words,
did no more make perfect, than the other shadows or sacrifices did,
but with them made way for the better hope,
towards which they were to lead their scholar, or disciple, as school-master.

3+++.+++ That the whole dispensation of the law was given to the Jews,
and not to the Gentiles. Rom. 9:4.
And so not any thing there written bindeth the Gentiles (as there written,
but only the Jews.
God had another way of making his mind known to the Gentiles.
Rom. 1:19:15. According to which he would judge them.
ver. 12. And not by the law written, which was given to the Jews,
which spake not to the Gentiles, but to the Jews, who were under it. Rom. 3:19.

4+++.+++ That the duration of this dispensation of Moses`' law in the letter, was till Christ,
the seed, should come and fulfill it. Gal. 3:19.
and 24,25. Moses`' family, with all the laws thereof,
were to prepare for Christ, the seed, and to give way to him when he came;
for when that dispensation, which was figured out, is come;
then that dispensation which did figure it out, is at an end. Heb. 3:5-6.
Christ came to do the will, to keep and fulfill the whole law,
and so to put an end to that dispensation of it.
Psa. 40. Rom. 10:4. And so he taketh away the first administration of the law,
which was in the letter, that he might establish the second, which is in the Spirit. Heb. 10:9.
2 Cor. 3:7-11.

This then is the truth, as it is in Jesus, concerning this thing;
That Christ coming in the flesh,
and fulfilling all the righteousness (as well of the ten commandments
as of the sacrifices) puts an end to that dispensation wholly;
so that henceforth both Jews and Gentiles are to come to him, to hear his voice;
"`This is my beloved Son, hear him.`" And Moses foretold, that when that prophet came,
he was to be heard in all things;
whose whole ministration was but to figure out what
the Son was afterwards to fulfill in Spirit, Heb. 3:5.
who would be faithful to give forth the entire
law and substance of life to his house or family of believers,
as Moses was faithful to give the entire shadow to his house or family,
of that nation of the Jews.
ver. 6. So that here, in the gospel, Christ being come,
the new covenant and law in the Spirit takes place,
and not the old covenant or law in the letter.
And this law is more inward, more full, more close, more spiritual, and more lasting,
than the ministration of Moses`' law to them of old time was.
Gal. 3:25, etc.
And it is the ministration of this law of the Spirit,
which is not to pass away from the disciples of Christ, until all be fulfilled;
but is to remain a sword against every lust and desire of the flesh in them,
until they all, with the very root of them, be thereby cut down. Matt. 3:12.
Heb. 4:12. Matt. 5:17-18.

Question.
But what were the ten commandments a figure or shadow of?

Answer.
The tables of stone were a representation or figure of the fleshly tables of the heart,
wherein the new law of the covenant of life is written.

The writing of the law of commandments in the tables of stone was a figure
of the writing of the new law by the finger of God`'s Spirit in the heart.
The outward writing in the outward tables was a figure
of the inward writing in the inward tables.

The law itself of commandments, which was written in those tables,
was a figure of the law of life which is to be written in these tables.

And this law thus received, thus written, is easily fulfilled; whereas,
the law in the letter, because of the weakness of the flesh,
was very hard to be fulfilled,
and generally proved a hand-writing of ordinances against the Jews:
for he that was guilty of one, was guilty of all,
and so upon every transgression had the force and strength of the whole law against him.
And whosoever now runs back to the law in the letter,
to take up any command as held forth in it, and so making himself a debtor thereto,
will be found a breaker thereof in spirit, even one that hath more gods than the Lord,
a maker of images, or likenesses of things in heaven, or things in earth, if not of both;
a taker of the name in vain, a profaner of the sabbath, etc.
For he that hath not received the law of the Spirit of life in Christ Jesus,
knoweth not the Lord of life to be the only true God, but maketh images in his mind,
and taketh his name in vain, not feeling the living power thereof;
nor can keep his sabbath (ceasing from sin, forbearing his own works,
his own willing and running, and entering into the rest of the gospel):
for there is but one day of rest holy to the Lord;
all the sabbaths of the law were but signs of it,
having but a significative or representative holiness;
but the day of redemption which the Lord hath made,
Ps. 118:24 (in which his redeemed rejoice,
and rest to him) that hath the true holiness.
This was it which came by Christ, the other came by Moses. John 1:17.
Moses`' family or children were to keep
that day (that was the day for the servants,
who were to be exercised under the shadows),
but the believers are to keep this day in the Spirit,
to enter into this rest by the faith, Heb, 4. and to worship the Father in it,
in the Spirit and in the truth, on the mountain of his holiness, John 4:23.
whereof the other mountain, temple, worship, and day were but a shadow.

Now the sum or substance of this law of the Spirit
may outwardly be signified in divers short words;
as love, that comprehends the whole of it; so doth fear;
there is the whole wisdom and course of the life comprehended also; or thus,
"`Thou shalt not lust,`" (thus it was administered to Paul, Rom.
7.) or thou shalt "`keep the sabbath, or "`believe in the light,
follow the light.`" The observing of any one of these in the Spirit,
is the keeping of the law; for every breach of the law is out of the love,
out of the fear; a lust of the fleshly spirit, a transgression of the sabbath,
or spiritual rest to God; out of the light, and out of the faith.
But if ye will read this in the Spirit, and come to the true righteousness of the faith,
which is received in the obedience of faith to the law of the Spirit,
ye must come to the word of faith; to which Paul directs, Rom. 10:6.
by the hearing whereof is the justification,
and not by a bare believing that Christ`'s blood was shed;
for it is the virtue of the blood which saves; which virtue is in the living word,
and is felt and received in hearing, believing, and obeying that word,
thereby bringing into unity and conformity with him, both in his death,
and in his resurrection and life.
This is the only way to life; be not deceived; there is not, nor ever was, any other.
Oh, wait on the Lord in his fear! that it may be opened to you,
and that slain in you which cannot bear the straitness thereof,
and with which there is no erring.

From a friend to your eternal peace,

ISAAC PENINGTON the Younger.
