== The New Covenant of the Gospel / Distinguished from the Old Covenant of the Law

[.heading-continuation-blurb]
And the rest or sabbath of believers, from the rest or sabbath of the Jews;
which differ as much from each other as the sign
and shadow doth from the thing signified and shadowed out.

[.heading-continuation-blurb]
In answer to some queries of W. Salter`'s,
tending to enforce upon Christians the observation of the Jewish sabbath,
which was given under the law to the Jews for a sign.

[.heading-continuation-blurb]
As also to some other _Queries_ sent in writing,
upon occasion of an _Epistle_ directed to all such
as observe the Seventh Day of the week for a Sabbath, now under the _Gospel._
As likewise some _Letters_ to the same purpose.

[.heading-continuation-blurb]
With a brief explication of the mystery of the
_six days`' labor,_ and _seventh day`'s sabbath._

[.heading-continuation-blurb]
Whereto are added some _Considerations_ propounded to the _Jews,_
tending towards their Conversion to that which is the Life and Spirit of the Law.

[.section-author]
By _Isaac Penington,_ the Younger

[.section-date]
1660

[quote.section-epigraph, , Heb. 4:3]
____
We which have believed do enter into Rest.
____

[quote.section-epigraph, , Col. 2:16-17]
____
Let no man therefore judge you in meat or drink, or in respect of an holy day,
or of the new moon, or sabbaths; which are a shadow of things to come: but the body is Christ.
____

=== Preface

The apostle Paul saith, that God had made them "`able ministers of the New Testament,
not of the letter, but of the Spirit,`" 2 Cor. 3:6. After the dispensation of the law,
which was a shadow of good things to come; and after the dispensation of the prophets,
who foretold of better days, and of a better state to come,
than the days and state under the law were;
it first pleased God to send the forerunner John the Baptist,
in the spirit and power of Elias, to prepare the way for the King and his kingdom;
and then to send the King himself, in the fulness of his spirit,
to gather disciples to him,
and to furnish them with a competent measure of the same Spirit,
to raise up a spiritual seed to him, in whom he would set up his kingdom, dwelling,
walking, and reigning there;
causing his light to shine from thence round about the earth, as from his holy city,
founded upon his holy hill of Zion.

Now those disciples or ministers whom he chose to raise up this holy seed unto him,
he made fit and able to minister his new covenant, by which it was to be raised; yea,
he furnished them with such a power of his Spirit,
that they were able through him to minister, not in the letter,
as the old covenant was ministered (which left the people still dead; nay,
because of the transgressing nature, made the offence abound,
and so increased death upon them), but in the quickening Spirit,
which raiseth from death, and bringeth into the light of the living,
to walk with the living God towards the land of eternal rest and peace.
So that that which they ministered was Spirit,
and that which they ministered to was spiritual.
By the power of the Spirit, in preaching the living Word of faith,
they reached through the veil to that which lay in death;
they stirred up a living principle, and ministered life to it through the Spirit. Gal. 3:5.
And such as were born of this living principle,
they taught to live in the Spirit, to walk in the Spirit,
to be made perfect by the Spirit,
and not to run back to the ministration of the letter (as was proper
for the Jews in their day) after the manner of the former dispensation,
but to keep in the living principle, to grow up in the seed,
into the eternal life and immortality of the gospel.

Mark well (O ye christians, who desire eternal life),
the different way of ministration between the law and the gospel!
The law was a ministration of the letter,
in which they were to wait for assistance from the Spirit,
by which they might be kept in the faith of, and made obedient to, the law. Neh. 9:20.
The gospel is a ministration of the Spirit,
wherein they are to begin with the Spirit, and to go on with the Spirit;
not to gather outward rules out of the letter, from what is written or spoken,
but to keep to the living principle, and feel refreshment to that,
in reading or hearing what is written or spoken by the Spirit.
And thus the Scriptures being read, or any one speaking from God being heard,
it is mingled with faith, and becomes profitable, feeding and refreshing the young,
tender plant, the living principle, and causing it to grow up into God:
whereas whatever is understood, or received, or held out of this, feeds but the earthly,
and doth but thicken the veil over the living seed; to which the kingdom belongs,
and to which the gospel is sent to be preached, to raise it,
that it might live and thrive, and grow up into its stature, that so it might inherit.

"`The kingdom of heaven is at hand,`" said John the Baptist. Matt. 3:2.
"`It is come unto you,`" said Christ, Matt. 12:28.
that power of life which was made manifest in him, to the Pharisees. Luke 17:21.
The Pharisees demanded of him when the kingdom of God should come.
It cometh not, saith he, with outward show or observation;
it cometh not that way you look for it; to wit,
by the manifestation of an outward glorious king,
to reign outwardly in the commonwealth of the outward Israel;
but the kingdom is within you.
How was it within them?
Christ explains to them in another place; it was in them like a grain of mustard seed;
it was the least of all the seeds in their hearts.
There were many great seeds of darkness there,
but yet there was also one little seed of light.
It was there as well as the rest (though less than them all),
and did sometimes cast some glimmmerings of light, and of its shining in the darkness,
though the darkness could not comprehend it.
This seed was also likened to leaven, which being received by faith into the lump,
would leaven the whole lump, and bring it into the savor and domination of the kingdom.
Now the ministry of the apostles was to turn men from Satan`'s kingdom to this kingdom;
from his large compass of dominion in the heart, to this narrow seed;
from his great territories of darkness, to this little principle of light;
from his great power of death, to this little, weak thing of God;
wherein the eternal power and godhead is made manifest,
as this comes to be opened and increased by the Spirit.
Here light is sown for the righteous, and joy for the upright in heart;
where it is to grow up,
and from whence it is to be reaped after its growth to perfection.

Oh, how long have Christians (so called) wanted the Spirit!
How have they wearied themselves, in running to and fro about the letter,
to find out the mind of God, and are still unsatisfied concerning it,
and even drowned in fleshly imaginations and contentions about it!
They seek to have that satisfied which is not to be satisfied:
they seek to have that know which is not to know: they offer to God the service, faith,
and obedience of that which he will not accept;
and keep that from him which he calls for.
They seek for the Spirit in the letter, according to the manner of the law;
but wait not to feel it in the seed, quickening the seed, raising up the seed,
and dwelling in the seed, whither Christ and his apostles directed to wait for it.
They look for that knowledge, that faith, that life, that Spirit, from words written,
which the apostle preached was to be waited for from the Word in the heart.
And by this means they raise up several buildings, and get various kinds of knowledge,
each according to his understanding and apprehensions of the letter,
every sort being very confident concerning their
own apprehensions that they are the right;
and thus they wander from the city of the living God, and from the living knowledge;
building up images, some outwardly, some in their minds; some more gross,
some more refined; but all, more or less,
who are not acquainted with the living knowledge and truths of God,
but have gathered apprehensions with the wrong tool from the letter,
have set up somewhat else instead of the true life
and power (the knowledge of the true God,
which is life eternal),
the knowledge of the true Christ (whom no man can indeed call Lord, but by the Spirit),
the knowledge of the everlasting gospel (which alone is read in the Spirit),
the knowledge of the Spirit (which alone is read in the seed).
These are strange things to the several generations of the Christians of this age,
who commonly know no more of them,
than according to the apprehensions they have taken in concerning them;
even from that wisdom and understanding which hath not a capacity in it to receive them,
but must be destroyed before these things can be understood aright. 1 Cor. 1:19.
Oh that ye could read in the eternal light of life!
O Christians, Christians!
Oh that ye could see how your understandings and
knowledge from the letter stand as much in your way,
as ever the Jews`' did in theirs; and must be broken down as flat as ever theirs was,
before the foundation of the kingdom can be laid,
and the building of eternal life reared up in your hearts!
Be not offended at my zeal for the Lord my God, and for your souls.
It hath cost me very dear,
what I testify to you in the simplicity and integrity of my heart;
and this I know to be most certainly true, that that spirit of man, which,
without the leadings of the eternal light, hath nestled itself in the letter,
got a seat of wisdom and knowledge there, raised up a building from thence,
either of inward or outward worship, will be dissettled and driven thence,
even by that very Spirit which gave forth the letter.
And when this is done, and God`'s Spirit again openeth the letter, oh, how sweet,
how profitable, how clear, how refreshing will it be,
being read in the light of the Spirit, and in the faith which is in Christ Jesus,
which is begotten in the heart by the word of faith, which is nigh there.
From that light, from that spring (as the Lord pleaseth to open, enlarge,
and fill the vessel), all the words of the holy men of God came;
and in that alone they have their sweetness, freshness, virtue, and fulness;
but how to read the words outwardly written, keeping to that,
and understanding them in that (and how to keep out the natural man,
with his natural understanding, which knoweth not the things of the Spirit,
nor can know or receive them, 1 Cor. 2:14),
is a mystery to them who have not been turned inward to this word,
nor have known or heard his voice.
The Lord is recovering the mystery of life; and as that appears, the mystery of death,
under all its paint (under all its painted faith, painted love, painted knowledge,
painted obedience, painted duties, ordinances, and worship), will be made manifest.
Happy is he whose inward building will stand,
whose gold will abide the fire and everlasting burnings of the jealous God,
whose eye-salve was bought of the true Spirit, whose raiment is right spun;
but exceeding hard will it go with that man whom the Lord (when
he cometh to search him) shall not find a right inward Jew,
as he took himself to be,
nor truly circumcised by the Lord`'s eternal Spirit with the light thereof,
but only by such a circumcising-knife as he himself
had formed out of the letter of the Scriptures.
This is the great misery of Christians; the veil lies over their hearts,
even the same veil which covered the letter of Moses from the Jews:
and they are groping after the mind of God in the letter; but the life is hid from them,
even as it was from the Jews: and because they also say they see,
and that they have the life and the Spirit, therefore the veil remains,
and the caul of iniquity surrounds them,
so that they cannot see into that which makes free from it,
but remain yet in captivity and bondage to the enemy.

[.old-style]
=== The New Covenent of the Gospel / Distinguished from the Old Covenant of the Law

[.section-summary-preface]
Some queries of W. Salter`'s,
tending to enforce upon Christians the observation of the Jewish sabbath, answered.

[.discourse-part]
_Query 1._ Whether the fourth commandment, expressed Exod. 20.
be not moral and perpetual, as well as the other nine be, yea or no?

[.discourse-part]
Answer.
That covenant which God made with the Jews at Mount Horeb,
when they came out of the land of Egypt, was not to be perpetual;
but to make way for that covenant, priesthood, lawgiver, and law,
which were to be perpetual.
That law, so given forth, made nothing perfect;
but was a continual handwriting of ordinances against the Jews;
and the very salvation of the Jews was by another covenant, and by the laws thereof, Duet. 30:11.
by which covenant, and by which law, they might be made perfect,
and come to the better hope.
Which other covenant is the covenant of grace,
or the law of the Spirit of life in Christ Jesus, or the Word which is nigh in the mouth,
and in the heart,
and speaks life to them that can hear and believe the joyful sound of it.

Now that this former covenant was not to abide, but to give place to the other, see Heb.
viii, which treateth of the new covenant:
for God`'s speaking of a new covenant importeth that he himself hath made the first old.
ver. 13. It had a long continuance among that people of the Jews;
but now against the coming of Christ, who was to be Mediator of a better covenant,
ver. 6. even a new covenant, ver. 8. as it had been long decaying, and waxing old,
so now it was ready to vanish away, as ver. 13.

And indeed it was necessary it should pass away; for it was not faultless.
How, not faultless!
Was there any sin in the holy law and ministration of God by Moses?
Can there any just blame be found in any thing that proceeded from the Lord?
Nay, surely the ministration of Moses was holy, and without blame; but it was weak,
through the flesh, Rom. 8:3. and therefore God would lay that aside,
so far as it was weak, and suited to the weakness of a fleshly people, and bring,
instead thereof, a ministration of the law in the Spirit,
which should be lively and powerful and effectual in the spirits of his people.

That which God aimed at in a covenant, was to keep him and his people together.
Now this covenant was weak on the people`'s part; they continued not in it, and so,
according to that covenant, God disregarded them.
ver. 9. Now God finding this covenant not able to
effect his purpose of love towards his people,
he finds fault with it, bringing forth another, or second, which this gives place to.
ver. 7. And this other covenant, or new covenant, is not according to that.
How not according to that?
Why this: it was not written outwardly, as that was.
"`Not according to that which I made with their fathers,
when I took them by the hand to lead them out of the land
of Egypt.`" ver. 9. "`For I will put my laws in their mind,
and write them in their hearts.`" ver. 10. And here they shall learn the knowledge of God,
every one from the least to the greatest,
ver. 11. "`So that all the children of this covenant shall
be taught of the Lord,`" and learn the law from his mouth;
not as it was given at Mount Sinai,
(which ministration was to the children of the old
covenant) but as it goes forth out of Zion,
and from the "`Jerusalem which is above,`" which is
the mother of all the children of the covenant,
and nourisheth them, not with the law of Moses, but with the milk of her own breasts.

Now if any think to restrain this to the types and shadows of the law, they therein err:
for the main covenant was the law of commandments, which they still broke,
worshipping other gods, making images and likenesses, taking his name in vain,
profaning his sabbaths, and so of the rest.
It is true, the first covenant had a worldly sanctuary,
a tabernacle wherein was the candlestick, etc.,
but the chief matter of the covenant was the ten words;
therefore the tables wherein it was written were called the tables of the covenant,
or the tables wherein the covenant was contained. Heb. 9:4.
Yea, the ten words are expressly called the covenant itself. Duet. 4:13.
Observe therefore diligently these
few things following in the fear of the Lord:

[.numbered-group]
====

[.numbered]
_First,_
The ten commandments given by Moses from Mount Horeb were the covenant which God made
with the Jews when he took them by the hand to lead them out of the land of Egypt.

[.numbered]
_Secondly,_ That covenant God found fault with,
because it was not able (through the weakness of
the flesh on their parts) to keep them to God.

[.numbered]
_Thirdly,_ Against Christ`'s coming God provideth a new covenant,
a better covenant for him to be Mediator of; which covenant was not outward,
like the former, but inward, put in the mind, writ in the heart.
As the people was inward, the sanctuary inward, the ark inward,
the tables of the covenant inward, so the covenant itself, and the writing of it,
were inward also.
And this covenant, as it is only written in the Spirit, and in that which is spiritual,
so it cannot be read in the letter.

[.numbered]
_Fourthly,_ That wherever this new covenant cometh, the other waxeth old,
whether to a person or people.
Wherever the law of the Spirit of life is made manifest,
the law of the letter is swallowed up in it,
and is known no more but as it is comprehended, and is brought forth in it.
And he that is in the Spirit,
and hath received the law of life from the Spirit knoweth not Christ after the flesh;
how much less Moses.
But taking the whole ministration of Moses in the spirit, not only the ten commandments,
but all the sacrifices and other types also, here they are owned and received,
even in Christ the substance: but the ten commandments, so far as they were a shadow,
pass away before the Sun of righteousness,
as well as the other types and shadows of the law.

====

[.discourse-part]
Objection.
But was there any thing of the ten words a shadow?
Do they not all command abiding things?

[.discourse-part]
Answer.
Moses`' whose ministration (as it stood in the letter without) was but a shadow
of the fulness and perfection of that ministry of the Spirit which was to come,
and to be set up by the Son in his house. Heb. 3:5-6.
Moses`' people, but a shadow of the spiritual people;
Moses`' priests and sacrifices, but a shadow of the spiritual priests and sacrifices;
Moses`' law in the letter ministered from Mount Sinai,
but a shadow of Christ`'s law in the Spirit to be ministered from Mount Zion. 2 Cor. 3:10-11.
The law itself which was given by him,
but a shadow of the grace and truth which came by Jesus Christ. John 1:17.
Of whose fulness every believer receives a portion of the same grace,
"`even grace for grace;`" ver. 16 which grace is to be his teacher,
both of what he should deny and turn from,
and how he should live and carry himself both towards God and man. Tit. 2:11-12.
Look particularly on the commandments,
and see if there will not appear something of a shadow in them.

The first commandment to that people,
"`That they should have none other gods (like the heathen) but him only whose
powerful arm had brought them out of Egypt.`" This is a shadow of the subjection
of the spiritual Israel singly in Spirit to the Lord of spirits,
who by his mighty arm redeemed them out of spiritual Egypt.
Now must they bow to other lords no more, Isa. 26:13.
as they did bow in the land of Egypt (Oh, who can read this!),
but bow alone at the name of Jesus,
and be subject to the arm of his power in their spirits alone forever.

The second commandment,
"`That they should not make any images or likenesses of things in heaven or earth,
or bow down to them, is a shadow of what God requires of spiritual Israel in the inward,
where all likenesses, inventions, imitations,
resemblances of what they have seen in the Spirit above,
or beneath in the earthly nature, they must not make themselves,
nor bow to such as any others make.

And they must not "`take the name (of the Lord their Redeemer) in vain,`"
pretending to the living power when it manifests not itself in them;
pretending to meet in the living name, and to worship in the Spirit,
when they are gone a whoring from it, and become strangers to it.
What should I mention any more?
It is easy to observe how the other commandments were shadows of the inward
innocency and purity which the believer receives inwardly into his heart
from the powerful operation of the law of the Spirit of life in him.

[.discourse-part]
Objection.
But may any of these laws be broken?
If they may not be broken, then they are perpetual.

[.discourse-part]
Answer.
The reason why they may not be broken is not because
that the dispensation of them is still in force,
but because the dispensation of the law of the Spirit
comprehends all the righteousness of Moses`' law:
and the end of Christ`'s dissolving that covenant was not that any might
have liberty to do any thing which is there manifested to be unrighteous;
but that the righteousness of it might be fulfilled
in them who receive his law in the Spirit,
which never could be fulfilled by receiving of Moses`' law in the letter. Rom. 8:4.
And mark this diligently,
ye that have been exercised in the Spirit towards God:
the law of sin is nearer to us than any law of the letter can come;
the covenant of death and hell (with the laws thereof)
is written within by the finger of Satan;
and that which blots them out must be as near, even an inward covenant,
an inward writing from the eternal Word in the heart,
by the law of his eternal Spirit of life.

This then is my answer: Moses`' law in substance remains, as it is taken in by Christ,
and administered by him in Spirit; but not as it was given in the letter to the Jews:
for so it was a shadow, making nothing perfect: but making way for the better hope,
for the covenant established upon better promises,
for the inward law of the Spirit of life in Christ Jesus:
which effects that in the spirits of his people, which Moses`' law could by no means do.

[.discourse-part]
Question.
But what is the substance of the law which abides?

[.discourse-part]
Answer.
The substance of the law is love: to love God above all (above all without,
above all within), and to love one`'s neighbor as one`'s self.
To receive this love from God, and to bring it forth in his Spirit,
this is the substance of the law; this is the thing which the law drove at in a shadow.
The law is fulfilled in this one word love;
but that love must be received from God which fulfils the law.
A man may strive to love abundantly, and strive to obey in love,
and yet fall short of the covenant;
but the Lord must circumcise the heart before that
love can spring up which fulfils the law. Duet. 30:6.

[.discourse-part]
Objection.
But doth not the Apostle Paul say, that by the law is the knowledge of sin;
and that he had not known lust, except the law had said,
"`Thou shalt not covet;`" plainly referring to the tenth commandment, which saith,
"`Thou shalt not covet.`"

[.discourse-part]
Answer.
By the law outwardly was the knowledge of sin outwardly to the people of the Jews;
by the law inwardly is the knowledge of sin inwardly to the spirits of disciples.
Now a little consider and wait on the Lord,
to know what administration of the law it was that Paul knew sin by;
whether it was by Moses`' administration of the law in the letter,
or by Christ`'s ministration of his law to him in the Spirit.
It is rendered in our last translation,
"`Thou shalt not covet;`" but it might more properly be rendered, "`Thou shalt not lust:`"
// lint-disable invalid-characters
for if ὲπιθυμία be properly rendered lust, then οὐκ επιθυμήσεις may as properly be rendered,
"`Thou shalt not lust.`" And he that hath received
the administration of the law in the Spirit,
knoweth it thus to issue forth from the Word of life into his spirit.
It discovers the lusts and affections of the flesh,
which draw from the yoke and subjection to the Spirit; and then,
by a command from the living Spirit, it hedgeth up the way after the other lovers,
saying, "`Thou shalt not lust.`" And as the law of the flesh ariseth,
kindling desires after vanity, and after fleshly ease and delight;
so the law of the Spirit arises in the inner man, forbidding, pricking, stopping,
and limiting that which would be at liberty out of the life and purity of the holy law.
And here begin the bitter fights and terrible battles
and conflicts between the two seeds,
wherein all the powers of heaven, earth, and hell are engaged.

Now because this interpretation of Paul`'s words may seem strange
and uncouth to persons who have drunk in another apprehension,
and have taken it for granted that Paul there refers to the tenth commandment,
consider the place yet further,
and perhaps the Lord may please to open it to you from the very letter,
even as he hath opened it to others immediately by his Spirit,
by causing them to feel the thing which Paul felt,
and to receive the law as he received it.

Paul (in that seventh of the Romans) speaks of three states which he had known.

[.numbered-group]
====

[.numbered]
_First,_ A state of life before the law: "`I was alive without the law once.`" ver. 9.

[.numbered]
_Secondly,_ A state of death after the commandment came: then sins revived, and he died.
When the word of life came with its living commandment to set upon sin indeed,
then sin would dally no longer; it would no longer lie as dead,
and let Paul live in his zeal and worship as he had done before; but it slew him,
it showed its power in him, sometimes deceiving him,
and sometimes forcing him from that which was holy, spiritual, just, and good,
and to that which was unholy; insomuch as he did do what he hated,
and could not do what he loved; and found himself a wretched man,
and in miserable captivity,
because of the body of death and the law of sin in his members.
ver. 23,24.

[.numbered]
_Thirdly,_ A state of life,
after the commandment had done its work in thoroughly slaying of him;
when that was removed which the law came against, then he was married to another husband,
then he could bring forth fruit unto God; Rom. 7:4.
then he could walk freely with God, not after the flesh,
but after the Spirit, chap.
8:4. and rejoice in the life and the peace, instead of roaring out because of the death,
which came from the carnal mind.
ver. 5.

====

Now when was the time when Paul "`was alive without
the law`"? Was it not when he was righteous,
when he was whole?
Then he had no need of the physician, then he had not received the wound,
even the terrible wound which Christ then gives the
soul when he calleth to it by his Spirit,
and giveth forth the commandment,
"`Thou shalt not lust.`" When he had "`confidence in
the flesh,`" being circumcised the eighth day,
of the stock of Israel, of the tribe of Benjamin, an Hebrew of the Hebrews;
as touching the law, a Pharisee; concerning zeal, persecuting the church;
touching the righteousness which is in the law, blameless. Phil. 3:4-6.
Here was a living man;
and his exact receiving the ministration of the law in the letter was part of his life;
yea, but he had not received the commandment yet that slew him.
Paul was alive yet, and could flourish in the freshness of his life, zeal,
and abundant knowledge under this administration of the law: but when God,
who caused the light to shine out of darkness, shined in his heart;
when God began the work of the new creation in him by his living light;
when the commandment came fresh from the Spirit (the
commandment which was ordained to life, Rom. 7:10.
which the ministration of the law in the letter was not,
no not to the Jews, but another.
Duet. 30:14-15), then Paul began to feel the sting of death, and the power of sin,
which now rose up in its strength to retain one of its subjects,
and to keep the stronger man than he from dispossessing him, if he could.
And now how was poor Paul rent and torn, and harrassed by the enemy,
and made to see and feel his miserable captivity, until he had passed through the death,
and was redeemed from under sin,
and consequently from under this bitter administration of the Spirit, by his holy, pure,
and severe law against sin!
For the man being dead, the law hath no force against the seed,
nor against that which is one with and lives in the seed:
and this it is he speaks to the Romans concerning,
who also were acquainted with the ministration of the law, as ver. 1. of the 7th chap.
Now is it not very manifest that Paul knew not sin spiritually
by the ministration of the law in the letter,
but was alive without it, until he felt the ministry of it from Christ in the Spirit?
And that soon struck at his life, and by degrees slew it, killing the body of sin in him,
with its members, and so preparing him for the marriage to another husband.

[.discourse-part]
Objection.
But by this then a man is not only freed from the law of the letter,
but also from the law of the Spirit:
for if this law be ministered to him till death pass upon him,
and till he be married to Christ, then after death is passed upon him,
and he is baptized into death, and risen with Christ, and married to him,
the law passeth away likewise.

[.discourse-part]
Answer.
There is a double ministration of the law of the Spirit;
a sharp ministration against sin, and a sweet ministration in the renewed Spirit.
The ministration against sin passeth away, as the sin is wrought out; but then the sweet,
spiritual current and law of its holy and pure life
in the renewed Spirit is more vigorous and full.
So that the law of the Spirit remaineth forever; but its convictions, its reproofs,
its chastisements towards the worldly part,
diminish and pass away as the worldly part is wasted; and its sweet, comforting presence,
pure peace, fresh joy and life, increase as the new man grows and flourishes.

[.discourse-part]
_Query 2._ Whether the scope and drift of that fourth precept be not to
persuade us to lay by the works of our calling one day in seven,
that we may on that day wholly give up ourselves to wait on the Lord,
in the performance of duties of piety and mercy, for our attaining of, and growing in,
sanctification and holiness?

[.discourse-part]
Answer.
The scope and drift of the fourth commandment was to enjoin
the Jews to keep the sabbath strictly as a sign,
by forbearing all works,
and sanctifying it as a day of rest to the Lord according to the law. Ezek. 20:12.
But the substance being come (Christ, who is the body, Col. 2:17),
the day and rest of the Spirit being known, the sign is at an end,
and the thing signified taketh place.
So that the rest is now in Christ, through the faith, by his Spirit, where the worship is.
And this in the gospel comprehends the time of worship, the place of worship,
and the worship itself (which are spiritual), where, in substance, all is known, enjoyed,
and solemnized, which was figured out in shadows under the law.
The sanctification being come, the rest being come, the Lord of the sabbath being come,
shall not the sign of the sanctification,
the sign of the rest (which rest the Lord of the sabbath was to give,
and lead the spirits of his people into), pass away? Ex. 31:13.

[.discourse-part]
_Query 3._ Whether the fourth precept do not as strictly bind
us to keep holy the seventh day of or from the creation,
as it bindeth us to the observation of a seventh day?

[.discourse-part]
Answer.
The fourth commandment did not require the observation of a seventh day in general;
but of a seventh day in particular, of those of whom it required it:
for what the law required, it required of those who were under the law,
and not of others. Rom. 3:19.

[.discourse-part]
_Query 4._ If the seventh day`'s sabbath be not moral and perpetual,
then how comes it to pass that it was instituted or appointed from the first creation,
when men by guilt stood in no need of a Saviour, nor yet of such a ceremony; Gen. 2:3.

[.discourse-part]
Answer.
That it was instituted or appointed from the first creation,
or that God intended to require of man the observation of it had he abode in innocency,
is not manifest in the Scriptures;
but that God did then bless and sanctify it (in relation to the service he had for it),
that is expressed in scripture. Gen. 2:2-3.
And that this was one end for which he did sanctify it, namely,
that it might be for a sign unto that people of the Jews (which were the people
he chose to set up his signs and figures of the invisible things among),
the scripture also testifies. Ex. 20:11.
but what further meaning there is in it,
and what relation it hath to all the redeemed of the Lord,
in whom God brings about the new creation, with the rest thereof (as he did the old),
it is better to wait to know and feel in the Spirit,
than to be prying into with the curious, searching, fleshly understanding.

[.discourse-part]
Query 5. If the seventh day`'s sabbath be not moral,
and belonging both to Jews and Gentiles,
then how comes it to pass that it was given to all men in Adam,
when there was no difference between Jews and Gentiles
and was observed by command from the beginning,
as appears by comparing together Gen. 2:3. and Ex. 16:18, to 31.

[.discourse-part]
Answer.
That it was given to Adam in innocency, or to all men in Adam, I do not find,
nor do these places quoted make it manifest;
but its being practised before the giving of the law doth not prove its perpetuity,
or that it was not given for a sign:
for circumcision was instituted and observed long before the giving of the law, Gen. 17.
and sacrificing long before that, Gen. 4. both which were signs of the inward,
and not perpetual as to the outward observation of them.

[.discourse-part]
_Query 6._ If when our Lord Jesus saith, (Matt. 5:18) that "`till heaven and earth pass,
one jot or tittle should in no wise pass from the law;`"
if he there meant not the law of the ten commandments,
expressed in Exodus xx, then what law did he mean?

[.discourse-part]
Answer.
By the law is meant the whole ministration of Moses; as by the prophets (ver. 17),
the whole ministration of the prophets:
and that it is not to be restrained to the ten commandments,
is manifest by the instances which Christ gives,
more of which relate to other parts of the law than to the commandments:
for there are but two instances out of the ten commandments;
but there are four instances out of other parts of the law, as may be seen,
ver. 31. 33. 38. and 43. of that chapter.
So that Christ doth not only take in the ten commandments,
but he takes in the rest of Moses`' ministry in the Spirit,
not one jot or tittle whereof is to pass till it be all fulfilled;
but was to stand in the letter to the Jews till full season,
and then in the Spirit till all be finished there also.

"`The law and the prophets were until John;`" from
that time the kingdom of God began to be preached, Luke 16:16.
and both the law, prophets, and John himself were to decrease,
and Christ and his kingdom to increase.
Christ, in this fifth of Matthew, had been preaching the kingdom,
declaring to whom it appertained, and the blessedness of such.
Now this his manner of preaching might seem to derogate from the law of Moses,
and from the prophets, whose doctrine and dispensation hereby he might seem to destroy:
but Christ taketh away the occasion of such a misapprehension,
bidding them not think he came to destroy the law, or the prophets:
for he was not come for that end, but to fulfill.
Wherein he doth these two things:

[.numbered-group]
====

[.numbered]
_First,_ He establisheth that ministration of the law and prophets for its season,
till it should be fulfilled by him the substance,
who was to fulfill all the righteousness of it.
It should last out its whole day,
and should not fail in the least tittle of it (as he himself explaineth it,
Luke 16:17); till the heaven and earth of the Jews passed away. Heb. 12:27-28.

[.numbered]
_Secondly,_ He taketh in the substance of it into his own ministration,
and layeth it more inwardly, and closely,
and largely upon the spirits of his disciples than
Moses had done in the letter upon his disciples;
but he doth not give it out in full,
but only giveth a taste to his disciples how straitly he would
minister it to them by his Spirit as they came under his yoke,
Matt. 11:29, which yoke is the Spirit of the law thereof,
as Moses`' yoke was the law of the letter.

====

Now mark yet further: Christ does not give out the letter for his law,
as it was delivered by Moses;
but requireth somewhat of his disciples which comprehends the letter.
As now when he administers the law against revenge, from whence murder proceeds,
he doth not say, "`Thou shalt not kill,`" as Moses had said to them of old time; but saith,
Thou shalt not be angry without a cause, nor give thy brother any provoking language.
ver. 22. Nor does he say, "`Thou shalt not commit adultery;`" but,
Thou shalt not let out a lustful look, nor let in a lustful thought.
ver. 28.

And had he spoken here about the sabbath, would he have administered it in the letter,
or would he have commanded the observation of the true sabbath, where no work is done,
no fire kindled (nor so much as any sticks gathered to make a fire with),
nor no burden borne; but the man-servant, the maid-servant, the ox, the ass,
and every creature rests in the seed?
"`The Son of man is Lord of the sabbath.`" It is true he subjected himself under the law;
but yet he was still Lord; and he maketh all his,
kings and priests to God! who being once baptized into his death,
know also his resurrection and reign.

[.discourse-part]
Objection.
But all the other commandments are to be kept according to the letter;
for although it should prove so,
that believers are not bound to observe them by virtue
of Moses`' ministration in the letter,
but by virtue of the ministration of the Spirit,
yet the commandments themselves are kept;
but take away the outward observation of the sabbath,
and this commandment hath no fulfilling at all according to the letter.

[.discourse-part]
Answer.
This ariseth from the different nature of the thing:
for the other commandments require or forbid that
which is either good or evil in its own nature;
but this is but good or evil by institution or command.
To keep a day, or not to keep a day, is not good or evil in itself,
but as it is commanded, or forbidden, or left at liberty in the Lord,
and according as it is done or forborne by him who received the command or prohibition,
or is let into the liberty of the gospel. Rom. 14:6.
So that if the nature of the thing required in this commandment,
had been alike with the nature of the things required or forbidden in the other commandments,
it would have been as durable after the dissolution of that covenant,
as the other things therein contained were;
which vanish not in themselves upon the dissolution of that covenant,
but only pass into a higher way of dispensation,
where they retain their full virtue and strength, even according to the letter,
though not by virtue of the administration of the letter;
another higher and fuller administration of a better
covenant challenging and taking its own place.

[.discourse-part]
_Query 7._ If the seventh day`'s sabbath be not moral, but an abrogated ceremony,
now since the death of Christ;
then wherefore should our Saviour instruct his beloved apostles,
that they must instruct the Christian churches to pray, Matt. 24:20.
that they might not flee on the sabbath,
knowing that their flight would fall out more than thirty years after his death?

[.discourse-part]
Answer.
Great was the hardship the Jews underwent in the siege of Jerusalem,
by that apprehension of theirs that they ought not to do any work
(not so much as of defending themselves) on the sabbath;
which hardship such disciples of Christ among the Jews,
as could not easily be drawn off from the law and Jewish observations,
but still were for circumcision, and keeping of an outward sabbath, might be liable to.
Now Christ, and the apostles after him, were not hasty to withdraw them from such things,
but for a time bore with them therein; insomuch that Paul circumcised Timothy,
and became to the Jews as a Jew; and to them that were under the law,
as under the law himself also.
But the strength of the query seems to lie in this,
That it should bear the name of sabbath from Christ`'s own mouth,
in relation to somewhat which should happen on it more than
thirty years after it should cease to be sabbath.
To which my answer is plain, that that may as well bear the name of sabbath,
as Jerusalem, or the temple, bear the name of the holy place, ver. 15. of the same chap.
For Jerusalem and the temple did as much cease to be the
holy place above thirty years after those words were spoken,
as the Jewish sabbath could cease to be the sabbath.

Now for the sakes of such as have been truly exercised in their spirits
by the Spirit of the Lord (and have felt the powerful work of his grace,
and a building raised up by him), and may yet be further exercised, I shall add this.
Jerusalem was a type of an inward building in the spirits of God`'s people;
both in its rearing up, in its situation, in its standing,
in God`'s dealing with it all the time of its standing; and lastly,
in its downfall and utter desolation.
There is an appearance and building of God in the spirits of his people,
which is to give way to, and be swallowed up in, a fuller and higher appearance.
But the fleshly spirit, getting into this building,
will not give way to the further and more inward and spiritual appearance of the Spirit,
but will have the first building stand as the building,
and will entertain no further appearance of God, than as it can comprehend it,
subject it, and afford it a place in the first building.
Hereupon God distresseth Ariel, even the city which David built (saying within his heart;
surely "`that which I have built will I break down,
and that which I have planted will I pluck up, even this whole land,
so he causeth the overflowing scourge to pass, even over thy whole land,
O Emanuel`"). Now when the enemy enters within the holy city, and within the holy temple,
it is time to flee, and exceeding great distress will befall that disciple,
whose flight is either in the winter or on the sabbath day.
Do not imagine at this; but if the Lord open it not at present, wait his season;
for the thing is true and sealed, both by the openings of the light eternal,
and by sensible exercises and experiences from that light.

Thus I have answered such of the queries as concern the seventh day`'s sabbath.
Such as seem to argue the unwarrantableness of observing
the first day of the week for a sabbath,
I leave to those to whom they are tendered (and of whom
an answer seems so conscientiously and zealously desired,
as I do not see how it can be reasonably neglected or denied),
that by weighty evidence of Scripture he may be reduced, if he hath erred; but if not,
but it be truth which he hath therein held forth,
the Lord may be honored in men`'s bowing and subjecting to every truth of his,
by what instruments soever it pleaseth him to make it manifest.

=== Some Queries,

[.heading-continuation-blurb]
Sent in writing, (upon occasion of an epistle directed to all such
as observe the seventh day of the week for a sabbath) _answered._

[.discourse-part]
_Query 1._ If the whole law of Moses, the law of the ten commandments,
as well as the law of sacrifices,
were both added upon one and the same account for transgressions;
then why doth the Holy Spirit in the Scriptures lay forth such
an antiphitical use of them (I suppose he means antitypical),
the one that sin might abound, Rom. 5:20. the other sacrificing for sin? Heb. 9:7-9.

[.discourse-part]
Answer.
That the law of Moses was added because of transgression,
is manifest from that scripture quoted by me in my epistle,
as well as from other scriptures;
and one end why it was added in relation to transgression, was,
that the offence might abound,
which would make the sacrifice of propitiation for
sin appear more necessary and more acceptable.
And the sacrifices also relate to the sinner, some referring to the sin committed,
others to the thankfulness and acknowledgment due for the peace, mercy,
and blessings of God towards his poor, sinful, erring creatures;
both which were to last till the time of reformation from the sin. Heb. 9:10.
Gal. 3:19. (But that they were both added upon one and the same account,
that I did not affirm; that is wrongfully put upon me.)

Now though both these were added because of transgression,
yet they had not both the same use and service in relation to transgression,
but the one was added to discover sin, and to make it appear exceeding sinful, Rom. 5:20.
the other to blot it out, to take it away, to make atonement for it;
which the sacrifices did,
making the sinner upright and perfect as relating to that outward state and capacity,
though they could not as pertaining to the conscience. Heb. 9:9.

[.discourse-part]
_Query 2._ If the whole law, the ten commandments, as well as the sacrifices,
were representations, figures, or shadows of somewhat relating to Christ, the seed;
then what did they in general, or either of them in particular, represent, figure,
or shadow forth, before they were written in tables of stone,
or since they were written in tables of stone, more of Christ then than now?

[.discourse-part]
Answer.
That the ten words were some of the precepts of Moses,
and appertaining to the first testament or covenant,
all which precepts were sprinkled with blood, cannot be denied.
And the apostle distinguisheth the precepts of Moses under the law,
which were sprinkled with the blood of the sacrifices under the law, Heb. 7:19.
from the precepts of Christ which he writes in other tables, chap.
10:16. which also are sprinkled with blood, but not with the blood of bulls and goats,
but with his own blood;
and he that receives any of these precepts out of the blood of Christ,
cannot truly and spiritually obey them,
though he may strive much to form his spirit into the obedience thereof.
Now the time and season of their signification was
the time which God allotted them under the law,
wherein was the use of signs; but the gospel is a state of substance,
of bringing the life and immortality into the heart,
and into the possession of believers, which the state of the law shadowed.
So that they are not signs since the gospel, since Christ put an end to the law-signs,
shadows, and figures, nor yet before the law to believers,
so far as they were in the new covenant; (for as the thing signified cometh,
so that which signifieth it passeth away) though that was a mixed state,
wherein God gave a taste of both covenants,
before his perfect dispensing or bringing forth of either.

[.discourse-part]
_Query 3._ If the whole dispensation of the law was given to the Jews,
and not to the Gentiles, and so the Gentiles not bound to that law,
but another way for them to know the mind of God; then whether that law cited, Rom. 2:15.
which the Gentiles showed the work of in their hearts,
be another law contrary to that law that was given to the Jews,
even the ten commandments?

[.discourse-part]
Answer.
The law which is the substance, is not contrary to the law which is the shadow,
but is the comprehending and fulfilling of it.
The law in the Spirit (written by God`'s power and presence in
the heart and mind) is not contrary to the law in the letter,
but is a higher and more glorious ministration of it.
The one commandment which God gave by Moses to the Jews, Duet. 30:11.
which was the commandment of life and death,
as relating to their inward and eternal state,
ver. 15. was not contrary to the ten commandments,
which God had commanded them before by another covenant,
which he had made with them as an outward people,
and which was to be their rule as to their outward state;
for they were chosen by God to be a holy people outwardly,
and so an outward rule of holiness and obedience was prescribed them;
but by all their obedience thereto, they could not be justified, but only by hearing,
believing, and obeying Christ, the word nigh in the heart,
and by feeling in the spirit the blood of that one offering.

[.discourse-part]
_Query 4._ If the Gentiles were not bound under that law that the Jews were,
which carried the curse with it;
then which way have the Gentiles redemption by Jesus Christ?
seeing all that are redeemed, are redeemed from the law, and the curse thereof.
Gal. 4:5:13.

[.discourse-part]
Answer.
As they were under the curse outwardly, by transgressing that outward law or covenant,
and so missed of the outward happiness of the holy land,
and still met with wrath and judgments, and at last utter cutting off,
as to their outward state, and as to all their hope from that covenant;
so he that comes to receive the ministration of the law of the Spirit,
will find the curse as abundantly inwardly,
even till that be cut down by the sword of the Spirit, which the curse is to;
and that brought into dominion, to which is the promise and blessing.
So that the Gentiles find as great need to be redeemed from the curse inwardly,
which the inward law brings upon the transgressor, as the Jews did outwardly; yea,
and find a more heavy burden and load than ever the Jews did outwardly.
Paul, when he was alive in the outward administration of the law,
not being acquainted with the inward, he knew little of the curse;
he was according to it blameless, Phil. 3:6.
but when he came to receive the living light
of the spiritual administration of it into his spirit,
then he felt the burden, and weight and misery of sin, and the curse indeed;
and cried out, "`O wretched man, who shall deliver?`"

[.discourse-part]
_Query 5._ If the duration of the dispensation of Moses`' law in the letter was till Christ,
the seed, should come and fulfill it,
and the dispensation of Moses`' law (so stated without
distinction) between that that was perpetual,
and that that was ceremonially vanishing, and so in the fulfilling of it besides;
then what law or commandments that or they were, which,
while Moses`' dispensation was in full force, is said to be perpetually sure,
to stand fast forever and forever, as Ps. 10:11:7,8. and when Christ, the seed,
was come, and had fulfilled all that the Father had appointed him to do,
was established, Rom. 3:31.
and not one jot or tittle of it to pass so long as heaven and earth remain? Matt. 5:18.
and Luke 16:17.

[.discourse-part]
Answer.
That distinction between something in Moses`' law being perpetual,
and something ceremonial, is not sound and proper in this place;
for all that was under Moses`' law was but a shadow, as in that dispensation;
and that testament was dedicated with blood (with the blood
which was a shadow) which related to every precept, Heb. 9:18-19.
and it was all substantial and
perpetual in what it signified and related to.
The sacrifices were substantial in that sacrifice which they signified,
as well as the law and precepts were substantial
in the law and precepts which they signified.
And as the first covenant pointed at a second covenant,
so the laws of the first covenant pointed at the law of the second covenant,
the ministration whereof is from the Mediator of that covenant,
and they come into the heart sprinkled with his blood.
Now the law or commandment, which even under that dispensation,
was to be perpetual and last forever, was "`the word in the heart,`"
and the laws thereof, Duet. 30:14. which Moses by especial order from God,
and according to the tenor of another covenant, directed the Jews to.
ver. 4. For the law, as administered by Moses, in the letter,
is not perpetual or eternal; but as it comes from the Spirit,
and is administered in the Spirit, so it is spiritual and eternal.
That administration was fitted to that people; and, we know, the Lord, if he had pleased,
could have given a fuller administration of his law in the letter than that was,
as Christ plainly intimates divers times.
Mat. 5. But if it had been ever so full,
yet the administration of it in the letter is to
give place to the administration of it in the Spirit;
so that the administration of it in the letter is not perpetual,
but for the time which God allotted it;
but the administration of it in the Spirit is eternal and perpetual,
and there it remains an eternal light, witness,
and sword against sin and the transgressor.
And thus it is established in the hands of the Spirit,
after the season of that ministration of it in the letter was ended;
and thus not one jot or tittle of it was to pass away, after the other ministration,
with every jot and tittle of it, was ended.

[.discourse-part]
_Query 6._ If the coming of Christ in the flesh;
and his fulfilling all the righteousness of the law;
and being foretold by Moses to be that prophet that was
to be heard in all things (which is not denied by us);
but if by these he put an end to the law of the ten commandments,
and gave forth another law to his house or family; then what law that is,
and whether it be contrary to that law that he with the Father gave forth,
as Duet. 33:2. with Ps. 80:17. which now is in gospel ministration holy, just,
good, as Rom. 7:12 and spiritual.
ver. 14.

[.discourse-part]
Answer.
It is the law of the Spirit, or the light of the Spirit in the heart,
which discovers sin (not only in the outward acts, but in its principle, rise,
first motions, and inward nature), giving forth his living commands against it.
This is the law now, in which the believer is to begin, Gal. 3:3.
and according to which he is to go on to perfection.
For as the believer is begotten of the Spirit, and born of the Spirit,
so he is to receive the ministration of his law from the Spirit, and in the Spirit.
He receives a gift of faith, a measure of faith from the eternal spring of life,
and that is his law.
His law is the law of faith.
The light of life, which he receives in the faith,
opens the mind and will of Christ to him in the Spirit, showing him both sin,
and also the things of God more fully than the law of Moses could,
though opened by the Spirit; for it is a fuller, a deeper kind of ministration,
and so opens the things which it ministers more fully
than a ministration of an inferior nature can.
Yet it is not contrary to Moses`' law, but comprehends all the substance,
all the righteousness and equity of it (as I said before),
which it as a shadow represented, and commanded to that outward or shadowy people,
the Jews.
But the law which Paul spake of, Rom. 7.
was the law of the Spirit, or such a ministration of the law as Paul knew not,
all the while he was under the ministration of Moses`' law blameless;
but this law found out sufficient blame in him.
ver. 14. etc.

[.discourse-part]
_Query 7._ If Jesus Christ, as he is the Son,
gave forth another law to his house or family;
and that law contrary to that that the Father gave forth;
then whether there are not two lawgivers, when the Scriptures say there is but one. James 4:12.

[.discourse-part]
Answer.
The substance, when it is shadowed out, and or when it is nakedly dispensed,
is one and the same thing; so that whenever it comes,
it cannot be another thing than what the shadow represented it to be.
Moses`' dispensation and Christ`'s are one in Spirit; and when he cometh in Spirit,
he doth not destroy either Moses or the prophets, but comprehends them;
so that the law is but one, although the dispensations of it have been various;
but the proper dispensation of the law now to Christians is Christ`'s dispensation,
not Moses`' dispensation;
and Christians are now to look for light and knowledge
of it in the tables where Christ writes it,
according to his covenant.
So that there have not been two laws given out,
but the one law of God hath been variously dispensed;
in and according to the letter by Moses to the Jews;
in and according to the Spirit by Christ to his disciples.

[.discourse-part]
_Query 8._ If the tables of stone,
the writing of the law of the ten commandments in the tables,
and the law of the ten commandments itself which was written,
were figures or representations;
then whether the finger of God`'s Spirit doth write the law of God two ways,
in the inward table (so called); namely, in the heart of Christ`'s family;
in one way whilst Moses`' dispensation was on foot. Ps. 37:31.
For the Psalmist speaks in the present tense (which was under that dispensation):
now is it another way in this latter dispensation expressed? 2 Cor. 3:3.

[.discourse-part]
_Query 9._ If two ways, then how doth the finger of God`'s Spirit write them these ways?

[.discourse-part]
Answer.
The eternal covenant was the same under the law as under the gospel;
and its tables were the heart then, as well as now;
and its way of writing the same then as now,
even by the finger of God`'s power or eternal Spirit:
and thither the Jews were even then referred for the inward writing of the law. Duet. 30:14.
So that they who truly hearkened even to Moses,
were to wait on this word, which was nigh in the heart,
for the writing of his laws there.
And they that hearkened to this law, which endureth forever,
knew the writing thereof in their hearts: whereas the Jews,
who were very diligent to get the law into their hearts from the letter,
could never thereby attain the writing of it there; but were still found breakers of it,
and under that curse which belonged to the breach.
Abraham, Isaac, and Jacob, David and the prophets, knew the inward Jew,
who becomes so by the inward covenant,
and by the inward dispensation of the law in that covenant;
and the law which was after the promise could not
disannul the promise which was before it:
but it stood good and firm to the children, even to all the spiritual seed,
the whole time of that outward dispensation of the law.

[.discourse-part]
_Query 10._ If not,
then how doth the writing of the law in tables of stone
represent the writing of the law in the tables of the heart;
seeing the tables of the heart were wrote upon by the finger of God`'s Spirit,
whilst the tables of stone were in full force, and the dispensation had not ceased?

[.discourse-part]
Answer.
Though the tables of stone, or law thereof, were in force to that outward people of God,
the Jews; yet this did not destroy his inward people,
nor his inward tables in their hearts, nor hinder him from writing his inward law there;
but the inward and eternal covenant ran underneath to them inwardly,
(even all the time of their outward dispensation) whereby
they were made inwardly righteous and obedient to God.
And as God had particularly directed, by Moses,
to the word and commandment of that covenant,
so he would not fail to write it thereby in the hearts
of such as turned to the word and commandment.
So that this was the law which God wrote in the heart even then,
and was always the inward substance,
while as Moses`' dispensation was but an outward sign thereof.

[.discourse-part]
_Query 11._ If the law of the ten commandments itself, which enjoined love and duty to God,
and love and duty to man, as Matt. 22:37-40, was or is a figure of another;
then what law that is that is the anti-type of this law, which in succeeding of it,
enjoins not love and duty to God, and not love and duty to man?

[.discourse-part]
Answer.
This query ariseth from a great mistake,
as if the law in the letter and the law in the Spirit could not require the same thing;
whereas they do require the very same thing in substance, but several ways,
according to the difference of each administration; to wit, the one literally,
of a literal or outward people; the other spiritually, of a spiritual or inward people;
one requires love according to the tenor of the letter,
the other according to the Spirit.

[.discourse-part]
_Query 12._ If the owning of the ten commandments,
as they are plainly laid down in the letter, be a breaking of them in the Spirit,
and especially those contained in the first table;
then how doth the truth of God written, which is life and truth, Acts 7:38.
and Ecc. 12:10. and the Spirit which is given forth, meet together;
seeing the Spirit leads and guides into all truth?

[.discourse-part]
Answer.
I do not know any who have said, "`that the owning of the ten commandments,
as they are plainly laid down in the letter,
is a breaking of them in the Spirit;`" but he that hath the Spirit
owneth the dispensation of the letter in its place and season:
but the Spirit doth not teach them to run from his own dispensation (where it is livingly
administered to such as wait on the eternal Word in his covenant of life for it),
to that dispensation which was appointed for, and given forth to, others.
But that the truth, as it is written (outwardly), is life, I do not read;
but otherwise, 2 Cor. 3:6. where Paul saith,
the letter killeth (speaking of the letter of the New Testament).
The Spirit indeed guides into all truth; but it is the living soul whom he so guides,
and it is the living truth into which he guides in the new covenant;
though it was he also who gave forth, required, and was able to lead into,
the letter of the old covenant.

[.discourse-part]
_Query 13._ Whether,
when Jehovah gave forth the ten commandments plainly as a law in the letter,
he did intend, by the observation according to the letter,
the breach of them by the Spirit?

[.discourse-part]
Answer.
The Spirit doth not teach to break the commands in the letter;
but such as are under the ministration of the letter,
to observe them according to the letter:
and such as are under the ministration of the Spirit,
to fulfill the righteousness of them in the Spirit.
Yet the Son of man is "`Lord of the sabbath;`" and
if he bid a man "`take up his bed and walk,
which was bearing a burden and doing of work on the sabbath-day,
it is no breach of the sabbath.
Now this is most righteous;
that as the Son`'s rest should be entered into under the gospel,
so the day of rest should be kept by his disciples and family.

[.discourse-part]
_Query 14._ Whether to say,
the keeping the law of God according to the letter is a breaking of it in the Spirit,
be not a charging of God, that gave it forth to be kept,
and the Holy Spirit that incites us so to do now in this administration, James 2:8.
and says they do well that do so;
and yet thou sayest they break it in Spirit: but tell us by any one scripture, how a man,
assisted by the Spirit to own Jehovah alone to be his God
according to the letter of the first commandment,
doth break the command in the Spirit?
Or so the like of any other of them.

[.discourse-part]
Answer.
This query is altogether from a mistake; for it was not said by me,
that "`the keeping the law of God according to the letter is a breaking
of it in the Spirit;`" but that he that "`runs back to the law in the letter,
to take up any command as held forth in it,
will be found a breaker thereof in Spirit.`" And for this, the Jews in general,
and Paul in particular, may be my instances;
who was exceeding strict according to the letter of the law,
but yet was a grievous breaker of it in Spirit; and did not love his neighbor as himself,
but, in a blind zeal, was a bitter persecutor:
and if the Jews had taken that direction of Moses, Duet. 30:14.
the observation of the law in the
letter might have been more easy to them.
So that the turning towards, and receiving the Word in the heart,
from whence the letter came, is the only way to fulfill the letter;
and the law is not so much as to be known, much less fulfilled,
by running to the letter of it in the first place.
And this I certainly know, that there is no coming to the Lord of life,
nor no keeping chaste to him, but in the new covenant, and in the light of the Lord,
as it is there dispensed: and till then,
the mind cannot forbear making of images and false representations of him to itself;
though being from the light of this covenant, it cannot discern that it doth so,
no more than Paul by the letter of the law,
could discern that he was a breaker thereof in his violent persecutions.

[.discourse-part]
_Query 15._ Whether the prophets, Jesus Christ, or the apostles,
by their keeping the law according to the letter (that they did so is evident),
did break the law in the Spirit?

[.discourse-part]
Answer.
The prophets were under the law as to their outward state;
though inwardly not without feeling the virtue of the new covenant.
Christ also was made under the law,
and took upon him the fulfilling of that dispensation of Moses,
that he might bring the believing Jews from under it into the liberty of the Spirit;
that they might receive the adoption of sons,
and the free ministration which was appointed for the sons,
and might not be held under that ministration of
bondage which was appointed for the servants.
And the apostle bids believers to stand fast in the
liberty wherewith Christ had made them free,
not making themselves debtors to the law. Gal. 5:1.
For they were children of the promise, children of New Jerusalem,
the free woman, children of the new covenant, and not children of Mount Sinai,
the old covenant, the law in the letter.
chap.
4:15,16.

[.discourse-part]
_Query 16._ If there be but one day of rest holy to the Lord,
and all the sabbaths of the law were but signs of it,
that is said to be the day of redemption which the Lord hath made:
then whether that day be a day natural, one of the seven days of the week,
which either respects the day on which our Redeemer suffered,
or that on which he rose again from the dead, or any other?

[.discourse-part]
Answer.
As the gospel is not natural, but spiritual; so its day of rest is not natural,
but spiritual likewise.
Yea, I may add this also, the six days`' work in the new creation is not natural either.

[.discourse-part]
_Query 17._ If not so,
but that it should be intended applicable to the day or time of the gospel-administration
from the time that Christ suffered in the flesh unto the end of the world:
then whether this day, that is intended as a sabbath,
is one with that day that the Scriptures intend and call a sabbath,
which Christ himself gave his disciples charge to have respect unto in their flight. Matt. 24:20.

[.discourse-part]
Answer.
The supposition here put,
demonstrates that those that put it have no acquaintance with the gospel-sabbath;
but propose another outward time for it,
even the time from Christ`'s suffering in the flesh, to the end of the world.
Now if any should so affirm, it were as justly to be excepted against,
as pressing the observation of the Jews`' sabbath is.
That which signifieth is outward or natural,
and signifieth to that part which is without:
that which is signified is inward and spiritual, and is known, entered into, kept,
and enjoyed in the Spirit.
It is a spiritual sabbath, not a natural,
which God hath instituted for his spiritual people,
after he hath led them out of spiritual Egypt,
and teacheth them to worship him in Spirit and in truth.

[.discourse-part]
_Query 18._ If they intend one and the same sabbath-day,
then how impossible was it for the disciples of Christ to escape fleeing on that sabbath-day,
though ever so fervent in prayer, in regard that this sabbath spoken of,
began when Christ had suffered, and put an end to the dispensation of Moses`'s law:
and the flight spoken of by Christ, which respects the Lord`'s sabbath,
was not until many years after Christ`'s sufferings.

[.discourse-part]
Answer.
The supposed sabbath being before denied, the foundation of this query fails.

Christ`'s sabbath is not an outward time or day in the flesh; but a day in the Spirit;
even a day of rest from all the labors of the fleshly part.
But this was spoken to before, in the answer to the last of W. Salter`'s queries,
whereto I may add this:
Christ spake to his disciples of things as they were able to bear them.
Now as they understood not his death,
so then they understood not the abolishing of those
things which were to pass away after his death;
so that Christ might very well call Jerusalem the holy place,
and the seventh day the sabbath, speaking to them in that state.

[.discourse-part]
_Query 19._ If they intend not one and the same sabbath-day,
then which are the disciples of Christ to have respect unto;
whether that that Jesus Christ enjoined his disciples to have respect unto,
or that that Isaac Penington would enjoin the disciples to have respect unto.

[.discourse-part]
Answer.
This query hath very little in it,
save to show the unsavoriness of the spirits of them that put it,
and their want of acquaintance with the ministration of the Spirit.
They that know the gospel-sabbath (which is the substance
of the law-sabbath) can tell who enjoined it them;
and can also tell that he hath not required of them the observation of the Jews`' sabbath.
But they that are born after the letter have been always
subject to revile and reproach the truths of the Spirit,
and those that testify thereto.

[.discourse-part]
_Query 20._ If the Lord`'s holy sabbath be that day which we may suppose is intended,
by this paper sent unto us,
to be the day that contains the time of gospel administration;
then whether that sabbath doth prohibit outward labor, as well as abstaining from sin?
If not, then which way must this sabbath be kept?
seeing that they that did and do observe the weekly sabbath, did and do it in the spirit,
and rest by faith in Christ, worshipping the Father in Spirit and in truth.

[.discourse-part]
Answer.
The gospel-sabbath begins not in the observation of outward time; but as it is spiritual,
so it hath a spiritual beginning, increase, and perfection,
wherein there is a rest to the spirit from sin, and from the creaturely works,
and a worshipping in the Spirit;
even as on the outward sabbath there was a bodily ceasing from labors,
and an outward worshipping.
And he that heareth the joyful sound of deliverance from sin and self-working,
and entereth into the faith (beginning to cease from his own works and working,
and to wait in the Spirit on the power for its working in him),
hath a taste of the gospel-sabbath,
and beginning to see that day which the type pointed to, and ends in.

[.discourse-part]
_Query 21._ If that that was ministered to Paul, Rom. 7.
thou shalt keep the sabbath, or believe in the light, follow the light,
and the observing of either of these in the Spirit, be a keeping the whole law;
then how are the Scriptures observed,
if the keeping of one commandment be a keeping the whole law,
when the Holy Spirit in Scripture says, that he that offends in one point,
is guilty of all? James 2:10.

[.discourse-part]
Answer.
I did not say, that the keeping of one commandment is the keeping of the whole law;
but that the observing in Spirit any one of those there mentioned by me,
is the keeping of the law: which was not barely said, but demonstrated;
because no part of the law can be broken, but every one of these must be broken.
He that commits any sin breaks the gospel-sabbath,
which is a resting from all sin and self-works;
errs from the law of love received in the Spirit,
which shuts out all enmity and transgression both against God and man;
departs from the fear, which keeps from departing from God by any iniquity;
and enters into the lust, where is the womb of sin,
out of the compass of which womb sin cannot be conceived, much less committed.
So that Paul, in that law received from the spirit, thou shalt not lust,
saw the whole body of sin struck at; whereas before,
under the ministration of Moses in the letter (according to which he said he
was blameless) there was not so much as the life of one sin struck at;
but for all his exact answering of the law according to that ministration,
he was alive still.
To decide this controversy, let it be put to trial;
let any one singly wait on the Lord for the administration of his law in the Spirit,
and if the Lord give forth that command to him,
"`Thou shalt not lust,`" in the clearness of the light of his eternal Spirit, let him try,
if, continuing in obedience and subjection thereto, he can commit any one sin whatsoever.
I do not say, that a man`'s proposing to himself that he will not lust,
or his striving of himself to love and fear the Lord,
or his applying himself to keep the sabbath, or rest from sin, to the Lord, will do this:
nay, this is but an administration in the letter,
and will prove weak against the inward strength of the enemy;
but receiving the law in its pure, living administration in the Spirit,
and from the Spirit, here comes strength against the enemy, which is too hard for him,
while it is abode in.
And this the Apostle Paul taught the Galatians, who were running backward toward the law,
and not forward in the Spirit:
he bids them "`walk in the Spirit.`" Gal. 5:25. And so doing,
as they should not be under the law,
ver. 18. so neither should they be breakers of the law:
for within those bounds sin enters not, but is kept out;
not so much as a lust against the law being there known,
much less any open transgression against it:
and against such as thus keep within the bounds of the Spirit there is no law,
ver. 22,23. but against all that make themselves debtors to the law of the letter,
there stand in force both the law of the letter, and of the Spirit also; and they cannot,
in that state, be free from the condemnation and curse thereof,
whatsoever they may imagine concerning themselves, and their own state,
from a misunderstanding and misapplication of the Scriptures.

==== The First Letter Answered.

There is a double ministration of the law: a ministration in the letter,
and a ministration in the Spirit.
The ministration of the letter was by Moses, from Mount Sinai, in tables of stone,
to that outward people, the Jews: the ministration of the Spirit is by Christ,
from Mount Zion, in tables of flesh, to believers, or his disciples.
Now this is it which the Lord hath made manifest to me, that the disciples of Christ,
or believers,
are to have recourse to their administration for the receiving of the law from the Spirit,
and not to run back to that ministration which was literal and outward,
and fitted to a literal and outward people.
This was more fully set down in my epistle in several particulars.
Now in opposition to this, it is said,

[.numbered-group]
====

[.numbered]
_First,_ That all, written in that epistle, makes no more at all against a gospel,
spiritual observing in love the seventh day sabbath to the Lord,
than they make against a gospel, spiritual observing of the other nine commandments.

[.discourse-part]
Answer.
My epistle striketh not at a gospel, spiritual observation of any thing;
but he that will obey spiritually, must receive his command from the Spirit,
in that way which the Spirit hath chosen to dispense it to him.
Now the same Spirit which wrote his law in the letter under the old covenant,
writeth his law in the hearts of believers under the new covenant, Heb. 8:10.
which is a better covenant, and of which covenant Christ is the mediator,
ver. 6. and Christ is as faithful to give forth the
laws of his Spirit in the hearts of his people,
as their condition requires them,
as Moses was to give the law written in the tables of stone to his house. Heb. 3:5-6.
And as Moses pointed his disciples to Christ coming in the flesh,
so Christ pointed believers, or disciples, to the Comforter, the Spirit of truth:
first to wait for him, and then to receive light or his law of life from him:
and this is gospel, or new covenant,
even that which the Spirit speaks or writes in the heart: and this hath power in it,
and saveth; whereas the letter killeth.

Now consider seriously, whither should a believer go for these laws?
To which covenant?
To Moses`' covenant, or to Christ`'s covenant?

[.discourse-part]
_Secondly,_ That all these commands, being holy and good, are to be loved,
and in love to be observed, etc.

[.discourse-part]
Answer.
All the statutes, and judgments, and ordinances,
and precepts of the Lord are holy and good, and are to be loved;
but each is to be obedient to that which God requires of him,
and to have recourse to that ministration of the law of God to him,
under which God hath set him.
He that believes, he that hath received the Spirit,
is to have recourse to the law of faith, and to the Spirit, for his light or law:
he who was under the law of Moses, was to have recourse to the law of Moses;
for the law of Moses spake to them who were under it in his family,
giving forth the precepts, or the commandments of that dispensation,
to them who were under his testament. Heb. 9:20.
And Christ speaks to his family by his Spirit,
whom the disciples are to hearken unto, and not to grieve him, or quench his motions,
or despise his prophesyings; but give diligent heed thereto, until the day dawn,
and the day-star arise in their hearts.

Now to obey in love doth not make the distinction of the ministrations;
for love belongeth to each ministration.
The Jews, in their day, were to obey the law in love, and to have it in their hearts. Duet. 6:5-6.
But this makes the difference,
the Jews were to seek to the letter for it;
the disciple is to receive it from the Spirit; for he is to begin in the Spirit, Gal. 3:3.
whereas the Jew`'s beginning was in the letter.
And this is obedience in the newness of the Spirit,
when the law is received fresh from the Spirit, who both writes new things,
and brings to remembrance old things livingly and powerfully:
but to go to Moses`' ministration, and learn it there,
and get it into the heart from thence,
that is according to the old ministration or covenant,
which was given in the letter to the Jews, as may appear in that place last cited. Duet. 6:5-6.

[.numbered]
_Thirdly,_ That in the same Spirit and love that we have the Lord for our God, etc.,
in the same we are to remember the sabbath-day to keep it holy.

[.discourse-part]
Answer.
The Lord teacheth believers to know him to be the only true God, etc.,
by the law of the covenant of life in Christ Jesus,
which he ministers to their spirits in the Spirit;
whereby he teacheth them so clearly and effectually,
that they need not run back to the tables of Moses`' covenant,
from thence to teach one another to know the Lord;
but they shall all know him from his teaching, from the least to the greatest: yea,
and I may add this; this covenant, by its ministration,
teacheth more clearly than the ministration of Moses`' law in the letter could teach. Heb. 8:10-11.
They that have been with Moses, and have learned the law of him,
under the ministration of his covenant, have yet need of coming to Christ;
but they that have been with Christ, and have learned the law of his Spirit,
by the teachings of the new covenant in their hearts,
have not need of being sent back to Moses.
Moses pointeth forward to Christ;
but Christ (even in the flesh) sendeth not his disciples from his own dispensation
back to Moses (though he also established the dispensation of Moses for its season),
but pointeth them forward to the Comforter, or to his appearance in the Spirit.
And this is the mark of a Christian,
which it is the intent of the letter to direct him to,
and not for him to fix in the letter,
as men have done since the apostasy from the Spirit.

[.discourse-part]
This argument is further enforced thus, because he that said the other,
said this in the same law and spirit.

[.discourse-part]
Answer.
It is true, he that said the other by Moses to the Jews, said this also to them,
and they were strictly bound thereto;
but that which binds the disciple is the ministration of the new covenant,
where Christ writes this law in the minds and spirits of his people,
by which they are bound, and such as are out of that, the Lord,
when he cometh to examine them concerning their faith and obedience, will say to them,
"`Who hath required this at your hands?
Were ye children of the new covenant?
Did ye receive the spirit?
Had ye a measure of faith given you?
Were ye new creatures?
Why did you not keep to your rule?
Why did ye not wait on the spirit, and receive the law from the New Jerusalem,
from whence it issues forth to the family of believers?`" The Jews
were to be taught by precepts and judgments from Moses;
but "`all thy children shall be taught of the Lord.`"

[.discourse-part]
It is said yet further, "`so that if thou keepest the other, and not this,
thou art a transgressor of the ROYAL LAW of LIBERTY.`"

[.discourse-part]
Answer.
What is the royal law?
What is the law of liberty?
Was the law as it was administered by Moses the royal law?
Or is it the royal law as it is administered by the Son, who is the King of saints,
and writes his law in their hearts, as their King?
Again, was the law, which Moses administered to the Jews, a law of liberty,
or a law of bondage?
Did not the ministration on Mount Sinai gender to bondage? Gal. 4:24.
But in the ministration of the law by the Spirit is life and liberty.
ver. 26. and 2 Cor. 3:17. And this very law,
"`Thou shalt love thy neighbor as thyself,`" is royal, and a law of pure liberty,
and there is no bondage in it thus administered:
but let any man now read it in the letter, and strive to obey it to the utmost he can,
he shall find it weak through the flesh, accusing and imbondaging him.
And this is the reason that Christians so mourn in their prayers,
even as persons in bonds, because they know not the royal law of liberty;
because they feel not the love which the Spirit begets,
but strive to get the letter into their hearts,
and to answer the commands in the letter with what love and obedience they can come at;
and this (through not seeing into the true covenant and
ministry of Christ) they call obeying in the spirit.
The testimony of Jesus, Rev. 12:17, is the Spirit of prophecy, chap.
19:10; and his commandments come fresh from that Spirit of prophecy,
which are to be taken heed to till the day dawn, and the day-star arise,
and then a fuller ministration is witnessed than that of prophecy,
even the shining and appearing of that which was prophesied of,
which every believer is to wait for in the prophecies of the Spirit,
and in obedience to those commands,
which come livingly into his heart from the Spirit of prophecy.

[.numbered]
_Fourthly,_ That the fourth command is to be in love kept by all believers.

====

[.discourse-part]
Answer.
All the commands of Christ`'s covenant are to be kept by believers,
according as he pleases to dispense them under his administration in the new covenant:
but the laws of the old covenant are not the laws of the new covenant, as so dispensed;
but only as they are comprehended in the righteousness
which is taught and required by the Spirit,
which is fuller, stricter, and exacter than that which the law of Moses required.

Nor do I hereby go about to teach any to break the least of Christ`'s commands,
but the way to fulfill them;
which is by keeping to the certain knowledge and obedience of them,
in that ministration where Christ hath promised to dispense and make them known to believers,
which is under the ministry of his own covenant,
writing them in their hearts and minds by his Spirit.
And here the keeping of all Christ`'s commands is possible; yea,
this is the only way to have the righteousness of the law fulfilled in us;
for he that keeps the eye which the Spirit hath opened in him close to the Spirit,
shall not be able to break any law of righteousness,
but the righteousness even of Moses`' law shall be fulfilled in him.

Christ is the rest of the gospel (as he is also the holy land):
believing is the entering into this rest; here is his sabbath, and the keeping of it.
Keep in the faith, the gospel rest is kept.
Parting with every lust that he makes manifest,
observing everything that this King calls for by his Spirit,
and waiting for the further manifestation or shining
of the light of his Spirit in the heart:
here is the obedience of the faith,
and the holy and spiritual life and subjection of the living soul to its living King.
Here is the beginning of a true Christian, his growth, his perfection; but as for times,
places, persons, etc., these are of another nature, to another part;
even to that part in man which is to be done away, as he comes into the faith,
and into the rest.
Let that which is invisible, whose habitation is out of the reasoning part,
feel and read me in that which is invisible: for I do not make void the law by faith,
or through publishing the ministry of the Spirit;
but establish it in its ministration in the Spirit to the disciples of Christ;
who keeping to the Spirit, cannot transgress the righteousness of it,
though they may there learn not to esteem one day above another, but to esteem every day,
no days having ever had any real holiness in them one above another;
but only a figurative, or representative, which the substance, Christ and his Gospel,
swallows up: for as his day dawns, those things which were the shadows of it fly away.

==== The Second Letter Answered.

[.discourse-part]
_Objection 1+++.+++_ It is said to be "`dangerous so to hold forth the spiritual sabbatism,
as to deny the weekly sabbath, wherein our Lord Jesus Christ rested, etc.,
and which he blessed and sanctified to Adam and his posterity,`" etc.

[.discourse-part]
Answer.
The gospel is a state of substance, of fulfilling the types and shadows of the law,
by bringing believers into the possession of that which they signified of.
Canaan was a type of Christ, who is the land of the living,
in whom every believer hath a habitation at present,
according to the proportion of his faith: and the sabbath is the day of rest,
which every believer is to celebrate to Christ in this holy land,
which he doth by believing and obeying his Spirit in the faith,
which keepeth him out of the sin, the unbelief, the unrest.
But that the sabbath of the law, the rest thereof, which pointed to the faith,
is still to be held up in the times of the gospel, I know no scripture which so teacheth,
and I know somewhat which teacheth me otherwise.
The day is dawned, blessed be the Lord God Almighty; the everlasting day is dawned,
and the shadows of the law are flown away.

[.discourse-part]
_Objection 2+++.+++_ It is said, that "`Heb. 4. speaks of three rests, the seventh day,
or sabbath rest, Israel`'s rest in Canaan,
and a remaining rest, whereof David speaks.`" Psa. 95.

[.discourse-part]
Answer.
I grant it; there were two rests under the law,
which were signs of the one rest under the gospel.
The two under the law were outward and natural,
the one under the gospel inward and spiritual, answerable to the state of the gospel.
David was not only acquainted with the law state, but with the free spirit, (Psalm.
li) and the eternal law thereof.
He knew the new creation,
the creating of a new spirit (with its travel through the law) and also the new rest.
He knew the circumcision of the heart,
the spiritual sacrifices of a broken heart and of praise;
he could take the cup of salvation, and sing the song of praise to the Lord,
which none can do in the strange land, nor on any other day but the day of rest.
And he incites Israel to this rest, that they might not harden their hearts against it;
but in the day of their visitation enter into it,
by hearkening to the Word which was nigh them,
which gives the entrance through the faith.
"`Today, if ye will hear his voice, harden not your hearts,`" etc.
There is a rest ye are now called to enter into,
as your fathers were called to enter into the land of Canaan;
harden not your hearts as they did; but hear the voice,
hear the word which calls to this rest, believe and enter.
This rest remains, says the apostle; the others were types of it under the law state,
which was to pass away.

[.discourse-part]
_Objection 3+++.+++_ It is said, "`ceremonial signs are done away,
but the ten commandments under the mercy-seat are of another nature:
and that there are signs which are not yet abolished (as the rain-bow, sun, moon,
and stars), but still remain for us to make good use of.`"

[.discourse-part]
Answer.
The mercy-seat under the law is done away, and the substance thereof is come;
and will ye not give him leave to write his law in the tables which he shall choose,
where his disciples may read it with the eye which he gives?
Is his law now to be read in the shadow, or with the outward eye,
or to be looked for under the old mercy-seat of the outward tabernacle?
Or is it to be read with the eye of the new creature, with the eye of faith,
with the eye of the Spirit, in the everlasting gospel, where the life itself is read,
and in other books or writings without, but tidings or relations of the life?
Here Christ, here the Spirit, here the eternal life, here the love, the joy, the peace,
the rest, the purity, which are eternal, are seen, are felt, are handled, are enjoyed:
for the true faith is indeed the substance of the things hoped for,
giving victory over the enemies which disturb,
and a quiet habitation in him who is the rest.

And as touching signs,
I do not say that signs are so done away as that
there is now no good use to be made of them;
but in reading the law, and shadows thereof, the Lord may please, by his Spirit,
to enlighten the spirit of him who reads in his fear to see through them:
but this I do not find,
that so much as any one sign or shadow under the law was
to be continued in that way of service under the gospel;
for indeed to what end should it?
When that is come which it signified, is not its work at an end?
And that that sabbath was given for a sign (as well
as any other sabbaths of the law) I find expressly.
Ex. 31:13 to 18.

[.discourse-part]
_Objection 4+++.+++_ It is said, "`That though Christ`'s law be a new law; yet it is also old,
given of old to the Jews.`"

[.discourse-part]
Answer.
Yea, it is older than so; for it was written in Abel`'s and the other holy men`'s hearts,
long before this covenant of the law in writing was made with the Jews.
And consider well which is now to stand in the times of the gospel,
the writing of the law by the Spirit in the hearts of believers,
as it was written by virtue of the promise before the law was given,
or the outward and visible writing under the law, which was done for the sake of,
and as a suitable dispensation for, that outward people.
It was not thus from the beginning; but after a long time:
for when God chose an outward people,
he chose also this way of writing to signify somewhat by;
which signification is concerning another state; in which state,
that which was signified is to be set up and advanced,
and not the shadows which were significant of it.

It is further said, "`That the Lord writes these things new in his people`'s hearts,
to know the Lord, as their God, and as the God and Father of Jesus Christ,
and as their Father in him; and to love their brethren as Christ loved them.
And he writes this law also in their hearts, '`Thou shalt have no other gods but me;
make no image, exalt my name, keep holy the sabbath,`'`" etc.

[.discourse-part]
Answer.
If God write these things in the heart, are they not to be read there?
If God write them in the new covenant, and in the new tables, shall not I read them there?
And if I can read there in this living book what God writes in it by his Spirit,
is not this nearer to me, and clearer, and read by a more certain eye,
than what I can read with my outward eye in tables of stone?
Oh! do not turn the believer out of his way: do not hinder him from reading in the book,
which is clear and infallible, the clear and infallible things of God.
Will God write in my heart, and will he not give me an eye to read?
Shall he give me an eye to read, and shall I not read therewith?
Thou has here confessed this to be the new writing,
and the new writing belongs to the new covenant;
both which are proper to the gospel state, and to Christ`'s mediation,
who is Mediator of the new covenant.
Heb. 8:6 "`And in that he saith, a new, he hath made the first old.
Now that which decayeth and waxeth old is ready to vanish away.`" ver. 13.

[.discourse-part]
_Objection 5+++.+++_ It is said, "`That love being the sum and substance of the law of the Spirit,
makes no more against the fourth commandment than against the rest.`"

[.discourse-part]
Answer.
Love is the substance of them all, and they are all fulfilled in it;
but they are not after this manner fulfilled; to wit,
that a man should strive particularly to keep them in his eye,
and so labor to fulfill them in love; but rather thus, in waiting on the Lord,
to receive love from him, and to be kept by him in the love;
in this love received they are all fulfilled, and cannot be broken,
and this is an easy yoke.
This is the new birth, and the path thereof; the other is but the old creature,
with its striving after the path and inheritance of life.
And as this love is the fulfilling of the law, so the heart is the tables of this love,
wherein God writeth both the whole and all the parts of his law.
Now I am not against any man, who in singleness of heart, applies himself to the letter;
yet it is but the old way,
and a conversing with Christ after the manner of Moses`' dispensation;
but I must confess that I am for the new covenant, and for the ministry of the Spirit,
which is far beyond the letter;
and though I have known Christ and the laws of his life after the flesh;
yet henceforth my desire is not after knowing him so any more,
but to know him in the eternal life of his Spirit, and to drink of the fruit of the vine,
new with him in his Father`'s kingdom.

[.old-style]
=== A Brief Explication / of the _Mystery_ of the _Six Days`' Labor_, / and Seventh Day`'s Sabbath,

[.heading-continuation-blurb]
For such to behold, the eye of whose Spirit is opened by the pure Anointing;
and who are not so drowned in their Conceivings and Reasonings about the Sense of the letter,
as most of the Professors of this Age are.

[quote.section-epigraph, , Matt. 11:28-30]
____
Come unto me, all ye that labor, and are heavy laden, and I will give you rest.
Take my yoke upon you, and learn of me, for I am meek and lowly in heart,
and ye shall find rest unto your souls; for my yoke is easy, and my burden is light.
____

He that hears the joyful sound of the ever-living power,
calling him by the voice of his eternal light out of the darkness, out of the death,
out of the misery, out of the dominions, territories,
and deep slavery of Satan unto himself,
and cometh unto him in the virtue and power of that life which calleth,
he hath a taste given him of the eternal rest, and a promise of entering into it.

But the entrance into the fulness thereof is not presently;
but he hath a long journey to take from Egypt, the dark land; from Sodom,
the filthy land; from Babylon,
where all the vessels and holy things of God have been defiled,
through the wilderness unto Canaan;
and many battles are to be fought with enemies by the way,
and also with the enemies which possess the holy land;
and many hardships to be undergone in following the Captain,
who also leadeth his Israel by a pillar of cloud by day,
and by a pillar of fire by night;
and there must be a circumcision and baptism in the cloud and in the sea,
and the falling of all those carcasses in the wilderness, which are not to enter,
nor so much as see, the good land, before the entrance be ministered to the seed,
and to that which passeth through the water and through the fire with the seed.
In plain terms, there must be a taking up of the yoke,
and a learning of Christ under the yoke, till the proud, the stiff, the stubborn,
the wise, the wilful, the selfish spirit, the hard, stony heart,
be wasted and worn out by the cross, and nothing left but what becomes one with the seed,
and so is fit to be married to it, and to enter with it into the everlasting kingdom.

Now this bearing the yoke, this taking up of the cross,
this following of Christ in the wilderness, through the corrections of the Father,
through the buffetings and temptations of the enemy,
in the midst of all the weaknesses and frailties of the flesh, going when he bids go,
standing still where he stops, fighting when he prepares for the warfare,
bearing the repulse when he suffers the enemy to prevail, and hoping, even beyond hope,
for his relief and victory in due season: here is the labor, here is the travail,
here is the working under the life,
with the measure of grace and power received from the life.
So that, first, the day-spring from on high visits;
from that visitation there is light entered into the heart;
by closing with that light there is grace received;
with this grace received there is work to be done for God;
his talent is to be improved all the six days,
by all that will rest with him on the seventh,
and that desire to cease from their labors in the fruition of the faith, the life,
the power; the power living, becoming, and performing all in them.
And he that doth not improve the talent; he that doth not follow on in the pure light,
but either sits down by the way,
or is deceived with an image of what once was true in him,
he can never arrive at the land of rest (though perhaps
he may arrive at that which he may call so),
but when the eternal witness awakes in him, he will find the want of it,
and bitterly bewail his grievous mistake.

Now in this hard travail and grievous labor under the close
laws and spiritual commandments of the life (hard I mean,
yea, very hard, to the unrenewed part,
though easy and natural to that part which is renewed and born of God),
it pleaseth the Lord now and then to give a day of refreshment,
causing his life so powerfully to spring up,
that it even sensibly is and doeth all in the heart.
This is a sabbath,
wherein the soul rests in the powerful movings and operations of the life,
and doth not find any stress of trouble, or hardship, or labor upon it;
but sits still in the power, is at ease in the life, in the eternal virtue, which lives,
and moves, and is all in it; and no pain, no trouble,
no grievousness of any command is felt; but to it all is easy, all is natural,
all is purely pleasant; the life (to which all its own laws, statutes, ordinances,
judgments, ways, and paths are easy) performing all it calls for,
even as fast as it calls for it.
And here, not only a sabbath of days, but also a sabbath of weeks, yea,
sometimes a sabbath of years (besides the everlasting jubilee,
or year of perfect redemption itself) is known and witnessed
by such as have waited on the Lord in singleness of heart,
under the yoke of his Spirit, for the bringing down of the rough and untoward nature,
and for the raising up of the meek and lowly heart.

But here it is exceeding easy running out, and starting aside;
it is easy running out from under the yoke,
to avoid the bitterness of the hardship to the earthly part;
it is much easier running out on the day of rest,
and so losing the truth in a joy and rejoicing,
even such a one as might have a true ground.
Oh! who can but think the bitterness of death is past, when all enemies are vanished,
and there is nothing left but the Lord and the soul embracing each other!
And who can but be unwilling to come back again to his labor,
and to the residue of his hard travail afterward?
And yet it is far better to return to the work in the vineyard,
and to suffer again with the seed, than to keep up the rest in a notion,
and so to lose the life and pure presence and virtue of the seed, when it returns unto,
and calls back to the labor.
Oh, how many have perished here! suffering a divorce from that which led them into the rest,
not being willing to go back again with it to fill up the residue of its sufferings,
which were yet behind, and so have kept up a false, dead, notional rest,
after the true sabbath was ended.

Now there is no way for such, but to wait to feel the living breath,
the quickening virtue, the day-spring from on high, which,
by the brightness of its rising, can discover this false rest, this dead rest,
this notional rest, this ease in the earthly, in the fleshly, in the understanding part,
which they uphold by things they have formerly gathered from the Scriptures,
or from their own (perhaps once living) experiences;
but now hold out of the feeling and possession of the life, in the dead part.
But that it is thus with them they can never see,
until the light from which they have erred spring up and discover it to them;
and when the light doth arise and discover it, they will find the way of return,
and the path of redemption, much more difficult to them than it was at first:
yet it is better to part with the ease of the flesh,
and to undergo the pangs of a new birth,
than to miss of the inheritance in the good land.

There are three steps or degrees of the blessed estate: First, there are desires,
thirstings, and breathings, begotten after the life.
Secondly there is a laboring in the service (under
the yoke) by the virtue which springs from the life.
Thirdly, there is a rest, or sitting down at ease in the life.
By the stirring of life in the soul, desires after life are kindled.
He in whom the desires are kindled, and who feeleth the eternal virtue,
cannot but be running the race;
he whom the Spirit of the Lord findeth faithful in running the race,
it pleaseth the Lord ever and anon to be giving him a taste of the rest.
Thus the spring stirring, the soul cannot but move towards its centre;
and as it entereth into and fixeth in its centre, it partaketh of the rest.
Now to know the leadings of the Spirit forward and backward into these, into desires,
when he pleaseth; into the labor and service of the life, when he pleaseth;
into the sweet rest and perfect repose in the life, when he pleaseth;
here is the safety and sweet progress of the renewed spirit.
That man who is born of the Spirit is to wait for the movings, breathings,
and kindlings of the Spirit in him: and when the Sun ariseth,
he is to go forth to his labor in the light thereof,
and in the night and withdrawing of the Sun, to retire;
and when his seventh day of rest comes, he is to receive it from, and enjoy it in,
the Spirit; and afterwards to be willing to begin his week again,
even till his whole race and the full course of his pilgrimage be finished.
Yet if it were possible for man, after he is come to Christ, to abide perfectly with him,
to cease from lust, to keep within the faith, to draw naturally in the yoke,
to bow in the spirit continually to the Father of spirits,
there would be a continual sabbath kept in the passage, even before the great, full,
and perfect sabbath in the end.
The hardness and uneasiness of the labor is because of a part contrary to the life,
which, when it is worn out, there will be no more labor,
but the yoke will become the rest,
and all the motions and operations of life will flow forth naturally in the rest.
And here is "`the patience and faith of the saints,`" to wait under the yoke,
under the daily cross to that part which is to be brought and kept under,
till all the bonds of captivity be broken through by the life,
and the veil of flesh rent from the top to the bottom (the remaining
of which is that which stops the free current of life),
and then shall the soul enter into the holy of holies,
obtaining the full possession of the everlasting inheritance,
and of the eternal redemption, and know sorrow, tears, bonds, sickness, death,
captivity (no not so much as grappling with them, or travelling out of them) no more;
but the enjoyment of the plenty and fulness of the life,
reaping all the pleasant fruits of life in the rich land of life forevermore.

=== Some Considerations Propounded to the Jews,

[.heading-continuation-blurb]
That they may Hear and Consider,
and their Hearts at length may be turned towards that which alone is able to Convert them to God;
that they may once more become his People,
and enter into an Everlasting Covenant with him that may not be broken;
that so they may abide in his Love and Covenant of _Life,_
and remain his People forever.

[.numbered-group]
====

[.numbered]
_Consideration 1._ What great love, mercy, and kindness God showed to that people,
above all nations and peoples under heaven!
Of his own free love he set his heart upon them, choosing them to be a people to himself.
He brought them out of Egypt, by a mighty hand and an outstretched arm;
he mightily preserved them in, and led them through, the wilderness.
He entered into a covenant with them to become their God,
and betrothed them unto himself for his own lot and inheritance.
He gave them righteous laws, judgments, statutes, and ordinances,
both of worship towards him,
and of an upright demeanor and conversation among themselves, and towards all men.
He drove out the heathen from before them, and gave them a pleasant land to possess,
even the glory of all lands, a land flowing with milk and honey.
He built a habitation for himself among them; first a moving sanctuary or tabernacle,
afterwards a more settled abiding place or temple (which Solomon built),
wherein was the ark of his presence,
where he was to be sought unto and inquired of by them,
and towards which their prayers were to be directed; and there was a mercy-seat,
whereof they had large experience, and he ever and anon sent prophets among them,
to reprove their errors and backslidings, and to set them to rights again.
He raised up judges likewise to defend them;
and although they were weary of his government, desiring a king,
after the manner of the nations, so vehemently, that they even forced a king from him,
yet he took him away from them, and after him, chose "`a man after his own heart,
to feed Jacob his people, and Israel his inheritance;
who fed them according to the integrity of his heart,
and guided them by the skillfulness of his hands.`" What should I say more?
What was wanting of love, of care, of goodness, of kindness, of mercy, of gentleness,
of any thing that a people could desire of their God?
I say, what was wanting of all this on God`'s part?
What could he have done more for his vineyard than he did do?
Nay, he emptied upon them all the goodness, all the mercy, love, favor, etc.,
that that covenant would hold to the full; yea, and more too;
for he bare with them more than that covenant required him to bear,
and redeemed them oftener than that covenant engaged him; "`yea,
many times turned he his anger away,
and did not stir up all his wrath,`" as he might often
have done according to the tenor of that covenant.
"`Yea, in all their afflictions he was afflicted,
and the angel of his presence saved them:`" and he was still ready to say in his heart,
"`Surely they are my people,
children that will not lie;`" at length they will see their error, repent,
and be true to me; insomuch as he was never weary of saving them,
of trying them again and again;
of stirring up his bowels of love and pity to redeem them;
of sending his servants and prophets among them to warn and reclaim them,
even till at last it was manifest, that there was no remedy but he must cast them off,
and provoke them to jealousy by a foolish nation, Duet. 32:20-21.
drawing them nigh to him, who had been worshipping stocks and stones;
making them become a people, who had long been no people;
and casting these out of his sight, making them become no people,
who had so long been his chosen, peculiar people, in covenant with him,
and nigh unto him, above all the families of the earth.

[.numbered]
_Consideration 2._ What constant rebellion and stiffness of
spirit that people all along expressed towards the Lord!
What wild, sour grapes they still brought forth to him; sour love, sour obedience,
sour worship and sacrifices,
such as the pure palate of the Lord could find no relish nor savor in:
But as Moses had told them,
that it was not for their righteousness God chose
them to give them the good land to possess,
for they were a rebellious and stiff-necked people; Duet. 9:6-7.
so it was not for their goodness that God continued his love to them,
for they were all along provoking him. Jer. 44:4.
When God came to show that great mercy
to them of redeeming them out of Egypt,
and bid them cast away their idols, they would not cast away their idols, Ezek. 20:7-8.
neither did they regard that mercy
of redemption from the house of bondage,
and from the iron furnace; but said to Moses, it was better for them to stay in Egypt,
and to serve the Egyptians. Ex. 14:12.
Again in the wilderness,
how did they provoke him all those forty years of mercy;
how did they err in their hearts from his pure fear, and from love to him,
and from faith and confidence in him!
How did they murmur against him, and against Moses and Aaron, their leaders!
How did they forget his works and his wonders continually!
When they came near the land, and should have gone in to possess it, then they would not,
but repined and rebelled because of the tallness and strength of the enemy,
and of their cities; and when they were forbid to go,
then they would go and fight with them.
What should I mention the time of the judges and of the kings;
how often the Lord made them smart by their enemies in their own land;
how often he gave them up to captivity out of their land,
even till at length that great captivity of Babylon befell them,
and since that a greater captivity and desolation than that of Babylon.

[.numbered]
_Consideration 3._ Whether God, having tried this people even to the utmost,
by that covenant which he made with them by Moses in Mount Sinai,
may ever please to try them so any more:
or if there yet remain any mercy or love from God towards them,
whether it is not to be expected another way, and upon another account?
This is very necessary and profitable for them to consider,
that they may not be looking that way for mercy and favor from God;
in which it is never to come,
and so have their eyes and hearts diverted from that
way according to which it is to come;
for this must needs put them back exceedingly, if their eyes be looking out one way,
and the love of God hath chosen another channel to run towards them in.
This may make them refuse the very mercy, love, and redemption, when it comes,
suspecting it not to be it, because it comes not in the way, and after the manner,
that they look for it.
Now God hath expressly said, that when he shall be pacified in them,
and shall look again upon them with an eye of favor, to do them good,
it shall not be by their covenant (which could never last,
but was still broken on their parts), but by his own everlasting covenant,
which he would establish to them.
Ezek. 16:60, etc.
It should therefore diligently be inquired by them,
What covenant it is which is called their covenant.
ver. 61. And what covenant it is which is called God`'s covenant.
ver. 62. That they may withdraw their eyes and hopes from the one,
from whence their redemption, recovery, and mercy cannot come,
towards the other from whence it is to come?
To which query, for their sakes, it is in my heart to return this answer.

====

[.discourse-part]
Answer.
Their covenant is that which they entered into with God,
the covenant that their hearts chose to unite with God by: and that was to this effect.
"`That if God would show them his will, they would obey it.
Go thou near,`" said they to Moses "`and hear all that the Lord our God shall say,
and speak thou unto us all that the Lord our God shall speak unto thee,
and we will hear it and do it.`" Duet. 5:27. Thus they thought,
but the Lord knew otherwise: for "`Oh`" saith the Lord,
"`that there were such a heart in them!`" etc. ver. 29. and Moses knew otherwise,
he knew that they would "`corrupt themselves,
and that evil would befall them in the latter days.`" Duet. 31:29.
But God`'s covenant was the free covenant he made with Abraham,
Isaac, and Jacob, the covenant of his grace, the covenant of his free love,
whereby he was able to reach them in Egypt,
upon the cry of the seed in them (in the midst of their idolatries,
and to bring them out and do them good,
notwithstanding their stubbornness and stiff-neckedness),
even before the other covenant was made; this covenant of love was God`'s covenant.
This is the covenant God remembered to them in the days of their youth,
while they were young and tender,
and not yet grown up to be a people under the other covenant;
and this is the covenant which lasts forever, which is not founded upon their obedience,
but on God`'s free love to them for his own name`'s sake,
and for their father`'s sake with whom he freely made it.

[.discourse-part]
Question.
What doth this covenant contain?

[.discourse-part]
Answer.
Putting his fear in the heart, writing his laws in the mind, pouring of pure,
clear water upon them to wash away the pollutions of their inward parts,
circumcising the filth of the heart,
healing the backsliding nature by creating of a right spirit within,
and keeping of the created spirit right by the presence of that Spirit which created it.
see Jer. 31:31-32. Ezek. 36:25, etc. Hosea 14:4.
This is God`'s covenant, this is the new covenant,
which is to be made with the house of Israel and Judah when God redeems them;
and they can never be redeemed but by this covenant, but are to remain desolate,
until the Spirit be poured out from on high upon them, Isa. 32:15.
until their hearts be circumcised to love the Lord their God,
until his fear be placed there, and they thereby caused to walk in his ways.
As therefore they receive the Spirit, are brought into the fear,
have the law written on their minds, and become subject thereto,
so will they taste of this covenant, be brought into redemption by it,
and become a glory inwardly, and outwardly also upon the earth.

[.discourse-part]
Question.
What is the way for them to have the fear of God put in their hearts,
to have their hearts circumcised, to receive the Spirit and his laws into their minds,
and so to come into this covenant?

[.discourse-part]
Answer.
There is no other way but that to which Moses himself directed them,
after God had made the other covenant with them, and tried them long by it,
together with many temptations, signs and wonders, both before and after it;
and seeing that by all these they had not a heart to perceive, nor eyes to see,
nor ears to hear, Moses at length directs them to another covenant,
the word whereof would give them eyes to see, and ears to hear,
and a heart to understand.
Which covenant was a covenant besides the former, Duet. 29:1.
and was indeed the covenant concerning life or death eternal, chap.
30:15. (the other being but a covenant of their outward state,
made with them after their coming out of Egypt, upon their deliverance therefrom,
and according to their choice to become a people to God according to it.) This word,
Moses tells them, was near them (nearer than that which was spoken by God on the mount,
and afterwards written on tables of stone).
The voice of this word and the commandment thereof was nearer,
that they need not seek anywhere abroad for it,
but only listen at home to hear its speech, obey it in the faith, and live forever.
Duet. 30:11, etc.
This is the way for them and all men to come into this covenant, and there is no other;
there is a light shining in the darkness of man`'s heart, which springs up in him,
and casts forth its rays to discover and draw him out of the darkness:
now as this light is felt, loved, understood, in spirit,
hearkened and cleaved to in the pure faith, which it begets; that which cleaves to it,
is drawn out of the darkness by it, into the covenant of the pure, eternal light,
where God is, and whither all they are translated,
who are drawn to him in and by this covenant, as they are kept, preserved,
and continue in the faith, love, and obedience of it.
Now I would yet put these few things more to them.

[.numbered-group]
====

[.numbered]
_First,_ Whether that people of the Jews,
as they stood related to God in that covenant (given by Moses at Mount Horeb),
with the covenant itself, and all things appertaining thereto,
were not a shadow of some inward and spiritual thing afterwards
to appear and be made manifest in its season.
Whether they themselves were not a shadow of a more inward and spiritual people,
to be gathered to God by the inward and spiritual covenant;
and whether their outward covenant was not a shadow
or visible representation of that covenant,
and the laws of it a shadow or representation of the inward laws,
which were to be written in the hearts of that spiritual people?
Was not their tabernacle, or temple, a shadow of the true tabernacle, or temple;
seeing God dwelleth not in temples made with hands, but in a poor, humble,
contrite spirit, and in the heart that trembles at his word? Isa. 57:15.
and chap.
66:1,2. So was not their circumcision a shadow of the circumcision
which is to pass upon the hearts of God`'s chosen?
Were not their sacrifices types, or representations,
of the sacrifices of praise and of a broken heart? Ps. 51:17.
and Ps. 50:14. Was not their Canaan, or holy land, a type of the true,
holy, spiritual rest, which the faith gives entrance into?
Their city Jerusalem, a type of the Jehovah-shamma?
Their priests and Levites, types of the spiritual priesthood,
which was to offer the pure offering and spiritual sacrifices among the Gentiles? Malachi 1:11.
Mark that place, if it did not plainly foretell the casting off the Jews,
with the rejecting of their offerings, priests, and Levites,
and God`'s raising up a seed among the Gentiles,
where he would have a more acceptable people and worship, even a pure, spiritual people,
and a pure, spiritual offering.

[.numbered]
_Secondly,_ If they were types, representations, or shadows of somewhat spiritual to come,
then were they not to give place to that which is spiritual when it came,
and so to be swallowed up in it?
Is not the spiritual glory the glory?
The inward Jew, the Jew inward?
The circumcision of the heart, the choice circumcision?
The offering up of praise and of a broken heart, the acceptable sacrifice?
The land of life and righteousness, the true land of rest to the living by faith?
Is not the spiritual city, house, or temple which God builds,
the Jerusalem or temple of the new covenant?
Is not this the choice house to God?
And is not this spiritual glory to be expected in the days of the Messiah,
and all the types and shadows of Moses, which pointed at him, to end in him,
when once he comes to set up his true, inward, invisible,
substantial glory among his inward and spiritual people?
When the day of Messiah dawns, shall not Moses`' shadows fly away?
Oh that your eyes were opened to behold the inward glory of life,
the good things of the new covenant,
the great treasure and riches which are revealed and possessed
in the Spirit by the spirits that are redeemed unto God,
that ye might partake thereof;
and then your eye would not be so much on that which is outward; which, if ye had,
even to the utmost of your desire, is not comparable to the inward!

[.numbered]
_Lastly,_ Search the prophets, see if the Messiah is not first to come in a despisable way,
as a man of sorrows, Isa. 53:2-3.
whose visage in that appearance was to be more marred than any
man`'s. Isa. 52:14. And consider whether he was not to be cut off,
though not for himself, Dan. 9:26. and then to sit at the right hand of God,
until his enemies be made his footstool,
Ps. 110:1. before he come in that glory wherein ye expect him.
So that if he be not thus come already, then that coming of his is yet to be expected,
and his hands and feet are yet to be pierced by you,
and then afterwards ye may look upon him whom ye have pierced, Zech. 12:10.
and all the families of Israel mourn bitterly apart for it.
ver. 12.

====

When Moses gave the law, the veil was over his face;
your fathers were not able to bear the light wherein the law was given,
nor the light wherein the prophecies of the prophets were given;
and so they still erred from the law,
were offended at the prophets while they were alive,
and misunderstood their words after their death.
Now do not ye search into Moses and the prophets
in the same spirit of error as your fathers did,
being shut out from the light of them, even as they were?
If it be thus, if the veil be over your hearts, if ye be ignorant of the true light,
of the true eternal power wherein the Scriptures were given forth,
ye must needs misunderstand them, misunderstand Moses, misunderstand the prophets,
misunderstand the things spoken concerning the Messiah;
and so not be able to see unto the end of those things ministered by Moses,
and of that ministration which was to pass away;
nor into the beginning of the ministration of the Messiah, which was to succeed it.
Oh, turn within to the word nigh in the heart! that the
true Jew may be begotten and formed in you,
and his light may arise and overspread you;
that in that light ye may see the light of Moses, and the light of the prophets,
and not gather false meanings from their words,
but understand them aright in the same holy Spirit,
and enjoy the blessedness they spake of and directed to,
which lies in the inward raising up of an inward seed,
and not in an outward conformity of the outward man,
while the heart and mind remains unchanged and unrenewed;
which can never be made new by any ministry of the letter without the Spirit,
but alone by the ministry of the Spirit, whether with or without the letter,
as he pleaseth.

[.signed-section-signature]
I+++.+++ P.
