[short="Queries Concerning the Work of God"]
== Some Queries Concerning the Work of God in the World / which is to be expected in the latter Ages thereof;

[.heading-continuation-blurb]
With a few Plain Words to the Nation of England,
tending towards stopping the future breakings forth of God`'s Wrath,
both upon the People and Powers thereof;

[.heading-continuation-blurb]
With an advertisement related to the present State of Things.

[.section-date]
1660

[.discourse-part]
_Query 1._ Whether the kingdoms of the earth shall
not one day become the kingdoms of the Lord,
and of his Christ, wherein the Lord God Omnipotent shall reign,
and man`'s glory and greatness fall, that God alone may be exalted in that day? Rev. 11:15,17.
Isa. 2:11-12. 17:22.

[.discourse-part]
_Query 2._ When shall this be?
Whether this is not to be expected upon the recovery out of the antichristian apostasy?
Whether the man-child is not then to be expected to be so born and brought forth,
as to rule all nations with a rod of iron? Rev. 19:6.
and chap.
12:5.

[.discourse-part]
_Query 3._ When the Son of man comes to take the government to himself,
to give forth the law out of Zion, and the word of the Lord from Jerusalem, Isa. 2:3.
whether he shall find faith on the earth?
Whether he shall find the kings and powers of the earth ready to receive him,
and the professors willing to submit themselves unto him?
Or whether they shall generally combine against him, and he be fain to overcome them,
before he can reign over them? Luke 18:8.
Rev. 17:12-14. Ps. 2:2-3.

[.discourse-part]
_Query 4._ Why these things may not be expected in this our day,
and be already begun in this our nation,
seeing so many strange things have happened among us, as have not in many foregoing ages:
God having so strangely raised up a generation to do service for him,
and so strangely again brought them down,
when they had so long and so often showed themselves unworthy of, and unfit for,
so great a service, by still seeking themselves,
and forgetting the Lord that raised them!

[.discourse-part]
_Query 5._ How the kingdoms of the earth are to become
the kingdoms of the Lord and of his Christ?
Whether it be not by taking his yoke upon them, by submitting to his laws, his cords,
and bands?
By giving up whatsoever is unjust, unrighteous, harsh, and oppressive;
and coming under the bands of righteousness, meekness, and equity? Ps. 2:10-11.
Matt. 11:29.

[.discourse-part]
_Query 6._ Whether the Lord be arisen to shake terribly
or no (as was long ago prophesied he should.
Isa. 2:19)? For the Lord will once more shake both heaven and earth. Heb. 12:26.
There hath been a sore shaking in this nation:
the foundations of government, yea, the very foundations of religion have been shaken,
that that which cannot stand might be removed out of the way,
and give place to that which cannot be shaken.
ver. 27. Consider therefore whether these be the beginnings
of the great and terrible day of the Lord God Almighty,
or only some such ordinary shakings as used to happen
according to the course of kingdoms and states,
which are subject to changes, alterations, and dissettlement?

[.discourse-part]
_Query 7._ When God beginneth to shake the heaven and
earth in nations (according to that great shaking,
which is to be after the antichristian apostasy, Rev. 4. and chap. 16.)
whether there ever can be any firm settlement again upon the old foundations?
There may appear some hopes and probability of a settlement again,
which man may be tempted to fasten upon;
but this will but provoke God to shake more effectually:
for when God once ariseth to shake, he will not give over till he hath made that fall,
which he began to shake. Rev. 11:13.
_O England, take heed!_

[.discourse-part]
_Query 8._ How the kings, powers,
and nations of the earth may secure their standing in that day?
Whether there be any way for them so to do, and what is that way?
Whether there be any other way but kissing the Son, submitting to his bands,
being willing to be bound with the chains of righteousness, love, and meekness,
from all unrighteousness and oppression,
both relating to their fellow creatures and to his people? Ps. 2:12.
and 159:8.

Come, O nation of England, be bound!
O powers of this nation, take the Lord`'s yoke upon you; seek righteousness,
seek meekness, seek the good of all; not in words and pretences,
but in truth and uprightness.
Seek out that which is of God in every one of your hearts, and let that govern for God.
Do not smite any for obedience to the living God, but come ye also under his yoke,
that what is not of God in yourselves, but an enemy to your souls, may be yoked down;
and let all laws be formed, directed, and managed, to reach the unrighteous,
that the rod of the wicked may not always lie upon the lot of the righteous,
Ps. 125:3. nor oppression and self-will sit in the seat of judgment,
and pass (because of its power and authority) for righteousness. Ecc. 3:16.
and 4:1. O ye powers of England! save yourselves
and this nation from the terrible stroke of God,
which is very near.
And let not this following advice be disdained by you, but consider seriously of it.

_Take heed how you call any to account for what they have done against you._
There was an extraordinary hand of God in these things;
and in falling foul upon instruments, ye may clash against him before you are aware.
For their iniquity the Lord hath laid them aside, and raised you up again,
giving you another day of trial; let that suffice, and look now to your own standing,
that ye also do not fall by following their example of iniquity and unrighteousness.
But if you will call them to account for any thing,
let it be for being unfaithful to God and the people of this nation,
to whom they made large promises, but performed little.
And that which God required of them (and the nation
had reason to expect from them) do ye now perform.
Give all men the liberty of their consciences towards God;
let them follow him out of the fashions, customs,
and worships of the world without interruption;
and let there also be a narrow search after what is unjust, unrighteous,
and oppressive in any kind; and as fast as it is discovered let it be removed,
that the nation may grow out of vanity, out of unrighteousness,
into solidity and righteousness;
and that the fear of offending man may not affright any from fearing, obeying,
and worshipping of God in Spirit and truth, as he requireth;
and then God will bless this nation and the powers of it.
For the Lord God taketh not pleasure in overturning of nations,
or breaking in pieces the powers thereof: yet if they will by no means hearken,
but harden their hearts, and stand in the way of his counsel and design,
he cannot spare them. Isa. 27:4.
Therefore stand not in battle against him, but bow before him,
O ye great ones of the earth! become low and little, that his wrath may pass by you;
let go your own strength and greatness, and take hold of his strength,
that ye may make peace with him,
ver. 5. and do not go about to limit the Spirit of God in his people;
that will most certainly ruin you!
The Lord God hath begun to bestow his Spirit upon his sons and daughters,
as in days of old, even as before the great apostasy and erring from it;
and he requireth their obedience to it;
and who may safely forbid or punish them therefore.
Much lies upon this land in this respect; oh, do not add more,
lest ye sink the nation and yourselves!
Now a little to help the nation and powers thereof the better to digest the work of God,
that they may not run on headily against him to their own ruin and destruction,
let these two things following be considered.

[.numbered-group]
====

[.numbered]
1+++.+++ Whether the people of God, in the days of the apostles, were not a separated people;
a people gathered out of nations, kindreds, tongues, and languages,
(gathered out of the Jewish worship,
gathered out of the Heathenish worship) and separated to God?

[.numbered]
2+++.+++ Whether, after the antichristian apostasy,
there are not a people to be gathered again, and separated again,
from all antichristian ways of worship,
even after the manner as they were before the apostasy
from the Heathenish and Jewish worship?
And so the same gospel which gathered at first, is, after the apostasy,
to be preached to gather men again. Rev. 14:6-7.

====

Consider well of these things, that ye may not set yourselves against the Lord,
to cross him in this work in this nation.
Ye cannot hinder him from gathering his people now out of the apostatized state,
no more than the Jews or Heathens could hinder him from
gathering his elect then out of their corrupt states.
The reformation out of popery was very weak and imperfect;
the Lord waited long for the perfecting of it; but instead thereof,
there was rather a running backwards towards it again.
The Lord hath now at length begun the work himself,
letting forth his Spirit upon his people, and gathering many into it,
and is preparing the stones of his temple for his building,
and he will assuredly build up his church again; ye cannot possibly stop him herein:
ye may break yourselves by attempting to remove this burdensome stone
out of your way (for indeed it doth lie somewhat offensively in the way
of all settlements and governments according to the fleshly wisdom);
but it will fall upon and break all that burden themselves with it,
though not by outward might or power,
yet by that Spirit of life and righteousness which is in it,
which the Lord is with to prosper.
Consider these things in meekness, righteousness, and in the fear of the Lord;
even in that Spirit which is fit to act for God, and not against him.

=== An Advertisement to the Powers and People of This Nation

Because of my dear love to my native country,
and because of the dregs of that cup which the Lord hath already caused it to drink of,
which cannot be spared unless the Lord`'s will be effected without it;
which dregs are so bitter, terrible, and dreadful,
as will make the stoutest hearts to faint, and the most confident countenance wax pale:
I say, for this cause, in love am I constrained to add these few lines more, that,
if it be possible, this nation may apply itself,
in the fear and dread of the eternal majesty and power,
to make its peace with him against whom it hath long
warred (not only by much outward wickedness,
looseness, vanity, and profaneness,
but more especially by setting up an invented form of godliness,
and persecuting the power), and to whom it is not yet reconciled in this matter,
nor found so much as willing to be reconciled.

The Lord God of heaven and earth, of glory, of majesty, of everlasting power, victory,
and dominion over all, who made both heaven and earth,
and hath the command of all things therein, he disposeth of nations, of governments,
of earthly powers according to his pleasure, and who may say unto him, what dost thou?
Who may implead him for making a rich nation poor, a strong nation weak,
or for bringing down the high and mighty, the strong, stout, honorable,
and noble in a nation, and exalting the poor, the mean, the persecuted?
And if he turn his hand again, and lay them flat whom he had lifted up,
and exalt the other even unlooked-for, who can withstand him, or who can contradict him?

Now what is in the Lord`'s heart (who is thus mighty
and absolute) he will certainly bring to pass,
how unlikely, how contrary, how impossible soever it seem to the eye of man.
If he will exalt his despised truth (which always was so
to the eye of the great and wise ones of this world),
or give his people liberty to fear, worship, and obey him;
if he will have truth and righteousness have the dominion in men`'s hearts,
and in the nations, and not in the wills and lusts of men, how great and powerful soever;
I say, if this be his intent,
though generation should rise up after generation to oppose him herein,
yet will he be too hard for them all, and they will all fall before him: and his truth,
his people, his holy, eternal counsel will he raise up,
and cause to triumph over them all.

It is man`'s way to settle himself by outward strength against outward strength,
and then he thinks he is safe; not eying the invisible hand which turns the wheels,
and delights to overturn that which is outwardly strong (and seemeth unremovable),
when it forgetteth him, and opposeth itself against him.
The Lord God loves to take his enemies at the strongest, when they are most wise,
most mighty, even when nothing seems able to deal with them but himself.
This was it overthrew the foregoing powers one after another;
they were courting worldly interest, and strengthening themselves that way;
but overlooking God who raised them, and the work which he had raised them to accomplish.
This turned the hand against them which had been for them,
and how then could they maintain their standing?

Oh! that the present generation could see the ticklishness of their standing,
and consider that this is their day of trial, and that the Lord`'s eye is upon them,
to observe their ways, to see whether they will now mind righteousness,
and the liberty of his people better than formerly they did; and that his truth may,
in its life and power (and not in such a form or
way of worship as they may think good to prescribe),
have its scope in the nation.
The Lord`'s eye and heart is upon his truth, and upon his people;
and as nations or powers deal with that, so will he deal with them.
Oh! therefore be not deceived;
for though the Lord hath often-times long suffered his people to lie under
reproach and persecution (as he did Israel in Egypt for divers ages),
yet at length he hath still heard their groans, and hath arisen to deliver them:
and though Pharaoh afterwards with all his strength went after them,
and made no question but to bring them back again under his subjection
(and there was nothing in appearance able to deliver them from him),
yet he could not, but overthrew himself and his strength utterly.
Ye know not what strong cries and tears were put up to the Lord before these late changes,
that righteousness might be established in the nation,
and that his people might have liberty to worship him in his fear,
and according to the leadings of his Spirit,
without being yoked under any form of worship which
their hearts could not own to be of God.
And when the Long Parliament was unexpectedly raised up,
that was looked upon by many to have been the means
God would have used towards the effecting of this:
and we cannot deny but that God did make use of them in some things for good,
for which his name was honored.
But though that instrument did warp, becoming unfaithful to the Lord,
diverting from his work and service,
towards the seeking and establishing of themselves and their own interests,
and so are at length themselves justly therefore fallen;
yet the work of the Lord is not fallen, as relating to himself; though,
because of the unfaithfulness and self-seeking of the instruments which he began to use,
at present it lieth under much reproach (and that justly as relating to them); yet,
for all this, the Lord himself can bring it about again,
and carry it on with better advantage to his name, truth, and people,
than if it had gone on in their hand: and the more men set themselves to oppose it,
the more glory will God get to himself in effecting it.

Let not, therefore, my true love to the nation, and to the present powers thereof,
be despised by them; but let them fear before the mighty God of heaven and earth,
and in their hearts bow to him, that they may be humbled,
and made fit instruments in his hand for his service,
and not be found enemies against him.
If they will be fit instruments for God to work by, they must be meek, lowly,
poor in spirit, waiting in God`'s fear for his counsel,
and not hearken to the fleshly wisdom of man, which is his utter enemy,
and will persuade, advise,
and instruct them to settle the nation and church
(as they call it) in a way contrary to him.
And remember this word: _Be sure you smite none for obedience to God.
Limit not his Holy Spirit in his people;
but limit the unclean and evil spirit in those who
manifest themselves not to be his people._
This is the true intent of government.
How can he who governs aright under God, hurt that which is of God, and for God?
Or how can he spare that which his sword is given him to cut down?
Oh, how happy were it for the nation, if they would let truth have its scope,
and let righteousness overcome them! and not contend for shadows against the substance;
but let the substance overcome all those shadows which have held it in bondage,
and upheld its enemy.

The great enemy of God, all this night of the apostasy, hath been antichrist;
who hath not been an open enemy only, but hath appeared as if he had been for Christ,
commanding the worshipping and honoring of Christ, yea,
and with a great zeal taking upon him to cause people to
worship according to what he determined to be right:
and thus he getteth into the temple, erecting a usurping authority over the conscience,
setting up and compelling to an invented worship.

Against this kind of worship God hath still been raising witnesses:
but he having the powers of the earth on his side (as was prophesied he should,
Rev. 17:13), hath often prevailed over them. Rev. 13:7.
And so the truth hath been suppressed,
and false worships set up by the powers of the earth,
according to the proportion they have drunk of the golden cup of fornication;
which doth not only deceive in one way of manifest and gross false worship,
but hath many mixtures and mysteries of deceit in it.
Rev. 17:2, etc.

Now God hath a time to call for an account of the sufferings and blood of his saints. Rev. 6:10-11.
He hath a time to judge the great whore. Rev. 17:1.
And when the time of God`'s judgment comes upon the earth,
God begins with his own house first,
and so with that which hath taken upon it to separate from Babylon,
to see what he can find of Babylon therein;
and he will judge that before he fall upon the great body of the mystery of iniquity. 1 Pet. 4:17.
Heb. 10:30.

Now, therefore, it behooves this nation to consider what of Babylon may be found in it,
and to part with it, that it may escape the plagues of Babylon, Rev. 18:4.
which are very bitter,
as ver. 7,8,etc. these are the two main things whereof Babylon is guilty:

[.numbered-group]
====

[.numbered]
1+++.+++ An invented form of worship, a likeness of the true worship;
but not the true worship itself.

[.numbered]
2+++.+++ A persecuting and endeavoring to suppress the power of the truth,
even of the purity of the godly religion and worship, by means of this form;
because for conscience`' sake, men, who are taught otherwise by the spirit of God,
cannot submit and subject thereto.

====

This God is coming down to plead within that great city, Babylon;
and this God will first plead with in thee, O England!
Consider what of this is yet remaining in thee (or what of this thy heart hankers after),
and part with it as thou lovest thy peace.
The Lord is the witness of the integrity and fidelity of my heart to thee in these lines.
It will be hard for thee to escape the Lord`'s hand; yet it is not impossible.
If thou bow before the mighty God, and lie abased in spirit at his feet,
he can open that eye in thee which can let thee see thy danger,
and also the way how to escape it.

[.signed-section-signature]
I+++.+++ P.
