[#common, short="Concerning the Book of Common Prayer"]
== The Consideration of a Position+++<br />+++Concerning the Book of Common Prayer

[.heading-continuation-blurb]
As also of some particulars held forth for truths, by one Edmund Ellis,
styled a minister of the gospel of Jesus Christ.

[.heading-continuation-blurb]
With a warning of tender bowels to the rulers, teachers,
and people of this nation, concerning their church and ministry.

[.heading-continuation-blurb]
Likewise a few Words concerning the Kingdom, Laws,
and Government of _Christ_ in the Heart and Conscience;
its Inoffensiveness to all just laws and governments of the kingdoms of men.

[.section-author]
By _Isaac Penington,_ the Younger

[quote.section-epigraph, , Rev. 16:15]
____
Behold, I come as a thief.
Blessed is he that watcheth, and keepeth his garments, lest he walk naked,
and they see his shame.
____

[.section-date]
1660

=== Preface

Christ, the eternal Son of God, the substance of all the types and shadows of the law,
was made a priest to God, not after the law of a carnal commandment,
but after the power of an endless life.
He came in the power of the Father; he received the power, he ministered the power,
and in the power.
Thus he gathered together living stones,
built them into a living temple for the Father of life to dwell in,
that they may be filled with the power, dwell in the power,
and be to the glory of the power.
The church of Israel, the church of the Old Testament, the church of Moses,
was gathered by the letter, was to be ordered by the letter,
was to keep and observe the law of the letter,
was to have priests and sacrifices according to the letter;
but the New Testament church was to be of true Jews, of Jews gathered in the power,
circumcised by the power, renewed in the power, etc.
So that he is not a Jew any longer, who is one outward,
nor that circumcision which is outward in the flesh: but he is a Jew who is one inwardly:
and circumcision is that of the heart in the Spirit, and not in the letter.
We are the circumcision, saith the apostle, which worship God in the Spirit,
and have no confidence in the flesh.
The New Testament state is a state of substance,
even of that spiritual substance which the law held out in shadows.
The Jew is inward, the circumcision inward, the sacrifices inward, the church inward,
the ministry inward, the worship inward: all is in spirit, in life, in power, in virtue;
the whole state is answerable to the High-priest of our profession,
even after the power of the endless life.
By the eternal Spirit was he made a minister, by it he preached,
("`The Spirit of the Lord is upon me,
because he hath anointed me to preach the gospel,`" etc.
Luke 4:18) "`through it he offered up himself a sacrifice without spot to God.`" Heb.
9:14. And in the same power runs the vein of the whole dispensation of the gospel;
for it is a ministration of the Spirit. 2 Cor. 3:8.
Take away the life, take away the Spirit;
ye take away the stones of this building; ye take away the church;
ye take away the ministry; ye take away all.

Now about this inward building there was an outward court, which had its being, state,
and honor from the presence of the inward life.
The virtue of the inward building did cast a reflection,
and bring forth an outward state (as it cannot but do,
wherever it appears in its riches and glory).
This state stood firm in the days of the apostles,
till God`'s measuring and removing of his temple, altar, and worshippers,
and his giving up of the outward court (it having lost the life and virtue,
which flowed into it from the temple,
while the temple remained within it) to the Gentiles;
who under the Gospel are such as are uncircumcised in spirit,
and can worship in the outward court without the Spirit.

The enemy indeed fought hard against the life and power, but he could not there prevail;
the gates of hell could not prevail against the true church,
which brought forth the man-child, nor against the man-child whom she brought forth;
but the man-child was caught up to God, and the woman fled into the wilderness.
Then that church-state, and worship, which depended upon their presence, was dissolved;
for how could it be otherwise, when both the man-child,
which was the head of the church (from whence the virtue, life,
and influence did flow into the whole body),
and the woman (or church) herself also were both gone out of sight?
So that the ministry of eternal life, and the temple, wherein the life was ministered,
being both removed, they are neither of them henceforward to be found in that place,
where they were beheld before (and where most eyes would be ready to look for them again),
but there where the Spirit had hid them.

Now mark diligently,
what kind of esteem the true church hath had in the world
ever since her disrobing herself of her outward garments,
and flight into the wilderness, and how her true seed have been handled.
The dragon immediately casts a flood after her; her beautiful raiment being put off,
and she clothed in the habit of a widow,
the eye of the world could no longer see and acknowledge her to be the church,
but disdain, reproach, revile her.
This is her lot all the days of antichrist;
she is misrepresented by the dragon`'s flood of reproaches,
and looked upon as a strumpet, as one that pretends to Christ for her Lord and husband,
to his spirit, to his kingdom, to his truth, without a just right;
and the remnant of her seed are still made war with by the dragon.
Who have been the hunted ones, the hated, the persecuted in all nations,
but the tender-conscienced, who receive the law of Christ into their hearts,
bowing to him in their worship and conversation,
and dare not bow or worship according to the doctrines and commandments of men?

Now the true church, or temple, being thus removed,
the outward court becomes the habitation and place of worship among the Gentiles,
all the time of the church`'s abode in the wilderness.
The Spirit of the Lord having left it,
the Heathenish spirit (man`'s earthly nature and wisdom), the spirit of antichrist,
enters into it,
and upholds the form of the former building (so far as it judgeth necessary),
and here it is found worshipping, and making a great show of holiness and devotion,
but in the mean time makes war with the true worshippers,
who cannot worship in the outward court (since the Spirit of the Lord hath left it,
and given it to the Gentiles), but follow the church into the wilderness,
and worship in that temple which God hath removed thither.

Oh! where is the eye which can read these things,
as they are written either in the letter, or in the Spirit.
Antichrist is a mystery of iniquity, which works, and gets up, and reigns,
under an appearance of godliness; and he that will discern him,
and his false ways of worship,
must have that eye which sees beyond the appearance of things, into their nature:
and in this is the discovery of him, and the redemption from him.
And happy is he, who is not "`defiled with women,`" but abideth in the true virginity,
expecting and preparing for the appearance of the bridegroom.

=== The Consideration of a Position etc.

There is a position laid down in some printed letters,
concerning the use of the Common-Prayer-book, tendered by one Edm.
Ellis (who professeth himself to be a minister of Jesus Christ) to Mr. Hughes,
and Mr. Ford (as he styleth them); against which position he entreateth me,
if I find upon my spirit any thing to be objected against it,
to discover it in exact and punctual expressions.
This desire of his is set down in print after the letters.

His position, or assertion, is this: "`That a man may worship God in Spirit and in truth,
in the use of that form of prayer for morning and evening,
which we call the Common-Prayer.`"

Now whoever would weigh this assertion aright, must have the balance of the sanctuary,
and must put it into the scale with an equal hand; and then looking with that eye,
which is given to see the mysteries of the kingdom of God, to him who is born of God,
the truth or error of it is easily discerned.

_True prayer is the breathing of the child to the Father which begat it,
from the sense of its wants, for the supply of those wants._

"`The wind bloweth where it listeth, and thou hearest the sound thereof;
but canst not tell whence it cometh, and whither it goeth;
so is every one that is born of the Spirit.`" John 3:8. God,
by the breath of his Spirit,
begets a man out of the spirit and likeness of this world into his own image and likeness.
He that is thus begotten, wants nourishment, wants the divine warmth,
the breasts of consolation, the clothing of the Spirit, the garment of salvation;
wants the bread of life to feed on; wants the water of life to drink;
wants strength against the enemy`'s assaults, wisdom against his snares and temptations;
wants the arm of the Deliverer to preserve and carry on the work of redemption daily;
wants faith to deny the fleshly wisdom,
that so he may trust and feel the virtue of the arm of the Deliverer; wants hope,
patience, meekness, a clear guidance, an upright heart to follow after the Lord; yea,
very many are the daily wants of that which is begotten by the breath of God,
in its state of weakness, until it be drawn up into the unity of the body,
where the full communion with the life is felt, the heart satisfied,
and the wants drowned.

Now the breathing of this child to the Father from
the sense of these wants for his supply;
that is prayer; nay, though it be but a groan, or sigh, which cannot be uttered,
or expressed; yet that is prayer, true prayer, which hath an acceptance with the Lord,
and receiveth a gracious answer from him.
And he that begetteth the child, teacheth him to pray,
even by the same Spirit which begat him.
In watching daily to the Spirit, the child is kept sensible of the will of the Father,
and in his light he sees the way wherein he is to walk;
he sees also the enemy when he is coming, yea, and the snares he is privily laying,
and he feels his own weakness to withstand or escape:
and in this sense his heart cries to the Father of spirits for preservation;
for him to stand by him; for him to step in in the needful time,
even in the season of distress.
And thus watching to the Spirit, the life of a Christian is a continual course of prayer:
_he prays continually._
This is the living prayer of the living child, which consists not in a form of words,
either read out of a book, or conceived in the mind;
but in feeling the breath of its nature issuing out
from the principle of life in it to the living spring,
which is the Father of it; who by causing his virtues to spring up in it,
nourisheth it to everlasting life.

But now, man who is not born of the Spirit,
but (by conceiving some of the truths of God in the wisdom from
below) hath attained to some change of opinion and conversation,
he pretends to be this birth from above;
though indeed he is born but "`of bloods,`" or "`of the will of the flesh,`"
or "`of the will of man,`" John 1:13. and what God begets in,
and gives to, his true child, he will be imitating,
though he be out of the nature and spirit where the true child is begotten,
and where the true gift of the Father is received by him.
He will be believing,
though he hath not received any proportion of the
living faith from the hand of the Father;
he will be forming repentance and sorrow for sin: though his heart be not turned from it;
he will be hoping in God`'s mercy, although he be both from off the foundation,
and from under the shadow of the mercy-seat; and he will be praying,
though he hath neither received the Spirit, nor been taught by the Spirit to pray;
and so being from that which should guide him,
and teach him the truth and way of worship as it is in Jesus,
he runs out into the inventions and imaginations, and sets up a way of his own choosing;
which he having much considered of, and beat out by reasonings,
and fenced about with arguments, he grows wise in his own eyes,
and now verily believes it to be the way of God,
and that he is able to maintain it against all opposers.
Thus one man, he is for a form; another man, he is against a form,
and for conceived prayers; and each thinks himself able to maintain his own,
and to overthrow the other.
But oh, that that ear were open which can hear the truth! that where there is any true,
honest, upright desire after God, from the simplicity of the heart,
it might not be thus betrayed through the subtlety of the fleshly wisdom,
which lies lurking in the wise, reasoning, knowing part, to betray the poor, weak babe.
The natural man, the reasoning man, the understanding man,
the wise man according to the natural wisdom, cannot understand the things of God.
Here is no learning to pray aright, to believe aright, to hope aright, to mourn aright,
to rejoice aright, etc., but this wisdom must be brought to nothing, 1 Cor. 1:19.
and a man must become a child to all knowledge, as let in this way;
and he that so becomes a child is taught to pray, to believe, to wait, to hope,
and all that is necessary to eternal life.

Now as the Father teacheth to pray,
so he giveth desires or words (if he please) according to the present need.
Sometimes he gives but ability to sigh or groan (if he give no more, he accepts that).
Sometimes he gives strong breathings and plenty of
words to pour out the soul in before the Lord.
But if a man should catch those words, and lay them up against another time,
and offer them up to God in his own will, this would be but will-worship and abomination.
This I have known experimentally, and have felt the wrath of God for it.
That is prayer, which comes fresh from the Spirit; and that is a true desire,
which the Spirit begets;
but the affections and sparks of man`'s kindling please not the Lord,
nor do they conduce to the soul`'s rest, but will end in the bed of sorrow.
Isa. 1.11.

Now as touching the Book of Common Prayer,
or prayers conceived without the immediate breathings of the Spirit,
I shall speak mine own experience faithfully, which is this;
I have felt both these ways draw out the wrong part, and keep that alive in me,
which the true prayer kills.
And he that utters a word beyond the sense which God begets in his spirit,
takes God`'s name in vain, and provokes him to jealousy against his own soul.
"`God is in heaven, thou art on earth,
therefore let thy words be few.`" The few words which the Spirit speaks, or the few still,
soft, gentle breathings which the Spirit begets, are pleasing to God,
and profitable to the soul; but the many words which man`'s wisdom affects,
hurt the precious life, and thicken the veil of death over the soul,
keeping that part alive which separates from God;
which part must die ere the soul can live.

The true prayer is by that which God begets in the virtue of his Spirit,
("`praying always in the Spirit,`" Eph. 6:18. Jude 20) in the time he chooses:
for the Spirit breatheth as well when he listeth, as where he listeth;
and man cannot limit him when he shall breathe, or when he shall not breathe;
but is to wait the season of his breathing, and so to "`watch unto prayer.`"

Now if the prayer be in words,
(for there is a praying without words) then it must
be in those words which he pleaseth to give,
from the sense which he kindleth, and not in the words which man`'s wisdom teacheth,
or would choose to use.
And indeed, in the true religion, and in every exercise of it man`'s wisdom is kept out,
and nailed to the cross, by which means the immortal life is raised,
and grows in the true disciple.
He believes, he hopes, he waits, he prays, he mourns, he rejoices, he obeys, etc.,
in the cross to the mortal part; not as man`'s wisdom teacheth, or would teach,
or can teach any of these things; for his sacrifice is still an abomination,
even to the wise Egyptian part in himself;
(O wise man! abase thyself before the Lord in his Spirit,
that thou mayest read this and live!) but as the life teacheth,
as the wisdom from above teacheth, which breaketh down, shutteth up,
confoundeth and destroyeth man`'s wisdom, while he is teaching his babe.

Thus have I answered in the simplicity of my heart, to the nature of the thing,
so far as the Lord hath pleased to draw forth my spirit; and in sinking down to that,
which thus opened my spirit, my answer may easily be read and assented to:
but to that which is in the disputing wisdom,
out of the feeling of the hidden life and virtue, it may prove a mystery.

Afterwards he also entreateth me to peruse seriously,
and to lay deeply to heart (in the real fear and dread of the great God),
some particulars which he teacheth for truths.

I perceive he is offended at the questioning of his ministry,
and that the main intent of his proposing these is to justify his ministry;
which if they were true, yet the preaching of them would not prove him, or any man else,
to be a minister of Jesus Christ:
for it is not preaching things that are true which makes a true minister;
but the receiving of his ministry from the Lord.
The gospel is the Lord`'s, which is to be preached, and is to be preached in his power;
and the ministers which preach it are to be endued with his power, and to be sent by him.
The apostles themselves though they had received instructions
concerning the kingdom from Christ`'s own lips,
both in his lifetime, and after his resurrection. Acts 1:3.
and had received a commission from him to teach all nations. Matt. 28:18-19.
yet this was not sufficient to
make them able ministers of the New Testament;
but, before they went abroad to preach, they were to wait for the power; Acts 1:4,8.
and when they had received it, they were to minister in it,
that men might be converted to the power, and by the power,
that the faith of persons might not stand in the wisdom of their words,
(which Paul might have abounded in, as well as others) but in the power of God. 1 Cor. 2:5.
And this was it made Paul minister in fear and trembling,
lest the wrong part in him should minister;
lest the earthly understanding part should be holding
forth the truths of God out of the life,
out of the power, and so he should convert men to the wisdom of the words he spake,
and not to the power.
ver. 2,3. This was it he was sent for, to turn men "`from darkness to light,
and from the power of Satan to God;`" Acts 26:18. from the spirit of enmity and death,
to the Spirit of love and life: and this he was careful of in his ministry,
that men might not run away with his words, and miss of the thing.
And this also was the way whereby he discovered true and false ministers: "`I will come,
and know (saith he) not the speech of them which are puffed up, but the power:
for the kingdom of God is not in word,
but in power.`" 1 Cor. 4:19-20. Many men might catch their words,
and run away with them, and preach them; but they could not minister in the power.
Now the kingdom which the gospel ministers are the preachers of, consists not in words,
but in power.
"`God hath made us able ministers of the New Testament, not of the letter,
but of the Spirit.`" 2 Cor. 3:6. The ministry
of the New Testament is a ministry of the Spirit,
and it cannot be without the Spirit.
It is a reaching to men`'s consciences "`in the demonstration of the Spirit and
power,`" 1 Cor. 2:4. and 2 Cor. 4:1-2. which being felt in the heart,
and turned to, this converts them to God.

The ministry of the gospel doth not consist in a bare opening of
the letter (or raising of doctrines and uses from the letter,
which the wisdom of man may easily perform) as the ministry of the law did:
but in bringing men to the feeling of the Spirit,
even of the eternal power of God which redeems,
in turning men from the darkness to the light, in setting their faces towards the power.
The gospel is the substance of what was shadowed out in the law;
and he that ministers it must minister substance.
He must have the heavenly treasure (that is the substance) in his earthly vessel; 2 Cor. 4:7.
and he must give out of this treasure into the vessel which God prepares:
and that he may do this, he must minister in the Spirit, and in the power.
His words must not be such as man`'s wisdom would teach,
or as man`'s comprehension would gather;
but such words as God`'s wisdom prepares for him, and puts into his mouth.
He that will be a true minister, must receive both his gift, his ministry,
and the exercise of both from the Lord: and must be sure, in his ministering,
to keep in the power, or he will never win others to the power:
but in keeping in the power,
while he is ministering and standing in the cross to his own understanding and wisdom,
giving forth the truths which the Lord chooseth to
have him speak in the words which God chooseth,
even in the words which are ministered to him by the power;
in thus ministering he shall save his own soul, and those that hear him,
even all who in fear and meekness receive the ingrafted word,
which is able to save the soul.
For alas, alas! many have received words of truth, and apprehensions of knowledge,
whereby they hope to be saved;
but how few are acquainted with that knowledge which stands in the power,
which alone converts and keeps alive unto God!
Oh, how many souls are to be answered for by them,
who take upon them to be pastors from God, who have fed the flock with words,
_with discourses which they have made,_ and have ruled over them with _force and cruelty;_
but have wanted the love, the tenderness, the light and power of the true Shepherd!
Oh, what will these do when God requires his sheep at their hands!
Oh, that there were an heart to consider!
Ye shepherds of England, little do ye know what is towards you.

Now for those things themselves,
which he saith "`he principally endeavors to make known to
the sons of men,`" there is a mixture in them;
which, if he could singly apply himself to wait on the Lord in the meek, sober spirit,
out of the consultations, wisdom, and confidence of the flesh,
it might please the Lord to make manifest to him.

The first particular of those, which he lays down for truths is,
"`that the good things of this life, honors, riches, etc.,
unless we make use of them in the service of God, are but vanity and vexation of spirit;
and in no wise any more capable to satisfy or content an immortal soul,
than lime, and ashes, and cobwebs, and such-like trash,
are to satisfy and keep in health the bodies of those persons, who,
through the depravedness of their appetite, desire to feed on them.

[.discourse-part]
Answer.
Christ, by his ministry, calleth his disciples out of the world up to the Father;
out of the honor, riches, and whatever else is of the world.
"`How can ye believe, which receive honor one of another,
and seek not the honor that cometh from God only?`" John 5:44. And the rich man,
he bids him "`sell all and follow him.`" And the Apostle John saith, "`Love not the world,
neither the things that are in the world.
If any man love the world, the love of the Father is not in him.
For all that is in the world, the lust of the flesh, the lust of the eyes,
and the pride of life, is not of the Father,
but is of the world.`" 1 John 2:15-16. He that will be a disciple of Christ,
must travel out of the earthly into the heavenly,
leaving all that is of this world behind him, possessing nothing as his portion,
but him who hath called him out of this country, from among his kindred,
and from his father`'s house, to another land, kindred, and habitation.
So that here they are pilgrims and strangers, sojourners and passengers,
unknown to the world, and of a strange garb, behavior, and appearance in it;
not enjoying any thing as the world enjoys; not using any thing as the world useth;
not honoring men, or receiving honor from men, as the world gives or receives honor;
but honoring men in the Lord, and receiving honor from the Lord:
and whatever they seem to retain of the earthly things,
they hold as steward under the Lord; not using or disposing of them, as they think good,
but waiting for the discovery of the Master`'s pleasure, who is to order,
in his counsel and wisdom, all that is his own, to his own glory.
The law requireth a tenth part to be given up to the Lord; the gospel requireth all,
_soul, body, spirit, good name, etc.;_ even that the whole possession be sold,
and laid at the Master`'s feet; and he that keepeth any thing back, cannot be a disciple;
cannot be a soldier of Christ;
but must needs _entangle himself with the affairs of this life._
This is sound and savory, even the truth of Jesus,
as it is known and felt in the renewed spirit; but his words,
if he measure them in the pure light of God, he will perceive not to have sprung thence;
but to have been formed in the earthly wise part; even in that wisdom, understanding,
and comprehension, which is shut out of the mysteries of God`'s kingdom.

For his second, "`That nothing but the enjoyment of God, the fountain of all goodness,
can truly and really content an immortal soul.`" And for his third,
"`That no man can enjoy God, but he that loves him with all his heart,
and with all his soul,
(and for his sake) his neighbor as himself.`" I own both the things themselves,
and these words, and I felt a good savor in them at the reading of them:
only let me say this, if he put men upon striving after these things,
without pointing them to the gift where the strength is received to perform,
and where the waiting is to be for the strength,
he cannot preach them profitably to his hearers.

To his fourth, "`That though every sincere convert, or regenerate person,
loves God continually with his whole heart, as to the habit or root of holy love;
yet whilst he is in the body, he may sometimes fail of the act or fruit of it,
and may offend God through the love of the creature.
Which truth (so much opposed in these days) is clear and manifest in the holy Scriptures;
particularly in the records of the heinous sins of the prophet David, and Peter,
the apostle.`"

[.discourse-part]
Answer.
The Lord _circumciseth the heart_ of believers under the new covenant,
_to love the Lord their God with all their heart, that they may live:
he causeth the plant to spring up out of the dry and barren ground,
which he watereth with his blessing; and he layeth his axe to the root of the old tree,
hewing at it, even till he hath cut it up: he engrafteth the Eternal Word into the heart,
and by it is daily purifying thereof,
fulfilling the good pleasure of his goodness therein,
and carrying on the work of faith with power:_
and the ministry which he gave was for the "`perfecting the saints,`" Eph. 4:12-13.
which ministry exhorted and encouraged believers (from God`'s promises of his
presence and powerful operation of his Spirit in the hearts of his sons and daughters)
to "`cleanse themselves from all filthiness of the flesh and spirit,
perfecting holiness in the fear of God.`" 2 Cor. 7:1. Now that
the corrupt tree shall never be cut down whilst man is in the body,
that the heart shall never be thoroughly circumcised to love the Lord,
but be in danger of "`offending God through the love of the creature,`" this doctrine
and belief springeth not from the pure fountain of life and power;
but the reasoning part hath gathered it from its conceivings beneath the power.

The seed of God cannot sin (for as he is pure which begetteth,
so is that pure which is begotten of him): nor can man sin, who is born of it,
and abides in it: and if God please to perfect the birth and the work of circumcision,
what can hinder a man from being wholly born from it, and from abiding in it?
Indeed a man that strives in his own strength, either against sin, or towards holiness,
may well doubt of ever having it accomplished:
but he that feels the eternal power beginning the work, and carrying it on daily,
cannot doubt but he can perfect it; yea,
and is encouraged (by the feeling thereof) to hope
and wait on him for the perfecting of it.

As for his instances of David and Peter, they reach not the thing:
for though David and Peter did fall;
yet both David and Peter might attain a higher state before they went out of the body,
than they were in before they fell.
David was a great prophet, and Peter a precious disciple;
but yet there was a higher estate to be administered,
even the receiving that which the prophets prophesied of,
and which the disciple was to wait for.
The disciples who had known Christ, and had been taught by him,
and had received a commission from him, to whom all power in heaven and earth was given,
yet were to wait for a further and higher state,
even for receiving "`the promise of the Father,
the power from on high,`" that he that was with them might be in them. John 14:17.
John was as great as any prophet,
and yet he that was least in the kingdom was greater than he.
Read the Acts of the Apostles.
Behold what a precious people was brought forth,
even in the beginning of the apostles`' ministry; how full of faith,
how stripped of the world, how single-hearted to God, and one towards another!
Acts 2:42, etc. and Acts 4:32. etc.
What would these be, abiding and growing up in the vine?
The cutting off of sin is necessary while in the body;
but to make the committing of sin necessary while in the body,
is a great derogation to the power of God`'s grace, and to the mystery of faith,
which overcometh the evils of the heart, and the worldly nature within;
purifieth the conscience from dead works,
and is "`held in the pure conscience.`" Oh that men knew the power,
and the faith which stands in the power! for then would they not judge
it so impossible to be cleansed by the faith through the power.
Oh, that light, that pure light of the Spirit, wherein the living blood runs,
which cleanseth from all sin, and keepeth clean them that abide and walk in it!
If this were but a little felt,
such doctrines as these (which are gathered in the comprehension from words read,
without being let into the thing itself) would soon vanish,
and find no place in the heart where the power dwells,
nor in the understanding which is renewed, preserved, and fed by the power.
For the things of God are to be known and held in the understanding
which is given of God (which understanding is of the Spirit,
and is spiritual), and not with the natural understanding,
which cannot receive the things of the Spirit,
but only a carnal apprehension and sense of the words of the Spirit,
according as a man can beat them out with, and comprehend them in, his reasoning part.

To the fifth, "`That the souls of the faithful are always growing in grace,
whilst they are in the body; and at the instant of death, or separation from the body,
our Lord Jesus shall present them to the Father, without spot or blemish.`"

[.discourse-part]
Answer.
Christ presenteth to the Father, when he hath purified the heart and mind,
and made it fit for God`'s pure life and presence.
He hath received the fulness from the Father,
and hath freely given of his grace and of his truth to the sons of men,
to regenerate them, to cleanse and sanctify their hearts,
and make them fit for God to dwell in.
He sitteth in his temple as "`a refiner and purifier
of silver,`" (who is like "`a refiner`'s fire,
and like fuller`'s soap`") and when he hath purified his disciples, his children,
his Levites, he presenteth them to the Lord, for the Lord to tabernacle and dwell in:
when he hath thoroughly consecrated them,
he presenteth them as kings and priests to his Father,
to offer up "`an offering in righteousness,`" and to reign with him in his kingdom. Mal. 3:3.
Rev. 1:5. And there were some so purified by the leaven of the kingdom
(which purgeth out the old leaven by degrees,
even till at length it hath made the lump wholly new),
that to them all things were pure. Titus 1:5.
There were some "`come unto Mount Zion, and unto the city of the living God,
the heavenly Jerusalem, and to an innumerable company of angels,
to the general assembly and church of the first-born, which are written in heaven,
and to God the Judge of all, and to the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant,
and to the blood of sprinkling.`" Heb. 12:22-24. Thus it was before the apostasy; yea,
and after the apostasy there were some found standing on "`Mount Zion`" again,
such as had learned the "`new song;`" such as "`were redeemed from the earth;`"
such as "`were not defiled with women,`" (with any of the false churches,
or their false ways of worship) but had kept their virginity in the wilderness.
If ye would know who these were,
they were the "`first-fruits unto God and the Lamb`" after the apostasy,
who were thoroughly cleansed by the spirit of burning,
insomuch as "`in their mouth was found no guile,`" but "`they
were without fault before the throne of God.`" Rev. 14:1-6.

The work of the Spirit of Christ in the heart is an inward work,
and doth not consist in outward times or seasons, but in spiritual degrees and seasons;
which when they are finished, the heart renewed, the spirit changed,
the work wrought out: then the glory of the Father is revealed,
the entrance into the everlasting kingdom ministered,
and then there is a sitting down in the everlasting mansion,
even with Christ in the heavenly places which he hath prepared;
where they that are redeemed, and purged, and sanctified, sit together with him:
and as the body cannot hinder his entering into the spirits of his saints,
and his dwelling in them,
no more can it hinder their entering into him and dwelling in him.

Now there are several exercises of spirit, several measures of faith,
and several degrees of life and glory.
Some are under the clouds, some in the sea; some in Egypt, some in the wilderness;
some waiting for his appearance, some in the enjoyment of him already appeared.
In some the work of regeneration, of sanctification,
of newness of spirit and life is but begun; in others it is interrupted,
and they come to a loss; in some it is much carried on, even towards consummation;
and some are already "`complete in him;`" finding fulness of satisfaction in him,
(in whom the everlasting springs are opened,
to the full content of their hearts) and bring forth fruit to him,
to the full content and satisfaction of his heart.
In the apostles`' days there were those that waited for his coming,
and there were those also that knew him come,
and had received the good understanding from him,
and were "`in the eternal life.`" 1 John 5;20.

Yet this doth not exclude growth, for the fulness is infinite;
and though a perfect state may be attained in the perfect gift,
yet there is a growth in the perfection (for Christ who was perfect,
and in whom was no guile, grew in wisdom, and knowledge, and in favor with God and men).
And as God is infinite, so to that which is transplanted into him,
there is no end of growth in him: but the tree, which stands in God`'s holy earth,
by his pure river of waters,
shall grow forever and ever into his endless life and fulness.

To his sixth, "`That no man can so know God as to love him with all his heart,
and with all his soul, but through the knowledge of Jesus Christ, and him crucified: who,
by those grievous sufferings which he endured when he was upon earth,
made satisfaction to the justice of God for the sins
of all those that believe in his name;
so that it is as consistent with the justice, as with the mercy of God,
to forgive them their sins, and make them heirs of eternal life.
God is just, and the justifier of him that believeth in Jesus.`"

[.discourse-part]
Answer.
The knowledge of Christ is life eternal, and in his cross is the spiritual virtue,
which cuts off the uncircumcision of the heart, whereby it is enabled to love the Lord.
Now "`Christ is the Lord from heaven,
the quickening Spirit,`" who soweth the seed of the kingdom in the heart,
and causeth it to spring up; out of which seed the faith, the love, the hope,
the meekness, the patience, and every spiritual fruit springs and grows.
And he that is thus born of this seed,
and receives the knowledge of life which springs from this seed,
he cannot but love him which begat him,
and he reapeth the fruit of all that Christ did and suffered in that prepared body;
and God is both just, and the justifier of him who is thus united to Jesus.
But that man who knoweth not this faith nor is acquainted
with the love which springeth from this root,
and which is of this divine nature,
but thinketh to be justified by applying to himself
what is related in the histories concerning Christ;
this man deceives his soul, and misseth of the true justification; for God is just,
who hath made the promise sure to the seed, and hath shut out man,
further than he is born of the seed, and found in the seed.
But he who abideth in the seed, and in whom the seed findeth pleasure and abideth;
he cannot miss of the promise, of the everlasting righteousness, the reconciliation,
the peace, the joy, and whatever else God giveth to the seed.

To his seventh and last, "`That the ready way to receive Christ, the only light,
by which we may see the way to heaven;
or so to believe in him that we may be saved by him; is to forsake all that we have,
that we may be his disciples: that is to say,
to take off our affections from things on the earth, and to set them on things above,
where Jesus sitteth on the right hand of God;
putting our trust and confidence in the free and in the infinite mercy of God,
through Christ; to be guided by him in all our ways,
to be led by his good Spirit in all those ways of grace and holiness,
through which we must pass before we can attain to glory.`"

[.discourse-part]
Answer.
To know Christ as the light eternal (as he was yesterday, is today,
and will be forever); to trust this light in its convictions, calls,
and free openings of love, to feel its living virtue,
and in that virtue to give up all that is of the earthly nature and spirit;
to sell all for the everlasting inheritance; this is indeed the way to life.
But it is not the doing of things which is of value;
for man may imitate and strive to do much, and may go a great way _in forsaking all,
and in taking off his affections from things_ (inasmuch
as he may give all his goods to the poor,
and his body to be burned, and yet it profit him nothing);
but it is the doing of things in the virtue, in the life,
in the power which comes from Christ, which is of acceptance with God,
and of advantage to the soul.
Every motion and operation of true life springs from the root of life,
and hath the virtue of the root in it;
and that which differenceth it from all men`'s imitations,
and from all the likenesses which the earthly spirit can frame,
is the nature and virtue of the root being found in it.
Therefore he that will be a true Christian, must eye Christ, the spring of his life,
and keep in the feeling of his living virtue,
and in that offer up all his sacrifices of faith, love, and obedience to God;
and he that will be a true minister, must wait upon the power himself,
to be an instrument (in the hand of power) to direct men to this,
and to preserve and build them up therein.

But alas! this is the stone which the wise builders have all along refused!
The builders before the coming of Christ,
they got a knowledge concerning the Messiah to come;
but being unacquainted with the thing itself, rejected both it at its coming,
and also the vessel wherein it appeared.
And the builders, all along the apostasy, got a knowledge of Christ come,
and preached believing in him crucified, as the way to life; but the living stone,
the living thing itself, which is both the foundation, the corner stone,
and the top stone of the building, they have been ignorant of,
and ready to persecute every appearance of it.
Christ can no more now appear in Spirit,
than formerly he could in that prepared body of flesh,
but the wise builders now are as ready to cry out against him for a blasphemer,
a profaner of God`'s ordinances, a deceiver of the people (yea, a witch,
or one that hath a devil), as the wise builders then were.
"`But wisdom`" in all ages "`is justified by her children,`" and of none else.
He that is born of the wisdom, he can discern the womb,
and own the fruit and branchings forth thereof under the mean, dark veil,
whereby it hides itself from all the fleshly-wise of every age.
"`The kingdom of God cometh not by observation;`" the wisest Scribes
and Pharisees could not know it by all the observations which they
could gather out of Moses`' and the prophets`' writings;
nor can any now know it by any observations which
they can gather out of the apostles`' writings;
but by being born of that Spirit whereof they were born,
and by being formed in that womb wherein they were formed,
by this means alone is the thing come to be known which they knew.
He that receiveth the same eye, seeth the same thing, according to his measure;
and coming to the life, wherein they received the truth;
the words which they spake concerning the truth are easy.
Thus as they were written in the Spirit, so are they there alone truly read;
and being so read, they become exceeding profitable to that which so reads them;
but man guessing and imagining and reasoning in his
carnal wisdom concerning the things of God,
and so gathering senses and meanings about the words and expressions of scripture,
doth but build up a Babel,
which the eternal life and power will throw down
(whenever he appears) with that which built it.
Oh that men were wise to wait for the discovery of the true rock,
and of the true builder upon that rock! that that
city and building might be raised in them,
which God alone can rear;
that they might not be left desolate and miserable in that stormy day,
which will shake all buildings and foundations and rocks, but our Rock;
wherein all professors, and preachers, and high notionists,
and whatever sort else can be named (who have stumbled at God`'s living truth,
and at the pure appearance of his redeeming power, which, in this age,
hath mightily broken forth, after the long, dark night of apostasy,
to the sight of every eye which is opened in the Spirit), shall confess with tears,
sorrow, anguish, and shame, that _their rock is not as our rock,
they themselves being judges._
For though all sorts of professors generally own Christ as the rock in words,
yet most miss of the thing; and the subtle enemy hath made use of a notion,
or apprehension of the thing in the carnal mind, to deceive them of the thing,
to keep them from feeling the eternal virtue, the living power of life in the heart,
which is the arm of God`'s salvation,
whereby Christ draws man`'s lost soul and spirit out of the grave of sin and corruption,
up to the Father.
But oh, how are poor hearts deceived! who think, by a believing of what Christ did,
of a satisfaction he made for them while he was here on earth,
though they lie in the pit all their days,
though they carry the body of sin about with them
to the very last of their time here in the body,
and have not felt the arm of God`'s power breaking down their spiritual enemies,
their lusts, their corruptions, and redeeming them from them;
yet hope to be saved in the end, and to be presented without spot or wrinkle to God!
Christ had the name Jesus given him, because he was to save his people from their sins;
and no man can truly and livingly know the name Jesus,
further than he feels the saving virtue of it; but he that effectually feels the virtue,
he indeed knows the name, and can bow at the name,
feeling his lusts and enemies bowed under by the power thereof,
and that raised up in him, which can worship the Father in the Spirit and in the truth.
Oh that the sons of men knew; oh that the teachers and professors of this age knew,
what they have so long reviled and trampled upon!
Surely they would mourn bitterly, kiss the Son, and escape the wrath.

Now, if the Lord please to smite any one`'s earthly wisdom and comprehension (which is the
main thing which stands in the way of the pure openings and revelations of the life),
and give him the feeling of any thing here written, let him in fear acknowledge the Lord,
sacrificing to his goodness, and waiting upon him to be kept in that feeling,
not magnifying or vilifying any of his instruments;
but in meekness and humility embracing the instructions of the Almighty,
from the hand which he pleaseth to give them forth by.
As for me, I am but a shell; and if this party knew me (who sets me up so high,
preferring me above many, whom the Lord hath preferred far above me),
he would soon acknowledge me to be a poor, weak, contemptible one;
yet this I must by no means deny, that the pure liquor of the eternal life,
at its pleasure springeth up and issueth out through me; though I can also,
in true understanding, say, that it issueth out far oftener,
and much more abundantly through others.
Let it have its honor,
wherever it appears! and the Lord bring down that in people`'s hearts,
which hindereth the owning and receiving of its virtue.

=== A Warning of Tender Bowels, to the Rulers, Teachers, and People of This Nation, Concerning Their Church and Ministry

That there was a fight between the dragon and his angels,
and Michael and his angels, concerning the New-Testament church and ministry,
is manifest even from the letter of the Scriptures.
Rev. 12.

That the dragon and his angels, though they could not get the better,
as relating to the power, yet that they did get the better, as relating to the form,
insomuch as that they overcame the third part of the true ministers,
and drew them from their standing in the firmament of God`'s power,
off to their earthly ministry;
and that the church herself also was fain to fly into the wilderness,
from the face of the dragon, for her safety and preservation,
where she was to be nourished and fed by God all the time of antichrist`'s reign;
this likewise is not only revealed in the Spirit, but is also manifest from the letter.
Rev. 12.

That after this flight of the true church, and overcoming of the true ministry,
the dragon erected his false church and ministry (which
had but at best the form without the power) over all nations,
peoples, multitudes, and tongues; this is also as evident,
to them that read the prophecies of the Revelations
in the light of that Spirit that wrote them.
Is not the false woman (after the true woman was fled) manifestly described?
Rev. 17. which hath a bewitching cup of fornications.
ver. 2,4. Mark,
she hath not the true "`cup of blessing,`" her cup is not filled
with the "`wine of the kingdom,`" it is not the cup of the true spouse
(which keeps chaste and loyal to the bed of the husband),
but the cup of fornications,
wherein is a form of doctrine and discipline and order and church-government,
which leads from the life, which bewitches from the power,
which lulls asleep in a form of profession and worship of Christ, without knowledge of,
guidance by, and subjection to, his Spirit.
And this is the government, ministry, and way of antichrist, wherever it is found;
how curiously soever the cup be gilded, yet it is but the cup of fornication,
which bewitcheth the heart with its golden appearance,
and then leads it into adultery from the life.
And the dragon doth not only set up a false church over the nations
(in many parts whereof the truth had before appeared), Rev. 17:15.
but a false ministry also.
There is a false prophet (which deceiveth with miracles and false
appearances of truth) advanced in this corrupt state;
which false prophet continues and upholds his deceit over the nations,
till the mighty appearance of Christ, in Spirit and power, doth judge him. Rev. 19:20.
2 Thess. 2:8. There is a beast
with "`horns like a lamb,`" who "`doth great wonders,
so that he maketh fire come down from heaven on the earth, in the sight of men,
and deceiveth them that dwell on the earth,`" etc. Rev. 8:13-14.
Insomuch that he draws the kings and inhabiters of the
earth (in a mystery of deceit) into the bed of whoredom and false worship,
instead of the pure way of life, and pure worship of the living God, in his Spirit,
and in his truth. Rev. 17:2.

Is it not further manifest, that this false church and false ministry,
set up in the world by the power of the dragon, persecuted God`'s witnesses to the truth,
in all the ages of antichrist`'s reign?
So soon as ever the church was fled into the wilderness,
the dragon forthwith went to "`make war with the remnant of her seed,
which kept the commandments of God,
and had the testimony of Jesus Christ.`" Rev. 12:17.
"`And it was given unto him to make war with the saints,
and to overcome them; and power was given him over all kindreds, tongues, and nations.
And all that dwell upon the earth shall worship him,
whose names are not written in the book of life,
of the Lamb slain from the foundation of the world.
If any man have an ear,
let him hear,`" Rev. 13:7-9. "`And he had power
to give life unto the image of the beast,
that the image of the beast should both speak,
and cause that as many as would not worship the image of the beast should be killed.
And he causeth all, both small and great, rich and poor, free and bond,
to receive a mark in their right hand, or in their forehead.
And that no man might buy or sell, save he that had the mark, or the name of the beast,
or the number of his name.`" Rev. 13:15-17. Yea, "`the woman`" (the false church,
which the dragon had set up, by his power in the nations,
instead of the true) "`was drunken with the blood of the saints,
and with the blood of the martyrs of Jesus.`" Rev. 17:6. Oh the misery,
and lamentable hard usage of the witnesses of Jesus,
who have been true lambs! born of the power, faithful to the power,
witnessing against every form and appearance of religion, doctrine, and worship,
which hath appeared without the power,
even in the days of greatest profession and highest
devotion under the apostasy from the power;
how have these been hunted, persecuted, devoured by the wolves in the sheep`'s clothing,
who had got the outside, the garment, the name of Christ and Christianity,
the profession of church, ministry, and ordinances, but have wanted the life, the virtue,
the thing itself; and so have turned against it, and kept it down,
that they might keep up their form!
For let but the power appear,
the form without the power is soon detected to be what it is.
And this is properly antichrist and antichristianism; to wit,
not openly to appear in a direct denial of Christ, his truths, and worship,
but to set up a way of knowledge and worship without his Spirit.
Another spirit creeping into the form,
that is antichrist (and the setting up observation
and practice of the form out of the life and power,
that is antichristianism), and this is the persecutor, destroyer,
and devourer about religion.

Now though the Lord hath suffered this false church and
false prophet to reign long in the dragon`'s power,
and to revile and worry his poor lambs, in every age of antichrist`'s reign;
yet the Lord hath appointed a season to judge this false church, Rev. 17:1.
to cast the false prophet into the lake. Rev. 19:20.
Yea, and to torment with fire and brimstone, all the false worshippers. Rev. 14:10-9.

Oh, how deeply doth it concern England! her rulers, her teachers, yea,
the whole people thereof, to consider their ways, to consider their worship,
to consider their church-state, to consider their ministry,
that they be not overwhelmed at unawares in the bitter wrath of the Almighty,
before which there is no standing.
Oh! that they could mourn, and pray, and wait for the eye of God`'s Spirit;
for his pure light, which searcheth and discovereth all the deceits of antichrist;
that they might not be bewitched with any of the
wine of the fornication of the false woman,
"`whose heart is snares and nets, and her hands as bands,`" to entangle her lovers in,
and keep them from the pure bed of life, where the Father of life,
with the Son and Spirit, is enjoyed and worshipped.

If men consult concerning these things in the wisdom of the flesh,
they will be entangled, and err; for that eye cannot see the mysteries of the kingdom,
or the course either of truth or deceit.
The gospel, the eternal truth, the true church, the true ministry, are all spiritual,
(not new shadows, as the things under the ministration of the law were,
but spirit and substance) and they can only be seen
by the spiritual eye of the children of wisdom.
The wise hunters, and diligent inquirers, into the comprehending part,
cannot find the womb or the way of life,
or the way of the worship of that which is begotten in the life,
or God`'s way of ministry,
which he hath appointed for the feeding and preserving of the life.
The prophets of old could not be known, discerned, or owned,
by the fleshly eye of observation in Israel after
the flesh (but they still rejected them,
esteeming and magnifying the false prophets above them);
how much less can the prophets and ministers of the New-Testament be seen by man`'s eye?
Are they the prophets and ministers of Christ, which a nation cries up for such,
and which the eye of the wise men therein admires, and pitches upon?
Or, are those they which the renewed eye, in the light of the Lord, sees to be fitted,
sanctified, and called forth by Christ into that service?
Ah, poor England! must thou fall into the pit before thine eyes be opened!

The great controversy of this age is about church and ministry, which must carry it,
the form or the power?
Whether the church and ministry shall take place which was before the apostasy,
or that which hath sprung up in or since the apostasy?
Whether man`'s wisdom shall determine which is the true church, and its true ministry,
or whether the Spirit of God shall determine it?
Whether a nation, with the ministers it sets up, shall be the church and ministry?
Or whether God`'s holy nation,
(which he calleth and sanctifieth by his Spirit) and the ministers which he chooseth,
and sendeth to gather and build up his in the holy faith, and pure power of life,
shall be the church and ministry?
Our eyes wait on the Lord to see this controversy determined,
and our hope of help is in his arm;
nor are we at all affrighted at the rising of any strength against us,
(our hearts being given up to God`'s truth, and to suffer for its testimony,
according to God`'s will,
meekly and patiently in his strength) but we pity this poor land; yea,
in the depth of bowels we pity the rulers, the teachers, and people therein.
Oh! that they might be humbled, and in fear of the great God, surrender to him his due,
before he appear in his strength to force it from them.

=== Of the Kingdom, Laws, and Government of Christ in the Heart and Conscience, Its Inoffensiveness to All Just Laws and Governments of the Kingdoms of Men

Christ`'s kingdom, God`'s kingdom,
the kingdom of heaven (for they are all one and the same),
is that seed of eternal life which God hath hid in the hearts of the sons of men,
whereby he gathereth them back unto himself,
bringeth them under the yoke of his government, ruleth over them, and reigneth in them.

This kingdom is likened to a grain of mustard-seed, for its smallness; to a pearl,
for its riches, value, and worth; and to leaven, for its spreading nature.
And many other parables did Christ make use of to discover it by:
as to a piece of silver, which the woman that lost it, lighting the candle,
sweeping the house, and searching it diligently, and at length found it,
even there where she had lost it.

Man fallen from God, is become lost as to the Lord,
and as to his own happiness in the Lord:
being driven from his blessed presence and divine image, life, and spirit,
into the earthly spirit, image, and life, which he chose: yet, in this earth,
in this field of the world, God hath hid somewhat, even the everlasting pearl; which,
when man is awakened to seek, and findeth in the living breath,
in the eternal light of life, it is able to redeem him;
it is able to overspread (he becoming subject to the laws, leadings, teachings,
and power of it) and leaven him into the likeness and image of the pure life and spirit.

Oh that men knew the gift of God!
Oh that men knew the purchase of the blood of Christ!
Oh that men knew that spiritual good thing,
which Christ (who died for them) hath given to redeem
them by! that in that they might be united to Christ,
and so by him be renewed and restored to God.
For as the Father receiveth none but through the Son,
so the Son receiveth none but in that gift which he bestoweth from the Father.
He owneth no faith, no love, no hope, no repentance, no obedience,
but what springeth from that, and standeth in that.

Now as man is born of this,
is leavened by this (as he becomes a fool in his
own earthly wisdom and excellency of the fallen spirit,
and becomes a babe, a child, a simple innocent, etc.), so he enters into the kingdom,
being ingrafted into the root,
through the virtue of this which is given him from the root, and so grows up in this,
and this in him.
And here is the new nature, the new life, the new heart, the new spirit,
in which the unity and fellowship with God is again known,
and the disunion with the world, the wisdom, the interests, the fashions, the customs,
the fears, the hopes, the delights, the joys of this world, and whatever else is of it.
For Christ, as he is not of the world, so he calleth men out of the world;
and they which follow him, and become his disciples, go out of the world after him;
that is, travel in spirit and conversation from what is of the earth,
from whatever is not of the Father, but of the world.
They are not of the world, as I am not of the world,
(saith Christ concerning his disciples, John 17.) therefore the world hateth them.

The laws of this kingdom are given forth in the kingdom, from the covenant of life,
which is made there in Christ.
They are written in the heart, in the mind, as far as it is renewed.
There the fear is put, there the eternal wisdom is opened, there is Zion known,
and the Jerusalem which is from above, and the laws of eternal life issue fresh from it,
and are revealed by the life in the heart which is turned towards the life.
There sin is reproved,
and everlasting righteousness manifested in the light which cannot deceive;
and as the heart is made subject under the yoke, so sin is wrought out,
and righteousness brought in;
and under the cross or yoke of life the blood of
the everlasting covenant runs through the vessel,
to keep it pure, sweet, clean, and fresh in the life.

This then is the government of Christ, to be subject to his spirit, which appears,
and opens his will, in the gift of grace which comes from him; to feel his living breath,
by which the heart is begotten to God, out of the region of darkness;
to know the movings, the stirrings, the leadings, the steps of the Lamb,
who is "`the Captain of our salvation;`" and to follow him wherever he goes,
doing all things that he commands, forbearing all things that he forbids,
"`without murmuring, without disputing.`"

Whoever will be of the inward Israel, the spiritual Israel,
which Christ redeems out of the spiritual Egypt,
and leads through the spiritual wilderness into the land of rest, must know his leader,
must receive his Spirit, and follow it faithfully.
"`If any man hath not the Spirit of Christ,
he is none of his;`" he is none of the spiritual Israel;
and if any man follow not the spirit of Christ through all the travels in the wilderness,
(but either sits down by the way, or lies overcome by any kind of enemies,
and comes not to the end of his journey,
finishing the warfare and fight of faith) he falls short of the rest.
Oh! that men were awakened to consider of things as indeed they are!
For religion is not such an outward form of doctrine, or worship of any sort,
as men generally (whose poor souls are deceived through the subtlety
of the powers of darkness) are too apt and willing to apprehend;
but it consists in Spirit, in power, in virtue, in life:
not in the oldness of any form that passeth away; but in the newness of the Spirit,
which abideth forever; in being born of the Spirit, in abiding in the Spirit, in living,
walking, and worshipping in the Spirit; yea, in becoming and growing into Spirit,
and into eternal life: for "`that which is born of the Spirit,
is Spirit.`" Oh! that the sons of men would hearken,
that they might taste of the sweetness and riches of the goodness which
the Father in his free love hath opened in the spirits of many,
and hath let the spirits of many into!
Oh! that men would suffer the wearing out of this earthly spirit and wisdom,
that they might become like God, be formed into, and live in his image!
How long shall the destroyer in every age prejudice men against
them in that age which seek their good with their hearts?
How long will the world stand in enmity against the generation of God`'s choice,
and provoke the Lord to wrath against them!
Surely the spirit of this world will try it out to
the very last against the Spirit of God!
For indeed the spirit of this world is not subject to the Spirit of God,
nor indeed can be,
and so cannot endure the government of his kingdom (which
is not of this world) to be set up in the sight of it.

Yet the government of Christ and his kingdom is not
opposite to any just government of a nation or people.
Christ`'s government is a righteous government of the heart, or inner man, chiefly;
which doth not oppose a righteous government of the outward man.
Nay, those who are Christ`'s subjects,
and singly obedient to his law of righteousness in their spirits,
are more faithful to men, and more subject to any just law of government,
than others can be: for their fidelity and subjection is out of love,
and for conscience`' sake.
But this is it which offends the world; men many times make laws in their own will,
and according to their own wisdom (now the wisdom of the world is corrupt,
and hath erred from the guidance of God), and are not free from self-ends and interests,
not being gathered into that which cleanseth and keepeth pure the naturals.
Now that which is of God cannot bow to any thing which is corrupt in man:
it can lie down and suffer, and bear the plowing of long and deep furrows upon its back;
but it cannot act that which is against its life.
It cannot be disloyal to its King, to gratify the spirit of this world;
but what practice or testimony its King calls for
against the evil and corruption of this world,
it must obey singly and faithfully.

God, in every age, so bringeth forth and ordereth his innocent lambs and people,
as that they are still offensive to the present age.
The Lord fitteth them,
and calleth them forth to be witnesses against the evils of the present age:
how can they but offend it?
Can darkness choose but hate the light, which speaks against it?
How can darkness in power and dominion bear to be reproved by a mean,
contemptible appearance of the light, in mean and contemptible vessels?
For God chooseth "`the weak and foolish things of this world, and things that are not,
to bring to naught things that are.`" Look into former ages;
how did God reprove the kings and princes of Israel?
Not by the eminent priests and prophets, whom they expected to be taught by,
but by herdsmen, by plowmen, by prophets which they despised.
How did he overcome the heathenish world, yea, and the Jewish corrupted state?
Was it by wise learned men (by the learned Scribes and Pharisees among the Jews,
or by the wise Grecians among the heathen), or by fishermen and publicans?
And how shall the recovery out of the apostasy,
and the reproof of the antichristian world be?
Shall it be by wise synods and counsels of learned
and orthodox men among them (as they speak),
or shall it be by the learning of the Spirit, which such as these contemn?
When God hath the rich treasure of the knowledge of his kingdom to manifest in the world,
he chooses earthen vessels, weak vessels, poor contemptible persons:
he appears there (where the eye of man least looks for him) that
"`the excellency of the power`" might appear to be of him wholly,
and that the vessel might rob him of none of the glory of it.
Now the Lord hath not only chosen,
in this day of his great appearance in Spirit to the spirits of his people,
mean instruments, but mean things also, foolish things, weak things,
the keeping on of an hat, the use of ordinary language, the appearing in mean habits,
and despised gestures; yea,
and in a foolish way of preaching (indeed it is so to that which
hath not the savor of the virtue and power of the life in it);
and how can the wisdom of man but stumble at it?
Who would think that God should require such things, or appear in such things?
O living eternal power! how is thy mighty presence and appearance
veiled from all that look for it in any way of man`'s observation,
or judge it with the eye of man`'s wisdom!
_Verily thou art a God that hast hid thyself from the earthly spirit in its utmost wisdom;
yea, in its utmost search after the knowledge of, and in the midst of,
the highest profession of religion!_
Which of the wise, which of the scribes in this age, can discern any of the paths,
or so much as one of thy footsteps?
Oh that men would fear before the Lord, and be sure to govern in that which is of God,
and then they should harm none of his,
nor hazard the shaking of their government! but whatever is not of God,
both within and without, must fall in the day of God`'s power.
Oh, happy is he who is now made willing to part with
that which God is determined to rend from man,
that his standing may be in that which cannot be shaken!
for there hath been a great earthquake in this nation,
both of things without, and of things within;
and there yet remains somewhat to be shaken, both without and within,
that the glory of God may have room to appear.
O England! "`kiss the Son,
lest he be angry:`" let all such laws and customs as are not of him fall before him;
and whatever is of him, let it bow unto him,
(both within and without) that his wrath break not forth like a fire,
which none can quench; for the Lord hath mighty things to bring to pass,
and he hath a mighty arm of power to effect them by,
and what shall be able to stand before him that stands in his way?
