[#objection, short="Answer to a Common Objection Against the Quakers"]
== An Answer to that Common Objection Against the Quakers that they Condemn All but Themselves.

[.heading-continuation-blurb]
With a loving and faithful advertisement to the nation, and powers thereof.

[.section-date]
1660

=== Objection

It is commonly objected against us, That we condemn all but ourselves;
all the Protestant churches, martyrs, and worthies formerly
(many of whom were valiant champions against Rome,
and divers of them sealed their testimony with their blood),
and all sorts of Christians and professors at present,
who are not just of our stamp and way, though otherwise ever so zealous.

=== Answer

The Protestant churches,
(as they are called in way of distinction from the church of Rome) the blessed martyrs,
who suffered for the testimony of a pure conscience towards God,
and all the worthies of the Lord in their several generations,
who fought against the scarlet whore,
were accepted of God in their testimony against her, and are not disowned by us,
but dearly owned and honored therein;
and for agreeing with them in their testimony in several things,
as against deriving of a ministry from Rome (which Luther wrote against,
and John Huss prophesied of another ministry to arise),
and against maintaining the gospel ministry by tithes,
or any other way of forced maintenance,
which (till Popery grew very strong and powerful) was known to have been free;
and against swearing, etc.
(Walter Brute said, "`The perfection of Christian men is not to swear at all,
because they are so commanded of Christ; whose commandment must in no case be broken,
although that the city of Rome is contrary to this
doctrine of Christ.`" Fox`'s Acts and Monuments,
pp.
460-461. And see also p. 495,
"`Thorpe`'s Testimony both about Tithes and Swearing.`") For these very things,
and such like, (as for following of Christ,
in not receiving or giving that honor which is out of the faith,
and for testifying against the hypocrisies and corruptions
of our age) do we suffer in this our day,
even as they did in their day, from the same spirit that persecuted them; which,
though it hath much changed its form and way of appearance,
yet still retaineth the same nature.

But all things were not discovered at once.
The times were then dark, and the light small;
yet they being faithful according to what was discovered,
were precious in the Lord`'s eyes; and what through ignorance they erred in,
the Lord winked at and overlooked,
being pleased with that sincerity and simplicity of heart
which he had stirred up in them towards himself.
But if they were now alive in these our days,
and should depart from the sincerity which was then in them,
and oppose the light of this age, they would not then be accepted of the Lord,
but their former sincerity would be forgotten.
For the light shineth more and more towards the perfect day:
and it is not the owning of the Light as it shone in the foregoing ages,
which will now commend any man to God,
but the knowing and subjecting to the Light of the present age.
Even as in these our days, there was, some years ago,
an honest zeal and true simplicity stirring in the Puritans
(especially among the Nonconformists of them),
which was of the Lord, and was very dear to him;
and had the generations of this age abode there,
they would have been able to have followed the Lord in every further step,
and leading of his Spirit: but departing from that into some form or other,
the true simplicity withered, and another thing began to live in them:
and so they settled upon their lees, magnifying the form they had chose to themselves,
till at length their hearts became hardened from the pure fear,
even to the contracting of a spirit of profaneness;
insomuch as they could mock at the next remove and discovery of the Spirit,
as some new light;
and so by degrees have grown persecutors of that
Spirit in its outgoings in the people of the Lord,
which they themselves had once some taste of, while they were reproached for Puritans.
And the god of this world, who at first tempted them aside into the form,
hath at length prevailed so far to blind them therewith,
that they can neither see what spirit they themselves are of,
nor what Spirit it is they persecute.

Let therefore people consider the truth of the thing, as it is before the Lord:
we do not cast dirt upon any in whom the truth of God hath
stirred and appeared in any measure in former ages,
or in this our age; but this we testify against; to wit,
the setting up of any form without the life:
for it is the erring spirit that still crieth up the form, to keep down the power,
by the form, and so by the help of it to bewitch from the Spirit wherein is the life,
and not in the form.
This was the painted Jezebel of the apostles`' age;
false teachers finely dressed up themselves with the form of godliness,
and then under this cover they could deny the power, and make head against it. 2 Tim. 3:5.
How easy is it for them to appear
in the form of the doctrines of the gospel,
in the form of zeal, in the form of holiness, to pass in a nation for the true church;
and then to asperse them for heretics, who, appearing in the power,
cannot but deny that form which is without the power.
This is the great witch of this age (even that spirit of zeal and devotion
which is best clothed and decked with the form without the power),
which though men (who judge of the things of God after the flesh) justify, admire,
and much contend for in her several shapes and dresses (some being for one,
some for another), yet the Lord is searching after her,
and will find her out with his eternal flames, which will make her manifest,
and all her lovers shall dread her burning and bed of torment.
Now, as all along the apostasy,
this bewitching spirit (this spirit which bewitcheth from the power),
hath crept up under a form of church worship and holiness;
so the other Spirit (the pure Spirit of life,
the Spirit of true zeal and fear of the Lord),
hath still appeared more and more out of the forms.
Who were the best preachers, and most eminent Christians in the Puritan days?
Were they not those who least minded the form then; nay, indeed,
who were most against the form, and persecuted for their conscientious stumbling at it?
And who were the greatest persecutors then, but they who were most zealous for the form,
both of the government and worship of the church of England?
And where is the persecuting spirit next to be looked for,
but in the forms which should next appear?
And where likewise is the appearance of the true Spirit next to be looked for,
but in those whom the Lord should raise up to testify against those forms,
and to be the succeeding sufferers for their testimony,
as the Puritans had been foregoing sufferers for their testimony.

Yet if there be any persons left,
among any of the forms which have appeared (whether former or latter),
that have not lost their sincerity and true zeal towards God,
them we own and have unity with, so far as they keep, or rather are kept, thereto.
If there be any among the Episcopal sort that in truth of heart desire to fear the Lord,
and look upon the Common-Prayer-Book as an acceptable way of worshipping him,
we pity their blindness, yet are tender towards them,
and would not have the simplicity persecuted in them because of this,
but rather cherished.
If there be any among the Presbyterians, Independents, Anabaptists, Seekers,
or any other sort, that in truth of heart wait upon the Lord in those ways,
and do not find a deadness overgrown them, but a pure fresh lively zeal towards God,
with an unfeigned love to his people, our hearts are one with this;
and we cannot fight against this good thing in any of them,
though in love to them we testify,
that their form and way of worship is their present loss and hindrance;
yet we doubt not but that the Lord (in his time)
will make manifest to such the light of this age;
which is the very thing the people of God, in many foregoing ages, have been praying for.
But this is our lamentation, that forms and ways of worship abound;
but the Puritan principle, the Puritan spirit, is lost and drowned in them all;
and that men are hardened against our testimony,
not from the remainders of the simplicity in them,
but because they are erred from the simplicity, and fallen in league with another spirit,
which hath lain lurking in forms of knowledge and worship (to tempt aside from the simplicity,
and to hide the sight of the life and power from
the panting soul) all this night of the apostasy.

Now mark how easy and natural it is to that spirit to enter into a form,
to cry up a form, to set up a form in a nation, city, or country;
doubtless it had been done in this nation long ago,
had not the mighty hand of the Lord withstood it.
When the evil and unclean spirit is detected and driven out of one form,
if it doth not get another suddenly to appear in, and tempt with,
it must needs loose many of its subjects.
The strumpet, or false church,
is forced (as God discovers her nakedness and lewdness) to change her dresses and appearances,
to new trick and adorn her bed: and then, as if she also were changed,
and were now no longer the same, she comes forth again with boldness,
and tempteth the young man again to come in unto her. Prov. 7:16.
And thus "`she casteth down many wounded; yea,
many strong men have been slain by her.`" ver. 26. Who otherwise
would have "`pondered the path of life,`" chap.
5:6. had they not been ensnared by her flatteries, who "`forsaketh the guide of her youth,
and forgetteth the covenant of her God.`" chap.
2:17. There is no more certain and ready way to suppress truth,
and to betray the honesty which is singly searching after it,
than to present a form of godliness or worship, as the proper way of meeting with it:
for hereby the soul is lulled asleep with a false hope,
until the freshness of its desire begins to die, and its life to wither;
and then the fleshly part easily grows into unity with, and zeal for,
that form which indeed is of the flesh;
though it appeared and tempted as if it had been otherwise.
And how many have gone a great way towards hell,
and have been deeply entangled and distressed in the chambers of death,
by entering into this strumpet`'s church or house,
which they then (through the subtlety of her deceit)
took for the house or church of God! Prov. 7:27.
Consider the thing a little seriously.
When the evil spirit is driven out of his strong-hold of gross Popery,
whither should he run but into Episcopacy?
When he is driven out of Episcopacy, whither should he run but into Presbytery?
When he is driven out of Presbytery, whither should he run but into Independency?
When he is driven out of Independency, whither should he run but into Anabaptism?
When he is driven out of Anabaptism, whither should he run but into a Way of Seeking?
And what is his end of running into Episcopacy,
but to save alive that spirit which was hunted out of Popery,
and could abide no longer there,
and so the better (and the safer from being discerned) to reproach and persecute
the other Spirit (wherever it appeared) under the nick-names of Puritans,
Separatists, Brownists, Round-heads, etc.
And what is his end afterwards of running into Presbytery,
but to save that alive which was hunted out of Episcopacy,
and to persecute the former truly zealous Spirit (where
it should further appear afterwards) by means of that form?
Thus the forms and appearances of things change; but the fight is still the same,
the evil spirit still getting uppermost, under a form of godliness,
and from thence shooting forth its arrows at those that seek after purity of heart,
and cannot but testify against those forms where the impure one lodgeth.

This then is the sum of our answer in this respect;
we are not against the true life and power of godliness, wherever it hath appeared,
or yet appears under the veil of any form whatsoever.
Nay, all persons who singly wait upon the Lord in the simplicity and sincerity of their hearts,
whether under any form, or out of forms,
(that matters little to us) are very dear unto us in the Lord.
But we are against all forms, images, imitations, and appearances,
which betray the simplicity and sincerity of the heart, keep the life in bondage,
and endanger the loss of the soul.
And too many such now there are,
which hold the immortal seed of life in captivity under death,
over which we cannot but mourn, and wait for its breaking off the chains,
and its rising out of all its graves into its own pure life, power,
and fulness of liberty in the Lord.

=== A Loving and Faithful Advertisement to the Nation, and Powers Thereof

O king!
O parliament!
O nation of England! consider before the decree come forth;
before the ruin of the nation (with the powers thereof) be irrevocably sealed:
for the Lord hath a controversy with this nation, and he will plead with thee,
O England! who desirest not, and canst not bear a government in righteousness,
for the suppressing of the evil, and encouragement of the good;
but the good is still suppressed in thee, and cannot grow as it ought,
because of the lust of the nation against the purity of the life of God,
and because of the corrupt wills, ends, and interests of those who still are in power.

After King Henry the VIIIth had renounced and shaken
off in part the Pope`'s authority in this nation,
he did not let it fall to the ground as an evil thing,
but took upon himself the exercise of it,
assuming to himself the headship and government under Christ
in all ecclesiastical causes and matters in his dominions.
The same course his successors followed,
keeping the very title which the Pope gave to him of Defender of the Faith.
And so parliaments in their days (as if the government
of the church were a right and privilege of the nation,
and not peculiar to Christ) have taken upon them to make laws and orders
about the government of the church and people of God in spiritual things,
as well as about matters of state.

Now it would fairly and honestly (with the spirit of meekness,
and in the fear of the Lord) be inquired into,
_Whether the Pope`'s power and authority in this nation was a true church-power and authority._
That is, whether it was such a church-power and authority as Christ had instituted;
or of another nature, even of a nature contrary to Christ,
and to his inward government in the spirits of his people.
For if the Pope`'s power and authority was a true church-power and authority,
then it may be lawful in another hand, though not in the Pope`'s;
but if it was a usurped kind of authority and government in itself,
then it cannot be lawful in itself, nor serviceable to Christ in any other hand;
but will prove an instrument of war against him, in whose hands soever it be put.
And let it be singly considered,
whether the church power in this nation hath not
been a curb to the rising of the purity of religion,
even a sharp check upon the tender conscience; but such as the loose (yea,
profane spirit) would take pleasure in and contend for.

The true church-power is only the power of the Spirit of Christ.
That converts men to God,
and that alone is able to govern them in the affairs of his kingdom, being converted.
Man, meddling with religion and church-government in his wisdom, is but a beast,
and must govern like a beast; namely,
with force and cruelty over the spirit and conscience which is tender towards God.
As the Lord God of heaven and earth never gave the converting power to any,
so neither did he ever give this governing power to any,
further than as they were endued with the Spirit;
for that is the sceptre of his church and kingdom, which is a sceptre of righteousness,
which leads on in the love and gentleness of the
Spirit that which is to be dealt gently with,
and spiritually cuts off, by its severity and sharpness, that which is to be cut off.
And here are Christ`'s limits of government, which that spirit and wisdom which exceeds,
errs, and does hurt both to itself and others.

Now if, in the mist of darkness,
which hath long overspread the earth (for though there broke
out a little light to discover the thick blackness of Popery,
and to cause some reformation out of it, yet the mist was not expelled),
this nation hath erred, her princes, her teachers, her parliaments,
and all sorts of persons, in laying hold on and establishing a wrong church-power,
which power hath had a bad effect; namely,
in suppressing the progress of the reforming spirit, and raising up a formal spirit,
if not a spirit of looseness and profaneness, which ran backwards towards Popery,
and not forwards from it: yet let them not love error,
and so strive against the light which shineth forth to discover the error to them;
but let them humble themselves before Christ, the Lord of all,
and restore unto him that which is his due, lest they provoke him to wrath,
and cause him to take from them what they look upon as their due.
For is it not just with Christ to take that power from men,
which they (so long as they have it) will not forbear
managing and making use of to keep him from his power?
Consider these things, O England! for they belong to thy peace,
and toward the mitigation of thy sorrow and misery in the day of thy calamity.

This is from one who hath mourned over thee, while thou hast been rejoicing.

[.signed-section-signature]
Isaac Penington the Younger.

Oh that thou couldst know, at least in this last hour of thy day,
how to make thy peace with the Lord, and not begin that controversy afresh with him,
which he hath already so much shattered and broken thee about, that the dregs of the cup,
whereof thou hast already so largely drunk, might pass from thee!

=== An Explanatory Postscript

We read of the getting up of another power than Christ`'s in the church,
after the days of the apostles. 1 Thess. 2:4.
Rev. 13:2. which power was to last forty-two months,
even all the time of antichrist`'s reign;
by which power the beast should make war with and overcome the saints in all kindreds,
tongues, and nations.
ver. 5,6,7. And all this wickedness and persecutions of
the saints should be committed under a pretence of righteousness,
as if it were for Christ, and the well-government of his church,
from a true and rightly-derived and well-balanced power. 1 Thess. 2:8-9.
Now this power will last in one form or other,
even till the very coming of Christ:
and then shall that wicked spirit (in all his workings,
in all his various appearings and transformings, as if he still were for God,
and for the right and orderly government of his church and temple) be discovered,
by degrees consumed, and at last destroyed.
ver. 8. And then the kings or powers of the earth,
which gave their power and strength to the beast (helping him to cause men to worship.
Rev. 13:15-16), making war with the Lamb and his suffering saints by their laws,
whips, prisons, fines, etc., shall be overcome by him,
who fighteth against them with "`the Spirit of his mouth,`" and by his "`truth, meekness,
and righteousness,`" which shines in the hearts and conversations of his "`called,
faithful, and chosen.`" Rev. 17:13-14. Ps. 45:4-5.

The power of Christ cannot hurt any of his lambs (it never forced the weak ones,
the tender-conscienced, but he carries the lambs in his bosom,
and gently leads those that are with young.
Isa. 40:11). He had rather have many hypocrites spared,
than one ear of wheat plucked up. Matt. 13:29.
That power therefore in the church which spares
the hypocrites (who can easily comply with an outward conformity in worship,
without feeling an inward life or virtue),
but lights heavy on that which is tender and shy in matters of
worship (knowing that it must give an account thereof to Christ),
that is not the true church-power, but at best but a counterfeit of the true.
