[#swearing, short="Swearing Under the Gospel"]
== The Great Question Concerning the Lawfulness or Unlawfulness of Swearing Under the Gospel

[.heading-continuation-blurb]
Stated and considered of for the satisfaction of such as desire to
scan the thing in the weight of God`'s spirit;
and to see the true and clear determination of it in his unerring light.

[.section-author]
By _Isaac Penington,_ the Younger

[.section-date]
1661

WHETHER it be lawful for Christians (who know Christ,
the substance of all the shadows under the law,
and are in the new covenant) to swear upon weighty occasions,
as it was lawful for the Jews to do under the old covenant.
Or, Whether Christ alloweth his disciples to swear in solemn cases,
as Moses did allow his disciples.

[.discourse-part]
Answer.
For the clearing of this weighty controversy,
to all such as singly desire to know the truth (as it is in Jesus) in this particular,
that their hearts may bow to him therein,
and not be overtaken with the reasonings and subtleties
of the carnal mind (which never knew nor can know the power,
but hath always been, and still is,
setting up dead images of God`'s truths and of his worship, out of the power),
these few things following would be considered of.
First, What an oath is.
Or, The nature of a right and true oath under the law.
Secondly, The ground or occasion of its institution.
Thirdly, The cases wherein an oath was to be used.
Fourthly, The proper end and service of an oath.
Fifthly, The suitableness of its nature to its end and service.
Lastly, The persons to whom the use of an oath was proper in itself,
and intended and allowed by God;
and whether there be any persons to whom it is not proper,
and to whom the Lord doth not allow it.
This last is the main, and will of itself determine the thing;
but yet a brief consideration of the former may not be unprofitable,
to make way for a clearer leading and insight into it.

First, As touching an oath, what it is, or the nature of it.
A true and lawful oath under the law was an engagement or bond upon the soul,
Num. 30:2 by the name of the Lord, Duet. 10:20.
to the speaking of truth in things affirmed,
and to the performance of truth in things promised.
It was as a seal to bind fallen man (man fallen from the truth,
from the uprightness) to truth in his words and promises, either to God or man.
This is the nature and use of an oath; to wit, to bind the soul to truth,
to be such an engagement upon the soul, as, if there be any fear of God there,
it cannot but dread to break, knowing, that "`the Lord will not hold him guiltless,
that taketh his name in vain.`"

Secondly, The ground or occasion of an oath, is the fall of man from truth,
from innocency, from the uprightness which engaged him to truth before his fall.
This made the Jews stand in need of this bond under the law,
in their purposes and promises towards God;
and the same thing likewise made them stand in need of it one from another,
to ratify and confirm truth between them.

Thirdly, The cases wherein an oath was to be used, which were chiefly these four.

1+++.+++ In case of a promise or vow to God.
2+++.+++ In case of promise to man.
That the truth, integrity, and plain intention of the heart might stand,
and there might be no departing therefrom, in the thing promised, either to God or man;
an oath in that state was found useful to bind the soul thereto.

3+++.+++ In case of pronouncing or declaring the truth of a thing which was weighty,
that there might be a clear and satisfactory ground of belief.

4+++.+++ In case of controversy between parties, where the controversy could not be determined,
but by taking the confession of the one party for truth;
there that party was to seal his confession with an oath,
and so the other to rest satisfied therewith, and the controversy thereupon end.

Fourthly, The end of an oath, which is for final confirmation,
and avoiding all further strife and contention about the thing sworn to.
By binding the thing (promised or affirmed) with an oath, the thing is confirmed;
and now there is no more strife in the heart concerning the thing, if relating to God,
or between man and man in things relating to them;
but the striving nature is bound down by the oath of God,
wherewith the thing is ratified, and so the doubt and uncertainty removed,
and the contest ended.
Thus of right it ought to be, and is,
where the oath is forcible and in its proper service.

Fifthly, The suitableness of its nature to the end aimed at by it.
Man out of the Christian life,
can go no further than to engage himself by the fear and dread of that God,
whom he professeth to worship and serve,
and who cannot but be jealous of his name and honor,
and ready to vindicate the taking of it in vain.
Man under the law could not bind himself to God,
in any promise or service more than this;
nor can there be any greater bond or seal of truth given by one man to another,
in the fallen state, than this.
And he that will venture to break this,
what but deceit and treachery can be expected from him?
insomuch as no other engagement from him can be of weight,
he hereby manifesting the want of that in his mind and spirit,
whereupon all ties are to fasten.

Sixthly, The persons to whom the use of an oath was proper and lawful,
and for whom it was instituted;
and whether there be any persons to whom it is not proper and lawful,
and for whose use it was not instituted.

To find out this distinctly and truly,
we must consider the several conditions of man since the creation;
and observe to which of those it is useful and proper in itself, and allowed by God,
and to which it is not useful in itself, nor allowed by God.

There have been four estates or conditions of mankind since the creation:

1+++.+++ An estate of innocency; an estate of integrity, of purity, of righteousness,
wherein man could not lie or deceive; but his promises to God, and his words to men,
must needs be Yea, and Amen: for it was impossible to man,
who was made in God`'s image (which is truth) to lie or deceive,
until the deceit entered him, and drew him out of the truth.

2+++.+++ There was (and still is) an estate of deep captivity,
wherein this truth and innocency was wholly lost;
and man wholly corrupted in his spirit and nature, and wholly degenerated from God.
This was the estate of the heathen, who knew not God generally, nor desired after him,
but walked in the vanity of their minds, and were given up to their own hearts`' lusts.
Yet among some of these the eternal principle of life was stirring, which did check them,
and offer to guide them out of this estate;
which they that hearkened unto did not remain in the fall with the rest,
but felt the power of that, which reproved and checked them, circumcising their hearts;
and, in their obedience thereto, justifying them in their consciences before God.

3+++.+++ There was an estate of shadowy redemption,
which was not the true estate of redemption itself,
or they the true people which were to be redeemed; but a shadow of the redemption,
a shadow of the redeemed people, a shadow of the way and path of life;
wherein were figures of the heavenly substance, the heavenly people, the heavenly things,
the heavenly inheritance, the heavenly food, etc.
But all these figures, in and under the law,
were not the true heavenly and invisible things themselves,
but outward and visible signs and representations of them.

4+++.+++ There was, and blessed be the Lord, now at length (after the great, long,
and dark night of apostasy) again is brought forth, an estate of true redemption;
wherein the soul is brought back from the death, from the captivity, from the fall,
from the deceit, and from the shadows, into the truth, into the pure life,
into the innocency, into the uprightness; wherein Christ (the power of God) is witnessed,
and the soul new formed in his pure image, and become a new creature, having a new eye,
a new ear, a new heart, a new nature, a new life and spirit,
(in the newness of which life it is to live and walk) a new course and conversation,
a new place to walk and have its conversation in,
even in that very heaven from whence it looks for the Saviour;
wherein also all old things, which came in by the fall,
and all the old shadows of the law, are to pass away,
and in this state all things are to become new.
And this is not only to be expected in the perfection of this state,
but belongs (in its measure and degree) to the very beginning of it:
for even so soon as a man is ingrafted into Christ, even then he is a new creature,
and all things then begin to become new unto him,
and he is then to begin departing from all old things,
both of the natural or heathenish state, and of the Jewish state,
until he hath left them all behind.
The apostle saith expressly, "`If any man be in Christ, he is a new creature:
old things are passed away, all things are become new.`" Christ,
the Lord and Master of all believers, who himself was not in the world,
calleth all his disciples and followers out of the world.
How, out of the world?
Doth he call them from having any being or commerce in the earth, or in the world?
Nay, not so; but to come out of the evil and corrupt state, practices,
and ways of the world; out of the earthly ways of the Heathens,
out of the earthly ordinances and observations of the Jews; yea,
even out of everything in both, which was not of the Father, but of the world;
and this made them a gazing-stock to both, and the scorn and hatred of both,
wherever they came.

These are the four estates or conditions of mankind since the creation; in one of which,
all men that ever were, have been to be found;
and according to the estate and condition wherein man is found, is the law of God to him,
and his requirings of him.

Now let any man, in the fear of the Lord God, weigh and consider,
to which sort or sorts of these an oath was useful in itself, and allowed by God,
and to which not.
Was it useful in the innocent state?
or did God appoint it there, when man could not but speak truth?
Or is it useful in the redeemed estate, where a greater bond is received,
and professedly held forth, than the innocency of man`'s nature was?
Is not Christ the truth, the substance?
Is not he that is in him, the new creature?
Were not all the oaths, and shadows of the law, to last till Christ the substance came?
Is not this the bond of the gospel?
And doth not this seal truth,
and keep to truth more firmly than the oath under the law could?
and the greater bond being come doth not the lesser bond, which signified it,
flee away and vanish, and the use of it now become both needless and unlawful?
Men may reason subtly, and persuade strongly against the truth;
but we know certainly and infallibly, in the light of the Lord,
that the use of an oath was not for man in innocency,
nor for man under the power and virtue of the redemption
by Christ (which brings man back into the truth,
into the innocency,
and into that life and strength which preserves in the truth and innocency),
but for fallen man, for man erred from the truth and covenant of God:
and it is very manifest to us, that for a disciple of Christ,
who hath received the law from his lips against swearing,
to be brought back again to swearing (the bond of man in the fallen state,
and under the law) is no less than a denial of Christ,
who is his life and redeemer out of the fallen state, and who also is the substance,
which ends the oaths; and he that hath ever known the pure power of his life,
and received the pure law thereof in the clear openings of his spirit,
must not depart from thence, from the feeling of that, into the fleshly reasonings,
into consultations with the fleshly-wise part,
which will be sure to give such interpretations of scriptures as may avoid the cross;
but keep to that power which begat him, and to that principle wherein he was begotten;
and there he shall never be able to get beyond the yea and amen in Christ,
beyond the confessing of the truth in the presence and life of it,
which is the end and substance of swearing under the law; and therefore the Apostle Paul,
who several times, and in several cases, refers to the prophecies of the prophets,
who foretold of things under the gospel in law-phrases, renders the word confess,
instead of swear,
as may appear by comparing Rom. 14:11. and Phil. 2:11.
with Isa. 45:23. That which the law called swearing,
the gospel calls confessing, each of them speaking of the same thing,
in the proper dialect of each; which confessing in the life, in the truth,
in the renewed principle, is the weight and substance of that,
whereof the oath was but a shadow.
For what is the substance and intent of an oath?
Is not the intent of it to bind to the speaking or performing of truth?
And what is it that binds?
Is it the shadow or the substance?
Is it the words of an oath, or the sense and weight of the thing upon the spirit?
It was not the form of an oath, but the weight and substance hid underneath,
which bound the Jew under the law;
and if there be no more weight and substance in the
yea and nay of a disciple under the gospel,
it must needs be more binding to them,
and hath also more true ground of satisfaction in it (to other
Christians at least) than a Jew`'s or Heathen`'s swearing;
yea, and if the men of the world would but freely speak their hearts,
it would be acknowledged to be of more weight with them also.
Who of those who have observed and known our conversation,
and upright speaking and behavior for these many years,
both towards the various rulers and authorities of the nation,
and also towards all men of all sorts,
would not prefer our yea and nay before the oaths of others?

[.discourse-part]
Objection.
But though a Christian may not swear in relation to himself;
yet why may he not swear in relation to the satisfaction of others,
seeing God himself sware in that respect,
who was as much in the power and virtue of that life
which binds from swearing as a Christian can be?

[.discourse-part]
Answer.
1+++.+++ God (being not bound himself by the laws wherewith
he binds the creature) may either himself,
or by an instrument (in his immediate life and power),
do that which the creature hath not liberty from him to do;
but that is no warrant in general,
but the disciple is particularly to eye the rule from his Master,
CHRIST JESUS (who is Lord over the household of faith,
and who was as faithful in all his house as a Lord, as Moses, the servant,
was in his house), by whom the same God, who once allowed oaths to the Jews,
hath now wholly forbidden swearing.
And let the disciple diligently and faithfully eye
the laws of the new covenant (which are written by,
and received from,
the ingrafted word of faith in the heart) he shall find oaths excluded there,
as a part of the old covenant,
even as a literal and shadowy confirmation of truth among
the Jews under Moses`' dispensation for the time of the law;
but the grace and truth itself is the substance,
and the faith received is the seal of truth under the gospel, both towards God and man.

[.discourse-part]
Answer.
2+++.+++ A Christian may not swear in relation to the satisfaction of others,
because he is to hold forth his light, his life, his principle, in the eye of the world;
he is to testify to the worth and excellency of it,
that it is a greater and firmer bond to him, both towards God and man,
than any oaths either of the Heathen or of the Jews can be.
Now his entering into their way of confirmation of things, which is short of his own,
is an undervaluing and disparagement of the worth and weight
of that principle of truth which God hath given him,
and raised up in him: it is indeed a denying of it: for entering into the law-bond,
is laying of the gospel-bond by; and an offering of that as a bond,
which indeed once was so,
but is now excluded by the law of faith from being a bond any longer,
and hath lost its virtue.
And if men would but open their eyes, they might easily see how little oaths bind,
and how unprofitable they are to the end and use for which they are intended:
but the yea, and amen in Christ (the principle of life) cannot be broken;
but he that abides in him must perform the yea and amen, which is firm in him.

[.discourse-part]
Answer.
3+++.+++ A Christian or disciple may not swear under the gospel,
because Christ hath brought in confession of the truth, from the principle of his life,
instead of oaths;
which is made good not only by the Apostle Paul`'s rendering of swearing in the law-time,
confessing, in the fulfilling of it under the gospel;
but also by Christ`'s bringing in the yea, yea, and nay, nay,
instead of the law`'s swearing.
In the Jew, the oath was the seal or confirmation under the law; in the disciple,
who is in the life, and hath learned the truth of Christ, the life, the yea, yea,
the nay, nay, is appointed him by Christ instead of the oath.
And though the subtlety and fleshly wisdom strive hard to
wrest that place out of the hands of the simplicity,
yet they shall never be able to do it:
but he that looks on it with a single eye in the
light of that Spirit wherein it was wrote,
shall plainly see Christ`'s drift to be to take away the shadow,
even to abolish that use of swearing,
which was proper and allowed to the Jews under the law,
and to bring the confession or denial of the thing, the yea, yea, and nay, nay,
(from the gospel spirit and principle in the disciple) in the stead of it;
which to make more manifest to the honest, simple, and naked heart,
which is willing to take up the will and truth of God in everything,
with all the crosses that attend it,
let these few things following be uprightly considered of.

First, That slight, trivial, and frequent oaths were not allowed under the law,
but forbidden by the law, as the taking God`'s holy and dreadful name in vain.

Secondly, That though vain oaths were then forbidden, yet solemn oaths, weighty oaths,
such as were needful and useful to the thing intended, were allowed under the law.
So in all those cases before expressed, oaths were allowed and justifiable,
so that they were but careful to perform them, and did not forswear themselves.

Thirdly,
Christ brings in an exception against the use of this lawful swearing under the law,
as the word but doth plainly signify, and forbiddeth swearing wholly, altogether,
or at all.
The law saith,
"`Thou shalt not forswear thyself;`" that is the substance of what the law forbids:
it allows swearing but forbids forswearing, but I say unto you,
ye shall not only avoid forswearing, but swearing also, and that wholly, or altogether:
"`but I say unto you, swear not at all.`"

Fourthly, Christ brings in another thing instead of swearing,
a thing far more suitable to the truth, plainness, and simplicity of the gospel,
which is confessing the thing, or speaking the thing in truth, just as it is,
either by way of affirmation or denial; "`but let your yea be yea, and nay nay.`"

And there is liberty enough left to a disciple to satisfy
any man concerning the truth of a thing by confession,
as much as by an oath:
for is it not full as weighty under the gospel to confess the presence of God,
or that he is witness, or that we speak the thing in his fear,
and in the feeling of his life and power, as it were under the law to swear by his life,
by his fear, by his power, or the like?
Is not the confessing of God by a Christian of more
weight than the swearing by him from a Jew or Heathen?
O nations and powers of the earth! seek truth, seek righteousness,
and do not set up a form or image of things in your own wills,
and according to your own wisdom and inventions, above the power of God.

And let it be duly considered,
whether the powers of this nation deal kindly with the Lord,
in exacting an oath from his people, who (not in the least disaffection to them,
but only in fidelity of conscience to Christ,
their Lord and master) cannot but refuse it.

The question is concerning their fidelity and obedience to the king;
that is the thing which an oath is required to ratify and confirm.
Now the swearing itself, or formal taking of an oath, is of little value;
but to be obedient, to be faithful, is the thing of value.
The case then stands thus: the Lord hath so formed them,
that they cannot but be faithful and obedient.
The Lord hath raised up that principle in them, which cannot hurt the king, or any man,
nor cannot stand by and see him or any man hurt, without endeavoring to prevent it.
Here is their strength of performing good, and avoiding evil; and their yea and nay,
from this principle,
is the best security which they can possibly give to any man (and
he who hath thus formed them in the pure principle of his life,
hath likewise forbidden them to swear).
But this cannot be accepted for want of the other confirmation; to wit, of swearing,
which came in by the fall, and was allowed among the shadows of the law,
but is forbidden by the gospel.

Now O king! shall not God`'s people be faithful and obedient to the Lord,
as well as to thee?
Shall they not be true to the principle of life,
wherein they are begotten and brought forth in the love and good-will to all,
and out of enmity to any?
Hath God raised up in them a principle which cannot deceive;
and will not the yea and nay of that serve (after so much experience,
through so many changes), but they must either break Christ`'s command,
and hazard their souls, or else lose their liberties and estates?

Oh! that men would wait on the Lord,
for his pure fear to be written on their hearts by the finger of his Spirit,
that they might come out of the fleshly wisdom into the womb of the eternal wisdom,
from whence our principle came; that they might be able to see and justify the purity,
righteousness, nobility, and worth of it;
and that they might feel its security from all that is out of the good-will,
out of the love, out of the life, and out of the peace;
that so there might be an end of all strife, rebellion, heart-burnings, plots,
and all manner of wickedness and ungodliness, which have no place in it,
but daily waste and wither where it is sown and grows, even till they come to an end;
and till the righteousness and pure innocency fill the room and place which they had,
both in the heart and mind within, and in the life and conversation outwardly.

And let every one that nameth the name of the Lord depart from iniquity,
and look well to his goings:
for the darkness of the thick night of apostasy is already past,
and the true light now again shineth.
Blessed is the eye which seeth it, and the heart which is established in it,
in the midst of those terrible and dreadful shakings and confusions,
which must not end here, but go over all nations.
Oh that this nation could once bow to it, that it might be happy,
and its rents and breaches be healed forever!
