[#weighty-question, short="Somewhat Spoken to a Weighty Question"]
== Somewhat Spoken to a Weighty Question Concerning the Magistrate`'s Protection of the Innocent

[.heading-continuation-blurb]
Wherein is held forth the blessing and peace which nations
ought to wait for and embrace in the latter days.

[.heading-continuation-blurb]
With _Some Considerations_ For the Serious and Wise in Heart throughout this Nation to ponder,
for diverting God`'s Wrath, if possible, from breaking forth upon it

[.heading-continuation-blurb]
Also A brief Account of what the People called _Quakers_
desire in reference to the Civil Government.
With a few Words to such as by the everlasting Arm of God`'s Power
have been drawn and gathered out of the Apostasy, into the living Truth and Worship.

[.section-author]
By _Isaac Penington,_ the Younger

[quote.section-epigraph]
____
And in that day will I make a covenant for them with the beasts of the field,
and with the fowls of heaven, and with the creeping things of the ground;
and I will break the bow, and the sword, and the battle out of the earth,
and will make them to lie down safely. Hos. 2:18
____

[.section-date]
1661

=== Question.

Whether the magistrate, in righteousness and equity, is engaged to defend such, who,
by the peaceableness and love which God hath wrought in their spirits,
and by that law of life, mercy, good-will, and forgiveness, which God, by his own finger,
hath written in their hearts, are taken off from fighting, and cannot use a weapon,
destructive to any creature, to defend him.

=== Answer.

Magistracy was intended by God for the defence of the people;
not only of those who have ability, and can fight for them, but of such also who cannot,
or are forbidden by the love and law of God written in their hearts so to do.
Thus women, children, sick persons, aged persons,
and also priests in nations (who have ability to fight,
but are exempted by their function,
which is not equivalent to the exemption which God makes by the
law of his Spirit in the heart) have the benefit of the law,
and of the magistrate`'s protection, without fighting for the defence of either:
and is it not most righteous and equal, that fighting, which came in by the fall,
should come to an end in such whom God draws out of the fall;
and that magistrates (who have power given them to rule by God,
and ought to rule under him) should not require fighting of them
whom the Lord of lords hath redeemed out of the fighting nature,
and chosen to be as examples of meekness and peaceableness in the places where they live?
How can he fight with creatures, in whom is love and good-will towards those creatures,
and whose bowels are rolling over them, because of their wanderings in the lusts,
in the strife, and in the wars?
Fighting is not suitable to a gospel Spirit; but to the spirit of the world,
and the children thereof.
The fighting in the gospel is turned inward against the lusts,
and not outward against the creatures.
There is to be a time, when "`nation shall not lift up sword against nation,
neither shall they learn war any more.`" When the
power of the gospel spreads over the whole earth,
thus shall it be throughout the earth;
and where the power of the Spirit takes hold of and overcomes any heart at present,
thus will it be at present with that heart.
This blessed state, which shall be brought forth in the general in God`'s season,
must begin in particulars; and they therein are not prejudicial to the world,
nor would be so looked upon, if the right eye in man were but open to see with,
but emblems of that blessed state which the God of glory hath promised
to set up in the world in the days of the gospel.
And though by this means there may seem to be a weakening of the strength of the magistrate,
and of the defence of that nation wherein God causeth the virtue
and power of his truth to spread in the hearts of his people;
yet in truth it is not so, but a great strengthening.
For if righteousness be the strength of a nation,
and the seed of God the support of the earth, then where righteousness is brought forth,
and where the seed of God springs up and flourisheth, that nation grows strong;
and instead of the arms and strength of man,
the eternal strength overspreads that nation,
and that wisdom springs up in the spirits of men, which is better than weapons of war;
and the wisdom which is from above is pure and peaceable, and teacheth to make peace,
and to remove the cause of contention and wars, and uniteth the heart to the Lord,
in waiting upon him for counsel, strength, and preservation in this state,
who brought into it.
Now is not this much better and safer than the present estate of things in the world;
first, to have the cause of wars removed, and a sweet, peaceable,
righteous Spirit in the stead thereof; secondly,
to have a peaceable and righteous generation, whom the Lord hath made and preserved so,
breathing to the Lord for peace, good, and prosperity to the nation,
and magistrates thereof, and to stretch forth his arm to be a defence about them;
thirdly,
to have the God of heaven engaged by his power to defend that power
and magistracy which defends righteousness in general,
and particularly his people in their obedience unto him,
whom it is most righteous for them to obey, and for the magistrate,
who claims his rule and dominion under God, to protect them in?
Were not this much better both for magistrates and people than the present estate?
Oh that that were awakened in man which can rightly discern and judge!

[.discourse-part]
Objection.
But this is an Utopian state, or a world in the moon.
Is it possible that ever there should be such a state here on earth?

[.discourse-part]
Answer.

[.numbered-group]
====

[.numbered]
1+++.+++ When the principle of God, which lies hid in the hearts of men,
over which the corrupt nature hath grown,
and upon which the spirit of darkness in men tramples,
shall be raised and come into dominion; righteousness, peace,
and good-will shall spring up as naturally among men, as wars, strifes, divisions,
emulations, heart-burnings, etc. now do.

[.numbered]
2+++.+++ There is a promise of such a state, "`when the lion shall eat straw like the ox,
and lie down with the lamb;
when the earth shall be filled with the knowledge of the Lord,
as the waters cover the sea,
and nothing shall hurt or destroy upon God`'s holy mountain;`" but the nations,
who have been full of war, shall throw away their weapons,
become subject to the spirit of peace and righteousness, and learn war no more;
when the wisdom of the wise, and strength of the strong, shall be broken in pieces;
and the little child shall play on the hole of the asp, and the cockatrice`'s den,
and lead all.
As certainly as the Lord God is true, so this must be in the Lord`'s season:
and will it not be happy when it comes to pass?
Who would hinder it?
Who would strive to keep the old heavens and the old earth standing,
which must be dissolved before the new heavens and the new earth
(wherein dwells righteousness) can be formed and brought forth?

[.numbered]
3+++.+++ This state was in a fair forwardness once,
before the universal apostasy from that truth and power which God had sown in the earth,
upon the breathing of and sending forth his Spirit among his disciples,
according to his promise.
Precious was that seed, great the growth of it, the woman, or true church,
full of beauty and glory, and brought forth the man-child, which was to rule all nations;
but it hath pleased the Lord to adjourn that day till after the night of apostasy,
catching up the man-child to heaven, and causing the woman to fly into the wilderness,
where she hath been hid ever since from all but the inward eye of the inward Israel:
and the world, in the heathenish nature, hath been crying up holy church,
holy church! to her who hath set upon the beast,
and been drunk with the blood of the martyrs of Jesus; but the tender spouse,
the Lamb`'s wife, the mother of all the lambs, hath been banished from the earth,
and a cruel, bloody step-mother set over all the tender-conscienced ever since.
Oh woful, woful hath been the state of the true church, and of all the children of truth,
all this dark night of the apostasy! but the Lord is putting an end to it:
and though this false woman seems to be recovering ground,
and setting her feet over the necks of the lambs again,
and begins to think she shall prevail,
and sit as a lady and queen over the consciences of God`'s heritage forever;
yet she shall find that strong is the Lord God who hath begun to judge her;
and into the sea which she raiseth shall she sink like a stone,
and her fall shall be great and speedy:
for even in one day shall her misery overtake and devour her.

[.numbered]
4+++.+++ After this long night of apostasy the Lord hath begun
to make some preparations towards this state again.
He hath opened his treasuries; he hath let forth the power of his truth;
he hath poured down of his Spirit to sanctify and gather a people unto himself;
he hath opened the principle of life in the hearts of many,
and in a great measure drawn them into it; who, so far as they are renewed thereby,
and found there, are made peaceable, pure, meek, gentle, innocent, upright-hearted,
and tender-conscienced, both towards God and man.
And though multitudes of reproaches have been cast upon them,
yet the Lord hath been pleased to cause their innocency and integrity to shine,
to the wiping of them off in a great degree, and will, in due time,
bring forth their righteousness as the light, and their judgment as the noon-day.
And what remains toward the carrying on of this work,
but the Lord`'s prospering of this principle, and blowing upon the other?
As the Lord doth this, so will it go on; and the nations, kings, princes, great ones,
as this principle is raised in them, and the contrary wisdom, the earthly policy,
which undoes all, brought down, so will they feel the blessing of God in themselves,
and become a blessing to others.
Oh that there were an ear to hear! for this is the only way of
healing this nation (which hath been so grievously torn),
as will be acknowledged when woful experience makes it manifest.
But man in prosperity cannot hear, and that enforceth from the Lord,
by the turning of his hand, the bringing upon him the day of his adversity; which,
could he have hearkened to in the day of his prosperity, might have been escaped:
for God doth not afflict willingly, nor grieve the children of men;
he is necessitated to it for his own glory`'s sake,
the preservation and defence of his truth and people,
and for the carrying on of his work.

[.discourse-part]
Objection.
But if all men were of this mind, and none would fight,
suppose a nation should be invaded, would not the land of necessity be ruined?

====

[.discourse-part]
Answer.

[.numbered-group]
====

[.numbered]
1+++.+++ Whenever such a thing shall be brought forth in the world,
it must have a beginning before it can grow and be perfected.
And where should it begin but in some particulars in a nation, and so spread by degrees,
until it hath overspread the nation, and then from nation to nation,
until the whole earth be leavened?
Therefore whoever desires to see this lovely state brought forth in the general,
if he would further his own desire, must cherish it in the particular.
And oh! that men would not spend their strength,
and hazard the loss of all in cherishing pretences and names of Christianity,
but would pray to the Lord at length to open that
eye in them which can see the loveliness of the truth,
power, and virtue of Christianity;
that they might cherish that tenderness of conscience wherein
the truth grows and springs up in its virtue and power.
And then perhaps they would soon acknowledge the happiness
of the world to depend upon the growth of that principle,
and of that people, who are now despised by the world,
and cannot but be so by the spirit and wisdom of the world, which lies in wickedness,
they being drawn out of, and testifying against, it.

[.numbered]
2+++.+++ It is not for a nation, coming into the gospel life and principle,
to take care before-hand how they shall be preserved;
but the gospel will teach a nation (if they hearken to it) as well as a particular person,
to trust the Lord, and to wait on him for preservation.
Israel of old stood not by their strength and wisdom,
and preparations against their enemies; but in quietness and confidence,
and waiting on the Lord for direction, Isa. 30:15. and shall not such now,
who are true Israelites, and have indeed attained to the true gospel state,
follow the Lord in the peaceable life and Spirit of the gospel,
unless they see by rational demonstration before-hand how they shall be preserved therein?
I speak not this against any magistrates`' or people`'s
defending themselves against foreign invasions,
or making use of the sword to suppress the violent and evil-doers within
their borders (for this the present estate of things may and doth require,
and a great blessing will attend the sword where it is borne uprightly to that end,
and its use will be honorable; and while there is need of a sword,
the Lord will not suffer that government, or those governors,
to want fitting instruments under them for the managing thereof,
to wait on him in his fear to have the edge of it rightly directed);
but yet there is a better state, which the Lord hath already brought some into,
and which nations are to expect and travel towards.
Yea, it is far better to know the Lord to be the defender, and to wait on him daily,
and see the need of his strength, wisdom, and preservation,
than to be ever so strong and skilful in weapons of war.

[.numbered]
3+++.+++ If the Lord shall undertake the defence of a nation by his Spirit and power,
what can hurt that nation?
What power of man can reach it, to disturb the peace of it?
"`The Egyptians are men, and not God; and their horses flesh,
and not spirit.`" Isa. 31:3. What could Sennacherib with
his army do against one angel in the time of the law?
How many of his host were slain in one night?
And what power then shall be able to prevail over a nation
brought into the peaceable Spirit of the gospel,
and defended therein by the mighty power of God himself?
Will not God be as sure a defence over the true Israel,
in the way and dispensation wherein he leadeth them,
as ever he was over the representative Israel,
in the way and dispensation wherein he led them?
Will he not preserve and defend that nation whom he first teacheth to leave off war,
that they shall not be made a prey of,
while he is teaching other nations the same lesson?

====

God promised Israel of old,
that when they went up thrice in the year to appear before the Lord,
according to his command,
he would keep it out of the hearts of the nations from so much as desiring their land,
much more from entering and taking it from them in the mean time,
though they might seem watchful after, and sufficiently greedy of such an opportunity,
they being cast out of the land, and having had it taken from them before. Ex. 34:24.
The Lord also can now keep it out of the hearts of the nations from invading
or prejudicing that nation which he shall first draw into the peaceable Spirit.
Or if he see not good to do that,
he can defend those that have followed him out of the earthly spirit, wisdom,
and strength, by ways that man knows not of; nor may it be fit for him to know,
till the Lord bring it forth.
Israel of old was not to know the deliverance beforehand; but to trust to the Lord.
Under the gospel, the Lord giveth more faith than to Israel of old under the law,
and therefore may justly require greater confidence in greater straits.
And awaken, O earth! behold the Israel of the Lord,
whom he hath begotten and brought forth in the earth, after the long,
dark night of apostasy,
and ye shall see what hearts the Lord hath given them to trust him,
in all the straits and trials wherewith he pleases to exercise them,
and what the Lord will do for them when they are brought to the brink of the pit,
and when it seemeth impossible for them to escape utter ruin and destruction.
The eye which the Lord hath given them seeth the Lord and his strength;
and the heart which he hath created anew in them,
naturally feareth the everlasting power,
which reacheth both to the body and soul forever:
but as for whole multitudes of nations, they are but as "`the drop of a bucket,`" and,
in their greatest wisdom and strength, but as "`vanity, as the small dust of the balance,
as nothing before him, and less than nothing to him.`"

Consider this, O ye great men!
O ye wise men, and deep politicians! all ye have done, or can ever do,
in relation to overturning any thing that God hath purposed, what are ye therein?
Or what will your work come to?
It is just like "`the small dust of the balance;`" it hinders
not at all the weight of his power on the other hand,
but he will carry on his work, bring to pass what he hath purposed in himself,
and promised to his people; and all your councils, wisdom, strength, hopes, resolutions,
and present or future advantages against him and his work,
shall hinder him not more than the small dust in
the scale of a balance which the wind blows away,
and it is not.
Be wise therefore, O ye sons of men! fear before your Maker;
wait in his fear for his counsel,
that ye may not be suffered by him to undertake any thing against him,
lest before ye are aware ye fall before him.
Oh! let every one in fear remember that passage, "`Lo,
this is the man that made not God his strength, but trusted in the abundance,`" etc.
Forgetting the Lord in the day of prosperity,
causeth much increase of the anguish and sorrow of heart in the day of adversity.
O ye that are in present power! consider how unwilling
ye would be to have the Lord turn his hand upon you,
and bring you under again!
Oh, provoke him not, for he is able to do it,
as he was to overturn those which went before.
It were far better for you now to fear the Lord, and prevent it,
than to bewail and repent afterwards.
Oh! reject not the love and counsel of the Most High (which
would now preserve you) as those which went before you did.

There is a desire in all men (in whom the principle
of God is not wholly slain) after righteousness;
which desire will be more and more kindled by God in nations,
before righteousness and peace meet together and be established in them.
Now such and so great hath been the kindling of this desire in this nation,
and such is the state thereof,
that nothing can satisfy the heart of it but righteousness:
this it longeth after at the bottom: this the governors which were before might have,
and the governors that now are (by asking counsel of the principle of God within themselves,
and keeping close thereto) may answer the nation in;
but if the consultations be not with the Lord,
in the principle of life which came from him,
but with the wisdom and policy which is of the earth, and from beneath,
and not from above, that will incline to self, and to corruption,
and never bring forth righteousness; nor can the blessing of God attend it,
nor the peace which accompanieth righteousness be reaped from it.

[.centered]
=== Some Considerations

[.heading-continuation-blurb]
For the Serious and Wise in Heart throughout this Nation to ponder,
that they may send up earnest Prayers to Almighty God,
and use their best Endeavors in their several Places and Stations,
to prevent that dreadful Storm of Wrath which hath long hung over this Nation;
that at length it break not forth like a Fire which none can quench,
or like a Flood which none can stop.

[.numbered-group]
====

[.numbered]
1+++.+++ Did not God, by the power of his Spirit in the apostles`' days,
gather a people out of the world unto himself, and by his wisdom,
and according to his heavenly will, build them up into a church, or holy temple,
for his Spirit to inhabit and dwell in,
and for himself to be honored and worshipped in Spirit and truth,
according as he should teach them, and require of them?

[.numbered]
2+++.+++ Did not the same spirit which built this church
not only signify that the love should wax cold,
and there be a falling away from the truth,
and warn the churches of Asia of the removal of their candlesticks,
but also foretell of the total dissolution of that building as to its outward
state +++[+++upon the close of the sharp battle by the dragon and his angels,
or false ministers, with Michael and his true church and ministers],
insomuch as the church herself should fly into the wilderness,
and her seed be made war with,
and persecuted up and down the nations all the time of the apostasy afterwards?
See Rev.
12.

[.numbered]
3+++.+++ Was not this desolate estate of the church to
remain and last all the allotted time thereof,
which is expressed to be forty-two months, twelve hundred and sixty days, or a time,
times, and half a time, wherein the beast should rule, antichrist sit in God`'s temple,
and the dragon be worshipped there, instead of the living God;
and also the lambs of Christ,
and witnesses of Jesus (who retain the worship in Spirit and truth,
and cannot join with any of the false ways of worship set up in the nations)
torn and rent by the woman which appears instead of the true church,
but is not?
Rev. 11:2 and 12:6.14. and 13:4. and 17:6.

[.numbered]
4+++.+++ Doth not this woman continue deceiving the nations and kings
of the earth (whom she causeth to drink of her cup of knowledge,
worship, doctrine, and discipline, whereby she blindeth their eyes,
bewitcheth their hearts, and maketh them take her for the true church, who,
notwithstanding all her glorious appearance, is but Babylon in a mystery, and,
notwithstanding all her pretences for Christ,
doth drink the blood of his true saints and witnesses); I say,
doth she not continue her deceit till the very hour of her judgment,
and until she hath brought the dreadful vials of the wrath of God both upon herself,
and upon all that continue joining with her? Rev. 17:2.
etc.

[.numbered]
5+++.+++ Is there not to be an end of this night of apostasy, and of the false church,
with all her various habits, and dresses, and new paints, and arts of deceit,
(though both have continued long) wherein Christ, the Lamb,
comes forth in his power to fight with the beast, and the woman which rides thereon,
and to smite the earth which remains infected with her fornications,
(which withdraw and steal away the heart from the pure life and Spirit of Christ,
and from his pure, living, spiritual worship, into a false, invented, dead,
formal worship) that so he may restore and set up his pure spiritual worship again? Rev. 19:11.

[.numbered]
6+++.+++ Are not the kings, powers,
and inhabitants of the earth in great danger of fighting against the Lamb,
in defence of this false church against his true church,
(when he again comes to set it up in nations,
after the expiration of the long night of apostasy) even
to the hazard of utterly ruining themselves thereby?
For those that fight against the Lamb must needs be overcome by him;
his invisible strength, and armies being much stronger than the visible armies,
and all the outward strength in nations; though, to the outward eye,
such may appear very great and invincible. Rev. 17:14.

[.numbered]
7+++.+++ Shall not the "`kings of the earth,`" and the remaining powers
at last (after the overthrow of many for joining to her,
and striving to uphold her) "`hate the whore`" (which
hath corrupted the earth with her fornications,
drunk the blood of the saints and martyrs of Jesus,
brought misery and desolation on nations, etc.), "`make her desolate,
and burn her flesh with fire?`" And were it not far better for them to do it before,
rather than to hazard the ruining of themselves by seeking to uphold her? Rev. 17:16.

[.numbered]
8+++.+++ Is it possible for any nation (or any power in any nation)
to hinder the shining forth of God`'s light therein,
after the long night of apostasy?
There is a spiritual day, as well as a natural day.
There was a spiritual day before the apostasy, in the days of the apostles;
and there is to be a spiritual day again after the apostasy,
upon the Spirit of life`'s entering into the witnesses,
their rising and standing on their feet, and the light of God shining forth from them.
The spiritual day dependeth upon the shining of God`'s Spirit
in the hearts of people (which did once shine forth,
and doth begin to shine forth again),
as the natural day dependeth upon the shining of the sun.
Now who can hinder the arising or shining of the
Sun of righteousness in the hearts of God`'s people?
If ye can,
then may ye prevent the carrying on of God`'s work of reformation in this nation,
and throughout the world;
but it is easier for you to stop the shining of the sun in the firmament.
Oh! that the eye were opened which can see the way of peace,
that the present governors might be blessed, and the nation blessed in them,
and not the spirit of the nation, by a secret kindling, which none knows whence it comes,
brought over them as a flood, as it was over them that went before them.

====

In that fear which God works in the heart,
and out of the compass of that carnal wisdom and strength, on which man relies,
is the wisdom, counsel, and preservation of the Most High; both of particular persons,
and also, of nations.
O Lord my God! if it may please thee, open the ear that can hear thy voice,
that misery may be avoided, and thy peace and blessing may be sought after and enjoyed;
or at least some of the force of that bitter storm,
which sweepeth away and maketh desolate,
even as the abomination of desolation hath entered,
and of a long time made the earth desolate of the life and power of godliness, +++[+++may be]
broken,
that this nation may not be swallowed up in the dreadful breakings-forth of thy displeasure,
but may be prepared by the correcting hand, and fitted for the day of thy mercy.

[.old-style]
=== A Brief Account / Of What the People Called Quakers Desire in Reference to the Civil Government

There are three things which we cannot but earnestly desire in our hearts,
and pray to the Lord for,
as the proper means of settling aright the spirit of this nation:
as also necessary for the growth of God`'s pure, living truth,
and as just and equal in themselves.

[.numbered-group]
====

[.numbered]
1+++.+++ Universal liberty for all sorts to worship God,
according as Christ shall open men`'s eyes to see the truth,
and according as he shall persuade their hearts by his Spirit;
who is every man`'s master in religion,
to whom they must stand or fall in all they do therein. Rom. 14:4.

Now if any man walk disorderly,
and contrary to the light of Christ`'s Spirit either in doctrine or worship;
that power which converts to God is to reprove and correct
such an offender with the spiritual rod and sword,
that he may be again restored to the truth and obedience of the Spirit;
but the magistrate is not for any such thing to imprison, fine, banish,
or put him to death.
For Christ is the judge of his people in the things of his kingdom, Heb. 10:30.
and he hath appointed to have his spiritual weapons in a readiness,
to revenge every disobedience and rebellion against his Spirit. 2 Cor. 10:4.
The bringing in and applying of the magistrate`'s sword to this work,
was never by the true church,
in whose hand the sword of the Spirit was ever found sufficient; but the false church,
not having the sword of the Spirit, is fain to uphold herself by the carnal weapons,
or else she would soon fall.
But the Lord God is wresting these out of her hands,
and then his light will break forth without interruption,
and her shame and nakedness soon appear.

[.numbered]
2+++.+++ That no laws formerly made,
contrary to the principle of equity and righteousness in man, may remain in force;
nor no new ones be made, but what are manifestly agreeable thereunto.
All just laws, say the lawyers, have their foundation in right reason,
and must agree with, and proceed from it, if they be properly good for,
and rightly serviceable to, mankind.
Now man hath a corrupt and carnal reason,
which sways him aside from integrity and righteousness,
towards the favoring of himself and his own party: and whatever party is uppermost,
they are apt to make such new laws as they frame,
and also the interpretation of the old ones, bend towards the favor of their own party.
Therefore we would have every man in authority wait, in the fear of God,
to have that principle of God raised up in him, which is for righteousness,
and not selfish; and watch to be guided by that in all he does,
either in making laws for government, or in governing by laws already made.

[.numbered]
3+++.+++ Seeing this nation is in such a shattered condition,
and there have been so many breaches, parties, and factions in it,
that no party might be bolstered up in enmity and opposition against another,
but that every party might be considered,
in what might be done for their ease and benefit,
without danger and detriment to any other party.
And if I might be hearkened to, I would persuade those now in power,
not to deal with their enemies as they formerly dealt with them,
but as they would have been dealt with by them when they were in power.

====

I would also dehort and dissuade all people from plotting or contriving
against this present government (for they must have their day,
do all men what they can); but instead thereof to pray for them,
that they may see the former errors in government, humble themselves before the Lord,
and (by their meekness, gentleness, and righteousness,
towards all) show forth the fruit of his long-afflicting hand upon them.
But if they shall overlook, forget, and neglect the Lord,
who hath shown so great mercy to them; and not in his fear wait on him,
to preserve for them the ground and interest he hath given them;
and think that now they are able to stand on their own legs,
and by their own wisdom and strength;
and so assay to carry on things according to their own will,
and in the strength of their own wisdom;
and so not mind for what end the Lord brought them in again,
and what he expecteth to have effected by them,
but strive again to settle the principles and practices which he hath been shaking,
according to what seems right and good in their own eyes,
measuring things by their own corrupt reason, selfish wisdom and interests,
and not by the principle of God, common equity, and right reason;--I say,
if it should come to be thus with them, ye shall not need to plot against them;
for the Lord God Almighty, who, with ease, removed their enemies, and made way for them,
can, with as great ease, remove them, and put the power into another hand.

Therefore, all people, be still and quiet in your minds, and wait for righteousness;
for that is it which the Lord is making way for in this nation,
and which he will set up therein; and he whose desire is not after that,
and whose interest lies not there, will find himself disappointed,
and at unawares surprised with what he expects not.

This is given forth that the powers and people may
see what is the desire of our hearts in these respects,
and how upright our hearts are towards them in what is just and right,
and that we are not at all against magistracy, laws, or government,
though we cannot flatter or bend to them in that which is selfish and corrupt;
and indeed against God, and not for the good of men.
It was written long since, and intended then for service to the Lord and this nation,
and his people therein, but the Lord ordered it otherwise.
If he please now to accompany it with his blessing, and make way for the reasonableness,
equity, and righteousness of it,
to enter into the minds and hearts of them that are in power,
it will be a good season for it, and they will find cause to bless the Lord,
for putting of it into my heart at first, and for the publishing of it now.

[.old-style]
=== A Few Words / To Such as Have Felt the Power of the Endless Life Drawing

[.heading-continuation-blurb]
And have faithfully followed the Leader of the flock of Israel;
who hath of late led his sheep in such paths as
have not been known all the night of the apostasy.

O ye children of the Most High! who have felt the breath
of the eternal Spirit begetting you in the pure life,
and drawing you out of this world; out of the vanities, out of the corruptions,
out of the course and fashions, out of the invented ways and forms of worship, yea,
out of the very root and principle thereof, into the worship and Spirit of truth,
and into the fear of the Most High, which is wisdom`'s place and habitation,
where the pure law of life is received, and the salvation begun, wrought out,
and perfected.
O ye dear plants of the right hand of eternity! fear not what is to come
to pass in this visible creation (to break the corrupt state thereof,
and to make way for the springing up and spreading of his pure life and righteousness,
which the corrupt estate, spirit, and principle of the world cannot but oppose,
until it be broken and subjected), but sanctify the Lord of Hosts,
and let him be your fear and dread; that he may compass you with the arm of his power,
and hide you under the shadow of his hand, until he hath planted the heavens,
and laid the foundations of the earth, and say to Zion, in the sight of all her enemies,
"`Thou art my people.`" The Lord my God watch over you night and
day! and preserve his living principle pure and fresh in you,
and you in perfect subjection unto it;
that ye may delight in what he hath begotten and preserved in you,
and ye may be satisfied in the openings and overflowings
of the love of his heart towards you.
Amen, saith my soul!

From Aylesbury prison in Bucks,
where my life breathes for the consolation and redemption of God`'s Israel,
and for the turning of the captivity of the whole creation.
1661.

[.old-style]
=== A Few Words / About the Present Work of God in the World

Would any know what God is now doing on the earth, and what changes he is making therein?
Let him sink out of the earthly part, even from that which blinds the pure eye;
and waiting to have the understanding and eye of his spirit opened in the Lord,
let him read these things following.

The Lord God of bowels and compassion, and of everlasting power and strength,
hath heard the groans of Israel, whose consciences have been burdened,
and whose souls have been bowed down, under the power of the beast,
under the hard yoke of antichrist, for these many generations;
and he is arisen in his jealousy, in his indignation, and in his fury, to break the yoke,
and let oppressed Israel go free,

He hath already stretched forth the arm of his power; the eye of Israel hath seen it,
and hath, in part, felt the redemption, both inwardly and outwardly,
which he hath brought to pass by it; and a song of praise hath been sung to him,
who hath begun to deliver his people,
and who is able perfectly to accomplish the work he hath begun,
notwithstanding all the opposition he can meet with, whether from within or from without.

Lift up the eye of faith,
and behold a great part of Israel already passed out of the land of Egypt,
and the Spirit of the Lord awakening and rousing the rest,
to leave their dark habitations in the land of darkness, oppression, and bondage,
and to travel towards the good land of light, rest, and peace.

Arise, O Israel! shake thyself from the dust,
O captive daughter of Zion! behold the courage of thy leader;
let thy heart consider the arm of his strength, and the rod of his power,
wherewith he is able to dash in pieces all his enemies.
Fear not, worm Jacob, because of thine own weakness and unworthiness;
thy strength is in thy leader, and thy comeliness not in what thou now appearest,
but in what thy husband will put upon thee, when he shall circumcise thee thoroughly,
and roll away thy reproach forever.

Was all the strength of Pharoah able to keep Israel in the land of Egypt,
or to drive them back after God had brought them forth?
Were all the enemies in the wilderness able to stop their passage forward?
Were all the enemies in Canaan,
or the strength of their cities (though their walls might seem to reach to heaven,
and the inhabitants thereof were tall and mighty) able to
keep them out of the inheritance which God allotted them?
Thy God, O worm Jacob,
is the same forever! he hath the same arm of power to stretch forth: yea,
and his heart loveth his inward Israel full as dearly as ever he did the outward.
Oh, wait on the Lord! believe in his name, trust his love;
hope beyond hope for the appearance of his power, and the Red sea shall divide,
and the waters thereof stand on heaps; yea, Jordan shall be again driven back;
the mountains shall skip like rams, and the little hills like lambs; yea,
the whole earth shall tremble at the presence of the Lord,
at the presence of the God of Jacob: and glory, glory, glory, everlasting glory, power,
rich praise, and endless life,
shall sound through all the tents of Jacob in the wilderness,
and through all the habitations of Israel in the holy land, to the King of glory, power,
and life; even to the Lamb that sits upon the throne, who was, and is,
and is to come! who hath reigned, doth reign, and will reign on his holy hill of Zion,
over all the powers of darkness forevermore; Amen, Hallelujah!

O ye sons of men! how long will ye run after vanity,
and seek to a refuge of lies for succor and stability,
and so lose your share in the everlasting riches and glory,
which God is preparing for the souls of his chosen?
Why will ye die?
Why will ye perish?
Why will ye undo your souls?
Why do ye so greedily sow misery, anguish, perplexity,
and wrath for your poor souls to reap?

O God of love! who knowest the value and price of souls, pity thy poor creatures,
and put a stop to this course of perishing,
wherein so many multitudes are overtaken and pass down to the pit unawares!
O thy bowels, thy bowels, thy wonderful bowels!
Let them roll in thee, and work mightily,
and in the strength of thy compassions bring forth
thy judgment and thy mercy among the sons of men!
Build up the tents of Shem; persuade Japhet to dwell therein;
and let Canaan become a servant.
Preserve the feet of thy saints forever;
shut up and silence the wicked one in the darkness;
let not his strength or subtlety prevail against thee or thine any more:
but let the fresh power of thy life, and the virtue of thy incomprehensible love redeem,
fill, possess, and make glad the heart of thy creation forever; Amen, Amen.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Printed 1661
