[#persecution, short="Concerning Persecution"]
== Concerning Persecution:

[.heading-continuation-blurb]
Which is the afflicting or punishing that which is good,
under the pretence of its being evil.

[.heading-continuation-blurb]
Which practice is contrary to the very nature of mankind
(so far as it is drawn out of the corruption and depravation),
which would be good, and do good, and have good cherished and evil suppressed,
both in itself and others.

[.heading-continuation-blurb]
It is contrary also to all equal and righteous government,
which is for the suppressing of evil, and cherishing of good;
and not for the afflicting and crushing of that which is good,
upon pretence of its being evil.

[.heading-continuation-blurb]
Yet this unhappy error will always be committed in nations and governments,
until the proper right and just liberty of men`'s consciences be discerned,
acknowledged, and allowed.

[.heading-continuation-blurb]
Likewise there are some answers given to that common objection,
against affording conscience its due liberty;
because evil persons may pretend conscience to escape the just punishment of their evil deeds.

[.heading-continuation-blurb]
With a brief account of that supposed stubbornness,
which by many is objected against the people called Quakers.

[.heading-continuation-blurb]
Given forth in love to this nation,
that at length the true bottom and foundation of a lasting peace and settlement may be espied;
the spirits of the governors and people fixed thereon;
and that dangerous rock of persecution
(whereon both the powers and people of this nation have so often split)
carefully avoided by all.

[.section-author]
By _Isaac Penington,_ the Younger

[.section-date]
1661

=== Preface

There hath been an enmity in the seed of the serpent against the seed of the woman,
from the time of the promise even until now.
God, in mercy to mankind, hath given unto him since the fall,
a seed or principle of life;
in the light and strength whereof he is to war against and subdue the corrupt principle,
and so be freed from the curse, and become heir of the blessing.
Against this principle all the powers of darkness fight (even in every
particular man and woman) until they be overcome and subjected there:
and against those in whom this pure principle reigns,
all the powers of darkness in the world fight also, striving to make it miserable,
and to bring it into death and captivity,
that they might keep up the content and happiness of the corrupt state.
All the nations of the earth have always warred against
the principle of God and the people of his choice.
In the time of the law, the Jews were the object of the envy and hatred of all the world;
in the times of the gospel, the Jews in spirit were hated and hunted,
in that day and hour, not only by Heathens,
but also by such as were Jews according to the letter; and ever since the apostasy,
by Christians also according to the letter;
who are as great enemies to the Spirit and power as ever the Jews were.

Now all the misery of the world,
as it at first came by departing from the principle of life,
so it hath been ever since continued by men`'s joining
with the principle of death and corruption,
to oppose and withstand the workings of the principle of life,
both in themselves and others.
What man is there that hath not in him a witness against that which is evil?
But where is that man who joins with this witness in him against the evil,
and not with the evil against this witness?
Oh, how doth God`'s witness reprove for sin,
making the heart (which is not sensual and brutish,
but seriously considers its latter end) sad because of it!
This is God`'s way of making the creature weary thereof, of weaning him from it,
delivering him out of it, and so rescuing him from the wrath and everlasting burnings,
which are the portion and inheritance of the wicked.
But who is it that doth not strive to stop, silence, and suppress the witness in himself,
that he might enjoy his lusts, ease, and content in the flesh,
by keeping the sight and remembrance of the evil day far from him?
And if he can do so, then he rejoiceth,
and maketh merry over the testimony of the witness in himself;
and when he hath so far prevailed, then he is in a good capacity to persecute others,
who hear and obey the voice and testimony thereof in themselves.

That which is to redeem the world out of misery is the power of the gospel;
and precious is the peace which comes thereby,
after the work of the spiritual sword (with the trouble thereof) is finished.
Oh, how blessed would the principle and power of life make the world,
might it but have its free course therein!
Oh, how happy is that man who bears the condemnation because of sin,
follows the guidance of the living God, and waits for the day of his salvation!
Oh the sweet inward peace of spirit which is enjoyed after the storm,
and after the judgment of that which is to be judged and destroyed!
And that which makes one person happy, the same must make nations happy.
There is no true settlement, nor abiding security,
but in the settled and abiding principle.
God is arisen to shake the earth, and it can settle no more upon the old foundations:
yea, the same God hath shrivelled up the old heavens,
and they can no more be stretched forth again.
"`Behold I make all things new,`" saith the Lord, in the days of the gospel,
when he stretcheth forth the arm of his power:
and who is he which shall venture to establish the old heavens and the old earth,
which the Lord God is removing, and causing to pass away,
and abolish the new heavens and the new earth,
which the Lord God hath created and formed, and is establishing?
Oh that men knew the place of wisdom, that they might be wise,
and not fight against their Creator, from whom their strength comes,
and against whom their strength cannot prevail!
Oh that men could see how industrious they are to keep up misery,
and to keep out happiness!
The eye of man, in the fallen and corrupt estate, cannot see aright; and misseeing,
how can he choose but misaim and misact?
And misaiming and misacting, how can he attain his end?
But the Lord`'s counsel shall stand,
and he will fulfill all his pleasure in every heart throughout the earth.
Happy is he who is weaned from himself, and begotten in the light of life,
which is incorruptible; he shall stand and be blessed,
when all flesh falls before the breath of the Lord, and becomes miserable;
and the fall of all the fleshly will, wisdom, and strength hastens apace;
happy is he who is delivered from them before the day of
their ruin! which is nearer than man is aware of,
or can believe.

=== Concerning Persecution

Because men generally, in persecuting,
know not what they do (neither whom it is they persecute,
nor how they sin against God therein, nor what danger they are exposing themselves to,
and what misery they are drawing upon themselves thereby,
both in this world and forever), even as Christ said concerning the Jews,
who were persecuting him even to death, "`Father, forgive them;
for they know not what they do:`" and afterward to Saul; "`Saul, Saul,
why persecutest thou me?`" Therefore,
in love to those who are at unawares running into this great error,
that they may find the good hand of God stopping them therein for their own good,
are these things following concerning persecution written, wherein are manifested,

[.numbered-group]
====

[.numbered]
1+++.+++ What it is that is persecuted.

[.numbered]
2+++.+++ Who it is that persecutes, or is the persecutor.

[.numbered]
3+++.+++ The nature of persecution.

[.numbered]
4+++.+++ The grounds or causes of persecution.

[.numbered]
5+++.+++ The ways and means of persecution.

[.numbered]
6+++.+++ The ends of persecuting; what men aim at therein, or rather what the spirit in men,
which puts them upon persecuting of others, aims at thereby.

[.numbered]
7+++.+++ The color, or false pretence, of the persecuting spirit.

[.numbered]
8+++.+++ The blessedness of the persecuted.

[.numbered]
9+++.+++ The misery of the persecutors.

[.numbered]
10+++.+++ The way and means whereby men may come to avoid this great evil of persecuting others.

====

Whereunto, in the last place, are added, _some sad effects of persecution;_
to kindle in men a desire of avoiding so great an evil in itself,
and so pernicious an enemy to all that is good in general,
and particularly to the peace and welfare of mankind, as the persecuting spirit is.

==== 1. What or Who It Is That Is Persecuted

The persecuted in all ages is that "`which is born after God`'s
Spirit.`" Gal. 4:29. He that is new-created in Christ Jesus,
who is formed in the image and by the Spirit of God (which
is contrary to the image and spirit of the world),
and who follows Christ in the leadings and teachings of his Spirit (which is out of,
and contrary to, the course, fashions, ways, and customs of the world),
this is the man that is persecuted in all ages.
He that is of another spirit and principle than the world,
and so cannot be as the world is (being made otherwise by God),
nor walk as the world walks, nor worship as the world worships,
being taught and required of God to do otherwise; this is the man who is afflicted,
reproached, hated, hunted, persecuted.
And so the apostle lays it down not only as a thing to be in his age,
but in after ages also. 2 Tim. 3:12.
"`Yea,
and all that will live godly in Christ Jesus shall
suffer persecution.`" Men may talk of Christ,
profess Christ, worship Christ according to the way that is set up in nations,
and avoid persecution; but come under the new principle, come into his life,
live godly in him, become really subject unto the power and direction of his Spirit,
then there is no longer avoiding of persecution.
That which comes into the life of Christ comes presently into a
proportion of suffering from that which is contrary to his life.

==== 2. What or Who It Is That Persecuteth, Or Is the Persecutor

The persecutor, in all ages, is that which is after the flesh.
That spirit and principle in man which is from beneath, puts the men in whom it is,
upon persecuting the other principle, and the persons in whom it appears.
Or more plainly thus: that which is of the world, that which loves the world,
and present state thereof, that which lies in the darkness, is in unity with it,
loveth it, and the corrupt ways thereof; that hates the light,
and persecuteth the children of the light, who are witnesses against,
and reprovers of the darkness. John 3:20.
"`He that was born after the flesh,
persecuted him that was born after the Spirit.`" So it was formerly, so it is also now,
saith the apostle. Gal. 4:29.
Now there are several sorts and ranks of these;
as some in the way of open profaneness and wickedness, some more civilized,
and of a more gentle, noble, and considerate spirit and temper,
some more religious and devout in worships (though not rightly principled and guided,
but turned aside to some inventions or other of the earthly spirit,
all which are pleasing to the earthly spirit), but all these,
though they are different one from another, and agree not well among themselves,
but are full of dislikes one toward another; yet they all agree in this; to wit,
in a willingness to have that persecuted and subjected which
is of a contrary spirit and nature to them all.
They are all against this more or less;
though not all against it in the same degree of heat and vehemency.

==== 3. The Nature of Persecution, or What It Is to Persecute

Persecution is the opposition of the flesh against the Spirit.
The fretting or dashing of the earthly spirit, or spirit of man corrupted,
against that which is born of God:
the fighting of the unregenerate and unrenewed spirit in man,
against the spirit of man renewed by the regenerating power of the Spirit of God:
the fighting, the opposing of this spirit against the other, is persecution.
Whatever any man does in his own will, according to his own wisdom,
and after the inclination of his own heart,
against another who desires to fear the Lord (who waits
on him for the counsel and guidance of his Spirit,
that he might obey and worship him aright), is persecution.
The principle of God teaches to fear the Lord;
not according to the fear which is taught by the precepts of men,
but according to the fear which God puts into the heart.
It teaches likewise to worship the Lord,
not according as man invents and thinks good to prescribe,
but as the Lord instructs and requires.
It teaches likewise not to conform to the world, but to deny it, and come out of it.
Now the hating, opposing, and punishing of that which is taught,
because of these teachings, and its obedience thereto, this is persecution.
The rising of the heart against such, is persecution in the heart.
The reproaching, scoffing at, or speaking evil of such, is persecution with the tongue.
(So Ishmael`'s mocking of Isaac Gen. 21:10-9. is called persecuting of him.
Gal. 4:29-30) The smiting, fining, imprisoning of such, etc.,
in relation to any thing that they do from this principle, is persecution with the hand,
or lifting up of the power, either of a particular person, or of a magistrate,
against such.

==== 4. The Grounds of Persecution, or What Are the Things That Cause the One Spirit and Principle to Persecute, and the Other to Be Persecuted

The grounds and causes which expose the one to persecution,
and kindle the heat of persecuting in the other, are chiefly these three ensuing.

[.numbered-group]
====

[.numbered]
1+++.+++ The enmity of the birth of the flesh against the birth of the spirit.
There is enmity in the serpent against the woman,
and in the seed of the serpent against the seed of the woman.
That which is born of the corrupt principle cannot
endure that which is born of the pure principle.
That which walks and worships in the will,
and according to the inventions of man`'s wisdom, and in shadows and fleshly forms,
pleasing to the flesh, cannot endure that which worships in Spirit and truth.

[.numbered]
2+++.+++ The contrariety of that which is born of God, and drawn out of the world,
to that which is of the flesh, or of corrupt man, and left in the world,
this is that which increaseth and draweth forth the enmity in the corrupt principle.
"`They are not of the world,
even as I am not of the world,`" John 17:16. "`therefore
the world hateth them.`" ver. 14. They are of another spirit,
of another image, of another make, of another heart, of another desire,
of another manner of carriage and demeanor, of another principle,
and have other ends in all they do, than the world.
And their whole course and conversation being in the light, and in the love,
and in true purity of mind, reprove the world, which lies in the darkness,
and in the enmity, and walks in the wickedness.
And how can the world bear this; in the midst of all their height, glory, and greatness,
to be continually reproved by a poor and contemptible generation,
as God`'s choice in the world have, for the generality of them, always been;
even looked upon by the world as the off-scouring thereof,
as not fit to be suffered to have a being in it,
but rather as deserving to be scoured off from it?

The light, whereof the children of light are born, and which they hold forth,
or rather which God holds forth by them, condemns the world.
The evenness, sweetness, and straitness of their conversation and practices,
condemn the unevenness, crookedness, and perverseness of the spirit of the world.
The integrity, seriousness, and spirituality of their worship,
with the living presence and power of God appearing among them, condemn the deadness,
formality, and hypocrisy of the worships of the world;
who draw nigh to God with their lips,
when it is manifest that their hearts are far from him,
being ensnared and captivated with vanities and self-interests,
and love of the world and earthly things.
Indeed the whole course and manifestation of the light and power of God in them is a
continual upbraiding of the principle and ways of darkness in the men of the world.
And how can the men of the world forbear making an unrighteous war,
even a war of persecution, against that which invades their territories,
and makes war with them in righteousness?
Can darkness choose but fight to save its own dominions?
It must put out the light, or it cannot save its own, but will be losing of ground daily.

[.numbered]
3+++.+++ Because of the children of light leaving and coming out of the world.
They were once of the world, as well as others, of the same nature, of the same spirit,
of the same corrupt will, of the same corrupt wisdom, walking in their way,
worshipping according to their worships, approving and observing their customs, fashions,
and vanities; but when the Spirit of Christ called them out of the world,
and created in them that which could hear his voice, and was willing to follow him,
then they left all these, and stood witnesses (in God`'s Spirit which called,
and in that life which was begotten in them, and in the fear, love,
and power of that God who quickened them) against all these.
And this mads the world, in that they were once of them, but left them.
Had they stayed in the world, and been still of the world,
the world would have loved them, as it doth the rest of its own,
but departing from the world, traveling towards another country,
subjecting themselves to another Spirit,
and testifying against that spirit which formerly led them, and still leads the world,
and against those ways and practices wherein they formerly walked,
and wherein the world still walks, this fills the worldly spirit with rage against them.

====

==== 5. The Ways and Means of Persecution

The ways and means of persecution are very many.
Who can want instruments to afflict the innocent and helpless,
who can neither resist the evil which is offered them, nor harm that which offers it?
I shall only mention here three general heads, to which many particulars may be referred.

[.numbered-group]
====

[.numbered]
1+++.+++ One great way of persecution is by making use of laws already made,
either according to their proper tendency to that end and purpose,
or by bending them aside from their proper intent,
to reach those whom they have a mind to afflict and persecute.
Thus the Jews, when they had a mind to have Christ put to death, told Pilate,
"`We have a law, and by our law he ought to die.`" John 19:7.

[.numbered]
2+++.+++ Another way is, by making new laws fit for their purpose, whereby they may catch,
ensnare, and suppress that which is contrary to their spirit and principle,
and which will not bow thereto.
This is a certain way to take that which is born of God,
and which cannot but be true to him, and so cannot bow to the corrupt will of man,
nor to any law made in the corrupt will, to strengthen the corruption,
and against the holy, pure will and mind of God.
Thus Daniel and the three Children were caught in the snare by laws; Daniel,
for praying to his God, against the royal statute and firm decree of the king,
signed in writing according to the desire and advice of all the presidents of the kingdom,
the governors, princes, counsellors, and captains, Dan. 6:7-8.
and the three Children,
for not worshipping the image Nebuchadnezzar had set up,
according to the decree of the king.
(Observe this by the way, and consider it well:
what hath been set up all this night of the apostasy, but images of the true worship;
and what compelling hath there been thereto.) Thus have articles been framed,
and statutes made, here in England,
(as in King Henry the VIIIth and Queen Mary`'s days)
which have been great engines of persecution;
and thus have there been some late laws made in New-England to the same effect,
though better might have justly been expected from them.
And this is not only a certain way, but a very plausible way likewise,
whereby the persecutor hides himself from the imputation of persecution,
and appears as a just executer of the law;
and so represents him who is upright before God, and innocent in the sight of God,
as an offender and breaker of the law, and so justly punishable.
But this will not always cover the unjust spirit`'s persecuting of the just.
He that shall persecute the Lord of glory (as he
that persecuteth the least member of his,
how contemptible soever he appears to his eye, doth no less, Acts 9:4.
Matt. 25:40,45) when Christ shall call him to account therefor,
it will be a vain plea for him to say, there was a law for it,
and he acted according to law.
It is fit for all men and laws to bow before the Lord,
and not to disturb any in their obedience to the Lord,
or hurt the principle of his life in any;
but cherish and nurse it up as much as in them lies,
in that tenderness which Christ begetteth in it,
and in that spiritual liberty which Christ allows it.

[.numbered]
3+++.+++ A third way of persecution is by the hand of violence, without either law,
or so much as pretence to law.
Thus the persecuting spirit, when it hath power in its hand, and is out of fear,
smiteth (with the open fist of wickedness) that which is an enemy to,
and stands a witness against, its wickedness.

====

==== 6. The Ends of Persection, or What the Persecuting Spirit Aims At in Its Persecuting, and Would Fain Attain Thereby

[.numbered-group]
====

[.numbered]
1+++.+++ The main end of persecution is to bring the children of light (who have left the evil,
darkness, and corruption of the world) back to the world again.
That which they persecute them for is for leaving the world,
both in its principles and practices,
and for professing obedience and subjection to another spirit;
that which they drive at in persecuting them is to force them back from
under subjection to that spirit which hath led them out of the world,
into subjection to the spirit of the world again.
There is a great fight between the Spirit of God
and the spirit of the world in the two seeds;
the Spirit of God striving to bring the spirit of the world under,
and the spirit of the world striving to bring the Spirit of God under.
This is well known in the heart where the new birth is witnessed.
Oh, what striving there is by the powers of darkness,
with all manner of secret temptations and forcible oppositions (so far as the Lord permits),
to bring the heart (which the Lord hath begun to redeem,
and in some measure set free from them) under their power again!
And the same that stirs up the darkness in the heart
against the seed and birth of light there,
the same stirs up in the darkness in other men against it also.
The Lord knows what bitter fights we have had with the enemy in our own hearts,
before we could leave our principles, paths, and practices of darkness;
how hard it hath been to us to deny the world, and come out of it;
and yet when the Lord hath conquered and subjected
the darkness in our own hearts in any measure,
then we meet with a new fight abroad in the world,
the same principle and power in them fighting against us, as did at first in ourselves.
And as this was the aim and work of the power of darkness in ourselves (and still is,
so far as any of it is left in any of us) to bring us back under the darkness again,
even from the light and leadings of the Spirit, and from single obedience thereto;
so it is the aim and endeavor of the same spirit in others.
And if they could but bring us back from our God into the world again,
they would be at peace with us, as well as with other men, and love and cherish us,
as they do the rest of the world.

[.numbered]
2+++.+++ A second end of persecution in the spirit that persecuteth is,
to keep the children of light from gaining further ground.
The kingdom of God and his truth is of a growing, spreading nature.
It is like leaven, like salt, like the light of the morning; its nature is to leaven,
to season, to overspread, and gather mankind from the evil, from the darkness,
from the corruption, from the death and destruction.
Now the spirit of the world, that spirit which ruleth the world, is loth to lose ground;
and therefore hunts and seeks to destroy the vessels wherein the light appeareth,
and from whom it shineth forth, and to make them appear as odious as it may,
that it may keep all its own territories and dominions in a perfect detestation of them,
and distance from them.
Thus though the people of God have still been an innocent people,
and simple as to the subtlety and deceit of the serpent,
and weak and foolish in compare with the wise and
strong ones in the worldly nature and spirit;
yet they are still represented as most dangerous, most subtle, and pernicious,
as shrewd deceivers, witches, Jesuits, etc., yea, any thing that is hateful and hated.

[.numbered]
3+++.+++ A third end of persecution is to afflict, grieve, vex, disturb,
and torment those whose principles and practices are displeasing to them.
There is enmity in the nature and spirit of the world, against the holy,
pure Spirit and seed of God; and if it cannot overcome and get its will one way,
in bringing back; yet it will strive to have its will another way,
even in vexing and afflicting.
It is the pleasure of hatred or enmity to do any thing which
may hurt that against which its hatred is.
Thus the evil spirit _rejoiceth in iniquity,_ in grieving and afflicting that which is good.
As the Spirit of love delights in love, and in doing good even to those which persecute;
so the spirit of enmity delights in hatred and doing evil;
even in vexing and oppressing those which seek their good, because they are not,
and cannot be, one with them in their dark principles and evil practices.

====

==== 7. The Color or Pretence Which Men Put upon Their Persecutions of That Which Is Good

Persecution is so hateful (and hath such a blackness of spirit
in it) that it cannot endure to appear in its own color.
Where is the man that would appear to persecute that which is good in men,
or men because of their goodness?
Therefore all persecutors, though they still persecute that which is good,
and those which are good; yet they still represent and charge them as evil,
that they might thereby hide the badness and unjustness
of their persecutions from their own eyes,
and from the eyes of others.
Thus the true prophets of the Lord were always misrepresented by their persecutors,
even as false prophets, as "`troublers of Israel,`" as madmen,
as men not fit to be tolerated in the kingdom or commonwealth of Israel.
See Jer. 29:26-27. And those which condemned their forefathers
for persecuting the true prophets in former days,
yet could also persecute the true prophets in their own days.
When Christ himself asked the Jews for which of his good works they stoned him?
they said "`Not for a good work,`" or _as a good man;_ but _for his doing evil;_
for his _blasphemy;_ in that he, _being a man, would make himself God._ John 10:32-33.
And the Pharisees did not represent him as a good man,
as a holy teacher from God, (as indeed he was,
though his doctrine and conversation differed very much from theirs) but as a deceiver,
a seducer of the people, a mean man, the son of Joseph the carpenter,
one whom none of the wise scribes owned, but only such silly people as knew not the law,
John 7:49, yea, as a very bad man,
as one that was against the worship and ordinances of Moses,
against God`'s temple and priests in his doctrine and principles,
and a profaner of God`'s holy sabbath in his practices; yea, more than this,
they represented him as a man that had a devil,
and that he was able to do such great things beyond them through Beelzebub,
the prince of devils.
Could the Jews think they did otherwise than well
in desiring such a man as this to be put to death?
Might they not well prefer Barabbas before a man
thus represented by their chief priests and teachers,
who knew and could expound the law, and were best able to judge,
as they might well think, both what was the truth, and who were deceivers?

==== 8. The Blessedness of the Persecuted

The disciple of Christ, who is persecuted for conscience`' sake,
who suffers from men and their laws for the uprightness of his heart towards,
and for his obedience unto, Christ, that man is precious in the eye of Christ,
and hath his blessing with him; yea,
the more men disesteem and hate him upon this account the greater is his blessedness.
"`Blessed are ye when men shall revile you and persecute you,
and shall say all manner of evil against you falsely for my sake.
Rejoice, and be exceeding glad.`" Matt. 5:11-12. He is blessed in several respects.

[.numbered-group]
====

[.numbered]
1+++.+++ That man is in that spirit, and in that way, which God hath chosen,
and so he is in a happy state and condition at present.
He is in the path of life, in the way of peace, under the leadings of God`'s Spirit.
The world loveth and cherisheth that which is its own, and walketh with it;
but is at enmity and war with that which is of God.
Therefore the world`'s dislike, enmity, and persecution are an evidence of God`'s choice,
and of a removal from it towards God.
It is a happy thing in the eye of man to be at unity with the world,
to have the love and friendship thereof, to have all men speak well of one,
to be found doing that which is pleasing in the eye of the world,
and to be enjoying the pleasures and profits thereof;
but in the eye of God it is happy to be in a unity
with that which is contrary to the world,
and procureth its ill-will.
"`Love not the world, neither the things that are in the world.
If any man love the world, the love of the Father,`" which begetteth out of the world,
"`is not in him.`" But he that loseth the love of the world, for the principle of God,
and his subjection thereto, is in that which the Father loveth,
and feeleth the love of the Father opened in him, and revealed to him;
and this is truly a happy state.

[.numbered]
2+++.+++ The recompense which God will give to them in the world to come,
who cleave to him and his truth,
for all the persecutions which they endure in this world for his truth`'s sake,
is exceeding great.
"`Great is your reward in heaven.`" Matt. 5:12. "`Our light affliction,
which is but for a moment,`" but at most for the time of this world,
"`worketh for us a far more exceeding eternal weight of glory.`" 2 Cor. 4:17.

[.numbered]
3+++.+++ The reward is great in this world also.
There is a hundred-fold recompense to be reaped in this life.
The peace of God in the conscience, the presence of God, the life of God,
the virtue of God, the glory of the Spirit of God, which accompanieth, resteth with,
and abideth on, the heart which is faithful, and waiteth upon God for patience, meekness,
innocency, and strength to carry through sufferings,
may well be valued at above a hundred-fold income and recompense for all
the hardships and tribulations which are undergone for his name`'s sake.
"`If ye be reproached for the name of Christ, happy are ye;
for the Spirit of glory and of God resteth upon you.`" 1 Pet. 4:14.

====

==== 9. The Grievous Misery of the Persecutors

It is a miserable thing to be deceived about that which is good; to put good for evil,
light for darkness, sweet for bitter, and so, under a mistake at least,
become a persecutor of the good.
All good is of God, and he that is against good is against God;
and it is a dreadful thing for the creature to set himself in battle against his Creator,
and to engage the power and wrath of the Omnipotent One against him;
though while the eye is shut, it doth not appear to men either that they are against God,
or that their danger is so great thereby as indeed it is.
The children of God are as the apple of his eye.
Who can touch them, and he not be deeply sensible?
Yes, and they are most dear to God in that for which the world most persecutes them;
and therefore their danger and misery must needs be great;
which may further appear in these three respects:

[.numbered-group]
====

[.numbered]
1+++.+++ In respect of the weight of wrath which their persecutions of
others here will bring upon themselves in the world to come:
then every hard word, with everything they have done against any lamb of Christ`'s,
shall come upon them.
There is a time of judgment for all that is sowed in this world,
and then every one shall reap what he hath sowed.
And if he that hath not visited the sick and imprisoned
for Christ`'s sake shall hear that sentence,
"`Go ye cursed,`" etc.; what will his portion be who hath imprisoned them,
and caused their sickness?
Now is our time of trouble;
but the Lord hath prepared a day of rest for that spirit
which is troubled in this world by the spirit of this world;
and then shall the troublesome spirit, which troubled the peaceable spirit,
and would give it no rest in its following and obeying the Lord,
be troubled by the Spirit of the Lord. 2 Thess. 1:6-7.
And what shall the misery of that spirit be,
whom the Spirit of the Lord troubleth and filleth with anguish and torments, in his fire,
and with his brimstone!
Oh that men would awaken, and consider in time,
and not sell away their everlasting inheritance for a mess of vanity,
and transitory lusts and pleasures.

[.numbered]
2+++.+++ The hand of God doth often overtake them in this world,
and the Lord doth many times curse their very blessings to them,
insomuch as they cannot enjoy the world with that sweetness and content they might,
were it not for the rage and bitterness of their spirits against God`'s people,
and their provoking of God against them thereby.
How many of his own people did Pharaoh lose,
and how did he break the strength and glory of his kingdom,
by persecuting God`'s Israel of old?
How did Amalek cause his name to be rooted out from under heaven?
How did the nations and mighty powers of the earth fall upon this account,
one after another?
And in this nation how many powers have already fallen thereby?
_Jerusalem is a burdensome stone_ (it was so in the type,
it is much more so in the substance),
which lies in the way of every earthly spirit and power;
which they know not how to build with,
neither can they rear up their own building because of it,
and therefore every power strives to remove it out of their way;
but they know not the weight of it, nor who it is that hath squared it,
and how firm it is fixed upon the rock.
The earthly spirit is never to enjoy any true or lasting peace and settlement
(which is the gift of God) until it leave off persecuting God`'s Israel
(which are the people whom God calleth out of the world),
and leave them free for God to enjoy, command, and dispose of;
and whatever holds Israel in bondage, either within or without,
must either be subject to the Lord,
or be broken by that arm of power which the Lord putteth forth to redeem Israel with.

[.numbered]
3+++.+++ By all their persecutions and afflictions they shall but increase
and cause to grow that which they strive to suppress.
This is misery indeed for a man to hazard his soul eternally,
and his peace and prosperity in this world, to crush and suppress a people,
and yet not be able to effect that neither,
but even thereby occasion their growth and increase;
and yet so it is in the day that God putteth forth his hand to redeem Israel.
The ways that man takes to bring them back into captivity
shall be the means of perfecting their redemption.
"`Come (said Pharoah) this people multiply too fast: they grow more and mightier than we;
let us deal wisely with them, and keep them down by hard labor,
lest they grow over-numerous, and join with our enemies against us,
when they see their advantage.`" But they grew and spread the more,
upon his wise plotting and contriving to diminish them.
And what did he get by striving to keep them from going forth of
his land and idolatrous worships to worship the Lord aright,
but plagues and judgments upon himself and his people from the Lord?
Can the powers of the earth withstand God any more now than they could formerly?
Shall he not redeem and bring forth his people from the land of Babylon?
His spiritual Israel from spiritual Egypt?
Shall he not break the antichristian yoke from their consciences,
that they may be free in spirit to serve the Lord?
Can any hinder God from breathing his Spirit upon people,
and from begetting them in the image and likeness of his Spirit unto himself?
And shall not these be the Lord`'s? Shall not the
same Spirit teach them to worship the Lord?
Shall God call them to worship him openly, and shall they not obey him,
but worship him according to man`'s inventions and commandments, or not at all publicly?
O ye sons of men! be wise; do not contend with the Lord;
be not bewitched by the cup of fornications from the pure,
spiritual worship of the living God into man`'s inventions,
which the Lord`'s soul loathes; nor do not strive to hold any back from the Lord,
whom the Lord draws after him; but consider his power,
wait to know his work in the world, and do not intrench upon his dominions,
but be thankful for and content with your own; and do not provoke him against you,
who can more easily take yours from you than ye can his from him.
And consider this watch-word, in that which can open and show the truth of it;
_the Lord hath put forth his arm to recover his possessions
from out of the hands of antichrist;_
and who shall be able to force it back again, to make it return into his bosom,
without effecting what he stretched it forth for?

====

Therefore,
O magistrates of this nation! do not make use of the sword to suppress the plants of God;
but to cut down that which manifestly is not of God.
Look abroad throughout this nation;
behold how much evil there is to grieve and provoke the Lord,
and to divert good from the nation, and to bring wrath upon it,
and the government thereof; strike at that in righteous and true judgment,
and with mercy to creatures`' souls and bodies.
But that which certainly is of God, meddle not with;
and that which may be of God for aught ye know, be circumspect in meddling with,
lest ye engage God against you.
It were better to let many tares grow, than to pluck up one ear of corn.
Christ hath absolutely expressed it to be his mind,
that he would not have that done which may so much
as hazard the plucking up of an ear of corn. Matt. 13:29.
But oh,
how are the laws and governments of this world to be lamented over!
And oh, what need there is of their reformation,
whose common work it is to pluck up the ears of corn, and leave the tares standing!
The chief cause of this misery (from whence it principally ariseth) is
men`'s meddling with those things which God has reserved for himself,
and assaying to do that carnally which God did spiritually,
and will do spiritually again, in his due time,
when he hath sufficiently shown how untoward and improper man`'s hand is to effect it.
The Christians in the apostles`' days were "`of one heart,
and one mind,`" which proceeded from the power and work of God upon them;
and then they soon came into one way and worship;
but men will have unity and uniformity in a way of religion
and worship before there is one heart and one mind.
Now this is contrary to the Spirit of God, and to the very nature of religion,
and the cause of much cruelty upon men`'s consciences:
and this hath been and will be the constant effect of it, even the crushing,
as much as lies in man, of that which is tender, and of and for God,
and the increasing of that which is formal, dead, and earthly.
Now if ever Christ appointed or intended such a church-government,
which naturally produceth this effect, let all that fear God, and are of sober spirits,
judge.

==== 10. The Way and Means to Avoid Persecution

Where is the man (in whom there is any good,
who hath any love to goodness and righteousness,
who hateth cruelty and oppression over men`'s outward liberties and estates,
and much more over the consciences of people) that could
not with his heart desire to have this grand enemy removed,
both from particular persons, and also from governors, and governments,
that peace and settlement might be known; righteousness reaped;
all cruelty and hardness in one man towards another removed;
and there be _no more complaining in our streets;_ either because of _oppressions from men,_
or fear of _wrath from God,_ upon those governments which oppress?
And who would not earnestly pray to God for the discovery of that way and those means,
and be very industrious in the use of them,
whereby this persecuting spirit and temper might be wasted and dried up in him?
Now the way and means whereby the persecuting spirit may be subdued, are divers; As,

[.numbered-group]
====

[.numbered]
1+++.+++ _By a true awe and fear of God in the heart._
The fear of God teacheth to depart from iniquity,
and to seek the crucifying and bringing under of the worldly spirit in a man`'s self,
and to wait daily to have God`'s will revealed,
and likewise to be made obedient thereunto.
Now he that is in this temper of spirit, will hardly be drawn to persecute another,
but rather rejoice to see a tenderness of spirit in him,
and true subjection of heart to what he believes to be the mind and will of God;
and dares not so much as judge him for differing, either in apprehensions or practices,
about worship, much less persecute him therefore.
But that man who is of a profane spirit, or comes easily by his religion,
even by the wisdom, industry, and parts of a man, and not by the gift of God,
and is exercised in that fear of God which is taught by the precepts of men,
but knoweth not that fear which God puts in the heart
(from whence the true religion and worship springs),
either of these may be drawn to persecute; yea, indeed,
it will be hard for either of them to abstain therefrom.

[.numbered]
2+++.+++ _By a meekness of spirit._
The gospel makes meek, tender, gentle, peaceable;
fills with love and sweetness of spirit; teaches to love, to forgive,
to pray for and bless enemies: and how shall this man persecute?
Can a lamb persecute?
Can a dove persecute?
Indeed a wolf in sheep`'s clothing may raven and devour, but a true sheep cannot.
As the power of the gospel is known, the devouring and persecuting nature is destroyed;
and that being taken away, persecution soon comes to an end.

[.numbered]
3+++.+++ _By a sober and patient consideration of their cause whom they persecute,
and what it is in themselves which moves them to persecute them._
The strength of persecution lies in the darkness, in the dark thoughts, misjudging,
and misapprehensions about him whom one persecutes, or is inclined to persecute;
in prejudices and false judgments of persons and things received; which,
by a sober hearing and considering of things in God`'s fear and meekness,
might be removed; and then the eager,
persecuting heat of spirit would soon abate and fall, the fuel, which kindled it,
being taken away.
"`The Jews stopped their ears,
and ran upon Stephen.`" Acts 7:57. This is the way of persecuting spirits;
they take in prejudices against persons, their principles and practices,
stop their ears against what may be said to manifest
either the equity of the thing in itself,
or their mistake about it,
and then run headlong in their fury of persecuting and devouring.
But he that is sober and considerate, and weighs the cause before he engages against it,
and observes what it is in him which moves so hotly against another,
and which is so ready to believe ill aforehand; he shall soon see that,
which is always hid from the eye of the persecutor,
and find water to cast on this devouring fire of spirit in him.

[.numbered]
4+++.+++ _By a righteous frame of spirit, which is willing to do by another,
as he would be done to in the like case._
Persecution ariseth from unrighteousness and selfishness;
righteousness and true equity would soon end it.
If no man would make another man`'s conscience bow by force,
who would not have his own so bowed, persecution would soon cease.
But this is the great evil and unrighteousness of man; whoever is uppermost,
thinks he hath a right to bow all the rest under him,
and looks upon them as guilty and offenders,
if their consciences do not yield and bow under him.
And he that newly complained of the load laid on his conscience by others,
yet if he can get ease and power into his hand, is presently laying a load upon others.
Here is a wrong frame of spirit within,
and how can it choose but bring forth injury and persecution outwardly?

[.numbered]
5+++.+++ _By taking heed and watching against the corrupt and carnal principle,
with the reasonings, self-ends, and interests thereof,
and hearkening to the principle of God, which teacheth and speaketh right reason._
Man as he came from God, and was by especial favor formed in his image,
so it pleased God to place in him a principle of his own life to govern him.
This image was defaced by the fall, and this principle forfeited,
yet for Christ`'s sake (who is the Saviour of all men,
but especially of them that believe) the Lord stirreth
up and visiteth all mankind more or less,
by the pure eternal principle of his own light and life in Christ.
In hearkening to this, man`'s reason is rectified, purified, and preserved pure;
and his steps here are safe.
But consulting and contriving out of this,
he meets with that which corrupts him (captivating and misbiasing his reason);
and then all his intents, designs, and contrivances become corrupt,
and tend not only towards the prejudice of others at present,
but also to his own loss and detriment in the issue.
He therefore that would be safe in the enjoyment
of any blessing which he hath received from God,
and faithful in doing him service in his generation,
must know what of himself is ready to betray him, that he may watch against it,
and turn from it; and what in himself is given him of God to enlighten, guide, instruct,
and preserve him, that he may hearken thereto, and be made happy thereby.

====

==== 11. The Fruits and Effects of Persecution

And lastly, to set it yet more home upon all that are ingenuous,
and would be worthy and noble, and do that which is worthy and noble, abhorring cruelty,
afflicting and oppressing of others;
let them consider _the fruits and effects of persecution,_ which are very many,
and of the worst kind, even suitable to the nature of the root.
At present I shall only mention these four.

[.numbered-group]
====

[.numbered]
1+++.+++ In a great degree, _it hindereth the growth of the present good,
in every age and generation,_
so far as the earthly power or sword of the magistrate can well hinder.
Persecution of that which is good by the earthly powers, in its proper tendency,
is an hindrance to the growth thereof in their age and day;
though the Lord can overbear the malignity of it,
and further the growth of his seed thereby.

[.numbered]
2+++.+++ _It wholly tends towards hindering the shooting up of any further seeds of good,
which God hath to sow in the earth._
For all the seeds of good which God hath to sow in the earth,
at first they are looked upon as evil; until by God`'s blessing upon them,
and opening of men`'s eyes through the much suffering of those vessels,
in whom God causeth the most excellent seeds of his virtue and goodness first to appear,
their innocence and beauty begin at length to shine in men`'s eyes, and be discerned.

[.numbered]
3+++.+++ _It occasioneth the growth of evil._
For good with-standeth, opposeth, and chaseth away evil, even as light doth darkness;
and therefore the preventing of the springing up of the good,
is a cherishing and strengthening of the evil.
Besides, the same spirit, government, or power,
which persecuteth and keepeth down the good, under a pretence of its being evil,
cannot choose but also cherish and nurse up the evil, under a pretence of its being good.
For the same eye, tongue, and heart, that seeth, calleth,
and acknowledgeth that which is indeed good to be evil,
cannot choose but also mistake the evil and think it good.

[.numbered]
4+++.+++ _It draweth down the wrath of God upon people, powers, and governments,_
where such persecution is; where evil is cherished under a pretence of its being good,
and the good endeavored to be suppressed under a pretence of its being evil.
If men from their hearts do acknowledge the being of God, and his disposal of things;
then surely what is truly good in persons or nations is of him; and what is of him,
his eye is upon.
He beholdeth the plants which he hath planted in the earth,
and the plants which the envious one hath planted; and he cannot bless that place,
that people, those powers, that government, where his plants are crushed,
under a pretence of their not being his,
and where the evil nature and plants are cherished as if they were the good.

====

Therefore he that would not be an enemy to God, an enemy to goodness,
an enemy to himself, an enemy to mankind, and a friend and promoter of evil,
let him wait on the Lord, for the fear of his name and power to be written on his heart,
and for a meek, righteous frame of spirit, etc., that he may consider his steps,
and the reasonings of his mind, and not mistake evil for good, and good for evil,
and so persecute men for being and doing that,
which (might it have its course and progress) would make the world happy.

[.discourse-part]
Objection.
But will not this undermine magistracy, and interrupt its punishing of evil-doers,
if they should be thus tender and considerate?
For what man cannot pretend conscience for what he does?
And if the magistrate should hearken to every pretence of conscience,
the laws would soon be silent, government at a stand, and every one do what they list,
bringing in all manner of licentiousness and disobedience to authority,
under a pretence of conscience.

[.numbered-group]
====

[.numbered]
_Answer 1._ Conscience is of God;
and tenderness and conscientiousness towards him
is necessary to the receiving of his pure fear,
and towards the springing up and growth of all good in the heart.
The seed of good is tender;
and if it be not received into tender and well prepared earth, but into thorny, stony,
or highway ground, it cannot grow.
And it cannot reasonably be supposed to be the intent of God in appointing governments,
that ever their laws and authority should hurt that tenderness of conscience,
wherein his seeds of good are sown.

[.numbered]
2+++.+++ It is true; the corrupt nature of man, which is selfish, and seeketh covers for evil,
may also seek this cover to hide iniquity under, and may pretend conscience,
when there is no matter of conscience at all, but self-will and self-ends at bottom.

[.numbered]
3+++.+++ Notwithstanding this,
God would not have the true conscientiousness and tenderness in any of his crushed;
nor can it be done by any person, authority, or law,
without provoking God on the one hand, or without injury to such who are so dealt with,
viz: who are punished by man for the exercise of that conscientiousness which is of God,
and which he requireth, and is pleasing to him.

[.numbered]
4+++.+++ It were far better in itself, safer for governors,
more agreeable to equity and righteous government, and more pleasing to God and good men,
rather to suffer some, by their craft and false covers, to escape due punishment,
than to punish those who, by the goodness, innocency,
and righteousness which God hath planted in them, are exempted from punishment.
Yea, it were better and much safer to spare many evil men, than to punish one good man:
for mercy and sparing, even of offenders, is natural to that which is good;
but severity and punishments are unnatural and but for necessity`'s sake.
And as for that man, who, by his subtlety and deceit, thus escapes man`'s hand,
he will be no great gainer; for God, who is above all, will be sure to meet with him.
Yea, that magistrate, who spares some evil and evil-doers,
merely upon this account,--lest he should hurt that which is good,
the Lord will help and bless; whereas,
that power and government which willfully errs herein, the Lord may soon cut down;
and that which errs thus through mistake (it being a grievous
mistake to cut down the good instead of the evil),
the Lord, who loveth the good and hateth the evil, may easily be provoked against.

[.numbered]
5+++.+++ As government came from God; so the righteous execution of it depends upon God.
Every man needs God`'s help daily, else he may easily err in his course;
and governments and governors need God`'s help much more,
in the many intricacies and perplexities which they often meet with.
And God is nigh to them in their difficult cases,
who wait upon him for counsel and direction.
If the case be knotty, yet if God give wisdom, hath the magistrate cause to complain?
And will God not assist that magistrate, who in his fear waits on him,
and is not willing to spare the evil, and afraid to hurt the good?
If there were not so much consulting with man`'s wisdom and policy,
nor such laying of designs and intents at first, as spring from man, and not from God,
but a naked, upright waiting on him for instruction,
who can only guide the spirit of man aright, governments would not prove so difficult,
nor the success therein so dangerous.

====

[.old-style]
=== A Brief Account of That Stiffness, Resolvedness and Supposed Stubbornness, / Which by Many Is Objected Against the People Called Quakers

[.discourse-part]
Objection.
That the people called Quakers are an innocent and industrious people,
that they aim at good,
and might be serviceable and profitable to the nation in many respects;
this many believe concerning them,
and in their hearts wish that the powers would let them alone, and make a trial of them;
the which they might be the more inclined to do,
were it not for a certain stiffness which appears in them,
they being so glued to their principles and practices,
that they will not bend in the least,
nor so much as meet the magistrate one jot in any favor he would show unto them.
This is such a temper as no magistrate or governor can bear,
and therefore there is a necessity either of banishing
or suppressing them one way or other.

[.discourse-part]
Answer.
I freely confess,
that (looking upon them with man`'s eye) it may easily appear so to man,
who cannot see either whence that is, or what that is,
which is wrought in their hearts by God.
And how can I blame others for judging thus of them,
when I myself should be liable so to judge, if I did so look upon them?
But yet, if I had patience to hear them,
and to consider the thing in the fear of God (watching against that wisdom,
from which the knowledge of the things of God and the state of his people is hid),
I see also, that there is some ground may appear unto man,
to let him see that this is not such a stiffness and stubbornness of spirit as he judgeth,
but ariseth from, and necessarily accompanieth,
a true tenderness and conscientiousness towards God;
which to make the more manifest to such as are willing fairly to consider the thing,
and know the truth thereof, I shall thus demonstrate.

[.numbered-group]
====

[.numbered]
1+++.+++ Stubbornness, or such a kind of stiffness and resolvedness,
ariseth from the strength and corruption of the natural will and earthly wisdom.
The wisdom which is from above is gentle, easy to be entreated;
and the will which is created by God is mild and flexible,
and easy to be led by the least child, in the line of goodness.
And I can truly say this,
that I never in my whole course and conversation (who have
long been a spectator and uninterested person,
both as relating to the civil state and the various professions of religion,
till the power of truth and presence of God appearing
in this people drew my heart after them),
yea, I cannot but say, in the singleness of my heart, I never met with a more mild,
gentle, flexible-spirited people.
And he that can reach the ground of the thing, cannot but see it to be thus;
for he that is daily exercised in denying his will and wisdom;
he on whose back the Lord lays the cross, and crucifies him every day,
his self-will and self-wisdom,
with all the conceitedness and stiffness which arise therefrom,
must needs be much broken in him.

[.numbered]
2+++.+++ In the tenderness and pliableness to good, which God begets, there is,
and cannot but be, an unbendedness to evil.
Consider this, O ye that are wise!
In the birth which God begets in the heart; in the immortal seed of life,
which God hath sown, and causeth to spring up in his heritage,
there is a bowing to God at every appearance of good, accompanied with a tenderness,
gentleness, and good-will to man;
but it cannot bow to that which is evil in any man upon the face of the earth.
Read then this riddle, with a true understanding: the tender one cannot yield,
the flexible one cannot bow; but naturally standeth upright and straight towards God,
even in everything it hath learned of him, and which he requireth of it.
Thus in the apostles`' days, the Christians, though meek, though sweet,
though pliable to the Spirit of God, and to all good,
yet could not bow to so much as an appearance of evil anywhere,
but shun and avoid it everywhere.
And if it were not for this kind of stiffness and unbendedness,
the children of God could never be preserved in their
departure out of the world`'s spirit,
ways, worships, and practices; but would soon be ensnared and drawn back again,
by the enticements and subtleties of the worldly nature, either in themselves or others.

[.numbered]
3+++.+++ A stiffness then I grant, an unbendedness I grant; but not of the earthly,
not of the self-will, nor according to the earthly;
but such as ariseth from truth in the heart, and from tenderness of spirit towards God;
such as is begotten in his fear, preserved by his power,
and is necessary towards their preservation who are born of him,
and called by him out of the world.
And if those, who are apt and liable to misjudge of them,
did but see the sincere desire of their hearts not to offend man,
but to be subject to the utmost according to the will of God,
and knew what breathings there are in their hearts to God (in relation to the magistrate,
and when they appear before him), that they may be preserved in the pure fear,
and in righteousness and inoffensiveness,
and how they cannot but refuse to break any of God`'s commands,
because he is their Supreme Lord, and they dare not disobey him to please man,
or avoid their own sufferings from man: I say, if men did see this,
surely they would not call it stubbornness and self-willedness,
but a pure subjection and denial of the self-will in God`'s fear,
joined with a holy and humble boldness in his power.

[.numbered]
4+++.+++ Let it be equally considered, and it will soon be acknowledged,
That the least thing which God requires (the command being from so great a King,
upon whom the soul hath so great dependence, from whom it hath so great hopes,
and to whom universal obedience is so due in itself,
and so profitable to the creature) is exceeding weighty;
and it is impossible for the fear of him, and due tenderness towards his commands,
to be preserved, without a strict and close giving up the will to him,
and standing in his strength, strong and unbended against all temptations, provocations,
allurements,
and affrightments to the contrary (and how easily may men call
this stubbornness and stiffness!). But this they receive from God,
as well as the law of obedience and power to obey;
and this (which men call stubbornness) flows in upon them from him,
when they are in the sweetest and meekest frame of spirit, most ready to deny themselves,
and to yield up their own wills to whatsoever is good and righteous, and so of God.

[.numbered]
5+++.+++ The same thing which is offended at this unbendedness and resolvedness,
which is wrought and preserved in them by the fear of God (calling it,
by way of reproach, stiffness and stubbornness); I say,
the very same thing will commend that resolution and stiffness,
which is taken up in man`'s wisdom, and held in man`'s will.
Is it not good to weigh and consider things reasonably,
and then to choose and hold fast those principles which appear most reasonable?
What man, but will say it is?
And is it not good to obey and keep to that light which is higher than reason;
which comprehends reason, rectifying and preserving it,
making it profitable and serviceable to God who made it, to the vessel in which it is,
and to the rest of the creation?
But "`wisdom is justified of her children.`" He that
knows not the principle of the eternal light,
who is not born of it (much less by unfeigned obedience and subjection formed into it),
he cannot justify it in his paths; but he justifies the earthly wisdom and reason of man,
by its setting up _appearances of good,_ instead of _good,_
and would make all acknowledge and bow to them as _good;_
whereas that which is indeed acquainted with the good, living in the principle thereof,
cannot bow to the false appearance, but only to the truth itself.
When man`'s spirit and wisdom is wearied out of all its paths,
and he broken with the misery which will certainly overtake him therein;
at last the path of God will be welcome to him, and that principle which,
through the operation of God, is able to rectify him and make him happy.

====

There hath long been a peace and prosperity throughout the world in unrighteousness;
but the season is at length come for the breaking thereof,
and now there is not to be such a settled, false peace in unrighteousness any longer:
but tribulation, anguish, and destruction are coming upon the selfish and unjust spirit;
and he that refuseth the path of righteousness, must not know peace,
but be overtaken with the overflowing scourge, and swept into and shut up in the pit,
which hath long been digging for the wicked; Ps. 94:13.
and mark this thing following,
ye that would not find yourselves deceived of your souls hereafter,
nor of your outward peace and prosperity here; for it deeply concerns both.

The Spirit of the Lord once raised up a spiritual building,
which the spirit of the dragon overturned (as to its outward state,
though the gates of hell could not prevail against the being and inward
state of the true church) and instead thereof set up an earthly image,
agreeable to the earthly spirit in nations, but burdensome to that which is innocent,
pure, and spiritual.
The Lord God suffered this to stand all its allotted time,
and to have power to keep down the visibility of his truth and people;
but the Lord hath appointed a season to raise up his own building again,
and to throw down this image.
Now this I say to all men, in the fear and dread of the Almighty, stand still and mark,
if all the power of man be able to keep down God`'s
spiritual building which he is raising up;
or to keep up any part of the earthly image which he is throwing down.
The spirit of man (in various ways) hath shown what it judgeth best to have down,
and to have up; and hath put forth its strength to accomplish its will and counsel.
Stand still a while, and ye shall see,
that the spirit of the Lord will also show what he would have down,
and what he would have up; and he will also put forth his strength,
to accomplish his will and counsel.
It is the glory and honor of the Lord to carry on
his work in the midst of all the oppositions of man,
and against the full current of his strength and will.
This will make it to appear to be of God, and cause the glory of his name to shine.
Oh that men could fear the Lord, and bow before him, that he might be honored in them,
and see good to honor them in the carrying on of his work,
and so might not be forced (through their hearkening to the dark spirit,
and because of their ignorance of, and disobedience to,
the light of his Spirit) to get himself a name,
by overturning their strength and counsels, and causing his glory to shine over them!

We have been a poor, oppressed people,
from the day that the power of the Lord broke forth upon us, and his light sprang in us,
even until now: and now we are brought lower than ever,
and are in greater danger (to the eye of man) than ever.
Yet our confidence is still in our God; and this we are certain of,
that our principle (and practices therefrom) shall stand,
and man shall not be able to prevail against it;
for God will preserve his people in his life and power,
and the heads of all that wait upon him in his fear,
shall be lifted up above all the swellings of the waters; yea,
a song of praise is already prepared in the heart of God`'s chosen,
against the day of his deliverance.
We look not out, but give up our backs to the smiter,
as if their strokes were never to have an end; and yet we wait on our God,
and hope in him, as if deliverance were springing up every moment.
And oh that God would smite the spirit of enmity and darkness in men and powers!
And then there would be love, peace, pursuing after God and righteousness,
and no more _persecuting_ and _smiting_ of God`'s people for the uprightness of their hearts,
and for their obedience and faithfulness to him.
But be it known throughout all the earth, we are the Lord`'s,
and we must worship and serve him.
He hath redeemed us (even all of us in some measure,
who have known unity with his living truth) in soul, in body, and spirit;
and they must all be his in the first place, and cannot bow to man in the least,
against his will, or contrary to the law of his pure life,
and leadings of his Spirit in the heart.
Here is our standing, in the strength of our God, whatever become of us.
And here we stand in love and good-will to mankind; yea, to these present powers,
however they judge of us; and have been praying for them, and mourning over them,
while they have been smiting of us.
And when they have drawn the hand of the Lord upon themselves,
if the Lord shall please to open their eyes to see what we have been towards them,
and how fain we would have had them set footing there,
where they might have stood firm and have been preserved,
they will bewail as much their dealings with us, as what will befall themselves.
The Lord will manifest all things in his time, and give his truth a passage in the earth,
and his people a quiet habitation therein,
how black soever the face of things now appears, as relating to them.

Oh! how happy will the day be,
when the Lord shall have wrought down the selfish spirit in man,
and shall have raised up his own noble and equal principle!
Then shall righteousness spring up and spread abroad throughout the nations;
and the work of righteousness shall be peace,
and the effect of righteousness quietness and assurance forever.
