== Some Directions to the Panting Soul

[.heading-continuation-blurb]
Which hath long been travelling in the Letter, but hath not yet been acquainted with the Power,
nor hardly so much as entered into the Ministration of the endless Life
(which is the Ministration of the _Gospel),_ that it may feel the Spring,
and come to drink there of the living Waters.

[.section-date]
1661

[quote.section-epigraph, ,Matt. 11:28-30.]
____
"`Come unto me, all ye that labor, and are heavy laden, and I will give you rest.
Take my yoke upon you, and learn of me, for I am meek and lowly in heart,
and ye shall find rest unto your souls; for my yoke is easy,
and my burden is light.`"
____

Some sweet meditations sprang in my heart concerning this portion of scripture;
with breathings of spirit for, and rollings of bowels towards,
those "`that labor and are heavy laden,`" which I find drawings to communicate.

[.numbered-group]
====

[.numbered]
1+++.+++ _In the gospel_ (which is "`the power of God unto salvation`") _is the soul`'s rest._
It is the doctrine of the kingdom, wherein is life, joy, peace,
and everlasting rest to the soul in God.
The law had the shadow of the good things to come;
but under it was not the possession of the good things themselves,
but only a laboring after them, and a mourning and load because of the want of them:
but in the gospel is the substance, the enjoyment;
life and immortality are there brought to light,
and an entrance ministered into the everlasting kingdom, where they are felt, possessed,
and enjoyed.
"`The kingdom of heaven is at hand,`" saith the forerunner; It is come, saith the Messiah;
and in it there is righteousness, and peace, and joy in the pure spirit of life.

[.numbered]
2+++.+++ _It is the will of the King of saints that his
people should enjoy the rest and peace of his gospel._
He would not have them always laboring and heavy laden, as under the law;
but he would have their souls feel and enjoy the ease, the liberty, the sweetness,
the pure power and eternal rest of his life.
The Spirit of the Lord was upon him to preach glad tidings to the meek,
liberty to the captives, life to the dead,
the opening of the prison to the prisoner of hope, the binding-up of the brokenhearted,
the pouring in of oil upon the wounded:
and he would have the souls of his people enjoy that which he came to bring them.

[.numbered]
3+++.+++ _Christ hath plainly chalked out the path of his rest to every weary, panting soul,
which he that walketh in cannot miss of._
He hath _cast up, cast up;_ he hath _made the way plain_ in the gospel, so plain,
that the way-faring man, though a fool, yet keeping to the light of the gospel,
cannot err therein, or miss of the blessed rest thereof.
How is it?
Why "`come unto me;
take my yoke upon you and learn of me.`" He that walketh in this path cannot miss of it:
the rest is at the end of it, nay, the rest is in it:
"`he that believeth entereth into the rest.`" The true faith,
the faith which stands in the power,
and which is given to the birth which is born from above,
is the substance of the rest hoped for,
and there is a true taste and some enjoyment of it given to him that truly believeth.

[.numbered]
4+++.+++ _The rest was once felt and enjoyed, when the gospel was known in power._
Believers, in the first day of the gospel,
before the night overtook that glorious dispensation,
found "`peace and joy in believing;`" yea, they could rejoice in the Lord always.
They felt the power and the life, which stood over all the powers of darkness,
and brought good to them out of every affliction, and out of every temptation,
and out of every distress: so that they standing in the life,
and in the power which had quickened them, and was present with them,
they could "`count it all joy when they fell into manifold temptations,`"
knowing the advantage which would accrue to them thereby,
and possessing their souls in the pure patience, till God wrought it out for them.
They had an entrance ministered to them into the everlasting kingdom:
they received the kingdom which could not be shaken,
and in it had fellowship with the Father, and with the Son,
and in the eternal light the blood ran in their vessels, which cleansed them,
and kept them pure; and they sat down with Christ in the heavenly places,
even every one in the particular mansion which God had built in them by his Spirit.
The fear of the living God was put in their hearts;
the Spirit of the Lord was within them, and there his law was written,
and read in the Spirit,
and the treasures of his kingdom were opened by the
key of David in the hand of the Spirit,
and their souls had true satisfaction and rest in measure,
and were travelling on towards the fulness.

[.numbered]
5+++.+++ _There is no rest to the soul to be enjoyed in the gospel from under the yoke._
This stands eternally:
that which yokes down that which would be at ease and liberty out of the life,
that is the soul`'s true rest; there is no other: and under the yoke it is enjoyed,
and not otherwise; only when that which is to be yoked down is consumed and destroyed,
it is then no longer a yoke, but perfect liberty.
But the same thing which is the liberty is the yoke: and under the yoke, the sweetness,
the ease, the lightsomeness, the safe possession of the life is enjoyed.
Mark this therefore diligently: the yoke is not one thing, and the liberty another;
but one and the same.
The power of God, the life everlasting, the pure light, the divine nature,
is a yoke to the transgressing nature; but it is the ease, the pleasure, the rest,
the peace, the joy, the natural centre of that which is born of God.

====

Now to the soul that hath felt breathings towards the Lord formerly,
and in whom there are yet any true breathings left after his living presence,
and after the feeling of his eternal virtue in the heart, I have this to say:
Where art thou?
Art thou in thy soul`'s rest?
Dost thou feel the virtue and power of the gospel?
Dost thou feel the ease which comes from the living arm,
to the heart which is joined to it in the light of the gospel?
Is thy laboring for life in a good degree at an end?
And dost thou feel the life and power flowing in upon thee from the free fountain?
Is the load really taken off from thy back?
Dost thou find the captive redeemed and set free from the power of sin,
and the captivity broken,
and he which led thee captive from the life and from the eternal power,
now led captive by the life, and by the redeeming power, which is eternal?
Hast thou found this, or hast thou missed of it?
Let thine heart answer.
Ah! do not imagine and talk away the rest and salvation of thy soul.
The gospel state is a state of substance, a state of enjoying the life,
a state of feeling the presence and power of the Lord in his pure, holy Spirit,
a state of binding-up, a state of healing, a state of knowing the Lord,
and walking with him in the light of his own Spirit.
It begins in a sweet, powerful touch of life,
and there is a growth in the life (in the power, in the divine virtue, in the rest,
peace, and satisfaction of the soul in God) to be administered and waited for daily.
Now art thou here, in the living power, in the divine life, joined to the spring of life,
drawing water of life out of the well of life with joy?
Or art thou dry, dead, barren, sapless,
or at best but unsatisfiedly mourning after what thou wantest?

Well, ye that are dry, dead, barren,
as it were without the living God (that know not the shining of his sun,
nor the descending of his dews from on high on his tender plants, nor the care,
diligence, and circumspection of the husbandman over his husbandry),
oh! wait for the quicken-virtue,
for the visitations of the day-spring from on high!
that ye may be quickened again to God,
that ye may find his life visiting you, his Spirit breathing upon you,
that the seed of Jacob may be raised in you to travel out of this barren state,
even out of this land of darkness, and from under the shadow of death,
to the land where life lives and flourishes,
and daily distributeth plentiful nourishment and refreshment to all its offspring,
who are taught to wait for it, and to feed on it in the holy place,
out of the sight of the eye of the fleshly wisdom.

And ye who are still gasping after the living God,
on whom the breathings of life still abide;
who remain unsatisfied inwardly for want of the presence of the Lord,
and whose hearts still mourn and lament deeply after him,
oh! consider what is the matter, that ye have mourned so long, and sought so long,
and yet to this day are at a distance from the thing
ye have mourned for and sought after.

"`Strait is the gate, narrow is the way, that leadeth unto life,
and few there be that find it.`" The way of unbelief is broad, yea,
the way of belief is broad also.
It is easy for a man so to believe concerning Christ, or in Christ,
(as his heart may call it) as to miss of the nature of the true faith,
and of the sweet and blessed effects which accompany it.
It is easy likewise to miss the yoke, (to take up a wrong yoke, in the self-will,
self-wisdom,
self-interpretation of scriptures) or easy starting aside from the true yoke;
but it is hard coming under the yoke of the life, and hard abiding under it.
Again, it is easy mislearning; a man may so read, and so hear,
as that he may be always learning, and never come to the knowledge of the truth;
never come to the truth as it is received and held in Jesus;
but may so get and hold the knowledge of the truth,
as man in his wisdom may get and hold it from the letter.
And if a man thus miss the way, how can he attain the end?
If a man begin not in the true faith, in the living faith,
how can he attain the rest which the true faith alone leads to?
If a man miss of the yoke, or abide not constantly under the yoke,
how can he meet with the true ease and rest which is in it,
and which it alone can administer?
If a man learn not the truth aright of the true teacher,
how can he ever reap the effects of the true knowledge?
Ah, poor hearts! it is not enough to have breathings after God,
nor to be very diligent and industrious, either in outward ordinances,
or inward exercises of spirit; but the way of the gospel must be cast up by God,
and the soul led into it by him, and daily preserved by him,
and must walk in the path which is proper for it to walk in,
or it may mourn and cry all its days, and never meet with that enjoyment of God,
and satisfaction in God, which it waits for, and cries after.
It is one thing to mourn after a gospel-state,
but another thing to be brought into it by the power.
With my heart I own those that mourn after, and feel the want of, God, wherever they are;
but this I know certainly, that they can never come to the enjoyment of him,
but in that living path which the Scriptures testify of to be in him who is the life,
and which his Spirit is now found manifestly leading into.
Blessed be his name!

[.discourse-part]
Question.
But how may my poor soul, who have long mourned, and groaned,
and been sick of love after my beloved,
but could never attain to the satisfactory enjoyment of him, come to walk in his path,
that so I may meet with, and lie down in,
the power of life and salvation which the gospel holds forth to the true believer,
and which I have been long sensible of the deep want of?

[.discourse-part]
Answer.
Thou that wouldst enjoy thy beloved, and feel the rest of his gospel,
and walk in that path which leads thereto,
wait to learn of the Spirit these things following:

[.numbered-group]
====

[.numbered]
1+++.+++ Know what it is that is to walk in the path of life,
and indeed is alone capable of walking therein.
It is that which groans, and which mourns; that which is begotten of God in thee.
The path of life is for the seed of life.
The true knowledge of the way, with the walking in the way,
is reserved for God`'s child,--for God`'s traveller.
Therefore keep in the regeneration, keep in the birth: be no more than God hath made thee.
Give over thine own willing; give over thine own running;
give over thine own desiring to know or to be any thing,
and sink down to the seed which God sows in the heart, and let that grow in thee,
and be in thee, and breathe in thee, and act in thee,
and thou shalt find by sweet experience that the Lord knows that,
and loves and owns that, and will lead it to the inheritance of life,
which is his portion.
And as thou takest up the cross to thyself,
and sufferest that to overspread and become a yoke over thee, thou shalt become renewed,
and enjoy life, and the everlasting inheritance in that.

[.numbered]
2+++.+++ Know in what light it is to walk, which is in the light of the Spirit.
There the child is begotten (not in Satan`'s darkness,
or highest transformings into the likeness of light, which is but darkness;
nor in the light of man`'s wisdom, searching knowledge, or comprehension),
and there it walks;
in that light it fetcheth every step and motion towards the land of life;
therefore hold no knowledge out of the Spirit.
If any knowledge concerning the things of God be held out of the freshness of the Spirit,
it presently proves dead and unprofitable.
The spiritual Israel cannot travel without a spiritual light;
which light is eternal and incomprehensible, and cannot be held by man`'s spirit,
but shineth fresh in the renewed spirit every day,
and so is daily gathering it more and more inward into itself,
comprehending it in itself, and preserving it in its own purity, clearness,
and brightness.
Oh! this is it hath undone many, even catching at light from the Spirit,
transplanting the image of divine things into the earthly principle,
and there holding of them in the earthly part, growing wise by them there,
and making use of them from thence as man sees good,
and not seeing a necessity of depending on the Spirit for
fresh light and life every day to every spiritual motion.
Thus the traveller soon comes to lose the true path,
and instead thereof travels on in a road of his own wisdom`'s forming:
and so though he seems to himself to make a large progress,
yet makes no true progress at all, but is exceedingly run out aside in a by-way;
all which ground he must traverse back again,
ere he can come to the truth of his former state, or proceed in the true travel.

[.numbered]
3+++.+++ Know and keep to the power, which alone began any true work in the heart,
which alone can preserve it, and which alone can carry it on.
Christ was made a priest, _not after the law of a carnal commandment,
but after the power of an endless life:_
and every sacrificer under him (which every true
believer is) is so made by the same power.
The powers of darkness are continually at hand,
which nothing can stand its ground against (much less walk
on safely) without being in that power which is above them.
The first coming to Christ must be in the power of the Father`'s drawing:
and no believing afterwards is of the true nature,
nor will avail the soul in its progress and travel towards life, but what abides in,
and goeth forth in the same power.
So the taking up the yoke, and drawing in it, must be by the power of the new life;
and so must the disciple`'s learning be.
As the master teacheth in the power of the Spirit
the things which alone can be seen with the new eye,
heard with the new ear, and received into the new heart;
so the scholar must learn and receive his lessons of life in the same power.
Let any disciple of Christ be from under the shadow of the power,
believe out of the power, walk out of the power, act out of the power,
he is from that wherein his life stands, and wherein alone is his preservation;
and ah! how liable is he then to falls, bruises, snares, and temptations of the enemy.

[.numbered]
4+++.+++ Watch against the selfish wisdom, in every step of thy growth,
and in every spiritual motion, that that come not between thee and thy life;
that that deceive thee not with a likeness, a shadow,
making it appear more pleasing to the eye than the substance.
Every step of thy way it will be laying baits for thee;
and it is easy for deceit to enter thee at any time,
and for that wisdom to get up in thee under an appearance of spiritual wisdom,
unless the Lord tenderly and powerfully preserve thee: and if it prevail,
it will lead thee from the path of the true wisdom;
it will cozen thee with a false faith, instead of the true faith; with false praying,
instead of the breathings of the true child; with diligence and zeal in thy false way,
instead of the true zeal and diligence; yea, it will hurry thee on in the path of error,
shutting that eye in thee which should see,
and hardening thine heart against thy bosom friend.
And being thus deceived,
thou mayest be as zealous in thy age and generation against the truth,
as the Jews were in theirs: and as certainly as they put Christ to death,
and persecuted his apostles, though they cried up the former prophets, so certainly thou,
under this deceit,
canst not but act against the present dispensation and appearance of Christ`'s Spirit,
and would persecute either the prophets, apostles, or Christ himself,
were it their present day now so to appear as formerly they did.

[.numbered]
5+++.+++ Let nothing judge in thee (concerning thine own heart, or concerning others,
or concerning any way or truth of God) but only the begotten of God in the heart.
Let the light in which thou art begotten to God, and which shines upon his begotten,
be the only judge in thee, and then thou canst not err in judgment.
Be not hasty, be not forward in judgment; keep back to the life,
still waiting for the appearance and openings of the life.
A few steps fetched in the life and power of God are much
safer and sweeter than a hasty progress in the hasty,
forward spirit.

====

Indeed this is the true religion, to feel God beginning the work,
and to wait on him for his carrying it on.
The feeling of God`'s Spirit beginning somewhat in the heart,
the heart`'s waiting on him for more of his Spirit,
and walking on with him in his Spirit, as he pleaseth to quicken, lead, draw,
and strengthen; this is the spiritual and true religion:
and there is no duty or ordinance of the gospel out of the Spirit;
but it is easy crying up and observing the likeness of any of them out of the Spirit,
into which observance a strange spirit easily enters;
and then that which was of God in the heart soon withers,
and a contrary building is raised, and the state of the heart changed.
Oh! wait on the Lord, that he may give you to understand these things;
for the apostasy from God is very deep,
and more provoking among the Protestants than among the Papists, yea,
most of all provoking where it is most inward and spiritual.

[.discourse-part]
Question.
But how may I know and keep to the begotten of God,
and to the light and power of the Lord,
and keep down the fleshly wisdom and comprehension concerning the things of God?

[.discourse-part]
Answer.
When God begets life in the heart, there is a savor of it in thy vessel, and a secret,
living warmth and virtue, which the heart in some measure feels, whereby it is known.
Lie low in the fear of the Most High, that this leaven may grow and increase in thee.
This is the leaven of the kingdom; this is it which must change thy heart and nature,
and make thy vessel (which perhaps hath been long and much
corrupted) fit to receive the treasure of the kingdom.
Now while the savor is upon thee, while the virtue of the life is fresh in thee,
thou findest some strength towards God,
with some little taste and discerning of the things of his kingdom.
Know thy weakness, and go not beyond the measure;
but in what thou hast received bow before the fulness, worship God in that,
and be patient in what he exercises thee withal, waiting for more from him.
And when the night comes upon thee, and thou perhaps art at a loss,
missing the savor and presence of the life, and not knowing how to come by it again,
be patient and still, and thou wilt find breathings after a fresh visitation, and a meek,
humble, broken spirit before the Lord.
Thou wilt see thou canst do nothing to recover his presence again; nay,
thou canst not so much as wait for him, or breathe after him, without his help;
but he is nigh to the poor, nigh to the broken, nigh to the distressed,
nigh to the helpless.
Oh! do not, with thy fleshly cries and roarings,
think to awaken thy beloved before his season; but in the night of distress,
feel after somewhat which may quiet and stay thy
heart till the next springing of the day.
The sun will arise, which will scatter the clouds;
and he is near thee who will give thee to hope that thou shalt yet see God,
and find again the quickenings and leadings of his Spirit.
And in the day of his power thou wilt find strength to walk with him; yea,
in the day of thy weakness his grace will be sufficient for thee;
and he will nurture thee up in his life by his pure Spirit,
causing thee to grow under his shadow; and he will be teaching thee to live,
and to speak, and to move and act from the principle,
and within the compass of his light and life eternal.
Only be not wise to catch the notion of things into the earthly part,
where the moth can corrupt, and where the thief can break through and steal;
but know the divine treasury,
where all the things of life are treasured up by the Spirit,
and handed forth to the living child with fresh life, according to its need of them.
And thus thy heart being kept close to God,
and thy spiritual senses continually exercised about the things of God,
it will be easy to thee to know the shepherd`'s voice,
and to distinguish the sound of the Spirit in thine own heart:
and that which tries spirits and motions in thine own heart,
will also give thee the discerning of truth and error abroad, even of the Spirit of God,
and the spirit of Satan in others; so that thou wilt be able to try not only words,
but spirits, becoming acquainted with the anointing, which savors all things,
and will give thee to judge, not by the words, but by the power:
for thou thyself being in the power, in the anointing, in the savor,
it will become natural to thee to feel, to taste,
to know and unite with what is one with thy life,
what comes from the same spirit in others, and to turn from the contrary.
And thus thy life, thy growth, thy path will be sweet, safe, clear, certain,
demonstrative in the Spirit and past all reasonings of flesh and blood,
either in thyself or others.
The beginning of life eternal is in a higher principle than man can come at.
Man`'s wisdom and knowledge of the things of God is but brutish before it.
As thou comest into that principle, abidest and growest in that principle,
thou art beyond man`'s judgment, and art able to judge man,
and fathom his whole course as with a span;
but art quite out of his reach in the lowest of thy motions, thoughts, or actions;
I mean such as flow from, and are comprehended in, the life.

[.signed-section-signature]
Isaac Penington the Younger
