== Concerning the Worship of the Living God, / Which He Teacheth Israel, His People.

[.heading-continuation-blurb]
Who know him to be the only true God,
and the worship which he teacheth them,
to be the only true, spiritual worship.

[.heading-continuation-blurb]
With some questions and answers relating to conversion,
and to tenderness of conscience.

BECAUSE the worship of God is a weighty thing,
and there have been (and still are) so many errors about it,
and the errors therein are of such dangerous consequence,
both in relation to men`'s eternal estate hereafter, and to their right constitution,
peace, and welfare in this world;
and because I have had deep experience concerning the worship of God from a child,
having travelled in spirit with my God for the right knowledge thereof,
and in singleness of heart giving up unto him,
according as he hath taught and led my poor, needy, depending soul; I say,
therefore is it on my heart, to answer some few questions concerning the worship of God,
for the service of such as both desire and need instruction therein.

[.discourse-part]
Question.
1+++.+++ Who is the worshipper, the acceptable worshipper in the sight of God?
Or whom hath God chosen out, to hold forth his worship in the sight of the world,
since he rejected the Jews with their worship?

That God hath appointed a chosen people to worship him, that I presuppose; though,
if need were, the proof thereof might be ready at hand.
It is not every man that would thrust himself upon the Lord, whom the Lord will accept;
but "`the Father seeketh such to worship him,`" John
4:23. There is a capacity to be found in man,
to make him a worshipper; even such a capacity,
as may enable him to perform that worship which God requireth of him.
Now this is the thing to be inquired into; What this capacity is,
and who are the persons that are found in this capacity?

[.discourse-part]
Answer.
The worshipper in the times of the gospel, the worshipper under the New Testament,
is "`he that is born of God.`" He that is drawn out of the dark spirit of this world,
and formed anew in the light of God`'s Spirit.
He that is a Jew inward,
he that hath the uncircumcision of his heart cut off by the power of God;
this is the worshipper,
whom "`the Father seeks to worship him.`" This is the sort of worshippers God chose,
when he cast off the Jews.
God did not choose any one nation, or many nations,
instead of that one which he cast off;
but he sent his apostles and ministers among all nations, to gather a spiritual seed,
instead of the natural.
And these alone are capable of setting up, and holding forth,
his spiritual worship unto the world, and to provoke them to wait for, and press towards,
the capacity of coming into the same spiritual worship with them.

[.discourse-part]
Question.
2+++.+++ Which is the place of worship?

[.discourse-part]
Answer.
The only place of worship in the New-Testament,
is where the spiritual worshippers meet together.
The place is spiritual.
As the worship is spiritual, so is the place where it is to be offered.
It hath a spiritual consideration; not outward, as under the law.
It is to be offered in the Spirit; that is the place.
Where doth my soul offer its private worship to God?
Hath it relation to any outward place?
Or is it in the building which God hath reared up in my heart by his Spirit?
Which building stands in, and is comprehended in, his Spirit.
And I can offer his public worship in no other place,
but in a building of the same nature, in a house built of more of the same stones.
This then is the way of worshipping in the true Light;
divers living stones meeting together, every one retiring in spirit into the living name,
into the power which begat them, they all meet in one and the same place,
in one and the same power, in one and the same fountain of Life;
and here they bow down to the Father of life, offering up living sacrifices to him,
and receiving the bread and water of life from him,
and feeding in the rich pastures of his infinite fulness.
In the holy city, in the living temple which is built by God,
of the stone which all other builders refuse,
is the place of the worship of the living God,
where the true Jews meet to offer up their spirits, souls, and bodies,
a living sacrifice to the Father of life;
and where they meet with such a glorious presence and power of the Father,
as none but the true Jews were ever acquainted with.

[.discourse-part]
Question.
3+++.+++ What is the worship, or what are the sacrifices,
which the true worshippers offer up to God in this holy place?

[.discourse-part]
Answer.
The gifts of his Spirit.
These they offer up, and nothing else.
The breathings which the Father gives into the heart of the child,
they are breathed back unto him in the same spirit of life; in the living sense,
in the quickening power.
Nothing of man`'s wisdom, nothing of man`'s invention, nothing according to man`'s will,
nothing that would please the flesh, or seem glorious in its eye, is offered up here;
but the exhortations, or directions, or reproofs that spring up in God`'s light,
in God`'s wisdom, they are given forth in the leadings,
and by the guidance of his Spirit, and they reach to the hearts of those,
to whom he pleaseth to direct them.
And this is the ground of such meltings, and breakings,
and convictions of soul (and such-like inward operations)
as are frequently found in such assemblies.
For the living God is there,
and the dread of his power overspreads the hearts of such
as are gathered into and assembled in his name;
and the life springs in the earthen vessels,
and the savor is precious to all that have their spiritual senses.

[.discourse-part]
Question.
4+++.+++ What is the season of offering up these gifts?

[.discourse-part]
Answer.
The seasons of the true worship stand in the will of God.
They are gifts, and the time of them stands in the will of the Giver.
Prayer is a gift.
A man cannot pray when he will; but he is to watch and to wait,
when the Father will kindle in him living breathings towards himself.
So the word of God (whether of exhortation or instruction) is a gift,
which is to be waited for,
and then to be given forth in the life and strength
of that Spirit which caused it to spring.
Indeed it is a hard matter either to speak the word of the Lord,
or to hear the word of the Lord.
A man may easily speak what he invents,
and another may easily hear and judge of such words; but to speak the word of life,
requires the tongue of the learned in the language of God`'s Spirit;
and to hear the word of life, requires a quickened ear:
and to know the times and seasons of the spirit,
required both being begotten of the Spirit, and being acquainted with it.

[.discourse-part]
Question.
5+++.+++ Was this the worship of the former Christians in the apostles`' days?

[.discourse-part]
Answer.
Search the Scriptures.
Were they not come to the New Jerusalem?
And where did they offer their sacrifices?
Did they offer them in the Old Jerusalem, or at Samaria,
or the mountain where the fathers worshipped?
Or did they not rather offer them at the Mount Zion, to which they were come;
where the male of the flock (even the Lamb without spot) is known,
and the blood of sprinkling felt? Heb. 12:22-24.
and 1 Pet. 2:5. Oh! read, read, in the life of God,
the nature of the things themselves; and do not feed upon your own imaginations,
or the imaginations of any other men concerning them.
Sweet is our God; his living presence is exceedingly nourishing to the soul;
precious is his power felt in the heart;
it is no less than life eternal to worship him in his Spirit.
Oh! let not the enemy of the soul cheat your souls
any longer of the precious things of his kingdom,
with husky and dry food instead thereof, which only gratifieth the earthly part,
but nourisheth not the immortal life.

[.discourse-part]
Question.
6 How came the worship of God to be transformed and changed so from the living power,
into such dead, formal ways as generally worshippers in the world are found in?

[.discourse-part]
Answer.
The enemy hath done this, by God`'s permission.
The Lord was pleased to suffer him thus far to prevail against the truth;
even to get into the form of it, and there to beget men into the form,
and then deny and turn against the power.
And this is the way of antichrist in kingdoms and nations,
even to set up a formal way of worship, and by it to fight against the true power.

[.discourse-part]
Question.
7+++.+++ How long hath this been done, and how long is it yet to last?

[.discourse-part]
Answer.
From antichrist`'s beginning, all the time of his reign, until his overthrow.
The formal way of religion will never be overturned,
nor the power of religion find place in the earth,
but there will be still countenancing of formal ways of worship,
and turning head against the power and life of the Spirit,
until antichrist`'s time come to an end,
and the Lord consume him by the Spirit of his mouth,
and destroy him by the brightness of his coming.

[.discourse-part]
Question.
8+++.+++ When shall this be?

[.discourse-part]
Answer.
The Lord is about this work.
He hath already raised up that which hath not been raised up for many generations;
and the Lord hath sorely smote down the spirit of antichrist in many hearts already;
and he is fetching a great and universal blow at him; at which stroke,
when it cometh from the throne of God, the nations shall tremble before him;
and it will be as honorable to wait for the movings of his Spirit,
and to worship him alone therein, as now it is reproachful.

[.old-style]
=== Some Questions and Answers Relating to Conversion / And to Tenderness of Conscience

[.discourse-part]
Question.
WHAT is the way of conversion?

[.discourse-part]
Answer.
To turn men from darkness unto light, and from the power of Satan unto God.

[.discourse-part]
Question.
When is a man converted?

[.discourse-part]
Answer.
When he is gathered into the light, and into the power,
out of the darkness of sin and dominions of Satan.

[.discourse-part]
Question.
How is man converted?

[.discourse-part]
Answer.
By the operation of the light and power of God upon his conscience.

[.discourse-part]
Question.
In what condition is the conscience before God works upon it?

[.discourse-part]
Answer.
Hard and corrupt; hardened by selfish reasonings and dark imaginations,
against the convictions of the light and operations of the power of God,
and corrupted with the sin and iniquity that dwell in it.

[.discourse-part]
Question.
What doth God make it in his working upon it?

[.discourse-part]
Answer.
Gentle and tender, fit to receive the impressions of his Spirit.
By the influence and power of his Spirit on the conscience,
he openeth the ear to hearken to his voice,
and prepareth the heart to follow him in his leadings.

[.discourse-part]
Question.
How doth God carry on his work in the converted soul?

[.discourse-part]
Answer.
By keeping it low and tender,
out of the self-wisdom and hardening reasonings of the human understanding:
by this means he keeps it pliable to the light and power of his Spirit.

[.discourse-part]
Question.
Is only the tender conscience then fit to be wrought upon by God?

[.discourse-part]
Answer.
Yea, indeed, that alone.
The heart that is hard is inconsiderate of the voice of God,
and stiff and stubborn against it; having ever at hand some wisdom or will of the flesh,
to withstand the voice and leadings of God by.

[.discourse-part]
Question.
Who is it that preserves the conscience tender?

[.discourse-part]
Answer.
The Lord of the conscience.
He who made it knoweth the proper temper of it;
and his light and power is alone able to preserve
it in that tenderness which he formed it in.

[.discourse-part]
Question.
What is it that hardens the conscience?

[.discourse-part]
Answer.
The wisdom of the flesh.
Man, having gained a wisdom out of the light of God, by the imaginations, reasonings,
and strength thereof, hardens himself against God.

[.discourse-part]
Question.
What is most necessary for a man to be vigilant in,
that desires to have the work of conversion to go on in his heart?

[.discourse-part]
Answer.
To be careful to turn from and avoid the reasonings of man`'s wisdom,
and to have his eye and ear open to the light and voice of God`'s Spirit,
that his conscience may be kept upright and clear before the Lord.

[.discourse-part]
Question.
What stains the conscience?

[.discourse-part]
Answer.
Any disobedience to God`'s Spirit, any hearkening to, or following the voice of,
a strange spirit.
This lets in the darkness, which defiles, even as the light cleanses.

[.discourse-part]
Question.
Is a man then to expect such a thing as the leadings of God`'s Spirit in his conscience?

[.discourse-part]
Answer.
A man cannot inherit the kingdom of God, but he must be born again,
even "`born of the Spirit.`" So saith the Scripture,
and so saith the experience of every one who feels the new birth.
And when he is born of the Spirit, he is to abide with him,
and learn the law of the new life, and receive power from him daily;
or the spirit of darkness will soon get ground upon him,
and by degrees be recovering him back again into his dominions.

[.discourse-part]
Question.
Surely if it be thus, hard is the way of religion,
and few there be who are found in the truth of it.

[.discourse-part]
Answer.
The way of religion is hard indeed, and wholly contrary both to man`'s wisdom and will;
insomuch as he cannot enter into it, nor walk therein, but as they are cut down.
He that will be a disciple of Christ, and follow the leadings of his Spirit,
must deny himself wholly, and become another`'s,
and be content to stand or fall to his own Master.
He cannot please men, no not in his worshipping of God;
but must turn from that which is glorious in their eyes,
and sacrifice that which is to them an abomination.
So that he must look to be condemned by men, who will be approved in the sight of God.

[.discourse-part]
Question.
Why hath God put his people upon such hardship,
as still (in all ages and generations) to walk in a way contrary to the world,
and still to be the objects of its hatred, scorn, and persecution?

[.discourse-part]
Answer.
How can it be otherwise, he begetting them in a Spirit contrary to the world,
and which testifieth against the world, showing that the deeds thereof are evil?
How can the spirit of the world but still turn against such, and hate, and persecute them?

[.discourse-part]
Question.
How long shall it be thus?

[.discourse-part]
Answer.
Till truth be raised by the power of God into dominion
over the spirit and power of darkness.
The Spirit of life now suffers under the burden of man`'s corruptions; in love to them,
striving to save them therefrom.
There is somewhat in every sinner that at seasons groans under the weight of his sins,
and in some proportion strives against the burden thereof.
This shall not always lie underneath;
but in the day of the Lord rise over the transgressor:
and in that day shall Israel be glorious with his God, and receive praise of him,
and be eased of all that hath oppressed him.

[.discourse-part]
Question.
Is there such a day to be?

[.discourse-part]
Answer.
The Scriptures testify of such a day,
wherein the Lord "`alone shall be exalted,`" and "`wherein he will take away
the rebuke of his people from off all the earth,`" and bring down "`all
that is high and lifted up`" above the fear and Spirit of the Lord:
and in this our age the Lord hath chosen many messengers to run up and down,
and proclaim this day.
And as sure as the Lord liveth, what he hath spoken shall come to pass,
and not a tittle of it fall to the ground.
God did not make man for him to serve his own lusts,
nor his creation to serve the lusts of man;
but he made man to fear before and serve his Creator;
and he made the creatures to be ordered by man in
the fear and wisdom of God to the glory of God.
The spirit of God now groaneth under man`'s iniquity;
the spirits of his people mourn and sigh also; yea,
and the very creatures groan under the bondage of corruption;
and the God of bowels heareth their cry; and a day,
even a mighty day of redemption and deliverance is determined,
wherein the spirit of the world shall be sunk down, with all its weight of wickedness,
and the Spirit of life and righteousness rise in its glory.

Amen, hallelujah! everlasting praises to the Omnipotent One, who was, and is,
and is a coming; who hath reigned, doth reign, and will reign,
over all the powers of darkness, in the pure power and glory of his life forevermore.
Let all the lambs skip for joy; let all the stars of the morning shout:
for the darkness vanisheth, and is passing away,
and the light of life shall cover the earth, as the waters cover the sea.
Amen, hallelujah!

Happy is the eye that seeth this, and the heart that prepareth for it,
overlooking all that stands between.
This is the hope of Israel, and the expectation of all that wait for the Lord,
which he is hastening upon the earth.

ISAAC PENINGTON
