[#jews-natural, short="Questions and Answers for the Jews Natural"]
== Some Questions and Answers+++<br />+++For the Opening of the Eyes of the Jews Natural / That they may see the hope of Israel, which hath so long been hid from them.

[.heading-continuation-blurb]
With some questions and answers for the direction, comfort, help,
and furtherance of God`'s spiritual Israel,
in their travels in spirit from spiritual Egypt through the spiritual wilderness,
to spiritual Canaan;

[.heading-continuation-blurb]
Which is the land where the redeemed soul flourisheth in the life,
walking with God, and worshipping him in spirit and truth.

[.section-author]
By _Isaac Penington,_ the Younger

[.section-date]
1661

=== Preface

Several things hath the life, begotten by the eternal virtue,
breathed in me towards my Father for, in relation both to myself and others,
from my childhood.
As touching myself; first, that I might be a vessel for him;
that I might be freed from the bondage of corruption,
and brought forth in the image of his life.
Secondly, that I might be filled with his life;
that I might be satisfied in the presence, and with the fulness of the spring of my life;
even that I might have enough of my God in my heart continually.
Thirdly, that he would, of his own mere goodness, both preserve the vessel,
and dwell in it forever; that so my tenure and possession of him, and fitness for him,
might be of his grace, of his love, of his good-will, of his own nature,
depending wholly and altogether on him,
and not at all on any thing that can be expected from the creaturehood in its pure state.
And likewise, that if he please to use me in any service, it might be of him,
and for him, and to him: that he would bring me so low in myself,
that I might not be able to detain any of his glory and virtue from him;
but the meanness of the vessel might still so appear to me,
and also be so sensibly discerned and acknowledged by all other eyes also,
that the excellency of the power and of the glory
might run back entirely into his pure bosom.

Besides these, there have been vehement desires in me concerning others also.
First, towards mankind in general,
that they might have an exceeding merciful and powerful day of visitation,
even that the whole earth might be touched with the power of life,
and drawn out of the darkness.
Oh! how hath my soul breathed for lost mankind! and how hath my spirit travailed,
with unutterable pangs and earnestness, for unheard-of, unthought-of,
and altogether unexpected mercy and good-will towards the sons of men in general.
Secondly, towards my brethren in spirit,
that they might know the day of redemption and power in Spirit,
and not always lie grovelling on the earth,
and groaning and mourning because of the lusts and corruptions,
but might know deliverance in power, and might sing the song of Moses,
and the song of the Lamb, because of their feeling victory over Pharaoh and the dragon;
and might serve and worship the living God in Spirit and truth,
without fear of interruption and captivity from the enemy any more.
Thirdly, towards the Jews after the flesh, that their iniquity might be blotted out,
their wound healed, the pure eye opened in them, and the pure glory revealed to them;
that they might know the Shepherd of Israel in Spirit, the spiritual tents of Jacob,
the beauty of the footsteps of the spiritual flock,
and might travel out of their darkness, earthliness, and literal knowledge,
into the land of pure life, rest, and peace, and fresh joy in the living God,
whereof their land of Canaan, with all the good things thereof, was but a shadow,
and might be anointed with the fresh oil of the salvation of the Messiah,
and might become, indeed, an holy nation; yea, a kingdom of priests,
to offer up spiritual sacrifices on God`'s spiritual altar.

My soul still breatheth to the Lord, and waiteth on him for all these things;
and as he draweth my spirit forth,
so am I ready in spirit to be serviceable unto him therein.
These present drawings and openings of my life, in the Questions and Answers following,
are both towards the Jews in the flesh, and also the Jews in Spirit,
that they may meet in One, even in the one path and pasture of life,
where there is one Shepherd, one seed, one flock, one Spirit, one beginning,
one progress, one end, in one and the same circle of life.
The Lord my God take it into his own hand, dispose of it for good,
manage and bless it according to his pleasure!

I+++.+++ P.

[.old-style]
=== Some Questions and Answers / For the Opening of the Eyes of the Jews Natural

[.discourse-part]
Question.
What was the rise of that people the Jews?

[.discourse-part]
Answer.
They came of Abraham after the flesh, who was God`'s friend,
whom God took from his father`'s house,
and from his native country (where he was worshipping and
serving idols) to be the stock and pattern of the faithful;
both of the Jews according to the flesh, and of the Jews in spirit.
Of this root, of this stock, came this people according to the flesh,
who were a holy nation, a circumcised people, a sanctified people outwardly;
and (as long as their day lasted) were the beloved of God, the pitied, the pardoned,
the redeemed ones, even until the shadows were finished,
and the season came for the substance to appear and be set up in the world;
whereof they had the first offer also,
and out of whom was the first gathering for the spiritual building.
But, they generally hardening their hearts,
and cleaving to the wisdom and knowledge which their wise ones had taught them,
(from their misunderstanding the letter of the Scriptures) missed of the Spirit,
rebelled against the redeeming power, and so lost their share in the inward glory,
and by God`'s righteous hand were cut off from their outward also, their day being spent,
and the blood, not only of the prophets, but of the Son and heir himself also,
required at their hands.

[.discourse-part]
Question. How came this people to be the chosen people at first, and so long to continue such?

[.discourse-part]
Answer. It was not for their righteousness, not for their loveliness,
or pliableness to God above other people;
but because it pleased the Lord freely to love them,
and to pitch upon them for the people of his choice after the flesh,
in the free covenant which he made with Abraham.
"`The earth is the Lord`'s with the fulness thereof;`" and he may
choose whom he will to fill with his inward and spiritual glory,
(even with the manifestations of his pure love, life,
and presence) and he may also choose whom he will to make outwardly or typically beloved,
great, and glorious.
He chose Abraham freely, he gave to Abraham a heart to follow him,
he gave him the faith and obedience which made him accepted with him;
and he chose his seed after the Spirit to be his eternal heir,
and his seed after the flesh to be his temporary heir.
Thus of Isaac in Spirit, came the children of the promise in Spirit;
and of Isaac after the flesh, came the seed of promise after the flesh.
Sarah after the flesh bare one of these:
the Sarah represented by her (or the free woman which is from above) bare the other.
And of Isaac comes Jacob, worm Jacob, who serves for his wife;
who flies from the face of Esau, yet afterwards finds favor in his eyes.
From this worm do the twelve patriarchs branch forth,
who were the heads of the tribes of Israel.
Thus hath it been with that nation according to the letter; and thus it hath also been,
and still is, inwardly in Spirit; as the Israel of God, the Jews in Spirit,
who are learned in the law of the Spirit of life, can very well read.
Thus outwardly Israel was God`'s child, Ephraim his dear, his beloved, his pleasant son;
Judah his praise, whom his heart was towards,
and to whom he stretched forth his arm of salvation all the day long.
"`In all their afflictions he was afflicted, and the angel of his presence saved them;
and he said, Surely they are my people, children that will not lie;
so he became their Saviour.`" Thus it was with them,
till the day of Israel after the flesh expired,
and the day of Israel in Spirit was to succeed in the sight of the world.

[.discourse-part]
Question. What was the end for which God chose that people?

[.discourse-part]
Answer. It was to be a vessel for him to form,
to try and experiment what his love could bring them to,
and bring forth in them that way of manifestation and operation.
This God opens to Jeremiah concerning them,
bidding him go down to the house of the potter; where, in a parable,
they might read their own state, and what they were to expect from God,
even to be formed by God unto the utmost, until he had made a perfect trial of them,
and then to be broken and laid aside,
as a vessel that could never be fitted for the Master`'s
use in this way of dispensation. Jer. 18:4.
On the Lord`'s part there was no defect towards his child, his spouse,
his vineyard, his garden of pleasant plants (as this people was in that dispensation);
for he was still a Father to them, faithful in covenant, tender in bowels,
abundant in lovingkindness and mercies: yea,
what could be expected from the Lord towards a people, according to that dispensation,
which the Lord failed in?
But they were still faithless, continually breaking covenant,
erring from his dear and tender love,
and drawing down the strokes of his wrath upon them: forsaking the guide of their youth,
forgetting the love of their espousals; continually starting aside from the right state,
wherein God pleased at first to set them,
or at any time afterwards in any measure to reduce them.

[.discourse-part]
Question. How did God exercise and try them to the utmost,
even till at length it was plainly manifest,
that there was no firm keeping a people to him by virtue of that dispensation;
but he must necessarily cut them off, choose another people, and take another course;
if he would have a people for his heart to love and delight in,
and for them to enjoy and possess him?

[.discourse-part]
Answer. He tried them several ways, and in several states and conditions; as, First,
In a state of captivity in the land Egypt.
Secondly, In a state of straits and continual dependence upon God, even for necessaries,
in the wilderness.
Thirdly, In a state of enlargedness in the land of Canaan,
which flowed with plentiful provisions for the outward man (which were
also shadows and instructions concerning the inward blessedness).
Fourthly, In often captivities.
Fifthly, In returns to their land again, with settlement and peace,
and many blessings therein.

[.discourse-part]
Question. How did God try them in Egypt?

[.discourse-part]
Answer. First, With sore bondage and oppression from Pharaoh and the Egyptians.
Secondly, With giving them the feeling of their state, the sense of their bondage,
and causing them to cry unto the Lord for deliverance.
Thirdly, In raising up a deliverer,
and giving them a sign of the deliverance by the hand of the deliverer,
in his smiting of an Egyptian, and saving a Hebrew.
Fourthly, In sending the deliverer to them, with promises of deliverance,
and with signs and symptoms of the delivering power.
Fifthly, In pardoning their unbelief and rebellions against him in Egypt,
and showing many signs and wonders for them in that land,
till at length he had brought them forth by his mighty, outstretched arm,
even against the will and mind of Pharaoh and their task-masters.

[.discourse-part]
Question. How did God find them in Egypt upon this trial?

[.discourse-part]
Answer. Very unbelieving, very stubborn, misinterpreting his sign of deliverance,
reasoning against his promise, because it came not so soon,
and after the manner they expected.
When he lifted up his hand to them to redeem them from under Pharaoh,
to bring them forth out of the land of bondage, to the good land he had espied for them,
and bid them forsake the idolatrous worships of Egypt,
and not defile themselves any longer therewith;
because he was now to become the Lord their God, and to appear in his power for them;
yet they would not.
Ezek. 20:5, etc.
When Moses would have reconciled a Hebrew to his brother he would not hear him;
but upbraided him for slaying the Egyptian, not waiting on God to understand the figure,
but misinterpreting and abusing it in the fleshly mind.
When the deliverance succeeded not according to their expectations,
they murmured against Moses and Aaron; and when God sent them again with a fresh promise,
they would not mind it.
Yet God bare with all this in them, and did not cast them off, but assuaged his wrath,
and stirred up his love to make a further trial of them.

[.discourse-part]
Question. How did God try them in the wilderness?

[.discourse-part]
Answer. By many temptations, signs, and wonders;
by powerful appearances for them against their enemies;
by bringing them into many straits;
by unexpected and impossible supplies (I mean impossible
to the sight or expectation of the outward eye);
as with bread from heaven, multitudes of quails, water from the rock,
keeping their clothes and shoes from wearing out and decaying.
Likewise he gave a holy and righteous law to inform their minds in equity and righteousness;
directing them in a holy way of walking with God, and one towards another,
and chalking out unto them an acceptable path of worship;
and this law was delivered in great majesty, dread, and terror,
to cause a deep impression thereof upon their minds.

[.discourse-part]
Question. How did God find them in the wilderness?

[.discourse-part]
Answer. Full of discontent; full of murmuring; full of self-will;
full of doubts and questionings concerning God`'s power.
They did not wait on him, who had delivered them out of the hand of Pharaoh,
and from under the Egyptian task-masters; but they murmured against him.
They did not wait for food or water when they wanted, but distrusted and complained;
repining at Moses and Aaron,
and sometimes talking of making a captain to lead them backward.
Neither were they content with the provision which
God allotted them (that was mean in their eyes),
but they would have flesh.
Though the Manna (the light bread as they esteemed it) of God`'s choice,
and with God`'s blessing, had been far better for them, than the flesh,
with his curse upon that lust which asked it, and would not be content without it.
Again they would not go on towards Canaan, or fight when God would have them,
and when his strength would have gone along with them; but when he forbade them,
of their own will, and trusting to their own strength, they would go on and fight.
It is a sad record which Moses,
their tender shepherd (who with the eye of true light had faithfully observed them),
left concerning them, Duet. 9:24. "`You have been rebellious against the Lord,
from the day that I knew you.`"

[.discourse-part]
Question. How did God deal with them in reference to the land of Canaan?

[.discourse-part]
Answer. First, He prepared them for it.
Secondly, He dispossessed their enemies, and placed them in it,
giving them an inheritance according to their own will.
Thirdly, He poured down blessings upon them therein.

[.discourse-part]
Question. How did God prepare them for the good land?

[.discourse-part]
Answer. First, By many afflictions and exercises in the wilderness,
wherein he judged and wore out the rebellious generation, who were consumed with dying,
and raised up their children in the awe and dread of his mighty power.
Secondly, By giving them a righteous law to walk by in every respect,
that they might not be to seek how to please God, or how to walk one towards another,
or towards the heathen among them, or round about them;
but in everything might be rightly instructed.
Thirdly, By warning them of their own proneness to err from God,
and of the danger thereof, both in relation to the loss of mercies,
and drawing down of judgments;
that they might watch against the erring nature and
transgressing spirit in their hearts.--Fourthly,
By appointing a way of sacrifice and mediation, whereby God might be atoned,
either for particular persons, or for the land in general.
Fifthly, By directing them to a principle as near to them,
and more strong than the unrighteous principle;
whereby they might be preserved in the obedience of the law,
and from out of the reach of the curse.

[.discourse-part]
Question. How did God find them in their own land?

[.discourse-part]
Answer. That generation, which was thus prepared, thus taught, thus directed,
walked sweetly with the Lord, and was a precious savor in his nostrils;
but soon after the evil thing sprang up again in the generations following,
and they did quickly corrupt themselves, departing from the Lord,
and running a whoring after their own hearts`' lusts.
Judg. 2:7, etc.

[.discourse-part]
Question. How did God deal with them then?

[.discourse-part]
Answer. He brought them judgment upon judgment, still weightier and weightier upon them,
according as their need required, exercising lovingkindness and mercy towards them,
as much as possibly their estate could bear.
He sent his prophets to forewarn them of the wrath, that they might be spared,
if possible; and when his judgments and severity came, he mingled mercy therewith,
that by both he might try to the utmost what they might be wrought to.
He tried them a long while under the judges, and a long while under the kings,
often recovering them and setting them to rights,
expecting the fruit of his rod and of his love towards them.

[.discourse-part]
Question. What was the result of God`'s trying them under the judges and kings?

[.discourse-part]
Answer. They wearied out God`'s prophets; yea,
they wearied out the Lord also in that way of dispensation.
They chose the false prophets before the true,
lying divinations before the openings of life, and dead idols before the living God.
The kindnesses and mercies of God were wasted upon them,
for with his love they were not drawn; the bellows also were burnt, the lead consumed,
the heat of the furnace spent upon them, and yet their tin and dross not purged away.
Under the judges they tried out the Lord`'s patient
expectation of good from his delivering hand,
insomuch as he resolved to deliver them no more. Judg. 10:13.
Under the kings they were as unruly (whether good kings or bad kings,
given in love or wrath), insomuch as the Lord said, "`Why should ye be stricken any more?
Ye will revolt, more and more.`" Isa. 1:5. There was, indeed,
no bending of Israel after the flesh, and keeping him strait to God,
in that way of dispensation; therefore must he be cast off;
even becoming reprobate silver in the sight of the whole earth,
because the Lord would reject him.

[.discourse-part]
Question. How came Israel after the flesh to be rejected?

[.discourse-part]
Answer. His day of flesh was out, and the day of spirit was come, wherein the spiritual glory,
which was to succeed the shadows of the fleshly, was to be set up;
and so he not seeing that, nor entering into that, his own sun set,
and he hath abode in the darkness unto this day.

[.discourse-part]
Question. How came he not to see the spiritual glory?

[.discourse-part]
Answer. Because the eye of the flesh was open in him; which eye cannot see it.
He read the law in a gathered light, in the light of the earthly wisdom,
and not in the light of the spring from whence it came;
and then how could he possibly understand the law aright?
Could he then choose but set up the shadows of the law in
the stead of the substance which was veiled therein?
He read Moses with the eye which can see but to the veil,
and not to the glory which was revealed to Moses, and which Moses hid under the veil.
And thus likewise he beheld the prophets, in the days of their appearance;
not in the light in which they appeared,
but in the light of his own reason and imaginations;
and upon this ground the Jews still chose and cried up the false prophets,
but persecuted the true.
Now not seeing Moses in spirit, nor the prophets in spirit,
how could they see him who was greater than the prophets;
he looking so contemptibly to the sight of that eye wherewith they expected to see him?
It is the Jew in spirit who alone can see and own the Messiah in spirit: yea,
no fleshly Jew could possibly discern him then, whose eternal life, light,
and power was hid under so mean a veil.
He must be more than a Jew after the flesh, who can own so much as the law,
or any of the prophets in spirit;
and then surely it can require no less than inward Jewship to discern the Messiah himself.
They knew by the letter that then he was to come and appear;
but they could not know by their observations from the letter which was he;
but alone by the pointing of the finger of the Spirit, which they were unacquainted with.

[.discourse-part]
Question. What did they do to him, not seeing his glory?

[.discourse-part]
Answer. They dealt with him as they had dealt with the prophets before him,
disdained him that he should claim to be the Son of God, slighted him, reviled him,
reproached him,
preferred Moses and the prophets above him (who all did but declare of him); yea,
at last they preferred a thief and murderer before him,
and put him to death after that manner that the prophets had foretold they would do.

[.discourse-part]
Question. Did the prophets foretell that the Jews would put the Messiah to death?

[.discourse-part]
Answer. Yea, very manifestly, with the manner and circumstances thereof.
Daniel said plainly that the Messiah should be cut off; though not for himself.
chap.
9:26. Isaiah shows the cause why he was cut off; to wit,
"`For the transgression of my people was the stroke upon him.`" chap.
53:8. He was the Lamb without spot; there was no iniquity found in his heart,
nor guile in his mouth; but he offered up his spotless soul, through the eternal Spirit,
as a ransom for the souls of transgressors, and with his bruise are they healed.
David shows yet more particularly how he should be cut off,
"`They pierced my hands and my feet.`" Ps. 22:16. And Zachary saith, that afterwards,
in the days of their visitation, "`They shall look on him whom they have pierced.`" chap.
12:10. Was he not betrayed by one of his own table? Ps. 41:9.
Did they not cast lots for his garments? Ps. 22:18.
Was not gall also given him, and vinegar to drink? Ps. 49:21.
Were not his bones kept from being broken, according to the paschal lamb,
the type? Ex. 12:46.
Oh that the Jews could read the words
of their own prophets in the light of the prophets,
and not in the light of man`'s imagination! and then they could
not but bow before the spring and fountain of that light,
as it was revealed in flesh according to the Scriptures,
and see how that body was prepared for the light to shine in,
and for it to do the will in, and to offer up the sacrifice which God would have,
that so an end might be put to all the sacrifices and offerings which God would not have. Ps. 40:6.
Dan. 9:27.

[.discourse-part]
Question. What was to befall the Jews for refusing the day of their visitation by the Messiah,
and for the putting of him to death?

[.discourse-part]
Answer. They were to be cast off, to become no people, their covenant to be broken,
their glory turned into shame, their light set in obscurity, their house made desolate,
and the hand of God pursuing this desolate people,
making them a scorn and reproach throughout all nations. Dan. 9:27.
And is not this come to pass upon them?
For what person hath been more hateful and hated than a Jew,
who was once the glory and envy of all nations?
Yea, hardness and blindness have so happened to them,
that they cannot see the plainest things written in the prophets
concerning the expiration of the day of Moses with all his shadows,
and the succeeding of the spiritual glory in the days of the Messiah;
but their eyes and hearts are still blinded, and held captive in the figures of things.

[.discourse-part]
Question. Is there any scripture of the prophets which declareth
that they should be thus blind and hard?

[.discourse-part]
Answer. The Spirit of the Lord in the prophet David (the beloved king,
and figure of the Messiah) prayed for this righteous recompense to them.
"`Let their table become a snare before them, and for welfare a trap.
Let their eyes be darkened that they see not, etc.
Let their habitation be desolate,`" etc.
Ps. 69:22, etc.
What is their table?
Where and on what do they feed?
Is it not on the writings of Moses and the prophets?
Now all the meanings, observations,
and hopes which they gather from these (being under the curse,
and out of the Spirit of the prophets) cannot but be that snare and trap;
and that which entangleth them deeply to this day is,
their misunderstanding and misinterpreting of Moses and the prophets.
O Lord, my God, in the abundant riches of thy goodness, at length pity them,
and let the fierceness of thine indignation abate towards them,
and in thy love open their eyes, to see their state, and what they have refused,
and against whom they have lifted up their heel, in their conceited wisdom and knowledge,
which they have gathered from Moses`' and the prophets`' writings,
that they may mourn after thee, and wait for thee in the way of thy redemption!

[.discourse-part]
Question. How long is this desolation and hardness to abide upon them?

[.discourse-part]
Answer. Until God visit them with his Spirit, and open their eyes to see his spiritual glory,
and turn their hearts towards it.
Then their outward expectations and desires after an outward
glorious kingdom will soon come to an end,
and the Messiah will be known, owned, and received by them in Spirit;
yet any outward glory that the Lord God sees good for them, they shall not want either.
This the prophet Isaiah plainly relates to the ear that is spiritual.
chap.
32:15. "`Until the Spirit be poured upon us from on high,
and the wilderness be a fruitful field,
and the fruitful field be counted for a forest.`" They must lie
waste until the Lord God please to let forth his Spirit upon them,
to gather them into his spiritual glory; for the day of their outward glory did end,
and a spiritual succeeded, which they are to be gathered into,
when the days of their distress and tribulation are accomplished.

The Spirit was once poured down from on high on the disciples of the Messiah,
upon his ascending into his glory, and the wilderness then became a fruitful field,
and the fruitful field was accounted for a forest;
but over that glory the defence was not so stretched forth,
but that a night overtook that day,
and the wild beasts made a prey of that vineyard and fruitful field also,
as well as of the former.
But there is to be a more general pouring out of the Spirit, even upon all flesh,
and the wilderness is more generally to be visited, and become a fruitful field,
and the fruitful field is more generally to be blasted and made a forest;
insomuch as all flesh everywhere shall appear grass,
and the glory thereof as the flower of the field,
which shall fade and wither before the breath of God`'s Spirit.
Then judgment shall dwell in the wilderness which is then visited,
and righteousness shall remain in the field which is then made fruitful;
and righteousness shall be powerfully operative, working out the lasting peace;
and the effect of it shall be "`quietness and assurance forever.`" No more war,
no more fighting with creatures, no more burdening and oppressing of the creation,
no more sinning and offending against the Creator,
no more being dispossessed of his life and glory;
but the dwellings which God reareth up in the last days for Israel, his people,
shall be peaceable habitations, sure dwellings, and quiet resting-places forevermore.
Oh, let Israel feel that which is able to awaken him, and wait for this!

[.discourse-part]
Question. How shall they be visited and gathered?

[.discourse-part]
Answer. By the new covenant, by the new law of the Messiah,
which is to go forth out of the New Zion, and by the word of the Lord,
which is to issue out of the New Jerusalem:
not by the covenant of Moses (their eyes may fail in hoping and looking out that way),
but by the covenant of the Messiah, where the law of the life is written;
not in tables of stone, or outward writings of the letter,
but in the heart by the Spirit.
There they shall be cleansed by inward water, receive the inward circumcision,
and mark of the inward Jew; be sprinkled with the everlasting blood of the Lamb,
and taught to offer up the spiritual sacrifice,
and shall hear the voice which will tell them of the way,
and which will lead them in paths they have not known.
There the spiritual seed, the spiritual Israel, shall find the Shepherd of Israel,
who leads into the land of life, puts forth his sheep into the pastures of life,
gives them of the living streams to drink begetting them as heirs of,
and bringing them up in, the everlasting power and dominion of the life.

[.discourse-part]
Question. How may old Israel enter into this path, and so become new Israel?

[.discourse-part]
Answer. By waiting on the Lord for the closing of that
eye which is wise according to the flesh,
and for the opening of that eye which is at first weak in spirit.
There must be a low beginning: Israel must know and not despise the day of small things,
if ever he will grow up into the riches and inheritance of his glory.
There is a light in every heart at first, which gives a sound in the natural vessel,
which is very hardly distinguishable from the natural, till,
by obedience and subjection thereto, its living touch, virtue,
and power comes to be felt and distinguished; but in the meek, humble, believing,
and obedient, it daily appears more and more,
and makes itself more clearly manifest to them who are walking
on unto the kingdom and inheritance in it,
while others are disputing about it.

[.discourse-part]
Question. How may Israel believe, and become subject to the light?

[.discourse-part]
Answer. When there is a drawing felt in the heart, either to good, or against evil,
he must not dispute concerning it on the one hand,
nor run on in the forwardness on the other (for both
these ways the breathings of the Spirit on him,
and springings up of the good seed in him, are easily quenched);
but in the fear he is to trust himself with what
his heart certainly feels in the drawing virtue,
and in the humility to give up the members to the good,
and to withhold them from the evil,
waiting for strength from the fountain of strength towards both.
By this means there is a travel and removal out of the corruption and filth of the heart,
into the pure, holy law, nature, image, and will of God.

[.discourse-part]
Question. Where doth God find the heart, when he first visiteth it with his light?

[.discourse-part]
Answer. In Egypt, in the darkness, in the bonds and captivity of death.

[.discourse-part]
Question. What doth the Lord do with it there?

[.discourse-part]
Answer. He exerciseth it awhile there, till he hath made it fit for a wilderness-state.

[.discourse-part]
Question. What doth he do with it then?

[.discourse-part]
Answer. He bringeth it into the wilderness which he hath fitted it for.

[.discourse-part]
Question. What doth he do with it in the wilderness?

[.discourse-part]
Answer. He prepareth it for, and leadeth it towards, the land of life.

[.discourse-part]
Question. What doth he do with it then?

[.discourse-part]
Answer. He giveth it an entrance into the everlasting kingdom (which
is the land of life) according as he hath prepared and fitted it.
That which is new-begotten, new-created and formed,
new-born in the Messiah`'s eternal light, findeth an entrance into, and a habitation in,
the light, and is not turned back into the land of darkness;
it abiding in the virtue and principle of its life,
although sometimes it may be exercised with the darkness for its further advantage.
"`Thou art our habitation from everlasting to everlasting,`"
saith the child of light unto the Father of spirits,
in all ages and generations.

Now that Israel after the flesh may the better understand
the path of the spiritual Israel in the way of redemption,
by the powerful visitations of the light of the Messiah in their hearts and consciences,
and may know the gospel of his salvation,
which is able to effect that which the law of Moses could not,
because of the weakness of the flesh on their parts; let them in fear,
and silence of the natural wisdom, and in waiting on the Lord in spirit,
consider the Questions and Answers following, relating to spiritual Israel.

[.centered]
=== Some Questions and Answers

[.heading-continuation-blurb]
For the direction, comfort, help, and furtherance of God`'s spiritual Israel,
in their travels in Spirit from spiritual Egypt,
through the spiritual wilderness, to spiritual Canaan;

[.heading-continuation-blurb]
Which is the land where the redeemed soul flourisheth in the Life,
walking with God, and worshipping him in Spirit and Truth

[.discourse-part]
Question.
What is the gospel?

[.discourse-part]
Answer.
A good message, or glad tidings to man, in the fallen estate,
concerning a promise of redemption out of it.

[.discourse-part]
Question.
Is man then in a fallen estate?

[.discourse-part]
Answer.
His present temper, constitution, disposition, and whole course,
upon the least touch of God upon his spirit,
do in some measure discover his fall unto him,
through the insensibleness which is come upon him by his grievous wound; and death,
through the fall, maketh him very unapt to take notice thereof.

[.discourse-part]
Question.
What was his estate before his fall?

[.discourse-part]
Answer.
A state of glory and blessedness, wherein he came pure out of the hands of his Creator,
was fitted for his use, service, enjoyment, and delight,
even for him to appear or disappear in, and exercise according to his pleasure.

[.discourse-part]
Question.
Wherein did his glory and blessedness consist?

[.discourse-part]
Answer.
Chiefly in these four things; to wit, in the light, in the life,
in the liberty in which the vessel was formed,
and in the indwelling and appearing of the Creator there, according to his pleasure.

[.discourse-part]
Question.
Open this a little further.

[.discourse-part]
Answer.
Man was made a vessel of light, a vessel of life, a vessel of pure freedom.
He was formed in the eternal image and had a pure being in that image.
He was light in the Lord, living in the Lord, free unto all good,
and from all evil in the Lord.
This was the state of his being at first,
and thus was he made in the image a pure resemblance of the eternal purity and blessedness:
but, besides this, he had the eternal life, the eternal substance,
the eternal purity itself dwelling in the vessel, shining in it,
and manifesting itself from it according to its pleasure.

[.discourse-part]
Question.
How came man to fall from this estate?

[.discourse-part]
Answer.
Not willingly, not of an inclination of his own; but he was deceived,
through the subtlety of temptation, to entertain a desire of enlarging his blessedness,
out of the limits of the will of his Creator.

[.discourse-part]
Question.
How could such a temptation enter man, he being pure and holy, inclined to good,
and against evil, after the image of his Creator?

[.discourse-part]
Answer.
Man was not made to enjoy a perfection in himself separate from his Creator,
or to live of himself, but by dependence.
Now though he had no inclination in him not to depend,
or to seek a life in himself out of the fountain, yet there was a capacity of so doing:
before which capacity the tempter laid his bait of advancing him to a greater wisdom,
glory, and excellency than his Creator had placed him in;
with which he consulting out of the dependence upon his Creator fell from that
which alone was able to uphold him in the pure state wherein he was made.
Thus was he taken in the snare of misery,
and brought to that loss which all the sons of Adam lie grovelling under to this day,
when the Lord at any time awakens the sense thereof in them.

[.discourse-part]
Question.
What was the state of man in and since the fall?

[.discourse-part]
Answer.
A state of darkness, a state of death, a state of deep captivity, wherein his soul, body,
and spirit are become dark as to the light of God, dead as to the life of righteousness,
and captive unto that spirit which hath entered them by their hearkening thereto,
who dwelleth and ruleth in them in the darkness, as God did before in the light.

[.discourse-part]
Question.
How is man dark?
How is man dead?
Is his soul or body dead as to their being?
Or how else is it?

[.discourse-part]
Answer.
Man is not dead as to his being either in soul or body, but as to the right, pure,
and sanctified state of each.
The vessels still remain the same in being; but they are emptied of their proper liquor,
and filled with other wine.
The understanding is the same, the reason the same, the will the same,
the memory the same, the bodily members the same, as to their being or matter;
but they are all otherwise leavened, and another king now dwells in them,
and reigns over them.

[.discourse-part]
Question.
Then there needs not any dissolution of man`'s reason, or bringing it to nothing,
in relation to man`'s recovery; but only a changing of the leaven.

[.discourse-part]
Answer.
Man is become another thing by degeneration from the life.
He is so poisoned by sin and corruption,
that he is to be wholly broken down and brought to nothing, even in the very naturals,
that he may be new-made and built up in the newness of the Spirit.
Thus he is to become as a fool, as a little child,
or rather as a seed to be cast into the womb of life,
there to be formed and born of the Spirit.
And as he springs up in the life, he is to forget his own country, living in the Spirit,
and walking in the Spirit; where watching to the Spirit,
and against his own reason in the pure childishness,
in the simple instinct and naturalness of the life,
he shall at length find a reason new-formed and springing up in him;
which waiting on the Lord in obedience and subjection,
shall be taken into unity with the life.
But if the eye of reason open too fast, and be not kept down to the light of life,
the betrayer will enter again at that door, and bring the soul into death,
after it hath had sweet and precious tastes of the redeeming virtue and power.

[.discourse-part]
Question.
Can man in the fall see his fallen estate, and so seek after a recovery out of it?

[.discourse-part]
Answer.
It is not possible for him so to do,
without some light shining upon him from the Redeemer.
How can darkness discover darkness?
That which maketh manifest the darkness is light.
When the vessel is dark, and the prince of darkness filleth it, and dwelleth in it,
what can that eye see but according to the darkness, judging evil good, and good evil,
bitter sweet, and sweet bitter.

[.discourse-part]
Question.
But there is no man but hath some light;
no man but at some time or other seeth good or evil in some measure.

[.discourse-part]
Answer.
That ariseth not from the light of man`'s nature,
as it now stands in the fall (which being wholly in the enemy`'s hands,
and being itself become darkness, cannot at all give man notice of, or light him out of,
the darkness), but from a fresh visitation of the life,
which giveth all men a day of visitation by the shining of its light,
wherein is some manifestation to man,
and some certain sight by him both of the good and of the evil; and not only so,
but there is also the living Spirit striving with him,
and attracting him from the one to the other, according to the Lord`'s good pleasure,
who is both the light,
and also the determination of the proportion of every man`'s visitation by it.

[.discourse-part]
Question.
But hath not man naturally a light in the fallen estate,
which discovereth unto him the good and evil?

[.discourse-part]
Answer.
Not a true light, not a true discovery;
but only somewhat which the enemy setteth up in man as such,
to keep him in the entanglements of the deceit, and out of the suspicion of it.
For the enemy entering into him,
by his subtlety blindeth and deceiveth his eye (that
he may the better hold him captive in the deceit),
insomuch as he discerneth not the false image which the enemy hath stamped upon him:
for though the enemy bringeth man into a state of real darkness, death, and captivity;
yet these do not at present appear to man what they are, but are miscolored, or painted,
to appear what they are not, the better to deceive, bewitch, and entangle man therein.
The enemy did not represent darkness in its black hue,
death and captivity in its dreadful appearance, to Adam; but as wisdom, as light,
as a better life, as a greater freedom.
And thus he still enters man, and after this manner he still dwells in man,
until the true light pursue him, opening and discovering his deceit,
and drawing man back from this false paradise of
pleasure in wisdom and liberty out of the life,
into a sense of his want of, and breathings after, the true garden of the living God.

[.discourse-part]
Question.
Is man then mistaken in his judgment of good and evil since the fall?

[.discourse-part]
Answer.
Yes, altogether;
and by this means doth he so pleasingly situate himself
and take up his habitation in the kingdom of darkness,
wherein are strong-holds and wise reasonings against the true God,
and for the false appearances of good,
which the enemy of the soul strongly makes men believe
to be such as he represents them for in the darkness.
Thus in particular persons, and also in societies, evil is pursued after,
and advanced for good, and the true good suppressed as evil,
through the working of the mystery of darkness in men`'s hearts.

[.discourse-part]
Question.
What then is the proper estate and condition of man in the fall?

[.discourse-part]
Answer.
A state of false light, of false life, of false liberty.
He seemeth to himself advanced in wisdom above the low, empty, naked estate of innocency,
which is nothing, and hath nothing,
but by a continual dependence on the goodness of the Creator.
He seemeth also advanced in life, advanced in liberty; he can speak his own words,
think his own thoughts, do his own will, seek himself, please himself, satisfy himself.
The life of righteousness is a yoke, a bond, in his eye;
he is free from the restraint of it; he hath life in himself,
and is exceeding wise in the compass of his own dominions.
Thus doth the enemy transform the kingdom of darkness and death,
giving fallen man a share with him in it, while he remains his willing subject.
And here the goods of the enemy, the heart estranged from God, yea,
not only the devout and zealous worshipper in invented forms, but also the gross sinner,
the envious, lustful, and wicked mind, the perverse tongue, the bloody hands and feet,
are at peace, and have joy and pleasure in their course and circuit in the earth.
But all this is but the deceit of the enemy wherewith he hath cheated
man with false appearances and representations instead of the true,
as man himself will see,
whenever the eye of his soul comes to be thoroughly awakened by the eternal light,
whether here or hereafter.

[.discourse-part]
Question.
What is the work of redemption?

[.discourse-part]
Answer.
To purge the old leaven out of the vessel,
to purify the vessel from all the false appearances of light,
to batter down all the strong-holds of the enemy in the mind, all the reasonings,
thoughts, imaginations, and consultations, which are not of the pure, nor in the pure;
and so to new-create and new-form the vessel in the image
of the wisdom and purity wherein it was at first formed.

[.discourse-part]
Question.
Who doeth this work, or who is man`'s redeemer out of the fall?

[.discourse-part]
Answer.
The Eternal Word or Son of the Father,
even the wisdom and power which went forth from the fountain in the creation,
the same goeth forth from the bosom of the Father to purify the creature,
and so bringeth the creature back (being purified and cleansed) into his bosom again.

[.discourse-part]
Question.
With what doth this Word, or Redeemer, redeem?

[.discourse-part]
Answer.
With his own life, with his own blood, with his own eternal virtue and purity.
He descendeth into the lower parts of the earth, becomes flesh there,
sows his own seed in his prepared earth, begets of his flesh and of his bone,
in his own likeness,
and nourisheth up his birth with his flesh and blood unto life everlasting.

[.discourse-part]
Question.
What is this life?
Or how doth it first manifest itself in the darkness?

[.discourse-part]
Answer.
It is the light of men.
It is that which gave light to Adam at first, again to him after the fall,
and to all men since the fall.
It enlightens in nature; it enlightened under the law;
it did enlighten under the gospel before the apostasy, and again since the apostasy.

[.discourse-part]
Question.
How doth the light enlighten?

[.discourse-part]
Answer.
By its shining.
The eternal Word moves, the life opens, the light shines: this, in the least degree,
is a beginning of redemption; in its fulness it is redemption perfected.

[.discourse-part]
Question.
How doth the light work redemption in its shining?

[.discourse-part]
Answer.
Two ways: first, By turning the heart from the darkness towards itself; secondly,
By exercising the heart, being turned.

[.discourse-part]
Question.
How doth it turn the heart from the darkness?

[.discourse-part]
Answer.
The light, by its shining and enlightening, findeth out its own, openeth it,
and toucheth it with a secret virtue, which persuades out of, and draws the heart from,
the principle and power of death and darkness, towards its own native spring.

[.discourse-part]
Question.
May not these drawings be quenched, and the work of God stopped?

[.discourse-part]
Answer.
The plant of the Lord is exceeding tender, his pure Spirit jealous,
the enemy very strong and subtle; insomuch as the plant itself may easily be crushed,
the Spirit grieved and quenched, and the captivity redoubled.

[.discourse-part]
Question.
If Adam was betrayed in his full strength, how shall this poor,
weak plant spring up and grow,
without being supplanted by the violence and treachery of the enemy?
Or how shall the grieving of the Spirit be avoided
by a heart so full of corruption and provocations,
as man in the alienated state is, when the light first visits him?

[.discourse-part]
Answer.
The Lord God is nigh to help, nigh to pity, nigh to pardon,
nigh to watch over and support worm Jacob: yea,
nigh to revive life and spirit in him freely, and to heal his backslidings,
and multiply pardons, or it could never be.
Yea, the creature can never be brought so low, or so far lost,
but there is still help in the nature of God concerning him,
though there may not be help in any revealed promise.

[.discourse-part]
Question.
How doth God exercise the heart which is turned?

[.discourse-part]
Answer.
In faith and obedience, through very great varieties and changes of conditions.
He exerciseth it in believing his voice, and in obeying his voice, and following him,
in whatever, and into whatsoever, he draws and requires.

[.discourse-part]
Question.
How is the voice of God known?
Doth not the enemy speak inwardly also, and resemble his voice?
How then is the voice of the redeemer distinguished from
him who counterfeiteth the Shepherd and his voice?

[.discourse-part]
Answer.
By these two means:

[.numbered-group]
====

[.numbered]
_First,_ the soul lying low,
out of the wisdom in which the enemy appears and forms his likenesses;
in the simplicity which the Lord hath begotten, the life opens to it,
and the true light appears, which manifests the false light,
and false appearances of the deceiver.

[.numbered]
_Secondly,_
In that which is begotten of God there is not a hastiness or suddenness to determine;
but a silent waiting on the Lord in subjection, till the life speak,
and make things manifest.
Thus the knowledge and light of the child is held in the will of the Father,
and received from his hand, and according to his pleasure.
Thus what he will he hides, and what he will he makes manifest, and the child,
which is born of his will, is content with his will; and lying down there,
it keeps out of the enemy`'s territories, and of the reach of his temptations.

====

[.discourse-part]
Question.
What are the several estates or conditions wherein
God exerciseth the spirit of man in faith and obedience?

[.discourse-part]
Answer.
The particular estates and conditions are innumerable;
but they may be referred to these three general heads: First,
An estate of breaking down the former building.
Secondly, An estate of devastation or preparation to be new built.
Thirdly, An estate of rebuilding.
God doth not forget, but exercise his people in Egypt, even while they are in bondage,
before they come to receive his law.
He is visiting them in the dark land, opening the eye that can see the captivity,
causing groans and sighs in their oppressed spirits,
and then holding forth to them the promise,
and preparing them for a departure from that land.
Secondly, He hath a time of stripping them,
of nurturing and bringing them up under his discipline and close exercises,
wherein they are desolate, and ready to sin and perish every moment;
but as they are wonderfully provided for, and abundantly helped and pardoned.
Thirdly, There is a state of rebuilding the stones, when they are prepared therefor,
into a new building for the life to dwell in,
and for their entrance into the land of life.

[.discourse-part]
Question.
Declare these estates, and the exercises therein more plainly;
and first show what is the estate of the soul in Egypt spiritually,
when the Lord visiteth it there with his light.

[.discourse-part]
Answer.
An estate of deep bondage and groaning under the powers of darkness,
whose bitter oppressions thereof increase,
even as the sensibleness and tiredness of the soul increases.
The soul then sees its captivity from the life,
and finds a building of death and corruption raised up in it,
in which the prince of darkness dwells and bears rule: and then, oh,
how it groans and longs after departure from that land,
and waits for the promise of redemption out of it!
But yet it is still left in the hand of the enemy, and daily feels the bitter bondage,
from the powerful law of sin and death springing up in the heart,
and issuing out through the members.

[.discourse-part]
Question.
How is faith and obedience here exercised?

[.discourse-part]
Answer.
In believing the promise, in waiting for the promise,
in feeling some remote drawings of the life, and uniting therewith,
so far as is possible in this dark, captivated estate.
There is an acknowledgment of the true prince,
and a bowing to him even in this estate of captivity,
until he please to break the bands thereof, and receive under his guidance.

[.discourse-part]
Question.
What is the estate of the wilderness spiritually?

[.discourse-part]
Answer.
It is an estate of waiting for the guidance of the leader;
of receiving direction and laws from the leader;
of following the leader as he pleaseth to lead, through the entanglements, temptations,
straits, and necessities which he seeth fit to exercise the spirit with,
for the wearing out of that which is not to inherit,
and for preparing the heir for the inheritance.

[.discourse-part]
Question.
How is faith and obedience here exercised?

[.discourse-part]
Answer.
In waiting on the light for the leadings in the law of life,
and then in subjecting to the leader, being content with all his dispensations therein;
with the time he chooseth for standing still,
and with the time he chooseth for travelling on;
with the proportion of light and leading that he judgeth fit,
with the food and clothing which he prepares and preserves;
with the enemies which he sees fit to have avoided or encountered with.
Hereby the own wisdom, the own will, the own strength, the own desires, the own delights,
with all the murmurings, weariness, and discontents, which arise from the earthly part,
are by degrees worn out,
and a pure vessel prepared for the pure birth to spring up and appear in.

[.discourse-part]
Question.
What is spiritual Canaan, or the heavenly-built state, or state of the gospel?

[.discourse-part]
Answer.
A state of regenerating or renewing in the life and pure image;
where the building is reared up which is made without hands;
where there is a sweet and peaceable growth in the life,
and a fresh and satisfactory enjoyment of the life.

[.discourse-part]
Question.
How is faith and obedience here exercised?

[.discourse-part]
Answer.
In abiding in the vine, in drawing from the vine,
in returning the sap and virtue back into the vine; and living according to the will,
and in the free dispensation thereof.
Thus works are excluded, with self, from whom they proceed,
and the vine becomes all in all.

[.discourse-part]
Question.
Are Egypt and the wilderness and Canaan, spiritually,
as distinct estates as they were literally?

[.discourse-part]
Answer.
There are such distinct several estates spiritually,
wherein a man may be spiritually in Egypt, and neither in the wilderness nor Canaan.
So there is an estate in the wilderness, which is out of Egypt, and not in Canaan;
and an estate in Canaan, which is beyond both Egypt and the wilderness.
Yet these estates in spirit are oftentimes interwoven, with the exercises thereof;
insomuch as the soul may, in part, or in some respect (to his own understanding),
be in Egypt; in part in the wilderness, and in part in the rest, life, and peace.
But these things are not to be curiously sought into,
lest a wrong wisdom and a knowledge get up;
but abiding low and little in the little seed,
the kingdom and everlasting inheritance grows daily in the soul,
and the soul daily shoots up into it, and is enlarged in it.

[.discourse-part]
Question.
Is there any return back into Egypt, or into the wilderness,
after the state of the soul is advanced higher;
the entrance into the everlasting inheritance being administered,
and the soul partly taken into, and having found a place of rest in, the life?

[.discourse-part]
Answer.
The enemy lies near to deceive; and while he hath power to tempt,
if there be a hearkening to his temptations, there is a departure from the pure life,
and a return of the captivity or bewildering in some measure.
In the faith and in the obedience to the light of life is the preservation;
out of it is death and destruction eternally.

[.discourse-part]
Question.
Is not the Pure Being untouched by death and destruction?
And shall not the creature, when it is redeemed into him, be as he is?

[.discourse-part]
Answer.
The Pure Being cannot be impure, evil cannot enter upon him, it hath no place in him,
his nature excluding it; nor can it enter into the principle of life that comes from him,
and is always preserved by him;
nor can it enter upon that man who is begotten of that principle, abideth with it,
and is preserved in it.
But so to be in him, as to abide and not go forth, is a great state,
even higher than the first Adam knew.

[.discourse-part]
Question.
But are not light and darkness, good and evil, all alike to God?
And shall they not be so also to him, who is in perfect unity and fellowship with God?

[.discourse-part]
Answer.
All the light and darkness, good and evil, which can issue from the creature,
cannot reach God`'s being as it is in itself,
but only so far as he hath pleased to expose his life (in
the various manifestations thereof) to be reached thereby.
Yet his eye seeth the evil and the good; the perfection and the imperfection,
and his nature is perfectly excluded from all evil and imperfection,
insomuch as he cannot possibly lie or deceive,
or be unrighteous or unmerciful in any of his dispensations;
and that which is gathered into him, is thus one with him.
But that which can do any thing which is sinful and evil in itself,
is not in the true unity with the eternal Being,
but in the deceit of that spirit which erreth from him,
and entereth the creature in the imagined likeness of his life and happiness.

[.discourse-part]
Question.
How far may persons go, and yet be liable to the enemy`'s snare?

[.discourse-part]
Answer.
Very far.
They may come out of Egypt; they may pass through the wilderness;
they may receive an inheritance or portion in the holy land;
they may have houses and vineyards which they builded not nor planted;
they may have had deep draughts of the life, deep incomes of the love,
large riches of the grace, and precious tastes of the fulness.
They may have been in the Paradise of God; may have been anointed by God;
may have stood upon his holy mountain,
and walked up and down in the midst of the stones of fire, etc.,
and yet the enemy may have leave to tempt, and may find entrance for his temptation;
advancing above his estate in the deceivableness,
and increasing the glory in the eye of the wisdom which he steals in;
and so hold the spirit captive in his golden chains,
and lead it back again to the chambers of death.

[.discourse-part]
Question.
How doth, or can, the enemy prevail over persons in so glorious an estate?

[.discourse-part]
Answer.
By opening a larger eye in them, than is given them in the life to see with.
The eye of life is limited in man,
and man is to be held within the limits and openings of life;
and his heart and mind to be bounded within the desires
and delights which arise from the life:
he is to wait on the life, for its living, moving, and being all in his being:
and here he shall be large enough, and full enough, and wise enough, and happy enough.
But there is somewhat which presents to him a kingdom, a riches, a dominion,
a vastness of perfection in himself, and at his own command; the which,
he beginning to listen unto,
the same opens an eye in him to see the beauty and glory thereof,
and then immediately his heart is taken, and he cannot avoid the snare;
nor can he henceforth know where he is,
until that which he hath forsaken again please to visit him,
and to discover to him his iniquity and error from the true root.

[.discourse-part]
Question.
What is the way of safety, when God enlargeth the territories of life in the soul,
and causeth his love and grace to abound?

[.discourse-part]
Answer.
To drink the draughts of joy and sweetness in the pure fear and trembling;
not departing therefrom in whatever it doth for God, or receives from him,
till the salvation be wholly wrought out and perfected,
the habitation of unspotted love prepared, and the soul led into, and seated in,
its complete mansion therein.
And then the name of fear is no more heard of in the land of life;
though the principle from whence the fear sprang,
and the birth and building (which was begotten, raised up, formed,
and perfected in the fear) abideth forever.
So that the pure love doth not cast out the pure fear (wherein is no bondage of the life,
but the preservation of the life from the bondage),
but swallows it up and comprehends it.
For the pure fear is but love descended, and the pure love is but fear ascended;
the eternal principle or substance being one and the same in both.

[.discourse-part]
Question.
Is there then such a place of safety, upon which the enemy cannot intrench?

[.discourse-part]
Answer.
There is a state of such union with the life, as the enemy cannot come between;
where there is lying down and rising up in the power of the life,
and no beast of prey can make afraid any more;
nor can any root of bitterness spring up from within,
to trouble or make any disturbance between the life and the soul any more.

[.centered]
=== Some Questions and Answers

[.heading-continuation-blurb]
Conducing towards the further manifestation and opening of the path of
redemption and eternal life to the eye of spiritual Israel.

[.discourse-part]
Question.
How doth the Son of God, or Eternal Word, in whom is the light of life,
redeem man out of the fallen estate, out of the kingdom of darkness and death,
into the kingdom of everlasting righteousness and peace in the life?

[.discourse-part]
Answer.
Three ways.
First, By wounding him in the natural and corrupt estate,
and so breaking his peace and pleasure in the kingdom of darkness,
and making him weary thereof.
Secondly, By weakening him under the teachings and chastisement of the law.
Thirdly, By healing and binding him up with the oil of salvation,
in the power of the endless life, which is the gospel.

[.discourse-part]
Question.
How doth God wound him in the natural and corrupt state?

[.discourse-part]
Answer.
By pursuing him with his light, which letteth him see what it is,
discovering the evil and danger of it, and so weaning his heart from it,
and making him look out after, and long for, a redeemer.
Oh! how burdensome is the captivity to the awakened soul,
when he hath a glimpse of what man was before his fall,
when he had a place and being in the life, with a spirit suitable to the life,
and what he is now in his estate of estrangedness and alienation from the life;
and whither he is going in his paths of unrighteousness, estrangedness and alienation!
And while his heart is thus returning from the land of death and captivity,
and longing after the redeeming power and virtue of the life,
the enemy--the power of darkness--lays loads upon him,
drawing him more and more under the chains and bonds
of iniquity to the utmost of its strength.
So that now lusts abound, evils increase, temptations and snares multiply;
and in the land of captivity their strength is great, the soul weak and faint,
and the redeeming power and virtue seem very far off.
Now this is the estate of conversion; when the Lord,
in the midst of the power of death and darkness,
turns the heart from them towards himself,
causing it to wait (under the captivity) for the appearance of the arm of his strength,
to break the yoke of the oppressor from off the necks of the oppressed,
and so to bring out of the land of death and darkness,
into the travels towards the land of promise; where the peace, the life,
the liberty in the Lord, the rest, the joy,
the full content and happiness is reaped by the soul which follows the Lamb thither.

[.discourse-part]
Question.
How doth God weaken the creature under the teachings and chastisements of the law?

[.discourse-part]
Answer.
By exercising him towards good and evil,
and correcting him for his unbelief and disobedience, as he finds good, just,
and necessary for him.

[.discourse-part]
Question.
How doth God exercise him towards good and evil, and correct him?

[.discourse-part]
Answer.
When he hath brought him from under the power of darkness in some measure;
and in some measure set the spirit free therefrom,
by the virtue of his life springing up in the heart,
then he exerciseth the heart and conversation towards the good and from the evil;
then he giveth out laws for or against things,
according as he findeth most proper to the estate of every particular soul.
Now upon the giving forth of the law (the life being in some measure raised),
there is that which loves its teachings and pure path,
and there is that also which draws back from it; and that being yet strong,
there come many strokes and chastisements from the Lord, upon his own dear child.
And these are bitter; and to be forced into the sin which it loathes,
and in heart is turned from; and to be kept from the good which it longs after,
and in heart is united to (partly by the strength of the enemy,
and partly by reason of its own weakness and negligence), this is bitter also;
insomuch as it crieth out day after day,
and findeth this administration of the law almost
as heavy a yoke as the land of captivity itself was,
because of the weakness of it through the flesh,
and the strength and advantages which the corruption
of the heart and prince of darkness gather thereby.

[.discourse-part]
Question.
What is the benefit of these exercises upon the soul?

[.discourse-part]
Answer.
They melt, they break,
they make the heart tender and fit to be moulded by the eternal virtue and power,
into a vessel for the power.

[.discourse-part]
Question.
What frames of spirit do they work the heart or mind into?

[.discourse-part]
Answer.
Into very many precious ones.
As for instance,

[.numbered-group]
====

[.numbered]
_First,_ They make the spirit poor.
The daily inroads of sin and corruption dashing against
the holy and righteous law of life,
the overbearing the strong desires after purity, and forcing into the defilement,
hindering the soul from doing what it loves,
and making it do what it hates and would not, this makes it become poorer and poorer,
and more afflicted day by day.
Upon some visitations of the pure life, and some fresh virtue received, oh,
how strong doth the soul seem! but when it suddenly forfeits its mercies,
loses its freshness, and is plunged deeper in the pit than before,
how poor and weak doth it then feel itself, trembling at the next openings of the life,
and springings up of the virtue thereof in it, not knowing what weakness, captivity,
entanglements, and misery from the snares of death remain to follow!

[.numbered]
_Secondly,_ They bring into a mourning estate.
They fill the eyes with tears, and the heart with sorrow; yea,
they cause an entrance into the house of mourning.
To be accustomed to wounds, bruises, snares, grieving of the Spirit,
provoking of the deliverer, furthering and giving advantages to the enemy, etc.,
the sense of this overwhelms the heart with grief,
and causeth continual sorrow and lamentation to that which is upright towards God.

[.numbered]
_Thirdly,_ They bring into a meek, merciful, tender-hearted frame towards others.
He that is tempted, he that often falls, and is so often wounded and made miserable,
he pities those that err; he mourns over the miserable.
His heart is broken with the sins and afflictions of others,
and he knoweth not how to be hard towards them,
feeling such continual need of abundant mercy himself.
It is the rich man, the sound man in religion, that is rough and hard;
but he that is once thoroughly melted in the furnace, and made up again,
is made but tender, and retaineth the impression of the meekness, love,
and mercy forever.
Now a broken estate in religion, or a state of waiting for the life,
is much more precious than that which is rich and full by what it had formerly received,
and still holdeth out of the immediate feeling and fresh virtue of the life.

[.numbered]
_Fourthly,_ They bring into a hungry and thirsty state after holiness and righteousness.
Oh, how the soul that is sensible of its filth longeth to be washed!
How it panteth after the pastures of life, the food of life, the living waters?
to appear before and enjoy God, in the land of the living!
Oh, how doth the heart, that is daily afflicted with its unbelief and disobedience,
long for the faith that stands in the power,
and the obedience that flows from the power! "`Oh, teach me thy statutes;
show me the pure path of obedience in the way of life;
guide my feet in the way everlasting!
Oh, write thy fear in my heart, that I may not depart from thee;
create a clean heart in me, and put thy Spirit within me to be my strength!
Oh, continue thy lovingkindness to them that know thee,
and thy righteousness to the upright in heart!`" Oh,
what unutterable breathings daily issue out from the broken spirit,
towards the spring of its life!

[.numbered]
_Fifthly,_ They bring into a pure frame, into a cleanness of inside.
"`Cleanse first the inside of the cup and platter,`" said Christ to the Pharisees;
and he doth so in his disciples.
"`With the mind I serve the law of God,`" said Paul, when he cried out,
"`Oh! wretched man that I am,
who shall deliver?`" It is not conceivable what purity
of heart is formed by God in his Israel,
by the fire which he kindleth in his Zion,
and by the furnace which he setteth up in his Jerusalem;
for though in the furnace the dross still appears,
the sight whereof is apt to grieve and afflict the precious heart,
yet the melting and purifying sweetly go on,
and the soul (which abideth the heat) is effectually cleansed thereby,
as is very manifest afterwards, when righteousness springs up,
with the quiet fruit thereof; but this cannot be discerned,
while the flames are discovering and taking hold of the unrighteousness.

[.numbered]
_Sixthly,_ They bring into a patient frame;
fit to bear reproaches and persecutions from the world, who,
in the midst of all this weakness, misery, and distress, lay loads upon the poor soul,
persecuting him whom God hath smitten,
and speaking to the grief of him whom God hath wounded.
God smites for want of obedience; for too much propensity to please the world;
for not coming soon enough out of their customs, vanities, earthly ways and worships;
and so soon as the heart and conversation are given up in obedience to the Lord,
the world is discontent, and they smite and persecute because of the obedience.
Now the more the spirit is broken by the hand of the Lord,
and taught thereby to fear him; and the less strength it hath in itself,
to grapple with the persecuting spirit of the world;
the fitter it is to stand in God`'s counsel, to wait for his strength and preservation,
which is able to bear up its head above all the rage and swelling
of the waters of the worldly spirit in the men of this world.

====

Much more might be said, but this may suffice.
What is behind will be felt inwardly,
as the soul waits on God in the leadings of his Spirit, through the teachings,
chastisements, and distresses of the law.

[.discourse-part]
Question.
With what kind of things doth the Lord exercise the spirits of his Israel,
to bring their hearts into these and such other like precious frames?

[.discourse-part]
Answer.
With several sorts and kinds of things, both outward and inward; as,

[.numbered-group]
====

[.numbered]
_First,_ With oppositions, reproaches, and interruptions from the earthly part,
both in the men of this world, and in themselves.
There is abundance within, and abundance without, to resist, disdain,
and interrupt the work of God in the heart,
to oppose and withstand that which he hath begotten there; his leadings of it,
and its obedience to him.

[.numbered]
_Secondly,_ With temptations from the enemy, even of many kinds, natures, and degrees,
according to the present temper and condition of the soul; as either to doubt,
and so despair; or be confident in the flesh from knowledge received,
out of the pure fear and fresh feeling of the life; so again,
either to halt or draw back, or to be over-hasty and forward; so likewise,
either not to obey and act for God,
or to act in that will and wisdom which is against God.
Now these, with such like, are very numerous, frequent,
and sometimes very violent and impetuous.

[.numbered]
_Thirdly,_ By withdrawings of the life and sweet presence of God from the soul.
These are very frequent from the Lord towards his people,
insomuch as he is called by this title;
"`The God that hideth his face from the house of Jacob.`" Isa. 8:17. chap.
45:15.

[.numbered]
_Fourthly,_ By buffetings and prevailings of the enemy.
When the Spirit is grieved, the life wounded, and withdraws inward,
the enemy often gets ground, giving wounds and causing bruises to the soul;
not only tempting, but finding entrance,
and taking in the snare the bird which once escaped, and was delivered.

[.numbered]
_Fifthly,_ By doubts, fears,
and confused reasonings concerning the voice of God and the voice of the enemy.
In the hour of darkness (when the Lord seeth good to let forth the power thereof,
and to withdraw the beams of his light), how can that be clearly distinguished,
which alone is known and seen in the light?
How can the motions, drawings, and pure, low workings of the life,
be discerned from the false images and transformings of the enemy?
Oh, the misery and anguish of the poor soul in this condition! how is the poor,
upright heart pained between faith and unbelief, obedience and disobedience, etc.,
not knowing when it is drawn forward or backward, or by whom.

====

[.discourse-part]
Question.
When do these exercises begin?
and how long do they continue?

[.discourse-part]
Answer.
The Lord doth begin to exercise the soul even in Egypt;
for after the promise (of deliverance from spiritual Pharaoh) the bonds increase,
the yoke grows more heavy, Pharaoh grows more violent and furious,
the captivity increaseth much; but there is no sight of redemption at all,
save to that eye which is weak, and easily overborne in Israel.
But the exercises are much more full and sharp in the wilderness,
where Israel is led about, tried, afflicted, consumed day by day,
as if he should never come to the holy land, nor any of Israel be left to enter therein.
Yea, in Canaan, in the rich possession, in the plenteous overflowings of the life,
there is still somewhat left to try Israel, and bring him low with,
if at any time he be exalted with the glory and fulness of his own estate,
and begin to forget his God.

[.discourse-part]
Question.
Why doth God thus exercise his Israel?
Why doth he lead them in such a knotty,
and not in a more easy and ready way to the everlasting possession,
and to the fulness thereof?

[.discourse-part]
Answer.
Because their estate and condition require it.
They could not be so purified and fitted for the life;
their vessels would not be so enlarged to receive it in, nor they so safely enjoy it,
were it not for this course of wisdom,
wherein God exercises and trieth every cranny of their spirits,
until he hath perfected them, and stopped up the entrance of death everywhere.

[.discourse-part]
Question.
How do these exercises purify and enlarge them?

[.numbered-group]
====

[.numbered]
_Answer. First,_ They try the strength and virtue of the life in them,
and discover to them their further want thereof.
In the time of the soul`'s prosperity there seems to be enough;
but the day of distress maketh manifest the estate and condition as it is.
Then the faith, the love, the patience, the meekness, the constancy,
and chasteness to the spouse (loving him, and cleaving to him, above all,
and in all) many times are found to be less than they were judged to be.

[.numbered]
_Secondly,_ It brings to a waiting on God for support, and for receiving of more from him.
Then the life breathes vigorously, and the soul hankers after, cleaves to,
and sees its need both of the presence and increase of the virtue of the life.
Then he that was rich becomes poor, and he that was full becomes empty and nothing; yea,
he that had enough to live on and to spare, is now pressed with hunger, want, and penury.

[.numbered]
_Thirdly,_ It prepares for a clearer entrance into, and safer enjoyment of, the fulness;
As the soul is more emptied of the strength and riches it received from God;
so it is more prepared to enter into, and live in, the Pure Being itself.
For nothing can live there which veils.
In the life God was, and is, and is to be all in all forever.
That, therefore, which enters there, and lives and abides there, must be poor, empty,
naked, nothing, and remain nothing forever.
As it gathers any thing from the fulness, and becomes any thing in itself,
thereby it is shut out.

====

[.discourse-part]
Question.
How doth God heal and bind up that which he hath wounded
and broken to pieces with his various and frequent exercises?

[.discourse-part]
Answer.
By opening the power of the endless life,
in the vessel which he hath thoroughly purified and prepared,
and filling it with the power.
The free power of life, that is the gospel.
To the meek, to the brokenhearted, to the cleansed it is prophesied;
and when the work of cleansing is finished, the wound made wide enough,
and kept open long enough, and the death to the first husband fully accomplished,
then the perfect oil is perfectly poured in,
and everlasting health and salvation obtained.
This is the end which God aims at in the visitations and leadings of his seed;
happy are they that pass through the vale of misery,
and drink off the dregs of the "`cup of trembling,`"
not fainting nor sitting down by the way,
but following the faithful Shepherd and Leader of Israel, till they arrive here.

[.discourse-part]
Question.
What is the great danger in the path of life?

[.discourse-part]
Answer.
The great danger is of ascending a step higher than
the present estate and condition will bear;
for by this means the aspiring mind gets up, and is exalted,
and holdeth somewhat received from the life,
out of the pure fear which preserves the heart clean,
and out of the sensible feeling which keepeth fresh and living to God.
And then the simplicity is betrayed, and a wrong spirit lives, and a wrong eye is opened;
so that there is nothing now but whoredom from the life,
and the heart exalted and conceited in the way of its whoredoms,
as if it were the pure bed and most excellent way of enjoyment of the life.

[.discourse-part]
Question.
What way is there of preservation herefrom?

[.discourse-part]
Answer.
Watching to the life, keeping low in the fear, and close to the feeling.
Here the aspirer is shut out, or soon espied at his beginning to enter,
and then the living cross received, which crucifieth and driveth him back.
And indeed there is no way of safety in the travels towards the enjoyment of life,
or under any enjoyment before the state of perfect death,
but under the cross to that spirit and nature which would dwell there,
and please itself therewith, and be somewhat therein,
and so forget the pure everlasting spring, adulterating with the streamings forth of it.

Man was made for God to be a vessel of his pleasure, to receive his content, enjoyment,
and happiness by reflection.
So that man`'s proper work was to watch to the spring from whence he came;
to be disposed of, ordered, and to be according to his pleasure.
This was natural to man before his fall, till a corrupt spirit by deceit entered him,
and corrupted him.
And while any thing of that corrupt spirit or fallen nature remains,
he is apt to aspire in the self-hood,
and to seek the enjoyment of what comes from the fountain (yea,
and the fountain itself also) in and according to the will and wisdom of the self-hood.
And here let man receive what gifts soever from God,
be advanced to ever so high a habitation in the land of life, yea,
have the very fountain itself given him; yet by this means he will corrupt,
lose the gift or spring, be separated from it,
and adulterate with what he can still retain or gather in his own principle.
And here do deep travellers lose their way,
falling from their portion in the land of life,
and from their enjoyments in the paradise of the pleasure of the life,
into the earthly and sensual spirit,
holding things wisely and richly there in the earthly principle,
not knowing the remove of their habitation thither, nor thinking that they are there.

He that readeth these things, let him not strive to comprehend them;
but be content with what he feeleth thereof suitable to his own present estate:
and as the life grows in him, and he in the life,
and he comes to meet with the things and exercises spoken of,
the words and experiences concerning them will of themselves open to him,
and be useful and serviceable to him so far as the Lord pleaseth,
he keeping to the leadings, savor, and principle of life in himself,
wherein alone his knowledge, sight, growth, and experiences are safe.

Now he that would travel safely in spirit unto the land of life,
let him wait to have these things following written by the finger of God in his heart,
and the sense and impression thereof preserved fresh in him.

[.numbered-group]
====

[.numbered]
_First,_ It is the free grace of God which begins the work of redemption,
which causeth the light to shine,
which worketh the repentance or turning from the dead state, and also the belief in,
and turning towards, the living God.

[.numbered]
_Secondly,_
It is the same grace alone that can preserve and cause the plant of grace to grow.
If there be a withdrawing of the light, a withholding of the free influence,
that which depends thereupon cannot retain its freshness;
which the Lord may do as often as he pleaseth,
for the chastisement of the rebellious part,
or for the trial of his pure life and virtue in his plants.

[.numbered]
_Thirdly,_ The grace of God visiting the soul in the death, in the darkness,
in the fallen estate, begetteth life anew in it,
maketh it in some measure light in the Lord,
openeth an eye in it to see the things of God,
an ear to hear and distinguish between the sound of life and of death,
a heart to turn from and refuse the vanity,
and to turn towards and abide in the living substance.

[.numbered]
_Fourthly,_ The Spirit of God carries on the work of redemption, by drawing, leading,
and acting the quickened soul: by exercising that which he hath begotten in the life,
under the law of the life.
Thus the life draws the soul daily nearer and nearer towards the everlasting spring,
and from the fading emptiness of sin, vanity, and the creaturehood; and the soul,
by the enlivening virtue, daily follows on after the life, in the leadings, spirit,
and power thereof.
There is a living soul begotten by the virtue of the grace,
and the living soul daily lives in the grace,
and travels in the virtue thereof from the unbelief to the faith,
from the enmity to the love, from the perverseness to the straitness,
from the iniquity to the righteousness, even from all the territories of the darkness,
and also from the weak measures and degrees of the
grace and life towards the fulness itself,
even until it perfectly centre in, and be fully filled therewith.

[.numbered]
_Fifthly,_ Where there is a stopping of the virtue received from the grace,
and not an answer in the heart, there the work of redemption is stopped.
If the soul follow not in the drawing, the drawing is lost, as to it.
If the ear open not to hear the voice of the Word,
or if it be not mixed with faith in the heart hearing, it proves ineffectual.
If strength issue forth from the Lord,
yet if the soul receive not the strength which issueth forth and bubbleth up in it,
or answer it not in giving up to it, and travelling on,
the soul abideth where it was at least,
if it also retire not backward from that estate and
condition whereto the life had advanced it:
for if the virtue of the life and grace be refused,
there is an advantage given to death to reenter,
and gain ground by its contrary virtue and power.

[.numbered]
_Sixthly,_
Mark therefore diligently how the Lord doth carry
on the dispensation of his love and free grace,
even as if there were much done by the strength and diligence of the creature.
What wounding of itself by repentance! what striving
to believe! what wrestling against enemies,
and for the influences of the grace, and to keep the hope up, and the distrust out!
What strict watching and waiting,
even as if the creature did work out its whole salvation!

[.numbered]
_Seventhly,_
Though the creature seemeth to do much itself (having received life from the grace,
and acting abundantly towards God in the grace),
yet it is the grace and virtue which comes from the Creator
(who is also the Redeemer) which indeed doth all:
for though the creature repent really, and turn from the darkness with its whole heart,
yet the repentance is of the virtue which flows from the grace,
and not of the creature which receives the grace: and so likewise in the faith, the love,
the obedience, the meekness, the patience, the watching, the waiting, the hoping, etc.
Yea, the very receiving the grace is not of the creature, but of the grace:
for the creature is dead until it be visited by the grace:
and by the visitation of the grace alone is made alive, and able to receive it.

====

Behold then the mystery of redemption.
God is all in redemption;
God doth all therein as fully as in creation (it
is a new creation) even the whole work thereof;
yet the creature quickened and renewed is in unity with him in his operations. Phil. 2:12-13.
He whose eyes are opened can read the mystery,
and in true understanding say (if he hath been led, and hath proceeded so far),
"`I am able to do all things through Christ that strengtheneth me; yet not I,
but the grace of God in me.`" Now to bring the creature to this,
the Lord exerciseth it daily in obedience unto him,
in the life and virtue which floweth forth from him,
causing it to feel its weakness as it forgets the virtue,
or aspires to live of itself on the virtue received,
out of the sensible feeling of its dependence upon the spring.
And indeed the virtue that comes from God can alone answer God,
and the creature is only accepted with the Spring and Father of life,
as it is found therein.

[.discourse-part]
Question.
But if the work of redemption be wrought by God`'s creating power,
how cometh it to meet with so many rubs and interruptions, and sometimes overturnings?
Can any thing stop God`'s creating power?

[.discourse-part]
Answer.
So far as God absolutely pleaseth to create, nothing can stop or hinder;
but the entrance of that which he beginneth to create into the creature,
and its getting a being there, as also the growth and preservation of it there,
may be hindered by the force of spiritual enemies, if the Lord pleaseth to permit;
or by the grieving and provoking of that free power,
which alone begetteth and preserveth life in the heart.

[.discourse-part]
Objection.
Then the work of redemption is not carried on by an absolute, free-creating power.

[.discourse-part]
Answer.
The creating power and preserving power is the same; but the work is somewhat different,
both in the outward, visible creation, and inward, new creation.
The preservation of that which is created and planted (unto its growth
and perfection) is by the same power which created and planted;
but rather in a way of care, industry, art, and skill,
than of such immediate force and power,
though by the exercise and putting forth of the same virtue and power.

[.offset]
There are three things in redemption:

[.numbered-group]
====

[.numbered]
_First,_ There is the issuing out of the free grace, love, virtue,
and divine power towards the creature.

[.numbered]
_Secondly,_ There is the opening of the estate of the creature thereby,
convincing and drawing it out of the alienation from the life,
towards unity with the life.

[.numbered]
_Thirdly,_ There is the following of the creature after the life,
in the quickening virtue of the drawings, through all the snares, temptations,
diversions and oppositions of the enemy.

====

Now there is no hindering of the issuing forth of the free grace towards the creature,
or of those convictions and inclinations of the creature to follow,
which necessarily ensue thereupon.
But the pursuit and progress of the creature (or its abiding with the
quickening virtue and power) may many ways be interrupted and diverted,
and so the creature drawn from under the influence of the free covenant;
for though the covenant be free, yet the creature only partakes of it,
as it is drawn into it, and preserved in it.

Therefore let those fear who feel the power and redeeming virtue, and know,
that notwithstanding the free and certain promise to the seed,
yet the creature is as clay in the hands of the potter,
which may be made a vessel of honor or dishonor, as he pleaseth to favor it,
or take occasion against it.
And whoever would pass through the work of salvation and redemption,
unto the salvation and redemption itself, in the living virtue received from the life,
let him keep fast hold on the good pleasure,
and in it give all diligence to make his calling and election sure,
working out his salvation with fear and trembling,
because God worketh in him both to will and to do of his good-will.
And walking diligently and industriously in this path,
he may attain the seal of the redemption, even that mark which can never be worn out,
and to full assurance of faith in the redeeming power;
though it is also possible for him afterwards,
through much negligence and grieving of the Spirit whereby he was sealed,
to lose the sight of the mark, and the comfort of the assurance,
which was once fresh and clear in his spirit.

For a close at this time,
I shall add a few words concerning the unity of God`'s grace (or free light of his spirit)
notwithstanding the various estates and conditions of man whom it visits,
and the variety of its operations.

==== There Is a Three-fold State of Man, Wherein the Grace of God Visits Him.

[.numbered-group]
====

[.numbered]
_First,_ The gentile state, or state of nature.

[.numbered]
_Secondly,_ The Jew state, or administration of the law,
wherein God takes him under his own tuition, making known his will to him,
and requiring obedience of him: and not only so,
but also directs him to the inward teacher, and to the principle of the pure fear,
which is the place of wisdom`'s teaching and instructions.

[.numbered]
_Thirdly,_ The gospel-state, or state of faith, where the principle is raised,
the seed lives, and that is felt springing up, known, and enjoyed, which does the will,
and receives the promise.

====

Now in all these, the law, the light, the life, the wisdom, the power,
are one and the same; but the administrations are different.

In the Gentile state, or state of nature,
the light which man receives there (to discover evil,
and work him into good) is of the Spirit, and by virtue of the promise.
For he had been everlastingly shut up in the darkness, had it not been for the promise;
and it is for the promise`'s sake, and from the free-grace,
that he hath any visitation in the state of nature, and any desires after,
or leadings towards, the good, and from the evil; which spring not, nor can spring,
from corrupted nature; but from the free fountain of the new life.

In the law-state, the light grows more clear;
the teacher is there discerned and acknowledged; his drawings, warnings, instructions,
and reproofs felt more distinctly,
and the soul (that is watchful) continually exercised therein.

In the gospel-state, the principle of life is raised, the promised seed come,
the power which doth the will received, and the light of life entering into,
and possessing the vessel.

Now this is the whole of man,
to wait on the ministration of the life to him in his present estate,
whether he be yet in the estate of nature, or under the law, or under grace.
To know whence his redemption springs,
and to wait on the redeeming arm for the beginnings, progress, and perfecting of it;
and if it be in the feeling of that virtue, it is enough;
or if it be kept longing or panting after it, it is well; yea,
if there be but a desire in him after a thirst, there is hope; nay,
if there be but the least feeling of his dead, barren, and senseless estate,
there is some life in him, which the Lord loves,
and will find a time to express his bowels towards: yea,
that which is wholly in the darkness, and shut up in the pit,
the Lord hath bowels in him towards, and after many days may please to visit.
Oh, the height, the depth, the length,
the breadth of the riches of the mercy and love of God!
Who knows his yearning towards souls, and his ways of visiting and redeeming!
O my soul! hope thou in the Lord forevermore, and leave not breathing towards him,
till thou and his whole creation be filled and satisfied with him,
and then fetch the full breath of life in him forever.

==== Postscript

I have been treating of the inward work, as it is wrought in the heart by the power,
and brought to the sensible, experimental knowledge of the creature;
yet would not be so understood as if I made void
what was done without by Christ in his own person,
or any of those ends and purposes for which it was wrought,
and appointed so to be done by the Father: though this I know,
that the knowledge of those things, with the belief therein,
or any practices and observations therefrom, without the life, can no more profit now,
than the Jews`' literal knowledge of the law could profit them,
when they were rejected therewith.
And since the apostasy, of this latter age especially,
I have clearly seen in the Spirit of the Lord,
that the professors`' knowledge of the letter of the gospel,
and cleaving to their apprehensions which they gather therefrom,
is become a snare and trap to them, to keep them from feeling the power,
and living in the sensibility of the virtue of the grace;
even as the Jews`' table (or gathered knowledge from
Moses and the prophets) became their snare and trap.
The Lord open their eyes in his due time to discern it,
that they may not withstand that ministration and revelation of his everlasting gospel,
which God seeth good to visit the apostatized world with, after this long,
dark night of apostasy! whereof those that stick in forms,
or knowledge of things in the letter, without the power,
cannot but prove the greatest enemies, opposers, and persecutors.

Now to help them a little, if the Lord please;
in the rolling of my bowels towards them I find my heart opened,
to lay a few things before them.

[.numbered-group]
====

[.numbered]
_First,_ With my heart, in the sight of the Lord,
do I own that principle which formerly wrought in some of them,
which I myself was wrought upon by,
and knew not only the outward knowledge which they were acquainted with,
but also the inward work: and I also knew what I called the light of nature,
and what I called the light of the Spirit, the one whereof was not the other,
but differed as far as Spirit and flesh.

[.numbered]
_Secondly,_
I also own all the openings and refreshments which they received from
the Lord in reading of the Scriptures in their public or private exercises,
and the experiences which they had from God in their own hearts:
and I know that these things in themselves were true in their proportion;
however the present sense, and holding of them out of that wherein they received them,
may justly be judged by the Spirit of the Lord in his servants.

[.numbered]
_Thirdly,_ Though those things were true in their day, and in their proportion and measure;
yet in them they might lose their virtue, and die,
and so they not retain the thing in its life, in its own principle,
in the newness of the Spirit, in that birth to which God gave it;
but only an image of it in the natural understanding, in the earthly part,
in the dead principle;
and then their knowledge of God and their experiences cannot but be corrupted,
and now become the possession of death, and the engines of death in their hearts.
Again, God had somewhat further to manifest,
even to bring forth that which they earnestly prayed for in that day; which they,
having abode in that virtue wherein they prayed,
might easily have discerned and embraced; but being out of that,
and pleasing themselves with the literal knowledge of the things they then received,
holding them in the wise and earthly part,
that part cannot but stumble at the low and contemptible appearances of God,
which are still offensive to that part.
The great glory of God is hid in a little seed;
and how can the great eye of the fleshly-wise see it?
We have Moses and the prophets (said the Jews after the flesh), but as for this man,
we know not whence he is.
Even so it is now:
we know the relation which the Scriptures have given of Christ by the apostles,
we are sure this is of God, say the professors;
but as for this little seed of the kingdom, or light of God in the heart,
we cannot believe that all we want is to spring up in it.

[.numbered]
Now, _Fourthly,_ there is a necessity both of the knowledge of persons to pass away,
and also of their experiences to be given up, and let fall, in these two cases following:

====

[.numbered-group]
====

[.numbered]
_First,_ When the virtue is withdrawn from them, when death hath caught them,
when they become death`'s goods:
for that which is received from the life is only
profitable to the soul in the virtue of the life.
When the earthly part hath caught them, and seated itself there,
they then become the strong-holds of the enemy, and the engines of death to the heart;
so that then life and true relief are not to be had in them,
but where the eternal virtue pleases next to appear.

[.numbered]
_Secondly,_ When God hath somewhat to bring forth further in the world,
or in any particular heart,
to make way for it he brings death upon that which was before living.
Thus when God is pleased to bring forth a greater measure of faith,
and power of his Spirit, he distresseth the heart,
making the foregoing faith and power appear weak, and pass away;
and many times for a season shutteth up the soul in the unbelief,
until the fresh faith and fresh power spring up and arise.
And this causeth the necessity of the further dispensations
of his eternal virtue to appear,
and the beauty of them to shine; which they would not have done so abundantly,
had it not been for the foregoing distress of the heart.

====

There are yet some things further weighty upon my heart to lay before them,
needful for them to consider of,
which may be serviceable and helpful to them in their present condition,
if the Lord please to open their hearts, and impress them thereon.
They are four propositions, relating to the right knowledge of the things of God,
which are these following:

[.numbered-group]
====

[.numbered]
_First,_ That the knowledge of the things of God comes from the Spirit.
As the Scriptures themselves came from the Spirit,
so the true knowledge of them is alone given, to any man which receiveth it,
by the same Spirit.
And no man living can know the mind of the words which the Spirit spake,
but as the same Spirit which spake them, gives the meaning of them.

[.numbered]
_Secondly,_ That the knowledge of God (the living knowledge,
the serviceable knowledge) is alone held in the Spirit,
and in the birth which is of the Spirit.
Man`'s natural part is not the true treasury,
nor is man`'s reason to be master of any of the things of God`'s Spirit;
but that which holds the knowledge of the kingdom, the grace of the kingdom,
the living experiences, is that which is born of the seed of the kingdom;
and man`'s reason is forever to be shut out of the things of God, further than it bows,
is limited, and subjected.

[.numbered]
_Thirdly,_ That the knowledge received from the Spirit, is still to be tried by the Spirit.
The Spirit alone can keep it living,
and the Spirit alone can tell whether the life and virtue be still in it,
or whether death hath caught it; whether it be the manna fit for the soul`'s food,
or manna once given, but now corrupted.
O! my dear friends, wait to understand my experience concerning this thing,
which is this:--That which I had certainly received from God,
and which the true birth at first had fed on, the earthly birth would be catching at,
laying hold of, and treasuring up to feed on at another time.
Likewise in my reading of the Scriptures, I lay open to this great snare,
of reading in my own will, and gathering from thence in mine own understanding,
and so growing wise concerning the things of God after the flesh:
for though at that time I was not without living knowledge and experiences of God,
yet I knew not how to turn from the death, nor to keep to the life; and so the bad,
the lean, the earthly, the ill-favored, overgrew the good and well-pleasing to God,
and brought it into bitter misery and death.
Oh that ye knew being begotten of the will of the Father,
and keeping to the will of the Father, and receiving the bread daily from his hand!
That which man conceiveth concerning the Scriptures, is not the pure milk of the Word,
but that which the breasts give out; that is it which hath the immediate life, virtue,
and true nourishment in it.
And this must be returned back into the treasury, and not held in the earthly part,
in the earthly will and understanding,
but received from the life again when it is again needed; yea, this have I often known,
that when I have been in great distress, I have received fresh comfort from the Lord;
but running to that afterwards, it never was able to comfort me,
but more deeply wounded me.
And thus hath the Lord been teaching me to live upon himself,
and not upon any thing received from him, but upon the life itself, the mercy,
the good pleasure, which proportions out the living bread daily to the living birth.

[.numbered]
_Fourthly,_ It is easy receiving of knowledge in the earthly part, in the earthly wisdom,
out of the Spirit and living virtue.
When one readeth a scripture,
it is easy conceiving and apprehending a meaning one`'s self,
or taking in another man`'s meaning;
but it is hard abstaining from all conceivings and reasonings of the mind,
and waiting for the pure will and opening of the Spirit therein.
Also it is easy retaining of knowledge,
and making use of it in the will and wisdom of the earthly mind,
for both these are natural: but it is hard denying the reason,
the thoughts and imaginations, and watching to the Spirit.

====

O professors! wait for the living appearance of God,
even for the freshness of his Spirit in your spirits;
that in that which cometh from the Spirit ye may know the Spirit,
and may also know how to turn to him and abide with him,
having the watch set against that wisdom in yourselves,
which in all ages and generations is eternally shut out of the things of the kingdom,
although it may gather, get,
and hold a vast knowledge of the things of the kingdom in the earthly treasury.
Thus fleshly Israel hath the wisdom of the letter; but spiritual Israel the wisdom,
virtue, and life of the Spirit in all ages and generations.
And though he that is born after the flesh despiseth him who is born after the Spirit,
yet this is God`'s heir; and the bond-woman, the earthly wisdom,
with all her children (even the greatest giants in knowledge, profession of religion,
and scripture observations), must be cast out, and not inherit the land of life.
This is written that that might be raised in you by the power,
which is to inherit the life eternal; and ye not find your souls deceived,
when the light of that day fully opens, which hath already dawned.

I was in a poor, low condition, when the Lord formerly visited me; as lost, as undone,
as miserable as any.
What knowledge, what life, what precious virtue I then received, was from God`'s grace;
which was still his own, and he might call for it at his pleasure.
And surely, he which hath received from the fountain,
ought to trust and to give back again to the fountain, when he calleth for it;
and then to remain empty, naked, desolate, until he be again freely visited.
This is a hard lesson, who can learn it?
Who can trust his life with the fountain, and lie open to what follows?
Yet this did the Lord require of me; and my heart being not willing to part with my life,
but striving to retain it,
and grow in the first way of the dispensation of the grace unto perfection,
he brake it after an unutterable manner,
and brought such misery and desolation upon me as I could not possibly have suspected,
having been sealed by him.
And now he is teaching me to live more fully upon his grace, or rather upon the spring,
where I am nothing, where I can be nothing forever:
but he is and will be what he will be, and when he will be;
and nothing in me can be satisfied with him, but what is of him, and lives in him.
And here all that I have known, or formerly tasted of him,
springs up again at his pleasure; and I drink of the old wine, and also of the new,
but have nothing at my own disposal.
And when I catch at any thing, or would be any thing, I lose the spring,
and am corrected for my backsliding and adultery of spirit,
but am still again visited with fresh love,
and the springings up of fresh power and life,
and fresh visitations of the rich mercy and grace,
which the everlasting fountain naturally openeth in its own.
The pearl is exceeding rich, the treasure of life unutterable;
and he that will possess it, must sell all for it: even all his lusts and corruptions;
yea, all the riches of his nature (the best of his will,
the best of his wisdom most refined); nay not only so, but all the riches of his spirit,
all that he hath held, or can hold out of the life.
Then, when he is poor in spirit, and hath nothing in himself but emptiness,
nothing so much as to receive or retain the life, but what is formed, groweth up in,
and is preserved in the life, according to its own mere will and good pleasure;
then alone is he fit to be comprehended and brought forth in the eternal spring.
Perfectly happy is he who is perfectly possessed thereof;
yet he is not without a proportion of blessedness also,
who is mourning after it and travelling towards it;
which can never be attained by the natural part retaining
the letter of any spiritual revelation or knowledge;
but only by beginning in the eternal virtue, abiding in it,
and travelling from death to death, and from life to life;
till all be slain which is to die and perish in the way,
and all be raised and perfected which is to receive,
and live in the kingdom and crown of life forever;
which the Lord lays before all to run after,
but none but the spiritual seed (begotten of and abiding in the Spirit) can obtain.
Mind then this brief sum.

The lost creature, the undone creature,
is graciously sought after and visited by the fountain of its life and being.

Being visited with the mercy and grace, and impressed,
it receiveth somewhat of the grace and living virtue from the fountain.

Having received somewhat,
the creature is apt to retain it in the creaturely vessel (even in the own will,
and to enlarge the own wisdom thereby, and so to become somewhat again in itself),
forgetting the spring.

As the creature retaineth any thing in the natural part,
out of the immediate feeling of the living virtue, it corrupts,
it adulterates from the living spring.

And that which any one hath thus adulterated with, must be taken from him,
and he be made dead to it, and it to him, before he can be recovered into a living state,
fit to enjoy what he formerly received, or further to receive of, and grow up in,
the fresh, living virtue.
