[#man-duty, short="Questions and Answers Showing Man His Duty"]
== Some Questions and Answers Showing Man His Duty / And Pointing Him to the Principle of God in His Heart

[.heading-continuation-blurb]
Which is the root of life in all its dispensations,
and which, being kept to,
is able to bear the fruit of life in every dispensation.

[.heading-continuation-blurb]
As also some questions and answers,
concerning the Seed of Jacob and the true church.

[.section-author]
By _Isaac Penington,_ the Younger

[.section-date]
1662

=== Preface

The goodness of God endureth forever.
And though his creature man (who should have been subject
and obedient to him) hath sinned against him,
and by motions and inclinations of his own will and
wisdom (out of the principle of his pure life,
which was to have been his guide and governor) hath fallen short of his glory;
yet he still pleaseth to visit his poor lost creature with lovingkindness and mercy,
and with various dispensations of his life, according to his pleasure.
What man is there that hath not received a soul from the breath of the Almighty?
And what soul is it that hath not some visitations of life from that living breath?
The bowels of eternity most naturally roll towards all its offspring;
who seeketh the gathering of them all in the variety,
and according to the limitations of his will, in his pure wisdom.

There is a current or stream of life before the promise is known,
which secretly visits all, discovering the darkness in some measure unto all,
and drawing from it.
And happy is he who falls in with, and follows the leadings of the Almighty here;
for then he cannot abide in the darkness,
but still (according to the need of his condition) will meet with a true guide out of it,
and with the true power which redeemeth and delivereth from it.
For as the promise made to Adam, had relation to all his posterity;
so whoever is visited with any light by virtue of the promise,
that light will lead him to the promise,
and he (in the obedience thereof) will meet with the sweetness and virtue of the promise.
So that the lowest dispensation of God (the creature being exercised therein,
feeling the want of God`'s power,
and drawn to depend upon him for mercy and strength)
will lead fallen man back again to his Maker,
by the virtue which flows into man from the promise,
though ever so secretly and hiddenly.
For it is not the distinct knowledge of the promise,
(though that is a very great advantage) but the virtue flowing from the promise,
which saves.
Man being touched by that virtue, and by the touch thereof quickened towards God;
and in that virtue which comes from the redeeming mercy, cleaving to his Maker,
and hoping in his tender bowels, and feeling the weakness, insufficiency,
and corruption of his own will and understanding,
and so going forth from himself towards the spring which quickened him.
Here is Christ known in spirit, received in spirit, believed and relied on in spirit,
and his living virtue already felt, and further waited for.
And can this man, thus walking, thus believing, thus obeying,
thus cleaving to the principle which gives life, thus receiving virtue from it,
and growing up (in that virtue) out of the self-hood, into it; I say,
can this man miss of eternal life,
which runs along in all the streamings forth of this living virtue?

But oh, how sweet is the stream of life in the sensible manifestation of the promise!
He who feels the covenant in Christ,
and life streaming into his heart through the covenant,
and the seal of eternal peace to his soul,
and that he shall never be left nor forsaken by the fountain of mercy,
but all that ever befalls him shall conduce towards the working
out of the perfect redemption and salvation of his soul;
this is a precious state indeed; and this is the state which the feeling of the faith,
and the living obedience in the Spirit leads to.
Happy are they that walk in the path thereof,
who content not themselves with man`'s knowledge of Christ,
with man`'s belief of the things written concerning him,
with man`'s obedience to the precepts left on record by the apostles,
but whose living soul cannot be satisfied without the feeling and pressing after Christ,
the life, and without a true engrafting into him in spirit, through the living Word,
or testimony of life, received into, and believed on in the heart.

And how sweet also is the ministration of the law, which comes from the promise,
and is managed to the soul by the hand of the Mediator!
How sweet is it to see the creature fall daily! to find one`'s own strength to believe,
to obey, to suffer, to abide with Christ, to wait on Christ, to hope for Christ,
daily battered and brought to nothing, and no life left but what issues from the spring,
and is alone maintained by the free current thereof into the heart daily!
Here the stroke of the law is received by degrees unto perfect death.
Here are the openings of the pure prophecies in the Spirit concerning a new kingdom,
a new birth, a new heir, a new life.
Here is the axe laid to the root of the tree,
and that cut down in the heart which is not to live,
and which hinders the heir from his inheritance.
Here is the vale of tears; which tears spring from the life,
whose virtue washeth away the corruptible day by day.
Here is the house of mourning, and that state of darkness entered into,
which swallows up all the joy of the dark, earthly spirit, and consumes its nature.
Here the light of life is sown, and through these exercises it springs up;
and after the passing away of this ministration,
breaks forth in strength upon that soul which hath been thoroughly exercised herein.

I desire the good of all mankind,
waiting for the swallowing up of the dispensations of death,
and the breaking forth of life upon them in the seasons thereof,
according to the good pleasure of him whose gift life is,
and whose are all the dispensations of it.
And in that love, through the openings and drawings of life in me,
have I writ what follows;
not to upbraid or strike at any but to be an help unto such
as the Lord shall please to make it serviceable to.
Wait on the Lord, eye him, read in fear, praying to be touched by, and gathered into,
that which gives the feeling of the weight of truth.
Oh, that men`'s souls were awakened, that they might know what it is to perish from God,
and what to be saved by him!
The proper portion of man`'s soul is the fountain of eternal life;
and he can never be happy (nor in true rest, peace, or joy) while separated from it.
Let him who is not brutish in understanding,
and whose soul is not wholly dead God-wards consider this.

[.old-style]
=== Some Questions and Answers / Showing Man His Duty

[.discourse-part]
Question.
What is the proper work of man here in this world?

[.discourse-part]
Answer.
To fear God, and keep his commandments.
This is all that God requires of him, and this is enough to make him happy.

[.discourse-part]
Question.
What is God?

[.discourse-part]
Answer.
The fountain of beings and natures, the inward substance of all that appears;
who createth, upholdeth, consumeth, and bringeth to nothing, as he pleaseth.

[.discourse-part]
Question.
How may I know that there is a God?

[.discourse-part]
Answer.
By sinking down into the principle of his own life,
wherein he revealeth himself to the creature.
There the soul receiveth such tastes and knowledge of him,
as cannot be questioned by him that abideth there.

[.discourse-part]
Question.
What is it to fear this God?

[.discourse-part]
Answer.
The spirit and soul of the creature standing in awe of his nature,
and waiting to be kept in due subjection thereto; this is to fear him,
and this is the proper means of preserving the spirit
of the creature right in its motion towards him,
attendance upon him, and expectations from him.

[.discourse-part]
Question.
What are his commandments?

[.discourse-part]
Answer.
They are such as are either general to all mankind, common to some sorts of men,
or proper to particular persons.

[.discourse-part]
Question.
What are those which are general to all mankind?

[.discourse-part]
Answer.
They are very many; but may all be referred to these two heads; to wit,
_To love God above all, and one`'s neighbor as one`'s self;_
even so in every respect doing to him, as one would be done to by him in the like case.

[.discourse-part]
Question.
How may man perform these?

[.discourse-part]
Answer.
Only by receiving a principle of life from God, and keeping close thereto.

[.discourse-part]
Question.
How may a man come by a principle of life from God?

[.discourse-part]
Answer.
God is near to every man with the breath of his life,
breathing upon him at times according to his pleasure; which, man`'s spirit opening unto,
and drinking in, it becometh a seed or principle of life in him,
overspreading and leavening him up to eternal life.

[.discourse-part]
Question.
What hinders man from receiving this principle of life, and from keeping close thereto?

[.discourse-part]
Answer.
A fleshly principle, which is contrary to the knowledge, fear, and obedience of the Lord,
and to all that springs from the principle and power of his life.

[.discourse-part]
Question.
How comes this fleshly principle to be found in man?

[.discourse-part]
Answer.
It was sown there by the enemy of man`'s soul; man giving him entrance into his spirit,
by hearkening to his suggestions and allurements.

[.discourse-part]
Question.
What help hath man against this fleshly principle?

[.discourse-part]
Answer.
None of himself; but being freely touched by the other principle, and tasting thereof,
he is to wait on God`'s mercy and grace for the manifestation of his light and power,
to discover to him the evil nature and course of his own heart,
and to cut down the corrupt desires, reasonings, and imaginations thereof.

[.discourse-part]
Question.
In what way is this effected upon the heart?

[.discourse-part]
Answer.
In the heart`'s belief of this principle, and in its obedience thereto.

[.discourse-part]
Question.
How may a man come to believe in this principle?

[.discourse-part]
Answer.
In feeling its nature, in waiting to feel somewhat begotten by it;
in this its light springs, its life springs, its love springs, its hidden power appears,
and its preserving wisdom and goodness are made manifest
to the soul that clings to it in the living sense,
which its presence and appearance begets in the soul.

[.discourse-part]
Question.
How may a man come to obey this principle?

[.discourse-part]
Answer.
In the faith, in the eying of it, in the clinging to it,
the strength issues from it into the creature,
which maketh it able to perform all that it calleth for.

[.discourse-part]
Question.
How come persons to be so weak, and to complain so much for want of power,
who feel a true beginning of life, and earnest breathings after God?

[.discourse-part]
Answer.
From the enemy`'s interposing of reasonings between them and their faith.
The darkness, the principle of unbelief, lies near,
and is still raising mud (as much as possible) between
the principle of life and the soul:
and so far as it can come between,
it disturbeth both the motions of the soul towards its spring or principle of life,
and also the spring`'s clear bubbling up in, and running through the soul.

[.discourse-part]
Question.
What is to be done in this case?

[.discourse-part]
Answer.
The soul is to wait God`'s seasons of deliverance from these,
and to hope for a hidden support from his grace,
while the visitations and leadings of his life are not made manifest.

[.discourse-part]
Question.
What ground is there for this hope?

[.discourse-part]
Answer.
There is ground of hope for the creature in God`'s goodness;
who naturally loveth and seeketh after the souls which he hath made,
and doth not readily nor easily cast off in any of his dispensations.
Besides, where he hath begotten somewhat, and where the bent of the heart is towards him,
and the desire after his pure life and spirit above all things kindled,
there hath he laid the foundation of a building, which,
though at present it may lie in the dust, and under heaps of ruins, he cannot forget.

[.discourse-part]
Question.
Are there other commands besides these common to all men?

[.discourse-part]
Answer.
Yes; according to that dispensation of life and mercy unto which they are called,
and into which they are admitted by the love and kindness of God,
which overspreadeth all his works,
and who forgetteth not his creatures in their estate
of separation and alienation from him.

[.discourse-part]
Question.
Are there then more dispensations of life and mercy than one?

[.discourse-part]
Answer.
Yes. For though the life and mercy in itself is but one;
yet it hath several ways of seeking out after, and gathering into itself,
the lost sons of Adam.

[.discourse-part]
Question.
What have been the chief ways of dispensing the light of life towards mankind?

[.discourse-part]
Answer.
First, By a secret shining into their hearts.
Thus the soul of the Lord holdeth forth some beams of his eternal light to all mankind,
according to his pleasure,
at some time or other visiting the darkest corners of the earth,
and making some way therein for the scattering of that darkness
which separates the soul from the light of life,
and from the sweet presence and enjoyment of its Creator,
which naturally flows into every soul in its believing and obeying of that light.

[.discourse-part]
Question.
Were ever any thus gathered to the Lord?

[.discourse-part]
Answer.
The Lord is able to make any dispensation of his life effectual.
And as many of the Jews were not gathered by the law,
so many of the Gentiles might be gathered without the law.

[.discourse-part]
Question.
But the law gave the knowledge of the Messiah to come through faith,
in whom was the remission of sins known, and strength against sin.

[.discourse-part]
Answer.
The knowledge of Christ runs along in all the dispensations of the eternal light:
the light cometh from him, and it manifests him in spirit;
and the remission by his blood is spiritually known
in the soul feeling the living virtue thereof.
The law and the gospel are both known in spirit, wherever the eternal light visiteth,
and is received.

[.discourse-part]
Question.
What are the commands common to those?

[.discourse-part]
Answer.
They are known to those who are thus gathered, who, in the life thus dispensed,
feel the leadings of it,
and in its light are sensible of those requirings which universally
stream forth from it among those that are thus gathered.

[.discourse-part]
Question.
What other way of dispensing the light of life hath there been?

[.discourse-part]
Answer.
That of the promise to the fathers, which was before the law,
wherein they saw the day of the Messiah, and were glad.
This was a glorious dispensation, in which they tasted the Sonship,
and felt power to walk with God, and faith to trust him in his leadings,
and were translated by him (in a sweet and precious degree) into the measure of his life,
which made them pilgrims and strangers in this world,
and steered their spirits towards another country.

[.discourse-part]
Question.
What were the commands common to these?

[.discourse-part]
Answer.
They were seen by them in the streamings forth of that dispensation of life among them;
a taste whereof the quickened spirit may have,
in reading the words concerning them up and down the Scriptures.

[.discourse-part]
Question.
What further dispensation of life hath there been?

[.discourse-part]
Answer.
That of the law to the Jews.

[.discourse-part]
Question.
Was that a ministration of life?
Was it not rather a ministration of death and condemnation?

[.discourse-part]
Answer.
It proved so in its effect, through the weakness of their state;
but its natural tendency and proper effect, in case of obedience thereto, was life.
And also in the midst of its administering death and condemnation,
it pointed to him who was the justification and the life;
insomuch as the law was kind to them in slaying them,
and serviceable to the life of such souls as kindly received the stroke thereof,
and fled to the hope set before them.

[.discourse-part]
Question.
What were the common laws amongst these?

[.discourse-part]
Answer.
They are to be read in the writings of Moses and the prophets,
wherein God`'s law and testimonies were abundantly given forth to that people.

[.discourse-part]
Question.
Have there been yet any further dispensations of life?

[.discourse-part]
Answer.
Yes; that of the gospel,
before the apostasy and falling away from the living truth and power of the Spirit,
into man`'s wisdom, inventions, and imitations.

[.discourse-part]
Question.
What were the laws common to these?

[.discourse-part]
Answer.
They may be read in the writings of the evangelists and apostles,
where the record of this ministration is to be found.

[.discourse-part]
Question.
What hath the ministration of life been since the apostles`' days?

[.discourse-part]
Answer.
Very low, very weak, very dark, very hidden, exceedingly retired;
yet true children have been begotten, and food hath been handed to them from the Father,
and they have been nourished up in the faith,
and have kept the commandments of their day, and died in the faith:
and those who have thus been led and preserved, their souls are at rest,
and in the peace of God.
But these have not been in any particular, distinct gathering,
and clear separation out of the world;
but scattered up and down in several mistaken forms,
and loaded with the inventions of the earthly wisdom,
and with the bondage and weight of corruption, not knowing that clearness of spirit,
and victory over sin, by the presence of the life,
which was felt and enjoyed by the Christians before the apostasy.

[.discourse-part]
Question.
Had these any common commandments?

[.discourse-part]
Answer.
Not so distinctly as the former; for they lying in a heap of confusion in a wilderness,
or chaos, scattered in the mists and fogs of antichristian darkness one from another,
had not such common beams of light, or clear streams of life running among them,
as those that had a more distinct gathering.
Yet some testimony for God, and against the corruption of the times,
according to what was in their day and age to be testified for and against,
did run among every sort (of such as were true-hearted) in some kind or other.
And for this they were hated and persecuted by men, (even by such as were formal,
and of another spirit) and also dearly tendered and beloved of the Lord.

[.discourse-part]
Question.
Hath there been any further dispensation of life since the apostasy?

[.discourse-part]
Answer.
There is another begun, whose glory is to exceed the former,
after the darkness (which overspread and clouded the beauty of
the former) is expelled by the growing brightness of this appearance.

[.discourse-part]
Question.
How may it appear that there is another?

[.discourse-part]
Answer.
There is no knowing this dispensation but by being gathered into the light of it.
Wisdom hath been alone justified of her children in former ages,
and she can be justified by none else, in her appearance in this age.

[.discourse-part]
Question.
What is the difference of this from the former?

[.discourse-part]
Answer.
It is more inward, more retired,
more closely depending upon the principle of life in the spirit, than the former.

[.discourse-part]
Question.
Is it then the same in substance?

[.discourse-part]
Answer.
Yes, the very same.
The very same truth of Christ Jesus, the very same building of God in the spirit,
the very same church is to be again brought forth; but in greater glory,
that being now to be left out whereby the enemy then entered; and also degrees of beauty,
strength and perfection being to be added.

[.discourse-part]
Question.
But surely a greater glory than that in the apostles`' days is not to be expected; nay,
it is not the belief of many that ever that shall be restored.

[.discourse-part]
Answer.
This ariseth from the unbelief,
and want of the sight of the thing by the right eye in the true light.
For the travel of the eternal Spirit in its dispensation is towards perfection;
and after the darkness of antichrist,
the brightness of the light of life is to shine more clear than ever,
as is abundantly testified in the Scriptures (especially in the book of the Revelations),
and also seen by many in the clear openings of the same eternal Spirit.

[.discourse-part]
Question.
Are there any common commands given forth in this dispensation?

[.discourse-part]
Answer.
Yes, unto all who are gathered in the Spirit of it.
They all feel the same common commands unto several things,
according to the nature and drift of this dispensation.

[.discourse-part]
Question.
What are they?

[.discourse-part]
Answer.
They are many, and concern many things; to wit,
their meetings to worship and wait on the Lord, who hath visited and gathered them;
together with their way of worshipping,
as also their converse and conversation amongst men, etc.,
which are not easily specified:
neither indeed are they fit to be held forth to man`'s disputing wisdom;
but to be waited for in the Spirit, where the light of them is evident,
and the strength to perform them received and held.

[.discourse-part]
Question.
But how may men know that these are true commands of the Lord,
and not imaginations or opinions of their own?

[.discourse-part]
Answer.
When the principle of life is known, and that which God hath begotten felt in the heart,
the distinction between what God opens and requires there,
and what springs up in man`'s wisdom, reason, and imagination, is very manifest.

[.discourse-part]
Question.
Are there particular commands to particular persons besides these?

[.discourse-part]
Answer.
As every heart hath its own particular state,
which is only fully known to the Spirit of the Lord,
who is the leader of the soul out of its darkness and captivity,
and the exerciser of it in what he judgeth proper to its present state;
so the Lord giveth out particular commands as he pleaseth,
either to do or forbear such a thing, as he judgeth it necessary for the soul.

[.discourse-part]
Question.
How may these be known?

[.discourse-part]
Answer.
By coming into acquaintance with the Lord, and the movings and voice of his Spirit.
First, the quickenings of the Spirit of the Lord are to be received into the heart;
then the eye fixed, in that which is quickened, on him that quickened it,
and all the inward senses waiting upon him, and exercised towards him.
Thus the sheep come to know the voice of the Shepherd,
and to follow his leadings into the pastures of life,
and out of the paths and feedings of death, and are drawn on by him towards any thing,
or stopped by him from any thing, at his pleasure.

Oh that the sons of men knew their God,
and were gathered into any living dispensation by him,
wherein they might have the true sense and seeking of him!
Oh that men`'s souls were awakened to feel the want
of the breath of life from whence they came!
Oh that the seed of Israel were redeemed by their God,
that their glory and beauty in his pure life might awaken the nations!
O God, hasten thy work in the world! bring the glory and wisdom of man into contempt,
and bring forth thine own glory and wisdom in its pure brightness.

[.old-style]
=== Some Questions and Answers / Concerning the Seed of Israel, and the True Church

[.discourse-part]
Question.
Who are the seed of Israel?

[.discourse-part]
Answer.
They who are begotten of the Spirit and nature of
the eternal Father and fountain of life,
out of the spirit and nature of this world.

[.discourse-part]
Question.
Are there such a seed in the earth?

[.discourse-part]
Answer.
Yea, and have always been, who have still been the blessing of this world,
though constantly hated and persecuted by it.

[.discourse-part]
Question.
Why are they hated by the world?

[.discourse-part]
Answer.
Because they are not of the world, but faithful witnesses against it, testifying unto it,
that its ways are evil, and its end misery.

[.discourse-part]
Question.
Why do they thus testify?

[.discourse-part]
Answer.
It is their nature, and God calleth them thereunto.
He hath set up his light in their hearts, to shine forth in the world,
and scatter the darkness.

[.discourse-part]
Question.
How do they scatter the darkness?
Doth not the darkness rather scatter them?

[.discourse-part]
Answer.
The darkness doth indeed often prevail against them outwardly,
hunting and scattering them up and down upon the face of the earth;
but they still prevail inwardly, in the testimony of men`'s consciences,
over the darkness; who, at one time or other,
are generally made to acknowledge in the secrets of their hearts that they are of God.

[.discourse-part]
Question.
Why doth the Lord suffer it to be thus, that that which is precious, and of him,
should be trodden under foot by that which is not of him?

[.discourse-part]
Answer.
The Lord hath his season for the discovery of all things.
He hath given the kingdom of darkness its time and power to reign over the just,
and to keep the holy seed in bondage and captivity;
and he hath also appointed his suffering seed its
season of suffering in all ages and generations.
And by these, and through these, the nature of each is discovered, their ends,
and their suitableness to their ends.

[.discourse-part]
Question.
But shall this holy seed always suffer in this world?

[.discourse-part]
Answer.
Nay, not so; for the Lord hath a day to raise the just into dominion over the unjust,
even here in this world.

[.discourse-part]
Question.
When shall this be?

[.discourse-part]
Answer.
When the malice and persecution of the enemies of the pure seed are filled up,
and the measure of its sufferings finished.

[.discourse-part]
Question.
Where are this seed?

[.discourse-part]
Answer.
They are (as yet,
for the generality) scattered up and down under the face of the whole heaven.
Not to be found in a visible body gathered together; but scattered up and down,
here a few, and there a few; here one, and there another.

[.discourse-part]
Question.
Were they then once in a body?

[.discourse-part]
Answer.
Yea, they were once embodied: for after God had cast off the natural seed, the Jews,
he gathered the spiritual seed, into a body, setting them as a city on a hill,
and making them the light of the world.

[.discourse-part]
Question.
How came they afterwards to be scattered?

[.discourse-part]
Answer.
The dragon hath done this, God suffering him many ways to assault this building,
and so far at length to prevail over it,
as even to scatter his church out of her built-state, into a wilderness-state,
where no eye can discern her any more, but that which is of God.
(Wait to read Rev. 12. in the light of that Spirit which wrote it.)

[.discourse-part]
Question.
Why did God suffer the dragon to prevail over so precious and glorious a building?

[.discourse-part]
Answer.
Because there was somewhat of the power of darkness necessary to be made manifest,
which could not be otherwise so made manifest as by this its prevailing;
and also that he might show the necessity of,
and make way for the bringing forth of that,
over which the power of darkness cannot prevail.

[.discourse-part]
Question.
Is there then such a thing to be brought forth?

[.discourse-part]
Answer.
Yea, there is a church, there is a spiritual building,
against which the gates of hell can never prevail; which is so united to the rock,
that the powers of darkness can by no means come between the rock and it.

[.discourse-part]
Question.
Are this church and the church in the apostles`' days different, or the same?

[.discourse-part]
Answer.
This church hath been in all ages;
but a more full and perfect bringing forth in the apostles`' days than in any age before:
yet not such a bringing forth outwardly, as might not be driven back.
And therefore did the Lord suffer it to be assaulted and prevailed over,
in that wherein it was weak through the outwardness of it,
that (after many days) he might manifest his strength in bringing it forth more perfectly.

[.discourse-part]
Question.
Where hath this church been these many ages,
since the dragon`'s sore assault and overcoming it, as to its outwardness?

[.discourse-part]
Answer.
In the wilderness.
Rev. 12.

[.discourse-part]
Question.
What wilderness?
Any outward, visible wilderness?

[.discourse-part]
Answer.
It is a parable,
representing the scattered state of the seed after
God`'s presence was withdrawn from the visible building,
and it laid waste as to its life, and the appearances of his Spirit,
and the dragon got into, and seated in, the form, 2 Thess. 2:4.
then the seed and appearances of God were to be found elsewhere,
and not in those buildings.

[.discourse-part]
Question.
How were those churches or buildings in the apostles`' days laid waste?

[.discourse-part]
Answer.
The presence of the life and power makes the form living;
and no longer is it or can it be so, than the life and power remain with it.
Now they not abiding in the life and in the power (the apostasy coming, spoken of,
2 Thess. 2:3), the life and the power also withdrew from them,
and left them the dead form, into which the prince of death immediately enters;
and so that which was a church unto God while the life abode there, and they in the life,
becomes a synagogue of Satan, he entering into the dead form,
and being worshipped there in the dead form.
So that it is not any outward gathering or profession
that makes a church under the New Testament,
but only the life and power.
That gathering which is in the life and power is a true church; that which is not,
is a synagogue of Satan, let them profess what they will.
For the living God dwells in living temples only,
and the prince of death dwells in all the territories of death.

[.discourse-part]
Question.
According to this rule there are, or have been,
few true churches of God in the world since the days of the apostles.

[.discourse-part]
Answer.
The true church hath been in a wilderness-state since the days of the apostles.
A scattered seed have her children been, and she a widow forsaken;
God providing a place for the inward part of his building,
and giving up the outward part to the formal spirit,
to the possession of the powers of darkness.
Read Rev. 11:1-2. The Lord, by the withdrawing of his Spirit,
took down his own building, gave up the outward court to the Gentiles,
removed the inward temple, altar, and worshippers into the wilderness.
And since that time, men have built many buildings,
in the imitation of that which God built (every sort according to their skill,
and reasonings of their wisdom about the thing); but they are not the same building.
But the true building, the true church, is reproached by all these builders,
and not known to be the thing, because hid from their eye.

[.discourse-part]
Question.
When shall this true church appear again?

[.discourse-part]
Answer.
When God, who gave her the wings of an eagle to fly into the wilderness,
bringeth her the same wings again to fly out.
Then shall she come forth clothed with the sun again, with the moon under her feet,
and with her crown of stars.

[.discourse-part]
Question.
How may it appear that those present buildings which
are to be found in the world are not the true churches?

[.discourse-part]
Answer.
Because they are built by men,
and their strength stands not in the demonstration and power of the Spirit,
but in the wisdom and power of man; take away that,
they soon crumble and moulder of themselves.
Beside, they are not clothed with the sun, have not the moon under their feet,
nor know not the travail to bring forth the man-child,
which the true church knows even in the wilderness.

[.discourse-part]
Question.
Why do men keep such buildings, and not rather mourn after the true building of God,
which is built and preserved in the light and power of his Spirit?

[.discourse-part]
Answer.
Antichrist`'s time is not yet fully ended,
nor the mists wherewith he blinds men`'s eyes scattered,
nor the cup of his fornications (which makes everyone drunk
and besotted as to the sight and knowledge of the true church,
which drinks of it) taken from men`'s lips.

[.discourse-part]
Question.
How may I know the true church?

[.discourse-part]
Answer.
By being born of God`'s Spirit,
and looking with that eye which he gives to those whom he
begets in that light of life which shineth from his presence:
here his holy church and true spouse is discerned and distinguished from all false resem-blances,
and vain pretenders.

[.discourse-part]
Question.
Are there then many resemblances of the true church, and pretenders to be such,
which are not so indeed?

[.discourse-part]
Answer.
Yes; there is the mother of harlots, Rev. 17:5. and her many daughters;
all which pretend to be the true churches of Christ, but want that life in themselves,
and that union in spirit with him, which alone can make such.

[.discourse-part]
Question.
What makes a true church?

[.discourse-part]
Answer.
That alone which makes a spiritual body, and which unites that body to the head.
There must be a true nature, and the union of that nature to the head,
or there cannot be a marriage in spirit to the Lamb.
Now the true church is Christ`'s spouse, _bone of his bone, and flesh of his flesh,_
as truly of the seed of Abraham after the spirit, as the Jews were after the flesh.
And _as he that saith he is a Jew,_
but wanteth the true circumcision of the heart and spirit, doth but lie,
and is not indeed so; so _they that say they are a church,_
but want the nature of the _church,_ they also lie,
and are not a true gathering of Christians out of the world, but a synagogue of Satan,
still abiding and worshipping in the spirit of the world. Rev. 2:9.
and chap.
3:9.

[.discourse-part]
Question.
May not the true church be known by outward, visible marks,
as most persons describe and seek to find and distinguish her by?

[.discourse-part]
Answer.
No; not possibly in her wilderness state, nor hardly in her built-state.

[.discourse-part]
Question.
Why not possibly in her wilderness-state?

[.discourse-part]
Answer.
Because there she is stripped of them, and the harlots, or false churches,
are clothed with them.
Mark the thing:--In the very apostles`' days,
the false ministers and false Christians got into the form, and denied the power. 2 Tim. 3:5.
Now after a season God leaves the form to them, Rev. 11:2.
gathering his church out of that appearance into the hidden power.
Here is the wilderness into which the church fled; the life, the power,
which before appeared in the form, being withdrawn and separated from the form,
and the living seed gathered into it, and worshipping in it.
And who can now find the church, or learn the worship?
Here the eye of the seed is tried, and the wisdom of the spirit of the true disciple.
And here, ever since, all the world have been jangling about the form,
while the true witnesses have been mourning after the power,
testifying concerning the power, and enjoying what was to be given forth of it,
in the present way of its dispensation in the wilderness.

[.discourse-part]
Question.
Why hardly in her built-state?

[.discourse-part]
Answer.
Because even then such variety of resemblances and
likenesses of the true church may be built,
as cannot be distinguished from the true itself by any outward marks.
There were in the apostles`' days false apostles, false ministers, and false churches;
which, though they appeared as the apostles of Christ, as ministers of righteousness,
as the churches of Christ, yet they were not so, but false prophets, deceitful workers,
and synagogues of Satan.
Now they which intend to deceive, appear most exactly in the form,
and with the outward marks, if need require; and that which is true and substantial,
is not so regardful of the outward form, but minds the inward life, truth and substance.
He therefore that judges by the form and outward marks,
cannot but judge that to be the true spouse which appears most in the form,
and with the outward marks, and so is very liable to be deceived and err,
by judging some of the false churches to be true, and the true to be false.

[.discourse-part]
Question.
What am I to do when I know the true church?

[.discourse-part]
Answer.
To wait in that which gives to be a member of it, and gives true union with it,
whether it be in the wilderness-state, or in its built-state.
For the same Spirit, which begets the child in the true life,
will also lead to the church;
and in that wisdom which is from above the true church will never be missed of;
but in the earthly reasonings and guessings of man`'s wisdom,
God`'s church (or New Testament building in the power of his Spirit) is easily missed.
And he that misseth of this, and is out of the pale of it,
is it possible he should meet with the true salvation?
"`He that hath an ear to hear,
let him hear;`" and he that hath but so much as the heart of a man, let him consider,
for the thing is of great weight, and of deep concernment to the soul.

Well: have but patience awhile,
and the true church (which God`'s Spirit builds) shall be known,
and all the false churches of men`'s building shall be known also.
And that which God hath built shall have the power from God, and the praise among men;
and all the Babylonish buildings of man`'s confused spirit, and inconsistent wisdom,
shall vanish away like smoke, and become a stink in all nostrils.
For strong is the Lord God of heaven and earth,
who is confounding Babylon in all her gaudy attire, and glorious appearances,
and raising up his Zion out of the dust.
Amen, hallelujah!

[.old-style]
=== Some Further Questions and Answers / Concerning the Seed of Israel

[.discourse-part]
Question.
Out of what womb doth the seed of Israel spring?

[.discourse-part]
Answer.
Out of the nature of eternal life, out of the bosom of eternal love,
out of the Jerusalem which is above, which is free,
and the mother of all that are born of the Spirit.

[.discourse-part]
Question.
By what covenant are the children of Israel brought up?

[.discourse-part]
Answer.
By the covenant of faith in the love of the Father, which gives life and strength to obey.

[.discourse-part]
Question.
Is there obedience required in the new covenant?

[.discourse-part]
Answer.
Yes; the obedience of faith, the subjection of the nature and heart of the child,
to the nature and will of the Father;
which is as fully natural in the substance as it
can be represented in any figure or shadow.

[.discourse-part]
Question.
What if there be disobedience?

[.discourse-part]
Answer.
The seed itself cannot disobey; but the vessel in which it is sown,
and to which it is united, may prove weak, frail, brittle, yea, sometimes stubborn;
the weight and chastisement whereof the seed also bears,
and in patient suffering helps and cleanses the vessel
through the virtue of the blood of Jesus,
which is felt in the seed which comes from Jesus.
And here is the blood of sprinkling known in the soul,
which cleanses the conscience from dead works, and washes away the iniquity thereof.

[.discourse-part]
Question.
Can any fall from this covenant?

[.discourse-part]
Answer.
The covenant is with the seed forever, and with the seed`'s seed also is it firm;
but the streamings forth of the light of the covenant do not always beget a seed,
but only sometimes set man`'s nature on work, drawing forth the faith, love,
and obedience thereof.
Now this will not hold.
All flesh is grass, and at one time or other will fade and wither;
but there must be a being begotten of the Word, to live and abide forever.

[.discourse-part]
Question.
How is this begetting?

[.discourse-part]
Answer.
In the weakening of man`'s strength day by day, and raising up the seed,
which seed gives life and strength to him that is weakened in the manhood.

[.discourse-part]
Question.
How is this done?

[.discourse-part]
Answer.
First by drawing forth what is in the man, and then by trying its strength,
distressing the man with exercises beyond him.
Thus the working man is brought down by the requirings of the law,
they being too hard for him, and the believing seed is raised up; who,
in the virtue of the living faith (whereof he receiveth
supplies from the breath of eternal life),
fulfils the righteousness of the law in the man,
and also communicates a righteousness of a higher nature unto him.

[.discourse-part]
Question.
Why doth God take this course with man?

[.discourse-part]
Answer.
It is proper and natural.
How can a higher principle be raised in man, but by the death of the former?
And how can the former die, but by such exercises, trials,
and distresses as are proper to wear out the strength of its nature,
and bring it into the nothingness, where that which is, springs up;
when it hath brought down that which appeared, but was not?

Oh! who can understand God`'s works in the world?
Who can read the mystery of life and death in man?
Oh, what a worm is man before his God!
What is his nature?
In what state is he able to walk with his God?
God can keep covenant with man in any kind of dispensation; but man still fails:
his heart deceives him, and he is not able to attain unto,
or maintain any considerable proportion of, happiness to his soul by his covenant.

[.discourse-part]
Question.
What is man`'s covenant?

[.discourse-part]
Answer.
That which his nature desires of God to make him happy.
That light, that counsel, that strength,
that presence which his nature thinks sufficient, will not carry him through.
Nay, let God show grace and mercy, and add helps unto him in the riches of his love,
yet this will not do.
How doth man fall in every dispensation, where there is any stress laid on this covenant,
though God is able to be a father and a husband therein!

[.discourse-part]
Question.
What is God`'s covenant?

[.discourse-part]
Answer.
That which his nature sees needful to make man happy in him,
and to keep man in the enjoyment of his happiness.
This, so far as it is dispensed, carries through; and when it is dispensed perfectly,
will bring forth the perfect redemption and happiness of the creature.

Now then that soul that would travel towards life eternal;

[.numbered-group]
====

[.numbered]
_First,_ Wait to feel a principle of life awakened, raised up,
sown in thy earth by the living God.

[.numbered]
_Secondly,_ Wait to receive all the light of life in every kind,
that the Father of lights shall please to cause to shine in thy heart,
from this principle.

[.numbered]
_Thirdly,_ Be content to be tried and distressed, and have thy strength broken day by day,
and thy wisdom confounded, that thou mayest sink into, and pass away in,
the weakness and foolishness which the Lord will bring upon thee,
before the wisdom and strength of his life appear in thee.

[.numbered]
_Fourthly,_ Keep thine eye and heart on the grace that first visited thee,
that there thy footing may be, and thy hopes fastened.
Oh! receive the light still from the hand of grace,
and look up thither for strength to obey the light;
that the earthly man get not a life in the obedience, and thou forget the grace,
and thy need of Christ, the anointed of the Lord;
and so thou live on what thou hast received from God, and not Christ live in thee;
and look upon thy working obedience as the righteousness,
and feel not the righteousness of Christ,
which is the free justification of his life and power,
washing away the guilt of the ungodly!

====

Ah! narrow is the path that leads unto life; none can enter in at it, but the Seed,
and the Seed`'s seed; even that which dies in the creatureship,
in the principle which Adam received from the Lord,
and springs up in the nature and being of this seed.

Read this, O travellers towards the holy land,
with the eye which God creates! that ye may run certainly in his begettings,
in his creatings, in his leadings towards his land of eternal rest;
even in the certain law and power of his endless life,
and not in the uncertain reasonings, imaginings,
and guessing at things by the human understanding.
