== To All Such As Complain that they Want Power

[.heading-continuation-blurb]
Not applying themselves to yield subjection to what of God is made manifest in them,
upon a pretence of waiting for power so to do.

[.section-date]
1661

THE Lord God of eternal power, who made man in his own image,
he stretcheth forth his arm to save and redeem his lost creature;
it is his power alone that effecteth the work of redemption; he quickeneth man,
who is dead in trespasses and sins; he keepeth alive,
and leadeth on the quickened soul in the path of life; he conquereth, scattereth,
and subdueth all the enemies round about the soul, even all the lusts, corruptions,
and temptations, which lead unto, and entangle in, perdition.

Yet the Lord God requireth somewhat of the man whom he saveth,
without which being found in man, and returned to him from man, he saveth him not.

Question.
What doth he require of man?

Answer.
He requireth of man repentance, faith, and obedience.
That he should turn at his call, from the darkness to the light; that he should trust in,
and cleave to the light, but believe the spirit of darkness no more; and lastly,
That he should obey the light, follow the light,
walk in the footsteps of the living towards the land of light;
work the works of God in the light.

Question.
How can man do this?

Answer.
Of himself he cannot: but being touched, being quickened by the eternal power,
being turned by a secret virtue and stirring of the life in his heart,
then he can turn towards that which turneth him.
Being drawn by the life, by the power; he can follow after the life, and after the power.
Finding the sweetness of the living vine, and his soul made alive by the sap of the vine,
his heart can now cleave to, and abide in, the vine,
and bring forth the fruit of the living faith and obedience to the husbandman,
who daily dresseth the heart,
that waiteth in the living principle for further life from the fountain,
that it may bring forth the fruits of life more and more.

Now mark: Is it possible for any man to come to the eternal rest,
that travels not in the path?
Or is there any path, but the repentance, faith, and obedience of the living spirit;
even of the child begotten by the eternal power,
who is taught by the Father to abide and walk in the life and in the power?

God putteth forth his hand all the day long, to fetch home lost man.
He hath given him a talent, a living talent, which is able to work man into life,
and to bring forth the fruits of life in man.
Man overlooks the talent, joins not his heart to it,
brings not forth the fruits of life to the giver, but cries he wants power;
and what is he?
What can he do?
Can he cleanse his own heart?
Can he kill his corruptions?
Can he quicken himself? etc.

Now mark again.
There are several dispensations of God to mankind; in all which,
man (of himself) falls short of the life, of the power, of the glory,
and comes under condemnation.
God lays the blame on man, for not hearkening, for not believing,
for not walking with him.
Man lays the blame on God, and says he wants power.
Look on him who is not obedient to the light,
which he cannot but confess to shine in his heart, and often to reprove him;
ask him why he doth not obey it?
Is not this his plea; that he wants power?
Now let men consider, will this stand before the throne of God?
This is the condemnation, that men do not believe the light of life,
do not obey the gospel of our Lord Jesus Christ,
do not trust and follow the light which would lead them to life,
but trust and follow the darkness, which leads into death,
and into everlasting condemnation.
Their plea is, they want power so to do.
Is this true?

I confess the power doth not so flow forth to man, as man expects it;
but the power of life works man out of death in a mystery, and begins in him as weakness.
There is all the strength, all the power of the enemy,
against the work of God in the heart.
There is but a little thing (like a grain of mustard-seed), a weak thing,
a foolish thing, even that which is not (to man`'s eye), to overcome all this;
and yet in this is the power.
And here is the great deceit of man; he looks for a great,
manifest power in or upon him to begin with,
and doth not see how the power is in the little weak stirrings of life in the heart,
in the rising up of somewhat against the mighty strength of corruption in him;
which he returning towards, cleaving to, and waiting upon the Lord in,
the strength of the Lord will be made manifest in its season,
and he will be drawn nearer and nearer to the Lord,
and his enemies be overcome and fall he knows not how.
But he that waits for such a mighty appearance of power at first, looking so to begin,
and after that manner to be preserved and carried on,
can never in this capacity so much as walk in the path eternal:
nor is not in the way of receiving the power, which springs up as weakness,
and leads on and overcomes enemies in a mysterious way of working,
and not in such a manifest and direct way of conquest, as man`'s wisdom expects.

The seed of the kingdom is sown man knows not how, even by a sound of the eternal Spirit,
which he is not a fit judge of; and it grows up he knows not how;
and the power appears and works in it, in a way that he is not aware of.
He looks for the kingdom, the power, and the life, in a way of his observation,
answerable to the thoughts and expectations of his heart.
But thus it never comes; but in the way of its own eternal motion,
it springs in the hearts of many, and they overlook the thing, and turn from it daily,
not knowing its proper way of appearance, but expecting it some other way.
And thus the enemy holds them in the bands of death,
and they are captives in the strange land, refusing the Prince of life,
in his daily offers of life, because they look not for him thus,
but after another way and manner.
And till this eye of observation be put out in them,
they can never clearly see the appearance of the Saviour to them,
nor feel the efficacy of his saving of them from that,
from which none but he can deliver.

Now for the sakes of such as are single-hearted,
and yet withheld from the enjoyment of the life of God and of his pure power,
through a way of wrong expecting it;
I shall say a little concerning the operation of the power
in quickening and leading on the quickened soul,
as also concerning the way of its springing up in the heart,
and the necessity of this way.
I myself was long withheld from obedience to the light eternal,
in its low appearance of discovering and convincing of sin, through this very deceit,
believing that my condition required the manifest
appearance of a very great power to help me;
and so when sin overcame me, I did only mourn over it,
crying after and waiting for power, but was kept from joining with, and cleaving to that,
wherein the power springs up and manifests itself according to its own pleasure,
quite contrary to the way of man`'s expectation.

The operations of the power are divers and gradual,
according to the condition and necessity of the soul whom it visits,
and reacheth forth its hand unto,

1+++.+++ There is a discovery of the darkness, and of the erring of the heart from God.
This is power; for this should never be in any heart,
could all the powers of darkness there withstand it.

2+++.+++ There is a rising of the heart against the evil, with a desire of deliverance from it,
and of the springing up of the good in such power as might conquer it.
This is a further appearance of power than the former,
and a good beginning towards believing or joining with the redeeming arm,
which all the powers of darkness (with all manner
of subtlety) endeavor to divert the heart from.

3+++.+++ There is an upright frame of spirit begotten,
and a truth of heart formed towards the Lord; from which desires, and cries,
and groans after his life and presence, and for deliverance from the enemy,
and from under the power of his deceit, spring more and more.

4+++.+++ There is a fear begotten in the heart of being deceived by the enemy,
of being drawn from the feeling of, and panting after, the life and power of God.

5+++.+++ There is a hope and trust in the Lord`'s goodness and mercy,
with a daily waiting for his appearance,
for the manifestation of his Spirit and pure presence,
and for the springings up of his fresh life and precious virtue.

6+++.+++ There are overturnings of the enemy, battering down his strong-holds,
breaking of many snares, beating back of many furious assaults,
and causing the plant of life to grow up, and triumph over all the powers of darkness.

7+++.+++ There are secret stayings and upholdings of the heart in the hour of darkness,
when God sees necessary to let forth the power thereof upon the soul,
and to eclipse his own power.
When the enemy buffets, tempts, prevails, and gets ground upon the soul,
is drawing it back under the veil, even into the pit,
and nothing appears near to stop it, or rescue the soul from death,
and from the power of the grave, but the sting thereof enters and deeply wounds the soul;
yet even then the power is near, secretly upholding, preserving,
and watching over the soul; and waiting for the proper season of deliverance.
"`Nevertheless I am continually with thee,
thou hast holden me by my right hand,`" said David,
when his feet had almost slipped into the grievous snare of desperate unbelief,
and murmuring against God`'s dealings with him and the rest of his people.

Many more operations of the power might be mentioned,
even of its tabernacling and glorious appearing in some vessels in various ways,
both delighting itself in the heart,
and also filling the heart with delight and joy in the pure life:
but these things are better enjoyed and sweetly felt, in the silence of the fleshly part,
than spoken of to the ear which is not fit to hear the sound thereof.

Secondly, The way of the power`'s springing up in the heart; which is,

1+++.+++ In its turning from the darkness, in the faith,
and in the pure obedience which flows from the faith.
For as the soul turns from the power of darkness and death,
towards the power of the eternal Spirit of light; so the power meets it, embraces it,
appears to it, and manifests itself in it,
proportionable to its present capacity and condition.
And as the soul, being touched with the living virtue, gives itself up to believe,
and to trust the power which draws; so the power manifests itself in the heart,
according to the proportion of the faith which the eternal virtue hath begotten there.
And as the soul in the faith gives itself up to obey,
so the power appears and works the obedience.
For we can do nothing of ourselves; but being called, being drawn,
being required to do that which is far beyond our strength, and giving up thereto;
the life springs, the power appears, which does the work.
This the Philippians had experience of, to whom the apostle gave that exhortation:
"`Work out your own salvation with fear and trembling; for it is God which worketh in you,
both to will and to do of his good pleasure.`" It is the unbeliever hangs back,
and cries where shall I have power?
But the faith follows the moving and drawing of the Spirit,
and the power never fails the faith.
But that which cries, how shall I get out of Egypt?
Which way shall I ever be able to pass through this intricate wilderness?
How shall I overcome those mighty enemies,
which already have the possession of the land I should inherit,
and are strongly fenced in it, and mighty in strength to keep their hold thereof?
This is not the right seed, this is not the true Israel,
for whom the everlasting inheritance of the life and of the pure power is prepared.

2+++.+++ Under the cross, under the yoke to the corrupt (yea, and to the very natural),
the power springs.
The false birth would have the power spring in a way pleasing to itself,
at the time its wisdom sees necessary, and in the way its will would have it;
but the power springs up according to its own wisdom, at its own time,
and after its own way.
When the man would have it, then it flies from him; and when it is not expected,
nor perhaps desired (at least in that way wherein it chooses to appear),
then it springs up and puts forth itself.
Most men, that have felt any thing of God, cannot but desire his life and power;
but most fly the cross, wherein it hath chosen to appear;
and so they can never meet with it, but are still complaining for the want of it.
In the power is the ease, the rest of the gospel.
Take my yoke upon you, and learn of me, saith Christ,
and ye shall find the rest which flows from the power.
This made Paul rejoice in the cross of Christ,
whereby the fleshly lusts were brought down in him;
and the life and eternal power sprang in the seed of the kingdom:
for under the cross the seed grows up and flourishes, and the flesh withers and dies.
And as the power of flesh and death wastes, so the power of Spirit and life increases.

3+++.+++ The power springs under the fear,
and in the uprightness and love which God hath begotten.
I put these together, for there is a close unity between them.
The fear is the dwelling of the upright heart, and the love is within the fear.
He that distrusts himself, feels his own nothingness,
finds no power to do any thing God requireth,
and yet also fears to stay behind the light of God`'s Spirit, in any thing it requires,
and so finds a putting on forwards in the faith; in him the power delights to appear.
He that would feel strength before-hand, and act in the sense of that strength,
from him the power withdraws; but he that is weak, and hath no strength,
but still as it freely drops into him from moment to moment,
this is the vessel the power chooseth to manifest itself to,
and to be continually appearing in.
This is the new covenant,
"`I will put my fear in their hearts.`" And where the fear of the new covenant is found,
so much life, power, and eternal virtue,
as is necessary for the present state of that heart, cannot be far off.
So in the upright-hearted, in the heart that is true to God,
the power of deceit cannot dwell, but the power of truth delights to fill it,
in a way suitable to the state of the spirit,
and so as may be seen by the eye of the spirit, and felt by the spiritual sense.
And in the love is the constraining power, which constrains from the evil path,
from the path of unbelief and disobedience, into the path of life.

Thirdly, The necessity of this way of the springing up of the power,
and not in such a manifest way as man`'s heart desires, and as man`'s eye expects.

It is necessary in several respects.
In respect of God, in reference to the creature, and in reference to the soul`'s enemies.

1+++.+++ In respect of God.
It is necessary that his power and life should spring up in the creature in its own way,
according to the counsel of his own wisdom, suitable to his own nature,
and not in the way which the creature chalks out, and expects it in.
God must be like himself, and walk in his own path in everything he does.
He is a God that hideth himself in the mystery of his working,
throughout the whole track of man`'s redemption; and man must be wrought out of himself,
out of his own thoughts, expectations,
gathered apprehensions concerning the kingdom and way to life,
and led in a path he doth not know (nor ever can know any longer than he is in it);
and in ways he hath not been acquainted with.
The way of life is still new, every moment fresh and living;
and the earthly part of those,
who may have in some measure felt the power of regeneration, cannot know it,
nor walk in it.
Consider this, O ye that fence yourselves against the present appearance of the Spirit,
and against the convictions, demonstrations, and drawings of its eternal light and power,
by somewhat which ye have formerly felt and known.

2+++.+++ In reference to the creature, the power of God must needs appear thus hiddenly,
and in such a mysterious way.

1+++.+++ That the creature might go through all those exercises of spirit,
which are necessary to fit it for its inheritance in the holy land.
There are straits, wants, trials, temptations, inward weaknesses,
buffetings from the enemy, withdrawings of the life, etc.,
God seeth necessary to exercise the spirits of his with,
that he might fit them for himself, and for a safe enjoyment of his life in fulness;
which could not be,
if there were such a manifest power to begin with and continually at hand,
to perform all in and for the soul, as many men wait for, and think necessary to have.

2+++.+++ That the fleshly part might be thoroughly worn out and destroyed.
When the power appears and works mightily in the soul, there is somewhat apt to get up,
to exalt himself by the power, and to abuse the power;
and if the power were not withdrawn,
and this tormented and famished in the absence of the power,
and in the withdrawing of the sweet appearance of life,
a wrong thing would be stealing into the inheritance,
and the soul would never be thoroughly purified,
nor come to a pure enjoyment of the power.
Therefore doth the Lord appear in this mysterious way,
that the promise might be sure to the seed;
that the seed which is the right heir of the power,
might come alone to inherit the power,
and the false birth not touch the least enjoyment of it,
but feel the bitter strokes of death and destruction from it.
What had become of Paul, if he had had power to resist the buffetings of the enemy,
as he desired?
Would not his fleshly part have remained in the exaltation,
and not have been brought down?
2+++.+++ Cor.
12:7.

3+++.+++ In reference to the enemy.
The enemy could never be wholly conquered, his strong holds in the heart broken down,
and the redemption from under his hand perfected,
were it not for this mysterious way of the appearing and working of the power,
even out of the sight of man`'s eye, and contrary to his will and expectation.
For had man such a power as he desires, still present with him;
had he faith in his power, or obedience in his power,
or could he take up the cross in his power,
or have strength to fight against the enemy as he desires and expects,
the enemy would still find entrance into him, and keep his hold of him.
But God, who knoweth the state of the creature,
with the strength and passages of the enemy into man,
by working with his mighty power in man according to his own will,
and in the way of his own wisdom (contrary to what man can desire or expect,
but as he is taken into, and comprehended in, the eternal will),
carries on his work sweetly, and safely,
and perfects the salvation of those who will not, who run not,
who desire not to be any thing, but wait to feel and know his power,
and to become subject to it, and lie under,
even in the lowest way of its manifestation and appearance.

Objection.
This may be true in the ordinary way of redemption of souls;
but there are deep captivities (even the captivity of Babylon inwardly,
spiritually) which surely will need a very great
appearance of the power of God to deliver out of;
and what can that soul do, but wait there under the captivity,
until the mighty power arise?

Answer.
It is true; the power must needs be very great, and the appearance of it wonderful,
which delivers out of such captivity; but yet the beginnings of it may be small,
and out of the sight of that eye which looks and waits for so great an appearance.
Hast thou not light enough already to begin thy travel out of Babylon?
Hast thou begun thy travel?
Dost thou walk in the light which shineth upon thee in that dark land,
to gather and lead thee out of it?
Or wilt thou not begin to come out,
till the very glory and brightness of Zion shine upon thee?
If there be but light and power enough to lead thee one
step out of the land of darkness and confusion of spirit,
towards obedience to the lowest or meanest truth, that is sufficient for thee at present;
and as thou art found faithful here, more will spring in thee;
but if thou stop here (or at any time after thou hast begun, and made some progress,
because of any thing which falleth out contrary to thy expectation),
then that which should lead thee on, and strengthen thee, stops also;
and thou meetest not with that which is found and enjoyed by others in the way,
because thou passest not on in it, but balkest thy proper path,
judging somewhat more necessary towards thy beginning or progress, than the Lord judgeth,
or yet seeth fit to impart to thee.

Thus the enemy betrays thee, and holds thee in his chains,
which might be loosed and cast off by little and little,
didst thou singly give up to the little appearance
of that light and power which is able to unbind them,
and not expect more at first (or afterwards) than
the Lord hath allotted for thy present condition.
And let me tell thee this from certain knowledge and experience; that thou,
who hast been high, and hast tasted much of God, but hast abused it,
and fed the wrong part with it, both in thyself and others;
thou must be brought lower than the rest, and for a long season be kept lower;
that the pure seed (which hath deeply been buried
in thee) may overgrow and sink all thy knowledge,
experiences, and observations, concerning the eternal life, and its way of appearance,
which formerly thou hadst some true taste of, but now holdest out of the life.

Thou must come down, thou must become nothing by degrees,
thou must lie at the foot of the reprovings of that light,
which thou thinkest thou hast gone far beyond,
and be glad of a little help now and then in the lowliness and humility of thy heart,
which must not choose what appearance and manifestation it will have from God,
before it will begin to follow him, but be glad of ever so little,
that the infinite wisdom sees good to give forth by the hand of his mercy.

Whoever have been high,
and are still waiting and expecting in the heights of their
own wisdom and observations concerning the kingdom,
let them take heed of despising the day of small things,
and know that their proper beginning (yea the very
path of eternal life itself) lies in the lowness,
in the humility, even in that nothingness which bows before the least light of the day,
and with gladness of heart enters into, and walks in it.
For this I certainly know; the wise, the observing eye, the vast comprehending heart,
which waits for such an extraordinary power, judging it cannot begin following the light,
which daily appears to check and reprove,
without some great manifest appearance of power;
this cannot see the low little path of life, which is proper for it to walk in,
and to the end whereof it must travel, if ever it come to sit down in the kingdom,
or to inherit the power of the endless life.
Precious is the dispensation of this age, great is the power and glory which is arising;
but the wise and knowing of this age are shut out of it,
as they have been out of the life and truth of the dispensations of God in all ages.
Happy is he who is not above that, wherewith God visiteth his soul to redeem it.

=== POSTSCRIPT.

THAT persons, who have not travelled into the land of life, want power,
that is out of doubt.
The state of Israel in its travels is a state of weakness and wants.
How can they in the wilderness but want that which is to be possessed in the Holy Land?
But dost thou want power to begin the travel with?
Dost thou want what proportion of power the Lord
sees necessary for thee in thy present estate?
Is there nothing at all discovered to thee which is contrary to God,
either in thy heart or in thy conversation or in thy worship,
which thou dost not so much as strive to give up to the Lord in,
waiting upon him for his power and strength to appear in helping thee?
The light appears to discover and lead out of the darkness:
now in giving up to the light,
and not doubting but that which calls and draws out will give strength,
and enable to come out, the power is met with unawares.
But that which stands gazing and looking out after a power,
which it expects to meet with before it will so much as begin to follow the light;
that cannot but abide in the captivity, and miss of that power which redeemeth from it.
Therefore,

1+++.+++ Wait to feel the light of life discovering and drawing from the evil;
and let it choose what it shall please first to discover and draw from.
And though it be little, and very inconsiderable in thine eyes, yet dispute not,
but where the light first begins to lead, do thou there begin to follow.

Then in this waiting and subjecting to the manifestations of the light,
out of the self-will, self-wisdom, self-knowledge, self-judgment,
in the lowliness and abasedness of the mind and spirit before the Lord,
the begettings of life in the light are felt, and the renewing into his pure image.

Afterwards that which is begotten (and begun to be renewed in the
divine image) is by degrees taught more distinctly to know,
discern, and walk in the path of life.

And after this, to that which is thus begotten,
and taught the living faith and obedience (which is wrought by the mighty power of God,
though running in a low, secret, hidden way, from the eye of the creature),
the great power is revealed, and he grows strong in the power for God,
and against the enemies of his soul; and by this strength and feeling of God`'s presence,
they fall daily and continually before him,
and then his victory over them goes on with joy.

But he that stops at first may grow wise and conceited,
concerning the things of the kingdom after the flesh,
and may hope for great things at last; but by the deceit of the subtlety,
is kept out of the living path, wherein they are to be waited for, reaped, and enjoyed.

Now for the encouragement of such as are willing to travel on in the weakness,
yielding up their members to the present manifestation of the light,
and waiting for the further appearance of the power;
it is on my heart to add a letter of a dear friend and brother of mine in the truth,
who hath been a deep traveller and fellow-sufferer with me formerly,
before this help came forth from the throne of God,
since the day-spring from on high hath vouchsafed to visit us,
and to guide our feet in the way of everlasting peace.

The LETTER is as followeth:--

Dear Friend,

"`My dear and tender love salutes thee, in that love from whence I had my being,
and from whence sprang all my Father`'s children, who are born from above,
heirs of an everlasting inheritance.
Oh! how sweet and pleasant are the pastures which
my Father causeth all his sheep to feed in;
there is variety of plenty in his pastures, milk for babes,
and strong meat for them of riper age, and wine to refresh those that are ready to faint,
even the wine of the kingdom, that makes glad the heart,
when it is ready to faint by reason of the infirmities.
Sure I am, none can be so weary, but he takes care of them; nor none so nigh fainting,
but he puts his arm under their heads;
nor none can be so beset with enemies on every side, but he will arise and scatter;
nor none so heavy laden and big with young, but he takes notice of them,
and gently leads them, and will not leave them behind unto the merciless wolf,
because they are his own, and his life is the price of their redemption,
and his blood of their ransom; and if they be so young that they cannot go,
he carries them in his arms; and when they can feel nothing stirring after him,
his bowels yearn after them; so tender is this good Shepherd after his flock.
I can tell, for I was as one that went astray, and wandered upon the barren mountains;
and when I had wearied myself with wandering, I went into the wilderness,
and there I was torn as with briars, and pricked as with thorns,
sometimes thinking this was the way, and sometimes concluding that was the way,
and by and by concluding all was out of the way; and then bitter mourning came upon me,
and weeping for want of the interpreter; for when I sought to know what was the matter,
and where I was, it was too hard for me.
Then I thought I would venture on some way where it was most likely to find a lost God,
and I would pray with them that prayed, and fast with them that fasted,
and mourn with them that mourned, if by any means I might come to rest, but found it not,
until I came to see the candle lighted in my own house,
and my heart swept from those thoughts, and imaginations, and willings, and runnings,
and to die unto them all, not heeding of them, but watching against them,
lest I should let my mind go a whoring after them.
And here I dwelt for a time as in a desolate land uninhabited,
where I sat alone as a sparrow upon the house-top,
and was hunted up and down like a partridge upon the mountains, and could rest nowhere,
but some lust or thought or other followed me at the heels,
and disquieted me night and day, until I came to know him in whom was rest,
and no occasion of stumbling, in whom the devil hath no part;
and he became unto me as a hiding-place from the storms, and from the tempests.
Then came my eyes to see my Saviour, and my sorrow fled away,
and he became made unto me all in all, my wisdom, my righteousness,
and my sanctification; in whom I was and am complete,
to the praise of the riches of his grace and goodness that endures forever.
Therefore be not discouraged, O thou tossed as with tempests! nor dismayed in thyself;
because thou seest such mighty hosts of enemies rising up against thee,
and besetting thee on every side: for none was so beset and tried, and tempted,
as the true Seed was, who was a man of sorrows, and acquainted with grief.
But be thou still in thy mind, and let the billows pass over, and wave upon wave;
and fret not thyself because of them, neither be cast down,
as if it should never be otherwise with thee: sorrow comes at night,
but joy in the morning; and the days of thy mourning shall be over,
and the accuser will God cast out forever.
For therefore was I afflicted, and not comforted, and tempted, and tried, for this end,
that I might know how to speak a word in due season,
unto those who are tempted and afflicted as I once was;
as it was said unto me in that day when sorrow lay heavy upon me.
Therefore be not disconsolated,
neither give heed unto the reasonings and disputings of thy own heart;
nor the fears that rise therefrom, but be strong in the faith,
believing in the light which lets thee see them,
and his grace thou wilt know to be sufficient for thee,
and his strength to be made perfect in thy weakness.
And so thou rather wilt glory in thy infirmities, that his power may rest upon thee,
than in thy earnest desires to be rid of them;
for by these things thou wilt come to live in the life of God, and joy in God,
and glory in tribulation, when thou hast learned in all conditions to be contented;
and through trials, and deep exercises, is the way to learn this lesson.
These things in dear love to thee I have written,
being somewhat sensible of thy condition, and the many snares thou art daily liable unto;
therefore watch that thou fall not into temptation,
and my God and Father keep thee in the arms of eternal love, over all, unto the end,
unto his praise; Amen.

John Crooke`"
