[#zealous-professors, short="Queries to the Strict and Zealous Professors"]
== Some Queries / To the Strict and Zealous Professors of this Age

[.heading-continuation-blurb]
(such as stick in the letter, but are strangers to the life and power),
to provoke them to jealousy,
lest the heathen and open sinners outstrip them and enter into the
kingdom of the pure everlasting light before them.

Query I. WHETHER God, since the fall of man from the purity and glory of his state,
doth truly and really desire the salvation of all mankind;
and so would have them come to the knowledge of the truth, that they might believe it,
receive it, walk in it, and so obtain salvation thereby?
Or whether he would have only some few of them to receive it, and be saved,
and the rest to perish?

Query II. If God would have all men to be saved, and come to the knowledge of the truth,
which is the means of salvation,
then whether there is sufficient done by God to convey
the knowledge of his truth to all men,
so as they may come to the knowledge thereof and be saved?
Or whether there is such a defect on God`'s part,
that some men never had sufficient means to come so far to the knowledge of his truth,
as that they might come into that way of salvation thereby?

Query III.
Though God doth please to add superabundant means, in the riches of his grace,
towards some, more than others; as to the Jews under the law,
and to the disciples of Christ under the gospel;
yet whether there is not so much light of the Spirit communicated to all, as,
if followed, might lead them out of the darkness, and from under the power of it?

Query IV. Whether God be not so near to every man,
as that possibly he may seek after him, and find him?
And if he do find him, and his heart cleave to him,
whether it can possibly be but virtue should issue forth from God,
to draw him out of the alienation from him, and out of the power of sin, death, and hell?

Query V. Whether, if a man feel God, and cleave to God,
and begin to discern the streamings of light from him, and follow the Lord therein,
whether God will not accept this man therein?
And whether his divine light let into him (being believed
in and obeyed) will not purify him from darkness,
unbelief, and disobedience?
And whether God will not impute to this man what
Christ performed on man`'s behalf in the flesh,
he being in unity with, and in subjection to,
the light and power whereby it was wrought (wherein is the fellowship with the blood,
and wherein alone it washeth from the sin),
though as to the outward knowledge of what was outwardly done,
the man may possibly be ignorant?
And seeing it is not absolutely necessary towards
the involving in the guilt of Adam`'s sin,
the outward knowing what Adam did; but the proceeding from, and being found in,
the same spirit and nature, doth sufficiently convey it; so whether being gathered into,
and found in, Christ`'s spirit, even in faith, obedience,
and subjection to the light thereof in the heart,
whether this is not also sufficient to convey the righteousness of Christ?
And whether God will fail to impute it to that man?

Query VI. Whether true religion, spiritual worship, and the salvation of the soul,
do not depend upon the Spirit of the Lord,
who is near to every heart with his eternal light,
which he can easily convey to any heart,
whose ear is opened to hearken to his breathings and drawings?
So that it is easy to the Lord to save any of the sons of men,
even in the darkest and remotest corners of the earth;
and he can cast off those who seem highest in zeal,
and most flourishing under any outward means of salvation.

Oh, wonderfully infinite is the Lord!
Who shall bound his Spirit?
Happy is he that feareth before him, and in his fear learneth to depart from iniquity,
and walk in the good path that his Spirit teacheth.
He is near to God, and shall taste of the good things,
and shall not be rejected for want of outward knowledge;
but whatever was done for lost man,
he that is found in the light of life (and in the obedience
to the Spirit of life) shall reap the benefit of;
but he that boasts in his knowledge of these things, and of his faith in Christ Jesus,
yet not being found in the true, living, eternal light of the Spirit (but an enemy to it,
and ignorant of it), the Lord will rend his confidence from him,
in a day that he is not aware of.

Glorious was the dispensation of the law,
and great was the advantage to the Jews thereby above the Gentiles;
yet they missing the Spirit and life of it (and growing wise in their own apprehensions,
and interpretations about it), fell beneath the Gentiles,
becoming greater strangers to the power and wisdom of God,
and harder to be reached and brought in under the subjection of the gospel.
More glorious was the dispensation of the gospel to the Christians,
and much greater was their advantage than that of the Jews; but an apostasy coming,
and they losing the true power and Spirit,
and growing wise by a literal knowledge of some of the things of God in the earthly part,
and forming interpretations of scriptures, and entering into practices in that wisdom,
they are now become at as great a distance from this powerful
visitation of God by his Spirit (which raiseth the seed,
and springeth up freshly in the hearts of those,
whom the Lord our God doth call out of their fenced cities,
and allure into the wilderness) as the Jews were
at from that appearance before the apostasy;
and in as great danger are the children of the kingdom to be cast out now as then.
Oh that my God would please to open the ear of some tender
and upright-hearted among them to hear this testimony,
that they might no longer stumble at that, which alone is able to lead them to God,
and to make them happy in God.

Is there any uniting with God, or enjoying of God, but by his Spirit?
Is there any receiving of God`'s Spirit but within the heart?
Doth he not appear there by his light, and in his power?
What if God please to give forth a measure of his
eternal light in the heart of his chosen,
to open that to them which they could never see before,
and to bring them into a nearer unity with him than ever they knew before,
may he not do it?
Nay, is not such a thing needful to help out of the deep and intricate apostasy,
wherein have been so many twistings and twinings of the
subtle serpent about every step or appearance of reformation,
and to gather the wandering sheep, who were scattered up and down,
and sorely distressed for want of the tongue of the learned
to speak a word in season to their estates and conditions?
Have not every sort bent the Scriptures in the reasonings of their own minds,
and made them speak according to their own heart`'s lusts?
And is not every one wise in his own eyes, and strong in his own tower and fenced city?
Surely there was great need of an appearance of the Lord to shut out the wisdom of man,
and to help the poor, the needy, the fatherless, the weak panting babes.
And blessed be the Lord God, who hath appeared;
and blessed are those who have seen his light,
and bowed at the feet of his living appearance, and felt the virtue of his saving arm,
scattering their lusts and corruptions; yea,
also raising up and bringing forth his pure seed in the fresh power, dominion,
and authority of his perfect life,
which reigneth in the hearts which the Lord hath regenerated and sanctified forevermore.

O my friends,
my friends! that that eye might be once blinded in you which hinders the sight of God;
and the eye opened which beholds his glory,
and also taketh pleasure in his lowest appearance.
The babe alone hath the mysteries of the kingdom revealed to him,
(the wise and prudent are excluded; the birth after the flesh, in every one,
must be famished and destroyed) and he alone can see in the eternal
light this dispensation of the everlasting gospel after the apostasy,
which the Lord hideth from those who are wise in the letter
of the former dispensation of the same gospel,
but cannot read it as it was given forth in the Spirit then,
nor as it is now again held forth in the same Spirit and power.
O my friends! this is the truth to you (wait on the Lord,
that ye may understand it from him): Your right eye must be put out,
(which will never cease offending you, and causing you to stumble,
so long as it is able to see) and all your knowledge which
ye hold out of the life become as dross and dung to you,
if ever ye taste and come to enjoy the excellency and glory
of this appearance of God in his eternal Spirit,
who hath descended from on high into the hearts of his chosen,
to prepare them for his spiritual temple, that he may dwell in them, and they in him.
And he will dwell in them, and they shall dwell in him,
to the full delight and satisfaction of their hearts,
and to the confusion of all those who remain despising
and reproaching this his glorious appearance,
and his people in whom he hath appeared.
The day is not far off, wherein this will be made manifest;
wherein great bitterness and anguish of spirit will
befall those who can only see the glory afar off,
but cannot inherit it, being found in that nature and spirit which is separated from it,
and eternally shut out of it.

ISAAC PENINGTON
