
[#rom14-20, "Some Observations Upon Romans 14:20"]
== Some Observations / Upon that Portion of Scripture, Rom. 14:20.

[.heading-continuation-blurb]
For the service of such in this present age,
whose eyes and hearts the Lord shall please to open,
to see and consider the weight of the truth thereof.

[.heading-continuation-blurb]
With some few weighty words of advice to several sorts of people,
according to their different states.

[quote.section-epigraph]
____
"`For meat destroy not the work of God.`" Rom. 14:20
____

[.section-date]
1662

[.old-style]
=== Observation 1 / God hath a work in some men`'s hearts.

The mighty God, who made heaven and earth, and whose eyes run to and fro through both,
he, by the finger of his pure power, toucheth some of the hearts of the children of men,
and in the pure demonstration of his living Spirit is found working there.
Religion, true religion, is not a matter of opinion (as men,
who have not tasted of the power, are apt to imagine),
but a new creation and work of God in the heart of the creature,
sowing the light and life of his Spirit there,
and by it working man out of the darkness and death of sin
(which is the destruction and misery of the soul),
into his life and blessedness.

[.old-style]
=== Observation II / That this work of God in man is liable to be destroyed.

God could so have made man as that he could not have fallen.
He could so have comprehended man`'s spirit in the pure power of his life,
as that man could not have broke out of it.
But it pleased him to make him under a law, wherein, waiting upon, and watching to,
the power of life, he might be preserved, and remain happy; but departing from it,
he should lose his state, and sink into misery.
God could also so redeem man, as that no power should stop or interrupt his work;
but it pleaseth him also to hold forth a law of redemption, according to which,
his work of redemption may either go forward or backward.
As man is drawn by the Spirit of God, and followeth his leadings out of the corruption,
out of the vanity, out of the earthly nature, out of the wisdom, reasonings,
and spirit of this world, so the work goeth forward.
As man is tempted, hearkeneth unto, and is drawn back by any of these,
from the leadings of God`'s Spirit, so the work goeth backward,
and degrees of destruction overtake and come upon the work of God in that heart.

[.old-style]
=== Observation III / A little thing will destroy the work of God in the heart.

A matter of meat, eating but a little meat doubtingly,
out of the faith (wherein is the preservation from the destruction),
this leads into the sin, where death and destruction is still met with.
For in the path of life, in the faith, in the obedience to God`'s Spirit,
there alone is the preservation of the work of God; but in the unbelief,
in the disobedience, is the doubting (though about ever so small a matter),
there is death and destruction met with,
if the person venture upon that which he doubteth of.
Those who have travelled in the path of life, I know can witness this.
Oh, how small a thing brings a veil over the life!
What a little giving way to the reasonings of the earthly spirit
about a small matter drives back the work of God in the heart,
and brings anguish and misery upon the soul,
causing the hiding the light of God`'s countenance,
which is the life and joy of the renewed spirit!
God is a great king, and all his leadings and teachings are weighty;
and he that rebelleth, or neglecteth in the least thing, must bear his burden;
unless he feel the humiliation of his soul,
and the remission from the spirit of the Lord, the grace of God pitying him,
and the blood of his Son washing him.

[.old-style]
=== Observation IV / No man should do that which tendeth to destroy the work of God in himself, or the work of God in another.

There is no such thing allowable by God for any man to do (whether in public government,
or in any kind of commerce or conversation amongst men,
or in one`'s private course of walking) which tendeth to destroy the work of God.
The intent of government, either in church or state,
was never to destroy the work of God in any man.
Government is of God, both in church and state.
But that way of government which destroyeth his work in any, is not of him;
but contrary to him, and against him.
Oh that men could consider, and had the balance of truth to weigh things in,
that they might bow before the God of truth,
and not strive with their Maker about his work in the world!

My soul hath mourned, I may say, almost from my cradle, about the estate of this creation.
To behold man fallen from his glory, departed from his God,
living without the sense of him,
and sowing the seeds of eternal misery for his poor soul
(which he must as certainly reap as he hath sown,
unless he travel the path of redemption in the powerful
leadings and guidance of God`'s Holy Spirit);
this hath so broken my heart (together with the close exercises
which have continually attended this poor wearied spirit),
that I have often wondered how the natural life could be contained in the natural vessel.

I am a lover of mankind in general, and have been a deep sufferer with,
and traveller for, all the miserable.
None knows the path of my sorrows, or the extent of my bowels, but he that made me.
It is not natural or kindly to me to upbraid any man with any kind of wickedness,
or ever so justly deserved misery;
but my bowels work concerning him towards the spring of eternal power and compassions,
even as I would be pitied and represented to the Father of mercies in the like condition.
Indeed I have been emptied from vessel to vessel,
and tossed with multitudes of storms and tempests;
yet the savor of my life remaineth with me to this day,
and the Spirit of my God breatheth on my heart; blessed be his holy name forever!
And though I walk with one sort of people, because my heart saith (yea,
the Spirit of the eternal God hath witnessed unto me,
and shown me in that light which cannot deceive,
and to that eye which cannot be deceived) that they are the people whom he hath
chosen out of all the gatherings (throughout the earth) from the apostasy,
to manifest his power in, and his presence among; I say,
though I have been guided and led by the Spirit of the Lord to walk among these;
yet am I not bounded there, either in the love, or in the unity of my heart,
but I have unity with the integrity and zeal for God which is in others,
of what sort or gathering soever; and I have tender bowels for all,
even for those which hate and persecute that which is my life,
and hath the love of my heart forever.

Oh! how have I prayed for the lost world!
For all the souls of mankind how hath my soul bowed
in unutterable breathings of spirit before my God,
and could not be silenced until he quieted my spirit
in righteousness and excellency of his will,
and bid me leave it to him.
And as touching this nation, and the several sorts in it,
even those who seem most cast off, and without all sense;
yet the preciousness of their souls have I spread before the Lord my God with tears.

And now I have somewhat to say, in the love of my heart,
and in the shinings of the light of my God, to several sorts of people,
which nearly concerns them;
as those whose hearts are weighty and serious (and who are
not drunk up in the earthliness of the sensual nature,
or misbiased by pre-assumed principles from the wrong ground) may easily perceive.

[.centered]
=== First

[.section-summary-preface]
To such as never knew what belonged to tenderness of conscience towards God,
but have spent all their days either in licentiousness of spirit,
or in a dead formality; to such my soul saith:

Oh Friends! wait to feel the power of God upon your hearts (which
is present with that which sometimes lets you see the evils thereof);
that they may be melted and made tender by him,
fit to receive the impressions of his life.
Why should ye go down to the pit in a dream, and centre in the land of misery?
Ye have immortal souls in these earthen vessels,
which must either be redeemed to God by the power of his life,
or be shut up from his glorious presence in the chambers of death.
It is a dreadful thing to appear before God after death,
and receive the sentence of condemnation for the things done in the body.
Oh that the eye of your souls were awakened,
that ye might see the hazard and danger ye are incurring daily;
and might know the hope of escape set before mankind,
by the appearance of the grace in you,
and learn of the living God to fly thereto for succor,
that ye might be sheltered in the evil hour, which hasteneth apace upon all flesh!

[.centered]
=== Secondly

[.section-summary-preface]
To such as formerly have been tender and sensible,
but are now grown hard and deaf to the voice of God`'s Spirit in their hearts and consciences;
this is the language of my soul in the love and life of my God:

Oh that ye could wait to feel the hammer and stroke of God upon that which is hard,
that it might be broken by him; and that that which is high,
and lifted up above his pure fear (where the law of his life is learned,
and the souls of his saints preserved), might be brought down and abased before him!
Great is your danger; exceeding difficult is your recovery.
Yet there is strength in the arm of the Lord God to strike through your deadness,
and to quicken the immortal principle of his life in you.
Why should ye, who have once tasted of the goodness of God,
become more miserable than the rest of the sons of men?
Why have you departed from that which once gave you a true taste of life,
and of the sweetness of redemption by it,
into that spirit which is sealed up in the death, in the midst of its greatest wisdom,
and surest footing?
Oh, return, return to that which leadeth to the living God,
that ye may travel (in the exercises of his Spirit)
out of the wisdom and spirit of this world,
unto the land of the soul`'s peace and rest!

[.centered]
=== Thirdly

[.section-summary-preface]
To such as are still tender, and dare not but exercise a conscience towards God,
even in these searching and trying times:

Friends, keep your standing in the life of God.
What God hath begotten in you, let it depend upon him.
Let him do what he will with his own in you,
and let the creature be subject to that living principle,
which God hath sown and raised in your hearts;
sell not your peace with God for any ease or advantage in this world.
Let the tenderness of your consciences, which is of value with God,
be precious also in your eyes.
The times and seasons are in the Father`'s hand,
and he seeth good to let this day of trial come upon you.
His grace is able to carry you all through.
It will be for his honor, to let all the world see how dear your God is to you,
and how able you are (in the meekness and strength of the
Lamb`'s Spirit) to suffer for his name`'s sake.
Thy will, O God, be done.
The cup which our Father gives us, shall we not drink it?
The Lord preserve you in uprightness of heart towards him,
in meekness of spirit towards those that afflict you,
and in true love and good-will towards all; that his light, which hath gathered you,
may shine over all the darkness which opposeth it; and his life,
which hath quickened and preserved you,
may be famous over all the territories and dominions of death.

[.centered]
=== Fourthly

[.section-summary-preface]
To such as are hard-hearted, and of a persecuting spirit towards the tender-conscienced:

Oh that ye knew what ye did!
Ye are enemies to the most precious thing to be found among the sons of men.
Ye strike at what God loves and cherishes, and takes great pains to bring the creature to.
Ye strive to keep that down upon which the happiness of mankind depends; yea,
ye consult and take much pains to remove that out of the way,
which stands between you and the judgments of God.
Oh that your eyes were opened! for surely then ye could not proceed in this course.

Well! the Lord will open the eyes of many;
and mercy towards mankind is issuing from his throne;
and he will smite that through and through which
maketh the earth miserable and desolate of his life.
But oh that man could hear in the day of his prosperity,
that adversity might not come upon him!

Wait to read these things in the life from which they sprang;
and then tell me whether there is not a cause for what I write.

=== Postscript

There hath been a great apostasy, since the days of the apostles, from the living power,
into dead forms of worship and devotion, where likenesses of truth have been set up,
instead of the truth itself.
Now the Lord is gathering his true seed (even Israel,
his beloved offspring) out of all dead forms of all kinds, into his living truth,
and into the true, spiritual worship;
and who is he that shall be able to stop him herein?
Let him consider his strength, who girds himself to the battle against him:
for not by might, nor by the power of man, but by the Spirit of life in his called,
faithful, chosen, and innocent lambs,
will the Lord of glory carry on his work in the world.
