[#three-queries, short="Three Queries for the King and Parliament"]
== Three Queries Propounded to the King and Parliament / In the Fear of the Most High, and in the Tender Love of my Soul to Them

=== PREFACE

THE main thing conducible towards man`'s safety and happiness, is to see things aright;
and he that seeth aright, must see with a right eye.
There is an eye which cannot see the things of God;
there is a heart also which is insensible of his warnings, and so runs into the pit.
There is also an eye, to which God giveth the true sight, which foreseeth the evil,
and seeketh a hiding-place; and a heart which feareth its Maker,
and waiteth on him for counsel, distrusting its own understanding,
which it feeleth shallow and apt to err.
Oh that man might feel his want of God, and receive a principle of divine life from him,
and be fixed and act therein!
If I should pray thus particularly for every one of you, would ye be offended with me?
I have written somewhat here in the kindlings of my love,
and in the light of life which shineth in my heart:
oh that the Lord would please to open a vein of the same
life in you! and then would ye read them in the same,
and, in a secret sense of spirit, feel what they are, and from whence they come.
Now if it should please the Lord that any of you should feel any touches of heart,
and secret assent of soul to the truth of them,
oh! take heed of the fleshly wisdom and reasonings of the earthly mind,
which will soon rise up afterwards,
to wear out the sense of any good that God begets in the heart.

=== THREE QUERIES etc.

==== QUERY I.

WHETHER ye do certainly and infallibly know what was the ground
or cause why the hand of the Lord was so heavy upon this nation,
and why he overturned the government thereof, and brought the honorable into contempt?

Three things are supposed to be taken for granted in this QUERY.

First, That it was the hand of the Lord that did this.
It is he that hath the anguish of soul, and the diseases of body, at his command;
and afflicteth both men`'s bodies and souls at his pleasure.
And he also afflicteth nations, with the powers and authorities thereof,
when it seemeth good unto him.
Now this is the thing which is mainly to be eyed by particular persons,
and also by nations, in whatever befalleth them: to wit, the hand of the Lord in things.

Secondly, That there was a ground and cause for which the Lord did it.
The Lord is tender-hearted, and loveth his creature, delighting to do it good,
and doth not afflict it out of any pleasure he hath therein,
but upon a kind of necessity, that he may bring down evil and bring up good in a nation.
"`He doth not afflict willingly,
nor grieve the children of men.`" It is no pleasure to the Lord to torment his creatures;
but to destroy the seeds of corruption and unrighteousness,
and to bring up the good seed which he hath sown in the hearts of men,
this is a pleasure to him.
Now as your afflictions were very great, and the alterations in this nation strange;
so there was a consideration in the Lord`'s eye to countervail them,
or they had never been.

Thirdly, that it is requisite and necessary for you,
certainly and infallibly to understand the ground why the Lord did this;
what his meaning was; what he was offended at, and intended to bring down;
what he was pleased with,
and intended to give scope to spring up and grow under this confusion;
which could not under the former settlement.

The reason why this is necessary for you, is this:
because unless ye certainly understand this thing,
ye may err and mistake in your present course, setting up the same things now,
which the heart of the Lord was then against,
and endeavoring to suppress the same things,
which it is the will of the Lord should grow up,
and so may provoke the same hand against you again;
which truly I think is not good for you to do, nor indeed can I think so of you,
as that ye willingly would do it.
Therefore pray to the Lord for the upright balance to weigh a thing of such a nature in,
and of so deep concernment to you;
for if ye do run a contrary course to the mind of the Lord,
and he be provoked against you, and stretch forth his mighty arm and overthrow you,
it will then be too late for you to consider of these things.

==== QUERY II

Whether, when the Lord did overturn the former powers,
with the glory and beauty of this nation,
and raise up other powers out of the dust (as I may say),
even from among them of low degree;
if they had then answered what the Lord expected and required of them in their day,
whether they should have been continued by him in their dominion or no,
and whether ye should have had this day of trial,
which it hath pleased the Lord now to afford you?

The day of power and government, which the Lord had given you formerly,
was manifestly by his providence come to an end;
and whether ever ye should have a day more, was very doubtful.
All your councils and strength availed nothing,
save only to make the work more difficult, if not at length almost impossible.
And now the Lord was busy in trying several sorts of these,
what they would do for his name.
And truly this I may say concerning them all (though I would not reproach any),
that they did not answer the expectation of the Lord.
But this I leave to you to consider, Whether,
if they had answered the expectation of the Lord, and done what his soul delighted in,
and what in part they promised,
whether the Lord would have continued them in authority or no.
I propose this, that ye may take notice upon what ticklish terms ye then stood,
as to your future hopes,
and how easily your authority and greatness might have been forever buried,
and that which was lately uppermost have continued so,
if it had seemed good unto the Lord;
that so ye may be sensible of what the Lord hath done in relation to you,
and pray that ye may walk worthy of it, making use of it in the fear of his name,
who hath all still in hand, and can still do what he pleaseth in this nation.
Indeed he can yet bring down whom he will, and he can yet set up whom he will;
and what he will do, ye know not; but in the fear of his dreadful name,
and in holding your standing out of self-confidence
(because of your present strength) is your safety.

==== QUERY III

If ye do not certainly know what was the cause of
the Lord`'s former displeasure against you,
and of his so sore afflicting you, but shall err in judgment,
and set up the same things again, which the Lord then put forth his hand to throw down,
and also endeavor to crush and suppress that which
the Lord then made way for the growth of,
whether this will not endanger your overthrow from the hand of the Lord?

Sure I am,
the Lord is able to overturn you as easily as he
overturned them that were in power before you.
What is man to the Lord?
What is his flesh to the Lord`'s Spirit?
What great tree could stand before the late vehement wind (where the Lord gave it power);
which was terrible and dreadful, tearing up by the very roots?
which might be a figure and warning where the Lord gives eyes to read.
After ye have done all ye can, even made laws as strong as ye can,
and put them in the strictest course of execution ye can,
one night from the Lord may end the controversy,
and show whether we please the Lord in obeying him,
or ye in making laws against us for our fidelity and obedience to him.

And as the Lord is able to overturn you, so if ye mistake your work,
misinterpreting the passages of his providence,
and erring in heart concerning the ground of his former displeasure;
and so (through the error of judgment) set yourselves in opposition against him,
replanting the plants which he will not have grow,
and plucking up the plants of his planting; do you not in this case provoke the Lord,
even to put forth the strength which is in him against you?
We are poor worms.
Alas, if ye had only us to deal with, we should be nothing in your hands!
But if his strength stand behind us, we shall prove a very burdensome stone,
and ye will hardly be able to remove us out of the place wherein God hath set us,
and where he pleaseth to have us disposed of.
And happy were it for you, if instead of persecuting us,
ye yourselves were drawn to wait for the same begettings
of God (which we have felt) out of the earthly nature,
into his life and nature, and did learn of him to govern in that;
then might ye be established indeed,
and be freed from the danger of those shakings and
overturnings which God is hastening upon the earth.

Now because ye may be apt to think, that I write these things for my own sake,
and the sakes of my friends and companions in the truth of God,
that we might escape the sufferings and severity which we are like to undergo from you;
and not so mainly and chiefly for your sakes,
lest ye should bring the wrath of God and misery upon your souls and bodies;
to prevent this mistake in you, I shall add what followeth.
Indeed this is not the intent of my heart; for I have long expected, and so still expect,
this cup of outward affliction and persecution from you,
and my heart is quieted and satisfied therein,
knowing that the Lord will bring glory to his name, and good to us out of it:
but I am sure it is not good for you to afflict us
for that which the Lord requireth of us,
and wherein he accepteth us; and ye will find it the bitterest work ye ever went about,
and in the end will wish that the Lord had rather never given you this day of prosperity,
than that he should suffer you thus to make use of it.
Now that ye may the more clearly see the temper of my spirit,
and how my heart stands in this thing,
I shall a little open unto you my faith and hope about it, in these ensuing particulars.

First, I assured in my heart and soul,
that this despised people (called QUAKERS) is of
the Lord`'s begetting in his own life and nature.
Indeed, had I not seen the power of God in them,
and received from the Lord an unquestionable testimony concerning them,
I had never looked towards them; for they were otherwise very despisable in my eyes.
And this I cannot but testify concerning them,
that I have found the life of God in my owning them;
and that which God hath begotten in my heart refreshed by the power of life in them;
and none but the Lord knows the beauty and excellency of glory,
which he hath hid under this mean appearance.

Secondly, the Lord hath hitherto preserved them against great oppositions,
and is still able to preserve them.
Every power hitherto hath made nothing of overrunning them; yet they have hitherto stood,
by the care and tender mercy of the Lord;
and the several powers which have persecuted them, have fallen one after another.

Thirdly, I have had experience myself of the Lord`'s goodness and preservation of me,
in my suffering with them for the testimony of his truth,
who made my bonds pleasant to me,
and my noisome prison (enough to have destroyed my weakly
and tender-educated nature) a place of pleasure and delight,
where I was comforted by my God night and day, and filled with prayers for his people;
as also with love to, and prayers for,
those who had been the means of outwardly afflicting
me and others upon the Lord`'s account.

Fourthly, I have no doubt in my heart that the Lord will deliver us.
The strength of man, the resolution of man, is nothing in my eye,
in compare with the Lord.
Whom the Lord loveth he can save at his pleasure.
Hath he begun to break our bonds and deliver us, and shall we now distrust him?
Are we in a worse condition than Israel was, when the sea was before them,
the mountains on each side, and the Egyptians behind pursuing them?
He indeed that looketh with man`'s eye, can see no ground of hope,
nor hardly a possibility of deliverance; but, to the eye of faith,
it is now nearer than when God began at first to deliver.

Fifthly, It is the delight of the Lord, and his glory, to deliver his people,
when to the eye of sense it seemeth impossible.
Then doth the Lord delight to stretch forth his arm, when none else can help;
and then doth it please him to deal with the enemies of his truth and people,
when they are lifted up above the fear of him,
and are ready to say in their hearts concerning them, They are now in our hands;
who can deliver them?

Well: were it not in love to you,
and in pity (in relation to what will certainly befall you, if you go on in this course),
I could say in the joy of my heart, and in the sense of the good-will of my God to us,
who suffereth these things to come to pass, Go on;
try it out with the Spirit of the Lord; come forth with your laws, and prisons,
and spoiling of our goods, and banishment, and death (if the Lord please),
and see if ye can carry it.
For we come not forth against you in our own wills,
or in any enmity against your persons or government,
or in any stubbornness or refractoriness of spirit;
but with the Lamb-like nature which the Lord our God hath begotten in us,
which is taught and enabled by him both to do his will,
and to suffer for his name`'s sake.
And if we cannot thus overcome you (even in patience of spirit, and in love to you),
and if the Lord our God please not to appear for us,
we are content to be overcome by you.
So the will of the Lord be done, saith my soul.

=== POSTSCRIPT

O dear friends, hearken to the voice of the love of my heart,
which speaketh thus unto you!
Oh wait, wait to feel somewhat of God,
somewhat of his divine life and power stirring in your hearts, and travel,
in the light and leadings of it, out of the earthly nature,
leaving the corruption of man behind, which makes you miserable,
and putting on the holiness and righteousness of the nature of God day by day,
which will make you happy, as ye are made partakers of it!
Yea, do but come into the power of that religion which ye yourselves profess,
not so much minding the outward form (for it is not of so much value),
and ye shall find that we shall agree in religion sooner than ye are aware.
Now if in your hearts ye shall ask me,
what it is to come into the power of that religion which ye yourselves profess,
I shall appeal unto your own souls whether it be not this;
even to forsake the devil and all his works,
taking up the cross unto your own hearts`' lust and corrupt ways,
and under this cross (wherein is the power of God felt by them that mind it,
and wait upon God there with humble and subject spirits)
to fight the battles of Christ against temptations to sin,
and the soul`'s enemies, even until death.
Here (if ye will enter at this narrow gate,
and walk on in this strait way unto the kingdom, into which flesh and blood cannot enter,
but the selfish nature and earthly spirit must be left behind) in this religion,
which is indeed the substance of all true religion,
we can readily meet and unite with you.
But if ye will set up a form to stop the power and progress of
the Spirit of the Lord in the hearts of his people in this nation,
and not mind the power of religion yourselves,
but with vehemency go about to force others to your
form (which ye cannot truly say is of God,
but of man), in this we cannot close with you,
but must be content in the will of God to suffer under you,
the time which the Lord hath allotted, which ye cannot go beyond.
And blessed forever be the name of the Lord our God,
who hath made us acquainted with that life and power which was before
all forms and ways of religion and worship of man`'s inventing,
and which will be after them;
and who hath hitherto borne up our spirits in the testimony
which he hath given us to bear to his living truth and worship,
and who we doubt not will yet bear us up,
even to a conquest in his Spirit over all that he hath called us forth to testify against.
And that great city, or building of religion, which is built up by man`'s wisdom,
and maintained by man`'s strength, we are sure is falling,
and shall fall throughout all the earth; yea,
man`'s striving to re-edify and reestablish it,
will but make the ruins thereof more speedy and more dreadful.
The mouth of the Lord hath spoken it, both in the Scriptures of Truth,
which cannot be broken, and in the hearts of many of his servants,
in this day of his appearance in Spirit to those,
the eyes of whose spirits he hath opened,
and by whom he hath given a visit and warning to the earth,
which the earthly ear cannot hear,
but will be overtaken and surprised with the day of the Lord.
And oh, what running and seeking will there be to the rocks, and hills, and mountains,
for a hiding place from the wrath of the Lamb! but none will be then found.
O miserable, earthly-spirited man! (who hath passed away thy time in a dream,
and hast little minded or regarded the salvation of thy soul,
or considered what thy present vain pleasures and
courses would tend to) what wilt thou then do?
There is a pit prepared for the wicked (I speak not an imagination of mine own;
indeed it is the truth of God).

Now the Lord seeks the souls of all lost men, to save them from the pit;
but their ears are dull of hearing, their eyes veiled,
their hearts grossly fatted and made insensible with
the senses and delights of the earthly nature,
and the voice of God (with the things that concern their eternal peace, yea,
their present welfare also) cannot enter into them:
and so they let slip the time of their redemption,
and waste away the season of their visitation,
hardly ever so much as thinking what will become of them in the end.
O Lord my God! awaken thy poor creatures, that they may live, and not die:
rather let thy judgments break forth to awaken them,
than that they should thus run on towards utter destruction,
even to perish from thy life and blessedness, and to be swallowed up in the misery,
torment, and wrath due to that nature which they have contracted,
and wallowed like swine in.
Every nature, principle, and spirit is travelling towards its end.
O man! take heed what nature thou art of, in what principle and spirit thou actest,
and towards what thou travellest.
And remember that God loveth his creature; thy destruction is not of him, if thou perish;
but in him is thy help, if thou hearken to his voice,
and turn at the reproofs of that which he hath placed near thee, even in thy heart,
to reprove sin in thee,
and to beget thee into the love and holiness of his life and nature,
leavening thee into a new man,
as thou becomest subject to the checks and leadings thereof.
This is pleasing to the Lord; that which proceeds from this, and is performed in this,
is the true worship, and not that which man hath invented,
and with which the earthly nature is quieted and satisfied,
but the power of life turns from.

It is the great mercy of the Lord to stop any man in the way of his error,
and happy is he that is stopped by him.

=== ANOTHER POSTSCRIPT

YET one thing, perhaps as my last unto you, let me freely propose;
and be not hasty in spirit,
but wait on God for skill and ability to weigh the thing aright,
and to give an upright answer thereto, as before him, in the secrets of your consciences.
It is briefly this: Why may not the power of religion be permitted to flourish under you?
Cannot the government of God`'s Spirit and your government stand together?
I beseech you consider it.
No man knoweth how short his time is,
nor what is to come after his present determination of things.
It is now your day?
Oh, that ye had the true light to walk by in it, that ye might not afterwards repent;
and that my heart might be gladded concerning you, who have so prayed for you,
as if I had felt my own soul in your conditions!

ISAAC PENINGTON.
