== A Salutation of Love and Tender Goodwill

[.heading-continuation-blurb]
To the commissioners of the peace for the County of Bucks,
and such others in that County, and also throughout the nation,
as are concerned in the contents hereof.

If I should warn you of the day of the Lord (which is a
day of terrible wrath to the transgressing nature,
but of peace, love, and tender mercy to the righteous, innocent, suffering seed);
if I should tell you that this day is hastening upon this nation,
and upon the whole earth; and if this should affright you,
and cause you to cry unto the Lord to deliver you from that nature,
and from those sinful courses,
which make you but fit fuel for his fire in the day of its hot burning,--I say,
if by this means ye should be thus prepared for this day,
and yet this day comes not so suddenly as ye might expect; yet that would be no loss,
or cause of grief unto you.
But if this day should suddenly come, and find you in your sins,
and so the fierce wrath of the Lord break in upon and afflict your souls,
and the day of your mercy and redemption be wholly passed over by you;
this would be matter of unutterable grief and sorrow to you,
and the remembrance of your former ease and pleasures would
but increase the sense and anguish of your misery.

Certain I am, there is a day of giving account for sinning against God,
and for oppressing that in your consciences which discovers to you, and checks you for,
your sins.
And this will as certainly come, as the day of sinning now is;
and then every man must receive from God according to his works,
and reap the fruit of the deeds done in the body;
then every soul must inherit according to its nature,
and every vessel be filled with what it is fitted to receive:
that which is fitted for mercy, with mercy; that which is fitted for wrath and misery,
with wrath and misery; and then the distressed sinner will wish,
Oh that I had an hour to escape!
Oh that God would once more give me a moment of repentance, and of turning from sin!

Oh consider! is it a slight thing with you that the infinite God,
who is little concerned in you (being perfectly blessed and happy forever without you;
but as his love, mercy, and tender nature,
maketh him concern himself about the salvation of your souls),
should give you so large a space of repentance,
and so many discoveries of the evil of your ways
(when at any time ye are retired and serious),
and so many checks and warnings in your hearts, as the vilest of sinners, at times,
have more or less from God?
Can ye lengthen out the day of mercy?
Can ye limit God how long he should strive with you?
Oh! why do you harden your hearts?
Why do you hearken to the lusts, desires, temptations, and counsels of the earthly mind,
whose counsel hath undone all that have listened thereunto?

There is no way of avoiding the eternal insupportable wrath of God,
but by travelling out of that nature, spirit, and course which it is to.
Him that sowed to sin and corruption under the law, the sacrifices would not save then;
nor him that soweth to sin and corruption under the gospel,
the sacrifice of Christ will not save now;
but he that is saved by Christ must be sanctified
and redeemed from sin and corruption by him;
which Christ worketh by his principle of life sown in the heart;
which principle turneth against the contrary principle, discovering its nature, and dark,
evil ways, and drawing from, and leading out of them.
Oh! therefore let me in love entreat you all,
my dear countrymen (indeed I have no end in it but your good),
to mind that in your hearts which discovers your evils to you;
that therein ye may feel the power of life drawing you from them,
and helping you against them.
Greater is the power in this than the power that is in the contrary principle;
as those that hearken to it, and become subject, by experience feel.
And what if ye lose a few fond pleasures for the present
(which indeed are beneath the true state of a man),
ye will lose a great deal of misery too, and your gain at last will be exceeding great.

If ye would know whether I speak truth in these things, come to the true balance,
and wait on the Lord, till by him ye be made able to weigh.
My meaning is, join to the good Spirit of the Lord,
when ye find it stirring in your own hearts; give up unto it,
let in its strength upon you, in its warmth and drawing virtue;
give up to forsake the evil, and pursue the good:
fear not the multitude of evils in the heart, nor the long accustomedness unto evil;
the Lord will help the willing soul out of them.
And in this obedience to the good Spirit of the Lord,
there will be an understanding received to know the things of God,
and to try words and sayings, whether they be of him, or of man.
And he that tries in this balance cannot be deceived (the measure being equal and just,
and proper to the things which are therewith to be measured); whereas the wisest of men,
trusting either to their own understandings and judgments,
or to the judgments and understandings of others, are liable to be deceived;
and then ye will acknowledge what love this sprang from,
and what light and life it sprang up in, though through a weak and contemptible vessel.

[.signed-section-signature]
Isaac Penington.

=== Concerning Peace and Good-Will.

The true peace is in the new nature,
which puts an end to the warring and fighting spirit inwardly,
and turns the whole strength of the battle against the enemies of the soul.
In the old nature there are lusts after dominion, and after liberty to the flesh,
and fulfilling the self-will of the earthly mind;
but these are all brought down in the renewed spirit, by the power, love,
and sweetness of the gospel of peace.
Here is indeed uprightness of heart to the Lord,
quietness of spirit under whatever the Lord suffers to be, and goodwill towards all men;
waiting on the Lord for his seasons of tender bowels, with strong cries and tears,
even for those, who, to the eye of man, may seem so hardened against God and his truth,
as to be out of the reach of mercy.
