[#question-king, short="A Weighty Question for the King and Parliament"]
== A Weighty Question / Propounded to the King and Both Houses of Parliament

[.heading-continuation-blurb]
Together with some queries about religion for the good of men`'s souls
that they may seek after, and be established in, that which gives life.

[.section-date]
1663

QUESTION

Whether laws made by man, in equity ought to extend any further than there is power in man to obey

Is it not cruel to require obedience in such cases,
wherein the party hath not a capacity in him of obeying?

Now in things concerning the worship of God, wherein a man is limited by God,
both what worship he shall perform, and what worship he shall abstain from,
here he is not left at liberty to obey what laws shall be made by man contrary hereunto.

The New Testament worship is to be in Spirit and Truth;
which is a principle above man`'s reason,
and cannot rightly be limited by a lower principle;
but the lower principle in every man should be subjected to the higher,
both in himself and others.

These things I write, not in pride or conceitedness, but with an humble heart,
and in love; that God may have his due, Caesar his, and all men theirs;
and that wrath from God may not break forth upon this nation;
for surely it cannot but greatly provoke him,
to see his people so deeply suffer for their obedience
to him in what he requireth of them.

I am a lover of peace, truth, and righteousness,
and a hearty desirer of the welfare and prosperity of this nation;
and that it may not more be broken up in the wrath and indignation of the Lord;
but that the peaceable and righteous seed, which he hath sown in the hearts of many,
may be quietly suffered to grow up, to the praise of the Lord,
and to the good of mankind.

This is from one, who was a mourner over you in your affliction,
and is now also a mourner over those whom ye afflict.

I+++.+++ P.

=== SOME QUERIES ABOUT RELIGION.

Query 1. What is true religion?
Is it a gift from God, bestowed on those whom he begets by the power of his life?
Or is it a profession of worship of the nature of this world,
which a man by natural parts and industry may attain to, as well as other things?

Query 2. What is the sum and substance of the true religion?
Is it not love from a principle of life?
Is it not a travel out of the enmity of the creature into the love of God?
Doth not the light of life spring in the love, and gather into the love?
Doth not Christ, revealed in the heart, and leavening the heart with the savor of life,
teach love to enemies, to bear with them in love, to seek them in love,
to forgive them in love, to pray for them in love, to wish good to them,
and wrestle with God for mercy towards them, even while they are hating and persecuting?

Query 3. Are the Papists, or Protestants, or any other sort of religious persons,
found in this love?
Do they manifest it by their discipleship to Christ, and the power of Christ in them?
Or rather, do they not set up their several forms,
and maintain them in wrath and enmity against each other?
Nay, would they not destroy each other, if they could?
Surely this spirit is in too many of them!
And doth not this give a strong evidence against their religion, that it hath but a form,
and not the true power in it, and that in heart they are not the disciples of Christ?
For if they were such, they would of him learn the love.

Query 4. Whether any form of religion (if not held in the power,
and subjected to the power) doth not fight against the power,
keeping up an outside show without the substance, and thereby crushing the substance?
What form of religion at this day in the world can suffer the love to grow,
and the life to lead and rule in the love,
and the Lord of life to exercise his authority in the hearts and consciences of men?
And this is for want of power within, and because of forms forcibly set up without:
for the religion of the gospel began in Spirit and in power,
and it never can be restored and preserved but by the same Spirit and power.
The renting of the Protestants from the Papists was
no further good than it was in the power of the life;
and the renting of others from the Protestants was no further good,
than it was begun and held in the same power: nay, any party,
though beginning ever so uprightly,
and by ever so true and clear a leading of the Spirit of God;
yet so soon as it begins to invent and turn aside to a form of its own choosing,
and is upheld by the reasonings and understandings of men, it presently corrupts.

Query 5. Whether the power of religion (and the true
love) if it were raised up and restored again,
would make the world happy, and set everything in its proper place,
both inwardly and outwardly?
Is not sense an excellent thing in man, if it be guided by reason?
And is not reason a much more excellent thing if
it be guided by an inward principle of life?
But sense left to itself, without the guidance of reason, how bruitish is it!
And reason left to itself, without the guidance of a principle of life, falls below sense.
How cruel, how blind, how selfish, how unrighteous is man,
that follows the dictates of his own corrupt reason,
without knowing and becoming subject to that, which should enlighten it,
and give him the right use thereof!

Query 6. Whether God will restore religion again in the power?
Whether he hath such a work to do in the world?
And whether the time be near that God is about such a work?
And whether he hath already begun it, and made any progress in it?
Is there such a thing as the power of religion sought after?
Do men grow weary of their forms of worship, and find them empty,
and unsatisfactory to the hungry soul, that pants after life?
Nay, have there not been some touches and appearances of life and power,
and of the true love, in some poor, weak, despised ones?
Oh that men knew the times and seasons,
and then perhaps they would see that this is not a day for setting up of forms,
but of longing and crying out after life and power!

Query 7. When God restoreth religion, and raiseth it up in power,
whether then forms and ways of worship, without the power,
must not needs wither and decay?
When the power first appeared in the dispensation of the gospel,
did not all the shadows of Moses`' ceremonies fly away, and vanish before it?
And when it appears again, shall not all the shadows and inventions of man,
which have sprung up since in the time of the night,
vanish before the brightness of the light of the day?
Where the power ariseth in any heart; what becomes of the man,
with all that springs from him?
Where is his wisdom?
Where is his former worship?
What becomes of all his forms of religion?
Do they not all moulder and come to nothing, and he become as a little child,
to be formed again in the power of life, and born of the Spirit of life,
that he may enter into God`'s kingdom?
Do not all the old things pass away, and new things spring up from the seed of life,
which God sows and preserves in the hearts of his by his power?

Now who is wise to understand these things?
Who hath the key to open the mysteries of life?
Who knoweth the times and seasons (the times and seasons of forms,
and the times and seasons of life and power)?
Who seeth what God is about to do in the world,
and prepareth his heart for his administrations on the earth?
Who is a friend to God, and to mankind, and willing to travel in spirit out of this dark,
corrupt, earthly state of things, into the heavenly nature and being,
where man was at first, from whence he came, out of which he departed,
and can never be happy till he return thither again;
and can never return thither by his own strength and reason,
but only by the power and leadings of God, revealed in him, an inward principle of life?
And he that will follow this must feel it in his heart,
and then turn his back upon the earthly nature and wisdom,
and war against his own corrupt reasonings,
in and with the light of the principle of life, as it ariseth,
and is further and further made manifest in his heart,
through the grace and mercy of God, which thereby offereth its help to miserable,
lost man, to redeem him out of his misery and undone estate.

Man hath a time here allotted him by God; and when the time is over,
it is determined concerning him.
He is a seedsman in this world, and what he sows here he must reap hereafter.
He soweth either to the flesh, or to the Spirit; either to his own will,
or to God`'s will.
He followeth either the ways of his own heart, or of God`'s Spirit.
He either feels the power of religion, and is renewed thereby, and fitted for God;
or contents himself with a form without the power, and in effect remains what he was.

He that is renewed, he that is changed in heart and life,
he that soweth to the will and nature of God, shall inherit life with God.
He that liveth in a form of religion without the power,
and followeth the vanities of his own mind (going
out of this world unrenewed and unfitted for God),
shall be cut off from God, and lie down in sorrow and anguish of soul,
where he will bitterly bewail his misspent time,
and the losing of his soul`'s life and happiness,
for the enjoying a few days the earthly nature and
spirit in its corrupt and degenerated estate.

O Man! whoever thou art, that art drowned in the lusts and pleasures of this world,
which answer only to the sensual and corrupt part!
Oh! remember that thou hast also a precious soul,
which wants redemption by the power of God to make thee happy.
And one day this soul will be awakened in thee, and when it is awakened,
it will feel its want of God.
This is the day of God`'s stretching out his arm to thee; oh,
slip it not out! for if thou dost, terrible will the day of thy awaking be;
and thy misery unavoidable and intolerable.
And if now the pains of thy body be so dreadful to thee,
what will the tearings of thy soul be by the wrath of the Almighty?
Lay it to heart, and retire inwardly,
seeking to feel somewhat of God gathering and guiding
thy soul out of thine own worldly nature and spirit,
into the nature and life of his Spirit; that thy soul (at present separated from God,
and drowned in the earth) may return to, and be happy in, the centre of life,
from whence it came.
For there is a centre of souls, as well as of the earthly nature;
and the spirit of man returneth to God that gave it, as well as the body to the earth.
And then the Lord appointeth it to its proper place,
which is according to the nature it is found in.
If it be wheat, if it be of the renewed nature, if it hath taken up the cross,
and followed Christ in the regeneration, then he gathereth it into his garner.
If it be of the chaffy nature, of the earthly spirit;
the mind remaining unrenewed and unreconciled to the nature of God;
then to the unquenchable fire (even the fire which will burn and
scorch unquenchably) and to the worm which dieth not;
but gnaweth perpetually, and bringeth to mind all the former vanity and misspent time,
to increase the heat and flames of the fire.
Oh! where is the soul, that,
if it were not wholly bewitched and lulled into a dead sleep,
by the stupefying spirit of this world, would run so great a hazard,
for the enjoying of a few momentary pleasures in the sensual part,
and lose thereby the inward enjoyment of peace and reconciliation with God here,
and of the pleasures of his kingdom of true glory afterwards.

Now for a close, let me say one word (in the upright love,
and true good-will of my heart) to this present generation,
that they may consider and take heed (if possible); it is this:

Even as a father after the flesh is tender to the
children he begets according to his nature,
and would not suffer them to be wronged or destroyed if he could help it;
so is the Lord tender of those whom he begets in the nature of his life,
and in his due season will appear for them, as surely as he is God,
and as surely as he has begotten them out of the worldly nature unto himself,
by the Spirit and power of his life.
Therefore,
oh! touch not any whom the Lord hath in the least measure anointed with his holy oil!
For what is done unto the least of these poor, naked, sick, imprisoned ones, etc.,
he looketh upon as done unto himself;
because he is one with them in the sufferings of their flesh,
whom he hath made one with himself in Spirit.

=== CONCERNING THE PERSUASIONS OF REASON AND FAITH IN MATTERS OF RELIGION

THERE is the natural man, and the spiritual man;
and there are the persuasions of each in and about matters of religion.
There is the persuasion of reason, and the persuasion of faith.

The persuasion of reason is that belief which man receives into
his mind or heart from the exercise of the reasoning faculty;
and this persuasion in matters of religion is but man`'s opinion or judgment; which,
how certain or infallible soever it appear to him,
yet may be shaken by a demonstration or evidence of a higher kind and nature.

The persuasion of faith is that belief which the
new creature receives in the renewed mind,
from the evidence and demonstration of the Spirit,
which openeth and manifesteth the things of the Spirit,
unto that mind which is begotten and renewed by it.
And this persuasion is certain and infallible, however it may be struck at and battered,
by the reasonings of the wise earthly part,
even in that very man whose heart is thus persuaded, by the light of the Spirit of God,
concerning the things of God`'s kingdom.

Now the lowest persuasion of faith is higher, and of a more noble nature,
than the highest persuasion of reason; because faith is of a higher principle,
and of a deeper nature and ground, than man`'s reason is.
But this, because it appears not in man`'s sphere, but rather out of it,
and is contrary to the line and reach of his wisdom,
is accounted by him foolishness and madness.
Thus is the wisdom of God (and the children thereof)
judged and condemned by man in this day.

And how can it be otherwise?
How can the wisdom of man but judge that as foolishness,
whose beauty and excellency is hid from its eye?
But this is because the wisdom of man is out of its place,
not subjected to the wisdom of God, but exalted above it;
therefore (as a curse unto it) is it suffered to
lift up itself in its conceitedness against,
and so to persecute, the pure wisdom of God and the births thereof, that it might fall,
and be broken, and snared, and taken, and its day deservedly come to an end,
and be shut up in the shadows and chambers of eternal darkness.

But what ear of man can hear this! surely none that is whole in the line of man`'s wisdom,
reason, and understanding; but that alone that is bruised, broken,
and in some measure dashed in pieces, by the inroads of a diviner life and nature.
This, in the leadings of that life which hath broken it,
and in the shinings of the light eternal upon it and into it,
may be enabled to take up the cross to the natural part,
and to die that death with Christ, which preserves from the second death,
with the misery thereof.

Happy is he, who knows and hearkens to the persuasions of God`'s Spirit,
who is born of God, and taught to wait upon him and worship him in Spirit,
who receives his religion from the light of faith, into the renewed nature and mind,
and not from the reason of man into the natural understanding, which is easily corrupted,
and cannot be kept pure,
but alone by the indwelling of the principle of eternal life in it.

For though such may suffer very deeply in this world,
from the men of this world (as the subjects and servants to the
principle of life have done in all ages and generations),
yet their principle will bear them out;
in which God will appear to strengthen and refresh their spirits,
and carry them up above all their sufferings, in the patience, meekness,
and faith of the Lamb.
And keeping to their principle they cannot be overcome,
but must either live or die conquerors,
according to the will and good pleasure of him who
ordereth and disposeth of all things well,
and bringeth good out of every evil, in despite of all the powers of darkness.
And he that overcometh (whether by life or death) in the Lamb`'s Spirit,
shall wear the Lamb`'s crown,
and sit down in that perfect rest in the kingdom of the Father,
which will give the hearts of all his children full satisfaction.
In which assured hope (life stirring in our bosoms,
and quickening our hearts with love unto God,
and zeal for his truth) we can freely give up all
that is near and dear unto us in this world,
and lay down our heads in inward peace,
in the midst of the greatest outward persecution and trouble.
Even so, O Lord, thy will be done concerning this generation of thy people,
whom thou hast begotten to thyself, and brought forth by thy mighty power,
to testify to thy truth in this present day.
Dispose of them as it pleaseth thee; and let not their faith in thee,
nor thy faithfulness to them, fail;
but let them be a praise to thy name throughout all generations; and tendered by thee,
as the first-fruits of thine appearance, in the glorious light of the everlasting day,
after this great, long, thick,
and dark night of apostasy from the life and spirit of the apostles,
which hath so long eclipsed and covered the brightness
of thy beauty from the sight of the earth.

ISAAC PENINGTON.
