== Some of the Mysteries of God`'s Kingdom Glanced At

[.heading-continuation-blurb]
For the service of the upright-hearted among several sorts of professors,
who have formerly had a feeling of most of these things in measure:

[.heading-continuation-blurb]
To which feeling, and that which gave it them, they are hereby allured and invited to return;
that the many names and various ways may perish and vanish;
and the One Spirit, One Life, One new, living Name and Way may be waited for and pursued after:

[.heading-continuation-blurb]
That so all the Tribes and Families, and several Divisions of _Israel_ may know one another,
and heartily unite in one Nature and inward Power of Life, which doth good to all,
and harm to none, neither inwardly nor outwardly.

[.heading-continuation-blurb]
By a traveller towards the living Substance,
and a mourner over the wanderings of the scattered sheep.

[.section-author]
Isaac Penington.

[.section-date]
1663

=== PREFACE

NONE but Christ, none but Christ, saith my soul,
from the sense of my continual need of him, and from the deep love of my heart unto him.
Now there is a two-fold way of knowing Christ, both which are of use,
and have their service in their several seasons,
according to the estate and condition of the soul,
and according to the dispensation which it pleaseth God to set up among his people;
the one whereof is literal, the other spiritual;
the one is according to a description of him received into the understanding;
the other is according to the revelation or unveiling of him in the heart.
As for instance, Christ may be preached as light, as life, as power,
as the eternal Word and wisdom of the Father, etc.
Now the receiving the knowledge of these things merely into the understanding,
is a receiving and knowing Christ according to the letter,
or according to a literal description of him;
and the receiving of any of these things in the living sense
and shinings of the eternal light of God in the heart,
and so becoming subject in that life, sense, and power,
is a knowing and receiving of them in spirit,
and the spiritual submission and obedience of the gospel.
This is the excellent way and path of life which
God in this last age of the world is making manifest;
though the other is not quite laid aside, nor to be rejected or despised,
where there is any of the light of life stirring in it.
But the main thing now to be minded is the heavenly birth,
with God`'s dispensation of life to it, and its separation from the earthly birth,
and its way of feeding on the heavenly things.
For Hagar and Ishmael (which are the mother and child
after the letter) are now to be cast out;
and the seed of promise, with its mother,
to abide in the house alone (with the Father of blessings) forever.
So that now the separation goeth very near and close.
The birth that is now raised is very inward and spiritual, even the seed itself;
and its food is the life itself,
even that which the earthly birth cannot feed on or digest;
and the way and knowledge of life is very inward and spiritual,
to cut off the earthly nature and spirit in its closest insinuations and transformings.
The Lamb, in his appearances in this day, is very hidden and retired;
and none can see his paths, and follow him, but such as receive of his present ointment,
and feel the guidance of the opening of his eye in them.
The Lord is bringing about great things, both inwardly and outwardly;
happy are they whose hearts and spirits are prepared for them: for great misery, death,
and destruction are coming upon the earthly,
and great joy and blessedness are breaking up in, and showering down upon, the heavenly;
which that all souls that have the breath of life in them,
and that pant after the living God, may partake of, is the earnest desire of my soul.

=== SOME OF THE MYSTERIES etc.

==== CONCERNING CHRIST

[.discourse-part]
Question.
WHAT is Christ?

[.discourse-part]
Answer.
He is the immediate offspring of eternal life in himself,
and the fountain or spring of life unto the creation.
"`Even as the Father hath life in himself,
so hath he given to the Son to have life in himself;`" and in and
through his Son he communicateth of his life unto his creatures.

[.discourse-part]
Question 2. How doth Christ convey life?

[.discourse-part]
Answer.
As the living Word; as the promised seed.
He soweth the seed of the kingdom in the heart, in which is life:
and as he maketh way for this to spread and grow up in and leaven the vessel,
even so he quickeneth and gathereth into his life.
Again, he is the enlightening word, the quickening word, the word of wisdom,
the word of power, the word of love and reconciliation,
whose voice worketh mightily towards the destroying of sin,
and saving of the soul from it.

[.discourse-part]
Question 3. Where is this Word, or seed, to be waited for?

[.discourse-part]
Answer.
Its appearance is in the hearts of the sons of men, and there it is to be waited for.
There God sows this seed;
and there it is nigh to them whom God visits with his lovingkindness and mercy.

[.discourse-part]
Question 4. How is this Word received?

[.discourse-part]
Answer.
By faith in the virtue which floweth from it.
Its nature is to turn against sin, and to draw towards the Father.
Its light shineth to discover sin, and its life stirreth to quicken against it.
Now in the heart`'s believing,
and being persuaded against that which the light discovereth to be evil,
and won to that which it showeth to be good, the word is thus far received,
and a foundation of union between it and the soul laid.
And so, on the other hand,
in the rejecting or turning from any thing that comes from Christ in the heart,
Christ is rejected and turned from.

[.discourse-part]
Question 5. How doth this Word work in or upon the heart?

[.discourse-part]
Answer.
According to the entrance it gets into the heart,
or according as it is rejected or refused.
As it gets entrance, it works life there, and works the creature into its life.
It brings in its nature, its righteousness, its holiness, its sweetness, its peace,
its love, its joy, its meekness, its patience, etc., as it makes room in the heart,
by working out the contrary.
But where it is rejected, it works death and condemnation,
and increaseth the captivity and misery of the soul;
so that it were better never to hear any sound of Christ in the heart,
than not to hearken and become subject thereto.

[.discourse-part]
Question 6. What hinders union with Christ?

[.discourse-part]
Answer.
The strong man armed, whom he cometh to dispossess;
who doth what he can to blind the eye from seeing the lovely nature of Christ,
and to harden the heart against his visits and appearances.

[.discourse-part]
Question 7. How may the soul be helped against him?

[.discourse-part]
Answer.
Receiving the truth in the love,
and giving up the heart in the virtue that flows from Christ in his visits and appearances,
brings in that strength into the soul which conquers him.
He is not able to stand before the power of Christ;
which power is the soul`'s as it is let in by the soul.
It is the unbelief of the heart, and the earthly thoughts and imaginations,
which give the enemy strength: but before the faith, even in the weakest, he is weak,
and his strength falls.

==== CONCERNING THE WAY OF KNOWING CHRIST

CHRIST is the minister of the true sanctuary, which God hath pitched, and not man.
There is a city, "`whose builder and maker is God.`" The foundation-stone,
the corner-stone, the topstone, of this city or building is Christ.
He therefore that would know Christ, and be built upon Christ,
must find a holy thing revealed in his heart, and his soul built thereon by him,
who alone can raise this building,
who can rear up the tabernacle that hath long been fallen down,
who can build up the old waste places,
and restore the paths for the ransomed and redeemed of the Lord to walk and travel on in.

Now he which can find any thing of God built up in his heart (yea,
if he can find but the beginning of the true sanctuary),
he may also find Christ ministering there;
even the true high-priest offering up the sacrifices, and interceding with the Father;
as also giving the soul the food of the holy things to eat of.
Now this is the way of Christ indeed; to wit, in his begettings in the heart,
in his presence there, in his ministrations there, between the soul and the Father.
And he that thus knoweth him, even in that which is begotten of him,
watching in singleness of heart with the true eye, cannot be deceived concerning him,
but knoweth the voice of his Spirit, and readily embraceth it;
but a stranger or deceiver it knoweth not, and will not hear,
but by the instinct of life turneth from it.
So that the knowledge and preservation of the sheep is not by the wise reasonings
of the mind concerning the shepherd`'s voice and the stranger`'s voice;
but by an instinct of the new hidden nature,
which teacheth the simple-hearted to avoid the snares
which the earthly wisdom is easily entangled in.
The meek, the humble, the brokenhearted, the weak, the poor, the babes,
the little children, these are they whom the Father teacheth;
these have that preservation and instruction, which the wise, knowing,
judicious minds (in man`'s account) miss of.
Thus the foolishness of God is wiser than man, and the weakness of God stronger than man.
And God hath chosen in every man that which is not,
to bring to nought all that is in him, that no flesh might glory in his presence,
nor no man be able to boast before the Lord of the salvation of his soul.

==== CONCERNING REPENTANCE

[.discourse-part]
Question 1. WHAT is repentance?

[.discourse-part]
Answer.
It is Christ`'s turning of the heart from the dead nature, and from the dead works,
towards the living principle, and the living works thereof.

[.discourse-part]
Question 2. Cannot a man turn from sin, and turn to God when he will?

[.discourse-part]
Answer.
No; man is a captive, his understanding captive, his will captive;
all his affections and nature in captivity; and nothing can turn him towards God,
but that which is stronger than that power which captivateth him.

[.discourse-part]
Question 3. How is repentance wrought?

[.discourse-part]
Answer.
It is Christ`'s gift, whom God hath appointed a prince and Saviour,
to give repentance and remission of sins,
who giveth it in its enlightening and drawing virtue, wherein sin`'s nature is opened,
and the bent of the soul by him secretly turned against it.

[.discourse-part]
Question 4. What is the heart turned from, and what is it turned towards?

[.discourse-part]
Answer.
From one nature to another, from one principle to another, from one spirit to another,
from one course to another, from one end to another.

[.discourse-part]
Question 5. Is repentance wholly given, or perfected, at first?

[.discourse-part]
Answer.
No; but it increaseth,
and is given daily more and more to the heart that waiteth on the Lord.
Sin, the nature of it, the course of the mind and body in it,
is discovered daily more and more, and the loathing and detesting of it increased,
as the new nature gathers strength in the mind,
increaseth in the light and power of life.

[.discourse-part]
Question 6. Is there never to be any reconciliation or turning back to sin?

[.discourse-part]
Answer.
No; but a further removing and separation from it; which separation is eternal,
even as the beginning of it is in an eternal nature.
The seed, at its first appearance and springing up, shutteth out sin,
as being of a contrary nature to it; and the stronger it groweth,
the more it shutteth sin out: and where it wholly leaveneth and possesseth the creature,
it wholly expelleth the old leaven, and leaveth no place for it to reenter.
This is perfect salvation, where there is no turning back to folly any more,
but a perpetual abiding in the nature of the eternal wisdom.

[.discourse-part]
Question 7. What if there be a committing of sin after one is turned from it?

[.discourse-part]
Answer.
The repentance is not there perfected; the enemy is not there wholly cast out,
nor his strength quite broken; the law is not there fulfilled,
the covenant of grace is not there fully witnessed;
but the soul still in a degree of captivity under the power of the enemy:
yet if the bent of the heart be against the sin committed,
God chargeth it upon the enemy and not upon the soul.
"`Now if I do that I would not, it is no more I that do it,
but sin that dwelleth in me.`" Rom. 7:20.

[.discourse-part]
Question 8. But is there any sin where there is no law?
What makes sin but the law?
When a man hath travelled through the law into the eternal nature, can he then commit sin?

[.discourse-part]
Answer.
Where there is no law, there can be no transgression;
but while any of that nature remains to which the law naturally belongs,
there may be sin and transgression.
Now that only is capable of being out of the reach of the law, whose nature is perfect,
and which comprehends and cannot but bring forth the righteousness of the law in it.
That therefore which falleth short of the righteousness of the law,
and pleads it is not sin to it, is in the deceit and error from the perfection,
and not in the perfect righteousness,
which eternally comprehends and brings forth the righteousness of the law;
but is not comprehended or judged by it, because its nature, life,
and righteousness is above it.

==== CONCERNING FAITH

[.discourse-part]
Question 1. WHAT is faith?

[.discourse-part]
Answer.
It is a belief in the appearances of the Lord to the soul, and a cleaving to,
and drinking in of, their virtue.
There are divers appearances of the Lord, even as a quickening Spirit,
quickening and enlivening the soul; also as a discoverer, reprover, and condemner of sin,
and justifier of righteousness;
likewise as a strengthener and comforter of that which wants his strength and comfort;
and as a fountain of perfect love, sweetness, and of all good, etc.
Now however the Lord pleaseth to appear, that which seeth, knoweth, owneth,
and falleth in with his appearances, drinking in the virtue thereof, that is faith.

[.discourse-part]
Question 2. By what means is faith wrought?

[.discourse-part]
Answer.
By the Word in the heart; by the living Word from which the soul came,
and which is nigh to the soul.
This was the Word of faith, or the Word which wrought faith under the law. Deut. 30.
This was the Word of faith which the apostles preached,
and which wrought faith under the gospel. Rom. 10.
This is the Word which we feel working faith in us now; yea,
and which worketh it in all those in whomsoever it is wrought;
though they may not know what works it: yea, this is the seed of life,
from which every spiritual thing springs and grows in the heart.

[.discourse-part]
Question 3. How is faith received?

[.discourse-part]
Answer.
In the quickening power.
The seed of life shoots forth its light, its life, its nature, its virtue into the heart.
The heart being touched with this, is in some measure quickened towards God,
and in and from this quickening virtue faith flows into the soul.
For in the death of sin, in the dead state, there is nothing but unbelief;
faith therefore must needs flow from the quickenings of life.

[.discourse-part]
Question 4. What doth faith do in the heart?

[.discourse-part]
Answer.
It uniteth to God, and separateth from sin.
It beginneth and carrieth on the work of redemption in the soul.
It receiveth in that which is of God, and beateth back the contrary.
It keepeth the mind chaste, pure, living, and fresh before the Lord.
It draweth out the virtue,
and sucketh in the sweetness of every appearance of God in the heart.
It keepeth in the love of God, and expelleth the love to sin, creature, self,
or any thing as it stands out of God.
Indeed faith is the natural sucker-in of the breath of life,
and the purger-out of the breath and power of death.

[.discourse-part]
Question 5. Wherein doth faith stand?

[.discourse-part]
Answer.
In that wherein it is received, even in the quickening power.
Faith must be continually kept alive by the seed of life, or it cannot live.
It springs in the power, it dwells in the power, it acts in the power,
and is never found out of it.
Man cannot believe when he will; it is a continual gift,
depending upon the continual quickenings and nourishment
of that life from whence it sprang.

[.discourse-part]
Question 6. But doth not God withdraw?
Doth not the power often clap in?
Where is faith then?

[.discourse-part]
Answer.
There is the secret presence of the power, when it is not visibly manifest,
enabling the soul to keep to, and depend upon, that which is not seen, but trusted in,
though unseen, and not sensibly felt: and there is a secret turning from,
and resisting of temptations,
and a secret overcoming (the heart being kept true and entire to
the Lord) while the enemy seemeth sensibly to prevail and overcome.

[.discourse-part]
Question 7. Why doth the enemy so assault with unbelief,
and fight so stiffly against the faith of the soul?

[.discourse-part]
Answer.
Because all depends upon it.
Stop that, he stops all; overcome that he overcomes all.
If that stand and abide in strength, he gains nothing;
but loses by every temptation and seeming victory;
for faith gets ground and advantage not only by a temptation, but also by a fall.

==== CONCERNING HOPE

[.discourse-part]
Question 1. WHAT is hope?

[.discourse-part]
Answer.
The expectation of somewhat from the Lord, in the season of his good-will.
The expectation of the crown of life at last;
the expectation of deliverance from snares and temptations at present;
the expectation of receiving his promises of the divine nature,
or of any mercy or blessing which he hath given to pray for; this is hope.

[.discourse-part]
Question 2. What are the grounds of hope to the soul?

[.discourse-part]
Answer.
There are manifest and visible grounds, or a secret and invisible ground.

[.discourse-part]
Question 3. What are the manifest and visible grounds?

[.discourse-part]
Answer.
They are many, and of divers kinds.
The Lord`'s love manifested to the soul;
the Lord`'s promises made to the soul particularly,
or generally to that condition wherein the soul is;
the soul`'s experience of the Lord`'s helping it in former distresses; yea,
the very tender nature of the Lord towards souls, and their descent from him,
notwithstanding their present alienation and corrupt estate, is a ground of hope,
where the Lord quickens it to the heart.

[.discourse-part]
Question 4. What is the invisible or secret ground of hope?

[.discourse-part]
Answer.
That cannot be discerned which is secret and invisible;
but yet there is sometimes a hope in the heart, when it is not perceived,
which is maintained and fed by the invisible life, which is hid there.

[.discourse-part]
Question 5. What is the nature and proper effects of hope?

[.discourse-part]
Answer.
It stays the mind, even in the midst of storms and tempests, that they do not overturn,
overwhelm, and sink the soul.
It keeps up the head above the many waters, and keeps the heart from utterly fainting.
It preserves life in the many famines and strait sieges of the enemy.
Hope of relief keeps from yielding to the enemy, and preserves from distrusting the Lord.
Distrust cannot enter and prevail, where hope abides.
Hope adds strength to the soul in its pursuit of all that is good,
and in its flying from and eschewing all that is evil,
and is the succorer of faith in the needful hour: yea,
how often would the faith be given up and foiled,
were it not for the hope which relieves it!

==== CONCERNING LOVE

[.discourse-part]
Question 1. WHAT is love?

[.discourse-part]
Answer.
What shall I say of it, or how shall I in words express its nature!
It is the sweetness of life; it is the sweet, tender, melting nature of God,
flowing up through his seed of life into the creature,
and of all things making the creature most like unto himself,
both in nature and operation.
It fulfils the law, it fulfils the gospel; it wraps up all in one,
and brings forth all in the oneness.
It excludes all evil out of the heart, it perfects all good in the heart.
A touch of love doth this in measure; perfect love doth this in fulness.
But how can I proceed to speak of it!
Oh that the souls of all that fear and wait on the Lord might feel
its nature fully! and then would they not fail of its sweet,
overcoming operations, both towards one another, and towards enemies.
The great healing, the great conquest,
the great salvation is reserved for the full manifestation of the love of God.
His judgments, his cuttings, his hewings by the word of his mouth,
are but to prepare for, but not to do,
the great work of raising up the sweet building of his life, which is to be done in love,
and in peace, and by the power thereof.
And this my soul waits and cries after,
even the full springing up of eternal love in my heart,
and in the swallowing of me wholly into it,
and the bringing of my soul wholly forth in it,
that the life of God in its own perfect sweetness may fully run forth through this vessel,
and not be at all tinctured by the vessel,
but perfectly tincture and change the vessel into its own nature;
and then shall no fault be found in my soul before the Lord,
but the spotless life be fully enjoyed by me,
and become a perfectly pleasant sacrifice to my God.

Oh! how sweet is love! how pleasant is its nature!
how takingly doth it behave itself in every condition,
upon every occasion, to every person, and about everything!
How tenderly, how readily, doth it help and serve the meanest!
How patiently, how meekly, doth it bear all things, either from God or man,
how unexpectedly soever they come, or how hard soever they seem!
How doth it believe, how doth it hope, how doth it excuse,
how doth it cover even that which seemeth not to be excusable, and not fit to be covered!
How kind is it even in its interpretations and charges concerning miscarriages!
It never overchargeth, it never grates upon the spirit of him whom it reprehends;
it never hardens, it never provokes;
but carrieth a meltingness and power of conviction with it.
This is the nature of God; this,
in the vessels capacitated to receive and bring it forth in its glory,
the power of enmity is not able to stand against, but falls before, and is overcome by.

==== CONCERNING OBEDIENCE

[.discourse-part]
Question.
WHAT is obedience?

[.discourse-part]
Answer.
It is the subjection of the soul to the law of the Spirit; which subjection floweth from,
and is strengthened by, love.
To wait to know the mind of God, and perform his will in everything,
through the virtue of the principle of life revealed within,
this is the obedience of faith.
This is the obedience of the seed, conveyed into the creature by the seed,
and it is made partaker of the seed.
He is the son who naturally doth the will;
he is the faithful witness who testifies concerning the will; yea,
and he is the choice servant also.

Mark how everything in the kingdom, every spiritual thing, refers to Christ,
and centres in him.
His nature, his virtue, his presence, his power, makes up all.
Indeed he is all in all to a believer,
only variously manifested and opened in the heart by the Spirit.
He is the volume of the whole book, every leaf and line whereof speaks of him,
and writes out him in some or other of his sweet and beautiful lineaments.
So that if I should yet speak further of other things, as of meekness, tenderness,
humility, mercy, gentleness, patience, long-suffering, contentedness, etc.
(all which I had much rather should be read in his book,
even in the living book of the eternal Word, than in my writings),
I should but speak further of his nature brought up, manifested,
and displaying itself in and through the creatures,
by his turning the wheel of his life in their hearts.
But my spirit hasteneth from words,
therefore can I not but cut short and pass over these openings in me,
that neither my own soul nor others may fix or stay upon words concerning the thing,
but may sink in spirit into the feeling of the life itself,
and may learn what it is to enjoy it there, and to be comprehended of it,
and cease striving to know or comprehend concerning it.
And then I am sure he that hath a taste of this cannot but be willing
to sell all the knowledge that can be held in the creaturely vessel,
for that knowledge which is living, and is laid up in that treasury,
into which the thief and corrupter can by no means steal or break.
Yet somewhat I cannot but further add concerning peace, joy, liberty, prayer;
as also concerning regeneration, justification, sanctification, reconciliation,
and redemption; because my heart believeth that it may prove serviceable to some,
in the guidance and mercy of the good Spirit of the Lord.

==== CONCERNING PEACE, OR REST

TRUE peace is the stillness, the quietness, the satisfiedness of the heart in God,
which floweth from and with the Spirit of life in the soul, that is subjected to Christ.
There is indeed a kind of peace; to wit,
a false peace or rest in sin and unrighteousness;
but this is not truly natural to the soul while it lasts,
and is likewise suddenly disturbed when the true light shines in the heart,
and when God`'s witness awakens it.
Then "`there is no peace to the wicked, saith my God.`" Oh,
the trouble and perplexity of the sinner,
when the light of God`'s Spirit makes his heart and ways manifest to him! yea,
and that soul also, which in its day of visitation pants after the Lord,
and is willing to give up to the guidance of his light,
and waiteth for the directing and redeeming power of his Spirit; yet oh,
what a bitter war, noise, and tumults doth the enemy raise within!
How doth it disturb every step of his way, and strive to darken every drawing, motion,
and leading of the soul out of his dominion!
But as the redemption is felt, the snares broken, the life manifested,
and the soul feels itself entered into the nature and obedience of it;
so the peace springs, and the rest in God is tasted of and enjoyed.

==== CONCERNING JOY

JOY is the gladness of the heart in God,
chiefly springing from the refreshings and presence of his life,
which carries through and over all, even the greatest trials and tribulations.
When the poor, panting, weary soul, which hath longed after God,
and long felt the bitterness and misery of its separation, begins to feel his love,
and its union with him, in his letting of it forth into the heart,
and its assurance of his goodness, righteousness, power, wisdom, and salvation, oh,
how is it filled with joy and delight in the earnest of its portion!
Now saith it, in the strength of life, My soul rejoiceth in God my Saviour;
for he hath regarded my low estate, his bowels have rolled towards me,
his dayspring from on high, and his mercies from beneath, have visited me; and I,
who long have been desolate and forsaken, have now found favor in the eyes of my beloved,
and my heart feeleth (in measure) that I am his, and he mine, who hath touched me,
won my heart, undertaken for me, and what can separate?
He hath tied the knot himself, and what can break it?
And how can my heart but rejoice in his name over all my fears, false reasonings, doubts,
and misgivings, which long held me captive, and withheld my eye from reading love,
the which was written both in his heart, and in his dealings towards me?

==== CONCERNING LIBERTY

LIBERTY is the enlargedness of the heart in the Spirit of the Lord,
wherein it hath scope in all that is good, and is shut out of all that is evil.
The Spirit of the Lord is free, and maketh free.
The earthly spirit is in bondage with her children;
but they which are begotten of the Lord, and wrapped up in his Spirit,
find the power and freedom of the new life therein,
and are thereby perfectly out of the reach of that,
which (let into the mind) hath power to captivate and inthrall.
Therefore it is not all manner of scope and latitude,
wherein the true liberty consisteth; but in the scope and latitude proper to its nature.
And thus the infinite and unlimitable One is limited (if it be proper so to express it),
even within the limits and bounds of his own nature and Spirit,
which he cannot transgress, or in any wise consent to do what is contrary thereunto.

==== CONCERNING PRAYER

PRAYER is the breath of the living child to the Father of life,
in that Spirit which quickened it, which giveth it the right sense of its wants,
and suitable cries proportionable to its state, in the proper season thereof.
So that mark: prayer is wholly out of the will of the creature,
wholly out of the time of the creature, wholly out of the power of the creature,
in the Spirit of the Father, who is the fountain of life,
and giveth forth breathings of life to his child at his pleasure.

==== CONCERNING REGENERATION

[.discourse-part]
Question 1. WHAT is regeneration?

[.discourse-part]
Answer.
It is the new birth of the creature,
or its being born again of the immortal seed of the word of eternal life.

[.discourse-part]
Question 2. How is this birth obtained?

[.discourse-part]
Answer.
By the springing up of the seed of eternal life in the heart,
and the heart being changed into it, and brought forth in it.

[.discourse-part]
Question 3. How is the heart changed into and brought forth in the seed?

[.discourse-part]
Answer.
By being leavened with the power and virtue of its nature by a new sap received from it,
which spreadeth by degrees, and at length becoming all in it.

[.discourse-part]
Question 4. How is this virtue received from the seed?

[.discourse-part]
Answer.
In giving up to it in the faith which flows from it:
this lets in the new sap and nature of life, which purgeth out the old.

[.discourse-part]
Question 5. How doth the seed appear and manifest itself, and how is it given up to in the faith?

[.discourse-part]
Answer.
It doth appear in its own light and quickening virtue,
which discovers the darkness and death of sin, and draws the heart,
which it makes willing, out of it.
Now its drawings being felt, it is well known, the thing required by it made manifest,
there is a faith herein begotten in the heart;
and then the soul is to give up in the obedience of the faith,
without consulting with the reasonings and wisdom of the fleshly mind,
where the enemy lies ready to damp this light of faith, and betraying into the unbelief.

==== CONCERNING JUSTIFICATION

[.discourse-part]
Question 1. WHAT is justification?

[.discourse-part]
Answer.
It is the owning or clearing of a person in his obedience to the Lord; or the pardoning,
passing by, and so clearing him from his disobedience.

[.discourse-part]
Question 2. Who is it that justifieth?

[.discourse-part]
Answer.
It is the Lord, who giveth the law to mankind according to his pleasure;
he it is that is also the judge of man`'s obedience or disobedience thereto,
and the proper justifier or condemner of him therein.

[.discourse-part]
Question 3. But is not man in a fallen state?
And can he so obey God in any thing as to be justified by him?

[.discourse-part]
Answer.
Man is indeed fallen, and hath no strength or will of himself to serve or obey the Lord;
but there is a visitation of life and love (for Christ`'s
sake) issuing forth towards mankind in general,
wherein there goeth forth a quickening life, and a secret, hidden virtue,
which giveth ability to the hearts which the Lord maketh willing to follow his drawings.
And this dispensation is so managed by the Lord, that no man perisheth for want of power,
but only from the stubbornness and choice of his own will.
So that man`'s destruction is indeed of himself everywhere; but nowhere of God,
whose delight is to save, and not to destroy, his creature,
under every dispensation of his life.

[.discourse-part]
Question 4. But many men do not know Christ, and how can they obtain justification by him?

[.discourse-part]
Answer.
There is a double knowledge of Christ; outwardly, by a relation concerning him,
and inwardly, by feeling the virtue of his nature.
Now thus many know Christ, who know him not outwardly.
They may have somewhat sown, touched, and raised by God, of the nature of Christ in them,
and in this they may know the Father, and spring of the same nature,
and be gathered in heart into it,
and so come within the line or compass of the spiritual life,
wherein the spiritual blessings and mercies run and flow through Christ,
and for his sake.
And so here they may see their sins, and be loaded with them,
and feel the life and virtue that washeth from them,
and that it is in the mere mercy of God, and so be drawn out of self into the nature,
life, virtue, and power of Christ,
which is conveyed in substance in the inward feeling and new-creating of the heart.

[.discourse-part]
Question 5. How is this justification wrought?

[.discourse-part]
Answer.
By faith in the virtue which floweth from Christ.
God letting in of the nature of his Son into the heart,
and begetting therein somewhat of his own likeness, in which he draweth,
and which he giveth to believe in: this faith is imputed by God for righteousness,
in every heart wherever it is found; and where this faith in the living virtue is found,
there God blotteth out the iniquities for his name`'s sake; yea,
and remission is felt in that which is made living.
And there is one near, who hath power to bind or loose in the conscience,
according to the nature of the dispensation;
and who doth bind or loose in every dispensation as he findeth cause.
But all loosing of sins is for Christ`'s sake, and through his blood;
though every one in every dispensation is not able distinctly so to read it.
Yea, under the law, the remission was by this sacrifice;
though many of the Jews could not read the type.
The promise is to the seed of the kingdom, and to man in the seed;
and there it reacheth him whenever it findeth him; for in all his gatherings into,
and being found in, that, he is blessed.

[.discourse-part]
Question 6. Then may a man be justified who never heard outwardly of Christ?

[.discourse-part]
Answer.
If he feel the seed of life, be overcome by its nature, give up to its law,
as it is made manifest in his heart, abhor the nature and law of sin and death,
and thus in soul cleave unto the Lord, and follow him as he pleaseth to lead,
the Spirit and life of the Lord cannot but herein justify him;
and the grace and mercy of the Lord cannot withhold giving him out his
pardon for his sins past (and also pass by his future frailties),
although he distinctly know not how to sue out and plead it.
The redemption and pardon of sin is through the unlimited grace of God:
which is not restrained to the outward knowledge of the creature,
but issueth forth according to the capacity that God creates any where to receive it.
Life, mercy, grace, pardon, etc. issue forth from God into the vessels of every kind,
under every dispensation that he prepareth for them:
and the inward sense of life is the thing that God aims at in all his dispensations,
and not the outward skill or knowledge, but thrusts that by in every dispensation,
except as his inward life and virtue is found in it.

[.discourse-part]
Question 7. How is justification by grace?

[.discourse-part]
Answer.
No man in his fallen estate can deserve any thing of God.
It is of grace that God visits him by any dispensation of his love and mercy.
It is of grace that he giveth him any ability to turn unto him.
It is of grace that he accepts him in turning,
giving him a share in the ransom he hath found,
which is still in God`'s eye in whatever he does for man, however man may be off from it.
Indeed such is the weakness of man,
that no man can be justified by the works of obedience
that he can perform under any dispensation,
but only by the remission and ability which he receives from grace,
and wherein alone he can be preserved unto the end by grace.
So that in every dispensation it is grace alone that
saves (through the redemption which is in Jesus Christ),
though from the eye of man this hath been very much hidden in divers dispensations.
Yet, notwithstanding,
the broken and humble-hearted ones (who have felt
the inward power of life to change their natures,
and to preserve them in that which God hath begotten in them),
the grace prevaileth to save in every dispensation.
For it is not the outwardness of any dispensation,
but the virtue let forth from God in the heart, which saves.
And by this the Lord can save under any dispensation,
and without this there is no salvation in any.

[.discourse-part]
Question 8. What is the righteousness that justifieth in the sight of God?

[.discourse-part]
Answer.
The righteousness of Christ alone.
This conveyed to the creature in and through the seed,
and brought forth in the creature by the seed,
and the creature united to Christ in the seed; here is the justification of the life.
Indeed there is also a justification according to the works of the law,
or the creaturely obedience,
which the Lord will so far own as the creature is able to bring it forth:
but it is the obedience of faith which is the pleasure of his soul.
And the other can hardly ever be perfect, so as the Lord can spy no fault in it,
and may also easily fail, depending upon the brittle nature and spirit of the creature;
whereas this is of an abiding nature, having its root not in the creature,
but in the seed.
Therefore,
O all that love life! descend from the outwardness of dispensation into the hidden seed,
where we may feel the living God,
and all that are in any living dispensation of his life,
as the Lord pleaseth to let our spirits into him, and into one another.
And wait for the light and power of this blessed day (which in the tender mercy of the
Lord hath dawned from on high upon us) which discovereth and maketh things known,
not after the letter of a dispensation, but by manifesting their inward nature, power,
and virtue in the endless life,
of which Christ is now become the minister in the living
sanctuary in those whose hearts he hath new-formed,
and dwelleth in.

==== CONCERNING SANCTIFICATION

[.discourse-part]
Question 1. WHAT is sanctification?

[.discourse-part]
Answer.
It is the cleansing of the vessel by the Spirit of the Lord,
from the pollution both of flesh and spirit.

[.discourse-part]
Question 2. And by what doth the Spirit of the Lord cleanse the vessel from its pollution?

[.discourse-part]
Answer.
By the living truth, which hath power in it to wash away the deceit, enmity, impurity,
and whatever evil hath formerly defiled, or may yet again at any time defile the vessel.

[.discourse-part]
Question 3. How doth the soul receive this cleansing or purifying from the Spirit of the Lord?

[.discourse-part]
Answer.
In its obedience to his truth made manifest in the heart;
for thereby the power of the Word enters into the soul,
and sheds abroad its living virtue in the soul.

[.discourse-part]
Question 4. What then is chiefly to be minded by the soul,
that would be cleansed from its filthiness?

[.discourse-part]
Answer.
The obedience of faith, or the obedience which springs from faith.
For as all the benefits and blessings of the law depended upon obedience to the law;
so all the benefits and blessings of the gospel depend upon obedience to the gospel.
Yea, and this is the glory and excellency of the gospel that the principle
of faith there doth that which the principle of the law could never do.

==== CONCERNING RECONCILIATION

[.discourse-part]
Question 1. WHAT is reconciliation?

[.discourse-part]
Answer.
It is a bringing together the minds and hearts of God and man into one.

[.discourse-part]
Question 2. How is this wrought?

[.discourse-part]
Answer.
By taking away the enmity of man`'s nature, which is therein against God,
and by planting him into, and causing him to grow up in,
that nature and life which God loveth, whereby that is removed from man which God hateth,
and which is the cause of separation; and man brought into, and brought up in,
that which is the love and delight of God`'s heart.

[.discourse-part]
Question 3. By what is this reconciliation wrought?

[.discourse-part]
Answer.
By the Word of God`'s power.
That comes forth from the love of God unto man;
and man being gathered out of himself into that, the evil seed is thereby destroyed,
and the good seed of the kingdom thereby cherished,
and groweth up in its shadow and nourishment.

[.discourse-part]
Question 4. How doth the Word work this?

[.discourse-part]
Answer.
By winning upon man, and gathering him into its light, out of man`'s own darkness,
exercising man various ways to empty him of himself, and make him weak in himself,
and putting forth its own strength in and for man,
as it hath emptied and weakened him in himself.

[.discourse-part]
Question 5. What then is man`'s great advantage towards reconciliation with God?

[.discourse-part]
Answer.
To become weak, to become poor, to become helpless,
to become nothing by the frequent exercises of the word of reconciliation in the heart:
for the poor receive the gospel, and the weak receive God`'s strength,
and the helpless his mercy, and the nothing-ones his fulness.

==== CONCERNING REDEMPTION

[.discourse-part]
Question 1. WHAT is redemption?

[.discourse-part]
Answer.
It is the purchasing of the vessel out of the captivity and misery of death,
into the liberty and blessedness of the divine life, sown, revealed, grown up,
and perfected in the heart.

[.discourse-part]
Question 2. Who is the redeemer?

[.discourse-part]
Answer.
The Son of God, the child of God`'s begetting, the divine image,
who naturally believes and fulfils the will of the Father,
in every vessel which it hath prepared.

[.discourse-part]
Question 3. By what doth he redeem?

[.discourse-part]
Answer.
By his blood; by his life; by his power; by his nature sown in the vessel,
and transforming the vessel into its own likeness.
Yea, this is indeed redemption, when the creature is changed into, and brought forth in,
the image, power, nature, virtue, and divine life of him that redeemeth;
and the old contrary image perfectly blotted out,
by the presence and indwelling of the new.
This is perfect redemption, the least measure whereof is redemption in a degree.

And after this springs up the glory of the life in the vessel,
even the glory which it had with the Father before the world was.
In the nature of the life the glory is hid: it is sown in the seed,
it dies with the seed, it is raised with the seed.
When Zion in any heart is built up,
it is natural to the Lord to appear there in his glory; and the pure eye sees it,
and the pure heart enjoys and is one with it.
So that as there is a true entrance into, fellowship in, and enjoyment of,
the death of Christ; so is there also of the resurrection and glory of the redeemed life;
which is the portion and inheritance which God hath prepared for Zion,
after her long desolation and sore widowhood;
which he will give unto her in the sight of all the world,
whereby she shall become the beauty, joy, and praise of the whole earth;
who hath hitherto been the reproached, despised, and afflicted, and made a prey of,
by the several sorts of devouring spirits.

==== A POSTSCRIPT TO PROFESSORS

THIS I am assured of, that it were an easy matter with the Lord,
to give forth a literal description of all the things of his kingdom, so exact,
full and natural to the thing, as might answer and satisfy every inquiring mind.
But this would not effect the work which God is now about.
This would not raise his seed, which would lie dead and buried under all this,
unless quickened and raised by the immediate power and life of the Father.
Nay, might not the earthly spirit be easily building with this an earthly fabric,
which would not come within the measure of the true temple!
May I speak freely; I would not deny any thing of God among you,
nor be an instrument to quench the least good in any of you; but indeed I have seen,
I have felt and known some of your snares;
yet have rather spent the strength of my spirit in crying to God for you,
that he would break them, and disentangle your souls,
than in endeavours to demonstrate and manifest them unto you.
And I am now touching at one of them, which is not the meanest; to wit,
a getting the knowledge of things into the mind and comprehension,
striving to grow rich there, and wise to understand and dispute about them.
Indeed, this is not the poor one which receives the gospel,
and is acquainted with the power and virtue of eternal life.
And if the Lord did not teach my soul continually
to give up the outward knowledge of everything,
and press after the inward life, I might soon grow wise after the flesh,
but lose the fresh oil which suppleth and nourisheth me.
My spirit boweth and presseth within me, in great earnestness to the God of mercies,
that ye may not be left behind the flock, whose path is living,
and who follow the living footsteps of the Lamb,
who leadeth by his living Spirit from life to life into his kingdom.

[.old-style]
=== Some Questions and Answers / of Deep Concernment to the Jews

[.heading-continuation-blurb]
From one who hath been a wrestler and traveller with the Lord of life,
for the day of their mercy and redemption.

[.discourse-part]
Question 1. WHETHER the people of the Jews do err in their hearts from the God
of their fathers (in this their sore dispersion and final captivity),
and are not acquainted with his ways, wherein he would have them walk with him,
and wait for his mercy and redemption.

[.discourse-part]
Answer.
That there is mercy towards, and redemption for, that poor, scattered, forsaken people,
my heart hath from my childhood, and doth still steadfastly believe.

That there is a way wherein they are to worship the God of their fathers,
and wait for his mercy and redemption, is also the belief of my heart.

But whether they do indeed know the Lord their God,
and the present path wherein he requireth them to walk,
and so are brought into the capacity and fitness for the mercy
and redemption which is in the heart of the Lord towards them,
that I very much doubt of,
and in the tender love and good-will of my heart am drawn
to propose the consideration thereof to them.

The grounds of this my doubt are chiefly these two:

1+++.+++ Because their fathers,
who had Moses and the prophets to instruct them in the law of the Lord,
and in his ways of worship and obedience,
yet did err in their hearts from the Lord their God,
both under the teachings of Moses and of the prophets.
"`It is a people that do err in their heart,
and they have not known my ways,`" said the Lord concerning them,
upon forty years trial of them in the wilderness. Ps. 95:10.
And Moses also complained unto all Israel,
that notwithstanding all that they had seen done by the Lord in the land of Egypt;
and the great temptations, signs, and miracles in the wilderness,
yet the Lord had not given them a heart to perceive, and eyes to see,
and ears to hear unto this day. Duet. 29:2-4.
Neither did they more understand
the mind of the Lord by the ministry of the prophets,
than by Moses; but misunderstood his way of worship,
misunderstood his intent about their sacrifices,
and offered up the abomination of his soul;
even when they offered up the very sacrifices which he required,
as the Spirit of the Lord in the prophets often testified unto them.
See Isa. 1. Isa. 66. Mic. 6. Ezek. 20.
with many more testimonies of the prophets,
pleading with them from the mouth of the Lord.

Now if their fathers, in the days of Moses, and in the days of the prophets,
when they had certain information from the mouth of the Lord concerning his ways,
yet then did err in heart, and did not understand the mind of his Spirit;
how much more probable is it that these, in the cloudy and dark day,
when the light (that shone upon their fathers) is hid from their eyes,
that these may miss of the mind of the Lord,
and not understand the way of peace and acceptance with their God.

2+++.+++ Because the prophets foretell of their idols cleaving to them,
and their uncleanness not being removed, but their stubbornness and hardness remaining,
until the great and terrible day of the Lord God Almighty,
wherein his Spirit shall be poured down from on high,
and they visited and redeemed in the light and power thereof.
Then shall Ephraim say to his idols, "`Get ye hence;
what have I to do any more with idols?`" Yea in that day "`shall
they cast their idols to the moles and to the bats.`" Isa. 2:20.
For the Lord will cleanse them from all their uncleanness, Ezek. 36:29.
and take away the stone out of their heart,
and make their spirits tender towards the God of their fathers;
insomuch as Ephraim shall smite upon his thigh,
and bemoan his unaccustomedness to the yoke, and eternal law of the Spirit of his God,
which he hath not understood in spirit, but been blinded about the ordinances of Moses,
and testimonies of the prophets.

[.discourse-part]
Question 2. Whether the Jews can possibly meet with the blessings of the Messiah,
while their heart errs from the God of their fathers, and they do not know his way.

[.discourse-part]
Answer.
It is utterly impossible, while they miss of the path wherein blessedness is to be found,
to meet with that blessedness which the path thereof alone leads to.
How can the heart, in erring from God,
meet with that which is alone to be found in union and walking with him?
Have they met with it to this day?
Or can they ever meet with it, till they be taught and led of the Lord to walk towards it?
Oh that Israel knew the way of life!
Oh that their hearts were turned towards their God, that they might no more die,
nor be estranged from him like the heathen, but live the life of the blessed,
and enjoy an inheritance in the land of the living!

[.discourse-part]
Question 3. Is there any way for Israel to be cured of the error of their heart,
that their misknowledge of God and his ways may be removed from them,
and they may come to a right understanding, and a clearness of light?

[.discourse-part]
Answer.
There is balm in the land of the living,
which is able to cure all the diseases and distempers of the dead,
and there is a physician who is able to apply it.
The God of Israel knoweth the very core of evil in the heart,
and all the issues of death from thence, and how to take out the core,
and stop all the issues of sin, death, and misery.
The Shepherd of Israel understandeth the lost state, the wandering state,
the sick state of every lost soul in Israel,
and hath skill and remedies to recover and heal them all.
Ezek.
34.

[.discourse-part]
Question 4. What way hath this skillful physician for the cure of the erring heart of his Israel,
and to bring them to an acquaintance with him and his ways?

[.discourse-part]
Answer.
He hath divers, which are able thoroughly to effect it.
As:

1+++.+++ By circumcising their hearts,
or by sprinkling clean water upon them to wash away the filth of their hearts.
With him is "`the fountain of living waters,`" and with them
can he "`wash away the filth of the daughter of Zion;`" yea,
"`his fire is in Zion,
and his furnace in Jerusalem:`" with him is "`the spirit of
judgment and the spirit of burning,`" wherewith he can search
out and judge all the evil in the hearts of his people Israel,
and burn it up.

2+++.+++ By creating a new heart and a new spirit within them.
He can not only take away the heart of stone, but he can give a heart of flesh,
which shall be sensible and tender to every motion and impression of his Spirit,
as the other was dull and hard.

3+++.+++ He can write his law in their heart,
that they may no more read in the oldness of the letter,
where life can never be learned (which is to pass away,
for the weakness and unprofitableness thereof), but in the newness of the Spirit,
where the new eye easily reads and understands what God writes in the new heart and mind.

4+++.+++ He can put his Spirit within them, and cause them to walk in his ways,
and to keep the statutes and judgments which God writes in this new book,
even the renewed heart; for this is the book of the new covenant,
these are the tables thereof, wherein God writes the law of life eternal for his Israel,
wherein they are to read, and live forever.
And happy is that Israelite who waits for, and receives, the Spirit.
To him none of the commandments of life are grievous,
being all quickened to him in and by the Spirit.
So that the more the Lord writes in his heart, the happier is he;
he thereby receiving more of the life and power of God`'s Spirit,
and learning thereby more of his God,
and travelling there-through further with him into his purity and divine sweetness.

[.discourse-part]
Question 5. What way is there for Israel to come by this cure?

[.discourse-part]
Answer.
None but God`'s covenant, the covenant which God made with their fathers.
Not the covenant of the law by Moses, but the covenant before the law,
which was also renewed by Moses,
but was not that covenant which God made with them in Horeb, but a covenant besides,
as they may read, Deut. 29.
Alas, alas! man can never come to life by his obedience; he still falls short there;
but by receiving the promised seed, he comes to be heir of the promise with the seed,
and finds the obedience of the seed brought forth in him,
through the grace and mercy of God, which breaketh forth upon his Israel.
Oh that the hearts of Israel after the flesh were circumcised to hear this sound!
that they might be turned in spirit towards the God of life and salvation,
that from him they might receive the seed of life into their vessels,
that their hearts might be purified and made living by the seed,
and they might there meet with that,
which their fathers could never meet with by the law of Moses;
nor indeed is never so to be obtained, but by the promise to their fathers,
which was before the law.
And this must be the way of their restoration into favor with God; to wit,
not the covenant which God made with their fathers,
when he took them by the hand to bring them out of the land of Egypt,
but the covenant by which God writes the law and knowledge of himself in the heart. Jer. 31:32-33.

[.discourse-part]
Question 6. How may Israel come into this covenant with God?
Or is there any thing for them to do, that they may enter into it,
and reap the blessings of it?

[.discourse-part]
Answer.
They must mind the small beginnings of it, and subject to God therein,
that they may know its further growth and progress in them.
He that withstands the beginning of a thing can never come to the end thereof.
Now the blessedness is chiefly in the end;
but it is not found and enjoyed but by him that meets with the beginning,
and so by degrees travels along till he comes to the end.
And here is a great mystery, which the wisdom of man cannot learn or understand; in that,
though the greatest blessings are contained in this covenant,
yet the beginnings of it are the smallest and most contemptible.
The seed of the promise, the seed of the kingdom, is the least of all seeds.
Man easily overlooks it; or if he have a little glimmering of it, readily despises it,
as unlikely ever to have that in it, or to bring that to pass for the soul,
which it desires and expects.
Yet there is no other way to the kingdom,
but by this seed of the kingdom opening and growing in the heart,
and gathering the heart into itself,
leavening it (by its spreading) with the leaven of life eternal,
and purging out the sour leaven of sin and death.
This then is the path of life;
thou must wait to feel the seed of the kingdom sown in thy heart by the good seeds-man,
and then wait for thy gathering into it, and growth in it; and by thy subjection unto it,
and its overspreading thee with the power of life eternal (which is in it,
though hidden from thee), thou wilt find sin and death, and the power of hell,
vanquished in thy heart,
and thy heart fitted for the God of thy life to dwell and appear in,
whose dwelling and appearance there will make thee completely happy.
Only if thou wouldst come out of thy captivity by the enemy of
thy soul (whereof thy present outward captivity is but a shadow),
into the life and rest of thy God; take heed of despising the day of small things,
or the low voice of thy God in thy heart; for therein are the beginnings of life.
And thou must begin at the lowest step that the God of thy
life chooseth for thee (and find that wisdom shut out,
which would begin or go on otherwise than the Lord seeth fit to
lead and teach) if ever thou enter into the path of life,
or walk on therein with thy God.

[.discourse-part]
Question 7. How may I know this seed of life, or feel when God begins to sow it in my heart,
that I may not turn from the small beginnings thereof,
but may find an entrance into this blessed covenant
of God with my fathers before the law?

[.discourse-part]
Answer.
The word or voice of this seed is nigh thee,
and it hath a living testimony with it for good, and against evil.
It hath a living sparkling in the heart,
whereby it is felt and known by those that wait for its appearance.
It naturally turneth from the evil and towards the good;
and in its moving and appearing in thee,
it will be turning thee towards that which it naturally loves,
and from that which it naturally hates.
In any such stirring in thy heart,
there is the beginning of light eternal to shine upon thy tabernacle;
and by giving up and being gathered into its warnings and motions,
thou wilt feel a touch of life, even a quickening and warmth towards good,
and a beginning of deadness and disunion with that which is evil.
And as this is waited for more and more,
it will appear more and more in the seasons it sees fit;
and as it finds entrance into thee, so will it lead thee into its covenant with its God.
Remember, therefore,
what Moses said to thy fathers concerning the word
of this covenant "`It is very nigh unto thee,
in thy mouth and in thy heart,
that thou mayest do it.`" Duet. 30:14. Thy fathers
never knew the virtue of this covenant,
but were drowned in misery for want of minding it.
And if thou wert gathered into it, thou wouldst meet with circumcision of heart,
and the new creation of thy mind and spirit,
and the writing of the eternal law of life there,
and the putting of the Holy Spirit of God into thee;
all which are contained in this covenant, yea, wrapped up in the very seed thereof,
which is (in the Lord`'s times and seasons) smiting the
seed of the evil-doer in the hearts of the sons of men,
and striving to gather them out of the disobedient state and nature,
into the obedience of the glimmerings of light in their hearts;
which becomes a law of life and power in them, as it finds entrance into, and place in,
them.
Therefore, O ye sons of Abraham after the flesh, wait for, know,
and believe in the light of this covenant,
and give up to be gathered into the holy seed thereof,
that ye may become his children after the Spirit, in this new covenant,
in this living covenant,
wherein all that enter live in Spirit and power to the God of Abraham;
and not by the works of the law of Moses, but by faith in the living seed,
become heirs and inheritors of the promise of eternal life,
which is to Abraham and his seed forever.

O poor wandering Jew! wait to hear the cry of wisdom`'s voice in thy streets,
discovering unto thee, and counselling thee against, the evil of thy heart and ways,
by the Word which is very nigh thee, in thy mouth, and in thy heart.
And be won upon by the voice of wisdom; give it thy heart, let its power enter into thee.
Take up its cross, be willing to be bound by it from what thy heart would run after,
and learn of it to draw in its yoke, that all may be yoked down and subdued in thee,
which makes thee miserable, that thou mayest find a place and honor in wisdom`'s courts,
and be adorned with her ornaments, and partake of her durable riches.

Watch unto that which reproves thee in thy heart, and watch unto its reproofs,
that thou mayest be reformed by it, and transformed into its nature,
and then thou wilt become a Jew indeed; even a Jew inward,
born of the immortal seed of the divine wisdom.

And be not discouraged,
either for want of light to distinguish between the good and the evil,
or for want of power to turn from the one or to the other, O tender-hearted ones,
who find a warmth and a willingness within to give up to the Lord: but wait his season,
and hope in his tender bowels,
in the midst of all the roarings and cruel usages of the enemy,
who will be striving to the utmost to keep his hold of his captive,
and to keep it back from travelling out of his dominions of death and darkness,
towards the land of life, light, and peace eternal!
I have had a very hard travel, and have felt his power and cruelty beyond measure,
yet the Lord my God hath helped me,
and my breathings abound toward the God of my life for his
helping hand unto all that are in heart turned towards him,
how difficult, intricate,
and impossible soever the enemy strives to make the path of life unto them.
Oh! remember the mercy of the Lord towards your fathers,
who never felt the strength of the love of this covenant,
which the Lord is now gathering his spiritual Israel into; how he pitied them,
how he forgave them, how he visited them with lovingkindness and mercy time after time!
What a stiff-necked people they were when he first
chose them! how ready to run a whoring from him,
and rebel afterwards!
And surely much more is to be forgiven in this covenant,
and much more is the help and healing thereof; only let the heart be true to him,
according to the virtue and power of this covenant; yea,
and wait to receive that also of him;
for it is the fruit and blessing of the covenant
in which God healeth the backslidings of his Israel,
and loveth them freely.
Amen, amen; O Lord God of everlasting and most tender bowels of compassion, saith my soul!

ISAAC PENINGTON.
