[#order-gov-church, short="The Order and Government of the Church of Christ"]
== Some Queries Concerning the Order and Government of the Church of Christ

Query 1. WHETHER Christ, who is the head, Lord, King,
etc. hath not appointed a spiritual order and government to be in his church and congregation.

Query 2. Whether a spiritual order and government is not useful, profitable,
and necessary,
for the well-being and right-managing of this spiritual body and
holy society in the faith and life of our Lord Jesus Christ.
In natural societies, natural government and order is profitable and necessary;
and is not spiritual government as profitable and necessary in spiritual societies?

Query 3. Did not Christ give power of government to his apostles and ministers,
at the first publication of his everlasting gospel?
All power was given him in heaven and in earth; and did not he,
who had all power given him, give power to his apostles and ministers,
to preach his everlasting gospel to the world, to gather his sheep out of the world,
and to watch over them, oversee them, reprove, exhort, admonish,
build up in the holy faith, and cut off and cast out that which was unholy,
and would dispute against, but not submit unto, the Spirit, life, and power of truth?

Query 4. Did not Christ give them gifts also answerable; spirits of discerning,
that they might be eyes to the body; and quick ears that they might hear for the body?
For though the Lord hath given every one an eye and an ear, as to themselves;
yet every one is not made by the Lord an eye or ear unto the body;
but this is appointed for, and given to, those to whom the Lord pleases,
who hath ordered all things wisely, carefully, and tenderly for the good of all.

Query 5. Were there not titles given them suitable
to their offices and services in this kind,
as pastors or shepherds after God`'s heart, according to the promise of the new covenant,
overseers or bishops, such as watch for the soul;
such as were not only to lay the foundation,
but also carry on the building even to perfection,
even till they were able to present the gathered
and quickened souls a chaste virgin to Christ?
and were they not to watch against, testify against,
and in the power and authority of the Lord to strike at, all that was contrary,
and would endeavor to interrupt, overturn, and destroy their work, which was of, in,
and from, the Lord?

Query 6. Whether the body and common members of the churches
were not to hearken to these ("`He that knoweth God,
heareth us.`" 1 John 4:6); to obey them in the Lord, to submit to this ministry,
and their work in it, in the Lord;
to receive the word of truth and holy exhortations and admonitions,
milked out by these to them from the breast of life.
And were not they that did hearken and obey commended?
And were not the other that were not subjected, but slighted them,
and their ministry and authority, testified against as disorderly and unruly?

Query 7. Were there not some relics of this order and government all along the apostasy,
in the true church and ministry thereof?
For there hath been a church and a ministry all along the apostasy,
blessed be the name of the Lord; though not so visible and outwardly glorious,
as many (who have erred from the Spirit and way of truth,
and are out of the holy understanding) would make it.
It is true, the church hath been as in a wilderness, desolate, as a woman forsaken,
as a widow, bereft of her husband, stripped of her children, her visage marred,
her witnesses mourning, nothing of her beauty, former estate, or glory,
to be discerned or found out; yet all hath been preserved in the root,
and there have been some shootings and sproutings of it forth,
which have been inwardly felt by that which is of God in the heart,
though not outwardly seen by man`'s eye.
Thus the witnesses have had a ministry, have had the testimony of Jesus,
even the Spirit of prophecy, all this dark night of apostasy,
and in it have spoken mourningly to the world, and to the captivated souls,
which that which was of God in his hath hearkened to;
and there hath been a bowing and subjection of spirit in the Lord.
Oh read this, and praise the name of the Lord,
for his mercy to his in former generations,
ye who are now gathered into his pure light and living power,
from whom the night is past, and on whom the day, the everlasting dayspring from on high,
is risen!

Query 8. After the apostasy, doth not God renew his commission,
and send forth his angel (for they are all but one) to preach his everlasting gospel?
And doth not he give them power to preach to the world, and to gather those,
that hear the everlasting voice through them, into holy assemblies, separated in spirit,
nature, and appearance from the world?
And have they not authority and gifts, as well to build up as to plant?
And ought not those that are gathered by them, as well to be subject to the light,
Spirit, power, and authority of the Lord in them,
as the former to the former ministers of the Lord?
Oh that the world knew them!
Oh that the world knew the appearance of God in them!
Surely then they would bow to the word of truth, and the glorious appearance thereof;
and happiness both inward and outward would break forth upon the earth.
There would be no misery, sorrow, nor distress in nations,
if the dispensations of life from God had but their course in the earth; yea,
nations and persons, that are now deadly sick, would soon be healed,
did they but eat of the leaves of the tree of life,
which are appointed by God for their healing, and can easily heal those wounds,
and repair those breaches, which the wisdom or counsels of man cannot heal or repair.
And oh,
that they that are gathered might keep and be preserved in that sense and subjection,
which they had and received from the Lord in the day of their convincement!
Oh, how beautiful, how precious,
how glorious was the ministry and ministers of God in their eye then!
And to those that are still there, they are still precious; and to those that grow there,
they are yet more precious.
But those that enter into, or are ensnared in another thing,
which leadeth from the true Spirit, lose the sight and sense which they then had,
and instead thereof are filled with prejudices and wise reasonings,
which to them may seem very strong and undeniable, though truth,
and the true spiritual eye, sense, and understanding easily pierces through them,
and preserveth those, who abide single in it, to the Lord.

Now against this holy order and government appointed by God, there may arise,
in some hearts, some such objections as these following.

[.discourse-part]
Objection 1. But is not this a turning away from the measure of life in a man`'s own vessel,
to another man`'s measure?

[.discourse-part]
Answer.
Waiting on God in his ordinances and appointments,
and upon the ministry which he hath set up, the measure of life in him teacheth;
and it is not a turning from the measure,
but a subjecting to the Lord in the measure of his life, so to teach and do.
The measure of his life taught me thus to do at first, and teacheth me to do so still;
and will teach so still, all that hearken to it.
It did not teach subjection in the apostles`'s days to the ministry then,
and another thing now to the ministry now.
But Christ is the same today as yesterday; his life the same, his Spirit the same,
its doctrine and teaching the same:
and that of God in the conscience within answers
the pure voice when it comes to the ear without.
If life speak in one vessel, and its voice be not heard or owned by another vessel,
the pure ear (in that other vessel) is not at that time open,
but there is somewhat there that obstructs.
And if the pure ear of the sheep be not open to hear the voice of the Shepherd,
but it be accounted strange,
it is much if the other ear in that vessel be not opened to hear the voice of the stranger,
and to look upon it as the voice of the Shepherd, it agreeing with that,
and answering to that,
which now goeth for the voice of the measure of life in that heart.
He that hath an ear, let him hear; for it is easy being taken in this snare,
and the danger thereof is very great.

[.discourse-part]
Objection 2. Is not the least measure of life in any vessel (if subjected to, waited on,
and believed in) sufficient to instruct and build up into a perfect man in God?

[.discourse-part]
Answer.
The sufficiency of the grace of God, turned to, and waited upon,
there is nothing in my heart either to undervalue myself, or to teach others so to do.
Nor when God did appoint a ministry to gather and build up his church,
do I believe he did intend therein to undervalue the sufficiency of his grace: yea,
I verily believe, that the grace of God, turned and hearkened to, and followed by,
any soul in the darkest part of the earth, hath sufficiency in it to save,
and will save that soul, though there be none outwardly to minister to it, or help it.
Yet this I also believe,
that as there is a sufficiency in every measure of
life to the work God hath appointed for that measure;
so there is a greater sufficiency in the growth and fuller proportion of life;
and the lesser, the weaker, the poor, the afflicted, the babes,
are to be helped by the stronger, especially in their darknesses, afflictions,
temptations, etc.
And so the greater and stronger in the life, Spirit, and power of the Lord,
is a strength and blessing to the weaker;
which the weaker making use of in the guidance of the Spirit of
the Lord (in the sense and benefit of the sweet help and relief
which often the Lord pleaseth to give forth thereby),
will find just cause, and be often drawn, to bless the name of the Lord for.

The measure of life in the vessel teacheth to subject to the Spirit of the Lord,
and his life in others; which the measure of life in any never refuseth,
but still knoweth (when awake and living in the vessel) its own, and hath, at least,
a secret sense of it, and unity with it.
But that which pretends to set up the measure of life as a teacher,
otherwise than God hath appointed,
and in opposition to the teaching and ministry which he hath appointed,
and to his gift in those vessels,
which is as well for the building up the perfecting of the body, as for the gathering;
that is another thing in that vessel that doth so, than the measure of life;
another spirit, another nature, another ear, than that that first heard.
And though it seem to cry up the sufficiency of the measure of life,
and to plead for that (and perhaps the creature thinks it is really so);
yet this is not the intent of the spirit in the vessel, but to cry up itself,
and to make its voice go for the voice of the measure of life:
and so such err from the faith, the truth, the Spirit, the measure of life,
and are in the nature, spirit, and measure of another thing; which is indeed death,
though they see it not, but look upon themselves as gloriously living,
and abiding in the pure doctrine and principle above others.

Now to help these a little out of the snares and deep entanglements of the enemy,
if the Lord please, I would earnestly press the consideration of this upon them.
Did not the apostles preach up the measure of life, the grace of God in their day,
Christ within, the word of faith nigh in the mouth and heart, the anointing within,
its sufficiency to teach all things, etc.
And yet did they so preach it as to overthrow the ministry,
or the gifts or service either towards them that were without, or them that were within?
Had they not power over them in the Lord?
Were they not to teach them, to instruct them, to build them up in the holy faith,
and also to watch against wolves and devouring spirits,
which would strive to enter the flock in sheep`'s clothing, and,
as preachers of righteousness,
to make a prey of the innocent life in the upright-hearted, if possible?

[.discourse-part]
Objection 3. But those who have ministered from the Lord, and whose ministry I have felt and owned,
and in the distress and affliction of my soul have had recourse to,
hoping that they might have a sense of my condition, and give me proper advice; yet they,
instead thereof, have turned me to his witness that wounded me,
counselling me to wait on the Lord there, and have they not also told us,
that if they themselves should turn from the things they have declared,
this truth would abide forever; to wit,
that man is to keep to the measure of life in his particular?

[.discourse-part]
Answer.
It is true; a man is to keep to the measure of life in his own particular.
They taught this then; they teach it now.
We practised it then; we are to practise it now.
In this measure of life we received them then;
and in this measure of life (if we abide still in it) we shall receive them now,
and feel their growth in the ability, gift, and power of the Lord.

And when any come to them for advice, they are to wait on the Lord,
to feel in him their state who come, and to give forth what the Lord gives them;
whether words from the Lord to the party concerning his state,
or directions to retire in, and wait for,
his more immediate appearance in their own measures.
For when we feel the presence and mighty power of God in them,
we are too apt to look at them,
and then a word may come (proper to our estates) to recall us to retire to our measure.
And when we feel immediate relief from the Lord,
and his appearing to us in our retiredness in our own spirits,
then we may be apt to despise the gifts and service of others;
and then another word may come from them, proper to our state then,
to warn us not to despise prophesying, or the gifts, power,
and authority of life in others.
Now both these are proper, useful, and weighty in their seasons,
when given forth by the Spirit of the Lord.
Nor are they contradictory one to the other, but subservient in their seasons and places,
which that which is of God feels; but that which is erred from God,
and joined to another (under a false representation and belief of things) feels not,
but finds a seeming difference, and sets them at variance one with another,
as if they could not stand together.
And this is the false nature, the false spirit, the false appearance of life,
which appears as if it were the measure of the pure, true life, but is not.
This is the false woman, the false wisdom, whose heart is as snares and nets,
and her hands bands.
Whoso pleaseth God (abiding in the measure of his truth) shall escape her;
but the sinner (that departs therefrom) shall be taken by her.
Therefore fear the Lord, come to that which first convinced; to the first truth,
to the first sense, to the first love, etc., and all these imaginations of the mind,
and subtle devices of the enemy, will fly away, and thy poor entangled soul be delivered,
as a bird out of the snare of the fowler.

If the enemy should directly cry out against God, or his Christ, or his grace,
or the measure of his truth, he would easily be espied and turned from.
Therefore he teacheth to cry up these in a wrong spirit and judgment,
and after a wrong manner, to undermine, betray, and lead the heart from that secretly,
which openly it would never hear any thing against.
Now those that are thus deceived, are exceedingly to be pitied,
and their deliverance from their entanglements and captivities to be breathed after,
and waited for.
For I may say, in truth and upright sense of heart,
there are many that look towards Zion,
who yet are ignorant of the devices and sleights of Satan, to entangle them in their way;
and some are caught in his snares (like foolish birds catching at the chaff,
which makes the bigger show, instead of the wheat), losing the substance for a shadow;
the life and power in the heart, for a notion and conceit in the brain.
And these are wise in their own eyes,
so that indeed it is very hard to reach or recover them; yea,
much harder than it was at first,
because they are become more rooted and settled in the wrong ground (yea,
in a worse earth) than they were when they were first reached to by the power of truth.
Yet over these there is a deep lamentation, and for these a sore travel,
which the Lord God bless and prosper, for their recovery unto that from which,
through mistake, they have erred.

[.discourse-part]
Objection 4. If any man hath received a gift of ministry, he hath received it of the Lord;
and its end being to gather to the Lord, they that by it are gathered,
are to be delivered up to the Lord, that he (as king, priest, and prophet) may govern, etc.

[.discourse-part]
Answer.
The end of the ministry is not only to gather,
but also to preserve and build up what is gathered, even to perfection.
And the soul being (especially at first, if not for a long time) weak and babish,
not so fully acquainted with the measure of life (having
had but some touches and demonstrations of it,
but not being gathered fully into it, nor rooted and settled in it); I say,
the soul in this state, hath as much need of the ministry to preserve, direct,
and watch over it in the truth, as to gather it out of the world.
Therefore the Father, in his tender mercy and love,
hath appointed those who are grown in his life (and
in the power and authority of his Spirit) to oversee,
watch over, instruct, and take care of the flock,
so as they may give to him an account of their souls; and in their care, diligence,
and faithfulness, they are owned and blessed of the Lord;
and the other in their holy fear, reverence, and subjection.
Now this is right order from God, wherein the safety of the flock consists;
but out of this is danger and confusion, which the measure of life teacheth to avoid.

[.discourse-part]
Objection 5. But in a case of doubt or difference, which shall be the judge;
the measure of life within, or the testimony of others without?
Shall I judge as I feel the thing in the measure of my own life?
Or shall I submit to others against my own sense and judgment,
because I have an esteem of them, as being much above me in the growth, sense,
and understanding of truth?

[.discourse-part]
Answer.
It is a great matter to judge aright, and to discern and

know the measure of truth (the voice, motion,
and judgment thereof) from all the enemy`'s false appearances,
and from all the deceits of the heart.
This is most certain; Jerusalem (the heavenly building,
the church of the first-born) is at unity with itself.
Truth is pure, eternal, unchangeable, always the same; the same in every member,
in every vessel, throughout the whole body.

And this I may say concerning its appearance in this our age,
Was ever the like unity known and brought forth since the days of the apostles?
How hath the Spirit been One, the demonstration and testimony of truth One,
the doctrine One, the conversation and practices One in us all!
Why, or how so?
Because we have had our begetting, birth, and teaching from the same life,
the same Spirit; the same fountain springing up, and opening in us all,
that have been gathered into its nature and power.
Now from this fountain, from this spring of life,
never issueth any thing that is contrary to the life in any.
Therefore if there appear a contrariety,
there must be a waiting to feel who is erred from,
or at least not yet fully gathered into, the measure of life.
And such as are of an inferior stature and growth in the body,
are (in an especial manner) to watch and wait in sobriety and fear,
till the Lord clear up, and make things manifest;
and likewise in the mean time to take heed of a hasty concluding,
according to what riseth up in the understanding or judgment
(though with ever so great a seeming clearness and satisfaction)
as if it must needs be of and from the life in the vessel.

It is not an easy matter, in all cases,
clearly and understandingly to discern the voice of the Shepherd,
the motions of God`'s Spirit,
and certainly to distinguish the measure of life from all other voices, motions,
and appearances whatsoever.
Through much growth in the truth, through much waiting on the Lord,
through much fear and trembling, through much sobriety and meekness,
through much exercise of the senses, this is at length given and obtained.
And yet there is a preservation in the mean time to that which is lowly and submissive,
looking up to the Lord continually, and not trusting to its own understanding, sense,
and judgment.
But that which is hasty and confident,
and so ready to plead for its own sense and judgment, according to the measure of life,
as it calls it; that is commonly out, entered into the erring spirit,
pleading and contending for it knows not what,
and is very apt to judge and condemn others in that very respect,
wherein itself is most justly and righteously judged and condemned by the Lord,
even by his pure life and Spirit in his people.

This then is in my heart to say in short to this objection:
Let the measure of life judge freely in thee at any time concerning any thing,
and that judgment will stand forever.
But be thou wary, wait on the Lord,
that thou mayest be sure thou dost not mistake in thy own particular,
calling that life which the Lord and his people know to be otherwise.
For if so, thou departest from the unity and bond of the Spirit,
and from the true sense and judgment, and givest deceit an advantage over thee,
even to lay a foundation of destroying thee.
Likewise those who are to watch over thee in the Lord (to lay this truth before thee,
to exhort and reprove thee,
as occasion is) that they may give an account of thy soul to him,
cannot do it with joy and rejoicing in his presence,
but with grief and lamentation of heart; which is not at all profitable,
but very unprofitable for thee.

Now for a close: there are some considerations springing up in my heart concerning unity,
which I find drawings here to annex, in true love and tenderness,
for the use and service of others; which are as follows:

1+++.+++ Unity in the spiritual body,
which is gathered into and knit together in the pure life,
is a most natural and comely thing.
Yea, it is exceeding lovely to find all that are of the Lord of one heart, of one mind,
of one judgment, in one way of practice and order in all things.

2+++.+++ The Lord is to be waited upon for the bringing forth of this in the body;
that as there is a foundation of it laid in all (the life and spring being over all),
so all may be brought by him into the true and full oneness.

3+++.+++ The Lord is to be acknowledged and praised in the bringing
of it forth (so far as it is brought forth),
and to be waited upon for the further perfecting of it.

4+++.+++ A watch is to be kept (throughout the whole body,
and in every heart) for the preserving of it, so far as it is brought forth,
that the enemy, by no device or subtlety, cause disunion or difference in any respect,
wherein there was once a true unity and oneness.
For the enemy will watch to divide; and if he be not watched against,
in that which is able to discover and keep him out,
by some device or other he will take his advantage
to make a rent (in those that are not watchful),
from the pure truth and unity of life in the body.
For he that in the least thing rents from the body (in any
respect or particular which was brought forth by the life),
he in that respect hearkens to another spirit, even the dividing spirit,
and by its instigation rents from the life itself, and so doth not keep his habitation,
nor his unity, with that which abides in its habituation.

Now it is also in my heart, for the perfecting of this close,
to mention a few things (in the same love and tenderness) which I have
found helpful to me towards the preserving of me in unity with the body.
Perhaps it may please the Lord to refresh some others by the mention of them,
and to make them useful and helpful to them also.

1+++.+++ The first is, the pure fear of the Lord.
This poiseth and guardeth the mind,
keeping down fleshly confidence and conceitedness (which is very apt to spring up),
making it wary and considerate either of what it receives or rejects;
of what it practiseth, or forbeareth practising; causing it to wait much, try much,
and consult much with the Lord, and with his ministers and people,
and preserves out of that suddenness and inconsiderateness of spirit,
at which the enemy often enters.
For truth is weighty, and will bear trial, and the more it is tried in the balance,
the more manifest its nature and ways appear:
but the enemy`'s appearance and likenesses are not so; but their deceit,
by a thorough trial, comes to be made manifest.

2+++.+++ The second is, humility of heart.
This is very precious, and of a preserving nature.
Yea, in this state the Lord helpeth and teacheth;
and the soul also (in this state) is fit to receive the help and teachings of the Lord.
That which is lifted up and conceited (ready to justify its own way,
and condemn even the whole body) is neither fit to be taught by the Lord,
nor doth the Lord delight (but rather disdain) to teach it.
And so not being taught by him, it must needs be liable to err; yea,
to hearken to that spirit,
whose voice is more pleasing and suitable to the erring mind than the Lord`'s voice is.

3+++.+++ A third great help, which in the tender mercy of the Lord I have had experience of,
is sobriety of judgment.
Not to value or set up mine own judgment,
or that which I account the judgment of life in me, above the judgment of others,
or that which is indeed life in others.
For the Lord hath appeared to others, as well as to me: yea,
there are others who are in the growth of his truth,
and in the purity and dominion of his life, far beyond me.
Now for me to set up, or hold forth,
a sense or judgment of a thing in opposition to them,
this is out of the sobriety which is of the truth.
Therefore, in such cases, I am to retire, and fear before the Lord,
and wait upon him for a clear discerning and sense of his truth,
in the unity and demonstration of his Spirit with others, who are of him, and see him.
And this will prevent the rents which the want of this sobriety may occasion.

4+++.+++ The last thing which I have now to mention is, ten-derness, meekness, coolness,
and stillness of spirit.
I wrap up these together, because they are much of a nature, and go much together.
These are of a uniting, preserving nature.
He that differs and divides from the body cannot be thus;
and he that is thus cannot rend or divide.
This is the pure, heavenly wisdom, which is peaceable and keepeth the peace;
but the other wisdom is rough, stiff, hard, clamorous, ready to take offence,
ready to give offence; exceeding deep in the justification of itself,
exceeding deep in the condemnation of others;
and dares (in this temper) appeal to the Lord, as if it were right in its ways,
but wronged by others; as if it did abide in the measure of his truth and life,
which others have departed from.
And how can it be otherwise?
How can the wrong eye, the wrong spirit, the wrong wisdom, but judge wrong,
justifying the wrong practices, and condemning the right?
But such shall find (if they come to the true touchstone,
even the measure of life indeed) that they are not in the true tenderness,
which proceeds from the life, in the true meekness and gentleness,
in the true coolness and stillness; but rather in the reasonings, noises, clamors,
and disturbances, which arise from another spirit, mind,
and nature than that which is of the truth.
And in coming back from this wisdom to the pure wisdom,
from the pretended measure of life to the true measure, and becoming tender, meek, cool,
and still in it, they shall there feel their error from the Spirit and power of the Lord,
and therein own their condemnation therefore from him;
and also justify them who have abode in the power,
and been guided by the Spirit and pure measure of life, which is from God, and in God,
while they have departed from it.
For though the spirit of error (wherewith they have been deceived and entangled) hath
made them believe that they have faithfully abode in the principle and doctrine of truth,
while others have departed; yet that will soon vanish, as truth comes again to be felt,
and heard speak in them, and the measure of life to live again in them,
and to redeem them afresh into its holy nature, and pure, living sense.
And blessed is he who is not deceived about truth; but is of the pure nature,
and in the pure power of it; in whom the true eye sees, the true ear hears,
the true heart understands; who is of a right spirit,
and walketh uprightly before the Lord, and among his people.
The blessing of the seed, the peace, comfort, and joy which is from the Most High,
shall descend upon him, fill his vessel, and continue with him,
to the satisfying of his heart, and the overflowing of his cup,
in the midst of his brethren, and in the very sight of his enemies.
The Lord God, of his tender mercy, who is the great Shepherd of the sheep, watch over,
preserve, and mightily defend all his from all devouring spirits,
and inward devices and deceits of the enemy;
carrying on and perfecting the work of his goodness, love, and mercy in them,
to his own glorious, eternal, everlasting praise.
Amen.

Written by ISAAC PENINGTON, in Aylesbury prison
