[short="Deep Considerations Concerning the State of Israel"]
== Some Deep Considerations+++<br />+++Concerning the State of Israel / Past, Present, and to Come / With Some Questions and Answers Concerning Unity

Many deep considerations have been upon my heart concerning the state of Israel,
both past, present, and to come; some of which I find drawings to communicate;
together with some QUESTIONS and ANSWERS concerning UNITY.
The Considerations concerning Israel are these which follow:

The precious living state which my soul remembereth to have
been about the beginning of the late troubles of this nation,
when Israel was bent to seek after the Lord,
and applied their hearts to wait upon him in fastings, and earnest supplications,
wherein my heart hath often had the testimony that they were accepted of him,
and had many times the seal of his presence and power among them: yea,
my heart did truly unite with and enjoy the Lord in what was then given forth,
and I can never be drawn to deny the truth and worth of that dispensation;
though I know it was swallowed up by a greater desolation soon following after,
and since by the breaking forth of a more lively dispensation.

[.numbered-group]
====

[.numbered]
2+++.+++ The over-running of that state by the subtlety of the enemy,
drawing the minds of the simple and upright-hearted from the living feeling,
and from the inward power of religion,
into the disputations and contentions about forms of worship and church-government,
which drew out the reasoning part,
and withdrew the spirit of the mind from feeding on its proper nourishment;
and so life decayed in the spirit, while wisdom, and knowledge,
and subtlety increased in the understanding.
And so the upright-hearted, missing of life where before they had found it,
were scattered up and down to seek after it; and those who abode where they were,
grew dry, barren, and contentious; losing the savor, sweetness, meekness, love,
and indeed whatever was living and precious,
and remained fixing their minds on that which the Lord had departed from.
Oh, the darkness and misery of this state!
Oh, the pain of the hearts where life was stirring, for want of the living God!
Oh, the death and formality of those that were dead and formal!
Surely, had not the Lord pitied his people in this state,
and appeared to them in his life and power (which this great desolation made way for),
it had been determined concerning Israel forever:
for death had overgrown the generality,
and life was even gasping and expiring in the single-hearted.

[.numbered]
3+++.+++ The precious breaking forth of the Lord (at this dismal time,
in this hour of distress and desperate condition of Israel) in some hidden vessels,
whom he had kept waiting upon him, and whom he had preserved fresh in the sense of him;
to whom his appearance was very glorious, to whom he opened the state of the earth,
and the state of his people,
giving them the everlasting gospel to preach to the inhabitants of the earth,
and promising them that his Spirit and power should go along with them,
bidding them go forth to till and dress the earth,
and to gather his people into his fold.
And who can utter what the glory of this light was,
in its shining and breaking forth in their hearts!
How welcome to their weary souls, how pleasant to the eye of their spirits,
how demonstrative and satisfactory to their hearts!
Oh! the joy of that day (surely it can never be forgotten by them) wherein
they sensibly felt the pouring down of the Spirit of life upon them,
and their hearts gathered into the bosom of eternal rest,
and their souls and bodies sanctified, and set apart for the Lord and his service.

[.numbered]
4+++.+++ The contemptible means God put into their hands to work this work by;
which was not by preaching any new thing,
but by directing to a principle which God had already
hid in the earth of every man`'s heart,
and which was to be known by its divine nature and light,
turning against and reproving sin;
testifying that this was the way the Lord of heaven and earth had chosen,
to bring his sons and daughters into the power and glory of his life.
Oh! what heart can receive this, what eye can see any beauty in this,
but that which the Lord toucheth and openeth!
I testify, in the sense of life, that the wisdom of man, yea,
the wisdom of Israel corrupted, cannot but despise and turn from this.
Is not this the lowest of all dispensations?
Is not this common to all mankind?
Doth not this fall short (in itself, as I may say,
and as it hath formerly been dispensed) of the dispensation
of the law of Moses to the Jews,
much more of the dispensation by Christ and his apostles?
Who would have looked for the Lord here!
And yet this hath the Lord chosen to gather his people by, and to appear to the world in;
and hath gathered the life, virtue, and substance of all former dispensations into it,
as those who are gathered thereby, and have waited upon him therein,
and felt the nature and power of his life, (and seen things past, present,
and to come) are living witnesses of, against all the gainsayings, thoughts,
and reasonings of flesh and blood.

[.numbered]
5+++.+++ The contemptibleness of the vessels, which the Lord chose to fill with this treasure,
and to let forth this dispensation of his life through.
They were for the most part mean, as to the outward; young country lads,
of no deep understanding, or ready expression,
but very fit to be despised everywhere by the wisdom of man,
and only to be owned in the power of that life wherein they came forth.
How ridiculous was their manner of coming forth and appearance to the eye of man!
About what poor, trivial circumstances, habits, gestures, and things,
did they seem to lay great weight, and make great matters of moment!
How far did they seem from being acquainted with the mysteries and depths of religion!
But their chief preaching was _repentance, and about a light within,
and of turning to that,
and proclaiming the great and terrible day of the Lord to be at hand;_
wherein I confess my heart exceedingly despised them,
and cannot wonder that any wise man, or sort of professors, did, or do yet, despise them.
Yea, they themselves were very sensible of their own weakness,
and unfitness for that great work and service wherewith the Lord had honored them,
and of their inability to reason with man;
and so (in the fear and in the watch of their spirits) kept close to their testimony,
and to the movings of his power,
not mattering to answer or satisfy the reasoning part of man,
but singly minding the reaching to, and raising of, that to which their testimony was.

[.numbered]
6+++.+++ The blessing that God gave to this his dispensation of life in their hands.
Oh, how did the Lord prosper them in gathering his scattered,
wandering sheep into his fold of rest!
How did their words drop down like dew, and refresh the hungry, thirsty souls!
How did they reach to the life in those to whom they ministered,
raising up that which lay dead in the grave,
to give a living testimony to the living voice of God in them!
How did they batter the wisdom and reasonings of man,
making the loftiness thereof stoop and bow to the
weak and foolish babe of the begettings of life!
Eye hath not seen, ear hath not heard,
nor hath it entered into the heart of man to conceive,
what the power of life hath wrought, through them,
in the hearts and consciences of those, who have longed after, and waited for, the Lord.
Oh! the breathings and meltings of soul, the sense of the living presence of God,
the subjecting of the heart unto the Lord,
the awakening of and giving strength unto his witness,
the falling down and weakening of the powers of darkness,
the clear shining of the light of life in the heart,
and the sweet running of the pure streams thereof into the enlivened souls,
which hath often been known and sealed to from the
powerful appearance of God in their ministry!
Indeed when I have considered these and such like things in my heart,
and narrowly marked them in my converse with them,
I have been often forced to cry out concerning them,
_Truly here is man very weak and contemptible; but God very glorious and powerful._
And indeed, when at any time I looked on the man,
I was hardly able to forbear disdaining them; but, on the other hand,
when the eye of my spirit beheld the power and glory of the Lord in them,
I could hardly forbear overesteeming and exalting them.

[.numbered]
7+++.+++ The glory which the Lord advanced these vessels to,
since his beginning to make use of them.
How hath he enriched them with gifts and abilities,
and every way fitted them for the service and employment he hath had for them!
How hath he enlarged their ministry, that they who had very little to say,
either by way of declaration or disputation at first, now abound with strength,
and abundantly surpass the knowledge and wisdom both of the world,
and of other professors of religion!
The Lord indeed hath adorned them, putting his beauty upon them,
and causing them to grow up in his strength, and in his wisdom.
This mine eye hath seen, and often taken notice of, blessing the name of the Lord,
and praying to him for their preservation.
And surely whoever he be, that hath either known himself,
or heard the relation of the poverty of these young striplings,
when they first came forth in the power of the Lord,
how empty in themselves they then were,
how sensibly they went up and down of their own weakness,
how little they had to say to people that came to observe them and inquire of them,
how afraid they were to be drawn from their watch,
at what a distance they stood from entering into reasoning about things,--I say,
he that did know, and doth consider this,
and shall also behold how the Lord hath advanced them since,
making them mighty and honorable with his gifts and abilities (with the beauty whereof
the very man flourisheth to the sight of every eye that is in any measure truly open),
cannot but acknowledge the change to be wonderful.

[.numbered]
8+++.+++ I have had the sense and consideration of this also in my heart,
that their danger is now greater than when they were poorer, weaker,
and not so enriched and gifted by the Lord.
The enemy is very subtle and watchful, and there is danger to Israel all along,
both in the poverty and in the riches; but the greater danger is in the riches:
because then man is apt to forget God,
and to lose somewhat of the sense of his dependence
(which keeps the soul low and safe in the life),
and also to suffer somewhat of exaltation to creep upon him,
which presently in a degree corrupts and betrays him.
The heart that is in any measure lifted up in itself,
so far it is not upright in the Lord.
Let every one feel this, waiting to be preserved,
and praying for those who are most beautified by gifts and abilities from the life,
because in this respect (and at this time) their danger is greatest.
When Israel is poor, low, weak, trembling,
seeing no loveliness nor worthiness in himself,
but depending upon the mere mercy and tender bowels
of the Lord in the free covenant of his love,
etc., then is Israel safe.
But when he hath a being given him in the life,
and is richly adorned with the ornaments of life,
and comes to have the power itself in his hand to make use of,
then is he in more danger of being somewhat of himself,
and of forgetting him that formed him,
(being apt to make use of his gifts without such an immediate sense of the giver as
he had in his trembling and weak estate) and so of departing out of that humble,
tender, abased, contrite state, and temper of spirit, wherein he was still preserved.

[.numbered]
9+++.+++ This also hath been manifest to me, and deeply impressed on my spirit all along,
that the Lord may, if he see good, suffer some great and eminent ones to fall in Israel.
Man may forget himself, and the Lord may let out temptation upon him,
and suffer it to enter,
that he may bring him to the sense and feeling of his weakness again.
Yea, those who have felt the power of the Lord in and through an instrument,
may give more to the instrument than belongs unto it,
and so put the Lord upon recovering the honor due to him,
which is misplaced and misapplied to that which is but his instrument.
This is the Lord`'s day (the light thereof is his, the life his, the power his),
and the glory thereof will he not give to another.
If therefore any man, in this day, shall take to himself what belongs to the Lord,
or any other shall give it him, the Lord will not so lose it,
but will find out a way to recover his own.
And happy is the man who lieth continually perfectly abased before the Lord,
assuming nothing of the Lord`'s to himself,
nor attributing any thing of the Lord`'s to another,
that the Lord alone may be exalted everywhere.
And let all gifts serve the seed, and its rising over all gifts be waited for,
that the life everywhere may have its due, being lifted up over all.

[.numbered]
10+++.+++ I have had a deep sense of this also,
that if the Lord should suffer such a thing to fall out among us,
it may cause a great shaking and scattering in Israel.
Surely I may say, it would come very unexpectedly and unsuspectedly to many;
and so such persons would be surprised with it, and not at all prepared for it.
Alas! who could suspect (feeling persons so eminent in the power,
and so exercised and skillful in the way and paths of righteousness,
and so able to instruct others therein) that they could possibly
fall in any degree from the truth and power of life!
And yet they are not free from temptation:
and if they be confident of their own strength, and forget the tender hand of the Lord,
he may suffer a temptation to enter them,
which presently begets a ground for evil weeds to spring up in, and for blindness,
and hardness, and error from the pure power, to creep in at.

====

O dear friends! who know the preciousness of life,
and desire the preservation of the Lord in your several conditions, let us fear the Lord,
and his goodness to us, remembering what a low ebb we were at when the Lord visited us,
and how freely he visited, and how freely he daily preserveth,
that we may not be hardened or lifted up against the world,
or against any sort of professors;
but may magnify the grace which hath made and keepeth
up the difference between us and them,
praying to the Lord for them, and watching for the hour of his mercy to them,
exercising all manner of sweetness, and meekness,
and long-suffering towards them in the mean time:
also pitying and bearing with all the tempted ones among ourselves,
as such who are sensible that we also may be tempted,
and that understand the ground why we fall not by the temptation.

What shall I say more?
There are three QUERIES appearing in my view, in relation to this thing,
which the hearts of some may desire satisfaction about; to which I find somewhat,
in way of answer, springing up in me.

[.discourse-part]
_Query 1._ How may a man, whom the Lord hath exalted by gifts and services to him,
be preserved from falling?

[.numbered-group]
====

[.numbered]
_Answer 1._ There is that which waiteth to preserve, and is still stretching forth its hand,
to keep to itself that which it hath gathered;
which being hearkened and yielded unto in its discoveries, and warnings,
will not fail to deliver the soul from the danger and snares of every condition.

[.numbered]
2+++.+++ There is the free mercy and love of the covenant,
wherein the soul may find help and pity,
although it should be somewhat tainted and entangled with the snares of the enemy.

[.numbered]
3+++.+++ There is a proper frame or state of spirit; to wit, of humility and brokenness,
which is fit for Israel in every condition;
but more especially when he is exalted in the dominion and power of life,
and honored with great gifts and services for the Lord.
In this Israel is safe:
and happy is he who is not suffered to abide in any degree of exaltation of spirit;
but is brought down again (through the tender mercy and love of the Lord) into this,
though by the buffetings of Satan.

====

[.discourse-part]
_Query 2._ How may the little ones,
if the Lord should suffer one or more (of such as have been
very eminent in his service) to decline and fall,
how may they be preserved from falling with him or them?

[.discourse-part]
Answer.
Keeping to the measure of life in the particular,
and not valuing others by an apprehension concerning them;
but only knowing and honoring them as they are felt and discerned in the life;
this will preserve every particular (that is thus ordered)
from being tainted with any of their snares or deviations.
_O Israel!
O little babes?
know no man after the flesh; but the Lord alone in his living Spirit._
For man is but a vessel, wherein the life may appear or disappear at pleasure;
and the Lord is not engaged to make use of man in his service,
further than he seeth good.
The Lord may appear where he hath never appeared before,
and he may not appear where he hath hitherto appeared very frequently and powerfully.
Oh! know the life in thine own heart,
that is to be the judge in thee concerning the appearances of life in others.
If that judge not, be still and silent in thy heart, waiting for its judgment:
when that judgeth, let all thy thoughts and reasonings be bowed down under it.
Let man have no more than his due, while the Lord pleaseth to make use of him;
and to such there will accrue no great shaking or damage,
when the Lord layeth aside any of his own instruments.
But if any thing but the life judge, it will still either be setting up,
or throwing down, man: whereby there will come loss on either hand in the issue,
to all such who thus act.

[.discourse-part]
_Query 3._ How may any such,
as have fallen from a high and glorious state in the power and dominion of life,
be again recovered?

[.discourse-part]
Answer.
Indeed this is a very difficult thing:
not because the mercy and power of the Lord is at
a loss to or concerning man in this state;
but because this condition sets a man`'s spirit at so great a distance
from the use of that remedy which the Lord hath appointed for man`'s recovery.
It is very hard to bring such an one to the sense of his loss (whereby
the depth of his fall might be prevented) until he be gone very far;
and the further he goes in his declining from the life, the harder will his recovery be.
Again: it is hard for such an one to become so poor,
and lie so low and so long at the foot of God`'s grace,
as also to be contented to be so laid aside and not made use of,
as the Spirit of the Lord may judge necessary for him,
to bring him into a perfect abasement of spirit,
and to work that perfectly out of him whereby the enemy now entered to betray him: yea,
the judgment of the Lord (the righteous and severe judgment
of the Lord) is hard to be borne in this state;
and it is much if such a vessel do not break here, in its new forming on the wheel.
Yet that which boweth before the Lord, being willing to be smitten and abased by him,
and to lie under his correction and judgment his season, even until he say it is enough,
the Lord will without doubt restore into his favor,
if not also into the honor of his service again.

[.discourse-part]
Objection.
But some tender heart may say (which feeleth many weaknesses, much unbelief,
and the danger of falling daily), If this be true, oh, what will become of me!
If such as these be liable to fall, and to fall so dangerously, how shall I stand!
I was wounded enough before with the sense of my own condition;
but this affrighteth me much more.

[.discourse-part]
Answer.
O tender heart! the enemy may make use of this to trouble and afflict thee;
but it was not so intended by the Lord, who is very full of unutterable bowels,
and who hath a day of bowels for thy state: yea, his day, which hath already dawned,
is so dawning as to reach thee.
The Lord hath not yet done gathering his scattered sheep,
nor yet shown the utmost skill he hath, either to gather, or to preserve;
and the state of the weakest, under the preserving power of the Lord, is safe.
Great are the diseases of Israel; great is yet the loss of scattered souls,
which as yet know not the call of the Shepherd;
and if at any time they do feel a touch thereof, are easily reasoned again out of it,
and driven back by the thoughts of their own hearts.
Oh! great, great also is the skill of the Shepherd, and his hand very tender,
which the Lord is putting forth for the help of these; blessed be his name.
And as the condition of these needs and requires
that from the nature and soul of the Lord,
which the conditions of others do not require;
so the nature of the Lord hath mercy and love in it to answer their states,
and will give it out in his day and season.
Oh! let none be offended thereat.
Let no eye throughout all Israel be evil, because the Lord is exceeding good.
If he please to kill the fatted calf, and set it before his prodigal son,
let none that have walked faithfully with him in any dispensation be offended thereat:
but rather let all (in whom is life) stand ready
to shout at the issuings forth of love and mercy,
in the varieties of the dispensations thereof,
according to the need and capacity of every sort of vessels,
prepared by the Lord to receive it.
Therefore, _O thou afflicted! tossed with tempests, and not comforted;_
thou shalt know and feel this from the Lord,
that he knoweth how to bring home his consolations to thy soul,
and to cast thee into the mould of his life,
and bring thee forth in the power of his righteousness;
and that he needeth not to find any worthiness or righteousness in thee;
for he can create and make room for it in thy heart; yea, he can begin, carry on,
and perfect his work in thee, for his own name`'s sake.
And to thee, O broken soul!
I cannot so much say, do this, or believe this; but rather, the Lord will work in thee;
yea, the Lord will quicken faith in thee,
and raise up his own nature from the seed of his own life,
which he himself hath sown in thy inward parts, and will not fail to preserve.

Besides,
this broken state of thine (wherein the vileness and weakness of self is daily felt,
with the exceeding great need of the Lord`'s preserving power and mercy) is a safe state;
towards which, that which (alone) preserveth,
is continually issuing forth in the bowels of his tenderness.
And though thou dost not see the love of the Lord,
and his tender care over thee (and so wantest the comfort of thine own condition);
yet it is never a whit the less in the heart and Spirit of the Lord towards thee;
and in divers respects I may say,
it is better for thee at present to want the sight of it.
I am satisfied in my heart concerning the nature and ways of the Lord,
and I know there is that mercy in him which my soul crieth for;
and that it is not only treasured up,
but about to be issued forth towards those for whose sakes the cry is unto him for it.
The Lord will arise, and have mercy upon Zion,
even upon the mourners and distressed ones in Zion;
he will say to them who are of a fearful heart,
and mourn bitterly because of their unbelief (finding
themselves as unable to believe now for righteousness,
as ever the Jews were to work for it); be strong; stand still; wait on me your God;
behold, my righteousness is ready to be revealed,
and I am bringing that faith with me which ye want,
to give your souls the entrance into my promises, and into my divine nature promised.
Ye are my lambs, and my bosom is for you, and thither will I gather you; yea,
ye have already conceived, and are with young, though ye know it not;
and I will lead you on gently in a way that ye cannot, nor never shall, know,
as ye would know it; but shall not want or miss of that knowledge thereof,
that I see good for you.
I will beget a deeper life in you,
and bring it forth after a deeper way of dispensation
than ye have yet been acquainted with,
or than your understandings can comprehend;
but in the death which I am bringing upon you,
and in the travailing pangs which ye shall feel in your hearts,
shall it spring up in you and be brought forth.
O dear lambs! mind the quickenings of life,
and the savor and sense which the Lord begets in the heart,
and let the outward knowledge (even of what ye have had experience) go,
but as the Lord quickens it;
and mind not the noises of thoughts and reasonings about things,
which the soul`'s enemy will be striving to fill you with, and batter you by;
but sink down from these, and wait to feel that which lies beneath them;
in the free nature, life, virtue, power,
and motions whereof alone is your soul`'s salvation;
and if ye cannot receive the sense of this direction at present,
wait on the Lord either for it,
or for what other manifestation or tender help he shall please to give forth unto you.

[.old-style]
=== Some Questions and Answers / Concerning Spiritual Unity

[.discourse-part]
_Question 1._ What is spiritual unity?

[.discourse-part]
Answer.
The meeting of the same spiritual nature in divers,
in one and the same spiritual centre or streams of life.
When the spirits or souls of creatures are begotten by one power into one life,
and meet in heart there; so far as they thus meet, there is true unity among them.

[.discourse-part]
_Question 2._ Wherein doth this unity consist?

[.discourse-part]
Answer.
In the life, in the nature, in the Spirit wherein they are all begotten,
and of which they are formed, and where their meeting is.
It consists not in any outward or inward thing of an inferior nature;
but only keeps within the limits and bounds of the same nature.
The doing the same thing, the thinking the same thing, the speaking the same thing,
this doth not unite here in this state, in this nature; but only the doing, or thinking,
or speaking of it in the same life.
Yea, though the doings, or thoughts, or words be divers;
yet if they proceed from the same principle and nature,
there is a true unity felt therein, where the life alone is judge.

[.discourse-part]
_Question 3._ How is the unity preserved?

[.discourse-part]
Answer.
Only by abiding in the life; only by keeping to the power, and in the principle,
from whence the unity sprang, and in which it stands.
Here is a knitting of natures, and a fellowship in the same spiritual centre.
Here the divers and different motions of several members in the body (thus
coming from the life and Spirit of the body) are known to,
and owned by, the same life, where it is fresh and sensible.
It is not keeping up an outward knowledge (or belief concerning things) that unites,
nor keeping up an outward conformity in actions, etc.,
for these may be held and done by another part in man, and in another nature;
but it is by keeping and acting in that which did at first unite.
In this there is neither matter nor room for division;
and he that is within these limits, cannot but be found in the oneness.

[.discourse-part]
_Question 4._ How is the unity interrupted?

[.discourse-part]
Answer.
By the interposition of any thing of a different nature or spirit from the life.
When any thing of the earthly or sensual part comes between the soul and the life,
this interrupts the soul`'s unity with the life itself;
and it also interrupts its unity which the life in others,
and the unity of the life in others with it.
Any thing of the man`'s spirit, of the man`'s wisdom, of the man`'s will, not bowed down,
and brought into subjection,
and so not coming forth in and under the authority and guidance of life,
in this is somewhat of the nature of division: yea, the very knowledge of truth,
and holding of it forth by the man`'s wisdom, and in his will,
out of the movings and power of the life, brings a damp upon the life,
and interrupts the unity; for the life in others cannot unite with this in spirit,
though it may own the words to be true.

[.discourse-part]
_Question 5._ How may unity be recovered, if at any time decaying?

[.discourse-part]
Answer.
In the Lord alone is the recovery of Israel, from any degree of loss in any kind,
at any time; who alone can teach to retire into, and to be found in,
that wherein the unity is and stands, and into which division cannot enter.
This is the way of restoring unity to Israel, upon the sense of any want thereof;
even every one, through the Lord`'s help,
retiring (in his own particular) and furthering the
retirings of others to the principle of life,
that every one there may feel the washing from what hath in any measure corrupted,
and the new-begetting into the power of life.
From this the true and lasting unity will spring amain,
to the gladding of all hearts that know the sweetness of it,
and who cannot but naturally and most earnestly desire it.
Oh! mark therefore;
the way is not by striving to beget into one and the same apprehension concerning things,
nor by endeavoring to bring into one and the same practices;
but by alluring and drawing into that wherein the unity consists,
and which brings it forth in the vessels,
which are seasoned therewith and ordered thereby.
And from this let all wait for the daily new and living knowledge,
and for the ordering of their conversations and practices in that light,
(and drawings thereof) and in that simplicity and integrity of heart which
the Spirit of life at present holdeth forth and worketh in them;
and the life will be felt, and the name of the Lord praised in all the tents of Jacob,
and through all the inhabitants of his Israel; and there will be but _one heart,
and one soul, and one spirit, and one mind, and one way and power of life;_
and what is already wrought in every heart, the Lord will be acknowledged in,
and his name praised:
and the Lord`'s season contentedly waited for his filling up of what is wanting anywhere.
So the living God (the God of Israel,
the God of everlasting tender bowels and compassions to
Israel) fill the vessels of his heritage with his life,
and cause the peace and love of his holy nature and Spirit to descend upon their dwellings,
and to spring up powerfully in them towards his living truth, and towards one another.

And let all strive to excel in tenderness, and in long-suffering,
and to be kept out of hard and evil thoughts one of another,
and from harsh interpretations concerning any thing relating to one another.
Oh! this is unworthy to be found in an Israelite towards an Egyptian;
but exceeding shameful and inexcusable to be found in one brother towards another.
How many weaknesses doth the Lord pass by in us!
How ready is he to interpret everything well concerning his disciples,
that may bear a good interpretation! "`The spirit`" saith he "`is willing,
but the flesh is weak.`" When they had been all scattered from him upon his death,
he did not afterwards upbraid them; but sweetly gathered them again.
O dear friends! have we received the same life of sweetness?
Let us bring forth the same sweet fruits, being ready to excuse,
and to receive what may tend towards the excuse of another in any doubtful case;
and where there is any evil manifest, wait, oh wait, to overcome it with good!
Oh! let us not spend the strength of our spirits
in crying out of one another because of evil;
but watch and wait where the mercy and the healing virtue will please to arise.
O Lord, my God, when thou hast shown the wants of Israel in any kind sufficiently,
whether in the particular, or in the general,
bring forth the supply thereof from thy fulness, so ordering it in thine eternal wisdom,
that all may be ashamed and abased before thee, and thy name praised in and over all.

[.signed-section-signature]
Isaac Penington
