== Concerning God`'s Seeking Out His Israel

[.heading-continuation-blurb]
Likewise concerning the principle of life, whereby he seeketh them;
And the way of their closing with his spirit therein.

[.heading-continuation-blurb]
As also concerning the two covenants;
under one whereof he pleaseth to exercise and prepare them for the life and inheritance,
which he hath treasured up for them in the other.

[.heading-continuation-blurb]
With a postscript, relating some things necessary for lost man to be acquainted with,
in his travels from his lost estate.

[.section-author]
By _Isaac Penington._

[.section-date]
1663

[.section-summary-preface]
To such in Godmanchester, and thereabouts, who bear the reproachful name of Quakers;
whose religion began in the power, and who still abide and walk on in the power,
waiting to be perfected in the full manifestation and appearance thereof.

[.salutation]
Dear Friends in God`'s pure eternal Truth,

It was my lot once to be among you in a meeting, together with a certain friend,
where I had a word unto you from the Lord, while the said friend was declaring.
But being exceedingly bowed down in spirit,
and afraid to interrupt the service in him (whom I looked
upon as far more abundantly grown up in the life,
and fitter to minister from the life), I waited till the life in him should stop.
But then those words, which had often sprung in me before, sprung not again;
and I durst not then speak them from a bare remembrance of them,
not finding the Spirit of the Lord then giving them me to speak.
So I went away with a burden on my own soul,
and also with a sense of some loss to you of some
part of the good which the Lord intended for you.
Since that time, I have often remembered the thing with grief; crying to the Lord,
that that which hath so often stopped the life in me,
and my service in the life might in his good time be removed;
and that the day might come, wherein the man might never more be or appear,
as of himself, or as a determiner concerning the things which flow from the life,
but that the life might have its free course and current through me,
in its own pure streamings, to the delighting of my own heart in the Lord,
and the refreshing of others.
And indeed this day I exceedingly long for,
that nothing of self might be left to be brought forth,
and that all which is of the life might spring up and flourish,
both in me and everywhere.

Now one morning, as my heart was breathing towards the Lord,
not having a thought either of you or this thing,
the very same words which were given me in that meeting, sprang up again livingly in me,
with a pointing to write them down, with what the Lord should please to give in further,
and send them to you, together with a paper, which was a little before written,
concerning the two covenants.
And when I had almost finished what was then given me to write,
I was further directed to annex to the first paper another concerning the principle.

How the Lord shall please to improve them to your advantage,
or to the advantage of any others, I leave to him;
it being the earnest desire of my heart, that his work may prosper in his hand,
and that the light and power which issueth forth from him for the salvation of souls,
may be effectual thereunto; and that nothing of love, of mercy, of goodness, of life,
of salvation, of his searching and healing virtue may be held back by him,
which the state or condition of any of his sheep
or lambs (whether lost or gathered) calleth for.
That his Israel may become the glory of the earth,
and all nations may be refreshed with beholding the beauty, and tasting the sweetness,
of life and righteousness, which shall assuredly flow forth from his sanctuary.
And surely the time is not far off (whatever the eye of sense may judge,
and however things may appear to man`'s understanding) wherein Israel shall be
no more compelled to worship in the temples of men`'s building and dedicating;
but shall in the beauty of holiness.
For the day is come (yea,
the blessed day is come) wherein the Lord God of life will build up his Zion,
and appear there in his glory; Amen, hallelujah.

[.centered]
=== Concerning God`'s Seeking Out His Israel

THIS is the word which was given to me; The Shepherd of Israel is seeking out his sheep,
even the lost sheep of the house of Israel.
Concerning which, these three Questions sprang up in me one after another,
as I was about to write, and writing.

Question.
1+++.+++ Who are his sheep?

Answer.
His sheep are the sons of men;
the lost sheep of the house of Israel are those among the sons of men,
who have felt touches of his life, begettings into his nature,
and were in some measure gathered into some appearance
and dispensation of his life by his Holy Spirit;
wherein they felt warmth from God in their spirits,
and a delight and joy in what they felt,
and a longing after a further manifestation of him.
These were his sheep, in a gathered estate in some degree,
by those dispensations of life in the darkness,
which had some strength in them to gather from under the darkness,
and did gather into that measure of light and life that was then dispensed.
But the sheep cleaving to the dispensations (which were very weak and imperfect,
and had little of Spirit,
but very much of flesh in them) and not following the lamb
out of them into the further dispensations of life,
into which he stood ready to lead; the Lord brake them in pieces, departed from them,
and left the life to be made a prey of, and brought under the captivity of death;
so that the sheep were scattered upon the mountains,
and every beast of prey was ready to fasten his teeth on them and devour them.
Oh! the precious buddings forth of the virtue and power of God,
that were to be found in the several sorts of professors,
while they sought the Lord only,
and the knowledge of one another in the breathing spirit,
and minded not the outward form, but the feeling of life in their duties and ordinances!

But when they began to mind the form, and cry up several forms;
the Lord also began to loathe the forms, and did not give forth that among them,
which formerly they met with, but took away the kernel, and left them the shell: and oh,
how dry and barren have they become since!
Where is the feeling of life?
Where is the love to one another in the living sense?
Where is the zeal after, and earnest seeking of, the power of religion?
Where is the nature of the sheep to be found in them?
And where is the presence of the Shepherd among them?
Are they not lost sheep indeed, lost to God, lost to themselves?
Have they not lost the holy, pure, sweet, meek, heavenly, tender,
gentle nature of the sheep?
Have they not lost the pasture and the fold, whereon they were wont to feed,
and wherein they were wont to lie down safe?
Have they not lost the preserver of their souls from the devouring spirit?
Nay, have they not lost the very seed of life, which the good husbandman did sow in them?
And do not evil seeds shoot up in the stead thereof, to the poisoning of their hearts,
and blemishing of their conversations?
And are not some of them insensible of their loss, and lie still drowned in their forms,
thinking to confine the appearance of the free life and unlimited Spirit there?
Others of them sick, and deeply wounded and languishing,
not knowing where to meet with the good Shepherd, nor how to make shift without him?
Oh, the cries of the desolate and mourning souls, which love God at their hearts,
and have the relics of his nature left in them in a seed still;
which he once begot and brought forth in some freshness!
Oh, their deep anguish! their miserable lost condition
for want of meeting with the Physician! their pantings,
their tears, their distresses, their roarings out, their overwhelmings,
their several kinds of captivities,
and the cruelties exercised upon their spirits by the captiver, even break my heart,
that I am almost overwhelmed in the sense of their misery!
But my heart is somewhat comforted with the freshness of this testimony,
which hath often risen up in the immediate life of God in my heart;
and I have heard his voice speaking it, even that he will seek them out.
And I know he hath the skill to find them, in their several mourning holes,
wherein they lie hid; and the pits whereinto they are tumbled;
and the briars and thorns of the wilderness, wherewith they are torn,
and wherein they are twisted and entangled, and held pining to death; and in the prisons,
and chains, and fetters of their spirits,
wherein they are closed up and bound down by the enemy of their souls.

Question 2. How will he seek them, and how will he find them out?

Answer. By the light of his Spirit shining in their hearts,
by which he will touch and quicken the sheep`'s life, and open the sheep`'s ear,
and persuade the heart to know and believe that it
is he that visiteth in his tender mercy,
and that he will have mercy on, and show compassion to,
that which hath long been cast off and forsaken; and he will be their God,
and they shall be his people, even the house of Israel that had departed from him;
and that he had not forgotten them, but waited for the hour of mercy,
and for the season of the bringing forth of that life and power,
whose searching and healing virtue will reach to the utmost extremity of their conditions.

Question 3. What will he do with them, when he hath sought after and found them out?

Answer. He will gather them into the fold of life, and lead them into the pastures of life,
and feed them with the food of life, as their conditions are able to bear;
he will be fitting them by the exercises of his Spirit,
for their passages from death to life; and as they are capable,
so he will be still translating them from the one into the other.
He will bring them from their several false-built states in the
land of Egypt (or Babylon) into a true wilderness state;
and there, as he wears out the old nature in them, so will he speak comfortably to them,
and build up the new; and nourish the true Israelitish babe there with manna from heaven;
and after he is grown up to a man`'s estate, and hath received the inward circumcision,
lead him into the pleasant land, where there are rich pastures,
and the sweet still waters, and the precious milk and honey of the living,
with which the land flows naturally,
and which yields pure nourishment to all the living offspring.
Oh! my heart is not able to contain the sense of all that God will do for Israel,
or of what he will be to them, or of what they shall be to him,
when he hath finished his work upon them,
and brought them forth (through the strength of his covenant) in the nature,
and into the possession, of his life.

But sure I am he hath begun his work;
the light of the day (even of the everlasting day) hath sprung and visited many;
the principle of life hath been revealed in the hearts of many;
and many are gathering into it, and find the man sinking and dying;
and the life rising and living in them day by day.
And though the passage be bitter, and the passover still eaten with bitter herbs,
and the devourer often let loose and suffered to nip and destroy;
yet out of the eater at last comes forth meat,
and out of the strong one in the issue comes forth sweetness.
Yea, though there be no faith found to close in with the light,
nor any strength left to obey or follow,
because of the deep foregoing breakings (wherein
both nature and spirit were all dashed in pieces,
and swallowed up in confusion);
yet the breath of life and the power of the light (in process of exercises,
and after much deep misery, and impossibilities,
to the sight and judgment of sense) at length raiseth
up a little seed in the longing soul;
which receiveth and bringeth forth, after a hidden way, that which it could not.
And here life is indeed of grace, and wholly of the seed, in this state.
Only wait to learn and know in spirit (and then take heed
of despising) the weak beginnings and dawnings of light,
in the secret stirrings and movings of the principle of life;
and wait also for a watch to be set up in thee against that fleshly wisdom and understanding,
which will be apt to be judging about the work of God in thy heart;
for if it prevail so far, it will then also be begetting in thee despisings of,
and turnings from, the low beginnings thereof,
and so divert thy feet from the path of life.
For the prevention whereof, and for the furtherance of thy soul, in its closing with,
and travelling on, in the light and guidance of the Spirit of the Lord,
this following paper is added.

[.old-style]
=== Concerning the Seed or Inward Principle / Whereby Life is Begotten and Maintained in the Heart

THE Lord God,
who is full of everlasting bowels of compassion towards mankind in general,
but more especially towards those, in whom he hath begotten a sense of the want of him,
with breathings and desires after him;
hath chosen a seed or inward principle of life to appear in,
towards the breaking the bonds of their captivity,
and the bringing them from under the power and misery of death.

This, many who have been overwhelmed with misery,
and whose spirits have melted and failed with the want of the sense of their God,
and have felt that life, which was formerly built up in them, broken down and laid waste;
and their communion with God swallowed up in the ruins thereof;
and their souls ready utterly to perish and be devoured by the enemy every moment;
after the cutting off of their hopes,
and the shutting up of their eyes towards all ways of relief; I say, after all this,
and much more than can be expressed, in the tender mercy of the Lord,
have they felt this principle revealed in their hearts, and their hearts by degrees,
through the skill and same mercy of the Lord,
which revealed the principle (and not from any worthiness,
or faith and obedience of theirs; for that was as freely given and preserved,
as the principle itself was revealed), gathered into the principle,
where the life reigns,
and where the strength and dominion of death is broken in all those,
who by the allurings and guidings of the Spirit of the Lord are led thither.

Now the main thing necessary towards the redemption of the soul is,
after the revealing of this principle, and some sense and feeling of it,
and the turning of the mind towards it,
to wait to be made more and more acquainted with it, that in the stirrings, movings,
and leadings thereof, there be a ready giving up to be gathered into it,
and to be guided by it.

For though this principle be all life, yet it is at first but as a seed,
and the appearance of the Lord in it is but as in a seed; very little, low, weak,
hard to be discerned, easy to be overlooked and despised,
and some greater and more undeniable appearance expected.
Yet that is not the way, but the soul must become subject unto, and bowed under,
this little appearance; and so as the seed gets advantage,
and grows bigger and larger in thy heart,
the appearance of the Lord will be greater and fuller there.
But to look for the greater appearance,
before the seed be owned and received in its lesser appearance (and the
vessel thereby fitted for the greater appearance) is not the way of God,
but the deceit of the enemy, whereby he would destroy the soul,
and cut it off from the Lord forever; which he certainly will do,
if he can keep the seed from growing there,
and the soul from joining with and growing into it.

Therefore watch to feel the savor of life in thy heart day by day,
and therein to feel leadings and drawings from the life, suitable to thy state;
for in this savor, and in these drawings, rises the true light,
which leads into the way of life.
And then watch against the reasonings and disputations
which the enemy will raise in thy mind,
who will strive to make thee a judge over these drawings; whereas the light,
which ariseth in the savor and in the drawings,
is thy King (though in this low appearance), and not to be judged by the mind, thoughts,
and reasonings, but to judge them all down, and be bowed unto and obeyed by thee.
And consider, in the weight of thy spirit, art thou (in thy darkness,
and with thy earthly mind) fit to be a judge concerning the light which ariseth in thee?
Or rather, is not the light, in its lowest and weakest appearance,
appointed and fitted by the Lord to judge thee,
and make thee bow down in fear and trembling before it?
And thy crown (thou in thy highest exaltation) is
to be cast at the lowest footstep thereof;
and then it will in some measure, thou lying at the foot thereof,
and bowing in spirit before it, enter into thee, and enlighten and quicken thee.
But in thy being wise about it, or taking upon thee to judge concerning it,
it will stand at a distance from thee, and leave thee in thy darkness and captivity.

Therefore consider where thou art,
and breathe unto the Lord to reveal that unto thee which is proper for thee at present,
and to bow thy spirit under his present will and manifestation to thee.

And be content to be little and low, and to receive little and low instructions from God,
and to walk in the path of brokenness and humility before the Lord;
for this is his way of fitting for, and advancing into,
the high and glorious power of his life.
And this my soul is assured of, that none shall enter into, or abide in, his kingdom,
but as they become little, poor, and naked,
and as they are led by the little child of God`'s begetting;
who not at all answers the wisdom of man and his expectations, but still confounds them,
and leads on in such a path, as, if the eye of man`'s wisdom be open,
it will still be crying out it can never bring to life.
Yet that which disputeth not, but believeth, at seasons feels a progress,
and that the growth of life had advantage in the heart by those very things,
which at present seemed to give death the advantage.

Therefore watch against thy understanding, and all the workings thereof,
as ever thou desirest life; for it will still betray thee,
and either keep thee from the way, or turn thee out of the way,
whenever thou hearkenest to it.
And mark this: That which God sows and brings up in thee is a sensible plant,
not a knowing mind; and thy right judgment is only in the sensibleness of that plant,
and not in the understanding or comprehension of thy mind; yea,
that sensible plant (which thy wisdom will be very apt to despise and
perk over) must batter down and bring to nothing thy understanding,
and grow up in the stead of it, if ever thy soul be made a habitation for the life.
Therefore sink into the feeling, and dwell in the feeling,
and wait for the savor of the principle of life,
and the touches and drawings of the savor, and walk along in it towards the land of life,
parting with all, and leaving behind thee, whatever the savor of life disrelisheth;
and entering into, and taking up, whatever the savor of life relisheth,
that thou mayest be prepared for the Lord,
and for the glorious appearance of his Spirit in thee.

And as thou art led into this, and becomest subject to this; so thou wilt taste the Lord,
and feel the sweetness of his ointment, and the peace of his nature,
and the joy of the beginnings of his kingdom in thy heart,
and the blotting out of thy iniquities for his own name`'s sake.
For though the enemy may lay a load upon thee,
and fill thee as much as he can with his filth, and lay it close to thy charge,
insomuch as thou art not able to acquit thyself at all,
but art as ready to charge thyself therewith, as the enemy is to charge thee;
yet the Lord considereth the seed he hath sown in thee,
and the desire which he hath wrought in thy heart to be joined thereunto;
and he knoweth whence the stirring of this mind is,
and how weak thou art in this hour of thy darkness and captivity;
and the intent of his heart is to deliver thee from all this,
and not to condemn thee for it.

But oh! take heed of limiting the Lord to give forth so clear a light,
as the natural understanding will be judging necessary;
but be content with the light which ariseth in the savor,
and shineth inwardly to thy spirit in the drawing;
and be subject and bowed under the light of the drawing,
though ever so much against the light of the creaturely understanding,
and the reasonings thereof.

Clearness of light is a state which is to be grown up into;
but before thou cometh to this, thy understanding must be darkened, confounded,
and brought to nothing; and thou canst not have such a clearness there,
while it is confounding.
There is indeed a true clearness in the principle of life
(proportionable to its state and growth) even then;
but the reasonings of thy dark mind will be continually
overclouding and overbearing it (as if it were darkness,
and not the light), and will prevail, unless thou be kept in the savor,
and suffer not thy understanding to judge, but keep it under the judgment of the savor.
Mark, therefore, heedfully this which follows:--

The first work of the Lord,
is to confound the knowledge and understanding of the creature;
especially in those who have been deep in wisdom and experience of things;
for if they were not closely pursued with darkness and confusion,
they would presently be gathering a stock into the old storehouse again,
and so grow wise after the flesh, and never learn the life of the Spirit.
Now in this work of confounding,
how can the leadings of God`'s Spirit be manifest and clear after the flesh,
and to the fleshly understanding?
Yea, if they were manifest after this manner,
how were it possible to withhold the fleshly part from drinking them in?
and so the man would live again, but the seed not live,
which gains its life (and being and form and perfection) in the man,
by the death of the man; even by the man`'s being hunted, and battered,
and broken out of his wisdom, and knowledge, and reasoning, and comprehension;
and becoming as a fool or child, being able to know nothing, nor retain nothing,
nor perform nothing, nor keep his standing; but still as he is led, and taught,
and created, and preserved in the power, and by the presence of the life.

[.centered]
=== Concerning the Two Covenants

WHAT is the covenant of the law?
Doth it not contain and hold forth eternal life to man, upon his faith in,
and obedience to the Spirit of God?

What is the covenant of the gospel?
Doth it not contain the promise to the seed, and life to man through the seed,
and forgiveness of his sins for the seed`'s sake, and the uniting of his heart to,
and preserving it in, the seed, through the grace; as also repentance, faith,
and obedience from the grace?

Mark then the difference between the two covenants.
The covenant of the law is all of works, and according to works; yea,
even the faith that is there found (which is begotten and brought
forth in man by virtue of that covenant) is of the man,
or of the working principle.
The covenant of the gospel is all of grace;
and the very works that are found are from the grace,
and the seed bestowed and conveyed by promise.

Now mark: The seed (or standing principle of life) in both covenants is the same.
It is the same Christ by which Adam stood before the fall,
and which was the promised seed after the fall.
The light of both the covenants is the same, even the eternal light of the Spirit.
The life and power is the same, even the life and power of the Spirit.
The end or mark, at which man aims, and towards which he travels, in both is the same;
even the land of rest and peace in the Spirit of the Father,
who begets a living soul under both covenants.
But the terms of the covenants, and the manner of dispensing them, are different;
and the wombs, whereof the children of each covenant are born, are different likewise;
the one being the working nature (which also came from God,
and hath its blessing from him in its obedience and subjection to him),
the other the womb of grace, which brings forth the child of grace in man, according to,
and by virtue of, the promise;
and doth not find a will in the day of man`'s choice and liberty,
but createth a will in the day of God`'s powerful appearance in it.

Yet this seed of promise,
or this new man begotten by the seed of life according to the promise,
must walk through the law, and travel through all the dark paths of that covenant,
before it come to inherit the promised land;
where the rigor of the law and the weakness of the flesh will be thoroughly felt,
and many transgressions and many stripes; yea,
many captivities and cuttings off from the life may be felt also; yea,
the seed of the first covenant may live and flourish, and enjoy and boast much of God,
while this seed is miserable.
But when this womb is visited with the strength of grace, and free power of life,
and bringeth forth her children therein,
and no more is called for from the working part of man,
but all brought forth in the free, full, and fresh power of life;
then shall the seed of Israel, after the promise, become an everlasting habitation for,
and a perfect joy in, the life.

Therefore distinguish in spirit between the law and grace, and the covenants of each,
and the dispensations of each, and how they are mixed and intermingled,
both towards man and towards the seed,
in the several dispensations in which each is brought forth.
For there hath been no perfect covenant brought forth,
either of works or of grace (in a way of public administration), since the fall of Adam.
Had there been a perfect covenant of works,
there had been no capacity of salvation thereby to fallen man.
Had there been a perfect covenant of grace,
there had been no possibility or capacity of destruction: for grace,
in its perfect going forth, cannot but overcome and save the man.
But God ordereth both these covenants, both towards the man and towards the seed,
according to the state of the man and the state of the seed, and according to what,
in his eternal wisdom, he judgeth meet to work upon them thereby.

Man being fallen,
and having lost his strength of faith and obedience
in and to the requirings of God`'s Spirit,
the visitation of him is now by grace, and not merely to call forth what is left in him,
but to help him with light and power,
and by the influences of the grace and of the power to quicken him towards God.
Yet man, in the receiving of this, is apt to overlook the grace,
and attribute too much to his own strength, thinking himself somewhat,
because of the grace and power which hath visited him,
and new refreshed the strength and nature of his principle in him again.
Hereby he is apt to fix his standing on his obedience
to the Spirit or appearance of the grace,
and so in effect builds his life and hopes on his own principle again,
or on a new-received power, as held or kept to by him (which he may fall from now,
as well as he did at first),
and not on the free begetting and free preserving of a principle of life in him.

This visitation of grace is to all mankind, there being none upon earth,
whom the Lord doth not thus seek and visit with the light of his eternal life,
thus administered through the grace; which so far as they fall in with,
the Lord doth receive them and beget life in them, ingrafting them into the living vine,
and preserving them according to their abiding in it,
and according to their obedience to him in the springings
up of the sap of the vine in them.

But besides this common administration of the grace to all mankind,
God formerly picked out a people after the flesh of Abraham,
and afterwards a people after the spirit of Abraham, towards whom,
in a more peculiar way, his grace did administer itself, and whom he dealt with,
not as with other nations,
but chose to love and work up into life and communion with himself,
by a more especial administration and visitation of his love and grace.
The one of these were that people of the Jews, the other the believing Christians.

With the Jews he remembered the covenant with Abraham.
By virtue of that he loved and chose them to be his people after the flesh,
or his outward people; by virtue of that he brought them out of Egypt,
led them through the wilderness, brought them into Canaan,
giving them an inheritance therein,
and delivering them from their enemies time after time.

Yet he also made another covenant with them (even
that of the law) which was suitable to their state,
and which their nature desired, and chose to walk with God in, but hardly ever kept it,
and so brought the curse and misery due thereby upon their heads,
and at last were utterly cut off,
so far and so long as the Lord pleaseth to let the
curse of that covenant have power over them,
until he shall please again to remember to them his covenant with Abraham, Isaac,
and Jacob, and breathe life through it into their dry bones.

Now though God did make this covenant with them, because they were fleshly,
and their present state required it,
yet he did not disannul or make void the other to them, all the while their day lasted;
but remembered lovingkindness and mercy towards them in it,
often delivering and redeeming them for his own name`'s sake,
pointing them also to the word in the heart, and the gracious administration thereof.
But they were blinded and held captive in the earthly nature and principle,
and in the law thereof, and held their marriage and union with God thereby.
And see,
though this administration to the Jews (wherein God did strive with them by his Spirit,
and sometimes stir life, and beget a true sensibleness in many of them,
calling to them for the circumcision of the heart,
and pointing them to the principle of life in the heart,
whereby it might be circumcised) though this advanced them far above the Heathen;
yet they, through the flesh and the letter,
at last fell below the very state of the Heathen, proving greater enemies to,
and persecutors of, the life than they;
and so the Lord brake them off from the Olive-tree into which they were ingrafted,
and cut them off from the covenant which he had made with Abraham, Isaac, and Jacob;
whereas, thitherto (though he had often been provoked by, and sorely offended with,
them), yet he had still loved them for their fathers`' sake.
After them, and in their stead, he chose the believing Gentiles,
ingrafted them into the stock from whence these were broken,
letting them into a sweeter and fuller, and more spiritual and abiding state,
and influences of the covenant.
For here the life was manifested, and the light did shine in great beauty and clearness.
And they were gathered into the true fold of the Shepherd (besides the outward state,
which was also built up by the Lord, and preserved for a season among them);
and they saw their standing to be by and in the grace, and were established in the grace,
and could feel the good pleasure calling, the good pleasure working,
the good pleasure being and doing all in them; and could cry grace, grace,
to this building; and say, not for any works that they had wrought,
or for their faith in, or obedience to, the light of life, which was made manifest;
but of his own mercy he saved them,
who wrought in them both the will and the deed of his own good pleasure,
and preserved them by his power through faith (which
was of his gift and begetting) unto salvation.

Yet for all this,
there was somewhat of the law or light eternal to be administered unto them,
which was suitable to the natural part or first principle
through which they were to travel,
even until the man, or first nature, was wholly wasted;
whereby some of them were in danger of falling away wholly,
others of coming under the chastisement and judgment, with which the Lord pursued them,
that they might not be utterly condemned with the world.
Mark, therefore, this brief sum of the matter:--

1+++.+++ Man fell under the first covenant: his restitution is never to be thereby,
but by the second;
through which God works up into a state of life and
glory in the administration of his grace.

2+++.+++ But in this working up of the vessel,
he sees necessary to make use of the other covenant,
according to the capacity that is left in man to answer it;
and so as that capacity wears out,
the covenant of the law wasteth and passeth away by degrees,
and the covenant of grace succeeds and fills up the room thereof.

3+++.+++ There is a great danger of falling from the life for some,
as also of chastisements and judgments to others, while this capacity remains;
even while the earthly nature, spirit, and principle is not worn out, by the entrance,
death, and resurrection of the principle of life in the heart.

4+++.+++ When the first principle is wholly dead, and the heart perfectly formed in the life,
and all perfectly raised and renewed in the life; then there is no danger of falling,
or fear of chastisement; but perfect life, and peace,
and joy with God in his Spirit of power and glory forevermore.

5+++.+++ Though God begin with man in a covenant of grace,
and bring in a covenant of the law to man (suitable to his
present state) only in subserviency to the covenant of grace;
and would not have man stick there, but cling to him in the grace,
and seek remission through the grace for his own name`'s sake; yet man,
through the prevalency of the first principle in
him (and his looking on God through that),
is apt to fix on this covenant,
and draw comfort or discouragement to himself from his own obedience or failings,
and not live on the freeness of God`'s love,
and the faithfulness of his heart to the soul in all conditions, for his Christ`'s sake.

This hath been the great error of Israel (even of Israel after the flesh,
and of Israel after the spirit also), that while God lays hold on them by his love,
promise, mercy, and grace; yet they lay hold on him by another covenant;
even their obedience to the laws he gives forth; not knowing,
that the obedience to the first covenant must be a fruit of the second;
and that they are not beloved or accepted for that, but that that flows into them,
and is brought forth in them through the love,
and through the free and powerful workings thereof in them.
I say, this (to wit,
their obedience) is not the ground of their acceptance or being loved,
so far as they are in this covenant; though as far as the other hath yet an influence,
it hath some force in this respect.
But this the eye is to pass through, and to be fixed on the other covenant,
still waiting for the revealing and manifesting the riches of the mercy thereof,
and to feel the washing and cleansing thereof from all the guilt,
which under the remainders of the first covenant will be daily contracting,
while any thing of the earthly principle and offending part is left standing.

There hath been in this day a very glorious administration
of life to the sons of men (after the long foregoing night),
wherein both these covenants have been again administered in Spirit,
suitable to the state of the persons whereto they have been administered.
And because of the necessity of faith and obedience in the
new covenant (both to the seed and to the man),
the man is so apt to fix his eye and build his hopes upon them,
and not upon the free love of him that works them in him,
that he is in danger of falling from and dishonoring the free grace,
which is the hope of Israel, and of losing his state,
which is not sure (how far soever it be advanced in a present power and dominion),
further than it is built upon and fixed in the grace.
And therefore is this given forth, that the life in Israel may be sure and lasting,
and that they may grow up perfectly, out of the principle of nature,
into the principle of grace, and know the difference between their being united to,
and living in, God, either in the fear, faith, or love,
so far as they can receive or retain them; and God`'s living in them,
and creating continually the fear, faith, and love in them,
and bringing forth all the fruits thereof in and from himself.

For though the covenants are and have been still the same from the beginning,
yet the manifestations of them have been still greater and greater.
And a greater manifestation may yet be of the love and life of God, and the sweet,
free nature of his covenant, than hath hitherto been, or yet is;
which Israel is to wait for and feel the need of, before it be brought forth.
And though all those forementioned (to wit, of fear, faith,
and love) are precious states, which God works his Israel up to,
in and by the covenant of his grace, according to their several growths and capacities;
yea, and according to which the delight and pleasure of his soul is in them;
yet the absolute assurance is only in the latter,
even where the creature is so gathered into the life of God,
that its state depends not at all upon what itself is, or doth,
but only upon what God is and will be to his freely of himself,
and for his own name`'s sake.

This is written in love, for preservation; and not for discouragement or destruction;
but that that which standeth, may feel where to fix.
For in the highest state that man can be advanced to,
yet if any of the creaturely principle be left in him unsubdued,
and not yet buried with the seed into its death, there is so far a capacity of falling;
and his fall, in case the Lord do suffer his feet to slip, will be the greater,
by how much the higher and more exalted he was in the dominion and presence of the power,
and by how much the more it was unexpected by him.

And this my heart hath often said within me, and still saith to a weary soul,
which hath felt the touches of life, and desireth everlasting unity with it; yea,
to all that desire to walk with God,
and to abide in the power of his life in any dispensation;
Keep the eye of thy mind to the grace which visits thee;
not so much to the light which comes from the grace,
as to the grace from which the light comes;
and daily look for help and remission from it, as freely as thou hadst at first.
And in all losses and darknesses, and risings up of guilt and condemnation,
cast thyself at the foot of it, saying in thy heart,
If thou hadst not freely visited me at first, I had not set one step in the path of life;
and if thou dost not as freely visit me still,
and renew life in me daily of thine own accord, and from the same love and goodness,
I cannot but be liable to miscarry.
Oh that I might obey every beam of thy light,
and every moving of thy life! but I dare not undertake it.
Oh that thou wouldst undertake for me my righteousness, my obedience, my love to thee!
My faith in thee is like the morning dew, which soon passeth away,
and I cannot find or come at it again!
Oh, raise up life from an everlasting seed, and gather my heart into it,
and preserve me in it; not according to what I am or have done, or yet can be or do;
but for thine own name`'s sake, and in thy love to thy seed,
and to thy creature in and through thy seed by the promise!

Thus as any grow into the covenant of grace,
through the covenant of works (which is necessary to be dispensed in some measure,
till the man`'s nature and principle be wholly worn out by it),
they will find sure footing there, and building upon that,
from which the soul (that cleaveth to it in the virtue
and nature that floweth from it) can never be removed.
Yea, the peace and safety of Israel in their travels (fixing here) will be greater,
and their assurance greater,
and their falls and the prevailings of the enemy
not so dangerous (that being had recourse to,
which never fails of healing that soul which lies at the foot of it,
and in heart waits its season);
however they may be hurried and driven about with tempests,
through the violence of the enemy, and good pleasure of Him,
who seeth it fit for the present state of the soul, to have it thus exercised.

The intent of God, in the salvation of man, is to magnify the riches of his grace,
and the freeness of his love.
And this is effected,
as man is broken in his natural principle and power of believing and obeying;
and a seed of life freely raised up in him, and he freely gathered into it,
and preserved in it.
And where is the boaster here?
Or where is he, who, in this state,
can throw a stone at another because of his transgressions?
Nay, nay; he that is freely forgiven, and lives merely and forever by mercy alone,
he is formed and brought forth in the tenderness
of the bowels which begat and nourish him;
and he crieth mightily for the spreading of the same bowels over other sinners,
waiting for the season of their visitation and gathering into the same love,
and by the same powerful hand, if it may be.

O my God, bring up the power and sweetness of thy life in Israel,
and show mercy to all nations!
Purge the earth with thy fan,
scatter the corruption thereof from the hearts of the sons of men,
and make them the paradise of thy pleasure; that thou, O living God, mayst dwell in,
and shine forth from, thy temple; and it may no longer lie waste,
nor the abomination of desolation defile it, to the dishonor of thy name,
and to the ruin and misery of thy creation!

=== Postscript

SOME things are exceeding necessary for lost man to be acquainted with,
in his travels from his lost estate, into the life and peace of God: as,

1+++.+++ To know his lost estate and misery forever, unless the Lord pity and help him.

2+++.+++ To know the light, wherewith the Lord visits the souls that sit in darkness;
that he may wait for the shinings thereof,
and in them travel with the leading Spirit of life,
from the darkness and death of sin towards the land of the living.

3+++.+++ To breathe unto the Lord,
and wait to have his heart joined to the light and power of life daily,
and separated from the powers of death and darkness, under which he was, and still is,
a captive, but as the Lord appears for him, and delivers him.

4+++.+++ To put forth all the strength of his soul and mind, and all the members of his body,
in the service of the Lord.
For as he is, in any measure, set free by the Lord from the service of sin;
so is he to serve and obey the Lord in righteousness.

5+++.+++ To wait daily to receive the strength from the Lord, wherewith he serveth the Lord.
For though, by the redemption of the Lord, he feels the creaturely part, in some measure,
renewed and restored, and an ability received to serve righteousness,
which before he had not; yet this is not so given to him,
as that the Lord hath it not still in his hand,
who can stop or let it out at his pleasure.
And happy is that man,
who looketh not upon himself as somewhat because of what in any kind he hath received,
but feeleth his dependence upon the Lord.

6+++.+++ To feel the grace and mercy of the Lord, in whatever he receiveth from the Lord,
or whatever he doeth for the Lord.
It is all of the Lord; happy is the man that sees it.
It is the mercy of the Lord, that man is not consumed.
It is the mercy of the Lord,
that any man in any state (or degree of life and redemption) is preserved.
The mercy of the Lord endureth forever, therefore is Israel safe.
This will be the song of praise in the house of the Lord forever.

7+++.+++ To wait for the wasting of the man, and the raising up of the seed day by day;
that that to which the covenant of works is natural,
and which cannot but desire it and seek to live by it, may be worn out;
and that to which the covenant of grace is as natural (if not more),
and which alone lives by the promise, and through the faith,
and in the grace which freely flows from the eternal fountain, may be raised up,
and succeed in the place and stead thereof.

Here is safety indeed.
Here is everlasting righteousness so brought in,
as that it can never be removed out of the heart more.
Here everlasting life and the soul are one forever.
Here is no more going into captivity; which Israel, settled in Canaan,
and enjoying the sweetness and rest thereof, under the first covenant may.
Here are no tears, nor sighing, nor departing from the life,
nor grieving the Holy Spirit of the Lord, nor being grieved by it any more;
but what the heart desires of God, and what God desires of the heart, mutually received;
and the going forth, and the coming in, and the abiding, one and the same forever;
the same life and power and love and eternal sweetness being all and in all forever.
This is the mark of Israel, and the haven of its eternal rest,
to which the Lord is leading the poor, hungry, empty, mourning, afflicted, tossed souls,
to whom it is as sure in the love and good-will of God (and
in the counsel of his heart determined thereupon),
as if they were already in it.
