[#to-friends, short="To Friends, in the Tender Spirit of Life and Love"]
== To Friends

[.heading-continuation-blurb]
In England, Ireland, Scotland, Holland, New England, Barbados, or anywhere else,
where the Lord God shall order this to come, in the tender spirit of life and love, greeting.

[.section-date]
1666

O FRIENDS!

IN the pure love of God, and fresh breath of his living Spirit,
is it now on my heart to write unto you, in fear, in tenderness, in meltings,
and true sense of spirit; and the Lord so guide my heart and words,
as that they may reach the witness in the hearts of all that shall read,
and may be felt by that to be purely of God, and not at all of the birth, will,
or wisdom of the flesh.

I remember, I remember,
O Friends! and it is in my heart to put you in remembrance of the cloudy, dismal,
and dark day, wherein the Shepherd of Israel visited our souls,
and what condition we were in,
when he caused the light of life to shine upon our tabernacles, and to spring up in us.
Oh the desolation, the desolation that our souls were in, in that day!
Oh the wanderings up and down, the seekings, huntings, mournings, bitter complaints,
and deep distresses for want of our God, and for want of the guidance of his good Spirit!
Who can utter now what was then felt of the thickness of darkness, of the misery,
the loss, the dreadful captivity that our poor souls were entangled and wrapped up in?
Oh, how acceptable was the visitation of God then! how deep was the sense
of his tender mercy in visiting! how glad was the soul then of the living
path revealed! how unfeigned did it cleave unto the Lord,
and embrace the measure of his life revealed inwardly to the mind! how
did it fear! how did it wait! how did it watch against the enemy,
and cry to the Father for his help!
How beautiful were the feet, and how pleasant the visitations of them,
who brought the tidings of this life and peace!
What love, what unity, what embracing one another in this life,
was then witnessed in the hearts of one another!
and where this lives and grows to this day,
oh how precious is that vessel! but where the life in any is departed from,
where another thing, of another nature, hath entered and been entertained by any,
there it is not so; but there the love is grown cold, the mind changed,
the goodness of the Lord forgotten,
and the poor soul again entangled in that which formerly
it felt some release and deliverance from.

Now that the enemy would endeavor to entangle the minds of the redeemed,
and to draw them back from the Lord, and his pure measure of life in the heart,
towards perdition again, that is not to be questioned;
it being his nature and property so to do; and that he would use not only his strength,
but also his subtlety and deceivableness to effect this
(his aim being at the church and redeemed of God,
more than at the world); appearing as an angel of light, in motions like light,
in ways like life; this is not to be doubted of either;
for how else could he gain upon that, whose eye is towards, and whose aim is after,
the Lord?
But this is the great thing for my heart, and the hearts of Friends, to be exercised in,
to wait on the Lord in his true light,
clearly to discern how far we have been assaulted by this enemy,
and how far the Lord hath preserved us from his assaults,
or suffered him to prevail upon us; for he hath prevailed in former ages,
under the ministration of the law in the prophets`' days,
and under the ministration of the gospel in the apostles`' days; yea,
and I must needs say, he hath also prevailed in our days,
on all that have not watched in the pure fear,
and been preserved by the pure power of the Lord.
Now doth it not concern every one to look up to the Lord,
to guide his heart in searching, that he may truly understand his state?
That, if he can witness the preservation of the power, he may sing praise to the power;
but if he hath been betrayed, and come to a loss,
he may seek after the power of life again, and wait for deliverance and restoring by it.
For with the Lord God is mercy and bowels, and he seeketh after and saveth the lost,
not once only, but again and again; only here is the great danger of souls,
when they are ignorant of their captivity, and judge in themselves,
and are guided by that which should be judged down and destroyed in them.
When darkness is the light and leader in the mind, oh, whither doth that soul travel!
How doth it judge, think,
act! how sure doth the enemy hold it in his bonds and chains! how
easily doth he prejudice it against that which is of God,
and for its good,
and incline it to think favorably of that which only appeareth to be of God, but is not,
and is to its hurt!

Now, Friends, there were three things on my heart this morning,
which sprang up in true sense and demonstration of God`'s Spirit,
as subtle engines which the enemy hath endeavored to make use of to hurt our souls;
which any that have been entangled in, have received hurt by,
and those that have escaped have cause to bless the name of the preserver of Israel.

The first is this:
By begetting in persons prejudices against those whom the Lord hath chosen,
and pleaseth to make use of in ministering to his people.
Precious is the ministry that is in the Spirit, for the building up in life,
as well as for begetting.
How doth the enemy strive to prejudice the world against them,
that there may be no begetting to God from amongst them!
And how doth he also endeavor to raise prejudices amongst the begotten,
that he may interrupt, and, if possible, stop their building up.

The second is this: To draw men from eying and subjecting to the present dispensation,
by an earnest looking after and waiting for another, or further.
The security and blessing of the soul lies in the present dispensation,
in bowing to God there, in being diligent under the exercises of his spirit therein.
Now that which draws the mind another way from the present exercise,
from belief in the present gift,
under a specious pretence of waiting for somewhat more glorious to appear,
betrays and deceives,
in thus turning the mind out of the path which God holds forth and guides into,
towards expectation of a path as yet to be revealed.

The third is this:
Under a pretence of sticking to the enlightening and guidance of one`'s own measure,
to set up a sense and judgment in the mind, both concerning persons, practices,
and things, which is not truly of the measure,
but secretly instilled into and raised up in the mind,
contrary to the pure measure of life.
All these have I not only seen in spirit, but been sorely assaulted with;
and that they have not prevailed upon me even to destruction,
is the tender mercy and kindness of the Lord unto me; and in that tenderness and love,
for the preservation of others, do I write these things.
And indeed I have somewhat in my heart to say singly
and nakedly concerning each of these,
which the Lord guide and bless to the conditions of those who stand in need thereof.

First,
Concerning those prejudices which the enemy is apt to lay before the minds of Friends
concerning those whom the Lord hath chosen to minister to them in the power of his truth,
I shall say this: Look over the former dispensations of God;
there were false prophets under the law,
and false apostles and ministers in the time of that dispensation of the gospel,
who did strive and labor hard to disturb,
undermine and overturn the building and work of God in the spirits of his people then;
but did God suffer the true prophets under the law, or the true apostles,
to fall and lose their ministry?
And is not this present dispensation pure and living,
and able to preserve both the instructors and instructed in the Lord?
It is natural to the enemy to suggest such a thing; but let all that fear the Lord,
and love his truth, take heed how they entertain such a suggestion.
Besides, he that hath felt the pure power in his heart,
and waited to be carried through the work of it,
and hath been carried through and brought into the dominion,
and set as a pillar in the temple of the Lord, it is not easy, if possible,
for him to fall, the Lord having undertaken for him, that he shall go no more forth,
as Rev. 3:12. But let me say this to thee,
O soul! whoever hast entertained this prejudice, Thou,
through prejudices and suggestions, judgest them fallen; but do not they,
in the true eternal light of the Spirit of life, see thee fallen?
Nay, if thou couldst but retire to the pure measure that at first quickened thee,
mightest not thou feel thy own fall?

To the second, of drawing out the mind to look after another or further dispensation,
I have this to say: Consider what this dispensation is; is it not of the seed itself?
Is it not of the light, life, and power of the Father, manifested in the seed,
and in the soul through the seed?
Is not the sense quick, and the love pure, where this is felt?
What wouldst thou have poor soul?
Oh that thou feltest the virtue and power of this! surely thou
wouldst then find that thou mightest sit down here in the peace,
purity, power, dominion, and perfection of life; for it is all in the seed,
and to be revealed to thee, and become thine, as thou art gathered into the seed,
and the seed opened in thee.
Besides, are there not many that have witnessed, and that can witness from God,
that this is the dispensation which is to go through the whole earth?
And shall it be laid aside in the beginning of its work?
"`If there had been a law given,
which could have given life`" (said the apostle) "`righteousness
should have been by the law.`" God doth not change.
When he hath brought forth that which will do the thing, why should he change it?
Now of the ability of this there are many witnesses; yea,
it hath brought forth life and righteousness in those that have been subject to it,
and was once owned as the desire of our souls, and became a covering to our eyes,
that we could look no further; our hearts, in the sense and life of truth,
being satisfied that this was the very thing we had long mourned after, and waited for.
Oh! that which begets another sense in any of us
(under what pretence or appearance soever),
let it be the abomination of our souls, that we hearken not,
nor give the least entertainment to it,
lest by it we are betrayed of our portion in the blessed treasure and inheritance.

To the third I say: It is a standing truth, the standard we were invited to,
and to which we are to keep forever, even the measure of life in our own vessels.
This will justify us in our subjection to whatever it reveals;
and its justification will stand, whatsoever any man else shall say to the contrary.
But this is at unity in itself,
and never opposeth the motion or appearance of life in another.
Now this is certain, the enemy will appear as near life and its motion as he can;
and if I receive his appearance, I am not subject to the measure of life in me,
but to him under his deceitful appearance.
Therefore if that which appears like life in thee contradict a practice
or appearance of life in others (who were in the truth before thee,
and are in the growth thereof far beyond thee), oughtest thou not to be sober in spirit,
and to wait in fear, lest thou shouldst be deceived;
lest thou shouldst exalt self and the enemy in thee, and not the truth; yea,
lest thy heart should grow hard, and thy neck stiff,
against those who are over thee in the Lord,
and so thou lose the benefit of their watching over thee, and counsel to thee,
and of God`'s preservation: for out of the truth, in the deceitful appearance,
there is no preservation, nor true light, nor justification of life; but self-conceit,
fleshly confidence, and the justification of a man`'s own spirit;
and his wisdom then gets up, and exalts itself, as if it were the right thing.
The Lord gave the measure of life to thee; and the Lord also hath given fathers, guides,
instructors, watchmen in his Israel.
These have a service from the Lord towards thee,
who knoweth that thy soul hath need of that service:
now if the enemy can prejudice thee against, and withdraw thee from,
the use of what thou needest, art thou not in danger of falling and miscarriage?
Dost not thou set up the measure of life in thee (if not another thing) beyond its place,
state, and growth?
And can any thing grow and thrive out of the order and wisdom of God?
Nay, nay; the very measure of life itself will this way come to wither and die in thee,
and another thing live in its place;
and the sword of the Lord will be drawn against thee,
and thou wilt be cut off from the body,
and also from him who is the quickener and preserver of the body.
Therefore, my friends, as the enemy watcheth to deceive and destroy,
so the Lord keep our souls in the true watch and looking up to him,
who (to those that fear him) discovereth the deceit, and preserveth from, the snare.

And this is witnessed concerning the measure of life in the heart,
and the way of its acting and operation, that it always acts in its place,
even in due subjection to the Father of spirits,
and to his life in others according to its growth;
for there is no rent nor division in the living body;
no setting up one measure of life against another measure,
or one motion of life against another motion, or one practice against another;
but all there is in the unity, in the love, in the tenderness, in the sense,
in the peace, in the dominion, in the subjection;
and that which differeth or dissenteth from the life,
interrupting the union and uniformity in the life, is not of the life;
which when it is everywhere cast out, life to life will answer everywhere;
which day my soul breatheth and waiteth for,
even the day wherein life alone shall live and reign in every vessel,
and all the devices and snares of the enemy not be able to enter
upon or catch any of God`'s little simple-hearted ones;
but still, by the power of life rising in clearness against them,
be thrown back upon the enemy, to his torment and disadvantage.

And, O dear lambs! consider how easy it is for you to mistake, err,
and wander from the truth; and do not refuse the care, watchfulness,
and tender counsel or those who were instrumental to beget you to, and are yet over you,
in the Lord.
Alas! how easy is it for the enemy to deceive your simplicity,
and get between you and your life;
and then ye are liable to mis-see and mis-act in all ye do, and to follow the enemy,
as if he were your right guide; and to fight against, and resist him,
who is your true leader, as if he were your enemy!
The life in you is to be your guide and leader, as it groweth up and receiveth ability,
strength, and dominion from the Lord; but the heir is to be under tutors and governors,
till the time appointed of the Father.
And the seed is meek, humble, tender, lowly, sensible of its own state and weakness,
and subject to the exaltation, dominion, and pure authority of life in others,
where the Lord hath so exalted it.
That which is otherwise in you (which is high, exalted, conceited of itself,
and not subject to every degree of life in others,
according to its state) is another thing, which is not of the true kind,
but only under a guise appears to you as the true; and as it gets entrance,
corrupts your hearts from the true,
and distils its poison into your spirits! which ye believing, entertaining,
and feeding upon, as if it were the true, grow up in his poisonful nature,
losing the pure nature and fellowship of the body,
and are travelling whither ye are not aware; being gone from that which first gathered,
into that which, through subtlety, hath deceived,
appearing to you as if it was still the same, and that ye still keep to it,
but others are departed: whereas the thing is clean contrary in the sight of the Lord,
and in the sight of those who keep to the anointing, and see with his eye.
Therefore,
O dear lambs and babes! what need have we to wait in tender
sense for the Lord`'s preservation of us in that nature,
spirit, and life, whereof we were begotten, and wherein we were taught,
that there we may still learn and keep to the true teaching,
in the innocency and simplicity of love,
and not hearken to the wisdom and reasonings of another spirit,
who lieth at watch to catch the mind with his wiles, and draw from the true thing.
Mark how we learned at first: was it not in a nature,
by a secret instinct and inclination of our minds towards the life, and the path, ways,
and practices thereof, whereinto the body, which before had been gathered,
was led and walked before us?
The same life, when it maketh us part of the flock, bringeth us into the same footsteps;
and there we walk with them, in the unity of the same life, and sense of the same leader;
but if the enemy can at any time draw us from this sense,
and from the belief and practices or practice which we received in this sense,
even out of the limits of this nature and its naturalness,
how easy is it for him to persuade us to question right things in our minds and understandings,
as if they were wrong (darkening our eye and causing us to overlook and forget the leading
and motion which we had in the true sense and nature from the anointing itself),
and so confidently to think and conclude,
that we took up such or such a practice by imitation, and have held it up in form.
Whereas the Lord, who forgetteth not what and how he hath wrought in us,
knoweth that we took it up in the sense and leading of his truth,
and are now tempted from that in the reasoning subtlety,
which we formerly practised in the true innocent simplicity.
And thus getting into us a belief and entertainment of his snare,
he draws us from that which at first led us,
and from the practices we were at first led into, to hearken to him, and follow him,
who instructeth us in a way we were not instructed
in before while the Lord instructed us;
and so destroyeth his nature, and the work of his Spirit in us,
dividing us both from the head and living body; and so our standing, growth, sense,
and judgment is altered, and we are neither to the Lord what we were before,
nor is he to us what he was before; for he hates that spirit in all its appearances,
and cannot have unity with the souls that are entangled by it.
Therefore, dear friends, as we prize our gathering to, and abiding with, the Lord,
and the enjoyment of his love, peace, joy, and presence at present,
and the crown and inheritance of life with him forever; so let us fear, so let us watch,
so let us cry unto him, to be preserved by him,
which gathered us in that into which he gathered,
and not by any means be betrayed (through subtlety of the enemy) into another thing,
where the life of the body (and union with the body) cannot possibly be witnessed,
nor the true justification of the Lord;
but only an appearing justification of a man`'s own spirit,
which must afterwards come under condemnation.
Ye, who are in the living and true sense, will feel my love, tenderness,
and faithfulness in what I write; and ye who are not, the Lord God of bowels pity,
and recover you out of the snare and wrong judgment, that ye may feel it;
and feeling that which is true, may be joined to it,
drinking of its virtue and preservation, and live;
which is the earnest desire of my soul to the Lord, who am

Your brother and companion in the tribulation and mercies which attend the living,

ISAAC PENINGTON.

From Aylesbury prison, the 14th of the Fifth month, 1666.

=== Postscript

DEAR friends, brethren, lambs, and plants of the Most High,
it is in my heart to add one thing, which I have been deeply exercised about,
and have received help from the Lord in, wherein I am truly willing,
in faithfulness and tenderness, to be helpful to any of you that stand in need thereof,
as the Lord shall give me ability and opportunity.
It is this:--

Among other things,
wherewith the enemy endeavoreth to reproach those whom the Lord hath sent forth among us,
he maketh use of this, as if they wanted bowels and tenderness.
Now, friends, I beseech you to consider it, that the enemy may not thus enter you.
Did not the Lord consider of his work,
and whom he sent forth in this his service and labor of love?
Doth he not know the need of bowels and tenderness in them,
and would he not especially furnish them therewith?
Yea, have they not bowels from and in the Lord?
And doth not the eye that is open see and acknowledge their bowels,
and bless the Lord for them?
I have lately been often warmed in the true sense of it,
and have felt that therein I have not blessed his name in vain;
but the thing is so in the sense of truth,
and so acknowledged before the Lord in that which erreth not:
only as true judgment and severity hath its proper place in the Lord,
as well as his mercy, and is made use of by him towards his people,
as all by experience know; so must it be in them also that bear his image; who must know,
in his wisdom and authority, whom to smite with his rod and sharp reproofs,
and when and whom to cherish in the tenderness and meltings of love.
And this is also love and tenderness (and hath sweet
and precious virtue and usefulness in it,
both for the recovery and restoring of those whose condition calls for the sharp stroke,
and for the preservation of the rest),
though it doth not so appear to that which by no means can endure the judgment,
but would have the tenderness and mercy which belongs not to it;
for the mercy is to be broken, to the humble, to the meek, to the afflicted,
and bowed-down ones under the sense of judgment;
not to the stiff and stubborn against the righteous
judgments and testimonies of the Lord.
And, my friends, consider,
could the Lord carry on his glorious work in the
hearts of his children without his judgments?
Or can they who are sent by him possibly carry on his work among his people,
without making use of his pruning-knife,
to cut off that which sprouted out unnaturally and unseasonably,
which (if it be let alone) will draw away the sap from that
which should be fed and nourished with it?
Dear friends, the Lord give you a true sense, that in his light, life, wisdom,
and presence, ye may justify what is of him, discerning between things that differ;
and not call any thing that is evil (as the tenderness which is out of him is) good;
nor any thing that is good (as the judgment and severity which is of him is) evil;
but may rightly distinguish between the nature of things,
knowing everything that is of God, and owning it in its place.

Aylesbury prison, the 29th of the Sixth month, 1666
