== One More Tender Visitation / To the Men of this Generation

[.heading-continuation-blurb]
Sent to them in bowels of love and tender compassion before their day be over.

[.section-date]
1666

[.offset]
Oh that those who read this might read with a right understanding,
and have a true sense of what is here proposed for the good of their souls!

IF there be a God,
and if this God hath let down a principle of life
from himself into the hearts of the sons of men,
to gather them out of the world unto himself by; and if we have been directed to,
and enlightened by, this principle, and have heard his voice,
and been gathered to him in it, and therein have been taught his true spiritual worship,
and drawn out of the worships, fashions, customs, and ways of the world,
who are estranged from God, and walk in their own wisdom,
satisfying the lusts of the flesh, and of the mind,
and doing what is right in their own eyes,--I say, if it be indeed so with us,
then that which any do against us, in this respect, they do against God.
The risings of heart against us, the hard words and reproaches,
the contriving to destroy or root us out of the land,
the making and executing sharp laws against us, etc., all this,
and whatever else is done against us on this occasion, must needs be done against him.

And what will this produce?
Will it not also engage the wisdom and power of the Lord against you?
He may let us suffer long, and let you be hardened against us, as if we were not of God,
by the slips and foolishness of such who have seemed to be of us,
but have not kept to his truth; yet still those that keep to the Spirit and truth of God,
are of God, and he is tender of them.
And if he that touched Israel after the flesh, touched the apple of his eye,
what doth he that toucheth his spiritual Israel?
We are content and quiet under what the Lord suffers to befall us from you;
but ye will find, in the end, it will not be well for you to deal so with us.
The Lord hath a spiritual crown, dignity,
and dominion in the hearts of many in this nation; why should he not enjoy it?
Why should not men let him enjoy his heavenly rule, who giveth to them their earthly,
and who can take it from them when he pleaseth?
See Dan. 4:32. and 35.

Therefore, my dear countrymen (and ye especially that are in authority), consider,
oh consider before it be too late!
I hope,
I hope (though the provocations have been very great) that it is not yet too
late for many of you to find a place of repentance and remission with the Lord.
If ye can plead ignorance before the Lord,
and that ye have not known what ye have done herein, he pitieth that,
if ye yet hearken to his counsel and reproof, and return unto him.
He hath power to destroy this nation; he hath power to do what he will in this nation.
Oh! fear before him, and take heed of fighting against him before whom none can stand.

Alas! if ye knew what we were doing,
while ye are afflicting and persecuting us for our subjection to the Lord,
surely it could not but melt and overcome you;
even how we have been mourning and wrestling many times with our God,
in earnest prayers and supplications to him for you;
not that we might escape your wrath (which he enableth us to bear),
but that ye might escape his fury, and terrible indignation,
which we know is ready to break forth, and that ye will not be able to bear it,
when it doth break forth; but it will pursue, overtake, break to pieces, and scatter,
and there will be none to deliver.

Are not these things serious?
Are they not true?
Are they not written in love?
Why should they not take place in you?
Oh! come out of the circle and mist of darkness, that ye may see the truth of them.
If ye be not in the nature of Christians, do not deceive yourselves, and provoke God,
in taking the name unto you.
If ye be true Christians, do not judge or walk as men,
even in and according to the wisdom of the earthly principle;
but feel that principle which is of God, and in that wait for,
and learn to hear and know the voice of God, and that will lead (out of all profane ways,
out of all superstitious ways, yea,
out of all the ways that man`'s fallen wisdom hath taught
and erred in) into the way of true and sound judgment,
where the true reformation within will be witnessed by you,
and the true reformation without brought forth through you (thus acting),
and no separation or rent from you heard of by them that fear the Lord.

But till then, the principle of God, the life of God in the heart,
the pure wisdom which is from above, cannot own that which is from below, in its fall,
in its separation from the true; but must remain distinct from it,
and a faithful witness against it.
And I say again and again, in the love and fear of God unto you,
take heed how ye persecute this in any, or any because of this:
for it will lie more heavy upon you in the day of God`'s pleading with you,
and executing his righteous judgments, than all your other sins.
If ye have ears to hear, oh! hear, and cast up your accounts,
making your peace with God before his wrath break forth against you like a flood,
which none can stop.

Feel my love, and the meltings of my spirit for you before the Lord;
and be not hardened against the truth, lest ye remember my words,
and the warnings of many of the precious servants of the Lord,
to the increase of your grief, and not to your benefit, in the day of your calamity.

BY ISAAC PENINGTON.

Written in Aylesbury prison, 16th of 5th month, 1666.
