== Concerning the Church: / Or of the Church State Under the Gospel

[.heading-continuation-blurb]
Whereby it may appear what a miserable _Apostasy_ from the _Truth_ hath
overspread and covered the Earth for many Ages and Generations,
and how gross and thick the Darkness yet lies upon it;
though the Light of _God,_ in his tender Mercy,
hath broke forth and shined upon the People of his gathering,
and through them hath also visited the World.

[.heading-continuation-blurb]
The Guidance of this in my heart was particularly and chiefly towards the Papists;
but I afterwards had a true sense that it also extended to the state of such Protestants
as had not waited on the Lord, for him, in his wisdom and power,
to rear up his own building, but had ventured to build of themselves,
and so had reared up Churches in the same spirit of error, darkness, and apostasy,
which they seemed to depart from: against all which the Lord will fight,
and all which he will break down,
in the day of the revelation of the glorious Light and Power of his Truth,
which will overcome, subdue, and reign over the earth;
not after the manner of men, but in the heavenly dominion of his life.

[.heading-continuation-blurb]
Written in _Aylesbury_ Prison, about the middle of Sixth month, 1666.

[.section-author]
By _Isaac Penington_

[.heading-continuation-blurb]
Whereunto are annexed some observations upon the eternal judgment,
as it is expressed by Christ, Matt. 25:31. to the end of the chapter.

=== Preface

BECAUSE the corruption of the Christian doctrine and worship hath been great (yea,
indeed very great) since the days of the apostles;
and the judgments also are to be very great, because of this corruption;
even dreadful woes, plagues, cups of wrath, and thunders unutterable,
as is expressed in the book of the Revelations; therefore,
that men may avoid the terrible wrath of God, which is breaking and to break forth,
by discerning and forsaking that which his wrath is against,--therefore, I say,
in tender bowels was it in my heart to discover somewhat of that which the Lord hath
made manifest to me (among many others) concerning the creeping in of this corrupt state,
and its getting up after the days of the apostles, with its continuance to this day;
that men and churches may consider their state, see their nakedness,
and look after the pure garment; that they may be clothed with the Spirit of the Lord,
and found in the righteousness thereof, that so they may stand boldly before him,
when the transgressors and hypocrites (of all sorts)
shall have their fig-leaf coverings ripped off,
and lie open to the strokes of his indignation.
And this I say to all:
take heed of two things in this day of the Lord`'s love and vengeance;
take heed of retaining or setting up any thing which the Lord is coming forth against;
and take heed of slighting or appearing against that
which the Lord is preparing to set up.
The appearance of his Spirit, the shining of his day, is precious,
even in the meanest glimmerings of it.
Oh! who shall be guiltless before him,
who defendeth or setteth up any thing of man`'s will or wisdom (his sun, moon, and stars,
in all their glory, being to fall and lose their shining),
or who debaseth the lowest appearance of his seed!
And if the Jews suffered so deeply for refusing and
despising Christ`'s appearance in the flesh,
what will light on those who refuse and despise his appearance in Spirit?
I know this, that Christians now overlook and slight this, as the Jews did that,
and by the same snare, even by a prejudice they have drunk in,
that this is contrary to the Scriptures, as the Jews then did conclude,
that that coming of Christ then was not agreeable to, but different from,
what the Scriptures had said concerning his coming.
But what said Christ then?
"`Wisdom is justified of her children.`" They who then were of the spirit,
and in the spirit, knew the voice of the bridegroom then.
And such also know it now, and rejoice in it;
though the wise in another wisdom (according to the
Scriptures as they think) refuse and disdain it;
and not knowing the righteousness of Christ in spirit,
set up a righteousness of their own in the flesh:
for their believing (and applying to themselves the righteousness
of Christ) out of the true limits of life,
according to their own apprehension of things, is no other.
And this must fall.
Man`'s knowledge of scriptures, the faith of man, through his own apprehensions,
must fall, and man appear naked underneath,
that the glorious righteousness of Christ in Spirit, and the precious covering thereof,
may be magnified over all.
And in this light of life, and newness of nature in Christ,
runs the blood which cleanseth, and not elsewhere.
It runs not according to men`'s notions, but in its own life, virtue,
and power in the heart; where (where it is livingly felt) the iniquity is washed away,
the sin is gone, the everlasting righteousness appears; yea, the water springs,
which washeth and keepeth clean continually.
Away with your notions, and empty husks,
O several sorts of professors! come to the thing itself,
or rather wait on the Lord to be led to it, that ye may feel the seed, the pure seed,
the living seed, the Holy One of God, and may know its planting and growth in you,
and your unclothing and emptying of all else, that ye may be clothed upon,
and filled with it.
And in the sense of it, and unity with it, ye will own and love what comes from it,
and rejoice in all the springings of its light, either within or without.

[.centered]
=== Of the Church State Under the Gospel

THE Jews`' church state under the law was precious; who,
walking with God according to the covenant of the law, were an holy people,
nigh and dear unto God above all other people.
But they provoked him so continually and grievously, that instead of blessings,
they drew plagues upon themselves, and were, at last, by his righteous judgments,
made desolate, and cut off from being any longer his select nation and people.

The church state of the Christians under the gospel is much more precious and glorious,
they being gathered into the substance of that,
whereof the Jews`' state had but the shadow.
The presence of God,
the manifestation of his life and power is more inward and bright among them;
their union with him more close, their communion and joy more full,
he tabernacling among them, dwelling and walking with them,
and advancing them into the state of sons and daughters;
whereas the law state was but a state of servitude.
And their standing also is more firm;
the covenant wherein they stand being more able to
hold them together with God than the other was.
The standing of the other was by the works of the law,
which they were to observe and live.
The standing of these is in the faith, which is from the power,
which worketh their works in them and for them.

Yet, as they are gathered in the faith, so their standing is in the faith,
and out of it they cannot be preserved.
So that (before they are established) there is a
possibility of their fall from the faith,
wherein their standing is, and from the power which preserveth.
And if they so fall, they are liable to be cut off, as the Jews were,
as their apostle tells them. Rom. 11:20-22.
In the fear, in the humility before the Lord, in keeping to the faith,
their safety is; but if they become high-minded,
because of their state and church privileges; if they think their standing so sure,
as that they are out of the danger of falling, then they are out of the fear,
out of the humility, out of the faith which preserves; and being out of the preservation,
must needs fall, and so continuing, must needs be cut off.

Now the same apostle doth not only warn them to take heed of falling from the faith,
but afterwards expressly foretells of a falling away,
even that there must come such a thing amongst them also; yea,
and of such a falling away from the truth and power of life,
as should give antichrist advantage to get into God`'s temple, and sit there as God,
taking upon him the power and authority,
as if he had the true power and authority of God. 2 Thess. 2:3-4.
And what doth he then?
Doth he not corrupt all, even as God`'s power and presence purifies and preserves all?
And as he shows himself as God,
so doth he not also show forth his church as God`'s church?
Yea, it goes on in the world as God`'s. All that drink of his spouse`'s cup take it to be so;
who are very many and great ones, even kings and inhabitants of the earth, peoples,
multitudes, nations, and tongues, Rev. 17:2. 15. and chap.
18;3. and none are able to discern that it is not so,
but those that are anointed with the true eye-salve,
which giveth to see through his deceits. 1 John 2:20.
For he cometh "`with all deceivableness of unrighteousness;`" 2 Thess. 2:10-9.
he maketh the church (after he hath got possession of it,
and made it his, sitting as God in it) appear as like the true church as possibly he can,
that he may hold up his mystery of deceit in the world, which if once discerned,
would soon fall, and come to nothing. 2 Thess. 2:7.
Rev. 17:5.

To open these things a little more fully and further from the Scriptures,
that they who yet cannot read otherwise may read them there,
and come in some measure to the acknowledgment of the truth,
and wait for the power from on high,
from whence is the true faith (wherein is the true church and its standing),
for want of which the world is become a wilderness; full indeed of profession,
but very empty of the nature and life of Christianity.

Christ tells his disciples, that false christs and false prophets should come,
and deceive many; yea, that they should prevail so far as, if it were possible,
to deceive the very elect. Matt. 7:15.
and chap.
24:11. 24. The Lord God hath sent forth his truth,
and now after it he suffers to go forth a power of deceit, a mighty power,
even having all manner of deceivableness of unrighteousness in it. 2 Thess. 2:10-9.
And it works according to its power,
it gathers all its own everywhere.
Not one, but he that is of the elect seed, can stand before it.
Now the reason why God suffered this to go forth, was in judgment.
Men had dallied with the truth, taken up a form of godliness, and rejected the power;
therefore God withdraws from the form, and suffers the unclean spirit to enter it,
and the uncircumcised nature of man to shelter itself there.
It arose also from the devil`'s subtlety, who,
finding himself dispossessing of his kingdom, played this master-piece,
both to save what he could at present, and to recover the rest again in process of time.
He (in his apostles and ministers) takes upon him the profession of Christianity,
sending them forth as the ministers of righteousness; 2 Cor. 11:13. 15.
but for all that, they were still of the worldly nature,
of the worldly root, spirit, and principle;
and so by them he brings forth Christianity (or the profession and observation of the
Christian religion) in such a way as would please the worldly mind and nature;
and bringing it forth so,
he gathers to him all that were not gathered and preserved by the power,
and so becomes the greater body and church in view,
and the rest (as to the outwardness of their church state) are fain to give way,
and retire into the power, out of their former place and station in the world.
Rev. 12.

Now as Christ had said that false christs and false prophets should come;
so John said they were come; 1 John 2:18. and also showed from whence they came,
"`They went out from us.`" ver. 19. They were such as came into the form among us,
but were not begotten of the life, nor subject to the power with us.
And there were many of them, chap.
4:1. and such they were as had a great power of deceit, and came therewith to seduce them.
1 John 2;26. Therefore he bids them, in the unction which they had received,
ver. 27. which searcheth and discerneth all,
"`try the spirits.`" If their spirit (or the spirit that is in them)
confess Christ (who is the power of the endless life,
the sum, substance, and end of all that which shadowed forth life), they are of God.
chap.
4:2. But if their spirit confess not Christ come in the flesh,
though they may seem ever so much to preach him, they are not of God.
ver. 3. Now whose spirit confesseth Christ?
Surely his only that is subject to him.
He that preacheth Christ in words, and denieth him in works,
whose works are not wrought in Christ, nor brought forth by Christ,
his confession is but outward, but formal; it is no true confession.
It is but the confession of his mouth, not of his spirit; and he is, in the sight of God,
not a confessor, but a denier, of him: and whoso is enabled by God to try spirits,
and waiteth in his light and anointing to try such, findeth him to be so,
and notwithstanding all his fair words and speeches of Christ,
and his pretending to be his minister.
Rev. 2;2. For men with fine words,
and fair speeches may deceive the hearts of the simple;
but they cannot deceive those to whom God giveth ability to try spirits.
Could the devil deceive Christ, when he said "`Thou art the son of God`"? No;
Christ knew his spirit to be against him, notwithstanding those words.
And can the ministers of antichrist deceive the elect of God, when they preach up Christ,
in words, to be the Saviour and Redeemer,
and yet own not that life and power which saves, but persecute it wherever they find it?
No;
the same Spirit of Christ in them discerneth quite through their words to their spirit.
"`My sheep,`" saith Christ, "`hear my voice.`" John 10:27. Man may be deceived,
and caught in the snare; but the elect, the sheep,
know the voice of the Shepherd from the voice of the stranger.
If the stranger say, Christ is the Son of God; though he believes, and owns the thing,
yet they receive it not from his mouth.
Well; whence are these false prophets and false christs?
"`They are of the world.`" That is their root.
Thence they come.
They are of the worldly spirit, the worldly wisdom, the worldly nature,
only clothed outwardly with a profession and show of the
doctrine and practices of Christ and his apostles.
And what do they do?
"`They preach worldly things.`" They suit their doctrine to the worldly nature, principle,
and spirit.
And what is their success?
"`The world heareth them.`" 1 John 4:5. The earthly wisdom in man falls in with them,
judges them to be right, owns them,
sets up their way of Christianity and worship in the world;
and thus the world become Christians.
Those which came in the name of Christ, the world could not receive.
("`He that knoweth God heareth us;`" not the world.
1+++.+++ John 4:6) There were but a few, in comparison, gathered here and there then;
a few in one place a few in another.
The doctrine that comes forth in the power scatters the worldly part.
Man`'s wisdom, man`'s nature, cannot receive it, in the love and life of it.
But when these false christs and false prophets come, the world can turn Christians;
then a whole city, or a whole nation, can presently become a church.
Why so?
These come in that which the world can receive, which their wisdom can answer,
fall in with, and subject to.
These can bring forth a cross, which the world can like, fall down, and worship;
but the cross of Christ they cannot; for that crucifies and slays the worldly nature,
wherever it is felt, taken up, and subjected to.
The way of life is strait and narrow, and few there be that can walk therein;
but a broader way more may walk in.
The true church is not easily found or entered into;
but the false is wider and far larger; yea, desirable to the flesh.
The true church is circumspect,
will admit none but in the way of God`'s wisdom and power;
but the false church prostitutes and thrusts herself upon all.
She meets men in the streets, and forceth them into her bed;
whereas the voice of the true church is, wait for the preparation,
for the being changed by that which giveth entrance into the truth;
for the builder of the church is God, Heb. 3:4
(he builds this house by Christ, ver. 6. as by Moses he built the house under the law)
and he is the ladder to the building. Acts 2:47.

So Paul also, writing to Timothy, tells him of perilous times in the last days.
2 Tim.
3;1. For when the last days come, and the antichrists and false prophets appear,
then men are in great danger of being deceived,
and of making shipwreck of faith and a good conscience.
Then he that is not in the truth, but only in the form and outward appearance,
will be swallowed up by the deceit,
and take up his dwelling in the form without the power;
for so saith the apostle concerning them, ver. 5 they have a form of godliness,
but deny the power of it.
And all manner of wickedness will shelter itself under this form; Self-love,
covetousness, boastings, pride, blasphemy, disobedience to parents, unthankfulness,
unholiness, etc., ver. 2,3,4. and indeed what not?
For what is so evil,
which cannot shelter itself under that form of religion and profession,
where there is not the true power and life of religion to resist and subdue it?

Now mark; When these antichrists and false prophets had got up into a body and strength,
gaining authority and credit in the world, what did they then do,
but endeavor wholly to crush and suppress the truth, with those that abode still in it?
Then the dragon, with his angels, fighteth with Michael and his angels.
They had still been fighting with the apostles and ministers of Christ,
endeavoring to disparage them, and eat out their esteem in the churches, as 2 Cor. 11.
but they could not prevail; Satan, in all his enterprises, fell down,
like lightening, before the glory and power of Christ in his apostles and ministers.
But when the apostasy increased, and the churches provoked their preserver,
growing cold in love, and faint in faith (being lifted up with their gifts,
thinking highly of themselves, and their standing to be firm),
and many received not the love of the truth, but only a profession of it for by-ends,
etc., then the Lord began to threaten some with the removal of their candlestick,
and did afterwards proceed in judgment,
even to let the false prophets and antichrist prevail, and strong delusions enter,
that they who had dallied with the truth,
might be frustrated of the salvation they expected by it,
meeting with a lie (which destroyeth) in the stead of it. 2 Thess. 2:10-12.
And so God, who before built up,
in his jealousy and indignation afterwards threw down men abiding not in the faith,
nor in the power, but in the form and outward profession,
which (separated from the power) the Lord abhorreth.
What he loves, he secures for himself
(his holy temple, his holy altar, his spiritual worshippers);
and what he regarded not (which was the form and outward ordinances,
now polluted) he gave to the heathenishly-professing spirit; and there they worship,
and magnify their own state, prizing it by its outward glory and appearance,
and not by a right sense and knowledge of it in the truth.
Read these things outwardly,
in the letter (or rather wait upon God that ye may read them,
who caused them to be written to that end, to be read and understood),
Rev. 12. and chap. 11:1,2.
where the battle of the dragon is related, and God`'s taking down his building,
and disposing of it according to his pleasure.

Again mark; Antichrist gets into the temple (upon the falling away), sits there as God,
ruling, giving laws, and exacting obedience in the name of God: but when was this to be?
In the last times, 1 Tim. 4:1 (which would be very perilous,
through the power of wickedness and deceit, then getting up).
When did those times begin?
They began in the apostles`' days.
The mystery of iniquity was then at work. 2 Thess. 2:7.
Yea, saith John,
"`it is the last time;`" by the coming of the antichrists
and deceivers we know it to be so. 1 John 2:18.
Christ said, they should come; John said, they are come;
Paul saw them then at work in the mysterious power of darkness.
But they could not carry their work through,
the Spirit and power of Christ in his apostles stood so much in the way;
but after they were removed out of the way,
antichrist got up his mystery of deceit apace.
Well, how long doth he reign?
Even till the very coming of Christ in his Spirit and power; yea,
there is some remainder of him till the very brightness of his coming. 2 Thess. 2:8.
This mystery of iniquity hath power and authority over all the wisdom of man;
but the appearance of Christ, in the spirits of his people, hath power over it,
and tormenteth it, by opening its nakedness, and causing its darkness to appear;
and the brightness of his coming shall quite dissolve and scatter it.
For it is but a mist of darkness, it hath no being in the truth,
nor can it stand before the truth.
So Babylon is found standing at the very last;
just before the breaking forth and coming down of the New Jerusalem,
and the marriage of the lamb with his bride. Rev. 29:6-7.
What is Babylon?
A mystery of iniquity, in a form of godliness.
A profession, a people, a religion, that seem to set up Christ;
but set up another nature, spirit, and power in his stead.
A church that is not of God, not formed in his divine wisdom,
not brought forth in his light and power, and in the season of his will; but of man,
and by man, that can go no further in religion than the number of a man.
Zion, under the gospel, is not literal, but mystical; and so is Babylon also,
who is the mother of fornications,
who teacheth her daughters to adulterate from the life and from the power,
who never knew the marriage of the Lamb in his Spirit, nor his pure bed of life,
but enter into the chambers and bed of a strange spirit.

[.discourse-part]
Question.
But what is the state of the church all this while, from this hour of corruption,
till the coming of Christ in his Spirit and power?

[.discourse-part]
Answer.
A state of desolation, a state of widowhood, a wilderness state;
where her living body is not discerned by the vulturous eye; but her children,
whenever they appear witnessing for her, are persecuted, hunted, afflicted,
and sometimes slain.
This bloody church, which comes from the red dragon, and rules in his spirit and nature,
drinks the blood of the lambs and martyrs of JESUS, who, in their several ages,
are his faithful witnesses, and love not their lives unto the death.
And here the truth, and that which hath appeared of the true church in the world,
for ages and generations (ever since this night of the dragon`'s and antichrist`'s darkness,
and his sitting in the temple under an appearance of light), hath only been to be found,
even among the persecuted ones, who have been dear to God;
of whom the professing world hath not been worthy, no, not at all, of that heavenly life,
spirit, and power, which dwelt in them,
and through which they have been able to testify for the truth,
and bear up their heads against the malice and persecutions of their enemies.
Rev. 12:11,17,etc., and chap.
11:3,7. chap.
13:15,16,17. chap.
14:12 chap.
17:6.

Now, for a close: There are a few questions in my heart, briefly to propound and answer,
which it may please God to reach forth to his witness in such, who,
in distrust of themselves and their own wisdom, shall wait upon him for understanding.
The questions are these.
First, What a true church is?
Secondly, How a true church may be known?
Thirdly, how a true church may continue so?
Fourthly, How a church may lose its state and being?
Fifthly, When a church hath lost its state and being?

[.discourse-part]
Question.
1+++.+++ What is a true church?

[.discourse-part]
Answer.
A true church is a truly spiritual body, gathered out of the world,
or worldly nature and spirit, into God`'s Spirit and nature,
there to live and walk with him, and worship him in spirit and truth,
and for him to tabernacle in and walk among,
and fill with his glorious presence and powerful life. Eph. 2:21-22.
1 Pet. 2:5. John 4:23. 2 Cor. 6:16.
It is not the profession of the truth makes a true believer;
nor is it a company of professors makes a true church; but their proceeding from,
and union with, the truth itself;
and their abiding in the life and power of that which they profess. Eph. 4:16.

[.discourse-part]
Question.
2+++.+++ How may a true church be known?

[.discourse-part]
Answer.
There must be somewhat in man to know them, and somewhat in them to be known by.
That in man which knows them, must be somewhat of God in him;
for that which is of man cannot measure or judge of the things of God.
As the worldly wisdom and spirit could not know Christ formerly;
so neither now can it know his church.
Many may appear to be churches of Christ, and yet not be so; and that which is so,
may not appear so.
In this case, who shall distinguish?
Not he that judgeth according to the appearance,
but he that judgeth the righteous judgment.
Therefore it is not for every man to take upon him to judge which is the true church;
but first to wait upon God to be led into that, and in some measure born of that,
which giveth ability to judge.
"`Wisdom is justified of her children;`" but of others she is condemned for foolishness,
and the foolishness justified in her stead.

And there is also somewhat for the church to be known by,
which is that which distinguisheth her from all other assemblies and gatherings;
which is the nature, life, and presence of the head with her and in her.
This none hath, but the true church, the gathered body, the separate body of the Lamb,
which is of his flesh, and of his bones. Eph. 5:29-30.
Her husband is with her, his life is in her: for she is a living body,
or gathering of living stones.
So that find the true life of the Lamb anywhere, there is somewhat of his church;
find a gathering in his life, name, and power, there is his church, and he also.
"`For where two or three are gathered together in my name,
there am I in the midst of them.`" Matt.
18;20.

[.discourse-part]
Question.
3+++.+++ How may a true church continue so?

[.discourse-part]
Answer.
By abiding in the Spirit, life, and power, that gathered and built them up into a church.
This first gave them their being; and this still preserves them in their being,
if they abide till they be perfected and established;
but falling or being cut off from this, they wither, die, and come to nothing.
Even as a disciple, departing out of the vine, making shipwreck of the faith,
loseth that which made him a disciple or Christian; John 15:6. so a church,
departing from the Spirit and life of what they profess, languish by degrees,
even till their life be wholly extinct,
and they wholly lose that state and being which they had by their gathering.
Thus the churches in Asia, beginning to corrupt, grew formal, lukewarm, dead, etc.,
were warned to repent and strengthen that which remained, lest they were spewed out,
the candlestick removed, etc.
Rev. second and third chapters.

[.discourse-part]
Question.
4+++.+++ How may a church lose its state and being?

[.discourse-part]
Answer.
Several ways; as first, By departing from the truth and simplicity of the gospel;
letting in doctrines, principles, observations, customs, and practices,
which are not of the pure Spirit, nor in the unity of it; but from the corrupt spirit,
and which corrupt the minds of them that are entangled in them.
Corrupt doctrines, corrupt principles, corrupt practices, etc.,
they all have of the nature and poison of death in them; and as they prevail,
they bring death upon, and engage God against,
that person or church where they get dominion.
See what danger one corrupt doctrine of the Nicolaitans
brought the Church of Pergamos into,
even of God`'s coming forth with his sword and fighting against her.
Rev. 2;16. And if God, who is the defender of his church, himself fight against her,
how shall she stand?

2+++.+++ By negligence and sluggishness in the truth;
by this means also life may languish and extinguish by degrees,
even till death come wholly over and swallow it up. Rev. 3:1-3.
If the first love do but abate and wax cold, iniquity will be abounding, Matt. 24:12.
and the church will be in danger of losing its candlestick. Rev. 2:4-5.

3+++.+++ By God`'s withdrawing his presence and power, for these or such causes abovesaid,
which nourisheth and preserveth.
For the life of the church, as well as of a disciple,
is fed and nourished from the fountain or vine; and if it miss of the nourishment,
its life cannot long continue.
The Jews may keep up their sacrifices, and reading of the law;
but yet they are a dead people to God, after their cutting off from the olive-tree.
And the Gentiles may worship in the outward court, and keep up the outward ordinances,
after God`'s rejecting and cutting them off also, and be as dead to God therein,
as the Jews in theirs. Rev. 11:1-2.
and Rom. 11:21-22.

4+++.+++ By their listening and yielding to the power of the enemy,
who quickly deceiveth (with his lies, instead of the truth), destroyeth,
and layeth waste such buildings,
where God in his just judgment letteth him forth upon them.
For the gates of hell will prevail against that building,
which the arm of Christ is not stretched forth (or ceaseth) to defend.
And as the defence of every particular building upon the rock, is in its abiding there,
and subjecting to the head; so the defence of larger gatherings or churches,
is no otherwise.
As their union and gathering is, so is their standing; to wit,
in believing and giving up to their leader; hearkening to his voice,
and obeying him only.
But if they hearken to a stranger, if they hear another voice than his,
if they follow another spirit, letting in his lies and deceit,
they cannot keep their standing in the truth; but in so doing depart from it,
and lose the promise and protection of it.
For as before, by God`'s gathering them from the spirit of darkness, they became his,
and met with his power, presence, and blessing; so afterwards being again,
by any subtlety of deceit, gathered from the truth itself,
into some likeness and appearance of it, which the enemy hath formed,
they become the enemy`'s synagogue, not God`'s church; into which he entereth again,
and dwelleth there, in that likeness and appearance.
And this house, which was once cleansed, swept, and garnished by God,
being again recovered and repossessed by the enemy, becomes worse,
and more filthy in the nature of wickedness, than it was before.
What is more pure, glorious, and excellent, than a true church of God,
which is sanctified by his Spirit,
and holds forth the virtues and pure nature of his life in the world?
What is more filthy and abominable, and where doth Satan more strongly dwell and act,
than in that which pretends to be a church, and is not?
The promises of God are only to the seed absolutely; but not so to any man,
or society of men, but as, in the tender mercy of the Lord, they are gathered into,
and preserved in, the seed, in the way that the Lord hath chosen and appointed.
For the way of life is glorious and perfect, and the Lord will honor it;
so that those that expect to reap salvation from him,
must walk and abide with him therein; for besides him there is no Saviour;
and besides his way, there is no way of salvation, either for any man or church.

[.discourse-part]
Question.
5+++.+++ When hath a church lost its state and being?

[.discourse-part]
Answer.
When its nature is changed; when it is overcome by, and gathered into,
another power and spirit, than it was first gathered into by the Lord;
when its standing is not in the Spirit, nor after the Spirit, but in the flesh,
and after the flesh; when its ways are carnal, its weapons carnal;
when its hedge or wall is broken down, and the spirit of the world not kept out,
but entered into it, and become one with it.
Then it is no longer of God, and separate from the world; but one in nature, state,
and being with the world. Rev. 2:9.

These things are written in the love and good-will of God, that men may see that spirit,
which hath bewitched and entangled them from him,
with the ways and false appearances wherein it hath entangled them;
and may wait on the Lord (in truth of heart) for his light, guidance,
and power to deliver them; that so they may come into his holy land,
and within the limits of his holy city, out of all polluted lands and buildings,
where his holy nature dwelleth not,
and the pure dominion of his holy life and power is not felt;
that they may sing praise to him among his redeemed ones, for his precious redemption;
who is breaking the bonds of captivity,
and redeeming his out of all the lands and countries,
wherein they have been scattered in the cloudy and dark day;
glory in the highest to his name forevermore!

[.old-style]
=== Some Queries to the Professors of Christianity / To Provoke Them to Jealousy for their Good

Query 1. HAVE ye eat of the bread and
drank of the wine in the Father`'s kingdom,
which they that have received the kingdom, and are in the kingdom, eat and drink of?

Query 2. Have ye known the heavenly Jerusalem, and are ye come to it,
as the Christians were in the apostles`' days?
Heb. 12;22.

Query 3. Are ye in him that is true, and your churches and gatherings in God,
and in the name of his Son?
Is your being and dwelling in the eternal life?

Query 4. Have ye received the promise of the Father, even the excellent Spirit of the Son?

Query 5. Have ye the true faith?
Do the living waters spring out of your bowels, according as the Scriptures have said?
"`He that believeth on me,
out of his belly shall flow rivers of living water.`" John 7:38. and chap.
4:14.

Query 6. Doth God tabernacle in you?
is his dwelling among you?
doth he walk up and down in your spirits, and sup with you, and you with him?

Query 7. Are ye in the new covenant?
taught of God, so as you need no man to teach you?
and your sins so blotted out, according to the covenant,
as to hinder no good things from you?

These things were spoken of in the law and prophets, to be fulfilled, witnessed,
and enjoyed under the power and life of the gospel;
which is not a state of the names and foretelling of things, as under the law,
but of the presence and enjoyment of the things themselves;
and so far as ye fall short of them, ye shall fall short of the state of Christianity.

[.old-style]
=== Some Observations upon the Eternal Judgment / As it is Expressed by Christ, Matt. 25:31. to the End of the Chapter.

Observation.
1+++.+++ THE condition of Christ here in this world,
in many of his members in their several ages and generations.
He is hungry, thirsty, a stranger, naked, sick, and in prison; yea, indeed,
what is there of misery, shame, and reproach, which he is not exposed to;
or which they are not exposed to, who entertain him as their Lord and King,
and are faithful in their obedience and subjection to him?
ver. 35, 36, 43.

Observation.
2+++.+++ The notice Christ takes of what is done in this kind, or not done in this kind,
to any of his suffering members; which extends to all, even the very least.
"`Insomuch as ye have done it unto one of the least of these,
ye have done it unto me.`" ver. 40. "`Insomuch as ye
did it not to one of the least of these,
ye did it not to me.`" ver. 45.

Observation.
3+++.+++ The honorable esteem Christ hath of his poor suffering members,
with what eye of contempt soever the world looks upon them,
yet he looks upon them as his brethren.
ver. 40.

Observation.
4+++.+++ The different carriages of persons towards Christ,
in this his low condition in his members.
Some gave him meat, some gave him drink; some took him in, some clothed him,
some visited and came unto him; ver. 35, 36. others did none of these things unto him.
ver. 43.

Observation.
5+++.+++ The different judgment Christ passeth upon these,
according to their different carriages.
The one he pronounceth blessed of his Father,
judging them to the inheritance of a kingdom of eternal life.
ver. 34. 46. The other he pronounceth cursed,
and adjudgeth to everlasting punishment in the fire of his wrath.
ver. 41.--46.

Observation.
6+++.+++ The ground or reason why those, who did not minister to him, neglected him,
which was their ignorance of him.
They saw indeed, and knew several persons to be in such kind of conditions,
but they did not know that it was Christ which suffered in them;
this is implied in their answer to him.
ver. 44. "`When saw we thee ahungered, or athirst, or a stranger, or naked, or sick,
or in prison, and did not minister unto thee?`" ver. 45.

Observation.
7+++.+++ That it will not excuse men from the judgment,
their not knowing of Christ in his members;
but if they neglect and have not done this thing,
though they may plead ever so strongly that they did not know any such,
they will incur and must suffer the judgment.
The Jews cried up Moses and the prophets, which had been before,
and yet persecuted Christ and his apostles; and many now cry up the prophets,
and Christ`'s appearance in a body of flesh, with his death, resurrection, ascension,
etc., and also the apostles, both their words and practices; and yet persecute him,
and the same practices, in his present servants and members.
How will these possibly escape this judgment?

[.discourse-part]
Objection.
But they that did minister unto him, they knew not that it was he either, as ver. 37, 38, 39.
Therefore they doing of it ignorantly (as we may say),
it seemeth to want its due weight, and not to render them so worthy of the reward,
as if they had done it in a clear and distinct understanding.

[.discourse-part]
Answer.
They did not know it so as to put so great a value upon it as Christ here doth;
but they knew that they had done things of this kind,
and that they had done them on Christ`'s account.
But that Christ was so in those to whom they did them, as he now speaks;
and that he would set so high an esteem on it, that they were not aware of.
Was it thou thyself that wast naked, sick, in prison, etc.,
and didst take all this as done to thee?
This is wonderful to us,
that thou shouldst so set by what we poor worms did to thy suffering saints,
in thy name and fear.

[.discourse-part]
Question.
But why doth Christ make this the ground of the general and universal judgment?
Men have committed many other sins (some of which are in appearance far greater):
why doth Christ mention none of them, but fix the judgment only upon this?

[.discourse-part]
Answer.
Surely because this is more in his eye, and more hateful to him than them all.
This argues an evil nature and spirit, and the joining of the mind to the wicked one,
more than them all.
For it plainly shows,
that there is none of the love and nature of Christ in such persons;
for if there be of the love and nature of Christ in any person,
it will incline his heart towards those which are Christ`'s,
and especially in their suffering conditions.
He therefore that hath no sense of those that belong to Christ,
in their suffering conditions, showeth plainly,
that he hath none of Christ`'s nature in him,
and so is not at all found in that which Christ comes to save,
but in that which he comes to judge and destroy forever.

Now I have three questions more to propose,
which I desire that all men that read may judge of in that
which giveth the true sense and judgment of their weight.

1+++.+++ If this be the cause and ground of the eternal judgment,
whether it may not also be the ground of temporal judgments on persons and nations;
to wit, if there be such a thing to be found in them,
as neglecting to minister to Christ in his suffering members?

2+++.+++ If there be not only this to be found,
but also a causing of him in his members thus to suffer (a causing of their hunger,
thirst, nakedness, sickness, imprisonment, etc.),
whether this is not of very great force to draw down plagues, judgments,
and miseries upon a nation?

3+++.+++ If there have been such sins committed, God`'s anger provoked,
and his judgments drawn down, whether it be possible to stop them,
or there can be any reasonable hope of the diverting of them,
without a deep humbling before God,
confessing the thing in the sight of the world (as
it hath been done in the sight of the world),
and laying such a foundation for the future,
as the Lord and men may be satisfied and assured
that no such thing shall be done any more?
Was it not a shameful thing, that Jerusalem, the outward holy city (and chief,
if not only professing people of the world), should stone, cast out, persecute,
put to death, etc. the prophets and Christ of God,
and set up priests and prophets of their own?
And where, and by whom, are the witnesses and martyrs hunted and slain?
Is it not still in that which is called the Christian world?
Do not they strive (each sort) for their forms, persecuting the life and power,
and those which follow the Lamb therein, out of their forms,
from which his life and spirit calleth and gathereth?
Oh that the world were awakened!
Oh that this nation were awakened!
Have there not been judgments enough to awaken it?
Oh, do not dally! ye have God to deal with,
who hath brought his truth and people upon the stage;
who is arisen against the darkness (which hath long possessed the hearts of men,
and held his people in captivity under their corrupt wills and wisdom),
and to bind down sin and iniquity in men.
Oh! do not say, "`Let us break their bonds in sunder,
and cast away their cords from us;`" but rather let every
one be willing to be found by the pure light of God,
by that which is holy of God in him (from the king that sits upon the throne,
even to the very beggar on the dunghill);
that iniquity may be purged out of the hearts of men, and they become,
not a vainly professing nation, but indeed a holy nation to the Lord;
that peace and righteousness, love and mercy, yea,
sweet and tender bowels may dwell within it, and flow up and down in all its borders;
to the glory of God`'s truth, which is able to work this (were it but let in, received,
and subjected to in the minds of men),
and to the delight and joy of the hearts of all in the nation.

ISAAC PENINGTON.

Written in Aylesbury prison, the 29th of the Eighth month, 1666.
