[#sum-substance, short="The Sum or Substance of Our Religion"]
== Concerning the Sum or Substance Of our Religion / Who Are Called Quakers / And the Exercises and Travails of our Spirits Therein

THIS is the sum or substance of our religion; to wit, to feel and discern the two seeds:
the seed of enmity, the seed of love; the seed of the flesh, the seed of the Spirit;
the seed of Hagar, the seed of Sarah; the seed of the Egyptian womb,
the holy seed of Israel;
and to feel the judgments of God administered to the one of these,
till it be brought into bondage and death;
and the other raised up in the love and mercy of the Lord to live in us,
and our souls gathered into it, to live to God in it.

Now when the light of God`'s holy Spirit breaketh in upon man,
and his quickening virtue is felt; then life enters into that which was slain,
and there is a desire begotten in the heart to travel out of the Egyptian state,
into the good land; that the soul, which came from God, might return back again to him,
out of the sinful, wandering, miserable, lost estate, and might live and walk with him,
in the purity, virtue, and power of his own life and spirit.

But then the other birth strives for its life, and Pharaoh, the king of Egypt,
takes part with his Egyptians against Israel; and there is no help to the poor soul,
but as God pours out his judgments upon that hard nature and spirit in man,
which is of the birth of the flesh,
and receives the influences and strength of its father,
which harden it against the true seed.
And now what a condition is this poor soul in?
The light of God`'s Spirit giveth it the sense of its state,
and the quickenings of life make it sensible of its bondage.
There are also some desires and longings after deliverance;
but this doth but provoke the enemy; and the soul being yet in his territories,
and under his power, he dealeth the more hardly with it,
increasing its burdens and oppressions daily.
And oh, the outcries of the soul in this state! how is its spirit pained, anguished,
and vexed within it;
so that it could almost many times choose rather to lie still in Egypt,
than undergo the heavy burdens, oppressions, fears, and dangers,
that it daily meets with in this state!

Yet there is a secret hope springing up in the heart from the true seed,
which often encourageth it to trust him, and wait upon him who hath visited,
in his pure ministration of judgment.
For this is felt many times, as the soul is made truly sensible by the Lord,
that the judgment is not to the seed,--not to Israel; but to Pharaoh and his Egyptians:
and by every stroke of God`'s wrath upon them, the seed is eased,
and its deliverance working out.

And so at last when the judgment is finished in the land of Egypt,
the strength of Pharaoh and his Egyptians broken, their first-born slain,
out comes Israel, out of the dark land, out of the house of bondage,
to travel towards its resting place.
Then the paschal Lamb is known and fed on; yea, it is because of the blood of the lamb,
sprinkled upon the door-posts, that Israel is passed over and saved,
in the day of Egypt`'s visitation.
Oh! who can read truly, that hath not felt and been a living witness thereof?

But now, when the seed is come out of Egypt, there is not the end,
but rather the beginning of its travels.
Pharaoh and his Egyptians, with their horses and chariots,
may pursue again and even overtake;
and there may seem no way of escape or help to the soul, but only to stand still,
hope in the Lord, and wait to see his salvation.
Then shall the sea be divided, which stopped Israel`'s course,
and Pharaoh with his Egyptians (the enemies of the soul in this appearance
of dreadful oppressing power) be destroyed and seen no more.

Yet in the wilderness, in the passage through the entanglements to the holy land,
there are many straits, trials, and sore enemies to be met with,
who will strive by open force, and also with enchantments, to betray Israel; yea,
there is a part yet unbrought down, yet unwrought out,
at which they will be striving to enter the mind.
And as Israel forgets his God, walking out of his counsel,
hearkening to that which his ear should be shut against,
and so joining to the contrary seed; the plagues, the judgments, the indignation,
and woe will be felt by him, and many carcases may fall there.
So that there may be a great outcry in the heart, Who can stand before this holy Lord God?
Shall we be consuming with dying?
Yes, there is somewhat must be consumed with dying.
Yea, if a man came so far as to witness dominion and victory over his soul`'s enemies,
the evil seed brought into death in him,
and a possession and inheritance in the pure rest of life;
yet if that part be not kept in the death,
if there be not a praying and watching to the preserver
of Israel (in the pure fear and humility),
the enemy will be sowing to the flesh again;
he will be getting some of his corrupt seeds into the heart
again (if the soul do but sleep and become negligent),
and so corruption will take root again, and the contrary birth grow up again,
and the foxes break into the vineyard, and spoil the tender grapes.

So that this is our religion, to witness the two seeds,
with the power of the Lord bringing down the one, and bringing up the other;
and then to witness and experience daily the same power, keeping the one in death,
and the other in life, by the holy ministration of God`'s pure living covenant.
And so to know God in this covenant, (in this covenant which lives, gives life,
and keeps in life) and to walk with God, and worship and serve him therein,
even in his Son, in the light of his Son, in the life of his Son,
in the virtue and ability which flows from his Son, into our spirits;
this is our religion, which the Lord our God, in his tender mercy, hath bestowed upon us.
And indeed we find this to be a pure, living, and undefiled religion before God,
daily witnessing his acceptance of it in and through his Son,
whose name is here known and confessed, worshipped and honored,
according to the very heart of the Father.

This may be further illustrated, and perhaps made more manifest to some,
by a scripture or two.

"`The flesh lusteth against the spirit, and the spirit against the flesh;
and these are contrary one to the other,`" saith the apostle.
Gal. 5;17.

Here are the two seeds (the seed of the serpent,
the seed of the woman) whose striving and fight is in man, when God awakens the soul;
the one whereof hath a nature, a desire, or lust contrary to the other.
Now as the one of these prevails in any heart, so the other goes down.
As the one gains life and power, so the other is brought into death and captivity.
So that this is it every one is to wait for,
after they once come to the sensible knowledge and experience of these two,
to feel the flesh brought down, the lusts of it denied,
the judgments of the Lord administered to it; that so the other may come up to live,
thrive, and prevail in the soul,
and so the soul witness salvation and redemption under its shadow.
"`Thus Zion is redeemed with judgment,
and her converts with righteousness.`" Isaiah 1:27. What is Zion?
Is it not the holy hill of God, whereon his Son is set King to reign?
whereon the holy city is to be built, and God to be worshipped in spirit?
What condition is Zion in, when God visits her to redeem her?
Is she not laid waste, desolate, lying in the dust?
as Ps. 102:13-14. Well, how will God redeem her?
"`Zion shall be redeemed with judgment,
and her converts with righteousness.`" By bringing
judgment upon that which keeps her under,
upon her enemies, the contrary seed, God redeems her;
and by bringing forth righteousness (the righteous life and spirit
of his own Son) in those whose minds are turned to her,
whose faces are set Zionward; thus God redeems her converts.
Yes, yes; it is truly felt and witnessed;
the living righteousness of Christ revealed in the heart, and having power there,
sets free from all the unrighteousness which was there before.
And then, when the unrighteous one is cast out, and the righteous one revealed,
and the soul united to him, and receives virtue and power from him,
then he becomes a servant of righteousness, and doth not commit sin,
but doth righteousness; "`and he that doth righteousness is righteous,
even as he is righteous.`" 1 John 3:7. For how can it be otherwise,
when the righteous life is revealed and brought up into dominion in him?
How can the same righteous Spirit and life (revealed in the members,
as it was in the head) but live and act after the
same manner in the members as it did in the head?
(Oh that men were turned to that which would give them the certain knowledge
and sensible experience of this!) Now this is exceeding comfortable and
precious to them that are in the true travel towards it;
much more to them that enjoy it.

This is the sum of all,
even to know and experience what is to be brought down into death, and kept in death;
what to be brought up out of the grave, to live to God, and reign in his dominion;
and what to be kept in subjection and obedience to him who is to reign.
Now to experience it thus done in the heart; the flesh brought down,
the seed of life raised, and the soul subject to the pure heavenly power,
whose right it is to reign in the heart in and by the seed;
this is a blessed state indeed!
For here the work is done; here the throne of God is exalted,
and his King reigns in righteousness and peace, and all his enemies are under his feet;
and this son, this true Israelite, this redeemed one, may wear the white robe,
and serve God in righteousness and holiness, without fear of his enemies,
(keeping in and to the covenant,
which ministers life and power abundantly) all the days of his life.
For that was to be the outward state of the outward Israel;
keeping to God in the outward covenant;
and it is to be the inward state of the inward Israel,
keeping to God in the inward covenant, which is a pure covenant of life and peace,
of all inward and spiritual blessings and mercies in Christ,
wherewith the souls are blessed that are obedient unto God,
and walk humbly with him in this covenant.
And I beseech you to consider (O tender people! who are
grieved because of sin and corruption in your hearts,
and would fain witness victory and dominion over it,
in the name and strength of the Lord Jesus Christ),
whom did that prophecy of Zachariah (Luke 1:17,72,74,75) concern?
What was that holy covenant?
Who were to be so redeemed?
Who were the Israel that were to inherit this promise?
All the promises are yea and amen in Christ to the Israel of God.
Why should not the Israel of God hope to enjoy this?
Even so to be acquainted with God`'s Holy Spirit, and to wait upon him,
that they may witness it granted to them; that they,
being delivered out of the hands of their enemies, might serve him without fear,
in holiness and righteousness before him (whose eyes are piercing,
and can behold no iniquity) all the days of their lives.
Surely they who witness that promise (mentioned Isa. 35:8) fulfilled to them,
cannot fall short of this.
And truly the children of the new covenant can never come thoroughly to
live to God till they witness the inward circumcision of the heart,
so as to love the Lord with all the heart and soul. Duet. 30:6.
Now where it is so, the devil or lust can find no place of entrance;
and how then shall they be able to sow their seed, and bring forth sin?
Out of the evil heart proceeds all evil;
but out of that heart which is thoroughly circumcised, to love the Lord God wholly,
evil cannot proceed.
If lust be not conceived, it cannot bring forth sin;
and where the womb which conceived it is kept dry and barren, it cannot conceive again.
And is not this the promise of the gospel, that the womb which was once barren,
shall be very fruitful, and bear abundantly; but the other grow feeble,
and be able to bear no more?
Oh! that people had experience of God`'s power, and did believe therein!
What should stand in the way of it?
It was Israel`'s sin of old, when they looked at their enemies,
and saw their footing and strength in the land which
God had promised to Abraham`'s seed for an inheritance,
they could not believe that they could be overcome.
Oh! take heed of the same unbelief now.

[.centered]
=== Concerning Christ;

[.heading-continuation-blurb]
Coming to the Father by Him, receiving him, walking in him,
not in the oldness of the letter, but in the newness of the Spirit;
and concerning reading the Scriptures aright.

"`I am the way, the truth, and the life: no man cometh unto the Father but by me,`"
saith Christ. John 14:6.

MAN, in the corrupt, degenerate estate, is fallen from God,
and hath lost his image (the holy, heavenly image of the Father of Spirits);
is driven out from his presence, dwells in the land of darkness and confusion,
under the government of the prince of the power of the air, who rules in,
and hath power over, all the children of disobedience.

Now this should be man`'s work; even to return to the Father;
to come back out of the prodigal lost state, to the Father`'s house;
where there is sufficiency and fullness of true bread and
water of life to satisfy every hungry and thirsty soul.

The way whereby a man must come, the truth wherein he must be renewed,
the life wherein a man must be quickened, is Christ, the Son of the living God;
and he must know him as the Son of the living God, and feel him revealed in him,
and received by him, and so walk in him the way, in him the truth, in him the life,
if ever he come to the Father.
He must not rest in the description of things; but feel and know,
receive and walk in the thing, which by the Spirit of the Lord hath been often formerly,
and is still, described, in what words, and by what means, the Spirit pleaseth.
But to receive all the descriptions of him that were formerly given forth,
or all the descriptions that are now given forth, that will not do;
but the soul that will live by him, must receive him,
and feel the ingrafting into him the holy root, the living word of God`'s eternal power,
and must feel this word ingrafted into his heart,
so that there be a real becoming one in nature and spirit with him.
And then he is truly in the vine, in the olive-tree,
and partakes of the virtue and sap thereof; he abiding therein,
and walking in the spirit, life, and power thereof.

Now here a man walks not, nor cannot walk, in the oldness of the letter;
but in the newness of the Spirit only.
Paul, notwithstanding all his knowledge of the Scriptures,
walked but in the oldness of the letter, before Christ was revealed in him.
And those in the apostles`' days, who had got the form of godliness,
but turned from and denied the power, they walked but in the oldness of the letter.
Yea, the church of Sardis, for the most part, and the church of Laodicea,
who had received the right order and ordinances, and the true descriptions of things,
and thought they were full and rich, and wanted nothing,
they walked but according to the oldness of the letter,
and not in the newness and power of the Spirit of life.
But alas, how far are many, who pretend to Christ in this day,
from this state! who never came so far as to walk in the oldness of the letter,
from a true understanding thereof;
but have only learned and continued to walk in the oldness
of their own apprehensions and conceivings upon the letter.

Can these, in this state, possibly understand truth, or know the inward, spiritual,
precious appearances thereof, either in their own hearts, or others?
Surely no.
Why so?
Why this is the reason: because they measure the appearances of truth,
either in themselves or others,
by their own old apprehensions and conceivings upon scriptures concerning truth;
which are not the proper measure of it.
Now all such are yet in darkness, let them pretend what they will,
and grow ever so high in knowledge, exercises, and experiences after this manner;
and so the best, zealousest, and most knowing of them in this state,
are but blind leaders of the blind, and, thus going on,
shall most certainly fall into the ditch of perdition.
Oh that men could feel that which makes rightly sensible, and might lay it to heart!
For no man can confess Christ (how then can he receive him,
and walk in him?) but by the Holy Spirit.

And he that knoweth not the Spirit rightly, knoweth not Christ rightly;
and he that doth not know him rightly, doth not confess him rightly;
and none can know him rightly but by the revelation of the Father inwardly.
The mystery must be opened within, or there is no true knowing.
The mystery of deceit is discovered within,
and the mystery of life is discovered within also.
And though the heart of man, in the unregenerate estate, is deceitful above all things,
and desperately wicked, and no man of himself can search or know it;
yet this is not the estate of the true Israelites whom God hath cleansed,
and taught to deny themselves daily;
but they have boldness before that God who hath searched them,
and removed from them the iniquities which he found therein.
Yea, whoever witnesseth Christ revealed within,
shall find him revealed within for this very end,
to destroy the works of the devil there;
and he is a powerful Saviour of the soul from sin,
and a powerful destroyer of the works of the devil within.

Now concerning reading the scriptures, mind this; It is said of the Jews,
that when they read Moses (or in reading the Old
Testament) the veil was upon their heart:
which veil is done away in Christ.
2 Cor.
3;14,15. Oh! consider seriously, is the veil done away from thee?
Dost thou read the Scriptures with the unveiled eye?
Dost thou read in the anointing, in Christ`'s Spirit,
in the pure heavenly wisdom of the divine birth?
It was promised of old,
that God would take away the face of the covering cast over all people,
and the veil spread over all nations.
Dost thou witness the promise fulfilled to thee?
Dost thou know the difference between reading the Scriptures with the veil on thee,
and with the veil off?
Are the Scriptures opened and unlocked to thee by the key of David,
so that thou readest and understandest them in the
light and demonstration of God`'s Holy Spirit;
or is thy own understanding and will at work of itself, in searching into the Scriptures?
If the wrong birth, the wrong wisdom, the wrong understanding, be at work,
it can gather but that which will feed and strengthen itself;
and if thou beest not in Christ, and dost not read in Christ,
the veil is not taken away from thee, for the veil is only done away in him;
but thou readest and walkest in the oldness of thy apprehensions upon the letter,
and not in the newness of the Spirit: and so knowest neither the Scriptures,
nor the power of God, whatever thou professest to men, or dreamest concerning thyself.
For it is no other indeed; thy knowledge, thy apprehensions, thy faith, thy hope,
thy peace, thy joy (being out of the compass of the pure, living truth,
in which the substance, the virtue,
the kernel of all is comprised and comprehended forever) are but as so many dreams.

Oh that men that are any whit tender,
and have any sincere desires in them towards the Lord,
could read that one scripture (Ps. 43:3,40 sensibly
and experimentally! "`Oh send out thy light and thy truth;
let them lead me; let them bring me unto thy holy hill,
and to thy tabernacles.`" (What! did not David know
how to go to the hill and tabernacles of God,
without a particular sending forth of light and truth from God
to lead him thither?) Then may men go to the altar of God,
unto God their exceeding joy, and witness his hill and house their dwelling-place,
when God, by his light and truth, sent forth from him into them, leads them thither.

The Scriptures are words, whose chief end, drift, and service is,
to bring men to the Word from which the Scriptures came.
And when men are there, then they are in the life of the Scriptures,
and witness the fulfilling of the Scriptures,
even the executing the righteous judgments of God upon that spirit, mind,
and nature in them, which is contrary to his image;
and the fulfilling of the promises and sure mercies, which belong to Christ the seed,
and to them who are gathered into, and abide in, Christ the seed.
Here is the covenant, the new covenant.
That which is said, or those things which are said,
concerning the covenant in the Scriptures, are but descriptions of the new covenant;
but Christ within, the hope of glory, the Spirit within, the fear within,
the power of life within,
breaking down and reigning over the power of sin and death (so
that the Lord is served in the dominion and power of his own life,
in the righteousness and holiness before him, out of the fear of sin and death,
all the days of our lives; so that captivity can lead captive,
nor break the soul`'s peace no more; nay,
not so much as make afraid those that keep their habitation on God`'s holy mountain);
here is the covenant indeed, the strength and virtue whereof is witnessed in the soul,
as the soul feels the power of life revealed in it,
and is made subject by the power of Christ, who reigns in righteousness, love, mercy,
and peace, in the hearts of those whom he redeems out of the earthly nature and spirit,
up to the mind and Spirit of his Father.
And here the psalms, hymns, and spiritual songs, the pure songs (the song of Moses,
the song of the Lamb) are sung to the Father of spirits, to the Redeemer of Israel;
which never were sung, nor can be sung, in any part of Babylon;
but all those songs are but dreams of the night,
which will be turned into howling and bitter lamentation,
when the whore (that which hath whored from God, and is not in the wisdom of his Spirit,
whatever she may pretend) is stripped,
and the nakedness of her profession and religion (with all her duties and ordinances,
as she calls them) made manifest.

[.centered]
=== Concerning the Gospel Ministration

IF the gospel be not a ministration of words or letter, but of Spirit, life,
and power;
and if it was the intent of God that men should not
stick in words or testimonies concerning the thing,
but come to the thing itself, and live in the Son`'s life and power,
and feel the Son living in them, then they are greatly mistaken,
who think to gather a rule to themselves out of the
testimonies and declarations of things in the Scriptures,
and do not wait upon the Lord to receive his Spirit itself to become their rule, guide,
and way.
For these are all one; the truth is the way;
the truth which lives and abides in the heart (where
it is received and entertained) is the way;
the rule is the guide: for God is One.
There are many names, but the thing is One.
The life, the power, the wisdom in the Father, Son, and Spirit, is all One: yea,
they themselves are One, perfectly One, not at all divided or separated;
but where the Father is, the Son is; and where the Son is, the Spirit is;
and where the Spirit is, there is both the Father and the Son,
who tabernacle in man in the day of the gospel.
And where these are, there that is which is to be preferred before all words,
which was afore them, and is in nature, Spirit, and glory above them.
He that hath the Son, hath life, even the life eternal, which the words testify of.
He that hath the Son hath him which is true;
and he that is in the Son is in him that is true; and abiding there, cannot be deceived;
but he that is not there is deceived,
let him apprehend and gather out of the Scriptures what he can.
Oh, how is God glorified,
and how is the redemption and real salvation of the
soul witnessed in this despised dispensation of truth,
which God hath held forth in these latter days!
Blessed be the name of the Lord,
who hath hid this pure dispensation of life from the eye
of the prudent worldly-wise part in every man,
revealing it only to the babish simplicity which is of his Son, and which lives in him,
and by him.

[.old-style]
=== Concerning Christ`'s Being Manifested Without, / And His Being Also Manifested Within, / And How Both Are Owned by Them that Know the Truth.

It is objected against us, who are called _Quakers,_
that we deny Christ (and look not to be saved by him) as he was manifested without us,
but look only to be saved by a Christ in us.
To which this is in my heart to answer such as singly desire satisfaction therein.

We do indeed expect to be saved (yea, and not only so, but do already,
in our several measures,
witness salvation) by the revelation and operation of the life of Christ within us;
yet not without relation to what he did without us.
For all that he did in that body of flesh was of the Father,
and had its place and service in the will, and according to the counsel, of the Father.
But the knowledge and belief of that, since the days of the apostles,
have been very much held in the unrighteousness,
and in the separation from the inward work of the power and life of Christ in the heart;
which, as so held, cannot save any.
But whoever feels the light and life of Christ revealed in him,
and comes into union with God there-through, he feels the work of regeneration,
of sanctification, of justification, of life, and redemption;
and so comes to reap benefit inwardly,
and to partake of the blessed fruits of all that Christ did outwardly.
Yea, he that is thus one with Christ in the Spirit, cannot exclude himself,
nor is excluded by God, from the advantage of any thing, nor everything,
Christ did in that body of flesh.

This indeed is the main thing, to witness salvation wrought out in the heart;
to witness the eternal power and arm of the Lord laying hold on the soul to save it;
and not only laying hold on it to save it,
but to witness the working out and the effecting of the salvation,
as really in the substance, as Israel of old did in the shadow.
For as they witnessed Moses and Joshua outwardly, so the true Israelite,
the inward Israelite, the spiritual Israelite,
is to witness that which is the substance of these,
even the Son of God revealed inwardly.
Now they were not saved outwardly by a bare outward believing
that Moses and Joshua were sent of God to save them;
but by following them in faith and obedience to what from God they required.
So to the inward Israel Christ is given for a leader and commander,
who appears to the distressed embondaged soul in Egypt, brings out of Egypt,
and so leads on towards the good land, and into it.
Now as the soul follows, as the soul believes in his appearances,
and obeys his voice in the holy, pure covenant of life;
so he works out the redemption thereof.
But as unbelief and disobedience get up,
and the heart is hardened at any time against his voice and counsel,
and the ear open to the temptations of the enemy, the redemption thereby goes backward,
and the distress and captivity return again.
This is witnessed, known, and experienced by every true traveller towards Zion;
therefore the main thing requisite is to abide in the sense of the Redeemer`'s power,
as also in waiting for his motions and appearances,
and in the faith and obedience thereof.
For sin gathers strength, and is brought forth,
by letting in and giving way to the motions thereof:
and so also holiness and righteousness is brought forth and getteth ground in the mind,
by hearkening and giving up to the stirrings and movings of God`'s Holy Spirit.
Therefore it is of great necessity to every true traveller
to come to a right understanding and distinguishing of these;
and that the heart may be kept with all diligence,
because out of it are the issues both of life and death.
And most happy is he who knows the issues of death stopped,
and the issues of life opened, and whose spirit is naked and open before the Lord,
for life to spring up in him, and issue forth through him at its pleasure.
Oh! it is a precious state to witness captivity led captive by life,
and the power of life reigning over it.
And truly there is as real deliverance witnessed inwardly,
by those that wait upon the Lord, and are faithful to the leadings of his Holy Spirit,
as ever there was by the Jews outwardly, in their faithful following Moses and Joshua:
and Christ is as truly a healer of his people,
in this ministration of life to them by his Holy Spirit,
as ever he was a healer of persons outwardly in the days of the flesh.
That, with the other miracles which he wrought then,
was but a shadow of what he would work and perform
inwardly in the day of his Spirit and holy power:
and shall he, or can he (to those that faithfully wait upon him) fall short in the one,
of what he shadowed out in the other?
Nay, surely; it was the intent of his heart, and he will not fail to perform it,
to save to the very utmost all that come to God by him, and abide in his holy, pure,
righteous, living covenant.
Here is the skill of Christianity, to abide in him;
and here the living virtue and pure power is felt, which overcometh all,
but nothing can overcome it: but victory, dominion, glory, majesty,
and power is sung unto him, who is King of saints, who reigns in righteousness,
and who establisheth peace and truth within his borders.

[.old-style]
=== A Few Words Concerning the Principle of Truth; / What it is, How it May Be Discerned, / and How it May be Purchased and Possessed

Question.
1+++.+++ WHAT is the principle of truth?

Answer.
It is the light, which reproves and makes sin manifest.
"`Whatsoever doth make manifest is light.`" Wherefore he saith, "`Awake thou that sleepest,
arise from the dead,`" etc. Eph. 5:13-14.
There is no other way of awaking out of sleep,
and arising from the dead, but by the light which makes sin manifest.
And oh, how precious is that light!

Question.
2+++.+++ How may the principle of truth be discerned?

Answer.
By its piercing, quickening nature,
which discovereth itself in its appearances and operations.
For it appears and works, not like man`'s reason,
or like motions of his mind which he takes into his understanding part;
but it appears and works livingly, powerfully, and effectually in the heart.

Man`'s reason is corrupt, dark, impure, since the fall;
and in the hand and under the power of the wicked one.
Its nature is to hide and cover sin, not to discover it.
Now the light of the law, which discovers sin, ariseth not hence.
Who can bring the clean, pure light of the law out of the unclean, impure reason of man?
The light indeed may shine in the darkness; but it is no part of it,
but of another nature and descent.
It is from God`'s Spirit, and given to man in his love unto him,
to lead him out of his dark ways and spirit into the pure Spirit and way of holiness.
For the light which discovers sin, is all holy and pure,
like the fountain from whence it comes.
Now a man that is acquainted both with reason and with this light,
he can distinguish the nature and operations of both.
For there is a great difference between truth held in the reasoning part,
and truth held in its own principle.
It is very powerful in the one; it effecteth little in the other.
In the pure quickenings of life this distinction is perceived, and also held.
Therefore our advice is to all men, to retire from all mortality,
that they may come to feel the spring of life in themselves,
and something springing therefrom into them to quicken them,
and to wait to have their understandings opened and kept open by that;
that so they may receive, retain,
and not again lose the capacity of understanding the things of God`'s kingdom.

Question.
3+++.+++ How may this principle, seed, or pearl, be purchased and possessed?

Answer.
By dying to a man`'s own wisdom and will.
There is not another way.
For the light is wholly contrary to man, as he stands in the alienation from God.
It crosseth his spirit, his thoughts, his desires, his knowledge, his reason,
his understanding; even all that is of himself.
He must therefore consult with none of these, but prefer the little,
pure demonstration of the light of Christ`'s Spirit above all these,
and stand in the parting with and loss of them all forever.
Oh! this is an hard saying, who can bear it?
Surely none but those that are taught and learn of the Father,
can thus come to give up to and follow the light of the Son.

"`The law of the Lord is perfect;
converting (or restoring) the soul.`" Ps. 19:7. What law was this or what law is this?
Was it the law of works in the hand of Moses?
Or is it the law of faith in the hand of Christ?
Doth not Christ enlighten every man that cometh into the world?
Would not God have all men to be saved?
And doth he not give to all a proportion of the true light whereby they may be saved?
And is it not the property of this light to convert to God?
Can any man receive this, and be united to this, and it not change his nature?
So that he must needs have a new nature, and from that new nature do that naturally,
which the Jews, by all their endeavors without this, could never do.

Can any thing convert fallen man to God, but Christ?
Hath any thing power to convert to God, but his pure law of life?
Can Christ and his light be separated?
Can any man receive his light and be united thereto, and not receive him?
Oh that men`'s hearts and understandings were opened by the Spirit and power of the Lord!
For this is a direct riddle to all men, who have not God`'s heifer to plow with,
to understand it by.
And so for want of a true understanding, it is despised and rejected among the builders;
but with us it is elect and precious, chosen of God,
and precious in the eye of our souls.

Now this doth not exclude or make void any thing
that Christ did in his body of flesh here on earth,
or that he doth in heaven for his; but this brings unto a right,
and into a possession and enjoyment of his purchase.
For all that are in the darkness, and walk in the darkness,
have nothing to do with Christ in truth and reality, whatever they may profess,
and what hopes so ever they may feed themselves with;
but all that are in any measure of his light, and walk therein, they are so far of him,
and have a right to, and share in, all that he did in and from the same light and Spirit.

And this I dare positively hold forth as a standing truth,
which hath been sealed unto me by constant experience;
That no man can fall in with and obey the light wherewith he is enlightened,
but he must deny himself, and take up a cross to his own wisdom and will;
which cross is the cross of Christ,
which is the power of God to the salvation of the soul.
And he that takes it up daily, and waits upon the Lord therein,
shall witness the power of the Lord Jesus Christ to the redemption of his soul; yea,
then he shall be able in true understanding to say; This is light indeed, life indeed,
power indeed.
That powerful arm which hath saved me from sin, and breaks the snares, devices,
and strength of the enemy before me (delivering me daily when none else can,
and when my own strength and wisdom is as nothing), I cannot but call Christ,
the living power and wisdom of God revealed in me,
who will not give his glory to another.
For he is the Lord God of pure power and life forevermore;
and beside him there is no such Saviour.
Yea, blessed be the name of the Lord forever,
the days of mourning after salvation are over with many,
and the days of reaping and enjoying salvation are come,
which shall endure with the Israel of God forevermore, amen.

ISAAC PENINGTON
