== Letters of Isaac Penington

[.letter-heading]
To Thomas Ellwood

[.salutation]
Dear Thomas,

Great hath been the Lord`'s goodness to thee, in calling thee out of that path of vanity,
and death, wherein thou wast running toward destruction; to give thee a living name,
and an inheritance of life, among his people:
which certainly will be the end of thy faith in Him, and obedience to Him.
And let it not be a light thing in thine eyes that He now
accounteth thee worthy to suffer among his choice lambs,
that He might make thy crown weightier, and thine inheritance the fuller.
O that that eye and heart may be kept open in thee,
which knoweth the value of these things! and that
thou mayst be kept close to the feeling of the life,
that thou mayst be fresh in thy spirit in the midst of thy sufferings,
and mayst reap the benefit of them: finding that pared off thereby,
which hindereth the bubblings of the everlasting springs,
and maketh unfit for the breaking forth and enjoyment of the pure power!
This is the brief salutation of my dear love to thee,
which desireth thy strength and settlement in the power; and the utter weakening of thee,
as to thyself.
My love is to thee, with dear Thomas Goodyare, and the rest of the imprisoned Friends.

I remain thine in the Truth, to which the Lord my God preserve me single and faithful.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From Aylesbury Jail, 14th of 12th month, 1660

[.letter-heading]
To King Charles II

[.salutation]
O King,

The Lord God of heaven and earth is mighty,
who hath often and greatly shaken this nation already: and this I have observed,
that the seeming settlements, which hitherto have been, since the Lord began to shake,
have been but preparative to a further shaking and dissettling.
O! happy wert thou, if thou couldst wait for, and receive, such a guidance from God,
as that thy government might be so pure, peaceable, and righteous,
as it might need no further shaking by his hand.
God sometimes raiseth man from a low estate, and exalteth him; but if he forget the Lord,
and his heart be lifted up, He is able to bring him down again.
O! fear the Lord in the days of thy prosperity, and let thy heart be abased before Him,
and sensible of the need of his preservation.
Indeed, it is a hard matter to govern these kingdoms aright, as the state now stands.
Thou mayst easily err and dash upon the rocks.
O that the pure eye were open in thee:
whereby thou mightest see that as thou didst not gain these kingdoms by policy or strength;
so neither canst thou retain them by those means,
but only by the good pleasure of Him who hath all the earth at his dispose!
I beseech thee, in that tender love I bear to thee,
take heed of going about to plant what the Lord hath plucked up;
or of endeavouring to pluck up what the Lord hath planted.
If thou lookest with man`'s eye, thou canst not see what God is doing in the world;
and so mayst easily run a course contrary to his will, and eternal counsel:
and O how hazardous must this needs be to thee!
The eternal peace of thy soul with God forever, and thy prosperity,
depend upon thy knowing the counsel of the Lord, and upon thy obedience thereunto.
Oh! retire from this world`'s baits, snares, temptations, allurements, and vanities;
which draw out and defile the mind; and retreat inward,
that the Lord may teach thee his fear,
and preserve thee from those lusts and desires of the fleshly mind, which,
being hearkened to and followed, are very dangerous to the soul,
and may prove perilous outwardly also.
What shall my love say to thee?
O that the Lord would speak to thee in spirit, and give thee an ear to hear,
that thou mightest be happy now and forever!
Often have my bowels rolled over thee exceedingly, even in the day of thy adversity,
and since thy prosperity.
O that thou couldest remember God daily, and forget this world!
Remember the years of thy affliction;
and make use of the present day with an humble heart, and with a broken spirit.
O! do nothing to provoke the Lord against thee; for surely his eye is upon thee,
and his heart pondereth all thy ways.
And bow before him for his counsel, that thou mayest not arise against thy Maker,
as the foregoing powers have done: for if He rise up in battle against thee,
thou wilt no more be able to stand before Him than they were.
Nay, the stronger thou art outwardly settled,
the greater will the glory of his name be in overturning thee.
O that thou mightest rule under God, and for God! and not with that wisdom,
and with those self-ends, and interests, which are not of Him,
and cannot but be against Him.
I cannot but desire thy good; yea,
the very breathings of my heart to the Lord have been often for thee:
and upon that account singly do I write thus to thee; beseeching the Lord,
if it be his pleasure, that when that work which is necessary to be done is finished,
thine eyes may be opened to see the way of righteous government in the true light.

From one who mourns over the misery of mankind,
longing for the redemption of those that go astray, and a true lover of thy soul.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury prison, where I am visiting some of my dear Friends in God`'s eternal truth,
17th 7th mo.
1661

[.postscript]
====

Postscript. Let thy government be like unto God`'s: even a yoke to the unjust,
but liberty to the just.
O, when shall the cry of the innocent cease, throughout all thy borders?
Restore unto the Lord his dominion over men`'s consciences,
while it is in the power of thine hand to do it--O! seek after love, meekness,
righteousness, tenderness, towards all thy subjects: which hath God`'s blessing with it,
and is the way to win all their hearts towards thee.
And do not harden multitudes of them against thee,
by unnecessary yokes over their consciences: which they that do not eye God in all,
and in lowliness of spirit bow before Him,
may be apt to kick against and strive to throw off.--And I beseech thee,
take heed of this world`'s pleasures and vanities; which steal away the heart from God,
and make it thick and gross, that it cannot hear his voice or know his counsel.
I am satisfied with what the Lord shall do; but it is the earnest desire of my heart,
that thou mightest be spared in the day of God`'s visitation,
which is coming upon this nation.--This is my desire for thee,
that thy heart might be brought into, and kept in,
that frame which God loves and delights to be present with, and to instruct, and +++[+++that]
all such things might be eschewed and avoided by thee,
which may prove dangerous to thy soul forever, and to thy government here.
For though thou beest a great king here, yet,
if thou wilt obtain the blessing and inheritance of eternal life,
and escape eternal misery and destruction, thou must take up the cross to thy lusts,
and walk in the same path of mortification and self-denial, which God,
who is no respecter of persons, hath chalked out to the meanest of thy subjects.
Hear, O king, turn towards the Lord, bow before Him in soul and spirit,
in thy whole conversation.
It is a greater honour to be a subject to Him, than to reign over men.

====

[.letter-heading]
To +++_______+++ +++_______+++

[.salutation]
Dear Friend,

It pleased the Lord to refresh me by thy letter.
O how precious and pleasant is it to feel life stirring in God`'s tender lambs,
and their hearts purely breathing towards their Father!
O that their joy may be full;
and that they might sit safe under the shadow of their beloved,
bringing forth the fruits of holiness and righteousness to him,
in the pure stillness and rest, forever.
Shall not the clouds fly away?
Shall not the blackness of darkness and troubles fix and abide in its own centre;
and all sorrow, sighing, and fear of the soul`'s enemy,
vanish from the hearts of all the mourners after, and waiters for, the Lord.

O God, hear the cries of thy poor inwardly distressed,
and also outwardly afflicted and persecuted, heritage.
Arise against that which stands in the way of their life and peace,
and of thy service and glory through them;
and let thy powerful presence (which doth great things)
be felt in the hearts and assemblings of thy people together;
that they may be purified and preserved thereby to dwell in thy courts,
to be satisfied with thee, to rejoice in thy goodness,
and be far from the fear of evil and transgression;
which thou knowest how sorely it hath afflicted them,
and bowed down their souls before thee.

O my Father, shall thy lambs live?
Wilt thou be with them, a tender Father and a mighty God and Saviour?
Wilt thou encourage them concerning all their fears,
and carry on thy work of redemption mightily in their hearts?
Then shall the glory of thy name be sung,
and our God alone exalted in the midst of us forever.
And we will walk in humility and fear before thee,
and in tender bowels one towards another all our days;
and nothing but life shall reign in us, and appear amongst us,
when thou hast perfectly destroyed sin and death out of the midst of us.

Dear friend, my heart is with you in your assemblings;
and sometimes the Lord gives me cries for you, that he would appear amongst you,
as a refresher of your souls and guider of your paths.
And O that he would put forth his mighty hand to slay the enmity
and earthly nature (with all the reasonings thereof) in every heart;
that the pure seed might spring and prosper in you all,
to the praise of that fountain from whose fulness it is,
and by whose blessing alone it grows up and prospers.

I am thy friend in dearness and truth of affection,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From Aylesbury Jail, 4th of 1st month, 1665

[.letter-heading]
To a Parent

[.salutation]
Dear Friend,

I have not much freedom to write at present, being retired in spirit,
and mourning to my God, for the powerful bringing forth of his pure life,
yet more perfectly, both in myself and others;
yet the spirit of thy letter doth so strongly draw, that I cannot be wholly silent.

This, therefore, in the uprightness, fear, and tenderness of my heart, I say to thee.

There is a pure principle of life in the heart, from whence all good springs.
This thou art to mind in thyself; and this, thou art to wait on the Lord,
to be taught and enabled by him to reach to, in thy children;
that thou mayst be an instrument in his hand, to bring them into that fear of him,
which is acceptable to him, and will be profitable to them.
Mind, therefore, its leadings in thy heart,
and wait to be acquainted with its voice there.
And, when thy children ask thee any questions of this nature,--What God is;
where he dwells; or whether he sees them in the dark--do not reject it;
but wait to feel somewhat of God raised in thee, which is able to judge,
whether the question be put forth in sensibility or in vanity;
and which can give thee an advantage of stirring the good, and reaching to that,
which is to be raised both in young and old, to live to the praise of him who raiseth it.
And take heed of a judgment after the flesh; for so thou mayst judge us,
our principles and practices, and approve or disapprove, etc.
But wait to feel that raised in thee,
which judges righteous judgment in every particular; and wait the time of its judgment,
and be still and silent, further than manifestly thou knowest that it, and not thou,
judgeth.

And, as to thy children, daily feel the need of instruction from the Almighty,
to govern and direct them, and wait daily to receive it from him;
and what thou receivest, give forth in fear,
and wait for his carrying it home and working it upon their hearts.
For he is a Father, and hath tenderness,
and gives true wisdom to every condition of his people, that wait upon him;
so as he may be known to be all daily, and they able to be nothing without him.

Thou expectest, perhaps, from me, an outward rule; but I have no rule,
but the inward life, and that not in the way of outward knowledge,
but daily made known as my Father pleaseth; nor can I direct thee to any other,
but to wait, that life may be revealed in thee daily,
according to thy daily need in every particular.
And this I say to thee, in the love of my heart, wait, O wait,
for the true discerning which is given to the true seed (in the
raising and dominion of which in thee thou wilt feel it,
and not otherwise), that a wrong thing judge not in thee,
in the reasoning and fairly appearing wisdom; for then thou wilt judge and be led amiss,
and, through error of judgment, stray aside, and wander from the desire of thy heart.

But breathe unto the Lord, that thy heart may be single, thy judgment set straight,
thou thyself by his principle of life in thee, and thy children guided to,
and brought up in, the sense of the same principle.
As for praying, they will not need to be taught that outwardly; but,
if a true sense be kindled in them, though ever so young,
from that sense will arise breathings to him that begat it, suitable to their state;
which will cause growth and increase of that sense and life in them.

Thus, in the plainness of my heart, have I answered thee,
according to the drawings and freedom which I found there, which I dare not exceed;
who am thy unfeigned Friend, though outwardly unknown,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
20th of Third Month, 1665

[.letter-heading]
To Bridget Atley

[.salutation]
Dear Friend,

I know thy soul desires to live; and my soul desireth that thou mightst live.
Oh! why art thou so backward to hearken to the voice which is nigh thee, wherein is life?
why dost thou reason?
why dost thou consult?
why dost thou expect?
why dost thou hope?
why dost thou believe against thy own soul?

The snares of the subtle one will entangle forever, unless thou wait for, hearken to,
and obey the voice of the living God,
who leads the single-hearted and obedient out of them.
Is there any way of life but one?
Is not the Lord leading his children in that way?
Must not all that come after, follow in the foot-steps of those that go before?
Is there any Saviour, but the seed of life and the Father of it?
Is it not the same in thee as in others?
Hath it not the same voice?
Oh that thou hadst the same ear and the same heart, that thou mightst hear, receive,
and live!
They wait aright; dost thou wait so?
They hope aright; dost thou hope so?
If not, what will thy waiting and expecting come to?
In that, which hath sometimes inclined thy heart, there is truth,
there were the beginnings of salvation;
but in that which draws thee out to expect some great matters,
and dries up thy present sense, and hinders thy present subjection, therein is deceit,
and the destruction of thy soul.
Therefore, if thou desire and love the salvation thereof, Oh hasten,
hasten out of it! wait for the reproofs of wisdom;
and what it manifests to be of the earthly and worldly nature in thee (the words, ways,
thoughts, customs thereof), hasten out of.
Oh, turn thy back upon the world with speed,
and turn thy face towards the heavenly wisdom and
light eternal! which will be springing up in thee,
if thou turn thy back upon the world, and wait for it.

And do not look for such great matters to begin with, but be content to be a child,
and let the Father proportion out daily to thee what light, what power, what exercises,
what straits, what fears, what troubles he sees fit for thee;
and do thou bow before him continually, in humility of heart,
who hath the disposal of thee, whether to life or death forever.
Ah! that wisdom which would be choosing must be confounded, and the low,
humble thing raised, which submits and cries to the Father in every condition.
And in waiting to feel this, and in joining to this, thou mayst meet with life;
but death, destruction, and separation from God is the portion of the other forever!
Oh, that thou mayst be separated from it, and joined to the seed and birth of God; that,
in it, thy soul may spring up to know, serve, and worship the Lord,
and to wait daily to be formed by him, until thou become perfectly like him.
But thou must join in with the beginnings of life,
and be exercised with the day of small things, before thou meet with the great things,
wherein is the clearness and satisfaction of the soul.
The rest is at noon-day; but the travels begin at the breakings of day,
wherein are but glimmerings, or little light,
wherein the discovery of good and evil is not so manifest and certain;
yet there must the traveller begin and travel;
and in his faithful travels (in much fear and trembling, lest he should err),
the light will break in upon him more and more.

This have I written in tenderness to thee,
that thou mightest not miss of the path of the living,
which is appointed of the Father to lead, and alone can lead, the soul to life.
Oh! that thou mightest be enlightened and quickened by the Lord to walk therein,
and mightest be thankful for, and content with, what he gives thee, and walk therein,
from the evil to the good, from the earthly to the heavenly nature daily,
and mightest not despise the cross or the shame of the seed.
For I know there is a wisdom in thee, which will despise and turn from it,
until the Lord batter and crucify it;
and I can hardly put up a more proper request for thee,
than that the Lord would draw out his sword against it,
and deeply perplex and confound it in thee.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
1665

[.letter-heading]
To One Who Sent a Paper of Richard Baxter`'s

[.salutation]
Dear Friend,

Whom I often remember with love and meltings of heart; desiring of God,
that thou mayst enjoy, in this world,
what of his presence and pure life he judgeth fit for thee, and that thy soul may,
after this life, sit down in rest and peace with him forever.

I received from thee a paper of Richard Baxter`'s, sent, I believe, in love; and,
in love, am I pressed to return unto thee my sense thereof.
It seems to me very useful and weighty as far as it goes; but, indeed,
there is a great defect in it,
in not directing sinners to that principle of life and power,
wherein and whereby they may do that which he exhorteth them to do.
For how can they come to a true sensibility or repentance,
or join in covenant with God through Christ,
until they know and receive somewhat from God, wherein it may be done?
O my dear friend! that he, and thou, and all who in any measure turn from this world,
and do indeed desire life eternal, might know the instruction of life,
and feel that from God wherein he is known, loved, and joined with in covenant; that so,
there might be a pure beginning, a pure growth and going on unto perfection,
and not notions concerning things set up in the earthly understanding,
which easily putrify and defile; but pure life, felt and enjoyed in the heart,
which is undefiled, and never saw nor shall see corruption.
I have not freedom to write many words; but my love breathes for thee,
and my life desires fellowship with thee,
(if it may seem good unto my God,) in that which is pure of him,
and will remain so forever.

And whatever men may say or think of me, I have no other religion now,
than I had from the beginning;
only a clearer leading into and guidance by that principle of life, in and through which,
it pleased the Lord then to quicken me.
And this is it, which I have daily experience of in my heart;
that it is no less than the light of the everlasting day,
in which the renewed man is to walk, and no less than the life of the Son,
(whom God gave a ransom for sinners,) which can quicken man so to do;
and none but Christ, none but Christ, by his life revealed in the soul,
and blood shed there to wash it, can save the poor sinner from sin, wrath, and misery;
and my hope is not in what I have done, do, or can do;
but in what he hath done without me, and also doth in me.

This is the account of my love unto thee,
drawn forth at this time by the outward expression of thine in sending that paper,
who remain, and, from my first acquaintance, have ever been, a Friend and lover of thee.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Peter`'s Chalfonte, 19th of Sixth Month, 1665

[.letter-heading]
To a Friend In London; Supposed to Be Written On Occasion of the Plague

[.salutation]
Ah!
Friend,

Dreadful is the Lord: it is now known and felt, beyond what can be spoken.
Doth thy heart fear before him?
art thou willing to be subject to him?
dost thou desire strength from him, to trust thyself and thy family with him?
Oh that thou mayst be helped daily to cry unto him, that he may have mercy upon thee,
who is tender-hearted and able to preserve, when his arrows fly round about!

Retire, deeply retire, and wait to feel his life;
that thy soul may be gathered out of the reasonings and thoughts of thy mind,
into that which stays from them, and fixes beneath them;
where the Lord is known and worshipped, in that which is of himself,
of his own begetting, of his own forming, of his own preserving,
of his own shutting and opening at his pleasure.
And, living in the sense and pure fear of the Lord (not
meddling to judge others or justify thyself,
but waiting for his appearance in thee, who is the justifier and justification),
thou wilt be enabled by the Lord, in his seasons,
to bring thy children and family into the same sense;
that thou and they together may enjoy the same preservation from him,
so far as he sees meet, whose will is not to be limited, but to be subjected to.

And if thy heart be right before the Lord,
and thy soul awakened and preserved in his fear,
thou wilt find somewhat to travel out of, and somewhat to travel into,
and the Lord drawing and leading thee.
And this stroke, which is so dreadful to others, nor altogether without dread to thee,
will prove of great advantage in thy behalf;
in drawing thee more into a sense and acquaintance of the infinite One,
and in drawing thee from thy earthly thoughts and knowledge,
which will not now stand thee in stead.

[.signed-section-closing]
Thy Friend,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
8th of Seventh Month, 1665

[.letter-heading]
To Elizabeth Walmsley

[.salutation]
Dear Friend,

My heart was exceedingly melted within me at the
reading of thy precious and tender lines;
yea, indeed, I was quite overcome, and was fain several times to break off,
the freshness and strength of life in them did so flow in upon me;
and I said again and again in my heart, It is the very voice of my Father`'s child,
whose sound did deeply reach to and refresh my very soul.
And this my heart saith, Blessed be my God, for his tender mercies to thee, in visiting,
leading, and preserving thee to this day,
and for teaching his seed thus to speak in thee.
Oh! let his praise live and abound in thy breast forever!
And in the flowings and streamings of this life,
remember me at the throne of my Father`'s mercy, by which alone I live,
and have hope before him.

May the mercies, blessing, and pure presence of my God fill thy soul,
and rest upon thee forever!
Amen!
Amen!

Thus prayeth for thee thy unfeigned Friend,
and dear lover of the pure seed of life in thee,

[.signed-section-signature]
I+++.+++ P.

[.postscript]
====

Mind my dear love to thy sister, whose inward welfare and prosperity I desire,
even that she may be one with thee in the seed and life of God.

====

[.signed-section-context-close]
Aylesbury Jail, 19th of Eighth Month, 1665

[.letter-heading]
To My Friends at Horton and Thereabouts

There hath been a cloudy and dark day,
wherein God`'s church and building hath been laid waste,
and his holy city (according to his decree and purpose) trodden under foot by the Gentiles;
all which time, his church hath been as a desolate widow, mourning in the wilderness.
Yet, during this season, God hath not left his people;
but there have been breathings and stirrings of life in and from the precious seed;
in which breathings of life, they have seen somewhat of the beauty of the built state,
and have had true desires and longings after it: but, in the midst of these desires,
the enemy hath struck in upon their spirits,
and put them upon pressing more forward towards it, than they have been truly led.
So reading in the Scriptures of a church state and church orders, etc.,
they thought it was their duty to set on building;
and so have thrust themselves into these things,
in which they have not been accepted of the Lord; though,
in their breathings and true desires, they were accepted.
And what hath been the issue of these buildings?
Ah! the pure seed hath been buried in them, they have been as a grave to it;
and their own imaginations, and wrought-out knowledge, and way of worship,
have been of high esteem.

O Lord my God! raise again, I beseech thee, the pure life,
and those pure breathings which have been drowned, lost, and buried in these buildings!

Now, dear Friends, the Lord alone built his church at the first.
The Lord also laid the buildings waste, and carried his living temple,
out of the shell of it, into a wilderness.
And the Lord alone can lead his church out of the wilderness (leaning upon her Beloved),
into her built state again.
Ah! dear Friends, all must be scattered, all must be scattered, all the gatherings,
all the buildings, which are not of the Lord, that his gathering, his building,
may be known and exalted in the earth:
so that I would not have you hold up any thing in this day of the Lord (it is so indeed),
against the light and power of the Lord.
The Lord is able, and will maintain his building,
however weak and low of esteem it be in the eye of man;
but man shall not be able to maintain his buildings,
however high and strong in his own eye.
Yea, every high tower and every fenced city shall fall before the dread of His presence,
who hath now appeared among his poor, desolate people,
and gathered them within the verge of his power: blessed be his holy name forever!

And since my spirit is at this time thus unexpectedly opened, in love and in life,
towards you, I shall mention one or two great snares,
which I see professors entangled in, that you may wait on the Lord,
to escape the evil and danger of them.
One is this, they look too much at outward time and outward things,
and their expectations are too much that way.
Oh let it not be so with you! but wait for the inward day,
wherein the things of God are wrought in the heart.
And take heed to your steps, thoughts, and ways; for the Lord,
who hath long tenderly visited, is now laying stumbling-blocks; and not only the world,
but even professors also, shall be hardened, snared, fall, and be taken;
and this word shall be fulfilled, even among them,
"`He taketh the wise in their own craftiness.`" But woe unto him that hath stumbled
at the living appearance of God`'s precious truth in this our day,
and in his wisdom hath been exalted above that which he should have fallen down before!
Oh that none of you (whom I have dearly loved, and still love,
and whom I have truly sought in the Lord,
and still seek) ever prove sad examples and spectacles of what I now write in a living,
feeling sense!
Oh that that which hath mourned and is oppressed among you might live,
and rise up in the power of life, over that which hath grieved and oppresseth it! for,
of a truth, I feel among you a wisdom and knowledge, which is not of the seed,
but oppresseth it.
Oh, what plainness of speech doth the Lord give me towards you!
Indeed, I am melted in concern for you; and,
in the strength of that love which searches into your bosoms, desire,
that the abominable thing among you might be discovered and purged out,
and that which is indeed of God might spring up, live, and flourish among you.

A second thing, wherein professors grievously mistake, is,
about praying in the name of Christ; in which name, he that asketh receiveth;
and out of which, there is no right asking of the Father.
They think that praying in the name of Christ consists in using some outward words; as,
"`Do this for thy Son`'s sake,`" or "`We beg of thee in Christ`'s name;`" whereas,
that in the heart which knoweth not the Father may use such words;
and that which is taught of the Father to pray, and prayeth in the Son,
may not be led to use those words.
The name, wherein the asking and acceptance is, is living;
and he that prayeth in the motion of the Spirit,
and in the power and virtue of the son`'s life, he prayeth in the name,
and his voice is owned of the Father; and not the other,
who hath learned in his own will, time,
and spirit to use those words relative to the Son.

Another thing, wherein professors exceedingly err and mistake, is,
about the applying of Christ`'s righteousness, which is only rightly done in the Spirit,
where the application hath its true virtue.
But man`'s misapplication hath no virtue; for, notwithstanding that, his sins remain;
and so the comfort, hope, and joy in his heart,
that his sins are pardoned is only a pleasing dream,
which will deceive him when he awakes, and finds his sins not blotted out by God,
but only in his own apprehension.

Ah Friends, that ye might travel into truth,
and meet with the unerring substance of things, that ye might live,
and not die! and then ye will see how man hath erred, and errs, yea, even the man in you;
and that the seed only, and they that are born of the seed, know the living truth,
and walk in the living path, where there is no error, no deceit,
but a perfect preservation out of them.
There, it is my desire to meet and embrace you, in the dear bowels of love,
where we may unite, and know one another, in the spiritual birth and life, inseparably,
forever; if we daily mourn after, and faithfully wait upon,
the true guide and leader thereunto.

I remain your imprisoned Friend, according to the wisdom of God,
and in his pure content and fear;
though the wisdom of man might easily have avoided these bonds.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 22d of Eighth Month, 1665

[.letter-heading]
To a Friend (an extract)

The Lord is tender of me, and merciful to me.
Though, indeed, I have felt much weakness both inwardly and outwardly,
yet my strength doth not forsake me; but the mercies of the Lord are renewed to me,
'`morning by morning.`'
I could almost sing to his glorious name, seeing (in the pure, powerful,
overcoming life) the death of all that troubles Israel.
O the gates of hell,
ye shall not prevail against the least lamb of my Father`'s preserving,
glory be to his mercy, to his love, to his power, to his wisdom, to his goodness,
forevermore!

[.signed-section-context-close]
+++[+++From Aylesbury Jail, according to Bevan, who dates it about 3rd month, 1666]

[.letter-heading]
To Friends of Truth in and about the Two Chalfonts

[.salutation]
Dear Friends:

I am separated, as to bodily presence, from you; but I cannot forget you,
because ye are written on my heart, and I cannot but desire your peace and welfare,
as of my own soul.

And this is my present cry for you.
Oh that ye might feel the breath of life, that life which at first quickened you,
and which still quickeneth, being felt; and that breath of life has power over death;
and being felt by you, will bow down death in you,
and ye will feel the seed lifting up its head over that which oppresseth it.
Why should the royal birth be a captive in any of you?
Why should any of you travail, and not bring forth?
Why should sin have dominion in any of you,
and not rather grace reign in its life and power in you all?
Oh that ye may receive quickenings!
Oh that ye may receive help!
Oh that ye may be led into the true subjection, which brings forth the true dominion!
Indeed, I cry for my own soul, and I cry for yours also,
that in one virtue and power of life, we may be knit together,
and serve the Lord our God in perfect unity of spirit.

O Father, blow upon flesh in us all, dry it up at the roots,
let all the births thereof die in us, and its womb become barren;
that no more fruit may be brought unto death and unrighteousness;
but let thy pure principle live in us, and the womb, that hath been too long barren,
abound with seed unto thee; that we may be, to thy praise,
a vineyard of thy own planting, watering, and dressing, bringing forth pure holy fruits,
pleasant to thy taste; that thou mayest never repent of the especial love, favour,
and mercy thou hast shown to us, in gathering us out of the world,
and from amidst the many professions;
but mayest follow us with the same love and delight, to do us good forever;
and we may be found walking worthy of thy tender visits,
and the great mercy thou has shown us, and of the great things we yet hope for from thee.

My Friends, what shall I say unto you?
Oh! the Lord keep you living and sensible, and let your walking and converse be with him,
both in private and in your assemblings; be serious in your spirits,
that ye may feel the weight of his seed springing up in you, and resting upon you,
to poise your hearts towards him.
And let the earthly thoughts, desires, and concerns, which eat like a canker,
be kept out by the power of that life, which is yours,
as ye abide in covenant with him that hath gathered you,
by his pure light shining in you.
Oh that ye may all dwell there! and not draw back into the earthly nature,
where the enemy lies lurking to entangle and catch your minds, and bring you to a loss.

Feel my bowels of love and tender care of you in the quickening life of God;
and the Lord God watch over you for good, to perfect his work in you,
and draw your hearts nearer and nearer to himself,
until they be quite swallowed up of him; that ye may at last find your hearts fitted for,
and welcomed into, the bosom of your Beloved,
and there may sit down in the rest and joy of his fulness forevermore;
which is the blessed end of the Lord`'s love to you,
and all the faithful travails which have been for you.

Your Friend and brother in the Truth.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From my place of confinement in Aylesbury

[.signed-section-context-close]
20th of Fourth Month, 1666

[.postscript]
====

Even when ye were sitting together, waiting on the Lord (some of you, I doubt not),
did these things spring up in my heart towards you;
and if ye taste any sweetness or refreshment in them, bow to the Fountain,
and be sensible of his praise springing in the midst of you.

====

[.letter-heading]
To Elizabeth Walmsley, of Giles Chalfont

[.salutation]
Dear Friend,

The thoughts of thee are pleasant to me; indeed,
I am melted with the sense of the Lord`'s love to thee, as to my own soul.

What were we, that the Lord should stretch forth his arm to us, and gather us?
And what are we, that the Lord should daily remember us,
in the issuings-forth of his lovingkindness and mercies?
Oh his pity, his compassion! (must I forever say) that my soul yet lives,
and hath hope before him!
And canst not thou also say the same?
Oh, my friend! we feel mercy and salvation from the Lord.
Oh, that he might have pure praise and service from his own in us! and yet,
that will be little thanks to us, but rather a new mercy received from him.
But all is his own, and of his own do we give him; and that, only when he quickens,
helps, and enables us to give.
Dear friend, my desire for thee is,
that the power and blessings of life may descend upon thee,
and that thou mayst feel thy God near, and thy heart still ready to let him in,
and shut against all that is of a contrary nature to his;
that thou mayst know that death passing upon thee, and perfected in thee,
which prepares for, and lets into, the fulness of his pure, unspotted life.

Thou mayst commend my dear love to thy sister, and to all Friends,
as thou hast opportunity, who breathe after the Lord,
and desire in uprightness of heart to walk with him.

I am thy Friend, in the affection which is of the Truth.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury, 20th of Fourth Month, 1666

[.letter-heading]
To Elizabeth Walmsley, of Giles Chalfont

[.salutation]
Dear Friend,

The thoughts of thee are pleasant to me; indeed,
I am melted with the sense of the Lord`'s love to thee, as to my own soul.

What were we, that the Lord should stretch forth his arm to us, and gather us?
And what are we, that the Lord should daily remember us,
in the issuings-forth of his lovingkindness and mercies?
Oh his pity, his compassion! (must I forever say) that my soul yet lives,
and hath hope before him!
And canst not thou also say the same?
Oh, my friend! we feel mercy and salvation from the Lord.
Oh, that he might have pure praise and service from his own in us! and yet,
that will be little thanks to us, but rather a new mercy received from him.
But all is his own, and of his own do we give him; and that, only when he quickens,
helps, and enables us to give.
Dear friend, my desire for thee is,
that the power and blessings of life may descend upon thee,
and that thou mayst feel thy God near, and thy heart still ready to let him in,
and shut against all that is of a contrary nature to his;
that thou mayst know that death passing upon thee, and perfected in thee,
which prepares for, and lets into, the fulness of his pure, unspotted life.

Thou mayst commend my dear love to thy sister, and to all Friends,
as thou hast opportunity, who breathe after the Lord,
and desire in uprightness of heart to walk with him.

I am thy Friend, in the affection which is of the Truth.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury, 20th of Fourth Month, 1666

[.letter-heading]
To +++_______+++ +++_______+++

[.salutation]
Friend,

Thy advantage in thy travels is great over what it hath been;
the Lord having given thee a better sight both of thy enemies,
and of that wherein his strength against them is revealed.

Now what remains but that thou hope in him, and breathe unto him, and hang upon him;
that his virtue may flow into thee, and the mountains and difficulties may pass away,
before the presence of the Seed, who is revealed in thee?
Look down no more, look out no more; but dwell with thy beloved,
in the tent that he hath pitched for thee.
Let him do what he will, let him appear how he will, wait on him in the daily exercise;
stand still in the faith, and see him working out thy salvation,
and scattering the bones of them that have besieged thee.
Think not hardly of him by no means; question not his carrying on of his work.
He knows what yet he hath to do,
and what stratagem the enemy yet hath to surprise and entangle thee.
Oh feel his arm stretched out for thee! and be not so much discouraged,
in the sight of what is yet to be done, as comforted in his good-will towards thee.
`'Tis true, he hath chastened thee with rods and sore afflictions;
but did he ever take away his lovingkindness from thee?
or did his faithfulness ever fail in the sorest, blackest, thickest, darkest,
night that ever befell thee?
And breathe to him, for the carrying on of his work;
that thou mayst feel his presence and life, getting dominion over death daily in thee,
more and more.
And wait to feel strength of life, that thy growth may be pure,
and the holy seed may have dominion and be all in thee.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
8th of the Eighth Month, 1666

[.postscript]
====

Postscript.--The enemy will be laying snares,
and forging subtle devices to darken and bow thee down,
which (thou, not being hasty to believe, join with, and let in as true,
but waiting on the Lord in singleness, fear, and humility),
his light will spring up in thee, and help thee to discern.
And oh! how sweet will it be for thee, who hast so often been ensnared,
to escape the gins and nets of the fowler, and to dwell in the rest and peace,
which thy soul hath tasted of, and which is the proper place of thy habitation.

Indeed, the Lord`'s thoughts have not been towards thee,
as thou hast apprehended all along.
His anger was towards the enemy, towards the oppressor, not towards thee.
Nor doth he judge and smite the mind, after that manner that the enemy doth accuse;
but according to his own nature, sweetness, and tender love.
And his judgments and smitings have other effects,
than the serpent`'s accusings and piercings; for they do not drive from him,
but they melt, and tender and prepare the heart for union with him.
Oh! keep close to the measure of life,
wherein thou mayst discern and distinguish these things;
and take heed of letting in one bowing-down thought (how manifest or demonstrative soever),
but look up to him who hath freely loved, and hath abounded in mercy towards thee;
that in the faith, patience, stillness, and meekness of his seed,
thou mayst be found always waiting upon him, in the several exercises,
wherewith he shall daily see good to exercise thee;
till he bring forth his seed in dominion in thee,
and thereby give thee thy desired and expected end.

====

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
9th of the Eighth Month, 1666

[.letter-heading]
To +++_______+++ +++_______+++

[.salutation]
Friend,

The vessel, or created nature, poisoned by sin and death, nothing can redeem,
but the life and power of God revealed in the vessel.
This life, this peace, this power, this righteousness, this salvation,
is the Lord Jesus Christ.
And he that feels any thing of this, feels somewhat of Christ; and being joined to,
and partaking of it, partakes somewhat of his redemption:
for it is not by an outward knowledge, but by an inward virtue, and spiritual life,
received from Christ, and held in Christ, that those who are saved, are saved.
This is the thing of value with me, for which I have been made willing to part with all,
and into this purchased possession am I daily travelling; and in my travels,
the Father of life and tender mercy pleaseth to help me.

Now, to have thee gathered into this light, this life, this power, which is of Christ,
and in which he is, and appears, is the desire of my soul,
in uprightness of heart before the Lord, for thee: and if he please,
I am willing to be instrumental in his hand, towards the bringing forth of this in thee.
It is not my desire to bring forth new notions in thee;
but rather that thou mightst wait on the Lord, for him to bring up his living,
powerful truth in thee,
wherein the knowledge of the new and living way is alone revealed.

I am a worm, I am poor, I am nothing; less than nothing, as in myself;
weaker than I can express, or thou imagine; yet, in the midst of all this, the life,
power, righteousness, and presence of Christ is my refreshment, peace, joy and crown:
and that, to which I invite thee, is substance, everlasting substance,
which thou shalt know and acknowledge in spirit to be so,
as that is created and raised in thee, which can see and acknowledge it in truth.
Oh! wait on the Lord, fear before him, pray for his fear,
in the upright breathings (which are not of thy spirit`'s forming,
but of his pure begetting);
that thou mayst be led by him out of that wisdom which entangles, into that innocency,
simplicity, and precious childishness, in which the Father appears to the soul,
to break the bonds and snares of iniquity;
for hereby the evil spirit not only involveth in iniquity, but also begets a belief,
as if there could be no perfect redemption therefrom,
till the time of redemption be over.

Thy truly loving Friend, desiring the right guidance and happiness of thy soul,
by the Lord Jesus Christ, the alone skilful Shepherd and Guide, even as of my own soul.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Prison, 20th of Tenth Month, 1666

[.letter-heading]
To the Friends in Truth in and about the Two Chalfonts

As a father watcheth over his children, so do I wait,
and desire to feel the Lord watching over my soul continually.
And in his love, care, wise and tender counsel, is my safety, life, and peace;
and I never yet repented either waiting for him or hearkening to him.
But if I have hearkened at any time to any thing else, and mistook his voice,
and entertained the enemy`'s deceitful appearance, instead of his pure truth,
which it is very easy to do,
that grievous mistake hath proved matter of loss and sorrow to my soul.

Now, O my Friends, that ye might know and hear the voice of the Preserver.
So shall ye be preserved, and kept from the voice of the stranger,
which draweth aside from the pure principle of life, and the true, feeling sense.
There is that near you which watcheth to betray.
O the God of my life, joy, peace, and hope, watch over your souls,
and deliver you from the advantages which at any time it hath against any of you.
The seed which God hath sown in you is pure and precious.
Oh that it may be found living in you, and ye abiding in it!
Oh that no other seed may, at any time, usurp authority over it;
but that ye may know the authority and pure truth which is of God, and therein stand,
in the pure dominion, over all that is against him.
For, in the principle of life, which ye have known and received in measure, is dominion;
and ye therein preserved are in the dominion over the impure and deceitful one;
and that judging in you hath power to judge all impurity and deceivableness,
as the light thereof pleaseth to make it manifest to you;
but out of that ye will easily become a prey, and set up darkness for light,
and account light darkness; and then a wrong wisdom, confidence,
and conceitedness will get up in you,
and lead you far out of the way and spirit of truth.
Oh, my dear Friends, that that may be kept down in you which is forward to judge,
to approve or disapprove; and the weighty judgment of the seed be waited for.
And oh do not judge, do not judge, before the light of the day shine in you,
and give forth the judgment; but stand and walk in fear and humility,
and tenderness of spirit, and silence of flesh,
that the Lord be not provoked against any of you,
to give you up to a wrong sense and judgment, to the hurt of your souls.
And mind your own states, and the feeling of life in your own vessels;
which will keep you pure, precious, and chaste in the eye of the Lord.
And oh do not meddle with talking about others, which eats out the inward life,
and may exalt your spirits out of your place, and above your proper growth;
be as the weaned child, simple, naked, meek, humble, tender; easily led by,
and subjected to, the Father; so will ye grow in that which is of God,
and be preserved out of that which hunteth after the pure life, to betray and destroy it.
I have an interest in you; my cries are to the Lord for you,
and I exceedingly thirst after your preservation and growth in that which is pure;
and in that breathing,
longing spirit towards you was it in my heart at this time to write unto you.

The Lord God of my mercies, hope, and life, watch over you for good,
and keep your hearts in the pure and single watch;
that the enemy (by any subtle device of his) break not in upon you; nor ye,
by any temptation, be allured or drawn from the Lord; but may know the pure, eternal,
everlasting habitation, and may dwell and abide therein, to the joy of your own souls,
and the rejoicings of the hearts of all that have
travailed for you in the Spirit of the Lord.

From your brother and companion in the faith, patience, and afflictions of the seed,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Prison, 25th of Eleventh Month, 1666

[.postscript]
====

Postscript.--Thus, feel after that which hath gathered you to the Lord; and then also, in that,
ye will feel the life, freshness, and glory in the Lord,
of those who have been made instrumental to gather you,
and are still serviceable in his hand and leadings, to build you up;
and then that which is ready to hearken to and receive prejudices, will be kept down,
and the pure life will live over it,
which he that feels has joy and peace and rest in God.

And Friends, you that are weak, bless God for the strong;
you that have need of a pillar to lean upon bless God,
that hath provided pillars in his house; and, in fear and the guidance of his Spirit,
make use of these pillars; who are faithful, and have ability from God,
in his power and glorious presence with them, to help to sustain his building,
even as they had ability from the Lord to gather unto him.
He that despiseth him that is sent, despiseth Him that sent him;
and he that undervalues any gift, office, or work,
that God hath bestowed upon any person, despiseth the wisdom and disposal of the Giver.
Are all fathers?
Have all overcome the enemy?
Are all grown up in the life?
Are all stars in the firmament of God`'s power?
Hath God made all equal?
Are there not different states, different degrees, different growths, different places,
etc.? Then if God hath made a difference, and given degrees of life, and gifts different,
according to his pleasure;
what wisdom and spirit is that which doth not acknowledge this, but would make all equal?
O my Friends! fear before the Lord; honor the Lord in his appearances,
and in the differences which he hath made among the children of men,
and among his people.
He gave prophets of old, and the rest of the people were not equal with them.
He gave evangelists, apostles, pastors, teachers, etc.,
and the other members of the churches were not equal with them.
He hath given fathers and elders now, and the babes and young men are not equal with them.
Thus it is, in truth, from the Lord; and that which is of God in you,
will so acknowledge it.

Therefore watch, every one, to feel and know his own place and service in the body,
and to be sensible of the gifts, places, and services of others;
that the Lord may be honored in all, and every one owned and honored in the Lord,
and no otherwise.

====

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
26th of the Eleventh Month, 1666

[.letter-heading]
To M. E.

[.salutation]
Dear M. E.,

I found true unity with thy letter,
and a tender desire springing in my heart to the Lord for thee,
that as he hath in mercy quickened and gathered thee to himself,
out of the nature and spirit of this world, so he would please,
through the same tender mercy,
to preserve thee in that which gives the sense of his goodness,
and enables to walk worthy thereof.

My dear and tender love to thy sister.
O fear the Lord, and watch over one another in love, faithfulness,
and meekness of spirit; and be not of a distrustful spirit,
but trust your father in every trial, temptation, condition, or strait.

[.signed-section-closing]
Thy friend in the truth, and for the truth`'s sake,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
27th of 11th Month, 1666

[.letter-heading]
To the Single, Upright-hearted, and Faithful Friends of Truth, in and about the Two CHalfonts

[.salutation]
Dear Friends,

Have ye in any measure drunk in the sense of what the Lord hath done for you?
and have ye felt meltings of spirit, and bowings before him,
with praises to his name therefor?
Indeed, my request is to the Lord for you,
that he would please to keep you truly sensible of what he already is to you,
and of what he hath already done for you; that he would also,
of his tender mercy and great goodness, visit you yet further, increase life in you,
cause faith to abound, give you to dwell in his power, and always abide in his seed,
and feel that to be your hope, peace, joy, life, and strength continually;
that ye may more and more give thanks unto him, as ye feel his pure life arising in you,
and death and the grave swallowed up thereby.

Ah! my friends, can we ever forget the lost and miserable estate,
wherein the mercy of the Lord and his power from on high visited us?
Oh, the blackness of that day, the misery, the deep distress of that day,
which some of your souls felt!
Did ye not know what it was to want God,
and to lie open to the furious assaults of the enemy; when ye felt no strength,
nor knew whither to retire, to keep out any hurt, any temptation,
any vain thought and imagination,
or to give you any grounded hope in the goodness and mercy of the Lord?
How did ye mourn?
how did ye cry out and pine away in your iniquities
day and night! and knew not which way to look,
nor what to wait for!
Are there not among you, who have known this state,
and felt somewhat of that which I now relate?
Sure I am, there are upon the earth, who can witness it to the full,
whose mouths and hearts are now filled with a sense of the Lord`'s goodness,
and of his great salvation, and with deep and high praises to his name.

But, my dear friends, is there any of you (I know to whom I speak, even to the sensible,
to the diligent, to the faithful among you),
who cannot in truth witness as in God`'s presence,
concerning the arm and power of his salvation, which ye have often felt?
insomuch that ye can sing that song,
"`He hath raised up a horn of salvation for us in the house of his servant David;
as he spake by the mouth of his holy prophets.`" Do
ye not know the house of his servant David,
with the horn of salvation in it,
and that horn raised up to you for your defence and comfort?
Yea, do ye not daily feel the Lord ministering out salvation to you from it?
Are not your enemies daily overcome by the faith, which he hath given you in his power?
May I not say to you, where is the strength of the tempter?
Have ye not felt the seed of the woman to bruise the head of the serpent?
so that, in the fear of the Lord, and in the strength, virtue,
and dominion of his life manifested in you, ye can say,
though as yet somewhat tremblingly, Where are those temptations, those lusts,
vain thoughts, and imaginations, which once I was overcome by and overrun with?
Surely, I may speak thus; for I know assuredly, that the power of the Lord God,
as it is lifted up in any of you, scatters these, and gives you dominion over them.
For the life and its power are given as bulwark and
weapon of war against iniquity and its power;
and, where it is received, it opposeth, warreth, striveth, until it overcome.

And, this is that which gives the victory and overcoming; to wit, faith in the seed.
The seed felt, the soul joined to it, faith in it and from it given to the soul.
Then it becomes the Leader, the mighty undertaker for the soul,
and overcomes its snares and enemies for it; and, when it hath overcome them,
they are overcome indeed.
And then the soul lies down in peace, dwells in peace, feeds on the living nourishment,
in the green pastures of life, in peace.
Then Jerusalem, the building or life in the heart, becomes a quiet habitation,
where God and the soul dwell sweetly together;
and there is nothing that hath power in it to disturb, annoy, or make afraid.
Why so?
Because the Lord God of power is present there, stretcheth out his wings there,
is a pillar of cloud by day, and a pillar of fire by night there!
He hath raised up his glorious life in that heart, whereof he is very choice;
and he hath also spread a defence over his glory,
with which the soul is so encompassed and defended,
that it feels the walls of this city to be salvation, and its gates praise.

O my soul, travel on!
O dear Friends! do ye also travel on, into the fulness of the glory of this state.
There is no other thing to be desired and waited for.
This is your portion, both here in this world, and forever.
Therefore wait in the seed of this life; wait to feel yet a further gathering into it,
and a growing up in it; and give yourselves up to it,
that it may overspread and cover you.
And the Lord God of life daily open it, and manifest it more and more in you and to you;
that ye may be more found in him,
and yet more acceptable and pleasing in the eyes of your God;
and may sing praises unto him, not only at the foot of the hill,
in some true proportion and measure of his life, but in the very heights of Zion,
even in the fulness of the measure of your stature in Christ;
which ye are all diligently to press after, till ye arrive at.
And then there is no more to be done, but to spread abroad into, and drink in of,
and live in, the full pleasure and safety of life forever!
Then may ye eat freely of the tree of life, which is in the midst of the paradise of God,
and draw water, with joy, out of the wells of salvation!

Therefore feel, oh! feel, in spirit, the mark of the high calling of God in Christ Jesus;
and be daily looking up to that, which quickens to God,
and keeps fresh and lively in him; that none of you grow slothful, drowsy, or negligent,
and so, unfaithful in relation to the great talent which God hath put into your hands;
and so the Lord be provoked against you,
and suffer the enemy to tempt and prevail upon you;
that a veil come over your hearts again, and the air thicken,
and the earthly nature cover the seed; and he, that hath power in that earth,
and over that air, captivate, oppress, entangle, and lead you back from God again.
Oh! cry to the Lord to keep the eye open, and the heart single,
and the soul in the true sense and feeling; that the heavenly voice,
which drew you out of the earth, may be daily heard further instructing you,
and gathering you more and more up into him, who is your life.
So ye that fear the Lord, and love his name,
and have tasted of his goodness and powerful salvation, oh hate evil!
All that his light hath made manifest, and drawn you from,
oh take heed of ever dallying with again!
Oh never hearken to the tempter! but pray to the Father, that ye may discern his baits,
and at no time consult or reason with him; but still wait, in everything,
to feel the motion, guidance, quickening, and sweet, pure,
heavenly leading of the spirit of your Father!

Hath the Lord spoken peace to you, peace which passeth man`'s understanding,
and only flows from him?
hath he given you any proportion of this precious peace?
Oh! may he watch over you, and preserve you in that wisdom,
in those heavenly instructions, in that heavenly life, divine power,
and holy conversation, wherein ye met with that peace,
and wherein alone ye can enjoy and possess it! and keep you out of all manner of sin,
lust, and foolishness of the fleshly mind and spirit; for the peace is not there.
That is the fruit of the enemy to your peace, and it hath of his nature in it;
it always breaks your peace, and sows distance, difference, and division,
between the Giver and Maker of your peace and you.
Do ye not always (ye that are in the true sense,
and have received the holy understanding) feel it thus, and know it to be thus?
it is an eternal truth, and the eternal eye, wherever it is opened,
witnesseth and sealeth to it.
Therefore this little thing, this light of God in you,
to which ye were at first directed and turned,
which discovers all the darkness of the enemy, and all his deceits and devices,
and keeps the minds of those that are stayed by it,--in this wait,
to this let your minds be still turned, and in it still abide;
and the power and glory of eternal life will daily, more and more, appear in you, yea,
flow and break in upon you; to the filling of your vessels with its virtue,
and the causing of your hearts to abound with joy before the Lord,
and with thanksgivings to him.

May the God of tender mercies and everlasting compassions cause
the bowels of his love to be daily yearning towards you;
that you may be nursed up with the living food,
and that that which would overturn and destroy his work may be opposed;
that ye may feel it daily go on, yea, mightily preserved and carried on by him,
even till it be finished, and the top stone laid; and your souls,
in the true and full sense of life, cry, Grace, grace, to Him that laid the foundation,
raised up, defended, and carried on the building, and now, at length, hath perfected it.
And thus, whatsoever ye have hitherto witnessed in measure,
ye shall then witness in fulness;
and see that all the promises of God are of a precious nature,
and are "`yea and amen`" from God to the seed.

May the life, presence, and power of the Lord be with you in this seed;
in your breathings after it, in your joinings to it,
in your abidings and waitings upon him in it;
and the Lord God give you to breathe after it, give you to join to it,
give you to abide always, and wait upon him in it, and never to hearken to,
and go out after, a contrary spirit and wisdom; but keep you in the simplicity,
lowliness, humility, and tender spirit which is in Christ Jesus,
to the praise of his own name,
and preservation and joy of your hearts before him forever, amen!

Written in the tender bowels and motion of the pure life,
from the place of my confinement in Aylesbury.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
1st of Third Month, 1667

[.letter-heading]
To Friends in Amersham

[.salutation]
Friends,

Our life is love, and peace, and tenderness; and bearing one with another,
and forgiving one another, and not laying accusations one against another;
but praying one for another, and helping one another up with a tender hand,
if there has been any slip or fall; and waiting till the Lord gives sense and repentance,
if sense and repentance in any be wanting.
Oh! wait to feel this spirit, and to be guided to walk in this spirit,
that ye may enjoy the Lord in sweetness, and walk sweetly, meekly, tenderly, peaceably,
and lovingly one with another.
And then, ye will be a praise to the Lord; and any thing that is, or hath been,
or may be, amiss, ye will come over in the true dominion, even in the Lamb`'s dominion;
and that which is contrary shall be trampled upon, as life rises and rules in you.
So watch your hearts and ways; and watch one over another,
in that which is gentle and tender, and knows it can neither preserve itself,
nor help another out of the snare; but the Lord must be waited upon,
to do this in and for us all.
So mind Truth, the service, enjoyment, and possession of it in your hearts;
and so to walk, as ye may bring no disgrace upon it,
but may be a good savor in the places where ye live, the meek, innocent, tender,
righteous life reigning in you, governing over you, and shining through you,
in the eyes of all with whom ye converse.

Your Friend in the Truth, and a desirer of your welfare and prosperity therein.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury, 4th of Third Month, 1667

[.salutation]
For My Dear Children J.J. and M.P.

[.salutation]
My Dear Children,

Two things I especially desire in reference to your learning;--one is,
that ye may learn to know and hearken to the voice of God`'s witness in you.
There is somewhat in you, which will teach you how to do well, and how to avoid the evil,
if your minds be turned to it.
And the same thing will witness to you, when ye do well,--and against you,
when ye do evil.
Now to learn to know this, to hear this, to fear this, to obey this,
that is the chief piece of learning that I desire to find you in.
And your master or any one of the family that turns you to the witness,
reminds you of the witness, reproves you for not hearkening to or obeying the witness,
O! love them, and bless God for them in that respect: and remember this,
that he that hearkens to reproof is wise, but he that hates or slights it is brutish.
That is the dark spirit, which would please itself in its dark ways,
and therefore loves not the light which makes them manifest and reproves them:
and that spirit is the brutish spirit, which hates the reproof of the light,
and would continue its vain foolish ways and delights,
which the light testifies against;--that spirit therefore debaseth man.
Therefore mind the witness which discovers these things to you,
and leads you out of them, as ye hearken to it, and come to know, fear,
and love the Lord God, by his instruction and testimony.
The way of youth is vain, and foolish, and defiles the mind: O! my children,
wait for the cleansing,--watch for that which cleanseth the foolish way of children,
which is that which discovers and witnesses against your foolishness and vain tempers,
and the temptations of your minds, and leads out of them.
Learn to bear the yoke in your tender years.
There is a vain mind in you--there is somewhat which
would be feeding and pleasing that vain mind;
and there is somewhat near you, appointed by God to yoke it down.
O! give not scope to vanity, it will be an occasion of woe and misery to you hereafter.
But the yoke which keeps under the vain mind, O! take that yoke upon you;
and then ye shall become not only my children, but the disciples of Christ,
and children of the Most High.
This is the first thing,
which I mainly and chiefly desire you should apply yourselves to learn.

The next thing is,
(which will also flow from the first,)--that ye learn
how to behave yourselves as good children,
both in the family and to persons abroad, in a meek, modest, humble, gentle, loving,
tender, respectful way,--avoiding all rude, rough, bold,
unbeseeming carriage towards all; honouring your mother and me,
as God teaches and requires; dearly cleaving to one another in the natural relation,
which is of God, wherein ye are loved, +++[+++having]
even a great proportion of natural affection and
kindness one to another.------So to the servants,
carry yourselves very lovingly, sweetly, meekly, gently;
that none may have any cause of complaint against you,
but that all may see your lowliness, and be drawn to love you.
And to strangers, carry yourselves warily, respectfully, in a sober, submissive,
humble manner of demeanour; not disputing and talking,
which becomes not your age and place; but watching what ye may observe of good in them,
and what ye may learn of those that are good, and how ye may avoid any such evil,
as ye observe in any that are evil.
Thus your time will be spent in profit,--and ye will
feel the blessing of God and of your parents,
and be kept out of those evils, which your age and natural tempers are subject to,
and which other children, who are not careful nor watchful, are commonly entangled in.
Mind these things, my children, as ye will give an account to God,
who through me thus instructs you,--who am your imprisoned father--and
have been much grieved when I hear of any ill concerning you,--it
being more matter of trouble and sorrow to me,
than my imprisonment, or any thing else I suffer, or can suffer from man.

Your father, who desires your good, and that it may go well with you,
both here and hereafter.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
10th of Third month, 1667

And remember this one thing, which as a father I admonish you of,
and charge you to take notice of and observe,
which is this,--that ye do not fly out upon one another, or complain of one another,
because of the evils ye observe in one another;
but first take notice of that evil in yourselves:
if by the true light ye find your own hearts cleansed from it,
bless God who hath done it;
and keep to his light and the testimony of his witness in you, whereby he did it;
and watch that ye be not overtaken in it for the future.
But if ye be guilty of the same evil, or have lately done the same thing,
or are liable suddenly to do it,--O! for shame! forbear accusing or blaming another:
and in the fear of God wait on him, and pray unto him that ye may be delivered from it,
and kept out of it.
And then in tender pity, love and meekness,
admonish thy brother or sister of his or her evil,
and watch to be helpful to preserve or restore them;
and pray to God to direct thee how to be helpful to them.
But that is the bad spirit and nature,
(which God will sharply punish,) that is ready to accuse others:
and though it be never so bad and guilty, yet will be excusing itself,
and laying the fault upon others, or remembering some other fault of another,
when it should be sensible of and ashamed of its own.

Dear children, if ye bend your minds to learn these things,
the Lord will help you therein, and become your teacher, guide and preserver,
and pour down his blessings upon you; and ye will be a comfort to me and your mother,
and an honour to his Truth;
and He also may give me wise fatherly instructions to teach you further.
But if ye be careless, foolish, vain, following your own minds,
and what riseth up there from the wicked one, ye will grieve my heart,
and provoke God against you, to bring evil upon you, both in this world and forever.

Therefore, children, mind that which is near you--the light of God,
which discovers the evil and the good.
His witness, which observes all ye do, is near you: yea, he himself is in that light,
and with that witness.
Therefore, know, ye are in his presence at all times; who is an holy and just God,
hating that which is vain and evil, and loving that which is good and right before him:
and hath appointed a day and set a time, wherein he will either reward you with peace,
joy, and eternal happiness, if ye have been good, and done that which is good;
or with misery, destruction, and unsufferable pain both of soul and body,
if ye have been evil, and done that which is evil.
And God takes notice how many instructions ye have heard from Friends in Truth,
and from your parents; and how many meetings ye have been at,
wherein ye have been taught and warned of these things:
so that if ye turn your back upon his light, and will not hear its reproofs,
but will be vain, and idle, and foolish, and rash, and quarreling,
and doing that which is naught, and then covering it with lies, and so be as bad,
if not worse,
than children who were never thus taught and instructed,--God
will be exceedingly angry with you;
and may in his just judgment and sore displeasure, separate you from his light,
give you up to the black, dark spirit,
(from whom all this wickedness is,) to sow in sin here,
and to suffer the flames of eternal fire hereafter;--which is his reward,
and the reward of all who are persuaded by him to be of his nature,
and who hearken to him, and let him work through them.

O! my children, mind the Truth of God in you;
and that will let you see and understand the truth of what I now
write,--and in what fatherly love and tender care of you,
I write these things;
that ye might be warned of the great danger of neglecting the time
of your visitation by God`'s light and witness in you,
and of going on in the evil ways of the dark crooked spirit,
who will be tempting you to evil and hindering you from God,
as long as ye hearken to him.
Therefore, be not fools, to be led by him to destruction, in the evil way and evil works,
which lead thereto; but be wise to hearken to the light, and follow it,
out of that which is evil,
into everything that is good,--to the salvation of your souls.

I desire that Friends in the family, watch over them in these respects;
and when they find just occasion, to put them in mind of any of these things,
in the fear and wisdom of God, with tenderness and gentleness,
that they may reach the witness; but to take heed of upbraiding them,
or aggravating any thing, lest they be thereby hardened,
and the bad raised and strengthened in them.
And, my dear G.^
footnote:[Doubtless his daughter in-law, Gulielma,
afterwards the wife of William Penn +++[+++editorial note by John
Barclay in Letters etc. of Early Friends (1841)].]
and Friends, watch over your hearts and ways, that ye may be as examples to them;
that they may not only read these things from my writing,
but in your carriage towards them, and one towards another;
that they meet with nothing to strengthen or raise up the bad thing,
but to reach the witness, and bring and keep down the evil in them.
So the Lord bless your watchfulness, care, and endeavors therein;
that I may hear good of them,
and be comforted in the mercy and kindness of the Lord towards them.

[.letter-heading]
For My Dear Friends, Brethren, and Sisters in the Truth, in and about the Two Chalfonts

[.salutation]
Friends,

The Lord will wonderfully teach his people,
and wonderfully help them! he will pour of his life and virtue into them,
and cause his strength to appear in them, and break forth through them,
to the glorifying of his name,
and making glad the hearts of those that have breathed after him, and waited for him.
Therefore, let us lift up our heads, and "`fear the Lord,
and his goodness in the latter days?`" And let us
wait to be made able by him to receive of his riches,
and drink in of his fulness, that we may become rich and full in him,
and kept empty and poor in ourselves; that the more the life ariseth in us,
the more we may feel our own nothingness,
and be to the praise of the riches of his grace and mercy,
wherein and whereby he hath made us accepted in his Beloved.

And dear Friends, mind the principle, mind the root,
into which the Lord hath ingrafted us; that we may abide and grow up therein,
and daily find and feel the sap thereof springing up in us,
and quickening us more and more to God.
Ye know how ye entered; even so, ye must abide and grow up, even in the light,
in the life, in the power, which gathered, preserveth, and causeth to flourish.
So my dear Friends, let us all dwell in our everlasting habitation, and no more go forth,
but sink into the kingdom, and wait to feel the dominion, righteousness, holiness, power,
and purity thereof, daily revealed more and more in our hearts.
For there is no other root or spring of life,
than that into which the Lord hath gathered us,
no other true life and power in any vessel upon the earth,
besides that which springs therefrom.
Therefore feel, oh! feel that which establisheth, and that wherein the establishment is,
and your union, life, and strength therein;
that ye may not be bowed down or overborne by whatever happens,
either from within or without; but may feel and enjoy the rest and peace of your souls,
in that which is over all, and orders all to the good of those who fear him,
and in uprightness of heart wait upon him!

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 23rd of Fourth Month, 1667

[.letter-heading]
To the Friends at Chalfont, in Buckinghamshire

[.salutation]
O Friends!

Feed on the tree of life; feed on the measure of life, and the pure power thereof,
which God hath revealed, and manifesteth in you.
Do ye know your food, do ye remember the taste and relish of it?
Then keep to it,
and do not meddle with that which seemeth very desirable to the other eye,
and very able to make wise.
Oh abide in the simplicity that is in Christ,
in the naked truth that ye have felt there! and there,
ye will be able to know and distinguish your food, which hath several names in Scripture,
but is all one and the same thing:--the bread, the milk, the water, the wine,
the flesh and blood of Him that came down from heaven, John 6:51, etc.--it is the same,
only it is given forth weaker and stronger,
according to the capacity of him that receiveth it;
and so hath different names given to it accordingly.

Oh! keep out of that wisdom, which knoweth not the thing; for that is it,
which also stumbles about the names.
But keep to the principle of life, keep to the seed of the kingdom,
feed on that which was from the beginning.
Is not this meat indeed, and drink indeed! flesh indeed, and blood indeed!
The Lord hath advanced you to that ministration of life and power,
wherein things are known above and beyond names; wherein the life is revealed and felt,
beyond what words can utter.
Oh! dwell in your habitations;
and feed on the food which God brings you into your habitations; which is pure, living,
spiritual, and will cause your souls and spirits more and more to live in and to God,
as ye eat and drink thereof.
So be not shaken or disquieted by the wisdom of the flesh;
but feel that which settleth and establisheth in the pure power.

And the Lord God preserve you, and give you to watch against,
and to feel victory and dominion over, all that is contrary to Him in any of you;
and which stands in the way of your fellowship with Him,
and of your joy and peace in Him.

This sprang unto you in the good will of your Father,
from the life and love of your brother in the Truth,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 8th of Fifth Month, 1667

[.letter-heading]
To George Fox

[.salutation]
Dear G. F.,

I feel the tender mercy of the Lord, and some portion of that brokenness, fear,
and humility which I have long waited for, and breathed after.
I feel unity with, and strength from, the body: oh! blessed be the Lord,
who hath fitted and restored me, and brought up my life from the grave.
I feel a high esteem and dear love to thee, whom the Lord hath chosen, anointed,
and honored, and of thy brethren and fellow-laborers in the work of the Lord.

And, dear George Fox, I beg thy love, I entreat thy prayers,
in faith and assurance that the Lord hears thee, that I may be yet more broken,
that I may be yet more filled with the fear of the Lord,
that I may be yet poorer and humbler before the Lord,
and may walk in perfect humility and tenderness of spirit before him, all my days.

Dear George Fox, thou mayest feel my desires and wants more fully than my own heart.
Be helpful to me in tender love, that I may feel settlement and stability in the truth;
and perfect separation from, and dominion in the Lord over, all that is contrary thereto.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 15th of Fifth Month, 1667

[.postscript]
====

I entreat thy prayers for my family, that the name of the Lord may be exalted,
and his truth flourish therein.
Dear G. F., indeed my soul longs for the pure, full,
and undisturbed reign of the Life in me.

====

[.letter-heading]
To Friends of Both the Chalfonts

Oh! the treasures of wisdom and knowledge, the riches of love, mercy, life, power,
and grace of our God, which are treasured up for the soul in the Lord Jesus;
and are freely dispensed and given out by him, to them that come unto him, wait upon him,
abide in him, and give up faithfully to the law of his life;
whose delight it is to be found in subjection and
obedience to the light and requirings of his Spirit.

Feel, my Friends, oh! feel your portion,
and abide in that wherein the inheritance is known, received, and enjoyed.
For there is no knowing Christ truly and sensibly,
but by a measure of his life felt in the heart,
whereby it is made capable of understanding the things of the kingdom.
The soul without him is dead: by quickenings of his Spirit,
it comes to a sense and capacity of understanding the things of God.
Life gives it a feeling, a sight, a tasting, a hearing, a smelling,
of the heavenly things,
by which senses it is able to discern and distinguish them from the earthly things.
And from this measure of life, the capacity increaseth, the senses grow stronger;
it sees more, feels more, tastes more, hears more, smells more.
Now when the senses are grown up to strength, then come settlement and stability,
assurance and satisfaction.
Then the soul is assured of, and established concerning, the things of God in the faith,
and the faith gives assurance to the understanding;
so that doubtings and disputes in the mind fly away,
and the soul lives in the certain demonstration, and fresh sense, and power of life.
It daily feels the eternal Word and power of life to be, in the heart and soul,
what is testified of it in the Scripture.
It knows the flesh and blood of the Lamb, the water and wine of the kingdom,
the bread which comes down from heaven into the vessel, from all other things,
by its daily feeding on it, and converse with it in spirit.
What heart can conceive the righteousness, the holiness, the peace, the joy,
the strength of life, that is felt here!

For, Friends, there is no straitness in the Fountain.
God is fulness: and it is his delight to empty himself into the hearts of his children;
and he doth empty himself, according as he makes way in them,
and as they are able to drink in of his living virtue.
Therefore, where the soul is enlarged, where the senses are grown strong,
where the mouth is opened wide (the Lord God standing ready to pour out of his riches),
what should hinder it from being filled?
And being filled, how natural is it to run over,
and break forth inwardly in admiration and deep sense of spirit,
concerning what it cannot utter! saying, oh the fulness, oh the depth, height, breadth,
and length of the love!
Oh the compassion, the mercy, the tenderness, of our Father!
How hath he pitied, how hath he pardoned,
beyond what the heart could believe! how hath he helped in the hour of
distress! how hath he conquered and scattered the enemies! which,
in the unbelief, the heart was ready often to say, were unconquerable,
and that it should one day die, by the hand of one of other or its mighty enemies, lusts,
and corruptions.
How hath he put an end to doubts, fears, disputes, troubles,
wherewith the mind was overwhelmed and tossed! and now he extends peace like a river;
now he puts the soul forth out of the pit, into the green pastures;
now it feeds on the freshness of life, and is satisfied,
and drinks of the river of God`'s pleasure,
and is delighted! and sings praise to the Lamb, and Him that sits on the throne, saying,
Glory, glory! life, power, dominion, and majesty, over all the powers of darkness,
over all the enemies of the soul, be to thy name forevermore!

Now, my dear Friends, ye know somewhat of this, and ye know the way to it.
Oh be faithful, be faithful! travel on, travel on! let nothing stop you, but wait for,
and daily follow,
the sensible leadings of that measure of life which God hath placed in you,
which is one with the fulness, and into which the fulness runs daily and fills it,
that it may run into you and fill you.
Oh that ye were enlarged in your own hearts,
as the bowels of the Lord are enlarged towards you!
It is the day of love, of mercy, of kindness, of the working of the tender hand;
of the wisdom, power, and goodness of our God, manifested richly in Jesus Christ!
Oh! why should there be any stop in any of us?
The Lord remove that which stands in the way; and,
in the faithful waiting on the power which is arisen, the Lord will remove, yea,
the Lord doth remove;
and growth in his truth and power is witnessed by those that wait upon him.
So, my dear Friends, be encouraged to wait upon the Lord in the pure fear,
in the precious faith and hope which are of him;
and ye will see and feel he will exalt the horn of his Anointed in you,
over the horn of that which is unanointed, and will sweep and cleanse and purify,
even till he hath left no place for the impure:
and then ye shall become his full dwelling-place, the place of his rest,
the place of his delight, the place of his displaying his pure life and glory;
and he will be your perfect dwelling-place forevermore!

May the Lord God, in his tender mercy, and because of his deep and free love unto us,
guide our hearts daily more and more in the travel, and into the possession of this;
that every soul may inherit and possess, notwithstanding all its enemies,
what it hath travelled into, and may also daily, further and further,
travel into what is yet before.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 2nd and 3rd of Sixth Month, 1667

[.postscript]
====

[.salutation]
Postscript.--Friends,

Be not discouraged because of your souls`' enemies.
Are ye troubled with thoughts, fears, doubts, imaginations, reasonings, etc.? yea,
do ye see yet much in you unsubdued to the power of life?
Oh! do not fear it; do not look at it, so as to be discouraged by it; but look to Him!
Look up to the power which is over all their strength;
wait for the descendings of the power upon you; abide in faith of the Lord`'s help,
and wait in patience till the Lord arise;
and see if his arm do not scatter what yours could not.
So be still before him, and, in stillness, believe in his name; yea,
enter not into the hurryings of the enemy, though they fill the soul;
for there is yet somewhat to which they cannot enter, from whence patience, faith,
and hope will spring up in you, even in the midst of all that they can do.

Therefore into this sink; in this lie hid in the evil hour;
and the temptations will pass away, and the tempter`'s strength be broken,
and the arm of the Lord, which brake him, be revealed; and then ye shall see,
that he raised but a sea of trouble to your souls, to sink himself by;
and the Lord will throw the horse and his rider,
which trampled upon and rode over the Just in you, into that sea;
and ye shall stand upon the bank, and sing the song of Moses to Him that drowned him,
and delivered you from him! and, in due season, ye shall sing the song of the Lamb also,
when his life springs up in you in his pure dominion; triumphing over death,
and all that is contrary to God, both within and without.

Now, Friends, in a sensible waiting and giving up to the Lord, in the daily exercise,
by the daily cross to that in you which is not of the life, this work will daily go on;
and ye will feel from the Lord, that which will help, relieve, refresh, and satisfy,
which neither tongue nor words can utter.
And may the Lord God breathe upon you,
preserve and fill you with his life and holy Spirit,
to the growth and rejoicing of your souls in Him, who is our blessed Father,
and merciful Redeemer,--in the Lord Jesus Christ,
our Head and King forever and forevermore!

And then, as to what may befall us outwardly, in this confused state of things,
shall we not trust our tender Father, and rest satisfied in his will?
Are we not engraven in his heart, and on the palms of his hands?
and can he forget us in any thing he doth?
Shall any thing hurt us?
Shall any thing come between us and our life, between us and his love,
and tender care over us?
What though the fig-tree should not blossom, neither there be any fruit in the vine;
what though the labor of the olive should fail, and the fields yield no meat;
what though the flock be cut off from the fold, and there be no herd in the stalls;
may we not for all this rejoice in the Lord, and joy in the God of our salvation?
And what though the earth be removed,
and the mountains carried into the midst of the sea;
what though the waters thereof roar and be troubled,
and the mountains shake with the swelling thereof; is there not a river,
the streams whereof make glad the city of God?
Is not the joy, the virtue, the life, the sweet refreshment thereof,
felt in the holy place of the tabernacle of the Most High?
And he that provides inward food for the inward man, inward clothing, inward refreshment;
shall he not provide also sufficient for the outward?
Yea, shall he not bear up the mind, and be our strength, portion, armor, rock, peace,
joy, and full satisfaction in every condition?
For it is not the condition makes miserable, but the want of him in the condition:
he is the substance of all, the virtue of all, the life of all, the power of all;
he nourisheth, he preserveth, he upholdeth, with the creatures, or without the creatures,
as it pleaseth him: and he that hath him, he that is with him, he that is in him,
cannot want.
Hath the spirit of this world content in all that it enjoys?
no: it is restless, it is unsatisfied.
But can tribulation, distress, persecution, famine, nakedness, peril,
or sword come between the love of the Father to the child, or the child`'s rest, content,
and delight in his love?
And doth not the love, the peace, the joy, the rest felt,
swallow up all the bitterness and sorrow of the outward condition?

The seed, the godliness, the uprightness, the true nature and birth,
hath not only the promise of eternal life; but also whatever is necessary for the vessel,
wherein it dwells, in this life too.
So dwell in that to which is the promise, and live upon the promise; yea,
live upon that which cannot miss of the promise,
but feels the presence and power of the Father, in all and over all.
The just lives by his faith; and he that is in union with the just,
lives by the faith of the just, and takes no more care than the lilies,
but leaves the care of all to him, to whom it properly belongs,
and who hath taken it upon him; who nourishes, clothes, preserves,
and causes the lilies of the field to grow and flourish in beauty and glory:
and shall he not much more clothe, nourish, and take care of his own lilies,
the heavenly lilies, the lilies of his garden?

Let us then not look out like the world,
or judge or fear according to the appearance of things, after the manner of the world;
but let us sanctify the Lord of hosts in our hearts, and let him be our fear and dread;
and he shall be an hiding place unto us in the storms, and in the tempests,
which are coming thick upon the earth.

Thus, my dear friends, let us retire, and dwell in the peace which God breathes,
and lie down in the Lamb`'s patience and stillness, night and day,
which nothing can wear out or disturb:
and so the preservation of the poor and needy shall be felt to be in his name;
and glory shall be sung to his name over all, which is a strong tower, a mighty,
impregnable rock of defence against all assaults and dangers whatsoever;
which they that have trusted therein have already experienced it to be;
and they that continue trusting therein, shall always experience it so to be,
in all trials and dangers, whatever may happen, of what kind soever, even to the end.
Amen.

====

[.letter-heading]
To +++_______+++ +++_______+++

[.salutation]
Dear Friend,

Thou hast had the path of salvation faithfully testified of to thee,
and hast come to a sense of the thing; even to the feeling of that,
whereby the Father begets life, and manifesteth his love and peace in and to the soul.
Now, what remains?
but that thou look up to the Lord, to guide thy feet in this path,
and to preserve from that which darkens and leads out of the way;
that thou mayst pass on thy journey safely,
and come to the inheritance and enjoyment of that which thy soul longeth after.

There is life, there is peace, there is joy, there is righteousness, there is health,
there is salvation, there is a power of redemption, in the seed: yea, there is so.
But thy soul wants, and doth not enjoy these things.
Well, but how mayst thou come to enjoy them?
There is no way, but union with the seed; knowing the seed,
hearing the voice of the seed, learning of, and becoming subject to, the seed.
"`Learn of me, take my yoke upon you,`" saith Christ,
"`and ye shall find rest to your souls.`" Wouldst thou feel thy soul`'s rest in Christ?
Thou must know the seed`'s voice, hear it, learn daily of him, become his disciple;
take up, from his nature, what is contrary to thy nature.
And then, as thy nature is worn out, and his nature comes up in thee,
thou wilt find all easy; all that is of life easy, and transgression hard, unbelief hard:
yea, thou wilt find it very hard and unnatural,
when the nature of the seed is grown up in thee,
either to distrust the Lord or hearken to his enemy.
And then thou wilt change that dwelling-place (into which Satan brings dark thoughts,
suggestions, and reasonings) for the dwelling place which is from above,
which is the habitation of the righteous; wherein there is light, life, peace,
satisfaction, health, salvation, and rejoicing of soul from and before the Lord.

Now, do not say, Who shall do thus for me?
but know, the arm of the Lord is mighty, and brings mighty things to pass;
and that arm hath been revealed in thee, and is at work for thee.
Oh that thou couldst trust it! (why canst thou not! hath it not
sown a seed of faith in thee?) and come into and abide in the path,
wherein its mighty, powerful operations are felt and made manifest!
And, oh that thou mayst find ability, to watch against that which bows down,
and not so let in, as thou hast done exceedingly,
to the grievous wounding and distressing of thy soul!
For the enemy`'s dark suggestions work according to their nature;
and if thou let them lie upon thee, how can they but darken, afflict, and perplex thee?

Therefore, in the evil hour, fly from all things that thus arise in thee; and lie still,
feel thy stay, till his light, which "`makes manifest,`" arise in thee,
and clear up things to thee.
And think not the time of darkness long, but watch, that thy heart be kept empty,
and thy mind clear of thoughts and belief of things, till He bring in somewhat,
which thou mayst safely receive.
Therefore, say to thy thoughts,
and to thy belief of things (according to the representation of the dark power,
in the time of thy darkness), "`Get thee hence!`" And if that will not do,
look up to the Lord to speak to them; and to keep them out,
if they be not already entered, or to thrust them out if they be already got in.
And if he do not so presently, or for a long time, yet do not murmur or think much,
but wait till he do.
Yea, though they violently thrust themselves upon thee,
and seem to have entered thy mind, yet let them be as strangers to thee;
receive them not, believe them not, know them not, own them not; and thy bosom will,
notwithstanding, be chaste in the eye of the Lord,
though they may seem to thee to have defiled thee.

Look up to the Father, that thou mayest learn this of him: and,
becoming faithful to him therein, thou wilt find thy darkness abate,
and its strength more and more broken in thee;
and thou wilt not only feel and taste a little, now and then,
but also come to possess and inherit, and rejoice before the Lord in thy portion.

Thy Friend in the truth, which changeth not, but is pure, and preserveth pure forever.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From Aylesbury Jail, 28th of Seventh Month, 1667

[.letter-heading]
To M. S.

[.salutation]
Dear M. S.,

It is in my heart at this time to write to thee, not in the will, wisdom,
and affections of a man, but in the tender love and melting bowels which are of God;
beseeching thee to take heed of that wisdom which
(under subtlety and disguise) leads from the nature,
spirit, and power of truth;
raising up another thing in the heart for the witness and truth of God,
with which it bewitches the mind, and then wipes its lips and saith, It has done no harm;
but others are guilty, and my spirit and ways are innocent in the sight of the Lord,
and I feel his justification and clearness before him therein.

O! M.S. if thou be`'st entangled by that deceitful wisdom,
if another thing get up in thee which is not of the
truth (of the true innocency and simplicity,
whatever it appears to thee), then thou canst not hear the voice of the prophet,
which thou once heardst, nor stand to the testimony which it gave thee to bear;
but wilt warp and decline from (in the subtlety and specious pretences)
what thou tookest up in the uprightness and simplicity of truth;
and, not hearing the voice of that prophet, thou wilt err more and more, and grow strong,
wise, and hard in thy error,
even till at length the Lord be provoked to cut thee
off by his spirit and power from among his people.

[.signed-section-context-close]
3d of the 8th Month, 1667

[.letter-heading]
To His Brother

[.salutation]
Dear Brother,

This morning, as I was going out to walk,
somewhat sprang up in my heart freshly and livingly to thee; whereupon, I consulted not,
but immediately turned back so to do.
Now, if the Lord make it useful to thee, thou wilt have cause to bless his name;
and so shall I also,
who heartily desire the life and welfare of thy soul in the living God,
and thy avoiding all such snares as the enemy lays to betray,
and to keep it in death and bondage.
The thing that rose up in me, was this.

God gave some apostles, some prophets, etc., for the work of the ministry,
for the building up of the body, for the perfecting of the saints.
This was God`'s gift, in mercy and love, to them in that day,
of which gift they were to walk worthy, and to be thankful for it.

And in these days, the Lord hath given gifts to some for this work,
which the body hath need of; and the body is to wait on the Lord in the use of his gift,
in fear and humility.
For those that gather the soul to the Lord,
they also are appointed to watch over the soul,
in the same power and authority that gathered.
Now, that which is of God in any heart, being heeded,
will teach to make use of the gift and ministry which is of him;
and it cannot be despised, but God is despised; nor can it be neglected,
without loss and danger to the soul that neglects it.
For God is wise, and his ordinances, his ministry, his gifts, are weighty,
and his blessings go along with them.
Who have been gathered to him in these days,
but by his ministry which he hath appointed and sent to gather?
and who have been preserved, but those who have waited on the Lord,
and been subject to his Spirit in the same ministry which hath gathered?
Mark, brother, in every age, God`'s ministers have been despised.
Moses and all the prophets were despised in their day.
What! +++[+++said the despisers]
hath God spoken only by Moses?
hath he not spoken also by us?
The apostles were despised in their days, by those that kept not to the anointing;
for this always teacheth to reverence, in subjection to the Lord,
the ministry which is of the anointing.
"`He that despiseth you,`" said Christ,
"`despiseth me.`" He that despiseth them in their gathering, or in their building up,
despiseth Him that sent them.
They were earthen vessels, in presence contemptible, and very liable to be despised.
It is easy still, to despise God`'s messengers and servants;
but he that will truly and rightly esteem them, must lie low,
must dwell in the pure fear, and in the sense of life,
that he may be taught of God so to do.
It is an easy matter to have objections enough against them;
but to see through all prejudices and objections, to the pure and precious life in them,
and to the gift and spirit and power of the Lord,
wherein and whereby they minister,--this requires a true eye,
and a heart opened by the Lord.

Ah brother! this is a snare, wherein many have been caught in former ages,
and in this age also, which it is easy falling into, but the preservation out of it,
is not easy, but only by the power and mercy of the Lord.
And blessed are those, whom the Lord so favors as to preserve out of it,
and to remove from them those prejudices and devices, whereby they are entangled.
Dear brother! when I am in the pure sense before the Lord, and my spirit opened by him,
and thou presented before me; I could even beg most earnestly of the Lord,
that he would open thy eye, and give thee a true sight of thy state,
and cause thy spirit to bow before him; and to know and honor what is of him, and not,
by any device of the enemy, be hindered from receiving therefrom, what he,
in tender love and mercy, holds out to thee.

And, dear brother, mind this advice which just springs in my heart:
pick out some of the faithful ones of the Lord`'s servants, and open thy heart to them,
as, in the leadings of the Lord and waiting upon him, thou findest freedom thereunto.
Indeed, brother, I have had, for a long time, a deep sense of danger towards thee:
the Lord prevent it, that thy soul may live to him, and not die from him!
There is a wisdom, a will near thee, which will destroy thee,
unless the Lord destroy it in thee.

Oh that thou mightst come to wait aright for the motion of his
spirit! and mightst be kept by him in that which knows the drawing;
then wilt thou hunger and thirst after the righteousness of his kingdom,
and long after times of meeting and assembling with his people;
and find thy sense of them living, and thy life refreshed therein.
For, God is with his people, of a truth, and they meet not without him;
but his presence is in the midst of them, causing his life to flow into every vessel,
that stands open to him.
And death has not come over his people, whatever the enemy suggests,
where he gets an ear open:
but life grows more and more in freshness and into dominion in them.
O brother! the Lord fully gather thee into and preserve thee in that,
wherein thou mayst feel this in thy own particular,
wherein thou mayst feel the freshness of life, and the power thereof in them;
that thy heart also, may be as a watered garden, and as a living temple,
wherein the pure, living God dwells!

I am satisfied in my heart, that not only my love, but my life speaks to thee.
Oh that thou couldst hear, and feel, and fear,
and bow down before the Lord! that he might, in his due season,
raise thee up in his life and power among his people, purifying thee,
and preserving thee pure and living to him forever.

[.postscript]
====

Postscript.--Dear Brother,

The desire of my heart to the Lord for thee is,
that he would open and keep open in thee the eye which sees, and the ear which hears,
and the heart which understands his truth;
and that he would prevent the enemy from raising up another thing in thee,
instead of the seed of life and holy witness.

Great hath been the subtlety, and deep hath been the error from the truth;
and many who seem to be Jews are not, but have erred from the Spirit, life, and power,
wherewith they were at first convinced, and whereby they were at first led.
And in these, the enemy hath raised up a seat of prejudices,
and strong-holds against the ministry and power of the living God;
but those that are of the right seed bless the Lord, beholding his work,
while others slight it, and are expecting somewhat else;
they bless also the church which the Lord hath built,
and the ministry which he hath sent forth to gather and build it.

O brother! there is a high-mindedness in some which
takes upon it to judge beyond its growth and capacity;
and there is a fear in the hearts of others, lest any thing in them should get up,
or judge, or be any thing, beyond or beside the pure Truth;
this teacheth to honor and prefer those, whom the Lord hath preferred,
the other hath accusations and pleas against them;
the one of these witnesseth preservation from God, the other is left to fall.
Dear brother,
believe a traveller in the path of life (the Lord
God raise up in thee that which can believe),
the enemy, with great subtlety, hath laid his snares, hath taken many in his snares,
even in the snares which he laid by his instrument, J--P--;
and many did let in his spirit before they were aware,
and are at this day (unknown to their own hearts) entangled therein.
The Lord God will terribly appear against such (indeed it is truth),
unless they bow to his light, acknowledge their error from the truth,
and come back to the body by repentance, and turning from that,
wherein this spirit hath entangled them.

Dear brother, it is my desire that thou mayst not perish,
but feel the carrying on of the work of salvation in thee; travel on in the pure, holy,
living, powerful path, and receive the crown of fidelity to the truth!
Ah brother! mourn to the Lord; fear before him;
converse and consult with those that abide faithful;
and they may help thee to see (through the guidance, presence,
and power of the Spirit of the Lord with them), what of thyself,
thou art not able to see.
Remember this counsel; thy life is wrapped up in it; for thou hast need of the helps,
which the Lord, in his tender mercy, hath provided, and canst not be safe without them.

Thy dear Brother, in the unity of nature, longing after perfect sense of thee,
and unity with thee, in the pure life.

====

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 7th of Eighth Month, 1667

[.letter-heading]
To +++_______+++ +++_______+++

[.salutation]
Dear Friend,

I have heard that thou hast somewhat against W.R. whereupon
thou forbearest coming to meetings to his house;
which thou oughtest seriously weigh and consider,
that thy path and walking herein may be right and straight before the Lord.
Is the thing, or are the things, which thou hast against him,
fully so as thou apprehendest?
Hast thou seen evil in him, or to break forth from him;
and hast thou considered him therein, and dealt with him as if it had been thy own case?
Hast thou pitied him, mourned over him, cried to the Lord for him,
and in the tender bowels of love and meekness of spirit, laid the thing before him?
And if he hath refused to hear thee, hast thou tenderly mentioned it to others,
and desired them to go with thee to him;
that what is evil and offensive in him might be more
weightily and advantageously laid before him,
for his humbling,
and for his recovery unto that which is a witness and strength against the evil?
If thou hast proceeded thus, thou hast proceeded tenderly and orderly,
according to the law of brotherly love,
and God`'s witness in thy conscience will justify thee therein.
But if thou hast let in any hardness of spirit, or hard reasonings against him,
or hard resolutions, as relating to him,
the witness of God will not justify thee in that.
And if at any time hereafter thou hast any thing against others,
oh learn from that of God in thee to show bowels of compassion towards them,
as the Lord has had pity on thee.
And keep to his witness in thy heart.
Wait to feel the seed, and to keep thy dwelling therein,
that thou mayest abide in the peace and rest thereof,
and not depart out of thy habitation, out of the sense of truth;
for that will let in temptation upon thee, give the enemy strength against thee,
and fill thy soul with anguish and perplexity.
So the Lord God of infinite tenderness renew his mercy upon thee, and keep thee in that,
wherein his love, life, rest, joy, peace,
and unspeakable comfort of his holy Spirit (which is able to keep the
mind out of all the snares and temptations of that which is unholy),
is felt and witnessed,
by those who are taught and enabled by him to abide
and dwell in that into which he gathered them,
and in which he hath pleased to appear unto them.

This is in the love and tender goodness of the Lord to thee,
from thy friend in the truth, and for the truth`'s sake,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
13th of 10th Month, 1667

[.letter-heading]
To Bridget Atley

[.salutation]
My Dear Friend,

If thy heart come to feel the seed of God,
and to wait upon him in the measure of his life,
he will be tender of thee as a father of his child,
and his love will be naturally breaking forth towards thee.
This is the end of all his dealings with thee, to bring thee hither,
to make thee fit and capable of entering and abiding here.
And he hath changed, and doth change thy spirit daily;
though it be as the shooting up of the corn,
whose growth cannot be discerned at present by the most observing eye,
but it is very manifest afterwards that it hath grown.
My heart is refreshed for thy sake, rejoicing in the Lord`'s goodness towards thee;
and that the blackness of darkness begins to scatter from thee,
though the enemy be still striving the same way to enter and distress thee again.
But wait to feel the relieving measure of life, and heed not distressing thoughts,
when they rise ever so strongly in thee; nay, though they have entered thee,
fear them not, but be still awhile,
not believing in the power which thou feelest they have over thee,
and it will fall on a sudden.

It is good for thy spirit, and greatly to thy advantage,
to be much and variously exercised by the Lord.
Thou dost not know what the Lord hath already done,
and what he is yet doing for thee therein.
Ah! how precious it is to be poor, weak, low, empty, naked, distressed,
for Christ`'s sake,
that way may be made for the power and glory of his life in the heart.
And oh! learn daily more and more to trust him and hope in him,
and not to be affrighted with any amazement,
nor to be taken up with the sight of the present thing;
but wait for the shutting of thy own eye upon every occasion,
and for the opening of the eye of God in thee, and for the sight of things therewith,
as they are from him.
It is no matter what the enemy strives to do in thy heart,
nor how distressed thy condition is, but what the Lord will do for thee, which is,
with patience, to be waited for at his season in every condition.
And though sin overtake, let not that bow down; nor let the eye open in thee,
which stands poring at that: but wait for the healing through the chastisement,
and know there is an Advocate, who, in that hour, hath an office of love,
and a faithful heart towards thee.
Yea, though thou canst not believe, yet be not dismayed thereat; thy Advocate,
who undertakes thy cause, hath faith to give: only do thou sink into,
or at least pant after the hidden measure of life,
which is not in that which distresseth, disturbeth, and filleth thee with thoughts,
fears, troubles, anguish, darkness, terrors, and the like; no,
no! but in that which inclines to the patience, to the stillness, to the hope,
to the waiting, to the silence before the Father: this is the same in nature,
with the most refreshing and glorious-visiting life, though not the same in appearance:
and if thy mind be turned to it, not minding but overlooking the other,
thou wilt find some of the same virtue springing up in thy heart and soul,
at least to stay thee.

In and through these things, thou wilt become deeply acquainted with the nature of God,
and know the wonderful riches and virtue of his life, the mightiness of his power,
and the preciousness of his love, tenderness of his mercy,
and infiniteness of his wisdom, the glory also, and exactness of his righteousness, etc.:
thou wilt be made large in spirit to receive and drink in abundantly of them;
and the snares of the enemy will be so known to thee and discerned,
the way of help so manifest and easy, that their strength will be broken, and the poor,
entangled bird will fly away singing, from the nets and entanglements of the fowler;
and praises will spring up, and great love in thy heart to the Forgiver and Redeemer.
Oh wait, hope, trust, look up to thy God!
Look over that which stands between!
Come into his mercy!
Let in the faith which openeth the way of life,
which will shut out the distrusting and doubting mind, and will close up the wrong eye,
that letteth in reasonings and temptations, the wrong sense, and death with them.

Thus mayest thou witness, in and through thy Redeemer,
the abundance of his life and peace.
