[short="Testimony of George Fox"]
== The Testimony of George Fox, concerning Isaac Penington

Concerning our dear brother Isaac Penington, who is lately deceased,
and whom the Lord hath lately taken away from among his people,
and from his wife and children; he was a serviceable minister of the gospel of salvation,
and of the word of life, which did spring through him often,
to the refreshing and comforting of the church of Christ, and to his own comfort,
and to the praise and glory of the Lord God.
Amen.

And now all must be content with and in the will of the Lord God,
who giveth and taketh at his own pleasure; who hath all breath and life,
and the length of days in his hand.
And so he is well in the Lord; blessed be the name of the Lord, who is over all forever.
For, as John saith; "`Blessed are the dead which die in the Lord, from henceforth: yea,
saith the spirit, that they may rest from their labors, and their works do follow them.`"

You may see what a cloud of witnesses the apostle speaketh of, which died in the faith,
and obtained a good report; which holy and divine faith is the victory.
In this faith they pleased God; and by this faith, the gift of God,
they had access to God, and so died in the Lord, and have his blessing from him,
the fountain then and now.
And so all true Christians are to live, that Christ may be "`magnified in their bodies,
whether it be by life or death,`" as the same apostle saith, Phil. 1:20.
And the same apostle saith to the saints; "`None of us liveth to himself,
and no man dieth to himself; for whether we live, we live unto the Lord,
and whether we die, we die unto the Lord: whether we live, therefore, or die,
we are the Lord`'s.`" Rom. 14:7-8. And Christ saith,
"`Whosoever liveth and believeth in me, shall never die.
Believest thou this?`" John 11:26.
For they are grafted into Christ by believing in his light,
which is the life in him.

The memorial of the just is blessed: "`Even the Lord God of hosts,
the Lord is his memorial.`" Hos. 12:5.
"`But the name of the wicked shall rot.`" Prov. 10:7.
"`and his memory shall be cut off from the earth.`"
Ps. 109:15. So ye may see the memorial of the just is
recorded by the just in Holy Scriptures of Truth.
But my desire is, that all may see their names written in the Lamb`'s book of life,
before the foundation of the world, and rejoice in that, "`and praise God,
that their life is hid with Christ in God.`" Col. 3:3.

"`Precious in the sight of the Lord is the death of his saints.`"
Ps. 116:15. Therefore live the holy and righteous life,
that ye may die the death of the righteous.

It is now above twenty years since Isaac Penington came among God`'s people,
and since that time he has gone through many exercises
and trials and temptations and snares,
both by them that are without, and false brethren; besides all his sufferings,
and cruel and tedious imprisonments, and persecutions,
for the name and life of Jesus Christ, and true Christianity; which in the end,
some years before his death, the Lord, in and with his power, set him free from;
and gave him dominion over all, and established him upon his living rock and foundation,
to praise his holy name in his church, and among his saints and people,
in the Lord`'s fresh living power and spirit.
And he did freely minister of his living bread and water,
which he had received from above, from the living God and his Son,
to the comfort of them that fear the Lord, and keep their habitation in the truth,
in meekness and in humility.

I do know that he is well in the Lord,
and in peace with him through the Lord Jesus Christ.
Such as are puffed up, and do swell in their notions,
may rejoice and be glad that he is taken out of their way;
and they may think they will have the more liberty; because that he,
being a living stone, and member of the living head,
had no fellowship nor unity with such as were full of high swelling words,
without the life of Christ, the heavenly and spiritual man; but did reprove such,
and admonish them:
but such their gladness and joy will be turned into
bitterness and sorrow and mourning in the end.
Therefore, let all such take heed and be warned,
lest the hand of the Lord do suddenly turn against them.
For I could desire,
that all were in that innocent life that he departed out of this world in:
and I know that he died in the Lord, and is blessed.
So let his works follow him, who is well, and at his rest with the Lord Jesus Christ,
who is the rest of all his faithful people.
To him be glory and honor, thanks and praise, now and forever.
Amen.
