[#ellwood-testimony, short="Testimony of Thomas Ellwood"]
== The Testimony of Thomas Ellwood, concerning Isaac Penington

Although I am not ignorant that many weighty and living testimonies have
been already given in by true and faithful witnesses upon the same occasion,
which might well seem sufficient to excuse mine; yet am I not thereby clear,
but find a pressing upon my spirit to write a few
lines also concerning this my dear deceased friend;
to which, I confess, I am induced, and in some sort engaged,
by the double obligation of affection and gratitude.
Love him I did, and that entirely, and sure I am, very deservedly;
for he was worthy indeed of love from all men, but more especially from me,
to whom he had been abundantly kind:
for in the day wherein it pleased the Lord to awaken my soul,
and call me out of the pollutions of the world,
with respect alike to worship and conversation,
(for which I became the derision of my country,
the scorn and contempt of my familiars and acquaintance, and in a manner an outcast also,
exposed as it were in the world to shift in it,) how welcome was I then
to him! how affectionately did he receive me! how regardfully did he take
care of me! how tenderly and like a father did he watch over me,
that I might not be drawn back, or any way be betrayed from the simplicity of truth,
as I had received it!
And can I ever forget his love, or let his manifold kindness slip out of my mind!
Oh no; the remembrance of him is pleasant to me, and I think not of him without delight:
for as a friend, I truly loved him;
as a father (for such his care of me rendered him to me), I reverenced him; as an elder,
I honored him, and that (as he right well deserved) with double honor.
My spirit was truly united to his; yea,
my soul was linked and knit unto him in the holy covenant of life,
which death hath not been able to dissolve.
Bear with me therefore a little, I entreat thee, whoever thou art,
under whose eye these lines may chance to fall,
if I take liberty to express my sense of this my beloved friend;
wherein if I seem somewhat particular, know that my acquaintance with him was so.

He was naturally furnished with a sharp and excellent wit,
and that well cultivated and polished with an ingenuous and liberal education;
his disposition was courteous and affable, free from pride and affectation.
His ordinary discourse cheerful and pleasant, neither morose nor light,
but innocently sweet, and tempered with such a serious gravity,
as rendered his converse both delightful and profitable.

From his childhood (as I have heard him occasionally say) he was religiously inclined,
and sought the Lord in his tender years.
And although the way of truth was not then so cast up unto him, as since,
through the goodness of the Lord, it was; yet that he had then, at times,
some true touches and tastes of life, some openings and sights of heavenly things,
(though not so clear, unmixed,
and abiding as after,) the treatises which he then wrote do manifestly declare.
-- And albeit, at the first manifestation of truth unto him in this present dispensation,
he was not without doubts and jealousies concerning it, as himself relates;
nor free for some time from disputes and reasonings against the meanness of its appearance,
yet, after it pleased the Father, in the riches of his grace, to reveal his Son in him,
thereby giving him to see, and certainly to know,
what was that good and acceptable and perfect will of God; oh,
how joyfully did he receive it! how willingly did he bow unto it!
how readily did he yield his neck to the yoke of Christ! and how
constantly and delightfully did he wear it!
Did he then regard the pleasures of the times,
or value the preferments and honors of the world,
though living at that time in the favor and affluence of it?
No, no: he turned his back upon it all;
esteeming the reproach of Christ greater riches than the treasures of Egypt;
and casting down his crown at the foot of Jesus, he willingly became a fool to the world,
and to the wisdom thereof, that he might be made truly wise to God.
And surely he obtained his desire herein; for as he honored the Lord,
and preferred him above all; so the Lord did highly honor him,
and gave him liberally of the true and heavenly wisdom, adorned with humility;
so that he was learned, and yet humble; full of knowledge (heavenly knowledge),
yet not puffed up thereby.
And as he had freely received of the Lord,
so did he freely and readily communicate thereof (as the following
sheets do witness) unto such as stood in need of counsel,
advice, information, or direction in their travel to the heavenly country.
To which service he was fitted and very well furnished
by the experiences of his own travel;
for the Lord had led him through many a strait and difficulty; through many temptations,
trials, and exercises, by which he had tried and proved him.
Not only through the Red Sea and the Wilderness had he passed,
but the bottom of Jordan also had he seen, and the upholding,
delivering arm of the Lord through all had he known and felt;
whereby he was able to speak a word of information to the bewildered passenger;
a word of encouragement to the weary and fainting traveller;
a word of comfort to the afflicted soul, and of consolation to the wounded spirit.
And oh, how sweetly have I heard it flow from him!
How has it dropped like the dew, and distilled like the gentle rain!
Ah, how tender, how compassionate, how full of bowels and feeling sympathy was he!
Surely his words have been many times as apples of gold in pictures of silver.
For of a truth the Lord was with him, and his heavenly power did often fill his temple;
and the Spirit of the Lord rested upon him,
and the fruits thereof were plentifully brought forth through him, in love, in joy,
in peace, in long-suffering, in gentleness, in goodness, in faith, in meekness,
and in temperance; so richly did the word of the Lord dwell in him.
His delight was in the service of God, to which he was wholly given up,
and in it spent most of his time, either publicly in meetings waiting upon God,
or privately in visiting and ministering unto those that were distressed,
or any way afflicted in mind or body; and when at home, he was frequent in retirements,
and very inward with the Lord.
Very fervent he was in prayer, and very frequent;
for the Spirit of grace and supplication was plentifully poured upon him,
by which he often wrestled with the Lord, and not in vain.
The holy Scriptures he read much, and with great delight and profit:
for he made it not a cursory or formal business,
nor sought to pick out the meaning by his natural wit or learning; but,
with a great composedness of mind, and reverence of spirit,
waited to receive the true sense of them from the openings of that divine spirit,
by which the penmen of them were inspired.
Great and strong was the travail of his spirit for the conversion of others;
and in a more especial manner did his love flow and
bowels yearn after the professors of religion,
for whom he continually and earnestly labored,
both by word and writing (not ceasing to seek them to his dying day),
that they might be brought off from the shadows, and come at length to inherit substance.
And blessed be the Lord, by the powerful operation of the Spirit of God,
through his ministry, many were turned to the truth, and many confirmed in it:
for the Lord was with him, and spake by him;
so that his teaching was with divine authority, in the demonstration of the Spirit,
and of power.
To the world, and the affairs of it, he was very much a stranger;
but deeply experienced in the things of God: for his affection being set on things above,
his conversation was in heaven, and his life hid with Christ in God.
He was but a pilgrim on the earth, and is now gone home.
In his family he was a true pattern of goodness and piety; not only by his grave example,
but by his savory instructions and exhortations to godliness.
To his wife he was a most affectionate husband; to his children,
a loving and tender father; to his servants, a mild and gentle master; to his friends,
a firm and fast friend; to the poor, compassionate and openhearted; and to all,
courteous and kind.
Very zealous he was for the truth, unwearied in promoting it,
bold and undaunted in the defence of it, faithful in his testimony to it,
patient and cheerful in his suffering for it.
A right good and pious man indeed was he; one that truly feared God,
and warily eschewed evil.

How great and various his exercises were in the times of his former professions;
how earnest and pressing his spirit then was after the pure enjoyment of God;
how strange and admirable the dealings of the Lord were with him;
and how far he came at length to see the travail of his soul, and to be satisfied;
as himself of all men best knew;
so he hath occasionally scattered here and there a hint thereof,
in several pieces of the following books; which, for the reader`'s satisfaction,
I had once thought to have collected and presented here together; but finding,
amongst his loose papers, a summary account thereof, written with his own hand,
above a dozen years ago, when, being in bonds for Christ`'s sake,
he was sick near unto death, I chose rather to transcribe that hither,
and refer the more curious and industrious reader
to the several books and papers of the ensuing volumes,
wherein he hath touched the same subject; as namely, The Way of Life and Death,
etc. in the preface, and in the postscript.
Babylon the Great described, etc.
The scattered Sheep, etc.
An Examination of the Grounds, etc. and A Glass for Professors.
Where is the Wise?
Observations on Rom. 14:20. Of the Church in its first and purest State.
The holy Truth and People defended.
Not to enumerate each particular.

The account he gives of his spiritual travail is as followeth:

"`A true and faithful relation, in brief, concerning myself,
in reference to my spiritual travails, and the Lord`'s dealings with me.
I say true and faithful, because it is of the truth, and not given forth in my own will,
but in the Lord`'s will and requirings of me at this time, for his service.
The relation is as follows:

"`I have been a man of sorrow and affliction from my childhood,
feeling the want of the Lord, and mourning after him: separated by him from the love,
nature, and spirit of this world, and turned in spirit towards him,
almost ever since I could remember.

"`In the sense of my lost estate, I sought after the Lord; I read the Scripture;
I watched over mine own heart; I cried unto the Lord for what I felt the want of;
I blessed his name in what he mercifully did for me, and bestowed on me, etc.
Whatever I read in the Scriptures as the way of God to my understanding,
I gave myself to the faithful practice of; being contented to meet with all the reproach,
opposition, and several kinds of sufferings,
which it pleased the Lord to measure out to me therein.
And I cannot but say that the Lord was good unto me, did visit me, did teach me,
did help me, did testify his acceptance of me many times,
to the refreshing and joy of my heart before him.

"`But my soul was not satisfied with what I met with, nor indeed could be,
there being further quickenings and pressings in my spirit, after a more full, certain,
and satisfactory knowledge; even after the sense, sight, and enjoyment of God,
as was testified in the Scriptures to have been felt and enjoyed in the former times:
for I saw plainly that there was a stop of the streams,
and a great falling short of the power, life, and glory which they partook of.
We had not so the Spirit, nor were so in the faith, nor did so walk and live in God,
as they did.
They were come to Mount Zion, and the heavenly Jerusalem, etc.,
which we had hardly so much as the literal knowledge or apprehension what they were.
So that I saw the whole course of religion among us was, for the most part, but a talk,
to what they felt, enjoyed, possessed, and lived in.

"`This sense made me sick at heart indeed, and set me upon deep crying to God,
close searching the Scriptures, and waiting on God,
that I might receive the pure sense and understanding of them, from and in the light,
and by the help of his Spirit.
And what the Lord did bestow on me in that state,
with thankfulness I remember before him at this very day: for he was then my God,
and a pitier and a watcher over me;
though he had not pleased then to direct me how to stay my mind upon him.
And then I was led (indeed I was led,
I did not run of myself) into a way of separation
from the worship of the world into a gathered society:
for this both the scripture and the Spirit of God in me gave testimony unto;
and what we then met with, and what leadings and help we then felt,
there is a remembrance and testimony in my heart to this day.
But there was somewhat wanting, and we mistook our way;
for whereas we should have pressed forward into the spirit and power,
we ran too much outward into the letter and form:
and though the Lord in many things helped us, yet therein he was against us,
and brought darkness, confusion, and scattering upon us.
I was sorely broken and darkened,
and in this darkened state sometimes lay still for a long season,
secretly mourning and crying out to the Lord night and day.
Sometimes I ran about, hearkening after what might appear or break forth in others;
but never met with any thing whereto there was the least answer in my heart,
save in one people, who had a touch of truth;
but I never expressed so much to any of them,
nor indeed felt them at all able to reach my condition.

"`At last, after all my distresses, wanderings, and sore travails,
I met with some of the writings of this people called QUAKERS,
which I cast a slight eye upon and disdained, as falling very short of that wisdom,
light, life, and power, which I had been longing for, and searching after.
I had likewise, some pretty distance of time after this,
opportunity of meeting with some of them;
and divers of them were by the Lord moved (I know it to be so since) to come to me.
As I remember, at the very first they reached to the life of God in me,
which life answered their voice, and caused a great love in me to spring to them;
but still in my reasonings with them, and disputes alone (in my mind) concerning them,
I was very far off from owning them, as so knowing the Lord,
or so appearing in his life and power as my condition needed, and as my soul waited for.
Yea, the more I conversed with them,
the more I seemed in my understanding and reason to get over them,
and to trample them under my feet, as a poor, weak, silly, contemptible generation,
who had some smatterings of truth in them, and some honest desires towards God;
but very far off from the clear and full understanding of his way and will.
And this was the effect almost of every discourse with them; they still reached my heart,
and I felt them in the secrets of my soul;
which caused the love in me always to continue, yea, sometimes to increase towards them:
but daily my understanding got more and more over them,
and therein I daily more and more despised them.

"`After a long time I was invited to hear one of them (as I had been often,
they in tender love pitying me, and feeling my want of that which they possessed);
and there was an answer in my heart, and I went with fear and trembling,
with desires to the Most High, who was over all, and knew all,
that I might not receive any thing for truth which was not of him,
nor withstand any thing which was of him;
but might bow before the appearance of the Lord my God, and none other.
And indeed, when I came, I felt the presence and power of the Most High among them,
and words of truth from the Spirit of truth reaching to my heart and conscience,
opening my state as in the presence of the Lord.
Yea, I did not only feel words and demonstrations from without,
but I felt the dead quickened, the seed raised;
insomuch that my heart (in the certainty of light, and clearness of true sense) said,
This is he, there is no other:
this is he whom I have waited for and sought after from my childhood;
who was always near me, and had often begotten life in my heart;
but I knew him not distinctly, nor how to receive him, or dwell with him.
And then in this sense (in the melting and breakings
of my spirit) was I given up to the Lord,
to become his, both in waiting for the further revealing of his seed in me,
and to serve him in the life and power of his seed.

"`Now what I met with after this, in my travails, in my waitings,
in my spiritual exercises, is not to be uttered: only in general I may say this,
I met with the very strength of hell.
The cruel oppressor roared upon me, and made me feel the bitterness of his captivity,
while he had any power: yea, the Lord was far from my help,
and from the voice of my roaring.
I also met with deep subtleties and devices to entangle me in that wisdom,
which seemeth able to make wise in the things of God, but indeed is foolishness,
and a snare to the soul, bringing it back into captivity,
where the enemy`'s gins prevail.
And what I met with outwardly from my own dear father, from my kindred, from my servants,
from the people and powers of the world, for no other cause but fearing my God,
worshipping him as he hath required of me, and bowing to his seed, which is his Son,
who is to be worshipped by men and angels forevermore, the Lord my God knoweth,
before whom my heart and ways are; who preserved me in love to them,
in the midst of all I suffered from them, and doth still so preserve me;
blessed be his pure and holy name.

"`But some may desire to know what I have at last met with?
I answer, I have met with the Seed.
Understand that word, and thou wilt be satisfied, and inquire no further.
I have met with my God; I have met with my Saviour;
and he hath not been present with me without his salvation;
but I have felt the healings drop upon my soul from under his wings.
I have met with the true knowledge, the knowledge of life, the living knowledge,
the knowledge which is life; and this hath had the true virtue in it,
which my soul hath rejoiced in, in the presence of the Lord.
I have met with the Seed`'s Father, and in the Seed I have felt him my Father.
There I have read his nature, his love, his compassions, his tenderness,
which have melted, overcome, and changed my heart before him.
I have met with the Seed`'s faith,
which hath done and doth that which the faith of man can never do.
I have met with the true birth, with the birth which is heir of the kingdom,
and inherits the kingdom.
I have met with the true spirit of prayer and supplication,
wherein the Lord is prevailed with,
and which draws from him whatever the condition needs;
the soul always looking up to him in the will, and in the time and way,
which are acceptable with him.
What shall I say?
I have met with the true peace, the true righteousness, the true holiness,
the true rest of the soul, the everlasting habitation, which the redeemed dwell in:
and I know all these to be true, in him that is true, and am capable of no doubt,
dispute, or reasoning in my mind about them; it abiding there,
where it hath received the full assurance and satisfaction.
And also I know very well and distinctly in spirit where the doubts and disputes are,
and where the certainty and full assurance are,
and in the tender mercy of the Lord am preserved out of the one, and in the other.

"`Now the Lord knows, these things I do not utter in a boasting way;
but would rather be speaking of my nothingness, my emptiness, my weakness,
my manifold infirmities, which I feel more than ever.
The Lord hath broken the man`'s part in me, and I am a worm, and no man before him.
I have no strength to do any good or service for him: nay,
I cannot watch over or preserve myself.
I feel daily that I keep not alive my own soul; but am weaker before men, yea,
weaker in my spirit, as in myself, than ever I have been.
But I can not but utter to the praise of my God, and I feel his arm stretched out for me;
and my weakness which I feel in myself, is not my loss, but advantage before him,
-- And these things I write, as having no end at all therein of my own,
but felt it this morning required of me;
and so in submission and subjection to my God have I given up to do it,
leaving the success and service of it with him.`"

I.P.

Aylesbury, 15th of 3d month, 1667

Neither to him was it given only to believe, but to suffer also for the sake of Christ.
His imprisonments were many, and some of them long,
which with great constancy and quietness of mind he underwent.
But because so general an account may perhaps not
answer the expectation and desire of the reader,
I will here subjoin a more particular; but that as contracted and short as may be.

His first imprisonment was at Aylesbury jail, in the years 1661 and 1662,
being committed thither for worshipping God in his own house; where, for seventeen weeks,
great part of it in winter, he was kept in a cold and very incommodious room,
without a chimney;
from which hard usage his tender body contracted so great and violent a distemper,
that for several weeks after, he was not able to turn himself in his bed.

His second imprisonment was in the year 1664, being taken out of a meeting,
where he with others was peaceably waiting upon the Lord, and sent to Aylesbury jail,
where he again remained a prisoner between seventeen and eighteen weeks.

His third imprisonment was in the year 1665, being taken up, with many others,
in the open street of Amersham,
as they were carrying and accompanying the body of a deceased friend to the grave.
From hence he was sent again to Aylesbury jail;
but this commitment being in order to banishment, was but for a month, or thereabouts.

His fourth imprisonment was in the same year, 1665,
about a month after his releasement from the former.
-- Hitherto his commitment had been by the civil magistrates; but now,
that he might experience the severity of each, he fell into the military hands.
A rude soldier, without any other warrant than what he carried in his scabbard,
came to his house, and told him he came to fetch him before Sir Philip Palmer,
one of the deputy-lieutenants of the county.
He meekly went, and was by him sent with a guard of soldiers to Aylesbury jail,
with a kind of mittimus, importing,
"`That the jailer should receive and keep him in safe custody
during the pleasure of the earl of Bridgewater;`" who had,
it seems, conceived so great, as well as unjust, displeasure against this innocent man,
that, although (it being the sickness year) the plague was suspected to be in the jail,
he would not be prevailed with,
by the earnest importunity of a person both of considerable
quality and power in the county,
only to permit Isaac Penington to be removed to another house in the town,
and there kept prisoner until the jail were clear.
Afterwards a prisoner dying in the jail of the plague, the jailer`'s wife,
her husband being absent, gave leave to Isaac Penington to remove to another house,
where he was shut up about six weeks: after which,
by the procurement of the earl of Ancram, a release was sent from the said Philip Palmer,
by which he was discharged, after he had suffered imprisonment three quarters of a year,
with apparent hazard of his life, and that for no offence.

By the time he had been at home about three weeks,
a party of soldiers from the said Philip Palmer (by order of the earl of Bridgewater,
as was reported) came to his house, and seizing him in bed,
carried him away to Aylesbury jail again; where, without any cause showed,
or crime objected, he was kept in prison a year and a half, in rooms so cold, damp,
and unhealthy, that it went very near to cost him his life,
and procured him so great a distemper, that he lay weak of it several months.
At length a relation of his wife`'s, by an habeas corpus,
removed him to the King`'s-Bench bar,
where (with the wonder of the court that a man should be so long
imprisoned for nothing) he was at last released in the year 1668.
This was his fifth imprisonment.

His sixth imprisonment was in the year 1670, in Reading jail,
whither he went to visit his friends that were sufferers
there for the testimony of Jesus.
Of which, notice being given to one called Sir William Armorer,
a justice of the peace for that county, and living in the town,
he was forthwith sent for before him, and committed to the jail,
thereby becoming a fellow-sufferer with them, whom, being sufferers for the truth,
he came to visit.
Here he continued a prisoner a year and three quarters,
and was brought under the sentence of premunire; but at length the Lord delivered him.

Thus through many tribulations did he enter into the kingdom; having been exercised,
tried, proved, and approved by the Lord.
Long was he in the warfare, and, like a good soldier,
manfully endured the fight of afflictions: but having fought the good fight,
and kept the faith, he hath now, in the Lord`'s good time, finished his course,
and is gone to possess the crown of righteousness laid up for him,
and all those that love the bright appearance of the Lord.
-- A faithful laborer he was in the Lord`'s vineyard for many years;
but now hath he ceased from his labor, and his works follow him.
He walked with God, and is translated.
To the Lord he lived, and in the Lord he died,
and by the Spirit of the Lord he is pronounced blessed:
blessed forever be the name of the Lord therefore.
