== BABYLON THE GREAT DESCRIBED

THE CITY OF CONFUSION IN EVERY PART WHEREOF ANTICHRIST REIGNS WHICH KNOWETH
NOT THE ORDER AND UNITY OF THE SPIRIT,
BUT STRIVETH TO SET UP AN ORDER AND UNIFORMITY ACCORDING TO THE WISDOM OF THE FLESH,
IN ALL HER TERRITORIES AND DOMINIONS

HER SINS, HER JUDGMENTS WITH SOME PLAIN QUERIES FURTHER TO DISCOVER HER;
AND SOME CONSIDERATIONS TO HELP OUT OF HER SUBURBS,
THAT HER INWARD BUILDING MAY LIE THE MORE OPEN TO THE BREATH AND SPIRIT OF THE LORD,
FROM WHICH IT IS TO RECEIVE ITS CONSUMPTION AND OVERTHROW

ALSO AN EXHORTATION TO THE POWERS OF THE EARTH

BY ISAAC PENINGTON, THE YOUNGER

+++[+++1659]

That which is far off, and exceeding deep, who can find out?
I applied mine heart to know, and to search, and to seek out wisdom, and the reason;
and to know the wickedness of folly, even of foolishness and madness.
And I find more bitter than death the woman whose heart is snares and nets,
her hands bands.
He that is good before God shall escape from her; but the sinner shall be taken by her.
Ecc. 7:24-26

He that is born of the pure, immortal seed, and lives in the anointing,
escapes the golden cup of fornication, and all the painted beds of fornication,
and is not defiled with women; Rev. 14:4. but remains chaste to the bridegroom.

Lo this is the city which is built up of and filled with
images and likenesses of the ways and truths of God,
without the life and power.

On her outside there is the likeness of a church, the likeness of a ministry,
the likeness of the ordinances, duties, and ways of holiness.

On her inside there is the likeness of the good knowledge,
the likeness of repentance and conversion, the likeness of faith,
the likeness of zeal for God, the likeness of love to God and his saints,
the likeness of the Lamb`'s meekness and innocency, the likeness of justification,
the likeness of sanctification, the likeness of mortification, the likeness of hope,
peace, joy, rest, and satisfaction, etc., but the substance, the truth,
the virtue of all these is wanting to her;
and she herself is found persecuting that very thing (where
it is found in truth) the image whereof she cries up.

This, this is the woman that hath bewitched the whole earth for these many generations,
and is still changing her dresses and paints, that she might still bewitch people,
and sit as a queen reigning over their consciences;
but blessed be the light which is arisen to discover,
and the power which is able to overthrow this stately, this lofty, this mighty city,
and all that take part with it.

The Lord God Omnipotent reigneth in Zion; and antichrist, with his city Babylon, falleth.
Sing praises, sing praises, O inhabitant of Zion! to him who subjecteth Babylon,
with all her glory, under thy feet.

For he bringeth down them that dwell on high; the lofty city he layeth it low;
he layeth it low, even to the ground; he bringeth it even to the dust.
The foot shall tread it down; the feet of the poor, the steps of the needy. Isaiah 26:5-6.

=== PREFACE

There hath been in me a zeal for God from my childhood,
and a most earnest search into the Scriptures (which my soul deeply relished,
and my heart honored and loved,
and still doth) for the revelation of the mind and will of God.
Two things did I earnestly search and beg for:
the one was for the discovery of the outward way of worship;
the other for the inward life, virtue, and power,
which I looked upon the outward as the proper means to lead me to.
At the beginning of the troubles in these nations, there was a lively stirring in me,
and a hope that God was bringing forth somewhat.
I likewise felt the same stirring in many others, at which my heart was rejoiced,
and with which my soul was refreshed; but I found it soon begin to flag and wither,
which forced me to retire,
and to separate from that where I found the life and power dying and decaying.
In my separation the Lord was with me; my soul remembereth it right well;
and he had regard to the simplicity, honesty, and integrity of my heart,
which he himself had kindled in me.
And though I fell too soon into a way of church-fellowship and ordinances;
yet he had regard to me, and pitied me, and refreshed my life even there.
But at length the form overgrew us, and the sweet and precious life in us began to die.
Then the Lord found out another way to refresh us (namely,
by a sensible relating of our conditions, and of his dealings with us,
and workings in us), which was very sweet and precious at first;
but the enemy crept in there also.
Out of this state I never made any change; but here the hand of the Lord fell upon me,
striking at my very root, breaking all my life in sunder,
and trampling my crown in the dust.
Then I became a man of sorrows (being stripped of all my life, faith, hope, joy, comfort,
in one day) not knowing which way to look, nor what to desire.
Sometimes there were breathings stirring in me, but they were presently judged;
sometimes a little glance of refreshment from a scripture presented to me;
but suddenly taken away, and my death and darkness increased thereby.
Then should I wish,
Oh that I might appear before his throne! for surely my conscience is clear in his sight,
and I have not wickedly departed from my God, but was broken in pieces by his hand,
even while my soul was earnestly seeking after him.
Oh how my soul did mourn,
to see how I was fit to be made a prey to every ravening
spirit! and many did seek to devour me,
but the hand of the Lord was with me, preserving me, though I knew it not.
And though I was wholly broken, and desolate of all that I had called, or could call,
knowledge (insomuch that I could not call any thing either good or evil), yet the Lord,
by a secret instinct, preserved me exceedingly out of that which was evil,
and kept my heart secretly panting after the fountain and wellspring of good.
Yea, when I was at length (through deep despair of ever meeting
with God any more in this life) captivated by the world,
and betrayed by the love of it (which at last rose up in me, and gained upon me,
by persuading me that my present estate and condition did require the free use of it,
and the enjoyment of all it could afford), yet the Lord followed me,
and often was I visited with secret loathings of the world, and turnings from it,
and pantings after the spring of my life: but these were dreaded by me,
and suddenly quenched by the evil part,
for fear of that misery and unutterable anguish which I had felt hereby;
the remembrance whereof was fresh in me.

In this my courting of the world, and estrangement from the life,
the reasoning part (which the Lord had been long battering,
and had laid very low) gathered strength in me; and I began to grow wise again,
and able to judge of the things of God, and to hope and wait for some great appearance,
wherein at length I might be visited, and meet with that which I so vehemently desired,
and stood in such need of.
Thereby the enemy deeply deceived me, pleasing me herewith,
and keeping me hereby from unity with that which
alone was able to give me the sight of him,
whenever he should appear.
And in this fleshly wisdom I judged and despised the true life in others; as weak, low,
and not able to bring them to that which I stood in need of, and waited for.
Yea, the more I considered and reasoned in my mind,
and the more I conversed with them (hoping thereby to find
some clear ground either of owning or turning from them),
the further off still was I; till at length the Lord powerfully touched,
and raised up the life in me (which by all these reasonings and consultations,
all this while, I slew); and then by degrees (waiting upon that), I saw, I felt,
I tasted, I handled, as the Lord pleased to open to me here,
that which was shut out from me in my narrowest search and closest reasonings.
Thus the Jew in me was cast off, and the Gentile called: but who can read this?
I am sure the eye of man`'s religious wisdom cannot.

Hereby my eyes have been opened, and I have seen the fetters,
whereby I have been held captive from my life all my days: yea,
many of the streets and chambers of Babylon hath mine eye beheld (in the pure life),
wherein the witch dwells which enchanteth from the life: yea,
I have heard the tongue of the false prophet, which speaketh so like the true prophet,
as no flesh can discern or distinguish between them: yea,
I have seen the dragon in the temple, worshipped there for God,
by the strictest sort of professors.
And now, in tender bowels, in the true light of life,
from the pure movings of the eternal spirit (as the Lord pleaseth to guide and
direct) do I come forth to visit my poor fellow creatures and captives in Babylon.
And what I have seen and known, I testify for the relief of others, that,
if it be possible (by the mercy and good hand of God),
they may escape that misery wherewith my poor soul hath been overwhelmed,
and may come out of that filthy, abominable city which God is making desolate;
where the pure life, the conquering faith, the suffering love, the purifying hope,
the putting off of the body of sin, the putting on the living garment,
is not and cannot be witnessed, but men are only dreaming of these things in Babylon;
where all the satisfaction they have, is from the pleasure of their dream;
but when they awake they will find leanness, and penury, and nakedness upon their souls.

=== A DESCRIPTION OF BABYLON FOR THE SAKE OF THE DAUGHTER OF SION, WHICH AT PRESENT DWELLETH IN THE MIDST THEREOF

Now, though the world be deaf and blind (even all sorts of worldly professors,
from the highest to the lowest), yet open your ears, and hear the joyful sound;
open your eyes, and see the city of desolations,
and of all the abominations of the earth (both of flesh and spirit);
and feel in yourselves what it is which is to be led out, and what is to lead you;
that your feet may be guided to, and set firm upon, Mount Zion;
where the life rules over all her enemies.

BABYLON is the spiritual fabric of iniquity;
the mystical great city of the great king of darkness; built in imitation of Zion,
painted just like Zion, that it might be taken for Zion, and be worshipped there,
instead of the true, eternal, ever-living God, and King of Zion.

This is the seat of the man of sin: where there is a building framed in any heart,
or in any society of men, like Zion; there he lodges, there he lives,
there he sits as god, there he reigns, there he is worshipped,
there he is exalted above all that can truly be called God in that heart,
or in that society.

1+++.+++ It is a city.
This is a proper parable, to discover the mystery of iniquity by in this state;
it is just like a city, in its kind it is a city.
In a city there are several streets; in the streets, houses; in the houses,
several rooms, to which families and persons appertain;
and to all these there are laws and governments.
Thus it is here; there are many streets in this city of Babylon,
many houses in every street, many rooms in every house;
and the houses and rooms have their several families and persons appertaining to them;
and they have their laws and governments, their knowledge of God and Christ; their order,
their worship, their discipline in which they walk,
and by which they order themselves in their several services, places, offices,
and employments, under the king of Babylon.

2+++.+++ It is a spiritual or mystical city.
It is not an outward building of earthly materials,
but an inward building of inward materials.
As the outward Zion, the outward Jerusalem, is passed away in its use and service;
so the outward Babylon is out of date too.
(Ye need not look so far for it.) And as God hath built up an inward city,
a spiritual building; so hath the king of darkness likewise.
He could never have tempted from the city of the living God,
from the city of the mystery of life, but by the city of the mystery of deceit.
And as God builds his city of hewn stones, of squared stones, of living stones;
so also hath the king of darkness his hewings, his squarings, his preparations,
his qualifications for his buildings.
If the light break forth, and make it appear too gross to have the whole nation a church,
or to admit a whole parish to ordinances, he will gather a church out of the nation,
and select some of his choicer stones out of the parish; yea,
he may grasp in some of the stones of the true temple,
if they come within his reach and circle; that is, if they look abroad,
if they step forth, and keep not close to the anointing within,
which is the great and only ordinance of the saints`'
preservation from antichrist`'s power:
for if they step forth but so much as into a prayer against antichrist, out of this,
they are caught in his snare, and are serving him in that very prayer,
which they may seem with great earnestness and zeal to put up against him.

3+++.+++ It is a great city; an overspreading city, a city that overspreads the earth.
As Zion was a vast city,
a city that did overspread the nations (how did the faith of the gospel over-run
the world in the apostles`' days!) so this city hath also over-run the world.
Indeed it hath taken up the whole territories and dominions
of the other city (and hath enlarged itself further),
and Zion hath been laid in the dust, and trodden under foot.
And though many witnesses, prophets, and martyrs, have mourned over her,
yet none have been able to raise up the tabernacle of David, which hath fallen down,
nor to recover Zion to this day; but Babylon hath had the power over her.
Look with the true eye, and behold how all nations, kindreds, tongues, and languages,
have been drunk with some or other of the mixtures
of this false woman`'s cup (some of them over,
and over, and over again), and have been inhabitants of this city,
crying her up (though not all in her gross habit,
but some in her more refined shapes and transformings) for the true church, for Zion;
whereas, alas! she hath only Zion`'s dress, Zion`'s shape,
Zion`'s outward garment (which is the likeness wherein she lies in wait to deceive),
but not Zion`'s spirit.

4+++.+++ It is a city of iniquity, of hidden iniquity.
That which is hidden in this city, it is not the life, it is not the righteousness,
the holiness of the saints; but iniquity, sin, transgression of the life.
Look into any of the streets of Babylon, into any of the houses, any of the rooms,
any of the chambers of darkness; there is sin there; there is unrighteousness there;
there is not one cleansed heart to be found there;
not one pure eye to behold the God of life is to be found there;
but in every heart sin in a mystery, iniquity in a mystery, unrighteousness in a mystery.
They seem to be for God and Christ, and to be cleansed by them;
but uncleanness lodges in them, and sin rules in them against God,
and against his Christ in a mystery; which their eye cannot see,
and so must needs mistake their state.
Yet this is the true state of Babylon, in all the parcels of it; it is the unclean city,
where purity of heart and life cannot be known;
but though it be washed and transformed ever so often outwardly,
yet still it remains inwardly polluted;
that which defileth keeping possession and dominion there in a mystery.
The living water, the living blood, runs not in any of the streets of this city,
so that there can be no true cleansing there.
Nay, such strangers are the choicest inhabitants of Babylon to the fountain of life in Zion,
to the river that cleanseth and healeth,
that they cannot so much as believe that there is
a possibility of cleansing and perfect healing,
and making sound and whole here, while on earth.
There is great talk of these things (of the water, the blood,
the cleansing) in all the regions of Babylon (which hath heard of the fame,
and forms to itself a likeness); but the thing itself is not to be found there,
and so the virtue, which comes from the thing itself alone, cannot be felt there.

And here, in this there is a great difference between the vessels of Zion,
and the vessels of Babylon.
The vessels of Zion, they are weak, earthen, foolish,
contemptible to the eye of man`'s wisdom (which cannot
look for any great matter of excellency there);
but the treasure, the liquor of life in them, is precious.
The vessels of Babylon make a great show, appear very holy, very heavenly,
very zealous for God and Christ,
and for the setting up of his church and ordinances all over the world.
Thus they appear without; but they are sepulchres; there is rottenness within:
under all this there lodgeth an unclean, an unsanctified heart;
a heart unsubdued to the spirit and power of the gospel,
while it makes such a great show of subjection and obedience to the letter.

5+++.+++ It is the city of the king of darkness, of the great king of darkness,
of the prince of the power of the air, who rules universally in the darkness,
in the mystery of iniquity throughout, even in every heart.
Wherever is sin, there is Satan`'s throne; and there he hath his laws, his government,
his power, in every heart of his dominion.
And where there is the least subjection to him, he is yet a prince;
his building is not as yet there wholly thrown down;
he is not there as yet dispossessed and cast out.
As long as there is any thing left wherein he may dwell, he knows his own,
and keeps his hold of it.
It is his right, and he will not lose it.
All sin, all darkness, is properly his: it is his seat, and he hath the government there.
Man is the land where these two kings fight;
and whatever is good and holy belongs to the one king,
and whatever is evil and unclean belongs to the other;
and there is no communion or peace between them; but each keeps his own,
and gathers of his own unto himself.
And where the fight is once begun between these, there is no quietness in that land,
till one of these be dispossessed: but then there is either the peace of Babylon,
most commonly under a form of holiness; or the peace of Zion, in the spirit, life,
and power.

6+++.+++ This city was built (and is daily built) in imitation of Zion, painted just like Zion.
The intent of its building was to eat out Zion, to suppress Zion,
to withdraw from the truth by a false image,
and to keep her inhabitants in peace and satisfaction,
under a belief and hope that it is the true Zion;
and therefore it must needs be made like Zion, else it could no way suit these ends.
Every street must be like the streets of Zion; every house, like the houses of Zion;
every tribe and family, like the tribes and families of Zion; every person,
like the persons in Zion; all the laws, ordinances, etc.,
like the laws and ordinances of Zion; the worship, like the worship in Zion; the faith,
like the faith of Zion; the painted Christ, like the Christ of Zion;
all that go for truths, like the truths of Zion; they would not deceive else;
Babylon would be soon seen through else, and become quickly desolate and forsaken,
did she not lay her paint very thick, and with great art and skill.
Now here is the wisdom, here is the true eye tried,
to see through all the paints of this city, in all the shapes and forms of it;
to turn from every street, every house, every chamber,
every image and false appearance of truth;
every false appearance of ordinances and ways of worship;
every likeness of things which this spirit forms from the letter;
every duty that it thus calls for;
every promise of scripture which it endeavors to apply to that to which it belongs not,
that it might lull the soul asleep, and cozen and deceive it of the thing promised; here,
I say, is the true eye tried to turn from all this,
and to wait for the raising and redeeming of the true seed of Zion,
and for the springing up of the true life and power in it and from it:
for as long as this spirit can deceive you with any likeness,
ye shall never know the truth, nor come to the worship of the true, living God,
which alone is in the spirit, and in the truth.

7+++.+++ The end of all this, of Satan`'s building up this city,
this great city (thus accurately in the power of deceit,
and in the very likeness of Zion) was, and is, that it might be taken for Zion,
and be worshipped there as God, and that without jealousy or suspicion.
And he hath attained his end; his city hath deceived and doth deceive,
it passeth current for Zion among all the inhabitants of Babylon;
almost every sort of people cry it up for Zion, in one appearance or other,
though all do not cry up the same appearance; but their own image, way, and worship,
every one extols; their own image of the truth, for the truth; their own way of worship,
for the way; their own church and family, for the church and family of God.
And worshipping here, they worship him, and not the Lord:
for the Lord cannot be worshipped in any part of Babylon;
but the king of Babylon is worshipped in Babylon, and the king of Zion alone in Zion.
Ah! how deeply do men deceive their souls! they think they believe in God,
they think they pray to God, and hope to be owned at length by God,
and yet are so far from coming out of mystery Babylon,
that it was never yet so much as discovered to them;
but they have either walked in the way of religion and worship they were brought up in,
in the apostasy, or perhaps have removed out of one or two of the broad streets of it,
and so thereby think they have left Babylon;
whenas the same spirit hath set down in another street of the same city,
building up another house by the direction of the king thereof,
and there worshipping the same spirit as they did before;
but their souls never knew the fire in Zion, and the furnace in Jerusalem;
by which the very inwards of their spirits must be cleansed,
before the pure eye of life be opened which can see Zion.

Now, because ye are more able to receive things from scripture expressions,
than from the nature of the thing itself,
spoken as it is felt in the heart (concerning which much more might be said,
were ye able to bear it), consider a few scriptures.

Babylon is called a great city, Rev. 16:19. and a great and mighty city.
chap.
18:10. Oh, the power of deceit in that city, to bewitch from the life!
Oh, the multitude of lying wonders that are there shown in the heart,
to make a man believe that he is in the life! to persuade men that
the king thereof is the king of Zion! and that the laws,
and ordinances of worship there,
are the laws and ordinances of Zion! that the prayer there,
is the prayer of the true child! that the believing there,
is the true faith! the love there, the true love! the hope there, the true hope, etc.
Some parts of Babylon, some likenesses of truth there, are so taking,
that none but the elect, by the opening of the eternal eye, can espy the deceit.

And it is a spiritual city, a mystical city,
a city built by the working of the mystery of iniquity, 2 Thess. 2:7.
whereupon she is called mystery. Rev. 17:5.
It is not a city of plain wickedness, but a city of sin hid;
of sin keeping its life under a covering, under a form of godliness;
of sin reigning in the heart under zeal, under devotion, under praying, believing,
worshipping, hoping, waiting, etc.
Where sin lies hid within under these, there is Babylon;
there is the mystery of witchcraft; there is the painted throne of Satan;
there is spiritual Egypt and Sodom, where the Lord of life is daily crucified.
This is the city, the mystical city, the spiritual city. Rev. 11:8.
And here is building up and throwing down continually.
She builds; the spirit of the Lord confounds, then down goes her building;
then up with another, then down again.
This is her course without end, when the spirit of the Lord disturbs her;
for otherwise she can settle in any form of knowledge or worship;
though in her ordinary course she hath also many changes and turnings;
one while this or that being a truth, another while not;
one while this or that being the sense or meaning of such a scripture, another while not.
Babylon is hardly ever without this kind of building up, and throwing down.

And this city is a great city, a city spread over all the earth.
"`She made all nations drink of the wine of the cup
of her fornication.`" Rev. 14:8. The woman,
which is this city (Rev. 17:18), "`sat upon peoples, and multitudes, and nations,
and tongues.`" Rev. 17:15. She sat upon them as queen, as princess,
guiding them in their knowledge and worship of the king of Babylon.
And those that once hated her, and made war with her, and burnt her flesh with fire,
she cozened them with a new paint, got them into her new bed of fornication,
and made them worship the king of Babylon again, Rev. 17:12-13.
and ver. 16-17. and there they lay committing whoredom with her,
till the time of her last burning and utter desolation; but then they forsook her,
for fear of her torment, when they saw the smoke of her burning. Rev. 18:9-10.

In the temples of this city (for in all the streets thereof, yea, in every house,
there are temples) antichrist sits as god, and is worshipped. 2 Thess. 2:4.
"`He, as God, sitteth in the temple of God,
showing himself that he is God.`" He hath clothed himself like God,
he appears like God (like the holy, pure spirit of life and power),
he appears in the temple of God, he sits there, he rules there,
he gives forth laws and ordinances of worship and devotion.
Yea, if any one will question his godhead, or his right to do thus, he will prove it,
he will make it manifest in the very temple of God, that he is God: "`He, as God,
sitteth in the temple of God,
showing himself that he is God.`" He hath exalted himself into the throne,
above all that is called God; he hath got into the temple, he sitteth there as God,
and there he maketh it manifest to all his worshippers that he is God; insomuch as,
among all the inhabitants of Babylon, he is acknowledged and worshipped,
and the true spirit of life is hid from their eyes, and denied and crucified.
He hath showed himself that he is God; he gives demonstrations of his godhead,
which that eye which is out of the life cannot but acknowledge and take to be true.
There is none can see and acknowledge the true God, the true Christ,
but those that have the true eye,
the true anointing ("`no man can say that Jesus is the Lord,
but by the holy spirit,`" 1 Cor. 12:3); and yet how many can speak great words of God,
and of Christ, who know not what belongs to the anointing?
Alas! alas! all nations and sorts of professors, out of the life,
are cozened with the devil`'s demonstrations, with antichrist`'s demonstrations,
with the whore`'s demonstrations, with the false prophet`'s demonstrations,
which are undeniable to that wisdom wherein they stand,
and to that eye wherewith they look to see.

Now mark this: antichrist`'s coming, when first perceived, was very mighty,
exceeding strong. 2 Thess. 2:9-10.
"`Whose coming is after the working of Satan, with all power,
and signs, and lying wonders, and with all deceivableness of unrighteousness,`" etc.
Weigh the thing well.
Satan used all his art, and all his strength,
to conceive and bring forth this mystery of iniquity, so like the mystery of godliness,
that it might pass for current in the world, and he rule as God in it.
With all power, etc., no power of deceit wanting; he did not spare for signs,
and lying wonders; yea, he gave power to the beast to do wonders and miracles,
even to make fire come down from heaven on the earth,
in the sight of men (which was the sign and wonder whereby
the God of Israel was distinguished from Baal;
power to work this very sign Satan gives to the beast,
to confirm the godhead of the dragon and antichrist with). Rev. 13:13-14.
These are the things men look for; see but great power, signs,
miracles, they are satisfied.
The whole world stands ready to be deceived with this.
Yea, and if the eye be not opened in persons, which can distinguish of power,
they must needs be deceived.
Signs, wonders, and miracles had their place in the first covenant,
and were to that part to which the first covenant was; not to them that believe,
but to them that believe not.
Now after the full demonstration of the truth by signs and miracles,
the power of Satan riseth up; and by lying signs, wonders,
and miracles overturneth the truth.
Now the unbelieving part in man expects and calls for signs and miracles,
and says they will determine the controversy, and settle the state of the church again;
but that part is not to prescribe God his way; yea, he will steal as a thief upon thee,
whose eye is abroad, and looketh for demonstrations without.

And as antichrist got up thus, so antichrist will go out thus.
He will raise up this power, and what lying signs, wonders, and miracles he can,
to defend himself with, now the spirit of the Lord is risen up to dispossess him,
and cast him out of the house which he hath long lodged in.
And he that can be cozened with power, with signs, with lying wonders,
(which are lying because they come from the spirit of deceit, with an intent to deceive,
though they may come to pass, and appear true to man`'s eye.
Duet. 13:1-3) or with any of the deceivableness of unrighteousness,
shall never come out of Babylon;
but only be translated into some of the more refined chambers of it,
and fed with some more fresh likenesses of truth,
where he shall still remain an inhabitant and worshipper in some image,
perhaps of universal love, life, and liberty, and yet be out of the life,
out of the love, out of the liberty of the truth,
which stands in the power and presence of the spirit of God,
and not in the most refined image or likeness.

"`All the world wondered after the beast,
and they worshipped the dragon which gave power unto the beast,
and they worshipped the beast.`" Rev. 13:3-4.

The dragon is the devil; the beast is that spirit of the earth which he raiseth up,
and feeds in men with a form and appearance of truth; to which he gives his power,
his seat, and his authority:
and every man hath a measure of this according to his state and condition,
place and service in Babylon.
And now what a man doeth here in religion, be he ever so devout and zealous,
and frequent in ordinances and duties, is the worship of this spirit,
and of the dragon who sits and rules in this spirit.
I am run into hard expressions, very hard,
because the nature of these things is hid from men`'s eyes,
and they are in the mist of antichrist`'s raising, in the smoke which comes from the pit,
where there is no opening of the true eye, and no true sight of things;
but truly if ever you espy the dragon, the beast, antichrist, the whore,
the false prophet, ye must look at home, and read within;
and there having found the thing, and seen it in the true light,
ye will be able to see it certainly abroad also.
Now do not go about to distinguish these things in the notion of the understanding;
but come to feel the life, to unite with the life,
and the eye will open which can see into the nature of things,
and will behold all in its season; for that eye which is so eager to see,
shall never see these things;
but that eye alone which waits in stillness and quietness
on the pleasure and good-will of the opener.

Now all this time, while Babylon stands, while antichrist sits in the temple,
while Satan reigns over all the antichristian world,
the true and living God hath not been known, feared, nor glorified;
but men`'s knowledge hath been of a false god they have set up, and him they have feared,
and given the glory to, in their worship.
Nay, the gospel hath not been preached; the true gospel, the everlasting gospel,
the gospel wherein is the light and power of eternal life,
to turn men from all antichristian forms of knowledge and worship,
to the true life and power: but when Babylon falls,
and Mount Zion begins to appear again, then the gospel is to be preached again,
even by an angel, who receiveth it from God himself, Rev. 14:6-7.
for man could never recover it again: it requires a new inspiration.
"`The law is to go forth out of Zion and the word of the Lord from
Jerusalem.`" And this gospel is to be preached "`to every nation,
kindred, and tongue, and people,`" ver. 6. Mark: there was not one nation,
not one kindred, not one tongue, not one people that kept the everlasting gospel;
but it was laid up in Zion; it was carried with the church into the wilderness,
and there it hath been hid all the time of the apostasy, since the days of the apostles.
But now Zion is redeeming, the true woman bringing back again out of the wilderness,
she brings back the true, everlasting gospel with her;
and there is an angel chosen in the power of the Lord (even in the same
power and spirit that first preached it) to preach it again to every nation,
kindred, tongue, and people.
And the Lord hath so ordered it,
that he will have the voice of this angel as despicable to the wise in religion,
to the zealous in devotion, of all sorts in this backsliding age,
as the former preaching was to the wise and devout both among the Jews and Greeks.
So that whosoever is wise in religion according to the flesh;
whosoever is wise in expectation and waitings for the kingdom;
whosoever is wise in reasoning about it, and can tell the foregoing signs of it, etc.,
shall not know the voice: but he that can shut his eyes by the leadings of the pure life,
and enter into the hidden womb of wisdom, where the light of life is sown,
he shall be new formed, and come forth a child out of the womb of wisdom,
with the new eye, the new ear, the new heart, the new understanding and senses;
and keeping in the childish simplicity, out of the wisdom, zeal,
and devotion which deceived him before,
he shall receive and enter into the everlasting kingdom.

Therefore all people wait humbly for the candle of the Lord,
that therewith ye may search out Babylon,
and may come to see what of her treasures ye have gathered;
that ye may throw them away speedily,
and give up your ships and vessels (wherewith ye have trafficked
for these kinds of wares) to the fire of the Lord`'s jealousy;
that ye may receive the durable riches;
that ye may hear the joyful sound of the everlasting gospel,
and know the true Christ which it alone reveals;
and come to fear and worship and glorify the true God;
and not go down into the pit or lake with the dragon, the beast, the whore,
and false prophet, which will be the portion of the most zealous false worshippers.
And when your eyes come once to be opened in the true light,
ye will bless the Lord for giving you these warnings,
and not be so angry at us (who have paid dear for them) for our willingness,
if it be possible, to save you some of the charges they have cost us: however,
at least to preserve your souls from that ruin and dreadful
destruction which all the paths of Babylon lead to.

=== THE SINS OF BABYLON

Although, in the foregoing description, some of the sins of Babylon have been touched at;
yet I find my spirit further drawn forth (in a way of service to the Lord and his people)
to take a further view, both of them, and some other of her sins.

THE sins of Babylon,
by the spirit of life (which hath righteously measured
and knoweth them) are referred to these two heads,
fornication and abomination.
She allureth the spirit of the creature into a strange bed,
and there it acts filthily and abominably with this strange spirit.
Now of these there are two sorts; first, some more open and manifest; secondly,
some more hidden and secret, hard (yea, utterly impossible) to be discerned,
without the shining forth of the pure light of life.

All sorts of men are estranged from the life;
under the whole heaven is the Lord God forgotten,
and his holy and pure law and way of life;
and filthiness and abomination are committed everywhere.
Now all this filth (even the common filth of the earth) springs out of Babylon,
hath its rise from her womb.
Were it not for her, the sound of life would be heard even among the heathen,
and they would not be such strangers to him that made them;
nor would they act so contrary to those leadings and teachings
of the spirit of God (who is the God of the whole earth),
which the darkest parts are not without.
It is she which withdraws their minds from the pure glimmerings that rise up in them,
setting up another god in their eyes, and heathenish, sottish ways of fear, worship,
and devotion: and under this she makes them filthy and polluted,
unclean in their minds and in their bodies,
brutish in their knowledge and in their practices; "`for she is the mother of harlots,
and abominations of the earth.`" Rev. 17:5. Look what of pride, of vanity, of cruelty,
of envy, of wrath, of lust, of covetousness, of idolatry, of blasphemy, etc.,
is to be found anywhere among men upon the earth, she is the mother of it all.
All the common filth and stench of the earth springs out of this womb, this secret womb,
this hidden womb: for though, in this her open and visible appearance,
she be manifest to the eyes of many;
yet to those children of hers who are thus conceived, brought forth, and bred up by her,
she is a mystery of iniquity, and they perceive her not so much as here,
and so cannot escape this her openly polluted bed.

Secondly, The whore hath more secret fornications and abominations.
Where she can pass thus, she need not paint either herself or her ware;
but where need requires she hath her paint, she hath her delicates for the curious eye. Rev. 18:3.
She hath her cinnamon, odors, ointments,
and frankincense for the nice scent; she hath her fine flour and wheat, etc.,
for the fine palate; and gold, precious stones, pearl, and vessels of ivory,
and all manner of vessels of most precious wood, for the more stately worshipper;
as well as of brass and iron for the more common. Rev. 18:12-13.
She can paint both herself and her ware,
so as to make them taking to the eye of all flesh.
She can so mingle her cup, as shall please every palate but that which is truly living;
and cast such a color upon her abominations, as no eye that is without can suspect;
but takes with every young man that is hunting abroad,
and knows not the spring of life in himself.
So that all the deceits in religion,
all the several forms and ways of knowledge and worship, all the ordinances, duties,
and devotions which the spirits of most men take pleasure in, are of her.
And herein are her pride and glory, in subjecting these, in ruling over these,
in blinding the eyes of these, and opposing the true life and power by these.
She doth not value whole territories of the other so much as the congregation of these.
For mark:

The great master-piece of the whore was to paint herself like the Lamb`'s wife,
and so to withdraw from the true church, and set up a false church; which,
by reason of its paint and likeness to that which once was the true,
should pass up and down the world, and be taken for the true: and here lie her beauty,
her glory, her majesty, her life, her heart,
even in the deceivableness of this appearance.
Therefore her great care and endeavor are to keep her possession and dominion here.
She often reneweth and changeth her paint,
nearer and nearer to the image and former likeness of truth,
that she might make it pass instead of the truth,
and so keep that which is indeed the truth down still under reproach, contempt,
and persecution, as she hath done these many ages.
Therefore she hath her sorts of paint by her, her varieties of sorcery, of witchery,
of enchantments, whereof her cup is full, and wherewith her wine is made strong,
to make the inhabitants of the earth drunk thereby; that being thus besotted,
being not themselves,
but their spiritual senses bound up (as the wine doth very effectually,
wherever her cup is drank of,) she might lead them up and down from one thing to another,
from one chamber to another, from one bed to another,
from one practice and way of worship to another, and still keep them from the true,
living thing which their souls seek.

For were it possible for persons who did but so much as read in the Scriptures
concerning the power of life the saints formerly enjoyed,
the living ministry and ordinances, their sweet walking and fellowship in the light,
the presence of the spirit in their worship, and in their whole course,
their sincere love in the spirit, and tender bearing with one another`'s weaknesses,
doubts and differences, which he that reads singly cannot but pant after;
and the state of the gospel was not to be a decaying and dying in these things,
or a losing of them, so that the power of the Spirit,
and the revelations thereof should cease (as the whorish spirit,
which hath gone out from the life, pleads); but to grow and increase,
and the last times to abound most of all with the power and glory of truth: I say,
were it possible for persons who should read and
entertain the least taste and savor of these things,
to be satisfied with any of those dead ways and forms
which the whore hath set up instead of them,
unless they were wholly bewitched, and altogether deprived of their senses,
being made dead drunk with the whore`'s mingled wine in this dark night of apostasy?
Yea, professors are drunk, they have deeply drunk of the cup, and are sorely overtaken,
and their hearts overcharged with strong liquor;
which makes them even mad to draw others into their beds of fornication,
and to stand up themselves in great rage,
and call also to the magistrates for the defence of them.
Yea, like the clamorous woman, they make a great noise about ordinances, duties,
ministry, church, etc.
("`I have decked and perfumed my bed,`" saith the lewd woman, the subtle-hearted woman,
Prov. 7:16-17) but do not soberly consider which are painted ones, which the truth.
We have run on headily after these things too long;
it is now time to stand still a while,
and wait for the purging out of the wine wherewith all our brains have been overturned,
that we may come into soberness,
and into a fit temper to be led by the spirit of life out of the bed of fornications,
and out of the ways, worships, ordinances, and duties of fornication,
into the bed of the undefiled spirit.
Now he that worships God aright, must feel life within,
and that life raised and strengthened by him who begets it; and this will savor death;
and, faithfully following its guide, will come out of the land of death;
even that land wherein all the false worshippers inhabit,
and wherein all these false ways and worships, duties, ordinances, ministries, etc.,
are set up and flourish.

Now these secret sins of Babylon are the same with the more open and gross;
the great difference is their secrecy, their not appearing like sins, their paint,
their color, whereby they are swallowed down for holy and good.
As for instance:

There is fornication (or adultery from the life) in the finest,
in the purest way of worship man can invent or imitate:
but the fornication doth not so plainly appear here,
but they who have drunk of the cup take these things
for the ways and appointments of God.
Those that set up the whore`'s church, do not call it so, nor perhaps think it to be so;
those that set up the whore`'s ministry, or ordinances, do not give them that name,
but call them the ministry and ordinances of Christ: yet this is as truly,
as really fornication from the life, as the grossest ways of heathenish worship.
Oh mark it! mark it!

If thou hast read the Scriptures,
and thrust thyself into any practices thou there findest mentioned,
without the raising up of a living thing in thee,
and without thy following by the guidance thereof,
thou hast done this by the whore`'s advice; and in this thou art committing fornication,
and erring from the life: for the true worship lies in the spirit and in the truth,
and it is the new birth that God seeks to worship him;
but the spirit of man thrusting itself into these things, the Lord abhors and rejects.
And this spirit never can be thus cleansed, and fitted to enter into Christ`'s bed;
but only gets a paint from scripture,
and enters into the painted bed and bosom of the harlot, where it remains unrenewed,
unchanged, unmortified,
in the midst of all its great talk and profession of these things.
And thus the Scripture,
the holy Scriptures of truth (which were given forth from the pure spirit of life),
the whorish spirit maketh use of to estrange from the life.
For what sort of persons, which have fornicated from the life,
but make use of the Scriptures to maintain their whoredoms by,
and to bewitch others into their whoredoms with?
Every sort cries up their own way and worship to
be the way and worship according to the Scriptures;
and if any be gathered out of these witcheries into the power of God,
then the bewitched say that such are bewitched.

Then as for all the abominations of the earth, all the filth that defiles the heart,
it is to be found on the skirts of the whore, even in her most refined dress:
for her religion, her worship, her profession, her practices,
do not reach to the purifying of the conscience,
but only to paint over the old sepulchre, where rottenness lodgeth within.
The sore was never thoroughly searched;
the heart was never thoroughly circumcised or baptized; the old man was never put off,
or the new man put on;
the blood of purifying (which truly washeth away
the sin) was never felt in its virtue and power,
but only an apprehension and talk that they are cleansed in Christ,
from a notion they have stolen out of the Scriptures;
but not from the sensible feeling of the thing in life and power in their consciences.
And so the evil nature still remains,
the evil heart of unbelief is still to be found in them, and they want the life,
they want the power, they want the spirit, they want the love, they want the humility,
they want the meekness, they want the patience,
they want the innocency and simplicity of the lamb and dove.
And when the Lord comes to provoke them to jealousy by the shining of his light,
and by the appearance of his power in some whom they despise, then the pride,
the passion, the envy, the heart-burnings, the hard speeches, the false surmisings,
with the rest of the enmity which still abides with them,
stirs and rises against the life and power, and their hypocrisy is made manifest.
Yea, some of the strictest among them can scoff and jeer at the appearance of life;
so strong is the evil and unmortified nature in them,
and so conceited are they in their ways and practices, because of their cover,
under which all this iniquity, for the most part, lies hidden from their eyes.
But, for all that, it is there; the Lord`'s candle will search it out,
and thine own eye shall see it, and find in thyself bloody Cain, scoffing Ishmael,
profane Esau, the uncircumcised Jew;
who is angry that his brother`'s sacrifice is accepted, and his not;
who disdains and derides the true seed of life, the living heir;
who hunts abroad for food pleasing to that nature which is to be famished;
who crucifies the Lord of glory because of his meanness,
and because he appears not in that way of devotion and holiness wherein they expect him.
Neither will he appear so; but to overturn all that which ye have set up,
and to set up that which ye disdain.
This is the Lord`'s work, and it is marvellous in our eyes.

Now there are several sins which the spirit of the Lord hath charged Babylon with,
and which he will reckon with her for, and with all that partake with her therein;
some whereof I may mention, as: --

1+++.+++ Her deep fornications from the life,
under a pretence of honoring and worshipping of it.
(Be not offended that I begin with it again,
seeing it is also mentioned among other particular sins of hers.
Rev. 9:12) She speaks fair words; she calls to have the worship of God set up,
and a godly ministry, and the ordinances of God in a nation;
but the thing is not so in the sight of God,
but in all this she seeks the advancement of her own whoredoms.
And this was, and this is, the very way of antichrist`'s rising; he gets into the form,
he cries up the form; and by the form which he cries up, he eats out the power.
If antichrist should speak directly against the power (without first creeping into,
and setting up a form, and crying up that) he would soon be detected: but,
under a form and profession of truth, he hides himself,
and covers his spirit of enmity and persecution therewith:
and here he can secretly and safely smite the innocent,
and fight against that very spirit, life, and power, which he himself, in his form,
makes a profession of being subject to.
And this is the wolf in the sheep`'s clothing, which,
by this fair appearance of the sheep`'s wool on his back,
covers his ravenous nature from the eyes of the beholders.

Now there are three ways of fornication, one of which this spirit is always guilty of,
sometimes of them all.

1+++.+++ By inventing things which the Lord never commanded,
or adding to that which the Lord did command.
The mind of man is very busy, and full of inventions;
and where the heart is touched with devotion and zeal towards God,
the inventing part exceedingly exerciseth itself this way,
either in imagining and forming somewhat which it thinks may be acceptable to God,
or in adding to those things which it finds commanded.
In this way of fornication the popish church abounds,
being filled with ceremonies of their own inventing,
and of additions to such things as are found mentioned in the Scriptures.
The common Protestants also have been too guilty here.

2+++.+++ By imitating of those things which were commanded to others.
When a man finds in scripture the things which some others did,
or which they were commanded to do;
and so he is venturing upon them before he feels the leading
of that spirit whereby they were led thereunto.
Now in this he errs from the life; he goes without his guide;
he doeth that which was a good thing in others (who were led by the spirit thereto),
but in him it is fornication.
This man is a thief and an intruder; he steals into the outward knowledge and practice,
without the inward life and power:
he intrudes into that into which others were fairly led; not coming in by the right door,
for which entrance he should have waited, and not have run on headily of himself.
This way of fornication the strictest among the Protestants
have generally been ensnared in,
who have run on further and further to search out the purest way of worship,
the nearest pattern to the primitive times,
and so have applied themselves diligently thereto,
not knowing what they were to wait for to be their guide, and give them the entrance.
And here now, thinking themselves to be in the right,
they have contracted a lofty spirit (and held forth
their conceptions of the way as the only way),
and so have lost the meekness and simplicity,
which were fresh and lively in some of them before; which sets them a great way back,
and makes the entrance into the kingdom very hard to them.
Whereas if that simplicity and tenderness were fresh in them,
the Lord would show great regard to that, easily pardoning this their error, and,
in mercy to them, visiting that evil spirit with his judgments, which stood nigh them,
and was the cause of their error.
But they are grown high, they are grown wise, they are become confident,
they know the way already,
and can maintain it by undeniable arguments (as they think) to be the way; so the Lord,
with his teachings, is at a great distance from them; that lying very low in them,
which the Lord alone will teach.

3+++.+++ By continuing in practices, to which they were once led by the spirit,
without the immediate presence and life of the spirit.
For the whole worship, the whole religion of the gospel,
consists in following the spirit, in having the spirit do all in us, and for us:
therefore whatsoever a man doth for himself is out of the life, it is in the fornication.
If a man pray at any time without the spirit, that prayer is fornication,
and is not either acceptable to God, or profitable to himself; but grieves the spirit,
hurts the life, and wounds the soul.
Now this way of fornication have they especially fallen into,
who have been acquainted with the true leadings and openings of the spirit,
and have afterwards run to them for refreshment,
and so by degrees forgot the spirit that opened.
And by this means was that life,
which was precious and very savory in the ranters (before they were seduced
by the spirit of deceit into that way of ranting) overturned.
And thus they also (who deeply saw into the mystery of whoredoms,
and into the more inward ways of fornication above others),
even they also were deceived with the whore`'s cup,
and drank afresh of that wine of fornication which
the whore very cunningly had new mingled for them;
and they also are become a reproach to the inhabitants of Zion,
who find a living habitation in that spirit of life which they turned from.

Now if there be a true eye opened in any in the reading of this,
how easily and manifestly will he see whoredom, fornication, adultery,
generally in men`'s religious practices, in their churches, in their ministries,
in their ordinances, in their prayers, in their whole course!
Oh how, think ye, doth the eye of the jealous God behold these things! but your eyes,
who are held captive here, cannot see it.
The God of the world, with his mists, hath darkened you; the great whore,
with her sorceries, hath enchanted you; and ye are her slaves, ye are drunk with her cup;
and how can ye judge soberly either of your own estate towards God,
or concerning your practices in religion?

2+++.+++ Her notorious blasphemies.
Having fornicated from the life, and from the spirit, then she blasphemes the life,
and the holy, pure power and movings of the Spirit.
"`The woman which sat upon the scarlet-colored beast
(with whom the kings of the earth committed fornication,
and the inhabitants of the earth were made drunk with the wine of her
fornication) was full of names of blasphemy.`" Rev. 17:2-3. Yea,
the beast which carried her, which had many heads, horns, and crowns,
he also had on his heads "`names of blasphemy.`" Rev.
13:1. "`And there was given to him a mouth,
speaking great things, and blasphemies.`" ver. 5. And he,
with the whore together (for he did it by her spirit and instigation,
by virtue of the wine he had drunk out of her cup)
"`opened his mouth in blasphemy against God,
to blaspheme his name and his tabernacle,
and them that dwell in heaven.`" ver. 6. This hath been the work of the tongue,
in every head of the beast; namely, to blaspheme the life, to blaspheme the true,
living power, in all ages and generations,
since the apostasy from the life and spirit of the apostles.

Now there is a twofold blasphemy, which the whore,
and the powers of the earth that serve her, are guilty of.

1+++.+++ There is a speaking well of the ways of their own invention,
or the ways which they have imitated without the life.
To call these the ways of God, the true ways of life, is blasphemy.
"`I know the blasphemy of them which say they are Jews, and are not,
but a synagogue of Satan.`" Rev. 2:9. There were, even in the apostles`' days,
persons who pretended to be Christians, and pretended still to be of the church,
though they had lost the life; and this the spirit of the Lord said was blasphemy.
And what is their gathering into a church, who were never gathered into the life,
and setting up ordinances, and pastors?
What is this?
What is it for him to call himself a Christian, or inward Jew,
who never had the foreskin of his flesh cut off by the circumcising knife of the spirit?
What will the Lord say this is, when he comes to judge?

2+++.+++ There is a speaking evil of the truths of God.
The true knowledge, the true fear, the true worship, the true saints, the true God,
the true tabernacle, the true temple, the true heaven, (all which is in the spirit,
and is alone revealed and seen there) these are reproached,
these are misrepresented (and the true sight and acknowledgment of them called error,
heresy, and sectarianism) by all the blasphemers of Babylon.

Israel, who had the law and the prophets, the true ordinances and the true priests,
yet they "`called evil good, and good evil; they put darkness for light,
and light for darkness; they put bitter for sweet,
and sweet for bitter.`" Isa. 5:20. "`They were so wise in their own eyes,
and so prudent in their own sight; they were so mighty to drink wine,
and men of such strength to mingle strong drink (justifying the wicked for reward,
and taking away the righteousness of the righteous from
him),`" there was no convincing of them by the LIGHT of GOD,
shining from the prophets, of their "`casting away the law of the Lord,
and despising the word of the Holy One of Israel.`" ver. 21 to 25. Nay,
they were observers of the law, and hearkened to the prophets
and the priests of the law. Jer. 5:31.
Therefore, when the overflowing scourge came,
it should not come near them: yea,
when the true prophets of the Lord threatened them with his coming with dreadful vengeance,
and his strange work, they, in the height and confidence of their spirits, could reply,
"`Let him make speed, and hasten his work,
that we may see it.`" Isa. 5:19. How blind were they from seeing their blasphemies;
their calling of evil good, and good evil, etc.
Yea, in the very days of the apostles, the way of truth was evil spoken of,
and synagogues of Satan setting up,
and blasphemies growing up apace from those which held the true form,
but denied the power, even while the pourings-forth of the Spirit,
and revelations from the Spirit, did abound:
how can it be expected it should be otherwise now,
when the Spirit is grown such a strange thing,
that to mention such a thing as being moved by the Spirit, or acted by the Spirit,
is become ridiculous?
and the very teachers of the nation (who must speak by the Spirit,
if they speak the word of God) cry revelation is ceased,
and count it a reproach for a man so much as to pretend to speak by the movings,
and in the power, of the Spirit.

Now this double blasphemy necessarily follows the fornication:
whoever is fornicated from the life, he blasphemes the life, in all his knowledge,
in all his worship, in all his religion.
He calls that prayer which is not prayer; that an ordinance which is not an ordinance;
that a church which is not a church; that a minister which is not a minister;
and that which is indeed the prayer, the ordinance, the church, the minister,
he denies and blasphemes; and cannot do otherwise,
until the righteous judgments of the Lord purge the whore`'s wine out of him,
and he be led back to that life and spirit again,
from which (in all these ways of worship, inventions,
and imitations) he is gone a whoring.

The whore, for these many ages, hath been laying blasphemy to the charge of such as,
in any degree, have been led by the spirit of the Lord from her whoredoms;
but now the Lord is taking it off from them (who have long been unjustly charged therewith),
and charging it upon her, and she cannot escape his judgment;
for though she put on ever so fine dresses and appearances,
like the spouse and church of Christ,
yet the Lord can distinguish and find out his spouse, though naked in the wilderness,
and without her attire; and can also espy the whorish spirit,
though clothed with the church`'s attire; and can charge her blasphemies (against him,
his tabernacle, and them that dwell in heaven) upon her.

3+++.+++ Gross or more refined idolatries.
"`Little children,`" said John,
"`keep yourselves from idols.`" 1 John 5:21. He saw antichristianism breaking in apace,
many antichrists being already come; and now (saith he) keep to the anointing,
and keep from idols.
Without a very strict watch, without a mighty preservation by the anointing,
he saw idolatry would even creep in upon them,
who had tasted of the true power and virtue of life.
But how shall they keep from idols, who know not the anointing,
but think the revelations thereof are ceased?
He that buyeth not the tried gold of Christ,
(Rev. 3:18) how can he avoid buying untried gold of antichrist, or silver, or brass,
or wood, or stone, which his merchants traffic for, and make idols of? Rev. 9:20.
If thine eyes be anointed with the true eye-salve,
thou mayest see and read the parable.

Idolatry is the worshipping of God without his spirit (that is the plain,
naked truth of the thing).
To invent things from the carnal mind, or to imitate things, which others,
who had the spirit, did in the spirit, by the command of the spirit,
for thee to imitate and practise these without the spirit, is idolatry.
An invented church, an invented ministry, an invented worship; an imitated church,
an imitated ministry, an imitated worship, without the life, without the spirit,
all these are the work of men`'s hands, and are idols,
and all that is performed herein is idolatry. Rev. 9:20.
This is a religion without life, a worship without life,
a fabric for idolatry; and the whole course of worship and service in it, is idolatry.
For the living God, the Lord God of endless life and power,
is alone worshipped by his spirit,
and in the truth of that life which he begets in the heart; and all other worship,
though ever so seemingly spiritual, is idolatrous.
Ah! professors,
professors! if ye knew how many idol-prayers and services ye have loaded the Lord with,
and how ye have been whoring from him, while ye have seemed to be drawing nigh to him,
ye would hang down your heads and mourn! for whatever ye have done in the worship of God,
without the leading and presence of his spirit, it hath been idolatry.
For the worship of God, under the gospel,
"`is in the spirit and in the truth,`" and required
of them who are in the spirit and in the truth,
and not of others. John 4:23.
For them alone the Lord seeketh to worship;
and the Lord will admit of none to his worship, but such as he seeks.
And if any else will thrust themselves into his worship, it is not accepted;
nor do they worship the true God,
but they "`worship they know not what;`" and their whole state
and course here is a state and course of idolatry.

4+++.+++ Sorceries, witchcrafts, divinations,
and enchantments (I do not mean outward sorceries or witchcrafts;
they are but the shadow or figure of the inward mystery of deceit of this black,
dark spirit, which appears as an angel of light, that he might bewitch and deceive).
"`Neither repented they of their sorceries.`" Rev. 9:21. This false church,
this adulterous woman, she hath her golden cup, and her wine mingled;
and with this cup she bewitches the eye, with this wine she inflames the heart,
and intoxicates the brain.
She invents ways and worships like to the true,
or she imitates the true ways and appearances of life; and when the poor,
simple young man is singly seeking after God, from some true touches of his life,
before he comes to know the spirit of life, before he can come to be married to the Lamb,
she comes with her golden cup, and with her tempting wine,
and bewitches the poor heart therewith, and so leads it aside into her painted bed.
Wouldst thou enjoy God?
saith she.
Wouldst thou worship him aright?
Wouldst thou have fellowship with him?
Lo, here is the way; here is the church; here are the ordinances; here is the ministry;
here are the means.
Thou must wait upon God in the use of the means, and these are they.
Did not the saints formerly do thus?
Did not they meet with God here?
Did not they serve and worship God thus?
Come thou hither also; do what they did; enjoy what they enjoyed.
Yea, but thou whorish woman, did ever God appoint means without his spirit?
Thou leavest the main, yea, indeed, the only thing behind thee,
which itself alone is accepted, and without which nothing is accepted.
And this is the course of the whore; in all her transformings, in all her baits,
in all her temptings, she still leaves the spirit behind her.
She may perhaps speak of the spirit,
to hide herself the more (because the letter of the scripture is so express therein);
and teach people to look and wait for the spirit, but so as it never is to be obtained:
for he that begins in religion either to pray or worship, or seek the knowledge of God,
without the spirit, shall never meet with the spirit so; but that way of knowledge,
religion, and worship of his, must first be broken down, and he become a fool,
and receive the spirit as a fool (out of all his religious
knowledge and wisdom which he had gathered before);
and afterwards, following the spirit which is thus received,
he shall be led into the true wisdom.
Now mark that which follows, ye that have a desire to understand.

This spirit of deceit, this whorish spirit,
this spirit of divination and witchcraft ("`which by her sorceries deceived
all nations,`" Rev. 18:23) came forth curiously decked at first,
with all manner of deceivableness of unrighteousness.
It had the exact form of life (the true form of godliness) and a lively spirit in it:
it had the form of knowledge, and the form of worship, and with these it came to tempt,
and draw away them from the life and from the power
who were in the life and in the power;
and it did prevail upon such as kept not close to the anointing.
But after it had overcome, and gained the church`'s territories,
then it might safely corrupt the form; and so it did,
and went into multitudes of inventions and fopperies
(as at this day may be seen amongst the Papists).
Now these are easily discovered, and seen through by any simple, plain, honest eye,
upon a little breaking forth of the light.
Therefore the whorish spirit, when she perceives herself found out here,
she changes her shape and attire,
and comes back again by degrees (as need requires) to the forms of knowledge and worship,
wherewith she was arrayed when she deceived at first: yet still she is the same,
and doeth this to keep poor, simple hearts still in her bands,
from the life and from the spirit.
And thus painted, thus decked,
thus holding forth scripture-knowledge and scripture-ways of worship,
she is the more subtle witch, the more subtle sorceress, and is able to deceive any eye,
but that which is opened in the light.
With her "`Lo, here is Christ, and lo, there is Christ,`" she would deceive the very elect,
if it were possible; but it is not possible:
for they are taught by the spirit not to go forth,
and the anointing within preserves them.
And he that knoweth not this preservation is bewitched by her;
and his fear of God is such as may be taught by the precepts of men,
and practised without the knowledge of the law of the spirit of life in Christ Jesus,
which is the saints`' rule, guide, and preservation.
For as the apostles were "`able ministers, not of the letter,
but of the spirit of the New Testament,`" 2 Cor. 3:6. so they that received
their ministry (or that which they ministered) received not the letter only,
but the spirit; and were preserved not by the letter, but by the spirit,
and were made able to try words, things, and spirits, not by the letter,
but by the spirit.
But this the whorish spirit is departed from, and bewitcheth others from;
first possessing them that the spirit is not to be looked for,
and then persuading them to make as good shift as they can without it:
and then (having thus prepared people) she brings forth her wares.
Look ye, saith she, this is the way; thus and thus the saints practised;
do thou thus also.
But thou must receive the saints`' spirit before thou either know or worship;
or thou knowest and worshippest out of it:
and in that path of sorcery and witchcraft from the life,
thou shalt never meet with the life; but the further thou proceedest therein,
wilt be more and more estranged from it,
and become still a greater and greater enemy to it,
and more and more in love with the whore,
and her whorish paths and pleasing ways of devotion,
whereby the false spirit in thee is raised up and nourished;
not with the bread of life from the hand of the spirit, but with words,
or forms of knowledge, or ways of worship invented, or imitated;
which do but tickle the understanding, or affectionate part of man,
but reach not the life; so that that which should serve the Lord, is there not raised,
but still bound over with the bond of iniquity.

5+++.+++ Luxury, excess, and pleasure.
She is rich with her merchandize, and she enjoys it to the full,
she takes the pleasure of it.
She builds costly houses, wears rich apparel,
fares deliciously (read spiritually with the spiritual eye).
She is rich in knowledge, rich in ways of worship, rich in duties,
rich in religious performances and practices.
And as she gained these in her own will (without the leadings
of the life) and by her own search and wisdom;
so she can make use of these in her own will,
and according to the direction of her own wisdom.
She can fast when she will, give thanks when she will, preach when she will,
pray when she will, sing when she will, meditate when she will,
bring forth her knowledge to others when she will.
Look on the Papists; how rich are they in outward buildings, in gorgeous ceremonies,
in times of worship, in ways of mortification and penance, in fasts, in feasts, etc.
Look on the several sorts of Protestants; they have their riches in their kind too;
their churches, their buildings, their arts, their sciences, their languages,
their bodies of divinity, their cases of conscience, etc.
They can open the whole body of religion, resolve all doubts, expound all scriptures, etc.
"`The great city was clothed in fine linen and purple and scarlet, and decked with gold,
and precious stone,
and pearls.`" Rev. 18:16. And she sat thus on the throne like a queen,
living deliciously, and taking her pleasure,
to which her torment and sorrow afterwards are proportioned.
ver. 7. Yea,
she had treasure and costliness enough to make all
her merchants rich that would trade with her.
ver. 19. What knowledge, what delicate food,
could the wisest or greatest of the earth desire, which she had not ready for them?
(see ver. 3, and ver. 9). But Zion, all this while, hath lain in the dust,
and been despised: she hath had no building, no fence,
but hath been trampled under foot by every unclean beast:
her witnesses have been clothed with sack-cloth (a garment
which all the lofty inhabitants of Babylon disdain):
her fare hath been hard in the wilderness, only a little manna (which,
with the fleshly Israel, who lust after rich and large knowledge, is counted light bread,
and their souls soon loathe it): nor had she this in plenty,
but only a small proportion daily, from the hand of the free Giver,
sufficient to keep life in her in the wilderness,
and to furnish her with strength to give in her testimony against Babylon,
so far as the Lord saw good to call any of her seed thereunto.
Now what professor can be willing to fare thus with her at present,
and to wait for her future riches, fulness, beauty, and glory?
Nay, nay; they have so long lived richly, and fared deliciously in Babylon,
that they know not how to eat the bread of affliction, and drink the water of affliction,
with sad and desolate Zion:
and yet this is the only way and passage out of Babylon into Zion.
That which hath been rich and fat, and full-fed there, must become poor and lean,
and feel hunger, and have none of the bread of life administered to it; no,
not so much as husks either.
And in this sad day, and state of misery, the poor are visited, which receive the gospel;
and the dead raised, which receives the life.

6+++.+++ Worshipping of the devil.
"`All the world wondered after the beast,
and they worshipped the dragon.`" Rev. 13:3-4. Now the dragon is the devil. Rev. 20:2.

There is no other worship of God under the New Testament, but in spirit and truth;
and he that worships otherwise, worships not God,
but that spirit which teacheth to worship out of God`'s spirit, and out of the truth.
Every prayer is not a prayer to God, but only that prayer which is from and in the spirit.
Every ordinance, or duty, is not an ordinance of God, or a duty performed to God;
but only that which the spirit leads into, and guides and preserves in.
This is the way that all the earth have departed from the Lord; namely,
by erring from his spirit.
They cry up practices in religion; duties, ordinances; the means, the means; a church,
a church (as the Jews did "`the temple of the Lord,
the temple of the Lord;`") but they find the church,
before they have found the spirit of the Lord;
and so they find not the church that is in God, the church that is of his building;
but they, poor hearts! frame up a building as well as they can,
according to the pattern they find in the Scriptures;
and so they are not a habitation for God in the spirit,
but are estranged from the life and spirit in all their worship;
and so are not found by the spirit (which searcheth
them and their worship) worshipping of God,
but "`the works of their own hands,
and devils.`" Rev. 9:20. For that charge holds
good against all the inhabitants of Babylon,
even to the highest and strictest of them all, whether in forms, or out of forms.
There are many men, who are very zealous and devout in their ways of worship,
who were never taught by the spirit the way of worshipping God,
nor do at all know how to worship in the spirit: these my soul exceedingly pities.
They have received into their understandings, from the letter of the scripture,
that God is to be worshipped in spirit,
and that God will give his spirit to them that ask it.
They have asked, and they hope that they have the spirit; but poor,
deceived hearts! they know not what spirit they are of, nor in what spirit they act,
nor what spirit they serve; and so perish for lack of knowledge,
the key whereof hath been hid from them.
Now let such consider:

There are but two spirits; the spirit of God, and the spirit of Satan:
one of which guides all men in their devotion and religion,
and one of which they serve therein.
He that is led by the spirit of God; he serves God, he worships God:
he that is led by the spirit of Satan; he serves not God,
but that spirit which appears in the temple of God, like God,
and gives such demonstrations that he is God, as no flesh can deny. 2 Thess. 2:4.
Here now is the great deceivableness.
In profaneness, in manifest wickedness, Satan is easily seen;
and men that are found here, it is granted that they are serving the devil:
but that he should sit as king in gathered churches, in duties, in ordinances,
in ways of self-denial and mortification, and be worshipped here,
this is hard to be seen: yet any of these which the spirit of the Lord leads not into,
or which are performed at any time without his spirit, he is worshipped in.
Consider this, ye that are wise in religion, and are diligently reading the Scriptures,
and gathering knowledge, and rules of worship, and applying promises, etc.
Do ye this in the life and spirit of God?
or in your own wisdom, and according to your own understanding?
Doth not the wisdom of that spirit, which is out of the truth,
guide you in your searchings after truth?
Oh, do not serve that spirit which the Lord hates, but come back to that, from which,
in all this, ye err, and which, in all this, ye cannot serve and worship.
And let not your religion any longer consist in mere practising what the
saints formerly practised (for that ye may do without the same spirit),
but in yielding up to that life, power, and pure spirit that they were led by.
And when ye are joined to this, then do not prescribe the Lamb the way that he should go,
but "`follow the Lamb,
whithersoever he goeth.`" Do not tell the Shepherd (by your
gathered wisdom) the way that he must lead you in;
but know the voice, and follow it; for this I can truly testify,
that if once ye come in faithfulness and true light to follow the Lamb,
he will lead in paths ye have not known, and out of the paths ye have known.

7+++.+++ Compelling of others to worship. Rev. 13:15-16.
The false woman and the beast set up a worship in the will,
and they do not know why any in the will also may not be subject and submit to it.
They can give them reasons, they can give them arguments from scripture;
and if they will not yield to these,
they are to be looked upon as stubborn and refractory,
and to be compelled by outward force.
This hath been the course generally throughout the land of Babylon;
but these show hereby that they themselves are erred from the truth
(and therefore very unfit and unlikely to teach it others):
for that which God works upon is the conscience,
which he convinceth by the light of his spirit; and no other light can truly convince it.
That therefore which would have a man yield to any practice, or way of worship,
till he be truly convinced, is of the devil.
"`My son, give me thy heart,`" saith Christ, the wisdom of God:
come not to me with oblations and sacrifices, but give me thy heart.
My son, give me thy knee, give me thy obedience to the ways I have set up,
give me thy conformity, saith antichrist, saith the adulterated wisdom:
and if any refuse, she endeavors to compel them.
Thus, like "`Jeroboam the son of Nebat,`" she makes (that which she calls) Israel to sin:
or, like Nebuchadnezzar, she sets up an idol, and causeth all her children to bow to it.
Thus the load of the iniquity of multitudes lies upon that scarlet whore,
who forces her cup of abominations and filthiness upon all she can, Rev. 17:4.
causing all, both small and great, in all her territories,
to receive her mark, and worship her image.
The work of the minister of Christ is to keep the conscience tender,
that the voice of Christ may be heard,
and the law of his spirit of life (which makes obedient
to the God of life) spring up there:
but this is the image, here is the way, bow, conform, say the ministers of antichrist.
But we are not convinced in the sight of God that this is the way, say poor souls.
It is your own fault; ye may be convinced if ye will, say the ministers of antichrist;
we are ready to give you arguments and scriptures to convince you;
how is it ye are not convinced?
Ye must be convinced, otherwise the magistrate must deal with you.
Thus they endeavor to harden the conscience, that they may sit upon it and ride it,
and terrify it from its subjection to its only true and lawful king.
Oh, the havoc that hath been made of souls by this means!
the Lord is requiring it of this generation.

But let me put this question to all the learned and wise, in all the regions of Babylon,
under what painted form or way soever.
Can any worship God aright, before they be truly convinced of his will and way?
Can any be convinced without his light and spirit?
Were it good and acceptable in the sight of God, for any persons to run into that way,
whereof thou sayest thou art convinced that it is the way,
before they themselves are convinced?
If it be not good and acceptable, what is that which goes about to compel them?
Away with thy carnal weapons; and if thou wilt draw to God,
draw by that which is spiritual:
but if thou wilt still be using outward force (running to the laws of men,
and power of the magistrate), the Lord hath opened an eye,
which discovers thy nakedness herein,
and is able to make it manifest in the sight of all people;
and thou shalt not long cover thy shame.
The Lord`'s people shall "`be a willing people,`" to follow him "`in the day of his power;`"
but all the Lord`'s people have been unwilling to follow thee in the day of thy power,
which is near an end; and the very fountain of thy deceit,
and tyranny over the conscience, is opening and making manifest.

8+++.+++ Persecution of such as she cannot compel to her worship.
She sets up her form of knowledge, she sets up her way of worship,
and those that will not be drawn to own the one, and practise the other,
she sets her brand upon them for erroneous persons, schismatics, heretics;
they must not "`buy or sell.`" Rev. 13:17. They must be banished or imprisoned,
or perhaps put to death; for she is hardly satisfied,
till she hath drunk the blood of those, who, in any eminent degree,
are the witnesses of Christ against her. Rev. 17:6.
This was a thing wondered at by John, with great admiration;
to see this woman, this great city,
out of which all the venomous darts are shot against the saints and martyrs of Jesus,
under a pretence of zeal for the church and ordinances of Christ.
For this is the engine, whereby the dragon makes war with the true woman`'s seed,
(which keep the commandments of God, and have the testimony of Jesus Christ),
even by this false woman which rides on the beast,
by whose power and strength she overcomes the saints.
She sets up a way of doctrine, a way of worship in a nation,
and gets laws made for the defence of it, and against them that will not submit to it;
and here she is too hard for the saints;
by this means she overcomes the martyrs and witnesses, and keeps the truth down,
and keeps up her way of deceit; which, without this prop, would soon fall.

This whorish spirit scents the spirit of the Lord; she knows it will soon be her death,
if she cannot make it appear odious, and suppress it: therefore she hunts this spirit,
she hunts the life and power of what she herself professes
(especially if it appear vigorous and strong in any);
she seeks advantages against the servants of the living God,
representing them to the earthly powers as persons of dangerous principles and bad practices,
inventing all manner of what can be called evil against them,
and spreading it among the people, that the truth may start up nowhere in the earth,
but everywhere be knocked down by the violence of the multitude,
or by the sword of the offended magistrate.
Now what is the matter of all this great noise and fury?
Why this; A lamb is risen up in the innocency;
the pure harmless spirit is appearing in the earth;
the true life (which discovers the hypocrisy,
and dead forms and ways of the whorish spirit) is breaking forth:
therefore she makes a great outcry: Awake, people! awake! the church is in danger: arise,
magistrates! magistracy and ministry will down, if this lamb-like spirit be suffered.
Nay, nay: these shall stand, but Babylon shall fall,
and her mystery of iniquity be discovered,
and her deceivableness of unrighteousness made manifest;
and the true life and spirit shall arise and take possession of the hearts of people,
and make them a clean and fit habitation for God: and people that are subject hereto,
shall feel it, and enjoy it; though the merchants of Babylon say,
men shall never be made clean while they live,
but must still have a body of sin and death hanging about them.
But how shall they put on Christ, who have not put off the body of sin?
Shall those who are made kings and priests to God here on earth,
minister in their filthy garments?

These are some of the sins of Babylon, that painted harlot, which is subtle in heart,
and lies in wait to deceive, in the absence of the true church,
whose clothing and resemblance she takes up, and appears in.

And when she had done all this; when, like Egypt,
she hath kept the seed in bondage in all her territories and dominions,
in every church she hath set up, and by all her ministries and ordinances; when,
like Sodom, she hath filled the whole world with filthiness, uncleanness,
and all manner of spiritual abominations; when, like old Jerusalem the bond-woman,
she and her children have scoffed at the spirit in every appearance,
all the time of her reign, and have trampled upon and domineered over them,
who have but spoken of the coming of the just One in his people,
sporting herself in her own deceivings; yet, after all this, she wipes her mouth,
and saith she hath done no harm; she hath been for the gospel, and church, and ministry,
and ordinances, and the faith once delivered to the saints, and only against deceivers,
seducers, blasphemers, and heretics.
But the spirit of the Lord cannot be thus deceived;
nor shall the nations be always thus deceived,
and suffer her to sit as a queen upon their consciences; but she shall see sorrow,
and they shall taste joy at the sound of the everlasting gospel,
when once again it cometh to their ears.
Rev. 14:6 and chap.
19:6-7.

=== THE JUDGMENT OF BABYLON

BABYLON the great, this great city of abominations,
which hath reigned over the whole earth,
which hath bewitched all sorts of professors with the golden cup of her fornications,
which hath subtly led from the life,
and held all sorts captive in the witchery of her deceit,
and hath triumphed over the holy seed, making Zion, their mother, desolate,
who sat in the dust, and was trampled upon by her: this great city, this glorious city,
this rich city, this mighty powerful city,
this queen of the earth (which knows not what belongs to Zion`'s misery, sorrow, poverty,
and desolation),
with antichrist her king and husband (who hath clothed
himself with the garments of light,
and appeared in the likeness of the king of Zion,
and hath long been so acknowledged and worshipped),
is to be judged by the spirit of life, which ariseth up out of the dust of Zion.

And though Babylon,
the great whore (who in all her transformings hath still remained an enemy to the life),
hath great power and great wisdom, and can shift very subtly to save herself by both;
yet strong is the Lord God who judgeth her, and he also is wise;
and she shall not escape his hand, but he will pursue her with his voices,
with his thunderings, with his hail-stones, with his earthquakes, with his woes,
with his plagues, with his cups of indignation, till he hath made her manifest,
till he hath broken her in pieces, till he hath crumbled and laid her in the dust,
till he hath brought her down to the very pit,
where the feet of Zion shall trample upon her forever.
Sing, sing,
Oh inhabitant of Zion! doest thou not behold the crown of pride going down apace?
The decree is sealed against her; she cannot escape; yea, she is fallen, she is fallen;
she is already taken in the snare; the eye of my life seeth it,
and rejoiceth over her in the living power.

The plagues of God Almighty, from the fierceness of his indignation,
are visiting her whole territories, and passing over all her land.
Nothing can help her to avoid his stroke; no paint will serve, no cover will hide,
no profession, no practice, no duties, no ordinances, no church, no ministry,
can avail to conceal her; but that spirit is pursued by the spirit of the Lord,
and found out everywhere, and plagues are prepared and pouring out upon her.
Nay, though she leave all her forms, and pretend to wait and seek for the Lord;
yet she is found out there also.

Now what is her judgment?
Destruction and utter desolation from the hand of the Lord;
to be a hissing and reproach throughout all generations;
to be brought down (by pourings-forth of the wrath
and vengeance of the Almighty) into the pit,
and there to drink the fulness of his wrath forever.
Zion shall be exalted; Zion shall drink the cup of life, the cup of blessing,
the cup of love, the cup of salvation forever: but Babylon the cup of fury,
the cup of indignation forever and ever.
Zion shall sing; but Babylon shall howl: and all that saw any beauty,
or took any pleasure in her, shall mourn over her.
Alas, alas, for her! she who hath so many ages gone for the church,
is now proved to be the whore; those who have been taken, in their several transformings,
for the true ministers, made manifest to be the false prophets;
their ordinances and duties, but thefts and imitations;
things which they have stolen from what they read in the Scriptures,
but never received from the hand of the spirit.

The wrath of God, the dreadful cup of his fury,
and jealous indignation for the cause of Zion, is to go over her whole land,
over her sea, and all the ships that trade therein, and all her merchants,
with all her precious traffic and merchandize.
All her doctrines which she hath stolen out of the scripture, all her disciplines,
all her experiences,
all her performances (even those which are most like
the performances of the former saints);
nay, though she may speak the very words of truth, yet as they come from her mouth,
they shall be thrown by and judged, and be of no service or esteem in Zion.
The preciousest of her ware shall be dross and dung in the land of life,
where there shall be no sea, and no such kind of merchants, traffic, or trading forever.

Her earth also shall be made desolate, and burnt up, with all that is found therein;
all her settlements shall be shaken; all her fruit-trees shall be rooted up;
all her fruit shall wither, rot, die, and perish.
All her conversions of people to God, as she calls them, shall come to nothing: yea,
and if she have yet any more dresses, or secret coverings,
wherein she would appear like the church again, and bring forth again;
yet she and her children shall immediately be discovered, her flesh burnt with fire,
and her children dashed against the stones.
Every street in her city, every house and idol in every street,
every room in every house, with every inhabitant, shall drink of the cup of astonishment,
and stumble and fall, and rise no more.
"`Thou hast long triumphed over me, O mine enemy! because I have fallen,
and have long sat in darkness; but rejoice no longer; for I shall rise again,
and the Lord shall be a light unto me: but thou shalt rise no more,
and thy light shall be put out forever.
Glory to the meek, suffering Lamb,
even to him that sits upon the throne of life forever.`"

Her air also shall be darkened.
The Lord shall enlighten my darkness;
but the light of Babylon shall be darkness forevermore.
"`The light of a candle shall be seen no more at all in thee.`"
Many lights hath Babylon set up in the dark night;
but the rising of the Sun of Righteousness shall extinguish them all forever,
and Babylon shall be shut up in utter darkness.
Yea, all that have retained to Babylon,
all that have walked by the light of any of her candles,
that have cried up any of her false ware for orthodox,
that have given up their names to her under any of her dresses or appearances,
or that have received any of her marks, they shall partake of her shame, of her misery,
and of her torment, from the hand of the Lord God.
Yea, her throne also shall be visited,
and the seat of antichrist in every heart shall feel the wrath.

Rise up from the dust, and shout forth with joy, O captive daughter of Zion,
who hast long dwelt under oppression, in the midst of the daughter of Babylon.
Behold!
Babylon`'s king shall be no longer judge over Zion; but thy King shall be judge,
and he shall judge the king of Babylon:
and let all the powers and potsherds of the earth strive to their utmost; yet,
saith the Lord,
"`have I set my king upon my holy hill of Zion,`" and he shall rule in my people,
and rule over Babylon.

Learn, therefore, O inhabitants of the earth, great and small, meekness;
learn righteousness; learn the fear of the Lord; kiss the Son;
harden not yourselves against him, calling him a deceiver, a blasphemer, a seducer,
a heretic (for what ye do to the least that appear in his life, ye do to him):
but hearken to the word of his everlasting gospel, which saith, "`FEAR GOD,
AND GIVE GLORY TO HIM,
FOR THE HOUR OF HIS JUDGMENT IS COME;`" and ye cannot escape his
hand by that fear which is taught by the precepts of men,
or by traditional knowledge out of the Scriptures;
nor while ye seek that honor which came out of the earth, and is of the earth,
and to that which is earthly.
Therefore let your hearts learn to know him, and your tongues to confess him,
and your knees to bow to him; which if ye do, ye must forget all that knowledge,
and those confessions and bowings, which ye have learned in Babylon;
for though ye may have confessed some true things,
yet (having learned this in Babylon) ye have confessed falsely; even as the Jews,
who said, "`the Lord liveth,`" yet swore falsely. Jer. 5:2.

Now consider, ye ministers of several sorts, and ye several sorts of professors:
we may appear great enemies to you, because we witness against your ways,
and tell you what the end of them will be; but are we enemies to you indeed,
whose desire it is to save you from this great wrath,
which hath already entered into the earth, and seized on some?
Should we soothe you up, and not witness these things to you (which we infallibly know),
how should we answer it to the Lord our God, or to your souls,
when we shall appear before him?
If we were in your condition, would we be content to be let go on,
and to be overtaken with this great destruction?
We cannot be silent.
Ye must be silent; but we cannot.
We know ye must be silent; for that which now speaks in you, hath been silenced in us,
and is not to minister the things of God.
But the spirit of the Lord must not be quenched in us, notwithstanding all our weakness;
but the treasure must issue forth from the earthen vessel,
for the relief of the poor in spirit, who alone receive the gospel.
Therefore, though ye hate us, though ye persecute us,
though ye speak all manner of evil against us, and use us ever so hardly;
yet there is love rooted in our souls toward your souls, yea,
and toward your persons also: and having both felt the wrath, and tasted of the mercy,
we cannot but warn you of the one, and invite you to the other.
And oh! that ye might find a shelter under the shadow of his wings in the stormy season,
when wrath shall be showered down without mercy!

And this we cannot but tell you,
that the several ways of religion in the Christian world are but so many several coverings;
and that that which is covered with them is the whorish spirit,
which the spirit of the Lord is hunting; who will strip her, and make her naked,
and she shall appear to have been the whore under them all.
Now that which lieth beneath this spirit in you,
which is despised and trampled upon as a thing of nought,
which is burdened and daily slain by your multitudes of ordinances, professions,
and religious practices; this is the heir of life;
and by the raising up and living of this in you, may ye come to life, and no otherwise.
And all religion without this, even the most inward, is but the deceit of the whore,
who makes a great show of worship, and zeal toward Christ,
his ordinances and ministry (as she calls them); but by all these, and under all these,
holds the life in bondage, and strives by all means to slay the heir,
that the inheritance might come to her son.
But Cain, the sacrificer; Ishmael, the son of the bond-woman; Esau,
the hunter abroad after venison; the Jew, full of profession, zeal, ordinances,
and worship, shall not inherit: but slain Abel shall be raised to life:
Isaac (who was born of the dry and barren womb) shall have the promise; plain Jacob,
the blessing; the out-cast Gentile be sought out.
Thus it shall be; can ye read it?
Yet it is the desire of our souls that a remnant of you may be saved,
and now is the gathering.
Therefore seek humility, seek poverty of spirit, seek the suffering seed, the meek,
innocent, harmless, dove-like nature, even the love which doeth no ill,
nor thinks no ill; for this is the spirit which is to be gathered:
but the high and lofty, the wise and knowing, the fat and strong,
the rough and confident, in their wisdom, and in their duties, churches, ordinances,
etc., (which they have gathered and stolen from the Scriptures,
out of the life) are with all these to be rejected,
and to be shut up in blindness and hardness of heart.
"`Seeing they are to see, and not perceive; and hearing, to hear, and not understand;
lest they should be converted, and healed.`" Yea,
it is this spirit which is to fret under its pain and torment from the woes and plagues;
but cannot repent, but passeth on with Babylon to ruin and destruction. Rev. 16:9-11.
"`Babylon is become the habitation of devils,
and the hold of every foul spirit, and a cage of every unclean and hateful bird.
Come out of her, my people, that ye be not partakers of her sins,
and that ye receive not of her plagues.`" Rev. 18:2,4.

This is the cry concerning Babylon just upon her fall.
Her iniquity is full, her filth overflows, the pure seed is gathering out of her,
and nothing but devils and foul spirits, and unclean, hateful birds, remain in her.
And the call still is to the people of God, from one remove to another,
from one part of Babylon to another, to travel on, and pass away still,
till they come quite out of it all.
To come out of one part of Babylonish worship, that is not enough;
or to come out of some pieces of Babylonish knowledge and wisdom,
will not answer the call; but ye must come out of it all.
"`Depart ye, depart ye; this is not your rest,
for it is polluted.`" Stay not in any part of the unclean land,
O child of the pure life! but be separate, and touch not the unclean thing,
if thou wilt have the holy One to receive thee.
Not only the several dresses and forms of the whore are polluted; but her spirit also,
and all her inward fabric of religion, out of which thou must also come,
if ever thou be joined to the pure life.
Thy faith, thy hope, thy love, thy patience, thy joy, thy peace, thy justification,
thy sanctification, thy mortification, thy ability to pray, to give thanks, to wait,
etc., all must down, all must suffer loss, all must become dross and dung to thee,
that thou mayst know the building of true life from and in the spirit.
For the Lord will not own any of these,
nor receive thee with any of these which the whore hath touched;
but if thou wilt have the pure life, both within and without,
thou must part with the corrupt life, both within and without.
This is a faithful and true testimony; but who can receive it?
Will not both the houses of Israel be offended, and stumble at it?
But if any of the people of God will abide still in Babylon,
and not hearken to every call of the spirit of the Lord,
to follow its guidance out of every part of her,
they shall receive (from the impartial hand of the Lord) of her plagues,
and have torment and sorrow proportionable to the
glory and pleasure they have had with her.
Therefore, if after one, two, three,
or many removes out of some parts and practices of Babylon, the voice still follow,
crying, "`Come out of her, my people`" (the spirit of antichrist is yet among you,
the wine of fornication from the pure life is not yet purged out of you),
do not stop your ears, thinking this belongs not to you,
because ye have forsaken some paths which are antichristian; but hear and follow;
for it is your life, and your way to rest and peace in the land of the living,
and your sure preservation from anguish, perplexity,
and misery in the hour of Babylon`'s judgment and sore distress.

==== AN OBJECTION ANSWERED

Now there is one thing which lies as a great block in the way,
to hinder this testimony from entering into the hearts of those to whom it is directed,
or at least to weaken the spirit`'s demonstration of it to their consciences
(for exceeding subtle is the whorish spirit to keep every one of her subjects
from the sight or suspicion of her in themselves,
and to darken every beam of light,
whereby it pleaseth God to make any way for the discovery of her in them), which is this:

Object.
But hath all our religion, for these many ages, been Babylonish,
and whoredom from the life?
All our churches, all our ordinances, all our duties, all our ministry, etc.
We can never be drawn to believe this.
We are sure we have felt lively touches from God many a time,
and enjoyed sweet communion with him in them.
God hath often met us there, and refreshed our spirits; which he would not have done,
had they not been of himself.

Ans.
There hath been a simplicity and sincerity of heart, stirring in some people towards God,
in all ages: even among the heathen, under all their idols; and among the Jews,
in the midst of their great apostasy: which simplicity is of God,
and acceptable with him,
notwithstanding all the load of filth that may hang round about it.
Even in the midst of Egypt, or in the midst of Babylon, if Israel groans, the Lord hears,
and may return sweet answers to Israel, even there.
"`When Israel was a child, I loved him,
and called my son out of Egypt.`" The lowest breathing
of true life towards God is the voice of his Son,
and enters into his ear from the darkest part of Egypt or Babylon.

Now in this nation the simplicity hath more stirred than in other nations;
the seed of God in this land hath been exceeding precious and dear to him.
And at the beginning of these late troubles,
the stirring of the simplicity from the pure seed was more
vigorous and lively than it had been in many ages before;
and accordingly the answers of God to it were more fresh and sweet;
and there was a taste of him, and fellowship with him,
and sweet hopes and refreshments to the soul.
Though the way of praying, preaching, and worship, either public or private,
was not right before him;
yet he overlooked that which his soul hated (winking
at the time of ignorance and antichristian darkness),
and met with that which he loved.
And if the simplicity had grown and thriven, communion with God, and life from him,
would have increased,
although the pure path of the sanctuary had not yet been made manifest.

But this was it destroyed all; another thing got up under a cover,
and the simplicity sunk; and so the life withdrew,
and God hath grown strange to his people.
He missed that which he loved, and came to visit; he found that thrust upon him for his,
which his soul cannot own or unite with; and so he became but "`as a wayfaring man,
that turneth aside to tarry for a night.`" Jer. 14:8. Enter into your hearts,
O ye backsliding children! is it not thus?
You who had sweet tastes of God, is he not become a stranger to you?
You that had sweet, fresh, lively breathings after God, are you not set down in a form,
or under some pleasing notions, and have got a covering,
but lost the simplicity of your life, and the sweet tastes of God,
and refreshments from him?
Thus it hath been in all reformations.
There was commonly a pure, single, naked beginning;
but an evil thing soon got dominion over it, slaying the pure,
living stirring by the form which it raised up,
under a pretence of preserving the life thereby,
and of serving God more uniformly and acceptably therein.
Ah! the precious seed that was sown at the beginning of these troubles!
What is become of it?
How is every one turned aside from the pure life,
into some idol or other of his own heart! some into one way of worship,
and some into another; some into one notion, and some into another;
and all joining together to keep the seed in bondage,
endeavoring either to bring it back again to Egypt (to make it serve there),
or to destroy and bury it in the wilderness.
But the Lord hath visited this poor, desolate seed,
and hath been gathering it from all quarters;
from amidst all empty forms on the one hand, and all vain,
high notions on the other hand; and he will preserve it, overturning all his new enemies,
as well as his old.

This then is the sum of the answer.

1+++.+++ No way, or particular act of worship, under the New Testament, is acceptable to God,
without his spirit.

2+++.+++ All invented or imitated ways or acts of worship,
to the performing whereof the moving, presence,
and power of his spirit are not necessary, but men can perform them without it,
are Babylonish, and whoredom from that spirit to which the true Christian is joined,
and in which all that he doeth is performed.

3+++.+++ Under this antichristianism, under this whoredom, even in the land of Babylon,
where the true Israel is captive,
a true simplicity towards God may sometimes be stirring.

4+++.+++ When this at any time is stirring towards the Lord, the Lord pities it,
the Lord loves it, the Lord accepts it.
When this calls, the Lord hears, and waits that he may be gracious,
and return answers of grace to it.

5+++.+++ Though the Lord accept of this in the midst of Babylon,
and in the midst of the whorish ways of worship that have been learned there;
yet this doth not make Babylon, or her ways of worship, acceptable;
nor are they to be made use of (nor cannot) by any that fears God, to justify them.

6+++.+++ Where they are so made use of,
and the Babylonish ways and forms of worship cried up (because
of God`'s visitations and tender mercy to his seed under them),
God is provoked, his presence withdrawn, life lost,
and wrath prepared against those forms and ways of worship,
which will reach to the very bowels of those who are found there.

And let this word come home to your hearts,
O ye that ever knew what belonged to sweet communion
with God! if God was so tender to you in Babylon,
when he stirred up in you a pure simplicity and zeal there,
what would he have been to you, if ye had come out of Babylon?
Ah! ye have lost the substance for a shadow; and that not a right shadow either,
but a shadow of your own forming! and now ye are angry with them,
who will not also leave the substance to cry up your shadow.
Ah! enter into your secret chambers, and let shame cover your faces;
ye who would propagate that apostasy from the Lord,
which your own hearts have too far entered into, and are so deeply involved in.
Oh, that the eye were opened in you which can see it!
Do not your hearts a little feel it?
Oh, mourn after the Lord,
and mourn after the loss of that which once (in some
measure in you) was true to the Lord.
Oh, that the lost sheep might be sought out,
and that which hath been scattered (in the day of your loftiness,
and seeking dominion and great things) might be gathered again to the
Lord! for great is the wrath and severity that is towards you,
and he is become exceeding jealous for his seed`'s sake;
and judgment must begin with you, who cry out against antichrist in one gross,
fleshly appearance, and yet are serving him yourselves, some of you in other forms,
some in spirit.

This is a standing truth; whatever is not of the spirit of God in religion and worship,
is of the spirit of antichrist.
Whatever the spirit of man hath invented or imitated, is not the thing itself,
is not the true worship; for the true worship is only and continually in the spirit,
and never out of the spirit.
The true praying is in the spirit; the true singing, in the spirit; the true preaching,
in the spirit: whatsoever is out of it, is of antichrist in man.
Now therefore give up all your religion, your knowledge, your worship, your practices,
which are out of the spirit; and return unto the Lord,
and wait for his raising of that seed in you, which once began to spring,
but is now slain, and lies in death and captivity under all these;
and the earthly part (wherein all this religion and
these practices stand) covers its blood,
so as ye cannot see how ye have slain, and daily do slay, the just One.

Oh the blood, the blood, the innocent blood, that daily cries to the Lord against you!
How can the Lord accept any of your services,
while your hands are full of blood! while the pure simplicity is slain,
the love grown cold, the life lost,
and the whorish way and path (wherein and whereby
it was lost) cried up for the way of God.
Shall not the Lord visit for these things?
Shall not his soul be avenged on such a nation as this?
Yea, his wrath is kindled,
the fierceness of his wrath is kindled against the professors of this age,
and woe is from the Lord towards them.
Woe to the Protestant congregations, woe to the select churches, woe to their pastors,
who have helped them to wander from the life to dead idols, which cannot profit:
woe to them who are exalted in notions and high knowledge.
Ye have judged and condemned the Papists,
and the Lord hath found the same spirit of idolatry in you! but turn from your idols,
return to your simplicity, put away your adulteries from between your breasts,
and return to your first love, and the Lord will receive you,
though ye have wandered after many lovers,
and have been inflamed with the love of idols under every green tree:
but in these your church-ways and worships the soul of the Lord abhors you,
and all your former zeal and simplicity are blotted out and forgotten;
and in your present adultery and idolatry shall ye die,
unless ye hear the voice of the Lord recalling you, and turn at his reproof.

Now in tender bowels to help you a little, consider that which follows:

The same spirit that stealeth away the true simplicity,
raiseth up and stealeth in a false image thereof;
which there is no perceiving at present, unless the soul lie very low,
and be kept open and clear in the pure light.

And as in the true simplicity, the true light, the true knowledge, the true faith,
the true hope, the true love, the true meekness, the true zeal,
the true poverty and humility, etc., spring up and are nourished;
so in the false image of simplicity (which the devil secretly conveys in,
when he steals away the true) there is a likeness of all these springing up and growing.

And here is the beginning of Babylon in the heart;
here are the inward riches and treasures thereof.
What can Zion pretend to, which Babylon hath not in the resemblance?
Is there simplicity of heart in Zion?
And is there not simplicity of heart among the inhabitants of Babylon?
Yea, a false image.
Is there light in Zion?
And is there not also light in Babylon?
Yea, there is the light of the sun, and the light of the moon,
and the light of the stars which fell from heaven,
and the light of many candles shining in Babylon.
Is there a true knowledge, in Zion?
There is knowledge, falsely so called, in Babylon.
A false knowledge of the cross of Christ; a false knowledge of his death;
a false knowledge of his blood, without feeling the living virtue thereof,
which truly washeth away the sin.
So for faith, hope, love, meekness, zeal, humility, etc,
there are false images of all these in Babylon,
and of whatever else is wrought in truth in the inhabitants of Zion.

Now when the truth is lost,
and the false image crept in (both which are done at unawares,
while the husbandman is asleep, and so he perceives it not,
but thinks in his very heart that it is still the
seed of truth that is growing up in him),
then begins the mystery of fornication, idolatry, witchcraft,
and all manner of spiritual wickedness and deceit to work in the heart.
Thy believing, thy hoping, thy love, thy zeal, thy praying, thy waiting, etc.,
all here is abomination; it is from a false root; it is of a false kind;
it is not of the true seed: the enemy hath stolen away that,
whilst thou wast negligent and slumbering;
and all this ariseth in thee from the seed which he did sow instead thereof,
and is the fruit of the land of Babylon.

And having thus committed inward whoredom in thine own heart,
then thou seekest and settest up outward ways of whoredom also.
Having first set up an inward image of the inward life of the saints,
thou then seekest and settest up another image of their outward worship;
an image of a church, an image of a ministry, an image of ordinances,
an image of praying, an image of singing, an image of preaching, an image of baptism,
an image of the saints`' communion.
And thus thou art defiled within and without:
and art mad with envy and rage that thou canst not bewitch the
inhabitants of Zion (who are kept pure from all these defilements,
and reserved as witnesses against thee) into thy bed of whoredoms.
And thus, while thou thinkest thou art the chief worshipper, thou art all over polluted;
"`the whole head is sick, and the whole heart faint;`" there is no cleanness, no soundness,
within or without, but "`wounds and bruises,
and putrifying sores,`" which "`have not been closed, neither bound up,
nor mollified with oil:`" but the hurt of the daughter
of my people hath been healed deceitfully,
by physicians of no value, who have not the oil.
Isa. 1:5-6 and Ezek. 13:10.

This is generally the state of professors of this day; but they cannot see it:
for they have put out the eye of the simplicity (wherewith
alone God will suffer the things of life to be seen),
and God hath blinded the eye of their wisdom, that they shall not see,
nor be converted and healed that way.
So that exceeding miserable is their estate: they will not see God`'s way,
and God will not let them see their way.
So that though there be "`line upon line, precept upon precept, here a little,
and there a little; yet it is that they might stumble, and fall, and be snared,
and broken, and taken.`" For as discoveries of truth grow more clear and manifest;
so they grow more hardened against it.
And as they, on the one hand, increase in walking contrary to God; so God,
on the other hand, proceeds in walking contrary to them;
delighting more and more to stumble the wise, disputing part, which would so fain know,
but must be made blind, that the eye of the babe may be opened,
which sees that in the childish simplicity,
which the other eye can never reach in the most manly wisdom.

Therefore put away all your images and likenesses of truth:
put away your false faith (which can never overcome
the worldly nature and spirit in you),
and your false hope (which can never purify your hearts), and your feigned humility,
and self-willed fasts (which can never bring down the lofty, exalted nature in you),
and your false love (wherewith ye can never love the brethren in the truth,
but only the brethren in your notions, or some such other likeness of the truth),
and your false zeal, meekness, holiness, etc.,
(all which spring and grow up from the wrong seed, in a seeming simplicity):
and all your praying reading, preaching, etc.,
which ye have taken up and do practise in your own wills, which should be crucified;
and wherewith no service, worship, or performance, can be pleasing to God;
and wait for the raising of the true seed of life, in the true simplicity,
whereby ye may serve God acceptably here, and be saved hereafter.
And be not mockers, lest your bands be made strong;
for the consumption is determined against you by that Spirit of life,
whose breath will waste you.
All flesh is grass, and the glory thereof as the flower of the field!
Surely this people is grass, and their zeal and profession of God, like the fading flower.

=== SOME PLAIN QUERIES

Drawn out of the book of the REVELATIONS,
for all Sorts of Professors of this Age to answer between GOD and their own Souls;
that they may see whether they have received that Light from him,
which his Spirit judged necessary to give forth, to keep People chaste to him,
and to preserve them from the several painted Beds of Antichrist`'s
Fornications and Whoredoms from the Life.

"`Blessed is he that readeth, and they that hear the words of this prophecy,
and keep those things which are written therein: for the time is at hand.`" Rev. 1:3.

The time of deceit was then at hand for antichrist (with his false church,
and false prophets) to get up,
which were to last till "`the hour of judgment.`" Rev. 14:7-8. Hast thou read?
hast thou heard?
hast thou kept the things written in this book?
Then happy art thou!
But hast thou not read in the Spirit?
hast thou not heard the true sound of these things from the Spirit of life?
hast thou not kept the things written therein?
Then thou hast been deceived with the mystery of iniquity,
and must smart with the whore in the hour of her judgment.

The QUERIES are these which follow.

FIRST, WHAT woman was that which was clothed with the sun,
and had the moon under her feet, etc. Rev. 12:1.
Whether it was the true church or no?

SECOND.
What that wilderness was whereinto she fled; where she had a place prepared of God,
that they should feed her there 1260 days?
ver. 6.

THIRD.
How long those 1260 days did last?
and whether they be yet expired?
and whether the true church is anywhere else to be found all the time of the 1260 days,
but in that place in the wilderness?

FOURTH.
What are all the churches, the ministry, the ordinances,
that appear out of the wilderness all this while, while the true church is there?

FIFTH.
What was that beast which came out of the sea; to which the dragon gave his power,
his seat, and great authority?
which all the world worshipped?
Rev. 13 ver. 1, to 5.

SIXTH.
What is that sea, and those ships,
wherein and wherewith the merchants of the earth traded with Babylon,
and were made rich by their traffic?
what were those merchants?
what their merchandize?
and what kind of riches was this?
Rev. 18 ver. 15, to 20.

SEVENTH.
What was that name of God, and that tabernacle, and those inhabitants of heaven,
which were blasphemed by the beast that arose out of the sea,
all the time of the forty-two months?
Rev. 13: ver. 5-6.

EIGHTH.
What is the Lamb`'s book of life?
and where is it?
and how are the names of any so written in it,
as to preserve them from the worship of the beast? Rev. 13:8.

NINTH.
What is that beast that came up out of the earth,
with the horns of a lamb (as if it came up in the Lamb`'s power),
which doeth great wonders, and justifieth his sacrifice,
by making fire come down from heaven in the sight of men;
who both caused men to make an image to the first beast,
and also putteth life into the image which men make?
Rev. 13. ver. 11, etc.
So that here is not a mere dead image, but there is life in the beast`'s knowledge,
ordinances, and worship: yet with God all this is dead, for it is not the true life.

TENTH.
What is the beast`'s mark, his name, his number? Rev. 13:17.
For if I do not infallibly know this, I may have received his mark;
I may help to make up his name; I may be of his number, and be, unknown to myself,
a worshipper of him and his image,
and so be liable to partake of the torment of the fire and brimstone threatened to such.
13:9-10.

ELEVENTH.
What is that song, which none could learn but the 144000,
which were not defiled with women, but remained virgins? Rev. 14:3.

TWELFTH.
What was that other woman, which took and kept the place of the former woman,
after she had fled into the wilderness, and enlarged her territories in nations, kindred,
tongues, and peoples?
Rev. 17:4, and ver. 15.

THIRTEENTH.
What were the purple and scarlet colours,
and the gold and precious stones she was decked with?
ver. 4.

FOURTEENTH.
What was the golden cup she had in her hand, which was full of abominations,
and filthiness of her fornications; in the midst of all her glorious appearance of zeal,
devotion, humility, and holiness?
ver. 4.

FIFTEENTH.
What kind of drunkenness was it,
wherewith the kings and inhabiters of the earth have
been made drunk with the wine of this cup? Rev. 17:2.

SIXTEENTH.
How may those who have hated the whore, and made her desolate and naked,
and eat her flesh, and burned her with fire, yet after all this,
give their kingdom again to the beast?
Rev. 17 ver. 16-17. How may this be done?
and how often may it be done?

These are plain, simple queries, not to entangle men`'s minds,
or set their brains on work (for that way shall they never be able
to resolve them) but to awaken the simplicity in them,
which will readily let them see what the Lord hath revealed to them herein,
and in which they are to wait for the knowledge hereof,
that they may escape or come out of the snare.
And in the mean time not to boast,
as Israel of old did (when the prophets from the mouth of the Lord
accused them) that they had not "`polluted themselves,`" they had
not "`gone after Baalim`" (Jer. 2:23. and ver. 35);
but wait O backsliding Christian! and thou shalt "`see the way in the valley.`"
And though thou hast often traversed thy ground to change thy path,
gadding from one form to another, from one notion to another;
yet all this hath been out of the life, out of the pure power, and still in the whoredom.
Open the weak, sick eye in the weak heart (for how weak is thy heart,
while thou hast done all this!), and let the languishing simplicity be my witness:
for (under all thy wisdom, thy zeal, thy knowledge, thy worship) that faints, that fails,
that is not what it was in the beginning.
Though thou art grown much higher, wiser, and greater otherwise,
yet there thou hast lost: and happy wilt thou be,
if all thy gains ever since may become loss to thee for the recovering of this.

=== SOME CONSIDERATIONS

Helping out of the Suburbs or Out-skirts of Babylon,
that her inward building may be the better come at,
and lie more open to the axe and hammer,
which are to batter it down, and to cut it for the Fire.

FIRST, consider what it was the church fled out of, when she fled into the wilderness.
Was it not out of that church-state or building,
which the Spirit of God had raised up for her here in the world, to which her ordinances,
and way of church-worship belonged?
Was it not here that the dragon assaulted her,
and from whence she fled into a desolate place and state?

Secondly, What spirit entered into these, when she fled out of them?
Were not these the conqueror`'s spoils?
Did not antichrist get possession of the form?
Did not the whore get the spouse`'s attire?
Did not the wolves gather up the sheep`'s clothing, and clothe themselves therewith?
Was not the outward court (what is the outward court under the gospel,
but the visible church-state,
with the visible ordinances thereof?) given to the Gentiles,
who trod under foot the holy city,
all the while they were worshipping in the outward court? Rev. 11:2.

Thirdly, What spirit is it directs men to these,
since the true church hath been fled out of them?
And to what intent?
Is it not that spirit which would keep men from the life,
that they might not be born of the barren womb in the wilderness,
but be born of some of the fruitful wombs of the visible churches;
while the true church is invisible, and hath no visible place in the earth,
but remains in that place in the wilderness which God prepared for her,
and where she receiveth her food all the forty-two months?
Rev. 12 ver. 6,14.

I have smarted deeply for these things,
and have been taught by the briars and thorns of the wilderness,
whereby my ears came to be opened, to hear the sound of the everlasting gospel,
to which they were before through ignorance stopped.
For I also did believe and expect great things in a church-state and way of worship;
and in simplicity of heart did I enter into it, and walk in it,
and was not without knowledge, warmth, and experiences there.
But all this the Lord broke down by a strong hand, in one moment;
and hath taught me since to throw away all my gains here, and elsewhere,
and to count them but dross and dung,
for the excellency of the knowledge of Jesus Christ my Lord.
And having tasted, having seen, having felt, having handled,
I cannot but commend the life; and dissuade all men from all knowledge, all worship,
all religion, all ways, and practices (though ever so taking, pleasant, and promising),
out of the life.
And this is to know Christ; namely, to know the life: and this is to obey Christ,
to obey the life: and this is the kingdom of Christ which is to come,
to have the life reign in power and great glory.
But the knowing or believing of a history concerning Christ,
this is not the knowledge or the faith: antichrist all along the apostasy,
in all his various forms and dresses, hath known and believed thus:
and this kind of knowledge must pass away,
further than it can find a place and service in the life.
Be not angry at my testimony; it flows from pure love,
and comes forth in great good-will to your souls.

Yea, if it be possible that I might be a little serviceable to you (for my soul travails
for the redemption of professors from the witchery of the whorish spirit,
even of such as are ready to revile that which alone can redeem them),
in the meekness and coolness of your spirits, out of the fiery, false zeal,
consider yet a little further these few things following:

1+++.+++ The state of the gospel is an invisible state,
a state consisting of invisible things (as the law was a visible state,
or a state consisting of visible things); the light invisible, the life invisible,
the power invisible; that which converts invisible, that which is converted invisible,
that which it is converted to invisible,
and the whole course of spiritual life lies invisible.

2+++.+++ This invisible state hath a visible way of appearance to the world,
by garments which it wears,
by motions and exercises which the life chooseth for it to appear in.

3+++.+++ These garments are subject to corrupt, and to be worn by that which is corruptible,
and corrupted.
That which hath not the life may put on the garment;
and that which hath lost the life may still keep the garment.

4+++.+++ The preservation of the life lies not in the garment,
or in the observation of any thing wherein the life did once appear;
but the preservation of the garment lies in the life.
And the life may change its garment at its pleasure,
and may refuse to wear those any more which the whore hath worn,
but as the life again leadeth.

5+++.+++ When the life is at any time lost,
the only way of recovery is by retiring to the invisible, and keeping there,
and growing up there; and not coming forth in the visible further than the life leads,
nor staying there any longer than the life stays.

Now this is the mistake of persons generally;
they look for the finding the invisible life in visibles.
They run to corrupted ordinances and ways of devotion, and think to find God there:
but do not wait to feel him in their hearts, and to be led by him into what he pleaseth;
and to stay no where any longer than while he stayeth there,
but to follow the Lamb wheresoever he goeth.

Some others mistake in running to that, and waiting there where they once felt life,
but do not know the way to wait on the life itself: and so they are running to an image,
waiting at an image, worshipping of an image,
and the living God will not meet them there.
But throw away your images; let Ephraim, the dear child, say to his idols, Get you hence;
thrust away your adulteries which provoke the eye of God`'s jealousy,
receive the forerunner (the severe purifier) into your bosoms,
and let the fire of his jealousy cleanse your hearts, and the pure will soon come after,
and lodge again between your breasts.
Can ye hear this sound?
That which is born of the same wisdom, cannot but hear it;
but the other birth must have its ear stopped.

Now hearken to this advice.
When the invisible life is felt and known,
do not disdain to follow it into whatever visible thing it leads.
Let not thy wisdom be judge what the life will lead into,
or what the life is to be followed in; but let the life itself be judge:
and let the child, which is born of the life, follow it singly, without murmuring,
without disputing.
The life hath foolish ways (to the eye of thy wisdom) of breaking the wisdom in thee,
which is contrary to it, which thy wisdom will be reasoning and disputing against;
and if that wisdom be hearkened to, the life is overturned in its course,
and the head of the serpent remains found in thee,
which the foolish and weak things (which the wisdom of God chooseth
to cross and disturb it by) would help to break and crush.

=== AN EXHORTATION TO THE PRESENT POWERS

BABYLON the great, the mystery of iniquity,
which hath deceived and held captive the whole Christian world for these many generations,
under forms and appearances of godliness and devotion,
is at length come into remembrance before God, who is arisen to judge her,
and overturn her seat.
The army hath been preparing, and many soldiers have been drawn forth;
the trumpet hath sounded, the battle is begun, and blood hath been shed on both sides;
the blood of the creature on the one side,
the blood of the whorish spirit on the other side.

The whore (with the power of the beast on which she rides,
and by whose strength and assistance she makes war with the Lamb) is mighty and dreadful:
and it hath long been said,
"`Who is able to make war with the beast?`" (whose strength is hers).
But the Lord God (who hath risen out of his holy habitation to judge,
and hath begun to judge her) is more mighty; by whose arm and strength she shall fall,
and the beast shall not be able to carry her up and down any longer; nay,
nor to uphold her in her seat of government over the consciences of men.

Be wise now, therefore, and consider the present state of things;
and if ye find not hearts to help the Lord against the mighty,
yet take heed of helping the mighty against the Lord.
The vessels wherein the life arises and appears, are poor and very contemptible,
and ye may easily trample upon them:
but the life which riseth up in them is very precious,
and too strong for the powers of earth or of hell.
The Lord did not appear formerly among you, or of late begin to raise you up again,
that ye should become enemies to him, or aiders of his enemies against him;
but that ye might let his seed go forth to worship him in
the wilderness (for in this dark land of Egypt they cannot).
Therefore break the yokes, and take off the burdens, and let there be no new snares laid;
but leave the conscience (where the Lord chooseth to appear,
and which he delights to draw out of the world to himself) free to the Lord.

The Lord hath kindled, and is kindling, the fire with which he is burning, and will burn,
the flesh of the whore.
Come not near to help her, lest ye feel the flames.
Stand afar off and see her burning, and at most pity her, but help her not.

We fight not against the flesh and blood of creatures,
but against that evil spirit which captivates and makes them miserable:
nor do we fight with carnal weapons,
but with such weapons as are able to reach that spirit.
Now if ye interpose with your carnal weapons,
and smite the vessel which the Lord is pleased to make use of in this warfare,
his hand will be upon you: yea, if ye endeavor to bear off the stroke from the whore,
it will light upon yourselves,
and the Lord`'s hand (and his strokes in this day
of his jealousy and vengeance) is very heavy.

Do what ye can, ye shall not be able to hinder the Lord`'s victory (who will overcome,
even by this very people, whom the wise of all sorts despise).
All that ye can do in taking part with the enemy,
is but to bring wounds and judgments upon yourselves,
and to shorten the days of your government.
But the work of the Lord will go on and prosper;
and this painted harlot (which pretends to be the spouse of Christ,
and has decked herself so pleasingly with her stolen knowledge of scriptures,
and lays claim to his ministry and ordinances) shall be stripped naked,
and her shame seen, and every child in the life shall be able to point at her;
and the song of triumph over the dragon, the beast, the false churches,
and all the false prophets (who are not made, nor prophesy not,
by the anointing) shall be sung in righteousness, even to the Lamb, who daily getteth,
and will get, perfect victory; for to him it is given over all his enemies.

=== POSTSCRIPT

THE redemption of the soul is by the Spirit of the Lord;
which he that would enjoy from it, must know its appearance and operation in himself,
and not quench or limit it, but universally be subject to its guidance and leadings.
All man`'s inward misery arises from man`'s inward rebellion,
which is as the sin of witchcraft (springing from the spirit of witchcraft).
His recovery and happiness are in the faith and obedience to the pure power, movings,
and operations of the Spirit in him.

The Lord God, who made mankind, who is the Lord of all,
he is redeeming a people to himself by his Spirit.
And this Spirit will not be limited by the powers of the earth,
but will break nations in pieces, and trample upon princes as mortar,
and as the potter treadeth clay, till it hath made its way through them.

Oh! open the eye, the inward eye, which can discern the seasons.
It is not now the time for antichrist to prevail,
or for proud flesh to rise up in its heady will, to stop the outgoings of its Maker.
This season is past;
and the season of the prevailing of the life and
power of the Sun of Righteousness is now come.

Therefore lift up your heads,
O ye weak and faint of the flock! for iniquity and
oppression must fall both within and without;
and the tender God of everlasting love will turn back the captivity of his people,
and of his creatures.
Be not therefore affrighted at the inward power of sin in the heart,
nor at the outward oppressing powers of the earth;
for the Redeemer`'s strength is above all,
and he is stretching forth his mighty arm to save:
in the true and living faith of the elect it is felt.

And O ye potsherds of the earth! strive not with your Maker, limit him not,
for he will assuredly break through you.
Think not to subject him to your laws; but learn his law, come under his yoke,
and be bound by him, that ye may taste of his liberty.
Wash your lips, and kiss the Son,
and be not angry at his various appearances so contrary to your wisdom;
but fear his dreadful name, and his threshing instrument which hath teeth;
and seek an hiding-place under the shadow of his wings,
against the sharp season of the breaking-forth of his wrath,
and jealous indignation for the cause of Zion, which hasteneth apace.

He hath long let the spirit of Babylon have its liberty, and his hath been silent:
now is the time for his Spirit to speak, and for Babylon`'s to be silent.
Will ye still force him to silence, and open Babylon`'s mouth?
Will ye not suffer him to speak, but according to the laws and orders of Babylon?
Must that counterfeit queen still sit on the throne among you,
and the true princess be made her servant?
Oh let it not be grievous to you, to see the Spirit of the Lord arise,
and make Babylon appear Babylon!
Her wisdom, her knowledge, her unity, her uniformity, her order, her comeliness,
her beauty, are but folly, confusion, disorder, and deformity before the Lord.
Happy is the eye that sees it, and the foot that turns from her.

Therefore awake, arise, and stand up from the dead.
Come out of the thick, dark land, where the pure God of life is not to be found:
"`Come out of Babylon,
and touch not the unclean,`" that the pure life may receive you into unity with itself:
but the spirit that is unpurged from its Babylonish worships and practices,
the Lord will not suffer to come near him.
Therefore search what is Babylon, and of Babylon, in all your ways and worships;
and wait on the Spirit of the Lord to be redeemed out of it, and separated from it,
or ye must remain separated from the Lord, and not partake of his life and virtue,
from which that city, with all her inhabitants, is shut out forever.

The Lord hath had a sore controversy with this nation (with her rulers, her teachers,
and people) for his seed`'s sake, which he hath been begetting to himself,
and calling forth to worship him (according to the pure law of his Spirit of life),
out of the ways, worships, and heathenish customs of the earthly spirit.

Israel is his first-born, whom he will not have any longer kept in bondage.
They are his own, of his own begetting and forming,
of his own nourishing and bringing up; the plants of his own right hand,
whom he watereth with the dews of heaven,
and with the showers of his everlasting mercy and lovingkindness;
whom he hath gathered by the arm of his power,
and whom he leadeth and defendeth by his cloud, and pillar of fire;
over whom he is tender as of the apple of his eye.
They are his anointed ones, whom he will not have touched,
but rebuketh kings and parliaments, armies and councils, for their sakes; saying,
"`Touch not mine anointed; and do my prophets no harm.`"

Have ye not seen, how no strength nor counsel hath been able to prevail against them?
They have had no fence, but the arm which hath gathered them.
What plottings and contrivings have there been against them!
How are they, as sheep appointed for the slaughter, destined to be devoured, crushed,
and trodden underfoot; what divinations and enchantments have been used against them,
even to blot out their name and remembrance from the earth!

But why do ye strive and contend thus with the God of Jacob?
Can ye prosper?
He that made the earth, will not ye let him have room therein for his people?
Must they be subject to your wills?
Must they bow to your image?
Shall not the God of the spirits of all flesh have
the command of the spirits of his own people?
Can ye stop the Spirit of God from breathing upon them?
Or will ye fall foul upon them,
if they be obedient to the breathings and movings of his Spirit?
May it not suffice that they are innocent and harmless
among you in their conversations and practices,
but will ye still lord it over their consciences?
Will ye put the Lord to it, to the very last, to try it out with you,
whether he can defend his people, and make way for their liberty?

Well! if peace be taken from you; if your rulers, laws,
and governments be broken in pieces; if his hand be stretched forth against you;
if he curse your very blessings, whom can ye blame?
Why do you provoke him against your own souls?
Are ye stronger than he?
If ye be stronger and wiser, ye may prevail: but if he be stronger,
and will put forth his arm, his people shall be saved, and find a shelter in him,
in the midst of all that wrath which is pouring down upon you.
Your peace hath been lengthened out for their sakes.
"`If it had not been for their sakes,`" (for the remnant
which the Lord hath had to gather) "`ye had,
ere this, been as Sodom, and like unto Gomorrah.`" The land is full of filthiness,
which the Lord`'s soul loathes; and instead of drawing forth the sword against it,
ye draw it forth against his witnesses.
There is liberty enough for sin and vanity, for excess and riotousness,
for images and idols: but to worship God in spirit, to obey his pure movings;
this kindles your rage, and these are the people who are a burden to you.
Ah! how fain would ye ease you of this people! (Zion is indeed a burdensome stone,
and will fall heavy on all that meddle with her).
But the Lord will ease himself of the adversaries of his life and Spirit,
and he will bring forth his righteousness which he hath prepared,
and set it up in the earth, and none shall be able to stop him.
Therefore gather yourselves together in battle; associate yourselves,
that ye may be broken in pieces: take counsel together, it shall come to nought;
speak the word, it shall not stand: but the Lord`'s counsel shall stand,
and he will fulfill all his pleasure, and will delight himself in his people,
and raise them up by the fall of their enemies:
and then ye shall see against whom ye have plotted and contended,
and what ye have helped to bring about by all your secret plots and designs.
"`If the Lord had not been on our side,
now may Israel say;`" if the Lord had not been on our side,
what had become of his poor people!
Ah, poor worm Jacob! how often would the foot of pride
have trampled thee down again and again,
had not the everlasting arm been stretched out for thee! but fear not, worm Jacob,
nor be solicitous for thy preservation,
but trust that arm which delighteth to preserve thee.

Ah foolish people and unwise! who strive against your own mercy;
who see not on what hinge all your mercies hang,
but make it your work to break down the wall that defends you!

Jerusalem is the city of the great King, which is coming down from heaven:
and Israel is his people; and both must have a place in the earth.
The Lord hath determined it, and who can withstand it?
What prejudice can Jerusalem, or the inhabitants thereof, bring unto you?
They are enemies, indeed, to this earthly state of things,
and would have all brought into subjection to the life and power of their king,
and all that stands in opposition to God brought down, and made pliable to his spirit;
and this the unyoked earthly spirit cannot bear.
But this is the interest of your souls,
and the way to unity with that life which is their happiness, peace, and rest forever.
For if ye could pass through the fire, and bear the burning up of your dross,
ye also might become vessels for the finer,
and might dwell with them in their everlasting habitation.

The saints formerly had an entrance ministered to them into the everlasting kingdom,
and came unto Mount Zion, which cannot be removed; and to Jerusalem,
the city of the living God, Heb. 12:22. where the blood of sprinkling,
the peace that passeth understanding, the everlasting righteousness,
and the joy unspeakable and full of glory, were witnessed in the renewed spirit,
which receiveth the kingdom which cannot be shaken,
and entereth into the everlasting rest.

And it is again revealed,
and the witnesses shall ascend into heaven in the sight of their enemies;
even into the new heaven and the new earth, where righteousness dwells;
and the old heaven and the old earth (with all their inhabitants) shall be burnt up:
and then it shall be seen that righteousness becomes, and belongs to,
the house of God forever.
And his city shall be a quiet habitation, free from all the noise and hurry of Babylon;
where the pure river of life runs clear, free from all the mud and mixtures of Babylon;
and the Lord God of infinite fulness will not disdain communion with his creatures,
but will tabernacle among them, dwell with them, sup with them, walk in them,
and take them into his holy habitation, and they shall dwell with him, sup with him,
and walk in him.

But who shall abide in his tabernacle?
who shall dwell in his holy hill?
He that walketh uprightly, and worketh righteousness,
and speaketh the truth in his heart, etc.,
he who contemns the vile person (how great and high soever),
but honoreth them that fear the Lord, be they otherwise what they will.
This man shall dwell on high, above the reach of all low, creeping, dark spirits,
even in that holy habitation of life and power, which nothing can touch or annoy.

I shall now conclude with a few words concerning the present estate of this poor,
distracted nation.

This nation hath long lain wounded and sick:
she hath had many physicians (on whom she hath spent much) who have promised her fair,
but have not effected her cure.
Of late her wound hath been much enlarged; yea, she is become sick at her very heart,
and in great danger.
Many are spending their judgment upon her; some thinking a king would help all,
some a parliament, and some hoping for good from the army;
but every eye sees her case to be very desperate.
Ah England, England!
Thou strivest with thy Maker, and he overturns thy strength and councils.
The life and wisdom which thou despiseth, is that which alone can heal thee.
Thou strivest to keep off the strokes from the enemies of God, and smitest his dear ones;
how can he spare thee?
Hand still joins in hand to keep the Lord`'s stroke from reaching Babylon,
which he hath directed at her heart, and will not miss her,
but will pierce through everything that stands in his way.
Though the cry hath long been, Hurt not the tender conscience;
it is that on which God works, and wherein he chooseth to appear,
and with which he is pleased, and pities.
Many promises have been, touching liberty of conscience; yet still the meek of the earth,
the innocent lambs of Christ (those that are faithful to the light
of God in their consciences) are persecuted and suffer.
What canst thou plead, O England! why the Lord should not break thee all in pieces,
and save his people himself, by and in the midst of thy ruins?
The Lord will have the victory over thee in this particular,
about which he hath so long striven with thee.
It would be better and easier for thee to yield unto, than be forced by, his hand.
Therefore, at length hear his voice, which hath so often and so loudly cried unto thee,
"`Let my people go, that they may serve me.`"
