== THE JEW OUTWARD

BEING A GLASS FOR THE PROFESSORS OF THIS AGE

WHEREIN IF THEY READ WITH MEEKNESS, AND IN THE TRUE LIGHT,
SUCH OF THEM AS HAVE NOT OVERSLIPPED THE DAY OF THEIR VISITATION,
MAY SEE THEIR OWN SPIRITS, TO THEIR OWN EVERLASTING ADVANTAGE AND COMFORT,
BY LEARNING SUBJECTION TO THAT WHICH HATH POWER IN IT TO DESTROY THE EVIL SPIRIT IN THEM

CONTAINING Some EXCEPTIONS and ARGUMENTS of the JEWS against Christ`'s
Appearance in that Body of Flesh in their Days;
which the present PROFESSORS may view and compare with their Exceptions
and Arguments against his Appearance in Spirit in this Age;
that they may see and consider which of them are the more weighty

BY ISAAC PENINGTON, THE YOUNGER

+++[+++1659]

=== PREFACE

THE Lord God of infinite goodness, hath ever dearly loved mankind,
yet could never so appear to them since the transgression, as to be owned by them,
till the veil was taken from before their hearts.
Israel in Egypt hearkened not to Moses, because of their anguish and bondage.
When they were led out, they were ever and anon murmuring,
and picking quarrels against him.
Samuel they rejected (as the Lord lays to their charge);
though they might excuse themselves, and say they had just exceptions against his sons.
Elijah, that mighty man of God, the great restorer of Israel,
and pleader against Baal by fire, his life was sought for.
And though there be not a particular record of their
usage of the prophets about those days,
yet in general he complains that they were all slain but himself. 1 Kings 19:10.
Micaiah was smitten on the cheek,
and jeered by the false prophet who smote him, and said,
"`Which way went the spirit of the Lord from me to speak
unto thee?`" And he was commanded to be put in prison,
and fed with bread of affliction and water of affliction.
Jeremiah was put into the dungeon, even to the danger of his life:
and by those few that were left,
that seemed singly to inquire by him concerning the will of the Lord (Jer. 42:2-3),
disdainfully rejected.
chap.
43:2. Why should I spend time in particular instances?
What prophet can I except?
for though all their bad dealings with them are not related in scripture;
yet Christ testifies that they did deal badly with them all; some of them they stoned,
some of them they scourged in their synagogues, some of them they killed and crucified,
and others they persecuted from city to city.
"`Yea,`" saith Stephen, "`which of the prophets have not your fathers persecuted?
And they have slain them which showed before of the coming
of the just One.`" Ye make it such a strange thing,
that if Christ had been a prophet, ye should not own him;
why which of the prophets was owned?
Ye have still some exception or other against us, that we are not the prophets of God;
and against our message, that it is not the mind of God.
Ye take arguments from one prophet`'s words to oppose another prophet with;
and from one prophet`'s manner of coming, to oppose another prophet`'s manner of coming.
If John come neither eating nor drinking, ye reject him for his austereness:
if Christ come both eating and drinking,
ye reject him for his liberty and freedom in the life.
Now what is the reason of this?
Christ himself gives the reason. Matt. 11:19.
"`Wisdom is justified of her children.`" Ye are not the children of wisdom,
ye are not begotten of the life, of the Spirit of the prophets,
and so cannot justify that Spirit.
Ye have got the letter of the prophets, ye are born of that;
but ye are not born of the life, ye are not born of the wisdom.
And so whoever comes forth in the same birth from the letter with you, him ye can own;
but if any prophet come forth with that same Spirit, him ye cannot own.
He that is born after the flesh, cannot but persecute him that is born after the Spirit.
Jerusalem was all along the persecutor of the prophets, from the beginning to the end.

And is this nothing to you, O ye professors of this age!
Search and see who have been the persecutors among you,
but they who have had the name of the church and her prophets.
Who have slain the witnesses?
The church of Rome hath slain the witnesses against her,
and the Protestants have slain the witnesses against them.
About the beginning of these troubles, if a man were never so truly zealous,
yet if he could not conform to the common prayer book and ceremonies,
how was he persecuted!
A Non-conformist, a Separatist, a Brownist,
an Anabaptist (though owning the same Christ in his very heart and soul) yet because
his practice was a testimony against the false church-worship of the common Protestant,
must be hunted up and down to courts, imprisoned, fined, banished.
And to this day, the Lord can bring forth no birth of his Spirit,
but the zealous professor hates, reviles, and seeks to destroy it.
If the Lord lay any law upon the conscience,
if it be not suitable to their apprehensions from the letter, how do they reproach,
disdain, revile, and endeavor to render such odious to the magistrates,
and to the people!

But why should we wonder at these things?
There is no new thing under the sun.
The state of the world is just as it always was.
The power of Truth in every age hath been still opposed by those who cried up the form.
It were a wonder if it should be otherwise.
I should much more wonder, if the teachers and professors of this age should own Truth,
than that they fight against it, and persecute it.
Well, friends and brethren, be strong in the Lord, and faithful to his Truth,
in the power of his might: bear the reproach, the afflictions of this age,
the persecutions of this your day.
Verily your eyes shall see that there is a reward for the righteous,
and your hearts shall be satisfied with it,
when the children of the kingdom (of this age, as well as of Christ`'s,
and all former ages) shall be shut out in utter darkness, where shall be weeping,
and wailing, and gnashing of teeth.

=== THE JEW OUTWARD SOME EXCEPTIONS AND ARGUMENTS OF THE JEWS AGAINST CHRIST`'s APPEARANCE, etc.

THE Jews were once the only outward, visible people of God,
who were chosen by God for a peculiar people, who had the promise of, and expected,
the Messiah; whose faith and hope of salvation was in him; yea,
and at that very time they were looking for him, yet, when he came,
he was "`a stone of stumbling, and a rock of offence`" to them,
and they could by no means receive him.
They were full of reasonings, and doubts, and contendings about it; but could never,
with all their wisdom from the letter, determine that was he.
Though he lived as never man lived; though he spake as never man spake;
though he did what never man did;
yet still some exception or other they had from the letter of the scriptures,
to which his manner of appearance, his conversation, and his doctrine,
did not suit in their judgment; and so, after many disputes and debates,
they at length delivered him up to death, as a blasphemer, a deceiver,
a seducer of the people.

Many exceptions and arguments they had against him; against his descent, his doctrine,
his practices, his miracles, his followers, etc., which I shall refer to heads,
to make them more obvious.

1+++.+++ They excepted at his descent and kindred.
"`Is not this the carpenter`'s son?
Is not his mother called Mary?
And his brethren, James, and Joses, and Simon, and Judas?
and his sisters,
are they not all with us.`" Matt. 13:55-56. What!
this that glorious Messiah! the great king of glory,
of whom all the prophets prophesied and spoke great things!
Surely it cannot be.
"`And they were offended in him.`" ver. 57. It was this made
them they could not receive that heavenly doctrine of his,
which otherwise might have been life to them,
when he taught them that he was "`the bread of life that
came down from heaven:`" but they murmured because of it,
and said, "`Is not this Jesus, the son of Joseph, whose father and mother we know?
How is it then that he saith, I came down from heaven.`" John 6:41-42. So again, John 7:27.
"`We know this man whence he is; but when Christ cometh,
no man knoweth whence he is.`" This was a close argument,
and was raised up to eat out a deep impression of his being the Christ,
as may appear from the foregoing verse.
He speaketh indeed boldly, and deep things, etc, as if he were the Christ;
but how can it be he, seeing it is known from whence he comes?

2+++.+++ At his country, or place of his education and residence, which was Nazareth of Galilee.
"`Can there any good thing come out of Nazareth?`" John 1:46. "`Shall
Christ come out of Galilee?`" John 7:41. "`Search and look;
for out of Galilee ariseth no prophet.`" ver. 52.

3+++.+++ At the time and season of his coming.
He came (as to their sense) before Elias.
With this argument they pinched the disciples,
as is signified in that query of theirs to Christ, "`Why then say the Scribes,
that Elias must first come?`" Matt. 17:10. This could
not but be a sore argument in the mouth of the Scribes,
who might reason with the disciples on this wise: what poor, ignorant, sottish,
deluded people are you, to own this man for your master, and take him for the Messiah!
Elias must first come, and restore all things.
If this man preached ever so heavenly doctrine, and did ever so many miracles; yet,
if he pretend to be the Messiah, he can be but a deceiver:
for the true Messiah comes not before Elias;
and every one knows that Elias is not yet come,
nor his work of restoring all things so much as begun.

4+++.+++ His doctrine administered abundance of offence to them,
and they were continually stumbling at it.
That heavenly doctrine, mentioned a little before,
that he was "`the bread of life,`" they murmured at. John 6:41.
When he did but say "`God was his Father,`" they presently flew out upon him,
and said, "`he made himself equal with God.`" John 5:18. When he said,
"`Destroy this temple, and in three days I will raise it up,`" they misunderstood him,
and brought it forth as an argument against him at the time of his suffering, Matt. 26:61.
and cast it as a jeer in his teeth. Matt. 27:40.
When he did but say to the man sick of the palsy, "`Son,
thy sins are forgiven thee;`" the Scribes and Pharisees presently exclaimed against him,
"`Who is this that speaketh blasphemies?
Who can forgive sins but God alone?`" Luke 5:21 and 7:49.
When he preached very powerfully against covetousness,
the Pharisees derided him. Luke 16:14.
Yea, when he did but preach a parable or two about "`the widow of Sarepta,
and Naaman the Syrian`" (it coming a little close to their
state) "`all they in the synagogue were so filled with wrath,
that they rose up, and thrust him out of the city, and led him unto the brow of the hill,
to cast him down headlong.`" Luke 4:28-29. At his
saying that "`Abraham rejoiced to see his day,
and he saw it, and was glad;`" the Jews replied, "`Thou art not yet fifty years old,
and hast thou seen Abraham?`" John 8:57. How absurd and impossible was this to them,
that a man of not fifty years should say,
that Abraham (who lived so many ages before) saw his day!
And instead of giving them an argument to demonstrate it to them,
he only returns them a more confident affirmation, "`Verily, verily, I say unto you,
before Abraham was, I am;`" ver. 58. which so enraged them,
that "`they took up stones to cast at him.`" ver. 59. Now mark:
the life speaks what it sees and knows, and so it gives forth its testimony.
The wise professor, not being in the life, cannot know or receive the testimony;
but calls for arguments and demonstrations to his wise eye.
The life refuseth to answer him; but instead thereof,
only affirmeth the thing more strongly and confidently.
This, being so far from that which he looks for, and requires to satisfy him,
kindles disdain and rage in him: and he looks upon the life, for this way of proceeding,
as worthy to be stoned.
What! when they should lay before Christ a fair argument,
whereby they might plainly convince him by evident reason,
that he could not see Abraham`'s day, and he, instead of answering it,
should only bring forth a more confident affirmation,
would not men`'s wisdom in this age even hiss at such a thing?
Yet this was the way of the life then, in that day; and the life may, at his pleasure,
take the same way again now, to offend the wise and knowing.

When he spake of his being "`the good Shepherd,`" and of his "`laying
down his life for his sheep`" (and of the hireling`'s flying,
in time of danger, to save himself), John 10:11-12. many of the Jews said,
"`He hath a devil, and is mad.
Why hear ye him?`" ver. 20. Many of them that were
then the people of God (the separated people;
for the Jews were a people separated from the world, and studied the law,
and observed the ordinances of Moses) looked upon
Christ as a man not fit to be heard speak;
but as a mad-man, as one that had a devil,
as one that might have great power of deceit from the devil, to bewitch men from truth.
"`Why hear ye him?`" What good can ye expect from him?
"`He hath a devil, and is mad.`" Oh,
how desperately will bold flesh venture to judge of the life and power of God,
when it hath got a little knowledge from the Scriptures, and a way of worship, duties,
and ordinances!

When he said,
"`I and my Father are one,`" John 10:30. "`they took up stones again to stone
him,`" ver. 31. and made no question but they did well in doing of it,
as appears by their answer to his demand, for which of his good works they stoned him.
They replied very confidently, "`For a good work we stone thee not; but for blasphemy;
and because thou being a man, makest thyself God.`" ver. 32-33. And when he said,
"`If a man keep my saying,
he shall never see death,`" John 8:51. then said the Jews unto him,
"`Now we know thou hast a devil.
Abraham is dead, and the prophets are dead.
Who makest thou thyself?`" ver. 53. Were not Abraham and the prophets holy men?
Had not they the sayings of God?
And did they not keep the sayings of God?
Yet they are dead.
Such a kind of speech as this must needs be from the devil.
Now thou makest manifest from what spirit thou speakest.
"`Now we know thou hast a devil.`" And indeed how could
the professors of that age digest such things,
being so contrary to what appeared to them to be certain truth in the Scriptures.

And there were many other things as hard to them;
though the exceptions which might or did arise in their minds,
are not particularly mentioned; as when he saith, "`I am the door of the sheep.
All that ever came before me are thieves and robbers;
but the sheep did not hear them.`" John 10:7-8. How offensive
must this doctrine needs have been to them,
going carnally to understand and reason about it?
What! were all the prophets and holy men before thee thieves and robbers?
Did the truth never come till thou broughtest it?
What became of our fore-fathers in former ages?
Were they none of them God`'s sheep?
Did none of them find the door?
For thou sayest thou art "`the door,`" and thou hast been but of late.
And whereas thou sayest the sheep did not hear them; that is utterly false;
for they did hear Moses, and they did hear the prophets: and we have their writings,
and will keep to them for all thee, let who will be thy sheep.
When he said, that "`he came not to send peace,
but division,`" Matt. 10:34-35. how readily might they reply,
that his own mouth discovered him not to be the Messiah, the Saviour, the Peace-Maker;
but the worker of divisions, the cause of breaches in families,
setting three against two, and two against three! Luke 12:51-52.
When he said, "`Whosoever committeth sin,
is the servant of sin,`" John 8:34. might not they well except against this,
as condemning the whole generation of the righteous,
and making null the way of sacrifices,
which God had appointed for sins committed at any time by his people,
which could not but pre-suppose their commission of sin?
Did not Abraham, Isaac, David, Moses, and the rest of the prophets, all commit sin,
and were they the servants of sin?
He taught also that the children of the kingdom should be cast into utter darkness. Matt. 8:12.
Oh, how harsh would this sound in the ears of the zealous,
professing Jew, who was waiting and hoping for the kingdom!
So in his doctrine there seemed many contradictions to the fleshly understanding;
for one while he said, "`I judge no man;`" for I came not to condemn the world:
and yet was not he continually judging and condemning the Scribes, the Pharisees,
the Priests, the Lawyers, and that whole generation of professors?
So again, he came to seek and save that which was lost; to preach the gospel of peace;
and yet another while he saith, he came not to send peace, but a sword,
and to kindle a fire, and to set men at variance, etc.
Again, one while he said, "`I and my Father are one;`" another time,
"`My Father is greater than I.`" One while he bid men
do as the Scribes and Pharisees taught;
another while he bid men beware of the leaven or doctrine
of the Pharisees and Sadducees. Matt. 16:12.

But to what purpose should I heap up any more instances?
O thou that readest this,
wait to know in thy self the ear that cannot hear Christ`'s doctrine;
while thou condemnest the Jews,
do not run into the same error of unbelief and gainsaying;
but wait to know the voice of Christ in this day,
and to receive the ear that can hear it; for though thou shouldst be willing to hear,
yet thou canst not till thy ear be opened.
Nicodemus,
who could acknowledge Christ "`a teacher come from God,`" yet could
not receive the doctrine of the new birth from him. John 3:4.
And there were many things the disciples themselves were not able to bear:
for when, at a certain time, he spake of "`giving his flesh to eat,`" not only the Jews, John 6:52.
but they also, stumbled.
ver. 61. And who is there among professors that can now bear it,
or receive Christ`'s own interpretation of it?
who saith,
that "`the flesh`" (which they understood) "`profiteth nothing;`" but
the flesh which he meant was "`spirit and life.`" ver. 63.

5+++.+++ At his practices and conversation.
"`How is it that he eateth with publicans and sinners.`" Mark 2:16.
"`Behold a gluttonous man,
and a wine-bibber; a friend of publicans and sinners.`" Luke 7:34. "`This man,
if he were a prophet,
would have known who and what manner of woman this is that toucheth him;
for she is a sinner.`" Luke 7:39. At the publicans and sinners drawing nigh to hear him,
the Pharisees and Scribes were offended, and murmured, saying,
"`This man receiveth sinners,
and eateth with them.`" Luke 15:1-2. And when he went to Zaccheus`'s house,
they all murmured, saying,
"`that he was gone to be guest with a man that is a sinner.`" Luke 19:7.

Again; because he healed on the sabbath,
and justified his disciples in plucking of ears of corn on the sabbath,
"`they were filled with madness,
and communed what they might do to him,`" Luke 6:3. "`and took
counsel how they might destroy him.`" Mark 3:5-6. Another time,
the ruler of the synagogue spake with indignation about it. Luke 13:14.
Yea, "`the Jews did persecute Jesus, and sought to slay him,
because he had healed a man, and bid him take up his bed and walk,
on the sabbath-day.`" John 5:16-8. And some of them
made it a strong argument against him,
"`This man is not of God,
because he keepeth not the sabbath-day.`" John 9:16. What! come from God,
and be a breaker of ordinances!
Can these two stand together?
Read and consider.
What more strict ordinance of God under the law than the sabbath?
What one ordinance more conducing to the honor and worship of God?
Did not their whole religion and worship much depend upon it?
How could this possibly but be a great offence to them in that spirit,
and literal wisdom from the scriptures, wherein they stood?
Yet Christ, in his fleshly appearance, was Lord of the sabbath;
and in his spiritual appearance he doth not lose his dominion.

Again; they excepted against him, that he did not teach his disciples to fast and pray,
as John did, Luke 5:33,
but could suffer them to transgress the traditions of the elders. Matt. 15:2.
He was not strict after the Jewish way of devotion,
nor strict after John`'s way neither;
but against the traditions of the godly elders of the Jewish church;
against sanctifying of the Lord`'s sabbath (justifying
his disciples in plucking ears of corn thereon;
whereas their fore-fathers the Jews were not so much as to gather manna on that day);
against fasting and prayer:
for he justified his disciples in that they did not fast and pray as John did, saying,
"`How could they mourn while the bridegroom was with them? Matt. 9:15.
And consider which way the Jews (in the
state they stood) could understand such an answer as this,
to rest satisfied therewith.

6+++.+++ They excepted "`against his miracles,`"
partly because he did them on the sabbath-day, John 9:16.
whereupon, they concluded he could not be of God; for if he had been of God,
he would have observed the day which God commanded:
and if he wrought them not by the power of God, by whose power then must he work them?
So they concluded,
"`He casteth out devils by the prince of devils.`" Matt. 9:34. "`He hath Beelzebub,
and by the prince of devils casteth he out devils.`" Mark 3:22.
And having thus concluded in themselves,
there was no ear open in them to hear any thing that might be said to the contrary.
And again, partly because he did not answer their wills,
in giving them such a sign as they required: for this was still their tone,
"`Master we would see a sign from thee.`" Matt. 12:38. "`What sign showest thou to us,
seeing that thou dost these things?`" John 2:18.
And they more particularly express what sign;
they would have a "`sign from heaven.`" Luke 11:16. "`What sign showest thou,
that we may see and believe thee?`" John 6:30. We are ready to be convinced,
we are ready to believe, if thou wouldst give us sufficient ground of believing in thee.
As for all thy healing people, and casting out devils, Beelzebub, the prince of devils,
may furnish thee with power wherewith to deceive
and bewitch us from the law and ordinances of Moses,
which we are sure are of God; but show us a sign from heaven,
or else blame us not for not leaving Moses to run after thee.

7+++.+++ They excepted at the testimony which the Spirit of God in him gave concerning him.
When he spake the inward testimony, which the Spirit of God gave from within, saying,
"`I am the light of the world; he that followeth me shall not walk in darkness,
but shall have the light of life,`" John 8:12, they presently cried out,
"`Thou bearest record of thyself; thy record is not true.`" ver. 13. Mark his answer:
"`It is written in your law, that the testimony of two men is true;
I am one that bear witness of myself,
and the Father that sent me beareth witness of me.`" ver.
17-18. How would such an answer pass now in these days,
though the same life should speak it?
Would not the wise professors of this age even hoot at it?
Yet the thing is known at this day, even the life which the Father begets,
and the Father`'s testifying of it, and with it.
And thou that readest this, mightest know it,
couldst thou wait in the loss of thine own life, wisdom, and knowledge, for it.

8+++.+++ They excepted against his disciples and followers, which were women, publicans,
and sinners; the common people, yea, the meanest, the poorest,
and most ignorant (in their account), who were fittest to be deluded and led away.
"`Are ye also deceived?
Have any of the Rulers, or of the Pharisees, believed on him?
But this people who know not the law are accursed.`" John 7:47-49. The common people,
the ignorant people, the unsettled people, such as know not the law,
such as understand not the Scriptures, they run after him, and cry him up;
but which of the settled ones, which of the truly zealous ones,
which of the wise men in the knowledge of the law and prophets,
which of the orthodox Scribes and Pharisees, who keep close to Moses,
which of these believe in him?
Whom of them can he deceive?
As for the heady people, who, for want of knowledge from the Scriptures,
are ready to run after every new fangle, they are not worth the minding,
they are accursed; and therefore no marvel,
though God give them up to follow this deceiver, and to cry up his new light,
and forsake the good old light of Moses and the prophets.

9+++.+++ They excepted against him, that he did not rebuke his disciples,
and the multitude (spreading their garments, cutting down branches from the trees,
and strewing them in the way), with the children that cried Hosanna to him,
as he rode on the ass`'s colt to Jerusalem; but he rather justified them. Luke 19:39-40.
and Matt. 21:15-16. What a ridiculous and vain-glorious
piece of pageantry would this seem to the fleshly-wise eye?

10+++.+++ That he did not show sufficient authority for what he did.
"`By what authority dost thou these things; and who gave thee this authority?`" etc. Mark 11:28.
Thou takest upon thee great authority over the people of God,
over their teachers, yea, over God`'s temple, sabbath, and ordinances;
but where is thy authority so to do?
Show us that, etc.

11+++.+++ They excepted when he spoke of his sufferings and death.
"`We have heard in our law that Christ abideth forever;
and how sayest thou the Son of man must be lifted up!
Who is the Son of man?`" John 12:34. Surely he that is to be lifted
up cannot be the Christ that is to abide forever,
and not to die!
So that here, in one breath,
thou hast overthrown all that thou hast been setting up by thy preaching and miracles.
Now which way could they understand this thing?
Nay, the very disciples themselves could not swallow it, but were startled at it;
and Christ was fain to hide it a long time from them.
And yet if there be any thing held forth now in these days,
by the same Spirit (as concerning light and perfection,
or other truths which are seen in the Spirit),
because men cannot apprehend them with their carnal understanding,
and make them agree with their carnal knowledge of the Scriptures,
what liberty do they take to themselves to speak both against the truth itself,
and also against them who have seen these things in the Spirit,
and speak them from the Spirit!
Now whosoever becomes a disciple, must wait in the obedience to know the doctrine,
and not think to enter with that wisdom and carnal reasoning from the Scriptures,
which the Scribes and Pharisees, and professors of that age were shut out with.

There were many other things which they could not but except against;
as at his answers to their questions, to which sometimes he was silent,
and gave no answer at all; at other times, he answered not directly, but in parables.
And how offensive is this to man`'s wisdom, who requires a positive and direct answer!
And sometimes his answers might seem quite from the thing, as John 12:34-35.

His not giving respect to persons (for it was a known
thing of him that he regarded not men`'s persons.
Matt. 22:16) could not be very pleasing to them, who loved greetings,
and sought honor one of another.
He showed not respect to Herod the king; but spake contemptuously of him,
as men would account it: "`Go,`" saith he,
"`and tell that fox.`" He did not show respect to the
reverend and grave doctors of the law;
nay, nor to the high priest himself.
Nay, he did not show respect to his own disciples;
but said to Peter (when he mildly and affectionately desired
his death might be avoided) "`Get thee behind me,
Satan.`" How harsh and rough a reply might this seem!
If Peter had erred, through his affection and tenderness to his Master,
a meek spirit would gently have informed him; but to call him devil, and say,
"`Get thee behind me;`" what kind of spirit doth this savor of?
would that professing Jew say, who knoweth not the true meekness,
but seeks after a fleshly meekness,
which is a servant to the fleshly wisdom and prudence, but not true-born.
Nay, he did not speak respectfully to his own mother (as man`'s spirit,
by its rule of respect, would judge and condemn him); but said, "`Woman,
what have I to do with thee?`" John 2:4. And in a manner denied all his relations. Matt. 12:48.

Lastly (to instance no more),
at his harsh censures of all the professors of that age (who observed the law of Moses,
and Israel`'s statutes), with all their laborious and godly teachers;
justifying none but himself, and what he taught, and a few of his followers.
He told them, that they had not the "`love of God in them.`" John 5:42. Did not this,
think ye, seem to them a very harsh charge?
And why not the love of God?
Because they did not follow him and his new doctrine?
Yea, would they be ready to say, they did love God, and kept his commandments, sabbaths,
and ordinances, which he transgressed.

He laid this also to their charge, that they did not believe Moses. John 5:46.
What an unjust charge might this seem, when they were so zealous for Moses;
and their very dislike of him, and controversy against him,
were for the sake of the law and ordinances of Moses!

Another charge he laid to them was, that they were not the children of Abraham,
or of God; but of the devil. John 8:39,42,44.
What a rash, censorious man might they account him,
thus to speak of them, who were the human seed of Abraham,
who were such strict observers of God`'s laws and
ordinances (which is the property of his children),
and such enemies to the devil,
that they would not be drawn from the truths and
way of worship taught by Moses and the prophets;
no, not by all the miracles he could work!

He called them "`a faithless and perverse generation.`" Matt. 17:17.

He told them that they did not know God;
though they said with confidence that he was their God. John 8:54-55.
How could they bear this?
They had been studying the law and the prophets,
and had a great stock of knowledge from thence,
and were strict and exact in worship (some of them, as well as Paul, might be,
according to the law, blameless).
And now to be told that they did not know God!
Nay, he that aboundeth in knowledge, devotion, and worship,
yet not being in the life and pure power of the Spirit,
hath not one dram of the true knowledge.

He told them that they should "`die in their sins.`" John 8:21. (Oh, hard word,
and severe judgment!) And yet he had told them a little before, that he judged no man.
ver. 15. Yea, they did think themselves exceedingly wronged by him;
and thought that no man that had any thing of God in him could speak such things,
but only one that was an enemy to the people of God, and led by the spirit of Satan.
To this effect they express themselves, ver. 48. of that chapter,
"`Say we not well that thou art a Samaritan, and hast a devil?`"

Yea, when he charged them with going about to kill him,
they seemed in themselves so clear in their own consciences, that they answered,
"`Thou hast a devil.
Who goes about to kill thee?`" John 7:20. How easily might they close up the controversy,
and, by this very thing, conclude him to be a false prophet!
He says, we went about to kill him;
when (God knows) there was not such a thing in our hearts.
Can this man be a true prophet?
Yet Christ knew the professing Jew to be the murderer, and,
in and for his religion`'s sake, still seeking to slay him.
And there is no such murderer of Christ (the life) upon the earth,
as the zealous professor and worshipper out of the life.
He that is in the life cannot persecute any man;
he that is out of the life cannot but persecute him that is in the life.
Hereby the true and false Christian may be discerned by the weakest simple and single eye.

And then for their teachers and expounders of the law,
how exceedingly bitter did he seem against them! and how
heavy things was he continually laying to their charge!
He called them blind guides, hypocrites, painted sepulchres, graves which appear not,
and pronounced woe upon woe against them.
Read that one place, Matt. 23:33. "`Ye serpents, ye generation of vipers,
how can you escape the damnation of hell?`" What! speak thus of our zealous teachers,
who study the law, are strict in practising of the ordinances,
and take such pains to instruct us in the mind of God from Moses and the prophets!
Was such a man as this fit to live?
Nay, and he does not show a gospel spirit.
Mark how sharp and bitter his words come from him (for indeed a sharper speech,
with greater vehemency and indignation of spirit, can hardly be spoken);
and they might seem to aggravate this sharp condemnation of his from his own confession.
He himself had confessed that they sat in Moses`' chair.
Now he might have shown some honor to Moses`' chair, and to their office,
which was of God, and doubtless good,
and not have gone about to make them thus odious in the eyes of the people.
Nay, he himself had bid men do as they said, but in ver. 3. of that chapter.
Now was it likely that ever men should mind what they said, or observe their doctrine,
when he had thus represented them "`as oppressors of the
conscience,`" ver. 4. "`as devourers of widows`' houses,
and making long prayers in hypocrisy,`" ver. 14. as "`making their
proselytes more the children of hell than themselves,`" ver. 15.
as "`neglecters of the weightier matters of the law,
judgment, mercy, and faith,`" ver. 23. as "`appearing righteous to men,
but full of hypocrisy and iniquity,`" ver. 28. as "`of the same generation that
killed the prophets,`" ver. 31-32. as "`deceivers;`" as "`such as led into the ditch;
and bid men beware of their leaven;`" were not these
good kind of encouragements for people to hear them?
Yea, he charged them with "`shutting up the kingdom of heaven against men,
and not going in themselves,
nor suffering men to enter that were going in.`" ver. 13. How could
they observe what they taught without hearing them?
And would Christ wish any to hear such men as these?
Yet for all this, without doubt,
they were not without their justifications against Christ in these respects;
and also had their charges, on the other hand, ready against him.
Now, how did they shut up the kingdom of heaven against men?
Did they not teach the law, and direct men to the ordinances of God,
and open the prophets`' words to them?
Was this shutting up the kingdom of heaven?
and would not they suffer men to enter?
Why, their work was to win people to their profession;
they would compass sea and land to make a proselyte.
How stiffly might the Jews have pleaded against Christ,
that he did slander their godly ministers,
who were very painful and zealous in opening the Scriptures, and teaching the way of God!
Nay, he himself could not deny but they taught well; for he himself saith,
"`Whatsoever they bid you observe, that observe and do.`" Matt. 23:3. But mark now,
that ye may understand the thing.
It is thus:
any teaching or expounding the Scriptures out of the life shuts up the kingdom:
for the life is the kingdom, and words from the life yield the savor of the kingdom;
but words out of it, though ever so good and true, reach not to the life in another;
but only build up a knowledge in the contrary wisdom,
and teach to hold the truth in the unrighteousness, where Satan`'s kingdom stands,
and where he hath the dominion over all that is brought thither.
And so this kind of teaching and knowledge shuts up the door and way of life,
and must be lost, before the kingdom can be found.

They shut up the true kingdom; but they opened another kingdom;
they opened the kingdom another way (which was in truth shutting of it);
and they had disciples and children of the kingdom,
whom they tickled with the hope of life, and fed with promises and comforts;
but these the Lord would shut out.
"`Many shall come from the east and west, and shall sit down with Abraham, and Isaac,
and Jacob, in the kingdom of heaven;
but the children of the kingdom shall be cast out into utter darkness.`" Matt. 8:11-12.
This is true at this day in the present dispensation,
as it was then in that dispensation; though men make it a great accusation against us,
charging us that we say none are the people of God but ourselves,
and as if all were damned but we.
These are men`'s harsh and unsavory expressions; we use not to speak after this manner,
but soberly open the state of the thing as it stands in the truth
(and as it hath been revealed unto us by him who is true,
and cannot lie); which is thus:

That through which men are saved, is the dispensation of Truth in their age.
The measure of light which God gives forth in every age,
that is the means and proper way of salvation in that age: and whatever men get,
or profess of the knowledge of Truth declared in former ages,
yet making use of that to withstand the present dispensation of Truth in their age,
they cannot thereby be saved;
but may thereby be hardened against that which should save them.
And this we are assured of from the Lord,
that as the Jews could not be saved by the law of Moses (making use of it in opposition
to the shining of the light of God in the prophets in their several ages),
nor afterwards could be saved by magnifying and observing
both the words of Moses and the prophets,
and their belief from thence of a Messiah to come (making use of
those things to oppose that appearance of Christ in the flesh,
which was the dispensation of their day then);
no more can any professors be saved now by the belief of a Christ come,
or any thing which they can learn or practise from the Scriptures,
making use thereof to oppose the dispensation of this day;
which dispensation is the immediate and powerful breaking forth of the light
of the Spirit in the hearts of God`'s people (who have earnestly sought,
and in much sorrow and perplexity of spirit longed and waited for him),
after this long dark night of the antichristian apostasy.

There remain yet some other exceptions against him,
about the time of his suffering death, with his hard usage,
which should not wholly be passed over, as:

1+++.+++ His disrespectful or irreverent answering of the high-priest, as it seemed to them,
when he asked him of his doctrine, John 18:19. his answer was,
that "`he spake openly in the world, not in secret; Why askest thou me?
Ask them that heard me.`" Whereupon one of the officers struck him, saying,
"`Answerest thou the high-priest so?`" ver. 22. The plainness
and simplicity of the life (which bows to God,
and cannot regard man in the transgression) seem
rude and unmannerly to the lofty spirit of the world.

2+++.+++ His silence at the testimonies brought against him,
and to the high-priest when he questioned him. Mark 14:60-61.
Indeed either the speaking or silence in the life,
is offensive to the carnal professor, who knoweth not the law of life in this particular;
but can either speak or be silent, according to his own will.
This is the difference between the true and the false Christian;
the false Christian`'s knowledge and religion stand in his own will,
in his own understanding; he speaks in his own time;
both which are crucified in him that is born of the Spirit.

3+++.+++ When he did speak the truth himself, the high-priest rent his clothes,
and charged him with blasphemy. Matt. 26:65.
And those that were by fell in with the high-priest, and said,
he was "`guilty of death.`" ver. 66. Then they "`spit on his face, and buffeted him,
and smote him, and mocked him, and blind-folded him, and struck him on the face,
bidding him prophesy who smote him.`" Matt. 26:67-68. and Luke 22:63-64.

When they brought him to Pilate,
they would have Pilate take it for granted that he was an evil-doer, and worthy of death:
for when Pilate asked for their accusation against him, they answer,
"`If he were not a malefactor,
we would not have delivered him up unto thee.`" John
18:29-30. Pilate refusing so to proceed in judgment,
ver. 31. they begin to bring in their charges:
"`We found this fellow perverting the nation, and forbidding to give tribute to Caesar,
saying, that he himself is Christ, a king.`" Luke 23:2. Pilate examines him herein;
but professes he can find no fault in him at all. John 18:38.
Then the chief priests accused him of many other things, Mark 15:3.
and were more fierce, saying, "`He stirreth up the people,
teaching throughout all Jewry,
beginning from Galilee to this place.`" (This indeed was his great offence,
he taught with the authority of the Spirit, and not as the Scribes).
Then Pilate sent him to Herod (where the chief priests
and scribes stood vehemently accusing him),
who questioned him much; but he answered him nothing.
And "`Herod, with his men of war, set him at nought, and mocked him,
and arrayed him in a gorgeous robe,
and sent him back to Pilate.`" Luke 23:9-11. Pilate professed
that he could not find him guilty of this second charge,
neither of perverting the people, ver. 14. therefore, chastising him,
he would release him, ver. 18. but the people,
by the persuasion of the chief priest and elders, cried all at once, "`Away with this man,
and release unto us Barabbas,`" ver. 18. but let him be crucified; "`Crucify him,
crucify him!`" ver. 21, etc.
Now when Pilate had scourged him, and the soldiers had stripped him,
and put him on a scarlet robe, and had put a crown of platted thorns on his head,
and a reed in his right hand, and had bowed the knee to him in mockery, and spit on him,
and smote him with a reed, he brings him forth to them again,
hoping this might appease their malice,
and they might be content to spare his being crucified.
They tell him they have a law, and by their law he ought to die,
because he made himself the Son of God. John 19:4,7.
(See how they turn and wind every way to make the innocent an offender,
and to make some law, of one kind or other,
take hold of him!) But when all their accusations would not prevail with Pilate,
but still (from the sense of his innocency) he had a mind to release him,
they used another subtle artifice, telling him, "`If he let this man go,
he was not Caesar`'s friend.`" John 19:12. This carries it with Pilate:
now he disputes no further; but delivers him to their will. Luke 23:25.

Now thou who readest this, take heed of judging the Jews for all this wickedness,
while the same nature is alive in thee which did all this in them:
for assuredly thou (in whom that nature which did it in
them is not subdued) wouldst have done the same thing,
hadst thou lived in those days.
Thou that disdainest and persecutest the appearance of Christ in this age,
wouldst have disdained and have persecuted his appearance in that age.
Do not deceive thy soul.

The Jews did as little think that ever they should have put a prophet,
or any good man to death (much less the Messiah) as thou canst: yea,
they could blame their fathers for killing the prophets, and say,
If they had lived in those days, they would not have done it;
and yet dost not thou read what they did?
The persecuting Spirit was ever blind,
and could in no age read its evil and bitter nature,
and its enmity against the life and power.
Be not thou blind in thy day, as they were in theirs; and an enemy,
under pretence of being a friend.

4+++.+++ Another exception or argument against him, about the time of his suffering death, was,
that he did not put forth his power to save himself from the cross; "`He saved others,
let him save himself,`" if he be Christ, the chosen of God. Luke 23:35.
Is it likely that this is the Son of God,
and that he did so many miracles by the power of God,
and cannot now save himself from the cross?
This his suffering death on the cross did a little stumble some of the disciples,
as may appear, Luke 24:20-21.
and was enough to have overturned
the faith of any which stood not in the Spirit,
and in the power.
The soldiers also could mock, and manage this argument against him, saying,
"`If thou be the king of the Jews,
save thyself.`" Luke 23:37. And they that passed by reviled him, wagging their heads,
and saying, "`Thou that destroyest the temple, and buildest it in three days,
save thyself.
If thou be the Son of God,
come down from the cross.`" Matt. 27:39-40. Likewise the chief priests,
with the Scribes and elders mocked among themselves, saying, "`He saved others,
himself he cannot save.
Let Christ, the king of Israel, descend now from the cross, that we may see,
and believe.`" Mark 15:31-32. One of the thieves also railed on him, saying,
"`If thou be the Christ,
save thyself and us.`" Luke 23:39. And when he cried out to his God, "`Eli, Eli,
etc.`" they derided him: "`This man calleth for Elias;
let us see whether Elias will come and save him.`" Matt. 27:47,49.
And after he was dead,
the chief priests and Pharisees spake of him as of a known deceiver, ver. 63. and seem,
in a pious zeal for the church, to take care that there be no further occasion,
after his death, for the reviving and spreading of his deceit and errors.
ver. 94. Thus the Holy One, the Pure One, the Just and True One,
(in whose heart and mouth was no guile found) was numbered among transgressors,
accounted a deceiver and put to death as a blasphemer,
by the zealous priests and professors of that age,
who were so confident of the righteousness of their
cause (on the behalf of the law of Moses,
and their sabbaths, temple, etc.) against him, that when Pilate washed his hands,
as clear of his blood, all the people answered, and said, "`His blood be on us,
and on our children.`" Matt. 27:25.

Now let men consider what the great exceptions are,
which they have against the living appearance of Christ in his Spirit,
now towards the close of the apostasy, and against us his witnesses,
whom the Lord hath called forth to testify his name.
Many exceptions men have against our persons, our doctrine, our practices,
for want of miracles, etc.
Is this generation more wise or more just in their exceptions than the former was?
Consider the main ones a little.

Their great exceptions against our doctrine are:

1+++.+++ That we preach up a light within, and that he that receiveth that light,
receiveth a perfect gift; and growing up in it, groweth up to perfection,
which in this life (through faith and obedience to
this light or perfect gift) may be attained,
and the body of sin put off, and the new man, Christ, put on.

Ans.
Indeed we cannot but preach up the Light within,
and declare unto men how great things it hath done for us;
even that which we could never by any means meet with from any light without.
And this is perfect, and tends to make perfect, carrying on its work daily.
Now he that feels its virtue, cannot doubt of its power.
He that seeth the body of sin daily going off, cannot doubt but he may be stripped.
Indeed, if a man strive against sin in his own will, and by his own gathered knowledge,
he cannot get much ground, and so it is hard for him to believe perfection.
But he that feels unity with that which is perfect,
cannot but acknowledge that it is able to perfect him,
and in faith and patience is encouraged to hope and wait for it.

2+++.+++ That we deny that Christ which died at Jerusalem, and his imputed righteousness,
and set up an inherent righteousness.

Ans.
We know no other Christ than that which died at Jerusalem,
only we confess our chief knowledge of him is in the Spirit.
And as Christ said in the days of his flesh, that the way to know his Father,
was to know him; and he that knew him knew the Father also; so we now witness,
that the way to know Christ is to know the Spirit; and that he that knoweth the Spirit,
knoweth Christ also; with whom Christ is one, and from whom he cannot be separated.
And as for imputed righteousness, it is too precious a thing to us, to be denied by us.
That which we deny, is men`'s putting it out of its place,
applying it to them who are not in the true faith, and walk not in the true light:
for in the true light, where the fellowship is with the Father and the Son,
there alone the blood cleanseth. 1 John 1:7.
And there alone the righteousness is imputed to him,
who is cleansed by the blood in the light, and not to him who knows it not.
And as for inherent righteousness, we meddle not with that word, but this we say;
That our life exceedingly lies in feeling the righteousness
of Christ wrought and revealed in us;
and we wish men could come out of the reasoning about it,
into the feeling of the same thing with us;
for then we are sure they would not so sharply, nor so long contend.

3+++.+++ That we deny the ordinances, and means of salvation.

Ans.
We deny nothing that the apostles and Christians formerly practised;
nor do we deny any thing that any now practise in the light, and in the faith;
but the setting up of such things in the will, that we deny;
or the imitating these without the command of the Spirit, that we deny also.
And this we testify, that antichrist crept in here,
and that they are his great cover to keep men from the life;
and therefore warn men to mind the life,
and to take heed they be not kept from the substance by the shadows,
where antichrist lies lurking, to bewitch from the substance.
And we are sure, that these in antichrist`'s hands, are not the means of salvation;
but keep from the sight of the holy city, where the life and salvation are.
And we read that the outward court was given to the Gentiles;
who "`trod under foot the holy city.`" Rev. 11:2. And we have found by experience,
that, while we ourselves were crying up the outward court,
we did trample under foot the city, though we then knew it not.

Their exceptions against our persons are, that we are ignorant, illiterate,
and also unsettled persons, who have still been seeking up and down, etc.

Ans.
What persons are fittest for God to make use of,
towards the recovery of his people out of the apostasy?
Doth not God choose that which is weak and mean and contemptible,
that his glory might the more appear?
Is not this a more likely way for him to steal upon the world,
than if he appeared in the wise and learned ones?
And among whom is his appearance to be expected?
Among those who are settled upon their lees in the apostasy;
or among those who have mourned, panted, and sought to come out of it,
and could not be settled without his appearing to them,
and fixing their feet upon the rock?
But have we been unsettled, since God hath fastened us on the living foundation?
Nay, here is no more going out;
but he that abides faithful remains a pillar in the house of God.

Men except likewise against our practices, as that we show not respect to persons,
and that we are not strict (after their manner) in duties, etc.

Ans.
We have heard that voice, "`Fear God,
and give glory to him,`" Rev. 14:7. (not only as it is written there,
but in Spirit:) and where the Lord is exalted, the glory of the creature falls;
read Isa. 2. how all falls in that day, that God alone might be exalted.
And we cannot, in this mighty day of the Lord,
any longer give to man that honor which he hath gathered in the fall,
and which pleaseth the fallen nature, and not that which is born of God.
And for duties, we have bewailed, in the sight of the Lord,
our former running into duties without his Spirit: and we must confess,
we can only pray in the Spirit; sing in the Spirit; wait in the Spirit;
speak in the Spirit (as that gives utterance), and not of ourselves, or when we will;
but as we see life, strength, and power from on high, leading and assisting us.
And our religion consists neither in willing nor running,
but in waiting on the Spirit and power of the Lord, to work all in us and for us.
All these things we look upon to be our duty, and practise them.

It is likewise excepted against us, that we do not work miracles.

Ans.
We point to that which wrought all the outward miracles formerly,
and which now worketh great inward miracles in Spirit; and we are sure the same power,
which we have received the Gospel in, is of the same healing virtue.
But that power worketh according to the purpose of its own will,
and not according to the will of man (yea, though Paul had the gift of healing,
yet he "`left Trophimus at Miletum sick.`" 2 Tim. 4:20);
neither was the will or wisdom of man satisfied in all those
miracles which Christ and the apostles wrought.
It is enough for us to feel and live in the moving of the power; in which we rejoice,
and are more satisfied (that by it our names are written in the Book of Life) than we
could be by any such outward and visible appearance and manifestation of it.
But if we did work outward miracles,
yet if thou hadst not an inward eye to see them with,
thou wouldst not be able to distinguish by what power they were wrought.

To what purpose should I mention any more particulars?
Is it not enough?
Oh! fear before the Lord! and do not lose the present dispensation of life through
mistake (or because ye cannot have things suited to your corrupt wills);
but know the Gospel, which is an inward dispensation,
and doth not consist in outward shadows, but in inward virtue, life, and power:
"`For the kingdom of God is righteousness, and peace,
and joy in the Holy Spirit.`" Come to wait for that, to feel that, to unite there;
and then we shall not differ about that which is outward.
But it is antichrist`'s way, by the magistrate`' power,
to force an agreement about the outward,
which destroys that tenderness of conscience which preserves the inward.

And now let me put one question to you;
Where is the deceit of the ages after Christ to be expected?
Did the Jews deny Moses and the prophets`' writings, or ordinances?
Nay, were they not very zealous for these?
And were not these their cover, under which they persecuted Christ,
and vented all their malice against him?
So can it be expected now,
that the deceivers of this age should deny the apostles`' writings,
or the practices therein mentioned; Or is it not rather to be expected,
that under their crying up of these, they should hide their enmity against the life?
Search and see,
hath not every after-age of professors taken up the words and practices
of them who were persecuted in the foregoing age;
and under the profession of those words and practices,
have hid their spirit of persecution?
There is a remnant only among professors to be saved;
the generality of them have still been persecutors, creeping into the form,
getting that for a cover upon their backs, and then fighting against the life and power.
Oh! wait on the Lord in his fear,
that ye may be found worthy to know the persecuted truth on the one hand,
and the persecuting spirit on the other hand, in this day of large profession,
and also of bitter persecution!

Now what might be the cause, or how could it come to pass,
that the zealous worshippers of that age should thus err in their zeal,
and be thus heady and rash against him, whom they looked for to be their Saviour?
How came they thus to err in vision, and stumble in judgment, in so weighty a matter?
Show unto us the cause, that we may see whether the same cause be not in us:
for undoubtedly if it be, it will produce the same effect,
and so we may ignorantly draw upon our heads the same heavy wrath in our day,
that they did in their day.

Ans.
The causes were very many; I may mention some few of the principal ones;
which if they be seen into and removed, by that power which is able to do it,
such as are of a more inferior influence, will not be able to stand.

1+++.+++ One cause of their blind zeal, and bitterness against Christ, was,
Their ignorance of the Scriptures, and of the power of God.
If they had known the Scriptures in the true light, they could not but have known Christ,
from whom the Scriptures were given forth; and if they had known the power of God,
they could not but have known him who came in the power; yea, who was the power.
They had knowledge enough of both these one way; that is in the letter:
they knew the words of scripture (they could make large expositions of them),
they knew what was said in scripture concerning the power of God,
but they knew not the thing itself; and so turned against it,
and made use of the words (which came from it, and testified of it) against it.

2+++.+++ A second cause of this their sad miscarriage in their zeal,
was Their putting the law and ordinances, and writings of the prophets,
out of their proper places.
They exceedingly magnified and cried them up,
in that carnal way wherein they apprehended and practised them,
but understood not the right end and use of them.
And by these means, practising the shadows in the carnal mind, they lost the substance,
which the proper use of the shadows was to have pointed them unto.

3+++.+++ Their high conceits of the goodness of their state in relation to God,
and of the certainty of their knowledge of the truths of God from Moses and the prophets.
They were confident they knew God aright, and that he was their Father,
and that they were his children and people.
And so Christ appearing in a seeming contrariety to these
(notwithstanding all his powerful preaching and miracles),
they made no question but they might boldly conclude him not to be of God.

4+++.+++ Christ`'s coming in a way that they looked not for him.
They had concluded from the Scriptures how Christ must appear;
and he coming in a far different manner, they could not own him,
but looked upon him as a deceiver, one that pretended to be Christ,
but was not like to what the Scripture said of Christ.
So what the scripture saith of Christ`'s second coming,
is hid as much from the carnal eye of professors in this age,
as what was said concerning his first coming, was hid from them in their age;
and he will steal upon them as a thief, at a time, and in a way, and after a manner,
that they expect not.

5+++.+++ (Which is the main one, and cause of all the former.)
Because they were from the light within,
from the true light in their own hearts and consciences.
The light within is the great ordinance of God,
and the proper means to give the knowledge of him (2 Cor. 4:6);
without which it was never received under any dispensation:
for the light that shines abroad, or from without,
can alone be known and received by the light that shines within.
Christ himself opens this in a parable; "`The light of the body`" (saith he) "`is the eye;
if, therefore,
thine eye be single`" (clear without beams or motes) "`thy whole
body shall be full of light.`" Matt. 6:22. But if that be evil,
if that be dark, if that be closed by the god of this world, all Moses`' words,
all the prophets`' words, yea, all Christ`'s and his apostles`' words,
cannot give thee light.
Can I see the light of the sun, moon, or stars, or of any fire or candle,
if I have not a natural eye, and if that natural eye be not open?
So neither can I see the light of any dispensation of life,
if I have not an eye within me open, wherewith to see it.
So that that which gives me the sight of the things of God,
is the eye which God hath given me.
By that may be read the eternal power and Godhead in the creatures,
in the books of Moses and the prophets,
in the writings of the evangelists and the apostles, as the Spirit leads and opens.
Yea, the same Spirit, that opened to these without books,
may again open to any of us without books at his
pleasure (and will not be limited to books);
and we then may read also as they did, even within in the Spirit,
and in the immediate life; but without this,
can none of these things of God be read aright.
Now the God of this world had blinded this eye in the Jews; yea,
they themselves had "`stopped their ears, and closed their eyes,`" etc.,
they would not see this way, they would not be converted and healed this way.
They would keep up the knowledge which they had gathered from Moses and the prophets,
without this eye; and with that they would see, or not at all.

Thus being from the light within, they could not see the place of life within,
where life is to be received: they could not see the womb of wisdom, which is within,
and so could not enter in to it, and be born again.
And being not born of the wisdom, how could they justify the wisdom?
Being not born of the light, how could they know or own Christ,
whose coming and appearance was in the light?
For that appearance of Christ the life, in that body of flesh,
could not be discerned by all men`'s wisdom in the letter
(the disciples themselves came not so to know it);
but "`my Father which is in heaven hath revealed it to you.`" And mark it:
the disciples who were illiterate,
and not so knowing of the scriptures that were written of Christ, yet they knew Christ:
but the Scribes and Pharisees, who were very skilful in the letter, could not know him.
What was the reason?
The reason lay in the difference of the eye, or light, wherewith they looked:
the one looked with an outward eye, the other with an inward eye.
And a little inward light will do that, which a great deal of outward light will not do.
And this I can certainly affirm,
that all the light that men can gather from the Scriptures,
cannot give them the knowledge of Christ as he hath appeared in this age; nay,
nor as he hath appeared in any age, since the days of the apostles:
but a little true inward light will give the knowledge of this thing,
and open those scriptures infallibly (in its season) which all the generations
of wise and learned men have been controverting and disputing about,
in that wisdom and searching spirit which is never to understand them.
This then is the main and full reason of this deep error of the Jews,
and their desperate splitting upon the rock, which would have saved them.
They were begotten of the letter, which was given forth in former ages;
but not of the life, which was raised up in their age:
and so they knew not how to turn to the light within,
which alone was able to give them the true and certain knowledge of the things of God.

Now consider these things well,
O ye professors of this age! and take heed that ye
do not fall after the same example of unbelief.
"`Be not high-minded,
but fear.`" Be not so confident of what you have gathered by your wisdom
for truth from the Scriptures (after the manner that they were,
of what they had gathered by their wisdom); but fear,
lest ye should be mistaken as they were:
and wait for the opening of that eye in you which was shut in them; even the true eye,
in the true light, by the holy anointing; where there never was nor can be any mistake.
The Jews fell by unbelief.
Unbelief of What?
They believed the Scriptures,
they believed according to that knowledge they had gathered from the Scriptures;
but they did not believe in the living Word.
They had a knowledge abiding in them, which they had gathered from the Scriptures,
but they had not the living Word abiding in them;
and so their faith was but unbelief (for the living faith
stands in the belief of the living Word in the heart,
which the Scriptures direct to; without the knowledge of which,
all knowledge of words is vain; and without faith in which, all faith is vain also).
Now saith the apostle to the Gentile Christian,
"`Thou standest by faith.`" Rom. 11:20. By what faith?
By faith in that Word in the heart, which they neglected and turned from. Rom. 10:8.
For Moses had taught them,
after the laws and ordinances about worship and sacrifices,
that the Word that they were to obey and do (the Word that could give them life,
and make them obedient to all the commandments without) was in their heart and mouth. Duet. 30:14.
And so the prophet Micah, when they proposed sacrifices and oil,
to please God with, brings them to this which was given to them in common with mankind. Mic. 6:8.
For all ordinances and laws and observations and practices without,
are but to bring to the life within, which is to be found again there, where it was lost,
and still lies slain and hid (even in the field or house where it was lost).
And he that seeks abroad, never finds it;
but when the candle is lighted in his own house, and he searches narrowly in the field,
in his own heart, and the eternal eye begins to open in him; then he cries out,
God was in this place, and I was not aware of it.
Ah! how the enemy bewitched me,
to run from mountain to mountain! and from hill to hill! and hath hereby
covered my eye from beholding the mountain of the Lord`'s house,
and from feeling the spring of my life, which I further and further ran from,
all the while I was seeking abroad.
Therefore, O ye professors, be not so conceited like the Jews,
and running after them into their desolation and misery, but learn wisdom by their fall!
Do not you set up your ordinances and scriptures,
after the manner that they set up theirs; for this is your danger: for this I clearly,
in the light of the Lord, testify to you;
that if ye gather a knowledge and wisdom from the letter of the Scriptures,
after the manner that they did, without knowledge of the Word within,
and without a light within from that Word, ye lose the living faith,
ye are but dead branches; and all your knowledge of scriptures, and practices, and faith,
and duties, etc., that ye here hold and observe, are but for the fire;
and the flames of eternal wrath shall kindle more fiercely upon you because of them,
than upon the Jews;
for ye stumble upon the same stumbling-stone at which they stumbled and fell,
and it will fall upon you also.
And as you have more scriptures than they had,
and the experience of their fall to warn you;
so your destruction will be exceeding dreadful "`if you neglect so great salvation;`"
whereof at this day there are so many living and powerful witnesses,
as they are known and owned to be in the light of the Lord,
though despised in your exalted and conceited wisdom.

Now to help any honest and single hearts among you
over this great stumbling-block of a light within,
consider these few things.

1+++.+++ That all the knowledge, all the true knowledge, that ever ye had of God,
was from a light within.
I do not deny that ye might receive your knowledge through the Scriptures (and
some warmth formerly in those things which ye call ordinances and duties);
but that whereby ye received the knowledge was the light within;
the eye that God secretly opened in your spirits.
This was the way ye then came by it, though ye perhaps might feel the thing,
but not know how ye came by it, even as a babe may see truly,
but doth not understand its own eye, or know how it sees.

2+++.+++ While this eye was kept open in you, your knowledge was true in its measure,
and serviceable to you, and did draw you nearer to God, making you truly tender, meek,
sweet, humble, patient, loving, gentle, and of precious breathings towards God,
and after righteousness.
Oh! how lovely were you to God in this state! "`When Israel was a child,
I loved him.`" God remembereth at this day the kindness of your youth,
and is seeking after you.
Oh! why do ye so harden your hearts against him?

3+++.+++ That wherever this eye is shut, the virtue of the true knowledge is lost,
and the sweet fruits thereof wither.
The outward part of the knowledge may be retained; yea, perhaps increased,
but the life is gone, and the pure sweet savoriness (to God) vanished.
And if this eye were but a little opened again in you,
your death and unsavoriness might be soon seen and felt in you, in all your knowledge,
duties, ordinances; yea, in your very graces and experiences.
You have a faith still; yea, but it wants the savor of your former faith:
ye have some kind of love, gentleness, and meekness; yea,
but it is only a thing formed by the fleshly wisdom and reasoning,
but not natural from the living spring, not such as ye once felt, etc.,
for the true and living eye being shut,
that which is then best (or afterwards attained) is held but in the dead part,
and serves but to feed death.

4+++.+++ The great work and design of the enemy of your
souls is not to steal away the bulk of your knowledge,
or to draw you from ordinances or duties; but to steal the life out of your spirits.
This I have experimented from my childhood:
I might still have knowledge enough of any kind; but that which I wanted was life;
and I was still sick under all the sorts of knowledge that ever I met with,
and under all ordinances and duties, for want of the life.
The Lord had given my soul a taste of true life, whereby I became unsatisfied without it,
and no manner of knowledge or enjoyment could take me up by the way: yea,
when through extremity I seemed willing to be content with any thing;
yet still my heart was sick after that one thing,
which alone could truly ease and satisfy it.
Now if the enemy can prevail herein: to blind the inward eye,
and steal away the life within, he hath enough.
Then abound as much as thou wilt in knowledge, in zeal, in duties, in ordinances,
in reading scriptures, praying, meditating, etc., thou art the surer his hereby,
and so much the better servant to him: for how much the richer thou art in knowledge,
experiences, hopes, and assurance, without the life and power;
so much the more acceptable and honorable and useful art thou in his kingdom.

Therefore see where ye are.
Is the inward eye open in you?
Do ye know the light within?
(Surely he that sees by a light within, can hardly speak evil of it!) Or hath the enemy,
by some of his artifices, drawn a veil over that eye,
wherewith once ye saw in some measure?
Oh! be not slight in a matter of so great weight!
Oh! please not yourselves with the eye of the perishing wisdom, with death`'s eye,
and with death`'s knowledge of scriptures and of the Son of God;
which speaks great words of the fame of true wisdom,
but is a stranger and enemy to the thing!
Oh! life is precious! eternal life is precious!
To have the word of God abiding in the heart,
and to feel the true light give the true life, who can set a value on this!
Ah! do not lose your souls for a trifle;
for a little such knowledge of the Scriptures as the earthly part can gather!
This I cannot but exceedingly despise, although the Scriptures I truly honor,
for their testimony of that whereby I live.
If ye see not the way of life by the inward light, which alone can show it,
ye lose your souls.
If the God of the world hath blinded that eye in you,
what are all your treasures of wisdom and knowledge?
What are all your hopes?
And what will become of you?
All these sparks of your own kindling from scriptures
will not secure you from the bed of sorrow.
O ye several sorts of professors, why will ye die with the uncircumcised?
Why will ye go down into the pit, among them that know not the Lord?

But what shall I say to this generation?
The spiritually-wise foreseeth the storm, and hideth himself;
but the spiritually-foolish run on headily, and are punished.
The clouds have long been gathering;
but the sick eye cannot discern the signs of the times and seasons;
and so because judgment comes not as men expected, they grow hard,
and wear off the sense wherewith they were somewhat
affected at the first threatening of it:
but assuredly both judgment and mercy hasten, and they will come, and will not tarry.

For the same Lord God Almighty,
which confounded the Heathens`' Babel (when their sins and vain confidence were ripe),
which they built to prevent any future flood (for though
they once had the true knowledge of God from an inward light, Rom. 1:21.
yet they soon left that,
"`not liking to retain God in their knowledge,`" ver. 28. but running out into imaginations,
and so building a Babel,
whereby their foolish hearts became darkened to the
light which God had made to shine in them;
which showed what might be known of God unto them.
ver. 19); yea, the Lord God which overthrew the Jews`' Babel,
which they had built from their knowledge of the laws and ordinances of Moses,
and the scriptures written to them (they running out into imaginations also);
whereby they likewise thought to prevent "`the overflowing scourge`" from coming near them,
Isa. 28:15; the same God will overthrow the Christians`' Babel,
which they have built from the prophets`' and apostles`' words (by
their own imaginations and conceivings in the high-mindedness,
out of the fear), whereby they think to escape the deluge of eternal wrath.
(For their city also shall be "`thrown down with violence,`" and
shall be "`found no more at all,`" Rev. 18:21) And the great
work of this day is to discover the rottenness of their wall,
and the untemperedness of the mortar wherewith they had daubed it.
He that readeth, let him understand; but the uncircumcised in heart and ears cannot.
