[.style-blurb, short="To the Parliament"]
== To the Parliament, the Army, and all the Well-affected in the Nation, who have been faithful to the Good Old Cause

[.section-date]
1659

That there hath been a backsliding and turning aside from
the _Good Old Cause_ even by the army (who formerly were glorious
Instruments in the hand of God) hath been lately confessed,
and that they have cause, and desire to take shame to themselves.

Now that they may see the cause of shame that lies upon them,
and may abase themselves in the sight of God, and before all the world,
it behooves them to search narrowly into their backslidings,
and consider the fruits thereof, that they may be truly humbled,
and turned from that Spirit which led them aside,
lest any of them take advantage to make a feigned confession for their own ends,
and fall afresh to seek themselves; and their own Interests, and not the _Good Old Cause,_
singly, and nakedly, as in the sight of the Lord.

Many bad fruits have grown from this corrupt spirit,
and the corrupt course it hath run in these late years,
which would be narrowly searched into, and considered of:
Some few general ones I may mention.

[.numbered-group]
====

[.numbered]
1+++.+++ The name of God hath been blasphemed in the sight of the whole earth,
and that holy Spirit and Power (which many hearts can witness was the beginner and carrier
on of this Work) made a scoff and derision to the enemies of truth in these nations,
and in the nations round about, who watched to see the issue and result of these things.
The controversy was very great and eminent, and drew many eyes upon it,
the Lord was appealed to on both sides to decide it; and many know,
that by his presence and power in the army, the scale was turned,
(even when they were very low, and cried out for prayers;
and made large promises in the day of their distress.) Yea,
the Lord did not desert the army, but heard their prayers,
and the prayers of his people for them, carrying on the deliverance,
until he had given a perfect victory into their hands.
But then the army deserted the Lord;
and just like men that were ruled by the spirit of the world, forgot the Lord,
and his cause and interest, and their fellow companions in the hard travel and service,
and set up themselves, and their own interest, making their general the greatest,
and their officers great.
Thus the Cause was betrayed, the measure of it lost, a private, particular, selfish,
earthly, corrupt interest set up, and men countenanced and advanced,
not according to their fidelity to the _Good Old Cause,_
but according to their compliance with this new selfish interest.

[.numbered]
2+++.+++ The great work of God, both in these nations, and in the world,
hath hereby been turned backward.
In these nations,
that spirit which began this work (when at any time it hath appeared in
simplicity and singleness for the prosecution of it) hath been snibbed;
what was built up formerly, thrown down; and that which was thrown down,
now again built up; so that the face of the nation was changed,
and unrighteous ones came into place and power,
and the innocent and upright (those that feared God, and could not seek themselves,
or the pleasing of men) have been oppressed and crushed.
And if the work was thus stopped in these nations,
its advantage of spreading further must needs be interrupted.
God had raised up a power against oppression, in which he eminently appeared,
even to the dread of the nations round about:
and how far this power should have gone on in his work, by the leadings of his Spirit,
had they waited in his counsel, kept to their Leader,
and not turned aside to another spirit, and to other ends and interests, who can tell?

[.numbered]
3+++.+++ Great and vast treasures have been expended,
for the maintaining of you in greatness in your backslidings,
and the poor have groaned to bear the burden: and while ye have grown thus high,
extravagant, and excessive,
many (who remained faithful) have wanted even that which was their due,
and have undergone great hardships thereby.

[.numbered]
4+++.+++ The account of all the blood which hath been shed lies somewhere.
Was it for a thing of nought?
Was it of no value?
Nay, it was precious in the sight of the Lord;
many (yea very many) in the singleness and simplicity
of their hearts losing their lives for the Cause.
And yet how soon had you forgot all this, casting it, and the cause behind your backs,
and setting up yourselves!
Thus have ye grieved that good Spirit,
which never gave you victory over your enemies for this end, that his name, and cause,
and interest should be forgotten, and yours grow great:
but the name of the Lord should have been exalted by you,
and ye should have remained low and little, both in your own eyes,
and in the eyes of others.
But the Lord hath been veiled by your greatness, and that veil lies upon him at this day:
Read this in the true humility, and in the fear and dread of his great name,
who will be exalted over all,
and whom no power or greatness on earth shall be able to hinder from arising.
Remember these things, O ye backsliding children, and be abased;
that the Lord may forgive you,
and may vouchsafe yet once more to make use of you in his service.

====

But I am jealous over you with a godly jealousy, lest ye should confess, and turn back,
not with an upright heart, but feignedly: and if so,
then you will not lie flat in your spirits, either before the Lord, or before men,
but will be keeping up the greatness ye have got in your backslidings,
and seeking your own interests, and self-ends afresh.
There hath been often a naked, honest, simple, pure thing stirring in the Army,
which the great ones (seeing some present use of) fell in with,
and improved for their own ends; but destroyed the thing itself;
so that it attained not to the bringing forth of that righteous liberty,
and common good which it seemed to aim at (and did indeed aim at in those
in whom the stirring did arise) but was made use of as an advantage to
advance them in their particular interests against their enemies,
and so set them up.
Have ye seen this use made formerly of such lively stirrings in some,
and such fair pretenses in others after righteousness, liberty, and the common good?
Take heed of it now.
Let not the pure stirrings after good,
be betrayed into the selfish lusts and interests of your own corrupt hearts.
Do not fall so hastily to the work of reformation,
nor be not so forward to propose things for settlement;
but wait to be purged from that backsliding spirit (which sticks closer
to you and makes you unfitter for this service than you are aware) that
you may come into a capacity of desiring the common good,
and of being faithful in the prosecution of it;
and put off your greatness and swelling honors that
ye have contracted in the time of your backslidings,
and come at least into an equal balance with them that remained faithful.
Are ye humbled before the Lord for your backslidings, and yet keep your corrupt standings?
Is this true humiliation?
Is this taking of shame to yourselves?
Ah, do not force the Lord to deal with you! do not force the Lord to strip you,
and manifest your shame!
If it be truly in your hearts, that the work of the Lord should go on,
let such be picked out who have not backslidden, and let them carry it on;
and stand ye by a while, till it be made manifest that your hearts are changed,
and there be a testimony given to the nation, that you are truly humbled,
and become men of other spirits: For while this spirit remains in you,
ye will be secretly for yourselves, and cannot possibly be cordial, either to the Lord,
or to the nation, in the work of reformation;
but while you seem to be setting your hands to it, your hearts will be erring from it,
and your endeavors will be to obstruct those whose hearts are entire and faithful to it.

Now to the Parliament, let me say this, Ye have one day more by the good hand of God,
by the great mercy of God, ye have one day more; (not for your righteousness,
not for your fitness for the work; but for the unrighteousness of that power,
which would not go on with the Lord`'s work, but bring back again to _Egypt,_
hath the hand of the Lord been stretched forth against them.) Be not slothful,
be not selfish, be not wise in the flesh:
but know that Wisdom which is to be your Guide and Leader,
and let it be your wisdom to follow.
A Providence hath brought you together; let the same Providence lead you.
Be single and honest to the nation, and upright-hearted toward God;
and if any straits come, be not hasty, but wait for the manifestation of his council,
for the unveiling of his arm to protect you.
Let not the army be your confidence.
Do not any one thing to please the army;
much less a corrupt interest of a part of the army;
but apply your selves to do that which is truly just and righteous in the sight of God,
of the army, and of all men.
The Lord hath as it were new created you, and given you a new being;
look up to him to preserve you, and apply your selves faithfully to his work,
without self-ends and interests in yourselves,
and against all self-ends and interests in others,
leaving it to his power to stand by you and preserve you therein;
and do not join (through fear or favor) with that which is great and powerful,
but with that which is single and honest.
Mind the stirring of that spirit in the army, and in the nation,
which revived the _Good Old Cause;_ and cherish it and cleave to it:
mind likewise the apostatizing spirit, which would color over the apostasy,
and make it seem as little as they could, and frown upon it,
though in persons never so great.
Ye are in the place of God; respect not persons, but righteousness,
and ye shall have honor, even that honor which will stand,
when the vain honor and title which corrupt man aspires after,
whereby his heart is lifted up above his brethren (which
the King of _Israel`'s_ was not to be) shall fall to the ground,
do men what they can.
Open your eyes (that eye in you which alone can see the power that
hath wrought this change) there is the arm of flesh,
and the arm of the Lord before you, choose which you will cleave to.
The Lord hath a work to do, a great work, and he will not want instruments.
Ye have a time of trial, whether ye will become fit instruments in the hand of the Lord;
improve it in his fear and in his wisdom; and do not think yourselves secure,
as ye can gain the present powers on your side; but be single to the Lord,
and he will bring over the hearts of the army and nation to you.
And take heed of your debates; let every man fear his own wisdom and his own will,
in every word he speaks in the House; for that which comes from self,
will be but for self (though under a pretence it may seem to be
for God) but pursue what is manifestly good and righteous,
and not what the wisdom of the serpent can cast a color over, and make appear so.

To those who have remained faithful in the nation, and waited for this day,
I have one word also.
Keep your eye on the Lord; fix not your hopes on the army, or on the Parliament;
but look through them, to him who hath the power over them.
Man is a vain, empty, foolish thing, there is no good to be expected from him.
If the Lord appear in them, and they abide in his fear, and be guided by his counsel,
they may be instruments of good in his hand, otherwise they will prove but broken reeds;
but he that waiteth on the Lord shall not be disappointed,
but shall meet with and receive the good in the Lord`'s season.
The Lord`'s mighty power is at work, he snappeth instruments asunder at his pleasure.
When they are wise, when they are strong,
when they are puffed up in the imaginations of their hearts,
he overturneth them with his finger, and calleth up that which was not,
that which the foot of pride trampled upon.
_The Lord is known by the judgment which he executeth;
the wicked is snared in the work of his own hands._
Wait on the Lord: If these also prove treacherous, his hand can overturn them also;
and he will at length bring forth an instrument, which his soul can take pleasure in,
and which he will make faithful to him in his work.
O nation of _England,_ wait on the Lord! wait on the Lord, O my soul!

[.signed-section-context-close]
From Chalfont in Bucks, the 18. of the 3. mon.
1659.

[.postscript]
====

This from one who is a friend to the Commonwealth, a lover of true Freedom,
and desires the good of all men.

====

[.signed-section-signature]
Isaac Penington the younger.
