== A Brief Account of Some Reasons / (Amongst many that might be given)

[.heading-continuation-blurb]
Why those People called _Quakers_ cannot do some Things on the one hand,
and forbear doing of some Things on the other hand; for which they have suffered,
and do still suffer, so much Violence from the People,
and such sore Persecution from the Teachers and Magistrates of these Nations.
Whereby it may appear to all,
who are willing to take any fair Consideration of their Cause,
that their Sufferings are for Righteousness`' Sake,
because of the Integrity of their Hearts towards God,
and void of any just Ground of Offence towards Man.

[.heading-continuation-blurb]
This account was drawn up thus brief,
for their sakes who want either time or patience to consider of it more at large;
and answers to the heads of their sufferings,
in a particular declaration to the _Parliament._

[.numbered-group]
=====

[.numbered]
1+++.+++ Why we go into meeting-places or markets or other-where to testify to the truth,
and against deceit.

[.discourse-part]
_Reason._
Because we are moved of the Lord so to do.
We are his; and where he bids us witness for him, and against deceivers and their deceit,
we must do it: woe unto us (from the Lord) if we do it not.
If any man do any such thing in his own will, we witness against him,
and the Lord will require it of him.
Now this is no more than the apostles and servants of the Lord have done,
as it is recorded in Scripture.

[.numbered]
2+++.+++ Why we cannot pay tithes.

[.discourse-part]
_Reason._
Because tithes were not a maintenance appointed by Christ for his ministers,
but were set up by the Pope (as the maintenance of
his ministers) since the days of the apostles.
And this maintenance by tithes, Wickliff and others bore a testimony against,
and divers of the martyrs in Queen Mary`'s days suffered for,
as by the articles charged against them, and the testimony that they held forth,
may appear.

[.numbered]
3+++.+++ Why we meet together on the first days of the week, and at other times.

[.discourse-part]
_Reason._
Because we find the Lord drawing of us, and his presence among us in our meetings,
and receive refreshings to our souls thereby.

[.numbered]
4+++.+++ Why we cannot swear.

[.discourse-part]
_Reason._
Because Christ our Lord (who is greater than Moses,
who gave the law about swearing) hath said,
"`Swear not at all;`" and his apostle (who abode in his doctrine) saith, "`Above all things,
my brethren, swear not; neither by heaven, neither by the earth,
neither by any other oath.`" Now mark the drift of Christ,
which is not only to forbid profane and unlawful oaths (for if that were all,
Christ had spoken nothing further nor fuller than Moses had done;
which is contrary to all the instances of the like kind,
whereby he straitens all that had been said by Moses of old time,) but all swearing,
without exception, as may further appear by the instance immediately foregoing,
in the case of divorce, where he expresseth an exception in these words,
"`Saving for the cause of fornication;`" but here is no exception added by Christ;
and the putting in of an exception by man`'s wisdom, destroyeth Christ`'s words,
making his command no straiter than the law of Moses,
which forbad all profane and unlawful swearing. Lev. 19:12.

[.discourse-part]
5+++.+++ Why we cannot put off our hats to men.

[.discourse-part]
_Reason._
Because it lifts up that in man which God will destroy.
It is suitable to that nature which is of the earth, and feeds it.
It is pleasing to the flesh; and that which is an enemy to the flesh,
cannot give it that which feeds and pleaseth it.
If we should please men, we could not be the servants of Christ.
This is the true ground whereupon we cannot do it; and not in contempt to authority,
or any man`'s person.
Neither can we respect men`'s persons; for in so doing we should commit sin,
as saith the apostle.
And let men consider what it is in them that cannot bear with it;
it being done in simplicity of heart upon this account.

[.numbered]
6+++.+++ Why we cannot justly be looked upon as vagrants or sturdy beggars.

[.discourse-part]
_Reason._
Because we beg not, nor pass up and down in any idle way;
but either about our civil employments and occasions, or about the work of our God;
nor are any way burdensome to the nation.
If to be from our dwellings about the work of our God, be accounted the breach of a law,
would not the same law have taken hold on Christ and his apostles,
if it had been in their days?

[.numbered]
7+++.+++ Why we visit friends in prison.

[.discourse-part]
_Reason._
Because they being imprisoned for their obedience to Christ, what we do to them,
we do to him; and we are afraid, lest he should say to us at the great day;
"`I was sick and in prison,
and ye visited me not.`" Now they that are so far from doing this themselves,
that they punish others for doing it, when God shall call them to account,
what will they answer?

[.discourse-part]
8+++.+++ Why we cannot contribute towards the repairing of the steeple-houses,
or pay clerks`' wages.

[.discourse-part]
_Reason._
Because they are places which were erected for popish and idolatrous worship;
and where a worship not differing in its nature and
ground (but only in form) is continued in this day;
and the root from whence all this idolatry grew, is not so much as discovered,
much less purged out of these dominions,
by them who formerly declared against it in words.
Now as we will answer it to God, we are to give no countenance or furtherance to idolatry.
And for clerks, they were officers invented by the false church (since the apostasy),
never appointed by Christ in his church, and such we dare not help to maintain.
Was it not solemnly covenanted with the Lord against superstition,
for the plucking up of Episcopacy, root and branch?
And must not those that are faithful to the Lord perform their covenant,
though to their hurt?

Now any man that shall in the fear of the Lord read this,
may see that these things bear a weight upon our hearts; and what we do herein,
we do for conscience`' sake, in obedience to the Lord;
and not out of stubbornness or rebellion, as by some we are charged,
nor out of any delight that we have to disturb or disquiet others;
but singly to the Lord, that we may stand clear in his sight.
We know whom we obey therein, and are sure we do that which is pleasing to him.
Therefore let men take heed how they persecute us,
lest they be found fighters against him who will be too strong for them.
For these many ages, since the days of the apostles, deceit hath got up,
antichrist hath sat in the temple,
the true worshippers have been imprisoned and martyred.
The Lord will avenge the sufferings and blood of his saints,
and in due time will plead their cause against the oppressors,
on whom his hand will then fall heavy,
and the rocks and the mountains shall not be able
to hide them from the presence of the Lamb;
and that day who will be able to abide?
though now men put it far from them.
