[#considerations-london, short="Considerations Proposed to the City of London"]
== Some Considerations

[.heading-continuation-blurb]
Proposed to the City of _London,_ and the nation of _England,_
to calm their spirits,
and prepare them to wait for what the _Lord_ is bringing about,
that they may not run headily into their ruin and destruction; and,
by this extraordinary heat of their spirits,
kindle that Fire which will soon devour them:
with a short exhortation to them relating to their true Settlement,
and the Removal of that which hinders it.

[.numbered-group]
====

[.numbered]
1+++.+++ The Lord God Almighty, who made heaven and earth;
who upholds them by the word of his power; whose they are, with all their inhabitants;
he ruleth in the kingdoms of men; establishing or overturning laws, governments,
and governors at his pleasure. Ps. 75:5.
etc. Dan. 4:25,35.

[.numbered]
2+++.+++ That the Lord hath had an especial hand in the shakings and changes of this nation;
and hath some great things to bring about, which he ordereth all unto.
And though many of the transactions and passages
(as relating to men) have been very blamable;
yet the Lord hath been just and good in them all; and can, in his own good time,
recover the ground which he hath seemed to lose, and advance both the good of his people,
and of the nation, by all their sufferings, losses, discouragements, and disadvantages.

[.numbered]
3+++.+++ In this late revolution, there may be more of God than man is aware of.
God, in his infinite wisdom, might see that this parliament was not fit for work,
and so might suffer such a thing to fall out between them and the army (heightening
their spirits on both sides) as might occasion the removal of them out of the way.
Yea, and this present change may be but a passage to another,
unless the Lord find these very faithful and diligent in his service,
and not minding themselves and their own interests.

[.numbered]
4+++.+++ If this late revolution was of God, and he saw it good to bring it about,
for the further carrying on of his work, he will be able to maintain it;
and those that oppose him therein shall not be able to stand before him.
They may bring ruin upon the nation and themselves;
but they cannot set up what God throws down,
nor raise up any thing else in the stead of it, according to their wills;
but that which he, by his providence and disposing hand, appointed to succeed,
must have the time of trial which he allotteth it.

====

Therefore let men fear the Lord God, whose eye is upon us, and whose power is over us;
and let us take heed of being found fighters against him.
The cause hath long lain a bleeding; yet there is at length a true reviving of it:
and those whose hearts the Lord hath stirred up to seek it faithfully,
the Lord will be with them, and he is ready to pardon their former miscarriages.
But oh, that they could lay themselves low, and forget their own interests,
that the cause might rise up clear and manifest above them!
Remember this saying, O ye great ones!
The Lord did not throw down the former greatness of the nobility,
for you to rise up in their places; but ye should have lain low, and remained little,
and have let the Lord been great;
and it is your true interest to descend and become little again.
And if it were once manifest that ye did not seek yourselves, but the cause of God,
the good of his people, and of the nation,
that every part and sort of men might feel their oppressions broken,
and their just rights and liberties recovered and preserved for them;
this would draw the hearts of all the honest-hearted people to you as one man;
and those which have been scattered would be again united;
and our very enemies (seeing our integrity and righteousness and true reformation
by the wisdom and guidance of God) would magnify that work of God,
which, as yet, cannot but be a reproach.

Therefore, O England! fear before the Lord, and wait upon him:
and let thine eye be taken from man; for he is very vanity.
Neither thy good nor thy harm ariseth this way; but out of thine own bowels.
What have all these afflictions done towards the refining thee?
Art thou not yet what thou wast?
O England! wilt thou not be made clean?
When shall it once be?
Murmur not against the rods wherewith the Lord seeth good to chastise thee;
but mourn over thy wickedness, thy pride, thy deceit, thy excess, thy cruelty,
thy oppression, thy false worship, and idolatries, etc.,
and over thy enmity against that which is of God, wherever it appears.

At the beginning of these troubles thou couldst bear with no form of worship,
but thine own.
Now thou art come thus far, that thou canst almost bear with any form.
Nay, but that will not serve; the Lord will have room for the power of godliness,
and he will not always suffer thee to smite his servants
for their obedience to his spirit.
This is his controversy with thee, and the cause of all thy misery: when misery,
distress, and ruin have opened thine eyes, thou wilt see it.
Oh that thy day of calamity might pass over thee! if thou
couldst indeed humble thyself before the Lord,
and not walk any longer thus contrary to him,
in the work which he is resolved to bring about, the Lord might pity and spare thee;
for he delighteth in mercy: but if thou continuest to walk contrary to him,
and wilt be settled afore his time, and in a way, and by such means, as he approves not,
the steps of his power against thee will over turn thee.
Therefore fear, and be humble and meek before him;
for therein lies the wisdom which can preserve thee:
but strive not to withstand his foot-steps, lest he trample down thy crown, thy strength,
thy hopes, thy peace, and all that is desirable in thine eyes.

This is in tender love, as a gentle warning to you,
that you may take heed of giving way to that fierce spirit,
which is the fore-runner of misery and desolation;

From him who is a dear lover of this city, and of his native country,

ISAAC PENINGTON, THE YOUNGER
