== SOME CONSIDERATIONS Proposed to the distracted nation of England,

concerning the present design and work of God therein;
upon their submitting whereto doth their settlement alone depend,
and not upon any Form of Government, or change of Governors,
as that spirit which seeketh their ruin tempteth them to believe.

+++[+++1659]

1+++.+++ THAT God, in great mercy, broke the bonds of the Romish yoke,
which lay hard upon the neck of this nation,
and was very weighty upon those consciences wherein
the true reforming light did arise in any measure;
and who were in any measure true to that light which
the Lord caused to break in upon them.

2+++.+++ That the reformation out of Popery was not presently perfected (nay,
was never yet perfected), but was very weak and low,
many things therein savoring very much of Popery (the nation
being hardly able to bear at that time what was done);
so that there were many things still continuing,
which could not but be burdensome to the upright-hearted, and to the tender consciences,
as the light which began their reformation did grow and increase in them.

3+++.+++ That the Lord God (who, in such great mercy,
had delivered this nation from the yoke of Popery) could not but expect
that the reformation should grow and increase until it were perfected;
even until nothing was left which arose from that spirit from whence Popery sprang,
and which might (in its proper tendency) be serviceable to that spirit;
but that all his people in this nation,
might have free liberty at least (if not encouragement),
to return to the pure worship of him in spirit and in truth;
even as in the days of the apostles,
before the apostasy from the Spirit and from the Truth.

4+++.+++ That the reformation out of Popery was not pursued as the Lord expected it should;
but a dark way of worship established in the land,
and a dark church-government (both like that of Rome);
whereby those that were truly conscientious,
and in whom the reforming light did further and further arise, were reproached,
nick-named, hated, persecuted, etc.,
insomuch that there was a bar set up against the proceeding of the reformation any further,
and a formal way of church-government and worship erected;
which was pleasing to the loose and carnal spirit; but sharp, cruel,
and burdensome to the stricter sort, and to such as were tender-hearted toward God.

5+++.+++ That under this church-government and way of worship
there was a going backwards towards Popery again,
instead of going further from it.
Things grew every day worse and worse; ceremonies daily abounding,
and were more and more strictly enjoined; wearing of surplices,
bowing at the name of Jesus, railing of the communion-tables,
and making steps up to them;
calling them high altars (bowing thrice at their
approach to them) having corporasses over their bread,
saying second service, etc.
And the chief end of their visitations was to establish such things as these;
and to suppress lecturers,
and conscientious preachers (among whom some fresh life did spring up,
for the relief of the needy and desolate); and to curtail preaching,
praying before and after sermons, yea, and catechising too,
which by authority was appointed in the place of the afternoon-sermons,
when they found it exceed the limits they intended.
And this proceeded so far,
that there was very little difference between us and the Papists, save only the name;
the worship in both becoming dead, and formal, and pleasing to the fleshly part,
but empty of that which should feed and refresh the spirit.
Only the Lord hath reserved to himself a remnant,
who could not bow to these things but groaned under them, and witnessed against them,
mourning bitterly to the Lord under the load and weight of them.

6+++.+++ That when the wrath of the Lord arose against this form of church-government
and worship (as indeed it was high time for the Lord to appear;
for the power and life of religion was even expiring),
and he brake down all that stood up in the defence of it,
and gave much liberty to the oppressed spirits and consciences of his people;
yet this was not pleasing to the nation;
but fain would they have had either the same form up again,
or at least some other such like in the stead of it;
whereby the loose spirit of the nation might be settled in some way of formal worship,
and the growing reforming light snibbed in the spirits of the tender-hearted towards God.

Look back with a single and honest eye.
Hath it not been thus?
Hath there not been a sharp contention between God and this nation concerning this thing?
The Lord hath risen to remove the yoke from the oppressed,
that he might cause the powers of this nation to let the oppressed conscience go free;
but the nation would have them bound.
It is still crying to the powers and authorities in being to lay the yoke on again.
When one power is broken down (because it is not faithful in the Lord`'s hand,
but starts aside from the Lord`'s work, for which it was chosen,
to another of its own choosing),
it seeks to have another harder power set up (I mean harder to the tender conscience);
yet God overturns that also;
and what can stand before him who is risen to shake terribly the earth,
and to make the oaks and cedars thereof to fail, totter, and fall?
O England! will nothing serve thy turn but the enslaving of God`'s heritage?
That tenderness of conscience which God hath begotten in his people is his own;
is that which he will inherit.
It is that which he brought out of the Egyptian darkness of Popery,
and which he is now redeeming, and delivering out of the relics thereof:
and if these three nations should for the generality join together as one man; yea,
and though other nations should join with them,
yet will they fall short of power and wisdom to prevent
the Lord of bringing to pass his intended work.

Was it the generality of the nations God redeemed out of Popery?
Or was it a poor, persecuted remnant, for whose sakes he did it,
and whom he chiefly had respect unto?
And is not the Lord able to carry on this work further and further?
Did he suffer them always to be stopped in their progress,
and held in bondage by the powers set up?
Nay, did he not at length break them down at their cries, for their sakes?
And do you think he will now suffer the line of Presbytery to be stretched over them,
to keep them down from rising up any further in obedience
to the pure law of life in their spirits?
O England! in the zeal of the Lord of hosts I could
bid defiance to all thy counsels and strength,
though I should see thee encompass round his poor suffering seed (who
are very weak and foolish as to that kind of strength and wisdom),
because mine eye seeth the Almighty One (before whom,
in thy greatest strength and height of confidence,
thou art as nothing) engaged against thee; but I rather choose to mourn over thee,
and to wait for the opening of thine eyes, by the anointing of the true eye-salve,
which alone can unbewitch the nations.
Yea, in bowels of tender love and pity to thee, I do beseech thee,
O England! consider thyself; do not undo thy happiness and prosperity;
fight not against the Holy One, the Mighty One of despised, distressed Israel;
be not tempted to follow Israel into the wilderness (where they now are,
and whither the hand of the Lord hath led them), to bring them back again into bondage,
because thou seest them entangled in the straits,
and nothing appears able to deliver out of thy hand.
Remember what befel Pharaoh and all his host.
This Israel, whom thou huntest, is dearer to the Lord than ever that Israel was:
for that was but a shadow of the true seed;
but the true life itself is begotten and brought forth in many of these;
and the power and presence of the Lord is mightily with them, and amongst them;
though thou, in the unbelief, canst not see it.
There is now an hour of temptation upon thee;
there appears a fair opportunity to thee to be revenged on them, and bring them under.
Take heed what thou doest, lest he, who hath the power over all, bring thee under,
and set them on the top.
Seek righteousness, seek the good of all, seek true reformation,
and the Lord will bless thee: but if thou think to obtain the setting up of old forms,
and ways of worship and government, or any new ones like to the old,
under which the righteous cannot but groan (though the wicked and loose spirit may rejoice),
thou wilt be deceived, and thy mistake may prove very dangerous and bitter to thee.
Our earnest desires to the Lord for thee are,
that thou mayest be spared as much as possible (and that the sufferings of God`'s people,
from the very first rent from Popery till this day, may not be laid to thy charge);
but iniquity is so twisted into thy bowels, that with much tearing,
which will cause great pain to thee, it can hardly be separated from thee.
Thou art too wise and wilful; this is the cause of thy sorrow.
If thou couldst fear before the Lord, and patiently wait for the revealing of his will,
and of his guiding thee by his wisdom, and not be so enraged against instruments,
but see through them to his hand (who hath afflicted thee),
and humble thyself before that, how sweetly and easily might his work go on in thee!
But alas! hast thou not set thyself against it from the very first?
And now thou art much pleased with a seeming probability of turning it backward.
Ah, poor land! what will this stiff spirit (which hath all along these times
of trouble repined at and opposed the work of the Lord) bring thee to?

The time of reformation is come;
the work of reformation is begun by that power which is able to carry it on;
and that which now standeth in the way thereof (how
high and mighty soever) will be overturned.
And although (as to what men have done) the cause
and work of reformation may justly become a reproach;
yet the foundation of reformation which God hath laid is glorious:
and in these troublesome times is he rearing up the building of his New Jerusalem, which,
when he hath finished and brought forth, will dazzle the eyes of the whole earth.
O England! be not high-minded, run not out into parties and breaches, in the heady will;
but fear before him whose power is over thee (who comprehends all thy counsels, strength,
designs, and hopes, as with a span, and when they are at the height,
can moulder them to nothing with the touch of his finger); for his will must stand,
not thine.

This is from him, whom,
in the day of thy distress and bitter calamity (which
thy present courses lead apace unto),
thou wilt confess to have been thy true friend,

ISAAC PENINGTON THE YOUNGER

Written the 19th of the 11th Month, 1659
