== TO THE ARMY

+++[+++no date]

FRIENDS,

Do ye not see how often ye have been betrayed?
The Lord hath done great things for you, and by you,
and put great opportunities into your hands: but still they have been lost,
his work fallen to the ground, and his name become a reproach over all the earth,
through your means.
Oh! be abased before the Lord, and lie very low,
and consider how justly he may lay you aside from being his instruments,
in that great and glorious work he hath to bring to pass.
If ye desire to stand, look up to the Lord, to keep your spirits very low, and poor,
and meek, and ready to hear.
Oh! wait to know what hath betrayed you hitherto!
for assuredly that lies in wait to betray you again:
and if the Lord mightily preserve you not from it, will make you forget him,
and cause you to mind and seek yourselves afresh, so soon as ever your fears are over.
Therefore, in the day of your prosperity, the Lord watch over you,
and keep you close to the stirrings and honest movings for public good,
that have sprung up in your hearts in the days of your adversity; and take heed,
lest the subtlety in the wise, fleshly-reasoning part deceive you;
but fear the Lord in your reasonings,
and beg earnestly of him to keep the simplicity alive in you,
that the fleshly wisdom get not mastery over it.
For the evil counsellor is near you, even in your own bosoms,
and he lies lurking in plausible and fair-seeming reasonings.
Therefore keep close to the simplicity, and let your reasonings be servants to it,
and not masters over it.
Ah! remember how often ye have started aside like a warped bow:
become now at length upright to the Lord,
carrying faithfully to the mark those his arrows
which he is shooting at the regions of Babylon.

This is from one who waits for what the Lord will effect,
and hopes at length to see an instrument in his hand wherein his soul will delight.

ISAAC PENINGTON THE YOUNGER
