== A QUESTION

Propounded to the Rulers, Teachers, and People of the Nation of ENGLAND,
for them singly to answer in their hearts and consciences,
in the fear and dread of the Mighty God of Heaven and Earth;
whose mighty Arm of Power is stretched out in this Nation,
first to overturn what stands in his way,
and then to establish (in the place thereof) what he hath purposed in his heart.
And this is the thing which the Lord hath determined to do, both particularly in persons,
and generally throughout the Earth; namely, to pull down the Mighty from their Seats,
and to exalt the Humble and Meek (who are made such
by the Presence and Power of his Life in them),
that he alone may be exalted in the Spirits of his People, and throughout the Earth.
And this Work hath the Lord begun already; for his great and notable Day hath appeared,
and breaketh forth apace, though the eye which is closed cannot see it,
nor the benumbed sense feel it.
But he that hath an ear, let him hear the sound of the Lord`'s Trumpet, which saith,
in the mighty breath of his Spirit of life, Awake! ye dead, and stand up to judgment;
for the day of Recompense is come, the day of the eternal vengeance of our God,
and the day of his everlasting Mercy and plentiful Redemption.
The Question is as followeth.

+++[+++1659]

When this nation was rent from Popery (in part I mean: for wholly it was never rent,
but did still retain the same spirit;
though by the magistrate`'s sword it was forced from that form
and way of worship which the Pope had established) did it wait
on the Lord for the guidance of his spirit and power,
thereby to build up a true church and habitation for God in the Spirit?
Or did it take such materials as were ready at hand,
and frame up a building as well as it could,
wherewith the consciences of many (that were tender-hearted
towards God) were even then dissatisfied,
and felt, in the eternal life of God, the reformation not to be right in its beginning?

This is a weighty question: for an error at first, an error in the foundation, is great,
and the cause of many following errors.
If the Spirit of God was not then consulted with, and waited upon;
if he did not raise the fabric, surely the building was not right.
It was the Spirit of God which rent men from Popery (so
far as they acted upon pure and honest principles),
showing the blackness and darkness thereof,
and kindling desires in them after a more inward and spiritual way of worship.
Thus far was of him.
But if men did then consult with their own wisdom,
for the ordering and carrying on of the reformation,
and so upon politic grounds and reasons did raise up a building,
and not wait on the Lord for his light and power to build with;
then surely that building was not of God, nor could he be honored thereby,
nor his truth preserved,
nor the integrity and conscientiousness of his people`'s hearts towards him cherished;
but all this would suffer and be in danger by this building,
and a contrary spirit be pleased with it, and thrive under it.
And hath it not been so?
Were not the Non-conformists to it (though known to be precious persons
in the savor and life of God) looked upon and dealt with as enemies,
while such Conformists as were known to be loose and scandalous,
yet could flourish well enough, and make a fair show in this national church,
and be zealous contenders for the way of worship and government in it?
Yea, those that have been strict in their lives and conversations,
and truly zealous towards God in their souls and spirits,
pressing after righteousness and purity; such as these, though they might conform,
yet were they not hated, nick-named, in scorn called Puritans,
and snares laid for them to entrap them?
And how could it be otherwise?
For if the building was not right,
if the constitution and government of this church were not of God,
then it could not favor and cherish that which was of God,
then it could not nourish or be pleased with obedience to his pure life and spirit,
but rather with obedience to its carnal form.
For so it is in truth and reality before God; this church, with its whole constitution,
government, order, and way of worship, was either of God`'s spirit, and so spiritual;
or of man`'s wisdom, and so carnal.
If of God`'s spirit, then it will be a friend to that which is spiritual,
and an enemy to that which is carnal; if of man`'s wisdom,
then it will be a friend to that which is carnal,
and an enemy to that which is spiritual.
And this is a true mark of the true church, and of the true church power and government;
it begets and preserves that which is spiritual, it beats down the carnal;
whereas the church power and government which is
carnal preserves that which is carnal (a carnal unity,
a carnal uniformity in worship, etc.), but checks, snubs, smites,
and persecutes that which is spiritual;
and for such a kind of power and government to be set up,
the carnal part in every man contends and cries out.
And so long as there is any change made in this church by the same wisdom,
it will never be otherwise; it will be from carnal to carnal,
and so still against that which is spiritual.
Therefore look back singly, and consider what the building was, and how it was reared up;
and see whether it was of God or no:
or whether it was built up in the forwardness of man`'s spirit,
by carnal reasonings and consultings,
accommodating things to the present state of the nation,
and not to the plain and clear measure of God`'s truth.

First, See what the materials were whereof this church was built.
Were they materials fit to make up a true church of?
Was it built up of a people truly converted to God?
Of persons changed in heart?
Of persons sensible of the foregoing idolatry, and turned in their souls, minds,
and spirits from dead idols towards the living God?
Or was not rather the heart of the nation still inclined towards Popery,
even while it was turning into a Protestant church?
And was it not chiefly made a Protestant church by the force of the civil power,
which wound in by degrees a Protestant interest;
the heart of the people still remaining unchanged, and hankering after Popery;
but at length, in tract of time, seeing they knew not how to help it,
won over to Protestantism with the same heart and
spirit that they came out of Popery with?
Consider seriously in the sight of God (who looketh both
forward and backward upon things with a true eye),
whether it hath been thus or no?

Secondly, See what kind of ministry was then set up.
Was it a new ministry (as John Huss, that famous Bohemian martyr,
prophesied should arise, and as Luther saw the necessity of,
utterly disclaiming the deriving of orders from Popish bishops)?
or was it the same ministry which was derived from Rome?
It is a sore stress the ministers of England have been put to; namely,
to plead for the truth of the ministry of the church of Rome,
that thereby they might defend their own.
Now mark this thing following; there arose false apostles, false prophets,
false teachers in the apostles`' days; whom Satan clothed like true apostles,
like true prophets, like ministers of righteousness.
Thus they appeared, thus they seemed to be; but they were not of God, but Satan;
not sent of God, not inspired by God; but inspired and sent by Satan.
These false apostles, these false prophets, fought against the true church,
and true ministry of Christ.
And though they were oftentimes discovered, by the spirit of Christ in his church,
and the church preserved from them, yet we find related in Scriptures,
that at length they did prevail,
insomuch as the third part of the true ministers were shaken,
and swept down from their place and standing by them, Rev. 12:4. yea,
and at length the church herself (as to the truth of her outward state) overcome,
and fled into the wilderness, ver. 6, 14. and a false church got up in her stead,
which hath a cup of fornication to make people spiritually drunk;
and to bewitch them from the true worship of God, into imitations and likenesses, Rev. 17:4.
and those who will not acknowledge
her likenesses and imitations to be the truth,
but, in the word of the Lamb`'s testimony, witness against them, she drinks their blood.
ver. 6. Now can any man of any manner of seriousness and sobriety of spirit
(who is not drunk and overcome with this whore`'s wine) believe,
that after false prophets had got the day, and set up the false church,
that they would set up the true ministry in it?
Oh, how blind have men been, that they should go about, and take such pains,
to derive a succession of the true ministry from
the ministers of prophets of the false church!

Thirdly, What kind of maintenance was set up for this ministry?
Was it a gospel maintenance?
Was it that they should live of the gospel,
which cannot but open men`'s spirits to the true ministers thereof?
Or was it a maintenance forced from the people,
by that outward power which set up the church?
And was this maintenance like unto, or the same with,
the maintenance which the Popish ministry had before in this nation,
for their idolatrous service?

Fourthly, What kind of worship was it, which was set up?
Was it the worship of the gospel, which is in spirit and truth?
Or was it a form of worship invented by man,
and so accommodated to the present temper of the nation, that they might,
with the more ease and willingness, step out of Popery into it,
because of its nearness and likeness thereto?

Fifthly, What kind of church-government was set up?
Was it a pure, spiritual government?
Was it put into the hands of the Spirit?
(For nothing is to govern, or can rightly govern over the spirits of Christ`'s people,
in spiritual things,
but the spirit of Christ.) Or did men frame up a church-government by their wisdom,
and put it into the hands of such as might exercise it without, yea, and against,
the Spirit?

Sixthly, What kind of order was set up in this church?
Was it the true, gospel order?
Was it the order of Christ`'s spirit, whereby the carnal wisdom of man might be quenched,
and his spirit have scope?
Or was it a carnal order, whereby the carnal wisdom, learning, knowledge,
and arts of man might have scope, and the spirit in its motions be quenched?

Seventhly, By what wisdom was the common prayer-book compiled and set up; and surplices,
crosses, and other ceremonies enjoined?
Was it by the wisdom of God`'s spirit,
for the building up of the spirits of his people in the faith?
Or was it for the pleasing and satisfying of the carnal part in people?
And what sort of persons were they who did most contend for, and were most pleased with,
these?
Were they, for the generality, the stricter, or the looser sort?

Eighthly, How came it about,
that the supreme magistrate of this nation was made
chief head and governor of this church under Christ?
Was this from Christ`'s institution, or of man`'s wisdom and invention?
If of man`'s inventing wisdom, then against Christ, then of antichrist`'s spirit,
who exalteth that which is not of Christ, to sit and govern in his temple.

Oh! weigh these things, look about thee, O England!
O rulers, teachers, and people look about you!
And if it plainly (upon a naked search) appear that there was, at the very first,
a foundation laid of suppressing the true worship, and the witnesses to it,
do not shut your eyes.
Have not the people of God still been misrepresented,
had reproachful names cast upon them, and, in some degree or other,
been persecuted from the beginning of the reformation?
And though names change, and rulers change, and the teachers change,
and the people also change in their religion and worships,
yet is not the persecuting spirit still the same,
and the persecuted spirit still the same also?
The persecuting spirit changeth its cover often, but still retains its nature,
hunting after the life and pure power of the spirit,
in the children which are begotten of God.
Are not the people of God in every change a despised people,
and their integrity towards God still struck at?
When the Lord began a little to wipe off the reproach from them,
at the beginning of these troubles,
and the persecuting spirit could not so conveniently
hunt them any longer under the name of Puritans,
then other names were invented for them,
whereby the same spirit sought to make them appear odious again,
under a new reproachful title, that so it might be persecuting the same thing afresh.
Oh, how mightily hath the Lord striven to keep the powers and people
of this nation from falling upon his people! and yet still,
so soon as they come to any peace, and feeling of power, they are at it again.
O England! thy persisting in this cannot but bring wrath upon thee.
What wouldst thou have of us?
Shall we not fear the Lord?
Shall we not obey the Lord?
Shall we not worship the Lord our God, who hath redeemed, and is redeeming,
our souls from death?
Shall we not be Protestants in truth and uprightness of heart before the Lord?
Shall we not testify against the Popish spirit, and Popish practices,
and all new inventions of the same spirit (though they get
ever so fine a covering) in the church of England,
as well as against them in the church of Rome?

The Lord is our witness, we would not offend thee, O England! no,
not the meanest persons of the whole nation:
but from out of Popery we are called (and from whatever else the
same nature and spirit may take up in the stead of it),
to follow the Lord our God towards the land of the living; and follow him we must,
however thou deal with us.
O England! if it had been so that thy rulers had built up a true church,
yet the evil spirit, the unclean spirit, would have endeavored to pollute it,
to provoke the Lord to remove his candlestick (which is an inward act of his spirit,
the outward building might stand notwithstanding),
and then thy house must have been left desolate,
and the same spirit would then have called his people out of it.
But if thy building hath not been spiritual, and in the spirit,
how can the spirit of the Lord suffer the children begotten by him to lodge in it!
Oh, when wilt thou have an ear to hear, that the Lord`'s wrath may assuage towards thee;
which kindleth more and more, and is entering apace within thy bowels!
This, this is the Lord`'s charge against thee:
Thou art for the Protestant name (it is now become thy interest,
and a goodly covering in thy eyes) but against the Protestant spirit;
which the Lord calleth to follow him further and further from all the things of Popery,
and from all the things like Popery.
And the Lord will put a difference between the Protestant name and the Protestant spirit;
between them that serve him in the fear which he begets in the heart,
and them that set up that kind of fear which is taught by the precepts of men.

O England! we are now seemingly in thy hands (who hast long handled us very roughly);
and we have no strength against thee, nor no hope of deliverance from thee,
but in the Lord our God; and there we are at rest, waiting upon him,
in the innocency and integrity which he hath begotten in our hearts,
until he plead our cause.
And in that day thou wilt see that we have not been thine enemies,
and then thou wilt mourn over that mist of darkness,
which hath withheld thine eye from discerning what true friends we have been to thee,
and how we have endeavored,
and sought with our hearts to prevent thy drinking of that bitter cup,
which is to go round the nations.
And if thine ear could have been opened, thou mightest have been spared.

=== POSTSCRIPT

THE gospel is free; the grace and mercy thereof free;
the spirit a free spirit (freely given of God, and freely ministering for God);
the church a spiritual building,
built in the freedom and liberty of the life of the spirit;
the order and government of the church is from and in the same free spirit,
guiding a people whom God makes willing in the day of his power;
the maintenance of the ministry a free maintenance; the whole obedience and worship free,
in the free spirit, and in the truth which is begotten in the heart by the free spirit.
The head of this church is Christ, the living Spirit,
who hath appointed none to be head under him here on earth,
nor hath given power to any to make any laws concerning his kingdom,
or the government thereof; concerning his ministry, or the maintenance thereof.
(Is it not thus?
Doth not the least child of light see it to be thus?)
But the church of England was a church built by force;
settled by force; her ministers maintained by force: her order, unity, uniformity,
and government, forcible; and the free, pure spirit of life can have no scope in her,
but according to the wills of her rulers, teachers, and people: if it move otherwise,
if it appear otherwise, it is sure to be nick-named and persecuted.
O England!
England! can God always suffer these things?
Will not his hand at length be stretched forth against thee?

Given forth by ISAAC PENINGTON the Younger, in the fear and dread of the Most High,
the 14th of the 12th Month, 1659.

=== REMARK

"`The day of the Lord so cometh as a thief in the night.
For when they shall say, Peace and safety; then sudden destruction cometh upon them,
as travail upon a woman with child,
and they shall not escape.`" 1 Thess. 5:2-3. And when the Lord cometh,
woe to him who is found beating his fellow servant,
and endeavoring to force the conscience (which God hath made tender and pliable
to the voice of his spirit) from its obedience and subjection thereto.
