[#state-of-things, short="Some Considerations Concerning the State of Things"]
== Some Considerations

[.heading-continuation-blurb]
Concerning the State of Things relating to what hath been, now is,
and shortly is to come to pass; warning all People to look about them,
and to wait on the _Lord_ for the unerring Light of his Spirit,
that they may know the Times and Seasons,
and the Work which _God_ is now about in the World, which is Great and Wonderful;
and so may not be found Fighters against _God,_ his Truths,
and the Witnesses of this Age and Generation;
more particularly Lamenting over and Exhorting _England._
With a faithful testimony concerning the _Quakers._

[.numbered-group]
====

[.numbered]
1+++.+++ That the spouse of Christ,
the true church which God built in the apostles`' days by his Spirit,
the church against which the gates of hell could not prevail;
the church which was the temple of the living God, the pillar and ground of truth;
the woman which was clothed with the sun, who had the moon under her feet,
and was crowned with a crown of twelve stars, etc.
-- this church, at the close of the fight between Michael with his angels,
and the dragon with his angels, fled into the wilderness,
into the place prepared of God for her, Rev. 12:6.
having two wings of a great eagle given her,
that she might fly thither to her place; where she was to abide,
and be hid from the face of the serpent,
and to be fed with the living nourishment from the hand
of the Father all the time of antichrist`'s reign,
which is said to be a time, times, and half a time,
ver. 14. or one thousand two hundred and sixty days, as ver. 6. or forty-two months,
as chap.
11:2. And she was accordingly gone out of sight,
insomuch as the serpent could find her no more,
but "`went to make war with the remnant of her seed, which kept the commandments of God,
and have the testimony of Jesus Christ.`" Rev. 12:17.

[.numbered]
2+++.+++ That the true church cannot come out of the wilderness,
till the time of her abode there (the set time appointed by God) be ended,
nor then either, but by the out-stretched arm of the Lord.
Ps. 102:13. She may mourn over her desolate wilderness-state,
but she cannot fly out of it, without the help of the wings of the same eagle,
which were given her to fly into it.
The Lord must pity the dust of Zion, and, by his everlasting strength and compassion,
raise up the tabernacle of David, which is fallen down, or it can be restored no more.
ver. 16. Rev. 21:3.

[.numbered]
3+++.+++ That the state of the people of God, all this time of the true church`'s absence,
hath been a state of captivity.
The seed hath been in bondage in Egypt, the dark land, in Babylon,
the land of confusion (for such all the church buildings, order,
and government have been in comparison with the true
order and government of the church by the Spirit,
which was known and enjoyed by the people of God, before this her flight);
where they have been mourning under the chains of darkness,
and lamenting over their mother; for Zion hath been laid waste, and Jerusalem,
the holy city, hath been trodden under foot by the Gentiles;
to whom the outward court was given, when God took down his building,
and secured his temple, altar, and the worshippers therein. Rev. 11:2.
And in this state God finds his people,
when he comes to overthrow her (to bring death and mourning and famine and fire upon her.
Rev. 18:8), and to redeem them;
for then the voice goes forth from the spirit of the Lord, to the spirits of his people,
"`Come out of her my people; that ye be not partakers of her sins.`" etc. ver. 4. Why,
were the people of God in her till now?
Yea, till the very hour of her judgment,
and are many of them in great danger of staying there, even till they feel her plagues.
They that sit down in any church building, taking it for Zion,
before God`'s season of building his Zion, sit down but in Babylon, it is no other;
though they who have drunk of the false woman`'s cup (new-mixed for them,
and so are enchanted afresh into some new,
fine-painted bed of her fornication) cannot believe it to be so.

[.numbered]
4+++.+++ That when God redeems his people out of Babylon,
he brings them not immediately unto Zion (not immediately into a built city),
but into the wilderness where the church lies unbuilt,
where they are prepared and fitted for the holy land,
and circumcised in spirit before their entrance.
There is a long travel from Babylon to Zion; wherein the hasty spirit, the rough spirit,
the exalted spirit, the murmuring spirit; the self-will, self-worship, self-wisdom,
knowledge, and righteousness (all which are of great price in Babylon) are cut down;
and the spirit broken, emptied, made poor, deeply humbled,
and so prepared for God`'s holy hill.
When a Babylonish building or way of worship is discovered,
man would fain have another ready,
to put in the place of it so soon as it is pulled down.
Thus man`'s wisdom would order it, but the Lord will not have it so;
but there must be a season of desolation, of stripping, of nakedness,
of being unclothed of all the purple and scarlet dye of Babylon. Rev. 17:4.
A pulling off the ornaments of all the knowledge, worship, ordinances,
duties, experiences, etc., which are held and practised out of the pure life.
And in this state of misery and sore distress,
the Lord lays the foundation of the new heavens, and of the new earth,
in the spirits of his people; which, when it is finished,
then at length he saith to Zion, "`Thou art my people.`" Isa. 51:16.

Observe therefore the error of the reformations since the apostasy.
They have been still building too fast, and not waiting on God to be hewn and squared,
and fitted for his building.
The reformed churches have still been built of stones
before they were made ready for the building.
They have not waited their time of preparation in the wilderness,
nor have they waited for God`'s building them up into a temple,
nor for the time and season wherein it is God`'s pleasure to build.
So that though they did well in separating from that
which was corrupt and manifestly evil;
yet they did not well in making haste into another way of their own forming,
but should have waited for God`'s manifestation of the good,
and for his leading of them by his Spirit into it.
And by this means it has come to pass,
that though there hath been a pure thing often stirring towards reformation;
yet by an over forward hastening to build, the good hath been quenched,
and the evil hath again (under a new cover or form of worship) overgrown it,
and then hath been ready to revile and persecute the good in others:
but this the eye which is overtaken with the appearing beauty of its building (having
concluded it to be according to the will of God revealed in the Scriptures) cannot discern.

[.numbered]
5+++.+++ That when Zion is rebuilt,
when the church its heaven is again stretched forth (wherein
she was seated before she fled into the wilderness,
Rev. 12:1),
those that are God`'s faithful witnesses (into whom the Spirit of life hath entered,
and whom he hath caused to stand upon their feet) shall ascend up to heaven in a cloud,
which their very enemies shall behold. Rev. 11:12.
And this was done in the time of a great earthquake,
wherein the tenth part of the city fell.
ver. 13. The shaking at this time is very great in this nation;
let them mark what will be the issue,
and observe whether (notwithstanding all the seeming
contrarieties) the Lord God doth not so order it,
as to bring a considerable part of Babylon down, and of the powers that uphold her.

====

The people of God, all this time of antichrist`'s reign, have been a suffering people.
The tender-hearted everywhere (whose souls could only bow to the Lord,
who could not receive doctrines from men,
or fall into worships and practices at the will of man) have lain open to church censures,
as they call them, and to the magistrates`' indignation, under the names of heretics,
blasphemers, seducers, and disturbers of the peace, both of church and state: and indeed,
so far as any have tasted of the true light and power of Christ,
and have been called forth by him to be his witnesses,
they could not but be disturber of the carnal peace and security
of the antichristian congregations against whom they witnessed.
When the true church fled into the wilderness, the serpent cast a flood after her:
she was reproached and blasphemed for a harlot, a strumpet,
one that was not the lamb`'s wife, as she pretended. Rev. 12:15.
For the dragon which persecuted her (having now
gained her ground) had set up another woman for the true church,
and had decked her richly, Rev. 17:4.
insomuch as she was admired for her
beauty by all the kings and inhabiters of the earth,
ver. 2. but she which was indeed the true woman was trampled upon and despised,
even by all the outward worshippers in the outward court all over the world. Rev. 11:2.
And if those of the synagogue of Satan could contend to be the true Jews,
and the true church, even while the true church was standing, Rev. 3:9.
no marvel though they carry it clear in their several
forms and disguises in the time of her flight and absence,
especially they appearing both in the place where she once was, and in her very dress:
and here is the eye of God`'s Spirit, and of the wisdom he gives to his babes, tried,
even to discern and fly from her there.
Let her paint ever so often, change her dresses in every hour of reformation,
come nearer and nearer into the likeness of the true church;
yet that which is born of the truth espieth her;
and the young man whose ear is kept open to the voice of wisdom,
which uttereth itself in the immortal seed, escapeth her bed,
and is not defiled with the great whore, nor with any of her women or daughters,
who are born of her after her spirit, though they deny her,
and seem much to differ from her according to the flesh. Rev. 14:4.
Enter into the mystery of life (from
out of the reach of the spirit of witchcraft),
and read me here, that in the true eternal light of all the living,
thou mayest perceive the mystery of deceit and escape as a bird from the snare, and live.
Now the true church being thus fled, what becomes of her seed?
They must needs be scattered; they can no more be found in a body as before;
there is now but a remnant left which "`keep the commandments of God,
and have the testimony of Jesus Christ,`" and these the dragon
applies himself still to manage the war against. Rev. 12:17.
And the beast (to whom the dragon gave his power, Rev. 13:2.
and upon whom the false church was found sitting even to the very last,
Rev. 17:3) did not only make war with the saints, but also overcame them:
and this power was given him over all kindreds and tongues and nations.
ver. 7. of chap. 13.
So that the holy city was to be kept down and trampled under foot by the false worshippers,
under one form or appearance of church worship or other,
all the time of the beast`'s reign. Rev. 11:2.
And as the beast did kill them,
so the woman that sat upon the beast drank their blood. Rev. 17:6.
For mark; the dragon, the first beast,
the second beast with the false church, are all in unity together,
and drive on their war and design, under disguises,
and appearances of truths and church worship and discipline,
against the Lamb and his followers;
against every appearance of Christ in his truth and people.
And everywhere, where he can get into any form without the power,
there he manageth his war by the form against the power.
Thus in Popery, by crying up holy church,
he knocks down all the springings-up of truth there; so in Episcopacy,
by crying up that form,
how did he knock down the buildings-up of the true life and power there also!
And if he be driven out there, then he stands ready to enter into the next form,
either of Presbytery or Independency,
that he may not want the advantage of a cover to keep his
war on foot still against the saints and the truths of Christ:
and here lies his strength; and the liker his form is to that which once was true,
the better it serves to cover him;
and he has better advantage of fighting under it against Christ, his truths and people,
than under another which is not so like.
But antichrist`'s reign who hath taken the name upon him without the nature,
and so persecuted the true nature, being covered with the name) is to have an end; yea,
(blessed be the Lord) it is in part ended, and the Lamb`'s day is already begun,
the out-stretched arm of the Lord`'s everlasting power is revealed,
and revealing more and more: yea, Babylon is already discovered, her waters are dried up,
her nakedness under all her covering is seen, her very life and spirit are struck at,
her kingdom totters daily; the stakes also of Zion`'s tabernacle are strengthening daily,
and the Lord is stretching out her curtains, and enlarging her territories:
and the wrath issues out more and more from the throne,
and dreadful woes and plagues are prepared for them,
who are either upholding any old likenesses of what once was true,
or setting up any new ones in this day of God`'s power,
wherein he is redeeming and bringing forth the life itself.

Is it not plain that the beast (or antichrist who sat in the temple of God,
ruling there as a beast by outward force, without the inward life and power.
2 Thess. 2:4) had power given him to continue his war against the saints,
till the very expiration of the forty-two months? Rev. 13:5.
And was not this power given him over all kindreds and tongues and nations?
ver. 7. Did not the false church, or false woman,
till the very end of this time (in one appearance or other,
under some form of worship or other; sometimes in a grosser and more loathsome,
sometimes in a finer and more taking dress), still go for the true church,
being upheld by the kings and inhabitants of the earth,
who all drank of her cup of fornication? Rev. 17:2.
4+++.+++ Was not the holy city (or true church)
trodden under foot all this while in every kindred,
nations, etc., by the heathenish spirit of the antichristian Christians therein,
who made a great show of zeal and worship in the outward court? Rev. 11:2.
For while the holy city is to remain unbuilt, he that will worship in it,
must sink into its ruins, and lie desolate with it;
but he that will be building before God`'s time, rejects the corner stone,
which lies hid in the ruins of this city, and so builds up a Babylon,
to which though he gives the name of Zion, yet it is not so in truth;
but Zion lies underneath, in the dust, trampled upon, and set at nought,
by him and his building.
Now, shall the forty-two months never have an end?
And shall the holy city never rise again from under the feet of
the antichristian professors and worshippers of the outward court?
Shall the walls of Zion never be built more?
Or is it to be expected, when the Lord begins to build her up, and bring her forth,
that ever any of the false churches should own her?
Oh, fear therefore before the Lord! every one entering into that in his own heart,
which (being hearkened unto) teacheth the fear, and breaketh the pride, loftiness,
and conceitedness of the high-imagining mind,
which first builds up with apprehensions about church, religion, and worship,
without the Spirit, and then is offended with that which cannot bow to those images.
But be it known unto you,
O nations and powers of the earth! that the Lord hath raised up a people,
whose knees can alone bow at the name of Jesus,
and whose tongues can alone confess to him.
And if Nebuchadnezzar`'s spirit should heat a furnace of affliction seven times hotter
than it hath yet been heated all this day of the cruel sufferings of God`'s dear people,
and threaten all with it that will not bow to the
image or form of worship which he sets up;
yet this we know assuredly, that the Lord hath begotten a seed which he can deliver,
and which we do not doubt but he will deliver,
let antichrist`'s sea and waves roar ever so loud against them.
But, however, bow to any image they cannot;
for they have tasted of the living truth itself,
which hath made them free from such images and idols wherein they were before entangled;
and the spirit of the Lord calleth aloud to them to stand
fast in the liberty wherewith Christ hath set them free,
and not receive any more the yoke of bondage upon their necks,
but to draw under the sweet, gentle yoke of his Spirit.

O England,
England! how sad is thy state! how great and mighty things hath
the Lord done for thee! but thou still overlookest his hand,
and art offended with the work of his Spirit,
because it suits not with thy fleshly desires and interests.
O England, England! what will become of thee?
The Lord hath kindled his fire, and thou addest fuel daily.
The Lord is arisen to make inquisition for the sufferings and blood of his people;
and thou, instead of repenting of what thou hast done, art greedy of more.
Thou hast deeply drunk of the whore`'s cup of fornication,
and that makes thee thus thirsty after the saints`' blood.
Thou criest out against those that put the martyrs to death,
as the professing Jews did against those that put the prophets to death;
and yet persecutest their spirit wherever it appears in
further prosecution of the work of reformation at this day,
even as the Jews did persecute the spirit of the prophets in Christ and his apostles.
Oh, mourn to the Lord to open thine eyes,
that thou mayest not thus stand any longer in his way!
Let him bring forth his church, let him set up his truth, let him advance his people,
and do not thou go about to limit the Spirit of the Holy One in them.
There is none of these will harm thee, but bring blessings upon thee.
Let thy governors keep within their bounds,
and be a defence upon all people in their just rights and liberties,
and see if from that day he do not bless thee.
But if there be one thing in the Lord`'s heart concerning his people,
and another thing in thine; if he resolve to bring them forth to his praise,
and to give them their liberty in their obedience to his Spirit,
and thou resolvest they shall come under thy yoke and bonds, how can ye agree?
Your wrath by this means must needs be kindled against each other,
and that hath most strength will carry it.
For as the day of your wrath is come, to see the people of God so increase,
grow bold in his truth and power; so the day of his wrath is come,
to see his people so reproached, hated, hunted, and persecuted, for his name`'s sake. Rev. 11:18.
And take heed,
lest upon that spirit which in this generation still continues persecuting,
the sufferings, persecutions,
and blood of all the saints and martyrs (shed all
the time of antichrist`'s reign) be not required.
The blood of all the prophets, from Abel to Zacharias,
was required of that great professing generation of the Jews,
who spake such great words of Moses and the prophets,
but persecuted Christ and his apostles. Matt. 23:35.
And the blood of all the souls that
lie under the altar crying "`How long,
O Lord, holy and true,
dost thou not judge and avenge our blood on them that dwell
upon the earth?`" They were bid to rest a little season,
and then the blood of all that ever were slain since the apostles`'
days is to be required of that generation of professors,
which are found, even to the very last, in the persecuting spirit. Rev. 6:10-11.

I do not write this to reproach any sort of professors;
but in true love and bowels of compassion,
that such among them as ever had any taste of God, and of his sweet, meek Spirit,
but are now grown hard, and found smiting their fellow servants,
may (if it be possible) hear the Lord`'s voice, which yet tenderly calls after them,
that they may not be cut in pieces,
and receive their portion of wrath with Babylon. Matt. 24:49-51.
Rev. 18:4. As for me, I am poor and weak (a worm, and no man),
one who hath been a mourner and wanderer in a strange land all my days; yea,
I have been that fool, who though I have often been very near,
yet still knew not the way to the city of my God. Ecc. 10:15.
And at present I am very unworthy and unfit to be the instrument
in the Lord`'s hand for the reclaiming of any man from his wanderings.
Yet this I can, in truth and uprightness,
say concerning the Lord`'s gracious dealings with me,
that in the bowels of his mercy he hath visited me, and turned my face toward his Zion:
and his life and Spirit (as he pleaseth to keep me
fresh and open) I know both my way and my leader;
and also that which is mine enemy, which continually endeavoreth to betray and devour me.
And I speak the truth in Christ, I lie not.
I know also what I have felt wrath and misery upon,
and what the Lord hath so long and so severely smitten in me,
he will not spare in others.
Oh! that men could hear, and avoid my bed of torment,
which I suffered a most dreadful and terrible hell for many years (bear with me,
for I cannot call it less), though without either guilt upon my spirit, or fear of wrath,
being justified before God in my own conscience (till afterwards,
under long continuance of misery and thick darkness, some guilt was contracted),
and having a secret root of hope concerning good from God,
if once I might appear in his presence to plead my cause there.
Who can possibly believe the misery I endured (if it were related)! and
yet it had not the least mixture of either of these in it for a long time.
But after this,
through the ignorance and thick darkness wherewith I had been long overwhelmed,
not knowing what had been, and still was, present with me,
the tempter by his subtlety got in,
and led out my mind from what had visited and sought after me all my days,
to wait and hope for some great appearance to set me to rights:
and here my loss was very great,
my soul being hereby removed far away from the present feeling of the spring of my life,
and drawn to neglect the little dawnings of that light which
shineth more and more to the perfect day;
having concluded in myself that no less would suffice to heal me,
than its breaking forth in its full strength, even at noon upon me.
Thus I despised the day of small things, and was seduced into a gaping after,
and waiting for that, which is never so to be received:
but the little seed of light being received, and finding good and honest earth,
groweth up therein even to perfection,
and then knoweth and receiveth the light of the day in its full strength.
And although there was such a savor of God left in me,
that upon the first converse with this people called QUAKERS,
I could own the voice of God in them,
and set to my seal (as in the presence of God) that it was the
true life and power of the Most High whereof they were born;
yet I could not but despise it as a weak and low appearance thereof; yea,
and started back from it,
as being such a kind of dispensation of life and power as was to pass away;
and the passing away whereof from me had made me so miserable.
And now I am as one born out of due time, and come lagging behind;
feeling myself altogether unworthy to be numbered amongst them,
or to bear a testimony to that truth and power of life wherein they flourish,
and by which they are redeemed and bought out of the earth with the price of the living,
immortal blood of Jesus,
by which (together with the word of his testimony) they cannot but overcome
all the powers of darkness (with all the powers of the earth,
which stand in the darkness, and fight under the darkness),
being taught thereby not to love their lives unto the death.
But the scoffing, conceited professor will be ready to say,
What! are those the only people?
Others besides them are as dear to God as they.
There are many in forms equal to them, and many out of forms far beyond them.
Whereto I answer thus; Yea, there are so in the scale of man`'s judgment:
but not so in the measure of the sanctuary.
These are the only redeemed people that my soul knows of.
There is a seed besides them, not yet gathered, but in Babylon,
whom the Lord (in his due season) will gather into the same light, life, and power;
but there is no other Saviour but that light eternal which hath given them life,
and dwells in them; who is risen in them, come to them, and hath taken them into himself;
in whom they are, even in him that is true, who is the Son of God, the true God,
and the eternal life, 1 John 5:20. who hath poured forth his Spirit upon them,
in which they minister and gather up to God those
who have an ear to hear the voice of his Spirit.
Beware, therefore, O ye nations and powers of the earth,
what ye do against his people! for ye cannot prevail by
any enchantment against these whom the Lord hath blessed;
but the more ye strive to vilify and suppress them,
the more the Lord will magnify and exalt them.
And the life which God hath raised up in them must reign, do what ye can against it.
Oh abase yourselves, and kiss the Son,
O professors and powers of the earth! that ye be not cut off;
for the Lord`'s hand is lifted up,
and in his jealousy he will smite home for the sake of Zion;
for his ear hath heard the cry of the poor and needy, whom no man regardeth. Isa. 32:10-11.
