== A WARNING OF LOVE FROM THE BOWELS OF LIFE

to the several generations of professors of this age

That they may awaken, and turn towards the LIFE,
to be truly cleansed and saved by its powerful, living Virtue,
before the Storm of Wrath break forth, and the overflowing Scourge overtake them,
which will sweep away the strongest and most well-built Refuge of Lies;
and sink those souls even into the Pit of Misery,
which are there found when the Storm comes.

HELD FORTH IN FOUR PROPOSITIONS, ASSERTIONS, OR CONSIDERATIONS,
CONCERNING MAN IN HIS LOST STATE, AND HIS RECOVERY OUT OF IT

+++[+++1660]

=== PROPOSITION I

// section-summary-preface ???
That MAN is fallen from GOD

THERE is an everlasting, infinite, pure fountain, and wellspring of life,
from whence all creatures came; from whence their life, being, motion, virtue,
and rest flow; in which they all have a place and standing according to their nature,
estate, temperature, and course of operation in his eternal counsel, who made all,
disposeth of all, ruleth in and over all eternally;
whose everlasting kingdom and dominion (which was before all,
and will be after all) cannot be excluded by any
power or dominion which ariseth after it;
but only so far as itself hath pleased, it hath given way to that power of darkness,
which is contrary to it; which how it sprang up, what it hath to do,
and how it is to vanish, is not for man`'s comprehension to fathom.

In this spring of life, man had an especial place and standing.
The Lord had created and placed him supreme, under himself, over the works of his hands;
gave him his kingdom here on earth under him, gave him his image to rule in,
even a sufficient measure of that eternal wisdom in which he formed him,
to which he was to be subject himself,
and by which he was to reign over and order all with delight, joy,
and comfort in himself, to the praise and glory of him who formed all,
and had given him dominion over all.
Here was the sweet estate, the sweet peace, the sweet liberty,
the sweet uniformity of all; all being kept and preserved in that life, virtue, wisdom,
goodness, power, and love wherein they were made;
the creatures naturally becoming subject to,
serving and obeying man (man using them and ruling over them not in the tyranny,
not in the lust, not in the vanity, not in the excess; but in the righteousness,
in the love, in the meekness, in the moderation, in the divine wisdom,
in the pure power and virtue of the life); man likewise naturally veiling to his Maker,
walking in his light, living in his life, shining in his beauty,
conquering and triumphing over all that might assault, in his strength,
and continuing perfect and straight before him in purity and cleanness
of the creature (not degenerated) towards his Creator and Preserver.
Now what could man want, having the spring of life so near him?
What could he desire, in the purity, in the life,
which the Father of life could have withheld from him?
Had he asked in the Spirit, could the Father have denied him?
And had he stood still a while in the life, out of the lust,
could he have forborne asking in the Spirit?
Had he not so suddenly been tempted to the tree of knowledge,
surely he had eaten of the tree of life, and had lived forever.

But man being in honor, lodged not one night (HE FELL THE FIRST NIGHT, read me who can),
but became like the beasts that perish.
He lost the divine image, and then had at best but the natural;
but that depending upon the divine, the beauty thereof was lost too.
He lost the eternal wisdom, he lost the spring, he lost the godhead,
he lost that which was to reign over the creatures,
and then he became but as the creatures; nay, worse than the creatures.
What he henceforth knows of God (as he stands in the degeneration) he knows naturally,
like brute beasts (even by the natural exercise of his mind, with the faculties thereof,
even as the beasts learn and know by their nature, after their kind);
and in what he thus knows, he corrupts himself worse than the beasts.
Let the Lord try him ever so much, ever so often;
drop down of the dew of heaven upon him, send him line upon line, precept upon precept,
now a little and then a little, yet he still remains brutish, both in his understanding,
receiving, and in his making use of it all.
Still he forgets the truth, and loses himself in the image; gets a notion,
an imagination,
a comprehension of somewhat into his natural part (which changes him not inwardly,
but still he is the same in his root, ground, and nature), but the life,
the eternal virtue, he is still estranged from,
and so is brutish in all his knowledge and apprehensions of God and his truths;
brutish in his worshipping of him, brutish in his belief and hopes,
and his immortal soul perishes under all.
Outward Israel was a true and full resemblance of him, who had many teachings,
a pure law of worship and sacrificing,
many prophets to reduce and restore them to the right path of holiness and obedience,
but still they were erring in their hearts from the Lord, and his pure law of life;
not knowing their owner, or their master`'s crib, so well as the ox or ass did theirs. Isa. 1:3.

=== PROPOSITION II

// section-summary-preface ???
That man, by all the imaginations that can enter into his heart,
and by all the means he can use, or courses he can run,
cannot return back to God again, or so much as desire it.

THE fall of man from God is such, that it hath benumbed all his senses; yea,
so bereft him of them, that he cannot feel his own estate.
He is dead, spiritually dead; and can no more feel his death, his spiritual death,
than a man naturally dead can his natural death.
He is bewitched into a fool`'s paradise, where he hath a new life, a new virtue,
a new wisdom, a new kingdom, a new dominion (which is indeed but death);
with which he is so transported, that he forgetteth the old;
and in this new spirit and estate cannot so much as desire after it.
Men speak of the relics of the image which the first man had: Ah! poor deceived hearts!
What relics of life are there in a dead man?
What relics of purity in a man wholly degenerated and corrupted?
Nay, nay; the spiritual image, the divine image, the eternal life,
the pure power and virtue is wholly lost; and there is nothing left,
but what is captivated and destroyed through the degenerating power.
There is nothing at all of the eternal kingdom, of the spiritual image,
of the divine life, to be found in fallen man, but a little seed;
and that seed not so much as sown in the earth, as he stands in the degeneration;
for the sowing of it is the beginning of the work anew.
And now, who can read this riddle?
The kingdom is within every man, and yet not so much as sown in any man,
till the springing up of the eternal virtue, according to the eternal pleasure: nay,
the earth is not so much as prepared to receive the seed,
until the Lord send his plough into the heart.
So that it is impossible for fallen man to attain to so
much as one true breathing or desire after God again;
this must arise from the grace, from the mercy,
from a new begetting (by the free gift) towards life, towards the divine image again;
which was slain in man (and the impression of it on him wholly
lost) ever since the foundation of the world in his heart,
which God hath set there, ever since he chose it.
And, indeed, fallen man, degenerated man (would the Spirit of the Lord let him alone,
and not disquiet him) likes his own estate well enough.
The world being written in his heart, his thoughts and desires are centred there,
and of themselves reach no further.
Might he but have the enjoyment of the creatures without,
and the enjoyment of such a kind of earthly knowledge and wisdom within,
as he now aspires after, he would sit down in Egypt and Babylon,
resting fully satisfied with Egyptian knowledge and wisdom,
and with the Babylonish treasures (might he have enough of them);
and never think of Zion, and the pure, holy land of life any more.

But when the Eternal stirs in him, when the pure Light opens at any time,
then he has some little glimmerings of his estate,
then he has some sense of his fallen condition, and some desire to remedy it.
What doth he then?
Then he bestirs himself to get somewhat to cover him, then he gathers stones,
and makes mortar to build up a wall and raise a tower,
that he may not lie open to the deluge of wrath; for, by this stirring of the life,
he hath some little taste and sight that he is not one with the life,
but departed from it.
The soul, being awakened by the opening of its own spring in it,
begins to feel the want of its spring.
It wants the true virtue, the true peace, the true joy, the true comfort and refreshment,
the true rest, the true liberty, the true life, the true light; and for want of this,
its estate is miserable; and in the stirring of the spring, it feels this misery;
and in this feeling it groans, it mourns, it pants, it cries out, and the creatural,
earthly spirit can have no rest because of it.
What, therefore, doth the creature do to still this cry?
Why, it joineth, as it were, with the soul;
it useth all the means it can to attain that which the soul sees the want of:
it inquireth after God, hearkeneth out after those that know him, studieth the law,
observeth the statutes and ordinances, performeth the duties, believeth, prayeth, hopeth,
waiteth; nay,
what is it which the creature will not set upon in this
distress (especially if the convictions of the eternal light
pursue and follow him close) to still the cry of the soul,
and to attain the price of the eternal inheritance, which is set before the soul;
which the soul can never be at rest or satisfied without some assurance of,
and progress towards?
But all this will not do.
Man, in all his own obedience, as well as in his disobedience, is shut out.
"`There is a flaming sword, which turns every way,
to keep the way of the tree of life;`" insomuch as man can, by no means,
come at the way to the true life,
nor enter into the strait and narrow path that leads thereto,
but as he is cut to the heart, his life let out, and he dies,
and comes into unity with that which slays him, and keeps the way from him.
So that man, in his running to God, is thrust by; as well as in his running from him:
in his willing and desiring after him he is rejected,
as well as in his willing against him.
"`It is not of him that willeth, nor of him that runneth,
but of God that showeth mercy.`" Mark: there is a birth of bloods,
a birth of the will of the flesh, a birth of the will of man, John 1:13.
all these will, all these run (some of them very hard);
but they are all thrust by, and disregarded by the Lord,
both in their willing and in their running.
There are many found running the race, but one obtains the prize,
which one is he that is born of God; to whom, when God gives the prize,
he will say to all the other births (notwithstanding all their willing and running,
their believing, hoping, praying, etc.), "`Depart from me,
I know you not,`" ye are the fruit of a strange womb, not of my spouse,
and so must not inherit my kingdom.
And as all these will be cut short of the inheritance at last,
so all that they do at present is loathsome to the Lord`'s soul.
"`The sacrifice of the wicked is abomination;
how much more when he bringeth it with a wicked mind.`" Prov. 21:27. His sacrifice,
his worshipping of God, his praying, his reading of Scriptures, his meditating thereon,
and of God and his works; his believing, hoping, waiting, fearing of threatenings,
and applying of promises, etc., all is abomination.
The wicked man, he whose heart is not circumcised by the Lord`'s eternal spirit,
whatsoever he can, or doth, sacrifice to God, the Lord loathes,
and it cannot profit his soul.

Object.
Yea, when he does them in hypocrisy, so they are.

Ans.
Nay, more than so.
When he doeth them with an evil heart, they are much more abominable;
how much more when he bringeth it with a wicked mind.
But let him bring it with a good mind, with that which he calls the good heart,
(for the circumcised heart, the heart of the true new birth, is only the good heart;
not that heart which every false birth is apt to call good);
let him bring it with that heart which he takes to be the upright heart;
with an honest intention, so far as he knows; take his sacrifices at the very best,
at the very purest he can attain to; yet then they are abomination.

And the reason hereof is plain and manifest.
The fountain is unclean, the root in him is corrupt;
and who can bring a clean thing out of an unclean?
Make the tree good, and his fruit will be good; but while the tree is bad,
the fruit cannot be good.
Now can the holy God be pleased with that sacrifice which comes from the unclean spring?
Can God own or approve that knowledge of himself, that faith, that love, that obedience,
that integrity or uprightness, that industry or diligence, those prayers or breathings,
which man pumps up out of the old cistern?
Nay, all these must into the pit, with the common filthiness and pollutions of the earth;
and when the Lord takes these aside from the several sorts of professors,
what will be left in them?
Oh, how many have builded up a wall, daubing it with untempered mortar,
which will not stand in the day of trial, nor shelter them from the eternal flames!
Oh, what yelling and roaring will there shortly be in such as by no means will be warned,
but would be justifying of themselves in their false knowledge and practices,
and reserving their fabrics of religion to the trial
of the day! and the day will try them indeed;
even to the bitter perplexity and anguish of their hearts,
when they come to see that there is now no way of escape;
but they must lie down in the bed of eternal sorrow, misery, and torment;
and in utter separation from that wherein they thought
they had a large and unquestionable share.

=== PROPOSITION III

// section-summary-preface ???
That all professions of God and of Christ upon the earth;
all knowledge and beliefs whatsoever, with all practices of duties and ordinances of worship,
save only such as proceed from, and are held in, the pure life, are but as so many fig-leaves,
or deceitful plasters, which may skin over the wound, but cannot truly heal it.

THE wound of man is deep by the fall: he hath really lost God,
he is shut out of his commonwealth; yea, in that estate,
he is altogether without hope (for the hope springs
from God`'s visitation of him with his light,
and from the living promise).

That which recovers man, is the eternal virtue, the endless power, the life immortal,
the Christ of God.

Now, whatever knowledge man gathers (whether from the book of the creatures,
or from the Scriptures, or any other ways) or whatever man professes,
or whatever man practises out of this, it is but a cover of his own, but a formed thing;
but his own image of truth, of knowledge, of faith, of love, of obedience, of worship;
it is not the living truth, the living knowledge, the living faith, the living love,
the living obedience, the living worship: and so it is but mortal, but fleshly;
and when it comes before the eternal flames, it will not abide them, but vanish.
"`All flesh is grass;`" all the knowledge, the faith, the love, the worship, the obedience,
the righteousness, etc.,
which man (who is ignorant of the leadings and power of the life) can come at,
is but grass; yea, the flower of it, the seeming beauty and goodliness of it,
the very choicest of it in any sort of professors,
is but "`as the flower of the field:`" it may make a fair show there,
but when the Lord cutteth it down with his sickle,
and when his sun riseth upon it with its burning heat, it will soon wither,
and his fire will soon devour it, so that its very place shall be found no more.
What will become of all the fruit that flesh hath borne, when God maketh bare,
and cutteth down the root?
What will become of all mortal knowledge of the Scriptures, mortal worship;
the faith and obedience which hath its root, growth, and spreading in the mortal part,
when the Lord heweth at it with his immortal axe?
Do not deceive yourselves; there is nothing will stand but what is immortal,
and that which is gathered into it, and so one with it.
No knowledge, no faith, no love, no obedience, no worship, no hopes,
but what spring from the seed, are gathered into the seed, and live in the seed.
This will abide, when all that springs from man,
and hath its place and residence in the mortal part
(and not in the true treasury) will come to an end,
and disappoint all who have their hopes of the inheritance there.

=== PROPOSITION IV

// section-summary-preface ???
That the living seed of eternal life, which God hath hid in man underneath his earth,
hath in it the living virtue, which alone can heal man, and restore him to God.

THAT which heals of the death, is the tree of life, whose rind or bark, whose leaves,
whose blossoms, whose fruit, whose boughs and branches, whose bulk or body,
with the whole sap thereof, are all healing, and there is nothing else can heal.
Let man catch all the knowledge that ever sprang from the life;
if he could believe (I mean in the man`'s part) all that ever the life spake,
if it were so that he could perform all that ever the life called for,
yet this would not heal him at all: whereas the least virtue from the life,
springing up into, and livingly retained in, the life`'s vessel,
truly refreshes and heals.
The seed in all its springings-up, and shootings-forth in the heart,
lets out of its healing virtue.
Let but in a reproof, a conviction, a judgment, a condemnation,
which wounds that part which hath erred from the life,
yet even in that there is a secret, hidden healing of somewhat else.
The smitings of the righteous principle are as balm, and its reproofs an excellent oil.
Thy rod and thy staff comfort me.
Light is sown for the righteous, and joy for the upright in heart.
In all the tearings, smitings,
and rendings of the earthly part (with which the seed also
suffers) and the faith in which these are received,
is the present substance of the healing from the eternal virtue hoped for.

Now, who will be wise?
Let him become a fool in the flesh.
Who will be strong?
Let him become weak in the man`'s part.
Who will be saved by the eternal power?
Let him cease from the man in himself.
Whoever would be able, in the life, to do all things,
let him sink into that in himself which is not,
that it may bring to nought all things in him that are; that so it alone may be:
and he by it being brought to nothing, will easily become all in it.
This is the true way of restoration, of redemption; first to be lost, to be overcome,
to be drowned, to be made nothing by that which is not; that that may come to BE in him,
and he be quickened, raised up, and perfected in that,
and so become possessor of the fulness.
"`The race is not to the swift,
nor the battle to the strong;`" but he that daily loseth his strength,
and his ability to know,
or so much as to will or desire (even till at length he become
nothing at all) in him is the corrupt at last destroyed,
and the mortal swallowed up of the life.
He, that feels the pure seed springing up, and by the growth of that is daily begotten,
quickened, raised, justified, sanctified, circumcised, baptized, +++[+++is]
fed in one part, and starved in another.
When the work of begetting, quickening, raising, regenerating, justifying, sanctifying,
circumcising, baptizing is finished in him, and he is thoroughly begotten into the life,
quickened by the life, raised in the life, regenerated, justified, sanctified,
circumcised, and baptized through the life, he shall have the kingdom, wear the crown,
enter into the joy of his Lord,
wielding the sceptre of righteousness with his Lord in his kingdom forever.
Now this work is to be done in the heart, on this side the grave;
for after death comes judgment for the things done in the body;
and the tree is to be disposed of, according as it is found at its fall,
either to the fire, or to grow and flourish in the land of life.
Therefore be not slothful, but watch unto the movings of the living seed,
that its work may be perfected; that it may arrive at its stature,
and come to its full growth, and may finish its service and testimony,
that so it may enter into its habitation,
and receive you with it into its everlasting mansion,
where every servant and constant sufferer with the seed shall be welcomed of its Father,
and remain a partaker of their joy and fulness forever.

ISAAC PENINGTON, THE YOUNGER
