== Where is the Wise?

[quote.section-epigraph]
____
Where is the Scribe?
Where is the Disputer of this World?
Hath not God made foolish the Wisdom of this World?
1 Cor. 1:20
____

[.section-date]
1660

These have always been the enemies and opposers of truth,
and setters-up of false images thereof in all ages; the wise, the learned,
the great disputants.
To these truth has still been mean and contemptible, their eye hath still over-looked it,
and their imaginations have still out-run it,
finding out somewhat else in the stead thereof;
for which they have been still able and vigorous to contend,
and against the truth itself.
And indeed how can the wise eye see that, how can the learned eye acknowledge that,
which comes quite out of the way of its knowledge and learning,
even in a path that it is not at all acquainted with?
"`Wisdom is justified of her children.`" Those that are wise to salvation,
those that are learned in the Spirit,
those that can dispute in the power of the life and demonstration of the Spirit,
these know her habitation, and her out-goings,
and can own her in every age and in every dispensation and coming-forth:
but the wise and learned of this world are shut out of this wisdom,
and in all their searches after truth cannot find her;
and if at any time they do find and taste somewhat of her, yet they cannot keep her;
but the wisdom and learning and strength of the earthly part in them soon
betrays and makes a prey of the simplicity that is in Christ,
and of his pure gospel; which cannot be comprehended,
nor will take up a dwelling-place with this wisdom, but brings it to nothing,
tramples upon it, and keeps it down forever, where it abides.

Three sorts of enemies, of the wise, the learned, the great disputants,
Truth hath always had.
First, Of such as have denied the true form of knowledge and worship.
Secondly, Of such as have owned the form, but withstood the power.
Thirdly, Of such as have had a taste of the power, but afterwards erred from it;
and so held that, which they had once a true taste of, in the unrighteous part,
and likewise added to it by their own imaginations.

When Israel was in Egypt (that poor,
illiterate company of brick-makers) in bondage under that wise people, the Egyptians,
with all their wisdom, could not own their God, or their worship;
but their God was an unknown being to all that wisdom, Ex. 5:2.
and his worship and sacrifice the abomination of their eyes. Ex. 8:26.
And Jannes and Jambres, with other wise magicians,
withstood the appearance of God; and Pharaoh and his people, with their wisdom,
thought to have kept God`'s Israel from multiplying, Ex. 1:10.
and to have held Israel still under their servitude,
after the Lord was risen to stretch out his arm for their deliverance. Ex. 5:8-9.
And how did all the wise nations still watch to make a prey of God`'s
Jerusalem! how did they count the towers! how often did they think to divide the spoil! Judg. 5:30.
Isa. 33:18. how did Sennacherib and Rab-shakeh make
her their own! and when the Lord did at any time give Jacob for a spoil,
and Israel to the robbers, how did they think to keep her under forever!
The wise Assyrian, the Moabite, the Ammonite, the Edomite, the Philistine, the Amalekite,
the wise Babylonian or Chaldean, thought to keep her under, as Pharaoh had done,
even till their wisdom and knowledge perverted them also, Isa. 47:10.
and the prince of Tyre, who was wiser than Daniel, Ezek. 28:3.
he also could insult over Jerusalem,
and rejoice at her downfall and captivity.
chap.
26:2.

But to come closer; come to Israel itself.
That people, by all the wisdom it could gather from the law,
by all the experiences it had had of God`'s power,
by all the faith that was wrought in them upon deliverances, yet had not eyes to see,
nor ears to hear, nor hearts to perceive;
but were a people that did always err in their hearts,
and did not understand the way of truth and peace.
The prophets among them were still fools; yea, the spiritual man mad. Hos. 9:7.
The priests were generally ignorant of the
Lord (for though they had the ark of his presence,
his tabernacle, his temple, altar, sacrifices, worship, etc.,
yet they did not know where he was, nor did inquire after him,
but contented themselves with a form of knowledge and worship).
And they that handled the law, knew not him who gave the law,
and was the sole true interpreter of the law; but the pastors transgressed against him,
and the prophets prophesied by another spirit. Jer. 2:8.
They were wise, and did abound in their own meanings, guessings,
and gathered knowledge; but they knew not the truth, no,
not of the letter according to the law,
and according to that light which God sometimes caused
to shine among them from his prophets.
Hence it was that that people, with their rulers, their teachers, their priests,
their prophets, were generally enemies to the prophets whom God raised up, hating,
persecuting, imprisoning, stoning them, etc.
The prophets of God (that spake his truth in his wisdom, in his life, in power,
in the demonstration of his Spirit) they could not away with: these were fools with them;
these were mad-men with them; 2 Kings 9:11. Jer. 29:26. these were poor,
illiterate herdsmen and ploughmen: they had learned men,
that were brought up at the schools of the prophets, that could prophesy divine things,
sweet things, that could open the law learnedly:
these prophets and these priests the rulers cherished, and the people loved.
Jer. 5:31, and 23:26-27. Ezek. 13:3, etc.

Yea, among that people, such as had a taste of the truth, as Korah, Dathan,
and Abiram might have (for surely it was not a small matter that
could so lift them up to oppose Moses and Aaron in that manner,
and to stand out the contest with them even in the Lord`'s presence, Num. 16:18.
but an apprehension of God`'s being on their side,
from some appearance of his to them), and as Balaam had,
whose eyes were opened to see the beauty of the tents of Jacob; yet these,
through the prevalency of the fleshly lusts and wisdom, become enemies,
and try always to prevail over Israel, even over the truth, and over the power.
The Apostle Jude compares such to the angels that kept not their first estate.
The angels that fell had a place and standing once in the truth;
but they kept it not (they abode not in the truth) but fell from it,
and so became devils, enemies to the truth from which they fell:
so those that fall from the truth, from the power,
from the living virtue whereof they once tasted,
from the true wisdom which once appeared to them, and began to season and savor them,
in their fallen wisdom they became the greatest enemies, the greatest accusers,
the greatest opposers,
and the stiffest maintainers of a false image of
that truth which they once had some knowledge of,
and some unity with.
Thus it was in the Jewish state: now come to the apostles`' days.

[.numbered-group]
====

[.numbered]
_First,_ They had all the wise men of that age against them; all the wise Greeks,
all the wise Jews, the learned men, the able disputants of all sorts.
The Greeks could not find wisdom in that knowledge of Christ which they held forth,
nor could the Jews find power in it, 1 Cor. 1:22.
and so one accounted it foolishness, the other stumbled at it.
ver. 23. There were many sorts and sects of wise men among the Jews;
but not one sort could own the truth, though they were looking for it,
searching the Scriptures about it, and disputing concerning it.
The very thing then in agitation and inquiry among them was,
_when the kingdom of God should come._
The King himself directs them where it was,
that they might know where to expect and wait for it, Luke 17:21.
and in many parables opens it to them;
but it was still hid from the eye of that wisdom wherewith they did strive to see,
understand, and comprehend it.
So that all the several sorts of wise men of that age,
even those who were admirers of the law and the prophets,
yet were strangers and enemies to the truth, because they joined to that wisdom,
and to that learning and comprehension of the Scriptures,
out of the sight whereof it came.

[.numbered]
_Secondly,_ For such as did own Christ after the flesh,
such as were convinced by his miracles (as Nicodemus
and many of the honester sort of the Jews were),
yet Christ did not commit himself to them. John 2:24.
He knew this faith and this owning of him which
was founded upon the wisdom and ingenuity of the creature,
would fail; and so he would not own it in Nicodemus,
but bids him look after the new birth, John 3:2-3.
nor in such as followed him up and down,
upon this or any other fleshly account, but sometimes withdrew,
and hid himself from them, Luke 5:16.
John 6:14-15. and sometimes preached doctrines which stumbled them,
and made them withdraw from him, John 6:66. And so in the apostles`' days,
there were many could get the form, and gain advantage thereby to the fleshly wisdom,
to withstand the power. 2 Tim. 3:5.
2 Cor. 11:13.

[.numbered]
_Thirdly,_ There were such as had tasted of the heavenly gift,
and of the powers of the world to come, and yet fell away. Heb. 6:4-6.
There were such as denied the Lord that bought them. 2 Pet. 2:1.
Such as fell from the love of the truth to the love of their vomit,
and of the mire of the world again.
ver. 22. 2 Tim. 4:10. Such as had a standing
in the church`'s heaven (like the angels which fell),
but kept not their habitation,
but were swept down from thence to the earth by the dragon`'s tail, Rev. 12:4.
these are the noblest champions (in the earthly wisdom,
and for a corrupted estate and false image) of all the rest.

====

Now as the prophets of God among the Jews had these enemies,
and as the apostles also had these enemies,
so all along the apostasy these enemies have been rife.
The witnesses have a wise sort of direct opposers among the Papists,
a wise sort of secret underminers among the Protestants,
and also another wise sort of such among themselves as had some taste of the truth,
but departed from the power of it into the earthly wisdom,
into the earthly understanding;
and this last sort fight more furiously and more vehemently against the truth,
and are more subtle to assault it, and grapple with it, than the other two.
Oh! there is no such bitter, deadly enemy to Christ and his Truth,
as he who once had some taste of the virtue of it,
and is now turned from it into the earth, into the wisdom and love of the world,
and yet still holds some of the notion of that truth
(whereof he once felt the power) in the earthly part.

To come yet closer.
There is in every man, not thoroughly sanctified, that wisdom which is not of God;
that wisdom from which God hides his precious truths;
which wisdom lies ready to catch every discovery and revelation of truth to him,
that it might improve it, and grow rich and wise by it.
Now this wisdom cannot attain to the knowledge of any of the things of God:
neither can this wisdom keep the true knowledge; but whatever this wisdom catcheth,
it presently corrupts.
The true wisdom, the true light, the true knowledge of Christ,
is like the manna in the wilderness; it daily comes down from heaven,
and must daily be gathered fresh.
The true light springs from the life; and it must be held in the life,
in the vessel which the life forms, in the new bottle, in the new understanding;
not in the fleshly part, nay, not in the natural part:
for as the natural man cannot receive the things of the Spirit, 1 Cor. 2:14.
so neither can he retain them.
The old storehouse, into which earthly things were gathered, must be burned up,
and not made a treasury for the things of God; but the new understanding,
which is given by him that is true, 1 John 5:20. which new-forms and preserves,
and is all in the natural.
Sink out of the earthly part, and read me,
that thou mayest be able to say within thyself, and concerning thyself,
Where is the wise?
Where is the Scribe?
Where is the disputer?

The wise part, the knowing part, the reaching part in every man,
will be putting forth its hand to gather of the tree of life;
but what hath it ever been able to gather?
I know men may gather notions of any kind, of any sect, of any sort of profession,
of any appearance or dispensation; but who is able to come near the life,
to touch the power, the truth, the everlasting spring,
or any stream or drop of water that issues from it?
And he who hath a true touch or taste thereof given him, can his wisdom add to it?
Nay, can he so much as retain it?
David had a true sense and experience of this, who cried out,
"`Oh continue thy lovingkindness to them that know thee,
and thy righteousness to the upright in heart.`" Indeed if
he like not to retain the thing itself in his knowledge,
he may improve the notion,
and bend that to the temperature and disposition
of the earthly part in himself and others;
but this is not truth, but a dead image,
or a dead remembrance of what once was truly living.
Oh! how doth the soul that is begotten of the divine breath,
that is born of the living power and virtue,
depend upon God for his continual breathings!
There is nothing that hath so much from God,
and yet nothing is so little able to live without him.
If he withdraw from it, it presently hangs down its head: nay,
if he do but so much as hide his face, it is troubled: and all the fulness,
which it immediately before had from God, is not able to keep up its life one moment;
but it pants, and fails, and flags, and withers,
until a new supply of refreshment be administered to it.
And he that knows this in any measure will not wonder at
the distress and misery of such for want of God`'s presence;
and at their cryings-out after the spring of their life
(even as the hart brayeth after the water-brooks),
though they should have fulness of all outward things, yea,
and also fulness of knowledge in things of religion,
even concerning all conditions and estates.
The thing that I wanted in my great misery, it was not outward knowledge,
it was not experience of God`'s mercy and goodness; but this I wanted,
the issuings-forth of his fresh life, and livingly to know where to wait for it,
and livingly to know it when it appeared:
for it was still near me all the time of my darkness, and did preserve me,
and appear unto me; but I livingly knew it not, but thought I would be wiser than others:
for I saw many deceived,
and so I would not own it in such a way as it then appeared in me,
lest I also should be deceived like others;
but waited for such an appearance as could not be questioned by the fleshly wisdom.
And he that waits for that, and so despises the day of small things,
cannot but refuse the little seed; and so, not being received into his earth,
it can never grow up in him into a great tree;
whereby the glory of the kingdom will be hid from him, and he shut out of it,
when others enter into and sit down in it.
Therefore, _he that will be wise, let him become a fool, that he may be wise;_
let him receive that for his light, his king, his guide, which man`'s wisdom never did,
nor never will, own.
He that ever looks to enjoy the Comforter, let him receive the Reprover,
the Convincer of sin,
and wait for his law of judging him throughout the
whole course of his sinful state and nature,
passing along with him through the whole condemnation,
until he arrive with him at the justification of the life, which the fleshly wisdom,
nor any of his knowledge of the things of God (as they are
held in the fleshly part) must never arrive with him at.

[.offset]
_Hath not God made foolish the wisdom of this world?_

The wisdom of this world is precious in the eye of the world;
and the wisdom of God in his poor, weak,
despised earthen vessels is still foolishness with them; but the Lord so orders it,
that he still justifies his despised wisdom in his despised vessels,
and makes the wisdom of the world appear foolish to all the single and upright-hearted,
who thirst after and wait for the revelation of his truth.
Now two ways especially the Lord makes the folly of this world`'s wisdom appear.

[.numbered-group]
====

[.numbered]
_First,_ In that by all their wisdom they cannot find out the true knowledge of God. 1 Cor. 1:21.
"`The world by wisdom knew not God.`" Though
there be an exceeding desire kindled in them to know God;
though they take all the ways that heart can imagine to attain their desires;
though they study and meditate ever so hard;
though they get ever so many arts and languages; nay,
though they read the very Scriptures ever so diligently;
though they _labor in the very fire;_ yet what they get, what they gather,
what they understand, what they comprehend by this wisdom,
it is all but "`very vanity.`" Hab. 2:13. It reaches not the immortal,
it nourishes not the immortal, it satisfies not the soul, it refreshes not the seed;
but only feeds and pleases the earthly part, the earthly understanding, the earthly mind,
the earthly desires and affections; even the man`'s part, the man`'s spirit,
the man`'s nature; which, though elevated and raised ever so high, is still but earth.

[.numbered]
_Secondly,_ In that all their wisdom cannot teach them to come down to, to submit to,
to come into God`'s way of having their wisdom crucified,
and that raised up in them which might receive the truth.
This they can never learn in the fleshly wisdom.
They may indeed come thus far, even to see that there is no way of entrance but by death;
and to seek death (that they may enter into the life), but they cannot find it.
The seed of Jacob, in his seeking, misses not; but this seeker never finds;
to this asker it is never given, and to this knocker it is never opened:
and that is it which makes this wisdom in every appearance,
in every sort of profession and sect of professors, so rage at the seed of Jacob,
even because it finds itself still shut out of the life,
into which an entrance is administered to the seed.
And how can that which would fain have the kingdom,
but rage against that which takes the inheritance from it?
How can every sort of professors but strive to slay the heir,
that the inheritance may be theirs?
Were it not for the living seed, and the living power and virtue,
which breaks forth in them and among them,
the religion and worship of the first birth might pass for current;
but this is it which darkens the glory of all professions and professors upon the earth,
even that living thing which God hath begotten in his people,
and his living presence with it, and blessing upon it.
At this all the zealous sacrificers, teachers, and professors, out of the life,
rage and are mad,
and would break the cords and bands wherewith this
strives to bind them unto God`'s altar.

====

Now look over all ages: Could the wise heathens stoop to God`'s dispensation to the Jews?
Was it not foolishness and abomination to them?
Or could the wise Jews stoop to the law within,
to the word in the heart (although directed thereto by Moses,
Duet. 30:14) to learn there to do justly, to love mercy,
and to walk humbly with their God? Mic. 6:8.
Could they wait there to have their
hearts circumcised by that word of power,
and so to be washed and made clean?
Nay, were they not drowned in the outward sacrifices, temple, incense,
new-moons and sabbaths, and such kind of observations,
and could not hear the truth of the Lord as it was delivered by Moses,
nor as it was opened by the prophets. Isa. 1:11.
So that this people,
seeking to know the Lord from the letter by this wisdom,
could never come to the knowledge of him;
but the place of his light and wisdom was hid from them.

Again, when Christ came, and the kingdom was preached,
and the everlasting way of redemption and salvation made manifest,
could the wise eye in the Greeks, or the wise eye in the Jews, see it?
Did not the Greeks shut themselves out by a wisdom above the letter (as they thought),
and the Jews by a knowledge and wisdom which they had gathered out of the letter?
How wise were they from the letter to reason against the King of life?
"`This man cannot be of God, for he is a breaker of his sabbaths.
He is a Nazarite, and can any good thing come out of Nazareth?
He saith the Son of man must be lifted up; but we read that Christ abideth forever.
He is against God`'s temple, against God`'s day of worship,
gives his disciples such scope and liberty,
as neither the Pharisees nor John gave their disciples;
but reviles our strict and godly teachers and expounders of the law,
calling them hypocrites, blind guides, etc.
And mark with what a rough, severe spirit he reproves them; whereas they call him master,
and speak mildly and gently to him.`" Oh! what Jew in that nature, in that wisdom,
in that spirit, could but find matter and occasion of stumbling at Christ,
even from the law and the prophets!

And as they stumbled at the true Christ,
so have all the generations of wise men since the apostasy,
all the learned men generally (their councils, synods, convocations,
and assemblies) stumbled at the true church,
looking for some such like building as had been in the apostles`' days,
and not understanding or observing how the Lord took down
that building (as it had been set up in the world),
and how he prepared a place in the wilderness for his true church,
unto which he gave her wings to fly.
Rev. 12. And how afterwards the false woman, or false church, got up in her stead, who,
with a golden cup of fornication, bewitched the kings and inhabiters of the earth, Rev. 17:2.
even peoples, multitudes, nations, and tongues,
ver. 15. so that they mistook her for the true church,
and went into her bed of whoredoms.
Which of all the learned men, which of all the councils of the Papists has seen this?
Nay, which of the Protestant councils or convocations or assemblies,
has beheld the state of the true church?
Nay, have not every sort and sect of the Protestants endeavored
to build up some image or likeness of the true church;
not so much as suspecting that she was fled into, and was to abide in,
the wilderness for a time, times, and half a time?
Oh, what darkness hath covered the earth!
Oh, how hath God befooled the wise of every sort! the wise men of every age! the wise Protestants,
as well as the wise Papists! the wise Independents and Baptists,
as well as the wise Episcopalians and Presbyterians! and how blind and sottish are nations,
and peoples, that still they think to find out the truth by having a synod, assembly,
or convocation of the wise men gathered together!
Indeed they are the fittest to rear up an image to please the earthly part of man,
and the earthly powers and interests with; but truth never came in by that way,
but the wise and learned have still been shut out from it, and have proved enemies to it.
And whosoever comes out of the apostasy from the Spirit and from the truth,
to the Spirit and truth again,
shall find nothing so great an enemy as the wisdom in himself,
and directions from the wisdom in others: for that which God leads is a simple,
a weak babe, a child to the wisdom of the world;
and he leads it in a path which is wholly out of the line of this world`'s wisdom,
and knowledge of the Scriptures,
as the path God chose in Christ`'s and the apostles`' days
was out of the line of the Jews`' knowledge of the Scriptures.
Such is the recovery out of the apostasy:
it is hid from all the fleshly-wise men of this age,
even as the entrance into the truths of the kingdom
was hid from all the fleshly-wise men of that age.
Happy is he who ceaseth from striving after the knowledge and comprehending
of the things of God in this world`'s spirit and wisdom,
and waiteth in the humility and fear of the Lord, first to be made a fool,
that afterwards he may be made wise unto everlasting life.

[.signed-section-signature]
I+++.+++ P.
