== Letters of Isaac Penington

[.letter-heading]
To His Father

[.salutation]
Ah! Dear Father,

Why dost thou so often give me occasion of mourning before the Lord,
on account of hard and unrighteous charges from thee!
How often have I solemnly professed, that there was never any desire in me,
or endeavor used by me, to draw thee to this way +++[+++of religious profession].
All that is in my soul is this,
that thou mightst have the true knowledge of Christ,
that thou mightst indeed hear his sayings, and do them,
and not set up thy own or other men`'s imaginations and invented reasonings,
instead of the sayings of Christ.

Now, though I am not for ways or opinions, but only for Christ, the substance,
the living power of God in the heart; yet, because thou stumblest at these things, and,
through prejudice, refusest the living testimony of God concerning Christ, the Rock,
building upon that which thou hast imagined concerning the Saviour,
in love and pity to thy soul, I cannot but say somewhat; for who knows but God may,
at length, give thee repentance to the acknowledgment of the truth,
and to the disclaiming of the way of error.

My father lays down three reasons why he cannot believe this way to be of God.

[.numbered-group]
====

[.numbered]
1+++.+++ God`'s way is a way of love, peace, and unity.

[.discourse-part]
Answer. If my father had that eye which can see the things of God,
and did apply himself to look therewith, he might see that peace, that love, that unity,
among this people, which other men do but talk of;
but if he take things by the report of the enemies both to God and to them,
he shall be sure to hear and believe bad enough.
They have no war with any thing but unrighteousness;
and with that they cannot have peace, no, not in their dearest relations.
They love the souls of their enemies,
and think no pains or hazard too great for the saving of them.
Being persecuted, they bless; being reviled, they entreat, and pray for their persecutors.
They are at unity with whatever is of God; but with the seed of the serpent,
they cannot be at unity: they know the "`generation of vipers`" in this present age,
and can witness against them under their several painted coverings,
as freely as ever Christ and his apostles did against the Scribes and Pharisees.
For the spirit of the Scribes and Pharisees is now in the world;
and the spirit of Christ and his apostles is also in the world;
and they cannot but fight, each with their proper weapons: the one with their stocks,
whips, fines, prisons, etc., the other with the spiritual armour of Christ.
Thus the one of these wrestles with flesh and blood, fights with the creature,
hurts that; the other loves the creature, seeks the saving of it,
and fights only with the power of darkness, which rules the creature.
Now which of these are the ministers of Christ?
These that stir up the magistrate to afflict the body,
or these that use the sword of the Spirit to wound the conscience?

And this peace, this love, this unity, they attain, not by their own strivings after it,
but by receiving it from above.
Indeed all our religion lies in receiving a gift: without which, we are nothing,
and can do nothing; and in which, nothing is too hard for us.
Yea, being kept in that, up to God, we can do all things, we can believe all things,
we can suffer all things.
Never was there a generation brought forth weaker in themselves, more foolish,
more ridiculous to the fleshly wisdom,
more exposed to sufferings from the world and worldly professors; yet,
being kept faithful to Him that hath called us, we sometimes feel strength and wisdom,
even such as the most zealous in the worldly ways of religion
have not an ear to hear the relation of.

[.numbered]
2+++.+++ God`'s way is a way of humility.

[.discourse-part]
Answer.
If they had not been broken and humbled by God,
they could never have entered into this way; which is that which the lofty,
fleshly part abhors.
Nor is this a voluntary humility;
but a humility which crosseth and breaketh the will all the day long.
Thou judgest at a distance, and with that which is not to judge, but to be judged.

[.numbered]
3+++.+++ That God is a God of order, not of confusion.

[.discourse-part]
Answer.
Blessed be the Lord, who hath recovered some of the true churches`' order for us;
and delivered out of the confusion of antichrist.
We know order in the light, order in the Spirit, order in Christ, the truth;
but that which man in his wisdom, calls order, is but antichrist`'s order, which,
with God, is confusion.
To have man`'s spirit speak and God`'s Spirit stopped,
this is the order of all the antichristian congregations and churches;
but to have man`'s spirit stopped and God`'s Spirit speak,
this is the order of Christ`'s church; and this order we know, and rejoice in,
finding that raised in us, which teaches us to "`cease from man,`" and his voice +++[+++as man]
is not at all "`accounted of;`" but the voice of the living God is heard, known, loved,
and obeyed, by that which he hath quickened in us, and made to live to himself.
The Lord is judging that which loved man`'s meanings and inventions,
all that the human part in us could gather from the Scriptures,
and is nourishing that which is of himself,
that which can receive no food but from his hand.

====

[.offset]
My father doth not believe that Mr. Gurden (as the world calls him),
or any other godly man, doth persecute them for their consciences.

[.discourse-part]
Answer.
I know no godly man can persecute.
The lamb never did worry the wolf.
But the grossest persons will not acknowledge that they persecute for conscience;
but accuse those whom they persecute, for evil-doers, and say they suffer as evil-doers.
Cannot my Father see the narrowness of this covering?
-- Would the Scribes, and Pharisees, and zealous among the Jews,
confess that they put Christ and Stephen to death for conscience?
Did they not put them to death as evil-doers, as blasphemers,
as speaking against the holy temple of God, the laws and ordinances of Moses?
Ah! --,
the children of wisdom were never justified by that
wisdom wherewith thou judgest of things.
The Scribes and Pharisees were as confident that Christ and his disciples were deceivers,
and that they brought up a new way of religion contrary to Moses,
as any can be that these people are deceivers, and that their way is new.
The scene is turned; the same things that were then are now;
and the eye of that spirit is as blind now as it was then: it cannot see its own deceit.

The last part of the letter consists of very harsh and unrighteous charges,
mixed with bitter expressions,
which I shall pass over -- only I confess it is somewhat hard to one part of me,
that my own father should deal thus with me.

About having comfort in me, and wishing me more comfort in my son, I must needs say this.
There is a part which God hath struck at, and is destroying, and I have no comfort here,
and that is able to yield little comfort to any one else.
-- If I were in any formal way of religion,
I might be a comfort to my father (for he could be gratified with that,
or at least bear with that);
but because the Lord hath seized upon my heart by the power of his Truth,
and I can bow to none but him (no, not to my most dear father), now I am no comfort.
I am sure I have had little comfort all my days,
in seeing my father`'s course of religion, which I ever could testify of,
as not being of God (yea, my late dear mother would often bewail it to me);
and many times have I poured out my soul before the Lord.
-- Yet hear my words, O my father, hear my words.
Oh! pierce into the nature of things.
Set not up shadows instead of the truth.
Wait for the gift.
Receive the true love, the true peace, the true unity, the true humility,
(which lies not in the will of the creature, but destroys it),
and we shall soon know one another, and have comfort in one another.

[.signed-section-signature]
I.P.

[.signed-section-context-close]
14th of 12th Month, 1658
