== APPENDIX A Additional Testimonies for Isaac Penington

=== The Testimony of WILLIAM PENN, concerning ISAAC PENINGTON

As the memory of the just is blessed,
so to me there seems a blessing upon those that have a right remembrance of them:
wherefore, to the memory of this just man, my dear friend and relation, Isaac Penington,
I do, with a sincere and religious affection, dedicate this ensuing testimony.

And first, give me leave to say something of his manly capacity: the best comes after.

He was well descended as to his worldly parentage, and born heir to a fair inheritance;
his education was suitable to his quality among men,
having all the advantages the schools and universities of his own country could give him,
joined with the conversation of some of the knowingest
and considerablest men of his own time.
But his natural abilities, the gifts of his Creator, they excelled:
he was a man quick in apprehension, fruitful in conception,
and of a lively wit and intelligence, all adorned with an extraordinary mildness:
that as other men are wont to show their pregnancy by sharpness,
he manifested his with an engaging sweetness.

His father`'s station in public business gave him
pretence enough to share of the world`'s greatness;
but, which brings me to his better and religious capacity, he, with blessed meek Moses,
refused the Egyptian glory of the world,
and chose rather a life dedicated to an inquiry after God,
and holy fellowship with him and his despised Israel.

Very early did the Lord visit him with a more than ordinary manifestation of his love;
and it had that good effect upon him, that it kept him both from the evils,
and vain worships of the world;
and he became the wonder of his kindred and familiars for his awful life,
and serious and frequent retirements,
declining all company that might interrupt his meditations;
and by giving himself over to a life of mourning and pilgrimage,
he was as unpleasant to them, as the world was to him.
Nor did this sorrow flow from a sense of former vice;
for he was virtuous from his childhood; but with holy Habakkuk,
from the dread he had of the majesty of God,
and his desire to find a resting-place in the great day of trouble.
Nothing in these exercises gave him ease or comfort,
but the smiles of God`'s countenance upon his soul;
and that it was he thirsted after with a perpetual solicitation; first,
"`How shall I appear?`" and then, "`Oh that I may appear before God!`"

His inward exercises and enjoyments being of a very peculiar nature,
made him take but little comfort in any of the religious societies then known to him.
He was as one alone;
for he saw so much of that uncircumcised and uncrucified flesh
(which is as grass) profess the mysteries of the heavenly kingdom;
I mean people but under ordinary convictions, that had never known Jacob`'s troubles,
nor the fear and trembling with which the true salvation is wrought;
and that the spirit and abilities of man took up so great
a part and share in religious duties among them,
and the spirit of the Lord so little, if any at all;
that he felt them of little or no use to him.
On the contrary, he was often burdened with them,
and pressed in spirit to lay open their carnal state under a Christian profession;
and though they held the notions of the truth,
it was not in the precious and experimental sense
of the holy virtue and life of the truth;
insomuch that he found it his duty to endeavor to break their false peace,
and bewilder their lofty wisdom and profession;
rather approving of a state of humble doubting, than hypocritical confidence;
and that waiting for the Lord`'s coming in spirit, without sin,
to the salvation of the soul, that people may truly know the Lord and his work,
and from thence speak forth his praise to others,
than profess the enjoyments of other saints,
that had been obtained through great tribulations,
when they had never known any such thing in themselves,
and so had no true sense of God`'s inward work,
nor the true sacrifice of God`'s preparing to offer to him,
which only is accepted with him.

This drew reproach upon him, as a man singular and censorious,
from the worldly professors;
particularly the clergy (that common eclipse between God and the souls of people);
yet those that with him waited for the consolation of Israel,
and the coming of the Son of man in power and great glory, they found him out,
valued and honored him, and sweet was their fellowship to him;
who boasted in nothing more than that they had nothing to boast of,
whilst the Laodicea of their age thought she wanted nothing:
and in that emptiness they waited to be filled of
him that filleth all things at his coming and kingdom,
that they might be the witnesses of his resurrection and appearance.
Some of them died before that blessed time came; some saw it, and were glad,
and with good old Simeon departed in peace:
and others lived to see the glory of that blessed
day both dawn and break forth upon them,
to their admiration and comfort; among whom my dear father-in-law, Isaac Penington,
was not the last, nor least of note.

About the year 1657, it pleased the Lord to send him a Peter to declare to him,
that the time of the pouring forth of the Holy Spirit,
and breaking forth of the heavenly work of God in the souls of men and women was come;
and many Aquilas and Priscillas came after,
who instructed him in the way of God more perfectly.
And however he was advanced above many in his knowledge of scripture,
and had formerly received many heavenly openings of truth`'s mysteries in the soul;
yet did the Lord`'s way of appearance disappoint his expectation;
and when the light broke forth in his heart, which his sincerity longed for,
he found a great mixture, and that he had much to lose and part with,
before he came to be that blessed little child (that new
and heavenly birth) which inherits the kingdom of God;
which made him cry, "`Narrow is the way, and strait is the gate, indeed,
that leads to life.`"

But to the glory of the living God, and praise of this just man`'s memory, let me say,
neither his worldly station, the most considerable of any that had closed with this way,
nor the contradictions it gave to any former conceptions,
nor the debasement it brought upon his learning and wisdom,
nor yet that reproach and loss that attended his public espousing of it,
did deter him from owning, and cordially embracing of it;
but with an humble and broken spirit, he fell before this holy appearance of Jesus,
that true light of men, whose power and life he felt revealed in him,
to the saving of his soul;
and boldly owned and confessed this spiritual coming of the great Messiah,
that was able to teach him all things: to his Name his knee truly bowed,
and the scripture was in him fulfilled; with Nathaniel he cried,
"`thou art the Son of God! thou art the king of Israel!`" Now he
saw clearly between the precious and the vile in himself,
between that which was truly of God, and that which was merely of man,
in his former exercises; and he was not stiff nor stout in defence of his own building,
and former conceivings: no; but sold all for the pearl,
and became willingly a poor man in spirit,
that so he might enter into the kingdom of God.
Thus parting with all he had not received of God, he received a new stock from heaven,
wherein God prospered him; the dew of heaven rested upon his branch and root,
and he grew rich and fruitful in all heavenly treasure; "`full of love, faith, mercy,
patience, and long-suffering; diligent in the work of the Lord,
and exemplary in his duty to God and men.`" Insomuch,
that I may say he was one of a thousand; zealous, yet tender; wise, yet humble:
a constant and early comer to meetings, and watchful and reverent in them:
one that ever loved power and life more than words; and as for that he waited,
so would he be often deeply affected with it,
and made to utter such testimonies as were greatly to the help of the poor and needy,
the weary and heavy laden,
the true sojourner and traveller to the eternal rest and city of God.
To this his writings as well as ministry tended,
as his ensuing worthy labors will abundantly witness;
wherein it will be easy for the reader to observe his peculiar
and mighty love to the great professors of religion in these kingdoms,
whom carnal apprehensions, or unjust prejudices,
have hindered from closing with the blessed truth, as it is known and felt amongst us;
and his fervent labor to remove those obstructions, with such tenderness,
yet great clearness, that I may venture to style him their apostle;
for as in almost every meeting, so in every book,
the bent of his spirit was towards them,
that those who made a more than ordinary profession of God,
not without some ancient touches of the divine grace,
and experience of God`'s visitation,
though much extinguished with human and worldly mixtures,
might come to know what that was they once tasted of, how they lost it,
and which is the way to recover the living and full enjoyment of it,
even the inward knockings and appearance of Jesus the Saviour,
to the salvation of their souls:
and I pray God they may answer his love (for he was much spent on their account);
that so his ministry, writings, travels,
and tears may not be matter of charge and evidence
against them in the day of their judgment.

As his outward man grew in age, his inward man grew in grace,
and the knowledge of our dear Lord and Saviour Jesus Christ; for the excellency of which,
he had justly counted all things else but as dross and dung:
for it was observable among them that rightly knew him in his declining time,
when the candle of his natural life burnt dimmer, his soul waxed stronger, and,
like a replenished lamp, shined with greater luster;
and truly he had a double portion of the spirit upon him,
and was anointed with judgment and zeal for the Lord,
which appeared in two eminent respects.

First,
that he was very urgent that all those who knew any
thing of the heavenly gift of ministry unto others,
would always wait in their several exercises to be
endued with matter and power from on high,
before they opened their mouths in a testimony for the Lord; and that at all times,
as well out of meetings as in them, they might live so near the Lord,
as to feel the key of David opening the mysteries of the heavenly kingdom,
and by experiencing the depth of the heavenly travail, and the trials, deliverances,
and consolations of it, with that dominion and victory that in the end, by perseverance,
are obtained, they might be as true saviours on Mount Zion,
the salt and lights of the world, thoroughly furnished to every good word and work,
and master-builders in God`'s house;
that "`a pure and living stream of ministry might
be continued and conveyed to the generations to come;
that they might not only hear, but taste of,
what we have known of the word and work of life and
redemption in our age.`" Herein he was very careful.

But his excellency in the second respect,
was his fervent love to the heavenly union of brethren; and whatever struck at that,
though under ever such specious pretences, he no sooner perceived it,
and the subtle but mischievous workings of it, than with deep wisdom he detected,
and with his whole might encountered and opposed it.

And though by nature he was suffering to a degree of letting
his mercy to others almost wound his own soul,
yet so deeply did his love to the Lord and his people,
and to that comely order God had settled them in, engage his soul,
that he was as bold as a lion, yea, as warlike as a champion,
against that spirit that went up and down to sow jealousies,
to smite and reflect upon the holy care of the brethren,
carnally interpreting their tender love and great pains,
as if what was done by them were not intended to the edification of the body,
but exaltation of some particular persons over it.
This ingratitude and injustice his soul abhorred,
and often mourned for such as were so seduced;
as if it were the design of those that had from the beginning
laid out themselves in the service of God and his people,
to bring them at last to a blind and unwarrantable subjection,
that they might the better exercise dominion over them.
This evil eye he helped to put out; and,
in his opposition to this wandering and destroying
spirit that leads out of the love and unity of brethren,
he approved himself a valiant of Israel, a Phineas for the God of his salvation;
and the rewards of heaven were poured into his bosom;
for his holy ministry manifestly increased in life and power,
and his peace flowed as a river, and many were the witnesses of his enlargements.
Let those that have lost their first love, and are gone from their ancient habitation,
"`rage, and imagine vain things,`" if they will:
surely the travails and testimonies of this blessed man will be
a witness against them that will not easily be silenced,
and a burden upon their backs that will not be easily taken off.
But because he desired not their destruction,
but prayed earnestly to the last for their return, let not me,
whilst I am writing of his character, fall short of his compassions; no,
I pray God also with my whole spirit that they may repent, be contrite in heart,
and faithfully return; at which, if the angels in heaven,
certainly the spirits of the just that dwell in heavenly places,
will abundantly rejoice too.

These two cares were chiefly and almost continually before him.
Thus he drew near to the grave, and I now draw to an end;
but because this service is never to be done again, let me say,
that as he was a light in the church, so he was a blessing to his own family:
"`A most chaste and loving husband, a very tender and prudent father,
and a just and kind master.`" I will add, "`and a good neighbor,
and a most secret and firm friend;`" of all unapt to believe ill, but never to report it,
much less to do it to any: a man that ruled his tongue, swift to hear, slow to speak:
but, when he did speak, he was serious, yet sweet, and not uncheerful.
What shall I say, but that great and many were the gifts God honored him with,
and with them he truly honored his profession.
-- Being thus fit to live, he was prepared to die,
and had nothing else to do when that summons was served upon him,
which was in the sixty-third year of his age;
at what time it pleased the Lord he fell very sick, under a sharp and painful distemper,
which hastened his dissolution: however,
the anguish of that bitter exercise could give no shake to internal peace,
so well established before it came; but he died, as he lived,
in the faith that overcomes the world; whose soul,
being now released from the confinements of time, and the frailties of mortality,
is ascended into the glorious freedom and undisturbed joys of the just, where,
with his holy brethren the patriarchs, prophets, apostles, and martyrs of Jesus,
he forever blesseth and praiseth the God and Father
of the righteous generations by Jesus Christ,
God`'s Lamb, and our heavenly Redeemer; to whom with the Father be all honor, glory,
might, majesty, and dominion, through all the ages of his church, and forever.
Amen.

WILLIAM PENN

Westminster, the 12th of the 12th month, 1680-81

=== The Testimony of GEORGE WHITEHEAD, concerning ISAAC PENINGTON

Precious in the sight of the Lord is the death of his Saints.
Ps. 116:15

THAT the Lord God, who is the Father of mercies,
is truly good unto all that wait for him, and diligently seek after him,
hath been signally manifested and experienced in our days, as in former ages;
and that he fails not to answer the desire and travail
of that soul that hath sincerity towards him,
however it be for a time clouded and bewildered under various professions and notions:
sincerity and honesty of heart in inquiring after
the knowledge of truth shall not be disappointed,
nor miss of its blessed end.
I hope I shall not need to write an apology for this man`'s many writings;
but let the sincere meaning and honest intent thereof,
and the lines of true sense and good-will therein,
speak forth the Christian mind and spirit of the author.
Nor is it altogether proper for me to apologize in such a case,
having not read all these his books and writings now to be exposed to public view,
though some of them I have at times formerly conversed with,
as opportunities have admitted: which,
as I have perceived the testimonies and instructions thereof to be both savory and experimental,
so I charitably believe and hope of the rest.
But in this I can be more general and absolute concerning the person;
that he was a man that sincerely sought after the
knowledge of the Lord God and his holy truth;
and that accordingly the Lord did vouchsafe graciously to
answer the sincere desires of his soul in due time,
to the settling of his mind,
and staying his soul in a secret sense and feeling of his living truth, power,
and spirit,
to his confirmation in that most precious and living faith
which was once delivered unto the saints in light:
and as God opened his heart to the tender reception
of his holy truth and gospel of peace,
and embracing the faithful messengers thereof;
so he wrought both immediately by his spirit, and instrumentally by his messengers,
for his confirmation in that light and grace,
from whence he had often before received many true discoveries, sights, and openings;
having also often heard the sound of that divine breath, or spirit of life,
which moved in his heart, before the immortal birth thereof was brought to light,
or the man-child (for which his soul travailed) was brought forth into the world.
He was not willing to obscure his divine discoveries,
nor to put his candle under a bushel, nor hide his talent in the earth;
but was industrious on the Lord`'s behalf,
in telling and showing to the sons of men what discoveries
he had made to him of the way of life and salvation,
from one degree to another.
His inward exercise of mind, and attention upon our Lord Jesus Christ in his light,
were serious, and his conversation innocent;
for he knew the presence and blessings of God were only to be enjoyed in such a condition.
The remembrance of his zeal for the holy truth in
the improvement of his gift is never to be extinguished,
nor the record of his integrity and faithfulness ever to be obliterated:
his tenderness and compassion towards the misled captives were such,
that he was not wanting in his industrious endeavors
for their deliverance out of their darkness,
and spiritual blindness of thraldom.
He earnestly labored with the barren professors under various notions,
and the fleshly Christians of our times, to invite them to the true light, life,
and spirit of Christianity, that they might not stick in their empty forms,
and literal professions, short of the power of godliness.
For his eye was to the principle of life, the true seed wherein the blessing is,
and to the spiritual, immortal birth, that breathes to God, and receives life,
nourishment, and strength from him, and lives to him,
as knowing that the fleshly birth must not inherit the promise,
nor the son of the bond-woman be heir with the son of the free.
He truly esteemed of the Holy Scriptures,
and seriously and frequently conversed with them:
his eye being to that divine light and spirit of Christ Jesus, which opens them,
and gives the true understanding and experience of them;
for he preferred the true and spiritual knowledge of the
Holy Scriptures before all literal knowledge and under standing,
exalting the spirit above the letter, the power above the form,
the substance above the shadow;
as knowing that the Holy Spirit and Power was the foundation and cause of scriptures,
and form of godliness.
His patience and innocency have been well known,
even towards such contentious and prejudicate professors as evilly requited
his labors of love (for their good) by perversely exposing him in print:
but he well knew that truth and innocence would outlive all envy and evil-mindedness.
It was given to him not only to believe,
but also patiently to suffer for the name of Christ; he patiently suffered by reproaches,
contradictions of evil men, persecutions and imprisonments.
I cannot forget the sweet communion and society in
the truth which we have often had together,
especially of latter years; being fully satisfied,
that it was a real earnest of that glorious communion
we shall eternally enjoy together in rest and glory,
where the precious and sincere soul is entered with
the Lord and all his saints and angels,
and spirits of just men made perfect, who are written in heaven,
having obtained a part in Christ Jesus, the resurrection and the life,
where the second death hath no power.
And to this glorious end and rest from our labors,
others of us yet surviving are travelling and hastening; glory and triumph forever!

Now, serious reader, in love to the truth and thy soul,
I would leave this caution with thee in relation to the
books and writings of this our deceased friend and brother,
that if thou meetest with any thing therein which thou dost not understand,
censure it not; be not prejudicate in any case, but wait till the Lord come,
who reveals secrets, and unfolds mysteries.
And if any thing (especially of what was early written,
as in a time of infancy) seems doubtful, or not so clear to thy understanding,
let it have such charitable construction as becomes a Christian spirit towards an industrious,
honest-hearted, and well-meaning servant of Christ in his lifetime,
who was and is ever blessed of the Lord, and now gone to his rest from his labors;
the general tenor and import whereof clearly evince his
pious endeavors for the good of the children of men,
and proclaim his Christian design and industry to
promote truth and righteousness in the earth,
pure religion, and Christianity in spirit and life among men.
The Lord of the harvest send forth more fruitful laborers
into his harvest and vineyard! for the harvest is great.

G+++.+++ W.

London, the 28th of the 6th month, 1680

=== The Testimony of SAMUEL JENNINGS, concerning that faithful Servant of the LORD, and our dear Friend, ISAAC PENINGTON, whom GOD hath lately removed from us, and fixed in his Eternal Rest

Strong and powerful is that excellent arm of the Lord,
which hath been revealed and made bare in this our day;
and very effectual hath been the operation of it for the
gathering of many into a nearness to the Lord,
and leavening of them into the nature of its own purity;
amongst whom God hath numbered this our dear friend, and dignified him with that honor.
And since God hath impressed upon our souls such a sense of him, I could not be clear,
in respect of my duty to God, and love to him, to shut it up only in my own bosom,
without giving this public testimony of him.
Although I know I can add nothing to him, as to his immediate enjoyment,
yet let it be as an evidence of the esteem I had of him when with us,
and of his memorial, now removed from us, which God will perpetuate among the righteous,
when the name of the wicked shall rot.

As to the innocency of his conversation in general (which is the
most evident token of the indwellings of truth and sincerity),
I have this to say upon my own observation of it, I know none that did exceed him;
for in that, God made him an adorning to the doctrine of the gospel.
To mention particularly those divine gifts wherewith he was eminently endued,
would be too large, yet I cannot wholly omit them;
wherefore I shall first mention that which had the first and chiefest place with him;
namely, his deep travail, labor, care,
and desires for the prosperity of that weighty and blessed work,
which God is carrying on in the earth; to wit, the gathering of lost man to himself,
and bringing him to know salvation in him; in which labor God blessed him with success,
and gave him the tongue of the learned to speak a word in due season,
fitly comparable to apples of gold in pictures of silver;
and by the force of this word he reached to many,
to the turning of them from the evil of their ways; which remains as a crown upon him,
and shall cause him to shine as a bright fixed star in the firmament of God forever.
And how many living witnesses are left behind,
of the use and service that God made him to be of to them,
who are deeply affected with the sense of their loss in him, yet dare not complain,
because the Lord hath done it!
Oh, how hath my soul, with many others, been consolated with him,
in the communion we have had together with God,
when the Lord hath opened his mouth in wisdom,
and caused his doctrine to drop as the rain,
and his speech to distil as dew on the tender plants!

O my dear brother! (or rather to many of us wast thou, in God,
a father) my soul is often pained, in the sense of thy absence, for our sakes:
yet greatly comforted and satisfied in God for thy sake: for our loss, though great,
doth not equal thy gain.
Oh, how often hast thou been opened, and thy spirit sweetened,
and in that sweetness drawn forth to minister to those that were Israelites indeed,
when thy words were softer than oil, sweeter than honey,
and more refreshing than the purest wine;
but to the wicked and deceitful as penetrating arrows.
And although it was so contrary to his nature to
touch with strife (being of so meek a spirit),
yet God, that guides the meek in judgment,
did sometimes concern him in a dreadful yet true
testimony against all that would divide in Jacob,
and scatter in Israel.
Yet how entire was his love to all those who had a right value of, and abode in,
the unity of the pure truth, against all the contemners and invaders of it!
How affectionately and reverently have I heard him speak of those,
who were the messengers of glad tidings to us,
and publishers of that peace which he is now in the certain possession of,
as the reward and end of the just and upright! but especially great were his regard to,
and esteem of, those who have faithfully borne the heat and burden of the day;
whose arrows the Lord directed to the wounding of the man of sin,
and who yet remain as a bow that abides in its strength,
and wax yet stronger and stronger:
those he did account (as indeed they are) worthy of double honor.
And although, through the infirmity of his nature, and weakness of his constitution,
he was made unfit for much hard and public travel;
yet his constant practice did declare he had a vigorous and active mind,
truly bowed to the service of truth,
as may appear by the many private and seasonable visits he made by writing,
unto those whom he had no other opportunity of being helpful to;
and much service he had of this kind, beyond what many were sensible of.
Many young and tender and distressed ones will lament their loss in him,
who was so easily touched with a feeling of their exercise,
from the sense and remembrance he had of his own; and was very ready, and also fit,
to contribute something to their relief: for as he was once a man of sorrows,
and well acquainted with grief, so this benefit did he reap by it,
to learn experience by the things he suffered;
and all the tribulation he met with did but make way for
the superabounding of his consolation through Christ.

What he was in his family, and especially to his dear and tender relations,
(whom he left weeping behind him,
though not without hope,) I shall not need to say much of;
knowing they themselves cannot be without a larger
testimony than mine concerning the matter:
only this I shall say,
I would to God there were more so fit for our example in each relation.

Having thus far sincerely discharged my duty in giving this testimony,
I am willing to confine myself to as much brevity as I can;
though much more might be truly said of him, and it is hard to say so little.
Yet, for further satisfaction to any concerning him, that are desirous of it,
I refer them to his writings, now published together, for common benefit:
only let me give the reader this advice,
that as God gave him wisdom to divide his word aright,
so do thou read it in the same wisdom to receive it aright; for in that only,
canst thou take a right measure of him, or have true fellowship with him.
I have only this to add, as a caution to all, that as truth hath many enemies,
so this our dear friend, for truth`'s sake, hath some also;
concerning whom I have a feeling that they will be ready to grudge
and take offence at this our innocent and justifiable practice,
to preserve the remembrance of the faithfulness of
those who have faithfully finished their course,
and, through the power of Christ, have had victory over the last enemy.
There can be no other ground for this, but envy or ignorance; and therefore,
to prevent so ill an effect (let it spring from whom it will), let such know,
that it was once not only allowed, but commanded of God,
to write the dead blessed that die in the Lord, as well as to esteem them so.
And since it is undeniably the mind of God "`that the just shall be had
in everlasting remembrance;`" what can be more effectual to it,
than by our written testimony to commend their memorial to our posterity,
that they may glorify the God of their fathers, and, after their example,
walk in his way; in which the Lord, who gathered us into it,
preserve us to the time of our death, that,
with the worthies of the Lord that are gone before us, we may receive the crown of life.

SAMUEL JENNINGS

=== The Testimony of THOMAS ZACHARY, for ISAAC PENINGTON

Ah! my dear and ancient friend! what shall I say of thee?
Thou hast been a long traveller, even from thy youth, through Egypt and Babylon,
and therein desolate, seeking rest, but finding none; till the Lord God,
the Shepherd of Israel (who heard thy bemoanings), found thee out,
and gathered thee by his Shepherd`'s crook out of and from all the barren mountains,
and wild, obscure places, wherein thou wast wearied and lost;
even in the wilderness did the Lord allure thee, and bring thee out to his own flock,
to hear and know his own voice from the voice of all strange spirits,
and to feed among his lambs in the pastures of life;
whereby thou grewest strong in the living word of power,
and hadst wherewith to minister of the words of life plentifully to others,
through the divine presence and overflowing life of the Father in thee and with thee;
whereby many have been awakened, strengthened, and comforted in the Lord alone,
and the very joy of God`'s salvation hath reached to the mourners of Israel.
Ah! a true laborer hast thou been in God`'s vineyard; and sowed,
in much brokenness of heart, and tears, the precious seed of God`'s kingdom,
and waited in the faith and patience for the coming up thereof,
and hast seen the desire of thy soul answered; and now is thy work, labor,
and travail over; and as thou hast sowed in the Spirit,
thou art now reaping of the Spirit, life everlasting,
and art released out of this strait and troublesome world,
wherein thou wert long a stranger and sufferer, and hadst no resting-place in it;
for thou earnestly soughtest for a city that had foundations,
whose builder and maker was God alone; and now thou hast found it,
and art gathered into it, inheriting thy own mansion of peace, rest, and joy,
which the God of the just hath provided for thee.

Oh, blessed and praised be the God of Abraham, Isaac, and Jacob,
who is not the God of the dead,
but of the living! and from the living ascend heavenly
praises and hallelujahs to him forever and ever.

THOMAS ZACHARY

=== The Testimony of AMBROSE RIGGE, of the Life and Death of ISAAC PENINGTON

THE Spirit of the Lord is upon me, and the fountain of love and life is open in my soul,
and freely floweth towards all my dear brethren and fellow-laborers
in the great harvest of our Lord and Master,
who are yet in the body;
and the renewed remembrance of them whose earthly tabernacles are dissolved,
and have put on immortality, is often with me in endeared love;
in which at this time I behold dear Isaac Penington, in lasting union with us,
though absent in body; whose work and labor of love in his day are not forgotten of God,
nor his people.
He was brought to the true fold in an early hour of the gospel day,
as it broke forth in our times, and a rest was prepared for him in a weary land;
and the Lord heard the cry of his soul in the deep, and prepared a deliverer for him,
out of the great sea of waves, troubles, and uncertainties;
and he came to the rock with joy when he saw him, and he built upon him,
and was established and fortified against every storm and tempest of the boisterous seas,
which lifted up themselves against him; and they were not a few,
nor of small consequence: his trials were great, both inward and outward,
in which he quitted himself as a valiant champion in the Lamb`'s war.
The Lord was with him, and delivered him out of all his troubles, and filled his cup,
and often caused it to overflow, to the refreshment of many;
and freely he dealt his bread to the hungry, and his cup he handed to the thirsty:
many widows and fatherless were relieved by him;
his life flowing forth as a fountain most clear, both to the freed and imprisoned seed:
a man of a contrite and humble spirit, in the innocency of a little child,
by which he had entrance into the kingdom of immortality; where he now resteth,
out of the reach of the oppressor.
He was a man of sorrows, and acquainted with griefs;
his life was a pilgrimatory passage to eternity.
-- Who can say he oppressed them, or was chargeable to them;
though part of his outward substance he lost for the truth`'s testimony?
He was a man filled with the power and spirit of the Lord; who, both in word, writing,
and conversation,
gave testimony to the world that he sought a city whose builder and maker was God.
He was a faithful witness for the saving truth,
against all bad spirits and unsound members,
unmeet for that body which God hath now prepared to do his will:
and his manuscripts left behind proclaim him a witness against all false
hirelings and their unrighteous practices and deceitful doctrines,
whereby the earth both is, and hath for ages been corrupted;
and the minds of young and old filled with unsound principles
and beliefs in the weighty things relating to another world;
and give a true and lasting testimony to the strait and narrow path of life and righteousness.
He was endowed with wisdom to discover the living child`'s mother,
and give her the possession;
for the spirit of a discerning and of a sound mind was in him,
and the secrets of the Lord were upon his tabernacle.
His upright Christian spirit rendered him lovely to the upright,
and formidable to the wicked.
My heart is full of tender love to his life, who died in the Lord,
and his works follow him;
and therefore doth my soul believe him blessed with the righteous in his death.
He was a man of a retired spirit, and little minded the things of this life;
but loved justice, and delighted in mercy.
The products of his life were the fruits of the Spirit of Truth,
therefore he is recorded among the living as one of the Lord`'s worthies,
whose remembrance shall live to generations to come.
His testimony he kept to the end, and finished his course with joy; so, on his behalf,
let the living praise the Lord, as doth my soul at this time; even so forever.

AMBROSE RIGGE

Gatton in Surry, the 22nd of the 10th month, 1679

=== The Testimony of ROBERT JONES, concerning ISAAC PENINGTON

IN the remembrance of my dear friend deceased, I had something lived with me,
to give in as in a way of testimony, according to the knowledge and sense I had of him.
He was a man very tender in spirit, and of a broken heart before the Lord,
as I often had a living sense thereof;
the sense of the power of an endless life being often upon him, which did affect many,
breaking them down in great tenderness.
His testimony for the Lord and his blessed truth was very sound and weighty,
to the reaching the consciences of many.
His labor in writing was in great tenderness, to the gathering of the scattered,
to the building up of the convinced,
and to the comfort and consolation of the brokenhearted;
for great were the bowels of mercy in him, even to all,
especially to such who had breathings in their hearts after the Lord,
and the way of his holiness; his travail was greatly for such;
and by his tenderness in the Lamb`'s spirit he had an influence upon many,
by reaching to the good in them; for his bowels were moved for them.
Well! his reward is with the Lord forever.
In his family he was a man of knowledge, and of true watchfulness,
that all those that were under his care might be kept savory in all things;
being as a weaned child from the world, and those things that perish with the using.
His moderation in all things was well known to many.
What shall I say?
He was a man wholly devoted in his heart to serve the Lord his God; yea,
I am persuaded it was his delight to do his will.
I have had knowledge of him near twenty years, especially in suffering;
for it pleased the Lord so to order it,
that our lot fell together in prison several times; and I may say it was well it was so;
for being made willing by the power of God (that
did attend him) to suffer with great patience,
cheerfulness, contentedness, and true nobility of spirit,
he was a good example to me and others.
I do not remember that ever I saw him cast down or dejected
in his spirit in the time of his close confinement,
nor speak hardly of those that persecuted him;
for he was of that temper as to love his enemies, and to do good to those that hated him;
having received a measure of that virtue from Christ, his Master,
that taught him so to do.
Indeed I may say, in the prison he was a help to the weak,
being made instrumental in the hand of the Lord for that end;
with much more than at present I shall express.
Oh, the remembrance of the glory that did often overshadow us in the
place of confinement! so that indeed the prison was made by the
Lord to us (who was powerfully with us) as a pleasant palace!
I was often, with many more,
by those streamings of life that did many times run through his vessel,
greatly overcome with the pure presence,
and overcoming love of our God that was plentifully shed abroad in our hearts.
If I should look back, and call to remembrance my knowledge further of him,
I could write much; but this short testimony, readily springing up in my heart,
was with me to give forth in the behalf of my dear friend.
And this further I have to add; indeed when I heard of his departure, it came near me;
but considering how it was with him, being fully persuaded he was fitted for his change,
in the will of the Lord I was satisfied, counting his state happy;
having faith in God that he had laid down his head in peace,
and entered into endless glory, where sorrow shall be no more;
having done the work his Master (Christ the Lord) gave him to do.
He kept the faith to the end, and has finished his course with joy,
leaving a good savor behind him.
With his spirit my soul has union.
At the writing hereof, my heart is broken into tenderness,
and mine eyes run over with tears.
Oh! let us follow after him in faithfulness,
fulfilling what is behind of our testimony for the Lord and his truth,
being faithful to the death,
as our brother that is gone before us was (who has left a good example behind him);
so will the crown of life be our portion forever!
That it may be so with my own soul,
and with the souls of all my tender brethren and sisters everywhere,
is the cry of my heart to the Lord my God;
and I hope it will be so till time shall be no more with me in this world.

ROBERT JONES

=== The Testimony of THOMAS EVERDEN, concerning ISAAC PENINGTON

CONCERNING our dear friend and brother Isaac Penington,
I have a testimony riseth in my heart.

I, with many thousands more in this our age, day, and generation, have cause to admire,
bless, praise, and magnify the name of the Lord God of heaven and earth,
in that he hath so largely manifested himself in the hearts of male and female,
to the tendering their hearts, and enlightening their understandings;
and to the gathering them out of the empty professions, and by-ways,
and crooked paths of this world,
and to the purifying and sanctifying their hearts by his powerful word;
and giving them a good understanding in the knowledge of himself,
and the deep mysteries of his heavenly kingdom; and enabling many of them,
in the openings and motion of the same life and power, to speak and write,
to the answering unto the witness of God in many, and for the joy, comfort,
and establishment of others.
I can truly say, dear Isaac Penington was one of that number;
for after full seven years travail and deep exercise of mind among the empty professions,
and that God had showed me mercy in drawing a little nearer to me,
and shining by his glorious light into my conscience,
whereby I came to see the formality of professors,
and the emptiness of all forms and professions that stood in man`'s will,
and the vileness of my own heart, and the necessity of being saved and sanctified;
and that there was no other way, but through and by the light of Christ Jesus,
that had wrought thus powerfully to convince me;
then did some of this good man`'s writings come to my view, which answered to the light,
life, and truth, which was raised of the Lord in my heart,
as face answers face in a glass; I can truly say,
to my joy and comfort and consolation and establishment in the truth.
So that the life and testimony of him were and are truly precious to me,
and to all the faithful; and he shall be had in everlasting remembrance, who,
in the time of his life, was a true subject in the kingdom of Jesus,
and a faithful laborer in his vineyard, and a sufferer for the truth,
in the patience of the Lamb: whose delight was to devote himself to retiredness,
and to wait upon God,
to feel his powerful love to abound in his tender heart
(this he accounted his greatest glory and riches);
by which he was made entirely to love, and have a good esteem of,
his faithful brethren in the truth; and was a man of peace and love to all,
and greatly delighted in the love and unity of the brethren;
and where the contrary appeared, it grieved his tender heart.
And glad I am that it was my lot to be with him the two last meetings that he was at;
the first of which was in the city of Canterbury, I being at that time very weak in body;
and it lay upon me from the Lord to go to the meeting, where I found him,
together with Friends, waiting in silence upon the Lord;
and when I had sat down with them, oh,
the mighty power of the Lord God that descended upon us! so that
I could say the fountain of the great deeps was opened! and oh,
the powerful, pleasant, and crystal streams,
how did they abundantly flow into our hearts!
And his cup was made to overflow, to the watering and refreshing of the tender-hearted;
so that God did make me a witness of the seal of his testimony, with many more,
at those two last meetings, as at some other times,
where the life and power of God did abound in him, and sweetly flow from him.
And fully satisfied I am that the Lord hath taken him in a good time,
and from the evil to come;
and that he hath laid down his head in rest and everlasting peace with the Lord,
where he is "`at rest from his labors,
and his works follow him;`" and is in a full and perpetual enjoyment of life and glory.
And although his body be in the dust, yet his life speaks, and his name is precious,
and shall be had in everlasting remembrance.

Farewell, dear Isaac! bless`'d man of peace and love;

Thou art i`'th`' glorious rest of God above.

And this upon my heart the Lord hath sealed;

For by his Spirit to me it is revealed.

THOMAS EVERDEN

=== The Testimony of CHRISTOPHER TAYLOR, for ISAAC PENINGTON

Blessed be the God of Abraham, Isaac, and Jacob, and of all his holy ones,
from the beginning of the world until now;
who hath kept all his by his mighty power and terrible name; who,
in all ages and generations, and under all ministrations and dispensations,
have feared and served him; glory be to his name forever.
And he hath been a God of eternal love unto them,
and it hath been his banner spread over them, and is at this day,
and hath been in all ages, and they have faithfully served him,
and offered holy offerings unto him, in his pure fear and reverence,
from the sense of his living and pure streaming love;
and the blessing of God hath been and is with them,
and his glory he still puts upon them, that they may bring forth unto him;
and in the end, when they have faithfully served the Lord in their day and generation,
they may return to their long home, and be at rest with God forever,
their portion forevermore.

Of this number was dear Isaac Penington; a worthy man in his generation,
dearly beloved of his God, and preserved by him;
so that many can say how dear he was unto them whilst he lived amongst them!
And though dead,
he yet liveth and speaketh in those pure and holy testimonies he hath borne unto truth,
both in word and writing;
so that many hearts can testify and bear witness that he was truly
sent of God to publish his most blessed and holy name;
for he was a tender-spirited man, and dear to the Lord, and near unto his heart,
where he tenderly lived and breathed, that in all things he might do his sacred will.
Ah! dear Isaac Penington was a man near and dear unto my soul,
as he was unto many others, because of his inward tender-spiritedness!
And methinks I feel him still in the course of his life,
since I have of late years more especially known him.
He was a man truly endued with humility; and when we have been together,
and he would open his heart unto me, it would so answer my own life,
and the exercises of my own condition, that my heart would be so affected with joy,
that with melting bowels of God`'s eternal love we have often met and saluted each other;
and I may say, dear brother Isaac Penington, thou livest indeed,
and my soul lives with thee.
And what happiness is it, that though dear and tender friends may be outwardly parted,
yet are they dearly united together in the Lord Jesus!
And my soul at this time is overcome, melted, and broken within me,
at the dear remembrance of thee.
Oh! dear Isaac liveth, and his life is with us, and not separated from us.
And I pray God that every one who now professeth the holy name of God may live as he did,
in the singleness of their hearts; entirely, above all things,
pressing to be united unto the holy power of God alone!
His cries were daily to God,
that all truth`'s professors might be really possessors of eternal life;
and his ministry was accompanied with a holy, heavenly zeal,
in the opening life of God`'s eternal power and wisdom;
so that the true birth within would many times leap at the sweet salutation of his life;
and the tender power of God, that spoke through him,
would preciously raise the life in others to a sweet harmoniousness,
livingly to praise God: for what he innocently and humbly aimed at,
both in his words and writings (I can testify with many others), was God`'s pure glory.
An entire innocent man he was, without guile in his heart; a true Nathaniel indeed;
a lovely instrument in God`'s hand to the turning many to righteousness,
both by word and writing;
a true friend to all that waited for God`'s salvation everywhere;
and such who labored under inward exercises and travails of soul,
he travailed with and for, and ministered unto many such, both by word and writing,
that they might come to be led by the spirit of true sanctification,
and know God`'s salvation.

About thirty years since, as I remember, in the North of England,
I met with a book of Isaac Penington`'s, which had this scripture following,
as the subject whereof he treated: Job 38:2.
"`Who is this that darkeneth counsel by words without knowledge?`"
This scripture, and the matter of his discourse upon it in that book,
at that time I was affected with; for at that time, I, with others,
had precious openings of many heavenly things;
being then sensible that no man could be a minister of Christ Jesus
without the work of regeneration wrought in his own heart;
and not only so, but he must be sent of God to publish the everlasting gospel,
in the alone evidence of his power and Spirit, without the mixture of his own will,
and observing his own time when to speak, and also to be silent;
so that we believed and were convinced it was to be a spiritual ministry,
and to be dispensed in the motion and evidence of the same Spirit,
otherwise it was "`a darkening of counsel by words without knowledge.`"
This was my condition, with many others at that time,
because we spent many precious openings upon our own wills,
and the wills and lusts of others.

Now this I bring to signify that dear Isaac Penington, in those days,
had precious openings of truth, and was a man waiting for the kingdom of God,
to be further instructed therein,
and came to attain the end of his divine breathings and heavenly desires.
And those that honestly, in the fear of God, read his writings,
may see how clearly he hath writ concerning the things of God`'s kingdom;
that so both small and great, professors and profane, may, as in a glass,
see their conditions; and those that as yet have not repented, may consider betimes,
and repent, lest they perish.

CHRISTOPHER TAYLOR

=== The Testimony of MARY PENINGTON, concerning her dear Husband ISAAC PENINGTON

WHILST I keep silent touching thee,
O thou blessed of the Lord and his people! my heart burneth within me.
I must make mention of thee, for thou was a most pleasant plant of renown,
planted by the right hand of the Lord, and "`thou tookest deep rooting downwards,
and sprangest upward.`"
The dew of heaven fell on thee, and made thee fruitful,
and thy fruit was of a fragrant smell, and most delightful.
Oh, where shall I begin to recount the Lord`'s remarkable dealings with thee!
He set his love on thee, O thou one of the Lord`'s peculiar choice, to place his name on!
Wast not thou sanctified in the womb?
Thy very babish days declared of what stock and lineage thou wert.
Thou desiredst after "`the sincere milk of the word,
as a new-born babe,`" even in the bud of thy age.
Oh, who can declare how thou hast travelled towards the
holy land in thy very infancy as to days!
Oh, who can tell what thy soul hath felt in thy travel!
Oh, thou was gotten to be in the mount with the Lord, and his spiritual Moses,
when the princes and elders saw but his back-parts,
and feared and quaked to hear the terrible thunderings in Mount Sinai.
The breast of consolation was held out to thee early, and thou suckedst thy fill,
till the vessel could no longer contain;
for thou couldst not in that fulness "`see God and live`" in this tabernacle:
so that thou besoughtest the Lord to abate this exceeding excellent glory,
and give thee such a measure as was food convenient.
Oh, the heavenly, bright, living openings that were given to thee many years past!
His light shone round about thee, and the book of the creatures was opened to thee;
and his mysteries (made known to holy men of old,
who spoke them forth as they were inspired by the
Holy Ghost) were made known to thee to discern.
Such a state as I have never known any in, in that day, have I heard thee declare of.
Oh, this did it please the Lord to withdraw and shut up as in one day,
and so leave thee desolate, and mourning many a day; weary of the night and of the day;
poor and naked; sad, distressed, and bowed down.
Thou refusedst to be comforted, because it was a time of night, and not day;
and because he that was gone was not come.
His time of manifesting his love was not at hand; but he was as a stranger,
or one gone into a far country, not ready to return;
and thou wouldst accept of no beloved in his absence,
but testifiedst that he thy soul longed for was not in this or that observation, nay,
nor opening; but thy beloved, when he came, would sit as a refiner`'s fire,
and would come with "`his fan in his hand, and thoroughly purge his floor.`"
No likeness, or appearance, or taking sound of words, or visions, or revelations,
wouldst thou take up with, instead of him that was life indeed.
Oh, the many years thou puttedst thy mouth in the dust, and wentest softly,
and bowed down, and hadst anguish of soul, weeping and groaning, panting and sighing!
Oh, who can tell the one half of the bitterness of thy soul!
Because substance was in thine eye, all shadows did fly away from before thee.
Thou couldst not feed on that which was not bread from heaven.
In this state I married thee, and my love was drawn to thee;
because I found thou sawest the deceit of all notions,
and layest as one that "`refused to be comforted`"
by any thing that had the appearance of religion,
till HE came to his temple, who is "`truth, and no lie.`"
For all those shows of religion were very manifest to thee,
so that thou wert sick and weary of them all.
And in this my heart cleft to thee,
and a desire was in me to be serviceable to thee in this desolate condition:
for thou wast alone and miserable in this world,
and I gave up much to be a companion to thee in this thy suffering.
Oh! my sense, my sense of thee and thy state in that day, even makes me as one dumb;
for the greatness of it is beyond my capacity to utter.

This little testimony to thy hidden life, my dear and precious one,
in a day and time when none of the Lord`'s gathered people knew thy face,
nor were in any measure acquainted with thy many sorrows, and deep wounds and distresses,
have I stammered out,
that it might not be forgotten that thou wast in the land of the living,
and thy fresh springs were in God, and light was on thy Goshen,
when thick darkness covered the people.
But now that the day is broken forth, and thou wert so eminently gathered into it,
and a faithful publisher of it,
I leave this bright state of thine to be declared of by the "`sons of
the morning,`" who have been witnesses of the rising of that "`bright
star of righteousness in thee,`" and its guiding thee to the Saviour,
even Jesus, "`the first and the last:`" they, I say, who are "`strong,
and have overcome the evil one,`" and are fathers in Israel,
have declared of thy life in God,
and have published it in many testimonies here to the glorious saving truth,
that thou wert partaker of, livedst and passedst hence in, as in a fiery chariot,
into the eternal habitation with the holy saints, prophets, and apostles of Jesus.

Ah me! he is gone! he that none exceeded in kindness, in tenderness,
in love inexpressible to the relation as a wife.
Next to the love of God in Christ Jesus to my soul,
was his love precious and delightful to me.
My bosom-one! that was as my guide and counsellor! my pleasant companion!
my tender sympathizing friend! as near to the sense of my pain,
sorrow, grief and trouble as it was possible.
Yet this great help and benefit is gone; and I, a poor worm, a very little one to him,
compassed about with many infirmities,
through mercy let him go without an unadvised word of discontent, or inordinate grief.
Nay, further; such was the great kindness the Lord showed to me in that hour,
that my spirit ascended with him in that very moment that his spirit left his body;
and I saw him safe in his own mansion, and rejoiced with him,
and was at that instant gladder of it, than ever I was of enjoying him in the body.
And from this sight my spirit returned again to perform my duty to his outward tabernacle,
to the answer of a good conscience.

This testimony to dear Isaac Penington is from the
greatest loser of all that had a share in his life.

MARY PENINGTON This was written at my house, at Woodside, the 27th of the 2nd month,
1680, between 12 and 1 at night, whilst I was watching with my sick child.

=== The Testimony of ALEXANDER PARKER, concerning ISAAC PENINGTON

HAVING seen and read many lively and fresh testimonies of several of my dear brethren,
concerning our dear friend and brother Isaac Penington, deceased,
I did satisfy myself with what was written by them, being so full and large,
and answering my own sense, that I did acquiesce in my own mind,
not intending to appear in public in this matter; but of late hearing a testimony read,
written by his dear wife Mary Penington, it did so revive the remembrance of him,
that the sense of that love and endeared affection which I always had for him,
did so work in my mind,
that I could not be clear without casting in my mite amongst the rest of my brethren,
having known him from the early days of his convincement of the blessed truth,
in which he lived, and for which he suffered;
and in the faith of which holy truth he finished his course.

The first time that I saw his face was at Reading in Berkshire, in the twelfth month,
called February, 1656.
And though at that time he had not the outward garb and appearance of a QUAKER,
yet did mine eye behold an inward beauty and hidden virtue of life in him; and my soul,
in the bowels of the love of the truth, did cleave unto him,
and I could have embraced him in the sense thereof;
but in those early days we were cautious, and laid hands on no man suddenly.
He did not hastily join in society with us;
but for some time did reason about many things.
Though he owned the principal doctrines of truth, yet the instruments that declared it,
and their way and manner, seemed very contemptible to him,
until he heard that faithful servant of God G.F. (who was the first
man that proclaimed the gospel of life and salvation amongst us),
at a meeting at J. Crook`'s, in Bedfordshire, at the time called Whitsuntide,
in the year 1658; at which meeting the mystery of iniquity was so opened,
and the mystery of the gospel of peace so plainly manifested,
that he was fully satisfied;
and from that time he gave up himself to the obedience of truth, and took up the cross,
and became a disciple and follower of Christ,
and suffered with us for the name and testimony of Jesus,
and bore the scoffings and reproaches of the ungodly with much patience,
accounting it his riches:
and in much love did he embrace and receive the messengers
and servants of God into his house;
where were many precious meetings,
and many were convinced and brought into the way of life,
amongst whom he was a good pattern, and an help unto them;
and when they were bowed down in spirit, and afflicted in mind,
he was a great help and comfort to such,
having himself travelled through various and deep exercises,
through which the Lord brought him, and established him in righteousness.
He was a man of a quick apprehension;
and when any spark did arise from the coals of God`'s altar,
it quickly kindled in him a flame of holy zeal for God and his truth;
even in the morning of his convincement, and in the fresh openings of life,
many living testimonies were given forth by him, as in his writings may be seen,
to which the reader is referred.
His heart and soul were much drawn forth unto the professors of religion of all persuasions,
having a deep travail for them;
and in much bowels of love and tender compassion did he
entreat and beseech them to turn to the true light,
that they might be converted and healed.
But few did regard his deep travails for them;
which doubtless will rise in judgment as a testimony against them.
And I do desire, that those whose day is not over may yet consider,
and take a further view into his writings, and search into their own hearts, that,
with the light of Jesus that shines there, they may come to a true sight of their sins,
and so to a godly sorrow, which may work repentance unto life,
that they may find mercy with the Lord, and peace to their immortal souls.
In all his writings and declarations he still pointed to life,
and pressed all to mind the power of godliness,
and not to settle or content themselves in the letter or form of religion.
This, oh! this, was the very bent of his mind;
and the strong cries of his soul to the Lord were, that all might partake of life,
even the life of Jesus, in their mortal bodies, which he, through the death of the cross,
was made a partaker of; in which life he lived unto God,
and was a lively pattern of humility, walking uprightly, in innocency before the Lord.
He was a man weaned from the world, and redeemed from the earth,
his mind being daily exercised in things of a higher nature,
drinking daily of the water that Christ gives; which was in him "`a well of living water,
springing up unto eternal life,`" which filled his vessel,
and caused his cup to overflow.
Much might be said of this good man;
but words are too short to signify the depth of his inward life.
I write not these things to exalt or set up man;
but to exalt and magnify the grace of God, which was in him;
which was sufficient for him;
by the power of which he was carried on through all his troubles and exercises;
by which he was taught to deny ungodliness, and all the evil lusts of this wicked world;
and to live righteously, soberly, and godly in this world;
in which godly life he persisted to the end of his days.
And as he lived in the Lord, even so he died, laying down his head in peace,
and liveth with the Lord in the enjoyment of his love,
where there is "`joy and felicity forever,`" and his memory is sweet and blessed.
Oh that every one that professeth the holy truth "`may so run,
that they may obtain the crown of eternal life!`"
This is the travail and the earnest desire of him who seeketh the good of all mankind.

ALEXANDER PARKER

London, the 5th of the 2nd month, 1681

=== The Testimony of JOHN PENINGTON, to his dear and deceased Father ISAAC PENINGTON

Give me leave also, in a few words,
to express my sense of him (seeing I have been no small sharer in the loss),
a man that had known the depths of Satan,
and had a stock to lose before he could embrace truth in the simplicity of it;
yet came forth in clearness: which is the more remarkable,
inasmuch as few came near him in those bright openings
and piercing wisdom he was endued with in those days;
whereby he struck at all the false foundations and professions, and saw their shortness,
and the very thing they wanted.
-- So that when I have taken a view of his former writings,
and beheld the glory he once had, and withal reflected on his present condition,
on his poverty, on his nothingness, on his self-denial, and self-abasement;
how little he esteemed all his former knowledge,
and sights of the heavenly things themselves,
in comparison of the more excellent knowledge he afterwards received,
and how he could be a fool for Christ`'s sake; the thing hath affected me,
and not a little, many times.
Oh! he was not one that could deck himself, or desired to appear before men,
or his very brethren; but ever chose to be more to the Lord than to men.
And when any have been deeply reached through his tender, yet searching lively testimony,
oh, how great was his care that none might look out too much at the instrument,
or receive truth in the affectionate part!
He was also a meek man, and very loving; courteous to all;
ready to serve his very enemies and persecutors; of whom some,
from an ill opinion of him, were gained to love and esteem him.
And wherever he entered into a friendship with any, he was constant.
Whatever provocations he might afterwards receive from any of them,
he could not let go his hold; but ever retained a good-will towards them,
and an earnest desire for their welfare.
I have also observed,
where he hath been engaged on truth`'s behalf to rebuke any sharply,
who were declining from their first love, and deviating from the truth,
as it is in Jesus,
it hath been with so much reluctancy and averseness to his natural temper,
as I never discerned the like in any; and herein I am not alone.
So that it may be safely said he never used the rod, but with bowels to reclaim;
and in the love was drawn to smite what the purest love could not suffer to go unrebuked.
What he was in the church of God for exemplariness, for deep travail, for sound judgment,
and heavenly ministry, I know not a few are very sensible of.
And have not I seen his cup many times overflow, and him so filled,
that the vessel was scarce able to contain!
Oh, it was delightful to me to be with him (as it was
often my lot) in his service on truth`'s account!
And my cry is, that I may walk worthy of so dear a parent,
so unwearied and earnest a traveller for mine and other`'s eternal well-being,
and so faithful and eminent a laborer in God`'s vineyard;
who is now gone to his rest in a good day,
having first seen the effects of the travail of his soul, and been satisfied in the Lord.
But he hath left us, his children, behind, for whom he hath often prayed,
and besought the Lord with tears, that we might walk in his steps,
and our father`'s God might be our God,
and that the blessings of our father`'s life might descend upon us.
And we are still, after much weakness, upon the stage of this world; which,
that it may be so rightly improved,
that we may walk worthy of the manifold visitations we have had from him in particular,
and many faithful laborers in general,
is the incessant desire of (him that hopes with thankfulness to the Lord,
to reverence his memory,
as well as that he honors him in the relation of a dear and tender father).

John Penington

The 9th of the 3d month, 1681

P.S. It pleased the Lord to remove him from us, and take him to himself,
on the eighth day of the eighth month, 1679, between three and four in the morning,
at one of my dear mother`'s farms in Kent, in the parish of Goodnestone,
called Goodnestone-Court.
They had been among their tenants in that country,
and in their return home spent some time here;
but the day appointed for my dear father to return, he was visited with this sickness,
whereof he died, having lain just a week.
His body was conveyed thence (some of his relations
and London friends accompanying it) to London,
thence into Buckinghamshire to his own house,
and so to the burying-place of friends belonging to Chalfont-meeting (called Jordan`'s);
where he was honorably buried,
being accompanied by some hundreds of friends and neighbors.

FINIS
