== Forward

=== About Isaac Penington

Isaac Penington (1616–1679) was the eldest son of a well-
known English politician and Puritan Congregationalist.
He was brought up in a wealthy and influential family,
and "`well cultivated and polished with an ingenuous and full education.`"^
footnote:[From _The Testimony of Thomas Ellwood Concerning Isaac Penington._
Written upon the occasion of Penington`'s death.]
Nevertheless, Penington`'s aspirations, from his earliest days,
were entirely fixed upon things above,
and not upon the many things of the world that were within his reach.
He says of himself: "`My heart from my childhood was pointed towards the Lord,
whom I cared for and sought after from my tender years.
I felt that I could not be satisfied with (nor indeed seek after) the
things of this perishing world which naturally pass away;
but I desired a true sense of, and unity with, that which abides forever.`"
Indeed,
Penington`'s hunger and desperation for the true knowledge and experience of God
(as the reader of this volume will no doubt recognize) was the hallmark of his life.
Seeking, he found; knocking, the door swung wide open before him.
He sought the Lord with all his heart, soul, mind and strength, and without a doubt,
the Lord was found by him.

Isaac Penington lived in a time of perhaps unequaled political, social,
and religious upheaval in England.
In the thirty years during which Penington wrote his letters and papers,
England experienced a civil war, the trial and execution of King Charles I,
the turbulent rule of Oliver Cromwell followed by the bloody return of Charles II,
the terrible Plague of 1665, and the Great Fire of London in 1666,
after which the French joined Holland in war against England.
In the midst of these troubled times,
the Lord raised up a people who both experienced and preached
the gospel of Jesus Christ in a way that was perhaps unknown
to the world since the times of the first Apostles.
The original Society of Friends (who in scorn were called
Quakers) were a people whose Christianity stood in,
and flowed out from, the light and life of Jesus Christ reigning in the inner man.
In his searching after God, Isaac Penington turned to this light,
and soon became a shepherd among this people and a teacher of
the truth that the Lord was restoring to His body.

The collected works of Isaac Penington were first published in 1681,
just two years after his death.
A second addition was printed in 1761, consisting of four volumes.
A third edition appeared in 1784,
and a fourth (which is available online in various digital formats) was printed in 1863.
In the 1990`'s,
Quaker Heritage Press transcribed and reprinted the 1863
edition of his complete works in four hardcover volumes,
which can be purchased through their website at www.qhpress.org.
Although the language is a bit more archaic and the punctuation more cumbersome,
I strongly recommend these four volumes for the serious student of Penington.

=== About This Edition

Most readers find the original four volumes of
Pening­ton`'s works somewhat difficult to read.
Though his writings are considered to be of the Early Modern English period,
today`'s readers often find aspects of the language, punctuation,
and syntax to be fairly distracting or burdensome.
Because of this,
many give up on this tremendous book rather than make the effort to wade through it.
 
My desire in putting together this edition is twofold: First,
I have tried to reduce the four volumes down to a more manageable two
volumes by retaining the bulk of his spiritual writings and letters,
while eliminating certain things I judged to be less weighty or relevant to our day.
Some of Penington`'s writings were papers addressed to Parliament, the City of London,
or the Army, having to do with specific laws, events, and persecutions of his time.
Others were lengthy examinations and refutations
of books or papers published against Quakers.
Most of these, and other writings of this nature, were not included in this publication.

My second goal in preparing this edition was to make the English somewhat
more readable without changing Penington`'s meaning or over-modernizing his language.
I struggled with this.
I deeply appreciate Penington`'s carefulness with words,
and I know that he was profoundly aware of both what and how he was communicating.
Furthermore,
I have no doubt but that the Spirit of God was the true Author behind much of his work.
On account of this,
I approached the task of editing and modernizing these writings with great care,
and in a measure of the fear of the Lord.
In my attempts to make his writings a bit more reader-friendly,
I sought to never change his meaning,
or even paraphrase his intent with my own words as much as that was possible.
Sometimes, however, I found this to be unavoidable.
And at other times,
I felt obliged to clip out portions so as to avoid wordiness or repetition.
Still, the vast majority of the changes I made were to small things like punctuation,
word order, and spelling.
An example of the kind of changes I made can be seen below.

Original Edition::
Thou takest up Cain`'s weapons, and fain wouldst thou kill thy brother,
because his sacrifice in the faith testifies against thine.

This Edition::
You take up Cain`'s weapons, and you would eagerly kill your brother,
because his sacrifice in the faith testifies against yours.

Some words from Penington`'s era simply do not carry the same meaning today.
These words were replaced with the closest modern equivalent I could find.
A few words and concepts warranted further explanation which can be found in footnotes.
The reader will also notice that pronouns and other terms referring to deity (like
seed or lamb) are usually not capitalized in this volume (though there are some
exceptions). It was not customary to capitalize such words in Penington`'s era,
and I have left them as he wrote them.

=== About the Quakers

According to George Fox`'s autobiography,
the name Quaker originated with a magistrate named Gervase Bennet.
"`Bennet,`" says Fox, "`was the first person that called us Quakers,
because I bade them tremble at the word of the Lord.`"
Thus the name Quaker began as a way of ridiculing George Fox`'s admonition,
but it soon became widely accepted and used by both Quakers and their enemies.

In my view,
the work of the Lord in and through the original Quakers of
the 17th century was a return to the original life,
light, power,
and purity that the first Apostles knew and proclaimed as the gospel of Jesus Christ.
These men and women saw the Lord, grew up in His life, and like their Master, were hated,
slandered, and persecuted for it.^
footnote:[To read more about of the message, history,
and persecution of the original Quakers, I recommend __The History of the Rise, Increase,
and Progress of the Christian People Called Quakers__ in two volumes,
by William Sewell (1653-1720). Being a contemporary and
personal companion of many of the original Friends,
Sewell is generally regarded to be the foremost authority on the history of the Quakers.]

However, as is often the case with genuine movements of the Spirit of God,
their teachings and practices were quickly misunderstood, corrupted,
and misrepresented by the suc­ceeding generations of those who bore their name.
Customs, principles,
and outward forms can be handed down from one generation to the next,
but the life of Christ must be born in, and experienced by, each individual soul.
So it is that the Quakers of today bear little
or no spiritual resemblance to their forefathers.
The Life that once reigned in the hungry hearts
of the 17th century has been largely forsaken,
and most Quakerism has become a mishmash of godless doctrines, earthly causes,
and religious traditions.
Penington is still venerated by many as a founding father of the movement,
but most who respect him for his intellect, devotion, or sufferings,
also hide from the light that he knew and loved so dearly.

As with all of our publications,
free copies of this book can be obtained through Market Street
Fellowship by visiting www.marketstreetfellowship.com.
The publishing company requires that I also make
copies available for sale online through Amazon,
but all proceeds from sales go to the free distribution of this and other publications.


[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
September, 2014
