== Chapter I. Memoir of Isaac Penington

[.blurb]
=== The following is a testimony written by Thomas Ellwood after the death of Isaac Penington, containing two short autobiographical narratives taken from Penington`'s own writings.

[.asterism]
'''

Although I +++[+++Thomas Ellwood]
am not ignorant that many weighty and living testimonies have been
already given by true and faithful witnesses upon the same occasion,^
footnote:[The occasion of Isaac Penington`'s death.]
which might well seem sufficient to excuse mine, yet am I not thereby clear.
Rather, I find a pressing upon my spirit to write a few lines
also concerning this my dear deceased friend,
to whom I owe both affection and gratitude.
Love him I did, and that entirely, and I am sure very deservedly;
for he was worthy indeed of love from all men, but more especially from me,
to whom he had been abundantly kind.
For in the day wherein it pleased the Lord to awaken my soul and call
me out of the pollutions of the world with respect to both worship
and manner of living (for which I became the derision of my country,
the scorn and contempt of my family and acquaintance, and in a manner an outcast also),
how welcome was I then to him!
How affectionately did he receive me!
How regardfully did he take care of me!
How tenderly and like a father did he watch over me that I might not be drawn back,
or in any way be betrayed from the simplicity of truth as I had received it!
And can I ever forget his love, or let his manifold kindness slip out of my mind?
Oh no; the remembrance of him is pleasant to me,
and I cannot think of him without delight.
For as a friend, I truly loved him; as a father (for such was his care unto me),
I reverenced him; as an elder, I honored him,
and that (as he right well deserved) with double honor.
My spirit was truly united to his; indeed,
my soul was linked and knit unto him in the holy covenant of life,
which death has not been able to dissolve.
Bear with me therefore a little I entreat you, whoever you are,
under whose eyes these lines may chance to fall,
if I take liberty to express my sense of this my beloved friend.
And if I seem somewhat particular, know that my acquaintance with him was so.

He was naturally furnished with a sharp and excellent wit,
one that was well cultivated and polished with an ingenuous and full education.
His disposition was courteous and affable, free from pride and pretense.
His ordinary discourse was cheerful and pleasant, neither morose nor light,
but innocently sweet,
and tempered with such a serious gravity as rendered
his conversations both delightful and profitable.

From his childhood (as I have heard him occasionally say) he was religiously^
footnote:[In these writings,
the word _religion_ does not carry the negative connotations
with which it is sometimes associated today.
Here it is used in a positive sense to refer to the knowledge and worship of God.]
inclined, and sought the Lord in his tender years.
And although the way of truth was not then made manifest unto him, as it had been since,
yet he had then, at times, some true touches and tastes of life,
some openings and sights of heavenly things (though not so clear, unmixed,
and abiding as after). At first,
the manifestation of truth unto him was not without doubts and jealousies concerning it,
as he himself relates.
Nor was it free for some time from disputes and
reasonings against the smallness of its appearance.
Yet, after it pleased the Father, in the riches of his grace,
to reveal his Son in him (thereby giving him to
see and know with certainty what was the good,
acceptable and perfect will of God), oh how joyfully did he receive it!
How willingly did he bow before it!
How readily did he yield his neck to the yoke of Christ!
And how constantly and delightfully did he wear it!

Did he then regard the pleasures of the times,
or value the preferences and honors of the world (though
living at that time in the favor and abundance of it)? No,
no.
He turned his back upon it all,
esteeming the reproach of Christ greater riches than the treasures of Egypt.
And casting down his crown at the foot of Jesus,
he willingly became a fool to the world and to the wisdom thereof,
that he might be made truly wise to God.
And surely herein he obtained his desire;
for as he honored the Lord and preferred him above all, so the Lord did highly honor him,
and gave him liberally of the true and heavenly wisdom, adorned with humility.
Thus he was learned, and yet humble; he was full of knowledge (heavenly knowledge),
yet not thereby puffed up.
And as he had freely received of the Lord,
so did he freely and readily communicate thereof (as the following
pages do witness) unto those who stood in need of counsel,
advice, information, or direction in their travel to the heavenly country.
To this service he was fitted and very well
furnished by the experiences of his own travel;
for the Lord had led him through many a distress and difficulty,
through many temptations, trials, and exercises, by which he had tried and proved him.
Not only through the Red Sea and the Wilderness had he passed,
but the bottom of Jordan had he also seen, and the upholding,
delivering arm of the Lord through all had he known and felt.
And so he was able to speak a word of wisdom to the bewildered passenger;
a word of encouragement to the weary and fainting traveler;
a word of comfort to the afflicted soul, and of consolation to the wounded spirit.
And oh, how sweetly have I heard it flow from him!
How it has dropped like the dew, and distilled like the gentle rain!
Ah, how tender, how compassionate, how full of tenderness and feeling sympathy was he!
Surely his words have been many times as apples of gold in settings of silver.

For of a truth the Lord was with him,
and his heavenly power did often fill his temple.
The Spirit of the Lord rested upon him,
and the fruits thereof were plentifully brought forth through him, in love, in joy,
in peace, in long-suffering, in gentleness, in goodness, in faith, in meekness,
and in temperance; so richly did the word of the Lord dwell in him.
His delight was in the service of God, to which he was wholly given up,
and in it spent most of his time, either publicly in meetings waiting upon God,
or privately in visiting and ministering unto those that were distressed,
or in any way afflicted in mind or body.
And when at home, he was frequent in retirements, and very inward with the Lord.
Very fervent he was in prayer, and very frequent;
for the Spirit of grace and supplication was plentifully poured upon him,
by which he often wrestled with the Lord, and not in vain.

The holy Scriptures he read much, and with great delight and profit.
He made it not a cursory or formal business,
nor sought to pick out the meaning by his natural wit or learning.
Rather, with a great composedness of mind and reverence of spirit,
he waited to receive the true sense of them from the revelation of
that divine Spirit by which the authors of them were inspired.
Great and strong was the travail of his spirit for the salvation of others;
and in a more especial manner did his love flow and his heart yearn after the professors^
footnote:[Throughout this book the word _professor_ will be used
often to refer to those who _profess_ faith in Christ.
Here the word has nothing to do with teachers or scholars.]
of religion.
For these he continually and earnestly labored, both by word and writing,
that they might be brought out from the shadows, and come at last to inherit substance.
And blessed be the Lord,
by the powerful operation of the Spirit of God through his ministry,
many were turned to the truth, and many others confirmed in it.
For the Lord was with him and spoke by him,
so that his teaching was with divine authority,
in the demonstration of the Spirit and of power.

As to the world, and the affairs of it, he was very much a stranger;
but he was deeply experienced in the things of God.
For his affection being set on things above, his citizenship was in heaven,
and his life hid with Christ in God.
He was but a pilgrim on the earth, and is now gone home.
In his family he was a true pattern of goodness and piety,
not only by his serious example,
but by his savory instructions and exhortations to godliness.
To his wife he was a most affectionate husband; to his children,
a loving and tender father; to his servants, a mild and gentle master; to his friends,
a firm and fast friend; to the poor, compassionate and openhearted; and to all,
courteous and kind.
Very zealous was he for the truth, unwearied in promoting it,
bold and undaunted in the defense of it, faithful in his testimony to it,
patient and cheerful in his suffering for it.
A right good and pious man indeed was he, one that truly feared God,
and watchfully renounced all evil.

How great and diverse were his trials in the times of his former professions.
How earnest and pressing was his spirit then after the pure enjoyment of God.
How strange and admirable were the dealings of the Lord with him.
And how far he came at last to see the travail of his soul, and to be satisfied,
as he of all men best knew (and so has occasionally scattered
hints thereof in several places in the following pages). I had
once thought to have collected and presented these together;
but finding among his loose papers a summary account thereof,
written with his own hand above a dozen years ago, when,
being in bonds for Christ`'s sake, he was sick near unto death,
I chose rather to include that here.

[.offset]
The first account that Isaac Penington gives of his own spiritual travail is as follows:

"`A true and faithful relation, in brief, concerning myself,
in reference to my spiritual travails and the Lord`'s dealings with me.
I say true and faithful because it is of the truth, and not given forth in my own will,
but in the Lord`'s will and requiring of me at this time, for his service.
The relation is as follows:

"`I have been a man of sorrow and affliction from my childhood,
feeling a need of the Lord, and mourning after him.
I was separated by him from the love, nature, and spirit of this world,
and turned in spirit towards him, almost ever since I can remember.

"`In the sense of my lost state, I sought after the Lord; I read the Scripture;
I watched over my own heart; I cried unto the Lord for what I felt the lack of;
I blessed his name in what he mercifully did for me, and bestowed on me, etc.
Whatever I read in the Scriptures as the way of God, according to my understanding,
I gave myself to the faithful practice of, being contented to meet with all the reproach,
opposition, and several kinds of sufferings,
which it pleased the Lord to measure out to me therein.
And I cannot but say that the Lord was good unto me, did visit me, did teach me,
did help me, did testify his acceptance of me many times,
to the refreshing and joy of my heart before him.

"`But my soul was not satisfied with what I met with, nor indeed could it be,
there being further quickenings and pressings in my spirit after a more full, certain,
and satisfactory knowledge.
I yearned after the sense, sight, and enjoyment of God,
as was testified in the Scriptures to have been felt and enjoyed in the former times.
For I saw plainly that there was a stop of the streams,
and a great falling short of the power, life, and glory which they partook of.
We did not have the Spirit, nor were we in the faith, nor did we walk and live in God,
as they did.
They were come to Mount Zion, and the heavenly Jerusalem, etc.;
while we had hardly so much as the literal
knowledge or apprehension what these things were.
So I saw the whole course of religion among us was, for the most part, but a talk,
compared to what they felt, enjoyed, possessed, and lived in.

"`This sense made me sick at heart indeed, and set me upon deep crying to God,
close searching the Scriptures, and waiting on God,
that I might receive the pure sense and understanding of them, from and in the light,
and by the help of his Spirit.
And what the Lord did bestow on me in that state,
with thankfulness I remember before him at this very day.
For he was then my God, and a pitier and a watcher over me,
though he had not yet directed me how to stay my mind upon him.
And then I was led (indeed I was led,
I did not run of myself) into a way of separation from
the worship of the world into a gathered society,^
footnote:[That is,
he departed from the traditional forms of Christian worship
and began meeting together with an independent congregation
comprised of others who shared his hunger and dissatisfaction.]
for this both the Scriptures and the Spirit of God in me gave testimony unto.
And for what we then met with, and what leading and help we then felt,
there is a remembrance and testimony in my heart to this day.
But there was something lacking, and we mistook our way.
For whereas we should have pressed forward into the Spirit and power,
we ran too much outward into the letter and form.^
footnote:[Penington often uses the word _form_ to express any physical or outward ceremony,
structure, or system used in religion.]
And though the Lord in many things helped us, yet in this he was against us,
and brought darkness, confusion, and scattering upon us.
I was sorely broken and darkened,
and in this darkened state sometimes lay still for a long season,
secretly mourning and crying out to the Lord night and day.
Sometimes I ran about, searching after what might appear or break forth in others;
but I never met with anything in which there was the least answer in my heart,
except in one people, who had a touch of truth,
but I never expressed so much to any of them,
nor indeed felt them at all able to reach my condition.

"`At last, after all my distresses, wanderings, and sore travails,
I met with some of the writings of this people called Quakers,^
footnote:[Quakers of today bear little or no spiritual resemblance to their predecessors.]
which I cast a slight eye upon and disdained as falling very short of that wisdom, light,
life, and power, which I had been longing for, and searching after.
I had likewise, some time after this, an opportunity to meet with some of them,
and a few of them were by the Lord moved (I know it to be so since) to come to me.
As I remember, at the very first they reached to the life of God in me,
which life answered their voice, and caused a great love in me to spring to them.
But still, in my reasonings with them and disputes in my mind concerning them,
I was very far off from accepting them as truly knowing the Lord,
or appearing in the life and power that my condition needed and my soul waited for.
Indeed, the more I conversed with them,
the more I seemed in my understanding and reason to get over them,
and to trample them under my feet as a poor, weak, silly, and contemptible generation.
I felt they had some smatterings of truth in them, and some honest desires towards God,
but were very far off from the clear and full understanding of his way and will.
And this was the effect of almost every discourse with them.
Yet they still reached my heart, and I felt them in the secret place of my soul,
which caused my love to continue towards them, and even sometimes to increase.
But daily my understanding got more and more over them,
and therein I daily more and more looked down on them.

"`After a long time I was invited to hear one of them speak (as I had been often,
they in tender love pitying me,
and feeling my lack of that which they possessed). I went with fear and trembling,
and with desires to the Most High, who was over all, and knew all,
that I might not receive anything for truth which was not of him,
nor withstand anything which was of him,
but might bow before the appearance of the Lord my God, and none other.
And indeed, when I came, I felt the presence and power of the Most High among them,
and words of truth from the Spirit of truth reaching to my heart and conscience,
opening my state as in the presence of the Lord.
Yes, I did not only feel words and demonstrations from without,
but I felt the dead quickened, the seed raised;
insomuch that my heart (in the certainty of light, and clearness of true sense) said,
__'`This is he, there is no other!
This is he whom I have waited for and sought after from my childhood;
who was always near me, and had often begotten life in my heart;
but I knew him not distinctly, nor how to receive him, or dwell with him.`'__
And then in this sense (in the melting and breaking of my spirit),
I was given up to the Lord, to become his,
both in waiting for the further revealing of his seed in me,
and to serve him in the life and power of his seed.

"`Now what I met with after this, in my travails, in my waiting,
in my spiritual exercises, is not to be uttered.
Only in general I may say this: I met with the very strength of hell.
The cruel oppressor roared against me, and made me feel the bitterness of his captivity,
while he had any power.
Yes, the Lord was far from my help, and from the voice of my weeping.
I also met with deep subtleties and devices to entangle me in
that wisdom which seems able to make wise in the things of God,
but indeed is foolishness and a snare to the soul, bringing it back into captivity,
where the enemy`'s contending prevails.
And what I met with outwardly from my own dear father, from my kindred, from my servants,
from the people and powers of the world, for no other cause but fearing my God,
worshiping him as he has required of me, and bowing to his seed, which is his Son,
who is to be worshiped by men and angels forevermore, the Lord my God knows,
before whom are my heart and ways.
And he preserved me in love to them, in the midst of all I suffered from them,
and does still so preserve me; blessed be his pure and holy name.

"`But some may desire to know what I have at last met with?
I answer, I have met with the SEED.
Understand that word, and you will be satisfied and inquire no further.
I have met with my God; I have met with my Savior,
and he has not been present with me without his salvation.
I have felt the healing drop upon my soul from under his wings.
I have met with the true knowledge, the knowledge of life, the living knowledge,
the knowledge which is life; and this has had the true virtue in it,
which my soul has rejoiced in, in the presence of the Lord.
I have met with the seed`'s Father, and in the seed I have felt him to be my Father.
There I have read his nature, his love, his compassion, his tenderness,
which have melted, overcome, and changed my heart before him.
I have met with the seed`'s faith,
which has done and does that which the faith of man can never do.
I have met with the true birth, the birth which is heir of the kingdom,
and inherits the kingdom.
I have met with the true spirit of prayer and supplication,
wherein the Lord is prevailed with,
and which draws from him whatever the condition needs--
the soul always looking up to him in the will,
and in the time and way which are acceptable with him.
What shall I say?
I have met with the true peace, the true righteousness, the true holiness,
the true rest of the soul, the everlasting habitation in which the redeemed dwell.
And I know all these to be true in him that is true, and I am capable of no doubt,
dispute, or reasoning in my mind about them; it abiding there,
where it has received the full assurance and satisfaction.
And also, I know very well and distinctly in spirit where the doubts and disputes are,
and where the certainty and full assurance is,
and in the tender mercy of the Lord I am preserved out of the one, and in the other.

"`Now the Lord knows, these things I do not utter in a boasting way,
but would rather be speaking of my nothingness, my emptiness, my weakness,
my manifold infirmities, which I feel more than ever.
The Lord has broken the man`'s part in me, and I am a worm, and no man before him.
I have no strength to do any good or service for him.
No, I cannot watch over or preserve myself.
I feel daily that I keep not alive my own soul, but am weaker before men, yes,
weaker in my spirit, as in myself, than ever I have been.
But I cannot help but speak to the praise of my God,
for I feel his arm stretched out for me.
And my weakness, which I feel in myself, is not my loss, but my advantage before him.

"`These things I write, as having no end at all therein of my own,
but felt it this morning required of me,
and so in submission and subjection to my God have I given up to do it,
leaving the success and service of it with him.`"

[.signed-section-signature]
Isaac Penington

[.signed-section-context-close]
Aylesbury Jail, 15th of 3rd month, 1667

[.offset]
The following is a second autobiographical sketch taken
from Penington`'s writings which he entitled,
__"`A Brief Account of My Soul`'s Travel Towards the Holy Land.`"__

"`My heart from my childhood was pointed towards the Lord, whom I cared for,
and looked after, from my tender years.
I felt that I could not be satisfied with (nor indeed seek after) the
things of this perishing world which naturally pass away;
but I desired a true sense of, and unity with, that which abides forever.
There was something within me even then (the seed of eternity)
which leavened and balanced my spirit almost continually;
but I knew it not distinctly, so as to turn to it,
and give up to it entirely and with understanding.

"`In this temper of mind I earnestly sought after the Lord,
applying myself to hear sermons, and read the best books I could meet with,
but especially the Scriptures, which were very sweet and savory to me.
Yes, I very earnestly desired and pressed after the knowledge of the Scriptures,
but was much afraid of receiving men`'s interpretations of them,
or of fastening any interpretation upon them myself.
So I waited much, and prayed much,
so that I might receive from the Spirit of the Lord the true understanding of them,
and that he would chiefly endue me with that knowledge
which might feel sanctifying and saving.

"`And indeed I did sensibly receive of his love, of his mercy, and of his grace,
which I felt freely to move towards me,
even at seasons when I was most filled with the sense of my own unworthiness,
and had least expectations of the manifestations of them.
But I was exceedingly entangled about election and reprobation,
(having drunk in that doctrine of predestination,
as it was then held forth by the strictest of
those that were called Puritans). I feared that,
despite all my desire and seeking after the Lord,
he might in his decree have passed me by.
I felt it would be terribly bitter to me to bear his wrath,
and to be separated from his love forevermore.
And yet, I thought, if he had so decreed, it would be; and I would,
(despite my fair beginnings and hopes), fall away and perish in the end.

"`In this great trouble and grief (which was much
added to by not finding the Spirit of God so in me and with me
as I had read and believed the former Christians had),
and in mourning over and grappling with secret corruptions and temptations,
I spent many years, and fell into great weakness of body.
And often casting myself upon my bed, I did wring my hands and weep bitterly,
begging earnestly of the Lord daily, that I might be pitied by him,
and helped against my enemies, and made conformable to the image of his Son,
by his own renewing power.

"`And indeed at last, (when my nature was almost spent,
and the pit of despair was even closing its mouth upon me), mercy sprang,
and deliverance came, and the Lord my God owned me, and sealed his love unto me.
Light sprung within me, which made not only the Scriptures,
but even the outward creatures appear glorious in my eye.
So that everything was sweet and pleasant and joyous round about me.

"`But I soon felt that this state was too high and glorious for me,
and I was not able to abide in it, for it so overcame my natural spirits.
Wherefore, blessing the name of the Lord for his great goodness to me,
I prayed to him to take that from me which I was not able to bear,
and to give me such a proportion of his light and
presence as was suitable to my present state,
and might fit me for his service.
Whereupon this was presently removed from me; yet a savor remained with me,
in which I had sweetness, and comfort, and refreshment for a long season.

"`But my mind did not then know how to turn to
and dwell with what gave me the savor.
Nor did I know how to read what God did daily write in my heart,
which sufficiently  manifested itself to be of him by
its living virtue and pure operation upon me.
I looked upon the Scriptures to be my rule^
footnote:[The word _rule_ is used throughout to refer to that which governs, rules,
or has true authority in the life of the believer.]
and so I would weigh the inward appearances of God to me by what was outwardly written.
I dared not receive anything from God directly, as it sprang from the fountain,
but only in that indirect way.
In this way I limited the Holy One of Israel and exceedingly hurt my own soul,
as I afterwards felt and came to understand.

"`Yet the Lord was tender to me, and condescended exceedingly,
opening Scriptures to me freshly every day, teaching and instructing,
warming and comforting my heart by this.
And truly he did help me to pray, to believe,
and to love him and his appearances in anyone; yes, to love all the sons of men,
and all his creatures, with a true love.
But there was that in me which knew not the appearances of the Lord in my spirit,
but would limit him to words of Scriptures formerly written.
A fabric of knowledge out of the Scriptures grew,
and became my perfect rule (as I thought) concerning my heart, my words, my ways,
my worship.
With much seriousness of spirit, and prayer to God,
I found myself helping to build an independent congregation,
in which the savor of life and the presence of God was fresh with me (as I
believe there are yet some alive of that congregation that can testify).

"`This was my state when I was smitten, broken, and distressed by the Lord.
I was confounded in my worship, confounded in my knowledge,
stripped of all in one day (which it is hard to utter),
and became a  matter of amazement to all that beheld me.
I lay open and naked to all that would inquire of me,
and strove to search out what might be the cause
that the Lord should deal with me in this way.
Some were at first sure that I had sinned and provoked him so to do it;
but when they had scanned things thoroughly, and I had opened my heart nakedly to them,
I do not remember anyone that ever retained that sense concerning me.
My soul remembers the wormwood and gall, the exceeding bitterness of that state,
and is still humbled in me in the remembrance of it before the Lord.
Oh, how did I wish with Job, that I might come before him, and knowingly plead with him!
For indeed I had no sense of any guilt upon me, but was sick with love towards him,
and was as one violently rent from the bosom of his beloved!
Oh, how gladly would I have met with death!
For I was weary all the day long, and afraid of the night,
and weary also of the night-season, and afraid of the ensuing day.

"`I remember my grievous and bitter mourning to the Lord.
How often I did say, '`Oh Lord, why have you forsaken me?
Why have you broken me to pieces?
 I had no delight but you, no desire after any but you.
My heart was bent wholly to serve you,
and you have even fitted me (as appeared to my sense)
by many deep exercises and experiences for your service.
Why do you make me so miserable?`'
 Sometimes I would cast my eye upon a scripture, and my heart would even melt within me.
At other times I would desire to pray to my God as I had formerly done;
but I found I knew him not, and I could not tell how to pray,
or in what way to come near him.
In this condition I wandered up and down from mountain to hill, from one sort to another,
with a cry in my spirit, '`Can you tell news of my beloved?
Where does he dwell?
Where does he appear?`'
 But their voices were still strange to me; and I retired sad and oppressed,
and bowed down in spirit from them.

"`Now surely, all serious, sober,
sensible people will be ready to inquire how I
came satisfyingly to know the Lord at length;
or whether I do yet certainly know him, and am yet truly satisfied.

"`Yes indeed, I am satisfied at my very heart!
Truly my heart is united to him whom I longed after,
in an everlasting covenant of pure life and peace.

"`Well then, some will say, how did this come about?
The Lord opened my spirit.
The Lord gave me the certain and sensible feeling of the pure seed,
which had been with me from the beginning.
The Lord caused his holy power to fall upon me,
and gave me such an inward demonstration and feeling of the seed of life,
that I cried out in my spirit,
__'`This is he! This is he!
There is not another, there never was another.
He was always near me, though I knew him not, (not so sensibly,
not so distinctly as now he was revealed in me and to
me by the Father). Oh that I might now be joined to him,
and he alone might live in me!'`__
And so,
in the willingness which God had wrought in me (in this day of his power to my soul),
I gave up to be instructed, exercised, and led by him,
in the waiting for and feeling of his holy seed,
that all might be wrought out of me which could not live with the seed,
but would be hindering the dwelling and reigning of the seed in me,
while it remained and had power.
And so I have gone through a sore travail, afflictions, and temptations of many kinds.
Yet the Lord has been merciful to me, helping me and preserving the spark of life in me,
in the midst of many things which had befallen me,
whose nature tended to quench and extinguish it.

"`Now thus having met with the true way, and walked with the Lord therein,
wherein daily certainty, yes,
and full assurance of faith and of understanding is at length obtained,
I cannot be silent, (true love and pure life stirring in me and moving me),
but must testify of it to others.
And this is it:  to retire inwardly, and wait to feel something of the Lord,
something of his Holy Spirit and power, uncovering,
and drawing away from that which is contrary to him,
and into his holy nature and heavenly image.
And then, as the heart is joined to this, something is received, some true life,
some true light, some true discerning,
which the creature not exceeding (but abiding in the measure of), is safe.
But it is easy erring from this, but hard abiding with it,
and not running out before its leadings.
But he that experiences life, and begins in life, does he not begin safely?
And he that waits and fears, and goes on no further than his captain goes before him,
does he not proceed safely?
Yes, very safely, even until he comes to be so settled and established in the virtue,
demonstration, and power of truth, as nothing can prevail to shake him.

"`Now, blessed be the Lord,
there are many in this day who can truly and faithfully
witness that they have been brought by the Lord to this state.
And these things we have learned of the Lord, not by the high striving, aspiring mind,
but by lying low, and being contented with a little.
If but a crumb of bread, yet is bread; if but a drop of water, yet is water,
and we have been contented with it, and also thankful to the Lord for it.
Nor by cleverness and wise searching and deep considering with
our own wisdom and reason have we obtained it.
But rather, in the still, meek, and humble waiting,
have we found that brought into the death which
cannot know the mysteries of God`'s kingdom;
and that which is to live, we have seen made alive, and increase in life.

"`Therefore he that would truly know the Lord,
let him take warning of his own reason and understanding.
I tried this way very far, for I considered it most seriously and uprightly.
I prayed, I read the Scriptures,
I earnestly desired to understand and find out whether what
this people called Quakers testified of was the only way and
truth of God (as they seemed to suggest). But for all this,
prejudices multiplied upon me, and strong reasonings against them,
which appeared to me as un-answerable.
But when the Lord revealed his seed in me, and touched my heart with it,
I presently felt them to be the children of the Most High, and so grown up in his life,
power, and holy dominion, (as the inward eye, being opened by the Lord sees),
as drew forth from me great reverence of heart, and praises to the Lord,
who had appeared so mightily among men in these latter days.

"`So as God draws in any respect to himself, give up in faithfulness to him.
Despise the shame, take up the cross, for indeed it is a way which is very cross to man,
and of which man`'s wisdom will be exceedingly ashamed.
But that wisdom must be denied and turned from, and the secret,
sensible drawings of God`'s Spirit must be waited for and given up to.
Mark: he that would come into the new covenant, must come into the obedience of it.
The light of life, which God has hidden in the heart, is the covenant.
And from this covenant God does not give knowledge to satisfy the vast, aspiring,
comprehending wisdom of man; but rather he gives living knowledge,
to feed what is made alive by him; which knowledge is given in the obedience,
and is very sweet and precious to the state of him that knows how to feed upon it.
Yes, truly, this is of a very excellent, pure, precious nature;
and a little of it weighs more than the great, vast knowledge in the intellectual part,
which man`'s spirit and nature so much prizes and presses after.

"`And truly, friends,
I witness at this day a great difference between the sweetness of comprehending the
knowledge of things expressed in the Scriptures (which I fed much on formerly);
and tasting the hidden life, the hidden manna in the heart (which is my food now,
blessed forever be the Lord, my God and Savior). Oh, that others had a true,
certain and sensible taste of the life, virtue, and goodness of the Lord,
as it is revealed there.
Surely it could not but kindle the true hunger, and inflame the true thirst,
which can never be satisfied but by the true bread,
and by water from the living fountain.
This the Lord (in the tenderness of his love, and in the riches of his grace and mercy),
has brought us to;
and this we earnestly and uprightly desire and
endeavor that others may be brought to also.
We desire that they may rightly (in the true silence of the flesh,
and in the pure stillness of spirit), wait for, and in the Lord`'s due time receive,
that which answers the desire of the awakened mind and soul,
and satisfies it with the true, precious substance forevermore.`"

[.signed-section-signature]
Isaac Penington

Neither to Isaac Penington was it given only to believe,
but to suffer also for the sake of Christ.
His imprisonments were many, and some of them long,
which he underwent with great constancy and quietness of mind.
But because so general an account of his imprisonments
may perhaps not satisfy the desire of the reader,
I will here present a more specific, albeit brief report of his sufferings.

His first imprisonment was at Aylesbury jail, in the years 1661 and 1662,
being committed there for worshiping God in his own house.^
footnote:[Because of the political insecurity of the times,
a law had been passed forbidding all religious gatherings except
those taking place at the times and places authorized by the state.
For conscience sake, Penington and many others continued to meet together in homes.]
There, for seventeen weeks (a great part of it in winter),
he was kept in a cold and very incommodious room, without a chimney.
From such hard usage his tender body contracted so great and violent an illness,
that for several weeks after he was not able to turn himself in his bed.

His second imprisonment was in the year 1664, being taken out of a meeting,
where he with others was peaceably waiting upon the Lord, and sent to Aylesbury jail,
where he again remained a prisoner between seventeen and eighteen weeks.

His third imprisonment was in the year 1665, being taken up, with many others,
in the open street of Amersham,
as they were carrying and accompanying the body of a deceased friend to the grave.^
footnote:[This funeral procession was considered an illegal religious gathering by
the priests and magistrates who were bent on persecuting early Quakers.]
From here he was sent again to Aylesbury jail.
This imprisonment led to an order of banishment, but only for a month, or thereabouts.

His fourth imprisonment was in the same year, 1665,
about a month after his release from the former.
Until this time, his imprisonments had been by the civil magistrates; but now,
that he might experience the severity of each, he fell into the military hands.
A rude soldier, without any other warrant than the sword that he wielded,
came to his house, and told him he came to fetch him before Sir Philip Palmer,
one of the deputy lieutenants of the county.
He meekly went, and was by him sent with a guard of soldiers to Aylesbury jail,
with a kind of court order saying,
"`that the jailer should receive and keep him in safe custody
during the pleasure of the Earl of Bridgewater;`" who had,
it seems, conceived so great, as well as unjust, displeasure against this innocent man.
And although it was the year of the plague,^
footnote:[The Great Plague of 1665-1666 was the last major
epidemic of the bubonic plague to occur in England,
killing an estimated 100,000 people, about 15% of London`'s population.]
and the sickness was suspected to be in the jail,
the Earl of Bridgewater would not be prevailed with (by the earnest pleas of
persons of considerable quality and power in the county) even to permit
Isaac Penington to be removed to another house in the town,
and there kept prisoner until the jail was clear of the sickness.
But after a prisoner died in the jail of the plague,
the jailer`'s wife (her husband being absent) gave leave
to Isaac Penington to remove to another house,
where he was shut up about six weeks.
After this, by the procurement of the Earl of Ancram,
a release was sent from the said Philip Palmer, by which he was discharged,
after he had suffered imprisonment three quarters of a year,
with apparent hazard of his life, and that for no offense.

By the time he had been at home about three weeks,
a party of soldiers from the said Philip Palmer (by order of the Earl of Bridgewater,
as was reported) came to his house, and seizing him in bed,
carried him away to Aylesbury jail again.
There, without any cause showed or crime objected,
he was kept in prison a year and a half, in rooms so cold, damp, and unhealthy,
that it very near cost him his life, and procured him so great an illness,
that he lay weak from it several months.
At length, a relation of his wife`'s, by a _habeas corpus,_
removed him to the King`'s-Bench bar,
where (with the wonder of the court that a man should be so long
imprisoned for nothing) he was at last released in the year 1668.
This was his fifth imprisonment.

His sixth imprisonment was in the year 1670, in Reading jail,
where he went to visit his friends that were sufferers there for the testimony of Jesus.
Upon notice of this visit being given to one called Sir William Armorer,
a justice of the peace for that county,
Penington was abruptly brought before him and committed to the jail,
thereby becoming a fellow-sufferer with them whom he came to visit.
Here he continued a prisoner a year and three quarters,
and was brought under the sentence of premunire;^
footnote:[Premunire was a legal judgment designed to disenfranchise
those who refused to formally swear allegiance to the King of England.
Those under a sentence of premunire were considered traitors to their country.
They lost all rights to property and possessions,
were removed from under the kings protection, and were often imprisoned for life.]
but at length the Lord delivered him.

Thus through many tribulations did he enter into the kingdom,
having been exercised, tried, proved, and approved by the Lord.
Long was he in the warfare, and, like a good soldier, endured the fight of afflictions.
But having fought the good fight, and kept the faith, he has now,
in the Lord`'s good time, finished his course,
and is gone to possess the crown of righteousness laid up for him,
and for all those that love the bright appearance of the Lord.
A faithful laborer he was in the Lord`'s vineyard for many years;
but now has he ceased from his labor, and his works follow him.
He walked with God, and is no more.
To the Lord he lived, and in the Lord he died,
and by the Spirit of the Lord he is pronounced blessed:
blessed forever be the name of the Lord therefore.
