[#ch3, short="Principles Guiding Out of the Apostasy"]
== Chapter III. Some Principles Guiding Out of the Apostasy and Into the True Christian Spirit and Life

[.numbered]
__1. That there is no salvation except by the true knowledge of Christ.__

The knowledge of Christ is not literal, traditional, or fleshly,
nor can it be received by the natural understanding; rather it is spiritual,
and the understanding must be given by God.
"`He has given us an understanding, that we may know him that is true.`"
1 John 5:20. A man may read Scripture or hear sermons
and thereby gather knowledge into the old understanding.
But neither this understanding, nor the knowledge itself which is gathered, is spiritual,
but rather fleshly, and so it cannot save.
He that comes to receive an understanding from Christ,
and to have the knowledge of Christ poured forth into his heart,
knows the difference between this and the understanding into which man gathers things.
The knowledge of Christ after the letter (and the kind of
faith that corresponds to such knowledge) will not save.
A man must know Christ in that Spirit, life, and power wherein he lives,
if he rightly hopes to be saved by him. 2 Cor. 5:16-17.

[.numbered]
__2. That Christ saves by the new covenant: not by anything acquired by the mind in the oldness of the letter; but by a life begotten, which is new.__

There are two covenants made mention of in Scripture,
one of which is called the old, the other the new.
The old belonged to the Jews, which is now done away,
with their ceremonies, nation, and kingdom.
Christ is the Mediator of the new covenant, which is better than the former.
Heb. 8:6. By mediating between God and the creature,
by bringing them together in and according to this covenant, he saves.
But man, left in a state of disunion and distance from God, perishes.
So then he that is not led by Christ into that covenant, is not in the state of salvation.

[.numbered]
__3. That the new covenant is written in the heart.__

There is no other way of coming into the new covenant,
of which Christ is High-priest and Mediator,
but by having the laws of God written in the heart.
"`This is the covenant... I will put my laws into their minds,
and write them in their hearts... They shall not teach every man his neighbor,
and every man his brother, saying, know the Lord: for all shall know me,
from the least to the greatest.`" Heb. 8:10-11.
Here he is speaking of the covenant whereof Christ is Mediator, ver. 6.
which he calls a new covenant, ver. 8.
and says it is not like the old, ver. 9.
showing in two main particulars how the two are different:
1) The old was written outwardly in letters, to be read by the outward eye.
The new is written inwardly in the heart and mind,
and so can only be read by a spiritual eye.
2) Under the old they needed teaching from men.
The priest`'s lips were to preserve knowledge,
and the people were to seek the law at the priest`'s mouth.
But in the new the law should be so near to them, so clearly written in them,
that they should need no one to teach them.

From the law comes the knowledge of God, and now the law is in the heart.
And from the law in the heart springs up the true knowledge of God
both in the least and in the greatest that are within this covenant.
These need not say to one another, '`know the Lord.`'
This is the state of the new covenant,
which the Christians came to in the first days of the church.
1 John 2:27. But it has been a foreign thing in this dark night of apostasy,
and is still a foreign thing to many.
"`They shall all know me, from the least to the greatest.`"
Observe: even the least in this covenant has the law so written in his
heart that he need not seek elsewhere for knowledge.

[.numbered]
__4. That the Spirit of God alone can write the covenant in the heart; or that Christ writes the covenant by his Spirit.__

Man, by all his wisdom, cannot attain this.
Man is driven out from God,
and cannot find the way back again to him without the
teaching and leading of God`'s own Spirit.
It is not in being educated in any way of religion from one`'s childhood,
or by running to Christian denominations and sects that avails anything;
but only the hearkening to the true voice of the true Spirit.
It is written in the prophets concerning the children
of this covenant that they shall all be taught of God:
"`And all your children shall be taught of the Lord.`"
It is the Lord alone,
who by his Spirit teaches them to come to Christ and to
receive the new covenant into their hearts from Christ.
Man is incapable of knowing or receiving Christ, or his covenant,
until the Spirit has fitted and taught him.
John 14:17. But when the Spirit has prepared and fitted a heart,
then with his own finger he writes the pure law of the nature and life of Christ therein.
Receiving this,
man comes out of his own dark spirit and nature into the true knowledge of God,
and into union with him.
"`I will put my Spirit within you.`" Ezek. 36:27.
This is part of the covenant,
and indeed it is that part through which all the rest is realized.

[.numbered]
__5. Therefore, the first proper step in religion is to know how to meet with God`'s Spirit.__

There is no true progress to be made in true
religion until a man comes into the covenant;
and there is no coming into the covenant but by the Spirit.
Therefore, the first thing that is absolutely necessary to
be known in religion is the Spirit of God,
that is, his writing, or at least his motions and stirrings in the heart.

All things in religion that are acceptable to God flow from the Spirit.
All knowledge is to come from him; for he alone has revealed and can reveal truth,
and is appointed by Christ to lead into all truth.
All worship is to be offered up in him: they that worship the Father,
must worship him in the Spirit and in the truth;
for the Father seeks such to worship him, and rejects all other worshipers and worship.
Prayer is always to be in the Spirit. Eph. 6:18. Jude 20.
So too with singing.
Indeed the whole life and conduct of the Christian is to be in the Spirit.
Gal. 5:25. The mortifying of all corruption is to be done by the Spirit.
"`If you, through the Spirit, mortify the deeds of the body, you shall live.`"
Rom. 8:13. Indeed a Christian is nothing, and can do nothing,
without the power and presence of the Spirit of God in him.
So then, if nothing in religion can be done (and be accepted by God) without the Spirit,
then the Spirit is the first thing to be looked
after by him who would be truly religious.

[.numbered]
__6. The first way of meeting with the Spirit of God is as a convincer of sin.__

Here is the true entrance.
This is the key that opens into life eternal; he that can receive it, let him.
It is not by soaring aloft into high imaginations and forms of worship;
but by coming down to this low thing; namely, convincement of sin.
This is the first and most proper work of the Spirit of God toward fallen man,
whereby he opens the way toward the writing of God`'s law in the heart.

When Christ promised the Comforter, the Spirit of truth,
he said this concerning him, "`that he would convince the world of sin.`"
John 16:8. Now, to those who are created anew in Christ and become his disciples,
these receive _comfort_ from the Spirit.
But what is the Spirit to the unbelieving world?
Or how may they feel any operation of him?
He is to them a convincer of sin, and they find him checking them for,
and convincing them of, their sins.
Thus the great objective for man,
while he lies in the darkness (for when he is translated into light this will be
easy) is to distinguish the movings and stirrings of the Spirit of God.
And here is the best way for a man in this state to know the movings of the Spirit:
that which uncovers and exposes the evil, _that_ is good.
That which uncovers what is spiritually evil, _that_ must of necessity be spiritually good.
Or, that which discovers what is undoubtedly pure, and inclines the heart to it,
_that_ must be of God.
And to know this, and be joined unto it, is a joining of the creature unto God.
This is a true beginning of life eternal.

[.numbered]
__7.  The way that the Spirit of God convinces of sin
is by his light shining in the conscience^
footnote:[It is important to note that it is not the conscience _itself_ that is,
or that possesses, divine light (as many falsely assume).
Rather, it is Christ the Light _in the conscience_ that brings man to the
knowledge of the truth and, when obeyed, to the salvation of the soul.]
or inner man.__

Fallen man is darkness.
The light shines in the darkness and shows man
the evil which otherwise would lie hidden in him.
Man fell from God, lost the image of God, and became wholly darkness.
But the Spirit of God is light, and shines in the darkness,
and strives with man to reduce him back again to that light from which he fell.
"`God, who commanded the light to shine out of darkness, has shined in our hearts,
to give the light of the knowledge of the glory of God,`" etc. 2 Cor. 4:6.
Where did the apostles and Christians in those days
meet with the light of the knowledge of the glory of God in Christ?
God shined in their hearts.
He that made the light to shine out of the deep darkness by his Spirit, Gen. 1:2,
by the same Spirit he made the light of the knowledge of life shine in their dark hearts.
And there it is also that the work of conviction is wrought by the same Spirit.
He that perfects the good work in the heart, the same is he that begins it there.
This beginning is by reproving and convincing of sin so
that man can turn his heart from it unto God,
and unto an obedience to the righteousness which God makes manifest.

Now, he that does not meet with the Spirit in the beginning of his work,
or slinks back, and does not go on with him, but rather smothers his reproofs,
will never meet with him in the end.
And then it will be too late for him to blame
that religion wherein there was only a dead form,
and not the living power of God.
He that will come to life eternal must be translated out of his dead understanding,
and all his dead ways and worships, into a living seed, and remain in that seed.
Then he shall know life indeed, and the true food of that life,
and the true worship and service out from that life, and the reward belonging to all.

[.numbered]
__8. That this light which convinces of sin, shines in every conscience.__

"`He has showed you, O man, what is good.`" Micah. 6:8.
"`The life,`" which was in Christ, was "`the light of men.`" John 1:4.
Christ is "`the light of the world.`" John 8:12.
God, as he loved the world,
so he manifested his love to the world by sending his light into it,
to "`enlighten every man that comes into the world,`" John 1:9,
that with the light they may see his Son.
And as many as receive him, to these he gives power to become the sons of God.
God desires "`all men to be saved,
and come to the knowledge of the truth;`" so he has given that light to all,
which may lead them to the knowledge of the truth which saves.
"`The grace of God, which brings salvation, has appeared unto all men.`"
Titus 2:11.

As the enemy got possession of every man`'s heart by filling it with darkness,
so Christ pursues and seeks to dispossess the enemy by
the light that he sends after him into every man.
And this is the condemnation of man:
not that he lacks a light to witness against and draw him out from the enemy,
but that he loves the enemy, and chooses to be one with the enemy, hating the light,
and turning from it. John 3:19-20.
Man hearkens to the reasonings of his mind against the light,
and so smothers and chokes it.
He does not turn to the light to have all the reasonings of his mind subdued by it,
and subjected to it.

[.numbered]
__9. The true way to life eternal is by believing in the light of the Spirit, which shines in the conscience.__

Man is in darkness, which keeps him in death;
and there is no way to come out of the death except by coming out of the darkness.
And there is no way to come out of the darkness
but by following the light which exposes it,
and calls out from it.
The one that follows that light cannot remain in the darkness, but will surely come out.

There is an evil seed in man, calling for evil;
and there is a good seed calling out from the evil unto the good.
Now he that follows the good, cannot follow the evil, but departs from it.
"`I am the light of the world (says Christ);
he that follows me shall not walk in darkness,
but shall have the light of life.`" John 8:12.
But man`'s ruin is found in this; that he loves the darkness,
he loves the world, the course of the world, the worships of the world.
He loves his own understanding and his own will,
and so he hates that light which crosses and contradicts these,
and which would teach him, by the denial of them,
to crucify that nature from whence they spring.

It therefore comes to pass (because the love of sin is strong, and Satan,
the strong man, keeps the house) that the motions of God`'s Spirit are easily trampled,
either by reasonings of the understanding, or by perverseness of the will.
But if any man dare entrust himself to the motions of God`'s Spirit,
he would quickly find of what nature they were by the
strong opposition of the strong man against them.
It is indeed a straight and narrow way into which no flesh can enter and walk.
And yet it is the only way: for there is no life in God, no peace with God,
while the enemy lives in the heart.
But when the light is received and turned to, then the power begins to work,
which slays the enemy in the heart; and that being done, there is no more war,
but  peace.
Then the true peace, which passes understanding, fills and refreshes the heart.

[.numbered]
__10. That believing in the light of the Spirit, which shines in the conscience, unites the soul to God, and opens the springs of life to it.__

Belief in darkness (which is unbelief towards God) disunited the soul from God,
and closed up the springs of life from it.
Belief in the light, which is sent to lead out from the darkness, unites again,
and opens the springs again.
God is light; he dwells in the light, and there enjoys the fullness of life.
He gives a measure of his own light to draw out from the darkness;
and he who believes and follows this is led by it unto God, from whom it came.
Now, having come out of the darkness unto God,
the soul begins again to feel the springs of life,
the fresh springs of life which are in him.
He that believes is come to the well of salvation, and draws living water out of it,
and drinks of the living water continually, so that he can thirst no more.
Indeed, "`out of his belly flow rivers of living water.`"
This is the fruit of the true faith.
This is the true way, the narrow way, (I can, in the presence of the living God,
set my seal to the truth of it) which it has pleased God to uncover,
and make manifest again, after the long dark night of apostasy.
And we come not to it by hearing or receiving new notions or apprehensions of things,
but by experiencing that which puts an end to all creaturely notions and apprehensions;
and we grow in it by the increase of that thing in us.
That is to say, the seed to which the promise was made,
the seed which was before Abraham, is felt and known,
and his day is seen and rejoiced in.
And by the light thereof the darkness is discovered,
and the kingdom of darkness is assaulted.

=== Some Objections and Answers

[.discourse-part]
__Objection 1. This is a new way, a new light.
We knew religion before this came up, and we will keep to that.__

[.discourse-part]
Answer:
It is new indeed to them who have lain long in the apostasy and set up another light.
But it is not new in itself, but is the same that was in the beginning; yes,
even before the beginning.
Christ was the same yesterday, today, and forever;
and the light that comes from him is like him, also being the same yesterday, today,
and forever.
It was the same light under the law, the same before the law, the same since the law.

"`That which was from the beginning,`" said the apostle John,
"`we declare unto you.`" 1 John 1:1.
And "`this is the message which we have heard of him, and declare unto you,
that God is light, and in him is no darkness at all.`" verse 5.
And the goal of preaching this message
is to draw out of the darkness into the light;
to bring men to the experiencing of the light of God in them, and so to union with it.
God, who is light, is close to every man, who is darkness,
even though man`'s senses are very thick and can hardly see or feel him.
A light from God shines in man`'s darkness; but man`'s darkness does not comprehend it.
Therefore, this light is not new in itself, but only new to the old spirit,
which has long lain hid in the region of darkness and death,
and has not known the light of life.

[.discourse-part]
__Objection 2. That this is a natural light, or the light of old Adam`'s nature and conscience.__

[.discourse-part]
Answer: It is in one sense a natural light;
it is of the nature of him from whom it comes; the nature of God, and of his Christ.
But it is not of the nature of corrupt Adam, whom this light has always reproved,
and against whom it still stands a witness, condemning all corruption.
Man is darkness; Eph. 5:8 and when Christ comes to redeem him,
he finds him to be in darkness.
Christ finds no light in man to help him uncover sin,
so all the discoveries of sin that are made in the heart are by the light of Christ,
and not by any light of man`'s nature.
The Lord is the searcher of the heart, and he searches it with his own candle,
and not with any light left in man`'s nature.
Man fell into darkness, and knew not where he was;
but the Lord comes after him with his candle, and manifests his state to him.
It is the light from which man fell, and against which he sins,
that alone is able to make his disobedience manifest to him.

"`We know`" says the apostle, "`that the law is spiritual; but I am carnal.`"
Rom. 7:14. The law is the lowest appearance of the light; and yet it is spiritual,
and of Christ`'s nature, and not of Adam`'s nature.
Whoever knows the nature of that which manifests sin, knows it to be spiritual.
It is the fallen man who calls the light darkness.
Man has set up a light of his own; has raised up a light by his study and invention,
in the strength of the fallen wisdom.
And now, setting this up for his light, he is bound to call the true light darkness,
as the Pharisees did Christ.

[.discourse-part]
__Objection 3. That this light makes the Scriptures void and useless.__

[.discourse-part]
Answer:  Not so.
The light came from the Spirit that gave forth the Scriptures;
it is of the same nature with the light that shone in them that gave forth Scriptures.
It speaks the same thing as Scriptures, it leads to the same thing,
and it opens and witnesses to the words which the Scriptures speak.
Therefore, the light brings the Scriptures
(which have long been abused) into their true use.
Indeed it puts an end to the corrupt use of Scriptures,
and to man`'s inventing and forming things out of them,
and brings them into their true use and service.
It takes the Scriptures out of man`'s hand, who has slain the life by his use of them.
It puts the Scriptures into the hands of the Spirit,
who makes the words again pure and quick and living;
purging away man`'s defiled and dead conceivings and interpretations of them.

A man must know the Spirit, come to the Spirit, be joined to,
and be in union with the Spirit,
before he can have the true understanding of the Scriptures.
The Scriptures indeed are the words of God, or various expressions of his mind.
Now the man who searches these before he has the Spirit cannot know the truth,
but can only guess and imagine.
And it is from here that so many sects and denominations are sprung up in the world,
according to the variety of their imaginations.
One sort of men cry, '`This is the way, this is the truth, this is the church,
this is the worship.`'
Another sort cry, '`That is not it; that is superstition and error;
but this is it!`' And so a third and fourth, etc.
It is the same with the Scriptures.
One says this is the meaning; another says it is not so, but this is the meaning.
They let their own reasonings and imaginations loose,
and there is no foundation of certainty.
But if they had waited for the Spirit to begin with,
and gone on no further than he opened to them,
all these doubts and dissensions would have been choked.

I do not altogether deny the reading of Scriptures,
even in this state of blindness and uncertainty,
so long as a man read with fear and trembling: not setting up his own understanding,
or the understanding of any man; but waiting for the Spirit,
which can alone give him an understanding to receive the true knowledge.
But this I dare boldly affirm,
that man`'s reading of the Scriptures in his own wisdom and self-confidence (or in
confidence in what interpretations others have given) does him no good at all,
but rather much harm, tending to the building up of that which God would again destroy.

He that begins with the Spirit of God,
giving himself up to the light which comes from him, comes to true union with God,
and to the experience of the life.
This one finds a true growth and knowledge of the Spirit of God,
whereby he comes to know and understand the Scriptures, which came from the same Spirit.
In this way he also comes to be able to measure the deceit of his own spirit,
which formerly led him astray, and also to see and measure the spirits of deceivers.
But he that is in the deceit, in the imaginations, outside of the true knowledge,
he cannot know the deceit of his own spirit, or the spirits of deceivers.

[.discourse-part]
__Objection 4. That this light teaches things contrary to the Scriptures.__

[.discourse-part]
Answer:
The light which comes from the same Spirit which the Scriptures came
from cannot teach things contrary to the Scriptures.
But man, who has taken the tools of his understanding,
and formed images and likenesses out of the
Scriptures (I mean invented meanings and senses,
and judged these to be agreeable to the Scriptures),
he will of necessity judge that which is contrary to
his meanings as contrary to the Scriptures.
The truth, however, is one in itself, and it agrees with whatsoever is true in this age,
or in former ages; and differs only from that which is not true.

[.discourse-part]
__Objection 5. That this sets up free-will.
When persons are exhorted to embrace the light, to let in the light, then they cry out,
'`Is it up to man to believe?
Is it up to man to receive the light?
Does man have free-will?`'__

[.discourse-part]
Answer: As for your speaking of free-will, you do not know what you speak of.
For the will, with the freedom of it,
either stands in the image and power of him that made it,
or in a contrary image and power.
While it is in the image and power of him that made it,
it is free unto good, and not to evil.
While it is in the image and power of him who corrupted it,
it is free unto evil, and not to good.
The will is not of itself, but stands in another,
and is servant to that in whom it stands,
and there its freedom is bound and comprehended.
For there is no middle state between the two, wherein the will stands of itself,
and is free to both equally.
The will of man is a servant, and under the command of one of these powers.
If it be under the command of sin, of the power of darkness,
it is free from righteousness.
And if it be under the command and power of righteousness, it is free from sin.
But such a free-will as men commonly speak of is mere imagination,
and has no foundation in the true state of things.

=== Three Things, By Way of Advice

And now you who find your hearts touched and convinced of the truth,
and find a desire kindled in you after the living God,
and a hungering and thirsting after his righteousness, take notice of these three things,
which I have upon my heart to say to you, by way of advice:

[.numbered]
__1.  Know and take up your cross, the cross of Christ, the daily cross of Christ.__

The cross of Christ is that which runs contrary to the natural;
and this is the power of God to deliver from the natural.
How should the earthly understanding, the earthly will, the earthly affections,
with the elementary nature (which have had their
reign in the earth) be crucified and slain,
except by the cross of Christ?
The one seeking a religion to please himself in anything, must not come here.
And the one, after coming to the cross, who then seeks anything pleasing to the earthly,
will deny and turn from the cross, and so go backward and not forward.
It is no wonder that there is such an enmity in all men against the truth;
for it strikes at their life, yes, at the very root of their life.

If this were any new way or form of religion held forth,
then man`'s understandings and affections might by degrees be made fit for it,
and find pleasure in it.
But the cross is a direct death to that nature and
spirit that has lived in any form of religion,
and to the whole course of that nature and spirit.
Nevertheless, through this death the true life springs up,
in those who receive its strokes.
Therefore be willing, and learn to die daily,
bringing everything which is contrary to Christ to the cross.
Deny self in everything, take up the cross in everything, follow Christ in everything.
This is the way by which Christ himself prescribed to become his disciples:
"`If any man will come after me, let him deny himself, take up his cross daily,
and follow me.`"
Seek not ease in the flesh, no, not in the least; but take up the cross every day,
in everything, till the earthly be slain;
until the wisdom and strength of the flesh be wholly subdued,
and then the wisdom and power of God will become natural.

[.numbered]
__2.  Keep to the sense, feeling, and experience,
and beware of the understanding, the imagining and conceiving mind.
The mind cannot be useful to God, nor bring forth anything for God,
until it be newly cast, and newly molded.__

The one seed of life lies in the invisible inner man of the heart,
among multitudes of seeds of death; all of which have their growth up into,
and strength in, the corrupted natural part.
Therefore, this seed of life cannot shoot up into any part of the
creature without the other seeds shooting up with it,
and endeavoring to choke it.
Now the other seeds spring up in two ways:
either in a way of opposition against the true seed, or in a way of similitude.
There cannot be a good thought, or desire,
or beam of light that enters into the understanding or will,
without multitudes of evil thoughts, evil desires, or fleshly reasonings against it,
springing up with it, and striving to overcome it.
But if, after such an assault,
the enemy is at length overcome (by the power of God fighting with
him and vanquishing him) then he also can put on his garment of light.
Then he brings in thoughts and desires, and motions which appear to be like God`'s,
and which easily pass for good, if the soul does not keep a close watch.

Now the only way of safety is to keep out of the natural,
whereof the enemy has possession, and where his strength lies,
and to keep in the sense and feeling of the invisible seed,
and only to come forth with him into the natural, in that sense and feeling.
And when he comes, he will come with strength,
above the strength that the enemy has in the natural, and by degrees conquer him.
But by no means rest or abide in the natural,
but retire with the Lord into the resting-place.
These words may be hard to you at present;
but hereafter (as you come into the exercise) you will experience them.

[.numbered]
__3.  Wait patiently for the Lord.
Be not hasty after life and salvation in the will of the flesh;
but leave the Lord to choose his own season for
the showering down of his mercy and blessing.__

The soul must know and feel that it has been an evil thing and bitter,
that it has forsaken the Lord, the living fountain of living mercies,
and has sought life from vanities, and among dead idols.
And all the idols must be thrown away,
and the heart washed from that nature that ran after them,
and become a pure virgin to bear and bring forth the living seed.
Now, by faithfulness to that seed, and waiting in that seed,
in the Lord`'s season it shall receive the mercy and the
blessing and the inheritance which belong to that seed.
The farmer does not immediately reap, but waits long,
even till the seed is grown up to maturity.
Therefore lie still,
and bear the indignation of the Lord against that which has transgressed,
till he judge it, and deliver from it, and lead into the innocency and righteousness.
And think not the race long, nor the battle hard,
nor be weary of the afflictions and chastisements in the way.
Follow the Captain, the Guide, the Leader; whose light, strength, courage,
and wisdom will overcome all, and bring the soul which abides in it into his own throne.

Now as you thus wait, taking up the cross,
and keeping in the feeling of the seed; so the corrupt nature, the mortal,
wherein Satan`'s throne and power has been, will wither, decay, and grow weak daily.
And the tender plant of God, the immortal seed, will shoot up, and gather strength daily;
and you will come to a new will in God, and a new understanding in God.
And that which is of God will manifest itself; and you will come to know, and desire,
and take delight in the things of God.
Then the soul, which is immortal, will come to hear, and receive,
and feed on the immortal word, which is the bread of life,
and which alone is able to preserve and nourish up to eternal life.
Then you will know what it is to tremble at this word,
and to have all the powers of nature melt and fail before it.
Then you will know the faith which gives the victory,
and the knowledge which lets into life, and the fear which keeps the heart clean,
and the hope which anchors the soul immortal in the immortal God,
and the patience which wins the crown.
And so you will come to witness the several conditions
of the saints in Scripture as you grow up into them.
You will not need men to give you their meanings of Scriptures
from their brain-studies and acquired arts and understandings;
but you will know the meaning from the thing itself in your own hearts.
You will hear the words from the living voice of
the Spirit that first spoke the Scriptures,
who alone is able to interpret his own mind, and open the words which he himself spoke.
Then you will know and love the true life,
and need no more exhortations to depart from all dead, corrupted, and corrupting forms,
which have forever been, and will forever be, enemies to the life.
And so the peace of God, the rest of God, the true Sabbath of God,
the everlasting light and life of God, will come to be your own, and be enjoyed by you,
past all doubting or disputing.
