== Chapter IV. The Axe Laid to the Root / Of the Old Corrupt Tree

=== Preface

There was a glorious day,
and a bright appearance of Truth in the times of the apostles.
They had the true Comforter, who led them into all Truth, and kept them alive in Truth,
and Truth alive in them.
By this Spirit, they, as living stones, were built up a spiritual house,
founded upon Zion, the holy mount; into Jerusalem, the holy city,
which is the church of the living God, the pillar and ground of Truth.
And here they had their citizenship in heaven, with God, the judge of all; with Christ,
the Mediator; and with the spirits of just men and the holy angels,
which always behold the face of God.
They lived in the Spirit, they walked in the Spirit, they prayed in the Spirit,
they sung in the Spirit, they worshiped in the Spirit,
and in the Truth which made them free.
They had God dwelling in them, and Christ walking in the midst of them; and,
by the presence and power of his life in them, were truly dead unto sin,
and alive unto God.
They did not strive against sin with man's legal spirit, but by the power of grace,
which made them more than conquerors through him that loved them.
This was part of the glory of that early state, in the day of the sunshine of the gospel.

But, behold!
A thick night of darkness overspread the beauty of this!
Some false brethren went out from the true church into the world,
and getting the sheep's clothing, and making a great outward appearance,
they drew the world after them; yes, even some from among the true churches.
(How hard was the apostle Paul obliged to plead with
the Corinthians about his own apostleship and doctrine,
that he might preserve that church from the false apostles!)
And when they had gathered a sufficient following in the world,
they gained ground against the true sheep and lambs of Christ, fought with them,
and overcame them.
And when they had overcome those that had the living testimony of Jesus,
and the true power and presence of the Spirit among them,
then they set up their own dead form, and cried out over all the nations of the earth,
saying: "`Revelation has ceased!
There is no looking now for such an infallible Spirit,
and such immediate teachings as the Christians had in the apostles' days,
who had the anointing to teach them all things.`"
So they pointed men to traditions, to the church,
as they called it (which title the harlot has controlled since the days of the apostles),
or to searchings of the Scripture, and reading expositions upon it, and religious works,
formed by the intellectual part in man to instruct the intellectual part.
Thus, the whole course of religion, and of the knowledge of God,
came to be outside of that Spirit and life wherein it first came forth (and
wherein it first stood). Christianity now consisted in doctrines of men,
and a form of worship and knowledge which the wisdom of man had constructed,
in an imitation of that which formerly stood in the life.

And now, men being gone from the life,
from the Spirit and his immediate teachings,
into an outward form of knowledge and worship of God in the wrong nature,
antichrist has risen up, and the dragon sits in the temple,
appearing there as if he were God, giving out public laws and ordinances of worship,
and requiring private duties and exercises of devotion.
Antichrist is obeyed and bowed down to in the observation of these things; but the true,
living God is not known, nor his secret, still voice,
which calls man out of these things heard;
because of the great noise which the dragon makes in his temple (for it is his now,
he having gained it, though it was formerly God's).

Yet it pleased the Lord, throughout all the night of this darkness,
to raise up some witnesses against the dragon and all his invented forms of worship.
These witnesses, however, were hunted, persecuted, knocked down,
and their testimony cried out against as error, heresy, schism, and blasphemy.
In this way,
the Roman Catholics cried out against the Protestants as heretics and schismatics,
who were witnesses against them;
and the Protestants cried out against the Non-conformists, Separatists, and Brownists,
who were witnesses against them.
And every sect cries out most against those who are led further from the darkness.
The form^
footnote:[Penington often uses the word _form_ to
express any physical or outward expression,
ceremony, structure, or system used in religion.]
always kills the life, which stirs underneath,
and which once made an appearance with some freshness.
But when the life (from which the form derived its seeming beauty and luster) dies,
then the form soon withers and dies also: so that the living seed being once slain,
there remains nothing but the dead spirit, feeding on the dead form.

Oh hasten out of this spirit!
Hasten out of Babylon!
For this is the great error of this age: man,
with an acquired knowledge from scriptural words, without the true faith and life,
goes about trying to evaluate that life and knowledge which comes from true faith;
and because it will not align with the apprehensions which he has taken into his mind,
he condemns it.
And thus, being in the earthly wisdom and observation (to which truth was never revealed,
but forever has been an offense) he stumbles at it, as did the Pharisees of old.

Listen therefore to my exhortation, you who love your souls;
come to that faith and church which is received, gathered, and defended by Christ,
the One Horn of Salvation.
Leave off your reasoning and disputing in that wisdom which has slain the life,
and come to that wisdom which springs from the life.
You will find more certainty and satisfaction in one touch of true life,
than in all the reasonings and disputes of wise men to the world's end.

The ground wherein man's religion grows (even the most zealous of men) is bad.
It is the same ground wherein the Pharisees' religion stood and grew.
This ground has brought forth such a kind of fruit; namely,
a conformity to the letter of Scripture which
stands in the understanding and will of man,
but it keeps far from the life, and from growing up in it.
But the true religion stands in receiving a seed of life; which, by its growth,
forms a vessel for itself.
And all the former part (wherein stood sin on the one hand,
or self-righteousness on the other), passes away.

=== The Faith of Man vs. the Faith Which is of God

There is a faith which is of a man's self;
and there is a faith which is the gift of God.
Or, there is a power of believing which is found in the nature of fallen man;
and a power of believing which is given from above.
As there are two births, the first and the second, so they each have their faith;
and each believes with his kind of faith.
Both claim to lay hold of the same thing for life;
and the contention about the inheritance will not be ended till God determines it.
Cain will sacrifice with his faith, and he believes he will be accepted;
if he had not believed so, he would not have been so angry when he found it otherwise.
And the Cainish spirit in man, the one cast out from the life of God,
which has not the eternal life of God abiding in him,
is busy with the same faith at this very day,
and has the same expectation from it as Cain had.

This is the root of the false religion; of the false hope; of the false peace;
of the false joy; of the false rest; of the false comfort; of the false assurance;
as the other is of the true.
In the faith which is of man, and in the improvement of it, stands all the knowledge,
zeal, devotion, and worship of the world in general,
and of the worldly part in every man in particular.
But the true knowledge, the true zeal, the true devotion, the true worship,
stand in the faith which is given of God, to those who are born of the immortal seed;
who live in God, and in whom God lives forever.

Now it deeply concerns every man to consider from
which of these kinds of faith his knowledge,
religion, and worship proceed, and in which of them they stand.
For if they proceed from, and stand in, the faith which is of man,
they cannot please God, nor be conducive to the salvation of the soul.
Even though they may taste very pleasantly to man's palate now,
and administer much hope and satisfaction to him at present,
yet they will fail at the time of need.
For, as Christ said concerning the righteousness of the Scribes and Pharisees,
so may I say concerning this faith--Except your faith exceeds that
faith which is found in man's nature (and all the works thereof),
it will never lead you to the kingdom of God,
nor grant you entrance into the inheritance of life.
For he that will inherit the promise, must be the right heir.
He must have the faith of Abraham, the faith of Isaac;
which springs up from the root of life in the seed;
and this leads the seed into that spring of life (out of which it
shot forth as a branch) which is the inheritance promised to the seed.
And here is Christ, Alpha and Omega,
in every particular soul where life is begun and perfected,
running its course through time, and back to that which was before the beginning.

Therefore observe, and consider well,
what this faith which is of man's self can do;
and how far it may go in the changing of man,
and in producing a conformity to the outward letter of Scripture.
And then also consider where man's faith is shut out, and what it _cannot_ do,
what change it cannot make, what it cannot conform to.
Thus a true distinction may be established in your mind,
and not a foundation laid for so great a mistake in a matter of such great importance.

[.numbered]
1+++.+++ A man may believe the history of the Scriptures; yes, and all the doctrines of them,
so far as he can reach them with his understanding, with this faith which is of man.
Reading a relation of the fall of man, of the recovery by Christ, of the way to life,
etc., man's faith can believe the relation of these things just as
well as it can believe the relation of other things.

[.numbered]
2+++.+++ This being believed from the relation of the history of these things,
this faith naturally sets all the powers of man at work (kindling the understanding,
will, and affections,) towards the avoiding of misery, and the attaining of happiness.
What would a man not do to avoid perpetual misery of soul and body forever,
and to obtain a crown of everlasting blessedness?
Such ideas stir up the affections, and set the understanding on work to the utmost,
to gather all the rules of Scripture,
and to practice all the duties and ordinances mentioned therein.
What can the Scriptures propose to be believed, that man will not believe?
What can it propose to be done, that he will not do?
Must he pray?
He will pray.
Must he hear?
He will hear.
Must he read?
He will read.
Must he meditate?
He will meditate.
Must he deny himself, and all his own righteousness and duties,
and hope only for salvation in the merits of Christ?
He will seem to do that too; and will say, when he has done all he can,
he is but an unprofitable servant.
Does the Scripture say he can do nothing without the Spirit?
He will acknowledge that too, and hope he has the Spirit.
God has promised the Spirit to them that ask it; and he has asked long, and asks still,
and therefore hopes he has it.
Thus man, by a natural faith, grows up and spreads into a great tree,
and is very confident and much pleased; not perceiving the defect in his root,
and what all this growth will come to.

[.numbered]
3+++.+++ This being done with much seriousness and vigor,
there will of necessity be a great change in man.
His understanding will be more and more enlightened;
his will more and more conformed to that to which he
gives himself and bends himself with all his strength.
His affections will be more and more weaned;
he will find a kind of life and growth in this (according to its kind).
Let a man's heart be in any kind of study or knowledge,
applying himself strictly to it, gathering understanding in his mind,
and warmth in his affection: so it is also here.

[.numbered]
4+++.+++ Now, how easy is it for a man to mistake here, and call this the truth!
First, he mistakes this for the true faith;
and then he errs in applying to this all that which belongs to the true faith.
Thus entering into the spirit of error at first,
he errs in the whole course of his religion, from the beginning to the end.
He sees a change made (by this natural faith) in him;
and this he accounts the true conversion and regeneration.
This leads him to ask, and seek, and pray; and this he accounts the true praying,
the true seeking, the true asking.
This cleanses (after its kind) his understanding, will, and affections;
and this he takes for the true sanctification.
And now this man feels safe!
He is a believer; he is a worshiper of God; he is a Christian;
he is an observer of the commands of Christ.
When the overflowing scourge comes, it will not touch him.
All the judgments, plagues, threatenings in the Scriptures, belong not to him,
but to the unbelievers!
But, the growth of this faith, and the spreading of it into all his knowledge, zeal,
and devotion, has not changed the nature of it all this while.
It remains the same that it was at the beginning,
_even a power of nature in the first birth._
And all these fruits are but the fruits of the first nature,
which is still alive underneath all.
And everything which stands on this false faith
can never kill the seed out of which it grows;
but rather feeds it more, and fattens it for the slaughter.

Thus far can man's faith go:
but then there is something that it is excluded from at the very first.
There is something that this faith cannot receive, believe, or enter into.
What is that?
It is the life, the power, the inward reality.
Though it may seem to have unity with all the Scriptures according to the letter;
yet it cannot have unity with one scripture according to the life:
for its nature is shut out of the nature of the things there described.

For instance: it may have a literal knowledge of Christ,
according as the Scripture speaks of him; of his birth, preaching, miracles, death,
resurrection, ascension, intercession.
Yes, but the actual thing spoken of it knows not.
The nature of Christ is hidden from that eye.
So it may have a literal knowledge of the blood of Christ, and of justification;
but the actual life of the blood it cannot feel; but can only talk of it,
according to what it reads in the Scripture.
So it may have a literal knowledge of sanctification;
but the thing that truly sanctifies, this it cannot receive into itself.
So it is for redemption, peace, joy, hope, love, etc.
It may get into the outward part of all these; but the inward part, the life,
the spirit of them, it is shut out of.
It cannot touch or come near;
nor can it witness that change which is felt and known here.

And here is the great contention in the world between these two births:
the one contending for its knowledge in the letter,
and the other contending for its knowledge in the life.
The one sets up its faith from the natural part, calling it spiritual; and the other,
which has felt the judgment of God upon man's
faith (and thereby come to know the difference),
sets up the faith of the true heir: which faith has a different source,
and a different growth from the other.
The faith that is from God will be welcomed into the land and kingdom of life.
The other will be manifested to be but the birth of the bond-woman,
and will be cast out with its mother to seek bread elsewhere.
For the seed of the bond-woman is not to share the inheritance with Isaac,
the seed of promise.

[.discourse-part]
Question: What then is that faith which is a gift of God?
And how is it distinct from the faith which is of man?

[.discourse-part]
Answer: It is that power of believing which springs out of the Seed of eternal life;
and leavens the heart, not with notions of knowledge, but with the powers of life.
In contrast, the faith which is of man is drawn out of man's nature,
by considerations which affect the natural part,
and it is kept alive by natural exercises of reading, hearing, praying, studying,
meditating, etc.
But the faith which is from God springs out of a seed of life given,
and it grows up in the life of that seed,
and feeds on nothing but the flesh and blood of Christ.
This faith, at its first entrance,
strikes that part dead in which the other faith did grow,
and by its growth perfects that death,
and raises up a life which is of another nature than
ever entered into the heart of man to conceive.
And by the death of this part in us, we come to know and enjoy true life.
And by the life we have received,
we come to see that which other men call life (and which we
ourselves were apt to call life formerly) to be but death.
And from this true knowledge,
we give a true testimony to the world of what we have seen and felt;
but no man receives our testimony.

It grieves us to the heart to see men set up a perishing thing as the way to life.
In tender love do we warn men of the pit into which they are generally running so fast;
though men reward us with hatred for our good will,
and become our bitter enemies because we tell them the truth.

Now be not rough and angry; but meekly read the following parable aright,
and it will open up into life.
The parable is just this: That which sold the birthright,
seeks after the birthright with tears and great pains; but will never recover it.
But there is that which lies dead, which has the promise,
which does not stir till he is raised by the power of the Father's life,
and then he wrestles with the Father, prevails, and gets the blessing from him.
Therefore, know the part in you that rises up first,
and is so busy in willing and running, and makes such a noise about duties,
and ordinances, and keeps down the life which it has slain.
Know also that seed of life which is the heir, which lies underneath all this,
and must remain slain while this first part lives.
But if ever you hear the voice of the Son of God, this seed will live, and the other die.
And happy forever will he be who knows this!
But misery will be his portion,
who cannot witness a thorough transformation by the almighty power of the living God,
but has only painted the old nature and sepulcher.
Misery will be the inheritance of those who never knew the old vessel broken,
and a new one formed,
which alone is able to receive and retain the new wine of the kingdom.
For the other vessel, like the Pharisees,
can only receive words about the kingdom written in the letter.

=== Some Assertions -- Concerning Faith, Its Nature, Rise, and Its Receiving of Christ.

[.alt]
==== Assertion I

That the true faith (the faith of the gospel, the faith of the elect,
the faith which saves the sinner from sin,
and makes him more than a conqueror over sin and the
powers of darkness) is a belief in the nature of God,
which gives entrance into, fixes in, and causes an abiding in that nature.

Unbelief enters into death, and abides in the death.
But faith is an engrafting into the vine, a partaking of the nature of the vine,
a sucking of the juice of life from the vine;
which nothing is able to do but the faith in the nature.
And nothing can believe in the nature, but that which is one with the nature.
So then, faith is not a believing the history of the Scripture,
or a believing and applying the promises,
or a believing that Christ died for sinners in general, or for me in particular;
for all this may be done by the unbelieving nature (like was seen in the Jews).

[.alt]
==== Assertion II

That the true faith springs from the
true knowledge of the nature of God in Christ.
He can never believe in the nature of God who
has not first the nature of God revealed to him.
If a man were to search the Scriptures all his days,
hear all that can be said by men concerning God, Christ, faith, justification, etc.,
be able to dispute about them,
and think he can prove his arguments against all the world; yet,
if he has not received the true knowledge of the nature of these things,
all his professed faith in them cannot be true.

[.alt]
==== Assertion III

That the true knowledge is only to be had by
the immediate revelation of Christ in the soul.
No man knows the Father but the Son, and he to whom the Son reveals him.
The dead will hear the voice of the Son of God, and they that hear will live.
There is no raising of a dead soul to life but by the immediate voice of Christ.
Outward preaching, reading the Scriptures, etc.,
may direct and encourage men to hearken after and wait for the voice,
but it is the immediate voice of Christ in the
soul which alone can quicken the soul to God.
Until the light of life shine immediately from Christ in the heart,
the true knowledge is never given. 2 Cor. 4:6.

Therefore,
they that have never heard the immediate voice of
Christ in the soul are still dead in their sins,
and have not yet received the true, living knowledge, but rather a dead,
literal knowledge, which gives a false shining of things in the dead part.
Indeed, the proper use of all means is to bring the soul to the immediate voice, life,
and power; and till this be done, till the soul come to that, to hear that, to feel that,
to be rooted there, there is nothing done that will stand.
But he that knows God comes into the immediate presence; and he that daily lives in God,
lives in the immediate life.
The true faith leads to this, giving the soul such a touch and taste of it at first,
as makes life unsatisfiable without it.

By this Christ excluded the Jews, with all their zeal and knowledge.
John 5:37-38. "`You have not heard his voice at any time, nor seen his form;
and you have not his word abiding in you.`"
There is a true hearing of the voice, seeing of the form,
and having the word of God abiding in the heart, that keeps the soul alive,
living in the life.
The voice gives life, the sight of the form daily conforms into the image,
which is beheld by the eye of life;
and the word abiding in the heart nourishes and feeds
the living soul with the pure bread of life.
But the Jews knew this not; but were exalting their sabbaths, the law of Moses,
the ordinances of Moses, the temple of God, the instituted worship of God,
and yet were shut out of the thing itself to which these things pointed.
And in the same way, many zealous ones at this day, not having come to this,
no more than the Jews did,
but sticking in the letter of the gospel (as the Jews did in the
letter of the law) stumble at the present dispensation of life,
and cannot do otherwise.

[.alt]
==== Assertion IV

That Christ's immediate revelation of the nature of his Father is unto babes.
Not to the wise, not to the zealous, not to the studious, not to the devout,
not to the rich in the knowledge of the Scriptures without: but to the weak, the foolish,
the poor, the lowly in heart.
Man does not receive these revelations by study, by reading, by willing, by running,
but by being formed in the will of life, by being begotten of the will of the Father,
and by coming forth in that will, lying still in that will, and growing up in that will.
Here the child receives the wisdom which is from above,
and daily learns the cross which crucifies the other wisdom and the other will,
which loves to feed on the shadowy and husky part of knowledge, without the life.

Therefore, if ever you desire to receive this knowledge from Christ,
you must come to discern that eye in you which must be blinded,
the eye to which Christ will never reveal the Father.

The true knowledge is only poured into the new vessel.
It is the living soul alone that receives the living
knowledge of the living God from Christ the life.
The old nature, the old understanding, is for death and destruction.
The wisdom of the flesh, though painted to look like spiritual wisdom,
is not to be spared anywhere; but that wisdom,
with all its zeal and growth and progress in religion must perish.
All men's knowledge of the Scriptures which they have
gathered in that dead part will profit them nothing,
but rather hinder them.
Every building which the leprosy of sin has overspread, is to be pulled down.

[.alt]
==== Assertion V

That this faith (which springs from the true knowledge) is God's gift,
and is not that power of believing which is to be found in man's nature.
It is of another nature, even the nature of the Giver.
And when man is called to believe,
he is not called to produce that faith wherewith he believes other things;
but to receive and exercise the gift of faith, which is from above.
That which is to be believed in is spiritual;
and that must be spiritual which believes in it.
Man, with all the powers of his nature, is shut out.
Let him believe and read and pray and hear and exercise himself in
that which he calls duties and ordinances ever so much;
for all these, set up in the wrong part in man, only feed the wrong part; and this,
with all its food and nourishment, falls short of the life.

Therefore the true entrance into life is to experience that power
which slays man's natural ability and propensity to believe,
that thereby the gift of the true faith may be received.
For there is no rising up and living of the second, without the death of the first,
with all its natural faculties and powers.

[.alt]
==== Assertion VI

That by this faith alone, which is the gift from above,
(and not that faith which grows in the garden of the old nature,
and is fed by the oldness of the letter and not
by the newness of the Spirit) is Christ received.
For Christ can be received by the faith alone that comes from him;
and that faith which comes from him cannot do otherwise than receive him.

Man's faith refuses him,
though it receives a literal knowledge of him from what it hears from men,
or reads in the Scripture concerning him.
It cannot be otherwise; for man's faith, not being of the nature of it,
cannot help but refuse it.
But the faith which is given of God, which is from above,
being of the same life and nature with Christ, cannot refuse the spring of its own life;
and so receives him immediately.
There is no distance of time; but just as soon as faith is received, Christ is received,
and the soul is united to him in the faith.
As unbelief immediately shuts him out, so faith lets him in immediately,
and centers the soul in him.
And the immortal soul feels the immortal virtue,
and rejoices in the true spring of its own immortal nature.

But the faith of man never reaches this, never receives Christ,
but receives only a description of things concerning him.
And with this faith which stands in the letter,^
footnote:[Whenever Penington speaks of _the letter,_
he is referring to the literal words of Scripture that testify
(and can only testify) of the true spiritual substance.
See Rom. 2:29-7:6, and 2 Cor. 3:6.]
the faith which stands in the life is opposed.
And here is the spirit of antichrist; here is the mystery of iniquity,
changing from one form into another.
For antichrist does not directly deny Christ, or deny the letter;
but rather applauds Christ, and commends the letter,
but in such a way that these may feed the faith of his own nature,
and maintain a hope there.
And thus the spirit of man is at unity with what will feed his own nature,
with what interpretations his own understanding can gather out of the Scriptures.
And thus can he venerate Christ, and say he hopes to be saved by him,
even while the spirit of enmity against the nature of Christ lodges in his heart.
This is antichrist, wherever he is found; and this is his faith,
and great is his knowledge, and many are his disguises.
Nevertheless, the Lord is searching him out, who will strip him,
and make his nakedness appear.

[.alt]
==== Assertion VII

That Christ is received as a grain of mustard seed, and that every eye,
except the eye of true faith, despises him.
He is the stone which the wisdom of the builders, in all ages, has rejected.
They look for a glorious Messiah; but they know him not in his humiliation,
in the little seed, out of which he is to grow up into his glory.
And so missing him entirely,
they build up the things concerning him with
only their high imaginations in the airy mind.

When God sent Christ in the flesh, there was neither majesty nor beauty in him.
Thus the Jews, whose hope and expectation lay there, saw no beauty,
no desirableness in him.
It is so even now.
When God comes to offer himself to those who claim to have their hopes in him,
they see no loveliness in him, but refuse him daily.
"`What?`" they say, "`this little thing, small, like a grain of mustard seed,
can this be the glorious Christ which the Scriptures have spoken so much of?
Why, we know the descent of this (its father, mother, and kindred are with us),
we find this in our own nature.`"
Thus, like the Jews of old, they make a great noise about Christ,
but refuse the thing itself, and this they do for a lack of the true eye of faith.
For if they had that eye, they would see the virtue in the little seed,
and receive him in his humiliation in their hearts, where he knocks daily for entrance.
They would not be content till this grain of mustard
seed grew up into a great and glorious tree.
But for lack of this eye, they keep him out, and let in the painted^
footnote:[Penington and his contemporaries frequently use the word
_paint_ or _painted_ to refer to a false covering or an outward
beautifying of something that is corrupt or carnal underneath.]
murderer, who dwells in them, and covers himself with a knowledge, a zeal, a faith,
and hope, etc., in the old nature, in the old vessel, in the old understanding.
Thus they give God and Christ good words,
while the evil spirit has their heart and dwells there, bringing forth his own old,
evil fruit under an appearance of devotion and holiness.

Hear now, you who are wise in the letter, but strangers to the life!
There is a twofold appearance of Christ in the heart.
There is an appearance of him as a servant to obey the law,
to fulfill the will of the Father in that body which the Father prepares there for him.
And there is an appearance of him in glory, to reign in the life and power of the Father.
He that knows not the first of these in his heart will never know the second there.
And he that knows not these inwardly, will never know any outward,
visible coming to his comfort.
For if Christ should come outwardly to reign (as many expect),
yet be sure he would not reign in you whose heart he
has not first entered into and subdued to himself;
which is only to be done by his appearance there, first as a servant, then as a king.

But what state are Christians (so called) now in,
who do not know the one in them who is able to serve God?
These are striving and fighting in that nature where sin has the power,
and which can never overcome, being not in union with, but strangers to,
that life and power which is the conqueror!
Therefore, let all consider in the depths of their hearts; for this is infallibly true:
they that never received the seed of life in their hearts, never received Christ.

[.alt]
==== Assertion VIII

That this seed being received within, grows up into its own form.
There it grows up into the body which is to serve the Lord.
Just as a seed cast into good earth, or the seed of man or beast sown in a fitting womb,
receives form and grows into a plant, or living creature,
so it is with Christ's seed in its land.

Now, this new creature, (or the Spirit of life in this creature,
which is in union with it) is the Christian's rule.^
footnote:[The word _rule_ is used throughout to refer to that which governs, rules,
or has authority in the life of the believer.]
Gal. 6:15-16. 1 John 2:27. Heb. 8:10,12.
Formerly, outward rules were given to the outward state, that is,
to men under the law who were not brought to the life,
but were exercised under shadows and representations of the life.
But the Son, who dwells within, who is the substance of all, who is the life,
who is one with the Father, he is not tied to any outward rule,
but is to live and walk in the immediate light of the Spirit of his own life.
And he that has the Son has this rule.
He that has not this rule has not the Son.
And he that has not the Son,
has not the true faith (which immediately receives him) and so is no Christian;
but has stolen the name from the letter,
having never received the nature from the Spirit, to which alone the name belongs.

[.alt]
==== Assertion IX

He that has Christ, or the seed of eternal life, which is Christ,
formed in him (which seed the Spirit always dwells in,
the same Spirit which gave forth the Scriptures),
he alone is capable of understanding those scriptures which that Spirit gave forth,
because the Spirit leads him into the understanding of them.
But he that has not received that seed which is like a grain of mustard seed,
and so has not Christ nor his Spirit (whatever he may pretend to), he,
by all his studies, arts, languages, reading of expositors, conferences,
or even experiences, can never come to the true knowledge of the Scriptures.
For such a man lacks the true key, which alone can open.
He may have collected a great many wrong keys, none of which can open.
But he lacks the true key of the true knowledge, and so is shut out of it,
and only let into such a kind of knowledge as the wrong key can open.

[.alt]
==== Assertion X

He that has received the new covenant into his heart,
with the laws of the life written there by the Spirit of life,
he understands that this living writing is his rule.
The Scriptures testify of where the covenant and law of life is written;
and if I desire to read it, there I must go.
I must go to where the Scriptures point me.
I must go to Christ the book of life, and read there with that eye which Christ gives.

The Scriptures are willing to surrender up their glory to Christ,
who was before them, and is above them, and will be after them.
But there is a false spirit,
which has seated itself in a literal knowledge of the Scriptures,
and has formed images and likenesses of truth from it (everyone after
the imaginations of his own heart). Now all of these images and
likenesses fall whenever Christ the life appears.
But this false spirit claims the Scriptures in a way of deceit,
just as the Jews claimed Moses.
It is a seducing spirit which rears up buildings and
forms of knowledge from the letter of the Scriptures,
and does not come to feel after, unite with, and live in, Christ the life.
And unless you come to this life, your reading of the Scripture is vain,
and all your gathered rules of practice, and comforts from promises, will end in vanity.
There is no possibility of knowing or receiving it,
but by experiencing the true touch of the inward life of it.
"`Wisdom is justified of her children:`" but they that
are not born of her cannot justify her womb or birth.

To the Jews, who were an outward people, there was an outward rule given,
a law of commandments, statutes, judgments, and ordinances,
proper to that state wherein they were.
But all this was to be done away and to end in that which all this represented.
So that to Christians, Christ the substance being come,
who is the end of all these shadows,
the true Jew being raised up into the immediate life,
now there is a necessity for the immediate life to be our rule.
To them under the gospel, to them who are come to the substance,
to them who are begotten and born in the life,
there can be no other rule proportionate to their state besides Christ the substance,
Christ the life.
Here he alone is the light, the way, the truth, the rule.
The Spirit is here the rule, the new creature is the rule, the new covenant the rule;
all which are in unity together, and he that has one of them has them all,
and he that has not them all has none of them.

Therefore,
written directions taken out of the Scripture cannot be
the rule to him who is the true Christian;
but rather the measure of grace, the measure of the light, the measure of the Spirit,
the measure of the gift received into the living soul from the spring of life,
this alone is the rule of life.
But Christians in the degeneration have lost this,
and so they have taken up words for a rule (which were not given for
that purpose). And so with deductions by the earthly mind,
they feed the earthly part.
What can be fed by men's Scripture knowledge except the earthly understanding?
Is not the earthly will stimulated, and are not the earthly affections warmed?
And when (as with Cain) such fruits are offered to God and rejected,
the earthly man becomes angry, seeing that God has raised up Abel, the younger brother,
who offers up the Lamb to God, and serves the living God in his own living Spirit,
and with the faith which comes from him.
Abel's religion stands not in that part wherein all other men's religion stands,
but in the death of that part; and in the raising up of another part,
wherein life springs.

=== A Necessary Warning

Hear and consider:  It is recorded, Rev. 22:18-19:

[quote.scripture]
____
"`If any man will add unto these things,
God will add unto him the plagues that are written in this book.
And if any man will take away from the words of the book of this prophecy,
God will take away his part out of the book of life, and out of the holy city,
and from the things which are written in this book.`"
____

Great are the plagues that are written in this book,
even the pouring out of eternal wrath without mixture; torment day and night,
in the presence of the Lamb, etc.
Great also is the life and blessedness that are promised to
those that fight with and overcome the mystery of iniquity.
Now, to face all the plagues mentioned here, and to miss all the blessedness promised,
would this not be a terribly sad state?
And the Lord says that this is what will befall
the one who adds to the things here spoken,
or diminishes from the words of this prophecy.
Therefore, in the fear of the one who has spoken this (and will surely make it good),
let everyone search and consider, _who is the adder, who is the diminisher._

Now consider,
is it not true that he who gives another meaning
to any scripture besides what is the true,
proper meaning thereof, this one both adds and diminishes?
He takes away the true sense, and adds a sense that is not true.
The Spirit of the Lord is the true expositor of Scriptures; he never adds nor diminishes.
But man, being without that Spirit, can only guess, imagine, study and invent a meaning,
and so he is ever adding or diminishing.
'This is the meaning,' says one.
'This is the meaning,' says another.
'No, this is the meaning,`" says a third and a fourth.
Another that is witty and learned declares them all to be correct.
Still another, perhaps more witty than he, says none are correct,
and invents a meaning different from them all.
Does this not plainly show that he who speaks in this way lacks the Spirit
of the Lord to open the Scripture to him and manifest the true meaning?
Is he not but working in the mystery of darkness?
And yet this very person, who is working with his own dark spirit in the dark,
will in words confess that there is no true understanding or
opening of Scripture except by the Spirit of God.
If this be so, how will you dare set your imagination, your fancy, reason,
or understanding upon this work,
and so be guessing at that which the Spirit has not opened to you?
Are you not, in this way, found to be adding and diminishing?

Now he that is the adder, he that is the diminisher,
cries out against the Spirit of the Lord.
He cannot possibly avoid this in the way that he is in;
for having first judged his own darkness to be light, then, in the next place,
he must necessarily judge the true light to be darkness.
He that has first set up his own invented
meaning of any scripture to be the true meaning,
he must of necessity oppose the true meaning, and call it false.
Thus man, having begun wrong in his knowledge of the Scriptures,
stands engaged to make use of them against the Lord, and against his own soul.
And yet, in himself, he thinks he makes a right use of them, that he serves the Lord,
and that he is not opposing his truth, but rather opposing error and heresy.
All the while, he himself is in the error, and in the heresy, and against the truth;
being a stranger to that Spirit, in whose immediate life and presence the truth grows.

[.discourse-part]
Question:
But how may I avoid adding to the things and diminishing from
the words of this prophecy and of other scriptures;
that I may not meet with the weight of this curse, or miss of the blessing?

[.discourse-part]
Answer: 1. Wait for the key of knowledge, which is God's free gift.
Do not go with a false key to the Scriptures of Truth; for it will not open them.
Man is too hasty to know the meaning of the Scriptures,
and to enter into the things of God,
and so he climbs up over the door with his own understanding.
He does not have the patience to wait to know the door,
and to receive the key which opens and shuts the door,
and so he gathers death out of words which came from life.
And this I dare positively affirm,
that all that have gone this way have only a dead knowledge;
and it is death in them that feeds upon this knowledge, and the life is not raised.

Consider now the weight of this counsel:
there is no opening of the Scriptures but by the true key,
nor is there any coming to the key till the Lord is pleased to give it.
What then is to be done,
but only to wait (in the silence of that part which would be
forward and running ahead) till the key be given.

[.numbered]
2+++.+++ Do not run in your own understanding, or in your own will,
to search out the meaning of Scripture;
for in this way you feed with the Scripture that which
it is the intent of all words of life to destroy.
But as you wait for the key at first,
so continually wait for the appearances and movings of the user of the key,
and he will shut out your understanding and will continually,
and let you into the life of both the prophecies and doctrines.

[.numbered]
3+++.+++ Do not graft any of the fruit of the tree of life upon the tree of knowledge;
for it will not grow there.
An appearance, or a likeness of the true fruit may grow there;
but the true fruit itself will not.
My meaning is, do not heap up a treasury of knowledge in the intellectual part,
which is to perish.
Rather, know the true treasury of all the things of life, which is in the life itself;
and in that understanding which is formed, kept, and lives in the life.
Set no manna aside to feed upon in the old store-house (lest the fleshly part
should be running there whenever its fleshly appetite is kindled after food);
but daily receive the continual bread from the hand of life.

[.numbered]
4+++.+++ There is a knowledge of things by the Spirit's opening the words which speak of them,
or by inward, immediate prophecies from the word of life in the heart.
This is an excellent knowledge, and not to be found in the earthly part of man.
This is very precious, and a much more full and certain knowledge than the other,
having the nature and immediate power of life in itself,
and so it is perfectly able to preserve.
Therefore, be not satisfied in opening of prophecies,
or true meanings of things (though this kind of knowledge is very excellent,
and has been very rare),
but wait to experience the thing itself which the words speak of,
and to be united by the living Spirit to that,
and then you will have a knowledge from the nature of the thing itself.
This is more deep and inward than all the knowledge
that can be had from words concerning the thing.

[.numbered]
5+++.+++ When you feel such things,
then seek their preservation in the spring of their own life.
Let the root support you, and all your knowledge,
with all that is freely given to you of God.
When you feel yourself leavened with the life, and become a branch shot out of the life,
then learn how to abide in the life, and to keep all that is given to you there.
Have nothing which you may call your own anymore, but be lost to yourself,
and found in him.
Know the land of the living, wherein all the things of life live,
and can live nowhere else.

Now in all this, there is stability and security.
From the very first opening of the true key, I begin to learn something of God;
and to learn it certainly, and to feel an assurance and establishment in it.
Here I begin to grow.
I grow up in the true learning, and in the true settlement.
I take none of the knowledge of the Scriptures from myself, from my own understanding,
from my own study and invention, or from the studies of other expositors,
but from the divine hand.
How can he twist Scripture who is kept single,
and has no desire to have anything to be the meaning of it,
but only what is the true meaning?
How can he fail to understand who waits to receive the true meaning,
not to feed the lustful, knowing part in himself, but to feed the life with it?
And when the life has no use for it, he is content to have it shut up,
and to be without it.
I say, how is it possible for this man to twist Scriptures?

But a man that has already received or invented a meaning,
this one goes to the Scripture and bends it, to make it conform to that.
And where it speaks contrary, he invents a way to make it comply,
and so wrests Scriptures forward and backward,
to make them speak agreeable to what he has already received and believed.
In this way every sort of person, Roman Catholics and Protestants,
bend the Scriptures to make them speak according to their opinions and practices;
not having known the true learning.
These are misled and unstable,
subject to be shaken by any wind of reason which is stronger than their own.
And such a wresting of Scripture is to their own destruction.

[.discourse-part]
Question:
Is not prayer a means by which one may avoid what is false and lay hold of the true?

[.discourse-part]
Answer: True; there is a prayer which is a means,
and there is a prayer which is not a means.
There is a prayer which is an ordinance, and there is a prayer which is an invention.
There is a prayer which is the breath of the true child,
and there is a prayer which is the breath of the fleshly part.
There is a prayer of the first birth, and there is a prayer of the second birth;
both of which cry and weep to God for the same thing.
Now the one of these is the true means, the other not.
One of them is Christ's ordinance, the other is antichrist's ordinance.
Now the question is, which of these is your prayer?
Is it your own breath, or God's breath?
Does it come from the renewing of the Spirit of life,
or from your own natural part painted?
For accordingly, it is either the true means, or the false means.
If it be the true means, it will have the Spirit, the life, the kingdom it prays for.
If it be the false means, it can never obtain it.

Catholics, they pray; Protestants, they pray; some in forms, some without forms;
some meditating beforehand, some not meditating.
Are all these the true means; or are any of them the true means?
The birth of the true child is the only true prayer;
and he prays only in the moving and in the leading of that Spirit that begat him.
And this is a prayer according to the will, in the life, and from the power of God.
But all men's prayers, according to times they set to themselves,
or according to desires in their own minds,
which they offer up to God with the nature and heart that sins against him,
these are false means.

Can you pray?
How did you learn to pray?
Were you taught from above?
Or did you gain the skill and ability by the exercise
and improvement of your own natural part?
Did you begin with sighs and groans,
staying there till the same Spirit who taught you to groan, taught you also to speak?
Were you ever able to distinguish the sighs and groans of the Spirit's begetting,
from the sighs and groans of your own natural and affectionate part?
And has that natural part, with all its sighings, groanings, desires, endeavors,
been thrust aside?
And has the seed immortal been raised by the Spirit of eternal life,
which teaches to cry and mourn, and at length to speak,
to the Father for the preservation and nourishment of his life?
If it has been thus with you, then you have known that prayer which is the true means.
But if otherwise, though you pray ever so long, and with ever so great affections,
and strong desires, this is all but the false means,
with its false warmth from the false fire.
This is but the means which the harlot spirit
(which is not in union with the life and power,
but keeps the seed in bondage) has set up instead of the true means.
And this can never lead to truth, but keeps alive God's enemy under a pleasant covering.
Neither is this the worship of the living God; but as it is from another spirit,
so it is to another spirit.
