== Chapter VI. Babylon the Great / The City of Confusion Where Antichrist Reigns

BABYLON:
this is the city which is built up and filled with
images and likenesses of the ways and truths of God,
but is without the life and power.
On her outside there is the likeness of a church, the likeness of a ministry,
the likeness of the ordinances, duties, and ways of holiness.
On her inside there is the likeness of good knowledge,
the likeness of repentance and conversion, the likeness of faith, and zeal, hope,
innocence, sanctification, etc.
But the actual substance, the truth, the virtue of all these things is lacking,
and she is found persecuting the very thing that she claims to be.

This is the woman that has bewitched the whole earth for many generations,
and is still changing her dresses and paints
that she might continue to bewitch the people,
and sit as a queen reigning over their consciences.
But blessed be the light which is arisen to uncover her,
and the power which is able to overthrow this
mighty city and all that take part with her.

The Lord God Omnipotent reigns in Zion;
and antichrist, with his city Babylon, falls.
Sing praises, sing praises, O inhabitant of Zion,
to him who subjects Babylon with all her glory under your feet.

=== Preface

There has been in me a zeal for God from my childhood,
and a most earnest search into the Scriptures (which my
soul deeply relished and my heart honored and loved,
and still does) for the revelation of the mind and will of God.
Two things did I earnestly search and beg for:
the one was for the discovery of the outward way of worship;
the other for the inward life, virtue, and power.
And I looked upon the outward as the proper means to lead me to the inward.

At the beginning of the troubles in these nations,
there was a lively stirring in me, and a hope that God was bringing forth something.
I felt this same stirring in many others,
and so my heart rejoiced and my soul was refreshed.
But the expectation I found to soon collapse and wither,
and I was forced to retire and to separate myself from that
where I found the life and power dying and decaying.
In my separation the Lord was with me; my soul remembers it well.
And he had regard to the simplicity, honesty, and integrity of my heart,
which he himself had kindled in me.
And though I fell too soon into a way of church-fellowship and ordinances,
yet he regarded me and pitied me, and refreshed my life even there.

But at length the outward forms overgrew us,
and the sweet and precious life in us began to die.
Then the Lord found out another way to refresh us (namely,
by a sensible relating of our conditions, and of God`'s dealings with us,
and workings in us), which was very sweet and precious at first;
but the enemy crept in there also.
And here it was that the hand of the Lord fell upon me, striking at my very root,
breaking my life asunder, and trampling my crown in the dust.
Then I became a man of sorrows (being stripped of all my life, faith, hope, joy, comfort,
in one day) not knowing which way to look, nor what to desire.
Sometimes there were breathings after God stirring in me, but they were quickly cut off.
Sometimes a taste of refreshment from a scripture was presented to me;
but then it was suddenly taken away, and my death and darkness thereby increased.
Then I did wish, Oh that I might appear before his throne!
For surely my conscience was clear in his sight,
and I had not wickedly departed from my God, but was broken in pieces by his hand,
even while my soul was earnestly seeking after him.
Oh how my soul did mourn,
seeing how I was fit to be made a prey to every
ravenous spirit!  Many did seek to devour me,
but the hand of the Lord was with me, preserving me, though I knew it not.
And though I was wholly broken and desolate of all that I had called,
or could call knowledge (for then I could not call anything either good or evil),
yet the Lord, by a secret instinct, preserved me exceedingly out of that which was evil,
and kept my heart secretly panting after the fountain and wellspring of good.

At length I was captivated by the world (through deep
despair of ever meeting with God any more in this life) and
betrayed by the love of it (which at last rose up in me,
and gained ground in me,
by persuading me that my present state and
condition did require the free use of the world,
and the enjoyment of all it could afford). Yet the Lord followed me,
and I was often visited with secret loathings of the world, and turnings from it,
and pantings after the spring of my life.
But I came to dread these longings after God,
for I feared the misery and unutterable anguish to which they had previously led me.

During this courting of the world and estrangement from the life,
the reasoning part in me (which the Lord had been long battering,
and had laid very low) gathered strength.
I began to grow wise again, or so I thought, and able to judge the things of God,
and to hope and wait for some great appearance.
But in this the enemy deeply deceived me, pleasing me with my sense of knowledge,
and keeping me hereby from unity with that which
alone was able to give me the sight of him,
whenever he should appear.
In this fleshly wisdom I judged and despised the true life in others as being weak, low,
and not able to bring them to that which I stood in need of, and waited for.
Yes, the more I considered and reasoned in my mind, and the more I conversed with them,^
footnote:[He is referring to the Society of Friends, who were in scorn called Quakers.]
the further off still I was.
Yet at length,
the Lord powerfully touched and raised up the life in me
(which by all these reasonings and consultations I had slain);
and then by degrees (waiting upon it) I saw, I felt, I tasted, I handled,
the living word.

Hereby my eyes have been opened,
and I have seen the bonds whereby I had been
held captive apart from the life all these days.
Indeed, many of the streets and buildings of Babylon have my eyes beheld.
Yes, I have heard the tongue of the false prophet,
who speaks so much like the true prophet that no
flesh can discern or distinguish between them.
Yes, I have seen the dragon in the temple,
being worshiped there by even the strictest professors, as though he were God.
And now, in tenderness and in the true light of life,
from the pure movings of the eternal Spirit,
I come forth to visit my poor fellow creatures and captives in Babylon.
What I have seen and known I testify of for the relief of others,
that they may escape that misery with which my poor soul has been overwhelmed,
and that they may come out of that filthy, abominable city which God is making desolate.

O Babylon, where the pure life, the conquering faith, the suffering love,
the purifying hope, the putting off of the body of sin,
the putting on the living garment, is not and cannot be known.
In Babylon men are only dreaming of these things,
and all the satisfaction they have is from the pleasure of their dream.
But when they awake they will find leanness, destitution, and nakedness upon their souls.

[.old-style]
=== A Description of Babylon / For the Sake of the Daughters of Zion / Who Presently Dwell in Her Midst.

Babylon is the spiritual fabric of iniquity;
the mystical great city of the great king of darkness.
It is built in imitation of Zion, painted just like Zion,
so that it be mistaken for Zion, and be worshiped there, instead of the true,
eternal God, and King of Zion.

This is the seat of the man of sin,
wherever he finds a dwelling place framed in any heart, or in any society of men.
Here he lodges, here he lives, here he sits as god, here he reigns, here he is worshiped,
here he is exalted above all that can truly be called God in that heart,
or in that society.

1+++.+++ Babylon is called a city.
This is a proper metaphor to uncover the mystery of iniquity.
It is just like a city, for in a city there are several streets, and in the streets,
houses, and in the houses, several rooms, to which families and persons belong.
So it is here; there are many streets in this city of Babylon,
many houses in every street, many rooms in every house;
and the houses and rooms have their several families and persons belonging to them.
These have their laws and governments, their knowledge of God and Christ, their order,
their worship,
their discipline in which they walk and by which
they order themselves in their several services,
places, offices, and employments, under the king of Babylon.

2+++.+++ It is a spiritual or mystical city.
It is not an outward building of earthly materials,
but an inward building of inward materials.
Just as the outward Zion, the outward Jerusalem, is passed away in its use and service,
so too the outward Babylon is out of date too.
(You need not look very far for it.) And even as God has built up an inward city,
a spiritual building; so has the king of darkness likewise.

3+++.+++ It is a great city, a city that overspreads the earth.
As spiritual Zion was a vast city,
a city that did overspread the nations (how did the faith of the gospel over-run
the world in the apostles`' days!) so this city has also over-run the world.
Indeed, it has taken up all the territories and dominions of the other city,
and now Zion has been laid in the dust and trodden under foot.
Indeed, she has deceived the nations, having Zion`'s dress, Zion`'s shape,
Zion`'s outward garment, but not Zion`'s spirit.

4+++.+++ It is a city of iniquity, of hidden iniquity.
That which is hidden in this city it is not the life, it is not the righteousness,
the holiness of the saints; but iniquity, sin, transgression of the life.
Look into any of the streets of Babylon, into any of the houses, any of the rooms,
any of the chambers of darkness; there is sin there.
And though it be washed and transformed in appearance ever so often outwardly,
yet still it remains inwardly polluted.

In this there is a great difference between the vessels of Zion,
and the vessels of Babylon.
The vessels of Zion, they are weak, earthen, foolish,
contemptible to the eye of man`'s wisdom; but the treasure,
the liquor of life within them, is precious.
The vessels of Babylon make a great show and appear very holy, very heavenly,
very zealous for God and Christ,
and for the setting up of his church and ordinances all over the world.
Thus they appear without; but they are sepulchers and there is rottenness within.
Under all this there lodges an unclean, an unsanctified heart;
a heart unsubdued to the spirit and power of the gospel,
even while it makes such a great show of subjection and obedience to the letter.

5+++.+++ It is the city of the king of darkness, the great king of darkness,
the prince of the power of the air, who rules universally in the darkness,
even in every heart.
Wherever there is sin, there is Satan`'s throne; and there he has his laws,
his government, his power, in every heart of his dominion.
And where there is the least subjection to him, he is still a prince,
and his building is not yet there wholly thrown down;
there he is not yet dispossessed and cast out.
As long as there is anything left wherein he may dwell, he knows his own,
and keeps hold of it.
It is his right, and he will not lose it.
All sin, all darkness, is properly his; it is his seat, and he has the government there.
_Man is the land where these two kings fight;_
and whatever is good and holy belongs to the one king,
and whatever is evil and unclean belongs to the other.
There is no communion or peace between them; but each keeps his own,
and gathers his own unto himself.
And where the fight has once begun between these two kings,
there is no quietness in that land till one of these be dispossessed.
But then there is either the false peace of Babylon,
most commonly under a form and guise of holiness; or there is the peace of Zion,
in the spirit, life, and power.

6+++.+++ This city was built (and is daily built) in imitation of Zion,
painted to look just like Zion.
The intent of its building was to diminish Zion, to suppress Zion,
to withdraw from the truth by a false image,
and to keep her inhabitants in peace and satisfaction,
under a belief and hope that it is the true Zion.

7+++.+++ The objective of all this, of Satan`'s building up this city,
this great city was, and is, that it might be taken for Zion,
and that he be worshiped there as God, and this without provoking jealousy or suspicion.

=== The Sins of Babylon

The sins of Babylon are related to these two heads: fornication and abomination.
She allures the spirit of man into a strange bed,
and there he acts filthily and abominably with this strange spirit.
Some of her acts are more open and manifest to all,
while some are more hidden and secret, hard (indeed, utterly impossible) to be discerned,
without the shining forth of the pure light of life.
For the great masterpiece of the harlot was to paint herself like the Lamb`'s wife,
and so to withdraw from the true church, and set up a false church.

Now the hidden sins of Babylon are the same nature as
the more open and gross sins;
the great difference is their secrecy, their not appearing like sins, their paint,
their color, whereby they are accepted as holy and good.
As for instance:

There is fornication (or adultery from the life) in the
finest or purest way of worship that man can invent or imitate.
Those that set up the harlot`'s church do not call it so, nor perhaps think it to be so.
Those that set up the harlot`'s ministry, or ordinances, do not give them that name,
but call them the ministry and ordinances of Christ:
yet this is as really and truly fornication from the
life as the grossest ways of heathenish worship.

If a man read the Scriptures and thrust himself
into any practices he finds there mentioned,
without the raising up of the living thing in him,
he has done this by the harlot`'s advice.
In this he is committing fornication, and erring from the life.
For the true worship lies in the spirit and in the truth,
and it is the new birth that God seeks to worship him.
But the spirit of man thrusts itself into these things,
and this the Lord abhors and rejects.
The spirit of man can never be cleansed in this way,
nor fitted to enter into Christ`'s bed;
but rather gets only a layer of paint from the Scriptures and
enters into the painted bed and bosom of the harlot,
where it remains unrenewed, unchanged, unmortified,
even while it professes great spiritual things.

And thus the Scripture,
the holy Scriptures of truth (which were given forth from the pure Spirit of life),
the harlot uses to draw away from the life.
And now every sort claims their own way and worship to
be the way and worship according to the Scriptures.
But the religion of the harlot, her worship, her profession, her practices,
do not reach to the purifying of the conscience,
but only to paint over the old sepulcher, where rottenness lodges within.
The heart was never thoroughly circumcised or baptized; the old man was never put off,
or the new man put on.
The blood of purifying (which truly washes away
the sin) was never felt in its virtue and power,
but only an apprehension and talk that they are cleansed in Christ,
from a notion they have stolen out of the Scriptures;
but not from the sensible experience of the thing in life and power in their consciences.
And so the evil nature still remains,
the evil heart of unbelief is still to be found in them, and they lack the life, power,
Spirit, love, humility, meekness, patience,
innocence and simplicity of the lamb and dove.

Now there are several sins which the Spirit of the Lord has charged Babylon with,
and for which he will reckon with her and with all that partake of her.
Some of these I will mention, such as:

1+++.+++ __Her deep fornications from the life,
under a pretense of honoring and worshiping it.__
She speaks fair words; she calls to have the worship of God set up, and a godly ministry,
and the ordinances of God in a nation; but it is not the true thing in the sight of God.
This was, and this is, the very way of antichrist`'s rising.
He gets into the outward form, he applauds the form;
and by use of the form (which he acknowledges and commends),
he eats away at the life and power.
This is the wolf in sheep`'s clothing, which,
by this fair appearance with the sheep`'s wool on his back,
hides his ravenous nature from the eyes of the beholders.

2+++.+++ __By inventing things which the Lord never com­manded,
or adding to that which the Lord did command.__
The mind of man is very busy, and full of inventions.
And whenever the heart is touched with devotion and zeal towards God,
the inventing part exceedingly exercises itself this way,
either in imagining and forming something that it thinks may be acceptable to God,
or in adding to those things which it finds commanded in Scripture.
In this kind of fornication the Catholic Church abounds,
being filled with ceremonies of their own inventing,
and additions to the things mentioned in the Scriptures.
But the common Protestants have been guilty of this as well.

3+++.+++ __By imitating those things which were commanded to others.__
When a man finds in Scripture the things which some others did,
or which others were commanded to do,
he takes upon himself to do the same thing before he knows the
leadings of that Spirit from whom such things proceeded.
Now in this he errs from the life; he goes without his guide,
he does that which was a good thing in others (who were led by the Spirit),
but in him it is fornication.
Such a man is a thief and an intruder.
He steals the outward knowledge and practice without the inward life and power.
He intrudes into where others have been led by the Spirit,
but comes not in by the right door.
He should have waited for the true entrance, and not run ahead by himself.

Into this kind of fornication the strictest
among the Protestants have often been ensnared.
These run on further and further to search out the purest way of worship,
the nearest pattern to the primitive times.
But they have applied themselves diligently to this not knowing the true guide,
nor waiting for him to give them entrance.
And now, thinking themselves to be in the right, they have contracted a lofty spirit,
holding forth their conceptions as the only way.
They are grown high, they are grown wise, they are become confident,
they know the way already,
and can maintain it by undeniable arguments (as they think). So the
Lord with his teachings remains at a great distance from them.

4+++.+++ __By continuing in practices into which they were once led by the Spirit,
without the immediate presence and life of the Spirit.__
For all true worship, the whole religion of the gospel, consists in following the Spirit,
in having the Spirit do all in us and for us.
Therefore, whatsoever a man does for himself is outside of the life,
and it is in the fornication.
Now this way of fornication have men especially fallen into who,
having been acquainted with true leadings and openings of the Spirit,
have afterwards run to these for refreshment,
and so by degrees forgotten the Spirit who formerly led them.

5+++.+++ __By speaking well of the ways of their own invention,
or the ways which they have imitated without the life.__
To call these the ways of God, the true ways of life, is blasphemy.
"`I know the blasphemy of them which say they are Jews, and are not,
but a synagogue of Satan.`"
Rev. 2:9. There were, even in the apostles`' days,
persons who pretended to be Christians, and pretended still to be of the church,
though they had lost the life; and this the Spirit of the Lord said was blasphemy.

6+++.+++ __By committing either manifest or more refined idolatries.__
"`Little children,`" said John, "`keep yourselves from idols.`" 1 John 5:21.
John saw anti-christianism breaking in rapidly,
many antichrists being already come; and now (says he) keep to the anointing,
and keep from idols.
Without watching carefully, without being mightily preserved by the anointing,
he saw idolatry would even creep in upon them who had
tasted of the true power and virtue of life.
But how shall they keep from idols who know not the anointing,
but rather think revelation has ceased?

Idolatry is the worshiping of God without his Spirit (this is the plain,
naked truth of the thing). To invent things from the carnal mind,
or to imitate things which others who had the Spirit did in the Spirit,
by the command of the Spirit, this is idolatry.
An invented or imitated church, ministry, or worship, without the life,
without the Spirit, these are the work of men`'s hands and are idols,
and all that is performed herein is idolatry.
Rev. 9:20. This is a religion without life, a worship without life.
For the living God, the Lord God of endless life and power,
is alone worshiped by his Spirit,
and in the truth of that life which he begets in the heart.
All other worship, however spiritual it may seem, is idolatrous.

This is a standing truth:
whatever is not of the Spirit of God in religion
and worship is of the spirit of antichrist.
Whatever the spirit of man has invented or imitated is not the thing itself,
is not the true worship.
For the true worship is only and continually in the Spirit and never out of the Spirit.
The true praying is in the Spirit; the true singing, in the Spirit; the true preaching,
in the Spirit: whatsoever is out of it is of antichrist in man.
Now therefore give up all your religion, your knowledge, your worship, your practices,
which are outside of the Spirit.
Return unto the Lord,
and wait for his raising of that seed in you which once began to spring,
but is now slain, and lies in death and captivity under all these.

Therefore, those who dwell in Babylon,
put away all your images and likenesses of truth.
Put away your false faith (which can never
overcome the worldly nature and spirit in you),
and your false hope (which can never purify your hearts), and your feigned humility,
and self-willed fasts (which can never bring down the lofty, exalted nature in you),
and your false love (wherewith you can never love the
brethren in the truth) and your false zeal,
meekness, holiness, etc.
For all of this springs and grows up from the wrong seed.
Put away all your praying, reading,
and preaching which you have taken up and do practice in your own wills,
which will should be crucified; and with which no service, worship,
or performance can be pleasing to God.
Wait for the raising of the true seed of life, in the true simplicity,
whereby you may serve God acceptably here, and be saved hereafter.
And be not mockers, lest your bonds be made strong;
for the destruction is determined against you by
that Spirit of life whose breath will waste you.
All flesh is grass, and the glory thereof is as the flower of the field!
Surely this people is grass,
and their zeal and profession of God is like the fading flower.
