== Chapter VII. The Holy Scriptures / Whether They Be the True Rule of Faith and Life

The greatest kind of knowledge is to know things by way of a unity with them,
even by experiencing a measure of their life made manifest within.
This we confess to be our way of understanding things,
and likewise of understanding the Scriptures, which speak of spiritual things.
Indeed, we have found this to be a far surer kind of knowledge; namely,
to understand the Scriptures by experiencing that of which they speak,
and not by guessing at things,
or by considering and scanning the words of Scripture with the earthly mind.

Now, concerning the holy Scriptures being a perfect rule of faith and life,
the new covenant is the covenant of the gospel; which is a living covenant,
a spiritual covenant, an inward covenant,
and so the law or rule of it cannot be written outwardly.
Read the tenor of the new covenant, Heb. 8:10. "`I will put my laws into their minds,
and write them in their hearts.`"
Notice: there is a manifest difference given between the new covenant and the old,
namely, that the laws of the one were written outwardly, in tablets of stone;
the laws of the other were to be written in the heart.
The heart is the book wherein the laws of the new covenant were promised to be written,
and there they must also be read.
So then,
he that will read and obey the laws of the covenant of life must look
for them in that book wherein God has promised to write them.
For though in other books a man may read some outward descriptions of the thing,
yet here alone can he read the thing itself.

"`Christ is the way, the truth, and the life.`"
What is a Christian's rule?
Is not the _way_ of God his rule?
Is not God's _truth_ his rule?
And is not the truth in Jesus, and only there to be taught and to be heard?
Eph. 4:21. Is not he the king, the priest, the prophet, the sacrifice,
the way to God, the life itself, the living path out of death; yes,
all in all to the believer whose eye is opened to behold him?
The Scriptures testify of Christ, but they are not Christ.
They also testify of truth, and indeed are a true testimony,
but the truth itself is in Jesus,
who by his living Spirit writes it in the heart which he has made alive.

Therefore a Christian's life is in the Spirit: "`If we live in the Spirit,
let us also walk in the Spirit.`"
Gal. 5:25. The whole life and course of a Christian is in the volume of that book,
as the Lord opens the pages of it in him.
"`The gift of God, the measure of faith`" given him by God, this is his rule;
this is his rule of knowledge, of prophesying, of obedience.
Heb. 12:2 Rom. 1:5. 12:6. If he keeps to this,
if he walks according to the proportion of this, he does not err.
But if he walk outside of the faith, then all that he knows, all that he believes,
and all that he does, is in error.
 
The new creature, (that which God has newly created in the heart,
which is taught by God,
and in which life breathes and nothing but life
breathes) this is the rule whereby man is to walk.
The apostle expressly says so,
Gal. 6:15-16. "`For in Christ Jesus neither
circumcision nor uncircumcision avails anything,
but a new creation.
And as many as walk according to this rule, peace and mercy be upon them,
and upon the Israel of God.`"

That which is begotten by God is a son; and this son,
as he is begotten by the breath of the Spirit,
is also preserved and led by the same breath.
Those who are led in this way are sons, and not any others.
For it is not reading of Scriptures and gathering rules
out from them that makes one a son,
but rather the receiving of the Spirit and being led by the Spirit.
Rom. 8:14. "`For as many as are led by the Spirit of God, these are sons of God.`"
And since the whole of worship in the gospel is in the Spirit,
there is a necessity of receiving that Spirit in the first place, and then,
in this Spirit, the soul learns to know and wait for its breathings and movings,
and follows on towards the Lord in them.
The Spirit will not stop breathing upon that which he has begotten;
and this breath is man's guide, man's rule, and man's way.

Now all this is most clearly manifest even from the Scriptures themselves,
for they expressly call Christ himself the way, the truth, the rule, the faith,
the grace, etc.,
and also show the heart to be that tablet upon which God has chosen to write his laws.
But where do the Scriptures call themselves a perfect rule of faith and obedience?
"`These are they (says Christ) which testify of me; and yet you will not come to me,
that you might have life.`" John 5:39-40.
Life cannot be received from the Scriptures,
but only from Christ who is the fountain and source of them.
In the same way, the Scriptures cannot give the true rule,
but rather point to the fountain of life where alone the rule of life can be received.
The Scriptures cannot ingraft the soul into Christ,
nor give a living rule to him that is ingrafted.
However,
he that has heard the testimony of the Scriptures concerning Christ and has come to him,
this one can abide in him and wait on him for the
writing of the law of the spirit of life in his heart.
_This_ will be his rule to bring him out from the
law of sin and death and into the land of life.

Now consider meekly and humbly whether the Scriptures
are the rule of the children of the new covenant.
For if the Scripture was not intended by God for the rule,
and you take it to be the rule, then you may easily mistake the way to eternal life,
and err also in your understanding and use of the Scriptures,
making such a use of them as they were never intended for,
and so missing of the true use and intent of them.

=== Three Arguments

The Scripture was indeed not intended, nor given forth by God,
to be the rule of the children of the new covenant.
Consider at present these three arguments:

1+++.+++ The Scripture is an outward rule or law;
but the Scripture expressly says that the law of the new covenant will be an inward law.
It is written in the prophets that all the children of the new
covenant (or New Jerusalem) shall be taught of the Lord,
Isa. 54:13. It is the Lord who teaches them inwardly by his Spirit,
and writes his law in their hearts, Jer. 31:33-34.
In this way the Lord took his people into covenant with himself,
and also taught them in the apostles' days. 1 John 2:27.
"`But the anointing which you have received from him abides in you,
and you do not need that anyone teach you;
but as the same anointing teaches you concerning all things, and is true,
and is not a lie, and just as it has taught you, you will abide in him.`"
The covenant is inward, the teacher inward, the writing inward, the law inward:
and there it is to be read, learned, and known, where the Spirit teaches and writes it.

2+++.+++ Scripture (or the writings of Moses and the prophets) was
not the law of the children of the new covenant.
The law of Moses was the rule of an outward state, it was the rule of the outward Israel,
but not the rule of the inward Israel.

Now, in Deut. 29,
Moses makes a covenant with Israel by express command from God,
besides the former covenant which he made with them at Sinai.
And he says the commandment of this covenant is
not to be looked for where the other was written,
but in another place, in a place nearer to them, even in their mouth and in their heart.
There they were to read, hear, and receive the commandment of this covenant.
"`For this commandment which I command you this day, it is not hidden from you,
neither is it far off,`" Duet. 30:11. "`It is not in heaven,`" ver. 12.
"`neither is it beyond the sea,`" ver. 13.
"`but the word is very nigh unto you, in your mouth, and in your heart,
that you may do it,`" ver. 14.
"`and this was the way of life then.`" ver. 15.
"`See (says Moses) I have set before you this day life and good, and death and evil.`"
Here your eternal happiness depends; obey this word, and live; disobey it, and die.
And if they had kept to this word,
they would also have walked in obedience to the written law; but neglecting this word,
they could never keep the law, but rather came under the curse of it,
and missed the blessings.
Israel thought to please God with sacrifices, and oil, and incense,
and observing new moons and sabbaths,
but the Lord still rejected them for lack of their obedience to this word.

The prophets also guided them to this word,
bidding them "`circumcise their hearts.`"
Even after much conflict between the Lord and them,
when the people seemed very desirous to please the Lord with what he should require,
whether "`burnt-offerings, calves, rams,
or oil,`" the prophet puts aside all of this and points them
to the obedience of this word as the way to please God,
and as the only thing that he required of them.
"`He has showed you, O man, what is good, and what the Lord requires of you,
but to do justly, and to love mercy, and to walk humbly with your God.`"
Micah. 6:8. All this is written in your heart, O man!
Read there, obey that word, this is the thing that God requires.

So too, David's law was the word written in his heart.
He saw through the sacrifices and burnt-offerings to the inward writing,
and this made him wiser than all his teachers, who were busied about the outward law.
The outward law was but a shadow of good things to come, and made nothing perfect.
But David knew a perfect law,
"`The law of the Lord is perfect, converting the soul.`" Ps. 19:7.

3+++.+++ The Scriptures of the New Testament never call themselves the rule,
but they call another thing the rule;
they call the writings of God's Spirit in the
hearts of his people the law of the new covenant, Heb. 8:10.
They call Christ "`the Way, the Truth, the Life.`" John 14:6.
(The way is the rule, the truth is the rule, the life is the rule).
They call the new creature the rule;
walking according to which the peace and mercy is received and enjoyed. Gal. 6:16.
They refer to the Comforter as the guide into all truth, John 16:13,
yes, as the compass of all truth wherein the believer
is to have his whole life and course. Gal. 5:25.
Live in the Spirit, walk in the Spirit, follow the Spirit;
keep within that compass and you cannot err.

A man may err in understanding and interpreting Scripture,
but he that has received the Spirit and knows the Spirit, follows the Spirit,
and keeps to the Spirit, so far as he does so he cannot possibly err.
So John, writing concerning seducers and warning against them, 1 John 2:27 says,
"`You have received an anointing, which teaches you all things.`"
Keep to the teachings of that in everything, and you are safe.
But can we not be deceived?
No, the anointing keeps from all the deceit in the heart,
and from all the deceits of seducers.
"`It is truth, and no lie,`" ver. 27,
and it leads into all truth and out of every lie;
and this will teach you to abide in him.
In whom?
In the Word which was from the beginning,
which is ingrafted into the heart of every believer,
and into which the heart of every believer is ingrafted.
The Word is truly in the vine,
and the sap of the vine runs through unto the believer and makes him fruitful to God.
He abides in the Word which he has heard from the beginning,
and the Word which was from the beginning abides in him, ver. 24.

The Apostle Paul expressly says that the righteousness
of faith comes by the hearing of this Word.
He makes this same Word the rule for the children of the new covenant now,
even as Moses said it was the commandment of God to them.
Paul shows, Rom. 10:6-8, that he indeed taught nothing but Moses and the prophets,
pointing to the very same Word and commandment of eternal life, as Moses had done.
"`This is the Word of faith which we preach.`"
The Word which Moses taught, which he said was close to you,
in the heart and in the mouth (no man need ascend up to heaven,  or go down to the deep,
or seek anywhere else for it), this is the very thing we point you to.
This is the Word of faith; this is the commandment of life.
And with what zeal would Paul (if he were now alive in the body) cry
out against those who should overlook or deny this Word,
but instead set up his writings, together with the writings of the rest of the apostles,
as the true rule!

Indeed, I could show yet further how the spirit of prophecy,
or testimony of Jesus, or the living appearance of God in the heart,
has been a rule to the witnesses against antichrist's deceit,
all throughout the long night of apostasy, Rev. 11:3. 19:10.

Now, consider whether the Scripture truly be your rule or no.
Do you, in singleness of heart, wait on the Lord to open the Scriptures by his Spirit,
and to keep out your carnal reason (which cannot understand them,
but will always be twisting them and making them speak according to
its desires)? Or do you search into them with that natural part which
has forever been shut out from the right knowledge of them?
"`The natural man understands not the things of the Spirit of God.`"
The Spirit of the Lord alone understands the meaning of his own words,
and he alone gives the understanding of them,
which he gives not to the wise searcher and disputer (nor to the prudent professor,
Matt. 11:25), but to the babe whom he begets.
To these he gives the kingdom and opens the words of the Scripture concerning the kingdom.
"`The wisdom of the flesh is enmity against God,`" and
if that fleshy wisdom searches into the Scriptures,
it will gather only a knowledge that is suitable to this enmity.
In this way the Jews were great enemies of Christ.
They opposed the true Word with a fleshy knowledge they had
gathered out of the Scriptures that God had given to them.
And this same spirit has also wound itself around the Scriptures written by the apostles.
For just as this spirit fought against Christ and his apostles using the Old
Testament Scriptures (which the Spirit of Christ had formerly written),
so the same spirit now fights against the lambs
of Christ  using the New Testament Scriptures.

Truly the great stronghold of antichrist at this day
is Scripture interpreted by the fleshly wisdom.
For antichrist comes not in a direct denial of Christ
or the Scriptures (he is too cunning to be found there),
but he bends them aside by the fleshly wisdom to serve the fleshly will.
In this way he undermines the Spirit,
and exalts the flesh with a fleshly understanding and interpretation of
those very Scriptures which were written by the Spirit against the flesh.
It is by this same error that some innocently praise those
things practiced at the first springing up of truth,
not seeing of what nature they were, and upon what account they were done,
and what of them were cast off by the same Spirit,
which before had led to the use of them, though Scripture expressly testifies thereof.

Many sorts of professors claim the Scriptures to be their rule,
but which of them is taught by the Spirit to keep the carnal part out of the Scriptures?
Which of them keeps out their own will and understanding,
receiving their knowledge of Scriptures only from that Spirit who wrote them?
Do not men instead gather a knowledge in the flesh,
and then grow strong and wise and able to dispute, and confident in their own way,
and become fierce despisers of those who cannot
acknowledge their interpretation of these scriptures?
Thus the mind of God, the true meaning of the Scriptures, is not their rule;
but an image which they have formed out of it.
They have a meaning which their wit has strongly imagined and fenced in with arguments,
but the real mind and intent of the Spirit is hid from them.
So by this means many both deceive their own souls,
and help to deceive the souls of others,
missing the plainness and simplicity of the Spirit,
and gathering notions in the wisdom and subtlety of the fleshly part,
where the serpentine wisdom lodges and winds around the tree of knowledge.
Now what are these men really doing?
Who do they really serve?
And to where do they run themselves,
and lead many other poor souls whom they pretend to save?
