[#ch8, short="The Authority and Government Christ Excluded"]
== Chapter VIII. The Authority and Government which Christ Excluded from His Church

[quote, , Matthew 20:25-28]
____
But Jesus called them to himself and said,
"`You know that the rulers of the Gentiles lord it over them,
and those who are great exercise authority over them.
Yet it shall not be so among you; but whoever desires to become great among you,
let him be your servant.
And whoever desires to be first among you,
let him be your slave--just as the Son of Man did not come to be served, but to serve,
and to give his life a ransom for many.`"
____

Here Christ cuts off that kind of power and authority
which grows up in the corrupt nature of man,
which was at times springing up even in the disciples.
Here he wholly excludes it out of the church,
and says expressly he would have no such thing among them; no such kind of greatness,
no such kind of authority.
Among the Gentiles there are great ones, there are princes; and these great ones,
these princes, they lord it over the inferior ones,
exercising authority and dominion over them; "`but it shall not be so among you.`"

The Gentile-state was a shadow, even as the Jews' state was a shadow.
The one of death, the other of life; the one of darkness, the other of light.
The one was the image of Satan, the prince of wickedness; the other of Christ,
the prince of righteousness and peace.
They were both veils, under which the two kingdoms were hid.

Now in the Gentile-state there were nations, princes, laws, governments,
dominions, authorities, etc., but they were all in the fall, all in darkness,
all in the transgression from the life of God.
The whole state was corrupt, and there must be no imitation made of it,
no likeness of any such thing in the kingdom of Christ.
In Christ's kingdom there is no such kind of law, no such kind of government,
no such kind of authority, no such kind of anger towards persons that transgress,
no such kind of dealings with any.
There is nothing to hurt in the mountain of God's holiness;
but there is a righteous scepter, a sweet scepter, a spiritual scepter,
which reaches the spirit of man in the power of life, but touches not the outward man.

Two things are here excluded by Christ,
and from these two arise all kinds of mischief in the church
(all the tyranny and oppression of men's consciences,
and of their persons, estates, and liberties, for conscience' sake): first,
personal greatness; secondly,
the exercising of dominion and authority by those desiring to be great in this way.

Such a kind of greatness as is in the world is
the destruction of the life of Christ.
Such a kind of dominion and authority as is among the nations
is the direct overturning of the kingdom of Christ.
It sets up another power than Christ's, another greatness than Christ's,
another kind of authority than Christ's;
and so it eats out the virtue and life of his kingdom,
making it just like one of the kingdoms of this world.

"`It shall not be so among you.`"
This spirit must be kept out from among you; this aspiring spirit, this lofty,
ruling spirit, which loves to be great, which loves to have dominion.
This spirit seeks to exalt itself because of the gift it has received,
and desires to bring others into subjection.
Thus it must be subdued among those who are Christ's disciples, or it will ruin all.

The Lord gives grace and knowledge,
but it is never given with the intention that men take it upon themselves to be great,
or rule over others because of it.
And he that, because of his gift, thinks himself fit to rule over men's consciences,
and to make them bow to what he knows or thinks to be truth,
will in this way lose his own life.
For it is not so much speaking true things that does good,
but speaking them out from what is pure, and conveying them unto what is pure,
for the life runs along from the vessel of life
in one into the vessel of life in another.
But the words, however true they may be, cannot convey life to another,
but only as the living vessel opens in the one, and is opened in the other.

[.discourse-part]
Question: But how shall this spirit be kept out, or kept down,
that it may not hurt the disciple in whom it arises?

[.discourse-part]
Answer: When this spirit begins to arise up in any, as soon as he perceives it,
he is to fight against it in the light that discovered it.
He is to lay himself so much the lower, to hearken to the cross,
and so to come down and subject himself in serving and
ministering to those who are little in his eyes.
Instead of reigning over them, let him lie beneath them.
Let him watch and know the seed of life in others, even in the smallest measure,
and serve it; for that is his place.
That which would rule is to serve; that which would be great is to be little;
and the little seed is to become a nation.
The seed which is low is to rise;
and you are not to rise with it further than you can serve it,
both in yourself and others.

Therefore if ever you are aspiring, if ever you have a mind to rule,
if ever you think yourself fit to teach because of what you have received, sink down,
lie low, take up the cross to that proud spirit, make it bend and serve!
Let the life in everyone rise over it, and trample upon it;
and afterwards something in you may arise which is fit to teach, yes,
and to rule in the Lord.
And so long as this has the dominion, you may be serviceable to the Lord,
and to his truth and people.
But if ever the other rises up again, you must presently come down again.

In this way, if a man be faithful to Christ, this evil, aspiring spirit,
may be dealt with at its first appearance, and kept down.
But if this spirit is admired and given way to,
then once it is let up it will be hard bringing it down afterwards.
Therefore, the disciples, or the church of Christ, are to watch over every such spirit,
to beat it down, to testify against it, to turn from it, to lay it flat,
to put it in its proper place, which is beneath all, to serve all,
and so not allow it to rise.
He that would be great, he that would rule, let him serve.

Christ urges this upon his disciples from his own pattern,
"`even as the Son of man came not to be served, but to serve`" ver. 28.
If any had right to be great, surely Christ.
If any had a right to exercise authority, surely it was Christ.
If any was to be advanced because of a gift received,
or because of the presence of the Spirit with him, surely Christ!
Yet Christ would not take upon him this kind of greatness,
nor did he exercise this kind of authority; but he was a servant.
He made use of the gift of the Spirit and the power of life received from the Father,
to minister and serve.
He never did lord it over the consciences of any of his disciples, but bore with them,
pitying them in their weaknesses.
("`What, can you not watch with me one hour? The Spirit,`" said he,
"`is willing, but the flesh is weak.`")
He did not hold out to them whatever
he knew to be truth and require them to believe it.
Rather, he was content with them in their state,
and waited till their capacities were enlarged,
being satisfied with the honesty and integrity of their
hearts in their present state of weakness.
Nor did Christ strive to reign over the world,
or call for fire from heaven when they would not receive him.
He did not express indignation when they desired him to depart out of their city,
or pray for twelve legions of angels when they came to betray him, seeking his life.
On the contrary,
the life he had received from his Father he gave up as a ransom for his disciples, yes,
and for his enemies.
Notice: Christ did not make use of what was given him to raise himself up above others,
to make his word stand for a law.
Rather, he waited till that was opened in his disciples, and in the people,
which was able to receive his testimony.
He made use of his power of life, and the fullness of the Spirit,
to enable him the more abundantly to serve,
and to wait in patience for the fulfilling of the will of the Father.
And though Israel was not willing to be gathered by him, yet was he meek, and patient,
and at rest in the will of him that sent him.
Instead of seeking to reign over all, he served all,
and gave that life (whose due it was to reign) "`a ransom for many`" ver. 28.

"`His kingdom was not of this world,`" nor did he seek
any greatness or authority according to this world,
neither over the Jews, nor over the Gentiles, nor over his own disciples;
but he served all, he sought the good of all.
The life in him, which was to reign over all, yet here served all, suffered for all,
and that was his way to his crown.
And now having finished his course, fulfilled his service, perfected his sufferings,
he has set down at the right hand of the majesty on high, where now he reigns over all,
and is made a king by God in righteousness.
This is the pattern by which all his disciples are to walk.
The more life they receive, the more they are to minister, the more they are to serve.
They must not lift up themselves by their gifts.
They must not lord them over others,
or hold forth their knowledge or doctrines and think to make others bow to these.
Rather, they are to wait in their service till the Lord makes way into men's hearts,
and plants his truth there;
and upon him they must also wait for the watering and growth of it.

=== The Authority and Subjection of the Spirit

[.discourse-part]
Question: But is there to be no greatness, no authority among the disciples of Jesus,
or in the church of Christ?
Is everyone to do what he will, to be subject to his own fancies and imaginations,
to the inventions of his own corrupt heart?
What a confused building will this be!
Surely this will not long remain a Zion, but soon become a Babylon,
even a heap of disorder and confusion.

[.discourse-part]
Answer: There is to be no greatness or authority of this _kind;_
yet there is indeed both a greatness and authority
suitable to the state of true disciples,
and to the kind of kingdom to which they belong.
There are laws, there are governments, there are governors, there is ruling,
and there is subjection: but all in the Spirit, and not according to flesh.
As Christ's kingdom is not of this world,
so the government of his church and people is not according to this world.
Just as that which gathers into his Spirit is spiritual,
and that which is governed are the spirits of his people,
so these are to be governed by his Spirit, and spiritually,
and not after a fleshly manner.

Thus Christ himself, though he served his disciples,
yet he also was their Lord and Master,
and in the Spirit and life of the Father ruled over them.
In the same way, the apostles and other ministers of Christ had, in the Spirit,
the care of the churches and authority in the Lord.
And by his Spirit they did govern the spirits of his people.
These did not govern after a fleshly manner, by their own wills.
They did not prescribe to others what they must believe or practice; but rather,
in the light and in the power of the Spirit,
they made their way into everyone's conscience in the sight of God.
They ministered to everyone in the Spirit according to their capacity and growth,
and waited patiently for God to convey the food and nourishment,
and to build up their spirits in faith.

"`The spirit of the prophets is subject to the prophets.`"
Here is the government, here is the law of rule and subjection in the life.
Everyone, feeling a measure of the Spirit in himself,
is thereby taught to acknowledge and be subject to a
greater measure of the same Spirit in another.
He that has no measure of the Spirit of God, he is not of God,
he is none of Christ's. But he that has received a measure of the Spirit,
in the same Spirit he can feel another's measure,
and acknowledge it in its place and service, and know its moving, and will not quench it,
but rather give way to it with joy and delight.
When the Spirit moves in anyone to speak,
the same Spirit moves in the other to be subject and give way.
So as everyone keeps to his own measure in the Spirit, here there can be no disorder,
but true subjection of every spirit.
But wherever this is lacking,
it cannot be supplied or set up in the church by any outward rule or order;
for that is fleshly, and lets in the flesh, and destroys the true order, rule,
and subjection of the Spirit.

The true apostles and ministers of Christ come
from Christ with a message of life and salvation,
with a testimony concerning the good-will of God, and his love to mankind.
These point out the way from death to life, from bondage to liberty,
from wrath and destruction to peace and salvation.
What they have seen, what they have felt, tasted, and handled,
what they have found to redeem and deliver them,
this they declare to others as they are moved, as they are sent,
as they are guided and assisted.

Now that which they preach is to men's consciences in the sight of God.
They open the truth which they know; they give their testimony in the moving, leading,
and power of the Spirit,
and leave it to the same Spirit to demonstrate it to men's consciences as he pleases.
The ministers are nothing, they can do nothing, they cannot convert any man to God.
Nevertheless, the power that speaks by them,
that same power works in other men's consciences at its pleasure.
And here is the beginning of the government of Christ in the heart:
when his truth carries conviction with it to the conscience,
and the conscience is drawn to yield itself up to him.
Then Christ lays his yoke upon it, and takes upon himself the guiding of it.
He cherishes it, he cleanses it, he comforts it, he orders it at his pleasure;
and he alone preserves it pure, chaste, gentle, meek,
and pliable to the impressions of his Spirit.
And as the conscience is kept single and tender to Christ,
so his government increases therein;
but as it becomes hard, or subject to men's wills,
so another spirit gets dominion over it.

Therefore,
the great work of the minister of Christ is to keep the conscience open to Christ,
and to preserve men from receiving from them any truths
of Christ further than what the Spirit has opened.
They must keep men from imitating any of their practices further than the Spirit leads,
guides, and persuades them.
For men are exceedingly prone to receive things as
truths from those of whom they have a high opinion,
and to imitate their practices, and thereby hurt their own growth,
and endanger their souls.
For if I receive a truth before the Lord by his Spirit makes it manifest to me,
I lose my guide, and follow only the counsel of the flesh,
which is exceedingly greedy to receive truths and run
into religious practices without the Spirit.

Therefore, the main thing in religion is to keep the conscience pure to the Lord,
to know the guide, to follow the guide,
to receive from him the light whereby I am to walk.
I must never take things for truths because others see them to be truths,
but rather wait till the Spirit makes them manifest to me.
Nor should I run into worships, duties, performances,
or practices because others are led there, but rather wait till the Spirit lead me there.
The apostles were exceedingly tender in this point;
for though they certainly and infallibly knew what was to be believed,
yet they were not lords over men's faith,
but waited till he who is Lord of the faith opened the way into men's consciences.
They did not take it upon themselves to be able to turn
the key and let truth and conviction into men's spirits,
but rather directed men to him who alone has the true key.

"`Let every man,`" says the apostle,
"`be fully persuaded in his own mind.`" Rom. 14:5.
Take heed of receiving things too soon;
take heed of running into practices too soon; take heed of doing what you see others do.
Rather wait for your own particular guidance, and for a full persuasion from God.
Though I know something to be true,
yet you must not receive it till God make it manifest to you.
Receive truth from his hand alone; stay till he gives it to you.
Indeed, the main matter in religion is to prevent the wrong part, the forward part,
the first birth, from running into duties and laying hold of promises;
and also to experience the true heir born of the
immortal seed to whom everything belongs.
Having known the true seed, let not the other birth afterwards get up above him,
but rather be subdued and brought into subjection.

Again, says the apostle, take heed of doing anything "`doubtingly.`"
Be not forward or hasty, but wait for the leading,
wait for the manifestation of the Spirit.
Be sure you receive all that you receive in faith,
and practice all that you practice in faith; for "`whatsoever is not of faith is sin.`"
To receive or act apart from faith is to err from the seed of life,
to lose your guide and thereby lose ground, dishonor Christ,
and come under condemnation.

And so the apostle warns believers to
take heed of drawing one another on too fast,
or of judging one another in such things as some of them might have light in,
and others not.
He that eats is not to judge him that does not eat;
and he that does not eat is not to judge he that eats.
In matters of worship, he that observed a day, and kept a Sabbath,
is not to judge him that did not observe a day, nor kept a Sabbath.
For in the days of the apostles,
the Jews who were truly converted were slow to be drawn
off from the observation of their Sabbath,
and could hardly bear with the believing Gentiles who
were never taught to keep their Sabbath,
but were taught to esteem every day the same, and sanctify them to the Lord.
Rom. 14:5. And those who esteemed every day the same, and dedicated them to the Lord,
could hardly bear with those who observed a day.
Now it is true that, Christ having come, we are not to set up a new type,
but to enter by faith into the true rest,
which is the substance of what the other days signified.
But Christians are prone to strive after a wrong unity
and uniformity in outward practices and observations,
and to judge one another unrighteously in these things.
Now mark; it is not the different practice that breaks the peace and unity,
but the judging of one another because of different practices.
He that does not keep a particular day may unite in the same Spirit, in the same life,
in the same love with him that keeps a day.
And he who keeps a day,
may unite in heart and soul with the same Spirit and life in him who does not keep a day.
But the one that judges the other because of either of these errs from the Spirit,
from the love, from the life, and so breaks the bond of unity.
And he that draws another to any practice before the life leads him,
this one does injure the soul of that person. verse 15.
This was the apostle's rule:
that everyone perform singly unto the Lord what he did,
and not for one to meddle with the light of
conscience of another (undervaluing his brother,
or judging him because his light and practices differed from his, chap. 14:10.)
Everyone was to keep close to their own measure of light,
even to that proportion of faith and knowledge
which God in his mercy had bestowed on them.
And here is the true unity in the Spirit, in the inward life,
and not in an outward uniformity.
Such an outward conformity was not necessary in the apostles' days,
nor is it necessary now,
and the eye that seeks it overlooks the one thing which is necessary.

If men will but keep close to God, the Lord will lead them on fast enough,
and give them light fast enough; for he takes care of such things,
and knows what light and what practices are most proper for them.
But when men walk on faster than the Lord holds forth his light to them,
this overturns them, and raises up a wrong thing in them.
In this way the true birth comes to suffer, to shrink and be driven back.
Oh how sweet and pleasant is it to the truly spiritual eye,
to see several sorts of believers, several forms of Christians in the school of Christ!
How great indeed when everyone learns their own lesson,
performing their own peculiar service, and knowing, acknowledging,
and loving one another in their several places
and different performances to their Master,
to whom they are to give an account,
and not quarreling with one another about their different practices! Rom. 14:4.

This is the true ground of love and unity:
not that a man walks and does just as I do,
but rather that I experience the same Spirit and life in him, and that he walks in this,
according to his own measure, order, and in proper subjection to it.
Indeed, this is far more pleasing to me than if he walked just as I walk.
For I cannot desire that he should do so until he be
particularly led there by the same Spirit which led me.
And he that knows what it is to receive any truths from the Spirit,
and to be led into practices by the Spirit,
and how prone the fleshly part is to run ahead,
he will not be quick to press his knowledge or practices upon others.
Rather, he will wait patiently till the Lord fit them for receiving these,
for fear lest they should receive and practice too soon,
even in that part of man which cannot serve the Lord.
And this I can truly say concerning myself,
I have never found my spirit pressing to draw
anyone either to what I believed to be true,
or to any practice or way of worship I observed or walked in.
Rather I have desired that the power and leadings of life might go before all men,
and have been afraid lest men should receive things
from my hand and not from the Lord's.

=== The True Government of the Church

Therefore, since the true church government is in the Spirit,
and over the conscience of man as in the sight of God,
great care must be taken that nothing else govern except the Spirit,
and that the government be extended only unto that which should be governed.

_First:_ Care must be given that nothing govern in the
church of Christ except the Spirit of Christ.
Nothing else much teach; nothing else exhort; nothing else admonish and reprove;
nothing else cut off and cast out.
Every minister in the church is to watch over his own
spirit that it does not intrude into the work of God,
that it does not take upon itself to be the teacher, the exhorter, the reprover, etc.
And every member is to wait in the measure of the Spirit which he has received,
to experience the movements of the Spirit in him who teaches and governs.
In this way each one is subject not to man, but to the Lord;
each receives from the Lord and obeys the Lord.
We are not to know any minister according to the flesh,
but to receive and submit to what comes from the Spirit, in the Spirit.
We are not to know Paul, or Apollos, or Cephas, but the Spirit ministering in them.
Paul may err, Apollos may err, Peter may err (and did err,
when he compelled the Gentiles to live as the Jews, Gal. 2:14),
and Barnabas also did err. ver. 13.
But the Spirit cannot err.
He that keeps to the measure of the Spirit in himself cannot let in error.
For the least measure of the Spirit is true, and gives true judgment.
Yet he that receives ever so great a measure of the Spirit,
if he does not keep low and abide therein,
but rather lifts himself up above his brethren,
this one may easily err and draw aside others into his error.

_Second:_ Care must be taken that the conscience be kept tender,
that nothing be received but according to the light in the conscience.
The conscience is the seat of faith;
and if it be not kept close to the light which God shines there,
faith is soon made shipwreck of.
Christianity is begun in the Spirit,
which keeps out the fleshly part with all its fleshly
wisdom and reasonings about spiritual things.
And even as the beginning is in the anointing, so must the progress be.
As the Spirit begins in the conscience, by convincing there and persuading there,
by setting up his light there and leading the soul by that light,
so that light must be continually sought and seen.
Only as the light grows and manifests itself in the
conscience does the soul either stand still or move on.

The great error of the ages of the apostasy has
been to set up an outward order and uniformity,
and to make men's consciences bend to it either by arguments of wisdom, or by force.
But the property of the true church government is to
leave the conscience to its full liberty in the Lord,
to preserve it single and entire for the Lord to exercise,
and to seek unity in the light and in the Spirit.
He that has faith, and can see beyond another, can have it to himself,
and not disturb his brother with it,
but rather descend and walk with him according to his measure.
Oh how sweet and lovely is it to see brethren dwell together in unity,
to see the true image of God raised in persons,
and they knowing and loving one another in that image.
How lovely to bear with one another through love,
helping one another under their temptations and distresses of spirit,
which everyone must expect to meet with.

If you are a Christian in deed and in truth,
preserve your conscience pure and tender towards God.
Do not defile it with religious practices, duties, ordinances, etc.,
into which the Spirit is not leading you; for all such things are idols,
and will exceedingly pollute you.
And be tender also of your brother's conscience,
and do not be an instrument to draw him into anything where the Lord does not lead him.
Rather, rejoice if you find him in simplicity of heart
being dealt with of the Lord in anything;
for if he abide here faithfully,
his guide will in due season appear to him and clear his way before him.

Oh how many have turned from the Lord and played the harlot!
How many have first lost the guidance of his Spirit,
and then drowned their life in religious performances!
How many have drunk of the cup of fornication
from the life at the hands of the fleshly wisdom!
How many have filled their spirit with New Testament idols and images!
How many have even hardened their hearts and
consciences by following the doctrines of men,
their imaginary meaning of scriptures,
and the imaginations and dreams of their own hearts!
Is it not time for men to turn back towards the Lord,
to wait for the visitation and light of his Spirit?
And if ever anyone feel and enjoy the guidance of God's Spirit,
their conscience must be kept tender to it,
and ready to hear and follow his voice who speaks in Spirit to that which is born of him.
"`My sheep hear my voice,`" says Christ; they know it,
and the voice of the strange spirit they do not know so as to follow it,
but turn from it, both in themselves and others.
Wait therefore for the birth of the Spirit, to which the Spirit is given for a guide,
who infallibly guides it out of deceit.

[.discourse-part]
Objection: But is not unity lovely;
and does not the apostle exhort Christians to be of one mind?
And would it not be a sweet thing if we were all of one heart and one way?

[.discourse-part]
Answer: Yes, unity is very lovely;
and to be desired and waited for as the Spirit of the
Lord (which is one) leads and draws into one.
But the fleshly part (the wise reasoning part in man), by fleshly ways and means,
strives to bring about fleshly unity; this is not lovely, nor spiritual, nor Christian.
And the apostle, who exhorts Christians to one mind,
yet does not bid them force one another into one mind,
but rather walk together sweetly so far as they had attained.
And if in anything they were otherwise minded,
God in his due time would reveal more to them. Phil. 3:15-16.
He that has, to him more shall be given.
And the intent and work of the ministry (with the
several ministrations of it) is to bring into the unity, Eph. 4:13,
according as persons are able to follow.
It is not to force all men into one practice or way.
This is the way to destroy the faith and the true unity.
This, at best, can introduce but a fleshly appearance of unity,
in an outward form of worship and godliness that eats out the power.

Indeed, the way is one--Christ, the truth of God.
He that is in the faith,
and in the obedience to that light which shines
from his Spirit into the heart of every believer,
has a taste of the one heart and the one way.
This one knows that no variety of practices (which are
of God) can make a breach of the true unity.
This is the one way:
for everyone to be subject to the light of Christ's
Spirit which he has received from Christ.
And if the unity be kept in this way, it will also come into an outward unity at length,
as the light grows in everyone, and as everyone grows into the light.
But this must be patiently waited for from the hand of
God (who has the right way of effecting it,
and who alone can do it), and not harshly and cruelly attempted by the rough hand of man.
