[#ch10, short="Prayer, Ministry, Wisdom, & Kingdom"]
== Chapter X. The Prayer, Ministry, Wisdom and Kingdom which are Spiritual

=== Prayer in the Spirit

True prayer is the breathing of the child to the Father which begat it,
from the true sense of its needs, for the supply of those needs.

"`The wind blows where it wishes, and you hear the sound of it,
but do not know where it comes from or where it is going;
so is every one that is born of the Spirit.`" John 3:8.
God, by the breath of his Spirit,
begets a man out of the spirit and likeness of
this world into his own image and likeness.
He that is begotten in this way needs nourishment, needs the divine warmth,
the breasts of consolation, the clothing of the Spirit, the garment of salvation.
He needs the bread of life to feed on and the water of life to drink.
He needs strength against the enemy's assaults
and wisdom against his snares and temptations.
He needs the arm of the Deliverer to preserve and carry on the work of redemption daily.
He needs faith to deny the fleshly wisdom that he may
trust and feel the virtue of the arm of the Deliverer.
He needs hope, patience, meekness, a clear guidance,
and an upright heart to follow after the Lord.
Indeed,
very many are the daily needs of that child which is begotten by the breath of God,
in its state of weakness, until it is drawn up into the unity of the body,
where the full communion with the life is felt, the heart satisfied,
and the deficiencies drowned.

Now the breathing of this child to the Father from the
true sense of these needs for his supply--that is prayer.
Even if it be but a groan or sigh which cannot be uttered or expressed,
yet this is prayer, true prayer,
which has an acceptance with the Lord and receives a gracious answer from him.
And he that begets the child is the one who teaches him to pray,
even by the same Spirit which begat him.
In watching daily to the Spirit, the child is kept sensible of the will of the Father,
and in his light he sees the way wherein he is to walk.
He sees also the enemy when he is coming, and the snares he is secretly laying,
and he feels his own weakness to withstand or escape.
And in the sense of this his heart cries to the Father of spirits for preservation,
for him to step in at the needful time, even in the season of distress.
And thus watching to the Spirit, the life of a Christian is a continual course of prayer;
he prays continually.
This is the living prayer of the living child, which consists not in a form of words,
either read out of a book or conceived in the mind,
but in experiencing the breath of its nature issuing
out from the seed of life within to the living spring,
which is the Father of it.
And the Father, by causing his virtues to spring up in it,
nourishes the soul to everlasting life.

But many are those who are not born of the Spirit,
but (by conceiving some of the truths of God in the wisdom from below)
have attained to some change of opinion and conduct.
These pretend to be of this birth from above,
though indeed they are born but "`of blood,`" or "`of the will of the flesh,`" or
"`of the will of man,`" John 1:13.
And though they will be imitating the things
which God begets in and gives to the true child,
they are outside of the nature and spirit where the true child is begotten,
and where the true gift of the Father is received by him.
These will be believing,
though they have not received a portion of the living faith from the hand of the Father.
They will be forming repentance and sorrow for sin,
though their heart is not turned from it.
They will be hoping in God's mercy,
although they are off the foundation and out from under the shadow of the mercy seat.
And they will be praying, though they have neither received the Spirit,
nor been taught by the Spirit to pray.
And so being out from that which should guide them and teach
them the truth and way of worship as it is in Jesus,
they run out into inventions and imaginations, setting up a way of their own choosing.
And having given much thought to their way, and formed it by reasonings,
and fenced it about with arguments, these grow wise in their own eyes,
and now verily believe it to be the way of God and that
they can maintain it against all opposers.

So it is that one man is for a particular form of prayer or worship,
and another man is against that form, and instead is for another;
and each thinks himself able to maintain his own view, and to overthrow the other.
But oh, that the ear were open which can hear the truth!
If only there were a true, honest, upright desire after God,
from the simplicity of the heart,
then man would not be so easily betrayed by the subtlety of the fleshly wisdom,
which lies lurking in the wise and reasoning part of man, to betray the poor, weak babe.
The natural man, the reasoning man, the understanding man,
the wise man according to the natural wisdom, cannot understand the things of God.
In the wisdom and understanding of man there is no learning to pray aright,
to believe aright, to hope aright, to mourn aright, to rejoice aright, etc.,
but such wisdom must be brought to nothing, 1 Cor. 1:19,
and a man must become a child to all knowledge for him to know God's way.
But the one that becomes such a child is taught to pray, to believe, to wait, to hope,
and all that is necessary to eternal life.

Now as the Father teaches to pray,
so he gives desires or words (if he please) according to the present need.
Sometimes he gives but the ability to sigh or groan
(and if he give no more, he accepts that).
Sometimes he gives strong breathings and plenty
of words to pour out the soul before the Lord.
But if a man should hear and remember those words, and lay them up for another time,
and offer them up to God in his own will, this would be but will-worship and abomination.
This I have known experientially, and have felt the wrath of God for it.
Prayer is that which comes fresh from the Spirit,
and the true desire is that which the Spirit begets.
But the affections and sparks of man's own kindling do not please the Lord,
nor do they conduce to the soul's rest, but will end in the bed of sorrow. Isa. 50:11.

Now concerning the use of the Book of Common Prayer,
or concerning prayers conceived in the mind
without the immediate breathings of the Spirit,
I will speak my own experience faithfully, which is this:
I have felt both of these draw out from me the wrong part,
and keep that alive in me which the true prayer kills.
And he that utters a word beyond the sense which God
begets in his spirit takes God's name in vain,
and provokes him to jealousy against his own soul.
"`God is in heaven, you are on earth, therefore let your words be few.`"
The few words which the Spirit speaks, or the few still, soft,
gentle breathings which the Spirit begets, are pleasing to God,
and profitable to the soul.
But the many words which man's wisdom conceives hurt the precious life,
and thicken the veil of death over the soul,
keeping that thing alive which separates from God,
that which must die so that the soul can live.

True prayer comes by that which God begets in the virtue of his Spirit,
("`praying always in the Spirit,`" Eph. 6:18. Jude 20) in the time he chooses.
For the Spirit breathes when he wishes and where he wishes,
and man cannot limit when he will breathe, or when he will not breathe.
But man is to wait the season of the Spirit's breathing, and so to "`watch unto prayer.`"

Now if the prayer be in words (for there is a praying without words),
then it must be in those words which the Spirit pleases to give,
from the sense which he kindles, and not in the words which man's wisdom teaches,
or would choose to use.
And indeed, in the true religion, and in every exercise of it, man's wisdom is kept out,
and nailed to the cross,
by which means the immortal life is raised and increases in the true disciple.
This one believes, he hopes, he waits, he prays, he mourns, he rejoices, he obeys, etc.,
abiding in the cross to the mortal part.
He does these things not as man's wisdom teaches,
for his sacrifice unto the Lord is still an abomination,
even to the wise Egyptian part in himself. Ex. 8:26.
But let him do all as the life teaches, as the wisdom from above teaches,
which breaks down, shuts up, confounds and destroys man's wisdom,
while God is teaching his babe.

=== Ministry in the Spirit

It is not preaching true things which makes a true minister,
but receiving a ministry from the Lord.
The gospel is the Lord's, which is to be preached, and is to be preached in his power;
and the ministers which preach it are to be endued with his power, and to be sent by him.
The apostles had received instructions concerning the kingdom from Christ's own lips,
both in his lifetime and after his resurrection, Acts 1:3,
and had received a commission from him to teach all nations. Matt. 28:18.
Yet this alone was not sufficient to
make them able ministers of the New Testament.
For before the apostles went abroad to preach,
they were instructed to wait for the power. Acts 1:4,8.
And having received power, they were to minister in it,
that men might be converted to the power, and by the power,
so that the faith of men might not stand in the wisdom
of their words (which Paul might have abounded in,
as well as others), but in the power of God. 1 Cor. 2:5.
Knowing this, Paul ministered in fear and trembling,
lest the wrong part in him should minister;
lest the earthly understanding part should be holding
forth the truths of God outside of the life,
outside of the power,
and thus converting men to the wisdom of the words he spoke and not to the power of God.
ver. 2-3. Paul was sent by the Lord to turn men "`from darkness to light,
and from the power of Satan to God,`" Acts 26:18,
from the spirit of enmity and death to the Spirit of love and life;
and so he took great care in his ministry that men might not
run away with his words and miss the substance.
This also was the way whereby he discovered true and false ministers: "`I will come,
and know (says he) not the speech of them which are puffed up, but the power;
for the kingdom of God is not in word, but in power.`" 1 Cor. 4:19.
Many men might catch the apostles'
words and run away with them and preach them;
but they could not minister in the power.

Now the kingdom, which gospel ministers preach,
consists not in words but in power.
"`God has made us able ministers of the New Testament, not of the letter,
but of the Spirit.`" 2 Cor. 3:6.
The ministry of the New Testament is a ministry of the Spirit,
and it cannot be without the Spirit.
It is a reaching to men's consciences "`in the demonstration
of the Spirit and power,`" 1 Cor. 2:4 and 2 Cor. 4:1-2,
which, being felt in the heart and turned to, converts them to God.

The ministry of the gospel does not consist in a bare opening
of the letter (or raising of doctrines and uses from the letter which
the wisdom of man may easily perform) as the ministry of the law did.
Rather, it consists in bringing men to the experience of the Spirit,
even of the eternal power of God which redeems,
in turning men from the darkness to the light, in setting their faces towards the power.
The gospel is the substance of what was shadowed out in the law,
and he that ministers it must minister substance.
He must have the heavenly treasure
(that is the substance) in his earthly vessel; 2 Cor. 4:7,
and he must give out of this treasure into the vessel which God prepares.

Now in order to do this, he must minister in the Spirit and in the power.
His words must not be such as man's wisdom would teach,
or as man's comprehension would gather,
but such words as God's wisdom prepares for him and puts into his mouth.
He that will be a true minister must receive both his gift, his ministry,
and the exercise of both from the Lord,
and he must be careful in his ministering to keep in the power,
or he will never win others to the power.
But in keeping in the power,
he is to minister standing in the cross to his own understanding and wisdom,
giving forth the truths which the Lord chooses
to have him speak in the words which God chooses,
even in the words which are ministered to him by the power.
Ministering in this way he shall save his own soul, and the souls that hear him,
even all who in fear and meekness receive the
ingrafted word which is able to save the soul.

For alas,
many have received words of truth and apprehensions of
knowledge whereby they hope to be saved,
but how few are acquainted with that knowledge which stands in the power of God,
which alone converts and keeps alive unto God!
Oh, how many souls are to be answered for by those
who take upon themselves to be pastors from God,
who have fed the flock with words, with discourses which they have made,
and have ruled over them with force and cruelty, but have lacked the love,
the tenderness, the light and power of the true Shepherd!
Oh, what will these do when God requires his sheep at their hands?
Oh, that there were in you a heart to consider, you shepherds of England!

Christ, by his ministry, calls his disciples out of the world up to the Father,
out of the honor, riches, and whatever else is of the world.
"`How can you believe, when you receive honor one of another,
and seek not the honor that comes from God only?`" John 5:44.
And the rich man, he bids him "`sell all and follow him.`"
And the Apostle John says, "`Love not the world, neither the things that are in the world.
If any man loves the world, the love of the Father is not in him.
For all that is in the world, the lust of the flesh, the lust of the eyes,
and the pride of life, is not of the Father, but is of the world.`" 1 John 2:15-16.
He that will be a disciple of Christ
must travel out of the earthly into the heavenly,
leaving all that is of this world behind him,
possessing nothing as his portion except for him who has called him out of this country,
from among his kindred, and from his father's house,
to another land, kindred, and habitation.
So that here they are pilgrims and strangers, sojourners and passengers,
unknown to the world, and of a strange dress, behavior, and appearance in it.
They are not enjoying anything as the world enjoys it,
nor using anything as the world uses it.
They are not honoring men or receiving honor
from men as the world gives or receives honor,
but rather are honoring men in the Lord, and receiving honor from the Lord.
And whatever they seem to retain of earthly things, they hold as stewards under the Lord,
not using or disposing of them as they think good,
but waiting for the discovery of the Master's pleasure,
who orders all in his counsel and wisdom to his own glory.
The law required a tenth part to be given up to the Lord; the gospel requires all--soul,
body, spirit, good name, etc.,
even that the whole possession be sold and laid at the Master's feet.
And he that keeps anything back cannot be a disciple, cannot be a soldier of Christ,
but must of necessity entangle himself with the affairs of this life.

The Lord circumcises the heart of believers under the new covenant,
to love the Lord their God with all their heart that they may live.
He causes the plant to spring up out of the dry and barren ground,
which he waters with his blessing, and he lays his axe to the root of the old tree,
hewing at it, even till he has cut it up.
He engrafts the Eternal Word into the heart,
and by it daily purifies and carries on the work of faith with power.
And the ministry which he gave was for the "`perfecting the saints,`" Eph. 4:12-13,
which ministry exhorted and encouraged believers (from God's promises of his
presence and powerful operation of his Spirit in the hearts of his sons and
daughters) to "`cleanse themselves from all filthiness of the flesh and spirit,
perfecting holiness in the fear of God.`" 2 Cor. 7:1.

=== Spiritual Wisdom

To know Christ as the light eternal (as he was yesterday, is today,
and will be forever), to trust this light in its convictions, calls,
and openings of love, to experience its living virtue,
and in that virtue to give up all that is of the earthly nature and spirit,
and sell all for the everlasting inheritance, this is indeed the way to life.
But it is not the doing of things which is of value,
for man may imitate and strive to do much,
and may go a great way in forsaking all and in taking off his affections
from things (inasmuch as he may give all his goods to the poor,
and his body to be burned, and yet it profit him nothing).
But the doing of things in the virtue, in the life, in the power which comes from Christ,
this has acceptance with God and is of advantage to the soul.
Every motion and operation of true life springs from the root of life,
and has the virtue of the root in it.
And that which distinguishes this from all of men's imitations,
and from all the likenesses which the earthly spirit can put forth,
this is the nature and virtue of the root being manifest.
Therefore, he that will be a true Christian must fix his eye on Christ,
the spring of his life, and keep in the feeling and experience of his living virtue,
and in that offer up all his sacrifices of faith, love, and obedience to God.
And he that will be a true minister must wait upon the power himself,
to be an instrument (in the hand of power) to direct men to this,
and to preserve and build them up therein.

But alas, this is the stone which the wise builders have always refused!
The builders before the coming of Christ got a knowledge concerning the Messiah to come,
but being unacquainted with the thing itself,
rejected both its coming and the vessel in which it appeared.
And the builders all throughout the apostasy got a knowledge of Christ having come,
and preached believing in him crucified as the way to life; but the living stone,
the living thing itself, which is both the foundation, the corner stone,
and the top stone of the building,
they have been ignorant of and ready to persecute at every appearance of it.
Christ can no more now appear in Spirit than formerly he could in
that prepared body of flesh without the wise builders showing
themselves ready to cry out against him as a blasphemer,
a profaner of God's ordinances, a deceiver of the people, or one that has a devil.
"`But wisdom`" in all ages "`is justified by her children,`" and by no one else.
He that is born of the wisdom can discern the
womb and acknowledge the fruit and branches,
even under the dark veil whereby it hides itself from all the fleshly-wise of every age.
"`The kingdom of God comes not by observation.`"
The wisest Scribes and Pharisees could not know it by all the observations
which they could gather out of Moses' and the prophets' writings.
And none can know it now by any observations
which they gather out of the apostles' writings,
but rather by being born of that Spirit whereof the apostles were born,
and by being formed in that womb wherein they were formed.
By this means alone does one come to know the thing that they knew.
He that receives the same eye, sees the same thing, according to his measure.
And coming to the life wherein the apostles received the truth,
the words which they spoke concerning the truth are easy to discern.
As they were written in the Spirit, so they must be read in the Spirit;
and they are exceedingly profitable when read in this way.
But man,
guessing and imagining and reasoning in his carnal wisdom concerning the things of God,
and so gathering senses and meanings about the words and expressions of Scripture,
does but build up a Tower of Babel,
which the eternal life and power will throw down (whenever he appears),
together with him who built it.

Oh that men were wise to wait for the discovery of the true rock,
and of the true builder upon that rock!
Oh that that city and building might be raised in them which God alone can erect.
Then they would not be left desolate and miserable in that stormy day
which will shake all buildings and foundations and rocks,
except our Rock.
For in that day all professors and preachers and high notionists and
whatever sort else can be named who have stumbled at God's living truth,
shall confess with tears, sorrow, anguish, and shame, that their rock is not as our rock.
For though all sorts of professors generally
acknowledge Christ as the rock in their words,
yet most miss the thing itself.
For the subtle enemy has made use of a notion or apprehension of the thing
in the carnal mind to deceive and lure away from the thing itself.
Thus he keeps them from feeling the eternal virtue,
the living power of life in the heart, which is the arm of God's salvation,
whereby Christ draws man's lost soul and spirit out of
the grave of sin and corruption up to the Father.
But oh,
how are poor hearts deceived who think they will be presented
without spot or wrinkle to God having a mere belief regarding
what Christ did while he was here on earth!
How deceived are they who boast in Christ's making satisfaction for
them even while they carry the body of sin around with them to the
very last of their time here in the body,
and have not felt the arm of God's power breaking down their spiritual enemies,
their lusts, their corruptions, and redeeming them from them!
Christ had the name Jesus given him because he was to save his people from their sins,
and no man can truly and livingly know the name Jesus
further than he experiences the saving virtue of it.
But the one that effectually experiences the virtue, he indeed knows the name,
and can bow at the name, feeling his lusts and enemies bowed under by the power of it,
and feeling something else raised up in him
which can worship the Father in Spirit and truth.
Oh that the sons of men knew!
Oh that the teachers and professors of this age understood
what they have so long reviled and trampled upon!
Surely they would mourn bitterly, kiss the Son, and escape the wrath.

Now, if the Lord is pleased to smite anyone's earthly wisdom and
comprehension (which is the main thing that stands in the way
of the pure openings and revelations of the life),
and give him a true sense of anything here written, let him in fear acknowledge the Lord.
Let him wait upon the Lord to be kept in this feeling,
not magnifying or reviling any of his messengers,
but in meekness and humility embracing the instructions of the
Almighty from whatever hand he has used to give to them.
As for me, I am but a shell.
And if this party knew me^
footnote:[The text of this chapter is taken from Penington's response to a paper in
which he felt he was being unduly praised or preferred by its authors.]
(who sets me up so high,
preferring me above many whom the Lord has preferred far above me),
he would soon acknowledge me to be a poor, weak, contemptible one.
Yet I must by no means deny that indeed the pure liquor of the eternal life,
at its pleasure, springs up and issues out through me.
Though I can also say, in true understanding, that it issues out far oftener,
and much more abundantly through others.
Let it have its honor, wherever it appears!
And may the Lord bring down that thing in people's hearts
which hinders the acknowledging and receiving of its virtue.

=== The Spiritual Kingdom

Christ's kingdom, God's kingdom,
the kingdom of heaven (for they are all one and the same),
is that seed of eternal life which God has hid in the hearts of the sons of men,
whereby he gathers them back unto himself, brings them under the yoke of his government,
rules over them, and reigns in them.

This kingdom is likened to a grain of mustard seed for its smallness;
to a pearl for its riches, value, and worth; and to leaven for its spreading nature.
And many other parables did Christ make use of to describe it: such as a piece of silver,
which the woman that lost it, lighting the candle, sweeping the house,
and searching it diligently, at length found it, even there where she had lost it.

Man, fallen from God, is become lost as to the Lord.
And as to his own happiness in the Lord,
he has been driven from God's blessed presence and divine image, life, and Spirit,
into the earthly spirit, image, and life, which he chose.
Yet, in this earth, in this field of the world, God has hid something,
even the everlasting pearl, which,
when man is awakened to seek and find by the eternal light of life,
is able to redeem him.
The pearl is able to overspread and leaven him (he becoming subject to the laws,
leadings, teachings,
and power of it) into the likeness and image of the pure life and spirit.

Oh that men knew the gift of God!
Oh that men knew the purchase of the blood of Christ!
Oh that men knew that spiritual good thing by
which Christ (who died for them) can redeem them!
Oh that in this gift they might be united to Christ and
so by him be renewed and restored to God.
For as the Father receives none but through the Son,
so the Son receives none but in that gift of grace which he bestows from the Father.
He acknowledges no faith, no love, no hope, no repentance, no obedience,
but that which springs from that, and stands in that.

Now, as man is born of this and leavened by it (as he becomes a fool in
his own earthly wisdom and excellency of the fallen spirit,
and becomes a babe, a child, etc.) so he enters into the kingdom,
being ingrafted into the root, and so grows up in this, and this in him.
And here is the new nature, the new life, the new heart, the new spirit,
in which the unity and fellowship with God is again known.
And here also is the disunion with the world, the wisdom, the interests, the fashions,
the customs, the fears, the hopes, the delights, the joys of this world,
and whatever else is of it.
For Christ, as he is not of the world, so he calls men out of the world.
And those who follow him and become his disciples must go out of the world after him;
that is, they must travel in spirit and conduct out from what is of the earth,
out from whatever is not of the Father.
They are not of the world,
as I am not of the world (says Christ concerning his disciples, John 17),
therefore the world hates them.

The laws of this kingdom are given forth in the kingdom,
from the covenant of life which is made there in Christ.
They are written in the heart, in the mind, as far as it is renewed.
There the fear is put, there the eternal wisdom is opened, there is Zion known,
and the Jerusalem which is from above, and the laws of eternal life issue fresh from it,
and are revealed by the life in the heart which is turned towards the life.
There sin is reproved and everlasting righteousness
manifested in the light which cannot deceive.
And as the heart is made subject under the yoke, so sin is wrought out,
and righteousness brought in.
And under the cross (or yoke of life) the blood of the
everlasting covenant runs through the vessel to keep it pure,
sweet, clean, and fresh in the life.

This then is the government of Christ: to be subject to his Spirit,
which appears and opens his will in the gift of grace which comes from him.
It is to experience his living breath, by which the heart is begotten to God,
out of the region of darkness.
It is to know the movings, the stirrings, the leadings, the steps of the Lamb,
who is "`the Captain of our salvation.`"
It is to follow him wherever he goes, doing all things that he commands,
forbearing all things that he forbids, "`without murmuring, without disputing.`"

Whoever will be of the inward Israel, the spiritual Israel,
which Christ redeems out of the spiritual Egypt,
and leads through the spiritual wilderness into the land of rest, must know his leader,
must receive his Spirit, and follow it faithfully.
"`If any man has not the Spirit of Christ,
he is none of his;`" he is none of the spiritual Israel.
And if any man follow not the spirit of Christ through all the travels in the wilderness,
(but instead sits down along the way, or lies down before any kind of enemy,
and comes not to the end of his journey,
finishing the warfare and fight of faith) he falls short of the rest.
Oh that men were awakened to consider things as they truly are!
For true religion is not an outward form of doctrine or worship of any sort,
as men generally (whose poor souls are deceived through the subtlety
of the powers of darkness) are too apt and willing to apprehend.
But true religion consists in Spirit, in power, in virtue, in life;
not in the oldness of any form that passes away, but in the newness of the Spirit,
which abides forever.
It consists in being born of the Spirit, in abiding in the Spirit, in living, walking,
and worshiping in the Spirit; yes, in becoming and growing into Spirit,
and into eternal life, for "`that which is born of the Spirit is spirit.`"
Oh that the sons of men would hearken,
that they might taste of the sweetness and riches of the goodness
which the Father in his free love has opened in the spirits of many!
Oh that men would allow the wearing out of their earthly spirit and wisdom,
that they might become like God, to be formed into and live in his image!
How long shall the destroyer in every age prejudice men against those who seek their good?
Surely the spirit of this world will strive to the very last against the Spirit of God!
For indeed the spirit of this world is not subject to the Spirit of God,
nor indeed can it be,
and so it cannot endure the government of Christ's kingdom (which is
not of this world) to be set up in its sight.

Yet the government of Christ and his kingdom is not
contrary to any just government of any nation or people.
Christ's government is a righteous government of the heart, or inner man,
which does not oppose a righteous government of the outward man.
Indeed, those who are Christ's subjects,
and are singly obedient to his law of righteousness in their spirits,
are more faithful to men, and more subject to any just law of government,
than any others can be, for their fidelity and subjection is out of love,
and for conscience' sake.
But that which offends the world is just this:
that men many times make laws in their own will, and according to their own wisdom,
which are wrought with selfish ends and corrupt interests.
And that which is of God cannot bow to anything which is corrupt in man.
It can lie down and suffer, and bear the lash upon its back,
but it cannot do anything which is against its life.
It cannot be disloyal to its King to gratify the spirit of this world;
but whatever practice or testimony its King calls for
against the evil and corruption of this world,
it must obey singly and faithfully.

Oh that men would fear before the Lord,
and be sure to govern in that which is of God.
Then the rulers on earth should harm none of his,
nor hazard the shaking of their government!
But whatever is not of God, both within and without, must fall in the day of God's power.
Oh, happy is he who is now made willing to part with
that which God is determined to rend from man,
in order that his standing may be in that which cannot be shaken!
For there has been a great earthquake in this nation,
both of things without and of things within; and there yet remains more to be shaken,
both without and within, that the glory of God may have room to appear.
O England! "`Kiss the Son, lest he be angry!`"
Let all such laws and customs as are not of him fall before him; and whatever is of him,
let it bow unto him (both within and without) that his wrath not break forth like a fire,
which none can quench.
