== Chapter XII. Some Questions and Answers / For the Opening of the Eyes

[.discourse-part]
Question: How came man to fall from his original condition?

[.discourse-part]
Answer: Not willingly, nor of an inclination of his own;
but he was deceived to entertain a desire of enlarging his
blessedness outside of the limits of the will of his Creator.

[.discourse-part]
Question: How could such a temptation enter man when he was pure and holy,
inclined towards good and against evil, after the image of his Creator?

[.discourse-part]
Answer: Man was not created to enjoy a perfection in himself separate from his Creator,
or to live of himself, but rather to live by dependence.
And though he had no inclination in himself to
seek a life in himself outside of the fountain,
yet there was in him the capacity to do so.
It was before this capacity that the tempter laid his
bait of advancing man to a greater wisdom,
glory, and excellency than what his Creator had placed him in.
Then man, considering the offer without dependence upon his Creator,
fell from that alone which was able to uphold him in the pure state wherein he was made.
In this way he was taken in the snare of misery and brought to that
loss which all the sons of Adam lie groveling under to this day.

[.discourse-part]
Question: What is the state of man since the fall?

[.discourse-part]
Answer: It is a state of darkness, a state of death, a state of deep captivity,
wherein his soul, body, and spirit have become dark as to the light of God,
dead as to the life of righteousness,
and captive unto that spirit which has entered them by their hearkening to it.
This spirit now dwells and rules in them in the darkness as God did before in the light.

[.discourse-part]
Question: How is man dark?
How is man dead?
Is his soul or body dead as to their being?
Or how is it?

[.discourse-part]
Answer: Man is not dead as to his being, either in soul or body, but as to the right,
pure, and sanctified state of each.
The vessels still remain the same in being, but they are emptied of their proper liquor,
and filled with other wine.
The understanding is the same, the reason the same, the will the same,
the memory the same, and the bodily members the same as to their being or matter;
but they are all entirely leavened,
and another king now dwells in them and reigns over them.

[.discourse-part]
Question: Is there no need then for the destruction of man's reason,
or bringing it to nothing, but only a need for a change of the leaven?

[.discourse-part]
Answer: Man has become another thing by degeneration from the life.
He is so poisoned by sin and corruption that he is to
be wholly broken down and brought to nothing,
even in the natural capacities,
so that he may be new-made and built up in the newness of the Spirit.
Thus he is to become as a fool, as a little child,
and to be formed and born of the Spirit.
And as he springs up in the life he is to forget his own country,
for he now lives in the Spirit and walks in the Spirit.
While he keeps watch to the Spirit and against his own reason in the pure child-likeness,
he shall at length find his reason new-formed and springing up in him.
But if the eye of reason opens too fast, and is not kept fixed upon the light of life,
the betrayer will enter again at that door and bring the soul into death,
even after it has had sweet and precious tastes of the redeeming virtue and power.

[.discourse-part]
Question: Can man in the fall see his fallen state,
and so seek after a recovery out of it?

[.discourse-part]
Answer:
It is not possible for him to do so without some
light shining upon him from the Redeemer.
How can darkness discover darkness?
That which makes the darkness manifest is the light.
When the vessel is dark, and the prince of darkness fills it and dwells in it,
what can that eye see except what is according to the darkness, judging evil to be good,
and good to be evil, bitter to be sweet, and sweet to be bitter.

[.discourse-part]
Question: But does not every man have at least some light, at some time or other,
whereby they can see good or evil in some measure?

[.discourse-part]
Answer:
This arises not from the light of man's nature as it now
stands in the fall (which being wholly in the enemy's hands,
and being itself become darkness, cannot at all give man notice of the darkness),
but from a fresh visitation of the life,
which gives all men a day of visitation by the shining of its light.
The living Spirit also strives with man, attracting him from the one to the other,
according to the Lord's good pleasure.

[.discourse-part]
Question:
But does not man have a kind of natural light in the
fallen condition which discovers to him good and evil?

[.discourse-part]
Answer: No, not a true light, not a true discovery,
but only something which the enemy sets up in man to keep him in the
entanglements of deceit and free from the suspicion of it.
For the enemy, entering into him by his subtlety,
blinds and deceives his eye (that he may the better hold him captive in the deceit),
insomuch as man cannot discern the false image which the enemy has stamped upon him.
For though the enemy brings man into a state of real darkness, death, and captivity,
yet these things do not appear to man as what they are, but are discolored, or painted,
to appear what they are not, and so serve better to deceive, bewitch,
and entangle man therein.
The enemy did not represent darkness, death,
and captivity in a dreadful appearance to Adam, but rather portrayed them as wisdom,
as light, as a better life, as a greater freedom.
And in this way he still enters man, and after this same manner he still dwells in man,
until the true light pursues him, opening and discovering his deceit.
The light then draws man back from this false paradise of
pleasure in human wisdom and in liberty outside of the life,
and into a sense of his lack of, and longings after, the true garden of the living God.

[.discourse-part]
Question: Is man then mistaken in his judgment of good and evil since the fall?

[.discourse-part]
Answer: Yes, altogether mistaken.
And by this mistake man situates himself and takes up
his habitation in the kingdom of darkness,
wherein are strongholds and wise reasonings against the
true God and for the false appearances of good.
So it is that in particular persons, and also in societies,
evil is pursued and affirmed as good;
and the true good is suppressed as evil through the
working of the mystery of darkness in men's hearts.

[.discourse-part]
Question: What then is the true state and condition of man in the fall?

[.discourse-part]
Answer: A state of false light, of false life, of false liberty.
He seems to himself to be advanced in wisdom above the low, empty,
naked condition of innocency (which is nothing, and has nothing,
except by a continual dependence on the goodness of the Creator).
He seems also to be advanced in life, advanced in liberty.
He can speak his own words, think his own thoughts, do his own will, seek himself,
please himself, satisfy himself.
The life of righteousness seems to him a yoke, a kind of bondage;
he is free from the restraint of it, for he has life in himself,
and is exceedingly wise in his view.

[.discourse-part]
Question: What then is the work of redemption?

[.discourse-part]
Answer: To purge the old leaven out of the vessel,
to purify the vessel from all the false appearances of light,
to batter down all the strongholds of the enemy in the mind, all the reasonings,
thoughts, imaginations, and consultations;
and so to newly-create and newly-form the vessel in the image
of the wisdom and purity wherein it was first formed.

[.discourse-part]
Question: Who does this work, or who is man's redeemer out of the fall?

[.discourse-part]
Answer: The Eternal Word or Son of the Father,
even the wisdom and power which went forth from the fountain to create all things.
The same Word goes forth from the bosom of the Father to purify the creature,
and so bring the creature back (being purified and cleansed) into his bosom again.

[.discourse-part]
Question: With what does this Word, or Redeemer, redeem?

[.discourse-part]
Answer: With his own life, with his own blood, with his own eternal virtue and purity.
He descends into the lower parts of the earth, becomes flesh there,
sows his own seed in his prepared earth, begets of his flesh and of his bone,
in his own likeness, and nourishes with his own flesh and blood unto life everlasting.

[.discourse-part]
Question: What is this life?
Or how does it first manifest itself in the darkness?

[.discourse-part]
Answer: It is the light of men.
It is that which gave light to Adam at first, again to him after the fall,
and to all men since the fall.
It enlightens in nature.
It enlightened under the law; it did enlighten under the gospel before the apostasy,
and again since the apostasy.

[.discourse-part]
Question: How does the light enlighten?

[.discourse-part]
Answer: By its shining.
The eternal Word moves, the life opens, the light shines.
This, in the least degree, is a beginning of redemption, and in its fullness,
it is redemption perfected.

[.discourse-part]
Question: How does the light work redemption in its shining?

[.discourse-part]
Answer: Two ways: first, by turning the heart from the darkness towards itself; secondly,
by exercising the heart which has turned.

[.discourse-part]
Question: How does it turn the heart from the darkness?

[.discourse-part]
Answer: The light, by its shining and enlightening, finds out its own, opens it,
and touches it with a secret virtue,
which persuades and draws the heart out from the
principle and power of death and darkness,
towards its own native spring.

[.discourse-part]
Question: May not these drawings be quenched, and the work of God stopped?

[.discourse-part]
Answer: The plant of the Lord is exceedingly tender, his pure Spirit jealous,
the enemy very strong and subtle, insomuch that the plant itself may easily be crushed,
the Spirit grieved and quenched, and the captivity redoubled.

[.discourse-part]
Question: How does God exercise the heart which is turned?

[.discourse-part]
Answer: In faith and obedience, through very great varieties and changes of conditions.
He exercises it in believing his voice, and in obeying his voice,
and in following him in whatever, and into whatsoever, he draws and requires.

[.discourse-part]
Question:
What are the several states or conditions wherein God
exercises the spirit of man in faith and obedience?

[.discourse-part]
Answer: The particular states and conditions are innumerable,
but they may be referred to under these three general heads: First,
a state of breaking down the former building.
Secondly, a state of devastation or preparation to be newly built.
Thirdly, a state of rebuilding.

God does not forget, but rather exercises his people in Egypt,
even while they are in bondage, before they come to receive his law.
He visits them in the dark land, opens the eye that can see the captivity,
causes groans and sighs in their oppressed spirits,
and then holds forth to them the promise,
and prepares them for a departure from that land.
Secondly, he has a time of stripping them,
of nurturing and bringing them up under his discipline and close exercises.
Here they are desolate, and ready to sin and perish every moment,
but they are also wonderfully provided for, and abundantly helped and pardoned.
Thirdly,
there is a state of rebuilding the stones into a new building for the life to dwell in,
after they have been prepared for their entrance into the land of life.

[.discourse-part]
Question: Declare these states, and the exercises therein more plainly.
And first show what is the state of the soul in Egypt spiritually,
when the Lord visits it there with his light.

[.discourse-part]
Answer: It is a state of deep bondage and groaning under the powers of darkness,
where the bitter oppressions increase even as the
sensitivity and tiredness of the soul increases.
The soul then discerns its captivity away from the life,
and discovers a building of death and corruption raised up in it,
in which the prince of darkness dwells and bears rule.
Then, oh, how it groans and longs after departure from that land,
and waits for the promise of redemption out of it!
But still it is left in the hand of the enemy,
and daily feels the bitter bondage from the powerful law of sin and
death springing up in the heart and issuing out through the members.

[.discourse-part]
Question: How are faith and obedience here exercised?

[.discourse-part]
Answer: In believing the promise, in waiting for the promise,
in feeling some remote drawings of the life,
and uniting with them so far as it is possible in this dark, captivated state.
Here there is an acknowledgment of the true prince,
and a bowing to him even in this state of captivity,
until he is pleased to break the bonds.

[.discourse-part]
Question: What is the state of the wilderness spiritually?

[.discourse-part]
Answer: It is a state of waiting for the guidance of the leader,
of receiving direction and laws from the leader,
of following the leader as he pleases to lead through the entanglements, temptations,
straits,
and necessities with which he sees fit to exercise the spirit
for the wearing out of that part which is not to inherit,
and for preparing the true heir for the inheritance.

[.discourse-part]
Question: How are faith and obedience here exercised?

[.discourse-part]
Answer: In waiting on the light for the leadings of the law of life,
and then in submitting to the leader,
being content with all his dispensations therein--with
the time he chooses for standing still,
with the time he chooses for traveling on,
with the proportion of light and leading that he judges fit,
with the food and clothing which he prepares and preserves,
and with the enemies he sees fit to either avoid or encounter.
Hereby man's own wisdom, man's own will, man's own strength, man's own desires,
man's own delights, with all the murmurings, weariness,
and discontent which arise from the earthly part, are by degrees worn out,
and a pure vessel is prepared for the pure birth to spring up and appear in.

[.discourse-part]
Question: What is spiritual Canaan, or the heavenly-built state, or state of the gospel?

[.discourse-part]
Answer: It is a state of regeneration or renewing in the life and pure image,
where the building is reared up which is made without hands,
and where there is a sweet and peaceable growth in the life,
and a fresh and satisfactory enjoyment of the life.

[.discourse-part]
Question: How are faith and obedience here exercised?

[.discourse-part]
Answer: In abiding in the vine, in drawing from the vine,
in returning the sap and virtue back into the vine,
and living according to its will in the free dispensation thereof.
Thus works are excluded together with self (from whom
they proceed) and the vine becomes all in all.

[.discourse-part]
Question: Are the states of Egypt, the wilderness,
and Canaan as distinct spiritually as they were naturally?

[.discourse-part]
Answer: There are indeed distinctions between spiritual states,
wherein a man may be said to be spiritually in Egypt,
and not at all in the wilderness or Canaan.
So too there is a state in the wilderness which is out of Egypt and not yet in Canaan.
And there is a state in Canaan which is beyond both Egypt and the wilderness.
Yet these states in spirit are oftentimes interwoven, along with the exercises thereof,
insomuch as the soul may, in some respects (to his own understanding) be partly in Egypt,
partly in the wilderness, and partly in the rest, life, and peace.
But these things are not to be curiously looked into,
lest a wrong wisdom and knowledge rise up.
But abiding low and little in the little seed,
the kingdom and everlasting inheritance grows daily in the soul,
and the soul daily shoots up into it, and is enlarged in it.

[.discourse-part]
Question: Is there any return back into Egypt, or into the wilderness,
after the soul has advanced higher,
and after an entrance into the everlasting inheritance has been administered,
and the soul has found a place of rest in the life?

[.discourse-part]
Answer: The enemy lies near to deceive, and while he has power to tempt,
if one hearkens to his temptations,
there will be a departure from the pure life and a return to
the captivity or to a bewildering in some measure.
In the faith and in the obedience to the light of life is the preservation;
outside of it is death and destruction eternally.

=== The Teaching, Chastisement, and Exercise of the Soul

[.discourse-part]
Question: How does the Son of God, or Eternal Word, in whom is the light of life,
redeem man out of the fallen state, out of the kingdom of darkness and death,
into the kingdom of everlasting righteousness and peace in the life?

[.discourse-part]
Answer: Three ways: First, by wounding him in the natural and corrupt state,
and so breaking his peace and pleasure in the kingdom of darkness,
and making him weary of it.
Secondly, by weakening him under the teachings and chastisement of the law.
Thirdly, by healing and binding him up with the oil of salvation,
in the power of the endless life, which is the gospel.

[.discourse-part]
Question: How does God wound him in the natural and corrupt state?

[.discourse-part]
Answer: By pursuing him with his light, which lets him see his condition,
discovering the evil and danger of it, and so weaning his heart from it,
and making him look for and long after a redeemer.
Oh, how burdensome is the captivity to the awakened soul,
when he has had a glimpse of what man was before his
fall (when man had a place and a being in the life,
with a spirit suitable to the life)! And how terrible to see
the present state of estrangement and alienation from the life,
and to know where man is going in his paths of unrighteousness, estrangement,
and alienation.

Now while man's heart is thus returning from the land of death and captivity,
and longing after the redeeming power and virtue of the life,
then the enemy (the power of darkness) lays loads upon him,
drawing him more and more under the chains and bonds of
iniquity with the utmost of its strength.
So that now lusts abound, evils increase, temptations and snares multiply.
Indeed, in the land of captivity their strength is great, and the soul is weak and faint,
and the redeeming power and virtue seem very far off.
Now this is the state of conversion,
when the Lord (in the midst of the power of death and darkness)
turns the heart from these things towards himself,
causing it to wait under the captivity for the appearance of the arm of his strength,
to break the yoke of the oppressor from off the necks of the oppressed.
In this way he brings the soul out of the land of death and darkness,
into the travel towards the land of promise, where the peace, the life,
the liberty in the Lord, the rest, the joy,
the full contentment and happiness is reaped by the soul which follows the Lamb there.

[.discourse-part]
Question:
How does God weaken the creature under the teachings and chastisements of the law?

[.discourse-part]
Answer: By exercising him with regard to good and evil,
and correcting him for his unbelief and disobedience, as he finds it good, just,
and necessary for him.

[.discourse-part]
Question: How does God exercise him with regard to good and evil, and correct him?

[.discourse-part]
Answer: When he has brought him from under the power of darkness in some measure,
and in some measure set the spirit free by the
virtue of his life springing up in the heart,
then he exercises the heart and conduct towards the good and away from the evil.
Then he gives out laws for or against things,
according as he finds it most proper to the state of every particular soul.
Now upon the giving forth of the law (the life being in some measure raised),
there is that which loves its teachings and pure path,
and there is also that which draws back from it.
And since that part which draws back is still strong,
there come many strokes and chastisements from the Lord upon his own dear child.
These are indeed bitter.
And it is also bitter to be forced into the sin which the heart now
loathes and has turned from (partly by the strength of the enemy,
and partly by reason of its own weakness and negligence),
and to be kept from the good which it longs after, and in heart is united to.
And so the soul cries out day after day,
and finds this administration of the law almost
as heavy a yoke as the land of captivity itself,
because of its weakness through the flesh,
and the strength and advantages which the corruption of
the heart and prince of darkness gather thereby.

[.discourse-part]
Question: What is the benefit of these exercises upon the soul?

[.discourse-part]
Answer: They melt, they break,
they make the heart tender and fit to be molded by the
eternal virtue and power into a vessel for the power.

[.discourse-part]
Question: What frames of spirit do they work the heart or mind into?

[.discourse-part]
Answer: Into very many precious ones.
As for instance: First, they make the spirit poor.
The daily inroads of sin and corruption dashing
against the holy and righteous law of life,
and overbearing the strong desires after purity, and forcing into the defilement,
hindering the soul from doing what it loves,
and making it do what it hates--this makes it become poorer and poorer,
and more afflicted day by day.
Upon some visitations of the pure life, and some fresh virtue received, oh,
how strong does the soul seem!
But when it suddenly forfeits its mercies, loses its freshness,
and is plunged deeper in the pit than before,
how poor and weak does it then feel itself to be!
Then it trembles at the next openings of the life and the springing up of its virtue,
not knowing what weakness, captivity, entanglements,
and misery from the snares of death remain to follow!

Secondly, they bring into a mourning state.
They fill the eyes with tears, and the heart with sorrow.
Yes, they cause an entrance into the house of mourning.
To be accustomed to wounds, bruises, snares, grieving of the Spirit,
provoking of the deliverer, furthering and giving advantages to the enemy, etc.,
the sense of this overwhelms the heart with grief,
and causes continual sorrow and lamentation to that part which is upright towards God.

Thirdly, they bring into a meek, merciful, tender-hearted frame towards others.
He that is tempted, he that often falls and is so often wounded and made miserable,
he pities those that err.
He mourns over the miserable.
His heart is broken with the sins and afflictions of others,
and he knows not how to be hard towards them,
feeling such continual need of abundant mercy himself.
It is the rich man, the sound man in religion, that is rough and hard.
But he that has been thoroughly melted in the furnace and built up again is made tender,
and retains the impression of the meekness, love, and mercy forever.
Now a broken state in religion, or a state of waiting for the life,
is much more precious than that which seems rich and full by what it formerly received,
and what it holds outside of the immediate feeling and fresh virtue of the life.

Fourthly,
they bring into a hungry and thirsty state after holiness and righteousness.
Oh, how the soul that is sensible of its filth longs to be washed!
How it pants after the pastures of life, the food of life, the living waters!
How it longs to appear before and enjoy God in the land of the living!
And oh how does the heart that is daily afflicted with its unbelief
and disobedience long for the faith that stands in the power,
and the obedience that flows from the power! "`Oh, teach me your statutes;
show me the pure path of obedience in the way of life;
guide my feet in the way everlasting!
Oh, write your fear in my heart that I may not depart from you.
Create a clean heart in me, and put your Spirit within me to be my strength!
Oh, continue your loving­kindness to those that know you,
and your righteousness to the upright in heart!`"
Oh, what unutterable breathings daily issue out from
the broken spirit towards the spring of its life!

Fifthly, they bring into a pure frame, into a cleanness of the inside.
"`Cleanse first the inside of the cup and platter,`" said Christ to the Pharisees;
and this he also does in his true disciples.
"`With the mind I serve the law of God,`" said Paul when he cried out,
"`Oh wretched man that I am, who shall deliver?`"
It is not conceivable what purity of heart God can form
in his Israel by the fire which he kindles in his Zion,
and by the furnace which he sets up in his Jerusalem.
For though in the furnace the dross still appears (the sight
of which is apt to grieve and afflict the precious heart),
yet the melting and purifying sweetly go on,
and the soul that abides the heat is effectually cleansed thereby.
Indeed, this cleansing is very manifest afterwards,
when righteousness springs up with its quiet fruit.
But this cannot be discerned while the flames are still
discovering and taking hold of the unrighteousness.

Sixthly, they bring into a patient frame,
fit to bear the reproaches and persecutions from the world, who,
in the midst of all this weakness, misery, and distress, lay loads upon the poor soul,
persecuting him whom God has smitten,
and speaking to the grief of him whom God has wounded.
God smites for lack of obedience, for too much propensity to please the world,
for not coming soon enough out of their customs, vanities, earthly ways and worships.
And just as soon as the heart and conduct are given up in obedience to the Lord,
then the world is discontent, and they smite and persecute because of the obedience.
Now the more the spirit is broken by the hand of the Lord,
and taught thereby to fear him,
and the less strength it has in itself to
grapple with the persecuting spirit of the world,
the fitter it is to stand in God's counsel.
Yes, it is now more apt to wait for his strength and preservation,
which is able to bear up its head above all the rage and swelling of
the waters of the worldly spirit in the men of this world.

Much more might be said, but this may suffice.
What is lacking here will be felt inwardly,
as the soul waits on God in the leadings of his Spirit, through the teachings,
chastisements, and distresses of the law.

[.discourse-part]
Question:
With what kind of things does the Lord exercise the spirits of his Israel in
order to bring their hearts into these and other similar precious frames?

[.discourse-part]
Answer: With several sorts and kinds of things, both outward and inward, such as: First,
with oppositions, reproaches, and interruptions from the earthly part,
both in the men of this world, and in themselves.
There is an abundance within, and an abundance without, that will seek to resist,
disdain, and interrupt the work of God in the heart.
Yes, there is much that will oppose and withstand that which he has begotten there,
and his leadings of it, and its obedience to him.

Secondly, with temptations from the enemy, even of many kinds, natures,
and degrees, according to the present temper and condition of the soul.
There are temptations to doubt, and so despair,
or to be confident in the flesh from knowledge received,
outside of the pure fear and fresh feeling of the life.
There are temptations to halt or draw back, or to be over-hasty and forward,
and so either to fail to obey and act for God,
or to act in that will and wisdom which is against God.
Now these, with other similar temptations, are very numerous, frequent,
and sometimes very violent and impetuous.

Thirdly, by withdrawings of the life and sweet presence of God from the soul.
These are very frequent from the Lord towards his people,
insomuch as he is called by this title,
"`The God that hides his face from the house of Jacob.`"
Isa. 8:17,45:15.

Fourthly, by the buffeting and prevailing of the enemy.
When the Spirit is grieved, and the life wounded and withdrawn inward,
then does the enemy often get ground, and give wounds and cause bruises to the soul.
He not only tempts, but finds entrance,
and then takes in the snare the bird which once escaped and was delivered.

Fifthly, by doubts, fears,
and confused reasonings con­cerning the voice of God and the voice of the enemy.
In the hour of darkness (when the Lord sees good to allow the power of darkness,
and to withdraw the beams of his light),
how can that be clearly distinguished which alone is known and seen in the light?
How can the motions, drawings, and pure,
low workings of the life be discerned from the
false images and transformings of the enemy?
Oh, the misery and anguish of the poor soul in this condition!
How is the poor, upright, heart pained between faith and unbelief,
between obedience and disobedience, not knowing when it is drawn forward or backward,
or by whom.

[.discourse-part]
Question: When do these exercises begin, and how long do they continue?

[.discourse-part]
Answer: The Lord begins to exercise the soul even in Egypt.
For after the promise of deliverance from spiritual Pharaoh, the bonds increase,
the yoke grows more heavy, and Pharaoh grows more violent and furious.
Indeed, the captivity increases much, and there is no sight of redemption at all,
except to that eye which is weak and easily overborne in Israel.
But the exercises are much more full and sharp in the wilderness,
where Israel is led about, tried, afflicted, consumed day by day,
as if he should never come to the holy land, nor any of Israel be left to enter therein.
Yes, in Canaan also, in the rich possession, in the plenteous overflowings of the life,
there is still something left to try Israel, and to bring him low,
if at any time he is exalted with the glory and fullness of his own state,
and begins to forget his God.

[.discourse-part]
Question: Why does God exercise his Israel in this way?
Why does he lead them in such a knotty way,
and not in a more easy and ready way toward the
everlasting possession and the fullness thereof?

[.discourse-part]
Answer: Because their state and condition require it.
They could not otherwise be so purified and fitted for the life.
Their vessels would not be so enlarged as to receive the life,
nor could they safely enjoy it, were it not for this course of wisdom,
wherein God exercises and tries every cranny of their spirits,
until he has perfected them and stopped up the entrance of death everywhere.

[.discourse-part]
Question: How do these exercises purify and enlarge them?

[.discourse-part]
Answer: First, they try the strength and virtue of the life in them,
and uncover to them their further need of it.
In the time of the soul's prosperity there seems to be enough,
but the day of distress makes manifest the state and condition as it is.
Then the faith, the love, the patience, the meekness, the constancy,
and chasteness to the spouse (loving him, and cleaving to him above all,
and in all) many times are found to be less than they were judged to be.

Secondly, it brings to a waiting on God for support, and to receive more from him.
Then the life breathes vigorously, and the soul longs after, cleaves to,
and sees its need both of the presence and increase of the virtue of the life.
Then he that was rich becomes poor, and he that was full becomes empty and nothing.
Yes, he that had enough to live on and to spare, is now pressed with hunger, lack,
and poverty.

Thirdly, it prepares for a clearer entrance into, and safer enjoyment of,
the fullness.
As the soul is more emptied of the strength and riches it received from God,
so it is more prepared to enter into, and live in, the Pure Being itself.
For nothing can live there which veils.
In the life God was, and is, and is to be all in all forever.
Therefore, that which enters there, and lives and abides there, must be poor, empty,
naked, nothing, and remain nothing forever.
But as it gathers anything from the fullness, and becomes anything in itself,
it is thereby shut out.

[.discourse-part]
Question:
How does God heal and bind up that which he has wounded and
broken to pieces with his various and frequent exercises?

[.discourse-part]
Answer:
By opening the power of the endless life in the vessel
which he has thoroughly purified and prepared,
and filling it with the power.
The free power of life--__that__ is the gospel; and this gospel was prophesied to the meek,
to the broken-hearted, and to the cleansed.
So that when the work of cleansing is finished,
and the wound made wide enough and kept open long enough,
and the death to the first husband fully accomplished (Rom. 7:4),
then the perfect oil is perfectly poured in,
and everlasting health and salvation is obtained.
This is the end which God aims at in the visitations and leadings of his seed.
Happy are they that pass through the vale of misery,
and drink off the dregs of the "`cup of trembling,`"
not fainting nor sitting down by the way,
but following the faithful Shepherd and Leader of Israel, till they arrive here.

[.discourse-part]
Question: What is the great danger in the path of life?

[.discourse-part]
Answer:
The great danger is of ascending a step higher
than the present state and condition will bear.
By this means the aspiring mind gets up and is exalted,
and holds something received from the life outside of
the pure fear which preserves the heart clean,
and outside of the sensible feeling which keeps the heart fresh and living to God.
Then the simplicity is betrayed, and a wrong spirit lives, and a wrong eye is opened,
so that there is nothing now but whoredom from the life.
Indeed the heart becomes exalted and conceited in the way of its whoredoms,
as if it were the pure bed and most excellent way of enjoyment of the life.

[.discourse-part]
Question: What is the way of preservation from this?

[.discourse-part]
Answer: Watching to the life, keeping low in the fear and close to the feeling.
Here the aspirer is shut out, or soon spied as he begins to enter,
and then the living cross is received which crucifies and drives him back.
And indeed there is no way of safety in the soul's travels towards the enjoyment of life,
except under the cross to that spirit and nature
which desires to intrude into the things of God,
and to please itself and be something there, and yet forgets the pure everlasting Spring,
because of its adultery with that which streams forth from it.

Man was made for God to be a vessel of his pleasure, to receive his contentment,
enjoyment, and happiness by reflection.
So that man's proper work was to watch to the spring from whence he came,
in order to be disposed of, ordered, and to live according to his pleasure.
This was natural to man before his fall,
till a corrupt spirit (by deceit) entered him and corrupted him.
And while anything of that corrupt spirit or fallen nature remains,
man is apt to aspire in the self-hood,
and to seek the enjoyment of what comes from the fountain (yes,
even the fountain itself) in and according to the will and wisdom of the self-hood.
And here do even experienced travelers lose their way,
falling from their portion in the land of life, and from their enjoyments of the life,
into the earthly and sensual spirit,
holding their wisdom and riches there in the earthly part,
not knowing they have moved their habitation there.

He that reads these things, let him not strive to comprehend them,
but rather be content with what he livingly feels,
and what is suitable to his present state.
And as the life grows in him, and he in the life,
and he comes to meet with the things and exercises here spoken of,
then the words and experiences concerning them will open of themselves to him.

=== Counsel for the Spiritual Traveler

Now he that would travel safely in spirit unto the land of life,
let him wait to have the following things written in his heart by the finger of God,
and to know the true sense and weight of them preserved fresh within him.

First, it is the free grace of God which begins the work of redemption,
which causes the light to shine,
which works the repentance or turning from the dead state, and also works the belief in,
and turning towards, the living God.

Secondly,
it is the same grace alone that can preserve and cause the plant of grace to grow.
If there is a withdrawing of the light, a withholding of the free influence,
then that which depends upon it cannot retain its freshness.
This the Lord may do as often as he pleases, for the chastisement of the rebellious part,
or for the trial of his pure life and virtue in his plants.

Thirdly, the grace of God visiting the soul in the death, in the darkness,
in the fallen state, begets life anew in it,
and makes it in some measure "`light in the Lord.`"
Yes, this grace opens an eye in the soul to see the things of God,
and an ear to hear and distinguish between the sound of life and of death,
and it works in the heart to turn from and refuse all vanity,
and to turn towards and abide in the living substance.

Fourthly, the Spirit of God carries on the work of redemp­tion by drawing,
leading, and acting upon the quickened soul,
and by exercising that which he has begotten in the life, under the law of the life.
Thus the life draws the soul daily nearer and nearer towards the everlasting spring,
and away from the fading emptiness of sin, vanity, and the creature-hood.
And the soul, by the enlivening virtue, daily follows on after the life, in the leadings,
spirit, and power thereof.
There is a living soul begotten by the virtue of the grace,
and the living soul daily lives in the grace,
and travels in the virtue thereof from the unbelief to the faith,
from the enmity to the love, from the perverseness to the straitness,
from the iniquity to the righteousness.
Yes, the living soul travels on from all the territories of the darkness,
and also from the weak measures and degrees of the grace and life,
towards the fullness itself, even until it is perfectly centered in, and filled with,
the life.

Fifthly,
where there is a stopping of the virtue received from
the grace due to a lack of response in the heart,
there the work of redemption is stopped.
If the soul does not follow in the drawing, the drawing is lost.
If the ear does not open to hear the voice of the Word,
or if it is not mixed with faith in the heart that is hearing, it proves ineffectual.
If strength issues forth from the Lord,
and yet the soul does not receive the strength which issues forth and bubbles up in it,
or does not respond by giving up to it and traveling on,
then the soul abides where it was before (if indeed it does not retire
further back from that state and condition to which the life had advanced it)
For if the virtue of the life and grace is refused,
then an advantage is given to death to re-enter and
gain ground by its own contrary virtue and power.

Sixthly,
mark therefore diligently how the Lord does carry on
the dispensation of his love and free grace,
even as if there were much done by the strength and diligence of the creature.
How the creature wounds itself by repentance!
How it strives to believe!
How it wrestles against enemies, and for the influences of the grace,
and to keep up the hope, and keep out the distrust!
What strict watching and waiting is known,
even as if the creature did work out its whole salvation!
But though the creature seems to do much itself (having received life from the grace,
and now acting abundantly towards God in the grace),
yet it is the grace and virtue which comes from the Creator (who is
also the Redeemer) which indeed does all.
For though the creature truly repent, and turn from the darkness with its whole heart,
yet this repentance comes from the virtue which flows from the grace,
and not from the creature who receives the grace.
So it is likewise in the faith, the love, the obedience, the meekness, the patience,
the watching, the waiting, the hoping, etc.
Yes, the very receiving of grace is not of the creature, but of the grace.
For the creature is dead until it be visited by the grace,
and by the visitation of the grace alone it is made alive and able to receive.

Behold then the mystery of redemption.
God is all in redemption.
God does all in redemption, even the whole work,
as fully as he does in creation (for it is a new creation).
Yet the creature that is made alive and renewed is in unity with him in his operations. Phil. 2:12-13.
He whose eyes are opened can read the mystery,
and in true understanding say (if he has been led this far),
"`I am able to do all things through Christ who strengthens me; yet not I,
but the grace of God in me.`"

Now, to bring the creature to this,
the Lord exercises it daily in obedience unto him,
in the life and virtue which flows forth from him,
causing the creature to feel its weakness,
and to forget its aspirations to live of itself
outside of a sensible dependence upon the spring.
And indeed, the virtue that comes from God can alone respond to God,
and the creature is only accepted as it is found
with and in the Spring and Father of life.

[.discourse-part]
Question: But if the work of redemption is wrought by God's creating power,
why does it meet with so many hindrances and interruptions,
and is sometimes even overturned?
Can anything stop God's creating power?

[.discourse-part]
Answer: There are three things in redemption:

First, there is the issuing forth of the free grace, love, virtue,
and divine power towards the creature.

Secondly, there is the opening of the state of the creature thereby,
convincing and drawing it out of the alienation from the life,
towards unity with the life.

Thirdly, there is the following of the creature after the life,
in the quickening virtue of the drawings, through all the snares, temptations,
diversions and oppositions of the enemy.

Now,
there is no hindering of the issuing forth of the free grace towards the creature,
nor of the creature's convictions and inclinations to
follow the Lord which necessarily ensue thereupon.
But the pursuit and progress of the creature (or its abiding with the
quickening virtue and power) may be interrupted and diverted many ways,
and so the creature may be drawn from under the influence of the free covenant.
For though the covenant is free,
yet the creature only partakes of it as it is drawn into it, and preserved in it.
Therefore let those fear who feel the power and redeeming virtue, and know that,
despite the free and certain promise to the seed,
still the creature is as clay in the hands of the potter,
and may be made a vessel of honor or dishonor,
as the potter pleases to favor or take occasion against it.

=== The Three-Fold State of Man

First, there is a Gentile state, or state of nature.

Secondly, there is a Jew state, or the administration of the law,
wherein God takes man under his own tuition, making known his will to him,
and requiring obedience of him.
And not only this, but he also directs him to the inward teacher,
and to the principle of the pure fear,
which is the place of wisdom's teaching and instructions.

Thirdly, there is a gospel state, or a state of faith,
where the seed is raised and lives;
yes the seed that does the will and receives the promise is known, enjoyed,
and felt springing up within.

Now in all these, the law, the light, the life, the wisdom, the power,
are one and the same, but the administrations are different.

In the Gentile state, or state of nature,
the light which man receives (to discover evil,
and work toward the good) is of the Spirit and by virtue of the promise.
For he would have been everlastingly shut up in
the darkness had it not been for the promise.
And truly, it is for the sake of the promise, and from the free grace,
that man has any visitation in his natural state, or any desires after,
or leadings towards, the good, and away from the evil.
Indeed, these do not spring, nor can they spring, from the corrupted nature,
but only from the free fountain of new life.

In the law state, the light grows more clear.
The teacher is here discerned and acknowledged, and his drawings, warnings, instructions,
and reproofs are felt more distinctly,
and the soul (that is watchful) is continually exercised therein.

In the gospel state, the principle of life is raised, the promised seed has come,
the power which does the will is received,
and the light of life is entering into and possessing the vessel.

Now this is the whole duty of man,
to wait upon the ministration of the life in his present state,
whether he be yet in the state of nature, or under the law, or under grace.
He must know from where his redemption springs,
and must wait upon the redeeming arm for the beginnings, the progress,
and the perfecting of it.
And if he has come to the feeling of that virtue, it is enough.
Or if he is kept longing or panting after it, it is well.
Indeed, if there is only a desire in him after a true thirst, there is hope; yes,
if there is even the least feeling of his dead, barren, and senseless state,
then there is some life in him which the Lord loves,
and He will find occasion to express his compassion towards it.
Yes, even the one that feels wholly in darkness, and shut up in the pit,
still the Lord has compassion towards him, and after many days may be pleased to visit.
Oh, the height, the depth, the length,
the breadth of the riches of the mercy and love of God!
Who knows his yearning towards souls, and his ways of visiting and redeeming?
O my soul, hope in the Lord forevermore,
and do not stop breathing towards him till you and his
whole creation are filled and satisfied with him,
and find the full breath of life in him forever!

=== To Those Who Claim to Lack Power from God

[.discourse-part]
Question: What is God?

[.discourse-part]
Answer: He is the fountain of beings and natures,
the inward substance of all that appears outwardly, the one who creates, upholds,
consumes, and brings to nothing, as he pleases.

[.discourse-part]
Question: What are his commandments?

[.discourse-part]
Answer: They are very many, but they all may be referred to these two heads:
To love God above all, and to love one's neighbor as one's self,
in every respect doing unto him as one would like to be done to by him in the like case.

[.discourse-part]
Question: How may man perform these?

[.discourse-part]
Answer: Only by receiving a seed of life from God, and keeping close to it.

[.discourse-part]
Question: How may a man receive a seed of life from God?

[.discourse-part]
Answer: God is near to every man with the breath of his life,
breathing upon him at times according to his pleasure.
Whenever man's spirit opens unto this life, and drinks it in,
it becomes a seed of life in him, overspreading and leavening him up to eternal life.

[.discourse-part]
Question: What hinders man from receiving this seed of life, and from keeping close to it?

[.discourse-part]
Answer: A fleshly seed, which is contrary to the knowledge, fear,
and obedience of the Lord, and to all that springs from the power of his life.

[.discourse-part]
Question: How came this fleshly seed to be found in man?

[.discourse-part]
Answer: It was sown there by the enemy of man's soul;
man giving him entrance into his spirit,
by hearkening to his suggestions and allurements.

[.discourse-part]
Question: What help does man have against this fleshly seed?

[.discourse-part]
Answer: None of himself; but being freely touched by the seed of life,
and tasting thereof,
he is to wait on God's mercy and grace for the manifestation of his light and power,
to discover to him the evil nature and course of his own heart,
and to cut down his corrupt desires, reasonings, and imaginations.

[.discourse-part]
Question: How may a man come to believe in this seed of life?

[.discourse-part]
Answer: In experiencing its nature, in waiting to experience something begotten by it.
In this its light springs, its life springs, its love springs, its hidden power appears,
and its preserving wisdom and goodness are made manifest to the soul that clings to it.

[.discourse-part]
Question: How may a man come to obey this seed?

[.discourse-part]
Answer: In the faith, in the seeing of it, in the clinging to it,
the strength issues forth from the seed into the creature
which makes him able to perform all that it calls for.

[.discourse-part]
Question: Why do persons who come to a true beginning of life,
and to earnest breathings after God, feel so weak and complain so much for lack of power?

[.discourse-part]
Answer: From the enemy's interposing of reasonings between them and their faith.
The darkness, the principle of unbelief, lies near,
and is raising mud (as much as possible) between the seed of life and the soul.
And so far as it can come between these,
it disturbs both the motions of the soul towards its spring of life,
and also the spring's clear bubbling up in and running through the soul.

[.discourse-part]
Question: What does God require of man?

[.discourse-part]
Answer: He requires of man repentance, faith, and obedience.
That he should turn at his call, from the darkness to the light;
that he should trust in and cleave to the light,
and believe the spirit of darkness no more; and lastly, that he should obey the light,
follow the light, walk in the footsteps of the living towards the land of light.

[.discourse-part]
Question: How can man do this?

[.discourse-part]
Answer: Of himself he cannot; but being touched, being quickened by the eternal power,
being turned by a secret virtue and stirring of the life in his heart,
then he can turn towards the one who turns him.
Being drawn by the life, by the power, he can follow after the life and after the power.
Finding the sweetness of the living vine, and his soul made alive by the sap of the vine,
his heart can now cleave to and abide in the vine and bring forth the
fruit of the living faith and obedience to the vinedresser.

Now mark this:
Is it possible for any man to come to eternal rest if he travels not in the true path?
Is there any path besides the repentance, faith, and obedience in the living Spirit?
Is there another way for the child begotten by the eternal power other than
to be taught by the Father to abide and walk in the life and in the power?

God puts forth his hand all the day long to fetch home lost man.
He has given him a talent, a living talent, which is able to bring man into life,
and to bring forth the fruits of life in man.
Man overlooks this talent and does not join his heart to it,
nor bring forth the fruits of life to the giver,
but rather cries out that he lacks power.
He cries, "`What am I?`" "`What can I do?`"
"`Can I cleanse my own heart?
"`Can I kill my own corruptions?`"
"`Can I make myself alive?`" etc.

Now mark this too: There have been several dispensations of God to mankind;
in all of which, man (of himself) falls short of the life, of the power, of the glory,
and comes under condemnation.
God lays the blame on man for not hearkening, for not believing, for not walking with him.
Man lays the blame on God, and says he lacks power.
Now consider those who are not obedient to the light (which
light they cannot but confess to shine in their heart,
and often to reprove them), and ask them why they do not obey it?
Is not this their plea, that they lack power?
But let men consider, will this stand before the throne of God?
This is the condemnation, that men do not believe the light of life,
do not obey the gospel of our Lord Jesus Christ,
do not trust and follow the light which would lead them to life.
Rather they trust and follow the darkness, which leads into death,
and into everlasting condemnation.
Man's plea is that he lacks power to do so.
Is this true?

I confess that the power does not flow forth to man in the way that he expects it.
The power of life works man out of death in a secret way,
and it begins in him as weakness.
At first there is all the strength and power of
the enemy against the work of God in the heart.
And there is but a little thing (like a grain of mustard seed), a weak thing,
a foolish thing, there to overcome all this; and yet in this little thing is the power.
And here is the great deceit of man: he looks for a great,
manifest power in or upon him to begin with,
and does not see how the power is in the little weak stirrings of life in the heart.
The power is in the rising up of something
against the mighty strength of corruption in him,
which he must turn towards, cleave to, and wait upon.
The strength of the Lord will be made manifest in its season,
and he will be drawn nearer and nearer to the Lord,
and his enemies will be overcome and fall in a way he knows not.
But he that waits for such a mighty appearance of power at first,
looking to begin in this way and thus be preserved and carried on,
this one cannot walk in the eternal path.
For God's power springs up as weakness,
and leads on and overcomes enemies in a mysterious way of working,
and not in such a manifest and direct way of conquest, as man's wisdom expects.

The seed of the kingdom is sown and grows up in
a way that man does not understand,
and the power appears and works in it in a way that he is not aware of.
Man looks for the kingdom, the power, and the life in a way of his observation,
answerable to the thoughts and expectations of his heart.
But it never comes this way, but rather in the way of its own eternal motion.
It springs in the hearts of many, and they overlook the thing, and turn from it daily,
not knowing its true way of appearance, but expecting it some other way.
And thus the enemy holds them in the bonds of death,
and they are captives in the strange land,
refusing the Prince of life in his daily offers of life,
because they do not look for him this way, but after another way and manner.
And until this eye of observation be put out in them,
they can never clearly see the appearance of the Savior to them,
nor feel the efficacy of his saving of them from that from which none but he can deliver.

=== The Right Knowledge of the Things of God

There are yet some things that lie weighty upon my heart to lay before you
which may be serviceable and helpful to you in your present condition.
They are four propositions, relating to the right knowledge of the things of God,
which are these following:

[.numbered]
_First,_ that the knowledge of the things of God comes from the Spirit.
As the Scriptures themselves came from the Spirit,
so the true knowledge of them is alone given to
any man which receives it by the same Spirit.
And no man living can know the meaning of the words which the Spirit spoke,
except as the same Spirit which spoke them gives the meaning of them.

[.numbered]
_Secondly,_ that the knowledge of God (the living knowledge,
the serviceable knowledge) is alone held in the Spirit,
and in the birth which is of the Spirit.
Man's natural part is not the true treasury,
nor is man's reason to be master of any of the things of God's Spirit.
Rather, that which holds the knowledge of the kingdom, the grace of the kingdom,
the living experiences, is that which is born of the seed of the kingdom;
and man's reason is forever to be shut out of the things of God except where it bows,
is limited, and subjected to them.

[.numbered]
_Thirdly,_ that the knowledge received from the Spirit is still to be tried by the Spirit.
The Spirit alone can keep it living,
and the Spirit alone can tell whether the life and virtue is still in it,
or whether death has caught it.
Only the Spirit can discern whether it be the manna fit for the soul's food,
or the manna once given but now corrupted.
Oh my dear friends, wait to understand my experience concerning this thing,
which is this: That which I had certainly received from God,
and which the true birth at first fed upon, the earthly birth then sought to catch,
lay hold of, and treasure up to feed upon at another time.
Likewise in my reading of the Scriptures,
I often fell into the great snare of reading in my own
will and gathering things in my own understanding,
and thereby growing wise concerning the things of God after the flesh.
For though at that time I was not without living knowledge and experiences of God,
yet I knew not how to turn from the death, nor to keep to the life.
And so the bad, the lean, the earthly, the ill-favored,
overgrew the good and well-pleasing to God, and brought it into bitter misery and death.
Oh that you knew being begotten of the will of the Father,
and keeping to the will of the Father, and receiving the bread daily from his hand!
That which man conceives concerning the Scriptures is not the pure milk of the Word,
for only that which the breasts give out has the immediate life, virtue,
and true nourishment in it.
And this must be returned back into the divine treasury,
and not held in the earthly part, in the earthly will and understanding,
but received from the life again when it is again needed.
Yes, this I have often known, that when I have been in great distress,
I have received fresh comfort from the Lord; but running to it afterwards,
it never was able to comfort me, but rather more deeply wounded me.
In this way the Lord has been teaching me to live upon himself,
and not upon anything received from him, but upon the life itself, the mercy,
the good pleasure, which comes directly from the living bread daily.

[.numbered]
_Fourthly,_ it is easy receiving a knowledge in the earthly part, in the earthly wisdom,
apart from the Spirit and living virtue.
When one reads a scripture, it is easy conceiving and apprehending a meaning one's self,
or taking in another man's meaning;
but it is hard abstaining from all conceivings and reasonings of the mind,
and waiting for the pure will and opening of the Spirit.
Also it is easy retaining knowledge and making use of
it in the will and wisdom of the earthly mind,
for both these are natural; but it is hard denying the reason,
the thoughts and imaginations, and watching to the Spirit.

O professors, wait for the living appearance of God!
Wait for the freshness of his Spirit in your spirits,
so that in that which comes from the Spirit you may know the Spirit,
and may also know how to turn to him and abide with him.
Watch against that wisdom in yourselves which in all ages and
generations is eternally shut out of the things of the kingdom,
although it may gather and hold a vast knowledge of the
things of the kingdom in the earthly treasury.
The fleshly Israel has the wisdom of the letter, but spiritual Israel the wisdom, virtue,
and life of the Spirit in all ages and generations.
And though he that is born after the flesh despises him who is born after the Spirit,
yet this one is God's heir; and the bond-woman, the earthly wisdom,
with all her children (even the greatest giants in knowledge, profession of religion,
and Scripture observations), must be cast out, and not inherit the land of life.
This is written that the seed might be raised in you by the power,
which is to inherit the life eternal,
and that you not find your souls deceived when the light of that day fully opens,
which has already dawned.

I was in a poor, low condition, when the Lord formerly visited me.
I was as lost, as undone, as miserable as any.
Whatever knowledge, whatever life,
whatever precious virtue I then received was from God's grace; but it was still his own,
and I found that he could call for it at his pleasure.
And surely,
he who has received from the fountain ought to trust and to
give back again to the fountain when he calls for it,
and then to remain empty, naked, desolate, until he be again freely visited.
This is a hard lesson, who can learn it?
Who can trust his life to the fountain and lie open to whatever follows?
Yet this did the Lord require of me.
And since my heart was not willing to part with my life,
but rather strove to retain it and to grow in
this first experience of grace unto perfection,
he broke it after an unutterable manner,
and brought such misery and desolation upon me as I could not possibly have suspected.
And now he is teaching me to live more fully upon his grace, or rather upon the spring,
where I am nothing, where I can be nothing forever,
but he is and will be what he will be, and when he will be.
And now nothing in me can be satisfied with him, except what is of him, and lives in him.
And here all that I have known, or formerly tasted of him,
springs up again at his pleasure; and I drink of the old wine, and also of the new,
but I have nothing at my own disposal.
And when I cling to anything, or seek to be anything, I lose the spring,
and am corrected for my backsliding and adultery of spirit.
But then I am again visited with fresh love,
and the springing up of fresh power and life,
and fresh visitations of the rich mercy and grace which
the everlasting fountain naturally opens in its own.

The pearl is exceedingly rich, the treasure of life unutterable.
He that will possess it must sell all for it, even all his lusts and corruptions,
indeed all the riches of his nature (the best of his will,
the best of his wisdom most refined).
Not only this, but all the riches of his spirit,
all that he has held or can hold outside of the life.
Then, when he is poor in spirit, and has nothing in himself but emptiness,
nothing so much as to receive or retain the life except what is formed, grows up in,
and is preserved in the life, according to its own mere will and good pleasure,
then only is he fit to be comprehended and brought forth in the eternal spring.
Perfectly happy is he who is perfectly possessed by the spring;
yet he is not without a proportion of blessedness also
who is mourning after it and traveling towards it.
This can never be attained by the natural part retaining the
letter of any spiritual revelation or knowledge;
but only by beginning in the eternal virtue, abiding in it,
and traveling from death to death, and from life to life,
until all be slain which is to die and perish in the way,
and all be raised and perfected which is to receive and
live in the kingdom and crown of life forever.
This crown the Lord lays before all to run after,
but none but the spiritual seed (begotten of and abiding in the Spirit) can obtain it.
Mind then this brief sum:

The lost creature, the undone creature,
is graciously sought after and visited by the fountain of its life and being.

Being visited with the mercy and grace, and impressed,
it receives something of the grace and living virtue from the fountain.

Having received something,
the creature is apt to retain it in the creaturely vessel (even in his own will,
and seek to enlarge his own wisdom thereby, and so to become something again in himself),
forgetting the spring.

As the creature retains anything in the natural part,
outside of the immediate experience of the living virtue, it corrupts,
it adulterates from the living spring.

And that with which any one has thus adulterated, must be taken from him,
and he be made dead to it, and it to him, before he can be recovered into a living state,
fit to enjoy what he formerly received,
or further to receive of and grow up in the fresh, living virtue.
