== Chapter XIII. The Sum and Substance of True Religion

[.discourse-part]
Inquiry 1: What is true religion?
Is it a gift from God bestowed on those whom he begets by the power of his life?
Or is it a profession of worship in the nature of this world
which a man may attain to by natural means and efforts?

[.discourse-part]
Inquiry 2: What is the sum and substance of the true religion?
Is it not love from a seed of life?
Is it not a travel out of the enmity of the creature into the love of God?
Does not the light of life spring in the love, and gather into the love?
Does not Christ, revealed in the heart, and leavening the heart with the savor of life,
teach love towards enemies, to bear with them in love, to seek them in love,
to forgive them in love, to pray for them in love,
to wish good to them and wrestle with God for mercy towards them,
even while they are hating and persecuting?

[.discourse-part]
Inquiry 3:
Are the Catholics or Protestants or any other
sort of religious persons found in this love?
Do they manifest it by their discipleship to Christ and the power of Christ in them?
Or rather,
do they set up their several outward forms and maintain
them in wrath and enmity against each other?
Indeed, would they not destroy each other if they could?
Surely this spirit is in too many of them!
And does this not give a strong evidence against their religion,
that it has but an outward form and not the true power in it?
Does it not show that in heart they are not the disciples of Christ?
For if they were his disciples, they would by him learn to love.

[.discourse-part]
Inquiry 4: Whether any form of religion (if not held in the power of life,
and subjected to the power) does not fight against the power,
keeping up an outside show without the substance, and thereby crushing the substance?
What form of religion at this day in the world allows the love to grow,
and the life to lead and rule in the love,
and the Lord of life to exercise his authority in the hearts and consciences of men?
This is for lack of power within, and because of outward forms forcibly set up;
for the religion of the gospel began in Spirit and in power,
and it never can be restored and preserved but by the same Spirit and power.
The splitting of the Protestants from the Catholics was no
further good than it was held in the power of the life;
and the splitting of others from the Protestants was no
further good than it was begun and held in the same power.
Even though a party begin uprightly by a true and clear leading of the Spirit of God,
yet just as soon as it starts to invent and turn aside to a form of its own choosing,
it is immediately corrupted, being upheld by the reasonings and understandings of men.

[.discourse-part]
Inquiry 5:
Whether the power of true religion (and true love)
if it were raised up and restored again,
would make the world happier, and set everything in its proper place,
both inwardly and outwardly?
Is not sense an excellent thing in man if it be guided by reason?
And is not reason a much more excellent thing if it be guided by the inward seed of life?
But sense left to itself, without the guidance of reason, how brutish it is!
And reason left to itself, without the guidance of the life, falls below sense.
How cruel, how blind, how selfish,
how unrighteous is the man that follows the dictates of his own corrupt reason,
without knowing and becoming subject to that which
should enlighten it and give him the right use of it!

[.discourse-part]
Inquiry 6: When God restores true religion and raises it up in power,
whether then the forms and ways of worship without the
power must of necessity wither and decay?
When the power first appeared in the dispensation of the gospel,
did not all the shadows of Moses`' ceremonies fly away and vanish before it?
And when it appears again,
shall not all the shadows and inventions of man which have sprung up since then (in
the time of the night) vanish before the brightness of the light of the day?
Where the power arises in any heart, what becomes of man and all that springs from him?
Where is his wisdom?
Where is his former worship?
What becomes of all his forms of religion?
Do they not all dissolve and come to nothing?
And does not he become as a little child to be formed again in the power of life,
and born of the Spirit of life, that he may enter into God`'s kingdom?
Do not all the old things pass away and new things spring up from the seed of life,
which God sows and preserves in the heart by his power?

Now who is wise to understand these things?
Who has the key to open the mysteries of life?
Who knows the times and seasons (the times and seasons of forms,
and the times and seasons of life and power)?
Who sees what God is about to do in the world,
and prepares his heart for his administrations on the earth?
Who is a friend to God, and to mankind, and willing to travel in spirit out of this dark,
corrupt, earthly state of things, into the heavenly nature and being?
This he cannot do by his own strength and reason,
but only by the power and leadings of God revealed in him, an inward principle of life.
And he that will follow this must feel it in his heart,
and then turn his back upon the earthly nature and wisdom,
and war against his own corrupt reasonings in and with the light of life as
it arises and is further and further made manifest in his heart,
through the grace and mercy of God.
In this way God offers help to miserable, lost man,
to redeem him out of his misery and undone state.

Man has a time here allotted him by God; and when the time is over,
it is determined concerning him.
He is a seedsman in this world, and what he sows here he must reap hereafter.
He sows either to the flesh or to the Spirit; either to his own will or to God`'s will.
He follows either the ways of his own heart or of God`'s Spirit.
He experiences either the power of true religion
and is thereby renewed and fitted for God,
or he contents himself with a form of godliness without the power,
and in effect remains what he was.

He that is renewed, he that is changed in heart and life,
he that sows to the will and nature of God, shall inherit life with God.
He that lives in a form of religion without the power,
and follows the vanities of his own mind, shall be cut off from God,
and lie down in sorrow and anguish of soul.
Such a one will bitterly bewail his mis-spent time and the losing of
his soul`'s life and happiness for a few days of enjoying the earthly
nature and spirit in its corrupt and degenerated state.

O Man, whoever you are that are drowned in the lusts and pleasures of this world,
which answer only to the sensual and corrupt part!
Oh remember that you have also a precious soul,
which needs redemption by the power of God to make you happy!
And one day this soul will be awakened in you, and when it is awakened,
it will feel its lack of God.
Now is the day of God`'s stretching out his arm to you!
Oh, do not let it slip away!
For if you do, terrible will the day of your awakening be;
and your misery will be unavoidable and intolerable.
And if now the pains of your body are so dreadful to you,
what will the tearing of your soul be by the wrath of the Almighty?
Lay it to heart, and retire inwardly,
seeking to feel something of God gathering and guiding your soul out of your
own worldly nature and spirit and into the nature and life of his Spirit.
For the spirit of man returns to God that gave it, as well as the body to the earth.
And then the Lord appoints it to its proper place,
which is according to the nature it is found in.
If it be wheat, if it be of the renewed nature,
if it has taken up the cross and followed Christ in the regeneration,
then he gathers it into his barn.
If it be of the chaffy nature, of the earthly spirit,
the mind remaining unrenewed and unreconciled to the nature of God,
then to the unquenchable fire (even the fire which will burn
and scorch unquenchably) and to the worm which dies not,
but gnaws perpetually and brings to mind all the former vanity
and mis-spent time to increase the heat and flames of the fire.
Oh, what soul,
if it were not bewitched and lulled into a dead
sleep by the stupefying spirit of this world,
would run so great a hazard for the enjoying of
a few momentary pleasures in the sensual part?
And who would knowingly lose the inward enjoyment of
peace and reconciliation with God here,
and the pleasures of his kingdom of true glory afterwards?

=== The Persuasions of Reason and Faith

There is the natural man, and the spiritual man;
and there are the persuasions of each in and about matters of religion.
There is the persuasion of reason and the persuasion of faith.
The persuasion of reason is that belief which man receives into his
mind or heart from the exercise of the reasoning faculty;
and this persuasion in matters of religion is but man`'s opinion or judgment.
Now, no matter how certain or infallible this persuasion appears to him,
yet it may be shaken by a demonstration or evidence of a higher kind and nature.

The persuasion of faith is that belief which the new creature receives in
the renewed mind from the evidence and demonstration of the Spirit.
This persuasion opens and manifests the things of the
Spirit unto the mind that is begotten and renewed by it.

Now the lowest persuasion of faith is higher, and of a more noble nature,
than the highest persuasion of reason.
True faith is of a higher principle and of a
deeper nature and ground than man`'s reason is.
But because such faith does not appear within man`'s sphere, but rather out of it,
and it is contrary to the line and reach of his wisdom,
it is accounted by him foolishness and madness.
So it is that the wisdom of God (and the children
thereof) are judged and condemned by man in this day.

And how can it be otherwise?
How can the wisdom of man not judge as foolishness something
whose beauty and excellency are hid from its eye?
But this is because the wisdom of man operates out of its place,
and is not subjected to the wisdom of God, but rather exalted above it.
Therefore man`'s wisdom is permitted for a time to lift itself up in
its conceit and persecute the pure wisdom of God and her children.
But it will at last fall and be broken,
and its day deservedly come to an end and be shut up in
the shadows and chambers of eternal darkness.

But what ear of man can hear this!
Surely none that is strong in the way of man`'s wisdom, reason, and understanding;
but only that which is bruised, broken,
and in some measure dashed in pieces by the inroads of the divine life and nature.
Happy is he who knows and hearkens to the persuasions of God`'s Spirit,
who is born of God and taught to wait upon him and worship him in Spirit.
And happy is the one who receives his religion from the
light of faith into the renewed nature and mind,
and not from the reason of man into the natural understanding,
which is easily corrupted and cannot be kept pure.

=== Some Mysteries of God`'s Kingdom Glanced At

[.alt.centered]
==== CONCERNING CHRIST

[.discourse-part]
Question: What is Christ?

[.discourse-part]
Answer: He is the immediate offspring of eternal life in himself,
and the fountain or spring of life unto the creation.
"`Even as the Father has life in himself,
so has he given to the Son to have life in himself;`" and in and
through his Son he communicates his life unto his creatures.

[.discourse-part]
Question: How does Christ convey life?

[.discourse-part]
Answer: As the living word; as the promised seed.
He sows the seed of the kingdom (in which is the life) into the heart.
And as he makes way for this to spread and grow up in and leaven the vessel,
so he quickens and gathers into his life.
Again, he is the enlightening word, the life-giving word, the word of wisdom,
the word of power, the word of love and reconciliation,
whose voice works mightily towards the destroying of
sin and the saving of the soul from it.

[.discourse-part]
Question: Where is this word or seed to be waited for?

[.discourse-part]
Answer: Its appearance is in the hearts of the sons of men,
and there it is to be waited for.
There God sows this seed,
and there it is nigh to them whom God visits with his loving-kindness and mercy.

[.discourse-part]
Question: How is this word received?

[.discourse-part]
Answer: By faith in the virtue which flows from it.
The nature of the word is to turn against sin, and to draw towards the Father.
Its light shines to discover sin, and its life stirs to quicken against it.
Now, as the heart believes and is persuaded against that which the light discovers to be evil,
and as it is won over to that which the light shows to be good,
the word is thus far received, and a foundation of union between it and the soul is laid.
But as the heart rejects or turns from anything that comes from the word,
Christ is thereby rejected and turned from.

[.discourse-part]
Question: How does this Word work in or upon the heart?

[.discourse-part]
Answer: According to the entrance it gets into the heart,
or according as it is rejected or refused.
As it gets entrance, it works life there, and works the creature into its life.
It brings in its nature, its righteousness, its holiness, its sweetness, its peace,
its love, its joy, its meekness, its patience, etc.,
as it makes room in the heart by working out the contrary.
But where it is rejected, it works death and condemnation,
and increases the captivity and misery of the soul,
so that it were better never to hear any sound of Christ in
the heart than to not hearken and become subject to it.

[.discourse-part]
Question: What hinders union with Christ?

[.discourse-part]
Answer: The strong man armed, whom Christ comes to dispossess,
does what he can to blind the eye from seeing the lovely nature of Christ,
and to harden the heart against his appearances.

[.discourse-part]
Question: How may the soul be helped against the strong man?

[.discourse-part]
Answer: Receiving the truth in the love,
and giving up the heart to the virtue that flows
from Christ in his visits and appearances,
allows into the soul that strength which conquers him.
The strong man is not able to stand before the power of Christ,
which power works within as it is let in by the soul.
It is the unbelief of the heart, and the earthly thoughts and imaginations,
which give the enemy strength.
But before true faith, even in the smallest measure, the strong man is weak,
and his strength falls.

[.alt.centered]
==== CONCERNING THE WAY OF KNOWING CHRIST

Christ is the minister of the true sanctuary which God has pitched, and not man.
There is a city, "`whose builder and maker is God.`"
The foundation stone, the cornerstone, the top stone of this city or building is Christ.
The one therefore that desires to know Christ, and to be built upon Christ,
must find a holy thing revealed in his heart,
and his soul built up upon it by him who alone can raise this building.
Only one can rear up the tabernacle that has long been fallen down,
who can build up the old waste places and restore the paths for the
ransomed and redeemed of the Lord to walk and travel upon.

Now he who can find anything of God built up in his heart (yes,
if he can find even the beginnings of the true sanctuary),
he may also find Christ ministering there.
In the heart the true high priest offers up sacrifices, intercedes with the Father,
and also gives the soul the food of the holy things to eat.
Now this is the way of knowing Christ, namely, in his begetting life in the heart,
in his presence there, in his ministrations there between the soul and the Father.
And he that thus knows him, watching in singleness of heart with the true eye,
cannot be deceived concerning him, but knows the voice of his Spirit,
and readily embraces it.
But a stranger or deceiver he knows not, and will not hear,
but by the instinct of life turns from it.
Thus the knowledge and preservation of the sheep is not by the wise reasonings of
the mind concerning the shepherd`'s voice and the stranger`'s voice,
but by an instinct of the new hidden nature,
which teaches the simple-hearted to avoid the snares in
which the earthly wisdom is easily entangled.
The meek, the humble, the brokenhearted, the weak, the poor, the babes,
the little children, these are they whom the Father teaches.
These have that preservation and instruction which the wise, knowing,
judicious minds (in man`'s account) miss.
Thus the foolishness of God is wiser than man, and the weakness of God stronger than man.
And God has chosen in every man that which is not, to bring to naught all that is in him,
so that no flesh might glory in his presence,
nor any man be able to boast before the Lord of the salvation of his soul.

[.alt.centered]
==== CONCERNING REPENTANCE

[.discourse-part]
Question: What is repentance?

[.discourse-part]
Answer: It is Christ`'s turning of the heart from the dead nature,
and from the dead works, towards the living seed and the living works thereof.

[.discourse-part]
Question: Cannot a man turn from sin and turn to God when he chooses?

[.discourse-part]
Answer: No; man is a captive, his understanding is captive, his will is captive.
All of man`'s affections and nature are in captivity,
and nothing can turn him towards God except for that which is
stronger than the power which keeps him captive.

[.discourse-part]
Question: How is repentance wrought?

[.discourse-part]
Answer: It is Christ`'s gift,
whom God has appointed a prince and Savior to give repentance and remission of sins.
He gives repentance in its enlightening and drawing virtue,
by which sin`'s nature is discovered,
and the bent of the soul is secretly turned against it.

[.discourse-part]
Question: What is the heart turned from, and what is it turned towards?

[.discourse-part]
Answer: It is turned from one nature to another, from one seed to another,
from one spirit to another, from one course to another, from one end to another.

[.discourse-part]
Question: Is repentance given in fullness all at once?

[.discourse-part]
Answer: No;
but it increases and is given daily more and more to the heart that waits on the Lord.
Sin, the nature of it, the course of the mind and body in it,
is uncovered daily more and more,
and the loathing and detesting of it increases as the new nature gathers
strength in the mind and increases in the light and power of life.

[.discourse-part]
Question: What if there be a committing of sin after one has turned from it?

[.discourse-part]
Answer: Here the repentance is not yet perfected; the enemy is not wholly cast out,
nor his strength quite broken; the law is not there fulfilled,
the covenant of grace is not there fully witnessed;
but the soul is still in a degree of captivity under the power of the enemy.
Yet if the bent of the heart is against the sin committed,
God charges it upon the enemy and not upon the soul.
"`Now if I do what I will not to do, it is no longer I who do it,
but sin that dwells in me.`" Rom. 7:20.

[.alt.centered]
==== CONCERNING FAITH

[.discourse-part]
Question: What is faith?

[.discourse-part]
Answer: It is a belief in the appearances of the Lord to the soul,
and a cleaving to and drinking in of their virtue.
There are diverse appearances of the Lord, even as a life-giving Spirit,
quickening and enlivening the soul; also as a discoverer, reprover, and condemner of sin,
and justifier of righteousness;
likewise as a strengthener and comforter of that which lacks his strength and comfort;
and as a fountain of perfect love, sweetness, and of all good, etc.
Now, however the Lord pleases to appear, that which sees, knows, owns,
and falls in with his appearances, drinking in the virtue thereof, that is faith.

[.discourse-part]
Question: By what means is faith wrought?

[.discourse-part]
Answer: By the living word in the heart; by the word from which the soul came,
and which is nigh to the soul.
This was the word of faith, or the word which wrought faith under the law. Deut. 30.
This was the word of faith which the apostles preached,
and which wrought faith under the gospel. Rom. 10.
This is the word which we feel working faith in us now.
Indeed,
this is the seed of life from which every spiritual thing springs and grows in the heart.

[.discourse-part]
Question: How is faith received?

[.discourse-part]
Answer: In the life-giving power.
The seed of life shoots forth its light, its life, its nature, its virtue into the heart.
The heart being touched with this is in some measure quickened towards God,
and in and from this life-giving virtue faith flows into the soul.
For in the death of sin, in the dead state, there is nothing but unbelief.
Faith therefore must necessarily flow from the quickenings of life.

[.discourse-part]
Question: What does faith do in the heart?

[.discourse-part]
Answer: It unites to God and separates from sin.
It begins and carries on the work of redemption in the soul.
It receives that which is of God, and beats back the contrary.
It keeps the mind chaste, pure, living, and fresh before the Lord.
It draws out the virtue and sucks in the sweetness of
every appearance of God in the heart.
It keeps in the love of God, and expels the love of sin, love of the creature,
love of self, or anything that stands outside of God.
Indeed faith is that which sucks in the breath of life,
and that which purges out the breath and power of death.

[.discourse-part]
Question: In what does faith stand?

[.discourse-part]
Answer: True faith stands in that by which it is received, even in the quickening power.
Faith must be continually kept alive by the seed of life, or it cannot live.
It springs in the power, it dwells in the power, it acts in the power,
and is never found out of it.
Man cannot believe when he will; it is a continual gift,
depending upon the continual quickening and
nourishment of that life from whence it sprang.

[.discourse-part]
Question: Why does the enemy so assault with unbelief,
and fight so strongly against the faith of the soul?

[.discourse-part]
Answer: Because all depends upon it.
Stop faith, and he has stopped all; overcome that, and he overcomes all.
If faith stands and abides in strength, the enemy gains nothing,
but rather loses by every temptation and seeming victory.

[.alt.centered]
==== CONCERNING LOVE

[.discourse-part]
Question: What is love?

[.discourse-part]
Answer: What shall I say of it, or how shall I in words express its nature?
It is the sweetness of life; it is the sweet, tender, melting nature of God,
flowing up through his seed of life into the creature,
and of all things making the creature most like unto himself,
both in nature and operation.
It fulfills the law, it fulfills the gospel;
it wraps up all into one and brings forth all in the oneness.
It excludes all evil out of the heart, it perfects all good in the heart.
A touch of love does this in measure; perfect love does this in fullness.

But how can I proceed to speak of it?
Oh that the souls of all that fear and wait on the Lord might experience its nature fully!
Then they would not fail to know its sweet,
overcoming operations both towards one another and towards enemies.
And this my soul waits and cries after,
even the full springing up of eternal love in my heart,
and the swallowing of me wholly into it, and the bringing of my soul wholly forth in it,
that the life of God in its own perfect sweetness may
fully run forth through this vessel,
and not be at all tinctured by the vessel,
but rather perfectly tincture and change the vessel into its own nature.
Then shall no fault be found in my soul before the Lord,
but the spotless life be fully enjoyed by me,
and become a perfectly pleasant sacrifice to my God.

Oh how sweet is love!
How pleasant is its nature!
How beautifully does it behave itself in every condition, upon every occasion,
to every person, and about everything!
How tenderly, how readily, does it help and serve the lowest!
How patiently, how meekly, does it bear all things, either from God or man,
however unexpectedly they come, or however hard they seem!
How it does believe, how it does hope, how it does forgive,
how it does cover even that which seems not to be excusable, and not fit to be covered!
How kind is it even in its interpretations and charges concerning wrongs!
It never grates upon the spirit of him whom it reprehends; it never hardens,
it never provokes; but it carries a meltingness and power of conviction with it.
This is the nature of God.
And in the vessels made able to receive love and bring forth its glory,
the power of enmity is not able to stand.

[.alt.centered]
==== CONCERNING OBEDIENCE

[.discourse-part]
Question: What is obedience?

[.discourse-part]
Answer: It is the subjection of the soul to the law of the Spirit,
which subjection flows from, and is strengthened by, love.
To wait to know the mind of God, and perform his will in everything,
through the virtue of the seed of life revealed within, this is the obedience of faith.
This is the obedience of the seed conveyed into the creature by the seed.
The obedient son is he who naturally does the will; yes,
and he is the choice servant also.

Mark how everything in the kingdom, every spiritual thing, refers to Christ,
and centers in him.
His nature, his virtue, his presence, his power, makes up all.
Indeed he is all in all to a believer,
only variously manifested and opened in the heart by the Spirit.
He is the volume of the whole book,
every page and line speaks of him and describes him in some or
other of his sweet and beautiful characteristics.
So that if I should yet speak further of other things, such as meekness, tenderness,
humility, mercy, gentleness, patience, long-suffering, contentedness, etc.
(all of which I would much rather be read in his living
book of the eternal Word than in my writings),
I am only speaking further of his nature brought up, manifested,
and displaying itself in and through the creatures by
his turning the wheel of his life in their hearts.
But my spirit hastens away from words,
and I feel I must cut short and pass over these openings in me,
so that neither my own soul nor others may fix upon the words concerning the thing,
but will rather sink in spirit into the feeling of the life itself.
Oh that we may learn what it is to enjoy the substance there,
and to be comprehended of it, and cease striving to know or comprehend concerning it.
For he that has a taste of this living knowledge,
which is laid up in that treasury into which the
thief and corrupter can by no means touch,
cannot help but be willing to sell all the knowledge
that can be held in the creaturely vessel.
And yet I cannot help but add something further concerning peace, joy, liberty, prayer,
as also concerning regeneration, justification, sanctification, reconciliation,
and redemption;
because my heart believes that it may prove serviceable to
some in the guidance and mercy of the good Spirit of the Lord.

[.alt.centered]
==== CONCERNING PEACE OR REST

True peace is the stillness, the quietness, the satisfaction of the heart in God,
which flows from and with the Spirit of life in the soul that is subjected to Christ.
There is indeed another kind of peace, that is,
a false peace or rest in sin and unrighteousness.
But this is not truly natural to the soul while it lasts,
and it is also suddenly disturbed when the true light
shines in the heart and when God`'s witness awakens it.
Then "`there is no peace to the wicked.`"
Oh, the trouble and perplexity of the sinner when the light of God`'
s Spirit makes his heart and ways manifest to him!
And oh what a bitter war, noise, and tumult does the enemy raise within!
How he seeks to disturb every step of the way, and strives to darken every drawing,
motion, and leading of the soul out of his dominion!
But as the redemption is experienced, the snares are broken, the life is manifested,
and the soul feels itself entering into the nature of life and the obedience to it.
And so the peace springs, and the rest in God is tasted of and enjoyed.

[.alt.centered]
==== CONCERNING JOY

Joy is the gladness of the heart in God chiefly
springing from the refreshings and presence of his life,
which carries through and over all, even the greatest trials and tribulations.
When the poor, panting, weary soul, which has longed after God,
and has long felt the bitterness and misery of its separation,
begins to feel its union with him, and his love, goodness, righteousness, power, wisdom,
and salvation,
oh how the soul is filled with joy and delight in the earnest of its portion!
Now it can say in the strength of life, "`My soul rejoices in God my Savior;
for he has regarded my low estate!
His heart has moved towards me, his dayspring from on high has visited me.
And I, who long have been desolate and forsaken,
have now found favor in the eyes of my beloved,
and my heart feels (in measure) that I am his, and he mine.
He has touched me, won my heart, and what can separate?
He has tied the knot himself, and what can break it?
And how can my heart not rejoice in his name over all my fears, false reasonings, doubts,
and misgivings, which long held me captive and kept my eye from reading his love,
the which was written both in his heart and in his dealings towards me?`"

[.alt.centered]
==== CONCERNING LIBERTY

Liberty is the enlarging of the heart in the Spirit of the Lord,
wherein it has freedom in all that is good, and is shut out of all that is evil.
The Spirit of the Lord is free, and makes free.
The earthly spirit is in bondage with her children;
but they which are begotten of the Lord, and wrapped up in his Spirit,
find in him the power and freedom of the new life,
and are thereby perfectly out of the reach of
that which has power to captivate and enthrall.
Therefore the true liberty does not consist of a
freedom in all manner of scope and latitude,
but rather in the scope and latitude proper to its nature.
Thus the infinite and unlimited One is limited (if it be proper so to express it),
within the limits and bounds of his own nature and Spirit, which he cannot transgress,
or in any way consent to do what is contrary to it.

[.alt.centered]
==== CONCERNING PRAYER

Prayer is the breath of the living child to the Father of life in
that Spirit which makes the child alive and grants a right sense of its
needs and suitable cries proportionable to its state and season.
So mark: prayer is wholly outside of the will of the creature,
wholly outside of the time of the creature, wholly outside of the power of the creature,
in the Spirit of the Father, who is the fountain of life,
and gives forth breathings of life to his child at his pleasure.

[.alt.centered]
==== CONCERNING REGENERATION

[.discourse-part]
Question: What is regeneration?

[.discourse-part]
Answer: It is the new birth of the creature,
or its being born again of the immortal seed of the word of eternal life.

[.discourse-part]
Question: How is this birth obtained?

[.discourse-part]
Answer: By the springing up of the seed of eternal life in the heart,
and the heart being changed into it, and brought forth in it.

[.discourse-part]
Question: How is the heart changed into and brought forth in the seed?

[.discourse-part]
Answer:
By being leavened with the power and virtue of its nature by a new sap received from it,
which spreads by degrees, and at length becomes all in it.

[.discourse-part]
Question: How is this virtue received from the seed?

[.discourse-part]
Answer: In giving up to it in the faith which flows from it.
This lets in the new sap and nature of life, which purges out the old.

[.discourse-part]
Question: How does the seed appear and manifest itself,
and how is it given up to in the faith?

[.discourse-part]
Answer: The seed appears in its own light and quickening virtue,
which uncovers the darkness and death of sin,
and draws the heart (which it makes willing) out of it.
Now as this drawing is felt, it is clearly known,
and the thing required by it is made manifest.
Here there is a faith begotten in the heart,
and then the soul is to give up in the obedience of the faith,
without consulting with the reasonings and wisdom of the fleshly mind,
where the enemy lies ready to dampen this light
of faith and bring the soul into unbelief.

[.alt.centered]
==== CONCERNING JUSTIFICATION

[.discourse-part]
Question: What is justification?

[.discourse-part]
Answer: It is the owning or clearing of a person in his obedience to the Lord;
or the pardoning, passing by, and so clearing him from his disobedience.

[.discourse-part]
Question: Who is it that justifies?

[.discourse-part]
Answer: It is the Lord, who gives the law to mankind according to his pleasure.
He it is that is also the judge of man`'s obedience or disobedience to it,
and the proper justifier or condemner of him in it.

[.discourse-part]
Question: But is not man in a fallen state?
And can he obey God in anything so as to be justified by him?

[.discourse-part]
Answer: Man is indeed fallen,
and has no strength or will of himself to serve or obey the Lord.
But there is a visitation of life and love issuing forth towards mankind in general,
in which the quickening life goes forth, and a secret,
hidden power which gives an ability to every willing heart to follow his drawings.
And this visitation is so managed by the Lord that no man perishes for lack of power,
but only from the stubbornness and choice of his own will.
So that man`'s destruction is indeed of himself, and not of God, whose delight is to save,
and not to destroy his creature.

[.discourse-part]
Question: How is this justification wrought?

[.discourse-part]
Answer: By faith in the virtue which flows from Christ.
God lets the nature of his Son into the heart,
and begets there something of his own likeness,
by which he draws and gives the ability to believe.
This faith is imputed by God for righteousness in every heart wherever it is found.
And wherever this faith in the living virtue is found,
there God blots out the iniquities for his name`'s sake; yes,
and remission of sin is felt in that which is made living.

[.discourse-part]
Question: May a man be justified who never heard outwardly of Christ?

[.discourse-part]
Answer: If a man experiences the seed of life, is overcome by its nature,
gives up to its law as it is made manifest in his heart,
abhors the nature and law of sin and death,
and thus in his soul cleaves unto the Lord and follows him,
then the Spirit and life of the Lord cannot but herein justify him.
The grace and mercy of the Lord cannot withhold giving him pardon for
his sins past (and also pass by his future frailties),
although he does not distinctly know how to plead for it.
The redemption and pardon of sin is through the unlimited grace of God,
which is not restricted to the outward knowledge of the creature,
but issues forth according to the capacity that God gives to receive it.
Life, mercy, grace, pardon, etc., issue forth from God into the vessels of every kind,
and the inward sense of life is the thing that God aims at in all his dispensations,
and not the outward ability or knowledge.

[.discourse-part]
Question: How is justification by grace?

[.discourse-part]
Answer: No man in his fallen state can deserve anything of God.
It is of grace that God visits him by any outpouring of his love and mercy.
It is of grace that he gives him any ability to turn unto him.
Indeed such is the weakness of man,
that no man can be justified by works of obedience that
he can perform under any dispensation,
but only by the remission and ability which he receives from grace.

[.discourse-part]
Question: What is the righteousness that justifies in the sight of God?

[.discourse-part]
Answer: The righteousness of Christ alone.
This righteousness conveyed to the creature in and through the seed,
and brought forth in the creature by the seed,
and the creature united to Christ in the seed; here is the justification of the life.

[.alt.centered]
==== CONCERNING SANCTIFICATION

[.discourse-part]
Question: What is sanctification?

[.discourse-part]
Answer:
It is the cleansing of the vessel by the Spirit of the
Lord from the pollution of both flesh and spirit.

[.discourse-part]
Question: And by what does the Spirit of the Lord cleanse the vessel from its pollution?

[.discourse-part]
Answer: By the living truth, which has power in it to wash away the deceit, enmity,
impurity, and whatever evil has formerly defiled,
or may yet again at any time defile the vessel.

[.discourse-part]
Question:
How does the soul receive this cleansing or purifying from the Spirit of the Lord?

[.discourse-part]
Answer: In its obedience to his truth made manifest in the heart;
for by this the power of the word enters into the soul
and sheds abroad its living virtue in the soul.

[.discourse-part]
Question:
What then is chiefly to be minded by the soul
that desires to be cleansed from its filthiness?

[.discourse-part]
Answer: The obedience of faith, or the obedience which springs from faith.
For as all the benefits and blessings of the law depended upon obedience to the law,
so all the benefits and blessings of the gospel depend upon obedience to the gospel.
Yes, and this is the glory and excellency of the gospel:
that the principle of faith now does that which the principle of the law could never do.

[.alt.centered]
==== CONCERNING RECONCILIATION

[.discourse-part]
Question: What is reconciliation?

[.discourse-part]
Answer: It is a bringing together the minds and hearts of God and man into one.

[.discourse-part]
Question: How is this wrought?

[.discourse-part]
Answer: By taking away the enmity of man`'s nature, which is against God,
and by planting him into, and causing him to grow up in,
that nature and life which God loves.
In this way, that which God hates, and which is the cause of the separation,
is removed from man, and man is brought into, and brought up in,
that which is the love and delight of God`'s heart.

[.discourse-part]
Question: By what is this reconciliation wrought?

[.discourse-part]
Answer: By the Word of God`'s power.
This Word comes forth from the love of God unto man,
and man being gathered out of himself into that, the evil seed is thereby destroyed,
and the good seed of the kingdom is thereby cherished.

[.alt.centered]
==== CONCERNING REDEMPTION

[.discourse-part]
Question: What is redemption?

[.discourse-part]
Answer: It is the purchasing of the vessel out of the captivity and misery of death,
into the liberty and blessedness of the divine life, which is sown, revealed, grown,
and perfected in the heart.

[.discourse-part]
Question: Who is the redeemer?

[.discourse-part]
Answer: The Son of God, the child of God`'s begetting, the divine image,
who naturally believes and fulfills the will of
the Father in every vessel which he has prepared.

[.discourse-part]
Question: By what does he redeem?

[.discourse-part]
Answer: By his blood; by his life; by his power;
by his nature sown in the vessel and transforming the vessel into its own likeness.
Yes, this is indeed redemption,
when the creature is changed into and brought forth in the image, power, nature, virtue,
and divine life of him that redeems.
And the old contrary image is perfectly blotted
out by the presence and indwelling of the new.
This is perfect redemption, the least measure of which is redemption in a degree.

After this springs up the glory of the life in the vessel,
even the glory which it had with the Father before the world was.
In the nature of the life the glory is hid.
It is sown in the seed; it dies with the seed; it is raised with the seed.
When Zion in any heart is built up,
it is natural to the Lord to appear there in his glory; and the pure eye sees him,
and the pure heart enjoys and is one with him.
So that even as there is a true entrance into, fellowship in,
and enjoyment of the death of Christ,
so there is also the resurrection and glory of the redeemed life.
This is the portion and inheritance which God has prepared for Zion,
after her long desolation and sore widowhood.
And this portion he will give unto her in the sight of all the world,
whereby she will become the beauty, joy, and praise of the whole earth.

=== A Last Word of Warning

This I am assured of,
that it would be an easy matter with the Lord to give forth a
literal description of all the things of his kingdom,
so exact, full and plain, so as to answer and satisfy every inquiring mind.
But this would not effect the work which God is now about.
This would not raise his seed,
which would lie dead and buried under all these descriptions unless
quickened and raised by the immediate power and life of the Father.
And would not the earthly spirit easily build with such clear words an earthly fabric,
such as would not be according to the measure of the true temple?

May I speak freely?
I would not deny anything of God among you,
nor be an instrument to quench the least good in any of you.
But indeed I have seen, felt, and known some of your snares,
and would rather spend the strength of my spirit in crying to God for
you that he would break them and disentangle your souls,
rather than in attempts to demonstrate and manifest them unto you.
And I am now touching upon one of these snares, which is not the smallest, namely:
a getting the knowledge of things into the mind and comprehension,
striving to grow rich there, and wise to understand and dispute about them.
And if the Lord did not teach my soul continually to
give up the outward knowledge of everything,
and press after the inward life, I might soon grow wise after the flesh,
but I would lose the fresh oil which softens and nourishes me.
My spirit bows and presses within me in great earnestness to the God of
mercies that you may not be left behind the flock whose path is living,
and who follow the living footsteps of the Lamb,
who leads by his living Spirit from life to life into his kingdom.
