== Chapter XIV. The Two Seeds

This is the substance of our religion: _first,_
to experience and discern the two seeds, that is,
the seed of enmity and the seed of love,
the seed of the flesh and the seed of the Spirit,
the seed of Hagar and the seed of Sarah,
the seed of the Egyptian womb and the holy seed of Israel; and second,
to experience the judgments of God administered to one of these seeds,
till it be brought into bondage and death;
and to experience the other raised up in the love and mercy of the Lord to live in us,
and our souls gathered into it, to live unto God in it.

Now when the light of God's Holy Spirit breaks
in upon man and his quickening virtue is felt,
then life enters into that which was slain,
and there is a desire begotten in the heart to travel
out of the Egyptian state into the good land.
And the soul, which was created by God, yearns to return back to him, out of the sinful,
wandering, miserable, lost state, that it might live and walk with him in the purity,
virtue, and power of his own life and Spirit.

But then the fleshly birth fights for its life, and Pharaoh, the king of Egypt,
takes part with his Egyptians against Israel.
In this there is no help to the poor soul,
except as God pours out his judgments upon that hard nature
and spirit in man which is of the birth of the flesh,
and which receives the influences and strength of its
father that harden it against the true seed.
And now what a condition is this poor soul in?
The light of God's Spirit gives it the awareness of its state,
and the quickenings of life make it sensible of its bondage.
There are also some desires and longings after deliverance,
but this only provokes the enemy,
for the soul is yet in his territory and under his power,
and he deals more harshly with it, increasing its burdens and oppressions daily.
And oh, the outcries of the soul in this state!
How is its spirit pained, anguished, and vexed within it,
so that it could almost choose to remain in Egypt rather than undergo the heavy burdens,
oppressions, fears, and dangers that it daily meets with in this state!

Yet there is a secret hope springing up in the heart from the true seed,
which often encourages it to trust him,
and to wait upon him who has visited with his pure ministration of judgment.
For this is felt many times (as the soul is made truly sensible by the Lord),
that the judgment is not to the seed, not to Israel, but to Pharaoh and his Egyptians.
And by every stroke of God's wrath upon them, the seed is further eased,
and its deliverance is worked out.

So at last, when the judgment is finished in the land of Egypt,
and the strength of Pharaoh and his Egyptians broken, and their first-born slain,
then out comes Israel, out of the dark land, out of the house of bondage,
to travel towards its resting place.
Then the paschal Lamb is known and fed upon.
Indeed, it is because of the blood of the lamb sprinkled upon the door-posts
that Israel is passed over and saved in the day of Egypt's visitation.

But now, when the seed is come out of Egypt, this is not the end,
but rather the beginning of its travels.
Pharaoh and his Egyptians, with their horses and chariots,
may pursue again and even overtake.
And there may seem no way of escape or help to the soul, but only to stand still,
hope in the Lord, and wait to see his salvation.
Then shall the sea be divided, which stopped Israel's course,
and Pharaoh with his Egyptians (the enemies of the soul in this appearance
of dreadful oppressing power) be destroyed and seen no more.

Yet in the wilderness, in the passage through the entanglements to the holy land,
there are many straits, trials, and sore enemies to be met with.
Some enemies will strive by open force, and others, with their enchantments,
will seek to betray Israel.
For there is still a part of Israel not yet brought down, not yet wrought out,
where the enemies will be striving to enter the mind.
And as Israel forgets his God and walks out of his counsel,
hearkening to that which his ear should not hear, and so joining to the contrary seed,
then the plagues, the judgments, the indignation and woe will be felt by him,
and many may fall there.
And here there may be a great outcry in the heart,
"`Who can stand before this holy Lord God?
Shall we all utterly die?`"
Yes, there is something that must utterly die.
For even if a man came so far as to witness dominion and victory over his soul's enemies,
and the evil seed brought into death in him, yet if that part is not kept in death,
then the enemy will again be sowing to the flesh.
He will again sow some of his corrupt seeds into the
heart (if the soul sleeps and becomes negligent),
and so corruption will take root again, and the contrary birth will grow up again,
and the foxes break into the vineyard and spoil the tender grapes.

So then, this is our religion: to witness the two seeds,
with the power of the Lord bringing down the one, and bringing up the other.
And it is to daily witness and experience the same power, keeping the one in death,
and the other in life, by the holy ministration of God's pure living covenant.
In this way we must know God in this covenant, in this covenant which lives, gives life,
and keeps in life.
And so we must walk with God, and worship and serve him in his Son,
in the light of his Son, in the life of his Son,
in the virtue and ability which flows from his Son into our spirits.
This then is our religion, which the Lord our God, in his tender mercy,
has bestowed upon us.
And indeed we find this to be a pure, living, and undefiled religion before God,
daily witnessing his acceptance of it in and through his Son,
whose name is here known and confessed, worshipped and honored,
according to the very heart of the Father.

This may be further illustrated, and perhaps made more manifest to some,
by a scripture or two.

[quote, , Gal. 5:17]
____
The flesh lusts against the Spirit, and the Spirit against the flesh;
and these are contrary one to the other.
____

Here are the two seeds (the seed of the serpent and the seed
of the woman) whose striving and fighting is in man,
once God awakens the soul.
The one has a nature, a desire, or lust contrary to the other.
Now as one of these prevails in any heart, so the other goes down.
As the one gains life and power, so the other is brought into death and captivity.
Therefore,
this is what everyone is to wait for after they come to
the sensible knowledge and experience of these two:
to know the flesh brought down, the lusts of it denied,
the judgments of the Lord administered to it; and to know the other seed come up to live,
thrive, and prevail in the soul,
and so the soul witnesses salvation and redemption under its shadow.
"`Thus Zion is redeemed with judgment, and her converts with righteousness.`" Isaiah 1:27.

What is Zion?
Is it not the holy hill of God where his Son is set as King to reign,
and where the holy city is to be built, and God to be worshipped in spirit?
What condition is Zion in when God visits her to redeem her?
Is she not laid waste, desolate, lying in the dust?
Ps. 102:13-14. Well, how will God redeem her?
"`Zion shall be redeemed with judgment, and her converts with righteousness.`"
By bringing judgment upon that which keeps her under, upon her enemies,
the contrary seed, God redeems her.
And by bringing forth righteousness (the righteous life and
Spirit of his own Son) in those whose minds are turned to her,
whose faces are set toward Zion, in this way God redeems her converts.
Yes, it is truly felt and witnessed;
the living righteousness of Christ revealed in the heart, and having power there,
he sets free from all the unrighteousness which was there before.
And then, when the unrighteous one is cast out, and the righteous one revealed,
and the soul united to him (receiving all virtue and power from him),
then the soul becomes a servant of righteousness, and does not commit sin,
but does righteousness; "`and he that does righteousness is righteous,
even as he is righteous.`" 1 John 3:7.
For how could it be otherwise,
if the righteous life is revealed and brought up into dominion in him?
How could the same righteous Spirit and life (now revealed in
the members as it was in the head) not but live and act after
the same manner in the members as it did in the head?
(Oh that men were turned to that which would give them the certain
knowledge and sensible experience of this!) Now this is exceedingly
precious to those who are truly traveling towards it,
and even more so to those that enjoy it.

These three then are the sum of all:
1) to know and experience what is to be brought down and kept in death;
2) to know what is to be brought up out of the
grave and live to God and reign in his dominion;
and 3) to know what must be kept in subjection and obedience to him who is to reign.
Now to experience this done in the heart (the flesh brought down,
the seed of life raised, and the soul subject to the pure heavenly power),
this is a blessed state indeed!
For here the work is done; here the throne of God is exalted,
and his King reigns in righteousness and peace, and all his enemies are under his feet.

For in the outward state of outward Israel,
they were to keep to God in the outward covenant.
And it is to be the inward state of the inward
Israel to keep to God in the inward covenant,
which is a pure covenant of life and peace.
It is a covenant of all inward and spiritual blessings and mercies in Christ,
in which souls are blessed who are obedient unto their God,
and walk humbly with him in this covenant.
Now who is the Israel that is to inherit these promises?
All the promises are "`yes and amen in Christ`" to the Israel of God.
Then why should not the Israel of God hope to enjoy these things?
Should they not be acquainted with God's Holy Spirit, and wait upon him,
that they may witness it granted to them?
And should they not be delivered out of the
hands of their enemies to serve God without fear,
in holiness and righteousness before him (whose eyes are piercing,
and can behold no iniquity) all the days of their lives?
And truly the children of the new covenant can never come thoroughly to live
unto God until they witness the inward circumcision of the heart,
so as to love the Lord with all the heart and soul. Duet. 30:6.
Oh that people had experience of God's power, and did believe in it!
What can stand in the way of it?
Was not Israel's sin of old when they looked at their enemies and saw their
strength in the land which God had promised to Abraham's seed for an inheritance?
They could not believe that such enemies could be overcome.
Oh take heed of the same unbelief now!

=== Concerning Coming to the Father by Christ

[quote, , John 14:6]
____
I am the way, the truth, and the life: no man comes unto the Father but by me.
____

Man, in the corrupt and degenerate state, is fallen from God,
and has lost his image (the holy, heavenly image of the Father of spirits).
He is driven out from God's presence,
and dwells in the land of darkness and confusion under
the government of the prince of the power of the air,
who rules in, and has power over, all the children of disobedience.
Now this should be man's aim, even to return to the Father,
to come out of the prodigal's lost state unto the Father's house,
where there is sufficiency and fullness of true bread and
water of life to satisfy every hungry and thirsty soul.

Now, the way whereby a man must come, the truth wherein he must be renewed,
and the life wherein a man must be made alive, is Christ, the Son of the living God.
Man must know him as the Son of the living God,
and experience him to be received and revealed within, and so walk in him as the way,
the truth, the life, if ever he will come to the Father.
He must not rest in a mere description of these things, but rather experience and know,
receive and walk in the thing itself which the Spirit
of the Lord has so often described in words.
It will not do simply to receive all the reports of him that were formerly given forth,
or all the reports that are now proclaimed.
Indeed, the soul that will live by him must receive him,
and experience an ingrafting into him as the holy root,
the living word of God's eternal power.
He must know this word ingrafted into his heart so that there
become a real oneness in nature and spirit with him.
Only then is a soul truly living in the vine, in the olive tree,
partaking of its virtue and sap, and walking in its spirit, life, and power.

A man cannot walk here in the oldness of the letter,
but only in the newness of the Spirit.
Paul, despite all his knowledge of the Scriptures,
walked but in the oldness of the letter before Christ was revealed in him.
And those in the apostles' days who had a form of
godliness but had turned from and denied the power,
these walked but in the oldness of the letter.
Even the church of Sardis, for the most part, and the church of Laodicea,
who had received the right order and ordinances and the true descriptions of things,
and thought they were full and rich and lacked nothing,
they walked but according to the oldness of the letter,
and not in the newness and power of the Spirit of life.
But alas,
how many are there in this day who claim to know Christ but never came so
far as even to walk in the oldness of the letter from a true understanding!
Can such men possibly understand truth, or know its inward, spiritual,
and precious appearances, either in their own hearts, or the hearts of others?
Surely no.
Why not?
This is the reason:
because they measure the appearances of truth in themselves and in
others by their own apprehensions and conceivings of the Scripture,
which are not at all the proper measure of it.
Now all such men are but blind leaders of the blind,
and by continuing on in this way they shall most
certainly fall into the ditch of perdition.

None can know Christ rightly but by the
inward revelation that comes from the Father.
The mystery must be opened within or there is no true knowing.
The mystery of deceit is discovered within,
and the mystery of life is discovered within also.
And whoever witnesses Christ revealed within shall find him revealed for this very end,
to destroy the works of the devil there.
He is a powerful Savior of the soul from sin,
and a powerful destroyer of the works of the devil within.

Now concerning reading the Scriptures, keep this in mind:
it is said of the Jews that when they read the
Old Testament the veil was upon their heart,
which veil is done away in Christ. 2 Cor. 3:14-15.
Oh consider seriously!
Is the veil done away from you?
Do you read the Scriptures with the unveiled eye?
Do you read in the anointing, in Christ's Spirit,
in the pure heavenly wisdom of the divine birth?
It was promised of old that God would take away
the face of the covering cast over all people,
and the veil spread over all nations. Isa. 25:7.
Do you witness this promise fulfilled?
Do you know the difference between reading the
Scriptures with the veil on and with the veil off?
Are the Scriptures opened and unlocked to you by the key of David,
so that you read and understand them in the light and demonstration of God's Holy Spirit?
Or is your own understanding and will at work in searching into the Scriptures?
If the wrong birth, the wrong wisdom, or the wrong understanding is at work,
it can gather only that which will feed and strengthen itself.
And if you are not in Christ, and do not read in Christ,
then the veil is not taken away from you, for the veil is only done away in him.
If you read and walk in the oldness of your apprehensions of the letter,
and not in the newness of the Spirit,
then you know neither the Scriptures nor the power of God,
whatever you may profess to men or dream concerning yourself.
For your own knowledge, your own apprehensions, your own faith, hope, peace,
and joy (being outside of the compass of the pure,
living truth) are nothing more than dreams.

The Scriptures are words, whose chief end, significance, and service,
is to bring men to the Word from which the Scriptures came.
And when men are there, abiding in this Word,
then they are in the life of the Scriptures,
and witness the fulfilling of the Scriptures.
Here they find the righteous judgments of God executed upon that spirit, mind,
and nature in them which is contrary to his image.
Here they know the fulfilling of the promises and the
sure mercies which belong to Christ the seed,
and to those who are gathered into, and abide in, Christ the seed.
Here is the covenant, the new covenant.

Now, all that has been said in the Scriptures concerning the
covenant is but a description in words of this new covenant;
but Christ within, the hope of glory, the Spirit within, the fear within,
the power of life within, breaking down and reigning over the power of sin and death,
this is the covenant indeed.
And the strength and virtue of the covenant is witnessed in the soul,
as it feels the power of life revealed in it.
And the soul is made subject to the power of Christ who reigns in righteousness, love,
mercy,
and peace in the hearts of those whom he redeems out of the earthly nature and spirit,
up to the mind and Spirit of his Father.
And here the psalms, hymns, and spiritual songs, the pure songs (the song of Moses,
the song of the Lamb) are sung to the Father of spirits, to the Redeemer of Israel.
These are songs which were never sung, nor can be sung, in any part of Babylon.

=== Concerning Christ Manifested Without and Within

It is objected against us that we deny Christ (and look not
to be saved by him) as he was manifested outwardly,
but that we look only to be saved by a Christ within us.
It is upon my heart to answer those who, with regard to this objection,
truly desire satisfaction.

We do indeed expect to be saved (yes, and not only expect, but do already,
in our several measures,
witness salvation) by the revelation and operation of the life of Christ within us.
Yet this is not without relation to what he did outwardly.
For all that he did in that body of flesh was of the Father,
and had its place and service in the will, and according to the counsel, of the Father.
But the knowledge and belief of this, since the days of the apostles,
has been very much held in unrighteousness and in a separation from
the inward work of the power and life of Christ in the heart;
and when it is so held, it cannot save any.
But the one who experiences the light and life of Christ revealed in him,
and comes into union with God thereby, this one experiences the work of regeneration,
of sanctification, justification, life, and redemption;
and in this way comes to reap the inward benefit and
blessed fruits of all that Christ did outwardly.
Indeed, he that is one with Christ in the Spirit,
cannot exclude himself (nor is excluded by God) from the advantage of
anything and everything that Christ did in his body of flesh.

This indeed is the main thing: to witness salvation wrought out in the heart;
to witness the eternal power and arm of the Lord laying hold of the soul to save it,
and not only to save it, but to work out and effect salvation as truly in substance,
as Israel of old experienced it in shadow.
For as they witnessed Moses and Joshua outwardly, so the true Israelite,
the inward Israelite, the spiritual Israelite,
is to witness that which is the substance of these,
even the Son of God revealed inwardly.
Now they were not saved outwardly by a bare outward believing
that Moses and Joshua were sent of God to save them;
but by following them in faith and obedience in what was required by God.
In the same way, Christ is given to the inward Israel for a leader and commander,
who appears to the distressed enslaved soul in Egypt, brings out of Egypt,
and leads on towards and into the good land.

Now as the soul follows and believes in Christ's appearances,
and obeys his voice in the holy, pure, covenant of life,
so the redemption of the soul is worked out.
But as unbelief and disobedience rise up,
and the heart is hardened at any time against his voice and counsel,
and the ear opens to the temptations of the enemy, the redemption thereby goes backward,
and the distress and captivity return again.
This is witnessed, known, and experienced by every true traveler towards Zion.
Therefore, the main thing required is to abide in the sense of the Redeemer's power,
waiting for his motions and appearances, in the faith and obedience thereof.
For sin gathers strength, and is brought forth,
by letting in and giving way to the motions thereof.
So also holiness and righteousness are brought forth and gain ground in the heart
by hearkening and giving up to the stirrings and movings of God's Holy Spirit.
Therefore,
it is of great necessity to every true traveler to come to a
right understanding and distinguishing of these things,
and that the heart be kept with all diligence,
for out of the heart are the issuings of both life and death.
Most happy is the one who knows the issues of death stopped,
and the issues of life opened, and whose spirit is naked and open before the Lord,
looking for life to spring up and issue forth at his pleasure.

Oh, it is a precious state to witness captivity led captive by life,
and the power of life reigning over it!
And truly there is as real a deliverance witnessed inwardly by those that
wait upon the Lord and are faithful to the leadings of his Holy Spirit,
as ever there was experienced by the Jews outwardly in
their faithful following of Moses and Joshua.
And Christ is as truly a healer of his people in this
ministration of life to them by his Holy Spirit,
as ever he was a healer of persons outwardly in the days of the flesh.
Such healings, together with the other miracles that he wrought then,
were but a shadow of what he would work and perform
inwardly in the day of his Spirit and holy power.
And now shall he,
or can he (to those that faithfully wait upon him) fall short
of in the substance what he testified of in the shadow?
Surely no!
It is the intent of his heart (and he will not fail to perform
it) to save to the very utmost all who come to God by him,
and who abide in his holy, pure, righteous, living covenant.
Here is the skill of Christianity: to abide in him.
Only here is the living virtue and pure power felt which overcomes all,
and which nothing can overcome.

=== A Few Words Concerning the Seed of Truth

[.discourse-part]
Question: What is the seed of truth?

[.discourse-part]
Answer: It is the light, which reproves and makes sin manifest.
"`Whatsoever makes manifest is light.`"
Wherefore he says, "`Awake you who sleep, arise from the dead.`" Eph. 5:13-14.
There is no other way of awaking out of sleep and
arising from the dead except by the light which makes sin manifest.
And oh, how precious is that light!

[.discourse-part]
Question: How may the seed of truth be discerned?

[.discourse-part]
Answer: By its piercing, life-giving nature,
which unveils itself in its appearances and operations.
For it appears and works, not like man's reason,
nor like the motions of his mind which he gathers into his understanding part;
but it appears and works livingly, powerfully, and effectually in the heart.

Since the fall, man's reason is corrupt, dark, impure,
and in the hand and under the power of the wicked one.
Its nature is to hide and cover sin, not to uncover it.
Now the light of the law, which uncovers sin, does not arise in man's reason.
Who can bring the clean, pure light of the law out of the unclean, impure reason of man?
The light indeed may shine in the darkness, but it is no part of it,
but rather of another nature and descent.
It is from God's Spirit, and given to man in his love unto him,
to lead him out of his dark ways and spirit into the pure Spirit and way of holiness.
For the light which uncovers sin is all holy and pure,
like the fountain from whence it comes.
Now a man that is acquainted both with reason and with this
light can distinguish the nature and operations of both.
But there is a great difference between truth held in the reasoning part of man,
and truth held in its own seed.
It is very powerful in the one; it effects little in the other.
In the pure quickenings of life, the distinction is clearly perceived, and also held.
Therefore,
our advice to all men is to turn from all mortality and come
to experience the spring of life working within them,
springing out into them to give them life.
Men should wait to have their understanding opened and kept open by this life,
so that they may receive, retain,
and not lose the capacity of understanding the things of God's kingdom.

[.discourse-part]
Question: How may this seed or pearl be purchased and possessed?

[.discourse-part]
Answer: By dying to a man's own wisdom and will.
There is not another way.
For the light is wholly contrary to man as he stands in the alienation from God.
It runs contrary to his spirit, his thoughts, his desires, his knowledge, his reason,
his understanding, even all that is of himself.
He must therefore consult with none of these, but prefer the little,
pure demonstration of the light of Christ's Spirit above all these,
and be made willing to part with them all forever.
Oh this is a hard saying, who can bear it?
Surely none but those that are taught and learn of the Father
can come to give up to and follow the light of the Son.

And this I dare positively hold forth as a standing truth,
which has been sealed unto me by constant experience:
No man can agree with and obey the light unless he deny
himself and take up a cross to his own wisdom and will.
This cross is the cross of Christ, which is the power of God to the salvation of the soul.
And he that takes it up daily, and waits upon the Lord therein,
shall witness the power of the Lord Jesus Christ to the redemption of his soul.
Indeed, he shall be able in true understanding to say, "`This is light indeed,
life indeed, power indeed.
That powerful arm which has saved me from sin, and breaks the snares, devices,
and strength of the enemy before me (delivering me daily when none else can,
and when my own strength and wisdom is as nothing), I know it to be Christ,
the living power and wisdom of God revealed in me,
who will not give his glory to another.
For he is the Lord God of pure power and life forevermore,
and beside him there is no such Savior.`"

=== How the Seed Begets and Maintains Life in the Heart

The Lord God (who is full of everlasting compassion towards mankind in general,
but more especially towards those in whom he has begotten a
sense of longing after himself) has chosen a seed,
or inward spring of life,
to appear in man for the breaking of the bonds of their captivity,
and the bringing out from under the power and misery of death.

Many are they who have been overwhelmed with misery,
and whose spirits have melted and failed with the lack of the sense of their God.
Many have felt the sense of life which was formerly
built up in them broken down and laid waste,
and their communion with God swallowed up in its ruins,
and their souls ready to utterly perish and be devoured by the enemy every moment.
Many have felt all hopes cut off, and their eyes shut up to all ways of relief.
And then, I say, after all this, in the tender mercy of the Lord,
these have felt the seed of life revealed in their hearts, and, by degrees,
have found their hearts gathered into this seed, where the life reigns,
and where the strength and dominion of death is broken in all those
who are led on by the drawing and guiding of the Spirit of the Lord.

Now after the revealing of this seed, and gaining a sense and experience of it,
and the turning of the mind towards it,
the main thing necessary towards the redemption of the soul is
to wait to be made more and more acquainted with it,
so that in its stirrings, movings, and leadings,
the soul is made ready to be gathered into it, and to be guided by it.
For though this gift be all life, yet at first it is but as a seed,
and the appearance of the Lord in it is but as in a seed--very little, low, weak,
hard to be discerned, easy to be overlooked and despised.
A far greater and more undeniable appearance is usually expected, but that is not the way.
No, the soul must first become subject unto, and bowed under, this little appearance.
And as the seed gets advantage, and grows bigger and larger in the heart,
the appearance of the Lord will be greater and fuller there.
But to look for the greater appearance before the seed is known and
received in its lesser appearance (and the vessel thereby fitted for
the greater appearance) is not the way of God,
but rather the deceit of the enemy.
For the enemy desires to destroy the soul, and to cut it off from the Lord forever,
which he will certainly do if he can keep the seed from growing there,
and the soul from joining with and growing into it.

Therefore, watch to feel the savor of life in your heart day by day,
and to feel the leadings and drawings from the life that are suitable to your state.
For in this savor, and in these drawings, rises the true light,
which leads into the way of life.
And then watch against the reasonings and arguments
which the enemy will raise in your mind,
who will strive to make you a judge over these things.
For the light, which arises in the savor and in the drawings,
is your King (though in this low appearance), and he is not to be judged by the mind,
thoughts, and reasonings of man, but rather to judge them all down.
And consider, are you (in your darkness,
and with your earthly mind) fit to be a judge concerning the light which arises in you?
Or rather, is not the light, in its lowest and weakest appearance,
appointed and fitted by the Lord to judge you,
and make you bow down in fear and trembling before it?
And your crown (in your highest exaltation) is
fit to be cast at the lowest footstep of him.

Therefore, consider where you are,
and breathe unto the Lord to reveal that unto you which is proper for you at present.
Bow your spirit under his present will and his present manifestation to you,
and be content to be little and low, and to receive little and low instructions from God,
and to walk in the path of brokenness and humility before the Lord.
For this is his way of fitting you for, and advancing you into,
the high and glorious power of his life.
And this my soul is assured of, that none shall enter into, or abide in, his kingdom,
except as they become little, poor, and naked,
and as they are led by the little child of God's begetting.
For the Lord will not at all answer the wisdom of man and his expectations,
but will rather confound them,
and lead the soul on in such a path as the eye of man's wisdom cannot see.
But the one who disputes not, but believes, at seasons will feel a progress,
and will understand the growth of life advanced in the heart by those
very things which formerly seemed to give death the advantage.

Therefore, watch against your own understanding and all of its workings,
if ever you desire life.
For your understanding will still betray you,
and either keep you from the way or turn you out of the way, whenever you hearken to it.
And mark this: that which God sows and brings up in you is a tender plant,
not a knowing mind.
True and right judgment is only in the apprehension of that plant,
and not in the understanding or comprehension of your mind.
Yes, that sensitive plant (which your wisdom will be very apt to despise and
overlook) must batter down and bring to nothing your understanding,
and grow up in place of it, if ever your soul will be made a habitation for the life.

Therefore, sink into the feeling, dwell in the experience,
and wait for the savor of the seed of life, and the touches and drawings of the savor.
Walk along in this towards the land of life, parting with all,
leaving behind you whatever the savor of life opposes,
and entering into whatever the savor of life relishes.
And as you are led into this, and become subject to it,
so you will taste the Lord and feel the sweetness of his ointment,
and the peace of his nature, and the joy of the beginnings of his kingdom in your heart,
and the blotting out of your iniquities for his own name's sake.
For though the enemy may lay a load upon you,
and fill you as much as he can with his filth, and then lay it all to your charge,
yet the Lord considers the seed he has sown in you,
and the desire which he has wrought in your heart to be joined to it.
And he knows how weak you are in this hour of your darkness and captivity;
and the intent of his heart is to deliver you from all this,
and not to condemn you for it.

But oh take heed of limiting the Lord to give you the kind of
clarity or light that the natural understanding judges necessary!
Rather, be content with the light which arises in his savor,
and shines inwardly to your spirit in his drawing.
Be subject and bowed under the light of this drawing,
though it be ever so much against the light of natural understanding and reasonings.
True clearness of light is a state into which you must grow up;
but before you come to this, your own understanding must be darkened, confounded,
and brought to nothing.
Therefore, mark carefully this which follows:

The first work of the Lord is often to confound
the knowledge and understanding of the creature,
especially in those who have been steeped in natural wisdom and experience.
For if the Lord did not closely pursue these with darkness and confusion,
they would quickly begin to accumulate knowledge into the old storehouse again,
and so grow wise after the flesh, never learning the life of the Spirit.
And here it is not the Lord's desire that the leadings of his
Spirit be manifest and clear according to the flesh,
and to the fleshly understanding.
Indeed, if they were manifest after this manner,
would not the fleshly part just drink them in?
And so the man would live again, but the seed would not live.
For the seed gains its life (and its form and
perfection) in the man by the death of the man;
even by the natural man being hunted, and battered, and broken out of his wisdom,
and knowledge, and reasoning, and comprehension.
And so man becomes a fool or a child, being able to know nothing, retain nothing,
perform nothing, nor keep his standing, except as he is newly created, led, taught,
and preserved in the power, and by the presence of the life.

=== Concerning Spiritual Unity

[.discourse-part]
Question: What is spiritual unity?

[.discourse-part]
Answer: The meeting of two or more in the same spiritual nature,
coming together in one and the same spiritual center or stream of life.
When the spirits or souls of creatures are begotten by one power into one life,
and meet there in the heart, insofar as they meet in this way,
there is true unity among them.

[.discourse-part]
Question: In what does this unity consist?

[.discourse-part]
Answer: In the life, in the nature, in the Spirit wherein they are all begotten,
and of which they are formed, and where their meeting is.
The unity consists not in any outward thing,
or in any inward thing of an inferior nature,
but is found only within the limits and bounds of the same Spirit.
The doing of the same thing, thinking the same thing, speaking the same thing,
these do not unite; but only the doing, thinking, or speaking in the same life.
Yes, and even though the doings, or thoughts, or words be diverse;
yet if they proceed from the same seed and nature, there is a true unity felt therein.

[.discourse-part]
Question: How is the unity preserved?

[.discourse-part]
Answer: Only by abiding in the one life; only by keeping to the power, and in the seed,
from whence the unity springs, and in which it stands.
Here is a knitting together and a fellowship in the same spiritual center.
Here the diverse and different motions of several members of the body (coming from
the life and Spirit of the body) are known and acknowledged by the same life.
It is not keeping up an outward knowledge (or belief concerning things) that unites,
nor keeping up an outward conformity in actions,
for these may be held and done by another part in man, and in another nature.
But it is by abiding in and acting in that which did at first unite.
In this there is neither cause nor room for division;
and he that remains within these limits cannot help but be found in the oneness.

[.discourse-part]
Question: How is the unity interrupted?

[.discourse-part]
Answer: By the interposition of anything of a different nature or spirit from the life.
When anything of the earthly or sensual part comes between the soul and the life,
this interrupts the soul's unity with the life itself,
and also interrupts the soul's unity with the life as it is working in others.
Anything of man's spirit, of man's wisdom, of man's will,
not bowed down and brought into subjection,
and so not coming forth in and under the authority and guidance of life,
in this there is always something of the nature of division.
Indeed, the very knowledge of truth held forth by man's wisdom, and in his own will,
outside of the movings and power of the life, this brings a damper upon the life,
and interrupts the unity.
For the life in others cannot unite with this in spirit,
though it may acknowledge the words to be true.

[.discourse-part]
Question: How may the unity be recovered, if at any time it is lost?

[.discourse-part]
Answer: In the Lord alone is the recovery of Israel,
from any degree of loss in any kind and at any time.
He alone can teach to retire into, and to be found in,
that wherein the unity is and stands, and into which division cannot enter.
This is the way of restoring unity to Israel when any lack thereof is experienced:
everyone, through the Lord's help,
must return (in his own particular) to the seed of life,
so that there they may experience a washing from whatever has corrupted,
and a new begetting into the power of life.
From this the true and lasting unity will spring quickly,
to the gladdening of all hearts that know the sweetness of it,
and who cannot but naturally and most earnestly desire it.

Therefore,
the way is not by striving to gather many into the same apprehension concerning things,
nor by endeavoring to bring all into the same practices.
Rather, it is by being drawn into that Spirit wherein the unity consists,
which will bring it forth in the vessels that are filled and ordered by it.
In this Spirit let all wait for the daily new and living knowledge,
and for the ordering of their lives and practices in the light.
And in this way, the life will be felt,
and the name of the Lord praised in all the tents of Jacob,
and there will be but one heart, and one soul, and one spirit, and one mind,
and one way and power of life.
And the Lord will be acknowledged in what he has already wrought in every heart,
and hearts will contentedly wait for his filling up of whatever is lacking in any.

So may the living God (the God of everlasting tender compassions to
Israel) fill the vessels of his heritage with his life,
and cause the peace and love of his holy nature
and Spirit to descend upon their dwellings.
And may his life spring up powerfully in them towards his living truth,
and towards one another.

And let all strive to excel in tenderness, and in long-suffering,
and to be kept out of hard and evil thoughts one of another,
and from harsh interpretations concerning anything relating to one another.
Oh this is unworthy to be found in an Israelite towards an Egyptian;
but it is exceedingly shameful and inexcusable
to be found in one brother towards another!
How many weaknesses does the Lord pass by in us!
How ready is he to interpret everything well concerning his disciples
that may bear a good interpretation! "`The spirit,`" he says,
"`is willing, but the flesh is weak.`"
When they had been all scattered from him upon his death,
he did not afterwards upbraid them, but sweetly gathered them again.
Oh dear friends, have we received the same life of sweetness?
Let us bring forth the same sweet fruits, being ready to excuse,
and to receive what may tend towards the excusing of another in any doubtful case.
And where there is any evil manifest, wait, oh wait, to overcome it with good!
Oh let us not spend the strength of our spirits
in complaining of one another because of evil,
but rather watch and look to where the mercy and the healing virtue will arise.
