== Chapter XV. How to Discern the Teachings of Christ

I have been afflicted from my childhood, mourning and seeking after the Lord,
and feeling very much grief and pain of spirit through my sense of the lack of him.
I was not contented with the way of religion in which I was educated,
but (through something from God which then stirred in me) I found great defects in it,
and was drawn and led by his Spirit to travel through it, and seek further.
That which I sought after was the resting place, the true life of my soul,
the power and presence of the Lord,
the same demonstration of his Spirit (with regard to the truth and
the way of God) which was witnessed in the days of the apostles.
Yet, breathing after this and not meeting with it caused unutterable anguish, misery,
and distress in my heart, so that my condition could not be hid within my own breast,
but my sorrow also broke forth in the sight of others.

But at length, the eternal mercy of God pitied me,
and showed me the place of the soul's rest,
and I have felt the eternal arm gathering me into,
and giving me some possession of what I had long sought after.
So that now my heart is satisfied about religion and the things of God's kingdom,
being taught of God how to know the Pearl,
and the way also how to come to inherit and enjoy it.
In this way I have had great experience of the love, mercy, wisdom, goodness, power,
and righteousness of the Lord.
And notwithstanding all my soul's enemies, I still feel his presence, life, and power,
to his praise, which does the work in me, and which gives me ability to hope in him,
and wait upon him.
And now, in love and tenderness of heart to others,
it is in my heart to answer a question or two about the ground
of the assurance and satisfaction that God has given my soul.
It is not my desire to grieve or trouble any,
but only to be helpful in holding forth what the
Lord has demonstrated to and written in my heart.

[.discourse-part]
Question: It may be inquired by some, how I came to know the Spirit of God,
and his church,
and the Scriptures of the holy men to be written by the
inspiration and leading of his Holy Spirit.
Also, it may be inquired how it is that I discern the motions
and drawings of his Spirit in me from the motions,
suggestions, and temptations of the evil spirit;
and how I am satisfied that I am in the eternal way of truth and life,
and do not wander out of it, or err from it.

[.discourse-part]
Answer: This is the way that I know: by receiving, joining to, abiding and growing up in,
that holy seed which the Father of spirits has sown in me.
There is an elect seed which cannot possibly be deceived, which seed the Father sows,
and causes to grow in the hearts of those who receive
it (whose ground is by him tilled and prepared for it).
Now, I have felt this seed from God, this holy and pure thing,
which there is nothing like for virtue and excellency.
Nothing has its nature besides it; nothing manifests the Father but it.
And the heart is changed, renewed, restored into the holy image by this seed alone.

In this seed there is no deceit.
No deceit ever came from it; no deceit ever entered into it, nor can enter it.
And from the day that I have known it, I have always felt preservation by it,
as long as my heart has been kept to it.
My eye never mis-saw in it, my ear never misheard in it,
my heart never misunderstood in it.
But in this seed I have felt given to me, and maintained in me by God,
the eye which sees, the ear which hears,
and the heart which understands the things of his kingdom.
And here the entrance has been ministered into the everlasting kingdom,
where God reveals by his Spirit the mysteries of his
kingdom (from which all are shut out except the seed,
and those born of it).
And when the enemy has at any time in my travels, by any temptation or device,
got in any degree between my soul and this seed, then a darkness, a loss, doubts, fears,
troubles, etc., have in equal measure come over my soul.

[.discourse-part]
Question: But how do I know this seed?

[.discourse-part]
Answer: By its nature, by its properties, by its manifesting of itself in my heart.
It has that light, that life, that power in it, which I never met with anywhere else.
It bruises the head of the serpent at its pleasure,
whereby I know it to be the seed of the woman.
It dashes in pieces (through subjection to it) whatever is contrary to God,
and brings up his holy nature in me.
It so brings me into the very image of his Son,
that what I read in the Scriptures concerning the nature, righteousness,
and work of salvation by Christ, I also find formed and springing up in my own heart,
as I am gathered into, and brought forth in this seed.

Here in this seed, I feel, know, understand, and am acquainted with,
the substance of that which all the types and figures of the law put forth in shadow.
Here I meet with the circumcision which is without outward hands,
the baptism which is without outward water,
the supper of the Lord which is without outward bread or wine.
Here I know the true Jew, whose nature, spirit, works, and ways are all of God,
in and through his Son, Jesus Christ.
And here I must profess that I cannot doubt concerning the things of God.
For in the light and anointing of this seed I see both
the mystery of iniquity and the mystery of godliness,
and the ways and workings of each spirit, both inwardly and outwardly.
And I see my unity with the one (through the tender mercy, goodness, love,
and power of the Lord, all which are herein revealed), and my separation from the other.

Now this is the true way of certainty and satisfaction which is of God,
and it will stand when all the several ways of men's
inventions fail in what they promise to men,
and fall in the sight of men.
For this seed and birth of God are to be acknowledged, and reign in the day of his power,
and not another.
And it is now the day of his power in some,
and shall soon be the day of his power in others.
For darkness or death shall not prevail to bring
the life of the risen Son into the grave again;
but he shall ride on conquering and to conquer, subduing and to subdue,
reigning and to reign,
until he has brought all things under the dominion of the Father's power.

=== The Way of Knowing the Motions, Doctrines, and Teachings of Christ's Spirit

[.discourse-part]
Question: How may a man know the motions, doctrines,
and teachings of Christ's Spirit inwardly, from the deceitful movings, appearings,
and workings of a contrary spirit?
And how may a man know concerning the doctrines that others teach,
whether they speak from Christ, or whether they speak from themselves?

[.discourse-part]
Answer: This is a great matter indeed,
and he that is able to discern in this matter must first receive something from God.
He must be born of the wisdom that is from above,
he must receive a spirit of discerning from God,
he must receive something of the sheep's ear, the holy understanding,
whereby he may distinguish spiritual things, between the pure and the impure,
between the pretender to the things of God and him who is indeed of God.
There is a balance of the sanctuary appointed to weigh spiritual things and appearances.
By this balance alone are all things truly and rightly discerned and distinguished;
and this balance is in the sanctuary, in the holy, heavenly place in Christ Jesus,
where the true weight of spiritual things is given and discerned.
But he that weighs without this, he that weighs by his own judgment and understanding,
by his own comprehension and conceivings, this one weighs by that which is uncertain,
changeable, and fallible.

Oh that men were humble, tender,
meek and sensible of their inability to judge as of themselves!
Then they might see the need of this gift of God, and wait upon him for it,
being in the meantime as a weaned child, not meddling with things too high for them,
but keeping and abiding low,
in fear and subjection to that which the Lord has already made manifest to them.
For what man is there to whom the Lord has not already, in his tender mercy and goodness,
made something of himself manifest?
Who is there who, by the light of the Spirit of God in his conscience,
knows not some evil which he ought to leave undone, and some good which he ought to do?
Now this is the way of God, and the work which man should be exercised in:
to experience his mind gathered into that which teaches this,
that he might receive power from the Lord to cease to do the evil and learn to do good.
For in this way the Spirit of the Lord teaches and requires of men,
even inwardly in their secret parts,
secretly quickening and enlivening them in some measure,
and also giving them a sense of their sin, death, and separation from him.
For where there is any sight of sin, and any sense of its burden,
there is also some life, some light, some little stirrings of the life,
without which this sense could not be.

Now mark: are not here the drawings of the Father?
Are not here the teachings of the Father, though but in a little measure,
yet true and living?
Is not here some little discerning given between the precious and the vile,
between that which is of God and that which is against him?
Well then, here is the gift of discerning, though in a poor, low, little, weak measure.
And the man who receives this,
receives the beginnings of the gift whereby he may be
able to discern and distinguish about spiritual things,
so far as the light and ability of the gift in him extends.

Now, this is man's work (and in this lies his safety), to come here, abide here,
and grow here.
He is not to judge outside of this,
nor judge further concerning the things of God than this light judges in him.
He must keep to the judgment he has from the Lord,
not hearkening to the subtle devices of the enemy,
which will strive afterward to cloud his mind,
delude and deceive him with a false appearance
of wise reasonings and disputings of his own,
or from other men, to make him believe otherwise.
And so keeping what ground he has gained, he is to wait for more of this light,
more of this life, more of this virtue, that his soul may grow up and increase therein,
that his eye may be strengthened to see further, and his ear to hear further,
and his heart to embrace more of the instructions and
directions of the Spirit of the Lord,
unto and in the way of the kingdom.

Therefore,
the man that desires to meet with and receive from God the gift of discerning,
let him mind the present manifestation of God's light from his Spirit in his heart.
Let him embrace that, fall in with that,
take heed of the reasonings of the mind against the
convictions and demonstrations of God's Spirit.
Receive the truth in the love of it, even the lowest appearance of truth,
about the least and most despicable things,
and give up faithfully to the Lord therein without murmuring, disputing,
or consulting with flesh and blood.
And he that is faithful to the light of the Spirit (and
to the discerning that comes by it) in the little,
he shall receive more,
he shall have his light and discerning thereby increased according as his need requires.
But he that stands disputing,
and desires to have all his way made clear to him before he takes one step in it,
this one is far from becoming that child that the Father can teach.

This, in effect,
was the very answer which Christ gave to this thing in the days of his flesh,
when there were great disputes concerning his doctrine,
how to know whether or not it was of God.
What was the way he resolved this question?
"`If anyone is willing to do his will`" says Christ, "`he will know of the teaching,
whether it is of God or whether I speak from Myself.`" John 7:17.
Do you desire to know of the Son's doctrine?
Do you desire to know whether it be the doctrine of the Son indeed,
the doctrine of him who comes from the Father?
"`Yes,`" the upright heart will eagerly say,
"`oh that I might know concerning what rises and opens in my heart,
whether it be from the Spirit of God, or from the root of deceit in me!`"
This then is the way: do the Father's will.

[.discourse-part]
Objection: Do the Father's will?
Why, what kind of an answer is this?
The entire dispute is about the Father's will!
How can I do the Father's will
(which the Son is supposed to teach me)
until I first know of the Son's doctrine?

[.discourse-part]
Answer: It is true, the Son's doctrine is the Father's will,
and you cannot do the Father's will except as you receive the Son's doctrine.
But mark well: there are disputes in your mind about something of the Son's doctrine,
whether it be his doctrine or not.
There are disputes within you concerning the inward motions, workings, and stirrings,
the origin of which you eagerly desire to know.
Now, the question at hand is concerning the way that you may attain to this, that is,
how you may come to a certain and satisfactory knowledge of these things.
The way is not by entering into reasonings and disputes
about the things wherein you have doubts,
but by coming into that light wherein and whereby these things are made manifest.
And this is by coming into obedience to the Father in
that which he has already made manifest.
For in that light (to them that believe in it),
and in obedience to it (be it ever so little, or the manifestation ever so small),
the Father will reveal even more.
And he will make that heart and mind to be sensible of what is of him,
and what is of the enemy, so far as it is needful in that moment for it to know.
For wise and absolute judgment in all things is not necessary for a baby,
but only enough sense to know the breast,
and to receive from it the milk by which it is to be fed that it may grow.
This is enough in its present state.
Yet if there be need of strength at any time to stay the enemy,
the Lord will reveal it in the heart,
and bring it forth out of the mouths of the babes to the perfecting of his praise.

So mind and learn the way,
you who are simple-hearted and truly desire after the Lord,
and the purity and power of his kingdom.
Take heed of the wrong way; take heed of man's way,
which is by consulting with his own wisdom,
and weighing things in the balance of his own reason and understanding.
In this way man may weigh the scriptures written in former ages,
and the appearances of God in this age, and err in heart, mind,
and judgment concerning them both all his days.
But he that waits on the Lord in fear,
and in obedience to that which is already made manifest,
not desiring knowledge from God in his own will, time, or way, but in the Lord's,
who perfectly knows everyone's state,
and what is fit for him--this one shall know concerning
every doctrine his heart desires to be instructed in,
in the Lord's season.
And in the meantime,
the Lord will feed him with necessary food and clothe him with necessary clothing.
Indeed,
there shall be no lack to him who bows before the Lord in what is already made manifest,
and who waits for the Lord's further manifestations and appearances.
But the wise hunter after knowledge, going out before the Lord leads,
and further than he leads and teaches--this is of the first birth,
which is excluded from the kingdom and its mysteries.
This comes from the despised one, who would still kill the heir,
so that the inheritance might be his.
But the inheritance is appointed for and given to another, even to the Lamb's nature,
the Lamb's Spirit, the Lamb's innocency, the birth of heavenly wisdom,
which birth is a foolish and weak thing in man's eye,
and not at all worthy of the inheritance.
But it is the Father's pleasure to give the kingdom and
inheritance of life everlasting to such as these.

Allow me to speak yet a little more plainly,
and to bring it yet a little closer to the heart, if I may.
It has pleased the Father, in this day of his love and power,
to gather a little flock out of the world (and out of all
worldly professions of worship and religion) unto himself.
This flock he has gathered by a poor, little, low thing in their hearts,
exercising them thereby in poor, menial, and contemptible ways to the eye of the world,
and to all the professions of man's wisdom.
And by this little and low seed, and concerning it,
the Lord testifies to others through those whom he has gathered.
And the testimony does evidence itself, through the power of the Spirit,
to all that wait upon God for an ear to hear.

Now, when we tell men of a divine seed, given of God,
wherein their religion is to begin, and from which it is to grow,
and of which they are to be born,
many will assent and be drawn so far as to wait inwardly for and upon this.
But when this seed begins to stir and move in them, it is often in such a way,
and having to do with such low, menial, contemptible things in their eyes,
that they are very apt to despise it, enter into disputes against it,
and so miss the entrance.
Instead, they are filled with doubts about the leader and his motions,
and puzzled and entangled in their minds, and stopped at the very beginning.
And so, though they desire much, and hope much,
yet all of this comes to little because the enemy has
possessed their minds with a device of his subtlety,
as if the things made manifest by the seed were small and of little importance.
That which they lack (so they believe) is the powerful manifestation of life,
the clear light, etc.,
and so their minds are taken up with expectations for these great things,
and desires after lofty things,
and they overlook the way whereby these are to be witnessed and obtained.

For the Lord God, in his infinite wisdom,
selected these contemptible things by which to exercise and lead his flock.
Now friend, you who desire life from God,
oh take heed that you do not beat back the beginnings of his life and the
redemption of your soul by despising and overlooking the day of small things!
Why may not God choose to lead you in the way that he has led the rest of his flock?
Why should you not also come to deny the customs and vanities
of this world (and come into that which is simple and plain),
and stand in the will and life of God out of them?
Are not the ways, customs,
and vanities of the world from the spirit of the world and not from the Father?
Do they not come from the corrupt part?
Are they not of the corrupt part?
Do they not please the corrupt part?
Must they not be left behind by him that travels into the seed, is one with the seed,
and lives in the seed?
Why get stuck on these things?
Why would you dispute about these things?
Oh feel the Father's drawings, first out of the world,
first out of that which is not of the Father but of the world,
so that he may draw you further and further, even into the kingdom and power everlasting,
which is many days' journey beyond the place where you now are stuck.

So mind and remember this which follows: In the days of Christ and his apostles,
God chose the foolish and the weak things, and things that were not,
to hide the path of life and the mysteries of his kingdom from the wise,
searching eye of man in those days.
Why may he not choose similar things now?
Why may he not now reveal things to the babes,
and not to the wise of this age and generation?
Why may it not be to his glory to have it now said also: "`Where is the wise?
Where is the scribe (where is the learned man)?
Where is the disputer of this world?`"
Can any of them find out, or any of them discern,
that which God reveals to his little ones?
No, no!
They have gotten up too high above that little, low, tender, meek, sensible seed,
in the faith of which, and in obedience whereto, the teachings of God are received,
and his life and power witnessed.
And because of the riches, wisdom, and knowledge already gained outside of this seed,
the entrance into the pure, living truth (which cleanses the mind, and keeps it clean,
which quickens it, and keeps it living) seems to them so exceedingly difficult.

And as the seed of the kingdom is little (like a grain of mustard seed),
the least of all seeds, why may not its appearance also be little, even in low,
weak things, despicable to man's eye and wisdom?
And yet, the power of the cross (which brings down and slays the corruptible),
and the resurrection of the life may be witnessed and felt in them.
"`The foolishness of God is wiser than men,
and the weakness of God is stronger than men.`"
And the Lord knows what he does in leading his children in this contemptible path,
and by these contemptible exercises, which all the wise, high, lofty, and aspiring,
according to the flesh, may easily overlook and slight,
and can hardly stoop down and subject themselves to.

God is the same that ever he was;
and he still appears in the way of his own wisdom,
and outside of man's. He that will partake of
God's wisdom must deny and keep out of his own.
The Lord's touches, drawings, teachings, blessings, love, peace, joy, sweetness, etc.,
are poured forth upon, felt, and enjoyed by the soul in the new creation,
in the new sense, in the denial and passing out of the old.
