== Chapter XVI. Letters of Isaac Penington / Written Between 1658 - 1671

[.letter-heading]
To His Father, Sir Isaac Pennington Sr.^
footnote:[Isaac Penington`'s Father (Sir Isaac Pennington Sr. 1584-1661) was a well-
known English politician and Puritan Congregationalist who sat on the House of
Commons from 1640 to 1653 and was Lord Mayor of London in 1642 and 1643.
He was a member of the tribunal that convicted Charles I of treason and executed him,
and afterwards became a prominent member of Oliver Cromwell`'s government.
With the Restoration of Charles II in 1660,
Pennington Sr. was tried for high treason and imprisoned in the Tower of London,
where he died awaiting execution on December 16, 1661.
(Isaac Penington Jr. dropped an "`n`" from his name,
perhaps so as not to be confused with his father.)]

[.salutation]
Ah, dear Father!

Why do you so often give me occasion of mourning before the
Lord on account of your hard and unrighteous charges?
How often have I solemnly professed that there was never any desire in me,
or endeavor used by me,
to draw you to this way +++[+++of religious profession]. All that is in my soul is this,
that you might have the true knowledge of Christ, that you might indeed hear his sayings,
and do them,
and not set up your own or other men`'s imaginations and
invented reasonings instead of the sayings of Christ.

Now, I am not for ways or opinions, but only for Christ the substance,
the living power of God in the heart.
Yet, because you stumble at these things,
and through prejudice refuse the living testimony of God concerning Christ the Rock
(building instead upon that which you have imagined concerning the Savior),
in love and pity to your soul, I cannot but say some things to you.
For who knows whether God may, at length,
give you repentance to the acknowledgment of the truth,
and to the disclaiming of the way of error.

You lay down three reasons why you cannot believe this way to be of God.

[.discourse-part]
1+++.+++ God`'s way is a way of love, peace, and unity.

[.discourse-part]
Answer: If you had that eye which can see the things of God,
and did apply yourself to see with it, you might see the peace, love,
and unity among this people which other men do only talk of.
But if you take things by the report of the enemies both to God and to them,
you shall be sure to hear and believe bad enough.
For this people +++[+++the Quakers, so-called]
have no war with anything but unrighteousness, and with that they cannot have peace, no,
not even in their dearest relations.
They love the souls of their enemies,
and think no pains or hazard too great for the saving of them.
Being persecuted, they bless; being reviled, they entreat, and pray for their persecutors.
They are at unity with whatever is of God; but with the seed of the serpent,
they cannot be at unity.
They know the "`generation of vipers`" in this present age and
can witness against them under their several painted coverings,
as freely as ever Christ and his apostles did against the Scribes and Pharisees.
For the spirit of the Scribes and Pharisees is now in the world;
and the Spirit of Christ and his apostles is also in the world.
And these cannot help but fight, each with their proper weapons:
the one with their stocks, whips, fines, prisons, etc.,
the other with the spiritual armor of Christ.
Thus the one wrestles with flesh and blood, fights with the creature, and hurts the body;
the other loves the creature, seeks the saving of it,
and fights only with the power of darkness which rules the creature.
Now which of these are the ministers of Christ?
Those who stir up the magistrate to afflict the body,
or those who use the sword of the Spirit to strike the conscience?

And this peace, love, and unity are attained,
not by their own strivings after it, but by receiving it from above.
Indeed, all our religion lies in receiving a gift,
without which we are nothing and can do nothing, and in which nothing is too hard for us.
Yes, being kept in that gift of God we can do all things, we can believe all things,
we can suffer all things.
Never was there a generation brought forth weaker in themselves, more foolish,
more ridiculous to the fleshly wisdom,
more exposed to sufferings from the world and worldly professors.
Yet, being kept faithful to him that has called us,
we sometimes feel strength and wisdom,
even such as the most zealous in the worldly ways of
religion have not an ear to hear the relation of.

[.discourse-part]
2+++.+++ God`'s way is a way of humility.

[.discourse-part]
Answer: If they had not been broken and humbled by God,
they could never have entered into this way, which is a way that the lofty,
fleshly part of man abhors.
Nor is this a voluntary humility,
but a humility which crosses and breaks man`'s will all the day long.
You judge at a distance, and with that which should not judge,
but should rather be judged.

[.discourse-part]
3+++.+++ That God is a God of order, not of confusion.

[.discourse-part]
Answer: Blessed be the Lord, who has recovered some of the true church`'s order for us,
and delivered us out of the confusion of antichrist.
We know an order in the light, an order in the Spirit, an order in Christ the truth.
But that which man in his wisdom calls order is but antichrist`'s order, which, to God,
is confusion.
To have man`'s spirit speak and God`'s Spirit stopped,
this is the order of all the anti-christian congregations and churches.
But to have man`'s spirit stopped and God`'s Spirit speak,
this is the order of Christ`'s church.
And this order we know and rejoice in,
finding that raised in us which teaches us to "`cease from man,`"
and man`'s voice is not at all "`accounted of.`"
But the voice of the living God is heard, known, loved, and obeyed,
by that which he has quickened in us, and made to live to himself.

The last part of your letter consists of very harsh and unrighteous charges,
mixed with bitter expressions,
which I shall pass over--only I confess it is somewhat hard to one part of me,
that my own father should so deal with me.

About finding no comfort in me, and wishing me more comfort in my son,
I must say this.
There is a part in me which God has struck at, and is destroying,
and I myself have no comfort here, nor is it much able to yield comfort to anyone else.
If I were in any formal way of religion,
I might be a comfort to my father (for you could be gratified with that,
or at least bear with that).
But because the Lord has seized upon my heart by the power of his Truth,
and I can bow to none but him (no, not even to my most dear father), now I am no comfort.
I am sure I have had little comfort all my days in seeing my father`'s course of religion,
which I ever could testify of as not being of God (yes,
my late dear mother would often bewail it to me).
And many times have I poured out my soul before the Lord.
Yet hear my words, Oh my father, hear my words.
Oh, pierce into the nature of things!
Set not up shadows instead of the truth.
Wait for the gift.
Receive the true love, the true peace, the true unity, the true humility,
(which lies not in the will of the creature, but rather destroys it),
and we shall soon know one another, and have true comfort in one another.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
14th of 12th Month, 1658

[.letter-heading]
To Thomas Ellwood

[.salutation]
Dear Thomas,

Great has been the Lord`'s goodness to you,
in calling you out of that path of vanity and death (wherein
you were running toward destruction),
to give you a living name and an inheritance of life among his people,
which certainly will be the end of your faith in him and obedience to him.
And let it not be a light thing in your eyes that he now
accounts you worthy to suffer among his choice lambs,
that he might make your crown weightier, and your inheritance the fuller.
Oh that that eye and heart may be kept open in you which knows the value of these things!
And oh that you be kept close to the experience of the life,
and be fresh in your spirit in the midst of your sufferings,
so you may reap the benefit of them.
This is a brief salutation of my dear love to you,
which desires your strength and settlement in the power of God,
and the utter weakening of you, as to yourself.
My love is to you, with dear Thomas Goodyare, and the rest of the imprisoned Friends.^
footnote:[Whenever the word '`Friends`' is capitalized in these letters,
Penington is referring to members of the Society of Friends (Quakers).]

I remain yours in the Truth,
to which the Lord my God preserve me single and faithful.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From Aylesbury Jail, 14th of 12th month, 1660

[.letter-heading]
To an Unknown Parent

[.salutation]
Dear Friend,

I have not much freedom to write at present, being retired in spirit,
and mourning to my God for the powerful bringing
forth of his pure life yet more perfectly,
both in myself and others.
Nevertheless, the spirit of your letter does so strongly draw me,
that I cannot be wholly silent.

This, therefore, in the uprightness, fear, and tenderness of my heart,
I say to you.

There is a pure seed of life in the heart, from whence all good springs.
This you are to mind in yourself,
and also to wait on the Lord to be taught and enabled
by him to reach to this seed in your children.
In this way you may be an instrument in the Lord`'s hand to bring them into
that fear of him which is both acceptable to him and profitable to them.
Therefore, mind its leadings in your heart,
and wait to be acquainted with its voice there.
And, when your children ask you any questions of this nature--what God is,
where he dwells, or whether he can see them in the dark--do not reject it,
but wait to feel something of God raised in you which is able to
judge whether the question is put forth in sensibility or in vanity.
And this can give you an advantage of stirring up the good,
and reaching to that which is to be raised both in young and
old to live to the praise of him who raises it.
Take heed of a judgment after the flesh,
but wait to feel that seed raised in you which judges
with righteous judgment in every particular case.
Be still and silent except when you manifestly
know that the seed (and not you) is judging.

And, as to your children,
daily feel the need of instruction from the Almighty to govern and direct them,
and wait daily to receive it from him.
And what you receive from him, give it forth in fear,
waiting for him to work it upon their hearts.
For he is a Father, and has tenderness,
and gives true wisdom to every condition of his people that wait upon him.

Perhaps you expect from me an outward rule,
but I have no rule except the inward life.
And this life is known not in the way of outward knowledge,
but is daily made known as my Father pleases.
I cannot direct you to any other rule,
except to wait that life may be revealed in you daily,
according to your daily need in every particular.
And this I say to you in the love of my heart: wait, oh wait,
for the true discerning which is given to the true seed (which you
will experience according as it is raised and gains dominion),
that the wrong thing does not judge in you,
having an outward appearance of wisdom and reason.

Breathe unto the Lord that your heart may be single and your
judgment set straight by his seed of life within you,
and that your children also be guided to and brought up in the sense of the same seed.
And as for praying, they will not need to be taught that outwardly.
But if a true sense of the seed is kindled in them (though ever so young),
from that sense will arise breathings to him that begat it,
suitable to their current state.
This will cause growth and increase of that sense and life in them.

Thus, in the plainness of my heart have I answered you,
according to the drawings and freedom which I found there, which I dare not exceed.
I who am your unfeigned friend, though outwardly unknown,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
20th of Third Month, 1665

[.letter-heading]
To One Who Sent Him a Paper of Richard Baxter`'s

[.salutation]
Dear Friend,

Whom I often remember with love and meltings of heart,
desiring of God that you may enjoy in this world whatever of
his presence and pure life he judges fit for you,
and that your soul may, after this life, sit down in rest and peace with him forever.

I received from you a paper of Richard Baxter`'s, sent to me, I believe, in love.
And in love I am pressed to return unto you my sense thereof.
It seems to me very useful and weighty as far as it goes.
But indeed, there is a great defect in it,
in not directing sinners to that seed of life and power wherein and
whereby they may do that which he exhorts them to do.
For how can they come to a true awareness or to repentance,
or join in covenant with God through Christ,
until they know and receive something from God wherein this may be done?
Oh my dear friend, I wish that he, and you,
and all who in any measure turn from this world and desire life eternal,
might know the instruction of life, and feel that gift from God wherein he is known,
loved, and joined with in covenant.
In this way you can know a pure beginning, a pure growth and going on unto perfection,
and not mere notions concerning things set up in the earthly understanding,
which easily putrefy and defile.

And whatever men may say or think of me,
I have no other religion now than I had from the beginning;
only now I have a clearer leading into, and guidance by,
that seed of life in and through which it then pleased the Lord to give me life.
And this I know (and do daily experience in my heart):
that this is no less than the light of the everlasting
day in which the renewed man is to walk,
and no less than the life of the Son (whom God gave a ransom for sinners),
which can quicken man so to do.
And none but Christ, by his life revealed in the soul,
and his blood shed there to wash it, can save the poor sinner from sin, wrath,
and misery.
My hope is not in what I have done, do, or can do; but in what he has done without me,
and also does in me.

This is the account of my love unto you,
drawn forth at this time by the outward expression of yours in sending that paper,
who remains, and, from my first acquaintance, have ever been, a friend and lover of you.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Peter`'s Chalfonte, 19th of Sixth Month, 1665

[.letter-heading]
To His Wife

[.signed-section-context-open.centered]
(Written on Occasion of His Fourth Imprisonment)

[.salutation]
My dear true love,

I have hardly freedom to take notice of what has happened,
even in my own thoughts; but I am satisfied in my very heart that the Lord, who is good,
has ordered things this way, and he will bring about what he pleases thereby.
Why should the fleshly-wise, reasoning part murmur, or find fault?

Oh be silent before the Lord all flesh within me!
And disturb not my soul in waiting on my God to know what he is working in me and for me,
and what these cruel occurrences can lead to.

One thing have I desired of the Lord, even that I may be his,
perfectly disposed of by him, knowing nothing but him,
enjoying nothing apart from his life and leadings.
Thus must I give up and part with even you, my most dear and worthy love,
or I cannot be happy in my own soul or enjoy you as I desire.

I find my heart deeply desiring and breathing
after the pure power of the Lord to reign in me;
yet I dare not choose for myself, but rather beg to be taught to wait,
and to be made willing to drink the residue of the cup of suffering,
both inward and outward, until the Lord sees good to take it from my lips.

Oh, my dear, say little concerning me.
Plead not my cause, but be still in your own spirit,
and await what the Lord will do for me.
Thus all my prayers (which in the tenderness of my soul I have
often put up for you) may have their full effect upon you.
My dear, be my true yoke-fellow, helpful to draw my heart toward the Lord,
and away from everything except what is sanctified by
the presence and leadings of his life.

I feel, and you know that I am, very dearly yours.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
1st of Seventh Month, 1665

[.letter-heading]
To a Friend in London

[.signed-section-context-open.centered]
(Written on Occasion of the Plague, 1665)

[.salutation]
Ah Friend!

Dreadful is the Lord, and it is now known and felt beyond what can be spoken.
Does your heart fear before him?
Are you willing to be subject to him?
Do you long for his strength in order to trust him with yourself and your family?
Oh that you may be helped daily to cry unto him,
that he who is tender-hearted and able to preserve may
have mercy upon you when his arrows fly round about!

Retire, deeply retire, and wait to feel his life,
so that your soul may be gathered out of the reasonings and thoughts of your mind,
into that which keeps from them and fixes beneath them.
Here the Lord is known and worshipped in that which is of himself, of his own begetting,
of his own forming, of his own preserving,
of his own shutting and opening at his pleasure.
And so,
living in the sense and pure fear of the Lord (not
meddling to judge others or justify yourself,
but waiting for his appearance in you, who is the justifier and justification),
you will be enabled by the Lord, in his seasons,
to lead your children and family into the same sense,
so that you and they together may enjoy the same preservation from him.

And if your heart be right before the Lord,
and your soul awakened and preserved in his fear,
you will find something to travel out of, and something to travel into,
and the Lord drawing and leading you.
And this stroke,
which is so dreadful to others (and not altogether without
dread to you) will prove of great advantage on your behalf,
in drawing you more into a sense and acquaintance of the infinite One,
and in drawing you from your earthly thoughts and knowledge,
which will not now support you.
Your Friend,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
8th of Seventh Month, 1665

[.letter-heading]
To Elizabeth Walmsley

[.salutation]
Dear Friend,

My heart was exceedingly melted within me at
the reading of your precious and tender lines.
Indeed, I was quite overcome, and was inclined several times to break off reading,
for the freshness and strength of life in your words did so flow in upon me.
And I said again and again in my heart,
"`It is the very voice of my Father`'s child,`" whose
sound did deeply reach to and refresh my very soul.
And this my heart says, "`Blessed be my God, for his tender mercies to you, in visiting,
leading, and preserving you to this day,
and for teaching his seed thus to speak in you.`"
Oh let his praise live and abound in your breast forever!
And in the flowings and streamings of this life,
remember me at the throne of my Father`'s mercy,
by which alone I live and have hope before him.

May the mercies, blessing, and pure presence of my God fill your soul,
and rest upon you forever!
Amen!
Amen!

Mind my dear love to your sister, whose inward welfare and prosperity I desire,
even that she may be one with you in the seed and life of God.

I am your unfeigned Friend, and dear lover of the pure seed of life in you,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 19th of Eighth Month, 1665

[.letter-heading]
To Friends at Horton

[.salutation]
To My Friends at Horton and Thereabouts,

There has been a cloudy and dark day,
wherein God`'s church and building has been laid waste,
and his holy city (according to his decree and
purpose) trodden under foot by the Gentiles.
All of this time, his church has been as a desolate widow, mourning in the wilderness.
Nevertheless, during this season, God has not left his people,
for there have always been breathings and
stirrings of life in and from the precious seed.
Yet though there were true desires and longings after the true church,
in the midst of these desires,
the enemy struck and put men upon pressing further ahead than they were truly led.
And so reading in the Scriptures about a church state and church orders, etc.,
they thought it was their duty to keep on building.
In this way they have thrust themselves into many things into
which they have not been accepted of the Lord (although,
in their breathings and true desires, they were accepted).
And what has been the result of man`'s buildings?
Oh, the pure seed has been buried in them, and they have been as a grave to it;
and their own imaginations, carnal knowledge,
and way of worship have been of high esteem.

Oh Lord my God, raise again, I beseech you, the pure life,
and those pure breathings which have been drowned, lost, and buried in these buildings!

Now, dear friends, the Lord alone built his church at the first.
The Lord also laid the buildings waste, and carried his living temple,
out of the shell of it into a wilderness.
And the Lord alone can lead his church out of the wilderness (leaning upon her Beloved),
into her built state again.
Ah dear friends, all must be scattered, all the gatherings,
all the buildings which are not of the Lord must be scattered, so that his gathering,
his building, may be known and exalted in the earth.
So then,
I desire that you not hold up anything in this day of the Lord
(it is so indeed) against the light and power of the Lord.
The Lord is able, and will maintain his building,
however weak and of low esteem it is in the eye of man.
But man shall not be able to maintain his buildings,
however high and strong they are in his own eye.

And since my spirit is at this time unexpectedly
opened in love and in life towards you,
I shall mention one or two great snares which I see professors entangled in,
so that you may wait on the Lord to escape the evil and danger of them.
One is this: they look too much at outward time and outward things,
and their expectations are too much that way.
Oh let it not be so with you, but wait for the inward day,
wherein the things of God are wrought in the heart!

Woe unto him that has stumbled at the living
appearance of God`'s precious truth in this our day,
and in his own wisdom has been exalted above
that which he should have fallen down before!
Oh that none of you (whom I have dearly loved, and still love,
and whom I have truly sought in the Lord,
and still seek) ever prove sad examples and
spectacles of what I now write in a living sense!
Oh that that seed which has mourned and is oppressed among you might live,
and rise up in the power of life, over that which has grieved and oppressed it!
For, of a truth, I feel among you a wisdom and knowledge which is not of the seed,
but rather oppresses it.
Oh what plainness of speech does the Lord give me towards you!
Indeed, I am melted in concern for you!
And in the strength of that love which searches into your bosoms,
I desire that the abominable thing among you might be discovered and purged out,
so that that which is indeed of God might spring up, live, and flourish among you.

A second thing, wherein professors grievously mistake,
is about praying in the name of Christ, in which name, he that asks receives,
and out of which name, there is no right asking of the Father.
They think that praying in the name of Christ consists in using some outward words,
such as, "`Do this for your Son`'s sake,`" or "`We beg of you in Christ`'s name.`"
But there are many who know not the Father, and yet use such words!
And there are others who are taught of the Father to pray, and who pray in the Son,
who are not led to use such words.
The name, wherein the asking and acceptance is, is living,
and he that prays in the motion of the Spirit,
and in the power and virtue of the Son`'s life, this one prays in the name.
Only this voice is acknowledged by the Father, and not the other,
who has learned in his own will, time, and spirit, to use words relating to the Son.

Ah friends, that you might travel into truth,
and meet with the unerring substance of things, so that you might live and not die!
Then you will see how man has erred, and errs, yes, even the man in you.
And you will see that the seed only, and they that are born of the seed,
know the living truth, and walk in the living path, where there is no error, no deceit,
but rather a perfect preservation out of them.
There, in the seed, I desire to meet and embrace you,
where we may unite and know one another, in the spiritual birth and life, inseparably,
forever.

I remain your imprisoned friend, according to the wisdom of God,
and in his pure content and fear,
though the wisdom of man might easily have avoided these bonds.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 22d of Eighth Month, 1665

[.letter-heading]
To Friends of Truth In and About the Two Chalfonts

[.salutation]
Dear Friends,

I am separated as to bodily presence from you, but I cannot forget you,
because you are written on my heart, and I cannot but desire your peace and welfare,
as of my own soul.

And this is my present cry for you:
Oh that you might experience the breath of life, that life which at first quickened you,
and which still quickens!
This breath of life has power over death, and being felt by you,
it will bow down death in you,
and you will feel the seed lifting up its head over that which oppresses it.
Why should the royal birth be a captive in any of you?
Why should any of you travail, and not bring forth?
Why should sin have dominion in any of you,
and not rather grace reign in its life and power in you all?
Oh that you may receive quickenings!
Oh that you may receive help!
Oh that you may be led into the true subjection, which brings forth the true dominion!
Indeed, I cry for my own soul, and I cry for yours also,
that in one virtue and power of life,
we may be knit together and serve the Lord our God in perfect unity of spirit.

Oh Father, blow upon flesh in us all, dry it up at the roots,
let all that is born of it die in us, and let its womb become barren,
so that no more fruit may be brought forth unto death and unrighteousness.
And let your pure seed live in us, and the womb that has been too long barren,
let it abound with fruit unto you, so that we may be a vineyard of your own planting,
watering, and dressing, bringing forth pure holy fruits, pleasant to your taste.
Oh Father, that you may never repent of the special love, favor,
and mercy you have shown to us,
in gathering us out of the world and from the midst of the many professions.

My friends, what shall I say unto you?
Oh, the Lord keep you living and sensible, and let your walking and living be with him,
both in private and in your assemblies.
Be serious in your spirits,
that you may feel the weight of his seed springing up in you and resting upon you,
to poise your hearts towards him.
And let the earthly thoughts, desires, and concerns, which eat like a canker,
be kept out by the power of that life which is yours,
as you abide in covenant with him that has gathered you
by his pure light shining within you.
Oh that you may all dwell there, and not draw back into the earthly nature,
where the enemy lies lurking to entangle and catch your minds, and bring you to a loss.

Feel my heart of love and tender care for you in the quickening life of God.
And may the Lord God watch over you for good, to perfect his work in you,
and draw your hearts nearer and nearer to himself,
until they be quite swallowed up by him, and you find your hearts fitted for,
and welcomed into, the bosom of your Beloved.
There you may sit down in the rest and joy of his fullness forevermore.
This is the blessed end of the Lord`'s love to you,
and all the faithful travails which have been for you.

Even when you were sitting together and waiting on the
Lord did these things spring up in my heart towards you.
And if you taste any sweetness or refreshment in them, bow to the Fountain,
and be sensible of his praise springing in the midst of you.
Your Friend and brother in the Truth,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From my place of confinement in Aylesbury

[.signed-section-context-close]
20th of Fourth Month, 1666

[.letter-heading]
To Elizabeth Walmsley, of Giles Chalfont

[.salutation]
Dear Friend,

The thoughts of you are pleasant to me.
Indeed, I am melted with the sense of the Lord`'s love to you, as to my own soul.

What were we that the Lord should stretch forth his arm to us and gather us?
And what are we, that the Lord should daily remember us,
in the issuing forth of his lovingkindness and mercies?
Oh his pity, his compassion!
And can you not also say the same?
Dear friend,
my desire for you is that the power and blessings of life may descend upon you,
and that you may feel your God near, and your heart still ready to let him in,
and shut against all that is of a contrary nature to his.
Oh and that you may know that death passing upon you, and perfected in you,
which prepares for, and lets into, the fullness of his pure and unspotted life.

You may commend my dear love to your sister,
and to all Friends as you have opportunity, who breathe after the Lord,
and desire in uprightness of heart to walk with him.
I am your friend, in the affection which is of the Truth.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury, 20th of Fourth Month, 1666

[.letter-heading]
To the Earl of Bridgewater^
footnote:[The Earl of Bridgewater was the man principally responsible
for several of Isaac Penington`'s long imprisonments.
Because Penington would not bow to him,
address him as "`My Lord,`" and refer to himself as "`your humble
servant,`" the Earl of Bridgewater procured military orders to have
Penington arrested and jailed on several occasions.
In total, Isaac Penington spent close to five years in jail, usually at Aylesbury,
but once at Reading.]

[.salutation]
Friend,

It is the desire of my heart to walk with God in the true
fear of his name and in true love and good will to all men,
all my days here upon the earth.
For this end I wait upon God night and day to know his will,
and to receive certain instruction from him concerning what is acceptable in his sight.
After he has in anything made manifest his pleasure,
I wait upon him for strength to perform it.
And when he has wrought it by me, my soul blesses him for it.
If this be a right course, I am not to be condemned herein.
But if it be not, and you know better, show me in love, meekness, and tenderness,
as I would be willing to make anything known to you, for your good,
which the Lord has shown me.
But this I am fully assured of, that God is higher than man,
and that his will and laws are to be set up and obeyed in the first place,
and man`'s only in the second, and in their due subordination to the will and laws of God.

Now friend, apply yourself to do that which is right and noble,
and that which is truly justifiable in God`'s sight,
that you may give a comfortable account to him when he shall call you to it.
That which you have done to me has not made me your enemy,
but rather in the midst of it I desire your welfare,
and that you may so carry yourself in your position and your actions in such
a way that you may neither provoke God against you in this world,
nor in the world to come.

Have you not yet afflicted me enough without cause?
Would you have me bow to you even when the Lord has not given me liberty to do so?
If I should give you outward titles and honors, might I not do you hurt?
Oh come down, be low in your spirit before the Lord!
Honor him in your heart and ways,
and wait for the true nobility and honor that is from him.
You have but a short time to be in the world, and then eternity begins.
What you have sown here, you must then reap.
Oh that you might sow, not to your own will and wisdom, but to God`'s Spirit,
and know his guidance who alone is able to lead man aright.
Indeed, you should be subject in your own heart
to that seed which you are offended at in others,
even that which testifies for God, and against the thoughts, ways,
and works of corrupt man.
Oh that you might feel the seed of life from God,
and know good fruit brought forth from it!
And that the evil nature, with the evil works thereof, might be cut down in you,
so that your soul may escape the wrath and misery which
attend the works and workers of iniquity.

I have sent you the enclosed booklet in love.
Read it in fear and humility, lifting up your heart to the Lord, who gives understanding,
that it may be a blessing to you.
For it was written in true love, and is of a healing and guiding nature.
I have formerly written to you,
but my way has been so barred up that I have not found access easy,
and how or whether this will come to your hand, I know not.
But this I truly say to you--I have felt the Lamb`'s nature under my sufferings from you,
for which I have given you no provocation,
neither for the beginning nor continuance of them.
And if you can bring this to the trial of the witness of God in your heart,
then that will deal truly with you, blaming what God blames,
and justifying what he justifies.
And though the Lord beholds, and will plead the cause of his innocent ones,
yet I do not desire that you should suffer, either from God or man, on my account.
But I desire that you might be guided to, and preserved in,
that which will be sweet rest, peace, and safety, to all that are sheltered by it.

This is the sum of what I have at present to say,
who have written this not for any end except (in the stirrings of true love towards
you) that you might experience the power of God forming in your heart aright,
and bringing forth the fruits of righteousness in you.
My desire is that you be made by him of the seed of the blessed,
and inherit the blessing, and find the earthly nature consumed,
and brought to nothing in you.
For to this nature belongs the curse, and it must feel the curse,
as God brings forth his righteous judgments in the
hearts and upon the heads of the transgressors.
And, knowing there to be a certain day of God`'s calling transgressors to account,
I warn you in tenderness to consider your ways, and make your peace with him,
so that you may not be irrecoverably and eternally miserable,
but rather may be transformed by his life and nature.

And friend, know this for certain:
it is not a religion of man`'s making or choosing (neither the Pope`'s,
nor any other man`'s), which is acceptable to God, but only that which is of him.
Now what will become of that man whose very religion and worship are loathsome to God?
Where will he stand, or what account will he be able to give when he appears before him?

You have not often met with such a plain dealing as this.
These things very nearly concern you.
Oh wait upon God for his true light, that you may not be deceived about them,
for your loss thereby will be so great and irreparable.

I am your friend in these things,
and have written as a true lover and desirer of the welfare of your soul.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From Aylesbury Jail, 24th of Sixth Month, 1666

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

The vessel, or created nature, poisoned by sin and death,
can be redeemed by nothing except the life and power of God revealed in the vessel.
This life, this peace, this power, this righteousness, this salvation,
is the Lord Jesus Christ.
And he that experiences anything of this, experiences something of Christ;
and being joined to, and partaking of this, he partakes of something of his redemption.
For it is not by an outward knowledge,
but by an inward virtue and spiritual life received from Christ and held in Christ,
that those who are saved, are saved.
This is the thing of value with me, for which I have been made willing to part with all,
and into this purchased possession am I daily traveling.
And in my travels, the Father of life and tender mercy is pleased to help me.

Now, to have you gathered into this light, this life, this power,
which is of Christ, and in which he is and appears, this is the desire of my soul.
And if he please,
I am willing to be instrumental in his hand towards the bringing forth of this in you.
It is not my desire to bring forth new notions in you,
but rather that you might wait on the Lord for him to bring up his living,
powerful truth in you, wherein the knowledge of the new and living way is alone revealed.

I am a worm, I am poor, I am nothing, less than nothing as in myself.
I am weaker than I can express, or than you can imagine.
Yet, in the midst of all this, the life, power, righteousness,
and presence of Christ is my refreshment, peace, joy and crown.
And that to which I invite you is substance, everlasting substance,
which you will know and acknowledge in spirit to be so when
that which can see in truth is created and raised up in you.
Oh wait on the Lord, fear before him,
pray for his fear in the upright breathings (which are not of your own forming,
but of his pure begetting).
Pray that you may be led by him out of that wisdom which entangles,
and into that innocency, simplicity,
and precious childlikeness in which the Father appears to the soul,
to break the bonds and snares of iniquity.

Your truly loving friend, desiring the right guidance and happiness of your soul,
by the Lord Jesus Christ, who alone is the skillful Shepherd and Guide,
even as of my own soul.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 20th of Tenth Month, 1666

[.letter-heading]
To the Friends in Truth In and About the Two Chalfonts

[.salutation]
Dear Friends,

As a father watches over his children,
so do I desire to feel the Lord watching over my soul continually.
And in his love, care, wise and tender counsel, is my safety, life, and peace.
And I have never yet repented of either waiting for him or hearkening to him.
But if I have hearkened at any time to anything else, and mistook his voice,
and entertained the enemy`'s deceitful appearance
instead of his pure truth (which it is very easy to do),
that grievous mistake has proved a matter of loss and sorrow to my soul.

Now my friends,
my heart`'s desire is that you might know and hear the voice of the Preserver.
So shall you be preserved, and kept from the voice of the stranger,
which draws aside from the pure seed of life.
For there is something near you that watches to betray you.
Oh may the God of my life, joy, peace, and hope, watch over your souls,
and deliver you from the advantages which, at any time, the enemy has against you.
The seed which God has sown in you is pure and precious.
Oh that it may be found living in you, and you abiding in it!
And may no other seed, at any time, usurp authority over it;
but may you know the authority and pure truth which is of God, and stand therein,
in the pure dominion over all that is against him.
For in the seed of life (which you have known and received in measure) is dominion,
and when you are preserved therein, there is dominion over the impure and deceitful one.

Oh my dear friends,
my desire is that that part in you may be kept down which runs forward to judge,
to approve or disapprove, and that the weighty judgment of the seed be waited for.
Do not judge, oh do not judge,
before the light of the day shine in you and give forth the judgment!
Rather stand and walk in fear and humility, in tenderness of spirit and silence of flesh,
that the Lord not give you up to a wrong sense and judgment, to the hurt of your souls.
And mind your own states, and the experience of life in your own vessels,
which will keep you pure, precious, and chaste in the eye of the Lord.
And oh do not meddle with talking about others, which eats out the inward life,
and may exalt your spirits out of your place, and above your proper growth.
Be as the weaned child, simple, naked, meek, humble, tender,
easily led by and subjected to the Father.
In this way you will grow in that which is of God,
and be preserved out of that which hunts after the pure life to betray and destroy it.
I have an interest in you; my cries are to the Lord for you,
and I exceedingly thirst after your preservation and growth in that which is pure.

The Lord God of my mercies, hope, and life, watch over you for good,
and keep your hearts in the pure and single watch,
so that the enemy (by any subtle device of his) cannot break in upon you.
And may you not, by any temptation, be allured or drawn from the Lord,
but rather know the pure, eternal, everlasting habitation,
and may dwell and abide therein, to the joy of your own souls,
and the rejoicings of the hearts of all that have
travailed for you in the Spirit of the Lord.

From your brother and companion in the faith, patience,
and afflictions of the seed,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 25th of Eleventh Month, 1666

[.letter-heading]
To the Faithful Friends of Truth In and About the Two Chalfonts

[.salutation]
Dear Friends,

Have you in any measure drunk in the sense of what the Lord has done for you?
Have you felt meltings of spirit, and bowings before him, with praises to his name?
Indeed, my request is to the Lord for you,
that he would be pleased to keep you truly sensible of what he already is to you,
and of what he has already done for you.
And I also pray that he would visit you yet further, increase life in you,
cause faith to abound, granting you to dwell in his power, and always abide in his seed.
Oh may you experience that seed to be your hope, peace, joy, life,
and strength continually,
so that you may more and more give thanks unto
him as you feel his pure life arising in you,
and death and the grave thereby swallowed up.

Ah my friends,
can we ever forget the lost and miserable state wherein the
mercy of the Lord and his power from on high visited us?
Oh, the blackness of that day, the misery, the deep distress of that day,
which some of your souls felt!
Did you not know what it was to be without God,
and to lie open to the furious assaults of the enemy?
Was there not a day when you felt your weakness,
and you knew not where to retreat in order to keep out of hurt, temptation,
vain thoughts, and imagination?
Did you not mourn?
Did you not cry out and pine away in your iniquities day and night?
Are there not some among you who have known this state,
and felt something of that which I now relate?
I am sure that there are some upon the earth who can witness it to the fullest,
yet whose mouths and hearts are now filled with a sense of the Lord`'s goodness,
and of his great salvation, and with deep and high praises to his name.

But, my dear friends, are there any of you (I know to whom I speak,
even to the sensible, to the diligent, to the faithful among you),
who cannot witness (in the presence of God)
concerning the arm and power of his salvation,
which you have often felt?
Indeed, do you not daily feel the Lord ministering his salvation to you?
Are not your enemies daily overcome by the faith which he has given you in his power?
May I not say to you, "`Where now is the strength of the tempter?`"
Have you not felt the seed of the woman bruise the head of the serpent?
Can you not say (though in the fear of the Lord), "`Where are those temptations,
those lusts, vain thoughts, and imaginations,
which once I was overcome by and overrun with?`"
Surely I may speak in this way, for I know assuredly that the power of the Lord God,
as it is lifted up in any of you, scatters these things and gives dominion over them.
For the life and its power are given as a bulwark and a
weapon of war against iniquity and its power.
And where this life is received, and its power is known, it opposes, wars, and strives,
until it overcomes.

And, this is what gives the victory and the overcoming: faith in the seed.
The seed is felt, the soul is joined to it,
and faith in it and from it is given to the soul.
Then faith becomes the leader, the mighty undertaker for the soul,
and overcomes its snares and its enemies for it.
And when it has overcome them, they are overcome indeed.
Then the soul lies down in peace, dwells in peace,
feeds on the living nourishment in the green pastures of life.
Then Jerusalem, the building or life in the heart,
becomes a quiet habitation where God and the soul dwell sweetly together,
and there is nothing that has power in it to disturb, annoy, or make afraid.
Why so?
Because the Lord God of power is present there; he stretches out his wings there,
and is a pillar of cloud by day and a pillar of fire by night!
He has raised up his glorious life in that heart,
and has also spread a defense over his glory,
with which the soul is so encompassed and defended that
it feels the walls of this city to be salvation,
and its gates praise.

Oh my soul, travel on!
Oh dear friends, you also travel on, into the fullness of the glory of this state!
There is no other thing to be desired and waited for.
This is your portion, both here in this world, and forever.
Therefore, wait in the seed of this life; wait to know a further gathering into it,
and a growing up in it.
Give yourselves up to it, that it may overspread and cover you.
And may the Lord God of life daily reveal it,
and manifest it more and more in you and to you!

Therefore,
come to feel (in spirit) the mark of the high calling of God in Christ Jesus.
Be daily looking up to him who keeps you alive and fresh,
so that none of you grow slothful, drowsy, negligent,
or unfaithful in relation to the great talent which God has put into your hands.
Let not a veil come over your hearts again, nor let the air thicken,
and the earthly nature cover the seed, so that he who has power in that earth,
and over that air, captivate, oppress, entangle, and lead you back from God again.
Oh cry to the Lord to keep the eye open, and the heart single,
and the soul in the true sense and experience, so that the heavenly voice,
which drew you out of the earth, may be daily heard,
instructing and gathering you more and more up into him who is your life.
Therefore, you that fear the Lord and love his name,
and have tasted of his goodness and powerful salvation, oh hate evil!
All that his light has made manifest and drawn you from,
oh take heed never to dabble with it again!
Oh never hearken to the tempter,
but pray to the Father that you may discern his enticements.
Never consult or reason with your enemy, but in everything wait to experience the motion,
guidance, quickening, and sweet, pure, heavenly leading of the Spirit of your Father!

Therefore, this little thing, this light of God in you,
to which you were at first directed and turned,
which discovers all the darkness of the enemy, and all his deceits and devices,
and keeps the minds of those that are staid by it--in this light wait.
To this light let your minds be turned, and in it continue to abide.
And the power and glory of eternal life will daily, more and more, appear in you.
Yes, it will flow and break in upon you, to the filling of your vessels with its virtue,
and the causing of your hearts to abound with joy before the Lord,
and with thanksgivings to him.

May the God of tender mercies and everlasting compassions
cause his love to be daily yearning towards you,
that you may be nursed up with the living food,
and that that which would overturn and destroy his work may be opposed.
May you feel the work daily go on and be mightily preserved by him,
even till it is finished, and the top stone is laid.
Then your souls, in the true and full sense of life, will cry out, "`Grace, grace,
to him that laid the foundation, raised up, defended, and carried on the building,
and now, at length, has perfected it.`"
And in this way, whatsoever you have now witnessed in measure,
you shall then witness in fullness.
And you will see that all the promises of God are of a precious nature,
and they are "`yes and amen`" from God to the seed.

May the life, presence, and power of the Lord be with you in this seed,
in your breathing after it, in your joining to it,
in your abiding and waiting upon him in it.
May the Lord God give you to long after it, to join to it,
to abide always and wait upon him in it, and never to hearken to, and go out after,
a contrary spirit and wisdom.
May he keep you in the simplicity, lowliness, humility,
and tender spirit which is in Christ Jesus, to the praise of his own name,
and the preservation and joy of your hearts before him forever, amen!

Written in the tender affection and motion of the pure life,
from the place of my confinement in Aylesbury.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
1st of Third Month, 1667

[.letter-heading]
To My Dear Children J. J. and M. P.

[.salutation]
My Dear Children,

Two things I especially desire in reference to your learning--one is,
that you may learn to know and hearken to the voice of God`'s witness in you.
There is something in you that will teach you how to do well, and how to avoid evil,
if your minds are turned to it.
And the same thing will witness to you when you do well,
and will witness against you when you do evil.
Now to learn to know this, to hear this, to fear this, to obey this,
that is the chief object of learning that I desire to find you in.
And when your master, or anyone of the family, turns you to this witness,
or reminds you of this witness,
or reproves you for not hearkening to or obeying this witness, oh love them,
and bless God for them in that respect!
And remember this, that he that hearkens to reproof is wise,
but he that hates or slights reproof is brutish.
That is the dark spirit, which desires to please itself in its dark ways,
and therefore loves not the light which makes his ways manifest and reproves them.
It is the brutish spirit which hates the reproof of the light,
and would continue its vain foolish ways and delights, which the light testifies against.
Therefore, mind the witness of God in your hearts which discovers these things to you,
and leads you out of them as you hearken to it, and come to know, fear,
and love the Lord God by his instruction and testimony.

The way of youth is vain and foolish, and it defiles the mind.
Oh my children, wait for the cleansing.
Watch for that which cleanses the foolish way of children,
which is the light that uncovers and witnesses against your foolishness and vain tempers,
and the temptations of your minds, and leads out of them.
Learn to bear the yoke in your tender years.
There is a vain mind in you,
and there is something which desires to feed and please that vain mind.
But there is something near you and appointed by God to yoke it down.
Oh give no place to vanity, for it will be an occasion of woe and misery to you hereafter.
But the yoke which keeps down the vain mind, oh take that yoke upon you.
For then you shall become not only my children, but the disciples of Christ,
and children of the Most High.
This is the first thing which I mainly and chiefly
desire you should apply yourselves to learn.

The next thing (which will also flow from the first),
is that you learn how to behave yourselves as good children,
both in the family and to persons abroad, in a meek, modest, humble, gentle, loving,
tender, respectful way.
Avoid all rude, rough, bold, unbecoming carriage towards all.
Honor your mother and me as God teaches and requires,
and dearly cleave to one another in the natural relation, which is of God,
wherein you are loved,
having a great proportion of natural affection and kindness one to another.

With the servants, carry yourselves very lovingly, sweetly, meekly, and gently,
so that none may have any cause of complaint against you,
but that all may see your lowliness and be drawn to love you.
And to strangers, carry yourselves warily, respectfully, in a sober, submissive,
humble manner of demeanor.
Do not be disputing and talking much, which is not fitting for your age and place.
Rather, watch what you may observe of good in others,
and what you may learn of those that are good.
And watch also to see how you may avoid any such evil as you observe in any that are evil.
In this way your time will be spent in profit,
and you will feel the blessing of God and of your parents,
and you will be kept out of those evils which
your age and natural tempers are subject to,
and which other children (who are not careful nor watchful) are commonly entangled in.
Mind these things, my children, as you will give an account to God,
who through me thus instructs you--who am your imprisoned father.
I am much grieved when I hear of any ill concerning you.
For this is more a matter of trouble and sorrow to me than my imprisonment,
or anything else I suffer, or can suffer from man.

And remember this one thing, which as a father I admonish you of,
and charge you to take notice of and observe,
which is this--that you do not fly out upon one another, or complain of one another,
because of the evils you observe in one another.
But rather, first take notice of the evil in yourselves.
If by the true light you find your own hearts cleansed from it,
bless God who has done it, and keep to his light and witness in you whereby he did it,
and watch that you are not overtaken by it in the future.
But if you be guilty of the same evil, or have lately done the same thing,
or are liable suddenly to do it--then oh, forbear accusing or blaming another!
In the fear of God wait on him, and pray unto him that you may be delivered from it,
and kept out of it.
And then, in tender pity, love, and meekness,
admonish your brother or sister of his or her evil,
and watch to be helpful to preserve or restore them.
And pray to God to direct you how to be helpful to them.
But it is the bad spirit and nature which is ready to accuse others.
And even when it has never been so bad and guilty, yet it will be excusing itself,
and laying the fault upon others, or remembering some other fault of another,
when it should be sensible of and ashamed of its own.

Dear children, if you bend your minds to learn these things,
the Lord will help you therein, and he will become your teacher, guide and preserver,
and pour down his blessings upon you.
And in this you will be a comfort to me and your mother, and an honor to his Truth.
And may he also give me wise fatherly instructions to teach you further.
But if you be careless, foolish, vain, following your own minds,
and what rises up there from the wicked one,
you will grieve my heart and provoke God against you, to bring evil upon you,
both in this world and forever.

Therefore, children, mind that which is near you--the light of God,
which discovers the evil and the good.
His witness (which observes all you do) is near you.
Yes, he himself is in that light, and with that witness.
Therefore, know that you are in the presence at all times of a holy and just God,
who hates that which is vain and evil, and loves that which is good and right before him.
And he has appointed a day and set a time wherein he will either reward you with peace,
joy, and eternal happiness if you have been good and done that which is good;
or with misery, destruction, and insufferable pain both of soul and body,
if you have been evil and done that which is evil.
God knows well how many instructions you have heard from friends in Truth,
and from your parents,
and how many meetings you have been at wherein
you have been taught and warned of these things.
So if you turn your back upon his light, and will not hear its reproofs,
but will rather be vain, idle, foolish, rash, quarreling,
and doing that which is wrong and then covering it with lies, (and so be as bad,
if not worse, than children who were never thus taught and instructed)--then,
in his just judgment and sore displeasure,
God may separate you from his light and give you up to the black, dark spirit,
(from whom all this wickedness is) to sow in sin here,
and to suffer the flames of eternal fire hereafter.
For this is the reward of the dark spirit,
and also the reward of all who are persuaded by him to be of his nature,
and who hearken to him, and let him work through them.

Oh my children, mind the Truth of God in you!
He will let you see and understand the truth of what I now write,
and in what fatherly love and tender care of you I write these things.
Oh, be warned of the great danger of neglecting the time of
your visitation by God`'s light and witness in you!
And do not go on in the evil ways of the dark, crooked spirit,
who will be tempting you to evil and hindering
you from God as long as you hearken to him.
Therefore,
be not fools to be led by him to destruction in
the evil way and evil works which lead thereto;
but be wise to hearken to the light, and follow it out of that which is evil,
into everything that is good, to the salvation of your souls.

I desire that Friends in the family^
footnote:[The remainder of this letter is not directed to his children,
but to other Friends who lived in his house, and to Gulielma, his step-daughter,
and afterwards the wife of William Penn.]
watch over them in these respects; and when they find just occasion,
to put them in mind of any of these things, in the fear and wisdom of God,
with tenderness and gentleness.
But take heed of upbraiding or aggravating them, lest they be thereby hardened,
and evil is raised and strengthened in them.
And, my dear G. +++[+++doubtless his step-daughter, Gulielma,
afterwards the wife of William Penn]
and Friends, watch over your hearts and ways, that you may be as examples to them,
so that they may not only read these things from my writing,
but also in your carriage towards them and towards one another.
So the Lord bless your watchfulness, care, and endeavors therein,
that I may hear good concerning them,
and be comforted in the mercy and kindness of the Lord towards them.

Your father, who desires your good, and that it may go well with you,
both here and hereafter.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
10th of Third month, 1667

[.letter-heading]
To the Friends at Chalfont in Buckinghamshire

[.salutation]
Oh Friends!

Feed on the tree of life!
Feed on the measure of life,
and its pure power which God has revealed and manifests in you.
Do you know your food?
Do you remember the taste and relish of it?
Then keep to it, and do not meddle with that which seems very desirable to the other eye,
and very able to make wise.
Oh abide in the simplicity that is in Christ, in the naked truth that you have felt there!
And there you will be able to know and distinguish your food,
which has several names in Scripture, but is all one and the same thing: it is the bread,
the milk, the water, the wine, the flesh and blood of him that came down from heaven, John 6:51.
It is the same,
only it is given forth weaker and stronger according to
the capacity of him that receives it,
and so has different names given to it accordingly.

Oh keep out of that wisdom which knows not the substance,
for it is this wisdom which also stumbles over names.
But keep to the seed of life, keep to the seed of the kingdom,
feed on that which was from the beginning.
Is not this food indeed, and drink indeed, flesh indeed, and blood indeed?
The Lord has brought you to that ministration of life and
power wherein things are known above and beyond mere names,
wherein the life is revealed and felt beyond what words can utter.
Oh dwell in your habitations and feed on the food which God brings into your habitations,
which is pure, living, spiritual,
and will cause your souls and spirits more and more to live in and to God!
Be not shaken or disquieted by the wisdom of the flesh,
but feel that which settles and establishes in the pure power.

And may the Lord God preserve you, and give you power to watch against,
and to experience victory and dominion over all that is contrary to him in any of you.

This sprang unto you in the good will of your Father,
from the life and love of your brother in the Truth,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 8th of Fifth Month, 1667

[.letter-heading]
To George Fox

[.salutation]
Dear G. F.,

I feel the tender mercy of the Lord, and some portion of that brokenness, fear,
and humility which I have long waited for, and breathed after.
I feel unity with, and strength from, the body.
Oh blessed be the Lord, who has fitted and restored me,
and brought up my life from the grave.
I feel a high esteem and dear love to you, whom the Lord has chosen, anointed,
and honored, and for your brethren and fellow-laborers in the work of the Lord.

And, dear George Fox, I beg your love, I entreat your prayers,
in faith and assurance that the Lord hears you, that I may be yet more broken,
that I may be yet more filled with the fear of the Lord,
that I may be yet poorer and humbler before the Lord,
and may walk in perfect humility and tenderness of spirit before him, all of my days.

Dear George Fox, you may feel my desires and needs more fully than my own heart.
Be helpful to me in tender love, that I may feel settlement and stability in the truth;
and know a perfect separation from, and dominion in the Lord over,
all that is contrary to him.

I entreat your prayers for my family,
that the name of the Lord may be exalted and his truth flourish therein.
Dear G. F., indeed my soul longs for the pure, full,
and undisturbed reign of the Life in me.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 15th of Fifth Month, 1667

[.letter-heading]
To Friends of Both the Chalfonts

[.salutation]
Dear Friends,

Oh the treasures of wisdom and knowledge, the riches of love, mercy, life, power,
and grace of our God, which are treasured up for the soul in the Lord Jesus!
These are freely dispensed and given out by him to them that come unto him,
wait upon him, abide in him, and give up faithfully to the law of his life,
to those whose delight it is to be found in subjection
and obedience to the light and requirings of his Spirit.

Feel, my friends, oh feel your portion,
and abide in that wherein the inheritance is known, received, and enjoyed!
For there is no knowing Christ truly and sensibly
except by a measure of his life felt in the heart,
whereby the heart is made capable of understanding the things of the kingdom.
The soul without him is dead,
but by the quickenings of his Spirit it comes to a
sense and capacity of understanding the things of God.
Life gives it a feeling, a sight, a tasting, a hearing, a smelling,
of the heavenly things,
by which senses it is able to discern and distinguish them from the earthly things.
And from this measure of life, the capacity increases, the senses grow stronger;
they see more, feel more, taste more, hear more, smell more.
Now when the senses are grown up to strength, then comes settlement and stability,
assurance and satisfaction.
Then the soul is assured and established concerning the things of God in the faith,
and the faith gives assurance to the understanding.
In this way, the doubts and disputes in the mind fly away,
and the soul lives in the certain demonstration and fresh sense and power of life.
It daily experiences (in the heart and soul) the eternal Word and
power of life to be what is testified of it in the Scripture.
It knows the flesh and blood of the Lamb, the water and wine of the kingdom,
the bread which comes down from heaven into the vessel, from all other things,
by its daily feeding upon it in spirit.
What heart can conceive the righteousness, the holiness, the peace, the joy,
the strength of life that is felt here!

Friends, there are no clogs in the Fountain.
God is fullness, and it is his delight to empty himself into the hearts of his children,
and he does this according as he makes way in them,
and as they are able to drink in his living virtue.
Therefore, where the soul is enlarged, where the senses are grown strong,
where the mouth is opened wide (and the Lord God standing ready to pour out his riches),
what should hinder the soul from being filled?
And being filled, how natural is it to run over,
and break forth inwardly in admiration and deep
spiritual sense concerning what it cannot utter!
It cries out saying, "`Oh the fullness, oh the depth, height, breadth,
and length of the love!
Oh the compassion, the mercy, the tenderness, of our Father!`"
How has he pitied, how has he pardoned beyond what the heart could believe!
How has he helped in the hour of distress!
How has he conquered and scattered the enemies which, in unbelief,
the heart was often ready to say were unconquerable,
thinking it should one day die by the hand of one of its mighty enemies, lusts,
and corruptions.
How has he put an end to doubts, fears, disputes, and troubles,
with which the mind was overwhelmed and tossed!
And now he extends peace like a river; now he brings the soul out of the pit,
into the green pastures; now it feeds on the freshness of life, and is satisfied,
and drinks of the river of God`'s pleasure and is delighted!
And it sings praise to the Lamb, and him that sits on the throne, saying, "`Glory, glory!
Life, power, dominion, and majesty, over all the powers of darkness,
over all the enemies of the soul, be to your name forevermore!`"

Now, my dear friends, you know something of this, and you know the way to it.
Oh be faithful, be faithful!
Travel on, travel on!
Let nothing stop you, but wait for, and daily follow,
the sensible leadings of that measure of life which God has placed in you.
For the measure is one with the fullness,
and the fullness runs daily into it and fills it, that it may run into you and fill you.
Oh that you were enlarged in your own hearts even as
the heart of the Lord is enlarged towards you!
It is the day of love, of mercy, of kindness, of the working of his tender hand!
It is the day of the wisdom, power, and goodness of our God,
manifested richly in Jesus Christ!
Oh, why should there be any stop of the flow in any of us?
May the Lord remove that which stands in the way.
And in faithful waiting upon the power which is arisen, the Lord will remove, yes,
the Lord does remove;
and growth in his truth and power is experienced by those that wait upon him.

Friends, be not discouraged because of your souls`' enemies.
Are you troubled with thoughts, fears, doubts, imaginations, reasonings,
etc.? Do you still see much in you that is unsubdued to the power of life?
Oh do not fear it!
Do not look at it, so as to be discouraged by it; rather look to him!
Look up to the power which is over all their strength.
Wait for the descending of the power upon you.
Abide in faith of the Lord`'s help, waiting in patience till the Lord arise,
and you will see if his arm does not scatter what yours could not.
So be still before him, and in stillness believe in his name.
Enter not into the stirrings of the enemy, though they fill the soul;
for there is something into which they cannot enter, and from which patience, faith,
and hope will spring up in you, even in the midst of all that they can do.

Sink into this, therefore,
and lie hidden in the evil hour till the temptations pass away,
and the tempter`'s strength be broken,
and the arm of the Lord which broke him be revealed.
Then you shall see that the enemy raised but a sea of
trouble to your souls only to sink himself in it.
And the Lord will throw the horse and his rider,
which trampled upon the Just One within you, into that sea.
And you shall stand upon the bank and sing the song of Moses
to him that drowned him and delivered you from him!
And in due season, you will sing the song of the Lamb also,
when his life springs up in you in his pure dominion, triumphing over death,
and all that is contrary to God, both within and without.

Now, friends, in an attentive waiting and giving up to the Lord,
and in the daily exercise of the cross putting
to death in you that which is not of the life,
this work will daily go on.
And you will feel from the Lord that which will help, relieve, refresh, and satisfy you,
something which neither tongue nor words can utter.
And may the Lord God breathe upon you,
preserve and fill you with his life and Holy Spirit,
to the growth and rejoicing of your souls in him, who is our blessed Father,
and merciful Redeemer.

And then, as to what may befall us outwardly in this confused state of things,
shall we not trust our tender Father and rest satisfied in his will?
Are we not engraved in his heart, and on the palms of his hands?
Can he forget us in anything he does?
Shall anything hurt us?
Shall anything come between us and our life,
between us and his love and tender care over us?
Though the fig-tree should not blossom, neither there be any fruit on the vine;
though the labor of the olive should fail, and the fields yield no food;
though the flock be cut off from the fold, and there be no herd in the stalls;
yet should we not rejoice in the Lord, and rejoice in the God of our salvation?
And even though the earth be removed,
and the mountains be carried into the midst of the sea;
even though the waters thereof roar and be troubled,
and the mountains shake with the swelling thereof, is there not a river,
the streams whereof make glad the city of God?
Is not the joy, the virtue, the life,
the sweet refreshment of this river felt in the
holy place of the tabernacle of the Most High?
And he that provides inward food for the inward man, inward clothing, inward refreshment,
shall he not also provide what is sufficient for the outward?
Yes, shall he not bear up our mind, and be our strength, portion, armor, rock, peace,
joy, and full satisfaction in every condition?
For it is not the condition that makes one miserable,
but the lack of him in the condition.
He is the substance of all, the virtue of all, the life of all, the power of all.
He nourishes, he preserves, he upholds,
(making use of the creation or without the creation) as it pleases him.
And he that has him, he that is with him, he that is in him, cannot be in want.
Now consider, does the spirit of this world have contentment in all that it enjoys?
No, it is restless, it is unsatisfied.
But can tribulation, distress, persecution, famine, nakedness, peril,
or sword come between the love of the Father to the child, or the child`'s rest,
contentment, and delight in his love?
And does not the love, the peace, the joy, the true rest,
swallow up all the bitterness and sorrow of the outward condition?

The seed, the true nature and birth, has not only the promise of eternal life,
but also whatever is necessary for the vessel (wherein it dwells) in this life too.
So dwell in that to which is the promise, and live upon the promise.
Yes, live upon that which cannot miss of the promise,
but feels the presence and power of the Father in all and over all.
The just One lives by his faith, and he that is in union with the just One,
lives by the faith of the just One, and takes no more care than the lilies,
but leaves the care of all to him to whom it properly belongs.
He is the one that nourishes, clothes, preserves,
and causes the lilies of the field to grow and flourish in beauty and glory.
And will he not much more clothe, nourish, and take care of his own lilies,
the heavenly lilies, the lilies of his own garden?

Let us then not look out like the world, or judge,
or fear according to the appearance of things, after the manner of the world.
Rather, let us sanctify the Lord of hosts in our hearts,
and let him be our fear and dread.
And he shall be a hiding place unto us in the storms
and tempests which are coming thick upon the earth.

Thus, my dear friends, let us retire, and dwell in the peace which God breathes,
and lie down in the Lamb`'s patience and stillness, night and day,
which nothing can wear out or disturb.
And may the Lord God, in his tender mercy, and because of his deep and free love unto us,
guide our hearts daily more and more in the travel, and into the possession.
For every soul may inherit and possess (notwithstanding
all its enemies) whatever it has traveled into,
and it may also daily, further and further, travel into what yet lies ahead.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 2nd & 3rd of Sixth Month, 1667

[.letter-heading]
To an Unknown Recipient

[.salutation]
Dear Friend,

You have had the path of salvation faithfully testified of to you,
and have come to a sense of the substance,
even to the experience of that whereby the Father begets life,
and manifests his love and peace in and to the soul.
Now, what remains?
Look up to the Lord to guide your feet in this path,
and to preserve you from that which darkens and leads out of the way.
In this way you may continue on your journey safely,
and come to the inheritance and enjoyment of that which your soul longs after.

There is life, there is peace, there is joy, there is righteousness,
there is health, there is salvation, there is a power of redemption, in the seed.
And yet your soul lacks, and does not enjoy these things.
Well, how may you come to enjoy them?
There is no other way but by union with the seed, by knowing the seed,
hearing the voice of the seed, learning of and becoming subject to the seed.
"`Learn of me, take my yoke upon you,`" says Christ,
"`and you shall find rest to your souls.`"
Do you desire to experience your soul`'s rest in Christ?
You must know the seed`'s voice, hear it, learn daily of him, become his disciple.
You must take up, from his nature, what is contrary to your nature.
And then, as your nature is worn out, and his nature comes up in you,
you will find all easy.
You will find all that is of life easy, and transgression will be hard,
unbelief will be hard.
Indeed, when the nature of the seed is grown up in you,
you will find it very hard and unnatural either
to distrust the Lord or hearken to his enemy.
And then that dwelling place (into which Satan brings dark thoughts, suggestions,
and reasonings) will be changed for the dwelling place which is from above,
wherein there is light, life, peace, satisfaction, health, salvation,
and rejoicing of soul, from and before the Lord.

Now, do not say, "`Who shall do thus for me?`"
But know that the arm of the Lord is mighty and brings mighty things to pass,
and this arm has been revealed in you, and is at work for you.
Oh that you could trust it! (Why can you not?
Has it not sown a seed of faith in you?) Oh that you could
come into and abide in the path wherein its mighty,
powerful operations are felt and made manifest!
And, oh that you may find the ability to watch against that
which wounds and distresses your soul!
For the enemy`'s dark suggestions work according to their nature,
and if you let them lie upon you, how can they not darken, afflict, and perplex you?

Therefore, in the evil hour, fly from all things that thus arise in you.
Lie still and feel your anchor, till his light which "`makes manifest`" arises in you,
and clears up all things to you.
And think not the time of darkness long,
but keep watch that your heart may be clear of your own thoughts and
beliefs until he bring in something which you may safely receive.
Therefore,
say to your thoughts and to your beliefs (according to the suggestion of the dark power,
in the time of your darkness), "`Go from me!`"
And if that will not do, look to the Lord to speak to them and to keep them out,
if they be not already entered.
And if he does not do so immediately, or for a long time,
yet do not murmur or think much, but wait until he does.
Yes, though these thoughts violently thrust themselves upon you,
and seem to have entered your mind, yet let them be as strangers to you.
Receive them not, believe them not, know them not, acknowledge them not!
And your heart will, notwithstanding, remain chaste in the eye of the Lord,
though they may seem to you to have defiled you.

Look up to the Father, that you may learn these things from him.
And as you become faithful to him therein, you will find your darkness abate,
and its strength will be more and more broken in you.
And you will not only feel and taste a little of the Lord now and then,
but also come to possess and inherit, and rejoice before the Lord in your portion.

I am your friend in the truth which changes not, but is pure,
and preserves us pure forever.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
From Aylesbury Jail, 28th of Seventh Month, 1667

[.letter-heading]
To His Brother

[.salutation]
Dear Brother,

This morning, as I was going out to walk,
something sprang up in my heart freshly and livingly to you, whereupon I consulted not,
but immediately turned back to write you.
Now, if the Lord makes it useful to you, you will have cause to bless his name.
And I too shall bless his name,
for I heartily desire the life and welfare of your soul in the living God,
and that you avoid all snares that the enemy lays to
betray and keep your soul in death and bondage.
The thing that rose up in me was this:

God gave some apostles, some prophets, etc., for the work of the ministry,
for the building up of the body, for the perfecting of the saints.
This was God`'s gift (in mercy and love) to them in that day,
and they were to walk worthily of this gift and be thankful for it.

Now, in these days, the Lord has given gifts to some for this same work,
which the body has need of, and the body is to wait on the Lord in the use of his gift,
in fear and humility.
And mark, brother, that in every age God`'s ministers have been despised.
Moses and all the prophets were despised in their day.
"`What?`"
they said "`Has God spoken only by Moses?
Has he not spoken also by us?`"
The apostles were despised in their days by those that
kept not to the anointing which teaches all things.
"`He that despises you,`" said Christ, "`despises me.`"
He that despises them in their gathering, or in their building up,
despises him that sent them.
They were earthen vessels, in presence contemptible, and very liable to be despised.
It is still easy to despise God`'s messengers and servants,
but he that will truly and rightly esteem them, must lie low,
must dwell in the pure fear, and in the sense of life,
that he may be taught of God to do so.
It is an easy matter to have objections against them;
but to see through all prejudices and objections to the pure and precious life in them,
and to the gift and Spirit and power of the Lord--this requires a true eye,
and a heart opened by the Lord.

Ah brother!
This is a snare in which many have been caught in former ages, and in this age also.
For it is easy to fall into, but the preservation out of this snare is not easy,
but is only by the power and mercy of the Lord.
Dear brother, when I am in the pure sense before the Lord,
and my spirit is opened by him and you are presented before me,
I can beg most earnestly of the Lord that he open your eye,
and give you a true sight of your state.
I beseech that he might cause your spirit to bow before him,
and to know and honor what is of him,
and not (by any device of the enemy) be hindered from receiving what he,
in tender love and mercy, holds out to you.

And so, dear brother, mind this advice which just springs in my heart:
pick out some of the faithful ones of the Lord`'s servants, and open your heart to them!
Indeed, brother, I have had, for a long time, a deep sense of danger towards you.
May the Lord prevent it, that your soul may live to him, and not die from him!
There is a wisdom and a will near to you which will destroy you,
unless the Lord destroy it in you.

Oh that you might come to wait aright for the motion of his Spirit,
and learn to be kept by him in that which knows his drawing!
Then you will hunger and thirst after the righteousness of his kingdom,
and long after times of meeting and assembling with his people;
and you will find your sense of them living, and your life refreshed therein.
For God is with his people, and they meet not without him,
but his presence is in the midst of them,
causing his life to flow into every vessel that stands open to him,
and to grow more and more in dominion in them.
Oh brother, I am satisfied in my heart that not only my love,
but my life speaks to you now.
Oh that you could hear, and feel, and fear, and bow down before the Lord!
Then he would, in his due season, raise you up in his life and power among his people,
purifying you, and preserving you pure and alive to him forever.

The desire of my heart to the Lord for you is that he
would open and keep open the eye in you which sees,
and the ear which hears, and the heart which understands his truth,
and that he would prevent the enemy from raising up
another thing in you instead of the seed of life.

Great has been the subtlety, and deep has been the error from the truth.
Many who seem to be true Jews are not, but have erred from the Spirit, life, and power,
by which they were at first convinced and first led.
And in these,
the enemy has raised up a seat of prejudices and strongholds
against the ministry and power of the living God.
But those who are of the true seed bless the Lord,
beholding his true work even while others scorn
in their expectations for something else.

Oh brother,
there is a high-mindedness in some which takes upon
itself to judge beyond its growth and capacity!
But there is a fear in the hearts of others, lest anything in them should rise up,
or judge, or be anything beyond or beside the pure Truth.
This fear teaches the soul to honor and prefer those whom the Lord has preferred,
while the high-mindedness has only accusations and pleas against them.
One of these will experience preservation from God; the other is left by God to fall.

Dear brother, it is my desire that you may not perish,
but rather experience the carrying on of the work of salvation in you.
Oh that you would travel on in the pure, holy, living, powerful path,
and receive the crown of fidelity to the truth!
Ah brother, mourn to the Lord!
Fear before him.
Converse and consult with those that abide faithful,
and they may help you to see (through the guidance, presence,
and power of the Spirit of the Lord with them) what you are not able to see.
Remember this counsel; for you have need of the help which the Lord, in his tender mercy,
has provided.
And you cannot be safe without it.

I am your dear brother according to a natural unity,
but longing after a unity with you in the pure life.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury Jail, 7th of Eighth Month, 1667

[.letter-heading]
To an Unknown Recipient

[.salutation]
My Dear Friend,

This is the way of redemption:
to wait to experience the appearance of the light of the Spirit in the heart, and,
at its least or lowest appearance, to be turned from the darkness towards it.
Oh feel the redeeming arm in your own heart, and know the love which stretches it forth!
Take heed of being prejudiced against his inward visitations to you,
for there is something near you which would
darken you and keep the seed of life in bondage.
I know there is that in you which pants after God and is not satisfied,
something that thirsts after the living waters.
The Spirit of the Lord says, "`Come, come to the fountain of eternal life; drink,
and live.`"

Oh Lord my God,
unveil to the thirsty souls what it is that withholds them from the living waters,
so that they may not labor and spend their strength in vain,
in duties and ordinances invented by man.
For these may perhaps lull one asleep for the present,
but they can never quiet the cry of the living seed, nor ever satisfy the soul.

My friend, I know your snare.
There is a building in your earthly wisdom,
a knowledge which you hold in your comprehension,
which is not of the light from which the true knowledge springs,
and in which alone it is held.
You must come to know the tearing down of this building,
the confounding and scattering of this knowledge,
so that the true heir may spring up in you.
You must feel the babe raised, to whom God reveals the mysteries of his kingdom,
which he hides from the wise professors and teachers in this age,
as he has done in all ages.
You are very wise,
but you must sell all that and become a fool if you desire the
riches and everlasting treasures of the kingdom.

And, if you desire to draw near and find access to God in prayer,
you must wait to feel the true birth pray,
and take heed of putting up requests in your own wisdom, and according to your own will.
For such are the prayers of the false child, or the counterfeit birth, the wrong seed,
which the Father does not know or regard.
But this is our religion:
to experience that which God begets and keeps alive in our hearts,
and to be taught by him to know him, to worship,
and to live to him by the leadings and power of his Spirit.
And in this religion we have the comfort and the appearances of his Spirit,
which are beyond all the disputes and questions of man`'s wisdom.
Indeed, they are beyond the disputes of our own hearts also,
being demonstrated and made manifest to our spirits in a higher principle.

I found my heart in great love drawn to write these things to you;
and my soul offers breathings to the Lord my God that you may be
drawn into true unity and fellowship with the spring of eternal life,
and that you not be led astray from the precious enjoyment of God here,
or of the salvation of your soul forever.
The path of life is living,
and your feet must be guided into it and walk faithfully in it to the end,
if you desire to sit down in God`'s eternal rest and peace.

I have been long desolate, and a great mourner after my God,
and know how to pity and weep over wandering souls,
though I cannot but rejoice at this great day of
salvation and powerful visitation of God`'s Spirit,
wherein he has sought out and gathered many into the fold of his pure rest.
The Lord has become a living Shepherd to many, and daily ministers his life unto them.
And he is seeking out many more.
Happy are they who know and return at the sound
of the Shepherd`'s voice when he calls after them.

I remain your true, entire, faithful, loving friend,
in the love and goodwill of the Lord, wishing to your soul as to my own.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Dear Friend,

Let me speak a few words to you, not only from what I have felt in my heart,
but have also read in the Scriptures of truth.

After the apostasy, the gospel is to be preached in this way: "`Fear God,
and give glory to him; for the hour of his judgment is come;
and worship him that made heaven, and earth.`" Rev. 14:7.
If you know the Preacher that preached this,
if you have heard this preached in your own heart,
if you have met with the fear that the Spirit teaches and gives,
if you have known the hour of God`'s judgment and
had the axe laid to the root of the tree,
and if you have been taught by the Son to worship the Father in Spirit and truth,
then you have, without doubt, met with the everlasting gospel.
And if God requires of you,
and assists you by his Spirit and power to preach this to others,
then you are a preacher of the everlasting gospel,
and an able minister of the New Covenant, not of the letter, but of the Spirit.
But I beseech you,
beware of preaching your own conclusions and conceivings upon the letter,
as too many do in this day.
For this falls short of true preaching.
Oh let these things be weighty with you!
You must learn the right way to search and understand the Scriptures.
And you must know how the Father has revealed the Son in this day,
and how to come to him to receive life from him.
For many, through ignorance, have erred in this matter,
and have run ahead in their own wills, wisdom, and comprehension of things.

Friend,
the God who caused light to shine in this outward world has judged it
necessary to cause the light of his Spirit to shine inwardly in the heart.
Only this gives the knowledge of the Scriptures,
and the true sense and discerning of inward and spiritual things.
Yes, by this light the Son is known, and his cleansing blood is felt.
Without this light, the Scriptures do not make manifest spiritual things;
but in the light, the Scriptures are a clear and faithful record and testimony of them.

Oh take heed how you read and how you understand the Scriptures!
In what light and in what spirit are you reading?
For it is easy to err,
and without the presence and guidance of God`'s Spirit you cannot walk safely.
Truly it is great presumption in any man to read the Scriptures
boldly and without fear and reverence towards him who penned them,
or to put any of his own meanings and conceivings upon God`'s words.
But this is hard to avoid in the man who reads in the liberty of his own spirit,
without the light of God`'s Spirit, which is the limit and yoke of the true readers,
and of those who understand the Scriptures.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
4th of Fourth Month, 1668

[.letter-heading]
To a Couple About to Marry

[.salutation]
Dear Friends,   

It is a great and weighty thing that you are undertaking,
and you have need of the Lord`'s leading and counsel therein,
that it may be done in the unity of his life,
and so Friends in Truth may feel it to be of God, and find satisfaction therein.

Friends, the affectionate part will run ahead in things of this nature,
unless it is yoked down.
It can easily persuade the mind to judge such things to be right and of the Lord,
when indeed they are not so.
Now, if it be not of the Lord, but only the affectionate part,
Friends cannot have unity with it, nor will it prove a blessing to you,
but you will find it a hurt to your conditions and a load upon your spirits afterwards,
and the fruits and effects of it will not be good, but evil.
And then, perhaps,
you will wish that you had waited more singly and earnestly upon the Lord,
and that you had taken more time, and consulted more with Friends.

The Lord, by his providence, has given you a little time of respite.
Oh, retire unto him, and abase yourselves before him,
and pray him to counsel you by his good Spirit for your good!
Pray that, if it be not of the Lord,
his power (being waited upon by you) may loosen your affections in this respect.
But if it be of the Lord, and is brought before Friends,
and their counsel and advice is sought in the fear of the Lord,
then they will have unity with it, and with gladness express their unity.
This will be a strength unto you against the tempter afterwards.

This is in true love to you, and in singleness of heart.
From your friend in the truth,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
4th of Third Month, 1668.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Oh Friend!

Shall the Lord appear mightily on the earth and Israel not know him?
Shall the professors of this age understand no more of Christ`'s appearance
in Spirit than the Jews understood of his appearance in flesh?
Shall they stumble at the very same stumbling stone?
Yes, the same stumbling stone is laid for man`'s wisdom to stumble at,
as in all generations.
And there is no avoiding stumbling except by coming out of that
wisdom into babe-like simplicity which gives entrance into the pure,
heavenly wisdom.
And this I dare affirm as in God`'s presence and in his pure fear (having received
the sense of it from him)--that there are none today who oppose Christ`'s present
appearance in Spirit (through their great knowledge and wisdom from the letter),
who would not also have opposed and denied his appearance in that body of flesh,
had they lived in that day.
For the wisdom which the Jews gathered from the
letter did not reveal Christ in their day,
but only the Father; and the same must reveal him in this day.

Oh that you could experience the pure revelation from the Father to your heart!
Oh wait for a new heart, a new ear, a new eye!
Wait to experience the pure One in you, and to have your mind changed by him,
that all things may become new to you.
The Scriptures must be new (they are so indeed when God opens them), duties new,
ordinances new, graces new, experiences new;
there must be a new church of the Spirit`'s building,
wherein God and your soul may dwell together.
And you will be able to say in the presence of the Lord,
"`This is a city of God`'s own building, the foundation whereof was laid with sapphires,
whose walls are salvation, and its gates praise!`"

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
12th of Third Month, 1669.

[.letter-heading]
To Catherine Pordage

[.salutation]
Friend,

Your state and condition have been pretty much with me since I last saw you.
I am sensible how hard it is for you to give up
to be reached by the seed and power of life,
and how readily and easily your ear and heart is opened to another.
This word of advice has been much in my heart to you this morning:
Sit down and count the cost of plowing up your field,
and of searching after the hidden treasure of pure and true wisdom,
and consider seriously whether you can sell all for it, both inward and outward riches.
Then, if you do set your hand to the plow, you will not look back after anything else,
within or without,
but will be content and satisfied with the pearl of true wisdom and life alone.

Now if you are truly willing in God`'s sight to do this,
you must singly give up to follow the Lord in the leadings of his Spirit,
out of all the ways of your own wisdom and knowledge,
out of all things wherein you have a life and delight outside of him.
You must not try to determine what you have a life in,
but the Lord must search your heart.
And he will soon show you (if your heart is naked and open before him,
willing to hear and learn of him) something in your heart, something in your ways,
something in your words, thoughts, etc., which is contrary to his pure life and Spirit;
then that must be denied and given up immediately.
And afterwards, perhaps the Lord will soon discover to you another lover,
which has had more of your heart than you have been aware of.
And so you must part with one after another until you have parted with all.
But if you be not singly given up to the Lord,
though you should put your hand to the plow, you will be looking back some time or other.
And soon the wisdom which draws aside from the Lord will blind your eye,
and deceive your mind,
and draw you from the simplicity and nakedness of truth into an image,
so that instead of the pure truth itself, you will believe and embrace a lie.

The Lord has reached to you, and the Lord is willing to search your heart,
to find out the deceiver and enemy in his most secret lurking places.
But when the Lord has found him out, you must give him up to God`'s stroke,
and not allow him to find a shelter in your mind to save him.
For he is very subtle,
and will twist and weave all manner of ways to deceive you and save himself,
and you are not yet acquainted with, or able to discern, his devices.

You must come out of the spirit of this world, if you will abide in God`'s Spirit.
And you must come out of the love of the things of this world,
if you will come out of the spirit of this world.
For in the love of the things of this world, the spirit of this world lodges and dwells,
and you cannot touch the unclean things without
also touching something of the unclean spirit.
Therefore, John said from a true and deep understanding, "`Love not the world,
neither the things of the world,`" (if you love the things of the world,
you love the world), for "`if any man love the world,
the love of the Father is not in him.`"

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
11th of First Month 1670.

[.letter-heading]
To Thomas Walmsley

[.salutation]
Dear Friend,

There is something on my heart this morning to write to you,
in the same love wherein I have written before, which I feel to be pure, of God,
and unfeigned towards you and all men.
It is as follows: All true religion has a true root; but that religion, profession,
worship, faith, hope, peace, assurance, etc., which does not grow from the true root,
is not true.

Now this true root is near, and must be experienced near,
bearing the branch and causing it to bring forth fruit.
It is not enough to hear of Christ, or read of Christ,
but rather I must experience him as my root, my life, my foundation.
I must experience my soul ingrafted into him by the one who has power to ingraft.
I must feel repentance given to me by him, faith given to me by him,
the Father revealed and made known to me by him,
by the pure shining of his light in my heart.
God, who caused the light to shine out of darkness, causes it to shine in my heart,
so that in and through him I come to know, not the Son only, but the Father also.
And so I must come out of the darkness, out of the sin,
out of the pollutions of the spirit of this world, into the pure,
holy fellowship of the living, by his holy guidance and conduct.
And I must feel all my prayers, all my comforts, all my willingness,
all my ability to do and suffer for God and the testimony of his truth,
to arise from this holy, pure root of life.
This root gives daily strength against sin and death to all who wait
in true humility and pure subjection of soul and spirit upon him.
In this there is unspeakable comfort and satisfaction given by him to the soul,
which all the reasonings of men and devices of Satan cannot dampen.
For he who gave it preserves and maintains it over all the strength that can assault it.

Oh friend, I beseech you to come, oh come to the true root!
Come to Christ indeed!
Rest not in an outward knowledge, but come to the inward life, the hidden life,
and receive life from him who is the life.
And then learn to abide in and live to God in the life of his Son.
For death and destruction, corruption and vanity,
may talk of the fame of Christ who is the wisdom of God,
but they cannot know or find out the place where this wisdom is revealed.
They cannot approach the true, pure fear, which God puts into the hearts of his own.
This is the beginning of the true wisdom which cleanses darkness and
impurity out of the hearts of those to whom it is given.
For light expels darkness; life expels death; purity expels impurity; Christ,
where he is received, binds and casts out the strong man, taking possession of the heart.
And if any man be truly and really in Christ, he comes to witness a new creation,
even the passing away of old things, and all things becoming new.

Christ is faithful in all his house ("`whose house we are,`" says the apostle,
"`if we hold fast the confidence and the rejoicing of the hope, firm unto the end.`"
Heb. 3:6). He is faithful as a Son,
who comes in the name and authority of the Father,
to do whatsoever is to be done in the heart.
He is faithful in discovering whatever is contrary to God there,
and faithful in engaging his power against it.
And will not his power prevail?
And where it does prevail, and the good pleasure of God`'s goodness is fulfilled,
and the work of faith with power,
is not the name of the Lord Jesus Christ glorified there?
Read 2 Thess. 1:11-12. and consider.
Did Christ overcome the devil in that body of his flesh,
and shall he not overcome him in the hearts of his children by the power of his Spirit?
Therefore,
wait to feel the Spirit and power of Christ saving you
from that which nothing else can save you,
and bringing down in you under his feet that which nothing else can bring down.

This is from the true desire which my soul has,
after the eternal salvation and satisfaction of yours.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
28th of First Month, 1670

[.letter-heading]
To Widow Hemmings

[.salutation]
My Dear Friend,

Whom I truly love, and whose prosperity in the truth I earnestly desire.
Because I find your mind much engaged about one thing, that is,
receiving bread and wine in remembrance of Christ`'s death,
it is on my heart at this time to say something to you.
Perhaps the Lord may open your mind, and let you into a true sense of the thing.

There is a supper, or a supping with Christ, beyond outward bread and wine,
which he promised to those that heard his voice, opened the door, and let him in. Rev. 3:20.
Now it is that supper that my heart
desires you to be acquainted with and partake of.
And as you come to be acquainted with it, and partake of it,
you will call it the feast of fat things and of wines well refined.
Christ said,
"`I will drink no more of this fruit of the vine till I
drink it anew with you in my Father`'s kingdom.`"
What wine,
what fruit of the vine is it which Christ drinks
anew with his disciples in his Father`'s kingdom?
Is it not that wine which he and they drink now together when he sups with them?
Oh, the Lord give you an understanding, that you may come to the substance,
feel the substance, and inherit the substance forever!

"`Flee from idolatry, my dearly beloved,`" said the apostle. 1 Cor. 10:14.
What idolatry did he mean?
"`I speak as to wise men,`" said he "`you judge what I say.
The cup of blessing which we bless, is it not the communion of the blood of Christ?
The bread which we break, is it not the communion of the body of Christ?`" v. 15-16.
With regard to the outward cup and bread,
might they not easily run into idolatry?
But they that knew, discerned, and minded the body and blood indeed,
they did not run into idolatry.
"`For we being many, are one bread and one body;
for we are all partakers of that one bread.`" v. 17.
Oh, deep, deep, indeed!
The bread which comes down from heaven, that is the bread which gives life to the soul.
And unless we eat the flesh of the Son of man and drink his blood, we have no life in us.
But if we eat his flesh and drink his blood, we become one flesh with him,
bone of his bone.
Indeed, we become of the same bread with him, and so of the one body of the living bread.

My dear friend, the Lord give you an understanding, and open your heart,
and cause you to grow into union and experience of his truth,
so that by growing up in the truth, you may come more and more to understand it,
and be acquainted with it.

I am your unfeigned friend in the truth which is pure,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, 3rd of Sixth Month, 1670

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

The Lord God of heaven and earth, who searches the heart and tries the thoughts,
knows that we who are called Quakers have no secret
things or hidden principles among us to win people to.
We ourselves have been won over to the simplicity and
plainness of truth as it is in Christ Jesus,
and we walk therein, so it is the single desire of our hearts to bring men here,
where they may have the demonstration of God`'s Spirit,
and hear the true witness speaking truth in their own consciences.

Indeed,
it was a great matter of satisfaction to our hearts when the Lord turned us to his truth,
that we found it to be no new thing,
but rather that which we had witnessed and
experienced in the days of our former profession.
For all the prayers, and knowledge, and understanding of the Scriptures, faith, love,
zeal, meekness, patience, humility,
and whatever we then had in those days which was
dear unto us and precious in the eye of God,
came from this Spirit of life, this seed of life,
which God has now manifested to us more clearly, and turned our minds unto.
And oh that they, who yet speak against it, knew it, as the Lord has given us to know it!
Surely they could not then either think or speak so harshly of it as they do.
But Christ was indeed the Son of God in his appearance in flesh,
whatever the wise men and professors of that age judged and spoke of him.
And now we have the appearance and manifestation of the same Christ inwardly,
even the same virtue, life, and power, which appeared in that body of flesh,
whatever the professors of this age think or speak concerning it.
Indeed, they are not guiltless before the Lord,
but deeply guilty for rising up against it.

There was a precious appearance of God among that sort that were called Puritans,
before there was a rent among them by falling into several ways of worship.
There was among them great sincerity, and love, and tenderness,
and unity in that which was true.
They minded the work of God in themselves,
and were sensible of grace and truth in one another`'s hearts.
Now to desire to know the true worship, this was good;
but everyone that had this desire was not acquainted with the Spirit of the Lord,
nor did they wait aright on him to be led by him into the true worship,
but rather followed the apprehensions and conceivings
of their own minds upon the Scriptures.
Now, had these known the true Leader, they would never have wandered away,
nor have been so scattered from the Puritan state.
For is it possible, if the Spirit of God had been the Leader of these,
that they could have wandered away from the truth, life, love, into a barren,
dead state in comparison of that?
It is true there was a sincerity and simplicity in many of them,
but that sincerity and simplicity was betrayed
and drawn out to seek the living among the dead,
among dead forms, ways, and worships.
For though they carried some life with them into their outward forms,
yet by degrees the forms grew, and the life and power decreased,
and they were swallowed up in high esteem for, and contentions about,
their various forms.
But they themselves lost what they were inwardly to God,
and had inwardly received from God in the days of their former zeal and tenderness.
Oh that they could see this!
Oh that they could return to their Puritan state, to the sense they then had,
the love and tenderness that was then in them,
to the experience of the seed of life which they then felt,
and which then worked in them!
Though they did not distinctly know it,
yet they loved that which gathered their minds to God,
and which gave them an ability to pray, and opened the Scriptures and the things of God,
and warmed their hearts in some measure.
Oh that they were but there again!
They might soon come further.
Oh that they knew their state, as it is known in the light of the Lord,
and by the Spirit of the Lord!
The Lord open the true eye in them, and give them to see therewith.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, 19th of Seventh Month, 1670

[.letter-heading]
To Nathaniel Stonar

[.salutation]
Dear Friend,

There is a great dispute between us and professors concerning the rule,^
footnote:[As mentioned previously,
the word _rule_ is used throughout to refer to that which governs, rules,
or has true authority in the life of the believer.]
which they hold forth to be the Scriptures.
Now truly I could wish, from the depth of love in my heart to them,
and from my desire of their good,
that the Scriptures (rightly understood by them) were their rule,
and not their own reasonings, conceivings, and apprehendings upon the Scriptures.
But yet, if this were so,
they would need to admit that the Spirit of life--who is truth that lives in the heart,
and law written by the finger of God in the inward parts--is
nearer and more powerful than the words or outward
descriptions concerning these things in the Scriptures.
Indeed, there is a measure of life to be received,
there is the Spirit of life to be received, there is a well of life,
from which pure life springs up,
to be received and enjoyed by them that truly and rightly believe.

The Lord, in the gospel state, has promised to be present with his people,
not as a wayfaring man for a night, but rather to dwell in them and walk in them.
Yes, if they are tempted and in danger of erring,
they shall hear a voice behind them saying, "`This is the way, walk in it.`" Isa. 30:21.
Will they not grant this to be a rule as well as the Scriptures?
Indeed,
is this not a more full direction to the heart than
what a man can pick for himself out of the Scriptures?
Truly, this testimony is true, which now springs up in my heart unto you, which is this:
The Lord has poured out his Spirit upon his sons and daughters,
in and by this precious dispensation of truth, and of the pure seed which is so despised.
And the Spirit which gave forth the words is greater than the words.
Therefore, we cannot help but prize him himself,
and set him higher in our hearts and thoughts than the words which testify of him,
though the words are also very sweet and precious to our taste.

There was a measure and rule unto which the true
ministers of Christ and the believing Gentiles had attained,
and by which they were to walk. See 2 Cor. 10:13,15.
"`According to the measure of the rule which God has distributed to us`"
and "`according to our rule,`" etc.,
and Phil. 3:16, "`Whereto we have already attained, let us walk by the same rule,
let us mind the same thing,`" as also in Gal. 6:15-16, "`For in Christ Jesus,
neither circumcision avails anything, nor uncircumcision, but a new creature.
And as many as walk according to this rule, peace be on them, and mercy.`"
Now consider what that rule was.
Oh that you may know it and walk by it even as they that had received God`'s Spirit did!
For I am assured in my heart that if you receive God`'s Spirit, and live and walk therein,
you cannot fulfill the desires of the flesh,
but you will find your heart opened thereby into a true sense, understanding,
and right use of the Scriptures.
For the Scriptures of the New Testament were written to the saints of old,
and so cannot be truly or rightly understood or made use of,
except as men come into their spirit and state.

These things are of great weight and concernment.
May the Lord open and guide your heart into true
satisfaction in this and other things also,
from the demonstration of his own Spirit.
Then you will truly be able to say as in his sight,
"`Now I believe and understand things, not because this or that man has said so,
but because the Lord, who is the Teacher indeed,
has taught and assured my heart concerning the truth itself, as it is in Jesus,
which I feel to be true by its living virtue and
powerful operation in and upon my heart.`"

This is my desire for you, who am your soul`'s true and sincere friend,
who would by no means have you deceived about anything.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Reading Jail, 24th of Seventh Month, 1670

[.letter-heading]
To Widow Hemmings

[.salutation]
Dear Friend,

Since I last saw you there have been many deep
and serious thoughts on my heart concerning you,
and a sense of your state as before the Lord, and breathings of heart for you.
I am sensible that the Spirit of the Lord is striving with you,
and in some measure opening your heart towards him and his truth.
And I am sensible that there is much striving against him,
and many strong-holds of wisdom and reasonings in you,
which must be broken down before truth can spring up in
your heart and exercise its power in you,
and have full command in you.

Now this morning when I awoke, there were three things that sprang up in me,
which my heart did singly and earnestly desire for you.
One was that you might be led by God`'s Holy Spirit into the new and living covenant,
where Christ is revealed,
and the soul is united to him as its Lord and King in a bond of indissoluble union.
Another was that you might daily be taught of God, and learn of him in this holy, new,
pure, and everlasting covenant.
The third was, that you might be true and faithful to God,
to obey and follow him in whatever he teaches and requires of you.

If you were in this state, you would find sweetness and rest, peace and power,
the righteousness of our Lord Jesus Christ and life eternal revealed in your own heart.
And with joy you would draw water out of the wells of salvation.

Now, if you come to witness Christ`'s appearance in spirit,
and are willing to become a disciple unto him,
there are three things you must apply your heart to learn of him.
These three are indeed the sum of the gospel, or of what is taught in and by the gospel.

The first is to fear God.
This is the beginning of true, heavenly wisdom,
and this is the perfection and the end of wisdom also.
For true wisdom not only brings into the fear of the Lord, but it builds up in the fear,
and even perfects in the fear also, according as the apostle says,
"`Perfecting holiness in the fear of the Lord.`"
Now this is not such a fear as man can attain by all he can do,
but rather is the fear of the new covenant,
which God puts into the hearts of his children as he
quickens them and brings them up in the new covenant.
This is such a fear that those in whom it is placed cannot depart from the Lord,
nor can those abiding in it err from the way of life and holiness.
For all sin and transgression,
all rebellion against the Lord and grieving and quenching his Spirit,
is outside of this fear.
Oh that you might receive this fear from the Lord, and grow up unto him daily in it!

The second, which depends upon and flows from the former,
is to give glory to God by discerning his life and power,
and experiencing the virtue of his Spirit and his grace working all things in you.
In this way, all glory is ascribed to him in all that you are, do, or can do.
For in the day of the gospel, no flesh can glory in the presence of our God,
but the Lord alone is exalted in the spirits of his children in that day.
And indeed, as every one comes into the fear of the new covenant,
the presence of the Lord is there, dwelling in the midst of the heart.
And God is found working there in all things, and bringing forth the seed of life,
and working down sin, and death, and corruption.
Those who are here feel their own poverty and nothingness as in themselves,
and see that the way to become strong in Christ is first to become weak in themselves.
And so when they are strong in him, he who is their strength is glorified and admired,
and self is of no reputation or value forever and ever.

The third is, that you learn to worship God in spirit and truth.
Oh this worship is precious indeed!
This is the only sort of worship which God seeks and regards among
the many various kinds of worshippers which appear at this day.
This worship was declared by Christ and taught by his disciples,
but it has been in great measure departed from.
And though many have sought after it,
yet none could ever find it except as they have
learned of the Father to return to the anointing,
and so to be gathered into his Spirit where Christ`'s name is known.
And of a truth, no one knows or can worship in Christ`'s name besides these.

There have been great mistakes about worship and gatherings.
They have not been in the name and power of our Lord Jesus Christ,
but only in an outward profession of his name,
and in an imitation of things without the true life and power.
But what is such worship and religion in the sight of the Lord?

Now, in order that you may come into this state and learn
all these lessons of the Lord in the new covenant,
there is one thing indispensably necessary for you, which is this:
to know the hour of God`'s judgment in your own heart,
and to lie under the judgment of the Lord.
Friend,
mind the words which now spring in my heart to you (for now my heart
is open to you in the true love and pure sense which is of God).
If you come to know God`'s Spirit, and to receive it, and feel it work in you,
and its pure light shines from the fountain of life,
you will have a quicker sense and discerning than can
arise from either words written or from thoughts.
The Lord will show you the way quicker than a thought can arise in you;
and the Lord will show you evil, in a pure sense of the new nature,
quicker than you can think of or consider anything.
And indeed this is needful.
For sin lodges in the evil nature inwardly, and works,
not so much by a known law set up in the mind, as by a secret nature.
And if this nature is not resisted and withstood by another nature,
it can never be overcome.
Now it is by his judgment set up in the heart
that God does overcome and keep down sin forever;
for the judgment of God is stronger than sin,
and will bring it down when his judgment is received.
And it being kept down, life and righteousness, even the righteous life, Spirit,
and power of the Lord Jesus inwardly revealed, will be uppermost and will reign over it.
And then you will know what it is to be a king and priest to God,
and to come to the laver at which God`'s priests wash,
and to the blood with which their right ear, and thumb, and toe, is sprinkled,
according to the type and shadow under the law.

Perhaps these words at present may be hard for you.
But if you come to wait on God`'s Holy Spirit,
and experience his appearance in your heart,
and learn of him to know what is good and what is evil in your words, ways, worship, yes,
and in your very heart and thoughts,
and learn also to choose the good and refuse the evil,
they will daily grow easier and easier, and plainer and plainer.
And you will find Christ (inwardly revealed in spirit)
to be very properly called the word of God,
even the ingrafted word which is able to save the soul.
For he is quick and powerful, and sharper than any two-edged sword,
able to cut down all that shall appear or rise
up in the heart to resist or oppose his work.

This is from one who wandered long in the vast howling wilderness,
adrift from the Shepherd and Bishop of the soul.
I was sorely afflicted, tossed with tempests, and not comforted.
But at length it pleased the Lord in tender mercy to visit me,
and by his own outstretched arm to gather me into his own fold.
And here I have met with the holy mount of God, and his city the heavenly Jerusalem,
and the spirits of the just men, and God the judge of all that ever arises in the heart.
And I have found Christ the mediator, and the new covenant,
wherein and whereby he mediates,
and the blood of sprinkling which speaks good
things to the souls that are sprinkled with it.
Yes indeed, here are all the good things met with and enjoyed,
which were given in shadow under the law.
And here are the precious promises fulfilled,
which make us partakers of the divine nature.

What shall I say?
The Lord knows that I do not speak these things boastingly,
or to lift up myself above others in my thoughts,
but rather in tenderness and humility of heart, as before the Lord, for your sake.
And now this is my desire and prayer to the Lord,
and the travail of my soul in his life and spirit:
that those who are yet scattered from the fold of rest, that is,
the rest of the sheep of the house of Israel that are as yet
lost and scattered up and down in their own apprehensions,
conceivings, and various gatherings, ways of worship,
likenesses and imitations of things without the true life and power,
that these may be gathered out of all of this, and into the same life, power, and rest,
into which God has been pleased in his great mercy to gather us.

The Lord give you the sense and savor of these things,
that you may thereby be kindled to wait upon the Lord,
and be led into the light of the living.
And may you live and walk with him who is, and dwells, and walks with his own,
in the light.
Oh house of Jacob, come now, let us walk in the light of the Lord,
and let us come up to Zion, the holy hill of God, and to the new Jerusalem,
that there he may teach us of his ways,
and we may there learn of him to walk in his paths!
For indeed,
here is the place of wisdom and true understanding
which none know but those that are taught of God.

This is in true friendship and tender love to your soul,
from its friend in truth and sincerity,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
26th of Eighth Month, 1670

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

Professors of Christianity have long known the name of Christ,
and what the Scripture relates concerning him,
but oh that they could know Christ himself, and receive him into their vessels,
and feel life flowing from him into them!
Then would they indeed know Christ according to the Spirit, which knowledge makes alive,
but the literal knowledge kills.
For he that has the Son,
he that is in true union with him and really changed by
him so as to become one nature and spirit with him,
this one has life.
But he that has not the Son has not the life of the Son, nor the liberty of the Son,
but is in the death of sin, and in service unto sin.

The directions from God`'s Holy Spirit in the Scriptures are
exceedingly weighty and precious in themselves,
and blessed is he who is found in the practice and observation of them.
And it has been the desire of my heart from my childhood, and still is,
that I might be found walking with the Lord according to what
is there taught and prescribed to the children of God,
in the several foregoing ages and generations.
These things were written, and are useful, for our instruction also, being read by us,
and heeded, in that light which gives the true understanding of them.

But though this was my desire, yet the way to attain this I missed.
For I thought that by getting the directions of Scripture into my mind,
and applying myself to the strict observation of them,
and praying for God`'s Spirit and help, I might obtain what I desired.
And truly the Lord was merciful to me, and did help me in a great measure,
but I still often felt the temptations and
darkness of the enemy nearer to me than my rule,
and in many cases I knew not what to do, nor how to resolve this with the Scriptures.

At length the Lord greatly distressed me,
and brought me to a fuller sense of my lack of his Spirit and power.
He dashed all my religion in pieces so that I was just like Babylon,
for in one hour judgment and desolation came upon me. Rev. 18:10.
I knew not what to do without the Lord, nor which way to draw nigh to him.
But the Lord was preparing me for that day of mercy, which since, in his tender goodness,
has broken in upon me.

And now the eye which he has opened in me sees that the gospel is a
ministration of the Spirit and power of the Lord Jesus Christ.
And I see that he who desires to be his disciple must be turned to his Spirit,
and receive the immediate light and shining of his Spirit into his vessel.
He must experience the law of life, the holy law of the new covenant,
not comprehended outwardly in the mind,
but written inwardly in his heart by the finger of God`'s Spirit.
And being written in his heart, this law has power over the heart, and causes him to obey.
And here he cannot help but fulfill the holy directions of the Scriptures,
for he is abiding in that from which they came,
and that which reveals the substance of them unto him,
and makes them living and powerful in him.
For indeed the law of sin and death has power over a man so long as he lives,
but when he meets with that which kills sin and death in him, and makes him alive to God,
he receives life in abundance in and through the Lord Jesus Christ.
Then the fruits of life become easy and natural to him, and the fruits and ways of sin,
unbelief, and disobedience become unnatural.
Here the yoke is easy and the burden light,
and none of the commandments of our Lord Jesus Christ are grievous.
But when they are taken merely out of the letter,
without experiencing the Spirit leading and making
alive and enabling the performance of them,
oh how heavy, how hard are they!
How impossible to believe aright, hope aright, pray aright, walk aright,
watch aright over the heart, fight against the enemies, lusts, and corruptions aright!
On the other hand, how pleasant is the way of life in the covenant of life,
in the power and virtue of life, when ministered from the Spirit of our God!
Here is God praised, and victory over his enemies is witnessed,
and peace with him is enjoyed in the pure seed of life.
Blessed be the name of our God forever!
For the letter, or the description of things, is not the way.
But the life is the way, the Spirit the way, the power the way,
the truth as it is in Jesus the way,
which none can truly and rightly know except as
they are ingrafted into and formed in him,
and he formed in them.
And this is only obtained, witnessed, and preserved,
in the soul`'s union and communion with, and obedience to,
God`'s Spirit and power inwardly revealed and made manifest.

This is in the nakedness of my heart, as in the Lord`'s sight,
and in the truth of friendship towards you.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
27th of Ninth Month, 1670

[.letter-heading]
To Widow Hemmings

[.salutation]
Friend,

As one comes to any sense or touch of truth from God`'s Holy Spirit,
doubts and scruples may very well arise in the mind concerning prayer,
since this duty has been performed and practiced
so long from the fleshly mind and nature,
and not in the leading, will, and compass of God`'s Holy Spirit and power.
And those who doubt in this matter cannot be satisfied till the Lord
open their spirits and make the thing manifest to them.
Yet this is most certain: that all prayer, all true prayer to God,
is in and from his Holy Spirit,
and whatsoever is otherwise is not accepted of the Father.
The promise, indeed, is to the prayer in faith, and to the prayer in the Holy Spirit,
but not to the prayer of the fleshly birth, will, or wisdom.
Therefore,
the great concern in prayer should be that that which is of God pray unto the Father,
in the quickenings and motions of his own Spirit.
For the dead cannot praise God, nor can the dead truly pray unto him.

Now, by abstaining from prayer there can be no peace,
for we are meant to pray continually.
Nor will peace be found by praying in a formal way without life, that is,
without God`'s Spirit (who gives ability to pray, and who makes intercession).
But it is manifest that prayer is not in the time, will, or power of the creature,
for it is a gift of God, and the ability lodges in his Spirit.
Prayer is not in us, except as it is given by his Spirit, which, therefore,
is to be waited upon, when it will move and breathe in us,
and so give us the ability of calling upon the Father in the name, and through the life,
of the Son.

Now as to your questions, I shall answer in plainness,
as the Lord is pleased to open my heart.

As to the first:
Whenever the creature finds breathings to the Father from a true sense of its needs,
these are not to be stopped,
but are to be offered up in that from which the breathings come.
For there is no true sense of one`'s condition, or of one`'s needs,
except from the Spirit of the Lord.
And it is the Lord who gives this sense, so that the soul might feel its need of him,
and cry to him.
And every sigh and groan that is in this way offered up to him is accepted of him,
and prevails with him for good towards that soul.

Now in particular,
the soul ought to pray for the appearance of God`'s Spirit and power.
And if it already tastes something of it, it ought to pray for more of the Spirit,
and that it may distinguish the requests that rise up in the heart,
whether they come from God`'s Holy Spirit and will, or from the fleshly nature and will.
For the wrong birth also desires the kingdom, and would possess the kingdom,
and prays for the kingdom, and strives for the kingdom; but it prays amiss,
and it strives amiss, and so it will never obtain, for the kingdom is appointed for,
and given to, another.

As to the second: Those that do not know,
nor are sensible partakers of the Spirit, yet feeling their lack thereof,
and true desires after it, ought to offer up those desires to God.
And if they keep to that which begets those desires,
they shall not long be ignorant of God`'s Spirit,
but will find that God is more willing to give it than
a parent to give necessary things to his children.
But as for those who have prayed long for the Spirit, and yet have not received it,
these have just cause to question the nature and ground of their prayers,
since God is so ready to give the Spirit to his children.
For does a child ask bread of his father for many years, and not receive it?
Oh, consider this thing!
If the child ask the Spirit aright,
it is impossible that he not receive some proportion of it from the Father,
as much as is necessary to his present state.
God requires his children to perform everything unto him in and with his Spirit,
knowing they can do nothing right without it.
And surely he will not require duties of them while withholding the Spirit,
without which they cannot acceptably perform these duties.

As to the third:
A mere notion that all the soul`'s supplies are from the
Father is not a sufficient ground of prayer;
for the wrong birth may, and often does, pray with such a notion.
Rather, a true feeling of the thing is a sufficient ground,
if the heart and mind keep within the limits of the feeling,
and offer up no more than what arises there.
Oh that everyone who has any true sense of God might wait on
him to savor this little thing which arises from God,
from amidst the multitude of his own thoughts, words, and desires,
which are from another root, even from the flesh, which is of no value,
and cannot avail with the Lord.
But the birth of life, the sensible breathings of his own life,
in the poorest and weakest babe, are always of esteem, and prevail with the Father.

As to the fourth: It is true that prayer is of God and is a duty.
Though not all prayer is such,
but only that which is within the limits of the true
Spirit and power--"`praying always in the Holy Ghost.`"
The pure prayer, the pure breathings of God`'s child, from the true birth,
is always within the limit which God has prescribed.
Therefore "`watch unto prayer,`" watch unto God`'s preparing
the heart by the motion and virtue of his good Spirit,
and offer up the breathings that then arise.
Wait to distinguish between the desires which arise from the fleshly part,
and the desires which arise from the spiritual and heavenly part.
For the first nature is earthly;
but the second nature (the nature which is from the second Adam,
the life-giving Spirit) is pure and heavenly,
and so are all the desires and breathings that spring from that nature in the vessel.
And as you come into that nature, and into that Spirit from which the nature proceeds,
you will truly distinguish concerning prayer, concerning faith, concerning love,
and all other spiritual things.
And you will know him who is truth and no lie,
and who preserves out of all error and deceit.

You seem also to be disturbed about some other duties as well as prayer.
Indeed, all flesh should be silent before him.
Alas, what room is there for his Spirit and power when there is such a multitude of thoughts,
workings, and reasonings, and such a noise of flesh in many hearts and spirits?
Happy is he who feels his flesh to be silent,
who comes to an end of his own willing and running!

The Lord raise up in you that which is of him, and so guide and order your heart,
that it may breathe and cry after him, and be heard and satisfied by him.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
28th of Ninth Month, 1670

[.letter-heading]
To Elizabeth Stonar

[.salutation]
Dear Friend,

I am sensible that the Lord has visited you with his power,
reaching to your heart in the demonstration of his own Spirit,
and that your heart has answered and said, "`It is God`'s truth indeed.`"
Now, in as much as God has reached to you, so it behooves you to confess him, his truth,
and his people before men,
and to give up in obedience and subjection of spirit to the Lord.

May the Lord guide you, and pity you, and help you in your difficulties, doubts,
and fears, both in reference to yourself and your mother.
God is my witness, whom I serve in my spirit in the gospel of his Son,
that I have not sought myself, but your good, and that not of myself either,
but in the leadings and drawings of his Holy Spirit.
And I gave your husband a warning, in true and tender love,
though I knew well enough how hard it would be to his spirit in its present state,
and what a bitter enemy he might become to me for telling him the truth.
I did it not unadvisedly, but in heaviness of spirit before the Lord.
And I heartily wish that he were not deceived in his heart concerning his own state,
but truly knew it as it is.

There is a light, which enlightens the soul, or else it remains in darkness.
"`You were darkness,`" said the apostle, "`but now are you light in the Lord.`"
Now, no man can become light in the Lord unless his nature and
spirit be renewed and changed out of darkness into light.
Now the question is, what is this light, and where is it to be met with?
Are the Scriptures this light?
Or do they testify of this light?
If they only testify of this light, then the light itself is to be come to,
and the soul is to be enlightened by it.
And he that comes to this light, and is enlightened by it, and walks in its pure shining,
this one becomes a child of light.
But he that is not enlightened and changed by it, this one is still a child of darkness,
regardless of what he learns, professes, or practices by imitation from the Scriptures.
This is a weighty matter.

Oh come, be not wedded to your own ways,
nor prejudiced against what God has taught others!
But let things be fairly examined that all things may be proved,
and that which is good held fast.
For truth will never lose ground by being tried.
But darkness is afraid of the light,
for it has a secret awareness that it cannot stand before it.

I am your soul`'s true and sincere-hearted friend,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
16th of Twelfth Month, 1670

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

The enemy kindles a great distress in the mind by stirring up an earnest desire,
and a sense of a seeming necessity to know.
For such thoughts arise, "`What shall I do to know whether it is of God or no?
For if it is of God, it ought to be obeyed.
And if it is not of God, it ought to be resisted.
But what shall I do, who cannot tell what it is?
I will of necessity fall either into disobedience to God`'s Spirit,
or into the snares of the enemy!`"
Thus the enemy raises up thoughts in the reasoning part which are unanswerable there.
But what if it were better for you at present to be darkened about these things?
Can that possibly be?
Yes it may, in many respects.
For there is something else that might rise up and be acting
in you if clear and heavenly knowledge were given.
For even what you receive from God can be centered in self.
In this way, you can miss the way of true knowledge,
and never learn in every state to be content, nor know the pure way and motions of life.

Truly, this is not the way of the child`'s knowing.
Instead, the child knows in resignation and subjection of its very knowledge.
And if there appears ever so great a necessity of knowledge,
and yet knowledge is not given,
then it sinks in fear and humility into the will of the pure seed.
And there something springs up (unknown to the natural wisdom,
and not in the way of man`'s wisdom), which preserves and bears it up in such a state.
This is a great mystery, yet it is sensibly experienced by the true travelers at this day.

Therefore,
retire out of all necessities that are according
to the apprehension of the reasoning mind,
and judge to be necessary only that which God, in his eternal wisdom and love,
delivers unto you.
And when you come to this, you will come to your rest; and as you abide here,
you will abide in your soul`'s true rest,
and you will learn the precious lesson of being content in every state.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

What is Paul?
What is Apollos?
What is Cephas?
It is one and the same pure life and word of
power which springs in all the holy brethren,
whom God has sanctified and prepared to give forth the sound of his holy trumpet.
It is the Lord himself who gives forth the true and certain sound,
and great is the company of those whom he has chosen and sent forth to make it known.
These cannot be despised in their message without despising him that sent them.

Oh,
take heed of that nature and spirit in you which desires and seeks after a sign!
It is the evil and adulterous generation which seeks after a sign.
But wait to meet with him inwardly, who changes the heart, and renews the mind to God.
Know him who teaches to love the Lord God with all the heart, soul, mind, and spirit,
so that true life from and in him may be witnessed.

Now, as for being as one of us, you must be formed so by the Lord,
by being inwardly changed and renewed by the Spirit and power of the Lord,
before you can witness true unity with us.
If you feel the seed of truth in your own heart,
and in that seed you know and acknowledge us, and so come among us,
and join to us in the truth, and keep faithful to the seed,
you will never be in danger of leaving us.
But they that depart from the seed in their own
hearts will soon and easily depart from us.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

Hearken to a word of advice which is in my heart to you,
for it may be of great use to you,
if the Lord opens your spirit and causes it to sink in.
It is as follows:

Wait on the Lord,
that you may feel from him the right limit to the mind in reading the Scriptures.
For the mind of man is busy and active, willing to be running beyond its bounds,
guessing at the meanings of God`'s Spirit, and imagining for itself,
unless the Lord limits it.
Therefore read in fear,
and wait to distinguish between God`'s opening to you the things of the kingdom,
and your own apprehensions about them.
For the one must be always cast away, and the other must always be embraced by you.
And always await God`'s season.
Do not presume to understand a thing before he gives you the understanding of it.
He alone is able to preserve the true sense and knowledge in you,
and you must learn to live dependently upon him for your knowledge,
and never "`lean on your own understanding.`"
Little do you know what it has cost us to have
our own understanding and wisdom broken down,
and how manifestly (by this Spirit) the Lord opens Scriptures to us (yes,
the things themselves, which the Scriptures speak of),
ever since he taught us to deny our own understanding,
and to lean upon his Spirit and wisdom.

The Lord guide you by his certain and infallible Spirit, into the certain,
infallible, everlasting way of life, so that by the shining of his light, Spirit,
and power in you, you may see light, and enjoy life.
For even if you did understand all the words, descriptions,
and testimonies in the Scriptures; yet it is one thing to understand words, testimonies,
and descriptions, and it is another matter to understand, know, enjoy, possess,
and live in that which the words describe and bear witness of.

And friend, if you will be an inward Jew,
and know and understand the laws of life, the laws of the new covenant,
you must read them in the tablets where God writes them in the new covenant.
Indeed, by reading in the letter,
you may read testimonies concerning the Spirit and his ministration,
but you must read in the Spirit if ever you will come rightly to understand the letter.
And the end of words is to bring men to the
knowledge of things beyond what words can utter.
So learn of the Lord to make a right use of the Scriptures,
which is by esteeming them in their place,
and prizing above them that which is above them.
The "`eternal life,`" the Spirit, the power, the fountain of living waters,
the everlasting, pure well, is above the words concerning it.
This, the believer must witness in himself, and from it he will draw water with joy.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To the Friend of Francis Fines

[.salutation]
Friend,

After some deep exercise of spirit concerning you,
under great grief of heart for you, I felt a constraint of love,
forcing these following considerations from me, to lay before you.

I am satisfied in God`'s Spirit that that which
I have written in the last letter I sent to you,
is the sum and substance of true religion.
The sum and substance does not stand in getting a notion of Christ`'s righteousness,
but in experiencing the power of the endless life, receiving the power,
and being changed by the power.
And where Christ is, there is his righteousness.
He that has the Son has life and righteousness;
but he that has not the Son has not life nor righteousness.
And where Christ is not, there is not his righteousness, but only a notion of it,
from apprehensions formed from the Scriptures by
man`'s wisdom (a wisdom which should be destroyed)
My desire for you is that your knowledge not be here, nor your standing here,
nor your faith here, but rather in the truth and life itself.

Christ was anointed and sent of God, a Savior, to destroy the works of the devil,
to break down all rule and authority contrary to
God in man--for his work is in the heart.
There he makes alive, there he raises,
there he brings into death that which is to die by raising the seed immortal,
and bringing the creature into subjection to it.
Now, to experience the power that does this, and to experience this wrought by the power,
this is far beyond all talk about justification and righteousness.
Here I desire you to come, out of the talk, out of the outward knowledge,
into the thing itself, and into the truth of the new and living knowledge.

There is a power in Christ to mortify and overcome sin in the very root.
It is not, however, overcome, except in the revealing of this power;
nor is the soul justified, except in and by the working of this power.
Therefore, justification is not the first thing,
but the power of life revealed in Christ,
in and through which the soul is both justified and sanctified,
through the working of the faith which is from the power.
And here salvation is felt nigh indeed to those that truly fear the Lord,
and glory dwells in the land which he has redeemed.
There, mercy and truth do indeed meet together,
and righteousness and peace kiss each other.
Yes, there truth springs out of the earth, and righteousness looks down from heaven.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To the Lady Conway

[.salutation]
Dear Friend,

As I was recently retired in spirit and waiting upon the Lord,
having a sense upon me of your long, sore, and deep affliction and distress,
there arose a scripture in my heart to lay before you, namely, Heb. 12:5-7.
I entreat you to call for a Bible and hear it read,
before you proceed to what follows.

Oh my friend, the Lord has been pleased in his tender mercy to visit us,
and to turn our minds from the world and from ourselves towards him,
and to beget and nourish that which is pure and living of himself in us.
Nevertheless, there remains something at first (yes, and perhaps for a long time),
which is to be searched out by the light of the Lord,
and brought down and subdued by his afflicting hand.
For when indeed something of the holy will is formed in the day of God`'s power,
and the soul (in some measure) is begotten and brought
forth to live to God in the heavenly wisdom,
yet still, all the earthly will and wisdom is not thereby immediately removed.
Indeed, there are hidden things of the old nature and spirit still remaining,
things which perhaps are not visible because they sink inward into their root,
so that they may save their life.
Such things a man cannot possibly discover in his own heart,
but only as the Lord reveals them to him.
But how does the Lord find them out?
Oh consider, his "`fire is in Zion, and his furnace in Jerusalem!`"
By casting us into the furnace of affliction, the fire searches us.
The deep, sore, distressing afflictions, which rend and tear the very inward parts,
these uncover both the seed and the chaff,
so that the gold can be purified and the dross consumed.
And then, at length, the quiet state is witnessed,
and the quiet fruit of righteousness is brought forth by the
searching and consuming nature and operation of the fire.

Oh that your soul may be tried unto victory
over all that is not of the pure life in you!
And may you wait to feel the pure seed, or measure of life in you, and die into the seed,
experiencing death unto all that is not of the seed in you!
And oh that you would experience life, healing, refreshment, support,
and comfort from the God of your life, in the seed, and nowhere else.
May the Lord guide you daily and keep your mind to him,
looking towards the holy place of the springing of his life and power in your heart.
Look unto him, and help, pity, salvation, will arise in his due time!
But it will not arise from anything you can do or think.
Faith will spring, and patience will be given, and hope in the tender Father of mercy,
and a meek and quiet spirit will be experienced.
The Lamb`'s nature will spring up and open in you from his precious seed,
and it will excel in nature, kind, degree, and virtue, beyond all the faith, patience,
hope, meekness, etc., which you, or any else, could otherwise attain unto.

Oh, look not at your pain or sorrow, however great it is!
Rather, look from them, look off them, look beyond them, to the Deliverer,
whose power is over them, and whose loving, wise,
and tender Spirit is able to do you good by them.
And if the outward afflictions work out an exceeding weight of glory,
oh what shall the inward afflictions do for those who are humbly, brokenly,
and faithfully exercised before the Lord by them!

If you will receive the kingdom that cannot be shaken,
you must wait to have that discovered in you which can be shaken.
This must be removed out of its place, and the heavens also rolled up like a scroll,
by the Lord`'s arising terribly to shake the earth.
And while the Lord is doing this,
he will be hiding you in the hollow of his hand (your mind still retiring to the seed),
and he will, in these troublesome and dismal times,
inwardly be forming the new heavens and the new earth, wherein righteousness dwells.
The Lord lead you day by day, in the right way, and keep your mind staid upon him,
in whatever befalls you.
And may you go on as a disciple, learning righteousness and holiness of him,
who teaches to deny and put off unholiness and unrighteousness, and to know, embrace,
and put on the newness of his life, and the holiness and righteousness thereof.

The Lord God of my life be with you, preserving and ordering your heart.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To an Unknown Recipient

[.salutation]
Friend,

It is of the infinite mercy and compassion of
the Lord that his pure love visits any of us,
and it is by his preservation alone that we stand.
If he leave us at any time, even for one moment, what are we?
And who is there that does not provoke him to depart?
Let him throw the first stone at him that falls.

In the truth itself, in the living power and virtue, there is no offense.
But that part which is not perfectly redeemed,
still has a place for the temptation to work upon, and it may be taken in a snare.
Let him that stands, take heed lest he fall; and with a heart of pity,
he should mourn over and wait for the restoring of him that is fallen.
That which is so apt to be offended, is the same as that which falls.
Oh, do not reason in the high-mindedness against anyone that turns aside from the pure Guide.
Rather fear, lest the unbelieving and fleshly-wise part get up in you also.
Oh you must come to know the weakness of the creature when the life withdraws!
You must know the strength of the enemy in that hour,
and the free grace and mercy which alone can preserve!
Knowing this, you will stand amazed that any do stand, rather than that some do fall.

When the pure springs of life open in the heart,
immediately the enemy watches his opportunity to get entrance,
and many times finds entrance soon after, for the soul little fears or suspects him,
having lately felt such mighty, unconquerable strength.
Yet, how often then does he get in, and smite the life down to the ground!
And what can he not do with the creature, unless the Lord graciously help!

Oh, great is the mystery of godliness, the way of life narrow,
the travel to the land of rest long, hard, and sharp.
It is easy to miscarry; it is easy to step aside at any time;
it is easy losing the Lord`'s glorious presence,
unless the defense around it be kept up by his Almighty arm.
Ah, turn in from the fleshly wisdom and reasonings, unto the pure river of life itself!
Wait there to have that judged in you which has been offended,
lest it grow stronger in you and draw you away from the life.

This is in dear love to you: retire from that part which looks out,
and feel the inward virtue of that which can restore and preserve you.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Widow Hemmings

[.salutation]
My Dear Friend,

Whom I have always truly and faithfully loved as in the sight of the Lord,
and to whom my love in the Lord still continues.

Since I heard of your illness and weakness by M.S.,
I have had an earnest desire to see you, and have been considering how to effect it,
but cannot with any convenience at present,
as my friend T.E. (the bearer of this letter), can further inform you.
But the desire of my heart to the God of my life is
that he would give you a visit in his tender pity,
and guide and help you to stay your mind upon himself, in his most precious truth,
of which he has not only given you a taste, but many times a full sense and experience.

Oh my dear friend, may nothing come between your soul and God`'s truth!
And may your comfort, peace, and joy be full,
and may you lay down your head quietly in the bosom of him who loves
you and accepts the sincere desires of your heart towards him.
Pay no mind to temptations or accusations,
nor the many noises the enemy will make in you and against you.
But wait to experience truth and life springing in your heart from the holy well,
and to hear the still voice of the Spirit of the Lord,
for he will testify his love to you, and speak peace.

Oh may the tender compassion of my heavenly Father
relieve you and gather you inwardly,
and preserve you where the enemy cannot break in upon you.
Look not upon your sins, even those committed since you have known the truth.
Rather wait to feel something inwardly in which God appears and breathes, and gathers,
and receives, and eases the fears, doubts, troubles, temptations, and accusations.
And may the Lord God of my life,
and his tender mercies (which he has made sure to my soul in the everlasting covenant),
give you solid peace and consolation in the Son of his love,
through the measure of his grace and truth springing in your heart,
and staying your mind upon him.

Oh experience the seed, and the faith which springs from the seed!
For this gives victory over the enemy, and all his mysterious workings in the heart.

Your friend, in the truest and most sincere love,

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
To Catherine Pordage

[.salutation]
Friend,

In truth of heart and tender love to you,
it is upon me to answer the chief passages of your letter, as briefly as I may.

It has not been my desire to bring you out of
the esteem or into the esteem of persons.
May the Lord guide you into true judgment, and keep you from judging,
except so far as the light is raised in you which makes one able to judge.
For I have known several who have spoken most gloriously about the Scriptures,
explaining things even to admiration, who yet have been outside the Spirit of truth.
These have sparkled with the light and life of a wrong spirit,
though they themselves did not know it to be so.

It is better that one feel his unwillingness,
and wait to be made willing by the Lord, than to think himself willing,
and upon conducting his own search, judge himself to be so.
For I have thought myself willing in several cases,
assuming that if the Lord would have showed me his will, I should have obeyed.
Nevertheless,
I found it to be otherwise when the Lord came to
lay the law of his Spirit of life upon me.

Now, this I am sure of:
there is something in you that is not willing to be impoverished,
and I cannot say concerning you that you are yet willing to be separated from it.
While it is in you, it will be working in a mystery of deceit, hidden from your heart,
which you cannot possibly discern.
For it is only discerned as the seed is raised, and the pure light shines in you.
You may very well think better of yourself than indeed it is with you,
for it is hard for you (in your present state) to know
what and how you are in the sight of the Lord.
For there are great and subtle workings from the enemy in your mind,
which are against God`'s truth, and which you do not discern or avoid.
Indeed, you rather embrace these things, as if they were true and precious.

In great plainness have I written to you,
and I beseech you to be willing to have the wound kept
open in you which the condition of your soul needs,
so that it may be thoroughly searched,
and whatever is for judgment may be judged and destroyed.
In this way your soul will be everlastingly saved by the everlasting Physician,
who is wise and skillful in ministering both judgment
and mercy to everyone according to their need.

I am your friend in true, faithful, and unfeigned love and tenderness,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
25th of First Month, 1671
